### PR TITLE
Filter on multiple Access Levels, Authors, Categories, and Tags

### PR DESCRIPTION
**Pull request by jrseliga**
### Summary

Allows articles and featured articles to be filtered by multiple access levels, authors, categories, and tags in Administrator.
### Current Joomla! behavior

The article/featured articles search (filter) tools allow one choice per input, each acting as a logical AND.
### New behavior
- Each input still acts as the logical AND.
- Each choice within a input act as the logical OR with all the other choices inside of that input.
### Notes
- The module "Article - Newsflash" has an option to select multiple categories, when for example two categories are selected the module pulls all of the articles from both categories. Since articles can only exist in one category this is the only logical behavior, not only for this module, but for any instance of a multiple select category field. As a result, it could be counter intuitive to implement other multiple select filters in a different fashion.
- The content model already supported filtering based on multiple categories before this pull request was made (see condition starting at line [244](https://github.com/jrseliga/joomla-cms/blob/multiple-tags-filter/administrator/components/com_content/models/articles.php#L244)). This pull request just enables it's use in the search filters.
- Similarly it seemed intuitive to introduce virtually identical code blocks (behavior when multiple are selected) for Author, Access Levels, and Tags.
##### Articles
1. Create 3 articles:
   1. Article 1 - Category 1 - Tag 1 - Author 1 - Public
   2. Article 2 - Category 2 - Tag 1 & Tag 2 - Author 2 - Registered
   3. Article 3 - Category 2 - Tag 2 - Author 1 - Super User
2. View Articles
   1. Use Search Tools
      - Just with a simple structure like this, there is a large number of potential test cases. Please refer to the New behavior section for an overview of the filtering logic
##### Featured Articles
1. View Featured Articles
   - Repeat in Featured Articles Search Tools
#### Site

Currently the only core feature that resembles the use case for this is in the module "Articles - Newsflash". If similar "Search Tools" are developed for filtering a list of articles in the front-end, it could leverage this feature in the same way as the back-end.
##### Articles - Newsflash (module)
1. Leave Categories option at "- All Categories -" only
2. Select one tag up to n tags. Any article with any of the n tags should be displayed.
   - This can be limited by selecting multiple categories.
### Acknowledgements

Thank you to @brianteeman and @nikosdion for taking the time to help with my first pull request!

### CODE REVIEW

**Comment by jrseliga** [comment]
@brianteeman @nikosdion what steps do I need to complete for this to be approved?

**Comment by nikosdion** [comment]
For starters, this PR has merge conflicts. You need to resolve them, i.e. rebase your PR against the staging branch and fix all merge conflicts.

Afterwards, you need two successful tests. Make a call for help on social media. Usually 2-4 of your followers will have the time to test the PR.

Afterwards, a member of the Joomla! PLT (Production Leadership Team) or an assigned "open source gardener" (like Brian) will flag this as RTC (Ready To Commit) if it can be merged a.s.a.p. or "Needs review" if the PLT needs to discuss about it. I am not a member of the PLT so I do what you'll have to do: wait patiently and hope my PR makes it into the core :)

Speaking of which, I think the beta window closed last night or thereabouts. This means that our PRs which weren't already RTC at the time will have to wait. If they are major changes (like yours) or new features (like mine) will have to wait for Joomla! 3.5, hopefully in 5-7 months. I know that's a bit of a let down but I think you'd agree that Joomla! stability is above making individual developers happy – and I say that having been on the "oh, shoot, I missed the beta window _again_" train too many times to count...

**Comment by paternax** [comment]
Several combinations of selections were tested successfully. But deleting the filter entries in the search tool doesn't reset the filtering in the articles list. It has to use the clear button to reset the list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by knoby2015** [comment]
it´s ok but when i set all in normal, there will not switch to all articles. the filter is ok only the set of zeoro is not possible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by FrankyDE** [comment]
bug found :-(
the selection of the tags works great, but it does not "reload" when you deselect the tags
Example: Tag: Red: correct articles are displayed.

 
5474 - select_tagscorrect

When you delete the Tag Selection the article view is not refreshed ... normally then all articles should be displayed again.

5474 - select_tagscorrectnorefresch

Sorry, as I like the idea very much and I find it cool and pretty much straight forward.

**Comment by brianteeman** [comment]
@FrankyDE that is something that @phproberto and myself have been discussing - the ability to choose if you want it to be AND or OR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by rmittl** [comment]
The selecting tags works great and also the resfreshing. The refreshing  doesn't works, if I deselect all tags.

I expected the the OR between the tags.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by jrseliga** [comment]
@FrankyDE there was a bit of discussion above about giving the choice between AND or OR.  @nikosdion had some reservations on the idea due to how inefficient the query already is, and the implications it might have for large sites.

**Comment by jrseliga** [comment]
@all Perhaps I'm not understanding the problem when resetting a filter group. I made a simple [demonstration] (https://youtu.be/8xnGHEeT-qo) of how it functions.

**Comment by ggppdk** [comment]
Some people above stated that 
  -- "deselecting all values"
from a multi-value filter does not "refresh" / list all articles

the reason is because a select-multiple when having no values behaves like a checkbox-set, aka -NO VALUE- is submited (?? by most / all browsers ??), so the filter maintains its session state


The solution is to detect that form was submited:
(*example code)

Client side
   <input type="hidden" name="form_submited" value="1"/>

Server side:
 $form_submited = JRequest::getVar('form_submited');
 $FILTERNAME = $form_submited ?
   JRequest::getVar('FILTERNAME')  :
   $app->getUserStateFromRequest( $option.'.'.$view.'.FILTERNAME', 'FILTERNAME',  false, 'array' );


please use above JInput instead of JRequest, etc, etc ...

the above solution is simple, if form was submitted then do not use session for getting the filter value

**Comment by nikosdion** [comment]
Hi Giorgo,

This approach is wrong on many levels. If you think hard about it you will see the subtle but grave bugs you have introduced.

Besides, what you really want is adding a “None” option to your multiselect lists. Trying to automate this behaviour has the side-effect of affecting ALL FILTERS, no matter their GUI type. If you let your business model know how your interface behaves you are coupling the GUI with the business logic. This is a grave mistake and you’re already half-way committing it.

So, no, don’t do that. Really. If you value your sanity don’t do it. Trust me. I’ve written my fair share of crappy code I had to maintain (read: rewrite from scratch, coursing my past self) later on.

Best regards,

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by ggppdk** [comment]
Hello

i will not agree or disagree with this

but mostly what i did is

1. explain --why/what-- is happening

2. used a common (indepedent to joomla) suggested approach, of detecting if form was submitted and not using the session

-- i don't say it is a best choise, but i don't think it is as harmful as you imply

about adding extra options to the multiselect, i am not sure if this best, since 
- browsers
- and chosen/select2 JS libs
treat it differently than how single select is treated

i think it will cause more work and also can you tell how to make this "none" value invisible without hacking choosen 2 JS ? e.g. via CSS , 

or we will need some extra JS to do this
or does Joomla / choosen already have this feature ??

**Comment by nikosdion** [comment]
If submitting a form is supposed to reset the filters you don’t need a user session. If you don’t save the filter values in the user session you need to explicitly pass them in each and every request which involves form submission. This includes using the Save, Save & Close, Save & New, Cancel buttons. This is not the intended behaviour.

Please let me elaborate a bit on architecture and explain why your code is both in the wrong place and unfit for inclusion in a framework.

Handling the deselection of multiselect lists is something that would ideally be handled in your Controller, only for fields you know are multiselects and only under the exact conditions of your business logic where this should be allowed. Moving this code into the Model is problematic because the Model must only be aware of its state, not the GUI. Applying hard resets of the model state based on the existence or the lack of existence of a variable is deeply problematic and can lead to abuse. On the other hand, the Controller is aware of the shape of the data it receives and responsible for transforming it into a Model state. Therefore the Controller is the architecturally correct place to decide whether to reset the Model’s data based on the incoming request, NOT the Model itself. The Controller is aware of the request, the Model must not be aware of it. You put your code in the Model, therefore you are violating the important architecture principle on separation or responsibilities.

So, you need to move your code in your Controller. Your code is not something which can be added to FOF since it’s not generic enough: it depends on the GUI representation of the data. As you correctly pointed out using Chosen vs native multiple selection lists also changes both the GUI representation and the submitted data. With Chosen it is possible to select no values and the field will not be submitted at all. With native multiple selection lists you need to add a “None” option with an appropriate (e.g. -1, 0 or empty string) value manually. Therefore the Controller code to handle no selection is dependent on both the field name (you must only act on multiple selection fields!) and its GUI representation (Chosen vs native). Therefore this code is dependent on your application, ergo not generic and inappropriate for inclusion in the framework.

I hope that this analysis gives you a good direction into what you should be doing (and why), as well as why I’m not going to include such code in FOF itself.

**Comment by jrseliga** [comment]
I've tested this across Firefox (Windows/Linux), Chrome (Windows/Linux), and IE 10 and am not experiencing any issues with deselecting. Perhaps this is a browser issue? IE 9 or older?

**Comment by nikosdion** [comment]
Please ignore my replies (I removed them now). A mail filter fail made me think they were about a completely different project. Receiving too much email can do that... Sorry!

**Comment by jrseliga** [comment]
Circling back to this, does anyone have more information on the environment their experiencing the issue with? Again I made a [demonstration] (https://youtu.be/8xnGHEeT-qo) for more clarity on how it should be working.

**Comment by ggppdk** [comment]
Indeed,
you clearly show it to work, sorry i don't have time to test,
can someone else do it ?

**Comment by Bakual** [comment]
This will also need some tests on PostgreSQL and MSSQL databases to make sure nothing breaks there.

**Comment by ggppdk** [comment]
I have tested firefox/chrome/ie11, seems to works properly, when clearing via clear button and by removing all selected options too.

Also article manager URLs seem to work properly

...&filter[access]=1

...&filter[access][]=1&filter[access][]=2

...&filter[somefiltername]=aaaa
'access' filter and other filters are cleared
thus #6916, which links from catergory manager towards the article manager seem to work properly

**Comment by roland-d** [comment]
@alikon can you take a look if this is OK for postgres and mssql? Thank you.

@jrseliga Can you please fix the merge conflicts so we can get it ready for 3.6? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by brianteeman** [comment]
@jsreliga will you be updating this to fix the merge conflicts. If we dont get a reply then this will be closed in a few weeks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5474">issues.joomla.org/joomla-cms/5474</a>.</sub>

**Comment by ggppdk** [comment]
@jrseliga 

> Circling back to this, does anyone have more information on the environment their experiencing the issue with? Again I made a demonstration for more clarity on how it should be working.

There were some bogus PHP versions (with suhosin ?),
that were submit select multiple as empty array, instead the array did not exist at all in the posted data

**Comment by roland-d** [comment]
I have someone working on this, will know next Friday if it is finished or not.

**Comment by brianteeman** [comment]
Closed as we have a NEW pr #11517

**Pull request closed without merging**
