### PR TITLE
Restore cache feature in category module

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for pr #39527.

### Summary of Changes
Restores the cache feature which got lost by the merge from #39527.

### Testing Instructions
- Create an instance of the module Articles Category
- Open the front end

### Actual result BEFORE applying this Pull Request
It shows some articles.

### Expected result AFTER applying this Pull Request
It shows some articles.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 115a158d5941441c8a8a689ac50777bc92ebb81b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40316">issues.joomla.org/tracker/joomla-cms/40316</a>.</sub>

**Comment by laoneo** [comment]
Can you have another look as I basically moved the load from cache function to the abstract module dispatcher.

**Comment by laoneo** [comment]
Reverted the deprecation change and made a new pr in #40325.

**Comment by joomdonation** [comment]
This works. However, the code looks a bit mess. I suggest to move the code which get Category ID ($idBase variable in current code) to a separate private method `getCategoryId` so that the method `getLayoutData` look cleaner.

**Comment by laoneo** [comment]
I would leave it as it is as it is then more inline with the previous function, so other developers will recognize that the logic from the old module file goes into the dispatcher.

**Comment by laoneo** [comment]
@joomdonation can you give this a test, so we can merge and then @carlitorweb can update his other pull requests the same way?

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 33dba3f7d5d9a758d83dc7b3909013904ae194ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40316">issues.joomla.org/tracker/joomla-cms/40316</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40316">issues.joomla.org/tracker/joomla-cms/40316</a>.</sub>

**Pull request merged**
