### PR TITLE
[fix] fixing limit.start state in JModelList

### PR DESCRIPTION
**Pull request by Disaron**
Fixing pagination bug according to [this](https://github.com/joomla/joomla-cms/pull/8475#issuecomment-157639860)

### CODE REVIEW

**Comment by Bakual** [comment]
Setting RTC based on review.

**Comment by rdeutz** [comment]
Not sure if that is right. If you have SEF on then start is used and when off then limitstart. So I think we need to test that, wouldn't merge that on review

**Comment by rdeutz** [comment]
But if we don't set $limit it is always 0 so $limitstart is also 0, doesn't makes sense either.

**Comment by Disaron** [comment]
>But if we don't set $limit it is always 0 so $limitstart is also 0, doesn't makes sense either. 
But we set $limit, this fix set $start too. For what reason we set $start to $limit ("warm" vs "soft")?

**Comment by Disaron** [comment]
For example: we have list.limit = 20 and list.start = 0. We set list.start = 20.
Not fixed code must do this:
list.start = 0 (because we don't assign list.start)
list.limit = 20 (because we assign only $limit)
Finally we have first 20 records instead second 20.

**Comment by rdeutz** [comment]
@Disaron it is not that there isn't a problem to fix, but around this part of the code looks odd and doesn't makes sense at all

**Comment by Disaron** [comment]
@rdeutz however it fixes bug described [here](https://github.com/joomla/joomla-cms/pull/8475#issuecomment-157708580)
And base code is really really strange and not logical.

**Pull request merged**
