### PR TITLE
[4] Code Cleanup

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 655605b87b9be8879c04916c2ad7942227788eb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35123">issues.joomla.org/tracker/joomla-cms/35123</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 655605b87b9be8879c04916c2ad7942227788eb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35123">issues.joomla.org/tracker/joomla-cms/35123</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35123">issues.joomla.org/tracker/joomla-cms/35123</a>.</sub>

**Comment by richard67** [comment]
Thanks

**Pull request merged**
