### PR TITLE
[4.0] Remove duplicated COM_MEDIA_INCREASE_GRID string

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

remove duplicated COM_MEDIA_INCREASE_GRID

### Testing Instructions

review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a35987e7821f2b02d31f1a5f8df9b577d92f5a97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24580">issues.joomla.org/tracker/joomla-cms/24580</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a35987e7821f2b02d31f1a5f8df9b577d92f5a97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24580">issues.joomla.org/tracker/joomla-cms/24580</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24580">issues.joomla.org/tracker/joomla-cms/24580</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
