### PR TITLE
[4.0] Clean up the editors

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Fix various bugs,
- Remove deprecated code (php side)
- Remove deprecated code (js side)

### Testing Instructions
Apply patch, select none as your editor check that all the buttons work correctly and the content is saved on clicking the save button.

Repeat for Codemirror and TinyMCE

### Documentation Changes Required
nope!

@wilsonge @mbabker please review the PHP part

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f0ec2b15d97f6d1b24c5a3f3e7d8d216ef782e8b<br /><br />Test using None, Codemirror and TinyMCE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15371">issues.joomla.org/tracker/joomla-cms/15371</a>.</sub>

**Comment by C-Lodder** [comment]
- [x] Codemirror
- [x] None
- [ ] TinyMCE

**Comment by dgt41** [comment]
@C-Lodder can you test tinymce again?

**Comment by C-Lodder** [comment]
Will do in an hour. Got some work to finish up

**Comment by dgt41** [comment]
I will redo this in smaller chunks

**Comment by wilsonge** [comment]
Sorry this largely looked ok. But I didn't get time to test what happened to tiny on upgrade when we removed all the legacy config handling code. As I said to you on skype - I don't mind if some things change. But it needs to not be totally screwed (which is what I needed to check)

**Pull request closed without merging**
