### PR TITLE
hiddenFieldsets & configFieldsets needs to be defined

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #16854 

### Summary of Changes

hiddenFieldsets & configFieldsets needs to be defined in any case

### Testing Instructions

```php
<?php $this->set('show_options', 0) ?>
<?php echo JLayoutHelper::render('joomla.edit.params', $this); ?>
```

### Expected result

No error

### Actual result

see #16854 

### Documentation Changes Required

none

please test @asika32764

### CODE REVIEW

**Comment by asika32764** [comment]
Another error message if we didn't set `hiddenFieldsets` in view.

```
Notice: Undefined property: ContentViewArticle::$hiddenFieldsets
```

Maybe use this?

```php
$hiddenFieldsets = $displayData->get('hiddenFieldsets') ?: array();
```

**Comment by zero-24** [comment]
pushed

**Comment by asika32764** [comment]
Fixed 👍

**Comment by richard67** [comment]
@asika32764 Please mark your test result as success by using the "Test this" button here: [https://issues.joomla.org/tracker/joomla-cms/16856](https://issues.joomla.org/tracker/joomla-cms/16856 "https://issues.joomla.org/tracker/joomla-cms/16856")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16856">issues.joomla.org/tracker/joomla-cms/16856</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
altered test successfully by @asika32764 in Issue Tracker.

**Comment by asika32764** [comment]
I have tested this item :white_check_mark: successfully on ba91e12b5971c471d684c81f301fb8e1522b0065<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16856">issues.joomla.org/tracker/joomla-cms/16856</a>.</sub>

**Comment by zero-24** [comment]
Would be great to get another tester here?

**Comment by Quy** [comment]
`!empty($configFieldsets)` and `!empty($hiddenFieldsets)` can be removed here:

https://github.com/zero-24/joomla-cms/blob/c9419cfd5440d53c1ca35759ae5d2c6ecee7c252/layouts/joomla/edit/params.php#L85

Also which file to add the code to test?

**Comment by brianteeman** [comment]
@zero-24 I have tried to replicate the error message and can't

**Comment by zero-24** [comment]
How did you tested it?

### Testing Instructions

Place this code
```php
<?php $this->set('ignore_fieldsets', false); ?>
<?php $this->set('show_options', 0) ?>
<?php echo JLayoutHelper::render('joomla.edit.params', $this); ?>
```

enable the debugger and set a break point here:
https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/edit/params.php#L57

Run the code (login and try to edit an article).
Notice that the variable $hiddenFieldsets is not instanciated.
apply this patch
try again

This does not throw a hard error but it is a bug that this patch is going to fix ;)

**Comment by brianteeman** [comment]
i tested it from the limited information available in the initial post. still not clear if this is frontend or backend or both

**Comment by asika32764** [comment]
This issue is at the backend edit page if we use custom fields. It will not shows fatal error but notice message if we set error_reporting to development.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1e8529d2f6a211aad91f0db96e5813e26109409b<br /><br />Open `\components\com_content\views\form\tmpl\edit.php`
Add `<?php $this->set('show_options', 0); ?>` on line 102.
Edit an article on the frontend.

Without PR:
```
Notice: Undefined variable: hiddenFieldsets in \layouts\joomla\edit\params.php on line 57

Warning: in_array() expects parameter 2 to be array, null given in \layouts\joomla\edit\params.php on line 57
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16856">issues.joomla.org/tracker/joomla-cms/16856</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16856">issues.joomla.org/tracker/joomla-cms/16856</a>.</sub>

**Pull request merged**
