### PR TITLE
onUserLoginFailure needs to catch failure to write to log file during failed login

### PR DESCRIPTION
**Pull request by GeraintEdwards**
Pull Request for Issue #11869 

### Summary of Changes
Added Try/Catch around the call to JLog::add so that failed attempt to login doesn't throw unhelpful error screen but instead returns visitor to login page as they would if the log file was writeable.

### Testing Instructions
Install patch
Login in the backend with incorrect password or missing password

### Expected result
return to login page with message about failure to login

### Actual result
Now it does this instead of the error page with message about failure to write to log file

### Documentation Changes Required
none

### CODE REVIEW

**Comment by mbabker** [comment]
This just needs the code style issues to be addressed (we use tabs instead of spaces), otherwise looks good to me.  Thanks!

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on 2053caabcf7243e12c885401db2b39774c71c0b9<br /><br />Now Joomla! redirects to the backend login page and shows the errors in the messages area above the login form.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16475">issues.joomla.org/tracker/joomla-cms/16475</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2053caabcf7243e12c885401db2b39774c71c0b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16475">issues.joomla.org/tracker/joomla-cms/16475</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
