### PR TITLE
[4] revert and improve #32013 to use htmlspecialchars to prevent XSS

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

[4] revert and improve #32013 to use htmlspecialchars on user supplied placeholders and use non html entity for the bullet to overcome the entity being destroyed by htmlspecialchars

### Testing Instructions

Look at Joomla Global Configuration Database Password field - ensure placeholders are `•` and not asterisks or badly formatted

### Actual result BEFORE applying this Pull Request

Potential XSS on any non-core use of this field with a user supplied `$hint` and `$lock` set to no.

### Expected result AFTER applying this Pull Request

In line with all other user supplied placeholders, htmlspecialchars is applied to prevent XSS injections. 

### Documentation Changes Required

None.

// @brianteeman

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 2fc47847466029647fbe28059144d844d7c93bbc<br /><br />I see the bullets in the password field and the two changes to the layout file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32044">issues.joomla.org/tracker/joomla-cms/32044</a>.</sub>

**Comment by PhilETaylor** [comment]
Merged back 4.0-dev and fixed cs, and reverted back to bootstrap 5 version. Ready to test again.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 40ddfeede8f184c59d2f0a4369f0021598a61cd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32044">issues.joomla.org/tracker/joomla-cms/32044</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 40ddfeede8f184c59d2f0a4369f0021598a61cd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32044">issues.joomla.org/tracker/joomla-cms/32044</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32044">issues.joomla.org/tracker/joomla-cms/32044</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
