### PR TITLE
[4.0] [Atum] Styling for user note options

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #17130

### Summary of Changes

Just some tweaks to improve the styling to access user notes

@brianteeman The first item in the dropdown says "**Show notes list for this user**". The string seems a little long for my liking. Are you happy to change to just "**Show notes list**"?

### CODE REVIEW

**Comment by brianteeman** [comment]
Much better - and yes that lang change is good to go for now

Although to be honest I am not sure why we have both the list and the popup

**Review by brianteeman — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bdd18b862cb63a13d1e4ddd0d26722f2123dafd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17152">issues.joomla.org/tracker/joomla-cms/17152</a>.</sub>

**Comment by C-Lodder** [comment]
@wilsonge

**Comment by zero-24** [comment]
```
FILE: ...la/joomla-cms/administrator/components/com_users/helpers/html/users.php
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 104 | WARNING | Line exceeds 150 characters; contains 180 characters
--------------------------------------------------------------------------------
```

http://213.160.72.75/joomla/joomla-cms/6934 ;)

**Comment by C-Lodder** [comment]
@zero-24 oops, fixed

**Comment by zero-24** [comment]
👍

**Pull request merged**
