### PR TITLE
[4.0] replacing Bootstrap popover on com_content by already implemented css only version

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #33296 .

### Summary of Changes

This PR will replace the Bootstrap popover by the already implemented css only version of tooltip. 
```
<button blablabla aria-labelledby="unique-id">blabla</button>
<div id="unique-id" rel="tooltip">text</div>
```

### Testing Instructions

- Joomla 4 with blog sample data
- Go to Content > Articles and hover Stage, Featured or Status icon
- see the result
- Apply this PR and repeat step 2 and 3 

### Actual result BEFORE applying this Pull Request

Schermafbeelding 2021-05-05 om 12 03 04

When workflow is enabled the hover on Featured and Status is not working on my machine.

### Expected result AFTER applying this Pull Request

Schermafbeelding 2021-05-05 om 11 35 47
Schermafbeelding 2021-05-05 om 11 35 51
Schermafbeelding 2021-05-05 om 11 35 56

### CODE REVIEW

**Comment by brianteeman** [comment]
Please change click to select. We don't use click as you can't click on a phone etc

**Comment by brianteeman** [comment]
Please use tabs not spaces for indentation

**Comment by brianteeman** [comment]
There is a featured button in com_contact as well. No preference on which is better but they should be consistent with each other please

**Comment by hans2103** [comment]
> There is a featured button in com_contact as well. No preference on which is better but they should be consistent with each other please

You are right @brianteeman... I've changed it from anchor to button now.

**Comment by brianteeman** [comment]
Please review the number of tabs
image

image

**Comment by hans2103** [comment]
> Please review the number of tabs

damn my settings in PHPStorm.

**Comment by brianteeman** [comment]
please recheck the tabs. if you look at the file here on github then you can easily see the multiple errors

**Comment by hans2103** [comment]
> please recheck the tabs. if you look at the file here on github then you can easily see the multiple errors

All checks are okay now... according to Drone

**Comment by brianteeman** [comment]
I wrote very specifically what you need to do

**Comment by hans2103** [comment]
and I followed the instructions replacing spaces with tabs at the places where Drone complained.

**Comment by hans2103** [comment]
The visually-hidden text can be removed. 

https://inclusive-components.design/tooltips-toggletips/#tooltipasprimarylabel
Good catch @chmst

**Comment by brianteeman** [comment]
@hans2103 its not just drone that you have to look at. You need to look at the code. Drone only reports on spaces instead of tabs. It doesn't report on too many or too few tabs

## Examples
image

image

image

**Comment by brianteeman** [comment]
@quy maybe you can explain better what needs to be done

**Comment by hans2103** [comment]
@brianteeman thank you for the example. I will revert those changes and only commit my intended changes/additions

**Comment by brianteeman** [comment]
Those are only examples and not an exhaustive list. It is really obvious what needs correcting when you look at the code here on github

**Comment by hans2103** [comment]
what I have done... 
- copied the content from all changed php files from branch 4.0-dev
- reapplied my changes

This should do the trick.

**Comment by hans2103** [comment]
I'm getting crazy... I do see code style changes to parts I did't touch.

**Comment by brianteeman** [comment]
You must have automatic code formatting set in your ide

**Comment by hans2103** [comment]
Thought I did.... and followed the steps as explained in PHPStorm.

**Comment by hans2103** [comment]
Seems that my PHPStorm fails like a charm. 
Back to vi editor. :-)

**Comment by chmst** [comment]
Thanks for working on this. Glad to get rid of the Popovers

For further improvements:  https://github.com/joomla/joomla-cms/issues/33575

**Comment by brianteeman** [comment]
@chmst I would create a new issue for this. And yes I agree its a long standing problem that would be good to resolve

**Comment by chmst** [comment]
@brianteeman Will do - then we can do this in smaller steps.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 76b6914089c0463b482a79e9fcc3e6879195af3f<br /><br />Sorry forgot to record a test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33557">issues.joomla.org/tracker/joomla-cms/33557</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 76b6914089c0463b482a79e9fcc3e6879195af3f<br /><br />Thank you! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33557">issues.joomla.org/tracker/joomla-cms/33557</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 76b6914089c0463b482a79e9fcc3e6879195af3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33557">issues.joomla.org/tracker/joomla-cms/33557</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33557">issues.joomla.org/tracker/joomla-cms/33557</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
