### PR TITLE
5.2 Improve Contrast of selected Options in Darkmode for issue #44203

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue #44203 .

### Summary of Changes
Issue had been closed but I think its valid

### Testing Instructions
Create a new task
Set Execution Rule to Cron Expression (Advanced)
Select some hours minutes and so and save

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on b62a2c6e010383956da5dcaa5a61240ac4a0e07d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44211">issues.joomla.org/tracker/joomla-cms/44211</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b62a2c6e010383956da5dcaa5a61240ac4a0e07d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44211">issues.joomla.org/tracker/joomla-cms/44211</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44211">issues.joomla.org/tracker/joomla-cms/44211</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for your contribution @coolcat-creations!

**Comment by coolcat-creations** [comment]
Thank you, @Hackwar, for merging :-)

**Pull request merged**
