### PR TITLE
Fix redirect updating new_url value

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue #36862 .

### Summary of Changes
Remove the direct changes to the redirect object and updating of new_url 

### Testing Instructions
Without this PR add a redirect and publish it into com_redirects, for example:

Source:
/my-custom-error 
Destination
/my-real-live-page

access 

/my-custom-error?query_junk_here

### Actual result BEFORE applying this Pull Request

you are redirected to:

/my-real-live-page?query_junk_here

Try it again and you will see you are redirected to:

/my-real-live-page?query_junk_here?query_junk_here

Because before this PR the DB is updated.

### Expected result AFTER applying this Pull Request

You are redirected to: /my-custom-error?query_junk_here 
But your redirect in the database is not changed.

### Documentation Changes Required

Back-port to J3 too.

### CODE REVIEW

**Comment by zero-24** [comment]
> Back-port to J3 too.

Could you do a PR there so this can be tested there and merged up? @tonypartridge

**Comment by Quiviro** [comment]
I have tested this item :white_check_mark: successfully on 514caa3e81c97d3d1fb411a1fc4d84d038fb40b0<br /><br />It works as expected in new redirections created after applying the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36873">issues.joomla.org/tracker/joomla-cms/36873</a>.</sub>

**Comment by zero-24** [comment]
I have just did the backport to 3.10 here: https://github.com/joomla/joomla-cms/pull/36951 idially its tested there and merged up from there.

**Comment by Quy** [comment]
Closing as it will be upmerged from v3.10. Thank you!

**Pull request closed without merging**
