### PR TITLE
[4.0] Categories don't contain only articles

### PR DESCRIPTION
**Pull request by Bakual**
Batch copying a category allows to reverse order all articles in the selected categories. But categories are not only for articles. It can be anything. So "items" is a better term.

### Summary of Changes
Changing the string to order items, not articles.

### Testing Instructions
Go to any categories manager (eg articles categories, banner categories, contact categories), select at least one category and then select "Batch" from the "Actions" dropdown. 

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
Are you sure that the bug is not the text but that it should only be shown when the context is com_content? In J3 it only displays in com_content

**Comment by Bakual** [comment]
Oops, that could be the case. I just assumed it works, but didn't test it. I'll check that and close this PR in the meantime.

**Comment by Bakual** [comment]
@brianteeman You're right, it only affects articles. But the bug is also in J3, as it shows in all category types, not only com_content. It probably shouldn't have been implemented in the com_category code 😄

**Comment by Bakual** [comment]
New PR: https://github.com/joomla/joomla-cms/pull/33190

**Pull request closed without merging**
