### PR TITLE
[4.2] Code style for webauthn plugin

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Code style for changes in #37910

### Testing Instructions

Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0054c27e7ee0449107e7ae42c8a1e3b44a85bcc<br /><br />Ok by review, and code style checks still succeed in drone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38191">issues.joomla.org/tracker/joomla-cms/38191</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a0054c27e7ee0449107e7ae42c8a1e3b44a85bcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38191">issues.joomla.org/tracker/joomla-cms/38191</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38191">issues.joomla.org/tracker/joomla-cms/38191</a>.</sub>

**Comment by richard67** [comment]
@HLeithner Any idea why PHPCS doesn't complain about the code style in that file without this PR?

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
