### PR TITLE
s/validatng/validating

### PR DESCRIPTION
**Pull request by PhilETaylor**
typo

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 56259e1078d121f2ca95f4aef73730ca889c5fb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38482">issues.joomla.org/tracker/joomla-cms/38482</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 56259e1078d121f2ca95f4aef73730ca889c5fb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38482">issues.joomla.org/tracker/joomla-cms/38482</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38482">issues.joomla.org/tracker/joomla-cms/38482</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Pull request closed without merging**
