### PR TITLE
[4.0] blog sample data

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects two instances of color in the displayed text

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6a39e802edfb51dfc6b0a8b1f118570dfe4c4332<br /><br />Tested successfully in Beta6-dev of 24 November.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31478">issues.joomla.org/tracker/joomla-cms/31478</a>.</sub>

**Comment by richard67** [comment]
Hmm, we fixed that already in the Cassiopeia repository.

**Comment by brianteeman** [comment]
@richard67 so merge it back. its pointless at this point keeping multiple rep[ositories and expecting people to know what is in each. especially as the sample data plugin is sample data for joomla and not sample data just for one template ;)

**Comment by richard67** [comment]
> ... and expecting people to know what is in each.

@brianteeman I don't expect that in general. Just in this case I thought maybe you might have remembered we handled it there because you had commented on it.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6a39e802edfb51dfc6b0a8b1f118570dfe4c4332<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31478">issues.joomla.org/tracker/joomla-cms/31478</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31478">issues.joomla.org/tracker/joomla-cms/31478</a>.</sub>

**Comment by brianteeman** [comment]
If I remembered what I did yesterday I am happy

**Comment by richard67** [comment]
I would sometimes be happy if I didn't remember what I've done the day before, but that's another issue ;-)

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
