### PR TITLE
Update default_results.php

### PR DESCRIPTION
**Pull request by diddipoeler**
there was a bug.

Pull Request for Issue # .

### CODE REVIEW

**Comment by ghost** [comment]
@diddipoeler thanks for Contribution. Can you please explain (Summary of Changes
Testing Instructions, ...) PR so People know what and how to Test?

**Comment by RonakParmar** [comment]
@diddipoeler  Can you please write what was the bug and what you have fixed? And also provide testing instruction to test the PR.
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17061">issues.joomla.org/tracker/joomla-cms/17061</a>.</sub>

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by Quy** [comment]
Duplicate of merged pr #17401

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17061">issues.joomla.org/tracker/joomla-cms/17061</a>.</sub>

**Pull request closed without merging**
