### PR TITLE
article layout override from category

### PR DESCRIPTION
**Pull request by shamsbd71**
Joomla has the ability to set the articles details page layout from category menu item. but it wasn't implemented. just add these xml and its gonna work perfect.
## Before

image
## After

image

### CODE REVIEW

**Comment by ghazal** [comment]
Test OK.
I hadn't figured out it was missing. But actually, it is.
TKS.

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on 96822b7bffd57b6b7845b1c40fc6fd6dea621cb1<br /><br />TEST OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :red_circle: unsuccessfully on 96822b7bffd57b6b7845b1c40fc6fd6dea621cb1<br /><br />I added a cuatom template override and it doesn´t appear in the list. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by designbengel** [comment]
Btw: We tested also when adding an override for an article, and that worked. But that seems not logical to me, because i expect to be able to choose a category **list** override there? 
Maybe we need then two fields there 1) List view layout and 2) Article view layout<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on 96822b7bffd57b6b7845b1c40fc6fd6dea621cb1<br /><br />Alternative Layout is working for Articles. It's a bit confusing. It should be called Alternative Layout for Articles.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by webnet-assmann** [comment]
Alternative Layout is working for Article. It's a bit confusing. It should be called Alternative Layout for Articles.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by shamsbd71** [comment]
Yes i agree that if we change the label to **Alternative Layout for Articles** would be more clear.
Need to add the language then. I'll add the correct language.

**Comment by conconnl** [comment]
@shamsbd71 are all the comments integrated in the patch?
If so, I and hopefully others can test this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by shamsbd71** [comment]
@conconnl yes it is.
thanks

**Comment by schmidtpaddy** [comment]
I have tested this item :red_circle: unsuccessfully on cdf7dc478467539968116f10dd72b6824fdf5ff7<br /><br />field alternative layout didn't appear @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by shamsbd71** [comment]
@schmidtpaddy there are two files, please try both. you have applied only language file changes.
https://github.com/joomla/joomla-cms/pull/8579/files
thanks

**Comment by Schmidie64** [comment]
tested: 
- install plugin successfully
- everything worked well
@icampus

**Comment by Schmidie64** [comment]
I have tested this item :white_check_mark: successfully on cdf7dc478467539968116f10dd72b6824fdf5ff7<br /><br />tested: 
•install plugin successfully
•everything worked well @icampus 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by roland-d** [comment]
@schmidtpaddy Can you test this once more please? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by Sieger66** [comment]
Alternative Layout for Article ist Display and is a good feature but 
I have testet #8579 the "Alternative Layout for Article" and see this problems (with and without SEO):

Example:
You make two article-category-list-menuitems  A  B
both for the same article-category 
article-category-list-menuitem  A in "Alternative Layout for Article" with Template-Override 
B in "Alternative Layout for Article" without Template-Override 

If you click on menu-item A 
and then click one of the article and you come to article with Template-Override

If you click on menu-item B 
and then click one of the article and you come also to article with Template-Override

or vice versa both without Template-Override

The article come allways with the self view and not always with the view from the menuitem-"Alternative Layout for Article" 

Second problem:

For example go to article-category-list-menuitem  A -> Details -> Template Style and change to an other Template with Template-Override
then go to List Layouts -> Alternative Layout for Article   and see the not correct list in.
Then click the "Save"-Button and go Back to List Layouts -> Alternative Layout for Article  and see the correct list now.

I hope this is helpful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/joomla-cms/8579</a>.</sub>

**Comment by shamsbd71** [comment]
@Sieger66 

> You make two article-category-list-menuitems A B
both for the same article-category 

This is wrong! you should not create the same menu twice and it's not practical either.

If you check Joomla routing, you are creating confusion for the routing not for the menu item.

This setting works based on menu item id. so when you have duplicate menu itemid for the same category, you are confusing yourself :(

thanks

**Comment by Sieger66** [comment]
> This setting works based on menu item id. so when you have duplicate menu itemid for the same category, 

In the example from me above i have **not** the same menu itemid for the same article-category !
In menu-item A is an other menu-item-id as in menu-item B

For example with SEO:
Menu-item A:  /extensions/components/content-component/article-category-list.html

different to 

Menu-item B:  extensions/components/content-component/article-category-list-2.html

The self single article in **both** article-category-lists 
extensions/components/content-component/article-category-list/8-beginners.html
( Always with "Template" from menu-item A )

Maybe this is a bug in Joomla.

Because if i go to  
extensions/components/content-component/article-category-list**-2**/8-beginners.html
Then i see the self single-article with the "Template" from menu-item B

Thats logical and i think the bug is the wrong link in the article-category-list.

**Comment by microtribe** [comment]
I have tested this item :white_check_mark: successfully on cdf7dc478467539968116f10dd72b6824fdf5ff7<br /><br />I tested this - first to confirm that the Alternative Layout selector was not available. Then I used the Patch Tester to install the patch. Then created a Category List menu item. Then check to see if the Alternative Layout selector was visible - it was. Then I created an article alternative layout override. Then I visited the Category List menu item, and the Alternative Layout I created was also visible and selectable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/tracker/joomla-cms/8579</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on cdf7dc478467539968116f10dd72b6824fdf5ff7<br /><br />All works like m wrote above, but "Show Votes in List" and "Show Ratings in List" isn't shown anymore after Patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/tracker/joomla-cms/8579</a>.</sub>

**Comment by mbabker** [comment]
This PR needs to be synchronized with the current development branches and the issues addressed for it to be reviewed.

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 22th June 2017.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8579">issues.joomla.org/tracker/joomla-cms/8579</a>.</sub>

**Comment by coolcat-creations** [comment]
How to sync it? should i create a new PR on the latest staging and reference it?

**Comment by brianteeman** [comment]
@coolcat-creations yes that will be the easiest in this case

**Comment by brianteeman** [comment]
closed please see #16755

**Pull request closed without merging**
