### PR TITLE
Phpcsfix

### PR DESCRIPTION
**Pull request by brianteeman**
This PR is in draft and is here to show how many "codestyle" pull requests could be saved if we just enabled the code style checker and fix across the repo. Without using this php-cs-fix and enabling the php codestyle checks across the entire repo **we are all wasting our time with hundreds of pull requests that can and should be automated**

This is created with just a subset of the tests from #33908 as an example.
```

		    'encoding' => true,
		    'elseif' => true,
		    'single_blank_line_at_eof' => true,
		    'blank_line_after_namespace' => true,
		    'line_ending' => true,
		    'lowercase_keywords' => true,
		    'single_import_per_statement' => true,
		    'no_spaces_inside_parenthesis' => true,
		    'single_line_after_imports' => true,
		    'no_trailing_whitespace' => true,
		    'no_whitespace_before_comma_in_array' => true,
		    'whitespace_after_comma_in_array' => true,
		    'no_blank_lines_after_class_opening' => true,
		    'phpdoc_trim' => true,
		     'single_blank_line_before_namespace' => true,
		    'no_whitespace_in_blank_line' => true,
```

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Flogging a dead horse. 

"We refuse to make these changes because it makes our job [The maintainers] difficult merging code"...

**Comment by brianteeman** [comment]
Thats simply not true or remotely what was said. But keep on repeating it and creating manual prs that can simply be done automatically

**Comment by PhilETaylor** [comment]
Facts will always be facts despite you trying to manipulate them. I'll find the reference eventually.

Here is an example working workflow you can use - or not - within 30 seconds... 
https://github.com/joomla/joomla-cms/pull/35267/
https://github.com/joomla/joomla-cms/pull/35267/checks?check_run_id=3384236115

Screenshot 2021-08-20 at 18 14 49

**Comment by brianteeman** [comment]
@bembelimen @wilsonge

**Comment by PhilETaylor** [comment]
history in https://github.com/joomla/joomla-cms/issues/33342

>. I'll find the reference eventually. 

rdeutz 

https://github.com/joomla/joomla-cms/pull/33357#issuecomment-827627256
> Changing a lot of files will make upstream merges more complicated as they are already. I don't will mege any of the code style PRs.  We can revisit this after we have released 4.0.0"

> A good moment could be before 4.0.0, I will put it on the agenda of the next meeting.

> It's not so easy as it looks, it will break all PRs. You need to find a good moment to make this change, because you change all files. You need to coordinate this with our CI. And there might be other problems I have forgotton.

> At the end of the day it is a political decision.


LMAO:

Screenshot 2021-08-20 at 18 21 04

**Comment by brianteeman** [comment]
all of which confirms my post. but you never let facts get in the way and prefer to bully people.

**Comment by brianteeman** [comment]
i am closing this so i dont have to see ay more spam

**Comment by PhilETaylor** [comment]
Toxic Teeman strikes again.

**Pull request closed without merging**
