### PR TITLE
Add class deafult to homepage menu item

### PR DESCRIPTION
**Pull request by artur-stepien**
That should be right from the start. Many themes are displaying default menu item differently or disables at all.
#### Summary of Changes

This adds a **default** class for a homepage/default menu item in current language.
#### Testing Instructions

Just check if menu item containing item marked as default/homepage has class **default**.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 5eacf43ca0fb2486df8c11de33622035cfee7d8a<br /><br />Fatal error: Call-time pass-by-reference has been removed in /modules/mod_menu/helper.php on line 191<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by artur-stepien** [comment]
> Fatal error: Call-time pass-by-reference has been removed in /modules/mod_menu/helper.php on line 191

Fixed that. Will check that all and give and comment again.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 25f47752694a14d78ea84307c691d9599d09429a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by artur-stepien** [comment]
Yup, now works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 25f47752694a14d78ea84307c691d9599d09429a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by Djshubh** [comment]
I have tested this item :red_circle: unsuccessfully on 25f47752694a14d78ea84307c691d9599d09429a<br /><br />    Undefined property: stdClass::$anchor_rel in /opt/lampp/htdocs/joomla-test/modules/mod_menu/tmpl/default_url.php on line 15
   
    this message is shown with every menu component after applying the patch on my testing site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by artur-stepien** [comment]
First of all if you are about to test this, clone a full branch. Not only some files. If there is something wrong with your Joomla instance (for example few patches with conflicts) it will be like this. Clone a full system then test it again please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9295">issues.joomla.org/joomla-cms/9295</a>.</sub>

**Comment by rdeutz** [comment]
@artur-stepien could you check the merge conflicts, thanks

**Pull request merged**
