### PR TITLE
[4.2] Post-installation messages UX #38064 code optimization

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for PR #38064 .

### Summary of Changes

- Use short array syntax https://github.com/joomla/joomla-cms/pull/38064#discussion_r898053882
- Replace deprecated method getDbo() by getDatabase() #38023
- Replace `where` with `whereIn` in database query

### Testing Instructions

Test the function of buttons at post-installation messages

### Actual result BEFORE applying this Pull Request

use of deprecated function

### Expected result AFTER applying this Pull Request

code optimization

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c15691aa6997162798c6350ded69c0e48b3f3284<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38099">issues.joomla.org/tracker/joomla-cms/38099</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c15691aa6997162798c6350ded69c0e48b3f3284<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38099">issues.joomla.org/tracker/joomla-cms/38099</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38099">issues.joomla.org/tracker/joomla-cms/38099</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
