### PR TITLE
[4.0] Obsolete code for RTL

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the code that  was added 7 years ago to handle parentheses in RTL being displayed incorrectly in language names

When the code was introduced the LTR text was displayed incorrectly when the document was RTL. Browsers are now better at detection and this code is no longer needed.

To test install any RTL language eg Arabic or Persian Farsi and make that the admin language. Then go to the following links

1. `administrator/index.php?option=com_languages&view=installed&client=1`
2. `administrator/index.php?option=com_languages&view=languages`
3. and the admin login form

Before this PR it should look like the screenshot below. After the PR it should still look the same.

If after applying the PR you see something like `English (en-GB(` please mark this as a failed test and report the exact browser and operating system

image

### CODE REVIEW

**Comment by brianteeman** [comment]
the drone error is unrelated to this pull request

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b382a0dfef036868497d37611a1f6df27216e7df<br /><br />All the brackets I saw were correct. However, I did not have any articles or menu items in an rtl language. I am using iranian for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36143">issues.joomla.org/tracker/joomla-cms/36143</a>.</sub>

**Comment by infograf768** [comment]
This does not work on Safari 15.1 (17612.2.9.1.20) MacOS Monterey concerning Installed languages

Screenshot 2021-11-30 at 09 19 30

Concerning the admin menu it is wrong before and after patch.

Screenshot 2021-11-30 at 09 25 20

Screenshot 2021-11-30 at 09 34 27

No problem for admin login

**Comment by brianteeman** [comment]
weird that it works in one place and not the other

**Comment by brianteeman** [comment]
Closed as it doesnt work in safari the new internet explorer 6

**Pull request closed without merging**
