### PR TITLE
Fixed a small doc block error in index.php

### PR DESCRIPTION
**Pull request by eeshaanSA**
### Summary of Changes

Fixed Small Grammatical error in the doc block of define() in Index.php

### Testing Instructions
--

### Actual result BEFORE applying this Pull Request
--

### Expected result AFTER applying this Pull Request
--

### CODE REVIEW

**Comment by brianteeman** [comment]
If this is to be corrected then it should be "cause an error"

**Comment by eeshaanSA** [comment]
> If this is to be corrected then it should be "cause an error"

oh yes sorry. Changes have been made.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on ab4de768cd7621eb307ae76408567f002ac8d4ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37918">issues.joomla.org/tracker/joomla-cms/37918</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab4de768cd7621eb307ae76408567f002ac8d4ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37918">issues.joomla.org/tracker/joomla-cms/37918</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37918">issues.joomla.org/tracker/joomla-cms/37918</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
