### PR TITLE
Make the form field attributes valid XML

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Input tags can have attributes without a value and are still valid HTML. But XML parser's will fail as they are more restrict, so it would be not bad to produce proper XML output for the form fields. This PR changes some attributes like `required` into `required=required"`.

### Testing Instructions
Ope the article edit form, all should work as expected.

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by mbabker** [comment]
What HTML variant is Joomla core building for?  Pick one and stick with it.  XHTML and HTML5 have conflicting rules, so both can't be appeased.

**Comment by laoneo** [comment]
Is then `required=required"` invalid HTML?

**Comment by mbabker** [comment]
It's valid HTML5 but as you pointed out XML parsers don't like it.  What benefit is there in ensuring the generated HTML is usable in XML parsers?  It seems like it's a statement of "we will not use these HTML5 features because these parsers don't accept it".  Personally, I don't think Joomla needs to ensure that valid HTML can be used with parsers written for another language structure (XML !== HTML).

**Comment by wilsonge** [comment]
I agree with Michael here. Our templates support HTML 5. Unless there's a really good reason I don't see the need to support xml parsers

**Comment by laoneo** [comment]
I guess you guys didn't understand. `required="required"` is valid HTML5, or? So this change doesn't invalidate anything, it just improves things.

**Comment by mbabker** [comment]
`required="required"` is valid HTML5, correct.  But again, what gain is this actually bringing beyond being able to parse HTML with an XML parser, considering the two are NOT 100% compatible?

**Comment by laoneo** [comment]
It improves Joomla and that should be reason enough, many pr's do land in Joomla to make things better. Joomla does that on many places like on the [list field](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/list.php#L51) so why not making it consistent?

**Comment by wilsonge** [comment]
I don't understand how it improves Joomla. Whilst it's not invalid HTML 5 it's not recommended either https://www.w3.org/TR/html5/forms.html#the-required-attribute - see how all the examples here use the single attribute not `required="required"`

**Comment by laoneo** [comment]
We can argue back and forth, turning around in circles. If there is no need for consistence, just to leave it. I'm out here!

**Pull request closed without merging**
