### PR TITLE
[4.0] Use unique identifiers in ExtensionHelper::getExtensionRecord()

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Currently, `Joomla\CMS\Extension\ExtensionHelper::getExtensionRecord()` uses extension "name" to retrieve extension record. But the name is not standardized, not unique and can not be relied on.

This changes the method to be based on element, extension type and, optionally, client ID and folder.

### Testing Instructions

Postinstall module and other code using the method should work like before.

### Documentation Changes Required

Maybe. Existing uses `Joomla\CMS\Extension\ExtensionHelper::getExtensionRecord()` need to be updated to account for changes in function signature.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 05f453419617f65ead835ab1499352898b1ea61f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29230">issues.joomla.org/tracker/joomla-cms/29230</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 05f453419617f65ead835ab1499352898b1ea61f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29230">issues.joomla.org/tracker/joomla-cms/29230</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29230">issues.joomla.org/tracker/joomla-cms/29230</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
