### PR TITLE
[4.0] com_installer sidebar

### PR DESCRIPTION
**Pull request by brianteeman**
removes the unused sidebar code from com-installer

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated branch to retrigger drone time out errors unrelated to the code in this pr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15cf007e46d2a098e56e7d7a0a73d88d2b225c4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24868">issues.joomla.org/tracker/joomla-cms/24868</a>.</sub>

**Comment by travisrisner** [comment]
I have tested thsi item :white_check_mark: successfully on 15cf007

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24868">issues.joomla.org/tracker/joomla-cms/24868</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
