### PR TITLE
[4.0] Latests/Popular Admin modules permissions

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #36558

### Summary of Changes
adds link if the user created the article

### Testing Instructions
See #36558

### CODE REVIEW

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on 1d873389a7e00aa18ed35f195f18e911fb6b46d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36559">issues.joomla.org/tracker/joomla-cms/36559</a>.</sub>

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on 929708b8fb911739f9fc186ca156832ebb8dcc12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36559">issues.joomla.org/tracker/joomla-cms/36559</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 929708b8fb911739f9fc186ca156832ebb8dcc12<br /><br />Tested successfully in 4.06-dev using PHP 8.0.13 in Wampserver 3.2.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36559">issues.joomla.org/tracker/joomla-cms/36559</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36559">issues.joomla.org/tracker/joomla-cms/36559</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
