### PR TITLE
[4.1] Update input dependency which contains PHP 8.1 fixes

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for part of Issue #37274 and #34952.

### Summary of Changes
Update the input package with the recent PHP 8.1 fixes.

### Testing Instructions
- Use PHP 8.1
- Set error reporting to maximum in the global Joomla configuration
- Open the back end dash board

### Actual result BEFORE applying this Pull Request
The following error is displayed:
_Deprecated: Return type of Joomla\Input\Input::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/libraries/vendor/joomla/input/src/Input.php_

### Expected result AFTER applying this Pull Request
No error.

### CODE REVIEW

**Comment by exstreme** [comment]
I have tested this item :white_check_mark: successfully on 3cbf26f6edf4671b5e0f1f6a370b5261bfc1ed30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37502">issues.joomla.org/tracker/joomla-cms/37502</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3cbf26f6edf4671b5e0f1f6a370b5261bfc1ed30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37502">issues.joomla.org/tracker/joomla-cms/37502</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37502">issues.joomla.org/tracker/joomla-cms/37502</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
