### PR TITLE
[4.0] Convert icon used for jgrid defaults to fas fa-

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
changes the icon used for grid defaults to fas fa-

### Testing Instructions
go to administrator/index.php?option=com_menus&view=items&menutype=0main-menu-blog inspect circle icon
go to administrator/index.php?option=com_menus&view=items&menutype=mainmenu inspect home icon
apply pr
both icons should not change but inspect should show fas fa-

### Actual result BEFORE applying this Pull Request
image
image

### Expected result AFTER applying this Pull Request
image
image

### Documentation Changes Required
none

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on aef5cdd014d00633a9fad9cf7f78b710354fb20f<br /><br />Tested successfully in Beta4-dev of 24 August.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on aef5cdd014d00633a9fad9cf7f78b710354fb20f<br /><br />Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by sandewt** [comment]
Two things require attention: new PR ?

```<span class="icon-trash" aria-hidden="true"></span>```, should be ```<span class="fas fa-trash" aria-hidden="true"></span>```

```<span class="fas fa-fw fa-user-circle" aria-hidden="true"></span>```, should be ```<span class="fas fa-user-circle fa-fw" aria-hidden="true"></span>```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aef5cdd014d00633a9fad9cf7f78b710354fb20f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by richard67** [comment]
> Two things require attention: new PR ?
> 
> `<span class="icon-trash" aria-hidden="true"></span>`, should be `<span class="fas fa-trash" aria-hidden="true"></span>`
> 
> `<span class="fas fa-fw fa-user-circle" aria-hidden="true"></span>`, should be `<span class="fas fa-user-circle fa-fw" aria-hidden="true"></span>`

@N6REJ Could you make a PR?

**Comment by N6REJ** [comment]
> Two things require attention: new PR ?

> `<span class="fas fa-fw fa-user-circle" aria-hidden="true"></span>`, should be `<span class="fas fa-user-circle fa-fw" aria-hidden="true"></span>`
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/30464](https://issues.joomla.org/tracker/joomla-cms/30464).

@sandewt does the fa-fw order really matter?  or is this just a code style issue?

**Comment by sandewt** [comment]
>@sandewt does the fa-fw order really matter? or is this just a code style issue?

@N6REJ, I haved only looked at the source code of the browser ```view-source:https://localhost/joomla400-1/...```

So I think, it's probably a code style issue.

[EDIT] 
I now see that ```fa-fw``` is one time before it and the other time it is after it (by different classes).

See also Fixed Width Icons, [link Font Awesome](https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons).
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30464">issues.joomla.org/tracker/joomla-cms/30464</a>.</sub>

**Comment by infograf768** [comment]
Tks!

**Pull request merged**
