### PR TITLE
RTL: adapting display of Joomla versions plus some

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21024#issuecomment-439344407

### Summary of Changes
As it was decided to allow Joomla updates to beta branches, the Joomla verions in RTL may now contain some latin characters.
The version should subsequently be displayed as LTR.

As I was at it, I also corrected the admin stats module display and the Maximum upload size MB figure.

### Testing Instructions
In JoomlaUpdate Options choose Custom URL and add this link  :
https://update.joomla.org/core/nightlies/next_major_list.xml
It will present the `4.0.0-alpha6-dev` update
Save Options.
Install the Persian language.
Publish the mod_admin_stats module (Statistics) in cpanel position

With English as default admin language:

Display CPanel in one browser window and Joomlaupdate in another window (switch tabs there)

Make Persian as default admin language.
Reload the browser windows.

Apply patch and test again.

### Before patch
joomlaupdatequickicons_before
siteinfobefore
joomlaupdate_before_1
joomlaupdate_before_2

### After patch
joomlaupdatequickicons_after
siteinfo_after
joomlaupdate_after_1
joomlaupdate_after_2

@mbabker @rdeutz

### CODE REVIEW

**Comment by ghost** [comment]
i see only at second and third Screenshot Differences between "Before" and "After" Patch. What are the Differences in first and fourth?

**Comment by infograf768** [comment]
@franz-wohlkoenig 
Not sure which screenshots you are referring to.

**Comment by ghost** [comment]
the Screenshots in https://github.com/joomla/joomla-cms/pull/23107#issue-231775487

**Comment by infograf768** [comment]
I thought it was clear, sorry.

Instead of `alpha6-dev-4.0.0`,`dev-3.9.1`, `MB 32.00`
we now have correctly in RTL
`4.0.0-alpha6-dev`, `3.9.1-dev`, `32.00 MB`

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1ea122b47a8e80923cbe0016a1fa75c34e164c44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23107">issues.joomla.org/tracker/joomla-cms/23107</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3ea61683a17470d6881f7dbca18ff12cb6486cec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23107">issues.joomla.org/tracker/joomla-cms/23107</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
