### PR TITLE
[4] remove additional provided param that's not part of method signature

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 4b09d39615b77ee293a4272654a5c34b2345e9e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33961">issues.joomla.org/tracker/joomla-cms/33961</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4b09d39615b77ee293a4272654a5c34b2345e9e2<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33961">issues.joomla.org/tracker/joomla-cms/33961</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33961">issues.joomla.org/tracker/joomla-cms/33961</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
