### PR TITLE
[4] Search Term Analysis Empty State

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Search Term Analysis Empty State

### Actual result BEFORE applying this Pull Request

Screenshot 2021-05-02 at 21 42 08

### Expected result AFTER applying this Pull Request

Screenshot 2021-05-02 at 21 41 42

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fea82b87c8fb6adc851c41fddcc83b38f0751dc8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33495">issues.joomla.org/tracker/joomla-cms/33495</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fea82b87c8fb6adc851c41fddcc83b38f0751dc8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33495">issues.joomla.org/tracker/joomla-cms/33495</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33495">issues.joomla.org/tracker/joomla-cms/33495</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
