### PR TITLE
CodeMirror 5.25.2

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .
#15532

### Summary of Changes
http://codemirror.net/doc/releases.html

### Testing Instructions
Use CodeMirror.

### Expected result
It will continue to work normally.

### Actual result
It continues to work normally.

### Documentation Changes Required
Nope

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
If you like CodeMirror, you'll want to check this out #12542

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 2a10a9537139a8115ba4d031eca556c1d677200f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15559">issues.joomla.org/tracker/joomla-cms/15559</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 2a10a9537139a8115ba4d031eca556c1d677200f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15559">issues.joomla.org/tracker/joomla-cms/15559</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
