### PR TITLE
Change type of field "value" in table #_fields_values from text to mediumtext

### PR DESCRIPTION
**Pull request by sergeytolkachyov**
Change type of field "value" in table `#_fields_values` from `text` to `mediumtext` for MySQL ONLY. PostgreSQL have only text field type with unlimited length. Pull Request for Issue #36065 and remake a PR #42605 for Joomla 5.1.0

# Testing instructions
1. Go to bottom of this PR and click **Show all checks** in **All checks have passed**  section
2. Click on **Details** in **download** line
image
3. You will go to https://artifacts.joomla.org/drone/joomla/joomla-cms/5.1-dev/42606/downloads/72696/
4. Download Full installation package and update package of Joomla 5.1 + this PR
image
5.  Make a clean install from `Joomla_5.1.0-alpha3-dev+pr.42606-Development-Full_Package.zip`
6. Go to PhpMyAdmin, select database you used for clean install and go to the `#__field_values` table. Then go to **structure** section and check that type of `value `field is `mediumtext`.
image
7. Clean your database and test domain folder and install a Joomla 5.0.1 
8. Check `value` field type in PHP My Admin in `#__field_values` table. It is a `text` type now.
image
9. Then go to **admin panel / System / Update / Joomla** . Press the **Upload and Update** button
image
10. Upload  the `Joomla_5.1.0-alpha3-dev+pr.42606-Development-Update_Package` and update
image
11. Then go to PhpMyAdmin again and check the `#__field_values` table - type of field `value`. It could be a `mediumtext`
image

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
@sergeytolkachyov By review your PR looks good to me. But it would be good if you could provide some testing instructions. When you create a pull request, there are already headings for testing instructions and so on in the description. This is intended to be completed by the author, not to be removed completely. Possible testing instructions could be to make a new installation and check the type of the column after that, and to make an update with the package ur custom URL created by drone and check the type of the column after that. Or in this simple case maybe only "Code review". But there should be some testing instructions.

**Comment by richard67** [comment]
@sergeytolkachyov You reacted with a thumbs up to my previous comment, but you haven't added any testing instructions to the description of this PR yet. Could you do that? Thanks in advance.

**Comment by bembelimen** [comment]
Just an off topic comment, if you working heavily with custom fields: you can improve the performance enormous when you change the ```item_id``` column to integer instead of varchar.

But for this change we need a small kind of migration, but I think worth to investigate (if you're up for another PR)

**Comment by sergeytolkachyov** [comment]
> @sergeytolkachyov You reacted with a thumbs up to my previous comment, but you haven't added any testing instructions to the description of this PR yet. Could you do that? Thanks in advance.

Done

**Comment by richard67** [comment]
> Done

Thanks.

**Comment by chmst** [comment]
> Just an off topic comment, if you working heavily with custom fields: you can improve the performance enormous when you change the `item_id` column to integer instead of varchar.
> 
> But for this change we need a small kind of migration, but I think worth to investigate (if you're up for another PR)

@bembelimen  It did that in my application with about 40k fields_values and  it makes such an incredible huge difference. I would really appreciate and support a PR for that.

**Comment by sergeytolkachyov** [comment]
@richard67 @bembelimen not merged?

**Comment by richard67** [comment]
@sergeytolkachyov You should know that
1. Every non trivial pull request needs 2 successful tests by hinab testers before it can be merged, and
2. I am not a release manager so I won’t decide anything.

**Comment by alikon** [comment]
quite every pr needs 2 human test

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a7badaac0a038d3e2d42dd14909d1e0db9e7bc46<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42606">issues.joomla.org/tracker/joomla-cms/42606</a>.</sub>

**Comment by richard67** [comment]
> quite every pr needs 2 human test

Yes, if it’s not just a typo in a comment, that’s what I mean with „non trivial“.

**Comment by sergeytolkachyov** [comment]
Strangely, for some reason I remembered that 2 necessary tests had already been done.

**Comment by richard67** [comment]
> Strangely, for some reason I remembered that 2 necessary tests had already been done.

@sergeytolkachyov Where? Here in the PR I can not see any human test results except of the one from a few minutes ago.

**Comment by sergeytolkachyov** [comment]
> > Strangely, for some reason I remembered that 2 necessary tests had already been done.
> 
> @sergeytolkachyov Where? Here in the PR I can not see any human test results except of the one from a few minutes ago.

I wrote to 3 humans for testing now. Thank you

**Comment by gug2** [comment]
I have tested this item :white_check_mark: successfully on a7badaac0a038d3e2d42dd14909d1e0db9e7bc46<br /><br />Successfully tested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42606">issues.joomla.org/tracker/joomla-cms/42606</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42606">issues.joomla.org/tracker/joomla-cms/42606</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
