### PR TITLE
[4.0] Permissions Text

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #27668

Changes the description from
> Default permissions for this component.

to

> Permissions for this component unless they are changed for a specific item.

This avoids confusion on the meaning of "default" and is more consistent with other similar descriptions used in options.

Note: the suggestion by @wilsonge to change the label didn't work because the text is too long

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 45aa20b6aec1a7c9168c67d4186b338214439ef2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27994">issues.joomla.org/tracker/joomla-cms/27994</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 45aa20b6aec1a7c9168c67d4186b338214439ef2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27994">issues.joomla.org/tracker/joomla-cms/27994</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27994">issues.joomla.org/tracker/joomla-cms/27994</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
