### PR TITLE
[4.0] sample data - modules

### PR DESCRIPTION
**Pull request by brianteeman**
Adjust the text in the Your Modules page as the edit modules icon is now always visible when enabled and you are logged in

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2a971b42c40fe003b2b313e161e965218073a418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32979">issues.joomla.org/tracker/joomla-cms/32979</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2a971b42c40fe003b2b313e161e965218073a418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32979">issues.joomla.org/tracker/joomla-cms/32979</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32979">issues.joomla.org/tracker/joomla-cms/32979</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
