### PR TITLE
[4.0] RTL : fixing mobile template

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
Fixing search tools and toolbar display

### Testing Instructions
Install Persian language, switch to Persian and reduce window width to mobile view

Run npm after patch
### Before patch
rtl_before

### After patch
Screen Shot 2019-10-24 at 10 50 35

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1294e2b06c7217cd685346f786a367c9bbb4467c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26796">issues.joomla.org/tracker/joomla-cms/26796</a>.</sub>

**Comment by infograf768** [comment]
@Quy @alikon @wilsonge 
Can you test this one and get it in as we need more to do in RTL?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2666d79db3ec40eeadb77a753736d2313cbfe111<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26796">issues.joomla.org/tracker/joomla-cms/26796</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26796">issues.joomla.org/tracker/joomla-cms/26796</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
