### PR TITLE
[5.1] webauthn missing string

### PR DESCRIPTION
**Pull request by brianteeman**
Adds a missing string. As its an error message string and virtually impossible to reach then code review should be enough.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7fdbc9f7b1b4d9dee899aebbec554a3bff48d5fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42393">issues.joomla.org/tracker/joomla-cms/42393</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7fdbc9f7b1b4d9dee899aebbec554a3bff48d5fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42393">issues.joomla.org/tracker/joomla-cms/42393</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42393">issues.joomla.org/tracker/joomla-cms/42393</a>.</sub>

**Comment by Razzo1987** [comment]
Thank you!

**Review by zwiastunsw — COMMENTED** [review]
sorry, mistake, accidentally

**Pull request merged**
