### PR TITLE
[4.0][Admin Menus]Fixed proceed button logic

### PR DESCRIPTION
**Pull request by alexandraciobica**
Pull Request for Issue #19827.

### Summary of Changes

In this PR #18195 this bug #15134 was fixed that is hiding the proceed button from the items with Trashed status. However, the fix affected all the statuses from the admin menus.

The old condition:
`<?php if ((strlen($menuType) && $menuType != '*' && $clientId == 0) || ($published > 0 && $clientId == 1)): ?>`

`$published` can be:

- `""` when `no status` is selected
- `0` when `Unpublished` status is selected
- `1` when `Published` status is selected
- `-2` when `Trashed` status is selected

 New condition, taking care of the items with Trashed state selected
`<?php if (strlen($menuType) && $menuType != '*' && $published != -2): ?>`

### Testing Instructions

1. Create an admin menu
2. Create some menu items in this admin menu
3. Select some menu items and click toolbar button batch

### Result
Hide proceed button when selected items state is Trashed, show it otherwise.

### CODE REVIEW

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 0e2851d2842603fc6f2660bf92478d7be39c2b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19879">issues.joomla.org/tracker/joomla-cms/19879</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 0e2851d2842603fc6f2660bf92478d7be39c2b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19879">issues.joomla.org/tracker/joomla-cms/19879</a>.</sub>

**Comment by infograf768** [comment]
@izharaazmi 
Is this PR OK for you?

**Comment by izharaazmi** [comment]
Looking at the current code (without this PR) it appears that it is still showing the `process` button for trash for frontend menus, not solving the real issue in #18195. Please verify.

This PR looks good to me, except the extra pair of parenthesis inside `if`  ;-)

**Comment by alexandraciobica** [comment]
I fixed this bug, but as it was related to the other bug for the items with Trashed status, I observed that:
- when selecting published status ‘All’ 
- if you select a trashed item 
- and then batch, the process button is not hidden. Should this be fixed? Or the functionality was only for selecting the Trashed status?

I believe that with the current implementation, there is no way of doing this in the backend, but I could write a JS script that at least hides the button in this case. 

PS: Removed extra parenthesis :D

**Comment by izharaazmi** [comment]
IMHO, nothing should stop us to batch process the trashed items. However, I haven't looked closely so I can't tell for sure.

If this is really the special case with trashed items, then we should have:

```php
if (strlen($menuType) && $menuType != '*' && strlen($published) && $published != '*' && $published != -2)
```

**Comment by alexandraciobica** [comment]
@izharaazmi, in your solution the proceed button is displayed only in the case when the selected state is 'Published' or 'Unpublished' but it is not shown when selected 'All', which affects the published and unpublished items together with the trashed ones. Indeed I don't know why trashed items shouldn't be batched, I've just followed what the other bug(#15134) said.

**Comment by samarthsharma36** [comment]
I have tested this item :white_check_mark: successfully on a569ca06382dbecad13eaad809bf711b8f87b772<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19879">issues.joomla.org/tracker/joomla-cms/19879</a>.</sub>

**Comment by infograf768** [comment]
I think this solution is fine. Should be ported to staging.
See https://github.com/joomla/joomla-cms/issues/22154

**Comment by infograf768** [comment]
As we have a similar issue in 3.9/staging, I am closing this in favor of https://github.com/joomla/joomla-cms/pull/22178 which shall be ported to 4.0 by the usual process.

**Pull request closed without merging**
