### PR TITLE
[4.0] Fix narrow column width in list view of media manager

### PR DESCRIPTION
**Pull request by eopws**
Pull Request for Issue #33943.

### Summary of Changes

Fix of the narrow column width in media manager.

### Testing Instructions

Go to Content > Media
Click List icon.
Go to sampledata > parks > landscape

### Actual result BEFORE applying this Pull Request

Icons column has small width

### Expected result AFTER applying this Pull Request

Icons column has enough width

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cfb3f4e3b0aac0bce5d03998902894811c97c9be<br /><br />Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cfb3f4e3b0aac0bce5d03998902894811c97c9be<br /><br />With Prebuild Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by brianteeman** [comment]
Sorry but this is not correct

image

**Comment by eopws** [comment]
@brianteeman
Is that because of incorrect line break?
The problem from the issue is caused by lack of width in icon column, and I know two solutions:

- The one proposed in the PR
- Set min-width property to icon cell

If you consider line break a bad solution I can replace it with min-width property.

**Comment by brianteeman** [comment]
The size of the other columns is way too big. you really dont want to wrap a filename unless you absolutely have to

image

Better to set some more sensible column widths such as

```

.media-browser-table .type {
    width: 5%;
}

.media-browser-table .size {
    width: 10%;
    text-align: right;
}

.media-browser-table .dimension {
    width: 15%
}

.media-browser-table .created,.media-browser-table .modified {
    width: 15%;
}

```

**Comment by eopws** [comment]
@brianteeman

> Better to set some more sensible column widths such as

But we are still gonna have the problem when the file name is too big. Try to add symbols to a filename in devtools.
I think it's cool to change column widths as you proposed and add the `word-break: break-all;` property to 'name' columns. Then if the filename will be very big the layout would not be broken.

**Comment by brianteeman** [comment]
> But we are still gonna have the problem when the file name is too big.

Always going to happen but we can reduce the times when it will happen by setting sensible column widths in the beginning - especially when the width of the data in the column is never going to be that wide

**Comment by eopws** [comment]
Please, test new patch.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b1b17be165d65221f7a7be173a46c1ba3e282ba8<br /><br />Installed the new Prebuild Package. It's much better now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b1b17be165d65221f7a7be173a46c1ba3e282ba8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by Quy** [comment]
The first column should align.

**Comment by richard67** [comment]
Back to pending, see comment https://github.com/joomla/joomla-cms/pull/33945#issuecomment-843541580 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by eopws** [comment]
The patch works on my machine. Please, test it too.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0d9143d476e99f654936e0aa7de97f54370d02e0<br /><br />Better that it was. But why does the icon cell have a bottom border but the rest of the row does not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by eopws** [comment]
> But why does the icon cell have a bottom border but the rest of the row does not?

What do you mean? Please, send screenshot.

**Comment by ChristineWk** [comment]
I'm not sure & see it now in this way:

screen shot 2021-05-19 at 09 31 01

or what do you mean @ceford?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by eopws** [comment]
https://github.com/joomla/joomla-cms/pull/33945#issuecomment-843925870
I can fix it, but it is out of the PR's topic.
Also it was before applying the patch too.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0d9143d476e99f654936e0aa7de97f54370d02e0<br /><br />@eopws OK. Don't remember the previous last line/border :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33945">issues.joomla.org/tracker/joomla-cms/33945</a>.</sub>

**Comment by Quy** [comment]
In Firefox, it is a pixel off to the left. In Chrome, it is fine. 

The toggle checkbox is 50px.

Please see if you can use the same value and look good in both browsers.

**Comment by eopws** [comment]
> In Firefox, it is a pixel off to the left. In Chrome, it is fine.
> 
> The toggle checkbox is 50px.
> 
> Please see if you can use the same value and look good in both browsers.

In Chrome, it is a pixel off to the right, if set min-width equals to 50px.
But in Chrome it doesn't seem to be critical while it looks bad in Firefox.

**Comment by Quy** [comment]
Merging as this is better than before. Thank you!

**Pull request merged**
