### PR TITLE
svg uploads

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
add three more errors to ignore as a temp measure until they have been whitelisted and/or bugfixed upstream

To test apply the pr and try to upload all the svg in the attached zip

It still correctly refuses to upload the bad files and there are less false positives

[svg.zip](https://github.com/joomla/joomla-cms/files/9389985/svg.zip)

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
As well as the three bad files getting "unable to upload" I also get "cleaned_example6, example4 and example5 getting "unable to upload"
Do you wish this marked as a fail or was this expected?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38545">issues.joomla.org/tracker/joomla-cms/38545</a>.</sub>

**Comment by brianteeman** [comment]
> Do you wish this marked as a fail or was this expected?

as expected. fewer false positives

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e8cce7c3ed90fe552c454c49746a45144928a2fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38545">issues.joomla.org/tracker/joomla-cms/38545</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38545">issues.joomla.org/tracker/joomla-cms/38545</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you Brian :)

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
