### PR TITLE
Removing ContactModelContact::getContactQuery()

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This removes the method ContactModelContact::getContactQuery(). I was unable to find any place in our codebase where we use it and to be honest, it looks as if this was added 8 years ago rather by mistake. All changes since then seem to have been mass-refactorings. While the method does return more or less correct data, it does not return all data that you get with ContactModelContact::getItem(). Since the method is protected and in a component, there should be no issue with backwards compatibility.

### CODE REVIEW

**Comment by brianteeman** [comment]
Isnt the correct thing to do is to mark it as deprecated and then remove it in J4

We cant know if some extension/site is using it for example

**Comment by mbabker** [comment]
The only way someone could be doing that is if they were extending the model class.  As a protected method, you can't call it from outside without using trickery to bypass the scope limitation.  So the safest path would be deprecate and remove in 4.0, but from a practical perspective...

**Comment by brianteeman** [comment]
>  you can't call it from outside without using trickery to bypass the scope limitation

so someone could ;)

i think we need to be strict on this stuff if we are using semver

**Comment by Hackwar** [comment]
@brianteeman I'm partially agreeing with you. The SemVer supporter in me says to do this in 4.0, but the developer in me says that whoever uses this must be the stupidest developer out there, since there is a getItem() method which does the same and even more and if I had the choice between using a proper named function with an undertstandeable name vs. a strangely named method which does not return everything that I expect, I would use the former...

**Comment by brianteeman** [comment]
We can't fix stupid

**Comment by Bakual** [comment]
There is absolutely no reason to **not** follow SemVer here.
Deprecate in J3 and remove in J4.

**Comment by Quy** [comment]
See PR #20353<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16460">issues.joomla.org/tracker/joomla-cms/16460</a>.</sub>

**Pull request closed without merging**
