### PR TITLE
[5.2] [Guided Tours] Fix content and footer padding

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #44096.

### Summary of Changes

When footer buttons are missing, the step content has no bottom padding.

### Testing Instructions

There is no core tour that can show this behavior.

Create a new tour (with relative URL: administrator/index.php, Component selector: 'Home dashboard').

Create the following steps for the tour:

Step 1:
Position: Bottom
Target: .quickicon a[href*=com_config]
Type: Interactive
Interactive type: Form submit

Step 2:
Position: Bottom
Target: #toolbar-save
Type: Interactive
Interactive type: Form submit

Step 3:
Position: Center
Type: Next

It does not matter what you enter in titles and descriptions.

Run the tour.

Run other tours and make sure bottom padding is correct in the other tour(s) you run.

### Actual result BEFORE applying this Pull Request

No padding at the bottom of the popup in step 3.

image

### Expected result AFTER applying this Pull Request

Padding at the bottom of the popup in step 3.

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on a38c01be9afd61dbfc000e0618da8bce2b715fb0<br /><br />It works, it's been tested.

The test instructions are not complete, after step 2 you need to create another step - informational, since step 2 of the test instructions (if it is the final one) will have a Close button, and we need to get a step without buttons.

In addition, the PR can be tested on an existing tour - a tour for creating STEPS (specifically step 3).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44104">issues.joomla.org/tracker/joomla-cms/44104</a>.</sub>

**Comment by richard67** [comment]
@obuisard `node build/build.js --prepare` fails in Drone. It seems there is something wrong with the CSS, but I don't see any mistake.

**Comment by obuisard** [comment]
> I have tested this item ✅ successfully on [a38c01b](https://github.com/joomla/joomla-cms/commit/a38c01be9afd61dbfc000e0618da8bce2b715fb0)It works, it's been tested.
> 
> The test instructions are not complete, after step 2 you need to create another step - informational, since step 2 of the test instructions (if it is the final one) will have a Close button, and we need to get a step without buttons.
> 

Thanks for the correction, you are right, it needs an extra step. I had one in my test tour.

**Comment by obuisard** [comment]
> @obuisard `node build/build.js --prepare` fails in Drone. It seems there is something wrong with the CSS, but I don't see any mistake. I will try if a branch update helps.

Got it, it does not like the order of the properties...

**Comment by richard67** [comment]
@Kostelano Could you briefly test again if it still works? I don't expect any issues but I'd like to be safe. Thanks in advance.

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on bcc1df94c031fc5cfe3530728f9010771b9918b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44104">issues.joomla.org/tracker/joomla-cms/44104</a>.</sub>

**Comment by obuisard** [comment]
I followed the requested change in Drone, but apparently it is not 'smart' enough to tell us the whole story. I had to change the order again. I apologize.

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 0abeffd3071f4f93694f4a269ae02e8973dfc001<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44104">issues.joomla.org/tracker/joomla-cms/44104</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44104">issues.joomla.org/tracker/joomla-cms/44104</a>.</sub>

**Comment by tecpromotion** [comment]
Step 3 in "How to add steps to a guided tour?" now with padding.
/administrator/index.php?option=com_guidedtours&view=steps&tour_id=12
step3-with-padding

**Review by tecpromotion — APPROVED** [review]

**Comment by Hackwar** [comment]
Thanks for your contribution @obuisard!

**Pull request merged**
