### PR TITLE
[5.2] Finder: Simplifying the populateState() method of SearchModel

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #43087 .

### Summary of Changes
For reasons unobvious to me, we are using the data from the request object in our input object when populating the state of the SearchModel model. This PR changes this to be in line with all other models by simply using the input object.

### Testing Instructions
Codereview?

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by growunder** [comment]
Code reviewed, seams ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43091">issues.joomla.org/tracker/joomla-cms/43091</a>.</sub>

**Comment by HLeithner** [comment]
I would expect the reason is that you can simple use POST or GET requests for the search, now only GET is possible anymore?

**Comment by Fedik** [comment]
> now only GET is possible anymore?

Nope, it the same, `$input` contain whole data from $_REQUEST, so it will be same result as `$input->request`.

For only GET would be `$input->get->get('foobar')`,
For only POST would be `$input->post->get('foobar')`,

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
