### PR TITLE
[4.0] Language string. Correct typo unkown instead of unknown

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
Code review. Typo is obvious.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cd755ba3baf87fc68dad384713d564dfc314fa2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23313">issues.joomla.org/tracker/joomla-cms/23313</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 528e24a5b27f84d299a0aaf8ef2203a2faab571c<br /><br />Code inspection.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23313">issues.joomla.org/tracker/joomla-cms/23313</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23313">issues.joomla.org/tracker/joomla-cms/23313</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
