### PR TITLE
Add id on installer buttons

### PR DESCRIPTION
**Pull request by 810**
we need an id on the buttons for better codestyle, on unittests

### CODE REVIEW

**Comment by mbabker** [comment]
Aren't these all displayed on the same page?  If so they can't use the same ID.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 388ff2f0879aeab36d9e9f507513b96f85d2978d<br /><br />on code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by andrepereiradasilva** [comment]
as mbabker comments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on 388ff2f0879aeab36d9e9f507513b96f85d2978d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your contribution but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 5c2c8f4a5afe7d499e8bd73529bce5cfa9e22f05<br /><br />on review.
ids are now different.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 5c2c8f4a5afe7d499e8bd73529bce5cfa9e22f05<br /><br />The IDs are unique and are set correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 5c2c8f4a5afe7d499e8bd73529bce5cfa9e22f05<br /><br />ids are now different and unique. Thanks :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by roland-d** [comment]
Setting to RTC, we have 2 successful tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Comment by zero-24** [comment]
we have 3 @roland-d and 2 who try to add the RTC label :smile:

**Comment by Kubik-Rubik** [comment]
Thank you @810 and testers!

**Comment by brianteeman** [comment]
Sorry for the confusion - posted on a wrong issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10322">issues.joomla.org/joomla-cms/10322</a>.</sub>

**Pull request merged**
