### PR TITLE
Fix warnings in layouts on PHP 7.4

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27259.

### Summary of Changes

Removes some misplaced code.

### Testing Instructions

Create Article Category List menu item and Featured Contacts menu items. View them in frontend.

### Expected result

No warnings.

### Actual result

>Warning: Creating default object from empty value

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 797d0192661f5c72294a7bb9ad378a7f397530f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27273">issues.joomla.org/tracker/joomla-cms/27273</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 797d0192661f5c72294a7bb9ad378a7f397530f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27273">issues.joomla.org/tracker/joomla-cms/27273</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27273">issues.joomla.org/tracker/joomla-cms/27273</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by hcherter** [comment]
Hello, 
I'm using Joomla 3.9.16 with PHP 7.4.2. I still get these warnings "Warning: Creating default object from empty value in...". 
Question: Is this fix already commited/released or can you estimate when it will be committed/released? 
Thanks for a feedback.

**Comment by zero-24** [comment]
Hi this has been fixed an released by 3.9.15 please open a new issue with your warning including the file and complete message so we can investigate.

**Pull request merged**
