### PR TITLE
[[4.3] Allow creating of name.min.css

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # #38455 .

Second attempt - different approach to #38458 

### Summary of Changes
`(?!\.) `- don't allow . at start
`(?!.*\.\.)` - don't allow 2 consecutive dots
`(?!.*\.$)` - don't allow . at end
`[a-zA-Z0-9_.] `only allow these characters

It is currently possible to upload a file.min.css, file.min.js, file.asset.json

However it is not possible to rename or create a new file as we had a check to prevent having a . in the name

There really is no need for this restriction. It dates back 10 years to a security fix but it wasn't needed as the rest of the security fix is still valid.

NOTE: This does not add .min.css or .min.js or asset.json to the list of filetypes. They are still just css, js and json but now you can put a dot in the filename

image

image

### Testing Instructions
1. Create files as below

2. Rename existing files as below

```
.template
template.
template
template.min
_template
template_
temp_late
9emplate
template9
temp.la.te.
temp..late

```
### Expected result AFTER applying this Pull Request
```

.template ❌ (note this will be saved as template)
template. ❌
template ✔️
template.min ✔️
_template ✔️
template_ ❌
temp_late ✔️
9emplate ✔️
template9 ✔️
temp.la.te. ❌
temp..late ❌


```
### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wilsonge** [comment]
//cc @joomla/security in case you want to review. Not a blocker for them to review though - I think this looks fine in my eyes

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
@brianteeman Maybe you should quote the file names in the testing instructions like we `quote code` because the underscores are not visible. The text is shown in italics instead. At least that's what I see on GitHub.

**Comment by brianteeman** [comment]
@richard67 thanks - I didnt spot that - I have updated it now

**Comment by brianteeman** [comment]
Drone errors are unrelated to this PR

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 38b0b816c1e6b7a0cba1ba6404420f3ed0de38e6<br /><br />.something ❌ (note this will be saved as template) - done and successful
template. ❌ - done and successful
template ✔️ - done and successful
template.min ✔️  - done and successful
_template ✔️ - done and successful
**template_ ❌ Acually created but I see no problem with it?**
temp_late ✔️ - done and successful
9emplate ✔️ - done and successful
template9 ✔️ - done and successful
temp.la.te. ❌ - done and successful
temp..late ❌ - done and successful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38987">issues.joomla.org/tracker/joomla-cms/38987</a>.</sub>

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 1df615784068e86dbe05561cd6d8cc7ec65fc96a<br /><br />Saving .tada.css will not fail, but save as tada.css (on Windows system).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38987">issues.joomla.org/tracker/joomla-cms/38987</a>.</sub>

**Comment by brianteeman** [comment]
> Saving .tada.css will not fail, but save as tada.css (on Windows system).

That's the same before this PR. There is other validation taking place elsewhere

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on 37e3c9c578afa2bf42f90da974254dd264ed2705<br /><br />Thank you Brian!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38987">issues.joomla.org/tracker/joomla-cms/38987</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38987">issues.joomla.org/tracker/joomla-cms/38987</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR!

**Comment by brianteeman** [comment]
Thank you. Now just needs the tinymce.min.css pr to be merged

**Comment by richard67** [comment]
> Thank you. Now just needs the tinymce.min.css pr to be merged

@brianteeman You mean this one #39124 ? Or a new one which is to be created?

**Comment by brianteeman** [comment]
yes thats the one

**Comment by richard67** [comment]
That's for 4.2-dev. So it would not only need to be merged but also to be merged up afterwards.

**Comment by brianteeman** [comment]
well it needs to be tested as well ;)

**Pull request merged**
