### PR TITLE
Give protected menu items container its own place independent of heading type.

### PR DESCRIPTION
**Pull request by izharaazmi**
### Summary of Changes
Admin menu manager currently uses heading menu type flag to set components menu items container. Now we will have another menu type under "System Links" by name "Components Menu Container"

### Testing Instructions
Create a new custom admin menu.
Create a menu item of type System Links > Components Menu Container
Make sure the components container menu item shows all published menu items of type "Main (Protected)"

### Documentation Changes Required
Not sure.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a0595ab59da56e388f9e1adb41408d59c4b9c25d<br /><br />"Components Menu Container" show im Menu all Menues of default "Components".

But got `Warning: The active administrator menu does not contain links to Module Manager and Menu Manager. Click to turn on the menu recovery mode.`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13749">issues.joomla.org/tracker/joomla-cms/13749</a>.</sub>

**Comment by infograf768** [comment]
@izharaazmi 
The new menu item should only display when adding to a custom admin menu.
That's why I added to my fast patch
`if ($this->get('State')->get('client_id') == 1)` in menutypes.view.html.php

**Comment by izharaazmi** [comment]
@infograf768 I'm sorry that I missed it. PR updated.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a8bc547b90dea2edca4c30df1253b85e970004e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13749">issues.joomla.org/tracker/joomla-cms/13749</a>.</sub>

**Comment by infograf768** [comment]
As the correction was simple. RTC.

@rdeutz Can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13749">issues.joomla.org/tracker/joomla-cms/13749</a>.</sub>

**Pull request merged**
