### PR TITLE
[com_fields][com_baners] Alt text label and desription

### PR DESCRIPTION
**Pull request by brianteeman**
Update strings to be consistent with their use elsewhere in Joomla

### CODE REVIEW

**Comment by cheesegrits** [comment]
On a fresh vanilla 3.6.4 install:

Error
The file marked for modification does not exist: administrator/language/en-GB/en-GB.com_fields.ini<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by cheesegrits** [comment]
Ooops, I'm a dork, forgot to switch to staging.  Mea Culpa.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by cheesegrits** [comment]
Tested succesfully.

Sorry about that, forgot my PR testing install is a fork, so forgot to do an upstream merge.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by brianteeman** [comment]
@cheesegrits please mark your test as a success or failure at the top of the page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by cheesegrits** [comment]
I have tested this item :white_check_mark: successfully on 9c0d991f76b9641036d76fe9a9ebdaef832a8ff1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 9c0d991f76b9641036d76fe9a9ebdaef832a8ff1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13117">issues.joomla.org/tracker/joomla-cms/13117</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
