### PR TITLE
UI/UX Review for com_search on mobile devices

### PR DESCRIPTION
**Pull request by zero-24**
see: #5628

This is a proposal UI/UX review on mobile for the search component.

This only remove (hide) the `show search results` button on mobile devices

### CODE REVIEW

**Comment by brianteeman** [comment]
This needs to be tested on a site that has had the search statistics plugin
active. Is this component useful without that button? I honestly dont know
I never use the plugin

**Comment by zero-24** [comment]
@brianteeman 

>Is this component useful without that button?

Yes just tested.

The Button only show or hide the itms of the `Results` row.

see:
screen shot 2015-01-11 at 13 05 20
screen shot 2015-01-11 at 13 05 27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5668">issues.joomla.org/joomla-cms/5668</a>.</sub>

**Comment by infograf768** [comment]
Imho, it is useful. We have only 2 types of information in that manager.

screen shot 2015-01-12 at 09 36 56

**Comment by zero-24** [comment]
@infograf768 
>Imho, it is useful. We have only 2 types of information in that manager.

Did you mean we should remove (hide) the button on mobile or not? (I'm not really sure what you mean :smile: )
I think (on mobile) we can hide it. I think it is useful enough without the button on mobile.

**Comment by infograf768** [comment]
Without the button (if the button is on hide results), the result column is useless.
I would keep the button.

**Comment by zero-24** [comment]
Thanks closing here as it is only a very smal point. Thanks @infograf768

**Pull request closed without merging**
