### PR TITLE
It's 2017. Happy New Year

### PR DESCRIPTION
**Pull request by wilsonge**

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
actually bump.php would do this automatticly :wink: on next run
https://github.com/joomla/joomla-cms/blob/staging/build/bump.php#L307

**Comment by dgt41** [comment]
@andrepereiradasilva you should have mentioned that a bit earlier, now almost all the PRs are out of sync... 😕

**Comment by andrepereiradasilva** [comment]
i mention it earlier ... back in june https://github.com/joomla/joomla-cms/pull/10865 :wink:

**Comment by dgt41** [comment]
So @wilsonge's fault then 😛

**Comment by mbabker** [comment]
> now almost all the PRs are out of sync...

Changing the file header doesn't make PRs out of sync unless said PR is changing the file header.  Same comment every year 😉

**Comment by wilsonge** [comment]
I forgot about bump. My bad!

**Comment by zero-24** [comment]
@jeckodevelopment @wilsonge please add the milestone on merge ;)

**Comment by wilsonge** [comment]
I kinda deliberately didn't - this is just junk in the changelog? I dunno.....

**Comment by mbabker** [comment]
Not every pull request needs to go to a milestone.  Some changes are administrative in nature and really don't matter.  If someone ran a PR updating the version numbers based on running `build/bump.php` does that really need to be there?

**Comment by zero-24** [comment]
In the past we added every change even just in the tests or build folder to a milestone. If we want to change that just tell me how exactly you want to handle that. So which change need a milestone one which not.

**Comment by rdeutz** [comment]
I am pushing admin changes directly without making a PR, so the junk started as the PR was made. Any PR should have a milestone, test, ....

**Pull request merged**
