### PR TITLE
[Fix]Component dropdown does not get the ??MISSING_LANGUAGESTRING??

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #15211

### Summary of Changes

Lets use the magic language system there is no fallback needed

### Testing Instructions

- install staging
- enable debug language
- install e.g german (or any other 3.6.5 language pack)
- switch to that language in the backend

### Expected result

??COM_ASSOCIATIONS?? in the components dropdown

### Actual result

"Multilingual Associations" (even without the ** arround it)
image

### Documentation Changes Required

None

### CODE REVIEW

**Comment by infograf768** [comment]
let me test this tomorrow, specially for the submenus

**Comment by alikon** [comment]
i like magic

**Comment by zero-24** [comment]
The submenu was just a forward change as the same should apply there. ;)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fae42224b5c84955e23a2c17aef60567e0408714<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15231">issues.joomla.org/tracker/joomla-cms/15231</a>.</sub>

**Comment by zero-24** [comment]
> i like magic

It is less magic but more a feature of JLanguage to handle that with the en-GB value. ;)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on fae42224b5c84955e23a2c17aef60567e0408714<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15231">issues.joomla.org/tracker/joomla-cms/15231</a>.</sub>

**Comment by infograf768** [comment]
Much simpler! RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15231">issues.joomla.org/tracker/joomla-cms/15231</a>.</sub>

**Comment by infograf768** [comment]
Should go into 3.7.0

**Pull request merged**
