### PR TITLE
Permissions status not translated on the fly Solving #9968

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #9968
#### Summary of Changes

Added the js ini constants 
#### Testing Instructions

On staging, install at least one language more than en-GB.
Switch to this language in backend.
Edit the permissions (Global or any component).
Select a new setting for a user group.

Before patch, the Calculated Setting will be displayed as harcoded English "Allowed" or "Not Allowed." One has to save to get the correct translation in the language used.

After patch, the Calculated setting will display in the language of the UI.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7302dcbf136c60237ef5fc0a886d127031d16e04<br /><br />No wonder I couldn't get my code to work I missed the rules.php ;)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 7302dcbf136c60237ef5fc0a886d127031d16e04<br /><br />Tested with both English and French languages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 7302dcbf136c60237ef5fc0a886d127031d16e04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by MATsxm** [comment]
Able to reproduce then #10117 works as described - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 7302dcbf136c60237ef5fc0a886d127031d16e04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10117">issues.joomla.org/joomla-cms/10117</a>.</sub>

**Comment by JurgenG** [comment]
Okay... so I did a bad bad thing... I submitted 2 bugs in 1 report. They are related though.
The first part of my video points out the solved issue. The second part (from 1:15) points out a second bug in the javascript...

(I will remove this video in 1 month from now):
https://dl.dropboxusercontent.com/u/7584025/troubleshooting.ogv

Clearly, the JS checks if the resp. is true ... and if it's not, it goes to "else".
There should be an elseif, discerning inherited from false.

**Comment by brianteeman** [comment]
Please create a new issue for the second part.

**Pull request merged**
