### PR TITLE
scrabble96 #26160

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue #26160
### Summary of Changes
Removed two lines of code (79 and 84) as IE11-related and not necessary.

### Testing Instructions
Create com_content category override. Remove the two lines from blog.php
Create or view a category blog.

### Expected result
The blog should display correctly

Summary of Changes, Testing Instructions and Expected result are copied from #26160 by @franz-wohlkoenig

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This one too please:

https://github.com/joomla/joomla-cms/blob/d268dc1aa8fde011b46a1c66efdaa84eea8a4d66/components/com_content/tmpl/featured/default.php#L35

And fix indentation.

**Comment by brianteeman** [comment]
Did you mean to delete that scss file?

**Comment by N6REJ** [comment]
@SharkyKZ thats everything right?

**Comment by brianteeman** [comment]
Now you are just deleting two files

**Comment by N6REJ** [comment]
crud.. fine.. one sec.

**Comment by SharkyKZ** [comment]
It's best to create a new branch for each PR instead of working on 4.0-dev.

**Comment by N6REJ** [comment]
@SharkyKZ yeah, I messed that part up.. I created the branch but then moved it.. 
break my 4.0 from it please so I can reset the fork and make new branches

**Pull request closed without merging**
