### PR TITLE
[5.1] GuidedTours: No error when joomla-welcome is missing

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
When an update of Joomla failed and the joomla-welcome guided tour wasn't added to the database, a big warning is displayed at the top of the backend dashboard. This PR adds another check to make sure we loaded anything in the first place before accessing it.

### Testing Instructions
1. Install Joomla
2. Delete the `joomla-welcome` from `#__guidedtours`
3. Login to the backend.

### Actual result BEFORE applying this Pull Request
Big warning at the top of the screen.

### Expected result AFTER applying this Pull Request
No warning.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 8036900460f9d0eb5ddea4fc87b4c2a42d0bf747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43139">issues.joomla.org/tracker/joomla-cms/43139</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8036900460f9d0eb5ddea4fc87b4c2a42d0bf747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43139">issues.joomla.org/tracker/joomla-cms/43139</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43139">issues.joomla.org/tracker/joomla-cms/43139</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Hackwar and also for testing @obuisard  and @Quy

**Pull request merged**
