### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jeckodevelopment**
### Summary of Changes
Added our Code of Conduct as suggested by GitHub.
immagine

Code of Conduct is the one published here: https://www.joomla.org/about-joomla/the-project/code-of-conduct.html

### CODE REVIEW

**Comment by wojsmol** [comment]
@wilsonge @jeckodevelopment Do we wont `CODE_OF_CONDUCT.md` in distributed packages?

**Comment by jeckodevelopment** [comment]
@wojsmol well, that can be avoided

**Comment by wojsmol** [comment]
@jeckodevelopment Yes but not after this PR, simplest way is by moving this file to .github folder.

**Comment by jeckodevelopment** [comment]
I'm doing a PR for that

**Pull request merged**
