### PR TITLE
Adding missing language flags

### PR DESCRIPTION
**Pull request by infograf768**
Adds the missing flags for Norwegian Nynorsk nn-NO and Uyghur ug-CN
Correcting uppercase for Sinhala si-LK

### CODE REVIEW

**Comment by infograf768** [comment]
can be merged on review.
@Bakual
@wilsonge 

Thanks.

**Comment by wilsonge** [comment]
I'm slightly nervous about case changing on different file systems (remember that horrible bug we had with the composer classLoader file a few versions ago. But merging.

**Comment by infograf768** [comment]
No worry, @wilsonge
As stated in https://github.com/joomla/joomla-cms/pull/9089#issuecomment-181982490 the Uppercase created an issue. We do need that file to be named the same as other language flags gif. 
it was a mistake when the gif was added (by me...).
https://github.com/joomla/joomla-cms/commit/2a9cbcef9220170107d323ac6af434118fa39f20#diff-d2ee215aba9b60e460d748888ef10ffb

**Comment by Bakual** [comment]
@wilsonge Shouldn't be an issue here. Worst case is we get two flags on linux systems, one uppercase and one lowercase. But the uppercased one will not create any troubles at all. It's just a bit of unneeded webspace used.
It's not like we autoload the flags like we do with classes :smile:

**Pull request merged**
