### PR TITLE
[4.0] Renaming JViewGenericdataexception to GenericdataException

### PR DESCRIPTION
**Pull request by Hackwar**
We added the class JViewGenericdataexception into 4.0. Refactoring lots of code later, it feels very wrong to have this non-namespaced class and thus this here refactors all of that to a nicer namespaced version. It also removes yet another class from /libraries/joomla.

### CODE REVIEW

**Comment by brianteeman** [comment]
When I was doing the namespacing I wondered why this one wasn't - now I know. Thanks

**Comment by mbabker** [comment]
Can you use the more grammatically correct "GenericDataException" please?  It's been irking me since day 1 that the casing on the class name was funny but with namespaced classes there isn't a real need to not do it "right".

**Comment by Hackwar** [comment]
done

**Comment by Hackwar** [comment]
@wilsonge Do I need to do anything else to get this merged?

**Comment by wilsonge** [comment]
Nope. RIPs was failing when I last looked which has now been fixed. Thanks!

**Pull request merged**
