### PR TITLE
[4.0][api] delete banner from api like article

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #31130 .

### Summary of Changes

delete banner from api even if it is published status like article

### Testing Instructions
create a banner and publish it

DELETE   api/index.php/v1/banners/{id}

### Actual result BEFORE applying this Pull Request
error

### Expected result AFTER applying this Pull Request
you can delete it even if it is in status published

### Documentation Changes Required
?

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 8ff498e5bbc1a3508e0b62ef4ac8944909c67f31<br /><br />Perfect.

If the chose of directly delete the item from API we need to fix all others API<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31134">issues.joomla.org/tracker/joomla-cms/31134</a>.</sub>

**Comment by flo-the-cat** [comment]
I have tested this item :white_check_mark: successfully on 8ff498e5bbc1a3508e0b62ef4ac8944909c67f31<br /><br />Works as it should<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31134">issues.joomla.org/tracker/joomla-cms/31134</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31134">issues.joomla.org/tracker/joomla-cms/31134</a>.</sub>

**Comment by HLeithner** [comment]
not sure if this is the way to go (not only if direct delete should be allowed see #31130) also if the implementation is the best way.

**Comment by alikon** [comment]
that's 1 of the reasons i've not closed #31130....
but at some point in time ie before RC some decisions should be taken

**Comment by rdeutz** [comment]
removing RTC because a final decision isn't made https://github.com/joomla/joomla-cms/issues/31130#issuecomment-717230721<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31134">issues.joomla.org/tracker/joomla-cms/31134</a>.</sub>

**Comment by ghost** [comment]
a ´final decision´ isn't made since one month.

**Comment by alikon** [comment]
closing as per https://github.com/joomla/joomla-cms/issues/31130#issuecomment-737591574

**Pull request closed without merging**
