### PR TITLE
Remove unused postSaveHook methods

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #23403

### Summary of Changes
Remove unused postSaveHook methods (fallback to the default) and fix the error in the mentioned issue

### Testing Instructions
Delete newsfeed items

### Expected result
No errors, items deleted

### Actual result
Error message

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 51dfad1c2e832736f0969e6a0ed47b28940563fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23445">issues.joomla.org/tracker/joomla-cms/23445</a>.</sub>

**Comment by dgrammatiko** [comment]
@bembelimen you need to do anther PR in the staging repo to deprecate these methods... Just saying..

**Comment by mbabker** [comment]
A deprecation notice isn't needed when you're removing an overridden method from a parent class.  Removing it just means the parent class' definition will be used.  Same as with https://github.com/joomla/joomla-cms/pull/23303

**Comment by dgrammatiko** [comment]
@mbabker my bad then I should have checked that this was overriding the parent class...
@bembelimen ignore me... 😉

**Pull request merged**
