### PR TITLE
[com_fields] Properly sanitise "alias" in field

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #14497 .

### Summary of Changes
Passing the item language to the stringURLSafe method in the field table

### Testing Instructions
Save a field and check that the alias is sanitised as expected. In english there should be no change at all to the current behavior. In other languages transliteration may kick in depending on the field language (or site language) setting.

### CODE REVIEW

**Comment by laoneo** [comment]
Can you please adapt your change to the new name field. Thanks.

**Comment by zero-24** [comment]
@laoneo @Bakual  please check with the last changes

**Comment by laoneo** [comment]
Thanks @zero-24, for me it looks fine now.

**Comment by rdeutz** [comment]
merged on review and because successful tests in the original issue

**Pull request merged**
