### PR TITLE
Pull request regarding [RFC] Backend: Log Out Button #37109

### PR DESCRIPTION
**Pull request by anmode**
Pull Request for https://github.com/joomla/joomla-cms/issues/37109
Feature:
Put the Extra logout button outside the dropdown menu

Summary of Changes
I have just configured the administrator/modules/mod_user/tmpl/default.php file in the codebase.

Actual result BEFORE applying this Pull Request

Expected result AFTER applying this Pull Request

Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by richard67** [comment]
Have you noticed that there are other pull requests by other people for the same issue?

**Comment by anmode** [comment]
> Have you noticed that there are other pull requests by other people for the same issue?

yes @richard67 but there were some issues in those PRs that is why I request a new PR.  In one of the PR some checks failed and I guess one has base conflicts.

**Comment by brianteeman** [comment]
well this PR is no better :(

**Comment by anmode** [comment]
> well this PR is no better :(

Why :( ? I will make necessary changes in it soon.

**Comment by richard67** [comment]
Wouldn't it be more fair to give the authors of the other PRs the same chance to fix their PRs? And wouldn't it be more effective to focus on some other issue - we have enough of them - instead of one where already 2 other people are working on?

**Comment by anmode** [comment]
I have tested code on my localhost the extra log out button working fine! With same UI
If then too there js any error pls guide a little i will try to solve it

**Comment by anmode** [comment]
> Wouldn't it be more fair to give the authors of the other PRs the same chance to fix their PRs? And wouldn't it be more effective to focus on some other issue - we have enough of them - instead of one where already 2 other people are working on?

Well yes actually i thought couple of days passed on those PR and feature not fixed that's why i tried and generated it. 
So may i close this PR :(? Or let it open

**Comment by richard67** [comment]
It's not a question of working or not. It has to be accessible, it has to remove the then redundant logout option from the drop down ... all that has been discussed in the other PRs, #37183 and #37165 . Maybe you should check the comments in these PRs first and also the comments in the issue #37109 (which us not really an issue or bug but a feature request or proposal for UX improvement) so you don't make the same mistakes again as the other PRs did or still do.

You also waste our time with that just by the way if we have to explain the same things again here and there.

**Comment by brianteeman** [comment]
> > well this PR is no better :(
> 
> Why :( ? I will make necessary changes in it soon.

1. There are unrelated files in the pull request
2. You have removed ALL formatting from the file. So not only does it break the style guidelines it is now impossible to see here on github what has changed as you have changed EVERY line
3. Plus everything @richard67 said

**Comment by anmode** [comment]
> It's not a question of working or not. It has to be accessible, it has to remove the then redundant logout option from the drop down ... all that has been discussed in the other PRs, #37183 and #37165 . Maybe you should check the comments in these PRs first and also the comments in the issue #37109 (which us not really an issue or bug but a feature request or proposal for UX improvement) so you don't make the same mistakes again as the other PRs did or still do.
> 
> You also waste our time with that just by the way if we have to explain the same things again here and there.

Sorry my bad actually i m new to open source.
I will not repeat my mistakes actually i haven't checked the comments well. I also misunderstood something sorry for that.
I will work upon other issue :) and solve it keeping in mind all things

**Comment by richard67** [comment]
@anmode I suggest you close your PR in favour of #37183 , because that one seems to be closest to the right solution.

We appreciate that you have made your PR because it shows your interest on working on Joomla.

But it's not easy at the beginning when you start to collaborate with others on a huge software project.

You should not be disappointed or discouraged but try to learn from it.

There are many things you can do to help Joomla and get more familiar with using it and with the code. A good start is always to test other people's pull requests.

And sooner or later there will be an issue for which you can provide a fix and make a nice pull request.

**Comment by anmode** [comment]
> > > well this PR is no better :(
> > 
> > 
> > Why :( ? I will make necessary changes in it soon.
> 
> 1. There are unrelated files in the pull request
> 2. You have removed ALL formatting from the file. So not only does it break the style guidelines it is now impossible to see here on github what has changed as you have changed EVERY line
> 3. Plus everything @richard67 said

Yes sorry for that i haven't know about it, i will surely not repeat my mistakes.

**Comment by richard67** [comment]
Closing as stated above. Thanks for your contribution, and heads up. The next one will be better for sure.

**Pull request closed without merging**
