### PR TITLE
[4.0] copy paste error in comments

### PR DESCRIPTION
**Pull request by brianteeman**
code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 09de7974fea044e55cb9ca9f15fd5353853745c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34040">issues.joomla.org/tracker/joomla-cms/34040</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 09de7974fea044e55cb9ca9f15fd5353853745c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34040">issues.joomla.org/tracker/joomla-cms/34040</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
