### PR TITLE
[4.0] remove unused class

### PR DESCRIPTION
**Pull request by brianteeman**
Some of the admin modules have a class of list-group-flush that doesn't exist in the template so can be removed.

This simple pr removes it

### CODE REVIEW

**Comment by SharkyKZ** [comment]
It's used. It applies styling to child `.list-group-item` classes.

**Comment by brianteeman** [comment]
So where is it defined in the atum template stylesheets?

**Comment by SharkyKZ** [comment]
It's coming from Bootstrap.

**Comment by brianteeman** [comment]
weird - my ide doesnt find it

**Pull request closed without merging**
