### PR TITLE
Update phar wrapper to 3.1.2

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #25248 .

### Summary of Changes
Update typo3 phar wrapper to PHP 7+ Version. This should also fix issue #25248

### CODE REVIEW

**Comment by mbabker** [comment]
Unless there is a really good reason please don't pin to a specific version.

**Comment by HLeithner** [comment]
@mbabker is this better?

**Comment by mbabker** [comment]
Yes.

**Comment by wilsonge** [comment]
Haven’t checked what’s in the version upgrade. But the diff looks fine to me at a quick glance

**Comment by wojsmol** [comment]
@HLeithner `composer.lock` neds updating after https://github.com/joomla/joomla-cms/pull/25252 was merged.

**Comment by HLeithner** [comment]
done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 57a87630c96f7f417ddbf7eac1896520548c6b3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25251">issues.joomla.org/tracker/joomla-cms/25251</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
