### PR TITLE
[4.1] Improve template module position preview

### PR DESCRIPTION
**Pull request by brianteeman**
When you preview a template an outline chrome is displayed around each module 
To ensure that you can see all available module positions even if there is no published module in that position a dummy module is created.

This PR tweaks that so that a dummy module is only created if there is no module published in the position

### before
image

### After
image

### CODE REVIEW

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 3cb7a70aea45f828ea925cedd3776463dfd0f488<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37335">issues.joomla.org/tracker/joomla-cms/37335</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3cb7a70aea45f828ea925cedd3776463dfd0f488<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37335">issues.joomla.org/tracker/joomla-cms/37335</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37335">issues.joomla.org/tracker/joomla-cms/37335</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
