### PR TITLE
[4.0] Cache Handler

### PR DESCRIPTION
**Pull request by brianteeman**
In global config the cache handlers should not be displayed if the cache its is off

PR for #33716

@philetaylor I did this blind as I dont have any cache handlers available to me to test but hopefully it is correct

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 8d84deb7d013dd6ed8b468b5fba30ebe9b5eb5fb<br /><br />Works perfectly - thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33777">issues.joomla.org/tracker/joomla-cms/33777</a>.</sub>

**Comment by PhilETaylor** [comment]
https://user-images.githubusercontent.com/400092/117962783-8318ea80-b317-11eb-90f1-fd98667a46c1.mp4

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d84deb7d013dd6ed8b468b5fba30ebe9b5eb5fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33777">issues.joomla.org/tracker/joomla-cms/33777</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33777">issues.joomla.org/tracker/joomla-cms/33777</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
