### PR TITLE
[5.2] [Guided tours] dark mode colors do not contrast well against the overall interface

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

Guided tours popups do not have a good contrast against the Joomla backend.
It is very difficult to distinguish the tour popups from the rest and even know what the step targets are.
This PR proposes to improve the contrast and change the popup colors for dark mode. 
We are keeping visual cues from the light version (darker header color than the popup content).
The header color is the same color as the editor header, so that we keep colors similar in the template.

### Testing Instructions

Run any tour once in light and once in dark mode.
You can try and test in conjunction with PR#43825 (to fix the arrows).

### Actual result BEFORE applying this Pull Request

image

image

### Expected result AFTER applying this Pull Request

image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I didn't find any issue with the existing colours but if others do then this PR works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43854">issues.joomla.org/tracker/joomla-cms/43854</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1d3a1eeb2785eb08ae2798f43a8cb81bdfd295a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43854">issues.joomla.org/tracker/joomla-cms/43854</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1d3a1eeb2785eb08ae2798f43a8cb81bdfd295a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43854">issues.joomla.org/tracker/joomla-cms/43854</a>.</sub>

**Comment by ChristineWk** [comment]
OT: When checking in dark mode, I see this:

issue43854

**Comment by pe7er** [comment]
Thanks @obuisard !

**Comment by obuisard** [comment]
Thank you!

**Pull request merged**
