### PR TITLE
Description text to allow translation using Crowdin

### PR DESCRIPTION
**Pull request by horus68**
Description text to allow translation of the description field using Crowdin

### CODE REVIEW

**Comment by Bakual** [comment]
Does that description show up somewhere in the installation?

**Comment by brianteeman** [comment]
That doesn't look right to me

**Comment by brianteeman** [comment]
Only the value of <metadata><name>English (United Kingdom)</name> is displayed in the CMS

How is the value you want to change displayed in crowdin?

**Comment by Vario1979** [comment]
It is not a major issue, but it should be fixed. <description> tag for our lang should contain some info about participants and sponsors.

**Comment by Bakual** [comment]
The issue is because Crowdin doesn't allow to translate an empty string. Which means if there is nothing in the source, you can't add something in the translation. Which makes sense for a translation service.

However to my knowledge the description tag in that XML could as well be deleted as it is never shown anywhere in the CMS.
Thus my question would be why we even have the tag there :smile:

**Comment by infograf768** [comment]
>Thus my question would be why we even have the tag there 

I guess because at some point in 1.5, someone decided all lang xml should have a <description> :smile:
I checked and the description was included in 1.5.0 beta
`<description>Spanish language file for web installer</description>`

we could definitively take if off

**Comment by infograf768** [comment]
@Vario1979 

The format of the installation xx.xml is different from the the xx.xml in the packages.
It is distributed with CORE and, as such should only customize the author/Team in the `<author>` tag
Example:
```
<?xml version="1.0" encoding="utf-8"?>
<metafile
	version="3.4"
	client="installation">
	<name>French (Fr)</name>
	<version>3.4.2</version>
	<creationDate>September 2012</creationDate>
	<author>Joomla.fr</author>
	<copyright>Copyright (C) 2005 - 2015 Open Source Matters. All rights reserved.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<description></description>
	<files>
		<filename>fr-FR.ini</filename>
	</files>
	<metadata>
		<name>Français (Fr)</name>
		<tag>fr-FR</tag>
		<rtl>0</rtl>
	</metadata>
	<params />
</metafile>
```
The details of the Team can be included here if desired (The TT Coordination will do that when asked), example: 
http://community.joomla.org/translations/joomla-3-translations.html#prs-af

In any case, "sponsors", if any as I never had the case, should never be included.

**Comment by Bakual** [comment]
Closing in favor of https://github.com/joomla/joomla-cms/pull/8546

**Pull request closed without merging**
