### PR TITLE
Add a text function for plugins

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Similar text function for plugins as we do in #41079.

### Testing Instructions
- Open the back end
- Go to the url /administrator/index.php?option=com_installer&view=install
- Open the "Upload Package File" tab

### Actual result BEFORE applying this Pull Request
All strings are translated.

### Expected result AFTER applying this Pull Request
All strings are translated.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
After installing the patch, the following notice messages appear:

Notice: Only variables should be passed by reference in C:\xampp\htdocs\bugtesting5\joomla\plugins\content\contact\services\provider.php on line 38

Notice: Only variables should be passed by reference in C:\xampp\htdocs\bugtesting5\joomla\plugins\content\emailcloak\services\provider.php on line 37

And so on.

Doesn't seem to be a problem of this patch, but an underlying problem.
Assigning to `$container->get(DispatcherInterface::class)` a separate variable, solves this problem.

**Comment by laoneo** [comment]
Does the same issue happen also on the 4.4-dev branch. For me it gives the impression that you somehow screwed up Joomla. But the message is definitely not related to the current pr.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c1ec40129dc59e9b21db1d64ab8ab7215fa66be6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41081">issues.joomla.org/tracker/joomla-cms/41081</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c1ec40129dc59e9b21db1d64ab8ab7215fa66be6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41081">issues.joomla.org/tracker/joomla-cms/41081</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41081">issues.joomla.org/tracker/joomla-cms/41081</a>.</sub>

**Comment by laoneo** [comment]
This here helps to ease the transition. At the end of the day the template files should work the same, regardless if they are used in views, modules, plugins and layouts. So this here is needed to provide a similar context in all of them. There are legit use cases where template files are used in plugins. So this is fine for the current architecture. If one some point we harmonize the whole code base then it will be even easier when all the template files use the same functions.

**Comment by HLeithner** [comment]
polluting the namespace/class for all plugins doesn't make sense anyway, better use a trait and the plugin that really needs this functionality should use it.

**Comment by brianteeman** [comment]
Why is it only this plugin that is updated and not all the others

**Comment by HLeithner** [comment]
Also this doesn't look like a proper "template engine" when you have to write the code your self:
https://github.com/Digital-Peak/joomla-cms/blob/c1ec40129dc59e9b21db1d64ab8ab7215fa66be6/plugins/installer/packageinstaller/src/Extension/PackageInstaller.php#L53-L55

and don't have at least a `render()` function

**Comment by sandewt** [comment]
> and don't have at least a render() function

Hey does such a render function look like?
Isn't this a proven technique in Joomla to render? See among others.

https://github.com/Digital-Peak/joomla-cms/blob/c1ec40129dc59e9b21db1d64ab8ab7215fa66be6/plugins/content/vote/src/Extension/Vote.php#L118-L121

**Comment by laoneo** [comment]
> Why is it only this plugin that is updated and not all the others

I will do this in 5.0 once it is upmerged, similar to  #41079 and #41063.

> Also this doesn't look like a proper "template engine" when you have to write the code your self

As I said, this pr is made for the current architecture. If you want to change it go ahead and make a pr. This here is fine for what we have now. Not saying it is the gold solution.

**Comment by laoneo** [comment]
@brianteeman here we go #41092.

**Pull request merged**
