### PR TITLE
Fix html5 validation, handle "novalidate" attribute correctly.

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Fix html5 validation, handle "novalidate" attribute correctly.

### Testing Instructions
Open the form for create a new Article.
In the browser Developer console run next code:

1) Imitate "Validation enabled":
```javascript
Joomla.submitform('article.apply', document.getElementById('item-form'), true);
```
2) Imitate "Validation disabled":
```javascript
Joomla.submitform('article.apply', document.getElementById('item-form'), false);
```

### Expected result
1) **No form submission**. You should get native browser validation popup message "Fill this field" (near field) (or similar)
2) Form submitted

### Actual result
1) Form submitted.
2) Form submitted.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
applied PR, got in new and empty Article:
bildschirmfoto 2017-06-20 um 18 33 30
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Fedik** [comment]
@franz-wohlkoenig what is on your screenshot it is normal 😉 

need to look at different thing, see "Expected result"

**Comment by franz-wohlkoenig** [comment]
Using `Joomla.submitform('article.apply', document.getElementById('item-form'), true);` "Fill this Field" is shown.

Using `Joomla.submitform('article.apply', document.getElementById('item-form'), false);` got "Warning_ Field required: Title", which is expected. So a successsfully Test?

**Comment by Fedik** [comment]
@franz-wohlkoenig yes, that is correct 😉

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 325ae010e2543bbf868030b71f52cbf69247226e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16791">issues.joomla.org/tracker/joomla-cms/16791</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 325ae010e2543bbf868030b71f52cbf69247226e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16791">issues.joomla.org/tracker/joomla-cms/16791</a>.</sub>

**Comment by dgt41** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16791">issues.joomla.org/tracker/joomla-cms/16791</a>.</sub>

**Pull request merged**
