### PR TITLE
[5.2] UPD composer files, phpseclib/bcmath_compat 2.0.3

### PR DESCRIPTION
**Pull request by tkuschel**
Pull Request for Issue #44028 .

Updated composer files, b/c of fixed https://github.com/phpseclib/bcmath_compat/pull/6

### Summary of Changes

phpseclib/bcmath_compat from 2.0.2 to 2.0.3

~~The following 3 packages have also been updated as a side effect as expected:
maximebf/debugbar v1.22.3 to v1.22.4
friendsofphp/php-cs-fixer v3.59.3 to v3.64.0
phpstan/phpstan 1.12.0 to 1.12.2~~

### Actual result BEFORE applying this Pull Request
bcmath_compat:
The exception ArgumentCountError gives wrong given parameter length. see https://github.com/phpseclib/bcmath_compat/pull/6
for more details.

### Expected result AFTER applying this Pull Request
Fixed

### Link to documentations
- [X ] No documentation changes for docs.joomla.org needed
- [X ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tkuschel** [comment]
What did I do wrong here that the build test "continuous-integration/dron/pr with phpcs failed? Please help.

**Comment by richard67** [comment]
> What did I do wrong here that the build test "continuous-integration/dron/pr with phpcs failed? Is it correct that all files that are in the log file of the cs-fixer must be adjusted; so here in this case it is the **sprintf** which should be written as **\sprintf**, according to the phpcs.

@tkuschel If you check the changes in the `composer.lock` file from your PR, you will see that it doesn't only update the `phpseclib/bcmath_compat` dependency but also others, including the code style checker. I think that's the reason why it complains about unrelated files now. Maybe you have run a `composer update` (without any option) instead of `composer update phpseclib/bcmath_compat` for updtaing just that dependency?

**Comment by tkuschel** [comment]
Thank you for the detailed description, I have corrected this.

**Comment by brianteeman** [comment]
It would have been better if you did what @richard67 said and ONLY updated bcmath with this PR.

Other changes such as phpcs and changing the sprintf should be in their own pull requests.

**Comment by tkuschel** [comment]
> Other changes such as phpcs and changing the sprintf should be in their own pull requests.
That's a good point. I will pick this apart. I didn't imagine that the `composer update` would cause such work :-)

**Comment by richard67** [comment]
@tkuschel You haven't reverted yet the unrelated changes of other dependencies.

**Comment by tkuschel** [comment]
> @tkuschel You haven't reverted yet the unrelated changes of other dependencies.
Had no time, now it looks good. I had dependencies with other local branches.

**Review by wilsonge — APPROVED** [review]

**Comment by Hackwar** [comment]
Thank you for your contribution @tkuschel!

**Pull request merged**
