### PR TITLE
update sample brochure content

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #15513 

Removes the text "The module on the left shows a list of older articles." as there is no module on the left ;)

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 619bb2734d86a446cfadf24e1ee865ea751bae5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15526">issues.joomla.org/tracker/joomla-cms/15526</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 619bb2734d86a446cfadf24e1ee865ea751bae5d<br /><br />Tested in MySQL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15526">issues.joomla.org/tracker/joomla-cms/15526</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
