### PR TITLE
[4] Branch in switch is a duplicate, merge them

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Branch in switch is a duplicate, merge them

### Testing Instructions

Code review - in context

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on d0b81c4544c68d89421f6e0b1f2abfd71d69cbf8<br /><br />Tested successfully in Beta7-dev of 10 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31998">issues.joomla.org/tracker/joomla-cms/31998</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d0b81c4544c68d89421f6e0b1f2abfd71d69cbf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31998">issues.joomla.org/tracker/joomla-cms/31998</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31998">issues.joomla.org/tracker/joomla-cms/31998</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
