### PR TITLE
Routing: Remove IDs from SEF URLs

### PR DESCRIPTION
**Pull request by Hackwar**
This PR removes the IDs from the URLs when using the new advanced routing. To test, please enable "Use new URL routing" and "Remove IDs from URLs" in the components options in the backend. You can set this feature individually for com_contact, com_content and com_newsfeeds. When set to yes, the IDs are removed from the URLs of the respective component

### CODE REVIEW

**Comment by zero-24** [comment]
Hmm it looks like that the unit test fails? Can you have a look into it? https://travis-ci.org/joomla/joomla-cms/jobs/127058538

**Comment by Hackwar** [comment]
I've fixed the tests.

**Comment by Denitz** [comment]
It's illogical to name setting 'sef_ids' and assume 'true' to remove IDs.

It's more obvious to have setting 'sef_no_ids' with same values, otherwise 'sef_ids' equal to true should mean 'including IDs'.

Why com_tags is missed? It's more used than com_newsfeeds and is bascially core while com_newsfeeds should be decoupled.

**Comment by JoshuaLewis** [comment]
Is this PR still active? In other words has no one given a test for the new router? If not, I can get testers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10170">issues.joomla.org/joomla-cms/10170</a>.</sub>

**Comment by chrisdavenport** [comment]
Testers are very definitely needed and will be very welcome. :-)

**Comment by JoshuaLewis** [comment]
I keep getting the error "The file marked for modification does not exist: libraries/cms/component/router/rules/menu.php" when attempting to  install this on a fresh copy of Joomla 3.5.1 via com_patchtester 2.0.1. Other PR's generally install just fine, am I missing something?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10170">issues.joomla.org/joomla-cms/10170</a>.</sub>

**Comment by Hackwar** [comment]
This needs changes that have been merged earlier. 3.5 is too outdated for this. Get the latest copy of the branch that this PR points to.
Am 03.07.2016 10:34 nachm. schrieb Josh Lewis <notifications@github.com>:I keep getting the error "The file marked for modification does not exist: libraries/cms/component/router/rules/menu.php" when attempting to  install this on a fresh copy of Joomla 3.5.1 via com_patchtester 2.0.1. Other PR's generally install just fine, am I missing something?This comment was created with the J!Tracker Application at issues.joomla.org/joomla-cms/10170.

**Comment by JoshuaLewis** [comment]
I installed Joomla 3.6 RC1, installed com_patchtester 3.0a, but got the error message "Could not connect to GitHub: No commit found for the ref sef_no_IDs". I found the download package the message referred to: https://github.com/Hackwar/joomla-cms/tree/sef_no_IDs

However I'm assuming there is supposed to be a way to install this as a patch via GitHub from com_patchtester using J 3.6.0 as opposed to installing it as it's own stand alone installation?

**Comment by mbabker** [comment]
The way patch tester "patches" things isn't the same as a proper patch in a
version controlled environment so don't take issues with patch tester
acting up as a sign of an issue with the patch.

**Comment by JoshuaLewis** [comment]
Now that Joomla 3.6 stable is out, can we test this PR with com_patchtester? Or should this only be tested on the developer version of J 3.7? Some guidance on how to test this would help get testers. :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10170">issues.joomla.org/joomla-cms/10170</a>.</sub>

**Comment by ulelo** [comment]
Can you please provide some details for testing (using 3.6 stable)? It will be useful for testing, like JoshuaLewis said.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10170">issues.joomla.org/joomla-cms/10170</a>.</sub>

**Comment by roland-d** [comment]
@Hackwar Could you fix the merge conflicts as well? Thanks.

**Comment by Hackwar** [comment]
I've updated the branch to the latest 3.6.x branch state. To test this PR, you have to use the 3.6.x branch as the basis and then the patchtester can be used to apply this PR. Or you directly get a copy of my branch and test that with an existing Joomla database of your choice. You can test that nothing has changed when the new option in the component configurations has not been activated and all old URLs work like before and then you should enable the option for the different components and see that the IDs are gone as well as that the new URLs still display the desired page.

**Comment by JoshuaLewis** [comment]
When installing a fresh installation of Joomla 3.6.0 on SiteGround I can't use this PR patch.

com_patchtester 3.0.0 alpha I get the error "Could not connect to GitHub: No commit found for the ref sef_no_IDs".

com_patchtester 2.0.1 I get the error "The file marked for modification does not exist: libraries/cms/component/router/rules/menu.php".

I've re-fetched the list, made sure my GitHub credentials were in on both versions of com_patchtester. I tried other tricks to with no luck on being able to successfully use this PR. Can you confirm this issue on a fresh install of Joomla 3.6.0 and com_patchtester?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10170">issues.joomla.org/joomla-cms/10170</a>.</sub>

**Comment by infograf768** [comment]
`libraries/cms/component/router/rules/menu.php` is not present in 3.6.0 or staging.
It is only present in https://github.com/joomla/joomla-cms/tree/3.6.x

@wilsonge
As you bumped version to 3.7.0-dev, would it be sensible to change the tree name?

**Comment by wilsonge** [comment]
I have changed the branch name and merged staging back in. @Hackwar you'll need to just recreate the PR (just use the same branch) - unfortunately there's no way to get github to migrate the PR to the new branch :(

**Comment by Hackwar** [comment]
Please see #11320 for the updated PR

**Comment by JoshuaLewis** [comment]
@infograf768 The link you mentioned is no longer valid (I saw it work yesterday but wasn't feeling too well). So does the new PR require downloading the following? https://github.com/joomla/joomla-cms/tree/3.7.x

**Comment by wilsonge** [comment]
Yes :)

**Pull request closed without merging**
