### PR TITLE
[4.0] Category ALT text

### PR DESCRIPTION
**Pull request by brianteeman**
Continues the work of  #31318 and #31323 by correcting the behaviour of the alt text and changing the strings to match the work done in #31318

### Background
To read why this change is very important see #31318 

### Testing Part 1
Testing is really easy. No npm, js or css involved.
Merge the pull request and then create a content category and a contact category and add an image

image

### Testing Part 2
Please test three scenarios when adding an image for a menu item of Content Category Blog, Content Category List, Contact Category

1. Image Description (Alt Text) = Empty
No Description = unchecked

2. Image Description (Alt Text) = "some description"
No Description = unchecked

3. Image Description (Alt Text) = Empty
No Description = checked

The expected behaviour for each of these tests is

1.``
2. `some description`
3. ``
or ``

PLEASE do not comment on what you think the code does but apply the PR and test it. Getting very tired of people blocking PR with their comments without actually testing the code.

cc @carcam

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 206c8591f35f03b00c56e2bb62a8a391127d92b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31326">issues.joomla.org/tracker/joomla-cms/31326</a>.</sub>

**Comment by priyankaSahutekdi** [comment]
I have tested this item :white_check_mark: successfully on 206c8591f35f03b00c56e2bb62a8a391127d92b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31326">issues.joomla.org/tracker/joomla-cms/31326</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31326">issues.joomla.org/tracker/joomla-cms/31326</a>.</sub>

**Comment by ceford** [comment]
The **loading="lazy" ** is absent. Is that due to copy/paste instructions? Can you tell us under what conditions alt appears without =""?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31326">issues.joomla.org/tracker/joomla-cms/31326</a>.</sub>

**Comment by brianteeman** [comment]
Fixed the copy/paste error 

**Can you tell us under what conditions alt appears without =""**
Basically if it is alt="" then some browsers when you _inspect_ instead of _view source_ abbreviate alt="" to alt

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
