### PR TITLE
Improve option handling and fix format handling in the API

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/39495 .

### Summary of Changes
Fixes linked bug

### Testing Instructions
In a webservice plugin (either custom or in a core one in the core add the following lines to the `onBeforeApiRoute` event (i used the content webservice plugin - but any will do)

```
        \JFactory::getApplication()->addFormatMap('application/ld+json', 'jsonld');
        $router->addRoute(
            new Route(['GET'], 'v1/format', '', [], ['format' => ['application/vnd.api+json', 'application/ld+json'], 'component' => 'com_content'])
        );
```

Then in the libraries/src/Application/ApiApplication.php add var_dump($this->input->get('format'), $this->input->get('option'));die; after this foreach loop (both before and after testing)

Generate a Bearer token and curl the url e.g. `curl -H "Authentication: Bearer <bearer_token>" -H "Accept: application/ld+json" http://localhost/joomla-cms/api/index.php/v1/format`

### Actual result BEFORE applying this Pull Request
```
        array(2) {
          [0]=>
          string(22) "applicationvnd.apijson"
          [1]=>
          string(17) "applicationldjson"
        }
        string(11) "com_content"
```

### Expected result AFTER applying this Pull Request
```
        string(7) "jsonld"
        string(11) "com_content"
```

i.e. the second dump (the component) is unchanged and the former (the format) now contains the Joomla format and not the array of possible options from the plugin

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by nikosdion** [comment]
I have tested this item :white_check_mark: successfully on 83ac935618ed4ae0bb04656905e325aca396530c<br /><br />It works!

Just note that if you have `Accept: application/ld+json` you get the format `applicationldjson` instead of the expected `jsonld`.

To fix that, the plugin needs to have the following in its onBeforeApiRoute handler (where routes are registered):

```php
$this->getApplication()->addFormatMap('application/ld+json', 'jsonld');
```

Since this is the _expected_ behaviour of ApiApplication I consider my test successful. Thank you, George!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39498">issues.joomla.org/tracker/joomla-cms/39498</a>.</sub>

**Comment by nikosdion** [comment]
I re-read my test description and it's… unclear. What I meant to say is that if you do not follow George's instruction to use `addFormatMap` you will get the "wrong" format, which is the expected behaviour in the Joomla API application. Even though there's this little gotcha, since it's an expected and documented gotcha, it does not affect me on marking this test successful.

I'm gonna go get some coffee now.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 83ac935618ed4ae0bb04656905e325aca396530c<br /><br />Using a custom component and only adding `'format' => ['application/json']`


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39498">issues.joomla.org/tracker/joomla-cms/39498</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39498">issues.joomla.org/tracker/joomla-cms/39498</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
