### PR TITLE
[4.0] Codemirror proper Custom Element

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Since we are already concatenating a bunch of files for the code mirror I've concatenated 2 more...
- The custom element is not using Async/Await as this will fail to anything older than current ver of Evergreen browsers
- The element is using correctly mutation observers
- Calling document API's in the connectedCallback **NEVER** in the constructor!!!
- Proper bindings

### Testing Instructions
Apply patch, change browser to Code mirror and check if everything still works ok

### Documentation Changes Required
No, this just moves the code closer to production

### CODE REVIEW

**Comment by PhocaCz** [comment]
I have tested this item :red_circle: unsuccessfully on c2ad19d742a259bc8b8011f8682158f19f94e187<br /><br />
> Apply patch, change browser to Code mirror and check if everything still works ok

Did you mean "editor" instead of "browser"?

Testing now on Joomla! 4.0.0-alpha7-dev and get following results, see images:

Before patch
OK

After patch
NOT OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23426">issues.joomla.org/tracker/joomla-cms/23426</a>.</sub>

**Comment by infograf768** [comment]
This PR works fine here, **IF the site is not installed in a sub folder.**
**Before or after this patch**, if the site is installed in a subfolder (I am testing in sub/sub here), I get the same result as @PhocaCz

**Comment by dgrammatiko** [comment]
@PhocaCz @infograf768 should be fine now

**Comment by infograf768** [comment]
Drone is not happy. javascript-cs
```
/drone/src/github.com/joomla/joomla-cms/build/build-modules-js/javascript/compile-w-c.es6.js
   74:116  error  Missing semicolon  semi
  107:40   error  Missing semicolon  semi

✖ 2 problems (2 errors, 0 warnings)
2 errors and 0 warnings potentially fixable with the `--fix` option.
```

Concerning the patch, it is now working fine. :)

**Pull request closed without merging**
