### PR TITLE
Update cacert.pem to latest version

### PR DESCRIPTION
**Pull request by nicksavov**
Source: http://curl.haxx.se/ca/cacert.pem

### CODE REVIEW

**Comment by nicksavov** [comment]
Framework PR:
https://github.com/joomla-framework/http/pull/16

**Comment by zero-24** [comment]
@nicksavov do we have any chance to test the change?

**Comment by nicksavov** [comment]
Thanks Tobias!

I don't think testing is needed for this one and it can just be merged. It's just syncing the file with the official one at http://curl.haxx.se/ca/cacert.pem

Examples of two previous PRs for it that were merged without testing:
https://github.com/joomla/joomla-cms/pull/4296
https://github.com/joomla/joomla-cms/pull/3634

**Comment by zero-24** [comment]
hehe i have ask the same some time bevor in a previous PR :smile: So I'm going to mark it RTC so a Maintainer can review and merge. Thanks :smile:

**Comment by wilsonge** [comment]
Thanks Nick!

**Comment by brianteeman** [comment]
Shouldn't this be something that is always done as part of the release
procedure. Otherwise it will always be out of date and we will have
multiple pull requests to update the cert before we ever get to a release.

**Comment by nicksavov** [comment]
+1

**Comment by mbabker** [comment]
I'd rather see PRs to update it as appropriate in the off chance a change in the cacert manages to break a site's ability to connect to a resource because of certificate verification.

**Pull request merged**
