### PR TITLE
Update composer, polyfill-unserialize, j/string, j/utilities, polyfill-php73

### PR DESCRIPTION
**Pull request by HLeithner**
Update composer packages mainly for php 7.4 compatibility

### Summary of Changes
* joomla/string 1.4.2 -> 1.4.3 (php 7.4)
* joomla/utilities 1.6.0 -> 1.6.1 (php 7.4)
* symfony/polyfill 1.11.0 -> 1.12.0
  * polyfill-php73 1.11.0 -> 1.12.0
* brumann/polyfill-unserialize 1.0.3 -> 1.0.4 (php 7.4)

### Testing Instructions

Use test php 5.3-php7.4 normal joomla usage.

### Expected result

Everything works

### CODE REVIEW

**Comment by Hackwar** [comment]
Why are you adding composer.lock to the gitignore file?

**Comment by HLeithner** [comment]
It's not required for operation and it's also ignored in another package.

**Comment by Hackwar** [comment]
And how are we supposed to update that file in the future?

**Comment by brianteeman** [comment]
@hackwar is correct the composer.lock should not be in the .gitignore

It might be correct in other software packages where the user always has to run composer but thats not the case or joomla where composer is only used by those developing the cms

**Comment by HLeithner** [comment]
We don't the lock file for subpackages because they get updated with joomla composer.lock but I can put it back if you like. We keep some and some are ignored seam not 100% clear to me.

**Comment by mbabker** [comment]
Composer does not use the lock files from packages in the vendor directory for calculating the dependency tree, it is not needed to check anything matching `libraries/vendor/**/composer.lock` into the repository (I'll go so far as to say that package is wrong for checking in a lock file in the first place, libraries shouldn't be checking those in).

**Comment by Hackwar** [comment]
reading through this again, I misread the original commit. @HLeithner you were right in adding that to gitignore.

**Comment by HLeithner** [comment]
I only removed the composer.lock of polyfill-unserialize and phpmailer.
I would create a new PR for the suggested global composer.lock ignore including some other cleanups.

I would add the following files to the list (feedback is welcome)
* libraries/vendor/**/.appveyor.yml
* libraries/vendor/**/.gitattributes
* libraries/vendor/**/.gitignore
* libraries/vendor/**/.github
* libraries/vendor/**/.gitmodules
* libraries/vendor/**/.travis.yml
* libraries/vendor/**/composer.lock
* libraries/vendor/**/composer.json
* libraries/vendor/**/CONTRIBUTING.md
* libraries/vendor/**/LICENSE
* libraries/vendor/**/phpunit*
* libraries/vendor/**/README*
* libraries/vendor/**/test*
* libraries/vendor/**/UPGRADING.md

**Comment by mbabker** [comment]
All LICENSE files should be checked in AND shipped unless someone is going to create and maintain a singular file listing all licenses of all third party elements.

Don’t most licenses also have text along the lines of “you should have received a copy of the license with this software and if not contact us”?  There is a method to the madness used for what files were elected to be kept and what files stripped.

**Comment by HLeithner** [comment]
I thought the same about the license files. Doesn't matter if we include the license files or not, so better include them.

Which method do you refrer to? I didn't found more then the comment at top of the ignore file.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on bef949c665ab8d0a9ef9db9bfec1843eec2068a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26000">issues.joomla.org/tracker/joomla-cms/26000</a>.</sub>

**Comment by HLeithner** [comment]
thx for testing.

**Pull request merged**
