### PR TITLE
Fix error message is not displayed in com_config (#4653)

### PR DESCRIPTION
**Pull request by tranduyhung**
While building a custom JFormRule to validate the options in my custom component's configuration, I realize that the rule's error message is not displayed after redirecting back to the configuration form.

```
class JFormRuleFoo extends JFormRule
{
    public function test(SimpleXMLElement $element, $value, $group = null, JRegistry $input = null, JForm $form = null)
{
        // Validation fails, enqueue error message, it must be displayed when we are taken back to the form.
        JFactory::getApplication()->enqueueMessage(JText::_('Validation fails'), 'warning');
        return false;
}
```

}

But if we try to go to somewhere else

```
JFactory::getApplication()->enqueueMessage(JText::_('test'), 'warning');
JFactory::getApplication()->redirect('index.php');
```

Then the message is displayed as usual.

The problem is in https://github.com/joomla/joomla-cms/blob/staging/components/com_config/model/form.php#L313

It should be

```
foreach ($form->getErrors() as $message)
{
    if ($message instanceof Exception)
    {
        JFactory::getApplication()->enqueueMessage($message->getMessage(), 'error');
    }
    else
    {
        JFactory::getApplication()->enqueueMessage($message, 'error');
    }
}
```

### CODE REVIEW

**Comment by ysavran** [comment]
Issue is fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4654">issues.joomla.org/joomla-cms/4654</a>.</sub>

**Comment by roland-d** [comment]
@tranduyhung Can you fix the merge conflicts and check if the issue still exist? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4654">issues.joomla.org/joomla-cms/4654</a>.</sub>

**Comment by tranduyhung** [comment]
I fixed the merge conflict. Thank you @roland-d for your letting me know.
Tested again and the problem was still fixed.

**Comment by zero-24** [comment]
@joomdonation can you retest the last changes? Than we can RTC ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4654">issues.joomla.org/joomla-cms/4654</a>.</sub>

**Comment by joomdonation** [comment]
Hi

Infact, this PR could be closed. The issue is not valid anymore because it was fixed with this PR https://github.com/joomla/joomla-cms/pull/6439

**Comment by roland-d** [comment]
Closing as requested. Thanks @joomdonation

**Pull request closed without merging**
