### PR TITLE
4.0 Removed hardcoded error reporting levels from CLI scripts

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Removed the hardcoded "maxmium, shout all the stuff out there" error-reporting level from the CLI scripts to respect the php.ini value.

### Testing Instructions
Add the line `brokenCode();` in front of `$app = \Joomla\CMS\Factory::getContainer()->get(\Joomla\Console\Application::class);` of the /cli/joomla.php. Run via CLI, find a fatal error outputted. Apply patch, run again - system now uses php.ini values for error reporting.

### Expected result
php.ini settings for error reporting being used.

### Actual result
Forced output of error messages.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4407635823da52c618e0b2d128e492df7081450a<br /><br />Tested ok

I wonder why it was put there in the first place?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20027">issues.joomla.org/tracker/joomla-cms/20027</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 4407635823da52c618e0b2d128e492df7081450a<br /><br />During my first attempts with Joomla CLI I tested this successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20027">issues.joomla.org/tracker/joomla-cms/20027</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 4407635823da52c618e0b2d128e492df7081450a<br /><br />During my first attempts with Joomla CLI I tested this successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20027">issues.joomla.org/tracker/joomla-cms/20027</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20027">issues.joomla.org/tracker/joomla-cms/20027</a>.</sub>

**Pull request merged**
