### PR TITLE
[4.0] Small typo

### PR DESCRIPTION
**Pull request by astridx**
I changed `diV` to `div` because it confused me.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d9e0db0ba27a50da3ca481c6c1c316758bc49ea5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26446">issues.joomla.org/tracker/joomla-cms/26446</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d9e0db0ba27a50da3ca481c6c1c316758bc49ea5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26446">issues.joomla.org/tracker/joomla-cms/26446</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26446">issues.joomla.org/tracker/joomla-cms/26446</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
