### PR TITLE
Add component (before and after) to debugger Profile Information

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds component to debugger `Profile Information` table.
It has two lines in the debugger `beforeRenderComponent` and `afterRenderComponent` just like exists for the modules.

Before:
image

After:
image
#### How to test
1. Apply this patch.
2. Turn on the debug in global config and the debug system plugin.
3. Go to frontend and check if the two lines are in the `Profile Information` table.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 174aed8e5950cacafc9f30b679f183d91ce7e83e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8882">issues.joomla.org/joomla-cms/8882</a>.</sub>

**Comment by alikon** [comment]
tested successfully

**Comment by andrepereiradasilva** [comment]
@alikon please mark as "Tested successfully" in "Joomla! Issue Tracker" https://issues.joomla.org/tracker/joomla-cms/8888 (after login the "Test this" button appears).
For more information see https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 174aed8e5950cacafc9f30b679f183d91ce7e83e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8882">issues.joomla.org/joomla-cms/8882</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@joomla-bot 2 tests. are you waked?

**Comment by andrepereiradasilva** [comment]
@dgt41 seems joomla-bot only respond to your commands :wink:

**Comment by dgt41** [comment]
@andrepereiradasilva somebody needs to set the label `RTC`, the bot won't do it itself!

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 174aed8e5950cacafc9f30b679f183d91ce7e83e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8882">issues.joomla.org/joomla-cms/8882</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot obey to @andrepereiradasilva commands 😄

**Comment by andrepereiradasilva** [comment]
ehheh. Thought he had some AI.

**Pull request closed without merging**
