### PR TITLE
[4.0] added lang files folder in actionlogs.xml

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - Languages folder not included in actionlogs.xml.

### Summary of Changes
Added missing `<languages>
		<language tag="en-GB">en-GB.plg_system_actionlogs.ini</language>
		<language tag="en-GB">en-GB.plg_system_actionlogs.sys.ini</language>
	</languages>`

### CODE REVIEW

**Comment by infograf768** [comment]
This is also missing in 3.9.x

**Comment by bahl24** [comment]
Ok will add it shortly.

**Comment by infograf768** [comment]
When done in 3.9, then it will later on be merged to 4.0.
Imho maybe better to just do it in 3.9.

**Comment by bahl24** [comment]
Closed. See https://github.com/joomla/joomla-cms/pull/24426

**Pull request closed without merging**
