### PR TITLE
[4.0] Replace inline style width 15% with w-15

### PR DESCRIPTION
**Pull request by Quy**
Continuation of PR #28692

### Summary of Changes
Replace inline style width 15% with w-15

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 755f065219ef4477e8d8e7f658e67caa1a8e530a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28969">issues.joomla.org/tracker/joomla-cms/28969</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 755f065219ef4477e8d8e7f658e67caa1a8e530a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28969">issues.joomla.org/tracker/joomla-cms/28969</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28969">issues.joomla.org/tracker/joomla-cms/28969</a>.</sub>

**Comment by rdeutz** [comment]
Do we really need to set it !important ?

**Comment by Quy** [comment]
Confirmed !important is not required. Thanks.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
