### PR TITLE
bugfixes and improvements for html5fallback

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Set the file to  "use strict" which immediately revealed a couple of bugs.
There's no JS coding style standard but I reformatted to be similar to Joomla's PHPCS standard
Added docblock style comments
Moved the browser feature sniffing out of the class so that it only executes once instead of once per form. 

There are more things that could be improved in this file but this should do for now.

### CODE REVIEW

**Comment by sovainfo** [comment]
See http://joomla.github.io/coding-standards/?coding-standards/chapters/javascript.md
for JS Coding Standard

**Comment by okonomiyaki3000** [comment]
Oh! thanks!

**Comment by okonomiyaki3000** [comment]
Hmm. Why is our PHP standard like:

```php
if ($something) 
{
    doSomething();
}
```

But our JS standard like:

```javascript
if (something) {
    doSomething();
}
```

**Comment by Fedik** [comment]
Because different languages, with different history, I guess :wink:
and 
```javascript
if ($something) 
{
    doSomething();
}
```
in javascript looks not good (from my point of view), it like use in css:
```css
.style
{
   color: #fff;
}
```

**Comment by wilsonge** [comment]
Because the PHP standard is our own whereas like 80% of our javascript stuff came from the jQuery standard I think

**Comment by Fedik** [comment]
+ https://github.com/rwaldron/idiomatic.js

**Comment by okonomiyaki3000** [comment]
fixed some merge conflicts that came up somehow

**Comment by zero-24** [comment]
@okonomiyaki3000 do you expect that this file has no content now: https://github.com/okonomiyaki3000/joomla-cms/blob/fix-html5fallback/media/system/js/html5fallback.js

?

**Comment by okonomiyaki3000** [comment]
Hmm. Probably not. Let me have a look.

**Comment by okonomiyaki3000** [comment]
I hope that, at some point, we'll be converting all the names of these files from using the `-uncompressed` naming scheme to using the `.min` naming scheme. Also, I bet there are some obsolete files in this directory.

**Comment by designbengel** [comment]
Testinstructions missing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by roland-d** [comment]
Hello @okonomiyaki3000 

Thank you for your contribution.

The last comment here was on 24th October. So the question is, Is this issue/pull request still valid?
if so please provide clear test instructions to be able to test / reproduce this issue.
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by okonomiyaki3000** [comment]
The problems with this code are not apparent unless javascript is being run in "strict" mode so the first thing you need to do to test it is to put:
```javascript
"use strict";
```
Just inside the closure. Then, go to any page that uses the html5fallback file. The article edit page in the administrator, for example. Look in your browser's console. You should see some errors. This patch fixes those errors.

**Comment by roland-d** [comment]
@okonomiyaki3000 I am confused, how could I test this? I can't seem to turn off HTML5 in the browser. Should I use some old browser?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by okonomiyaki3000** [comment]
@roland-d The first thing you have to understand is that this file is pretty badly named. It's not like something that only runs on old browsers. It runs anyway but it provides some polyfills for old browsers. 

To understand what's fixed, you must understand what was broken. You'd never notice because the original file was not in strict mode. Add `"use strict"` at the top of the closure in the original file and then open a page where this file used and look in your console. There should be some js errors. Probably none of the javascript on the page will work. Then switch to the updated file. Everything will work again. That is what is fixed.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 7c3f758f4da6ee2430617db288fc24a4c657b04b<br /><br />@okonomiyaki3000 Thank you, that was clearing things up. I was able to spot the errors and they were resolved after applying the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Little by little, I want to get all of joomla's js files to use strict mode and I think it should be required for any new JavaScript.

**Comment by roland-d** [comment]
We should see if we can enforce that for new files and implement it for existing files since it promotes better coding.

**Comment by Fedik** [comment]
:+1: I am also for make `"use strict"` required

**Comment by andrepereiradasilva** [comment]
:+1: for use strict

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 7c3f758f4da6ee2430617db288fc24a4c657b04b<br /><br />Tested the patch
"Use strict" is visible after applying and the website is still working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by conconnl** [comment]
@okonomiyaki3000 i just found out that this patch creates issues in the configuration screen of Joomla, as you can see in my screenshotscreen shot 2016-06-25 at 06 12 36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by roland-d** [comment]
@okonomiyaki3000 I can confirm the finding by @conconnl The error thrown is:
Error: TypeError: features.fields is undefined
Source File: http://localhost:8888/joomla-cms/media/system/js/html5fallback-uncompressed.js
Line: 383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Thanks @conconnl, @roland-d! This should fix the issue.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 108cfdbfb10d0370fb0a4bdeed8c3e3e5c564fdb<br /><br />With the last change all is working fine now on frontend and backend as far as I can see.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 108cfdbfb10d0370fb0a4bdeed8c3e3e5c564fdb<br /><br />Retested everything, it's working fine now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6409">issues.joomla.org/joomla-cms/6409</a>.</sub>

**Comment by wilsonge** [comment]
Merged with a585c9b - Thanks!

**Pull request closed without merging**
