### PR TITLE
Delete form.xml since outdated since J!1.6

### PR DESCRIPTION
**Pull request by jo-sf**
Pull Request for Issue 10694 .

Delete the file `components/com_contact/models/forms/form.xml` from future versions of Joomla since it is no longer valid.

### CODE REVIEW

**Comment by bertmert** [comment]
Sorry, have some problems to understand ;-)
https://github.com/joomla/joomla-cms/pull/10730

**Comment by jo-sf** [comment]
See also PR #10694 

I think the deleted file shall be added to `administrator/components/com_admin/script.php` but I'm not sure with which Joomla version this patch will be applied.

**Comment by jo-sf** [comment]
@bertmert 
Since @brianteeman commented in PR #10694 that I should submit a PR to remove the outdated file I did so - I assume that your PR #10730 would have done as well (but it is already closed).

**Comment by infograf768** [comment]
To consider it as deprecated but still let use it for B/C (unlikely used but one never knows...), it should not be added to deleteUnexistingFiles() in script.php.

**Comment by brianteeman** [comment]
Closed see #16007

**Pull request closed without merging**
