### PR TITLE
[4.0] Submenu items not modules

### PR DESCRIPTION
**Pull request by SharkyKZ**
Redo of #26245. Pull Request for Issue #25993.

### Summary of Changes

This removes incorrectly place module action icon from `mod_submenu` and other code mistaking submenu items for modules.

### Testing Instructions

View System Dashboard.

### Expected result

Still works but no more misleading module action next to submenu items.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f389cdde17b55d8c7a2855c33b824f79772b5be7<br /><br />Remains to solve https://github.com/joomla/joomla-cms/pull/26245#issuecomment-529809452<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26600">issues.joomla.org/tracker/joomla-cms/26600</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f389cdde17b55d8c7a2855c33b824f79772b5be7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26600">issues.joomla.org/tracker/joomla-cms/26600</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26600">issues.joomla.org/tracker/joomla-cms/26600</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
