### PR TITLE
Update registration.php: Messages to unfinished actions should be warnings.

### LINKED ISSUE #23763: Message requiring to log in should be of type Notice (blue) or Warning (yellow) instead of Message (green)
### Steps to reproduce the issue

* Register a new arbitrary user.
* Log out of all the Joomla frontend.
* Wait for the activation e-mail and activate the account by clicking on the link.

### Expected result

A non-green (an unaccomplished event) message or notice should appear. It can be blue Notice or yellow Warning as in https://docs.joomla.org/Display_error_messages_and_notices

### Actual result

A green (successful event) message appears. The text is great and valid, but it is misleading about successful event.

### System information (as much as possible)

Joomla 3.9.2

### Additional comments

This behavior changed in the last months. Previously it was possible to activate accounts unless the respective administrator was logged out. Now, it is required that the administrator (or similar user) logs in. That is a valid requirement and a good change in the code, IMO. But visually nothing changed, only the message and the process changed. The message is still green as in "successful valid action completed". That is misleading. Action is required to finish the validation process.

All it is a corrected optical aid. Of course, it is no excuse that the message was interpreted falsely by the user... Or is it? ]:->

### PR DESCRIPTION
**Pull request by kofaysi**
Pull Request fixes #23763.

### Summary of Changes

Changed type of message from default (message) to warning.

### Testing Instructions

Set administrator confirmation to required, when new users are registering.
* Register a new arbitrary user.
* Log out of all the Joomla frontend.
* Wait for the activation e-mail and activate the account by clicking on the link.

### Expected result

A Warning (yellow) message appears. The action hasn't been accomplished yet. (Please log in to confirm that you are authorised to activate new accounts.)

### Actual result

A green (successful event) message appears. The text is great and valid, but it is misleading about the event -- action has to be taken.

### Documentation Changes Required

IDK about any

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 8658030c7fdadf30696a50c4f546a288e6d7676c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24081">issues.joomla.org/tracker/joomla-cms/24081</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a2b6485998384032a5a40375eaf61c26e2440738<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24081">issues.joomla.org/tracker/joomla-cms/24081</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24081">issues.joomla.org/tracker/joomla-cms/24081</a>.</sub>

**Comment by HLeithner** [comment]
@kofaysi did you mixed you branch? because the nowrap shouldn't be in this pr

**Comment by kofaysi** [comment]
Yes, I see that did mix them up. The bad thing is that I do not recall where did I make the mistake. (I remember I even deleted the forked repository to be sure that I'm PR-ing a single new suggestion.) The worse thing is that I do not know, how to correct the merge.

**Comment by Quy** [comment]
Simple PR to merge.

**Comment by ghost** [comment]
@kofaysi can you please resolve conflicting file so Release Lead @HLeithner can merge if he decide to?

**Comment by HLeithner** [comment]
@kofaysi simply revert the change and commit it to this branch.

**Comment by kofaysi** [comment]
I'm sorry, but I don't think it is possible in the web interface after I deleted the branch, isn't it? 

(I learned from the issue and I'll be ignoring the "safe to deleted branch after creating a PR" notification and I'll be keeping all my branches named after the PR number until the PRs are closed.)

**Comment by Quy** [comment]
Since it is a minor change, close this PR and open a new PR.

**Pull request closed without merging**
