### PR TITLE
[4.0] sidebar layout alpha class

### PR DESCRIPTION
**Pull request by brianteeman**
The class hidden-sm-down was removed from bs between bs4 alpha and the final release with d-none d-md-block

### testing
probably just code review as I dont think core uses this

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 599bbef325bcd737c2d682d1b04dc30930cbf77f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26519">issues.joomla.org/tracker/joomla-cms/26519</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 76dd8eee141dfac304a169e957e76a5e03bcd1cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26519">issues.joomla.org/tracker/joomla-cms/26519</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26519">issues.joomla.org/tracker/joomla-cms/26519</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
