### PR TITLE
MFA: ignore non html requests

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #38476 and #38436 .

### Summary of Changes

MFA redirect should not happen on non HTML request

### Testing Instructions
Please follow #38436 and #38476

### CODE REVIEW

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on 1fd81f6c8d984bedc11f6e4e1d8af8c439d86b85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38492">issues.joomla.org/tracker/joomla-cms/38492</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1fd81f6c8d984bedc11f6e4e1d8af8c439d86b85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38492">issues.joomla.org/tracker/joomla-cms/38492</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38492">issues.joomla.org/tracker/joomla-cms/38492</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Comment by roland-d** [comment]
@nikosdion Thank you for catching this. I have reverted this now and we can check later how it should be handled as it does show an error when users click on the button.

As for contacting the code owner, I understand that but I never thought about contacting a code owner because I was not triggered by anything. Yes, I know you contributed this code but I do not know that for every feature in Joomla. Having some kind of notification to contact the code owner would be helpful. Perhaps we should add you to the codeowners file if that helps, I do not know.

**Comment by richard67** [comment]
@roland-d Shouldn't we re-open the 2 issues #38476 and #38436 as long as we don't have the solution?

**Comment by roland-d** [comment]
@richard67 Good point, we should only re-open 38476 as the fix was for that.

**Comment by nikosdion** [comment]
@roland-d I am always going through the commits before a new release because I am weird like that :p 

Regarding code ownership, I think there are two problems. One is GitHub and the other is the institutional knowledge gap which is a chronic Joomla pain.

I had been added in the `.github/CODEOWNERS` file for the WebAuthn plugin and the MFA. However, since I am a lowly Collaborator and not a full Member of the repo, GitHub would NOT auto-assign me as a reviewer for PRs touching my code. Therefore this change never made it to the repo. Even if you add me now, it will be for naught (and I think I was told it was creating problems, dunno?)

So, I have a question. Can I get into the CMS maintenance team? At this point I am pretty much doing the work anyway so if it means I can actually get to be notified for PRs touching security-sensitive code I have contributed so much the better. I'd prefer if there was a way to do that without having to carry a badge, albeit GitHub won't play ball. Well, in for a dime, in for a dollar.

@richard67 I had already said how we can address that problem:

> Another way to do it — best practice for 3PDs actually — is for the plugin to check if we're in a captive page and not execute. I am leaving this note not as something applicable to this PR but as something that a 3PD might stumble on. The rabbit hole will lead them to this comment here and they will figure out what to do next ;)

If you assign https://github.com/joomla/joomla-cms/pull/38436 and https://github.com/joomla/joomla-cms/issues/38476 to me I can make it happen, tomorrow, after a morning swimming session.

**Comment by richard67** [comment]
@nikosdion Assigned #38476 .

**Pull request merged**
