### PR TITLE
[4] s/JTable/Table

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on e88dcb51c805c1887962f0a565ac2f58209ee343<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34008">issues.joomla.org/tracker/joomla-cms/34008</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e88dcb51c805c1887962f0a565ac2f58209ee343<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34008">issues.joomla.org/tracker/joomla-cms/34008</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34008">issues.joomla.org/tracker/joomla-cms/34008</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
