### PR TITLE
[4.2] Convert mod_articles_archive to new structure

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Follow https://github.com/joomla/joomla-cms/pull/37445 , this PR convert mod_articles_archive  to new structure

### Testing Instructions
1. Use Joomla 4.2
2. Create an instance of Archived Articles module. Note how it works
3. Apply patch
4. Delete administrator/cache/autoload_psr4.php
5. Refresh the page, make sure the module still displays the same as before.

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by richard67** [comment]
It seems the PR has been messed by the PSR-12 conversion. @HLeithner Any idea? Maybe it would be easiest if @joomdonation does it again with a new PR?

**Comment by joomdonation** [comment]
@richard67 It is not easy to resolve the conflicts, so Yes, I will close the PR and  redo it at a later time.

**Comment by HLeithner** [comment]
@joomdonation sorry for the inconvenience and thanks for redoing it.

**Comment by joomdonation** [comment]
@HLeithner No problem. Thanks for your hard work on PSR-12 conversion.

**Pull request closed without merging**
