### PR TITLE
[4.0] Convert plugin user joomla to prepared statements

### PR DESCRIPTION
**Pull request by HLeithner**
# Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

Create/Change/Delete Users.

Login and Logout.

### Expected result
Nothing changed.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 1185a49da1a6733db33bd4d788e2fe01455213c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25543">issues.joomla.org/tracker/joomla-cms/25543</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1185a49da1a6733db33bd4d788e2fe01455213c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25543">issues.joomla.org/tracker/joomla-cms/25543</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25543">issues.joomla.org/tracker/joomla-cms/25543</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
