### PR TITLE
[4.1] com_scheduler columns

### PR DESCRIPTION
**Pull request by brianteeman**
The display of the columns in a row did not match the display of the headers at responsive breakpoints

## Before
zoom

## After
zoom

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1ac7d49bcf0e4ee28a8202db103eb8476ae6f1cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37503">issues.joomla.org/tracker/joomla-cms/37503</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ac7d49bcf0e4ee28a8202db103eb8476ae6f1cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37503">issues.joomla.org/tracker/joomla-cms/37503</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37503">issues.joomla.org/tracker/joomla-cms/37503</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
