### PR TITLE
Broken batch-modal layout

### PR DESCRIPTION
**Pull request by chmst**
http://issues.joomla.org/tracker/joomla-cms/7301.
batch-3 4 2-after-patch
batch-3-4-2

### CODE REVIEW

**Comment by mbabker** [comment]
The corresponding LESS file needs to be updated too please.

**Comment by chmst** [comment]
Thank you @mbabker, I added the change to the modal.less. And thank you  @zero-24 - I got lost in the tracker :)

**Comment by losedk** [comment]
Agree with the change. It also fixes the inline scroll in different modals.

**Comment by infograf768** [comment]
You have to indeed modify modals.less, BUT then run generatecss.php as Protostar is also using modals.less and its css has to be modified thrugh this CLI.

**Comment by infograf768** [comment]
I did a new PR which corrects this one:
https://github.com/joomla/joomla-cms/pull/7318

This one can be closed.

**Comment by Jay-Jay-OPL** [comment]
To whom it may concern,

I believe this was the last commit made to the Protostar Template before the public release of: Joomla 3.4.3.

If so, there is a bug found with the navigation menu in responsive "mobile" view when having long sub-menus.

These two threads report and provide screenshots of the current issue:

http://forum.joomla.org/viewtopic.php?f=706&t=891691

http://forum.joomla.org/viewtopic.php?f=706&t=892016

**Pull request closed without merging**
