### PR TITLE
[4.0] Replace box shadow by border

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #32255 .

### Summary of Changes
Replace box shadow by border

### Testing Instructions
See #32255: apply patch, clear cache and copmpare

### Actual result BEFORE applying this Pull Request
shadow around boxes is not attractive

### Expected result AFTER applying this Pull Request
border makes a clean structure

### CODE REVIEW

**Comment by infograf768** [comment]
It solves even more in Safari ;)

before patch
Screen Shot 2021-02-09 at 09 53 08

after patch
Screen Shot 2021-02-09 at 09 59 40

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 833a065e12df597a73ef7bc2cef75d008711e0e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32361">issues.joomla.org/tracker/joomla-cms/32361</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 833a065e12df597a73ef7bc2cef75d008711e0e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32361">issues.joomla.org/tracker/joomla-cms/32361</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 833a065e12df597a73ef7bc2cef75d008711e0e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32361">issues.joomla.org/tracker/joomla-cms/32361</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32361">issues.joomla.org/tracker/joomla-cms/32361</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
