### PR TITLE
Remove word options

### PR DESCRIPTION
**Pull request by brianteeman**
Most tabs in the options tab dont have the word option in the title. Some did. This PR removes them.

See screenshots 
### tag before

tagged-before
### tag after

tagged-after
### redirect before

redirect-before
### redirect after

redirect-after
### articles before

article-before
### articles after

article-after
### banners before

banner-before
### banners after

banner-after

### CODE REVIEW

**Comment by MAT978** [comment]
@test
#7474 works as described.
Great improvement
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7474">issues.joomla.org/joomla-cms/7474</a>.</sub>

**Comment by yanivRozenman** [comment]
works grate <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7474">issues.joomla.org/joomla-cms/7474</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing - Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7474">issues.joomla.org/joomla-cms/7474</a>.</sub>

**Comment by infograf768** [comment]
Conflicts

**Comment by brianteeman** [comment]
Conflicts resolved

**Pull request merged**
