### PR TITLE
[4.0] Use unset filter to unset created_by data if needed

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Our Form API has **unset** filter which is used to disallow changing certain data if the current user does not have permission to change. We use it to handle other fields such as ordering, published.... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_contact/src/Model/ContactModel.php#L194-L196 , so created_by should not be treated in different way.

### Testing Instructions
1. Modify this line of code https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/user.php#L138 to:

```php
<?php if (true) : ?>
```

2. Apply this PR to your Joomla 4 installation.

The purpose is to have the the hidden field always rendered so that you can use browser inspect element tool to change hidden input variable to change created by data of a record.

3. Login to administrator area of your site using a Manager account (by default, Manager account does not have permission to manage users, so he won't be allowed to change Created By data of article)

4. Access to Content -> Articles, click on an article to edit. Navigate to Publishing tab, look at **Created By** field, you will see that it is readonly, mean you are not allowed to change Created By of the article
created_by

5. Inspect that Created By element, try to change the value of the hidden input (which stores ID of the user who created that article) to a different value
inspect_created_by

6. Save article. Then edit it again, check and make sure **Created By** is not changed (it still keeps the original user, not change to the new user which you changed)

### Actual result BEFORE applying this Pull Request
Works, but has to override method `validate` in some model classes. Code is in-consistent with the way we handle other fields.

### Expected result AFTER applying this Pull Request
Works, do not need to override `validate` method in model classes to just unset the field. Code is consistent with how we handle other fields data.

### CODE REVIEW

**Comment by richard67** [comment]
@zero-24 @SniperSister Do you know if it had security related reasons why we did it like we did and not like proposed by this PR here for the created_by field?

**Comment by wilsonge** [comment]
> @wilsonge How do you think about this change?

Seems logical to me

**Comment by joomdonation** [comment]
Thanks @wilsonge. Could we have testing instructions by code review ? Or need real test?

**Comment by richard67** [comment]
> Could we have testing instructions by code review ? Or need real test?

Maybe a compromise: Real code review 😉 (joking)

**Comment by joomdonation** [comment]
For this kind of PR, it would be easier for someone who understand how our Form API works to review code than end-user testing. But if real testing is needed, I will try to write testing instructions :)

**Comment by richard67** [comment]
I don't really understand the Form API.

**Comment by joomdonation** [comment]
> I don't really understand the Form API

We could not understand/know everything :).

**Comment by wilsonge** [comment]
Umm because this is a recent security fix unfortunately I think this one needs testing @joomla/security FYI

**Comment by joomdonation** [comment]
OK. I updated the testing instructions. Hope it is clear enough for users to test.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9a09cac4c5fce799fe1f4b121649bce244fc3c5e<br /><br />With and without PR the change of user-id in dev-tools is not saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34303">issues.joomla.org/tracker/joomla-cms/34303</a>.</sub>

**Comment by joomdonation** [comment]
@zero-24 @SniperSister Could you please review this PR?

**Review by zero-24 — CHANGES_REQUESTED** [review]
Please also apply this to:
- Categories: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_categories/src/Model/CategoryModel.php#L371-L378
- Fields: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_fields/src/Model/FieldModel.php#L968-L975

Otherwise this looks fine.

**Comment by joomdonation** [comment]
@zero-24 Done with commit https://github.com/joomla/joomla-cms/pull/34303/commits/edf00212b28b6b61b177af420c53227c3e5b47b7

**Review by zero-24 — APPROVED** [review]

**Comment by zero-24** [comment]
> @zero-24 Done with commit [edf0021](https://github.com/joomla/joomla-cms/commit/edf00212b28b6b61b177af420c53227c3e5b47b7)

Thanks

**Comment by joomdonation** [comment]
@wilsonge Could this be merged by code review please? We now have one human test and approval from @zero-24 .

**Comment by wilsonge** [comment]
Yup I'm OK with that. Thankyou!

**Pull request merged**
