### PR TITLE
[4.0][admin menu] fix creating from preset on postgresql

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #26713 .

### Summary of Changes
use the ?? (Null Coalescing Operator) to get 1 instead of ""
redo of #25949

### Testing Instructions
create an admin using  Import a preset "Preset - Joomla Main Menu".

### Expected result
able to create admin menu

### Actual result
SQL ERROR:

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I don't think ID should be hardcoded. There's `Joomla\CMS\Table\Nested::getRootId()` method for getting root item ID.

**Comment by alikon** [comment]
correct, make perfect sense

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 180335d644efb6b014a6d1b43c3612c8e6ee7f3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26807">issues.joomla.org/tracker/joomla-cms/26807</a>.</sub>

**Comment by richard67** [comment]
@waader Please test. Thanks in advance.

**Comment by waader** [comment]
@richard67: I tested with postgresql and after selecting "Preset - Joomla Main Menu" no menu items where inserted.

**Comment by richard67** [comment]
Hmm, I had postgresql, too, have it for testing such PRs .. for me it worked .. strange. I have version 10.10. Does your postgresql log show any errors? On my Ubuntu Linux it is `/var/log/postgresql/postgresql-10-main.log`. On other OS, at least the file name should be similar.

**Comment by waader** [comment]
There is no error in the postgresql log and a look in _menu shows that records are inserted.

**Comment by richard67** [comment]
@waader So they are just not visible in the menu in backend, but in database the new records are there? @alikon Could that be a problem with nested table, lft and rgt?

**Comment by waader** [comment]
@richard67 Correct!

**Pull request closed without merging**
