### PR TITLE
Remove wrong implementation of display: box and line-clamp

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue # .

### Summary of Changes
In the Atum template I noticed a wrong implementation of the line-clamp property in combination with display box which throws a waring when using a CSS prefixer. This styling is also obsolete as truncating is added in the PHP code.

### Testing Instructions
Apply the patch and build the CSS. Go to modules and click on "New". Nothing is changed in the layout.

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct. Well the css might be (i dont know) but the intended behaviour is to truncate the text at 200 characters https://github.com/joomla/joomla-cms/blob/06ae97f00a47591f85260ebfd503567824e7482c/administrator/components/com_modules/tmpl/select/default.php#L64

**Comment by RickR2H** [comment]
As my CSS prefixer tripped over the code I noticed the wrong implementation of the CSS. I agree with the 200 character truncate. I'll just remove the wrong code.

**Comment by RickR2H** [comment]
@brianteeman thanks for the review

**Comment by brianteeman** [comment]
Confirming that chrome agrees the current css is wrong

image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c6f13334227f50b63a6db19d1adcda0e9e5756e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37272">issues.joomla.org/tracker/joomla-cms/37272</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c6f13334227f50b63a6db19d1adcda0e9e5756e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37272">issues.joomla.org/tracker/joomla-cms/37272</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37272">issues.joomla.org/tracker/joomla-cms/37272</a>.</sub>

**Comment by C-Lodder** [comment]
Browsers are only complaining because it hasn't been implemented properly. The feature is completely prefixed.

Just use (with `-webkit-` prefix):

```
&-caption {
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 3;
}
```

image

**Comment by RickR2H** [comment]
@C-Lodder I'm aware, but like @brianteeman said the text get truncated in the PHP. This was an old implementation to truncate by CSS to three lines. So code is obsolete.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
