### PR TITLE
[4.0]  Module Assignment menu function accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
This PR addresses some of the issues for #23911

Specifically numbers
2, 4, 6

There are others that need to be addressed relating to the actual lists themselves but I a not sure if the list is even remotely accessible so wish to tackle that in a desperate issue

### CODE REVIEW

**Comment by Quy** [comment]
Out of curiosity, should there be a space before `All` so screenreaders don't read them as one word?
`<span class="sr-only">Expand</span>All`

**Comment by infograf768** [comment]
> Out of curiosity, should there be a space before All so screenreaders don't read them as one word?

In any case, it looks like this is not compatible with languages where the order would be different, i.e. where the equivalent of the `Select` verb has to be placed after the `All` or `None` object.

I'm afraid the only solution is to create new strings of the type:
`COM_MODULES_EXPAND_ALL` etc.

**Comment by brianteeman** [comment]
Changed the approach to use an aria-label instead as it will allow better translation as highlighted by @infograf768 
Also re-ordered the language file

**Comment by brianteeman** [comment]
Could someone please fix drone

**Comment by HLeithner** [comment]
@brianteeman can you merge the latest changes into this branch please?

**Comment by brianteeman** [comment]
@HLeithner its not showing me that option or any merge issues

image

**Comment by HLeithner** [comment]
@brianteeman I have no idea why it doesn't work can you create a new PR please?

**Comment by brianteeman** [comment]
Done see #28250

**Pull request closed without merging**
