### PR TITLE
PostgreSQL - SQL error when adding a user note

### LINKED ISSUE #6262: Postgresql: Add user note gives an error
Try to add a user note. When hitting the save button you get an error due to a violation of a not-null-constraint in column "modified_user_id".

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

 Backend go to the User -> User Note ->  add a note
#### Expected result

the data are saved
#### Actual result

Got an ERROR  SQL NULL VALUE in column modified_user_id
#### System information

PostgreSQL 9.3.5
Joomla 3.4.0
#### Additional comments

Even on new note we need to add a value for NOT NULL FIELDS
fix #6262

### CODE REVIEW

**Comment by waader** [comment]
@test works for postgresql, mysql and mssql! Thanks @alikon!

**Comment by wilsonge** [comment]
This is one of those times where we should make the field not null actually I think

**Comment by alikon** [comment]
@wilsonge we need to review our data model constraints from the start
can you have a look at #6104

**Comment by waader** [comment]
Déjà vu at #6355. What´s the decision here?

**Comment by orware** [comment]
@alikon I've taken a closer look at this one and I would suggest the following set of changes instead (you would have to update the PR with these):
http://pastebin.com/6BCRMq75

The reason for the changes are:
1. In the current PR the review_time will always be set to the current date (even if the user selects a different date). It looks like currently with Notes we should allow for it to be empty (set to the Null Date for the Database)...here's the tooltip for the field: "Review Date is a manually entered date you can use as fits in your workflow. Examples would be to put in a date when you want to review a user or the last date you reviewed the user."
2. Even after making adjustments for the date in the JTable class, the User Notes List View doesn't correctly support the Postgres Null Date value (for the MySQL Null Date of 0000-00-00 00:00:00 it will just display a dash "-", for the Postgres Null Date it will display the actual 1970-01-01 00:00:00 date). I've added an additional change to the User Notes List view that changes that behavior and compares the stored Review Time against the current database driver's Null Date value instead so the output is consistent (at least across MySQL and Postgres).

I don't have any issues with the modified_user_id value being set the way it is so that part should be fine.

I've successfully tested things on my end with those modifications in place...hopefully if we can get the PR updated we can get some more people to officially test it as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed issue.
Confirmed PR resolves the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by brianteeman** [comment]
Multiple tests setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by wilsonge** [comment]
This breaks the review date functionality by always setting it to the last date the note was edited whereas you should be able to set it to any date or have the date as null. The last modified user change is correct but you need to fix the review time stuff before this can be merged

**Comment by brianteeman** [comment]
@alikon are you able to com up with a different solution based on @wilsonge comments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by alikon** [comment]
fixed  the review_time functionality  able to set it to any date (null included)
@brianteeman not so sure it is compliant with @wilsonge 
cause i'm not changing null constraints

**Comment by brianteeman** [comment]
Thanks I will test later today

**Comment by brianteeman** [comment]
Retested after the changes and I can successfully create a note and set the review date as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by wilsonge** [comment]
Nah I'm happy with this. I mean ideally the modified user and date wouldn't be set on note creation - but as we are already doing the modified date i'm happy to standardize on that

**Comment by smz** [comment]
Does this has issues with PHP 5.6?

**Comment by wilsonge** [comment]
Why are you experiencing any?

**Comment by smz** [comment]
... not me, but I can swear I saw Travis complaining with PHP 5.6... strange... everything seems OK now... :confused:

**Comment by smz** [comment]
ehmm... this seems to be the only PR still having a 3.4.2 milestone...

**Comment by zero-24** [comment]
@waader are you able to retest the last changes here? so we can RTC it for 3.4.2? Thanks :smile:

**Comment by zero-24** [comment]
Wrong button :smile:

**Comment by waader** [comment]
@retest works!

**Comment by zero-24** [comment]
RTC Thanks for testing and coding :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6265">issues.joomla.org/joomla-cms/6265</a>.</sub>

**Comment by wilsonge** [comment]
Merged

**Pull request closed without merging**
