### PR TITLE
[4.0] Fix smtp test mail and migrate related jquery code to es6

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #31981 .

### Summary of Changes
* Make password lock and show exclusive
* Fix upmerge typo issue
* Replace jquery code with es6 and move to passwordview js file

### Testing Instructions
* Test password fields
* Test smtp email settings as in #31724

### Actual result BEFORE applying this Pull Request
Smtp test mail with password didn't worked
View Password Icon and Modify button was visible at the same time which doesn't work.

### Expected result AFTER applying this Pull Request
Test E-Mail settings work and only "Modify" or "Show Password" Icon exists and work

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on f3b6f0ed814a4b584560dab56173c299d902c9f3<br /><br />The Modify button did not work at all.  

The Categories of this RP include JavaScript and NPM Change.  Does something special need to be done before or after the RP is applied in Joommla! Patch Tester?  I do not use NPM.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by wilsonge** [comment]
Yes this one will need npm to test (or one of the prebuilt packs)

**Comment by toivo** [comment]
@wilsonge where can I download one of the prebuilt packs to test this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by brianteeman** [comment]
@toivo on github
image

**Comment by ghost** [comment]
@toivo at end of this pr as always on github

image

**Comment by toivo** [comment]
@brianteeman @gostn thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by toivo** [comment]
@brianteeman @gostn - installing that version is far too complicated: "Environment Setup Incomplete
It looks like you are trying to run Joomla! from our git repository. To do so requires you complete a couple of extra steps first."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by wilsonge** [comment]
@toivo you shouldn't get that - the entire point of that binary is that it has all the environment dependencies (npm + composer) installed. I'll look later.

**Comment by ceford** [comment]
After applying the patch and npm ci I could not get to see the smtp plain text password at all, before or after save. Is that expected? I did not test sending a test email.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by HLeithner** [comment]
> After applying the patch and npm ci I could not get to see the smtp plain text password at all, before or after save. Is that expected? I did not test sending a test email.


yes that's expected, it's part of a security patch in j3

**Comment by HLeithner** [comment]
> @brianteeman @gostn - installing that version is far too complicated: "Environment Setup Incomplete
> It looks like you are trying to run Joomla! from our git repository. To do so requires you complete a couple of extra steps first."

Download https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/31999/downloads/38993/Joomla_4.0.0-beta7-dev+pr.31999-Development-Update_Package.zip and install it as update package to your j4 installation 

alternative you can install the full installation package: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/31999/downloads/38993/Joomla_4.0.0-beta7-dev+pr.31999-Development-Full_Package.zip

**Comment by toivo** [comment]
@HLeithner thanks for those links!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 5b384f101fe91c10d66813bea0d68e82f007bdbe<br /><br />Tested successfully in Beta7-dev installed from Joomla_4.0.0-beta7-dev+pr.31999-Development-Full_Package.zip.

The Modify button works fine.  The View Password button is not there but it is not needed, especially if it would change the functionality of the Sent Test Mail button in a way that is not obvious to an average webmaster.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by HLeithner** [comment]
I removed the eye button because it would only work if you enter a new password and would confuse people when they see no existing passwords. So the functionality would be very limited anyway. And I think disabling it if not modified and enable on modify could be more unexpected. ymmv

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5b384f101fe91c10d66813bea0d68e82f007bdbe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31999">issues.joomla.org/tracker/joomla-cms/31999</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
