### PR TITLE
[system messages] Add new options for custom title and/or hide title

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

The system messages are somewhat limited, since we can't change their title or even remove their title.

To solve this, this PR adds new options for system messages.
- Allows to hide the message title.
- Allows to add a custom title.

This PR also applies the changes need in all layouts (system, isis, protostar and beez3).

#### Testing Instructions

- Test if messages are working fine
- Then add the following code to the beggining of the `index.php` file of the Joomla templates (protostar, beez3, isis and hathor):
```php
JFactory::getApplication()->enqueueMessage('Test 1: Message without group (fallbacks to <code>message</code> group).');
JFactory::getApplication()->enqueueMessage('Test 2: Message in <code>error</code> group.', 'error');
JFactory::getApplication()->enqueueMessage('Test 3: Message in <code>notice</code> group.', 'notice');
JFactory::getApplication()->enqueueMessage('Test 4: Message in <code>warning</code> group.', 'warning');
JFactory::getApplication()->enqueueMessage('Test 5: Message in <code>message</code> group (will be in the same queue as test 1).', 'message');
JFactory::getApplication()->enqueueMessage('Test 6: Message in <code>message without title</code> group.', 'message', array('showTitle' => false));
JFactory::getApplication()->enqueueMessage('Test 7: Message in <code>notice with custom title</code> group.', 'notice', array('customTitle' => 'My custom title'));
JFactory::getApplication()->enqueueMessage('Test 8: Message in <code>notice with custom title</code> group (message 2).', 'notice', array('customTitle' => 'My custom title'));
```
- Check if the result is something like this (please not that in beez3 there is no message title):
image

An effort was made to preserve B/C with existent layout overwrites. You should also test this patch in a custom template that has a message layout override (in `/templates/<template-name>/html/layouts/joomla/system/message.php`) (or use the one of in isis without this PR changes).

Note that before this patch this messages would look like this:
image

#### Observations

@mbabker i had to change `JDocumentRendererHtmlMessage` and `enqueueMessage` (normal and legacy) to make this work with the new options, please check if everything is fine with this changes.

Any suggestions and/or improvements are welcomed.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@mbabker can you give a little help here?
what does this mean?
```
There was 1 failure:
1) JApplicationCmsTest::testRedirectLegacy
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (
         'message' => 'Test Message'
         'type' => 'message'
+        'options' => Array (...)
     )
 )
```

**Comment by mbabker** [comment]
The test is checking the returns from `getMessageQueue` since there is a B/C handler with adding messages to the message queue when calling the redirect method.  So any of the tests validating that behavior you'll need to add the new options array to the expectation.

**Comment by andrepereiradasilva** [comment]
thanks?
like this? https://github.com/joomla/joomla-cms/pull/9732/commits/eb3546951259423681798783cd675f86d71a0fe6

**Comment by mbabker** [comment]
Should be fine now that you have the comma in there :wink:

**Comment by andrepereiradasilva** [comment]
eheheh :) thanks a lot

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on 7b9e068b1b8439e12bd23f1bf9f5891e87c4dec3<br /><br />TEST OK
screen shot 2016-04-07 at 04 12 29
(J3.5.1, PHP 7)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on 7b9e068b1b8439e12bd23f1bf9f5891e87c4dec3<br /><br />Tested successfully on protostar, tested without B/C issues on a Warp Template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 7b9e068b1b8439e12bd23f1bf9f5891e87c4dec3<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by wilsonge** [comment]
Setting to needs review. I wanna sit down and think about whether serialzing the data is the right choice here (my gut is that it isn't but I'm at the end of a long day so could be just not thinking straight!)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i don't like it either, but i didn't find another way without creating a new message queue and preserving B/C. But please review when you have time. If you find a better method is fine by me.

**Comment by wilsonge** [comment]
OK. This is a 3.6 feature anyhow - but I promise I will look over it - hopefully over the next week or so - but if not @brianteeman is going to force me to have reviewed all the Needs Review issues in the next 3 weeks ⚠️

**Comment by andrepereiradasilva** [comment]
:wink:

**Comment by roland-d** [comment]
@andrepereiradasilva Can you please fix the merge conflict? Thank you.

**Comment by zero-24** [comment]
@wilsonge can we move this to RTC now if @andrepereiradasilva  get the merge conflicts fixed?

**Comment by wilsonge** [comment]
Yeah do it

**Comment by brianteeman** [comment]
@andrepereiradasilva can you fix the merge conflicts please and then this can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by andrepereiradasilva** [comment]
don't test yet

**Comment by andrepereiradasilva** [comment]
hum all seems fine but i get this notices/warning when appling the patch, after that all seem fine

> Notice: Undefined index: options in /path/to/joomla-staging/libraries/joomla/document/renderer/html/message.php on line 89
> Warning: array_replace(): Argument #1 is not an array in /path/to/joomla-staging/libraries/joomla/document/renderer/html/message.php on line 89

Probably because the patchtester send a message (Github api limit) to the before patch queue system and render it in the after patch system?

Don't have much time to look into it now. So if anyone can see if this is a problem that will exist on update please say.

**Comment by brianteeman** [comment]
@andrepereiradasilva you can avoid that by adding your github credentials to the patchtester options. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by brianteeman** [comment]
Tested ok in isis, protostar and hathor but in beez its not quite correct

screen shot 2016-08-02 at 05 38 59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 48f730417c5b2f11ae0242265eb4a3982d226e4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/joomla-cms/9732</a>.</sub>

**Comment by brianteeman** [comment]
@andrepereiradasilva can you look at the beez issue please and then we can get this tested and merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/tracker/joomla-cms/9732</a>.</sub>

**Comment by zero-24** [comment]
we have aslo conflicts here ;)

**Comment by mbabker** [comment]
This PR needs a new owner or it will have to be closed as abandoned.

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9732">issues.joomla.org/tracker/joomla-cms/9732</a>.</sub>

**Pull request closed without merging**
