### PR TITLE
[4.1] Restore post-installation messages

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #37480 .

### Summary of Changes

check token in $_GET

### Testing Instructions

see Issue

### Actual result BEFORE applying this Pull Request

not possible

### Expected result AFTER applying this Pull Request

possible again

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9e6cd9e6013971c7575925445e4d352ad8c46c26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37481">issues.joomla.org/tracker/joomla-cms/37481</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 9e6cd9e6013971c7575925445e4d352ad8c46c26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37481">issues.joomla.org/tracker/joomla-cms/37481</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37481">issues.joomla.org/tracker/joomla-cms/37481</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
