### PR TITLE
Cleaning whitespaces from the allowed and ignored extensions array in co...

### PR DESCRIPTION
**Pull request by Radek-Suski**
Cleaning whitespaces from the allowed and ignored extensions array in com_media
I think it makes sense. I am usually putting a space after a comma for better readability.

### CODE REVIEW

**Comment by infograf768** [comment]
In media config we have 4 fields needing comma separated input.
Could you consider all of them?

**Comment by Kubik-Rubik** [comment]
Good change, I also do the same in all my extensions. One more tester please!

**Comment by infograf768** [comment]
Please let's wait for

>@infograf768 Will to do today later then.

**Comment by Kubik-Rubik** [comment]
@infograf768 Radek already did the changes in his last commit! :-) IMO can be merged.

**Comment by Radek-Suski** [comment]
Yes. I did. Sorry, forgot to mention it.

**Comment by brianteeman** [comment]
Setting to RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5647">issues.joomla.org/joomla-cms/5647</a>.</sub>

**Comment by phproberto** [comment]
@Radek-Suski can you update this PR to fix the code style issues? I was going to send a PR to your branch but apparently it doesn't exist anymore

**Comment by Radek-Suski** [comment]
@phproberto I had to delete my fork. I am not really sure if I can change anything now. Or at least I have no clue how to be honest

**Comment by phproberto** [comment]
I'll try to get the code from the patch and create new PR.

**Comment by phproberto** [comment]
Replaced by:
https://github.com/joomla/joomla-cms/pull/6412

Please @Radek-Suski test it

**Comment by phproberto** [comment]
Replaced by https://github.com/joomla/joomla-cms/pull/6419

**Pull request closed without merging**
