### PR TITLE
[4.0] loadmodulebyid fix strict comparison

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
cast to int to fix strict comparison

### Testing Instructions
create/edit an article 
click on CMS Content and select 
select a module to embed in the article
save the article

### Expected result
the module output is showed in the article

### Actual result

no module output

### CODE REVIEW

**Comment by infograf768** [comment]
Please test first
https://github.com/joomla/joomla-cms/pull/28259

**Comment by SharkyKZ** [comment]
There's already PR for staging https://github.com/joomla/joomla-cms/pull/26531. But it's also wrong.

**Comment by alikon** [comment]
why this is wrong ?

**Comment by SharkyKZ** [comment]
Read the comments in #26531.

**Comment by alikon** [comment]
umm i was testing with postgresql....i'll look with mysql .....

**Comment by alikon** [comment]
work with mysql as well

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b12efc079ee61236e3c723d7ca2c24bda02f1e7d<br /><br />on code inspect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28269">issues.joomla.org/tracker/joomla-cms/28269</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on b12efc079ee61236e3c723d7ca2c24bda02f1e7d<br /><br />Tested with adding CMS content to article. Content displays correctly after PR is applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28269">issues.joomla.org/tracker/joomla-cms/28269</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28269">issues.joomla.org/tracker/joomla-cms/28269</a>.</sub>

**Comment by SharkyKZ** [comment]
No RTC. This breaks PDO.

**Comment by jwaisner** [comment]
Set back to Pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28269">issues.joomla.org/tracker/joomla-cms/28269</a>.</sub>

**Comment by alikon** [comment]
@SharkyKZ  may i ask you to test on PDO please ?
i've tested with all the 3 flavour of db's supported on j4 and it works as expected with this pr on all the 3

**Comment by SharkyKZ** [comment]
PDO returns strings for numeric columns when using pdo_mysql.

**Comment by SharkyKZ** [comment]
This seems to be because the driver is using `PDO::ATTR_EMULATE_PREPARES`.

**Comment by alikon** [comment]
closing as this will be probably fixed when #28278 will land in 4 branch

**Pull request closed without merging**
