### PR TITLE
Updated link

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38943 .

### Summary of Changes
changes the link to the awesome new doc that @ceford has created

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9e8ad93f91437e4bed4f7b04276bff27d748db9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38944">issues.joomla.org/tracker/joomla-cms/38944</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 9e8ad93f91437e4bed4f7b04276bff27d748db9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38944">issues.joomla.org/tracker/joomla-cms/38944</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38944">issues.joomla.org/tracker/joomla-cms/38944</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
