### PR TITLE
[4.2] PHP8.2 Add the missing props to the password form field

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Define the missing properties in the PasswordField class to prevent deprecation notice on PHP 8.2.

Test by code review.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on a1c61c792e007d95d7e5a5804a26b72c2d477ab5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39608">issues.joomla.org/tracker/joomla-cms/39608</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a1c61c792e007d95d7e5a5804a26b72c2d477ab5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39608">issues.joomla.org/tracker/joomla-cms/39608</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39608">issues.joomla.org/tracker/joomla-cms/39608</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
