### PR TITLE
Update some apache links

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue # .

### Summary of Changes
Update some Apache links that were using the old http version of the url.
Now they are https.

### CODE REVIEW

**Comment by brianteeman** [comment]
As a general rule we don't change files from upstream providers. @rdeutz your call

**Comment by rdeutz** [comment]
I don't see the value in this change

**Comment by brianteeman** [comment]
closed for the reasons stated above

**Comment by sshcli** [comment]
A question,
if I make a PR for update http://update.joomla.org to https://update.joomla.org
It will be closed too ?

**Comment by zero-24** [comment]
@sshcli 

> if I do a PR for update http://update.joomla.org to https://update.joomla.org
> It will be closed too ?

No you can do that (for the operational code this is already done looks like some unit tests needs to be updated and old update scripts.)

But please exclude the path JRoot\libraries\fof\* as this is 3rd Party code.

**Comment by sshcli** [comment]
@zero-24 thanks for your response.
This is the pr #16817

**Pull request closed without merging**
