### PR TITLE
[3.10] Preupdate checker: Removing HTML from a name of a malformed extensions

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #34993 .

### Summary of Changes

This removes any HTML that may be added by extension developers to the name translation.

### Testing Instructions

Review should be enough. 
But if you have such extension then please try test PreUpdate checker with it.

### CODE REVIEW

**Comment by brianteeman** [comment]
Need to also check with language override created by site builder.

(waiting for joomla.org servers to be back online before I can test myself)

**Comment by richard67** [comment]
@Fedik I've allowed myself to use the button to update your branch because appveyor failed for (I think) unrelated reasons but several restarts did not help ... so I hope this helps now.

**Comment by richard67** [comment]
After having restarted appveyor some 150 times it is ok now.

**Comment by joeforjoomla** [comment]
I have tested this item :white_check_mark: successfully on 90f64512f799202705a05236b2f5f589663b4d35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34995">issues.joomla.org/tracker/joomla-cms/34995</a>.</sub>

**Comment by richard67** [comment]
With current 3.10-dev I could verify that this PR successfully strips off the image tag from an extensions name in the pre-update check. I have modified a patchtester 3.0.0 package for that. But I could not reproduce the broken pre-update checker described in issue #34993 . For me nothing crashed without the patch of this PR.

**Comment by richard67** [comment]
Maybe it has to be a critical plugin and not just any extensions which has to be used for reproducing the issue?

**Comment by Fedik** [comment]
seems so, because it is used for `nonCoreCriticalPlugin` variable

**Comment by richard67** [comment]
> seems so, because it is used for `nonCoreCriticalPlugin` variable

Will eat something and later modify one of that type and check again.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 90f64512f799202705a05236b2f5f589663b4d35<br /><br />I've verified the issue and tested the patch with success. For this I've installed OSmap and modified the language string for the title of their system plugin so it contained an image tag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34995">issues.joomla.org/tracker/joomla-cms/34995</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34995">issues.joomla.org/tracker/joomla-cms/34995</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
