### PR TITLE
[languages] Organize and new metadata (Native language and calendar type)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes
1. Add `nativeName` and `calendar` to language metadata xml.

This new `nativeName` metadata is the language title in the native language.
This should be added to all languages packages.

For consistence i added in the 3 language metadata xmls.

After this is merged it can be used in installation and when installing languages.

This new `calendar` metadata is the calendar type to be used in the new datapicker.
Example: gregorian, jalali
1. Uniformized all en-GB language title to be:
2. title: English (en-GB)
3. native title: English (United Kingdom)
### Testing Instructions
1. Code review.
2. Apply this patch, delete configuration.php, refresh page and install Joomla 
3. Check the english title is "English (en-GB)" and the native title is "English (United Kingdom)" in Extensions -> Languages -> Content Languages
4. Check the english title is "English (en-GB)" in Extensions -> Languages -> Installed Languages in Both Site and Admin
5. Check the names of the language extensions in Extensions -> Manage -> Manage (check language and package type)

Reggarding the unit test changes if they pass is ok.
### Documentation Changes Required

Pages that indicate how to create a language package need to be updated.

---

@brianteeman please check if the English native title is correct.
@infograf768 @Bakual After this is merged this new var can be used in installation and when installing content languages.

### CODE REVIEW

**Comment by brianteeman** [comment]
Fine by me. Some sources might say it should be great Britain not united kingdom but I don't really care

**Comment by andrepereiradasilva** [comment]
> it should be great Britain not united kingdom but I don't really care

i actually add that doubt because en-GB means "English (Great Britain)", not "English (United Kingdom)" that as you know better than i do are different things.

**Comment by brianteeman** [comment]
I did look it up on the iso standards once to see what they said and it was
as clear as mud

**Comment by brianteeman** [comment]
We use GB as the two digit because UK is the Ukraine. But as the country
full name is The United Kingdom of Great Britain and Northern Ireland it is
best to write United Kingdom in this case

**Comment by andrepereiradasilva** [comment]
> We use GB as the two digit because UK is the Ukraine. But as the country full name is The United Kingdom of Great Britain and Northern Ireland it is best to write United Kingdom in this case

yes just saw that right now in official iso codes page

> UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND

https://www.iso.org/obp/ui/#iso:code:3166:GB

**Comment by Bakual** [comment]
Can you use `nativeName` instead of `native_name`? Looks to be more consistent with other names in the XML.
Other than that I think it is a good move :+1:

**Comment by andrepereiradasilva** [comment]
yes we can will change

**Comment by dgt41** [comment]
A list with all the native names exists here: https://github.com/dgt41/joomla-cms/blob/e17e53dcb8a764765c1d6b81933c5854b94d9a6a/plugins/editors/tinymce/helpers/tinymce.php
(If that would be somewhat helpful)

**Comment by Bakual** [comment]
@dgt41 Unfortunately that doesn't help as it is not complete in the sense we need. Eg it has only one entry for "de" (node-DE, de-CH, de-LI, de-AT, de-LU) and it is exactly where the current issue is coming from. :smile:

**Comment by Bakual** [comment]
You're sure you want to mix all those codestyle and SQL stuff into this PR?
The first changes could have been merged by review alone, but now this becomes a regular PR which needs testing instructions and regular tests.

**Comment by andrepereiradasilva** [comment]
@Bakual i know, the problem is the unit tests ... because of the inconsistency of the language names across joomla which is really annoying ....! Every time i try to change something in language i got problems because in some place is "(en-GB)", other is "(UK)", others is "(United Kingdom)" ...

IMHO, if we are changing the native title to be "English (United Kingdom)" and the international name being "English (en-GB)" we need to reflect this across joomla (install sql, unit tests, xml files, etc).

Also add to make a series of changes to have valid unit tests. 
Basicly added consistency to all language names across joomla and unit tests.

> You're sure you want to mix all those codestyle and SQL stuff into this PR?
> The first changes could have been merged by review alone, but now this becomes a regular PR which needs testing instructions and regular tests.

This will probably only be merged in 3.7.x so ... i see no issue with that.

The most important test continues to be a code review.
More tests i will write them after.

**Comment by andrepereiradasilva** [comment]
updated test instruction in the PR description.

**Comment by infograf768** [comment]
@andrepereiradasilva 
If this goes in (OK for me for 3.7), let's also add the new metadata proposed for the new calendar at the same time.
https://github.com/joomla/joomla-cms/pull/11138

**Comment by andrepereiradasilva** [comment]
just tell what is the metadata needed and if @dgt41 agrees i can add in this PR too, or we can wait for this one to get tested and eventually merged in 3.7.x branch and then add the calendar metadata.

**Comment by infograf768** [comment]
The new metadata is
`<calendar>jalali</calendar>`
or
`<calendar>gregorian</calendar>`
for now (other calendars may be added in the future).

If not present it would use `gregorian`.

**Comment by andrepereiradasilva** [comment]
ok added the calendar type to site and admin metadata xml. Didn't add it to install because i think it's not used there.

also updated PR description.

Please do a general code review and test.

**Comment by dgt41** [comment]
> Didn't add it to install because i think it's not used there.

No problem, I did that on the other PR 😄 (for the shake of unification)

**Comment by infograf768** [comment]
> Example: gregorian, javali

"jalali" ;)

**Comment by infograf768** [comment]
Please milestone to 3.7

**Comment by andrepereiradasilva** [comment]
> "jalali" ;)

ehhehe corrected

**Comment by andrepereiradasilva** [comment]
ok now it will use the new nativeTitle (if exists) on language install to create the content language native title as it should be.

It will still fallback to the install language variable (that should then be removed in 4.0).

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on d3e9986edbcfa8d8b35c963204d7447e845ea866<br /><br />:+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12036">issues.joomla.org/joomla-cms/12036</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d3e9986edbcfa8d8b35c963204d7447e845ea866<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12036">issues.joomla.org/tracker/joomla-cms/12036</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12036">issues.joomla.org/tracker/joomla-cms/12036</a>.</sub>

**Pull request merged**
