### PR TITLE
[4.0] codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
7393 instances of `; ?>`
26 instances of `;?>`

This makes them all the same - with the space obviously ;)

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by brianteeman** [comment]
@dgt41 approving is nice but it needs tests for a pr to be merged

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d705ec287136a8fd8504ef6a1fcf3b3e1cbae46<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17779">issues.joomla.org/tracker/joomla-cms/17779</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 8d705ec287136a8fd8504ef6a1fcf3b3e1cbae46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17779">issues.joomla.org/tracker/joomla-cms/17779</a>.</sub>

**Comment by dgrammatiko** [comment]
RTC

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
