### PR TITLE
[4.0] [a11y] anchor text-decoration underline

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #29744 .

### Summary of Changes

Backend Atum template changes
This PR sets css `text-decoration:underline` for anchor elements by default. 
This PR also sets `text-decoration:none` to the following anchors:
- anchor in header
- anchor in sidebar-wrapper
- anchor in sidebar-nav
- anchor in quick-icons

reason why is explained / discussed in https://github.com/joomla/joomla-cms/issues/29744

### Testing Instructions

- apply patch
- run cli command `npm run build:css`
- refresh page Joomla Administrator > System > Post Install Messages

### Actual result BEFORE applying this Pull Request

Anchor in text is not underlined. 

Schermafdruk 2020-07-28 09 03 00

 #### Extra screenshots from other pages BEFORE applying this Pull Request

Schermafdruk 2020-07-28 09 02 40
Schermafdruk 2020-07-28 09 02 45

### Expected result AFTER applying this Pull Request

Anchor in text is underlined.

Schermafdruk 2020-07-28 09 01 17

 #### Extra screenshots from other pages AFTER applying this Pull Request
Schermafdruk 2020-07-28 09 01 33
Schermafdruk 2020-07-28 09 01 22

### Documentation Changes Required

no changes required

### CODE REVIEW

**Comment by ReLater** [comment]
Could you please explain why you ignored comment https://github.com/joomla/joomla-cms/issues/29744#issuecomment-648140535 ?
We have already a feature in Joomla to underline links if wanted.

I'm just asking because I don't understand the concept of duplicate solutions and existing settings for nothing.

**Comment by hans2103** [comment]
> Could you please explain why you ignored comment [#29744 (comment)](https://github.com/joomla/joomla-cms/issues/29744#issuecomment-648140535) ?
> We have already a feature in Joomla to underline links if wanted.
> 
> I'm just asking because I don't understand the concept of duplicate solutions and existing settings for nothing.

sorry overlooked... I totally agree with you to and perhaps we should create a new PR to remove the `.a11y_highlight` after this issue is approved. 

Is there something I should do to get these settings activated? 
- Joomla Administrator > User Menu > Accessibility Settings
- com_users edit is opened for my user... but no Accessibility Settings tab to be seen. 

I think everyone will benefit with an underlined anchor in component output.

**Comment by brianteeman** [comment]
> Is there something I should do to get these settings activated?

Looks like someone broke it

>  remove the .a11y_highlight after this

Please do not do that it is doing more than this pr

**Comment by brianteeman** [comment]
The reason that it is broken comes from #29251 
> com_users edit is opened for my user... but no Accessibility Settings tab to be seen.
the offending pr change it to com_admin not com_users and it did not include the accessibility tab

If you go to your account in com_users you will see it is still there

**Comment by Quy** [comment]
> Is there something I should do to get these settings activated?

See PR #29226

**Comment by hans2103** [comment]
I have found the setting and activated it. See screenshots below:

Schermafdruk 2020-07-29 09 15 39

Schermafdruk 2020-07-29 09 16 11

Schermafdruk 2020-07-29 09 17 28


As the setting implies it will highlight anchors. (not all by the way... take a look at the white icons in the dark blue header top right.)
Besides the highlight I think all users would benefit a text-decoration underline on anchors in the component output. Not only the users who are aware of the availability of the a11y setting, able to find it and activate it. All users would benefit applying this PR.

**Comment by johndeutesfeld** [comment]
I have tested this item :white_check_mark: successfully on a70796a84eca25665e0984bf41b382fb1bdba2b4<br /><br />1. Applied Patch
2. ran `npm run build:css`
3. visited multiple sites<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30207">issues.joomla.org/tracker/joomla-cms/30207</a>.</sub>

**Comment by vdfk13** [comment]
test unsuccessfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30207">issues.joomla.org/tracker/joomla-cms/30207</a>.</sub>

**Comment by hans2103** [comment]
> test unsuccessfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30207">issues.joomla.org/tracker/joomla-cms/30207</a>.</sub>

@vdfk13 did you run 'npm run build:css' ? It is required to see the changes.

**Comment by johndeutesfeld** [comment]
image

This is what my result looks like after following the testing instructions.

**Comment by nurcihandem** [comment]
I have tested this item :white_check_mark: successfully on a70796a84eca25665e0984bf41b382fb1bdba2b4<br /><br />Followed the instructions above and visited the given pages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30207">issues.joomla.org/tracker/joomla-cms/30207</a>.</sub>

**Pull request merged**
