### PR TITLE
: Make upload and foldername fields required in com_media

### PR DESCRIPTION
**Pull request by manchumahara**
Pull Request for Issue # .
#### Summary of Changes

added html5 tag "required" as the input field is required as folder name
#### Testing Instructions

as folder name is required we can add the simple html5 "required" tag so that form is not submit, just a small fix/adjust for making it user friendly.

### CODE REVIEW

**Comment by manchumahara** [comment]
added required tag field in three places for file upload and folder creation. It will improve user experience as people sometimes forget to choose file or write folder name and click upload/submit button.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de9502aef02a9d7517cdaac42fb3494a17ef783d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11109">issues.joomla.org/joomla-cms/11109</a>.</sub>

**Comment by izharaazmi** [comment]
Can the title be: *Make upload and foldername fields required in com_media* or something better?

**Comment by brianteeman** [comment]
Updated title to something with meaning<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11109">issues.joomla.org/joomla-cms/11109</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on de9502aef02a9d7517cdaac42fb3494a17ef783d<br /><br />I have tested this item successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11109">issues.joomla.org/joomla-cms/11109</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11109">issues.joomla.org/joomla-cms/11109</a>.</sub>

**Pull request merged**
