### PR TITLE
Fix Hamburger menubutton on Mobile/Firefox/Android

### LINKED ISSUE #7293: Hamburger menubutton: No mainmenu in mobile Firefox on Android
#### Steps to reproduce the issue
Just load administrator in mobile Firefox browser(Android). When pushing the Hamburgermenubutton, you are redirected to the homepage on the frontend.

#### Expected result
When pushing the Hamburgermenubutton we should see the administrators mainmenu as a vertical mobile menu.

#### Actual result
When pushing the Hamburgermenubutton, you are now redirected to the homepage on the frontend.

#### System information (as much as possible)
Latest Firefox mobile browser (Android)

#### Additional comments
This is very easy to fix:

Just add the attribute href with the "#" value: href="#" to the &lt;a....&gt; on line 154 of index.php of the isis template. So line 154 become:
&lt;a href="#" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse"&gt;

### PR DESCRIPTION
**Pull request by PhilETaylor**
Fix Hamburger menubutton on Mobile/Firefox/Android - Closes #7293

@brianteeman I dont have Mobile/Firefox/Android - Please can you test.

### CODE REVIEW

**Comment by brianteeman** [comment]
Tested successfully in Firefox for android. Not observed any difference on other browsers which is good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7305">issues.joomla.org/joomla-cms/7305</a>.</sub>

**Comment by waader** [comment]
@test works with firefox on android and other browsers.

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7305">issues.joomla.org/joomla-cms/7305</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @PhilETaylor! Merged.

**Pull request closed without merging**
