### PR TITLE
[4.3] Batch Copy Banners

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40261 .

### Summary of Changes
ensure that $published is an integer

### Testing Instructions
Create a banner and then try a batch action. It should look like this
image

Then apply any filter and/or sort by any column and try to batch action again

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3bbec6fb349098ed878e0360f2fa27e3199e3137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40263">issues.joomla.org/tracker/joomla-cms/40263</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40263">issues.joomla.org/tracker/joomla-cms/40263</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks brianteeman

**Comment by brianteeman** [comment]
thnks

**Pull request merged**
