### PR TITLE
[4.0] Take results outside the form tag in Archives page

### PR DESCRIPTION
**Pull request by htmgarcia**
Pull Request for Issue N/A .

### Summary of Changes
Moving the archive results outside the form. There is no need to have the results inside the form.

### CODE REVIEW

**Comment by brianteeman** [comment]
Are you sure? Does pagination and the special archive filtering still works?

**Comment by htmgarcia** [comment]
Hi @brianteeman, 
the question here is: why do we have non required content inside the `<form>` tag? Is about best practices.

**Comment by htmgarcia** [comment]
And yes! The filtering and pagination still works.

**Comment by brianteeman** [comment]
Thats good  to hear - I couldn't test it as there is a syntax error in the file with if opened on l19 but not closed

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3f88aa7e3302a346f3b906ac0dab762d3a8a6ca1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21426">issues.joomla.org/tracker/joomla-cms/21426</a>.</sub>

**Comment by lavipr** [comment]
Hi @htmgarcia, I want to test your changes, but I need more information on how to test it. Could you please add testing instructions? Thank you.

**Comment by christianhent** [comment]
I have tested this item :white_check_mark: successfully on 8939574e0e331d410d5e7235c09a3700ae050d4b<br /><br />Result as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21426">issues.joomla.org/tracker/joomla-cms/21426</a>.</sub>

**Comment by ghost** [comment]
@christianhent can you please describe how you have tested so @lavipr can also test?

**Comment by htmgarcia** [comment]
@lavipr there are no visual improvements when testing this PR, just a better HTML code in the source as described at the beginning:
> Moving the archive results outside the form. There is no need to have the results inside the form.

Not sure how to provide you testing instructions [besides updating the file I modified](https://github.com/joomla/joomla-cms/pull/21426/files) in a local Joomla 4 installation.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8939574e0e331d410d5e7235c09a3700ae050d4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21426">issues.joomla.org/tracker/joomla-cms/21426</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21426">issues.joomla.org/tracker/joomla-cms/21426</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
