### PR TITLE
Redirects - move Filters from left to [Search Tools]

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves the Filter option of the **Redirect Manager: Links** to the [Search Tools] button.
(See Issue #6941 regarding the inconsistency with Filter options).
## Test instructions

In back-end > Components > Redirects
See the filter "- Select Status-" on the left
Also notice that the Expired URL column is too small.

screen shot 2015-05-15 at 08 46 30

Compare with the other filters, e.g. in **Category Manager**: 
In back-end > Content > Categories
### This PR changes moves the Filter

from the left to the middle column and will be visible when you click on the [Search Tools] button.
This PR also fixes the **column width** of the **Expired URL** column (now the columns Expired URL, New URL, and Referring Page are all 30%) so that it looks better on a smaller screen.

screen shot 2015-05-15 at 08 46 30

### CODE REVIEW

**Comment by MAT978** [comment]
@test
able to reproduce then #6953 works as described (*Travis*) - thanks
strange having the left collapse column empty O.o

**Comment by zero-24** [comment]
@pe7er i have just tested this.

here my result. 
pr_6953

I hope we are able to remove the side bar as it looks very bad.
The seccond thing i marked is the info box are we abel to add a bit space between the searchtools and the message? If searchtools are open all is ok but can we have this extra space also if the searchtools are closed?

**Comment by zero-24** [comment]
Also i have just noted that the filter don't work. It will be shown but don't work here. If i change to e.g. unpublished i still get all also the publiched etc.

**Comment by bertmert** [comment]
@pe7er 
To remove sidebar you need an empty one in tmpl/default.php. Remove line
```
$this->sidebar = JHtmlSidebar::render();
```
in view.html.php.

**Comment by bertmert** [comment]
@pe7er 
To make filter work you have 1) to change
*name="published"*
to
*name="state"*
in filter,,,.xml.

And you have 2) to add *state* to *config_fields* in constructor of model
```
'published', 'a.published', 'state'
```

**Comment by pe7er** [comment]
Thank you all for testing.
I've committed the PR from @zero-24 to fix a CS issue,
and after changing the field name in the filter.xml (thanks @bertmert !) the filter works correctly.
Do I still need to add "config_fields" to the constructor of the model?

I also added a "Links" submenu so that (although this component has just 1 view) the view is consistent with all other components. 
screen shot 2015-05-17 at 07 58 10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by jwaisner** [comment]
@test 

Menu on left contains "Links" now. "Search Tools" works when filtering. Spacing between "search tools" and the below message still is not corrected.

screen shot 2015-05-23 at 00 03 19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by brianteeman** [comment]
I do not understand why there is a sidebar with a link to open the view that you are already on - this serves no purpose at all<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by pe7er** [comment]
Consistency & it's a visual aid that makes orientation (especially for new users) easier.

All components that have multiple views (e.g. items & categories) have a sidebar with (sort of) "menu items" where you can easily select another view of that component. Besides selecting "menu options" it also shows the admin which "admin sub menu" they are using.

I've noticed that especially for new users the admin menu structure can be very confusing. The sidebar functions as visual aid that makes orientation easier. 

And when you only have one highlighted (blue background) option, it gives admins a visual aid that is consistent with all "multi view" components.

**Comment by brianteeman** [comment]
I understand you but disagree.

**Comment by bertmert** [comment]
I would remove the sidebar, too, because any unneccessary rendering ist a waste of time and performance. Every little helps...

**Comment by larapetersen** [comment]
Tested succesfully. I agree however, that the sidebar is only useful when an item has subitems. With Redirect, that's not the case. And why use the term "Links" and not "Redirect"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by genesisfan** [comment]
@test succesfully tested. No sidebar necessary IMHO.
The space between searchtools and message bar should be fixed?

space<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by roland-d** [comment]
I also agree the sidebar is useless on the redirect manager. @pe7er Can you please update your PR? It seems to have some issues as well.

**Comment by zero-24** [comment]
Moving to `Information Required` until @pe7er get the time to change the Code as @roland-d sugsested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6953">issues.joomla.org/joomla-cms/6953</a>.</sub>

**Comment by pe7er** [comment]
I tried to update this PR but had some "HEAD detached" problems & merge conflicts.
Therefore I've created a new PR. Could someone please merge this with the new PR #7697
Thanks!

**Comment by zero-24** [comment]
Closing as we have a new & updated.

**Pull request closed without merging**
