### PR TITLE
[4.1] Remove Unused Imports from /libraries folder

### PR DESCRIPTION
**Pull request by PhilETaylor**
Remove Unused Imports from /libraries folder

Code review.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4a845a4b11a96b5c56f5c1c335cfa2a168c29866<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36132">issues.joomla.org/tracker/joomla-cms/36132</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 2c33dadf7e5777ed152769865e87af8f18ef2565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36132">issues.joomla.org/tracker/joomla-cms/36132</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36132">issues.joomla.org/tracker/joomla-cms/36132</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
