### PR TITLE
[4.0] Fix the debug plugin on error page

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #32354 .

### Summary of Changes

Correcting an event when an assets need to be used.

### Testing Instructions
please follow #32354 

### Actual result BEFORE applying this Pull Request

not works

### Expected result AFTER applying this Pull Request

works

### Documentation Changes Required
none

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 46ebeda4af78a67e0b2775e882f1645168fa6e82<br /><br />👍 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32358">issues.joomla.org/tracker/joomla-cms/32358</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 46ebeda4af78a67e0b2775e882f1645168fa6e82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32358">issues.joomla.org/tracker/joomla-cms/32358</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32358">issues.joomla.org/tracker/joomla-cms/32358</a>.</sub>

**Comment by richard67** [comment]
Trying to fix the broken appveyor ci by updating the branch.

**Comment by richard67** [comment]
Thanks! Just have tested, too, also with log deprecated. All fine.

**Pull request merged**
