### PR TITLE
[com_modules] - fix Notice: Undefined variable: clientId

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #17982.

### Summary of Changes
fix Notice: Undefined variable: clientId

### Testing Instructions
Edit an article.
Click Module button in the editor.

### Expected result
No notice

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4db0b1fe6077159f426590cf39c5a6d2e9b4c675<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17983">issues.joomla.org/tracker/joomla-cms/17983</a>.</sub>

**Comment by izharaazmi** [comment]
I have tested this item :white_check_mark: successfully on 4db0b1fe6077159f426590cf39c5a6d2e9b4c675<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17983">issues.joomla.org/tracker/joomla-cms/17983</a>.</sub>

**Comment by izharaazmi** [comment]
IMO, this should go in 3.8.0 milestone

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@mbabker

**Comment by tstransco** [comment]
I lost some of the components from components list after I updated to 3.8 from 3.75. How can I get back my those components back viz. breezingforms, fabrik etc Can anybody help me plz?

**Comment by ghost** [comment]
@tstransco Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding, thanks.

**Pull request merged**
