### PR TITLE
Image CSS style strings

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Same as #19143 but for image.

### Testing Instructions

Code review.

### Documentation Changes Required
Update help page? https://help.joomla.org/proxy?keyref=Help38:Menus_Menu_Item_Manager_Edit&lang=en

### CODE REVIEW

**Comment by brianteeman** [comment]
This is reverting a deliberate change made for #19122

**Review by brianteeman — COMMENTED** [review]
This is reverting a deliberate change

**Comment by SharkyKZ** [comment]
This does not revert anything. In #19143 strings were corrected for link. This PR adds the same corrections for image.

**Review by brianteeman — APPROVED** [review]
Sorry I needed more coffee

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 01948edf262101d3ebb15381ef2df42b98230558<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20591">issues.joomla.org/tracker/joomla-cms/20591</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 01948edf262101d3ebb15381ef2df42b98230558<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20591">issues.joomla.org/tracker/joomla-cms/20591</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20591">issues.joomla.org/tracker/joomla-cms/20591</a>.</sub>

**Pull request merged**
