### PR TITLE
Optimizing getExt method

### PR DESCRIPTION
**Pull request by foxo79**
This is my first commit so sorry if it is not OK.

Pull Request for Issue # .

### Summary of Changes
Replacing old code with the new one (just one line of code).

### CODE REVIEW

**Comment by ethernidee** [comment]
Checked PHP source: pathinfo behavior is stable and it's simpler, than manual code.

**Comment by ghost** [comment]
@berserkerx can you please mark your test as successfully?

**Comment by ethernidee** [comment]
I have tested this item :white_check_mark: successfully on dee42df6cbc92875a7830efd78b18c6d66eae446<br /><br />Tested file names with or without extensions. OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by HLeithner** [comment]
Optimizing is really relative, pathinfo is much slower then the substr version.

strpos version about 0.016 seconds (by 10000 calls) 
https://3v4l.org/OjlXi/perf#output

strpos version about 0.018-0.022 seconds (by 10000 calls) 
https://3v4l.org/KvAmV/perf#output

PS: I know 3v4l is not a good benchmark tool but shows a direction.

**Comment by ethernidee** [comment]
Agree, PHP 7.1:
```
function getExt1 ($fileName) {
  return ($pos = strrpos($fileName, '.')) !== false ? substr($fileName, $pos + 1) : '';
}

function getExt2 ($fileName) {
  return (string) pathinfo($fileName, PATHINFO_EXTENSION);
}

$fileName = 'mod_subscription.php';
$s        = microtime(true);

for ($i = 1000000; $i--; ) {
  $fileExt = getExt2($fileName);
}

$time = microtime(true) - $s;

exit(var_dump($time));
```
Joomla's method: 3.26-3.21s
Pathinfo: 4.91-5.23s

**Comment by vladimir179** [comment]
IFilter::GetText method
[Indexing Service is no longer supported as of Windows XP and is unavailable for use as of Windows 8. Instead, use Windows Search for client side search and Microsoft Search Server Express for server side search.]
Retrieves text (text-type properties) from the current chunk, which must have a CHUNKSTATE enumeration value [xmovies8 2016](https://xmovies8.biz "") of CHUNK_TEXT.
Syntax

C++

HRESULT GetText(
  [in, out] ULONG *pcwcBuffer,
  [out]     WCHAR *awcBuffer 
);
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by alikon** [comment]
can someone remove the previous spam message please

**Comment by vladimir179** [comment]
ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by ghost** [comment]
@vladimir179 does "ok" means a successfully Test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by HLeithner** [comment]
@franz-wohlkoenig in my opinion this PR doesn't makes any sense because it slows down Joomla without any benefit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by ghost** [comment]
@HLeithner thanks for Info. Callling @mbabker or @wilsonge if this PR should be closed.

**Comment by wilsonge** [comment]
If the difference is a second per million files I'm not sure it's a problem to be honest. When you're at the point of manipulating a million files a second here or there is going to be next to nothing

**Comment by ghost** [comment]
If this Issue get no different Response, it will be closed at 26th November 2017.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by wilsonge** [comment]
To clarify above I think that we should merge this unless @mbabker feels differently

**Comment by HLeithner** [comment]
Does it really makes sense to reduce the speed of the core cms? Doing many of these changes would slow down the overall performance of the cms with no real benefit.

The running code is well tested and is faster then php native code. Even if this commit has a small speed impact, we should check every commit for performance improvements to get a better CMS.

But I'm happy with the decision by @mbabker what ever it is.

**Comment by mbabker** [comment]
If the method were legitimately being used 10K+ times in a request cycle, we might consider leaving it alone and closing this.  I would guess though it sees less than 10 uses in a request cycle when it actually does get called up, so at this point we're talking about a performance degradation of 1 or 2 milliseconds per method call.  It can be made up for in other ways IMO.

**Comment by HLeithner** [comment]
Think of a Site 1000 requests per second

**Comment by ghost** [comment]
Maintainers please decide, Status is set on "Needs Review".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18030">issues.joomla.org/tracker/joomla-cms/18030</a>.</sub>

**Comment by SharkyKZ** [comment]
As a side effect, this fixes a bug we currently have when path contains period but file does not. So we're going to need something like this. On PHP 7+ `pathinfo()` seems much slower than string manipulation.

**Comment by HLeithner** [comment]
Alternative PR #30646 has been merged. Closing this. thanks for your time creating this PR.

**Pull request closed without merging**
