### PR TITLE
[4.1] - fix  All Menu Items Check In

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue ##37004 .

### Summary of Changes
used proper items

### Testing Instructions

Administrator got to Menus / All Menu Items /Select All
In Actions select Chck-in

### Actual result BEFORE applying this Pull Request
An error has occurred.

### Expected result AFTER applying this Pull Request

No error

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e6cb7b0a7eafa371f124379915b3fb5474720468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37005">issues.joomla.org/tracker/joomla-cms/37005</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on e6cb7b0a7eafa371f124379915b3fb5474720468<br /><br />Only one menu item but workded fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37005">issues.joomla.org/tracker/joomla-cms/37005</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37005">issues.joomla.org/tracker/joomla-cms/37005</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by John46c** [comment]
Coin Master is an app game launched by the company Moon Active studio. In this game, you have to help a wizard collect coins. And find other treasures from various locations. You can also Collect many items in this game that are not available in any other games. For more Visit [coin master daily free spins](https://www.intensedebate.com/people/Ragnerbrooke "coin master daily free spins")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37005">issues.joomla.org/tracker/joomla-cms/37005</a>.</sub>

**Pull request merged**
