### PR TITLE
[5.3] [Events] Use event classes for custom fields plugins

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Update `fields` plugins to use `SubscriberInterface` and event classes.

### Testing Instructions

Create/edit custom fields, all should work as before.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 62953679ab214dfa59c9ed8dacc3f494972af785<br /><br />I created a Textarea field, a radio button field, Media (image) and it worked perfectly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43611">issues.joomla.org/tracker/joomla-cms/43611</a>.</sub>

**Comment by Frostholm7** [comment]
I have tested this item :white_check_mark: successfully on 62953679ab214dfa59c9ed8dacc3f494972af785<br /><br />with new installation with 5.1 dev and 5.2 dev
Have I tested  
New Group 
New Subfild
New calendar
New Articles
Filled in the new fields
Saved
Checked logs
everything ok
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43611">issues.joomla.org/tracker/joomla-cms/43611</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43611">issues.joomla.org/tracker/joomla-cms/43611</a>.</sub>

**Comment by Hackwar** [comment]
I'm not convinced that the subform field works and since none of the testers claimed to have tested that, I'd like to wait with merging.

**Comment by exlemor** [comment]
@Hackwar - I just retested it with the subform field... Here is a screenshot:



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43611">issues.joomla.org/tracker/joomla-cms/43611</a>.</sub>

**Comment by exlemor** [comment]
Here it is (had to use GitHub, Joomla Issue Tracker wouldn't let me add the image :/ 

for-PR-43611-for-Hackwar

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.3-dev.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
