### PR TITLE
[4.0][Aurora] Offline style

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #16833 .

### Summary of Changes
Some style for the Aurora offline page.

### Testing Instructions
Set site to offline and check frontend. Apply patch. Check again.

### Before
offline1

### After
offline2

### CODE REVIEW

**Comment by C-Lodder** [comment]
Ooo I like that. Nice one Ciaran

**Comment by C-Lodder** [comment]
Dont forget to add `form-control` to the "Secret Key" input too (below password)

**Comment by ciar4n** [comment]
Thx Charlie.. Done!

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a5a53e0cdaa05157d94dd6f7a63954c18b89b1fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16930">issues.joomla.org/tracker/joomla-cms/16930</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Pull request merged**
