### PR TITLE
[4.0] Numbers not digits

### PR DESCRIPTION
**Pull request by brianteeman**
This corrects the mistake in #30473 - the word should be number not digit

I have checked this with my client Cambridge University Press and they have checked the usage within the Corpus. https://en.wikipedia.org/wiki/Cambridge_English_Corpus The corpus is a multi billion word database of the usage of the english language in the world. The corpus is about how language is used and not just about the dictionary meaning

They wrote

>Interesting! I’ve had a look and it looks like ‘number’ is more common – there are only a small number of examples with ‘digit’.
It’s hard to know for sure, as there are only very few examples of the exact sentences you’ve given so I did a more general search and often ‘number’ is used in sentences like ‘they could steal your credit card number and password’. But, I had a scan through and there are definitely lots of examples of e.g. ‘use a password that contains letters, numbers and special characters’, so I think you’re right to go with your feeling on this.

### Testing Instructions
Code review

cc @wilsonge

### CODE REVIEW

**Comment by jiweigert** [comment]
I would expect the term "digit" or "digits" more in a specific technical conversation/ documentation like a API-Interface description, not in a usual conversation or message presented to the user as a hint, error or general explanation.

It's not wrong, but highly uncommon, even when I reflect all the documentations, texts and emails i had to write to customers, technical staff or in CMS-Frontend code I had to write in customer projects.

"Number/ numbers" was always the way to go.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30559">issues.joomla.org/tracker/joomla-cms/30559</a>.</sub>

**Comment by sandewt** [comment]
A different approach: numbers versus digits

digit: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 <=> these are just digits

number: 21, 567, 23471 <=> You use the digits to make numbers which represents a certain value.

For example with 6 digits you make a number with a certain value.

Compare this with the letters from the alphabet with which you make words.

**Comment by jiweigert** [comment]
Hi sandewt,
we should really not be too technical in presenting messages or anything else, when it come to "communicate" with the users.

Messages should be understandible and that begins with the right choice of terms.

Outside of technical groups I hardly had ever heard the term digit or digits for single numbers. 
What's total ok internal, is confusing when it comes to explain something to the (End-)user, here the Infomessage for missing numbers in a password.

The number area on a standard keyboard is called num(ber)pad
not digitpad, the key to lock or unlock it numlock, etc.

That is, what a user can associate with, when he see such Infomessage.

> Compare this with the letters from the alphabet with which you make words.

Actually, the word letter is used  in sense of printing, painting..
were it's originated from in book printing letters (on to the paper) while typing on a type writer...

characters is used when to write a messages, letters, documents.

But that is nitpicking ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30559">issues.joomla.org/tracker/joomla-cms/30559</a>.</sub>

**Comment by sandewt** [comment]
@jiweigert 

>we should really not be too technical in presenting messages or anything else, when it come to "communicate" with the users.

Indeed, the following could be an intermediate solution:

This language string:
`JFIELD_PASSWORD_NOT_ENOUGH_INTEGERS_N_1="Password does not have enough numbers. At least 1 number is required."`

Could be:
`JFIELD_PASSWORD_NOT_ENOUGH_INTEGERS_N_1="Password does not have enough numbers. At least 1 digit is required."`

**Comment by SharkyKZ** [comment]
Digit is the correct term. But I'm not going to argue with native English speakers. My only wish is that a note is added for language translators so they know it should be correctly translated as digit.

**Comment by wilsonge** [comment]
I agree with Brian in this case. numbers is the phrase used most at least in British english.

**Comment by infograf768** [comment]
@wilsonge You just killed https://github.com/joomla/joomla-cms/pull/30559 as these strings are useless in installation...

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Pull request merged**
