### PR TITLE
[4.0] Edit users title

### PR DESCRIPTION
**Pull request by brianteeman**
Before this simple pr the tooltip was "Edit Edit User username" Now it is simply "Edit User username"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 58120bee11e89d0e72aaafd7f35f4329af8ca1c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25370">issues.joomla.org/tracker/joomla-cms/25370</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6f34ee11587c2324d737cf28e6ce2b36735add24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25370">issues.joomla.org/tracker/joomla-cms/25370</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25370">issues.joomla.org/tracker/joomla-cms/25370</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
