### PR TITLE
css invalid code

### PR DESCRIPTION
**Pull request by CEWebDesign**
delete invalid code (in favor of #8594 )

### CODE REVIEW

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on 557a18fa145d55a963782d91b7fec021ffacc012<br /><br />It's ok for me to remove this declaration. :+1: 
Tested with "old" mootools modals, and this is correct to remove it (and B/C is ok as joomla is not using anymore mootools modals).
By default, overflow has the "visible" value.
"none" was not a valid value (and so visible was used).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8595">issues.joomla.org/joomla-cms/8595</a>.</sub>

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on 557a18fa145d55a963782d91b7fec021ffacc012<br /><br />It's ok for me to remove this declaration. :+1: 
Tested with "old" mootools modals, and this is correct to remove it (and B/C is ok as joomla is not using anymore mootools modals).
By default, overflow has the "visible" value.
"none" was not a valid value (and so visible was used).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8595">issues.joomla.org/joomla-cms/8595</a>.</sub>

**Comment by JoomliC** [comment]
i realize that this overflow error was... mine! (2 years ago...)
So i can confirm this one could be removed!

About the <b>@moz-document</b>, i would say that you can remove this declaration too.
Added here https://github.com/joomla/joomla-cms/commit/85b3ebc6f7835c626b44a7841ba8912ff138c0de by @infograf768 (if Jean-Marie, could you confirm that this declaration is not needed anymore ?)

As @moz-document is still experimental (https://developer.mozilla.org/en/docs/Web/CSS/@document), i don't see a reason to use it today, as in recent version fo Firefox, i can't reproduce the issue for which it was intended for "[#29014] *Firefox 14.0.1: Insert Image, Article or Pagebreak always inserts on top".
:+1:

**Comment by JoomliC** [comment]
I think we can close this issue as we have a PR : https://github.com/joomla/joomla-cms/pull/8595
;-)

**Comment by JoomliC** [comment]
Hi @joo7 ,

I've seen you have opened a new PR for moz-document : https://github.com/joomla/joomla-cms/pull/8601
Do you know you can update your PR here just by editing the file modas.css again in your branch, or directly here ?
As the purpose of your PRs is the same : clean mootools modal from css errors.

When using the component Patch Tester for Joomla, you won't be able to apply and test the 2 patchs in the same time, as the changes in the same file (https://github.com/joomla-extensions/patchtester/releases).
So, would be easier for testers to have the 2 changes here in the same PR ;-)

<b>For Testing</b> (as mootools modals are removed from Joomla in 3.5.0) : 
- Apply the patch and test modals used in third party extensions (everywhere you have a mootools modal)
- Test if behavior is ok on all devices (mobile, browser...)

I have tested on iphone and mac (with https://github.com/joomla/joomla-cms/pull/8601 and https://github.com/joomla/joomla-cms/pull/8595 applied in manual), with third party extensions on 3.5.0-beta1 : all is ok
In the same time, i have tested this css lines removal on a 3.4.5, with previously used mootools modals for select user, image, etc... just to be sure. And it's working as well!
So, the 2 deletions seem ok for all usage of "deprecated" mootools modal. :+1: 

Cyril

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 557a18fa145d55a963782d91b7fec021ffacc012<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8595">issues.joomla.org/joomla-cms/8595</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8595">issues.joomla.org/joomla-cms/8595</a>.</sub>

**Comment by rdeutz** [comment]
closing this one because it fails on travis and it was easier to redo the patch as to look what is wrong here, redo PR #8850

**Pull request closed without merging**
