### PR TITLE
Not Allowed label

### PR DESCRIPTION
**Pull request by brianteeman**
Probably my mistake but the label "Not Allowed" in the Acl permissions had a period at the end when it shouldnt have.

This simple PR removes the period from the language string AND the js files used in the ajaxified calculated settings

### CODE REVIEW

**Comment by infograf768** [comment]
Please modify to only patch the ini file. See https://github.com/joomla/joomla-cms/issues/10117

**Comment by infograf768** [comment]
Or I can add in #10117 as you like

**Comment by brianteeman** [comment]
I modified here as it made more sense

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7c9795509d4f77dfc9f257eaa48a7ddc9698f62b<br /><br />Simple change. Can be merged on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10116">issues.joomla.org/joomla-cms/10116</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10116">issues.joomla.org/joomla-cms/10116</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 7c9795509d4f77dfc9f257eaa48a7ddc9698f62b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10116">issues.joomla.org/joomla-cms/10116</a>.</sub>

**Pull request merged**
