### PR TITLE
[4.0][mod_messages] messages badge

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #26895 .

### Summary of Changes
fix

### Testing Instructions

1.   apply pr
2.     Login to Joomla admin with one user
3.     Go to the private message section.
4.     Add another user Id in recipients
5.     Add some context and send the message.
6.     Now login with another user.
7.     See the admin panel

### Expected result
badge

### Actual result

no badge

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on eb4387b13004a90176ef93060b40be747c2055ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by thite-amol** [comment]
I have tested this item :red_circle: unsuccessfully on eb4387b13004a90176ef93060b40be747c2055ff<br /><br />Now the messages appear in the list view. However, the notification count does not change even after I read the messages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by alikon** [comment]
that's another issue see  #26921 and should be managed in a separate  PR

**Comment by thite-amol** [comment]
Please check the image below. The referred issue is different from this.
Private Messages     Administration

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on eb4387b13004a90176ef93060b40be747c2055ff<br /><br />I agree with @thite-amol and modify my test

looks like getitems will get all items pertaining to the user whatever the state of the message. It works in the Messages manager because we have filters, but not for the module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by infograf768** [comment]
I get it to work by using the query we had in J3
```
diff --git a/administrator/modules/mod_messages/mod_messages.php b/administrator/modules/mod_messages/mod_messages.php
index 1a346ed..b53a2a7 100644
--- a/administrator/modules/mod_messages/mod_messages.php
+++ b/administrator/modules/mod_messages/mod_messages.php
@@ -10,5 +10,19 @@
 defined('_JEXEC') or die;
 
+use Joomla\CMS\Factory;
 use Joomla\CMS\Helper\ModuleHelper;
 
+// Get the number of unread messages in your inbox.
+$db   = Factory::getDbo();
+$user = Factory::getUser();
+
+$query = $db->getQuery(true)
+	->select('COUNT(*)')
+	->from('#__messages')
+	->where('state = 0 AND user_id_to = ' . (int) $user->get('id'));
+
+$db->setQuery($query);
+
+$countUnread = (int) $db->loadResult();
+
 require ModuleHelper::getLayoutPath('mod_messages', $params->get('layout', 'default'));
diff --git a/administrator/modules/mod_messages/tmpl/default.php b/administrator/modules/mod_messages/tmpl/default.php
index ec0fa3a..00bda51 100644
--- a/administrator/modules/mod_messages/tmpl/default.php
+++ b/administrator/modules/mod_messages/tmpl/default.php
@@ -27,5 +27,4 @@
 			<?php echo Text::_('MOD_MESSAGES_PRIVATE_MESSAGES'); ?>
 		</div>
-		<?php $countUnread = $app->getSession()->get('messages.unread'); ?>
 		<?php if ($countUnread > 0) : ?>
 			<span class="badge badge-pill badge-danger"><?php echo $countUnread; ?></span>
```

**Comment by alikon** [comment]
@infograf768, @thite-amol  please retest

**Comment by isidrobaq** [comment]
I have tested this item :white_check_mark: successfully on 296bb159bf8a1c24f0d605782c4700f32bfae9f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on 296bb159bf8a1c24f0d605782c4700f32bfae9f1<br /><br />Followed testing instructions.

Notifications appeared when patch was applied. Not before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 840bb9db9cae6e03d3dd45523011fc5b9c649eaf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26912">issues.joomla.org/tracker/joomla-cms/26912</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
