### PR TITLE
Popover styling

### PR DESCRIPTION
**Pull request by brianteeman**
Redo to solve conflicts of ##11332

### CODE REVIEW

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 63bbe4cabe073b772e55e3b433413ef80094d325<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12749">issues.joomla.org/tracker/joomla-cms/12749</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 63bbe4cabe073b772e55e3b433413ef80094d325<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12749">issues.joomla.org/tracker/joomla-cms/12749</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12749">issues.joomla.org/tracker/joomla-cms/12749</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
