### PR TITLE
[4.0] newsfeeds labels

### PR DESCRIPTION
**Pull request by brianteeman**
Labels should be capitalised. code style change only so code review is enough for testing

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2aa892d33c5617fdc5ca24406aaf9ef9e20480ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28188">issues.joomla.org/tracker/joomla-cms/28188</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2aa892d33c5617fdc5ca24406aaf9ef9e20480ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28188">issues.joomla.org/tracker/joomla-cms/28188</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28188">issues.joomla.org/tracker/joomla-cms/28188</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
