### PR TITLE
[3.8] Fix classname conflict

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
As requested by @mbabker.

### CODE REVIEW

**Comment by mbabker** [comment]
Ping @infograf768 as this was your issue report.

**Comment by infograf768** [comment]
will test tomorrow.

**Comment by infograf768** [comment]
This solves the issue. RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16638">issues.joomla.org/tracker/joomla-cms/16638</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on fbce89f1f8c6f9bfe1b54d01a1aac16c18eedb51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16638">issues.joomla.org/tracker/joomla-cms/16638</a>.</sub>

**Pull request merged**
