### PR TITLE
Correcting Jalali/Persian calendar popup

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/17389

### Summary of Changes
Days incorrectly displayed in popup

### Testing Instructions
Please test on clean staging : https://github.com/joomla/joomla-cms/archive/staging.zip
Patch proposed by @balvard 
After patch we should get

screen shot 2017-08-07 at 09 05 10

@balvard @farhadst
You are the only ones to know what should be. :smile:

### CODE REVIEW

**Comment by balvard** [comment]
Salam
I checked staging file.
and I saw no change on it.
screen shot 2017-08-07 at 12 43 16
Patch Links file is right.javascript:
https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/17432.patch.
I can't approve current staging file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17432">issues.joomla.org/tracker/joomla-cms/17432</a>.</sub>

**Comment by dgrammatiko** [comment]
@balvard your code is in this PR, not in staging. So you have to apply this PR to get the updated code

**Comment by balvard** [comment]
Good
I approved it.

**Comment by balvard** [comment]
Yes
Test OK with new javascript edition.
Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17432">issues.joomla.org/tracker/joomla-cms/17432</a>.</sub>

**Comment by ghost** [comment]
@balvard i altered your Test as successfully at Issue Tracker.

**Comment by farhadst** [comment]
I have tested this item :white_check_mark: successfully on d5c7f25f380ab23477aea178f3b24472c821b28e<br /> and patch ok
I approved it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17432">issues.joomla.org/tracker/joomla-cms/17432</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
