### PR TITLE
Cache and Language list limit

### PR DESCRIPTION
**Pull request by brianteeman**
Go to the Clear Cache menu item
Change the value of the limit
Switch from site to admin and the limit will change to 25

Go the Languages Installed Menu item
Change the value of the limit
Switch from site to admin and the limit will change to 25

This is because it was hard coded in the javascript preventing global list limit from working etc

Apply this pr and repeat above and the list limit will not change when switching between site and admin. This is not the same behaviour as for example when switching the module manager between site and admin modules

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b295540a511aa91e84c84a4e78d9d7dac75bf9aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9855">issues.joomla.org/joomla-cms/9855</a>.</sub>

**Comment by ywebdesign** [comment]
tested succesfully - limit doesn't change <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9855">issues.joomla.org/joomla-cms/9855</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9855">issues.joomla.org/joomla-cms/9855</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
