### PR TITLE
[4.0] Install languages

### PR DESCRIPTION
**Pull request by brianteeman**
Changes the button from black to blue - seems to make more sense to me and to be more consistent - no css changes

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ef79e9d7940c4695780e010c789694acc41c9e2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28165">issues.joomla.org/tracker/joomla-cms/28165</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on ef79e9d7940c4695780e010c789694acc41c9e2b<br /><br />I I made the change manually and the buttons are blue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28165">issues.joomla.org/tracker/joomla-cms/28165</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28165">issues.joomla.org/tracker/joomla-cms/28165</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
