### PR TITLE
Remove robot strings from article form menuitem

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue # .
https://github.com/joomla/joomla-cms/pull/30399#issuecomment-736841598

### Summary of Changes
Apparently missed an XML with https://github.com/joomla/joomla-cms/pull/30110

### Testing Instructions
* Create a menuitem for the article form ("Create Article").
* Check the "Robots" parameter in the "Metadata" tab

### Actual result BEFORE applying this Pull Request
Options are translated strings

### Expected result AFTER applying this Pull Request
Options are no longer translated strings

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Bakual** [comment]
My PhpStorm automatically removed some superfluous spaces in that file. Shouldn't be an issue.

**Review by richard67 — APPROVED** [review]

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3d3f995c404213ff1d0de0abb871c139bfc7b3cb<br /><br />Tested successfully in 3.9.23.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31557">issues.joomla.org/tracker/joomla-cms/31557</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3d3f995c404213ff1d0de0abb871c139bfc7b3cb<br /><br />Tested successfully in 3.9.23.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31557">issues.joomla.org/tracker/joomla-cms/31557</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3d3f995c404213ff1d0de0abb871c139bfc7b3cb<br /><br />Tested successfully in 3.9.23.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31557">issues.joomla.org/tracker/joomla-cms/31557</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3d3f995c404213ff1d0de0abb871c139bfc7b3cb<br /><br />Tested successfully in 3.9.23.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31557">issues.joomla.org/tracker/joomla-cms/31557</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3d3f995c404213ff1d0de0abb871c139bfc7b3cb<br /><br />Tested successfully in 3.9.23.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31557">issues.joomla.org/tracker/joomla-cms/31557</a>.</sub>

**Pull request merged**
