### PR TITLE
[4.0] Fix js lint

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Suppress Eslint warning

### Testing Instructions
No test needed, the addition is just a comment

### Actual result BEFORE applying this Pull Request

Screenshot 2020-10-02 at 19 32 14

### Expected result AFTER applying this Pull Request

Screenshot 2020-10-02 at 19 34 42

### Documentation Changes Required

No

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@wilsonge this one is a no brainer as well

**Comment by mqueme** [comment]
I get other error when running the command
/administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  152:30  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  152:95  error  Missing semicolon      

administrator/components/com_media/resources/scripts/components/modals/modal.vue
  21:15  warning  Require self-closing on HTML elements (<slot>)  vue/html-self-closing

After applying this PR, the func-names warning is gone.

**Comment by mqueme** [comment]
I have tested this item :red_circle: unsuccessfully on b6cfca1a31122d3cdb0f7c00075bed20b3709186<br /><br />I get other error when running the command
/administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
152:30 error Expected an assignment or function call and instead saw an expression no-unused-expressions
152:95 error Missing semicolon

administrator/components/com_media/resources/scripts/components/modals/modal.vue
21:15 warning Require self-closing on HTML elements () vue/html-self-closing

After applying this PR, the func-names warning is gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30875">issues.joomla.org/tracker/joomla-cms/30875</a>.</sub>

**Comment by dgrammatiko** [comment]
@mqueme check the output of drone at the bottom of this pr at GitHub 
EB927011-9577-4F1A-93AD-49D0EE108533

**Comment by dgrammatiko** [comment]
Closing in favour of https://github.com/joomla/joomla-cms/pull/31146

**Pull request closed without merging**
