### PR TITLE
Fix typo in comments

### PR DESCRIPTION
**Pull request by brianteeman**
Obvious typo "pf" should be "of"

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0281431e202aa2dbe15adf903314c74b057c8449<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22309">issues.joomla.org/tracker/joomla-cms/22309</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0281431e202aa2dbe15adf903314c74b057c8449<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22309">issues.joomla.org/tracker/joomla-cms/22309</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22309">issues.joomla.org/tracker/joomla-cms/22309</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
