### PR TITLE
[5.0] Move the compatibility plugin from system to behaviour folder

### PR DESCRIPTION
**Pull request by HLeithner**
This allows system plugins using the JPlugin class to still work with joomla 5.0 compatibility enabled

Pull Request for Issue when system plugins need JPlugin before the b/c plugin is loaded

### Summary of Changes
Moved the plugin from the system folder to the behaviour folder which is the first folder loaded by the cms.

### Testing Instructions
Use a system plugin which extends JPlugin.

### Actual result BEFORE applying this Pull Request
Might not work

### Expected result AFTER applying this Pull Request
Works now.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please add scripts to remove the system plugin files
Please add sql to remove the system plugin
Please update the language strings to use the correct prefix

**Comment by HLeithner** [comment]
not planing to do so, within alpha, only starting with beta1 to include an upgrade path

**Comment by brianteeman** [comment]
This is wrong - makes the nightly builds pointless

**Comment by HLeithner** [comment]
not true, they are for new installations and update from last stable version.

**Comment by brianteeman** [comment]
not true but you clearly know best and are free to change the practices of the last few years.

**Comment by HLeithner** [comment]
> Warning! These builds are intended for testing purposes only and should never be used on production websites.

We can break joomla installations beyond repair and in alpha version till beta1 of joomla 4 no upgrade policy exists. before this point in time even update breaks between rc and final exists (can't remember if this happend or not).

any way alpha is for testing and not for wasting time to write update scripts for 10 users that might need them because they don't have backups.

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on 71c7f5f41e76f865970b1e2a3c54d8fec0382e1b<br /><br />This resolved the issue for extensions with class JPlugin not working with the b/c plugin enabled. Tested two extensions that previously wouldn't install with b/c plugin enabled without throwing the JPlugin error. They install with this PR. Thanks. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41276">issues.joomla.org/tracker/joomla-cms/41276</a>.</sub>

**Comment by HLeithner** [comment]
thanks for testing

**Pull request merged**
