### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by release-joomla**
Enjoy!

### CODE REVIEW

**Comment by Bakual** [comment]
This PR needs a bit of an explanation I guess 😄 

This PR is automatically created by Crowdin based from the translations done in https://crowdin.com/project/joomla-cms
Since we don't distribute the translations with the core, this PR is to a great degree useless to us.

It **could** be used to update the installation language files, but we need to adjust the .gitignore file first I think, so the admin and site language folders are ignored.

So look at this as a work in progress.

**Comment by ghost** [comment]
@Bakual thanks for Explanation, haven't known whats meant.

**Comment by HLeithner** [comment]
Crowdin could make such a pr a bit better not generating 900 mails in my INBOX^^

**Comment by elkuku** [comment]
I believe that this is a good thing, but it is definitely making a lot of noise...

**Comment by Bakual** [comment]
>  it is definitely making a lot of noise...

Indeed :)

I've paused it now. We'll look for a solution.

**Comment by ggppdk** [comment]
> I've paused it now. We'll look for a solution.

Please give feedback if you find a solution

**Comment by brianteeman** [comment]
would it not be better for there to be a new repo that is used just for the language files? if i understand it correctly this change will result in extra commits everytime a single language file is updated.

**Comment by rdeutz** [comment]
However it is done in the future we need to make sure that a language file change doesn't trigger our CI setup, I canceled 800 builds alone on appveyor yesterday.

**Comment by Bakual** [comment]
> would it not be better for there to be a new repo that is used just for the language files?

No, because it would mean we need a script which updates that separate repo each day. And if we do that, we can as well just write a script which updates Crowdin directly. Which I did so far on my own server.
I wanted to avoid having to maintain own scripts when there is already an integration available.

That being said, I've got some inputs from Crowdin which hopefully reduce that commit spam to a reasonable amount.

**Pull request closed without merging**
