### PR TITLE
Cleanup on an unused lang string related to com_banners

### PR DESCRIPTION
**Pull request by rjcf18**
### Summary of Changes

Deleted an unused language string (COM_BANNERS_BANNERS_NO_ITEM_SELECTED) due because there is another language string (COM_BANNERS_NO_BANNERS_SELECTED) with almost the exact same content that is in fact used elsewhere. The deleted one had "No Banners selected." and the one that is used and that remained had "No banners selected.". 

### Testing Instructions

You can see that the deleted language string is not used anywhere:
deepinscreenshot20170414203623

And the other similar language string is in fact used:
deepinscreenshot20170414212149

### Expected result

No longer have an unused lang string while there is another that has the same content and that is used.

### Actual result

An unused lang string alongside another lang string with the same content.

### CODE REVIEW

**Comment by brianteeman** [comment]
For long and boring reasons it is not our practice to delete unused strings.

**Comment by rjcf18** [comment]
Oh ok I didn't know that sorry. Will take that into account from now on.

**Comment by zero-24** [comment]
@rjcf18 can you readd that string and add `; The following string are deprecated and will be removed with 4.0.` before that line?

**Comment by brianteeman** [comment]
@zero-24 don't forget a lot of unused strings have already been removed from j4 back in September

**Comment by rjcf18** [comment]
Sure I can do that. I can put something like `; This string is deprecated and will later be removed.`.

**Comment by brianteeman** [comment]
P!ease use the exact string that @zero-24 stated

**Comment by rjcf18** [comment]
I've placed the comment to flag the lang string as deprecated.

**Comment by rjcf18** [comment]
Ah ok sure.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/controller/admin.php#L120 This string is used through a concat of the prefix here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_banners/controllers/banners.php#L27

Tbh this should always be picked up by the javascript in the backend. But if somehow it gets forced through server side then this string will be used.

**Pull request closed without merging**
