### PR TITLE
Add a comment on the engine portion about upgrades

### PR DESCRIPTION
**Pull request by dgrammatiko**
So that the internal tools won't be broken

Pull Request for Issue # .

### Documentation Changes Required

This is purely a comment so any future upgrades of node/npm won't break the rest of the internal tools

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7927b8defa4194bf8ba6aac9a6662c3899964905<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37830">issues.joomla.org/tracker/joomla-cms/37830</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7927b8defa4194bf8ba6aac9a6662c3899964905<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37830">issues.joomla.org/tracker/joomla-cms/37830</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37830">issues.joomla.org/tracker/joomla-cms/37830</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
