### PR TITLE
Update MediaElement.js to 2.22.1

### PR DESCRIPTION
**Pull request by viocassel**
#### Summary of Changes

This PR updates the library MediaElement.js to version 2.22.0.

2.22.0 (2016/07/17)
- Introduce new stretching models (stretching: 'fill','responsive')
- Fix for IE9-10 fullscreen control hover issues
- Update Flash HLS to v0.4.4.21
- Update Flash HLS to accept audio
- Updated Korean translation
- Improve video ID parsing for YouTube URLs
- Removed extrainous call to removePlugin
#### Testing Instructions

Upload a mp4 into the Media Manager and try view the video.

### CODE REVIEW

**Comment by hardiktailored** [comment]
I have not tested this item.<br /><br />When applying patch receiving warning though Patch applies successfully. But still not able to upload mp4 file.

Warning
The patch you've applied includes binary files which the patch tester does not currently support.

Message
Patch successfully applied

Notice(When uploading mp4 file)
This file type is not supported.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Comment by jeckodevelopment** [comment]
Maybe you need to "approve" the file type into Media manager options.
Did you allow this extension?

**Comment by brianteeman** [comment]
> The patch you've applied includes binary files which the patch tester does not currently support.

You wont be able to use the patchtester  on its own to test this PR

After using the patchtester you will need to manually upload these two files
media/media/js/flashmediaelement-cdn.swf
media/media/js/flashmediaelement.swf
which you can download from here 
https://github.com/viocassel/joomla-cms/tree/012767ed796271385bb548e1f975fefff4f29f4c/media/media/js

then make sure you refresh the browser cache and you should be good to test



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Comment by hardiktailored** [comment]
@jeckodevelopment Thanks, I forgot to add file extention in allowed list. Now able to upload mp4 file.
@brianteeman I have updated existing flash files using link you provided.
But I found issue in previewing video, clicking on video name in media. Video is not rendering in popup properly. Closing and opening preview again works though.

See screen-shot(Chrome on Ubuntu 12.04)

screen shot 2016-07-30 at 08 07 16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Comment by brianteeman** [comment]
I can confirm the issue with previewing the video 
BUT
I get the exact same issue without the patch as well

**Comment by viocassel** [comment]
Update MediaElement.js to [2.22.1](https://github.com/johndyer/mediaelement/releases/tag/2.22.1) (2016/08/18)

- Fix wrong parameter sent to defaultSeekForwardInterval and defaultSeekBackwardInterval options
- Fullscreen in Safari Mac must show player skin
- Fix for aspect ratio when playing Hls Flash video if m3u8 does not have a resolution indicated
- Only focus the play button when the control bar is not hidden
- Avoid hiding audio controls when tabbing
- Stylesheet minor fixes
- Time update on rail only when controls are visible
- ARIA attributes for big play button to continue improving player accessibility

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de4ffd67226263a388a6cd7b6876f63df7520137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on de4ffd67226263a388a6cd7b6876f63df7520137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11363">issues.joomla.org/joomla-cms/11363</a>.</sub>

**Pull request merged**
