### PR TITLE
[4.0][com_actiologs]  better visualization for option  Verbs To Log

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
use fancy select

### Testing Instructions
administrator->user->user action log -> options

### Expected result

Screenshot from 2020-04-25 18-55-19

### Actual result

Screenshot from 2020-04-25 18-57-25

### CODE REVIEW

**Comment by sere-b** [comment]
I have tested this item :white_check_mark: successfully on 6f3ae3622f3ad7a36f69f3f1813724397d4122fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28802">issues.joomla.org/tracker/joomla-cms/28802</a>.</sub>

**Comment by ggenovino** [comment]
I have tested this item :white_check_mark: successfully on 6f3ae3622f3ad7a36f69f3f1813724397d4122fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28802">issues.joomla.org/tracker/joomla-cms/28802</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28802">issues.joomla.org/tracker/joomla-cms/28802</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
