### PR TITLE
[4.0] Change the select all toggle to a checkbox in media manager

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #34204.

### Summary of Changes
Replace the link to toggle all selection with a checkbox.

### Testing Instructions
- Go to /administrator/index.php?option=com_media
- Click the toggle all selection link

### Actual result BEFORE applying this Pull Request
All items are selected.

### Expected result AFTER applying this Pull Request
All items are selected.

### CODE REVIEW

**Comment by brianteeman** [comment]
Almost perfect.

Checking the box correctly selects all but when you do anything else afterwards which changes the selection the box remains checked. Which means you have to click it about three times to select all again

demo

**Comment by laoneo** [comment]
Try again

**Comment by brianteeman** [comment]
Still not right

demo

**Comment by laoneo** [comment]
Ok, figured it out, the problem is that preventDefault should not be called, otherwise the checkbox is not selected. If somebody else will come across this one, it is needed to stop propagation because of event listener here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L173. So we are not unselecting all of the items first which would result in an extra call. A side effect would be that the checkbox can't be watched and unselected when a single item gets selected.

**Comment by laoneo** [comment]
@brianteeman check again.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5f45fee233eacd9facc4f110f54409490ef4473b<br /><br />woohoo<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34597">issues.joomla.org/tracker/joomla-cms/34597</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 5f45fee233eacd9facc4f110f54409490ef4473b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34597">issues.joomla.org/tracker/joomla-cms/34597</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34597">issues.joomla.org/tracker/joomla-cms/34597</a>.</sub>

**Comment by richard67** [comment]
Back to pending. @laoneo Please fix code style errors reported here: https://ci.joomla.org/joomla/joomla-cms/45335/1/21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34597">issues.joomla.org/tracker/joomla-cms/34597</a>.</sub>

**Comment by laoneo** [comment]
@richard67 cs fixed...

**Comment by richard67** [comment]
I've restored the previous test results in the issue tracker since the commit which invalidated the test count was just code style.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34597">issues.joomla.org/tracker/joomla-cms/34597</a>.</sub>

**Comment by bembelimen** [comment]
Thank you!

**Pull request merged**
