### PR TITLE
Disable Chosen.js for the rule field, again

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #12843 .

### Summary of Changes
Revert the check for instance type of data-chosen, to allow to disable Chosen for field with data-chosen="true"

### Testing Instructions
Make sure that the rule field use simple `<select>` input (without Chosen stylling),
and all icons "ok/loading/error" are visible again when try to change the rule value

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on c4fe40ad7b7ac15694cdb15ef0704369a06cd442<br /><br />After patch is applied and browser cache cleared chosen is gone from ACL rule selects and icons are back.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12877">issues.joomla.org/tracker/joomla-cms/12877</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on c4fe40ad7b7ac15694cdb15ef0704369a06cd442<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12877">issues.joomla.org/tracker/joomla-cms/12877</a>.</sub>

**Comment by dgt41** [comment]
RTC

NOTE to whomever merge this: please ping me!

**Comment by wilsonge** [comment]
Is the only way to achieve this really with more hacks to chosen :(

**Comment by Fedik** [comment]
unfortunately, 
Correct way would be apply Chosen only to "specific" select with specific class, eg "advancedSelect", instead of apply Chosen to all `select` on the page, 

but for now it sounds like utopia 😉

**Comment by rdeutz** [comment]
@Fedik could you please remove the commented code 598-602, thanks

**Comment by rdeutz** [comment]
seems comment are the common practice, could you them please add the reason why this change was made, thanks

**Comment by Fedik** [comment]
@rdeutz ok, I will add

**Comment by Fedik** [comment]
@rdeutz added

**Comment by rdeutz** [comment]
@Fedik Thanks, merged

**Pull request merged**
