### PR TITLE
[4.0][com_contenthistory] fix php 7.4 deprecation

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #27214.

### Summary of Changes
php 7.4 compatibility

### Testing Instructions
If you compare two versions of an article you will get the error
Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in \joomla-cms\administrator\components\com_contenthistory\Model\CompareModel.php on line 104

### Expected result
no deprecated messages in log when php 7.4

### Actual result

deprecated messages in log

### CODE REVIEW

**Comment by brianteeman** [comment]
fixes the issue with compare two versions 
now I can see an issue when you preview a version

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in administrator\components\com_contenthistory\Model\PreviewModel.php on line 96
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27493">issues.joomla.org/tracker/joomla-cms/27493</a>.</sub>

**Comment by alikon** [comment]
should be fixed now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d9c77a894a3022d2f32c7f4f542b19b6bef975ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27493">issues.joomla.org/tracker/joomla-cms/27493</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d9c77a894a3022d2f32c7f4f542b19b6bef975ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27493">issues.joomla.org/tracker/joomla-cms/27493</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27493">issues.joomla.org/tracker/joomla-cms/27493</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by laoneo** [comment]
Backported it to staging in #29430.

**Pull request merged**
