### PR TITLE
[4.0] Routing not working in com_contact

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes routing not working in com_contact.

### Testing Instructions

Create contact category menu item.
View contact item links.

### Expected result

SEF links.

### Actual result

Non-SEF links.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 6d1924b88e821381ca9ee0c49bf4ba2123c27f84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27693">issues.joomla.org/tracker/joomla-cms/27693</a>.</sub>

**Comment by astridx** [comment]
I have tested this successful:

1. `git fetch origin pull/24311/head:ContactFrontendEditJ4`
2. First I made a new installation with standard settings.

3. I create two contacts 
4. I create a new `menu item` of the type `List Contacts in a Category.`
5. I click menu item `List Contacts in a Category` and then `one item` in the list.
6. I see the url `http://localhost/joomla-cms4/index.php/component/contact?view=contact&id=1:test&catid=4`
7. git checkout ContactFrontendEditJ4
git checkout j4/contact-routing 
8. I click the menu item again and I see `http://localhost/joomla-cms4/index.php/list-contacts-in-a-category/1-test`

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 6d1924b88e821381ca9ee0c49bf4ba2123c27f84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27693">issues.joomla.org/tracker/joomla-cms/27693</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27693">issues.joomla.org/tracker/joomla-cms/27693</a>.</sub>

**Comment by rdeutz** [comment]
We have to fix the test here, before we merge it

**Comment by astridx** [comment]
What do mean by "
We have to fix the test here, before we merge it"?

**Comment by astridx** [comment]
Should I test again?
What should I change?

**Comment by brianteeman** [comment]
@astridx Robert is referring to the failing system tests

**Comment by SharkyKZ** [comment]
Test failure not related to PR. It's tests for `Joomla\CMS\Image` that fail sometimes.

**Comment by rdeutz** [comment]
> Test failure not related to PR. It's tests for Joomla\CMS\Image that fail sometimes.

yep got that, had started the build quite some time and it had fail at the same step, but now it is good, so my mouse is hovering over the mergen button, stay tuned :-)

**Pull request merged**
