### PR TITLE
Replace showcase URLs in install data

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Change showcase site links from `https://community.joomla.org/showcase/` to  `https://showcase.joomla.org/` in installation sql files.
### Testing Instructions

Code review. Just URLs changed in installation sql files.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by bhavikTailored** [comment]
- I have review your code and tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11848">issues.joomla.org/joomla-cms/11848</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11848">issues.joomla.org/joomla-cms/11848</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11848">issues.joomla.org/joomla-cms/11848</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11848">issues.joomla.org/joomla-cms/11848</a>.</sub>

**Comment by brianteeman** [comment]
Are we sure this is a good idea? I am assuming they will be doing a redirect anyway. Plus we will have to do the same with the shop

**Comment by brianteeman** [comment]
scrub that comment - even if there is a redirect if we dont make the change then we will always get PRs to make the change

**Comment by mbabker** [comment]
Personal opinion, when it's feasible it's generally better to eliminate needless redirects.

**Pull request merged**
