### PR TITLE
[4.x] Backport fix for Error in PrivacyConsent::getPrivacyItemId()

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Backport changes from #41976 to 4.x branch

### Testing Instructions
See original PR.

### Actual result BEFORE applying this Pull Request
See original PR.

### Expected result AFTER applying this Pull Request
See original PR.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d2374fd9b2528d57c4e8d175afcc569f2d7444b<br /><br />Tested by code review: The application object doesn't have a getTag method, but the language object has.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43445">issues.joomla.org/tracker/joomla-cms/43445</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d2374fd9b2528d57c4e8d175afcc569f2d7444b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43445">issues.joomla.org/tracker/joomla-cms/43445</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43445">issues.joomla.org/tracker/joomla-cms/43445</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
