### PR TITLE
[5.0] Missing ID [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
The stats dialog on the dashboard references an id that didnt exist.

Simple fix - code review
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f055478e1c346fae42c6e0dcf2dcc9780deab7ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41949">issues.joomla.org/tracker/joomla-cms/41949</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on f055478e1c346fae42c6e0dcf2dcc9780deab7ed<br /><br />Just curious - I triggered the stats dialog and tested with axe.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41949">issues.joomla.org/tracker/joomla-cms/41949</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41949">issues.joomla.org/tracker/joomla-cms/41949</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
