### PR TITLE
[4.0] RTL Media field

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the media field on RTL displays

dont forget npm i

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1cae004f9515cfaee4f4c3228daeb36cee6c1b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27505">issues.joomla.org/tracker/joomla-cms/27505</a>.</sub>

**Comment by infograf768** [comment]
I think we need more and same issue in LTR/RTL

In `administrator/templates/atum/scss/blocks/_global.scss` line 149
We have
```
 //Multiple buttons wrapping
.input-group input {
  min-width: 220px;
}
```
This should be deleted, otherwise, depending on the modal width, we get for a modal

Screen Shot 2020-01-14 at 09 04 15

and when reducing window width when for example editing an article

Screen Shot 2020-01-14 at 09 08 21

After deleting that class

Screen Shot 2020-01-14 at 09 09 03


I had a fast look at other places in core where we have `.input-group input ` and deletion looks like it has no unwanted impact.
The correction can be done in this PR (easier) or in a specific PR.

**Comment by brianteeman** [comment]
@infograf768 that change was added by you here https://github.com/joomla/joomla-cms/pull/27128

**Comment by infograf768** [comment]
It looks like that had unwanted consequences...
We could solve it by not deleting that class (to keep associations displaying OK in mobile view and be eventually useful as @ciar4n said in #27128) but adding a new one specific to the image field.
```
#images .input-group input {
  min-width: 0;
}
```

This works here.

**Comment by ciar4n** [comment]
> This should be deleted, otherwise, depending on the modal width, we get for a modal

What is the problem here? Is it that the buttons wrap? In that instance, I would consider it acceptable behavior as the alternative is an unreadable input field. Fix the layout of the form, not the field.

**Comment by brianteeman** [comment]
I bow to the opinion of the designer

**Comment by infograf768** [comment]
@ciar4n 
Ooops, I forgot that the field may be filled by the image path...

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bf62cf985e79ebf35f71ca7803a8c6a02fedcb43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27505">issues.joomla.org/tracker/joomla-cms/27505</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27505">issues.joomla.org/tracker/joomla-cms/27505</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
