### PR TITLE
[4.2] Fix none empty string validation for MediaItem

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #37242.

### Summary of Changes
This simple PR fixes media manager broken when there is folder with name 0 (zero) managed by media manager.

### Testing Instructions
1. Create a folder with name **0**  (zero character) under images folder (this folder must be created outside media manager)
2. Access to Content -> Media and try to navigate to that folder

### Actual result BEFORE applying this Pull Request
You get error: Property 'name' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: non empty string

### Expected result AFTER applying this Pull Request
No error, media manager works properly

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1b4f3c6cfc3d7fe0887300cd4c73e84938b6d71c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39476">issues.joomla.org/tracker/joomla-cms/39476</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1b4f3c6cfc3d7fe0887300cd4c73e84938b6d71c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39476">issues.joomla.org/tracker/joomla-cms/39476</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39476">issues.joomla.org/tracker/joomla-cms/39476</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
