### PR TITLE
[4.0] toolbar button

### PR DESCRIPTION
**Pull request by brianteeman**
Redo of #21202

### CODE REVIEW

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on b9e06e315e9afe0756a89b3f8db08e1b4f9143b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21215">issues.joomla.org/tracker/joomla-cms/21215</a>.</sub>

**Comment by infograf768** [comment]
will test ok after correction in toolbar scss

**Comment by brianteeman** [comment]
Hound should be fixed now

**Comment by wilsonge** [comment]
Tested succesfully. Thanks

**Comment by brianteeman** [comment]
thanks. scss isnt as hard to work out as i thought

**Pull request merged**
