### PR TITLE
Alert container background removed

### PR DESCRIPTION
**Pull request by vlaucht**
Pull Request for Issue #26817 

### Summary of Changes
Background of system message container has been removed

### Testing Instructions
apply PR
run npm i 
Do something that will create multiple alerts. eg install a patch with com_patchtesters

### Expected result
Background of container should be transparent

### Documentation Changes Required
none

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Can you please make these changes against https://github.com/joomla/joomla-cms/pull/26077 
You see there is a very wrong approach considering the css as a monolith and also it’s against the joomla’s intended way...

**Comment by BertaOctech** [comment]
I have tested this item :red_circle: unsuccessfully on dbecdc48b099a79263e7aaed929bb466a0064f14<br /><br />I applied a random patch to observe the effect and the revert the patch. Infact the space between messages was not transparent
Then I applied the patch and applied a second patch to observe the messages.

I am afraid nothing changed.

I am using Firefox on suseLinux<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26855">issues.joomla.org/tracker/joomla-cms/26855</a>.</sub>

**Comment by Quy** [comment]
@dgrammatiko Is this still a valid fix?

**Comment by dgrammatiko** [comment]
@Quy yes! but the PR needs to be updated (we moved the alert code to it's own file, the comment I made above)

**Comment by Quy** [comment]
Please test PR #27394

**Pull request closed without merging**
