### PR TITLE
Image contact category list new

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request replacing #8580 
#### Summary of Changes

That is a clean pull request replacing #8580 since I accidentally removed the installation folder on my last commit. Sorry for the inconvenience!
Removed the image column parameters as asked by @wilsonge 
#### Testing Instructions

Same as #8580 but without parameters.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 9947a91d2b7f9a5206858229e34550404d97452a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by brianteeman** [comment]
I think this will need a change in the beez3 template as that template has an override for this view<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 9947a91d2b7f9a5206858229e34550404d97452a<br /><br />Works on Protostar, not on Beez3, so i have to change the Test-Result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by wojsmol** [comment]
@drmenzelit See https://github.com/drmenzelit/joomla-cms/issues/2

**Comment by iljabos** [comment]
I have tested this item :red_circle: unsuccessfully on bfa98d816653b4191150ef434141d2d1ba6ca693<br /><br />I have tested this but there was no image in the contactlist. 
Contact webmaster does have an image.
I tried it on Beez3 and Protostar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by drmenzelit** [comment]
@iljabos Can you please explain what you did?

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on bfa98d816653b4191150ef434141d2d1ba6ca693<br /><br />Works fine here <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by iljabos** [comment]
I have tested this item :white_check_mark: successfully on bfa98d816653b4191150ef434141d2d1ba6ca693<br /><br />Second time I tested succesfull for a list of contacts in a **single** category. The first time I used featured contacts.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Comment by MDXBilal12** [comment]
I have tested this item :white_check_mark: successfully on bfa98d816653b4191150ef434141d2d1ba6ca693<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9906">issues.joomla.org/joomla-cms/9906</a>.</sub>

**Pull request merged**
