### PR TITLE
[6.0] Remove obsolete code

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Per comment, remove obsolete code.

### Documentation
Manual Update: https://github.com/joomla/Manual/pull/321

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 45c0c0c96a5911943dfede9060d8859f5191feb0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43959">issues.joomla.org/tracker/joomla-cms/43959</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 45c0c0c96a5911943dfede9060d8859f5191feb0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43959">issues.joomla.org/tracker/joomla-cms/43959</a>.</sub>

**Comment by laoneo** [comment]
This needs to go into 6.0 as it is a bc break.

**Comment by Fedik** [comment]
> Per comment, remove obsolete code.

It was for 5.0, but cannot go into 5.x. It can go to 6.0, but cannot go into 6.x :wink:

**Comment by Fedik** [comment]
One more thing. 
The following properties also should be removed with this PR:
```php
 protected static $gmt;
 protected static $stz;
```

They not in use by core, but were kept for backward compatibility.
See the original PR https://github.com/joomla/joomla-cms/pull/29270

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 73d7d4d0d736e49b25df7f8a199012bf32d8d740<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43959">issues.joomla.org/tracker/joomla-cms/43959</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 73d7d4d0d736e49b25df7f8a199012bf32d8d740<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43959">issues.joomla.org/tracker/joomla-cms/43959</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43959">issues.joomla.org/tracker/joomla-cms/43959</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
