### PR TITLE
[5.0] Cleaning the localization of the plugin "System - Debug"

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
After the "rebranding" of the plugin in the 4th version, 95% of the language strings are outdated, since they are hardcoded into the JS files.

In addition to checking with some program to find strings, enable debugging + language debugging in the general site settings + enable the debugging plugin and make sure everything works as it did before the PR.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 773c129eb32473afd0c2721593db92bbc2a6d1b2<br /><br />No clue about the date in copyright.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37668">issues.joomla.org/tracker/joomla-cms/37668</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 773c129eb32473afd0c2721593db92bbc2a6d1b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37668">issues.joomla.org/tracker/joomla-cms/37668</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37668">issues.joomla.org/tracker/joomla-cms/37668</a>.</sub>

**Comment by bembelimen** [comment]
This can only happen in 5.0 ([see](https://developer.joomla.org/development-strategy.html#backward_compatibility))

**Pull request closed without merging**
