### PR TITLE
remove cassiopeia/images/system

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35544.

### Summary of Changes
remove unused folder

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 997a27db1c509509c3519116b52cec3cb0c70074<br /><br />nice cleanup!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35549">issues.joomla.org/tracker/joomla-cms/35549</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 997a27db1c509509c3519116b52cec3cb0c70074<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35549">issues.joomla.org/tracker/joomla-cms/35549</a>.</sub>

**Comment by alikon** [comment]
is there nothing more to do with 
	https://github.com/richard67/joomla-cms/blob/916cae7fb405398c937123b37c036b938c15ef84/administrator/components/com_admin/script.php#L624

?

**Comment by wojsmol** [comment]
@richard67 Please help with script.php part.

**Comment by richard67** [comment]
@wojsmol @alikon We do not bother authors of pull requests anymore to do that. At least before each release or after pull requests have been merged which require this, @wilsonge or me use a tool to generate the list of files and folders to be deleted and update script.php. So for me this PR is fine, and I have it on my watchlist to see when it's merged and then update script.php.

**Comment by alikon** [comment]
super

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35549">issues.joomla.org/tracker/joomla-cms/35549</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
