### PR TITLE
5.0 Useless returns

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove useless returns

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

See bad code.

### Expected result AFTER applying this Pull Request

See good code.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 450057fad390b8269fc1202181171700c7f23d8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41656">issues.joomla.org/tracker/joomla-cms/41656</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 450057fad390b8269fc1202181171700c7f23d8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41656">issues.joomla.org/tracker/joomla-cms/41656</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41656">issues.joomla.org/tracker/joomla-cms/41656</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
