### PR TITLE
Fix Joomla version note

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #32578 .

### Summary of Changes
Update some version notes incorrectly set in the last release

/cc  @PhilETaylor

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Incomplete. There are SIX __DEPLOY_VERSION__ in the distributed Joomla 3.9.25 stable zip.

**Comment by HLeithner** [comment]
Yes but they got wrongly tagged in the reset to dev bump

**Comment by PhilETaylor** [comment]
Yup Im wrong. This PR looks good.

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 5e407ac528d56366cccfb999674583a0226b9ed3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32731">issues.joomla.org/tracker/joomla-cms/32731</a>.</sub>

**Comment by ChristineWk** [comment]
@HLeithner 

checked each file via FTP successful. But I don't hv /installation/... :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32731">issues.joomla.org/tracker/joomla-cms/32731</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
