### PR TITLE
Update phar-stream-wrapper

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #23907 .

### Summary of Changes
Updated phar-stream-wrapper to 2.0 dev version fixing https://github.com/joomla/joomla-cms/issues/23907

@jurihahn please test this PR

### CODE REVIEW

**Comment by mbabker** [comment]
`libraries/vendor/brumann/polyfill-unserialize/composer.json` should be added to the `.gitignore` file (consistent with everything else checked into the repo).

And update your local Composer version, looks like you're a few releases behind if you're getting 2016 in the license file 😛

**Comment by HLeithner** [comment]
hehe thats the reason way I only did a unmergeable draft PR ;-)

**Comment by jurihahn** [comment]
I have tested this item :white_check_mark: successfully on 2c6577c1a80afcd6c076983de3ce84feb1caca62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23956">issues.joomla.org/tracker/joomla-cms/23956</a>.</sub>

**Comment by HLeithner** [comment]
@jurihahn I update to 2.1 please retest this PR thx

**Comment by jurihahn** [comment]
I have tested this item :white_check_mark: successfully on f85648a4b811f59ac535702f26762ea4bd600762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23956">issues.joomla.org/tracker/joomla-cms/23956</a>.</sub>

**Comment by HLeithner** [comment]
thx for testing.

**Pull request merged**
