### PR TITLE
[4.1] Cassiopeia Terms of Service - Display Options Inline

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
The PR https://github.com/joomla/joomla-cms/pull/37709 missing the profile plugin (Terms of Service parameter).

Enable the option in the plugin User - Profile and check the options on the registration page.

Screenshot_1

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 577120e805720aade4e63b469af1ea0d05f471f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37858">issues.joomla.org/tracker/joomla-cms/37858</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a9ba9ada5beedbe9f7f48a1d36f5fac66e7394e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37858">issues.joomla.org/tracker/joomla-cms/37858</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37858">issues.joomla.org/tracker/joomla-cms/37858</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
