### PR TITLE
[4.0] RTL Permissions

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the margin on the permissions pages for components etc not for individual items.
dont forget npm i

There is more to do on this page for RTL but thats for another day

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 32b1d4c804362e98cae0c0aa618eca6fd3f451b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27506">issues.joomla.org/tracker/joomla-cms/27506</a>.</sub>

**Comment by infograf768** [comment]
I suggest to add a specific dir=ltr for the margin-left

**Comment by brianteeman** [comment]
There is no need

**Comment by infograf768** [comment]
It is always better to do that as otherwise you would need to do a mergin-left: auto to make sure nothing wrong happens, also we have to check mobile view.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 32b1d4c804362e98cae0c0aa618eca6fd3f451b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27506">issues.joomla.org/tracker/joomla-cms/27506</a>.</sub>

**Comment by infograf768** [comment]
This solves indeed what the PR is for.
As stated, there are other aspects remaining in ltr as well as rtl.
Mobile is anyway quite useless as the groups will always show below the permissions (which is not the case in J3). Will merge as soon as drone is fine.

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
Thanks - one issue at a time

**Pull request merged**
