### PR TITLE
Remove link from tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
`PLG_CODEMIRROR_FIELD_VIM_KEYBINDING_DESC="Select this option to make CodeMirror work in Vim mode."`

It is never possible to click on that link inside the tooltip - this PR removes the link

### CODE REVIEW

**Comment by roland-d** [comment]
@test: Looks good based on code review.

**Comment by losedk** [comment]
It's clickable on mobile devices. But I agree, it should properly be removed

**Comment by losedk** [comment]
There's a number of other descriptions, where links are present. Perhaps we should remove these as well to maintain consistency?

**Comment by brianteeman** [comment]
I didn't spot them can you let me know

**Comment by losedk** [comment]
@brianteeman 

Thinks that all of them:

PLG_CAPTCHA_NOCAPTCHA_XML_DESCRIPTION (SYS)
PLG_GMAIL_XML_DESCRIPTION (SYS)
PLG_CAPTCHA_NOCAPTCHA_XML_DESCRIPTION
PLG_GMAIL_XML_DESCRIPTION
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION (plugins)
PLG_CAPTCHA_RECAPTCHA_XML_DESCRIPTION
PLG_TINY_FIELD_SKIN_INFO_LABEL

**Comment by zero-24** [comment]
@brianteeman what do you think if we move the link to 
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.plg_editors_codemirror.ini#L55

so we have
`PLG_CODEMIRROR_FIELD_VIM_KEYBINDING_LABEL="<a href="_QQ_"http://en.wikipedia.org/wiki/Vim_%28text_editor%29"_QQ_" target="_QQ_"_blank"_QQ_">Vim</a> Keybinding"`

**Comment by zero-24** [comment]
>PLG_CAPTCHA_NOCAPTCHA_XML_DESCRIPTION (SYS)
PLG_GMAIL_XML_DESCRIPTION (SYS)
PLG_CAPTCHA_NOCAPTCHA_XML_DESCRIPTION
PLG_GMAIL_XML_DESCRIPTION
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION
PLG_SYSTEM_LANGUAGECODE_XML_DESCRIPTION (plugins)
PLG_CAPTCHA_RECAPTCHA_XML_DESCRIPTION
PLG_TINY_FIELD_SKIN_INFO_LABEL


All clickable see here e.g. for the gmail.

gmail


same applys to the tinyMCE string:
tiny

**Comment by losedk** [comment]
Ohh okay. Didn't notice that they weren't descriptions for labels. Sorry!

**Comment by zero-24** [comment]
You are welcome @losedk :+1:

**Comment by losedk** [comment]
@zero-24 think your proposal is good:

skaermbillede 2015-01-05 kl 19 06 29

But perhaps it should be for the entire label?

**Comment by brianteeman** [comment]
It shouldnt be for the whole label and I'm not convinced its a good idea to
have links in labels

**Comment by zero-24** [comment]
>But perhaps it should be for the entire label?

I agree. So the new string would be:

PLG_CODEMIRROR_FIELD_VIM_KEYBINDING_LABEL="<a href="_QQ_"http://en.wikipedia.org/wiki/Vim_%28text_editor%29"_QQ_" target="_QQ_"_blank"_QQ_">Vim Keybinding</a>"

What do you think @brianteeman ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5621">issues.joomla.org/joomla-cms/5621</a>.</sub>

**Comment by rdeutz** [comment]
I am going to merge this one because it doesn't makes sense to have it in the tooltip and I have my doubts that a link to wikipedia (to explain what vim is) makes sense at all.

**Comment by losedk** [comment]
:+1:

**Pull request merged**
