### PR TITLE
[plg_search_newsfeeds]Code style

### PR DESCRIPTION
**Pull request by wojsmol**
### Summary of Changes

Code style changes for plg_search_newsfeeds
### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fa521a924f90755255c4db8a3d4255b2b9a76857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10494">issues.joomla.org/joomla-cms/10494</a>.</sub>

**Comment by JoomliC** [comment]
@wojsmol maybe removal of empty line after closing <code>fielset</code>?

**Comment by wojsmol** [comment]
@JoomliC done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e6f81368fe9b67a165b2a1fb732d6848b908750a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10494">issues.joomla.org/joomla-cms/10494</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on e6f81368fe9b67a165b2a1fb732d6848b908750a<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10494">issues.joomla.org/joomla-cms/10494</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10494">issues.joomla.org/joomla-cms/10494</a>.</sub>

**Comment by JoomliC** [comment]
@wojsmol thanks! :+1:

**Pull request merged**
