### PR TITLE
[4.0] Add structured data to newsflash

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Newsflash has no structured data.

### Testing Instructions
Inspect Sourcecode of a module with structured data.

### Actual result BEFORE applying this Pull Request
No structured data

### Expected result AFTER applying this Pull Request
Articles are marked as  itemscope itemtype="https://schema.org/Article"

### CODE REVIEW

**Comment by ChristineWk** [comment]
Before:
`<div class="mod-articlesnews newsflash">div class="mod-articlesnews__item">`

After:
`<div class="mod-articlesnews newsflash"><div class="mod-articlesnews__item" itemscope="" itemtype="https://schema.org/Article">`

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 24fd4681be569708333d04968832df6db845c92d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32502">issues.joomla.org/tracker/joomla-cms/32502</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 24fd4681be569708333d04968832df6db845c92d<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32502">issues.joomla.org/tracker/joomla-cms/32502</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32502">issues.joomla.org/tracker/joomla-cms/32502</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
