### PR TITLE
joomla-cms / administrator / language / en-GB / en-GB.com_cpanel.ini

### PR DESCRIPTION
**Pull request by Hils**
Grammar correction - addition of **'s'** line 29 - 'change**'s'** (plural)

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c2cf3a080fa525963b40378e5997b01df3a38b70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9422">issues.joomla.org/joomla-cms/9422</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c2cf3a080fa525963b40378e5997b01df3a38b70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9422">issues.joomla.org/joomla-cms/9422</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9422">issues.joomla.org/joomla-cms/9422</a>.</sub>

**Comment by Hils** [comment]
Thank you! Let me know if there is anything I need to do with the branch conflict stuff please

**Comment by rdeutz** [comment]
@Hils could you check the merge conflicts, thanks.

**Comment by brianteeman** [comment]
@hils As i think you just use github.com to do your pull requests then you might find this useful to update your branch and resolve the merge conflicts http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/ <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9422">issues.joomla.org/joomla-cms/9422</a>.</sub>

**Comment by rdeutz** [comment]
@Hils redo and close this one might be easier

**Comment by rdeutz** [comment]
closing this one because of #9900

**Pull request closed without merging**
