### PR TITLE
[4.0] Mass mail users

### PR DESCRIPTION
**Pull request by brianteeman**
the checkbox is not aligned correctly as there is a class missing

Pull Request for Issue #21876

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0fe561eee21f39e1b19d8be9f733ea828c659a34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21878">issues.joomla.org/tracker/joomla-cms/21878</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0fe561eee21f39e1b19d8be9f733ea828c659a34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21878">issues.joomla.org/tracker/joomla-cms/21878</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
