### PR TITLE
Update fa-IR installation language

### PR DESCRIPTION
**Pull request by Bakual**
Please review and merge once Travis passes

### CODE REVIEW

**Comment by infograf768** [comment]
this ini file has windows EOL instead of Unix

**Comment by infograf768** [comment]
Here is a corrected file (for EOL) only.

[fa-IR.ini.zip](https://github.com/joomla/joomla-cms/files/1325155/fa-IR.ini.zip)

**Comment by infograf768** [comment]
Hmm, I am afraid it can't be used as patch. 
@mbabker 
I suggest to delete the original file and add the one in the zip to make sure it is now Unix.

**Comment by infograf768** [comment]
I.e use this one
[fair.ini.diff.zip](https://github.com/joomla/joomla-cms/files/1325212/fair.ini.diff.zip)

**Comment by Bakual** [comment]
Let me fix it 😄

**Comment by Bakual** [comment]
Better now?

I thought my Git does change the line endings automatically, but apparenlty it didn't in this case?

**Pull request merged**
