### PR TITLE
[4.0] Improve article list performance on multilingual sites

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25770.

### Summary of Changes

Replaces `JOIN` and `GROUP` clauses in query with a subquery.

### Testing Instructions

Set up a multilingual site.
Enable associations.
Create some articles and add associations.
View article list in backend.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 10687ec3cfd6660a5cd7e281f839421460b6e788<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

About performance I can't say anything because my test data set is too small.

But I can confirm everything works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log.

There is a PHP notice "Undefined index: link in /layouts/joomla/content/associations.php on line 18" at least when using PostgreSQL before and after having applied this PR, so not related to this PR. This just as info for other testers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26465">issues.joomla.org/tracker/joomla-cms/26465</a>.</sub>

**Comment by alikon** [comment]
What language have you used in the installation step ?
i've tryied persian , french always got this  trying to add multilanguage content sample data 
Screenshot from 2019-10-04 19-09-51

**Comment by richard67** [comment]
Sometimes content languages are not added after language install. I've helped myself then with uninstalling languages and installing again.

**Comment by alikon** [comment]
seems that  German - DE  allows me to run sample multilanguage data (just for note on postgresql now)

**Comment by richard67** [comment]
I'm using German (DE), French and for RTC sometimes Persian.

**Comment by SharkyKZ** [comment]
@alikon you may have to create a Content Language manually.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 89e6b32886a0c9e674c538bda0d18f6a5dcc10b0<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

About performance I can't say anything because my test data set is too small.

But I can confirm everything works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26465">issues.joomla.org/tracker/joomla-cms/26465</a>.</sub>

**Comment by alikon** [comment]
@SharkyKZ  ok maybe another issue to open if it will be still there when we will have languages pack ready for 4, anyway PR seems fine & all works as before , despite i don't  have a good big dataset to do some real case performance check... i cannot trust my EXPLAIN with my short data , but it looks fine and i cannot guess how it can works worst than now...

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 89e6b32886a0c9e674c538bda0d18f6a5dcc10b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26465">issues.joomla.org/tracker/joomla-cms/26465</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26465">issues.joomla.org/tracker/joomla-cms/26465</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
