### PR TITLE
[4.0] Updating to PHPCS3

### PR DESCRIPTION
**Pull request by Hackwar**
This updates PHPCS to version 3 and fixes all violations. This requires https://github.com/joomla/cms-coding-standards/pull/5 to be merged.

### CODE REVIEW

**Comment by wilsonge** [comment]
I guess it goes without saying drone doesn't think this works :) Maybe the cache?

**Comment by Hackwar** [comment]
As I wrote above, the other PR to cms-coding-standards has to be merged first for this to work.

**Comment by wilsonge** [comment]
Tagged an alpha2 so please use that rather than just dev

**Comment by Hackwar** [comment]
I have no idea what I have to put into the composer.json for that. Also, the tag says that there are 0 commits in that tag. Otherwise this would be ready for now.

**Comment by wilsonge** [comment]
Now the alpha has been released please use the tagged version rather than the branch

**Comment by wilsonge** [comment]
We seems to have significantly less assertions in PHPCS 3 than 2. Is there a reason for this?

**Comment by 810** [comment]
v2 runs deprecated code filters also there where some exclude filter issues, now on v3 it has been resolved.

**Pull request merged**
