### PR TITLE
[4.0] Make alert inline consistent

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Make alert inline consistent like this.

no-matching-results

### Testing Instructions
Go to System > Warnings

### Expected result
alert-after

### Actual result
alert-before

### CODE REVIEW

**Comment by brianteeman** [comment]
Goof spot but you need to fix the other ones in the same file as well

**Comment by Quy** [comment]
I am not sure how to handle these.

The first one has dynamic heading and description. I will have to see what possible headings are.

For the second one, can the heading be replaced with the `i` icon?
> COM_INSTALLER_MSG_WARNINGFURTHERINFO="Further information on warnings"

```
						<?php foreach ($this->messages as $message) : ?>
							<div class="alert alert-warning">
								<h4 class="alert-heading"><?php echo $message['message']; ?></h4>
								<p class="mb-0"><?php echo $message['description']; ?></p>
							</div>
						<?php endforeach; ?>
						<div class="alert alert-info">
							<h4 class="alert-heading"><?php echo Text::_('COM_INSTALLER_MSG_WARNINGFURTHERINFO'); ?></h4>
							<p class="mb-0"><?php echo Text::_('COM_INSTALLER_MSG_WARNINGFURTHERINFODESC'); ?></p>
						</div>
```

**Comment by brianteeman** [comment]
just about to start a presentation. i wont be able to take a look now until tomorrow

**Comment by brianteeman** [comment]
For the first one I think we need to keep the heading but we could include the relevant icon for some consistency

image


For the second message you are correct

Note the exact same code is used in com_joomlaupdate so that would need updating as well

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 5aecd4c4b60e2a135439ea1015907fa83d7aaf38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27707">issues.joomla.org/tracker/joomla-cms/27707</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5aecd4c4b60e2a135439ea1015907fa83d7aaf38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27707">issues.joomla.org/tracker/joomla-cms/27707</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27707">issues.joomla.org/tracker/joomla-cms/27707</a>.</sub>

**Comment by brianteeman** [comment]
The exact same code in joomlaupdate should be changed as well

**Pull request merged**
