### PR TITLE
Fixed the modal filter to not use the search value of the category list

### LINKED ISSUE #8222: com_category Error while using modal for making multilingual associations between the categories
#### Steps to reproduce the issue
See this video to understand the issue
https://www.youtube.com/watch?v=-qs2PiXCA3A&feature=youtu.be

1. install Joomla Multilingual website, French and English
2. Create category with Engligh (UK) language.
3. Create category with French (FR) language.
4. search for the english category in the search bar.
5. click on the category (english).
6. Go in the association section.
7. click on select.
8. search for the french category.
9. french category gets replaced by the english category
10. you will see the error.

#### Expected result
1. we get the french category on searching it in the modal

#### Actual result
2. Search fails

#### System information (as much as possible)
Macbook pro
El Capitan
Safari
firefox

### PR DESCRIPTION
**Pull request by roland-d**
The association modal was broken due to the filters automatically set on chosen options in another screen. The modal now uses it's own search field.

This fixes #8222 and test instructions can be found there. The output should now be the expected result after applying this fix.

### CODE REVIEW

**Comment by n9iels** [comment]
After applying the patch, the French category is visible, but I still can't search for another category.
I search for the category "park site", when I search in the modal of the associate tab the value of the search field still keeps "Park site" when I hit the search button.

**Comment by roland-d** [comment]
@n9iels The search value is supposed to remain in the search field.

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 57e0c3787625ce415269b86d22b74097447e2d35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by infograf768** [comment]
This does not work correctly here. The only aspect changed is that it now displays the correct list of categories in the chosen associated language, which is indeed much better.

Search in the modal does not give any result. It just display again the whole list of items. When searching, the field keeps the value given in the manager and does change when one enters another value or when clearing.
After choosing a category in the modal, when coming back to the Manager, the Search Tools Language filter  is set to the Language chosen for the association (really wrong) and the search field has exactly the same value as before, which basically displays an empty list as the item searched in the Manager originally was in another language.


The search in the modal is still totally broken, even when not having searched first in the Manager.
See https://www.dropbox.com/s/vnawvxgxqf51bfg/modal.mp4?dl=0

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 57e0c3787625ce415269b86d22b74097447e2d35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by infograf768** [comment]
Search in modal now works. :)

One issue remains, when save and close and redirecting to the manager, the manager is filtered by the associated language as I explained above.
This will explain better than words. The original category is tagged to French. I confirm the choice for an en-GB item in the modal.
https://www.dropbox.com/s/duvijfoy196ouyp/category_filter.mp4?dl=0

**Comment by infograf768** [comment]
Forgot to say that we do not have this issue when doing the same for articles.

**Comment by roland-d** [comment]
@infograf768 That remark about articles was spot on. I think I have a cleaner solution now.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4ba23086e1d7af123a4a3d61fb0f84e8a71107f6<br /><br />That is not totally OK. One more test to get this in. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4ba23086e1d7af123a4a3d61fb0f84e8a71107f6<br /><br />That is now totally OK. One more test to get this in. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 4ba23086e1d7af123a4a3d61fb0f84e8a71107f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8227">issues.joomla.org/joomla-cms/8227</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thanks @roland-d and testers! Merged.

**Pull request merged**
