### PR TITLE
Search secret in plugins and modules

### PR DESCRIPTION
**Pull request by brianteeman**
The search tip for com_modules and com_plugins does not show that you can search by ID as well as title. This PR fixes that - there is no new functionality - this has always been possible just not displayed.
### Before

module-before

plugin-before
### After

module-after

plugin-after

### CODE REVIEW

**Comment by Fedik** [comment]
@brianteeman sorry I am not native english, just thought about: can it be with an example, something like `Use id:<number> for search for a plugin ID`?

**Comment by brianteeman** [comment]
@Fedik thanks for looking - it could be indeed BUT this is how the tips for Menus and Content are written right now and I didnt want to make too many changes. Not sure it is necessary myself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7532">issues.joomla.org/joomla-cms/7532</a>.</sub>

**Comment by MAT978** [comment]
Still not totally convinced but #7532 works as described.
What about: **Search in module title or ID**

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7532">issues.joomla.org/joomla-cms/7532</a>.</sub>

**Comment by brianteeman** [comment]
Mat you have to use ID: as a prefix to search the ID so that text isn't
correct

**Comment by AshwathiVenugopal** [comment]
Tested in Chrome(Version 44.0.2403.89 m) and IE8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7532">issues.joomla.org/joomla-cms/7532</a>.</sub>

**Comment by gunjanpatel** [comment]
We have two successful tests. Moving to RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7532">issues.joomla.org/joomla-cms/7532</a>.</sub>

**Comment by Bakual** [comment]
Merge into `staging`. Thanks!

**Pull request closed without merging**
