### PR TITLE
[4.1] Release Checklist typos

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 22739600c6a14514c95b0eead5f84677338151ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36902">issues.joomla.org/tracker/joomla-cms/36902</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 22739600c6a14514c95b0eead5f84677338151ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36902">issues.joomla.org/tracker/joomla-cms/36902</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36902">issues.joomla.org/tracker/joomla-cms/36902</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
