### PR TITLE
Fixed Strip whitespace from Json string before decoding (joomla-cms/libraries/vendor/joomla/registry/src/Format/Json.php)

### PR DESCRIPTION
**Pull request by Bhola-B2C**
Pull Request for Issue #14502 .

### Summary of Changes
Beside using trim, I also used preg_replace() to remove any whitespaces in between the JSON string.

### Testing Instructions
Code Review

### Documentation Changes Required
None

### CODE REVIEW

**Comment by mbabker** [comment]
👎 as explained in the other issue it is not this formatter's responsibility to "clean" the data it receives.  The outer trim is a sanity check but anything happening to the actual data is invalid and potentially breaks the fallback onto the INI format used if the basic JSON checks are not met.

**Comment by Bhola-B2C** [comment]
Then what should be done

**Comment by Bhola-B2C** [comment]
I'm not able to understand..explain it clearly plz

**Comment by brianteeman** [comment]
Closed  for the reason stated above by @mbabker

**Pull request closed without merging**
