### PR TITLE
Use the new native title metadata in installed languages view

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Use the new native name metadata in installed languages view

image
### Testing Instructions
1. Use latest staging
2. Apply patch
3. Go to Extensions >Languages > Installed
4. Check there is a new column (Native Title) with the info
5. Test site and admin languages.

The code was also optimized to use the new JLanguageHelper::getInstalledLanguages method.
### Documentation Changes Required

None.

@infograf768 please check this.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
yes we can, will add a `-` then

**Comment by andrepereiradasilva** [comment]
done

**Comment by brianteeman** [comment]
Sorry i am confused
The Native Language column is complete in the content language view and incomplete in the installed language view

image

image

**Comment by andrepereiradasilva** [comment]
@brianteeman the native name for a language is a new metadata value for the site/admin language, when the language packs translate that metadata value it will apeear here.

The content languages use other method since, IIRC, they fallback to the name, and if installed using install they even fallback to a language var in installation inis.

This was made to preserve B/C.

In the future this nativeName metadata should be the native title used for all views: Installed languages, Content Languages and Installation.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a0388f476b871aa875aa9055d52402479bfdb026<br /><br />Does what you say it will do althuough kind of hard to test if no language supports this yet<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12641">issues.joomla.org/tracker/joomla-cms/12641</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> Does what you say it will do althuough kind of hard to test if no language supports this yet

They will in 3.7.0. See for instance https://crowdin.com/translate/joomla-cms/532/engb-pt

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 966431617cd7296374aed0acd0301a44f9315d8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12641">issues.joomla.org/tracker/joomla-cms/12641</a>.</sub>

**Comment by infograf768** [comment]
RTC

screen shot 2016-11-01 at 01 47 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12641">issues.joomla.org/tracker/joomla-cms/12641</a>.</sub>

**Comment by infograf768** [comment]
@andrepereiradasilva 
Note: I remarked that updating a language pack via Extensions=>Install=>Upload Package File does not create a Content Language. 
If a pure install (i.e. NOT updating), the Content language is created.
You may want to look into this

**Comment by andrepereiradasilva** [comment]
@infograf768 not related to this PR will check that in another PR if needed

**Comment by alikon** [comment]
@andrepereiradasilva  just noticed that in a pure install (i.e. NOT updating), the Content languages other than en-GB - English are not more created with postgresql , some other PR's maybe have create these issues

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva just noticed that in a pure install (i.e. NOT updating), the Content languages other than en-GB - English are not more created with postgresql , some other PR's maybe have create these issues

Seems to be database related. Can you open a new issue @alikon ?

**Pull request merged**
