### PR TITLE
fixes overridebility of com_media

### PR DESCRIPTION
**Pull request by Webdongle**
Fixes administrator/components/com_media/views/images/tmpl/default.php override failing
#### Test instructions:

Apply this patch with patch tester
Go to protostar/html and create a folder com_media
Create another folder named images
Copy the content of the file administrator/components/com_media/views/images/tmpl/default.php to the newly created file
Edit the file so the first line above the first form tag to be `<div><h1>This is a Protostar Override</h1></div>`
Now try to login in the fronted and edit an article.
Go to Images and link and try to select an image
If you see the title This is a Protostar Override in the modal the you have a successful test!

### CODE REVIEW

**Comment by dgt41** [comment]
@Webdongle can you check my solution here: https://github.com/joomla/joomla-cms/pull/5871/files#diff-46853d5c602b247ad0d2954fc28d7510

**Comment by mbabker** [comment]
In theory that would work.  FWIW that code snippet changed here is what I'm
using in my own fork of the media manager without issue.

**Comment by Webdongle** [comment]
@dgt41 does that fix the override issue 

There are too many changes in that for me to replicate on localhost unless I use the patch tester on my local install

**Comment by dgt41** [comment]
@Webdongle Just tested your code with a protostar override and it did work nicely:
screenshot 2015-10-05 18 09 18

All the other changes in the file in my repo is just some CS work

**Comment by Webdongle** [comment]
@dgt41 
@mbabker 

Used patch-tester to pull 5871 to localhost test J3.4.4 ... FULL SUCCESS

Closing my patch

**Comment by dgt41** [comment]
Set to "open" on behalf of @dgt41 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8016">issues.joomla.org/joomla-cms/8016</a>

**Comment by dgt41** [comment]
@Webdongle Can you reopen this as the other PR is set to 3.5 and this can be accepted for the next minor version? In essence it is the same solution 😄

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on eabbf5003274def02b93c3c40a7677856c709c69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8016">issues.joomla.org/joomla-cms/8016</a>.</sub>

**Comment by soap** [comment]
I have tested this item :white_check_mark: successfully on eabbf5003274def02b93c3c40a7677856c709c69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8016">issues.joomla.org/joomla-cms/8016</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8016">issues.joomla.org/joomla-cms/8016</a>.</sub>

**Pull request merged**
