### PR TITLE
Correct return type and add comment

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Corrects return type for `Joomla\CMS\HTML\HTMLHelper::image()`.

### Testing Instructions

Review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0d559a6093aa6d137f736d1f5c85d0ffb43cb448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31245">issues.joomla.org/tracker/joomla-cms/31245</a>.</sub>

**Comment by chmst** [comment]
Why then not return null; instead of return $file on line 587? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31245">issues.joomla.org/tracker/joomla-cms/31245</a>.</sub>

**Comment by SharkyKZ** [comment]
@chmst `$file` is `null` if file is not found. See line 581.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0d559a6093aa6d137f736d1f5c85d0ffb43cb448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31245">issues.joomla.org/tracker/joomla-cms/31245</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31245">issues.joomla.org/tracker/joomla-cms/31245</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
