### PR TITLE
[4.1] Remove old asset code in media manager

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for pr #35863.

### Summary of Changes
This pr removes some not used code which was introduced in version 1.7 over 11 years ago in the media manager. Since the rewrite in version 4, it doesn't work anymore.

Here is the commit
https://github.com/joomla/joomla-cms/commit/f15f514d0c332ec40ee633670a9a2b9aeb322a2a#diff-f552c6c7d57b8a7e01a7b1d6cd2e20de6f8087b6dc0786ce2b3577bb6faca5e5R16

### Testing Instructions
Open the media manager on the front end.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### CODE REVIEW

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on f763316e50eab59e6d626794a9e1e09365e36249<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35886">issues.joomla.org/tracker/joomla-cms/35886</a>.</sub>

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on f763316e50eab59e6d626794a9e1e09365e36249<br /><br />Hello:

"All works" is too generic but it seems to work fine.

Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35886">issues.joomla.org/tracker/joomla-cms/35886</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35886">issues.joomla.org/tracker/joomla-cms/35886</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
