### PR TITLE
Move a subform template out of the form scope, for IE compatibility

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #24832 for Joomla 3.x version
Same as #24944 but for staging.

### Summary of Changes

This fix the subform field in IE, when one of subfield are required.

### Testing Instructions
Please look for related issue for details.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab3b0a496fce809218a84537f28f336bd0ed389d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24947">issues.joomla.org/tracker/joomla-cms/24947</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ab3b0a496fce809218a84537f28f336bd0ed389d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24947">issues.joomla.org/tracker/joomla-cms/24947</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24947">issues.joomla.org/tracker/joomla-cms/24947</a>.</sub>

**Comment by SharkyKZ** [comment]
@Fedik fix conflicts please.

**Comment by okonomiyaki3000** [comment]
The only conflict is in the minified version of the js file. It shouldn't be necessary to have the author of the patch fix that. Ideally the minified file shouldn't even be committed in the first place.

**Comment by Fedik** [comment]
fixed

**Comment by brianteeman** [comment]
@okonomiyaki3000 This is for Joomla 3 and we dont have anything setup to minify files for 3 - only j4

**Comment by HLeithner** [comment]
@Fedik I'm sorry, could you please resolve the conflict again?

**Comment by Fedik** [comment]
fixed

**Comment by HLeithner** [comment]
thx

**Pull request merged**
