### PR TITLE
Add comment about content plugins to view layouts

### PR DESCRIPTION
**Pull request by Bakual**
### Issue

Currently it's not that intuitive to find out where those next/prev and other plugin generated output is coming from.
### Solution

This PR just adds some simple PHP comments into the layouts which state the triggered event responsible for the generated output.
This should make it easier for frontend devs to figure out where to look.
### Testing

Not much you can test here since it only adds PHP comments into the layout. Make sure all com_contact and com_content views are still the same before and after.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4040f6a7b3f155631ed9b99d87123f8248f999cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8517">issues.joomla.org/joomla-cms/8517</a>.</sub>

**Comment by zero-24** [comment]
Maybe this can be implemented only if debug is enabled and not just for com_content? Maybe in the event itself? Or any other generic place? I'm not sure if we hafe a functin thats get called on every plugin event ?

**Comment by Bakual** [comment]
> Maybe this can be implemented only if debug is enabled and not just for com_content?

It's a PHP comment, not a HTML comment. So no output at all. :smile: 
It is meant to indicate in the view layout itself where the content from that property is coming from.

**Comment by alikon** [comment]
tested successfully
it adds more code readabilty so always welcome for me

**Comment by zero-24** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8517">issues.joomla.org/joomla-cms/8517</a>.</sub>

**Comment by pjwiseman** [comment]
I have tested this item :white_check_mark: successfully on 4040f6a7b3f155631ed9b99d87123f8248f999cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8517">issues.joomla.org/joomla-cms/8517</a>.</sub>

**Comment by pjwiseman** [comment]
I have tested this item :white_check_mark: successfully on 4040f6a7b3f155631ed9b99d87123f8248f999cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8517">issues.joomla.org/joomla-cms/8517</a>.</sub>

**Pull request merged**
