### PR TITLE
[com_media] Moved folder list to sidebar

### PR DESCRIPTION
**Pull request by ghost**
First mini-step in getting https://github.com/Buddhima/joomla-cms/tree/new_com_media into core.

Moved the folder list to sidebar
Before:

After:

### CODE REVIEW

**Comment by brianteeman** [comment]
Did you mean to edit all those files?

On 6 August 2015 at 11:31, Peter van Westen <notifications@github.com>
wrote:

> Reopened #7642 <https://github.com/joomla/joomla-cms/pull/7642>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7642#event-375154454>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Ignore that message - it was based on a github mail that showed hundreds of files being changed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7642">issues.joomla.org/joomla-cms/7642</a>.</sub>

**Comment by n9iels** [comment]
@test works fine for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7642">issues.joomla.org/joomla-cms/7642</a>.</sub>

**Comment by sanderpotjer** [comment]
@test works as expected <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7642">issues.joomla.org/joomla-cms/7642</a>.</sub>

**Comment by Bakual** [comment]
Set RTC as we have two good tests. Looks fine to me.

**Pull request merged**
