### PR TITLE
[4.0] Cassiopea table css

### PR DESCRIPTION
**Pull request by pdkpavankumar**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/30715.

### Summary of Changes
fixing hardcoded value to variable value for cassiopea table css

Testing Instructions
go to any article in front end and edit (login as admin)
click on versions
inspect the table (table -> td)

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

table padding should take values from variables $table-cell-padding-sm rather than 8px hardcoded

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by richard67** [comment]
Please provide some testing instructions.

**Comment by pdkpavankumar** [comment]
@bato3

**Comment by pdkpavankumar** [comment]
> Please provide some testing instructions.

added @richard67 its more of css update

**Comment by richard67** [comment]
Thanks.

**Comment by SharkyKZ** [comment]
Remove padding from this file completely.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ed3612b45a7ff9518634bd3e6a589e6b8c170d04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30740">issues.joomla.org/tracker/joomla-cms/30740</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ed3612b45a7ff9518634bd3e6a589e6b8c170d04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30740">issues.joomla.org/tracker/joomla-cms/30740</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30740">issues.joomla.org/tracker/joomla-cms/30740</a>.</sub>

**Comment by infograf768** [comment]
tks.

**Pull request merged**
