### PR TITLE
[4] Missing?

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue https://github.com/joomla/joomla-cms/discussions/32760

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct.
Those files are updated by the build scripts.
So you need to have updated the packages defined in npm in order to have those versions.

Therefore you need to commit the updated package.json and package-lock.json as well

**Comment by astridx** [comment]
package.json and package-lock.json are already updated. For example:

https://github.com/joomla/joomla-cms/blob/c78ef2fb45f68c91d87aa553532dceb4d66478db/package.json#L58

**Comment by brianteeman** [comment]
Look again;)

**Comment by astridx** [comment]
hm, this appeared for me after I ran npm ci. This is probably an error on my part.

**Comment by dgrammatiko** [comment]
@astridx this is a legit PR, can you reopen it?
@richard67 can you merge this on review? (explanation what happed here: we updated the package.json *without* running `npm install` so not all changes were applied)

Ignore me, the current versions are aligned

**Comment by brianteeman** [comment]
@dgrammatiko you are wrong.

As I explained - if you run npm install then it will update these packaged and the xml files. You then have to commit these two xml AND the package.json and package-lock.json

**Pull request closed without merging**
