### PR TITLE
Fix chevron color in module menu assignment

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue # .

### Summary of Changes
The chevron in the Module menu Assignment in light mode is not visible. In dark mode the chevron is visible.

module-light-mode
module-dark-mode

I used the default link color as new color.

### Testing Instructions
- Checkout this PR and build the CSS with: npm run build:css
- Set the template to light mode
- Check if the chevron is visible

### Actual result BEFORE applying this Pull Request
Chevron not visible

### Expected result AFTER applying this Pull Request
Chevron is visible

module-light-mode-fixed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8cc4aafa8d5ff8cd243e8dffa2e72d0c6c695dd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43645">issues.joomla.org/tracker/joomla-cms/43645</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 8cc4aafa8d5ff8cd243e8dffa2e72d0c6c695dd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43645">issues.joomla.org/tracker/joomla-cms/43645</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43645">issues.joomla.org/tracker/joomla-cms/43645</a>.</sub>

**Comment by brianteeman** [comment]
Something sees odd here - the css being changed was only recently added #43160

Did not work then (we need to improve our testing) or has another PR somewhere else changed the behaviour

**Comment by RickR2H** [comment]
PR is closed due to some solution is merged already #43160.

**Comment by brianteeman** [comment]
This PR is needed. 

> Did not work then (we need to improve our testing) or has another PR somewhere else changed the behaviour

**Comment by RickR2H** [comment]
@brianteeman Re-opened

**Comment by RickR2H** [comment]
Was closed before so the successful tests where reset. No code has been changed so added the tests and RTC status again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43645">issues.joomla.org/tracker/joomla-cms/43645</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43645">issues.joomla.org/tracker/joomla-cms/43645</a>.</sub>

**Comment by pe7er** [comment]
Thanks @RickR2H !

**Pull request merged**
