### PR TITLE
[5.1] Fix user field validation on change

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR fixes error validation on a "User" field when a user is selected.

### Testing Instructions

1. Got to `administrator/index.php?option=com_messages&view=messages`
2. Click "New"
3. Focus on the "Recipient" user input field
4. Focus away from the "Recipient" user input field (you'll see a red error message)
5. Select a user

### Actual result BEFORE applying this Pull Request

Field remained red with the error message

### Expected result AFTER applying this Pull Request

Error message is removed and field border turns green

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I wouldn't add another listener into the validate.js.
FWIW you can fix this issue by replacing this
https://github.com/joomla/joomla-cms/blob/4e6d9ea537ddfabdb357650eb3ea7d696cdc95e4/build/media_source/system/js/fields/joomla-field-user.w-c.es6.js#L142-L146

with this:

```js
    dialog.addEventListener('joomla-dialog:close', () => {
      window.removeEventListener('message', msgListener);
      dialog.destroy();
      this.dialog = null;
      this.inputName.focus();
      this.buttonSelect.focus();
    });
```

Basically it's a focus delegation problem...

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 57babeeffcef8a278c16ff495b1d71d47eb1cc07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0dabe825b0c62da183f984478eb3f1bfcecf4c44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0dabe825b0c62da183f984478eb3f1bfcecf4c44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Comment by crimle** [comment]
I have tested this item :red_circle: unsuccessfully on dc0db7f8f3a4099c1713f0eba5c660b52ea9cd63<br /><br />Pressing the button {Apply Patch] results in error message
There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Comment by Nuyonuyonoina** [comment]
"Apply patch" button doesn't worK;

**Comment by eddiekonczal** [comment]
I have tested this item :red_circle: unsuccessfully on dc0db7f8f3a4099c1713f0eba5c660b52ea9cd63<br /><br />When I try to install the patch, I get this error:

"There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42756">issues.joomla.org/tracker/joomla-cms/42756</a>.</sub>

**Comment by richard67** [comment]
@crimle @Nuyonuyonoina @eddiekonczal I will reset your negative test results as they are not caused by this PR. The PR modifies an NPM dependency, which can be seen by the label "NPM Resource Changed". Such PRs can't be tested with Patchtester, they require either a development environment with composer and NPM, or they need to be applied by using the packages created by drone, which can be found in the "Downloads" section of the integration checks at the bottom of the PR.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
