### PR TITLE
JSession Refactor

### PR DESCRIPTION
**Pull request by wilsonge**
This allows JSession to be unit testable and provides an interface similar to that in Symfony to allow injection of sessions into the CMS.

It _should_ be b/c for users however so far all I've been able to do is test stuff with core extensions. If you are doing anything outside of core that uses JSession please do test it or let me know of your application!

### CODE REVIEW

**Comment by anibalsanchez** [comment]
@test OK

In an OAuth2 authorization workflow, internal information is saved in JSession. User leaves the site and after the external authorization step, the information is retrieved from JSession to complete the auth token retrieval.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5088">issues.joomla.org/joomla-cms/5088</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing by @anibalsanchez and @compojoom Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5088">issues.joomla.org/joomla-cms/5088</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge can you update the `@since` and copyright dates bevor committing?

**Comment by mbabker** [comment]
So, as an additional validation on this PR, using the new `JSessionHandlerNative` class, I am able to get sessions working on PHP 7 (see #7143 for more).  With the `JSessionHandlerJoomla` class, we get nowhere.  So :+1: on this.

**Comment by mbabker** [comment]
Merged to `3.5-dev` via https://github.com/joomla/joomla-cms/commit/e36e879bc387ee21059258ac9db05b2d44a2426c

**Pull request closed without merging**
