### PR TITLE
Wrong comment in file

### PR DESCRIPTION
**Pull request by Kaushik1216**
Pull Request for Issue # .
Corrected wrong comment in code 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eb0842c1cfc93bb842e497a093df95dc913cc0e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39812">issues.joomla.org/tracker/joomla-cms/39812</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on eb0842c1cfc93bb842e497a093df95dc913cc0e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39812">issues.joomla.org/tracker/joomla-cms/39812</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39812">issues.joomla.org/tracker/joomla-cms/39812</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by Kaushik1216** [comment]
Thanks to @Quy and @ChristineWk to check this pr and @wilsonge to merge

**Pull request merged**
