### PR TITLE
[4.0] calendar cellpading

### PR DESCRIPTION
**Pull request by brianteeman**
Kills the deprecated (and useless) cellpadding and cellspacing.

There should be no visual impact on the calendar

Testing requires npm i

### CODE REVIEW

**Comment by Shubham-com** [comment]
I have tested this item :white_check_mark: successfully on d29649629bfb044bf7689d4ecef0ac6ad226afc9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33505">issues.joomla.org/tracker/joomla-cms/33505</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d29649629bfb044bf7689d4ecef0ac6ad226afc9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33505">issues.joomla.org/tracker/joomla-cms/33505</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33505">issues.joomla.org/tracker/joomla-cms/33505</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you update the branch of this PR to latest 4.0-dev so it gets the change from #33507 ? Without that, appveyor fails, and so merging of this PR requires more privileges than I and most other maintainers have. I will restore test results after that, so no need for re-test.

**Comment by brianteeman** [comment]
@richard67 I wont be able to do it today as I am in the studio filming but you can do this for me

**Comment by richard67** [comment]
@brianteeman Ok, will do later if no forced merge before. I wish you success with filming.

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
