### PR TITLE
[4.0] namespace JText

### PR DESCRIPTION
**Pull request by brianteeman**
Fix some missing namespace changes or JText

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fc204290b861e0aa076058dfca00f3bbea40f503<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27364">issues.joomla.org/tracker/joomla-cms/27364</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc204290b861e0aa076058dfca00f3bbea40f503<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27364">issues.joomla.org/tracker/joomla-cms/27364</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27364">issues.joomla.org/tracker/joomla-cms/27364</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
