### PR TITLE
[4.0]Mail component behaviours

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to remove two behaviors that are not being used

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b52b5bcd94f5c7159c5d50926923275ebe024bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26474">issues.joomla.org/tracker/joomla-cms/26474</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 5b52b5bcd94f5c7159c5d50926923275ebe024bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26474">issues.joomla.org/tracker/joomla-cms/26474</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26474">issues.joomla.org/tracker/joomla-cms/26474</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
