### PR TITLE
[4.0] Sample data fix wrapper

### LINKED ISSUE #17404: [4.0] Sample Sites: Wrapper-Module to width
### Steps to reproduce the issue
Comparing Screenshots below shows Wrapper-Module to width:
bildschirmfoto 2017-08-04 um 09 33 41
bildschirmfoto 2017-08-04 um 09 34 04

### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

### PR DESCRIPTION
**Pull request by brianteeman**
Update the sample data to use width 100% for the wrapper to fix #17404

### CODE REVIEW

**Review by C-Lodder — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d3887cf3fca5255b46d5e11f52ce15c36115b9a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17424">issues.joomla.org/tracker/joomla-cms/17424</a>.</sub>

**Comment by Bakual** [comment]
Given the merge of the Sample Data module/plugin into 3.8, the Sample Data installer and the respective SQL files will likely be removed from 4.0. So this is probably not worth pursuing anymore 😄

**Comment by brianteeman** [comment]
This Ims for the testing data and not the end user sample data

**Comment by Bakual** [comment]
Same thing. Testing data is a plugin as well in 3.8.

**Comment by infograf768** [comment]
I guess this can be closed.

**Comment by brianteeman** [comment]
As the "plugin" has not yet been merged into j4 (and judging on the current conversations it will be a while before it is merged) please merge it @wilsonge

**Comment by mbabker** [comment]
Until we reach a state where the workflow has changed, the status quo is still in effect so we might as well keep fixing things.  Worst thing we do is waste 2-3 minutes of someone's time, but we really don't want to push away legitimate fixes because something may be replaced later.

**Comment by C-Lodder** [comment]
Why was the plugin for sample data was put in 3.8 and not 4?

Considering a lot of sample data has been changed for 4 and there's still a load to come, I can't see any logic in it being in 3.8

**Comment by mbabker** [comment]
The module/plugin stuff is just architecture.  And the existing sets converted to demonstrate that architecture.  For 4.0 you'll just implement your own plugin with the same data set.

**Comment by brianteeman** [comment]
So please can we merge this into 4 now even if it may be removed later

**Comment by brianteeman** [comment]
Thank you

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/17434 for the respective change in the plugin.

**Pull request merged**
