### PR TITLE
CLI extensions installer

### PR DESCRIPTION
**Pull request by nikosdion**
# Executive summary

This PR introduces a command-line interface (CLI) extensions installer. This allows automation of extension installation (new installs and updates) using command line tools. It can be used on various scenarios including, but not limited to, virtual machine provisioning (see Vagrant), automated tests for extension integration, mass updates of hundreds of sites in a hosting environment and so on. The script in this PR offers an equivalent to all of the installation methods allowed by the Extensions Manager in the back-end of your Joomla! site.
# Testing instructions

For testing purposes we are going to install the same dummy extension in several ways. After each installation please check that the extension is installed on your site. Then remove it and test the next method. There are eight tests in total, including the short and long command versions. _Important_: Being familiar with the command line environment is necessary, given the nature of this PR.
## Using an XML update stream (equivalent to Install from Web)

Run this script as
`php /path/to/site/cli/install-extension.php -w "http://akeebatest.s3.amazonaws.com/dummy/update.xml"`
Also try the long command version
`php /path/to/site/cli/install-extension.php --web="http://akeebatest.s3.amazonaws.com/dummy/update.xml"`
## Using an extension package URL (equivalent to Install from URL)

Run this script as
`php /path/to/site/cli/install-extension.php -u "http://akeebatest.s3.amazonaws.com/dummy/com_dummy-1.2.0.a1.zip"`
Also try the long command version
`php /path/to/site/cli/install-extension.php --url="http://akeebatest.s3.amazonaws.com/dummy/com_dummy-1.2.0.a1.zip"`
## Using a local extension package (equivalent to Install from Package File)

Download the [installation package](http://akeebatest.s3.amazonaws.com/dummy/com_dummy-1.2.0.a1.zip) into a directory, let's call it `/foo/bar`. DO NOT extract it! Now run
`php /path/to/site/cli/install-extension.php -p "/foo/bar/com_dummy-1.2.0.a1.zip"`
Also try the long command version
`php /path/to/site/cli/install-extension.php --package="/foo/bar/com_dummy-1.2.0.a1.zip"`
## Using a local directory (equivalent to Install from Directory)

Download the [installation package](http://akeebatest.s3.amazonaws.com/dummy/com_dummy-1.2.0.a1.zip) AND extract it into a directory, let's call it `/foo/bar`. Now run
`php /path/to/site/cli/install-extension.php -f "/foo/bar/com_dummy-1.2.0.a1.zip"`
Also try the long command version
`php /path/to/site/cli/install-extension.php --folder="/foo/bar/com_dummy-1.2.0.a1.zip"`
# Backwards compatibility

No b/c issues are present. This is a new CLI script which doesn't interfere with existing functionality.
# Translation impact

One new translation file added (language/en-GB/en-GB.cli_install_extension.ini) with 22 language strings. Expected translation impact: about 8 minutes.
# Credits and acknowledgments

This PR is inspired by the CLI extension installation scripts written by [Nicola Galgano](https://github.com/alikon/joomla-platform-examples/blob/master/Joomla%20CLI%20App/cli/jeicli.php) and [yours truly](https://github.com/akeeba/vagrant/blob/master/vagrant/files/joomla/install-joomla-extension.php). It seems that many of us are reinventing the same small but very convenient wheel.

### CODE REVIEW

**Comment by waader** [comment]
Testing the installation of com_dummy-1.2.0.a1.zip and other components using the different methods went fine.

But I got one problem with the installation of acymailing (com_acymailing_starter_v4.8.1_2015-01-05_13-19-06.zip). Doing this

php install-extension.php -f "c:\com_acymailing_starter_v4.8.1_2015-01-05_13-19-06.zip"

gives the following fatal error:  Call to undefined method JoomlaExtensionInstallerCli::isAdmin() in .... joomla34\administrator\components\com_acymailing\helper\helper.php on line 863.

On the other hand: the installation is successful in the backend.

Can somebody more knowledgeable assess this error?

**Comment by wilsonge** [comment]
It means they expect an instance of ```JApplicationCms``` when you call ```JFactory::getApplication()``` which contains that function (https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/cms.php#L663). What we actually have is the cli application instance (https://github.com/joomla/joomla-cms/pull/5460/files#diff-f85f920df9966deeeae69694208c8acdR441) so it fatals. Nic this one is one for you to work out a solution for I guess.

**Comment by nikosdion** [comment]
Technically, this is an architectural issue. I can work around it by adding a dummy method in the CLI script’s class. Is that an acceptable solution?=

**Comment by wilsonge** [comment]
How far would this run though. I'm thinking logically the 3 methods that people would likely use in an install script are ```isSite```, ```isAdmin``` and ```enqeueMessage```. I mean I know technically it could be anything. But I'd imagine these 3 would regularly appear

**Comment by waader** [comment]
Meanwhile I tested with Kunena 3.0.6 which gives me another fatal error:
Call to undefined method JoomlaExtensionInstallerCli:getRouter() in ... \joomla34\libraries\joomla\application\route.php on line 47

**Comment by nikosdion** [comment]
I guess we have to deal with this issue architecturally instead of going through a patchwork of workarounds. Having an application interface which really includes all methods developers expect an application object to have and refactoring JApplicationCli / JApplicationWeb is the only way to realistically go forward :(=

**Comment by mbabker** [comment]
I was just typing something similar; an interface will definitely help here.

**Comment by nikosdion** [comment]
I guess that this would have to wait for Joomla! 3.5 (I can see a probability for b/c issues there) and, as a result, the CLI extensions installer would also need to wait until then.=

**Comment by infograf768** [comment]
@nikosdion
Shall we consider this PR as postponed to 3.5?
I need to be sure as I would have to upgrade com_localise for this new ini.

**Comment by brianteeman** [comment]
It would be a real shame if it was delayed

**Comment by nikosdion** [comment]
Yes, it has to be delayed. There’s no point shipping broken code just to make it through the 3.4 deadline. We need to deal with the JApplication* classes’ architecture before we can include the CLI extensions installer script.

Of course, if you want to use it on your sites you still can: just check out the file and put it in your site’s cli directory. The script is self-contained. I just can’t vouch it will work with any extension as you can read in this issue thread.=

**Comment by brianteeman** [comment]
:(

On 6 January 2015 at 10:08, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> Yes, it has to be delayed. There’s no point shipping broken code just to
> make it through the 3.4 deadline. We need to deal with the JApplication*
> classes’ architecture before we can include the CLI extensions installer
> script.
>
> Of course, if you want to use it on your sites you still can: just check
> out the file and put it in your site’s cli directory. The script is
> self-contained. I just can’t vouch it will work with any extension as you
> can read in this issue thread.=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5460#issuecomment-68847496>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nikosdion** [comment]
Closing this PR as it requires a major core refactor which can't happen before Joomla! 4.0.

**Comment by wilsonge** [comment]
@marcodings You should review for Joomla 4

**Comment by wilsonge** [comment]
I've added the label Re-evaluate for Joomla 4 as well

**Pull request closed without merging**
