### PR TITLE
Add width and height attributes for modal window

### PR DESCRIPTION
**Pull request by ryandemmer**
Add width and height attributes for the modal window with defaults set to the original values of 800 x 500

### CODE REVIEW

**Comment by n9iels** [comment]
Can you please add some test instructions so we can test this feature

**Comment by zero-24** [comment]
@n9iels 

### simple testing

1) BE --> Content --> Article --> New Article
2) 'Images & Links' Tab
3) klick on `select` for the intro image
4) see the pop up.
5) apply the patch
6) repeat 1 to 4 again
7) see it is still the same popup

### Advanced testing

1) Step 1-7
2) go to \administrator\components\com_content\models\forms\article.xml arround Line 618
3) replace this:
```xml
<field
	name="image_intro"
	type="media"
	label="COM_CONTENT_FIELD_INTRO_LABEL"
	description="COM_CONTENT_FIELD_INTRO_DESC" />
```

with
```xml
<field
	name="image_intro"
	type="media"
	height="200"
	width="200"
	label="COM_CONTENT_FIELD_INTRO_LABEL"
	description="COM_CONTENT_FIELD_INTRO_DESC" />
```
4) try the same button again
5) see the new higth and width styled pop up.

I have just tested both ways successful. Thanks @ryandemmer <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7817">issues.joomla.org/joomla-cms/7817</a>.</sub>

**Comment by MAT978** [comment]
**Success** as able to confirm both *simple testing* and *Advanced testing*

Thanks @ryandemmer & Tobias<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7817">issues.joomla.org/joomla-cms/7817</a>.</sub>

**Comment by zero-24** [comment]
Thanks! RTC based on testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7817">issues.joomla.org/joomla-cms/7817</a>.</sub>

**Comment by rdeutz** [comment]
new function because some can set the width and the height of the iframe

**Comment by roland-d** [comment]
Thanks @ryandemmer Merged with commit 8c276e into 3.5-dev.

**Pull request closed without merging**
