### PR TITLE
parse preprocess rules from component routers

### PR DESCRIPTION
**Pull request by alexva24**
The component's parse preprocess rules added to router

### CODE REVIEW

**Comment by wojsmol** [comment]
@alexva24 see https://github.com/alexva24/joomla-cms/pull/1

**Comment by brianteeman** [comment]
Please provide a detailed explanation of the aim of this Pull Request and how it can be tested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8801">issues.joomla.org/joomla-cms/8801</a>.</sub>

**Comment by alexva24** [comment]
The aim of this PR is providing possibility to execute custom component's parse preprocess rules instead develop onAfterInitialise plugin.

For testing you should create parsepreprocess method on router of any installed components. The method will be executed on 593 line /libraries/cms/router/router.php

**Comment by alexva24** [comment]
Reopen request

**Comment by brianteeman** [comment]
Looks like you have deleted your branch with the pull request<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8801">issues.joomla.org/joomla-cms/8801</a>.</sub>

**Comment by wojsmol** [comment]
New PR by @alexva24 https://github.com/joomla/joomla-cms/pull/8986

**Pull request closed without merging**
