### PR TITLE
[4.0] Expand all

### PR DESCRIPTION
**Pull request by brianteeman**
Following the styleguide https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html this should be Expand All

image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 84f42b8c6f716f5900a75c4e61ac7461fd699827<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34416">issues.joomla.org/tracker/joomla-cms/34416</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 84f42b8c6f716f5900a75c4e61ac7461fd699827<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34416">issues.joomla.org/tracker/joomla-cms/34416</a>.</sub>

**Comment by rjharishabh** [comment]
@brianteeman Is `Collapse all` correct, if not then, please change it also

**Comment by richard67** [comment]
> @brianteeman Is `Collapse all` correct, if not then, please change it also

Agree. See here: https://github.com/joomla/joomla-cms/blob/84f42b8c6f716f5900a75c4e61ac7461fd699827/administrator/language/en-GB/com_finder.ini#L73

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 6879a2c4ae01f43e1da5249de47bdc56bb7a263f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34416">issues.joomla.org/tracker/joomla-cms/34416</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks all - small steps

**Pull request merged**
