### PR TITLE
Added wildcard option to com_finder

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue #35861 

### Summary of Changes
By default Smart Search searches form the start of the word. This PR adds the option to search for a phrase in the middle of a word.

### Testing Instructions
Checkout this PR
Create a menu item with menu item type Smart Search -> Search
Go to Components -> Smart Search -> Index
Open the options and set the Wildcard option in the tab "Smart Search" to On

Image 8

Create an article with some long words
Go to Components -> Smart Search -> Index and start the indexer
In the frontend search for a phrase in the middle of the word

### Actual result BEFORE applying this Pull Request
No search results as search terms have to start from the beginnen of a word.

Image 9

### Expected result AFTER applying this Pull Request
Search phrase in the middle of a word is found.

Image 7

### Documentation Changes Required
Yes

### CODE REVIEW

**Comment by brianteeman** [comment]
I believe this is wrong for the reasons I commented in the original issue. Plus if you enable % at the start it should also be enabled at the end.

**Comment by RickR2H** [comment]
The % is enabled at the end by default.

**Comment by RickR2H** [comment]
> I believe this is wrong for the reasons I commented in the original issue. Plus if you enable % at the start it should also be enabled at the end.

By default the option is disabled!

**Comment by brianteeman** [comment]
https://docs.joomla.org/Smart_Search_Frequently_Asked_Questions#Why_are_wildcard_searches_not_supported.3F

**Comment by MSnoeren** [comment]
I think this feature is very useful when searching in a content-rich Joomla website. The option is disabled by default, so existing websites won't be affected. Maybe add a notice to inform website administrators of the slower query?

**Comment by brianteeman** [comment]
just use com_search then

**Comment by RickR2H** [comment]
Closing PR because of wildcard search was left out by design en for reasons stated in the documentation

**Pull request closed without merging**
