### PR TITLE
Find favicon

### LINKED ISSUE #6077: favicon.ico incorrect url Apache windows server
libraries\joomla\document\html\html.php on line 593:
$path = str_replace(JPATH_BASE . '/', '', $dir);
to:
$path = str_replace(JPATH_BASE . '\\\', '', $dir);

### PR DESCRIPTION
**Pull request by sovainfo**
Fixes #6077 
Without introducing yet another DIRECTORY_SEPARATOR !

### CODE REVIEW

**Comment by infograf768** [comment]
@test
This still works here on Macintosh. No idea on Windows.

**Comment by imanickam** [comment]
I have tested this in a Windows 7 64 bit environment and it looks like there still some issues.  Following is the summary of the test results.

Scenerio 1 - favicon.ico present in the template's folder: CORRECT
 <link href="/joomla_34_b3/templates/protostar/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

Scenerio 2 - favicon.ico NOT present in the template's folder and favicon.ico NOT present in the site's root folder: CORRECT
 No statement created for favicon.ico

Scenerio 3 - favicon.ico NOT present in the template's folder and favicon.ico is present in the site's root directory: WRONG
 <link href="/joomla_34_b3C:/wamp/www/joomla_34_b3/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

Hope this helps...

**Comment by infograf768** [comment]
Correcting my test;
Indeed, if favicon in root: no show.

**Comment by infograf768** [comment]
If I take off
//$path = JPath::clean($path, '/');
then it is OK here (Macintosh)

**Comment by imanickam** [comment]
With the line (specified by infograf768) commented, all three scenarios wok fine.

**Comment by sovainfo** [comment]
@infograf768, @imanickam Thanks for testing. Below my Findings:
Findings:
Fuctionality: Provide a favicon in the browser. Active template overrides application.

Implementation: <link href="/j3x/j340b3/administrator/templates/isis/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

Infra: W8.1 (32) XAMPP 1.8.1 (A: 2.4.3, M: 5.5.27, P: 5.4.7)

Environment: J336 on MySQL with Learning demo data
Result Favicon FE/BE        Favicon location
+       V       backend     template
+       V       backend     administrator
+       X       backend     joomla root
+       X       backend     document root
+       V       frontend    template
+       V       frontend    joomla root
+       X       frontend    document root

Environment: J340b3 on MySQL with Learning demo data
Result Favicon FE/BE        Favicon location
-       X       backend     template
+       V       backend     administrator
+       X       backend     joomla root
+       X       backend     document root
-       X       frontend    template
+       V       frontend    joomla root
+       X       frontend    document root

Environment: J340b3 on MySQL with Learning demo data
    with PR manually applied
Result Favicon FE/BE        Favicon location    Comment
+       V       backend     template
-       X       backend     administrator       Filepath in url
+       X       backend     joomla root         No icon link
+       X       backend     document root       No icon link
+       V       frontend    template
-       X       frontend    joomla root         Filepath in url
+       X       frontend    document root       No icon link

Environment:J340b3 on MySQL with Learning demo data
    with PR manually applied, but reverted suggestion mbabker to use JPATH::clean
Result Favicon FE/BE        Favicon location    Comment
+       V       backend     template
+       V       backend     administrator
+       X       backend     joomla root         No icon link
+       X       backend     document root       No icon link
+       V       frontend    template
+       V       frontend    joomla root
+       X       frontend    document root       No icon link

Based on these findings will revert the suggestion of mbabker to use JPATH::clean and request testing again.

**Comment by infograf768** [comment]
@test
Works on UNIX/Macintosh

**Comment by waader** [comment]
@test works on windows! Thanks!

**Comment by infograf768** [comment]
Merging. Thanks.

**Comment by sovainfo** [comment]
Thank you all for testing and merging!

**Pull request merged**
