### PR TITLE
Module navigation menu title equal to parent menu item title

### PR DESCRIPTION
**Pull request by ggeorgg**
Pull Request for Issue # .
#9692
#### Summary of Changes

Added possibility to name displayed name of the modul after the current parent menu item.
At the moment it only works when html5 is chosen as menu style.
#### Testing Instructions

Create a menu like:
- Menu A (alias: menu_a)
- Menu B (alias: menu_b)
- \- Sub Menu B1 (alias: submenu_b1)
- -- Sub Sub Menu B11 (alias: submenu_b11)
- -- Sub Sub Menu B12 (alias: submenu_b12)
- \- Sub Menu B2 (alias: submenu_b2)
- -- Sub Sub Menu B21 (alias: submenu_b21)
- -- Sub Sub Menu B22 (alias: submenu_b22)
- \- Sub Menu B3 (alias: submenu_b3)
- -- Sub Sub Menu B31 (alias: submenu_b31)
- -- Sub Sub Menu B32 (alias: submenu_b32)

Create a menu modul, change the modul style to html5, set the modul active and choose a position on your webpage.
Base entry = current
Choose first stage = 3
Set "Use parent menu entry as modulname" to true

### CODE REVIEW

**Comment by wojsmol** [comment]
@ggeorgg see https://github.com/ggeorgg/joomla-cms/pull/1

**Comment by bembelimen** [comment]
I don't like the idea, that you add code for a specific module in a general approach like a module chrome. Especially you load the parent menu item regardless if you have a parent id or if you have another module type loaded...

If you need this function, just create your own module chrome in your own project.

**Comment by brianteeman** [comment]
This really isnt a good solution to go into the core of Joomla as there is no way to know what module chrome is being used by a template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9705">issues.joomla.org/joomla-cms/9705</a>.</sub>

**Comment by ggeorgg** [comment]
Ok, thanks for your comments! 
Maybe I will try to implement a modul which can do this. (I am quite new to this and I have never done this before, but I think it can't be too hard)

**Pull request closed without merging**
