### PR TITLE
sql - support for scss,sass source formats

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #10186 .

### Summary of Changes
added sql for https://github.com/joomla/joomla-cms/pull/10186#issuecomment-257952879

### CODE REVIEW

**Comment by zero-24** [comment]
We need to revert the update part as it would overwrite the current settings by the site owners.

**Comment by mbabker** [comment]
This overwrites the entire component parameters.  Not sure that's a good idea...

**Comment by zero-24** [comment]
@mbabker we just need to revert the update part the install part is correct ;) or do i miss something?

**Comment by mbabker** [comment]
If you want to add the values during the update, it can't be a full replacement of the parameters column like it is now.  If you choose not to add the values then just removing the update SQLs is fine.

**Comment by C-Lodder** [comment]
Won't the updates need to be done in `administrator\components\com_admin\script.php`?

**Comment by alikon** [comment]
lets'go  only with install for now , the full update of the param field as noticed was a really bad idea

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 4edd94df2b65621018065d922348ba45d2cc53da<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12712">issues.joomla.org/tracker/joomla-cms/12712</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 4edd94df2b65621018065d922348ba45d2cc53da<br /><br />I do hope the update side of things isn't forgotten about though<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12712">issues.joomla.org/tracker/joomla-cms/12712</a>.</sub>

**Comment by alikon** [comment]
i'm thinking something about this  update query:

```sql
UPDATE params = 
        replace(params,'"source_formats":"','"source_formats":"scss,sass,')
  FROM #__extensions
where extension_id =20;`

what do you think?

**Comment by zero-24** [comment]
Thanks!

**Comment by alikon** [comment]
@C-Lodder not forgotten please test/comment #12727

**Pull request merged**
