### PR TITLE
Code Style - contact - default_links.php

### PR DESCRIPTION
**Pull request by LLNet**
- html 
- php
- optimized code so we not open and close php for fun.

### CODE REVIEW

**Comment by brianteeman** [comment]
@javigomez Can you comment on the code style please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4829">issues.joomla.org/joomla-cms/4829</a>.</sub>

**Comment by brianteeman** [comment]
@javigomez waiting on you to comment before this can be either closed or moved forward<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4829">issues.joomla.org/joomla-cms/4829</a>.</sub>

**Comment by zero-24** [comment]
hmm for my personal view we should use

```php
<?php if (whatever) : ?>
<?php // Do what ever you want to do ?>
<?php endif; ?>
```

It is most smaler code and easier to read in views. As there should be majority HTML Code. ;) For models and other stuff like classes etc. I agree with:

```php
<?php if (whatever)
{
 // Do what ever you want to do
}
```

In the last time we merge a lot of the first type of code. But the PLT needs to take that if we want to change all the files again :smile:

**Comment by Bakual** [comment]
In layout files, we use
````
<?php if (whatever) : ?>
<?php // Do what ever you want to do ?>
<?php endif; ?>`
````
Except in the first PHP block at the very beginning of the file. There we usually use
````
<?php if (whatever)
{
 // Do what ever you want to do
}
````

Reason is that the first variant is supposed to be easier to understand by frontend guys and regular users. You can also easier move blocks around without creating fatal errors due to missing <?php ... ?> tags and the like.

So this PR doesn't follow our codestyle for the most part.

I'm closing it.

**Pull request closed without merging**
