### PR TITLE
[4.2] pre-update check missing class

### PR DESCRIPTION
**Pull request by brianteeman**
The checkbox is not displayed correctly

```
<input type="checkbox" class=" me-3" id="noncoreplugins" name="noncoreplugins" value="1" required />
```

Should be changed to

```
<input type="checkbox" class="form-check-input me-3" id="noncoreplugins" name="noncoreplugins" value="1" required />
```

### before
image

### after
image

### CODE REVIEW

**Comment by brianteeman** [comment]
could someone restart drone please

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 03b60f1b958a92040e45eb26fe9e999561ff83cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38074">issues.joomla.org/tracker/joomla-cms/38074</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 03b60f1b958a92040e45eb26fe9e999561ff83cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38074">issues.joomla.org/tracker/joomla-cms/38074</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38074">issues.joomla.org/tracker/joomla-cms/38074</a>.</sub>

**Comment by richard67** [comment]
I could post a 3rd good tests since I've just tested with success (before I've noticed it is already RTC) 😄 For testing I have created a fake update site for a 4.3-dev release so the pre-update checker is shown.

**Comment by richard67** [comment]
Thanks all.

**Pull request merged**
