### PR TITLE
[4.0] [com_newsfeeds] Parameterized queries (backend)

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds parameterized queries and cleans up SQL in `com_newsfeeds` backend part.

### Testing Instructions

Go to `com_newsfeeds` in backend.
Create some newsfeeds.
Search, filter and order newsfeeds.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fcdb83499d453159d6bcbcfe74fb17125b549851<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27220">issues.joomla.org/tracker/joomla-cms/27220</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0436d4a6dd8d48c7c106da1dd9ea653b65ab9825<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27220">issues.joomla.org/tracker/joomla-cms/27220</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27220">issues.joomla.org/tracker/joomla-cms/27220</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
