### PR TITLE
Don't include autoloaded files in tests

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

The test environment boots up the autoloader, so there is no need to include autoloaded files in the test classes.  Remove extraneous include/require statements.
### Testing Instructions

Unit tests pass, merge this.
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by rdeutz** [comment]
I have tested this item :white_check_mark: successfully on 79e63599711df87744ed57216849bf05ca0db544<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11693">issues.joomla.org/joomla-cms/11693</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 79e63599711df87744ed57216849bf05ca0db544<br /><br />united tests passed.
"merge this" :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11693">issues.joomla.org/joomla-cms/11693</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 79e63599711df87744ed57216849bf05ca0db544<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11693">issues.joomla.org/joomla-cms/11693</a>.</sub>

**Comment by dgt41** [comment]
RTC @rdeutz go on and hit that button

**Pull request merged**
