### PR TITLE
[3.9][com_content featured] Remove redundant intro_image check

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
- Remove lines for check if intro image exists because this is done in JLayout already.

### Testing Instructions
Code review in pr plus code of JLayout `joomla.content.intro_image` https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/intro_image.php#L14

Or:
- Create some featured articles with and without intro images.
- Test that nothing has changed after applying the patch. Intro images are displayed or not.

### Expected result
- Nothing has changed.

### Actual result
- Unnecessary/redundant code.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 6a91da1e7d805bae8cc240e90e3c8dff285488a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24389">issues.joomla.org/tracker/joomla-cms/24389</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0e997163170d1a4d00aa5bedbedd301068da1ac8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24389">issues.joomla.org/tracker/joomla-cms/24389</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24389">issues.joomla.org/tracker/joomla-cms/24389</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
