### PR TITLE
Ignore block user

### PR DESCRIPTION
**Pull request by saharin88**
Ignore records created by blocked users.

### CODE REVIEW

**Comment by mbabker** [comment]
Arbitrarily not loading categories from the tree because a user account is blocked seems wrong.

**Comment by saharin88** [comment]
> Arbitrarily not loading categories from the tree because a user account is blocked seems wrong.

Мore precisely, do not count records (in category) from blocked users*
This change is probably more related to the public part of the site. For example, a category module.

**Comment by alikon** [comment]
or at least quite debatable, imho, can you describe a real use case scenario for this ?

**Comment by saharin88** [comment]
> or at least quite debatable, imho, can you describe a real use case scenario for this ?

Any Counter of materials of a category, whether it is a module of a category or something else - a custom code (extends Joomla\CMS\Categories\Categories)

**Comment by mbabker** [comment]
Then implement the logic in your subclass instead of arbitrarily changing the entirety of core.  This really comes across as a total edge case that should be dealt with in that specific implementation.

Imagine if menu items or articles or modules started disappearing because you blocked the user account that "owns" the item.

**Comment by HLeithner** [comment]
Thanks @saharin88 for your PR but I see this as michael, it's an edge case. You can solve this by setting a special viewlevel if a user is blocked per batch processing for articles.

I'm closing this.

**Comment by saharin88** [comment]
> Thanks @saharin88 for your PR but I see this as michael, it's an edge case. You can solve this by setting a special viewlevel if a user is blocked per batch processing for articles.
> 
> I'm closing this.

Ок

**Pull request closed without merging**
