### PR TITLE
[4.0] Append Field to the form field class names

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #16568.

### Summary of Changes
The form fields must end with `Field` in J4.

### Testing Instructions
- Create a new category
- Edit an article
- Change the category in the article edit view

### Expected result
The select box is filled.

### Actual result
A Javascript error is thrown and the select box to change the category is empty.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2f1e89862b3f7a559cc9a5d67b12fce766e54ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16580">issues.joomla.org/tracker/joomla-cms/16580</a>.</sub>

**Comment by Bakual** [comment]
Why is that suddently needed? Afair the fields were working fine about a week ago. What about all the other formfields? Do they need a namechange as well?
And how will this work for extension which are supposed to run in J3.9 and J4?

**Comment by laoneo** [comment]
We have only this fields here, no other fields are namespaced till now. It affects only the namespaced fields the rest stays as it is. No changes.

**Comment by laoneo** [comment]
The change with appending `Field` to the name came with #16396.

**Comment by Bakual** [comment]
Do we really need that suffix? Looks a bit strange to me to require such a suffx when the class is namespaced (namespace already makes clear it's a field).

**Comment by laoneo** [comment]
Rules do also end with `Rule` or with `Form`. Also it can cause problems with reserved words in PHP 7 and I personally like to have clear class names. But we can now discuss up and down if we should add `Field` to the class name or not. At the end it is just personal preferences.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4bc79fba07c977d0594721483125c97846fe1aed<br /><br />Confirming that this PR fixed the reported problem - not commenting on the issue raised by @bakual<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16580">issues.joomla.org/tracker/joomla-cms/16580</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4bc79fba07c977d0594721483125c97846fe1aed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16580">issues.joomla.org/tracker/joomla-cms/16580</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Just to follow up on @laoneo 's comment. For example take the integer form field. With namespacing this will end up having a class of Integer which is reserved in PHP7. Giving it a name of IntegerField (which corresponds to the integer in the XML) by suffixing the classname of namespaced class with the entity type here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Form/FormHelper.php#L185

I'm going to merge this as is. @Bakual if you want to open a discussion about this I'm open to that but let's do that in a fresh issue and get this form field working :)

**Pull request merged**
