### PR TITLE
[4.0] Smart Search - Search Terms

### PR DESCRIPTION
**Pull request by brianteeman**
There are a few components that will give a warning message if a required plugin is not enabled AND the message includes a link directly to the plugin.

Smart Search -> Search Terms has a requirement for a specific option in the component to be enabled. This PR updates the message to provide a link to the options.

image

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 54933f90b002d1f77f5f1ed3158e72d07c811f51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32251">issues.joomla.org/tracker/joomla-cms/32251</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54933f90b002d1f77f5f1ed3158e72d07c811f51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32251">issues.joomla.org/tracker/joomla-cms/32251</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32251">issues.joomla.org/tracker/joomla-cms/32251</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
