### PR TITLE
[4.0] codemirror height

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #30955 .

### Summary of Changes
Port #13266 to Joomla 4

On larger screens, CodeMirror height seems small (300px) compared to the space available.

### This PR...

Gives Codemirror a fluid height, increasing the working space when available.
Keeps a min-height of 400px
Ensures space remains above the fold for appending buttons (article edit)

### Testing Instructions
Apply PR and open CodeMirror (template file edit, article edit)

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cb1a38ac79cb64a046c351809d182c9f789e7b27<br /><br />Set in Global Options Editor: Codemirror. Test on Template file, Article, Custom Module.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30990">issues.joomla.org/tracker/joomla-cms/30990</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cb1a38ac79cb64a046c351809d182c9f789e7b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30990">issues.joomla.org/tracker/joomla-cms/30990</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30990">issues.joomla.org/tracker/joomla-cms/30990</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
