### PR TITLE
Update/reorder language strings

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
* Remove space
* Change text to match similar verbiage
* Reorder strings

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 26478ffa73bc7af2b02bc9038a4a2948ca6d1e52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15103">issues.joomla.org/tracker/joomla-cms/15103</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 26478ffa73bc7af2b02bc9038a4a2948ca6d1e52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15103">issues.joomla.org/tracker/joomla-cms/15103</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15103">issues.joomla.org/tracker/joomla-cms/15103</a>.</sub>

**Comment by brianteeman** [comment]
@bakual @infograf768 are the admin and site en-GB.ini files supposed to be identical? I forget

**Comment by Bakual** [comment]
I don't think so. Only the lib one needs to be in sync.

**Comment by brianteeman** [comment]
I knew there was one just didnt remember which :)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1354b15f5e5555af2f869cbf195b2b6b6ffd4568<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15103">issues.joomla.org/tracker/joomla-cms/15103</a>.</sub>

**Comment by infograf768** [comment]
I can't set the milestone. This has to go into RC1.

**Pull request merged**
