### PR TITLE
Made default language parameter from setDefault equal to getDefault

### PR DESCRIPTION
**Pull request by bembelimen**
.

### CODE REVIEW

**Comment by Hackwar** [comment]
@test This is a correct fix.

**Comment by jacxx** [comment]
@Test, I have tested the fix and work. Jacxx :)

**Comment by wilsonge** [comment]
I can't imagine how setting the default home page item gets set outside of menu manager. But indeed it seems correct to use the same standardisation here as we have for the default value in com_menu's itself

**Comment by Hackwar** [comment]
There are several reasons to set the default home page. For example, I had to write a plugin that made a menu item the default page when the user first opened the page via some landing page. Remember that this is not set permanently, but only sets the default page in JMenu for the duration of the pageload.

**Comment by bembelimen** [comment]
Yep, I wrote a multi domain plugin (that's the reason why I found this "issue") where I set the default page depending on the domain.

**Comment by zero-24** [comment]
moving to RTC since we have successdful tests by @Hackwar and @jacxx Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4342">issues.joomla.org/joomla-cms/4342</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request merged**
