### PR TITLE
[4.3] Fix error from #39537 [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
You can't have two buttons with the same text that do different things. I am assuming that this change was made in error by @wilsonge in #39537

### Joomla 4.29
image

### Joomla 4.3 before this PR
image

### Joomla 4.3 after this PR
image

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 98105dc810914c9f3ec39d99e5c7a677716791a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40323">issues.joomla.org/tracker/joomla-cms/40323</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 98105dc810914c9f3ec39d99e5c7a677716791a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40323">issues.joomla.org/tracker/joomla-cms/40323</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40323">issues.joomla.org/tracker/joomla-cms/40323</a>.</sub>

**Comment by wilsonge** [comment]
Yup looking at it I'd assume I made a mess of it too. Thanks!

**Pull request merged**
