### PR TITLE
Fix batch processing of articles. Fixes #7038.

### LINKED ISSUE #7038: Batch process articles completely broken
#### Steps to reproduce the issue
Install current staging with testing sample data
In article manager select multiple articles
Press batch on the toolbar
Select a tag eg red (same with all other batch options)
Click Process

#### Expected result
Batch action is performed

If you have debug enabled then you will see further information

>Call stack
#	Function	Location
1	JApplicationCms->execute()	/Applications/MAMP/htdocs/joomla-cms-staging/administrator/index.php:47
2	JApplicationAdministrator->doExecute()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/cms.php:252
3	JApplicationAdministrator->dispatch()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/administrator.php:152
4	JComponentHelper::renderComponent()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/administrator.php:98
5	JComponentHelper::executeComponent()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/component/helper.php:372
6	require_once()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/component/helper.php:392
7	JControllerLegacy::getInstance()	/Applications/MAMP/htdocs/joomla-cms-staging/administrator/components/com_content/content.php:20
 Return to Control Panel

#### System information (as much as possible)
This is with staging branch as at 09:00 GMT Tuesday 26 May

### PR DESCRIPTION
**Pull request by wilsonge**
Try and perform any batch article process. Before you'll get a error that the controller can't be found. After should work properly

### CODE REVIEW

**Comment by infograf768** [comment]
OK here. Simple merge.

**Comment by brianteeman** [comment]
Works for me - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7040">issues.joomla.org/joomla-cms/7040</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7040">issues.joomla.org/joomla-cms/7040</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Merged. Thank you @wilsonge for PR, @infograf768 for the solution and @brianteeman for finding the bug! :-)

**Pull request closed without merging**
