### PR TITLE
Added Mail template Help strings

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue # .

An issue raised in the Joomla docs tracker.

### Summary of Changes

Added/revised JHELP keys and strings for the com_mails component

### Testing Instructions

Go to System / Mail Templates. In the mail templates list select the Help button
Then select a template to edit and in the Edit screen select the Help button
Then back in the list of email templates select the Options button. In the Options screen select the Help button

### Actual result BEFORE applying this Pull Request

All the help screens load a 404 page.

### Expected result AFTER applying this Pull Request

All the Help screens load a Help page 

### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5937327d9be0287df2d40aa5958a11c8a752772f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31054">issues.joomla.org/tracker/joomla-cms/31054</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5937327d9be0287df2d40aa5958a11c8a752772f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31054">issues.joomla.org/tracker/joomla-cms/31054</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31054">issues.joomla.org/tracker/joomla-cms/31054</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
