### PR TITLE
Merge in most the rest of Joomla 3.8.8

### PR DESCRIPTION
**Pull request by wilsonge**
ENSURE THIS IS MERGED AS A MERGE COMMIT - DO NOT SQUASH AND MERGE TO ALLOW ME TO BE ABLE TO FIX CONFLICTS BETWEEN J3.X AND J4

### CODE REVIEW

**Comment by wilsonge** [comment]
@rdeutz need you (or someone in the test team) to look at drone here ASAP please. As far as I'm concerned the only thing that's changed versions here is codemirror. Everything else is just http/https stuff

**Comment by rdeutz** [comment]
it fails because of the node update, we need to add [CLEAR CACHE] to a commit message to clean the cache hopeing the old sass bindung are deleted too.

**Comment by wilsonge** [comment]
Doesn't seem like that worked

**Comment by rdeutz** [comment]
http://ci.joomla.org/joomla/joomla-cms/12930 worked till the security analysis otherwise it seems ok to me.
@SniperSister or @zero-24 can you have a look?

**Comment by zero-24** [comment]
Rebooted drone as i have white listed the false positives; http://ci.joomla.org/joomla/joomla-cms/12931

**Comment by zero-24** [comment]
Drone & rips are happy now.

**Comment by rdeutz** [comment]
Thanks @zero-24, what now @wilsonge should I merge it?

**Comment by wilsonge** [comment]
Perfect! Thankyou :)

**Pull request merged**
