### PR TITLE
[4.0] Make transitions translateable

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #35094 .

### Summary of Changes
Transitions are now translateable everywhere.

For example:

Backend article edit view:
grafik

Backend article list view:
grafik

### Testing Instructions
- Make a fresh install of this PR
- Activate the workflow
- Go to the transitions
- See that there are now language keys as title
- Check the different occurrence of the transitions (backend/frontend edit article, list view backend)
- Use own language keys in transitions + language override function.

### Actual result BEFORE applying this Pull Request
Transitions are not (everywhere) translated

### Expected result AFTER applying this Pull Request
Transitions are translated everywhere.

### CODE REVIEW

**Comment by Kostelano** [comment]
Probably, we need to add new lines including to `api/language/en-GB/joomla.ini`

**Comment by brianteeman** [comment]
Yes please, at least for now, it is helpful if we just keep these files in sync

**Comment by brianteeman** [comment]
I am not a fan of editing previous update sql. They should be immutable.

**Comment by brianteeman** [comment]
Also the update sql you have will fail on an existing site.

/* SQL Error (1062): Duplicate entry '1' for key 'hvu3i_workflow_transitions.PRIMARY' */

**Comment by richard67** [comment]
> I am not a fan of editing previous update sql. They should be immutable.

@brianteeman I thought you meanwhile had understand that "immutable" is wrong due to all my past work on old update SQL files. And here you are again wrong: We can and should change the old update SQL because there is no risk in doing it and it makes the workflow transitions to be translatable also after update from 3.10 to 4.0.

> Also the update sql you have will fail on an existing site.
> /* SQL Error (1062): Duplicate entry '1' for key 'hvu3i_workflow_transitions.PRIMARY' */

Than only happens if you apply the update SQL changed by this PR to a Joomla 4 database. But that will never happen since this SQL will only run when updating a 3.10.

**Comment by brianteeman** [comment]
I stick by my views

**Comment by richard67** [comment]
As usual.

**Comment by brianteeman** [comment]
No point in having opinions if you don't believe in them. To repeat it's not about the technical need but as pointed out previously by another user changes to existing dated files can break complex work flows for server management

**Comment by bembelimen** [comment]
Hello,
thanks for the feedback.

> Also the update sql you have will fail on an existing site.
> 
> /* SQL Error (1062): Duplicate entry '1' for key 'hvu3i_workflow_transitions.PRIMARY' */

My concerns were, that I didn't want to change existing workflows, so I updated only the 3.x => 4.x path, not adding a new file which changes existing data. How did you raise this error? Could you give me please a little guide, so I can fix it?

**Comment by brianteeman** [comment]
If you are updating manually (perhaps you want to keep everything in github) then its reasonable to assume that someone would run the sql updates manually. Thats when you get the error. also see #22754

> My concerns were, that I didn't want to change existing workflows,

So now we have two sites with different data depending on when they were installed

When you now tell a user that workflows are translatable and they just need to create a language override it will only work on one of the two sites.

If you do an update query instead then everyone is on the same data (unless they changed the text already in which case their changed data is untouched)

UPDATE #__workflow_transitions SET title="PUBLISH_AND_FEATURE" WHERE title = "Publish & Feature"

**Comment by bembelimen** [comment]
Thanks @brianteeman I've pushed the update files.

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on c091084e4436572a2ad00929de13bee260bc10e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35457">issues.joomla.org/tracker/joomla-cms/35457</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on c091084e4436572a2ad00929de13bee260bc10e7<br /><br />All overrides work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35457">issues.joomla.org/tracker/joomla-cms/35457</a>.</sub>

**Comment by richard67** [comment]
@bembelimen This PR has conflicts now due to the names of the SQL update scripts already being used. That comes from the merged PR #35483 . Could you solve that?

**Comment by richard67** [comment]
Conflict solved, Since it doesn't have changed anything on what was relevant for the test, I restore the test results in the issue tracker so they are counted, and will set RTC.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35457">issues.joomla.org/tracker/joomla-cms/35457</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
