### PR TITLE
[4.0] Remove unused use statements and alphasort

### PR DESCRIPTION
**Pull request by Hackwar**
This removes unused use statements and alphasorts them everywhere. I'm relying on PHPStorm here, so I haven't tested every single file. If you want to do this yourself, simply select the project root (or the file that you want to check) and press CTRL-ALT-o. This does more than check all PHP files and I removed everything non-PHP, but unfortunately the SVG file slipped through the cracks...

### CODE REVIEW

**Comment by wlisikpl** [comment]
Agree. Should have been removed long ago in fact<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29581">issues.joomla.org/tracker/joomla-cms/29581</a>.</sub>

**Comment by ceford** [comment]
Using Eclipse I looked at almost all of the files bearing a tiny red x marker - usually indicating a list of use statements. I skipped some of those in vendor. I only found one list not in apparent alphabet order, in plugins/system/remember/remember.php:
 use Joomla\CMS\Plugin\CMSPlugin;
 use Joomla\CMS\Plugin\PluginHelper;
 use Joomla\CMS\User\UserHelper;
 use Joomls\CMS\Log\Log;
If you look closely that last is Joomls with an **s**. Is this a pass?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29581">issues.joomla.org/tracker/joomla-cms/29581</a>.</sub>

**Comment by alikon** [comment]
> use Joomls\CMS\Log\Log;

that's a typo

**Comment by alikon** [comment]
fix #29593

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 20cadf5990410604ff3dd988354ef74577462585<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29581">issues.joomla.org/tracker/joomla-cms/29581</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 20cadf5990410604ff3dd988354ef74577462585<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29581">issues.joomla.org/tracker/joomla-cms/29581</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29581">issues.joomla.org/tracker/joomla-cms/29581</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
