### PR TITLE
[4.0] calendar css

### PR DESCRIPTION
**Pull request by brianteeman**
This is a css change so you will need to run npm build:css

### Before
before

### After
after

Pull Request for Issue #34393

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5034eb10348ec78baf5a5ed61fcae004b9a9e374<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34395">issues.joomla.org/tracker/joomla-cms/34395</a>.</sub>

**Comment by brianteeman** [comment]
oops I committed unrelated files

**Comment by ghost** [comment]
Re-test?

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 71bb5ba950e0b739b6461d2ab033daa6868afb86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34395">issues.joomla.org/tracker/joomla-cms/34395</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
