### PR TITLE
Media type field strings

### PR DESCRIPTION
**Pull request by brianteeman**
This PR adds some consistency to the text in the tooltips for all media type fields. They now all indicate that you can **select** and **upload** an image with this field

### CODE REVIEW

**Comment by wilsonge** [comment]
RTC

**Comment by wilsonge** [comment]
This has conflicts - please can you merge in staging :)

**Comment by brianteeman** [comment]
My git skills are not good - can you help me

**Comment by wilsonge** [comment]
Do you have git set up on a command line?

**Comment by brianteeman** [comment]
i do yes but I usually just use the github mac client which is what causes issues

**Comment by brianteeman** [comment]
tried and failed to find resolve the conflicts - any help appreciated

**Comment by wilsonge** [comment]
I'm halfway through a long explanation. But just had an idea I can try to fix things first - two minutes!

**Comment by brianteeman** [comment]
Thanks - next time I wont use the mac client - it is harder to fix stuff with the gui than the cli

**Comment by wilsonge** [comment]
OK I think I've got it - can you just confirm for me for my own piece of mind this commit does the same thing as this PR https://github.com/wilsonge/joomla-cms/commit/60da74b25eae01cb014549b2db3cc6b8467b4c96

**Comment by brianteeman** [comment]
THANKS!!!!

Almost correct - you introduced two new changes that I have commented on

**Comment by wilsonge** [comment]
WOOOT :D Merged https://github.com/joomla/joomla-cms/commit/fb3b9ce70846486d92b3cb324866e99c4390a7f1

**Pull request closed without merging**
