### PR TITLE
[4] s/string/array to match function signature

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/string/array to match function signature

Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0d273b04effd4cac1a7fadd016bf74b57aa0cbb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33000">issues.joomla.org/tracker/joomla-cms/33000</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0d273b04effd4cac1a7fadd016bf74b57aa0cbb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33000">issues.joomla.org/tracker/joomla-cms/33000</a>.</sub>

**Comment by alikon** [comment]
i don't understand why drone complain on api test ?

**Comment by PhilETaylor** [comment]
> i don't understand why drone complain on api test ?

Because drone sucks sometimes. Its unrelated to this change in a docblock.

```
---------
433	1) ContactCest: Test crud on category
434	 Test  tests/Codeception/api/com_contact/ContactCest.php:testCrudOnCategory
435	                                                                                                                                                                                                                                                            
436	  [GuzzleHttp\Exception\ConnectException] cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/test-install/api/index.php/v1/contact/categories  
```

**Pull request merged**
