### PR TITLE
[6.0] Custom Fields: Correcting typehint for $this in layout

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
When adding typehints for these custom fields, I mistakenly used the FileLayout class, while it actually is the respective plugins class.

### Testing Instructions
Codereview.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by HLeithner — APPROVED** [review]
code review

**Comment by zero-24** [comment]
@HLeithner could it be that we need to merge the 5.2-dev to 6.0-dev first?

**Comment by HLeithner** [comment]
yes, but didn't head the time yet

**Comment by zero-24** [comment]
Done: https://github.com/joomla/joomla-cms/pull/43515

**Comment by HLeithner** [comment]
Merged in 6.0 to prevent override notification system, thanks

**Comment by Hackwar** [comment]
Thank you!

**Pull request merged**
