### PR TITLE
Get the runtime database driver for the configuration

### PR DESCRIPTION
**Pull request by twister65**
If the selected driver is `mysql` and we are on PHP 7 or greater, switch to the `mysqli` driver.
See PR #25729 and #25807 

### Summary of Changes
Get the actual database driver loaded at run time and fill in the dbtype parameter in the configuration form. You must save the configuration to update the file.

### CODE REVIEW

**Comment by richard67** [comment]
If this is the same as the other PR for 3.10-dev then it doesn‘t need the other one. @wilsonge Is that right?

**Comment by mbabker** [comment]
> If this is the same as the other PR for 3.10-dev then it doesn‘t need the other one. @wilsonge Is that right?

One pull request for a change, where the pull request is sent to the lowest active version branch the change applies to, and when merged the change merges forward as branches are merged up.  Not that hard of a concept once people get used to it...

**Comment by richard67** [comment]
@mbabker You don't have to explain me that. I know it. Was at work and so could not check if this PR is really the same, that's why I asked.

**Comment by richard67** [comment]
Ok, maybe I should not have asked George to confirm it, but I got used to people don't believe me so I ask for someone more "official" to confirm.

**Comment by mbabker** [comment]
The question comes up often enough that I figured more than you and a couple others might know for sure by now 😉

**Comment by richard67** [comment]
Anyway thanks for confirming and clarifying.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e86108066c4202c71b285a592137f223782e410c<br /><br />Tested by code review. I've tested the same change for 4.0-dev before (PR #25729 ) with a real test, so I think it is enough to verify that it's the same.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25833">issues.joomla.org/tracker/joomla-cms/25833</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e86108066c4202c71b285a592137f223782e410c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25833">issues.joomla.org/tracker/joomla-cms/25833</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25833">issues.joomla.org/tracker/joomla-cms/25833</a>.</sub>

**Comment by twister65** [comment]
@alikon please, could you also test PR #25729 ?

**Comment by alikon** [comment]
sure, done, and thanks i've missed that one

**Comment by HLeithner** [comment]
Thanks for preparing J3 for J4

**Pull request merged**
