### PR TITLE
[4.2] CLI extensions enabled

### PR DESCRIPTION
**Pull request by brianteeman**
When performing the cli commands
`php .\cli\joomla.php extension:list`
`php .\cli\joomla.php extension:discover`

the list of extensions contains a column titled **active**

not only is this a different term than used inside of Joomla it technically has a different meaning than the existing term **Enabled**

### Before

image

### After

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e806dff3ef38646fe68d4ac0f819bc7f46b1fd79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38205">issues.joomla.org/tracker/joomla-cms/38205</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e806dff3ef38646fe68d4ac0f819bc7f46b1fd79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38205">issues.joomla.org/tracker/joomla-cms/38205</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38205">issues.joomla.org/tracker/joomla-cms/38205</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
