### PR TITLE
[4.0] Fix error on creating a new viewing access level

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue #19374 

### Summary of Changes

A prefix for the table class name changed.

### Testing Instructions
1.Go to Users -> Viewing Access Levels
2.Try to create a new "Viewing Access Level" or edit previously Access Level.

Test this on Linux

### Expected result
No Error comes out.

### Actual result
Error Page

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2c47bf2373f1cb1c131f3bc60529a3cd24ab8ad1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19386">issues.joomla.org/tracker/joomla-cms/19386</a>.</sub>

**Comment by anuragteapot** [comment]
@laoneo can you test this on Linux if possible?

**Comment by laoneo** [comment]
Please fix it by using the namespace and not the legacy class name.

**Comment by anuragteapot** [comment]
Ok, let me try using the namespace.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19386">issues.joomla.org/tracker/joomla-cms/19386</a>.</sub>

**Comment by anuragteapot** [comment]
@laoneo I think the namespace which was used is correct because it works fine with Windows.
We have to do some changes in <code>getInstance</code> function to work fine with all types of OS.
what's your opinion??

**Comment by Anu1601CS** [comment]
The

**Comment by laoneo** [comment]
I hope that I can have a look tomorrow if it works on Linux too.

**Comment by anuragteapot** [comment]
So, I leaving this PR as it is.

**Comment by laoneo** [comment]
Replace the type argument with `$type = 'ViewLevel'` in the function parameter list. That should work then.

**Comment by anuragteapot** [comment]
@laoneo thanks,  it works. 
But, why <code>Viewlevel</code>  works with windows can you explain? Just for knowledge.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on abdaf52ca1bd6410f964de25fba9828798212a9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19386">issues.joomla.org/tracker/joomla-cms/19386</a>.</sub>

**Comment by anuragteapot** [comment]
@Quy test this change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19386">issues.joomla.org/tracker/joomla-cms/19386</a>.</sub>

**Comment by anuragteapot** [comment]
@wilsonge thanks :)

**Pull request merged**
