### PR TITLE
Remove some deprecated files

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

Removes two empty files that were marked as deprecated 3.2 and adds them to the list of files to be removed on upgraded sites
Removes all the batch_body files that were marked as deprecated 3.4 and added them to the list  of files to be removed on upgraded sites

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />Done code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11762">issues.joomla.org/joomla-cms/11762</a>.</sub>

**Comment by gwsdesk** [comment]
Applied and works4me :white_check_mark: 

RTC

**Comment by chrisdavenport** [comment]
Is there any possibility that this will break someone's site?  Bear in mind our development policy which states:

> "Previously deprecated elements that are no longer used in the product itself MUST be removed in the first version of a new major series but MUST NOT be removed in a minor or patch release."

**Comment by brianteeman** [comment]
I checked with @rdeutz before doing the pr

**Comment by rdeutz** [comment]
Didn't know about this policy. I think we should change it. I agree with not removing deprecated files in a patch release but it should be ok to remove in a minor release.

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 0d8356578485cccfe2e22882b297a22156537464<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11762">issues.joomla.org/joomla-cms/11762</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on 0d8356578485cccfe2e22882b297a22156537464<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11762">issues.joomla.org/joomla-cms/11762</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on 4cba7077572c9b72992c662a27a9dac1830854df<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11762">issues.joomla.org/joomla-cms/11762</a>.</sub>

**Comment by gwsdesk** [comment]
We have 4 x positive test results so this should be RTC?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11762">issues.joomla.org/joomla-cms/11762</a>.</sub>

**Comment by rdeutz** [comment]
Quick feedback on this here. We discussed the use of the deprecated tag in combination with semver yesterday at the PLT meeting. We realised that we don't have the same understanding, so the decision was to do some research and document a policy so that it is clear what it means and how to handle it. 

I am sorry but I think we need to set the state to needs review. Thank you all for working on this it has made clear that we need to define this clearer.

**Comment by wilsonge** [comment]
I'm merging this. We don't guarentee b/c in extensions according to our policy and we are no longer using these files. If someone is overriding default.php and this file in a template then it will also continue to work. But if they are overriding just this file then as we aren't loading them they will be non-functional.....

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/2ece1a792aede0a90642babb5c889cffbe295fdd

**Comment by brianteeman** [comment]
Thanks

**Comment by infograf768** [comment]
I suggest to revert this.
We have issues at least for 2 components in hathor
see
https://github.com/joomla/joomla-cms/issues/12407

**Comment by infograf768** [comment]
Was too fast: I guess we can solve the issues. See
https://github.com/joomla/joomla-cms/issues/12407#issuecomment-253479556

**Pull request closed without merging**
