### PR TITLE
[4.0] Toggle menu selection template style

### PR DESCRIPTION
**Pull request by brianteeman**
If you go to the template style and try to select which menu items etc that the style will be applied to then the wording is "Toggle selection".

The reality is that it does not toggle the selection but does either "select all" or "select none".

This PR corrects that so the toggle really does toggle the state of the checkboxes.

(Although the code is different in j3 the problem exists there as well so I can backport it if required @hleithner @zero-24)

The same problem with the toggle not being a toggle exists in other places but again as the code is different in each place I will address those in their own PR.

To test don't forget to do `npm i` or `node build.js --compile-js`

### Before
before

### After
after

### CODE REVIEW

**Comment by brianteeman** [comment]
(Note toggle selections in com_finder for the filters works correctly already)

**Comment by Fedik** [comment]
hm, actually there no issue with functionality, it supposed to work as it works now.
Your changes will make much more complicated to Select/Deselect all.

There only the label may a bit confusing, but we cannot easily switch it between "Select All/ Unselect All", that why it named with general string "Toggle".

Or we need to have 1-2 more buttons:
Select All / Deselect All / Toggle All

**Comment by brianteeman** [comment]
@Fedik It is not a toggle currently. Even though the value of the string is "toggle" and the key of the string is "invert" so clearly the original intent was for this to be a toggle. You will also see that the toggle string when used in com_finder for filters works correctly as a toggle and not a select all.

So if you want a select/deselect all then that is a separate and NEW issue that should have its own PR. This PR is fixing the bug that Toggle/Invert is not working correctly

**Comment by Fedik** [comment]
I understand your expectation, but I do not agree with suggested fix, because in reason I wrote.

> So if you want a select/deselect all then that is a separate and NEW issue that should have its own PR

Currently it not an issue, but this **will be** a new issue if your patch will be merged, I think it need to be fixed at once, somehow. 
Otherwise the patch introduce degradation in functionality.

**Comment by brianteeman** [comment]
We can agree to disagree then. From my perspective this PR fixes a bug in expected behaviour  of what a toggle will do. Think of it as a new user and not an experienced user who knows that when it says red it actually means green. Anything else is out of scope for this PR

**Comment by HLeithner** [comment]
Actually I think it a bug because the description of the button says "toggle" and not "select all" (an extra button that can do this would be useful if this get merged)

I'm also open for a backport to j3

**Comment by brianteeman** [comment]
Not just the text which could have been an error but the language key is explicit.

Will backport it tomorrow

**Comment by Fedik** [comment]
If you want, please leave it just for 4.0,
The behavior 10+ years old, and changing it in last versions of j3 (especially without additional button), I not think it a good idea.
People are used to it. That what I think.

**Comment by brianteeman** [comment]
@Fedik I checked the history and the original code was for it to be a toggle. It was _broken_ when it was converted from mootools to jquery

**Comment by brianteeman** [comment]
@HLeithner someone else will have to do the backport. its jquery and i dont get it

**Comment by HLeithner** [comment]
Ok thanks @brianteeman

**Comment by infograf768** [comment]
I would certainly not backport this to J3 and also not merge this in J4.
I agree with @Fedik that whatever the label, we are used to Unselect or Select All via the button.
The "original intention" was plain wrong and counterproductive.
A real toggle as proposed in this PR is totally useless and confusing. 
Anyone using a lot of menus would have to anyway go over all items to figure what is now selected or unselected...
Let's just change the label for the purists or make it 2 buttons, or indeed add a Select and Unselect all buttons BUT in the same PR. Otherwise, if not done, this will stay forever...

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 95b0c57c8faf09431599842e53be07fa428d956b<br /><br />For the reasons stated above I consider this PR "AS IS" as counterproductive.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27631">issues.joomla.org/tracker/joomla-cms/27631</a>.</sub>

**Comment by brianteeman** [comment]
It's a bug. The code originally was a toggle. A mistake when it was converted from mootools to jQuery resulted in the bug. That bug was replicated when converted to vanilla.

**Comment by infograf768** [comment]
It was a welcome bug as the feature is counterproductive.
If one really wants to Toggle as suggested add a Select and Unselect all buttons BUT in the same PR. Otherwise, if not done, this will stay forever...

**Comment by brianteeman** [comment]
> Otherwise, if not done, this will stay forever...

That is your personal opinion

> the feature is counterproductive.

I guess you need to change the behaviour of the **toggle** everywhere else that it is used then as everywhere else  the toggle works as a toggle. 

How do you explain to the users that here when it says toggle it doesnt really mean toggle

**Comment by brianteeman** [comment]
It is quite crazy that you are refusing to allow a bug to be fixed!!

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 6a6579965a1d4b18b060bf3e84d6e8e21c789d57<br /><br />The button now works as a toggle and checks/unchecks as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27631">issues.joomla.org/tracker/joomla-cms/27631</a>.</sub>

**Comment by Razzo1987** [comment]
@brianteeman can you pushes a change to GitHUb to generate prebuilt packages from Joomla CMS Bot  please

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 6a6579965a1d4b18b060bf3e84d6e8e21c789d57<br /><br />Tested and work!

Thanks to @roland-d who create the pakage for us :D <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27631">issues.joomla.org/tracker/joomla-cms/27631</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on 6a6579965a1d4b18b060bf3e84d6e8e21c789d57<br /><br />Good
<br /><br />
Thanks to @roland-d for the pakage<br />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27631">issues.joomla.org/tracker/joomla-cms/27631</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27631">issues.joomla.org/tracker/joomla-cms/27631</a>.</sub>

**Comment by wilsonge** [comment]
I have to say I'm not convinced that toggle really is the useful functionality here as opposed to a select all/deselect all. But clearly that was the original intention so merging as a fix

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
