### PR TITLE
[4.0] Form Rule prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements to `Joomla\CMS\Form\Rule\EmailRule` and `Joomla\CMS\Form\Rule\UsernameRule`.

### Testing Instructions

Enable user registration.
1) Try to register with already used username or email.
2) Try to register with unique email and username.
3) Login to frontend with another user. In user profile, try changing email to other user's email.
4) Edit profile without changing email or changing to unique email.

### Expected result

1) Registration fails with email/username already in use message.
2) Registration completed successfully..
3) Saving profile fails with email already in use message.
4) Profiled saved successfully.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9e19f01641831ba0a6b1b0e924ce13ab028ca0c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26083">issues.joomla.org/tracker/joomla-cms/26083</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9e19f01641831ba0a6b1b0e924ce13ab028ca0c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26083">issues.joomla.org/tracker/joomla-cms/26083</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26083">issues.joomla.org/tracker/joomla-cms/26083</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
