### PR TITLE
Fix Stylesheet Mime type keeping b/c

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #16266.

### Summary of Changes

Ensure b/c and ensure mime type is set on XML Stylesheets in RSS Feeds without PHP undefined index error. 

### Steps to replicate,

 - Edit /libraries/joomla/document/feed.php
 - On Line 206 (or anywhere in the render function, this is just to break it) add code:

```php
// 3/4 style with no options or attribs
$this->addStyleSheet('/media/system/css/modal.css');
```

or 

```php
// 3 with mime specified
$this->addStyleSheet('/media/system/css/modal.css','text/css');
```

or 

```php
// Joomla 4 with type specified
$this->addStyleSheet('/media/system/css/modal.css',array(),array('type'=>'text/css'));
```

 - View any RSS feed created by your Joomla site (mine: E.g.: index.php?option=com_content&view=featured&Itemid=109&format=feed&type=rss)

 - see error message in the RSS of:

screen shot 2017-05-26 at 22 18 05

Then Apply this PR, 

### Expected result

No error

@810

### CODE REVIEW

**Comment by brianteeman** [comment]
what change in 3.7  introduced this "error"? Surely we should be reviewing what broke things before coding solutions. Perhaps the thing thhat broke this broke something else as well which hasnt been reported yet

**Comment by PhilETaylor** [comment]
All this changed! https://github.com/joomla/joomla-cms/commit/b325dcd09d7607803de0219518cbeca08df016be#diff-88fc539e0ca61aec41d3fe2cb09ecc02

**Comment by PhilETaylor** [comment]
The whole method signature changed in Joomla 3.0

If @810 is actually complaining the Kunena does this, then maybe they should also change their method calls to `addStyleSheet` making sure they pass the correct parameters for the correct signature in Joomla 3 +

**Comment by PhilETaylor** [comment]
In fact looking at the comments:

```
* @deprecated 4.0  The (url, mime, media, attribs) method signature is deprecated, use (url, options, attributes) instead.
```

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 3593f5c8bfae6f5924b640725eb5b330571141d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16284">issues.joomla.org/tracker/joomla-cms/16284</a>.</sub>

**Comment by 810** [comment]
We will change it before J4.

thnx for the fix

**Comment by PhilETaylor** [comment]
Actually I have changed this PR to a different approach to fix the logic in the change for b/c made last year. This works better as it only effects the b/c block and not two different files.

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on f6008d93340d499dba3ba7ff71d3193dd4681e9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16284">issues.joomla.org/tracker/joomla-cms/16284</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f6008d93340d499dba3ba7ff71d3193dd4681e9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16284">issues.joomla.org/tracker/joomla-cms/16284</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
