### PR TITLE
[4.0] Removal of _QQ_

### PR DESCRIPTION
**Pull request by brianteeman**
These were all removed for J4 in #19030 but it looks like these two have appeared (probably the merges from j3)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2415277f537a0310c7645e9b27d3d575ac9b4640<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20399">issues.joomla.org/tracker/joomla-cms/20399</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 2415277f537a0310c7645e9b27d3d575ac9b4640<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20399">issues.joomla.org/tracker/joomla-cms/20399</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20399">issues.joomla.org/tracker/joomla-cms/20399</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
