### PR TITLE
en-GB extension install/uninstall strings

### PR DESCRIPTION
**Pull request by brianteeman**
This changes
Installing %s was successful.
to
Installation of the %s was successful.

and
Uninstalling %s was successful.
to
Uninstalling the %s was successful.

Which are both better english

### CODE REVIEW

**Comment by oorzaak** [comment]
After applying the patch, "%s" is replaced by "component", not by the component's name. Is that as intended?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6619">issues.joomla.org/joomla-cms/6619</a>.</sub>

**Comment by brianteeman** [comment]
yes it will be replaced by either component, module, plugin or template

On 10 April 2015 at 14:04, oorzaak <notifications@github.com> wrote:

> After applying the patch, "%s" is replaced by "component", not by the
> component's name. Is that as intended?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6619
> <http://issues.joomla.org/tracker/joomla-cms/6619>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6619#issuecomment-91549416>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by oorzaak** [comment]
Ok, thanks for your reply. See you around these Joomladagen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6619">issues.joomla.org/joomla-cms/6619</a>.</sub>

**Comment by crommie** [comment]
Tested. Everything you state above is true :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6619">issues.joomla.org/joomla-cms/6619</a>.</sub>

**Comment by zero-24** [comment]
RTC'ing again :smile: Thank you here!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6619">issues.joomla.org/joomla-cms/6619</a>.</sub>

**Pull request merged**
