### PR TITLE
[4.0] Clean up and alpha-order imports

### PR DESCRIPTION
**Pull request by roland-d**
### Summary of Changes
This PR only cleans up the imports by alpha-ordering them. After this we should enforce alpha-ordering the imports so we don't get fatal errors anymore because people add multiple includes.

For those on PhpStorm, you can enable the `Optimize Imports` in your commit window
image

### Testing Instructions
There are no functional changes, everything should work as before.

### CODE REVIEW

**Comment by brianteeman** [comment]
Cool stuff - did you have a script?

**Comment by roland-d** [comment]
Yes, it is a feature in PhpStorm where it lets you optimize imports on 
folders. I did check the results on every changed file if there were 
changes because since files showed up as changed but had no changes.

**Comment by brianteeman** [comment]
Cool - thanks for doing this.

> After this we should enforce alpha-ordering the imports so we don't get fatal errors anymore because people add multiple includes.

Could you add that to the styleguide please

**Comment by roland-d** [comment]
@brianteeman Done

**Comment by brianteeman** [comment]
Superstar!!

**Pull request merged**
