### PR TITLE
[fix] If Plugin "User - Joomla! " is disabled no login & logout possible

### LINKED ISSUE #7762: If Plugin "User - Joomla! " is disabled no login possible
#### Steps to reproduce the issue
Disable the plug-in "User - Joomla!" and logout. Now you cannot login anymore in Joomla! after you activate the plug-in by hand in database.

Is that normal?
If yes, I suggest to show a warning or add a message in the description as in the "Authentication - Joomla" plug-in: "Warning! You must have enabled this plugin if you use the Joomla! user management or you will lose all access to your site."

Regards,
Jan

### PR DESCRIPTION
**Pull request by zero-24**
This adds a message to the Plugin and fixes #7762 as this plugin needs to be there if you use the Joomla User Management.

Thanks @sisko1990

### CODE REVIEW

**Comment by wilsonge** [comment]
This isn't actually **strictly** true. The reason why things fail is because the user is logged in successfully. But when disabled the user details aren't stored in the session and therefore everything dies. Technically any plugin can store the user object in the session and it will work fine. Tbh you might even be able to get away with not even storing it in the session (although at that stage `JFactory::getUser` might have issues.

**Comment by zero-24** [comment]
@wilsonge do you have a suggestion for a better message?

Something like?
`
Warning! You must have enabled at least on plugin that handle the user session management or you will lose all access to your site.
`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7763">issues.joomla.org/joomla-cms/7763</a>.</sub>

**Comment by wilsonge** [comment]
This is @brianteeman territory but from a technical perspective that's much better than what you have at the moment

**Comment by laoneo** [comment]
Agree with the comments. Feeling a bit awkward to hit the Test success button for language strings changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7763">issues.joomla.org/joomla-cms/7763</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge I have updated it to that wording. Any problems with it @brianteeman ?

**Comment by brianteeman** [comment]
It should be ONE not ON
HANDLES not HANDLE

**Comment by zero-24** [comment]
oops some bad issues. Thanks @brianteeman fixed.

**Comment by zero-24** [comment]
As it is just a language update there we have a review. --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7763">issues.joomla.org/joomla-cms/7763</a>.</sub>

**Pull request merged**
