### PR TITLE
[4.0] remove unused js files

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #25568

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 868240e605ef8096ce032f4384acabef9dafe585<br /><br />Code review: This PR removes only the files mentioned in issue #25568 , not more and not less. It seems that these files are really not used anymore, but I can't grant this for 100%, I might have overseen something.

Hint: After these files have been removed with this PR, someone should add them to admin.php for removal, e.g. if the script for creating the list of removed files and folders is run.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25572">issues.joomla.org/tracker/joomla-cms/25572</a>.</sub>

**Comment by brianteeman** [comment]
@richard67 while J4 is in alpha we're not doing that per PR. @wilsonge is doing it with a script

**Comment by richard67** [comment]
@brianteeman Thanks. I know he has a script. I only did not know when he will use it, so I thought I leave a reminder. I did not expect it do be done with this PR here, that's why I gave it a good test.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks @C-Lodder

**Pull request merged**
