### PR TITLE
Add vscode to global gitignore

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Add .vscode to global .gitignore same as we did for .idea (PHPStorm)

### Testing Instructions

Review

### Expected result

git ignores vscode files / folders

### Actual result

git does not ignore vscode files

### Documentation Changes Required

None

### CODE REVIEW

**Comment by yasirunilan** [comment]
I have tested this item :white_check_mark: successfully on 1fff4104b5b7ed2783a85a8c011f703a8e84f2a1<br /><br />vscode files have been added to gitignore file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14505">issues.joomla.org/tracker/joomla-cms/14505</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 1fff4104b5b7ed2783a85a8c011f703a8e84f2a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14505">issues.joomla.org/tracker/joomla-cms/14505</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14505">issues.joomla.org/tracker/joomla-cms/14505</a>.</sub>

**Comment by zero-24** [comment]
Thanks 👍

**Pull request merged**
