### PR TITLE
[4.0] com_menus sidebar

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the unused sidebar code from com_menus

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated branch to retrigger drone time out errors unrelated to the code in this pr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fa0fa33fa6745c025c6939343be744b2536acaef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24866">issues.joomla.org/tracker/joomla-cms/24866</a>.</sub>

**Comment by Quy** [comment]
Delete: https://github.com/joomla/joomla-cms/blob/b756a9bec34493357327602ca70075689fe67ab0/administrator/components/com_menus/View/Menus/HtmlView.php#L72-L78

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 11a445f157292544c5819b7a12036baf390cd81f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24866">issues.joomla.org/tracker/joomla-cms/24866</a>.</sub>

**Comment by travisrisner** [comment]
I have tested this item :white_check_mark: successfully on 11a445f

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24866">issues.joomla.org/tracker/joomla-cms/24866</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
