### PR TITLE
Module article -newsflash

### PR DESCRIPTION
**Pull request by brianteeman**
Summary of Changes

Use the showon functionality now available in forms to simplify/reduce the options displayed in the module options in this case relating to displaying the article title

Testing Instructions

This is only a cosmetic change
Go to the module and try all the options on that page to ensure that the new show/hide functionality makes sense.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Random order doesn't have direction. You can use show on there to.

See https://github.com/joomla/joomla-cms/blob/staging/modules/mod_articles_news/helper.php#L67

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on ab50b8396de96c06d1dfce4dc65fb0810bb98056<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10163">issues.joomla.org/joomla-cms/10163</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ab50b8396de96c06d1dfce4dc65fb0810bb98056<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10163">issues.joomla.org/joomla-cms/10163</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10163">issues.joomla.org/joomla-cms/10163</a>.</sub>

**Pull request merged**
