### PR TITLE
fix on change JavaScript event on color form field with layout advanced

### PR DESCRIPTION
**Pull request by jurihahn**
Pull Request

### Summary of Changes
"onchange" event don't work on color form field. If I add 
```
<field
	name="my_color"
	type="color"
	control="advanced"
	onchange="alert('color changed');"
/>
```
I get result HTML result:
`<input type="text" name="my_color" ... data-control="advanced" alert('color="" changed');="" data-format="hex" size="7">`

### Testing Instructions
Create form with color form field and add custom "onchange" for example `onchange="alert('color changed');"` then load page with this form and select any color

### Actual result BEFORE applying this Pull Request
you **don't** get message "color changed"

### Expected result AFTER applying this Pull Request
you get message "color changed"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9193822d24568c4e812e8c4775925fe4f790c213<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41126">issues.joomla.org/tracker/joomla-cms/41126</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9193822d24568c4e812e8c4775925fe4f790c213<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41126">issues.joomla.org/tracker/joomla-cms/41126</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41126">issues.joomla.org/tracker/joomla-cms/41126</a>.</sub>

**Comment by obuisard** [comment]
Thank you Juri @jurihahn for the PR!

**Pull request merged**
