### PR TITLE
Fix max_execution_timeout exception for large documents in sef.php

### PR DESCRIPTION
**Pull request by hordijk**
Changed the reqex for all unknown protocols.

Removed the + character for the whitespace to solve a max_execution_timeout exception.
If you have a large output document (for example 1 mb) the regex '#\s+(src|href|poster)="(?!/|' . $protocols . '|#|\')([^"]*)"#m' takes way to long. Supporting only one \s will do the trick as well. The result will be additional spaces between attributes, but this shouldn't harm.

### CODE REVIEW

**Comment by nueckman** [comment]
Looks fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by b2un0** [comment]
Looks good, should be RTC.

**Comment by garstud** [comment]
Hello @hordijk 

Thank you for your contribution.
Please provide clear test instructions to be able to test this issue.
Does we need to create a big article (>1Mb), or something else ?

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by nueckman** [comment]
@garstud It's just a little performance tweak. max_execution_error is only a side effect. For testing you should load a large document (e.g. write a very large article and look at it on frontend).

**Comment by brianteeman** [comment]
Tried to get a time out with a massive article but failed so I cant test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by nueckman** [comment]
@brianteeman You don't need to get a time out. Just compare the execution time.

**Comment by nueckman** [comment]
And of course SEF has to be enabled.

**Comment by brianteeman** [comment]
The instructions and title both say " Fix max_execution_timeout exception"
Not compare execution time

On 25 May 2015 at 19:43, Nils Rückmann <notifications@github.com> wrote:

> And of course SEF has to be enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5741#issuecomment-105287216>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nueckman** [comment]
@brianteeman As max_execution_time is thrown after a certain time limit, it seems obvious to compare the execution time.

**Comment by brianteeman** [comment]
Clearly it wasnt obvious to me

On 25 May 2015 at 21:24, Nils Rückmann <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> As max_execution_time is
> thrown after a certain time limit, it seems obvious to compare the
> execution time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5741#issuecomment-105306018>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nueckman** [comment]
### Test Instructions:

1. Write an article with a significant amount of internal links.
2. Make sure that SEF is enabled. 
3. Browse to your article in the frontend
4. Measure the time to load the page (for example with debug-mode)
5. Apply the patch
6. Measure the time to load the page again.
7. Compare results.


### Expectation:

After applying the patch, the page should be a bit faster without any side effects.

**Comment by designbengel** [comment]
Tried to test it but the results are changing... :/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by anibalsanchez** [comment]
Tried to test it but I cannot verify an improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 19bf76b17ac29a63d950d977cae4197a3d563590<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by Fedik** [comment]
before patch:
  regex search for 1 or more `spaces`
after patch:
  regex check if 1 `space` exists

the improvement is obvious :wink:

**Comment by Kubik-Rubik** [comment]
Thank you for creating this. It’s been some time since you created this and there are now some merge conflicts that prevent a direct merge. Could you please update your PR? Thank you!

**Comment by brianteeman** [comment]
@hordijk Did you see the message above?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by ggppdk** [comment]
Ok with 1000 cases of 5000 spaces before  src="..."
```
for ($i=0; $i < 1000; $i++)
{
	echo '<img '.str_repeat(' ', 5000).' src="http://www.some_domain_test.org/img.png" />';
}
```

**Application afterRender**

**Before**:   36,000 miliseconds       15 KB   (compressed)    /   15 KB   (uncompressed)
**After**:  60 miliseconds    5 KB  (compressed) /	4956 KB  (uncompressed)


This is enough to accept **on code review**, it is really waste of CPU cycles to put a preg_match that starts on (without a good reason):   \s+

but i also tested, (easy to test just use the code above ...)

----
**A comment , it is not ONLY  cases of space before  src**
----

- **it is ALL the cases of consecutive "white-spaces" characters that TRIGGER the regexp**

think of it, it starts reading whitespace and then finds a word e.g.  hello   and it stops, but it has started to read the whitespace, that is the reason that this PR needs to be tested and accepted !

e.g. this will have the same effect
```
for ($i=0; $i < 1000; $i++)
{
	echo str_repeat(' ', 5000).' hello ';
}
```

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 19bf76b17ac29a63d950d977cae4197a3d563590<br /><br />Please read my previous comment and test, the more spaces you have on a large document, the slower your joomla page gets , and this happens for no good reason<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by hordijk** [comment]
Sorry for the delay, I finally updated the PR.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 96fe5854823d6d57037235c2a036c6c39e616716<br /><br />Please see my above comment about code to test performance, about correctness you can do a core review too<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by brianteeman** [comment]
(set back to pending as the merge conflicts were resolved)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by ggppdk** [comment]
This had 2 successful tests but due to rebase ,
it show only 1 test

Also it had code reviews and the fix is obvious too,

Please see my analysis above ,
on why this is a big performance issue in large documents, the effect becomes exponential

https://github.com/joomla/joomla-cms/pull/5741#issuecomment-236977383
https://github.com/joomla/joomla-cms/pull/5741#issuecomment-236978203

This can be merged

**Comment by Sieger66** [comment]
I have tested this item :white_check_mark: successfully on 96fe5854823d6d57037235c2a036c6c39e616716<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/joomla-cms/5741</a>.</sub>

**Comment by ggppdk** [comment]
Ok now this had 3 tests

**Comment by roland-d** [comment]
Setting RTC as we have multiple good tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5741">issues.joomla.org/tracker/joomla-cms/5741</a>.</sub>

**Pull request merged**
