### PR TITLE
[4.0][com_installer] - memory_limit check

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #26151 .

### Summary of Changes
more readable code

### Testing Instructions
change `memory_limit` setting in you php.ini
restart apache 

### Expected result

warning if  less than 8M or less than 16M
no warning if  greater than 16M

### CODE REVIEW

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on edf0e2f541f5b9dab75dd5cdc87f201310c18ea9<br /><br />Tested and watched the warnings change with the correct memory limits, thanks for patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26488">issues.joomla.org/tracker/joomla-cms/26488</a>.</sub>

**Comment by simonsigns** [comment]
I have tested this item :white_check_mark: successfully on edf0e2f541f5b9dab75dd5cdc87f201310c18ea9<br /><br />Tested - working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26488">issues.joomla.org/tracker/joomla-cms/26488</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26488">issues.joomla.org/tracker/joomla-cms/26488</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
