### PR TITLE
[com_fields] Remove obsolete modals

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #12659.

### Summary of Changes
Removes the modal files as they are not needed anymore because the content plugin support was removed. More information can be found here https://github.com/joomla-projects/custom-fields/issues/12 and here https://github.com/joomla-projects/custom-fields/pull/135.

If content support will be added then we need to add them as well as we can then implement an editor button to select fields in a description of an article.

### Testing Instructions
All should work as before.

### CODE REVIEW

**Comment by infograf768** [comment]
Tested OK. Missing commit SHA to use tests succesful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12672">issues.joomla.org/tracker/joomla-cms/12672</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok on code review

**Comment by mbabker** [comment]
> Missing commit SHA to use tests succesful

Refresh your browser cache.  Though that shouldn't be happening anymore at all; that was fixed two weeks ago and the cache directives for the tracker only cache CSS and JavaScript for one week.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ab370ba6b7aec5a27c92e95451befdbb27723067<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12672">issues.joomla.org/tracker/joomla-cms/12672</a>.</sub>

**Comment by laoneo** [comment]
So is this RTC ?

**Comment by laoneo** [comment]
RTC

**Comment by infograf768** [comment]
rtc anyway<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12672">issues.joomla.org/tracker/joomla-cms/12672</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ab370ba6b7aec5a27c92e95451befdbb27723067<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12672">issues.joomla.org/tracker/joomla-cms/12672</a>.</sub>

**Pull request merged**
