### PR TITLE
[4.0][a11y] Improve accessiblity in mod_search

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Improve a11y by adding role="search" to the form tag.

### Testing Instructions
Add a search module to your website.
Inspect the souce code before and after patch.

see also https://issues.joomla.org/tracker/joomla-cms/23686
and good description in https://issues.joomla.org/tracker/joomla-cms/23692

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 5c36fdaccdb80aa1f984e600cfca1556ee1d63d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23694">issues.joomla.org/tracker/joomla-cms/23694</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 5c36fdaccdb80aa1f984e600cfca1556ee1d63d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23694">issues.joomla.org/tracker/joomla-cms/23694</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23694">issues.joomla.org/tracker/joomla-cms/23694</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5c36fdaccdb80aa1f984e600cfca1556ee1d63d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23694">issues.joomla.org/tracker/joomla-cms/23694</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
