### PR TITLE
[4.0] Don't output empty target attribute

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Check for target value and to not output if empty.

### Testing Instructions
In back end, go to `System`.
View page source.
Find `target=""` (31 instances)

Go to `Help`.
Find `target=""` (2 instances)
Note the other links have `target="_blank"`.

### Expected result
No `target=""`

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1dbb48d8093a023672314ffdc2c75d659ef7f1bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26060">issues.joomla.org/tracker/joomla-cms/26060</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 1dbb48d8093a023672314ffdc2c75d659ef7f1bd<br /><br />After patch applied, all target="" have been removed from System and Help pages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26060">issues.joomla.org/tracker/joomla-cms/26060</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26060">issues.joomla.org/tracker/joomla-cms/26060</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
