### PR TITLE
[4.0] Add fancy select layout to multiple select lists

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR loads the fancy-select layout for some multiple lists instead of the default layout.

### Testing Instructions
Check views with multiple select fields (contact, some content modules, ...)

### Expected result
Fancy-select layout

### Actual result
Defualt list layout

### CODE REVIEW

**Comment by wilsonge** [comment]
Is there any reason for this other than consistent styling? Because that was the whole reason we ended up with everything being a chosen element. So I think where we can use the browser implementation we should.

**Comment by bembelimen** [comment]
For me the main reason is, that "normal people" don't know to multi-select with ctrl+mouse (+ definitely the layout)
For normal selects we should use the browser default (+ css) but for multiple select, the browser defaults are still unusable (imho)

**Comment by brianteeman** [comment]
Really?

For me we should only be using fancy-select when we need the extra functionality such as the ability to search a very long list. Which at a quick glance is probably true for most of these

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on f9d654ac1dda12f46abee852eaf134b9966fb75d<br /><br />Tested:
Components:
Contacts (2 elements found)
Modules:
Articles Latest
Articles Most Read
Articles: Newsflash
Banners
Tags: Popular

If I've missed any, please provide list.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24122">issues.joomla.org/tracker/joomla-cms/24122</a>.</sub>

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on f9d654ac1dda12f46abee852eaf134b9966fb75d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24122">issues.joomla.org/tracker/joomla-cms/24122</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Can we get another test because choices has been updated. Then we can merge it, to get tinymce merged.

**Comment by bembelimen** [comment]
> 
> 
> Can we get another test because choices has been updated. Then we can merge it, to get tinymce merged.

No Choices update here, I reverted it, I did it on the wrong branch...

**Comment by wilsonge** [comment]
I'm going to close this. I disagree with choices becoming the new chosen by using it everywhere. We use it where we need the full functionality (basically tags or searching lists of items)

**Pull request closed without merging**
