### PR TITLE
[4.0] fontawesome update

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #27019

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 11de481a727dfe81eac7260565b923d39c038994<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27028">issues.joomla.org/tracker/joomla-cms/27028</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 11de481a727dfe81eac7260565b923d39c038994<br /><br />1. Applied PR.
2. Done `npm install`.
3. Cleared browser cache.
4. Checked that version in file `./media/vendor/fontawesome-free/scss/brands.scss` is 5.11.2.
5. Checked backend icons still look as usual.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27028">issues.joomla.org/tracker/joomla-cms/27028</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27028">issues.joomla.org/tracker/joomla-cms/27028</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27028">issues.joomla.org/tracker/joomla-cms/27028</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
