### PR TITLE
[4.0] Update Button API typehints

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

As discussed in https://github.com/joomla/joomla-cms/pull/24305, this updates state value type to integer.

### Testing Instructions

Go to article list in backend. Inspect featured/transition icons.
Go to database, manually edit `featured` value of some article in `#__content` table. Change it to `2` or more. View the article in the article list.

### Expected result

Works like before.
Article with modified `featured` value shows `Unknown State` icon.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ I hope I can find time soon for testing. But I think you should extend your testing instructions a bit:
- Check that changing featured status works with the icon, for multiple selected items with the action button and in the edit view of a single article.
- Check that the featured articles view still works.
- Check that changing published status works with the icon, for multiple selected items with the action button and in the edit view of a single article.

And maybe the test with changing the value to a number larger than 1 in the database should be done for published, too.

**Review by wilsonge — APPROVED** [review]

**Comment by Razzo1987** [comment]
I have not tested this item.<br /><br />I done the test instruction befor apply the patch.

I have the expected resut without the patch...

immagine


EDIT: I see now on github that  @wilsonge approved these changes 22 days ago... why it is in the Joomla! Issue Tracker ? XD

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28380">issues.joomla.org/tracker/joomla-cms/28380</a>.</sub>

**Comment by wilsonge** [comment]
Because I can't merge everything based on code review. Often I want to see a test too to be confident in what I'm merging :)

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
