### PR TITLE
[4.0] website not web site

### PR DESCRIPTION
**Pull request by brianteeman**
As documented in the style guide this should be one word without capitalisation (unless it starts a sentence)

https://developer.joomla.org/en-gb-user-interface-text-guidelines/words-to-watch.html

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 435241ab506f78cfb69ce348924b42f131902f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25690">issues.joomla.org/tracker/joomla-cms/25690</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 435241ab506f78cfb69ce348924b42f131902f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25690">issues.joomla.org/tracker/joomla-cms/25690</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25690">issues.joomla.org/tracker/joomla-cms/25690</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
