### PR TITLE
[AppVeyor] Try to fix appveryor builds

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #28789

### Summary of Changes

[AppVeyor] Try to fix appveryor builds as mention here: https://github.com/joomla/joomla-cms/issues/28789#issuecomment-620941697

### CODE REVIEW

**Comment by zero-24** [comment]
Any pointers on this one where to look at @rdeutz @SniperSister or should we just drop php 7.2+ testing as it is not supported by our tooling? Would not good to me.

**Comment by wilsonge** [comment]
The only thing that doesn't support it is the friendsofphp/php-cs-fixer - I'm not even sure if we use this anywhere - I think it was just a nice to have automated fixer?

I'd be tempted to just drop it in staging if we aren't using it actively

**Comment by zero-24** [comment]
> I'd be tempted to just drop it in staging if we aren't using it actively

hmm agree but seems our lock file is out of date and needs to be updated anyway right? Or I'm just looking at the wrong place?

**Comment by wilsonge** [comment]
why is it out of date?

**Comment by zero-24** [comment]
when i remove the line mention and run composer i get this:
image

**Comment by wilsonge** [comment]
That means you've made changes locally to the files in the directory on your laptop

**Comment by zero-24** [comment]
Well I just have to run composer remove on the mention package right?

That thing than result into a tone of changed files. Maybe i'm doing something wrong?

**Comment by mbabker** [comment]
Here's my free advice for the day.  Check the Composer version that AppVeyor is installing, the error message being printed comes from a feature in Composer 2.0.

Working around that addresses the most immediate error, but it still doesn't address the fact that the CMS dependency tree is reliant on a number of end of support versions of software packages and with PHP 8 approaching you might find yourselves forking and maintaining packages to try and be compatible with the 10 PHP branches the version constraint will allow (5.3.10 thru 8.0).

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/commit/3687dba27ed2f7e5cedc50797a8073ba31e29efa Based on @mbabker 's comment fixed

**Pull request closed without merging**
