### PR TITLE
[4.1] task titles

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the period from the end of the title. This is more consistent and follows the style guidelines

## Before
image

## After
image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on cf5b071f279a54fbc759a2ed58a0c60705e77cba<br /><br />Code inspect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36205">issues.joomla.org/tracker/joomla-cms/36205</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on cf5b071f279a54fbc759a2ed58a0c60705e77cba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36205">issues.joomla.org/tracker/joomla-cms/36205</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36205">issues.joomla.org/tracker/joomla-cms/36205</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on cf5b071f279a54fbc759a2ed58a0c60705e77cba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36205">issues.joomla.org/tracker/joomla-cms/36205</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
