### PR TITLE
Corrected typo in pt-BR. Issue #6121

### PR DESCRIPTION
**Pull request by prasoon2211**
A simple typo was fixed. Verification : http://goo.gl/adTKoK

Issue #6121

### CODE REVIEW

**Comment by Bakual** [comment]
Sent an email to the language coordinators so they can have a look.

**Comment by Bakual** [comment]
Hmm, emails are rejected as don't exist.
@infograf768 Can you contact them somehow?

**Comment by infograf768** [comment]
On it

**Comment by infograf768** [comment]
helvecio is the new pt-BR coordinator. I asked him to have a look.

**Comment by Bakual** [comment]
Can you update http://community.joomla.org/translations/joomla-3-translations.html#pt-br then with his contacts?

**Comment by infograf768** [comment]
@bakual
WE forecast to do that when the 3.4.0 language pack is release

**Comment by Bakual** [comment]
Cool, thanks :+1:

**Comment by helvecio** [comment]
Thank you for correcting the typo. Original file has been updated.

**Comment by brianteeman** [comment]
Can we close it here then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6122">issues.joomla.org/joomla-cms/6122</a>.</sub>

**Comment by Bakual** [comment]
Merging it so it's in core.
Since original file is updated, it will not conflict.

**Pull request merged**
