### PR TITLE
Language files for components updated to match style guidelines.

### PR DESCRIPTION
**Pull request by Duke3D**
References to Joomla in mid-sentence should not include the exclamation point.  Usability / accessibility outweighs any trademark benefit.

Trademark indicia added to references to the JED.

### CODE REVIEW

**Comment by infograf768** [comment]
We are in language freeze. Imho this should not be merged until 3.4.1.

**Comment by brianteeman** [comment]
This is part of the work of the en-GB working group and will be followed by further PR for plugins and modules shortly. Removing the ! does not effect translations and is part of the agreed work that PLT has already approved can be committed and as agreed is being deliberately submitted after the language freeze.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6094">issues.joomla.org/joomla-cms/6094</a>.</sub>

**Comment by infograf768** [comment]
sigh...

**Comment by Hils** [comment]
For the very many translators using eg Transifex as their preferred tool to prepare translations for Joomla before submission to the official team,  this has a great effect on translations. 

For example Joomla! is a different word from Joomla and is treated as such. 

Several official translators have already packaged their languages for 3.4 and I think it is our job to make things less disruptive for translators by waiting until after 3.4 release.

**Comment by brianteeman** [comment]
This is a PLT decision

On 15 February 2015 at 12:56, Hils <notifications@github.com> wrote:

> For the very many translators using eg Transifex as their preferred tool
> to prepare translations for Joomla before submission to the official team,
> this has a great effect on translations.
>
> For example Joomla! is a different word from Joomla and is treated as
> such.
>
> Several official translators have already packaged their languages for 3.4
> and I think it is our job to make things less disruptive for translators by
> waiting until after 3.4 release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6094#issuecomment-74416375>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
I do not believe PLT would decide to do this if they understood how translators work. When was this decision made please? and where? Was it a decision by the whole PLT which included people who understand translating as, for example, @Bakual does?

**Comment by Hils** [comment]
Further information that might be useful:
As a result of https://github.com/joomla/joomla-cms/pull/5615 ,
from the 8333 total lines to be translated for 3.4, 1849 had to be edited, after the language freeze.

**Comment by brianteeman** [comment]
Hils - that was the agreement made and it was done at the request of the PLT and the TT co-ordinator AFTER the language freeze. It was ready a month before the freeze but the TT co-ordinator requested that it was NOT merged until after the freeze.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6094">issues.joomla.org/joomla-cms/6094</a>.</sub>

**Comment by Bakual** [comment]
PLT decided to merge #5615 after language freeze so JM can do diffs and share them with the teams.
This was done in agreement with JM and translators were informed about it.

There was no decision made for following PRs. My understanding was that the referenced PR was complete for stage1 and that further PRs will be done after 3.4.0 is released.

I certainly don't want to merge more language strings at this time, short before RC.

However I agree with the standardising and we will likely merge it shortly after 3.4.0 is released. Giving translators enough time to update their strings.

**Comment by brianteeman** [comment]
OK I am closing this PR and will close the WG - you win again and we go
back to the dark ages

On 15 February 2015 at 13:25, Thomas Hunziker <notifications@github.com>
wrote:

> PLT decided to merge #5615
> <https://github.com/joomla/joomla-cms/pull/5615> after language freeze so
> JM can do diffs and share them with the teams.
> This was done in agreement with JM and translators were informed about it.
>
> There was no decision made for following PRs. My understanding was that
> the referenced PR was complete for stage1 and that further PRs will be done
> after 3.4.0 is released.
>
> I certainly don't want to merge more language strings at this time, short
> before RC.
>
> However I agree with the standardising and we will likely merge it shortly
> after 3.4.0 is released. Giving translators enough time to update their
> strings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6094#issuecomment-74417316>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
Factual discussion is constructive. @Bakual has said that 'they will likely merge it shortly after 3.4.0 is released'. Why can't this PR, which we all seem to agree with, wait? What has closing it achieved?

**Comment by Bakual** [comment]
Huh? Reopneing since I still think this is a valid PR.

**Comment by ot2sen** [comment]
The cosmetic style changes here do have an impact on the work the Fellow volunteers in the translation area will have. More of the tools they use to assist on automatically merging and updating source to target language changes, will reset a full string in most cases.
While it is good on quality that the individual teams are forced to review any core source language changes, still such cosmetic style changes in last minute mean that 40 strings will have to be redone for all 60 languages. 

Would be reasonable to wait until after release in a case like this.
Adding an example of how removing one ! in source will bring work to any team of the full string where the ! was removed.
joomlatest_after
joomlatest_before

**Comment by Duke3D** [comment]
While there is some urgency to get a style guide in place, which Brian has done great job in coordinating, I see no reason that implementation in the language files cannot wait until 3.4.1  My apologies if this PR was premature - there was to intention to disrupt the TT teams.  Implementation for the en-gb files served as a good test whether the style rules were complete enough to address the actual language stings in use, without ambiguity, before we go to the next step of translating the rules themselves.

**Comment by Bakual** [comment]
Set to RTC and added the 3.4.1 milestone. Thanks Duke!

**Comment by phproberto** [comment]
Merged. Thanks!

**Comment by Bakual** [comment]
Sorry guys. Had to temporary revert this commit because we are still in language freeze for Joomla 3.4.1.
We will reapply it once 3.4.1 is released.

**Comment by brianteeman** [comment]
sad

On 14 March 2015 at 09:28, Thomas Hunziker <notifications@github.com> wrote:

> Sorry guys. Had to temporary revert this commit because we are still in
> language freeze for Joomla 3.4.1.
> We will reapply it once 3.4.1 is released.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6094#issuecomment-80211267>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
So is this going to be re-opened or are we now going to completely ignore anything that you dont like to have in joomla. And no I dont believe that you are going to commit it after 3.4.1 - it was already promised for 3.4.1 when you made the last useless language freeze.
Seriously the language freeze is a joke. Did it result in even a majority of translations being ready

**Comment by phproberto** [comment]
Sorry if I caused the confusion. I saw it in the v3.4.1 milestone after the discussion about including it or not and I thought it was decided.

**Comment by brianteeman** [comment]
It was decided but no one carried out the decision :(

On 14 March 2015 at 14:47, Roberto Segura <notifications@github.com> wrote:

> Sorry if I caused the confusion. I saw it in the v3.4.1 milestone after
> the discussion about including it or not and I thought it was decided.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6094#issuecomment-80517950>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
Reopened and assigned to 3.4.2 milestone.  @wilsonge when you do your post release merge frenzy, merge this.

**Comment by Bakual** [comment]
> So is this going to be re-opened

I would just have applied it again after release, but reopening sure works as well.

**Pull request merged**
