### PR TITLE
[4] s/timout/timeout

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/timout/timeout

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1223b655427edae9b1859b59279b2eea5693a7d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35344">issues.joomla.org/tracker/joomla-cms/35344</a>.</sub>

**Comment by zero-24** [comment]
Isnt that the same change the we merged into 3.10 already so this will be merged up from there?

Can you traget such PRs against 3.10 so both branches get the fixes?

**Comment by PhilETaylor** [comment]
Different file, different location. Saves maintainers time.

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 1223b655427edae9b1859b59279b2eea5693a7d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35344">issues.joomla.org/tracker/joomla-cms/35344</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35344">issues.joomla.org/tracker/joomla-cms/35344</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
