### PR TITLE
[4.0] Remove title tooltip overlapping tooltip

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove title tooltip that has redundant info overlapping tooltip.

### Testing Instructions
Install Multilingual Sample Data.
Go to Articles list.
Under Association column, hover over a badge.
See tooltip overlapping tooltip.

Do the same for Categories, Contacts, News Feeds, and Menus.

### Actual result
tooltip

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 5764702076f2f4622e6c0dd280e146726b59f7f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27557">issues.joomla.org/tracker/joomla-cms/27557</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5764702076f2f4622e6c0dd280e146726b59f7f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27557">issues.joomla.org/tracker/joomla-cms/27557</a>.</sub>

**Comment by infograf768** [comment]
Thanks. I tested it ok.
We have the same issue for com_associations:
I solved it by
```
diff --git a/administrator/components/com_associations/Helper/AssociationsHelper.php b/administrator/components/com_associations/Helper/AssociationsHelper.php
index 3dc84f2..651a1b4 100644
--- a/administrator/components/com_associations/Helper/AssociationsHelper.php
+++ b/administrator/components/com_associations/Helper/AssociationsHelper.php
@@ -338,5 +338,5 @@
 			$classes = 'badge ' . $labelClass;
 
-			$items[$langCode]['link'] = '<a href="' . $url . '" title="' . $language->title . '" class="' . $classes . '">' . $text . '</a>'
+			$items[$langCode]['link'] = '<a href="' . $url . '" class="' . $classes . '">' . $text . '</a>'
 				. '<div role="tooltip">' . $tooltip . '</div>';
 		}
```
Shall you add it in this PR or make a new PR?

**Comment by infograf768** [comment]
@SharkyKZ 
can you test again, this time for com_associations?

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 40d33f879951c339c0c97207cbbc0d0305bd8741<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27557">issues.joomla.org/tracker/joomla-cms/27557</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27557">issues.joomla.org/tracker/joomla-cms/27557</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
