### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by wilsonge**
Whilst we have a b/c policy to maintain. In this very special case I'd like to propose removing this method. It is completely and irreversibly broken. It stems from `http://help.joomla.org/helpsites.xml` not actually existing as a file. Me and @mbabker removed the entire Joomla 1.0 site there so it was just the minimum required for the 1.0 and 1.5 help screens. This file didn't even exist at that point - which means it's been broken for a long long time as it's getting the html page contents and pushing it into the `JPATH_BASE . '/help/helpsites.xml` if it ever gets called. This will then screw the actual help sites list in com_config in the currently used method.

Therefore I think this is a special case to our usual b/c policy because using this method will actively break the Joomla API. So I'd like to propose removing it in Joomla 3.5 (and technically our b/c policy doesn't cover extensions anyhow)

### CODE REVIEW

**Comment by infograf768** [comment]
What about
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/help/help.php#L187

**Comment by Bakual** [comment]
As you said, our B/C promise doesn't cover com_config anyway. So it would be fine for removal especially if it's broken anyway.
For testing I suppose just test that the "Refresh" button for the "Help Server" parameter in the Joomla configuration still works as before (or better).

**Comment by wilsonge** [comment]
The refresh button doesn't use this code. It uses the code Jean Marie pointed out. This code is literally unused in the CMS

**Comment by Bakual** [comment]
Yeah, assumed that. But just to make sure and to have some simple tests :)
Or if someone wants to confirm that code isn't called anywhere.

**Comment by andrepereiradasilva** [comment]
`egrep -R 'refreshHelp' /path/to/joomla-cms/` only results in:
```
/path/to/joomla-cms/administrator/components/com_config/controllers/application.php:       public function refreshHelp()
```
In other words ... the file you are removing.

**Comment by infograf768** [comment]
I tested the patch here i.e. deleted the French help site from `/administrator/help/helpsites.xml` and used the refresh button. All went fine. 
As for the use of the code deleted here, no idea tbh.

**Pull request merged**
