### PR TITLE
form field number issue for negative min values

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue # 8928

**Summary of Changes**
If the min value is set to negative then value , by default value was set to the min-value. Solved by replacing a few lines of code.

**Testing Instructions**
As stated in the issue #8928

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 25e98ea27271b49eb4107a97ce9251305c4113e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9336">issues.joomla.org/joomla-cms/9336</a>.</sub>

**Comment by nibra** [comment]
As the tests show, this approach breaks compatibility. If neither `value` nor `min` are given, the resulting HTML **must** contain `value=""`.

**Comment by GABBAR1947** [comment]
@nibra can you have a look. I modified the code accordingly.

**Comment by nibra** [comment]
Tests pass, so it's fine. @RonakParmar, could you test once again?

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 46201640896e6e36b73609f9f571f319b587c8d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9336">issues.joomla.org/joomla-cms/9336</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 46201640896e6e36b73609f9f571f319b587c8d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9336">issues.joomla.org/joomla-cms/9336</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9336">issues.joomla.org/joomla-cms/9336</a>.</sub>

**Pull request merged**
