### PR TITLE
[4.0] Fix: Upload & Update. Notice: Undefined offset: -1 in TemplateModel.php

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23702

### Summary of Changes
- Additional check if filename contains a hyphen. Only then it's guaranteed that `$size = count($explodeArray);` (line 568) has a minimal value `2` and `$explodeArray[$size - 2]` (line 569) will not throw a waning.

### Testing Instructions
- Code review after reading https://github.com/joomla/joomla-cms/issues/23702#issue-403803982
- Or build your custom update/full package with this pr applied and follow instructions in https://github.com/joomla/joomla-cms/issues/23702#issue-403803982

- Test with "Joomla Patch Tester"? NO. Not possible.

### CODE REVIEW

**Comment by astridx** [comment]
I have tested this PR. But I did it a different way:
I saw this error message in template manager after renaming an override file form `default.php` to `default9.php`. And after that I saw this error every time I clicked on the filename for opening the file `default9.php` in the template manager.

After applying this patch everything works fine. If this type of test is also OK, then Patch Tester could be used.

templates customise cassiopeia rsfd administration
templates customise cassiopeia rsfd administration 1

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 35cc9950ede138f98e503295eb39b1998338c281<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23712">issues.joomla.org/tracker/joomla-cms/23712</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 35cc9950ede138f98e503295eb39b1998338c281<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23712">issues.joomla.org/tracker/joomla-cms/23712</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
