### PR TITLE
[#31514] Changing list formfields to use a default class "advancedSelect" for Chosen support

### PR DESCRIPTION
**Pull request by Bakual**
This is an updated and bit improved version of #1620.
Originally it started as a way to automatically disable Chosen when there are a lot of options. It expanded a bit from there.
There are also other PRs with have different ways proposed to solve similar issues: #2018, #1609

See also Feature Tracker:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31514
### Issue

Chosen has performance issues when facing a huge amount of options. Since the menu item view (like most views) use `JHtml::_('formbehavior.chosen', 'select');` to load Chosen on every ``, this can break the creation of menu items.
This PR makes use of the default behaviour of`JHtml::_('formbehavior.chosen');`which triggers on the class`.advancedSelect`.
### Proposed Solution

This PR will do a few things:
- Changing the `list`, `groupedlist`, `accesslevel` and `componentlayout` formfields so it defaults to the class "advancedSelect" if no class is given. Currently there is no default at all.
- Changing the `list` formfield so it removes this class if there are more than 10'000 options.
- Changing the call `JHtml::_('formbehavior.chosen', 'select');` to use the default `JHtml::_('formbehavior.chosen');` in the menu item view.

For now, the scope is only the menu item edit form, however it would be possible to expand it to other places as well if we decide to follow that route. Especially if we use a default class within the fields, we don't have to edit 100+ XML files to add the class there.

If a developer decides he doesn't want to use Chosen for a specific field, he could just add a random class to the field in the XML and Chosen wouldn't be loaded anymore.

There may be better ideas of course :smile: 
### Testing
- Make sure the menu item edit screen looks the same before and after the patch. Especially the dropdown lists should look and behave the same (using Chosen).
- Try testing with some big data, like 10'000 categories and check that the category selection doesn't use chosen anymore.

### CODE REVIEW

**Comment by n9iels** [comment]
Can you please give us an method to make 10000 categories so we can test your patch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3721">issues.joomla.org/joomla-cms/3721</a>.</sub>

**Comment by brianteeman** [comment]
You can use com_overload from @nikosdion
https://github.com/nikosdion/com_overload

**Comment by Bakual** [comment]
Closing due to lack of interest.

**Comment by brianteeman** [comment]
Any chance of resurrecting this

**Comment by Bakual** [comment]
If there is any interest in it, I (or anyone else) can recreate it easily.

**Comment by brianteeman** [comment]
If its easy to recreate I am definitely interested in seeing it

On 13 April 2016 at 18:09, Thomas Hunziker <notifications@github.com> wrote:

> If there is any interest in it, I (or anyone else) can recreate it easily.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/3721#issuecomment-209548635>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
@brianteeman See https://github.com/joomla/joomla-cms/pull/9901 (waiting for Travis to fail, need likely to fix some Unit Tests).

**Comment by brianteeman** [comment]
Thanks - i will take a look tomorrow when I sober up

On 13 April 2016 at 18:47, Thomas Hunziker <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> See #9901
> <https://github.com/joomla/joomla-cms/pull/9901> (waiting for Travis to
> fail, need likely to fix some Unit Tests).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/3721#issuecomment-209564400>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by xjdfhbv** [comment]
There absolutely needs to be a way for select lists to "opt out" of being modified by Chosen. There will always be occasions where Chosen either doesn't work well, or isn't appropriate. I have just had to add some Javascript to one of my extensions to prevent a select list being hit by Chosen, but it's not pretty. The Chosen initialisation should be modified to always exclude selects that have a certain class, e.g. "not_chosen", or something.

**Pull request closed without merging**
