### PR TITLE
Use new user instance

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Create new user instance before clearing access rights cache so as not to clear it globally.

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 56f7bc0af6e131a0f52c42d8506f4a911bf570a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22697">issues.joomla.org/tracker/joomla-cms/22697</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 56f7bc0af6e131a0f52c42d8506f4a911bf570a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22697">issues.joomla.org/tracker/joomla-cms/22697</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22697">issues.joomla.org/tracker/joomla-cms/22697</a>.</sub>

**Comment by HLeithner** [comment]
@SharkyKZ whats the reason for this change?

**Comment by SharkyKZ** [comment]
It was a mistake on my part. We need to check new user access rights in this plugin but we shouldn't clear them on the global user instance as this could lead to undesirable behavior in code and other plugins that run after this one.

**Comment by HLeithner** [comment]
ok thx

**Comment by HLeithner** [comment]
thx

**Pull request merged**
