### PR TITLE
[4.0] correct css class for backgrounds

### LINKED ISSUE #22979: [4.0] Updates Alert background color missing
### Steps to reproduce the issue

install old Joomla 4 extension - example file: http://screenshot.myjoom.la/40198d99d777
go to Joomla 4 admin

### Expected result

screenshot 2018-11-09 at 15 17 26

But it should not be a green background - its a warning ! 

### Actual result

screenshot 2018-11-09 at 15 08 02

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Steps to reproduce the issue

#22979

install old Joomla 4 extension - example file: http://screenshot.myjoom.la/40198d99d777
go to Joomla 4 admin

### Expected result

screenshot 2018-11-09 at 15 17 26

### Actual result

screenshot 2018-11-09 at 15 08 02

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks :)

**Comment by PhilETaylor** [comment]
I cannot work out how to change the success to a danger/warning though :( any ideas?

**Comment by wilsonge** [comment]
https://github.com/PhilETaylor/joomla-cms/blob/5a50c5b52a8451c92f4c76f7c5e5c53dae64a210/build/media_src/system/js/core.es6.js#L396-L399

**Comment by PhilETaylor** [comment]
Hmmm @infograf768 has a pr that removes that somewhere - so maybe that too is broken and needs fixing now :-( if you ass that kind of error: info at the moment you get two alert boxes!!!



——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Pull request merged**
