### PR TITLE
[4.0] Fix module ordering field

### PR DESCRIPTION
**Pull request by Bakual**
Fixes the admin module ordering field 

### Summary of Changes
Fixes a typo in the AJAX call

### Testing Instructions
Edit an admin module and see the "Ordering" field.

### Expected result
List of modules in that position

### Actual result
"None"

### Documentation Changes Required
None.

### Comment
You have to run the npm command to build the JS stuff. I just did "npm ci" but I'm sure there is a simpler way.

### CODE REVIEW

**Comment by wilsonge** [comment]
`npm run build:js` (see https://github.com/joomla/joomla-cms/blob/4.0-dev/package.json#L15-L23 for the list of available commands)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f6ccb16fee3f7d89c5f54fea7f7c5eba7cc1a227<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24358">issues.joomla.org/tracker/joomla-cms/24358</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f6ccb16fee3f7d89c5f54fea7f7c5eba7cc1a227<br /><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24358">issues.joomla.org/tracker/joomla-cms/24358</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24358">issues.joomla.org/tracker/joomla-cms/24358</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
