### PR TITLE
[4.0] Media Manager: Fix messages display

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
Instead of getting an auto-dismiss alert which format is wrong and and automatically shortly disappears, we now get messages of the same type as in other components.

### Testing Instructions
In media manager:
Upload a file to get a success message.
Without selecting anything, click on the Delete button to get an error.

### Before patch

media_alert

### After patch
Screen Shot 2020-02-23 at 08 01 00

Screen Shot 2020-02-23 at 08 01 13

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a5e5d7112de834bac7a730347995f1ee20f9f1c9<br /><br />great stuff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28025">issues.joomla.org/tracker/joomla-cms/28025</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a5e5d7112de834bac7a730347995f1ee20f9f1c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28025">issues.joomla.org/tracker/joomla-cms/28025</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28025">issues.joomla.org/tracker/joomla-cms/28025</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
