### PR TITLE
[4.3] spelling fine-tune

### PR DESCRIPTION
**Pull request by brianteeman**
This should be a hyphenated w9ord and not two individual words

references
 https://dictionary.cambridge.org/dictionary/english/fine-tune
 https://www.oxfordlearnersdictionaries.com/definition/english/fine-tune?q=fine+tune

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: (https://github.com/joomla/Manual/pull/113)
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ce013c4e15c28a6972b2b5fb7103d50bdfa6fee3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40471">issues.joomla.org/tracker/joomla-cms/40471</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ce013c4e15c28a6972b2b5fb7103d50bdfa6fee3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40471">issues.joomla.org/tracker/joomla-cms/40471</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40471">issues.joomla.org/tracker/joomla-cms/40471</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brian @brianteeman !

**Comment by brianteeman** [comment]
thx

**Pull request merged**
