### PR TITLE
[4.0] `td` is not a self closing html tag

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

`td` is not a self closing html tag

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b20433b0936a0130918e834e325d705a96cbbacf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36339">issues.joomla.org/tracker/joomla-cms/36339</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b20433b0936a0130918e834e325d705a96cbbacf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36339">issues.joomla.org/tracker/joomla-cms/36339</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36339">issues.joomla.org/tracker/joomla-cms/36339</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
