### PR TITLE
[4.4] Media Manager long filenames

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #41839 .

### Summary of Changes
- Truncate filename in media actions menu
- set max width on media-browser-item-info

### Testing Instructions
Using the image select in the _images and links_ tab of a new article 
- rename an image to something crazy long
- close the image select
- re-open the image select

as this an scss change you will need to test with either one of the prebuilt packages or `npm run ci` after applying the pr
### Actual result BEFORE applying this Pull Request

image

image

### Expected result AFTER applying this Pull Request
image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@crystalenka This touches some css you wrote so it would be good to have a check if you have time please.

@hans2103 CSS is not really my thing so a check would be appreciated

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 1a477c51cf4e7c92d8270bfa60a77e96a6567fc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42691">issues.joomla.org/tracker/joomla-cms/42691</a>.</sub>

**Comment by laoneo** [comment]
Having a file with a long name wrapps the media manager like:
image

With the patch, everything looks normal:
image

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1a477c51cf4e7c92d8270bfa60a77e96a6567fc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42691">issues.joomla.org/tracker/joomla-cms/42691</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42691">issues.joomla.org/tracker/joomla-cms/42691</a>.</sub>

**Comment by MacJoom** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks - please close the issue this was created for

**Comment by Mich-es** [comment]
Thanks!

**Pull request merged**
