### PR TITLE
[4.3] Duplicate/missing field

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Remove duplicated field
fix missing field

### Testing Instructions
Create an admin menu
Create an admin menu item of type system alias
Go to the Link Type tab

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e6e6a099ef4e542ddcfdb85183e74e08c7cfcb46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41350">issues.joomla.org/tracker/joomla-cms/41350</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e6e6a099ef4e542ddcfdb85183e74e08c7cfcb46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41350">issues.joomla.org/tracker/joomla-cms/41350</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41350">issues.joomla.org/tracker/joomla-cms/41350</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
