### PR TITLE
[4.1] s/cloack/cloak

### PR DESCRIPTION
**Pull request by brianteeman**
Spelling - the oldest one yet at 11 years

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a2841316e8becfa39fd8718833a78fa926e1e330<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36827">issues.joomla.org/tracker/joomla-cms/36827</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a2841316e8becfa39fd8718833a78fa926e1e330<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36827">issues.joomla.org/tracker/joomla-cms/36827</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36827">issues.joomla.org/tracker/joomla-cms/36827</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
