### PR TITLE
[4.2] Correct size of template files to upload

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Quite a while ago, there was a PR https://github.com/joomla/joomla-cms/pull/10944 that changed the size of template upload files from 2MB to 10MB.

To date, the localization string has not been changed.

It's probably better for us not to use the size in the wording so as not to mislead users for such a long time. I suggest using a similar phrase in file  [lib_joomla.ini](https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/language/en-GB/lib_joomla.ini):

`JLIB_MEDIA_ERROR_WARNFILETOOLARGE="This file is too large to upload."`

Actually, I also used its formulation in PR.

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on e05283e0c2c245bd10b54ba0bb8893a8a8b5a741<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38459">issues.joomla.org/tracker/joomla-cms/38459</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e05283e0c2c245bd10b54ba0bb8893a8a8b5a741<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38459">issues.joomla.org/tracker/joomla-cms/38459</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38459">issues.joomla.org/tracker/joomla-cms/38459</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
