### PR TITLE
[4.0] Remove old search component

### PR DESCRIPTION
**Pull request by brianteeman**
The regular search component is not in J4

This pr removes reference to it in the help system
`administrator/index.php?option=com_admin&view=help`

Pull Request for Issue #30504 .

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6b059febc2b2b59c18af36b5522146836cadcb66<br /><br />it was possible without NPM. (?)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30506">issues.joomla.org/tracker/joomla-cms/30506</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 6b059febc2b2b59c18af36b5522146836cadcb66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30506">issues.joomla.org/tracker/joomla-cms/30506</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30506">issues.joomla.org/tracker/joomla-cms/30506</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
