### PR TITLE
[3.10] Finder plugins modify component params registry / Backport #35855

### PR DESCRIPTION
**Pull request by zero-24**
Backport #35855

### Summary of Changes

Backports the changes done for J4 here #35855 to 3.10 thanks @Denitz

### Testing Instructions

Ensure that finder content plugin is enabled.
Edit article and set any setting to non-global, i.e. "Layout", save article.

### Actual result BEFORE applying this Pull Request

Test your custom `onContentAfterSave` event executing after the finder plugin, see that the component param is article param now:
`\JComponentHelper::getComponent('com_content')->getParams()->get('article_layout')`;

### Expected result AFTER applying this Pull Request

Component param value is original.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on f5bb8087b8eab5f84d4821036ca07965a9b164f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36141">issues.joomla.org/tracker/joomla-cms/36141</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on f5bb8087b8eab5f84d4821036ca07965a9b164f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36141">issues.joomla.org/tracker/joomla-cms/36141</a>.</sub>

**Comment by Fedik** [comment]
R2C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36141">issues.joomla.org/tracker/joomla-cms/36141</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
