### PR TITLE
[4.0] re-throw the original exception

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for follow up https://github.com/joomla/joomla-cms/pull/30642/files#r488220693.

### Summary of Changes
re-throw the original exception for  ArticleModel and ContactModel

### Testing Instructions
code review
and/or same test as #30642 and for article

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 443dd9ece059d484352b7992a79bc667f960e4cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30653">issues.joomla.org/tracker/joomla-cms/30653</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 443dd9ece059d484352b7992a79bc667f960e4cb<br /><br />It would be better to have separate exception types for the one and the other case (404 and others) instead of checking the code all the time to decide if to re-throw or not.

But that's beyond the scope of this PR.

And for now it is better to re-throw the exception here instead of creating a new, identical one, and so this PR is good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30653">issues.joomla.org/tracker/joomla-cms/30653</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30653">issues.joomla.org/tracker/joomla-cms/30653</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
