### PR TITLE
[4.0] Replace link by a button for the dismiss button

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Replace < a Tag by the correct < button Tag 

### Testing Instructions
Code inspection.

### CODE REVIEW

**Comment by Quy** [comment]
Code looks good. How to get to the screen to see it in action?

**Comment by chmst** [comment]
The modal appears if there are ambiguous transitions between workflow stages - rather sophisticated. I will try to create a test instruction.

**Comment by chmst** [comment]
Testing this requires a workflow with at least: One stage in condition unpublished and two stages in condition published. 
If an article has the unpublished stage: Go to aticles overview. 
Select the article in the checkbox, then use the Action button in the toolbar and try tu publish the article. This is an ambiguous situation and a module appears where the user can choose one of the possible stages. 
change-action-publish


When I tested this, everything worked as expected. 
Now the modal disappears at once, which is another issue.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8b9f93030e4d49c68b3cc5c821c46a5e5e4a5d9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23740">issues.joomla.org/tracker/joomla-cms/23740</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 8b9f93030e4d49c68b3cc5c821c46a5e5e4a5d9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23740">issues.joomla.org/tracker/joomla-cms/23740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23740">issues.joomla.org/tracker/joomla-cms/23740</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
