### PR TITLE
[4.0] Use namespaced classes in Finder, namespace route helper

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Replace alias uses with namespaced classes.
Namespaces `FinderHelperRoute`.

### Testing Instructions

Run Smart Search Index.
Use Smart Search in frontend.
Inspect `com_finder` pages in backend.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 179860bf0f129bf9ec8532a97a8f72ff7c1bab36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27601">issues.joomla.org/tracker/joomla-cms/27601</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2bba488dcd2057dbdb55f3cccfda81ca01d560a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27601">issues.joomla.org/tracker/joomla-cms/27601</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6a61d63497b592c3d310ce5f577a8afe04b45eed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27601">issues.joomla.org/tracker/joomla-cms/27601</a>.</sub>

**Comment by softforge** [comment]
Followed instructions and works as before

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on 6a61d63497b592c3d310ce5f577a8afe04b45eed<br /><br />Followed instructions and works as before<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27601">issues.joomla.org/tracker/joomla-cms/27601</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27601">issues.joomla.org/tracker/joomla-cms/27601</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Is this one ok to be merged, or is there something missing? To me it looks ok.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
