### PR TITLE
[4.0] Fix mod_articles_latest

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #30445 .

### Summary of Changes
Add a filter.condition for published articles to mod_articles_latest.

### Testing Instructions
See the related #30445 .

### Actual result BEFORE applying this Pull Request
Unpublished articles are shown in the Module mod_articles_latest.

### Expected result AFTER applying this Pull Request
Only published articles are shown in the Module mod_articles_latest.

### Documentation Changes Required
no

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Is there any reason why state/condition filter is called `filter.published` in backend and `filter.condition` in backend?

**Comment by chmst** [comment]
@SharkyKZ I don't know. The filter should have the same name as in J3.x for 3rd party extensions. This is a quick fix for the issue.

**Comment by paternax** [comment]
It works like it should with this patch

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c1498f4372138216ef667a87b7a5a70ec9b67093<br /><br />Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT

See comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30459">issues.joomla.org/tracker/joomla-cms/30459</a>.</sub>

**Comment by richard67** [comment]
> It works like it should with this patch

@paternax Does it mean you have tested this pull resuest with success? If so, could you mark your test result on the issue tracker? Just follow this link https://issues.joomla.org/tracker/joomla-cms/30459 and then use the "Test this" button. Then select your appropriate test result ("succes" in this case) and submitt. Thanks in advance.

**Comment by sandewt** [comment]
>Is there any reason why state/condition filter is called filter.published in backend and filter.condition in backend?

```$model->setState('filter.published', 1)``` DOESN'T WORK !


This following code works as alternative for: ```$model->setState('filter.condition', 1);```

```
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
...
$model->setState('filter.condition', ContentComponent::CONDITION_PUBLISHED);
```
[EDIT]
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30459">issues.joomla.org/tracker/joomla-cms/30459</a>.</sub>

**Comment by SharkyKZ** [comment]
@chmst So it should be `filter.published`. I guess https://github.com/joomla/joomla-cms/pull/29235 just forgot to make replacements in frontend models. Maybe @bembelimen or @HLeithner knows.

**Comment by chmst** [comment]
Then it would be good th have this merged soon. And make complete change for the filter name.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30459">issues.joomla.org/tracker/joomla-cms/30459</a>.</sub>

**Comment by HLeithner** [comment]
Yes seems like we oversee this, it should be `filter.published` iirc there should be no _condition_ keyword more in frontend.

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on c1498f4372138216ef667a87b7a5a70ec9b67093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30459">issues.joomla.org/tracker/joomla-cms/30459</a>.</sub>

**Comment by richard67** [comment]
@HLeithner So this one here is ok so far, and the rest can be fixed with a new PR?

@chmst Can you do that?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30459">issues.joomla.org/tracker/joomla-cms/30459</a>.</sub>

**Comment by chmst** [comment]
@richard67 I'll prepare a PR for that

**Comment by wilsonge** [comment]
Merging this one as above then. Thanks!

**Pull request merged**
