### PR TITLE
Fix undefined key in HTMLDocument setBuffer

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Fix undefined key in HTMLDocument setBuffer

### Testing Instructions
Apply patch.
Enable error reaporting.
Add to index.php of any template:
```php
$this->setBuffer('<h1>FooBar</h1>', ['type' => 'component']);
```
Navigate to any page with this template.

### Actual result BEFORE applying this Pull Request
Warning message: accesing undefinend key.

### Expected result AFTER applying this Pull Request
No warning, the page render "Foobar" heading.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
No warnings however in the browser's console.

**Comment by Fedik** [comment]
Yes, that is expected, because the test instruction overrides whole component output, and every srcipt will be broken.
But that only for testing setBuffer method, so all good :wink:

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 17e7a663c02dbb09c7522b7207ac6ec8e3d831b6<br /><br />Tested successfully in Joomla 4.3.10-dev of 16 March in PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40081">issues.joomla.org/tracker/joomla-cms/40081</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 17e7a663c02dbb09c7522b7207ac6ec8e3d831b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40081">issues.joomla.org/tracker/joomla-cms/40081</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by obuisard** [comment]
Thank you Fedir @Fedik :-)

**Pull request merged**
