### PR TITLE
[4.0] com_privacy New request

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the new request form for com_privacy to match the J4 standards and style
(administrator/index.php?option=com_privacy&view=request&layout=edit)
Changed the toolbar button to Save & Close instead of Save

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 366537bda6d0e686d4ae65be84d8bb6af1d7df70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25746">issues.joomla.org/tracker/joomla-cms/25746</a>.</sub>

**Comment by Quy** [comment]
Does #24188 apply here?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 366537bda6d0e686d4ae65be84d8bb6af1d7df70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25746">issues.joomla.org/tracker/joomla-cms/25746</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
