### PR TITLE
[4] s/mixed/boolean

### PR DESCRIPTION
**Pull request by PhilETaylor**
Aint no body got time for `mixed` in 2021 :)

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8cf6bd9137e7b32f9e2a8683e4447f83f6ece518<br /><br />boolean<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35258">issues.joomla.org/tracker/joomla-cms/35258</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8cf6bd9137e7b32f9e2a8683e4447f83f6ece518<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35258">issues.joomla.org/tracker/joomla-cms/35258</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35258">issues.joomla.org/tracker/joomla-cms/35258</a>.</sub>

**Comment by wilsonge** [comment]
Aint no body got time for "Aint no body got time" comments in 2021 :P :P 

But thanks anyhow :)

**Pull request merged**
