### PR TITLE
Core.js AJAX method

### PR DESCRIPTION
**Pull request by Fedik**
In the pull request a couple methods which allow to work with Events, and do AJAX request.
That allow to write some basic JavaSript without additional JavaSript library.
#### Testing Instructions

Add in `index.php` of Isis template the button:

``` html
<button id="my-button">button</button>
```

And in `template.js`:

``` javascript
Joomla.domReady(function(){
    var button = document.getElementById('my-button');

    function myClickHandler (event){
        console.log('You just clicked', event.target || event.srcElement);
        testRequest();

        button.removeEventListener('click', myClickHandler);

        button.addEventListener('click', function(){
            alert('Click me again!');
        });
    }

    function testRequest(){
        Joomla.request({
            url: 'index.php?option=com_content',

            onBefore: function(xhr){
                console.log('Before:', xhr.readyState);
            },
            onSuccess: function(response, xhr){
                alert('Page title is ' + response.match(/<title[^>]*>([^<]+)<\/title>/)[1]);
            },
            onError: function(xhr){
                alert('Error:' + xhr.status + ' ' + xhr.statusText);
            }
        });
    }

    button.addEventListener('click', myClickHandler);
});
```

then click on the button:
- on first click you should get an alert with page title of `'index.php?option=com_content` "Page title is Articles ..."
- on second click you should get an alert with `Click me again!`

Then try change `url: 'index.php?option=com_content',` to `url: 'index.php?option=com_foobar',`.
After first click you should get an alert with "Page not found"

Ping @dgt41 @andrepereiradasilva @roland-d

### CODE REVIEW

**Comment by mbabker** [comment]
My first feeling here is do we really want to go the route of writing a Joomla JavaScript framework and be 100% independent of dependencies that we're already loading and shipping?  I get the value for some of our other utilities, but replacing `jQuery.ajax()`?  Unless we're aiming for a headless CMS in 4.0 (and all of the UI stuff is basically deferred to templates only), this just seems like doing stuff for the sake of doing it.

**Comment by Fedik** [comment]
I seen stuff where jQuery used only for catch `domReady`, and load a whole library just for it is a bit strange 

> Joomla JavaScript framework

That would be fun 😄

**Comment by mbabker** [comment]
I honestly don't see the need to invent new APIs and wheels to do stuff that is already being done with existing code and resources, even if it does mean a dependency to a library that people seem to hate being loaded for some reason.  I'm all for using native JavaScript where it makes sense and where it doesn't create overly complex code (knowing we're still supporting IE8), but right now I'm not convinced that a homegrown replacement for `jQuery(document).ready()` or `jQuery.ajax()` is in our best interests.  Maybe during the 4.0 development cycle where older browser support can be dropped that opinion could sway, but right now I think our time is better invested elsewhere.

Honestly in general I'm not a fan of how many times I see it suggested that Joomla writes its own solution when there is already a functional and supported solution either already shipped with Joomla or available to be easily consumed.  Ya there's some risk with including third party dependencies, but the more we build in house and the more Joomlaisms we create the harder it is to maintain our code base or have it in a state where folks can easily implement it.  Even worse is when the suggestion to just fork the third party resource and maintain it ourselves comes around.

**Comment by andrepereiradasilva** [comment]
I agree with @mbabker when it says there are several cases were `Joomla writes its own solution when there is already a functional and supported solution either already shipped with Joomla or available to be easily consumed` but for me this is not the case.

I agree with @Fedik on this, there are several case jQuery is only used for events or ajax calls and i prefer to always use a vanilla js aproach. For js performance reasons a vanilla js is always better than using jQuery.
I will test this when i have time.

**Comment by andrepereiradasilva** [comment]
@Fedik tested your example and works fine, but i also tried to add this and didn't totally work:

```php
JFactory::getDocument()->addScriptDeclaration("
Joomla.addListener(window, 'load', function ()
{
	var xhr = Joomla.request({
		url: 'index.php?option=com_foobar',
		onBefore: function(xhr){ console.log('Before:', xhr.readyState); },
		onSuccess: function(response, xhr){ alert('Page title is ' + response.match(/<title[^>]*>([^<]+)<\/title>/)[1]); },
		onError: function(xhr){ Joomla.ajaxErrorsMessages(xhr); }
	});
});
");
```

Js Console log
```
Before: 1
core.js:1 GET /administrator/index.php?option=com_foobar 404 (Component not found.)
core.js:1 Uncaught TypeError: Cannot read property 'replace' of undefined
```

Is something wrong with my code or other thing?

**Comment by Fedik** [comment]
it because `Joomla.JText._('JLIB_JS_AJAX_ERROR_OTHER')` do not return the translation, because it do not exists.
you also need to call: `JText::script('JLIB_JS_AJAX_ERROR_OTHER')` if I right

**Comment by andrepereiradasilva** [comment]
sorry my mistake, was sleeping before this works fine!:


```php
// Load JavaScript message titles
JText::script('ERROR');
JText::script('WARNING');
JText::script('NOTICE');
JText::script('MESSAGE');

// Add strings for JavaScript error translations.
JText::script('JLIB_JS_AJAX_ERROR_CONNECTION_ABORT');
JText::script('JLIB_JS_AJAX_ERROR_NO_CONTENT');
JText::script('JLIB_JS_AJAX_ERROR_OTHER');
JText::script('JLIB_JS_AJAX_ERROR_PARSE');
JText::script('JLIB_JS_AJAX_ERROR_TIMEOUT');

JFactory::getDocument()->addScriptDeclaration("
Joomla.addListener(window, 'load', function ()
{
    var xhr = Joomla.request({
        url: 'index.php?option=com_foobar',
        onBefore: function(xhr){ console.log('Before:', xhr.readyState); },
        onSuccess: function(response, xhr){ alert('Page title is ' + response.match(/<title[^>]*>([^<]+)<\/title>/)[1]); },
        onError: function(xhr){ Joomla.renderMessages(Joomla.ajaxErrorsMessages(xhr)); }
    });
});
");
```

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a1ae34ca98ec8509c61ab6ba8f5d72fb4f04ce70<br /><br />Works fine and IMHO a much needed PR!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11585">issues.joomla.org/joomla-cms/11585</a>.</sub>

**Comment by C-Lodder** [comment]
This will definitely need to be tested in IE8. If I rightly remember, don't older IE versions need a small pollyfill for functions like `removeListener` and `addListener`?

**Comment by Fedik** [comment]
it already should work in IE, but testing is required 😉

**Comment by dgt41** [comment]
@Fedik I think I agree to some extend with @mbabker, but that doesn't mean that I disagree completely with this PR.
My point of view is that Joomla should not start creating own functionality for something that is already given in ecmascript6. So let's say for addEventListener, this works for every modern browser except IE8! OK then, **let's use that** and polyfill the missing part for IE. At the end we end up at the same result BUT we re using the STANDARDS from ECMA and probably none of the PLT (in their right mind) should object on that (I mean ECMA6 is already killing jQuery, open your eyes and don't put the project to the same position as with mootools/jquery)!
Recap: instead of introducing Joomla's own weird functions let's embrace the ECMA6 and fill the gaps for IE8 (for as long as this browser exists as a supported thing from the project)

**Comment by andrepereiradasilva** [comment]
as usual the real problem here is IE ...

**Comment by dgt41** [comment]
@andrepereiradasilva I am just saying **let's use vanilla js** _AND_ polyfill what IE is missing. In matter of fact we don;t even have to code that as those polyfills already exist

**Comment by dgt41** [comment]
@andrepereiradasilva we could even use JBrowser to add the polyfill only for IE

**Comment by andrepereiradasilva** [comment]
do you mean something like if ie load ecma6shim.js?
The same way we do it for html5shim ?

**Comment by Fedik** [comment]
ok, I can remove `Joomla.(add/remove)Listener` and just add fallback for IE for `(add/remove)EventListener`

about polyfill, it can be only with client side check, because JBrowser will fail for 100% when Joomla behind caching proxy.

**Comment by Fedik** [comment]
I have removed Joomla.(add/remove)Listener and  added very simple fallback for IE for `Element.(add/remove)EventListener`, but it is pour fallback  :neckbeard:  
There still a small difference in event object. In theory it should be enough for our basic needs but, it like a half-worked solution.
 
So no idea, maybe can leave `ajax` and `domReady`, but remove other event stuff. Or include one of existing polyfill in the core, but it doesn't  sounds as good idea 😄

**Comment by andrepereiradasilva** [comment]
if i understand correctly for the webApi you use something like this
```js
document.addEventListener('DOMContentLoaded', function() {

	this.getElementById('myElement1Id').addEventListener('click', function() {
		alert('clicked 1');
	});

	this.getElementById('myElement2Id').addEventListener('click', function() {
		alert('clicked 2');
	});
});
```
For what i understand this doen't work only in IE8 right?

**Comment by Fedik** [comment]
> For what i understand this doesn't work only in IE8 right?

yes, and maybe in IE9, not remember

**Comment by andrepereiradasilva** [comment]
so reggarding events we "just" needd to polyfill (add/remove)eventlistener and domcontentloaded for IE8 and all should work.

ajax is another matter

**Comment by andrepereiradasilva** [comment]
doesn't hsi does that? https://github.com/WebReflection/ie8

we can include the polyfill only in ie8, like we do for html5shim, something like

```html
<!--[if lt IE 9]><script src="/media/jui/js/ie8polyfill.js"></script><![endif]-->
```

**Comment by andrepereiradasilva** [comment]
what do you guys think?

**Comment by Fedik** [comment]
unfortunately it will not work that easy, because `<!--[if lt IE 9]>..` must be manually added in the template, and we cannot force it
so if template do not contain this then or scripts will be broken in old IE

**Comment by andrepereiradasilva** [comment]
Doesn't that also happens with html5 js?

**Comment by andrepereiradasilva** [comment]
See https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/index.php#L130

**Comment by andrepereiradasilva** [comment]
> and we cannot force it

when we need, we can
```php
$doc->addCustomTag('<!--[if lt IE 9]><script src="/media/jui/js/ie8polyfill.js"></script><![endif]-->');
```

**Comment by ggppdk** [comment]
> unfortunately it will not work that easy, because <!--[if lt IE 9]>.. must be manually added in the template, and we cannot force it, so if template do not contain this then or scripts will be broken in old IE

since the code is really small, why not add inside **core.js**,
and then add it inside an if statement
```
var userAgent = navigator.userAgent.toLowerCase();
var IEversion = (userAgent.indexOf('msie') != -1) ? parseInt(userAgent.split('msie')[1]) : false;
var isIE8 = IEversion ? IEversion < 9 : false;

if (isIE8)
{
...
}
```

also a little off topic, maybe we are are adding too many small JS files

**Comment by C-Lodder** [comment]
@ggppdk - Using @andrepereiradasilva's method above is better than checking the user agent. Also means it doesn't need to manually be added to the template. Personally, I'd suggest combining **all** IE8 pollyfills and shivs into 1 JS file and simply use the following in core templates:

```
<!--[if lt IE 9]>
    <script src="/media/jui/js/ie8.js"></script>
<![endif]-->
```

Either that or park this PR until J4.x when supporting IE8 may not be required in core, but instead the template providers.

**Comment by andrepereiradasilva** [comment]
> also a little off topic, maybe we are are adding too many small JS files

I see no problem with that.

Also, after SPDY, the web is moving to HTTP 2.0 (finaly!!) and HTTP 2.0 does multiplexing of requests so from what i understand there is no bottleneck in a browser downloading a lot of js/css files from the same server.

**Comment by ggppdk** [comment]
Yes, ok, 
@andrepereiradasilva 

you mean add it here ?
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/behavior.php#L87

```
JFactory::getDocument()->addCustomTag(
  '<!--[if lt IE 9]><script src="/media/jui/js/ie8polyfill.js"></script><![endif]-->'
);
JHtml::_('script', 'system/core.js', false, true);
```

**Comment by Fedik** [comment]
> Doesn't that also happens with html5 js?

html5 js do not contain any logic we use, it just for browser to help to understand new tags 😉

**Comment by andrepereiradasilva** [comment]
> you mean add it here ?
> https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/behavior.php#L87

if we use add/removeEventListener + DOMContetnLoaded in the core.js ...

What i'm saying is adding a JHtml behaviour to add that custom tag

```php
public static function ie8()
{
	// Only load once
	if (isset(static::$loaded[__METHOD__][$selector]))
	{
		return;
	}

	// Include IE8 ployfill
	JFactory::getDocument()->addCustomTag('<!--[if lt IE 9]><script src="/media/jui/js/ie8polyfill.js"></script><![endif]-->');
	
	// Set static array
	static::$loaded[__METHOD__][$selector] = true;
}
```

them whenerver you use add/removeEventListener + DOMContetnLoaded polyfill you call that dependency first.
```php
JHtml::_('behavior.ie8');
```

**Comment by andrepereiradasilva** [comment]
@Fedik @dgt41 @C-Lodder @ggppdk what do you guys think about this?

**Comment by C-Lodder** [comment]
Yup, that sounds like a good idea. 

`JHtml::_('behavior.ie8');` should also load `html5shiv.js`.

One thing that needs to happen though is, these script should be loaded before any other script

**Comment by andrepereiradasilva** [comment]
> One thing that needs to happen though is, these scripts should be loaded before any other script

for that you need to change JDocumentRendererHtmlHead output order
See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer/html/head.php#L310

**Comment by ggppdk** [comment]
What about
```
JHtml::_('behavior.extend'); 
```

or similar ?
in near furture version of Joomla the inclusion of IE8 specific stuff will be removed

**Comment by andrepereiradasilva** [comment]
for me is ok

**Comment by andrepereiradasilva** [comment]
so for what i understand from this discussion we need to separed things:

- joomla ajax request method in the core.is one thing. and IMO it should be in core.js
- an events ie8 polyfill is another thing.

So this should be two different PR's not related. @Fedik do you agree?

**Comment by Fedik** [comment]
yes, better to split these things,
I will remove the event stuff from current pull request

**Comment by Fedik** [comment]
I have removed the events stuff, and updated the testing instruction

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on d00041772ed764d3ea2d0664961fa9e03d5d09ac<br /><br />Works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11585">issues.joomla.org/joomla-cms/11585</a>.</sub>

**Comment by dgt41** [comment]
RTC Let's wait for PLT

**Comment by andrepereiradasilva** [comment]
ok so this PR will be only for the core.js ajax request.

we will need a other PR for the events + DOMContentLoaded IE8 polyfill 
@dgt41 @Fedik so how do you think it's better to proceed with this part?

**Comment by dgt41** [comment]
@andrepereiradasilva if you are about to do that can you use:
```php
$scriptPath = JHtml::_('script', 'media/jui/js/ie8polyfill.js', false, true, true, false, true); // return only path
  // Include IE8 polyfill
    JFactory::getDocument()->addCustomTag('<!--[if lt IE 9]><script src="' . $scriptPath . '"></script><![endif]-->');

```

**Comment by Fedik** [comment]
well, find a good polyfill and use condition comment as you suggested,
one of hundert https://github.com/WebReflection/ie8 
there also was @dgt41 suggestions

hard to chose 😉

**Comment by andrepereiradasilva** [comment]
i am not `about to do it`. you guys have more knowledge in this than i do.

**Comment by dgt41** [comment]
I suggested https://github.com/jonathantneal/Polyfills-for-IE8

**Comment by andrepereiradasilva** [comment]
you mean this https://github.com/jonathantneal/polyfill/blob/master/polyfills/Event/polyfill.js + https://github.com/jonathantneal/polyfill/blob/master/polyfills/Event/DOMContentLoaded/polyfill.js ?

**Comment by dgt41** [comment]
I fail miserably on copy-paste 😂

**Comment by andrepereiradasilva** [comment]
:)
it seems that is forked from https://github.com/Financial-Times/polyfill-service/tree/master/polyfills

**Comment by dgt41** [comment]
Yeah Financial-times don;t use native mobile apps instead they use plain javascript. Most of their code is available on github. Thus the polyfill need I guess

**Comment by andrepereiradasilva** [comment]
and this licence is usable with current joomla policy (i honestly don't have a clue)

**Comment by dgt41** [comment]
MIT should be fine (I have no clue either)

**Comment by mbabker** [comment]
MIT's fine.  Otherwise the Symfony code we're shipping would have to come out.

**Comment by brianteeman** [comment]
What @mbabker said MIT is fine

**Comment by andrepereiradasilva** [comment]
so will this be RTC ?

**Comment by dgt41** [comment]
@andrepereiradasilva ok RTC down to PLT then

**Comment by dgt41** [comment]
RTC

**Comment by dgt41** [comment]
@joomla-bot

**Comment by Fedik** [comment]
@yvesh do you have a tip how to write a tests for AJAX requests? 
and also be able test the HTTP errors while request.

**Comment by yvesh** [comment]
@Fedik Take a look at the [sendtestmail tests](https://github.com/joomla/joomla-cms/blob/staging/tests/javascript/sendtestmail/spec.js), they [mock](https://github.com/joomla/joomla-cms/blob/staging/tests/javascript/sendtestmail/spec-setup.js) the http requests.

Ping me if i should explain more :)

**Comment by Fedik** [comment]
@yvesh  thanks for the links.
Other small question. How to debug stuff inside the test? I tried `console.log` but nothing in the console output

**Comment by yvesh** [comment]
@Fedik use console.info or jasmine.log

**Comment by rdeutz** [comment]
@Fedik could you have a look at the conflicts and resolve them, thanks!

**Comment by Fedik** [comment]
done, just conflict of minified versions

**Pull request merged**
