### PR TITLE
[com_fields] Add a note field from the #__fields_groups table to the field list query

### PR DESCRIPTION
**Pull request by rigin**
Pull Request for Issue # .

Note fields are useful for transferring data to a template or to third-party extensions

### Summary of Changes
Added the group_note field to the field list output request

### Testing Instructions
When you receive a list of material fields from the FieldsHelper :: getFields method, the group_note field should appear in the elements

### Expected result

When you receive a list of material fields from the FieldsHelper :: getFields method, the group_note field should appear in the elements

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
Honestly I don't see the use case, but the change will harm nobody.

**Comment by rigin** [comment]
For example -  a  module - a plugin for creating filters by fields that will be bound to fields by means of a label located in note.
I actively use this technique with this CCK http://fieldsattach.com/

**Comment by brianteeman** [comment]
As we now have custom fields I dont see the need for this.

**Comment by roland-d** [comment]
@brianteeman This is not related to custom fields, @rigin only adds an existing field to the SQL query. 

Like @laoneo I don't see any harm in adding this field.

**Comment by Tchangue** [comment]
I have tested this item :white_check_mark: successfully on 898ec93cf492551adf4b9ab76b5c86d077890a0d<br /><br />@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15808">issues.joomla.org/tracker/joomla-cms/15808</a>.</sub>

**Comment by fatmaakay** [comment]
I have tested this item :white_check_mark: successfully on 898ec93cf492551adf4b9ab76b5c86d077890a0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15808">issues.joomla.org/tracker/joomla-cms/15808</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by roland-d** [comment]
Merged with commit d46391e0c63e518bd9ba69c60b54923e7205880f

**Comment by fatmaakay** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15808">issues.joomla.org/tracker/joomla-cms/15808</a>.</sub>

**Comment by fatmaakay** [comment]
I have tested this item :white_check_mark: successfully on 898ec93cf492551adf4b9ab76b5c86d077890a0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15808">issues.joomla.org/tracker/joomla-cms/15808</a>.</sub>

**Pull request closed without merging**
