### PR TITLE
Check for a 'default' element as well as 'default' attribute

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .
### Summary of Changes

When getting the default value for a form element, first check if the `<field>` node has a child `<default>`. Use the value of the `<default>` node if it exists, otherwise use the the `default` attribute.

The main value of this will be in conjunction with field types such as `subform` which take their default values as json. Writing correct json into an xml attribute kind of sucks as you must use a lot of `&quot;` and the whole thing gets very long and illegible. By using a dedicated node, you can simply wrap the json inside of `<![CDATA[]]>` and write it normally. So, instead of:

``` xml
<field type="subform" name="myfield" default="{&quot;myfield0&quot;:{&quot;key1&quot;:&quot;value1",&quot;key2&quot;:&quot;value2&quot;},&quot;myfield1&quot;:{&quot;key1&quot;:&quot;value3",&quot;key2&quot;:&quot;value4&quot;},&quot;myfield2&quot;:{&quot;key1&quot;:&quot;value5",&quot;key2&quot;:&quot;value6&quot;}}" /> 
```

You could have:

``` xml
<field type="subform" name="myfield">
    <default><![CDATA[
    {
        "myfield0": {"key1": "value1", "key2": value2},
        "myfield1": {"key1": "value3", "key2": value4},
        "myfield2": {"key1": "value5", "key2": value6}
    }
    ]]></default>
</field>
```
### Testing Instructions

Create a field and give it a `<default>` element as a child. Load the form and notice that the value of the `<default>` node is used for your field. 
### Documentation Changes Required

Probably.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 08fa8254aabc55853361010f62e2dc0c2bfebb95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12451">issues.joomla.org/tracker/joomla-cms/12451</a>.</sub>

**Comment by Fedik** [comment]
cool idea, also it allow to add huge text as default value for `textarea`, `editor`, more easy

**Comment by Fedik** [comment]
test example for `textarea`:
```xml
<field type="textarea" name="myfield1" class="input-xxlarge" rows="6">
  <default><![CDATA[
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Cras risus velit, malesuada ut feugiat semper, blandit sit amet velit.
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  ]]></default>
</field>
```

**Comment by laoneo** [comment]
I like this but I think the check should flipped, first check if there is a default attribute and then check for a default node. Just to be 100% BC safe :anguished:

**Comment by laoneo** [comment]
Just asked myself, do we even need a `<default>` tag? Would that not also also work:
```
<field type="textarea" name="myfield1" class="input-xxlarge" rows="6">
  <![CDATA[
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Cras risus velit, malesuada ut feugiat semper, blandit sit amet velit.
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  ]]>
</field>
```

**Comment by Fedik** [comment]
@laoneo and how about subform then, with changes from another pull?
```xml
<field type="subform" name="myfield">
    <![CDATA[
    [
       {"key1": "value1", "key2": value2},
       {"key1": "value3", "key2": value4},
       {"key1": "value5", "key2": value6}
    ]
    ]]>
   <form>
            <field name="key1"  label="key1"  type="text" />
            <field name="key2"  label="key2"  type="text" />
    </form>
</field>
```

looks not very good without `<default>`,
I think use `<default>` tag is a good idea.

**Comment by laoneo** [comment]
True...

**Comment by okonomiyaki3000** [comment]
@laoneo You might be right about precedence. It's not likely to make any difference but it could, in theory. 

Anyone else agree it should be flipped or see a reason why it shouldn't?

**Comment by Fedik** [comment]
I think flipping will be more safe, in case if some extension already use `<default>` tag in own needs

**Comment by okonomiyaki3000** [comment]
Finally I got around to changing the precedence.

**Comment by Fedik** [comment]
@okonomiyaki3000 it is works, if formsource is external file, 
but broken when the form source is "children":

```xml
<field type="subform" name="myfield" multiple="true">
  <default><![CDATA[
[
        {"key1": "value1", "key2": "value2"},
        {"key1": "value3", "key2": "value4"},
        {"key1": "value5", "key2": "value6"}
]
]]></default>
	<form>
	  <field name="key1"  label="key1"  type="text" />
	  <field name="key2"  label="key2"  type="text" />
	</form>
</field>
```

@laoneo maybe you have an idea?

**Comment by okonomiyaki3000** [comment]
@Fedik The problem here is in `JFormFieldSubform::setup()`

```php
if (!$this->formsource)
{
	// Set the formsource parameter from the content of the node
	$this->formsource = $element->children()->saveXML();
}
```

This is too flexible. A proper implementation would be like this:

```php
if (!$this->formsource && $element->form)
{
	// Set the formsource parameter from the content of the node
	$this->formsource = $element->form->saveXML();
}
```

Changing it now may break BC. I will check a little. However, your example can work if the `<default>` and `<form>` elements are swapped. As long as `<form>` is first, it will be fine.

**Comment by okonomiyaki3000** [comment]
Maybe it does not need to be seen as a break since, even now, only a `<form>` element will actually work there.

**Comment by okonomiyaki3000** [comment]
OK, so here's the fix. Technically, it's a change to current behavior. 

__Before__
A subform with no formsource will get its formsource from its children. 
The first child must be a `<form>` element or the field will be broken in some way. 
Any subsequent children (`<form>` or otherwise) will have no effect on the field.

__After__
A subform with no formsource will get its formsource from its first `<form>` child.
Any child node other than the first `<form>` will just be ignored.

Essentially, any subform definition that currently works will continue to work just the same. Some definitions which are currently broken (should such things exist at all), may be fixed.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 078a86cc9664ec2eaea6abce4311f6a8735ffa78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12451">issues.joomla.org/tracker/joomla-cms/12451</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Fedik can you please test again?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 529f83f4d0721def6fc04e3106589c6290940aab<br /><br />Tested it with custom fields with #16659. If this one gets in, #16659 will be ready to be tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12451">issues.joomla.org/tracker/joomla-cms/12451</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 529f83f4d0721def6fc04e3106589c6290940aab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12451">issues.joomla.org/tracker/joomla-cms/12451</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by laoneo** [comment]
As this one get in now, can you guys please test #16659. Would be nice to support that feature in custom fields, would make the default value attribute much more stable.

**Pull request merged**
