### PR TITLE
[4.0] Change sort options to match columns order

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Go to Components > Smart Search > Content Maps
Click Sort Table By dropdown
See that sort options are in the same order as columns

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e49a2a845dd5e5f782a440c7fe99db6133fc7019<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26283">issues.joomla.org/tracker/joomla-cms/26283</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 383582ffd245c2a0ff99c70a3502703e99031354<br /><br />After applying the patch, the options follow the order of the columns.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26283">issues.joomla.org/tracker/joomla-cms/26283</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
