### PR TITLE
Use JHtmlBootstrap in front-end editing

### PR DESCRIPTION
**Pull request by n9iels**
#### Summary of Changes

This PR replaces the hard coded bootstrap tabs in com_content.form with `JHtml::_("bootstrap.tab")`. The advantage of this change is that we can override this library to use Bootstrap 3 for example.
#### Testing Instructions
1. Log in on the front-end and edit an article
2. Make sure all the tabs are working correctly
3. Apply this PR
4. Make sure all the tabs are still working correctly

### CODE REVIEW

**Comment by brianteeman** [comment]
Are you sure they were bootstrap tans before? What happens now if you have
a non bootstrap template?

**Comment by C-Lodder** [comment]
Could you use a more specific selector other than `myTab`? I think I've seen this in other places in Joomla so it could cause conflicts

**Comment by n9iels** [comment]
@brianteeman yes i'm sure the were Bootstrap tabs. The code generated by the JHtml library is exactly the same as it was before. So nothing will change after this update.

@C-Lodder Good point, I changed the selector to `com-content-form`

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 029e1a02d8dfebed05fede8e1bd044c201f866d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11562">issues.joomla.org/joomla-cms/11562</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 029e1a02d8dfebed05fede8e1bd044c201f866d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11562">issues.joomla.org/joomla-cms/11562</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 029e1a02d8dfebed05fede8e1bd044c201f866d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11562">issues.joomla.org/joomla-cms/11562</a>.</sub>

**Comment by roland-d** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11562">issues.joomla.org/joomla-cms/11562</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/32766cdd017fb35d0a2fcaa49e6234413aaee56b - Thanks!

**Pull request closed without merging**
