### PR TITLE
[4.3] Button text color issue

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue #40306

### Summary of Changes

Changes some code in _global.scss file

### Testing Instructions

- See #40306
- See #40420
- Build: npm ci
- Clear the browser cache (historie) after the patch if necessary

### Actual result BEFORE applying this Pull Request

Text NOT continues to be read.

### Expected result AFTER applying this Pull Request

Text continues to be read.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Thanks @joomlaphp and @dgrammatiko

### CODE REVIEW

**Comment by sandewt** [comment]
@dgrammatiko for clarity

I used this code:

```
  &:not(.btn):hover,
  &:not(.btn):focus {
    color: var(--cassiopeia-color-hover);
  }
```
Instead of the code from your comment, see https://github.com/joomla/joomla-cms/issues/40306#issuecomment-1498784720
Because this last one caused an npm error.

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 3399b30ee1738a5f96cea4816f5b93f9eef7d46a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40435">issues.joomla.org/tracker/joomla-cms/40435</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 3399b30ee1738a5f96cea4816f5b93f9eef7d46a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40435">issues.joomla.org/tracker/joomla-cms/40435</a>.</sub>

**Comment by sandewt** [comment]
_Drone: Build is failing_ 
Does this have to do with this pr or just ignore this message?

**Comment by sandewt** [comment]
@joomlaphp

> I made the changes in the templates/site/cassiopeia/scss/blocks/_global.scss file. Do I need to make changes to another file as well?
Browser cookies + Joomla cookies cleared.

> Please, give your comment here https://github.com/joomla/joomla-cms/pull/40435

Here you will find information about testing: https://docs.joomla.org/Testing_Joomla!_patches

**Comment by sandewt** [comment]
I would benefit from testing this pr, thanks in advance.

@joomlaphp

**Comment by joomlaphp** [comment]
> I would benefit from testing this pr, thanks in advance.
> 
> @joomlaphp

Hi,

No problem as there is no link:: `<button type="button" class="btn btn-primary">Primary</button> `

The problem persists after the link is given. All cookies etc. I cleaned: `<a class="btn btn-primary" href="#" role="button">Link</a>`

I'm good at CSS and I can fix it with user.css but it's so annoying :)
Regards

**Comment by sandewt** [comment]
> The problem persists after the link is given. All cookies etc. I cleaned:

Did you run **npm ci** after installing the patch ?

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 26b30098306dbd1dde8516275bc395fb9117ef25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40435">issues.joomla.org/tracker/joomla-cms/40435</a>.</sub>

**Comment by N6REJ** [comment]
RTC

**Comment by obuisard** [comment]
Thank you for the PR @sandewt :-)

**Comment by sandewt** [comment]
Thanks all.

**Comment by sandewt** [comment]
> This needs to be reverted as it caused https://github.com/joomla/joomla-cms/pull/41153 and https://github.com/joomla/joomla-cms/issues/41172

That's just the question. These both issues (#41153 and #41172) are easy to solve with some extra css code.

**Comment by sandewt** [comment]
> This needs to be reverted as it caused https://github.com/joomla/joomla-cms/pull/41153 and https://github.com/joomla/joomla-cms/issues/41172

I'm looking for a solution, my finding is the following:

The :not() CSS pseudo-class represents elements that do not match a list of selectors. See: [https://developer.mozilla.org/en-US/docs/Web/CSS/:not](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)

In this case these are the buttons (.btn) that are excluded, what the desired behavior is. See the code below.
```
a:not(.btn):hover, a:not(.btn):focus {
  color: var(--cassiopeia-color-hover);
}
```

So it's strange (irrelevant) that elements in the footer that have nothing to do with a button, act on it.

This justifies not undoing this pr.

@brianteeman what is your opinion ? Do you have another solution for this pr ?

**Comment by brianteeman** [comment]
you misunderstood the css

```
a:not(.btn):hover, a:not(.btn):focus {
  color: var(--cassiopeia-color-hover);
}

```
in english that says

> when you hover over any link that is not a button then set the color to blue

So the color of the links in the footer and the back-to-top (which is a link not a button) change to blue when you hover.

**Comment by brianteeman** [comment]
They did not before because they were set by the css

```
.footer a {
    color: currentColor;
}
```

but the change made in this PR override that

**Comment by sandewt** [comment]
> but the change made in this PR override that

That's why I want to extend the css, because I have no other solution for this PR.

```
.footer a, .footer a:focus, .footer a:hover {
  color: currentColor;
}
```

**Comment by obuisard** [comment]
Have you tried to add?
```
.footer a:not(.btn):hover, .footer a:not(.btn):focus {
  color: currentColor;
}
```

**Comment by sandewt** [comment]
>Have you tried to add?

Yes, I have replaced this pr with your code proposal.
And it works. 👍

**Comment by sandewt** [comment]
> Have you tried to add?

If you meant this suggestion only for the footer, we'd better have the discussion here: #41172

**Comment by obuisard** [comment]
> > Have you tried to add?
> 
> If you meant this suggestion only for the footer, we'd better have the discussion here: #41172

No, I meant to add the specific code for the footer to complement this PR and fix all related issues at once.

**Comment by jackal-kr** [comment]
> > This needs to be reverted as it caused #41153 and #41172
> 
> That's just the question. These both issues (#41153 and #41172) are easy to solve with some extra css code.

Hello, i have those two also after upgrade to 4.3.3 - can you please help me with the workaround in user.css? I am new to css and joomla so that fixing myself will take some time... thanks a lot!

also any idea, when these two will be fixed? in 4.4.4?,,,

**Comment by sandewt** [comment]
> Have you tried to add?

Yes, but not with the desired result.

> No, I meant to add the specific code for the footer to complement this PR and fix all related issues at once.

Sorry  @obuisard , it's not quite clear to me what you mean. If you would like to make the PR in question. I'll test.

**Comment by obuisard** [comment]
> also any idea, when these two will be fixed? in 4.3.4?

No, it won't, the version is already in RC phase, any fix will have to do to 4.3.5.

**Comment by obuisard** [comment]
> Sorry @obuisard , it's not quite clear to me what you mean. If you would like to make the PR in question. I'll test.

Ok, I'll give it a try (probably not today) and see if can come up with a fix that takes care of everything.

**Comment by obuisard** [comment]
I was started to look for a solution to fix this, but, to be honest, I cannot even replicate the initial issue stated in #40306.

image

My fix, in this instance, would be to revert this PR, as suggested by Brian @brianteeman early on.

Ugur @joomlaphp, before we do such a thing, could you share the URL of the site where you had the issue in the first place? I don't want to dismiss any issue and I need to see if your initial issue was not related to something else.

**Comment by sandewt** [comment]
>This needs to be reverted as it caused https://github.com/joomla/joomla-cms/pull/41153 and https://github.com/joomla/joomla-cms/issues/41172

I think this is the overall solution:

Change the code fo this pr
```
a:not(.btn):hover, a:not(.btn):focus {
  color: var(--cassiopeia-color-hover);
}
```
in
```
a:not([class]):hover, a:not([class]):focus {
  color: currentColor;
}
```

We (@RickR2H and I) have tested this code in the PBF.

**Comment by sandewt** [comment]
>I was starting to look for a solution to fix this, but, to be honest, I cannot even replicate the initial issue stated in https://github.com/joomla/joomla-cms/issues/40306.

@obuisard I can reproduce this issue in J4.3.5-dev, see:

Schermafbeelding 2023-08-27 105721

Method:
Create a custom module in the banner position, with the following button code:
`<p><a class="btn btn-success" href="#!">Get started</a></p>`

I changed the code to the original one:
\joomla\build\media_source\templates\site\cassiopeia\scss\blocks\_global.scss

```
Line 63:
&:hover,
  &:focus {
    color: var(--cassiopeia-color-hover);
  }
```
Run: npm ci

**Comment by sandewt** [comment]
> I think this is the overall solution:

I am waiting for response(s), if ok then I will make a new PR.

**Comment by obuisard** [comment]
> I am waiting for response(s), if ok then I will make a new PR.

Yes, if you make a new PR to fix the issue, then we can have people test it. Thanks @sandewt !

**Comment by sandewt** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/41749

**Pull request merged**
