### PR TITLE
Added login background setting

### PR DESCRIPTION
**Pull request by ghost**
As a continuation of the discution at https://github.com/joomla/joomla-cms/pull/6340 this PR does:
- Adds a new `Login Background Colour` setting to the isis template, defaulting at `#224C8F`
- Adds the `custom.css` stylesheets to the `login.php` and `component.php` as done for the `index.php` here: https://github.com/joomla/joomla-cms/pull/3709

Result:

### CODE REVIEW

**Comment by JoomliC** [comment]
Hi @nonumber So, if adding this option for color, maybe the possibility too to used a custom image as background ? (as it is possible for logo)

Just a suggestion... ;-)

**Comment by nonumber** [comment]
You can do that via the ```custom.css```.
I don't see it as something that should be a ready-to-use setting.

**Comment by JoomliC** [comment]
@nonumber so you can remove all styling options then!
Just a remark: how many people using Joomla know how to code css file, and how many future potential Joomla users will know ?
ready-to-use === more users ;-)

**Comment by nonumber** [comment]
With that same logic, you could/should add styling settings for every possible element and colour.
I don't see adding a background image to the login page as something that is useful to the larger public at all.

But that is a totally separate discussion. You can add an issue on the tracker or discuss it in the Joomla forum.

This PR focusses on the background colour only.

**Comment by JoomliC** [comment]
@nonumber : forgot my suggestion, but i won't open a new PR for this.
Just that i didn't mean options for all styling (a designer/coder vision) but basical ones (a basic joomla user with zero skill in coding) (this one will only ask for simple changes, not advanced one ;-) ).
If you add an option for login pack background color, you will find people to ask for the possibility to use an image as background (but less chance of this if there's no option at all ;-) )
Not sure to be clear, as not always easy to explain what could be a end-user behavior.
But i'm sure that you have already faced people asking more options for a feature after you've added this one. But before addition of this feature, no one asked for the options. ;)

With the same logic of the addition of a custom css file for login page as for the one for index.php, no need to add options for colors, as not needed by users with skills in editing a custom css file.

But i will stop trolling this PR ;-)

**Comment by Bakual** [comment]
> how many people using Joomla know how to code css file

Those who really care about a background image, usually know how to add it :smile:

**Comment by JoomliC** [comment]
@Bakual Exactly! The same for the color ;-) I was maybe not enough clear in my first post...

**Comment by mbabker** [comment]
You gotta draw the line somewhere on how many options there are to customize the UI within the UI.  We add an option to customize the login screen color or add a background image, why not add one for the form background, or the login button, or to change the icons on the inputs?  Personally I fall into the "why do we even have these options in the UI anyway, make a CSS file!" camp but I recognize some people will respond with "what's CSS?".  The color options are a big enough compromise and I don't think we need to go further than that.

**Comment by JoomliC** [comment]
@mbabker :+1: 
I agree that if options, more ones will be requested by users who don't know what CSS is.
And to be honnest, i don't really like the way those styling are added to the index.php.
A custom.css (and no color options) seems better.

My opinion : 
- if 1 option for background color (a full page background, not button) it's better to have an option for using an image too.
- BUT better with no option at all!

**Comment by jmccabe** [comment]
It seems to me that @JoomliC (and possibly @mbabker) is saying don't bother adding this because it'll just lead to people asking for more unnecessary stuff to be added. Is that right? I personally don't see any point in adding an extra option but it might be nice to update the text for the Nav Bar Option to mention that it also controls the login background colour.

**Comment by JoomliC** [comment]
@jmccabe Yes, that's it! ;-)

**Comment by Bakual** [comment]
For me it's ok to add one more color. I can see that this could be helpful to match the color to a brand or to improve contrast or whatever.
But I certainly don't want an option to add a background image (which leads to repeated or not, centered or not, ...)
Keep it simple. Everything beyond that can be achieved with extensions.
We will be thankful for that simple code the next time we look at it again to fix something :smile:

**Comment by dgt41** [comment]
Wouldn’t it be better if we provide a variables_user.less file that if exists will override the variables.less and thus no more options for colors etc on the template. Just a button to initiate the generation of the template.css will be enough, and you have all the customization options you need! No custom.css no php arguments inside the index.php. Think about it!

**Comment by mbabker** [comment]
That option would mean that we couldn't provide CSS updates with core Joomla updates as those would overwrite the user customizations.

**Comment by Bakual** [comment]
You would still need the custom.css file.
And it actually would complicate code once more with a hidden feature nobody knows anything about.

**Comment by dgt41** [comment]
@mbabker Mike I am talking about variables.less not template.less. Also we can (i think so) initiate the generates.php at the end of the update procedure provided that generatecss.php also takes account of the variables_user.less.
And if we want to take it to another level we can make a page with all the options of the variables_user.less, so even the clueless can customize the template just by selecting colors etc

**Comment by dgt41** [comment]
@Bakual You are right custom is also needed for 3PD code, so it’s not clever to remove it 😄

**Comment by mbabker** [comment]
Isn't that essentially what the features in the Template Manager enable?  You can't overwrite template.css, but you can sure add your custom.css and tweak the entire template through that.  You can also copy the entire template, and now your only concern is keeping it in sync with core at new releases.

I miss the days where there weren't any of these options in the UI.  Now we're all sitting here debating about how many color options there should be in the template's config and how we can add more to our already less-than-optimal update system.  `</reminiscing>`

**Comment by nonumber** [comment]
PS: there are currently 2 colour settings I would like to get removed in a future PR: `Sidebar Colour` and `Link Colour`.
This because we want to make isis as accessible as possible, also regarding colour contrasts. Being able to customize the link colours makes this near impossible.

Mind you, this is the admin template we are talking about.
It's nice if people can give it their own little spin, but we want to keep the basic styling as fixed as possible. Not only because this is the identity of Joomla, but also because of screenshots in documentation and books.

**Comment by nonumber** [comment]
@dgt41 getting into custom less files and triggering the less compiler is way beyond this PR.
If you want to discuss/code that, then please make a different PR/issue for it.

**Comment by dgt41** [comment]
@nonumber sorry for hijacking your PR 😃
Will try to do another with my idea of custom variables.less

**Comment by jmccabe** [comment]
Interestingly, @nonumber, I was talking about books earlier to someone. It's nice when you buy a book about a product and the book content actually looks like what you see when you're using that product. It helps give you, as a reader, learner and user, that you're doing things right. This is part of the reason why I got a bit carried away on your removing gradients PR.

**Comment by davdebcom** [comment]
@test
Works, finally I can change my background when logging in, I have wanted this forever, a major pain point has been removed. 

:-P<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by davdebcom** [comment]
But seriously, good work Peter!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by nonumber** [comment]
:)

**Comment by larapetersen** [comment]
@test Works!
@nonumber Love it! :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by dam-man** [comment]
@test working :) Needed cache refresh.. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by dam-man** [comment]
Testing the same item triple..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by zero-24** [comment]
RTC'ing here :smile: Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by brianteeman** [comment]
Why are you removing the reference to the default value from the tooltip? This is useful for people who want to go back to the original settings

Also you are removing a string. I know it may seem daft but we usually dont remove any strings as they might be used by other developers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6703">issues.joomla.org/joomla-cms/6703</a>.</sub>

**Comment by nonumber** [comment]
The thought about removing the default value from the description is that these string had the wrong value, because they had changed. Also this is something that might change in future too.
It feels daft to have to state the default value and have to update all language strings which is really something that is subject to change. Result would be that you don't really know if translations are stating the correct value.

Also, the default value returns if you just empty the field and save it. So it doesn't seem like important information.

Regarding the removal of a language string. Good point. Didn't think about the use of these outside J! core.
I placed it back.

**Comment by brianteeman** [comment]
If the default value returns them I guess its ok.

**Comment by infograf768** [comment]
Even if the colour value changes, it may be useful to keep stating that:
"If left blank, the default value will be used."

**Comment by brianteeman** [comment]
Yes I think that is a good idea

On 3 May 2015 at 07:45, infograf768 <notifications@github.com> wrote:

> Even if the colour value changes, it may be useful to keep stating that:
> "If left blank, the default value will be used."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6703#issuecomment-98443839>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nonumber** [comment]
Done.

**Comment by nonumber** [comment]
So is this good to go? Already RTC...

**Comment by wilsonge** [comment]
Merged to 3.5 branch

**Comment by nonumber** [comment]
Thanks :)

**Pull request closed without merging**
