### PR TITLE
[4.0] Correct filtering by access level in Page Navigation plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31220.

### Summary of Changes

Fixes filtering by access level in Content - Page Navigation plugin.

### Testing Instructions

Install Blog Sample Data.
View "About" article in frontend as a guest.

### Actual result BEFORE applying this Pull Request

"Next" button is shown, clicking it leads to an unauthorised article:

>You don't have permission to access this. Please contact a website administrator if this is incorrect.

### Expected result AFTER applying this Pull Request

"Next" button is not shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 683db36f443ecf35985135a2f52bdceddb761bca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31223">issues.joomla.org/tracker/joomla-cms/31223</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 683db36f443ecf35985135a2f52bdceddb761bca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31223">issues.joomla.org/tracker/joomla-cms/31223</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31223">issues.joomla.org/tracker/joomla-cms/31223</a>.</sub>

**Comment by richard67** [comment]
Drone and Appveyor failures seem to me not to be related to this PR but to the testing environment. => Ping @Hackwar .

**Pull request merged**
