### PR TITLE
Add description to a move/copy operation in batch process form

### PR DESCRIPTION
**Pull request by yild**
### Summary of Changes

This PR will add description to a move/copy label text in batch process modal forms for Content, Menus, Banners, News feeds and Tags. ATM all controls except move/copy have a description on that form.
### Testing Instructions

Go to Content->Articles, select item and go to batch modal form, hover over label above move/copy category selection control - there wont be any tooltip.
Go to Menus -> All menus items, select an item, go to batch modal form, hover over label above move/copy category selection control - there wont be any tooltip.

Apply this PR - again check above instructions - new description tooltip should be visible.

Same instruction for Content->Categories, Banners, Banners->Categories, Contacts, Contacts->Categories, News feeds, News feeds->Categories.
### Documentation Changes Required

Modified key JLIB_HTML_BATCH_MENU_LABEL value in en-GB.lib_joomla.ini and en-GB.com_menus.ini

Added new keys JLIB_HTML_BATCH_MENU_LABEL_DESC to en-GB.lib_joomla.ini and en-GB.com_menus.ini

Modified/added key strings may need some adjustments to correct grammar/syntax.

### CODE REVIEW

**Comment by bhavikTailored** [comment]
- I have tested successfully and attached Screen shot.
-screen shot 2016-08-24 at 05 25 57<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 80e789e1b935e942b1d1804600f11d7397bbbb1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 80e789e1b935e942b1d1804600f11d7397bbbb1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by BhaveshTailored** [comment]
## screen shot 2016-08-24 at 05 32 17Your title here...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I dont see this as an improvement - you've just manipulated the text to let you create a tooltip which isnt needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for your contribution but I am closing this. The wording of the label was very deliberately chosen and ties directly in to the default option in the dropdown list. This change breaks that behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11770">issues.joomla.org/joomla-cms/11770</a>.</sub>

**Pull request closed without merging**
