### PR TITLE
[J5.2] Cassiopeia - Only add margin to system message container if it contains a joomla-alert

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue #40639.

### Summary of Changes
Added a :has rule to control the margin of the system-message-container if it does not contain a <joomla-alert> tag
:has selector is supported by all modern browsers

grafik

### Testing Instructions
login with wrong credentials in your cassiopeia frontend. 
A system message appears that the login data is wrong
Click the close button to hide the message

### Actual result BEFORE applying this Pull Request
After hiding a system alert, a margin of 1rem remains

### Expected result AFTER applying this Pull Request
After hiding a system alert, the margin is not present anymore

### Link to documentations

Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 97d020908cf2431984ab1a4e820786ac4370addd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44222">issues.joomla.org/tracker/joomla-cms/44222</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 97d020908cf2431984ab1a4e820786ac4370addd<br /><br />with NPM Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44222">issues.joomla.org/tracker/joomla-cms/44222</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44222">issues.joomla.org/tracker/joomla-cms/44222</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 97d020908cf2431984ab1a4e820786ac4370addd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44222">issues.joomla.org/tracker/joomla-cms/44222</a>.</sub>

**Comment by pe7er** [comment]
Thanks @coolcat-creations !

**Comment by coolcat-creations** [comment]
Thank you for merging!

**Pull request merged**
