### PR TITLE
File too large

### PR DESCRIPTION
**Pull request by brianteeman**
This pr changes the message to inform the site owner that they can change the limits in the components options.

Note it only changes the strings in the admin as the information is not useful to a front end user

### Before
image

### After

image

The easiest way I found to test was to change the option from the default 10MB to 1MB

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4a0eb844e09dbc0c4f4aaab8a9bb3a77fbbd2d68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38622">issues.joomla.org/tracker/joomla-cms/38622</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4a0eb844e09dbc0c4f4aaab8a9bb3a77fbbd2d68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38622">issues.joomla.org/tracker/joomla-cms/38622</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38622">issues.joomla.org/tracker/joomla-cms/38622</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
