### PR TITLE
[4.0][com_tags] Fix "Too few arguments to function PlgContentJoomla::onContentBeforeSave". Add $data to event_before_save

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23401, https://github.com/joomla/joomla-cms/issues/23529

### Test
- J4 nightly. Try to save a tag.
```
Error:
Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in /joomla-cms/libraries/src/Plugin/CMSPlugin.php on line 287 and exactly 4 expected
```
- Apply patch and try again.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on bfae4a5af49e39f87dc33cdb1d97f779d6f67b6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23531">issues.joomla.org/tracker/joomla-cms/23531</a>.</sub>

**Comment by infograf768** [comment]
We have the same error when we save a Menu
`Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in /Applications/MAMP/htdocs/installmulti/joomla40/libraries/src/Plugin/CMSPlugin.php on line 287 and exactly 4 expected `
Was'nt there a discussion somewhere about $data?

**Comment by ChristineWk** [comment]
@infograf768 



> 
> 
> We have the same error when we save a Menu
> `Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in /Applications/MAMP/htdocs/installmulti/joomla40/libraries/src/Plugin/CMSPlugin.php on line 287 and exactly 4 expected `
> Was'nt there a discussion somewhere about $data?

yes, see here please: https://github.com/joomla/joomla-cms/pull/23395

**Comment by wojsmol** [comment]
@infograf768 $data is now required see https://github.com/joomla/joomla-cms/pull/23293#issuecomment-450033939.

**Comment by ReLater** [comment]
> We have the same error when we save a Menu

We **had** the same error but @Wilsonge fixed it in a way that I copied here ;-)
@joomdonation pushed me in the right direction. Some more infos: https://github.com/joomla/joomla-cms/issues/23276

**Comment by wilsonge** [comment]
Thanks :)

**Comment by infograf768** [comment]
I guess it may have been lost in translation...
We still HAVE (not HAD) the same error for menu.
Here is the patch:
https://github.com/joomla/joomla-cms/pull/23535

Was just hesitating between `$data` and `$data = array()`

**Pull request merged**
