### PR TITLE
Update JFormFieldSQL to use JDatabaseQuery

### PR DESCRIPTION
**Pull request by fastslack**
### Use JDatabaseQuery

This PR update the JFormFieldSQL input field to use JDatabaseQuery with separated query elements.
Into your form xml file you can set the query using this way:

```
<field name="example_group" 
type="sql" 
label="COM_EXAMPLE_GROUP" 
sql_select="e.*" 
sql_from="#__example AS e" 
sql_group="name" 
sql_order="e.id ASC" 
key_field="id"
value_field="name" 
onchange="this.form.submit();" />
```

This example will recreate this query:

```
SELECT e.* FROM #__example AS e GROUP BY name ORDER e.id ASC
```
### Filters

One posibility that offer use JDatabaseQuery instead the old way is to have a way to get "inline" filters. That mean that if you have multiple dropdowns as filter in your list view, its posible that you need to connect it togheter.

For example, we have 2 dropdowns that filter our list, one called "groups", another called "subgroups":

```
<field name="groups" 
type="sql" 
label="COM_EXAMPLE_GROUP" 
sql_select="e.*" 
sql_from="#__example_groups AS e" 
sql_group="name" 
sql_order="e.id ASC" 
key_field="id"
 value_field="name" 
onchange="this.form.submit();" />
```

And the second:

```
<field name="subgroups" 
type="sql" 
label="COM_EXAMPLE_GROUP" 
sql_select="e.*" 
sql_from="#__example_subgroups AS e" 
sql_group="name" 
sql_order="e.id ASC" 
sql_filter="groups"
key_field="id"
 value_field="name" 
onchange="this.form.submit();" />
```

Note that we added **sql_filter="groups"**, that search for groups changes and set the condition if its founded. So we can have a 'inline' filter on our lists. This will recreate:

```
SELECT e.* FROM #__example_subgroups AS e WHERE `groups` = 99 GROUP BY name ORDER e.id ASC
```

### CODE REVIEW

**Comment by chmst** [comment]
Works only with correct syntax. Otherwise - Warnings or destroyed Template <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3476">issues.joomla.org/joomla-cms/3476</a>.</sub>

**Comment by fastslack** [comment]
@chmst can you give me an example? because i think that the current sql field destroy the template if syntax is wrong too

**Comment by chmst** [comment]
You are right - the behaviour is the same if a query is not well formed. 
I've repeated the test - and with your query it works. 
But I could not add a where clause. So this feature is not very useful for me.
Maybe you can expand your code?

			
		<field
			 name="test" 
			 type="sql" 
			 label="test" 
			 query="select c.id, c.title from #__content as c where c.title like '%Begleitservice%'"
			 key_field="id"
			 value_field="title" 
			 onchange="this.form.submit();"
			/>
makes a dropdown with 2 entries as expected for my database.

		<field
			 name="test" 
			 type="sql" 
			 label="test" 
			 sql_select="c.id, c.title" 
			 sql_from="#__content as c" 
			 sql_where="c.title like '%Begleitservice%'"
			 sql_group="c.title" 
			 sql_order="c.id ASC" 
			 key_field="id"
			 value_field="title" 
			 onchange="this.form.submit();"
			/>

gives the whole list of entries in the table.

**Comment by fastslack** [comment]
Of course, i ll check this. Thanks for testing!

**Comment by zero-24** [comment]
@fastslack did you get time to check the `where` as suggested by @chmst ?

**Comment by fastslack** [comment]
@chmst can you re-test with latest Joomla! version? Because i cannot reproduce the issue, the sql filters works fine for me

**Comment by fastslack** [comment]
@chmst please test now, sorry about the delay

**Comment by chmst** [comment]
Hi, I did it - and it was successful. I tested on a database with > 1000 articles and both variats, the old and the new one gave the same result: 
    <field
         name="test-new" 
         type="sql" 
         label="test" 
         sql_select="c.id, c.title" 
         sql_from="#__content as c" 
         sql_where="c.title like '%Bayrischzell%'"
         key_field="id"
         value_field="title" 
        />
	
 <field
         name="test-old" 
         type="sql" 
         label="test old" 
         query="select c.id, c.title from #__content as c where c.title like '%Bayrischzell%'"
         key_field="id"
         value_field="title" 
        />

Note: I did not test join ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3476">issues.joomla.org/joomla-cms/3476</a>.</sub>

**Comment by zero-24** [comment]
@fastslack i have just also retetsted with the codes above.

But i know it is hard to tell but Travis is again not happy.

```
1) JFormFieldSQLTest::testGetInput
Undefined property: JFormFieldSQL::$header
/home/travis/build/joomla/joomla-cms/libraries/joomla/form/fields/sql.php:79
/home/travis/build/joomla/joomla-cms/libraries/joomla/form/fields/sql.php:273
/home/travis/build/joomla/joomla-cms/libraries/joomla/form/fields/list.php:58
/home/travis/build/joomla/joomla-cms/libraries/joomla/form/field.php:393
/home/travis/build/joomla/joomla-cms/libraries/joomla/form/fields/sql.php:82
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/form/fields/JFormFieldSQLTest.php:108
phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/TextUI/Command.php:152
phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/TextUI/Command.php:104
```
https://travis-ci.org/joomla/joomla-cms/jobs/61804403

It looks like he is not happy with the new `$header` option?

**Comment by fastslack** [comment]
@zero-24 Seems that Travis is happy now :-D

**Comment by zero-24** [comment]
Thanks @fastslack Based on the tests here i move to RTC. :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3476">issues.joomla.org/joomla-cms/3476</a>.</sub>

**Comment by mbabker** [comment]
Merged to `3.5-dev` via 30a953e

**Pull request closed without merging**
