### PR TITLE
[4.0] Update files/folders to remove

### PR DESCRIPTION
**Pull request by brianteeman**
Post #32933 update the list of files and folders in script.php

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 324a206e38278326dd4195bc5703300d18b2ad97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32942">issues.joomla.org/tracker/joomla-cms/32942</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 324a206e38278326dd4195bc5703300d18b2ad97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32942">issues.joomla.org/tracker/joomla-cms/32942</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32942">issues.joomla.org/tracker/joomla-cms/32942</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
