### PR TITLE
[4] Show better message on restoring from versions

### PR DESCRIPTION
**Pull request by PhilETaylor**
Its not pretty and I dont like it, but it works.

Pull Request for Issue #35257

### Summary of Changes

Translates date according to `DATE_FORMAT_LC3` at all times
show `No version note` if there was no version note to fulfil a placeholder and not leave a trailing period after a space. 

### Testing Instructions

restore an item from content history

### Actual result BEFORE applying this Pull Request

1) The "Saved on" date show from `$model->getState('save_date')` doesnt respect my language file date format

2) if there was no `$model->getState('version_note')` to show something like `(No Version Note)` instead of a space that then pushes the period looking odd. 

Screenshot 2021-08-20 at 16 47 16

Caused by language string:

```ini
JLIB_APPLICATION_SUCCESS_LOAD_HISTORY="Prior version restored. Saved on %s %s."
```

https://github.com/joomla/joomla-cms/blob/55b02c923b65dc9016a3f82671bb9bd9177e2e4d/libraries/src/Versioning/VersionableControllerTrait.php#L91

```php
$this->setMessage(
Text::sprintf(
  JLIB_APPLICATION_SUCCESS_LOAD_HISTORY', $model->getState('save_date'), $model->getState('version_note')
  )
);
```

### Expected result AFTER applying this Pull Request

Screenshot 2021-08-22 at 17 40 59
Screenshot 2021-08-22 at 17 40 55

### CODE REVIEW

**Comment by brianteeman** [comment]
~Your screenshot shows why this change to remove time is not a good idea~

**Comment by PhilETaylor** [comment]
> Your screenshot shows why this change to remove time is not a good idea

By using the language string [you yourself chose](https://github.com/joomla/joomla-cms/issues/35257#issuecomment-902931790) from the [list of available translated dates](https://github.com/joomla/joomla-cms/issues/35257#issue-975727511) I provided... I give up.

**Comment by PhilETaylor** [comment]
Now Changed to `DATE_FORMAT_LC2` so that a time is provided. 

Screenshot 2021-08-22 at 18 09 14
Screenshot 2021-08-22 at 18 09 09

**Comment by Quy** [comment]
The Version Note column displays `No version note` even when there is a note.

**Comment by PhilETaylor** [comment]
> The Version Note column displays No version note even when there is a note.

I cannot replicate that sorry.

Screenshot 2021-08-30 at 15 18 47

Screenshot 2021-08-30 at 15 18 54

**Comment by Quy** [comment]
Stupid me entered in `Note` and not `Version Note`. Sorry for the noise.

**Pull request closed without merging**
