### PR TITLE
[4.0] Fixing searchtools in xtd plugins in frontend (partial fix)

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28119

### Summary of Changes
This PR adds searchtools to frontend cassiopea in order to display correctly and use the filters (Filter Options, Clean) when using XTD plugins when editing an article.

It solves correctly the Contact XTD as well as Menu XTD
It also solves tooltips in the search field.

**It does NOT solve entirely the issue for Article filters as well as Module filters**
This would need a PR by another volunteer to deal with these fields.

### Testing Instructions
Edit an article in frontend and use the various XTDs. Try to display or not filters, etc.

### Before patch

Screen Shot 2020-03-06 at 10 46 26
Screen Shot 2020-03-06 at 10 46 11
Screen Shot 2020-03-06 at 10 45 50
Screen Shot 2020-03-06 at 10 45 25

### After patch

Screen Shot 2020-03-06 at 10 42 19_after
Screen Shot 2020-03-06 at 10 41 59
Screen Shot 2020-03-06 at 10 41 11
Screen Shot 2020-03-06 at 10 40 54

### Note
I may have added more variables than necessary as well as svg. This can be solved after a next PR which would entirely correct the Article and Module filter fields

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a5898e56676034af34682cd9e7a9b37f9370f9f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28248">issues.joomla.org/tracker/joomla-cms/28248</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a5898e56676034af34682cd9e7a9b37f9370f9f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28248">issues.joomla.org/tracker/joomla-cms/28248</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28248">issues.joomla.org/tracker/joomla-cms/28248</a>.</sub>

**Comment by infograf768** [comment]
I also at last found the reason of the broken fields in XTD module frontend.
xml is wrong
patch would be
```
diff --git a/components/com_modules/forms/filter_modules.xml b/components/com_modules/forms/filter_modules.xml
index 37df5bb..4e0e9bb 100644
--- a/components/com_modules/forms/filter_modules.xml
+++ b/components/com_modules/forms/filter_modules.xml
@@ -1,6 +1,4 @@
 <?xml version="1.0" encoding="utf-8"?>
-<form>
-	<fieldset addfieldpath="/administrator/components/com_modules/models/fields" />
-
+<form addfieldprefix="Joomla\Component\Modules\Administrator\Field">
```

As soon as this PR is merged, will make a specific PR for that.

**Comment by infograf768** [comment]
don't know why it was changed. RTC again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28248">issues.joomla.org/tracker/joomla-cms/28248</a>.</sub>

**Comment by infograf768** [comment]
Note: Changes to filter_articles.xml (frontend) will correct the display of the fields concerned. In next PR.

This does not mean ALL css is corrected/improved (including RTL), but it lets work on these for cassiopea.

**Comment by infograf768** [comment]
@wilsonge 
Please let's get this in to be able to work further.

**Comment by alikon** [comment]
> don't know why it was changed. RTC again

cause i missed your last sentence

> As soon as this PR is merged, will make a specific PR for that.

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
@alikon @richard67 
First PR ready to test
https://github.com/joomla/joomla-cms/pull/28283

**Pull request merged**
