### PR TITLE
[4] remove unused import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 609aafd675beaa6cfc625ab52242932e49bc2f64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35411">issues.joomla.org/tracker/joomla-cms/35411</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 609aafd675beaa6cfc625ab52242932e49bc2f64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35411">issues.joomla.org/tracker/joomla-cms/35411</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35411">issues.joomla.org/tracker/joomla-cms/35411</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
