### PR TITLE
[3.10] "I do not agree" for two more plugins

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
By analogy with https://github.com/joomla/joomla-cms/pull/37181 (https://github.com/joomla/joomla-cms/issues/22198) for Joomla 3.10, I added lines for two more plugins.

It was:

Screenshot_1

### CODE REVIEW

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on d92f57eba06ed2bfdbaf52d3aa13e5e29d01de61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37346">issues.joomla.org/tracker/joomla-cms/37346</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on d92f57eba06ed2bfdbaf52d3aa13e5e29d01de61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37346">issues.joomla.org/tracker/joomla-cms/37346</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37346">issues.joomla.org/tracker/joomla-cms/37346</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks.

**Comment by joomleb** [comment]
Hi guys,
maybe this #37645 related Cassiopea "fix" could be "merged" too...

**Pull request merged**
