### PR TITLE
[4.1] Create Child Template Button

### PR DESCRIPTION
**Pull request by brianteeman**
Renames the button to clarify that its an action and not a link etc

### After
image

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b17138f4bb95347a7cc49fe9dd8d64ed12fb9744<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36228">issues.joomla.org/tracker/joomla-cms/36228</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on b17138f4bb95347a7cc49fe9dd8d64ed12fb9744<br /><br />@brianteeman will the official name be `Child Templates`?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36228">issues.joomla.org/tracker/joomla-cms/36228</a>.</sub>

**Comment by brianteeman** [comment]
@dgrammatiko No idea, above my paygrade

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36228">issues.joomla.org/tracker/joomla-cms/36228</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
