### PR TITLE
Fix the return url in the login form

### PR DESCRIPTION
**Pull request by cdekok**
… of the full url https://...

This fixes the return page after login.
The full url option was removed due to a security fix according to this page: https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F#Overriding

### Summary of Changes

Changed the return url to be index.php?Itemid=x instead of the full url.

### Testing Instructions

Visit a restricted page, login and you are returned to the correct page, which is broken on the current 3.8.x

### Expected result

You are returned to the previous page.

### Actual result

You are returned to the homepage.

### CODE REVIEW

**Comment by csthomas** [comment]
Here is a similar change which I suggest in https://github.com/joomla/joomla-cms/pull/22229/files#diff-a17a2f629f4567e156880f91bff86ea9

You test instruction is unclear. J3.8 should work with not relative URLs.

**Comment by cdekok** [comment]
It does not work for me on 3.8.13 i do use the login form from the component, not the module.

**Comment by csthomas** [comment]
Do you have a multilingual website?

**Comment by csthomas** [comment]
The problem may be similar to https://github.com/joomla/joomla-cms/pull/19196

**Comment by cdekok** [comment]
Yes correct this was on a multilingual site

**Comment by ghost** [comment]
@csthomas any comment?

**Comment by csthomas** [comment]
I am sorry but I can not help. I'm very busy. New job and long commutes take me a lot of time.

**Comment by adtj93** [comment]
I have tested this item :white_check_mark: successfully on bb30adc0613c3c6ad9f6563191a7c641e8e17d42<br />

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on bb30adc0613c3c6ad9f6563191a7c641e8e17d42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22572">issues.joomla.org/tracker/joomla-cms/22572</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22572">issues.joomla.org/tracker/joomla-cms/22572</a>.</sub>

**Comment by zero-24** [comment]
Within this call we also could have post parameters which should not be added to the URL as they could contain sensitive data. I will close here for that reason and keep the current behavior for j3.

**Pull request closed without merging**
