### PR TITLE
Correct languages/package extensions name in install sql files

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Ths simple PR is just to correct an inconsistency in what is installed and the names of the languages/package that are in the joomal sql files.

What is installed is this:
image

So the install sqls should have that.
### Testing Instructions

Code review.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I'm not sure about this. I dont remember the links right now but there were ISO standards that were used for the naming.

**Comment by brianteeman** [comment]
I don't care myself - 

Maybe @infograf768 has an opinion

**Comment by andrepereiradasilva** [comment]
@brianteeman that is just the install files that are not consistent.
Try to install a new staging and check what are the extension names for those extensions after install.

**Comment by yild** [comment]
This should be correlated with:
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/install.xml#L3 AND
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/install.xml#L3
`name` value (IMO).

But there are those files:
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.xml#L3 AND
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.xml#L3
`name` show ISO names...

**Comment by andrepereiradasilva** [comment]
Actually have been saying that for some time ...

**Comment by infograf768** [comment]
Imho, there is no reason to use "United Kingdom" as en-GB is enough in the install.xml(s) and en-GB.xml(s) 
[btw, I just released a new version of com_localise which changes the install.xml name to the same name as the xx-XX.xml and not to the language pack name of the type `<name>French Language pack</name>` (for French) to differentiate languages and pack in the Manager.]

It is OK though, as I see it, to use "United Kingdom" in the Installation xml files in metadata <name.

**Comment by andrepereiradasilva** [comment]
ok changed in install.xml files too.

BTW, @infograf768 should it be "Language Pack" or "Language Package"? We normally use the term "Package", IIRC this is the only place where "Pack" is used.

**Comment by infograf768** [comment]
also for admin install.xml file i guess.
as for pack or package, not really important imho as long as it is different from install.xml

**Comment by andrepereiradasilva** [comment]
> also for admin install.xml file i guess.

i already changed that one.

> as for pack or package, not really important imho as long as it is different from install.xml

it's different, just asking because we use "Package" elsewhere in Joomla, but ok, will leave "Pack".

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b52f4277f68c8dfbcbdfa9b0c5dad99207bd0737<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11977">issues.joomla.org/joomla-cms/11977</a>.</sub>

**Comment by andrepereiradasilva** [comment]
closed in favour of https://github.com/joomla/joomla-cms/pull/11977 that also have this changes.

**Pull request closed without merging**
