### PR TITLE
[4.0] Remove module from sidebar in com_config

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #28674 .

### Summary of Changes
Remove position sidebar frmom com_config. 

### Testing Instructions
See issue #28674. Make a update from 3.10 to 4.0 
In J4 this PR may not change anything in the backend. 

### Expected result
The updated site looks like a fresh installation of a J4 in com_config.
In J4.0 every view of com_config looks as before

### Actual result
See issue #28674. 

### Documentation Changes Required
no

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 43f905e577ab930a5c7fe95f2670f1d41f63d3cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28699">issues.joomla.org/tracker/joomla-cms/28699</a>.</sub>

**Comment by Quy** [comment]
Please delete lines 12 & 16.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eace22acafb20281f20b4d92c16efc3740eea549<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28699">issues.joomla.org/tracker/joomla-cms/28699</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28699">issues.joomla.org/tracker/joomla-cms/28699</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
