### PR TITLE
[4.0] Fix error 404 in modern routing for links without own menu item (NomenuRules)

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

This is a copy of https://github.com/joomla/joomla-cms/pull/19280 without unit tests.

When there is no menu item for category/categories/article view in com_content and option `Remove IDs` is enabled then a link like:
- `/index.php/en/component/content/article/article-en-gb?catid=8` returns error 404

In this PR  I rewrote `NomenuRules` class to `build` and `parse` links:
- `index.php/en/component/content/article/category-en-gb/article-en-gb` (option `Remove IDs` is enabled)
- `index.php/en/component/content/article/3-category-en-gb/2-article-en-gb`

### Testing Instructions
Disable all menu items for `com_content` `categories/category/article` views.
Go to frontend `index.php/component/content/categories` and check links to category and article items.

### Expected result
Links work, no 404 when option `Remove Ids` is enabled/disabled.

### Actual result
When option `Remove Ids` is enabled then links to articles return error 404.

### CODE REVIEW

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 7ba153eadc50c129e67fb45f378b379ffe640d2b<br /><br />Links are working with and without IDs, even on a multilanguage site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20979">issues.joomla.org/tracker/joomla-cms/20979</a>.</sub>

**Comment by infograf768** [comment]
Multilingual

###NOTE: 
I am testing here after correcting the info-block and any file related in order to add the category and parent category language to `ContentHelperRoute::getCategoryRoute()` as these are missing.

[patchcontentcategory.diff.zip](https://github.com/joomla/joomla-cms/files/2332746/patchcontentcategory.diff.zip)

Wanted to make a PR with this but as it is still broken, I will wait...

Results
Setting all types of com_content article or category display (separately or together).
Making sure category and parent category (with links) are set to display in the info-block.

Clicking on the category or parent category link in the infoblock gives correct results depending on the language of the category and its parent category. 

If any is set to ALL, the urls are real bad.

I can get:
`/en/featured-en-gb?view=category&id=19` Bad
or, if I have a menu item for the article
`/en/othercatarticle?view=category&id=18` Bad

If all set to the same Content Language, it will use my hidden All Categories Menu item (alias: `allcategories-en-gb`) as base (correct result in 3.x with modern router). 
`/en/allcategories-en-gb/category-all` Good.

Briefly said, when anything set to language ALL, sef links in 4.0 are badly broken, even after this patch.

I also tested with a custom menu item to use instead of blog (With xml and all).
I can create the menu item, it will display fine, except for the info-block category and parent category where the layout is appended `&layout=cassiopeamyblog` for example...

@Hackwar  Any idea?

**Comment by csthomas** [comment]
> I can get:
> `/en/featured-en-gb?view=category&id=19` Bad
> or, if I have a menu item for the article
> `/en/othercatarticle?view=category&id=18` Bad

This is another issue, more related to reversed PR #19099 and issue at #19537.

**Comment by infograf768** [comment]
Solved here the issue with info-block and categories set to ALL languages.
Change has to be done in route.php
Will make PR for info-block as it is a separate issue than this PR

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/21916 concerning multilang
For com_content, as long as one has a `List All Categories` menu item, even hidden, no more 404 afaik.

**Comment by brianteeman** [comment]
Requiring a "hidden menu item" is not a real solution

**Comment by csthomas** [comment]
We have 2 issues, one is fixed by your PR another by this PR. Please do not mix it.
This PR is only for URL when there is no any menu item assigned.

**Comment by csthomas** [comment]
@infograf768 Can you say that you have tested this PR?

**Comment by infograf768** [comment]
let me retest in present 4.0-dev + https://github.com/joomla/joomla-cms/pull/22022

**Comment by infograf768** [comment]
@csthomas 
Multilingual:
**Settings**
If we have absolutely no menu item to com_content stuff, i.e. if we have for example a home displaying a contact or a com_search menu item.

Then using as url `index.php/component/content/categories` just gives me a `Category not found`

Now, if I use the module articles_category, it will display articles and I can click on their title link or their category link.

**After your PR, I get links like**
/en/component/content/category/category-en-gb?Itemid=112

or
/en/component/content/article/category-en-gb/article-en-gb?Itemid=112

with always the same Itemid=112 , which is the itemid of the Home page whatever the menu item displayed (a contact, a search, whatever) before clicking on the links in the articlescategory module.

**I never get the type of links you posted above**
  ` en/component/content/article/category-en-gb/article-en-gb`

**before your patch I do indeed get 404s.**

Not sure I can set the test as successful.

**Comment by csthomas** [comment]
Probably J4 start to add an Itemid everywhere, but this is not job for this PR to fix it. IMO this Itemid is redundant. @Hackwar do you want to add something?

**Comment by csthomas** [comment]
@infograf768 Your test has been successful. J4 adds `Itemid` before and after the patch.

**Comment by infograf768** [comment]
Any consideration about B/C as we had with https://github.com/joomla/joomla-cms/pull/19280 ?
@wilsonge @mbabker

**Comment by laoneo** [comment]
This here is a fix for a pretty obvious bug. As it is now ported to 4 it should be fine to be accepted as BC breaks can be tolerated.

**Comment by wilsonge** [comment]
I want the unit tests ported as well please @rdeutz can you please work with @csthomas on that. Having stable routing unit tests is going to be super important for j4 so if we do need to make any more changes in the future we can understand the impact clearly

**Comment by csthomas** [comment]
It may be hard to start as I have not found any tests on joomla routing. 
https://github.com/joomla/test-unit/ ?? 
Please contact me at glip.

**Comment by Hackwar** [comment]
Idk where the tests are now, but I wrote full tests for all routing code...

**Comment by csthomas** [comment]
They were deleted at https://github.com/joomla/test-unit/commit/f1a5ac853745399d0ba8530af8cb3eb923e7f0a8#diff-6862fb1e873b5617da1d3c4dc1447d2b

**Comment by mbabker** [comment]
Try https://github.com/joomla/test-integration (anyone got a map to actually find any of the tests anymore?)

**Comment by csthomas** [comment]
Thanks, I found. 

I see that I can use database in tests but I should not as @Hackwar mentioned in older PR.

**Comment by roland-d** [comment]
@wilsonge Should this be followed-up on?

**Comment by roland-d** [comment]
Can anybody pick this up or should we close this PR?

**Comment by chmst** [comment]
I had the same issue as described in #32248. 
The link is: ... /index.php/component/contact/contact/uncategorised/bb?Itemid=101 
SEO friendly urls is ON
index.php/component/contact/contact/uncategorised/bb?Itemid=101 

before patch: 404, after patch - the contat form is displayed with this url <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20979">issues.joomla.org/tracker/joomla-cms/20979</a>.</sub>

**Comment by richard67** [comment]
Closing in favour of #32695 .

**Pull request closed without merging**
