### PR TITLE
[4.0] DebugBar use csp nonce

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
DebugBar use csp nonce

### Testing Instructions
Apply patch and make sure the debugbar still works.

Also can look at the source code of the page, at bottom, to check that inline script of DebugBar has `nonce="blabla"` attribute.

### Expected result
`nonce="blabla"` exist

### Actual result
`nonce="blabla"` not exist

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0f5cd50354376bcb0c1242615a731d1a5bd0ad55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25727">issues.joomla.org/tracker/joomla-cms/25727</a>.</sub>

**Comment by pravinTek** [comment]
I have tested this item :white_check_mark: successfully on 0f5cd50354376bcb0c1242615a731d1a5bd0ad55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25727">issues.joomla.org/tracker/joomla-cms/25727</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25727">issues.joomla.org/tracker/joomla-cms/25727</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
