### PR TITLE
[com_fields] Remove not needed version and hits field from db schema

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #12659.

### Summary of Changes
Removes the hits and version fields from the database structure.

### Testing Instructions
All should work as before.

### CODE REVIEW

**Comment by laoneo** [comment]
@alikon you need to adapt it on the #12660 pr as well.

**Comment by alikon** [comment]
done thanks

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6e624f5854244bd1cc1063a1e881193a62b04bb5<br /><br />Looks OK.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12674">issues.joomla.org/tracker/joomla-cms/12674</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6e624f5854244bd1cc1063a1e881193a62b04bb5<br /><br />tested on postgresql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12674">issues.joomla.org/tracker/joomla-cms/12674</a>.</sub>

**Pull request merged**
