### PR TITLE
[4.0] Remove unused PLG_FIELDS_SQL_RULES_ADAPTED

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28745

### Summary of Changes & Testing Instructions
- See https://github.com/joomla/joomla-cms/pull/28757

### See also deprectation pr
- https://github.com/joomla/joomla-cms/pull/28761

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 136f8063db1dbe89f25b1a0cf56118df44ff07e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28760">issues.joomla.org/tracker/joomla-cms/28760</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 136f8063db1dbe89f25b1a0cf56118df44ff07e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28760">issues.joomla.org/tracker/joomla-cms/28760</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28760">issues.joomla.org/tracker/joomla-cms/28760</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks 👍

**Pull request merged**
