### PR TITLE
[4.0] Enable button when returning from article

### PR DESCRIPTION
**Pull request by maliouris**
New pull request for https://github.com/joomla/joomla-cms/pull/24328.
In Chromium browsers, when you check a checkbox, you follow a link and then you come back the checkbox is still checked but you can't get that information with javascript. So according to this https://stackoverflow.com/questions/33731067/checkbox-still-checked-hitting-the-back-button-but-it-has-no-checked-attribut I applied the <code> autocomplete='off' </code> and the checkboxes are no longer checked when you come back (as it currently works in Firefox)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8fb8eb773f53a1f08a02910fc3d8b44becadcf5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30498">issues.joomla.org/tracker/joomla-cms/30498</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8fb8eb773f53a1f08a02910fc3d8b44becadcf5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30498">issues.joomla.org/tracker/joomla-cms/30498</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30498">issues.joomla.org/tracker/joomla-cms/30498</a>.</sub>

**Comment by zero-24** [comment]
Thanks merging

**Pull request merged**
