### PR TITLE
Adding maxlength parameter to version_note field

### PR DESCRIPTION
**Pull request by Bakual**
### Issue

As explained in #7539 the version note will be truncated without notice if it is longer than 255 characters. That is because the database field is no bigger. See https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1724
### Solution

Add the HTML `maxlength` attribute so the user isn't able to enter more than 255 characters into the version note field
### Testing
- Add a long string (more than 255 characters) into the version note field in any of the forms supporting it. Eg article, banner, contact. Check after saving and see that the string was truncated.
  You can use this string:

```
abcdefghijklmnopqrstuvwxyz1abcdefghijklmnopqrstuvwxyz2abcdefghijklmnopqrstuvwxyz3abcdefghijklmnopqrstuvwxyz4abcdefghijklmnopqrstuvwxyz5abcdefghijklmnopqrstuvwxyz6abcdefghijklmnopqrstuvwxyz7abcdefghijklmnopqrstuvwxyz8abcdefghijklmnopqrstuvwxyz9abcdefghijklmnopqrstuvwxyz10
```
- Apply patch and try to enter the string again. See that it is truncated before saving already. You will not be able to paste the full string.

### CODE REVIEW

**Comment by brianteeman** [comment]
I guess the same should be applied to the Note field in Menus and Modules?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7541">issues.joomla.org/joomla-cms/7541</a>.</sub>

**Comment by Bakual** [comment]
True. I was just looking for the `version_note` ones. But those have the same limit in the database, so adding it there would make sense.
Same also for categories and tags.

For the module it was currently already limited to 100 characters. I tracked it back to 2010 when the note was added. No clue why it was set to 100 when the database allows for 255. I changed it to 255 now.

**Comment by RickR2H** [comment]
Test successful. The note field text gets truncated when pasted. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7541">issues.joomla.org/joomla-cms/7541</a>.</sub>

**Comment by zero-24** [comment]
Works as expected now :smile: Thanks. --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7541">issues.joomla.org/joomla-cms/7541</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @Bakual! Merged.

**Pull request merged**
