### PR TITLE
[4.0] Properly Initialize Image Editor Plugins

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- The code had a monkey patch so that the last RC didn't had to be delayed. This PR removes the monkey patch 

### Testing Instructions
Apply the PR
Check that the Media Manager Editor is initializing all the plugins correctly
Check that the plugins still work as expected

### Documentation Changes Required

No, fixing my own ugly code

@wilsonge

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 28e889ebdffaaf28cbf5d4a400cfce1c0e57c4bc<br /><br />Applied patch and execute build tools. Rotate, scale, crop all work in the media manager.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34950">issues.joomla.org/tracker/joomla-cms/34950</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 28e889ebdffaaf28cbf5d4a400cfce1c0e57c4bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34950">issues.joomla.org/tracker/joomla-cms/34950</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34950">issues.joomla.org/tracker/joomla-cms/34950</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
