### PR TITLE
[4.0] delete a duplicate string in com_mails

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

delete a duplicate string in com_mails

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 818fb0c86ea989a95bf0991846c1f56cfd0c5140<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30842">issues.joomla.org/tracker/joomla-cms/30842</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 818fb0c86ea989a95bf0991846c1f56cfd0c5140<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30842">issues.joomla.org/tracker/joomla-cms/30842</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30842">issues.joomla.org/tracker/joomla-cms/30842</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
