### PR TITLE
Re-init tinymce when sorting happen, fix #24343

### LINKED ISSUE #24343: (Subform)Repeatable editor blank after drag&drop reorder
### Steps to reproduce the issue
Create a new Field with type repeatable and add under form fields one field type Editor. Set options to be shown in a tab in article edit view. Create a new article go to the tab and add 2 rows. Write something in each editor field and save and reorder the rows.

### Expected result
After reordering the rows editor behavior is normal

### Actual result
After you release the mouse button after reordering the rows the editor field gets blank and uneditable but the content will be saved and after refresh loaded correctly.

### System information (as much as possible)
Linux apache php 7.2 and 7.3. Joomla 3.9.4. Editor JCE Pro and TinyMCE (joomla standard). Also tried it with a new clean cloud installation via launch.joomla.

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #24343 .

### Summary of Changes

Browser will clear iframe content when DOM changes, so we need to re-init the editor every time.
This fix only for Joomla 3.

Based on @ryandemmer idea, but more simple, without introducing new events.

### Testing Instructions

Apply patch and please follow #24343

### Actual result BEFORE applying this Pull Request
Editor lose the content

### Expected result AFTER applying this Pull Request
Editor works

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Fedik** [comment]
Drone fail with MySQL connection error, that not related to javascript changes

**Comment by richard67** [comment]
Have restarted the drone and it seems it has helped.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c0eea4f4d972b684c9ff45d126aae3c278be7f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34808">issues.joomla.org/tracker/joomla-cms/34808</a>.</sub>

**Comment by ryandemmer** [comment]
I would suggest that if you are going to use the "sortstop" event bound to the document object, then you check that it is actually sorting a subform, eg:
```javascript
jQuery(document).on('sortstop', function (event, ui) {
    if (ui.item[0] && jQuery(ui.item[0]).is('.subform-repeatable-group')) {
        Joomla.JoomlaTinyMCE.setupEditors(ui.item[0]);
    }
});
```

**Comment by ryandemmer** [comment]
Or better yet, bind to the subform container instead, eg:
```javascript
jQuery(document).on('sortstop', '.subform-repeatable .ui-sortable', function (e, ui) {
    if (ui.item[0]) {
        Joomla.JoomlaTinyMCE.setupEditors(ui.item[0]);
    }
});
```

**Comment by Fedik** [comment]
I thought about it, but from other hand it will help also for someone who use own jquery UI sorting with editor.
The main issue comes from jquery UI.

**Comment by ryandemmer** [comment]
If you don't bind the event specfically to the subform, then the event will trigger whenever a sortable occurs, regardless of whether it is on a subform or not. This is inefficient and unnecessary, and could cause unforseen issues.

**Comment by Fedik** [comment]
Not really, `Joomla.JoomlaTinyMCE.setupEditors()` will care about existing editor.

Using jQuery delegation just add one more `if()` in the chain. 
In one or another way it will be the same if talk about efficiency ;)

> then the event will trigger whenever a sortable occurs, regardless of whether it is on a subform or not.

And that is potential side effect (positive one), for people who use Editor with UI Sortable but not in subform.

**Comment by pixxelfactory** [comment]
I have tested it and there is an issue:
If you add a row and try to reorder it without saving the article first, the content disappears (tested with this repo with stock tinymce).
And it does not work at all using JCE (newest version, JCE Core).. =(

**Comment by Fedik** [comment]
> And it does not work at all using JCE

Please test with core TinyMCE editor,
JCE should implement its own fix, because it the editor issue

**Comment by ryandemmer** [comment]
> And it does not work at all using JCE (newest version, JCE Core).. =(

This will be fixed independantly in the next JCE update, as this current core fix cannot be applied to JCE.

**Comment by pixxelfactory** [comment]
Ok, done, it works, except in one case: If you add an editor and try to reorder it without saving the article first, in that case the content is emptied.

**Comment by Fedik** [comment]
hmhm, I will check

**Comment by ryandemmer** [comment]
It's a good idea to remove the editor first, before re-initialising it. This also saves the content to the textarea, which would prevent the content from dissappearing. See my comment here - https://github.com/joomla/joomla-cms/issues/24343#issuecomment-515784534

**Comment by Fedik** [comment]
> It's a good idea to remove the editor first, before re-initialising it. 

It done here already.
On quick check it some random TinyMCE bug, happened when call `editor.remove()`. 
In most cases it works okay, but sometimes it cause `TypeError: Cannot read property 'startContainer' of null`

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c7d466c9dc00488848a098cd8b7993600f837a02<br /><br />Works good to me thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34808">issues.joomla.org/tracker/joomla-cms/34808</a>.</sub>

**Comment by zero-24** [comment]
Merging for now thanks @Fedik

**Pull request merged**
