### PR TITLE
[4.0] Fix invalid table names in assocations

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #21110

### Summary of Changes
Fixes the table names

### Testing Instructions
See #21110 - no longer errors

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bb3443aec1f303aaba59dac5ad55d7d126225732<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21171">issues.joomla.org/tracker/joomla-cms/21171</a>.</sub>

**Comment by infograf768** [comment]
I do not have the Notices anymore (Nice) but some weird behavior in the side by side page.

here is a screenshot for 2 articles (Already associated)
screen shot 2018-07-18 at 13 10 18

Here for 2 contacts.
remark the tabs are changed to buttons (that may be a template issue) but also the fact that the association is not displayed which is a bug.
screen shot 2018-07-18 at 13 12 20

**Comment by ghost** [comment]
have seen Buttons but thought out of Scope of this PR.

**Comment by wilsonge** [comment]
The tabs collapse into an accordion style format on smaller screen resolutions. so i think that's good.

**Comment by wilsonge** [comment]
Merging this to allow progress. Most of the rest of the issues are javascript ones which aren't my strong suit :P

**Comment by wilsonge** [comment]
@infograf768 fwiw

screen shot 2018-07-18 at 18 08 49

Right now in dev the association doesn't display either - so I don't think that's a 4.x bug

The change target button is broken in 4.x though - I've asked Dimitris to look into that

**Comment by infograf768** [comment]
> Right now in dev the association doesn't display either 

you mean in 3.x ?

**Comment by infograf768** [comment]
> The tabs collapse into an accordion style format on smaller screen resolutions. so i think that's good.

no problem with that. The issue is that we have a different display for menu items, articles and caregories.

**Comment by wilsonge** [comment]
> you mean in 3.x ?

Yes (see screenshot)

> no problem with that. The issue is that we have a different display for menu items, articles and caregories.

I think @dgt41 implemented the custom element tabs in articles and categories only right now (also media manager - but obviously that's not covered by associations) - so I'd expect those two to be different to the rest right now. That's a WIP that will get standardised one way or another

**Comment by infograf768** [comment]
> you mean in 3.x ?

> Yes (see screenshot)

GRRR, same for newsfeeds.... We have to solve that. Also in 3.x

**Comment by infograf768** [comment]
Created issue
https://github.com/joomla/joomla-cms/issues/21178

**Comment by infograf768** [comment]
and patch for 3.x
https://github.com/joomla/joomla-cms/pull/21180

**Pull request merged**
