### PR TITLE
Menu manager pagination broken in 3.5.0 beta

### PR DESCRIPTION
**Pull request by wojsmol**
Simple fix for joomla#8456.

A copy of the original issue description

> ### Steps to reproduce the issue
> 
> Install Joomla 3.5.0 beta
> Open Administrator->Menus->Main menu
> Add at least 5 new menu items
> Change limit dropdown to "5"
> Open search tools, select "Published".
> Change to page 2, everything ok.
> Change back to page 1, everything ok.
> Open search tools again, select "- Select status-".
> Try going to page 2 again.
> ### Expected result
> 
> Page 2 shown
> ### Actual result
> 
> Page 1 shown again
> ### Additional comments
> 
> Please note that this is using 3.5.0 beta, so the changes regarding pagination included here do not fix this problem.

For details see that issue.

### CODE REVIEW

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 64f76a11c54a19e265c6214cb7d82d3decdf0955<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8467">issues.joomla.org/joomla-cms/8467</a>.</sub>

**Comment by izharaazmi** [comment]
@wojsmol It would be better and easier to understand if you can copy the title & details here from the original issue. Also keeping the reference to that issue.

**Comment by osignell** [comment]
I have tested this item :white_check_mark: successfully on 64f76a11c54a19e265c6214cb7d82d3decdf0955<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8467">issues.joomla.org/joomla-cms/8467</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8467">issues.joomla.org/joomla-cms/8467</a>.</sub>

**Comment by wojsmol** [comment]
@izharaazmi Done

**Comment by izharaazmi** [comment]
@wojsmol Thanks :+1:

**Pull request merged**
