### PR TITLE
Allow toolbar popup buttons use bootstrap footer

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Allow custom footer on BS modals rendered from toolbar button

This is a new feature requested at #4563
#### What it does?

Allows to render modal in the bootstrap official way, where the buttons are on the bottom of the modal window
#### How to test

Apply this patch and #4563
Change line 83 of administrator/components/com_messages/views/messages/view.html.php to

``` php
$bar->appendButton('Popup', 'cog', 'COM_MESSAGES_TOOLBAR_MY_SETTINGS', 'index.php?option=com_messages&amp;view=config&amp;tmpl=component', 600, 250, 0, 0, '', '', '<a href="#" class="btn">Close</a> <a href="#" class="btn btn-primary">Save changes</a>');
```

You should get:
screen shot 2015-03-16 at 8 10 49

Mind that the buttons are fake, no functionality is attached

### CODE REVIEW

**Comment by n9iels** [comment]
@test Looks good on desktop, on mobile layout the buttons fall over each other

**Comment by losedk** [comment]
Just tested it. It works fine!

**Comment by losedk** [comment]
Should we move this RTC? Two good tests

**Comment by dgt41** [comment]
@zero-24 can we RTC this one?

**Comment by zero-24** [comment]
Thanks for the bump :smile: RTC now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6462">issues.joomla.org/joomla-cms/6462</a>.</sub>

**Comment by zero-24** [comment]
@committer please be sure that #4563 is merged bevor this as this is a requirement.

**Pull request closed without merging**
