### PR TITLE
[5.2] TinyMCe insert content

### PR DESCRIPTION
**Pull request by brianteeman**
This changes the button text used when selecting a content template from "Save" to "Insert".

No additional changes are required for this to be translated as "Insert" is already translated.

(This PR was created at the request of "Daniel C K Tan" on facebook.

### Testing Instructions
If you dont already have content templates set up and working for tinymce go to the plugin settings for tinymce and setup the correct folder
image

Then create a .txt file in that folder. (As this is just to test the UI the file can be empty)

Finaly in an article select the content template icon from the toolbar
image

And in the dialog that opens observe the text of the buttons.

Then apply this PR and retest. As it is a js change either apply the pr and then run `npm i` or use the prebuilt joomla package that can be found at the bottom of this page at the download link

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 8dd3109c513b4d5c79dc7f11cd163f58e4d60bf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43411">issues.joomla.org/tracker/joomla-cms/43411</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8dd3109c513b4d5c79dc7f11cd163f58e4d60bf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43411">issues.joomla.org/tracker/joomla-cms/43411</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43411">issues.joomla.org/tracker/joomla-cms/43411</a>.</sub>

**Comment by pe7er** [comment]
Thanks @brianteeman !

**Pull request merged**
