### PR TITLE
[5.3] [bugfix] Use iife for the scripts core and load validate as module

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43714 .

### Summary of Changes

Use iife instead of esm for the script core.js and load the script validate.js with a `type=module`

### Testing Instructions

- Apply the PR
- run `npm install`
- Check that authenticating in the administrator works
- Create a new article, don't add anything and press save, the validation error should appear

### Actual result BEFORE applying this Pull Request

Leaking variables in the global scope

### Expected result AFTER applying this Pull Request

NO leaking variables in the global scope

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
This is no go, sorry.

I would suggest to keep for 5.1 the same what you did for 4.4 (will be upmerged).
And set core and validator to type=module for 5.2 as a new feature.

Please, without this huge code move, that you made in core.js. 
Just `window.Joomla = Joomla;` is enough. Having 100 `window.Joomla.foobar = ..` is very bad idea.
Thanks.

**Comment by Fedik** [comment]
If you have a problems with eslint, just add:
```
/* global Joomla */
```
At top of the file

**Comment by dgrammatiko** [comment]
> I would suggest to keep for 5.1 the same what you did for 4.4 (will be upmerged).
And set core and validator to type=module for 5.2 as a new feature.

I don't see any problems with the change from `defer` to `type=module`. Let me explain:
- the defer script in 4.4 has a `use strict` but with the `type=module` this is inferred
- Both defer and `type=module` load the script as deferred
- The only difference is that in the 4.4 the class `JFormValidator` is globally registered but I could attach it to the window and have the same effect.

In sort this change shouldn't be assumed as a breaking change as it isn't

I'll change the `window.Joomla` refs

**Comment by Fedik** [comment]
There no problem to set `type=module` as it is, however they may be extensions that doing "script optimisation" merging non module scripts etc. It will change behavior slightly, to them. 

It is not a big deal, but I would keep it safe, and would not to do such changes in patch release.

**Comment by dgrammatiko** [comment]
> It is not a big deal, but I would keep it safe, and would not to do such changes in patch release.

I'm willing to take full responsibility for this if the maintainers trust me 🙋‍♂️

**Comment by Fedik** [comment]
Then I leave you to maintainers :smile:

**Comment by Fedik** [comment]
Please add one more globals for `window.punycode = punycode;` (as it may used by some script).

And then release manages can decide. What to do with the PR.

**Comment by dgrammatiko** [comment]
> Please add one more globals for window.punycode = punycode; (as it may used by some script).

Done, I guess you could raise this to the maintainers

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 2c1f421afc593f45c1f49befe3b3d56404f0d126<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43758">issues.joomla.org/tracker/joomla-cms/43758</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2c1f421afc593f45c1f49befe3b3d56404f0d126<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43758">issues.joomla.org/tracker/joomla-cms/43758</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43758">issues.joomla.org/tracker/joomla-cms/43758</a>.</sub>

**Comment by bembelimen** [comment]
Hey @dgrammatiko thanks for this PR. Just to understand, isn't this a B/C break, if someone e.g. made an override of the "old" core/validation script and now it's loaded as a module?

**Comment by dgrammatiko** [comment]
No, type=module means:
- use strict by default
- Deferred
- Reduced scope

the reduced scope in this case is irrelevant as the classes are exposed as global vars. In sort there won’t be any issue!

**Comment by bembelimen** [comment]
Ok, I just saw, that after the upmerge something similar was done in 4.4, could you (@dgrammatiko ) please check, if the changes were correct and if this PR is still needed? Thank you!

**Comment by dgrammatiko** [comment]
@bembelimen these changes are still better than the code in 4.4. ES modules should be the default way of serving js in 2024...

**Comment by HLeithner** [comment]
I rebased this for 5.2, not sure if this comes to 5.2 or not @bembelimen @Hackwar

**Review by laoneo — APPROVED** [review]

**Comment by Hackwar** [comment]
I understand that something similar was added to 4.4 and that theoretically this **could** go into 5.2, however I feel uncomfortable adding this to a patch release. That's why I'm moving this to 5.3, but I'm also asking @viocassel and @Fedik to re-test and then will merge it into 5.3. Thank you for your work so far.

**Comment by Hackwar** [comment]
Can you please solve the conflict in the file... ☹️

**Comment by dgrammatiko** [comment]
@Hackwar done

**Comment by laoneo** [comment]
Can we have here one more test, just to see if it still works as there were some commits after the rebase.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
