### PR TITLE
[4.0] Add missing language strings

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add missing language strings

### Testing Instructions
Create a custom media field.
Edit an article.
Click Fields tab.
See labels not translated.
Repeat on the frontend.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 37a5da9dadb655ebb0e69551ef70248cfffbd184<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29784">issues.joomla.org/tracker/joomla-cms/29784</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 37a5da9dadb655ebb0e69551ef70248cfffbd184<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29784">issues.joomla.org/tracker/joomla-cms/29784</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29784">issues.joomla.org/tracker/joomla-cms/29784</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
