### PR TITLE
[4.0] Move toolbar apply items to thead (com_content)

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #16000  .

### Summary of Changes
Second of 2 PRs to apply #16000. Moves the toolbar apply actions to the table header in com_content->articles.

### Testing Instructions
Apply patch and navigate to Content -> Articles. Ensure each item in the dropdown functions correctly.

thead-actions

### Documentation Changes Required
Yes

### CODE REVIEW

**Comment by brianteeman** [comment]
personally i wouldnt move batch to this group but thats something for a ux team review

**Comment by ciar4n** [comment]
I can move batch back to the toolbar until such time UX can review the best location?

**Comment by brianteeman** [comment]
Yes please

**Comment by ciar4n** [comment]
Done!

**Comment by brianteeman** [comment]
it works but i have some odd styling issues
screenshotr11-09-58
screenshotr11-10-04

**Comment by ciar4n** [comment]
Thank you @brianteeman 

Webkit appearance fix committed, resolving this issue.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 64cf20799425ed258210651f589224434103f1c2<br /><br />Thanks @ciar4n <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16076">issues.joomla.org/tracker/joomla-cms/16076</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Click on "Apply Patch" got:

Error 
The file marked for modification does not exist: administrator/components/com_content/views/articles/tmpl/default.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16076">issues.joomla.org/tracker/joomla-cms/16076</a>.</sub>

**Comment by C-Lodder** [comment]
Not sure about this. Having looked at it again now, I don't think a dropdown in the table header would be the best place. The toolbar is where list actions have always resided in Joomla, so I think it would be best to keep them there, and group them.

Submitting that sort of PR would of course get grilled by some just for the sake of it.

**Comment by franz-wohlkoenig** [comment]
Test on fresh installed nightly Build full Package:
bildschirmfoto 2017-05-31 um 12 33 51

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - that was to do with another PR that was submitted yesterday. Just needs to fix conflicts.

**Comment by ciar4n** [comment]
@coolcat-creations  Conflicts fixed

**Comment by brianteeman** [comment]
What is the status on this or is it redundant with the new admin ui
?

**Comment by ciar4n** [comment]
Personally I still consider this a viable UI solution. It is not part of the new design.

**Comment by laoneo** [comment]
Can you fix the conflicts here and make the dog happy?

**Comment by laoneo** [comment]
Can you still unpublish multiple articles with this pr?

**Comment by coolcat-creations** [comment]
https://invis.io/2XESGMRA9#/267252691_Content_-_Manage_Articles_-_Item_1_Ticked_-_Actions_Open

you should of course be able to unpublish

**Comment by laoneo** [comment]
I mean multiple items.

**Comment by coolcat-creations** [comment]
Yes thats the indent of the Action Button.

**Comment by laoneo** [comment]
Now I got it right, the actions menu in the table header is for all articles and the three dots are per article. Thanks for clarification.

**Comment by coolcat-creations** [comment]
I applied the current designapproach which makes it probably more obvious :) The concept in the header is not how it will be...

**Comment by ciar4n** [comment]
Conflicts and hound errors fixed

**Comment by laoneo** [comment]
Had a look on it now. I do miss here the connection to the checkboxes, something feels for me not clear, especially when a first time user opens that list. But eager to hear other opinions.

**Comment by ciar4n** [comment]
> Had a look on it now. I do miss here the connection to the checkboxes, something feels for me not clear, especially when a first time user opens that list. But eager to hear other opinions.

We could hide the 'actions' button until an item has been selected. Animating the button in on selection I believe would make more of a visible connection between the selected items and the button. It is hard for me to look at this with 'new' eyes to completely agree with you.

Regardless maybe best putting this on hold until the template has changed. It is only within the new design that the point can be properly tested. It would make for a good userbob test.

**Comment by laoneo** [comment]
Agree. As one more option. Here is the Google way
image

**Comment by coolcat-creations** [comment]
If you click through the draft, the button was designed "inactive" until the user selects something. This is due to usability. Just start from the beginning and click yourself through to the article overview: https://projects.invisionapp.com/share/8SES9JLZB#/screens/266861164_Desktop_-_Login

**Comment by brianteeman** [comment]
This should be closed as the concept has been applied in another pr. My 2c

**Comment by ciar4n** [comment]
Closed as suggested.

**Pull request closed without merging**
