### PR TITLE
Fix quickicons categories counter

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #37735 .

### Summary of Changes
Add extension=content to the ajax request. The effect is visible on my local winn1, xampp php Version 8.1.5

### Testing Instructions
see #37735 

### Actual result BEFORE applying this Pull Request
Categories counter is a load whieel

### Expected result AFTER applying this Pull Request
Cateories counter shows the number of categories 
grafik

### CODE REVIEW

**Comment by pritam825** [comment]
@chmst counter is not showing , after applying the patch, is something will I have to do after applying the patch.

**Comment by brianteeman** [comment]
@pritam825 You need to go into the module and change the option for the categories to "show counter"

**Comment by pritam825** [comment]
Screenshot (2133)
Are you talking about this "Number of Article", if yes then it's not showing after changing to show.

**Comment by chmst** [comment]
@pritam825 it is the category icon.
grafik

The problem is only visible in PHP/8.1.5

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4b87be32166de21d9d1aa57fb5f18128fbdbdfbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37738">issues.joomla.org/tracker/joomla-cms/37738</a>.</sub>

**Comment by pritam825** [comment]
@chmst Thanks and understood, it's working fine now after patch :)

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 4b87be32166de21d9d1aa57fb5f18128fbdbdfbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37738">issues.joomla.org/tracker/joomla-cms/37738</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37738">issues.joomla.org/tracker/joomla-cms/37738</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
