### PR TITLE
Small grammatical correction

### PR DESCRIPTION
**Pull request by chrisdavenport**
Small correction to English grammar in the email notification message.

### CODE REVIEW

**Comment by brianteeman** [comment]
I'm blind I cant see the change

**Comment by MATsxm** [comment]
If you do not understand what Joomla! is
instead of
If you do not understand what is Joomla!

Is this the only one?

**Comment by chrisdavenport** [comment]
Yeah, GitHub's diff UI is a bit rubbish...

> "If you do not understand **what is Joomla!** and what you need to do please do not contact the Joomla! project"

changed to

> "If you do not understand **what Joomla! is** and what you need to do please do not contact the Joomla! project"

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 960966e931c9183925100c24108384e27222d95e<br /><br />on review BUT @brianteeman is the one for that :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9763">issues.joomla.org/joomla-cms/9763</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 960966e931c9183925100c24108384e27222d95e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9763">issues.joomla.org/joomla-cms/9763</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9763">issues.joomla.org/joomla-cms/9763</a>.</sub>

**Pull request merged**
