### PR TITLE
Search tool filter for com_contact

### PR DESCRIPTION
**Pull request by aniket19491**
With this pull request the filters for Contact component list view will be shown under search tool as per Article list view

### CODE REVIEW

**Comment by zero-24** [comment]
#### How to test

- Navigate to the contacts backend views
- take a view to understand how the filter currently work
- apply this patch
- make sure all still works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7995">issues.joomla.org/joomla-cms/7995</a>.</sub>

**Comment by soap** [comment]
I have tested this item :white_check_mark: successfully on b241d58f3105a2c295a65e54456a69c9c551afe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7995">issues.joomla.org/joomla-cms/7995</a>.</sub>

**Comment by vvkhandagale** [comment]
Working for me as well!

**Comment by zero-24** [comment]
RTC based on testing. Thanks :smiley:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7995">issues.joomla.org/joomla-cms/7995</a>.</sub>

**Pull request merged**
