### PR TITLE
[4.0] Fix filtering in users model

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue [https://github.com/joomla/joomla-cms/pull/26970#issuecomment-549499004](https://github.com/joomla/joomla-cms/pull/26970#issuecomment-549499004), first sentence, and [https://github.com/joomla/joomla-cms/pull/26970#issuecomment-549506006](https://github.com/joomla/joomla-cms/pull/26970#issuecomment-549506006) .

### Summary of Changes

Correct check for "never" filter for last visit date which was broken by PR #26611 (blush).

Don't use "orWhere" for text search filters because this will result in further, later "where" clauses being appended with "OR", which are those of the date range filters, if used. Thanks @SharkyKZ for this fix.

Beside this, for other date range filter options where 2 dates are used, the 2 comparisons ">=" and "<=" are replaced by using "BETWEEN", which is standard SQL and gives the same result. This change can be tested by code review.

### Testing Instructions

Precondition: Have at least 2 users of which some visited the site and some others never visited the site.

1. Go to "Users -> Manage".

2. Click filter options.

3. Select "never" in the dropdown "- Select last visit date -". Check the result in the list.

4. Select any other date range for the last visit date. Check the result in the list.

5. Enter in the text search box the username of a user for which the date range filter selected in step 4 matches. Then click the "search" icon right of the search box. Check the result in the list.

6. Now either change the text in the search box or change the last visit date range so that there are users which match to one of these criteria but not to both. 

### Expected result

For step 3: Only users who never visited the site ("never" shown for last visit date in the list) are shown in the list.

For step 4: Only users with last visit date matching the selected range are shown in the list.

For step 5: Only those users are shown for which both criteria are true, the text search and the last visit date range.

For step 6: No user is shown.

Hint for testers: Please note that all these filters "today", "in the last week", "in the last month" and so on will always show a user who has registered or visited (depending on which filter) the site today, because today is in all these ranges (from 1 week ago until and including today, or from 1 month ago until and including today, and so on). This is desired behavior of these filters and was like this all the time. Only the filter "more than a year ago" excludes today, and for last visit date the "never" filter of course also does not include "today".

### Actual result

For step 3: All users are shown in the list.

For step 4: Same as expected result for step 4.

For step 5: Users are shown for which either the text box or the last visit date matches the criteria.

For step 6: Users are shown for which either the text box or the last visit date matches the criteria.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@infograf768 Could you test this PR, and also test of there are no other issues anymore?

Regarding other "issues" discussed in PR 26970: Please note that all these filters "today", "in the last week", "in the last month" and so on will always show a user who has registered or visited (depending on which filter) the site today, because today is in all these ranges (from 1 week ago until and including today, or from 1 month ago until and including today, and so on). This is desired behavior of these filters and was like this all the time.

Only the filter "more than a year ago" excludes today, and for last visit date the "never" filter of course also does not include "today".

For me with this PR here all works like it should.

**Comment by infograf768** [comment]
Looks Ok now.
FYI phpMyAdmin refuses to update `/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-10-17.sql`
I had to reinstall

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3a49f0313cf1915f2c6b715af8c44d6110eca6f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26982">issues.joomla.org/tracker/joomla-cms/26982</a>.</sub>

**Comment by richard67** [comment]
@infograf768 For the problem with some update sql scripts and PhpMyAdmin with MySQL server versions 5.7 or later there is a trick: Copy the first statement for setting the sql_mode from joomla.sql into the SQL statements window before the statements from the update sql, so it runs first. This will set the session sql mode to something which does not include session variables for strict mode. Then the SQL should run with success in PhpMyAdmin.

**Comment by infograf768** [comment]
You mean
```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
```
?

**Comment by richard67** [comment]
Yes. First one is the important one. Second one not necessary but useful.

**Comment by richard67** [comment]
@infograf768 Did that help with the update sql?

**Comment by richard67** [comment]
@SharkyKZ One more tester needed.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 6ed7099a3a133d20a2dcf764b2f9403a4126c12b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26982">issues.joomla.org/tracker/joomla-cms/26982</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26982">issues.joomla.org/tracker/joomla-cms/26982</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by richard67** [comment]
Thanks to all.

**Pull request merged**
