### PR TITLE
[5.1] Database installation Fields

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #43049 .

### Summary of Changes
As requested modifies the text for the fields in the installation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
No change.

43054-database

**Comment by brianteeman** [comment]
Please recheck that the package you used had the updated language file

**Comment by Quy** [comment]
Yes, it has the updated changes. My installer is using `en-US` thus the no changes.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b530b65384709a8f3fbe37b444ded9b8078b0420<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43054">issues.joomla.org/tracker/joomla-cms/43054</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b530b65384709a8f3fbe37b444ded9b8078b0420<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43054">issues.joomla.org/tracker/joomla-cms/43054</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43054">issues.joomla.org/tracker/joomla-cms/43054</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
