### PR TITLE
[5.3] Revert #44161

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
With #44161 the limitation that custom fields has to be unique system wide was removed. This could break when e.g. a plugin loads custom fields from another extension into a form.

### To simulare the problem
- Enable the user registration
- Create a custom text field called "Foobar" in com_users
- Create a custom list field called "Foobar" in com_contact (and add some options)
- Go to and add the following code to ```components/com_users/tmpl/registration/default.php``` line 23: 

```
Joomla\Component\Fields\Administrator\Helper\FieldsHelper::prepareForm('com_contact.contact', $this->form, []);

```
- Go to the user registration

### Expected result
two "Foobar" fields visible

### Actual problem
Only one "Foobar" field is loaded, the fields are conflicting. This has also different effect when e.g. saving etc.

### Solution
I like in general the idea of the original PR, but it has to be in a Major version respecting the B/C rules.

@Hackwar

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks @bembelimen!

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2cba92917b83d87721cafc0d06bd5a97133873f7<br /><br />Hint for other testers: When having applied this PR, it is not enough just to visit the user registration again to see both fields. You have to edit one of the 2 fields again (or proceed again from the start where you have none of these fields yet). Then you won't be able to save the field (2nd in case if you started again from scratch). You have to manually chose a different name, then you can save, and then you will see both fields in the user registration.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44462">issues.joomla.org/tracker/joomla-cms/44462</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2cba92917b83d87721cafc0d06bd5a97133873f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44462">issues.joomla.org/tracker/joomla-cms/44462</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44462">issues.joomla.org/tracker/joomla-cms/44462</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
