### PR TITLE
[4.x] Fix com_content batch modal button logic

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
The ACL check for the batch toolbar button in the com_content articles backend view has been fixed. So far it was checking for the transition execution permission of com_workflows even if the workflow wasn't enabled at all.

### Testing Instructions
Install a 4.x site, create an "Administrator" level user account, navigate to the article list, create at least one example article. Select that article in the list view, hit the "Actions" button in the toolbar and look for the "batch" option in the submenu.

### Actual result BEFORE applying this Pull Request
Batch option missing

### Expected result AFTER applying this Pull Request
Batch option available

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 08b50172c8bc0a37cbfeac9b924f0fcb7156dbf4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43651">issues.joomla.org/tracker/joomla-cms/43651</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 08b50172c8bc0a37cbfeac9b924f0fcb7156dbf4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43651">issues.joomla.org/tracker/joomla-cms/43651</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43651">issues.joomla.org/tracker/joomla-cms/43651</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
