### PR TITLE
codeception readme

### PR DESCRIPTION
**Pull request by brianteeman**
correct the path in the instructions

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on faf0a92e12044db2b0aa0e5bfb6a9efb2c99b6a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38575">issues.joomla.org/tracker/joomla-cms/38575</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on faf0a92e12044db2b0aa0e5bfb6a9efb2c99b6a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38575">issues.joomla.org/tracker/joomla-cms/38575</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38575">issues.joomla.org/tracker/joomla-cms/38575</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you!

**Pull request merged**
