### PR TITLE
[4.0] Missing strings in admin menu

### PR DESCRIPTION
**Pull request by brianteeman**
Revert three strings

PR for #18858

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 34100c53943f584a405e203ebe8b9e20c74dbbc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18862">issues.joomla.org/tracker/joomla-cms/18862</a>.</sub>

**Comment by infograf768** [comment]
Is also missing an important tip (among others) that was present in en-GB.com_categories.sys.ini
`COM_CATEGORIES_CHOOSE_COMPONENT_DESC="Select a component to which this category should be linked. <br />If a component using categories is not shown in the list, please create at least one category for it using the default regular menu."`
Description missing in the `extension` field in `/administrator/components/com_categories/tmpl/categories/default.xml`

We have
screen shot 2017-11-26 at 09 22 55

We should have
screen shot 2017-11-26 at 09 30 05

**Comment by infograf768** [comment]
Although the tip should be modified a bit (`this category` looks wrong as well in 3.8) as it works fine for "Create a New Category" but not for "List all categories'

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 34100c53943f584a405e203ebe8b9e20c74dbbc5<br /><br />As it can be considered as a separate issue. I added a my test as succesful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18862">issues.joomla.org/tracker/joomla-cms/18862</a>.</sub>

**Comment by infograf768** [comment]
@izharaazmi 
Can you look into that specific tip for staging?

**Comment by franz-wohlkoenig** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks :)

**Comment by brianteeman** [comment]
thanks

**Comment by izharaazmi** [comment]
@infograf768 I checked these keys are present in staging. What else you want me to check?

**Comment by infograf768** [comment]
@izharaazmi 
It looks like `COM_CATEGORIES_CHOOSE_COMPONENT_DESC` is used both for 
`Create New Category` and `List All Categories`.
The value is fine for the first one, but not for the second one.

**Pull request merged**
