### PR TITLE
[4.4] str_replace() on NULL in Joomla\CMS\Uri\Uri::isInternal()

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Don't call Joomla\CMS\Uri\Uri::isInternal() on empty redirect URL.

### Testing Instructions

PHP 8.1, error reporting maximum, update from Joomla 4.3.0 to 4.3.1

### Actual result BEFORE applying this Pull Request

`Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in \libraries\src\Uri\Uri.php on line 243`

### Expected result AFTER applying this Pull Request

No warning.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]
By reviw I think this change is right because not every record in the redirects table has a redirect_url. New records collected with the automatic collection definitely don't have it.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b6a27a23b41e6b05587c65ac9df4063e6fe3bc09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40528">issues.joomla.org/tracker/joomla-cms/40528</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b6a27a23b41e6b05587c65ac9df4063e6fe3bc09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40528">issues.joomla.org/tracker/joomla-cms/40528</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40528">issues.joomla.org/tracker/joomla-cms/40528</a>.</sub>

**Pull request merged**
