### PR TITLE
Control loading of content plugins in mod_articles_news

### PR DESCRIPTION
**Pull request by CoalaWeb**
## Description

Updated the **context** of the trigger events in the **mod_articles_news** module helper to use the context of the module. This allows individual plugins to decided based on the correct context if they should be loaded.
## Testing

To help get my PR tested and included I have made it even easier to test just follow the steps [here](https://issues.joomla.org/tracker/joomla-cms/8610#event-177490).

### CODE REVIEW

**Comment by infograf768** [comment]
Please alpha order the new language strings.

**Comment by Bakual** [comment]
Imho, the real issue is coming from the module inconsistently calling the plugin event with a context of `com_content.article` instead of the 'mod_articles_news.content' it uses in a earlier call.
If it always would call with the proper context, then the plugins itself could decide if they should show or nor in that context.

**Comment by CoalaWeb** [comment]
I totally agree Bakual sorry I missed that. I will update the code accordingly and then as you said a plugin can check the context and decided itself.

**Comment by brianteeman** [comment]
(restarted travis)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by CoalaWeb** [comment]
Do you need me to do anything to help this along?

**Comment by brianteeman** [comment]
I think the travis failure is unrelated to this PR - maybe @wilsonge can check

**Comment by wilsonge** [comment]
Yup it's unrelated. For tests to pass in this PR we need to have the PR rebased onto staging so that it contains this commit: 
https://github.com/joomla/joomla-cms/commit/41807b2cb96740ff050e4411330f872f459db12a (which fixes 

Which fixes this issue

**Comment by brianteeman** [comment]
@coalaweb please can you do as George says and rebase your PR

On 10 March 2016 at 16:21, George Wilson <notifications@github.com> wrote:

> Yup it's unrelated. For tests to pass in this PR we need to have the PR
> rebased onto staging so that it contains this commit:
> 41807b2
> <https://github.com/joomla/joomla-cms/commit/41807b2cb96740ff050e4411330f872f459db12a>
> (which fixes
>
> Which fixes this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8610#issuecomment-194932724>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by CoalaWeb** [comment]
Will do I just need a minute.

**Comment by CoalaWeb** [comment]
I just rebased

**Comment by CoalaWeb** [comment]
OK cool I'll take a look.

**Comment by CoalaWeb** [comment]
Thanks for the help, its all good now ;)

**Comment by wilsonge** [comment]
No thank you for sticking with it :)

**Comment by CoalaWeb** [comment]
Just a question is this not RTC because of the lack of testing?

**Comment by brianteeman** [comment]
Thats correct - it needs at least two succesfull user test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by CoalaWeb** [comment]
Cool I will throw together a plugin to make it easier for people to test and I will hit the old social media to see it I can get a couple of people testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by CoalaWeb** [comment]
To help get my PR tested and included I have made it even easier to test just follow these steps.

1. First create a new article or use an existing one with a bit of text.

2. Next create an Articles - Newsflash module. 

3. Lastly install and publish the plugin [Content - CW Mod News Test](http://cdn.coalaweb.com/test-ext/cwmodnewstest.zip "Test Plugin") and you should now see the context of the article is **com_content.article** and the module is **mod_articles_news.content** So I think it stands to reason that my PR that the changes:

**From**
    $results = $app->triggerEvent('onContentAfterDisplay', array('com_content.article', &$item, &$params, 1));
    $results = $app->triggerEvent('onContentBeforeDisplay', array('com_content.article', &$item, &$params, 1));

**To**
    $results = $app->triggerEvent('onContentAfterDisplay', array('mod_articles_news.content', &$item, &$params, 1));
    $results = $app->triggerEvent('onContentBeforeDisplay', array('mod_articles_news.content', &$item, &$params, 1));

Would be a worth while change or am I missing something?

Cheers,

Steve<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by mcanuste** [comment]
I have not tested this item.<br /><br />I have followed the steps for testing and it says com_content.article for the context of the article, and says mod_articles_news.content on the module. But applying patch on Patch Tester for this issue doesn't change anything. So I'm not sure if its successful or not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by mcanuste** [comment]
I have tested this item :red_circle: unsuccessfully on b7c14bd6ad397198a2fe17e893fcdbf4d4661894<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by CoalaWeb** [comment]
I think has been some confusion the patch won't change anything visual I have just included the plugin to show that an article is using **com_content.article** while the module is using **mod_articles_news.content** as you saw with the plugin installed. Based on that it stands to reason that the module's plugin trigger events should be on the module content **mod_articles_news.content**.

Cheers,

Steve<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by ggppdk** [comment]
This PR asks for:
```
mod_articles_news.content
```

PR suggests:  #11339 , to use context
```
mod_articles_news.article
```

Now we have: (in existing module code)
```
com_content.article
```

I would like:
(something to clearly give out both the used content type and the location of usage)
e.g.
```
com_content.article@mod_articles_news
```


Please note, i am just summarising, i am not asking for any changes, or anything

- in fact i don't know if some intended B/C breaks , can be published e.g. a few months time prior to e.g. official release of J3.7, then most developers can update their extensions, before they happen

so that we do not have to wait for J4 for some improvements, like this (= knowing not only what is displayed, but also where it is displayed)

**Comment by Curiensol** [comment]
I have tested this item :red_circle: unsuccessfully on b7c14bd6ad397198a2fe17e893fcdbf4d4661894<br /><br />Either the test is incomplete or there is no difference.
The Locations of Article & Module remain the Same

@icampus Pizza, Bugs&Fun<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by wmchris** [comment]
I have tested this item :white_check_mark: successfully on b7c14bd6ad397198a2fe17e893fcdbf4d4661894<br /><br />Context have been changed, checked manually with debugger.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by CoalaWeb** [comment]
Curiensol please see my earlier comment. Thanks.

**Comment by mcanuste** [comment]
I have tested this item :white_check_mark: successfully on b7c14bd6ad397198a2fe17e893fcdbf4d4661894<br /><br />Sorry about before, I have tested again and it works as it is said in the suggested steps.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by kevinscheithauer** [comment]
I have tested this item :white_check_mark: successfully on b7c14bd6ad397198a2fe17e893fcdbf4d4661894<br /><br />I tested this @icampus PBF and confirm that this works. I followed the suggested steps and fix works as suggested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8610">issues.joomla.org/joomla-cms/8610</a>.</sub>

**Comment by ggppdk** [comment]
Yes it "works", that is not what is most important here,

questions are
- what is a proper **context** to be used ? (please see my previous comment)
- there is a big B/C break, for e.g. 2%-5% ?? (i do not know percentage) sites using the module and along with some plugins (please see my previous comment)

Plugin replacements will stop working, since all 3rd plugins will not to be updated in "time"

**be honest i do not care much about this module**, as much i mind the "**proper context**" question

**(users will care),** also site managers will mind when they hear the users complaints, plus they will be annoyed by delay in plugin updating, (and not every plugin will be updated either)

**Comment by roland-d** [comment]
@ggppdk You raise a valid question as to what is the correct context. Looking at what is in core now the structure allows follows the name of the view. com_content.archive for the archive view, com_tags.tag for the tag view. So for this PR I would say we need com_content.mod_articles_news. Another variation on what you proposed. To be B/C we would need to call both and deprecate the old one.

**Comment by wilsonge** [comment]
As there are conflicts here, I've created an updated PR with #12289

**Pull request closed without merging**
