### PR TITLE
Tags - move Filters from left to [Search Tools]

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves the 3 Filter options of the Tags Manager to the [Search Tools] button.
**note**: The ordering dropdown in [Search Tools] **needs to be fixed** before merging.
(See Issue #6941 regarding the inconsistency with Filter options).
## Test instructions

In back-end > Components > Tags
See the filters on the left (compare the position with filters in Content, Category & Menu components)

screen shot 2015-05-15 at 05 38 02
### This PR changes moves the Filters

from the left to the middle column and will be visible when you click on the [Search Tools] button.

screen shot 2015-05-15 at 05 38 02
### **Notes:**

I can use some help & suggestions regarding the following issues:
- The ordering dropdown in [Search Tools] is currently not working
- What to do with the empty slider? Add the "Tags" as title?
- Code cleanup 1 - tmpl view ( /administrator/components/com_tags/views/tags/tmpl/default.php ) 
  contains "Joomla.orderTable = function()" that probably can be removed
- Code cleanup 2 - In tmpl view (/administrator/components/com_tags/views/tags/view.html.php) 
  I commented out the old filters in the left slider, they can be removed...
- Code cleanup 3 - In tmpl view (/administrator/components/com_tags/views/tags/view.html.php) the function "protected function getSortFields()" can be removed as the ordering in [Search Tools] uses the "fullordering" specs from filter_tags.xml

### CODE REVIEW

**Comment by pe7er** [comment]
I've changed the component title from "Tags" to **"Tags Manager"**,
and added a "Tags" submenu so that (although this component has just 1 view) the view is consistent with all other components. 

screen shot 2015-05-17 at 08 40 03

**Note**: Sorting the results via the column headers works ok,
but the sorting option "Sort Table By:" (the dropdown) **does not work** yet.
I have not found a solution for that yet. I hope that someone can give me some pointers on that...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6950">issues.joomla.org/joomla-cms/6950</a>.</sub>

**Comment by jduerscheid** [comment]
Issue successful tested! #jab15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6950">issues.joomla.org/joomla-cms/6950</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing :smile: #jab15 #makteithappen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6950">issues.joomla.org/joomla-cms/6950</a>.</sub>

**Comment by mbabker** [comment]
Merged to `3.5-dev` via b52f030

**Pull request closed without merging**
