### PR TITLE
com_redirect disabled not unpublished

### PR DESCRIPTION
**Pull request by brianteeman**
Update the error and success message and the toolbar button for the Purge functionality to change from unpublished to disabled as redirects are enabled/disabled and not published/unpublished

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 770191f10a1117d5f57d89584bb19ffb538adc28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17418">issues.joomla.org/tracker/joomla-cms/17418</a>.</sub>

**Comment by Quy** [comment]
Under Search Tools, change `Published/Unpublished` to `Enabled/Disabled`.

Trash an item. Under the Status column in the drop down menu, change `Publish` to `Enable`.

**Comment by brianteeman** [comment]
@quy I have done the search tools but I dont really know the best way to do the actionsdropdown (or if it is really needed)

**Comment by infograf768** [comment]
As far as I know there are no actions dropdown else than Archive and Trash in other managers.
PR looks fine here.

**Comment by ghost** [comment]
@infograf768 should i alter a successfully Test for you?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on eb1f6f64b726af1b74f5e5ceb4041c2173924168<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17418">issues.joomla.org/tracker/joomla-cms/17418</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on eb1f6f64b726af1b74f5e5ceb4041c2173924168<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17418">issues.joomla.org/tracker/joomla-cms/17418</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17418">issues.joomla.org/tracker/joomla-cms/17418</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
