### PR TITLE
Add html data to the html array instead of echoing

### PR DESCRIPTION
**Pull request by alexvanniel**
Instead of echoing the input field in place, the html code for the input field should be added to the html array otherwise the html code will end up outside of the intended div.

### CODE REVIEW

**Comment by zero-24** [comment]
This looks correct but i have no idea to test it? Where do you see / catch this so we can test it ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7923">issues.joomla.org/joomla-cms/7923</a>.</sub>

**Comment by alexvanniel** [comment]
It it is rather hard to actually find a usecase, it is more of a clean up than a big bugfix. Although, if the intent here was to echo the field input before the hidden div then the code is a bit odd and the $html declaration should be done lower and after echoing the field input. You might not even see any "problems" in the browser unless you open up a debug window and start looking for hidden input fields/fieldsets and see that the fieldset is outside of the hidden div.

**Comment by mbabker** [comment]
I don't know how you'd check it, but pre-patch the contents are rendered and then an empty div (which has inline styling to not be displayed) is rendered; post-patch the contents are inside that div.  Code wise it reads fine to me, I just wouldn't know where to start looking at it.  Since this is supposed to be rendering hidden fields, I'd say you could remove the $html array and just echo the fields also.

**Comment by alexvanniel** [comment]
I am not entirely sure it handles hidden fields. It handles hidden fieldsets as far as I know and not necessarily hidden fields. I suspect that removing the hidden div would potentially display fields that are not set to hidden even though the fieldset is declared hidden. Or am I swinging left and right and missing massively?

**Comment by mbabker** [comment]
If it's fieldsets then ya, that might be the case.

**Comment by alexvanniel** [comment]
Granted, the parameters of this ever showing or causing any problems are obscure to say the least :)

**Comment by wilsonge** [comment]
Merged on review.

**Pull request merged**
