### PR TITLE
[5.1] collapsed sidebar menu [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes to display the flyout title on the sidebar manu in both dark and light modes
replacement pr for #43134 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 976880f8303c720245459992523b67753683d639<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43137">issues.joomla.org/tracker/joomla-cms/43137</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 976880f8303c720245459992523b67753683d639<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43137">issues.joomla.org/tracker/joomla-cms/43137</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43137">issues.joomla.org/tracker/joomla-cms/43137</a>.</sub>

**Comment by brianteeman** [comment]
would be great if this could make it into 5.1 - otherwise the collapsed admin menu is not usable

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
