### PR TITLE
[4.0] Skipto 4.1

### PR DESCRIPTION
**Pull request by brianteeman**
I just made a new release of skipto - mainly just tweaks and a slight change in how the tooltip for the accesskey info is displayed

css change to the joomla black tooltips as it was effecting the skipto help text see #33493

Pull Request for Issue #33493 .

This will need a full npm i as there is a package update and a css change

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Still get a horrid dropshadow - but the text is no longer truncated. 

Screenshot 2021-05-23 at 11 45 21

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 47d92f4f3b6f821b31cd3f4a3b111fc7a84f03c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34119">issues.joomla.org/tracker/joomla-cms/34119</a>.</sub>

**Comment by PhilETaylor** [comment]
Also a very strange tooltip anyway - I have just pressed CTRL+Option+9 twice to get to this state, so telling me what the access key is now is strange as I KNOW, I PRESSED IT TWICE ALREADY hahahahha

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 47d92f4f3b6f821b31cd3f4a3b111fc7a84f03c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34119">issues.joomla.org/tracker/joomla-cms/34119</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34119">issues.joomla.org/tracker/joomla-cms/34119</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Pull request merged**
