### PR TITLE
[4.x] Treeselect fixes

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #41309

### Summary of Changes

1. Fix the treeselect dropdowns not working
2. Fix the check/uncheck buttons not toggling checkboxes that had been manually changed (backported from https://github.com/joomla/joomla-cms/pull/42776)
3. Fix select/deselect changing the state of the current menu (backported from https://github.com/joomla/joomla-cms/pull/42776)

### Testing Instructions

1. Go to edit any module in the Module Manager
2. Navigate to the Menu Assignment tab
3. Change the assignment to "Only on selected pages"

**Test 1:**
Ensure the dropdown menu opens as shown below:
image

**Test 2:**
1. Open the dropdown menu and click "select" or "unselect"
All checkboxes (including the one parallel to the dropdown toggle) should be toggled

**Test 3:**
1. Check (or uncheck) any checkbox
2. Click the buttons shown above: 
image

All checkboxes should be toggled.

@LadySolveig @Quy

### CODE REVIEW

**Comment by C-Lodder** [comment]
@Quy I wouldn't make the UX better to be honest. If a checkbox appears to be "disabled" (as shown in your screenshot), I'd assume I wouldn't be able to manually check it, which the user should be able to.

**Comment by Quy** [comment]
It is unchecked and not toggleble by default for `URL` and `Alias`, however, the `All` and `Select/Deselect` toggle them. Ideally, they should be skipped with these actions.

**Comment by C-Lodder** [comment]
Oh I see. Didn't know that was the expected behavior. Will take a look tomorrow morning

**Comment by C-Lodder** [comment]
@Quy fixed

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 1ce3ae6ecf2a047ee79ca9249ffdac04423bcb90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42895">issues.joomla.org/tracker/joomla-cms/42895</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ce3ae6ecf2a047ee79ca9249ffdac04423bcb90<br /><br />Thank you!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42895">issues.joomla.org/tracker/joomla-cms/42895</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42895">issues.joomla.org/tracker/joomla-cms/42895</a>.</sub>

**Comment by laoneo** [comment]
@C-Lodder can you fix the whitespaces?

**Comment by C-Lodder** [comment]
@laoneo Done.
Silly windows eol

**Comment by laoneo** [comment]
@C-Lodder thanks

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
