### PR TITLE
Newsfeedimage

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11270 .
#### Summary of Changes

In the News Feed component options are two settings for the default value for the image float for each news feed. It the news feed it is clear that they are the first and the second images but it is not clear in the component options. This fixes that
#### Before

459ff2d8-50f3-11e6-82d4-7292b56e06d5
#### After

l7tv

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 9ff5f4d0be711fb2042f5596e876442ce39c5ba5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11515">issues.joomla.org/joomla-cms/11515</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on fb670a42cb0b8316f3818a8ac452a5e11a1bfae6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11515">issues.joomla.org/joomla-cms/11515</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11515">issues.joomla.org/joomla-cms/11515</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on fb670a42cb0b8316f3818a8ac452a5e11a1bfae6<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11515">issues.joomla.org/joomla-cms/11515</a>.</sub>

**Pull request merged**
