### PR TITLE
[4] CTRL + OPTION + A on MacOS.

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Append CTRL + OPTION + A on MacOS to help text in "System - Additional Accessibility Features" plugin

### Testing Instructions

Read. 

### Actual result BEFORE applying this Pull Request

Screenshot 2021-04-22 at 20 37 25

### Expected result AFTER applying this Pull Request

Screenshot 2021-04-22 at 20 38 59

### CODE REVIEW

**Comment by brianteeman** [comment]
I don't have a Mac to test so I assume that you did.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on af27a799e71bdc854156bb16d5dc0beca3ac0217<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33254">issues.joomla.org/tracker/joomla-cms/33254</a>.</sub>

**Comment by PhilETaylor** [comment]
Yup - works for me with CTRL + OPTION + A on MacOS.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on af27a799e71bdc854156bb16d5dc0beca3ac0217<br /><br />Can the text be changed to "with the hotkey CTRL + ALT + A or on MacOS CTRL + OPTION + A." if this is a good english? As its now it looks like both hotkeys are for macos.

Better to show only hotkeys working on os user use but i don't know if this is possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33254">issues.joomla.org/tracker/joomla-cms/33254</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33254">issues.joomla.org/tracker/joomla-cms/33254</a>.</sub>

**Pull request merged**
