### PR TITLE
[sql install] Set all front menu modules to display sub menus per default when installing Joomla

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/15094

### Summary of Changes
As title says.
When creating a frontend menu module the default is to show the sub menus.
```
				<field
					name="showAllChildren"
					type="radio"
					label="MOD_MENU_FIELD_ALLCHILDREN_LABEL"
					description="MOD_MENU_FIELD_ALLCHILDREN_DESC"
					class="btn-group btn-group-yesno"
					default="1"
					>
					<option value="1">JYES</option>
					<option value="0">JNO</option>
				</field>
```
This normalises this setting in all sample data.
I see no unwanted consequences: when no submenus available, no change.
### Testing Instructions
Patch an instance of Joomla and install with various sample data
This can also be tested using this pack
https://github.com/infograf768/joomla-cms/archive/sub_menus_modules.zip

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
@infograf768 installed your zip but don't get how to test.

**Comment by franz-wohlkoenig** [comment]
see its an complete install. Test now.

**Comment by infograf768** [comment]
It's indeed mostly code review, but you can check is none or any sample data installs ok, and then look at the menu modules to confirm that Sub Menu Items parameter is set to Yes.

**Comment by franz-wohlkoenig** [comment]
tested successfully (didn't get Button on Issue Tracker to mark)

**Comment by infograf768** [comment]
We need one more tester.

**Comment by Quy** [comment]
Tested successfully via code review.

Should this file be updated too?
`\joomla-cms\tests\unit\stubs\database\jos_modules.csv`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15099">issues.joomla.org/tracker/joomla-cms/15099</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
