### PR TITLE
[Regression] Pagination not working in menu items

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue (Regression).
#### Summary of Changes

When selecting a menu (besides the `- Select Menu -` option) the pagination is not working.
#### Testing Instructions
1. Use latest staging
2. Go to Menus -> (Any menu with several pages)
3. Check the pagination is not working (hint set pagination to 5 items)
4. Apply patch
5. Repeat test and check the pagination is working now.
6. Check also that when moving from one menu to another the pagination always resets to 1.

@infograf768 @bembelimen please check.

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on e673299079cb9e5b514cca551dd557ac08a4f30c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10649">issues.joomla.org/joomla-cms/10649</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on e673299079cb9e5b514cca551dd557ac08a4f30c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10649">issues.joomla.org/joomla-cms/10649</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10649">issues.joomla.org/joomla-cms/10649</a>.</sub>

**Comment by joomlalombardia** [comment]
I have tested this item :white_check_mark: successfully on e673299079cb9e5b514cca551dd557ac08a4f30c<br /><br />text example ready in Joomla! Pizza bug & fun Milano 28 May. #PBFIT  with Joomla!Lombardia compliments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10649">issues.joomla.org/joomla-cms/10649</a>.</sub>

**Comment by andrepereiradasilva** [comment]
folks, thanks for testing.
@joomlalombardia have fun at "Joomla! Pizza bug & fun" Milano event!

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
