### PR TITLE
Custom fields missing when editing articles using Beez3

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/15665.

### Summary of Changes

Renders additional fields in article form in frontend.

### Testing Instructions

Use Beez3 template in frontend.
Create some article custom fields.
Create/edit an article in frontend.

### Expected result

Custom fields shown in form.

### Actual result

Custom fields not shown in form.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3a30638e7171732484f4e49fcf5ed6200d7a6e2a<br /><br />I did not get the notice mentioned in issue #15665 .
But I can confirm that with this PR the fields are shown in frontend editing form of an article when using the Beez3 template, and field validation (e.g. if required and empty) works, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29577">issues.joomla.org/tracker/joomla-cms/29577</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3a30638e7171732484f4e49fcf5ed6200d7a6e2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29577">issues.joomla.org/tracker/joomla-cms/29577</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a30638e7171732484f4e49fcf5ed6200d7a6e2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29577">issues.joomla.org/tracker/joomla-cms/29577</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29577">issues.joomla.org/tracker/joomla-cms/29577</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
