### PR TITLE
Removed redundant period in language string

### PR DESCRIPTION
**Pull request by ghost**
Used for example in categories > Batch modal

### CODE REVIEW

**Comment by Bakual** [comment]
@brianteeman For you to verify.

**Comment by brianteeman** [comment]
Peter is correct and I already fixed it with the batch processing PR

On 6 August 2015 at 14:34, Thomas Hunziker <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> For you to verify.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7645#issuecomment-128367051>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
the fix is in #7637

**Comment by Bakual** [comment]
I think we close this one then in favor of yours. Thanks Peter!

**Pull request closed without merging**
