### PR TITLE
[4.0] module count quickicon

### LINKED ISSUE #29831: [4.0] 3rd Party Dashboard Module -> Modules count doesnt honour trash
### Steps to reproduce the issue

Joomla 4.0 beta 1 enable the "3rd Party" Admin Module (This is a core Joomla thing, not actually a 3rd Party provided module) 

Not sure why its called "3rd Party" ???

Anyway, edit the module, set all to `Show Items with Count` 

Screenshot 2020-06-29 at 12 06 22

View the module on the "Home Dashboard"

Screenshot 2020-06-29 at 12 06 42

### Expected result

That the number of MODULES = the number of NON TRASHED modules

Note that the number of ARTICLES and ARTICLE CATEGORIES **DO** honour items that are trashed (E.g They show 0 if all are trashed. The number should show the number of NOT TRASHED items) 

### Actual result

The number of modules includes the number in the trash. 

### System information (as much as possible)

Joomla 4 Beta 1

### PR DESCRIPTION
**Pull request by brianteeman**
Correctly count the number of published site modules

fixes #29831

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 13029b5925b4bad4bc8e9eb312254a5fe98b28d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29835">issues.joomla.org/tracker/joomla-cms/29835</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 13029b5925b4bad4bc8e9eb312254a5fe98b28d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29835">issues.joomla.org/tracker/joomla-cms/29835</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29835">issues.joomla.org/tracker/joomla-cms/29835</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 13029b5925b4bad4bc8e9eb312254a5fe98b28d7<br /><br />Applying the patch changed the number of modules from 32 to 29. That excludes Unpublished modules and refers to Site modules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29835">issues.joomla.org/tracker/joomla-cms/29835</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
