### PR TITLE
[4.0] @subpackage

### PR DESCRIPTION
**Pull request by brianteeman**
Fix some copy paste errors

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a8832c0060407ed142de6a39caaf29061fcfbae9<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25723">issues.joomla.org/tracker/joomla-cms/25723</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a8832c0060407ed142de6a39caaf29061fcfbae9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25723">issues.joomla.org/tracker/joomla-cms/25723</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25723">issues.joomla.org/tracker/joomla-cms/25723</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
