### PR TITLE
[3.10] Pre-Update Check - Doesn't repect Minimum Extension Stability

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #34555

### Summary of Changes

Pre-Update Check - Doesn't repect Minimum Extension Stability

### Testing Instructions

1. Install extension with stability lower than *Stable* (ie. Beta, Release Candidate) and updates in manifest with stability lower than *Stable*

1. Set up Minimum Extension Stability to: Development  
   *Administrator > Global Configuration > Installer*

1. Start Joomla update from 4.0.0-rc.1 to 4.0.0-rc.2

### Actual result BEFORE applying this Pull Request

Extension Pre-Update Check should not show extension in *Update Information Unavailable* section

### Expected result AFTER applying this Pull Request

Extension Pre-Update Check shows extension in *Update Information Unavailable* section.

### Documentation Changes Required

none

cc @piotr-cz please test with your extensions mention here https://github.com/joomla/joomla-cms/issues/34555

### CODE REVIEW

**Comment by piotr-cz** [comment]
Code looks good to me,
I don't have any extensions in unstable versions anymore.

**Comment by zero-24** [comment]
Thanks

**Comment by zero-24** [comment]
Merging this for now.

**Comment by piotr-cz** [comment]
Thank you!

**Pull request merged**
