### PR TITLE
Fix #10725. "List of all tags" menu item does not show site name in page title if requested

### LINKED ISSUE #10725: "List of all tags" menu item does not show site name in page title if requested
#### Steps to reproduce the issue
Create a menu item of type "List of all tags".
In Global Settings - SEO, set Include site name in page title to Before (or After).
Go to front end and click to that menu item of list of all tags

#### Expected result
Page title in the browser should include site name and then the menu item name.

#### Actual result
Page title does not include site name.

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/10725
#### Testing Instructions

Create a menu item of type "List of all tags". Or use menu item _All Tags_ in staging with test datas.
In Global Settings - SEO, set Include site name in page title to Before (or After).
Go to front end and click to that menu item of list of all tags
No sitename in Browser TITLE.

Apply patch.

Test again.

### CODE REVIEW

**Comment by sovainfo** [comment]
I have tested this item :white_check_mark: successfully on 8137699af6e7a8496a17df8ed0ebecefafc6b6b2<br /><br />Works as designed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10727">issues.joomla.org/joomla-cms/10727</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8137699af6e7a8496a17df8ed0ebecefafc6b6b2<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10727">issues.joomla.org/joomla-cms/10727</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10727">issues.joomla.org/joomla-cms/10727</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request merged**
