### PR TITLE
[4.2] Provide a fallback for the persisted url for the Media Manager

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Provide a reasonable fallback for the client side persisted state of the current folder

### Testing Instructions
- Open Media manager
- navigate to `images/sampledata/cassiopeia`
- Open the browser dev tools
- Open to the tab `Application` (or Storage for Safari)
Screenshot 2022-10-11 at 17 03 25

- Edit the session storage from `selectedDirectory:  "local-images:/sampledata/cassiopeia"` to `selectedDirectory:  "local-none:/sampledata/cassiopeia"`
Screenshot 2022-10-11 at 17 03 52

-Reload the page (F5 or clicking the refresh button of the browser)

### Actual result BEFORE applying this Pull Request
Broken

### Expected result AFTER applying this Pull Request
Fallback to the root of the drive or fallback to the first available drive

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 9a05ac588c0bd2c15037005b7e21f411dd7ece73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9a05ac588c0bd2c15037005b7e21f411dd7ece73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by laoneo** [comment]
I did now restart drone two times and bot times it failed on the same test `showsFilesAndFoldersOfASubdirectoryWhenOpenedUsingDeepLink`. @dgrammatiko can you have a look if this pr breaks the test?

**Comment by dgrammatiko** [comment]
@laoneo the test is probably wrong

**Comment by laoneo** [comment]
I don't think so. Can you please check why the test is failing? I would like to get this one merged.

**Comment by dgrammatiko** [comment]
> Can you please check why the test is failing

Could you send me the error log of the the CI?

**Comment by dgrammatiko** [comment]
@laoneo turns out the computer was right and I was wrong. The code should now work as expected.

**Comment by laoneo** [comment]
Rarely this happens in Joomla land... 😉

**Comment by ceford** [comment]
I can't get the first part of the test to work. When I change local-images to local-none and reload, the page reloads normally and the session storage is back to local-images. This with Firefox and Chrome on Mac. What have I misunderstood?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 20de282faa04f7a7b85f5b4879aeaa9b7363493f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by laoneo** [comment]
@ceford this is how it should be. If you do that on a joomla installation without the patch, then it breaks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by fancyFranci** [comment]
@viocassel Could you please test again? There where some changes in the script. Would be great to have it in the coming release.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 445bde398f0de5ebdb028fe4bcbfb8f4d9e21c6c<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38934">issues.joomla.org/tracker/joomla-cms/38934</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you! Great that you improved the media manager :)

**Pull request merged**
