### PR TITLE
Add Microdata to popular articles - hard coded values

### PR DESCRIPTION
**Pull request by photodude**
Pull Request to Add Microdata to popular articles.
#### Summary of Changes

Adds hard coded Microdata to popular articles following the format established in the latest articles module
#### Testing Instructions
1. Add patch
   https://docs.joomla.org/Testing_Joomla!_patches
2. Add a popular articles module to a view
3. Check that microdata values are applied using a microdata validation tool such as
   https://developers.google.com/structured-data/testing-tool/
#### Additional Comments

With the JMicrodata PR's #8934 and #8933 in review, this PR is proposed to add the hard coded Microdata values so that schema.org markup can be added in the short term. 

The does not replace #8934, nor is it an alternative.  This PR is just a solution to put in place the missing Microdata values while the change to use the JMicrodata library is in Review.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
**Titles not linked**
Without Patch you see linked Titles in Module "Articles - Most Read":
without-patch-fe
With Patch unlinked Titles:
patch-fe

**Testing Tools Failure**
Without Patch you see no Module Failure (Failures only in "Article")
without-patch
With Patch there are Failures:
patch

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 0e9063250aeff9c5e9cd76ee3651615f2be3d0ed<br /><br />breaks links as noted above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9474">issues.joomla.org/joomla-cms/9474</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 0e9063250aeff9c5e9cd76ee3651615f2be3d0ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9474">issues.joomla.org/joomla-cms/9474</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on ca0b09fdfb095131cbb9dba85ae796d44807f485<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9474">issues.joomla.org/joomla-cms/9474</a>.</sub>

**Comment by coolman01** [comment]
I have tested this item :white_check_mark: successfully on localhost <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9474">issues.joomla.org/joomla-cms/9474</a>.</sub>

**Comment by nikitadhiman** [comment]
I have tested this item :white_check_mark: successfully on ca0b09fdfb095131cbb9dba85ae796d44807f485<br /><br />The patch works fine!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9474">issues.joomla.org/joomla-cms/9474</a>.</sub>

**Comment by photodude** [comment]
@brianteeman Can this be set to RTC now?

**Comment by photodude** [comment]
@wilsonge @mbabker could someone mark this RTC now that we have successful human tests?

**Pull request merged**
