### PR TITLE
Update copyright on readme

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to update to 2016 the copyright date to 2016

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Does this needs tests?

**Comment by justinherrin** [comment]
I have tested this item :white_check_mark: successfully on 3ab6581294a8251d41479fcd6407ed4348121c72<br /><br />In case a test is needed. Simple, but needed change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8838">issues.joomla.org/joomla-cms/8838</a>.</sub>

**Comment by infograf768** [comment]
I think we can make a global change for the copyright date which is anyway necessary.

**Comment by brianteeman** [comment]
I did this one separately to the global change that you usually do as it is
not in the copyright block in the header but in the body

On 5 January 2016 at 17:05, infograf768 <notifications@github.com> wrote:

> I think we can make a global change for the copyright date which is anyway
> necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8838#issuecomment-169062998>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3ab6581294a8251d41479fcd6407ed4348121c72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8838">issues.joomla.org/joomla-cms/8838</a>.</sub>

**Comment by infograf768** [comment]
@brianteeman 
Here is a global PR where the copyright is updated, including in the readme and sql files.
It is not updating fof or other 3rd party.
https://github.com/joomla/joomla-cms/pull/8848

**Comment by infograf768** [comment]
Something else to check and correct separately or add to this PR
we have both
`Open Source Matters, Inc.` and `Open Source Matters.`

I guess this has to be normalised.

**Comment by brianteeman** [comment]
+1 on standardising

**Comment by brianteeman** [comment]
Close in favour of #8848 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8838">issues.joomla.org/joomla-cms/8838</a>.</sub>

**Pull request closed without merging**
