### PR TITLE
Remove Manager and standardise on Options

### PR DESCRIPTION
**Pull request by brianteeman**
This is the Pull request to remove the word manager which is pretty redundant. The PR also standardises on Options not a mix of options and configuration

In researching and testing this PR it became apparent that the word Manager had already been removed in some translations already eg German

Below are screenshots for the changed top menu, quicklinks on the control panel and one view from com_content and com_modules as an example but all components have been updated in the title bar.

Thanks to @rgmears for the images and everyone who contributed to the discussion on this in the en-GB User Interface Text Working Group  and on the test proposal. You can read the discussions about this change at #7431 #7432 and https://github.com/joomla/user-interface-text/issues/42
### Top Menu

user_interface_top_menu
### Control Panel Quick Links

user_interface_side_menu
### Article Manager

user_interface_articles
### Module Manager

user_interface_modules

### CODE REVIEW

**Comment by wilsonge** [comment]
Haven't tested this but the screenshots look **MUCH** better. One thing I'm not quite sure I like is the removal of "Configuration" from "Global Configuration" in the cPanel quick icons. There are many places in the language files we reference "Global Configuration" and I think it may be better to keep it in line with that (even though it is under a subheading of "Configuration")

**Comment by brianteeman** [comment]
For me the second configuration is superfluous on that specific view

**Comment by brianteeman** [comment]
The actual menu item has not changed and is still called global
configuration

**Comment by MAT978** [comment]
#7490 works as describe.
Thanks for this great improvement - Thanks @brianteeman 

-Top menu: success
-Control Panel Quick Links: success
-Article + Module + **Plugins** (not on screenshot): success<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7490">issues.joomla.org/joomla-cms/7490</a>.</sub>

**Comment by jwaisner** [comment]
@test 

PR works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7490">issues.joomla.org/joomla-cms/7490</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Great change, thank you @brianteeman and all other who participated in the discussion. Merged with https://github.com/joomla/joomla-cms/commit/587d8460e9cd700902b453ae8914c54ea4feb35d!

**Comment by infograf768** [comment]
Any reason to treat "Languages" differently from Plugins, Modules, Templates (s between parenthesis)?
screen shot 2015-07-22 at 10 52 54

**Comment by brianteeman** [comment]
Yes because all sites with have a plural of Plugins, modules and templates
but only some sites will have more than one language

On 22 July 2015 at 09:53, infograf768 <notifications@github.com> wrote:

> Any reason to treat "Languages" differently from Plugins, Modules,
> Templates (s between parenthesis)?
> [image: screen shot 2015-07-22 at 10 52 54]
> <https://cloud.githubusercontent.com/assets/869724/8821685/e45b95c2-305f-11e5-973a-4a051c0adb0f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7490#issuecomment-123624954>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I guess you do not count the fact that there are at least 2 languages: admin and site... each with a sub menu in the sidebar...
And, if we were going your way, then :
"Overrides" should be "Override(s)"
"Content Languages" => "Content Language(s)"
On the opposite
"Install Language" should be "Install Language(s)"

And what if someone is only using one category only? "Categories" would not fit...
Same for Contacts, Tags, whatever....

Thanks for correcting to "Languages"
Please correct

**Pull request closed without merging**
