### PR TITLE
Checkbox selection in new or edit Smart Search Filter

### PR DESCRIPTION
**Pull request by amone4**
Pull Request for Issue #19930.

### Summary of Changes

corrected typo to ensure proper checkbox functionality

### Testing Instructions

click on the text corresponding to the checkbox to toggle its status

### Expected result

checkbox corresponding to text gets checked

### Actual result

same as expected

### Documentation Changes Required

none

### CODE REVIEW

**Comment by ghost** [comment]
Changed Title to be clear whats the Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19969">issues.joomla.org/tracker/joomla-cms/19969</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 32dffdf4c049b6fa9ba020fdbe0f7c11f97e8f3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19969">issues.joomla.org/tracker/joomla-cms/19969</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 32dffdf4c049b6fa9ba020fdbe0f7c11f97e8f3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19969">issues.joomla.org/tracker/joomla-cms/19969</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
