### PR TITLE
[4.0] Eliminate some inline js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
In Joomla 4 the form submission related script is automated through the class `form-validate`

### Testing Instructions
Go to `http://j4.local/administrator/index.php?option=com_privacy&view=requests`
Click on the New button
Fill the form and click `Save And Close`
You will return to the list so click on the newly created line and then on the button invalidate

Everything works...

### Documentation Changes Required

No, cleanup

### CODE REVIEW

**Comment by CG-68** [comment]
All test passed!

**Comment by berndkohlen** [comment]
tested and ok

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26617">issues.joomla.org/tracker/joomla-cms/26617</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks to @dgrammatiko and the testers here 👍

**Pull request merged**
