### PR TITLE
[4.0] Remove eval from modal.js

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Redo of #32271 but without `eval`

### Testing Instructions

Same as #32271 

ping @wilsonge @dgrammatiko

### CODE REVIEW

**Comment by infograf768** [comment]
`// This is UNSAFE!!!!`

??

**Comment by Fedik** [comment]
yes, it still unsafe, but not that as  `eval` :smile:

**Comment by dgrammatiko** [comment]
Ahuh I forgot to return 🤦‍♂️

**Comment by Fedik** [comment]
yeap, `return` changes everything

**Comment by infograf768** [comment]
PR works fine here.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 2cf694684c578cfa3a8c9b36643d88ce7283093d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32469">issues.joomla.org/tracker/joomla-cms/32469</a>.</sub>

**Comment by richard67** [comment]
> PR works fine here.

@infograf768 So was that a good test? If yes, shall I set the test result for you?

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32469">issues.joomla.org/tracker/joomla-cms/32469</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2cf694684c578cfa3a8c9b36643d88ce7283093d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32469">issues.joomla.org/tracker/joomla-cms/32469</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32469">issues.joomla.org/tracker/joomla-cms/32469</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
