### PR TITLE
[4.2] The "activate" tag is not needed in the user registration email template without activation

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/39115.

### Summary of Changes
The PR removes an unnecessary tag, see details https://github.com/joomla/joomla-cms/issues/39115.

### Testing Instructions
Install the build with PR, go to email templates, make sure templates `com_users.registration.user.registration_mail` and `com_users.registration.user.registration_mail_w_pw`  don't have tag `{ACTIVATE}`.

The PR is also making changes to existing sites to get rid of the tag there as well. Regular update.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
l that update script overwrite any existing customisations?

**Comment by Kostelano** [comment]
Sorry, I didn't understand the question. If we are talking about templates, then by default the tag is not included in the text. It is difficult to imagine a situation in which one of the users still added a tag to the text, which in the end does not show anything.

**Comment by brianteeman** [comment]
If a user has customised that mail template then applying your update will overwrite their changes. You can either not have an update query OR you will need to write a query that only alters the params.

**Comment by Kostelano** [comment]
How can it be? We are talking about a fresh installation of Joomla 4.2 and an upgrade from 3x.

**Comment by brianteeman** [comment]
@richard67 am I wrong? Wouldn't this change be applied on a normal 4.x update as well?

**Comment by richard67** [comment]
> @richard67 am I wrong? Wouldn't this change be applied on a normal 4.x update as well?

You are wrong.

When updating a 4.0.**0**, the database schema version is "4.0.0-2021-08-17" because that's the name of the youngest schema update for 4.0.0 at that time, and now we update to a 4.x.y and have a script `4.0.0-2020-12-20.sql`. The schema version "4.0.0-2020-12-20" in that script's name is lower than "4.0.0-2021-08-17" when comparing with `version_compare`, and so it will not run.

It will only run when we update a version (old alpha or beta or maybe also RC) where the script `4.0.0-2020-12-20.sql` was not there yet.

You would be right if this PR would have added a new 4.0.0 update SQL with a newer date. This then would run when we would update a 4.0.0.

But this is not the case, and this is a perfect example why it sometimes makes sense to update the old update SQL scripts which you claim to be immutable because (as your question here shows, too), never really understood how the database updates work.

I am almost sure that for the one or the other of your recent PRs where you said you won't make update SQL scripts it would have been possible to do the same, change the old update SQL so at least updating from 3.10 will result in the right params.

But because you never accepted any of my explanations why we can and sometimes should change old update SQL scripts.

And so I gave it up to check your PRs for that and argue with you.

**Comment by richard67** [comment]
> How can it be? We are talking about a fresh installation of Joomla 4.2 and an upgrade from 3x.

@Kostelano You are right. Brian just doesn't understand how it works.

**Comment by brianteeman** [comment]
mea culpa

**Comment by brianteeman** [comment]
I might not know how it works according to you but surely this PR will only fix the bug for new installs and new upgrades from joomla 3. All other sites will still have the extra param.

this is not the first time that we have had an almost identical issue with the params for the updates see #37504 which @richard67 approved and was a pr created because of an issue also reported by @kostelano

It needs an update sql like this

```

UPDATE `#__mail_templates`
	 SET `params` = '{"tags":["name","sitename","siteurl","username","password_clear"]}'
 WHERE `template_id` = 'com_users.registration.user.registration_mail_w_pw' AND `params` = '{"tags":["name","sitename","activate","siteurl","username","password_clear"]}';
 
UPDATE `#__mail_templates`
	 SET `params` = '{"tags":["name","sitename","siteurl","username","password_clear"]}'
 WHERE `template_id` = 'com_users.registration.user.registration_mail' AND `params` = '{"tags":["name","sitename","activate","siteurl","username","password_clear"]}';


```

**Comment by Kostelano** [comment]
Ok, I'll add tomorrow.

**Comment by Kostelano** [comment]
Got it today, added. Should be OK.

**Comment by Kostelano** [comment]
Now I have rechecked and everything works - both for a new installation and for a live site. Description corrected.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc1f750a4036ee12c663d9c119a12d49e00e7588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39195">issues.joomla.org/tracker/joomla-cms/39195</a>.</sub>

**Comment by richard67** [comment]
@Kostelano Was there the need for updating the branch, i.e. conflicts, or broken drone? You know, when you update the branch, it resets the counter for human tests, so if nobody restores that test in the issue tracker, we will not find a PR which has 2 tests when we search for that in the issue tracker. That means additional work for us, so we should avoid unnecessary branch updates. Now I will go and restore Quy's test.

**Comment by Kostelano** [comment]
@richard67 I didn't know that, sorry. Let then hangs PR so.

**Comment by richard67** [comment]
@Kostelano Well, it still might need branch updates when there are conflicts or when you want to restart drone or appveyor and can't do that directly in their UI. Let me know when you have a PR which needs tests to be restored because commits after tests were just clean branch updates or small changes in code comments or so, or when you find such PRs. Thanks for your contributions by the way.

**Review by richard67 — APPROVED** [review]
All SQL changes are correct. The name of the new update SQL files is still suitable because no files with newer schema version in their name have been added for 4.2.x in the mean time. The update statement is safe because it changes the complete "params" value so there are no risky json manipulations.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cf42737393c5c2e5aa1c7593ea184275d593d541<br /><br />I've tested installations as well as updates. For the latter, I've used the custom URL created by drone for this PR for the live update with the update component to update from current 4.2-dev to this PR.

I've tested with both MySQL and PostgreSQL, so it was 4 tests in total, and all SQL changes made by this PR were covered by these tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39195">issues.joomla.org/tracker/joomla-cms/39195</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39195">issues.joomla.org/tracker/joomla-cms/39195</a>.</sub>

**Comment by roland-d** [comment]
Hello @Kostelano I would like to get this into 4.2.7 but the filename of the SQL file should be updated as it is now `4.2.6-2022-11-11.sql`. Can you please update these filenames so I can merge this?

**Comment by Kostelano** [comment]
@roland-d, done.

**Review by richard67 — APPROVED** [review]

**Comment by roland-d** [comment]
@Kostelano Thank you, now we wait for Drone :)

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
