### PR TITLE
[4.2] Fix multiselect, Correcting com_installer "update" layout markup

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #37600 .

### Summary of Changes

use correct cell tag in com_installer "update" layout.

### Testing Instructions

You need to have some updates available.
Then follow  #37600.

### Actual result BEFORE applying this Pull Request

Select works correctly

### Expected result AFTER applying this Pull Request

Select works incorrectly.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 52891a49f9c85d78def5987ee2b48b0402ed9f34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37725">issues.joomla.org/tracker/joomla-cms/37725</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 52891a49f9c85d78def5987ee2b48b0402ed9f34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37725">issues.joomla.org/tracker/joomla-cms/37725</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37725">issues.joomla.org/tracker/joomla-cms/37725</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
