### PR TITLE
Add missing 'Show Subcategories Text' param to Contacts

### PR DESCRIPTION
**Pull request by nvyush**
Pull Request for Issue # .

### Summary of Changes
For Contacts component:
/administrator/components/com_contact/config.xml - add missing ```show_category_heading_title_text``` parameter.
/components/com_contact/views/categories/tmpl/default.xml - add missing ```show_category_heading_title_text``` parameter, code style.
/components/com_contact/views/category/tmpl/default.xml - add missing ```show_category_heading_title_text``` parameter, code style.

### Testing Instructions
Use a fresh Joomla, apply the patch.
Create a tree of some contact categories.
Create contacts with default options and place they to some contact categories.
Create menu items of the types Contacts » List All Contact Categories and Contacts » List Contacts in a Category for the root contact category.
Check the contact categories in the frontend. All should be fine.
Play with the option 'Show Subcategories Text' in the Global Configuration » Contacts, in the Category tab of the menu items you created.

NB!: When testing the  menu item of the type ```Contacts » List All Contact Categories```, the menu item of the type ```Contacts » List Contacts in a Category```  must be unpublished.

### Expected result
When the option 'Show Subcategories Text' is Off in backend, the label "Subcategories" must not be shown in frontend.

### Actual result
The option 'Show Subcategories Text' is missing in backend, the label "Subcategories" is shown always in frontend.

### CODE REVIEW

**Comment by Heggi93** [comment]
I have tested this item :red_circle: unsuccessfully on 5f42d0fe5900fedec6a634bbebf9611b0eea3e37<br /><br />I create a tree of categories with a depth of 3 and added some contacts to the categories. For the type Contacts >> List Contacts in a Category the button worked fine. The button is shown in the administration view and the title 'Subcategories' in the front-end worked as described.

For the type Contacts >> List All Contact Categories the button is shown in backend but doesen't work. Also if I unpublish the Contacts >> List Contacts in a Category item the selection has no effect on the view. After the selection of the root category the title 'Subcategories' is always shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17316">issues.joomla.org/tracker/joomla-cms/17316</a>.</sub>

**Comment by nvyush** [comment]
@Heggi93 I rechecked, all work. When you test the menu item of the type 'Contacts >> List All Contact Categories' you need to open some subcategory of the root category and test that page. It is important that the menu item of the type 'Contacts » List Contacts in a Category' must be unpublished, otherwise in this case that menu item will be opened.

**Comment by MeghaBiranje** [comment]
I have tested this item :white_check_mark: successfully on 5116ecaedbb62dd8df8b61667663927a2575bf09<br /><br />I have tested this successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17316">issues.joomla.org/tracker/joomla-cms/17316</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5116ecaedbb62dd8df8b61667663927a2575bf09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17316">issues.joomla.org/tracker/joomla-cms/17316</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17316">issues.joomla.org/tracker/joomla-cms/17316</a>.</sub>

**Comment by laoneo** [comment]
Since Joomla 3 is not accepting new features, we would like to ask you to rebase your PR to the 4.2 branch to be tested in Joomla 4. In the meantime we close it. When ready for testing please reopen the pr.

**Comment by brianteeman** [comment]
it is NOT a new feature it is fixing a bug!!!

**Comment by laoneo** [comment]
When you add new parameters, then I doubt that it is fixing a bug. What is broken without the pr?

**Comment by brianteeman** [comment]
If you read the post you will see - I really wonder sometimes if people prefer to just click close instead of actually reading and trying to understand

**Comment by laoneo** [comment]
@brianteeman does this pr the same as https://github.com/joomla/joomla-cms/pull/32736?

**Comment by brianteeman** [comment]
That PR is for j4

**Pull request closed without merging**
