### PR TITLE
[4.2] Show permission core.admin in table of debuguser

### PR DESCRIPTION
**Pull request by heelc29**
Related to PR #38781

### Summary of Changes

Permission `core.admin` do **not** `contain always the same value because these are global permissions` (#37807) @chmst 

Both permission are `core.admin`:

https://github.com/joomla/joomla-cms/blob/e9b9263a34ad919c7a8e6b817074f53eb1997565/administrator/components/com_config/forms/application.xml#L1264-L1267

image

https://github.com/joomla/joomla-cms/blob/e9b9263a34ad919c7a8e6b817074f53eb1997565/administrator/components/com_banners/access.xml#L4-L7

image

Added permission `core.admin` back to table

### Testing Instructions

Check `Permissions for User` which belongs to group `Administrator`

### Actual result BEFORE applying this Pull Request

You can't see if the user can configure ACL of a specific component
image

_(unless you explicitly filter for it)_
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceciogit** [comment]
I have tested this item :white_check_mark: successfully on 08b4df73ac943e0b16ceb2c2d15c55b9091a7c68<br /><br />👌 perfect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39481">issues.joomla.org/tracker/joomla-cms/39481</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 08b4df73ac943e0b16ceb2c2d15c55b9091a7c68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39481">issues.joomla.org/tracker/joomla-cms/39481</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39481">issues.joomla.org/tracker/joomla-cms/39481</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
