### PR TITLE
Fix for Issue https://github.com/joomla/joomla-cms/issues/41270 Loading Views

### PR DESCRIPTION
**Pull request by coolcat-creations**
Fix like suggested in https://github.com/joomla/joomla-cms/issues/41270#issuecomment-1655905244

Pull Request for Issue #41270 .

### Testing Instructions
make a copy of
html/com_content/category/default.php
html/com_content/category/default.xml
html/com_content/category/default_articles.php
html/com_content/category/default_children.php

rename them and put in this template an alternate layout for a category list:
html/com_content/category/mylayout.php
html/com_content/category/mylayout.xml
html/com_content/category/mylayout_myarticles.php
html/com_content/category/mylayout_mychildren.php

In mylayout.php change articles to myarticles (I did that but did not mentio in the test instructions)
Change something in the _myarticles file or put a die(); at the top to see if your template is loaded.
Change the layout title in the mylayout.xml so you recognize it in the menu item types overview

Create a new menu item and select my layout as a menu item type

### Actual result BEFORE applying this Pull Request
Is not working when you load multiple sublayouts and your childtemplate name is the same name as the main template

### Expected result AFTER applying this Pull Request
Is working when you load multiple sublayouts and your childtemplate name is the same name as the main template

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I still cannot replicate the reported problem. What am i missing

image

**Comment by degobbis** [comment]
@brianteeman It mainly affects templates that use your own child template workflow, like Yootheme Pro.

**Comment by brianteeman** [comment]
well thats an issue for yootheme to fix then

**Comment by degobbis** [comment]
at this point fixed that also templates with underscore in the name, like "mytheme_business" -> "mytheme_business_child" and that without B/C

**Comment by brianteeman** [comment]
> at this point fixed that also templates with underscore in the name, like "mytheme_business" -> "mytheme_business_child" and that without B/C break.

Repeated my tests and this time with a parent template called brian_default and a child therefore of brian_default_child

I still cannot replicate the reported problem

image

**Comment by degobbis** [comment]
Sorry, my mind was on something else.
You are right, with child templates created by Joomla there is no problem, because $template->template == $layoutTemplate.

But there are other ways to use child templates, see Yoothe Pro, which already offered this before Joomla knew what it is.
Here $template->template == 'yootheme' and $layoutTemplate == 'yootheme_childname'.

In $this->_path['template'] the paths are already correct, until Search and Replace.

The search string is not structured in a way that it only considers complete template paths.

JPATH_THEMES . DIRECTORY_SEPARATOR . 'yootheme' is therefore also used in JPATH_THEMES . DIRECTORY_SEPARATOR .'yootheme_childname'.

The result is then replacing 'yootheme' with 'yootheme_childname' in JPATH_THEMES . DIRECTORY_SEPARATOR .'yootheme_childname' and that ends in JPATH_THEMES . DIRECTORY_SEPARATOR .'yootheme_childname_childname'.

This change ensures that this no longer happens.

At this point it should be mentioned, not the template/template framework loads the overrides, they are just provided.
The override is loaded by the component from the HtmlViewer, this cannot be intercepted via the template.
At least I am not aware of any way.

**Comment by brianteeman** [comment]
I have never used a yootheme template not will I ever use a yootheme template. If their template doesnt work with core joomla then they should change their code. This is why Joomla releases nightly builds of development builds as well as multiple alpha, beta and release candidates. </rant>

**Comment by HLeithner** [comment]
@degobbis can you give me access to a test site please? I would like to have a look at directly, I can't follow the reason why this only happens with a 3rd party pagebuilder.

**Comment by coolcat-creations** [comment]
I can give you access tomorrow evening :-) thank you

**Comment by dgrammatiko** [comment]
> why this only happens with a 3rd party pagebuilder.

@HLeithner I suspect that it would happen with any template that has `_` in the name (ie `cassi_opeia`). I would prefer another way to deal with the parts of the path, ie in the application lifecycle when the template is selected there's a query that fetches all the non disabled templates. We could store a simple array `$app->templates` with the name, path, legacy or not, etc. Then all the path resolvers could just search the array and pick/skip. In sort no guessing...

**Comment by dgrammatiko** [comment]
> At least I am not aware of any way.

@degobbis the way to override the paths exists since forever: https://github.com/joomla/joomla-cms/blob/bd92bc442082ccb5f15170a185fe09917310d837/libraries/src/MVC/View/HtmlView.php#L134-L165

Actually you could override many things. It's very weird that none of the _good_ templates out there is not using it.

**Comment by HLeithner** [comment]
@degobbis showed me what's happening, and ignoring if it's right or not what yootheme does, we should replace the complete path ant not only a part of it, so from my side this pr ok.

**Comment by brianteeman** [comment]
>  @HLeithner I suspect that it would happen with any template that has _ in the name (ie cassi_opeia).

My test above showed that it works fine with a _ in the name

**Comment by dgrammatiko** [comment]
> My test above showed that it works fine with a _ in the name

@brianteeman you didn't tested the failing case, ie parent === `some_thing` child: `some_thing_child_name`

**Comment by HLeithner** [comment]
> > @HLeithner I suspect that it would happen with any template that has _ in the name (ie cassi_opeia).
> 
> My test above showed that it works fine with a _ in the name

It's not the underscore, the reason is that the str_replace an older "replaced" string replaces a second time, then you have `yootheme_elisa_elisa` and in this case joomla should not replace wrong pathes which are not relevant to replace.

**Comment by brianteeman** [comment]
@HLeithner thanks for the explanation of the real issue

**Comment by dgrammatiko** [comment]
>  joomla should not replace wrong pathes which are not relevant to replace

I see. FWIW the code is like that since before v4 so it's weird that this was never came up.

Hopefully @coolcat-creations could convince them to embrace the modern templates structure...

**Comment by HLeithner** [comment]
you are right you changed something on this but that shouldn't be relevant for this issue, the original code already solved a similar issue it seems https://github.com/joomla/joomla-cms/commit/ddf93d207e0f980159ed840a218fc4cd1fe0af20

did this ever worked? @coolcat-creations for example in joomla 4.0 before child templates has been introduced?

**Comment by dgrammatiko** [comment]
> did this ever worked? @coolcat-creations for example in joomla 4.0 before child templates has been introduced?

@HLeithner all versions of Joomla 4.+ (since beta.4: https://github.com/joomla/joomla-cms/pull/30192) had support for child templates. 4.1 just brought the missing UI. Basically the question is if it ever worked in 3.x?

**Comment by HLeithner** [comment]
I'm asking if yootheme had worked with the old joomla version.

**Comment by coolcat-creations** [comment]
I made an override for the category list I never had this task before inside YT so I can't say if it worked before. I just wonder why we discuss so much if the fix is quite easy and existing ? Does it cause problems? I don't know. Does it solve problems? Yes it does.

**Comment by brianteeman** [comment]
> . I just wonder why we discuss so much if the fix is quite easy and existing

At the beginning it took a long time to identify where the problem was because it was not in joomla child template but in something from yootheme with the same name. None of your initial reports on github mentioned yootheme

Because yootheme (or a user of yootheme) has not (until now) reported an issue with this code so it ~is~ was unclear where the problem arises. In **_general_** we cant just make changes in core because of the behaviour of an extension as it would be impossible to test and impossible to ensure that the code was not reverted as it had no apparent effect or putpose

**Comment by brianteeman** [comment]
> I made an override for the category list

Have you made overrides of anything else before. The problem should be the same

**Comment by coolcat-creations** [comment]
Yes I did overrides of modules in YT before and it works everywhere without issues. In J3 and J4

**Comment by brianteeman** [comment]
so what is different this time

**Comment by coolcat-creations** [comment]
Probably the way how the category list template is loaded. If you compare the category list view to Joomla 3 category list views a Layout was introduced into the view which calls again the views. I don't know what are the reasons behind that change.

**Comment by degobbis** [comment]
Let's leave third party extensions aside.

The code is already existing since Joomla 3 (https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/MVC/View/HtmlView.php#L663-L671), when childthemes were not considered yet. 

According to the comment, it was used to use layouts from other templates by exchanging the path of the active template with the path of the alternative template.

Let's analyse what this code is supposed to do:

Let's assume the properties are set as follows: 
- `$template->template = 'originaltheme'`
- `$layoutTemplate = 'originaltheme_myclone'`

This results in the following values for the str_replace:
Search pattern: `<path-to-joomla-root>/templates/originaltheme`
Replace with: `<path-to-joomla-root>/templates/originaltheme_myclone`
In path: `<path-to-joomla-root>/templates/originaltheme_myclone/html/category/mycat_article.php`

The error here is that the search pattern is found even if it is part of the wrong path.

It should only replace if the path is `<path-to-joomla-root>/templates/originaltheme`/html/category/mycat_article.php.

Now the search pattern is found in `<path-to-joomla-root>/templates/originaltheme`_myclone/html/category/mycat_article.php and converted to `<path-to-joomla-root>/templates/originaltheme_myclone`_myclone/html/category/mycat_article.php, and that is wrong.

So it is necessary to make the search pattern more precise so that it does not swap subpaths, and thus does correctly what it was originally conceived to do.

This PR takes care of that.

The YooTheme Pro template was just the trigger that led us to this BUG.

So please let's stop outsourcing the fix of this BUG to third party extension developers when it's clear that it's mishandled in core.

Translated with www.DeepL.com/Translator (free version)

**Comment by HLeithner** [comment]
I head not the time to check this again in deep. I'm also not sure if it gets in to beta2 (no matter if 4.4 or 5.0) since that's tomorrow. for 4.3 no further releases are planned.

**Comment by HLeithner** [comment]
didn't had time to look more in deep in this problem, rebasing for 4.4 at least make sense.

@laoneo and @MacJoom 

can you please have a look at this

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 02abfdc7b24b8628c2510701313a128bbc21dcd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41274">issues.joomla.org/tracker/joomla-cms/41274</a>.</sub>

**Comment by laoneo** [comment]
Actually this should be merged much earlier in the release lifecycle to identify some regressions, as I think it has the potential to break templates. Nevertheless, I'm merging it for now, so hopefully people test it with 3rd party templates. When problems will occur, I will not hesitate to revert it during the release candidate phase of 4.4.

Thanks for all the help here from so many people and for the understanding that it took so long till we maintainers could care about it.

**Pull request merged**
