### PR TITLE
2008 to 2016

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Very simple PR. Update some dates in comments in some files 2008 --> 2016.
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 494d775532d80738f668dfdb312c353fc697b048<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10844">issues.joomla.org/joomla-cms/10844</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 494d775532d80738f668dfdb312c353fc697b048<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10844">issues.joomla.org/joomla-cms/10844</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10844">issues.joomla.org/joomla-cms/10844</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks all for testing and merging!

**Pull request merged**
