### PR TITLE
Fixes #6461 | Adding custom position of the module in the position dr…

### LINKED ISSUE #6461: Module front editing : custom positions not listed
Hello !

#### Steps to reproduce the issue
Log into the front using a super admin account and edit a module. Click on the position list : if you set some custom positions, you won't see it in the list. If you edit a module which is on a custom position and save, the module will be placed to the first default position (banner)

#### Expected result
A bug of the new module front edit.

#### Actual result
No custom position in front editing. Modules moved to another position without user action.

#### System information (as much as possible)
Bug appears on an upgraded installation and a fresh installation

#### Additional comments
Please correct it fast

### PR DESCRIPTION
**Pull request by Achal-Aggarwal**
…opdown while editing module on frontend.

http://issues.joomla.org/tracker/joomla-cms/6461
#### Added by @brianteeman 25 Aug

Edit the index.php of the protostar template and rename the module position in line 177 from
`<jdoc:include type="modules" name="position-8" style="xhtml" />`

to

`<jdoc:include type="modules" name="test123" style="xhtml" />`

Now go to the module and create a new custom module and place it in position test123 (it wont be on the list you have to manually enter it)

Go to global configuration and make sure that you have "Mouse-over Edit Icons for" set for modules

Go to the front end of the site and check the new module is displayed and then log in

Hover over the module and you get an icon to let you open the module for editing. Change the module title and press save. The module will have been saved in a different position.

Now apply the patch. Go to module manager and put the module back into test123 and repeat

You will now see that when you edit the module you will see at the bottom of the list of module positions a section "Active positions" and test123 is there. Dont change the position. Edit the title and sabe the module. The module will have been saved in the same position

### CODE REVIEW

**Comment by brianteeman** [comment]
While this edit does mean that the custom position IS displayed when you edit a module in a custom position  the custom position is still NOT displayed when editing another module. This means that while you can move a module from a custom position to a position defined in the templatedetails.xml you cannot do the reverse.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by Achal-Aggarwal** [comment]
Yes that is correct.

I don't think on frontend module position dropdown should have all custom positions. I don't know whether this is the requirement or not. I remember you saying that module position should behave on frontend as it does on backend. I don't agree with this.

This edit will allow users to edit module (positioned on custom position) on frontend. Currently they can't do it without changing its position to a position defined in the templatedetails.xml

**Comment by brianteeman** [comment]
Hard to explain to a user that they can move a module from one position to
another but not to all module positions

**Comment by sovainfo** [comment]
See no reason for the frontend to work differently from the backend, what is the justification for that?

**Comment by Bakual** [comment]
It should behave the same, yes. If it's possible of course.
I don't see a reason why it should not.

**Comment by Achal-Aggarwal** [comment]
@sovainfo 
Assuming user doesn't have or can't change frontend template from frontend, Let there are two templates TemplA & TemplB having custom-posA and custom-posB as custom position respectively.

Now backend will show both positions (if Active) under position dropdown. And if the same behaviour is provided on frontend too then user can choose either of two positions through dropdown.

If TemplA is active and user chooses custom-posB as a position of a module then he/she won't be able to edit the module again as it will not be visible anywhere on the current/active template anymore.

I know there are lots of ifs, I think it is a valid and possible scenario in which something unexpected will and probably can happen leaving the state un-editable for the user having restricted rights.

@Bakual I think it is possible. It is just that whether we want it that way or not.

**Comment by sovainfo** [comment]
There is no protection against stupidity! Not everything can be done from front-end, possible mistakes have to be corrected in the backend. Considering these misstakes can be made with the reduced options, you might as well allow them to be made with the custom options as well.

When the experience in the front-end is going to be different from the back-end don't bother to allow it in the front-end!

**Comment by Achal-Aggarwal** [comment]
So in conclusion we should not give option to select any custom position on front-end, Am I right?

**Comment by Bakual** [comment]
The conclusion is that you can't prevent users from doing stupid things anyway. Like for example unpublish the module which can't be fixed from frontend anymore. If you try, you restrict users who want to do perfectly fine things, which is worse.

As said, the frontend should behave exactly the same as the backend. There is no reason to restrict the frontend editing in functionality.
So please allow the users to select any custom position (or even create new ones) exactly as it is in backend.

**Comment by sovainfo** [comment]
In my opinion you should be able to select the custom positions in the front-end. Those are the positions used on the site.

**Comment by Achal-Aggarwal** [comment]
I have added another commit which basically adds all active positions in the list. Same as back-end behaviour, user now can select any custom position currently active and can assign new custom position.

Note: There is lots of duplicated code (copied from com_module). I didn't wanted to make dependency of front-end module editing on back-end com_module.

**Comment by conconnl** [comment]
@Achal-Aggarwal can you write a Test scenario, so people can test your patch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cda9f807fd69ad84836653ebcdee01203be28aa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by brianteeman** [comment]
Added test instructions to the original post<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by veronikapatel** [comment]
-->I have tested successfully
**Before Patch**
screen shot 2016-08-29 at 08 06 59

**After Patch**
screen shot 2016-08-29 at 08 07 35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by veronikapatel** [comment]
I have tested this item :white_check_mark: successfully on cda9f807fd69ad84836653ebcdee01203be28aa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by zero-24** [comment]
RTC. If a maintainer merge this before the CS Pr gets merged please ping me CS PR against this repo is: https://github.com/Achal-Aggarwal/joomla-cms/pull/1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7540">issues.joomla.org/joomla-cms/7540</a>.</sub>

**Comment by rdeutz** [comment]
@Achal-Aggarwal can you merge the CS fix so we can merge this one. Thanks

**Comment by zero-24** [comment]
@rdeutz feel free to merge i can send a PR after the merge this PR is over a year old.

**Comment by zero-24** [comment]
done at #11843

**Pull request merged**
