### PR TITLE
[#32241] Client side validation based on validation.js not working. And ...

### PR DESCRIPTION
**Pull request by Achal-Aggarwal**
...adding precomputation of labels in jQuery version.

### CODE REVIEW

**Comment by zero-24** [comment]
Hi @Achal-Aggarwal 

is this issue still valid? As the last comment here was on 27 Aug 2014? Also pull requests to the master branch of this repo are not longer accepted. Can you close this pull request and submit a new one against the staging branch, if this issue still exists?
If there is no response in a month we will close the PR here.

Thanks for understanding!

**Comment by roland-d** [comment]
Closing this PR due to inactivity. If you still feel this is valid, the issue can be reopened. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2233">issues.joomla.org/joomla-cms/2233</a>.</sub>

**Comment by RyanfaeScotland** [comment]
Just ran into this issue when trying to diagnose why my Global Config wouldn't save.

Going by previous comments I found if I had an email address in the 'From email' form then the validation would try and run and the system would just hang. With the developer console open the code breaks in validate.js script at the function 'function(e,t){e=punycode.toASCII(e);var n=/^[a-zA-Z0-9.!#$%&’*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;return n.test(e)}' right on the 'e=punycode.toASCII' call.

This may not give you more information but I just wanted to confirm that A) someone else had the issue and B) it is still valid in 3.4.0.

I apologise if this has since been sorted or there is another ticket open for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2233">issues.joomla.org/joomla-cms/2233</a>.</sub>

**Comment by Fedik** [comment]
@RyanfaeScotland how much User groups do you have on your Site?
if there is a loot User Groups it  can be a reason of system  hang .. such performance issue you can test there #7460

**Comment by RyanfaeScotland** [comment]
Hi @Fedik thanks for the quick response.

I'd assume my User Groups are either 0, 1 or whatever the default is when Joomla is installed as I've never made explicit use of them. I can check for certain after work / over the weekend if you are interested?
Also happy to help get to the bottom of this. I've got a workaround of not having the email field filled so don't need an answer but happy to help if you (or anyone else) would like to investigate it.

**Comment by RyanfaeScotland** [comment]
Just repeated the process at home on my own PC and with IE 11.0.9600.18015 it still happens but using Chrome 45.0.2454.99 m there isn't any issue.

**Comment by Achal-Aggarwal** [comment]
Hi Ryanfae,

Please add some steps how one can reproduce the issue at local.

On Sun, Sep 27, 2015 at 8:43 PM, RyanfaeScotland <notifications@github.com>
wrote:

> Just repeated the process at home on my own PC and with IE 11.0.9600.18015
> it still happens but using Chrome 45.0.2454.99 m there isn't any issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/2233#issuecomment-143566958>.
>



-- 
Achal

**Comment by RyanfaeScotland** [comment]
Will do @Achal-Aggarwal it may be a little while though as I don't have a local install and do all my work on my actual site. Been wanting to make a copy to local for a while though so will add it to my task list and report back when I get it done (if you never hear from me again assume I won the lottery and have decided never to touch a computer again).

**Pull request closed without merging**
