### PR TITLE
New URL for Joomla! Events

### PR DESCRIPTION
**Pull request by MATsxm**
Now that the Events site is part of Community site, urls must be fixed to: 
`https://community.joomla.org/events.html`
### Testing Instructions

Code review

### CODE REVIEW

**Comment by MATsxm** [comment]
Should be ok now.
Could someone (@andrepereiradasilva ? :flushed:) check I haven't missed a file?
Thanks

**Comment by dgt41** [comment]
@MATsxm I think you are fine:
screen shot 2016-09-20 at 22 11 54

**Comment by MATsxm** [comment]
@dgt41 Merci :wink:

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on db3c23e09118d049723f9abede0624975898f862<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12114">issues.joomla.org/joomla-cms/12114</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on db3c23e09118d049723f9abede0624975898f862<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12114">issues.joomla.org/joomla-cms/12114</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Pull request merged**
