### PR TITLE
[4.0] - sql fix when CAST using CASE

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #26355 .

### Summary of Changes
Fixed the wrong `CAST`  when using `CASE`

when using case the  return type must be always the same 

### Testing Instructions

#26355 

### Expected result
no error

### Actual result
error on Postgresql

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6bf54bf0c886e135e3aecf4c67cc61dcaa32b26e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26362">issues.joomla.org/tracker/joomla-cms/26362</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 6bf54bf0c886e135e3aecf4c67cc61dcaa32b26e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26362">issues.joomla.org/tracker/joomla-cms/26362</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26362">issues.joomla.org/tracker/joomla-cms/26362</a>.</sub>

**Comment by wilsonge** [comment]
Thanks for working so hard on getting postgres working again :) much appreciated!

**Pull request merged**
