### PR TITLE
[4.0] Fix History Versions Modal display (.es6.js instead of .es5)

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/25147#issuecomment-500205316

### Summary of Changes
Changing js to .es6.js

### Testing Instructions
See https://github.com/joomla/joomla-cms/pull/25147
Apply patch
Make sure the admin-history-versions.es5.js has been deleted in build before running npm

### Expected result
Same as https://github.com/joomla/joomla-cms/pull/25147

@C-Lodder @wilsonge @richard67

### CODE REVIEW

**Review by C-Lodder — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0e4ea35aea2fea02669ca0ced3ff71b30e311bac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25151">issues.joomla.org/tracker/joomla-cms/25151</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0e4ea35aea2fea02669ca0ced3ff71b30e311bac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25151">issues.joomla.org/tracker/joomla-cms/25151</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25151">issues.joomla.org/tracker/joomla-cms/25151</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
tks @C-Lodder

**Pull request merged**
