### PR TITLE
[com_categories] Complete tooltip

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to improves the search tooltip and element label (accessibility) in com_categories.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Go to Content -> Categories, check the tooltip in the search field.

### CODE REVIEW

**Comment by brianteeman** [comment]
Seems strange to search for the author on a category as a category doesnt
really have an author

On 30 April 2016 at 16:11, andrepereiradasilva <notifications@github.com>
wrote:

> Summary of Changes
>
> Simple PR to improves the search tooltip and element label (accessibility)
> in com_categories.
> Testing Instructions
>
> Code review, or:
> 1. Apply patch
> 2. Go to Content -> Categories, check the tooltip in the search field.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/10145
> Commit Summary
>
>    - complete tooltip
>    - category
>
> File Changes
>
>    - *M*
>    administrator/components/com_categories/models/forms/filter_categories.xml
>    <https://github.com/joomla/joomla-cms/pull/10145/files#diff-0> (3)
>    - *M* administrator/language/en-GB/en-GB.com_categories.ini
>    <https://github.com/joomla/joomla-cms/pull/10145/files#diff-1> (3)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/10145.patch
>    - https://github.com/joomla/joomla-cms/pull/10145.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10145>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
i think it does (`created_user_id` in `#__categories`). 

Anyway, check what search the category model does: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/categories.php#L231-L247

**Comment by brianteeman** [comment]
Yes I know that the code works - but its just strange. Categories have a
creator not an author and we never display the value of that anywhere so I
just dont see why you would want to search on this. I would personaly
prefer removing that part of the code

(Content also supports searching by author and it is very relevant there
and also missing from the tooltip)

On 30 April 2016 at 16:27, andrepereiradasilva <notifications@github.com>
wrote:

> i think it does (created_user_id in #__categories).
>
> Anyway, check what search the category model does:
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/categories.php#L231-L247
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10145#issuecomment-215973312>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
> Yes I know that the code works - but its just strange. Categories have a creator not an author and we never display the value of that anywhere so I just dont see why you would want to search on this. I could personaly prefer removing that part of the code

Don't forget com_categories is a vertical component (used with other components) that is used in third party extensions and those may or may not use the `author:`.

Also a creator, IMO, is the author of that category, so i see no problems.

> (Content also supports searching by author and it is very relevant there and also missing from the tooltip)

yeah, i know. another PR for com_content ...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2dda8168dc82c605e28d0c1da6ae3ddf91c971b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10145">issues.joomla.org/joomla-cms/10145</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 2dda8168dc82c605e28d0c1da6ae3ddf91c971b8<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10145">issues.joomla.org/joomla-cms/10145</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10145">issues.joomla.org/joomla-cms/10145</a>.</sub>

**Comment by rdeutz** [comment]
Agree with Brian on the Author for categories topic, this seems wrong, a category is an element for structure content so an being a creator of a category isn`t the same as an author. Anyway this PR only reflects the situation we have ow so I am merging it. But I think we should change it.

**Comment by brianteeman** [comment]
I created #10150 as an issue to remind about removing the author search

On 30 April 2016 at 19:05, Robert Deutz <notifications@github.com> wrote:

> Merged #10145 <https://github.com/joomla/joomla-cms/pull/10145>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10145#event-646583645>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request merged**
