### PR TITLE
Removing unnecessary code from com_search router

### PR DESCRIPTION
**Pull request by Hackwar**
The code that is being removed does nothing. Literally. It acts on an empty array... I was thinking about removing much of the code in parse(), too, but while Joomla itself does not create such URLs, you could hand in the searchword as a first segment and that worked in the past, so we will have to keep that in until at least 4.0...

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks like this was introduce by @wilsonge here #3399

**Comment by SamuelSchepp** [comment]
I have tested this item :white_check_mark: successfully on 6531a19b5a15cdcfeefdd82bb5e66fb3aa97307e<br /><br />Removed code does nothing, since $segments is always array().
Searching by SEF URL index.php/search/my%20word/ still works.
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12482">issues.joomla.org/tracker/joomla-cms/12482</a>.</sub>

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on 6531a19b5a15cdcfeefdd82bb5e66fb3aa97307e<br /><br />

## Tested

### Search

1. Go to <myinstallpath>/index.php/search
2. Search for some content
3. Go to <myinstallpath>/index.php/search/<some%20content> (which is a SEF URL)
4. Activate bugfix
5. Go to <myinstallpath>/index.php/search
6. Search for some content
7. Go to <myinstallpath>/index.php/search/<some%20content> (which is a SEF URL)

## Behaviour

### Removed code does not change anything

Comparing the results of the test (step 1-3 and 5-7), there is no difference. The usual search as well as SEF URLs still work. The removed code does not affect anything since $segments is always an empty array.

Tested @iCampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12482">issues.joomla.org/tracker/joomla-cms/12482</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
