### PR TITLE
Control panel module titles

### PR DESCRIPTION
**Pull request by brianteeman**
The indented alignment of the module titles really bugs me
#### Before

before
#### After

after

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
bulk redirrect language strings?

**Comment by brianteeman** [comment]
Oops they shouldn't be there. I will check and fix in the  morning

**Comment by brianteeman** [comment]
@andrepereiradasilva fixed the PR to remove the language string changes

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8d02eaba74929907365acbf05db1fcd455289e0f<br /><br />Now only left to normalize the dates and column widths (logged in users is different).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10018">issues.joomla.org/joomla-cms/10018</a>.</sub>

**Comment by brianteeman** [comment]
I will do logged in users in a different PR

On 21 April 2016 at 11:14, andrepereiradasilva <notifications@github.com>
wrote:

> I have tested this item [image: :white_check_mark:] successfully on
> 8d02eab
> <https://github.com/joomla/joomla-cms/commit/8d02eaba74929907365acbf05db1fcd455289e0f>
>
> Now only left to normalize the dates and column widths (logged in users is
> different).
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10018
> <https://issues.joomla.org/tracker/joomla-cms/10018>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10018#issuecomment-212843772>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
brian i noticed in your css changes that tou're changng modal classes and prototstar? something is not correct.

**Comment by brianteeman** [comment]
I changed one line in the less and then ran generatesss.php

**Comment by andrepereiradasilva** [comment]
so something has merged with running generatecss ...

**Comment by brianteeman** [comment]
Probably means a previous update was not done correctly. Most likely
someone manually edited the less and CSS files

**Comment by andrepereiradasilva** [comment]
or it can be your joomla is not the latest staging

**Comment by brianteeman** [comment]
I just double checked on a completely new and 100% up to date branch and the generatess.php results are exactly the same as here so some earlier PR did not do it correctly

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d02eaba74929907365acbf05db1fcd455289e0f<br /><br />Looks much better indeed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10018">issues.joomla.org/joomla-cms/10018</a>.</sub>

**Comment by brianteeman** [comment]
I am making this RTC - maintainer please see my comments above about the css and less files. the problem is not with this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10018">issues.joomla.org/joomla-cms/10018</a>.</sub>

**Comment by rdeutz** [comment]
could it that with this change https://github.com/brianteeman/joomla-cms/commit/477863c346dd02aaf14f65cad17425e45472bd0c the less file wasn't changed? Going to merge it anyway.

**Comment by andrepereiradasilva** [comment]
hey, don't blaim me :smile:  i think did it in the less to https://github.com/joomla/joomla-cms/pull/9703/files

**Pull request merged**
