### PR TITLE
[4.0] Enabled not published

### PR DESCRIPTION
**Pull request by brianteeman**
Site languages are enabled/disabled (in the extension manager) not published/unpublished

This PR corrects the language strings in the multilanguage status module to reflect that.

PR for #25580

### CODE REVIEW

**Comment by infograf768** [comment]
Although this would be better, it does not solve the real bug.
See: https://github.com/joomla/joomla-cms/issues/25580#issuecomment-511762580

**Comment by brianteeman** [comment]
That's a completely different issue.

**Comment by infograf768** [comment]
Yes, it is. This is why I wrote: "Although this would be better, it does not solve the real bug."
As an information... Just an information.

**Comment by brianteeman** [comment]
Drone error is unrelated to this PR and is fixed by #25585

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 41ad38bee2d31a56dbccc33191c5860e852e62f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25584">issues.joomla.org/tracker/joomla-cms/25584</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d3343bacb482ea2c907add2977500f89422b05e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25584">issues.joomla.org/tracker/joomla-cms/25584</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25584">issues.joomla.org/tracker/joomla-cms/25584</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
