### PR TITLE
[4.0] Improve backend edit account

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
PR https://github.com/joomla/joomla-cms/pull/32771 allows users without core.manage permission to edit their own accounts directly via com_users instead of via view profile of com_admin (view profile later was removed via PR https://github.com/joomla/joomla-cms/pull/32933)

However, it causes some changes when a manager edit his account:

- He can now change username even if **Change Username** parameter in com_users set to No
- He can see and changes some settings which he should not be allowed to change like Receiving System Emails, User Status...

This PR fixes that behavior. Basically, for users without core.manager permission, editing his account (now via com_users) should work the same as before (via com_admin)

### Testing Instructions

1. Apply Patch
2. Login to administrator area of your site using a manager user account
3. Access to **Edit Account** link from User Menu at the top right
4. Before patch:
- You can change username (when **Change Username** parameter in com_users set to **No** - default Joomla 4 setting)
- You can see some fields: Last Reset Date, Password Reset Count, Receive System Emails, User Status
5. After patch:
- You are not allowed to change username when **Change Username** parameter in com_users set to **No** 
- You won't see the fields Last Reset Date, Password Reset Count, Receive System Emails, User Status anymore

### CODE REVIEW

**Comment by joomdonation** [comment]
Ping @ceford since you reported the issue at https://github.com/joomla/joomla-cms/pull/32933#issuecomment-810172356

**Comment by ceford** [comment]
For some reason this PR has no Test or diff buttons when accessed from Patchtester. And I don't know how return test result another way.

I am happy and it is a pass. But I am not sure an Administrator should be allowed to set his own Status to blocked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32947">issues.joomla.org/tracker/joomla-cms/32947</a>.</sub>

**Comment by joomdonation** [comment]
> For some reason this PR has no Test or diff buttons when accessed from Patchtester. And I don't know how return test result another way

Maybe you will have to click on Fetch Data to have Patch Tester fetches the new PRs. I still see the PRs listed (see the attached screenshot)
PRs

There is another way to test if you cannot use patch tester. Just download the update package for this PR https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/32947/downloads/41449/Joomla_4.0.0-beta8-dev+pr.32947-Development-Update_Package.zip , go to **System -> Update -> Joomla** (the URL of that page looks like  http://localhost/joomla4/administrator/index.php?option=com_joomlaupdate ), upload and install this update package. Then you can test it.

> I am happy and it is a pass. But I am not sure an Administrator should be allowed to set his own Status to blocked.

I have same question for this myself. I'm unsure if a user should be able to change his Status to Blocked. However, that's the current behavior of Joomla! and I don't want to touch it. For this PR, I just want to address the issue which you reported (make sense BTW).

**Comment by ceford** [comment]
On submitting test result - in Patchtester I have done Reset and Fetch Data (twice). For this PR in the Joomla Issue Tracker I see this:

screen shot 2021-04-01 at 06 02 34

In comparison to other PRs such as this:

screen shot 2021-04-01 at 06 03 16

In the first example (this PR) the Diff link and Test this button are missing so I can't submit a test result. I have applied the patch and tested it but I don't know another way to return a result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32947">issues.joomla.org/tracker/joomla-cms/32947</a>.</sub>

**Comment by joomdonation** [comment]
@ceford Ah, Yes. I see. I could not see submit test result button in issue tracker, too, so strange. So have you tested this PR yet? If it is a success, maybe you can leave a comment here so that maintainer knows about it.

**Comment by infograf768** [comment]
👍 Works fine. (Submit test is not available in https://issues.joomla.org/tracker/joomla-cms/32947 )<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32947">issues.joomla.org/tracker/joomla-cms/32947</a>.</sub>

**Comment by ceford** [comment]
👍 Works fine. Count this as a test Pass.

**Comment by joomdonation** [comment]
Thanks @ceford and @infograf768 for testing.

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32947">issues.joomla.org/tracker/joomla-cms/32947</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
