### PR TITLE
Template menu assign fix & styling

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Currently there is an issue with the template menu assignment. This PR fixes the issue along with some minor styling tweaks.

### Testing Instructions
Apply patch and navigate to template assignment.

**Before Patch**
template-assign1

**After Patch**
template-assign2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on ece00ecaa1a81f99efff703fbbe1f05409f8d580<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13280">issues.joomla.org/tracker/joomla-cms/13280</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ece00ecaa1a81f99efff703fbbe1f05409f8d580<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13280">issues.joomla.org/tracker/joomla-cms/13280</a>.</sub>

**Comment by dgt41** [comment]
RTC

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13280">issues.joomla.org/tracker/joomla-cms/13280</a>.</sub>

**Comment by zero-24** [comment]
Merged Thanks :+1:

**Pull request merged**
