### PR TITLE
Fix domain checking for request

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #39969 and #39970 and #39580.

Alternative to PR #39970 .

### Summary of Changes

Better checking for domain 

### Testing Instructions
Apply patch, run `npm install`
Please follow #39969

### Actual result BEFORE applying this Pull Request
Installation broken

### Expected result AFTER applying this Pull Request
Installation works

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by richard67** [comment]
@Fedik Is this an alternative for PR #39970 ? Or is it an addition to it?

**Comment by Fedik** [comment]
This is alternative

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a632e7e3b77ea73f062f4f9514fb4ab9c5ccb41c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40080">issues.joomla.org/tracker/joomla-cms/40080</a>.</sub>

**Comment by joomdonation** [comment]
So I tested it and it solved the issue. Sending test mail from Global Configuration is still working, too

However, there is one case which I think the test does not pass. Assume the current site is http://localhost/joomla42, if ajax request make to http://localhost/joomla43, the token is still send. It's not a big thing, I guess, so if you confirm that it is OK, I will report my test result @Fedik

**Comment by obuisard** [comment]
Tuan @joomdonation can you confirm the test is ok and report in the issue tracker? Thank you!

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on a632e7e3b77ea73f062f4f9514fb4ab9c5ccb41c<br /><br />Not 100% accurate but should be OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40080">issues.joomla.org/tracker/joomla-cms/40080</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40080">issues.joomla.org/tracker/joomla-cms/40080</a>.</sub>

**Comment by obuisard** [comment]
Thank you Fedir @Fedik for the PR!

**Comment by Fedik** [comment]
> Assume the current site is http://localhost/joomla42, if ajax request make to http://localhost/joomla43, the token is still send

As long as you an owner of the domain, that should be fine :)

**Pull request merged**
