### PR TITLE
Stop extension installation if minimum requirement isn't met.

### PR DESCRIPTION
**Pull request by Bakual**
PR https://github.com/joomla/joomla-cms/pull/3447 introduced a new class `JInstallerScript` which allows to specify a minimum PHP and Joomla version for extensions by simply setting the respective property in the extensions script file (assuming it extends that class).
The check is done during the `preflight` stage.

### Summary of Changes
* Changing those checks so they actually return false if the minimum requirement fails, aborting the installation with an error message. Currently it just shows the warning but the extensions still installs.
* Changing the version check so it is indeed a minimum requirement. Currently the specified minimum version is considered "to low".

### Testing Instructions
If you have an extension already using those features, test that it works as expected. Adjust the minimum versions and check that installation succeeds/fails as expected.

### Expected result
If the installation doesn't meet the minimum requirements, the extension should not install.
If the installation meets exactly the minimum requirements, the extension should install without any message.

### Actual result
Installation isn't aborted at all and if the minimum requirement is met exactly, the message is still shown.

### Documentation Changes Required
None

Pinging @wilsonge since he was the original writer of those lines.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]
Looks fine to me. The return false thing is clearly a bug. As to whether the minimum version should accept the same version, I guess it should, but I think that's more just an opinion than anything else *shrug*

**Comment by brianteeman** [comment]
@bakual if you can provide an extension to use for testing it will get tested faster :)

**Comment by Bakual** [comment]
Sure thing. I've adjusted my component so it requires Joomla 3.7.3 and PHP 7.1.0 as minimum.
Without this PR you will get a message that it doesn't meet the minimum requirements but it still installs. With the PR applied the installation will be aborted and you get the message that either the PHP version (if you're under PHP 7.1.0) or the Joomla version doesn't meet the requirements.
[com_sermonspeaker.zip](https://github.com/joomla/joomla-cms/files/1036660/com_sermonspeaker.zip)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 864de8059abe8253e5dfe50dace67f814a7f50cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15890">issues.joomla.org/tracker/joomla-cms/15890</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 864de8059abe8253e5dfe50dace67f814a7f50cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15890">issues.joomla.org/tracker/joomla-cms/15890</a>.</sub>

**Comment by brianteeman** [comment]
@bakual see how quick that was :)

**Pull request merged**
