### PR TITLE
Admin Status Module

### PR DESCRIPTION
**Pull request by brianteeman**
Update the Module description - it does a lot more than described
Change the Module options to use Show/Hide instead of Yes/No which makes it more consistent with the Joomla UI
Update the labels to account for the change to Show//Hide

##Before

screenshotr11-56-22

##After

screenshotr12-05-34

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 0f9fdbd3130c5033f9bf702da06336a92e5c88d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14570">issues.joomla.org/tracker/joomla-cms/14570</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 0f9fdbd3130c5033f9bf702da06336a92e5c88d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14570">issues.joomla.org/tracker/joomla-cms/14570</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14570">issues.joomla.org/tracker/joomla-cms/14570</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
possible Enhancement #14130

**Pull request merged**
