### PR TITLE
[3] com_tags, Tagged Items, Remove error-prone structured data markup

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27358
and additional find with tagged com_banners.category

### Testing Instructions
- Create a tag `TagA`.
- Add this tag to some articles.
- **Add intro images to these articles.**

- Go to `Banners: Categories`
- Add tag `TagA` to a category.

- Create a menu item of type "Tagged Items":

- Leave `Content Type` empty.

- Tabulator `Tag Options` > **Set "Item Image" to "Show"**

- Go to https://search.google.com/structured-data/testing-tool
and test the new menu item/front-end link.

### Expected result
- No errors

#### 2 errors:

- Error 1 (com_banners.category item): `A value for the url field is required.`
**Not solvable because a com_banners.category item never has a link/url.**
**That's the reason why I removed the (here anyway needless(!)) markup completely instead of solving just error 2.**

- Error 2:
"Duplicate values for itemListElement.url are not allowed."

Reason: Two links inside `ItemList` marked as "url" (1 around headline, 1 around images).

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9ace9e75d17ef7475972cec3534c7f0ba56ad67d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28010">issues.joomla.org/tracker/joomla-cms/28010</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ace9e75d17ef7475972cec3534c7f0ba56ad67d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28010">issues.joomla.org/tracker/joomla-cms/28010</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28010">issues.joomla.org/tracker/joomla-cms/28010</a>.</sub>

**Comment by HLeithner** [comment]
Thanks, if this is needed by a site owner a better override should be possible.

**Pull request merged**
