### PR TITLE
Update Composer dependencies

### PR DESCRIPTION
**Pull request by SharkyKZ**
The last one for some reason ignored PHP constraints.

### Summary of Changes

```
- joomla/string (1.4.3 => 1.4.4)
- joomla/filter (1.3.5 => 1.4.0)
- symfony/polyfill-php55 (v1.12.0 => v1.18.1)
- joomla/registry (1.6.2 => 1.6.3)
- symfony/polyfill-util (v1.12.0 => v1.18.1)
- symfony/polyfill-php56 (v1.12.0 => v1.18.1)
- symfony/polyfill-php71 (v1.12.0 => v1.18.1)
- symfony/polyfill-php73 (v1.12.0 => v1.18.1)
- brumann/polyfill-unserialize (v1.0.4 => v2.0.0)
- typo3/phar-stream-wrapper (v2.1.3 => v2.2.0)
- Updating joomla/filesystem (1.5.2 => 1.6.0)
- Updating symfony/polyfill-ctype (v1.12.0 => v1.18.1)
- Updating symfony/yaml (v2.8.50 => v2.8.52)
- Updating psr/log (1.1.1 => 1.1.3)
```

### Testing Instructions

Browse around, do some Joomla things.

### Expected result AFTER applying this Pull Request

Joomla still works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by zero-24** [comment]
Drone failed on javascript tests. I have just rebooted drone.

**Comment by zero-24** [comment]
cc @HLeithner

**Comment by chmst** [comment]
While testing this PR (applied via patchtester on a 3.9.21) and searching around in the backend I notices the following effect in extensions which I have not on my 3.9.21 site: 

compserpatch

There seems to be some warning which is overwritten when the site i relaoded. Don't know if this is reated to this patch.

**Comment by zero-24** [comment]
Can you see something in the php error log?

**Comment by Quy** [comment]
Close #30215?

**Comment by SharkyKZ** [comment]
@Quy Not yet. See PR https://github.com/joomla-framework/string/pull/28.

**Comment by zero-24** [comment]
> There seems to be some warning which is overwritten when the site i relaoded. Don't know if this is reated to this patch.

hmm i have just tried to reproduce any issues and also checked your error log but i can not found any warning / issue there or in mine. To me it seems that jump is also happening on current installs

**Comment by HLeithner** [comment]
Thanks I see this as 2 positive tests

**Pull request merged**
