### PR TITLE
[4.0] #29722 hidden recaptcha v2

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #29722 .

### Summary of Changes

This PR will add inline styling for the Google invisible reCaptcha v2 and prevents it from hiding behind other elements by adding a huge z-index.

### Testing Instructions

- follow the instructions as mentioned on #29722 
- apply this patch
- no NPM needed
- repeat the instructions

### Actual result BEFORE applying this Pull Request

Google invisible reCaptcha v2 badge is hiding behind other blocks

### Expected result AFTER applying this Pull Request

Google invisible reCaptcha v2 badge is in front of other blocks

### CODE REVIEW

**Comment by brianteeman** [comment]
can it please be done without using an inline style

**Comment by hans2103** [comment]
@brianteeman I was not able to find the exact location of the inline styles on the element. And loading an extra css file when this plugin is enabled does not seem to be a better solution then using the proposed style element.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 5bf6e64539a7d9aa114803c8afcefc1d991c059c<br /><br />It works as described, although getting a V2 Key is a pain. It seems to me the obvious place to put the style is in template.css. Will other template developers want to use a different z-index?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31454">issues.joomla.org/tracker/joomla-cms/31454</a>.</sub>

**Comment by brianteeman** [comment]
@hans2103 the aim is to try and remove inline styles - not easy - but we certainly should not be adding any. This is to allow stricter CSP policies for security.

cc @zero-24 @wilsonge

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5bf6e64539a7d9aa114803c8afcefc1d991c059c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31454">issues.joomla.org/tracker/joomla-cms/31454</a>.</sub>

**Comment by Quy** [comment]
@hans2103 You can see how it is done in PR #31098.

**Comment by hans2103** [comment]
@Quy I know how it is done. The reason I added is using inline styling was to prevent an extra httpRequest.

**Comment by richard67** [comment]
@ceford @gostn This PR has received changes. Could you test again? Thanks in advance.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 39fa0ea2ba37298bedc2d6e4343bf64cf26a80e8<br /><br />It still works. Do we have any information on the extra time needed to fetch a style sheet containing one line?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31454">issues.joomla.org/tracker/joomla-cms/31454</a>.</sub>

**Comment by Fedik** [comment]
> The reason I added is using inline styling was to prevent an extra httpRequest.

You can add it to existing template css, no need inline css or separated css file.
It is template styling issue,  not reCaptcha issue

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 39fa0ea2ba37298bedc2d6e4343bf64cf26a80e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31454">issues.joomla.org/tracker/joomla-cms/31454</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31454">issues.joomla.org/tracker/joomla-cms/31454</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
