### PR TITLE
formfields with Jlayout render

### PR DESCRIPTION
**Pull request by studio42**
This commit render chechboes,chechbos radio and range fields with jLayoutRender, this mean formfield can now be overrided in template and unwanted javascript can be removed or bad display solved(it's the case for bootstrap 3)
I do it with all formfields that can have troubles because javascript or render, that template can override it.
 Thank you to review and test the code.

### CODE REVIEW

**Comment by zero-24** [comment]
Hi @studio42 

is this issue still valid? As the last comment here was on 20 Dec 2013? Also pull requests to the master branch of this repo are not longer accepted. Can you close this pull request and submit a new one against the staging branch, if this issue still exists?
If there is no Response in a month we will close the PR here.

Thanks for understanding!

**Comment by brianteeman** [comment]
Closing as per the comment of @zero-24 above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2678">issues.joomla.org/joomla-cms/2678</a>.</sub>

**Comment by studio42** [comment]
Sorry for non response, but i think the jlayout for form fields does not exist anymore ?
This was a great advance to change default render of from fields but i'm not in the dev group, why spend time to answer for nothing if at end this is completly for nothing ???
Is always Joomla CMS a real developpement for the final users ?

**Comment by studio42** [comment]
I think really that Joomla team do more thinks wrong.
Now the admin mod_menu is rendered by class JAdminCssMenu. And core templates exlucing isis do not work anymore and you have to rewrite all for own menu renders(eg using bootstrap 4.
I know tha most user was using isis, but now Hathor cannot be used anymore.
If you think this right, then simply do this in Front too.
I know the issue is not directly related to jMayout, but i think that curently the dev team go on the wrong way and don't check why the code have to be changed. Eg. changin the user registration class and noone checked the consequence
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/2678">issues.joomla.org/tracker/joomla-cms/2678</a>.</sub>

**Comment by brianteeman** [comment]
There was a reason you were asked to answer a few basic questions when you
posted this. they were not there to make you delete them.

What change are you referring to that has stopped Hathor from working. It's
working in staging for me.

Are you referring to j4 perhaps which is in early stages?

Remember that joomla is a community project. If you have something
constructive to contribute you are always welcome.

**Comment by brianteeman** [comment]
That reply was from my email and I assumed it was a new issue and not one from 2013. The issue numbers are almost the same.

Commenting on a closed issue will not be seen by most people.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/2678">issues.joomla.org/tracker/joomla-cms/2678</a>.</sub>

**Pull request closed without merging**
