### PR TITLE
[com_fields] Add help button to the fields views in the back end

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Adds a help button on the back end views of com_fields. They are static names, was unsure if a similar logic as with com_categories should be implemented.

Ping @infograf768. Are the language strings correct?

### Testing Instructions
- In the back end go to Content -> Fields
- Click on the Help button 
image

### Expected result
A help screen opens.

### Actual result
No button

### CODE REVIEW

**Comment by Sandra97** [comment]
Thaks Alon!
As it's a component, maybe better to name them JHELP_COMPONENT_FIELDS...
I'll create the Help Screens once we're sure for the names.

**Comment by tuts-22** [comment]
The Help button but on clicking on it I get the following error!!!!!screen shot 2017-02-25 at 14 54 42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14239">issues.joomla.org/tracker/joomla-cms/14239</a>.</sub>

**Comment by zero-24** [comment]
@tuts-22 yes this is expected as we need to fix the strigns to `JHELP_COMPONENT_FIELDS:..` and as well create the pages to the docs if that is done the page links should work 😄

**Comment by tuts-22** [comment]
@zero-24 oh..Thanks for the information!!!Then should i mark the test as successful?

**Comment by Sandra97** [comment]
Maybe better to not mark it as successful right now, as we need to be sure that the names of the language strings are the right ones.

**Comment by franz-wohlkoenig** [comment]
should that Issue @tuts-22 wrote be solved by https://github.com/joomla/joomla-websites/issues/852?

**Comment by mbabker** [comment]
Nope.  It doesn't address a page not found issue, he only created a namespace alias for the Help37 namespace to load Help36 until 3.7 releases.

https://docs.joomla.org/Help36:Fields_fields doesn't exist.

**Comment by franz-wohlkoenig** [comment]
thanks for Info, @mbabker

**Comment by laoneo** [comment]
So how do we proceeded here, any maintainer a suggestion?

**Comment by mbabker** [comment]
You also need strings in https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.com_admin.ini so the pages show up in the sidebar of `administrator/index.php?option=com_admin&view=help`.  I wrote https://github.com/joomla/joomla-cms/blob/staging/build/helpTOC.php once upon a time to help make sure that side bar and the static file it is built from stays in sync with the help screen category on the docs wiki but I honestly have no clue what state is in anymore.

As for the `JHELP` keys, I'd suggest following the naming structure from `com_contact` for the new strings:

```sh
JHELP_COMPONENTS_CONTACT_CATEGORIES="Components_Contacts_Categories"
JHELP_COMPONENTS_CONTACT_CATEGORY_EDIT="Components_Contacts_Categories_Edit"
JHELP_COMPONENTS_CONTACTS_CONTACTS_EDIT="Components_Contacts_Contacts_Edit"
JHELP_COMPONENTS_CONTACTS_CONTACTS="Components_Contacts_Contacts"
```

Beyond that, seems fine to me.

**Comment by Sandra97** [comment]
I've created the 4 help screens following Allon's keys. But we can still rename them of course.
If we add JHelp Keys for `com_contact`, I presume we shoud also have JHelp keys for `com_content `and `com_users`?   
Thank you to make my life miserable Michael ;)

**Comment by mbabker** [comment]
You don't need separate keys for each fields context, I'm just suggesting to use the same naming structure so it's consistent is all.  It doesn't matter at this point if it's changed or not though.

The `COM_ADMIN_HELP` keys are definitely needed though as I said for the navigation on that one page.

**Comment by laoneo** [comment]
Added COMPONENTS to the keys and made it available in the help page
image
Guess not it should be ok.

**Comment by infograf768** [comment]
New strings need to be alpha ordered. Thanks.

**Comment by laoneo** [comment]
I never learn that, thanks @infograf768 for the hint. Fixed.

**Comment by laoneo** [comment]
Should we go with the current set up, then I would say it is ready for testing>?

**Comment by franz-wohlkoenig** [comment]
@laoneo is it a Question or a go for testing?

**Comment by laoneo** [comment]
It's more of a question for @infograf768, @Sandra97 and @mbabker.

**Comment by Sandra97** [comment]
3 of the 4 help screens are set up and should work well. 
For the 4th one (Components Fields Fields), I did a mistake while renaming it. Tom will fix it, but it's not yet done.

**Comment by laoneo** [comment]
Very good, so I guess it's up to @infograf768 and @mbabker to give a go for the help keys and then it is ready for testing I would say.

**Comment by Sandra97** [comment]
Tom has fixed the 4th help screen. So everything is ready on JDocs.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 615ff6f1475a23fe76bcaaa931c1cdd29dc4913d<br /><br />Test on Article - Fields:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14239">issues.joomla.org/tracker/joomla-cms/14239</a>.</sub>

**Comment by Sandra97** [comment]
@laoneo, Regarding these lines:

index

Shouldn't it be `Components_Fields... `instead of `Fields_...`?

**Comment by laoneo** [comment]
@Sandra97 done.

**Comment by Sandra97** [comment]
Thank you Allon!

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on fb762a7b322ac5ef89f4f1fcd2a11ac3a836ee39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14239">issues.joomla.org/tracker/joomla-cms/14239</a>.</sub>

**Comment by infograf768** [comment]
@Sandra97 
Looking at this, I saw no specific help is set for multilang associations component although the help button is present with `JToolbarHelper::help('JGLOBAL_HELP');`
Can you take care of that?

**Comment by Sandra97** [comment]
Thanks @infograf768 
I will create them and let you know when done.

**Comment by Sandra97** [comment]
I have tested this item :white_check_mark: successfully on fb762a7b322ac5ef89f4f1fcd2a11ac3a836ee39<br /><br />Followed the instructions, all Help Screens are working as expected, in articles, users as well as contacts. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14239">issues.joomla.org/tracker/joomla-cms/14239</a>.</sub>

**Comment by laoneo** [comment]
Ready for RTC?

**Pull request merged**
