### PR TITLE
[4.1] s/fo/for

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a96275d0c32a7599d9ddbffe668299f6c4b7d2ab<br /><br />@bembelimen Could be merged by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36844">issues.joomla.org/tracker/joomla-cms/36844</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a96275d0c32a7599d9ddbffe668299f6c4b7d2ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36844">issues.joomla.org/tracker/joomla-cms/36844</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36844">issues.joomla.org/tracker/joomla-cms/36844</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
