### PR TITLE
[5.x] Indexer taxonomy language strings

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

With #36748 

> "This PR checks if a translation for the language key exists and if there is none (and debug is not enabled) it will instead display the taxonomy title instead."

It is confusing that this doesnt work if debug is enabled. There is nothing else in Joomla where this is the case and I just wasted a lot of time trying to see why the string wasnt displayed.

I believe that the **_intention_** of the code was to display the language key when "debug language" was enabled not when "debug" was enabled

If you want to create your own value for the key as an override you would expect the key to be displayed in debug language mode (which it is not) and you would not expect the key to be displayed in debug mode 
### Testing Instructions
Perform a search on the front with Debug enabled and a new search with debug language enabled

#### Debug
image

#### Debug Language
image

#### Debug
image

#### Debug Language
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Shouldn't that be fixed in 4.4-dev, as it is a bug fix and the bug also applies there?

**Comment by richard67** [comment]
@brianteeman I think it would help to change the base branch on GitHub by using the "edit" button right beside the title.

**Comment by brianteeman** [comment]
yeah - didnt work - creating a new pr instead

**Comment by richard67** [comment]
> yeah - didnt work - creating a new pr instead

@brianteeman Ok, thanks.

**Pull request closed without merging**
