### PR TITLE
[4.0] Figure out the image size for external adapters

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request is supplamentary to https://github.com/joomla/joomla-cms/pull/33724

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 52520577f8dc2da4dd4f14504b7e181fb03fd8fb<br /><br />I've tested with success as follows:
1. Applied the patch from PR #33724 and installed the dropbox plugin as described there in testing instructions.
2. Removed the guzzlehttp folder from the plugin's vendor folder as described here, so that the one shipped with the CMS is used, to work around the issue linked in that comment, too: https://github.com/joomla/joomla-cms/pull/33724#issuecomment-847081056 .
3. Inserted an image into an article, using an image from the Dropbox.
Result: See https://github.com/joomla/joomla-cms/pull/33724#issuecomment-847044369 .
4. Applied the patch of this PR.
5. Repeated step 3 a few times with different images:
Result: Image is visible, and the  tag has the height and width attributes equal to height and width of the image.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34177">issues.joomla.org/tracker/joomla-cms/34177</a>.</sub>

**Comment by richard67** [comment]
@chmst Could you test this PR as desribed in my test result above?

It's the same test you already have done for @joomdonation 's PR with the external Dropbox adapter.

First check if it has your issue, then apply the patch of this PR here, too, run npm ci and check again.

For me it worked.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 52520577f8dc2da4dd4f14504b7e181fb03fd8fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34177">issues.joomla.org/tracker/joomla-cms/34177</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34177">issues.joomla.org/tracker/joomla-cms/34177</a>.</sub>

**Comment by dgrammatiko** [comment]
# Please DO NOT merge this BEFORE #33724

**Comment by richard67** [comment]
@dgrammatiko The other PR has been merged now. Could you solve here the conflict resulting from that?

**Comment by richard67** [comment]
Previous tests and RTC are still valid since the one commit after the tests was a clean branch update. In addition I have repeated my test with the same result as before, success.

**Pull request merged**
