### PR TITLE
Some improvements in tests #6:

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
- merged unset() calls
- declared a few properties

### Testing Instructions
Code review only.
A lot of unset() merging. Except for 6-7 property declarations. Should be easy to review, though.
PRIORITY: LOWEST

**Unified view for reviewing is recommended.**

### Documentation Changes Required
None

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by laoneo** [comment]
@frankmayer I have another request. Can you also please exclude administrator/com_media from your cleanup please. We are redoing the new media manager and are touching almost any file there. So it will help us to stay up to date with staging.

**Comment by frankmayer** [comment]
@laoneo (You're killing me... :smile:). But of course, I'll exclude that, too, for future work and I will also check the current ones.
But it would also be nice if my existing PR's could finally be reviewed/merged. I have put a lot of work into all of this, and also did a lot of work splitting the really big ones up into more logical chunks to help you people review them.
There are a lot of smaller ones or ones with only one specific type of change, which should be relatively easy to review. When those are merged, I can also move on with conflict resolving of the initial big ones, which will result a lot less changes to finally review those ones, too.
Note, that I am aware that, with my PR's I have also put a lot of weight on the shoulders of the reviewers, but these are one time cleanups that would have to be done either way, to improve Joomla. So, please do help me, help you (Joomla Project :heart:).

**Comment by Quy** [comment]
It would be nice to limit this PR to unset only. I am unsure of the declaration of properties to give this a successful test.

**Comment by frankmayer** [comment]
@Quy You cannot test this in the frontend. These are all changes to the testsuite.
I think, only code review is possible here, and since the tests do pass, it is a sign that those changes did not do any harm.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d9b9ae5f2135732dad6c9550e060f2f15185121e<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13414">issues.joomla.org/tracker/joomla-cms/13414</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d9b9ae5f2135732dad6c9550e060f2f15185121e<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13414">issues.joomla.org/tracker/joomla-cms/13414</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
