### PR TITLE
[#33948] fix email validation, allowing email with new domain name extension

### PR DESCRIPTION
**Pull request by rvbgnu**
J2.5 email addresses with new TLD extensions are not valid upon installation
#### Steps to reproduce the issue
1. Install a new site with Joomla! 2.5.x (I believe it is in all versions). 
2. Provide an admin email address with a new type of extension (e.g. .ninja .expert .company .cool .sexy etc.)
3. Test also any kind of email following these rules:
   
   The local part of an email (text before the "@") may include any of the following characters
   Uppercase and lowercase English letters (a–z, A–Z)
   Digits 0 to 9 
   These special characters: ! # $ % & ’ \* + - / = ? ^ _ ` { | } ~
   Character . (dot, period, full stop) (ASCII: 46) provided that it is not the first or last character, and provided also that it does not appear consecutively (e.g. John..Doe@example.com is not allowed).
#### Expected result

Any email address from current and scheduled domain name should be accepted.
#### Actual result

Address is not accepted as valid.
#### System information (as much as possible)

Initial report on Joomla 2.5.20 - confirmed in 2.5.28-dev
#### Additional comments

Initial issue Submitted By: Ben Shomer - Open Date: 2014-07-14
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33948
fix email validation, allowing email with new domain name extension (more than 4 characters) like new gTLDs
- Adding more test instructions from Jean-Marie https://github.com/joomla/joomla-cms/pull/4899#issue-46596542

### CODE REVIEW

**Comment by davidmdawson** [comment]
You say don't put on a production site... however I am stuck using Joomla 2.5 as our component is not yes ready to move away from an old version of virtuemart.

Now I have the problem on multiple sites that people can't register. 

Will there be a patch for joomla 2.5 that we can use?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4135">issues.joomla.org/joomla-cms/4135</a>.</sub>

**Comment by brianteeman** [comment]
Simple answer is no. There is no official support for Joomla 2.5 any more

On 6 August 2015 at 09:58, davidmdawson <notifications@github.com> wrote:

> You say don't put on a production site... however I am stuck using Joomla
> 2.5 as our component is not yes ready to move away from an old version of
> virtuemart.
>
> Now I have the problem on multiple sites that people can't register.
>
> Will there be a patch for joomla 2.5 that we can use?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/4135
> <http://issues.joomla.org/tracker/joomla-cms/4135>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/4135#issuecomment-128296065>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
>You say don't put on a production site

If this is related to the use of https://github.com/rvbgnu/joomla-cms/archive/2.5.x_fix_33948.zip,  it is no need. This patch has been merged into 2.5.28 in December 2014

**Comment by davidmdawson** [comment]
oh, I still have the problem. I'll look elsewhere then. Maybe an issue with the registration page in virtuemart
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4135">issues.joomla.org/joomla-cms/4135</a>.</sub>

**Pull request closed without merging**
