### PR TITLE
[3.8] Tweak update percentage message to include %-sign

### PR DESCRIPTION
**Pull request by Sophist-UK**
Pull Request for Issue # .

### Summary of Changes

Adds a % character to the end of the progress bar Percent-Progress commentary during a Joomla version upgrade.

### Testing Instructions

Install Joomla previous to current version. Apply fix. Upgrade to current version. During upgrade the Percent-complete line below the progress bar should now end with a '%' character.

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
This is possibly the most trivial possible change ever even when compared to all other trivial changes. Let's not get too hung up on having loads of people regression test it.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 37fe9c6aff253cd616cf963494183b61863b1c01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19628">issues.joomla.org/tracker/joomla-cms/19628</a>.</sub>

**Comment by Sophist-UK** [comment]
@Quy - thanks.

That is already 10x as much effort testing as this trivial change deserves. To be honest an eye-ball review would probably have sufficed.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 37fe9c6aff253cd616cf963494183b61863b1c01<br /><br />Easy and quick to test this
Tested with patch applied the percentage appears as intended
Search through code, there is no code that tries to use the inner HTML of element, so nothing will break by this change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19628">issues.joomla.org/tracker/joomla-cms/19628</a>.</sub>

**Comment by ggppdk** [comment]
Only i see an issue, not directly related to this PR

2 files exist
`media/com_joomlaupdate/js/update.js`
`media/com_joomlaupdate/js/update.min.js`
- but update.js is loaded despite Debug being OFF, i guess this is known and discussed else ?, just i am not aware of it

Also this PR does not update file 'update.min.js'

**Comment by Sophist-UK** [comment]
@ggppdk - I was of the view that minimised versions should not be included in PRs because it prevents two simultaneous PRs both being mergeable - after the first PR is merged, because the minified version is all on one line, the second PR cannot be successfully diffed and so becomes unmergeable. So in my experience on other projects, the minification is typically done as part of a merge process or left for automatic generation as part of a release.

However Joomla's rules may be different - and if so, if someone points me  to the specific way of minifying that Joomla uses, I would be happy to add a minified version.

**Comment by brianteeman** [comment]
Please include the minified ms in this pr and use any minified of your choice

**Comment by Sophist-UK** [comment]
Added - using https://jscompress.com/

**Comment by wilsonge** [comment]
Merging with the good test + on my review

**Pull request merged**
