### PR TITLE
[NF] Menu item visibility indicator

### PR DESCRIPTION
**Pull request by Devportobello**
### Context

The new feature of the menu component allowing to show/hide a menu item from params, when we watch all items we can't know if item is hidden or not.
### Testing Instructions
- Create a menu with some items, hide some with the param: "Display in Menu"
- Take a look at the list of items, unable to know who is hidden or not

Patch
- Now you can know hidden or not
### Work in progress

i dunno if the icon is at the right place (before title)

### CODE REVIEW

**Comment by brianteeman** [comment]
I see what you are trying to do but I dont think this is the correct approach.

As the majority of menu items will be visible I dont see the need to always show the eye-icon

So  I would probably only show the icon for items that are invisible and I would display that after the title.

Also you need some sort of tooltip/popover to explain the meaning of the icon

**Comment by Bakual** [comment]
Instead of showing an icon (with a tooltip) maybe you can just show a small label that says "hidden" behind the title. Similar to how we show unpublished articles in frontend to the admins.

**Comment by brianteeman** [comment]
That would work too

**Comment by Devportobello** [comment]
@brianteeman @Bakual 
Ye i agree with you
Label will add a new text translation, adding "JHIDDEN" in "en-GB.ini" is the right approach ?

**Comment by Bakual** [comment]
I wouldn't make it a global string. It's only used in the menu manager. Just put it into the `en-GB.com_menus.ini` and name it something like `COM_MENUS_LABEL_HIDDEN`.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0b5251db140b482cd1084443574eddfc5da4042a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11998">issues.joomla.org/joomla-cms/11998</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on ba68b2d1968d4e6d538bd0ffb90c88fb9364e83b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11998">issues.joomla.org/joomla-cms/11998</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on ba68b2d1968d4e6d538bd0ffb90c88fb9364e83b<br /><br />Tested successfully at PBF NL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11998">issues.joomla.org/tracker/joomla-cms/11998</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on ba68b2d1968d4e6d538bd0ffb90c88fb9364e83b<br /><br />After applying the patch the hidden notice shows behind the menu item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11998">issues.joomla.org/tracker/joomla-cms/11998</a>.</sub>

**Comment by roland-d** [comment]
Setting to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11998">issues.joomla.org/tracker/joomla-cms/11998</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman @roland-d bot wrongly removed `Language Change` label

**Pull request merged**
