### PR TITLE
[5.2] [feature] Media manager select last uploaded item (iframe)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Select the last uploaded file when media manager is inside an iframe (ie, when selecting an image in a media field or inside an editor)

### Testing Instructions
- Create a new article
- Select an intro image
- navigate to any folder
- Upload an image

The image should be selected

Repeat the same with the CMS Content->Media button in tinyMCE editor

Repeat the same with the media button bellow the Codemirror

### Actual result BEFORE applying this Pull Request

The file was not selected after upload, user needed to pick the file manually

### Expected result AFTER applying this Pull Request

The file is selected after upload, user needed to pick the file manually

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Clicking `Select` or `Insert Media` button does not insert the image. You have to reselect the image, then the button will work.

**Comment by Quy** [comment]
Firefox 128.0 and Chrome Version 126.0.6478.128 on Windows

**Comment by brianteeman** [comment]
Confirming the results from @Quy 

Chrome Windows - Version 126.0.6478.128 (Official Build) (64-bit)

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on b3c304d84b6d744f433494b6c9ccd99218678dfc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by dgrammatiko** [comment]
> User selection happen on click, then that "select event" is triggered

I'm **NOT** doing an automatic insertion of the uploaded image, I just set the state of the selected file! (means the user still needs to press the insert button, but in this case the file is already selected no need to search for it...) BTW the issue was about `SELECTING` the image not automatically inserting it, that's a different case

**Comment by dgrammatiko** [comment]
@Quy @brianteeman should be ok for all browsers now (tested with Chrome, Webkit, FF)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f669b9fc062d1429458d22691fa415c6bd209813<br /><br />works as intended now - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f669b9fc062d1429458d22691fa415c6bd209813<br /><br />Thank you!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by dgrammatiko** [comment]
Just a note for the person that would merge this PR: please merge first PR #43579 and then this one.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on d357b4ca2b4028e77127aee0ca9153de2106d921<br /><br />Tested image in editor and intro image. Also with the DPMedia restricted plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by Hackwar** [comment]
@Quy @brianteeman could you test this again? There were some changes lately and we are missing one more test.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0d98552281ac0954daff56ddd135935c59fdb4ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43823">issues.joomla.org/tracker/joomla-cms/43823</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @dgrammatiko! 😊

**Pull request merged**
