### PR TITLE
Improve search syntax in backend User Manager

### PR DESCRIPTION
**Pull request by joomdonation**
## PR Summary

This PR makes small improvement to search feature in User Manager from backend to allow searching for exactly user base on given ID or username:
- Enter id:42 will return the user has ID = 42 in your system.
- Enter username:admin will return user has username = admin in your system

This is useful in case you want to find a user when you know username or user id in a site has thousands of users.
## Testing instructions

Login to backend of your site, access to User -> User Manager:
- Try to search for user by enter keyword into the searchbox and make sure the search feature still work well
- Try to use syntax id:ID_OF_USER, for example id:42 and make sure only user with that id is returned
- Try to use syntax username:USER_NAME_OF_USER and make sure only user with that username (or similar) returned.

### CODE REVIEW

**Comment by sovainfo** [comment]
Send you a PR on code improvement on $query.

**Comment by joomdonation** [comment]
Thanks @sovainfo. Merged.

**Comment by sovainfo** [comment]
Thanks for accepting, tested succesfully.

Request for to be labelled as "New Feature". Please refer to documentation on using labels when this request is denied. Haven't been able to find any!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6755">issues.joomla.org/joomla-cms/6755</a>.</sub>

**Comment by Dylis** [comment]
@test - Patch working as expected :  id:ID_OF_USER, username:USER_NAME_OF_USER, and simple keyword search, all 3 syntaxes returning correct answer after applying patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6755">issues.joomla.org/joomla-cms/6755</a>.</sub>

**Comment by vinespie** [comment]
@test - succes - correct answer after applying patch
It's the same feature in article manager (id:ID_OF_ARTICLE)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6755">issues.joomla.org/joomla-cms/6755</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks for the tests here :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6755">issues.joomla.org/joomla-cms/6755</a>.</sub>

**Comment by wilsonge** [comment]
Merged into 3.5-dev branch - thanks!

**Pull request closed without merging**
