### PR TITLE
[4.1] All Categories

### PR DESCRIPTION
**Pull request by brianteeman**
Create a new menu item of type featured or archived articles -> Select Blog Layout Tab -> look at the category selector

Pull Request for Issue #33556 .

## Before
image

## After
image

### CODE REVIEW

**Comment by Quy** [comment]
See custom fields where the value is `0`. https://github.com/joomla/joomla-cms/blob/ab70aeac3c3203042704da8529a692013e054fef/administrator/components/com_fields/forms/field.xml#L41

**Comment by brianteeman** [comment]
What does that have to do with this?

**Comment by Quy** [comment]
For consistency.

**Comment by brianteeman** [comment]
I am happy with how this PR is.

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 69f47d34e1d8f7b1e13fcc3081f88da1b6e50c54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37140">issues.joomla.org/tracker/joomla-cms/37140</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 69f47d34e1d8f7b1e13fcc3081f88da1b6e50c54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37140">issues.joomla.org/tracker/joomla-cms/37140</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37140">issues.joomla.org/tracker/joomla-cms/37140</a>.</sub>

**Comment by bembelimen** [comment]
Tbh I don't like the solution that much, but have no better idea.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
