### PR TITLE
Add workflow strings

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add missing language strings for the frontend from #39325.

### Testing Instructions
Enable Workflow.
Edit an article on the frontend.
Go to the Publishing tab.

### Actual result BEFORE applying this Pull Request
39325-workflow

### Actual result AFTER applying this Pull Request
39325-workflow-pr

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 27121e3df1e5a8528b26cf88732f4b23ce6836f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39680">issues.joomla.org/tracker/joomla-cms/39680</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 27121e3df1e5a8528b26cf88732f4b23ce6836f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39680">issues.joomla.org/tracker/joomla-cms/39680</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39680">issues.joomla.org/tracker/joomla-cms/39680</a>.</sub>

**Comment by obuisard** [comment]
Thank you @Quy !

**Pull request merged**
