### PR TITLE
[4.0] Load JS message titles on login

### PR DESCRIPTION
**Pull request by brianteeman**
If you get an error on login eg by hitting login without filling any field then the resulting error message has an untranslatable and lowercase "error" as the title

This PR fixes that

For completeness, consistency and future proof I added the other error message strings

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2d37fac97267b1f9a5ad6bc7a710b1c02dc79941<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25474">issues.joomla.org/tracker/joomla-cms/25474</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2d37fac97267b1f9a5ad6bc7a710b1c02dc79941<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25474">issues.joomla.org/tracker/joomla-cms/25474</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25474">issues.joomla.org/tracker/joomla-cms/25474</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
