### PR TITLE
Addition of a new module submenu under administrator extension drop down menu.

### PR DESCRIPTION
**Pull request by shubhamnba2009**
#### Summary of Changes

1.Added a new sub menu under module option provided in extension drop down menu.
2.Changes made can also be seen in Hathor template.
#### Testing Instructions

1.Before applying patch no sub menu under module option provided in extension drop down menu.
2.Apply patch
3.New submenu to Add New Module is created.
4.Check with hathor template also.

### CODE REVIEW

**Comment by brianteeman** [comment]
1. if you look in the options for the admin menu module you will see an option to enable or disable the "Add New Shortcuts" this is done in code by using 	if ($createContent) so this PR would need that as well 

2. The bigger problem is that when you use this new add module link it doesnt know if you are creating a site or an admin module. If the last filter used in the module manager was admin then the new module link will create admin modules etc (I think this is why the menu link was never created)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9845">issues.joomla.org/joomla-cms/9845</a>.</sub>

**Comment by shubhamnba2009** [comment]
Just some doubts @brianteeman 
1. I went to module manager and set the Edit module option to "Administrator".

After coming back to Module dialogue box it was like this
pic

The area i have marked in black rectangular box, should'nt it show "Modules(Administrator)"?
Maybe i had got a wrong idea, if u can clear.

2.I was unable to locate admin menu module option to enable and disable shortcuts. Could you point me in its direction.
 Thanks in advance<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9845">issues.joomla.org/joomla-cms/9845</a>.</sub>

**Comment by brianteeman** [comment]
### Part 1
screen shot 2016-04-11 at 05 54 41

### Part 2
screen shot 2016-04-11 at 05 52 22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9845">issues.joomla.org/joomla-cms/9845</a>.</sub>

**Comment by shubhamnba2009** [comment]
Ohh! now i see!!
By directly adding a new module submenu confusion can occur whether it is for Administrator or for Site.

I think than this pull request is not necessary.

Btw I think there is a bug if you can confirm.

1. Click on the top-right "options" button
new

2. Select "Administrator" in edit module option.
n

3. After saving and closing it It still redirects to the "Modules(site)" page, I think it should redirect to "modules(administrator)" page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9845">issues.joomla.org/joomla-cms/9845</a>.</sub>

**Comment by brianteeman** [comment]
OK I will close this

As for your other issue. I dont think its a bug. clicking cancel or save always returns to the page you were on previously. The option you are selecting is to chose the default setting when you select modules from the menu

**Pull request closed without merging**
