### PR TITLE
[4.0] Use setDocumentTitle for com_contact

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes small clean up to contact and featured view of com_contact. It uses setDocumentTitle method of HtmlView class to set document title instead of calculating the title manually (reduce repeating code)

### Testing Instructions
1. Create two menu items: One links to Featured menu item type and one links to Single Contact menu item type of com_contact
2. Access to the menu items, make sure page title (and how the page is being displayed) is the same before and after patch

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 04aa267bb296c064ccaef7a03b9725bbf7b9d569<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32311">issues.joomla.org/tracker/joomla-cms/32311</a>.</sub>

**Comment by richardfrederik67** [comment]
I have tested this item :white_check_mark: successfully on 04aa267bb296c064ccaef7a03b9725bbf7b9d569<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32311">issues.joomla.org/tracker/joomla-cms/32311</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 04aa267bb296c064ccaef7a03b9725bbf7b9d569<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32311">issues.joomla.org/tracker/joomla-cms/32311</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32311">issues.joomla.org/tracker/joomla-cms/32311</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
