### PR TITLE
[4.0] Learn more

### PR DESCRIPTION
**Pull request by brianteeman**
Sync the string from admin to api
Add the string to site

Change all to match the style guide.

PR for #34543

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 7413989d992c6f4fc6ac431faf4e1d3b382a2518<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34550">issues.joomla.org/tracker/joomla-cms/34550</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7413989d992c6f4fc6ac431faf4e1d3b382a2518<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34550">issues.joomla.org/tracker/joomla-cms/34550</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34550">issues.joomla.org/tracker/joomla-cms/34550</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
