### PR TITLE
[4.0] Javascript tweaks

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

- Remove some unecessary code for IE
- Remove `html5.js` and `html5fallback.js`
- Remove `"use strict";` calls in ES6 files as they're not required
- Update `draggable.js` to ES6

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for doing this

**Comment by dgrammatiko** [comment]
ES6 or greater is not forcing strict mode *unless* you’re in module mode, eg the de facto for current code. Also if you wanna go this way you should drop all the iife as these were an ES5 technic. 
I think there is a greater question/problem that needs to be answered before any of these enhancements get merged and that is: “is joomla willing to really follow the new JavaScript paradigm?”

**Comment by Fedik** [comment]
I am agree with @dgrammatiko . `"use strict";` must stay.
It does not enabled magically if you start to use `() => {}` instead of `function(){}`. It a question about a scope isolation.

**Comment by Fedik** [comment]
@C-Lodder but other parts was good :wink:

**Comment by C-Lodder** [comment]
@Fedik - I'll submit a new PR ;)

**Comment by C-Lodder** [comment]
@Fedik @dgrammatiko https://github.com/joomla/joomla-cms/pull/25227

**Pull request closed without merging**
