### PR TITLE
[4.0] Fix navigation path to database check in language string after PR #34366

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Adapt a language string for the pre-update check to changes from merged PR #34366 .

### Testing Instructions

Code review, or make that a database error is shown by the database check e.g. by adding a new, empty update SQL script "4.0.0-2021-06-03.sql", and then checking the pre-update check.

### Actual result BEFORE applying this Pull Request

2021-06-03-pre-update-check

### Expected result AFTER applying this Pull Request

The right way to the database check is shown.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman Please test.

**Comment by richard67** [comment]
@brianteeman Should this language string be renamed, too?

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/mod_menu.ini#L131

**Comment by brianteeman** [comment]
Well remembered - thanks for fixing.

I "think" the other string is used in the alternate menu? If so then it doesnt need changing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34376">issues.joomla.org/tracker/joomla-cms/34376</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 753553fdeae14df04f2572fd4c4235475c4dfa70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34376">issues.joomla.org/tracker/joomla-cms/34376</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
