### PR TITLE
[4.0] use Joomla\CMS\Factory

### PR DESCRIPTION
**Pull request by brianteeman**
error from https://github.com/joomla/joomla-cms/commit/aef4d2f576c8e1ccf8e6af6544adfda0f64bb902

code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c563b4fbc5ed66e84cde97e369262997f2516b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31686">issues.joomla.org/tracker/joomla-cms/31686</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c563b4fbc5ed66e84cde97e369262997f2516b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31686">issues.joomla.org/tracker/joomla-cms/31686</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31686">issues.joomla.org/tracker/joomla-cms/31686</a>.</sub>

**Comment by infograf768** [comment]
There are other errors in this file related to last merge. Usage of `strtotime()` is wrong as stated in maintainers chat.

@wilsonge Are you going to debug your last merge and correct all issues or shall we correct one at a time?

**Comment by wilsonge** [comment]
Thanks 

> @wilsonge Are you going to debug your last merge and correct all issues or shall we correct one at a time?

I'll do what I can but I'll still probably miss some parts. i'm focussing on the downloads site translation pack stuff - so if you have time feel free to submit something

**Comment by brianteeman** [comment]
Please stop bikeshedding

thanks for merging

**Comment by infograf768** [comment]
> Please stop bikeshedding

I had a good reason to ask George about that. So, please cool down.

https://github.com/joomla/joomla-cms/pull/31689

**Pull request merged**
