### PR TITLE
Use simpler db query for admin mod_menu, without GROUP BY

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #12983 and in general.

### Summary of Changes
Use more simpler and faster query and return the same result.

* return the same result
* do not use GROUP BY

### Testing Instructions

1. Go to backend and check whether menu items display the same list of items before and after patch.
2. It would be good to test it on multi language menu.

Before query:
```sql
SELECT a.*, SUM(b.home) AS home,b.language,l.image,l.sef,l.title_native
FROM j37_menu_types AS a
LEFT JOIN j37_menu AS b ON b.menutype = a.menutype AND b.home != 0
LEFT JOIN j37_languages AS l ON l.lang_code = language
WHERE (b.client_id = 0 OR b.client_id IS NULL)
GROUP BY a.id, a.menutype, a.description, a.title, b.menutype,b.language,l.image,l.sef,l.title_native
```

menu_no_group2

After query:
```sql
SELECT a.id, a.asset_id, a.menutype, a.title, a.description, a.client_id,c.home, c.language, c.image, c.sef, c.title_native 
FROM j37_menu_types AS a 
LEFT JOIN ( 
    SELECT b.menutype, b.home, b.language, l.image, l.sef, l.title_native 
    FROM j37_menu AS b 
    LEFT JOIN j37_languages AS l ON l.lang_code = b.language 
    WHERE b.home != 0 AND (b.client_id = 0 OR b.client_id IS NULL)
) c ON c.menutype = a.menutype
ORDER BY a.id
```

menu_no_group3

### Expected result
Works as before but for tables with more rows it works faster.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by wilsonge** [comment]
Given you've been doing all the sqlsrv patches I'm assuming you've tested this on there given the group by comment?

**Comment by csthomas** [comment]
I'm not sure I understand you correctly. 
This PR is not related to single db type.

I have tested it on localhost on mysql and a few minutes ago on mssql too.

**Comment by csthomas** [comment]
This PR replace current joomla query `... GROUP BY ...` with simpler one which does not require `GROUP BY`. Results of query should be the same across all DBs.

**Comment by wilsonge** [comment]
I know it's not. But given the group by comment is `Sqlsrv change` it seemed prudent to check this didn't affect sqlsrv :)

I like the concept for sure!

**Comment by csthomas** [comment]
I assume you talk about https://github.com/joomla/joomla-cms/commit/ef3bafc3c4f9829f3cf5482098bd37aceb53590c#diff-a296558abf749881f99f0297bb5c725bL38

There was change which support ONLY_FULL_GROUP_BY. 
What I have read J4 will required it for all queries.

For this PR I changed the entire query to  another one which works in different way. I ask for tests on multilingual joomla to be sure that I not make a mistake in my theory:)

**Comment by csthomas** [comment]
@ggppdk I have changed the code to fit your needs. 
I do not want to change query but one php loop seems to resolve your problem.

**Comment by ggppdk** [comment]
> @ggppdk I have changed the code to fit your needs.
> I do not want to change query but one php loop seems to resolve your problem.

It seems that your PHP loop tries to count multiple home menu items inside same menu, 
thus achieving the same result as doing it at the SQL Query

sorry no time to test and verify if it works like this:
https://github.com/joomla/joomla-cms/pull/12991#issuecomment-262836905

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on aecd3e47af48aaffef9774367c5afc30e2192a8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14011">issues.joomla.org/tracker/joomla-cms/14011</a>.</sub>

**Comment by csthomas** [comment]
The last commit (add order by a.id) is for types of database other than mysql innodb.

**Comment by infograf768** [comment]
After a discussion in bugsquad, I suggest to let open a future implementation of multiple home pages (when set to a lang else than ALL). This would be done in the libraries.
I.e. I suggest to just concentrate on the faster query if really necessary.
1.7 is a dead fish.

**Comment by csthomas** [comment]
I have removed old workaround for multiple home pages.
Now is only optimised query.

**Comment by alikon** [comment]
didn't tested on a big #__menu table  but EXPLAIN looks far better now

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fa5d3fa52984b7e57694d8725d6f75eb3f940f58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14011">issues.joomla.org/tracker/joomla-cms/14011</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on fa5d3fa52984b7e57694d8725d6f75eb3f940f58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14011">issues.joomla.org/tracker/joomla-cms/14011</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
