### PR TITLE
[4.2] Grammar child/children

### PR DESCRIPTION
**Pull request by brianteeman**
The error message when you try to uninstall a template that still has child templates says "children". It is better to say "child" and that is the word used everywhere else.

image

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 457ebede43ab6c14f27fd74e2d120a0c0377231a<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39143">issues.joomla.org/tracker/joomla-cms/39143</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 457ebede43ab6c14f27fd74e2d120a0c0377231a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39143">issues.joomla.org/tracker/joomla-cms/39143</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39143">issues.joomla.org/tracker/joomla-cms/39143</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
