### PR TITLE
Adding back in a rule to match on specific files for .htaccess

### PR DESCRIPTION
**Pull request by Hackwar**
This is an attempt to fix the issue in #4955. Please test

### CODE REVIEW

**Comment by brianteeman** [comment]
So after 2 months with no progress on this issue can we close it as not Joomla core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4957">issues.joomla.org/joomla-cms/4957</a>.</sub>

**Comment by zero-24** [comment]
Closing as requested by @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4957">issues.joomla.org/joomla-cms/4957</a>.</sub>

**Comment by wilsonge** [comment]
I'm reopening this based on some feedback from @nikosdion where apparently the original removing PR

```Unfortunately, on some servers this makes it impossible to access /administrator OR /administrator/index.php```

Nic's shipped this patch out with the latest admin tools versions so I'm going to await feedback and merge assuming there were no issues.

**Comment by Bakual** [comment]
This PR is far from having no issues. It breaks the page. That's why it has been closed and since there was no progress to actually fix the PR. Imho makes no sense to have a non-working PR open for such a long time. If the issue is valid, create a new one or reopen the old one.

**Comment by wilsonge** [comment]
Can you try replicating that again please? I just implemented this on my site (http://joomjunk.co.uk/) and as you can see there are no menu issues. If so can you list server details please?

**Comment by Bakual** [comment]
Ah true, the later commits fixed it. I can't say if it fixes the 401 issue but at least it doesn't look like it's breaking URLs.

**Comment by nikosdion** [comment]
I have tested this code on my Mac (Zend Server), Apache on Windows (custom build per my blog’s instructions), Ubuntu Server (per my published Vagrant setup scripts), another Ubuntu Server with Zend Server and two live sites on Rochen and SiteGround. I had no issues with SEF URLs, with and without redirections, with and without suffixes. I am waiting for my clients to give me feedback since I have applied the same change on Admin Tools’ .htaccess Maker.=

**Comment by brianteeman** [comment]
As this change was reverted in admintools as it was found to not be a good solution I am therefore closing tis PR once again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4957">issues.joomla.org/joomla-cms/4957</a>.</sub>

**Comment by JialuZhang** [comment]
@Bakual @Webdongle 

In Apache configuration,
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
The default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users. :)

Thereby, simply leaving off the configuration parameter "RewriteEngine"
would be enough and ideal.

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Pull request closed without merging**
