### PR TITLE
[4.0] COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC

### PR DESCRIPTION
**Pull request by brianteeman**
Clarify the message in accordance with php.net

pr for #30098

### CODE REVIEW

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 430cfd4d6529998bb947cafb6713693dec56e36a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 430cfd4d6529998bb947cafb6713693dec56e36a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by infograf768** [comment]
Looks like we have 2 contradictory tips here.

This patch
 COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC="The maximum file size for uploads is set to less than 8MB which may impact on uploading large extensions. This is set in php.ini in both the upload_max_filesize and post_max_size settings of your PHP settings (located in php.ini and/or .htaccess file). **The value of post_max_size must be greater than the value of upload_max_filesize.**"
 
 but we have below:
 
  COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC="The value of the upload_max_filesize in the php.ini file is greater than the post_max_size variable. The post_max_size variable will take precedence and block requests larger than it. This is generally a server misconfiguration when trying to increase upload sizes. **Please increase the upload_max_filesize to at least match the post_max_size variable or vice versa.**"

**Comment by infograf768** [comment]
Moved back to pending because of  https://github.com/joomla/joomla-cms/pull/31736#issuecomment-749410561

**Comment by brianteeman** [comment]
Maybe I need coffee but where is the contradiction?

**Comment by infograf768** [comment]
`The value of post_max_size must be greater than the value of upload_max_filesize.`
vs
`Please increase the upload_max_filesize to at least match the post_max_size variable or vice versa.`

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by chmst** [comment]
Back to pending. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by richard67** [comment]
@brianteeman The contradiction is that COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZEDESC says that the value of post_max_size must be greater than the value of upload_max_filesize, while the other text COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC says "Please increase the upload_max_filesize to at least match the post_max_size variable or vice versa.", and that first includes that the upload_max_filesize should be greater than or equal to the post_max_size and then confuses with the "or vice versa".

Both is wrong. True is that the value of post_max_size must be greater than or equal to the value of upload_max_filesize. See here for an explanation: [https://stackoverflow.com/questions/7754133/php-post-max-size-overrides-upload-max-filesize](https://stackoverflow.com/questions/7754133/php-post-max-size-overrides-upload-max-filesize).

**Comment by brianteeman** [comment]
This PR is correct and follows the documentation at php.net. If you want to change the other string then that should be done in its own PR

**Comment by HLeithner** [comment]
Brians PR is correct but the description in "COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC" is wrong and should be fixed

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31736">issues.joomla.org/tracker/joomla-cms/31736</a>.</sub>

**Comment by infograf768** [comment]
> Brians PR is correct but the description in "COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC" is wrong and should be fixed

RANT: It was so simple to do it here instead of a new PR!!! I can't believe this. I asked for it 13 days ago...

**Pull request merged**
