### PR TITLE
[4.0] Remove obsolete import

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes an import which isn't needed for a very long time.

### Testing Instructions

Temporarily set text filtering to `No HTML` for Super Users in Global Configuration -> Text Filters.
Create a Custom HTML module with some HTML content.
Save and check that HTML is stripped out after saving.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
@SharkyKZ Site module? Or admin module? Or doesn't matter which kind?

**Comment by richard67** [comment]
@SharkyKZ Have just tested and am confused. Followed the testing instructions but HTML isn't stripped off, not without this PR and also not with this PR. What am I doing wrong?

**Comment by SharkyKZ** [comment]
Doesn't matter which module. Did you set filtering to `No HTML` in your user group?

**Comment by richard67** [comment]
@SharkyKZ Yes, like you wrote, in global config for the super users, and I was working with the only one user who is a super user.

**Comment by SharkyKZ** [comment]
Since you're experiencing this without patch, you might want to open a separate issue. Though I can't replicate it.

**Comment by richard67** [comment]
@SharkyKZ Not sure if it's an issue. Maybe I'm doing something wrong? Am using current 4.0-dev branch on a git clone, i.e. no nightly or alpha.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9fa4331243853a4be2a1d9496501fb452957fcb1<br /><br />Was a bit tricky with TinyMCE settings to get the Joomla Filter being used, but after I've managed that, all works as expected with and without this PR.
So the PR doesn't break anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27608">issues.joomla.org/tracker/joomla-cms/27608</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9fa4331243853a4be2a1d9496501fb452957fcb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27608">issues.joomla.org/tracker/joomla-cms/27608</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27608">issues.joomla.org/tracker/joomla-cms/27608</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
