### PR TITLE
Fix Showon feature for fields in a subform field, AND speadup showon code

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The pull fix Showon feature for a fields in the subform field, #11548 . 
Also here is the perfomance optimisation.

Perfomance of showon feature in global configuration:
**before** 134ms
screen 2016-10-22 17 17 50 574x306

**after** 59ms
screen 2016-10-22 17 18 20 668x288
### Testing Instructions

Create subform field (example in module Custom):

``` xml
<field name="items" type="subform" formsource="modules/mod_custom/test.xml"
  multiple="true"  label="Subform Field" />
```

Create a form (`modules/mod_custom/test.xml`) for the subform field, that contain `showon` feature:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<form>
<field name="type" type="list" default="0" label="Type" >
        <option value="0">Small</option>
        <option value="1">Medium</option>
        <option value="2">Large</option>
    </field>

        <field name="something"  type="text"
            label="Show when Type=Large" showon="type:2" />
</form>
```

or even use XML from #8524 (that even better for test, but without the radio button with "btn-group-yesno" as it still broken).

And make sure that `showone` feature works.
### Documentation Changes Required

none

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@Fedik i think this needs to go to 3.7.x branch.
Also since 3.7.x already accepts js polyfills can't we drop jQuery here and use vannila js ? 
i mean IIRC jQuery is only used in cms.js for this showon.

But also i think that can be another PR, since this intend to fix an issue too.

**Comment by Fedik** [comment]
> can't we drop jQuery here and use vannila js?

it can be complicated here, for now I would leave it as it is

> i think this needs to go to 3.7.x branch

it is bugfix from some point of view 😄 
I leave it for maintainers to decide

**Comment by webchun** [comment]
Hi @Fedik I have tested it and it's working good  Thanksss!!!!!
But there's a little thing, if you choose to use radio button with "btn-group-yesno" class as the sub-parent field instead of dropdonw list, it wont be clickable. So no showon item will be displayed
1bjzj

**Comment by Fedik** [comment]
radio button with "btn-group-yesno" it another issue, not related to `showon`

**Comment by webchun** [comment]
Ah I see. Hopefully this fix will be incorporated in the next 3.6.4

**Comment by zero-24** [comment]
@webchun can you report your test via the tracker than?

**Comment by webchun** [comment]
I have tested this item :white_check_mark: successfully on fa779c533ed1d0d69e93b5e4ab23af6a30e77f87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12511">issues.joomla.org/tracker/joomla-cms/12511</a>.</sub>

**Comment by webchun** [comment]
@zero-24 Done! Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12511">issues.joomla.org/tracker/joomla-cms/12511</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on fa779c533ed1d0d69e93b5e4ab23af6a30e77f87<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12511">issues.joomla.org/tracker/joomla-cms/12511</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on fa779c533ed1d0d69e93b5e4ab23af6a30e77f87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12511">issues.joomla.org/tracker/joomla-cms/12511</a>.</sub>

**Comment by dgt41** [comment]
RTC
Thanks @Fedik

**Comment by zero-24** [comment]
Thanks merged 👍

**Pull request merged**
