### PR TITLE
[5.1] Revert implementation of AfterInitialiseRouterEvent

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #42991.

### Summary of Changes
In an ideal world, the site router would only be created when necessary with the previously added onAfterInitialiseRouter event. However if a system plugin requests the site router object before all constructors of system plugins have run, the event would be fired, but no plugin would react to it, since the events haven't been registered yet. Since we can't guarantee that no one requests the router object prematurely, we have to revert the code and load the site router regardless of the application executed.

### Testing Instructions
1. Edit `plugins/system/redirect/services/provider.php` and insert `$container->get(\Joomla\CMS\Router\SiteRouter::class);` at line 43 (after '$plugin->setDatabase($container->get(DatabaseInterface::class));') 
2. Make sure the languagefilter plugin is enabled
3. Open any page 

### Actual result BEFORE applying this Pull Request
The page throws an error.

### Expected result AFTER applying this Pull Request
The page works fine.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
Please wait with it, I need time to check different approach.

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on 479dcacd94cf480b031f4af951817707c23c1150<br /><br />Works as described. For more info see my test comments in #43015 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43009">issues.joomla.org/tracker/joomla-cms/43009</a>.</sub>

**Comment by Hackwar** [comment]
yes

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 479dcacd94cf480b031f4af951817707c23c1150<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43009">issues.joomla.org/tracker/joomla-cms/43009</a>.</sub>

**Comment by Fedik** [comment]
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43009">issues.joomla.org/tracker/joomla-cms/43009</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Hackwar and for the support and testing @Fedik @SniperSister

**Pull request merged**
