### PR TITLE
Buttons on modal footer freaks out the forms

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/12563 .

### Summary of Changes

Change tag name from `button` to `a`

### Testing Instructions
Follow the description on the issue

### Expected result
Nothing

### Actual result
Form canceled

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 6ccf6591a855202ae0e6d87d783e7e0887571af3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14483">issues.joomla.org/tracker/joomla-cms/14483</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6ccf6591a855202ae0e6d87d783e7e0887571af3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14483">issues.joomla.org/tracker/joomla-cms/14483</a>.</sub>

**Comment by infograf768** [comment]
Remain to do
/administrator/components/com_associations/models/fields/modalassociation.php
/protostar/html/layouts/joomla/form/field/media.php

Van you add them here, @dgt41 ?

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 6ccf6591a855202ae0e6d87d783e7e0887571af3<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14483">issues.joomla.org/tracker/joomla-cms/14483</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14483">issues.joomla.org/tracker/joomla-cms/14483</a>.</sub>

**Comment by brianteeman** [comment]
See #16156  for the remaining places identified by @inforgraf768

**Pull request merged**
