### PR TITLE
[4.0] Fix field mapping in content type table for registerDate of users

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Change the value of column `field_mappings` of the record for com_users in table `#__content_types` from '"core_created_time":"registerdate"' to '"core_created_time":"registerDate"' so the camel case of the register date columns fits to the name of that columns in table `#_users`, like is is already correct for column `lastvisitDate`.

### Testing Instructions

Can be merged on review.

### Important for maintainer

@wilsonge I've made 2 commits, one for joomla.sql for new installations and one for the update sql script, so in case if you think the update statement is too risky and we should leave updated installations alone, just cherry pick the first commit for the new installations. But I don't really see a risk in the update sql.

### CODE REVIEW

**Comment by wilsonge** [comment]
I'm happy with this. But @alikon i'd like you to do a secondary review on the update statement as ~punishment~ someone who's done this before and knows the risk

**Comment by richard67** [comment]
@wilsonge @alikon The update with replace statement in the update sql script is safe because the search string `"core_created_time":"registerdate"` covers the complete parameter name value pair including all double quotes at beginning and end, so partial strings will not match, which was the problem in past issues with such statements.

**Comment by Eriiond** [comment]
I have tested this item :white_check_mark: successfully on 138d50519ede1634de34a3adf1fa420289fcbee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26580">issues.joomla.org/tracker/joomla-cms/26580</a>.</sub>

**Comment by punambaravkar** [comment]
I have tested this item :red_circle: unsuccessfully on 138d50519ede1634de34a3adf1fa420289fcbee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26580">issues.joomla.org/tracker/joomla-cms/26580</a>.</sub>

**Comment by richard67** [comment]
@punambaravkar Could you report back how you have tested this PR? It does not make sense to test it with patchtester because it contains sql changes only. You have to run the SQL statements in file `administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-10-13.sql` in PhpMyAdmin or file `administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-10-13.sql` in PhpPgAdmin, depending on which kind of database you use.

**Comment by richard67** [comment]
@punambaravkar Please read my previous comment and either change back your test result to "I have not tested this item" in the issue tracker, or test it in the right way. And in general leaving a negative test result without giving any information what has failed is not ok.

**Comment by richard67** [comment]
> 
> 
> I'm happy with this. But @alikon i'd like you to do a secondary review on the update statement as ~punishment~ someone who's done this before and knows the risk

@alikon please do review as George required in his comment above. Execute the SQL statement in the update sql script created by this PR on a J4 installation and then check in PhpWhateverYourDbTypeIsAdmin in table `#__content_types` that all is like before except of the thing changed with the statement.

**Comment by alikon** [comment]
review done and update query tested, all good for what i can see

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d4871eb0ad7aef32142e5b9ee48671b44e5c3052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26580">issues.joomla.org/tracker/joomla-cms/26580</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26580">issues.joomla.org/tracker/joomla-cms/26580</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
