### PR TITLE
ISIS  (list views) - Replace html/pagination.php::pagination_list_footer() by JLayouts

### PR DESCRIPTION
**Pull request by ghost**
#### Summary of Changes
- Replace in ISIS template deprecated override of pagination via html/pagination.php in all backend list views by JLayouts.
- Remove method pagination_list_footer() from ISIS html/pagination.php.
- Create overrides for joomla.pagination.link.php and joomla.pagination.links.php.
- Add features:
- \- Current page number also visible on phones.
- \- Expand tooltip for End link with information about total pages.
#### Testing Instructions
- Backend. ISIS template.
- Open administrator/index.php?option=com_content&view=articles
  or any other list view in backend (core components).
- Set limit box to 5 to make sure that a pagination list is displayed below items list.
- Test pagination also in smaller device widths.

Apply patch.
-  Compare pagination behavior. 
- Nothing has changed BUT
- \- On small devices you'll see the current page number (red arrow).
- \- You'll see an additional info on End link about number of total pages (green arrow)

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 763b2cb6ac715e44445a78e4dfe3b4bfa678c8d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11246">issues.joomla.org/joomla-cms/11246</a>.</sub>

**Comment by RonakParmar** [comment]
@bertmert One suggestion, Here at the end we can see "End (Page 14 of 14)", so it would be good that we can see "Start (Page 1 of 14)" in tool tip.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11246">issues.joomla.org/joomla-cms/11246</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on b96393008c1638947b28193a67e057b11056fe97<br /><br />Great work @bertmert<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11246">issues.joomla.org/joomla-cms/11246</a>.</sub>

**Comment by bertmert** [comment]
@RonakParmar 
Thanks for testing!

> One suggestion, Here at the end we can see "End (Page 14 of 14)", so it would be good that we can see "Start (Page 1 of 14)" in tool tip.

Even if I think that it's obvious that Start = Page 1 I changed the code because an information about total pages count could be helpful here, too, sometimes.

**Comment by wilsonge** [comment]
Let's keep things exactly the same as they are for this PR ;) Single responsibility

**Comment by bertmert** [comment]
@wilsonge 
I don't understand.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b96393008c1638947b28193a67e057b11056fe97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11246">issues.joomla.org/joomla-cms/11246</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11246">issues.joomla.org/joomla-cms/11246</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix the conflicts here please

**Comment by bertmert** [comment]
@wilsonge 
Done.

**Comment by bertmert** [comment]
Could somebody please help me.
When a PR has a Milestone 3.7.0 and there is a merge conflict is it against Staging or do I have to solve the conflicts against 3.7.0.
(I solved it against Staging).
Thx!

**Comment by rdeutz** [comment]
I changed the branch for this PR, conflicts must be solved for the 3.7.x branch

**Comment by bertmert** [comment]
@rdeutz @wilsonge 
Done! Branch 3.7.x now

**Comment by wilsonge** [comment]
So there were still conflicts. But I think I have solved them with https://github.com/joomla/joomla-cms/commit/fc41a23a9e8740c7864eaee166e1a089940cec97

**Comment by bertmert** [comment]
Now it's exactly the same like my first commits. Confusing! Thanks, @wilsonge

**Pull request closed without merging**
