### PR TITLE
[4.0] Remove Fade effect

### PR DESCRIPTION
**Pull request by brianteeman**
### Faster login
Removes the delay which is counter-logic

### Solves stutter bug #25904
https://github.com/joomla/joomla-cms/issues/25904#issuecomment-522082581

### Solves internet explorer bug #26005
(of course it wont work nicely with IE but at least someone could now log in if they have an emergency AND it opens the possibility to add a "does not work with IE" message" which you can't before this PR

### Testing Instructions
Apply PR and then run npm i

Check that login works
It should now be faster and smoother

Bonus try and open the admin with ie11 

(First of several PR on atum)

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2e3b4eee78a6c251c8a9031bdc1e44f1627c3959<br /><br />Login page no longer fades on login. Confirmed clean install is successful. Login is faster.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27857">issues.joomla.org/tracker/joomla-cms/27857</a>.</sub>

**Comment by Quy** [comment]
Please don't delete `_mixin.scss` and `@import` so the same mixin code for LTR/RTL can be implemented for the backend. Thanks.

**Comment by brianteeman** [comment]
But it's not being used after this pr

**Comment by Quy** [comment]
Yes, but I want to add the LTR/RTL mixin from #27861 to `_mixin.scss` in Atum. Leave the file blank instead of deleting it please so I don't need to recreate it in my PR to come later.

**Comment by brianteeman** [comment]
Ok. Will do in the morning

**Comment by brianteeman** [comment]
@quy done as requested

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b932cb17f811e51c581413519c419ecdfeab3725<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27857">issues.joomla.org/tracker/joomla-cms/27857</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27857">issues.joomla.org/tracker/joomla-cms/27857</a>.</sub>

**Comment by richard67** [comment]
Tested with success, too. Will merge.

**Comment by richard67** [comment]
Thanks. Btw. my nick name for my German friends is "Fade", so I first was confusde about the title ;-)

**Comment by Quy** [comment]
@brianteeman Close #25904?

**Comment by brianteeman** [comment]
@quy you requested that this empty mixin file was not removed as you had a PR that would be using it
its nine months later and the empty file is still there. did you forget your pr or was it done a different way.

In other words we should remove this empty file and references to it

**Comment by Quy** [comment]
Thanks for the reminder. Removed in PR #31210.

**Pull request merged**
