### PR TITLE
Add afterRespond event to the Joomla Debug Console

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

Following https://github.com/joomla/joomla-cms/pull/8888, this PR adds the final event `afterRespond` to the Joomla! Debug Console `Profile Information` block.

As it is now Joomla is not returning the real page time because it's not counting the `afterRespond` event.

To achive this goal a new event, the `onBeforeEnd`, is created. This event:
- is the last one (load after the `onAfterRespond` events) and before the app closes.
- can only be loaded by the debug system plugin and it was to be enabled.

Since the `onAfterRespond` events are now in the Profiler too, this PR will also allow to debug the `onAfterRespond` events.

Before PR:
image

After PR:
image
#### How to test
1. Apply this patch.
2. Turn on the debug in global config and enale the debug system plugin.
3. Test any page in frontend or admin and check if the `afterRespond` time and memory usage is in the Joomla! Debug Console `Profile Information` block.
4. You can now also test send info to Joomla! Debug Console on a `onAfterRespond`. For instance, add the following php to a system plugin that is enabled, load page and observe if the messages appear in the Joomla! Debug Console.

``` php
public function onAfterRespond()
{
    // Test to add mark in the profiler Joomla! Debug Console Profile Information block.
    JDEBUG ? JProfiler::getInstance('Application')->mark('testMark') : null;

    // Test to add log message to Log Messages block.
    JDEBUG ? JLog::add('Test log message to Joomla! Debug Console Log Messages block.', JLog::WARNING, 'deprecated') : null;
    }
```
#### Observations

Improvements or suggestions are welcome.

### CODE REVIEW

**Comment by mbabker** [comment]
The parent JApplicationWeb class has onBeforeExecute and onAfterExecute
events that we pulled out when migrating the application classes from the
legacy stuff.  So if we're going to put a new trigger at the end of the
execute method I'd put that onAfterExecute trigger back.

**Comment by andrepereiradasilva** [comment]
ok. i will replace it onBeforeEnd for onAfterExecute. But only for JDEBUG right?

**Comment by andrepereiradasilva** [comment]
In the Joomla Framework the commnet for that `onAfterExecute` event is executed before `afterRespond` event (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L263).

The goal here is to have a last event that is executed after the `afterRespond` event to be only used by the debugger so we can debug all events in the application so `onAfterExecute` i think will not serve the goal.

**Comment by mbabker** [comment]
Oh... These web application classes are so inconsistent.  The base application class triggers that event as the last thing in execute, I wish I knew why the folks who wrote those classes decided to have `onAfterExecute` in the middle of execute :facepalm:

Also, you can't create an event trigger that will only dispatch to one plugin.  If you really wanted to do that, you'd need to just trigger `$plugin->runThisAfterExecuteFinishes()` instead of using the event dispatcher.  Even if it's only dispatched if JDEBUG is true, any plugin with a `public function onAfterExecute()` would still listen to that event.

I'd just use `onAfterExecute` for the method and consider changing the event trigger order in `JApplicationWeb` so that the method is actually triggered after execute finishes.

**Comment by andrepereiradasilva** [comment]
Check also the comments in Joomla Framework:
- https://github.com/joomla-framework/application/blob/master/src/AbstractApplication.php#L102-L107
- https://github.com/joomla-framework/application/blob/master/src/AbstractWebApplication.php#L116-L121

If i understand this correctly there is a `doExecute` inside the `execute`. The `onAfterExecute` and `onAfterExecute` are related to the `doExecute`, in other words, `onAfterExecute` the `doExecute`.

Regarding this PR, i will try to change and call the debug plugin directly (with no new event).

**Comment by mbabker** [comment]
As the only crazy guy left using the Framework, I'd say the current trigger position is wrong, or the web application classes need an additional `afterExecute` type of event after the response is sent.  Either way what's there now is less than optimal.

**Comment by andrepereiradasilva** [comment]
Look on the bright side, if you're the `only crazy guy left using the Framework` you have more liberty to correct it. :smile:

**Comment by andrepereiradasilva** [comment]
closing for lack of interest

**Pull request closed without merging**
