### PR TITLE
[4.0] Remove database check for utf8mb4 support

### PR DESCRIPTION
**Pull request by csthomas**
Alternative for #19837

### Summary of Changes
Do not check if the database supports full Unicode characters.

On php >= 7.0 and mysql >= 5.5.3 we should be safe to save utf8mb4.
The same for PostgreSQL and SQLite3.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by laoneo** [comment]
Drone is crashing. Can you check if installation is still working with your patch?

**Comment by csthomas** [comment]
Yes, I will check it.

**Comment by csthomas** [comment]
I installed Joomla with your last merge (and without) and I have not seen any problem related to my patch.

I saw in /instalation/error_log only this:
```
[10-Sep-2018 09:48:21 Europe/Berlin] PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/home/.../components/com_mailto/mailto.xml&quot; in /home/.../libraries/src/Installer/Installer.php on line 2032
[10-Sep-2018 09:48:21 Europe/Berlin] PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/home/.../components/com_wrapper/wrapper.xml&quot; in /home/.../libraries/src/Installer/Installer.php on line 2032
```

**Comment by csthomas** [comment]
I tested on php 7.1 and mysql 5.7.23 (mysqli, pdomysql)

**Comment by alikon** [comment]
should'nt be removed the `UTF8MB4SupportInterface` then ?

**Comment by csthomas** [comment]
Yes, but we still have no green light from Michael:)

**Comment by mbabker** [comment]
I'd keep the interface and related functionality on the database API for now.  Dropping it IMO should be a FW3/CMS5 discussion.

**Comment by mbabker** [comment]
(Because that interface is also defining marker functions to downgrade queries written with utf8mb4 charsets for schema changes to utf8, so there is some utility there)

**Comment by alikon** [comment]
ok, then  
code review is successfully for me

**Comment by csthomas** [comment]
One more detail. PostgreSQL/SQLite3 supports full range of utf8 (utf8mb4). 
In Joomla3, on Postgresql, characters with 4 bytes are deleted.

**Comment by csthomas** [comment]
The interface may stay but it is only used by mysql. 

If this PR will be accepted then
($db instanceof UTF8MB4SupportInterface) will be equal to ($db->getServerType() === 'mysql')

**Comment by mbabker** [comment]
For all intents and purposes the two are functionally the same, because it's only with MySQL that these types of differences have to be accounted for, and TBH `$db instanceof UTF8MB4SupportInterface` is much cleaner in the code than `method_exists($db, 'convertUtf8mb4QueryToUtf8')`.

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
