### PR TITLE
[4.1] remove unused import in 4.1 media api

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 38978c83ba57ca31632923e3d409f8c5ebcaedf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36133">issues.joomla.org/tracker/joomla-cms/36133</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 38978c83ba57ca31632923e3d409f8c5ebcaedf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36133">issues.joomla.org/tracker/joomla-cms/36133</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36133">issues.joomla.org/tracker/joomla-cms/36133</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
