### PR TITLE
[com_menus] - wrong alias and field #10618

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #10618 .
#### Summary of Changes

SQL error (there is no table with p alias in the query)
#### Testing Instructions

see #10618

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a7ab3ffac1df5d09457a6065bb6a6043d3e56c95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10620">issues.joomla.org/joomla-cms/10620</a>.</sub>

**Comment by sovainfo** [comment]
Could someone provide proper test instructions? Wonder what is tested!
Haven't been able to find its use, sounds like these lines can be removed. Including the duplicate lines in populateState, no need to do that twice, so one set can be removed anyway, but expect them to be obsolete both. Including its line (159) in getStoreId.

**Comment by andrepereiradasilva** [comment]
Go to menu items and add `&filter[parent_id]=PARENT_MENU_ITEM_ID` to the URL.Wherwe `PARENT_MENU_ITEM_ID` is a menu item parent id.

**Comment by andrepereiradasilva** [comment]
soemthing like `/administrator/index.php?option=com_menus&view=items&filter[parent_id]=277`

before patch 500 error
after patch shown the child menu items

**Comment by sovainfo** [comment]
Considering the view doesn't provide this functionality, it shouldn't be accepted on the url.

**Comment by andrepereiradasilva** [comment]
this is one of those "hidden" filters in the models.
You have similiar in other models also.

**Comment by sovainfo** [comment]
@alikon See my PR#21

**Comment by sovainfo** [comment]
I have tested this item :white_check_mark: successfully on a7ab3ffac1df5d09457a6065bb6a6043d3e56c95<br /><br />Works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10620">issues.joomla.org/joomla-cms/10620</a>.</sub>

**Comment by infograf768** [comment]
rtc. thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10620">issues.joomla.org/joomla-cms/10620</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
