### PR TITLE
Alpha ordering plg_actionlog_joomla.ini strings

### PR DESCRIPTION
**Pull request by infograf768**
As title says.

can be merged on review

### CODE REVIEW

**Review by brianteeman — COMMENTED** [review]
I thought you didn't want strings to be grouped?

**Comment by infograf768** [comment]
I did not group them. They were grouped already. I respected the intention of the original coder, as we still have elsewhere in code. This is just for alpha ordering IN the groups.

Note: the groups are separated by comments

**Comment by infograf768** [comment]
@mbabker
can you merge this please?

**Comment by infograf768** [comment]
Thanks

**Pull request merged**
