### PR TITLE
[cs] leading spaces

### PR DESCRIPTION
**Pull request by brianteeman**
While checking #20844 I saw that these strings all have a leading space which should not be there

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d5882f4ad261602fe85b75b571e6f9e99952123f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20858">issues.joomla.org/tracker/joomla-cms/20858</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on d5882f4ad261602fe85b75b571e6f9e99952123f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20858">issues.joomla.org/tracker/joomla-cms/20858</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20858">issues.joomla.org/tracker/joomla-cms/20858</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
