### PR TITLE
Update Mfa.php s/dissappear/disappear

### PR DESCRIPTION
**Pull request by brianteeman**
Spelling mistake

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 03b7f9a6bb12ba53f08f64340eb80f2fa24ad8f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38050">issues.joomla.org/tracker/joomla-cms/38050</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 03b7f9a6bb12ba53f08f64340eb80f2fa24ad8f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38050">issues.joomla.org/tracker/joomla-cms/38050</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38050">issues.joomla.org/tracker/joomla-cms/38050</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
