### PR TITLE
[4.0] Contact Category list limits

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #33021 

Hopefully this resolves the bug reported with #30813. 
#30904 tried to fix it by removing the feature introduced with #23710 completely which was wrong

To test

- Create at least 10 contacts in the same category
- Create a menu item to display all the contacts in that category
- in the menu options make sure that Display Select is set to show (List layouts tab)
- In the global configuration check the value for default list limit (its probably 20)
- In the front end go to the new contact list menu item
- Check that the list limit select is displayed
- Check that the value is the same as in global config
- Check that changing the value in the select works
- Go back to the admin and edit the menu item and find the # contacts to list at the bottom of the list layouts tab
- Change the value from Global to 5 and save
- Clear "cookies" !!!
- In the front end go to the updated contact list menu item
- Check that the value is the same as you just set in the menu item (eg 5)
- Check that changing the value in the select works

### CODE REVIEW

**Comment by joomdonation** [comment]
@brianteeman Thanks for working on this issue. There are some small problems with your proposed code and I made a PR to your branch to fix it https://github.com/brianteeman/joomla-cms/pull/123 . Please review, test it and if it is OK for you, please merge it so that we can test.

**Comment by brianteeman** [comment]
@joomdonation - thanks - missed that use case.

**Comment by PhilETaylor** [comment]
```
FILE: /********/src/components/com_contact/src/Model/CategoryModel.php
47	----------------------------------------------------------------------
48	FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
49	----------------------------------------------------------------------
50	 295 | WARNING | Line exceeds 150 characters; contains 166
51	     |         | characters (Generic.Files.LineLength.TooLong)
52	----------------------------------------------------------------------
```

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 34828ff3c2c656d7fc7240abd558d4002282f262<br /><br />Note for testers: clear cookies is tricky as it forces logout - try a different browser instead?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33050">issues.joomla.org/tracker/joomla-cms/33050</a>.</sub>

**Comment by joomdonation** [comment]
@brianteeman Could you please fix the code style here so that I can test it and get this one merged? I see some other potential issues with the CategoryModel class (not really related to this PR), but I can make a separate PR after this one merged.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 0f10d555534c593de85cdb60d401a0cb3a918107<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33050">issues.joomla.org/tracker/joomla-cms/33050</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33050">issues.joomla.org/tracker/joomla-cms/33050</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks for testing and merging

**Comment by AndySDH** [comment]
Thanks for making this @brianteeman!

**Pull request merged**
