### PR TITLE
[#4355] - I think we can add Upload Limit hint at extension manager

### PR DESCRIPTION
**Pull request by vaishalivk**
I have commited changes to show the Maximum upload file size on installation screen and in media manager

### CODE REVIEW

**Comment by thiago-takeshi** [comment]
This patch is working. I used and now i can see a limit of 60M maximum upload.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4837">issues.joomla.org/joomla-cms/4837</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on ab673d2db88ae06ca20cc4100bb565247db8200e<br /><br />Works great in the installation manager
Doesnt appear to do anything in the mdia manager (perhaps the code in media manager has changed since this PR)

Lets get this PR finalised and then if people want to have tooltips they can be discussed then in a seperate PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4837">issues.joomla.org/joomla-cms/4837</a>.</sub>

**Comment by brianteeman** [comment]
@vaishalivk can you look at the issue with media manager please. Otherwise this will be closed in a few weeks s it cant be merged as it is <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4837">issues.joomla.org/joomla-cms/4837</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for creating this. It’s been some time since you created this and there are now some merge conflicts that prevent a direct merge. The Media Manager is currently rewritten, please consider to make a new PR against this repository.

**Pull request closed without merging**
