### PR TITLE
Change error on registration

### PR DESCRIPTION
**Pull request by brianteeman**
In the admin if a registration fails then it is an error message but on the front end it was only a warning

This PR makes them both errors

PR for #9502

### CODE REVIEW

**Comment by Quy** [comment]
I still get the warning message and not error message.

**Comment by joomdonation** [comment]
The code Brian modified is for error when activating account. For registration failed error messages, you will need to modify code in different places:

https://github.com/joomla/joomla-cms/blob/staging/components/com_users/controllers/registration.php#L150
https://github.com/joomla/joomla-cms/blob/staging/components/com_users/controllers/registration.php#L154
https://github.com/joomla/joomla-cms/blob/staging/components/com_users/controllers/registration.php#L177

**Comment by brianteeman** [comment]
Will look again later

**Comment by brianteeman** [comment]
Updated - thanks for testing

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dd887b3168255ec88075acaeebf2ebd0ba7107d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19142">issues.joomla.org/tracker/joomla-cms/19142</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on dd887b3168255ec88075acaeebf2ebd0ba7107d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19142">issues.joomla.org/tracker/joomla-cms/19142</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
