### PR TITLE
Make user field initialize itself when a new subform row is added

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes

Subform repeatable has a function `fixScripts` which calls a few js initialization functions on a few of the field types that require it. There is a now a better way to handle that kind of thing by having any field that may need initialization listen for an event fired by subform repeatable. In this PR, I am transferring responsibility of one such initialization from subform repeatable to the correct field type itself. 

Note: this PR doesn't really fix anything. the user field type already works with repeatable subforms. This just does it in a somewhat better way. 

### Testing Instructions

Set up a subform containing a user field. There's a subform in the redirect plugin that's simple to use for this purpose. 

Open up the form and create new rows. The user field in each new row should function properly. 

### Expected result

User field functions normally.

### Actual result

User field functions normally.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f2999becd4e0986882912c0e204beb483f15fa00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20231">issues.joomla.org/tracker/joomla-cms/20231</a>.</sub>

**Comment by okonomiyaki3000** [comment]
See also #24919

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 157e33dda0948abd12ac1066fb660c1f7a050c39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20231">issues.joomla.org/tracker/joomla-cms/20231</a>.</sub>

**Comment by HLeithner** [comment]
@okonomiyaki3000 could you please solve the conflicts?

**Review by wilsonge — APPROVED** [review]

**Pull request merged**
