### PR TITLE
[4.0][Atum][CS] Line-breaks, indents and spaces

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26759 .

### Summary of Changes
Consistent line-breaks, indents, and spacing across all Atum template SCSS using the following...

```JSON
"end_with_newline": true,
"indent_char": " ",
"indent_size": 2,
"newline_between_rules": true,
"selector_separator_newline": true,
"space_around_combinator": true,
```

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
Please fix conflicts.

**Comment by ciar4n** [comment]
Conflicts fixed

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 57334fe63e0d6a86a7750b742665abad4683c336<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26793">issues.joomla.org/tracker/joomla-cms/26793</a>.</sub>

**Comment by wilsonge** [comment]
Sorry I just came back to this :( shouldn’t have merged the other part first, if you do this and ping me wildly I’ll try and get it merged fast this time :(

**Comment by ciar4n** [comment]
If you don't mind, Im gonna close this and create a new pr. Hard negotiating some of these conflicts.

**Comment by wilsonge** [comment]
Sure. Just ping me when it's in and i'll try and get it in asap

**Pull request closed without merging**
