### PR TITLE
html5fallback.js: remove aria-invalid on label if field is invalid. fix #6573

### LINKED ISSUE #6573: html5fallback.js generates errors
Hi, with my fellow worker @vinespie we found a mistake are generate by html5fallback.js

example : 
For the mod_login, when you go out of a field like username "html5fallback.js" generate a aria-invalid="false" in the label.

aria-invalid is not used for label.

### PR DESCRIPTION
**Pull request by vinespie**
Removing "aria-invalid" attribute on label when input is not valid.
https://www.w3.org/WAI/GL/wiki/Using_Aria-Invalid_to_Indicate_An_Error_Field
fix #6573 

---

Hi, with my fellow worker @vinespie we found a mistake are generate by html5fallback.js

example : 
For the mod_login, when you go out of a field like username "html5fallback.js" generate a aria-invalid="false" in the label.

aria-invalid is not used for label.

### CODE REVIEW

**Comment by zero-24** [comment]
@vinespie can you fix also the compressed file? https://github.com/vinespie/joomla-cms/blob/staging/media/system/js/html5fallback.js<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6631">issues.joomla.org/joomla-cms/6631</a>.</sub>

**Comment by vinespie** [comment]
No, I searched the compression tool used to joomla but I have not found. Can you give me a link / her name?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6631">issues.joomla.org/joomla-cms/6631</a>.</sub>

**Comment by Fedik** [comment]
@vinespie see https://gist.github.com/phproberto/6933178

**Comment by vinespie** [comment]
@zero-24 I added the correction in the compressed file
thank you for the help @Fedik

**Comment by crommie** [comment]
Could you please add step by step testing instructions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6631">issues.joomla.org/joomla-cms/6631</a>.</sub>

**Comment by hans2103** [comment]
Need testinstructions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6631">issues.joomla.org/joomla-cms/6631</a>.</sub>

**Comment by zero-24** [comment]
@crommie @hans2103 

### how to test

##### first test

- Use a Browser (like old IE)
- go to a mod_login screen
- see the sourecode of the Username field
- see the `aria-invalid="false"`
- apply the patch
- see it is gone

##### seccond test

- go to a mod_login screen
- copy the sourecode into http://validator.w3.org/
- see issue about the `aria-invalid="false"`
- apply the patch
- see it is gone

**Comment by matrikular** [comment]
I have tested this item :red_circle: unsuccessfully on a104968d6cebb29ccca660b8b461888b25399e06<br /><br />Either this has already been fixed or I'm missing something.

The html5fallback.js is present in the documents head on: index.php?option=com_users&view=login but there is no aria-attribute on the label. Tested with IE 8.0.7601<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6631">issues.joomla.org/joomla-cms/6631</a>.</sub>

**Comment by yvesh** [comment]
@zero-24 we are a bit irritated about your test instructions here at PBF Munich, the patch is for the label and not the field!? (INPUT) But we couldn't reproduce it either with the windows machines here.

**Comment by zero-24** [comment]
Thanks @yvesh and @matrikular closing here.

**Pull request closed without merging**
