### PR TITLE
Some missing jquery framework dependency

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Description

This PR adds some missing jquery framework dependency.
### How to test
- In admin go to Content -> Media and check there is no javascript errors in the js console.
- In admin go to System -> Global Check in and check there is no javascript errors in the js console.

You can also check the code to see jquery js are loaded.
### B/C

None

### CODE REVIEW

**Comment by zero-24** [comment]
hmm jquery is loaded also without this patch or i miss something?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8543">issues.joomla.org/joomla-cms/8543</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Yes it's loaded, but because JDocument loads the scripts in this order:

- External scripts
- Inline scripts

If they were loaded in the order they are called (not matter if they are internal or external) there would be a JS error.

They work now, because some other component in that pages is calling jQuery.

This is only for js integrity no changes in output.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5bf71d1cc36a9ba0fcb8871fa928569998d6989c<br /><br />Ok agree than my test was successfull.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8543">issues.joomla.org/joomla-cms/8543</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 5bf71d1cc36a9ba0fcb8871fa928569998d6989c<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8543">issues.joomla.org/joomla-cms/8543</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks @zero-24 @anibalsanchez
can we have an RTC :)

**Comment by dgt41** [comment]
@joomla-bot RTC this

**Comment by wilsonge** [comment]
Hi @andrepereiradasilva can you contact me please. Glip/email so we can clean up your staging branch. I'm having to squash you're commits every time which is time consuming. Would save my time (and probably some of yours if i can help you fix up your branch).

**Comment by andrepereiradasilva** [comment]
@wilsonge sure, sorry for that.
how do i send you a private message with my contact details?

**Comment by wilsonge** [comment]
either email me at george.wilson@community.joomla.org grab me on glip or skype george.wilson1992 

Don't worry about it! I know I've made this mistake several times :)

**Pull request closed without merging**
