### PR TITLE
[4][com_templates] cast to int for pgsql

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42408 .

### Summary of Changes
cast to int 

### Testing Instructions
Packages for new installation and update with this PR applied and a custom update URL can be found here: https://artifacts.joomla.org/drone/joomla/joomla-cms/4.4-dev/42569/downloads/72523

use postgresql
 "System" -> "Site Templates", in the drop-down list  select: "Site", then "Cassiopeia Details and Files" and move to the editor.

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request
able to edit

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8c8371a53885f9217223a937dc8bdb7af41316a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42569">issues.joomla.org/tracker/joomla-cms/42569</a>.</sub>

**Comment by ambltsk** [comment]
I have tested this change, I confirm it works.

**Comment by richard67** [comment]
> I have tested this change, I confirm it works.

@ambltsk Thanks for testing. Could you mark your test result in the issue tracker so it's properly counted? For doing this, just go to https://issues.joomla.org/tracker/joomla-cms/42569 , then use the blue "Test this" button at the top left corner, select your test result (success) and finally submit. Thanks in advance.

**Comment by ambltsk** [comment]
I have tested this item :white_check_mark: successfully on 8c8371a53885f9217223a937dc8bdb7af41316a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42569">issues.joomla.org/tracker/joomla-cms/42569</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42569">issues.joomla.org/tracker/joomla-cms/42569</a>.</sub>

**Review by MacJoom — APPROVED** [review]

**Pull request merged**
