### PR TITLE
[4.0] Correct FontAwesome SCSS import order

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for https://github.com/joomla/joomla-cms/pull/31262#issuecomment-718556229.

### Summary of Changes

Corrects SCSS import order.

### Testing Instructions

@infograf768 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I suggest to add, as for atum:
`@import "../../../../../../media/vendor/fontawesome-free/scss/brands"; // order of loading is important.`

**Comment by SharkyKZ** [comment]
Added comment.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0f0864af1b7d3492f8f9b0f89697f17cc68c653f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31268">issues.joomla.org/tracker/joomla-cms/31268</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0f0864af1b7d3492f8f9b0f89697f17cc68c653f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31268">issues.joomla.org/tracker/joomla-cms/31268</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31268">issues.joomla.org/tracker/joomla-cms/31268</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
