### PR TITLE
travis again

### PR DESCRIPTION
**Pull request by dgrammatiko**

### CODE REVIEW

**Comment by dgt41** [comment]
Check https://github.com/krakjoe/apcu/issues/154

**Comment by Kubik-Rubik** [comment]
Merge on code review. Thank you @dgt41!

**Comment by mbabker** [comment]
If I'm following that correctly, then the env vars should be `INSTALL_APCU` for PHP 5.5/5.6 and `INSTALL_APCU_BC` for PHP 7 and the command for that install changed to `pecl install apcu_bc-beta`.

All this pull request did was rename env vars and missed changing the if conditional for the APCu beta install which makes the PHP 7 build bypass installing it giving the appearance of a passing build.

**Comment by dgt41** [comment]
Yep my bad, fixing it now

**Pull request merged**
