### PR TITLE
[4.0] Switcher + checkbox layout fixes

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR:

- Fixes the checkboxes layout
- Adds the switcher class to new parameters merged in from J3.7
- Fixes the switcher input width

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
whats the Difference between with- or without PR? 

Switch (Default Page) looks same:
bildschirmfoto 2017-03-14 um 12 49 22

**Comment by C-Lodder** [comment]
@franz-wohlkoenig 

If you try and click anywhere within the red box (screenshot below), then the switcher doesn't work. This is because the element was 10px narrower than the parent.

untitled

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on cdefe0f8fc564d44e533ba8d0eb7c6fbea20e293<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14601">issues.joomla.org/tracker/joomla-cms/14601</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by C-Lodder** [comment]
@wilsonge ready to merge

**Pull request merged**
