### PR TITLE
[4.0] Correcting success colour after installing sample data

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23632

### Summary of Changes
When using Joomla.renderMessages, the correct class for a success and getting a greenish colour is `message` and not `success`.
This is defined in `core.es6.js` by the code
```
if (['notice', 'message', 'error', 'warning'].indexOf(type) > -1) {
          alertClass = (type === 'notice') ? 'info' : type;
          alertClass = (type === 'message') ? 'success' : alertClass;
          alertClass = (type === 'error') ? 'danger' : alertClass;
          alertClass = (type === 'warning') ? 'warning' : alertClass;
        } else {
          alertClass = 'info';
        }
```

### Testing Instructions
Patch.
Run npm ci
Install some sample data 

### After patch
screen shot 2019-01-31 at 11 20 06

### CODE REVIEW

**Comment by infograf768** [comment]
@zero-24 
RIPS please

**Comment by zero-24** [comment]
Rips is happy here now

**Comment by PhilETaylor** [comment]
@infograf768 I think you should be the [CODEOWNER](https://github.com/joomla/joomla-cms/blob/staging/.github/CODEOWNERS) for alert messages after all your work on them :)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bdbb6b06f86d44335f5cc8a0a8c4c61ed013ec6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23726">issues.joomla.org/tracker/joomla-cms/23726</a>.</sub>

**Comment by infograf768** [comment]
@PhilETaylor 
no thanks for owning code.😉
but your test would help to get that in...

**Comment by infograf768** [comment]
@C-Lodder

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 497337ee781b616b5d7dc4dab56e7878177f6ff0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23726">issues.joomla.org/tracker/joomla-cms/23726</a>.</sub>

**Comment by C-Lodder** [comment]
It's weird that this PR actually solves the issue but either way. +1 from me if that's the final result

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23726">issues.joomla.org/tracker/joomla-cms/23726</a>.</sub>

**Comment by wilsonge** [comment]
Thanks JM!

**Comment by wilsonge** [comment]
@C-Lodder Our javascript mappings are somewhat weird https://github.com/infograf768/joomla-cms/blob/c2a6e13a5d2d819fdbe1ba62295aaf8208a9cc99/build/media_src/system/js/core.es6.js#L437-L442

**Pull request merged**
