### PR TITLE
Add missing self-closing tag for input-tag within JHtmlSelect

### PR DESCRIPTION
**Pull request by hordijk**
The input-tag within the radiolist function of JHtmlSelect is not closed, causing issues in validators. This change fixes the issue and created a input-tag which is inline with the other HTML utility classes as well, which are already using self-closing tags.

### CODE REVIEW

**Comment by zero-24** [comment]
So for testing it is just make sure the select options still work after the patch. 

Please correct me if I wrong.
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8102">issues.joomla.org/joomla-cms/8102</a>.</sub>

**Comment by hordijk** [comment]
I've updated the corresponding unit test as well. But you should test if the select options are still working. You can check for example the search component.

The file components/com_search/views/search/view.html.php contains:
$lists['searchphrase'] = JHtml::_('select.radiolist', $searchphrases, 'searchphrase', '', 'value', 'text', $state->get('match'));

If the search_phrases are shown in the front-end search the generated HTML was not valid due to the missing self-closing tag. You can use https://validator.w3.org/ to validate the generated HTML.

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on 403116dc7d38faa7315224282b95841e8abab420<br /><br />The testinstructions are misleading. The validator only throws an validation error if an html4 template is used. In HTML5 self closing tags don't require the closing slash.

So, it would suggest to test this by checking the generated HTML with the inspection tools of your browser manually. That way I was able to test and verify that the patch is working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8102">issues.joomla.org/joomla-cms/8102</a>.</sub>

**Comment by henrylamare** [comment]
I have tested this item successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8102">issues.joomla.org/joomla-cms/8102</a>.</sub>

**Comment by Coscha** [comment]
i have tested this item :white_check_mark: successfully.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8102">issues.joomla.org/joomla-cms/8102</a>.</sub>

**Comment by SniperSister** [comment]
3 successful tests, setting to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8102">issues.joomla.org/joomla-cms/8102</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @hordijk and testers! Merged.

**Pull request merged**
