### PR TITLE
Correct version number for removed file

### PR DESCRIPTION
**Pull request by brianteeman**
fixes typo

Pull Request for Issue # .

### CODE REVIEW

**Comment by wilsonge** [comment]
This was 3.9.7 i think?

**Comment by brianteeman** [comment]
The number is the version number that the file is removed in

**Comment by wilsonge** [comment]
I understand and that access.xml was removed in 3.9.7 and not an unreleased version of joomla

**Comment by brianteeman** [comment]
@wilsonge silly me "fixed" the wrong line

**Comment by wilsonge** [comment]
Looks better now. Ta! Silly me too :)

**Comment by mbabker** [comment]
Umm, why are there files in the folders array?

**Pull request merged**
