### PR TITLE
[4.0] Creating default object from empty value

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23063 .

### Summary of Changes

not so sure this is the right way

### Testing Instructions
see #23063

### Expected result
no more PHP Warning:  Creating default object from empty value in /var/www/html/.../libraries/src/Updater/Update.php on line 299

### Actual result
PHP Warning

### CODE REVIEW

**Comment by zero-24** [comment]
How exactly can this be reproduced?

**Comment by SharkyKZ** [comment]
@zero-24 https://github.com/joomla/joomla-cms/issues/23063#issuecomment-495136350.

**Comment by SharkyKZ** [comment]
The erroneous code exists in staging so I guess it should be fixed staging? Or at least in 3.10 where warning can be reproduced?

**Comment by mbabker** [comment]
This doesn't look like a fix to me.  If I had to guess, the problem is there's some scenario where `$this->currentUpdate` hasn't been initialized yet.  Proper PHPUnit test cases would help to isolate this.

**Pull request closed without merging**
