### PR TITLE
Add PHP 8.2 to PHP version check plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds PHP 8.2 to PHP version check plugin

### Testing Instructions

Review.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b3e1d16c9339697cfd43557fe85c4586e595af79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39396">issues.joomla.org/tracker/joomla-cms/39396</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b3e1d16c9339697cfd43557fe85c4586e595af79<br /><br />Tested by review. Added information matched https://www.php.net/supported-versions.php .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39396">issues.joomla.org/tracker/joomla-cms/39396</a>.</sub>

**Comment by richard67** [comment]
Back to pending due to issue tracker problem with RTC label.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39396">issues.joomla.org/tracker/joomla-cms/39396</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39396">issues.joomla.org/tracker/joomla-cms/39396</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 we should backport this into 3.10

**Comment by fancyFranci** [comment]
Thank you!

**Comment by zero-24** [comment]
> @zero-24 we should backport this into 3.10

Noted 👍

**Pull request merged**
