### PR TITLE
[4.0] Fix login box disappearing

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #17366

### Testing Instructions

Attempt to login to the backend with an incorrect username and/or password.

The login box should not disappear

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@C-Lodder can you add this:
```js
				if (!document.querySelector('joomla-alert')) {
					document.getElementById('mod-login-username').focus();
				}
```
instead of `document.getElementById('mod-login-username').focus();`

The reason is better UX, keep the focus on the alert. Obviously my first take wasn't quite there

**Comment by C-Lodder** [comment]
@dgt41 - done

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 33c9caf3e5090a3229bba6222381a6352ea59142<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17369">issues.joomla.org/tracker/joomla-cms/17369</a>.</sub>

**Comment by dgrammatiko** [comment]
RTC @wilsonge please merge

**Pull request merged**
