### PR TITLE
Fix filepath to PHPMailer language file

### PR DESCRIPTION
**Pull request by mbabker**
Partial Pull Request for Issue #19071

### Summary of Changes

From what I can tell, after https://github.com/PHPMailer/PHPMailer/commit/6a6165f5761aacf7432809630cdb944323566a37 introduced in PHPMailer 5.2.17 our language file loading has been broken for the library.  This fixes it.

### Testing Instructions

Whatever it takes to get language strings out of PHPMailer should now be translated with Joomla's strings versus the hardcoded English that'll be loading now.

### CODE REVIEW

**Comment by brianteeman** [comment]
I tested this in j4 against the issue i reported in 19071. the problem is that it solves the issue of the message appearing incorrectly that I reported then but now I cant create an error to test that the message is now correct. So I am guessing the previous error message was completely incorrect and that by fixing the bug here it has resolved that

**Comment by mbabker** [comment]
No idea to be honest.  I didn't even actually test mail sending, I went straight for the "language file not loading correctly" thing since that can be debugged/fixed without sending mail and traced through that until I had a correct file name/path.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 113cb2051858781b7f5d85cc9e0f6d25c6f33a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19072">issues.joomla.org/tracker/joomla-cms/19072</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 113cb2051858781b7f5d85cc9e0f6d25c6f33a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19072">issues.joomla.org/tracker/joomla-cms/19072</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 113cb2051858781b7f5d85cc9e0f6d25c6f33a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19072">issues.joomla.org/tracker/joomla-cms/19072</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS thanks for Test. As this is a Pull Request (PR) which is set "Ready to Commit" (RTC) its not necessary to test again. 

Maybe you can list on [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms) PR having one Test and need a second one (click st "Search Tools" then "Tests" > "Needs one")?

**Comment by anuragteapot** [comment]
ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19072">issues.joomla.org/tracker/joomla-cms/19072</a>.</sub>

**Comment by infograf768** [comment]
What is the impact of this for non-en-GB languages?

**Comment by brianteeman** [comment]
The untranslated strings from phpmailer will be correctly translated by joomla

**Pull request merged**
