### PR TITLE
Removed the depreciated JArrayHelper Class

### PR DESCRIPTION
**Pull request by rdeutz**
I came across this file and removed the depreciated JArrayHelper class 
#### Summary of Changes

Changed JArrayHelper to Joomla\Utilities\ArrayHelper
#### Testing Instructions

Apply Patch and check if the User Profile Plugin still works as expected

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d0f630430b4abf519effc53f55b423f5406988b2<br /><br />by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10206">issues.joomla.org/joomla-cms/10206</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on d0f630430b4abf519effc53f55b423f5406988b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10206">issues.joomla.org/joomla-cms/10206</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10206">issues.joomla.org/joomla-cms/10206</a>.</sub>

**Comment by rdeutz** [comment]
Thanks for testing and merging :-)

**Pull request merged**
