### PR TITLE
[5.1] com_contact remove showon when useglobal is used in the field

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #42381  .

### Summary of Changes
Removed the showon option in several fields

### Testing Instructions
See issue #42381 

### Actual result BEFORE applying this Pull Request
Showon fields are not displayed in contact and menu item if the "parent" field has useglobal

### Expected result AFTER applying this Pull Request
Showon fields are displayed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
maybe it's better to fix the real issue if the issue is true for all global based showOns ?

**Comment by drmenzelit** [comment]
> maybe it's better to fix the real issue if the issue is true for all global based showOns ?

Yes ;-) useglobal inserts a new select option but without value ... do you know where that is created?

**Comment by crimle** [comment]
I have tested this item :white_check_mark: successfully on 441e2f167ccd0f2d7db4a7d9c992b8ce1a34e2e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42386">issues.joomla.org/tracker/joomla-cms/42386</a>.</sub>

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 441e2f167ccd0f2d7db4a7d9c992b8ce1a34e2e3<br /><br />Tested on 5.1.0 RC1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42386">issues.joomla.org/tracker/joomla-cms/42386</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42386">issues.joomla.org/tracker/joomla-cms/42386</a>.</sub>

**Comment by cybersalt** [comment]
I have tested this item :white_check_mark: successfully on a80245dbdf6d525942a083a494749ff727849ae1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42386">issues.joomla.org/tracker/joomla-cms/42386</a>.</sub>

**Review by bembelimen — CHANGES_REQUESTED** [review]
Like Harald said, removing the option does not fix the issue: https://github.com/joomla/joomla-cms/pull/42386#issuecomment-1823964132

**Comment by bembelimen** [comment]
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42386">issues.joomla.org/tracker/joomla-cms/42386</a>.</sub>

**Comment by drmenzelit** [comment]
> Like Harald said, removing the option does not fix the issue: [#42386 (comment)](https://github.com/joomla/joomla-cms/pull/42386#issuecomment-1823964132)

I was not able to find the code for that ... https://github.com/joomla/joomla-cms/pull/42386#issuecomment-1824108867

**Comment by drmenzelit** [comment]
This PR doesn't solve the underlying problem of showon fields. We need more coding effort for that.

**Pull request closed without merging**
