### PR TITLE
Add early version of model abstractions

### PR DESCRIPTION
**Pull request by jissereitsma**
First steps into creating proper models for files, file types and folders.

### CODE REVIEW

**Comment by alikon** [comment]
Why this has been merged without tests?
It introduces new table but, only the mysql part was supplyed
Are the rules changed ?

**Comment by Kubik-Rubik** [comment]
This is a special branch that we use in the Roompot Code Sprint in the Netherlands!

No rules changed, we need the changes to work further on the improvements.

**Comment by wilsonge** [comment]
Why isn't this being done in the Joomla Projects repo (https://github.com/joomla-projects/joomla-cms) like usual then?

**Comment by Bakual** [comment]
Yeah, please use the joomla projects. To many people are listening here and you're spamming and confusing them unnecessary.

**Comment by alikon** [comment]
sorry for the confusion, i was reading on phone
so i didn't notice the "special branch"

**Pull request merged**
