### PR TITLE
[4.0] Correct ordering icon

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Corrects icon.

### Testing Instructions

Go to `com_languages`. Edit permissions.
Set `Edit State` to `Deny` for administrators.
Create an administrator user.
Login with administrator.
Go to `Content Languages`.
Inspect ordering icon in the table.

### Actual result BEFORE applying this Pull Request

Bars icon is shown.

### Expected result AFTER applying this Pull Request

Vertical ellipsis is shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 124c5d146042376c1eb209179db258ee35302eea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31266">issues.joomla.org/tracker/joomla-cms/31266</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 124c5d146042376c1eb209179db258ee35302eea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31266">issues.joomla.org/tracker/joomla-cms/31266</a>.</sub>

**Comment by infograf768** [comment]
Restarted drone

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
