### PR TITLE
__DEPLOY_VERSION__

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=+__DEPLOY_VERSION__&type=Code
#### Testing Instructions

Nothing to test as it is just a doc block change!

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i was about to do this. Thanks.
But will 3.6 be the next version?

**Comment by roland-d** [comment]
@zero-24 If we hardcode this, shouldn't we change it every time with a new release?

**Comment by zero-24** [comment]
@andrepereiradasilva yes see: https://developer.joomla.org/news/644-version-number-shifting.html

@roland-d I'm not sure what you mean? The `__DEPLOY_VERSION__` string is a placesholder the framework use to set the correct version on time of the release.

But the CMS don't use this kind of automation. This is the last i know. Maybe @mbabker can help.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 19dad0c32589940ec85acf8e4e2bd270b6729a21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10183">issues.joomla.org/joomla-cms/10183</a>.</sub>

**Comment by andrepereiradasilva** [comment]
BTW shouldn't it be `3.6.0` instaead of `3.6`. Is there any rule for that?

**Comment by andrepereiradasilva** [comment]
@zero-24 can you replace with `3.6.0`

**Comment by mbabker** [comment]
There isn't a rule on whether it's just major.minor or if it's major.minor.patch.  The CMS has mainly used the former while the Framework ends up using the latter because the job that creates the release tag runs this command and uses the user's input version number:

```sh
find . -name "*.php" -type f -exec sed -i "s/__DEPLOY_VERSION__/$Version/g" "{}" \; -exec git add {} \;
```

The CMS doesn't have a fully automated job like that and IMO it shouldn't either for reasons not relevant to this discussion.

**Comment by roland-d** [comment]
All clear, I was just wondering :)

**Comment by wilsonge** [comment]
We have as of recently in build/bump.php - but that's for another PR.

**Pull request merged**
