### PR TITLE
[5.0] Fix legacy table creation

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #42179 .

### Summary of Changes
If a legacy table is created by Table::getInstance() twice it fails the second time. Reason for this is that the legacy table name is not used if the table class already exists.

### Testing Instructions
Test joomla core and a random 3rd party extension which uses tables

### Actual result BEFORE applying this Pull Request
Could fail if `Table::getInstance()` is called more then 1 time for the same old (JTableXXX) syntax.

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Did you change something in the code? Only intendation is added.

**Comment by Quy** [comment]
Add `w=1` to hide whitespace changes. https://github.com/joomla/joomla-cms/pull/42180/files?w=1

**Comment by laoneo** [comment]
Thanks, I was sure that I miss here something :-)

**Comment by HLeithner** [comment]
@georgebara can you please test this pr?

**Review by georgebara — APPROVED** [review]

**Comment by georgebara** [comment]
Thank you for the fast feedback.

**Comment by richard67** [comment]
@georgebara Was your approval a real successful test? If so, please mark your test result so it's properly counted. For doing this, go to the PR in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/42180 , then use the blue "Test this" button at the top left corner, then select your test result and finally submit. Thanks in advance.

**Comment by georgebara** [comment]
I have tested this item :white_check_mark: successfully on 6265a1bfa18c3d0814a422bb4ab5b9bf4b3b098e<br /><br />The issue could not be reproduced anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42180">issues.joomla.org/tracker/joomla-cms/42180</a>.</sub>

**Review by georgebara — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6265a1bfa18c3d0814a422bb4ab5b9bf4b3b098e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42180">issues.joomla.org/tracker/joomla-cms/42180</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42180">issues.joomla.org/tracker/joomla-cms/42180</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
