### PR TITLE
[4.3] spelling fulfill

### PR DESCRIPTION
**Pull request by brianteeman**
Minor spelling correction to a code comment.

code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dd6f70878864a7e7e2c7268666648b57f59dd0a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39799">issues.joomla.org/tracker/joomla-cms/39799</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dd6f70878864a7e7e2c7268666648b57f59dd0a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39799">issues.joomla.org/tracker/joomla-cms/39799</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39799">issues.joomla.org/tracker/joomla-cms/39799</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
