### PR TITLE
[Imp] Implementing Alert when deleting items

### PR DESCRIPTION
**Pull request by infograf768**
This PR display an Alert to confirm deletion of items.
It works for the Buttons:
Delete
Empty trash
Uninstall

Only 2 new language strings.

com_media is not taken care of in this PR.

To test, patch and try to delete stuff via the buttons above in various list pages in admin.
Example in the Users interface:
screen shot 2016-01-27 at 14 11 22

Note: Brian already looked at the new lang strings.

### CODE REVIEW

**Comment by brianteeman** [comment]
Language strings looks good ;)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d2952d8dec2f203dce2ae92c6d00ad4ff1c23605<br /><br />Tested installer, contacts, menus and articles - worked as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8995">issues.joomla.org/joomla-cms/8995</a>.</sub>

**Comment by Bakual** [comment]
Looks fine from review.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on d2952d8dec2f203dce2ae92c6d00ad4ff1c23605<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8995">issues.joomla.org/joomla-cms/8995</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d2952d8dec2f203dce2ae92c6d00ad4ff1c23605<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8995">issues.joomla.org/joomla-cms/8995</a>.</sub>

**Comment by brianteeman** [comment]
RTC  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8995">issues.joomla.org/joomla-cms/8995</a>.</sub>

**Pull request merged**
