### PR TITLE
[4.0] remove hhvm ci step on travis

### PR DESCRIPTION
**Pull request by rdeutz**
Same as in staging, see https://github.com/joomla/joomla-cms/pull/16232

### CODE REVIEW

**Comment by mbabker** [comment]
This should take care of itself when George merges up staging to 4.0.

**Comment by Bakual** [comment]
Closing as already done in staging. George just has to merge staging into 4.0 and resolve the conflicts correctly 😄

**Comment by wilsonge** [comment]
Goodbye Sunday afternoon. It was nice nearly knowing you 😝

**Comment by rdeutz** [comment]
ok, we will see :-P

**Pull request closed without merging**
