### PR TITLE
[4.2] Add alias for old router class names in container

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Adds an alias for the old router classes in container. Like that point the code `$app::getRouter('Site');` to the same instance as `Factory::getContainer()->get('SiteRouter');`.

### Testing Instructions
Add the following code to the file /plugins/system/schedulerunner/schedulerunner.php at line 110
```
$appRouter = $this->app::getRouter('Site');
$containerRouter = Factory::getContainer()->get('SiteRouter');
$appRouter->setVar('test', 'joomla');
echo $containerRouter->getVar('test');die;
```

### Actual result BEFORE applying this Pull Request
Joomla is not printed.

### Expected result AFTER applying this Pull Request
Joomla is printed

### CODE REVIEW

**Comment by joeforjoomla** [comment]
I have tested this item :white_check_mark: successfully on 48262afb6e6676de099ba0d2439555422e1d2cc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37381">issues.joomla.org/tracker/joomla-cms/37381</a>.</sub>

**Comment by joeforjoomla** [comment]
This PR is correct but it's the contrary:

Actual result BEFORE applying this Pull Request
Joomla is not printed

Expected result AFTER applying this Pull Request
Joomla is printed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37381">issues.joomla.org/tracker/joomla-cms/37381</a>.</sub>

**Comment by richard67** [comment]
@laoneo Your testing instructions are indeed inverted regarding actual and expected result.

**Comment by laoneo** [comment]
Can you change it? Been away on phone only...

**Comment by richard67** [comment]
> Can you change it? Been away on phone only...

@laoneo Done.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 48262afb6e6676de099ba0d2439555422e1d2cc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37381">issues.joomla.org/tracker/joomla-cms/37381</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37381">issues.joomla.org/tracker/joomla-cms/37381</a>.</sub>

**Comment by fancyFranci** [comment]
@laoneo I would like to merge it but you need to update first :)

**Comment by laoneo** [comment]
Updated

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
