### PR TITLE
[4.1] Flag border

### PR DESCRIPTION
**Pull request by brianteeman**
Some flags have a white background and so they do not display correctly. This is particularly true for the japanese flag but its true for other flags as well.

### Before
image

### After

image

This is a css change so will require npm run build:css
**__lets not start another debat here about not using flags or not usings gifs__**

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c9bde9c51b89cf0c05bc26a172b7f28acd7fab8a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36609">issues.joomla.org/tracker/joomla-cms/36609</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on c9bde9c51b89cf0c05bc26a172b7f28acd7fab8a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36609">issues.joomla.org/tracker/joomla-cms/36609</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36609">issues.joomla.org/tracker/joomla-cms/36609</a>.</sub>

**Comment by bembelimen** [comment]
I see the problem here, that any gif everywhere in the backend gets the border.

**Comment by brianteeman** [comment]
Yes I understand that. It was the lowest cost means of correcting the issue

**Comment by brianteeman** [comment]
see #36706 for an alternative solution

**Comment by bembelimen** [comment]
We should go with #36706

**Comment by brianteeman** [comment]
ok

**Pull request closed without merging**
