### PR TITLE
[com_fields] Change the description field of the group to the default editor layout

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
At the moment the description field of a group is a textarea. In Joomla! in general all description fields are editor fields. This PR changes the field to an editor field

### Testing Instructions
Create or edit a field group.
Before: there is a textarea field
After: there is an editor field + the Joomla! text filter parameters are applied

### CODE REVIEW

**Comment by Bakual** [comment]
That's intended to be a textarea. Since the text is used in fieldset (tabs) descriptions where all tags are stripped anyway, it doesn't make sense to have a wysiwyg editor field here. It would only be confusing if you add eg an image to the description and then don't see it in the form.

**Comment by bembelimen** [comment]
We could allow HTML there?

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 0197b1fe0d0a712be8a41a53abe8f3310ce6cb2b<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :red_circle: unsuccessfully on 0197b1fe0d0a712be8a41a53abe8f3310ce6cb2b<br /><br />A warning blocking the Save operation:

**
Warning
Invalid field: JFIELD_RULES_LABEL**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by Bakual** [comment]
> We could allow HTML there?

We probably don't allow it for a reason 😄

**Comment by laoneo** [comment]
I guess when we change to an editor, then we should also allow HTML content in tabs descriptions. But as @Bakual said, there is probably a reason why the tags are stripped.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 0197b1fe0d0a712be8a41a53abe8f3310ce6cb2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 0197b1fe0d0a712be8a41a53abe8f3310ce6cb2b<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by Bakual** [comment]
@joomla/cms-maintainers Needs a decision here.
Changing this to an editor doesn't change anything as long as fieldset (tab) descriptions filter any HTML tags out. So that would would need to be changed as well but I don't know why there is filtering to begin with. I just assume there was a reason for it.

**Comment by laoneo** [comment]
I have tested this item :red_circle: unsuccessfully on 0197b1fe0d0a712be8a41a53abe8f3310ce6cb2b<br /><br />When adding HTML tags to the description trough the editor, then the tags are stripped in the edit form tabs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by laoneo** [comment]
@bembelimen any intention to fix this PR?

**Comment by coolcat-creations** [comment]
Would be nice to have an editor here @bembelimen <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Comment by roland-d** [comment]
Other than we should have an editor here. What is the added value of having an editor?

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by bembelimen** [comment]
The question is: should there be an editor field at all? As I read here, some say yes, some say no... so? If all say "yes", I can fix it.

**Comment by franz-wohlkoenig** [comment]
asking @Production Departement

**Comment by laoneo** [comment]
I will go trough the git history next week to see if there is a reason why it is plain text only atm.

**Comment by laoneo** [comment]
I guess we can't change it because the description gets translated first and then escaped. This would lead to a situation that the HTML code will be shown as output. Relevant line is here https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/edit/params.php#L119. I wen't back in history and this code exists over 4 years like that. So it would probably lead to a BC break when we stop escaping the output. It's a minor one but it will be one at the end. @Bakual what do you think?

**Comment by Bakual** [comment]
Personally I don't see a reason to add HTML to the fieldset description.
In the end I think we end up with more issues if we allow it.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13281">issues.joomla.org/tracker/joomla-cms/13281</a>.</sub>

**Pull request closed without merging**
