### PR TITLE
[4.1] Smart Search: Don't reindex when changing access or publish state

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #32904.

### Summary of Changes
On a large site with Smart Search enabled, changing the state of a category will fail with a timeout, since it will try to reindex all items in the category. While the indexer will abort when noticing that the content is still the same, the plugin will load all those content items (for example articles) and prepare them for indexing. This takes a very long time and in nearly all cases is unnecessary. Thus we remove the reindexing step. If a data source indeed requires the reindexing, it can still add that step back into its plugin when overriding the methods of the Smart Search adapter.

### Testing Instructions
1. Get a huge site, for example from the initial issue report and setup a site with that.
2. Try to publish or unpublish a category with a lot of content in it. The SQL from @PhilETaylor has categories with 1000 articles in them

### Actual result BEFORE applying this Pull Request
The site loads forever and eventually dies.

### Expected result AFTER applying this Pull Request
The category is published and the index is properly updated in a reasonable time.

### CODE REVIEW

**Comment by JenSeReal** [comment]
I have tested this item :white_check_mark: successfully on fee0044d8848d45e94075d3f978223483f4d8e29<br /><br />Tested this with 15,915 articles and 368 categories created with [Overload](https://github.com/nikosdion/overload) with `php ~/overload/overload.php --site-url="http://localhost" --categories-levels=5 --categories-count=3 --articles-count=50`.
On the latest 4.0-dev [commit](https://github.com/joomla/joomla-cms/commit/932dea2c0d59fabff1865d9d4b667baa28b9d09a) I got timeouts (I think when the session times out and you need to relogin) when publishing or unpublishing all categories and doing the same with a category that has many subcategories the same issue occured.
I also tested [this](https://github.com/joomla/joomla-cms/pull/35341) pull request and nothing changed.

With this pull request unpublishing all categories took 52s, and republishing all categories took 1m42s and I could not find any breaking changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33853">issues.joomla.org/tracker/joomla-cms/33853</a>.</sub>

**Comment by pabloarias** [comment]
I have not tested this item.<br /><br />Tested with Overload tool too. 1000 articles per category.

Before applying this patch, I obtain a server error: 502 Bad Gateway.

After applying this patch, it has taken just some seconds.

Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33853">issues.joomla.org/tracker/joomla-cms/33853</a>.</sub>

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on fee0044d8848d45e94075d3f978223483f4d8e29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33853">issues.joomla.org/tracker/joomla-cms/33853</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33853">issues.joomla.org/tracker/joomla-cms/33853</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
