### PR TITLE
[4.3] The "Forbidden MIME Types" parameter is not used

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
In the settings of the **Media** component at the very bottom there is a parameter **Forbidden MIME Types**, which is not used and it is not known if it was ever used. More from Joomla 3x.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
It is even not used when the MIME type check is switched on?

**Comment by Kostelano** [comment]
> It is even not used when the MIME type check is switched on?

@Quy mentioned issue. It just says that the dependency is removed in 3.7.1. At the moment there is no connection with the parameter.

**Comment by ReLater** [comment]
> It is even not used when the MIME type check is switched on?

As reference: https://github.com/joomla/joomla-cms/issues/38280

**Comment by richard67** [comment]
@ReLater Thanks.

**Comment by richard67** [comment]
@Kostelano Can it be that by accident you merged the 4.0-dev branch into the branch for this PR (which is based on 4.3-dev)? The PR shows 56 changed files now on GitHub- Possibly that might be fixed with the next update of the 4.3-dev branch to the 4.2-dev branch. Just wanted to tell so you know the reason.

**Comment by Kostelano** [comment]
Oh, thanks @richard67, I didn't notice. But it seems that I updated the branch as usual, with the 1st button.

**Pull request closed without merging**
