### PR TITLE
Minimizing JArrayHelper by using Joomla\Utilities\ArrayHelper internally

### PR DESCRIPTION
**Pull request by izharaazmi**
Minimizing `JArrayHelper` by using `Joomla\Utilities\ArrayHelper` internally with appropriate deprecation warnings. All functionality of `JArrayHelper` is already available there, so no point keeping duplicate code.

### CODE REVIEW

**Comment by izharaazmi** [comment]
@roland-d No. The fix in https://github.com/joomla-framework/utilities/pull/12 is independent of this PR.

**Comment by izharaazmi** [comment]
Kindly let me know If there something awaited from my part.

**Comment by roland-d** [comment]
@izharaazmi Please provide test instructions that touches this code so users can test that nothing is broken. Code review looks good but that is not enough in this case. Thanks.

**Comment by izharaazmi** [comment]
@roland-d There is no special instruction for this change as I have not made any logical change. No feature added or removed or fixed or improved. The normal tests that applies to `JArrayHelper` (without this patch) or `Joomla\Utilities\ArrayHelper` is applicable for this PR as well.
This means the existing unit test cases are well sufficient for this purpose.

However, I might be wrong in saying so, please enlighten me with your perspective.

**Comment by izharaazmi** [comment]
Please advise if I need to make any changes/improvements to this.
Thanks.

**Comment by roland-d** [comment]
@izharaazmi Finally I had some time to test and the proxies are working fine. Only issue I did find is you changed in the logs the names to __FUNCTION__ and this is not working. The value of __FUNCTION__ is always empty, so I would suggest to revert this change. So your point that the existing unit test cases are sufficient is not correct because they do not test the logging.

To test this issue, you will need to enable debugging mode with XDebug for example to see the changes at work. Editing a category will trigger most changed methods except for the **pivot** and **arrayUnique** methods, these are only unit tested.

**Comment by roland-d** [comment]
I have tested this item :red_circle: unsuccessfully on 7f9ff9d3bc875d79ceee1e0cf5172a6c920540ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Comment by izharaazmi** [comment]
I just tested the 5 methods in `JArrayHelper` with object type arguments. I got these lines in my log file. I see the `__FUNCTION__`  is not empty.

```sh
#Fields: datetime	priority clientip	category	message
2015-10-03T08:47:20+00:00	WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::toObject.
2015-10-03T08:47:21+00:00	WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::toString.
2015-10-03T08:47:21+00:00	WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::getColumn.
2015-10-03T08:47:21+00:00	WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::pivot.
2015-10-03T08:47:21+00:00	WARNING ::1	deprecated	This method is typehinted to be an array in \Joomla\Utilities\ArrayHelper::sortObjects.
```
However, I have still changed those 5 lines to fixed string for the method names.
Thanks.

**Comment by roland-d** [comment]
I have tested this item :red_circle: unsuccessfully on ad48dac00d634fdafa82fa883c3cd5123c4a1cc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Comment by roland-d** [comment]
@wilsonge Can you have a look at this too? Looks good to go for me.

**Comment by izharaazmi** [comment]
@roland-d In your last comment you say 'looks good to me', but your recent test status says: _tested unsuccessfully on ad48dac_. Was there any issue?

**Comment by roland-d** [comment]
@izharaazmi Look at the issue and the test results, I have set the test to successful after your last change.

**Comment by izharaazmi** [comment]
Sorry, but I see the 2nd test too marked as 'tested unsuccessfully' only. May be I'm missing something!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on ad48dac00d634fdafa82fa883c3cd5123c4a1cc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Comment by roland-d** [comment]
Now it is successful :)

**Comment by izharaazmi** [comment]
Thanks!

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on ad48dac00d634fdafa82fa883c3cd5123c4a1cc6<br /><br />Applied the patch and worked for a while, no issues so far. Ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Comment by zero-24** [comment]
RTC. for 3.5.0 Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7782">issues.joomla.org/joomla-cms/7782</a>.</sub>

**Pull request merged**
