### PR TITLE
[#33195] Form validation issues

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This fixes a few problems with formvalidation.js as listed on the tracker here: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33195&start=0

These fixes are only in the uncompressed file. I was wondering if Joomla! has a preferred minifier. Let me know what it is and I'll make the compressed file too. 

Test instructions:
1) Open a form with a field that is both 'required' and 'disabled' (this is a strange case but it's not impossible). 
2) Click submit without selecting or changing any fields. 
3) The required-disabled field(s) will be marked as invalid. 
4) Click submit again. The form will be sent as if valid.

### CODE REVIEW

**Comment by roland-d** [comment]
@okonomiyaki3000 Could you please update to the current staging? Thank you.

**Comment by okonomiyaki3000** [comment]
I was actually thinking that I might close this PR and redo it since several things have changed. Let me see.

**Comment by roland-d** [comment]
@okonomiyaki3000 Thank you for your consideration.

**Comment by okonomiyaki3000** [comment]
Closing in favor of #6409

**Pull request closed without merging**
