### PR TITLE
[4.0] Content Languages action button

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Convert the toolbar buttons in the Content Languages page to use the same actions button as other components

### Testing Instructions
Check that all actions work as expected
Check that the empty trash button appears and works as expected when the filter is set to trashed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 192177dafd5ecd9f260997e3d87865d1632e3fdb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26186">issues.joomla.org/tracker/joomla-cms/26186</a>.</sub>

**Comment by infograf768** [comment]
Works fine.
Any reason to the use of `: void` in
`protected function addToolbar(): void`
which is used for some components but not all of them in core.

**Comment by brianteeman** [comment]
update branch to retrigger drone

**Comment by pravinTek** [comment]
I have tested this item :white_check_mark: successfully on 3623afe4737a8fa3dfd5784697639f95e872ba5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26186">issues.joomla.org/tracker/joomla-cms/26186</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26186">issues.joomla.org/tracker/joomla-cms/26186</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by shinderohanoffical** [comment]
I have tested this item :red_circle: unsuccessfully on 3623afe4737a8fa3dfd5784697639f95e872ba5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26186">issues.joomla.org/tracker/joomla-cms/26186</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
