### PR TITLE
Media manager should consider path variable

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/40690.

### Summary of Changes
When passing a path variable in the browser url, the media manager should take that one to display the files instead of the one from the session.

Some system tests are also provided to make sure the combination between the session and url is playing nicely together.

This is a more lightweight alternative to the pr #40691.

### Testing Instructions
- Go to /administrator/index.php?option=com_media&path=local-images:/sampledata
- Type in the url /administrator/index.php?option=com_media&path=local-images:/banners

### Actual result BEFORE applying this Pull Request
The media manager redirects to the sampledata directory.

### Expected result AFTER applying this Pull Request
The media manager shows the contents of the banners directory.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
It is the same behavior as now, currently you you just have to set the invalid folder in the session.

**Comment by dgrammatiko** [comment]
But the session is only set by the app?

**Comment by laoneo** [comment]
And when you put an invalid path in the url, then an error message is shown:
image

This pr restores the old behavior we had in 4.3.0. Changing the path to a valid one when it is invalid is not the scope of this pr and should probably be done in 5.0.

**Comment by laoneo** [comment]
> But the session is only set by the app?

Yes, but it doesn't mean it can't be invalid. When one user browses to a folder and then another one deletes that folder, you get the same result as with this pr when you put an invalid folder name into the url.

**Comment by dgrammatiko** [comment]
> This pr restores the old behavior we had in 4.3.0.

This behaviour was, and after this PR is still, broken. The state of the app is not set correctly (ie there is no initial selected folder and there is no code to cope with that), in short the media manager initial state could be really harmful

**Comment by brianteeman** [comment]
if a non existing path now results in a success then this is not correct
if you can then write to that then its a security issue

**Comment by laoneo** [comment]
This one restores the same behaviour as before https://github.com/joomla/joomla-cms/pull/40013 which was shipped with 4.3.2. There is nothing new in there.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 24418e1c772fcb6fee9af8814ac24e12b6016a2b<br /><br />The path on the URL is respected but there are quite a few inconsistencies and things should be done differently when media manager is booting. Also The store needs to be migrated to pinia. Allon is aware of this but for 4.3 this is fixing the regression<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40704">issues.joomla.org/tracker/joomla-cms/40704</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 24418e1c772fcb6fee9af8814ac24e12b6016a2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40704">issues.joomla.org/tracker/joomla-cms/40704</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40704">issues.joomla.org/tracker/joomla-cms/40704</a>.</sub>

**Pull request merged**
