### PR TITLE
 Updated installation language files (ru-RU)

### PR DESCRIPTION
**Pull request by Kostelano**
TT coordinator @b2z

Recently we have updated the file in the repository of the Russian team of localizers (https://github.com/JPathRu/localisation/commit/0d337fa311188da3056be05a42f0cfc243774e71).

Escaping quotes `\"`, 2 new constants (https://github.com/joomla/joomla-cms/pull/31426), wording in a single format with other global changes in localization for version 3.9.18 (~40 commits).

### CODE REVIEW

**Comment by Bakual** [comment]
Please use the official way for providing installation language files. Your TT has to post the file in the translation forum so we can pick it from there and do a coordinated PR.

**Comment by b2z** [comment]
Will do ✌️👌

**Comment by Kostelano** [comment]
Ok, sorry, I didn't know about this method :).

Dmitry will do it.

Thanks.

**Comment by b2z** [comment]
Done :+1:

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/31461

**Pull request closed without merging**
