### PR TITLE
[4.0] Simplify for loop in articles model

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Just a small code improvement: Use foreach instead of a complex for loop (so we always use the correct key)

### Testing Instructions
The backend articles view should work exactly the same before and after the patch

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on ebdde82517ec39d5bd076c6ac17e72c4737869b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by rdeutz** [comment]
I have tested this item :red_circle: unsuccessfully on ebdde82517ec39d5bd076c6ac17e72c4737869b0<br /><br />see comment on #15363<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by bembelimen** [comment]
@franz-wohlkoenig @rdeutz could you test again please?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1a13d601d9651eecced99385b6eb3f9628d235ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by coolcat-creations** [comment]
somehow patchtester doesn´t fetch this one ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations you have com_patchtester(beta3) installed?

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig just updated it from beta 3... it just does not catch this and another one... some patches i could test already
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations can you reinstall 4.0-dev? This helps me most if something doesn't work cause i updated per nightly Builds.

**Comment by coolcat-creations** [comment]
it was a brandnew installation due to "make it happen" here in krakow... it´s just this issue not in the patch-list...
i´ll try again in with a new installation next days....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by ghost** [comment]
closed in favor of Pull Request #18183<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Comment by ghost** [comment]
@mbabker cannot close this PR, it always get reopend by joomla-cms-bot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15364">issues.joomla.org/tracker/joomla-cms/15364</a>.</sub>

**Pull request closed without merging**
