### PR TITLE
Correct the usage of getInt in two places

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Correct the usage of getInt in two places

### Testing Instructions

review

### Expected result

getInt just accepts two parameters see: https://api.joomla.org/cms-3/classes/JInput.html#method_getInt

### Actual result

getInt is called with three parameters

### Documentation Changes Required

none

### Reporter to the JSST

@sandewt

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on f1fc93a68fa1b7ce1e737cb1442435df404efb94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17566">issues.joomla.org/tracker/joomla-cms/17566</a>.</sub>

**Comment by sandewt** [comment]
I would also like to test. Do you have instructions how? (I have installed the patchtester.)

**Comment by wilsonge** [comment]
Check that editing your user profile still works in the frontend, and that when editing an article in the frontend you are still correctly redirected to the correct place :)

**Review by wilsonge — APPROVED** [review]

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on f1fc93a68fa1b7ce1e737cb1442435df404efb94<br /><br />Tested in Joomla! 3.8.0-beta3-dev.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17566">issues.joomla.org/tracker/joomla-cms/17566</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys :)

**Pull request merged**
