### PR TITLE
[3.9] Add Argon2id Password Support

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #20826

### Summary of Changes

Per https://wiki.php.net/rfc/argon2_password_hash_enhancements Argon2id password hashes will be supported in PHP 7.3. We should add support for this alongside our existing Argon2i logic.

### Testing Instructions

review

### Expected result

Argon2id PW supported

### Actual result

Argon2id PW NOT supported

### Documentation Changes Required

@mbabker can you tell me where you documented the Argon2i support?

### CODE REVIEW

**Comment by HLeithner** [comment]
I think this will not work.
You have to check for "$argon2id" before checking for "$argon2i" in the if Statement because strpos  "$argon2i"  will already be true for "$argon2id"

**Comment by zero-24** [comment]
fixed by the last commit thanks @HLeithner

**Comment by mbabker** [comment]
> can you tell me where you documented the Argon2i support?

It's not really documented anywhere.  We don't have a place covering this part of the API AFAIK.

**Review by mbabker — APPROVED** [review]

**Comment by HLeithner** [comment]
J4i the rfc has been accepted and is already implemented in php 7.3.

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on c09b09d8196380978608e09c6a8b024b7c6d31f9<br /><br />Successfully on PHP 7.3.0alpha4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20855">issues.joomla.org/tracker/joomla-cms/20855</a>.</sub>

**Pull request merged**
