### PR TITLE
Incorrect position of calendar in Internet Explorer 7-10 (Rework #3079)

### PR DESCRIPTION
**Pull request by Kubik-Rubik**
This is a rework of the PR by @piotrmocko: #3079

Due to conflicts in the compressed JS file and the number of commits it was easier to create a new, clean PR for this issue.

**How to test**
1. Download, install and activate the test module: https://github.com/joomla/joomla-cms/pull/3079#issuecomment-125932042
2. Click on the calendar button in the frontend in the Internet Explorer (7-10) and you will see that the calendar is not displayed directly above the field but much higher. Do the same with a proper browser and you will see that it works as it should.
3. Apply the patch and check again with IE.
   (For more insight, please check the origin PR.)

All kudos to @piotrmocko!

### CODE REVIEW

**Comment by zero-24** [comment]
Just reproduced the bug (With ie10 emulation of ie11 dev tools) and confirmed the patch. Patch don't change the behavoir on ie11 & chrome. Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7643">issues.joomla.org/joomla-cms/7643</a>.</sub>

**Comment by infograf768** [comment]
Warning about merging this in 3.4.4 as we are in language freeze and Persian language pack would have to change their custom calendar. If it is merged, please contact Mohsen Firoozmandan : http://forum.joomla.org/memberlist.php?mode=viewprofile&u=1958

**Comment by Flow87** [comment]
I tested the patch with IE 7,8,9 and 10.
Therefore I emulated each version of IE from 7 to 10.
As expected all versions of IE make the calendar appear at the upper left-hand side of the front end even if the position of it is set to debug.

After I applied the patch all versions were working as intended like if i would have opened the calendar in my firefox.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7643">issues.joomla.org/joomla-cms/7643</a>.</sub>

**Comment by zero-24** [comment]
RTC based on tests. @Bakual can You cordinate the persia calender?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7643">issues.joomla.org/joomla-cms/7643</a>.</sub>

**Comment by Bakual** [comment]
@zero-24 I can't, but maybe @imanickam can.

**Comment by imanickam** [comment]
I have intimated Mohsen Firoozmandan (http://forum.joomla.org/memberlist.php?mode=viewprofile&u=1958) about this and he should be looking into this issue.

I have also discussed this with JM and he has provided a revised language pack that Mohsen would review, test and apply the changes to the revised language pack.

Once I hear back from Mohsen, I will provide more update.

**Comment by zero-24** [comment]
Great thanks @imanickam and @Bakual !

**Comment by imanickam** [comment]
Mohsen Firoozmandan (http://forum.joomla.org/memberlist.php?mode=viewprofile&u=1958), the Translation Coordinator for the Persian language has released the next version of the Persian language pack. Probably the new Persian language pack fa-IR_joomla_lang_full_3.4.4v2.zip at http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6435 could be used for testing.

**Pull request merged**
