### PR TITLE
[4.0] namespace Jplugin

### PR DESCRIPTION
**Pull request by brianteeman**
Fix some missing namespace changes for JPlugin and JPluginHelper

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 896a30ab70e7c1baeeaed81d2ef5901fe12c4310<br /><br />Code review: PR covers all remaining "JPlugin" and "JPluginHelper" uses.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27363">issues.joomla.org/tracker/joomla-cms/27363</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 896a30ab70e7c1baeeaed81d2ef5901fe12c4310<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27363">issues.joomla.org/tracker/joomla-cms/27363</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27363">issues.joomla.org/tracker/joomla-cms/27363</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
