### PR TITLE
[js message system] Correct js messages class

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to correct the colors and titles of the js messages.
##### Before

image
##### After

image
#### Testing Instructions
- Go to isis/protostar index.php and add this code

``` php
// JS Messages
JText::script('MESSAGE');
JText::script('ERROR');
JText::script('NOTICE');
JText::script('WARNING');

JFactory::getDocument()->addScriptDeclaration("
jQuery(document).ready(function() {
    var messages = {
        'message': ['JS Success Message 1', 'JS Success Message 2'],
        'error': ['JS Error Message 1', 'JS Error Message 2'],
        'notice': ['JS Notice Message 1', 'JS Notice Message 2'],
        'warning': ['JS Warning Message 1', 'JS Warning Message 2']
    };
    Joomla.renderMessages(messages);
});");
```
- Now run any isis/protostar page. You'll see the "Before" scenario
- Apply patch
- Repeat step 2 (clear browser cache). You will see the "After" scenario.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 85756931e9fa1736c7522eb39d7a47398f0367d8<br /><br />Good spot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10521">issues.joomla.org/joomla-cms/10521</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 85756931e9fa1736c7522eb39d7a47398f0367d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10521">issues.joomla.org/joomla-cms/10521</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing @brianteeman @infograf768 !

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10521">issues.joomla.org/joomla-cms/10521</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva and testers!

**Pull request merged**
