### PR TITLE
standardise on folder

### PR DESCRIPTION
**Pull request by brianteeman**
We use both terms and really we should standardise on one. We even use both terms on the same page. As you can see in these screenshots its confusing.

folder1
folder2
folder3

This PR standardises to just use the word folder after discussions in the en-GB working group where the consensus was to standardise on using folder. I have added this to the Words2Watch https://github.com/joomla/user-interface-text/blob/master/words2watch.md

### CODE REVIEW

**Comment by jwaisner** [comment]
@test 

PR works as intended. All instances of "Directory" have been replaced with "Folder".

The only one instance I wanted to confirm was the JED. Did we rename it to the JEF?

screen shot 2015-07-22 at 19 33 28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7523">issues.joomla.org/joomla-cms/7523</a>.</sub>

**Comment by infograf768** [comment]
Please stop committing this considerable amount of en-GB only ini value changes for 3.4.4. At least, if we can't avoid them, do that for 3.5.0.

**Comment by Bakual** [comment]
Why? According to SemVer it's absolutely fine to merge this into a patch version.

The workload for translators is exactly the same, doesn't matter in which version it goes.
That is, most can simply ignored by the translators as it doesn't apply to translated languages.

**Comment by infograf768** [comment]
>That is, most can simply ignored by the translators as it doesn't apply to translated languages.

Wrong. We do have to check all of them to know if they are useful or not, and it implies a considerable amount of work. Also, to provide a similar experience to the user, we have to adapt most of them.
The Manager modifications concerned 40 ini files for one PR only + some to come.
I am not sure you are conscious of such a workload.

**Comment by Bakual** [comment]
Yep, the manager one applies to translators. Except for languages where they didn't have that word, like eg in german we didn't use it.

Yes, it is work, but it is the same work if you have to do it for 3.4.4 (if that even will be released) or 3.5.0.

**Comment by brianteeman** [comment]
@jwaisner Thanks for testing. Serves me right for doing a search/replace for the first time ever and not checking. I have fixed the JED references<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7523">issues.joomla.org/joomla-cms/7523</a>.</sub>

**Comment by infograf768** [comment]
Beware to committers, this PR includes installation ini files changes and, if merged, should include en-US, en-AU, en-CA + a specific freeze before next release.

**Comment by brianteeman** [comment]
I can supply the en-US, en-AU, en-CA installation ini file changes if
requested

On 23 July 2015 at 09:34, infograf768 <notifications@github.com> wrote:

> Beware to committers, this PR includes installation ini files changes and,
> if merged, should include en-US, en-AU, en-CA + a specific freeze before
> next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7523#issuecomment-124021751>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
en-US, en-AU, en-CA installation ini file changes have been added<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7523">issues.joomla.org/joomla-cms/7523</a>.</sub>

**Comment by Duke3D** [comment]
Tested and works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7523">issues.joomla.org/joomla-cms/7523</a>.</sub>

**Comment by brianteeman** [comment]
Multiple tests - thanks - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7523">issues.joomla.org/joomla-cms/7523</a>.</sub>

**Comment by brianteeman** [comment]
BTW do we have a way of telling TT not to translate something. A quick check showed that the majority of translated the word "installation" when it is the name of the folder and should not be translated

**Comment by infograf768** [comment]
The TT coordination should inform them of this when asking for the next update.
A good way (better than nothing) is to add a comment before the first use of the word "Installation" + add quotes around that name when it concerns the folder, with no empty line before and after (This last requirement because com_localise will display the comment in that case).
Example:

```
INSTL_COMPLETE_ADMINISTRATION_LOGIN_DETAILS="Administration Login Details"
; When it concerns the folder itself, the word 'installation' should not be translated.
INSTL_COMPLETE_ERROR_FOLDER_ALREADY_REMOVED="The 'installation' folder has already been deleted."
INSTL_COMPLETE_ERROR_FOLDER_DELETE="'installation' folder could not be deleted. Please manually delete the folder."
INSTL_COMPLETE_FOLDER_REMOVED="'installation' folder successfully removed."

etc.
```

**Comment by brianteeman** [comment]
So which do you prefer? I go through all the translation files and add that
note where appropriate and/or we ask the TT co-ordinator to tell the TT to
correct their translations or both.

I'm happy either way and will create a NEW PR with the do not translate
comment if needed.

**Comment by infograf768** [comment]
The en-GB, en-US, en-CA, en-AU have to be corrected as I suggest :
1. adding single quotes each time the word 'installation' concerns the folder.
2. adding the comment the first time before the line where 'installation' is used in that sense

Do not touch please any other language file. It is the responsibility of their respective TTs.
TT Leader Mig will inform them when this will be merged and installation ini files will be frozen.

As the single quotes are necessary, it is this PR that should be updated imho, not a new one that would add to the confusion.

**Comment by brianteeman** [comment]
This PR does not alter the word installation - in fact there is another PR
(cant find it right now I am on my phone) from someone else that addresses
the word installation.

It is NOT just the installation language files that need updating with a
"do not translate" message and it is not just the word "installation" that
should not be translated. I have seen several cases of the "cache, logs and
tmp" folder also being translated and they will need the "do not translate"
message as well.

So no I will not update this PR with the "do not translate" message - it is
beyond the scope of this PR. "One PR per issue" should be the correct
process.

Yes it will create some work for the TT to review this but it can hardly be
helped if they have translated words that should never have been translated
.

On 25 July 2015 at 10:19, infograf768 <notifications@github.com> wrote:

> The en-GB, en-US, en-CA, en-AU have to be corrected as I suggest :
> 1. adding single quotes each time the word 'installation' concerns the
> folder.
> 2. adding the comment the first time before the line where 'installation'
> is used in that sense
>
> Do not touch please any other language file. It is the responsibility of
> their respective TTs.
> TT Leader Mig will inform them when this will be merged and installation
> ini files will be frozen.
>
> As the single quotes are necessary, it is this PR that should be updated
> imho, not a new one that would add to the confusion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7523#issuecomment-124825135>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Well, then you should have used another place to ask your question: I replied. Do whatever you want.

**Comment by brianteeman** [comment]
I will thanks

On 25 July 2015 at 10:41, infograf768 <notifications@github.com> wrote:

> Well, then you should have used another place to ask your question: I
> replied. Do whatever you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7523#issuecomment-124826455>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Merged into `staging`. Thanks!

**Pull request closed without merging**
