### PR TITLE
[5.1] Cleanup input options

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
When the live site parameter was added for some reason rather than adding just that parameter into the existing definition we re-created the entire definition

### Testing Instructions
Check all global options are still available when using the CLI (such as verbosity and the live site parameter). There should be no changes but less code (yay!)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Remove the `use Symfony\Component\Console\Input\InputArgument;` in line 57 because it became obsolete with the other changes, that's why PHPCS fails in drone (new rule for unnecessary use statements).

**Comment by HLeithner** [comment]
conflict's will be solved by upmerging 5.0 to 5.1 soon

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4e2c60a8db2f92c484dcb4df344686b8083db1b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42166">issues.joomla.org/tracker/joomla-cms/42166</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4e2c60a8db2f92c484dcb4df344686b8083db1b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42166">issues.joomla.org/tracker/joomla-cms/42166</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42166">issues.joomla.org/tracker/joomla-cms/42166</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @wilsonge !

**Pull request merged**
