### PR TITLE
[4.0] Discover string fix

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue #26299 .

### Summary of Changes

Added strings JLIB_INSTALLER_DISCOVER_INSTALL="Discover Install"
In admin and site lib_joomla.ini

I noticed that there places where strtoupper is missing: e.g  - Text::_('JLIB_INSTALLER_' . $this->route), - leaving that as a separate issue but could fix if anyone would like to confirm - look in libraries/src/Installer/InstallerAdapter.php

### Testing Instructions

See #26299 
I do not know how to test this PR! I checked the code and I am fairly sure there is only one string missing from the set discover_install, install, update and uninstall. 

### Actual result BEFORE applying this Pull Request

Check the code: the strings are missing.

### Expected result AFTER applying this Pull Request

Check the code: the strings are present.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by chmst** [comment]
I think that the string 'discover_install" is wrong and should be only "discover" in installer_adapter.php. Then the Language Key is in the language file like all the others.

**Comment by SharkyKZ** [comment]
@ceford This PR is fine but can you make it against staging instead?

**Comment by ceford** [comment]
> @ceford This PR is fine but can you make it against staging instead?

Being relatively new to github, I don't know how to change a pr. And I don't know how changes in staging make their way to 4-Dev. I don't seem to have staging on my local clone. A few pointers would be helpful.

**Comment by SharkyKZ** [comment]
@ceford Depends on what you're using. If branch is not available, you may need to use `git checkout` command to check out staging branch.

**Comment by brianteeman** [comment]
You can change the branch here

ceford

**Comment by ceford** [comment]
Closing this to create a new request with new base. I don't get a list of my requests so I can't select this one to edit.

**Pull request closed without merging**
