### PR TITLE
[4.0] Backend - Fix Privacy Requests Alert

### PR DESCRIPTION
**Pull request by YatharthVyas**
Pull Request for Issue #33696

### Summary of Changes
- Add two missing language strings to the js file and modified the alert code by removing the old parts. (This fixed the undefined)
- Add `btn-small` class so the Button doesn't look oversized as compared to the text
- The 4.0 language string for the message uses %s to map the Count of Messages and hence I added the entire text inside the countSpan to ensure that it stays together and so that the use of innerHTML is avoided. In the previous language string, there was no %s so that justifies why the initial code could have the count and string in separate HTML tags.

### Testing Instructions

1. Please follow the instructions given in #33696
2. Apply Patch and `npm run build:js`

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 56676fb67c38c4ac039e16a4f9f145142b41fe83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33735">issues.joomla.org/tracker/joomla-cms/33735</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 56676fb67c38c4ac039e16a4f9f145142b41fe83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33735">issues.joomla.org/tracker/joomla-cms/33735</a>.</sub>

**Comment by ceford** [comment]
And I see you have the Home Dashboard problem for which I described a fix in the Forum: https://forum.joomla.org/viewtopic.php?f=803&t=986269&sid=c9245193e86a36cac77c0c382ea9ad1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33735">issues.joomla.org/tracker/joomla-cms/33735</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33735">issues.joomla.org/tracker/joomla-cms/33735</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by YatharthVyas** [comment]
Thank you

**Pull request merged**
