### PR TITLE
MediaHelper: proper check if file is an image (#42105)

### PR DESCRIPTION
**Pull request by coderiekelt**
Pull Request for Issue #42105.

### Summary of Changes
- Changed `MediaHelper.php` to properly check if the uploaded file is actually an image, instead of assuming `true`.

### Testing Instructions
Upload a PDF file to the media library, this should work properly. Uploading images will also still work fine in accordance with previous behavior.

### Actual result BEFORE applying this Pull Request
Uploading a PDF fails, providing an unhelpful error to the user. When checking the request in within the browser the message is along the lines of "This is not a valid image".

### Expected result AFTER applying this Pull Request
Uploading a PDF works fine, uploading images still follows the previous behavior.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
unable to test as I cannot replicate the reported error

**Comment by brianteeman** [comment]
i can confirm that this issue occurs when exif is not available.

**Comment by brianteeman** [comment]
Some history https://github.com/joomla/joomla-cms/issues/16086

Which should have been fixed with https://github.com/joomla/joomla-cms/pull/16091

**Comment by richard67** [comment]
> Some history #16086
> 
> Which should have been fixed with #16091

@brianteeman Yes, but that code has been modified meanwhile. In PR #16091 it was checked if the file name extension is in the allowed list for images, and if that was the case, the `static::getMimeType` method was called with value `true` for the `$isImage` parameter. That was right.

Later the code was changed so it uses the list of allowed file name extensions for uploads, which can also be e.g. a video or a PDF file; `params->get('restrict_uploads_extensions', 'bmp,gif,jpg,jpeg,png,webp,ico,mp3,m4a,mp4a,ogg,mp4,mp4v,mpeg,mov,odg,odp,ods,odt,pdf,png,ppt,txt,xcf,xls,csv')`

The `static::getMimeType` method then checks with EXIF only when that parameter has value true, but that would fail for a video or PDF file:

https://github.com/joomla/joomla-cms/blob/4e36f775954e62fa3dde7083ae0c79f144544944/libraries/src/Helper/MediaHelper.php#L92-L96

So to me the change made by this PR here seems to be right. It replaces the hard-coded `true` value by the result of the `static::isImage` call, which does nothing else than checking the file name extension again for valid values for images.

**Review by richard67 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fde2fe859c7fec019fe2af2588f60dad79f23663<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43345">issues.joomla.org/tracker/joomla-cms/43345</a>.</sub>

**Comment by Fedik** [comment]
> Uploading a PDF fails, providing an unhelpful error to the user

The fix for unhelpful message is there https://github.com/joomla/joomla-cms/pull/38536

**Comment by Fedik** [comment]
Hm, the getMimeType() should not care about `isImage`, it should read the file mime for any file, regardless its type.
But that another issue.

As for now the PR is okay.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on fde2fe859c7fec019fe2af2588f60dad79f23663<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43345">issues.joomla.org/tracker/joomla-cms/43345</a>.</sub>

**Comment by Fedik** [comment]
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43345">issues.joomla.org/tracker/joomla-cms/43345</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
