### PR TITLE
[4.0] kill flash

### PR DESCRIPTION
**Pull request by brianteeman**
There really is no reason to have a check for a dead format.

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b56ad4080220abbcc8d60516a67affcf4a41f26b<br /><br />1. Code review: The function is not used anywhere in our code.
2. Facts review: The Flash format is dead.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34045">issues.joomla.org/tracker/joomla-cms/34045</a>.</sub>

**Comment by softforge** [comment]
Zombies? Always good to be prepared

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b56ad4080220abbcc8d60516a67affcf4a41f26b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34045">issues.joomla.org/tracker/joomla-cms/34045</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34045">issues.joomla.org/tracker/joomla-cms/34045</a>.</sub>

**Comment by brianteeman** [comment]
I guess flash wasn't the saviour of the universe after all

**Pull request merged**
