### PR TITLE
Calendar off screen detection broken when window scrolled

### PR DESCRIPTION
**Pull request by cheesegrits**
Pull Request for Issue #23243.

### Summary of Changes

Fix for bounds detection in the calendar field.  Currently, calendar fields at the bottom of the viewport will be opened off screen, if the window has been scrolled down.

See https://github.com/joomla/joomla-cms/issues/23243

### Testing Instructions

Add a calendar field to a long form, for example the Options fieldset in the com_content backend.  Around line 604 in administrator/components/com_content/models/forms/article.xml, just before the close fieldset, add ...

```
			<field
					name="foobar"
					type="calendar"
					label="foobar"
					description="foobar"
					translateformat="true"
					showtime="true"
					size="22"
					filter="user_utc"
			/>
```

Now edit an article, switch to the Options tab and scroll down so the new 'foobar' date field is at the bottom of the window.  Open the calendar widget.

### Expected result

Widget should open above the field, fully visible

### Actual result

Widget opens below the field, mostly off screen.

Apply this PR, and the widget will open correctly, above the field.  No other behavior is changed, dates on non scrolled pages, or near the top of the viewport, are not affected.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by cheesegrits** [comment]
Just to be clear, the issue is that getBoundingClientRect() returns coordinates relative to top left of the viewport, not the document:

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

... so scrollY should not be added to the window's innerHeight when comparing that with the bottom of the calendar's container.

**Comment by Quy** [comment]
Please apply the same change to `calendar.min.js`.

**Comment by cheesegrits** [comment]
What minifier should I use?

**Comment by mbabker** [comment]
There isn't a standard one for 3.x, the last time I did something with JavaScript on 3.x I used https://jscompress.com/

**Comment by cheesegrits** [comment]
OK, I finally took the time to figure out how to minify automagically in PHP Storm.  Used uglifyjs which is what I use for my component (although I do it in a Grunt build script, as our paths get a bit too complicated to do on the fly).

The result seems to be a little larger than the original, not sure what it was originally compressed with, but nothing major.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b7f6f81df0d11e579eb8e1459f8fa3407085ef60<br /><br />OK here, although I do not have the issue on Firefox Macintosh.
Before patch:
calendar-before
After patch
calendar-after


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23244">issues.joomla.org/tracker/joomla-cms/23244</a>.</sub>

**Comment by infograf768** [comment]
Difference with using https://jscompress.com/ is a bit much imho as it is around 4-5KB

**Comment by cheesegrits** [comment]
@infograf768  OK, I'll redo the minification.

Also, the issue kind of depends on browser and surrounding CSS.  The example you posted, your browser has resized the container the calendar is in and made the page longer to accommodate it (and probably auto-scrolled the page to bring it into view).  But some browsers won't do that, and some front end site templates (like Gantry) prevent the container being auto-resized, so the calendar literally becomes inaccessible.

**Comment by Quy** [comment]
I use this one: https://skalman.github.io/UglifyJS-online/

**Comment by cheesegrits** [comment]
I'm just reluctant to use online minifiers, as there's no way to tell if malicious code is being injected.  So I'm dicking around with a few options in PHP Storm, see if I can get the size down a bit.

**Comment by cheesegrits** [comment]
@infograf768 - OK, back down to 25k, the original size.

**Comment by trob** [comment]
I have tested this item :white_check_mark: successfully on 0478781ea4769a4dbf17249a23c997266ca65e78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23244">issues.joomla.org/tracker/joomla-cms/23244</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0478781ea4769a4dbf17249a23c997266ca65e78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23244">issues.joomla.org/tracker/joomla-cms/23244</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23244">issues.joomla.org/tracker/joomla-cms/23244</a>.</sub>

**Comment by cheesegrits** [comment]
Thanks, guys 'n' gals.

**Pull request merged**
