### PR TITLE
Set an empty string value to the legacy otpKey and otep columns if empty

### PR DESCRIPTION
**Pull request by nikosdion**
Pull Request for Issue #38543 .

### Summary of Changes

Modified the User table to add empty string values to the `otpKey` and `otep` columns if they are empty.

**NORMALLY THIS SHOULD NOT BE NECESSARY**. The table definition gives a default value of an empty string to both columns and the reported issue cannot be reproduced.

However, if your site came from a series of upgrades from older versions and/or transferred between servers by hand it might end up having these columns as `NOT NULL` but without a default value.

### Testing Instructions

From the CLI folder run

```bash
php joomla.php user:add --username=foobar --name="Foo Bar" --email=foobar@example.com --password="P@s5w0rD" --usergroup=Registered
```

### Actual result BEFORE applying this Pull Request

It works on all sites except the issue reporter's site.

### Expected result AFTER applying this Pull Request

It works on all sites.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 12f665c3ab73994fe87398766354073e1e5ee204<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38549">issues.joomla.org/tracker/joomla-cms/38549</a>.</sub>

**Comment by Webdongle** [comment]
Please reopen. https://forum.joomla.org/viewtopic.php?f=808&t=998623 appears to be the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38549">issues.joomla.org/tracker/joomla-cms/38549</a>.</sub>

**Comment by nikosdion** [comment]
Reopening as this is a recurring issue, per https://github.com/joomla/joomla-cms/pull/38549#issuecomment-1363261274

Kind reminder @fancyFranci @roland-d that this **needs** to be fixed in 4.2, ideally four months ago.

BTW, this fixes a simple mistake I made in an earlier PR that none of you caught (because y'all were too busy bikeshedding instead of _actually_ testing during the entire month you were bombarding me with hundreds of mostly nonsense comments). Also note that I came here with a fix for it as soon as 4.2.1 was out which is when people actually started upgrading to 4.2. I don't understand why this trivial fix of an issue with a real world impact is still languishing in the PR purgatory.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 177be860b3fab60856a4a49b2dac75b52afc02dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38549">issues.joomla.org/tracker/joomla-cms/38549</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks @nikosdion

**Comment by nikosdion** [comment]
Thank you! This will help folks work with their legacy template overrides without undue frustration 🎉

**Pull request merged**
