### PR TITLE
[4.1]  order formdata

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/36346 .

### Summary of Changes

Send all the form data (although it's useless as you only need the changed id's for reordering) to the PHP

### Testing Instructions

- The core still works as before because **it doesn't need any extra data**

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### CODE REVIEW

**Comment by brianteeman** [comment]
impossible to test

**Comment by dgrammatiko** [comment]
> impossible to test

Well, we can confirm that the core still works as expected so that the core is not broken but these changes. The extra bits on the payload would be useful for devs doing things out of the core API and that's untestable but also should be ok if we didn't broke the core extensions...

**Comment by PhocaCz** [comment]
To test it: Use browser with DevTools enabled (e.g. Google Chrome). Create articles and sort them. In DevTools switch to Network tab, to "Fetch/XHR" tab and see the AJAX results (see image):


img

When the patch is not applied, you will see only cid and order variable.

When the patch is applied, you will see more form data available. When you see them, you can mark this test as successfull.

Jan

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on d88638c83038e45dea4b76a394fcf39207cb82a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36353">issues.joomla.org/tracker/joomla-cms/36353</a>.</sub>

**Comment by jwaisner** [comment]
@dgrammatiko 

Please update the PR to the latest branch.

**Comment by dgrammatiko** [comment]
@bembelimen  is there any interest for this one or should I close it?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 746b970dc6026ac10709d0fdb8913bca427df4e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36353">issues.joomla.org/tracker/joomla-cms/36353</a>.</sub>

**Comment by laoneo** [comment]
image

**Comment by laoneo** [comment]
Tested with reordering a module and the last screenshot is the request with all variables.

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36353">issues.joomla.org/tracker/joomla-cms/36353</a>.</sub>

**Comment by dgrammatiko** [comment]
@bembelimen any decision here?

**Comment by roland-d** [comment]
Thanks everybody.

**Comment by dgrammatiko** [comment]
Nice, that was my last pending PR, so good news for me

**Pull request merged**
