### PR TITLE
Adding a Limit Box to Languages Manager: Installed languages

### PR DESCRIPTION
**Pull request by infograf768**
To test:
Install more than 5 languages via Extension Manager Install.
Go to Modules Manager and set the limit box to 5.
Go to Languages Manager: Installed languages
The # of languages displayed in the list is 5. No way to change it in the manager.

Patch and retest.

### CODE REVIEW

**Comment by infograf768** [comment]
Screenshot after patch
screen shot 2015-06-19 at 10 41 41

**Comment by infograf768** [comment]
Merged. They were there before my patch it seems. :)

**Comment by zero-24** [comment]
Thanks :smile: Tested successful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7201">issues.joomla.org/joomla-cms/7201</a>.</sub>

**Comment by brianteeman** [comment]
Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7201">issues.joomla.org/joomla-cms/7201</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7201">issues.joomla.org/joomla-cms/7201</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Looks good for me but could you please correct the indents (line 23 - 30), then I will merge it. Thanks!

**Comment by infograf768** [comment]
Which indents?
We have now
```
<form action="<?php echo JRoute::_('index.php?option=com_languages&view=installed&client=' . $clientId); ?>" method="post" id="adminForm" name="adminForm">
<?php if (!empty( $this->sidebar)) : ?>
	<div id="j-sidebar-container" class="span2">
		<?php echo $this->sidebar; ?>
	</div>
	<div id="j-main-container" class="span10">
<?php else : ?>
	<div id="j-main-container">
<?php endif;?>
```

If I move all these one indent to the right, then `<div id="j-main-container">` will not be aligned anymore with its closing `</div>`

**Comment by Kubik-Rubik** [comment]
@infograf768 You are right, thank you. Merged.

**Pull request closed without merging**
