### PR TITLE
[5.3] Upmerge 2024-11-14

### PR DESCRIPTION
**Pull request by LadySolveig**
Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@LadySolveig System tests are failing for the contact router single contact without menu item test. It seems it needs to revert my fix from here https://github.com/joomla/joomla-cms/pull/44434/commits/4f2a09ef42676f91647ebecdef27bf1e73117e17 .

**Comment by heelc29** [comment]
It needs this commit
https://github.com/joomla/joomla-cms/commit/aab9ce1d1631d202e1483cb219bf8aa8ed74f09a
I can create later a PR for it.

**Comment by heelc29** [comment]
> I can create later a PR for it.

check out #44459

**Comment by HLeithner** [comment]
closing in favor of #44463

**Pull request closed without merging**
