### PR TITLE
[5.3] handle check

### PR DESCRIPTION
**Pull request by brianteeman**
Resolve todo as we only support php8 now.

This should probably have been done when I did #41885

Original PR where this check was added https://github.com/joomla/joomla-cms/pull/28694

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aca08a874a629f59f6698db28ccae83958cf7e7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44275">issues.joomla.org/tracker/joomla-cms/44275</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on aca08a874a629f59f6698db28ccae83958cf7e7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44275">issues.joomla.org/tracker/joomla-cms/44275</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44275">issues.joomla.org/tracker/joomla-cms/44275</a>.</sub>

**Comment by rdeutz** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
