### PR TITLE
[namespace] Move JTable* to namespaces

### PR DESCRIPTION
**Pull request by laoneo**
Moving JTable* to namespace.

More detailed explanation can be found in #13683.

### CODE REVIEW

**Comment by laoneo** [comment]
Ping @wilsonge and @mbabker for a review.

**Comment by mbabker** [comment]
I don't think they need a `Type` subnamespace.  `Joomla\Cms\Table\Asset` is more than adequate.

**Comment by laoneo** [comment]
Honestly they don't even belong there, they should be put into the right components, that's why I want to separate them.

**Comment by mbabker** [comment]
Except not all of the tables actually belong to a component.  There's no assets component, and I'd call the update and user tables system tables versus extension tables (com_installer or com_users in this case), just using what's in the `libraries/joomla/table` directory.

**Comment by mbabker** [comment]
So thinking out loud here, it looks like JTableContent might be the only candidate to move to an extension.

Categories and menus have library classes (JCategories and JMenu), moving the table classes couples the library and component and we should try to not do that.

Extension tables (JTableExtension and JTableModule) are also system and have management UIs exposed through a few components.  So I think those are good to stay too.

As I said before, user and ACL related tables are definitely system tables.  Honestly JUser and JTableUser are pretty well independent of com_users and aside from whatever internal couplings exist to the component you could presumably run a site without that component at all.

And that leaves the UCM and history tables.  History I guess could be argued either way (that one is kinda bound to the component but at the same time IIRC uses UCM style data structure).  UCM as I've hinted at earlier I'd love to have revisited to figure out how it ties into Joomla's future.

**Comment by laoneo** [comment]
Ok, moved the rest of tables as well.

**Comment by wilsonge** [comment]
:+1:

**Pull request merged**
