### PR TITLE
[4.0] Correct update SQL

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Corrects columns in SQL update file.

### Testing Instructions

Code review.

CC @wilsonge

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cd86f909e6f8e46d95989e508e2ef35004af21d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24143">issues.joomla.org/tracker/joomla-cms/24143</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cd86f909e6f8e46d95989e508e2ef35004af21d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24143">issues.joomla.org/tracker/joomla-cms/24143</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
