### PR TITLE
[5.1] Add SVG support to mod_banners

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

It is possible to assign SVG files to banners, however, the module does not reflect it, only allowing image files.

Notes:

An isImage function was created specifically for Banners. However, it should not be necessary to have such a function since the MediaHelper offers it as well. To ensure Banners support the same image file extensions as the rest of the core, I opted for the use of the MediaHelper instead.

SVG files act a bit differently than image files.
When forcing a width and a height on a image, the image will 'follow' those dimensions.
A SVG file will be scaled to fit its defined viewport. So it won't 'obey' a specific height if you set one for the banner.
Depending on your situation, you may have to restrict the SVG's height with max-height.

Use of SVGs in mod_banners is safe, the SVG files are checked in MediaHelper::getMimeType.

### Testing Instructions

Create banners in the administration console. Some use standard image files, some use SVG files.

### Actual result BEFORE applying this Pull Request

Only banners with standard image files are shown.

### Expected result AFTER applying this Pull Request

Banners with standard image files and SVG files are shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: [link](https://github.com/joomla/Manual/pull/205) (about the deprecation)
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 611d72e6fde962b75db16319b3b08d52482728f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41854">issues.joomla.org/tracker/joomla-cms/41854</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 611d72e6fde962b75db16319b3b08d52482728f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41854">issues.joomla.org/tracker/joomla-cms/41854</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 611d72e6fde962b75db16319b3b08d52482728f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41854">issues.joomla.org/tracker/joomla-cms/41854</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41854">issues.joomla.org/tracker/joomla-cms/41854</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 9755714fb8898ed3bef6b2de68e4325fe5eac13c<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41854">issues.joomla.org/tracker/joomla-cms/41854</a>.</sub>

**Pull request merged**
