### PR TITLE
[4.0] Fix type in table head in tmpl-file of com_contact

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # .

### Summary of Changes
Changed `td `to `th` in table head of template default.php in com_contact.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4d2b2ff1b71de9aff4b60afe9a6382db4fd98d4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24546">issues.joomla.org/tracker/joomla-cms/24546</a>.</sub>

**Comment by brianteeman** [comment]
No. This was correct as TD.

**Comment by alikon** [comment]
not an expert but a td tag between th tag is correct ?  
sorry for the dumb question

**Comment by brianteeman** [comment]
That cell is not a header. If you check the same field in other views you will see they are all td

**Comment by astridx** [comment]
> That cell is not a header. If you check the same field in other views you will see they are all td

@brianteeman 
Yes, I have seen that too. And also in the body of the table is a `th` element that I would change to a `td`.
But: I do not understand why that is. Could you explain that please?

**Comment by brianteeman** [comment]
The HTML < th > element defines a cell as header of a group of table cells

The HTML < td > element defines a cell of a table that contains data

**Comment by wilsonge** [comment]
Closing. Basically what Brian says is correct when you have a select all element it causes screenreader issues per https://stackoverflow.com/questions/39901980/select-all-checkbox-in-table-header-is-causing-issues and so the workaround for us has been to use a td element. in the head.

**Comment by astridx** [comment]
@wilsonge Many Thanks for the link. Now I think I have understood the problem. 
If I see it correctly, the td element is a help. A better solution would be to move the "select-all" to the end of the table. But because the table can be spread over several pages, this is not trivial.

**Comment by wilsonge** [comment]
Yeah td is definitely a work around. We can probably create a tfooter to do the same thing. Unsure if it’s a better solution. But no it’s definitely not trivial.

**Pull request closed without merging**
