### PR TITLE
 set() returns the old value of the variable #9276 (revised)

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue #8859

Testing instructions remain the same as referenced in the issue:
$session = JFactory::getSession();
$session->set('test', 1);
echo $session->set('test', 2);

### CODE REVIEW

**Comment by richard67** [comment]
@GABBAR1947 Seems you have indented with 8 spaces and the 1 tab instead of 2 tabs? Or was it edited on GitHub, and GitHub did that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9285">issues.joomla.org/joomla-cms/9285</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21e9fec9016a1afcebc70f95e14ed85f93b962d2<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9285">issues.joomla.org/joomla-cms/9285</a>.</sub>

**Comment by GABBAR1947** [comment]
@richard67 This is the first time I'm facing such kind of issues on github. It's absolutely fine on my system, must be github issue.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21e9fec9016a1afcebc70f95e14ed85f93b962d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9285">issues.joomla.org/joomla-cms/9285</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21e9fec9016a1afcebc70f95e14ed85f93b962d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9285">issues.joomla.org/joomla-cms/9285</a>.</sub>

**Comment by richard67** [comment]
It seems GitHub (or the bot?) is really confused. Whatever I test after a new commit, it still refers to this old commit 21e9fec, which always drops to the end.

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 21e9fec9016a1afcebc70f95e14ed85f93b962d2<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9285">issues.joomla.org/joomla-cms/9285</a>.</sub>

**Comment by wilsonge** [comment]
Merged

**Pull request closed without merging**
