### PR TITLE
[4.0] Set min-width for select fields

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
What it says on the tin

### Testing Instructions
Apply patch. Navigate to Article edit -> Options

### Before patch
select-width1

### After patch
select-width2

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 16f7d80b00e309f125b4793c0bbe242c85136510<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14731">issues.joomla.org/tracker/joomla-cms/14731</a>.</sub>

**Comment by tonypartridge** [comment]
@ciar4n funnily enough I was just thinking about the same. But should we exclude some items. It seems like a lot of wasted space in small items like limits and short valued lists.

screen shot 2017-03-18 at 17 23 57

**Comment by ciar4n** [comment]
@tonypartridge We could do that. It would mean targeting each of these fields individually...

Eg. 

```
select[name="jform[list_limit]"],
select[name="jform[feed_limit]"] {
  min-width: auto;
}
```

**Comment by ciar4n** [comment]
The SCSS linter doesn't allow the use of IDs so would need to use the name attrib

**Comment by tonypartridge** [comment]
@wilsonge can we merge this? And if the UX team have anything to say we can look at it more then. But otherwise, this to me improves the native view.

**Review by dgrammatiko — APPROVED** [review]

**Pull request merged**
