### PR TITLE
Change the getItem return type to stdClass and make the CMSObject inherit it

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
To get away from the CMSObject class we need a step by step process in the getItem function of the admin model. Alternative to #42714 which makes the `CMSObject` a `stdClass` and changes the return type to it. It is a more lightweight solution as no new deprecated flag is introduced. It has basically the same effect as when we change the flag in 6.0.

### Testing Instructions
Create an article in the back end. With as many content plugins as possible.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/232
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 080cca9abe134c034cde296f0152b8b88a8fef7f<br /><br />I've created an article with a number of custom fields and schema stuff. No difference before / after patch so I guess it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42717">issues.joomla.org/tracker/joomla-cms/42717</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 080cca9abe134c034cde296f0152b8b88a8fef7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42717">issues.joomla.org/tracker/joomla-cms/42717</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42717">issues.joomla.org/tracker/joomla-cms/42717</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @laoneo and also for testing @crommie and @viocassel

**Pull request merged**
