### PR TITLE
[4.0] s/td/th

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

correctly close a `th` with ` /th` and not a `/td`

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2a67602373f3e2f10a7fe38cb402a300151f206c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36340">issues.joomla.org/tracker/joomla-cms/36340</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2a67602373f3e2f10a7fe38cb402a300151f206c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36340">issues.joomla.org/tracker/joomla-cms/36340</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36340">issues.joomla.org/tracker/joomla-cms/36340</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
