### PR TITLE
UI/UX Review for com_redirect on mobile devices

### PR DESCRIPTION
**Pull request by zero-24**
see: https://github.com/joomla/joomla-cms/issues/5628

This is a proposal UI/UX review on mobile for the redirect component.
### Bevor this Patch

mobile_com_redirect_bevor
### After this Patch

mobile_com_redirect_after

### CODE REVIEW

**Comment by brianteeman** [comment]
I think there is a bigger UI problem with this component and it effects all
resolutions.

If the plugin is running then it will end up capturing lots of crazy long
URLs that we dont wrap. I would look at the PR that @philetaylor mad to
etap crazy long article titles

**Comment by zero-24** [comment]
@brianteeman i think this is out of scope of this PR :smile: This should only fix the `resolution` issue.

**Comment by brianteeman** [comment]
:) I suppose I asked for that. I will do a separate PR

**Comment by zero-24** [comment]
Thanks @brianteeman

**Comment by brianteeman** [comment]
@test all good thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5665">issues.joomla.org/joomla-cms/5665</a>.</sub>

**Comment by waader** [comment]
@test success! If the scope was to hide several columns on small devices.

**Comment by zero-24** [comment]
thanks @waader 

>If the scope was to hide several columns on small devices.

Yes the other issue is handeled by @brianteeman with this PR: https://github.com/joomla/joomla-cms/pull/5679<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5665">issues.joomla.org/joomla-cms/5665</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5665">issues.joomla.org/joomla-cms/5665</a>.</sub>

**Comment by roland-d** [comment]
@zero-24 Can you please check your files since they can't be applied. I get the following errors:
error: patch failed: administrator/components/com_redirect/views/links/tmpl/default.php:120
error: administrator/components/com_redirect/views/links/tmpl/default.php: patch does not apply

Your branch may be out of sync.

**Comment by zero-24** [comment]
Closing: https://github.com/joomla/joomla-cms/pull/5665 It fixes the merge conflicts Thanks @roland-d

**Pull request closed without merging**
