### PR TITLE
Convert the system Redirect plugin to use lowercase urls at all times…

### LINKED ISSUE #12666: Redirect component uses inconsistent case sensitivity
### Steps to reproduce the issue
Create a redirect link for http://www.mysite.com/page to go to http://www.mysite.com/mypage. 
Enter a URL of http://www.mysite.com/page, successful redirect to http://www.mysite.com/mypage.
Enter a URL of http://www.mysite.com/Page , returns 404. 
Attempt to create a redirect link for http://www.mysite.com/Page in the redirect component, returns the message "Source URL must be unique".

### Expected result
either both urls http://www.mysite.com/Page and . . . /page would successfully redirect 
OR
allow entry of redirect for both source URLS /Page and /page.

I think first would be preferred.screen shot 2016-10-31 at 14 10 12

### System information (as much as possible)
See attached screenshot of system info display.

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue # .

### Summary of Changes
Converted the Redirect System Plugin to store in lowercase and match redirect on lowercase. I've gone for strtolower since it's url based. But we could replace it with mb_strtolower for UTF-8 standards if you think it is needed but it is slower.

### Testing Instructions
Create an article on your website say: my-article and access it in the frontend. Perfect. remove e from it so change the url to say: mywebsite.com/inde.php/my-articl and now you get a 404, next change it to mywebsite.com/inde.php/My-articl and you get a 404. But you now have two redirects to do in the redirects component. 
 
### Expected result
upper and lowercase 404 urls show be equal since J! stores menu item aliases in lowercase.
### Actual result
both lowercase and uppercase 404's are stored and matched independently. 
### Documentation Changes Required

Resolves #12666

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
guess testing on legacy routing?

**Comment by tonypartridge** [comment]
Testing is for Default routing, not the new Router since that is disabled by default and doesn't appear to work with the redirects component.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on deae8cd0c56bd42465fec5d95037d900a89aac86<br /><br />Legacy Routing, the Redirect Plugin is enabled. The option 'Collect URLs' is enabled.

#### With PR:
Original-URL: index.php/sample-sites
- index.php/sample-site > 404
- index.php/sample-Site > 404

One disabled Redirect `index.php/sample-site`
#### Same without PR got two Redirect
- `index.php/sample-site`
- `index.php/sample-Site`

#### Test on:
Joomla! 3.7.0-beta1
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13853">issues.joomla.org/tracker/joomla-cms/13853</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on deae8cd0c56bd42465fec5d95037d900a89aac86<br /><br />:+1: Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13853">issues.joomla.org/tracker/joomla-cms/13853</a>.</sub>

**Comment by zero-24** [comment]
RTC #jc17de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13853">issues.joomla.org/tracker/joomla-cms/13853</a>.</sub>

**Comment by josarnold** [comment]
**This was actually not a good idea!** - There are several circumstance when case sensitive behavior is needed. Guess you have images to redirect or old static html files. In my opinion it would have been better to give the component a real case sensitive behavior. **We have a lot of trouble through this change.** :-1:

**Comment by brianteeman** [comment]
Please don't comment on a closed issue. It won't be seen. Please create a new issue and reference this

**Comment by tonypartridge** [comment]
As brain said please open a new issue. 

The problem with your scenario is it is not directly related to Joomla! This change follows Joomla! Standards directly, where uppercase characters are not used within URLs and the redirects component is for this. Plus you couldn't create a redirect uppercase and lowercase as it conflicts its self due to the way joomla handles it.

It is also good practice to not have uppercase characters in urls.

In your scenario you could create a little custom plugin which bypasses this, or use one of the many sef components.

**Comment by josarnold** [comment]
ok, thanks

**Comment by tonypartridge** [comment]
You are welcome, it may also be worth pointing or most modern web servers treat upper and lower case equally and they are no longer unique see:

https://github.com/joomla/joomla-cmS

Is the same as

https://github.com/joomla/joomla-cms

You may want to look at update the server and add the required module to handle this accordingly.

**Pull request merged**
