### PR TITLE
[4.0] Fix saving in modal window not working

### PR DESCRIPTION
**Pull request by Arpit-24**
Pull Request for Issue #23260  .

### Summary of Changes

Retrieving content from iframe is changed. This fixes the issue, and to ensure compatibility across various browsers the || (or) statement was necessary.

### Testing Instructions

Install current 4.0-dev with testing sample data.
Go to any menu item of type Category List, Single, Contact, Single Article, Single News Feed
Edit item in modal window
Try save using Save or Save & Close buttons

### Expected result

Item saved

### Actual result

Fixed Item saved

### Documentation Changes Required

None

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 497b22b7e998eef1546c9763cb5f1cea733483d6<br /><br />Works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24350">issues.joomla.org/tracker/joomla-cms/24350</a>.</sub>

**Comment by infograf768** [comment]
I tested after patching with https://issues.joomla.org/tracker/joomla-cms/24349

**Comment by brianteeman** [comment]
The or statement is not necessary as contentDocument is supported by all the browsers joomla supports - we dont need to add support for browsers below ie8 
 https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument#Browser_compatibility

**Comment by Arpit-24** [comment]
> The or statement is not necessary as contentDocument is supported by all the browsers joomla supports - we dont need to add support for browsers below ie8
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentDocument#Browser_compatibility

Updated

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f3936d8f5f01d0de62c7db53d117221727e79097<br /><br />Works after patching with https://issues.joomla.org/tracker/joomla-cms/24349<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24350">issues.joomla.org/tracker/joomla-cms/24350</a>.</sub>

**Comment by infograf768** [comment]
restarted drone

**Comment by Quy** [comment]
Closing in favor for PR #25001.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24350">issues.joomla.org/tracker/joomla-cms/24350</a>.</sub>

**Pull request closed without merging**
