### PR TITLE
[4.0] document extracted vars

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

When using the `extract` function in PHP you should always document what vars are being created, this is especially important when using IDE's and static analysis tools. 

### Testing Instructions

code review - dump `$displayData` if you wish and check 

Screenshot 2021-12-18 at 15 39 53

### Actual result BEFORE applying this Pull Request

`$params` and `$module` are undefined in the method and IDEs struggle to understand what is happening 

### Expected result AFTER applying this Pull Request

Better code quality

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 148747755572e5f236bf06634363a3111befe497<br /><br />Tested successfully in 4.0.6-dev using PHP 8.0.13.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36348">issues.joomla.org/tracker/joomla-cms/36348</a>.</sub>

**Comment by Fedik** [comment]
It more useful to have in the module layouts, in each tmpl/blabla.php Instead of Dispatcher.
Also `$buttons` not available for all modules, you probably have checked QuickIcon module.

**Comment by PhilETaylor** [comment]
what I did was run `get_defined_vars` and then document them...

**Comment by Fedik** [comment]
"Global variables" is set here: https://github.com/joomla/joomla-cms/blob/148747755572e5f236bf06634363a3111befe497/libraries/src/Dispatcher/AbstractModuleDispatcher.php#L109-L118

There no "buttons" as you can see :wink: 

But it exists in QuickIcon Dispatcher.

**Comment by PhilETaylor** [comment]
In fact my screenshot proves what I did, I did not use get_defined_vars I used `dd($displayData)`

Anyway, the only two that are needed to stop static analysis breaking are modules and params...

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 79b5b267a4530b6636f65daf59750ef11741ec65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36348">issues.joomla.org/tracker/joomla-cms/36348</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 571f0b3dc29e1575a6232dadde732b1ce1cf2448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36348">issues.joomla.org/tracker/joomla-cms/36348</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36348">issues.joomla.org/tracker/joomla-cms/36348</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
