### PR TITLE
[4.0] some more fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Fixes for the latest sync with 3.x

### Testing Instructions

- Code review

screen shot 2017-06-07 at 16 52 51

### CODE REVIEW

**Comment by dgt41** [comment]
@wilsonge

**Comment by wilsonge** [comment]
Whats this PR doing? I have absolutely no clue :)

**Comment by dgt41** [comment]
- gets the path polyfill with grunt
- removes the -uncompressed.js
- sorts the tab-state.js/tab-state.min.js (the first had the minified version)

**Comment by Bakual** [comment]
@wilsonge Looks like he fixes your wrong merge conflict fixing 😆

**Comment by dgt41** [comment]
And a fix to jquery.simplecolors.min.js which we renamed some time ago to simplecolors.min.js (due to wrong file handling of filenames with multiple `.`)

**Comment by wilsonge** [comment]
Conflicts

**Comment by dgt41** [comment]
@wilsonge fixed

**Pull request merged**
