### PR TITLE
[4.0] [com_contenthistory] Add check for real null datetimes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This is a follow up to recently merged PR's which changed datetime columns in database for real null values.

Because content history might be used not only for core components' database tables, the checks for the old (preudo-)null datetimes are kept and extended by the check for real null values.

The PR makes sure that in the comparison and preview models, no datetime formatting is done with null values.

### Testing Instructions

Code review should be sufficient: Make sure that in com_contenthistory there are no other places where old (preudo-)null datetimes are checked without checking for real null values, too.

### Expected result

Datetime values which have real null values in database are shown as emtpy and not as any rubbish date.

### Actual result

Datetime values which have real null values in database might be shown as some rubbish date or lead to formatting errors.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
Drone failure seems to be unrelated.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e494e8084e3c9d276569ccd1a39da52dad7fff2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26777">issues.joomla.org/tracker/joomla-cms/26777</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e494e8084e3c9d276569ccd1a39da52dad7fff2a<br /><br />By review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26777">issues.joomla.org/tracker/joomla-cms/26777</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26777">issues.joomla.org/tracker/joomla-cms/26777</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks too.

**Pull request merged**
