### PR TITLE
[com_fields] Remove obsolete custom fields code

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
As captcha was removed from the custom fields types in #12719 this PR removes some obsolete code in the captcha form field.

### Testing Instructions
The captcha plugin should work as before.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cc7dfe1fa496c8aa8daf671ae0779d8090ec9a52<br /><br />Sorry I didnt spot that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12803">issues.joomla.org/tracker/joomla-cms/12803</a>.</sub>

**Comment by laoneo** [comment]
No problem...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b900c7aa63229fcf4eee9c5acc90119640dce42f<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12803">issues.joomla.org/tracker/joomla-cms/12803</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b900c7aa63229fcf4eee9c5acc90119640dce42f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12803">issues.joomla.org/tracker/joomla-cms/12803</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
