### PR TITLE
Remove unused fieldsets from Category List

### PR DESCRIPTION
**Pull request by smz**
#### Summary of Changes

In "Category List" we have (_since Joomla 3.0 if I'm not mistaken_) two fieldsets and related "tabs" which I think are of no usage: "**Options**" (_which is for setting **articles** options_) and "**Integration**" (_for setting RSS feeds related options_), but in "Category **List**" we just build up a list of articles with just links to them: no article has **ever** been displayed by that view and hence all related options are totally ineffective.
#### Testing Instructions

Not much to test... everything should work "_business as usual_"...

### CODE REVIEW

**Comment by brianteeman** [comment]
Integration tab for rss feeds is used - you can see that by viewing the source with feeds on and feeds off

Options is used - you can see this by setting the first option - show title to hide<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10055">issues.joomla.org/joomla-cms/10055</a>.</sub>

**Comment by richard67** [comment]
@smz Sure you changed the righ file? I would expect the categoy list to be "components/com_content/views/categor**ies**/tmpl/default.xml" and **not** "components/com_content/views/categor**y**/tmpl/default.xml", which is the one you changed. The latter one is the one where you also can find the blog views, so there the article-related options should be kept, or am I wrong?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10055">issues.joomla.org/joomla-cms/10055</a>.</sub>

**Comment by brianteeman** [comment]
Closed as this is simply wrong<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10055">issues.joomla.org/joomla-cms/10055</a>.</sub>

**Comment by smz** [comment]
@richard67 the xml for the "Category Blog is "components/com_content/views/category/tmpl/blog.xml" (not "default.xml")

**Comment by richard67** [comment]
And what is "components/com_content/views/categories/" good for then?

**Comment by smz** [comment]
it is for the "List All Categories" view/menu item

**Comment by brianteeman** [comment]
It doesnt matter what file it is. As I stated before the options are in use
as can be clearly seen if you change the values

On 22 April 2016 at 23:21, Richard Fath <notifications@github.com> wrote:

> And what is "components/com_content/views/categories/" good for then?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10055#issuecomment-213608359>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
No Brian, they are not: maybe just the title thing (_I'm checking right now_), but not all the others... think it over...

**Comment by richard67** [comment]
@smz Ah I see, thanks for the info.

**Comment by brianteeman** [comment]
I cant help it if you are wrong but i can stop you having bad code accepted

On 22 April 2016 at 23:25, Richard Fath <notifications@github.com> wrote:

> @smz <https://github.com/smz> Ah I see, thanks for the info.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10055#issuecomment-213610389>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
Sorry, Brian, you're wrong: the title is controlled by the "Category Title" option in the "Category" tab, not in the "Options" tab. Please test...

**Comment by smz** [comment]
And as far as regards the RSS feed there is not a single line of PHP code referencing it in the view. Please review...

**Comment by mbabker** [comment]
The RSS stuff is coming from the parent `JViewCategory` class: https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/category.php#L302

Don't just look at the single class and assume it's unused.  You also have to look at parent classes in some cases.

**Comment by smz** [comment]
> The RSS stuff is coming from the parent JViewCategory class: https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/category.php#L302

... oops!

Your opinion about article's option @mbabker ?

**Comment by mbabker** [comment]
I don't know.  Without explicitly tracing every single option you can't say what's used or not used where.  There's a part of me that doubts though that an entire tab is totally ignored.

**Comment by brianteeman** [comment]
As you dont seem to believe me I made a video of core joomla with testing
sample data showing that both the integrations tab and the options tab are
being used.

https://www.dropbox.com/s/j0aooskw0g9ru4z/10055.mp4?dl=0

On 22 April 2016 at 23:37, Michael Babker <notifications@github.com> wrote:

> The RSS stuff is coming from the parent JViewCategory class:
> https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/category.php#L302
>
> Don't just look at the single class and assume it's unused. You also have
> to look at parent classes in some cases.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10055#issuecomment-213613555>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
The video is the proof - I didnt just close the PR because I dont like you.
I closed the PR because you were completely wrong

On 22 April 2016 at 23:42, Michael Babker <notifications@github.com> wrote:

> I don't know. Without explicitly tracing every single option you can't say
> what's used or not used where. There's a part of me that doubts though that
> an entire tab is totally ignored.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10055#issuecomment-213614713>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
Apart the RSS thing (_with which I've to admit I'm not familiar, and which I'm reverting_) my rationale is the if that there is not a **single point** in the view's template where those option are referenced (_and we are talking about options that should have a **visible** effect on the generated view_), then the options are "unused".

But I might be wrong: I see while I'm writing the @brianteeman has prepared a video to look at... give me the time to watch it, please...

**Comment by mbabker** [comment]
Ya know what, I change my mind.  I have no freakin' clue anymore what's used where or not used.  A search on the `show_title` param (https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=show_title&type=Code) honestly leaves me clueless whether it is actually used by core in the default layout (or its sublayouts) of com_content's category view.

Even if it isn't, if a template's implemented the param though, it's a B/C break.

And people wonder why I hate how many options are in the Joomla UI...

**Comment by smz** [comment]
> Even if it isn't, if a template's implemented the param though, it's a B/C break.

I don't think so as in case of an override also the xml should be overridden (_or am I wrong ?_)

**Comment by mbabker** [comment]
You can create a layout override without creating a XML override.

**Comment by smz** [comment]
@brianteeman 

I've watched your screen capture and I totally agree as far as regards the RSS feed thing. I was wrong on that.

As far as regards the article titles appearing/disappearing in the single article view... I don't understand... is it because the "Category List" is the only menu item "controlling" the the article view?

**Comment by mbabker** [comment]
Another thought dawned on me.  The params may not even apply directly to the category view but rather articles on the article view which have inherited the menu item params for its parent category view.

Translation.  I ain't got a clue, and I honestly don't care enough to find out.  There are too many possible combinations to test effectively.

**Comment by richard67** [comment]
> is it because the "Category List" is the only menu item "controlling" the the article view?

Yes, I think it depends on if you have a menu item for the single article or not.

**Comment by smz** [comment]
> Translation. I ain't got a clue, and I honestly don't care enough to find out. There are too many possible combinations to test effectively.

Yes... I guess it all comes from the "_somehow unpredictable_" or at least "_difficultly predictable_" way the router associates "things" and what comes in control as far as regards options...

**Comment by brianteeman** [comment]
No it is perfectly predictable and working exactly how it is supposed to be
working

On 23 April 2016 at 00:01, Sergio Manzi <notifications@github.com> wrote:

> Translation. I ain't got a clue, and I honestly don't care enough to find
> out. There are too many possible combinations to test effectively.
>
> Yes... I guess it all comes from the "*somehow unpredictable*" or at
> least "*difficultly predictable*" way the router associates "things" and
> what comes in control as far as regards options...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10055#issuecomment-213618801>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
> No it is perfectly predictable and working exactly how it is supposed to be working

Have a look at https://github.com/joomla/joomla-cms/issues/9717 ...

**Comment by richard67** [comment]
Anyway ... even if this PR was wrong, I learned something new from it.

**Comment by smz** [comment]
> Anyway ... even if this PR was wrong, I learned something new from it.

me too...

**Comment by richard67** [comment]
Question is if it is worth to keep that all in mind when things will soon change completely with 4.0 :tongue:

**Comment by richard67** [comment]
was joking

**Comment by smz** [comment]
soon? :confused:

**Comment by richard67** [comment]
months ago if looking at old project schedules :smile:

**Comment by Bakual** [comment]
It's really simple. The options aren't used in the cageories list, but they are used once you navigate from the categories list down to a single category or article view. Then the params from the menu take precedence over the global component params and you can eg hide the author in that specific menu item.
If the category or article **item** has own options set, then it gets a bit more complex, but that's not the topic here :smile:

**Pull request closed without merging**
