### PR TITLE
[4] add missing class import statement

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 6bfaa784f1b962e1798c7f096411e04a19ca3649<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34006">issues.joomla.org/tracker/joomla-cms/34006</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6bfaa784f1b962e1798c7f096411e04a19ca3649<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34006">issues.joomla.org/tracker/joomla-cms/34006</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34006">issues.joomla.org/tracker/joomla-cms/34006</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
