### PR TITLE
Update en-GB.com_cpanel.ini - ul tag not closed properly

### PR DESCRIPTION
**Pull request by waader**
A ul tag in COM_CPANEL_WELCOME_BEGINNERS_MESSAGE is not properly closed so the "hide this message" button is not aligned left as it should. In the backend go to the post-installation messages and observe the alignment of "hide this message" buttons before and after this patch.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 1fb580bcbee5884f06731cc5815689a95eea3f3b<br /><br />Works great. Simple change. :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8461">issues.joomla.org/joomla-cms/8461</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on https://github.com/joomla/joomla-cms/commit/1fb580bcbee5884f06731cc5815689a95eea3f3b

**Comment by zero-24** [comment]
RTC.

@andrepereiradasilva you can use the "test this" button on  issues.joomla.org to record your test. That send this message automagic see: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results as well as alter the test to our database so we can filter on this more easy ;) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8461">issues.joomla.org/joomla-cms/8461</a>.</sub>

**Comment by andrepereiradasilva** [comment]
oh ok :) thanks @zero-24

**Pull request merged**
