### PR TITLE
Bug #27080 fix: Incorect id generated for input fields in repetable s…

### PR DESCRIPTION
**Pull request by ankushmaherwal**
Bug #27080

Summary of Changes
For repetable subform if the name of any field in the subform contains hyphen (-) then the id of the clone is not generated correctly.

If we click on (+) button to add the clone of the subform then the id of the field with hyphen (-) in name do not contain correct number of the clone, instead X is shown in the id.

Testing Instructions
Check the value of id attribute of input element in repetable subform after clicking the plus (+) button to add new clone of sub-form with a field having name hyphen (-) in it.

E.g If we have repetable subform field named as 'office-address' then the id of the elements in the cloned set should be like this 'jform_office_address__office_address1__address' but it is generated as 'jform_office_address__office_addressX__address'

Expected result
The value of id attribute of input element should contain clone number and not X

Actual result
The clone number for the field is not getting replaced with X

Documentation Changes Required
no change required in documentation

### CODE REVIEW

**Comment by HusiBT** [comment]
I have tested this item :white_check_mark: successfully on 64c3c90fcb563d630e1e742ba3f4f6e94f27f28e<br /><br />Seems to work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27081">issues.joomla.org/tracker/joomla-cms/27081</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 64c3c90fcb563d630e1e742ba3f4f6e94f27f28e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27081">issues.joomla.org/tracker/joomla-cms/27081</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27081">issues.joomla.org/tracker/joomla-cms/27081</a>.</sub>

**Review by amit4106udale — APPROVED** [review]

**Comment by amit4106udale** [comment]
I have tested this item :white_check_mark: successfully on ef4ed487df75c29def2201f26759f23796d892a1<br /><br />Working with all the editors<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27081">issues.joomla.org/tracker/joomla-cms/27081</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by grantg182** [comment]
I have tested this item :white_check_mark: successfully on ef4ed487df75c29def2201f26759f23796d892a1<br /><br />Works with TinyMCE and "None", in 3.9.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27081">issues.joomla.org/tracker/joomla-cms/27081</a>.</sub>

**Pull request merged**
