### PR TITLE
J Installation: loss of session when getting to the "remove" view

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #25130 .

### Summary of Changes
Fixes the session handler to be consistent during the installation (in both name and handler) so that before and after the configuration file is written you preserve your session

### Testing Instructions
Copy down the french language pack for the installation directory from Joomla 3. Run the installer in french and check after installation on the success page that Joomla is still in french (obviously there will be some strings in english/missing things as you've copied the old 3.x pack)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4ab2399bd69a9dd8498d3c27720fab360878e8cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27439">issues.joomla.org/tracker/joomla-cms/27439</a>.</sub>

**Comment by infograf768** [comment]
Will test tomorrow. Hint: no need to use the French installation folder from J3.
Just use en-US instead of en-GB as installation language and check source.

**Comment by wilsonge** [comment]
Yah sorry. Ones a language and ones imposter syndrome language :p

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 11d6b6490913d4fbdb9e9da51f42f30db4285786<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27439">issues.joomla.org/tracker/joomla-cms/27439</a>.</sub>

**Comment by infograf768** [comment]
tks. One less. :)

**Pull request merged**
