### PR TITLE
Disable sql query cache in debug mode

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13265.

### Summary of Changes

This PR makes the query cache disabled when db driver runs in debug mode.
Only for mysql, because the profiling only seems to work there. 

Also add checks for profiling in pdomysql (was missing), which meand pdo mysql driver now as the "Profile" in debug console too.

### Testing Instructions

1. Apply patch
2. Enable debug mode in global config and system debug plugin
3. Test Mysql, MySqli and PDO Mysql drivers: Reload the pages and confirm in debug console "Database Queries" "Profile" that each query in run without using db cache

#### Example

With query cache
image

Without query cache
image

### Documentation Changes Required

None.

### Notes

- Didn't test "mysql" driver because is not available in my test server (only "mysqli" and "pdo (mysql)")
- before merging, this should be reviewed from a expert db person.
- More info http://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html

### CODE REVIEW

**Comment by csthomas** [comment]
There is also option `DEMAND` which may add some flexibility.
http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_query_cache_type
https://mariadb.com/kb/en/mariadb/server-system-variables/#query_cache_type

I do not know if anybody care but for mysql driver missing line:
`mysql_query($this->connection, 'SET profiling_history_size = 100;');`

**Comment by andrepereiradasilva** [comment]
Grande i noticed that too. Didn't add it because i have no MySQL drivers to test. If anyone confirms it works i can add it.

**Comment by csthomas** [comment]
IMHO It does not depend on type of driver like mysql or mysqli or pdomysql.
http://stackoverflow.com/questions/8443674/profiling-and-optimising-php-mysql-websites

**Comment by andrepereiradasilva** [comment]
ok added to mysql too, but his needs to be tested in mysql also

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on eecd48e05faada6f691f8d731600914251a48f8d<br /><br />Code review + I have tested it before and after patch on mysql, mysqli and pdomysql with successful.
On debug mode is now with out checking query cache.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13268">issues.joomla.org/tracker/joomla-cms/13268</a>.</sub>

**Comment by waader** [comment]
Profil comes with this message: "No SHOW PROFILE (maybe because there are more than 100 queries)"
But I have only 26 queries logged.  The system plugin is enabled with each option set to yes.

Does somebody know what´s going on here?

**Comment by brianteeman** [comment]
> The query cache is deprecated as of MySQL 5.7.20, and is removed in MySQL 8.0.

>  as of MySQL 5.6.8 query cache is now disabled by default
source https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html

**Comment by csthomas** [comment]
@brianteeman Is there any rule? How to become a new owner?

**Comment by mbabker** [comment]
Fork the source branch of the PR, make your changes, and open a new PR.

**Comment by brianteeman** [comment]
@csthomas will you be able to take over this?

**Comment by csthomas** [comment]
I created a new PR #20322.

**Comment by ghost** [comment]
closed in favor of PR #20322 as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13268">issues.joomla.org/tracker/joomla-cms/13268</a>.</sub>

**Pull request closed without merging**
