### PR TITLE
[4.4] plugins\filesystem\local\src\Adapter\LocalAdapter.php

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Spotted this code style issue while working on something else. Might as well fix it.
Code review only

Maintainers can decide which branch to merge it into
### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ad9f6f0de4c18d3b6ecbe43285d4efb710f3e33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43274">issues.joomla.org/tracker/joomla-cms/43274</a>.</sub>

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43274">issues.joomla.org/tracker/joomla-cms/43274</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1ad9f6f0de4c18d3b6ecbe43285d4efb710f3e33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43274">issues.joomla.org/tracker/joomla-cms/43274</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43274">issues.joomla.org/tracker/joomla-cms/43274</a>.</sub>

**Comment by brianteeman** [comment]
sorry I found another one in the same file please retest

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 29fc372e99da7cf8de11c6c4ead4af8cb5f77c01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43274">issues.joomla.org/tracker/joomla-cms/43274</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
