### PR TITLE
[4.0] Update Checks quickicon module

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #28669 and elsewhere

This module displays many things that are not updates so lets change the module title to Notifications

### CODE REVIEW

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on d01d73c0aee931fdc3e1645539d631a1b4576a78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31733">issues.joomla.org/tracker/joomla-cms/31733</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d01d73c0aee931fdc3e1645539d631a1b4576a78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31733">issues.joomla.org/tracker/joomla-cms/31733</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31733">issues.joomla.org/tracker/joomla-cms/31733</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
