### PR TITLE
[j4] html5 language update

### PR DESCRIPTION
**Pull request by brianteeman**
Replace all remaining instances of `<br/> and <br/>`

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on c1b48cbd27a7e1c8c4fdc0257417e5a8532a35b3<br /><br />Made my day<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15110">issues.joomla.org/tracker/joomla-cms/15110</a>.</sub>

**Comment by brianteeman** [comment]
I did it just for you ;)

**Comment by brianteeman** [comment]
Would you like me to change the i to em and the b to strong as well? It's not as clear cut a case for changing them

**Comment by C-Lodder** [comment]
depends on whether or not the words should be emphasised or they just need to have bold styling.

**Comment by brianteeman** [comment]
@c-lodder I will leave that change for another day as it would also require making a decision on the existing em strongg

**Pull request merged**
