### PR TITLE
[4.0] Error in legacy plugins when method contains $event argument

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes legacy plugins being registered as modern plugins when method takes `$event` argument.

### Testing Instructions

install and enable this plugin: [plg_system_dummy.zip](https://github.com/joomla/joomla-cms/files/5223563/plg_system_dummy.zip).

### Actual result BEFORE applying this Pull Request

>Argument 1 passed to PlgSystemDummy::onDummyTest() must be of the type string, object given

### Expected result AFTER applying this Pull Request

No errors.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
@SharkyKZ 

Installed dummy plugin. Joomla 4.0.0-beta4
Before Patch:
0 Argument 1 passed to PlgSystemDummy::onDummyTest() must be of the type string, object given, called in /......./libraries/vendor/joomla/event/src/Dispatcher.php on line 495 

Couldn't return to Dashboard & now site is broken.
Will install tomorrow a new fully nightly (4.0.0-beta5) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30575">issues.joomla.org/tracker/joomla-cms/30575</a>.</sub>

**Comment by SharkyKZ** [comment]
That's expected behavior before patch.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7e7b73ce1face83b71003b65ae11fab560be4040<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30575">issues.joomla.org/tracker/joomla-cms/30575</a>.</sub>

**Comment by ChristineWk** [comment]
> 
> 
> That's expected behavior before patch.

Of course, the message before patch was expected, but not, that my site becomes complety broken.

What I did:
At first I deleted the dummy plugin via phpMyAdmin successfully & backend was available again.
The possibility for an update tor 4.0.0-beta5 was shown > but unsuccessful, because got: AJAX Loading error ...
(Correct server nightly xml)

Therefore I deleted space/database and installed fully nightly 4.0.0-beta5 plus Patchtester etc.
Then activated this Patch (did not check now message before Patch :-) 
Installed your Dummy plugin and Result: No failure/message.

**Comment by ChristineWk** [comment]
Hmmm: After successful Patch (see above) I reverted it and got the failure again. Backend broken now.
Will try to delete dummy Plugin via phpMyAdmin again.

For other testers: Please before reverting Patch: de-active Plugin ....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30575">issues.joomla.org/tracker/joomla-cms/30575</a>.</sub>

**Comment by SharkyKZ** [comment]
I hope you're not testing on live site 😅

**Comment by ChristineWk** [comment]
> 
> 
> I hope you're not testing on live site 😅

It's a live site (space), but for testing purposes only of course :-)
Will never forget your plugin -hv deleted it now  :-)

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7e7b73ce1face83b71003b65ae11fab560be4040<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30575">issues.joomla.org/tracker/joomla-cms/30575</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30575">issues.joomla.org/tracker/joomla-cms/30575</a>.</sub>

**Comment by laoneo** [comment]
Conflicts here...

**Comment by SharkyKZ** [comment]
Conflicts fixed.

**Comment by SharkyKZ** [comment]
Last commit changes condition order for optimization. No change in functionality.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
