### PR TITLE
[4.0] [plg_extension_finder] Use injected database object

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use injected database object.

### Testing Instructions

Plugin works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on f16b7e4811f120f453dd173a5002f061d51eb0ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25622">issues.joomla.org/tracker/joomla-cms/25622</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f16b7e4811f120f453dd173a5002f061d51eb0ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25622">issues.joomla.org/tracker/joomla-cms/25622</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25622">issues.joomla.org/tracker/joomla-cms/25622</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
