### PR TITLE
Articles - Latest

### PR DESCRIPTION
**Pull request by brianteeman**
The descriptions says "This module shows a list of the most recently published and current Articles."

So if they are "current" then they cant also "may have expired"

Simple PR to correct that on the front end

For the admin version of the module the change is a little different as here the list will show all the articles irrespective of their current published state so the string change is different and is just a simplification and not a correction

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bbada145e43e1047c5f0d4d63ac679fdfda6f013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19664">issues.joomla.org/tracker/joomla-cms/19664</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on bbada145e43e1047c5f0d4d63ac679fdfda6f013<br /><br />The part concerning the admin module is correcting a wrong description and is perfectly OK.

The part concerning the frontend module is wrong as any Editor and up, when logged in, will also get in the list articles which are not current, i.e. whose Publishing date has expired.

Please correct PR, i.e. take of the part concerning the admin module.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19664">issues.joomla.org/tracker/joomla-cms/19664</a>.</sub>

**Comment by brianteeman** [comment]
I  disagree. The aim of the description is to describe its pur

**Comment by brianteeman** [comment]
The purpose of the description is to explain the intended and typical usage. It cannot nor should it cover everything. I will not be changing this pr.

**Comment by infograf768** [comment]
You are mistaking even more as the xml description is only seen by people who have access to the backend and they should know what the module really displays, not only what you describe as a "typical" use.
I hope this will not be merged as is.

**Comment by brianteeman** [comment]
If that is true then we will need to review every string .accept this pr or reject this pr. I stand by it.

**Comment by mbabker** [comment]
> The part concerning the frontend module is wrong as any Editor and up, when logged in, will also get in the list articles which are not current, i.e. whose Publishing date has expired.

Authenticated users are treated differently site wide based on ACL.  Every language string cannot reasonably account for these ACL based differences.  So IMO the general use case for the module is fine for the description unless we are going to add every potential caveat to it (without using hardcoded group names since as we know the groups are customizable).

**Comment by infograf768** [comment]
Why was I expected this? I wonder...

**Comment by mbabker** [comment]
I just don't agree with adding extra text to the description basically saying "when authenticated a user may see additional content that unauthenticated users do not because of their additional ACL privileges" is all.  Nothing to do with round 14268950 of the JM/Brian fight.

**Comment by infograf768** [comment]
this pr is not adding extra text. it takes it off. it was satisfying everyone until today. it has nothing to do with who made the pr.  to be clear, i was asked to check it although i try to avoid that kind of pr because of a specifc lobby.  i will not anymore. you are not the only one to be fed up.

**Comment by brianteeman** [comment]
Language is no different to code. There are bugs that need to be fixed. If we are ever to be more than a hobby project then we need to improve quality

**Comment by wilsonge** [comment]
After some discussion in maintainers and with @mbabker I'm merging this

**Pull request merged**
