### PR TITLE
Separate login and logout forms in beez3 template

### PR DESCRIPTION
**Pull request by jo-sf**
About 4 years ago the login and logout forms have been separated in `modules/mod_login/tmpl`, but this separation never made its way into the beez3 template. This PR will change this...
#### Testing Instructions

For testing this change you need a current Joomla installation with the sample data installed.

**Status Quo**
- open the site homepage
- locate the menu "A Deep Menu" (on the right side, scroll down)
- click on "Using Joomla!"
- again locate the menu "A Deep Menu" and click on "Using Extensions"
- click on the "Templates" link in the middle of the screen
- click on the "Home Page" link below "Beez 20" in the middle of the screen
- the next page is shown using the "beez3" template
- scroll down and locate the "Login Form" (on the left side)
- notice that the text "Log in" at the button is blue
- log in using any valid user name and password
- again scroll down and locate the "Login Form" (same place as before)
- notice that the text "Log out" at the button is black
- press the "Log out" button
- click on the "Beez 2" link in the breadcrumb line

**Changes**
- install this PR
- click on the "Home page" link in the article area (I assume that you're still at the page from the end of the "Status Quo" test instructions)
- again locate the "Login form" and notice that it looks as before, including the blue "Log in" text
- log in using any valid user name and password
- again scroll down and locate the "Login Form"
- notice that the logout form looks nearly the same as before, the only change is that the "Log out" text is now blue
- press the "Log out" button

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 94f777d87e729d4f85c02bd40c50e8b5788b0dc0<br /><br />just change the default template to beez3 in template manager and made the test
works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11531">issues.joomla.org/joomla-cms/11531</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 94f777d87e729d4f85c02bd40c50e8b5788b0dc0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11531">issues.joomla.org/joomla-cms/11531</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 94f777d87e729d4f85c02bd40c50e8b5788b0dc0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11531">issues.joomla.org/joomla-cms/11531</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11531">issues.joomla.org/joomla-cms/11531</a>.</sub>

**Pull request merged**
