### PR TITLE
[4.0] Change fa-fw to icon-fw

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
To remove references to FontAwesome, use generic icon class.
Change fa-fw to icon-fw.
Change order for consistency.

### Testing Instructions
Code review.

or

Log in to the administration area.
View Post Installation Messages/Private Messages buttons in the upper right corner.
Icons same before/after PR.

### CODE REVIEW

**Comment by ChristineWk** [comment]
@Quy Sorry, maybe I make something wrong.
Hv now 50:50 :-)
View Post Installation Messages = OK
screen shot 2021-05-19 at 17 24 40

`<span class="icon-bell icon-fw" aria-hidden="true"></span>`

But I couldn't see the Private Messages buttons in the upper right corner.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33980">issues.joomla.org/tracker/joomla-cms/33980</a>.</sub>

**Comment by Quy** [comment]
> But I couldn't see the Private Messages buttons in the upper right corner.

It is hidden by default when there are no new private messages.

To make it appear, please do the following in this file:
administrator/modules/mod_messages/tmpl/default.php

`if ($hideLinks || $countUnread < 1)`
to
`if ($hideLinks)`

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d24022c51e6d128a09747d8f3c7b96ae08f91c35<br /><br />@Quy Thanks for the hint. Changed the code via FTP accordingly.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33980">issues.joomla.org/tracker/joomla-cms/33980</a>.</sub>

**Comment by ChristineWk** [comment]
OK now:

`<span class="icon-envelope icon-fw" aria-hidden="true"></span>`
screen shot 2021-05-19 at 17 54 28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33980">issues.joomla.org/tracker/joomla-cms/33980</a>.</sub>

**Comment by brianteeman** [comment]
I trust if you are going to insist on this **pointless** change then you will be updating all the other instances in the admin. There is a valid reason to use a generic class in the frontend but none in the admin

**Comment by Quy** [comment]
Nope. There are only 2 instances of `fa-` in the backend, thus, this PR. The rest are `icon-.`

**Comment by brianteeman** [comment]
Search again

**Comment by Quy** [comment]
Well this PR makes these icons consistent with the other icons in the header. I am blind to what you are referring to so please enlighten me.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d24022c51e6d128a09747d8f3c7b96ae08f91c35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33980">issues.joomla.org/tracker/joomla-cms/33980</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33980">issues.joomla.org/tracker/joomla-cms/33980</a>.</sub>

**Comment by brianteeman** [comment]
sorry I was searching a branch of mine that had a lot of extensions installed and I didnt realise. There is only one fa- remaining

`fa-8x`

**Comment by Quy** [comment]
Mystery solved. I will do a PR for fa-8x. Thank you!

**Pull request merged**
