### PR TITLE
[3][com_content] fix php8 Deprecated

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes

fix php8 Deprecated

### Testing Instructions
use php 8 rc4
admin->Contents->Articles

### Actual result BEFORE applying this Pull Request

Screenshot from 2020-11-19 20-05-35

### Expected result AFTER applying this Pull Request

no more Deprecated msg

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Can you do the same here?

https://github.com/joomla/joomla-cms/blob/a5b37ed5b199b7489e9f91b35a47209947d41c02/administrator/components/com_contact/helpers/html/contact.php#L104

**Comment by alikon** [comment]
sure done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a7dd2fe897032c467b9cbfc963d3fb9ef52a137b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31434">issues.joomla.org/tracker/joomla-cms/31434</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on a7dd2fe897032c467b9cbfc963d3fb9ef52a137b<br /><br />Notices are gone after applying fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31434">issues.joomla.org/tracker/joomla-cms/31434</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
