### PR TITLE
[4.0] Make drone happy

### PR DESCRIPTION
**Pull request by brianteeman**
cs changes reported by drone

### CODE REVIEW

**Comment by zero-24** [comment]
Drone has bee rebooted here: http://ci.joomla.org/joomla/joomla-cms/16158

**Comment by zero-24** [comment]
Give it another try ... http://ci.joomla.org/joomla/joomla-cms/16159 :D

**Comment by zero-24** [comment]
@yvesh @puneet0191 can you help here as it seams again something about `Unable to locate element: {"method":"css selector","selector":"h1.page-title"}`

**Comment by brianteeman** [comment]
@zero-24 thats unrelated to this PR which is to fix an error reported here http://ci.joomla.org/joomla/joomla-cms/16153/15

**Comment by rdeutz** [comment]
closed in favor of #24309, thanks Brian

**Comment by brianteeman** [comment]
No problem

**Pull request closed without merging**
