### PR TITLE
[4.0] Remove a "development" error_reporting as obsolete

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Remove a "development" error_reporting from configuration, as obsolete.
Since php 5.4 `error_reporting(-1)` and `error_reporting(E_ALL)` have the same behavior.
See https://www.php.net/manual/en/function.error-reporting 

> Passing in the value -1 will show every possible error, even when new levels and constants are added in future PHP versions. The E_ALL constant also behaves this way as of PHP 5.4.

### Testing Instructions

Code review.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 44da91959a1b270752a57ae0139e485efb5957d7<br /><br />If your site is set to development before you upgrade (or for testing before you apply this PR) then the configuration.php will still say 	
`public $error_reporting = 'development';`
but joomla says system default

image


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28580">issues.joomla.org/tracker/joomla-cms/28580</a>.</sub>

**Comment by Fedik** [comment]
hm yeap, 
a little drawback :smiley:

**Comment by Fedik** [comment]
okay, I made the option disabled, instead of fully removing, for now. It can be removed in future 4.x
screen 2020-04-05 11 44 25 564x72

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 05af9e25ae1b48bd8a61f0dfe6403caf8e606900<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28580">issues.joomla.org/tracker/joomla-cms/28580</a>.</sub>

**Comment by wilsonge** [comment]
Rather than leaving the option in the list override `getData` https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/src/Model/ApplicationModel.php#L81 similar to what we did for the DB driver being used. Remove the option from the form field - leave the handling code in include.php

**Comment by Fedik** [comment]
@wilsonge thanks for a tip, I will look

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 8c6f8eb90a4e4fa796a90295b97e11334fa78f7d<br /><br />Tested in beta1-dev 20200409<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28580">issues.joomla.org/tracker/joomla-cms/28580</a>.</sub>

**Comment by Fedik** [comment]
I have remove the option from the form, and made override for old value in the model.
Please retest.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b34801245aa113f392cdb13b509fb883015ea504<br /><br />Tested in beta1-dev of 20200411<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28580">issues.joomla.org/tracker/joomla-cms/28580</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
