### PR TITLE
[4] To and Do fell out with each other

### PR DESCRIPTION
**Pull request by PhilETaylor**
To and Do had a fight... lets reunite them...

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6e11b4275ba7c55aeef77b2233122b38eb8a33bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36418">issues.joomla.org/tracker/joomla-cms/36418</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6e11b4275ba7c55aeef77b2233122b38eb8a33bf<br /><br />Tested successfully in 4.0.6-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36418">issues.joomla.org/tracker/joomla-cms/36418</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36418">issues.joomla.org/tracker/joomla-cms/36418</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
