### PR TITLE
Wrong administrator module-editing URL

### PR DESCRIPTION
**Pull request by Marc-oO**
#### Testing Instructions

Go here : /administrator/index.php?option=com_config&view=component&component=com_modules
Select editing module : administrator
Go here : /index.php once you are logged in with admin account, edit a module via the frontend link

### CODE REVIEW

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 6ecc942ee5c8e0c11d6e51b59fb7221be109195b<br /><br />Before applying the patch an error is shown trying to edit the module. After applying the patch the module is editable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10559">issues.joomla.org/joomla-cms/10559</a>.</sub>

**Comment by infograf768** [comment]
I can't reproduce the error here.
What url do you get when editing the module in frontend?
Here I get
`index.php?option=com_config&controller=config.display.modules&id=116&return=aHR0cDovL2xvY2FsaG9zdDo4ODg4L3Rlc3R3aW5kb3dzL3RydW5rZ2l0bmV3Lw%3D%3D`

**Comment by infograf768** [comment]
That was when Options default is site.
When Options default is admin, I get:
`administrator/index.php?option=com_modules&view=module&layout=edit&id=116`
and no error

**Comment by roland-d** [comment]
@infograf768 That URL goes to the global configuration screen, that looks wrong as you are supposed to edit the module. It works now because George already merged this. The URL that should be shown is administrator/index.php?option=com_modules&task=module.edit&id=87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10559">issues.joomla.org/joomla-cms/10559</a>.</sub>

**Comment by infograf768** [comment]
oh, me old and tired, did not see it was merged.
I am worrying though that such a PR is merged with only one test...

**Comment by roland-d** [comment]
The URL you get for the frontend is correct though. It is more worrying how this broke, George merged it so it can go into the alpha is my guess.

**Pull request merged**
