### PR TITLE
[4.2] Removing MCrypt class

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
I'm currently checking our codebase for validity against PHP 7.2 and there are a few things which have come up. One of them is that the mcrypt library has been removed in PHP 7.2.0 completely.
https://www.php.net/manual/en/function.mcrypt-get-iv-size.php
This library does not exist for any version of PHP that Joomla supports and thus this class has not been possible to be used with MCrypt instead of OpenSSL. Since that means no one has been using this, we can remove this now without having to wait until 5.0.

### CODE REVIEW

**Review by wilsonge — CHANGES_REQUESTED** [review]
No this allows compatibility of extensions running over multiple joomla versions. This is wrong and the deprecation notice stands as is

**Comment by brianteeman** [comment]
exactly what @wilsonge said and I'm pretty sure this has come up before

**Comment by Hackwar** [comment]
I'm wondering what situation could come up where this would still work. Yes, someone might develop an extension across 3.x and 4.x which uses this, but the moment the user updates to PHP 7.2, it wont work anymore. Also, if they update to Joomla 4, this code also wont work anymore. That person also wont be able to decrypt old encrypted data with this code again after updating to 4.x. If a dev uses the class directly instead of the AES class, I really doubt that person is going to check the support prior. In that case it will still fail, regardless of us having this class here or them running into the problem of the missing mcrypt extension. I would still vote to remove this.

**Comment by HLeithner** [comment]
this is for combat and there is no reason to remove support in the bugfix release.
mcrypt still works with php 8.2.0 https://pecl.php.net/package/mcrypt

**Comment by HLeithner** [comment]
@Hackwar would you please so kind an recreate the PR for 5.0?

**Pull request closed without merging**
