### PR TITLE
Fix for Broken html in Date of Birth field in User Profile Form

### PR DESCRIPTION
**Pull request by AndySDH**
Pull Request for Issue #28883, see that for code details.

### Summary of Changes

This fixes the Date of Birth field in User Profile Edit Form that generates a broken html.

The issue is to due the extra info about the date format being added with broken html around it.

### Previous result

The previous "hacky" HTML creates an extra control-group, and the actual "controls" is outside of it, so two problems for the price of one.

The goal was to put the info language string on a separate line but I don't think that is worth breaking the HTML structure of the form.

### New result

Now the info sits near the label and doesn't break the HTML of the control-group. It does occupy a bit more space (with the default layout) but at least the HTML is correct.

### Testing Instructions

Simply see the HTML of the edit form of a user profile page with a DOB field enabled.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5c4aa86f2b294f49f9c89eb10cccdbb356a656d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28884">issues.joomla.org/tracker/joomla-cms/28884</a>.</sub>

**Comment by infograf768** [comment]
Although the PR works as intended, I am not sure we should merge it, given the readability results.  Screenshots back-end/frontend below.

### BEFORE
Screen Shot 2020-05-01 at 08 10 50
Screen Shot 2020-05-01 at 08 10 38

### AFTER
Screen Shot 2020-05-01 at 08 09 51

Also Frontend date format is right aligned...
Screen Shot 2020-05-01 at 08 09 35

**Comment by AndySDH** [comment]
@infograf768 I understand, but at least with this PR the HTML structure is semantically correct.

The current solution is not acceptable either, with a random empty control-group being output, and a controls that sits outside of it.

image

If you a better idea to fix it, please do so...

Maybe by modifying this file in another way?
https://github.com/joomla/joomla-cms/pull/28884/commits/5c4aa86f2b294f49f9c89eb10cccdbb356a656d6

The ideal scenario is that, instead of outputting the info tooltip inside the control-label, it should be output inside the controls (input), possibly under it, and that would solve the problem, displaying the info in a new line, without breaking the html.

**Comment by jwaisner** [comment]
I agree with @infograf768 . If we can avoid breaking something as the result of the PR we will be better off and that is the goal of the PRs. Fix issues and not create them. 

I wish I understood how to resolve but I do not.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5c4aa86f2b294f49f9c89eb10cccdbb356a656d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28884">issues.joomla.org/tracker/joomla-cms/28884</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28884">issues.joomla.org/tracker/joomla-cms/28884</a>.</sub>

**Comment by infograf768** [comment]
Sorry, but I disagree with this PR.
I prefer readability to a semantically "pure" html.

**Comment by HLeithner** [comment]
Dump question do we need this text at all? Can't we use a placeholder (YYYY-MM-DD) or reduce the text to "Format: YYYY-MM-DD"

Don't we have tooltips for such help?

**Comment by AndySDH** [comment]
@HLeithner  Not a dumb question at all.

This is actually what I've done on my sites too:

image

**Comment by infograf768** [comment]
We could indeed modify the string.
In en-GB
```
; Adapt the following string to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_SPACER_DOB="Format: Year-Month-Day.<br /> ie 0000-00-00"
```
in French
```
; Adapt the following string to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_SPACER_DOB="Format : jour-mois-année.<br />Exemple 05-11-1992"
```
Screen Shot 2020-09-20 at 18 02 44
Screen Shot 2020-09-20 at 18 01 46
Screen Shot 2020-09-20 at 17 59 51

**Comment by HLeithner** [comment]
Din't we have a description text for such things?

**Comment by infograf768** [comment]
If I remember well info was chosen instead of description in order to display a long piece of information. Was ages ago...
I would not change this now for B/C reasons (older lang packs).

code is specifying this aspect:
`// Closing the opening .control-group and .control-label div so we can add our info text on own line`

**Comment by AndySDH** [comment]
So what to do?

**Comment by HLeithner** [comment]
Is this addressed in j4?

**Comment by AndySDH** [comment]
Nope: https://github.com/joomla/joomla-cms/blob/4.1-dev/layouts/plugins/user/profile/fields/dob.php

**Comment by zero-24** [comment]
> So what to do?

please do a new PR against 4.2 changing the place holder. In that case we might should also be able to use the laguage string for that format as provided by the TTs?

**Comment by richard67** [comment]
> please do a new PR against 4.2 changing the place holder. In that case we might should also be able to use the laguage string for that format as provided by the TTs?

@zero-24 Should the issue #28883 be re-opened as long as this hasn't happened yet?

**Comment by AndySDH** [comment]
See PR for 4.2: https://github.com/joomla/joomla-cms/pull/38057

**Pull request closed without merging**
