### PR TITLE
[5.0] Extending Joomla\CMS\Filesystem\Folder from Joomla\Filesystem\Folder

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This PR extends the CMS Folder class from the framework Filesystem Folder class. This removes all duplicate code from the CMS class, using the framework methods where possible. This means that now this class throws exceptions and that all FTP remnants are removed.
Looking at the remaining code, we should consider moving some of this into the framework as well. 
I've changed this a bit agressively, no remaining method stubs with deprecation notices, no hints at the removed FTP code, but I hope that this is still okay.

### Testing Instructions
Everything should work like before... I think this should rather be done by codereview.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
That would be a hard b/c break, we have to move all calls in the CMS to the framework or convert exceptions to errors in this class as long as this class exists.

can't except this for 5.0

**Comment by HLeithner** [comment]
btw. I think documentation is needed for such a change.

**Comment by HLeithner** [comment]
@Hackwar can you get this read till weekend please?

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by Hackwar** [comment]
I doubt this will ever be merged, so I'm closing this.

**Pull request closed without merging**
