### PR TITLE
[4.0] Fix assets table lft and rgt and add missing assets for modules

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This pull request (PR) adds missing assets and corrects wrong `lft` and `rgt` values in the `#__assets` table for new installations.

The following mistakes are corrected:
1. PR #25516 has removed asset (ID 13) for `com_mailto` but hasn't updated `lft` and `rgt`.
2. PR #25570 has added 2 new modules (ID's 107 and 108) which use new asset (ID's 84 and 85), but these assets haven't been added.
3. The same PR has added 3 new modules (ID's 96 to 98) which use the same assets (ID's 41, 42 and 45) as already existing modules (ID's 3,4 and 10), but they should use their own assets.
4. PR #33550 has removed asset (ID 69) for `com_csp` but hasn't updated `lft` and `rgt`.

At least for the last PR it's partly my fault because I had reviewed the SQL parts of it.

But I had planned to check that anyway and provide the necessary fix, what I do now with this PR here.

#### Requirements

Testers need to know and have understood the principles of hierarchical tables using the nested set model as described here:

https://en.wikipedia.org/wiki/Nested_set_model

The `#__assets` table uses an extended model which saves as redundant information also `parent_id` and `level` in addition to `lft` and `rgt` for speeding up certain queries.

My following drawing shows the same model for the `#__usergroups` table and might help to understand this model.

usergroup-tree-calculation

I just see one line missing between the "Editor" and "Publisher", but I think you get it.

The values in the box are the ID's, the number left beside the box are `lft`and right beside the box are `rgt`, and the arrows show how the values are incremented.

If you select data from such a table and sort it by `lft`, you can easily check if there are errors in `lft` and `rgt` values if the table is not too big and has not too many levels in hierarchy. For the `#__assets` table it is still possible for me.

#### Instructions

_**Step 1:**_ Copy the `CREATE TABLE` statement for the `#__assets` table and the `INSERT` statements for this table from the `base.sql` file for your database type from the _current 4.0-dev branch without this PR_ into the SQL command window of an SQL client tool.

E.g. if using MySQL (or MariaDB), copy the code from here into phpMyAdmin's SQL command tab:
https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/base.sql#L8-L103

Don't replace the `#__` table prefix so it doesn't have impact on any existing tables.

Execute the SQL so the table is created and all records are inserted.

_**Step 2:**_ Execute following SQL command to get a list or the assets sorted by `lft`:

```
SELECT `id`,`parent_id`,`lft`,`rgt`,`level`,`name` FROM `#__assets` ORDER BY `lft`;
```

Make sure that all records are shown (checkbox "Show all" in phpMyAdmin).

_**Step 3:**_ Check if the `lft` and `rgt` values are correct with respect to the model described above and the `parent_id` and `level` values.

_**Result:**_ There are errors, details see section "Actual result BEFORE applying this Pull Request" below.

_**Step 4:**_ Export the result of this query (all records) into an SQL file.

_**Step 5:**_ Delete all records from the table.

_**Step 6:**_ Copy the `INSERT` statements for the `#__assets` table from the `base.sql` file _of this PR_ for your database type into the SQL command window of an SQL client tool.

E.g. if using MySQL (or MariaDB), copy the code from here into phpMyAdmin's SQL command tab:
https://github.com/joomla/joomla-cms/blob/a5c03e3657b11abe970877d69097771f6703b69e/installation/sql/mysql/base.sql#L27-L108

Don't replace the `#__` table prefix.

Execute the SQL so that all records are inserted.

_**Step 7:**_ Execute the same SQL command as in step 2 to get a list or the assets sorted by `lft`.

Make sure that all records are shown (checkbox "Show all" in phpMyAdmin).

_**Step 8:**_ Check if the `lft` and `rgt` values are correct with respect to the model described above and the `parent_id` and `level` values.

_**Result:**_ The `lft` and `rgt` values in the `#__assets` are correct.

_**Step 9:**_ Export the result of this query (all records) into an SQL file, using a different file name than in step 4.

_**Step 10:**_ Compare the 2 files exported in steps 4 and 9 using a good comparison tool like e.g. Beyond Compare, the one in TotalCommander, Araxis Merge or if you have an IDE what that ships.

_**Result:**_ The comparison shows only changes in `lft` and `rgt` values and the 5 added records (2 missing and 3 for the wrong duplicate uses) due to PR #25570 .

The ordering of names and the values of `id`, `parent_id` and `level` of previously existing records haven't changed.

_**Step 11:**_ Using the same tool as in the previous step, compare the `INSERT` statements for the `#__assets` table in the 2 files modified by this PR, to make sure they are the same for both database types.

This shall make sure that the changes in the file for the other database type are equal to the changes you have tested in the previous steps for your database type.

_**Result:**_ The `INSERT` statements for the `#__assets` table in the 2 files modified by this PR have the same data.

_**Step 12:**_ Check that the system tests in drone have passed for all database types.

_**Result:**_ The system tests in drone have passed, so this PR hasn't made any SQL syntax errors in the `base.sql` for new installations.

_**Step 13 - optional test for paranoid testers who think I might have broken something:**_ 

Apply the patch of this PR to a clean, current 4.0-dev or latest 4.0 nightly and make a new installation into an empty database.

Check that everything related to assets, i.e. permissions, works at least as well as before.

### Actual result BEFORE applying this Pull Request

- Gap between rgt 46 and lft 49 (asset ID's 12 and 14) caused by PR #25516 .
- Duplicate lft and rgt values 74 and 75 for asset ID's 46 and 67 caused by PR #25570 .
- Gap between rgt 79 and lft 82 (asset ID's 48 and 49) caused by PR #25570 .
- Duplicate lft and rgt values 90 and 91 for asset ID's 53 and 70 caused by PR #25570 .
- Duplicate lft and rgt values 92 and 93 for asset ID's 55 and 71 caused by PR #25570 .
- Gap between rgt 126 and lft 129 (asset ID's 21 and 65).
- Duplicate lft and rgt values 129 and 130 for asset ID's 23 and 65.
- Duplicate lft value 131 for asset ID's 24 and 66 .
- Wrong lft and rgt values 132 and 133 for asset ID 24 due to the previous error.

2021-05-16_j4-asset-table_errors

### Expected result AFTER applying this Pull Request

- The `lft` and `rgt` values in the `#__assets` are correct:
2021-05-16_j4-asset-table_corrected

- The comparison between the old and the corrected data ordered by `lft` shows only changes in `lft` and `rgt` values and the 5 added records (2 missing and 3 for the wrong duplicate uses) due to PR #25570 . The ordering of names, the ID's and the parent ID's haven't changed. See the following comparisons with left side = data with changes from this PR and right side = data without these changes as it is now in 4.0-dev.

2021-05-16_j4-asset-table_diff-1

2021-05-16_j4-asset-table_diff-2

### Additional information

I've checked `lft` and `rgt` values of all other nested tables where we add records in installation SQL scripts, and those were ok.

The same for asset_id values: Beside the wrong duplicate use corrected by this PR here, I have found no other mistakes or missing assets.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
Setting the release blocker label as we should not ship new installs with corrupted data.

**Comment by ceford** [comment]
I went through this as far as Test 10 at which stage I ran out of brains. It all looks good to me. Thanks for excellent explanation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33924">issues.joomla.org/tracker/joomla-cms/33924</a>.</sub>

**Comment by richard67** [comment]
> I went through this as far as Test 10 at which stage I ran out of brains. It all looks good to me. Thanks for excellent explanation.

@ceford So it wasn't a good test because not complete? If so, how can I help to complete it?

**Comment by ceford** [comment]
I can't do Step 12 because I don't know anything about drone. Or does that mean check that the drone check on github has passed? I could probably do Step 13.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33924">issues.joomla.org/tracker/joomla-cms/33924</a>.</sub>

**Comment by richard67** [comment]
@ceford The drone thing means only to check that "All checks have passed" is shown with green check mark at the bottom of the PR on GitHub.

**Comment by richard67** [comment]
If I had SQL syntax error in the base.sql, it would show that some tests have failed.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d07104e699408e5a6f49c019f933d61fcb130e98<br /><br />I have completed as far as and including Step 13 and everything seems to work. I have a nodding acquaintance with Nested Sets and everything I looked at seemed OK. I am content to pass this PR. But, I can't think of a sensible test on a new install that would show an error if something were amiss.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33924">issues.joomla.org/tracker/joomla-cms/33924</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d07104e699408e5a6f49c019f933d61fcb130e98<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33924">issues.joomla.org/tracker/joomla-cms/33924</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33924">issues.joomla.org/tracker/joomla-cms/33924</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks all!

**Pull request merged**
