### PR TITLE
[5.1] Convert mod_syndicate to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the syndicate link site module to service provider.

### Testing Instructions

1. Make sure you have site module mod_syndicate published
2. Make sure you have RSS Feed link enabled in Articles component configuration (Integration tab)
3. You should see module output on articles listing menu items - Category blog, Featured articles...
4. You should not see module output on other menu item types - Single Article, other components...

mod_syndicate

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on fdcea5cb2da8eab4fb0ee85b1e0672b43d209351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42883">issues.joomla.org/tracker/joomla-cms/42883</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on fdcea5cb2da8eab4fb0ee85b1e0672b43d209351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42883">issues.joomla.org/tracker/joomla-cms/42883</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42883">issues.joomla.org/tracker/joomla-cms/42883</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also for testing @fgsw @viocassel

**Pull request merged**
