### PR TITLE
[4.0] com_privacy requests and consents blank state

### PR DESCRIPTION
**Pull request by brianteeman**
See #33264 for instructions but this time for Users: Privacy and not content

This PR requires the code from #33264 to be merged first - specifically the change in libraries/src/MVC/Model/ListModel.php

Note that there is no button to add a new consent

image

image

### CODE REVIEW

**Comment by online-today** [comment]
Those blank state pages are great! It is good to have "no button to add a new consent". 
Would it not make more sense to handle the information request similarly? Does an administrator needs a backend encouragement to start a privacy request for himself?

**Comment by brianteeman** [comment]
@online-today thats beyond the scope of this PR. Please create a new issue

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 01935de8a4d63bb944eb4f9bb416caa34f2b3c61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33272">issues.joomla.org/tracker/joomla-cms/33272</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 01935de8a4d63bb944eb4f9bb416caa34f2b3c61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33272">issues.joomla.org/tracker/joomla-cms/33272</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33272">issues.joomla.org/tracker/joomla-cms/33272</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
