### PR TITLE
[4.1] Layout for 2FA parameter

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
User settings, 1st tab, at the very bottom is the setting for 2FA and user groups.

**Before / After**

Screenshot_1

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c1560c567413ca9972f9a41e83e6ecd11e6992b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37462">issues.joomla.org/tracker/joomla-cms/37462</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c1560c567413ca9972f9a41e83e6ecd11e6992b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37462">issues.joomla.org/tracker/joomla-cms/37462</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37462">issues.joomla.org/tracker/joomla-cms/37462</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
