### PR TITLE
confirm request remove ugly legend

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
from `<legend>` to `<p>`

### Testing Instructions
confirm a privacy request

### Expected result
screenshot from 2018-10-23 10-36-18

### Actual result

screenshot from 2018-10-23 10-35-11

### CODE REVIEW

**Comment by kofaysi** [comment]
I don't see the "Actual result" in J3.9.2 anymore. I see a text formatted compatibly with the text around. I see "Expected result" with no patch applied.
Notice

I agree that no emphasis is needed in this situation (notice on sent e-mail). If emphasis is needed, a Message (of type message or notice) should be used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22774">issues.joomla.org/tracker/joomla-cms/22774</a>.</sub>

**Comment by alikon** [comment]
on staging I still see that 
screenshot from 2019-02-10 08-57-27

**Comment by kofaysi** [comment]
OK, I confirm the stated: The text is larger and inconsistent with other messages.
image
(My personal ignorance and mistake.)

Mind the similarity with the "verification code"
https://github.com/joomla/joomla-cms/blob/fe597ef10fe6d6f0841bebc8aeebaad72d7080f3/language/en-GB/en-GB.com_users.ini#L18
Here is the message with "confirmation token"
https://github.com/joomla/joomla-cms/blob/fe597ef10fe6d6f0841bebc8aeebaad72d7080f3/language/en-GB/en-GB.com_privacy.ini#L12
In principle, it is the same process (request and confirm by a code/token), and should the messages use the same wording and terminology, shouldn't they?

I would also prefer to use message as in "requesting a forgotten username"
image
but of type Notice (unfinished action).

**Comment by kofaysi** [comment]
I have tested this item :white_check_mark: successfully on bf400810e05db8c3cf6fdd1581d5c018968de382<br /><br />J3.9.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22774">issues.joomla.org/tracker/joomla-cms/22774</a>.</sub>

**Comment by Ruud68** [comment]
I have tested this item :white_check_mark: successfully on bf400810e05db8c3cf6fdd1581d5c018968de382<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22774">issues.joomla.org/tracker/joomla-cms/22774</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
This should not be RTC in its current form
A fieldset must have a legend. If you remove it here then we will only have to put it back in J4 where we take a11y seriously.
That does not mean that the wall of text has to remain as the legend.
That also does not mean that the wall of text cannot remain as a legend and be styled as a paragraph.

As it is this PR is just wrong, sorry

**Comment by ghost** [comment]
Status back on Pending. 

I set RTC cause i thought i have missed the 2 successfully tests.

**Pull request closed without merging**
