### PR TITLE
[5.3] Removing LegacyPropertyManagementTrait::setProperties() usage in Core

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The LegacyPropertyManagementTrait is deprecated and we are still using setProperties in some areas. This PR removes the usage of that method from all occurences in our core.

### Testing Instructions
Test registering a user and logging in and view a category view in the frontend. That should trigger all the code. There should be no difference between before and after applying this PR.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
Upmerge for 5.3 missing first?

**Comment by rdeutz** [comment]
Shouldn't the use LegacyPropertyManagementTrait; be removed in the files?

**Comment by Hackwar** [comment]
No, we can't remove those traits, because it would be a b/c break. I'm looking forward to removing the trait from everything in 6.0, but right now we are stuck with it.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
