### PR TITLE
TemplateName fieldtype

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9850.
#### Summary of Changes

See https://github.com/joomla/joomla-cms/issues/9850
#### Testing Instructions

See https://github.com/joomla/joomla-cms/issues/9850

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b7dbd1c14d2fd14846e56cd90d90c84c771d122f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9853">issues.joomla.org/joomla-cms/9853</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on b7dbd1c14d2fd14846e56cd90d90c84c771d122f<br /><br />good catch :smile: 

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9853">issues.joomla.org/joomla-cms/9853</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for the quick fix <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9853">issues.joomla.org/joomla-cms/9853</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman thanks for discovering yet another bug with the "eagle eye" and for the test.
@MATsxm thanks for testing.

**Pull request merged**
