### PR TITLE
[4] use correct object to get message from

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

There is no such method as `$db->getMessage()` - one assumes you are trying to get the exception message?

### Testing Instructions

Code review 

### Actual result BEFORE applying this Pull Request

The code would fatal error if this exception block was ever invoked

### Expected result AFTER applying this Pull Request

The exception would be correctly reported 

### Documentation Changes Required

none

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c9998f35c146a74feb74b1a2b4f38e3bd329041a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37213">issues.joomla.org/tracker/joomla-cms/37213</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c9998f35c146a74feb74b1a2b4f38e3bd329041a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37213">issues.joomla.org/tracker/joomla-cms/37213</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37213">issues.joomla.org/tracker/joomla-cms/37213</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
