### PR TITLE
Allows loading in a custom JS file like we do with CSS in isis theme

### PR DESCRIPTION
**Pull request by tonypartridge**
Function the same way as custom.css file but for JavaScript.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@tonypartridge What is that you might want to include in the template level?
I'll say this is not a good idea

**Comment by tonypartridge** [comment]
I knew you would say that!! For certain scenarios when you say need to move a field around in a component and you can write a little bit of JavaScript to handle this. Instead of a template override it's easier to future proof it with a little JS. 

It's similar to CSS, but allows more tweaks and is easily noticeable that the JS file has been loaded which debugging any issues etc.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on afc3642edc08f5dfe7628fb39e3371f2c6f1e878<br /><br />Seems a logical improvement to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18062">issues.joomla.org/tracker/joomla-cms/18062</a>.</sub>

**Comment by GeraintEdwards** [comment]
I have tested this item :white_check_mark: successfully on 694bc8c36777bd0ab415876ed5f5179c820bf918<br /><br />Tested without custom.js file and no problems

Tested with custom.js file present and it was loaded and executed.

Seems a logical extension of the custom css loading mechanism.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18062">issues.joomla.org/tracker/joomla-cms/18062</a>.</sub>

**Comment by ghost** [comment]
@brianteeman can you please test again?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 694bc8c36777bd0ab415876ed5f5179c820bf918<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18062">issues.joomla.org/tracker/joomla-cms/18062</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by tonypartridge** [comment]
would be nice for 3.8.1 @mbabker 😉

**Comment by mbabker** [comment]
Features don't go into patch releases.

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 694bc8c36777bd0ab415876ed5f5179c820bf918<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18062">issues.joomla.org/tracker/joomla-cms/18062</a>.</sub>

**Comment by tonypartridge** [comment]
@mbabker any suggestions on satisfying drone? Failing on Firefox but I haven't changed any JS.

**Comment by mbabker** [comment]
Drone as a CI platform and JavaScript testing as a whole are not in my areas of expertise.

**Comment by tonypartridge** [comment]
@yvesh any suggestions kind sir...

**Comment by dgrammatiko** [comment]
>  Instead of a template override it's easier to future proof it with a little JS.

@tonypartridge Please no! Template is just a shell that in a perfect world should have 0 lines of HTML, shouldn't impose any CSS files OR javascript files! I perfectly understand that it's easier to add some js there and have it available everywhere but this approach will not fly anymore in 2018. We need to write better code instead of using ideas/shortcuts to write easy code!

**Comment by tonypartridge** [comment]
And that’s all good a well if you are the developer creating the component, I 100% agree.

But not all Joomla! Extensions are perfect. And need some JS, for instance say set some default values. Make some ordering changes because say the component doesn’t do it in the template file and instead do it in the view file.

This is a solution which allows you to refine extensions which are not perfect, or to make UX better for your client adding stuff. The exact same reason as loading in custom css.

**Comment by dgrammatiko** [comment]
@tonypartridge this approach will not fly in J4 because **all** fields that have some js interaction will be (most are already, or there is a PR) custom elements. In that sense your proposed script needs to go after those scripts, but those scripts are easy loaded...

**Comment by tonypartridge** [comment]
Ive not looked into J4, but essentially your saying we can’t load JS without custom elements?

**Comment by dgrammatiko** [comment]
> And that’s all good a well if you are the developer creating the component, I 100% agree.

This makes 0 sense. If you're not a developer, so you don't really understand what the js is doing, for security and many other reasons you **shouldn't** be able to add javascript. Or any kind of code!

**Comment by tonypartridge** [comment]
No you are miss understanding. IF you are not the Developer of the component you wish to make a change too.

**Comment by dgrammatiko** [comment]
@tonypartridge give me a real example that this is not possible right now in joomla with simple layout overrides...

**Comment by tonypartridge** [comment]
I give up.

**Comment by mbabker** [comment]
I get what your intent here is, but this is really something where you need to be doing layout overrides of the affected component screens, not adding a global JS file to the template.  The custom CSS file is quick fixes for personalizing the appearance, it's not changing functionality, whereas a custom JS file changes functionality.  That needs a lot more scrutiny in general.

**Comment by tonypartridge** [comment]
Which is great when the component allows overrides. Not all do, not all follow MVC.

As said I give up, I’ll just continue using custom plugins to inject it where needed.

**Comment by mbabker** [comment]
Ahh, more extensions for my personal blacklist then 😉

**Comment by tonypartridge** [comment]
Ahaha

**Pull request closed without merging**
