### PR TITLE
[4.0][com_messages]: Private message: Tooltip is missing for search filter

### PR DESCRIPTION
**Pull request by sudhir-j-sapkal**
Pull Request for Issue #26897 

### Testing Instructions

1. Login to Joomla admin with one user
2. Go to the private message section.
3. Click on filter option

See the new blank filter

### Expected result
This should display the filter for Messages with option
-- All 
-- Read
-- Unread
-- Trashed

Screenshot from 2019-11-02 12-34-29

### Actual result

It is not showing any options in filter.
68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f61663266313364663439326538383462666530316131626462396537633435342e706e67

### Documentation Changes Required
No

#jpbf19 #codepatch

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 98916705ac1da080a38bd6dfeea44aa2d78981ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 98916705ac1da080a38bd6dfeea44aa2d78981ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by infograf768** [comment]
Hmm, this is weird.
In all xmls the type is set as lowercase, even when the field `protected $type` is camelcase.

Not sure about this PR.

(+ I can't repoduce the issue...)

**Comment by alikon** [comment]
needs more review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by infograf768** [comment]
@sudhir-j-sapka
Please let us know your settings (php, database, etc.)

**Comment by uthorat** [comment]
@infograf768  PFA added the screenshot of system information

System Information - - Administration

**Comment by infograf768** [comment]
I can't reproduce the issue
Screen Shot 2019-11-02 at 10 24 33

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 98916705ac1da080a38bd6dfeea44aa2d78981ec
#pbf19 #test1

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by infograf768** [comment]
Folks, first state if you can reproduce the issue... and add screenshot

**Comment by flavia-b** [comment]
> Folks, first state if you can reproduce the issue... and add screenshot

@infograf768  Yes, I have also faced this issue. And have logged it also: https://github.com/joomla/joomla-cms/issues/26924

dropdwon

**Comment by flavia-b** [comment]
I have tested this item :white_check_mark: successfully on 98916705ac1da080a38bd6dfeea44aa2d78981ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by infograf768** [comment]
Looks like we may have a camelcase issue here.
No issue on Macintosh. May concerns Linux and/or Windows

I am now informing maintainers about that.

**Comment by SharkyKZ** [comment]
This PR is correct. RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26902">issues.joomla.org/tracker/joomla-cms/26902</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! As mentioned on glip - my guess is this is going to be a case sensitivity issue specific to Linux (and that would tie up with the system information in the screenshot)

**Pull request merged**
