### PR TITLE
[5.0] schemaorg remove unused strings

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

remove not used strings

### Testing Instructions

code review (search for usage)

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b78708aa1c2da105167dbc938ec1b4c603ec3ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41402">issues.joomla.org/tracker/joomla-cms/41402</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5b78708aa1c2da105167dbc938ec1b4c603ec3ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41402">issues.joomla.org/tracker/joomla-cms/41402</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41402">issues.joomla.org/tracker/joomla-cms/41402</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
