### PR TITLE
Fixing comments containing editor references

### PR DESCRIPTION
**Pull request by artur-stepien**
Just fixing the comments.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bc75244fa7178925c1ad66fce327a22c64a0dfd2<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43888">issues.joomla.org/tracker/joomla-cms/43888</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on bc75244fa7178925c1ad66fce327a22c64a0dfd2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43888">issues.joomla.org/tracker/joomla-cms/43888</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43888">issues.joomla.org/tracker/joomla-cms/43888</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
