### PR TITLE
[4.0] Namespace JMailHelper

### PR DESCRIPTION
**Pull request by brianteeman**
Fix the last remaining namespace update for JMailHelper

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3cb279e993aad4aa15cea18fa59861d3968e4c50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24119">issues.joomla.org/tracker/joomla-cms/24119</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3cb279e993aad4aa15cea18fa59861d3968e4c50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24119">issues.joomla.org/tracker/joomla-cms/24119</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24119">issues.joomla.org/tracker/joomla-cms/24119</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
