### PR TITLE
improve en-GB.localise.php

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Just reduces if else elseif's

### Testing Instructions

Go to the backend and publush on article, publish 2 articles and publuch mire than two articles

### Expected result

Should still work

### Actual result

Works

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8126ae916fbf1428b6190668bdbdd7b817343cff<br /><br />1 article published.
2 articles published.
3 articles published.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14226">issues.joomla.org/tracker/joomla-cms/14226</a>.</sub>

**Comment by Bakual** [comment]
Code looks fine, however you would have to do the same in the corresponding admin file.

Not sure how useful it is. It's not like the elseif here is overly complex :laughing:

**Comment by infograf768** [comment]
it's ok as it is imho. no use to change.

**Comment by mbabker** [comment]
Actually for English it should change.  By default, the pluralizer already has suffixes for the count, so it can be simplified to this:

```php
return $count > 1 ? array('MORE') : array();
```

(there's no need to add a second suffix to the array for the actual numbers, the logic only needs suffixes for specific pluralization rules and the resulting key ends up as something like `COM_COMPONENT_STRING_MORE`.

**Pull request closed without merging**
