### PR TITLE
[4.2] Improve nonce and strict-dynamic handling within the http header plugin

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #37461

### Summary of Changes

Improve nonce and strict-dynamic handling within the http header plugin:
- once the nonce setting is enabled always add the nonce to the header and dont require an specific tag + bc handling.
- make sure strict-dynamic is the first setting set in the header.

#### First test
- Enable the nonce setting within the plugin
- check the http header
- confirm that the nonce is not added to the header
- add `{nonce}` to script-src
- confirm that the nonce is now at the header
- apply the patch
- confirm the nonce is still at the header
- remove the {nonce} tag
- confirm the nonce is still at the header

#### Seccond test
- Enable the strict-dynamic setting
- set some own script-src settings and end that line with ";"
- confirm that the strict dynamic setting is than showed outside of the script-src
- apply this patch
- confirm that this issue is resolved

### Actual result BEFORE applying this Pull Request

- Nonce only added to the header once the {nonce} tag is aviable
- In some cases the strict-dynamic setting is generated outside of the script-src

### Expected result AFTER applying this Pull Request

- Nonce is added to the header once the setting is enabled
- The {nonce} tag will still be removed to keep B/C
- The strict-dynamic option is now always at the first option once enabled

### Documentation Changes Required

n.a. (as the {nonce} was never documented)

### CODE REVIEW

**Comment by gopitzohlsen** [comment]
With strict dynamic enabled, I get strict dynamic inside the script-src directive and outside the script-src directive.
With strict-dynamic disabled, I get no strict-dynamic inside and outside the script-src directive.

**Comment by richard67** [comment]
> With strict dynamic enabled, I get strict dynamic inside the script-src directive and outside the script-src directive. With strict-dynamic disabled, I get no strict-dynamic inside and outside the script-src directive.

@gopitzohlsen Does that mean you have successfully tested this pull request? If so, could you go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/37940 and use the blue "Test this" button at the top left corner? Just use the button, then select your test result and then submit. Thanks in advance.

**Comment by gopitzohlsen** [comment]
I have tested this item :white_check_mark: successfully on 899007cd677bf189ff57ea1c73df0ca7b26a865b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37940">issues.joomla.org/tracker/joomla-cms/37940</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 899007cd677bf189ff57ea1c73df0ca7b26a865b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37940">issues.joomla.org/tracker/joomla-cms/37940</a>.</sub>

**Comment by laoneo** [comment]
But I think this change should go into 4.2.

**Comment by richard67** [comment]
> But I think this change should go into 4.2.

@laoneo If so, then this should also apply to PR #37942 .

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37940">issues.joomla.org/tracker/joomla-cms/37940</a>.</sub>

**Comment by bembelimen** [comment]
Yes agree, thanks for this changes, but I will rebase to 4.2.

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
