### PR TITLE
[3][com_contact] - contact webpage text

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #35817 .

### Summary of Changes
fixed COM_CONTACT_WEBPAGE management

### Testing Instructions
see  #35817 .

### CODE REVIEW

**Comment by brianteeman** [comment]
Should be "website"

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 36d4452bc67a7d44303e7acabb2a902b7ee0cdd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35835">issues.joomla.org/tracker/joomla-cms/35835</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 36d4452bc67a7d44303e7acabb2a902b7ee0cdd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35835">issues.joomla.org/tracker/joomla-cms/35835</a>.</sub>

**Comment by rjharishabh** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35835">issues.joomla.org/tracker/joomla-cms/35835</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
