### PR TITLE
[4.0] AlreadyPunycodeException exception in email test

### PR DESCRIPTION
**Pull request by conseilgouz**
Don't convert domain to punycode if domain is already a Punycode string

Pull Request for Issue #36301 .

### Testing Instructions
In Global Configuration, Server tab, in mail section, update "from email" parameter so that domain name contains one or more accented character. Click on "Send TestMail".

### Actual result BEFORE applying this Pull Request

Nothing happens : no error, no email sent

### Expected result AFTER applying this Pull Request

a message "The email was sent to ..." is displayed and, if domain exists, you should receive an email.

### CODE REVIEW

**Comment by infograf768** [comment]
Tested with
infograf@avélaccent.fr

Before patch, we get the error
`An error has occurred while fetching the JSON data: HTTP 0 status code.`

After patch, the mail is sent.

Still remains a problem:

**After patch: I can't save such an email as I get a warning**
`The email address you entered is invalid. Please enter another email address.`
I guess the regex may be wrong

**Comment by infograf768** [comment]
Maybe

`if (preg_match('/[^\x20-\x7e]/', $utfString))`

**Comment by PhilETaylor** [comment]
this is the type of thing that is best tested with Unit Tests - can you provide a set of Unit tests as well?

**Comment by HLeithner** [comment]
the regex will always match because it doesn't except . right?

**Comment by HLeithner** [comment]
and it would be easier to test for `xn--`

**Comment by conseilgouz** [comment]
> and it would be easier to test for `xn--`

I was not sure about uniqueness of the prefix.

**Comment by conseilgouz** [comment]
Updated code to ignore AlreadyPunycodeException instead of testing domain value.

**Comment by fontanil** [comment]
The PR works fine for me: test email sent and well received, no more Punycode error. 
Thanks!

**Comment by FrankReisenhofer** [comment]
@conseilgouz : Any idea when this PR will be merged. So the fix would be available for consumers :-)
Thanks for an update.

**Comment by conseilgouz** [comment]
> @conseilgouz : Any idea when this PR will be merged. So the fix would be available for consumers :-) Thanks for an update.

This PR has been marked "closed", and is not in 4.1. 

No idea who did that, but, I think that as nobody tested it, it's normal PR life.....

**Comment by FrankReisenhofer** [comment]
@conseilgouz : Thanks for your quick reply.

At the moment I can confirm that the issue is still reproducible in 4.1.4

So how to proceed? What do you suggest?

Above I saw: [1]. So the PR was tested

[1]

[fontanil](https://github.com/fontanil) commented [on Dec 16, 2021](https://github.com/joomla/joomla-cms/pull/36303#issuecomment-995887489)
The PR works fine for me: test email sent and well received, no more Punycode error.
Thanks!

**Comment by conseilgouz** [comment]
> @conseilgouz : Thanks for your quick reply.
> 
> At the moment I can confirm that the issue is still reproducible in 4.1.4
> 
> So how to proceed? What do you suggest?
> 
> Above I saw: [1]. So the PR was tested
> 
> [1]
> 
> [fontanil](https://github.com/fontanil) commented [on Dec 16, 2021](https://github.com/joomla/joomla-cms/pull/36303#issuecomment-995887489) The PR works fine for me: test email sent and well received, no more Punycode error. Thanks!

A PR has to be "human tested" twice, following the right procedure. 
 [fontanil](https://github.com/fontanil) commented [on Dec 16, 2021](https://github.com/joomla/joomla-cms/pull/36303#issuecomment-995887489) just said it was ok, but did not respect the procedure, so no human test has be recorded for this PR => dead PR

To go RTC, it has to be reopened and tested.

**Comment by FrankReisenhofer** [comment]
@conseilgouz : Thanks for your update. Are you going to reopen the PR? If not: Who can do this?

**Comment by conseilgouz** [comment]
I don't have the rights to do it. I just asked it in issue #36301 . 
Let's hope this will reopen this PR.

**Comment by alikon** [comment]
pr opened as rquested https://github.com/joomla/joomla-cms/issues/36301#issuecomment-1143271603

**Comment by conseilgouz** [comment]
@alikon : what is missing in this PR to go RTC ?

**Comment by alikon** [comment]
2 human succesfull tests
image

**Comment by conseilgouz** [comment]
@FrankReisenhofer  @fontanil : please test this PR and send your result via https://issues.joomla.org/tracker/joomla-cms/36303

**Comment by conseilgouz** [comment]
@alikon : thank you.

Next question : I have "This branch is out-of-date with the base branch" message and no way to fix this. Any idea ?

**Comment by FrankReisenhofer** [comment]
I have tested this item :white_check_mark: successfully on 5d16f6e90bef7d94dece3a3dbf2c77e2deabbf60<br /><br />With the fix the reported issue is no longer occurring. My human manual tests are green<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36303">issues.joomla.org/tracker/joomla-cms/36303</a>.</sub>

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on 5d16f6e90bef7d94dece3a3dbf2c77e2deabbf60<br /><br />Tested after manual changes in the file (Patch tester doesn't change the code) : no more error for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36303">issues.joomla.org/tracker/joomla-cms/36303</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36303">issues.joomla.org/tracker/joomla-cms/36303</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
