### PR TITLE
Deprecate MooTools based helpers

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

These helpers are dependent on MooTools.  Deprecate them.
### Testing Instructions

N/A
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1e9c61d2931fa04e2319c3868bd11112de198ad9<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12268">issues.joomla.org/joomla-cms/12268</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d02f1e877ed4f2b31bb82adace4a6037128e846d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12268">issues.joomla.org/joomla-cms/12268</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on d02f1e877ed4f2b31bb82adace4a6037128e846d<br /><br />:+1: I'm sure @dgt41 will be very happy about this :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12268">issues.joomla.org/joomla-cms/12268</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12268">issues.joomla.org/joomla-cms/12268</a>.</sub>

**Pull request merged**
