### PR TITLE
[4.0] Improve styling of redirect batch update form

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Improve styling of redirect batch update form

### Testing Instructions
Go to System > Redirect
Click `Batch Update Selected URL(s)` button.

### Actual result BEFORE applying this Pull Request
batch-before

### Expected result AFTER applying this Pull Request
batch-after

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 8008117083b2014d048f6415cd92242d86310d33<br /><br />It works as described. But why is this feature using a button below the form instead of being in the Toolbar Actions button - separate issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32180">issues.joomla.org/tracker/joomla-cms/32180</a>.</sub>

**Comment by Quy** [comment]
> But why is this feature using a button below the form instead of being in the Toolbar Actions button - separate issue.

#25489

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8008117083b2014d048f6415cd92242d86310d33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32180">issues.joomla.org/tracker/joomla-cms/32180</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32180">issues.joomla.org/tracker/joomla-cms/32180</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
