### PR TITLE
[4.0] Add missing period

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #31044.

### Summary of Changes
Sentence missing a period.

### Testing Instructions
Code review
or 
Open index.php?option=com_installer&view=install
Tab ´Upload Package File´
Upload a textfile

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7cfcfe18bd9c658111430733c19a5591fe646d2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31243">issues.joomla.org/tracker/joomla-cms/31243</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7cfcfe18bd9c658111430733c19a5591fe646d2b<br /><br />Thanks @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31243">issues.joomla.org/tracker/joomla-cms/31243</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31243">issues.joomla.org/tracker/joomla-cms/31243</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
