### PR TITLE
[4.0] database fix text

### PR DESCRIPTION
**Pull request by brianteeman**
After merge https://github.com/joomla/joomla-cms/commit/05b83c94a29922e92029fd0faed1ae5ba9460d1a update the string to match changes in joomla 4

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3970e3a5741b467717e96c035c9153e44e5e4f68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33506">issues.joomla.org/tracker/joomla-cms/33506</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3970e3a5741b467717e96c035c9153e44e5e4f68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33506">issues.joomla.org/tracker/joomla-cms/33506</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33506">issues.joomla.org/tracker/joomla-cms/33506</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33506">issues.joomla.org/tracker/joomla-cms/33506</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
