### PR TITLE
Fixed bug at core javascript file for backend site

### PR DESCRIPTION
**Pull request by tabaresjc**
- force conversion to int of a value who might be of string type.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please can you provide instructions on how to test this. What is the problem that can be observed before this and what is the expected result afterwards

**Comment by jctt1983** [comment]
hi brianteeman, 

Basically the problem arises when you use a custom button at the backend of joomla

1) Create a "Validate" button in your view with this,
JToolBarHelper::custom('validate', 'arrow-right', 'arrow-right', JText::_('Validate'), true);
$listSelect is True, so it will be checking a standard list. 
2) Create the list in your view, with check-boxes on the side, (code preview)
<?php foreach ($this->items as $i => $item) :?>
    <tr>
        <td class="center"><?php echo $item->is_completed ? JHtml::_('grid.id', $i, $item->id): ''; ?></td>
.
.
.

Ideally Joomla.isChecked, should be checking whether or not, there is at least one item checked in the list, and if there is at least one item checked then it will proceed with the execution of one action in the controller, via form submission.

3) Check just one item on the list, and then un-check the same item, and press the button created in step 1. It will let you execute the action in the controller, even though you don't have any items checked?

So the problem is that the code, is making a sum operation on strings. 

I have Chrome Version 46.0.2490.86 m, also it happens on IE11 and Firefox 42.0.

**Comment by jctt1983** [comment]
Hi @brianteeman 
Is the instruction clear or does it need further clarification?

**Comment by Edu20** [comment]
I have tested this item :white_check_mark: successfully on e1e07a5e49536bd4f1ddf7dbd9ae981f97064bc0<br /><br />I have tested this patch with the [Patch Tester 2.0.1](https://github.com/joomla-extensions/patchtester/releases/tag/2.0.1 "Patch Tester 2.0.1") and was successfully applied.

Tested @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8412">issues.joomla.org/joomla-cms/8412</a>.</sub>

**Comment by mehmetalipamukci** [comment]
I have tested this item :red_circle: unsuccessfully on e1e07a5e49536bd4f1ddf7dbd9ae981f97064bc0<br /><br />tested @icampus
cant reproduce the error, tested with firefox 47.0 and google chrome 52.0.2743.82 (64-bit)
I followed your instructions ,checked an item in a list (in the backend of joomla)then i unchecked the item, and after that, if i click on the created button (named "validate"), i got the Message "Please first make a selection from the list.". So there is no action executed. 
I tested it also wit multiple checks / unchecks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8412">issues.joomla.org/joomla-cms/8412</a>.</sub>

**Comment by wmchris** [comment]
I have tested this item :white_check_mark: successfully on e1e07a5e49536bd4f1ddf7dbd9ae981f97064bc0<br /><br />Couldn't reproduce the problem, but the code review is fine @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8412">issues.joomla.org/joomla-cms/8412</a>.</sub>

**Comment by brianteeman** [comment]
@wmchris without being able to replicate the problem I am reluctant to push this forward for merging. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8412">issues.joomla.org/joomla-cms/8412</a>.</sub>

**Comment by roland-d** [comment]
I am closing this issue because the issue has already been fixed in core. Thanks everybody.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8412">issues.joomla.org/joomla-cms/8412</a>.</sub>

**Pull request closed without merging**
