### PR TITLE
[4.0] Add new Helper folder structure

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
The Categories class still try to load from the old path structure. With this patch it respects the new structure + fallback for the old one.

### CODE REVIEW

**Comment by laoneo** [comment]
The issue is that we are unsure how to deal with helper classes. So the lowercase folders, like the helper ones, are not namespaced. We first need a concept for it.

**Comment by bembelimen** [comment]
So we should ship two helper(s) folder for now? (it affects a GSoC project)

**Comment by laoneo** [comment]
Yes for the time being a `helpers` and a `Helper` folder.

**Comment by laoneo** [comment]
Since #19667, we can get a category trough the ComponentInterface. Will close this one then as it doesn't apply to the new service based approach.

**Pull request closed without merging**
