### PR TITLE
[4.0] Fix paths

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review
Check revised paths exist

### CODE REVIEW

**Comment by richard67** [comment]
Can be merged by review. But I'll wait until drone and appveyor have passed.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2130081bb6df263832c820fe28154b7a248dfd54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31102">issues.joomla.org/tracker/joomla-cms/31102</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2130081bb6df263832c820fe28154b7a248dfd54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31102">issues.joomla.org/tracker/joomla-cms/31102</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31102">issues.joomla.org/tracker/joomla-cms/31102</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
