### PR TITLE
[5.1] Convert mod_frontend to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the frontend link administrator module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_frontend published
2. You should see module output

mod_messages

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 3671f9209ab628df552faae344275e91c5355018<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42853">issues.joomla.org/tracker/joomla-cms/42853</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3671f9209ab628df552faae344275e91c5355018<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42853">issues.joomla.org/tracker/joomla-cms/42853</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42853">issues.joomla.org/tracker/joomla-cms/42853</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also for testing @fgsw @viocassel

**Pull request merged**
