### PR TITLE
Fix: Extension Manager: Install Languages:: Display the 'No matching Results' message , If there search result not exist

### PR DESCRIPTION
**Pull request by zero-24**
see: #5750

-Go to extension manager>Install Languages
-Search an invalid keyword
-Ideally, application should display a message **'No matching Results'**

screen shot 2015-01-16 at 03 35 49screen shot 2015-01-16 at 03 35 54

### CODE REVIEW

**Comment by pe7er** [comment]
In your screenshot "No Matching Results" is in red, and you have the search field.

On my system (3.4dev), after the search for a non existing language, 
the "No Matching Results" is in yellow, 
and the Search Field + Name/Version/Type/Details is missing:
extension manager - install languages

**Comment by pe7er** [comment]
@test
I've tested your new patch and that works great!

**Comment by zero-24** [comment]
sorry @pe7er this is fixed now :smile: 

new_fix

**Comment by zero-24** [comment]
now we don't have the table headings. oops sorry for the german scrennshot here is the english:

new_fix_engl

**Comment by waader** [comment]
@test works!

**Comment by zero-24** [comment]
Thanks @waader can you retest @pe7er ?

**Comment by infograf768** [comment]
This works fine but imho needs correcting formatting.
@zero-24 
I made a patch for that including your changes towards staging.
code:
```
diff --git a/administrator/components/com_installer/views/languages/tmpl/default.php b/administrator/components/com_installer/views/languages/tmpl/default.php
index 9446eb1..d607c0f 100644
--- a/administrator/components/com_installer/views/languages/tmpl/default.php
+++ b/administrator/components/com_installer/views/languages/tmpl/default.php
@@ -30,7 +30,11 @@
 		<div id="j-main-container">
 	<?php endif;?>
-
-		<?php if (count($this->items) || $this->escape($this->state->get('filter.search'))) : ?>
-			<?php echo $this->loadTemplate('filter'); ?>
+	<?php if (count($this->items) || $this->escape($this->state->get('filter.search'))) : ?>
+		<?php echo $this->loadTemplate('filter'); ?>
+		<?php if (empty($this->items)) : ?>
+			<div class="alert alert-no-items">
+				<?php echo JText::_('JGLOBAL_NO_MATCHING_RESULTS'); ?>
+			</div>
+		<?php else : ?>
 			<table class="table table-striped">
 				<thead>
@@ -64,6 +68,5 @@
 				</tfoot>
 				<tbody>
-					<?php foreach ($this->items as $i => $language) :
-				?>
+				<?php foreach ($this->items as $i => $language) : ?>
 					<tr class="row<?php echo $i % 2; ?>">
 						<td class="center">
@@ -94,10 +97,11 @@
 						</td>
 					</tr>
-					<?php endforeach; ?>
+				<?php endforeach; ?>		
 				</tbody>
 			</table>
-		<?php else : ?>
-			<div class="alert"><?php echo JText::_('COM_INSTALLER_MSG_LANGUAGES_NOLANGUAGES'); ?></div>
 		<?php endif; ?>
+	<?php else : ?>
+		<div class="alert"><?php echo JText::_('COM_INSTALLER_MSG_LANGUAGES_NOLANGUAGES'); ?></div>
+	<?php endif; ?>
 
 			<input type="hidden" name="task" value="" />
 
```

**Comment by zero-24** [comment]
should be ok now Thanks @infograf768

**Comment by infograf768** [comment]
Fixed a bit more and merged. Thanks!

**Comment by zero-24** [comment]
Thanks @infograf768 can you remove also this line?
https://github.com/joomla/joomla-cms/commit/e9d179fdc70b7f6ed1a0657a18061c2e30d560d9#diff-2a269d0642e99207e237b2301e44178aR106

**Comment by infograf768** [comment]
>Thanks @infograf768 can you remove also this line?
e9d179f#diff-2a269d0642e99207e237b2301e44178aR106

We usually leave a blank line before `<input type="hidden" etc.` although it is not done in some places.

**Comment by zero-24** [comment]
thanks.

**Pull request closed without merging**
