### PR TITLE
s/externel/external

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/externel/external

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a55ceae34dfe7ce37f63cbc8f13834d298627d95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31933">issues.joomla.org/tracker/joomla-cms/31933</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on a55ceae34dfe7ce37f63cbc8f13834d298627d95<br /><br />Tested successfully in Beta7-dev of 9 January<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31933">issues.joomla.org/tracker/joomla-cms/31933</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31933">issues.joomla.org/tracker/joomla-cms/31933</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
