### PR TITLE
[RFC] Normalization and new metadata for languages (international_name and native_name)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

While dealing with https://github.com/joomla/joomla-cms/pull/11867 it became clear to me the names of the languages extensions/packages need some normallization.

If you install all language packages you will notice there isn't really little normallization of this, which difficults any automation process needed to done in the core and also IMHO is not good for UX.

A language have a lot of xml files, and all of this have names for the language, example for english:
- [Installation Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/installation/language/en-GB/en-GB.xml)
- [Site Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.xml)
- [Site Language Manifest](https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/install.xml)
- [Admin Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.xml)
- [Admin Language Manifest](https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/install.xml)
- [Language Package Manifest](https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/packages/pkg_en-GB.xml)

So this proposal is to start normalizing all language packages (starting with english en-GB here).

Keep in mind this is an effort to normalize and only a proposal, and i could be missign something, any contribution to this discussion is appreciated.
### So what are the changes proposed?

What i propose is the following:
1. All xx-XX.xml and install.xml xml `name` element would get the same value, i.e. the language in english following the language code, in english would be _English (en-GB)_.
2. The installation/site/admin xx-XX.xml `metadata`-> `name` element would get the same value as above.
3. The pkg_xx-XX.xml `name` element would get the same value as above + Language Package, in english would be _English (en-GB) Language Package_.
4. Two new metadata elements would be created in the xx-XX.xml files: `native_name` and `international_name`
   - `international_name`: in english would be _English (United Kingdom)_
   - `native_name`: in english would be _English (United Kingdom)_

So we would have 3 names for each language, some examples:

| Name | International Name | Native Name |
| --- | --- | --- |
| English (en-GB) | English (United Kingdom) | English (United Kingdom) |
| Portuguese (pt-PT) | Portuguese (Portugal) | Português Europeu |
| Portuguese (pt-BR) | Portuguese (Brazilian) | Português do Brasil |
| Arabic (ar-AA) | Arabic (Unitag) | اللغة العربية بالكود الموحد |
| German (de-DE) | German (Germany) | _don't know native german :)_ |
| German (de-CH) | German (Switzerland) | _don't know native german :)_ |
| Sinhala (si-LK) | Sinhala (Sri Lanka) | සිංහල (ශ්‍රී ලංකාව) |
### Testing Instructions

Code review.
### Documentation Changes Required

The documentation on creating language packages would need to be updated.
Translation Coordenation Team would have to agree and transmit this normalization and new metada to language package translation coordenation.

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
> Portuguese (European)

should it be "Portugal" instead of "European" ?

> ( don't know native german :) )

If i remember well it should be "Schweiz"

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment those are  just examples

**Comment by infograf768** [comment]
This would be a new feature.
Some thoughts:

The name used in the install.xml is never used and is indifferent. No absolute need to normalize.

The name used in the Installation xx-XX.xml can include the native translation because it is easier for people speaking only this language to choose it in the dropdown when installing. This is why we have for example:
`<name>Arabic Unitag (العربية الموحدة)</name>` or `<name>Bulgarian (Български)</name>` or `<name>Japanese 日本語 (Japan)</name>` or `<name>Khmer ភាសាខ្មែរ (Cambodia)</name>`
This was decided already some time ago and I see no reason to change this.

I do not understand what you mean with `international_name`. I think adding the pure `native name` in the future is a good idea.

Note: the German is `Deutsch` 😄 
 from
`INSTL_DEFAULTLANGUAGE_NATIVE_LANGUAGE_NAME="Deutsch"`

**Comment by andrepereiradasilva** [comment]
> The name used in the install.xml is never used and is indifferent. No absolute need to normalize.

IMO makes life easier for everyone if normalized.

> The name used in the Installation xx-XX.xml can include the native translation because it is easier for people speaking only this language to choose it in the dropdown when installing. This is why we have for example:

That can easily be done by programming with the metadata i proposed and mainting the consistency of the metadata files across clients (installation/site/admin),

> I do not understand what you mean with international_name. I think adding the pure native name in the future is a good idea.

The international name in a long name without language tags, more easy to understand for regular users.

**Comment by infograf768** [comment]
> That can easily be done by programming with the metadata i proposed and mainting the consistency of the metadata files across clients (installation/site/admin),

So, you would get 2 lines in the dropdown for each language? Otherwise I don't see how...

**Comment by andrepereiradasilva** [comment]
for instance, `$metadata->international_name . ' | ' . $metadata->native_name` or something like this

**Comment by infograf768** [comment]
I am not convinced, except for the native name which can indeed be used in the future.

**Comment by andrepereiradasilva** [comment]
after dealing with the PR to create the content languages to me is clear that this should be normalized

**Comment by infograf768** [comment]
> for instance, $metadata->international_name . ' | ' . $metadata->native_name or something like this

As I said, all languages would now be displayed with 2 lines in Joomla installation: here just changed for en-GB
screen shot 2016-09-05 at 09 04 33

This does not make sense imho.

**Comment by andrepereiradasilva** [comment]
closing as it seems no interrest in this

**Pull request closed without merging**
