### PR TITLE
Fixed casing in class names

### PR DESCRIPTION
**Pull request by ghost**
Not sure whether to touch FOF files...

### CODE REVIEW

**Comment by brianteeman** [comment]
These should be passed upstream directly to fof - we dont touch external
libraries

On 22 July 2015 at 12:01, Peter van Westen <notifications@github.com> wrote:

> Not sure whether to touch FOF files...
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/7519
> Commit Summary
>
>    - Fixed casing in class names
>
> File Changes
>
>    - *M* libraries/fof/controller/controller.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-0> (40)
>    - *M* libraries/fof/dispatcher/dispatcher.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-1> (10)
>    - *M* libraries/fof/download/download.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-2> (6)
>    - *M* libraries/fof/form/field/published.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-3> (2)
>    - *M* libraries/fof/form/field/selectrow.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-4> (2)
>    - *M* libraries/fof/form/field/user.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-5> (2)
>    - *M* libraries/fof/form/form.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-6> (6)
>    - *M* libraries/fof/form/header/field.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-7> (2)
>    - *M* libraries/fof/form/header/ordering.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-8> (4)
>    - *M* libraries/fof/model/behavior/filters.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-9> (2)
>    - *M* libraries/fof/model/model.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-10> (2)
>    - *M* libraries/fof/render/joomla.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-11> (2)
>    - *M* libraries/fof/string/utils.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-12> (4)
>    - *M* libraries/fof/table/table.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-13> (4)
>    - *M* libraries/fof/template/utils.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-14> (16)
>    - *M* libraries/fof/utils/installscript/installscript.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-15> (12)
>    - *M* libraries/fof/utils/ip/ip.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-16> (14)
>    - *M* libraries/fof/utils/update/collection.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-17> (4)
>    - *M* libraries/fof/utils/update/extension.php
>    <https://github.com/joomla/joomla-cms/pull/7519/files#diff-18> (4)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/7519.patch
>    - https://github.com/joomla/joomla-cms/pull/7519.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7519>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nonumber** [comment]
Ok :)

**Comment by nonumber** [comment]
Closing...
@nikosdion

**Comment by nikosdion** [comment]
Class and method names in PHP are case insensitive. I don't see the point of going through all that trouble for doing a code style change in an EOL version of FOF.

**Comment by nonumber** [comment]
Figured as much.

**Pull request closed without merging**
