### PR TITLE
[4.0] Com_installer view=warnings

### PR DESCRIPTION
**Pull request by brianteeman**
The markup on this page is incorrect as there are extra closing divs and a close bootstrap accordion

To test view source (not inspect) of the generated page and validate with https://validator.w3.org/

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9f49b3c2704fc6062ea4b8fea9b53b657874be09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20982">issues.joomla.org/tracker/joomla-cms/20982</a>.</sub>

**Comment by brianteeman** [comment]
grr -   [ConnectionException] Can't connect to Webdriver at http://127.0.0.1:4444/wd/hub. Please make sure that Selenium Server or PhantomJS is running.  

Restarting drone

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 3ea614dbdbbc41734632871addd7442838eb5494<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20982">issues.joomla.org/tracker/joomla-cms/20982</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3ea614dbdbbc41734632871addd7442838eb5494<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20982">issues.joomla.org/tracker/joomla-cms/20982</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20982">issues.joomla.org/tracker/joomla-cms/20982</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
