### PR TITLE
[4.0] A11y changes for admin login

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Changes title to h1. More descriptive title. Removes input placeholders. Make input labels visible. 

### Before
a11y-login1

### After
a11y-login2

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0b2e1bdd8eb3b2eba4b120391a8849534288b332<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17039">issues.joomla.org/tracker/joomla-cms/17039</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix conflicts please :)

**Comment by ciar4n** [comment]
Done!

**Comment by brianteeman** [comment]
1. I dont understand the reasoning behind changing the text - i am not sure I see the need but mayeb yu have some reasoning I dont understand yet
2. Why did you create a new string instead of editing the current one
3. As it is a title then the new string should be capital case

**Comment by armenos** [comment]
I have tested this item :white_check_mark: successfully on 8e66bf11ba6f84b8cc7ebf5a7b6c8722576860be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17039">issues.joomla.org/tracker/joomla-cms/17039</a>.</sub>

**Comment by ciar4n** [comment]
@brianteeman 

1. This is what was suggested by @armenos. His reasoning was to make it clear to the user where he is.

2. The same string was used for the log in button so a separate string was created to allow alternative text.

3. Like this?..

a11y-login3

**Comment by brianteeman** [comment]
1. OK

2. Ah I thought the button used the existing JLOGIN string which is the string used on the front end. I would recommend changing the button to JLOGIN and simply editing the current string - less duplication

3.Sorry I actually meant sentence case not capital case but it looks just as good or even better as capital case

**Comment by C-Lodder** [comment]
I'd even probably say remove the "Login" text about the 2 inputs. The form and button text are already pretty self explanatory.

**Comment by brianteeman** [comment]
@C-Lodder that is there so that the page had a title which is an a11y requirement

**Comment by ciar4n** [comment]
> 2. Ah I thought the button used the existing JLOGIN string which is the string used on the front end. I would recommend changing the button to JLOGIN and simply editing the current string - less duplication

> 3. Sorry I actually meant sentence case not capital case but it looks just as good or even better as capital case

Done

Conflicts fixed.

**Review by C-Lodder — APPROVED** [review]

**Pull request merged**
