### PR TITLE
Media manager: hide the Up button when in base directory (solves issue #5662)

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/5662
After the patch the button will display only when a folder inside the base directory is open.

screen shot 2015-01-13 at 10 25 20

When `sampledata` directory is displayed:

screen shot 2015-01-13 at 10 26 43

### CODE REVIEW

**Comment by uthorat** [comment]
Resolved (Y) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5704">issues.joomla.org/joomla-cms/5704</a>.</sub>

**Comment by brianteeman** [comment]
@ test all good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5704">issues.joomla.org/joomla-cms/5704</a>.</sub>

**Comment by brianteeman** [comment]
Set to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5704">issues.joomla.org/joomla-cms/5704</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks

**Pull request merged**
