### PR TITLE
[4.0] Update composer.json - update pear/cache_lite

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
-         "pear/cache_lite": "1.7.16"
-        "pear/cache_lite": "1.8.0"

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
- Applied patch
- Updated composer `composer update`
- Run `php libraries/vendor/phpunit/phpunit/phpunit tests/unit/suites/libraries/joomla/cache`
- All unit tests passed and no more Cache_Lite deprecated notice

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on f5c9b36b4158258172695d1349e99e5dda3f1dc1<br /><br />as comments above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11884">issues.joomla.org/joomla-cms/11884</a>.</sub>

**Comment by mbabker** [comment]
This can't be merged.  Their repo's `composer.json` manifest is incorrect.  If you look at the [PEAR package manifest](https://github.com/pear/Cache_Lite/blob/master/package.xml), in the changelog for the release they indicate bumping to a PHP 5.4 minimum.  Also see https://github.com/joomla/joomla-cms/issues/10835#issuecomment-230352148

**Comment by andrepereiradasilva** [comment]
> changelog for the release they indicate bumping to a PHP 5.4 minimum

michael what's the impact of that? Unit tests on Cache_Lite don't run in php 5.3 ?

**Comment by mbabker** [comment]
I don't know how Composer handles it, but if our `composer.lock` file were correctly updated with this change and someone on a PHP 5.3 environment tried to run `composer install` they would potentially get a message about being unable to install all dependencies.  If that happened the entire PHP 5.3 build would fail.

**Comment by mbabker** [comment]
If we want to test Cache_Lite 1.8 we'll need a conditional step in the Travis build sequence to update it on-the-fly before running the tests.

**Comment by csthomas** [comment]
IMHO No. This PR only remove notice on php7.

**Comment by andrepereiradasilva** [comment]
i don't know much about composer but isn't it possible to add a separate config for php version?
like (note this is just a wild guess)
```json
  "config": {
    "platform": {
      "php": "5.3.10"
    },
    "platform-dev": {
      "php": "5.4"
    },
```

**Comment by mbabker** [comment]
The `config` key doesn't have a `platform-dev` key, see https://getcomposer.org/doc/06-config.md

**Comment by andrepereiradasilva** [comment]
ok thanks michael for the explaining

**Comment by mbabker** [comment]
After [updating the lock file](https://github.com/mbabker/joomla-cms/commit/050c1fc82d9ab0e8762cfe9f273498e261ec53df) the [PHP 5.3 build](https://travis-ci.org/mbabker/joomla-cms/jobs/157083657) doesn't error out, this is most likely because as I pointed out their `composer.json` manifest is incorrect (it still declares PHP 4.0 as minimum though the PEAR channel declares different).

Still can't say I'm comfortable with that though as the package author has explicitly declared dropping PHP 5.3 support which we are still supporting.

**Comment by csthomas** [comment]
Then for the moment I have to close it. 

I have checked changes in cache_lite code at https://github.com/pear/Cache_Lite
and the is no reason to bump php version to 5.4 for now, may be later author want to add incompatibility changes.

**Comment by csthomas** [comment]
I close it.

**Comment by andrepereiradasilva** [comment]
can't this go for `4.0-dev` (which is php 5.5+) branch now ?

**Comment by csthomas** [comment]
Good point:)

**Comment by csthomas** [comment]
I have rebased my PR to 4.0-dev branch, but it is probably not enough.

**Review by andrepereiradasilva — APPROVED** [review]

**Review by mbabker — CHANGES_REQUESTED** [review]
This also needs the relevant lock file changes.  With at least Composer 1.2 installed:
- Revert your change in composer.json so it doesn't make a fuss about the lock file being out of sync
- `composer install`
- Make the change in composer.json again
- `composer update pear/cache_lite`
- `composer install --no-dev`
- Push the changes

**Comment by csthomas** [comment]
I downloaded composer from https://getcomposer.org/download/
and run as you mentioned but using local version:
```
$ php composer.phar -V
Composer version 1.2.1 2016-09-12 11:27:19
```

If changes in `libraries/vendor/composer/ClassLoader.php ` can not be merged then I can try again with composer 1.2.0.

**Comment by mbabker** [comment]
Looks fine, hadn't realized 1.2.1 released.  The important part was using
at least 1.2.0 since we have the static loader files it generates already
and I didn't want the whole thing to get out of sync along the way.

**Comment by zero-24** [comment]
@mbabker can you approve the changes than? (else we get the red X in the PR) :smile:

**Review by mbabker — APPROVED** [review]

**Comment by mbabker** [comment]
They need to make that possible via the mobile interface...

**Comment by zero-24** [comment]
I agree :+1:

**Pull request merged**
