### PR TITLE
[staging] Correcting small typo from 30496

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30586

### Summary of Changes
Correcting string from `Unicode Alias` to `Unicode Aliases`
Thanks MartijnMaandag 

### Testing Instructions
Can be merged on review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9b73110764b7c258d648f464db9656e1055aea82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30589">issues.joomla.org/tracker/joomla-cms/30589</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9b73110764b7c258d648f464db9656e1055aea82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30589">issues.joomla.org/tracker/joomla-cms/30589</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30589">issues.joomla.org/tracker/joomla-cms/30589</a>.</sub>

**Comment by infograf768** [comment]
@alikon You can merge.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
