### PR TITLE
[4.0][api][com_content] render the image field

### PR DESCRIPTION
**Pull request by alikon**
redo of #29020

### Summary of Changes
 render the image field

### Testing Instructions
edit an article
add an Intro Image and/or Full Article Image
save
 call the api 
`{{base_url}}api/index.php/v1/content/article`

### Expected result
the image field are rendered
Screenshot from 2020-05-10 12-12-47

### Actual result

N/A

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 5dd71c61ff6446e7fa0f92f1cc3c0a0e4a4d235b<br /><br />I looked up your previous testing instructions. The output was a bit of a visual mess. However, I figured out that if I put /11 on the end of the URL I got the data for the article I added the pictures to, with the image data. JSON Lint says it is valid JSON. And going back to without /11, the visual mess is valid JSON too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29630">issues.joomla.org/tracker/joomla-cms/29630</a>.</sub>

**Comment by maikol-ortigueira** [comment]
I have tested this item :white_check_mark: successfully on 5dd71c61ff6446e7fa0f92f1cc3c0a0e4a4d235b<br /><br />I've tested successfully on Joomla 4.0.0-beta2-dev.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29630">issues.joomla.org/tracker/joomla-cms/29630</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29630">issues.joomla.org/tracker/joomla-cms/29630</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
