### PR TITLE
[4.0] refactor Switch which has only single case

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

Refactor of a few `switch` statements which only have a single switch case and therefore are code smell and can be simplified refactored and beautified.

Ok, not beautified,, but they are less complex now

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e18920f5a37bd093b891c39e60ed650f1ab942e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36414">issues.joomla.org/tracker/joomla-cms/36414</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on e18920f5a37bd093b891c39e60ed650f1ab942e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36414">issues.joomla.org/tracker/joomla-cms/36414</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36414">issues.joomla.org/tracker/joomla-cms/36414</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
