### PR TITLE
[4.4] Fix filter for option, format, view and layout in cache and pagination

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Improved version of the PR https://github.com/joomla/joomla-cms/pull/43976 that covers all relevant parameters and reflects the changes in the cache key generation method.

### Testing Instructions
See original PR

### Actual result BEFORE applying this Pull Request
See original PR

### Expected result AFTER applying this Pull Request
See original PR

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 76e607e744c9a8c5ba7c23671574daa06afd52d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43983">issues.joomla.org/tracker/joomla-cms/43983</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 76e607e744c9a8c5ba7c23671574daa06afd52d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43983">issues.joomla.org/tracker/joomla-cms/43983</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43983">issues.joomla.org/tracker/joomla-cms/43983</a>.</sub>

**Comment by MacJoom** [comment]
Thanks for the fix!

**Pull request merged**
