### PR TITLE
[4.0] Fix Text case

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change casing.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e5bd915ec416a0d7130b9706abb1db2e97e4bd4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29973">issues.joomla.org/tracker/joomla-cms/29973</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e5bd915ec416a0d7130b9706abb1db2e97e4bd4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29973">issues.joomla.org/tracker/joomla-cms/29973</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29973">issues.joomla.org/tracker/joomla-cms/29973</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e5bd915ec416a0d7130b9706abb1db2e97e4bd4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29973">issues.joomla.org/tracker/joomla-cms/29973</a>.</sub>

**Pull request merged**
