### PR TITLE
Callback plural suffixes have not a priority in extra cases

### PR DESCRIPTION
**Pull request by pitu-sk**
Pull Request for Issue #20002 .

### Summary of Changes

Change in priority for the language plural potential suffixes

### Testing Instructions

See Steps to reproduce the issue on https://github.com/joomla/joomla-cms/issues/20002.
Each language package should work with plurals as well or better than before.

### Expected result
See Expected result on https://github.com/joomla/joomla-cms/issues/20002
Each language package should work with plurals as well or better than before.

### Actual result

See Actual result on https://github.com/joomla/joomla-cms/issues/20002

### CODE REVIEW

**Comment by infograf768** [comment]
Please read comment here:
https://github.com/joomla/joomla-cms/issues/20002#issuecomment-376430064

**Comment by ghost** [comment]
@pitu-sk any Comment?

**Comment by mbabker** [comment]
Closed based on related issue being closed in favor of no change.

**Comment by davidmocond** [comment]
[https://url4.org/tasnf](https://url4.org/tasnf)
[https://url4.org/yzesu](https://url4.org/yzesu)
[https://url4.org/ddxgt](https://url4.org/ddxgt)
[https://url4.org/lxzjt](https://url4.org/lxzjt)
[https://url4.org/krmul](https://url4.org/krmul)
Hello
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20003">issues.joomla.org/tracker/joomla-cms/20003</a>.</sub>

**Pull request closed without merging**
