### PR TITLE
[4.0] namespace fix

### PR DESCRIPTION
**Pull request by brianteeman**
TBH I dont really know but it looks wrong that these two occurrences begin with a slash when the other instances do not

### CODE REVIEW

**Comment by mbabker** [comment]
use statements generally don't have the leading slash, so this is a good change.  If you're using the fully qualified class name without importing it through a use statement then you would need the slash.

with_use.php
```php
<?php
namespace Joomla\CMS\Session;

use Joomla\CMS\Factory;
use Joomla\Session\SessionInterface;

class Proxy
{
    public function getSession(): SessionInterface
    {
        return Factory::getSession();
    }
}
```

without_use.php
```php
<?php
namespace Joomla\CMS\Session;

use Joomla\Session\SessionInterface;

class Proxy
{
    public function getSession(): SessionInterface
    {
        return \Joomla\CMS\Factory::getSession();
    }
}
```

**Comment by brianteeman** [comment]
Thanks for the lesson and confirming these need to be fixed

**Comment by brianteeman** [comment]
thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
