### PR TITLE
Modal com_contact: improve Select & Edit Contact

### PR DESCRIPTION
**Pull request by cyrez**
Improve modals to select and to edit a contact.
**Note: to be testing on staging.**
#### Summary of Changes
- When Bootstrap modal loads an iframe, BS tooltips with placement top are truncated at the top border of the iframe. (no auto placement in BS2). This PR sets the tooltip placement to bottom to fix this issue.
- Remove inline CSS
- Content is embedded in a container div (using already existing container-popup class for modal.php)
- Add empty lines to improve the readability
- Add viewport dimensions (new <code>3.6.0-dev</code>)
- Contact edit modal is simplified (load edit layout, so no dupplicated code)
- Fix Edit button when current associated contact in data is not the selected contact
- Control if modal, in edit layout
- Add <code>Save</code> (keep modal open), <code>Save & Close</code> and <code>Close</code> button to the footer of the modal
- Fix Edit modal not opening as a modal (missing bootstrap.renderModal for Edit modal)
- Fix consistency of fieldsets <code>$this->ignore_fieldsets</code>, and add missing tabs, and remove dupplicated fieldset metadata (as using now correct edit view inside the modal)
- Consistency of language string <code>COM_CONTACT_EDIT_CONTACT</code> with other components (com_content, com_categories...) : "_Edit Contact_" and not "_Contact_".
#### Testing Instructions (Staging + Multilanguages enabled!)
- Go to Components > Contacts > open a contact, and go to <code>Associations</code> tab to select associated contact to open the modal.
- Verify tooltip placement is bottom, and not truncated
- Verify the modal size now is proportionnal to viewport (modal is 80/100th viewport width, and modal-body is 70/100th viewport height)
- Select an associated contact and save the contact to show edit button
- Open Edit modal and play with it ;-)
- Do the same in a menu item type "Single contact", for Select and Edit contact.

Same rendering as for Categories in PR #10441 (screenshots)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9f26ce12618de538a276cf458f60f61b32e23e2e<br /><br />Nice work yet again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10457">issues.joomla.org/joomla-cms/10457</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just an additional info, this modals also exists in menu item -> single contact (you don't need multilanguage there to test).

**Comment by JoomliC** [comment]
> just an additional info, this modals also exists in menu item -> single contact (you don't need multilanguage there to test).

Yes, you don't need multilanguage there, but it's good to test both places where those modals are used ;-) (as in menu, "clear" is no allowed by field attribute, but is allowed (as optional) in associations)

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 9f26ce12618de538a276cf458f60f61b32e23e2e<br /><br />Installed the latest staging and setup a multilangual website.
All works as described, great!

Will you do the same for the Contacts Categories?
I'll be happy to test that too!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10457">issues.joomla.org/joomla-cms/10457</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> Will you do the same for the Contacts Categories?

That one is already done https://github.com/joomla/joomla-cms/pull/10441

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 9f26ce12618de538a276cf458f60f61b32e23e2e<br /><br />Works great - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10457">issues.joomla.org/joomla-cms/10457</a>.</sub>

**Comment by BurtNL** [comment]
> That one is already done #10441

Confirmed!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10457">issues.joomla.org/joomla-cms/10457</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10457">issues.joomla.org/joomla-cms/10457</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@JoomliC, not for this PR, but did you notice there is another edit modal for creating/editing a module?

That i know of, only in Menus -> Manage (modules button in "Linked Modules")

**Comment by JoomliC** [comment]
> That i know of, only in Menus -> Manage (modules button in "Linked Modules")

There are the same modals as for the assignment modules in menu edition.
And it is in 3.5 the only edit modal opening in a modal. In fact, i based all work done for 3.6.0 on this one ;-)
I'm currently working on newsfeeds modal, and the next one will be modules with only a few improvements, to have consistence with already edit modals done : category and contact.
Edit article was done, but will do too a new PR just to add the Save button there too, and to use same file structure as done here ;-)
So, still in process, but good to point me this location for where module edit is used too! :+1:

**Comment by JoomliC** [comment]
Thanks @andrepereiradasilva @BurtNL @MATsxm for testing 👍 
Just opened a PR for com_newsfeeds modal (with same testing instructions and expected results) ;-)
https://github.com/joomla/joomla-cms/pull/10516

**Pull request merged**
