### PR TITLE
PHP 8.2 Creation of dynamic property

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

PHP 8.2, Creation of dynamic property

### Testing Instructions

Use PHP 8.2, see Creation of dynamic property in FileAdapter

### Actual result BEFORE applying this Pull Request

Deprecation warning

### Expected result AFTER applying this Pull Request

No warning

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by obuisard** [comment]
Hello, I would leave `protected $scriptElement = null;` and match the other adapters

**Comment by Denitz** [comment]
@obuisard Done.

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 7c4a8ea175d07a2846f515de3d93ae6be0cd9511<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41554">issues.joomla.org/tracker/joomla-cms/41554</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7c4a8ea175d07a2846f515de3d93ae6be0cd9511<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41554">issues.joomla.org/tracker/joomla-cms/41554</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41554">issues.joomla.org/tracker/joomla-cms/41554</a>.</sub>

**Comment by obuisard** [comment]
Thank you @Denitz for the PR.

**Pull request merged**
