### PR TITLE
Search filters case sensitive in sql #9242

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9242 .
#### Steps to reproduce the issue

> Go to extensions->install languages
> Search for french
> #### Expected result
> 
> two languages are found
> #### Actual result
> 
> With Mysql you see two languages
> With PGSQL you see zero languages
#### Comment

sql is case sensitive

### CODE REVIEW

**Comment by brianteeman** [comment]
I tried doing that myself but then it fails if someone searches for FRENCH

**Comment by alikon** [comment]
ops ...
should be fixed now tested with `FreNcH`
j35 administration extensions install languages

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f6f8fc129c04574c80305108213c5228573f28b2<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9244">issues.joomla.org/joomla-cms/9244</a>.</sub>

**Comment by brianteeman** [comment]
Oh boy I am embarrassed I didn't think to lowercase both sides

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f6f8fc129c04574c80305108213c5228573f28b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9244">issues.joomla.org/joomla-cms/9244</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9244">issues.joomla.org/joomla-cms/9244</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request merged**
