### PR TITLE
[3.10] Add back com_joomlaupdate default.min.js

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/31200#issuecomment-808710736 .

### Summary of Changes

Add back the minified js which has been removed with #31200 .

I've used https://jscompress.com/ to minify the js.

### Testing Instructions

Make sure that the Joomla Update Component javascript stuff (pre-update checker, quickicon) still works with the minified js.

### Actual result BEFORE applying this Pull Request

No minified js present.

### Expected result AFTER applying this Pull Request

Minified js is present and used, the Joomla Update component works as well as before.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by ceford** [comment]
Just a comment: I have local install created with git import of joomla-cms (files dated 12 March) and in which the missing file is present:

```<script src="/j4test/media/com_joomlaupdate/js/default.min.js?561cadc6377b18079d6e2bda22abbef2" defer></script>```

And it is there. So I doubt deleting and applying the patch will tell me anything. I don't know how my installation came to have a file it should not have.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32883">issues.joomla.org/tracker/joomla-cms/32883</a>.</sub>

**Comment by richard67** [comment]
> I don't know how my installation came to have a file it should not have.

@ceford That's simple: As you wrote, your installation if from March 12. But the PR which has deleted it was merged 3 days ago, and now we have Macrh 29.

**Comment by ceford** [comment]
@richard67  - thanks for the clarification, I was confused by the date on the original issue:  `commented on 22 Oct 2020 •`

**Comment by zero-24** [comment]
Ok will merge here on review after confirming that the minified version is 1:1. Thanks @richard67

**Pull request merged**
