### PR TITLE
Remove non callable array items from field categories

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue #20066 .IF categories are removed from the systems after being allocated to a field the field still has the category id and it is included in the implode.

This PR just removes null/non callable array items from the category display.

### CODE REVIEW

**Comment by Quy** [comment]
I assume this should be fixed in `getAssignedCategoriesTitles`.

**Comment by tonypartridge** [comment]
@Quy I did contemplate that... but wasn’t sure if someone maybe check in for null values to see if categories had been removed. Maybe I was just over thinking it?

**Comment by laoneo** [comment]
Do we have the same problem when a category is unpublished? If it is only the case when a category is deleted, then it would probably be better to solve the root cause and clean up the relation table when a category is deleted. Similar to what we do when an item is deleted [here](https://github.com/joomla/joomla-cms/blob/staging/plugins/system/fields/fields.php#L197).

**Comment by tonypartridge** [comment]
No the issue only occurs when it cannot find the category.

**Comment by brianteeman** [comment]
Shouldnt it work the same as the rest of joomla in that you cannot delete a category that has items that belong to it?

**Comment by tonypartridge** [comment]
Not really since fields might be assigned to a category but no content filled out within them. Preventing deleting categories because a field is set to apply to them would be overkill and could cause a world of confusion imho.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 309894e2bc52c34961f96aa8fbfbb7beb342d589<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by SharkyKZ** [comment]
Use inner join in the query.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 309894e2bc52c34961f96aa8fbfbb7beb342d589<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by Quy** [comment]
@tonypartridge Please see SharkyKZ's comment.

**Comment by Quy** [comment]
@tonypartridge Inner is the way to go.

LEFT
```
array(3) {
  [0]=>
  string(20) "Sample Data-Articles"
  [1]=>
  NULL
  [2]=>
  string(5) "Test2"
}
```

INNER
```
array(2) {
  [0]=>
  string(20) "Sample Data-Articles"
  [1]=>
  string(5) "Test2"
}
```

**Comment by ghost** [comment]
@tonypartridge any Comment?

**Comment by tonypartridge** [comment]
@franz-wohlkoenig sorry I've been mad. I've just made the change on my phone. Can you test please? Thanks!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 73de34dd10cdade7ec874c027e69a8ddbf0404fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by Quy** [comment]
Sorry to give you the wrong info as the last commit works for `Fields` but not under `Articles` when editing an article. 

What you had previously works.

```
Call to undefined method FieldsHelper::displayFieldOnForm()
\administrator\components\com_fields\libraries\fieldsplugin.php:156 

Call stack
# 	Function 	Location
1 	() 	JROOT\administrator\components\com_fields\libraries\fieldsplugin.php:156
2 	FieldsPlugin->onCustomFieldsPrepareDom() 	JROOT\libraries\joomla\event\event.php:70
3 	JEvent->update() 	JROOT\libraries\joomla\event\dispatcher.php:160
4 	JEventDispatcher->trigger() 	JROOT\libraries\src\Application\BaseApplication.php:108
5 	Joomla\CMS\Application\BaseApplication->triggerEvent() 	JROOT\administrator\components\com_fields\helpers\fields.php:460
6 	FieldsHelper::prepareForm() 	JROOT\plugins\system\fields\fields.php:289
7 	PlgSystemFields->onContentPrepareForm() 	JROOT\libraries\joomla\event\event.php:70
8 	JEvent->update() 	JROOT\libraries\joomla\event\dispatcher.php:160
9 	JEventDispatcher->trigger() 	JROOT\libraries\src\MVC\Model\FormModel.php:321
10 	Joomla\CMS\MVC\Model\FormModel->preprocessForm() 	JROOT\administrator\components\com_content\models\article.php:922
11 	ContentModelArticle->preprocessForm() 	JROOT\libraries\src\MVC\Model\FormModel.php:242
12 	Joomla\CMS\MVC\Model\FormModel->loadForm() 	JROOT\administrator\components\com_content\models\article.php:463
13 	ContentModelArticle->getForm() 	JROOT\libraries\src\MVC\View\HtmlView.php:423
14 	Joomla\CMS\MVC\View\HtmlView->get() 	JROOT\administrator\components\com_content\views\article\view.html.php:63
15 	ContentViewArticle->display() 	JROOT\libraries\src\MVC\Controller\BaseController.php:672
16 	Joomla\CMS\MVC\Controller\BaseController->display() 	JROOT\administrator\components\com_content\controller.php:54
17 	ContentController->display() 	JROOT\libraries\src\MVC\Controller\BaseController.php:710
18 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT\administrator\components\com_content\content.php:21
19 	require_once() 	JROOT\libraries\src\Component\ComponentHelper.php:382
20 	Joomla\CMS\Component\ComponentHelper::executeComponent() 	JROOT\libraries\src\Component\ComponentHelper.php:357
21 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT\libraries\src\Application\AdministratorApplication.php:101
22 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT\libraries\src\Application\AdministratorApplication.php:159
23 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT\libraries\src\Application\CMSApplication.php:195
24 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT\administrator\index.php:51 
```

**Comment by tonypartridge** [comment]
no worries @Quy try again now :-)

**Comment by SharkyKZ** [comment]
@tonypartridge the issue described by @Quy is not related to changes in this PR. Revert previous commit please. You need to sync tonypartridge/patch-7 with joomla-cms/staging to solve the issue.

**Comment by Quy** [comment]
@tonypartridge Sorry again. @SharkyKZ is right. Please revert. Thank you!

**Comment by tonypartridge** [comment]
Re-Applied again.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 67629fdbb47830c2d3ecf1a26830e9d368dcd04a<br /><br />I had to manually apply the PR since the branch is out of synch causing PatchTester to patch incorrectly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by tonypartridge** [comment]
Thanks I’ll resync shortly

**Comment by tonypartridge** [comment]
Now re-synced.

**Comment by Quy** [comment]
@coolcat-creations Please test. Thanks.

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 36525a433045b119bc40a1048ced04f2d520711a<br /><br />Works as expected, thanks!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 36525a433045b119bc40a1048ced04f2d520711a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20093">issues.joomla.org/tracker/joomla-cms/20093</a>.</sub>

**Pull request merged**
