### PR TITLE
[5] correct forum link

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #43413 .

### Summary of Changes
correct forum link to 5.x  https://forum.joomla.org/viewforum.php?f=834

### Testing Instructions
Postinstall component administrator/index.php?option=com_postinstall 

### Actual result BEFORE applying this Pull Request
link to 4.x  https://forum.joomla.org/viewforum.php?f=808

### Expected result AFTER applying this Pull Request
correct forum link to 5.x  https://forum.joomla.org/viewforum.php?f=834

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4e4a8cb840107fd58122539277abcf36de0c3431<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43414">issues.joomla.org/tracker/joomla-cms/43414</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4e4a8cb840107fd58122539277abcf36de0c3431<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43414">issues.joomla.org/tracker/joomla-cms/43414</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43414">issues.joomla.org/tracker/joomla-cms/43414</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @alikon and for the tests @Quy @viocassel !

**Pull request merged**
