### PR TITLE
Correcting Back-end Users menu Submenu name.

### PR DESCRIPTION
**Pull request by shubhamnba2009**
#### Steps to reproduce
1. Go to Administartor backend.
2. Go to Users dropdown menu.
3. Select User Note Category.
#### Expected Result

Add New User Note Category.
#### Actual Result

Add New Category.
#### Steps to test
1. Apply the PR 
2. User Note Categories submenu will now be correct.

### CODE REVIEW

**Comment by brianteeman** [comment]
Am I looking in the wrong place as I dont see the problem that this PR is fixing
screen shot 2016-04-07 at 16 31 55

screen shot 2016-04-07 at 16 32 00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by shubhamnba2009** [comment]
After adding PR it looks like this.

image<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by brianteeman** [comment]
OK so I was looking in the wrong place
I dont think this change is necessary. The existing string is clear enough

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 05f4c9b17147894043532dcba87293d16dd13e74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by shubhamnba2009** [comment]
Is this unsuccessful test due to PR not working properly or your diagreeing with PR?

**Comment by brianteeman** [comment]
disagreeing

On 7 April 2016 at 22:51, Shubham Rajput <notifications@github.com> wrote:

> Is this unsuccessful test due to PR not working properly or your
> diagreeing with PR?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9798#issuecomment-207103901>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Its also a fail as it doesnt have any effect in the hathor template <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by shubhamnba2009** [comment]
While checking it on hathor Template i found out that "Templates" and "Language" submenu option is not showing. Can you confirm it @brianteeman

pic<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by brianteeman** [comment]
that is correct - its a bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by brianteeman** [comment]
> While checking it on hathor Template i found out that "Templates" and "Language" submenu option is not showing.

I have done a Pull Request for that  #9823 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by shubhamnba2009** [comment]
Made changes in hathor template if anyone else agree's with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d9d9c6d6dc77a3c069f7c14345a09ec8d0117b6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by zero-24** [comment]
I'm moving that on the `Review List` so we can have a decision here. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your contribution but it has been decided that this is not something that will be changed in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9798">issues.joomla.org/joomla-cms/9798</a>.</sub>

**Pull request closed without merging**
