### PR TITLE
[4.0] Displaying Client and Menus filters in Menu Items manager

### PR DESCRIPTION
**Pull request by infograf768**
The filters are missing in the menu manager

### Before patch
screen shot 2017-08-20 at 10 42 47

### After patch

screen shot 2017-08-20 at 10 38 28

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for this - @C-Lodder and I both looked and couldnt work out the problem

Can you take a look at how the styling is for the client filter in the module and template managers and make this the same. There it is left aligned and it looks from your screenshots that here it is right aligned

**Comment by infograf768** [comment]
Will look at styling later.
For now, we have another issue when displaying menus manager (NOT menu items)
`An error has occurred.

    0 Class 'Joomla\Component\Menus\Administrator\View\Menus\JToolbarHelper' not found `
I am trying to solve that issue now.

**Comment by wilsonge** [comment]
Good work JM! Thankyou!

**Comment by C-Lodder** [comment]
Thanks @infograf768 

Once more slight issue: https://github.com/joomla/joomla-cms/issues/17633

**Pull request merged**
