### PR TITLE
Fix hathor users view broken by #6264

### PR DESCRIPTION
**Pull request by dgrammatiko**
There is a break on functionality with hathor and #6264.

How to test:
select hathor
create a new user note
goto administrator/index.php?option=com_users&view=users
The link `Display 1 note` should bring a modal with the note!

@wilsonge @Kubik-Rubik @Bakual @rdeutz @roland-d

### CODE REVIEW

**Comment by infograf768** [comment]
Test: this now works fine.
PS: are we the only ones to worry about Hathor? :)

**Comment by mbabker** [comment]
What's Hathor? :laughing:

**Comment by infograf768** [comment]
http://en.wikipedia.org/wiki/Hathor
"an Ancient Egyptian goddess who personified the principles of joy, feminine love, and motherhood."

**Comment by dgt41** [comment]
Now that I saw her photo I can say with certainty: There is some resemblance 😜

**Comment by infograf768** [comment]
Look at these beautiful tabs....

hathor

**Comment by losedk** [comment]
Whoops :)

**Comment by wilsonge** [comment]
Nice spot!

**Pull request merged**
