### PR TITLE
[4.1 Scheduled Tasks] Missing constants and demo plugin description

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Lines are missing when creating an item me **in the control panel**. This is a copy-paste from com_scheduler.ini.

Screenshot_1

The demo plugin description had a hardcoded line.

Offtopic. By the way, to the question of the demo plugin. As far as I understand, it was necessary directly during the development of the component. Is he still needed now?

### CODE REVIEW

**Comment by ditsuke** [comment]
I have tested this item :white_check_mark: successfully on 3abe9fe9ba99c00c3955a8e0bfbeeec67a75e150<br /><br />Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36479">issues.joomla.org/tracker/joomla-cms/36479</a>.</sub>

**Comment by ditsuke** [comment]
Thanks!

> Offtopic. By the way, to the question of the demo plugin. As far as I understand, it was necessary directly during the development of the component. Is he still needed now?

Not quite. I expect we'll remove it in the coming weeks.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c31d994e2c6d30bdc44bd3defb9f696b4e750955<br /><br />Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36479">issues.joomla.org/tracker/joomla-cms/36479</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
