### PR TITLE
Updated button margin issue and input button issue on mobile view #33717

### PR DESCRIPTION
**Pull request by deveshprasad**
### Solved 2 issues:

**Issue 1)** Margin issue between the three buttons
Solved the issue using bootstrap margin in all the 3 buttons as individually it will affect the vertical or horizontal alignment.

**Issue 2)** Difference in the height of input and visibility button
Solved by adding a bootstrap bottom margin to 0.

### Actual result BEFORE applying this Pull Request

Check the notification on dashboard on mobile view.
### 1

Go to the main joomla web page and view it on mobile view.
### 2
10 05 2021_20 55 28_REC

### Expected result AFTER applying this Pull Request

1) Solved the margin issue on buttons.

2) The input and button now have the same height.

11 05 2021_21 10 38_REC

### Issue 1 code after solving

`       <button type="button" class="btn btn-primary js-pstats-btn-allow-always m-1"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_SEND_ALWAYS'); ?></button>
	<button type="button" class="btn btn-primary js-pstats-btn-allow-once m-1"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_SEND_NOW'); ?></button>
	<button type="button" class="btn btn-primary js-pstats-btn-allow-never m-1" style="margin:0px"><?php echo Text::_('PLG_SYSTEM_STATS_BTN_NEVER_SEND'); ?></button>
 `

### Issue 2 Code after solving

Modules > mod_login > tmpl > default.php
`<button type="button" class="btn btn-secondary input-password-toggle mb-0">
        <span class="icon-eye icon-fw" aria-hidden="true"></span>
        <span class="visually-hidden"><?php echo Text::_('JSHOWPASSWORD'); ?></span>
</button>`

### CODE REVIEW

**Comment by deveshprasad** [comment]
### Can anyone guide me how to solve these conflicts.

**Comment by richard67** [comment]
@deveshprasad The conflicts are caused by your branch not being up to date with latest 4.0-dev. To me it seems it is very outdated, so the easiest way would be to start again with a new branch based on current 4.0-dev of the CMS repository.

**Comment by richard67** [comment]
@deveshprasad For example you can see that by checking the changed files of this pull request on GitHub. You will see in total 78 changed files with lots of changes not related to what this PR claims to do.

**Comment by Quy** [comment]
Closing in favor of #33899. Thanks.

**Pull request closed without merging**
