### PR TITLE
[4.0] Implementing display of password minimum requirements for frontend registration

### PR DESCRIPTION
**Pull request by infograf768**
Replaces https://github.com/joomla/joomla-cms/pull/30456

### Summary of Changes
Instead of using a tooltip in #30456, this displays the requirements as a description on top of the field.

The new xml attribute is `rules="true"`. This lets developers chose to display or not these.
The code does not change the J installation password string.

### Testing Instructions
**Define Password requirements in Users Options=>Tab Password Options**
No need for npm. Does not change any CSS.

### Actual result BEFORE applying this Pull Request

The password field does not indicate any requirements, forcing the new user to enter stuff and then modify depending on the Errors messages.

### Expected result AFTER applying this Pull Request

Screen Shot 2020-08-25 at 10 23 55

When set to 0, the requirement is not displayed

Screen Shot 2020-08-25 at 10 27 10

Installation tip is not modified

Screen Shot 2020-08-25 at 10 24 52

### Documentation Changes Required
Yes, including the meter which is new in 4.0

### Note
If this is accepted, we can implement in other core places by just adding the description string and the new attribute.

@zero-24

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @infograf768

**Comment by Magnytu2** [comment]
Test ok, the information is there.
Enregistrement

**Comment by Magnytu2** [comment]
I have tested this item :white_check_mark: successfully on e75237e56ed5135465a9814b73070f6d179dc881<br /><br />Test ok, the information is there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30473">issues.joomla.org/tracker/joomla-cms/30473</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on e75237e56ed5135465a9814b73070f6d179dc881<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30473">issues.joomla.org/tracker/joomla-cms/30473</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30473">issues.joomla.org/tracker/joomla-cms/30473</a>.</sub>

**Comment by brianteeman** [comment]
Repeating my objection to the use of the word digits. It should be numbers as in _this password is made up of numbers and letters_
This is the same usage as google, twitter and facebook.

**Comment by infograf768** [comment]
As I said, if you do not like it, this term has to be modified all over the strings, including the existing error ones.
You are free, once this is merged, to propose a PR.

**Comment by brianteeman** [comment]
yay for knowingly merging a string that is wrong so it can be changed later. whoopee for making more work because you are stubborn and insist that you know english better than anyone else

**Comment by brianteeman** [comment]
I have checked this with my client Cambridge University Press and they have checked the usage within the Corpus. https://en.wikipedia.org/wiki/Cambridge_English_Corpus The corpus is a multi billion word  database of the usage of the english language in the world. The corpus is about how language is used and not just about the dictionary meaning

They wrote

> 
> Interesting! I’ve had a look and it looks like ‘number’ is more common – there are only a small number of examples with ‘digit’.
> 
> It’s hard to know for sure, as there are only very few examples of the exact sentences you’ve given so I did a more general search and often ‘number’ is used in sentences like ‘they could steal your credit card number and password’. But, I had a scan through and there are definitely lots of examples of e.g. ‘use a password that contains letters, numbers and special characters’, so I think you’re right to go with your feeling on this.
>

**Comment by infograf768** [comment]
I have contacted the great Mamamouchi ( https://wordhistories.net/2016/10/18/mamamouchi/ ) and informed him about this post.

His reply was quite interesting.

> English is quite a simplistic language. Example: it does not differentiate a street number from a mathematical number, both being composed with digits.
But it looks like the important use of `number` instead of the correct English `digit` in the case at stake is simply due to what many call "American cultural imperialism" imposed by the GAFA (Google, Amazon, Facebook, Apple).

I asked then the great Mamamouchi what was the GAFA's interest in this misuse of the language of Shakespeare. He replied:

> Interesting! I have been wondering too about that. I came to the conclusion that it has to do with their conception of taxes.

"How is that?", I asked.

> Well, as everybody knows, the GAFA try by all means to pay the less taxes possible all over the world. Their "deep state" aim is to pay only one digit of the kind of currency used in each country. Therefore only digits from 0 to 9. Example: 1 Euro per year in the European Union, 2 Dollars in the USA, etc.

> Using the term `number` instead of `digit` is an attempt at making people believe that the GAFA do pay a normal amount of taxes.

"Interesting!", I said. "Then what shall I reply to the person who posted his feeling on this matter?"

> Simple. Let him create a specific proposal to change all instances of "American cultural imperialism" in your software.

"Wow!" I said. "We would also have to change `In the trash` to `In the dustbin`"

**Comment by brianteeman** [comment]
very funny but completely irrelevant.

**Comment by wilsonge** [comment]
I agree with Brian with numbers vs digits (personally I don’t think I’ve ever used the word digit properly other than to describe my fingers and toes :p and that includes during my physics degree 🤪).

**Comment by brianteeman** [comment]
@wilsonge so why did you merge it

**Pull request merged**
