### PR TITLE
Fix Fields editor plugin for com_categories

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Correct context for com_categories to insert the field placeholder.
Currently, the com_fields modal iframe has the link with invalid context:
https://site.com/administrator/index.php?option=com_fields&view=fields&layout=modal&tmpl=component&context=com_categories.category&editor=jform_description
The correct context is:
https://site.com/administrator/index.php?option=com_fields&view=fields&layout=modal&tmpl=component&context=com_content.categories&editor=jform_description

### Testing Instructions

Create category custom fields, edit category.
Try to insert custom field placeholder in category description via editor's 'CMS Content > Fields'

### Actual result BEFORE applying this Pull Request

The fields modal window is empty.

### Expected result AFTER applying this Pull Request

The fields modal window displays category fields.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on d07f6037abaf4c694d6960a5dc569792c6d992cd<br /><br />Fields are shown<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37118">issues.joomla.org/tracker/joomla-cms/37118</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d07f6037abaf4c694d6960a5dc569792c6d992cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37118">issues.joomla.org/tracker/joomla-cms/37118</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37118">issues.joomla.org/tracker/joomla-cms/37118</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
