### PR TITLE
Handle DB errors in categories search plugin

### PR DESCRIPTION
**Pull request by alikon**
added the generic message string "There has been an error" as suggested in #6710

### CODE REVIEW

**Comment by alikon** [comment]
pr6710

**Comment by brianteeman** [comment]
Sorry can you add a full stop at the end

> There has been an error.

On 30 May 2015 at 18:00, Nicola Galgano <notifications@github.com> wrote:

> [image: pr6710]
> <https://cloud.githubusercontent.com/assets/181681/7898100/a0e37dac-06f5-11e5-9bf9-5d5494dc4a5b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7073#issuecomment-107056957>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
You have a binary patch file for some reason :P sorry!

**Comment by alikon** [comment]
no, only my mistake

**Comment by infograf768** [comment]
Please add
`JLIB_DATABASE_GENERIC_SQL_ERROR="There has been an error."`
also in en-GB.lib_joomla.ini both site and admin

as the one in en-GB.ini is a fall back
```
; if there is an error connecting database before initialisation, en-GB.lib_joomla.ini can't be loaded
; we therefore have to load the strings from en-GB.ini
```

**Comment by alikon** [comment]
@infograf768 strings added
we can close #6710 in favour of this one that is more complete

**Comment by Bakual** [comment]
Do we need this string also in administrator/language/en-GB/en-GB.ini ? Or is only the frontend used as fallback?

I wonder if we cna extend the error message a tiny bit. Currently there is absoluetly no value in it. You could as well show nothing because the user can probably figure out himself that there was some error.
I would at leats point him to the database as the suspect. So something like "There was an error related to the database." Better wording needed for sure, but make the error message at least contain some information.
@brianteeman @wilsonge What do you think?

**Comment by wilsonge** [comment]
So don't forget the full message is going to be stored in the logs. This is a message target at the frontend user who wants to see content and doesn't care where the error message comes from

**Comment by Bakual** [comment]
Yeah, I'm aware it's going to be logged.
But to the user seeing this message, it's useless. You could as well use the existing one `JERROR_AN_ERROR_HAS_OCCURRED="An error has occurred."`

I would even suggest to extend the message and include something like the existing one for JLayout (?):
`JERROR_LAYOUT_PLEASE_CONTACT_THE_SYSTEM_ADMINISTRATOR="If difficulties persist, please contact the System Administrator of this site and report the error below."`

So I would even use something like:
`JLIB_DATABASE_GENERIC_SQL_ERROR="There has been an error in the database query. If difficulties persist, please contact the System Administrator of this site and report the error below."`

Don't show the actual error, but give the user (who may be the admin!) a clue what happend.

**Comment by Bakual** [comment]
We could even tell in the message that the actual error was logged. That would be most helpful to the admin.

**Comment by wilsonge** [comment]
I agree having a "report the error below" might help - but then we need to have something significant the backend admin understands it but enough that the frontend user doesn't understand it...

**Comment by Bakual** [comment]
> the frontend user doesn't understand it...

He is allowed to understand. That's not a problem at all as long as no sensible data is shown.

**Comment by alikon** [comment]
if i understand well, @bakual you want a little bit more informative msg
the msg should be something like this
"There has been an error and has been reported on the LOG file."
if i'm correct can someone  correct/review  the new msg ?

**Comment by brianteeman** [comment]
Sorry but there is zero value telling a guest that something has been
logged when they can't see the log.

**Comment by Bakual** [comment]
> Sorry but there is zero value telling a guest that something has been
logged when they can't see the log.

There is even less value in showing "There was an error" when the guest already can see that by looking at the page.
I don't care much. My point is either create a new string which also has some value in the message, or use the already existing `JERROR_AN_ERROR_HAS_OCCURRED="An error has occurred."`.
Personally I would prefer the first option but I can sure also live with the second if you all feel it's to much detail.

**Comment by alikon** [comment]
ok, i'll wait till a final decision will be taken, where all agree...

**Comment by Bakual** [comment]
Just do what @wilsonge says. He is in charge :smile:

**Comment by anibalsanchez** [comment]
Just in case, it works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7073">issues.joomla.org/joomla-cms/7073</a>.</sub>

**Comment by Bakual** [comment]
After having a chat with @wilsonge we settled for `JERROR_AN_ERROR_HAS_OCCURRED="An error has occurred."` for now. We can always use a different string if needed in future.
I merged the plugins PRs, removed the new language string and changed the string to the existing one.

**Comment by alikon** [comment]
thx for take care of these

**Comment by wilsonge** [comment]
No THANKYOU for going through the CMS and finding all these places where we weren't catching exceptions!

**Comment by alikon** [comment]
It's a pleasure to work with you folks, I like costructive critic to mY dirty fixes...

**Pull request closed without merging**
