### PR TITLE
Login URL is wrong (doesn't check layout)

### PR DESCRIPTION
**Pull request by OctavianC**
### Summary of Changes
The Legacy router grabs the incorrect item ID if you've created a logout menu item before creating the login menu; that's because it doesn't verify the layout. This patch fixes that. No idea how to fix the Modern routing though.

### Testing Instructions
- Make sure SEF is enabled
- Make sure you're using `URL Routing` set to `Legacy` in `Users > Manage > Options > Integration`
- The order is important: create a new `Users > Logout` menu item and after that, create a new `Users > Login` menu item.
- Run the following code:
```php
require_once JPATH_SITE.'/components/com_users/helpers/route.php';
var_dump(JRoute::_('index.php?option=com_users&view=login'));
var_dump(UsersHelperRoute::getLoginRoute());
die;
```

### Expected result
```
string(21) "/joomla/index.php/login" string(3) "110" 
```

### Actual result
```
string(21) "/joomla/index.php/logout" string(3) "109" 
```

### CODE REVIEW

**Comment by csthomas** [comment]
IMO there is a little weird configuration after https://github.com/joomla/joomla-cms/pull/7703.
Logout view should have own `view=logout` not `index.php?option=com_users&view=login&layout=logout&task=user.menulogout`

**Comment by brianteeman** [comment]
isnt this related to the change being discussed at #19497

**Comment by OctavianC** [comment]
This was on 3.8.3 so no relation with that issue. This seems to have been added way back in #7703 - it added a new layout for the logout menu item, but the routing didn't take it into account (it assumed if it's `view=login` then it's a login menu item and picks up the Itemid - however, we now have a `view=login&layout=logout` which is a logout menu item - a little bit of discrepancy here, but everything should be fine after this is merged) :)

**Comment by brianteeman** [comment]
OK - thanks for clarifying that

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f655360420ce380c12a215e58a2301869da4a497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19485">issues.joomla.org/tracker/joomla-cms/19485</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f655360420ce380c12a215e58a2301869da4a497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19485">issues.joomla.org/tracker/joomla-cms/19485</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19485">issues.joomla.org/tracker/joomla-cms/19485</a>.</sub>

**Comment by alikon** [comment]
@HLeithner please a final response 

1 year old rtc pr

**Comment by HLeithner** [comment]
thx

**Pull request merged**
