### PR TITLE
Fix to prevent double modification of the module content by chrome style

### PR DESCRIPTION
**Pull request by Fedik**
Alternative fix for #38571 which for for #37147 and #12888

### Summary of Changes
Clone a module before render "chrome" style, to avoid content duplication

### Testing Instructions
Please follow #38571 

### Actual result BEFORE applying this Pull Request
Doubled content

### Expected result AFTER applying this Pull Request
Works fine

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8e742c9b92711899c8bbcf39cfc3b991e21db67a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38582">issues.joomla.org/tracker/joomla-cms/38582</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8e742c9b92711899c8bbcf39cfc3b991e21db67a<br /><br />😎👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38582">issues.joomla.org/tracker/joomla-cms/38582</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38582">issues.joomla.org/tracker/joomla-cms/38582</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you very much

**Pull request merged**
