### PR TITLE
[4.2] Change the db calls back to the getDbo

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #38505.

### Summary of Changes
When an extension is overriding the getDbo function in a model and returning it's own database instance, then the parent classes are not using it anymore as they use getDatabase now. Correct way would be to inject the database instance through the argument in the constructor config or setDbo/setDatabase.

The following code snippet shows the code issue:
```
class MyModel extends ListModel {
  private $mydb;
  public function __construct(..) {
    parent::__construct(...);
    $ẗhis->mydb = MyHelper::getGridDB();
  }
  
  public function getDbo() {
    return $this->mydb;
  }
}
```

Correctly you would write:
```
class MyModel extends ListModel {
  public function __construct(..) {
    parent::__construct(...);
    $this->setDbo(MyHelper::getGridDB());
  }
}
```

To maintain full backwards compatibility, this pr changes back the usage to getDbo.

### Testing Instructions
Use the extension from issue #38505.

### Actual result BEFORE applying this Pull Request
It throws an error.

### Expected result AFTER applying this Pull Request
It works as expected.

### CODE REVIEW

**Comment by roland-d** [comment]
@FoTo50 Can you test this pull request please?

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on f5b8086a3ee3ce479dec5346d5f6349c912a6604<br /><br />After applying the patch the external database connection is being used which it did not use before the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38506">issues.joomla.org/tracker/joomla-cms/38506</a>.</sub>

**Comment by laoneo** [comment]
Even when this article still uses the old code, it shows you how to do it the correct way, by using the setDbo function and not overriding getDbo. It is not safe to rely on the base class, that it uses all the time getDbo when there is even a protected variable $_db in the BaseDatabaseModel class. So I suggest you adapt your code, as this change will be reverted in 5.0.

Anyway, happy that the pr works also for you now and the issue is fixed.

**Comment by roland-d** [comment]
@FoTo50 Great to hear it is working again.

Could you please mark your test on our issue tracker as well? All you need to do is:
1. Go to https://issues.joomla.org/tracker/joomla-cms/38506
2. Click Login with Github
3. After you are logged in you can click the `Test this` blue button
4. Write in the box that it works as expected
5. Click on the `Submit test result`

This will then be marked here as a human test result and we can get this merged. Thank you.

**Comment by FoTo50** [comment]
I have tested this item :white_check_mark: successfully on f5b8086a3ee3ce479dec5346d5f6349c912a6604<br /><br />works as expected, thnx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38506">issues.joomla.org/tracker/joomla-cms/38506</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38506">issues.joomla.org/tracker/joomla-cms/38506</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you very much!

**Pull request merged**
