### PR TITLE
[4.0] Cassiopeia remove mixin - margin

### PR DESCRIPTION
**Pull request by brianteeman**
This mixin was added #27861

But then the only place it was used was removed during #31520

To test

- make a copy of templates\cassiopeia\css\template.css
- apply pr
- regenerate the css (node build/build.js --compile-css)
- compare the copy and the new template.css
- There should be no differences.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5db1660fb12a1711b408a7d0854d56d92bde5637<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32481">issues.joomla.org/tracker/joomla-cms/32481</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on 5db1660fb12a1711b408a7d0854d56d92bde5637<br /><br />The two files are identical.[SS of comparison](https://i.ibb.co/2v0mSn1/2021-02-22-2.png "SS of comparison.")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32481">issues.joomla.org/tracker/joomla-cms/32481</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32481">issues.joomla.org/tracker/joomla-cms/32481</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
