### PR TITLE
[4] Add trailing comma to array to comply with CodeStyle

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4] Add trailing comma to array to comply with CodeStyle

Code Review

### CODE REVIEW

**Comment by brianteeman** [comment]
loving how you suggested I closed my pr that did all this sort of stuff.

**Comment by PhilETaylor** [comment]
I don't think I did? Infact I think I actually gave you the instructions on how to run the commands yourself.￼

There is plenty that needs doing - I was bored sat in the car on the laptop waiting for kid to finish extracurricular activities so had a stab

Sorry if you feel put out because it that

**Comment by PhilETaylor** [comment]
In fact you said 

> I don't have the time but I do want to learn and save myself time in the future. So thats what I am looking at

So I assumed you were not going to follow the instructions I provided. Ah well.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3f32088dedda62ba472e8937021227a6895d606b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33352">issues.joomla.org/tracker/joomla-cms/33352</a>.</sub>

**Comment by PhilETaylor** [comment]
Closing as [no one has the balls](https://github.com/joomla/joomla-cms/pull/33357#issuecomment-827627256) to merge this.

**Pull request closed without merging**
