### PR TITLE
Sidebar navigation hover width

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

In #11723 I changed the background on hover of the menu items on the sidebar. I got it 1px out

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 85a898789472593bce26ed2c8d40af67700765ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11973">issues.joomla.org/joomla-cms/11973</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 85a898789472593bce26ed2c8d40af67700765ad<br /><br />I have tested this successfully
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11973">issues.joomla.org/joomla-cms/11973</a>.</sub>

**Comment by sonalitailored** [comment]
After Patch applied<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11973">issues.joomla.org/joomla-cms/11973</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11973">issues.joomla.org/joomla-cms/11973</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
