### PR TITLE
[4.0] Fix table status icon styling

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #20315 .

### Before
image

### After
image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c3c2333409d2459e04d90e0a5e07081d891645ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20514">issues.joomla.org/tracker/joomla-cms/20514</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c3c2333409d2459e04d90e0a5e07081d891645ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20514">issues.joomla.org/tracker/joomla-cms/20514</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20514">issues.joomla.org/tracker/joomla-cms/20514</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by ciar4n** [comment]
Thank you for the tests!

**Pull request merged**
