### PR TITLE
[4.1] Filter on category state for Tags module (Part: frontend fix)

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #37577 .

### Summary of Changes
Count only items in published categories in the tags module.

### Testing Instructions
* Create a catgory called test and create 4 articles in that category. 
* Add a tag to each article
* Create a module to display popular tags and counts
* Unpublish or Trash the category

Bonus points for testing other items types like Contract, Newfeeds, ....

### Actual result BEFORE applying this Pull Request
Unpublish or Trash a category doesnt't has an effect on the counter in the tag module

### Expected result AFTER applying this Pull Request
Unpublish or Trash a category has an effect on the counter in the tag module

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7934927bec5a39feda7d53b83fa5ef95767549e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37578">issues.joomla.org/tracker/joomla-cms/37578</a>.</sub>

**Comment by richard67** [comment]
@rdeutz It solves only a part of the issue, right? If yes, then it would be good to mention that in the description e.g. by adding a " (part)" at the end of the "Pull Request for Issue #37577".

**Comment by rdeutz** [comment]
@richard67 it solves the problem for the frontend and number are correct after the patch. We can do more ofc but I would create another PR for it.

**Comment by richard67** [comment]
@rdeutz Then I would really suggest to add something like "(part)" to the line at the top of this PR's description which refers to the issue so no JBS member or maintainer thinks they can close the issue because solved by this PR.

**Comment by MacJoom** [comment]
I have not tested this item.<br /><br />also tested newsfeeds with separate tags successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37578">issues.joomla.org/tracker/joomla-cms/37578</a>.</sub>

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 32ef4b774192733668c2c63de572ff0226eef7db<br /><br />also tested newsfeeds with separate tags successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37578">issues.joomla.org/tracker/joomla-cms/37578</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 32ef4b774192733668c2c63de572ff0226eef7db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37578">issues.joomla.org/tracker/joomla-cms/37578</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37578">issues.joomla.org/tracker/joomla-cms/37578</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
