### PR TITLE
It should be 3.5.1-rc2 not 3.5.1-rc22

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Fixes Version number to match version.php @wilsonge I guess it was just a typo on releasing RC2? As it break the database checker on 3.5.1-rc2(2) ;)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c983c165dbc7431c862e5377f1be2749f12fc042<br /><br />this should be merged directly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9674">issues.joomla.org/joomla-cms/9674</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c983c165dbc7431c862e5377f1be2749f12fc042<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9674">issues.joomla.org/joomla-cms/9674</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9674">issues.joomla.org/joomla-cms/9674</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman the RTC label has not added

**Comment by brianteeman** [comment]
RTC again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9674">issues.joomla.org/joomla-cms/9674</a>.</sub>

**Pull request merged**
