### PR TITLE
[4.0] reordering done

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #24008

### Summary of Changes
reordering(i.e. drag and drop enabled as required)

### CODE REVIEW

**Comment by HLeithner** [comment]
I'm not sure what are you trying to do, but in this PR you check the $saveOrder variable for false and allow ordering? That makes no sense $saveOrder has to be true, if it is false the list order is not ordered correctly by the 'ordering' column but if have to!

**Comment by puneeth-chanda** [comment]
Can you say me exactly what to do? I am not able to get the issue correctly.

**Comment by HLeithner** [comment]
@dgrammatiko already explained it:
> So in reality the patch should be quite easy: in the filters script we should take care of the form or the table (wherever the nested attribute is set and make sure that the value reflects the filtered list.
> Plain English: by default most lists can be nested. If you filter on a category or whatever then probably you loose the nested part but the script still behaves as if the list was still nested...
> Should be easy to patch if anyone follows the logic explained above

I didn't looked into it I only checked the PR

**Comment by infograf768** [comment]
this has nothing to do with #24008

**Comment by HLeithner** [comment]
I close this PR because its wrong, please check the original issue again and create a new PR. thx

**Pull request closed without merging**
