### PR TITLE
[4.0] [a11y] Remove uppercase text transformation from menus in the header area of the Cassiopeia template

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This Pull Request (PR) removes `text-transform: uppercase;` from (S)CSS for com_menu items (`.mod-menu li`) in the header section of the Cassiopeia template (`.container-header`), i.e. from menus shown at the top on module positions "Menu" or "Search".

Having all menu items in uppercase letters makes the menu hard to read, e.g. for dyslexic people. As I've just learned it's an accessibility issue.

### Testing Instructions

1. Create a menu with more than 1 item on the first level and at least one item having sub-items on the 2nd level.

2. Create a frontend module for that menu on one of the module positions on module positions "Menu" or "Search" and set `Sub-menu Items` to `Show` in the module settings. 

3. Go to the front page and check the menu link texts.

Result: They are all in uppercase on all levels of the menu.

4. Apply the patch of this PR.

5. Run `npm run build:css` if you have npm, or update to the update package built for this PR if you know how to do that.

6. Go again to the front page or if still there, do a forced reload so no cached css is used, and check again the menu link texts.

Result: They are on all menu levels as defined for that menu item, i.e. not capitalized anymore.

### Actual result BEFORE applying this Pull Request

On all levels of menus shown in the header section, i.e. module positions "Menu" or "Search", the link texts are transformed into uppercase letters:

j4-menu-capitalization_1

### Expected result AFTER applying this Pull Request

On all levels of menus shown in the header section, i.e. module positions "Menu" or "Search", the link texts are **not** transformed into uppercase letters:

j4-menu-capitalization_2

Note: The ugly display of menus with more than one level is not subject of this PR. We should have some nice accessible menu with dropdowns.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
> I don't know if that is not even an accessibility issue.

it is a massive a11y issue. No idea why the a11y team didnt spot that yet

**Comment by richard67** [comment]
Thanks for the feedback, @brianteeman . I was surprised too that I did not find any old issue or PR for that.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d43b0c83b2aeffe200833f8ffae76ad8032d7c3e<br /><br />By code review. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30320">issues.joomla.org/tracker/joomla-cms/30320</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on d43b0c83b2aeffe200833f8ffae76ad8032d7c3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30320">issues.joomla.org/tracker/joomla-cms/30320</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30320">issues.joomla.org/tracker/joomla-cms/30320</a>.</sub>

**Comment by richard67** [comment]
Thanks for testing.

**Pull request merged**
