### PR TITLE
[4.0] Sample Data div

### PR DESCRIPTION
**Pull request by brianteeman**
Not quite sure why it's there but the typography article is wrapped in a div that is not required

### CODE REVIEW

**Comment by wilsonge** [comment]
Merged on review - thanks!

**Comment by brianteeman** [comment]
cool - thanks

**Comment by chmst** [comment]
Maybe you could test this one https://github.com/joomla/joomla-cms/pull/31711? I would be grat to get this merged

**Comment by brianteeman** [comment]
Sorry @chmst I forgot all about that. Will put it on my list for later today

**Pull request merged**
