### PR TITLE
Add Drag and Drop Installation with upload box for #14905

### PR DESCRIPTION
**Pull request by asika32764**
Pull Request for Issue #14905

### Summary of Changes

This is a new PR for #14905 that for easy discuss about the new upload layout.

### Images

Drag and drop install

drag-upload

Select install

select-upload

If browser does not support `FormData`, will fallback to original upload layout. Please someone help me test in IE8.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d66be8414f3198cb19e52944ee97c9024c51d1b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by C-Lodder** [comment]
All the JS and CSS should really go into separate files:

>media/com_installer/js/com_installer.js
>media/com_installer/css/com_installer.css

**Comment by asika32764** [comment]
> All the JS and CSS should really go into separate files.

May I just let the maintenance team to do this since I just follows original code to write it in php.

For me, it is make sense to write this css, js in plugin file because we can close them by closing plugin instead couple them in com_installer.

**Comment by infograf768** [comment]
Agree with @C-Lodder

Also, I suggest that the dropbox be a bit different, something like
```
#dragarea {
    background-color: #fafbfc;
    border: 1px dashed #999;
    padding: 5% 0;
    transition: all 0.2s ease 0s;
    width: 100%;
}
```
It would give something like
 
screen shot 2017-03-27 at 16 17 07

What do you think?

**Comment by asika32764** [comment]
Not bad, I can do the styling change.

**Comment by C-Lodder** [comment]
@asika32764 - In J4, we're trying to move ALL Javascript and CSS to the `media` directory, so that it's all in 1 place. This means debugging and finding code is much easier. So it would be appreciated if you could do this.

The CSS bit is easy. As for the JS, you'll need to get the `$return` value, so simply add a hidden input like so:

```
<input type="hidden" id="installer-return" value="<?php echo $return; ?>">
```

Then get this value in the JS file:

```
var returnUrl = $('#installer-return');
```

**Comment by infograf768** [comment]
hmm, found an issue which is not be related to this PR.

In LTR, we do get OK
screen shot 2017-03-27 at 16 44 10

But in RTL, it is another matter
screen shot 2017-03-27 at 16 45 14

Will create a specific PR

**Comment by asika32764** [comment]
@C-Lodder 

I know, my code is only against 3.7 now.

If I do this staff, I can only move my code since I don't know there may be any break after I moved other code wrote in the past and separated in different plugins. It will be clear that a PR just do one thing.

So I suggest make this thing happened after J4 that we can make sure code works currently in 3.7.

**Comment by C-Lodder** [comment]
Ok leave it for now, I'll move it myself once this is merged and staging has been merged into 4.0-dev

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 5cf5dce673990c31e5d817ee3f03470c56ff378a<br /><br />Tested on:

- Firefox
- IE8
- IE9
- IE10
- IE11
- Edge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5cf5dce673990c31e5d817ee3f03470c56ff378a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by asika32764** [comment]
Moved return value out of JS from @C-Lodder 's suggest. That can be more easy to move code to single js file in the future.

**Comment by asika32764** [comment]
Also moved token out. 

Maybe we can consider use Laravel way to handle CSRF token for Ajax and JS use:  https://laravel.com/docs/5.4/csrf#csrf-x-csrf-token

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 13630daa76180f23ea5f33a50ca36fce82335df6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 13630daa76180f23ea5f33a50ca36fce82335df6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14924">issues.joomla.org/tracker/joomla-cms/14924</a>.</sub>

**Comment by brianteeman** [comment]
yay!!!!

**Comment by infograf768** [comment]
@asika32764 
Please look at https://issues.joomla.org/tracker/joomla-cms/15119

we have no message of success or error when using drag and drop

**Pull request merged**
