### PR TITLE
[user notes] Category is required

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

The user notes new/edit form is missing the required in category field.
### Testing Instructions
1. Code review
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 68a633b1d7a23a08eb403b1362529978ffd2fee9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11947">issues.joomla.org/joomla-cms/11947</a>.</sub>

**Comment by AnishaTailored** [comment]
I have tested this item :white_check_mark: successfully on 68a633b1d7a23a08eb403b1362529978ffd2fee9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11947">issues.joomla.org/joomla-cms/11947</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11947">issues.joomla.org/joomla-cms/11947</a>.</sub>

**Comment by infograf768** [comment]
is it really useful in staging as it is never empty as it defaults to uncategorised (unless that default category has been deleted) ? it looks only  useful when modal_category is used, therefore in 3.7

**Comment by brianteeman** [comment]
it fixes a bug - no reason to wait to fix a bug no matter how signifcant

**Comment by wilsonge** [comment]
Uncategorised is often deleted I think.... I don't see any reason to not accept it tbh

**Comment by andrepereiradasilva** [comment]
thanks

**Pull request merged**
