### PR TITLE
[staging] Category and field date fields do not display jalali date

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Changing text type to calendar in category.xml
When using Persian language, the jalali date is not displayed in the date fields when editing a category.

### Testing Instructions
Install Persian language and switch to Persian in back-end.
Edit a category, Publishing tab.
Look at the Created and Modified date fields.

Patch and test again.

### Before patch
screen shot 2019-02-07 at 08 47 43

### After patch
screen shot 2019-02-07 at 08 46 25

### CODE REVIEW

**Comment by infograf768** [comment]
@alikon @imanickam

**Comment by Bakual** [comment]
Same exists in `administrator/components/com_fields/models/forms/field.xml`. You may want to extend you PR with this file.

It seems to be those fields which are readonly. However I don't see why they should be readonly to start with. other similar fields (eg for an article) are fully editable. Maybe we can do that consistent at the same time?

**Comment by infograf768** [comment]
Good idea. Evidently Modified date should remain readonly, but we could indeed change the created date to be active. 

I found out though that we may have a general bug here. Tested on article:
A Created date can be set in the future, and therefore appear as created AFTER the modified date...
screen shot 2019-02-08 at 09 14 26

**Comment by infograf768** [comment]
I can solve this bug by preventing save and set an error in that case all over core.
Something like (for contacts):
```
		if ($data['modified'] < $data['created'])
		{
			$this->setError(JText::_('JERROR_CREATED'));

			return false;
		}
```
in the save($data) method.
may be a bit different depending on components.

What do you think?

**Comment by Bakual** [comment]
I certainly wouldn't do that in the same PR as it is quite unrelated.

**Comment by mbabker** [comment]
> A Created date can be set in the future, and therefore appear as created AFTER the modified date...

I don't consider this an issue.  If in 4.0 it wants to be redefined that the create date is the time an item is first saved in a site and made readonly then so be it.  Otherwise I quite commonly set my create and publish times to the same thing, which will most often be in the future of the modified date; off hand I don't know where the create time is actually exposed in the frontend but I feel like making it a readonly field in a patch release has bad idea written all over it.

**Comment by infograf768** [comment]
Created Date IS used both in backend and frontend for articles.
Backend:

screen shot 2019-02-09 at 09 04 55

Frontend:

screen shot 2019-02-09 at 09 06 57

**Comment by infograf768** [comment]
In the mean while, I corrected the readonly for Created time and added similar modifications  in field.xml

**Review by Bakual — APPROVED** [review]

**Comment by HLeithner** [comment]
@infograf768 can you plz upgrade the PR

**Comment by infograf768** [comment]
@HLeithner 
As usual I merged again

**Comment by HLeithner** [comment]
thx

**Pull request merged**
