### PR TITLE
FIX #37772 - inlineHelp Toggle Button control

### LINKED ISSUE #37772: [4.1] Missing descriptions for options in settings
### Steps to reproduce the issue
Install [Joomla RC1](https://github.com/joomla/joomla-cms/releases/tag/4.1.3-rc1), note that in all components (for example, in the media manager) the descriptions for the parameters in the component settings have disappeared.

The problem is with [this change](https://github.com/joomla/joomla-cms/pull/37699/files#diff-52b62a7e2124dfb59b290327f0768731196ef8718c757a3d8bae73c8502ed989R40). Remove the change on this line and the descriptions will revert to parameters.

As far as I can tell, this breaks the PR https://github.com/joomla/joomla-cms/pull/37699, so I'm not sure how to properly fix this to keep PR https://github.com/joomla/joomla-cms/pull/37699 working.

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue #37772 .

### Summary of Changes
- Add inlineHelp option to formField
- Control if inlineHelp toggle button is enabled for the current form
- Add 'hide-aware-inline-help d-none' if enabled, as default description class
- ~~You can know add an xml form field attribute "inlinehelp" to use or not the toggling of description field by field (values boolean true/false). Eg. inlinehelp="false" applied on one field, will keep always the description shown even if click on description toggle.~~

UPDATE: see PR #37849 removing the inlinehelp attribute availability for form field xml element.

### Testing Instructions
- Check if descriptions are hidden by default in com_config and com_content options.
- Check if descriptions are shown by default everywhere else (where toggle button is not integrated) : component options, item edition, plugins manager... and in third-party extensions not integrating the toggle button.
- Toggle button works as expected in com_config and com_content

### Actual result BEFORE applying this Pull Request
- Description is hidden on all places where inlinehelp toggle button is not integrated. Almost everywhere in 4.1.3.

### Expected result AFTER applying this Pull Request
- Description is shown if no inlinehelp toggle button.

### Documentation Changes Required
inline help global documentation, and form field attribute inlinehelp.

### CODE REVIEW

**Comment by Valc** [comment]
Hi :)
After test your patch all is working as you explain: the views with 'Options' button that have not an "inlinehelp" are displaying the desc text.

At com_content pressing the "inlinehelp" is also working.

**But at "com_config" >> "Options" with an "inlinehelp" button is failing: pressing it has no effect.**

fail


I know Github has a "tested with success or not" button, but each time a search it i can't found it easy... can you point me to the button, please?

For me is not working at all as is expected due at com_config is failing toggle it.

If i understand right this patch is not focused to  solve the issue about editing modules than also lost the desc text: this one is also an

> Check if descriptions are shown by default everywhere else (where toggle button is not integrated) : component options, **item edition**, plugins manager... and in third-party extensions not integrating the toggle button.

**EDITED**

> So, at modules item edition is not working, and at my third-party extensions site module the same.

Forgot it! at modules edition is also working like a charm! XD
working

Other site module:
working2

When my modules have selected "Hide Legends" only the Desc text is displayed:
working3
And now all is working rightly again.
working4

Regards, Valc.

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 288c69e7e457d7e6bdfa4cbbbe4e1d81263a7852<br /><br />I checked components, modules, plugins. Everything works as stated. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37819">issues.joomla.org/tracker/joomla-cms/37819</a>.</sub>

**Comment by richard67** [comment]
> I know Github has a "tested with success or not" button, but each time a search it i can't found it easy... can you point me to the button, please?

@Valc That button is not on GitHub, it is in our issue tracker, e.g. for this PR on https://issues.joomla.org/tracker/joomla-cms/37819 . Use the blue “Test this” button at the top left corner, then select the right test result and the submit.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b1cb87567e2fc9ac0434808443e948048b1808f1<br /><br />Tested following the test instructions. Com_config, com_content and some other core components and an own plugin work as described. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37819">issues.joomla.org/tracker/joomla-cms/37819</a>.</sub>

**Comment by bembelimen** [comment]
Nice solution, thx

**Comment by cyrez** [comment]
UPDATE: see PR #37849 removing the inlinehelp attribute availability for form field xml element.

**Pull request merged**
