### PR TITLE
[staging] added missing lang files in actionlogs.xml

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - Languages folder not included in actionlogs.xml.

**Summary of Changes**
Added missing `<languages> <language tag="en-GB">en-GB.plg_system_actionlogs.ini</language> <language tag="en-GB">en-GB.plg_system_actionlogs.sys.ini</language> </languages>`
Also, missing in 4.0. If merged in 3.9, then it will later on be merged to 4.0.
https://github.com/joomla/joomla-cms/pull/24424#issuecomment-478324648

### CODE REVIEW

**Comment by alikon** [comment]
~~shouldn't we need the uncompressed/compressed version ?~~

**Comment by bahl24** [comment]
@alikon I couldn't understand what you mean, can you please elaborate?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f3e5476e3199aeac2666cc27e6a92202ec7f5c29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24426">issues.joomla.org/tracker/joomla-cms/24426</a>.</sub>

**Comment by infograf768** [comment]
@alikon 
this is just few lines missing in the xml

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f3e5476e3199aeac2666cc27e6a92202ec7f5c29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24426">issues.joomla.org/tracker/joomla-cms/24426</a>.</sub>

**Comment by alikon** [comment]
@infograf768 , @bahl24,  sorry my previous comment was unrelated to this pr

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
