### PR TITLE
[4.0] NPM package update

### PR DESCRIPTION
**Pull request by brianteeman**
The change of note here is the jump in tinymce version. A separate pull request is coming to add a new feature from that update

+ eslint@7.12.1
+ @babel/plugin-transform-runtime@7.12.1
+ @webcomponents/webcomponentsjs@2.5.0
+ cropperjs@1.5.9
+ @babel/plugin-transform-classes@7.12.1
+ @babel/core@7.12.3
+ bootstrap@4.5.3
+ codemirror@5.58.2
+ @babel/preset-env@7.12.1
+ focus-visible@5.2.0
+ eslint-plugin-import@2.22.1
+ @fortawesome/fontawesome-free@5.15.1
+ selenium-standalone@6.20.1
+ file-loader@6.2.0
+ eslint-plugin-vue@7.1.0
+ postcss@7.0.35
+ karma@5.2.3
+ stylelint@13.7.2
+ tinymce@5.5.1
+ vue@2.6.12
+ vue-loader@15.9.4
+ vue-template-compiler@2.6.12
+ webpack@4.44.2

### CODE REVIEW

**Comment by richard67** [comment]
Composer failing here in Drone due to unrelated reason caused by the testing environment problem, see issue #31281 .

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6379c8938a06c4ec6b8aee59881cafb4e85dd169<br /><br />Applied the patch on a clean 4.0dev branch and run composer install and npm ci. Result:
- The packages to be updated were updated.
- No new warnings or error messages.
- After new installation: The CMS works as well as before.

Code-review: The lock file contains no unresolved dependencies.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31280">issues.joomla.org/tracker/joomla-cms/31280</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6379c8938a06c4ec6b8aee59881cafb4e85dd169<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31280">issues.joomla.org/tracker/joomla-cms/31280</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31280">issues.joomla.org/tracker/joomla-cms/31280</a>.</sub>

**Comment by richard67** [comment]
I've restored previous test results because only change after tests was a clean branch update.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
