### PR TITLE
Fix calendar field min/max year

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #40481 .

### Summary of Changes

Restoring feature, that was broken in 4.x (#34870)
https://docs.joomla.org/Calendar_form_field_type
min/max year is relative numbers.

### Testing Instructions
Apply patch, run `npm install`
Please follow #40481
Or create a custom calendar field, somewhere in XML:

```xml
<field type="calendar" name="cal1" label="Calendar test" minyear="-1" maxyear="1"/>
```
And check which year is available to select.

### Actual result BEFORE applying this Pull Request
It display year 1

### Expected result AFTER applying this Pull Request
It allows to select years:  2022, 2023, 2024

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2d69e007f35455a89f203efa3204242fe5eb6cda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40580">issues.joomla.org/tracker/joomla-cms/40580</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 2d69e007f35455a89f203efa3204242fe5eb6cda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40580">issues.joomla.org/tracker/joomla-cms/40580</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40580">issues.joomla.org/tracker/joomla-cms/40580</a>.</sub>

**Comment by obuisard** [comment]
Thank you Fedir @Fedik for the PR!

**Pull request merged**
