### PR TITLE
Fix #8621. Regression: Select Module. Shows always frontend modules

### LINKED ISSUE #8621: 3.5.0 Beta. New module after administrator selection shows frontend modules
I' ve installed staging of today.

After installation I didn't open any list views (components).
Just configuration. 
Installed patch tester, and a small backend module. 
Afterwards I opened modules manager. 
Selected "Administrator" in Client filter field: 
Page reload and Administrator modules are displayed.
Clicked "New".
The page for selecting modules shows frontend modules.
Clicked Cancel. Filter still shows "Administrator".

Tried a lot (changing filters, client, ordering) but always frontend modules after New.
Firefox and Chrome.

### PR DESCRIPTION
**Pull request by ghost**
Issue: https://github.com/joomla/joomla-cms/issues/8621

Test:
Install staging (3.5.0 Beta).

Go to modules manager (backend).
Select "Administrator" in Client filter field:
Page reload and administrator modules are displayed.
Click "New".
The page for selecting modules shows frontend modules.

Apply patch.
Test again.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on db1605f764837113f7d735ebebde0226c743a4dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8626">issues.joomla.org/joomla-cms/8626</a>.</sub>

**Comment by infograf768** [comment]
Added Regression to title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8626">issues.joomla.org/joomla-cms/8626</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on db1605f764837113f7d735ebebde0226c743a4dd<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8626">issues.joomla.org/joomla-cms/8626</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8626">issues.joomla.org/joomla-cms/8626</a>.</sub>

**Pull request merged**
