### PR TITLE
Revert "Use icon exit  for close buttons"

### PR DESCRIPTION
**Pull request by obuisard**
Reverts joomla/joomla-cms#40167

Should be something that would be handled in 5.0 rather than in a bug fix release.

### CODE REVIEW

**Comment by brianteeman** [comment]
yes I see that and I agree with @Fedik 

However Allon is saying that the label has changed https://github.com/joomla/joomla-cms/pull/40167#issuecomment-1536318359

**Comment by wilsonge** [comment]
The label hasn’t changed. @chmst tracked that down in the maintainers group earlier. Allon was wrong about that

**Comment by brianteeman** [comment]
it was only 30 minutes ago that he said that :(

**Comment by obuisard** [comment]
The fix from Fedir @Fedik is a good solution but looking at it more closely, brought up to the surface some inconsistencies we have in the toolbars (for instance, we have a 'close' button instead of 'cancel' when creating a new category).

**Comment by laoneo** [comment]
Perhaps I did change the branches too fast and the labels are still the same. Then it is my fault. But the other statement from me is still valid. This should not go into a patch release.

**Comment by Fedik** [comment]
That probably result of George PR #39537,
there for existing item: 

```php
ToolbarHelper::cancel('category.cancel', 'JTOOLBAR_CLOSE');
// changed to
$toolbar->cancel('category.cancel');
```

Probably need 
```php
$toolbar->cancel('category.cancel', 'JTOOLBAR_CLOSE');
```
At https://github.com/joomla/joomla-cms/blob/524f58f0ba48195cf1abe0ebf859f1ecf5b35e4f/administrator/components/com_categories/src/View/Category/HtmlView.php#L235

**Comment by obuisard** [comment]
> @obuisard this will fix the problem:
> 
> ```
> return $this->standardButton('cancel', $text, $task)->icon('icon-exit');
> ```
> 
> This will keep old tookbar-cancell ID but use new icon, from the linked PR.

So we don't forget @Fedik suggested adding:
`->buttonClass('btn btn-primary')`
so that icons turn blue.

**Comment by sdwjoomla** [comment]
Reverting the close icon change makes sense given that the replacement of the icon enhances the look and is not fixing a broken/non-loading icon. Additionally, further discussion is needed to be more consistent in the actions, using Close vs Cancel.
image

**Comment by brianteeman** [comment]
> Additionally, further discussion is needed to be more consistent in the actions, using Close vs Cancel.

What discussion is needed - this has been the behaviour for a very very long time without issue. The only issue was regarding the icon clashing with the delete icon

**Comment by sdwjoomla** [comment]
Thanks Olivier

**Pull request merged**
