### PR TITLE
s/string/array

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Docblock correction: s/string/array

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on d94614d3f20d7d066c9904144d5b3963fee2bfd1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29800">issues.joomla.org/tracker/joomla-cms/29800</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d94614d3f20d7d066c9904144d5b3963fee2bfd1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29800">issues.joomla.org/tracker/joomla-cms/29800</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29800">issues.joomla.org/tracker/joomla-cms/29800</a>.</sub>

**Comment by zero-24** [comment]
Merging

**Pull request merged**
