### PR TITLE
System info fatal error on symbolic linked folders

### PR DESCRIPTION
**Pull request by n3t**
Pull Request for Issue #13552.

### Summary of Changes
isDot check first, before isDir

### Testing Instructions
Follow the Issue tracker https://issues.joomla.org/tracker/joomla-cms/13552

### CODE REVIEW

**Comment by zero-24** [comment]
@n3t it looks like you committed to the wrong branch?

**Comment by n3t** [comment]
:-/ yeah, I am not so much familier with github, bit lost now...

**Comment by n3t** [comment]
Ok, now it should be as before, sorry for complications...

**Comment by franz-wohlkoenig** [comment]
@n3t close this Issue?

**Comment by zero-24** [comment]
@franz-wohlkoenig no this should be still a valid fix for the issue.

**Comment by n3t** [comment]
@franz-wohlkoenig even commits are bit masched up, it still solves the initial issue, and the PR is back in its initial state.

**Comment by henkrijneveld** [comment]
I have tested this item :white_check_mark: successfully on 277b7aeb17dd244a6f85811434c651c6aed92be4<br /><br />open basedir message disappears after applying patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13553">issues.joomla.org/tracker/joomla-cms/13553</a>.</sub>

**Comment by ghost** [comment]
I couldn't reproduce the issue on Linux-4.17.8-1 with PHP7

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13553">issues.joomla.org/tracker/joomla-cms/13553</a>.</sub>

**Comment by Schmidie64** [comment]
I have tested this item :red_circle: unsuccessfully on e1d08ad38ad46a9990452d799824589a7d1e9d2c<br /><br />I followed the instructions step by step but i coundn't reproduce the issue. I think it can be close.

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13553">issues.joomla.org/tracker/joomla-cms/13553</a>.</sub>

**Comment by roland-d** [comment]
@n3t Can you please followup on the unsuccessful tests? Thank you.

**Comment by csthomas** [comment]
IMO negative tests were not carried out with full understanding of the problem.

Example.
Php has access to `/var/images`, then we want to list directory like 
```php
$folder = new DirectoryIterator(JPATH_ROOT . '/images');  // In real, it will be `/var/images`
```
and now we have a list of elements:
```php
.
..
image1.png
image2.png
```

when we are in line `..`, php want to get access to `/var/images/..` which is `/var` and then we get the error because php has access only to `/var/images` not `/var`. 

This PR is valid. I did code review.

**Comment by roland-d** [comment]
@csthomas Thank you for your input. @Schmidie64 @niklas-deworetzki-thm Please review your testing and check again.

**Comment by ghost** [comment]
@csthomas oh, now I see the problem here. I'm sorry, I misunderstood at first, that he had problems with accessing the symlinked directory. 
But as far as I understand now, the problem is not the symlink. PHP tries to check isDir on `..` . This folder is not in baseDir. So PHP fails and shows an error. And this error is 1. unnecessary and 2. shows critical information about the system path to the user.

I'm testing it now, knowing the real issue. Thank you for clarifying it.

@icampus

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e1d08ad38ad46a9990452d799824589a7d1e9d2c<br /><br />Tested this ✅ successfully as specified by @csthomas <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13553">issues.joomla.org/tracker/joomla-cms/13553</a>.</sub>

**Comment by ghost** [comment]
@henkrijneveld can you please retest?

**Comment by n3t** [comment]
@csthomas yes your explanation is exact. problem is not symlink itself, but isdir check to dots folders, which don't need to be accessible...

**Comment by roland-d** [comment]
@Schmidie64 Can you please test this again?

**Comment by HLeithner** [comment]
Thx @n3t, good things need sometime sometimes...

**Pull request merged**
