### PR TITLE
[4.1][bugfix] Fix the preview/thumb images for children

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36235 .

### Summary of Changes

Follow the inheritance correctly

### Testing Instructions

See the issue #36235

### Documentation Changes Required

No bugfix

@brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2d8312247948b562016dfc864c3d51f8d41499ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36236">issues.joomla.org/tracker/joomla-cms/36236</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 2d8312247948b562016dfc864c3d51f8d41499ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36236">issues.joomla.org/tracker/joomla-cms/36236</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36236">issues.joomla.org/tracker/joomla-cms/36236</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
