### PR TITLE
s/favorite/favourite

### PR DESCRIPTION
**Pull request by PhilETaylor**
en GB!

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 505154c77d1487faaa2ba5c5b5e4534bdc190761<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38479">issues.joomla.org/tracker/joomla-cms/38479</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 505154c77d1487faaa2ba5c5b5e4534bdc190761<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38479">issues.joomla.org/tracker/joomla-cms/38479</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38479">issues.joomla.org/tracker/joomla-cms/38479</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Pull request closed without merging**
