### PR TITLE
Replacements for deprecated AbstractRegistryFormat Class implementations

### PR DESCRIPTION
**Pull request by frankmayer**
Replacements for deprecated AbstractRegistryFormat Class implementations

### CODE REVIEW

**Comment by mbabker** [comment]
The libraries/vendor dir shouldn't be changed unless you run "composer update".

Also, this change is a B/C break (it breaks class inheritance).  Which is why it's only done on the Registry package'a 2.0 branch.  So it'll be fixed in 4.0 but for 3.x it's fine as is.

**Comment by frankmayer** [comment]
Argh.. the vendor thing... yes... then this can be used for 4.0 then.

**Comment by andrepereiradasilva** [comment]
@frankmayer please close the PR then

**Comment by frankmayer** [comment]
Closing this for the 3.x line. If there is need, will make another one to the appropriate channel.

**Pull request closed without merging**
