### PR TITLE
Fix language keys which trigger wrong plural detection in translation tools

### PR DESCRIPTION
**Pull request by Bakual**
### Issue

While testing Crowdin we found that we have seven language keys in core which are named in a way that triggers plural detection in Crowdin (and probably also other translation tools).
This is because they end with eg "_1". Keys ending directly with a number only are usually used for plural forms.
### Solution

This PR deprecates the existing language keys and use new key names for those strings.
According to our rules we don't remove strings within a major series to provide backward compatibility.
### Testing

The affected strings are used as options in "Purchase Type" in com_banners component settings, the client and banner forms and the Search Tools in the client manager.
After applying the PR, you should see the english values instead of the translated ones because your language pack doesn't contain a translation (yet) and Joomla will fall back to the english one.

The remaining two are the "Version" parameter in the reCaptcha plugin. However since I doubt that the values are actually different in your language (1.0 likely will be 1.0 as well) you will likely see no difference.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 882ea81a1a541ba062e9103f63e4e90323619646<br /><br />Works great. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8300">issues.joomla.org/joomla-cms/8300</a>.</sub>

**Comment by infograf768** [comment]
No problem here on review.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 882ea81a1a541ba062e9103f63e4e90323619646<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8300">issues.joomla.org/joomla-cms/8300</a>.</sub>

**Comment by infograf768** [comment]
RTC as 2 tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8300">issues.joomla.org/joomla-cms/8300</a>.</sub>

**Pull request merged**
