### PR TITLE
[4.1] Mail Templates [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Correctly change the cells in the title column to use th scope=row as used elsewhere

codereview should be fine

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0824a924af57a374362bfd6ebaee50b043abb1a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36622">issues.joomla.org/tracker/joomla-cms/36622</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0824a924af57a374362bfd6ebaee50b043abb1a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36622">issues.joomla.org/tracker/joomla-cms/36622</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36622">issues.joomla.org/tracker/joomla-cms/36622</a>.</sub>

**Comment by brianteeman** [comment]
could someone restart drone here please

**Comment by richard67** [comment]
> could someone restart drone here please

@brianteeman I did, but it will fail again because currently they are all failing in the 4.0-dev branch.

**Comment by brianteeman** [comment]
are the tests still failing?

**Comment by brianteeman** [comment]
rebased to 4.1

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks for merging

**Pull request merged**
