### PR TITLE
[CS] CodeStyle on joomla.sql

### PR DESCRIPTION
**Pull request by shur**
If you export a live site's database and compare it to the core joomla.sql you'll see lots of minor differences. This hardens the database examination and shows that joomla.sql contains many code style mistakes.

This is the second portion of CS changes.
First portion: #4298

### CODE REVIEW

**Comment by shur** [comment]
To simplify I will divide this PR into several PRs.
After all small PRs will be processed, I'll close this big PR.

**Comment by roland-d** [comment]
@shur The first portion PR has been merged. What is the status on this one? Are you going to make smaller ones or can we test this one?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4311">issues.joomla.org/joomla-cms/4311</a>.</sub>

**Comment by shur** [comment]
@roland-d test this one #7735

**Comment by zero-24** [comment]
As this is replaced by #7735 I'm closing here.

**Pull request closed without merging**
