### PR TITLE
[4.0] Don't pass $displayData to module layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Currently module dispatcher passes both the extracted data from the array and the array from which the data was extracted. We don't need the latter.

### Testing Instructions

Inspect `mod_quickicon` in backend and some other modules.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fbeffe805afde091685e1875d65cfbf759d1a690<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26249">issues.joomla.org/tracker/joomla-cms/26249</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fbeffe805afde091685e1875d65cfbf759d1a690<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26249">issues.joomla.org/tracker/joomla-cms/26249</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26249">issues.joomla.org/tracker/joomla-cms/26249</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
