### PR TITLE
[4.0] Rename some component helper classes

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Renames `Joomla\Component\Finder\Administrator\Helper\FinderHelperLanguage` and `Joomla\Component\Users\Administrator\Helper\UsersHelperDebug` to follow the same convention as other helper classes.

### Testing Instructions

1. Run Smart Search indexer, search using Smart Search in frontend.
2. View Users and User Groups, click the icon in Permissions column.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8985f5d680e8d9839c9288721dc09645a63b1c43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27528">issues.joomla.org/tracker/joomla-cms/27528</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8985f5d680e8d9839c9288721dc09645a63b1c43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27528">issues.joomla.org/tracker/joomla-cms/27528</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27528">issues.joomla.org/tracker/joomla-cms/27528</a>.</sub>

**Comment by richard67** [comment]
Drone mysql system test failing seems not to be related to this PR.

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
