### PR TITLE
[4.0] short and sweet fix

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35018 .

### Summary of Changes
- Fixes the empty textarea (but not the other 2 points from the initial issue)
- update short and sweet to 1.0.4
- remove unneeded `document.addEventListener('DOMContentLoaded', ...` as the script is loaded with `defer` attribute

### Testing Instructions
- Create an article
- Edit the database row and increase the value of the description to more than 160 characters
- Try to edit the article in the backend, the description **shouldn't** be empty

Probably a Release Blocker

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for the upstream PR to address the empty area

_when you save the article with the character count greater than the maximum allowed it will be saved truncated_

**Comment by dgrammatiko** [comment]
> when you save the article with the character count greater than the maximum allowed it will be saved truncated

I think by editing the db directly we can replicate the issue (eg j3 article with more than 160chrs in the description). But after editing the article in the backend then the description **will** be <= 160chrs

**Comment by brianteeman** [comment]
Tested this PR and it doesnt work :(

image

image

**Comment by dgrammatiko** [comment]
> Tested this PR and it doesnt work :(

Delete the media folder and run again `npm install`

**Comment by brianteeman** [comment]
weird. I thought that `npm i` already did the media folder bit

anyway works now

**Comment by brianteeman** [comment]
ah - see the problem (i think)

Before this PR the folder media/vendor/short-and-sweet/js had three files .js, .min.js, .min,.js.gz

The npm i script only copies files to the media folder it doesnt remove existing files

**Comment by dgrammatiko** [comment]
> The npm i script only copies files to the media folder it doesnt remove existing files

Maybe the build tools should remove any existing `.gz` files, will do a PR later

**Comment by brianteeman** [comment]
or just remove everything?

**Comment by dgrammatiko** [comment]
> or just remove everything?

I didn't do that on purpose, eg someone tries to test a PR but also has installed some 3rd PT extension. In such case, testing will require uninstalling and reinstalling the extension(s), since the media assets will be deleted, and thus making the process significantly slower.

**Comment by brianteeman** [comment]
The real problem in this specific example is that an existing install of rc5 will have the three files in it but for some reason when you run the install script now now only one file is created. When someone upgrades from rc5 to the final release wouldn't that cause problems

**Comment by dgrammatiko** [comment]
> but for some reason when you run the install script now now only one file is created.

I have 2 files and once you run the compress part will get also the `.gz`

Screenshot 2021-08-04 at 11 57 27

**Comment by dgrammatiko** [comment]
@brianteeman can you retest deleting the media folder and re run `npm i`? You should now get 2 files

**Comment by brianteeman** [comment]
image

**Comment by dgrammatiko** [comment]
@brianteeman should be ok now with https://github.com/joomla/joomla-cms/pull/35039/commits/01e89f8ab63035cf3cda8dbe3d91c1b459932b42

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 01e89f8ab63035cf3cda8dbe3d91c1b459932b42<br /><br />Patch works. On loding the article the description gets truncated to 160 characters.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35039">issues.joomla.org/tracker/joomla-cms/35039</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 01e89f8ab63035cf3cda8dbe3d91c1b459932b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35039">issues.joomla.org/tracker/joomla-cms/35039</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35039">issues.joomla.org/tracker/joomla-cms/35039</a>.</sub>

**Comment by wilsonge** [comment]
@dgrammatiko can you fix conflicts here and @brianteeman you able to test this on windows?

**Comment by brianteeman** [comment]
@wilsonge https://github.com/joomla/joomla-cms/pull/35039#issuecomment-892483043 its fine

**Comment by wilsonge** [comment]
@brianteeman but then dimitris fixed the two files thing. which you gave a negative test on and he attempted a second fix on (see https://github.com/joomla/joomla-cms/pull/35039#issuecomment-892539757)

**Comment by brianteeman** [comment]
ah sorry. taking another look

**Comment by brianteeman** [comment]
ok now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 01e89f8ab63035cf3cda8dbe3d91c1b459932b42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35039">issues.joomla.org/tracker/joomla-cms/35039</a>.</sub>

**Comment by wilsonge** [comment]
Amazing. Thanks @dgrammatiko just conflicts and I'll get this in then

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
