### PR TITLE
[4.0] Tiny-mce plugin options

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the code so that the switchers show green for on and grey for off

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0b77877a5d31673ab3f5a70222dca4e80a05801e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24664">issues.joomla.org/tracker/joomla-cms/24664</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b77877a5d31673ab3f5a70222dca4e80a05801e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24664">issues.joomla.org/tracker/joomla-cms/24664</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24664">issues.joomla.org/tracker/joomla-cms/24664</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
