### PR TITLE
[4.0] WebAssetManager Exception messages

### PR DESCRIPTION
**Pull request by brianteeman**
Simple Pr to correct the english for the exception messages.

Code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 119f5a1a5530c5528390fe8a100b87d0d0df63f8<br /><br />Am not native English speaker but good enough to confirm the changes are correct and good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27853">issues.joomla.org/tracker/joomla-cms/27853</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 119f5a1a5530c5528390fe8a100b87d0d0df63f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27853">issues.joomla.org/tracker/joomla-cms/27853</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27853">issues.joomla.org/tracker/joomla-cms/27853</a>.</sub>

**Comment by alikon** [comment]
@richard67 maybe you can hit the merge button, so you can start to use your new superpower 
:smile:

**Comment by richard67** [comment]
@alikon Is it the button with the red exclamation mark left beside the "Comment" button? ;-) (joking)

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
thx

**Pull request merged**
