### PR TITLE
Fix colour field in repeatable form field

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #11309 
#### Summary of Changes

This PR fixes the colour input fields in repeatable form fields. Reason being is the input fields needed to be properly destroyed and re-initiated, which they weren't
#### Testing Instructions

Add the following repeatable form field to (for example) the `mod_login.xml` file:

```
<field name="j51_inlineicons"
    type="Repeatable"
    select="List/Add Icons(s)"
    icon="list"
    description="Icons(s)"
    label="Icons(s)">
    <fields name="params">
    <fieldset hidden="true" name="j51_inlineicons_modal" repeat="true">
        <field name="j51_iconclass" type="text" default="" label="FontAwesome Icon Class" description="Set your FontAwesome Icon class name" />
        <field name="j51_icontitle" type="text" default="" label="Icon Title" description="Set your icon title" />
        <field name="j51_iconurl" type="text" default="" label="Icon URL" description="Set your linked icon URL" directory="/" filter="" exclude="" stripext="" />
        <field name="j51_iconcolor" type="color" default="#adb3b8" label="Icon Color" description="Set your icon colors" />
    </fieldset>
    </fields>
</field>
```

Then in the Module Manager, open the Login module, then open the repeatable form field.

**Before patch:**

before

**After patch:**

after

### CODE REVIEW

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 9c104638aff057bf5c739eaedd95fed96dd2568c<br /><br />PR worked as described for me - before the js was dodgy and the input field misplaced. Both fixed after applying the JS modification. Nice work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11451">issues.joomla.org/joomla-cms/11451</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 9c104638aff057bf5c739eaedd95fed96dd2568c<br /><br />Tested successfully with version Joomla! 3.6.3-dev Development [ Noether ] 5-August-2016 00:32 GMT <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11451">issues.joomla.org/joomla-cms/11451</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11451">issues.joomla.org/joomla-cms/11451</a>.</sub>

**Comment by Fedik** [comment]
@C-Lodder can you please do same for new field [subform-repeatable.js#L219](https://github.com/C-Lodder/joomla-cms/blob/9c104638aff057bf5c739eaedd95fed96dd2568c/media/system/js/subform-repeatable-uncompressed.js#L219) ?

**Comment by C-Lodder** [comment]
@Fedik - Does the issue occur with sub-forms too?

**Comment by C-Lodder** [comment]
@Fedik - I've tested the colour field on subforms-repeatable and it's working fine.

**Comment by C-Lodder** [comment]
Applied fix to subforms-repeatable too

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully

Excellent! Nicely done! Admittedly I was unable to replicate any issues with the new subforms repeatable before the patch but both working perfectly now.

**Pull request merged**
