### PR TITLE
Cleanup batch copy of items

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Cleanup of the batch copy'ing of data. This introduces a empty post processing of batch copied data in order for com_content to add items into the frontpage table (and other components to do whatever processing they want).

### Testing Instructions
Test Banners, Newsfeeds and contact work as is (there are no changes here - they just implement the parent method which is the same)

In com_content test batch copying with items that are featured and aren't featured and ensure that items are created correctly in the `#__content_frontpage` table

### Documentation Changes Required
None

### CODE REVIEW

**Comment by webnet-assmann** [comment]
I have tested this item :red_circle: unsuccessfully on 44f856de38fc7001c8877166a837dddef41bcad4<br /><br />Newsfeeds and featured items are created correctly in the #__content_frontpage table
banners get an error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13501">issues.joomla.org/tracker/joomla-cms/13501</a>.</sub>

**Comment by joomlamarco** [comment]
I have tested this item :red_circle: unsuccessfully on 44f856de38fc7001c8877166a837dddef41bcad4<br /><br />Banner creates an error.News, Contact works fine. The entries into table #_content_frontpage are correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13501">issues.joomla.org/tracker/joomla-cms/13501</a>.</sub>

**Comment by wilsonge** [comment]
Hey both. can you please tell me what errors you are getting. I can't seem to reproduce anything at the moment (I have merged in staging since you both tested so it might be simply related to that)

**Comment by webnet-assmann** [comment]
See the Screenshot, i've uploaded

**Comment by wilsonge** [comment]
Hmm I definitely can't reproduce. Can you please try again on a clean copy of staging/nightly. Maybe just merging in staging now fixed something?

**Comment by webnet-assmann** [comment]
Reproduced it on a nightly build - same error. It's localhost with xampp on windows10 php7.0.9

**Comment by webnet-assmann** [comment]
Feel free to contact @zero-24

**Comment by zero-24** [comment]
> Hmm I definitely can't reproduce. Can you please try again on a clean copy of staging/nightly. Maybe just merging in staging now fixed something?

@wilsonge it is about the different sql definition https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L111 for banners the `title` field is called `name` so we need a extra case for that :smile:

**Comment by wilsonge** [comment]
Umm i don't understand how I can't reproduce this cause clearly you are correct. But I guess this latest version should fix things?

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on 1121efedbbae4884d1ef1e14ed4c76c46f24fe53<br /><br />Everything is fine now :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13501">issues.joomla.org/tracker/joomla-cms/13501</a>.</sub>

**Comment by wilsonge** [comment]
Merged in staging

**Comment by roland-d** [comment]
@wilsonge Is this merged?? If not, can you update the merge conflicts?

**Comment by priiish** [comment]
I have tested this item :red_circle: unsuccessfully on 2952f2a0ac3b85a5cfec5ef220d8336c9b9f3001<br /><br />- Tried to copy banner to another category via batch feature
- error coming up:
"Argument 1 passed to Joomla\CMS\MVC\Model\AdminModel::cleanupPostBatchCopy() must be an instance of Joomla\CMS\MVC\Model\JTableInterface, instance of BannersTableBanner given, called in 
<path-to-joomla!>/Joomla_3/libraries/src/MVC/Model/AdminModel.php on line 450	
<path-to-joomla!>/Joomla_3/libraries/src/MVC/Model/AdminModel.php:472"

therefore tested unsuccessful

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13501">issues.joomla.org/tracker/joomla-cms/13501</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7ec4d5d34d6e4947394329dbd3e0dcd35713a1f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13501">issues.joomla.org/tracker/joomla-cms/13501</a>.</sub>

**Pull request merged**
