### PR TITLE
p4.0] com-cache namespace

### PR DESCRIPTION
**Pull request by brianteeman**
It was missing the Text namespace ad producing errrors

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 698bd3f16a2cd3794376227c5d688ddd97c879cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22510">issues.joomla.org/tracker/joomla-cms/22510</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 698bd3f16a2cd3794376227c5d688ddd97c879cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22510">issues.joomla.org/tracker/joomla-cms/22510</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22510">issues.joomla.org/tracker/joomla-cms/22510</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
