### PR TITLE
[4.0] s/succesfully/successfully

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/succesfully/successfully

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This issue does not appear on the Issue Tracker for some reason.

**Comment by richard67** [comment]
@PhilETaylor I've corrected the build for you (staging -> 4.0-dev).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by richard67** [comment]
It appears on the tracker but has no option to test it.

I've tested it with success. Code review + check that this PR covers all occurrences of wrong English "succesfully" (case-insensitive) in Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by PhilETaylor** [comment]
> @PhilETaylor I've corrected the build for you (staging -> 4.0-dev).

Doh. I gave up a long time ago correcting spelling in 3.x :)

**Comment by richard67** [comment]
Does anybody have an idea why for this PR there is no button for testing shown in the issue tracker?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by PhilETaylor** [comment]
Maybe @mbabker might know - else you will have to view the source code of the tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by mbabker** [comment]
Webhook doesn't process correctly the most likely cause.

**Comment by richard67** [comment]
@SharkyKZ Have you tested this PR with success and just could not report that on the issue tracker because of problems mentioned above? If yes, then report it back here so @Quy could make it RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by Twincarb** [comment]
Code Review
No Test Button to confirm as above comments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by Quy** [comment]
Does PR #14607 apply here with comments?

**Comment by PhilETaylor** [comment]
No - it doesn’t apply in the slightest 

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23008">issues.joomla.org/tracker/joomla-cms/23008</a>.</sub>

**Comment by richard67** [comment]
succesfully merged ;-)

**Pull request merged**
