### PR TITLE
[4.3] Template style assigned text plurals

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Use plural language strings

### Testing Instructions
Create a new template style and assign it to ONE page
Create a new template style and assign it to TWO pages

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on fbf59417d2a1b607e4d5d28d3b4d052595d85a7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40732">issues.joomla.org/tracker/joomla-cms/40732</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fbf59417d2a1b607e4d5d28d3b4d052595d85a7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40732">issues.joomla.org/tracker/joomla-cms/40732</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40732">issues.joomla.org/tracker/joomla-cms/40732</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman

**Pull request merged**
