### PR TITLE
[4.0] Eaccelerator post-install

### PR DESCRIPTION
**Pull request by brianteeman**
We removed the message from new installs back in 2015 https://github.com/joomla/joomla-cms/pull/6199

it has not been possible to use eaccelerator since 3.4 iirc

This file is just a remnant that should have already been removed

we certainly dont need to maintain the language strings or update the code ;)

> /**
> * Checks if the eAccelerator caching method is enabled.
>  *
>  * This check should be done through the 3.x series as the issue impacts migrated sites which will
>  * most often come from the previous LTS release (2.5). Remove for version 4 or when eAccelerator support is added.
>  *
>  * This check returns true when the eAccelerator caching method is user, meaning that the message concerning it should be displayed.
>  *
>  * @return  integer
>  *
>  * @since   3.2

### CODE REVIEW

**Comment by Quy** [comment]
Remove language strings?

```
COM_CPANEL_MSG_EACCELERATOR_BODY="eAccelerator is not compatible with Joomla! By selecting the Change to File Caching button below we will change the cache handler to file. If you want to use a different cache handler, please change it in the Global Configuration page."
COM_CPANEL_MSG_EACCELERATOR_BUTTON="Change to File."
COM_CPANEL_MSG_EACCELERATOR_TITLE="eAccelerator is not compatible with Joomla!"
```

**Comment by brianteeman** [comment]
oops forgot to commit the change before pushing

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ee00f04f673ad4f018d3ef38204c2a5e25c572f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26323">issues.joomla.org/tracker/joomla-cms/26323</a>.</sub>

**Comment by brianteeman** [comment]
update branch to retrigger drone

**Comment by rmittl** [comment]
How to test?

**Comment by uglyeoin** [comment]
@rmittl you will need to install the patch and check the deleted file has gone as well as the language strings.  It will require FTP access.  If you are doing PBF then you possibly may not have FTP which will mean a localised install.  I'll give it a go so you can move onto another issue if you are still working.

**Comment by wilsonge** [comment]
Do we need to trash the message from the database? I don't remember exactly how this component works anymore

**Comment by brianteeman** [comment]
@wilsonge you mean on existing installs? Technically you are probably correct but we havent done that before in similar curcumstances

**Comment by wilsonge** [comment]
OK merging. I think we probably need to revisit that policy decision. Inconsistent release leads these days :roll_eyes:

**Comment by brianteeman** [comment]
Thanks. Policy is not my area

**Pull request merged**
