### PR TITLE
[5.1] Guided Tours Welcome Text Update Step 1 

### PR DESCRIPTION
**Pull request by coolcat-creations**
Improve and shorten text for the welcome Guided Tour to add more clarity about what the tour is about.

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I agree its too long

But this proposed text is not describing the same thing as the original.

And my 2c "there is nothing **fun** about building a web site for your job"

**Comment by coolcat-creations** [comment]
Okay, I removed the fun part @brianteeman

**Comment by sandewt** [comment]
Joomla or Joomla! ? Both occur here. My suggestion is Joomla! (with an exclamation mark) only in the tittle.

**Comment by coolcat-creations** [comment]
Removed the Bang before "site".

**Comment by brianteeman** [comment]
/me still does see this proposed text as having the same intended meaning as the original concept text

**Comment by LadySolveig** [comment]
Thank you!

**Pull request merged**
