### PR TITLE
Fix PHPCS failing in drone after release of 4.2.4

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Fix code style errors introduced with release of 4.2.4.

### Testing Instructions

Check drone logs for PHPCS checks.

### Actual result BEFORE applying this Pull Request

```
FILE: .../plugins/system/debug/src/DataCollector/RequestDataCollector.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
----------------------------------------------------------------------
 24 | WARNING | [ ] Visibility must be declared on all constants if
    |         |     your project supports PHP 7.1 or later
 44 | ERROR   | [x] Expected 1 space after FUNCTION keyword; 0 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```
### Expected result AFTER applying this Pull Request

Success. No errors and no warnings.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by leetempest** [comment]
You cannot now change the visibility of the constant, as this as already been released, and changing it from public to private would be a B/C break! Yes I know its only been released less than an hour, but still a b/c promise is exactly that - a promise, and this breaks that promise

**Comment by richard67** [comment]
> You cannot now change the visibility of the constant, as this as already been released, and changing it from public to private would be a B/C break! Yes I know its only been released less than an hour, but still a b/c promise is exactly that - a promise, and this breaks that promise

@leetempest Yep. This PR here just unmasked another error and when that will be fixed, this PR here will not be necessary anymore, so I will close it.

**Comment by richard67** [comment]
@leetempest P.S.: Your comment doesn’t apply here since the b/c promise doesn’t cover extensions, and the debug plugin is an extension and not e.g. an API.

**Comment by brianteeman** [comment]
PPS Wow you're skills have improved Lee are you sure you're not really Phil trying to get around his block

**Pull request closed without merging**
