### PR TITLE
fixes Titles in the Admin Page

### LINKED ISSUE #24304: [4.0] Titles in the Admin Page
### What needs to be fixed
Titles in the admin page (control panel) are left aligned. It should be at the center.

### Why this should be fixed
It affects the user experience.

### PR DESCRIPTION
**Pull request by meet2410shah**
Pull Request for Issue #24304

### Summary of Changes
administrator\templates\atum\html\module.php

### Testing Instructions
go to /administrator/index.php

### Expected result
Titles in the main content are aligned center.

### Actual result
Previously titles are aligned left which affects user experience.

### Documentation Changes Required
		if ($module->showtitle)
		{
			echo '<h2 style="display:flex; justify-content:center" class="card-header' . $headerClass . '">' . $module->title . '</h2>';
		}

### CODE REVIEW

**Comment by ghost** [comment]
Please give the Pull Request a more meaningful Title like the issue.

**Comment by brianteeman** [comment]
1. This PR includes a lot of unrelated changes 
2. Using an inline style is not the best way
3. changing from left/right aligned to center aligned is a design issue

**Comment by C-Lodder** [comment]
Your issue mentions that the title being left aligned affects the user experience. Do you have any evidence to back this up? Why _should_ it be aligned to the center?

**Comment by brianteeman** [comment]
This should be closed for the reasons stated above

**Comment by ghost** [comment]
Closed as stated by @brianteeman

**Pull request closed without merging**
