### PR TITLE
[4.0] Improve article list performance when filtering by tags

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

This ports changes from #19284 to backend article list view.

### Testing Instructions

Create some articles with tags.
View article list in backend.
Filter articles by single and multiple tags.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Here drone is failing because of PHPCS, not because of unrelated stuff like elsewhere.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 532c1893e302c71004d6515af40ab1f2132fb4ea<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

About performance I can't say anything because my test data set is too small.

But I can confirm everything works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26466">issues.joomla.org/tracker/joomla-cms/26466</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4f40d0773ee6a6d9cbea030b8d76c4d9e3c66f16<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

About performance I can't say anything because my test data set is too small.

But I can confirm everything works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26466">issues.joomla.org/tracker/joomla-cms/26466</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4f40d0773ee6a6d9cbea030b8d76c4d9e3c66f16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26466">issues.joomla.org/tracker/joomla-cms/26466</a>.</sub>

**Comment by alikon** [comment]
RTD<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26466">issues.joomla.org/tracker/joomla-cms/26466</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
