### PR TITLE
JImage: drop incorrect use of imagecopyresize (take 2)

### PR DESCRIPTION
**Pull request by piotr-cz**
Rebased to staging branch #2116

Description from #2116 (added by @zero-24)
There was a invisible bug in the `resize` method that showed up when I've implemented [SCALE_FIT](https://github.com/joomla/joomla-cms/pull/1565) functionality - I didn't have time to update last commit like in the [Framework](https://github.com/joomla/joomla-framework/pull/223), which is attached here. Below is explanation what it's all about.

The class didn't evaluate loaded image be transparent ([see fix](https://github.com/joomla/joomla-framework/pull/223/files#L0R642)) and thus was always using [`imagecopyresampled`](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Image/Image.php#L701) function and everything seemed alright.

After the patch resource handle is evaluated to be transparent and `imagecopyresized` method produces visually poor results.

After little research I'm not sure, why it's even been used; I hope the author @rvsjoen can say something about it.
It seems that `imagecopyresized` is quite faster, but still would be used for wrong reasons.

Other frameworks:
- [Lavarell Resizer bundle uses](https://github.com/maikeldaloo/Resizer/blob/master/resizer.php#L133) just `imagecopyresampled`
- Symfony [too](http://trac.symfony-project.org/browser/plugins/sfImageTransformPlugin/branches/2.0/lib/transforms/GD/ImageTransformResizeSimpleGD.class.php#L60)
- Kohana [as well](https://github.com/kohana/image/blob/3.3/master/classes/Kohana/Image/GD.php)

Resources:
- TuxRadar: [Scaling and rotating](http://www.tuxradar.com/practicalphp/11/2/12)
- StackOverflow: [php imagecopyresized vs imagecopyresampled](http://stackoverflow.com/questions/18004702/php-imagecopyresized-vs-imagecopyresampled-vs-imagecopy-pros-cons)
- php.blogle.info: [Performance comparison](http://www.php.blogle.info/2010/funkcje-biblioteki-rozszerzenia/php-a-grafika/wydajnosc-funkcji-imagecopyresampled-i-imagecopyresized/)
- random search [result showing difference in quality](http://blog.vexer.ru/post53115076)

### CODE REVIEW

**Comment by designbengel** [comment]
How to test? thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by SniperSister** [comment]
I have tested this item :red_circle: unsuccessfully on eac76a4c032f00c915ecd8f59e7832e5154dd8df<br /><br />I was able the reproduce the "visually poor result" before the patch, but the patch itself didn't work either, because the transparency got lost. I'll attach the 2 images that have been generated in the next comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by jduerscheid** [comment]
I have tested this item :red_circle: unsuccessfully on eac76a4c032f00c915ecd8f59e7832e5154dd8df<br /><br />Picture is no more transparent. the Problem is with and without the patch the same Problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by SniperSister** [comment]
Original:
https://commons.wikimedia.org/wiki/File:Tibia_insulaechorab_transparent.png

Before:
screen shot 2015-10-24 at 08 15 35

After:
screen shot 2015-10-24 at 08 15 35

Tested on 3.4.5 with PHP 5.4.38.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by jduerscheid** [comment]
I tested under PHP Version 5.6.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by roland-d** [comment]
Hello @piotr-cz

Thank you for your contribution.

The last comment here was on 24th October 2015. So the question is, Is this issue/pull request still valid? 
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Comment by piotr-cz** [comment]
Hi this fix is actually from 2013 and I'm not using this Joomla functionality anymore.
As there are two failed tests it looks like this PR doesn't address the problem.

Anyway let's wait suggested 4 weeks before closing it.

**Comment by brianteeman** [comment]
There really is no point in waiting. If you're not going to look at the issue to see why your own PR has two failed tests it might as well be closed right now

**Comment by Kubik-Rubik** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla!.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4234">issues.joomla.org/joomla-cms/4234</a>.</sub>

**Pull request closed without merging**
