### PR TITLE
[3.9] Fixed left-right operator precedence in showon expressions.

### PR DESCRIPTION
**Pull request by chrisdavenport**
Pull Request for Issue #16954 .

### Summary of Changes
The operator precedence in showon expressions was not working as expected, that is, from left to right.  All operators prior to the right-most were being ignored completely.

### Testing Instructions
Set up a form using the XML file (which is actually the .txt file in the attached zip).  This has three fields (Field 1, Field 2 and Field3) which can each be set to Yes or No.  Depending on the state of these fields, further fields will be shown or hidden according to the showon expressions they contain.  All possible operator combinations for the three fields are included.  Change the field states and compare with the spreadsheet in the attached zip which shows the actual and expected results.

### Expected result
As per the Expected section of the spreadsheet in the attached zip.

### Actual result
As per the Actual section of the spreadsheet in the attached zip.

### Documentation Changes Required
Add a note to https://docs.joomla.org/Form_field to explain that left-right precedence should be expected.

[showon-issue-16954.zip](https://github.com/joomla/joomla-cms/files/2971796/showon-issue-16954.zip)

### CODE REVIEW

**Comment by chrisdavenport** [comment]
The cms.js file will also need to be amended.  Any preference on minifiers?

**Comment by wilsonge** [comment]
Not in j3. take your pick

**Comment by chrisdavenport** [comment]
Minified file added.

**Comment by dgrammatiko** [comment]
@chrisdavenport could you please do the same changes for J4: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/showon.es6.js

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 82f49c0ef287aec9939661b2b14dfa1ca2c83eb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24197">issues.joomla.org/tracker/joomla-cms/24197</a>.</sub>

**Comment by HLeithner** [comment]
I tested it successful. thx

**Comment by gwsdesk** [comment]
I have tested this item ✅ successfully on [82f49c0](https://github.com/joomla/joomla-cms/commit/82f49c0ef287aec9939661b2b14dfa1ca2c83eb8)

**Pull request merged**
