### PR TITLE
[4.1] Codemirror search

### LINKED ISSUE #26411: Add search plugins to Codemirror on template file editing
Is possible to add Codemirror search plugins? https://codemirror.net/demo/search.html

If it isn't possible to add for Joomla 3.*, is it maybe possible to add for Joomla 4.0?

P.s. - search plugin js files is exist in addon directory in Codemiror dir in site 'media' dir, so it's simply not "loaded" ("copypaste" into addons.js)... isn't it?

### PR DESCRIPTION
**Pull request by brianteeman**
This PR corrects some obvious path errors in the build script for codemirror and loads the search plugin.

To test this apply the pr and run `npm ci`

Go to the template manager and open a file to edit.

Try ctrl-f to search, ctrl-g to find next, shift ctrl f to search replace

Closes #26411

### CODE REVIEW

**Comment by Quy** [comment]
Ctrl-H brings up the browser's History.

**Comment by brianteeman** [comment]
@quy 

> Ctrl-H brings up the browser's History.

sorry it was shift ctrl f

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 30abeaa4335437eb6fa7584c5f5027ebcb23fc5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37130">issues.joomla.org/tracker/joomla-cms/37130</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 30abeaa4335437eb6fa7584c5f5027ebcb23fc5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37130">issues.joomla.org/tracker/joomla-cms/37130</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37130">issues.joomla.org/tracker/joomla-cms/37130</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
