### PR TITLE
[4.0] Replace com_content 'Image Float' with 'Image Class'

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #31017.

### Summary of Changes
Make same changes to the frontend to match the backend.

### Testing Instructions
In the backend, go to Global Configuration > Articles > Editing Layout
Enable `Frontend Images and Links`
Login in the frontend
Edit an article
Click `Images and Links` tab

### Actual result BEFORE applying this Pull Request
Image class displays as dropdown menu.

### Expected result AFTER applying this Pull Request
Image class displays as text field.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7e8e3ee04281d5b142af14a8085964f17a27e4b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31163">issues.joomla.org/tracker/joomla-cms/31163</a>.</sub>

**Comment by gostn** [comment]
I have tested this item :white_check_mark: successfully on 7e8e3ee04281d5b142af14a8085964f17a27e4b3<br /><br />Adding ´right´ on intro-image didnt change float, but thats another reported issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31163">issues.joomla.org/tracker/joomla-cms/31163</a>.</sub>

**Comment by richard67** [comment]
> Adding ´right´ on intro-image didnt change float

@gostn Yes, because it needs to use `float-right`.

**Comment by gostn** [comment]
´float-right´ dont change anything on intro-image.

´right´ on Full Article Image works.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31163">issues.joomla.org/tracker/joomla-cms/31163</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
