### PR TITLE
Remove check as JApplicationCli constructor has a check for this

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue # Check is unnecessary as JApplicationCli constructor has a check for this.

### Summary of Changes
Removes duplicated code

### Testing Instructions
CLI scripts are still work in CLI and not accessible via things like web interface. 

**(code review might be sufficent)**

### Expected result
CLI scripts are still work in CLI and not accessible via things like web interface. 

### Actual result
CLI scripts are still work in CLI and not accessible via things like web interface. 

### Documentation Changes Required
none

### CODE REVIEW

**Comment by photodude** [comment]
Can someone rerun the appveyor 5.6 test? the Cachelite failure is unrelated to this PR
```php
1) JCacheStorageCacheliteTest::testCacheTimeout
Some data should be available in lifetime.
Failed asserting that false matches expected 'testData'.
\tests\unit\core\case\cache.php:121
\tests\unit\suites\libraries\joomla\cache\storage\JCacheStorageCacheliteTest.php:66
```

**Comment by wilsonge** [comment]
You can't rerun appveyor tests :(

**Comment by mbabker** [comment]
I have to do it from the bot account.  I set it to rebuild.

**Comment by photodude** [comment]
Thanks @mbabker

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on 3300a4629e4910bc34ac2af36bfc4d8847549308<br /><br />scripts remain inaccessible for the web as indeed the `JApplicationCli` does the same check.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15011">issues.joomla.org/tracker/joomla-cms/15011</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3300a4629e4910bc34ac2af36bfc4d8847549308<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15011">issues.joomla.org/tracker/joomla-cms/15011</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by wilsonge** [comment]
It's not exactly the same check. But seems to be good enough for web accessibility

**Comment by photodude** [comment]
I believe the [JApplicationCli constructor check](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/cli.php#L52_L60) is better than the PHP_SAPI check. As @nikosdion pointed out in another pr
>You MUST NOT explicitly check for the CLI SAPI. Some hosts only provide access to the CGI SAPI but allow you to set the maximum execution time to 0, i.e. work almost identical to the CLI SAPI. In these cases you need to tweak the way input handling works.

I think the JApplicationCli constructor check fixes that issue too

Although his [constructor check is probably a lot better](https://github.com/akeeba/docimport/blob/development/component/frontend/Helper/Cli.php#L232_L245)

**Comment by nikosdion** [comment]
Please do not mention me on Joomla repositories.

**Pull request merged**
