### PR TITLE
[com_finder] filters view: searchtools ordering, bug corrections and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR by adding the ordering normalizes the searchtools in com_finder filters view. 

Also:
- Corrects some minor bugs
- Some code style improvements.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use latest staging and apply patch
2. Go to Components -> Smart Search -> Filters
3. Create some filters
4. Test if search, filters, ordering and page limit (aka searchtools) are working properly.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c7059d2700a36d6064629c78c498bf14efe37ed6<br /><br />Makes sense, we can have other bulk process.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have not tested this item.<br /><br />ups<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by brianteeman** [comment]
Would it not be consistent to move the message that Smart Search content plugin is not enabled to above the filters?


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by andrepereiradasilva** [comment]
yes it will and it will be done in another PR.
this PR is only for the smart search filters view (Smart Search: Search Filters).

**Comment by brianteeman** [comment]
OK I thought in the past you did it as a single PR. My mistake.

**Comment by andrepereiradasilva** [comment]
no smart search has many things to correct. i will do one PR for each view.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2b4ceb2edf4db1206ed2e2eb3cf30a71d8843268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman just corrected a state filter problem. wasn't working properly in hathor. See (https://github.com/joomla/joomla-cms/pull/10029/commits/9855e85a296f60a68197b75374889b345d5a9262)

To test this change just test the state filter in isis and in hathor.

I found similar problem in some filters in hathor. will make a PR to solve them.

**Comment by brianteeman** [comment]
Is it related to #6578

**Comment by andrepereiradasilva** [comment]
no, not related.

This is because the filter input is too restrictive. 'int' doesn't allow empty values, only int. The same problem in happing to languages. All is `*`, but the input filter is `cmd` that doesn't allow `*`.

See here https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/filter/src/InputFilter.php#L147-164

As said i will  make a PR to correct them.

**Comment by brianteeman** [comment]
OK - I was hoping it was and we could kill two birds with one PR

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 9855e85a296f60a68197b75374889b345d5a9262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @grhcj thanks for testing!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9855e85a296f60a68197b75374889b345d5a9262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10029">issues.joomla.org/joomla-cms/10029</a>.</sub>

**Pull request merged**
