### PR TITLE
[4.0] Correct module quick task link

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #26414 .

### Summary of Changes

Adds client filter to module quick task link in admin menu presets.

### Testing Instructions

View administrator modules in backend.
In menu click + icon next to Site Modules.

### Expected result

A list of site modules opens up.

### Actual result

A list of administrator modules opens up.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 483a7d7768a841b07bdf98faf588491689c9f1d7<br /><br />- Go to administrator modules
- Click on + icon in Site modules menu item shows a list of administrator modules
- After patch applied, click on + icon shows a list of site modules<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26415">issues.joomla.org/tracker/joomla-cms/26415</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 483a7d7768a841b07bdf98faf588491689c9f1d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26415">issues.joomla.org/tracker/joomla-cms/26415</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26415">issues.joomla.org/tracker/joomla-cms/26415</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
