### PR TITLE
[a11y] Fix aria attribute aria-sort

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Replace the aria attribute "aria-sorted" by the correct attribute "aria-sort"

### Testing Instructions
for example com_content/articles, reorder the table via the table header and inspect the source code. The aria attribute "aria-sorted" is set. 
Use AXE to get the error "wrong attribute aria-sorted". 

Apply the patch (don't forget the npm i)

The attribute is now "aria-sort" and AXE is satisfied.

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 0c4770227cf4488cb20f492610c43d6886427e5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23662">issues.joomla.org/tracker/joomla-cms/23662</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 0c4770227cf4488cb20f492610c43d6886427e5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23662">issues.joomla.org/tracker/joomla-cms/23662</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23662">issues.joomla.org/tracker/joomla-cms/23662</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0c4770227cf4488cb20f492610c43d6886427e5c<br /><br />My fault - oops<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23662">issues.joomla.org/tracker/joomla-cms/23662</a>.</sub>

**Comment by brianteeman** [comment]
Can you fix the conflicts please

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
