### PR TITLE
[4.0] date filter width

### PR DESCRIPTION
**Pull request by brianteeman**
This pr makes the date filter field the same width as the other filters. you can test this with the Banners->tracks filters

### CODE REVIEW

**Comment by Quy** [comment]
Could it be that the value `2019-08-26` is only 10 characters so don't need to be wider?

**Comment by brianteeman** [comment]
1. consistency
2. the hint text is truncated

image

**Comment by infograf768** [comment]
One of this template limitations.
In 3.x, we display the full format of the date to be entered for any language.

Screen Shot 2019-08-27 at 07 14 40

If the placeholder is truncated, which is the case before or after this PR, it is just useless.

Screen Shot 2019-08-27 at 07 23 22

Modifying globally the font-size and padding to something like
padding: 0.2rem 0.2rem;
font-size: 0.9rem;

would solve the issue, and this should be done imho in general in this template to get a better UI
Screen Shot 2019-08-27 at 07 52 25

**Comment by 0xNorin** [comment]
I agree that the font size and paddings are a little bit to large in the new template "here and there". Just a little bit more consistency would be great.

**Comment by C-Lodder** [comment]
Aren't the standard inputs set to 100% width so that the parent will dictate the width?

**Comment by brianteeman** [comment]
@c-lodder you would be correct in thinking so but there is also a min-width set on the input of these filters AND for the calendar field it is an input with an additional button appended.

Don't care how its fixed but it should be fixed and instead of sitting there and moaning I tried to fix it

**Comment by C-Lodder** [comment]
@brianteeman That's fine. Was just asking as this looks like a very dirty fix.

**Comment by brianteeman** [comment]
yes it is a dirty fix - all my css is like that. :(

**Comment by opn365** [comment]
I have tested this item :red_circle: unsuccessfully on cb3378b51b37b5440b91396569228eab60e08513<br /><br />Did not change the width of the filter box<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26040">issues.joomla.org/tracker/joomla-cms/26040</a>.</sub>

**Comment by brianteeman** [comment]
@opn365 did you run npm i

**Comment by opn365** [comment]
@brianteeman  
> @opn365 did you run npm i

did not for initial test but then ran npm and seemed to get the same result. (i was testing using pbf preloaded instance)

**Comment by LukasHH** [comment]
i would like add a css in the template.css with min-with, not font-size. eg:
`.field-calendar > .input-group .form-control{
  min-width: 15rem;
}`

**Comment by nadjak77** [comment]
applied patch, run pm i, patch works but I think the input is still too small
image

**Comment by nadjak77** [comment]
I have tested this item :white_check_mark: successfully on cb3378b51b37b5440b91396569228eab60e08513<br /><br />apply patch
run npm i
patch work
but I think the input is still too small
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26040">issues.joomla.org/tracker/joomla-cms/26040</a>.</sub>

**Comment by jaydevingawale** [comment]
I have tested this item :white_check_mark: successfully on cb3378b51b37b5440b91396569228eab60e08513<br /><br />I have tested this and its working correctly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26040">issues.joomla.org/tracker/joomla-cms/26040</a>.</sub>

**Comment by Quy** [comment]
While it looks good in English, it doesn't align in French (and possibility other languages) since the dropdown's width depends on the label's length and not a fixed width. Accessibility-wise, I assume it would be better to read the placeholder. 

26040-french

**Pull request closed without merging**
