### PR TITLE
[mod_languages] - no need of cache fields

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/23166#issuecomment-441553945

### Summary of Changes
removed the unsed cache fields

### Testing Instructions
the module works as before

p.s 
cc : @infograf768

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d25c3cd92f8975b460002063eb5f023d19afa305<br /><br />tks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23174">issues.joomla.org/tracker/joomla-cms/23174</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d25c3cd92f8975b460002063eb5f023d19afa305<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23174">issues.joomla.org/tracker/joomla-cms/23174</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23174">issues.joomla.org/tracker/joomla-cms/23174</a>.</sub>

**Comment by klas** [comment]
Sorry to be late to the party, but why were this fields removed? This one was different from mod_syndicate, here caching worked and since by the itemid.

**Comment by infograf768** [comment]
hmm. Have'nt we suggested many users to disable the cache for this module as they were getting weird results?

**Pull request merged**
