### PR TITLE
[com_installer] languages: Allow to search language tag

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

Allow to search for language tag in com_installer languages view.
#### Testing Instructions

Code review, or:
1. Go to Extensions -> Install languages
2. Try to search for language tag (ex: cs-CZ). No results.
3. Apply patch
4. Try to search now. All ok.

### CODE REVIEW

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 1ffeec4ebe1a6c97380d400279d2d4e54d78ce62<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10253">issues.joomla.org/joomla-cms/10253</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1ffeec4ebe1a6c97380d400279d2d4e54d78ce62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10253">issues.joomla.org/joomla-cms/10253</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10253">issues.joomla.org/joomla-cms/10253</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 @BurtNL thanks for testing!

**Comment by wilsonge** [comment]
@brianteeman can you please look at the English here

**Comment by andrepereiradasilva** [comment]
thanks for testing, comments and merging!

**Comment by brianteeman** [comment]
@wilsonge the language string sucks but it is consistent and I already have a note to review all these search tips in the en-gb working group

**Pull request merged**
