### PR TITLE
[4] sApplication/ApplicationModel

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 5ae8864c002b1dcb07fae85bbaf54a094d2a06dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34004">issues.joomla.org/tracker/joomla-cms/34004</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5ae8864c002b1dcb07fae85bbaf54a094d2a06dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34004">issues.joomla.org/tracker/joomla-cms/34004</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34004">issues.joomla.org/tracker/joomla-cms/34004</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
