### PR TITLE
Fix padding for #9822 + minor changes for consistency of iframe modals

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue #9822 .
#### Summary of Changes
- content is embedded in a container div (using already existing container-popup class for modal.php)
- add a few empty lines to improve the readability
- adjust <code>.container-popup</code> padding
#### Testing Instructions
- Test with TinyMCE editor
- Go to: Content > article, and edit an article
- clic on editor toolbar buttons: module, article, image and pagebreak
- control if padding is ok, as well as tooltip visible
- verify if issue #9822 for Page break is fixed

**Example with Modules modal:**
Before Patch
capture d ecran 2016-04-20 a 17 30 22

After Patch
capture d ecran 2016-04-21 a 00 56 58

**Page Break issue #9822 solved:**
Before Patch
capture d ecran 2016-04-20 a 19 58 22

After Patch
capture d ecran 2016-04-20 a 19 59 59

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 577576c0afe855331856e196cf6f50525a1ea28f<br /><br />Thanks - great stuff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10013">issues.joomla.org/joomla-cms/10013</a>.</sub>

**Comment by andrepereiradasilva** [comment]
pleazse don't add the hr between the searchtools and the results. The other views don't have that (sonsistency).

Also is it possible to make the TinyMCE modals with flexible width like the other modals?

**Comment by JoomliC** [comment]
> pleazse don't add the hr between the searchtools and the results. The other views don't have that (sonsistency).

I added it as it was already in some modal reviewed for styling issue: https://github.com/joomla/joomla-cms/commit/12ed1578cba4e6a6d8a5096744b5e98343874914#diff-8dbab11ae07a5edb26df7ac1ef5cdf74R52
But i agree the hr there is when buttons.
So, to be removed if search tools ? or to be added too in main list ? (as better spacing... or a minor change later to add extra margin bottom search tools ?

> Also is it possible to make the TinyMCE modals with flexible width like the other modals?

This is TinyMCE modals, not Joomla core ones ;-)
This PR is only for contents loaded inside an iframe, in a modal.

**Comment by andrepereiradasilva** [comment]
> So, to be removed if search tools ? or to be added too in main list ? (as better spacing... or a minor change later to add extra margin bottom search tools ?

to be removed if searchtools IMO

> This is TinyMCE modals, not Joomla core ones ;-)
> This PR is only for contents loaded inside an iframe, in a modal.

I know, i mean in another PR
For instance, if the width is larger, the ordering and limit select boxes of searchtools will appear.

Also, i think you need to check frontend edit modals in tinymce too.

**Comment by JoomliC** [comment]
> to be removed if searchtools IMO

@andrepereiradasilva Done!
Removed <hr> after Search Tools

>  For instance, if the width is larger, the ordering and limit select boxes of searchtools will appear.

Responsive design... in media queries (hidden-phone) in think... But, as you added Seach tools in some modals, you may know this already ;-)

> Also, i think you need to check frontend edit modals in tinymce too.

Oh yes! Forgot Beez3 and Protostar, where, indead the class container-popup was missing...

I think it's ok now ?!

@brianteeman need re-testing as missing css change for frontend, and removal of the <hr> between search tools and list of items, as suggested by @andrepereiradasilva .
Thanks!

**Comment by andrepereiradasilva** [comment]
@JoomliC check the searchtools tooltips in the backend tinymce article modal.

The rest seems fine.

There are also other modals :):
- Menu item: Single Article or Article through language association
- Menu item: Single Contact or Contact through language association
- Menu item: Single News feed or News feed through language association
- Category through language association

**Comment by JoomliC** [comment]
> @JoomliC check the searchtools tooltips in the backend tinymce article modal.

Do you mean tooltip truncated for you on windows ? (i don't have issue with top, before and after patch, but added 3 px more than the previously inline style, to padding top for the content).
And so thought setting tooltip placement to bottom not needed.
Could you attach a screenshot ?

> Menu item: Single Article or Article through language association
    Menu item: Single Contact or Contact through language association
    Menu item: Single News feed or News feed through language association
    Category through language association

Not only, as there are too almost all the modal.php loaded inside iframe (but waiting first to complete the PR for Versions, as even if core fixed, i was asked at final to fix Hathor, which is already not good since a long time... :-( )

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on cbb65657899094dff8a4992c8ddaf6d9ea9a6164<br /><br />sorry! it was browser cache...

great job!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10013">issues.joomla.org/joomla-cms/10013</a>.</sub>

**Comment by JoomliC** [comment]
Oh yes, the template.css change ;-) (need always a cache refresh when css changes)
Thanks for testing! :+1:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cbb65657899094dff8a4992c8ddaf6d9ea9a6164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10013">issues.joomla.org/joomla-cms/10013</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10013">issues.joomla.org/joomla-cms/10013</a>.</sub>

**Pull request merged**
