### PR TITLE
[4.0] Use namespaced classes in typehints

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Some more namespacing.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 709942bca9156cbd60397bbd2707205e0a44e373<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30865">issues.joomla.org/tracker/joomla-cms/30865</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 709942bca9156cbd60397bbd2707205e0a44e373<br /><br />On code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30865">issues.joomla.org/tracker/joomla-cms/30865</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30865">issues.joomla.org/tracker/joomla-cms/30865</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
