### PR TITLE
s/Midlename/Middlename

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/Midlename/Middlename

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b45696ce953d792ecec8a1a5f2eaf77f1a41bbea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31930">issues.joomla.org/tracker/joomla-cms/31930</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b45696ce953d792ecec8a1a5f2eaf77f1a41bbea<br /><br />Tested successfully in Beta7-dev of 9 January<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31930">issues.joomla.org/tracker/joomla-cms/31930</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31930">issues.joomla.org/tracker/joomla-cms/31930</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
