### PR TITLE
[5.1] Unused imports

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove unused PHP imports.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Unused imports, see IDE warnings.

### Expected result AFTER applying this Pull Request

No unused imports.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I'm wondering why the CS fixer is not detecting that one.

**Comment by alikon** [comment]
should be nice to have this check/fix in the pipeline
🍹

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by rdeutz** [comment]
LGTM, code review and checking a few files if it is correct

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b1fb2c978635c80f764799a2e61a6d6d77bee1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41980">issues.joomla.org/tracker/joomla-cms/41980</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0b1fb2c978635c80f764799a2e61a6d6d77bee1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41980">issues.joomla.org/tracker/joomla-cms/41980</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41980">issues.joomla.org/tracker/joomla-cms/41980</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
