### PR TITLE
Vertically center Joomla Logo

### PR DESCRIPTION
**Pull request by vlaucht**
Pull Request for Issue # .
#26702
### Summary of Changes
vertically centered the joomla logo on installation page

### Testing Instructions

Install the 4.0-dev, Installation Spinner after Database settings should be centered

### Documentation Changes Required
none

### CODE REVIEW

**Comment by C-Lodder** [comment]
Not tested, but `top: -15%;` doesn't seem right.

**Comment by vlaucht** [comment]
> Not tested, but `top: -15%;` doesn't seem right.

align-items: center; vertically centered the box on the screen, but the box is rotated by 45 degrees, and the center of the logo is not the center of the box, so I had to offset it by -15%

**Comment by brianteeman** [comment]
this doesn't work on other instances of the loader eg when you create fields. Is it supposed to?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26845">issues.joomla.org/tracker/joomla-cms/26845</a>.</sub>

**Comment by brianteeman** [comment]
tested this in two places. Installation and when you create a field. In both cases you can see that it is not centered

chrome_2019-10-28_15-30-45
chrome_2019-10-28_15-34-14

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 173ec04ade12d0cd737b191c01737117fd5e2e46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26845">issues.joomla.org/tracker/joomla-cms/26845</a>.</sub>

**Comment by C-Lodder** [comment]
Yup, thought it wouldn't work. Percentages (`top: -15%`) should not be used to vertically align something

**Comment by Quy** [comment]
Tested successfully.

Apply PR.
Run `npm i`.
Clear browser's cache.
Delete configuration file.
Reinstall.

**Comment by C-Lodder** [comment]
@Quy Reduce your viewport height and you'll notice spacing at the top:

screeny

**Comment by vlaucht** [comment]
center

Open for other suggestions. As seen in the Screenshot, the Box is vertically centered, but the logo is not centered to the box. 
The spacing as mentioned by @C-Lodder only happens if the viewport size is reduced to the height of the logo, and its even worse if the offset is removed

212px would be half the height of the box. The Logo doesn't start at exactly half the box, so I guess offsetting it by roughly -150px would do the trick as well

**Comment by C-Lodder** [comment]
I believe the issue is simply due to the size of the spans, in conjunction with the box dimensions

**Comment by vlaucht** [comment]
Now the logo should be centered in the box

**Comment by ciar4n** [comment]
I'd suggest reverting your changes and instead adding `translate(-25%, -25%)` to this transform... https://github.com/joomla/joomla-cms/blob/fe9210ca7736a820c9b066e1f1ff91e33f38299c/build/media_source/system/scss/joomla-core-loader.scss#L27


It should save you all the messing with margins.

**Comment by vlaucht** [comment]
> I'd suggest reverting your changes and instead adding `translate(-25%, -25%)` to this transform...
> 
> https://github.com/joomla/joomla-cms/blob/fe9210ca7736a820c9b066e1f1ff91e33f38299c/build/media_source/system/scss/joomla-core-loader.scss#L27
> 
> It should save you all the messing with margins.

yep, tested it and it works. Should be fine now

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d75b0d4bb349483835fefb5c7c34072caa1f0667<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26845">issues.joomla.org/tracker/joomla-cms/26845</a>.</sub>

**Comment by pabloarias** [comment]
Not vertically centered.
Screenshot_20191115_202603

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on 1e2696b6ffcff84091ba2434b7758416b0a48186<br /><br />After applying PR, the logo is not vertically centered.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26845">issues.joomla.org/tracker/joomla-cms/26845</a>.</sub>

**Comment by Quy** [comment]
It is centered for me in Firefox and Chrome on Windows. Please advise your browser.

**Comment by Quy** [comment]
@ciar4n Can you also look into this? Thanks.

**Comment by Quy** [comment]
Fixed in PR #28888

**Pull request closed without merging**
