### PR TITLE
[4][com_installer] update site location editable

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #33439 .

### Summary of Changes

make  update site location editable

### Testing Instructions
go to Extensions: Update Sites
edit an item (chnage something in the location field) and save
don't worry hitting rebuild the original one is restored

### Actual result BEFORE applying this Pull Request
 update site location not editable

### Expected result AFTER applying this Pull Request

 update site location editable

### CODE REVIEW

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 74f69e2b4f6e923163ade7f0d665532946cccb85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33460">issues.joomla.org/tracker/joomla-cms/33460</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 74f69e2b4f6e923163ade7f0d665532946cccb85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33460">issues.joomla.org/tracker/joomla-cms/33460</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33460">issues.joomla.org/tracker/joomla-cms/33460</a>.</sub>

**Comment by brianteeman** [comment]
I am not convinced yet that it was intended for this field to be editable<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33460">issues.joomla.org/tracker/joomla-cms/33460</a>.</sub>

**Comment by richard67** [comment]
> I am not convinced yet that it was intended for this field to be editable

Me neither => ~~Setting the RLDQ (Release Lead Decision Queue) label and~~ pinging the guys of Glip for discussion.

**Comment by richard67** [comment]
~~Does anyone know that that "Edit" button shall be good for? Can it be that it is for editing product keys for the extra query for extensions where the update site provides such keys?~~

Update: After reading the comments in issue #33439 it's clear to me. Now I'm not sure if this PR here solves all aspects of the issue or if there should be done more, like changing the button text from "Edit" to something more telling.

**Comment by richard67** [comment]
What sense does it make to edit the location field? Won't it be overwritten with the next rebuild of update sites? Are we triggering that rebuild automatically in some cases? Or does it only happen if someone uses the button for that? In the first case, editing the field would not make much sense, would it?

**Comment by joomdonation** [comment]
The Location of update site is defined in the manifest file of the extension https://docs.joomla.org/Manifest_files#Update_servers and should not be editable (it will be updated when we rebuild update sites for example). If it is needed, we can change code so that if there is no data for extra query, the save buttons can be removed (since there is no change to save). And in that case, maybe change page title from **Edit Update Site** to **View Update Site**. At of right now, this PR should not be RTC.

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33460">issues.joomla.org/tracker/joomla-cms/33460</a>.</sub>

**Comment by alikon** [comment]
> What sense does it make to edit the location field? 

suppose you have installed extA wich follow the j update ie have an update server link in the extension manifest
now suppose the extension developer change that link for whatever reason...and provide a new one for extA
with this pr the end user can simply change that

**Comment by joomdonation** [comment]
@alikon If an extension changes it update server, it should not ask every user to change it manually. It should be updated automatically during upgrade process (I'm a bit surprise that it is not updated automatically by Joomla while updating the extension - mean developer will have to write some script to update).

**Comment by richard67** [comment]
@alikon The update site location should not be editable in backend. If it really needs a manual correction by a site admin, then this site admin should have the knowledge to make this correction directly in database. So I would prefer if this PR here was closed.

**Comment by alikon** [comment]
let me disagree on this
and in the hope that site  admin are skilled

**Pull request closed without merging**
