### PR TITLE
Inconsistency in permission rules - configure options only

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes 
"Configure Options Only" makes me think .. why only?
 
grafik

Change the String to "Configure Options"

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 125143e1467004884d98ac32501d5ca0867562cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38781">issues.joomla.org/tracker/joomla-cms/38781</a>.</sub>

**Comment by brianteeman** [comment]
Not at my pc but please check template manager. Iirc this string comes from there where you could have access to options but not other restricted items. Unlike all other components

**Comment by chmst** [comment]
The string is used in permissions of the template manager. But still correct when the "only" is removed.

If core.options has another meaning in template management than in other components, we better should define an specified action. 

grafik

**Comment by brianteeman** [comment]
Now that I am at my pc I can see that what was originally just a template manager permission is now everywhere and that the problem is not so much the word "only" but that there is a column missing in the users permissions view. "Configure ACL and Options"

**Comment by brianteeman** [comment]
Looking at the issue I just created #38830 I can see that the problem here arises from your pr #37807 which moved core.admin (Configure ACL and Options) out of the columns but did not also move core.options (Configure ACL Only)

In summary this is not the correct fix and it should be fixed together with #38830

**Comment by chmst** [comment]
Will check after my holidays. The problem occurs if no permissions are found on level >= 4.

**Comment by chmst** [comment]
> Looking at the issue I just created #38830 I can see that the problem here arises from your pr #37807 which moved core.admin (Configure ACL and Options) out of the columns but did not also move core.options (Configure ACL Only)
> 
> In summary this is not the correct fix and it should be fixed together with #38830

https://github.com/joomla/joomla-cms/issues/38830 is resolved with https://github.com/joomla/joomla-cms/pull/38960. PR https://github.com/joomla/joomla-cms/pull/37807 did not import a bug but made an old error visible. 
In summary this issue has nothing to do with the above PRs.

**Comment by brianteeman** [comment]
Sorry for mistaking that error.

While I agree that in the debug user permissions view it _might_ not be needed removing it from the permissions table does change its meaning.

image

**Comment by chmst** [comment]
I don't insist in changing the label, but I see a logical error in the permission rules. As a user and only from labels I think:


Configure everything | Configure options only  |  result
-----------------------------------------------------------------------------
         yes         |       yes               |   configure everything but for what do we need  options only?
         yes         |       no                |   configure eeryting but don't configure options only (!)
         no          |       yes               |   configure nothing but configure options only (!)
         no          |       no                |   configure nothing but for what do we need  options only?



The follwing would be correct but must be checkd in the whole core 

```

Configure ACL | Configure options       | result
-----------------------------------------------------------------
         yes  |       yes               | configure everything
         yes  |       no                | configure ACL only 
         no   |       yes               | configure options only
         no   |       no                | configure nothing
```

**Comment by brianteeman** [comment]
There isn't a configure acl only option

(maybe there should be)

**Comment by chmst** [comment]
This is what I wanted to demonstrate. Configure ACL and Configure Options would be better. But this is a bigger task and surely not for J4.

**Comment by brianteeman** [comment]
Agreed.

Originally the  "configure options only" was a _hack_ for joomla.com in com_templates when it was at siteground iirc

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 125143e1467004884d98ac32501d5ca0867562cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38781">issues.joomla.org/tracker/joomla-cms/38781</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38781">issues.joomla.org/tracker/joomla-cms/38781</a>.</sub>

**Comment by tecpromotion** [comment]
The change was unfortunately not made consistently in the API.
https://github.com/joomla/joomla-cms/blob/4c918795a083cc03a808c02920f7d06093b26b15/api/language/en-GB/joomla.ini#L167

PR #39682 will fix this.

**Pull request merged**
