### PR TITLE
Responsive Issues on different screen sizes #33717

### PR DESCRIPTION
**Pull request by deveshprasad**
Pull Request for Issue #33717.

### Summary of Changes

Added Y-axis margin to both the buttons as individual will affect its alignment vertically.
(I have asked on my previous pull request #33824 regarding the method to use as the button.scss file is creating error so followed bootstrap margin)

### Testing Instructions

Go to the Post Installation Messages page.

### Actual result BEFORE applying this Pull Request

13 05 2021_15 45 42_REC

### Expected result AFTER applying this Pull Request

13 05 2021_20 50 17_REC

### Documentation Changes Required

No

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9edac5a25caf2061c60e8dad0b8263b2eebb4bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33893">issues.joomla.org/tracker/joomla-cms/33893</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on 9edac5a25caf2061c60e8dad0b8263b2eebb4bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33893">issues.joomla.org/tracker/joomla-cms/33893</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33893">issues.joomla.org/tracker/joomla-cms/33893</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
This is the wrong approach and should not have been merged. You dont solve a responsive issue by adding a global class. please see #33899

**Comment by brianteeman** [comment]
By using the correct code you do not need to keep adding classes to buttons.  Using only #33899 this is fixed correctly

image

**Pull request merged**
