### PR TITLE
[4.0] Language Switcher: correcting dropdown when no flags

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says. Modifying class.

### Testing Instructions
Create a multilingual site with the sample data (2 languages minimum).
Edit mod_languages settings to:

Screen Shot 2021-04-09 at 09 24 41

Display the switcher in frontend

### Actual result BEFORE applying this Pull Request

Screen Shot 2021-04-09 at 09 08 14

### Expected result AFTER applying this Pull Request

Screen Shot 2021-04-09 at 09 02 27

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0f81a23e3cec42915c9a24affa5b5ff6097f6762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33076">issues.joomla.org/tracker/joomla-cms/33076</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0f81a23e3cec42915c9a24affa5b5ff6097f6762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33076">issues.joomla.org/tracker/joomla-cms/33076</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33076">issues.joomla.org/tracker/joomla-cms/33076</a>.</sub>

**Comment by infograf768** [comment]
@joomla/cms-maintainers 
Please merge. I have another pr to do for the switcher. tks.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
