### PR TITLE
Converts the authentication plugins to service providers

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Converts the authentication plugins to service providers.

### Testing Instructions
Log in on the back and front end. If possible also with Ldap.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
Except ldap I could not test, the rest work okay. Let me kown if the notice message is important enough...if not I can mark the test successfully

**Comment by laoneo** [comment]
The notice should be fixed with the last commit. Thanks for reporting.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 558f6dda8738d816f92963fed45eaa7e6167c583<br /><br />Remember clean autoload_psr4.php cached after apply the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39624">issues.joomla.org/tracker/joomla-cms/39624</a>.</sub>

**Comment by laoneo** [comment]
@tatankat can you test this one here as well as it converts the ldap auth plugin to service provider?

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on c6c61b441535495599e398caff61415d94457611<br /><br />* the LDAP was not tested for actually authenticating (I don't have LDAP locally)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39624">issues.joomla.org/tracker/joomla-cms/39624</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39624">issues.joomla.org/tracker/joomla-cms/39624</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo for the PR!

**Comment by tatankat** [comment]
A bit too late for the party, but I can confirm ldap works as it should. Thanks for also updating the ldap plugin.

**Pull request merged**
