### PR TITLE
Update jQuery autocomplete to 1.2.18

### PR DESCRIPTION
**Pull request by C-Lodder**
### How to test
1. Enable the Smart Search (mod_finder) module
2. Ensure the **Search Suggestions** is set to **Show**
3. In the frontend, type a word in the search input field
### Expected result

A dropdown will appear with associated results as shown in the image below

search

### CODE REVIEW

**Comment by n9iels** [comment]
Can you please add some test instructions?

**Comment by C-Lodder** [comment]
@n9iels - Oops. I've added some test instructions

**Comment by n9iels** [comment]
@test when I type "componen" I get the same results as the screenshot. When I type "component" I get no suggested results.

**Comment by bertmert** [comment]
> When I type "component" I get no suggested results.
Identical behavior before and after patch. (Try "install", too. Same thing. No "installation" etc.). I don't know...

@test Success concerning jQuery update. Same results/suggestions before and after patch.
Only english content tested.

**Pull request merged**
