### PR TITLE
[4.0] Wrong toolbar preferences for com_contact

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
com_contact Options toolbar loads com_menus  preferences instead of com_contact

### Testing Instructions
Display Contacts Manager and click on the Options button before and after patch

can be merged on review

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b9891a7c3e0376a301858660794b757f09076410<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24014">issues.joomla.org/tracker/joomla-cms/24014</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b9891a7c3e0376a301858660794b757f09076410<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24014">issues.joomla.org/tracker/joomla-cms/24014</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24014">issues.joomla.org/tracker/joomla-cms/24014</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
