### PR TITLE
[4.0]  "Call to a member function getRegistry() on null" error 

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes error in articles and featured articles lists in backend.

### Testing Instructions

Enable Workflow in com_content configuration.
View article/featured article list in backend.

### Actual result BEFORE applying this Pull Request

Error.

### Expected result AFTER applying this Pull Request

No error.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ceford** [comment]
I had a look at this and don't see any error, either directly in the Featured Articles list or in the html source. There is something fishy: I have Workflow Enable set to No in Options / Transitions (after having it previously set to Yes for some other test). The Featured Articles list Actions dropdown shows Run Transitions links but they don't do anything. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29850">issues.joomla.org/tracker/joomla-cms/29850</a>.</sub>

**Comment by SharkyKZ** [comment]
@ceford You're right. Workflows need to be enabled. I'll update testing instructions.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on d240040e315a83abde51e7701ade44f8a34f99f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29850">issues.joomla.org/tracker/joomla-cms/29850</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
