### PR TITLE
Temp#30018

### PR DESCRIPTION
**Pull request by NikitaEmberi**
Pull Request for Issue # 30018

### Summary of Changes

Changed fontawesome.min.css by removing :
- .icon-download::before{
   content: " "
}
-.icon-list::before{
  content: " "
}
-.icon-share-alt::before{
  content:" "
}

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### CODE REVIEW

**Comment by drmenzelit** [comment]
@NikitaEmberi I think something went wrong with your PR, it is showing more then 5.000(!) changed files, that is impossible to check. Please try again and check that only the really modified files are being committed.
If you remove the content from the icons that would probably affect other parts of Joomla, where these icons are being used.

**Comment by NikitaEmberi** [comment]
I cloned joomla-3 and in the process of updating to joomla-4 it happened. I'll try again.

**Comment by drmenzelit** [comment]
That is not the right way, you should clone Joomla and checkout the 4.0 branch

**Comment by infograf768** [comment]
In any case, as @drmenzelit said, the solution proposed would have unwanted effects.

See a solution here
https://github.com/joomla/joomla-cms/issues/30018#issuecomment-801730769

**Comment by NikitaEmberi** [comment]
So @infograf768 sir I have to clone install-from-web-server repository, make changes there and open a pull request on "install-from-web-server" repository right?

**Pull request closed without merging**
