### PR TITLE
[4.0] Use the namespaced Form class in the fields plugin functions

### PR DESCRIPTION
**Pull request by laoneo**
Use the namespaced Form class in the fields plugin functions.

### Testing instructions
Create a custom field.

### Expected result
Field is created.

### Actual result
Field is created.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 89a26319bbe1e898b772e5ef709413df38e871e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22865">issues.joomla.org/tracker/joomla-cms/22865</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 839f45af93eefb2267cece06b6c094bf38da91a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22865">issues.joomla.org/tracker/joomla-cms/22865</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 839f45af93eefb2267cece06b6c094bf38da91a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22865">issues.joomla.org/tracker/joomla-cms/22865</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22865">issues.joomla.org/tracker/joomla-cms/22865</a>.</sub>

**Pull request merged**
