### PR TITLE
[4] Remove J prefix from Class name

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on bafe8a3d06231fc8be8167f77c523b009b73f738<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35133">issues.joomla.org/tracker/joomla-cms/35133</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bafe8a3d06231fc8be8167f77c523b009b73f738<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35133">issues.joomla.org/tracker/joomla-cms/35133</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35133">issues.joomla.org/tracker/joomla-cms/35133</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
