### PR TITLE
Include user.css in error page protostar

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #25286 

### Summary of Changes
Load user.css on protostar error page on if needed.

### Testing Instructions
create a user.css in the css folder of protostar
trigger a 404 error page

### Expected result
user.css gets loaded

### Actual result
user.css not loaded

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 96891308acbd71e5e69b36de0fcf5c1b1f931c7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25416">issues.joomla.org/tracker/joomla-cms/25416</a>.</sub>

**Comment by SharkyKZ** [comment]
It should be the last CSS file loaded.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 62ff4951141589723a2d6122d9d44b722d1e32a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25416">issues.joomla.org/tracker/joomla-cms/25416</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 62ff4951141589723a2d6122d9d44b722d1e32a5<br /><br />user.css is included in error page if there's user.css file in css folder
user.css not included if there's no user.css file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25416">issues.joomla.org/tracker/joomla-cms/25416</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25416">issues.joomla.org/tracker/joomla-cms/25416</a>.</sub>

**Pull request merged**
