### PR TITLE
[4.0] Change the readme to reflect the latest changes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### CODE REVIEW

**Comment by Bakual** [comment]
Imho either have a doc page (https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment) and link to that from here or explain it in the readme here. But don't do it in two places as one will be outdated soon this way.

**Comment by dgrammatiko** [comment]
I think this info belongs here. Migrating, languages etc that is currently in the readme is totally irrelevant with the source code.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/21217#issuecomment-406975038

**Comment by brianteeman** [comment]
Before any of the new text I would suggest and link to that you can download and install a complete installation from d.j.o nightly build

**Comment by Bakual** [comment]
> I think this info belongs here.

I'd prefer the docs page. It's more complete and a readme should explain what the project in the repo is, not provide a documentation about it itself. And especially don't duplicate documentation. It's hard enough to keep one place updated.

**Review by brianteeman — APPROVED** [review]
language ok

**Comment by wilsonge** [comment]
I've added a link to the docs and merging this

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
