### PR TITLE
Featured contacts

### PR DESCRIPTION
**Pull request by brianteeman**
Make featuring a contact similar to featuring an article.
Currently you can only make a contact featured from the contact view but with articles you can do it from the article AND articles view
#### Summary of Changes

Added Feature/Unfeature toolbar buttons
Merged feature column into status column (like with articles)
Reordered dropdown filters to match the column ordering 
#### Testing Instructions

Make sure that you can feature/unfeature a contact and sort by featured

### CODE REVIEW

**Comment by sovainfo** [comment]
I have tested this item :white_check_mark: successfully on 698b97f0bf3dd93c2ce572f2fafb00da94dd9c56<br /><br />Works as designed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10738">issues.joomla.org/joomla-cms/10738</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10738">issues.joomla.org/joomla-cms/10738</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 698b97f0bf3dd93c2ce572f2fafb00da94dd9c56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10738">issues.joomla.org/joomla-cms/10738</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks for testing <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10738">issues.joomla.org/joomla-cms/10738</a>.</sub>

**Comment by sovainfo** [comment]
Not too late for J360, I hope!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10738">issues.joomla.org/joomla-cms/10738</a>.</sub>

**Comment by brianteeman** [comment]
That's up to @wilsonge

**Pull request merged**
