### PR TITLE
[4.2] remove php open close tags

### PR DESCRIPTION
**Pull request by brianteeman**
code review

This is a redo of #38484

### CODE REVIEW

**Comment by richard67** [comment]
For some reason this PR doesn't appear in the issue tracker so I can't mark a test result.

**Comment by richard67** [comment]
Now it appears but has no "Test this" button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38495">issues.joomla.org/tracker/joomla-cms/38495</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
For some reason the issue tracker doesn't show this PR as a PR, i.e. it looks like an issue there, and there is no "Test this" button and no way to set RTC.

Setting the RTC label here since this PR has 2 good code reviews.

I have observed in past that the issue tracker sometimes has problems when several PRs are created at the same time or in a very short time period.

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
