### PR TITLE
[4.4.0] Fix condition for menuitems

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Fix a condition in saving a menu item. 

### Testing Instructions
On a fresh 4.4.0 install testing sample data. 

### Actual result BEFORE applying this Pull Request
grafik

Installation breaks.

### Expected result AFTER applying this Pull Request
Installation works. 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
as this is a backport of #41500 lgtm

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 5d2a0e68e2d8c3ae6f804623761fe730e6e954cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42157">issues.joomla.org/tracker/joomla-cms/42157</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5d2a0e68e2d8c3ae6f804623761fe730e6e954cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42157">issues.joomla.org/tracker/joomla-cms/42157</a>.</sub>

**Comment by Fedik** [comment]
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42157">issues.joomla.org/tracker/joomla-cms/42157</a>.</sub>

**Pull request merged**
