### PR TITLE
[4.3] Guided Tours search by note

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
All components that have a note field allow you to search by the value of the note. This was missed in com_guidedtours

### Testing Instructions
Add a string into the note field for a tour 
Search for that string in the list view

Repeat for steps

### Actual result BEFORE applying this Pull Request
No matching results

### Expected result AFTER applying this Pull Request
Matching results

image

This is not a new feature. It is a bug that it was not implemented

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Please add note to filter search description.

40607-note

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 17bf4bf0abc911526d0e6ac60d4e42badd736203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40607">issues.joomla.org/tracker/joomla-cms/40607</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 17bf4bf0abc911526d0e6ac60d4e42badd736203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40607">issues.joomla.org/tracker/joomla-cms/40607</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40607">issues.joomla.org/tracker/joomla-cms/40607</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the missing note search

**Pull request merged**
