### PR TITLE
[4.0] article news module

### PR DESCRIPTION
**Pull request by brianteeman**
Add the switcher class to the triggerevent option

### Before
screenshotr21-46-50

### After
screenshotr21-49-22

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 96d63c3f95507c031c9e017df87c634eca062b29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17210">issues.joomla.org/tracker/joomla-cms/17210</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 96d63c3f95507c031c9e017df87c634eca062b29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17210">issues.joomla.org/tracker/joomla-cms/17210</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
