### PR TITLE
[5.0][Events] Event classes for Actionlog, Cache, Contact, Checkin components

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Event classes for Actionlog, Cache, Contact components

Affected events:

- [x] onAfterLogPurge (Actionlog)
- [x] onAfterLogExport (Actionlog)
- [x] onAfterPurge (Cache)
- [x] onValidateContact (Contact)
- [x] onSubmitContact (Contact)
- [x] onAfterCheckin (Checkin)

### Testing Instructions

Use Actionlog, Cache, Contact components. Clean cache, submit contact form, Checkin.

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/Plugin/Events
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
do you think it's good that we have the same event class for purge and purge group?

PurgeGroup could be abstracted from the purge event and add the information (group) as argument?

**Comment by Fedik** [comment]
I think it is okay, they doing basicaly the same. I would not make it more complicated. 
As I see, this event mostly used only for logging.

**Comment by Fedik** [comment]
I think it is okay, they doing basicaly the same. I would not make it more complicated. 
As I see, this event mostly used only for logging.

**Comment by HLeithner** [comment]
Merging this as with code review and based on the other similar PRs, before beta1 to get enough feedback for final release.

Additional, we need to deprecate the referenced arrays, so we can remove the workaround in J 7.0

**Pull request merged**
