### PR TITLE
Banner Tracks background

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #15269

I cant see any reason for the active class to be green and I cant find any other use of it so I simply removed the class from the template

Unless anyone has any better idea

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 30731ed6e2ccfdde603efbcf28e9824eab020c0c

Theres also a Alignment-Issue ("Begin date" and "End date" are not vertical aligned) :
screenshot-2017-10-4 banners tracks - 3 - administration

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18231">issues.joomla.org/tracker/joomla-cms/18231</a>.</sub>

**Comment by C-Lodder** [comment]
@brianteeman - can you also use the code I provided in this PR to: https://github.com/joomla/joomla-cms/issues/15269#issuecomment-321070910

cause currently you're only addressing half of it.

**Comment by brianteeman** [comment]
@C-Lodder what is not addressed?

screenshotr16-23-27

**Comment by C-Lodder** [comment]
The margin:

a2d10e96-1f89-11e7-85c7-134b6fc5e497

You're also editing the BS CSS file in this PR which shouldn't be done

**Comment by brianteeman** [comment]
Ah I see the margin now. was hard to see on my screen as it was on a second row.

The only file i edited was  media/jui/less/forms.less

**Comment by C-Lodder** [comment]
In which case this should be done at template level. If you edit `media/jui/less/forms.less`, you to modify the `bootstrap.css` which should *never* happen

**Comment by brianteeman** [comment]
re the margin
your code was not correct as it is set here https://github.com/joomla/joomla-cms/blob/staging/media/jui/css/jquery.searchtools.css#L63

**Comment by C-Lodder** [comment]
Hmm worked fine for me

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09f1fdcd1ec2e910008f94c342d88b4e390dd58d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18231">issues.joomla.org/tracker/joomla-cms/18231</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 09f1fdcd1ec2e910008f94c342d88b4e390dd58d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18231">issues.joomla.org/tracker/joomla-cms/18231</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by mbabker** [comment]
Before I merge, I have to ask since this is changing the Bootstrap stuff.  Is there anywhere else this combination of classes is used producing the green display?

**Comment by brianteeman** [comment]
I couldnt find any

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
