### PR TITLE
Make sure automatic title is enabled by default like we had it in 2.5

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomlagerman/joomla/issues/437

### Summary of Changes

Make sure automatic title is enabled by default like we had it in 2.5

### Testing Instructions

[Install this branch](https://github.com/zero-24/joomla-cms/archive/autotitle.zip) and confirm that the setting Automatic Title is enabled for `Popular Articles`, `Recently Added Articles` & `Logged-in Users`

### Expected result

The setting is enabled and shows the generated title instead of the default.

### Actual result

The setting is disabled and just the original title is displayed.

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am assuming this is related to the admin modules

IIRC it was a deliberate decision not to make them automatic and as you say it has been the case since 3.0

Note that the only reason for the automatic title was to allow the language to change automatically and the admin modules now support languages correctly

**Comment by zero-24** [comment]
How can a language pack do/use this? Thanks

**Comment by brianteeman** [comment]
it is defined in the helper for the module - best to read the code as you will understand it better than I can explain it

**Comment by Bakual** [comment]
> IIRC it was a deliberate decision not to make them automatic and as you say it has been the case since 3.0

As for the history:
* J3 didn't have the "automatic title" feature anymore (that one which dynamically says "Last 5 articles" instead of "Last articles").
* With 3.4.2 (https://github.com/joomla/joomla-cms/pull/5793), the installation SQL file got adjusted to reflect that.
* With 3.5.0, the feature was reintroduced (https://github.com/joomla/joomla-cms/pull/7925), but the installation SQL didn't get changed back.

Thus all sites created prior to 3.4.2 have the automatic title enabled by default and translation (which is a nice sideeffect) works. Sites created after 3.4.2 have it disabled.

> it is defined in the helper for the module - best to read the code as you will understand it better than I can explain it

If you refer to the `getTitle` function in the helper, that's exactly what this PR tries to enabled. That method is only called if `automatic_title` is enabled.

**Comment by brianteeman** [comment]
For me the main problem with the automatic titles is that they are not intuitive and they do not reflect the entry in the title field. So if automatic titles was enabled by default the user is confused why the title of the module doesnt reflect what is output on the screen.

I can't find it right now but i had an issue to remove this functionality completely but someone pointed it out its use in multilingual sites and it was rejected. As we can now have language specific modules its no longer the only option

**Comment by SharkyKZ** [comment]
If this is accepted, make the changes in module files, not in SQL files, please.

**Comment by infograf768** [comment]
@zero-24 
I know why it was taken off in the first place. **It was an accident when a PR by Kyle was merged.**
I quote Hannes in https://groups.google.com/forum/#!msg/joomla-dev-cms/0P6NMtWnYeE/vap2bdgeB0AJ :
"It was most likely removed by accident while the backend was rewritten
to Bootstrap code. The commit where this was removed has more than 300
files and several thousand changed lines of code. The feature was part
of a view file that was overwritten, but the option was not removed from
the XML files of the modules. "

Once enabled in the Advanced tab of the modules concerned, it works like a charm.
The strings exist in all language packs. Example for mod_logged.
```
MOD_LOGGED_TITLE="Last Logged-in Users"
MOD_LOGGED_TITLE_1="Last Logged-in User"
MOD_LOGGED_TITLE_MORE="Last %s Logged-in Users"
```
Imho, it is a nice effect and saves creating similar modules for each language installed.

screen shot 2018-08-01 at 08 25 04

screen shot 2018-08-01 at 08 28 48

I am in favour of re-introducing it by default in joomla.sql

**Comment by brianteeman** [comment]
No dispute it can be useful but I would not make it the default after all these years.

**Comment by Bakual** [comment]
> If this is accepted, make the changes in module files, not in SQL files, please.

The SQL files are the correct place to set the initial values for new installations. If you change the default values in the modules it would change behavior on existing sites if they haven't stored the parameters.
So this PR is correct in that regard.

**Comment by zero-24** [comment]
@mbabker can you take a look here and share your thoughts about this one?

**Comment by mbabker** [comment]
Never used the feature so have no opinion either way.  But if it's been turned off for the entirety of 3.x we shouldn't turn it on now.

**Comment by zero-24** [comment]
Ok I'm going to check if there is a way to override that in the language pack full install and close this here. Thanks!

**Pull request closed without merging**
