### PR TITLE
[4.0] Sample Data not available message

### PR DESCRIPTION
**Pull request by brianteeman**
If no sample data plugins are enabled the message displayed was very generic. This PR adds a more informative message. Hopefully this message will also be usable if/when the plugins are updated to not be displayed if they can not be installed eg if there is already content on the site

### Before
chrome_2018-06-13_22-53-03

### After
chrome_2018-06-13_22-54-24

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 8d7c225b56a5105ab34fa69d072c5e0cdf022086<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20744">issues.joomla.org/tracker/joomla-cms/20744</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d7c225b56a5105ab34fa69d072c5e0cdf022086<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20744">issues.joomla.org/tracker/joomla-cms/20744</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20744">issues.joomla.org/tracker/joomla-cms/20744</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
