### PR TITLE
[4.0] Cs fix

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Small CS fix, see https://github.com/joomla/joomla-cms/pull/32960#issuecomment-814624792

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on d0d1821b5c5724c4e66b5250a47b0379e4bfc307<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33046">issues.joomla.org/tracker/joomla-cms/33046</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d0d1821b5c5724c4e66b5250a47b0379e4bfc307<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33046">issues.joomla.org/tracker/joomla-cms/33046</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33046">issues.joomla.org/tracker/joomla-cms/33046</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
