### PR TITLE
[4.1] Fix the SCSS file paths

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36872.

### Summary of Changes

- The SCSS files delivered in the templates have wrong paths due to the source moved in the `build` folder, so we have to patch them.
- Fixes the Atum imports pointing at the node_modules resources

### Testing Instructions
Before applying this PR try:
- `npm run build:css -- media/templates/site/cassiopeia/scss`
- `npm run build:css -- media/templates/administrator/atum/scss`

Both commands will fail because the paths are wrong.

Apply this PR and rerun the commands:
- `npm run build:css -- media/templates/site/cassiopeia/scss`
- `npm run build:css -- media/templates/administrator/atum/scss`

### Documentation Changes Required

No

### CODE REVIEW

**Comment by Quy** [comment]
Please fix conflicts.

**Comment by HarshJaiswani** [comment]
I have tested this item :white_check_mark: successfully on 4351d25f0a9c42eaea2279cfc45aa6f10f88fe05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36879">issues.joomla.org/tracker/joomla-cms/36879</a>.</sub>

**Comment by Aman21591** [comment]
I have tested this item :white_check_mark: successfully on 4351d25f0a9c42eaea2279cfc45aa6f10f88fe05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36879">issues.joomla.org/tracker/joomla-cms/36879</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36879">issues.joomla.org/tracker/joomla-cms/36879</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
