### PR TITLE
[4.0] Composer update joomla/database

### PR DESCRIPTION
**Pull request by twister65**
### Summary of Changes
`composer update joomla/database`
This will update the joomla/database framework to the latest version.

### CODE REVIEW

**Comment by mbabker** [comment]
How are you doing these updates?  The lock file diff shows a bunch of other metadata updates and no hash update.

I don’t doubt you’re using `composer update` to do these things, but something hasn’t looked right in these PRs for some reason.

**Comment by twister65** [comment]
@mbabker, I don't know why. I just sent you an invitation. Could you do it please?

**Comment by wilsonge** [comment]
So FWIW on latest composer 1.9.3 and 1.9.0 - if I run `composer update joomla/database` then I don't get the metadata changes - but I also do not get a content-hash update :/

**Comment by twister65** [comment]
With version 1.9.3 of composer, if I run `composer update --interactive` and type `joomla/database` for the name of the package, I get this result. That's exactly what I did.

**Comment by mbabker** [comment]
I just double checked, `content-hash` is a hash of `composer.json`.  All this time I thought it had to do with the state of the lock file 🤦‍♂

**Comment by wilsonge** [comment]
Cool. Then we should be good here. Today I learnt too :)

**Pull request merged**
