### PR TITLE
[4.0] Admin mod-login styling updates

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

1. Login page now based on flexbox
2. Remove inline CSS
3. Move JS to separate file
4. Fix styling for language dropdown

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@C-Lodder you still need to wrap the code with:
```js
document.addEventListener(`DOMContentLoaded`, function() {
yourCodeHere
});
```
untill we manage to append those scripts at the bottom of the page instead of the head

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5f05a3dbde8317b810006142f8388c2d72a95b12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19087">issues.joomla.org/tracker/joomla-cms/19087</a>.</sub>

**Comment by C-Lodder** [comment]
@dgt41 - Those scripts are already at the bottom of the DOM ;) https://github.com/joomla/joomla-cms/pull/19087/files#diff-e9274ec084960b677e0f46fac1b1a531L119

**Comment by dgrammatiko** [comment]
@C-Lodder one beer from me to whomever did that 🎉

**Comment by C-Lodder** [comment]
@dgt41 - Grab yourself a beer then :) https://github.com/joomla/joomla-cms/pull/17024/files#diff-e9274ec084960b677e0f46fac1b1a531R114

**Comment by anuragteapot** [comment]
Are bottom links are removed from mobile view??
screen shot 2017-12-17 at 07 52 15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19087">issues.joomla.org/tracker/joomla-cms/19087</a>.</sub>

**Comment by C-Lodder** [comment]
@Anu1601CS correct

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 5f05a3dbde8317b810006142f8388c2d72a95b12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19087">issues.joomla.org/tracker/joomla-cms/19087</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
