### PR TITLE
[4] add missing imported namespaced classes

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4] add missing imported namespaced classes - code review

### CODE REVIEW

**Comment by joomdonation** [comment]
You will hate me: For comment, docblock, I prefer using fully qualified class name instead of un-necessary use statements.

**Comment by PhilETaylor** [comment]
Done.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on bcbde8866ad913ab5cb1ac545ea3d2f8dca29574<br /><br />Thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34037">issues.joomla.org/tracker/joomla-cms/34037</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bcbde8866ad913ab5cb1ac545ea3d2f8dca29574<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34037">issues.joomla.org/tracker/joomla-cms/34037</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34037">issues.joomla.org/tracker/joomla-cms/34037</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
