### PR TITLE
Add icon to parent category in article details

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #37913 .

### Summary of Changes
An icon is added to parent category

### Testing Instructions
see #37913.
Make article in an category on level 2 and set the param Parent Category to yes.

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f05b203dd3034e7304fe0e00975bd46ec10db1f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38017">issues.joomla.org/tracker/joomla-cms/38017</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f05b203dd3034e7304fe0e00975bd46ec10db1f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38017">issues.joomla.org/tracker/joomla-cms/38017</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38017">issues.joomla.org/tracker/joomla-cms/38017</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
