### PR TITLE
[4.0] Ensure path contains api in the router

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
When the live_site attribute is set in the Joomla configuration.php file, then all API requests do fail with a 404 "Resource not found" error.

### Testing Instructions
Lets assume the website runs on http://joomla.box/cms4 (in your case use your own url).
- Set the live site parameter in the configuration.php file to http://joomla.box/cms4
- Make a get request with the bearer token to the following url http://joomla.box/cms4/api/index.php/v1/content/articles

### Actual result BEFORE applying this Pull Request
404 error

### Expected result AFTER applying this Pull Request
List of articles with a 200 return code

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 743cbe6f0191f92322bbd24724e9710fae3351a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36315">issues.joomla.org/tracker/joomla-cms/36315</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 743cbe6f0191f92322bbd24724e9710fae3351a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36315">issues.joomla.org/tracker/joomla-cms/36315</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 743cbe6f0191f92322bbd24724e9710fae3351a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36315">issues.joomla.org/tracker/joomla-cms/36315</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36315">issues.joomla.org/tracker/joomla-cms/36315</a>.</sub>

**Comment by wilsonge** [comment]
Isn't it a better/more consistent fix to add the same thing we have for the administrator app https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Uri/Uri.php#L151-L157 for the api app?

**Comment by laoneo** [comment]
I never liked the dependency of Uri to to an app. But if you want me to add there another if block, then I can do it. All I want is to make the api actually work with the live site parameter.

**Comment by wilsonge** [comment]
I'm not against moving things around (but if I was doing that I'd probably be using the application to seed the base url/path into Uri rather than having them duplicating them determining URLs). But I think that would be for a minor version. For a patch version consistency is probably the best course of action.

**Comment by laoneo** [comment]
@wilsonge made it with Uri.

**Comment by wilsonge** [comment]
Fine by me. Can you update your base branch please so that the API tests run through just as a sanity check.

**Comment by laoneo** [comment]
The failing tests have nothing to do with the pr as they are date related.

**Comment by wilsonge** [comment]
Yeah before the API tests weren't starting because it was behind (and Harald's been doing drone system test work). Obviously fine now!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
