### PR TITLE
Routing: Legacy Router Rule for com_contact

### PR DESCRIPTION
**Pull request by Hackwar**
This implements the current routers behavior of com_contact as a legacyrouter. This is meant for those that want to keep the old behavior at all costs. Later, parameters will be introduced to switch between the legacy behavior and new features.

This router is copied verbatim from the current router to make sure that the same behavior is kept. No changes should be done to it until Joomla 4.0, when this is supposed to be deleted. The component routers right now are so fragile, that a slow transition will be next to impossible. To prevent any breaks in backwards compatibility, this legacy router is introduced, so that people having problems with the new router can switch back.
### How to test
1. Check your site before applying the patch and see the URLs of com_contact.
2. Apply the patch.
3. See the URLs of com_contact to stay the same.
### Dependencies

This PR requires #5446 to be accepted by the project before it can be applied.

This was made possible through the generous donation of the people mentioned in the following link via an Indiegogo campaign: http://joomlager.de/crowdfunding/5-contributors

### CODE REVIEW

**Comment by paternax** [comment]
tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5502">issues.joomla.org/joomla-cms/5502</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5502">issues.joomla.org/joomla-cms/5502</a>.</sub>

**Comment by Hackwar** [comment]
This is not RTC, since first #5444 needs to be merged and then this needs some slight modifications.

**Comment by zero-24** [comment]
Thanks @Hackwar moving back to pending. This also needs to be updated to staging as github say we have merge problems. Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5502">issues.joomla.org/joomla-cms/5502</a>.</sub>

**Comment by Hackwar** [comment]
This has been updated to work with the latest implementation of JComponentRouterView. Please test.

**Comment by Bakual** [comment]
@Hackwar Looks like you messed up something in this PR. Please check.

**Comment by Hackwar** [comment]
No, this is expected. The original PR was from a time where no 3.5-dev branch existed. Since the basic classes were merged into the 3.5-dev branch, I had to pull in the 3.5-dev branch into this one to make everything work. Since we can't switch branches for PRs after they have been created, I can't correct that. But overall, this is perfectly fine this way.

**Comment by Bakual** [comment]
Same as in the other one. Please close this PR and create a new PR from this branch against 3.5-dev. then.

**Comment by Hackwar** [comment]
Same as in the other PR: no.

#5444 was against staging and was merged by you guys into 3.5-dev. The other PRs are depending on that code and thus I need to merge that code into this PR. I did discuss this with George. I know how to use git and this here was the reason why I proposed to use a different branching scheme than the current one.

If we were to create a branch for the current minor release and let people create bugfixes against that branch instead of creating a branch for the NEXT minor release and thus force ALL PRs that are meant to go into a minor release to be closed and re-opened or manually merged, we could develope the future version of Joomla in staging and bug-releases would really just be bug-releases, because only serious issues/regressions would be solved by PRs that are targeted at the current minor release branch. But the way it is now, a feature that I'm working on (like for example the routing) would either have to be aimed at staging and then create this mess that we have right now, or you would have to open it against the next minor release branch, then see it not getting merged, close it, open it against the then next minor release branch, again not seeing it being merged, closing, re-opening and then hoping that people will finally get this.

**Comment by Hackwar** [comment]
I've combined the changes from this and all other routing related PRs into a new PR: #7615 Please review and comment in the new PR. I'm closing this one, so that we can focuse on the new PR.

**Pull request closed without merging**
