### PR TITLE
Fixes #8661. Regression: Broken ordering in com_newsfeeds

### LINKED ISSUE #8661: Regression - ordering broken in Newsfeed and Tags
Since the change to combine the two ordering selects into a single select (field plus direction) the ordering is completely broken

To test - install latest staging with sample data
Go to newsfeeds and try to sort by ID Ascending or ID Descending. The order should change but it doesnt
Go to tags and try to sort by ID or Title.  The order should change but it doesnt

### PR DESCRIPTION
**Pull request by ghost**
Issue: https://github.com/joomla/joomla-cms/issues/8661

Test:
Install latest staging with sample data
Go to newsfeeds and try to sort by ID Ascending or ID Descending. The order should change but it doesnt

Apply patch
Try again

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 67d00c60e84fd9da2a570cb9e9c74369abfbab11<br /><br />Works as described - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8670">issues.joomla.org/joomla-cms/8670</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 67d00c60e84fd9da2a570cb9e9c74369abfbab11<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8670">issues.joomla.org/joomla-cms/8670</a>.</sub>

**Comment by AshlinRejo** [comment]
I have tested this item :white_check_mark: successfully on 67d00c60e84fd9da2a570cb9e9c74369abfbab11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8670">issues.joomla.org/joomla-cms/8670</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8670">issues.joomla.org/joomla-cms/8670</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @bertmert and testers! Merged.

**Pull request merged**
