### PR TITLE
[4.0] Use ExtensionHelper::getExtensionRecord to get finder plugin ID

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Instead of writing code to query #__extensions table to get finder plugin ID, this PR uses our extension ExtensionHelper::getExtensionRecord library method to get ID of the plugin as agreed by @wilsonge  as https://github.com/joomla/joomla-cms/pull/34645#issuecomment-872780288

### Testing Instructions
1. Apply patch
2. Go to Extensions -> Plugins, disable **Content - Smart Search** plugin.
3. Access to Components -> Smart Search -> Index, there should be a warning message ask you to enable the plugin
4. Click on the link (see the screenshot), make sure the right plugin is opened on modal popup so that you can enable it

Smart-Search-Indexed-Content-Joomla-4-Administration

### Actual result BEFORE applying this Pull Request
Works, but more code than needed.

### Expected result AFTER applying this Pull Request
Works and less code to maintain.

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 1981f7ffee568c9a199787d62f36e598d5806e56<br /><br />Works like described.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34738">issues.joomla.org/tracker/joomla-cms/34738</a>.</sub>

**Comment by alikon** [comment]
on today 4.0-dev

> 3. Access to Components -> Smart Search -> Index, there should be a warning message ask you to enable the plugin

there is not

image

**Comment by joomdonation** [comment]
@alikon Did you disable the plugin **Content - Smart Search** ? That warning message will only be shown if the plugin is disabled.

**Comment by alikon** [comment]
yes i have disabled all finder plugins

**Comment by alikon** [comment]
ahh me silly not content smart search

**Comment by alikon** [comment]
anyway  when clicking  js error
image

**Comment by joomdonation** [comment]
Yes. Just realized that. It is because the modal is not loaded in empty state (happens before this PR, too).

If you index something, then empty state layout is not used and it should work well.

**Comment by alikon** [comment]
yeah , sure not depend  from your pr,  just discovered now me too 😃

**Comment by joomdonation** [comment]
@alikon Should be fixed in last commit

**Comment by alikon** [comment]
should'nt refresh  the return page after enabling the content - smart search plugin  ?

ie after clicking the link and enabling the content - smart search plugin  

it report that the plugin is still disabled

image

**Comment by joomdonation** [comment]
@alikon Yes. @dgrammatiko Could you please give instructions for refresh ?

**Comment by brianteeman** [comment]
we have this update and refresh problem in lots of places

**Comment by sakiss** [comment]
@joomdonation 
You can refresh the page after closing the modal, using a script like that, inside the modal:
```
document.addEventListener('DOMContentLoaded', function() {
	document.querySelector('#Modal_id').addEventListener('hide.bs.modal', function() {
	    window.parent.location.reload();
	});
});
// Modal_id => The id of the modal window
```

But the "Save and Close" button is error prone, as in many cases the save will finish after the page is refreshed.

**Comment by joomdonation** [comment]
Hmm. Maybe we should do that in a separate PR, then as this is unrelated to the main change from this PR.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 22ca77e23a04ff004d4ec920d3aa6e79ad8403ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34738">issues.joomla.org/tracker/joomla-cms/34738</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22ca77e23a04ff004d4ec920d3aa6e79ad8403ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34738">issues.joomla.org/tracker/joomla-cms/34738</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34738">issues.joomla.org/tracker/joomla-cms/34738</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
