### PR TITLE
[4.0] Calendar Field CSS

### PR DESCRIPTION
**Pull request by NunoLopesPT**
### Summary of Changes

Currently when the field type is a calendar it has a fixed width that can cause it going out of the window, to not change the libraries, I created a class to fix this that needs to be added at the .xml in the forms folder. 

### Testing Instructions

Go to Modules -> Select one Module -> Right side the "Start Publishing" and "Finish Publishing" fields

### Expected result

screenshot from 2017-04-08 18-04-30

### Actual result

screenshot from 2017-04-08 17-58-38

screenshot from 2017-04-08 17-58-26

### Documentation Changes Required

None ( I guess ).

### CODE REVIEW

**Comment by C-Lodder** [comment]
Please do not update the CSS file only. In J4 we're using NodeJS and SCSS. You need to make your changes to the relevant SCSS file, then compile it.

Please read this: https://github.com/joomla/joomla-cms/blob/4.0-dev/grunt-readme.md

**Comment by NunoLopes96** [comment]
Hi @C-Lodder , I've installed already and ran the commands but not sure what to do, there is no currently .scss file for the one that I have edited

**Comment by C-Lodder** [comment]
Hmm, you're current PR is an extremely dirty approach, so please can you close this. I'd like to wait for BS4 beta 1 to come out first and I'll get this sorted.

**Comment by NunoLopes96** [comment]
done

**Pull request closed without merging**
