### PR TITLE
[Plugins] Add filters to manifest files.

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This adds filter attribute to some fields in plugin manifest files.

### Testing Instructions

Code review: 
1) Check that filtered default value is identical (including data type) to fallback value inside plugin code.
2) Check that comparisons are valid (not type safe or, if type safe, not compared to different type).

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 042cfa5484dad06434bf05cc2a53a24cb8eadc03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20410">issues.joomla.org/tracker/joomla-cms/20410</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 042cfa5484dad06434bf05cc2a53a24cb8eadc03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20410">issues.joomla.org/tracker/joomla-cms/20410</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20410">issues.joomla.org/tracker/joomla-cms/20410</a>.</sub>

**Comment by wilsonge** [comment]
Awesome stuff! Thanks!

**Pull request merged**
