### PR TITLE
[4.0] REST semantic Provide Sensible Resource Names

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #33336 .

### Summary of Changes
from GET  `/api/index.php/v1/installer/manage`
to GET `/api/index.php/v1/extensions
`

### Testing Instructions

read #33336
or test the endpoint :

  

-   `GET {{base_path}}/api/index.php/v1/extensions?core=true/false`
-   `GET {{base_path}}/api/index.php/v1/extensions?status=0/1`
-   `GET {{base_path}}/api/index.php/v1/extensions?type=component/plugin/module/template`

### Documentation Changes Required
already undocumented but should be

### CODE REVIEW

**Comment by anibalsanchez** [comment]
I have tested this item :red_circle: unsuccessfully on 9b7acd4cb36c2252563177579f066c44a777f475<br /><br />It seems that I always get the same response and it doesn't use the filters:

```sh
curl -H "Authorization: Bearer ...." -X GET "http://.../api/index.php/v1/extensions?core=true"

curl -H "Authorization: Bearer ..." -X GET "http://.../api/index.php/v1/extensions?core=false"

curl -H "Authorization: Bearer ..." -X GET "http://.../api/index.php/v1/extensions?status=1"

curl -H "Authorization: Bearer ..." -X GET "http://.../api/index.php/v1/extensions?status=0"
```

**Comment by alikon** [comment]
@anibalsanchez can you please retest, now just 1 pr 😃

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on 340411851341f71fe4a027e2ca70713563342dca<br /><br />I have tested the 3 poposed endpoints with their filters and it returns different content according to each of the proposed filters.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33339">issues.joomla.org/tracker/joomla-cms/33339</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on 340411851341f71fe4a027e2ca70713563342dca<br /><br />Before applying the patch I did not manage to get any answer from the API
After applying the patch, I got correct filtered data in response to 

curl  -H "Authorization: Bearer XXXXXX" http://localhost/demo_j4/api/index.php/v1/extensions?status=1

and

curl  -H "Authorization: Bearer XXXXXX" http://localhost/demo_j4/api/index.php/v1/extensions?status=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33339">issues.joomla.org/tracker/joomla-cms/33339</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33339">issues.joomla.org/tracker/joomla-cms/33339</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by PhilETaylor** [comment]
Just a quick follow up

The code merged was totally wrong. 

```
$this->modelState->set('filter.status', $this->input->get('status', $this->input->get->get('status')), 'INT');
$this->modelState->set('filter.type', $this->input->get('type', $this->input->get->get('type')), 'STRING');
```

Those type hints at the end are wrong - Im fixing it in #33960 so follow along there if interested.

**Pull request merged**
