### PR TITLE
[4.0][a11y] Add landmark to breadcrumbs

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Add a landmark NAV to bredcrumbs module to  improve navigation 

### Testing Instructions
View sourcecode before and after patch.

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on bcaab10d3f4c130a50b6e27851c3fe7a7bdfb473<br /><br />

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on bcaab10d3f4c130a50b6e27851c3fe7a7bdfb473<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 @SniperSister rips please

**Comment by zero-24** [comment]
Rebooted drone @ http://ci.joomla.org/joomla/joomla-cms/13960

**Comment by zero-24** [comment]
Rips and drone are happy now.

**Comment by brianteeman** [comment]
Sorry this is not correct. As we still support IE 11 it is required to also have role=navigation

See https://www.drupal.org/project/drupal/issues/2655764#comment-11322013
and https://www.html5accessibility.com/#support

**Comment by zwiastunsw** [comment]
I tested in Windows 10 and Internet Explorer 11 with NVDA. IE11 supports tag `nav`. Screen reader announces a landmark.

**Comment by chmst** [comment]
I asked https://caniuse.com/#search=nav
It seems that all modern browsers support the nav tag.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by brianteeman** [comment]
caniuse doesnt cover the accessibility tree ;)

according to all the docs i can find online ie11 doesnt support it. Although I can confirm Stefan results

**Comment by zwiastunsw** [comment]
My proposal:
- in Joomla 4 do not add a redundant attribute role. 
- in Joomla 3 leave, as in other cases (e.g. pagination.php. )

**Review by brianteeman — COMMENTED** [review]
You can have <nav role=navigation

**Comment by zwiastunsw** [comment]
I am sorry, but the last change does not make sense at all. Why use the general tag `div` and add an attribute `role`, since there is a `nav` tag. 
Please restore the `nav` tag. I won't argue about the role attribute, although I don't agree with Brian.

**Comment by chmst** [comment]
I see the problem with IE11. So w coud do it this way and use a role="navigation" with aria-label.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by zwiastunsw** [comment]
Use `<nav role="navigation" ...` as Brian writes

**Comment by zwiastunsw** [comment]
I have tested this item :red_circle: unsuccessfully on 8c30cef48e28dd25dac890f9b39269f20578b294<br /><br />Use <nav role="navigation" ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on c84724a4e8d447fab9ba01fbbc66444f9cb39d9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on c84724a4e8d447fab9ba01fbbc66444f9cb39d9d<br /><br />I have tested successfully, but I still think that the role attribute is redundant. Please settle the dispute @wilsonge <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c84724a4e8d447fab9ba01fbbc66444f9cb39d9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23685">issues.joomla.org/tracker/joomla-cms/23685</a>.</sub>

**Comment by zwiastunsw** [comment]
nav_element

**Comment by brianteeman** [comment]
That shows html validation and as already explained several times now Internet explorer does not map nav to the accessibility api. There is nothing to resolve. You are simply wrong.

https://mobile.twitter.com/brianteeman/status/1089555677780082690?s=19

**Comment by zwiastunsw** [comment]
As I wrote earlier. The role attribute is redundant in this case. Tag without attribute is fully correct. I understand that you want to ensure better accessibility for IE11 users as well. 
I take note of this. But that doesn't mean I'm wrong.  I have already presented arguments. Joomla4 will be used for the next few years. 
I understand that consistently, in all cases of new HTML5 tags, we will add a redundant role attribute, e.g. in a Cassiopeia template.

**Comment by brianteeman** [comment]
Joomla supports ie11 therefore it must have the role and therefore it is not redundant

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
