### PR TITLE
Update jquery.jcrop

### PR DESCRIPTION
**Pull request by brianteeman**
The version we are using is 0.9.12 and the current version is 2.0.4

This PR just updates to 2.0.4 
http://deepliquid.com/content/Jcrop.html

Go to the template manager and select an image. You can then highlight an area of the image and use the crop button on the toolbar

### CODE REVIEW

**Comment by brianteeman** [comment]
I found it is used in the template editor where you can use it to crop an image in a template

**Comment by zero-24** [comment]
@brianteeman can you have a look into the file permissioms?

**Comment by brianteeman** [comment]
Grrrh

**Comment by brianteeman** [comment]
Should be OK now

**Comment by andrepereiradasilva** [comment]
yes, in the core, seems to be only used on:

```
/administrator/components/com_templates/views/template/tmpl/default.php
/administrator/templates/hathor/html/com_templates/template/default.php
```

**Comment by brianteeman** [comment]
Yes so I have updated the test instructions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10475">issues.joomla.org/joomla-cms/10475</a>.</sub>

**Comment by brianteeman** [comment]
@andrepereiradasilva @infograf768 can you test this please. it is an easy fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10475">issues.joomla.org/joomla-cms/10475</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a7e686b207425466e7f10703bef2a49de9abfb6e<br /><br />still crops.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10475">issues.joomla.org/joomla-cms/10475</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on a7e686b207425466e7f10703bef2a49de9abfb6e<br /><br />Looks still working from here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10475">issues.joomla.org/joomla-cms/10475</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10475">issues.joomla.org/joomla-cms/10475</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
