### PR TITLE
Code style: one too much greater-than

### PR DESCRIPTION
**Pull request by infograf768**
As title says.
Can be merged on review.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8ec7938f55a8f617ead6da622484c58bdec64a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13024">issues.joomla.org/tracker/joomla-cms/13024</a>.</sub>

**Comment by andrepereiradasilva** [comment]
this is actually a xml error, not code style

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8ec7938f55a8f617ead6da622484c58bdec64a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13024">issues.joomla.org/tracker/joomla-cms/13024</a>.</sub>

**Comment by andrepereiradasilva** [comment]
an there are at least one more ...
See 
`/components/com_content/views/category/tmpl/default.xml`

**Comment by infograf768** [comment]
Added the missing one.

**Comment by infograf768** [comment]
RTC. Simple.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13024">issues.joomla.org/tracker/joomla-cms/13024</a>.</sub>

**Comment by brianteeman** [comment]
No matter how simple please don't mark your own pr as RTC

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9a6d80a637122f4f52f17472a18bebc9f1db5d5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13024">issues.joomla.org/tracker/joomla-cms/13024</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 9a6d80a637122f4f52f17472a18bebc9f1db5d5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13024">issues.joomla.org/tracker/joomla-cms/13024</a>.</sub>

**Pull request merged**
