### PR TITLE
[5.1] Alias string consistency

### PR DESCRIPTION
**Pull request by brianteeman**
five years later as requested by @rdeutz ... redo of #19857

Pull Request for Issue #19856 reported by @MartijnMaandag 

### Summary of Changes
On the Tab 'Publishing' we do have the label 'Created by Alias' in Contacts, Banners and Articles (although in Contacts it is 'Created By Alias' with capital 'B').

**This PR makes them all "Created by Alias"**

In Tags, Newsfeeds and frontend content editing this is uses a generic string called 'Author's Alias'. 

**This PR makes the generic string "Created by Alias" and updates the generic description**

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on da0bd8b83e92489fb5edc760d3e4a11adc034fae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42220">issues.joomla.org/tracker/joomla-cms/42220</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42220">issues.joomla.org/tracker/joomla-cms/42220</a>.</sub>

**Comment by adj9** [comment]
By installing the PR from scratch the administrative homa does not have the cottect style, the titles of all boxes are to be reduced.
While the other pages , such as articles and system, work
JD

**Comment by brianteeman** [comment]
@adj9 you posted that report on the wrong issue

**Comment by Razzo1987** [comment]
thanks @brianteeman ;)

**Pull request merged**
