### PR TITLE
[4.2] [FIXED]::Responsiveness of User/Groups/Permission table

### PR DESCRIPTION
**Pull request by Lakshay-Pruthi**
Pull Request for Issue # .
#38828
### Summary of Changes
User/Groups/Permission table has been made responsive

### Actual result BEFORE applying this Pull Request
https://user-images.githubusercontent.com/91469717/205014030-29ebd5fa-d263-4360-a19d-2b97d5a16719.mp4

### Expected result AFTER applying this Pull Request

https://user-images.githubusercontent.com/91469717/205015429-a0dcf2f2-71d9-4008-ae98-c5245882cf16.mp4

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
The changes here will break the admin when RTL

**Comment by Lakshay-Pruthi** [comment]
Fixed!!

**Comment by brianteeman** [comment]
image

No better than before and arguably worse

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on bd8661dedcef11976a44d02c4bcc7c2904c81790<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39335">issues.joomla.org/tracker/joomla-cms/39335</a>.</sub>

**Comment by Lakshay-Pruthi** [comment]
It's working completely fine on my local

https://user-images.githubusercontent.com/91469717/207333358-7f496b1c-74d4-4ab9-992b-925ea76e4840.mp4

**Comment by Quy** [comment]
Not aligned:

39335-columns

Pagination cut-off:
39335-pagination

**Comment by Quy** [comment]
Closing as  this is not a proper fix. Thank you for trying.

**Pull request closed without merging**
