### PR TITLE
Dropdown menu

### PR DESCRIPTION
**Pull request by brianteeman**
It's been a long standing issue that if the component or menu dropdown menus are too long then it is not possible to ever scroll to the bottom. This happens quite a lot on a site with multiple languages
#### Summary of Changes

Add a fix max height of 500px to the height of the dropdown menu. If the menu gets too long then it is scrollable within the menu.

(Note this is not the final PR as I havent touched the less file yet - this does not apply to hathor which doesnt have this scrolling problem)
#### Testing Instructions

Create enough menus for the menu dropdown to be too long or the screen
## Menu screen before

before-menu
## Component screen before

before-component
## Animated gif to show the scroll after applying the patch

dropdown-menu-bug

### CODE REVIEW

**Comment by brianteeman** [comment]
Source for this code is https://ugate.wordpress.com/2013/06/28/scrollable-twitter-bootstrap-menus/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9347">issues.joomla.org/joomla-cms/9347</a>.</sub>

**Comment by Sandra97** [comment]
Would be great like this!

**Comment by brianteeman** [comment]
Currently there is an issue as it is stopping the submenu links from working - looking into that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9347">issues.joomla.org/joomla-cms/9347</a>.</sub>

**Comment by brianteeman** [comment]
The example provided by ugate shows that submenus will work - struggling to get my head around that part at the moment - any help appreciated to get this finally fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9347">issues.joomla.org/joomla-cms/9347</a>.</sub>

**Comment by wilsonge** [comment]
http://jsfiddle.net/XKEmy/ Look at their example fiddle here - for the scrollable example they place the scroll-menu class on the <li> element the child <ul> element is placed in - dunno why it works - but that's what they've done and there's a special comment about the fact it's done differently for that...

**Comment by brianteeman** [comment]
Thats what I was looking at last night before my brain crashed. Just not
100% they actually have a scrolling menu with submenus. Looks like just a
regular menu with a scrolling submenu.

**Comment by photodude** [comment]
Would it be possible to tie this new menu height to the viewport size rather than using 500px? say 85% of the viewport size (noting that this viewport concept only applies some tablets, desktops, and high-resolution desktop screens. As mobile has its own menu that behaves differently)

**Comment by infograf768** [comment]
>http://jsfiddle.net/XKEmy/
They do have scrolling submenus at first sight.

screen shot 2016-03-09 at 10 14 59

**Comment by wilsonge** [comment]
That was what I didn't want to say :( they didn't have an example there. Was kinda hoping it would work 'out of the box'

**Comment by wilsonge** [comment]
@infograf768 yes the submenu scrolls but they don't have an example of the main menu scrolling when there are submenu items

**Comment by brianteeman** [comment]
Thats the problem - i will see what I can work out this morning

@photodude If I get it working this way then I can look at making it based
on the viewport.

On 9 March 2016 at 09:17, George Wilson <notifications@github.com> wrote:

> @infograf768 <https://github.com/infograf768> yes the submenu scrolls but
> they don't have an example of the main menu scrolling when there are
> submenu items
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9347#issuecomment-194198516>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Doesnt help that every response to this issue on the bs mailing list is
"your menu is too long make it shorter" and "submenus suck we're dropping
them"

On 9 March 2016 at 09:18, Brian Teeman <brian@teeman.net> wrote:

> Thats the problem - i will see what I can work out this morning
>
> @photodude If I get it working this way then I can look at making it based
> on the viewport.
>
> On 9 March 2016 at 09:17, George Wilson <notifications@github.com> wrote:
>
>> @infograf768 <https://github.com/infograf768> yes the submenu scrolls
>> but they don't have an example of the main menu scrolling when there are
>> submenu items
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/9347#issuecomment-194198516>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
As I suspected - the code in that fiddle does not support submenus on a
scrollable dropdown menu

On 9 March 2016 at 09:25, Brian Teeman <brian@teeman.net> wrote:

> Doesnt help that every response to this issue on the bs mailing list is
> "your menu is too long make it shorter" and "submenus suck we're dropping
> them"
>
> On 9 March 2016 at 09:18, Brian Teeman <brian@teeman.net> wrote:
>
>> Thats the problem - i will see what I can work out this morning
>>
>> @photodude If I get it working this way then I can look at making it
>> based on the viewport.
>>
>> On 9 March 2016 at 09:17, George Wilson <notifications@github.com> wrote:
>>
>>> @infograf768 <https://github.com/infograf768> yes the submenu scrolls
>>> but they don't have an example of the main menu scrolling when there are
>>> submenu items
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/joomla/joomla-cms/pull/9347#issuecomment-194198516>.
>>>
>>
>>
>>
>> --
>> Brian Teeman
>> Co-founder Joomla! and OpenSourceMatters Inc.
>> http://brian.teeman.net/
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Maybe we could look into another solution for submenus if feasible, like displaying them indented below their menus? With a up/down arrow would be better. In that case the scroll may be possible.

I mean something like:
Banners ⏷
   Banners
   Categories
   Clients
   Tracks
Contacts ⏷

etc.


Just an idea.

**Comment by brianteeman** [comment]
I tried that and it was actually a worse experience for everyone forcing a scroll when you only have a few components - some of them have a lot of submenus

**Comment by infograf768** [comment]
When I talked about the arrow, I meant that the arrow would react in the dropdown, not be there just for display.

**Comment by brianteeman** [comment]
ah - I see what you mean now. so the arrow activates the submenu

On 10 March 2016 at 09:00, infograf768 <notifications@github.com> wrote:

> When I talked about the arrow, I meant that the arrow would react in the
> dropdown, not be there just for display.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9347#issuecomment-194743367>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Just to clarify - are you thinking of something like this http://www.bootply.com/uBoT3zP1P2 @infograf768  combined with the new scrolling code

**Comment by infograf768** [comment]
Exactly!

**Comment by infograf768** [comment]
And with arrows for the menu itself to indicate that there are submenus

**Comment by brianteeman** [comment]
I will have a look and see what I can come up with. That code example is not suitable for us. I am thinking we could maybe have it as an alternative module

**Comment by brianteeman** [comment]
I think this looks like what you are talking about - scrolling and expanding submenus
Its bootstrap3 though - not sure if it can be backported 
http://www.bootply.com/0ZWCUWF61p

**Comment by C-Lodder** [comment]
The only way I know of fixing this in the current top menu is to have an empty `<ul>` tag after your `scroll-menu`. On hover, you'll have to clone the contents of the submenu (all `<li>` elements) and append them to the empty `<ul>`, using JS.

You'll also need to get the top offset of the menu item your hovered over and use that to assign the `top` position of the `<ul>`.

There will also be some styling tweaks for the UL's pseudo selectors.

RTL support will also need to be taken into consideration

Screenshot below is an example:

screeny

**Comment by brianteeman** [comment]
That looks good. Are you able to produce some code. The method I'm looking
at is a massive rewrite of the code and probably won't be b/c

**Comment by C-Lodder** [comment]
@brianteeman done: https://github.com/joomla/joomla-cms/pull/9347

**Comment by brianteeman** [comment]
closing in favour of #9375

**Pull request closed without merging**
