### PR TITLE
[5.1] Trailing slash: Don't redirect for homepage

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #43056 .

### Summary of Changes
When you open the homepage and have additional query parameters appended, you can encounter an infinite redirect loop.

### Testing Instructions
1. Go to the System - SEF plugin and set "Trailing Slash for URLs" to "Enforce URLs without trailing slash".
2. Go to your frontend and open the homepage. Append query parameters like `?test=1` to the URL.

### Actual result BEFORE applying this Pull Request
You encounter a redirect loop.

### Expected result AFTER applying this Pull Request
You don't get a redirect.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f43e22ac841852359320e368513f7821db329cb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43063">issues.joomla.org/tracker/joomla-cms/43063</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f43e22ac841852359320e368513f7821db329cb5<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43063">issues.joomla.org/tracker/joomla-cms/43063</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43063">issues.joomla.org/tracker/joomla-cms/43063</a>.</sub>

**Comment by LadySolveig** [comment]
Thanks and thank you for the quick testing @brianteeman @viocassel

**Pull request merged**
