### PR TITLE
Convert users notes modal to Bootstrap modal

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Convert users notes mootools modal to BS modal

In users list view (/administrator/index.php?option=com_users&view=users), there is still a mootools modal. Needs some notes to reveal it!
This PR converts it to Bootstrap modal
#### Preview:

screen shot 2015-01-23 at 1 37 59
#### Testing

Create some user notes (/administrator/index.php?option=com_users&view=notes)
Apply patch 
go to (/administrator/index.php?option=com_users&view=users) and click "display 1 note"

### CODE REVIEW

**Comment by losedk** [comment]
@test All good!

**Comment by waader** [comment]
@test works for me!

**Comment by zero-24** [comment]
Thanks for testing and coding here! Moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5873">issues.joomla.org/joomla-cms/5873</a>.</sub>

**Comment by dgt41** [comment]
Thanks for testing. @wilsonge @phproberto 3.5?

**Comment by wilsonge** [comment]
It's good for 3.4 (no layouts involved) but I'm not merging anything more until i release beta 1 tonight

**Comment by wilsonge** [comment]
@test works fine.

@dgt41 before this patch (and still now) if you have debug enabled it's completely broken in the modal. Can you look into that please?

**Comment by wilsonge** [comment]
Merged this. Thanks!

**Comment by dgt41** [comment]
@wilsonge 
We can use this code:
```php
		// Also skip for the component output
		$tmpl = JFactory::getApplication()->input->getCmd('tmpl', '');
		if (isset($tmpl) && $tmpl == 'component')
		{
			return;
		}
```
here: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/debug/debug.php#L120

But I don’t know if we need an option in the plugin as well, any thoughts?

**Comment by wilsonge** [comment]
The problem is in some frontend areas people render component only output and will expect debug to show :/ so i don't think it's that easy to do it for all component only views

**Comment by dgt41** [comment]
I think it needs to be controlled in the plugin somehow. Front end, back end will also make some devs unhappy… I am not sure also, maybe raising an issue and get some feedback?

**Comment by dgt41** [comment]
@wilsonge Actually the problem comes from the new sidebar

**Comment by dgt41** [comment]
@wilsonge #5917 ??

**Pull request merged**
