### PR TITLE
[4.0] Various installation cleanups

### PR DESCRIPTION
**Pull request by wilsonge**
- Cleans up how options are passed around the models
- Fixes database check (which was stored in the pre-installed CMS session and therefore `db_created` property isn't found
- Makes `deleteInstallationFolder` public
- Fix fatal error when sample data cannot be found

Testing:
- Check installer still works
- Sample data can now be installed in the installer

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by Bakual** [comment]
> Sample data can now be installed in the installer

@wilsonge You should not fix that, you should remove it. Because we should get rid of the samledata SQL files. That was the whole point of the module 😄

**Comment by ghost** [comment]
changed Title to make clear its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20306">issues.joomla.org/tracker/joomla-cms/20306</a>.</sub>

**Comment by brianteeman** [comment]
Agree with @bakual

**Comment by wilsonge** [comment]
Then let's get a PR in for deleting it after this is merged. This is fixing at least 3 other issues as I've documented above - so it's not a reason to reject the PR

**Comment by infograf768** [comment]
Understand the limitations of this PR:
Reminder though
1. We still do not have the UI to delete older tables when installing on same db
2. Installing one of the possible languages gets in a loop although language is installed

**Pull request merged**
