### PR TITLE
[Regression] Clean cache of installed language query on language extension install/update/remove

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.

### Summary of Changes

After https://github.com/joomla/joomla-cms/pull/12671 when you have cache enabled an install a language the language cannot be used until you clean the cache.

This PR intends to solve that.

### Testing Instructions

1. Use latest staging
2. Enable cache
3. Install a language and go to installed languages see the installed language is not there.
4. Clean the cache. the language is there now.
5. Apply patch
6. Install a language. Repeat step 3. the language is there.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by mbabker** [comment]
This seems somewhat backward to me.  It seems to me this data should be saved to a cache group that gets cleared on extension install/update and if we aren't already doing so there should be "critical" cache groups that are cleared on extension install/update.

**Comment by andrepereiradasilva** [comment]
right, first instinct was to solve the imediate problem and think later 😄

anyway in this PR i do the same for the getContentLanguages (which by now is only used in associations edit), but those IMO we cannot cache to file (unless we clear the cache everytime we create/delete/change a content language).

so what do you propose, add a cache clean of `com_languages` everytime a language is installed?
if so, i'm not very confortable with caching mecanisms and JInstaller, could you help pointing the way?

**Comment by mbabker** [comment]
At https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/languages.php#L257 add a call to `JFactory::getCache()->clean('com_languages');` to the end of the method.

Edits to content languages already clear that cache group, see https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_languages/models/language.php#L262

So the part that isn't covered is clearing cache after a regular extension install or update.  For install you could do something in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/install.php#L64 but you'd need to figure out what kind of data is available to you to only clear that cache for language packages/extensions.  Funny enough, the controller method for that task clears the `mod_menu` cache always on success.  The same applies to the update controller/model as well.

**Comment by andrepereiradasilva** [comment]
thanka a lot! will check that

**Comment by andrepereiradasilva** [comment]
i think (and hope) in the last comit i cover all installed languages cases.

content languages is another issue, because we need to clean the cache on every action ... even just changing the state of a content language in the list view. so, probably is better not to cache those...

**Comment by andrepereiradasilva** [comment]
ok @mbabker since the content languages is already been cached anyway i added it again.
See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/helper.php#L134

please check if we can solve the installed languages cache the way i did it. thanks in advance.

**Comment by mbabker** [comment]
This should work.  I can't say that clearing this cache in the install adapters is a good technical solution, but I don't really have anything better for the moment so let's run with it so we don't lose the ability to cache this data.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ab7eca42ab30a30fef962e47347ccdcf50227178<br /><br />confirmed issue with cache
applied patch - no issue with cache<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12906">issues.joomla.org/tracker/joomla-cms/12906</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ab7eca42ab30a30fef962e47347ccdcf50227178<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12906">issues.joomla.org/tracker/joomla-cms/12906</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on ab7eca42ab30a30fef962e47347ccdcf50227178<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12906">issues.joomla.org/tracker/joomla-cms/12906</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12906">issues.joomla.org/tracker/joomla-cms/12906</a>.</sub>

**Pull request merged**
