### PR TITLE
Admin menu missing

### PR DESCRIPTION
**Pull request by brianteeman**
Custom Admin Menu - missing options  …
With the new ability to create your own admin menu some components were missed.

This PR adds com_tags, multilingual associations, com_redirect and com_search

To test - first confirm that you can not create an admin menu for these 4 components
Apply the PR and make sure that you can create an admin menu of these 4 components and that they work

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cd1d23ad5ad388f3872bba24e8ec8d26da33e3bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16588">issues.joomla.org/tracker/joomla-cms/16588</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on cd1d23ad5ad388f3872bba24e8ec8d26da33e3bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16588">issues.joomla.org/tracker/joomla-cms/16588</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests. 

Thanks @brianteeman for PR and @Quy for Test.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
