### PR TITLE
[4.2] CLI core scripts cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
This is part of a series of pr (broken down to smaller ones to make testing easier) that fixes several issues in the cli commands.

Make sure the title is displayed
Make sure the case of the title matches the styleguide
Make sure table column headings match the styleguide

### core update
image

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0af3aa2a4d7012d6de503243d4cc3c983379b106<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38216">issues.joomla.org/tracker/joomla-cms/38216</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0af3aa2a4d7012d6de503243d4cc3c983379b106<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38216">issues.joomla.org/tracker/joomla-cms/38216</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38216">issues.joomla.org/tracker/joomla-cms/38216</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by heelc29** [comment]
@roland-d Can you please correct the milestone to `Joomla! 4.2.0`?

**Comment by richard67** [comment]
Done.

**Pull request merged**
