### PR TITLE
[4.4] Update .drone.yml

### PR DESCRIPTION
**Pull request by brianteeman**
grammar/typo

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 27e8072d8086126e9423230cfa334594c0631105<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44107">issues.joomla.org/tracker/joomla-cms/44107</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 27e8072d8086126e9423230cfa334594c0631105<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44107">issues.joomla.org/tracker/joomla-cms/44107</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44107">issues.joomla.org/tracker/joomla-cms/44107</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
