### PR TITLE
Add release news link to the mail

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #16090

### Summary of Changes

Add release news link to the mail. cc @brianteeman & @sharphosting 

image

### Testing Instructions

- install 3.7.0
- apply this patch
- see the mail the core sends out about 3.7.1

### Expected result

Release news link is included

### Actual result

Release news link is not included

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a16d90c9a4a3edff562c94d2a7a1531a0152176e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16170">issues.joomla.org/tracker/joomla-cms/16170</a>.</sub>

**Review by brianteeman — APPROVED** [review]
Thanks

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on a16d90c9a4a3edff562c94d2a7a1531a0152176e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16170">issues.joomla.org/tracker/joomla-cms/16170</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
