### PR TITLE
[4.1] s/toogle/toggle

### PR DESCRIPTION
**Pull request by brianteeman**
Note there is a change in js here as well

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 450f239ee68e3ecde37da831dbce16c30a2f12c6<br /><br />Code review. Error occurs at no other places than those fixed by this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36831">issues.joomla.org/tracker/joomla-cms/36831</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 450f239ee68e3ecde37da831dbce16c30a2f12c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36831">issues.joomla.org/tracker/joomla-cms/36831</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36831">issues.joomla.org/tracker/joomla-cms/36831</a>.</sub>

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
