### PR TITLE
[4.1] inline-help hidden by default

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37697 .

### Summary of Changes
The intention of this functionality is for the description to be hidden by default and its visibility toggled from the button.

The problem is that the default hidden state was added by javascript after the page has loaded and this resulted in a flash of text being displayed.

This PR changes the code so that the d-none class is present by default in the markup

### Testing Instructions

This includes a javascript chanage so will need npm run build:js or one of the prebuilt packages

### Actual result BEFORE applying this Pull Request

before

### Expected result AFTER applying this Pull Request
after

### Documentation Changes Required

none

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4c414799c8becaa642cc0636213acf84c4f024db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37699">issues.joomla.org/tracker/joomla-cms/37699</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 4c414799c8becaa642cc0636213acf84c4f024db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37699">issues.joomla.org/tracker/joomla-cms/37699</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37699">issues.joomla.org/tracker/joomla-cms/37699</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 4c414799c8becaa642cc0636213acf84c4f024db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37699">issues.joomla.org/tracker/joomla-cms/37699</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Comment by cyrez** [comment]
The PR has broken the display of descriptions everywhere as always hidden by default, and because the toggle button is integrated yet only in com_config and com_content options, can't be set by default on d-none in the markup.
Not only config pages are affected, but all edition and third-party extensions.

So, i would go to revert this PR until we find a better solution to not have the "flash" of description text.

https://github.com/joomla/joomla-cms/issues/37772

**Pull request merged**
