### PR TITLE
[3.9] Capitals in label callback

### PR DESCRIPTION
**Pull request by brianteeman**
pr for  #21957

Words in labels should be capitalised

### CODE REVIEW

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on cb8d1a017508a2e4b5c005911cf73229384e33d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22048">issues.joomla.org/tracker/joomla-cms/22048</a>.</sub>

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on cb8d1a017508a2e4b5c005911cf73229384e33d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22048">issues.joomla.org/tracker/joomla-cms/22048</a>.</sub>

**Comment by Harmageddon** [comment]
RTC after two successful tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22048">issues.joomla.org/tracker/joomla-cms/22048</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
