### PR TITLE
Fix tooltip for subform table layout, #39848

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #39848 .

### Summary of Changes
Fixing the tooltip for table layout with `groupByFieldset="true"` parameter

### Testing Instructions

Create a subform, somewhere:
```xml
<field type="subform" name="teest" label="Subform"
  groupByFieldset="true" multiple="true"
  layout="joomla.form.field.subform.repeatable-table">
  <form>
    <fieldset name="set1" label="set1" description="Set 1 description">
        <field type="text" name="text" label="text"/>
        <field type="textarea" name="bigtext" label="bigtext"/>
    </fieldset>
    <fieldset name="set2" label="set2" description="Set 2 description">
        <field type="text" name="text2" label="text2"/>
        <field type="textarea" name="bigtext2" label="bigtext2"/>
    </fieldset>
  </form>
</field>
```

And check the table header, there should be tooltip with a description text on hover.

### Actual result BEFORE applying this Pull Request
Tooltip icon is visible but no text

### Expected result AFTER applying this Pull Request
Tooltip icon is visible, and there a text

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 369a569172e05fc2f09e2cfb4bf62257ee771c91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39894">issues.joomla.org/tracker/joomla-cms/39894</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39894">issues.joomla.org/tracker/joomla-cms/39894</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39894">issues.joomla.org/tracker/joomla-cms/39894</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
