### PR TITLE
[4.0] Port privacy check to es6 js and fix quickicon

### PR DESCRIPTION
**Pull request by wilsonge**
To test this ensure the privacy policy quickicon now correctly functions after the patch (before it always hangs on finding requests)

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c8557ba89a9e3a5c91cba6adf0197cd2ac00698f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24875">issues.joomla.org/tracker/joomla-cms/24875</a>.</sub>

**Comment by wilsonge** [comment]
Thanks JM!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c8557ba89a9e3a5c91cba6adf0197cd2ac00698f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24875">issues.joomla.org/tracker/joomla-cms/24875</a>.</sub>

**Comment by infograf768** [comment]
Please though:
The button View Requests should align to right in LTR and left in RTL,
as it does for Extensions Update.
Text centered.

Screen Shot 2019-05-13 at 11 04 50

For extensions:

Screen Shot 2019-05-13 at 11 12 39

**Comment by infograf768** [comment]
Also it looks like we have a typo in the .js
`langaugeStrings`

**Comment by infograf768** [comment]
The wrong alignment of the warning comes from a missing
`<div class="message-alert">`
as we have for extension update

**Comment by wilsonge** [comment]
@infograf768 can you do a PR for that please?

**Comment by infograf768** [comment]
You mean towards yours or a new one?

**Comment by wilsonge** [comment]
New one. I already merged this before you posted

**Comment by infograf768** [comment]
argg ;)

**Comment by infograf768** [comment]
Please merge
https://github.com/joomla/joomla-cms/pull/24882

**Pull request merged**
