### PR TITLE
mod_feed - catch all Exceptions (Solves #9291)

### PR DESCRIPTION
**Pull request by EmilMassey**
PR to avoid displaying an error in mod_feed as issued in #9291.
The module should now render a message: _Feed not found_
### **Testing Instructions**
1. Add a Feed Display module
2. Add any RSS Feed which has uncommon date formats
3. See if the module throws error in Front-End.

### CODE REVIEW

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 7d810d7e8b0c3a80da3373720c67ebe8de6b2fed<br /><br />It's Ok, the module render a message: Feed not found with the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Comment by mbabker** [comment]
This changes nothing.  If the feed module is only catching `RuntimeException`s then it's better off catching all `Exception`s instead.  You're catching the thrown Exception and rethrowing a new `Exception` which makes debugging more difficult because now the error trace leads to that rethrown `Exception` versus the one that actually caused the error.

**Comment by EmilMassey** [comment]
Yeah, it was silly... I guess catching all `Exception`s in mod_feed helper is the best solution for now.

**Comment by mbabker** [comment]
:+1:

**Comment by grhcj** [comment]
I have tested this item :red_circle: unsuccessfully on 0fd45bfc92812d847eff5b406bdb2ffcf761edc2<br /><br />Tested on latest staging + this patch.
The fatal error described in #9291 appears with and without this patch applied (tested with the feed given in this issue).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Comment by mbabker** [comment]
If it's a fatal error that would be expected then as that isn't a thrown `Exception` that can be caught.  Maybe if that error is a `Throwable` in PHP 7 it can be caught in the feed module but not much else that can be done for PHP 5 without validating the format before passing it into the `JDate` instance.

Semantically this patch is valid in the fact that it will catch all `Exception` objects thrown during processing of the feed.

**Comment by EmilMassey** [comment]
According to [http://php.net/manual/en/datetime.construct.php](url), since 5.3.0, if date/time format passed to the constructor is invalid, then `Exception` is thrown, so the patch should work as 5.3.10 is minimum for Joomla 3.x. I've tested this on PHP 5.5.9, and the `Exception` has been caught in the module.

Date/time format validation may be implemented as proposed here: [http://php.net/manual/en/function.checkdate.php#113205](url), but is it really necessary?

**Comment by grhcj** [comment]
@EmilMassey My php version is 5.6.15.

**Comment by mbabker** [comment]
This should be merged.  Semantically it is a correct change.  The fact that @grhcj still gets an error does not mean that this patch fails (it could be another location throwing the error, like the admin mod_feed module or the newsfeed component).

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 0fd45bfc92812d847eff5b406bdb2ffcf761edc2<br /><br />As @mbabker said - error might not be related to this patch - all fine with code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Comment by EmilMassey** [comment]
I have tested this item :white_check_mark: successfully on 0fd45bfc92812d847eff5b406bdb2ffcf761edc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Comment by mrcompl** [comment]
I have tested this item :white_check_mark: successfully on 0fd45bfc92812d847eff5b406bdb2ffcf761edc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Comment by zero-24** [comment]
RTC based on multible tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9293">issues.joomla.org/joomla-cms/9293</a>.</sub>

**Pull request merged**
