### PR TITLE
Install from web message

### PR DESCRIPTION
**Pull request by brianteeman**
Change from Now to is - its no longer a new thing
Remove the "and all applicable third party license terms." because no one has a clue what this refers to and anyway you cant agree to terms that you can not see

Pull Request for Issue #14672 .

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on bae647df23c203d9b879866958601af5b27e8d2f<br /><br />Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14682">issues.joomla.org/tracker/joomla-cms/14682</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on bae647df23c203d9b879866958601af5b27e8d2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14682">issues.joomla.org/tracker/joomla-cms/14682</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14682">issues.joomla.org/tracker/joomla-cms/14682</a>.</sub>

**Comment by mbabker** [comment]
Bumping to Needs Review.

I went back to my email from 2013 and I've got a couple of threads from the board at the time communicating with the legal team and the terms piece seems to be discussed in that thread.  I'm going to read over that again and try to make complete sense of this with a fresh mind.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14682">issues.joomla.org/tracker/joomla-cms/14682</a>.</sub>

**Comment by mbabker** [comment]
FWIW, the last message I got on the topic was this:

> The following text was just approved by our lawyers:

> The Joomla! Extensions Directory (JED) is now available with _Install from Web_ on this page. By clicking "Add Install from Web tab" below, you agree to the _JED Terms of Service_, and all applicable third party license terms.
[Add "Install from Web" tab]

(Italicized text represents text which was to be linked, as is done now)

**Comment by Bakual** [comment]
Maybe that lawyer had no clue or just wanted to be on the save side?

**Comment by mbabker** [comment]
No, they were very well informed.  That comes at the tail end of a multi-week thread.

**Comment by Bakual** [comment]
Still, the points from Brian are valid. You can't accept "applicable third party license terms" if you have no clue which they are. So it at least has to be clarified somehow (eg having a link which states those licenses).
Otherwise I doubt it can have any juristical relevance.
Maybe that needs to be checked with lawyers again, but imho common sense could apply here :laughing:

**Comment by mbabker** [comment]
Hence the reason a question has been raised.  All I know is during the initial review that was the text we were given and now (years later) a fresh question about it for a fresh set of eyes can be answered.

**Comment by ronnikc** [comment]
I was, as my memory services me, not in the debate at the time, but i will try and clarify.

The reason why it's formulated as  "applicable third party license terms" and you approve to take on that risc yourself, even when you dont know it, is to make sure joomla is 100% free of risc.

So it's going in with safety belt and goggles at once - and that's why the lawyer has formulated it like this.

Install from web still constitutes Distribution, and that is why that passage is needed.

**Comment by brianteeman** [comment]
it is well established in law in both the usa and europe that if you ask someone to agree to terms and conditions without them being able to check the terms and conditions then they are legally invalid and the user can not be held to the terms and conditions.

**Comment by tonypartridge** [comment]
What was the 'Lawyers' thought on this? Did we get legal confirmation?

**Comment by brianteeman** [comment]
@mbabker any update on this or shall I just close it as stuck in lawyer hell

**Comment by mbabker** [comment]
I think my original message got lost in the abyss.  Let me go back and find it and bring it up again.

**Pull request closed without merging**
