### PR TITLE
[3.7.x] Admin login language field fix

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #12436 .
### Summary of Changes

Removes CSS override on the language field of the admin login. CSS was forcing an incorrect height on field and incorrect width on field dropdown. 
### Testing Instructions

Using Joomla 3.7 install multiple languages. Open login screen. Check field alignment (dropdown opened & closed)

**Before Patch**
admin-lang1

**After Patch**
admin-lang2
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
The height might be fixed but the widths needs some improvement and it would be great if you could do that too - see the three highlighted areas in the image

screen shot 2016-10-16 at 14 16 09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12442">issues.joomla.org/tracker/joomla-cms/12442</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @brianteeman That is definitely better.

admin-lang-align

**Comment by brianteeman** [comment]
Thanks!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 4c92ca3f69e9cad08465fd2fea23cac346a42912<br /><br />:+1: Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12442">issues.joomla.org/tracker/joomla-cms/12442</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4c92ca3f69e9cad08465fd2fea23cac346a42912<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12442">issues.joomla.org/tracker/joomla-cms/12442</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12442">issues.joomla.org/tracker/joomla-cms/12442</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 this is still showing as Open on the Issue Tracker

**Comment by mbabker** [comment]
Not anymore 😉

**Pull request merged**
