### PR TITLE
[4.2] Workflow Notification no recipient

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #37744

### Test Setup Instructions

- Enable workflows in the content options with Basic as the default
- Edit all the Transitions so they have notifications enabled and set the Usergroups to Manager
- Create a new user in the usergroup manager
- Create a new article and save & close
- Edit an article and change the stage

## Test 1
- Check that the new user is receiving the notification emails for the change in state
_only proceed to test 2 & 3 when you are sure that you are gettig the email_

## Test 2
- Log in as the manager user and go to Messaging and in the **My Settings** lock the inbox
- log back in as your super user
- edit the previous article again and change the stage
### Before this PR
No notifications sent and no message displayed
image

### After this PR
No notifications sent and a message is displayed - I am very open to suggestions for a better message
image

### Test 3
In the transition remove the usergroup 
image

### Before this PR
No notifications sent and no message displayed
image

### After this PR
No notifications sent and a message is displayed - I am very open to suggestions for a better message
image

### CODE REVIEW

**Comment by brianteeman** [comment]
rebased to 4,2 now that there will be no further 4.1 releases

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 359dfb9c93378e5bb048d6287e974c45ebb0bc06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37747">issues.joomla.org/tracker/joomla-cms/37747</a>.</sub>

**Comment by brianteeman** [comment]
brancg updated to restart drone

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on da184b39de32c2d879a9c44b6fbcd9a4ea65aa90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37747">issues.joomla.org/tracker/joomla-cms/37747</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37747">issues.joomla.org/tracker/joomla-cms/37747</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37747">issues.joomla.org/tracker/joomla-cms/37747</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
