### PR TITLE
[3][Security] Implement security fix in other places

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Joomla 3.9.26 had last min security fixes added to it by the JSST 

One of these security issues was not fixed in all places. 

This commit https://github.com/joomla/joomla-cms/commit/6c7b17c33ed7b14d162e9fbcccda339009b05b56#diff-36647192855b2ef14c990918bb56b4da7ac2d012fece3b98f3090d95fcd3abe2R44 also needs to be made to the offline.php file.

Thanks to @C-Lodder for reporting.

### CODE REVIEW

**Comment by ChristineWk** [comment]
Will this be fixed in the next version or will there be a new update package? Of course, you can (for the time being) temporarily exchange relevant code. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33128">issues.joomla.org/tracker/joomla-cms/33128</a>.</sub>

**Comment by PhilETaylor** [comment]
> Will this be fixed in the next version or will there be a new update package? 

Not my decision. Just another sloppy JSST security fix :-(

**Comment by dgrammatiko** [comment]
Out of curiosity why is this a security problem or even a problem at all?

Template editing is allowed only from Super Users. Also, this field accepts only a URL path, so I find this extremely weird that a superuser decides to alter the logo and inject faulty code. Or it's just me...

**Comment by PhilETaylor** [comment]
Ask the @joomla/security JSST team. Im not part of that team. Im not privileged to see the original reports. 

I know as much as everyone else - and that is its "Inadequate escaping allowed XSS attacks using the logo parameter of the default templates on error pages" as per https://developer.joomla.org/security-centre/850-20210401-core-escape-xss-in-logo-parameter-error-pages.html

**Comment by joomdonation** [comment]
@dgrammatiko I was about asking the same question myself. Don't we trust super users anymore ?

**Comment by dgrammatiko** [comment]
@PhilETaylor I'm not trying to blame you here, just to understand why this is treated as insecure

Edit also why there's no validator/sanitiser for media field: https://github.com/joomla/joomla-cms/tree/staging/libraries/src/Form/Rule

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c30531131b983189cfe7da3f1755b9bd50132c53<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33128">issues.joomla.org/tracker/joomla-cms/33128</a>.</sub>

**Comment by sandewt** [comment]
Why has `htmlspecialchars($this->params->get('sitetitle'))` (also line 82) no `ENT_QUOTES` or `ENT_COMPAT` ?
In other places this is done in the Joomla code !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33128">issues.joomla.org/tracker/joomla-cms/33128</a>.</sub>

**Comment by PhilETaylor** [comment]
@sandewt your comment is unrelated to this PR. 

`ENT_COMPAT` is the default value of `$flags` https://www.php.net/htmlspecialchars

**Comment by sandewt** [comment]
>@sandewt your comment is unrelated to this PR.

Right.

>ENT_COMPAT is the default value of $flags https://www.php.net/htmlspecialchars

Of course supplemented with UTF8

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c30531131b983189cfe7da3f1755b9bd50132c53<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33128">issues.joomla.org/tracker/joomla-cms/33128</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33128">issues.joomla.org/tracker/joomla-cms/33128</a>.</sub>

**Pull request merged**
