### PR TITLE
Fix for loader position

### PR DESCRIPTION
**Pull request by rs4231199**
Pull Request for Issue #32916 .

### Summary of Changes
Set `top` as 0, So that, it shows in all screen sizes.

### Testing Instructions
Apply the patch.

### Actual result BEFORE applying this Pull Request
Can be seen in the original issue.
Note that you might need to zoom out to see the loader.

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by rs4231199** [comment]
@PhilETaylor It works fine on Firefox on windows. Can you share your system information?

**Comment by infograf768** [comment]
This does not work, either with Macintosh safari or firefox or chrome

**Comment by infograf768** [comment]
Here is an animated gif for Firefox macintosh.

spinner


Details of spinner placement

Screen Shot 2021-04-02 at 07 52 53

Detail of what is displayed briefly when install is almost done

Screen Shot 2021-04-02 at 07 53 21

EDIT: corrected test below

**Comment by PhilETaylor** [comment]
> @PhilETaylor It works fine on Firefox on windows. Can you share your system information?

Primary testing is normally with with Safari on macOS.

**Comment by infograf768** [comment]
I correct my test.

I had some issues with npm ci.
The patch is OK for Firefox and Chrome Macintosh.

Indeed I have an issue with Safari where the spinner does not animate.

**Comment by infograf768** [comment]
@PhilETaylor 
I also have an issue with WebInstaller and Safari-Macintosh (while no such issue with Chrome or Firefox.)

Screen Shot 2021-04-02 at 12 06 30

**Comment by PhilETaylor** [comment]
Currently working fine for me :) 

Screenshot 2021-04-02 at 11 10 30

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 103e79658436eb9c910ba833a183cfcaa4f24758<br /><br />No animate on Mac-Safari, works on Mac-Firefox.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32940">issues.joomla.org/tracker/joomla-cms/32940</a>.</sub>

**Comment by dips1400** [comment]
I have tested this item :white_check_mark: successfully on 103e79658436eb9c910ba833a183cfcaa4f24758<br /><br />Works fine on chrome..!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32940">issues.joomla.org/tracker/joomla-cms/32940</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by laoneo** [comment]
Is this pr already solved with the merge of #37570?

**Comment by Hackwar** [comment]
Yes, this seems to be solved with that PR, so I'm closing this one.

**Pull request closed without merging**
