### PR TITLE
Moved JPluginHelper::importPlugin() call outside loops, project-wide.

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
- Moved `JPluginHelper::importPlugin()` call outside loops.

### Testing Instructions

None, should not change behavior

### Documentation Changes Required

None.

### CODE REVIEW

**Review by ggppdk — APPROVED** [review]

**Review by izharaazmi — APPROVED** [review]

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6b355d7729ba3ecc0ead37dbf37916497d4dc19e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13248">issues.joomla.org/tracker/joomla-cms/13248</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 6b355d7729ba3ecc0ead37dbf37916497d4dc19e<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13248">issues.joomla.org/tracker/joomla-cms/13248</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13248">issues.joomla.org/tracker/joomla-cms/13248</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Pull request merged**
