### PR TITLE
[4.0][backend template] Create opacity for disabled top menu items

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25872

### Summary of Changes
As title says. There is no way to differentiate top menu items when they are disabled.

### Testing Instructions
Edit an article.

### before patch
Screen Shot 2019-08-16 at 18 03 56-before

### After patch
Screen Shot 2019-08-16 at 18 06 18-after

@C-Lodder

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 01a02aba0b28a532c08374f8e0cfb32ec19bcae4<br /><br />Works like a charm.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25906">issues.joomla.org/tracker/joomla-cms/25906</a>.</sub>

**Comment by dgrammatiko** [comment]
@infograf768 please add `pointer-events: none;`, see https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by brianteeman** [comment]
@dgrammatiko Why? There isnt anything using pointer events then as far as I can tell

**Comment by dgrammatiko** [comment]
@brianteeman if I m not wrong devs can append links and buttons in that position as well. This is just a fail-safe for any appended link that needs to be disabled but the dev thinks that the reduced opacity also means not working links. In a perfect world that wouldn't be needed but let's be realistic here...

**Comment by brianteeman** [comment]
I think you are confusing cursor and pointer

**Comment by dgrammatiko** [comment]
The `cursor` is all about the visual representation of the cursor, the `pointer-events` is about removing the click functionality. Probably both are needed but the essential is the pointer-events as it will trully disable the functionality of those btns/links

**Comment by brianteeman** [comment]
How are they not disabled now?

**Comment by infograf768** [comment]
So, shall I add:
```
cursor: not-allowed;
pointer-events: none;
```

**Comment by brianteeman** [comment]
I do not see the need for the pointer-events  line - that's disabling something that is already disabled

**Comment by dgrammatiko** [comment]
> that's disabling something that is already disabled

It's already disabled for the core but what I'm suggesting will also disable, by default without extra code, 3rd PD buttons/links published in that position. It's about dev ergonomics

**Comment by brianteeman** [comment]
It should be the responsibility of the dev to choose if their stuff is enabled or disabled not just because it is in position x

**Comment by dgrammatiko** [comment]
@brianteeman the problem is that if they have a link (and obviously they wanted to tight it to the hiddenMenu) their course of action could be either:
- not echoing the link at all
- add some js to actually disable the link

By having this simple css you make peoples life easier by simply disabling tap/clink on links and buttons. Also, it's not that it gonna make any difference the delivered css in the backend is already around 1/2 a meg, so adding one more line won't make a difference

**Comment by brianteeman** [comment]
The problem is that you are forcing it to be disabled - it should be the developers choice. They might have a very good reason for it to be enabled

**Comment by dgrammatiko** [comment]
> The problem is that you are forcing it to be disabled

You're missing the point mate. This behaviour is coupled to a class `disabled`. Now tell me that the disabled class should be interpreted as **visual-disabled** and not as actually disabled... (it doesn't affect the normal links/button in that position `header`)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ead86c5e94ae6a7dc18623fb6925d0e785a462ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25906">issues.joomla.org/tracker/joomla-cms/25906</a>.</sub>

**Comment by wilsonge** [comment]
@brianteeman @dgrammatiko so the proposition as i understand is that if a developer chooses to have their content disabled, by using the disabled class (e.g. here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_user/tmpl/default.php#L21 ) then in the SCSS block response for disabled here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_header.scss#L109-L115 we'd add `pointer-events: none;` which would stop any special treatment whilst modules still choose if they want to allow clicks or not by choosing whether they are using the disabled class or not?

If i understand correctly then it makes sense to do it for me?

**Comment by dgrammatiko** [comment]
@wilsonge you got it, that was my proposal

**Comment by brianteeman** [comment]
The correct way to disable a button is with the element `disabled` not the class `disabled`
A button with a class disabled and pointer-none is not really disabled. It is still has focus. It is still in the accessiblity tree. It will still be announced as a button (with no mention that it is disabled.

**Comment by brianteeman** [comment]
image

image

**Comment by dgrammatiko** [comment]
For the button what Brian wrote is correct, but the rule also covers plain links and for those pointer-events is required

**Comment by brianteeman** [comment]
Links

image

**Comment by dgrammatiko** [comment]
AFAIK focus cannot be controlled by CSS, so I don't even understand why are we arguing here...

**Comment by brianteeman** [comment]
You are saying that you can just disable something with a class. I am proving that you cannot

**Comment by dgrammatiko** [comment]
What you are proving is that the platform doesn't provide any way to do it (only with CSS) in an accessible way. The functionality **is** disabled but to make it accessible you need to remove the tabindex as well

**Comment by brianteeman** [comment]
All of which makes your suggestion pointless

**Comment by dgrammatiko** [comment]
Common sense is not that common, I guess. Have it your way. Unsubscribe

**Comment by infograf768** [comment]
@wilsonge
Please decide if I should modify the PR to any of the proposed suggestions or not.
If not this can be merged.
Imho, if anyone is not happy, another PR can be done later and discussion can be done there.

**Comment by C-Lodder** [comment]
You don't control what elements (`<button>` or `<a>`) are added to the top menu and cannot disable a link with the `disabled` attribute, so `pointer-events: none;` should be added just incase a user decides to use `<a>`

**Comment by brianteeman** [comment]
As stated before
1. The creator of the link might want it to be enabled
2. It fails accessibility

**Comment by C-Lodder** [comment]
@brianteeman in which case at leatst use `a:not([target=_blank]) { pointer-events: none; }`. If an a user is editing an article and accidentally clicks a link that opens in the same tab, they'll lose their changes

**Comment by brianteeman** [comment]
pointer-events none only has an effect on mouse users

**Comment by C-Lodder** [comment]
Yup, but better than nothing. You'd have to use JS (`event.preventDefault()`) if you wish to cater for keyboard users

**Comment by brianteeman** [comment]
i still say it should be the 3pd problem to solve, there is no issue in core

**Comment by wilsonge** [comment]
Modify it please @infograf768

**Comment by infograf768** [comment]
@wilsonge
Done.

Note: when `pointer-events: none;` is present, then `cursor: not-allowed;` does not work. Therefore I did not add it.

**Pull request merged**
