### PR TITLE
Two search modules on same page: Invalid HTML.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary of Changes

Added module id to attributes _id_ and _for_ to have vaild HTML.
Fixed JQuery conflict in Beez3 (`role="search"`).
#### Testing Instructions
- Create 2 modules of type mod_search on same page.
- Validate page on https://validator.w3.org/ or just check HTML source code of page. 2 times `id="mod-search-searchword"`. This is invalid HTML.

Apply patch.
- Test again
- Test also FORM tags in template Beez3 with Firebug that both mod_search forms get a `role="search"` via JQuery.

### CODE REVIEW

**Comment by ggppdk** [comment]
Ok, this is nice to fix,

just a small number of websites will have problem if they 
- use custom JS or CSS based on old id
- and they do not have a custom module override

same comment applies for:  #11168

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 6d8ca30a8a95769abdcb45e277e869d468c43e99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11229">issues.joomla.org/joomla-cms/11229</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on fd247c0ae77adc0d7c4526f5052b560f779acfa9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11229">issues.joomla.org/joomla-cms/11229</a>.</sub>

**Comment by hardiktailored** [comment]
I have tested this item :white_check_mark: successfully on fd247c0ae77adc0d7c4526f5052b560f779acfa9<br /><br />Now search module label and input have different ID. "mod-search-searchword" concatenated with module ID. And both form have role="search".
Both working perfectly, no issue found with multiple search on same page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11229">issues.joomla.org/joomla-cms/11229</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on fd247c0ae77adc0d7c4526f5052b560f779acfa9<br /><br />Yes got the issue two same ids on same page for search.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11229">issues.joomla.org/joomla-cms/11229</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11229">issues.joomla.org/joomla-cms/11229</a>.</sub>

**Comment by rdeutz** [comment]
this can have an effect on site if someone use the id but it is right to merge it. I have set the milestone to 3.7.0, this should be something we point out in the release notes

**Pull request merged**
