### PR TITLE
[4.0] Fixing #33070

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #33070

### Summary of Changes

Check the issue

### Testing Instructions

> Edit an image in Joomla 4 media manager
> When I click on 0/90/180/275 the Angle field should update with that figure and the image preview should rotate.

### Documentation Changes Required
No, this is a bug fix

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d6729e1dddd2466c4155b8eb236c0e6e4b5f8202<br /><br />with Prebuild Package. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33071">issues.joomla.org/tracker/joomla-cms/33071</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d6729e1dddd2466c4155b8eb236c0e6e4b5f8202<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33071">issues.joomla.org/tracker/joomla-cms/33071</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33071">issues.joomla.org/tracker/joomla-cms/33071</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
