### PR TITLE
[4.0][com_config] Fixed sending the test mail

### PR DESCRIPTION
**Pull request by roland-d**
### Summary of Changes
Currently when you want to send out a test mail you get a notice that it is not possible because mail sending is disabled, even though it is enabled. Added the lost language strings as well.

### Testing Instructions
1. Make sure you have a Joomla 4 installation
2. Click on System in the menu
3. Click on Global Configuration
4. Click on the Server tab
5. Make sure that Send Mail is enabled
6. Click on Send Test Mail
7. Notice you get a message saying that mail sending has been disabled:
image

8. Apply the patch
9. Run the `npm ci` in the Joomla folder to generate the updated files
10. Click Send Test Mail
11. Notice that the test email has been sent
image

I may need help to correctly generate all JS files, so if there is any issues please let me know.

### Expected result
That the test email is send when mail sending is active

### Actual result
The test email is not send when mail sending is active

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :red_circle: unsuccessfully on bb3aa23919bcbff569643985e8167738efbb7cb8<br /><br />Confirm testing instructions, except for:
9. Run the npm ci in the Joomla folder to generate the updated files

That's why Tested unsuccessfully? sorry :-)
Do I hv to install e.g. https://docs.npmjs.com/cli/ci.html?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23591">issues.joomla.org/tracker/joomla-cms/23591</a>.</sub>

**Comment by roland-d** [comment]
Hello @ChristineWk Not being able to execute the test instruction isn't really an invalid test ;)
Have a look at [J4 Setting Up your Local Environment](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment) and see if that helps. This `npm` stuff is needed for many PRs so it is handy to have.

**Comment by ChristineWk** [comment]
Hi @roland-d I feared it :-)
delete from above URL the: ]. Site is empty. Found: https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en
You are right - but it's difficult :-) Thank you for info and understanding. Can or should I delete the "unsuccessfully"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23591">issues.joomla.org/tracker/joomla-cms/23591</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 RIPS please

**Review by wilsonge — APPROVED** [review]

**Comment by roland-d** [comment]
@ChristineWk Test seems to have been removed already, all is good and link is fixed. Thank you.

**Comment by zero-24** [comment]
Rebooted drone at: http://ci.joomla.org/joomla/joomla-cms/13804

**Comment by zero-24** [comment]
Drone is happy now cc @wilsonge

**Comment by roland-d** [comment]
@zero-24 Please check RIPS, it gives an ISE.

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on 7455c3739789c7640e05e2b099124a3de281528e<br /><br />Hi,

fix about mailonline is ok and I tested successfully, but I had to force $tls=false in library /vendor/phpmailer/phpmailer/src/PHPMailer.php, just before if instruction at row n. 1945, to send mail correctly. Its my smtp server fault.

In joomla 3.9 staging I have option "SMTP Security" option set to "None" to let it work. I set to "None" in Joomla 4 dev too, but to send the email I need to force $tls value to false. I think is something about SMTPAutoTLS functionality.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23591">issues.joomla.org/tracker/joomla-cms/23591</a>.</sub>

**Comment by roland-d** [comment]
@ladyjer Thank you for testing. Indeed your issue with TLS is not related. Feel free to create a new issue so this can be further investigated.

**Comment by Quy** [comment]
Tested on launch.joomla.org where the message is displayed correctly, but I don't get the test email. Should this still be considered a successful test?

**Comment by roland-d** [comment]
@Quy Can those sites actually email? I believe the test is still successful because it shows the fixes I have done are working. As in the mail is triggered and the message is showing correctly.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7041c424f813e18290ff2e990ba567795a23d664<br /><br />Works fine. tested with smtp.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23591">issues.joomla.org/tracker/joomla-cms/23591</a>.</sub>

**Comment by infograf768** [comment]
rebooted drone.we will see.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23591">issues.joomla.org/tracker/joomla-cms/23591</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by joeforjoomla** [comment]
There is still something wrong here, It's not possible to connect to SMTP server without any SSL/TLS because $SMTPAutoTLS in the PHPMailer class is always true and not managed in any way by the mail class or Joomla options.

image

**Comment by ghost** [comment]
@joeforjoomla please open a new Issue and set a link here.

**Pull request merged**
