### PR TITLE
[4.0] Fix save contact

### PR DESCRIPTION
**Pull request by infograf768**
Similar to https://github.com/joomla/joomla-cms/pull/23638
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23617#issuecomment-457888862 but this time for contact.

### Summary of Changes
A new contact should have hits set to 0

### Testing Instructions

Create a new contact.

### Expected result
Contact is saved

### Actual result
Contact is not save with error:
`Save failed with the following error: Incorrect integer value: '' for column 'hits' at row 1`

### CODE REVIEW

**Comment by alikon** [comment]
similar to #23689 for custom field

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23688">issues.joomla.org/tracker/joomla-cms/23688</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 46feb02cedc0b47498ab454e186d00a53acd0939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23688">issues.joomla.org/tracker/joomla-cms/23688</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 46feb02cedc0b47498ab454e186d00a53acd0939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23688">issues.joomla.org/tracker/joomla-cms/23688</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23688">issues.joomla.org/tracker/joomla-cms/23688</a>.</sub>

**Comment by infograf768** [comment]
@zero-24 @SniperSister RIPS Please

EDIT: Updating branch solved RIPS

**Comment by wilsonge** [comment]
Thanks JM!

**Pull request merged**
