### PR TITLE
Fixed overwritten properties

### PR DESCRIPTION
**Pull request by demis-palma**
#### Summary of Changes
1. Fixed overwritten properties
2. Removed redundant unit of measure

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
the `0px`to `0`of course.

regarding the rest, test instructions?

**Comment by brianteeman** [comment]
Without any real test instructions nothing will happen with this.
With good test instructions at least explaining what can be seen before and
after this PR it will get tested quickly

On 15 April 2016 at 11:59, andrepereiradasilva <notifications@github.com>
wrote:

> the 0pxto 0of course.
>
> regarding the rest, test instructions?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9928#issuecomment-210414811>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by demis-palma** [comment]
@andrepereiradasilva thanks for asking. I'm sorry for the lack of details.

I only removed a bounce of duplicated occurrences of identical instructions, for example

line-height: 1.6em;
*and 3 lines after*
line-height: 1.6em;

or others slightly different
border: solid 1px;
*and 2 lines after*
border: 1px solid #DDDDDD;
which the second overwrites and prevales on the first

or again
margin: 0;
*and 2 lines after*
margin: 0 0 0;

It is well visible with a good diff program.

I can't think about a test except checking that the templates renders the same as before.
It's only an optimization, it should not produce any visible effect.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 58d837250a12a1ef2a31879ee3506358711936c9<br /><br />Makes sense.
Removes duplicated css and makes micro-optimizations to css.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9928">issues.joomla.org/joomla-cms/9928</a>.</sub>

**Comment by henkrijneveld** [comment]
I have tested this item :white_check_mark: successfully on 58d837250a12a1ef2a31879ee3506358711936c9<br /><br />deskcheck and small regressiontest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9928">issues.joomla.org/joomla-cms/9928</a>.</sub>

**Comment by demis-palma** [comment]
Thanks!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9928">issues.joomla.org/joomla-cms/9928</a>.</sub>

**Pull request merged**
