### PR TITLE
Fix changed behavior of getAuthorisedViewLevels

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

After PR #36432 `$user->->getAuthorisedViewLevels()` now return Associative array, 
that may lead to unexpected bugs when code relies on non Associative array. 
This PR make sure the array is non associative

### Testing Instructions

In index.php of template add:
`dump(Joomla\Utilities\ArrayHelper::isAssociative($app->getIdentity()->getAuthorisedViewLevels()));`

### Actual result BEFORE applying this Pull Request
Result is `true`.

### Expected result AFTER applying this Pull Request
Result is `false`.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on c7d86af7521343f52ec3b6dd0322819b4cf712b1<br /><br />Tested successfully in 4.1.1-dev of 22 February in Wampserver 3.2.7 using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37096">issues.joomla.org/tracker/joomla-cms/37096</a>.</sub>

**Comment by wilsonge** [comment]
@bembelimen adding this as a release blocker as it's a API B/C break

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c7d86af7521343f52ec3b6dd0322819b4cf712b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37096">issues.joomla.org/tracker/joomla-cms/37096</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37096">issues.joomla.org/tracker/joomla-cms/37096</a>.</sub>

**Comment by laoneo** [comment]
> @bembelimen adding this as a release blocker as it's a API B/C break

Why a BC break?

**Comment by Fedik** [comment]
> Why a BC break?

Because return value is changed

**Comment by bembelimen** [comment]
Good find, thx.

**Pull request merged**
