### PR TITLE
[4] contact search error

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #37151 .

### Summary of Changes
 get the state of the list LIMIT

### Testing Instructions

- create a contact category
- create several contacts, and put them all in this category
- create a menu item of type "List Contacts in a Category", and set the "filter field" option to "show" in list layouts
- if front end visit that page
- apply a filtering criteria
- apply again a filtering criteria (or simply reset)

### Actual result BEFORE applying this Pull Request
error page saying "0 Object of class stdClass could not be converted to string"

### Expected result AFTER applying this Pull Request

search works as expected

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on df98bb9be7aa08537d2e46e4ca1d253bbe6c1013<br /><br />Tested successfully in 4.1.1-dev of 2 March using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37166">issues.joomla.org/tracker/joomla-cms/37166</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on df98bb9be7aa08537d2e46e4ca1d253bbe6c1013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37166">issues.joomla.org/tracker/joomla-cms/37166</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37166">issues.joomla.org/tracker/joomla-cms/37166</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
