### PR TITLE
Chunk the tokens array to avoid making extremely long queries.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes
Chunk the tokens array (which can potentially be very long) before using it to generate a query. Run a query for each chunk instead of the whole array.

### Testing Instructions
1) Check that your php `max_execution_time` is something sensible like 30 seconds. 
1) Turn on finder indexing for content.
2) Create a super long article. Maybe like 10,000 words. Maybe this can help: http://slipsum.com/
3) Save the article.

### Expected result
Well, I expect the article to save properly and the page to reload without crashing.

### Actual result
Most likely, the article will save but in the post-save indexing process there will be a timeout. This happens because we are looping over a huge array of tokens and adding each one to the `values` array of the query object. The query object handles this rather inefficiently (should be addressed in a different PR) but is mostly fine until the `values` array gets very large. 

One solution is to avoid getting a huge `values` array by sending several smaller queries instead of one big one. This is that solution.

### Documentation Changes Required
nope

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by okonomiyaki3000** [comment]
Rebased with latest staging. I can't imagine why that drone test is failing. There's nothing in this code that would cause it to fail.

**Comment by okonomiyaki3000** [comment]
Hmm. So, is this getting in? Because this is a legit problem that people in the real world may actually face.

**Comment by mbabker** [comment]
If it gets tested, sure.  Looking at this again reminded me of something though.

There's already a similar (yet less elegant) implementation of this in the [SQL Server subclass](https://github.com/joomla/joomla-cms/blob/3.8.1/administrator/components/com_finder/helpers/indexer/driver/sqlsrv.php#L543) and I think it essentially is the same thing, so it looks like the overriding method can be removed.

**Comment by okonomiyaki3000** [comment]
Yeah, that's weird. Someone noticed this could happen with SQL Server but didn't think it would ever be a problem for other dbs? Anyway, I can remove that override and include it in this PR if you want.

**Comment by mbabker** [comment]
That was me.  SQL Server actually has (had?  this was SQL Server 2008) a hard query limit of inserting 1000 values in a query which is why I had to do the override for that driver.

**Comment by okonomiyaki3000** [comment]
Rebased with latest staging and went ahead and removed that redundant override.

**Comment by okonomiyaki3000** [comment]
Just need one more approval...

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on a972a115254ba8813027efb7863732842304d130<br /><br />

Tested and did code review too,

i am using similar code for updating DB in a faster way,
also this is not only about updating DB when having a long article,
there should be a considerable performance gain for the indexer in big sites<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17390">issues.joomla.org/tracker/joomla-cms/17390</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a972a115254ba8813027efb7863732842304d130<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17390">issues.joomla.org/tracker/joomla-cms/17390</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
