### PR TITLE
Fixes #6965. Multilang. Article associations. Multiple ID conflict in bootstrap modal

### LINKED ISSUE #6965: Unable to correctly setup articles associations
#### Steps to reproduce the issue
1. make a clean installation from the staging code and perform the *Extra Steps* installing **two** additional languages (e.g. fr-FR and it-IT). In the *Extra Steps* also check the "Activate the mulitlingual feature* option, so that example categories/articles are installed too
2. set-up association between the 3 language specific categories (maybe unneded step, but no problem)
3. try to set-up association between the 3 articles (starting from the en-GB one)

#### Expected result
You should be able to set up association between the en-GB article and the fr-FR and it-IT articles

#### Actual result
when trying to set up the association for the it-IT article you are offered the fr-FR one

#### System information (as much as possible)
PHP Built On: Windows NT SMZ 6.3 build 9200 (Windows 8.1 Business Edition) i586
Database Version: 5.6.23
Database Collation: utf8_general_ci
PHP Version: 5.4.39
Web Server: Apache
WebServer to PHP Interface: apache2handler
Joomla! Version: Joomla! 3.4.2-dev Development [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

#### Additional comments
The *problematic* language seems to be the one with the lowest language ID
e.g. if (beside en-GB) you install ca-ES and fr-FR, it is fr-FR that becomes problematic

### PR DESCRIPTION
**Pull request by ghost**
Please see https://github.com/joomla/joomla-cms/issues/6965 for test instructions.
After applying patch you should be able to select associated articles for all languages.

### CODE REVIEW

**Comment by infograf768** [comment]
Good find! @test OK here on a new install..

(Note: on an existing legacy site, I could not reproduce the issue)

**Comment by infograf768** [comment]
in fact, this is apparently a <b>regression</> as the issue comes from
https://github.com/joomla/joomla-cms/pull/6804

**Comment by dgt41** [comment]
@infograf768 How does modal conflict with associations?
I see associations as chosen items on a select tag:
`<select id="jform_associations_en_GB" name="jform[associations][en-GB]" class="chzn-done" style="display: none;">`
What am I missing here?

**Comment by dgt41** [comment]
@bertmert Sorry I didn’t realize that this was a PR with code in it. Thanks for taking care of it! I will try to test it later on!

**Comment by smz** [comment]
@test success
Thank-you, @bertmert

**Comment by infograf768** [comment]
same issue for contact and newsfeeds
Making a PR now for both.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/6983

**Comment by smz** [comment]
Will do: at this time I have a problem, here, with http://issues.joomla.org/ not loading... :confused:

**Comment by sovainfo** [comment]
No problem for me, loads fine.

**Comment by smz** [comment]
... must be a local issue... sorry!

**Comment by Kubik-Rubik** [comment]
Merged. Thank you @bertmert!

**Pull request closed without merging**
