### PR TITLE
[4.0] grunt readme update

### PR DESCRIPTION
**Pull request by brianteeman**
Correct some typos
Correct some paths
Remove chosen from the list
Add dragula to the list

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by C-Lodder** [comment]
Incomplete but ok

**Comment by brianteeman** [comment]
what was incomplete? what did I miss

Note if you are referring to the list of extensions that are installed then I was thinking that it was best not to list them in the readme anyway as it will be hard to keep uptodate

**Comment by C-Lodder** [comment]
Some are missing still. If you think it would be best to remove them from the `readme.md`, I'm fine with that. If you want to submit a PR, go for it, else I can do so :)

**Comment by brianteeman** [comment]
I took the list from /dev/assets/packages.json

**Comment by C-Lodder** [comment]
This file gets automatically updated when you run `grunt`, so you're probably on a older version. Have a look in `root/media/vendor` or `grunt_settings.yaml` for a list of all packages

**Comment by brianteeman** [comment]
packages.json is certainly out of date compared to grunt_settings.yaml

which suggest to me that this line in the readme is incorrect

> - `grunt shell:update`.................will update all the npm packages to the version defined in /dev/assets/package.json


Even more reason not to include the list of extensions in the readme but it would be good to replace it with the definitive place to find the list which right now I am not sure what that is

**Comment by dgt41** [comment]
since we're still haven't rich the stability level, I'll say let this file as is and we'll revisit it once all the javascript tasks are completed. 
Eg. https://github.com/joomla/joomla-cms/pull/14594 adds two more scripts to the list and is not the last PR from the task list...

**Comment by C-Lodder** [comment]
No, it's not incorrect. The way it works is:

1. Run `grunt`
2. This will read all the packages from the `grunt_settings.yaml`
3. This willl then dynamically create a `package.json`

The reason why there's an old package.json there is cause it must have been committed ages ago. It the only file in the `dev/assets` directory on the Github repo. Not sure how Github plays with empty directories to be honest.

**Comment by zero-24** [comment]
> Not sure how Github plays with empty directories to be honest.

It is going to be removed ;) This is the reason for the index.html files in some folders that are expected to be empty

**Comment by dgt41** [comment]
> It is going to be removed

If I remember well it will be recreated by the script, so np

**Comment by C-Lodder** [comment]
cool, so just remove the `package.json` and add an `index.html`

**Comment by zero-24** [comment]
> cool, so just remove the package.json and add an index.html

Sounds like a plan :+1:

**Pull request merged**
