### PR TITLE
[4.0] JText error message

### PR DESCRIPTION
**Pull request by brianteeman**
Make sure we use the namespaced Text:: instead of JText::

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 08a98446bf1bf753f1f9c527182c68f2e71d7fc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33025">issues.joomla.org/tracker/joomla-cms/33025</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 08a98446bf1bf753f1f9c527182c68f2e71d7fc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33025">issues.joomla.org/tracker/joomla-cms/33025</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33025">issues.joomla.org/tracker/joomla-cms/33025</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33025">issues.joomla.org/tracker/joomla-cms/33025</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR. It comes from the 4.0-dev branch and will be fixed with #33026 .

**Comment by TLWebdesign** [comment]
Sorry i have no clue how to do a PR but i can tell you there are two more files having JText:: PHP code in it in this repo after doing a search:

https://github.com/joomla/joomla-cms/blob/a1ae392c3f980dc7fd3ddd7a588ffb81f3e6decb/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php#L20
https://github.com/joomla/joomla-cms/blob/a1ae392c3f980dc7fd3ddd7a588ffb81f3e6decb/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php#L21
https://github.com/joomla/joomla-cms/blob/a1ae392c3f980dc7fd3ddd7a588ffb81f3e6decb/plugins/actionlog/joomla/joomla.php#L1154

**Comment by richard67** [comment]
@TLWebdesign You've checked the staging branch, as far as I can see. On that branch they are ok, we only want to get rid of the JText is the 4.0-dev branch, as far as I know.

**Comment by TLWebdesign** [comment]
Hi @richard67 i checked the 4.0-dev branche. downloaded the package and did a search.

**Comment by TLWebdesign** [comment]
Maybe i posted the wrong links then here i guess. Will try to correct them :) 

Hmm links are the same so i think i did it correctly tho. Very much a beginner on this so excuse me if it was incorrect tho. 

What i did was download 4.0-dev branche and then did a search for JText:: on my Mac. Then looked those files up on github i the 4.0-dev staging branche and got the perma link of the corresponding line.

**Comment by infograf768** [comment]
As far as I could check, @TLWebdesign  findings are correct in 4.0-dev

**Comment by richard67** [comment]
There might come more of these `JText`s when the upmerge from 3.10-dev will be continued.

**Comment by richard67** [comment]
@brianteeman Do you want to fix the 3 other places found by @TLWebdesign in the 4.0-dev branch? Or will you make another PR for these plus the other ones which might come when George continues the upmerge from 3.10-dev?

**Comment by TLWebdesign** [comment]
This is quite a low skilled job changing this. i wouldn't mind spending my time on this. So you guys can do more higher skilled stuff.

**Comment by brianteeman** [comment]
They are not normal JText - they need to be tested

Please merge this for now. @wilsonge usually catches them when he commits

**Comment by wilsonge** [comment]
@TLWebdesign definitely happy for you to do some PR's though - every bit definitely helps :)

Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
