### PR TITLE
[4.1] plg_system_schedulerunner s/atrributes/attributes

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/atrributes/attributes

### CODE REVIEW

**Comment by brianteeman** [comment]
shouldnt bug fixes like this be on the main branch and not the 4.1 branch

**Comment by PhilETaylor** [comment]
Considering the task scheduler is a Joomla 4.1 feature and this file doesn't exist in the 4.0-dev branch... no.

**Comment by richard67** [comment]
> shouldnt bug fixes like this be on the main branch and not the 4.1 branch

@brianteeman The scheduler stuff is only in 4.1, or am I mixing up something?

**Comment by richard67** [comment]
But shouldn't the attributes of the es5 and the es6 version be different? => @dgrammatiko Could you have a look on it?

**Comment by PhilETaylor** [comment]
> But shouldn't the attributes of the es5 and the es6 version be different?

No idea - I just fixed a blatantly obvious typo.

**Comment by richard67** [comment]
Yes, and the typo fix is right of course.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d4ca03da72d4c29200e28e872b11b7aabf6e1cf8<br /><br />Typo fix is right. Other stuff (values of the attributes) need to be checked separately.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36342">issues.joomla.org/tracker/joomla-cms/36342</a>.</sub>

**Comment by dgrammatiko** [comment]
> But shouldn't the attributes of the es5 and the es6 version be different

Yes, the current definition is wrong, here's the correct one:

```json
    {
      "name": "plg_system_schedulerunner.run-schedule.es5",
      "type": "script",
      "uri": "plg_system_schedulerunner/run-schedule-es5.min.js",
      "dependencies": [
        "core"
      ],
      "attributes": {
        "nomodule": true,
        "defer": true
      }
    },
    {
      "name": "plg_system_schedulerunner.run-schedule",
      "type": "script",
      "uri": "plg_system_schedulerunner/run-schedule.min.js",
      "dependencies": [
         "plg_system_schedulerunner.run-schedule.es5"
       ],
       "attributes": {
         "type": "module"
       }
```

**Comment by PhilETaylor** [comment]
added  "type": "module"

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dcad60023a047d2c22ad906e6bab90118d5a630a<br /><br />By review. Typo fixed and values corrected. Now the es6 is loaded as module and the es5 not, like it should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36342">issues.joomla.org/tracker/joomla-cms/36342</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on dcad60023a047d2c22ad906e6bab90118d5a630a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36342">issues.joomla.org/tracker/joomla-cms/36342</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36342">issues.joomla.org/tracker/joomla-cms/36342</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
