### PR TITLE
Updated Copyright text of Readme.md file in 3.10-dev branch and aligned it with staging branch text

### PR DESCRIPTION
**Pull request by manakwadhwa2002**
Pull Request for Issue #32801

### Summary of Changes
Updated Readme.md file of 3.10-dev branch

### Testing Instructions
You can compare it with staging branch

### Actual result BEFORE applying this Pull Request
(C) 2005 Open Source Matters, Inc. https://www.joomla.org
Distributed under the GNU General Public License version 2 or later
See License details

### Expected result AFTER applying this Pull Request
Copyright (C) 2005 - 2021 Open Source Matters. All rights reserved, Inc. <https://www.joomla.org>
* Distributed under the GNU General Public License version 2 or later
* See [License details](https://docs.joomla.org/Special:MyLanguage/Joomla_Licenses)

### Documentation Changes Required
No documentation changes are required i have added the text and have not removed any text

### CODE REVIEW

**Comment by brianteeman** [comment]
Changes made in branches are merged up so you dont need to create the same pull request for each branch

**Comment by richard67** [comment]
@manakwadhwa2002 Three things:

1. When having already the idea how to solve an issue and planning to make a pull request, it is sufficient to just make the pull request, it doesn't need to make an issue in this case.
2. The copyright statements have been changed with PR #31504 for 4.0-dev to a new standard format which doesn't contain an end year so that we don't have to adjust them every year.
3. The 3.10-dev branch doesn't need to be fixed with copyright statements because this will be regularly merged up from staging, except if it concerns files which only exist in 3.10-dev but not in staging.

**Comment by richard67** [comment]
P.S.: And for 3.10-dev it was changed with #29689 . This PR here would undo this change for the readme file and so not be correct.

Closing for the reasons stated above.

**Comment by manakwadhwa2002** [comment]
@richard67  thanks for updating me with new standards of copyright text, I'll keep in mind that I'll not push any changes regarding this. This happened because I am not in any of the joomla discussion forums or on glip, it would be a great help if you can add me in glip or add me any discussion channels as my commits are not limited to correction. I am a full stack developer and i am willing to contribute in code also. it would be a great help if you can add me in glip or add me any discussion channels.

**Comment by richard67** [comment]
@manakwadhwa2002 Are you a GSoC 2021 student, too?

**Comment by manakwadhwa2002** [comment]
@richard67  yes i am also in GSoc 2021 student but apart from that I was continually looking for bugs and other issues in joomla cms. This year only i got to know about GSoC.

**Comment by richard67** [comment]
@manakwadhwa2002 I've just checked with the people on Glip who care for the GSoC students and was told you will be contacted and invited soon.

**Comment by manakwadhwa2002** [comment]
@richard67 thanks for your help, means a lot for me.

**Comment by richard67** [comment]
@manakwadhwa2002 We do what we can 😄 And don't be disappointed that your first pull request got closed. That can happen at the beginning, I think it happened to me, too, in some 2014 or so, when I've started here. Next one will be better.

**Comment by manakwadhwa2002** [comment]
@richard67 No No, I am not disappointed at all, after all it is a process and I can under stand that none of the joomla team member  merges a PR that is not as per policies. I can under this happens will of us newbies but I'll continuously look towards working on other issue and I hope I'll be able to merge a good PR soon. Looking forward to work with Team Joomla

**Pull request closed without merging**
