### PR TITLE
[4.3] After saving a menu item, rebuild the tree

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
While working on the tags, I noticed that the menu system is missing a rebuild upon saving an item. We have this code in com_categories and in com_tags. Without this, errors in the tree are not fixed upon saving the item again. 

### Testing Instructions
In a website with a few menu items, change the lft and rgt value from a menu item to 0. Edit that menu item and save it again. See that the lft and rgt values are restored.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
Would this mean that we can remove the rebuild button?

**Comment by Hackwar** [comment]
I fear not. It is present everywhere else, so for now I would keep both... In the long run I'd like to have a maintenance component where stuff like this would be moved to. But that's far into the future.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b22ab6336fc86f3282316642bbfd87e851b582d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39153">issues.joomla.org/tracker/joomla-cms/39153</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b22ab6336fc86f3282316642bbfd87e851b582d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39153">issues.joomla.org/tracker/joomla-cms/39153</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39153">issues.joomla.org/tracker/joomla-cms/39153</a>.</sub>

**Comment by laoneo** [comment]
Thank you!

**Pull request merged**
