### PR TITLE
Wrong class for chosen

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .
### Summary of Changes

Fix the class name to chzn-done

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks

**Comment by dgt41** [comment]
My crap, my fix 😉

**Comment by dgt41** [comment]
@zero-24 nope, travis needs https://github.com/joomla/joomla-cms/pull/11413 or something similar.
It's not this PR

**Comment by wilsonge** [comment]
3.7 branch has many travis issues with form fields :( wasn't this one tho

**Pull request merged**
