### PR TITLE
[4.0] Select modal button

### PR DESCRIPTION
**Pull request by brianteeman**
When creating a newsfeed, menu alias, contact, article or any type of category of menu item we have the option to Select, Edit, Create an item

image

For some reason, perhaps legacy, the title for the Select was "Select or Change" but you can only select. There is no ability to change - to do that you have to clear furst.

This pr therefore corrects the title on the button and the title on the modal page and then removes the unused strings

image

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on cd22e457d25ed893fc55b2aada0209bff3a55a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on cd22e457d25ed893fc55b2aada0209bff3a55a8d<br /><br />Text should also be changed here:
[https://github.com/joomla/joomla-cms/blob/cd22e457d25ed893fc55b2aada0209bff3a55a8d/administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php#L150](https://github.com/joomla/joomla-cms/blob/cd22e457d25ed893fc55b2aada0209bff3a55a8d/administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php#L150 "https://github.com/joomla/joomla-cms/blob/cd22e457d25ed893fc55b2aada0209bff3a55a8d/administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php#L150")

Otherwise see screenshot in my next comment.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by richard67** [comment]
screen shot 2019-06-02 at 08 58 59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ae9855520d353758dce6c01e72c7501565496256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ae9855520d353758dce6c01e72c7501565496256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25082">issues.joomla.org/tracker/joomla-cms/25082</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
