### PR TITLE
[4.1] fix parks image

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes

Parks image doesn't display properly due to improper relative path.

### Testing Instructions
Install sample testing data.
Click on "parks" on the menu at the top
Notice that the image does not display.
Verify the url for the image is "http://j4.local/index.php/images/sampledata/parks/banner_cradle.jpg" ( your uri will be different of course )
view that the image displays.
verify url for the image is "http://j4.local/images/sampledata/parks/banner_cradle.jpg"

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
see #37663

**Comment by Quy** [comment]
My local testing is in a subdirectory `http://localhost/joomla-cms-4.1-dev/` and not in the root so this PR will not be a correct fix.
Enable `Use URL Rewriting` and it will not be an issue.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on cccd072351a21f91f6021b62cbd035f9637131da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37674">issues.joomla.org/tracker/joomla-cms/37674</a>.</sub>

**Comment by N6REJ** [comment]
> My local testing is in a subdirectory `http://localhost/joomla-cms-4.1-dev/` and not in the root so this PR will not be a correct fix. Enable `Use URL Rewriting` and it will not be an issue.

Mine is a sub as well...
www/j4/.....

We had this exact same issue several years ago when the router was changed.

**Comment by N6REJ** [comment]
> I have tested this item 🔴 unsuccessfully on [cccd072](https://github.com/joomla/joomla-cms/commit/cccd072351a21f91f6021b62cbd035f9637131da)
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/37674](https://issues.joomla.org/tracker/joomla-cms/37674).

How was it unsuccessful, please show the failure.  Just because you don't like the fix doesn't mean it doesn't work.

**Comment by brianteeman** [comment]
Before PR
image

image

After PR
image

image

**Comment by brianteeman** [comment]
this really should be closed

**Comment by N6REJ** [comment]
No, it shouldn't.  
The "default" dataset returns 
image
which is incorrect.
"http://j4.local/index.php/images/sampledata/parks/banner_cradle.jpg"
image
is off yet is clearly being left on even with .htaccess and url rewriting going on.

IF infact we do remove the testing sample dataset then that is a different issue.

**Comment by brianteeman** [comment]
1. Add suffix to URL is nothing to do with this
2. I already showed that this PR does not work

**Comment by N6REJ** [comment]
your test doesn't even make sense... if the image showed pre-fix why would I change it?  and how would adding a "/" change the url so dramatically.  I'll retest yet again with a clean ( again ) install.

**Comment by N6REJ** [comment]
sample "test" data option has been removed from 4.1-x  So I'm closing this

**Comment by brianteeman** [comment]
sample "test" data has NEVER EVER been part of any joomla release

**Pull request closed without merging**
