### PR TITLE
[4.3] Remove unnecessary escaping

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove unnecessary escaping of double quotes since enclosed in single quotes.

### Testing Instructions
Code review.
or 
Install/update PR.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d6494a79d62e169f0ee9ee76694f356e429fe5fc<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40274">issues.joomla.org/tracker/joomla-cms/40274</a>.</sub>

**Comment by richard67** [comment]
I'm not sure if it's sufficient to test only by code review. The escape is definitely not necessary for the databases, but maybe the component needs that?

What happens if you add a new tour? Does it escape the quotes again in the `extensions` column for the newly created records?

**Comment by Quy** [comment]
In the `guidedtours` table, there are no double quotes with fresh installations of the latest branch and prebuilt package of this PR.

**Comment by richard67** [comment]
@Quy And what happens if you create a new tour in backend so a new records gets added by PHP?

**Comment by richard67** [comment]
@Quy I've just tested what I meant. It is ok, when adding a new tour in backend, the double quotes are also not escaped, so all fine.

**Comment by Quy** [comment]
Same as the other entries `["*"]`.

**Comment by richard67** [comment]
@Quy Except if you select some components, then it is e.g. `["com_content","com_categories"]` 😛 

The question is now: Do we want to add a new update SQL which removes the escapes from beta 4 or rc1 or rc2 versions when updating? I am not sure if it needs that, but I know at least one person of whom I think he would want that.

**Comment by Quy** [comment]
Sorry I meant to say no `\` required in the SQL files and not no double quotes in the table.

**Comment by richard67** [comment]
I've restored the previous test result in the issue tracker since the commit which invalidated the test count was just a clean branch update.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a8969e67fa0a2fef8e01d234b8e0f6727a0fc1aa<br /><br />I've verified that on both MySQL and PostgreSQL, the double quotes in the `extensions` column are already stored in database without escaping when making anew installation without this PR applied. This means that it does not need a new update SQL script for fixing the values when updating 4.3 beta and RC versions because there would be nothing to fix.

I've also verified on both databases that a new installation with this PR applied works fine, there is nothing new in the database server logs.

By review all SQL changes of this PR are correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40274">issues.joomla.org/tracker/joomla-cms/40274</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40274">issues.joomla.org/tracker/joomla-cms/40274</a>.</sub>

**Comment by obuisard** [comment]
Thank you @Quy for the PR :-)

**Pull request merged**
