### PR TITLE
JHtml image. Parameter $returnPath = -1 returns image path instead of image tag

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/19762#issuecomment-368095188

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/19762#issuecomment-368095188
- Apply patch
- Test again

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ac8edde7c418b5eb0b9c64ea3c90a47392f9ad1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19770">issues.joomla.org/tracker/joomla-cms/19770</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 1ac8edde7c418b5eb0b9c64ea3c90a47392f9ad1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19770">issues.joomla.org/tracker/joomla-cms/19770</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by dgrammatiko** [comment]
I am (and probably not only me) using this to have exactly the path and not an image tag with the given source tag (obviously you don’t need a php helper to do that, you can echo the image tag directly). All and all you should correct the doc block instead of changing the behaviour!

**Comment by dgrammatiko** [comment]
Disregard my comment, I thought there was only one param for this attribute.

**Pull request merged**
