### PR TITLE
[4.2] Template Override description

### PR DESCRIPTION
**Pull request by brianteeman**
This fixes a language string error in my own pr #38451

Testing requires overrides that need checking. You can simulate this by

1. Create template overrides for com_content/article and com_newsfeed/feed
2. Run this sql query replacing #_ with your db prefix INSERT INTO `#__template_overrides` (`id`, `template`, `hash_id`, `extension_id`, `state`, `action`, `client_id`, `created_date`, `modified_date`) VALUES (1, 'cassiopeia', 'L2h0bWwvY29tX25ld3NmZWVkcy9uZXdzZmVlZC9kZWZhdWx0LnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54'), (2, 'cassiopeia', 'L2h0bWwvY29tX2NvbnRlbnQvYXJ0aWNsZS9kZWZhdWx0X2xpbmtzLnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54');

You will now have two override files to update and can test this PR

image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 140924ae95e97232cc0e558706c4dae88d5ddb89<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39336">issues.joomla.org/tracker/joomla-cms/39336</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 140924ae95e97232cc0e558706c4dae88d5ddb89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39336">issues.joomla.org/tracker/joomla-cms/39336</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39336">issues.joomla.org/tracker/joomla-cms/39336</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you!

**Pull request merged**
