### PR TITLE
[4.1] configuration.php-dist debug

### PR DESCRIPTION
**Pull request by brianteeman**
The file configuration.php-dist should have values that match the standard installation. 
This pr sets the value for debug to false from true

code review only

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 44fce27ad23d9aaee4fd67b18738a470b2ea7a0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37506">issues.joomla.org/tracker/joomla-cms/37506</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44fce27ad23d9aaee4fd67b18738a470b2ea7a0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37506">issues.joomla.org/tracker/joomla-cms/37506</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37506">issues.joomla.org/tracker/joomla-cms/37506</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
