### PR TITLE
[5.1] Light/Dark Mode switch

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #43307 .

### Summary of Changes

The icon represents the current state and the text identifies what you can switch between

image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 7b4bf9c63c842f30484937c7a95d4f0740ecb651<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43454">issues.joomla.org/tracker/joomla-cms/43454</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7b4bf9c63c842f30484937c7a95d4f0740ecb651<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43454">issues.joomla.org/tracker/joomla-cms/43454</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43454">issues.joomla.org/tracker/joomla-cms/43454</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @brianteeman and for testing @ChristineWk  @dautrich

**Pull request merged**
