### PR TITLE
[4.0] Update dependencies

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Update dependencies

_Note that this really should be automated by a Bot. Consider using Renovate or dependabot-preview_

### Testing Instructions

Go round the site and ensure it's working the same as before

### CODE REVIEW

**Comment by ghost** [comment]
> _Note that this really should be automated by a Bot. Consider using Renovate or dependabot-preview_

added this for Meeting of BugSquadTeam this Friday.

**Comment by wilsonge** [comment]
@C-Lodder you need to commit a package-lock to go with this otherwise we won't get the new deps

**Comment by wilsonge** [comment]
@C-Lodder still wrong. package-lock.json has tinymce still at version 5.0.1 for example. whereas in this pr you're trying to bump it to 5.0.9. You need to run `npm update` not just `npm install`

**Comment by C-Lodder** [comment]
@wilsonge already tried. Nothing to commit

**Comment by C-Lodder** [comment]
@wilsonge done. Has to revert `babel-preset-minify` back to `0.4.3` as the later version was causing issues

**Comment by wilsonge** [comment]
Javscript tests are still failing

**Pull request closed without merging**
