### PR TITLE
[4.0] Rename Levels to Access Levels in system dashboard

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #29550 .

### Summary of Changes
Rename text in system dashboard

### Testing Instructions
Go to system dashboard

### Actual result BEFORE applying this Pull Request
"Levels"

### Expected result AFTER applying this Pull Request
"Access Levels"

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not such a simple solution. Unfortunately we have at least three different terms being used for the same thing.

**Comment by richard67** [comment]
I can confirm that this PR solves issue #29550 according to its description, i.e. the menu item title in the system dashboard is consistent with the one in the users dashboard and the left side navigation menu.

But when following that menu item, the title of the page isn't consistent with the menu item title in the left side menu, see green and red marks in the following screenshot:

j4-pr31832_3

There are more places where we use "Viewing Access Level":

```
richard@vmkubu02:~/lamp/public_html/joomla-cms-4.0-dev$ find ./ -type f -name "*\.ini" -exec grep -iHn "viewing access level" {} \;
./administrator/language/en-GB/com_users.ini:174:COM_USERS_LEVELS_TABLE_CAPTION="Table of Viewing Access Levels"
./administrator/language/en-GB/com_users.ini:224:COM_USERS_NO_LEVELS_SELECTED="No Viewing Access Levels selected."
./administrator/language/en-GB/com_users.ini:264:COM_USERS_SEARCH_ACCESS_LEVELS="Search Viewing Access Levels"
./administrator/language/en-GB/com_users.ini:278:COM_USERS_SUBMENU_LEVELS="Viewing Access Levels"
./administrator/language/en-GB/com_users.ini:335:COM_USERS_VIEW_EDIT_LEVEL_TITLE="Users: Edit Viewing Access Level"
./administrator/language/en-GB/com_users.ini:339:COM_USERS_VIEW_LEVELS_TITLE="Users: Viewing Access Levels"
./administrator/language/en-GB/com_users.ini:341:COM_USERS_VIEW_NEW_LEVEL_TITLE="Users: New Viewing Access Level"
richard@vmkubu02:~/lamp/public_html/joomla-cms-4.0-dev$
```
I think we should consistently use either "Access Level" or "Viewing Access Level" wherever possible (but the latter could be a bit long).

So I agree with @brianteeman that there is more to be cleaned up.

@bembelimen Do you want to fix that with this PR here? Or shall it be done with another PR?

The column title "Level Name" (see orange marks in the above screenshot) are ok in this context, I think.

**Comment by ceford** [comment]
Looked at this with and without patch. For me it is the word **Viewing** that makes me scratch my head. What does it mean (rhetorical). Could it be left out?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31832">issues.joomla.org/tracker/joomla-cms/31832</a>.</sub>

**Comment by brianteeman** [comment]
@richard67 a long time ago I tried with Chris Davenport to standardise these strings and we just gave up. There are so many in so many places and as for consistency well that's a complete mystery

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 01266d6f67b98733a1881705f2690f171082c72e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31832">issues.joomla.org/tracker/joomla-cms/31832</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 01266d6f67b98733a1881705f2690f171082c72e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31832">issues.joomla.org/tracker/joomla-cms/31832</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31832">issues.joomla.org/tracker/joomla-cms/31832</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
This should not have been merged it is not correct
I will do a correction

**Pull request merged**
