### PR TITLE
Add missing input filter to tags

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Missing input filter to tags. cc @dgt41 

### Testing Instructions

Apply this patch and confirm you can still can use the frontend tags seach

### Expected result

Still works

### Actual result

Works but without input filter

### Documentation Changes Required

None

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 0aa358b3e8fcb6b6cc0de246a2a4780b7144828d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15950">issues.joomla.org/tracker/joomla-cms/15950</a>.</sub>

**Comment by brianteeman** [comment]
does this mean that all uses of 'integer' need to be changed to 'int' ??

**Comment by mbabker** [comment]
> does this mean that all uses of 'integer' need to be changed to 'int' ??

Actually, no... https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filter/input.php#L150-L151

**Comment by brianteeman** [comment]
Now I am more confused why it is being changed here.  Guess I have lots to learn

**Comment by zero-24** [comment]
> Now I am more confused why it is being changed here. Guess I have lots to learn

I have changed it based on the doc block: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filter/input.php#L116 As Michael pointed we don't need to change that but we should be consistend there i think.

**Comment by franz-wohlkoenig** [comment]
Installing PR failed:
bildschirmfoto 2017-05-23 um 15 22 21
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Then you're not on the right Joomla version.  That file most assuredly exists in 3.7 (staging), with the namespacing effort it doesn't exist in 3.8.

**Comment by brianteeman** [comment]
Always test on staging unless it says it is for a different version

**Comment by franz-wohlkoenig** [comment]
Thanks for Info. I updated from 3.7.3-dev cause got Message to update.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 0aa358b3e8fcb6b6cc0de246a2a4780b7144828d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15950">issues.joomla.org/tracker/joomla-cms/15950</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
