### PR TITLE
[4.4] Fix the actions menu in the admin isn't working on mobile

### PR DESCRIPTION
**Pull request by AkameOuO**
Pull Request for Issue #44198 .

### Summary of Changes

Fix the actions menu in the admin isn't working on mobile

### Testing Instructions

Select one or more articles / users from the list. Then click in the top right corner to open the menu and click on 'Actions'.

### Actual result BEFORE applying this Pull Request

The whole menu is closed.

### Expected result AFTER applying this Pull Request

Open the submenu to give you a choice

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@hans2103 Could you have a look on this PR here and the corresponding issue #44198 ? It seems to me that it was introduced with your PR #43891 , or at least this PR modifies what you had introduced with your PR.

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 43c6243e11790b677e1f186744a2b1471d2fcce9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44199">issues.joomla.org/tracker/joomla-cms/44199</a>.</sub>

**Comment by richard67** [comment]
@hans2103 Thanks for checking and testing.

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 43c6243e11790b677e1f186744a2b1471d2fcce9<br /><br />Tested successfully on 4.4.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44199">issues.joomla.org/tracker/joomla-cms/44199</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44199">issues.joomla.org/tracker/joomla-cms/44199</a>.</sub>

**Comment by MacJoom** [comment]
Thank you

**Pull request merged**
