### PR TITLE
[3.x] Admin registration emails

### PR DESCRIPTION
**Pull request by brianteeman**
Only send email notificiations  only to all users with user creating permissions and receiving system emails

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Tested with this PR - unfortunately the same thing:

None - Users with no Admin rights receives the mail
Self - Users with no Admin rights receives the mail
Administrator - Only Admin gets the mail

**Comment by brianteeman** [comment]
All 3 cases worked for me

https://user-images.githubusercontent.com/1296369/153448678-8c48860d-a35c-474b-9516-b87bb785b982.mp4

**Comment by coolcat-creations** [comment]
Thank you for rechecking, I checked the files and the update package did not update the model. Weird. I Will copy paste your code and check again.

**Comment by coolcat-creations** [comment]
Ok I tested now:

None - Test successful
Self - Test successful
Admin - My Provider Blocked me hahaha - will report this in a few

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 145132b283660e936acccc573579bf49cff567ae<br /><br />Thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36997">issues.joomla.org/tracker/joomla-cms/36997</a>.</sub>

**Comment by coolcat-creations** [comment]
Oh I hope my partial test and Brians recording and yours is enough no idea when hosting.de will unblock me. And thank you @brianteeman  for this fast reaction and fix!

**Comment by brianteeman** [comment]
@coolcat-creations reconfigure global config to test with mailtrap.io

**Comment by brianteeman** [comment]
@zero-24 technically this is a JSST issue so please check it carefully, merge quickly and it will also need to be merged into 4.1

**Comment by coolcat-creations** [comment]
I could test now the 3rd case and it was successful! Thank you!

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 145132b283660e936acccc573579bf49cff567ae<br /><br />Successful tested as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36997">issues.joomla.org/tracker/joomla-cms/36997</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36997">issues.joomla.org/tracker/joomla-cms/36997</a>.</sub>

**Comment by coolcat-creations** [comment]
Seems it did not make it into todays release altough its security related :-(

**Comment by brianteeman** [comment]
Only so much I can do :(

**Comment by zero-24** [comment]
Yes will be shipped with 3.10.7 sorry took the wrong milestone thanks for correction @Quy

**Comment by zero-24** [comment]
Merging thanks :-)

**Comment by brianteeman** [comment]
thanks

**Comment by coolcat-creations** [comment]
Thank you everyone

**Pull request merged**
