### PR TITLE
[4.0] Improve list status buttons structure/styling

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

- Remove the "feature/unfeature" buttons in each row (use toolbar instead)
- Put the "checkin button" in the Status column
- Use more vibrant colours for the status buttons
- Change the Hits, Votes and Ratings badges to use the same colour

### Testing Instructions

- Check articles list

### To-Do

- [ ] Rest of list views

### Screenshot

screeny

### CODE REVIEW

**Comment by dgt41** [comment]
@C-Lodder you missed the dnd hamburger icon (disabled or hidden if dnd is not enabled)
Other than that 👍

**Comment by C-Lodder** [comment]
@dgt41 - done (`opacity: .5`)

**Comment by brianteeman** [comment]
Contacts can be featured as well

**Comment by C-Lodder** [comment]
@brianteeman yup. Basically whichever component supports featured/unfeatured, the button in each row will be removed.

**Comment by brianteeman** [comment]
It was a statement not a question. ;)
You need to.update the other view

**Comment by C-Lodder** [comment]
It's on my to-do list ;)

**Pull request closed without merging**
