### PR TITLE
[4.0] Newsfeeds image alt

### PR DESCRIPTION
**Pull request by brianteeman**
Continues the work of  #31318 and #31323 by correcting the behaviour of the alt text and changing the strings to match the work done in #31318

### Background
To read why this change is very important see #31318 

### Testing Part 1
Testing is really easy. No npm, js or css involved.
Merge the pull request and then create a newsfeed (you can use https://community.joomla.org/blogs/community.feed and in the options add a first and second image

image
### Testing Part 2
Please test three scenarios when you display the newsfeed from the menu

1. Image Description (Alt Text) = Empty
No Description = unchecked

2. Image Description (Alt Text) = "some description"
No Description = unchecked

3. Image Description (Alt Text) = Empty
No Description = checked

The expected behaviour for each of these tests is

1.``
2. `some description`
3. ``
or ``

PLEASE do not comment on what you think the code does but apply the PR and test it. Getting very tired of people blocking PR with their comments without actually testing the code.

cc @carcam

### CODE REVIEW

**Comment by richard67** [comment]
Strange, this PR doesn't appear in the issue tracker.

**Comment by Quy** [comment]
Tested successfully.

**Comment by BertaOctech** [comment]
Hi,
Is this issue waiting for tests?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31357">issues.joomla.org/tracker/joomla-cms/31357</a>.</sub>

**Comment by alikon** [comment]
yes :+1:

**Comment by snehal0904** [comment]
Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31357">issues.joomla.org/tracker/joomla-cms/31357</a>.</sub>

**Comment by richard67** [comment]
@snehal0904 Could you mark your test result in the issue tracker? Just go to the PR here https://issues.joomla.org/tracker/joomla-cms/31357 , use the "Test this" button, select the appropriate test result and the submit. Thanks in advance.

**Comment by ghost** [comment]
@snehal0904 please mark your test as successfully at issue-tracker.

**Comment by snehal0904** [comment]
@gostn I tried this but I don't know why for this particular issue Test this button is not present.

**Comment by ghost** [comment]
@snehal0904 you're right, there is no test this-button for this pr; don't know why.

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
