### PR TITLE
[5.0] Remove deprecated lang string debug plugin

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the deprecated language strings as marked in #40469 

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/101/

### CODE REVIEW

**Comment by HLeithner** [comment]
are we able to get a removal PR for manual migration 5.0 in the b/c removal section? also we need a PR for 4.4 to deprecate the strings.

**Comment by brianteeman** [comment]
yeah - forgot about the docs - doing it now

**Comment by HLeithner** [comment]
Hmm what's with https://github.com/joomla/Manual/pull/101#discussion_r1184010867 is this valid?

**Comment by brianteeman** [comment]
> Hmm what's with [joomla/Manual#101 (comment)](https://github.com/joomla/Manual/pull/101#discussion_r1184010867) is this valid?

Not sure but it doesnt apply to this PR anyway

**Comment by heelc29** [comment]
@brianteeman Can you please update this PR?
image

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 3d09a669d10c8f3b68d4acc14399ccf876385cca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40470">issues.joomla.org/tracker/joomla-cms/40470</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3d09a669d10c8f3b68d4acc14399ccf876385cca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40470">issues.joomla.org/tracker/joomla-cms/40470</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40470">issues.joomla.org/tracker/joomla-cms/40470</a>.</sub>

**Pull request closed without merging**
