### PR TITLE
[com_content] Featured articles tag filtering

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This fixes tag filtering in Featured Articles view in administrator.

### Testing Instructions

Create some featured articles with tags.
Go to Featured Articles in administrator.
Filter by tags.

### Expected result

Featured articles filtered by tags.

### Actual result

Featured articles not filtered by tags.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
CC @csthomas as this is copypasta from #19284.

**Comment by csthomas** [comment]
It is OK by code review. I will test it later.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1ca980ca35ae59144c3a5f4fd45f7b0620eb6231<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21138">issues.joomla.org/tracker/joomla-cms/21138</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 1ca980ca35ae59144c3a5f4fd45f7b0620eb6231<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21138">issues.joomla.org/tracker/joomla-cms/21138</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21138">issues.joomla.org/tracker/joomla-cms/21138</a>.</sub>

**Pull request merged**
