### PR TITLE
[4.0] Reverse the order of articles in column 'ordering'

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

A refreshed solution for Joomla 4 based on @alikon PR #8576.

Support for updates existed articles in joomla 3.x to 4.0:

- reversing the order in the featured/frontpage table
- reversing the order in the article table per category.

Two indexes have been added to speed up the order change.

### Testing Instructions
See #8576

### CODE REVIEW

**Comment by alikon** [comment]
we need to reconsider this with more attention 
IMHO, 
there will be a significant performance gain

**Comment by richard67** [comment]
@csthomas Could you update your branch with latest 4.0-dev and solve conflicts in files `administrator/components/com_content/Model/ArticleModel.php` and `installation/sql/mysql/joomla.sql`?
Thanks in advance.

**Comment by Quy** [comment]
@richard67 I think this PR needs a new owner as he has been offline for awhile.

**Comment by roland-d** [comment]
Since the owner has left I will close this PR, if anyone is interested in picking this up it can always be reopened or a new PR created.

**Comment by alikon** [comment]
this went out of my radar
a new PR is coming

**Pull request closed without merging**
