### PR TITLE
[a11y] change ordered list in blog-links to unordered list

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue this issue .

### Summary of Changes
This PR will change the unordered list of com_content > category > blog-links.php into an unordered list.
The list is no sequential information but a list of items where the order is not relevant. 
Therefor an unordered list should be used. 

`<ul></ul>` instead of `<ol></ol>`

### Testing Instructions

- Joomla test environment with demo sample data. 
- Go to Sample Layouts > Blog
- Scroll to the pagination and notice a single link with title = _Welcome to your blog_

### Actual result BEFORE applying this Pull Request

Scherm­afbeelding 2023-05-15 om 16 05 18

### Expected result AFTER applying this Pull Request

Scherm­afbeelding 2023-05-15 om 16 05 37

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@hans2103 Could you remove the icon/emoji from the title of this PR? I remember that icons in PR titles have confused some of our tools in past. Thanks in advance.

**Comment by brianteeman** [comment]
For reference these lists were made into ordered lists by the accessibility team in 2012 https://developer.joomla.org/joomlacode-archive/issue-29827.html

**Comment by chmst** [comment]
@brianteeman no need for finger pointing. @brianteeman did not find the issue, but the accessibility team did.

**Comment by brianteeman** [comment]
it is NOT finger pointing - why always looking at the bad :) :-x

I was simply pointing it out that the code is an ordered list because the accessibility in the past changed it to an ordered list so presumably they had a reason for doing so and as @angieradtke is still around from that time it might be a good idea to find out why before reverting their changes.

**Comment by hans2103** [comment]
> For reference these lists were made into ordered lists by the accessibility team in 2012 https://developer.joomla.org/joomlacode-archive/issue-29827.html

Thank you for finding out when these lists where changed into ordered lists.

Apart from what the team thought was right in the past I think we have to change it now. The list is no sequential information but a list of items where the order is not relevant.
Therefor an unordered list should be used.

Do you agree with that argument?
If yes... can this pr be tested and merged?

And if merged, I will create another pr to apply the same change to other ordered lists.

**Comment by sandewt** [comment]
In addition to the previous.

An unordered list makes here the most sense and is therefore preferred, because:
- _Unordered lists_ are used when the order of the items is not relevant. List items in unordered lists are marked with a bullet.
- _Ordered lists_ are used for sequential information and are automatically enumerated by the browser.

source: https://www.w3.org/WAI/tutorials/page-structure/content/

**Comment by HLeithner** [comment]
> In addition to the previous.
> 
> An unordered list makes here the most sense and is therefore preferred, because:
> 
> * _Unordered lists_ are used when the order of the items is not relevant. List items in unordered lists are marked with a bullet.
> * _Ordered lists_ are used for sequential information and are automatically enumerated by the browser.
> 
> source: https://www.w3.org/WAI/tutorials/page-structure/content/

why makes an unordered list more sense then an ordered? isn't the order the most important thing on a pagination?

As unordered list I would expect a grocery store list but not the index of book which the pagination actually is.

**Comment by chmst** [comment]
An ordered list indicates that the user has to follow steps in the given order. Like a cooking receipe. 
In the pagination the user can choose a pagenumber as he wants. fist page 10, then page 2, or the 20th link first then.

**Comment by sandewt** [comment]
> why makes an unordered list more sense then an ordered? isn't the order the most important thing on a pagination?

> An ordered list indicates that the user has to follow steps in the given order. Like a cooking receipe.

Now I'm starting to doubt, because these arguments are very convincing.

So went to look at the code from Bootstrap, that uses Joomla. 
See code Bootstrap v5.2. They use `ul` for the pagination: (probably the most basic?)
```
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>
```
Source: https://getbootstrap.com/docs/5.2/components/pagination/

The two questions I'm asking now is why `ul` and why would Joomla differ from Bootstrap?

**Comment by hans2103** [comment]
This PR does not change the HTML used for pagination. 
This PR only changes the HTML for the list above pagination.
See screenshot... the list with a single item with title "Welcome to our blog".

The pagination is not in this scope.

**Comment by richard67** [comment]
@HLeithner I think you misunderstood the PR, like I did at the first time. The relevant thing is not the pagination, it is the small link shown above it. Hard to see in the screenshots.

**Comment by sandewt** [comment]
> The pagination is not in this scope.

Good of you to mention this.

**Comment by hans2103** [comment]
I like it that we're on the same track now. Please use the same energy as used in discussing this issue for testing this issue. ;-)

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 8157e31800283a702ae57732223a131ff821c082<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40600">issues.joomla.org/tracker/joomla-cms/40600</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 8157e31800283a702ae57732223a131ff821c082<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40600">issues.joomla.org/tracker/joomla-cms/40600</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40600">issues.joomla.org/tracker/joomla-cms/40600</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hans @hans2103 for the PR!

**Comment by brianteeman** [comment]
Should this really have been merged in a patch release.

I understand it is being treated as a bug but unlike most bug fixes this changes the visual output of the site which is a breaking change that a user would not epxect in a patch release.

**Comment by obuisard** [comment]
Thanks Brian @brianteeman, I understand the concern. I merged this as it has a really low impact and did not deserve to be ignored for another 5 months. The visual will change, but was not right in the first place. That's why I made this decision.

**Comment by brianteeman** [comment]
Thanks for the response @obuisard #While I appreciate the explanation I will stick with my view that it is wrong in this specific case. It's been wrong for 12 years without comment, until now, so its hardly urgent and there is a remedy available to all users right now (a template override). There are a huge number of other pull requests that user's have reported that are now waiting for 5+ months for a fix and I just dont see what makes this one special.

**Comment by obuisard** [comment]
Hans @hans2103, I will reverse this PR for now, this fix could still impact sites that rely on the <ol> being used.

**Comment by richard67** [comment]
@obuisard Should this be done in 5.0? Or even 6.0?

**Comment by chmst** [comment]
Agree with reverse of this PR. It is a bug but not as urgent. It would be nice to have the fix in 5.0 if possible, together with a fix for all occurencies.

**Comment by hans2103** [comment]
retried it on branch = 5.0-dev with PR = https://github.com/joomla/joomla-cms/pull/40633

**Pull request merged**
