### PR TITLE
[5.0] Fix missing dependency for editors asset

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes
The editors asset is depend from JoomlaDialog, hovewer the dependency is not defined.

### Testing Instructions
Run `npm install`
In dashboard select Add module => Custom HTML module.
Inspect browser dev console

### Actual result BEFORE applying this Pull Request
An error `Failed to resolve module specifier "joomla.dialog"`

### Expected result AFTER applying this Pull Request
No error

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Reference:
- https://github.com/joomla/joomla-cms/pull/40202

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1209779ebe7c196333dc11f5a6a0f371ec00bdf4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41859">issues.joomla.org/tracker/joomla-cms/41859</a>.</sub>

**Comment by HLeithner** [comment]
Strange I don't have this error with beta2

**Comment by HLeithner** [comment]
ok found the error, thanks

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on 4b519b83fee2829431ec2791450164d55b874b1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41859">issues.joomla.org/tracker/joomla-cms/41859</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
