### PR TITLE
Revert the removal of deprecated code

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #15440 .

### Summary of Changes

Restore deprecated code, this should be removed in J4 not yet!

### Testing Instructions

Review the code!

### Documentation Changes Required

@rdeutz

### CODE REVIEW

**Comment by rdeutz** [comment]
could you @avjoomla test if the fix solves the problem

**Comment by infograf768** [comment]
Release Blocker?

**Comment by rdeutz** [comment]
@infograf768 we need to test and merge before release

**Comment by infograf768** [comment]
Tested that it does not break the new calendar (just to be sure). I do not have a sample code to test the original issue.

**Comment by wilsonge** [comment]
Added release blocker tag

**Comment by avjoomla** [comment]
Just installed a new installation of Joomla! 3.7 as released today.
Sadly there are to typos in the code which was merged into the behavior.php with PR #15441

Line 381 (wrong)
JHtml::_('stylesheet', 'system/calendarjos.css', array('version' => 'auto', 'relative' => true), $attribs);
correct:
JHtml::_('stylesheet', 'system/calendar-jos.css', array('version' => 'auto', 'relative' => true), $attribs);

Line 383 (wrong)
JHtml::_('script', $tag . '/calendarsetup.js', array('version' => 'auto', 'relative' => true));
correct
JHtml::_('script', $tag . '/calendar-setup.js', array('version' => 'auto', 'relative' => true));

In both cases the file name is incorrect, the minus characters in file names are missing.

Regards,
Aicha
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15441">issues.joomla.org/tracker/joomla-cms/15441</a>.</sub>

**Comment by zero-24** [comment]
Can you please send that as PR against staging?

**Pull request merged**
