### PR TITLE
[4.0] Cassiopeia module header class

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes a silly little error to make the module header class work as intended.

### To test
Create a module and publish it in the sidebar-right position
In the module options give it a header class eg broken

### before
`<h3 class="brokencard-header broken"`

### After
`<h3 class="card-header broken"`

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0c66a4d3283c68e79de517c79d6365229e4bf0be<br /><br />Tested successfully in Beta6-dev of 23 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31771">issues.joomla.org/tracker/joomla-cms/31771</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0c66a4d3283c68e79de517c79d6365229e4bf0be<br /><br />but must read: <h3 .....> :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31771">issues.joomla.org/tracker/joomla-cms/31771</a>.</sub>

**Comment by brianteeman** [comment]
@ChristineWk I would love to say that it was deliberate to see if anyone read the instructions but it wasn't. 

Updated test instructions now

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31771">issues.joomla.org/tracker/joomla-cms/31771</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
