### PR TITLE
Hathor fails to detect disabled modules (redo)

### PR DESCRIPTION
**Pull request by brianteeman**
Redo of #12405 to resolve conflicts (i must learn how to do this properly)

See #12405 for description and test instructions

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 92d8edf0d608244d954810b63dec9b64adaf764a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12925">issues.joomla.org/tracker/joomla-cms/12925</a>.</sub>

**Comment by RonakParmar** [comment]
After patch applied:
screen shot 2016-11-17 at 05 14 37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12925">issues.joomla.org/tracker/joomla-cms/12925</a>.</sub>

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 92d8edf0d608244d954810b63dec9b64adaf764a<br /><br />Test result identical to the above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12925">issues.joomla.org/tracker/joomla-cms/12925</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
