### PR TITLE
Solves 9326: clean beta 4 install without pre-created database doesn't work

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9326 .
#### Summary of Changes

Solves https://github.com/joomla/joomla-cms/issues/9326
#### Testing Instructions
1. Use beta 4 or latest staging and proceed with clean joomla install
2. Do step 1 of install
3. Check code difference in this PR and change that file (/libraries/joomla/database/driver.php) before executing step 2 (database) of install.
4. On step 2 of install enter a new database (don't use one that already exists). before this change it wouldn't work, after this change it will work.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@richard67 can you test this?

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 7cacd55668b182f563626c53a6bfb6d88e38eee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9328">issues.joomla.org/joomla-cms/9328</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva I just was testing new install for several db and php versions but could not confirm problems reported in issue #9326 yet. But in 1 case my server got extremely slow. Because I was dealing with this piece of code, too (also wanted to change it to support utf8mb4), I would say by code review that your change with this PR here corrects a bad mistake.

@wilsonge Should be merged by code review, it is obviosly correcting a bad mistake, no need to test that.

**Comment by andrepereiradasilva** [comment]
@richard67 it only happens when you create a new database on install on a utf8 capable server. If you use one that already exists it works before this PR.

**Comment by Bakual** [comment]
I could replicate the issue and the proposed fix solves it.

Also current code is obviously wrong as there is an undefined variable (`$collation`)

**Comment by richard67** [comment]
Yes, just got that after reading comments to the issue. I can test but would be nice if I could save the work because it gets merged before.

**Comment by andrepereiradasilva** [comment]
yeah sure

**Comment by richard67** [comment]
Well I start preparing the test ... is a bit uncomfortable because I test on remote shared host, not on local PC.

**Comment by richard67** [comment]
ahhh ... i cannot test this i am afreaid ... will not have privileges maybe to create new db with Joomla! installation.

**Comment by richard67** [comment]
Maybe @stellainformatica can test?

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 7cacd55668b182f563626c53a6bfb6d88e38eee4<br /><br />Ok, now I can install Joomla 3.5 beta4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9328">issues.joomla.org/joomla-cms/9328</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on 7cacd55668b182f563626c53a6bfb6d88e38eee4<br /><br />Tested in localhost, it solves the issue I reported here https://issues.joomla.org/tracker/joomla-cms/9326 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9328">issues.joomla.org/joomla-cms/9328</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Could be worth to make a Beta 5 just with this Patch included.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9328">issues.joomla.org/joomla-cms/9328</a>.</sub>

**Comment by wilsonge** [comment]
I don't have the resources to release on laptop :(

**Comment by mbabker** [comment]
@wilsonge Do you need a b5 package posted?  Begrudgingly I still have access to everything to do it.

**Comment by Kubik-Rubik** [comment]
@wilsonge @mbabker Beta 5 should be released to fix this issue. It would be great if you could create it, Michael. Thank you!

**Comment by mbabker** [comment]
On it.  Expect everything to be published in next half hour.

**Comment by Kubik-Rubik** [comment]
Welcome back, my friend! :-)

Thank you!

**Comment by mbabker** [comment]
Done.  https://www.joomla.org/announcements/release-news/5649-joomla-3-5-beta-5-released.html

**Comment by Kubik-Rubik** [comment]
Thank you @mbabker!

**Comment by wilsonge** [comment]
Thanks so much michael!

**Pull request merged**
