### PR TITLE
Fix simplecolors and improve minicolors scripts of the color field, to work with the subform field

### PR DESCRIPTION
**Pull request by Fedik**
Fix simplecolors and improve minicolors scripts of the color field, to work with the subform field

### Testing Instructions
Make subform field with the color field, in the template, in `templateDetails.xml` somewhere [here](https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/templateDetails.xml#L49) . 
Example subfrom field (copy/paste to `templateDetails.xml`):
```xml
<field name="colors1" type="subform" label="Colors Test" multiple="true">
	<form>
		<field name="color1" type="color" label="Color1" control="simple"/>
		<field name="color2" type="color" label="Color2" />
	</form>
</field>
```

### Expected result
The color fields in the subform should work 

### Documentation Changes Required
none

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
- can you give Instructions where to put example Code in?
- also what "color field works" mean? Show different colors i guess is meant?

**Comment by Fedik** [comment]
@franz-wohlkoenig I have updated the comments 

> also what "color field works" mean

they should work 😄  that all.
for `type="color"` there no visible difference, and for `type="color" control="simple"` it should work now (before it was broken)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 12baa1b4dd71f650406a9351fb60246f06b51f0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15974">issues.joomla.org/tracker/joomla-cms/15974</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 12baa1b4dd71f650406a9351fb60246f06b51f0e<br /><br />This fixes issue #15958 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15974">issues.joomla.org/tracker/joomla-cms/15974</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
