### PR TITLE
[4.1] Change scheduler filter search desc

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change language string for consistency.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e80a6307a3ba78e8cc714dc5e3acf780c701d060<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36637">issues.joomla.org/tracker/joomla-cms/36637</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on e80a6307a3ba78e8cc714dc5e3acf780c701d060<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36637">issues.joomla.org/tracker/joomla-cms/36637</a>.</sub>

**Comment by rjharishabh** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36637">issues.joomla.org/tracker/joomla-cms/36637</a>.</sub>

**Comment by tecpromotion** [comment]
Please add "Language Change" Label again @richard67 or @Quy

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
