### PR TITLE
[3.X][plugin][actionlog] change the action to joomlaupdate

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .
as requested on the JBS Glip channel after the merge of #30157 

### Summary of Changes
change `'action'      => 'joomlaupdate',
`

### Testing Instructions
code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 794bedb9b27cf54f7db12d1aa1eed933ad338cca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30407">issues.joomla.org/tracker/joomla-cms/30407</a>.</sub>

**Comment by richard67** [comment]
Not sure if a code review is enough. A valid btest would be to apply this patch on a clean staging branch and then update to the update package which has been built for this PR. The custom update URL and download packages for such an update can be found here at the bottom of this PR (if necessary use the "Show all checks" to expand the checks):
j3-pr-downloads

In this way you can do an update, and the patch of this PR is applied before and after the update.

Unfortunately I don't have time right now to test that.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 794bedb9b27cf54f7db12d1aa1eed933ad338cca<br /><br />Well, I could not resist to do a real test.

All ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30407">issues.joomla.org/tracker/joomla-cms/30407</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30407">issues.joomla.org/tracker/joomla-cms/30407</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
