### PR TITLE
Show Redirect Status Code in Redirection List

### PR DESCRIPTION
**Pull request by jo-sf**
This PR adds a new column to the redirection list if the advanced mode is active. In this new column you can see the redirect status code defined for each redirected URL.

Test instructions:
- Disable advanced mode (if enabled) => the redirection list consists of 8 columns, the redirect status code ist not shown.
- Enable advanced mode => the redirection list consists of 9 columns, the redirect status code is shown in a column between the 404 Hits and the ID.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Just one comment, you need to add the `a.header` ordering (ASC and DESC) to the filter xml to (https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/models/forms/filter_links.xml#L43).

This way it will appear in the ordering select box (and be selected when you order by that colunm).

**Comment by jo-sf** [comment]
@andrepereiradasilva 
Thanks for your comment, I just added the two lines to filter_links.xml (the necessary messages were already defined in en-GB.com_redirect.ini).

The only problem I see with this change is that the redirect status code is shown only if advanced mode is on. but as far as I understand this filter_links.xml definition the two ordering variants will be shown always - even when advanced mode is off. Is there any way to show them conditionally?

**Comment by andrepereiradasilva** [comment]
That i know of, as it is now, there is only one case that happens, the language associations (only exis when site is multilinguage).

See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/filter_articles.xml#L101-L102

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9df9c9d8d30278966498ad9c06ad06cb84c20b31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by brianteeman** [comment]
When you are not in advanced mode the Status Code column disappears but the Sort by Status Ascending in the dropdown select is still present<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman that's what @jo-sf and i discussed in the comments above.

There is not, that i know of, a way to do this in the XML (see comments above).

You have two options:
1. Don't add to the xml. Problem: when in advanced mode you will have a problem in the filter when ordering by that columns
2. Add to xml. Problem: it appear in the ordering list when you don't have advanced mode and the column don't exist.

BTW what is advance mode for? Can't all the options exist without the advance mode option? There is no other component in joomla that does this.

**Comment by brianteeman** [comment]
OK - I have no problem with it being in the dropdown list if that cannot be
avoided.

Advanced mode was one of those compromises. Someone wanted to add the
functionality. Someone else felt it would confuse regular users

On 4 May 2016 at 10:34, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> that's what @jo-sf
> <https://github.com/jo-sf> and i discussed in the comments above.
>
> There is not, that i know of, a way to do this in the XML (see comments
> above).
>
> You have two options:
> 1. Don't add to the xml. Problem: when in advanced mode you will have a
> problem in the filter when ordering by that columns
> 2. Add to xml. Problem: it appear in the ordering list when you don't have
> advanced mode and the column don't exist.
>
> BTW what is advance mode for? Can't all the options exist without the
> advance mode option? There is no other component in joomla that does this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10217#issuecomment-216811148>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
IMO this "Advanced mode" confudes even further. but ok...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9df9c9d8d30278966498ad9c06ad06cb84c20b31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9df9c9d8d30278966498ad9c06ad06cb84c20b31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by brianteeman** [comment]
I am setting this to Needs Review so that the CMS maintainers can make a decision about the dropdown select issue - hopefully that wil me made at the sprint this weekend<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by jo-sf** [comment]
I think the advanced mode allowing to set any HTTP status code beside 301 (the default) is OK, since setting an inappropriate code here might lead to problems later (see the hint shown when passing over the field label).

But we could show the status code column always even if the advanced mode is off. In this case the default status code (301) is shown and there is no problem with showing the "sort by" alternatives for this column. Moreover it would remove some complexity from the code...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i agree

**Comment by jo-sf** [comment]
@brianteeman 
What do you think about always showing the status code column?

If you agree too I'll change my PR accordingly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by brianteeman** [comment]
I see no reason why not myself so go for it and lets see what others think

On 4 May 2016 at 20:39, jo-sf <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> What do you think about always showing the status code column?
>
> If you agree too I'll change my PR accordingly.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10217
> <https://issues.joomla.org/tracker/joomla-cms/10217>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10217#issuecomment-216978019>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jo-sf** [comment]
Now the "Status Code" column will be shown always regardless of the setting of the advanced mode. So the two items in the sorting dropdown menu are always valid.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 60a3b7e055247afcd74a6d5449634e8f2f8ee229<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by jo-sf** [comment]
@andrepereiradasilva 
Wow you're really fast!

**Comment by andrepereiradasilva** [comment]
with the patchtester is easy :wink:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 60a3b7e055247afcd74a6d5449634e8f2f8ee229<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10217">issues.joomla.org/joomla-cms/10217</a>.</sub>

**Pull request merged**
