### PR TITLE
[bug] Do not force value validation (media field)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

This step is unnecessary and it breaks some 3rd PD adapters

### Testing Instructions
- Create a new article
- Select an intro image
- type the same path for the full image
- save the article 
- reopen

Everything works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 26176b4e42b2ef7802fbc25622bc1d217b71522e<br /><br />Tested it with the restricted adapter, before the patch it created an url like when saving the article:

Before save:
images/dprestricted/items/com_content.article/1/actions-list.png#joomlaImage://dprestricted-item/actions-list.png?width=1067&height=457
After save:
images/dprestricted/items/com_content.article/1/actions-list.png#joomlaImage://local-images/dprestricted/items/com_content.article/1/actions-list.png?width=1067&height=457

After applying the patch, the urls do look like:

Before save:
images/dprestricted/items/com_content.article/1/actions-list.png#joomlaImage://dprestricted-item/actions-list.png?width=1067&height=457
After save:
images/dprestricted/items/com_content.article/1/actions-list.png#joomlaImage://dprestricted-item/actions-list.png?width=1067&height=457<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39091">issues.joomla.org/tracker/joomla-cms/39091</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 26176b4e42b2ef7802fbc25622bc1d217b71522e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39091">issues.joomla.org/tracker/joomla-cms/39091</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39091">issues.joomla.org/tracker/joomla-cms/39091</a>.</sub>

**Comment by wilsonge** [comment]
Sorry what validation are we skipping here and why? Breaking 3PDs obviously isn't great. But not really understanding why we're ignoring invalid data

**Comment by dgrammatiko** [comment]
@wilsonge on connectedCallback the element needs to create the preview image. I wrongly forced validating the value (coming from the db) which is obviously wrong. The validation on typing is still intact

**Comment by fancyFranci** [comment]
Thank you for helping 3rd PD adapters!

**Pull request merged**
