### PR TITLE
[4.0] Remove magic quotes

### PR DESCRIPTION
**Pull request by brianteeman**
Final removal of remnants of magic quotes related code

as magic quotes was completely removed in php 5.4 there can never be an instance when it will be triggered in j4

### CODE REVIEW

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 8981bcf6fd7446ecb56c216d5b3784b323c26118<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24320">issues.joomla.org/tracker/joomla-cms/24320</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8981bcf6fd7446ecb56c216d5b3784b323c26118<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24320">issues.joomla.org/tracker/joomla-cms/24320</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24320">issues.joomla.org/tracker/joomla-cms/24320</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
