### PR TITLE
[4.0] Fix double header

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/33687 .

### Summary of Changes
adds a missing div

### Testing Instructions

Navigate to http://example.com/administrator/index.php?option=com_foo where com_foo is not installed.

### Actual result BEFORE applying this Pull Request
Broken

### Expected result AFTER applying this Pull Request
Not Broken

### Documentation Changes Required

Noooo

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on b9980768dc481511449dd45f70ebbd45b355f262<br /><br />This one is fixed, but found something else now ;-) incoming... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33689">issues.joomla.org/tracker/joomla-cms/33689</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on b9980768dc481511449dd45f70ebbd45b355f262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33689">issues.joomla.org/tracker/joomla-cms/33689</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33689">issues.joomla.org/tracker/joomla-cms/33689</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
