### PR TITLE
remove individual https force options 

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #17142 .

### Summary of Changes
Removes the options to force a menu item or login form to be http or https

We should not encourage this at all. A site should either be all http or all https - the options for this in glbal configuration remain

### CODE REVIEW

**Comment by tonypartridge** [comment]
Great @brianteeman , can you also remove the PHP Code using these settings?

**Comment by brianteeman** [comment]
@tonypartridge unless I misread the code (in which case please submit a PR against my branch) the code is used for the force site https option in global configuration

**Comment by tonypartridge** [comment]
I shouldn't look at the code on my phone... I see you are removing them as we were setting them in the form from what I can see. All good, just fix drone ;-)

**Comment by brianteeman** [comment]
i think the drone issue is unrelated

**Comment by zero-24** [comment]
Drone is satisfied now.

**Comment by brianteeman** [comment]
Thanks - that was fast

**Pull request merged**
