### PR TITLE
Fixed url of joomla update error help button

### PR DESCRIPTION
**Pull request by beni71**
Pull Request for Issue #39769 

### Summary of Changes
Fixed/changed the url of the joomla update error help button

### Testing Instructions
(It doesn't update joomla, it generates an error instead)
1. In the backend navigate to System
2. Under "Update" click Joomla. You will see the view of: administrator/index.php?option=com_joomlaupdate
3. Click the button "Upload and Update"
4. Instead of selecting a regular zipped version on Joomla, select a picture of type .png
5. Set the check box "I'm aware that a backup before any update is highly recommended."
6. Click the button "Upload & Install"
7. Confirm the action, if needed and start the installation.
8. This should result in an error like:
grafik
9. Click on the button "Get help with this error"

### Actual result BEFORE applying this Pull Request
Instead of showing a help page, there is an error:

404 - RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist.

=> url: https://help.joomla.org/proxy?keyref=Help43:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en

### Expected result AFTER applying this Pull Request
The following help/doc page should be visualized:

Joomla Update Problems

(the content of this page is under construction)

=> url: https://docs.joomla.org/Special:MyLanguage/J4.x:Joomla_Update_Problems

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/Special:MyLanguage/J4.x:Joomla_Update_Problems
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 072758769c6af54de15bdcb03ce6548172d0bd07<br /><br />I have updated the referenced page with a revised introduction and some screen shots. I also learned a few things! Good to go.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40670">issues.joomla.org/tracker/joomla-cms/40670</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 072758769c6af54de15bdcb03ce6548172d0bd07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40670">issues.joomla.org/tracker/joomla-cms/40670</a>.</sub>

**Comment by brianteeman** [comment]
not convinced that it is correct to change the url from the help domain

**Comment by richard67** [comment]
> not convinced that it is correct to change the url from the help domain

I think it needs to be checked by the release leads. @sdwjoomla @obuisard

**Comment by richard67** [comment]
RTC as it has 2 successful tests (which might get lost in the counter when doing a branch update). But it still requires a final decision.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40670">issues.joomla.org/tracker/joomla-cms/40670</a>.</sub>

**Comment by ceford** [comment]
This particular page is not used as a Help page via a Help button. It is used as an external link. That is why I suggested it should have the J4.x namespace. It is similar to the Forgot your login details? link on the Admin login page.

**Comment by obuisard** [comment]
What I can see at first glance is that the help language key is not translated. The page it points to DOES exist: https://help.joomla.org/proxy?keyref=Help43:Components_Joomla_Update&lang=en. We should probably fix the area in the code where the language key is supposed to be replaced with its translation.

**Comment by obuisard** [comment]
We should probably have
`$helpUrl = Help::createUrl(Text::_('JHELP_COMPONENTS_JOOMLA_UPDATE'), false);`
rather than the new URL.

**Comment by ceford** [comment]
Search for all instance of JHELP_ in the .ini files of a Joomla 4 installation. There are none! Search for all Instance in .php files - there are 4 but no way use them. All of these JHELP language strings were removed for the Joomla 4 release. Look at the bottom of any admin HtmlView page. You will see the actual filename. Example: $toolbar->help('Articles');

**Comment by ceford** [comment]
> Yes, I just realized that looking at the code. Then the proper replacement should be: `$helpUrl = Help::createUrl('Components_Joomla_Update', false);`

No! Leave it exactly as it is in the PR we tested. This is an external link that should not go through the proxy server. And you keep quoting an out of date naming convention. This filename is the same as the title. This is Joomla Update Problems and not Components Joomla Update.

**Comment by sdwjoomla** [comment]
Thanks beni71

**Pull request merged**
