### PR TITLE
Update en-GB.com_config.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Fixed invalid HTML tags

### CODE REVIEW

**Comment by brianteeman** [comment]
Simple and correct change - setting to RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7362">issues.joomla.org/joomla-cms/7362</a>.</sub>

**Comment by wilsonge** [comment]
Should we not use the ```&hellip;``` html entity for the ellipsis?

**Comment by brianteeman** [comment]
https://github.com/joomla/user-interface-text/blob/master/punctuation.md#ellipsis

On 7 July 2015 at 15:38, George Wilson <notifications@github.com> wrote:

> Should we not use the &hellip; html entity for the ellipsis?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7362#issuecomment-119224022>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
OK well what is in this PR reverts the change in your link there to the ellipsis

**Comment by brianteeman** [comment]
In which case please update as per the style guide

On 7 July 2015 at 16:42, George Wilson <notifications@github.com> wrote:

> OK well what is in this PR reverts the change in your link there to the
> ellipsis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7362#issuecomment-119243131>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@aaleksanyants you can fix this by adding a new commit to your branch. If you edit that file here: https://github.com/aaleksanyants/joomla-cms/blob/patch-3/administrator/language/en-GB/en-GB.com_config.ini and commit this this pull request gets updated :smile: :+1:

**Comment by aaleksanyants** [comment]
@zero-24 , when trying to do that I get the message:
There isn't anything to compare.
joomla:staging is up to date with all commits from aaleksanyants:staging. Try switching the base for your comparison.

**Comment by zero-24** [comment]
@aaleksanyants please try to edit file in my comment :) 

go to: https://github.com/aaleksanyants/joomla-cms/blob/patch-3/administrator/language/en-GB/en-GB.com_config.ini
klick the "edit button"
change the file
commit with a message
PR gets updated ;)

**Comment by aaleksanyants** [comment]
But the file is already updated! please search for ** within it and you will see that there are no BOLD tags any more

**Comment by infograf768** [comment]
@aaleksanyants
If I get it right, you should correct the use of `&hellip;`  and replace it by what it was before, i.e. 3 dots `...`

**Comment by aaleksanyants** [comment]
I have replaced three dots with a single ellipsis char itself and it is displayed correctly (because all files are treat as UTF-8 files), so why should I replace it with its HTML entity or revert back to three dots?

**Comment by aaleksanyants** [comment]
Or do you provide HTML entities for all cedils, acutes etc when translating to French?

**Comment by wojsmol** [comment]
@aaleksanyants please see https://github.com/joomla/joomla-cms/pull/7362#issuecomment-119226798

**Comment by aaleksanyants** [comment]
So is it about adding spaces before and after, or about replacing a single char with three dots chars?

**Comment by wilsonge** [comment]
Read this :) https://github.com/joomla/user-interface-text/blob/master/punctuation.md#ellipsis

**Comment by aaleksanyants** [comment]
Your guide says "Each period should have a single space on either side. " But I could not find a single string in language files which would implement that rule. All read more strings contain a space before the first period, but none of them has spaces between periods, ie ._._. (replace undelines with spaces). And if we speak about adding leading and trailing spaces, they are already there …

**Comment by infograf768** [comment]
I guess there is a mistake in that guide
`Each period should have a single space on either side.`
should be read as `Each group of 3 periods should have a single space on either side.`

**Comment by brianteeman** [comment]
Yes I am updating that part

On 9 July 2015 at 10:44, infograf768 <notifications@github.com> wrote:

> I guess there is a mistake in that guide
> Each period should have a single space on either side.
> should be read as Each group of 3 periods should have a single space on
> either side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7362#issuecomment-119891488>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
@aaleksanyants
This the en-GB language, not French or else.
They have decided to NOT use the ellipsis but 3 dots instead.
You for Armenian or I for French can do anything we like :smile:

**Comment by aaleksanyants** [comment]
OK, I have replaced ellipse back to three dots per your request. BTW, I have checked the original version and saw that it had no leading/trailing spaces within the row...

**Comment by brianteeman** [comment]
Yes that was missed when the style guide was created. I have created another PR for some other missing spaces

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b8ce177f1d05f5a003fc63921c2a5e7faea79dc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7362">issues.joomla.org/joomla-cms/7362</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7362">issues.joomla.org/joomla-cms/7362</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a69ab32fcce3b3cc95ec3cfaa62179eeba57148d<br /><br />Only updated the branch to latest staging. All equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7362">issues.joomla.org/joomla-cms/7362</a>.</sub>

**Pull request merged**
