### PR TITLE
[4.0] Improve success message for when you upload a file to a template

### PR DESCRIPTION
**Pull request by particthistle**
### Summary of Changes
Tidying up the message displayed when you upload a file to a template.
- Changed language string COM_TEMPLATES_FILE_UPLOAD_SUCCESS from "File uploaded." to "File uploaded:"
- Added space between language string and the file name uploaded

### Testing Instructions
Apply the patch.
Upload a new file to a site or administrator template.

### Actual result BEFORE applying this Pull Request
Message is compressed.
image

### Expected result AFTER applying this Pull Request
Message is spaced and : precedes file name.
image

### CODE REVIEW

**Comment by Quy** [comment]
Is it even necessary to display the file name? This is not the case in Media Manager.

**Comment by particthistle** [comment]
Necessary: no.
Informative UX feedback: yes.

I'm just correcting the appearance of the message that's already there.

Plus while https://github.com/joomla/joomla-cms/issues/33179 is an issue, if they upload a file with an uppercase extension, they're not going to see it in the folder tree and start scratching their head.

Mentioning "This is not the case in the Media Manager" raises another point. In the media manager when you upload a file of the same name, it prompts you if you want to overwrite it or not. The file upload in the Template manager doesn't prompt you to overwrite, it just throws an error saying file already exists.

**Comment by Quy** [comment]
Let's use `sprintf` instead.

**Comment by particthistle** [comment]
Updated to sprintf.

Ready for testing.

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on c5d13574fb39b5875d766f210f87fc0fd9a88536<br /><br />Works as mentioned.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33181">issues.joomla.org/tracker/joomla-cms/33181</a>.</sub>

**Comment by richard67** [comment]
Failing unit tests in Appveyor and Drone and not related to this PR but to the 4.0-dev branch at the time of the PR's creation. This has been fixed meanwhile in the 4.0-dev branch by PR #33207 .

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c5d13574fb39b5875d766f210f87fc0fd9a88536<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33181">issues.joomla.org/tracker/joomla-cms/33181</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33181">issues.joomla.org/tracker/joomla-cms/33181</a>.</sub>

**Comment by richard67** [comment]
Appveyor failure is not related to this PR.

**Pull request merged**
