### PR TITLE
Change in file en-GB.com_tags.ini

### PR DESCRIPTION
**Pull request by helvecio**
#### String changed:

COM_TAGS_TAG_VIEW_LIST_DESC
#### Summary of Changes

I propose that the sentence "Displays a compact list of items that have been **tagged with** the selected tags" is changed to "Displays a compact list of items that have been **assigned to** the selected tags". The idea here is to avoid the use of the same or similar words while keeping the message clear.

### CODE REVIEW

**Comment by brianteeman** [comment]
I understand what you are trying to do but I dont agree that this makes it clearer. What about going even simpler

COM_TAGS_TAG_VIEW_LIST_DESC="Displays a compact list of items with the selected tags."
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10837">issues.joomla.org/joomla-cms/10837</a>.</sub>

**Comment by helvecio** [comment]
Even simpler and even better. Thank you! I've already added to the pull-request.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cab366388ed0d1c2962668472967132abf1e1d67<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10837">issues.joomla.org/joomla-cms/10837</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on cab366388ed0d1c2962668472967132abf1e1d67<br /><br />Thanks :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10837">issues.joomla.org/joomla-cms/10837</a>.</sub>

**Comment by zero-24** [comment]
RTC :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10837">issues.joomla.org/joomla-cms/10837</a>.</sub>

**Comment by helvecio** [comment]
Newbie question: now all checks have passed, should I close and comment for this PR to be merged?

**Comment by zero-24** [comment]
Hi @helvecio 


RTC means ready to commit. So your Job is basically done. ;) Now we need a Maintainer how do a final review and merge. You can't do that for your self for understandably reason that only a fee people have merge access to the main CMS repo.

Close and comment would mean that this PR can not be merged by the maintainer so please don't so that :)

If an maintainer get the time to review the RTC PRs this here will be on the list too. Thanks for your PR!

**Comment by helvecio** [comment]
Thank you for the clarification @zero-24 !

**Pull request merged**
