### PR TITLE
[4.0] - postgresql some sql fix

### PR DESCRIPTION
**Pull request by alikon**
- default date 1970-01-01 00:00:00
- no AFTER clause

can be merged on review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1a71629eb064ea52402ba391d9ed3d9db586aa89<br /><br />Tested by code review:
1. The PR covers all occurrences of '0000-00-00' or '0000-00-00 00:00:00' in joomla.sql or any schema update sql for PostgreSQL.
2. The PR covers all occurrences of "after" for columns in DDL statements in joomla.sql or any schema update sql for PostgreSQL.
3. There is no occurrence of "before" for columns in DDL statements in joomla.sql or any schema update sql for PostgreSQL to be corrected, too.

I think the errors corrected by this PR were the reason (or some of the reasons) why currently installation of 4.0 with PostgreSQL fails. I will test soon if it works with this PR applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21873">issues.joomla.org/tracker/joomla-cms/21873</a>.</sub>

**Comment by alikon** [comment]
i'm afraid this doesn't cover all the glitch with postgresql... but a start

**Comment by richard67** [comment]
Yes, it solves many problems. What is remaining then is an issue with double backslash in string values, mainly in values for column `namespace` of table `#__extensions`. Not sure if this column still has to be filled by joomla.sql or schema updates because I remember there was a PR merged which fetches the namespace column value from the extensions manifest XML.
As far as I could read in docs, strings with double backslash have to be prepended by an "E" for marking it as escape string. I've tried to fix that here for the extensions table but there are still errors about double backslash reported in the postgresql log file.

**Comment by richard67** [comment]
Ah I just see that pr for the namespace from manifest file is not merged yet: PR #21766 .
So for now we would have to fix those double backslashes in strings, and then postgresql installation should work.
Do you want to do it with this PR here? Or a new one?

**Comment by laoneo** [comment]
I would not mix things. Better to do one issue in one pr, instead of fixing many things in the same pr. Especially for the namespacing column. I would wait what comes out in #21766, before putting much effort into updating the namespaces in the installer file.

**Comment by richard67** [comment]
Yes, I agree. I just see there are more errors with installation on PostgreSQL, mainly from workflow stuff, so we should get this good PR here merged for coming forward.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21873">issues.joomla.org/tracker/joomla-cms/21873</a>.</sub>

**Comment by laoneo** [comment]
Thanks for this one.

**Pull request merged**
