### PR TITLE
[staging] Move HHVM Test fixes to staging

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #12336 
### Summary of Changes

See: #12336
### Testing Instructions

with this PR, the errors would be reduced from 80 to 11
### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @Hackwar !

**Comment by photodude** [comment]
These are exactly the changes I have made in my test branches pending release of hhvm 3.15.2 or 3.16 which will resolve these issues. 

I have been hesitant to submit the change for our call to `pg_set_error_verbosity()`  since I'm unsure of any possible downstream consequences (I assume possibly none, but you know what they say about assuming). I'm also hesitant since this issue is fixed in hhvm 3.15.2. At the same time I have suggested the same change as a possible work around. 

Looks good on code review and travis review.

**Comment by photodude** [comment]
The change for our call to `pg_set_error_verbosity()` is no longer needed as hhvm 3.15.2 has been released. We do still need the change to the separator for the DSN used in the tests.

**Comment by zero-24** [comment]
Thanks closing than.

**Comment by photodude** [comment]
@zero-24 the DSN separator portion of this is still needed.  It just needed to be modified

**Comment by photodude** [comment]
The HHVM patch to fix the DSN separators to allow semicolon or space has been merged, the HHVM 3.16.0 STS release will have this, and is on the list of potential cherry picks for HHVM 3.15.3 LTS. 

HHVM 3.16.0 STS is expected around 10/24/2016 and will automatically be the version tested on Travis CI

**Pull request closed without merging**
