### PR TITLE
[4.0] Unused Use Statements

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
I removed three unused `use` statements.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ae0a1eefc052940cf176e0491fdab74f41d2415f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28327">issues.joomla.org/tracker/joomla-cms/28327</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ae0a1eefc052940cf176e0491fdab74f41d2415f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28327">issues.joomla.org/tracker/joomla-cms/28327</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28327">issues.joomla.org/tracker/joomla-cms/28327</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
