### PR TITLE
not only the domain name, the same address of the user can be in UTF-8. Part 1

### PR DESCRIPTION
**Pull request by rigin**
Pull Request for Issue # .

### CODE REVIEW

**Comment by rigin** [comment]
In our country, actively provide such addresses. eg: Вадим.Ригин@почта.рф

**Comment by richard67** [comment]
@rigin Why have you closed this? As far as I understood you in discussion of #13742 that this one here is needed to make #13742 work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13741">issues.joomla.org/tracker/joomla-cms/13741</a>.</sub>

**Comment by rigin** [comment]
You yourself asked me to close this branch # 13742. I told you that this file is also needed, but I do not know how to combine revision 2 files in 1 Pull.

This file need to modify , compress and set instead of media/system/js/punycode.js.  It provides client-side validation

**Comment by richard67** [comment]
yes, i did so because i thought that the other thing was just the issue report for this pull request here when i adviced you to close it. but you told me then that it ids another pull request, and so i thought "ok, i was wrong" and assumed you will not close it. Sorry for misunderstanding, was my fault. But you can do following: You can go in github to the branch of this pull request here and then on the website of github edit the javascript file in the same way as you did it in the other, meanwhile closed pull request. Then you have both changes in this one here. I do not have much spare time but if I can I will advice in case of questions. And of course I will test when it is ready and if I have time. Again sorry for misunderstanding and me having confused you.

**Comment by richard67** [comment]
ahh i see i confuse again!!! I just notice this here is the closed one, and the other one is the open one. So you have to invert my previous comment, add the file not to this but to the other, open pull request.

**Comment by rigin** [comment]
To this end, I created a Pull # 13770

**Comment by rigin** [comment]
Testing together

**Pull request closed without merging**
