### PR TITLE
Change the defaults for new installs to disable com_mailto in articles

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Change the defaults for new installs to disable com_mailto in articles.

As discussed with the JSST this is now a public tracker item: cc @SniperSister @mbabker

### Testing Instructions

- Install [this branch](https://github.com/zero-24/joomla-cms/archive/mailto_disabled_bydefault.zip)
- make sure the default for com_mailto settings in com_content Global configuration is off

### Expected result

default is off

### Actual result

default is on

### Documentation Changes Required

none

### Additional notes

When this got merged I'm going to build a PR against 4.0 that set the correct settings to the xml and PHP Code too if needed.

### CODE REVIEW

**Comment by brianteeman** [comment]
> When this got merged I'm going to build a PR against 4.0 that set the correct settings to the xml and PHP Code too if needed.

I have a pr open to remove it completely in j4

**Comment by zero-24** [comment]
> I have a pr open to remove it completely in j4

Would be great but I have been told that I should better rewrite it to JForm than removing it by @wilsonge . Well maybe we can finally remove it with 4.0 but for 3.8 & 3.9. we need to fix it anyway. The defaults and the support for captcha.

**Comment by mbabker** [comment]
No, not removing com_mailto.  Removing the email button.

**Comment by zero-24** [comment]
> No, not removing com_mailto. Removing the email button.

I don't care for now what is done in 4.0 with com_mailto lets get this one into 3.8.8 and we do what ever we decide to do in 4.0 this was just a general note to avoid discussions about xmls and PHP code to change or not as that was decided to be done if ever in 4.0. :)

**Comment by Quy** [comment]
Update:
sample_learn.sql
jos_extensions.csv
jos_menu.csv

**Comment by zero-24** [comment]
Thanks @Quy just pushed that fixes.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 367b4d4bdf1d1930d9ec7b2e5bc3815cc5e05a9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20266">issues.joomla.org/tracker/joomla-cms/20266</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 367b4d4bdf1d1930d9ec7b2e5bc3815cc5e05a9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20266">issues.joomla.org/tracker/joomla-cms/20266</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20266">issues.joomla.org/tracker/joomla-cms/20266</a>.</sub>

**Pull request merged**
