### PR TITLE
"This is the latest new from us" typo Update sample_brochure.sql sqlazure

### PR DESCRIPTION
**Pull request by PhilETaylor**
```
-This is the latest new from us
+This is the latest news from us
```

### CODE REVIEW

**Comment by brianteeman** [comment]
Tested ok

Missing aha @mbabker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12771">issues.joomla.org/tracker/joomla-cms/12771</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 047d186457e8aecff80487003d882253fa92f012<br /><br />code review/spelling review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12771">issues.joomla.org/tracker/joomla-cms/12771</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 047d186457e8aecff80487003d882253fa92f012<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12771">issues.joomla.org/tracker/joomla-cms/12771</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12771">issues.joomla.org/tracker/joomla-cms/12771</a>.</sub>

**Pull request merged**
