### PR TITLE
[4.0] Remove the local dependency in the media select field

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The media select field has a hard dependency to the local adapter to insert media data. Instead of it should just check if the media file is a local one or not. This allows adapters which are working with local files as well to insert relative urls.

### Testing Instructions
- Download and install the free version DPMedia from [here](https://joomla.digital-peak.com/download/dpmedia)
- Create a Pixabay adapter in the back end as described [here](https://joomla.digital-peak.com/documentation/dpmedia/image-services/pixabay-plugin)
- In the article form select an image from the local adapter
- In the article form select an image from the Pixabay adapter

### Actual result BEFORE applying this Pull Request
- Local has a relative url
- Pixabay has the url to pixabay

### Expected result AFTER applying this Pull Request
- Local has a relative url
- Pixabay has the url to pixabay

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo Is it right that actual and expected result are the same? Or is that some kind of typo?

**Comment by laoneo** [comment]
It should be the same.

**Comment by richard67** [comment]
@laoneo Hmm, but then I would expect another test to show the difference described in the description. Is there some 3rd party adapter available which works with local files so it can be tested, too?

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on cb1192425449d8e43e35b3822788b4165a4991dc<br /><br />Also tested with https://restrictedfs.dgrammatiko.dev (alternative local adater)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36667">issues.joomla.org/tracker/joomla-cms/36667</a>.</sub>

**Comment by laoneo** [comment]
I tested it with a local adapter I'm shipping soon with DPMedia and it worked, and now @dgrammatiko tested it with his one. Guess more we can't provide atm.

**Comment by HusiBT** [comment]
I have tested this item :white_check_mark: successfully on cb1192425449d8e43e35b3822788b4165a4991dc<br /><br />Tested successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36667">issues.joomla.org/tracker/joomla-cms/36667</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36667">issues.joomla.org/tracker/joomla-cms/36667</a>.</sub>

**Comment by bembelimen** [comment]
Reset as there were some changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36667">issues.joomla.org/tracker/joomla-cms/36667</a>.</sub>

**Comment by laoneo** [comment]
There were no changes, only merge conflicts. So ready to commit.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
