### PR TITLE
[5.1] Fix for legacy editor-xtd plugins with array of buttons

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43128 .

### Summary of Changes

Fix compatibility with legacy editor-xtd  plugins, which return multiple buttons.

### Testing Instructions
Edit https://github.com/joomla/joomla-cms/blob/ef33d44375080b2e49962927fd3169523c3b610d/plugins/editors-xtd/contact/src/Extension/Contact.php#L46

And replace whole method with:
```php
public function onDisplay($name)
{
  return [
    new CMSObject([
        'action'  => 'insert',
        'icon'    => 'foobar',
        'text'    => 'Beer',
        'options' => ['content' => '🍺 ']
    ]),
    new CMSObject([
        'action'  => 'insert',
        'icon'    => 'foobar',
        'text'    => 'Cat',
        'options' => ['content' => '🐈 ']
    ]),
  ];
}
```

Go to content editing. And check for this button.

### Actual result BEFORE applying this Pull Request
Only Cat button is shown.

### Expected result AFTER applying this Pull Request
Both buttons is shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Tazzios** [comment]
I have tested this item :white_check_mark: successfully on 07ebef5ec01338e9f48868e7d90546668f6e5947<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43129">issues.joomla.org/tracker/joomla-cms/43129</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 07ebef5ec01338e9f48868e7d90546668f6e5947<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43129">issues.joomla.org/tracker/joomla-cms/43129</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43129">issues.joomla.org/tracker/joomla-cms/43129</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by LadySolveig** [comment]
Thank you @Fedik and for testing @Tazzios and @viocassel

**Pull request merged**
