### PR TITLE
Show configured upload limit when uploading files (redo of #11255)

### PR DESCRIPTION
**Pull request by izharaazmi**
This is the redo of PR #11255 against 3.7.x branch. Please see the other PR for details.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on ea5b850dd5f6bb5e3e80710094f9b124e9608922<br /><br />Tested with 3.7 and in the template manager it is not showing the correct values.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12396">issues.joomla.org/tracker/joomla-cms/12396</a>.</sub>

**Comment by brianteeman** [comment]
screen shot 2016-10-12 at 16 48 11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12396">issues.joomla.org/tracker/joomla-cms/12396</a>.</sub>

**Comment by izharaazmi** [comment]
Thanks @brianteeman. Fixed in template manager, please check.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e2230308227ab0114afd73aaedfdbdc8b03e1e2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12396">issues.joomla.org/tracker/joomla-cms/12396</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on e2230308227ab0114afd73aaedfdbdc8b03e1e2f<br /><br />Looks great merging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12396">issues.joomla.org/tracker/joomla-cms/12396</a>.</sub>

**Comment by JoomliC** [comment]
Hello,

Sorry first to see this late, but i just discovered that this apply then to all file type field, in third party too, but it display there the max server limit. (maybe an issue...)

Another suggestion would have been to disable this by default, and to create a xml attribute to turn on this info (or set it to "global media setting" OR custom limit value, if one want a smaller value than the global setting).

@izharaazmi What's your opinion on this ?

Best regards,
Cyril

**Comment by izharaazmi** [comment]
I understand your concern. Please create a separate issue for this
mentioning this thread. Otherwise your comment would not be noticed on a
closed PR.

**Comment by JoomliC** [comment]
@izharaazmi it was just to have your opinion as you did this PR ;-)

I will better check this later (when a bit of time) and open a PR with needed options (as for now, in a 3PD extension using file type input, the message is displayed, but with server max limit, and not media set limit which is an issue, so i will have to look futher on this first).

Regards,
Cyril

**Comment by izharaazmi** [comment]
Sure. my view was just to let the user know the max limit they can upload
as limited by whatever factor its limited by. Basically most of the places
the only limiting factor is the server limit, hence the display text. I
just focused on the being informative part when doing this PR.

We can surely improve that to show custom limit such as `<field type="file"
limit="20MB" showlimit="true"/>` to show 20MB or server limit whichever is
lesser.

**Comment by JoomliC** [comment]
Yes limit and showlimit are useful, but it should be disable by default.

Reason : file size could be checked php side, which could be a different value than server limit value.

If someone use this in its code : 
`		<field
			name="file"
			type="file"
			label="File Upload"
			description="File Upload. Maximum upload limit : 1MB"
		/>
		<field
			name="MAX_FILE_SIZE"
			type="hidden"
			default="1048"
		/>
`

Then, doing some control php or ajax side, it will display the server value which is not the developer expected ;-)

If you agree, i could check in a few days to do this PR (options + disable by default for "minor" B/C reason).

Cyril

**Comment by spomares** [comment]
Intentando resolver un problema de uan web obsoleta y me ha servidor de ayuda, gracias

**Pull request merged**
