### PR TITLE
[4.0] Remove the min attribute from the com csp csp values xml

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue partial #28171 

### Summary of Changes

Remove the min attribute from the com csp csp values xml

### Testing Instructions

Go to System > Manage > Content Security Policy > Options
set the CSP Mode to custom
add directive below
add 2nd directive
try delete all directives...

### Expected result

all directives are deleted

### Actual result

Actual result: I can delete all, until one directive (first) still remain. I can't delete it.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on d53c09e2b5c9b41ee6cba5786f30076f0f5efb00<br /><br />1. I opened System > Manage > Content Security Policy > Options 
2. I set set the CSP Mode to custom
3. I added two smple directive 

Before applying this patch I could not delete the last directive. After it was possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28173">issues.joomla.org/tracker/joomla-cms/28173</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d53c09e2b5c9b41ee6cba5786f30076f0f5efb00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28173">issues.joomla.org/tracker/joomla-cms/28173</a>.</sub>

**Comment by richard67** [comment]
@zero-24 Why do your instructions say "Pull Request for Issue partial #28171 "? To me it seems it solves the issue completely.

**Comment by zero-24** [comment]
> To me it seems it solves the issue completely.

Well as said there I personally would expect that the last delete would reset the values to empty, this here just masks the issue.

**Comment by richard67** [comment]
> > To me it seems it solves the issue completely.
> 
> Well as said there I personally would expect that the last delete would reset the values to empty, this here just masks the issue.

@zero-24 Thanks for explanation. Do you recommend to re-open the original issue #28171 ?

**Comment by zero-24** [comment]
I does not need to be re-opend when it is just me having that expectation :)

**Comment by richard67** [comment]
>>>>@richard67: To me it seems it solves the issue completely.

>>>@zero-24: Well as said there I personally would expect that the last delete would reset the values to empty, this here just masks the issue.

>>@richard67: @zero-24 Thanks for explanation. Do you recommend to re-open the original issue #28171 ?

>@zero-24: I does not need to be re-opend when it is just me having that expectation :)

What does @blueforce as the author of the issue think?

**Comment by blueforce** [comment]
Yes works as expected... It's more consistent and the same behavior (UX) as the other filter options

**Comment by blueforce** [comment]
I have tested this item :white_check_mark: successfully on d53c09e2b5c9b41ee6cba5786f30076f0f5efb00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28173">issues.joomla.org/tracker/joomla-cms/28173</a>.</sub>

**Pull request merged**
