### PR TITLE
[4.0] Deleting obsolete template.min.js

### PR DESCRIPTION
**Pull request by Hackwar**
Seems like this file is a leftover of earlier cleanup.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
You're breaking B/C here.
That code ensures that group buttons will work as they meant to...

In order to remove this part you need first this: https://github.com/joomla/joomla-cms/pull/20549

**Comment by HLeithner** [comment]
Seams that got fixed in https://github.com/joomla/joomla-cms/commit/6a3edd081ceb2bc1b2de36cb3f4ffeeae2b6a67e ? because in this commit the original template.js as been deleted.

**Comment by dgrammatiko** [comment]
@HLeithner No, that PR **assumes** that bootstrap.js is always loaded by the template. This **won't** be the case for Atum...

**Comment by wilsonge** [comment]
@dgrammatiko why is there only a minified file committed then? There is no way of trying to get the original back out from this i guess

**Comment by Hackwar** [comment]
There is no original source of that JS file anymore and the code has not been included in the template for pretty exactly a year now: #19326

**Comment by Hackwar** [comment]
@wilsonge we can of course restore the old file from a year ago, but considering that it has not been included for a year and nobody really noticed it, I would claim that it is not needed.

**Comment by HLeithner** [comment]
> @HLeithner No, that PR **assumes** that bootstrap.js is always loaded by the template. This **won't** be the case for Atum...

You reopend https://github.com/joomla/joomla-cms/pull/20549 do you try to fix the Situation suiteable for screenreaders?

**Comment by dgrammatiko** [comment]
@Hackwar @wilsonge go ahead and remove it. I already reopened #20549 and will patch the a11y concerns there.

FWIW my point was that @Bakual 's PR removing the js file was based on the assumption that Bootstrap.js will **always** be loaded, which of course is wrong as both Atum and Cassiopeia will be free from jQuery.js and Bootstrap.js

**Comment by Bakual** [comment]
This PR indeed is fine since my PR back then removed all reference to load that file. I don't know why I missed the minified one. The code in that file was broken anyway.

> FWIW my point was that @Bakual 's PR removing the js file was based on the assumption that Bootstrap.js will always be loaded, which of course is wrong as both Atum and Cassiopeia will be free from jQuery.js and Bootstrap.js

That's true, and explicitely mentioned in my PR back then:
> Since Bootstrap is loaded anyway and it offers the same functionality, we can use just that one for now (until it gets eventually converted to a CE).

So yes, it's one roadblock to get Bootstrap removed from the template.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
