### PR TITLE
Add comment to string

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #15531

### CODE REVIEW

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on 5671dd2965c3d991c308b29d80abc9ad3be342e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15571">issues.joomla.org/tracker/joomla-cms/15571</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5671dd2965c3d991c308b29d80abc9ad3be342e0<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15571">issues.joomla.org/tracker/joomla-cms/15571</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
