### PR TITLE
[4.3] Tags: Don't put NULL into trim()

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #41466.

### Summary of Changes
When on PHP 8.1 and editing an article, adding an unknown tag triggers an AJAX call which throws a notice.

### Testing Instructions
1. You have to be on PHP 8.1 or higher
2. Edit an article and click into the tags field
3. Open the browser console to see the ajax request
4. Type a random tag-name into the tag field
5. See the request in the console and check the request answer

### Actual result BEFORE applying this Pull Request
A notice is thrown and the JS actually throws an error, too.

### Expected result AFTER applying this Pull Request
No notice, everything is hunky dorry. 😉 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 149d1538921754a89549847e9b20288104ab3492<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41509">issues.joomla.org/tracker/joomla-cms/41509</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 149d1538921754a89549847e9b20288104ab3492<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41509">issues.joomla.org/tracker/joomla-cms/41509</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41509">issues.joomla.org/tracker/joomla-cms/41509</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
