### PR TITLE
Update PostCSS to 8.x

### PR DESCRIPTION
**Pull request by ghazal**
Please see https://github.com/joomla/joomla-cms/issues/36038

### CODE REVIEW

**Comment by richard67** [comment]
@ghazal You need to update the package-lock.json, too. For this you run the command "composer update postcss" on a command line in the Joomla root folder after having applied the changes of this PR on the package.json file.

**Comment by brianteeman** [comment]
For reference https://evilmartians.com/chronicles/postcss-8-plugin-migration any postcss plugin in use needs to be checked to ensure it works with v8

**Comment by dgrammatiko** [comment]
Please close this PR as it's wrong and test https://github.com/joomla/joomla-cms/pull/32574 that does the upgrade correctly

**Comment by richard67** [comment]
> Please close this PR as it's wrong and test #32574 that does the upgrade correctly

@dgrammatiko #32574 is for 4.1-dev. Should we wait until 4.1 with that update, or should we do that for 4.0-dev so it can be fixed with the upcoming next release?

**Comment by dgrammatiko** [comment]
> Should we wait until 4.1 with that update, or should we do that for 4.0-dev so it can be fixed with the upcoming next release?

PostCSS 7.x is still working (tests don't throw) AFAIK

**Comment by ghazal** [comment]
npm v 8.1.3
node v 17.0.1
Composer v 2.1.12

I began to get errors with PostCSS after I updated to the above versions, ie this PR.
But I had not noticed @dgrammatiko PR.
Well, as tests are failing, I close this.

**Comment by dgrammatiko** [comment]
@richard67 fwiw https://github.com/joomla/joomla-cms/pull/36050 also upgrades PostCSS to 8.x and it's on 4.0.x

**Comment by richard67** [comment]
@dgrammatiko Thanks!

**Pull request closed without merging**
