### PR TITLE
[3.9] Make sure we don't send a referrer on the remind and reset views

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Make sure we don't send a referrer on the remind and reset views

### Testing Instructions

1) Apply this patch
2) go to the remind page and request and remind token
3) click on the link that is send to you
4) check the http header of that page with the F12 developer tools.

### Expected result

On this specific page we set the Referrer-Policy and set it to no-referrer so no referrer is send.

### Actual result

We do not send that policy.

### Documentation Changes Required

None. 

### Additional Information

This is a pull request for an report to the security team where the @joomla/security team decided to move the patch to the public tracker.

Thanks to Pim Feltkamp & Vipul Sahu for reporting this to us.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
This is ok. But I think this belongs in the controller not the view?

**Comment by zero-24** [comment]
Where do you want me to add the header call?

**Comment by mbabker** [comment]
> Where do you want me to add the header call?

Headers should be set in whatever controller is triggering the view, in this case that'd be `/components/com_users/controller.php`

**Comment by zero-24** [comment]
> Headers should be set in whatever controller is triggering the view, in this case that'd be /components/com_users/controller.php

Something like this? https://github.com/joomla/joomla-cms/pull/21722/commits/8dcc51c9575bb07485052bfb87d99dac1a0e7793

**Review by mbabker — APPROVED** [review]

**Comment by PhilETaylor** [comment]
> @mbabker approved this pull request.

The highest form of approval and something to which will all aspire to seeing ;-)

**Comment by alikon** [comment]
is something we should also need to consider in the privacy-framework ?

**Comment by zero-24** [comment]
> is something we should also need to consider in the privacy-framework ?

You can apply that on any page where you send a mail with a token in the URL. I'm not 100% sure but if you have a similar page please do so.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8dcc51c9575bb07485052bfb87d99dac1a0e7793<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21722">issues.joomla.org/tracker/joomla-cms/21722</a>.</sub>

**Comment by fabpacheco** [comment]
I have tested this item :white_check_mark: successfully on 8dcc51c9575bb07485052bfb87d99dac1a0e7793<br /><br />**Before patch:**
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 3778
Content-Type: text/html; charset=utf-8
Date: Fri, 31 Aug 2018 13:00:04 GMT
Expires: Wed, 17 Aug 2005 00:00:00 GMT
Keep-Alive: timeout=5, max=100
Last-Modified: Fri, 31 Aug 2018 13:00:05 GMT
Pragma: no-cache
Server: Apache/2.4.29 (Win32) OpenSSL/1.0.2n PHP/7.0.28
Vary: Accept-Encoding
X-Powered-By: PHP/7.0.28

**After patch:**
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 3775
Content-Type: text/html; charset=utf-8
Date: Fri, 31 Aug 2018 13:20:18 GMT
Expires: Wed, 17 Aug 2005 00:00:00 GMT
Keep-Alive: timeout=5, max=100
Last-Modified: Fri, 31 Aug 2018 13:20:19 GMT
Pragma: no-cache
**Referrer-Policy: no-referrer**
Server: Apache/2.4.29 (Win32) OpenSSL/1.0.2n PHP/7.0.28
Vary: Accept-Encoding
X-Powered-By: PHP/7.0.28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21722">issues.joomla.org/tracker/joomla-cms/21722</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
