### PR TITLE
[bug] Missing variables

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

The error_login page needs also the `$loginLogo` and `loginLogoAlt` (check line 120), my bad!

### Testing Instructions

Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Line 121, change to:
`<?php echo HTMLHelper::_('image', $loginLogo, $loginLogoAlt, ['loading' => 'eager', 'decoding' => 'async'], false, 0); ?>`

Otherwise, it will output without the `alt=`:
``

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 11dc9e2f2377dcafbf79f7a7edb181ca965cd1c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39676">issues.joomla.org/tracker/joomla-cms/39676</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 11dc9e2f2377dcafbf79f7a7edb181ca965cd1c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39676">issues.joomla.org/tracker/joomla-cms/39676</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39676">issues.joomla.org/tracker/joomla-cms/39676</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
