### PR TITLE
[4.0] Fix js error in mod_finder

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #32325 .

### Summary of Changes

Fix js error in mod_finder

### Testing Instructions
Please follow #32325

### Actual result BEFORE applying this Pull Request
error

### Expected result AFTER applying this Pull Request
no error

### Documentation Changes Required
none

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bcd3e2389be4c22bf71c446e398821aa0d8f1e00<br /><br />:)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32333">issues.joomla.org/tracker/joomla-cms/32333</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bcd3e2389be4c22bf71c446e398821aa0d8f1e00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32333">issues.joomla.org/tracker/joomla-cms/32333</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32333">issues.joomla.org/tracker/joomla-cms/32333</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
