### PR TITLE
[4.2] Update deleted files and folders for 4.2.0-beta3

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Update the lists of files and folders to be deleted on update by script.php to the latest changes in the 4.2-dev branch in preparation of the upcoming 4.2.0 Beta 3.

Following files and folder from following PR's are included (note that this includes the old location of moved files):
- From PR #37910 file "plugins/system/webauthn/webauthn.php" and folders "plugins/system/webauthn/src/Helper" and "plugins/system/webauthn/src/Exception" and the files in these folders.
- From PR #38072 file "plugins/task/checkfiles/checkfiles.ph".
- From PR #38098 file "plugins/task/demotasks/demotasks.php".

### Testing Instructions

**_Please wait with testing until the PR is ready for review._**

Code review.

Or if you want to make a real test, update a 4.2.0-beta2 to the last 4.2 nightly build to get the actual result, and update a 4.2.0-beta2 to the update package built by Drone for this PR to get the expected result.

### Actual result BEFORE applying this Pull Request

Files and folders mentioned in the description above are still present after updating from 4.2.0-beta2.

### Expected result AFTER applying this Pull Request

All files and folders mentioned in the description above have been deleted after updating from 4.2.0-beta2.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by HLeithner** [comment]
A new pull request has been created automatically to convert this PR to the PSR-12 coding standard. The pr can be found at https://github.com/richard67/joomla-cms/pull/27

**Comment by HLeithner** [comment]
A new pull request has been created automatically to convert this PR to the PSR-12 coding standard. The pr can be found at https://github.com/richard67/joomla-cms/pull/28

**Comment by HLeithner** [comment]
A new pull request has been created automatically to convert this PR to the PSR-12 coding standard. The pr can be found at https://github.com/richard67/joomla-cms/pull/29

**Comment by roland-d** [comment]
Thank you @richard67

**Pull request merged**
