### PR TITLE
[4.0] Redirect plugin

### PR DESCRIPTION
**Pull request by brianteeman**
Correct the display of the switcher

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a1e5dc42641337526f5b8ac9b2eb9c2b1ee073e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25846">issues.joomla.org/tracker/joomla-cms/25846</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on a1e5dc42641337526f5b8ac9b2eb9c2b1ee073e7<br /><br />Default value of "Include Domain Name in Expired URL" set to No
Patch applied
Default value of "Include Domain Name in Expired URL" set to Yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25846">issues.joomla.org/tracker/joomla-cms/25846</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
