### PR TITLE
[4] replace deprecated class call

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 1d6660cd8a4e61ceeafd81872b53588ccc53f5fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35131">issues.joomla.org/tracker/joomla-cms/35131</a>.</sub>

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 1d6660cd8a4e61ceeafd81872b53588ccc53f5fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35131">issues.joomla.org/tracker/joomla-cms/35131</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35131">issues.joomla.org/tracker/joomla-cms/35131</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
