### PR TITLE
[4.0] Extending PHP pipeline

### PR DESCRIPTION
**Pull request by Hackwar**
This updates the PHP versions used for the unittests

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by SniperSister** [comment]
Nice one, thanks @Hackwar! I assume that we need a Cronjob on the drone machine fetching the new daily images once a day?

**Comment by Hackwar** [comment]
As far as I can see we would just have to clear the docker image cache for the new image to be built from the sources. I would even say that once a week would be enough. We could add an attribute to those steps to never cache these images, but that seems excessive and would extend build times...

**Comment by SniperSister** [comment]
> As far as I can see we would just have to clear the docker image cache for the new image to be built from the sources. 

Exactly, so we need the cron once it's merged :) ping me, i can take care of that

**Comment by wilsonge** [comment]
This looks fine on review to me

**Comment by Hackwar** [comment]
Just to make sure that you are not missing something: Yes, this looks fine right now, but it has a lot less PHP modules/extensions than our current image. So when we extend the unit tests to test other stuff, we will have to revisit this topic. But for now this is the quickest solution to move forward here. For integration tests we will have to also extend this, I guess. But for now, this gets us the unit tests onto PHP 7.2/.3/.4/8.0 quickly and removes the need for Travis in 4.0-dev.

**Review by SniperSister — APPROVED** [review]

**Comment by SniperSister** [comment]
@Hackwar suggestion: adding a php -v before running the tests should give us some debug info in case we run into issues - what do you think?

**Comment by Hackwar** [comment]
done

**Comment by Hackwar** [comment]
done

**Comment by Hackwar** [comment]
Somehow it doesn't save my comments, but I just wanted to let you know that I did the change.

**Comment by SniperSister** [comment]
Merged! Thanks :)

**Pull request merged**
