### PR TITLE
com_languages - Moved Filters from sidebar to Search Tools

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves Filters from left sidebar to Search Tools.
# Testing instructions
## Before this PR

Extensions > Language(s) > Content Languages
1. In the sidebar on the left there are 2 Filters: Select Status & Select Access
2. On the top right there are two duplicate ordering fields: "Sort Table By" & "Select the ordering" (for the direction of the ordering).

languages_contentlanguages_before
## After this PR

Extensions > Language(s) > Content Languages
1. the Filters from sidebar should be moved to the middle under "Search Tools" option. All filters can be reset with the "Clear" button.
2. the "Sort Table By" & "Select the ordering" have been removed. The ordering field + ordering direction can be set by clicking on a column header (fieldname).

languages_contentlanguages_after

### CODE REVIEW

**Comment by infograf768** [comment]
Please format the new file `filter_languages.xml` with tabs as in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/filter_articles.xml

**Comment by infograf768** [comment]
Otherwise looks fine here.

**Comment by pe7er** [comment]
I've reformatted the spaces in filter_languages.xml to tabs.
Thanks @infograf768

**Comment by infograf768** [comment]
:+1:

**Comment by zero-24** [comment]
@pe7er can you resolve the merge conflicts?

**Comment by pe7er** [comment]
Thanks @zero-24 
I fixed the merge conflict...

**Comment by zero-24** [comment]
RTC :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7704">issues.joomla.org/joomla-cms/7704</a>.</sub>

**Comment by coolman01** [comment]
I have tested this item :white_check_mark: successfully on a90380dc8d7a47a47734f537ad0f241a61d6345c<br /><br />Nice and clean<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7704">issues.joomla.org/joomla-cms/7704</a>.</sub>

**Comment by zero-24** [comment]
pending ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7704">issues.joomla.org/joomla-cms/7704</a>.</sub>

**Comment by pe7er** [comment]
I've added the Ordering + Direction dropdown options to Search Tools area.

language-content-ordering

**Note:** There are still 2 issues with this functionality:
1. The dropdown option **Direction** is **not yet working**. 
2. The **dropdown ordering** options **do not inherit** the ordering **status of the click-on-column-order**. If you click on the "ID" column header, the "Sort Table By:" does not change to "ID".

I hope that someone knows a solution for this. Thanks!

**Comment by pe7er** [comment]
I've **solved the issues** mentioned in https://github.com/joomla/joomla-cms/pull/7704#issuecomment-150841825

Now the **ordering & direction dropdown** boxes & **column headers** are **all working and synchronized**:
clicking on a column header will select the ordering + direction of the dropdown boxes (ordering and direction), and vice versa.

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on 1334244bce47a69cbe94dfbca547bd7ae730d5d4<br /><br />Works as described. -> RTC

Thank you @pe7er!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7704">issues.joomla.org/joomla-cms/7704</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 1334244bce47a69cbe94dfbca547bd7ae730d5d4<br /><br />One question: for overrides the filter is still on the sidebar, is this intended?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7704">issues.joomla.org/joomla-cms/7704</a>.</sub>

**Pull request closed without merging**
