### PR TITLE
[4.2] javascript cs warning

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Convert `unnamed function` to `arrow function`

### Testing Instructions

follow #38154

### Actual result BEFORE applying this Pull Request

warning at `npm run lint:js`
image

### Expected result AFTER applying this Pull Request

no warning at `npm run lint:js`
image

### CODE REVIEW

**Comment by brianteeman** [comment]
obvioously there is an issue with drone as this should have been picked up

**Comment by heelc29** [comment]
> obvioously there is an issue with drone as this should have been picked up

That it's just a warning, I guess it's ok for drone ...
image

**Review by richard67 — APPROVED** [review]
Fits to the syntax we have elsewhere.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dd0e85e4b0fc070978be6a554391bd6e78baba19<br /><br />Warning from eslint is fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38613">issues.joomla.org/tracker/joomla-cms/38613</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dd0e85e4b0fc070978be6a554391bd6e78baba19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38613">issues.joomla.org/tracker/joomla-cms/38613</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38613">issues.joomla.org/tracker/joomla-cms/38613</a>.</sub>

**Comment by dgrammatiko** [comment]
Although this PR cleans up the warning there are more problems in this file, eg the `addEventListener('DOMContentLoaded', ...)` is an ANTIPATTERN and should be removed (the file is either loaded with attribute defer or type=module which render the waiting for the DOM to be ready useless). I had fixed it correctly with #38225: https://github.com/joomla/joomla-cms/pull/38225/files#diff-4afb4f910136391957e62b8afcb5f0d6b240ee226cd69b4960777bc15ddfe668

The code should be:

```js

/**
 * @copyright  (C) 2022 Open Source Matters, Inc. <https://www.joomla.org>
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */
[].slice.call(document.querySelectorAll('.article-status')).forEach((element) => {
  element.addEventListener('click', (event) => {
    event.stopPropagation();
  });
});
```

**Comment by obuisard** [comment]
I agree @dgrammatiko, this should be cleaned up. Do you mind writing a PR for this issue and if you can't work on it I will try and rally the troops so you get help :-)

**Comment by dgrammatiko** [comment]
@obuisard you could use https://github.com/joomla/joomla-cms/pull/35725 as a guide.
In short the scripts need to:
- be converted to `type=module` + add the -es5 in the dependencies
- remove the iife, if exists (type= module  scripts are scoped by default)
- remove strict mode (type= module is strict by default)
- remove the `addEventListener('DOMContentLoaded', ...)` as it's pure overhead

**Pull request merged**
