### PR TITLE
[4.0] Fix core loader on RTL

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #26356

### Summary of Changes

Fix the core-loader web component on RTL

### Testing Instructions

- Modify `installation/language/en-GB/en-GB.xml` to set it to RTL: `<rtl>1</rtl>`
- Install Joomla.

Demo Codepen: https://codepen.io/charlie-lodder/pen/rNBQBev

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bd1d8ad2b57af5b585ac78e47042ad74641c459a<br /><br />Works fine. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26358">issues.joomla.org/tracker/joomla-cms/26358</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge 
Good to go.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bd1d8ad2b57af5b585ac78e47042ad74641c459a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26358">issues.joomla.org/tracker/joomla-cms/26358</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26358">issues.joomla.org/tracker/joomla-cms/26358</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
