### PR TITLE
Restrict search result messages by putting it in parentheses

### PR DESCRIPTION
**Pull request by ma-at**
Pull Request for Issue # .

The or in the were clause will give a result for all users.

### Summary of Changes

By putting it in parenthesis it will restrict to the user only.

### Testing Instructions

If you search messages with a keyword I suppose you only search in your own messages. By the or in the were clause you also get results from other users.

### Expected result

The search should give you only results from your own messages.

### Actual result

results from all messages.

### CODE REVIEW

**Comment by ma-at** [comment]
This is my first pull request so not sure if I did it well

**Comment by alikon** [comment]
Hi @ma-at 
to be a little bit more helpfull :smile: 
 just fulfill the missing template points like :
- Testing Instructions
- Expected result
- Actual result

it's a little bit hard to guess what you are trying to achieve.... or me i'm too naive

**Comment by ma-at** [comment]
Hi Nicola,

Not sure if it is clear now but I updated the template.
Just tell me if it is still confusing.

Op 29-08-19 om 12:13 schreef Nicola Galgano:

**Comment by alikon** [comment]
thanks for the explanation,much  more clear, now let's wait from some other's  feedback , i'm not one of heavy user of that feature/use case

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on bf8e7ce1a808e021362c2e1039435f699a8eeb86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26065">issues.joomla.org/tracker/joomla-cms/26065</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bf8e7ce1a808e021362c2e1039435f699a8eeb86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26065">issues.joomla.org/tracker/joomla-cms/26065</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26065">issues.joomla.org/tracker/joomla-cms/26065</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by HLeithner** [comment]
Thanks for catching this bug.

**Pull request merged**
