### PR TITLE
[4.0] Global config media query fix

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #18595 .

### Summary of Changes
Custom media query breakpoint for the global config

### Testing Instructions
Apply PR and navigate to global config. Resize browser width and ensure fields never overlap. See original issue screenshot.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 6778f80eaca7eb5e5bb6b4caa7d0e68d569598f7
### Using PR got:
bildschirmfoto 2017-11-18 um 13 12 20
### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18658">issues.joomla.org/tracker/joomla-cms/18658</a>.</sub>

**Comment by ciar4n** [comment]
@franz-wohlkoenig Could you try clearing cache after applying PR

**Comment by ghost** [comment]
done, but resizing from 50% of an 27"-iMac smaller got overlapping (starting around 1258px).
bildschirmfoto 2017-11-18 um 15 04 01

**Comment by ciar4n** [comment]
You are correct. I hadn't considered the sidebar been opened. I have made some changes so should be ok now.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ff48602ba1f18f24d3f7875f225c49e0c08336a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18658">issues.joomla.org/tracker/joomla-cms/18658</a>.</sub>

**Pull request merged**
