### PR TITLE
com_messages - Component naming 'Messaging'

### PR DESCRIPTION
**Pull request by pe7er**
The **Title** of this **Messaging component** is **different** in **Menu Names** and **Component Views**.

This PR **corrects the Menu Names and Component titles** so that the naming of the component is consequently the same.
### Testing Instructions

You'll need to create a couple of test users that have access to the back-end (e.g. Administrator or Super Administrator). Otherwise you cannot send Private Message and not see all screens.
#### Before the PR:

Backend: System > Global Configuration > under COMPONENT (left menu)
Configure Menu Title: **Messaging**

configure-components-plural-single-before

Backend: System > Global Configuration > under COMPONENT (left menu) click on Messaging
Configure Component Title: **Messages: Options**

configure-components-plural-single-messaging-before

Backend: Components
Menu Title: Components > **Messaging**
Menu Title: Components > Messaging > **New Private Message**

configure-components-plural-single-messaging-menu

Backend: Components > Messaging > New
Write Message Title: **Private Messages: Write**

configure-components-plural-single-messaging-component-write-before

Backend: Components > Messaging
View Title: **Private Messages**

configure-components-plural-single-messaging-component-read-before

Backend: Components > Messaging > click on a new message
View Message Title: **Private Messages: Read**

configure-components-plural-single-messaging-component-read-before2

### CODE REVIEW

**Comment by zero-24** [comment]
@pe7er did you commit everything?

>Private Messages: Read

This is not implemented or do i miss something? It is still view ;)

**Comment by pe7er** [comment]
#### After the PR:
Backend: System > Global Configuration > under COMPONENT (left menu)
Configure Menu Title: **Messaging** [NOT changed]

Backend: System > Global Configuration > under COMPONENT (left menu) click on Messaging
Configure Component Title: **Messaging: Options** (WAS Messages: Options)

configure-components-plural-single-messaging-after

Backend: Components
Menu Title: Components > **Messaging**  [NOT changed]
Menu Title: Components > Messaging > **New Private Message**  [NOT changed]

Backend: Components > Messaging > New
Write Message Title: **Messaging: Write Private Message** (was Private Messages: Write)

configure-components-plural-single-messaging-component-write-after

Backend: Components > Messaging
View Title: **Messaging: Private Messages** (WAS Private Messages)

configure-components-plural-single-messaging-component-read-after

Backend: Components > Messaging > click on a new message
View Message Title: **Messaging: Read Private Message** (WAS Private Messages: Read)

configure-components-plural-single-messaging-component-read-after3

**Comment by pe7er** [comment]
@zero-24 Yeah, sorry. 

The testing instruction was a bit of a hassle so I decided to split it in two (before & after) and only then I noticed a typo in one of the strings which I've just corrected.
Hopefully everything is ok now...

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on fc3041e3e8baba3c5fc7d67f4fe848665a0a89a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12097">issues.joomla.org/joomla-cms/12097</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on fc3041e3e8baba3c5fc7d67f4fe848665a0a89a9<br /><br />Thanks. :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12097">issues.joomla.org/joomla-cms/12097</a>.</sub>

**Comment by brianteeman** [comment]
I am going to set this and the related PR to needs review so they are not merged until we make a decision on them all as I am not convinced it is correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12097">issues.joomla.org/joomla-cms/12097</a>.</sub>

**Comment by pe7er** [comment]
IMHO the titles of the com_messages Component and its options should be the same.

Some references are called "**Messaging**": 
- Components > Messag**ing** menu
- Global Configuration: the reference in the left side: Messag**ing**
- Extension > Manage > Component name: Messag**ing**

Some are called "**Messages**"
- Global Configuration > Messaging (on left side) > Messag**es**: Options
- Components > Messaging > Component title: Private Messag**es**
- Components > Messaging > [New] > Title: Private Messag**es**: Write
- Components > Messaging > [Read a message] > Title: Private Messag**es**: Read

I would like to have all references to and in the com_messages component the same.
**Messages or Messaging**, I don't mind which one, but not both as that might be confusing...

**Pull request closed without merging**
