### PR TITLE
correct field category description.

### PR DESCRIPTION
**Pull request by brianteeman**
you can not create a category on the fly when creating a field

screenshotr15-46-36

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6350856a08dd887bc76db5e96f78a28b12af34fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14492">issues.joomla.org/tracker/joomla-cms/14492</a>.</sub>

**Comment by brianteeman** [comment]
This PR of mine is not correct :(

The string is the same one that is used in places where categories can be created on the fly. I saw the KEY of  JFIELD and thought that this was just for the fields. It will need a new string instead to be used here. I will update this PR for that tomorrow

**Comment by brianteeman** [comment]
OK fixed it so that com_fields uses a unique string for the category with the correct description

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 986fa19ca3b6b2b7787fa62ee566e732f42ad49f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14492">issues.joomla.org/tracker/joomla-cms/14492</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 986fa19ca3b6b2b7787fa62ee566e732f42ad49f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14492">issues.joomla.org/tracker/joomla-cms/14492</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14492">issues.joomla.org/tracker/joomla-cms/14492</a>.</sub>

**Pull request merged**
