### PR TITLE
Minor change in selector titles

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

As discussed in https://github.com/joomla/joomla-cms/pull/9227 this PR changes title in com_cache cache view, com_module, modules view and com_languagues installed view.

image

image

image
#### Testing Instructions
1. Use latest staging
2. Install this patch
3. Check if the page title changes to "(Site)" or "(Administrator)" according to the selected client in the views described above.
#### Observations

I removed the recently added language variable because i think they are not needed as we have JADMINISTRATOR and JSITE.
If not please say so.

@brianteeman, @infograf768 please test.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 45c6d2b81d9ef59a3ec49348177b0454c93df7fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9234">issues.joomla.org/joomla-cms/9234</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 45c6d2b81d9ef59a3ec49348177b0454c93df7fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9234">issues.joomla.org/joomla-cms/9234</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9234">issues.joomla.org/joomla-cms/9234</a>.</sub>

**Comment by infograf768** [comment]
REGRESSION! Not B/C
The original strings must not be modified as the language packs for 3.5.0 may be used on pre-350 sites.
example:
```
-COM_LANGUAGES_VIEW_INSTALLED_TITLE="Languages: Installed"
+COM_LANGUAGES_VIEW_INSTALLED_TITLE="Languages: Installed (%s)"
```
On a pre-350 site the toolbar title will show:
<b>Languages: Installed ()</b>

Same for cache.

**Comment by brianteeman** [comment]
I see no reason at all for this to be an issue - we do not support old
versions of joomla - if nothing else because they are vulnerable to being
hacked. If someone has an old version of joomla and installs a new language
file that should not be our problem - we want people to upgrade.

This is nothing to do with backwards compatibility

On 28 February 2016 at 07:09, infograf768 <notifications@github.com> wrote:

> REGRESSION! Not B/C
> The original strings must not be modified as the language packs for 3.5.0
> may be used on pre-350 sites.
> example:
>
> -COM_LANGUAGES_VIEW_INSTALLED_TITLE="Languages: Installed"
> +COM_LANGUAGES_VIEW_INSTALLED_TITLE="Languages: Installed (%s)"
>
> On a pre-350 site the toolbar title will show:
> *Languages: Installed ()*
>
> Same for cache.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9234#issuecomment-189805310>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
It is not B/C. The policy is to not modify older strings that can be used by older versions (3.4.8 is not so old that everybody will move to 3.5.0...).
It would be OK if the modification of the string value was typo/better english or better explanation of a tip, but in this case we introduce a new variable with parenthesis.

**Comment by infograf768** [comment]
@bakual
Please explain our policy again.

**Comment by infograf768** [comment]
Here is a PR correcting this.
https://github.com/joomla/joomla-cms/pull/9239

**Pull request merged**
