### PR TITLE
Add alt and aria-hidden="true" for logo

### PR DESCRIPTION
**Pull request by denysdesign**
### Summary of Changes

Fix image (logo) for screen reader.

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry but this is not correct. 
Adding aria-hidden=true removes the image from the accessibility tree so it would not matter what the alt description was as a screen reader would never see it.

A decorative image should not have an alt description - it is absolutely correct for it to have the current alt="" in this use case

There is however a bug in that the template style has an option for an alt description to be entered but it is never used. Personally I would be removing that option.

**Comment by denysdesign** [comment]
Why read the logo when logged in?

**Comment by brianteeman** [comment]
Sorry I do not understand that comment

**Comment by Quy** [comment]
Please test PR #28839

**Pull request closed without merging**
