### PR TITLE
Use published date in the category feed view

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #20885 .

### Summary of Changes
Use the published date for the atom/rss feed if it is set

### Testing Instructions
Access feed and check published date is used instead of creation date (when set) and that it falls back to creation date when the published date isn't set

### Documentation Changes Required
n/a

### CODE REVIEW

**Comment by AndNovAtor** [comment]
continuous-integration/drone/pr "failed", PHP_CODESNIFFER says `Usage of ELSE IF is discouraged; use ELSEIF instead` (line 107, `else if ($createdField)`)

**Comment by wilsonge** [comment]
Fixed :)

**Review by mbabker — APPROVED** [review]

**Comment by ghost** [comment]
@AndNovAtor please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bf07872470a5ebe3abdcc63e4edee2be78131a7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21684">issues.joomla.org/tracker/joomla-cms/21684</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on bf07872470a5ebe3abdcc63e4edee2be78131a7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21684">issues.joomla.org/tracker/joomla-cms/21684</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
@wilsonge that would change every rss feed, I don't think that is a good idea to do this in a bugfix release.

**Comment by AndNovAtor** [comment]
@HLeithner , Joomla 3.9.3 was "bugfix" release, but it changes some small components logic (one file using was removed), and so many of compoents became "broken" (with 500 error). However this PM is realy BUGFIX and DOESN'T broke anything. So I think is a good idea - fixing the "bug" that is several YEARS old

**Comment by HLeithner** [comment]
@AndNovAtor which file got removed in 3.9.3 I can't find it and do you have a issue number for me?

This PR has another problem, you can't decide if you like the to show the publish date or the create date for the modification date, like on the normal frontend.

Anyway in my opinion this is a feature and 3.9 has a feature freeze. 

@wilsonge please rebase to j4

**Comment by AndNovAtor** [comment]
@HLeithner , >>you can't decide if you like the to show the publish date or the create date for the modification date, like on the normal frontend
CMN! Joomla itself DOESN'T have this feauture and chooses BAD variant for use - a lot of people ask about exactly publish update. Reread the issue that iniztialized this PM.
SO, I need to reopen the issue.... So many years, and here is still a using create date for publish date.

**Comment by AndNovAtor** [comment]
@HLeithner, >>Anyway in my opinion this is a feature and 3.9 has a feature freeze.
I think that it's a bug (read my last commen in my issue) =)
So I sad, that it's closed for Joomla 3, because Joomla 4 will not be used by MANY people even after release - because minimum php and mysql requerements, for examle.
But I agree that this PM is dead....

**Comment by mbabker** [comment]
If this is going to get closed as a "new feature" then you might as well just do an entire code freeze on the 3.9 as everything can be considered either a new feature or a B/C break (yes, bug fixes are B/C breaks because they change a behavior).

**Comment by AndNovAtor** [comment]
@mbabker , @franz-wohlkoenig , btw, maybe we should create a new pull request for 3.9 branch (it was Joomla 3.8.[11] when this PM was created)? I can....

**Comment by wilsonge** [comment]
Can someone pick up porting this to J4 in this case. I'm busy trying to get J4 things in order before I go on holiday tomorrow

**Comment by Quy** [comment]
I consider it as a bug as the published date in the article does not match with the published date in the feed.

```
Details
    Written by Joomla	
    Category: Park Blog	
    Published: 15 May 2019 
    Hits: 0 
```

```
		<item>
			<title>First Blog Post</title>
			<link>http://localhost/Joomla_3.9.6-Stable-Full_Package/index.php/park-blog/17-first-blog-post</link>
			<guid isPermaLink="true">http://localhost/Joomla_3.9.6-Stable-Full_Package/index.php/park-blog/17-first-blog-post</guid>
			<description><![CDATA[<p><em>Lorem Ipsum is filler text that is commonly used by designers before the content for a new site is ready.</em></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus purus vitae diam posuere nec eleifend elit dictum. Aenean sit amet erat purus, id fermentum lorem. Integer elementum tristique lectus, non posuere quam pretium sed. Quisque scelerisque erat at urna condimentum euismod. Fusce vestibulum facilisis est, a accumsan massa aliquam in. In auctor interdum mauris a luctus. Morbi euismod tempor dapibus. Duis dapibus posuere quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In eu est nec erat sollicitudin hendrerit. Pellentesque sed turpis nunc, sit amet laoreet velit. Praesent vulputate semper nulla nec varius. Aenean aliquam, justo at blandit sodales, mauris leo viverra orci, sed sodales mauris orci vitae magna.</p>
]]></description>
			<category>Park Blog</category>
			<pubDate>Fri, 31 Dec 2010 23:00:01 +0000</pubDate>
		</item>
```

**Comment by AndNovAtor** [comment]
I recreated this PR with [25095](https://github.com/joomla/joomla-cms/pull/25095) and [25106](https://github.com/joomla/joomla-cms/pull/25106) (for 3.10-dev branch).
@mbabker, @franz-wohlkoenig, @wilsonge, @Quy, please check it.

**Pull request closed without merging**
