### PR TITLE
Media select all

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Adding a "select all" box in the media list view. At the moment, the only batch operation that can be performed in this view is "delete" so the main point of this is to make it easier when you have a folder full of things that you need to delete. 
## Testing

It works like any other "select all" box so, to test it, just go to a media folder that has multiple items in it and check the box. You should see that they all become selected. Uncheck the box, they will all be deselected. It works both ways so you can also check all item checkboxes and you should see that the "select all" becomes selected automatically, deselect one of the item checkboxes and the "select all" becomes deselected.
## More?

It seems to me that it would be nice to be able to select not only "all" but also on the basis of type. This is almost trivial because this view already treats folders, images, videos, and other documents as separate groups. In fact, it can be done relatively easily but it doesn't work as perfectly as I'd like due to limitations of the Joomla core js. Honestly, some of those functions are just not super great. Perhaps someone will completely rewrite them in the future and then these additional features can be easily added.

### CODE REVIEW

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 27f3371739a26b9af1e63ef73c2630aa227dab1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 27f3371739a26b9af1e63ef73c2630aa227dab1e<br /><br />The select and delete work but the message is wrong
It only shows

> Message
Delete Complete: /sampledata/fruitshop/tamarind.jpg

It would be better if it was to say something like "Multiple selected files deleted"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Ah, good catch. I'll fix this.

**Comment by okonomiyaki3000** [comment]
@brianteeman Actually... that has nothing to do with this PR. Multiple selection/deletion is already a thing and this poor message is the status quo. I can fix it in this PR though.

**Comment by okonomiyaki3000** [comment]
I'm updating both the 'file' controller and the 'folder' controller to report all deleted files and folders but, in fact, the 'file' controller is never actually used. Actually, a lot of things in this component are outdated or could use some work. For example, `JError` is still used quite a lot.

**Comment by infograf768** [comment]
```
print_r($app); die();
```
:smiley:

**Comment by brianteeman** [comment]
The component is scheduled for replacement but I guess not till 3.6 now

On 22 January 2016 at 09:48, infograf768 <notifications@github.com> wrote:

> print_r($app); die();
>
> [image: :smiley:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8852#issuecomment-173863752>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by okonomiyaki3000** [comment]
lol! Epic fail.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6c71696277bd577aeb07350780ee11a25cd1ba13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by genesisfan** [comment]
I have tested this item :white_check_mark: successfully on 6c71696277bd577aeb07350780ee11a25cd1ba13<br /><br />It works like a charm!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by wilsonge** [comment]
I'm sorry @okonomiyaki3000 but there are conflicts - so I can't merge it - can you rebase please?

**Comment by rdeutz** [comment]
This is a new feature so it has to go into 3.6.x ?

**Comment by brianteeman** [comment]
Personally its more of a bug fix than a feature as this should have always been there and it cant be said to have any effect in anything else.

**Comment by rdeutz** [comment]
"It should have been there" fits for or lot of issues :-)

Anyway I checked the last commits, there are files renamed, so when someone has overwritten a layout it fails (chances are low I know). I also think it should be testet again.

If we are strict with semver then this is a interface change and allows a different way of doing something so it isn't bugfix it is a new way and so it is a new feature. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by brianteeman** [comment]
Wow - didnt actually spot that this (small change) had so many edits. Seeing all the file changes I agree with you 3.6 and will retest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 2c272f1f541c1a2576ed5cd43d3cb249ca63a4e4<br /><br />Came across a problem when deleting invalid files

Create a file caled **test (1).jpg** and add to the images folder manually

If you try to delete it you will correctly get a message 
Unable to delete: . File name must only contain alphanumeric characters and no spaces.


Now try to use the delete all checkbox on the folder and you get a message
Unable to delete: .


When you try to delete multiple files you get a success message for each file with the filename as expected
But if you have multiple files that cannot be deleted like above then you only get the one message
Unable to delete: .
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by okonomiyaki3000** [comment]
I'll have a look at that but maybe we should address the issue of being unable to delete files because of their names. Is there any reason for that?

**Comment by brianteeman** [comment]
The reason is that there has always been the view that media manager should
only delete files that it can create.

BUT as this has now been pushed to 3.6 and @dgt41 is working on a new Media
Manager for 3.6 maybe any further new work on the existing Media Manager is
pointless

@dgt41 Thoughts?

On 13 April 2016 at 07:55, Elijah Madden <notifications@github.com> wrote:

> I'll have a look at that but maybe we should address the issue of being
> unable to delete files because of their names. Is there any reason for
> that?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8852#issuecomment-209260944>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by okonomiyaki3000** [comment]
It's perfectly fine with me to drop this PR if the functionality is being included in the new version.

**Comment by okonomiyaki3000** [comment]
On the other hand, if there's a chance that the rewrite would be delayed and get pushed back to whatever version comes after 3.6, I can easily brush this up to make sure at least this feature gets in.

**Comment by brianteeman** [comment]
I would wait for a comment from @dgt41

On 13 April 2016 at 09:03, Elijah Madden <notifications@github.com> wrote:

> On the other hand, if there's a chance that the rewrite would be delayed
> and get pushed back to whatever version comes after 3.6, I can easily brush
> this up to make sure at least this feature gets in.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8852#issuecomment-209293219>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Setting to Needs Review by @dgt41 ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by roland-d** [comment]
I am in the loop for the new Media Manager as well, work is being done for it but it isn't implemented until finished. Until then I would like to see this go in as it enhances the user experience.

@okonomiyaki3000 Could you please brush op this PR so we can get it tested and merged? Thank you.

P.s. if you are interested in contributing to the new media manager, let me know.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by okonomiyaki3000** [comment]
I'll get this PR ready then. I might be interested in the new one but not sure if I have much time to work on it.

**Comment by roland-d** [comment]
@okonomiyaki3000 Thank you, I will let Jisse contact you and you guys can figure it out the options.

**Comment by okonomiyaki3000** [comment]
@brianteeman In the case that you try to delete a badly named file along with some properly named files, do you think it's best to abort all delete operations or just skip the badly named file(s)?

**Comment by okonomiyaki3000** [comment]
For now, I've gone with deleting what can be deleted and displaying errors for what can't but I wrote it in such a way that it's very simple to abort before deleting anything in case of errors. 

There's something else to consider though. We decide which files are _good_ and which files are _bad_ before firing any events. We then warn about the _bad_ files and do nothing else with them. The _good_ files get events fired for them at which time path to the file to delete can be changed (by a a plugin). So, a _good_ path may become _bad_ (because of a plugin) but a _bad_ path has no chance to be made _good_. 

Also, `MediaControllerFile` and `MediaControllerFolder` both have identical `delete` functions. One is used when deleting a single file, the other for multiple. It's kind of nonsense. I'm not going to fix it now because it's not a big deal and anyway a new media manager is being developed. Let's hope we can avoid this kind of thing in the new one.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3ec14a07604cb5e02c7dd74d45c60c252d9ddb29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 3ec14a07604cb5e02c7dd74d45c60c252d9ddb29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8852">issues.joomla.org/joomla-cms/8852</a>.</sub>

**Comment by wilsonge** [comment]
Merged. Thanks!

**Comment by brianteeman** [comment]
Changed milestone as it was merged early

**Comment by wilsonge** [comment]
3.7.x branch :)

**Comment by brianteeman** [comment]
Oops  my mistake. Github doesn't show the bramch

**Pull request closed without merging**
