### PR TITLE
[4.0] Admin modules bootstrap

### PR DESCRIPTION
**Pull request by brianteeman**
Re-implements the missing code to output the bootstrap size and header tag for the admin modules.

At this time to test you will need to do a full install as there is NO update script yet (@richard67 can you assist on that please)

There will be no visible difference but if you edit an admin module then you can change the bootstrap size and the header tag in the advanced tab of any admin module and it will have an effect. Before this pr they didnt do anything at all.

Pull Request for Issue #33029 and #25952

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman Should we really do that with update SQL scripts for updates? Although it is possible in many cases, some people say we should not modify json with SQL replace statements. If it shall be done with SQL, I can help, but it might be weekend until I have time, and I don’t want to be the one who has to decide if we do it with SQL script or if we use script.php, so other opinions are welcome.

**Comment by brianteeman** [comment]
I dont care. I dont even care if there is an update mechanism as nothing will break (i think)

**Comment by infograf768** [comment]
This PR does what it says but see https://github.com/joomla/joomla-cms/issues/25952#issuecomment-814695653

Default bs 12 displays the modules full width of the column, other bs will just reduce the width of the module inside that column width.

**Comment by infograf768** [comment]
Example bs6 gives for Site

Screen Shot 2021-04-07 at 10 13 22

**Comment by brianteeman** [comment]
Yes that is correct because on that page there is a two column grid. So bs6 is half the width of the column.
If you go to the help page then that page has three columns etc.

Changing the fr columns is beyond the scope of this PR.

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on e40d949c217dbdc489cfe02d9b8585f50c5f2408<br /><br />I've tested this issue successfully.

Now there are other issues, for example: with the 2 columns layout, as @infograf768 says, it's not intuitive.

Another example is that if I choose width of 6 for 2 modules, they should be in the same row, not one on top of the other.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33045">issues.joomla.org/tracker/joomla-cms/33045</a>.</sub>

**Comment by ghost** [comment]
@brianteeman can your pull request get a test or need before resolve conflicting files?

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by ghost** [comment]
@brianteeman I will test when launch.joomla.org will work again, see https://github.com/joomla/joomla-websites/issues/1614#issuecomment-821979170.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 522f3e12ca9dd82265fe250788f12ecba3a61b50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33045">issues.joomla.org/tracker/joomla-cms/33045</a>.</sub>

**Comment by ghost** [comment]
> choose width of 6 for 2 modules, they should be in the same row, not one on top of the other.

@pabloarias correct but i guess its not in the scope of this pull request so you need to open a new issue.

Can you please retest? Since your test are new commits and your test doesn't count.

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on 522f3e12ca9dd82265fe250788f12ecba3a61b50<br /><br />Tested again. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33045">issues.joomla.org/tracker/joomla-cms/33045</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33045">issues.joomla.org/tracker/joomla-cms/33045</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Comment by richard67** [comment]
@brianteeman Could you test PR #33370 for the SQL updates related to this PR? Thanks in advance.

**Comment by richard67** [comment]
New PR is #33375 .

**Comment by brianteeman** [comment]
I've got better things to do than test an update from beta to beta. - sorry

**Comment by HLeithner** [comment]
> At this time to test you will need to do a full install as there is NO update script yet (@richard67 can you assist on that please)

@brianteeman not sure why you ask richard for help but when he help you tell him he is on his own? That's a strange behavior!

**Comment by richard67** [comment]
I think that was the last time I did help.

**Comment by brianteeman** [comment]
Sorry you missed something or I misunderstood something.

I understood your original post as a reminder that we dont change this json data as its userdata

**Comment by richard67** [comment]
> Sorry you missed something or I misunderstood something.
> 
> I understood your original post as a reminder that we dont change this json data as its userdata

I missed that it will really need the update SQL because I did not except it to look like reported in issue #33314 without it.

**Pull request merged**
