### PR TITLE
[4.0] [com_users] Fix query when searching and filtering users

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/26970#issuecomment-549506006 .

### Summary of Changes

Fixes condition in query when filtering and searching users.

### Testing Instructions

Open user list.
Set some filter and enter a keyword to search by.

### Expected result

Users filtered by keywords AND filters.

### Actual result

User filtered by keywords OR filters.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
Hint for testers: Don't use the "never" filter for the last visit date for the test. There is another mistake for which I am currently working on a correction.

**Comment by richard67** [comment]
2nd hint: The problem appears only with the date range filters for registered date and last visit date (of which the "never" filter for last visit date still needs a correction, see my previous comment). With other filters the problem does not appear.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7ca2a5c2ef3e92556b360035d967778fff0cd3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26981">issues.joomla.org/tracker/joomla-cms/26981</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ I just see there are PHPCS issues reported by drone.

**Comment by richard67** [comment]
@SharkyKZ Maybe we should combine this PR and my new one #26982 ? Or better keep it separate?

**Comment by SharkyKZ** [comment]
Sure, why not. Submitted https://github.com/richard67/joomla-cms/pull/14.

**Comment by richard67** [comment]
@SharkyKZ Thanks a lot. That will simplify things with testing because both errors can influence each other.

I worry we might have this "orWhere" problem at other places, too, that after that some other where is added or not, depending on filters.

**Comment by SharkyKZ** [comment]
Making PR for other places now.

**Pull request closed without merging**
