### PR TITLE
[4.0] Expired content shown in tag view

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31094.

### Summary of Changes

Fixes expired/not yet published content items shown in tag view.

### Testing Instructions

Create an article with a tag.
Set `Finish Publishing` date to a past date.
View the tag in frontend.

### Actual result BEFORE applying this Pull Request

Article is shown.

### Expected result AFTER applying this Pull Request

Article not shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 60383d9fcefcf9667fab7a0cf69f85246ebb2457<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31097">issues.joomla.org/tracker/joomla-cms/31097</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 60383d9fcefcf9667fab7a0cf69f85246ebb2457<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31097">issues.joomla.org/tracker/joomla-cms/31097</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31097">issues.joomla.org/tracker/joomla-cms/31097</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
