### PR TITLE
[4.0] No jQuery

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Remove jQuery dependency from com_actionlogs admin view

### Testing Instructions
Go to `administrator/index.php?option=com_actionlogs`
Check if the buttons ` Export Selected as CSV` and ` Export All as CSV` work correctly

### Documentation Changes Required
No, removed unneeded dependency

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5acdf7195f541dbc348ac46a2070f61a8528f249<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26584">issues.joomla.org/tracker/joomla-cms/26584</a>.</sub>

**Comment by Quy** [comment]
For `Export Selected as CSV` button, here is the message `There are no User Action logs to export.`

**Comment by richard67** [comment]
@Quy Did you do npm and clear broswer cache? I had that too but with npm and cleared cache it was ok.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5acdf7195f541dbc348ac46a2070f61a8528f249<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26584">issues.joomla.org/tracker/joomla-cms/26584</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26584">issues.joomla.org/tracker/joomla-cms/26584</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
