### PR TITLE
[4.0] Toolbar button - banner export

### PR DESCRIPTION
**Pull request by brianteeman**
Change the class of the button so that it is the same size as the others and is styled the same - see #28061 for reference

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7481348698fffbfefa6c557592824f673941096c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28062">issues.joomla.org/tracker/joomla-cms/28062</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7481348698fffbfefa6c557592824f673941096c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28062">issues.joomla.org/tracker/joomla-cms/28062</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28062">issues.joomla.org/tracker/joomla-cms/28062</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
