### PR TITLE
[4.0] Category field validation error

### PR DESCRIPTION
**Pull request by pdkpavankumar**
Pull Request for Issue # . https://github.com/joomla/joomla-cms/issues/29662

### Summary of Changes
passing correct label **for** attribute for validation to trigger

### Testing Instructions
Joomla 4 - user notes -> New

Just hit save.

Select a user.
Click save

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Documentation Changes Required
No

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0cd0c8f32c99b3cda59d44d7f8dc57cf74174d49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30612">issues.joomla.org/tracker/joomla-cms/30612</a>.</sub>

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on 0cd0c8f32c99b3cda59d44d7f8dc57cf74174d49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30612">issues.joomla.org/tracker/joomla-cms/30612</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30612">issues.joomla.org/tracker/joomla-cms/30612</a>.</sub>

**Comment by wilsonge** [comment]
I’m not sure this is right and will likely have association issues - see the original discussion about this change at https://github.com/joomla/joomla-cms/pull/24775

**Comment by pdkpavankumar** [comment]
@wilsonge agree, the root cause of this issue is id and for attribute mismatch which is making validation to not trigger.

**Comment by infograf768** [comment]
Setting back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30612">issues.joomla.org/tracker/joomla-cms/30612</a>.</sub>

**Comment by infograf768** [comment]
I am closing this as I reopened the original issue.

**Pull request closed without merging**
