### PR TITLE
Change version to 3.9 in JVersion

### PR DESCRIPTION
**Pull request by laoneo**
Fixes the version strings in the version class.

### CODE REVIEW

**Comment by brianteeman** [comment]
Isn't this something done by the automatic bump script?

**Comment by laoneo** [comment]
I don't know, the tests are failing because of it.

**Comment by mbabker** [comment]
The since tags are not the issue.  It's the new `MINOR_VERSION` constant not being bumped after a staging to 3.9 merge.

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/a561ae5826e91e665bac0826d903584667a07dd4

**Pull request closed without merging**
