### PR TITLE
[privacy] Create only 1 domain for the items custom fields (simplify export xml)

### PR DESCRIPTION
**Pull request by cyrez**
### Summary of Changes
Privacy information request: create only 1 domain for the items custom fields to simplify export xml.

### Testing Instructions
- Install Joomla 3.9.0 RC with sample data (or create some articles, contacts)
- Create custom fields for article (do the same for contact, users).
- Create a new user information export request in component Privacy (if none exists). Easier to create one for super user email address (sample data is created with super user as creator)
- Export user information from request in privacy component before to apply this patch.
- Check xml file for content_custom_fields, contact_custom_fields and users_custom_fields domains
_Result_ : 1 domain element is creating for each item.
- Apply the patch
- Export again the same user information request.
- Check second xml file for content_custom_fields, contact_custom_fields and users_custom_fields domains
_Result_ : 1 domain element is creating for all items (simplify the view and readability of the export xml file).

### Expected result
```
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data">
    <item>
      <content_id>67</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
    <item>
      <content_id>69</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
    <item>
      <content_id>70</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value>Test CF value</field_value>
    </item>
    <item>
      <content_id>6</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
    [...]
  </domain>

```

### Actual result
```
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data">
    <item>
      <content_id>67</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
  </domain>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data">
    <item>
      <content_id>69</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
  </domain>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data">
    <item>
      <content_id>70</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value>Test CF value</field_value>
    </item>
  </domain>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data">
    <item>
      <content_id>6</content_id>
      <field_name>test-custom-field</field_name>
      <field_title>Test Custom Field</field_title>
      <field_value/>
    </item>
  </domain>
  [...]

```

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by mbabker** [comment]
If this doesn't merge for 3.9.0 then honestly we probably can't take it until 4.0 because it does change the exported schema structure.

**Comment by laoneo** [comment]
Agree with @mbabker, so lets get some tests here.

**Comment by cyrez** [comment]
Another test example with **NO custom fields**, could help to see current result VS expected result...

- Install 3.9.0 RC with sample data
- Create a frontend menu to generate a user privacy information request for email of super user
- Go to admin to download the export xml file
- Then install patch, and export again the xml file to see expected result.


### Expected result
```
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
```


### Actual result
```
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
  <domain name="content_custom_fields" description="joomla_content_custom_fields_data"/>
```

No custom fields for articles result in as many line for content_custom_fields as articles created by exported user.
_(the same for contacts, but not issue with user custom fields, as only one user exported. This patch aims to manage array of item(s) to manage the contents/contacts as well as user exported custom fields)_

Let's imagine the user has created 1000 articles, with no custom fields... ;-)

**Comment by mbabker** [comment]
I have tested this item :white_check_mark: successfully on 2a79839044945b9b47c6013978d432006ed5def1<br /><br />Important note: Make sure you have at least two articles for the user whose data is being exported, otherwise you'll be like me and spend 10 minutes trying to recreate the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22608">issues.joomla.org/tracker/joomla-cms/22608</a>.</sub>

**Comment by cyrez** [comment]
> Important note: Make sure you have at least two articles for the user whose data is being exported, otherwise you'll be like me and spend 10 minutes trying to recreate the issue.

I have added the info to install with sample data in my last post, but i've forgotten to mention it on PR testing instructions. I've updated it! Thanks!

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2a79839044945b9b47c6013978d432006ed5def1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22608">issues.joomla.org/tracker/joomla-cms/22608</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22608">issues.joomla.org/tracker/joomla-cms/22608</a>.</sub>

**Comment by cyrez** [comment]
Thanks!

**Pull request merged**
