### PR TITLE
TinyMCE 4.5.6

### PR DESCRIPTION
**Pull request by brianteeman**
Version 4.5.6 (2017-03-30)
	Fixed bug where it wasn't possible to select floated images in some cases.

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 28b4f941a1ea83defbe30b26a6e8f5c0a83ad49c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15091">issues.joomla.org/tracker/joomla-cms/15091</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 28b4f941a1ea83defbe30b26a6e8f5c0a83ad49c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15091">issues.joomla.org/tracker/joomla-cms/15091</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by brianteeman** [comment]
@franz-wohlkoenig

I think you mean tests not Hoden . ;)

**Comment by franz-wohlkoenig** [comment]
updated saved replies, had hundrets of them.

**Comment by brianteeman** [comment]
I noticed it before but didn't comment until I realised it was a saved reply.😀

**Comment by brianteeman** [comment]
thanks

**Comment by wilsonge** [comment]
thankyou :)

**Pull request merged**
