### PR TITLE
Support readonly editors

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #13665 .

### Summary of Changes
This PR adds support for readonly/disabled editors

### Testing Instructions
* Create a new custom field of the type "editor" and either set the permission so it is not editable (that's the case by default in the contact form) or enabled readonly or disabled in the field options
* Check the item where the field appears
* Test with all three core editors (TinyMCE, Codemirror, None)

Another test:
* Edit the editor formfield spec in a form XML and add a `readonly="true"` attribute to it. Eg edit /administrator/models/forms/article.xml and change
````
<field 
	name="articletext"
	type="editor"
	label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
	description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
	filter="JComponentHelper::filterText"
	buttons="true"
/>
````
to
````
<field
	name="articletext"
	type="editor"
	label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
	description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
	filter="JComponentHelper::filterText"
	buttons="true"
	readonly="true"
/>
````
* Check the item

### Expected result
Editor should be readonly/disabled.

### Actual result
You can edit the content fine.

### Documentation Changes Required
https://docs.joomla.org/Editor_form_field_type can now have added attributes "readonly" and "disabled" (they both do the same thing here).

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 7fef75c6a2cb56bcd9006b167f2228beae487224<br /><br />with tinymce as the editor I created an editor field for a contact and set it to read only.
I created a new contact and can confirm that the tinymce editor is disabled BUT I then click on the Toggle Editor and can enter text into the editor AND this text will be saved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15157">issues.joomla.org/tracker/joomla-cms/15157</a>.</sub>

**Comment by Bakual** [comment]
Good catch, now to figure out where that comes from 😄

**Comment by Bakual** [comment]
@brianteeman Can you try again? I think I fixed that now.

**Comment by zero-24** [comment]
@Bakual http://213.160.72.75/joomla/joomla-cms/2432 Drone is complaining ;)

**Comment by brianteeman** [comment]
@Bakual that fixed that bug

**Comment by Bakual** [comment]
> Drone is complaining ;)

@zero-24 Fixed 👍 

@brianteeman Thanks for the confirmation.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 58e0ce3ad1e7468cef61239e8f9e2cda1b72a78b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15157">issues.joomla.org/tracker/joomla-cms/15157</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@brianteeman can i alter your Test as successfully?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15157">issues.joomla.org/tracker/joomla-cms/15157</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 58e0ce3ad1e7468cef61239e8f9e2cda1b72a78b<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15157">issues.joomla.org/tracker/joomla-cms/15157</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
> @brianteeman can i alter your Test as successfully?

No - I did not fully test it - I only tested the one small part

**Pull request merged**
