### PR TITLE
[4.0] Move some inline scripts to separate JS files

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #19640

### Summary of Changes

Move some inline scripts for files in the `layouts` folder to separate JS files.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
This would be a good starting point for anyone that wants to get their fingers dirty with vanilla js.
I'll write some examples:
jQuery 
```js
jQuery(document).ready(function($) {
}):
```
Vanilla 
```js
document.addEventListener('DOMContentLoaded', function() {
}):
```
jQuery
```js
if ($("#batch-category-id").length){
		var batchSelector = $("#batch-category-id");
}
```
vanilla
```js
if (document.querySelector("#batch-category-id").length){
		var batchSelector = document.querySelector("#batch-category-id");
}
```

jQuery
```js
$("#batch-copy-move").hide();
$("#batch-copy-move").show();
```
vanilla
```js
document.querySelector("#batch-copy-move").style.display = 'block';
document.querySelector("#batch-copy-move").style.display = 'none';
```

jQuery
```js
batchSelector.on("change", function(){
	if (batchSelector.val() != 0 || batchSelector.val() != "") {
 		$("#batch-copy-move").show();
 	} else {
 		$("#batch-copy-move").hide();
 	}
});
```
vanilla
```js
batchSelector.addEventListener("change", function(){
	if (batchSelector.value !== 0 || batchSelector.value !== "") {
 		document.querySelector("#batch-copy-move").style.display = 'block';
 	} else {
 		document.querySelector("#batch-copy-move").style.display = 'none';
 	}
});
```

**Comment by C-Lodder** [comment]
Better to use `getElementById()` over `querySelector()` for ID's if you're starting from the `document`. Much faster

**Comment by dgrammatiko** [comment]
Sure I just did it with `querySelector` to be 1 - 1 conversion but @C-Lodder is right if you're querying an element through it's id (since id's are unique) you can use the `getElementById` method

**Comment by C-Lodder** [comment]
Closing in favour of: https://github.com/joomla-projects/joomla-es6/pull/57

**Pull request closed without merging**
