### PR TITLE
[4.1] Update the configuration.php-dist thanks @brianteeman

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/37040#issue-1137719023

### Summary of Changes

Update the configuration.php-dist from here: https://github.com/joomla/joomla-cms/pull/37040#issue-1137719023 thanks @brianteeman

### Testing Instructions

Code review

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on f7bde6f58b83477938c2e90e6c7a13c45673c9e0<br /><br />core review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37041">issues.joomla.org/tracker/joomla-cms/37041</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f7bde6f58b83477938c2e90e6c7a13c45673c9e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37041">issues.joomla.org/tracker/joomla-cms/37041</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37041">issues.joomla.org/tracker/joomla-cms/37041</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37041">issues.joomla.org/tracker/joomla-cms/37041</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
