### PR TITLE
Filesystem namespace

### PR DESCRIPTION
**Pull request by fastslack**
Filesystem libs namespacing 

### Summary of Changes

Move old filesystem libraries to namespace

### Testing Instructions

Apply this patch and run Joomla!. Everything should work without issues

### CODE REVIEW

**Comment by wilsonge** [comment]
Kill the wrapper classes please :)

**Comment by laoneo** [comment]
I would love to see it against staging or at least 3.9. Can we change the base branch of it?

**Comment by fastslack** [comment]
@laoneo should i close this PR and open a new one?

**Comment by laoneo** [comment]
Whatever feels more comfortable for you.

**Comment by ghost** [comment]
@fastslack close this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18321">issues.joomla.org/tracker/joomla-cms/18321</a>.</sub>

**Comment by fastslack** [comment]
@franz-wohlkoenig closed i ll open a new one soon

**Comment by fastslack** [comment]
Need review https://github.com/joomla/joomla-cms/pull/18565

**Pull request closed without merging**
