### PR TITLE
Make squeezebox initialize itself when a new subform row is added

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes

Subform repeatable has a function `fixScripts` which calls a few js initialization functions on a few of the field types that require it. There is a now a better way to handle that kind of thing by having any field that may need initialization listen for an event fired by subform repeatable. In this PR, I am transferring responsibility of one such initialization from subform repeatable to the correct field type itself. 

Note: this PR doesn't really fix anything. Fields that use squeezebox already work with repeatable subforms. This just does it in a somewhat better way. 

Another note: Squeezebox uses mootools and is deprecated. Bootstrap modals are prefered. Still, as long as some fields use it, they should use it like this. 

### Testing Instructions

Set up a subform containing a field that uses squeezebox (for example `contenthistory`). There's a subform in the redirect plugin that's simple to use for this purpose. 

Open up the form and create new rows. The field in each new row should function properly. 

### Expected result

Fields that use squeezebox function normally.

### Actual result

Fields that use squeezebox function normally.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 41229fdcc3088fadb100ad2eb740b6db4fecd5d7<br /><br />Tested with the Redirect plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20232">issues.joomla.org/tracker/joomla-cms/20232</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 41229fdcc3088fadb100ad2eb740b6db4fecd5d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20232">issues.joomla.org/tracker/joomla-cms/20232</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20232">issues.joomla.org/tracker/joomla-cms/20232</a>.</sub>

**Comment by alikon** [comment]
@HLeithner please a final response 

1 year old rtc pr

**Comment by HLeithner** [comment]
I think it makes no sense merging this if it fix nothing and subforms doesn't exists anylonger in j4. ymmv

**Comment by okonomiyaki3000** [comment]
Wait... subforms don't exist anymore?

**Comment by HLeithner** [comment]
They are getting hopefully replaced with https://github.com/joomla/joomla-cms/pull/24711 if you can please test subfields, also a migration script should kick in converting subforms to subfields.

**Comment by wilsonge** [comment]
@HLeithner you're getting confused here. subforms do exist :) these are the xml attributes. subfields you're linking to are just subforms as a custom field

**Comment by HLeithner** [comment]
thx @wilsonge for correction

**Comment by okonomiyaki3000** [comment]
So we're still doing this, right?

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20232">issues.joomla.org/tracker/joomla-cms/20232</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
