### PR TITLE
Update folderinstaller.xml

### PR DESCRIPTION
**Pull request by Ayushgadre**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
Do you see all those questions you were asked. You were supposed to answer them. Otherwise no one knows why you made the changes and no one will be able to test it.

**Comment by Deepesh0289** [comment]
Could anyone tell me more about this issue? I am new for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37520">issues.joomla.org/tracker/joomla-cms/37520</a>.</sub>

**Comment by richard67** [comment]
> Do you see all those questions you were asked. You were supposed to answer them. Otherwise no one knows why you made the changes and no one will be able to test it.

@Ayushgadre What @brianteeman means with his comment is that you did not fill in any of the information in the description of your pull request (PR).

There are headlines for this already:
- Summary of Changes
- Testing Instructions
- Actual result BEFORE applying this Pull Request
- Expected result AFTER applying this Pull Request
- Documentation Changes Required

You are expected to add the corresponding information below each headline.

And when your PR solves an existing issue (see https://github.com/joomla/joomla-cms/issues for the complete list), please refer to the issue in the top "Pull Request for Issue # ." line by appending the issue number to the "#".

**Comment by richard67** [comment]
> Could anyone tell me more about this issue? I am new for this.

@Deepesh0289 This here is not an issue, it is a pull request. The author is requested to provide information on it in the description. Then it can be tested by contributors. Check our documentation if you are new to it, e.g. this one: https://docs.joomla.org/Testing_Joomla!_patches .

**Comment by drmenzelit** [comment]
Closing this PR as it is introducing an unnecessary change (removed a blank space).
@Ayushgadre @Deepesh0289 please ask your questions about Joomla in the GSoC students channel in glip.

**Pull request closed without merging**
