### PR TITLE
[4.0] Update chosen to latest version

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28154 .

### Summary of Changes
Update chosen to the latest version

### Testing Instructions
Add `HTMLHelper::_('formbehavior.chosen', 'select');` (I did `administrator/components/com_content/tmpl/article/edit.php` and check select boxes show as chosen (note some might conflict with either the fancy box or choices views - that's fine - just check regular select boxes)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 3078ed48898e6141b92a4d43a6913d827034a2d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28354">issues.joomla.org/tracker/joomla-cms/28354</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3078ed48898e6141b92a4d43a6913d827034a2d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28354">issues.joomla.org/tracker/joomla-cms/28354</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28354">issues.joomla.org/tracker/joomla-cms/28354</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
