### PR TITLE
[3.7] Simplify instantiation of Registry

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Following https://github.com/joomla/joomla-cms/pull/12270 this simplifies the instantiation of Registry objects across the rest of the application.  This also replaces a couple lingering uses of JRegistry.
### Testing Instructions

Functions using the Registry object continue working as expected.
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by sovainfo** [comment]
What about removing the usage of $registry when not needed?

**Comment by mbabker** [comment]
> What about removing the usage of $registry when not needed?

Working through that as able, some things are easier than others.

**Comment by sovainfo** [comment]
Thanks for not ignoring.
Too late for this PR, but thought about replacing
$data->params->merge($registry);
with 
$data->params->merge(new Registry($data->params));
making $registry obsolete.

**Comment by mbabker** [comment]
I was thinking about that last night but honestly couldn't remember if PHP 5.3 supported that syntax (this is the only place I write code anymore that has to retain 5.3 compatibility).  All in all I'm trying to clean things up bit by bit which also makes cleaning stuff up in the 4.0 branch easier (like the places that are casting the Registry to a string could be replaced with `(new Registry($data))->toString();` with 5.4+ syntax to avoid the needless variable AND keeping that stuff in memory).

**Pull request merged**
