### PR TITLE
[4.0] Fix a warning "language has been changed"

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #27258 .

The script associations-edit should check for a selected value, not for the article title.

### Testing Instructions

Please look #27258 for detail

Note: need to run `npm install`

### CODE REVIEW

**Comment by infograf768** [comment]
@Fedik 
There was a good reason we switched to name instead of id.
Will try to find the PR concerned tomorrow.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/25060

**Comment by Fedik** [comment]
I see, 
but the `_name` always have a value (even if nothing selected), so it make no sense to use it to detect  `existsAssociations = true;`, 
or I missed something, hm

**Comment by infograf768** [comment]
Looks like the file has been modified since #25060 . Your PR works fine. thanks.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a1c90783277ad9e286729707b6e4d6f8121dc3d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27269">issues.joomla.org/tracker/joomla-cms/27269</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a1c90783277ad9e286729707b6e4d6f8121dc3d9<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27269">issues.joomla.org/tracker/joomla-cms/27269</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27269">issues.joomla.org/tracker/joomla-cms/27269</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
