### PR TITLE
[4.0] Fix tinymce the options form

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Fixing the tinymce configuration form, broken after #33177
Also clean up after #25734 

### Testing Instructions
Apply path,
Try change the editor skin to dark, 

### Actual result BEFORE applying this Pull Request
skin not changes

### Expected result AFTER applying this Pull Request
skin changes

### Documentation Changes Required
no

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a85eb45a91b9f2a171fdd091b560ae82c2e44362<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33464">issues.joomla.org/tracker/joomla-cms/33464</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR just by the way.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a85eb45a91b9f2a171fdd091b560ae82c2e44362<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33464">issues.joomla.org/tracker/joomla-cms/33464</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33464">issues.joomla.org/tracker/joomla-cms/33464</a>.</sub>

**Comment by richard67** [comment]
Restarted drone. all fine now.

**Comment by Quy** [comment]
Thanks

**Pull request merged**
