### PR TITLE
[4.0] Background and color change to quickicons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Adds a background color to quickicons area. Color change to quickicons.

### Testing Instructions
Open 'control panel'

### Before
quickicons1

### Actual result
quickicons2

### CODE REVIEW

**Comment by ghost** [comment]
bildschirmfoto 2017-07-11 um 11 08 55
Will make a new Install and looks if this works.

**Comment by C-Lodder** [comment]
@franz-wohlkoenig One of my PR's that got merged yesterday adds this file to the template. Please ensure you have the latest Joomla code before applying the patch.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 60fcabf88ef12a8d7091b0c7a07343bc2f7253d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17062">issues.joomla.org/tracker/joomla-cms/17062</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 60fcabf88ef12a8d7091b0c7a07343bc2f7253d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17062">issues.joomla.org/tracker/joomla-cms/17062</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Can we check this new contrast meets AA

**Comment by wilsonge** [comment]
My guess is the white text on light blue and the light blue on the dark blue would fail. But only looking at the screenshots on my mobile which isn't exactly a reliable checker :p

**Comment by ciar4n** [comment]
Original it was only AA compliant with small text. I've made buttons darker to be compliant for both small and large text...

quickicons3

**Pull request merged**
