### PR TITLE
Properly update associations during saving

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #11871.

The associations are not properly updated when making changes:
- Removing an associated item doesn't remove it from the database `#__associations` table.
- Setting the item language to `All` clears all other associations.
### Summary of Changes

`JModelAdmin::save` now deletes all associations for the currently saved item based on its association key plus if present on the associated items ids.
If language is set to `All`, the saved item isn't added to the `$associations` array anymore. However it now always saves the associations, regardless of the language of the saved item.
### Testing Instructions

From the original issue:

> Multingual site with associations enabled.
> 3 content languages
> 
> Create an article in each content language and associate them.
> 
> Then edit one of these articles and change its language to ALL.
> The article saves with this correct warning:
> 
> A content item set to All languages can't be associated. Associations have not been set.
> The problem is that the 2 other articles are no more associated between them.

Additionally test with at least 4 content languages:
1. Associate an item to 3 other items and save
2. Remove the association of two items and save
3. Expected result would be to only have the remaining two items associated but you get 2 pairs of associations now, the removed ones build one (unexpected) and the saved one builds another one (expected).
Apply patch and try again and you should only get the saved pair. The removed ones aren't associated to anything anymore.

Also test other cases like removing all associations.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by C-Lodder** [comment]
Correct me if I'm wrong, but shouldn't you be using `$query->clear()`?

**Comment by Bakual** [comment]
@infograf768 One thing I was unsure was the behavior of the association data in the form when switching the language to "All".
With this PR, changes made to the association would stick. The warning message would be a bit misleading.

Another way would be to leave the existing association entries alone and just remove the edited item. But then you need to query the database first (since we don't know the existing state) and then decide if we need to delete one item or in case there would be only one left both of them.

**Comment by Bakual** [comment]
> Correct me if I'm wrong, but shouldn't you be using $query->clear()?

Why or where do you think so? `$query = $db->getQuery(true)` gives you always a clean query.
`$query->clear()` imho is used when you want to clear certain aspects of an existing query to run a similar query again.

**Comment by infograf768** [comment]
will test tomorrow.

**Comment by infograf768** [comment]
one fast remark though
if I remember well, com_categories are special cases

**Comment by Bakual** [comment]
> one fast remark though
if I remember well, com_categories are special cases

Good memory. Did it for categories in the category model as well.

**Comment by infograf768** [comment]
and com_menus?

**Comment by Bakual** [comment]
> and com_menus?

Done now as well. Anything else? :smile:

**Comment by infograf768** [comment]
First test
4 languages
I have 3 items associated
screen shot 2016-09-02 at 08 41 41

I create a new item in a 4th language and associate it to one of the items (here the it-IT one to the fr-FR one, without selecting anything else in the association tabs for the 2 other languages).
I expect the 4 items to be associated.
Result: I lose the existing associations:

screen shot 2016-09-02 at 08 46 01

If I do the same but also associating to en-GB. 
Result: the es-ES one is no more associated to anything.

screen shot 2016-09-02 at 08 50 45

I have to associate the new it-IT article to ALL the already associated items to get what I expect.

screen shot 2016-09-02 at 08 53 15

**Comment by infograf768** [comment]
Second test:
I have 4 items associated. I change the language of one of the items to "All languages".
The other items remain associated. 
It therefore solves https://github.com/joomla/joomla-cms/issues/11871 👍 
screen shot 2016-09-02 at 08 58 46

**Comment by Bakual** [comment]
For the first test, I would say it is expected behavior. If you assign your italian article only to one other article, it should not magically associate with additional articles. It should only associate with the ones I have chosen. And that is what it does and what it did before this PR afaik.

If you want to assign your italian article, simplest way is to add it from an existing associated article.

**Comment by infograf768** [comment]
>If you want to assign your italian article to an existing association group, simplest way is to add it from an existing associated article.

It is indeed what it did before this PR. Would be nice to let the user choose though.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on cad32915b4fc7ad1171ad8cf234cf2d0affba1d9<br /><br />@andrepereiradasilva 

@jreys 

@alikon 



Please test this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11877">issues.joomla.org/joomla-cms/11877</a>.</sub>

**Comment by infograf768** [comment]
Concerning the message, we get now for articles
`COM_CONTENT_ERROR_ALL_LANGUAGE_ASSOCIATED="A content item set to All languages can't be associated. Associations have not been set. "`
and similar for other components.

code is
```
JFactory::getApplication()->enqueueMessage(
					JText::_(strtoupper($this->option) . '_ERROR_ALL_LANGUAGE_ASSOCIATED'),
					'warning'
				);
```
and similar for categories and menus except that we raise Notice instead of warning.

Do you think we could use an alert at saving time when the item is not new and its language is changed to All while it already has associations?

**Comment by Bakual** [comment]
> It is indeed what it did before this PR. Would be nice to let the user choose though.

Imho, that would become overly complex.

> Do you think we could use an alert at saving time when the item is not new and its language is changed to All while it already has associations?

It sure could be done using JavaScript checking, but I would be the wrong person to do that. And I'm not sure if we should.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cad32915b4fc7ad1171ad8cf234cf2d0affba1d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11877">issues.joomla.org/joomla-cms/11877</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks!

Please set milestone to 3.6.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11877">issues.joomla.org/joomla-cms/11877</a>.</sub>

**Pull request merged**
