### PR TITLE
[4.0] Switch remaining options from grid to column layout

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #27136.

### Summary of Changes
This PR applies #27141 to the remaining forms.

### Testing Instructions
Apply this patch and run `node build.js --compile-css` for updating the changed SCSS. 

Ensure options column layout is correct. The majority of this PR effects the Global Configuration form layout. For details on these changes, take look at #27141.

### CODE REVIEW

**Comment by Quy** [comment]
Fieldset/legend not styled.

BEFORE:
27153-before

AFTER:
27153-after

**Comment by ciar4n** [comment]
> Fieldset/legend not styled.

@Quy I am unable to replicate this. Full refresh after compiling?

**Comment by Quy** [comment]
Installed your branch and it is fine. Yes, full refresh after compiling. I must have done something wrong. Thanks.

**Comment by Quy** [comment]
Will the following be one column? I see that this is the case with `Configure Edit Screen`.

27153-options

**Comment by ciar4n** [comment]
My personal preference would be all one column but it was not my intent here to change that. It looks like I missed the `Configure Edit Screen` tab.

**Comment by ciar4n** [comment]
I have moved the `Configure Edit Screen` to 3 columns as before.

**Comment by Quy** [comment]
That would be my preference too as I find it disorienting in columns as mentioned in ##25891.

**Comment by Quy** [comment]
Table not full width under Global Configuration > Permissions.

27153-permissions

**Comment by brianteeman** [comment]
that one is a special case iirc and has a class specified `administrator\components\com_config\tmpl\application\default_permissions.php`

**Comment by ciar4n** [comment]
Thank you. It should be ok now.

**Comment by Quy** [comment]
`Debug Language` moves depending on the selection. Is this beyond the scope of this PR?
When `Yes`, it is in the first column.
When `No`, it is in the second column. 

debug-on

debug-off

PS: Global Configuration differs from the other Components' settings by having 2 columns vs 1 column.

**Comment by ciar4n** [comment]
Thanks @Quy. I'll have a look in to this in the morning.

**Comment by ciar4n** [comment]
> Debug Language moves depending on the selection.

Debug fields re-ordered to amend this issue..

c51JcHZx4X

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 11a3af806f0c4aa4d7c059fe4cdd706075ad3ce1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27153">issues.joomla.org/tracker/joomla-cms/27153</a>.</sub>

**Comment by Quy** [comment]
Sorry another one with `Connection Encryption`:

27153-database-1way

27153-database-2way

**Comment by ciar4n** [comment]
Sry @Quy.. I'd forgotten about this.

Currently no way around stopping the jump here. The column-count CSS property, by default, evenly splits content across the set number of columns.. Because this show-on adds so many new fields, some of the fields will always jump to the first column.

AFAIK we can not set the break point (spec.. https://drafts.csswg.org/css-multicol-1/#cc). Even if we can, I suspect https://github.com/joomla/joomla-cms/issues/27165 will be an issue

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 11a3af806f0c4aa4d7c059fe4cdd706075ad3ce1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27153">issues.joomla.org/tracker/joomla-cms/27153</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1e661b6ccda3e7ade0f297aacd006a624b42a7fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27153">issues.joomla.org/tracker/joomla-cms/27153</a>.</sub>

**Comment by infograf768** [comment]
It does no solve https://github.com/joomla/joomla-cms/issues/27490

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Sorry for missing this when it first came in

**Comment by Quy** [comment]
@ciar4n Please look into the issue I reported here as this happening in the nightly builds. Thanks.

https://github.com/joomla/joomla-cms/pull/27153#issuecomment-558699905

**Pull request merged**
