### PR TITLE
[4.0] Use double colon for pseudo elements

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Use double colon for pseudo elements

### Testing Instructions

Code review

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I should be blamed for this...

**Comment by brianteeman** [comment]
it is actually optional for this pseudo element but I am happy to blame @dgrammatiko

**Comment by C-Lodder** [comment]
@brianteeman Still optional but better to distinguish between a pseudo element and pseudo class. You also never know if browsers will drop single colons for pseudo elements in the future.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 15035c7e18c993b77ea28574d32ed539289bb4c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26088">issues.joomla.org/tracker/joomla-cms/26088</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15035c7e18c993b77ea28574d32ed539289bb4c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26088">issues.joomla.org/tracker/joomla-cms/26088</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26088">issues.joomla.org/tracker/joomla-cms/26088</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by ghazal** [comment]
I have tested this item :red_circle: unsuccessfully on f24c44153ce9324563baee230fde692b469ea7b0<br /><br />Just tested this on a fresh install with Composer and NPM,  and I got this error in the Terminal:
```Error: ".icon-generic::before" failed to @extend ".fa-dot-circle::before".
       The selector ".fa-dot-circle::before" was not found.
       Use "@extend .fa-dot-circle::before !optional" if the extend should be able to fail.
        on line 22 of build/media_source/system/scss/_icomoon.scss
>>     @extend .#{$fa-css-prefix}-dot-circle::before; 

compile-css could not proceed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26088">issues.joomla.org/tracker/joomla-cms/26088</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

Fixed with https://github.com/joomla/joomla-cms/commit/4a5a2fb4b154bcbdd1e74c6e5e36dd99fa9d57a1 (clearly no one actually tested)

**Pull request merged**
