### PR TITLE
[4.0] Remove unnecessary queries in article form

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Pass the slug to route helper to remove some database queries.

### Testing Instructions

Edit a published article in backend. Click on Preview button.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e444c4ab4bd191c9eddcc38aab133b72bdf25264<br /><br />Note for other testers:
When testing with a blog sample data article, this PR has to be applied together with PR #26209 , otherwise you get the SQL error mentioned in that PR instead of the preview.
When PR #26209 was applied and this PR here not, I had 56 queries.
When both PRs were applied I had 54 queries, if I remember right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26220">issues.joomla.org/tracker/joomla-cms/26220</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e444c4ab4bd191c9eddcc38aab133b72bdf25264<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26220">issues.joomla.org/tracker/joomla-cms/26220</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26220">issues.joomla.org/tracker/joomla-cms/26220</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
