### PR TITLE
[5.2] remove margin-bottom on .btn styling to prevent nasty offset

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

This PR will remove the following piece of SCSS and uses proper Bootstrap classNames to achieve the same goal.

https://github.com/joomla/joomla-cms/blob/45adb61f8306b945f43b4326305fafe87c154aa2/build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_buttons.scss#L50-L57

PR https://github.com/joomla/joomla-cms/pull/32697 introduced a margin-bottom of .25em on all buttons.
A fix made by @brianteeman prevented this to happen on buttons in an input-group.
Both are not needed when using proper Bootstrap classNames on the wrapping element.

### Testing Instructions

- Joomla 5.1 with sample data installed.
- Compile SCSS
- Head over to page Typography and reduce the viewport. On mobile the elements with className `.btn` are stacked with a proper gap between.
- Login on frontend and click an item to edit. On mobile the elements with className `.btn` are stacked with a proper gap between.
- Go to a random page to invoke a 404. Inspect the button with home icon and text "Home page". On mobile this button has no obsolete margin-bottom anymore. And all elements with className `.btn` don't have a obsolete margin-bottom anymore. 

### Actual result BEFORE applying this Pull Request
Scherm­afbeelding 2024-04-10 om 17 15 10

Scherm­afbeelding 2024-04-10 om 17 13 25

Scherm­afbeelding 2024-04-10 om 17 12 12

### Expected result AFTER applying this Pull Request

Scherm­afbeelding 2024-04-10 om 17 15 31

Scherm­afbeelding 2024-04-10 om 17 13 05

Scherm­afbeelding 2024-04-10 om 17 12 32

### Comment
Even Bootstrap core has no margins around buttons. See screenshot below where I have disabled the DOCS styling.

Scherm­afbeelding 2024-04-10 om 17 05 01

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Which was the PR I made a partial fix in? Would like to check exactly what the issue it was fixing is still fixed. Thanks

**Comment by brianteeman** [comment]
Thanks

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by RAMBOTOTO** [comment]
RAMBOTOTO

[RAMBOTOTO](https://www.rambototo.com/ "RAMBOTOTO")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43247">issues.joomla.org/tracker/joomla-cms/43247</a>.</sub>

**Comment by JeroenMoolenschot** [comment]
I have tested this item :white_check_mark: successfully on bbc2940bac8c5f50d68fd4653ac28f356ecfe802<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43247">issues.joomla.org/tracker/joomla-cms/43247</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 59254e368d3e5b861030a91a434dc3ee1c5bfb38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43247">issues.joomla.org/tracker/joomla-cms/43247</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43247">issues.joomla.org/tracker/joomla-cms/43247</a>.</sub>

**Comment by pe7er** [comment]
Thanks @hans2103 !

**Pull request merged**
