### PR TITLE
[4.0] Token plugins

### PR DESCRIPTION
**Pull request by brianteeman**
renames the files to remove the en-gb prefix
fixes two typos
alpha sorts the strings

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8552362a0549cee8f86f51f41e735e1c637b44f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28486">issues.joomla.org/tracker/joomla-cms/28486</a>.</sub>

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/en-GB.plg_api-authentication_token.ini

these also need renaming

**Comment by brianteeman** [comment]
they are renamed in this pr already
https://github.com/joomla/joomla-cms/pull/28486/files#diff-c31d6a9d5de5ea12e6940ad11f99272a

**Comment by infograf768** [comment]
oops

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
