### PR TITLE
Hide Intro Text not working - blog_item.php

### PR DESCRIPTION
**Pull request by DelPoint**
In current stable J! version (4.03) the option to hide **Intro Text** is not working on blog views. **Intro Text** is displayed always regardless of settings.

Pull Request for Issue: -

### Summary of Changes
Added `if-endif` around `echo $this->item->introtext;` in blog_item.php

### Testing Instructions
1. Apply PR.
2. Use Cassoipeia template to minimize effects of 3rd party templates.
3. Create an article with intro text.
4. Set option **Intro Text** in **Global Configuration -> Articles -> Articles panel** to **Hide**.
5. Check if this setting is not overwritten in Menu / Article.
6. Check article in category blog view.

### Actual result BEFORE applying this Pull Request
Intro text will be there regardless of the option selected for **Intro Text**.

Actual Result
### Expected result AFTER applying this Pull Request
Intro text should be hidden for the article.

Expected Result

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by brianteeman** [comment]
sorry but this is completely wrong and you have misunderstood the purpose of the hide intro text option. A blog view will always show the intro text. The linked full article view will show the full text. the purpose of this option is to hide the intro text from the full article view.

**Comment by brianteeman** [comment]
https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help40:Articles:_Edit

Please close this

**Comment by rdeutz** [comment]
If you want to do this you can make an overwrite, but as Brian said it is not what the option is meant to be.

**Comment by DelPoint** [comment]
`you have misunderstood the purpose of the hide intro text option`
That is likely :) It has never occured me Brian's explanation.

`you can make an overwrite`
Yes, I know. But actually I think Brian's explanation of the function makes more sense than mine vague, original idea about it.

Sorry for your time guys.

**Comment by vdneut** [comment]
Sorry to dig up this topic, but there is a discrepancy on how the option to not show the intro is used in html and feed rendering.
If the show intro option is set to false, the html renderer does not show the intro of the article in full article view.
However, if I define the feed to show full article (in Article option Tab Integration), the feed shows both the intro as well as the full article. The feed does not obey / follow the article option not to show the intro in full article view. This is the case in both J3 as J4.
If you do not agree with me, that's fine, but could you please give me a hint where to change this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35869">issues.joomla.org/tracker/joomla-cms/35869</a>.</sub>

**Comment by brianteeman** [comment]
full article = intro + rest

**Comment by vdneut** [comment]
I see now that my problem description does not belong here in this topic. I can not delete it, but it should.
I will create a separate topic for it. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35869">issues.joomla.org/tracker/joomla-cms/35869</a>.</sub>

**Pull request closed without merging**
