### PR TITLE
Calendar Fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #16590 .

### Summary of Changes
List of changes:
- Make all comparisons strict
- fix the bottom buttons (clear, today, close)
- Clear button disappeared if today button was disabled
- Fix the inconsistency of manual input (enter, tab, etc)

### Testing Instructions
Create a new article and fill the publishing fields with different methods (manual using the UI)
save the article
Edit again the fields (try clearing the filed with backspace, the clear button) and also change the values manually and using the UI
Report any remaining inconsistencies, if any

### Expected result
Consistent behaviour

### Actual result
Inconsistent behaviour

### Documentation Changes Required

Calling @farhadst to crash test the Jallali calendar

### CODE REVIEW

**Comment by infograf768** [comment]
Please @farzadtaheri also test this in Persian

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9fd1e06139dac6ef1675eeb9e49912221db2e338<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16794">issues.joomla.org/tracker/joomla-cms/16794</a>.</sub>

**Comment by dgt41** [comment]
@farzadtaheri @farhadst can you please test Joomla 3.7.3 RC! This is really important, thank you

**Comment by farzadtaheri** [comment]
@dgt41 i have this issue yet: #16628

**Comment by dgt41** [comment]
@farzadtaheri your solution `Joomla.submitform('field.storeform', element.form);` needs to be merged, can you do a PR for that?

**Comment by farzadtaheri** [comment]
@dgt41 please check #16721.

**Comment by farzadtaheri** [comment]
my solution Joomla.submitform('field.storeform', element.form); is work, but there is another problem after this change!
calendar fields time shift after each category field value change, when i set Asia/Tehran time zone (or another time zones) in configuration!

**Comment by farhadst** [comment]
@dgt41 I have test joomla 3.7.3 RC!
problem for select date by popup calendar fix and not reset but after set manual time and date and save it, time and date reset to today.

**Comment by dgt41** [comment]
>  time and date reset to today.

- What was your input?
- If what you entered was invalid the calendar falls back to today!

**Comment by ghasemy50** [comment]
hi
@dgt41
if any date and time selected manual and not use the calendar the date and time is reset to today and now time.
thanks

**Comment by infograf768** [comment]
@dgt41 
I confirm the issue

I copied a date in the future from an existing article publishing date and pasted it in an article just created.

Entering the date in the future (equivalent of `2017-09-29 10:57:00`) :
screen shot 2017-06-29 at 10 59 59

After save
screen shot 2017-06-29 at 11 00 26

It works perfectly in Gregorian.

**Comment by infograf768** [comment]
Equivalent in en-GB

screen shot 2017-06-29 at 11 07 22

**Comment by farhadst** [comment]
@dgt41 
I entered valid calendar like 1396-04-03 11:10:19 or by Persian number like ۱۳۹۶-۰۴-۰۳ ۱۱:۱۰:۱۹
In both cases after save calendar reset to current time and date

in Gregorian calendar every things is ok, type calendar by manual or popup calendar is fine

**Comment by infograf768** [comment]
@farhadst
On it now. As soon as there is a patch we let you know

**Comment by infograf768** [comment]
@farzadtaheri @farhadst Please test #16922 urgently

**Comment by drewgg** [comment]
Some of these issues may be related to #17171. I made some changes that fix those issues ( https://github.com/joomla/joomla-cms/pull/17183 ) but it involves removing a conditional that I don't fully understand the purpose of (that conditional was added in this pull request).

@dgt41, could you weight in on the the purpose of the `if (typeof calObj.dateClicked === 'undefined') {` conditional and why the false path is needed?

Originally, instead of removing it, I changed it to `if (typeof calObj.dateClicked === 'undefined' || !calObj.dateClicked) {` which fixed it for all cases except when using the "today" button (which results in calObj.dateClicked = true causing the else path to be taken).

**Pull request merged**
