### PR TITLE
[4.1] Fixes spacing for inline tags.

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
The spacing for inline tags made things appear smushed.  This fix better delineates between tags

### Testing Instructions
install clean  install of J4
install sample blog data
go to very bottom of page and check that image matches
run npm ci to rebuild template.css and check that image matches.

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
none

### CODE REVIEW

**Comment by N6REJ** [comment]
@chmst

**Comment by chmst** [comment]
Nice!

**Comment by Kostelano** [comment]
`padding: .5rem .25rem .5rem 0` is better so that the line of text does not move from the left side.

**Comment by N6REJ** [comment]
> `padding: .5rem .25rem .5rem 0` is better so that the line of text does not move from the left side.

I was thinking about that.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5214587445b686ad5584cfa16ea78ae99cef0660<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37805">issues.joomla.org/tracker/joomla-cms/37805</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5214587445b686ad5584cfa16ea78ae99cef0660<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37805">issues.joomla.org/tracker/joomla-cms/37805</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37805">issues.joomla.org/tracker/joomla-cms/37805</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
