### PR TITLE
[4.2] update message

### PR DESCRIPTION
**Pull request by brianteeman**
image

COM_JOOMLAUPDATE_VIEW_DEFAULT_POTENTIALLY_DANGEROUS_PLUGIN_CONFIRM_MESSAGE="Are you sure you want to ignore the warnings about potentially incompatible extensions and proceed with the update?"

COM_JOOMLAUPDATE_VIEW_DEFAULT_NON_CORE_PLUGIN_CONFIRMATION="Acknowledge the warnings about potentially incompatible extensions and proceed with the update."

changes the first one to also use the word acknowledge and not ignore

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ed1aa328cbae9047fb87025b10bfe49b11d95982<br /><br />Ok, more consistent now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38075">issues.joomla.org/tracker/joomla-cms/38075</a>.</sub>

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on ed1aa328cbae9047fb87025b10bfe49b11d95982<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38075">issues.joomla.org/tracker/joomla-cms/38075</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38075">issues.joomla.org/tracker/joomla-cms/38075</a>.</sub>

**Comment by richard67** [comment]
Thanks all.

**Comment by richard67** [comment]
@roland-d @fancyFranci Ouch .. I just see that I should not have merged it because I was one of the testers ... but it's such a simple change that I think it should be ok.

**Pull request merged**
