### PR TITLE
[4.3] Migrate the extension finder plugin to services

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Migrate the extension finder plugin to services.

### Testing Instructions
Install an extension.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on e46b1ec43f6ce052e31f2f23fe310267ed919927<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39006">issues.joomla.org/tracker/joomla-cms/39006</a>.</sub>

**Comment by laoneo** [comment]
@heelc29 do you also have time to test this?

**Comment by heelc29** [comment]
Can you remove the two `require` -> file is empty

https://github.com/joomla/joomla-cms/blob/8208f270de1fb293e738609cf1889c0d963a3f63/plugins/extension/finder/src/Extension/Finder.php#L162
https://github.com/joomla/joomla-cms/blob/8208f270de1fb293e738609cf1889c0d963a3f63/plugins/extension/finder/src/Extension/Finder.php#L196

https://github.com/joomla/joomla-cms/blob/17ac356af50ed5bc20bd49102a71c1906dcf1742/administrator/components/com_finder/helpers/indexer/helper.php#L13-L18

Import is used
https://github.com/joomla/joomla-cms/blob/8208f270de1fb293e738609cf1889c0d963a3f63/plugins/extension/finder/src/Extension/Finder.php#L16

**Comment by laoneo** [comment]
Thanks for the hint @heelc29, removed it.

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 1b619e9cb37fa920ae90d2d18841599c255dd2af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39006">issues.joomla.org/tracker/joomla-cms/39006</a>.</sub>

**Comment by laoneo** [comment]
Setting RTC as only requires are removed which are pointing to an empty file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39006">issues.joomla.org/tracker/joomla-cms/39006</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo!

**Pull request merged**
