### PR TITLE
Update Fontawesome 5 to final version

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
update npm package for fontawesome to final version of 5.x family

### Testing Instructions
code review

### CODE REVIEW

**Comment by brianteeman** [comment]
There really must be an automated process for npm updates

**Comment by richard67** [comment]
@N6REJ Have you checked their changelog if there are any breaking changes? Or can we rely on their respect to semver so that a change of a minor version (2nd number) doesn't contain any B/C breaks?

Update: According to my experience they don't do breaking changes with minor versions, but I'm maybe too paranoid to rely on that ;-)

**Comment by N6REJ** [comment]
no, i didn't but I agree, I've never seen them have b/c issues mid major version.  
6 went public today and is now the default version but I didn't want to go that far on my own.

**Comment by richard67** [comment]
@N6REJ Not sure if code review alone is sufficient for testing, or if it would not be better to do a real test in addition, i.e. to apply the changes to the package.json and run npm to update the fontawesome package and then check at least here or there if icons still look fine.

**Comment by brianteeman** [comment]
I would check the changelog and then check if there is anything relevant there that impacts joomla

**Comment by richard67** [comment]
> I would check the changelog and then check if there is anything relevant there that impacts joomla

Agree. That's the minimum which has to be done.

**Comment by brianteeman** [comment]
This definitely can **not** be blindly updated as their are breaking changes that may or may not effect us
https://github.com/FortAwesome/Font-Awesome/releases

**Comment by N6REJ** [comment]
The changes don't seem to affect us.  I changed the \f9 's to \e0 's like indicated, ran npm ci to build the .min 's then verified the changes had been kept.
There was nothing to commit nor push.

**Comment by N6REJ** [comment]
@richard67 cant you write up the test or explain how they would apply the patch?

**Comment by N6REJ** [comment]
I've been asked to close this as @Hackwar has opened another https://github.com/joomla/joomla-cms/pull/30248

**Pull request closed without merging**
