### PR TITLE
[4.0] Favicons fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/31508 .

### Summary of Changes
Remove the hardcoded favicon from the templates manifests (atum + cassiopeia)

### Testing Instructions
Try to copy a template

### Actual result BEFORE applying this Pull Request
Missing favicon

### Expected result AFTER applying this Pull Request
All good, you successfully cloned the template

### Documentation Changes Required

A bit of documentation about the favicons:
- The actual files are in `media/system/images`
- Can be overridden by copying these files to `templates\templateName\images\favicon**.(svg|ico)`
- Any updates **will not affect your overrides** (a popular question in the forum)

Things to note about the svg files:
- the contents of the `joomla-favicon` can be replaced with any valid svg (the viewBox can be anything user defined)
- the contents of the `joomla-favicon-pinned` can be replaced with any valid svg **BUT the viewBox needs to remain `viewBox="0 0 16 16"`**
- The classic favicon.ico can be either 16x16 or 32x32

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7bbf37f7535b99c3129a72c7c6efa09adc70e8b9<br /><br />Applied patch and copied both templates successfully. Reviewed code too. Thanks for attending to this so promptly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31512">issues.joomla.org/tracker/joomla-cms/31512</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7bbf37f7535b99c3129a72c7c6efa09adc70e8b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31512">issues.joomla.org/tracker/joomla-cms/31512</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31512">issues.joomla.org/tracker/joomla-cms/31512</a>.</sub>

**Comment by richard67** [comment]
System test failure in Drone seems not to be related to this PR. It seems to be a problem with our testing environment.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
