### PR TITLE
Change `defined('JPATH_BASE') or die;` into `defined('_JEXEC') or die;` for all folders with the exception of layout folder

### PR DESCRIPTION
**Pull request by astridx**
# Summary of Changes
Because I think it is a bug i changed 
`defined('JPATH_BASE') or die;`
into
`defined('_JEXEC') or die;`

### Testing Instructions
Code review.

See https://github.com/joomla/joomla-cms/pull/28416 for layout folder

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 1b38b8d6ff5ee49b602c06878c0896271b769968<br /><br />very nice to have it everywhere the same <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28417">issues.joomla.org/tracker/joomla-cms/28417</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1b38b8d6ff5ee49b602c06878c0896271b769968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28417">issues.joomla.org/tracker/joomla-cms/28417</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28417">issues.joomla.org/tracker/joomla-cms/28417</a>.</sub>

**Comment by zero-24** [comment]
merging thanks @astridx

**Pull request merged**
