### PR TITLE
[4.0] Unused strings

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #20312

As @infograf768 pointed out these can never be used in the installer

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@brianteeman this is wrong. The strings are for the Form Field Password and are required for the javascript part that does the check against the requirements (for the installation I think we hardcoded some, but for the rest front end/backend are configurable via the com_user, might be wrong for the component here, have to actually check). So all and all these strings are part of the password form field, if the team that did the last update in the template removed that functionality then they might appear as useless but ARE NOT.

**Comment by dgrammatiko** [comment]
@brianteeman this is wrong. The strings are for the Form Field Password and are required for the javascript part that does the check against the requirements (for the installation I think we hardcoded some, but for the rest front end/backend are configurable via the com_user, might be wrong for the component here, have to actually check). So all and all these strings are part of the password form field, if the team that did the last update in the template removed that functionality then they might appear as useless but ARE NOT.

**Comment by brianteeman** [comment]
@dgrammatiko 
> (for the installation I think we hardcoded some, but for the rest front end/backend are configurable via the com_user, might be wrong for the component here, have to actually check).

Please do check because I couldnt see any

**Comment by dgrammatiko** [comment]
There few parts here:
- the password field at it's current state is not ok, needs https://github.com/joomla/joomla-cms/pull/23215
- This section https://github.com/joomla/joomla-cms/blob/b8bc589038a0f0fe0f5c03a2f167264e52d0b288/libraries/src/Form/Field/PasswordField.php#L163-L169 in the field controls the behaviour specifically for the installation, eg only thing we check is that the password cannot be less than 4 characters.
- The last update of the template had nothing changed regarding this, so if anyone got offended by this comment, I do apologise :(

**Comment by brianteeman** [comment]
That's my point - the strings are not being used in the installer

**Pull request closed without merging**
