### PR TITLE
PostgreSQL - sql error save category with tag

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

go to the category manager and create or edit a category  In the tags field create or add a tag then click  "Save".
#### Expected result

The category is saved with the  tag
#### Actual result

the tag field is cleared and the category is not saved
#### System information

PostgreSQL 9.3.5
Joomla 3.4.0
#### Additional comments

added a sanity check for NOT NULL FIELDS

### CODE REVIEW

**Comment by waader** [comment]
@alikon Please try the following test cases:

- Add a new (=ad hoc) tag to an existing or new category and save. That works.
- Repeat the above step: You get the following error: SQL=INSERT INTO sdfjk_contentitem_tag_map

mssql gives this error message:
23000 [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'core_xreference', table 'joomla34.dbo.ufv5y_ucm_content'; column does not allow nulls. INSERT fails.SQL=INSERT INTO [ufv5y_ucm_content] ([core_type_alias],[core_title],[core_alias],[core_body],[core_state],[core_access],[core_params],[core_metadata],[core_created_user_id],[core_created_time],[core_modified_time],[core_language],[core_content_item_id],[core_images],[core_urls],[core_hits],[core_version],[core_metakey],[core_metadesc],[core_catid],[core_type_id]) VALUES ('com_content.category','Joomla!','joomla','','1','1','{"category_layout":"","image":"","image_alt":""}','{"author":"","robots":""}','247','2011-01-01 00:00:00.000','2015-03-05 20:26:38','*','19','{}','{}','0','1','','','14','5')

**Comment by alikon** [comment]
retest with #6314

**Comment by brianteeman** [comment]
Issue confirmed
Tested with this PR an #6314
Issue resolved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6326">issues.joomla.org/joomla-cms/6326</a>.</sub>

**Comment by waader** [comment]
@test works fine! Thanks!

**Comment by zero-24** [comment]
RTC based on testing :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6326">issues.joomla.org/joomla-cms/6326</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @alikon! Merged.

**Pull request closed without merging**
