### PR TITLE
[4.0] Remove outdated comment

### PR DESCRIPTION
**Pull request by brianteeman**
Really no need to have this comment anymore

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 69ae4ce7c29c8eb5457490191f802d9ee53dc184<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19277">issues.joomla.org/tracker/joomla-cms/19277</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 69ae4ce7c29c8eb5457490191f802d9ee53dc184<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19277">issues.joomla.org/tracker/joomla-cms/19277</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
