### PR TITLE
[3.x] Trim extra spaces from download URL in com_installer and com_joomlaupdate

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Trim extra spaces from download URL as we do in other places in the installer already as it should be consisted. I have extended this PR to the new downloadsource tag too.

cc @astridx 

### Testing Instructions

Install this component: https://github.com/astridx/mod_agiframewrapper/releases/tag/v0.0.2
See it finds the update to 0.0.3
Notice that when you try to install it it gets an error (can't download the package)
apply the patch
try to apply the update again

### Expected result

Update works

### Actual result

Update errors with "Can't download package"

### Documentation Changes Required

None.

### More Information

The reason for that extra spaces is that here: https://github.com/astridx/mod_agiframewrapper/blob/v0.0.3/agiframewrapper-update.xml#L57-L63 there is a return an this gets into the variable.

### CODE REVIEW

**Comment by astridx** [comment]
I tested this successful. Thank you very much @zero-24 
erweiterungen aktualisieren test administration 1

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 0dced2c939a10fe65ab76a273beceface9cca588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23248">issues.joomla.org/tracker/joomla-cms/23248</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 0dced2c939a10fe65ab76a273beceface9cca588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23248">issues.joomla.org/tracker/joomla-cms/23248</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 0dced2c939a10fe65ab76a273beceface9cca588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23248">issues.joomla.org/tracker/joomla-cms/23248</a>.</sub>

**Comment by SharkyKZ** [comment]
Wouldn't it be better to fix the XML file instead?

**Comment by astridx** [comment]
@SharkyKZ 
You are right, one solution is to change the XML-Document. 
But: White space characters and line breaks are permitted in XML content (https://www.w3.org/TR/xml/#charsets). So the XML-Document is valid.

And others had my problem, too. For example here: https://www.kunena.org/forum/k-3-0-installation-and-upgrade/132397-illegal-characters-found-in-url

If you insert an url with containing white space in the address field of a browser, the browser trims it, too. 
Why should not we do this in Joomla Updater?

**Comment by SharkyKZ** [comment]
The part about XML validity is irrelevant. The content contains characters it should not contain. 3rd parties should fix their manifests.

If this is "fixed" in core, the same needs to be done literally where XML forms are used. All because of some 3rd parties who intentionally add garbage characters to their forms.

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 0dced2c939a10fe65ab76a273beceface9cca588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23248">issues.joomla.org/tracker/joomla-cms/23248</a>.</sub>

**Comment by 810** [comment]
rtc

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23248">issues.joomla.org/tracker/joomla-cms/23248</a>.</sub>

**Pull request merged**
