### PR TITLE
Admin menu - home menu item icons display.

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #17406 .

### Summary of Changes
Admin Menus:
Show language icons for menus which contain home menu items for a language. And home icon which contains global home page.

For details please refer to the mentioned issue #17406 

### Testing Instructions
Create menu items under different menus and set some menu items as default for different languages in each menu type.

### Expected result
Respective language flags should be displayed in admin menu "Menu" dropdown.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by izharaazmi** [comment]
@infograf768 Please test this one.

**Comment by brianteeman** [comment]
Why is this introducing a css file instead of using the images as before?

Its a little more complex as a result as if we add a language or flag then the css will need to be updated as well

**Comment by izharaazmi** [comment]
I am adding this to make it reusable at other places (core or custom
extensions) with a simple icon class instead of full IMG tag. That's why I
left it within the mod_languages context instead of adding in mod_menu.
Updating CSS should not be an issue IMHO.

**Comment by brianteeman** [comment]
for me that change is beyond the scope of this PR.

**Comment by izharaazmi** [comment]
@brianteeman Please have a look at this now. I have removed the CSS definitions and usage.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c7b935296cea84d8ad00574de15f26431713d3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17511">issues.joomla.org/tracker/joomla-cms/17511</a>.</sub>

**Comment by infograf768** [comment]
@izharaazmi 
Works fine here and I set my test OK.

I suggest to make another PR (or add in this one) to take care of the situation where, by mistake or db corruption, 2 or more Home pages exist in a single menuType.
This was taken care of previously when we had 
```
elseif ($menuType->home > 1)
		{
			$titleicon = ' <span>'
				. JHtml::_('image', 'mod_languages/icon-16-language.png', $menuType->home, array('title' => JText::_('MOD_MENU_HOME_MULTIPLE')), true)
				. '</span>';
		}
```
with the existing string
`MOD_MENU_HOME_MULTIPLE="Warning! Multiple homes!"`

To test this, create a multilang site as usual, define a flag/icon for a content language then in the db, set to home another menu item than the usual home for that language in the same menu type.
We will get correctly the generic icon in the menu. Here for German main menu:

screen shot 2017-08-13 at 08 37 51

But I think we should also display a warning in the Menu items Manager and modify the value of this lang string to include the name of the menutype with a sprintf.

Can do?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c7b935296cea84d8ad00574de15f26431713d3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17511">issues.joomla.org/tracker/joomla-cms/17511</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by izharaazmi** [comment]
@infograf768 It's already taken care of. Please let me know if it's failing.

**Comment by izharaazmi** [comment]
Though the warning is not displayed. We can do that in another PR.

**Comment by infograf768** [comment]
@izharaazmi 
Ok for another PR. :smiley:  This one can go in in the meanwhile. Thanks

**Pull request merged**
