### PR TITLE
[4.0] Password focus

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #28794

### Summary of Changes
Keep focus on the password field

### Testing Instructions
As this is a js change you will need to npm ci and make sure you clear the browser cache

Check the recordings below to see the changes

### Before
bits

### After
bits

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 566d41c4014a95ad58056c1a8313bd33c8fe4ec4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31775">issues.joomla.org/tracker/joomla-cms/31775</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 566d41c4014a95ad58056c1a8313bd33c8fe4ec4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31775">issues.joomla.org/tracker/joomla-cms/31775</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31775">issues.joomla.org/tracker/joomla-cms/31775</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
yeah my first JS merge

**Pull request merged**
