### PR TITLE
[4.0] codemirror fonts

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/25588 thanks @brianteeman 

### Summary of Changes

For some reasons this commit here: https://github.com/joomla/joomla-cms/commit/574bc4141acb51635192f5967669f0d749f0e02a#diff-6042b20d31889b87a9357432fef2ab1a has never been merged up to 4.0-dev this here adds it back 

### Testing Instructions

Make sure fonts are always loaded via https

### Expected result

fonts are always loaded via https

### Actual result

fonts are not always loaded via https

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 414c23cfb1900ae59759f0d090a710b69335502f<br /><br />Code review: PR does the same as PR #19488 did for staging, and it covers all fonts in `plugins/editors/codemirror/fonts.json` except of those which were already using https.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25593">issues.joomla.org/tracker/joomla-cms/25593</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 414c23cfb1900ae59759f0d090a710b69335502f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25593">issues.joomla.org/tracker/joomla-cms/25593</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
