### PR TITLE
Update Language.php in com_finder - Allow period before character in search (example search for: .net)

### PR DESCRIPTION
**Pull request by BrainforgeUK**
Allow period before letter characters (for example when searching for .net).

Pull Request for Issue #41338 .

### Summary of Changes

In tokenise() allow a period before letter characters.

### Testing Instructions

Create an article with the text
_I require a .net developer_
Then search for .net

### Actual result BEFORE applying this Pull Request

No match found.

### Expected result AFTER applying this Pull Request

Article added is found.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Please update the title to something that has some meaning

**Comment by BrainforgeUK** [comment]
Expanded title

**Comment by BrainforgeUK** [comment]
Should this be moved to 4.4 or 5?

**Comment by rachelwalraven** [comment]
I have tested this item :white_check_mark: successfully on 9ea78a0dea6c69c55d40ab3d90d7a577c54b1976<br /><br />With patch searches with a period before the word give the right result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41353">issues.joomla.org/tracker/joomla-cms/41353</a>.</sub>

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 9ea78a0dea6c69c55d40ab3d90d7a577c54b1976<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41353">issues.joomla.org/tracker/joomla-cms/41353</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41353">issues.joomla.org/tracker/joomla-cms/41353</a>.</sub>

**Comment by obuisard** [comment]
Thank you Jonathan @BrainforgeUK for the PR.
The release team decided to include it in the release.

**Pull request merged**
