### PR TITLE
[4.0] PHP 8 Ensure that we have a valid date

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review 

Symptoms:

Screenshot 2021-12-24 at 18 05 54

```
  <b>Deprecated</b>:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in <b>/tests/www/postgres/libraries/src/Date/Date.php</b> on line <b>126</b>
```

# Unit test before PR

I mean, the provided unit test in this PR, before the change the Date.php 

```
libraries/vendor/bin/phpunit tests/Unit/Libraries/Cms/Date/DateTest.php

PHPUnit 8.5.21 by Sebastian Bergmann and contributors.

..........PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /Users/phil/Sites/joomla-cms/libraries/src/Date/Date.php on line 126
.                                                       11 / 11 (100%)
Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /Users/phil/Sites/joomla-cms/libraries/src/Date/Date.php on line 126


Time: 34 ms, Memory: 10.00 MB

OK (11 tests, 33 assertions)
```

# Unit test after PR

```
libraries/vendor/bin/phpunit tests/Unit/Libraries/Cms/Date/DateTest.php


PHPUnit 8.5.21 by Sebastian Bergmann and contributors.

...........                                                       11 / 11 (100%)

Time: 52 ms, Memory: 10.00 MB

OK (11 tests, 33 assertions)
```

### CODE REVIEW

**Comment by PhilETaylor** [comment]
That awkward moment when you go to check the[ unit tests on a class](https://github.com/joomla/joomla-cms/blob/4ee06a1fc3222f1c09ad5db37ebfe87deb7d40a8/tests/Unit/Libraries/Cms/Date/DateTest.php), and the whole class is full of your exact birth date/time LMAO - I guess I wrote these unit tests then or else someone is trolling me geek time...

**Comment by brianteeman** [comment]
such a short memory. it was only march this year

**Comment by PhilETaylor** [comment]
Excuse me for forgetting which of the 3000+ contributions this year that was.. Ive probably slept since then
Screenshot 2021-12-24 at 18 13 52

**Comment by PhilETaylor** [comment]
Added a unit test that fails before PR and passes after PR

**Comment by PhilETaylor** [comment]
Drone failure is unrelated to this PR content

**Comment by PhilETaylor** [comment]
This overlaps https://github.com/joomla/joomla-cms/pull/36355 but Im leaving this open as it has a unit test which the other PR doesn't and that's better...

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4db98d759771136a9b369524de81234c4937cbd8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36396">issues.joomla.org/tracker/joomla-cms/36396</a>.</sub>

**Comment by PhilETaylor** [comment]
I have removed the Date.php changes in this PR and left the Unit Test only as the Date.php issue is fixed in https://github.com/joomla/joomla-cms/pull/36355

**Pull request closed without merging**
