### PR TITLE
[3] com_tags. Microdata. Add position to itemListElement LIs

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27349

### Summary of Changes
- Add itemprop `position` to LI elements.

### Testing Instructions
- Create a tag "Joomla".
- Add this tag to some articles.
- Create a menu item of type "Tagged Items":

- Go to https://search.google.com/structured-data/testing-tool
and test the new menu item/front-end link.

### Actual result
- position errors for ItemList.

- Apply patch and test again

### Expected result
- No position errors.

### CODE REVIEW

**Review by EJBJane — COMMENTED** [review]
If I apply this patch in the file default_items.php (at line 101) then I get another error and the original error is still there: "Duplicate values for itemListElement.url are not allowed."
Thanks for looking at this in any case, hope we get this straightened out.

**Review by EJBJane — COMMENTED** [review]
Sorry I am not sure if this was seen..

If I apply this patch in the file default_items.php (at line 101) then I get another error and the original error is still there: "Duplicate values for itemListElement.url are not allowed."
Thanks for looking at this in any case, hope we get this straightened out.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9c796fff81d1c0ba8451edf99f7f9e3216e31a2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27350">issues.joomla.org/tracker/joomla-cms/27350</a>.</sub>

**Comment by ReLater** [comment]
> If I apply this patch in the file default_items.php (at line 101) then I get another error and the original error is still there: "Duplicate values for itemListElement.url are not allowed."

@EJBJane 

I can't reproduce your find with core Joomla.
- Do you use an template override for file  components/com_tags/views/tag/tmpl/default_items.php ?
You should not for testing this pr.

- Did you follow the testing instructions exactly? Same menu item type and so on?
If not: What are the differences between your menu item and my screenshot above?

- Can you provide the link to your page where I can see the error?

**Comment by EJBJane** [comment]
I did have an override.. (very embarrassing sorry) 
Your patch absolutely did work!

**Comment by alikon** [comment]
maybe outside of the scope of this pr....
btw
i still get an error
Screenshot from 2019-12-28 10-12-16

**Comment by ChristineWk** [comment]
@alikon 
Tested yesterday after removing (temporary) my .htaccess (otherwise not possible) :-)
Just an idea: Code review shows:

`<li class="cat-list-row0 clearfix" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
													<h3 itemprop="name">
						<a href="/hstompers/index.php/testg" itemprop="url">
							TestG						</a>
					</h3>
`

your line is without /menue ?

`<a href="/index.php/" itemprop="url">`

**Comment by ReLater** [comment]
> Your patch absolutely did work!

@EJBJane 
Could you please mark your test as successfully on https://issues.joomla.org/tracker/joomla-cms/27350

**Comment by ReLater** [comment]
@alikon 

("Devi specificare un valore por il campo url" = "You must specify a value of the url field")

Your find is outside of the scope of this pr and I can't reproduce it. When I test a Tagged Items page that contains the following code (similiar to your snippet; same url "/index.php" for first item) I see no errors. 

```
<ul class="category list-striped" itemscope itemtype="http://schema.org/ItemList">
    <li class="cat-list-row0 clearfix" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
	   <h3 itemprop="name">
		  <a href="/index.php" itemprop="url">
			 00000 GHSVS Berlin Kreuzkölln
		  </a>
	   </h3>
	   <span class="tag-body" itemprop="description">
	   <p>Blah blah</p>
	   </span>
	   <meta itemprop="position" content="1">
    </li>
```

**Comment by ReLater** [comment]
TBH: If it wouldn't be a B\C break I would propose to remove at least the `ItemList` microdata from this view ;-)

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27350">issues.joomla.org/tracker/joomla-cms/27350</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by EJBJane** [comment]
I have tested this item :white_check_mark: successfully on 9c796fff81d1c0ba8451edf99f7f9e3216e31a2e<br /><br />I tested this and it worked for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27350">issues.joomla.org/tracker/joomla-cms/27350</a>.</sub>

**Comment by EJBJane** [comment]
> > Your patch absolutely did work!
> 
> @EJBJane
> Could you please mark your test as successfully on https://issues.joomla.org/tracker/joomla-cms/27350

Done! thanks

**Pull request merged**
