### PR TITLE
[com_config] Error?/Success? messages on save

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

In com_config when we get an error on save (ex: bad session token or no permission) we get a green (aka success) message.

This is a bad UX problem:
- Green messages are for success
- Blue messages are for information
- Yellow messages are for warnings
- Red messages are for errors or very importing stuff

This PR corrects that.
#### Testing Instructions

Code review, or, for instance:
1.  (browser Tab 1) Go to global config form, don't save
2.  (browser Tab 2) Open a new browser tab, go to backend, logout and login again
3. (browser Tab 1) Press "Save" or "Save and Close" in the global config to save.
4. You'll notice you get and invalid token message and the message is green and from a user perspective it's associated with action success.
 image
5. Apply patch, repeat process 1 to 3. Now the message is red.
 image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d7b3fdbb15feca337bb27df643a939c089ea05fb<br /><br />Good find<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10425">issues.joomla.org/joomla-cms/10425</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on d7b3fdbb15feca337bb27df643a939c089ea05fb<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10425">issues.joomla.org/joomla-cms/10425</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10425">issues.joomla.org/joomla-cms/10425</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @BurtNL thanks for testing!

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d7b3fdbb15feca337bb27df643a939c089ea05fb<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10425">issues.joomla.org/joomla-cms/10425</a>.</sub>

**Comment by richard67** [comment]
I was a bit late I just see :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10425">issues.joomla.org/joomla-cms/10425</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks @richard67 another test in always good :smile:

**Comment by brianteeman** [comment]
all tests always welcome

On 11 May 2016 at 17:51, Richard Fath <notifications@github.com> wrote:

> I was a bit late I just see [image: :smile:]
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10425
> <https://issues.joomla.org/tracker/joomla-cms/10425>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10425#issuecomment-218520186>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by richard67** [comment]
I will soon (in a few days) need testers for PR I am preparing, make utf8mb4 conversion use files with version numbers so not on every change all has to run, and make it handle extensions, too, so I am also working on a PR for weblinks to provide an example. Testers will be welcome, I'll let you know when my PR is ready.

**Pull request merged**
