### PR TITLE
[4.0] Comments typo

### PR DESCRIPTION
**Pull request by brianteeman**
Small typo in the doc block comments. Can be merged on review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6a1edf3f2874f01a733116d232b489f1f9ac31a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25091">issues.joomla.org/tracker/joomla-cms/25091</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fe5c4a7e9845ce3f6fd6eee83255136a9eba7c8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25091">issues.joomla.org/tracker/joomla-cms/25091</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25091">issues.joomla.org/tracker/joomla-cms/25091</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
