### PR TITLE
[plg_finder_categories]Code style

### PR DESCRIPTION
**Pull request by wojsmol**
### Summary of Changes

Code style changes forplg_finder_categories
### Testing Instructions

code review

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a8d3d140c823717f72bd7244f326ff598ea09354<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10488">issues.joomla.org/joomla-cms/10488</a>.</sub>

**Comment by wojsmol** [comment]
@JoomliC Please test this PR.

**Comment by JoomliC** [comment]
@wojsmol Even if it's valid in a php code, i think here, it uses Joomla library <code>__clone()</code> function to prevent fatal error, and will control to be sure we have an object : https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L1396

Would need confirmation from PLT, maybe @wilsonge could confirm ?

**Comment by mbabker** [comment]
`__clone()` is a [PHP magic method](http://php.net/manual/en/language.oop5.cloning.php) and the method you linked isn't being called in this case.  `clone $this` is a language construct in PHP, not a method call.

**Comment by JoomliC** [comment]
Thanks @mbabker !
So the change here is valid.

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on a8d3d140c823717f72bd7244f326ff598ea09354<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10488">issues.joomla.org/joomla-cms/10488</a>.</sub>

**Pull request merged**
