### PR TITLE
[4.1]Add form layout option to custom fields

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #36548.

### Summary of Changes
Makes the form layout for custom field configurable. Actually only for the following fields:
- list
- sql
- radio

Any suggestions for language strings?

### Testing Instructions
- Create a list custom field where multiple is set to yes
- Change the form layout to enhanced list in the options tab
- Edit an article

### Actual result BEFORE applying this Pull Request
The list is rendered with the default select HTML Element.

### Expected result AFTER applying this Pull Request
The list is rendered with the choices.js script.

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this small bug part of this pr?

radio

**Comment by brianteeman** [comment]
Otherwise everything looks great to me

**Comment by laoneo** [comment]
No, this looks like an init issue on the JS part which I didn't touch. But could also not reproduce the issue on my end.

**Comment by brianteeman** [comment]
ok

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5da3d2a109303a0930d383f5bc932d98df13fb94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36551">issues.joomla.org/tracker/joomla-cms/36551</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 5da3d2a109303a0930d383f5bc932d98df13fb94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36551">issues.joomla.org/tracker/joomla-cms/36551</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36551">issues.joomla.org/tracker/joomla-cms/36551</a>.</sub>

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on 5da3d2a109303a0930d383f5bc932d98df13fb94<br /><br />Beautiful!!! Thanks so much, and also for including the radio layout!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36551">issues.joomla.org/tracker/joomla-cms/36551</a>.</sub>

**Comment by crystalenka** [comment]
I reproduced part of Brian's issue. It's because the layout expects the values to be in the order of No - Yes; if they are flipped, it doesn't respect that. I'm wondering if there is any way to detect the values of 0/1 or true/false or yes/no and make it a bit 'smarter'? I'm not sure this is something that would prevent merging the PR, but wanted to clarify the bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36551">issues.joomla.org/tracker/joomla-cms/36551</a>.</sub>

**Comment by laoneo** [comment]
Thanks for clarification. When the order mathers, then we need to mention this in the docs.

If this should be handled on the code side, then I would do it in another pr.

**Comment by bembelimen** [comment]
Thx

**Comment by laoneo** [comment]
Can you guys also test #36553 which does the same for the color field.

**Comment by AndySDH** [comment]
@laoneo I just ran into this and I noticed this is the wrong placement for this setting.

The "Options" tab is dedicated to global settings that are shared by all field types. It's not the place to add type-specific settings.

Options tied to specific types of fields should be added in the first "General" tab. This is what has always been done for all field types and field settings.

So this new "Form Layout" should be moved under the "General" tab for all the fields in which you added it. For example, under the "Multiple" setting:

image

But: **Do we even need this setting at all?**

I would argue: do we really need a setting? The other "raw" layout is ugly and unusable. I don't think anyone will ever want to use it.

The new one it's just better, and it's similar to what he had in J3.

I personally would just implement the "enhanced select" by default, and get rid of the other layout altogether. Like we had in J3. What do you think?

**Comment by laoneo** [comment]
Please open a new issue, so it can be discussed properly as this pr is closed.

**Pull request merged**
