### PR TITLE
Less support

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Add support for less stylesheets. This is implemented in such a way that you can just use `JHtml::_('stylesheet', 'path/to/stylesheet.less')` and your 'less' stylesheet will be used in debug mode and `less.js` will be loaded. If not in debug mode, Joomla will look for `.min.css` or `.css` in the same directory and use whichever one it finds. `$document->addStylesheet()` also works but does not automatically load `less.js`  or search for precompiled/minified css files. 

So, for testing:
1) Create a less stylesheet somwhere and a precompiled/minified/appropriately named css file in the same directory.
2) Add `JHtml::_('stylesheet', 'path/to/stylesheet.less')` to your code somewhere. 
3) Check what's being loaded when debug mode is on and when it is off. 

You should expect that your less stylesheet will be loaded when debug is on and less.js should also be loaded. When debug mode is off, you should see that the `.min.css` or `.css` version is loaded (`.min.css` should take precedence over `.css`).

### CODE REVIEW

**Comment by Hackwar** [comment]
just an FYI: You can't use JDEBUG alone. JDEBUG is not defined if debugging is not enabled, so it would throw notices. You can only check like ```defined('JDEBUG')```.

**Comment by okonomiyaki3000** [comment]
@Hackwar I don't think that's true actually. If you look in `includes/framework.php`, it's being defined as whatever `$config->debug` is whether or not `$config->debug` is true. But, for several reasons, it seems like there's never a case where it's not better to check the global config instead of `JDEBUG`. Is there any reason to keep this constant around? Maybe its use should be deprecated.

**Comment by Hackwar** [comment]
@okonomiyaki3000 yes, I was false at that time. JDEBUG is actually set to the value in global config. JDEBUG is a valid constant, since you might have apps that don't define this in the configuration file in this way. Besides that, it is a lot quicker than looking it up in the app configuration all the time. :wink:

**Comment by mbabker** [comment]
In a more proper structure, a lot of code wouldn't have direct access to the app config like we enable today via JFactory.  Views, layout files, and modules would all fall into this.  So the constant isn't so bad.

**Comment by okonomiyaki3000** [comment]
I really like it for convenience but it creates a problem for testing. If you have a function that needs to be tested with and without debug enabled, you can't do that if it uses the constant unless you run the test twice with different settings each time.

**Comment by mbabker** [comment]
Testability and constants never really go well together when the constants can change behavior (in which case, it isn't really all that constant).  Definitely something that needs addressed long term.

**Comment by okonomiyaki3000** [comment]
I guess this should have the `new feature` label, right?

**Comment by Bakual** [comment]
Done ;)

**Comment by brianteeman** [comment]
Under the licence terms of the added javascript file the licence file must be included 
> It requires you to:
Include a copy of the license in any redistribution you may make that includes Less.js
Provide clear attribution to The Less Core Team for any distributions that include Less.js

In addition it is licensed as Apache 2 which is not compatible with GPL2 http://www.gnu.org/licenses/license-list.en.html#apache2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5267">issues.joomla.org/joomla-cms/5267</a>.</sub>

**Comment by ggppdk** [comment]
What about instead of instead of loading less.js,
if .less extension is detected:

we use:
```
$less = new JLess();
$less->checkedCompile(...);
```

because JLess extends lessc, which has:
```
	// compile only if changed input has changed or output doesn't exist
	public function checkedCompile($in, $out) {
		if (!is_file($out) || filemtime($in) > filemtime($out)) {
			$this->compileFile($in, $out);
			return true;
		}
		return false;
	}
```

**Comment by brianteeman** [comment]
That defeats the objective (I assume)of this PR which is to be able to test
a less stylesheet before compiling it

On 18 December 2015 at 09:31, Georgios Papadakis <notifications@github.com>
wrote:

> What about instead of instead of loading less.js,
> if .less extension is detected:
>
> we use:
>
> $less = new JLess();
> $less->checkedCompile(...);
>
> because JLess extends lessc, which has:
>
>     // compile only if changed input has changed or output doesn't exist
>     public function checkedCompile($in, $out) {
>         if (!is_file($out) || filemtime($in) > filemtime($out)) {
>             $this->compileFile($in, $out);
>             return true;
>         }
>         return false;
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5267#issuecomment-165724890>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment]
@brianteeman
Right, i missed that

**Comment by ggppdk** [comment]
then to avoid modifying the current CSS files,

it could create the compiled CSS files inside 
- /tmp folder, 
- or in subfolder /test/ inside the given path

**Comment by brianteeman** [comment]
Personally I see no need for this functionality in the core

**Comment by okonomiyaki3000** [comment]
I think I'll look into how less support could be provided via a plugin but it will still require some parts of Joomla to be a bit more flexible if it's to work as I think it should.

**Comment by brianteeman** [comment]
Can I close this here?

On 18 December 2015 at 10:59, Elijah Madden <notifications@github.com>
wrote:

> I think I'll look into how less support could be provided via a plugin but
> it will still require some parts of Joomla to be a bit more flexible if
> it's to work as I think it should.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5267#issuecomment-165748561>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by okonomiyaki3000** [comment]
Sure, why not?

**Pull request closed without merging**
