### PR TITLE
changed readme file

### PR DESCRIPTION
**Pull request by jagatheeswar**
Pull Request for Issue # .

### CODE REVIEW

**Comment by PhilETaylor** [comment]
This looks like #hacktoberfest spam haha

**Comment by brianteeman** [comment]
Gsoc spam

**Comment by jagatheeswar** [comment]
> This looks like #hacktoberfest spam and its not even october haha

i am a newbee, is there any mistake in my pull request. can u say if there is any.

**Comment by richard67** [comment]
> i am a newbee, is there any mistake in my pull request. can u say if there is any.

@jagatheeswar Several mistakes:

1. When you create a new pull request (PR), you will see that there are head lines like "Summary of Changes", "Testing Instructions" and so on. They are not there for nothing, they are there so that the creator of the PR can add the corresponding information below them.
For such a small PR it would not really need other testing instructions than "Code review", but at least those it would need.
Furthermore your PR should at least tell about why you do that change in the readme file.

2. The change in the readme file provided by this PR is no no value. It doesn't really add new information.
The readme is intended to give a brief overview and summary on all you need to know to get started with Joomla.
Anything which makes that file longer needs a good reason.

3. The GSoC projects focus on the next mayor version 4 of Joomla, which here belongs to the 4.0-dev branch, but this PR is for the current version 3, i.e. the staging branch.

Thanks you for your contribution. At least you could see how the workflow is to make a new PR. I hope you are not disappointed when I close it now.

The next one will be better 😄 .

It can happen also to experienced contributors like me that a PR is wrong, so all is fine.

**Comment by PhilETaylor** [comment]
> This looks like #hacktoberfest spam and its not even October haha

Im sorry, I had assumed this was automated spam, and not a genuine attempt to contribute. 

This repo has had a lot of "newbie" injection in the last 2 weeks, and has a long history of spam from individuals trying to get a free Hacktoberfest T-Shirt with spam PRs

https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/

My reply should have been more like Richards. Sorry.

**Comment by jagatheeswar** [comment]
> > i am a newbee, is there any mistake in my pull request. can u say if there is any.
> 
> @jagatheeswar Several mistakes:
> 
> 1. When you create a new pull request (PR), you will see that there are head lines like "Summary of Changes", "Testing Instructions" and so on. They are not there for nothing, they are there so that the creator of the PR can add the corresponding information below them.
>    For such a small PR it would not really need other testing instructions than "Code review", but at least those it would need.
>    Furthermore your PR should at least tell about why you do that change in the readme file.
> 2. The change in the readme file provided by this PR is no no value. It doesn't really add new information.
>    The readme is intended to give a brief overview and summary on all you need to know to get started with Joomla.
>    Anything which makes that file longer needs a good reason.
> 3. The GSoC projects focus on the next mayor version 4 of Joomla, which here belongs to the 4.0-dev branch, but this PR is for the current version 3, i.e. the staging branch.
> 
> Thanks you for your contribution. At least you could see how the workflow is to make a new PR. I hope you are not disappointed when I close it now.
> 
> The next one will be better 😄 .
> 
> It can happen also to experienced contributors like me that a PR is wrong, so all is fine.

thank you for your information sir. i studied git on my own and tried. i just did for a practice sir. i will correct my mistake as i learn. thanks for ur feedback sir.

**Pull request closed without merging**
