### PR TITLE
Remove submitted values from data if field is disabled

### PR DESCRIPTION
**Pull request by degobbis**
Pull Request for Issue #25652 .

### Testing Instructions
see #25628

### CODE REVIEW

**Comment by gogicomputers** [comment]
I have tested this item :white_check_mark: successfully on 4bb2e3a39a59229c8cf67e6704b530d0e447d6ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25682">issues.joomla.org/tracker/joomla-cms/25682</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4bb2e3a39a59229c8cf67e6704b530d0e447d6ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25682">issues.joomla.org/tracker/joomla-cms/25682</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25682">issues.joomla.org/tracker/joomla-cms/25682</a>.</sub>

**Comment by HLeithner** [comment]
@laoneo can you have a look at this because i'm not quite confident with this.

**Comment by laoneo** [comment]
Me neither, pretty sure this will introduce a regression.

**Comment by degobbis** [comment]
@laoneo Could you please describe in more detail why this would introduce a regression?
The only problem I still see are disabled fields which are also required, but we already have the problem and I can take care of that in a next step.

**Comment by degobbis** [comment]
@laoneo @HLeithner I have restored the previous state, as I do not really fully understand when a default value is needed. The only adjustment now concerns what, according to the description, anyway should not be. 
If the field is disabled, and the browser still sends data, then I will delete it again.
I hope now there should be no reason to hold back the fix.

**Comment by laoneo** [comment]
@degobbis can't say exactly what, it is just so a feeling. It took a couple of iterations till we were on a stable state with all these readonly, disabled states and access level settings including the passed array. What I can remember is that we had issues with values not being present in the data array as they were needed to clear values, etc.

**Comment by degobbis** [comment]
@laoneo However, we are currently receiving an error message because the values from disabled fields are still sent. With my fix, I'm only making sure that the described procedure of the Bowser is actually executed. Either way, the same result.

**Comment by degobbis** [comment]
@gogicomputers @viocassel Could You please test my changes again?

**Comment by d4shoerncheN** [comment]
I have tested this item :white_check_mark: successfully on 174136cd6a56ce88b6cdb6d6313358b8fcbe9d20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25682">issues.joomla.org/tracker/joomla-cms/25682</a>.</sub>

**Comment by gogicomputers** [comment]
I have tested this item :white_check_mark: successfully on 174136cd6a56ce88b6cdb6d6313358b8fcbe9d20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25682">issues.joomla.org/tracker/joomla-cms/25682</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

Thanks for tests.

**Comment by HLeithner** [comment]
thx

**Pull request merged**
