### PR TITLE
[5.1] Redundant else usage

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove redundant ELSE usage.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Complex code.

### Expected result AFTER applying this Pull Request

Simple code.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Wrong branch

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da378aa2a8ad0e03c30295fbb6b8a5cf4286bfc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41983">issues.joomla.org/tracker/joomla-cms/41983</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on da378aa2a8ad0e03c30295fbb6b8a5cf4286bfc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41983">issues.joomla.org/tracker/joomla-cms/41983</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41983">issues.joomla.org/tracker/joomla-cms/41983</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by Quy** [comment]
@Denitz Please fix [phpcs](https://ci.joomla.org/joomla/joomla-cms/71111/1/7).

**Comment by Denitz** [comment]
@Quy Done.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
