### PR TITLE
Mozilla cacert update via Github Action

### PR DESCRIPTION
**Pull request by wilsonge**
For staging as we won't use mozilla update the cacerts by using a github action once a month. This should mean we're never shipping with multiple years out of date files again. This should be fine as Mozilla's website notes:

> We don't mind you downloading the PEM file from us in an automated fashion, but please don't do it more often than once per day. It is only updated once every few months anyway.

See https://github.com/wilsonge/joomla-cms/runs/2980634936?check_suite_focus=true for sample job output

### CODE REVIEW

**Comment by richard67** [comment]
Is there a way to test this on a modified branch where we have an outdated cert file so the auto commit has something to commit?

**Comment by zero-24** [comment]
I dont want anything to auto commit to stuff 3.10-dev can we update this to create a PR similiar to the translation PR?

**Comment by wilsonge** [comment]
Should be done but I don't have any easy way to test anymore :(

**Comment by zero-24** [comment]
How could it be tested? Would merging it in help it to be tested? I have been told you can manually trigger gh actions too?

Btw it seems no user data has been added here can that be correct or is a default user from github used in that case?

**Comment by wilsonge** [comment]
> Btw it seems no user data has been added here can that be correct or is a default user from github used in that case?

GitHub Actions have an auto-generated token that can be used for Pull Requests to the same repository

> How could it be tested? Would merging it in help it to be tested? I have been told you can manually trigger gh actions too?

Yes once merge we can manually trigger and debug.

**Comment by zero-24** [comment]
> GitHub Actions have an auto-generated token that can be used for Pull Requests to the same repository

Cool :)

> Yes once merge we can manually trigger and debug.

Merged ;)

**Pull request merged**
