### PR TITLE
Remove unused meaningless strings

### PR DESCRIPTION
**Pull request by brianteeman**
As discussed here #14555 these strings are completely meaningless for translators

As confirmed by @infograf768 https://github.com/joomla/joomla-cms/issues/14555#issuecomment-290676871 they can be safely removed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6753500370130dd7619c836230a2fc2183f65295<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18202">issues.joomla.org/tracker/joomla-cms/18202</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6753500370130dd7619c836230a2fc2183f65295<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18202">issues.joomla.org/tracker/joomla-cms/18202</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
