### PR TITLE
[5.0] Replaces the dependency for model state with a State object

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Replaces the state holder for model with an array based class. It removes the dependency for the deprecated `CMSObject` class.

Like that he performance can be improved by a third against using the `CMSObject` class.

### Testing Instructions
- Create an article in the back end with the state published
- Filter for trashed articles

### Actual result BEFORE applying this Pull Request
No article is shown.

### Expected result AFTER applying this Pull Request
No article is shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/78 and https://github.com/joomla/Manual/pull/77
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on a9aa13d8632208abdc169bbacf6e8de4b1aae917<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39024">issues.joomla.org/tracker/joomla-cms/39024</a>.</sub>

**Comment by wilsonge** [comment]
Is there a reason not to use Registry? Given it has similar methods as JObject for b/c purposes but also implements arrayAccess as an interface which could be situationally useful

**Comment by laoneo** [comment]
I tried to use registry but it doesn't support field access. So it would be a hard BC break. It is also massive slower than CMSObject or this new State class.

**Comment by Fedik** [comment]
Registry have some benefits also. In future you probably will be need serialisation, cloning.
Can try extend ModelState from Registry, and implement magick `get/set`.

Performance issue can overcome by disabling `$separator`, and make it always "flattened".
But that probably require changes in Registry class itself. 
Much more work.

**Comment by laoneo** [comment]
But then I would rather extend the registry class with the magic methods and not introduce a new class at all.

**Comment by HLeithner** [comment]
> But then I would rather extend the registry class with the magic methods and not introduce a new class at all.

This would be against the argumentation in https://github.com/joomla-framework/registry/pull/58

**Comment by laoneo** [comment]
I made an alternative which is using the registry in #39663.

**Comment by laoneo** [comment]
Closing in favor of #39663. When https://github.com/joomla-framework/registry/pull/66 got merged, then we have the same speed without a new class which does more or less the same as the registry.

**Pull request closed without merging**
