### PR TITLE
[4.0] UserGroupsHelper prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements and cleans up queries in `Joomla\CMS\Helper\UserGroupsHelper`.

### Testing Instructions

Simple queries, code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ad2054c61dad47308d48156bca609417af2d956d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26030">issues.joomla.org/tracker/joomla-cms/26030</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ad2054c61dad47308d48156bca609417af2d956d<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26030">issues.joomla.org/tracker/joomla-cms/26030</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
