### PR TITLE
[plugin][recaptcha] - detect correct IP address

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #22636 .

### Summary of Changes

detect correct IP address using
forked `FOFUtilsIp::getIp()` with joomla-framework/utilities#22 to `IpHelper::getIp()`

### Testing Instructions
apply #22673 before
see #22636

### CODE REVIEW

**Comment by zero-24** [comment]
Another comment like this: I would suggest to fork the fof method into some joomla API / lib (with mention the source) so we are not going to introduce another dependency on the deprecated / old FOF code.

**Comment by alikon** [comment]
@zero-24  see https://github.com/joomla-framework/utilities/pull/22

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/commit/5153c8344548aba6946ba2cbb0d3c9f99098f934 has committed the bump on the Utilities package, so this is now testable against current staging if you patch the modified files.

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 64bc9a8536879be9124f2ceb8ffa048b6fe4ad05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22672">issues.joomla.org/tracker/joomla-cms/22672</a>.</sub>

**Pull request merged**
