### PR TITLE
Fix appveyor builds and bump driver dll version

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue fix/update appveyor config .

### Summary of Changes
- bump sqlsrv driver dll version
  - https://pecl.php.net/package-changelog.php?package=pdo_sqlsrv
  - https://pecl.php.net/package-changelog.php?package=sqlsrv

Implement a workaround to the appveyor resource download issue. This fixes the Appveyor builds

### Testing Instructions
review only, appveyor tests run

### Expected result
appveyor tests run

### Actual result
appveyor tests run

### Documentation Changes Required
none

### CODE REVIEW

**Comment by wilsonge** [comment]
Doesn't feel like this worked :)

**Comment by photodude** [comment]
Ya it appears there is something deeper that's wrong here. Not sure if the issue in appveyor, or in the URL's for downloads of some resources, or in Chocolatey, or in some other thing.

**Comment by photodude** [comment]
So the underlying issue here is in the `appveyor DownloadFile` command. I've contacted appveyor and they are looking into what went wrong. There is an ugly workaround, but hopefully they can fix the issue in their `appveyor DownloadFile` command.

**Comment by photodude** [comment]
@mbabker @wilsonge @zero-24 @rdeutz (and anyone else)

bump for merge consideration, this now has the workaround to fix the issue with the appveyor builds

**Pull request merged**
