### PR TITLE
[4.0][com_content] Remove getAuthors()

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This removes code deprecated in #22288.

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by laoneo** [comment]
For consistency, can we deprecate the getAuthors function in 3 too?

**Comment by SharkyKZ** [comment]
It was already deprecated in #22288.

**Comment by laoneo** [comment]
Ah sorry missed that.

**Comment by laoneo** [comment]
I'v tested it and the getAuthors function is still used. It is possible to filter the articles in the back end per author.

**Comment by laoneo** [comment]
I have tested this item :red_circle: unsuccessfully on e0b5a86ebff0657dd96e6a1deed8102294eea7df

I'v tested it and the getAuthors function is still used. It is possible to filter the articles in the back end per author.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22401">issues.joomla.org/tracker/joomla-cms/22401</a>.</sub>

**Comment by SharkyKZ** [comment]
@laoneo this is expected. Author filter is now provided by `AuthorField`. `getAuthors()` was used before we had Search Tools.

**Comment by laoneo** [comment]
But it is still used in J4. So we can't remove something which crashes on purpose.

**Comment by SharkyKZ** [comment]
@laoneo It's not used. Filter form uses `AuthorField`.

**Comment by laoneo** [comment]
I was on the wrong branch. Works ok

**Pull request merged**
