### PR TITLE
[4] fix Notice: Only variables should be passed by reference

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

Test case: https://3v4l.org/OQacn

```php
<?php
$command = ['one'=>1,"two"=>2,"three"=>3];
$keys = array_keys($command);

// Raises a notice
var_dump(array_pop(array_keys($command)));

echo "\n\n\n\n";

var_dump(array_pop($keys));
```

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 80ad3ae981f4825dc49da5f55896e601bc1f27f7<br /><br />Tested successfully in Beta7-dev of 16 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32052">issues.joomla.org/tracker/joomla-cms/32052</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 80ad3ae981f4825dc49da5f55896e601bc1f27f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32052">issues.joomla.org/tracker/joomla-cms/32052</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32052">issues.joomla.org/tracker/joomla-cms/32052</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
