### PR TITLE
remove extra Tinymce code

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # 9339.
#### Summary of Changes

Remove duplicated code icon
#### Testing Instructions

Check in the advanced AND extended modes of tinmyce and you will see two code icons. One after the image icon and one at the very end

This PR removes the second instance

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 15a4c811ab0652f692663efaf33c01684c0ca852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :red_circle: unsuccessfully on 15a4c811ab0652f692663efaf33c01684c0ca852<br /><br />The PR solves the issue for extended funcionality, but in this way in Advanced funcionality there is no more <> button.
If you change just the line 890, then you'll have the expected result.
I would suggest not to put the code button at the end, but in the middle, in this way

toolbar1: \"$toolbar1 | code | $toolbar5 \", <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 15a4c811ab0652f692663efaf33c01684c0ca852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on 655d7fa06ad25ba530496d1a752ca7889b51919d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 655d7fa06ad25ba530496d1a752ca7889b51919d<br /><br />Tested in both advanced and extended mode that in both cases there is 1 icon "<>" for source code insert shown after the icon for image insert.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9341">issues.joomla.org/joomla-cms/9341</a>.</sub>

**Comment by wilsonge** [comment]
Thanks Brian!

**Pull request merged**
