### PR TITLE
[plg_system_logout] Load language files only when needed

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11714 (part 3).
### Summary of Changes

Only load the plg_system_logout language file when they are needed.

For more info see https://github.com/joomla/joomla-cms/issues/11714
#### Reproduce
- Use latest staging
- Enable plugin system logout (if not yet)
- Enable debug and debug lang in global config
- Enable debug system plugin with all options activated
- Go to frontend and check the debug console
- Notice `JROOT/administrator/language/en-GB/en-GB.plg_system_logout.ini` is loaded no matter what page you are (even in backend pages they are loaded).

image
#### Test patch
- Apply patch
- Repeat the steps above and check the language file is NOT loaded (except when needed). 
- Check plugin work as before if language files are required to load (ex: add `JError::raiseError(403, 'test');` after https://github.com/joomla/joomla-cms/pull/11736/files#diff-0bd8e36ff5e9b432eb9c55d94266d786R43 and them logout).
### Documentation Changes Required

None.
### Notes

This also solves a PHP warning when handling error on logout
`Warning: Parameter 1 to PlgSystemLogout::handleError() expected to be a reference, value given in /path/to/joomla-staging/libraries/legacy/error/error.php on line 781`

@mbabker please check this one also. Maybe this could be done without JError...

### CODE REVIEW

**Comment by dgt41** [comment]
@andrepereiradasilva can you fix the CS:
```
FILE: /home/travis/build/joomla/joomla-cms/plugins/system/logout/logout.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 90 | ERROR | Usage of "$this" in static methods will cause runtime errors
```

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 0652138486dc167fe593c1b43cd12a2462890e92<br /><br />On frontend and backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11736">issues.joomla.org/joomla-cms/11736</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 0652138486dc167fe593c1b43cd12a2462890e92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11736">issues.joomla.org/joomla-cms/11736</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this successfully.
Please find attached snapscreen shot 2016-09-14 at 00 34 15screen shot 2016-09-14 at 00 34 43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11736">issues.joomla.org/joomla-cms/11736</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11736">issues.joomla.org/joomla-cms/11736</a>.</sub>

**Pull request merged**
