### PR TITLE
[4.0] Fix useless red class when unpublishing Content Language

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says. That class has not been used for ages.

### Testing Instructions
Create a content language. Unpublish it.
EDIT: small change in message to be more clear in English.

Can be merged on review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am fine with removing the unused class but you have also changed the string. So the message has changed and it no longer makes sense in English.

**Comment by infograf768** [comment]
a site language that `also has to be` was wrong. I used `should have` which may not be good english but reflects the real sense.
`should have an assigned` ? `should be assigned a` ?
Better suggestion?

**Comment by brianteeman** [comment]
Your original comment says there is no change in the message

**Comment by infograf768** [comment]
yes, i forgot.
please, for once, be positive.

**Comment by brianteeman** [comment]
I'm not sure what you mean by "also has to be" is wrong so its hard to be exact but if I have guessed correctly then it should be 
"should have an assigned "

As its a definitive statement - ie it wont work if you dont do this then it would be better to use the word "must"

"must have an assigned"

**Comment by infograf768** [comment]
English corrected

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7f0c570b30ce40255dc446d6b184e88fcfdd4c58<br /><br />Updated language strings look good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29431">issues.joomla.org/tracker/joomla-cms/29431</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7f0c570b30ce40255dc446d6b184e88fcfdd4c58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29431">issues.joomla.org/tracker/joomla-cms/29431</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29431">issues.joomla.org/tracker/joomla-cms/29431</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
