### PR TITLE
[a11y]Language Installer

### PR DESCRIPTION
**Pull request by brianteeman**
Remove the orphaned label

This looks like a copy paste error from other components

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 41d23a90bae61726dfec97e7730749ce51dc67dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15913">issues.joomla.org/tracker/joomla-cms/15913</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Quy have you test by Code review or can this be test by non-Technical?

**Comment by brianteeman** [comment]
@franz-wohlkoenig compare the generated html before and after the pr
before there is a label and after there is no label
there should be no label because it has nothing to describe

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 41d23a90bae61726dfec97e7730749ce51dc67dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15913">issues.joomla.org/tracker/joomla-cms/15913</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
