### PR TITLE
[5.2] Rename update SQL scripts 5.2.1-2024-09-24.sql to 5.2.2-2024-09-24.sql

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

The update SQL scripts "5.2.0-2024-09-24.sql" which were added with PR #44133 and renamed to "5.2.1-2024-09-24.sql" with PR #44388 were not included in the 5.2.1 release as that was a fix release for only the file permissions.

Therefore these files should be renamed again to "5.2.2-2024-09-24.sql".

This PR here does that now.

### Testing Instructions

Code review, and check if the files "5.2.1-2024-09-24.sql" can be found in a 5.2.1 installation or update package.

### Actual result BEFORE applying this Pull Request

Update SQL scripts are named "5.2.1-2024-09-24.sql" but can't be found in a 5.2.1.

### Expected result AFTER applying this Pull Request

Update SQL scripts are named "5.2.2-2024-09-24.sql".

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 716c196758851b955c160fb95ab2e64d4b6a7458<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44467">issues.joomla.org/tracker/joomla-cms/44467</a>.</sub>

**Comment by richard67** [comment]
It can be that this PR comes too late because the 5.2-dev branch is already closed for merging because 5.2.2 is already in preparation.

In this case this PR should not be merged but be closed after the 5.2.2 release.

The wrong file names fixed here are not a technical but only an esthetic problem.

I will leave this PR here open just in case the branch gets unlocked for other reasons so it could be merged.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 716c196758851b955c160fb95ab2e64d4b6a7458<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44467">issues.joomla.org/tracker/joomla-cms/44467</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44467">issues.joomla.org/tracker/joomla-cms/44467</a>.</sub>

**Comment by richard67** [comment]
@Hackwar @pe7er This PR here should only be merged if the 5.2-dev branch will be unlocked because some other urgent fix will be merged before 5.2.2 stable or an RC is released.

If that doesn’t happen and 5.2.2 stable or a 5.2.2-rc1 is released based on the current 5.2-dev branch without this PR, then this PR should be closed without merging because we should not rename Update SQL scripts when they have been shipped already with a release if that is not really necessary, and here it is not really necessary. The update SQL script will also run with the current name when updating to 5.2.2. This PR only makes the file name more correct regarding the version part.

If that is too complicated for the release workflow, I am also ok with closing this PR now and leave things as they are.

**Pull request merged**
