### PR TITLE
[4.0] SCSS Tweaks

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #17817

### Summary of Changes

This PR adds a max width to the `.custom-select` class, and also fixes the grid issue on the Global Config

### Testing Instructions

1. Select boxes should not overlap the parent element and should be the same width as input fields
2. The global config settings UI should be the same as before. `Site Settings` on the left and `SEO Settings` on the right

### CODE REVIEW

**Comment by brianteeman** [comment]
screen shot 2017-12-30 at 13 50 29

As you can see in the screenshot the width is now corrected but there is no border on the right or bottom only on the top on left<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19229">issues.joomla.org/tracker/joomla-cms/19229</a>.</sub>

**Comment by C-Lodder** [comment]
Fine for me on FF.

Can you check the Bootstrap demo site and use the inspector to add a long option?

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c6010de8fb3400bb2bba52fb45ba86a67ce8c040

bildschirmfoto 2017-12-30 um 15 15 30

### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19229">issues.joomla.org/tracker/joomla-cms/19229</a>.</sub>

**Comment by brianteeman** [comment]
Works fine on the getbootstrap site
Its not just the dropdowns with a long value it is all of them on chrome

**Comment by ciar4n** [comment]
Seems to be fine on Windows Chrome (63.0)...

image

**Comment by wilsonge** [comment]
I'm also good in Chrome. I'm going to merge this for now so Charlie doesn't get years of conflicts. Brian if you're still getting this could you sit down and screenshare with charlie so he can debug because it doesn't seem like any of the rest of us can reproduce your issue :/

**Comment by brianteeman** [comment]
@wilsonge was that chrome on mac or windows? My test was windows

**Comment by wilsonge** [comment]
Mine was a mac. Ciaran was windows, so I think both bases got covered

**Pull request merged**
