### PR TITLE
[4.0] Fix Drag'n'Drop a parent-category show children-categories only after page-refresh

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #34389 .

### Summary of Changes
Move the children after the order is changed

### Testing Instructions
Apply patch, run `npm install` and please follow #34389

### Documentation Changes Required
none

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Fedik is this also replacing #34520 ?

**Comment by Fedik** [comment]
hmhm, nope, it separated :)

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on ba784c0a7729c673dd4a079815e20283a94148ae<br /><br />Tested success with categories and menu items. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34584">issues.joomla.org/tracker/joomla-cms/34584</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on ba784c0a7729c673dd4a079815e20283a94148ae<br /><br />Verified the bug and the fix! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34584">issues.joomla.org/tracker/joomla-cms/34584</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34584">issues.joomla.org/tracker/joomla-cms/34584</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
