### PR TITLE
[4.0] [libraries] Add check for real null datetimes to CoreContent table class

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This is a follow up to recently merged PR's which changed datetime columns in database for real null values.

Because core content (table `ucm_content`) shall be usable not only for core components', the checks for the old (preudo-)null datetimes are kept and just extended by the check for real null values.

Like for several other components, the table class for core content swaps publish up and down times if they are given and the down time is earlier than the up time. This is not a good thing in my opinion but to change that is outside the scope of this PR.

The check for the condition when to swap is extecned by the check for real null values.

### Testing Instructions

Code review should be sufficient: Make sure that in the file modified by this PR there are no other places where old (preudo-)null datetimes are checked without checking for real null values, too.

### Expected result

No check of published up and down time for old (preudo-)null datetimes without checking for real null values, too.

### Actual result

Check for null values is missing.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d2b0bc8555660d5a0dc3a00ce85f66ca0c9060f4<br /><br />LGTM
code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26781">issues.joomla.org/tracker/joomla-cms/26781</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d2b0bc8555660d5a0dc3a00ce85f66ca0c9060f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26781">issues.joomla.org/tracker/joomla-cms/26781</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26781">issues.joomla.org/tracker/joomla-cms/26781</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks to all testers and mergers (there are so many of the latter 😄 ).

**Pull request merged**
