### PR TITLE
[4.3] Fix the mobile footer of the source modal

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/39871 .

### Summary of Changes

- Remove the `position: absolute`

### Testing Instructions

Follow the issue instructions

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kaushik1216** [comment]
I have tested this item white_check_mark successfully on 7dcca2e

**Comment by N6REJ** [comment]
I have tested this item :red_circle: unsuccessfully on 7dcca2e49221516302805a86720a184018cc2920<br /><br />I still see the same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39873">issues.joomla.org/tracker/joomla-cms/39873</a>.</sub>

**Comment by N6REJ** [comment]
retested with DL'd pr release
and it worked fine, so probably something wrong with patchtester
image

**Comment by dgrammatiko** [comment]
@Kaushik1216 could you mark your test here: https://issues.joomla.org/tracker/joomla-cms/39873
Thanks

**Comment by Kaushik1216** [comment]
I have tested this item :white_check_mark: successfully on 7dcca2e49221516302805a86720a184018cc2920<br /><br />I have tested this item Successfuly: 7dcca2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39873">issues.joomla.org/tracker/joomla-cms/39873</a>.</sub>

**Comment by laoneo** [comment]
@N6REJ can you mark your test as successful?

**Comment by dgrammatiko** [comment]
@laoneo the issue tracker has 2 successful tests

**Comment by laoneo** [comment]
Which one is the second test? I see only the ones from @Kaushik1216.

**Comment by dgrammatiko** [comment]
I think the issue tracker comment was deleted but the tracker has 2 entries 
Screenshot 2023-02-17 at 17 29 35

**Comment by laoneo** [comment]
I was thinking the same, but just to be sure it would be good when @N6REJ can do a second test so we are on the safe side.

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko !

**Comment by N6REJ** [comment]
I did "alter test" and mark it successful and it says it did but its not changing here... I did the same thing yesterday

**Pull request merged**
