### PR TITLE
postgresql fix regression Implement ACL to backend menus #9814

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9814 .
#### Summary of Changes

managed the new field on postgresql
#### Testing Instructions

install with sample testing data

postgresql fix Implement ACL to backend menus #9814
introduce a new field asset_id but not correctly managed in sample_testing data file

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
doesn't it need it to be done in all sample data files?

**Comment by alikon** [comment]
we are made in the same i'm closing mine

**Comment by andrepereiradasilva** [comment]
no no i didn't mess with the asset_id column
i just added the other columns

See https://github.com/joomla/joomla-cms/pull/10321/files

**Comment by andrepereiradasilva** [comment]
but it seems it solved the issue

**Pull request closed without merging**
