### PR TITLE
Regression - adding language image on com_categories

### PR DESCRIPTION
**Pull request by alikon**
##### how to reproduce

with current staging on postgresql
play with com_categories from backend 
##### Actual result

categoriesfix
##### comment

just another Wrong `group by`

### CODE REVIEW

**Comment by infograf768** [comment]
Any reason to not do as for l.title, i.e. use l.image ?

Otherwise, this has no unwanted effect on mysql.

**Comment by andrepereiradasilva** [comment]
@alikon this was added in https://github.com/joomla/joomla-cms/commit/e8b9c74eca4275f1b0ade28551aa804239a5196a

Can you check the other views work fine in postgresql?

**Comment by alikon** [comment]
@infograf768 
changed,
no reason even if should be the same cause of `ALIAS`
@andrepereiradasilva 
found on com_modules  #9185

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9f018cee96ff823a74a8e59eaa9d657920316a9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9173">issues.joomla.org/joomla-cms/9173</a>.</sub>

**Comment by brianteeman** [comment]
Simple change RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9173">issues.joomla.org/joomla-cms/9173</a>.</sub>

**Pull request merged**
