### PR TITLE
[4.0] Further protection (requires PHP 5.6+) about an session timing attack

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This is an further protection (requires PHP 5.6+) about the session timing attack implemented in Joomla 3.8.8

This issue is now moved to the public tracker thanks for the work done on this by:
@demis-palma
@wilsonge 
@SniperSister
@mbabker
@PhilETaylor 

### Testing Instructions

- apply the patch
- login the backend
- make sure the ajax call checking for Joomla Updates still works as expected.

### Expected result

Everything works and session is aborted

### Actual result

In some very very rare cases session is not aborted.

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Get session from application please. `Joomla\CMS\Factory::getSession()` is deprecated.

**Comment by zero-24** [comment]
Ok ready for testing now. George just corrected the call and I removed the now useless use call :)

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on a0fed8a65c06499d555847b4d2fcfea5747b9bb0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24317">issues.joomla.org/tracker/joomla-cms/24317</a>.</sub>

**Comment by zero-24** [comment]
Can we get one more test here please? cc @wilsonge @SniperSister

**Comment by zero-24** [comment]
Would be great when we can get one more tester so we can include this patch in 4.0. :)

**Comment by zero-24** [comment]
Can we find anyhow an tester on this one?

**Comment by wilsonge** [comment]
I'm merging this so that it gets extra testing.

**Pull request merged**
