### PR TITLE
Supported font formats mismatch

### PR DESCRIPTION
**Pull request by brianteeman**
The default values in the xml include woff2
The default value in the db does not include woff2

The default values on a new install should match those in the component xml and this PR corrects that.

We can't fix it on update as that would be changing user data.

To test either code review or do a clean install from the provided build

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 428c6306eb963f0d577e08e223073eee4ee14d24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38465">issues.joomla.org/tracker/joomla-cms/38465</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 428c6306eb963f0d577e08e223073eee4ee14d24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38465">issues.joomla.org/tracker/joomla-cms/38465</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38465">issues.joomla.org/tracker/joomla-cms/38465</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
