### PR TITLE
[4] Cleanup of restore.php - Remove redundant constructor

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 8f86fa54fcf804706b7f48b1c74dd0e3a463f9cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35292">issues.joomla.org/tracker/joomla-cms/35292</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8f86fa54fcf804706b7f48b1c74dd0e3a463f9cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35292">issues.joomla.org/tracker/joomla-cms/35292</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35292">issues.joomla.org/tracker/joomla-cms/35292</a>.</sub>

**Comment by PhilETaylor** [comment]
This broke things. Sorry.

#35331

**Pull request merged**
