### PR TITLE
[4.0] Replace atum/Service/HTML/Atum.php with CSS equivalent

### PR DESCRIPTION
**Pull request by ciar4n**
### Summary of Changes
Currently, we use a PHP helper to set variants for admin color variables. This PR removes that requirement and uses CSS instead.

### Testing Instructions
Apply PR, compile SCSS and check administration looks the same. Ensure color selectors in admin template style settings still function.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 70958d8d8c46693c4a0e574ecf9ffeb84826975a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32492">issues.joomla.org/tracker/joomla-cms/32492</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :red_circle: unsuccessfully on 728034532f6d113ad5f2f9cf68188ce8ee10aa52<br /><br />There is something wrong for me: in Colour Settings, above the Hue bar it says 'Unable to convert HSL value' and the bar is completely white. And the background is white rather than grey-blue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32492">issues.joomla.org/tracker/joomla-cms/32492</a>.</sub>

**Comment by dgrammatiko** [comment]
> There is something wrong for me

This needs composer/npm install or downloading the package from the github page. Were you trying to test this with patch tester? (it will never work you need to recompile the SCSS files)

**Comment by ceford** [comment]
> > There is something wrong for me
> 
> This needs composer/npm install or downloading the package from the github page. Were you trying to test this with patch tester? (it will never work you need to recompile the SCSS files)

I installed patch and then npm ci - I looked at the diff and that seemed enough for testing.

**Comment by chmst** [comment]
Testing the branch directly, win10, firefox. After composer install  / npm ci, the dashboard has white icons in quickicons

grafik icons are white

**Comment by ciar4n** [comment]
Is this issue present if you open the template style settings and save?

**Comment by chmst** [comment]
After setting the values again this is ok. Then I have the same situation as ceford with the hue values, no colour bar is visible and the message "Unable to convert HSL value" occurs after save. 

grafik

**Comment by ciar4n** [comment]
It seems to color field in hue format does not allow the saving of the number defined in the input, only the hex or hsl code of the color it represents?

**Comment by ciar4n** [comment]
@chmst @ceford Hopefully ok now 🙏 

Thank you @dgrammatiko

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 07260ed125ab5b2b24543e3b564789d9640ff46d<br /><br />Nice one @ciar4n <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32492">issues.joomla.org/tracker/joomla-cms/32492</a>.</sub>

**Comment by ceford** [comment]
The colour bar now does contain a colour background but the Home dashboard icons are missing without hover; and some of the Templates: Styles (Administrator) Toolbar buttons disappear on hover. So I guess I can't test this properly with Patchtester + npm ci.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32492">issues.joomla.org/tracker/joomla-cms/32492</a>.</sub>

**Comment by brianteeman** [comment]
image

image

image

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 07260ed125ab5b2b24543e3b564789d9640ff46d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32492">issues.joomla.org/tracker/joomla-cms/32492</a>.</sub>

**Comment by dgrammatiko** [comment]
@brianteeman I think you need to save the template style once as there are no defaults in the XML (might be wrong, its been some time since I tested this)

**Comment by brianteeman** [comment]
@dgrammatiko yes thats it. So the PR works but is incomplete

**Comment by dgrammatiko** [comment]
FWIW the fallbacks are wrong, should be:
```php

$wa->usePreset('template.atum.' . ($this->direction === 'rtl' ? 'rtl' : 'ltr'))
  ->useStyle('template.active.language')
  ->useStyle('template.user')
  ->addInlineStyle(':root {
     --hue: ' . $matches[1] . ';
     --atum-bg-light: ' . $this->params->get('bg-light', '#f0f4fb') . ';
     --atum-text-dark: ' . $this->params->get('text-dark', '#495057') . ';
     --atum-text-light: ' . $this->params->get('text-light', '#fff') . ';
     --atum-link-color: ' . $this->params->get('link-color', '#2a69b8') . ';
     --atum-special-color: ' . $this->params->get('special-color', '#001b4c') . ';
     --atum-sidebar-link-color: ' . $this->params->get('sidebar-link-color', '#132f53') . ';
  }');
```

@ciar4n can you update the PR?

**Comment by ciar4n** [comment]
Im gonna close this for now as I'm working on another pr with this applied. If it doesnt get merged I will re-open this.

**Pull request closed without merging**
