### PR TITLE
[4.0] [passwordstrength.js] Migrate es5 code to es6

### PR DESCRIPTION
**Pull request by moeinio**
### Summary of Changes

Migrated passwordstrength.js to es6

### Testing Instructions
run npm install
test Joomla core functionality like
* javascript translations
* check error messages creation in forms / ajax forms
* check webcomponents loaded correctly
* when registering a new user or adding new user in backend, check if the password strength criteria matches Password options set in Users: Password Options.

### Expected result
Passwordstrength should work same as before

### Actual result

Passwordstrength works same as before

### CODE REVIEW

**Comment by HLeithner** [comment]
@C-Lodder or @dgrammatiko can you have a look at this?

**Comment by mbabker** [comment]
Isn't this a third party script?  Or is the doc block at the top of the source file just a lie?

**Comment by HLeithner** [comment]
Only the first strength calculation of the file, https://github.com/joomla/joomla-cms/blob/5a95313e9d6cb0d0028c8f69ad2dc1f0ade7ce55/build/media_source/system/js/fields/passwordstrength.es5.js

The rest seams to be Joomla related.

@moeinio please add the correct header and add a note that the class has been converted to es6 by the joomla project.
Similar to this Commit: https://github.com/joomla/joomla-cms/pull/26300/commits/ddc7ea0606fd3e1f0ab22dc2af54dcd6309682ff#diff-4dcabad787cfa22ffb12e6dcede3da2aR40-R41

**Comment by dgrammatiko** [comment]
@HLeithner since you’ve asked, here is my answer: NO. This field, as the rest ones (that depend on js) **need to be custom elements**. Actually the code already exists here: 
https://github.com/joomla/joomla-cms/pull/23215

**Comment by brianteeman** [comment]
And since it's being looked at this should not exist at all as it is not a test of password strength by any measure.

**Comment by dgrammatiko** [comment]
Actually it does what it was supposed to do: connect the front end validation to the defined values in the php world

**Comment by brianteeman** [comment]
but nothing to do with password strength

**Comment by dgrammatiko** [comment]
Maybe you should blame me for naming this script `passwordstrength` when in j3 it was named progressbar: https://github.com/joomla/joomla-cms/blob/staging/media/system/js/progressbar-uncompressed.js

In fact if you really want to do this differently you’re gonna need to break quite a lot APIs

**Comment by mbabker** [comment]
> add a note that the class has been converted to es6 by the joomla project

I wouldn't even do that because at that point you've forked the script for the novelty of converting ES5 source to ES6.  Put it in a separate file that doesn't get touched by the project, third party scripts should not be getting altered by Joomla without damn good reason.

**Comment by HLeithner** [comment]
If you look at upstream you can see that this is already a work because upstream is coffee script.
Splitting the code in 2 files make sense see my pr https://github.com/joomla/joomla-cms/commit/ddc7ea0606fd3e1f0ab22dc2af54dcd6309682ff

**Comment by Quy** [comment]
Replaced by PR #29041

**Pull request closed without merging**
