### PR TITLE
HTML5 pattern in validate.js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/12857 .

### Summary of Changes
HTML5 NATIVE validation is done through `pattern="something"`
The validate.js is adjusted so if pattern tag exists will take precedence else we fall back to the rules

### Testing Instructions
- try adding any of the patterns to a text, email, etc field and see if this works
- use http://html5pattern.com/Names for reference

Add `pattern="[a-zA-Z]+"` after https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L13
Create a new article and try to submit without a title or with title as 87587676 (or anything apart english alphabet letters)

screen shot 2016-12-05 at 16 35 31

@Fedik @ggppdk @mbabker

---
This change is [Reviewable](https://reviewable.io/reviews/joomla/joomla-cms/13094)

### CODE REVIEW

**Review by ralain — COMMENTED** [review]
Pretty sure it's not going to work with a regex literal. You might try something like this, instead:

`isValid = new RegExp($el.attr('pattern')).test($el.val());`

**Comment by Fedik** [comment]
works good 👍 
but I think better to change  as @ralain sugested

**Comment by ralain** [comment]
Looked into this further and as I suspected you can't use a variable in a JavaScript regex literal. The variable itself (not its value) becomes the pattern.

Also, html5 pattern and JS regex are not fully compatible, but it's fixed easily by adding start and end of string, like so:

`isValid = new RegExp('^'+$el.attr('pattern')+'$').test($el.val());`

**Comment by dgt41** [comment]
@Fedik @ralain I've pushed the suggested code

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 73c97f8521f8a5a8d6ac8bcb76e634c4668b08c9<br /><br />HTML5 pattern and JS validation match up perfectly, now. Thanks for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13094">issues.joomla.org/tracker/joomla-cms/13094</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 73c97f8521f8a5a8d6ac8bcb76e634c4668b08c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13094">issues.joomla.org/tracker/joomla-cms/13094</a>.</sub>

**Comment by gptforjoomla** [comment]
Hi, this pull has a problem with unrequired inputs. test: a field that is not required but has pattern to be a number or other . when user not enter value for this input and submit, validation say that field is not correct

**Comment by ghost** [comment]
@minijoomla is this similar to #18591?

**Pull request merged**
