### PR TITLE
[5.2] Other JS improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

1. Convert site template JS to ES6
2. Remove `[].slice.call()` calls where possible.
3. Other minor improvements

### Testing Instructions

1. Ensure the front-end MetisMenu is working properly.
2. Code review @dgrammatiko @Fedik

### CODE REVIEW

**Comment by HLeithner** [comment]
@dgrammatiko @Fedik can you have a look?

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 559efc8f34defed37c9b2bff2121aea272a250ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42798">issues.joomla.org/tracker/joomla-cms/42798</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 559efc8f34defed37c9b2bff2121aea272a250ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42798">issues.joomla.org/tracker/joomla-cms/42798</a>.</sub>

**Comment by richard67** [comment]
@C-Lodder I've allowed myself to solve the conflict in file `build/media_source/system/js/inlinehelp.es6.js` which was caused by your other PR #42726 having been merged up meanwhile. I hope I've done it all right.

**Comment by richard67** [comment]
RTC as the previous human tests are still valid. The commit which invalidated the test count was just a branch update with a small easy conflict which I've resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42798">issues.joomla.org/tracker/joomla-cms/42798</a>.</sub>

**Comment by C-Lodder** [comment]
Thanks @richard67

**Comment by pe7er** [comment]
Thanks @C-Lodder !

**Pull request merged**
