### PR TITLE
Fix HTML markup

### PR DESCRIPTION
**Pull request by Quy**
Please enter somme description

### CODE REVIEW

**Comment by bertmert** [comment]
# test instructions
- BE > Go to module manager
- Open a module, e.g. a new one of type "Articles - Archived"
- Inspect HTML source code of page
- - Search for `data-position-element`. You'll see a white space after it.
```
data-position-element ="com_modules.module_0"
```
- - Search for `value=""size`. You'll see NO white space after `value=""` in calendar fileds.

- Apply patch. Check again.

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 894a22b52321301a3867faf110bdc1a6b29d3cc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14552">issues.joomla.org/tracker/joomla-cms/14552</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 894a22b52321301a3867faf110bdc1a6b29d3cc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14552">issues.joomla.org/tracker/joomla-cms/14552</a>.</sub>

**Comment by dgt41** [comment]
My bad, I guess

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14552">issues.joomla.org/tracker/joomla-cms/14552</a>.</sub>

**Comment by wilsonge** [comment]
Thanks @Quy !

**Pull request merged**
