### PR TITLE
[4.0] Fix markup in Privacy Dashboard

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix mismatched closing tag. See opening tag in line 37.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1a21e81e09c3b6bd909715eb4a9bbce02160dc16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33827">issues.joomla.org/tracker/joomla-cms/33827</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1a21e81e09c3b6bd909715eb4a9bbce02160dc16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33827">issues.joomla.org/tracker/joomla-cms/33827</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33827">issues.joomla.org/tracker/joomla-cms/33827</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
