### PR TITLE
[4.2] Missing Folder message

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38866.

### Summary of Changes
Adds a meaningful error message (and alpha-sorts the messages)

### Testing Instructions
Create anew directory in the root of your web space
In the filesystem local plugin add the new directory as a source
Verify that the directory is displayed in the media manager.
Delete the directory from the computer
Reload the media manager

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by brianteeman** [comment]
updated branch to retrigger drone

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 986b1ca1dc7802d03416c37057fc0e6d639713d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38867">issues.joomla.org/tracker/joomla-cms/38867</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 986b1ca1dc7802d03416c37057fc0e6d639713d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38867">issues.joomla.org/tracker/joomla-cms/38867</a>.</sub>

**Comment by Fedik** [comment]
R
2
C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38867">issues.joomla.org/tracker/joomla-cms/38867</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
