### PR TITLE
[5.0] Update TinyMCE to 6.7.2

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Updating TinyMCE to 6.7.2 to fix a mXSS vulnerability, see:
https://github.com/tinymce/tinymce/security/advisories/GHSA-v65r-p3vv-jjfv

### Testing Instructions
Apply patch, run npm install to download the updated Tiny version, test the editor.

```

6.7.2 - 2023-10-25
Fixed
The function getModifierState did not work on events passed through the editor as expected.

Indenting or outdenting a list item that contained non list item siblings after it would result in those siblings being removed.

Removed use of async for editor rendering which caused visual blinking when reloading the editor in-place.

Toggling a list that contained a list item element — <li> — which, in turn, contained another list item element as its first child, removed other content within the first list item element.

6.7.1 - 2023-10-19
Fixed
Specific HTML content caused mXSS when using undo/redo.

Specific HTML content caused mXSS when using the getContent and setContent APIs with the format: 'raw' option, which also affected the resetContent API and the draft restoration feature of the Autosave plugin.

Notification messages containing HTML were not properly XSS sanitized before being displayed.
```

### CODE REVIEW

**Comment by HLeithner** [comment]
I was confused why you set as minimum 6.7.1 when you say to upgrade to 6.7.2, but found out that the issue is fixed in 6.7.1

**Review by dgrammatiko — APPROVED** [review]

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on a81ed2095a986e59c805856af402c994bb8ce1d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42240">issues.joomla.org/tracker/joomla-cms/42240</a>.</sub>

**Comment by heelc29** [comment]
Plugin manifest version should be updated too.

**Comment by SniperSister** [comment]
Good catch @heelc29 , done!

**Comment by brianteeman** [comment]
Usually we post the changelog in the first post to help testers especially as in this case we are jumping two releases.

.7.2 - 2023-10-25
Fixed
The function getModifierState did not work on events passed through the editor as expected.

Indenting or outdenting a list item that contained non list item siblings after it would result in those siblings being removed.

Removed use of async for editor rendering which caused visual blinking when reloading the editor in-place.

Toggling a list that contained a list item element — <li> — which, in turn, contained another list item element as its first child, removed other content within the first list item element.

6.7.1 - 2023-10-19
Fixed
Specific HTML content caused mXSS when using undo/redo.

Specific HTML content caused mXSS when using the getContent and setContent APIs with the format: 'raw' option, which also affected the resetContent API and the draft restoration feature of the Autosave plugin.

Notification messages containing HTML were not properly XSS sanitized before being displayed.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on cb295dc7721135caff9a2076361bac09c12faf93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42240">issues.joomla.org/tracker/joomla-cms/42240</a>.</sub>

**Comment by Fedik** [comment]
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42240">issues.joomla.org/tracker/joomla-cms/42240</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
