### PR TITLE
[4.0] Correcting mutilingual sampledata plugin

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Correcting typo introduced in https://github.com/joomla/joomla-cms/pull/24025
Also normalizing params compared to a new Content List All Categories menu item

### Testing Instructions
Install a clean 4.0 site.
When installing, also install one of the possible languages (French, German DE, Persian)
In Control panel, click the module to install the Multilingual sample data
Then in the specific language Main menu, edit the List All Categories menu item

### Before patch
```
An error has occurred.

    0 Error decoding JSON data: Syntax error 
```

### After patch
Issue solved

Can be tested with patchtester.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cd34ccb95bc52a2ed5882ccef19446f613255508<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25223">issues.joomla.org/tracker/joomla-cms/25223</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cd34ccb95bc52a2ed5882ccef19446f613255508<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25223">issues.joomla.org/tracker/joomla-cms/25223</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25223">issues.joomla.org/tracker/joomla-cms/25223</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
