### PR TITLE
[5.0] LICENSE.txt

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

set correct license information in header (see also #40400 or #41277 for reference)

### Testing Instructions

code review

### CODE REVIEW

**Comment by heelc29** [comment]
> why were these changes not in an upmerge? its a waste of your valuable time to do this

@brianteeman do you mean the other PR #41422?

The "error-pages" (`templates/system/build_incomplete.html`, `templates/system/fatal-error.html`, `templates/system/incompatible.html`) are generated/updated by the translation-bot in PR for translation update (eg. #41137)
https://github.com/joomla/joomla-cms/blob/79572828c54272adee9ae0851a88d02b3c4eb0ca/.github/workflows/create-translation-pull-request-v4.yml#L60

and this is (at the moment) only available for 4.3-dev.
https://github.com/joomla/joomla-cms/blob/79572828c54272adee9ae0851a88d02b3c4eb0ca/.github/workflows/create-translation-pull-request-v4.yml#L76-L77

So only the 3 files were updated in 4.3-dev (and upmerged).

The 4th file is only available in 5.0-dev (added with #40509) and do not exist in prior versions (no upmerge possible)
https://github.com/joomla/joomla-cms/blob/fbdd32b4f0e9e167fa30a952bc79454e8811ca37/build/build-modules-js/settings.json#L804

The solutions would be

- run `npm ci` in the upmerge PR
- or create an second/new workflow for translation update v5 (if crowdin is ready)

to to this automatically...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e7c4629bdf54f3336bd0e6f964f9b50fbd922bcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41423">issues.joomla.org/tracker/joomla-cms/41423</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e7c4629bdf54f3336bd0e6f964f9b50fbd922bcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41423">issues.joomla.org/tracker/joomla-cms/41423</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41423">issues.joomla.org/tracker/joomla-cms/41423</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
