### PR TITLE
[4.2] Remove mocking XMLReader as it's bad practice. Fix parsing version

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Fixes tests to run on PHP 8.1. Generally we shouldn't be mocking core PHP classes so this fixes:

- Everywhere we mocked and then didn't even mock any values/return types etc. Just insert a real dummy instance
- The one place we did test was mocking versions. Here however this covered up a bug because when turning to concrete tests it turned out we parsed the XML version in the XML doc type rather than the version of the feed being used :D This bug is fixed as part of this and one extra test case in atom added

### Testing Instructions
Check Drone 8.1 tests

### Actual result BEFORE applying this Pull Request
All tests related to feed do not pass

### Expected result AFTER applying this Pull Request
All tests related to feed do pass (note session tests do fail - but that will be the subject of a different PR)

### Documentation Changes Required
None

### CODE REVIEW

**Review by rdeutz — APPROVED** [review]
looks good to me

**Review by HLeithner — APPROVED** [review]
Looks good to me but I think needs real tests for our RSS feed.

**Comment by wilsonge** [comment]
Agreed but probably outside the scope of this PR

**Comment by HLeithner** [comment]
I mean a really test in an installed cms to merge this PR ;) not only codereview

**Comment by wilsonge** [comment]
Screenshot 2022-06-19 at 21 35 22
Screenshot 2022-06-19 at 21 35 17

Took a 3rd party one in too for good measure

**Review by Hackwar — APPROVED** [review]

**Comment by HLeithner** [comment]
Thanks

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
