### PR TITLE
[4.0] Cassiopea: Correcting positions translation

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Correct Cassiopea language file to fit positions

### Testing Instructions
Choose a position for a site module
Position is now translated correctly

### CODE REVIEW

**Comment by SharkyKZ** [comment]
If you change positions in the XML file, you also need to change them everywhere else (installation SQL, sample data plugins, etc.).

**Comment by infograf768** [comment]
Not sure about that. Will check, but my feeling is that it is the value of the position which is used in these cases.
If not, I will modify this PR and change the constants in the lang file.

**Comment by infograf768** [comment]
Ok, will modify the lang constants instead

**Comment by infograf768** [comment]
@SharkyKZ 
Done.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8f452cdf8f206e98d14e517fa7997189695690ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27278">issues.joomla.org/tracker/joomla-cms/27278</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on ad3d8b2dc596024af4a67f139a83372b389cf197<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27278">issues.joomla.org/tracker/joomla-cms/27278</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27278">issues.joomla.org/tracker/joomla-cms/27278</a>.</sub>

**Pull request merged**
