### PR TITLE
[com_fields] Automatic Display of Custom Fields.

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for #15204

Original Report
We have the options "After Title", "Before Display","After Display" and "No". Translating this into Dutch I do think it is better to use "Not" instead of "No". I am not native English, but in Dutch it is better. Because of the use of JNO as string I don't have the option to change it in the Dutch translation.

This PR changes it from No to Do not automatically display and it is also a new string so that the dutch can translate it correctly

### CODE REVIEW

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on f2c9b832db7c6ddcf6a59a2d73d55edde043f3ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17607">issues.joomla.org/tracker/joomla-cms/17607</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f2c9b832db7c6ddcf6a59a2d73d55edde043f3ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17607">issues.joomla.org/tracker/joomla-cms/17607</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
