### PR TITLE
[plg_user] - delete messages when onUserAfterDelete()

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #12883 .

### Summary of Changes
delete items from #__messages table  when a user is deleted

### Testing Instructions
follow https://github.com/joomla/joomla-cms/issues/12883#issue-188994577

### CODE REVIEW

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on a61a5db820f8ceb95fcad78b1e13f30d17313a02<br /><br />I have tested this and it works as expected, tested deleting normal users and publisher with messages pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13052">issues.joomla.org/tracker/joomla-cms/13052</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on a61a5db820f8ceb95fcad78b1e13f30d17313a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13052">issues.joomla.org/tracker/joomla-cms/13052</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13052">issues.joomla.org/tracker/joomla-cms/13052</a>.</sub>

**Comment by tonypartridge** [comment]
Just a side thought.... should we clean up articles and set userid to the
deleting user also?

**Comment by zero-24** [comment]
Thanks 👍

**Pull request merged**
