### PR TITLE
[4.0] MenuHelper::getList() doesn't cache menu items

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

`MenuHelper::getList()` doesn't cache menu items because `$key` variable is overwritten in `foreach` block.

### Testing Instructions

Enable Joomla caching, log in, load any page with cached menu module.

### Actual result BEFORE applying this Pull Request

See that menu items cache file is regenerated on each page load.

### Expected result AFTER applying this Pull Request

Menu items cache file stays same.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Denitz** [comment]
Can somebody restart AppVeyor?

**Comment by rdeutz** [comment]
Restarted, good find.

**Comment by simbus82** [comment]
I don't understand :-) but it is my limit.
Why is this solved only renaming $key to $cachekey?

**Comment by rdeutz** [comment]
> Why is this solved only renaming $key to $cachekey?

There is an foreach in-between that uses $key, you have to view the whole file and not only the change

**Comment by simbus82** [comment]
> > Why is this solved only renaming $key to $cachekey?
> 
> There is an foreach in-between that uses $key, you have to view the whole file and not only the change

Ah, thanks! I found it!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 56a658e5ce9e11b81ac657698ecaaac5f6387bab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35703">issues.joomla.org/tracker/joomla-cms/35703</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 56a658e5ce9e11b81ac657698ecaaac5f6387bab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35703">issues.joomla.org/tracker/joomla-cms/35703</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35703">issues.joomla.org/tracker/joomla-cms/35703</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
