### PR TITLE
replace https://resources.joomla.org 

### PR DESCRIPTION
**Pull request by PhilETaylor**
replace https://resources.joomla.org with https://community.joomla.org/service-providers-directory/

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bc59afad04b9f41c049307412dc7ad34c3f9dc0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32907">issues.joomla.org/tracker/joomla-cms/32907</a>.</sub>

**Comment by zero-24** [comment]
@PhilETaylor Do you want to extend the replacement to the other places the link is used? https://github.com/joomla/joomla-cms/search?q=resources.joomla.org

**Comment by PhilETaylor** [comment]
Also going to remove 

`<li><a href="http://astore.amazon.com/joomlabooks04f-20">Books</a></li>` 

as that URL is dead too.

**Comment by PhilETaylor** [comment]
Done.

**Comment by brianteeman** [comment]
Shouldnt we ask to make sure that resources.j.o is a permanent removal or not?

**Comment by PhilETaylor** [comment]
I would not know who to ask... haha

**Comment by PhilETaylor** [comment]
Maybe they moved it to get away from the bad press of "the data breach" as that's mostly all I find when I google `joomla resources directory`

**Comment by zero-24** [comment]
> Shouldnt we ask to make sure that resources.j.o is a permanent removal or not?

From my understanding it is but @conconnl might can offically confirm that?

**Review by zero-24 — APPROVED** [review]

**Comment by zero-24** [comment]
> Also going to remove 
> 
> `<li><a href="http://astore.amazon.com/joomlabooks04f-20">Books</a></li>` 
> 
> as that URL is dead too.

Oh yeah that book store :-D

**Comment by conconnl** [comment]
The site doesn't exist anymore, only the domain does to handle the redirect.

**Comment by zero-24** [comment]
Thanks merging

**Pull request merged**
