### PR TITLE
[4.3] Guided Tours remove description of permissions fieldset

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Remove additional description like #37875. After #40228 is merged no longer item level permissions are present.

### Testing Instructions

check `Guided Tours: Options`

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a606f0fc25f8b36e7a5538a6a0fd9d43fb616225<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40300">issues.joomla.org/tracker/joomla-cms/40300</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a606f0fc25f8b36e7a5538a6a0fd9d43fb616225<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40300">issues.joomla.org/tracker/joomla-cms/40300</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40300">issues.joomla.org/tracker/joomla-cms/40300</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 !

**Pull request merged**
