### PR TITLE
Make sure when we have no update and no download url we show the correct message

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue raised by @franz-wohlkoenig 

### Summary of Changes

Make sure when we have no update and no download url we show the correct message

### Testing Instructions

Install 3.9.12-dev
switch to the default update server (which does not know anything about 3.9.12 yet)
Joomla claims it found an update but could not found an download URL wich is not true
apply this patch
notice the correct message comes up
switch to the nighlty update server: https://update.joomla.org/core/nightlies/next_patch_list.xml (which knows of the existence of the 3.9.12-dev)
notice the reinstall message comes up

### Expected result

image

### Actual result

image

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3352704140db0923ae91093a662bd73b8f2c05d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26076">issues.joomla.org/tracker/joomla-cms/26076</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3352704140db0923ae91093a662bd73b8f2c05d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26076">issues.joomla.org/tracker/joomla-cms/26076</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26076">issues.joomla.org/tracker/joomla-cms/26076</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
