### PR TITLE
[com_finder] Toggle selection does not toggle in accordion

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #15063

### Summary of Changes
Changing `"` to htmlentity `&quot;` in the jhtml

### Testing Instructions
See #15063

### Expected result

Works after patch.

finder-filters

@Quy @dgt41 @franz-wohlkoenig

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 75c550d619dc0d8764224df64059617ea001c722<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15092">issues.joomla.org/tracker/joomla-cms/15092</a>.</sub>

**Comment by afk** [comment]
I have tested this item :white_check_mark: successfully on 75c550d619dc0d8764224df64059617ea001c722<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15092">issues.joomla.org/tracker/joomla-cms/15092</a>.</sub>

**Comment by Quy** [comment]
You may want to combine the 2 `class` attributes in the main `Toggle Selection` button in this PR.
`<button class="btn btn-default" type="button" class="jform-rightbtn" onclick="jQuery('.filter-node').each(function () { this.click(); });">`

**Comment by afk** [comment]
The PR combines it to `class="btn jform-rightbtn"`.

**Comment by Quy** [comment]
Yes, but there is a main `Toggle Selection` button to toggle all checkboxes and not within each section.

**Comment by C-Lodder** [comment]
Please could you remove the class `jform-rightbtn` as this isn't needed.

**Comment by infograf768** [comment]
@C-Lodder 

> Please could you also remove the class jform-rightbtn, as this isn't needed.

It is used by Hathor.

@Quy 
You are right, the classes should be also be combined in
/administrator/components/com_finder/views/filter/tmpl/edit.php line 73.
Please make PR.

**Comment by C-Lodder** [comment]
@infograf768 Hathor already contains a float classes. So, `fltrt` can just be used and the `jform-rightbtn` class can be removed

**Comment by infograf768** [comment]
@C-Lodder
Please post here https://github.com/joomla/joomla-cms/issues/15097 to improve at the same time.

I done my part 😺

**Comment by Quy** [comment]
@C-Lodder  `jform-rightbtn` is in \administrator\templates\hathor\less\template.less . Should it still be replaced with `fltrt`?

**Pull request merged**
