### PR TITLE
[5.1] Alpha sorting tuf strings

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

The TUF strings are sorted alphabetically.

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

The strings are not sorted alphabetically.

### Expected result AFTER applying this Pull Request

The strings are sorted alphabetically.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tecpromotion** [comment]
Thanks to @heelc29 for the hint during the translation and the review https://github.com/joomlagerman/joomla/pull/3103.

**Comment by tecpromotion** [comment]
Thanks to @heelc29 for the hint during the translation and the review https://github.com/joomlagerman/joomla/pull/3103.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 22428ea3229502b57d180d00dbac975323957299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42942">issues.joomla.org/tracker/joomla-cms/42942</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 22428ea3229502b57d180d00dbac975323957299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42942">issues.joomla.org/tracker/joomla-cms/42942</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42942">issues.joomla.org/tracker/joomla-cms/42942</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
