### PR TITLE
s/Allways/Always

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/Allways/Always

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d5f621fb07438afdbc8d23d160da27111e952bf4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31931">issues.joomla.org/tracker/joomla-cms/31931</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on d5f621fb07438afdbc8d23d160da27111e952bf4<br /><br />Tested successfully in 3.9.24-rc2 of 9 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31931">issues.joomla.org/tracker/joomla-cms/31931</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31931">issues.joomla.org/tracker/joomla-cms/31931</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
