### PR TITLE
[4.2] Deprecate a not used function in the modules HTML service

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Since https://github.com/joomla/joomla-cms/commit/5d2beea1dd1a01402fa91c471c030990cbc66223 this function is not used in core anymore. This pr deprecates it so it can be later removed.

It was added in https://github.com/joomla/joomla-cms/pull/29.

Can be merged on review.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e868c0164353e95cc2ef4ef454b4572f6b21f361<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37638">issues.joomla.org/tracker/joomla-cms/37638</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e868c0164353e95cc2ef4ef454b4572f6b21f361<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37638">issues.joomla.org/tracker/joomla-cms/37638</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37638">issues.joomla.org/tracker/joomla-cms/37638</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
