### PR TITLE
[install] - validate username

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23658

### Summary of Changes
do username validation check 

### Testing Instructions
see #23658

### Expected result
validation of username is consistent  cross the cms

### Actual result
you can install with a username with special chars like (**admin%**) on install but you cannot login with that username

### CODE REVIEW

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on 0e5ec0131e59feb6aca40dbcec4efd4e4ec792e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23918">issues.joomla.org/tracker/joomla-cms/23918</a>.</sub>

**Comment by adj9** [comment]
Acccept the charapt '€' but not '%' and '<'

**Comment by lucasacchiricciardi** [comment]
I have tested this item :white_check_mark: successfully on 0f85823eca89c2743630d9dbfac5a461cec5f3e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23918">issues.joomla.org/tracker/joomla-cms/23918</a>.</sub>

**Comment by davidemessia** [comment]
I have tested this item :white_check_mark: successfully on 0f85823eca89c2743630d9dbfac5a461cec5f3e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23918">issues.joomla.org/tracker/joomla-cms/23918</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 0f85823eca89c2743630d9dbfac5a461cec5f3e9<br /><br />Accept the charapt '€' but not '%' and '<'<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23918">issues.joomla.org/tracker/joomla-cms/23918</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23918">issues.joomla.org/tracker/joomla-cms/23918</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
