### PR TITLE
[4.3] Column Select Template Override

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the column select script to the list view of the updated template files to check. This can be really useful on this view as the file name column can be very wide etc.

### Testing Instructions
Testing requires overrides that need checking. You can simulate this by

Create template overrides for com_content/article and com_newsfeed/feed
Run this sql query replacing #_ with your db prefix 
`INSERT INTO #__template_overrides (id, template, hash_id, extension_id, state, action, client_id, created_date, modified_date) VALUES (1, 'cassiopeia', 'L2h0bWwvY29tX25ld3NmZWVkcy9uZXdzZmVlZC9kZWZhdWx0LnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54'), (2, 'cassiopeia', 'L2h0bWwvY29tX2NvbnRlbnQvYXJ0aWNsZS9kZWZhdWx0X2xpbmtzLnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54');

`You will now have two override files to update and can test this PR

image

PS It would be great if this view could also be filtered by component and had pagination etc

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 243ab7412402be65a9266cec1e305040f32154f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39380">issues.joomla.org/tracker/joomla-cms/39380</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 243ab7412402be65a9266cec1e305040f32154f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39380">issues.joomla.org/tracker/joomla-cms/39380</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39380">issues.joomla.org/tracker/joomla-cms/39380</a>.</sub>

**Comment by obuisard** [comment]
Thank you, Brian @brianteeman  :-)

**Comment by brianteeman** [comment]
thx

**Pull request merged**
