### PR TITLE
[4.0] com_messages: fix user settings and move these params to a view

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28958
### Summary of Changes
As title says.
The pop up is here changed to a view and the controller is corrected.

### Testing Instructions
Load Private Messages Manager.
Click on `My Settings` button.
For example switch `Lock Inbox` to Yes.
Save.
Click again on the button.

### Before patch

lockbrokenj4

### After patch

mysettings

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9d9e8462f02b08aa9f76ed87853d3df4b6f8a50a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29006">issues.joomla.org/tracker/joomla-cms/29006</a>.</sub>

**Comment by Quy** [comment]
Maybe add `<div class="card">` and `<div class="card-body">` to the form to separate it from the background pattern.

\administrator\components\com_messages\tmpl\config\default.php

pm

**Comment by infograf768** [comment]
@Quy 
Done, including taking of useless btn, limiting fields value width,etc.

Screen Shot 2020-05-10 at 08 25 25

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3a4d1cecd4012a2019a6e131b61e9dc0321a519f<br /><br />lgtm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29006">issues.joomla.org/tracker/joomla-cms/29006</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3a4d1cecd4012a2019a6e131b61e9dc0321a519f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29006">issues.joomla.org/tracker/joomla-cms/29006</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29006">issues.joomla.org/tracker/joomla-cms/29006</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 3a4d1cecd4012a2019a6e131b61e9dc0321a519f<br /><br />I also confirm the PR. It's a result of flag bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29006">issues.joomla.org/tracker/joomla-cms/29006</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
