### PR TITLE
[5.3] com_users doc comment

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes an obvious copy paste error that I had made

code review only

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 127290f421528164c6b809c8ed871cbc044d847d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44616">issues.joomla.org/tracker/joomla-cms/44616</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 127290f421528164c6b809c8ed871cbc044d847d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44616">issues.joomla.org/tracker/joomla-cms/44616</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44616">issues.joomla.org/tracker/joomla-cms/44616</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
