### PR TITLE
[4.1] skipto update

### PR DESCRIPTION
**Pull request by brianteeman**
Minor bugfix release upstream

Fixes problem in failure to create the SkipTo menu due to invalid configuration

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman The build.js fails because it can't find a file, see here: https://ci.joomla.org/joomla/joomla-cms/52245/1/7 .

**Comment by brianteeman** [comment]
thanks for the heads up. I made a mistake upstream. I trusted someone elses work - oops

**Comment by brianteeman** [comment]
Closing this - maintainers obviously dont car

**Comment by roland-d** [comment]
Thank you for the update

**Comment by brianteeman** [comment]
This should have been merged into 4.1.5 not 4.2

**Pull request merged**
