### PR TITLE
[4] en-GB verses en-US - order the languages

### LINKED ISSUE #33663: [4] en-GB verses en-US?
after running the commands to build everything from git, recently Ive been getting build_incomplete.html and fatal-error.html as modified files. 

The only difference is the language 

Screenshot 2021-05-08 at 20 30 58

Im not aware of having chosen a default language yet, is this something that needs fixing?

### PR DESCRIPTION
**Pull request by PhilETaylor**
Closes #33663

### Summary of Changes

I have no idea what any of this means, I just did as I was told by @dgrammatiko haha

### Testing Instructions

git checkout 4.0-dev
run the standard `jinstall` command (as [aliased in the docs](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment) to be:

```
alias jclean="rm -rf administrator/templates/atum/css; rm -rf templates/cassiopeia/css; rm -rf administrator/templates/system/css; rm -rf templates/system/css; rm -rf media/; rm -rf node_modules/; rm -rf libraries/vendor/;rm -f administrator/cache/autoload_psr4.php;rm -rf installation/template/css"
alias jinstall="jclean; composer install; npm ci"
```

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

No changes after running command.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on deddb71ce10cf757b46cd2d56d71b3aa2de4c8a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33674">issues.joomla.org/tracker/joomla-cms/33674</a>.</sub>

**Comment by PhilETaylor** [comment]
This did not work :( 

Screenshot 2021-05-08 at 22 51 05
Screenshot 2021-05-08 at 22 51 02

**Comment by dgrammatiko** [comment]
> This did not work :(

Wrong expectations?
Let me clarify what is happening here. Before https://github.com/joomla/joomla-cms/pull/32300 the languages were ordered ascending. After the refactoring the order was random (mostly `en-US` first and the `en-GB` but really dependant on the filesystem). Applying this PR the order becomes again asc (`en-GB` first, `en-US` second)

**Comment by PhilETaylor** [comment]
ah so you want me to commit these two modified files too? then they will stay like this...

**Comment by dgrammatiko** [comment]
> ah so you want me to commit these two modified files too? then they will stay like this...

Yup, that should fix it for everybody and set the ordering to something that is more predictable

**Comment by PhilETaylor** [comment]
> Yup, that should fix it for everybody 

ok added those files after building them with the new JS

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 5e8b84a003ed4dff769ff392fb66dddd26272435<br /><br />I was scratching my head over this issue yesterday. Thanks for fixing it!
I tracked the initial files before and after a clean install, they weren't modified.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33674">issues.joomla.org/tracker/joomla-cms/33674</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 5e8b84a003ed4dff769ff392fb66dddd26272435<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33674">issues.joomla.org/tracker/joomla-cms/33674</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33674">issues.joomla.org/tracker/joomla-cms/33674</a>.</sub>

**Comment by richard67** [comment]
Thanks all!

**Pull request merged**
