### PR TITLE
Complete the removal of weblinks from stats modules

### PR DESCRIPTION
**Pull request by brianteeman**
In #13389 the code for weblinks in the stats module was removed but the description remains in the module. This is confusing and so this PR removes the text about weblinks from the description. Its not needed just as there is no text in the description about having plugins installed that will inject other stats into that module

### CODE REVIEW

**Comment by Quy** [comment]
I don't know if it is necessary to update these files too in `installation\sql`:
sample_learn.sql
sample_testing.sql

**Comment by brianteeman** [comment]
@quy i think thats fine

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 55e291ccfec1079c07c97d963a4981e2d9c66ffb<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17458">issues.joomla.org/tracker/joomla-cms/17458</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 55e291ccfec1079c07c97d963a4981e2d9c66ffb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17458">issues.joomla.org/tracker/joomla-cms/17458</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17458">issues.joomla.org/tracker/joomla-cms/17458</a>.</sub>

**Comment by zero-24** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks for merging

**Pull request merged**
