### PR TITLE
Update JINVALID_TOKEN text for consistency

### PR DESCRIPTION
**Pull request by photodude**
In all other languages (and the en-GB install ini) JINVALID_TOKEN includes additional text beyond "invalid token" This PR makes this Language file consistent with the other language files.

Here is a ruff guidline based on the approved [Semantic Versioning](http://semver.org/) used by Joomla, which I think works well for evaluating if a PR is a bug fix for MAJOR.MINOR.PATCH, increment (or in this case for inclusion in the current beta series. Since all bug fixes which would otherwise increment PATCH number generally can and should be included during beta)

| Semantic Versioning  question | Answer for this PR |
| --- | --- |
| new API methods (aka endpoints) | no |
| new API functionality | no |
| fixes an existing issue/bug | yes |
| improvement to an existing feature | yes. |
| Backwards compatible | yes |
| changes existing lines of code | no |
| changes existing translation strings | yes |
| internal change that fixes incorrect behavior | Yes, as a correction to a translation string it fixes an incorrect internal behavior |

Based on those review points I would suggest that this has good qualifications for being a bug fix.

### CODE REVIEW

**Comment by creativeprogramming** [comment]
I have tested this item :white_check_mark: successfully on 42c7e6fecbc3a5aac87123651a3c041cdcc5ad68<br /><br />+1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8819">issues.joomla.org/joomla-cms/8819</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 42c7e6fecbc3a5aac87123651a3c041cdcc5ad68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8819">issues.joomla.org/joomla-cms/8819</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8819">issues.joomla.org/joomla-cms/8819</a>.</sub>

**Comment by photodude** [comment]
@rdeutz Is there any reason to hold a text correction back for 3.5.1 rather than including in 3.5.0?

**Comment by rdeutz** [comment]
Beta state means only bug fixes go in, that's the procedure, that's all.

**Comment by brianteeman** [comment]
This is a bug.

**Comment by rdeutz** [comment]
In a language file?

**Comment by brianteeman** [comment]
Yes.

**Comment by infograf768** [comment]
@rdeutz 
I think this can go in 3.5.0 as we are not yet in language freeze. It will be one less to do for 3.5.1. I personnaly did already correct it in our fr-FR 3.5.0.1 future pack.

**Comment by rdeutz** [comment]
Whatever, this is in no meaning a bug. We have a process and I am following the process. I am open to discuss the process but I am not open to discuss any issue, if that can be merged or not. The reason for having a policy is that 
a) Anyone can know how and what we do
b) Not to discuss any issue and wasting time

It wouldn't be the first time we merged a small change and the result was that there was a side effect and we had to release and new release just some days after we released a version. We need to deliver a more stable and better in quality Joomla.

I checked any issue in RTC and I am merging all issues that are bug fixes following the procedure we agreed on usually within hours. But it seems that this is not a way to make people happy so I will stop doing it, there are enough people with merge right that can do the job.

**Comment by photodude** [comment]
@rdeutz it's clearly a mater of interpratation on if a text string wording is a bug. 

I'm not intending to debate the process. Clearly 3.5.0 is in beta, therefore it's in language freeze (i.e. no api end point changes or new feature additions) and only bug fixes should go in (unless a show stopper bug is discovered). 

But we unfortunetly don't have good guidlines on when a bug is acceptable for inclusion in a beta state release vs when it has to be help back for the next patch release. Therefore there is all kinds of opinions going arround on whether this PR or that PR is actually a bug that can be included durring the beta state of 3.5.0. Which is where, as you pointed out, some people are not happy with the resulting decisions and interpretations of whether a PR is or isn't the type of bug that can be merged at the point of a beta state.

**Comment by wilsonge** [comment]
We haven't called language freeze on anything other than the installation folder langs at the moment. So I'm merging this for 3.5

**Pull request merged**
