### PR TITLE
[#5570] - Create Article:: Can we change the placeholder message for 'Tag'

### PR DESCRIPTION
**Pull request by Flow87**
Provide possible solution for issue #5570

**Request:** 
Placeholder message for tag field should be "Type or select some options".

**More information:**

The input field of tags which you find at the article manager in the back end has the placeholder message "Select an option". This can lead the user to think that there it is only the possibility to select one of the already given tags. But the actual options you have through selecting the input field are:
1. Select one tag from available list
2. Select multiple tags from available list
3. Type a tag
4. Type multiple tags
5. Combination of selected and typed tags

In order to make the bahavior of this input field clearer the placeholder message should be changed to something like: "Type or select some options" 

**The solution for this issue:**
1. The string used as placeholder is from the global variable "JGLOBAL_SELECT_SOME_OPTIONS" in the "en-GB.ini".
2. In the "formbehavior.php" this variable is used as placeholder when the field is marked as "multiple" in a method named "chosen".
3. Created a new global variable named "JGLOABL_TYPE_OR_SELECT_SOME_OPTIONS" in "en-GB.ini" which contains the string "Type or select some options".
4. Changed the method "chosen" in "formbehavior.php" so if the field is marked as "multiple" the string given for the placeholder message is the created "JGLOABL_TYPE_OR_SELECT_SOME_OPTIONS". 

**How to test:**

-Log into the administrator panel
-Go to article manager
-Create new article
-Check placeholder message

**Expected result after solution:**
The placeholder message of the tag field will now be "Type or select some options."

_Worked as a group on that issue: @icampus, @FPerisa, @kathastaden and @xsability_

### CODE REVIEW

**Comment by zero-24** [comment]
successful tested by @wschouwe here: https://github.com/joomla/joomla-cms/commit/3eb605c598a025110afbf421bd973f4bf5263458 one more tester ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Comment by brianteeman** [comment]
@wschouwe How can that be a successful test. That was the original string not the changed string

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on d8f1b7ee4728aa1e6ee328a7c65d75371e015074<br /><br />Tested according to instructions. Works. Nice.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Comment by roland-d** [comment]
Removed RTC status because of Brian's remark that the first test can't be successful. Please make another test on this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Comment by infograf768** [comment]
The new string should also be added in frontend en-GB.ini as it is used there.

screen shot 2015-10-23 at 08 41 20

**Comment by si-wi** [comment]
I have tested this item :white_check_mark: successfully on d8f1b7ee4728aa1e6ee328a7c65d75371e015074<br /><br />tested  successfully according "How to test"
Button label before patch: "Select some options" 
Button label after patch: "Type or select some options"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Comment by zero-24** [comment]
@Flow87 can you implement the new string also to the frontend en-GB.ini see: https://github.com/Flow87/joomla-cms/blob/staging/language/en-GB/en-GB.ini

**Comment by wojsmol** [comment]
@Flow87 see https://github.com/Flow87/joomla-cms/issues/1

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on d8f1b7ee4728aa1e6ee328a7c65d75371e015074<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Comment by brianteeman** [comment]
This cant be merged https://github.com/joomla/joomla-cms/pull/8041#issuecomment-150490649

**Comment by wojsmol** [comment]
@brianteeman @Flow87 see https://github.com/Flow87/joomla-cms/pull/1

**Comment by brianteeman** [comment]
This has been waiting for 3 months just to have a new string added to the PR - not worth waiting any longer. I have remade the PR with the missing string at #9360<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8041">issues.joomla.org/joomla-cms/8041</a>.</sub>

**Pull request closed without merging**
