### PR TITLE
typo in tinymce script

### PR DESCRIPTION
**Pull request by brianteeman**
#11157 introduces a new thing called setupCallbacString

The OCD typo hunter in me spotted the missing k so I have changed all instances to setupCallbackString

There is no b/c issue as #11157 was only introduce by @fedik in 3.7 so the code hs never been released

I'm afraid I have no idea how to test it other than by code review as I dont know what it does

### CODE REVIEW

**Comment by Fedik** [comment]
> I have no idea how to test it 

all xtd-buttons should continue to work 😉

**Comment by dgt41** [comment]
@brianteeman since you did the correction both php and javascript this only needs a review

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on b1e396e456dba1d88b0ce35f9e25b48802ee7e1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12913">issues.joomla.org/tracker/joomla-cms/12913</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on b1e396e456dba1d88b0ce35f9e25b48802ee7e1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12913">issues.joomla.org/tracker/joomla-cms/12913</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
