### PR TITLE
Use Framework Crypt package

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Pull in the Framework's Crypt package, rebase the `JCrypt` classes onto it.

This pulls in the updated `defuse/php-encryption` package too.  It has B/C breaks between the version we have now and 2.0 but it's written in a way the two can be used side-by-side.

The `random_bytes()` polyfill is updated too as a requirement of the updated encryption package.  The change here is that it doesn't use the OpenSSL pseudo random number generator.
### Testing Instructions

The encryption API continues to work.
### Documentation Changes Required

`JCryptKey` is now an immutable object.  Pass all values into the constructor when creating it.

There are now getter methods for all key properties, use those instead of direct access.

### CODE REVIEW

**Comment by zero-24** [comment]
Can we remove with this change the old `cipher` that are vulnerable? If you agree i can do it in a different PR.

* `JCryptCipher3Des`
* `JCryptCipherBlowfish`
* `JCryptCipherMcrypt`
* `JCryptCipherRijndael256`
* `JCryptCipherSimple`

**Comment by mbabker** [comment]
If they're deprecated then yes they should be dumped.  I just aimed to make
everything that's there now work, wasn't looking for class deletion.

**Comment by zero-24** [comment]
Ok i'm going to prepare two PRs than one for staging and one for 4.0 :smile:

**Comment by wilsonge** [comment]
I merged @zero-24 's PR before I saw this. Unsure how we want to proceed with this? Remove the unsecure ones from the framework? Do we even want to be doing this ourselves or is there a better 3rd party full implementation?

**Comment by mbabker** [comment]
They're already gone in the Framework.  All that's left is the defuse
package crypto class.

**Comment by mbabker** [comment]
I've rebased this.

**Pull request merged**
