### PR TITLE
[4.0] move icon to block

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue #29733

### Summary of Changes
move icon to block for webauth button

### Testing Instructions
Access Joomla 4 over a SSL
Go to /administrator/
notice that icon is missing
apply pr.
in termal run `npm ci`
notice that icon is showing in webauth block
notice that the joomla logo is colorized

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required

none

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Black on blue?... any chance it can be white? and why double the height of the button? Sorry, don't like it :) :) :) 

And No, I could not do better :)

**Comment by N6REJ** [comment]
can definitely be white.  Not sure why it's black.  I was thinking the same thing to be honest.
as for making it smaller, believe it or not it doesn't play nice.  I tried several times to get the block to a more uniform size and was unable to.
I can always go back to the drawing board if desired.

**Comment by N6REJ** [comment]
how's this? 
image

**Comment by PhilETaylor** [comment]
Much Better but still bad :) 

Its not your fault - its just a crappy logo which then pushes the text to "appear" not centered. 

Maybe less padding to the left of "Web" maybe? but what do I know :)

**Comment by N6REJ** [comment]
This is the best I can do.
image

**Comment by richard67** [comment]
@N6REJ Could you fix the SCSS code style errors reported here by Drone? https://ci.joomla.org/joomla/joomla-cms/36296/1/22 

They are mainly about ordering of properties. The reason why you didn't notice that might be that drone failed for unrelated reasons at some other test before running the scss cs test.

Now after I have restarted drone it turned out there are these scss code style errors.

Thanks in advance.

**Comment by PhilETaylor** [comment]
>This is the best I can do. 

Like I said I don't think this is your fault - just a crappy logo... Can we even just remove the logo? after all its never shown to anyone before you fixed it anyway :) haha that would solve all the issues. !?

**Comment by richard67** [comment]
> Like I said I don't think this is your fault - just a crappy logo... Can we even just remove the logo? after all its never shown to anyone before you fixed it anyway :) haha that would solve all the issues. !?

Agree. That logo just shows too many small details for being used as an icon.

**Comment by dgrammatiko** [comment]
Please use SVG for the icon as anything non vector will always be crappy in some scenarios.
Copy paste the icon from here:
https://iconify.design/icon-sets/simple-icons/webauthn.html

License : cc, so it's fine

**Comment by N6REJ** [comment]
well, took a while to get everything "perfect" but I think we got there as far as using an icon goes.
as for removing it, you'd need to ask someone far higher up the food chain then me if thats ok.
image

**Comment by PhilETaylor** [comment]
If the icon is staying, then the great job you have done now gets a thumbs up from me and is a lot better than the first black logo attempt.

**Comment by PhilETaylor** [comment]
Just another Sunday question - why are we using a black version of the joomla logo instead of the actual colour logo on the login page there? Surely the project should be using and promoting its main symbol on the main login page and not a manipulated black version. Just a thought.

**Comment by infograf768** [comment]
@PhilETaylor 
> why are we using a black version of the joomla logo instead of the actual colour logo

Good question...

Here is a login page with a colored svg (size can be modified)

Screen Shot 2020-10-11 at 12 08 00

**Comment by infograf768** [comment]
If you need it to replace the present svg, here it is (same size)

Screen Shot 2020-10-11 at 16 46 40

[login.svg.zip](https://github.com/joomla/joomla-cms/files/5361280/login.svg.zip)

**Comment by N6REJ** [comment]
@PhilETaylor @infograf768 done and ty for supplying the svg file

**Comment by dgrammatiko** [comment]
@N6REJ the sass linter expects alphabetical sorted properties...

**Comment by N6REJ** [comment]
READY FOR TESTING FINALLY

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on fbd68545c47f25be7c234f576abff43d5912a26f<br /><br />The result is exactly like the expected one in the description<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31028">issues.joomla.org/tracker/joomla-cms/31028</a>.</sub>

**Comment by Turikhay144** [comment]
Tested logo changes to color
But I don't see the web auth button
Screenshot 2020-10-17 at 17 56 20

**Comment by richard67** [comment]
@Turikhay144 The WebAuth button can only be seen when accessing the site with https. I assume you used http.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fbd68545c47f25be7c234f576abff43d5912a26f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31028">issues.joomla.org/tracker/joomla-cms/31028</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31028">issues.joomla.org/tracker/joomla-cms/31028</a>.</sub>

**Comment by richard67** [comment]
Thanks everybody who was involved.

**Pull request merged**
