### PR TITLE
[4.0] concat spaces

### PR DESCRIPTION
**Pull request by brianteeman**
When we concat two things with a . there should be a space on either side of the .

code review (stop my ide screaming)

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 0b553533f961122dd4f9e0776216c6687671871e<br /><br />This is the kind of thing php-cs-fixer can be automated to do if this project actually had balls, instead we have to waste our time with this kind of crap.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34346">issues.joomla.org/tracker/joomla-cms/34346</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b553533f961122dd4f9e0776216c6687671871e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34346">issues.joomla.org/tracker/joomla-cms/34346</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34346">issues.joomla.org/tracker/joomla-cms/34346</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
