### PR TITLE
[com_contact] Adding "category on fly" functionality when create/edit contact

### PR DESCRIPTION
**Pull request by vinespie**
#### Summary of Changes

 Adding "category on fly" functionality when create/edit contact.

Before
2016-07-29 17_34_07-contacts_ new - joomla 3 - administration

After
2016-07-29 17_27_20-contacts_ new - joomla 3 - administration
#### Testing Instructions
1. Apply patch
2. Go to Administrator -> Components -> Contacts ->Contacts
3. Click "New"
4. Enter contact name
5. Go to category list, enter category name and press "Enter" : 
   2016-07-29 17_38_03-contacts_ new - joomla 3 - administration
6. Save contact
7. Contact and new contact category "Example" were created
8. Do the same test when editing

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 59096807d20bae76a37800344846048216f2d509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11354">issues.joomla.org/joomla-cms/11354</a>.</sub>

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on 59096807d20bae76a37800344846048216f2d509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11354">issues.joomla.org/joomla-cms/11354</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11354">issues.joomla.org/joomla-cms/11354</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/a32d8463a910ffe064eb717316b945f71c43e100 - thanks!

**Pull request closed without merging**
