### PR TITLE
Messaging - remove duplicate submenu item

### PR DESCRIPTION
**Pull request by pe7er**
This PR removes the duplicate menu item in the Messaging submenu. 
IMHO offering less (duplicate) options is better for UX.
# Testing instructions
## Before this PR

Components > **Messaging** (shows list of private messages) has two submenus:
- **New Private Message** (create new private message form) 
- **Read Private Messages** (shows list of private messages) which is a duplicate of the parent **Messaging** menu item

messaging-menu-before

Other components, like com_content, do not have such duplicate options.
See Content > Articles (shows list of articles) > has one submenu item **Add New Article** (create new article form)

messaging-menu-articles-example
## After this PR

The administrator menu items are created from records in the database. 
The database settings are created upon installation and therefore the testing procedure is a bit different:
- Install the patch
- remove configuration.php
- install Joomla again
- check the new menu settings:

Components > **Messaging** now has only one submenu: **New Private Message**

messaging-menu-after

**Note:** I have only removed the duplicate menu item in the MySQL files (Joomla core installation and all different sample data files), and in tests/system/webdriver/Pages/System/AdminPage.php and tests/unit/stubs/database/jos_menu.csv. 
I have **not yet** changed it in **Postgresql, nor in SQLAzure**. I would like to have this PR tested before I'll make the necessary changes in those two databases.

### CODE REVIEW

**Comment by n9iels** [comment]
For some strange reason, I can not apply this patch via the Joomla! Patch tester. Is this a problem in my test installation?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by brianteeman** [comment]
Quick comment without testing as I'm on a phone.

The 'add new' is usually governed by a setting in the admin menu module

**Comment by pe7er** [comment]
Did you reinstall Joomla after applying the patch?

The submenus of the components under the Components menu are retrieved from the database. And the database settings are created upon installation. Therefore you'll need to reinstall Joomla with the patched SQL files.

**Comment by YouriiM26** [comment]
I can't not apply the patch. I have re-installed the newest joomla-cms-staging on my localhost. 

This is the error what I get when I apply the patch: 
Error
The patch could not be applied because it conflicts with a previously applied patch: installation/sql/mysql/joomla.sql

Hopefully can you fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by mbabker** [comment]
That's by design with the patch tester.  What that means is that it has found a backup of that file in the `administrator/components/com_patchtester/backups` folder either from a previous patch or having not fully reverted a patch.  When you're using the patch tester, you should ensure that you have reverted all patches before applying a new one, and if you still get this message after that, you need to delete any backups from that folder.

**Comment by YouriiM26** [comment]
I have looked in the administrator/components/com_patchtester folder and this folder is empty.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by patjun** [comment]
I think the test description is not complete. The patch changes a file in the installation directory. I added the first list item.

- add the installation folder to your joomla installation
- Install the patch
- remove configuration.php
- install Joomla again
- check the new menu settings:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by patjun** [comment]
I have tested this item :white_check_mark: successfully on 1a41dfbcbdb0fa07d683137d47b736c7ba49e51b<br /><br />I tested the patch with the changed test description in my comment. With this description the patch works for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on 1a41dfbcbdb0fa07d683137d47b736c7ba49e51b<br /><br />Patch works as described.

Remember to update the IDs and also the lft, rgt values for the other entries in that table for the final version of this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by zero-24** [comment]
RTC @committer please take care on the comment by @matrikular <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8057">issues.joomla.org/joomla-cms/8057</a>.</sub>

**Comment by pe7er** [comment]
@zero-24 Do you mean me?
What's an easy way to update the IDs and lft, rgt values for the other entries in those tables?

**Comment by roland-d** [comment]
@zero-24 The lft and rgt values do not need to be updated because the entries @pe7er is removing are not in the assets table. Only the main extension com_messages is in there but not the suboptions. The suboptions are only links to the component.

As for updating the ID's, I wouldn't go through the hassle. It would be a major hassle to reclaim number 12.

**Pull request merged**
