### PR TITLE
[5.2] Privacy: Allow MFA and invalid privacy consents

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #42783, #38791.

### Summary of Changes
When a user has no valid privacy consent and has MFA enabled, they are stuck in an endless redirect loop.

### Testing Instructions
1. Setup a user with MFA
2. Enable the privacyconsent system plugin
3. Login with that user in the frontend

### Actual result BEFORE applying this Pull Request
Endless redirect loop between captive view and profile edit view.

### Expected result AFTER applying this Pull Request
MFA captive view is displayed and you can type in a MFA code.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on e02d12b9c93ca4ee3415cb73b9be81ae6ceb677f<br /><br />I was able to reproduce the issue: I ended up in an endless loop and could not login. 

After the patch I was able to login, and the Privacy Policy consent option is displayed in the User Profile<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44522">issues.joomla.org/tracker/joomla-cms/44522</a>.</sub>

**Comment by alikon** [comment]
without pr
image

with pr
I was able to login.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e02d12b9c93ca4ee3415cb73b9be81ae6ceb677f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44522">issues.joomla.org/tracker/joomla-cms/44522</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44522">issues.joomla.org/tracker/joomla-cms/44522</a>.</sub>

**Pull request merged**
