### PR TITLE
[4.0] Javascript - destruct params

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Just some minor JS improvements to use parameter destructing.

### Testing Instructions

Code review

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@C-Lodder you cannot introduce such ES2015+ options without a way to compose ES5 compatible scripts. In short you need to pump (eg use rollup) the build tools if you still care for ES5. I'm guessing the project neither cares about ES5 or any js version other than the latest ES20**..
Not a wise choice (just an opinion from an old guy...)

**Comment by C-Lodder** [comment]
Babel transpiles destructing params by default. This **isn't** a DOM method.
No need to use rollup at all.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 25a88da4a356840ce8ce637ad89fdf8095646c1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28710">issues.joomla.org/tracker/joomla-cms/28710</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 25a88da4a356840ce8ce637ad89fdf8095646c1f<br /><br />Test OK

The build script transpile the parameter destructing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28710">issues.joomla.org/tracker/joomla-cms/28710</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28710">issues.joomla.org/tracker/joomla-cms/28710</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix conflicts here please - it's from the install from web pr you did

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
