### PR TITLE
[4.0] Cleanup .gitignore a little - can be merged on sight :) 

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

 - removed the trailing `#` in comments, not all comments had them so was inconsistent anyway
 - removed the trailing `.` in comments
 - Remove blank line
 - added `.docker` and `/docker-compose.yml` as some people use official Joomla docker images for testing  
 - s/handeling/handling

### CODE REVIEW

**Comment by brianteeman** [comment]
Just a question for my own education I think but why are some paths with a preceding slash and some not
eg
administrator/language/*
/administrator/components/com_patchtester

**Comment by PhilETaylor** [comment]
Pattern format is explained here https://git-scm.com/docs/gitignore

In your example there would be no reason not to have a preceding `/` to `administrator/language/*` if the purpose was to exclude the `/administrator/language` folder 

however if the intention was also to exclude `/some/other/path/to/administrator/language/` then not preceding it with a `/` seems right. 

A good example is `node_modules/`. which would not only exclude the root `/node_modules` but would also exclude any other `node_modules` folder throughout the webspace. 

The gotcha is that if you exclude with a line like `log.php` this will also exclude ANY file in the webspace with a suffix of `log.php` including things like `Monolog.php`

**Comment by brianteeman** [comment]
So thats what I thought it meant

so surely **most** of the paths should be preceded by a /

**Comment by PhilETaylor** [comment]
I cannot speak for the authors of those lines and their intentions at the time, but yes it does seem that some could be, you are right.

**Pull request merged**
