### PR TITLE
Update to default.php: removed nowrap class to allow wrapping title…

### PR DESCRIPTION
**Pull request by kofaysi**
…and alias

Pull Request for Issue #24650.

### Testing Instructions

Create a contact with a name/title of 200+ characters

### Expected result

The title and the alias will wrap, long words will break.

### Actual result

The title and the alias does not wrap and pushes other parameters (access, hits, language, ID) behind the right edge of the screen.

### Documentation Changes Required

IDK about any.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 2643f7a7f6ab7db2ee1a44891446a33436b3bfcd<br /><br />
#### Without PR
Screen Shot 2019-04-24 at 08 49 21
#### With PR
Screen Shot 2019-04-24 at 08 49 52

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24712">issues.joomla.org/tracker/joomla-cms/24712</a>.</sub>

**Comment by kofaysi** [comment]
a `break-word` class has to be added a line below the current change
`<div class="pull-left break-word">`
But I do not understand how can I change the existing PR. I can create a new PR, but is that the right approach?

**Comment by ghost** [comment]
i don't know but pretts aure a dev will answer.

**Comment by hardik-codes** [comment]
@kofaysi you can do the changes on your local machine and then push those changes. In this way a new commit will be added to the existing PR

If you are finding it difficult and if you want  I can do a PR for you with your suggested changes

**Comment by kofaysi** [comment]
Unfortunately, I'm making changes and PRs through the web interface. Looking into the existing PR, I cannot make changes to the code.

So, please, if you feel so, make a change. Thank you!

**Comment by brianteeman** [comment]
Go to https://github.com/kofaysi/joomla-cms

Select the branch - in this case it is staging

Make the changes you want there and they will appear here

**Comment by hardik-codes** [comment]
Please elaborate the change you want to have along with the line number where it should go.
I will do a PR asap

**Comment by hardik-codes** [comment]
@kofaysi you can follow what @brianteeman suggested

**Comment by kofaysi** [comment]
Thank you for the suggestion. Changes are made and pushed. (Well, that was very straightforward.)

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1314cc9c67d6bb30e8a9e789ce341f68fa073d4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24712">issues.joomla.org/tracker/joomla-cms/24712</a>.</sub>

**Comment by brianteeman** [comment]
@kofaysi glad you worked it out.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1314cc9c67d6bb30e8a9e789ce341f68fa073d4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24712">issues.joomla.org/tracker/joomla-cms/24712</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24712">issues.joomla.org/tracker/joomla-cms/24712</a>.</sub>

**Comment by SniperSister** [comment]
Merged, thank you for contribution, it's much appreciated!

**Pull request merged**
