### PR TITLE
[4.0] Improve text padding in quickicons

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #28665 .

### Summary of Changes
Improve padding around text in quickicons

### Testing Instructions
Apply the patch don't forget to build the css with npm.
Have a look on the quickicons on differents screens. 

### Expected result
All texts should have some padding. 

### Actual result
see the issue

### Documentation Changes Required
no

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f960459aa4fcb3fbf98705125a64a51b4159ab32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28668">issues.joomla.org/tracker/joomla-cms/28668</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on f960459aa4fcb3fbf98705125a64a51b4159ab32<br /><br />Successful for the mentioned Icon in the PR, could not test with 3rd party extensions because I am constantly thrown out of the backend since applying the patch. I am sure it has nothing to do with each other since you only worked on the scss and classes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28668">issues.joomla.org/tracker/joomla-cms/28668</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28668">issues.joomla.org/tracker/joomla-cms/28668</a>.</sub>

**Comment by richard67** [comment]
I've also checked that the quickicons still work by faking a Joomla Update, and Extension Update and an Urgent Privacy Request.

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
