### PR TITLE
Mod Latest Articles - Admin

### PR DESCRIPTION
**Pull request by brianteeman**
the admin module mod_latest displays a list of the most rrecent articles added to the site but it only shows if the article is published or not. It doesnt display if the article is pending or expired.

this PR resolves that and the module will now correctly display if the article is
published, unpublished, pending or expired

### Test Instructions
Create 4 articles
1. Published
2. Unpublished
3. Published but Pending (published in the future)
4. Published but Expired (published but now after the end date)

Before the PR the admin module on the control panel will just display published/unpublished

After the PR the admin module will display the correct icons (the ones you see in the article manager)

### Before

screenshotr09-58-43

### After

screenshotr10-00-05

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
After applied PR got:
bildschirmfoto 2017-03-10 um 11 32 52

**Comment by brianteeman** [comment]
Strange. Clearly I dont see that as I took screenshots with error reporting set to development and i tested on php 56 and 71

**Comment by infograf768** [comment]
The module is not designed to modify the state of the articles in the CPanel. It should just show their state.

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 2059fe16960dd6cbd70a958b1b8859c3202fd843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14446">issues.joomla.org/tracker/joomla-cms/14446</a>.</sub>

**Comment by wilsonge** [comment]
I haven't tested but as far as I can tell you are not defining `$canChange` on the line 19 which would backup @frankmayer 's test. In terms of whether you are allowed to change state - I'm easy. We can just replace `$canChange` with `false` if we don't want to allow state change

**Comment by infograf768** [comment]
@brianteeman 
@wilsonge suggestions works great.
Just add `$canChange = false;` after `JHtml::_('bootstrap.tooltip');`

Example of results:
screen shot 2017-03-11 at 10 17 11

**Comment by brianteeman** [comment]
Updated. I cant test it though as I was never able to get the error for some reason - even though I agree it should have appeared

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 2059fe16960dd6cbd70a958b1b8859c3202fd843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14446">issues.joomla.org/tracker/joomla-cms/14446</a>.</sub>

**Comment by joomdonation** [comment]
@brianteeman I can see the error, too, both from testing and reading the code as @wilsonge described . Just change the code from:

```php
<?php echo JHtml::_('jgrid.published', $item->state, $i, 'articles.', $canChange, 'cb', $item->publish_up, $item->publish_down); ?>
```
To:
```php
<?php echo JHtml::_('jgrid.published', $item->state, $i, 'articles.', false, 'cb', $item->publish_up, $item->publish_down); ?>
```
and it should be OK. Please don't add an unnecessary command **$canChange = false;**

**Comment by brianteeman** [comment]
I just did what i was told to do :(

**Comment by joomdonation** [comment]
Not sure what you did but the code still not updated in this PR

**Comment by brianteeman** [comment]
doh - i needed coffee I updated the wrong file. Reverted that and set to false correctly now

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on e8042900a83664e87ddecd0c09c3004f2ad8cdf7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14446">issues.joomla.org/tracker/joomla-cms/14446</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e8042900a83664e87ddecd0c09c3004f2ad8cdf7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14446">issues.joomla.org/tracker/joomla-cms/14446</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14446">issues.joomla.org/tracker/joomla-cms/14446</a>.</sub>

**Comment by wilsonge** [comment]
Good stuff :)

**Pull request merged**
