### PR TITLE
[4.0] Hide Mass Mail Users menu when Send Mail is disabled

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #25508 .

### Summary of Changes
Hide `Mass Mail Users` menu when `Send Mail` is disabled which takes precedence of `Disable Mass Mail`.

### Testing Instructions
For screenshots, go to #25508 

Go Global Configuration > Server
Set `Send Mail` to Yes
Set `Disable Mass Mail` to No
Click Save
Under `Users` menu, `Mass Mail Users` is displayed
Set `Send Mail` to No
Click Save
Under `Users` menu, `Mass Mail Users` should not be displayed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e002bdbaf5e91765a7579851a978df4922ced059<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25510">issues.joomla.org/tracker/joomla-cms/25510</a>.</sub>

**Comment by richard67** [comment]
Does anybody know why nobody else than me tests this PR?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e002bdbaf5e91765a7579851a978df4922ced059<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25510">issues.joomla.org/tracker/joomla-cms/25510</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25510">issues.joomla.org/tracker/joomla-cms/25510</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
