### PR TITLE
[4.0] Update jquery migrate

### PR DESCRIPTION
**Pull request by brianteeman**
Pr for #19434

See comment from @wilsonge https://github.com/joomla/joomla-cms/pull/15136#issuecomment-296371996 as to why it is not being 100% removed

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by mbabker** [comment]
The lock file's missing...

**Comment by brianteeman** [comment]
I didnt know I was supposed to commit that :(

Should I do a new pr for that?

**Comment by brianteeman** [comment]
#22617

**Comment by mbabker** [comment]
> I didnt know I was supposed to commit that :(
> 
> Should I do a new pr for that?

Same as `composer.lock`, should be committed because that's tracking the actual dependency versions to use, not just declared supported ranges.

**Pull request merged**
