### PR TITLE
[4.0] MVC library prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements in `Joomla\CMS\MVC` namespace.

### Testing Instructions

Set up a multilingual site.
Create some articles. Add language associations. Check that associations are saved correctly.
Edit some articles. Check associations again.
Delete some associated articles. Check that related entries are removed from `#__associations` table.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 66f64dc61c9327809858508db752fa78a604882c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26099">issues.joomla.org/tracker/joomla-cms/26099</a>.</sub>

**Comment by obuisard** [comment]
Tested successfully!

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26099">issues.joomla.org/tracker/joomla-cms/26099</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
