### PR TITLE
[4] Allow banner creation if there are not categories

### PR DESCRIPTION
**Pull request by PhilETaylor**
https://github.com/joomla/joomla-cms/pull/33380#issuecomment-828806385

### Summary of Changes

Allow banner creation if there are no banner categories. 

### Testing Instructions

Delete all your banner categories.
Note you cannot create any banners as the NEW toolbar button doesn't show

### Actual result BEFORE applying this Pull Request

Note you cannot create any banners as the NEW toolbar button doesn't show

### Expected result AFTER applying this Pull Request

You can click NEW to create a new Banner, and a new Uncategorised category is created on the fly when you save it. 

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by joomdonation** [comment]
Still not valid. Please use the suggested code https://github.com/joomla/joomla-cms/pull/33380#issuecomment-828808240

**Comment by PhilETaylor** [comment]
you were too quick for me ... I was multi tasking - now done.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on c452f8793894307a4e79e70e627a1f6d1912c6cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33399">issues.joomla.org/tracker/joomla-cms/33399</a>.</sub>

**Comment by Quy** [comment]
The `New` button is fixed, but no `Add your first banner` button.

**Comment by PhilETaylor** [comment]
added that to this as well now

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c2260e9c7e688d44f5936b98ea67242fe6a7513b<br /><br />Perfect! Thank you!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33399">issues.joomla.org/tracker/joomla-cms/33399</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on c2260e9c7e688d44f5936b98ea67242fe6a7513b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33399">issues.joomla.org/tracker/joomla-cms/33399</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33399">issues.joomla.org/tracker/joomla-cms/33399</a>.</sub>

**Comment by joomdonation** [comment]
A perfect fix would be store $canDo as a property of the class and use **$this->canDo->get('core.create')** instead of **$user->authorise()** but guess I'm asking too much :D

**Comment by richard67** [comment]
@PhilETaylor The next one with conflicts due to one of your other PR's, this time file `administrator/components/com_banners/src/View/Banners/HtmlView.php`. No need to hurry, just a remainder so it is addressed.

**Comment by PhilETaylor** [comment]
Sorry - sidetracked with https://github.com/joomla/joomla-cms/pull/33422 and trying to hide show form fields :(

**Comment by PhilETaylor** [comment]
Done

**Comment by richard67** [comment]
I've restored previous test results in the tracker since the last commit after that was just a clean branch update and merge conflict resolution.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
