### PR TITLE
[4.0] Remove getsortfields from views of com_users, menus, modules

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
List Views have a method getSortFields().
This Method is not used in the core. The names of the table headers are in the respective tables as language keys. 

### Testing Instructions
Code Inspect. Testing this can only be playing around with table headers in list views. 
Are all texts displayed corretly, does sorting work as before? Also with open search tools? 

### Expected result
Everything works as before

### Note
There are several similiar PRs, hopefully reducin the risk of conflicts

### CODE REVIEW

**Comment by astridx** [comment]
I tested this successful.
1. git fetch origin pull/27677/head:remove-getsortfields-users-menus-modules
2. git checkout remove-getsortfields-users-menus-modules

3. I have often wondered what I need these methode for. The sort fields are inserted with an XML file. That is why I first checked if this XML-File is for every component in this PR on his place.
The files 
/administrator/components/com_menus/forms/filter_*
/administrator/components/com_modules/forms/filter_*
/administrator/components/com_users/forms/filter_*
are there.

4. After that I checked that I could sort `users`, `menus` items and `admin/site modules.`

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on b74484f9e1f84911f1a8c6ea066b4a232b2422c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27677">issues.joomla.org/tracker/joomla-cms/27677</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b74484f9e1f84911f1a8c6ea066b4a232b2422c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27677">issues.joomla.org/tracker/joomla-cms/27677</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27677">issues.joomla.org/tracker/joomla-cms/27677</a>.</sub>

**Comment by chmst** [comment]
@Quy , @astridx thank you for testing

**Pull request merged**
