### PR TITLE
[4.0] Language strings are coupled to template

### PR DESCRIPTION
**Pull request by brianteeman**
The string TPL_ATUM_TOGGLE_SIDEBAR should not be tied to the template. This PR renames the string to JTOGGLE_SIDEBAR_MENU and moves it to the generic language file

Pull Request for Issue #25950 .

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 65dda48d963544034a79a9ee227015f72b92b519<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27082">issues.joomla.org/tracker/joomla-cms/27082</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 65dda48d963544034a79a9ee227015f72b92b519<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27082">issues.joomla.org/tracker/joomla-cms/27082</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27082">issues.joomla.org/tracker/joomla-cms/27082</a>.</sub>

**Comment by anibalsanchez** [comment]
From #JMAD19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27082">issues.joomla.org/tracker/joomla-cms/27082</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
