### PR TITLE
New Installer plugins version (not 3.5)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

The version on the new installer plugin merged in https://github.com/joomla/joomla-cms/commit/c52e0d2ea90b9a73ac224d757a23add064f94e00 are 3.5 and should be 3.6
#### Testing Instructions

Simple code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f1466fe420363a6ff26b3387a4a4131261a65e97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10298">issues.joomla.org/joomla-cms/10298</a>.</sub>

**Comment by brianteeman** [comment]
Simple and obvious fix RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10298">issues.joomla.org/joomla-cms/10298</a>.</sub>

**Comment by roland-d** [comment]
Merged based on review

**Comment by andrepereiradasilva** [comment]
thanks!

**Pull request merged**
