### PR TITLE
[4.0] Fix dispatcher to use the backend

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #18626 .

### Summary of Changes
Attempts to fix versioning in the frontend. I'm very unsure about the quality of this fix. But it does work

### Testing Instructions
Checking versioning in the frontend editing view works

### Expected result
It works

### Actual result
Fatal Error

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 4cd835a2f812254b9f9dfe16d638cc03b1d7df85<br /><br />Firefox: Modal Window open and closed.
Chrome: cmd+Click on "Versions" open Modal which stay open but Buttons (Rstore … Delete) don't work after Click on them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18679">issues.joomla.org/tracker/joomla-cms/18679</a>.</sub>

**Comment by mbabker** [comment]
This might work for history but it isn't portable.  The way getController is called by default it makes all of the existing config override logic just not work and I don't think we need to be overloading getController to repeat logic we're already running elsewhere (or move that logic into extended methods).

**Comment by wilsonge** [comment]
It depends what we want to do with the Application object. It's not exactly the most sustainable thing to create an admin app instance i guess. There are various ways to make this more pretty from a method overriding perspective

**Comment by mbabker** [comment]
AFAIK you don't need to have an admin app instance to make it work right (we aren't doing that now in the proxies).  The issue we have is getController is called without passing a client argument by default so it's resolving to the active app to generate namespaces, and in these proxy cases we need to explicitly state admin client to get the namespaces right.

**Comment by wilsonge** [comment]
It's not just `getController` - it's also in the MVC factories

**Comment by mbabker** [comment]
Same root issue.  Without explicit client it resolves to active app.  Honestly it's a higher level problem than this because there's so much dependent on active app and we shouldn't have to inject another one to make things work.

**Comment by wilsonge** [comment]
Which is why i said earlier 

> It depends what we want to do with the Application object

**Comment by brianteeman** [comment]
closed see #21208

**Pull request closed without merging**
