### PR TITLE
[4.0] Preview button translated twice

### PR DESCRIPTION
**Pull request by hardik-codes**
### Summary of Changes
Correcting double translation of the `Preview` button`

### Testing Instructions
In the articles overview, open any article

### Expected result
See the ```Preview``` button in the toolbar buttons
untranslated2

### Actual result
untranslated1

### Documentation Changes Required
None

### CODE REVIEW

**Comment by hardik-codes** [comment]
@infograf768 thanks

**Comment by hardik-codes** [comment]
Members please test this PR.

**Comment by infograf768** [comment]
In fact, it is translated, but twice...
pr solves that

**Comment by ghost** [comment]
@hardik-codes can you please correct Title according Comment above?

**Comment by hardik-codes** [comment]
> @hardik-codes can you please correct Title according Comment above?

which comment are you referring to @franz-wohlkoenig ?

**Comment by ghost** [comment]
https://github.com/joomla/joomla-cms/pull/24173#issuecomment-472152578

As far as i understood its not about "Preview button is now translated" its about "In fact, it is translated, but twice..."

**Comment by infograf768** [comment]
Corrected title and description

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e261db46bc6315c7e237c38860a5590fd8dd41ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24173">issues.joomla.org/tracker/joomla-cms/24173</a>.</sub>

**Comment by hardik-codes** [comment]
@franz-wohlkoenig please test this PR

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e261db46bc6315c7e237c38860a5590fd8dd41ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24173">issues.joomla.org/tracker/joomla-cms/24173</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24173">issues.joomla.org/tracker/joomla-cms/24173</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
