### PR TITLE
Do not distribute default_ftp.php

### PR DESCRIPTION
**Pull request by PhilETaylor**
This is a file Joomla doesn't need to be distributing as it deletes it immediately after installing anyway

Part of #22219

### CODE REVIEW

**Comment by brianteeman** [comment]
Are you sure its not an error in https://github.com/joomla/joomla-cms/pull/20564 that the file is being removed

**Comment by PhilETaylor** [comment]
It's an override. Tell me what it's overriding in [this folder](https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_languages/views/installed/tmpl). There is your answer.

**Comment by mbabker** [comment]
It's still used by the override of the `default.php` file, see [here](https://github.com/joomla/joomla-cms/blob/4b6a8076991b6218d84b6c7a67040369072b2dbc/administrator/templates/hathor/html/com_languages/installed/default.php#L47-L49).

So yes, it's a mistake it's in the delete array.

**Comment by PhilETaylor** [comment]
Awesome.

**Comment by brianteeman** [comment]
I see @mbabker beat me too it

**Pull request closed without merging**
