### PR TITLE
Cassiopeia template - changing Tagline to Description - Optional text to show as a subheading parameter

### PR DESCRIPTION
**Pull request by PhocaCz**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35719

### Summary of Changes

Change the name of the parameter and add its description, as it was usual in Joomla 3. "Tagline" is replaced by "Description" and the description "Optional text to show as a subheading" is added.

img

### Testing Instructions

Go to Cassiopeia template options and see the parameter "Tagline" (before applying this PR) and "Description - Optional text to show as a subheading" (after applying this PR)

### Actual result BEFORE applying this Pull Request

"Tagline" displayed

### Expected result AFTER applying this Pull Request

"Description - Optional text to show as a subheading"

### CODE REVIEW

**Comment by brianteeman** [comment]
I'm fine with the change to add the description but tagline should stay. Its not a description of anything. Tagline is the correct english for what this does.

**Comment by PhocaCz** [comment]
See alternative PR: https://github.com/joomla/joomla-cms/pull/35729

BTW, I think the word "description" in this case was seen as some sort of short description of the entire page appearing below the logo/title. That's probably how it was perceived in Joomla 3. This should be seen in the context of the whole CMS, where the word "description" is an established term.

**Comment by ChristineWk** [comment]
After applying the patch, response: The patch could not be applied because the repository is missing

Of course do not know which decision will be made. Whether tagline or description. In HTML / CSS, of course, is description.
See alternative PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35720">issues.joomla.org/tracker/joomla-cms/35720</a>.</sub>

**Comment by ceford** [comment]
Strapline? (British English) If this is about the Masthead.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35720">issues.joomla.org/tracker/joomla-cms/35720</a>.</sub>

**Comment by wilsonge** [comment]
Closing this as the alternative PR was merged. Thanks!

**Pull request closed without merging**
