### PR TITLE
[4.0] Fix mailto

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #15778.

### Summary of Changes
Currently Mailto component gives a 500 on use

### Testing Instructions
Go to an article with email dropdown

### Expected result
Email window opens

### Actual result
500 and the white screen issue in 15778 when 500 is fixed

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Changed Title to show its about 4.0.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1643e74b758350b015518d07326867c53ba95a47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16341">issues.joomla.org/tracker/joomla-cms/16341</a>.</sub>

**Review by C-Lodder — COMMENTED** [review]
Note to self: fix styling

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1643e74b758350b015518d07326867c53ba95a47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16341">issues.joomla.org/tracker/joomla-cms/16341</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
