### PR TITLE
[4.1] Fix usage of unset parent ID mapping when getting recursive access rules

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #36783 .

### Summary of Changes

Fix PHP notices ` Trying to get property 'rules' of non-object in /libraries/src/Access/Access.php on line 548` and ` Undefined offset: 33 in /libraries/src/Access/Access.php on line 553` caused by access to unset array element when recursive access rules are fetched.

### Testing Instructions

Not sure yet how to reproduce the issue. It might need a broken assets table.

The author of the issue was not really able to provide the necessary details on how it can be reproduced.

But maybe a code review would be sufficient.

### Actual result BEFORE applying this Pull Request

See issue #36783 .

### Expected result AFTER applying this Pull Request

None of these PHP notices mentioned in issue #36783 .

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by chmst** [comment]
I think the problem was caused by changing something in the database via phpmyadmin, such breaking the asset table. But could not reproduce the effect. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36786">issues.joomla.org/tracker/joomla-cms/36786</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 019abdb0cfafbc05f02beeb8140be5e883b4eda9<br /><br />Code review looks good, could not reproduce the described behaviour. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36786">issues.joomla.org/tracker/joomla-cms/36786</a>.</sub>

**Comment by Aman21591** [comment]
I have tested this item :white_check_mark: successfully on 019abdb0cfafbc05f02beeb8140be5e883b4eda9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36786">issues.joomla.org/tracker/joomla-cms/36786</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36786">issues.joomla.org/tracker/joomla-cms/36786</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
