### PR TITLE
Rapid Repair Fix: Restore browser detection

### PR DESCRIPTION
**Pull request by smz**
#### Description

This fixes a stupid, idiotic, moronic and whatever else mistake **I** introduced in #7055: browser detection was broken because in case of missing/wrong language cookie I'd set it to the default language instead of setting it to null and then let browser detection do its duty...

### CODE REVIEW

**Comment by smz** [comment]
@Bakual , @infograf768 :astonished:

Sorry, guys...

**Comment by smz** [comment]
This is not what I was wishing to do, but this must be done ASAP...

**Comment by infograf768** [comment]
@test
I confirm the issue and solution.

**Comment by smz** [comment]
@bakual, @infograf768  Thanks, and again my apologies...

**Pull request merged**
