### PR TITLE
[4.0] Swap Hide/Show and No/Yes switchers

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
For consistency with other switchers, swap the Hide/show and No/Yes.

### Testing Instructions
Code review

### Documentation Changes Required
none

### CODE REVIEW

**Review by C-Lodder — APPROVED** [review]

**Comment by C-Lodder** [comment]
Add `[4.0]` to title

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4489f1e978b02e4948d1672a3a4ca933faf07d72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19305">issues.joomla.org/tracker/joomla-cms/19305</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 4489f1e978b02e4948d1672a3a4ca933faf07d72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19305">issues.joomla.org/tracker/joomla-cms/19305</a>.</sub>

**Comment by Quy** [comment]
RTC

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
