### PR TITLE
[4.3] Admin modules and xtd-editor plugins

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Remove xtd-editors from the text area when used in an admin module eg the admin version of mod_custom as only the media plugin will actually work
fields -> fails as there is no context
articles, contacts and menus -> fail as they are generating frontend links but as they are absolute they will either 404 or 500 missing layout

### Testing Instructions
create a new administrator module of type custom
click on the cms-content button in the wysiwyg toolbar

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc00b9b6e4361d166dd44b8a2ed5c346be337197<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39834">issues.joomla.org/tracker/joomla-cms/39834</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dc00b9b6e4361d166dd44b8a2ed5c346be337197<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39834">issues.joomla.org/tracker/joomla-cms/39834</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39834">issues.joomla.org/tracker/joomla-cms/39834</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Pull request merged**
