### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #14660 #14635 

### Summary of Changes
tag teaser image was using the full image alt tag instead of the teaser alt tag
tag full image was not using the alt tag

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 482c97fa54c2be16b367d97dace5c893f9c6b608<br /><br />thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14665">issues.joomla.org/tracker/joomla-cms/14665</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman i have just fixed a space that was to much in that file with https://github.com/joomla/joomla-cms/pull/14665/commits/4f9fba89587ef2ffcd46aa3069c3a928ea234aef ;)

**Comment by brianteeman** [comment]
@tonypartridge can you test this one if you get a moment - I tested your tags PR ;)

**Comment by tonypartridge** [comment]
Hey Brian,

I have already tested this because I wrote a very similar fix with @wilsonge closed in favour of:
https://github.com/joomla/joomla-cms/pull/13906/files

However, yours resolves two issues so therefore trumps #13906 IMHO as it is more in-depth. 

I'll just double test now. then @wilsonge can merge this and close #13906 ?

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 4f9fba89587ef2ffcd46aa3069c3a928ea234aef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14665">issues.joomla.org/tracker/joomla-cms/14665</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @tonypartridge

**Comment by wilsonge** [comment]
Merged with two good tests (ignoring tobias' codestyle fix)

**Comment by tonypartridge** [comment]
@wilsonge my hero.

**Comment by zero-24** [comment]
@wilsonge why do you want to ignore me / my fix?

**Comment by wilsonge** [comment]
only for the sake of two good tests (because one was before and one was after your codestyle fix) :) your fix was good!

**Comment by zero-24** [comment]
Ah ok. I just was confused ;)

**Pull request merged**
