### PR TITLE
[4.1] template previews need size restrictions

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #35498

If a template developer supplies a template_thumbnail.jpg that is oversized then it _breaks_ the layout of the page.

## To Test
1. Delete media\templates\site\cassiopeia\images\template_thumbnail.png
2. Copy media\templates\site\cassiopeia\images\template_preview.png to template_thumbnail.png
3. Visit administrator/index.php?option=com_templates&view=templates&client_id=0 and you will see the oversized image
4. Apply this pr (and `npm run build:css` or use a prebuilt package
5. Visit the url in step 3 and you will see the image displayed resized to fit the column

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab7b8ce722709b0b1c72d71466673210204d7b61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36946">issues.joomla.org/tracker/joomla-cms/36946</a>.</sub>

**Comment by jwaisner** [comment]
@brianteeman , can you please sync this PR to the latest branch?

**Comment by brianteeman** [comment]
@jwaisner there is no need to do that unless there are conflicts which there are not

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on ab7b8ce722709b0b1c72d71466673210204d7b61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36946">issues.joomla.org/tracker/joomla-cms/36946</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36946">issues.joomla.org/tracker/joomla-cms/36946</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
