### PR TITLE
Plugin Installation

### PR DESCRIPTION
**Pull request by wnnz34**
# Introduction

This joomla extension gives the user in the installation Modus in joomla to choose the functionality he or she wants to use for the installation.
These following plugins: urlFolderInstaller and packageInstaller are plugins which have the same functionalities as Install from url, install from folder path and upload from package. urlFolderInstaller Plugin allow the user not only to install from a path folder, but also from an url. And PackageInstaller allow the user to install from an extension file (zip Package).These plugin can also be disabled so that the user can just use what she or he wants to use. The advantage of this Solution is the flexibility of the User.
# Fix

After the installation, the plugin have to be  already in Extension / Manage enabled. There is only 2 columns installation: Install from url or path folder functionalities of the plugin urlFolderInstaller  and upload from package File functionality of packageInstaller plugin.
# How to test it.
- Login as Administrator
- Go to Extension / Manage:
- Install a plugin by entering an url or folder path in Install from url or folder.
- Check and test.
- Install a Plugin from package zip
- Check and test
- Disable one of the Plugin in Extension / plugins:
  Enter the name and search for the plugin you want to disable in the installation Modus (urlFolderInstaller or packageInstaller)
- Disable one of the plugin and test the remaining plugin installation
- Check the ordering
  Extension / plugin and search for the plugin -> and test the ordering by choosing a position and save.
- Go to Extension / manage and check the position of the Plugin you just changed the ordering position.

worked as a group on that issue: @icampus , @Mpompejus , @G-Lu

### CODE REVIEW

**Comment by infograf768** [comment]
What are these German and French ini files doing here?

**Comment by roland-d** [comment]
I think it is a mistake in the commit :)

**Comment by wnnz34** [comment]
infograf768 this is in for the translation in case the user is using joomla in French or German.

**Comment by wnnz34** [comment]
@infograf768  what do you mean ?

**Comment by Wolf-Rost** [comment]
I removed the unnecessary language folders from the plugins. Everything should be fine now. :)

**Comment by wnnz34** [comment]
@zero-24 we have hier All checks failed ...

**Comment by roland-d** [comment]
@Wolf-Rost There are conflicts, can you check please?

**Comment by Wolf-Rost** [comment]
The conflicts are solved. Feel free to test it now. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by zero-24** [comment]
@Wolf-Rost and @wnnz34 i have just add a new PR that fixes the lang file load issue see: https://github.com/wnnz34/joomla-cms/pull/3

For testing it looks good but we need to do 2 things more to make this happen.

- Add the new plugins to the script.php (com_admin)
- Add Update SQL (com_admin)

A very importand point is that both plugins should be enabled by default and on updating (e.g. via script or SQL update files)

An Improvmend could be maybe to send a message if there are no installer plugins enabled to tell the user something like:

`You have no installer plugin enabled. To be able install extensions you need to enable atleast on Plugin of the type installer.`

**Comment by wnnz34** [comment]
@zero-24 we could make the both plugin enabled by changing some values in the SQL  in folder Installation so that it would be enabled by default.
Some checks have failes aigain by Merging.. please check it...

**Comment by wnnz34** [comment]
@zero-24  All checks have Failed

**Comment by zero-24** [comment]
The travis checks errored because a upstream domain is down where we get on component fpr the tests. The tests fail only on two php versions so if that domain comes back we can restart the build ans they will pass :)

**Comment by brianteeman** [comment]
I have restarted Travis<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by zero-24** [comment]
Thanks @brianteeman @wnnz34 can you fix the merge  conflicts here?

**Comment by Wolf-Rost** [comment]
I fixed the merge conflicts.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on c7a4be4f4b1a85667e1db64687df6e63fd785208<br /><br />After applying this patch in Joomla! 3.5.0-beta  — staging 2016-01-17 go to Extensions > Manage > Install.
No tabulators, no search tools, no way to install something.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c7a4be4f4b1a85667e1db64687df6e63fd785208<br /><br />Took me a while to work out what this PR is trying to do so I will write down my findings to help others.

1. In the Joomla installer (administrator/index.php?option=com_installer) we currently have three tabs 
Upload Package File
Install from Folder
Install from URL
or 4 if you have the install from web plugin

This PR combines Install from Folder and Install from URL into a single tab so there are only two tabs
Install from URL or Path Folder
Upload Package File
or 3 if you have the install from web plugin


2. This PR then moves control of those tabs to their own plugins just like the install from web plugin
This means that as a site admin you are able to disable one or other or even both



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by brianteeman** [comment]
[NOTE] This PR can not be tested with com_patchtester so you will either need to use git or you can download a complete joomla install with this PR applied from https://github.com/wnnz34/joomla-cms/archive/staging.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by AnneKlapwijk** [comment]
I have tested this item :white_check_mark: successfully on c7a4be4f4b1a85667e1db64687df6e63fd785208<br /><br />To test this I used this [install package](https://github.com/wnnz34/joomla-cms/archive/staging.zip) (thanks @brianteeman for the helpful comments).

I was able to:
* install an extension by uploading a zip file
* install an extension by URL
* disable any tabs (Package File and URL or Path Folder)
* order the 2 tabs (go to _Extensions > Plugins_, sort by column and drag the plugins in the desired order)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by roland-d** [comment]
@wnnz34 @Wolf-Rost Please update this PR so the conflicts are resolved.

**Comment by brianteeman** [comment]
Setting to Needs Review so the CMS Maintainers can make a decision<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by roland-d** [comment]
I have spoken to @Wolf-Rost he is going to fix this PR.

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on c7a4be4f4b1a85667e1db64687df6e63fd785208<br /><br />Thank you for the improvement!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8201">issues.joomla.org/joomla-cms/8201</a>.</sub>

**Comment by roland-d** [comment]
Thank you everybody for your participation. PR has been merged.

**Pull request merged**
