### PR TITLE
TinyMCE: allow to edit image title in “Insert/Edit Image” Dialogue

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #13818 .

### Summary of Changes
allow to edit Image title in TinyMCE “Insert/Edit Image” Dialogue

### Testing Instructions
please see #13818

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3df93d52c157a522f6b82671ab9be832ead80c84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13833">issues.joomla.org/tracker/joomla-cms/13833</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3df93d52c157a522f6b82671ab9be832ead80c84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13833">issues.joomla.org/tracker/joomla-cms/13833</a>.</sub>

**Comment by infograf768** [comment]
RTC.

@rdeutz Can be merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13833">issues.joomla.org/tracker/joomla-cms/13833</a>.</sub>

**Comment by AlexRed** [comment]
Please also enable by default "Advanced Image" parameter for Administrator, to set the margin in the image in TinyMCE “Insert/Edit Image” Dialogue

**Pull request merged**
