### PR TITLE
Use HTML 5 input attributes when possible

### PR DESCRIPTION
**Pull request by larsgrefer**
Using the HTML 5 placeholder attribute for the search box when possible and setting the type attribute to 'search' instead of 'text'

### CODE REVIEW

**Comment by nternetinspired** [comment]
:clap: 

Good improvement @larsgrefer. Thanks.

**Comment by zero-24** [comment]
@larsgrefer i have send you a CS PR against your branche.

@nternetinspired did you a test or code review? If it is a test can you add it here? http://issues.joomla.org/tracker/joomla-cms/5453

Thanks to both here!

**Comment by zero-24** [comment]
@larsgrefer can you check `Chorme` I think it supports it also atm we don't use `placeholder` for chrome.

**Comment by zero-24** [comment]
@test patch works for IE 11 (atm i have no FF or Opera here)

**Comment by zero-24** [comment]
i will mark it successful if we have a review for chrome :smile:

**Comment by zero-24** [comment]
Chorme supports it: http://caniuse.com/#feat=input-placeholder

Can you add it to the check? maybe also `Safari`?

**Comment by zero-24** [comment]
@larsgrefer i have just add a patch to add safari and chrome.
https://github.com/larsgrefer/joomla-cms/pull/2

If we get this in i can mark the successful test. Thanks!

**Comment by nternetinspired** [comment]
@test successful, placeholder element used and shown in:

Chrome (OSX): 39.0.2171.99
Safari: 7.1.2 (9537.85.11.5)

**Comment by larsgrefer** [comment]
@zero-24 according to http://caniuse.com/#feat=input-placeholder Chrome supports the placeholder attribute since version 4 (January 2010) and Safari since version 5 (june 2010)

I thought it's not necessary to consider browsers which support the attribute for such a long time.

if we should consider them please check your patch larsgrefer#2 to use the correct versions, then il merge it into this pull-request

**Comment by zero-24** [comment]
Thanks @larsgrefer moving this here to RTC since it is tested by me and @nternetinspired <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5453">issues.joomla.org/joomla-cms/5453</a>.</sub>

**Pull request closed without merging**
