### PR TITLE
[4.3]Update template-rtl.scss

### PR DESCRIPTION
**Pull request by brianteeman**
Addresses the concern elsewhere that it was not obvious that the file was being used and could not be deleted

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 53630bc46b92e579b3e97645e5fd976c9ba39168<br /><br />By review with knowledge of the changes from PR #38412 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39384">issues.joomla.org/tracker/joomla-cms/39384</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 53630bc46b92e579b3e97645e5fd976c9ba39168<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39384">issues.joomla.org/tracker/joomla-cms/39384</a>.</sub>

**Comment by richard67** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39384">issues.joomla.org/tracker/joomla-cms/39384</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brian @brianteeman !

**Comment by brianteeman** [comment]
thx

**Pull request merged**
