### PR TITLE
Remove log as requested by @mbabker

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #14557

### Summary of Changes

Remove the log message as requested

### Testing Instructions

Review

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by mbabker** [comment]
Can you mark the strings deprecated in the language files too?  That way we aren't coming back in 4 years trying to figure out where they're used and they might actually get deleted with 4.0.

**Comment by zero-24** [comment]
Something like this? Is this understandable?

**Comment by mbabker** [comment]
That works.

**Comment by brianteeman** [comment]
It is understandable but not consistent with other notices

> ; The following five strings are deprecated and will be removed with 4.0. They generate wrong plural detection in Crowdin.
do


So just do

> ; The following two strings are deprecated and will be removed with 4.0

**Comment by zero-24** [comment]
Done thanks.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 212aad1ac990fa6d41b515550646ff80a8eeff0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14576">issues.joomla.org/tracker/joomla-cms/14576</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 212aad1ac990fa6d41b515550646ff80a8eeff0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14576">issues.joomla.org/tracker/joomla-cms/14576</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by gwsdesk** [comment]
I have tested this item ✅ successfully on [212aad1](https://github.com/joomla/joomla-cms/commit/212aad1ac990fa6d41b515550646ff80a8eeff0b "https://github.com/joomla/joomla-cms/commit/212aad1ac990fa6d41b515550646ff80a8eeff0b")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14576">issues.joomla.org/tracker/joomla-cms/14576</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14576">issues.joomla.org/tracker/joomla-cms/14576</a>.</sub>

**Pull request merged**
