### PR TITLE
Add possibility to load view tmpl with own layouts

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
At the moment it's very complicated to define a default sublayout which can be loaded by different layouts. For example let's assume you have a calendar view with three layouts: month, week, year and the following structure

```
|- views
    |- calendar
        |- tmpl
            |- month.php
            |- week.php
            |- year.php
            |- year_myfunnystuff.php
```
I can call the three layouts with the parameter &view=calendar&layout=week/month/year. But now if I want to load "myfunnystuff" in all other layouts I have to do the following:
year: ```$this->loadTemplate('myfunnystuff');```
month: ```$this->setLayout('year');$this->loadTemplate('myfunnystuff');$this->setLayout('month');```
week: ```$this->setLayout('year');$this->loadTemplate('myfunnystuff');$this->setLayout('week');```

After this patch it's much more easier:
year: ```$this->loadTemplate('myfunnystuff');```
month: ```$this->loadTemplate('myfunnystuff', 'year');```
week: ```$this->loadTemplate('myfunnystuff', 'year');```

### Testing Instructions
try to create structures like above and load it.

### CODE REVIEW

**Comment by Bakual** [comment]
If you name your sublayout `default_myfunnystuff.php`, you can load it using `$this->loadTemplate('myfunnystuff') from any layout. The function has a fallback to "default_" prefix in case a layout specifc file (eg year_myfunnystuff.php) doesn't exist.

**Comment by brianteeman** [comment]
So there is no need for this PR and it can be closed?

**Comment by laoneo** [comment]
That's actually very useful and shouldn't be closed.

@Bakual this pr solves a different use case. The issue is when you want to use a sublayout of a different layout, then you need to do the hack @bembelimen has described in the description or you need to copy it. You can even go further and load one template in another with this patch.

**Comment by Bakual** [comment]
The PR description starts with:

> At the moment it's very complicated to define a default sublayout which can be loaded by different layouts. 

Just name the default sublaout `default_foo` and it will work. That's exactly the usecase for that feature that already exists.

> The issue is when you want to use a sublayout of a different layout

That would be a different usecase, and honestly I'd say it's a hack if you call a sublayout from another layout. Just name that sublayout with a prefix "default_" if you're going to use it in multiple layouts.

**Comment by bembelimen** [comment]
Closed in favor of: #21228

**Comment by fatmaakay** [comment]
I have tested this item :white_check_mark: successfully on 3a119085dc467d8db13db68d29686c614e6c5a0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14251">issues.joomla.org/tracker/joomla-cms/14251</a>.</sub>

**Comment by ghost** [comment]
@fatmaakay thanks for testing but this PR is closed.

**Comment by bembelimen** [comment]
@fatmaakay could you please test here: https://github.com/joomla/joomla-cms/pull/21228

**Pull request closed without merging**
