### PR TITLE
[4.0] Namespace from 3.9.4

### PR DESCRIPTION
**Pull request by brianteeman**
Namespace an error message introduced with the merge of 3.9.4 #25219

Code review should be enough

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 99169d19202933054107e22e1801712a8f10b1d7<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25221">issues.joomla.org/tracker/joomla-cms/25221</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 99169d19202933054107e22e1801712a8f10b1d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25221">issues.joomla.org/tracker/joomla-cms/25221</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25221">issues.joomla.org/tracker/joomla-cms/25221</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
