### PR TITLE
[4.0]Remove manifest files and use existing XML info

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
This is the first (in hopefully a series) of a cleanup of the Installer classes in Joomla 4, with the aim to make extension installs much more consistent and the classes more manageable.

### Testing Instructions
Ensure installing libraries and packages is unchanged from the current state in 4.x

### Documentation Changes Required
Classes removed.

### Additional Notes
If this works after testing then of course the relevant deprecations must be made in 3.x but I'm not 100% confident of these changes (it feels far too easy) so I want some tests from others first.

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by brianteeman** [comment]
updated the title to show it is for J4

**Comment by laoneo** [comment]
I guess you need to first merge #15884 into the 4.0-dev branch, otherwise you will probably get merge conflicts.

**Comment by wilsonge** [comment]
For sure. As I said I just want testing because I can't believe I can delete this much code for adding an extra 5 lines into 2 files......

**Comment by wilsonge** [comment]
Rebased with the #15884 in 4.0 - can i please have some testing :)

**Comment by C-Lodder** [comment]
Tried installing extensions from Regular Labs and Akeeba....both of which are returning an alerted `Internal Error`.

**Comment by wilsonge** [comment]
@C-Lodder your test hit a bug fixed by Michael with #16300 - now I've rebased this it should work :)

**Comment by brianteeman** [comment]
@wilsonge can you resolve conflicts please so this can be tested

**Comment by wilsonge** [comment]
Forgot this was still open - me and Michael found a problem which meant (as is) this can't work for packages. I'll sit down and try again another day

**Comment by brianteeman** [comment]
ok thanks

**Comment by brianteeman** [comment]
Can you check your other open issues - maybe the same is true for some of them as well https://github.com/joomla/joomla-cms/pulls/wilsonge

**Pull request closed without merging**
