### PR TITLE
[4.0] Password eye button

### PR DESCRIPTION
**Pull request by brianteeman**
Changed the class in the layout and the js

### Result
password

### Testing Instructions
Cannot be tested with patchtester
You can try (if I did it correctly to install a complete install here https://github.com/brianteeman/joomla-cms/archive/password-eye-temp.zip)

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@brianteeman shouldn't we just finish https://github.com/joomla/joomla-cms/pull/19231 instead?

**Comment by brianteeman** [comment]
yes - tbh I didnt spot that one until after i did this

its been bugging me that it looks so awful as it is and from the todo list on the other pr it will be quite a while before that one is ready

**Comment by wilsonge** [comment]
This is fine for now :)

**Comment by brianteeman** [comment]
thanks - I wont need to groan each time I install now :)

**Pull request merged**
