### PR TITLE
[5.1] Use Dialog for Plugin editing

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Use Dialog for Plugin editing modals.
Similar to https://github.com/joomla/joomla-cms/pull/42423

### Testing Instructions
Run `npm install`.
Disable plugins:
Content - Smart Search
System - Redirect

Visit Finder Index overview, you should see a message about disable pplugin, with link to edit it. Try to use it for change plugin state.

Visit Redirects overview, you should see a message about disable pplugin, with link to edit it. Try to use it for change plugin state.

### Actual result BEFORE applying this Pull Request
Works with BS modal

### Expected result AFTER applying this Pull Request
Works with Joomla Dialog

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/208
- [ ] No documentation changes for manual.joomla.org needed

References:
- https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 974f5959b17d7db4c1751104e8db61cc164af644<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42447">issues.joomla.org/tracker/joomla-cms/42447</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 974f5959b17d7db4c1751104e8db61cc164af644<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42447">issues.joomla.org/tracker/joomla-cms/42447</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42447">issues.joomla.org/tracker/joomla-cms/42447</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and also for testing @Quy @viocassel

**Comment by brianteeman** [comment]
This is completely wrong - at least for the redirects. It stops checking if the plugin is enabled or disabled. it only checks if the plugin is installed

**Pull request merged**
