### PR TITLE
Update default_results.php

### PR DESCRIPTION
**Pull request by diddipoeler**
display images in search results

Pull Request for Issue # .

### CODE REVIEW

**Comment by Quy** [comment]
Please follow [Joomla Coding Standards](https://developer.joomla.org/coding-standards/php-code.html).

**Comment by C-Lodder** [comment]
Please also refrain from using inline CSS. We have LESS files

**Comment by diddipoeler** [comment]
is the code better now ?

**Comment by C-Lodder** [comment]
@diddipoeler - unfortunately not:

- You're not using indentation
- You're still using inline styling
- You're using uppercase for `<?PHP`. It should be lowercase

**Comment by diddipoeler** [comment]
@C-Lodder 
write an example please.

**Comment by C-Lodder** [comment]
@diddipoeler - examples are cleared stated on the [Joomla Coding Standards](https://developer.joomla.org/coding-standards/php-code.html) page

**Comment by infograf768** [comment]
Keeping inline style for the moment, this should be
```
	<?php // display images in search results ?>
	<?php if (isset($result->image)) : ?>
		<?php $image = json_decode($result->image); ?>
		<?php $result->picture = $image->image_intro; ?>
	<?php endif; ?>
	<?php if (isset($result->picture) && $result->picture != '') : ?>
		<div style="float: left;margin: 0px 0px;"><img src="<?php $this->escape($result->picture); ?>" width="50" alt="" /></div>
	<?php endif; ?>
```

But, first, could you give an example of how this works please.? 
Give detailed test instructions and screenshots.

**Comment by infograf768** [comment]
@diddipoeler If no reply to our questions, we will close this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18236">issues.joomla.org/tracker/joomla-cms/18236</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.

**Pull request closed without merging**
