### PR TITLE
[4.0] A11y select target associations

### PR DESCRIPTION
**Pull request by brianteeman**
image

#### Issue
`Form elements must have labels` ([label](https://dequeuniversity.com/rules/axe/3.3/label?application=msftAI))
#### Target application
[Multilingual Associations: Edit Associations (Articles > Articles) - 4.0 Test Site - Administration](http://localhost/joomla-cms/administrator/index.php?option=com_associations&view=association&layout=edit&itemtype=com_content.article&task=association.edit&id=28)
#### Element path
#jform_itemlanguage
#### Snippet
`<select id="jform_itemlanguage" name="jform[itemlanguage]" class="custom-select">`

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0fba76ddba4ab7b9908b57ba293770fb5a846d86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27397">issues.joomla.org/tracker/joomla-cms/27397</a>.</sub>

**Comment by Quy** [comment]
Under Articles, here is one filter where `- Select Featured -` is in both places. Can we use `COM_ASSOCIATIONS_SELECT_TARGET_LANGUAGE` and not create a new one?

```
<div class="js-stools-field-filter">
				<span class="sr-only"><label id="filter_featured-lbl" for="filter_featured">
	- Select Featured -</label>
</span>
				<select id="filter_featured" name="filter[featured]" class="custom-select" onchange="this.form.submit();">
	<option value="" selected="selected">- Select Featured -</option>
			</div>
```

**Comment by brianteeman** [comment]
The strings are not the same

**Comment by Quy** [comment]
If that is the case, then the filters in Articles should be changed.
```
Select Featured (label)
- Select Featured - (dropdown)
```

**Comment by brianteeman** [comment]
I was lazy when I did that

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0fba76ddba4ab7b9908b57ba293770fb5a846d86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27397">issues.joomla.org/tracker/joomla-cms/27397</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27397">issues.joomla.org/tracker/joomla-cms/27397</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
