### PR TITLE
[5.2] Shorten com_content search description

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
The sentence is wron "use a or b or c to search for content checked out by a specified user".
Shortening the description for the search input field in com_content also is a partial solution for #44086.

### Testing Instructions
see #44086 and compare the tooltip before and after patch.

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
For me the text is wrong. We do not use ID: or AUTHOR:  or CHECKEDOUT: to get the articles checked out by a user. 

We use ID: to get articles by ID, AUTHOR to get articles written by an author or CHECKEDOUT to get articles checked out by a user.

The length is only a side effect.

**Comment by brianteeman** [comment]
> For me the text is wrong. We do not use ID: or AUTHOR: or CHECKEDOUT: to get the articles checked out by a user.
> 

Read the actual text not the text that you can see in your screenshot
https://github.com/joomla/joomla-cms/blob/74c81e6e776e088c62a4052b80081568ce4ddc7b/administrator/language/en-GB/com_content.ini#L109

**Comment by chmst** [comment]
Aplogies, I had a wrong com_content.ini in my test environment. Agree with css for tooltip.

**Comment by richard67** [comment]
So according to previous comment this PR can be closed. For the CSS a new one should be made.

@chmst If my understanding is wrong, feel free to reopen.

**Pull request closed without merging**
