### PR TITLE
hathor postinstall typos

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for typos introduced in Issue #15210

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @brianteeman

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7f507274708252eb33ddc55eda40116a9a5a0d33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15235">issues.joomla.org/tracker/joomla-cms/15235</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7f507274708252eb33ddc55eda40116a9a5a0d33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15235">issues.joomla.org/tracker/joomla-cms/15235</a>.</sub>

**Comment by infograf768** [comment]
RTC. For 3.7.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15235">issues.joomla.org/tracker/joomla-cms/15235</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
