### PR TITLE
Change email notification to use site from address (Fix #9261)

### LINKED ISSUE #9261: SMTP From address is not used with private messages
#### Steps to reproduce the issue

Configure the server global settings to use SMTP email and enter a value in the From address.
Use Components -> Messaging -> New Private Message to send a message from an admin with a different address to another user.
#### Expected result

User should receive an email to their configured email address that is from the SMTP from address with a reply-to reflecting the user email address who sent the message
#### Actual result

"SMTP Error: data not accepted" due to the fact that the SMTP server expects the From address to be on a local domain, but it was using the sender's email address instead. See http://joomla.stackexchange.com/questions/15444/smtp-email-failing-via-joomla-succeeding-outside-of-joomla
#### System information (as much as possible)

Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Dreamhost web host
PHP version 5.5.26
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
SMTP configuration...
Send Mail: Yes
Mailer: SMTP
From email: bluemonkmn@sgdk2.enigmadream.com
From name: Benjamin Marty
Disable Mass Mail: No
SMTP Authentication: Yes
SMTP Security: None
SMTP Port: 25
SMTP Username: bluemonkmn@sgdk2.enigmadream.com
SMTP Password: (same password I used in other tests that worked)
SMTP Host: mail.sgdk2.enigmadream.com
#### Additional comments

The same test succeeds if I change the sending user's email address to match the SMTP From address.
It's not clear if this problem extends beyond private messages. that's just the easiest way I know how to test Joomla email.

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #9261

### Summary of Changes

The email notification sent when sending a private message uses the "from" user's email address as the sender which can cause some sending failures (see referenced issue for examples).  This changes the process to set the "from" user as the reply-to address instead.

As well, proper error checks will be made when setting the reply-to and recipient addresses and the message will not be sent if this step fails.  Additionally, a message will be displayed if sending 

Concurrent with https://github.com/joomla/joomla-cms/pull/13504 the log statements are wrapped in try/catch.

### Testing Instructions

Pre-patch, an email message sent via the "Private Message" feature of com_messages will have the "from" address set as the sending user.  Post-patch, the message will use the site's configured from address with the sending user set as the reply-to address.

### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on db2e207c2cf9f0fa570e55ad0ab135ab972fb9e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13518">issues.joomla.org/tracker/joomla-cms/13518</a>.</sub>

**Comment by brianteeman** [comment]
As pointed out in #16107 the site email address is not a required or a validated field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13518">issues.joomla.org/tracker/joomla-cms/13518</a>.</sub>

**Comment by mbabker** [comment]
Still a better option than potentially spoofing someone's email address as if it's configured properly that would be valid data from the site owner.

**Comment by brianteeman** [comment]
i agree i was just pointing it out and that with this PR there is even more reason to merge #16107

**Comment by Quy** [comment]
Somewhat related: Our forms were setup to use the user's email for the FROM, and got bounced/rejected:
> 550 5.1.0 ###.####.####.### is not allowed to send from <example.com> per it's SPF Record. Please inspect your SPF settings, and try again. IB508 <http://x.co/srbounce>

Now the FROM is set to use the site's email and Reply-to is the user's email.

**Comment by Quy** [comment]
Why do need to include REPLY-TO? The email notification is generic. There is no context to the message to know what reply to. 
```
Subject: A new private message has arrived from Acme Corp
Message:
Please log in to http://www.example.com/administrator/index.php?option=com_messages&view=message&message_id=2 to read your message.
```

**Comment by brianteeman** [comment]
@quy you are probably correct but I guess someone could be overriding the message

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on db2e207c2cf9f0fa570e55ad0ab135ab972fb9e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13518">issues.joomla.org/tracker/joomla-cms/13518</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
