### PR TITLE
[4.1] Fire change events consistently on the media Field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #37640 .

### Summary of Changes

- Call the Custom Element function setValue instead of manually updating the value

### Testing Instructions

- Edit an article and go to the images tab
- Open the inspector and inspect the intro image input (the one left to the select button bellow the image)
- type in the browser's console `$0.addEventListener('change', (e) => console.log(e))`
- Select an image, check that a change event was recorded in the console
- Clear the field, check the recorded event
- Select another image and check that the event was recorded again

### Actual result BEFORE applying this Pull Request

No event on image selection

### Documentation Changes Required

No this is a bug

### CODE REVIEW

**Comment by laoneo** [comment]
Can you rebase this to 4.2?

**Comment by dgrammatiko** [comment]
So 4.1 and 4.2 are not in sync? @laoneo

**Comment by richard67** [comment]
@dgrammatiko I think the problem with the branch sync will be solved after the next upmerge from 4.1-dev to 4.2-dev and then update of the branch of this PR to 4.2-dev. As there is an alpha-2 release scheduled for tomorrow, I assume the upmerge will happen just after that.

**Comment by dgrammatiko** [comment]
@richard67 sure but I have no clue why this small bug fix needs to wait few months in order to be (potentially) merged. It's not very helpful for those devs that have a problem with the field right now. Anyways, not my call, just seems not very dev friendly approach

**Comment by richard67** [comment]
> @richard67 sure but I have no clue why this small bug fix needs to wait few months in order to be (potentially) merged.

@dgrammatiko Maybe you misunderstood or I explained wrong. Tomorrow is 4.2 alpha-2 and after that the upmerge, so your PR can be tested and RTC'ed on the day after tomorrow, I would think.

**Comment by richard67** [comment]
@dgrammatiko P.S. Ah .. you mean the rebase decision? Well I don't know why that was made. @laoneo ?

**Comment by richard67** [comment]
@laoneo To me this PR seems to be a bug fix, so I don't see why it should go into 4.2. What am I missing?

**Comment by dgrammatiko** [comment]
@richard67 this should be already fixed for 4.2 with https://github.com/joomla/joomla-cms/pull/37654, so this isn’t needed anymore

**Comment by richard67** [comment]
@dgrammatiko Thanks.

**Comment by dgrammatiko** [comment]
Unless the fix is ok for 4.1, then I can redo this PR (2 lines or whatever)

**Comment by richard67** [comment]
> Unless the fix is ok for 4.1, then I can redo this PR (2 lines or whatever)

@bembelimen I think that's on you to decide.

**Comment by dgrammatiko** [comment]
So I redid it in #37702, feel free to close the PR if 4.2 is fine

**Pull request closed without merging**
