### PR TITLE
[4] remove J prefixed class names

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 88a05985144faa4c7ff56a699e3f079f04acbcb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34017">issues.joomla.org/tracker/joomla-cms/34017</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 88a05985144faa4c7ff56a699e3f079f04acbcb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34017">issues.joomla.org/tracker/joomla-cms/34017</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34017">issues.joomla.org/tracker/joomla-cms/34017</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
