### PR TITLE
[4.0] Remove markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove erroneous markup.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d58d05294650567fe090d5360fd96797b1d740b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26305">issues.joomla.org/tracker/joomla-cms/26305</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on d58d05294650567fe090d5360fd96797b1d740b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26305">issues.joomla.org/tracker/joomla-cms/26305</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26305">issues.joomla.org/tracker/joomla-cms/26305</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
