### PR TITLE
[5.0] Chore/disable polyfill php 7.0 - 8.1

### PR DESCRIPTION
**Pull request by HLeithner**
We don't need the symfony polyfills for php < 8.2 since the php minimum requirement is 8.1

This PR is based on #40292

### CODE REVIEW

**Comment by brianteeman** [comment]
121 changed files ?

**Comment by HLeithner** [comment]
> 121 changed files ?

as description said it's based on #40292 (the upmerge) which will be merged when the ci is ready

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/40287#issuecomment-1493262929

The changes look ok but please - one commit per issue. Nothing is really testable when you lump so many things into one pr

**Comment by HLeithner** [comment]
I try to reduce merge conflicts, pr based on other prs is a common case, and as soon as the other pr is merged this one get cleared automatically.

**Comment by brianteeman** [comment]
I dont see how there would have been a merge conflict - even so it makes the pr hard to review and thats why mistakes happen when there are so many changes

**Comment by HLeithner** [comment]
> I dont see how there would have been a merge conflict - even so it makes the pr hard to review and thats why mistakes happen when there are so many changes

do you understand it now? after merging the upmerge pr, this PR is clean and has only the commits related for this pr

**Comment by brianteeman** [comment]
I understood it before - I still dont think it is good practice.

Also due to language issues I read your comment "based on" to mean the code in this pr is _based on_ the same techniques in this other PR.

**Comment by richard67** [comment]
Was just preparing my tests.

**Comment by richard67** [comment]
Test was successful, PR solves the problem.

**Pull request merged**
