### PR TITLE
Fix the backend logout button issue

### PR DESCRIPTION
**Pull request by prakhar3062**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37109[](https://user-images.githubusercontent.com/82047120/156143888-5484a57c-8d46-40f0-8dd4-0f70a9d781fa.png)[](https://user-images.githubusercontent.com/82047120/156147977-a8c9326c-6127-4182-adfb-2d8887f7ac46.jpeg)

Summary of Changes
Put the logout button outside the dropdown menu.

Testing Instructions
After applying the patch, see the header of home page , you

Actual result BEFORE applying this Pull Request
68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39363334316334343432313938626239366230323562663934356465363136322e706e67

Expected result AFTER applying this Pull Request
Web capture_1-3-2022_153056_localhost

Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by richard67** [comment]
Would you please give this pull request a meaningful title telling what it solves? And of course that title should not provide false information. The issue was not a bug but a feature request. Maybe you should do a research about what the word „bug“ means in software business.

**Comment by prakhar3062** [comment]
> Would you please give this pull request a meaningful title telling what it solves? And of course that title should not provide false information. The issue was not a bug but a feature request. Maybe you should do a research about what the word „bug“ means in software business.

Okay i changed the title

**Comment by prakhar3062** [comment]
@richard67 i changed this file only administrator/templates/atum/html/mod_user/default.php

Other files are added by mistake.  hoping it will help you in reviewing

**Comment by richard67** [comment]
> @richard67 i changed this file only administrator/templates/atum/html/mod_user/default.php
> 
> Other files are added by mistake. hoping it will help you in reviewing

Sorry but with these unrelated changes this PR will not be accepted. You should get families with Git and GitHub.

**Comment by prakhar3062** [comment]
> > @richard67 i changed this file only administrator/templates/atum/html/mod_user/default.php
> > Other files are added by mistake. hoping it will help you in reviewing
> 
> Sorry but with these unrelated changes this PR will not be accepted. You should get families with Git and GitHub.

i think but it will not distrub the configration it is just the part of the administrator template

**Comment by richard67** [comment]
> > > @richard67 i changed this file only administrator/templates/atum/html/mod_user/default.php
> > > Other files are added by mistake. hoping it will help you in reviewing
> > 
> > 
> > Sorry but with these unrelated changes this PR will not be accepted. You should get families with Git and GitHub.
> 
> i think but it will not distrub the configration it is just the part of the administrator template

I think you don’t know what a pull request is. When it will be merged, all changes in it will be merged. So a pull trauest shall not make unrelated changes or add unrelated files.

It cannot be accepted as it is.

**Comment by prakhar3062** [comment]
> > > > @richard67 i changed this file only administrator/templates/atum/html/mod_user/default.php
> > > > Other files are added by mistake. hoping it will help you in reviewing
> > > 
> > > 
> > > Sorry but with these unrelated changes this PR will not be accepted. You should get families with Git and GitHub.
> > 
> > 
> > i think but it will not distrub the configration it is just the part of the administrator template
> 
> I think you don’t know what a pull request is. When it will be merged, all changes in it will be merged. So a pull trauest shall not make unrelated changes or add unrelated files.
> 
> It cannot be accepted as it is.

okay what if deleted these extra files and then commit

**Comment by prakhar3062** [comment]
@richard67 is it now okay

**Comment by richard67** [comment]
Now it is even worse because you have deleted files which were not added by accident but were modified by accident, so the deletion is again an u wanted change. You should be able to see that when checking the changed files of your pull request on GitHub. There you would see that it still shows 7 modified files.

**Comment by brianteeman** [comment]
As stated before the changes should not be in the form of an override!!

**Comment by rjharishabh** [comment]
I suggest you, first revert all the changes, then apply the changes you want and commit
OR Close this PR and then create a new PR

**Comment by prakhar3062** [comment]
> I suggest you, first revert all the changes, then apply the changes you want and commit OR Close this PR and then create a new PR

I revert the changes and commit again

**Pull request closed without merging**
