### PR TITLE
[4.0] Update joomla/console package and adapt code to changes

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

This PR updates the `joomla/console` package based on the last architectural update and adapts the classes within the CMS environment to those changes.  This PR also includes other minor updates to the service definition of the console application class.

Changes include:

- Update application constructor signature to match new structure
- Update all command classes to new structure
- Update console application service to use the defined `session.cli` service versus the inlined session service and to inject via constructor the dispatcher and container dependencies

### Testing Instructions

Apply this patch to a local installation and run `composer install` to pull the updated Composer dependencies.  Run `php cli/joomla.php <command>` to validate console runs, keeping https://github.com/joomla/joomla-cms/issues/23845 in mind and if necessary updating your environment.

### CODE REVIEW

**Comment by mbabker** [comment]
Not quite sure why I spent time on proper CLI support for an application that can't even properly support its non-HTML outputs.

**Comment by zero-24** [comment]
Can you please re-open this one. I havn't have time to look into all PRs but it seams i have missed this. Can you give this an seccond chance?

**Comment by zero-24** [comment]
Thanks Michael this is now on my personal to-do list. It might take some time but it will not be forgotten.

**Comment by dneukirchen** [comment]
I have tested this item :white_check_mark: successfully on e3266957c92d3963d86b8f00fce9ff3f0413facb<br /><br />I can confirm that this PR fixed the issue (needed to disable debug plugin as described). Thx michael. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23847">issues.joomla.org/tracker/joomla-cms/23847</a>.</sub>

bildschirmfoto 2019-02-20 um 11 03 27

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e3266957c92d3963d86b8f00fce9ff3f0413facb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23847">issues.joomla.org/tracker/joomla-cms/23847</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by zero-24** [comment]
Thanks for testing and merging guys 🎉 you just removed one item from my to-do list  :+1:

**Pull request merged**
