### PR TITLE
[4,0] #34942 fix

### PR DESCRIPTION
**Pull request by brianteeman**
Merged in haste.

This ensures it works in RTL

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 25d77a0f7319295021f4491b63e689a367a0fb52<br /><br />Code review only, but that should be sufficient here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34943">issues.joomla.org/tracker/joomla-cms/34943</a>.</sub>

**Comment by wilsonge** [comment]
Removed the dir=ltr because we don't have that in other places and technically if dir is absent it gives a fallback (not sure practically on our template if that can ever happen but better safe than sorry). It's probably technically the right thing - but if we do it here we should probably do it all over the shop rather than in this one place.

**Comment by brianteeman** [comment]
We do it the correct way like this in lots of places. Not happy you changed the pr and merged

**Comment by richard67** [comment]
I remember having seen both ways, so it seems we are not consistent with that.

**Comment by brianteeman** [comment]
yes - everything created by one person was done the wrong way or just shoved in a separate rtl file. Which is why there were so many bugs to fix as you don't know there is a need to update in other places. bad practice leads to bad code leads to more work.

</rant>

**Comment by wilsonge** [comment]
I just searched and we currently use dir=ltr in 3 places in all the SCSS twice in joomla-tab scss override and once in quickicons. I very specifically said that what you did is probably technically right - just it's not good to just add it to one more place - it should be done at once or not at all.

**Pull request merged**
