### PR TITLE
Update en-GB.tpl_beez3.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Same change as in language folder ini file

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f9aaab65852ee07e23ca4900b02b2ae9c85ca2ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Comment by brianteeman** [comment]
By adding the version number for joomla this fails the style guide for the use of the joomla name https://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Comment by aaleksanyants** [comment]
Thanks for pointing this out, changed to Joomla! 3.x

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on edb63f718719e051086e4a2011f0b41ad79a283a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Comment by brianteeman** [comment]
Contacted Angie as the creator of the template to confirm the html5 change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed with Angie Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8b16bdbfee071ddc8c81578cbd177c54664fe60a<br /><br />Only updated the branch to latest staging. All equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7364">issues.joomla.org/joomla-cms/7364</a>.</sub>

**Pull request merged**
