### PR TITLE
Space missing between attributes in xml.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes
Added a newline where one was missing.

### Testing Instructions
Open a page that reads `components/com_content/views/featured/tmpl/default.xml` (for example, a menu listing page in the admin which has a "featured articles" type on it). 

### Expected result
The page will render without issue.

### Actual result
Errors from attempting to parse bad xml.

### Documentation Changes Required
Nope.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
This seems like the kind of thing that could easily have been caught by an automated test. Isn't there an xml validator that can be run on all PRs?

**Comment by infograf768** [comment]
One of these has already been corrected
See https://github.com/joomla/joomla-cms/commit/15c4ccca3e56bac6765c65320621a4f075d2f260

**Comment by brianteeman** [comment]
@okonomiyaki3000 i wish there was or I wouldnt have spent a long time revieiwing every single xml file. Sorry that this one slipped through the net

**Comment by okonomiyaki3000** [comment]
@infograf768 OK, then this PR is not needed. 67 of these 68 changes are just my editor automatically removing white space from the end of lines. I don't know if there's any official policy about that. This project could add a `.editorconfig` file to specify editor behavior like that but that's just a convenience for anyone who uses the plugin. It's not really enforcing anything. 

@brianteeman I honestly have no idea what this means at all but it seems Travis can maybe validate xml i-akhmadullin/Sublime-CSS3@e2e6bd204bb909eb120725e17f059c0c1b76a2a3

**Comment by brianteeman** [comment]
i am going to close this one then as it was solved by JM elsewhere
spaces and validation arent the real issue with the xml it was getting all of them into a consistent style

**Pull request closed without merging**
