### PR TITLE
[4.1] Update Sites rebuild

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Tweak the language string to avoid any misunderstanding

### Testing Instructions
Go to the system update sites and click on rebuild

### Actual result BEFORE applying this Pull Request
old ambiguous message

### Expected result AFTER applying this Pull Request

new clearer message

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 68b0882a0ffd506e13b1dff6eb13950b3c89c6f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37617">issues.joomla.org/tracker/joomla-cms/37617</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8dc8b28f0a494ff8e21332dc1ee8be6304a7b337<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37617">issues.joomla.org/tracker/joomla-cms/37617</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37617">issues.joomla.org/tracker/joomla-cms/37617</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
