### PR TITLE
[4.4] com_scheduler - Update ExecutionRulesRule to validate custom cron expression correctly

### PR DESCRIPTION
**Pull request by n3t**
### Summary of Changes
Avoid fatal PHP error on saving Task with incorrect user input.

### Testing Instructions
Create new task in com_scheduler, select "Cron Expression (Advanced)" as "Execution Rule", do not choose any Minute, Hour, Day, Month or Day of Week in Cron Match section and save. Sames apply if you choose only some of these but not all.

### Actual result BEFORE applying this Pull Request
PHP Error 
`
Joomla\Component\Scheduler\Administrator\Model\TaskModel::wildcardIfMatch(): Argument #1 ($target) must be of type array, null given, called in ../administrator/components/com_scheduler/src/Model/TaskModel.php on line 637
`

### Expected result AFTER applying this Pull Request
Warning is raised, task not saved. User can correct input and save again.

### Additional info
Modified the Rule to reflect real cron expression rule type (it is not `custom` but `cron-expression`), plus added `required` for subsequent fields in validation.

Applies to Joomla 5 also.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Alternative PR #37536 using JavaScript.

**Comment by brianteeman** [comment]
@quy not an alternative but a requirted additional https://github.com/joomla/joomla-cms/pull/37536#issuecomment-1099124898

**Comment by n3t** [comment]
Seems both these PR could live together, #37536 is client side JS solution, this PR is server side solution.

**Comment by fgsw** [comment]
With PR only 3 fields are missing:

image

correct the missing fields 2 more fields are missing:

image

All missing fields should show at once.

**Comment by n3t** [comment]
This is Joomla standard, show only up to 3 errors and is caused directly by FormController. Doesn't have to do anything with this PR. I do not think we should override this behavior just for this use case...

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 54e89cff91758713821b92bf35d07b1fc22d71bf<br /><br />Thanks for eplenation @n3t.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42863">issues.joomla.org/tracker/joomla-cms/42863</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 54e89cff91758713821b92bf35d07b1fc22d71bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42863">issues.joomla.org/tracker/joomla-cms/42863</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42863">issues.joomla.org/tracker/joomla-cms/42863</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
