### PR TITLE
[4.0] content dashboard

### PR DESCRIPTION
**Pull request by brianteeman**
Add the missing title to the add new content, category, module links on the content dashboard

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc2bb1eb261cd677543e4f21d7d6ae4dce58e866<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27289">issues.joomla.org/tracker/joomla-cms/27289</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fc2bb1eb261cd677543e4f21d7d6ae4dce58e866<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27289">issues.joomla.org/tracker/joomla-cms/27289</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27289">issues.joomla.org/tracker/joomla-cms/27289</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
