### PR TITLE
Add Language string DELETE_FROM_TRASH and replace alle occurences of …

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #41106 .
Replacement for PR #41119.

### Summary of Changes
The String "Empty Trash"in list views is replaced by "Delete". To avoid a b/c break by modifying the Language String a new Languages string has been added. 

### Testing Instructions
Code review, have a look on list views when the state filter is set to "trashed" 

### Actual result BEFORE applying this Pull Request
The Button says "Empty Trash"

### Expected result AFTER applying this Pull Request
The Button says "Delete"

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
As I wrote on the original PR

> For me there is nothing wrong with the current text.
> 
> We put items in the trash (by changing the state) Then we empty the trash.
> 
> That is the same language construct used in windows

Technically this PR is correct however

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on e66327e04bf1e8ba516cac58fc06176e887a6422<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43841">issues.joomla.org/tracker/joomla-cms/43841</a>.</sub>

**Comment by Quy** [comment]
Why add another string? Use `JTOOLBAR_DELETE`.

**Comment by Quy** [comment]
@HLeithner suggested the same thing. https://github.com/joomla/joomla-cms/pull/41119#issuecomment-2236408534

**Review by HLeithner — APPROVED** [review]

**Comment by HLeithner** [comment]
> @HLeithner suggested the same thing. [#41119 (comment)](https://github.com/joomla/joomla-cms/pull/41119#issuecomment-2236408534)

was a bad idea

**Comment by Iniestaso** [comment]
Please describe millestone 5.2, this PR is not visible to translators. I only discovered it when comparing versions.

**Pull request merged**
