### PR TITLE
[4.0] [a11y] Adding Label for Login Module password field

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23860

### Summary of Changes

Label added

### Testing Instructions
See source code for the frontend login module

@zwiastunsw

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on d807449a664a16586760d6cccd6217d61542491e<br /><br />thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23862">issues.joomla.org/tracker/joomla-cms/23862</a>.</sub>

**Comment by dgrammatiko** [comment]
@infograf768 can you do your PR against: https://github.com/joomla/joomla-cms/pull/23215

The current HTML is **not** the actual output of the field that we want, as the field needs to be a Custom Element

Actually this is already done in that PR

**Comment by infograf768** [comment]
@dgrammatiko 
I can close this PR indeed. I have tested your PR and I see that label is added but the class `class="sr-only"` is absent. Is that OK? @zwiastunsw

**Comment by dgrammatiko** [comment]
@infograf768 there is no class sr-only but there is a **non Bootstrap** class with the same effect: https://github.com/joomla/joomla-cms/pull/23215/files#diff-b38b2a09fa4b4f3eefc4fdc9db3d87e5R154

The reason is that none of the input fields (the custom elements I mean) should be Bootstrap or Font Awesome dependant...

**Comment by infograf768** [comment]
OK, closing.

**Pull request closed without merging**
