### PR TITLE
Update en-GB.com_postinstall.ini (cosmetic)

### PR DESCRIPTION
**Pull request by Hils**
(from Joomla.org) - Joomla.org is not a word or a link or a location. Should it be linked somewhere? Should it be to Joomla's home page? (http://www.joomla.org/) or perhaps the correct category in docs? Joomla.org is the slang term we all use and we know what it means ;)

### CODE REVIEW

**Comment by zero-24** [comment]
@Hils do you think we can use: `<a href="_QQ_"http://www.joomla.org"_QQ_">http://www.joomla.org/</a>`

**Comment by zero-24** [comment]
or @Hils 
`<a href="_QQ_"http://www.joomla.org/announcements/release-news/"_QQ_">from joomla.org</a>`

**Comment by Hils** [comment]
COM_POSTINSTALL_LBL_RELEASENEWS="<a href="_QQ_"http://www.joomla.org/announcements/release-news/"_QQ_">from the Joomla! Project</a>" (project word 'stolen' from marketing on 3.4.0 release page ;) ) - is that OK?

**Comment by zero-24** [comment]
just to be sure:
`COM_POSTINSTALL_LBL_RELEASENEWS="Release news <a href="_QQ_"http://www.joomla.org/announcements/release-news/"_QQ_">from the Joomla! Project</a>"`

looks good here :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6215">issues.joomla.org/joomla-cms/6215</a>.</sub>

**Comment by brianteeman** [comment]
For future reference of anyone else seeing this 

The rule of thumb for sage of the ! is
Whenever you can substitute "your Joomla CMS" in place of "Joomla" and still make sense, then it's descriptive and no bang needed.

As for making this a link - is it really necessary - it is a title and everything below the title is a link in iteself

**Comment by Hils** [comment]
Perhaps it is best to quote this in comments:
https://github.com/joomla/user-interface-text/commit/1b384a25f046254d75a518b13db21f2835e00345
that is what I am working from

**Comment by brianteeman** [comment]
that is the exact quote i used unless my eyesight is failing and copy/paste is not working

**Comment by Hils** [comment]
Your eyesight is working perfectly but now everyone has the full information and the location where they can find it in future.

**Comment by brianteeman** [comment]
I deliberately did NOT link to a specific location as that location is not
permanent

On 27 February 2015 at 13:58, Hils <notifications@github.com> wrote:

> Your eyesight is working perfectly but now everyone has the full
> information and the location where they can find it in future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6215#issuecomment-76397853>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
Apologies - @all please ignore that link to the bang rules provided by @Duke3D

**Comment by dnimooj** [comment]
works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6215">issues.joomla.org/joomla-cms/6215</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6215">issues.joomla.org/joomla-cms/6215</a>.</sub>

**Comment by infograf768** [comment]
To merge after 3.4.1

**Comment by wilsonge** [comment]
Thanks Hils :)

**Pull request merged**
