### PR TITLE
Maintenance Menu group

### PR DESCRIPTION
**Pull request by brianteeman**
If you look at the system menu you will see that there is a separator between checkin and cache. This is presumably done because they have different components (com_cache and com_checkin)

But whenever you select one then you have all three available in the sidebar and they are all titled Maintenance - so while it makes sense from a code perspective for their to be a separator in the menu it doesnt make sense,nor is it consistent, from a UI perspective.

This PR removes the separator. See screenshots

Before
before

After
after

Maintenance Menu
manage

### CODE REVIEW

**Comment by brianteeman** [comment]
This does not effect hathor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5768">issues.joomla.org/joomla-cms/5768</a>.</sub>

**Comment by waader** [comment]
@test works!

**Comment by pe7er** [comment]
@test
works good

**Comment by brianteeman** [comment]
Setting RTc - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5768">issues.joomla.org/joomla-cms/5768</a>.</sub>

**Pull request merged**
