### PR TITLE
Enable fullscreen mode in TinyMCE

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #10879 .
#### Summary of Changes

Enable TinyMCE Fullscreen mode
#### Testing Instructions

Apply patch - note new full screen menu option in tinymce editor - use it - test it 

as proposed by @c-lodder in #10879 (cc: @brianteeman)

Milestone 3.6.1 please

### CODE REVIEW

**Comment by PhilETaylor** [comment]
This PR has a bug.. in so much as the top navbar that is fixed in Joomla hides the top menu bar of tinymce in full screen mode and therefore there is no way to come out of full screen mode in order to save the content with the joomla save button :-( 

The PR therefore cannot be merged in its current state until this bug is fixed... but that probably needs a frontend JS/CSS guru and some funky z-index css rule or something :-( Beyond me this late at night :)

**Comment by C-Lodder** [comment]
Cheers. I'll look at this after I've done the menu fix

**Comment by PhilETaylor** [comment]
find somewhere appropriate for this css and this fixes that overlay bug as the fixed navbar z-index is 1030

div.mce-fullscreen {
    z-index: 1031;
}

**Comment by brianteeman** [comment]
That's one reason I didn't implement it already Phil :)

**Comment by PhilETaylor** [comment]
ready for testing :)

**Comment by C-Lodder** [comment]
@PhilETaylor - CSS should be applied to the LESS files ;)

**Comment by PhilETaylor** [comment]
ah crap... like I said

> that probably needs a frontend JS/CSS guru

200_s

**Pull request closed without merging**
