### PR TITLE
[4.0] Packages or Extensions

### PR DESCRIPTION
**Pull request by brianteeman**
I really don't know why it was written as packages as technically packages are just one type of extension and it is more normal to refer to "extensions" when installing something

### CODE REVIEW

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on dd4685d8286c371ce6c482b38ec02f9e381bbf92<br /><br />This package/extension/patch changed the language file<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24091">issues.joomla.org/tracker/joomla-cms/24091</a>.</sub>

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on dd4685d8286c371ce6c482b38ec02f9e381bbf92<br /><br />All 7 files changed from packages to extensions.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24091">issues.joomla.org/tracker/joomla-cms/24091</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24091">issues.joomla.org/tracker/joomla-cms/24091</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
