### PR TITLE
[4.4] json_decode of NULL in InstallerScript::getItemArray()

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Prevent calling `json_decode` on NULL.

Possible behavior on language pack update:

`Joomla\CMS\Installer\InstallerScript->getItemArray( $element = 'manifest_cache', $table = '#__extensions', $column = 'element', $identifier = 'German (Germany) Language Pack' )`

### Testing Instructions

PHP 8.1, set error reporting to maximum, update de-DE language.

### Actual result BEFORE applying this Pull Request

`Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in \libraries\src\Installer\InstallerScript.php on line 304`

### Expected result AFTER applying this Pull Request

No warnings.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@Denitz How dod you get that error? I'm asking because in the extension table, the manifest_cache column has a not null constraint, so the result of that query should never be null. See https://github.com/joomla/joomla-cms/blob/4.3-dev/installation/sql/mysql/base.sql#L137 .

**Comment by Denitz** [comment]
@richard67 I updated core German language pack, see `pkg_de-DE.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<extension type="package" method="upgrade">
	<name>German (Germany) Language Pack</name>
	<packagename>de-DE</packagename>
	<version>4.3.1.1</version>
...
```

The installer tries to find the `element` via `Joomla\CMS\Installer\InstallerScript->getItemArray( $element = 'manifest_cache', $table = '#__extensions', $column = 'element', $identifier = 'German (Germany) Language Pack' )` which results in

```
SELECT * FROM `#__extensions` WHERE `element` = 'German (Germany) Language Pack'
```

See the code in `\libraries\src\Installer\InstallerScript.php:144`

```
// Abort if the extension being installed is not newer than the currently installed version
        if (!$this->allowDowngrades && strtolower($type) === 'update') {
            $manifest = $this->getItemArray('manifest_cache', '#__extensions', 'element', $this->extension);

            // Check whether we have an old release installed and skip this check when this here is the initial install.
            if (!isset($manifest['version'])) {
                return true;
            }

            $oldRelease = $manifest['version'];

            if (version_compare($this->release, $oldRelease, '<')) {
                Factory::getApplication()->enqueueMessage(Text::sprintf('JLIB_INSTALLER_INCORRECT_SEQUENCE', $oldRelease, $this->release), 'error');

                return false;
            }
        }
```

There are no extensions with this `element`, German language pack has `element = "pkg_de-DE"` and `name = "German (Germany) Language Pack"`

**Comment by richard67** [comment]
@Denitz So this PR seems to be the wrong fix, and the right fix would be to change the parameters in the call to the `getItemArray` method so that the `$column` and `$identifier` fit together. It would work with `$column` = `'name'` instead of `'element'`, or when using `$column` = `'element`' the `$identifier` should be `'pkg_' . <the packagename from the XML>`, e.g. `'pkg_de-DE'`.

**Comment by Denitz** [comment]
@richard67 Yes, agree, I've updated the call to getItemArray(). And still it's better to leave initial update of getItemArray() method because we can potentially load NULL on missed record.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 11517ee427211f1d1be8b1055d015fbcaa484e4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40527">issues.joomla.org/tracker/joomla-cms/40527</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 11517ee427211f1d1be8b1055d015fbcaa484e4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40527">issues.joomla.org/tracker/joomla-cms/40527</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40527">issues.joomla.org/tracker/joomla-cms/40527</a>.</sub>

**Comment by laoneo** [comment]
Thanks for the fix...Currently checking with @tecpromotion about impacts for translation packs. Assigning it to the milestone 4.4.2.

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 11517ee427211f1d1be8b1055d015fbcaa484e4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40527">issues.joomla.org/tracker/joomla-cms/40527</a>.</sub>

**Review by tecpromotion — APPROVED** [review]
Thanks all

**Pull request merged**
