### PR TITLE
Filter input remove - do not run cleanTags twice

### PR DESCRIPTION
**Pull request by csthomas**
Speed up $input->remove() function, replace deprecated stuff.

### CODE REVIEW

**Comment by Hackwar** [comment]
Thank you for looking into this code. I personally have the feeling that JFilterInput is a weakness in Joomla, because it is EXTREMELY complex and I haven't been able to review it, when I looked into this a few years ago because of its complexity. I fear that there is a special string waiting somewhere out there, which is not properly handled by this class. Anyway, back to this PR :wink: 

You are right that the code is executed more often than necessary. Can you move the variable assignment outside of the while condition? You could do a do {} while() instead, to run it at least once before checking the result.

It would be cool if we could get unittests for this class. Proper ones, that is.

**Comment by csthomas** [comment]
I'm not familiar with the tests, but I like to optimize the code.

**Comment by csthomas** [comment]
The information about build "The Travis CI build failed" is incorrect.

Please check status of build at https://github.com/joomla/joomla-cms/pull/9161 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9163">issues.joomla.org/joomla-cms/9163</a>.</sub>

**Comment by beat** [comment]
From a code point of view :+1:  : The new code is equivalent to the old one and avoids a lot of unneeded cycles (speed optimization).

**Comment by roland-d** [comment]
I have merged this based on both code reviews and testing the PR myself.

**Comment by photodude** [comment]
Part of this change is a B/C break,
$source = $this->cleanTags($source); needs to remain as $source = $this->_cleanTags($source);
the underscore-methods need to remain in functions until the underscore-method is depreceated (4.0 in this case) @wilsonge fixed that B\C issue with https://github.com/joomla/joomla-cms/commit/6e24ab47fa8047eb4b4751ef21b6e87d2885a625

@csthomas would you also consider making make this change at the [Framework filter package](https://github.com/joomla-framework/filter)?

**Comment by beat** [comment]
Woops, missed the underscore removal from visual inspection on github, sorry! :cry: 
Thanks @wilsonge for fixing

**Comment by csthomas** [comment]
@photodude I will push request on  Framework filter package (without underscores)

**Comment by photodude** [comment]
Yep, the Framework luckily doesn't have the underscore B/C issue to deal with. ;-)
@csthomas Thanks for carrying these changes over to the Framework.

**Pull request merged**
