### PR TITLE
[4.0] Optimize Discover and Update menu badges

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Run simplified query for `Discover` and `Update` badges on System Dashboard.

### Testing Instructions

Drop some extension files in your Joomla! installation so they can be discovered.
Install some outdated extension.
Check that `Discover` and `Update` badge still work correctly.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b641f46039975a674dc87639ff2745573f3a712<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29159">issues.joomla.org/tracker/joomla-cms/29159</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b641f46039975a674dc87639ff2745573f3a712<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29159">issues.joomla.org/tracker/joomla-cms/29159</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :red_circle: unsuccessfully on 5b641f46039975a674dc87639ff2745573f3a712<br /><br />Hi,

I have deleted one extension from the the extensions table (plg_quickicon_downloadkey) and then I have used the Discover button but it could not discover it.

There was no change applying the patch.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29159">issues.joomla.org/tracker/joomla-cms/29159</a>.</sub>

**Comment by SharkyKZ** [comment]
@BertaOctech that doesn't seem related to the PR. This PR only affects badges shown in System Dashboard, not functionality in Discover/Update views. If you're having problems with discovering extensions, you might want to open a new issue.

**Comment by BertaOctech** [comment]
OK, thank you, will do

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 5b641f46039975a674dc87639ff2745573f3a712<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29159">issues.joomla.org/tracker/joomla-cms/29159</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29159">issues.joomla.org/tracker/joomla-cms/29159</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
