### PR TITLE
Reset pathways counter after the set pathways

### PR DESCRIPTION
**Pull request by alexva24**
Internal counter needs to update after new pathways set

### CODE REVIEW

**Comment by alexva24** [comment]
Nothing to test

**Comment by brianteeman** [comment]
Then it will be closed.

Please describe the issue that this Pull Request resolves. How to replicate that problem and how to see the results of this Pull Request

**Comment by alexva24** [comment]
Pathways counter needs to update after new pathways set. This PR fixed this bug.

**Comment by brianteeman** [comment]
How can I see this bug!!!

On 28 January 2016 at 14:55, Aleksey Vaganov <notifications@github.com>
wrote:

> Pathways counter needs to update after new pathways set. This PR fixed
> this bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8987#issuecomment-176224132>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alexva24** [comment]
In source code

**Comment by mbabker** [comment]
There needs to be a way to reproduce this or it'll never get tested.  Even if it's telling someone to put a var_dump() in somewhere to compare results before and after.  Simply reading the source code isn't going to cut it, I'm reading it and I'm not immediately grasping what your change is doing.

**Comment by alexva24** [comment]
$pathways = JFactory::getApplication()->getPathways();
print_r($pathways);
$pathways->setPathways(array());
print_r($pathways);

// Pathways must be a zero, but it stay on old value. It's a bug!!!

**Comment by mbabker** [comment]
Thank you, that gives folks an easy way to validate what you've changed.

**Comment by sovainfo** [comment]
Haven't been able to find a reference to _count other than in the addItem method of JPathway.
Sounds like it is not used, no wonder it is not properly maintained. Agree with @alexva24 that his change would maintain it properly, only see no reason to do it. 

Suggest to remove _count and use count($app->getPathway()) or count($pathway) instead.

**Comment by alexva24** [comment]
@sovainfo, I agree with you.

**Comment by alexva24** [comment]
Countable interface implemented on JPathways class

**Comment by anibalsanchez** [comment]
I have tested this item :red_circle: unsuccessfully on e1bb5d519c6aeae0134bf590c7c69392d0ad2729<br /><br />Tested with the suggested code:

Fatal error: Call to undefined method JApplicationAdministrator::getPathways()<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8987">issues.joomla.org/joomla-cms/8987</a>.</sub>

**Comment by mbabker** [comment]
The method's name is `getPathway()`, plural I'm going to assume is a typo.

**Comment by alexva24** [comment]
To test Countable interface implementation use code bellow:
$pathways = JFactory::getApplication()->getPathway();
echo count($pathways);
$pathways->setPathway(array());
echo count($pathways);
$pathways->addItem('Anchor1', '/link1');
echo count($pathways);

**Comment by sovainfo** [comment]
That is not testing the count interface, it is testing the php count function.As already mentioned that works, no need to test that.
To test the count interface you would need to get an instance of the Pathway and call the count method:
JPathway::getInstance('site')->count();
Which is why I concluded there is no need for Pathway to maintain a count. No need to implement the count interface either. Considering it only returns an array of values and php count can be used to count them!

**Comment by alexva24** [comment]
@sovainfo JPathway::getInstance('site') and JFactory::getApplication()->getPathway() returns JPathway object with protected property _pathway

**Comment by sovainfo** [comment]
No, it doesn't. The getPathway() returns: return array_values($pw);
At least in j345, maybe staging is different.

**Comment by alexva24** [comment]
count(JPathway::getInstance('site')) simpler than count(JPathway::getInstance('site')->getPathway())

**Comment by sovainfo** [comment]
And count($pathways) is simpeler than that!

**Comment by alexva24** [comment]
@sovainfo But before your need to set variable $pathways

**Comment by sovainfo** [comment]
No, you don't. IF there is a need for a count without the values then count($app->getPathway()) will do.

**Comment by roland-d** [comment]
I agree with @sovainfo here. A simple count($app->getPathway()) will do. I do not see the need to implement a Countable interface for this. As mentioned before it is a value that doesn't seem to be used because it is a protected variable and only used internally to increment the value. For what it is worth, I would say the deprecation would just say that the $_count will be removed in 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8987">issues.joomla.org/joomla-cms/8987</a>.</sub>

**Comment by ggppdk** [comment]
I do not say it is enough to accept a PR without testing although the fix is obvious
- I have seen this bug a few years ago, but since the variable is currently not used for something important, that is the reason i did not report

But code review,
**is more than enough to confirm the issue**, since the involved code is too small

Please click at the very 1st commit to see the fix, (only the 1 commit of this PR is needed)
- the other commits to implement the countable interface are not needed

Explanation:
The class has a property:
```
protected $_count = 0;
```

When you an item the above property, is incremented, click here to confirm this:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/pathway/pathway.php#L175

When you use setPathWay, it is not set to new value, click here to confirm this:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/pathway/pathway.php#L127-L135

To cut this short, **only the 1st commit is needed**, no need to implement a Countable interface

**Pull request closed without merging**
