### PR TITLE
[com_fields] Define the batch commands

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #12691.

### Summary of Changes
Removes the notice from the issue.

### Testing Instructions
- Create some field groups
- Create a Content field.
- Select this Content field and Batch copy or move

### CODE REVIEW

**Comment by infograf768** [comment]
That does not work here.

**Comment by infograf768** [comment]
@laoneo 
That patch is done to the wrong file.
In fact, this will work (if we keep using categories...)
```
diff --git a/administrator/components/com_fields/models/field.php b/administrator/components/com_fields/models/field.php
index f2fee8e..8d8ae2e 100644
--- a/administrator/components/com_fields/models/field.php
+++ b/administrator/components/com_fields/models/field.php
@@ -27,4 +27,22 @@
 
 	/**
+	 * Batch copy/move command. If set to false,
+	 * the batch copy/move command is not supported
+	 *
+	 * @var string
+	 */
+	protected $batch_copymove = 'category_id';
+
+	/**
+	 * Allowed batch commands
+	 *
+	 * @var array
+	 */
+	protected $batch_commands = array(
+			'assetgroup_id' => 'batchAccess',
+			'language_id' => 'batchLanguage',
+	);
+
+	/**
 	 * Constructor.
 	 *
diff --git a/administrator/components/com_fields/views/fields/tmpl/default_batch_body.php b/administrator/components/com_fields/views/fields/tmpl/default_batch_body.php
index f54cf1e..8d2645c 100644
--- a/administrator/components/com_fields/views/fields/tmpl/default_batch_body.php
+++ b/administrator/components/com_fields/views/fields/tmpl/default_batch_body.php
@@ -28,8 +28,10 @@
 </div>
 <div class="row-fluid">
-	<div class="control-group span6">
-		<div class="controls">
-			<?php echo JHtml::_('batch.item', $context . '.fields');?>
+	<?php if ($published >= 0) : ?>
+		<div class="control-group span6">
+			<div class="controls">
+				<?php echo JHtml::_('batch.item', $context . '.fields');?>
+			</div>
 		</div>
-	</div>
+	<?php endif; ?>
 </div>
```

**Comment by laoneo** [comment]
Thanks for the patch. I'v adapted it. Does it work now as expected as I couldn't reproduce the issue.

**Comment by infograf768** [comment]
Except for the indentation in default_batch_body (look above), it is fine.
But  maintainers discussed and do agree that modifying com_categories as you did is not acceptable, so a solution has to be found there.

**Comment by laoneo** [comment]
This PR has nothing to do with the other discussion. Lets try to focus.

**Comment by infograf768** [comment]
It has everything to do with it, as batch is implemented using com_categories.

**Comment by laoneo** [comment]
What I wanted to say is that we should not discuss it over multiple issues.

**Comment by infograf768** [comment]
In the mean while, thanks for correcting the indent.

**Comment by zero-24** [comment]
I have just moved the since tags to `__DEPLOY_VERSION__` ;)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2ef574305e720380757785d587e18d025fbeca93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12695">issues.joomla.org/tracker/joomla-cms/12695</a>.</sub>

**Comment by Bakual** [comment]
I think this isn't needed anymore as it should be fixed with https://github.com/joomla/joomla-cms/pull/13019

**Comment by zero-24** [comment]
@laoneo you just reverted my changes here :smile: Can you apply the changes (missing spaces and `__DEPLOY_VERSION__`):

image

image

**Pull request closed without merging**
