### PR TITLE
[4.4] Use HelperFactory to get Helper for mod_quickicon

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes small changes to mod_quickicon code to use HelperFactory  to get it's Helper class. It has two benefits:

1. Consistent code with how we are getting Helper for other modules. For example https://github.com/joomla/joomla-cms/blob/4.2-dev/modules/mod_articles_latest/src/Dispatcher/Dispatcher.php#L41
2. Save the system from having to go to `bootModule` routine again before it can get module helper class.

### Testing Instructions
1. Use Joomla 4.3 nightly build
2. Apply patch
3. Access to administrator area of your site, look at Home Dashboard, Notifications section. Make sure the icons there are still being displayed (see the attached screenshot)

quick_icons

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 632ec44b2b8d07ff8ea41dec4c5311e836b0dac6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40018">issues.joomla.org/tracker/joomla-cms/40018</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 632ec44b2b8d07ff8ea41dec4c5311e836b0dac6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40018">issues.joomla.org/tracker/joomla-cms/40018</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40018">issues.joomla.org/tracker/joomla-cms/40018</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
