### PR TITLE
[4.0] [a11y] Admin Login Page

### PR DESCRIPTION
**Pull request by brianteeman**
The a11y team has asked that the login page has a main landmark region

### Testing
There should be no visible difference

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 7df511d50db7ad90ec1007f376cc5cbd28eeed2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21604">issues.joomla.org/tracker/joomla-cms/21604</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 7df511d50db7ad90ec1007f376cc5cbd28eeed2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21604">issues.joomla.org/tracker/joomla-cms/21604</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21604">issues.joomla.org/tracker/joomla-cms/21604</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
