### PR TITLE
Alphabetical not ASCII

### PR DESCRIPTION
**Pull request by brianteeman**
It is not ASCII characters - just the alphabetical ascii characters 
#### Before

COM_USERS_CONFIG_FIELD_MINIMUM_UPPERCASE_DESC="Set the minimum number of upper case ASCII characters required for a password."
#### After

COM_USERS_CONFIG_FIELD_MINIMUM_UPPERCASE_DESC="Set the minimum number of upper case alphabetical characters required for a password."

### CODE REVIEW

**Review by jeckodevelopment — APPROVED** [review]
Fine by me

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 29db47b31cade6b33d365199b77048b9613bc213<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12365">issues.joomla.org/tracker/joomla-cms/12365</a>.</sub>

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12365">issues.joomla.org/tracker/joomla-cms/12365</a>.</sub>

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 29db47b31cade6b33d365199b77048b9613bc213<br /><br />Seems Good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12365">issues.joomla.org/tracker/joomla-cms/12365</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
