### PR TITLE
[4.0] Installation text improvement

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue #20351.

### Summary of Changes
Text improvement for the "Congratulations" page of the installation process.

### Testing instructions
Go through the installation proces and check if the correct new message appears on the Congratulations page.

Old text: Before going on to your site you have the chance to pre-configure some features to your Joomla installation.
New text: You now have the option to customise your installation by adding another language or installing the sample data.

### CODE REVIEW

**Comment by ghost** [comment]
@brianteeman @laoneo Is it ok like this? I thought the code would be added to the original issue, or is this normal? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by carlitorweb** [comment]
@joomlara is normal. A Pull Request and an Issue, they are two different things. That is why you need to say "Pull Request for Issue...." in case an issue was already reported

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 9d2a489c410d74f54d6d27d58042d70218752266<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 9d2a489c410d74f54d6d27d58042d70218752266<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by ghost** [comment]
Ok, thanks @carlitorweb !

**Comment by laoneo** [comment]
Nice one!

**Comment by ghost** [comment]
Thanks @laoneo and also for explaining it!

**Comment by brianteeman** [comment]
Congratulations on your first pr.

**Comment by brianteeman** [comment]
I don't think we need the second sentence. The UI already does it.

Just the text I wrote here  https://github.com/joomla/joomla-cms/issues/20351#issuecomment-390161658 is enough. Less is always better.

**Comment by ghost** [comment]
Thanks @brianteeman and also for your help!
Do you mean the sentence "If you are not interested just skip this step...."? If so, I will delete it. 
Or do I have to create a new branch then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by brianteeman** [comment]
Just delete that part

**Review by brianteeman — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6243f90277903f98ce85f8e48fa7d03782e2670c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 6243f90277903f98ce85f8e48fa7d03782e2670c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Comment by laoneo** [comment]
Thank you! #jab18

**Comment by brianteeman** [comment]
Congratulations on successfully completing your first merged pr. I hope this is the first of many

**Comment by ghost** [comment]
Thanks Brian! Wow, merged on the same day...
Thanks everyone, for testing, merging my first PR so quickly!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20454">issues.joomla.org/tracker/joomla-cms/20454</a>.</sub>

**Pull request merged**
