### PR TITLE
Fix drag n drop install message issue for #15119

### PR DESCRIPTION
**Pull request by asika32764**
Pull Request for Issue #15119 .

### Summary of Changes

Fix no message issue after drag and drop extension installation.

### Testing Instructions

Go to extension installer, drag and drop an extension to install.

### Before PR

No flash message, only extension message.

### After PR

A green alert message will appear.

p-2017-04-06-001

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on aec39fe6f3345402ac9c36973b6a12a47a399a5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15135">issues.joomla.org/tracker/joomla-cms/15135</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on afa351dee97e2825f51959f5de9ce94910d84fac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15135">issues.joomla.org/tracker/joomla-cms/15135</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2c8c14b927208043fd88f4b1246fd592fbcead6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15135">issues.joomla.org/tracker/joomla-cms/15135</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2c8c14b927208043fd88f4b1246fd592fbcead6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15135">issues.joomla.org/tracker/joomla-cms/15135</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
