### PR TITLE
[4.0] FLoC options

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the display after Merge commit 'f2b6d58' into 4.0-dev

### Before
image

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 16e8d557dfc74ecfa5401da8578baea8d2c63501<br /><br />@brianteeman Thanks for creating the pull request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34507">issues.joomla.org/tracker/joomla-cms/34507</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 16e8d557dfc74ecfa5401da8578baea8d2c63501<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34507">issues.joomla.org/tracker/joomla-cms/34507</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34507">issues.joomla.org/tracker/joomla-cms/34507</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
