### PR TITLE
[4.0] Support null values in Extensions table

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds null value support flag to Extensions table. Fixes enabling/disabling plugins.

### Testing Instructions

Go to plugins list.
Click the icon to disable a plugin.
Click the icon again to enable the plugin.

### Expected result

Plugin enabled.

### Actual result

Plugin remains disabled.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on dcd2b084a5358a46f01470473821547588ed02d0<br /><br />Tested successfully in 4.0 beta2-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29356">issues.joomla.org/tracker/joomla-cms/29356</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dcd2b084a5358a46f01470473821547588ed02d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29356">issues.joomla.org/tracker/joomla-cms/29356</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29356">issues.joomla.org/tracker/joomla-cms/29356</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
