### PR TITLE
[4.0] Fix filter by condition

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Articles filtered from Categories is by condition and not by published.

### Testing Instructions
Go to Content > Categories.
Under the Published column, click on a number.
On the Articles page, no selection under `- Select Condition -`.
Apply PR.
Repeat steps above with the other columns.
On the Articles page, `Published` is selected under `- Select Condition -`.

Go Component > Tags
Filter on `Select Tag Type`

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a4661be1cfad003fab97bb8ca795742487e86607<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by SharkyKZ** [comment]
This fixes the issue in `com_content` but introduces the same issue in other components.

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on a4661be1cfad003fab97bb8ca795742487e86607<br /><br />@SharkyKZ You are right. I've just tested with contact categories.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by Quy** [comment]
Fixed to factor in other components.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ee06942b13ed05a32b6451c2c1893ac504c28f21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by Quy** [comment]
Added filter to Tags component. 
@richard67 Please test again. Updated testing instructions.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 14139cb3e76f27a3e3b77e637f7ae047da388246<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3789b6a874e0b6d34f3a7262d6e20b4c632ffa50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 3789b6a874e0b6d34f3a7262d6e20b4c632ffa50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27126">issues.joomla.org/tracker/joomla-cms/27126</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
