### PR TITLE
[4.0] Update mediaelement.js to v4.1.1

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

We're currently 2 major versions behind on `mediaelement.js`, so this PR updates it to the latest version.

As it stands, there is still some jQuery behind the scenes but I won't remove that as I'm sure the new media manager will sort it.

### Testing Instructions

- Go to the Media Manager options
- Add `video/mp4` as a **Legal MIME Type**
- Add `mp4` as a **Legal Extension**
- Upload an MP4 video (can use [this sample one](http://techslides.com/demos/sample-videos/small.mp4))
- Click the video to play

### Expected result

Video plays as expected.

### CODE REVIEW

**Comment by dgt41** [comment]
Must be a world wide disease that everyone want to move away from jQuery 🎉 
Trolls please take a note of the common patterns...

**Review by dgrammatiko — APPROVED** [review]

**Comment by dgt41** [comment]
@C-Lodder we need to drop `flv` from the supported file formats in media manager I guess, but leave that for the other group. I'll raise an issue there.
Thanks for pulling this in!

**Comment by Bakual** [comment]
> Trolls please take a note of the common patterns...

#dgt41 You seriously should start watching your language here. Not everyone disagreeing with you is automatically a troll.

**Comment by laoneo** [comment]
Guess this pr should be done against the media manager repo, it affects some views we don't have anymore in the new media manager.

**Comment by C-Lodder** [comment]
@laoneo the changes to the PHP files aren't actually required, so do you want me to just revert them?

**Comment by dgt41** [comment]
@C-Lodder yes, drop the view changes here

**Comment by laoneo** [comment]
How and where is this lib used?

**Comment by dgt41** [comment]
@laoneo there is no php helper to render video tags, so it's custom code

**Comment by laoneo** [comment]
Do we use that lib in the new MM as well?

**Comment by dgt41** [comment]
We haven't implemented a preview for videos yet, so atm no

**Comment by C-Lodder** [comment]
@dgt41 @laoneo view changes reverted

**Comment by wilsonge** [comment]
@laoneo You need to make a decision on this. As this is only used for rendering videos in MM, this is on you.

**Comment by laoneo** [comment]
For me it is ok to merge. We didn't decide right now how preview is done.

**Pull request merged**
