### PR TITLE
[5.2] Tinymce lang sort

### PR DESCRIPTION
**Pull request by brianteeman**
Fix the alpha sort of the language file

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e73305386a196f663a8da8b0766d36694024ce7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43910">issues.joomla.org/tracker/joomla-cms/43910</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e73305386a196f663a8da8b0766d36694024ce7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43910">issues.joomla.org/tracker/joomla-cms/43910</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43910">issues.joomla.org/tracker/joomla-cms/43910</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution, @brianteeman!

**Pull request merged**
