### PR TITLE
Added javascript folder description to tests/README.md

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Added the description of the new JavaScript tests folder to the tests/README.md file
### Testing Instructions

none, just review
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6605f74eae3b2fb8ce13b500859db2d733ccc0ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11629">issues.joomla.org/joomla-cms/11629</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 6605f74eae3b2fb8ce13b500859db2d733ccc0ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11629">issues.joomla.org/joomla-cms/11629</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 6605f74eae3b2fb8ce13b500859db2d733ccc0ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11629">issues.joomla.org/joomla-cms/11629</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11629">issues.joomla.org/joomla-cms/11629</a>.</sub>

**Pull request merged**
