### PR TITLE
[4.0] [mod_tags_similar] Parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds parameterized queries to `mod_tags_similar`.

### Testing Instructions

Create some articles with tags.
Publish Tags - Similar module.
View article page in frontend.
Inspect the module.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0bbd1342c987455da99042a2c5130df9bd3cbf69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27076">issues.joomla.org/tracker/joomla-cms/27076</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0bbd1342c987455da99042a2c5130df9bd3cbf69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27076">issues.joomla.org/tracker/joomla-cms/27076</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27076">issues.joomla.org/tracker/joomla-cms/27076</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
