### PR TITLE
Getdbo patch fixes #35884

### LINKED ISSUE #35884: Joomla\CMS\Factory::getDbo() is deprecated.
### Steps to reproduce the issue

Multilpe components still use getDbo() with is depracted

### Expected result

must use Factory::getContainer()->get('DatabaseDriver'); instead

### PR DESCRIPTION
**Pull request by basd82**
Made pull request like sugested by Richard Fath

I made this change to 4.0-dev branch becouse they are fixes that are only valid voor 4.x

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by ceford** [comment]
This PR needs a description and testing instructions as in all other properly documented PRs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35888">issues.joomla.org/tracker/joomla-cms/35888</a>.</sub>

**Comment by basd82** [comment]
Pull Request for Issue # 35884

Summary of Changes

Replaced Getdbo() becouse it is deprecated

Testing Instructions

Test if the following component's in the frontend are still working like before:
com_users
com_content
com_finder

Actual result BEFORE applying this Pull Request

Messages about depricated calls to getDbo() in adminstrator/log/depricated.php

Expected result AFTER applying this Pull Request

No more log messages for these components

Documentation Changes Required

None that i can think off

**Comment by basd82** [comment]
Pull Request for Issue # 35884

Summary of Changes

Replaced Getdbo() becouse it is deprecated

Testing Instructions

Test if the following component's in the frontend are still working like before:
com_users
com_content
com_finder

Actual result BEFORE applying this Pull Request

Messages about depricated calls to getDbo() in adminstrator/log/depricated.php

Expected result AFTER applying this Pull Request

No more log messages for these components

Documentation Changes Required

None that i can think off

**Comment by basd82** [comment]
> This PR needs a description and testing instructions as in all other properly documented PRs.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/35888](https://issues.joomla.org/tracker/joomla-cms/35888).

Added the request pr

**Comment by alikon** [comment]
thank you @basd82 superseded by  #36502

**Comment by PhilETaylor** [comment]
There is no point reopening this after you threw your toys out your cot after being asked to make 12 lines of copy and paste changes  - it’s no better than the PR you proposed. 

I’ll make a PR later tonight that does it correctly, completely, in all places

**Comment by alikon** [comment]
looking forward for your pr

**Comment by PhilETaylor** [comment]
PR Provided as #36511

**Pull request closed without merging**
