### PR TITLE
[4.0] Use name when sending mass mail

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/29538.

### Summary of Changes

Use recipient's name when sending mass mail.

### Testing Instructions

Go to Users -> Mass Mail Users.
Untick `Recipients as BCC` option.
Send mass mail.
Check your email, inspect `To` value.

### Actual result BEFORE applying this Pull Request

Only recipient email is used, e.g.

    To: info@localhost <info@localhost>

### Expected result AFTER applying this Pull Request

Recipient name and email are used, e.g.:

    To: Admin <info@localhost>

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4eb96163e7e1d009424e91d1011eff36641a5332<br /><br />Tested successfully in Beta2-dev of 23 June.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29769">issues.joomla.org/tracker/joomla-cms/29769</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4eb96163e7e1d009424e91d1011eff36641a5332<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29769">issues.joomla.org/tracker/joomla-cms/29769</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29769">issues.joomla.org/tracker/joomla-cms/29769</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
