### PR TITLE
CLEANING - JCacheStorageCachelite

### PR DESCRIPTION
**Pull request by Mathewlenning**
Removed a nested switch if/else construct the from JCacheStorageCachelite::clean method.

There is more that can be done here, but baby steps are better than buggy steps.

### CODE REVIEW

**Comment by zero-24** [comment]
@Mathewlenning can you update your PR? Github thinks we have merge conflicts<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6527">issues.joomla.org/joomla-cms/6527</a>.</sub>

**Comment by Mathewlenning** [comment]
How do I identify where a merge conflict could possibly be coming from?

**Comment by zero-24** [comment]
@Mathewlenning Now all is ok github is happy with you :)

>How do I identify where a merge conflict could possibly be coming from?

hmm i don't know maybe @roland-d can help here?

**Comment by Mathewlenning** [comment]
I think I figured it out the hard way. I just went to the folder in the Joomla repository and checked the history of the class. 

@roland-d I'm hoping you know a better way =^P

**Comment by roland-d** [comment]
@Mathewlenning @zero-24 To see merge conflicts you can click on the Details link. I assume you can see that as well :)
gh_status

**Comment by Mathewlenning** [comment]
@roland-d thanks but it seem like I can only see the details button on pull requests that can be automatically merged. This is what it looks like when there is a conflict

merge_conflicts

**Comment by roland-d** [comment]
@Mathewlenning Aha, that I didn't know. Someone with access will have to post the conflicts then.

**Comment by mbabker** [comment]
You can't see the conflicts via the GitHub UI.  If you're running git from a command line the easiest way is to fetch the current staging branch and merge it to your branch; git will show any conflicts.  FWIW, I see a "Merge pull request" button right now and no conflicts notice.

**Comment by Kubik-Rubik** [comment]
Thank you for creating this. It’s been some time since you created this and there are now some merge conflicts that prevent a direct merge. I will close this PR now. If you want to update your PR, then this can be re-opened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6527">issues.joomla.org/joomla-cms/6527</a>.</sub>

**Pull request closed without merging**
