### PR TITLE
Update jQuery Autocomplete to 1.4.10

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes
This PR updates [jQuery Autocomplete](https://github.com/devbridge/jQuery-Autocomplete) library to version [1.4.10](https://github.com/devbridge/jQuery-Autocomplete/releases/tag/v1.4.10) for **com_finder** and **mod_finder**.

### Testing Instructions
1. Apply patch
2. Test the **com_finder** and **mod_finder** typing any word in search field (for example, _joomla_)
3. Make sure there are no JS errors and the list dropdown displayed correctly.

### Result
**com_finder**
com_finder

**mod_finder**
mod_finder

### CODE REVIEW

**Comment by ChristineWk** [comment]
Apply Patch: Get response: Error The file marked for modification does not exist: media/jui/js/jquery.autocomplete.js 

Don't know if foll. infos are relevant, just add. FYI:
4.0.0-beta1-dev / Patchtester: 4.0.0-beta2/17oct2019
Konsole: some errors: jquery.min.js & core.min.js > useless expression

**Comment by wilsonge** [comment]
@ChristineWk this is a PR to staging :) it's correct that it won't apply to J4 branch :D

**Comment by ChristineWk** [comment]
@wilsonge 
ah thks - I see now (comment from HLeithner). As I jumped automatically to J 4 :-)

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 26b3cfdffaa7cd896ba516b237df865ecec256d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26974">issues.joomla.org/tracker/joomla-cms/26974</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 26b3cfdffaa7cd896ba516b237df865ecec256d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26974">issues.joomla.org/tracker/joomla-cms/26974</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26974">issues.joomla.org/tracker/joomla-cms/26974</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for updating our deps.

**Pull request merged**
