### PR TITLE
Add consistency in Permissions tabs

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Small PR

All items that allow permissions across the core: Articles, Menu, Fields (Articles, Contacts and Users) and Categories (Articles, Banners, Contacts, News Feeds and Field Groups in Articles, Contacts and Users) and all component Options have the last tab named "Permissions".

There is only two different: Modules and Global config, in case of the modules the tab is even called "Module Permissions" ...

image

image

So, this PR makes modules and global config behave like all the others views in this matter, ie, always the last tab and always with "Permissions" name.

### Testing Instructions

Very simple test. (30 sec)
- Apply patch
- Go to global config and check the last tab is "Permissions"
- Create/Edit a module and check the last tab is "Permissions"

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Shouldnt you change this as well?

screen shot 2016-11-09 at 13 02 07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12851">issues.joomla.org/tracker/joomla-cms/12851</a>.</sub>

**Comment by andrepereiradasilva** [comment]
oh didmn't notice that one. yes i will change.

**Comment by andrepereiradasilva** [comment]
done

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on a85cbb04d0b6ba66d0ebb9d1ddb74e7f31d7a245<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12851">issues.joomla.org/tracker/joomla-cms/12851</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on a85cbb04d0b6ba66d0ebb9d1ddb74e7f31d7a245<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12851">issues.joomla.org/tracker/joomla-cms/12851</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12851">issues.joomla.org/tracker/joomla-cms/12851</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC
Hey bot! :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12851">issues.joomla.org/tracker/joomla-cms/12851</a>.</sub>

**Comment by zero-24** [comment]
You calling me :p @jeckodevelopment what is wrong ;)

**Pull request merged**
