### PR TITLE
JFormRuleEquals doesnt take into account group

### PR DESCRIPTION
**Pull request by Devportobello**
The rule equals doesnt take into account group fields so we cant validate this rule.
## To reproduce the issue

Setup JForm XML form with a group + use field to validate equals:
ex:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<form>
  <fields name="example">
   <field name="name" type="text" ... />
    <field name="password" type="password"
      autocomplete="off"
      class="validate-password"
      description="DESIRED_PASSWORD"
      field="password"
      filter="raw"
      label="PASSWORD_LABEL"
      size="10"
      validate="password"
      required="true"
    />
    <field name="password2" type="password"
      autocomplete="off"
      class="validate-password"
      description="PASSWORD2_DESC"
      field="password"
      filter="raw"
      label="PASSWORD2_LABEL"
      message="PASSWORD1_MESSAGE"
      size="30"
      validate="equals"
      required="true"
    />
 </fields>
</form>
```

OR use this custom component: https://github.com/Devportobello/joomla-attach-PR-5979
## Expected result

Comparing password fields when password == password2 return true
## Actual result

Comparing password fields dont return true if password == password2
## System information

Joomla : Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
PHP : 5.5.12
Apache : 2.4.9
## Additional comments

Group are not taked into account when comparing value of those fields
### Test instructions
- Download ZIP of com_test at https://github.com/Devportobello/joomla-attach-PR-5979
- Install it.
- Have a look into components/com_test/models/fields/test.xml if you want to.
- Go to frontend home. Add /?option=com_test to URL.
- Type "test" on all password field
- Submit form, you will see an error message about password2 not equals
- Apply patch
- Type "test" on all password field
- Submit form, you will see <code>string 'OK' (length=2)</code> (used to exit code before save)

### CODE REVIEW

**Comment by Devportobello** [comment]
Added a custom component "See description https://github.com/joomla/joomla-cms/pull/5979#issue-56651202" to help test.

**Comment by Preview** [comment]
@test I followed the test instructions mentioned above and the patch worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5979">issues.joomla.org/joomla-cms/5979</a>.</sub>

**Comment by erikvandoorne** [comment]
I have tested this item :white_check_mark: successfully on a4f0cf1d00a172d593331f26c94c3d4482bcb4a4<br /><br />I tested this according to the test instructions and tested the patch to be OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5979">issues.joomla.org/joomla-cms/5979</a>.</sub>

**Comment by insitevision** [comment]
I have tested this item :white_check_mark: successfully on a4f0cf1d00a172d593331f26c94c3d4482bcb4a4<br /><br />Succesfully tested the patch according to the test instructions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5979">issues.joomla.org/joomla-cms/5979</a>.</sub>

**Comment by beneberle** [comment]
I just ran into this issue and confirmed the proposed patch solved my problem. Can we get it merged?

**Comment by mbabker** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5979">issues.joomla.org/joomla-cms/5979</a>.</sub>

**Comment by Devportobello** [comment]
Any milestone for this ? :)

**Comment by zero-24** [comment]
@joomla-cms-bot please help me here :smile:

**Comment by zero-24** [comment]
Can please someone with merge rights close this issue and remove the RTC label? It looks like the bot don't want to help me with this issue

**Comment by zero-24** [comment]
Thanks.

**Pull request closed without merging**
