### PR TITLE
[com_content] - add random order to featured view

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #15220 .

### Summary of Changes
add random order option to featured view

### Testing Instructions
featuredrandorder

### Expected result
you can select random order for featured articles

### Actual result
no random option

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4df84762678e18d0c2e9f942a20f87dae512cdd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15232">issues.joomla.org/tracker/joomla-cms/15232</a>.</sub>

**Comment by Quy** [comment]
Move it in the same position as in Category Blog.

article-order

**Comment by Open2logic** [comment]
Successfully tested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15232">issues.joomla.org/tracker/joomla-cms/15232</a>.</sub>

**Comment by Open2logic** [comment]
I have tested this item :white_check_mark: successfully on 4df84762678e18d0c2e9f942a20f87dae512cdd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15232">issues.joomla.org/tracker/joomla-cms/15232</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by Quy** [comment]
@alikon Just in case you didn't get the notification to move it to the same position as in Category Blog.

**Comment by zero-24** [comment]
Taking off RTC until @alikon got the time to move the option as suggested :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15232">issues.joomla.org/tracker/joomla-cms/15232</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@alikon PR ready for test?

**Comment by alikon** [comment]
i'd say no need to re-test again  cause i've only 

> Move it to the same position as in Category Blog.

you can simply swith to RTC on

**Comment by franz-wohlkoenig** [comment]
set RTC again

**Pull request merged**
