### PR TITLE
[4.0] Group categories toolbar buttons

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR continues the grouping of action buttons in the backend (see https://github.com/joomla/joomla-cms/pull/22832 and https://github.com/joomla/joomla-cms/pull/22393). This time the categories buttons.

### Testing Instructions
Go to any categories manager in the backend and check the toolbar. There should be a "Change status" dropdown now which activates when you select a category item.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cabe6e4e5ed92a1530a5376c30c857b03059fedc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23337">issues.joomla.org/tracker/joomla-cms/23337</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on cabe6e4e5ed92a1530a5376c30c857b03059fedc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23337">issues.joomla.org/tracker/joomla-cms/23337</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23337">issues.joomla.org/tracker/joomla-cms/23337</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
