### PR TITLE
[6.0] Remove deprecated db object from views

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Removes some deprecated database properties in views. They stayed to not break overrides during the upgrade from 3 to 4. But are not used anymore.

### Testing Instructions
- Create an article
- Open the article on the front tend

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/243
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by brianteeman** [comment]
Should this be documented ?

**Comment by laoneo** [comment]
Yes, just didn't had time.

**Comment by laoneo** [comment]
Added documentation

**Review by wilsonge — APPROVED** [review]

**Comment by Hackwar** [comment]
Can you fix the codestyle issues?

**Comment by laoneo** [comment]
done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b2603a5f2fc6f323c522e9bb4f0427b819d51fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42962">issues.joomla.org/tracker/joomla-cms/42962</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0b2603a5f2fc6f323c522e9bb4f0427b819d51fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42962">issues.joomla.org/tracker/joomla-cms/42962</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42962">issues.joomla.org/tracker/joomla-cms/42962</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
