### PR TITLE
[4.0] codename Mañana

### PR DESCRIPTION
**Pull request by alikon**
New Codename for Joomla 4: Mañana

### CODE REVIEW

**Comment by richard67** [comment]
@alikon How does that come? Who has decided for that name? Just am curious how it comes. But the new name fits well to our delayed project time schedule for J4. Maybe that was the reason? ;-)

**Comment by alikon** [comment]
It was a funny explanation from the "Spanish" folks of the expression "Mañana", which  does not exactly always means tomorrow ..... but sometimes/unpredictable in the future....... and some of us  thinked that :

> "_fits well to our delayed project time schedule for J4"_

but i prefer it is an hope 😃

**Comment by richard67** [comment]
@alikon Same as "domani" in Italian. E.g. if you need a hand worker to repair something in your home and you ask him when he can do that, he will say "mañana". And if you ask him again one day later he will say "mañana" ... and so on and so on ;-)

**Comment by brianteeman** [comment]
"professionalism"?

**Comment by alikon** [comment]
"un-professionalism" 🤣

**Comment by infograf768** [comment]
I guess `Inch’Allah` woud have also fit... 🤣

**Comment by richard67** [comment]
Btw. in Germany we do that differently: We don't say "tomorrow", we say "next year". See the new Berlin airport as a reference, which should have been finished since 10 years or so ;-)

**Comment by richard67** [comment]
But we also can see it positive: Mañana can also mean that J4 is the future, and as Tom Petty once sang: "The future is wide open" :-)

**Comment by klucon** [comment]
Which code name is correct?
In Joomla 4.0.0 - 4.0.3 is in ROOT / libraries / src / Version.php is "Furaha", but here is Mañana.
Thanks for the reply.

**Comment by zero-24** [comment]
> Which code name is correct?
> In Joomla 4.0.0 - 4.0.3 is in ROOT / libraries / src / Version.php is "Furaha", but here is Mañana.
> Thanks for the reply.

Furaha is the correct one starting from 4.0.0
Mañana was used in the development time.

**Comment by klucon** [comment]
Thank you :-)

**Comment by wilsonge** [comment]
Documented here https://docs.joomla.org/Joomla!_Codenames by the way :)

**Pull request merged**
