### PR TITLE
Rebased download system/environment information

### PR DESCRIPTION
**Pull request by phproberto**
This is a rebased version of https://github.com/joomla/joomla-cms/pull/6021 See description there

I have added suggestions by @roland-d and small code style fixes.

---

https://github.com/joomla/joomla-cms/pull/6021
Implementing a possibility to download system/environment information for support purposes.
The output is a text file which is probably not the best solution. Hope for some input. 
It adds a button in "administrator/index.php?option=com_admin&view=sysinfo" which allows to create a text file with all relevant settings.
All sensitive informations should have been removed.

### CODE REVIEW

**Comment by dgt41** [comment]
@phproberto I  get both on json and txt the following error code in the beginning of the files:
```
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Trying to get property of non-object in /Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/models/sysinfo.php on line <i>424</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0008</td><td bgcolor='#eeeeec' align='right'>249968</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/index.php' bgcolor='#eeeeec'>../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0791</td><td bgcolor='#eeeeec' align='right'>3301872</td><td bgcolor='#eeeeec'>JApplicationCms->execute(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/index.php' bgcolor='#eeeeec'>../index.php<b>:</b>47</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0791</td><td bgcolor='#eeeeec' align='right'>3302176</td><td bgcolor='#eeeeec'>JApplicationAdministrator->doExecute(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/cms/application/cms.php' bgcolor='#eeeeec'>../cms.php<b>:</b>252</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1283</td><td bgcolor='#eeeeec' align='right'>5060400</td><td bgcolor='#eeeeec'>JApplicationAdministrator->dispatch(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/cms/application/administrator.php' bgcolor='#eeeeec'>../administrator.php<b>:</b>152</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1316</td><td bgcolor='#eeeeec' align='right'>5185216</td><td bgcolor='#eeeeec'>JComponentHelper::renderComponent(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/cms/application/administrator.php' bgcolor='#eeeeec'>../administrator.php<b>:</b>98</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.1379</td><td bgcolor='#eeeeec' align='right'>5280664</td><td bgcolor='#eeeeec'>JComponentHelper::executeComponent(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/cms/component/helper.php' bgcolor='#eeeeec'>../helper.php<b>:</b>372</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.1383</td><td bgcolor='#eeeeec' align='right'>5301608</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/admin.php'</font> )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/cms/component/helper.php' bgcolor='#eeeeec'>../helper.php<b>:</b>392</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.1564</td><td bgcolor='#eeeeec' align='right'>6111072</td><td bgcolor='#eeeeec'>JControllerLegacy->execute(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/admin.php' bgcolor='#eeeeec'>../admin.php<b>:</b>16</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>0.1564</td><td bgcolor='#eeeeec' align='right'>6111552</td><td bgcolor='#eeeeec'>JControllerLegacy->display(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/legacy/controller/legacy.php' bgcolor='#eeeeec'>../legacy.php<b>:</b>728</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>0.1706</td><td bgcolor='#eeeeec' align='right'>6706704</td><td bgcolor='#eeeeec'>AdminViewSysinfo->display(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/libraries/legacy/controller/legacy.php' bgcolor='#eeeeec'>../legacy.php<b>:</b>690</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>0.1707</td><td bgcolor='#eeeeec' align='right'>6707248</td><td bgcolor='#eeeeec'>AdminViewSysinfo->getLayoutData(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/views/sysinfo/view.text.php' bgcolor='#eeeeec'>../view.text.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>0.2160</td><td bgcolor='#eeeeec' align='right'>7192304</td><td bgcolor='#eeeeec'>AdminModelSysInfo->getSafeData(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/views/sysinfo/view.text.php' bgcolor='#eeeeec'>../view.text.php<b>:</b>80</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>0.2160</td><td bgcolor='#eeeeec' align='right'>7192784</td><td bgcolor='#eeeeec'>AdminModelSysInfo->getExtensions(  )</td><td title='/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_admin/models/sysinfo.php' bgcolor='#eeeeec'>../sysinfo.php<b>:</b>318</td></tr>
</table></font>
```

**Comment by dgt41** [comment]
@phproberto take a look at https://github.com/phproberto/joomla-cms/pull/1

**Comment by phproberto** [comment]
@dgt41 I have a applied a different fix in https://github.com/joomla/joomla-cms/commit/c50f6ef6869fab034bfc97d529d40d9943e42a25 after realising that some extensions manifest may not be cached in the database. 

The best example I found was plg_weblinks on my own website

**Comment by dgt41** [comment]
@test ok Thanks @Radek-Suski @phproberto

**Comment by roland-d** [comment]
@phproberto Should we be outputting the host paths in the PATH, SystemRoot, COMSPEC, WINDIR, error_log, extension_dir, include_path, upload_tmp_dir, and session.save_path variables?

**Comment by phproberto** [comment]
> @phproberto Should we be outputting the host paths in the PATH, SystemRoot, COMSPEC, WINDIR, error_log, extension_dir, include_path, upload_tmp_dir, and session.save_path variables?

@roland-d  in my opinion anything that gets private info that may involve security issues should be skipped. I don't see issues with paths relative to system libs. Maybe **Phil Taylor** (I forgot his github username) can help us here. I'll ping him to see if he can check it.

* [ ] **PATH**. I need more info
* [ ] **SystemRoot**. I need more info. Windows thing?
* [ ] **WINDIR**. I need more info. Windows thing?
* [x] **error_log**. Already disabled
* [x] **extension_dir**. Not dangerous IMO
* [x] **include_path**. Not dangeour IMO
* [x] **upload_tmp_dir**. Already disabled
* [x] **session.save_path**. Already disabled

**Comment by PhilETaylor** [comment]
@PhilETaylor :-) 

The %SystemRoot% variable is a special system-wide environment variable found on Windows NT and its derivatives. Its value is the location of the system directory, including the drive and path.

The %WINDIR% is where windows is installed, E.g c:\windows

All of the information in your post is available to hackers with a single line of code anyway - so as long as the exporting of this information is restricted to Super Admins, authenticated and logged in, then its no more of a security risk while displaying the data on the site. 

Those that argue otherwise, would probably be the people still recommending moving configuration.php outside the public_html folder - doh! 

What is done with the information AFTER it is extracted is another matter - when its posted in open forum etc... thats when this becomes a "security" issue.  

Knowing these paths for support purposes is not normally needed, what is more important is a check that the path actually exists, and is writable most of the time. One doesn't care where they are configured to point at, one cares if they are useable. 

extension_dir should probably never be writable as this is a system folder and not a folder PHP should have access to on a per site basis

Quite frankly if you are having issues with include_path, upload_tmp_dir, and session.save_path then you need a better webhost - these should be set on a hosting level and not messed around with on a per Joomla install level.

**Comment by wilsonge** [comment]
@PhilETaylor this is information to export. So I'd see the most likely use case as a user giving this info to extension dev's to replicate environments etc

**Comment by PhilETaylor** [comment]
Then the question is how much do you trust extension developers :-) 

Exporting absolute paths will not help extension developers replicate environments...

**Comment by Radek-Suski** [comment]
I was trying to remove all security relevant data from the output. I agree with Phil. The issue is when someone will post these data in forum etc

**Comment by phproberto** [comment]
I have removed the information that won't help in any way to replicate enviroments. I think is better that we are more restrictive and then wait for someone asking that some information would be useful.

I'd like that a Windows user confirms that there is no private information shared there.

**Comment by phproberto** [comment]
BTW thanks @PhilETaylor for checking it!

**Comment by PhilETaylor** [comment]
No worries :-)

**Comment by brianteeman** [comment]
Tested and it works BUT

1. Is there a reason that the order of each section in the download does not match the order of the tabs.

2. I think it would be better if the name of each section matched the name of the tabs

3. When hiding information in the download sometimes `xxxxxx` is used and sometimes `set` I think it is better to be consistent and use `xxxxxx` or was there a specific reason to do this differently that I missed
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by phproberto** [comment]
Thanks for the feedback @brianteeman.

I have rebased the PR against latest staging and based in your comments:

* Both text + json sections now follow the tabs order.
* Text file sections now use same titles than the tabs + additional string for Extensons.
* JSON still uses same keys instead of titles because using translatable titles here would make harder  process the file with external tools.
* For consistency I replaced `set` with `xxxxxx`. Old `not set` strings will just be empty. That way is easier to track all the information that has been set as private.

**Comment by infograf768** [comment]
Any reason not to translate the number of seconds used in the title of the file produced to a real date as this number looks like it is the time elapsed since the epoch time?

**Comment by infograf768** [comment]
Something like:
```
$today = microtime(true);
$today = date("Y-m-d_H-i-s");
[...]
header('Content-Disposition: attachment; filename="systeminfo-' . $today . '.txt"');
```

**Comment by roland-d** [comment]
@phproberto Can you follow up on @infograf768 question? Thanks.

**Comment by phproberto** [comment]
PR updated and @infograf768 's suggestion to get a human readable date implemented.

Thanks!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c823c3e5caef60d5ebf06a6e8452e7fce03977e5<br /><br />Works great. Filename is now something like: `systeminfo-2015-11-03T09-43-44+01-00.json` and `systeminfo-2015-11-03T09-43-30+01-00.txt`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by peterpeter** [comment]
I have tested this item :white_check_mark: successfully on c823c3e5caef60d5ebf06a6e8452e7fce03977e5<br /><br />Obviously the security issues are clarified. Technically it works perfekt.

As those informations are for supporters, some toughts of me as a forum moderator/supporter: 

Due to extensions, important infos for supporting are (beside others of course):
- what 3rd party extensions are installed (id > 700, #__extensions)
- wich plugins are published and their (fire-)ordering
- wich templates are involved/having page assignments

Core Components whow are maintained by the core are mostly irrelevant for support. And Modules too, as they 'living' all in their own 'universe', not interfere/manipulate with other extension parts. Templates who are not involved are irrelevant.

But I think that's all stuff for another rainy day :smile: 

But for the first implementation I would advise to add the publish state at least for plugins and modules, and ordering of the plugins groupwise + ordering ASC


Just my 20 cents. But anyway, it's a helpful feature for the future. Thanks for the work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by peterpeter** [comment]
I have tested this item :white_check_mark: successfully on c823c3e5caef60d5ebf06a6e8452e7fce03977e5<br /><br />Obviously the security issues are clarified. Technically it works perfekt.

As those informations are for supporters, some toughts of me as a forum moderator/supporter: 

Due to extensions, important infos for supporting are (beside others of course):
- what 3rd party extensions are installed (id > 700, #__extensions)
- wich plugins are published and their (fire-)ordering
- wich templates are involved/having page assignments

Core Components whow are maintained by the core are mostly irrelevant for support. And Modules too, as they 'living' all in their own 'universe', not interfere/manipulate with other extension parts. Templates who are not involved are irrelevant.

But I think that's all stuff for another rainy day :smile: 

But for the first implementation I would advise to add the publish state at least for plugins and modules, and ordering of the plugins groupwise + ordering ASC


Just my 20 cents. But anyway, it's a helpful feature for the future. Thanks for the work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by peterpeter** [comment]
Obviously the security issues are clarified. Technically it works perfekt.

As those informations are for supporters, some toughts of me as a forum moderator/supporter: 

Due to extensions, important infos for supporting are (beside others of course):
- what 3rd party extensions are installed (id > 700, #__extensions)
- wich plugins are published and their (fire-)ordering
- wich templates are involved/having page assignments

Core Components whow are maintained by the core are mostly irrelevant for support. And Modules too, as they 'living' all in their own 'universe', not interfere/manipulate with other extension parts. Templates who are not involved are irrelevant.

But I think that's all stuff for another rainy day :smile: 

But for the first implementation I would advise to add the publish state at least for plugins and modules, and ordering of the plugins groupwise + ordering ASC


Just my 20 cents. But anyway, it's a helpful feature for the future. Thanks for the work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by zero-24** [comment]
Thanks lets RTC here and you can send you improvments with another PR or open a new issue for it ok? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7129">issues.joomla.org/joomla-cms/7129</a>.</sub>

**Comment by peterpeter** [comment]
Sure, that's what I mean with
"But I think that's all stuff for another rainy day :smile:"

**Pull request closed without merging**
