### PR TITLE
Revert "[5.0] Error Pages language (#41934)"

### PR DESCRIPTION
**Pull request by HLeithner**
This reverts commit 1d137d590cad96aabc52ec7b38a825965eb3c001.

Pull Request for Issue #42016 .

### Summary of Changes
Removed the comment for translators, better fix would be to update our build tools to support this syntax but for now I revert the change.

### CODE REVIEW

**Comment by richard67** [comment]
It would work if the comment was not at the end of the string but in a separate line above the string.

The standard ini file syntax doesn't support inline comments, only complete comment lines, that's why the js ini file parser doesn't work with these strings.

**Comment by tecpromotion** [comment]
Then, from the translators' point of view, we should please put the comment above.

**Comment by brianteeman** [comment]
yes - doing a pr to fix the bug now. Dont know why there was such a rush to revert it instead of giving time to fix it

**Comment by HLeithner** [comment]
> Then, from the translators' point of view, we should please put the comment above.

that doesn't work for crowdin

> https://github.com/joomla/joomla-cms/pull/42019#issuecomment-1742776096

because I didn't see any pr for it yet.

**Comment by tecpromotion** [comment]
> > Then, from the translators' point of view, we should please put the comment above.
> 
> that doesn't work for crowdin

ok

**Pull request closed without merging**
