### PR TITLE
[4.0] Admin login Module

### PR DESCRIPTION
**Pull request by brianteeman**
updated link to forgot password to indicate opens in a new window

image

### CODE REVIEW

**Comment by Quy** [comment]
These too:

```
You can find help here:

    Joomla! Support Forum
    Joomla! Documentation
    Joomla! News
```

**Comment by brianteeman** [comment]
They are content.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ca4134ba597c680702370324c55228321d5c49cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28007">issues.joomla.org/tracker/joomla-cms/28007</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ca4134ba597c680702370324c55228321d5c49cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28007">issues.joomla.org/tracker/joomla-cms/28007</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28007">issues.joomla.org/tracker/joomla-cms/28007</a>.</sub>

**Pull request merged**
