### PR TITLE
Standardise on  break in php - code style

### PR DESCRIPTION
**Pull request by brianteeman**
Standardise on using `<br />` in our code as discussed #5711

### CODE REVIEW

**Comment by rdeutz** [comment]
Did a code review and it looks good to me!

**Comment by brianteeman** [comment]
thanks - cant see any other way to really test other than a code review so
can this be RTC

On 13 January 2015 at 20:26, Robert Deutz <notifications@github.com> wrote:

> Did a code review and it looks good to me!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5713#issuecomment-69813388>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rdeutz** [comment]
The person who is doing the merge will check it again, it is so simple so this should be enough.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5713">issues.joomla.org/joomla-cms/5713</a>.</sub>

**Comment by wilsonge** [comment]
Merged. Thanks

**Pull request merged**
