### PR TITLE
[mod_footer]XML code style

### PR DESCRIPTION
**Pull request by wojsmol**
### Summary of Changes

Code style changes for mod_footer
### Testing Instructions

code review

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d7e0bff36efd55e08a25fb220f9c1a1212164d8e<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10584">issues.joomla.org/joomla-cms/10584</a>.</sub>

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on d7e0bff36efd55e08a25fb220f9c1a1212164d8e<br /><br />On code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10584">issues.joomla.org/joomla-cms/10584</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10584">issues.joomla.org/joomla-cms/10584</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10584">issues.joomla.org/joomla-cms/10584</a>.</sub>

**Pull request closed without merging**
