### PR TITLE
#6967 Compact list of tagged items. New option Items to List

### PR DESCRIPTION
**Pull request by ghost**
See feature request https://github.com/joomla/joomla-cms/issues/6987
Menu item type _Compact list of tagged items_.
This PR adds a new option _# Items to List_ like in menu item type _Articles > Category List_.
It removes old option _Item Selection Options > Maximum Items_ because not needed anymore.

Test instructions:
- Create a tag.
- Apply it to several items (20, 30 ...) like articles, categories, contacts...  It's easy with button Batch.
- Create a menu item of type _Compact list of tagged items_ and select above tag.
- Save & Close.
- Open in frontend but do not touch limit box yet!!!
- Number of diplayed items = _Default List Limit_ in Global Configuration of Joomla.
  (If not delete cookie [= kill session], clear browser cache and reload page).
  tags-limitbox
- Apply patch.
- Reload page in frontend. Nothing changed. Do not touch limit box yet!!!
- Backend > open menu item.
- Change new option List Layouts > _# Items to List_. E.g. to 5
  tags-limitbox2
- Reload page in frontend.
  tags-limitbox3

### CODE REVIEW

**Comment by brianteeman** [comment]
Issue confirmed
PR Resolves it BUT
Why is it linked to displaying the limit box?
"Default number of tagged items to list on a page. Only if limit box is shown (Display Select: Show).

If you look at category list menu item for example there is not connection to displaying the limit box<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7031">issues.joomla.org/joomla-cms/7031</a>.</sub>

**Comment by bertmert** [comment]
Yes, I know. I wondered too. I don't know why. I tried to make this "strange connection" a bit more transparent for users by text.

I had to search inside PHP code to find this solution for limiting items (before PR)
https://github.com/joomla/joomla-cms/issues/6987#issuecomment-105132102

**Comment by brianteeman** [comment]
Just doesnt seem right to me and its not consistent

**Comment by bertmert** [comment]
The old behaviour doesn't seem right to you? Or the new one combined with old one?

**Comment by brianteeman** [comment]
The requirement to display the list box.

**Comment by bertmert** [comment]
I share the same opinion right from the start. I will work over the PR, remove old maximum field that we don't need any more. I close PR just for a short time to avoid tests.

**Comment by brianteeman** [comment]
It should work the same as category list

**Comment by bertmert** [comment]
Removed old field|option *maximum|Maximum Items* and dependency on field *Display Select*.

**Comment by bertmert** [comment]
If this RP works error free same feature, same changes should be applied to menu item type *Tags » Tagged Items* (with another PR please).

**Comment by BuddhiEash** [comment]
This patch works.But i'm bit confused because without the patch too it's working here.Only difference is once i added the patch i can manually set the starting value for the dropdown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7031">issues.joomla.org/joomla-cms/7031</a>.</sub>

**Comment by shre001** [comment]
@this works

**Comment by bertmert** [comment]
@BuddhiEash Read the discussion here and my linked comment in related issue and you'll see the difference.

**Comment by BuddhiEash** [comment]
bertmert : Got that point :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7031">issues.joomla.org/joomla-cms/7031</a>.</sub>

**Comment by zero-24** [comment]
Thanks for coding and testing :+1: Moving to RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7031">issues.joomla.org/joomla-cms/7031</a>.</sub>

**Comment by roland-d** [comment]
@bertmert Can you have a look at the conflicts please? Once done I can merge it for 3.5. Thanks.

**Comment by bertmert** [comment]
@roland-d 

> Can you have a look at the conflicts please?

Sorry, I don't understand. Which conflicts?

**Comment by zero-24** [comment]
Merge conflicts ;)

**Comment by bertmert** [comment]
And again I've forgotten how to solve it

**Comment by brianteeman** [comment]
You cant solve merge conflicts with GUI ;(

**Comment by zero-24** [comment]
the fasted solution (with the GUI) is close here and open a new PR (with the same changes) based on the current code base.

via cli:
git checkout patch-20
git pull upstream staging
<git tell you here which files has conflicts so they need to be fixed local)
git commit -am 'fix merge conflicts'
git push origin patch-20

**Comment by bertmert** [comment]
Thank u for informations @brianteeman and @zero-24 
will open new one

**Comment by bertmert** [comment]
Closed because merge conflict. See new https://github.com/joomla/joomla-cms/pull/8116

**Pull request closed without merging**
