### PR TITLE
[3.9] Message reporting changed to error type

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull Request for Issue #24177 

### Summary of Changes
Changed the message reporting at the time of log in to error type.

### Expected result
The message should be of warning type

### Actual result
The message is green, a positive and successful action.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by HLeithner** [comment]
Isn't this an error?

**Comment by hardik-codes** [comment]
> Isn't this an error?

In the issue it was mentioned by @kofaysi to make it to warning type that's why I made it warning type

**Comment by HLeithner** [comment]
please change it to error.

**Comment by hardik-codes** [comment]
> please change it to error.

Ok I'll do so

**Comment by hardik-codes** [comment]
Now have a look @HLeithner

**Comment by HLeithner** [comment]
thx, now we need 2 testers.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 35becdf03e1aefbdb315cc43ebb2675a30803b4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24200">issues.joomla.org/tracker/joomla-cms/24200</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 35becdf03e1aefbdb315cc43ebb2675a30803b4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24200">issues.joomla.org/tracker/joomla-cms/24200</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by zero-24** [comment]
Merging this into Joomla 3.9.5 now thanks @hardik-codes for your first contribution to Joomla. 🎉

**Comment by hardik-codes** [comment]
> Merging this into Joomla 3.9.5 now thanks @hardik-codes for your first contribution to Joomla. tada

Thanks @zero-24, but I have contributed to Joomla before as well and will continue to do the same.

**Comment by zero-24** [comment]
Hmm GitHub fooled me than. It showed `first contribution` to me. But anyway thanks and good to hear 👍

**Pull request merged**
