### PR TITLE
[4.1] cs

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Use single quote to remove escaping double quotes.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 17dd5e26da92a5d73542869de12fafed368ce9aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36627">issues.joomla.org/tracker/joomla-cms/36627</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 17dd5e26da92a5d73542869de12fafed368ce9aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36627">issues.joomla.org/tracker/joomla-cms/36627</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36627">issues.joomla.org/tracker/joomla-cms/36627</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
