### PR TITLE
[5.0] Fix broken npm on windows, pkg lock file update, and tinymce 6.7.3 update

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
npm fell out of the window

test fix for issue https://github.com/joomla/joomla-cms/issues/42356 .
And tinymce update to 6.7.3

### Testing Instructions
run npm install on Windows

### Actual result BEFORE applying this Pull Request
not works

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
Works on win11 , xampp, node.js 20.9.0

**Comment by Fedik** [comment]
Okay, interesting.
I not sure what maintainers doing with this file.
I have generated a new. 
This also updates TinyMCE to 6.7.3, and other libs mainly dev.

**Comment by brianteeman** [comment]
for the tinymce update (which is a security update) you will need to run the full npm install to generate the updated xml

**Comment by drmenzelit** [comment]
Works on MacOS Sonoma 14.1.1, node 21.2.0 and npm 10.2.3

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on fe293e4735ae0dc96ba10b94abe229c1a729328b<br /><br />Works for me on win11, xampp, node 20. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42361">issues.joomla.org/tracker/joomla-cms/42361</a>.</sub>

**Comment by Fedik** [comment]
Already should be fixed, without this PR

**Comment by brianteeman** [comment]
What makes you think that. Still not working

**Comment by Fedik** [comment]
Release managers told me :)

**Pull request closed without merging**
