### PR TITLE
[4.x][build tools] [NO CACHE]  Use the embeded sass

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request is a redo of https://github.com/joomla/joomla-cms/pull/33170

### Summary of Changes
- Change the SASS package
- perf gains (less time for compilation of sass) read more here: https://sass-lang.com/blog/embedded-sass-is-live

### Testing Instructions
Before applying this PR run `npm install` on a clean git fork and move the media folder with another name (eg media_old)
Apply this PR and run again `nom install` 
compare the folders `media` and `media_old` should be the same

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Well NO.

**Comment by brianteeman** [comment]
What was wrong?

**Comment by dgrammatiko** [comment]
I have no clue, Drone failed and last time we spend months trying to fix the same thing unsuccessfully (I think the npm container is missing git)...

**Comment by brianteeman** [comment]
Sounds like the same problem we had with jooa11y  that was fixed

**Comment by dgrammatiko** [comment]
> Sounds like the same problem we had with jooa11y that was fixed

Where? The drone is pulling the alpine container of npm: https://github.com/joomla/joomla-cms/blob/88b03dd506233117f7225140387ad0ad365d6a5f/.drone.yml#L26-L31

**Comment by HLeithner** [comment]
@dgrammatiko started it manually but didn't solved the issue or is this another issue?

**Comment by dgrammatiko** [comment]
@HLeithner could you pass me the error log `/root/.npm/_logs/2022-02-02T14_21_15_036Z-debug.log` ?

Remote debugging without access is kinda Houdini tricks...

**Pull request closed without merging**
