### PR TITLE
[4.1] Remove ! in task title

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove exclamation point in task title.

### Testing Instructions
Code review.
or 
Create a new task.
See title without exclamation point.

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 73a23c7bd8cfa2c7afbb6fb331773568407bce86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36270">issues.joomla.org/tracker/joomla-cms/36270</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 73a23c7bd8cfa2c7afbb6fb331773568407bce86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36270">issues.joomla.org/tracker/joomla-cms/36270</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36270">issues.joomla.org/tracker/joomla-cms/36270</a>.</sub>

**Comment by wojsmol** [comment]
@alikon Please readd labels.

**Comment by alikon** [comment]
@wojsmol the  joomla-cms-bot sometime do strange things

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
