### PR TITLE
[4.0] Changes in Toolbar, separate Save (and stay) button from Save button …

### PR DESCRIPTION
**Pull request by drmenzelit**
…group

Pull Request for Issue #21989

### Summary of Changes

All edit views were changed to separate Save (and stay) button from Save button group

### Expected result

A "Save" button and a "Save & Close" / "Save & New" button group

### Actual result

Save is integrated in the grouped button

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 0ca1857bbf5a4d53ddb113f065e88c547ff60836<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23942">issues.joomla.org/tracker/joomla-cms/23942</a>.</sub>

**Comment by brianteeman** [comment]
In the design document and #21989 the same icon is used for the save button and the save as grouped button. In this pr there are two different icons

**Comment by coolcat-creations** [comment]
I would recommend to merge this (After tests) and take the Icons for the discussion of a second PR. Then we could maybe discuss also if we use the wording „apply“ instead of save. But for now this PR solves a big UX issue and would be great to have.

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on 0a6fbd5a5d6ab1057056c14ecf3b9259885f077b<br /><br />Tested on:
Joomla! 4.0.0-alpha7-dev successfully

Tags<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23942">issues.joomla.org/tracker/joomla-cms/23942</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by puneet0191** [comment]
@HLeithner seems to work now, please merge this asap so we can have other PR's also green

**Comment by HLeithner** [comment]
@puneet0191 you have to write faster ;-)

**Comment by puneet0191** [comment]
and also less, I wrote too many words :stuck_out_tongue:

**Pull request merged**
