### PR TITLE
Add LDAP to Appveyor

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue "need LDAP for some future testing"
See comment for request from @wilsonge https://github.com/joomla/joomla-cms/pull/17081#issuecomment-320436677

### Summary of Changes
Follow symfony/polyfill appveyor setup https://github.com/symfony/polyfill/blob/master/appveyor.yml to enable LDAP

### Testing Instructions
merge by code review

### Expected result
Appveyor tests pass and do not throw warnings like missing extension

### Documentation Changes Required
none

### CODE REVIEW

**Comment by photodude** [comment]
@wilsonge @mbabker Any thoughts on how to verify that this worked (other than just throwing `php -m` into appveyor to get an echo list)?

**Comment by wilsonge** [comment]
Take back out `--ignore-platform-reqs` from `composer install` and see if composer now installs dependencies on appveyor?

**Comment by wilsonge** [comment]
Merged on review. Appveyor `composer install` now works (the fails are cause of libsodium polyfill) and drone also unrelated

**Comment by photodude** [comment]
Thanks @wilsonge

**Pull request merged**
