### PR TITLE
[5.2] [Guided Tours] unescaped quotes in a language string

### LINKED ISSUE #45443: Cookie Manager
### Is your feature request related to a problem? Please describe.
Many countries and regions have passed laws regulating cookies over the last decade, but Joomla still doesn't have a cookie manager out of the box, which is what almost every website needs, and if all websites need this tool to comply with the laws of many countries and regions, then it should be part of Joomla's core.

California Consumer Privacy Act (CCPA/CPRA) - 🇺🇸 USA
Personal Information Protection Law (PIPL) - 🇨🇳 China
Lei Geral de Proteção de Dados (LGPD) - 🇧🇷 Brazil
Digital Personal Data Protection Act (DPDPA) - 🇮🇳 India
Protection of Personal Information Act (POPIA) - 🇿🇦 South Africa
Personal Data Protection Act (PDPA) - 🇸🇬 Singapore
Revised Data Protection Act (UK GDPR) - 🇬🇧 United Kingdom
Swiss Data Protection Act (Revised 2023) - 🇨🇭 Switzerland
Personal Information Protection and Electronic Documents Act (PIPEDA) - 🇨🇦 Canada
Act on the Protection of Personal Information (APPI) - 🇯🇵 Japan
Personal Information Protection Act (PIPA) - 🇰🇷 South Korea

### Describe the solution you'd like
I propose to create a `Cookie Manager` extension for @Joomla

The cookie categories should be something like this:

**By Source**
- **1st party cookies:** created when one visits a website to remember preferences (i.e. cart items, login details, or language settings). These expire when the browser closes and are typically session-based.
- **3rd party cookies:** placed by external partners/domains (i.e. analytics tools, advertisers etc ) to track cross-site behavior for analytics and targeted ads. These raise privacy concerns and persist longer...

**By Functionality**
- **Strictly necessary Cookies:** required for a website's core functionality (i.e. shopping cart, login etc). ✅
- **Performance/Analytics Cookies:** tracks user interactions (i.e. page visits, bounce rates) mostly to optimize a site's performance. ⚠️ GDPR requires consent.
- **Functional Cookies:** enables non-essential features (i.e. preferences saving). ⚠️ GDPR requires consent.
- **Targeting Cookies:** used for ad personalization. ⚠️ GDPR requires explicit consent.

**By Security Attributes**
- **Secure cookies:** to prevent interception, these are only transmitted only over HTTPS.
- **HTTP-only cookies:** they protect sensitive data and block access to client-side script
- **SameSite cookies:** to mitigate CSRF attacks, they restrict cross-site sharing.

✅ - Consent is not required under GDPR.
⚠️ - GDPR requires consent — in some cases, explicit consent before use.

### Additional context
I made this feature request based on an article from [Joomla Magazine](https://magazine.joomla.org/all-issues/april-2025/i-m-a-good-cookie-monster).
 Best practices for cookie notices - [https://web.dev/articles/cookie-notice-best-practices](https://web.dev/articles/cookie-notice-best-practices)
Wiki - [https://en.wikipedia.org/wiki/HTTP_cookie#EU_cookie_directive](https://en.wikipedia.org/wiki/HTTP_cookie#EU_cookie_directive)

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request for Issue # .

### Summary of Changes

see #44106 

add `\`

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

`class="fw-medium"`

### Expected result AFTER applying this Pull Request

`class=\"fw-medium\"`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 20b5c7c0915197492d05c460de190251a94528e0<br /><br />code revieuw<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44110">issues.joomla.org/tracker/joomla-cms/44110</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 20b5c7c0915197492d05c460de190251a94528e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44110">issues.joomla.org/tracker/joomla-cms/44110</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44110">issues.joomla.org/tracker/joomla-cms/44110</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for your contribution @tecpromotion!

**Pull request merged**
