### PR TITLE
Fix strtotime() warnings on PHP 8

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes use of `strtotime()` in favor of string comparison for dates.

### Testing Instructions

Use 32-bit version of PHP 8.0.0 RC1 or newer dev build.
Create an article. Don't set `Finish Publishing` date.
View article list/blog/featured view containing the article in frontend.
View the article in frontend.

### Actual result BEFORE applying this Pull Request

>Warning: strtotime(): Epoch doesn't fit in a PHP integer 

### Expected result AFTER applying this Pull Request

No warnings.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
Unfortunately I don't have the required testing environment, 32-bit version of PHP 8.0.0 RC1 or newer dev build.

But from code review it's absolutely clear what this PR does, and it makes sense, first check for the null date and then to a strtotime for the other check, and not vice versa.

@HLeithner What do you think? Would you count a good code review as a good test, too?

**Comment by infograf768** [comment]
@SharkyKZ 
Can you also fix it here
https://github.com/joomla/joomla-cms/blob/a1ecbc25056ba6eb5d762c44f18e3c8bddc6fdab/components/com_contact/tmpl/category/default_items.php#L113-L126

**Comment by SharkyKZ** [comment]
@infograf768 Will do. But I'm starting to question the validity of this fix. It has a limited range:

>The valid range of a timestamp is typically from Fri, 13 Dec 1901 20:45:54 UTC to Tue, 19 Jan 2038 03:14:07 UTC. (These are the dates that correspond to the minimum and maximum values for a 32-bit signed integer.) 

I guess we should account for values outside this range?

**Comment by infograf768** [comment]
I was born after 1901 and 2038 would mean I would be 90. Can't project so far. ;) 
But this says that anyway code will have to be modified in 2038. 
https://www.unixtimestamp.com/ (unix starts in 1970 btw)

https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by SharkyKZ** [comment]
Do we even need `strtotime()` here? Looks like we could be comparing date strings instead.

**Comment by richard67** [comment]
> Do we even need `strtotime()` here? Looks like we could be comparing date strings instead.

@SharkyKZ Where do you mean? For the greater than or lower than comparisons we can only use strings if we can 100% be sure that they are in ISO format.

**Comment by SharkyKZ** [comment]
Dates returned from the databases should always be the same format, right?

**Comment by richard67** [comment]
@SharkyKZ Yes, but the question is not if it is the same format always but if this format means that alphabetical sorting is equal to sorting by date and time, and this is not given for a format like e.g. "DD.MM.YYYY hh:nn:ss". Alphabetical sorting is only equal to sorting by date and time if the order of the time periods "year, month, day ... seconds" is either ascending or descending with the length of these periods, and if the number of digits used for each period is always the same, i.e. it will not work when using only 1 digit for months 1 to 9.

So the ISO formats (short or long) fulfil this, they go from year down to second: "YYYY-MM-DD hh:mm:ss".

It would theoretically also work with "ss:mm:hh DD-MM-YYYY", but nobody really uses that.

So if you can be 100% sure that the string representation is always the same ISO format, then you can compare strings like times.

But if not, then you have to force this format.

**Comment by SharkyKZ** [comment]
But dates from the database are always going to be in `YYYY-MM-DD hh:mm:ss`  (or `Y-m-d H:i:s` in PHP terms) format across all supported databases and locales?

**Comment by richard67** [comment]
> But dates from the database are always going to be in `YYYY-MM-DD hh:mm:ss` (or `Y-m-d H:i:s` in PHP terms) format across all supported databases and locales?

@SharkyKZ Exactly that's what I'm not 100% sure about. At least on MS SQL Server it might be different.

**Comment by richard67** [comment]
@SharkyKZ I'd stay with the strtotime to play safe.

**Comment by SharkyKZ** [comment]
We can't use `strtotime()` because of the limitations. And we do only support `Y-m-d H:i:s` format for database dates. Database API can support different formats but this doesn't concern the CMS.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/30921#issuecomment-706722408

**Comment by SharkyKZ** [comment]
I'll do that later. It's for 4.0 anyways. There's also same issue in calendar field on 4.0.

**Comment by roland-d** [comment]
Like Richard I don have a 32-bit environment either, who does :thinking: However code review looks good.

**Comment by HLeithner** [comment]
@roland-d can you test on a 64bit system?

**Comment by bayareajenn** [comment]
also @roland-d will you see if Patch Tester gives you this PR in PHP8? :)

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on bbcb7bf72dd069640473dda8ce1bdcf6827b3c6b<br /><br />I tested on 64 bit PHP8. Added article. Added cat blog, cat list, single article, featured on the frontend. No errors. Couldn't find it broke anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30921">issues.joomla.org/tracker/joomla-cms/30921</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bbcb7bf72dd069640473dda8ce1bdcf6827b3c6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30921">issues.joomla.org/tracker/joomla-cms/30921</a>.</sub>

**Comment by richard67** [comment]
@gostn Which PHP version did you use? 8? If so: 32 or 64 bit?

**Comment by ghost** [comment]
ups i forgot i'm a troll https://github.com/joomla/joomla-cms/pull/30716#issuecomment-736284377

**Comment by HLeithner** [comment]
> ups i forgot i'm a troll [#30716 (comment)](https://github.com/joomla/joomla-cms/pull/30716#issuecomment-736284377)

not sure what you mean with this but in this case it's important to know which version you tested. (I mean it's always a useful information)

**Comment by ghost** [comment]
if you read the comment you wll understand that asking by one who call you a troll is …

**Comment by HLeithner** [comment]
ok @gostn but still no answer for the version

**Comment by richard67** [comment]
Exactly this behaviour was what I've meant.

**Comment by gostn** [comment]
64 bit PHP8

**Comment by ghost** [comment]
> ok @gostn but still no answer for the version

as long as i´m called a troll and no apologize for that …

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30921">issues.joomla.org/tracker/joomla-cms/30921</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
