### PR TITLE
[4.0] Update comment

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Updates the comment after changes in code.

### Testing Instructions

Code review. Notice there is no `switch` statement below.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d3436180cf6021b1a4771c0da4c8f88590ed10b9<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31019">issues.joomla.org/tracker/joomla-cms/31019</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d3436180cf6021b1a4771c0da4c8f88590ed10b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31019">issues.joomla.org/tracker/joomla-cms/31019</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31019">issues.joomla.org/tracker/joomla-cms/31019</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
