### PR TITLE
Converting TRUE and FALSE to 1 and 0 when editing Purity III template. Fix #7834

### LINKED ISSUE #7834: Not editing Purity III template using PostgreSQL. Wrong type in "a.published IN (true)"
Trying to edit a Purity III template I get an error:

error-1-duplicar-template

Trying the SQL in ```psql``` I see:
diagnostico-error-1-duplicar-template

The type of the field ```published``` of the table ```dyv_menu``` is ```smallint``` that cannot be compared with ```true``` in PostgreSQL.

I see two possible solutions:
1. Altering the table to change the type of ```published``` to become ```boolean```
2. Changing the query to be something like ```a.published <> 0```

¿Which one is better?

### PR DESCRIPTION
**Pull request by vtamara**

### CODE REVIEW

**Comment by vtamara** [comment]
The bug that this path fixes, and some thoughts about the solution are described at https://github.com/joomla/joomla-cms/issues/7834 

I will summurize here anyway.   Using the latest version of Joomla, on a PostgreSQL database and trying to edit a template you will obtain the error shown below:

error-1-duplicar-template

**Comment by Bakual** [comment]
I haven't tested on PostgreSQL, but on MySQL it obviously works fine.
Inspecting `$published` while opening a template style also shows me that it is empty. Thus the code in question isn't fired at all.
Looking at your screenshot, it looks like you are using at least some 3rd party plugins or even a template with a framework. Which makes me believe the issue is caused from there.
That `$published` variable should contain an array of integers with the values of the states to be filtered. Passing `true` or `false` would be wrong values.

If you want to sanitise it, you may instead use `$published = JArrayHelper::toInteger($published)` which will cast the values to integer and remove any non-integer values. Making the code much easier to read.

**Comment by alikon** [comment]
without this pr on postgresql no problem on edit and save a "core template" without 3dp
so unable to reproduce

**Comment by Bakual** [comment]
@vtamara Can you provide details with which template you had this issue? Or what the exact steps are to reproduce the issue?

**Comment by vtamara** [comment]
I'm using T3 Framework with template Purity III --that announce to work on PostgreSQL

**Comment by vtamara** [comment]
Using $published = JArrayHelper::toInteger($published)  instead of the filter I proposed gives the following error:

jarrayhelper_tointeger

**Comment by Bakual** [comment]
Ah, that may be because you end up with all invalid entries in the array and thus implode on an empty array.

We could add a check to see if the array contains anything after it's passed through the JArrayhelper. But honestly I think it's a bug in the T3 framework which should be fixed by them, they seem to pass "true" instead of "1".
We can (and should) sanitise the input on our part, but fixing the issue is their job.

**Comment by vtamara** [comment]
Thank you. Confirmed it is a T3 issue I'm proposing solution there and closing here. 

https://github.com/t3framework/t3/pull/423

**Pull request closed without merging**
