### PR TITLE
[protostar] Clearfix after component

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #13387

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 42283e4dea9e3d6060c214c861e732e2c2e6a8fe

#### Breadcrumbs-Module with PR:
bildschirmfoto 2017-10-03 um 17 56 16
#### Breadcrumbs-Module without PR:
bildschirmfoto 2017-10-03 um 17 56 28

Thanks @brianteeman 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18210">issues.joomla.org/tracker/joomla-cms/18210</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 42283e4dea9e3d6060c214c861e732e2c2e6a8fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18210">issues.joomla.org/tracker/joomla-cms/18210</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
