### PR TITLE
[5.1] WebAssetManager: reset sorting state when new item enabled or disabled

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

WebAsset ignoring newly added assets (without dependencies) after https://github.com/joomla/joomla-cms/pull/42661
This PR is fixing it.

### Testing Instructions
Apply patch, visit home page, and check for Schema.org markup in source code.

### Actual result BEFORE applying this Pull Request
None (except BreadcrumbList)

### Expected result AFTER applying this Pull Request
It is there

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by crommie** [comment]
Without patch: only breadcrumb stuff
With patch: all schema.org

(Debug switched off)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42880">issues.joomla.org/tracker/joomla-cms/42880</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 3f09ba15fb0246e4304a0713694f74410414826a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42880">issues.joomla.org/tracker/joomla-cms/42880</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 3f09ba15fb0246e4304a0713694f74410414826a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42880">issues.joomla.org/tracker/joomla-cms/42880</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42880">issues.joomla.org/tracker/joomla-cms/42880</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and and for the speedy testers @crommie @Hackwar ❤️

**Pull request merged**
