### PR TITLE
[4.3] typo com_users.ini

### PR DESCRIPTION
**Pull request by brianteeman**
removes the typo "to to" ==> "to"

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 322e3040472cb4f16604ffcd142aee6626bbdf2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40716">issues.joomla.org/tracker/joomla-cms/40716</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 322e3040472cb4f16604ffcd142aee6626bbdf2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40716">issues.joomla.org/tracker/joomla-cms/40716</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40716">issues.joomla.org/tracker/joomla-cms/40716</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brain @brianteeman !

**Pull request merged**
