### PR TITLE
Implement the global text filter settings to the Tiny MCE editor

### PR DESCRIPTION
**Pull request by chmst**
#### Summary of Changes

At the moment, the filter settings for HTML tags and attributes in the Tiny MCE are completly independent from the Joomla! settings (=> Global Configuration). So it's possible, that elements are allowed in the Tiny MCE but are forbidden in the Joomla! filter or vice versa. 
With this patch it's possible to ignore the Tiny MCE settings and use the Joomla! settings to have the exact same filter rules and no variance. Special advantage: with this new function it's possible to define the rules for each user group! 
#### Testing Instructions
1. You need at least one user who is not super user
2. In global configuration define textfilter for the usergroup the user belongs to, as for example set White list and allow the tag iframe and the attribute background.
3. Login as this user and write a new article which contains an iframe. Save the article and the iframe disappears if it is denied in TinyMCE.
4. Apply the patch
5. In the TinyMCE Plugin set the new Param "use Joomla textfilters" to on.
6. Login again as the user and write a new article containig an iframe and a style baykground
7. For this user, iframe and background will remain
8. Now play around and test some combinations, allowing and denying different tags or attributes to different user groups

### CODE REVIEW

**Comment by roland-d** [comment]
@chmst Please alpha-order the language strings.

**Comment by chmst** [comment]
@roland-d done

**Comment by zero-24** [comment]
hmm maybe I'm worng but i'm unable to add a `script` tag bevor and after the patch.

I'm super user without any filter resctrictions.

I did try to insert this piece of code via the "html code / source code" field from the tinyMCE:

```html
<div>foo</div>
<script>
document.write('<div>Print this after the script tag</div>');
</script>
<div>bar</div>
```

And after i'd want to save it the script tag was removed.

But this happen before and after the patch.

The iframe thing is working perfect in frontend and backend looks good to me :+1:

**Comment by chmst** [comment]
Thank you, you are right. The tiny has it's own whitelist. I take this whitelist now additional to the text-filter. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9993">issues.joomla.org/joomla-cms/9993</a>.</sub>

**Comment by wojsmol** [comment]
@chmst Please see https://github.com/chmst/joomla-cms/pull/3

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on b3f83ea819cb67b7168b6e4d072a2f5079bff979<br /><br />Works now. Thanks @chmst I can't wait that 3.6 with this feature is be released very usefull.

@brianteeman are you ok with the language strings?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9993">issues.joomla.org/joomla-cms/9993</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on b3f83ea819cb67b7168b6e4d072a2f5079bff979<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9993">issues.joomla.org/joomla-cms/9993</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman the last commit was just a one line cs change: https://github.com/joomla/joomla-cms/pull/9993/commits/8f44c4b08e89e58e07add52430b25fa8328d12ed can we RTC than here based on the tests by @bembelimen and me? Thanks @chmst !

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9993">issues.joomla.org/joomla-cms/9993</a>.</sub>

**Comment by rdeutz** [comment]
@chmst cloud you please check the merge conflicts, thanks

**Pull request merged**
