### PR TITLE
[4.0][CS] Remove tabs/blank line

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove tabs/blank line

### Testing Instructions
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 80190431653cc48eac4fc007b884e79114182383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21346">issues.joomla.org/tracker/joomla-cms/21346</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 80190431653cc48eac4fc007b884e79114182383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21346">issues.joomla.org/tracker/joomla-cms/21346</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
