### PR TITLE
[4] Correct docblock in stubGenerator

### PR DESCRIPTION
**Pull request by PhilETaylor**
replacement for https://github.com/joomla/joomla-cms/pull/33155

Code review.

### CODE REVIEW

**Comment by richard67** [comment]
Would a `@return  void` in addition make sense? Or would that be wrong?

**Comment by PhilETaylor** [comment]
I wrote this up and deleted it before I submitted... chose not to include the commentary - If you or anyone else can prove that this method actually ever returns anything, then we can documentation for that return, but https://3v4l.org/gPnHd leads me to believe that nothing is ever "returned".

**Comment by richard67** [comment]
> I wrote this up and deleted it before I submitted... chose not to include the commentary - If you or anyone else can prove that this method actually ever returns anything, then we can documentation for that return, but https://3v4l.org/gPnHd leads me to believe that nothing is ever "returned".

You are right, it never will return anything.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 94b39ddadf17ac93525669fcb468317f2dd5e906<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33184">issues.joomla.org/tracker/joomla-cms/33184</a>.</sub>

**Pull request merged**
