### PR TITLE
[4.0] Change Status dropdown consistency

### PR DESCRIPTION
**Pull request by brianteeman**
Having a consistent UI is essential. All off the new change status dropdown items are ordered Published->Unpublished->Archive->Checkin->Trashed except for com_content where Archive and Checkin are reversed.

This PR changes the order of the articles change status dropdown items to be consistent with all the others

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5170932a99519c13547d7d983c483e8295f01b76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24078">issues.joomla.org/tracker/joomla-cms/24078</a>.</sub>

**Comment by Quy** [comment]
Please do the same with `Featured Articles`.

**Comment by brianteeman** [comment]
Updated for featured aarticles

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
