### PR TITLE
[com_associations]  - sort order fix

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #14572

### Summary of Changes
rationalize Multilingual Associations Sort order 

### Testing Instructions
check sort order works as expected on different  item type

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
No Associtation Ascending or Descending are shown in `Sort Table by:`
bildschirmfoto 2017-03-20 um 19 47 56

**Comment by alikon** [comment]
i think is meaningfull to sort on associated not associated

**Comment by franz-wohlkoenig** [comment]
@alikon i understand #14572 as wish to get "Associtation Ascending" or "Associtation Descending" in Sort-Drpdown.

**Comment by brianteeman** [comment]
The issue i raised was that the association sort was another in the correct place

From what i can see @alikon has concluded that it makes no sense to have a sort by association so he has removed that?

**Comment by alikon** [comment]
yes,
even if i can be wrong

**Comment by brianteeman** [comment]
Makes sense to me - thanks, will test later

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1747e9c6ed52023aacd3ddeb657c43998f1690dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14814">issues.joomla.org/tracker/joomla-cms/14814</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1747e9c6ed52023aacd3ddeb657c43998f1690dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14814">issues.joomla.org/tracker/joomla-cms/14814</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14814">issues.joomla.org/tracker/joomla-cms/14814</a>.</sub>

**Pull request merged**
