### PR TITLE
[4.0] Fix sticky toolbar

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #34793. Revert #34426.

### Summary of Changes
Fix toolbar scrolls out of view.

### Testing Instructions
Download/install the prebuilt package.
or
Apply PR.
Run `npm run build:css`

Go to Global Configuration.
Scroll down.

### Actual result BEFORE applying this Pull Request
Toolbar scrolls out of view.

### Expected result AFTER applying this Pull Request
Toolbar sticks at the top.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2d4679a6891fbe31ac5fa32a69922b45adae7f80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34805">issues.joomla.org/tracker/joomla-cms/34805</a>.</sub>

**Comment by brianteeman** [comment]
I'm assuming that while this fixes the sticky it reintroduces the overflow issue?

**Comment by Quy** [comment]
This restores the functionality that #34426 inadvertently broke to fix #32820.

**Comment by richard67** [comment]
Issue #32820 is still open so nothing got lost.

**Comment by brianteeman** [comment]
Thanks for answering the question @richard67

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2d4679a6891fbe31ac5fa32a69922b45adae7f80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34805">issues.joomla.org/tracker/joomla-cms/34805</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34805">issues.joomla.org/tracker/joomla-cms/34805</a>.</sub>

**Comment by Quy** [comment]
Also fixed #34842.

**Pull request merged**
