### PR TITLE
Content filter order

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Changed the order of the filters for articles and featured articles to match the order of the columns below to be consistent with all other filters

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8195a8783fb0b2ebef90f575df5815d2332c70ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9863">issues.joomla.org/joomla-cms/9863</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 8195a8783fb0b2ebef90f575df5815d2332c70ff<br /><br />what to say?
Thanks?
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9863">issues.joomla.org/joomla-cms/9863</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9863">issues.joomla.org/joomla-cms/9863</a>.</sub>

**Comment by brianteeman** [comment]
free beer?

On 12 April 2016 at 00:39, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> I have tested this item [image: :white_check_mark:] successfully on
> 8195a87
> <https://github.com/joomla/joomla-cms/commit/8195a8783fb0b2ebef90f575df5815d2332c70ff>
>
> what to say?
> Thanks?
> Thanks!
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9863
> <https://issues.joomla.org/tracker/joomla-cms/9863>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9863#issuecomment-208619849>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request merged**
