### PR TITLE
[New Calendar] Replacing "Time" by the clock icon

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/14422#issuecomment-285618117

In some languages, the word "Time" is too long to fit
### Summary of Changes
Changing the "Time" string to the clock icon

### Testing Instructions
Patch, make sure to clear cache, display the Calendar.

You should get
screen shot 2017-03-11 at 09 57 06

@dgt41 
@coolcat-creations 
@chmst

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 97b5e715bcbaa64f4d5d5eec12012fa58fb4176e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by chmst** [comment]
I've tested this item successfully for the icon-clock.

What do you think about setting the btn-group centered? Or should this be another issue?

**Comment by franz-wohlkoenig** [comment]
@chmst can you please mark your test at [Issue-Tracker](https://issues.joomla.org/tracker/joomla-cms) as successfully?

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 97b5e715bcbaa64f4d5d5eec12012fa58fb4176e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by chmst** [comment]
done ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by infograf768** [comment]
> What do you think about setting the btn-group centered? Or should this be another issue?

No idea what you mean.

**Comment by infograf768** [comment]
3 good tests.

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
thanks @chmst 
@infograf768 i think @chmst means to center the group (clock+Hour+Minute)

**Comment by infograf768** [comment]
It is not a btn-group and one should not forget we also mau have am-pm

**Comment by dgt41** [comment]
> What do you think about setting the btn-group centered

Do we have a centered class in bs2?

**Comment by brianteeman** [comment]
Doesnt this code require you to be loading icomoon?

While that is almost certainly true for the admin as both core templates use it is not the same for the front end where this will also be displayed

**Comment by brianteeman** [comment]
Also for accessibility purposes when using icons in this way you should be using aria-hidden="true" to hide the icon as it is used purely for decoration.

**Comment by infograf768** [comment]
Indeed, we do have an issue in Beez, and not only for the clock (See buttons at bottom:

screen shot 2017-03-11 at 11 00 59

Taking off RTC.

**Comment by infograf768** [comment]
back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by brianteeman** [comment]
As my comment has highlighted a bigger issue with none protostar templates and the entire calendar field this should probably get a release blocker status

**Comment by dgt41** [comment]
Can be fixed in the calendar.css, copy paste the basic btn class from BS, and for icon-time class have an inline base64 image

**Comment by brianteeman** [comment]
That would work and would be template independent

**Comment by infograf768** [comment]
Will update here to get an inline base64 image.
As for the BS btn-goup, I would not know which ones to pick.

**Comment by infograf768** [comment]
Modified PR to use base64 image.
We should now get:

screen shot 2017-03-11 at 12 03 50

Please test that one.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1b171099017a46d1a114fd3bfb5e5b2ccbe697a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 1b171099017a46d1a114fd3bfb5e5b2ccbe697a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Comment by dgt41** [comment]
RTC
Thanks @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14484">issues.joomla.org/tracker/joomla-cms/14484</a>.</sub>

**Pull request merged**
