### PR TITLE
[4.0] fix merge error in #18839

### PR DESCRIPTION
**Pull request by brianteeman**
As per the title these two css files should not have been merged

### CODE REVIEW

**Comment by infograf768** [comment]
Restarted Travis.

**Comment by infograf768** [comment]
Setting to RTC directly as it is obvious.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18632">issues.joomla.org/tracker/joomla-cms/18632</a>.</sub>

**Comment by infograf768** [comment]
WEll, let's give up with Travis. ;)

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
