### PR TITLE
fix undefined error

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #17041 .

### Summary of Changes
Change the variable `setCustomDir` to the correct `tinyMCE.activeEditor.settings.setCustomDir`

### Testing Instructions

Create a new article
Upload and upload a picture (Note: dragdrop upload)
Drag and drop again to upload the same picture (same file name)

### Expected result

alert with a message that file exists

### Actual result
Javascript,: Error:Uncaught, ReferenceError:, setCustomDir, is, not, defined

### Documentation Changes Required
None

### CODE REVIEW

**Review by C-Lodder — APPROVED** [review]

**Comment by AlexRed** [comment]
Ok, no more Javascript Error, but in the message window there is an "undefined" folder name:
File already exists.: undefined/images/imagename.png

undefined

**Comment by dgrammatiko** [comment]
@AlexRed thanks, there was a copy paste mistake there, it should be ok now.

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on ba91b1fbef16302c5beb2e05284bd646e13c10fe<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17063">issues.joomla.org/tracker/joomla-cms/17063</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba91b1fbef16302c5beb2e05284bd646e13c10fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17063">issues.joomla.org/tracker/joomla-cms/17063</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
