### PR TITLE
Highlight behavior hardening

### PR DESCRIPTION
**Pull request by jeffchannell**
Pull Request for JSST report sent 5 Feb 2016.
#### Summary of Changes
- Added `JFilterOutput::stringJSSafe`
- Modified `JHtmlBehavior::highlighter` to use `JFilterOutput::stringJSSafe`
#### Testing Instructions

Test URL: `index.php?option=com_finder&highlight=WyJcXCIsIl0pO2FsZXJ0KDEpO1wvXC9cXCJd`

### CODE REVIEW

**Comment by jeffchannell** [comment]
@mbabker ...

**Comment by mbabker** [comment]
Fixes the issue in the report.  Just need to deal with the PHPCS issues when merging.

@joomla/security please review.

**Comment by jeffchannell** [comment]
@mbabker checks all passed

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 90cabc14fe37d428d9f353ffd44b08a74e11d052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9524">issues.joomla.org/joomla-cms/9524</a>.</sub>

**Comment by beat** [comment]
Good improvement, but a question about performance and output size: Do we need to hex-escape every character one by one, including all alphanumericals ? Can't we use a php function that js-escapes the whole string at once instead of handling it character by character ?

Possible functions for strings would include json_encode() and removing the first and last character with a substr() around it ?

**Comment by beat** [comment]
@wilsonge @mbabker  Please check my feedback that I was writing while you were already merging

**Pull request merged**
