### PR TITLE
Wrong message after publishing nested sub-items

### PR DESCRIPTION
**Pull request by infograf768**
This PR to replace https://github.com/joomla/joomla-cms/pull/8038 where nested is not taken into account.
How to test:

```
Navigate to Category Manager
Create a main category
Create a sub-category that is related to the new main category
Unpublish the main category
Both main & sub-category will get unpublished
Click on the sub-category and try to publish and check the message
```

Do the same for sub_menus and sub_tags

### CODE REVIEW

**Comment by infograf768** [comment]
Result would be of the type:
screen shot 2015-10-11 at 19 28 56

**Comment by wilsonge** [comment]
We should use an error message type when it's not successful. Nice spot tho JM :)

General question. Should we queue the actual error messages? So the user actually understands why things have failed. For example if they haven't touched the parent category for a while they might be confused that they can't publish the child cateogry

Obviously though this is a needed bug fix!

**Comment by infograf768** [comment]
As we check that the reason for failing is clear, I am changing the string values.
Example:
```
COM_TAGS_N_ITEMS_FAILED_PUBLISHING="Failed publishing %d tag as at least one of their parents is unpublished."
COM_TAGS_N_ITEMS_FAILED_PUBLISHING_1="Failed publishing %d tags as at least one of its parents is unpublished."
```

**Comment by infograf768** [comment]
@wilsonge 
Changed the normal message to Error.
We would now get for example:
screen shot 2015-10-12 at 09 12 22

**Comment by YouriiM26** [comment]
I have tested this item :white_check_mark: successfully on 96595deca442413e5c6550094d741db005c62bca<br /><br />Works perfect for me. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8065">issues.joomla.org/joomla-cms/8065</a>.</sub>

**Comment by Hils** [comment]
I haven't got the complete context in front of me just now but 'failed to publish...' is better en-GB than 'failed publishing...'.

**Comment by infograf768** [comment]
Folks, let's wait for that one. I found a problem in nested.php which may have to be solved first.
See https://github.com/joomla/joomla-cms/issues/8082

If it can't be solved, we may have to add a new condition in this PR with new language strings, or simplify with no condition by not explaining in the string the reason of the failure.

**Comment by infograf768** [comment]
Changed PR as it is unlikely that https://github.com/joomla/joomla-cms/issues/8082 would be changed.
The new string is now of the type:
```
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING="Failed publishing %d categories as at least one of their parents is unpublished or one of their children is checked out."
COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING_1="Failed publishing %d category as at least one of its parents is unpublished or one of its children is checked out."
```
Thank you for testing again.

**Comment by fontanil** [comment]
@test:
Patch works here. Thanks

**Comment by YouriiM26** [comment]
I have tested this item :white_check_mark: successfully on 93157fa9c1c03638df5ef1df0321f425effe5008<br /><br />Patch works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8065">issues.joomla.org/joomla-cms/8065</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8065">issues.joomla.org/joomla-cms/8065</a>.</sub>

**Pull request merged**
