### PR TITLE
Change vote plugin to disabled

### PR DESCRIPTION
**Pull request by brianteeman**
On new installs this changes the vote plugin to be disabled by default. It is not used that often and by disabling it we also benefit from a simpler article list view in the admin

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 76e4bcd0ffbea562943bc4dbaf4d1ca376e29d2d<br /><br />Tested on MySQL and code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17106">issues.joomla.org/tracker/joomla-cms/17106</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 76e4bcd0ffbea562943bc4dbaf4d1ca376e29d2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17106">issues.joomla.org/tracker/joomla-cms/17106</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks for merging

**Pull request merged**
