### PR TITLE
[4.0] Check if file exists before trying to copy

### PR DESCRIPTION
**Pull request by Bakual**
Follow up on https://github.com/joomla/joomla-cms/pull/28813

### Summary of Changes
Just adding a check if the file exists before trying to copy it.

### Testing Instructions
Copy a template

### Expected result
works

### Actual result
works

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 80450cb8bef856d281ad462d08f2d1ec219c3c1f<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28823">issues.joomla.org/tracker/joomla-cms/28823</a>.</sub>

**Comment by richard67** [comment]
You could move the `$dst = Path::clean($toPath . '/' . $folder . '/' . $languageFile);` inside the `if (File::exists($src))` ;-)

**Comment by Bakual** [comment]
I could, but I prefer it to have like it is so src and dst are right after eachother. Imho it's easier to see what happens.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 80450cb8bef856d281ad462d08f2d1ec219c3c1f<br /><br />On review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28823">issues.joomla.org/tracker/joomla-cms/28823</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28823">issues.joomla.org/tracker/joomla-cms/28823</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
