### PR TITLE
[5.0] [new feature] TinyMce sample image plugin

### PR DESCRIPTION
**Pull request by brianteeman**
This is a toolbar icon for the tinymce editor that will let you quickly generate a placeholder image in your content.

## To test
1. Apply pr
2. rebuild the js with `npm run build:js`
3. Go to the tinymce plugin and drag the new icon to your toolbar
4. Go to any article and try it you

## Plugin
tiny

## Demo
tiny2

### CODE REVIEW

**Comment by laoneo** [comment]
Why do you need that? I don't think this needs to come in core. Write a plugin and load it through the plugin feature if you need it.

**Comment by brianteeman** [comment]
It speeds up development and makes life easier to build a site. Feedback was very positive when I showed the concept on FB. We have to start treating tinymce as a first class citizen. Instead we push people to use an editor that is old and outdate but has the extras people need.

**Comment by laoneo** [comment]
Don't agree here. The core should act as an example and doesn't need to compete out 3rd party extensions. Bloating the core with such useless features which will not bring any benefit to the users is a wrong direction. Instead of, you should tell the users how extensible the core editor is and make an example of this use case either in the official docs or in a magazine post.

**Comment by brianteeman** [comment]
I couldnt disagree more

**Comment by Fedik** [comment]
I think the idea is good, can be useful for authors, it allow to format the article and replace images to final ones later.

**Comment by HLeithner** [comment]
I don't think it should be in core if it's possible to do it with a Plugin. A 3rd Party Plugin could also use 3rd Party image services.

**Comment by Fedik** [comment]
I know, but that something that Writers would like to see in core.

**Comment by brianteeman** [comment]
@HLeithner you are missing the point. Core must be usable and useful. It doesnt matter how fast the code is or how modern the code is. What matters is that users can use it. Why should they have to install a plugin for something that is 40 lines of code. You can make the argument about making it a 3rd party extension with every new feature added to core in J4. Workflows -> almost unusable in its current form without extra code. Schedule -> completely unusable without extra code. Media Manager - the least said abut the better.
PS it is not possible to do this with an installable plugin that is fully integrated into the editor

**Comment by brianteeman** [comment]
Forgot to add. I actually did some (rudimentary) user research before even starting this. When was the last time anyone did that

**Comment by laoneo** [comment]
TinyMCE has a feature where you can load TinyMCE plugins by adding it to the options. We do not talk here about a Joomla plugin.

**Comment by brianteeman** [comment]
You can make this argument about everything. Its a stupid argument. We must make joomla usable.

**Comment by brianteeman** [comment]
> TinyMCE has a feature where you can load TinyMCE plugins by adding it to the options. We do not talk here about a Joomla plugin.

Show me how a joomla user can install that plugin. There is no functionality for that.

**Comment by laoneo** [comment]
The part on the bottom:

image

I'm using it on my production sites with the autolink plugin.

**Comment by Fedik** [comment]
@laoneo please do not forget that Joe Average does not have a skills to code it (and this plugin exists nowhere) :wink: 
He want to write a text.

**Comment by brianteeman** [comment]
@laoneo  I am well aware of that option. Still doesn't answer the fact that there is no way on joomla to install that plugin.

There has been more lines of comment than there has been code

**Comment by laoneo** [comment]
> Instead of, you should tell the users how extensible the core editor is and make an example of this use case either in the official docs or in a magazine post.

Again, publish your sample lines and tell the world how extensible it is.


> @laoneo I am well aware of that option. Still doesn't answer the fact that there is no way on joomla to install that plugin.

Uploading it via FTP or the template editor is enough. There is really nothing to install here. Again, this is a great showcase how to use the plugin feature of TinyMCE.

**Comment by laoneo** [comment]
> @laoneo please do not forget that Joe Average does not have a skills to code it (and this plugin exists nowhere) wink He want to write a text.

Copy paste is enough for the few people who are using it.

**Comment by brianteeman** [comment]
I wonder how you would have reacted if I had told you to just write a blog post about custom fields. No need for that to be in the core. Just copy paste code, use ftp etc.

**Comment by laoneo** [comment]
> I wonder how you would have reacted if I had told you to just write a blog post about custom fields. No need for that to be in the core. Just copy paste code, use ftp etc.

It's ok, no need to shift away. I shared my opinion. Do whatever you guys want. It really doesn't matter if this feature is in or not at the end of the day.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on fa0844737788e3f05402fc120c65b8a0b6f58d10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36968">issues.joomla.org/tracker/joomla-cms/36968</a>.</sub>

**Comment by brianteeman** [comment]
closed due to lack of interest from release lead

**Comment by brianteeman** [comment]
re-opening. this is far more useful to users than other features being added to 4.2 and does not already have an extension offering this on the jed

**Comment by jwaisner** [comment]
Clearing test as this PR will need 2 test again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36968">issues.joomla.org/tracker/joomla-cms/36968</a>.</sub>

**Comment by brianteeman** [comment]
> Why do you need that? I don't think this needs to come in core. Write a plugin and load it through the plugin feature if you need it.

It is completely impossible to do that. The plugin feature does not allow you to add an icon to the toolbar or to add a link to the menu which means that even though the plugin is running it can not be used.

I have spent the day checking into this. The person who wrote the pr for that feature did it as a result of some tutorials they wrote for the tinymce web site. I have checked those plugins (fixed one along the way) and can confirm that the only tinymce plugin that is usable when added in this way is when it is triggered by a hotkey or autocomplete.

@obuisard this and the associated two other plugins for tinymce would be great additions for 4.3. They got universal positive feedback when showcased on the facebook group. see also #36975 and #36962

**Comment by brianteeman** [comment]
> > Instead of, you should tell the users how extensible the core editor is and make an example of this use case either in the official docs or in a magazine post.
> 
> Again, publish your sample lines and tell the world how extensible it is.
> 
> > @laoneo I am well aware of that option. Still doesn't answer the fact that there is no way on joomla to install that plugin.
> 
> Uploading it via FTP or the template editor is enough. There is really nothing to install here. Again, this is a great showcase how to use the plugin feature of TinyMCE.

except it doesnt actually work

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev.

**Comment by fancyFranci** [comment]
I have tested this item :red_circle: unsuccessfully on fa0844737788e3f05402fc120c65b8a0b6f58d10<br /><br />First the icon did not load in the Tinymce plugin view, just the placeholder text. After reloading the page the icon appeared as expected. I can drag it to my toolbar and save it. But then I can not open the article any more. A soon as I revert the patch its working again. I think placeholder images are really useful, would be great if you can fix that.

"An error has occurred.
    0 Call to a member function getIdentity() on null "<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36968">issues.joomla.org/tracker/joomla-cms/36968</a>.</sub>

**Comment by brianteeman** [comment]
I can't replicate your issue

**Comment by HLeithner** [comment]
> I have tested this item 🔴 unsuccessfully on [fa08447](https://github.com/joomla/joomla-cms/commit/fa0844737788e3f05402fc120c65b8a0b6f58d10)First the icon did not load in the Tinymce plugin view, just the placeholder text. After reloading the page the icon appeared as expected. I can drag it to my toolbar and save it. But then I can not open the article any more. A soon as I revert the patch its working again. I think placeholder images are really useful, would be great if you can fix that.
> 
> "An error has occurred. 0 Call to a member function getIdentity() on null "
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36968](https://issues.joomla.org/tracker/joomla-cms/36968).

a trace log would be helpful

**Comment by fancyFranci** [comment]
> a trace log would be helpful

You're right.
 
grafik

**Comment by HLeithner** [comment]
@Fedik could this be of the change from pseudo event buttons to real events?
@laoneo or did you missed something for identity here?

**Comment by fancyFranci** [comment]
@HLeithner I really dont know why, but after I tested https://github.com/joomla/joomla-cms/pull/36975 with the same result, I went back to here, installed again and the error is gone now... Inserting sample images works as expected.

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on e2ada52503b27eb8c6b7722d5f79348960ef07ad<br /><br />I was able to add sample images into my article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36968">issues.joomla.org/tracker/joomla-cms/36968</a>.</sub>

**Comment by fancyFranci** [comment]
The error comes back when I remove the other new plugin (sample text) from the tinymce toolbar. After I tested it and left it there, the sample image worked.

**Comment by Fedik** [comment]
> could this be of the change from pseudo event buttons to real events?

Nope, this can happen when $application not injected in to plugin while bootPlugin, https://github.com/joomla/joomla-cms/blob/6ba6cbd2e8b8aba5079da07b17454abe1df11745/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php#L70

It nothing with events

**Comment by Fedik** [comment]
@fancyFranci did you tested iit for joomla 5 or 4? because title say 4,but the target is 5 :)

**Comment by N6REJ** [comment]
I have tested this item :red_circle: unsuccessfully on e2ada52503b27eb8c6b7722d5f79348960ef07ad<br /><br />applying the patch causes tinymce to no longer appear<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36968">issues.joomla.org/tracker/joomla-cms/36968</a>.</sub>

**Comment by brianteeman** [comment]
a trace log would be helpful

**Comment by brianteeman** [comment]
The PR was created for Joomla 4.2 using tinymce 5. @HLeithner changed this to be for 5.0 but as that uses tinymce 6 and a reworked plugin tbh I wouldnt expect this to work at all.

**Comment by N6REJ** [comment]
> The PR was created for Joomla 4.2 using tinymce 5. @HLeithner changed this to be for 5.0 but as that uses tinymce 6 and a reworked plugin tbh I wouldnt expect this to work at all.

ok, so this fails j5.

**Comment by HLeithner** [comment]
same as the other pr, why not using the template system for this?

**Comment by brianteeman** [comment]
> why not using the template system for this?

because the template system is not easily portable and is template dependent

**Comment by HLeithner** [comment]
didn't we had a standard set/location in joomla too? or was this located only in Cassiopiea? Anyway tinymce deprecated the "simple" template system for there paid advanced template system. So we forked it and maybe @Fedik or @dgrammatiko or @laoneo has a nice idea for a better template system for such cases.

**Comment by Fedik** [comment]
Following code is looking for templates https://github.com/joomla/joomla-cms/blob/ad7796a7fdea3939d27e50b7a5b0d85326e1491a/plugins/editors/tinymce/src/Extension/TinyMCE.php#L65-L67

Not sure what exactly, I think @dgrammatiko know better.
It is part of #40626

**Comment by Fedik** [comment]
it maybe a good idea to have some default templates under `/media/plg_editors_tinymce/templates/`

**Comment by dgrammatiko** [comment]
> Not sure what exactly, I think @dgrammatiko know better.

That ajax fn just replaced the code that resolved the templates on startup (now it's per use case)

> it maybe a good idea to have some default templates under /media/plg_editors_tinymce/templates/

It's very easy to add one more lookup path in the code you linked above https://github.com/joomla/joomla-cms/pull/36968#issuecomment-1704066203

**Comment by brianteeman** [comment]
do it without me. wasted enough time on making a good editor for joomla already without an 18 month delay to everything

**Pull request closed without merging**
