### PR TITLE
solves #10293

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/10293.
#### Summary of Changes

Solves https://github.com/joomla/joomla-cms/issues/10293
#### Testing Instructions

Code review, or:
1. Logout
2. Login and go to Menus -> Manage
3. Now click in the sidebar "Menu items"
4. No 403 now.

### CODE REVIEW

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on f7429ad1f1678babc4cf8717818990e5cd264ea2<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10314">issues.joomla.org/joomla-cms/10314</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on f7429ad1f1678babc4cf8717818990e5cd264ea2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10314">issues.joomla.org/joomla-cms/10314</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@pe7er @grhcj thanks for testing!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10314">issues.joomla.org/joomla-cms/10314</a>.</sub>

**Comment by bembelimen** [comment]
Wouldn't it be better to get the first valid menu instead of all menu items?

**Comment by andrepereiradasilva** [comment]
well i don't know which is better, ask @infograf768 

i just solved made this PR to solve the 403 error.

**Pull request merged**
