### PR TITLE
Link to a field outside of any group (showon)

### PR DESCRIPTION
**Pull request by saharin88**
Exemple xml for testing
```
    <field
            name="field1"
            type="list"
    >
        <option value="1">val 1</option>
        <option value="2">val 2</option>
    </field>
    <fields name="groupname">
        <field
                name="field2"
                type="text"
                showon=".field1:1"
        />
    </fields>
```

### CODE REVIEW

**Comment by Quy** [comment]
Please fix phpcs: https://ci.joomla.org/joomla/joomla-cms/36019/1/2

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on bae95b1b69cbcb8dd562512d06ad7f2244b0f0c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30850">issues.joomla.org/tracker/joomla-cms/30850</a>.</sub>

**Comment by Fedik** [comment]
for testing, add this XML to Custom HTML module (somewhere inside `<fieldset name="options">`):
```
<fields name="groupname">
	<field name="field2" type="text" label="Field 2" showon=".published:1" />
</fields>
```

Then try change module "Status":
When module is published then the custom field should be visible and vice versa.

**Before path**: it not work
**After**: should work

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bae95b1b69cbcb8dd562512d06ad7f2244b0f0c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30850">issues.joomla.org/tracker/joomla-cms/30850</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30850">issues.joomla.org/tracker/joomla-cms/30850</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
Sorry merged this at the wrong time, can you rewrite a PR please then I can merge it next week.

**Comment by richard67** [comment]
@saharin88 Could you make this pull request again? It was merged but then had to be reverted because 3.22 was already in release candidate phase. Sorry for the inconvenience, and thanks in advance.

@HLeithner Could you put this on your to do list to initiate a new PR in case if @saharin88 is not available?

**Comment by stell** [comment]
Could there be another PR for this. Would be too bad if its missing in the next Update too.

**Comment by richard67** [comment]
@HLeithner Anything new with redoing this merged and later due to RC status reverted PR? OR has this already been done?

**Comment by richard67** [comment]
@HLeithner New PR is #32646 .

**Pull request merged**
