### PR TITLE
use the index for session table

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue  #22632 .

### Summary of Changes
just completing the work made in #22668 for supported db's

### Testing Instructions

see #22668

### Expected result

screenshot from 2019-01-23 19-05-49

### Actual result
screenshot from 2019-01-23 19-06-26

### CODE REVIEW

**Comment by lucasacchiricciardi** [comment]
I have tested this item :white_check_mark: successfully on cd9752fcfbb145e6bacaf3b49ccf2565bbaa44a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23650">issues.joomla.org/tracker/joomla-cms/23650</a>.</sub>

**Comment by davidemessia** [comment]
I have tested this item :white_check_mark: successfully on cd9752fcfbb145e6bacaf3b49ccf2565bbaa44a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23650">issues.joomla.org/tracker/joomla-cms/23650</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on cd9752fcfbb145e6bacaf3b49ccf2565bbaa44a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23650">issues.joomla.org/tracker/joomla-cms/23650</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23650">issues.joomla.org/tracker/joomla-cms/23650</a>.</sub>

**Comment by HLeithner** [comment]
@alikon could you rebase this for 3.9.7 please

**Comment by alikon** [comment]
@HLeithner done ;)

**Comment by richard67** [comment]
@HLeithner This PR had 2 good tests and then was set to RTC. Since this time, only rebase has happened, no further changes. So I think the good tests and RTC status is still valid, it does not need to be re-tested. In addition, I've checked by code review that the database changes are right and consistent, and that the schema update scripts have the right file name for 3.9.7. => Please set RTC again.

**Review by richard67 — APPROVED** [review]

**Comment by ghost** [comment]
@richard67 set back on pending and RTC again.

**Comment by richard67** [comment]
@franz-wohlkoenig Issue tracker shows failure status for some reason.

Update: Seems to be some old drone status shown in issue tracker which was not related to this PR but to javascript stuff.

**Comment by ghost** [comment]
> Issue tracker shows failure status for some reason.

have seen but don't know why. That kind of failure happen sometimes but other doing merge know if this is a Probem or not.

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
