### PR TITLE
Fixed issue 5211

### PR DESCRIPTION
**Pull request by spignataro**
Signed-off-by: Steven Pignataro steven@corephp.com

### CODE REVIEW

**Comment by brianteeman** [comment]
Please provide  a description and test instructions.

**Comment by spignataro** [comment]
Please see issue: https://github.com/joomla/joomla-cms/issues/5211

**Comment by brianteeman** [comment]
Sorry - testing your own code doesnt count. It is assumed you tested it before you submitted.

Please fix the codestyle issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7472">issues.joomla.org/joomla-cms/7472</a>.</sub>

**Comment by matthewbaylor** [comment]
@test patch tests good for me.
Installed patch.
Verified session time out set to 15 min.
Left it sit idle for 20 min.
Navigated to media manager and was logged out.
Logged back in and was returned to the media manager which was displayed as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7472">issues.joomla.org/joomla-cms/7472</a>.</sub>

**Comment by Duke3D** [comment]
Successful install and test.  

Timeout triggered login after appropriate time.  Login redisplayed target page with no issues.

Repeated with a form submission left idle.  Again, successful commit following re-login.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7472">issues.joomla.org/joomla-cms/7472</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7472">issues.joomla.org/joomla-cms/7472</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @spignataro! Merged with https://github.com/joomla/joomla-cms/commit/ba43c6d6af298fa1e2d30ca221698b674004ef28

**Pull request closed without merging**
