### PR TITLE
Revert "Fixing admin user activation"

### PR DESCRIPTION
**Pull request by HLeithner**
Reverts joomla/joomla-cms#31076

`PHP syntax error, unexpected ')'`

Can't believe that anyone tested this PR.

### CODE REVIEW

**Comment by artur-stepien** [comment]
My job that should be merged is #31076 and if you look closely there is only one file changed and it was tested. What you reverted is some mixup with SharkyKZ work. I assume that's what causes the parsing error.

**Comment by HLeithner** [comment]
I don't understand what you mean your pr #31076 has only one commit: https://github.com/joomla/joomla-cms/pull/31076/commits/cb96bed83c28ddef596587844c67de76c11709d6 and github says there is one ) too much. 

I'm wrong?

**Comment by artur-stepien** [comment]
@HLeithner Oh yeah, I see it now. Was confused with #31024 mentioned in here. I'll fix it.

**Comment by HLeithner** [comment]
I reopened #31024 by accident...

**Comment by infograf768** [comment]
And nobody tested it as should have been.
Please make new Pr. no need to upgrade the old one.

**Comment by infograf768** [comment]
And please state that this ONLY concerns multilingual sites.

**Pull request merged**
