### PR TITLE
Fix modal in outdated overrides

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #23199.

### Summary of Changes

Fixes consent field modal in old overrides.

### Testing Instructions

Set Beez3 as default template.
Enable `Content - Confirm Consent` plugin and assign a privacy article.
Go to a contact form.
Click on `Privacy Note`.

### Expected result

Modal with privacy article opens.

### Actual result

Nothing happens.

### Documentation Changes Required
IDK.

### CODE REVIEW

**Review by conseilgouz — APPROVED** [review]
Fix beez3 rendering issue

**Comment by brianteeman** [comment]
Better to fix the override

**Comment by SharkyKZ** [comment]
We can do that. But this also affects 3rd party templates.

**Comment by brianteeman** [comment]
thats why its called an override. if they override something then they have to keep it up to date

**Comment by mbabker** [comment]
We can't force every template to "fix the override".  A lot of core, and a lot of documentation and tutorials, still say to use `$field->label` and `$field->input` to render each field's elements manually, which was honestly the only way to do things from 1.6 up to 3.2 when the `render*` methods were added.  Less documentation and tutorials document things using those, and much of core still doesn't.  So this is honestly yet another compromise that will fix things in the least painful way for the highest number of users.

**Comment by conseilgouz** [comment]
This PR is not included in 3.9.2 RC. 

Is it ok for everybody ?

**Comment by mbabker** [comment]
Without testing and review no patch is merged to core.  There hasn't been much testing and review here.

**Comment by conseilgouz** [comment]
I can't find "HumanTesting" option on this PR and "all checks have passed".

**Comment by ghost** [comment]
@pmleconte https://issues.joomla.org/tracker/joomla-cms/23205

**Comment by infograf768** [comment]
Using Beez, this patch does not open a modal but displays the article below the form.
Link obtained here is of the type:
`/contact-me#modal-jform_consentbox`

Before patch, indeed, we do not even get that.
screen shot 2019-01-12 at 10 58 09

**Comment by infograf768** [comment]
MORE: I needed to enable bootstrap for com_contact for Beez
In that case I do get a modal although the display may be obfuscated if Tabs have been chosen to display the contact.
Works fine with sliders.

**Comment by SharkyKZ** [comment]
Seems to be a z-index issue here:
https://github.com/joomla/joomla-cms/blob/c17bfc4bfc75847c334176c519a87ba871c401de/templates/beez3/css/layout.css#L1005-L1009

**Comment by SharkyKZ** [comment]
Updated beez3 CSS for modal rendering in tabs. Hope this doesn't break anything.

**Comment by ghost** [comment]
@@pmleconte please test > https://docs.joomla.org/Testing_Joomla!_patches

**Review by conseilgouz — CHANGES_REQUESTED** [review]
modal-header is displayed when calling contact form when it should be hidden. It's due to hide class missing from layout.css file.

Chrome Legacy Window 24042019 133214

Just add the following lines in beez3 layout.css file
.hide {
 display;none
}
Chrome Legacy Window 24042019 133305

Pascal

**Comment by SharkyKZ** [comment]
@pmleconte Beez3 has `Components Requiring Bootstrap` option for loading Bootstrap CSS.

**Comment by conseilgouz** [comment]
> @pmleconte Beez3 has `Components Requiring Bootstrap` option for loading Bootstrap CSS.

Oops, i did not read Jean Marie's comment.

Maybe, this could be added to privacy suite documentation.

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on ee3d22c87ea0b27631685a6d7334a147d0cd6324<br /><br />Privacy Note is not a clickable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23205">issues.joomla.org/tracker/joomla-cms/23205</a>.</sub>

**Comment by SharkyKZ** [comment]
@jwaisner did you assign a privacy article in Content - Confirm Consent plugin options?

**Comment by jwaisner** [comment]
Yes, the article was assigned in the plugin options.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23205">issues.joomla.org/tracker/joomla-cms/23205</a>.</sub>

**Comment by SharkyKZ** [comment]
I can't reproduce your issue. Does this happen without patch too?

**Comment by jwaisner** [comment]
With PR applied modal popup works for the consent.

Can I recommend removing the "Next" and "Prev" buttons for the privacy article modal? That might cause confusion and seems to let you navigate the site in the modal window if you click next.

**Comment by SharkyKZ** [comment]
>With PR applied modal popup works for the consent.

I'm confused. Does it work or not? In your screenshot it looks like you're using Protostar template but this needs to be tested on Beez3.

>Can I recommend removing the "Next" and "Prev" buttons for the privacy article modal?

Please open a new issue for this.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on a507f5e9c0b4d4c6406944d7b902b579983eed9f<br /><br />This works as far as this PR concerned. I will open a ticket for the suggestion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23205">issues.joomla.org/tracker/joomla-cms/23205</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a507f5e9c0b4d4c6406944d7b902b579983eed9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23205">issues.joomla.org/tracker/joomla-cms/23205</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23205">issues.joomla.org/tracker/joomla-cms/23205</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
