### PR TITLE
4.0 rename language files

### PR DESCRIPTION
**Pull request by Bakual**
This PR renames the language files so they no longer have a language code prefix (eg en-GB.com_content.ini becomes just com_content.ini).
This is based on a change made in 3.10: https://github.com/joomla/joomla-cms/pull/19353

### Summary of Changes
* Removes language prefix from language files
* The files named `en-GB.ini` become `joomla.ini`
* The files named `en-GB.xml` become `langmetadata.xml`

### Testing Instructions
Enable language debug so you see which files are loaded and if there are translation errors.

### Expected result
There should be no errors. If there are, they should be the same regardless of this PR.

### Documentation Changes Required
In 3.10 and 4.0, the files with language prefix will still work. But documentation for language packs and extensions should be adjusted to let them know of that change.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c5e5234004522aabd3ecc641a8ffae58b40b5c74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27130">issues.joomla.org/tracker/joomla-cms/27130</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c5e5234004522aabd3ecc641a8ffae58b40b5c74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27130">issues.joomla.org/tracker/joomla-cms/27130</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27130">issues.joomla.org/tracker/joomla-cms/27130</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge
have docs been updated? If yes, link?

**Comment by wilsonge** [comment]
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Language

**Comment by infograf768** [comment]
tks

**Pull request merged**
