### PR TITLE
s/cachable/cacheable in comment (I missed one!)

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/cachable/cacheable in comment (I missed one!)

### CODE REVIEW

**Comment by brianteeman** [comment]
Could you please close this and add it to #29812

**Comment by PhilETaylor** [comment]
No because its totally unrelated. 

In fact if you look this was reverted out of  #29812 specifically to be its own issue, as you and others had already tested the large spelling PR I made. 

This is a tiny comment change which is a typo.

 #29812 is about PHP Code and a legacy typo that has massive consequences to change and will hang around unmerged for months/years/forever

The two are totally unconnected.

**Comment by brianteeman** [comment]
and thats why we add descriptions such as - only effects a comment

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2c7ec549328cbb012043a09a69a14eeded93fd64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29813">issues.joomla.org/tracker/joomla-cms/29813</a>.</sub>

**Comment by PhilETaylor** [comment]
I'm sorry that " in comment" in the title was missed by you...

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2c7ec549328cbb012043a09a69a14eeded93fd64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29813">issues.joomla.org/tracker/joomla-cms/29813</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29813">issues.joomla.org/tracker/joomla-cms/29813</a>.</sub>

**Comment by zero-24** [comment]
Merged

**Pull request merged**
