### PR TITLE
[com_fields] Remove unneeded fields from com_fields

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #12733.

### Summary of Changes
* Removes `image` and `image alternate text` fields from the field definition. Those aren't used anywhere and would only confuse users.
* Removes `options`, `attributes`, `created_by_alias`, `publish_up` and `publish_down` columns from the #__fields table. They are not used at all and make no sense in the context of a field.

### Testing Instructions
* Test that creating, editing and general use of fields work as before. There should be no difference except that the two "image" and "image alternate text" fields are no longer part of the edit form.
* To test the database changes, you need to either install a fresh installation or update from a 3.6.5 installation to this branch. So this may be a bit tricky. You can however also manually delete the columns and test or just create a few fields and verify there is no data stored into those columns.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by laoneo** [comment]
The update scripts are missing.

**Comment by zero-24** [comment]
> The update scripts are missing.

@laoneo There are no update needed as it was not in any stable release. ;)

**Comment by laoneo** [comment]
@zero-24 https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-08-29.sql#L21 questions?

**Comment by Bakual** [comment]
> The update scripts are missing.

Look again. The update scripts are there. I adjusted the existing ones so we don't add the fields and remove them again.

**Comment by zero-24** [comment]
Looks good to me after that patch check https://github.com/bakual/joomla-cms/blob/RemoveUnneededFields/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-08-29.sql#L21

**Comment by laoneo** [comment]
Was a mistake on my side. Sorry for the confusion, too long day.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 5fd022a19eee95b0dd8da2356565287ab010c996<br /><br />Tested 2 Fields in Field Group "Details": 

- Field "Colour" is shown correct below "Details"
- Field "Editor" is shown at "Basic Settings".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13621">issues.joomla.org/tracker/joomla-cms/13621</a>.</sub>

**Comment by Bakual** [comment]
@franz-wohlkoenig That's an interesting bug you found there, but not related to this PR.
I actually suspected that this behavior could be possible but haven't got the time to try to produce it. What happens here is that if you name the field alias the same as an existing regular formfield, the custom one will overwrite the existing one. There are two reasons for that: First we allow the admin to name the field the way he wants, which means it can take the name of an existing one. Second we're using the "params" form group to store our fields. That group often is already used by the original form. So it clashes there.

There are already PRs open which would solve that issue:
* Don't store in params group: https://github.com/joomla/joomla-cms/pull/13353
* Remove the alias field: https://github.com/joomla/joomla-cms/pull/13182

**Comment by franz-wohlkoenig** [comment]
@Bakual Changing Fieldname from `Editor` to `Editor1` solved Problem:
bildschirmfoto 2017-01-19 um 21 57 35

**Comment by franz-wohlkoenig** [comment]
Tested Field-type `Gallery` on Article got on different Paths in Front- and Backend: 
- `Warning: JFolder: :files: Path is not a folder. Path: __/images/images/sampledata/fruitshop` 
- and ` Picture-Gallery: Warning: Invalid argument supplied for foreach() in /plugins/fields/gallery/tmpl/gallery.php on line 50`

**Comment by Bakual** [comment]
@franz-wohlkoenig Is that on a Windows machine?

It isn't an issue of this PR, but may be a bug related to the different directory separators.

**Comment by franz-wohlkoenig** [comment]
Test on:
Joomla! 3.7.0-beta1-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5fd022a19eee95b0dd8da2356565287ab010c996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13621">issues.joomla.org/tracker/joomla-cms/13621</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 5fd022a19eee95b0dd8da2356565287ab010c996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13621">issues.joomla.org/tracker/joomla-cms/13621</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 5fd022a19eee95b0dd8da2356565287ab010c996<br /><br />1. I pull the current version of joomla-cms
2. I made a new installation without testdata
3. I installed Patch tester but I get the message
1146 Table 'joomla-cms.#__patchtester_pulls' doesn't exist
 I solved this problem by creating the database tables manually. I had this problem earlier, that is why I tell it. Perhaps someone has a hint for me.
4. I applied the patch
5. I deleted the configuration.php and copied a installation folder and made new installation.
6. I created a lot of field and everything worked well.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13621">issues.joomla.org/tracker/joomla-cms/13621</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 5fd022a19eee95b0dd8da2356565287ab010c996<br /><br />1. I pull the current version of joomla-cms
2. I made a new installation without testdata
3. I installed Patch tester but I get the message
1146 Table 'joomla-cms.#__patchtester_pulls' doesn't exist
 I solved this problem by creating the database tables manually. I had this problem earlier, that is why I tell it. Perhaps someone has a hint for me.
4. I applied the patch
5. I deleted the configuration.php and copied a installation folder and made new installation.
6. I created a lot of field and everything worked well.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13621">issues.joomla.org/tracker/joomla-cms/13621</a>.</sub>

**Pull request merged**
