### PR TITLE
[4.0] use Joomla\CMS\HTML\HTMLHelper;

### PR DESCRIPTION
**Pull request by brianteeman**
namespace JHtml

code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 385d7f2d21314410ec5e7d0124f80df730ddf0de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31685">issues.joomla.org/tracker/joomla-cms/31685</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 385d7f2d21314410ec5e7d0124f80df730ddf0de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31685">issues.joomla.org/tracker/joomla-cms/31685</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31685">issues.joomla.org/tracker/joomla-cms/31685</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
and another one down

**Pull request merged**
