### PR TITLE
[5.0] wincache

### PR DESCRIPTION
**Pull request by brianteeman**
updates the todo comment as it will be removed in 6.0 now and not 5.0

https://github.com/joomla/joomla-cms/blob/acd25e5a79b3a1dc2f96681a024ce4940c34ad68/libraries/src/Cache/Storage/WincacheStorage.php#L23

### CODE REVIEW

**Comment by brianteeman** [comment]
or should all the wincache stuff simply be removed as its not compatoble with php 8

**Comment by HLeithner** [comment]
Tbh it's dead since ages, so i think we should remove it directly.

**Comment by brianteeman** [comment]
ok - closing this pr and will make a new one

**Comment by HLeithner** [comment]
And if I'm not wrong it has been deprecated in 3.x

**Pull request closed without merging**
