### PR TITLE
[staging] [fix] Bugs in multilingual associations component

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/18552
(The original issue, plus the further discovered ones with `Publishing Options`)
Plus solving other bug.

### Summary of Changes
1. Adding hidden `id` field in layouts/joomla/edit/global.php
2. Moving code for the allowed categories to choose from in `Select Target` to the correct view
3. Solving https://github.com/joomla/joomla-cms/issues/18552 by preventing race condition caused by loading Target iframe at the same time as Reference. Thank you Robbie Jackson !!!

### Testing Instructions
Set a multingual sites with some articles associations and some categories set to All languages and different content languages.

Bug1. 
In Articles Global Options, set `Show Publishing Options` to hide

screen shot 2018-09-13 at 15 33 56
Go to the multilingual component. Choose articles and a language. Try to load the sidebyside for an article ot its associated item. We get in a loop.

jform_id

Bug2. 
Load the side by side view from clicking on an article or contact or Newsfeed (after setting `Show Publishing Options` back to Show.
In the Target part click on `Select Target` (or `Change Target` to load the modal.
In the modal click on SearchTools.
Then click on `Select a Category`
The dropdown will display all categories, although it should ONLY display categories tagged to ALL languages or to the language of the Target item.

screen shot 2018-09-13 at 15 52 29

Bug3. 
Filter by articles and one of the Content languages.
The items already associated show as a grey button.
Click on one of these grey buttons to load the side by side page with the already defined target (tagged to the language of the grey button)

The first time one clicks, the already associated target first appear for a while and then disappear to finally display a blank article.
Close the side by side page and then click again the same grey button.
This time all is fine, the already associated target displays fine.

com_assoc

This may depend on the session and cache used on site. I get this all the time on my test sites

### After patch
Bug1 solved as we always have a `jform_id` obtained from the hidden id field

Bug2 solved

screen shot 2018-09-13 at 15 40 37

Bug3 solved. No need to reload.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by alikon** [comment]
i've tested succesfully
but unable to mark it on Issue Tracker cause this pr is not listed
same as https://github.com/joomla/joomla-cms/pull/22175#issuecomment-421103754

p.s
maybe the Issue Tracker don't like PR from @infograf768 
:smile:

**Comment by wojsmol** [comment]
@alikon This PR is listed correctly for me in issue tracker.

**Comment by alikon** [comment]
screenshot from 2018-09-13 21-23-20

@wojsmol 
i  belive you 
but believe  me i'm not able to use gimp :rofl: 

update
now i can see it but still cannot mark the test result

maybe some cron jobs  is going to have a break  :smile:

**Comment by infograf768** [comment]
Test button issue cconfirmed.
One more tester needed here as we can RTC and merge here eventhough we have this issue with the test button.

**Comment by zero-24** [comment]
Issues described here are fixed by the patch provided. Thanks @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22166">issues.joomla.org/tracker/joomla-cms/22166</a>.</sub>

**Pull request merged**
