### PR TITLE
[4.0] Default Menu item

### PR DESCRIPTION
**Pull request by brianteeman**
When setting the default menu item on and off you will see that the publish up and publish down fields are shown/hidden as appropriate. However because they are above the home button it creates a usability and an accessibility as you have already navigated passed those fields.

This PR simply changes the order.

### before
before

### after
after

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 445c3e6046a8b9946edb1ef78b8cf1403186f509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33124">issues.joomla.org/tracker/joomla-cms/33124</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 445c3e6046a8b9946edb1ef78b8cf1403186f509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33124">issues.joomla.org/tracker/joomla-cms/33124</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33124">issues.joomla.org/tracker/joomla-cms/33124</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks for testing and merging

**Pull request merged**
