### PR TITLE
[5.1] Use Dialog for Batch for Redirect component

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Use Dialog for Batch for Redirect component.
I somehow forgot it in previous PR https://github.com/joomla/joomla-cms/pull/42328

### Testing Instructions
Use "Bulk Import" button to import an urls in Redirect component.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0f3a32c483d1df5fe6338ac29892c504d8374497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42355">issues.joomla.org/tracker/joomla-cms/42355</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0f3a32c483d1df5fe6338ac29892c504d8374497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42355">issues.joomla.org/tracker/joomla-cms/42355</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42355">issues.joomla.org/tracker/joomla-cms/42355</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and for testing @Quy @viocassel

**Pull request merged**
