### PR TITLE
[5.0] Codemirror RTL fix in com_templates

### PR DESCRIPTION
**Pull request by brianteeman**
Text-align is not the same as direction.

As this is a css change you will need to test with a prebuilt package or with the build scripts

Pull Request for Issue #42654 .

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have successfully tested this PR. ✅ 

As the issue tracker currently has a problem, I can't mark my test result there.

**Comment by Quy** [comment]
Tested successfully.

**Comment by Quy** [comment]
RTC

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
