### PR TITLE
[5.0][Events] Schemaorg event classes

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Implementing Event classes for Schemaorg events.

Affected events:

* [x] onSchemaBeforeCompileHead
* [x] onSchemaPrepareData
* [x] onSchemaPrepareForm
* [x] onSchemaPrepareSave

### Testing Instructions

- Apply patch (and delete autoload_psr4.php)
- Create schemas for articles and contacts in backend
- Check output in frontend

### Actual result BEFORE applying this Pull Request

works but support no concrete events

### Expected result AFTER applying this Pull Request

works with legacy and concrete events

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: [Plugin/Events#Schemaorg](https://docs.joomla.org/Special:MyLanguage/Plugin/Events#Schemaorg)
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
@Fedik can you have a look at this please?

**Comment by Fedik** [comment]
Looks good, by code review

**Comment by heelc29** [comment]
conflicts resolved

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
