### PR TITLE
[4.0] RTL logical property mod-list

### PR DESCRIPTION
**Pull request by brianteeman**
The class mod-list is used extensively in the site modules.

This PR replaces the use of separate LTR and RTL classes by using css logical properties

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0fe93f229be51af4998d7d88022e27cd45816d4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34835">issues.joomla.org/tracker/joomla-cms/34835</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0fe93f229be51af4998d7d88022e27cd45816d4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34835">issues.joomla.org/tracker/joomla-cms/34835</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34835">issues.joomla.org/tracker/joomla-cms/34835</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
