### PR TITLE
[4.0] Add missing import

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix `Class 'Factory' not found`.

### Testing Instructions
Go Users > Privacy
Click Dashboard icon
Apply PR
No error

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 4a2da2d42302bb1113097eb6cc6cdfc8991992ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26736">issues.joomla.org/tracker/joomla-cms/26736</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 4a2da2d42302bb1113097eb6cc6cdfc8991992ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26736">issues.joomla.org/tracker/joomla-cms/26736</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26736">issues.joomla.org/tracker/joomla-cms/26736</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
