### PR TITLE
[4.0] Code cleanup: remove setFieldAttribute('catid', 'action', …)

### PR DESCRIPTION
**Pull request by nhusung**
### Summary of Changes

Since the introduction of the `CategoryEdit` form field in the edit models/views of `com_content`, `com_contact`, `com_newsfeeds` and `com_banners` (joomla/joomla-cms@d6673d7), there is no `action` attribute on the `catid` form field and thus no need to set it anymore.

### Testing Instructions

As the changes are pretty small, a code review should be enough. However you can have a look at the category field inside the edit forms of com_content, com_contact, com_newsfeeds and com_banners with users associated to different groups and access levels and privileges.

### Expected result

Same as before this pull

### CODE REVIEW

**Comment by SharkyKZ** [comment]
@nhusung Can you fix the conflict please.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on cca35fa036e9c8dd96250dc91b73531d2cfefcd1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24329">issues.joomla.org/tracker/joomla-cms/24329</a>.</sub>

**Comment by SharkyKZ** [comment]
There are conflicts again 😕 .

**Comment by nhusung** [comment]
Sorry, I made a mistake during the merge

**Comment by nhusung** [comment]
Now my problem should be fixed, sorry again. However, the first push added some review requests and I couldn‘t find a way to remove these. I hope I‘m not getting on your nerves …

**Comment by ghost** [comment]
@nhusung thanks for Contributing, no reason for care about nerves :-)

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 28ea0f76474d380e472ca660c19442e6722efcbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24329">issues.joomla.org/tracker/joomla-cms/24329</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
