### PR TITLE
[4.0] key exists is an alias

### PR DESCRIPTION
**Pull request by brianteeman**
key_exists is an alias for array_key_exists. Better to use array_key_exists (which we do over 500 times)

code review

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on d3690c2d4ecea8d371ca6154de945652ac426235<br /><br />Code review.

I have never ever used `key_exists` in my life! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34345">issues.joomla.org/tracker/joomla-cms/34345</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d3690c2d4ecea8d371ca6154de945652ac426235<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34345">issues.joomla.org/tracker/joomla-cms/34345</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34345">issues.joomla.org/tracker/joomla-cms/34345</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
