### PR TITLE
[Accessibility] Convert b tags to strong

### PR DESCRIPTION
**Pull request by dgrammatiko**
This a complimentary PR to #6467 from @nonumber
#### What is changed?
1. All tags from `<b>` converted to `<strong>`
2. The `<h3>` on the bootstrap modal is converted to `<p class="lead><strong>`

Results before applying this:

screen shot 2015-03-17 at 3 28 45

### CODE REVIEW

**Comment by nonumber** [comment]
The ```<b class="caret"></b>``` should not be converted to ```strong```, but to ```span```. I have already done that in https://github.com/joomla/joomla-cms/pull/6467

**Comment by dgt41** [comment]
Also this brings another point for discussion: the chosen script is throwing some `<b>` tags…
This can be either tapped by:
1. making a PR to their repo (even tho we use an outdated version)
2. patch it in jui folder
3. introduce select2 or bootstrap select

screen shot 2015-03-17 at 3 38 20

**Comment by dgt41** [comment]
Thanks @nonumber, will take it out from here

**Comment by nonumber** [comment]
What is the reason for not using the ```<h3>``` in the modals?

**Comment by nonumber** [comment]
For chosen: Best is to have them fix it on their side and then update to that version once it's fixed.
Best not to tamper with the 3rd party js files.

**Comment by nonumber** [comment]
Chosen: https://github.com/harvesthq/chosen/pull/2270

**Comment by dgt41** [comment]
H tags should cascade gracefully. Try users list view: there is an h1 for the title and if there is user note the modal title will be an h3 tag. But h3 should follow after an h2...

**Comment by dgt41** [comment]
@nonumber Peter the problem with chosen isn’t so simple. Joomla is using chosen v0.14 but chosen is now at v1.4.1. The problem is that with the release of version 1.0 is the change all the selectors from `chzn-` to `chosen-` which obviously breaks backwards compatibility. Your PR is against the latest staging but here we still use something outdated, so even if that gets accepted we still can’t use that as it is incompatible with joomla’s b/c policy. Is kinda dead end situation with that code, that’s the reason I suggested to move on to select2 or bootstrap select...

**Comment by nonumber** [comment]
Going by the explanation of the Chosen guys at https://github.com/harvesthq/chosen/pull/2270#issuecomment-82509746 I think we'll just let this be for what it is.

**Comment by dgt41** [comment]
I don’t see much interest on this, so I am gonna close it.

**Pull request closed without merging**
