### PR TITLE
Moving association saving to JModelAdmin

### PR DESCRIPTION
**Pull request by Bakual**
### Background

This is a followup PR on #7583. That PR introduced a new property `$associationsContext` for model classes which holds the context for the association table. We now use this property to safely delete associations in JModelAdmin if an item is deleted.
A similar thing can be done when saving the associations
### Issue

Currently, we have the same code duplicated for each extension where we support associations. With the only difference being the context of the item we're saving.
This is just tedious for extension developers.
### Solution

Using that new `$associationsContext` property we can now do the saving in JModelAdmin instead of each child model. Which means the extension developers just have to define that property and the associations will be saved automatically.
### Testing

The following extensions need to be tested. Make sure you can associate items from different languages together as before. There should be no change in function at all.
- com_content (Articles)
- com_contact (Contacts)
- com_newsfeed (Newsfeeds)

The following extensions just changed the context from being hardcoded to use the class property now. The code to save the associations is still in the child class since the parent method isn't used there.
- com_categories (Categories)
- com_menus (Menu Items)

### CODE REVIEW

**Comment by infograf768** [comment]
Test OK here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7617">issues.joomla.org/joomla-cms/7617</a>.</sub>

**Comment by joomlacorner** [comment]
worked here too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7617">issues.joomla.org/joomla-cms/7617</a>.</sub>

**Comment by infograf768** [comment]
2 test OK. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7617">issues.joomla.org/joomla-cms/7617</a>.</sub>

**Comment by gwsdesk** [comment]
Just for the records otherwise "Opa" get's annoyed: Works like a charm JM ..... ;_) RTC indeed

**Pull request merged**
