### PR TITLE
[4.0] Correct code comments

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted this copy/paste error when trying to debug #24973

Can be merged on review I hope

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21dc45fa9ce1ee5931cf48d69bffe57cd6c08dfe<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24974">issues.joomla.org/tracker/joomla-cms/24974</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 21dc45fa9ce1ee5931cf48d69bffe57cd6c08dfe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24974">issues.joomla.org/tracker/joomla-cms/24974</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24974">issues.joomla.org/tracker/joomla-cms/24974</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
