### PR TITLE
[4.0] Fix actionlog message value

### PR DESCRIPTION
**Pull request by twister65**
Pull Request for Issue #24846 .

### Summary of Changes
Load language on after initialise.

### Testing Instructions
- Enable/Disable a plugin.
- Add/Update/Delete an extension, an article, an user, a group.
- Publish/Unpublish/Trash/Archive an article, a categorie, a menu.
- See the Latest Actions module in the Control Panel

### Expected result
No constant value, the actionlog message is translated.

### Actual result
As expected result.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This is not the right fix. The underlying issue has been discussed here https://github.com/joomla/joomla-cms/issues/17444. Until it is fixed, plugin language files can be loaded manually with `$this->loadLanguage()` in `onAfterInitialise()`.

**Comment by infograf768** [comment]
Diff would be
```
diff --git a/plugins/system/actionlogs/actionlogs.php b/plugins/system/actionlogs/actionlogs.php
index 521b510..0d4f97d 100644
--- a/plugins/system/actionlogs/actionlogs.php
+++ b/plugins/system/actionlogs/actionlogs.php
@@ -64,4 +64,23 @@
 
 	/**
+	 * Listener for the `onAfterInitialise` event
+	 *
+	 * @return  void
+	 *
+	 * @since   4.0
+	 */
+	public function onAfterInitialise()
+	{
+		if (!$this->app->isClient('administrator'))
+		{
+			return;
+		}
+
+		// Load plugin language files only when needed (ex: they are not needed in site client).
+		$this->loadLanguage();
+	}
+
+
+	/**
 	 * Adds additional fields to the user editing form for logs e-mail notifications
 	 *
```

**Comment by infograf768** [comment]
@twister65 
Please modify your PR with the code above.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4c4b0a8dcaad037f513587d3109e5aee6c7f94ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24847">issues.joomla.org/tracker/joomla-cms/24847</a>.</sub>

**Comment by wilsonge** [comment]
`protected $autoloadLanguage = true;` you need to remove this class property otherwise it will always be loaded in the constructor anyhow?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
