### PR TITLE
[4.0] [a11y]Decorative images

### PR DESCRIPTION
**Pull request by brianteeman**
These joomla logos are purely decorative so in this case we need to have a null alt text
https://www.w3.org/WAI/tutorials/images/decorative/

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1c7eeceb0068413bfd3ed5f53586fbf6a516dca3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21102">issues.joomla.org/tracker/joomla-cms/21102</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 1c7eeceb0068413bfd3ed5f53586fbf6a516dca3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21102">issues.joomla.org/tracker/joomla-cms/21102</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21102">issues.joomla.org/tracker/joomla-cms/21102</a>.</sub>

**Comment by laoneo** [comment]
Can you remove the `$sitename` variable completely in _index.php_ and _full_errror.php_ as it is not used anymore, except on the places you have removed?

**Comment by brianteeman** [comment]
@laoneo removed as requested

**Comment by laoneo** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
