### PR TITLE
[4.0] View Private Message

### PR DESCRIPTION
**Pull request by brianteeman**
Just some styling

pr for #26915 

### before
image

### after
image

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on b4a60f37ec171e84a721a2fcbb745807b21c64d8<br /><br />tested

immagine

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on b4a60f37ec171e84a721a2fcbb745807b21c64d8<br /><br />perfect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b4a60f37ec171e84a721a2fcbb745807b21c64d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :red_circle: unsuccessfully on b4a60f37ec171e84a721a2fcbb745807b21c64d8<br /><br />I have a test with Safari 13.0.5 o macOS and it doesn't work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

Schermata 2020-04-11 alle 16 21 15

**Comment by brianteeman** [comment]
@adj9  that screenshot is nothing to do with this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by ggenovino** [comment]
I have tested this item :white_check_mark: successfully on b4a60f37ec171e84a721a2fcbb745807b21c64d8<br /><br />I have successfully tested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28646">issues.joomla.org/tracker/joomla-cms/28646</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
