### PR TITLE
[5.0] [New Feature] TinyMCE Image Classes

### PR DESCRIPTION
**Pull request by brianteeman**
Based on user feedback this PR adds the ability to add "Left, Right & Center" alignment for images using the tinymce image button. This uses the tinymce api and existing tinmyce language strings so should be compatible with all languages and easy to maintain etc.

As a bonus this resolves the current issue that after inserting an image with the media manager when you select the image again you can change the alignment.

This is NOT using inline styles. It uses correct classes but as they are present in cassiopeia but not in the editor.css they have been added to the editor.css to ensure they preview correctly.

To test either use a prebuilt package or apply the pr and rebuild the css `npm run build:css`

https://user-images.githubusercontent.com/1296369/152953050-92ec009f-798d-4867-87c0-4d1ae576a295.mp4

### CODE REVIEW

**Comment by brianteeman** [comment]
closed due to lack of interest from release lead

**Comment by brianteeman** [comment]
re-opening. this is far more useful to users than other features being added to 4.2 and does not already have an extension offering this on the jed

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev.

**Comment by brianteeman** [comment]
This is even more important in joomla 5 as tinymce have removed the ability to add a style to an image

**Comment by HLeithner** [comment]
That are bootstrap only classes right? might it be more useful to make this configurable in the plugin?

**Comment by brianteeman** [comment]
Someone else can do that. I am not going to waste my time creating another config that no one will use. On the day that a template provider that uses a different framework actually contributes to joomla then I could look at it again. We need to stop pretending that we can be css framework neutral when they never contribute to make it happen.

**Comment by laoneo** [comment]
As far as I can see it, these are only floats, so instead of using BS classes, just make generic ones for the editor.

**Comment by brianteeman** [comment]
> As far as I can see it, these are only floats, so instead of using BS classes, just make generic ones for the editor.

and then people will need to add those generic ones to their existing bootstrap templates when they have a perfectly good class already. Sorry your suggestion makes no sense.

or did you mean to add an inlinen style for the float? that makes even less sense

**Comment by brianteeman** [comment]
please read it again

**Comment by fancyFranci** [comment]
I have tested this item :red_circle: unsuccessfully on 10e3fb9dfc3879a918f1ac695ca46aaea7fa2328<br /><br />As soon as I add the change I can not edit the article any more. Console gives the error message "Uncaught TypeError: o is null" in tinymce.js.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36962">issues.joomla.org/tracker/joomla-cms/36962</a>.</sub>

**Comment by fancyFranci** [comment]
screen shot 2023-08-26 at 11 03 05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36962">issues.joomla.org/tracker/joomla-cms/36962</a>.</sub>

**Comment by brianteeman** [comment]
@fancyFranci how did you apply the pr? Did you rebuild with npm

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on c56e1b2761e46e2e13ead1ae38887d5f9806ca51<br /><br />I tested again the same way like before, but maybe testing your plugin-PRs with some more build:js/:css in the meanwhile helped? Anyway, now it's working correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36962">issues.joomla.org/tracker/joomla-cms/36962</a>.</sub>

**Comment by HLeithner** [comment]
can you create a documentation for template devs in the manual? and maybe something in the migration section?

**Comment by brianteeman** [comment]
will do

**Pull request merged**
