### PR TITLE
[4.1][bug] TinyMCE language bug

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36966 .

### Testing Instructions
- open an article for editing (or anything that uses tinymce)
- observe the missing script file
- Apply the patch and revisit the same page
- Repeat but with debug enabled

### CODE REVIEW

**Comment by brianteeman** [comment]
```
Failed to load resource: the server responded with a status of 404 (Not Found)
tinymce.min.js?a8a418fd78a33f2adf92579f95dbe2ba:9 Failed to load language: en.min from url http://localhost/joomla-cms/media/vendor/tinymce/langs/en.min.js
Mv @ tinymce.min.js?a8a418fd78a33f2adf92579f95dbe2ba:9
```

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0e5aa332b3b06d3d33b98e13532e5ae339a5871b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36971">issues.joomla.org/tracker/joomla-cms/36971</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0e5aa332b3b06d3d33b98e13532e5ae339a5871b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36971">issues.joomla.org/tracker/joomla-cms/36971</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36971">issues.joomla.org/tracker/joomla-cms/36971</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
