### PR TITLE
debug bar update to 1.18

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #37274 .

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Does this PR also solve the following part of the mentioned issue?

> And some deprecations in fields with date:
> Deprecated: Function strftime() is deprecated in C:\OpenServer\domains\joomla.test\libraries\src\Form\Field\CalendarField.php on line 277

If not, you should maybe make clear in the description that it solves only a part of the issue, and reopen the issue.

**Comment by alikon** [comment]
this cover only the  https://github.com/maximebf/php-debugbar part hopefully
got some strange ukranian support messages from composer :star_struck:

**Comment by alikon** [comment]
thanks @richard67 :+1:

**Comment by alikon** [comment]
for those curious https://github.com/composer/packagist/commit/86244a3695fcaaac9c5ba4257a4314eae1c6d981

**Pull request closed without merging**
