### PR TITLE
[com_content][featured] - fix category filter

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23450 .

### Summary of Changes
fix filter on category

### Testing Instructions
see #23450

### CODE REVIEW

**Comment by carlitorweb** [comment]
Thank you @alikon . This fixed the problem, but now if I make this:

**Parent Category
____ Children Category
_________ 2 Children Category**

And assign a feature article to the category "2 Children Category", this article is not listed on Featured Articles View, even without using a filter. The view is only listed the 0 and 1 categories levels

**Comment by alikon** [comment]
unable to replicate
screenshot from 2019-01-07 13-07-33
with this tree
screenshot from 2019-01-07 13-08-42

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 57a132bfbb4f9bf698f1a5323071a59ea67f20ab<br /><br />My apologies were my mistake running that test. I check again and work as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23454">issues.joomla.org/tracker/joomla-cms/23454</a>.</sub>

**Comment by carlitorweb** [comment]
@Quy  Can we include this in the next release?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 57a132bfbb4f9bf698f1a5323071a59ea67f20ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23454">issues.joomla.org/tracker/joomla-cms/23454</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23454">issues.joomla.org/tracker/joomla-cms/23454</a>.</sub>

**Pull request merged**
