### PR TITLE
Update en-GB.com_users.ini

### PR DESCRIPTION
**Pull request by webgras**
Pull Request for Issue #25099 .

### Summary of Changes
Change language code for verification error message.

### Testing Instructions
Setup global user options for "Allow User Registration" - Yes
"New User Account Activation" - "Self"
Register a new user in the frontend.
Now you have two options:
1. Go back to Administrator and activate the user manually. Then go back to the email and click the confirmation link in the email. 
--> error message "verification code not found".
2. don't activate the user manually, but click the activation email one time. --> user is activated
Now, if you click the activation link again, the error is also shown.

### Expected result
User get confused, give more information why the token is not found.

### Actual result
New error message: Verification code not found. Check if your account is already activated and try to log in. Check also if the token is copied correctly to the browser address bar.

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally speaking I don't see this as a general improvement - especially the last sentence which is meaningless on a mobile device.

For me this is the sort of the thing that should be left to the site owner to modify as an override

**Comment by webgras** [comment]
@brianteeman hm, yes, probably. However, it is not so easy to find out why you get this error message. I mean, the administrator might know that the account would be already activated. But the enduser in the frontend gets an error that they could actually overcome, if they would go and try logging in. But they have no idea they could do that.

I think in quite some projects it would help people to find the solution faster. My client had quite some discouraged users. 

I was not sure about the second part - yes, for mobile device that does not make sense. So, maybe just remove that part.

I am okay if it does not get merge - i wanted to help UX. I am okay in my projects with this error to solve.

**Comment by ghost** [comment]
@webgras Can you delete the last Sentence "Check also if the token is copied correctly to the browser address bar."? The "Check if your account is already activated and try to log in." is helpful.

@brianteeman comment?

**Comment by brianteeman** [comment]
The other solution would be to check if the account has already been verified and only then to display that specific error message

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 852855db008348e60243d4ed4c5950ab59aabdeb<br /><br />Hi Sigrid,

after Patch, got following response:
403 Verification code not found. Check if your account is already activated and try to log in. Check also if the token is copied correctly to the browser address bar.

But this: "Check also if the token is copied correctly to the browser address bar." is confusing :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25107">issues.joomla.org/tracker/joomla-cms/25107</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 852855db008348e60243d4ed4c5950ab59aabdeb<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25107">issues.joomla.org/tracker/joomla-cms/25107</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25107">issues.joomla.org/tracker/joomla-cms/25107</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25107">issues.joomla.org/tracker/joomla-cms/25107</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC

**Comment by SharkyKZ** [comment]
RTC

**Comment by brianteeman** [comment]
@SharkyKZ just because something has 2 tests doesn't mean it should automatically be RTC

This relates to an english language string. No native english speaker has approved/tested this. One of the testers still commented that they didnt understand the new message

**Comment by SharkyKZ** [comment]
@brianteeman Shouldn't a maintainer decide what to do next?

**Comment by infograf768** [comment]
Imho, we could do without the last sentence indeed.

**Comment by SharkyKZ** [comment]
Status set back to Pending. Bot keeps adding PR-4.0-dev label 😕

**Comment by infograf768** [comment]
@webgras 
Please modify this PR by taking off the last sentence.

**Comment by webgras** [comment]
ah, sorry, wrong button. I will change the language string and then commit again.

**Comment by HLeithner** [comment]
> The other solution would be to check if the account has already been verified and only then to display that specific error message

@brianteeman Without looking at the code I think we don't want to expose if the account exists or not. I know maybe makes not much sense to hide it, at least for sites with public registrations.

Anyway do you have anything against the wording?

**Comment by brianteeman** [comment]
@HLeithner possibly correct - it was just a suggestion because I don't like having a single message for multiple "_errors_"

**Comment by HLeithner** [comment]
ok thanks for then I merge this and if someone came up with a better solution we can talk about this again.

**Comment by HLeithner** [comment]
thanks @webgras for this patch

**Pull request merged**
