### PR TITLE
Modified function name to avoid conflict with PHP keyword.

### PR DESCRIPTION
**Pull request by eeshaanSA**
Pull Request for Issue  #37823 
Link for the issue: 
[https://github.com/joomla/joomla-cms/issues/37823](url)

### Summary of Changes
Changed the function name to avoid conflict with PHP keyword. Previously it was "match", but match is a PHP keyword since PHP 8.0, so changed it to "_match". 

### Open Questions:
I am unware of of the naming standards followed by the Joomla! team, so if you want me to change the name to something more 'understandable', let me know. 
Other function names that I have in mind:
- match_useragent
- match_features

### Actual result BEFORE applying this Pull Request
nil

### Expected result AFTER applying this Pull Request
nil

### Documentation Changes Required
None to my knowledge.

### CODE REVIEW

**Comment by richard67** [comment]
@eeshaanSA It seems you either have missed or not understood this comment in the issue: https://github.com/joomla/joomla-cms/issues/37823#issuecomment-1129313947 . It says that there is no need for this change here, but if you change it you have to keep the method with the old name and let it can a method with a new name, and the old method is to be deprecated and can be removed not before version 5.

So this PR here is wrong as it is now.

**Comment by richard67** [comment]
P.S.: See also this doc about Joomla‘s semantic versioning https://developer.joomla.org/roadmap.html .

**Comment by eeshaanSA** [comment]
Sorry i missed the comment. So there are no changes required as of now?

**Comment by richard67** [comment]
@eeshaanSA There are no changes REQUIRED. But what still CAN be done is to add a new method with a good name, let the old method with the „bad“ name call the new one so the old one is just a proxy to the new one, and add a deprecation note to the documentation block of the old method.

**Comment by richard67** [comment]
So either close this PR or change it as requested in the above comment.

**Comment by eeshaanSA** [comment]
understood @richard67 . will try to work on the change.

**Comment by eeshaanSA** [comment]
@richard67 i would like some help on the deprecation note. along with the deprecated tag and the version, is there anything else I am supposed to mention in the documentation block of the method?

**Comment by richard67** [comment]
> @richard67 i would like some help on the deprecation note. along with the deprecated tag and the version, is there anything else I am supposed to mention in the documentation block of the method?

@eeshaanSA No, there isn't anything else. Just search for sting "@deprecated" in PHP files and you will find examples. I suggest you change this PR, then we (me or other maintainers or contributors) can suggest changes if necessary.

**Comment by ditsuke** [comment]
@eeshaanSA

See this for how to log the deprecation:
https://github.com/joomla/joomla-cms/blob/360409f51cd81de6ca302ee3a51e718f26d3fa7b/libraries/src/Application/CMSApplication.php#L422-L426

**Comment by eeshaanSA** [comment]
sorry, commited the same code by mistake. Deleted the whole PR. will submit a new one shortly and provide a link to it.

**Pull request closed without merging**
