### PR TITLE
Single line

### PR DESCRIPTION
**Pull request by laoneo**
Make the line a bit more inline with the rest. Simple CS fix which can be merged by review.

### CODE REVIEW

**Comment by heelc29** [comment]
It looks like the changes from package.json are missing from upmerge from 4.4-dev to 5.x-dev, so no *.mjs are checked in 5.2-dev  
https://github.com/joomla/joomla-cms/pull/43778

**Comment by laoneo** [comment]
Strange yeah. Can you do another pr against 5.2 with these changes.

**Comment by heelc29** [comment]
> Strange yeah. Can you do another pr against 5.2 with these changes.

Done, see #44443

**Comment by laoneo** [comment]
Thanks!

**Pull request closed without merging**
