### PR TITLE
Fix media manager when using 0 maximum file size

### PR DESCRIPTION
**Pull request by maliouris**
Pull Request for Issue #30567 

### Summary of Changes

Check if maximum file size is set to 0 and let user upload the image, else check if file size is larger than the maximum file size and throw error

### Testing Instructions

Set maximum file size to 0.

### Actual result BEFORE applying this Pull Request

Can't upload any image

### Expected result AFTER applying this Pull Request

Upload images as expected

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 84e1f80b692a12fd3724a761bf0c19ac776c745c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30572">issues.joomla.org/tracker/joomla-cms/30572</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 84e1f80b692a12fd3724a761bf0c19ac776c745c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30572">issues.joomla.org/tracker/joomla-cms/30572</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30572">issues.joomla.org/tracker/joomla-cms/30572</a>.</sub>

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on 84e1f80b692a12fd3724a761bf0c19ac776c745c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30572">issues.joomla.org/tracker/joomla-cms/30572</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by wilsonge** [comment]
Thankyou for you first PR to joomla ❤️

**Comment by maliouris** [comment]
Thank you, although It's not my first PR to joomla

**Pull request merged**
