### PR TITLE
Replace Help Popup for Help modal

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
### Summary of Changes

The title says it all Replace Help Popup for Help modal.

modal-help
### Testing Instructions

Apply patch and test the "Help" buttons in the backend views.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
hum ... it seems this failed a unit test ...

**Comment by mbabker** [comment]
The test is checking the HTML the button's echoing.  Yay for [flaky tests](https://github.com/joomla/joomla-cms/issues/10984)

**Comment by mbabker** [comment]
Even better the test is manipulating global state and causes side effects.

**Comment by andrepereiradasilva** [comment]
:smile: so what to do here?

**Comment by chrisdavenport** [comment]
I'm not in favour of this change.  Having a separate window means that the help screens can be separately navigated side-by-side with the application.  You can follow along with a set of instructions on the help screen without having to cancel the help and then having to re-open the help screen again for the next instruction.

**Comment by brianteeman** [comment]
Good point. I hadn't thought of that scenario. Definitely a valid reason
not to accept this pr

**Comment by andrepereiradasilva** [comment]
so, how about adding a open in new window button in the modal footer for those that want to use that  `navigated side-by-side with the application`?

**Comment by brianteeman** [comment]
What's the point of adding this extra step

**Comment by andrepereiradasilva** [comment]
ok i just tried what @chrisdavenport said and i have to say that's in fact handy for people learning joomla.
so i will close this PR

**Pull request closed without merging**
