### PR TITLE
[4.1] Remove maximebf debugbar developer stuff from builds and on update

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This pull request (PR) adds removal of .bowerrc and bower.json files from 3rd party libraries in general and of the "build", "demo", "docs" and "tests" folder or the composer dependency "maximebf/debugbar" in particular to the build script "build/build.php" so that these files and folders which are not needed on a J4 installation will not be included in the full installation or update packages.

Furthermore it adds the mentioned files and all files in the mentioned folders to script.php to the list of files to be removed on update and the folders to the list of folders to be removed on update.

The reason for this is that again - like it was before with another dependency and fixed with my PR #37458 - these developer files have been released with the 4.1.3 release in the installation package, while they are not in the 4.1.4-dev nightly builds and also not in packages which I build here locally on Linux.

### Testing Instructions

Code review by someone who knows the build process should be enough this time.

Ping @wilsonge .

I am not really willing to write again such detailed testing instructions like I did for my PR #37458 .

### Actual result BEFORE applying this Pull Request

Depending on your environment (OS), there might or there might not be all these files and folders in the full installation package when you build it locally.

### Expected result AFTER applying this Pull Request

None of these files and folders is in the full installation package when you build it locally, as it is with the nightly builds.

### Documentation Changes Required

None.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
//cc @bembelimen

**Comment by bembelimen** [comment]
Yep, thx, I'm aware of it :+1:

**Comment by laoneo** [comment]
Keep in mind, once the debug bar dependency will be reverted back to the official release, then these changes can probably be reverted. This was introduced with #37488 and the open issue is #37274.

**Comment by richard67** [comment]
> Keep in mind, once the debug bar dependency will be reverted back to the official release, then these changes can probably be reverted. This was introduced with #37488 and the open issue is #37274.

@laoneo The change in build.php maybe, but the change in script.php will still be necessary if we want to clean up these files when updating from 4.1.3.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
