### PR TITLE
[4.0] boolean check

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24452.

### Summary of Changes
added the check

### Testing Instructions
see #24452

### CODE REVIEW

**Comment by ghost** [comment]
@chmst can you please test?

**Comment by chmst** [comment]
This does not work. It results  in a notice in view.html.php, where an array is expected, empty or not..
An empty result in articles is quite normal. 
The related issue was probably caused by an inconxistency in the database of my repo. After installing the whole new with a fresh database, theis issue was solved.

**Comment by mbabker** [comment]
> It results in a notice in view.html.php, where an array is expected, empty or not..

The view needs to account for this return type too.  Folks, error handling is simple; you should not be writing code assuming that things will never have errors and things will always work as expected and you can't tell people the fix to running into these errors is to drop your database and reinstall everything.  Error handling is not a new programming concept, but the fact that Joomla has next to none of it is quite embarrassing.

**Comment by ggppdk** [comment]
I agree with @chmst
Finding zero records is not an error to return false
An empty array should be returned.

Regarding the error handling in case that this method return false on real errors, i agree with @mbabker,  view.html.php should be patched too (in some other PR along with other files ?)

**Comment by mbabker** [comment]
Finding 0 records is not the error, `getItems()` in that case should be returning an empty array (because of type coercion with PHP the if check probably needs to be `if ($items === false)`).  The intent here is to handle the case when `getItems()` DOES reach an error and returns boolean false instead of an array.  And no, returning an empty array in the error case is not a proper fix.

**Comment by alikon** [comment]
patched the view

**Comment by euismod2336** [comment]
Well, as far as i can quickly see, it's possible to get an empty array from getTransitions. That gives a 500 error however because the view checks for falsy instead of false.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24458">issues.joomla.org/tracker/joomla-cms/24458</a>.</sub>

**Comment by wilsonge** [comment]
@alikon can you patch the comment from @euismod2336 please

**Comment by alikon** [comment]
@wilsonge @euismod2336  not sure to understand can you elaborate and/or add suggestion, pr is open

**Comment by wilsonge** [comment]
Done and thanks :)

**Pull request merged**
