### PR TITLE
Clarify message for old language packs

### PR DESCRIPTION
**Pull request by brianteeman**
It is unclear the consequence of using an old language pack
### Before

Language pack does not match this Joomla! version. Some strings may be missing.
### After

Language pack does not match this Joomla! version. Some strings may be missing and will be displayed in English.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11957">issues.joomla.org/joomla-cms/11957</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11957">issues.joomla.org/joomla-cms/11957</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11957">issues.joomla.org/joomla-cms/11957</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
