### PR TITLE
Remove unused description tag

### PR DESCRIPTION
**Pull request by Bakual**
This removes the description tag from the language xml file in the installaton folder.
That tag isn't used at all in the installation and currently an empty tag. Thus it can be removed safely.

### CODE REVIEW

**Comment by infograf768** [comment]
I suggest to mass change this for ALL installation languages.

Can be merged on review.

**Comment by Bakual** [comment]
Good point, will do later for the other languages as well.

**Comment by Bakual** [comment]
@infograf768 Done :smile:

**Comment by infograf768** [comment]
RTC

**Pull request merged**
