### PR TITLE
Fix for #7695 - close unclosed div tag in DOB field layout

### PR DESCRIPTION
**Pull request by Fedik**
Here is try to fix issue #7695

For test look in to  #7695
also please make sure that this fix do not break the issue fixed in #7340 :wink:

### CODE REVIEW

**Comment by infograf768** [comment]
This works here in Isis: tested in front and back-end when Two Factor Authentication is enabled.
Dob displays only once in Contact page Profile Tab in front-end.

NOTE: in Hathor, before or after this patch we do have a weird display for the DOB field. I.e. even when closing the User Profile slider, the dob displays.
screen shot 2015-08-16 at 18 20 23

**Comment by Fedik** [comment]
hm, right in Hathor the dob field looks really broken, even without this patch

**Comment by Fedik** [comment]
@infograf768 please try again with Hathor

**Comment by infograf768** [comment]
Pretty good. :+1:

**Comment by zero-24** [comment]
Works as expected. Thanks @Fedik !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7698">issues.joomla.org/joomla-cms/7698</a>.</sub>

**Pull request merged**
