### PR TITLE
[4.0] update sites [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Same issue as with #29902

Ensures that there is only one label and that it is correctly named

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on db86a06566792f420e50494fa932dc926bab7a79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29912">issues.joomla.org/tracker/joomla-cms/29912</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on db86a06566792f420e50494fa932dc926bab7a79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29912">issues.joomla.org/tracker/joomla-cms/29912</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29912">issues.joomla.org/tracker/joomla-cms/29912</a>.</sub>

**Comment by richard67** [comment]
@brianteeman I've solved the conflict for you which came from #29975 .

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
