### PR TITLE
[4.0] readmore structured data

### PR DESCRIPTION
**Pull request by brianteeman**
The itemprop for the intro image that is NOT also a link is obviously incorrect.

https://schema.org/docs/search_results.html?q=thumbnail

Code review should be enough

(easier to create a PR than to create an override)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 49f6abdce3fa44f197ab878c63244499e3501850<br /><br />Confirmed. According to the specs, the value of an element with itemprop `thumbnailUrl` is expected to be of type `URL`, and the value of an element with itemprop `thumbnail` is expected to be of type `ImageObject`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32401">issues.joomla.org/tracker/joomla-cms/32401</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 49f6abdce3fa44f197ab878c63244499e3501850<br /><br />Applied patch and tested in real intro image. And followed link to better understand why itemprop should be there at all - mmm. Otherwise, all good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32401">issues.joomla.org/tracker/joomla-cms/32401</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32401">issues.joomla.org/tracker/joomla-cms/32401</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
