### PR TITLE
[4.0] Use setLimit() to set query limit

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Limit and offset arguments of `Joomla\Database\DatabaseInterface::setQuery()` are deprecated. Use `Joomla\Database\Query\LimitableInterface::setLimit()` instead.

### Testing Instructions

Code review?

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Code review looks good regarding your changes, i.e. I've checked every single change is correct. But it seems you've missed one:

[https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_finder/Indexer/Adapter.php#L584](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_finder/Indexer/Adapter.php#L584)

Or am I wrong?

**Comment by SharkyKZ** [comment]
Thanks. Added that too.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8c4beabb77cd766838cc9d0dced00065eed93958<br /><br />1. Code review

Checked that every change made by this PR is correct.

Checked that this PR covers all calls to `Joomla\Database\DatabaseInterface::setQuery()` with deprecated arguments `limit` or `offset` or both in soures which belong to the CMS, i.e. not to external libraries.

2. Functional test

Applied the PR and navigated a bit in backend and used a few functions, e.g. indexed com finder, and verified that nothing broken and nothing logged to PHP error log.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25981">issues.joomla.org/tracker/joomla-cms/25981</a>.</sub>

**Comment by richard67** [comment]
@Quy Could you test, too? I ask because you are an excellent reviewer.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c4beabb77cd766838cc9d0dced00065eed93958<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25981">issues.joomla.org/tracker/joomla-cms/25981</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25981">issues.joomla.org/tracker/joomla-cms/25981</a>.</sub>

**Comment by HLeithner** [comment]
@SharkyKZ can you fix the merge conflict?

**Comment by SharkyKZ** [comment]
Conflicts fixed.

**Comment by HLeithner** [comment]
Thanks for setting the limit.

**Pull request merged**
