### PR TITLE
Radio buttons are not styled when showing forms in modals

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #26774.

### Summary of Changes

Added template.js to component.php in Protostar.

### Testing Instructions

Open a form containing radio buttons inside a modal while using Protostar.
(Sorry, I have noticed while testing a commercial extension, therefore I have no example to provide).

What you could try:

- Create a contact mail custom field of radio type.

- Create a menu item of type 'List contacts in a category'.

- Create an override of the com_contacts component (category view).

- Modify the link to the contact items in the default_items.php override to force the modals (just for test purposes):

JRoute::_(ContactHelperRoute::getContactRoute($item->slug, $item->catid)).'&tmpl=component'
In the frontend, this will open the contacts into component.php rather than index.php.

### Expected result

The radio buttons are styled.

### Actual result

The radio buttons are not styled.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 8abae6e9847f13d704ee962e5238affbbddc56f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26775">issues.joomla.org/tracker/joomla-cms/26775</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8abae6e9847f13d704ee962e5238affbbddc56f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26775">issues.joomla.org/tracker/joomla-cms/26775</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26775">issues.joomla.org/tracker/joomla-cms/26775</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
