### PR TITLE
[4.0] Added password strength checker and viewer

### PR DESCRIPTION
**Pull request by Arpit-24**
Pull Request for Issue # .

### Summary of Changes

Added javascript that checks for password strength and displays it to the user.

Pretty basic checking with special characters, lowercase and uppercase letters and numbers.

Could use a better checking process like that of dropbox's [zxcvbn](https://github.com/dropbox/zxcvbn) project.

### Testing Instructions

Visit home page
Create an account
Type in some password

### Expected result

Screenshot (1266)
Screenshot (1267)

### CODE REVIEW

**Comment by brianteeman** [comment]
we already have a password strength checker

**Comment by ghost** [comment]
@Arpit-24  yes if you know how to do this better try to solve this #24259 #23283 #23261 
 no one is trying to do these issues

**Comment by Arpit-24** [comment]
> we already have a password strength checker

I just thought a visual feedback while typing the password would be a good choice, as most nowadays have it. Will try to integrate the visual feedback with the existing strength checker

**Comment by Arpit-24** [comment]
> @Arpit-24 yes if you know how to do this better try to solve this #24259 #23283 #23261
> no one is trying to do these issues

Sure, will try to fix them ASAP

**Comment by brianteeman** [comment]
yes it is a good idea. that is why it already exists!!

pass

**Comment by Arpit-24** [comment]
Sorry, didn't notice this.

**Pull request closed without merging**
