### PR TITLE
[com_finder] review config global default options

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR intends to normalize config global default options in com_finder.

The method used was:
1. Review cs of the config.xml file - also add missing default values
2. Check the current params in installation joomla.sql mysql
3. Add missing defaults to install sql

### Testing Instructions

0. Code review
1. Apply patch and https://github.com/joomla/joomla-cms/pull/12916 patch (if not merged yet)
2. Delete configuration.php
3. Install Joomla (no sample)
4. Create a menu item of "Smart Search" type and check all "Use Global"have the global value.

### Documentation Changes Required

None.

### Added/changed defaults in the xml

changed: none

added:
- opensearch_name, opensearch_description: *empty*

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 66363b9c6739edd258ed852fd413968edac75d70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12973">issues.joomla.org/tracker/joomla-cms/12973</a>.</sub>

**Comment by brianteeman** [comment]
Still got some missing global values
screen shot 2016-12-05 at 06 47 58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12973">issues.joomla.org/tracker/joomla-cms/12973</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman IIRC those 3 don't have a global value in com_finder, so you can't use global. don't have any idea where the use global is fetched (if it's fetched from somewhere)

**Comment by brianteeman** [comment]
If they dont have a global value then why do they have a use global setting? Is that another bug?

**Comment by andrepereiradasilva** [comment]
probably .. no time to investigate now what value is read in php

**Comment by andrepereiradasilva** [comment]
> If they dont have a global value then why do they have a use global setting? Is that another bug?

didn't find any references to that in com_finder ( except the xml - https://github.com/joomla/joomla-cms/blob/staging/components/com_finder/views/search/tmpl/default.xml#L100-L133 ), but in other components those parameters exist and are used.

maybe @chrisdavenport knows if they are used or not, and why they don't have a global value like the others.

anyway this PR cannot fix a global value that seems to not exist...

**Comment by Bakual** [comment]
They don't have the "show_global" feature turned on anyway, so this PR should be tested without those three options.

I'd say it is a copy paste error and those parameter global options should be removed.

**Comment by andrepereiradasilva** [comment]
ok. so ready to test

**Comment by chrisdavenport** [comment]
I think the global values should exist and should be supported in the core layout.  Don't know why they were missed.  But, I agree, fixing that should be a different PR.

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 56d0503756f4249d16cd0b1e55cde51849c32930<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12973">issues.joomla.org/tracker/joomla-cms/12973</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 56d0503756f4249d16cd0b1e55cde51849c32930<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12973">issues.joomla.org/tracker/joomla-cms/12973</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests but Conflicts are to resolve.

**Pull request merged**
