### PR TITLE
MSSQL: use error code instead of SQLSTATE

### PR DESCRIPTION
**Pull request by williamsandy**
Change to use native error code for exceptions instead of the driver specific SQLSTATE value because this value is not always am integer

### CODE REVIEW

**Comment by williamsandy** [comment]
Created this PR for  issue #11280 
SQLSTATE as seen here it is not always a number [MSDN article](https://msdn.microsoft.com/en-us/library/ms714687.aspx.) 

So if you are passing the SQLSTATE value '42S22' for error 'Column not found',  '42S01' for error 'Base table or view not found' or even  'HY000' for 'General error' into RuntimeException for the error code that will be problematic as it is expecting an integer.

**Comment by mbabker** [comment]
Based on the [PHP documentation](http://php.net/manual/en/function.sqlsrv-errors.php) this looks fine to me.  Don't have a Windows box to test this against though.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />I could reproduce the problem described in #11280 and this patch resolves it. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11860">issues.joomla.org/joomla-cms/11860</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />on code review + for documentation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11860">issues.joomla.org/joomla-cms/11860</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11860">issues.joomla.org/joomla-cms/11860</a>.</sub>

**Pull request merged**
