### PR TITLE
RFC: Change to Datepicker / Calendar Fields

### PR DESCRIPTION
**Pull request by purplebeanie**
I'm a little nervous to fire off this PR as it turned out to to be a lot more complicated than I first thought.... But here goes.

This PR will need more work before it is ready but I wanted to get some feedback from others on the approach I have taken with the languages and the best way to demonstrate was with code.  I have put some discussion questions at the end which was where I was seeking most feedback.
## The problem I'm trying to solve
- The current Joomla calendar picker is quite old, and based on feedback from an earlier question to the devcms list does not natively have support for non-Gregorian calendars. 
- The current Joomla calendar picker has a fairly weak time picker that is not enabled, and currently cannot be turned on without changing the calendar behaviour.
## The calendar I have used

A user on the CMS list (Elvis) turned up the Keith Woods calendar picker from here (http://keith-wood.name/calendarsPicker.html).  This is a modern, maintained calendar picker that includes:
- Support for RTL
- Support for non-Gregorian calendars
- Extensive localisation already done out of the box
- A good underlying calendaring JS library to allow conversions from one calendar to another
## The approach I have taken

After feedback from @Bakual I have included ALL calendars and localisation files as part of the base PR. The relevant language and localisation file is then loaded based on the language.

This PR introduces a new attribute to the Calendar form field XML caltype.  This is set to one of the calendar types that the Keith Wood jQuery calendar plugin has support for.  See the files in `/media/calendar/js` for complete listing.  By default these are named jquery-calendars.persian.js etc. 

If no caltype is specified a Gregorian calendar will be used.

Presently if using a calendar type other than Gregorian the conversion is done on the client side and the dates converted.  I found doing some conversion on the server and some on the client resulted in drift due to the Browser time zone.  Conversion needs to be done either all on the server, or all on the client.  The reason for choosing client meant that the changes could all be contained within the JS injected by the Calendar behaviour.
## To test

Install this PR and go to a content item.  

Focus on or click the button beside a calendar field and the new calendar picker will popup.  This is the redmond theme which seemed the closest match for the present Joomla admin.  There are a few css fixes in `/media/calendars/css/joomla-css-fixes.css`

keith-picker-1

To use with a different language install the relevant Joomla language pack and login using the desired language.  The calendar will load the correct localisation pack based on the language. These are from the calendar picker widget so may not be the same as the calendar strings defined in the Joomla language file.

To use with a different calendar open the form xml and add a `caltype="persian"` to the form attribute. For example if using a content article from administratator open `administrator/components/com_content/models/forms/article.xml` and for arguments sake set the created field to:

`<field name="created" type="calendar" label="COM_CONTENT_FIELD_CREATED_LABEL"
            description="COM_CONTENT_FIELD_CREATED_DESC" size="22"
            format="%Y-%m-%d %H:%M:%S" filter="user_utc" caltype="persian" />
`

**A note for testing *\* when loading the JS files using JHtml::_('script') I have used the / instead of the DIRECTORY_SEPERATOR constant.  Is this okay or will this cause breaks? I also test for a file path using `if (!file_exists(JPATH_BASE.'/media/calendars/js/jquery-calendars-'. $langTag .'.js'))` again is this okay? or will they break on Windows?**
## Discussion Questions
- Presently the calendar is swapped per field based on using the caltype attribute in the form XML.  Is this the best way? 
- Is there a reason why a user would want to have several different calendar types in a form or should I swap this based on the user language as well?
- Is it safe to define a calendar based on language type? Would a Persian user for example want to use a Gregorian calendar?
- Is client side JS the best place to do conversion to / from Gregorian and chosen calendar?

### CODE REVIEW

**Comment by Hackwar** [comment]
Regardless of how this is implemented further, could you please look at the results of travis and fix those? Start by pulling in the latest changes to staging and then work your way from there on up.

**Comment by roland-d** [comment]
Hello @purplebeanie 

Thank you for your contribution.

The last comment here was on 3rd February. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4203">issues.joomla.org/joomla-cms/4203</a>.</sub>

**Comment by digitalgarage** [comment]
Hey @roland-d and @Hackwar .... It sort of fell in a hole for a while.  I changed github accounts and then got slammed with study and work commitments.

The goal was to swap out the old dhtml datetime picker -- the current Joomla calendar picker -- to something more modern that still had support for all the different calendars that Joomla needs to support.

So yes, I will refresh this and do some work to make Travis happy.  I should have some time free week after next to get onto this one.

It's up to you folks if you'd prefer to close this PR and I can re-open another one when I've had a chance to fix it up? 

Eric.

**Comment by roland-d** [comment]
Hey Eric,
Thank you for the follow-up. I am happy to leave this open longer, a few more weeks won't matter. Looking forward to your changes.

**Comment by purplebeanie** [comment]
Hey Folks,

I am closing this PR.  After reviewing over the weekend it needs a little more TLC than I've got time to give until after college ends for the year (13th November).

I will work on it again then and re-open the PR then based on whatever is current at mid November.

Cheers,
Eric.

**Pull request closed without merging**
