### PR TITLE
Fix for menu items containing nested field groups and no immediate fields in request

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25211.

### Summary of Changes

Get `request` group fields recursively.

### Testing Instructions

Create/modify view layout XML file to contain a nested field group but no immediate fields in `request` field group, e.g.:

```
<fields name="request">
	<fieldset name="request">
		<fields name="filter">
			<field
				name="id"
				type="category"
				label="JGLOBAL_FIELD_CATEGORIES_CHOOSE_CATEGORY_LABEL"
				description="JGLOBAL_FIELD_CATEGORIES_CHOOSE_CATEGORY_DESC"
				extension="com_content"
				show_root="true"
				required="true"
			/>
		</fields>
	</fieldset>
</fields>
```
Create a menu item for the view.
Inspect `Link`  field value.
### Expected result

Nested group field parameters included, e.g.:

    index.php?option=com_content&view=categories&filter[id]=0

### Actual result

Nested group field parameters not included, e.g.:

    index.php?option=com_content&view=categories

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by muesliflyer** [comment]
This works for me. Thanks for the quick fix.

**Comment by ghost** [comment]
@muesliflyer  please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by muesliflyer** [comment]
I have tested this item :white_check_mark: successfully on 914b2c810fc3c621e828d082c4bd7608644ff7c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25213">issues.joomla.org/tracker/joomla-cms/25213</a>.</sub>

**Comment by muesliflyer** [comment]
For the test, I installed Patch Tester 2.0.1 (the stable version). When fetching the patch data, I got an error:

`Notice: Undefined offset: 0 in /var/www/bugtesting/libraries/joomla/database/query.php on line 351
{"success":false,"message":"Error inserting pull request data into the database: Column count doesn't match value count at row 1","messages":null,"data":null}`

Then I installed the latest version 3.0.0 beta 4. Then it worked.

**Comment by infograf768** [comment]
> Then I installed the latest version 3.0.0 beta 4. Then it worked.

??

**Comment by SharkyKZ** [comment]
@infograf768 it's about Patchtester.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5bba89ddf68d988ddcdc7a370bf268ea603fc736<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25213">issues.joomla.org/tracker/joomla-cms/25213</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
