### PR TITLE
Create apcu-7.2.ini

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue Travis PHP 7.2 errors due to missing file .

### Summary of Changes
- Create apcu-7.2.ini

### Testing Instructions
code review

### Expected result
Travis PHP 7.2 does not error for missing apcu-7.2.ini file

### Actual result
Travis PHP 7.2 does not error for missing apcu-7.2.ini file

### Documentation Changes Required
none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9867ca9d9dc526730a625959dfec03fabe057283<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19366">issues.joomla.org/tracker/joomla-cms/19366</a>.</sub>

**Comment by brianteeman** [comment]
I assume this can be RTC on review as the tests pass

**Comment by zero-24** [comment]
Merged thanks.

**Comment by photodude** [comment]
You are welcome

**Comment by photodude** [comment]
@wilsonge This will also fix the PHP 7.2 errors on Travis in J 4.0.

**Pull request merged**
