### PR TITLE
[4.2] Fix wrong data for calendar custom fields when user registration fail

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #39844

### Summary of Changes
Currently, if you use Calendar custom fields for user registration, if registration fail, there could be some issues with data of Calendar custom fields:
- Time of the selected date could be changed. It happens because the Calendar form field expect to receive input datetime from UTC timezone , but the provided value is from user timezone (filter is not applied yet)
- In some cases like when you use US language package, the Calendar field could not parse the selected date and result in fatal error

To address these issues, we can use same code which we are using on FormController https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/MVC/Controller/FormController.php#L839-L855 : Process filter for Calendar fields, store the filtered data back to request. 

### Testing Instructions
1. Follow instructions at https://github.com/joomla/joomla-cms/issues/39844 and confirm the issue
2. Apply patch, confirm that when registration fail, you do not get fatal error anymore. The date which you selected in the field remains as how it is.

### Actual result BEFORE applying this Pull Request
There is fatal error

### Expected result AFTER applying this Pull Request
No fatal error anymore

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on 0c7530cb7c379135c9d108bb71ad554bdb8120b2<br /><br />Reproduced the error 0 Failed to parse time string (01-30-2023 12:30:22) at position 0 (0): Unexpected character

When the option Default Date was 01-30-2023 12:30:22 and the option Show Time was Yes **and the patch had been applied**, browsing to the registration form at http://joomla4test/component/users/registration?Itemid=101 displayed the error "0 Failed to parse time string (01-30-2023 12:30:22) at position 0 (0): Unexpected character"  
That error was then displayed repeatedly even after Default Date was set to 2023-02-15  and Show Time was set to No, whenever the registration form was loaded.  This error was shown until the custom calendar field was unpublished.

When the same custom calendar field was published, just loading the registration form displayed the same error.

It looks like the request or the session does not get cleared and that is why the time entry stays in the form data.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39863">issues.joomla.org/tracker/joomla-cms/39863</a>.</sub>

**Comment by joomdonation** [comment]
The issue with default data is a different issue with our Calendar Form Field. For the default value you entered, it is the format could not be parsed by PHP DateTime class. I guess that's the reason in description of the field, it says:


> This is the default date. The value can be an ISO 8601 format (YYYY-MM-DD HH:MM:SS) or NOW, which displays the actual date.

So you need to enter default value for the custom field in that format.

**Comment by toivo** [comment]
The behaviour of the form gets quite murky, if I may say so. In a new test the Default Date is in the correct ISO date format and the patch is applied, the form returns the error message about an existing user and the selected date is in the correct US format.  The form is cancelled and the browser is closed.  The Chrome browser cache in History is cleared.  A new tab is opened and the registration form is loaded.  Now the custom date field shows the date selected from the Calendar button, not the Default Date.  Strange, it should not behave like this.

The I open the test site in Edge and go to the registration form.  The Default Date is displayed.

 Thank you for your assistance! It is past midnight and I will continue tomorrow. It would be good to keep our US webmasters happy.  Maybe some documentation improvements or a Help page sritten by an expert could clarify the use of custom calendar fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39863">issues.joomla.org/tracker/joomla-cms/39863</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0c7530cb7c379135c9d108bb71ad554bdb8120b2<br /><br />Tested successfully in Joomla 4.2.8-dev of 15 February using PHP 8.1.10.
Default Date 2022-12-31
Show Time: No
After the error message about the existing user the custom calendar field displayed the date selected earlier though the Calendar button in the correct US format.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39863">issues.joomla.org/tracker/joomla-cms/39863</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0c7530cb7c379135c9d108bb71ad554bdb8120b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39863">issues.joomla.org/tracker/joomla-cms/39863</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39863">issues.joomla.org/tracker/joomla-cms/39863</a>.</sub>

**Comment by fancyFranci** [comment]
I really appreciate how much bugs you are fixing! Thank you :)

**Pull request merged**
