### PR TITLE
[4.0] Nested Bootstrap tabs

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #20627.

### Summary of Changes

Fixes nested Bootstrap tabs

### Testing Instructions

Create a nested Bootstrap tab set:

```
echo JHtml::_('bootstrap.startTabSet', 'outerTab', array('active' => 'x1'));

echo JHtml::_('bootstrap.addTab', 'outerTab', 'x1', 'x1');
echo 'Outer Tab 1';
echo JHtml::_('bootstrap.endTab');

echo JHtml::_('bootstrap.addTab', 'outerTab', 'x2', 'x2');
echo 'Outer Tab 2';

// Nested tabset
echo JHtml::_('bootstrap.startTabSet', 'innerTab', array('active' => 'y1'));

echo JHtml::_('bootstrap.addTab', 'innerTab', 'y1', 'y1');
echo 'Inner Tab 1';
echo JHtml::_('bootstrap.endTab');

echo JHtml::_('bootstrap.addTab', 'innerTab', 'y2', 'y2');
echo 'Inner Tab 2';
echo JHtml::_('bootstrap.endTab');

echo JHtml::_('bootstrap.endTabSet');
// End of nested tabset

echo JHtml::_('bootstrap.endTab');
echo JHtml::_('bootstrap.endTabSet');
```

### Expected result
Tabs working normally:

### Actual result
Nested tabs shown along with top most level tabs:

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by manojLondhe** [comment]
I have tested this item :red_circle: unsuccessfully on ff97a1f92671d65fe8bbd066fc2c5f153b7b48f7<br /><br />This is what I see after applying this patch
screen shot 2019-07-04 at 12 58 07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25420">issues.joomla.org/tracker/joomla-cms/25420</a>.</sub>

**Comment by manojLondhe** [comment]
I have tested this item :white_check_mark: successfully on ff97a1f92671d65fe8bbd066fc2c5f153b7b48f7<br /><br />Sorry! My bad.

Working after ```npm install``` (rebuilding JS files)

screen shot 2019-07-04 at 13 07 22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25420">issues.joomla.org/tracker/joomla-cms/25420</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ff97a1f92671d65fe8bbd066fc2c5f153b7b48f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25420">issues.joomla.org/tracker/joomla-cms/25420</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25420">issues.joomla.org/tracker/joomla-cms/25420</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
