### PR TITLE
FeaturedButton fix

### PR DESCRIPTION
**Pull request by Denitz**
# Summary of Changes

`FeaturedButton` has hard-coded task prefix `articles.` and uses COM_CONTENT-related tip strings.

It should work similarly to `PublishedButton`.

### Testing Instructions

Create your own FeaturedButton button with own `task_prefix` option.

Apply patch, ensure that feature/unfeature buttons work in backend articles.

### Actual result BEFORE applying this Pull Request

See that `articles.` still exist in button HTML.

### Expected result AFTER applying this Pull Request

Valid task name in custom button

Ensure that feature/unfeature buttons work in backend articles.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 616539da30dcb5303cdb7586c289240b7e09807f<br /><br />Not sure exactly how best to create my own FeaturedButton. I just duplicated the few button lines in com_content/tmpl/articles/default.php and changed the task prefix. With the two buttons side by side the correct button worked normally to feature/unfeature an article.

An aside: I noticed that the Featured button in com_content has a different tooltip from that in com_contacs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31322">issues.joomla.org/tracker/joomla-cms/31322</a>.</sub>

**Comment by Denitz** [comment]
The button code makes custom tooltip option really complex, it's easier and completely enough to have the common tooltip title which will satisfy all components (JFEATURED/JUNFEATURED)

**Comment by Quy** [comment]
Go to Content > Featured Articles
Clicking the Featured icon does not toggle to Unfeatured.

**Comment by Denitz** [comment]
@Quy Fixed in featured articles view as well. Checked all `FeaturedButton` usages, there are only two - both have the `task_prefix` option now.

**Comment by ceford** [comment]
The Featured Articles Feature button does Unfeature the article. But neither Featured nor Status buttons do anything when Workflows are enabled. That makes me suspect something is wrong. I guess that is a separate issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31322">issues.joomla.org/tracker/joomla-cms/31322</a>.</sub>

**Comment by Denitz** [comment]
@ceford Yes, separate, it looks like Feature and State columns should be not displayed if Workflows are enabled because all state-related and feature-related changes are only possible with a drop-down in Stages column.

**Comment by wilsonge** [comment]
Nice spot. Thanks!

**Pull request merged**
