### PR TITLE
Fix invalid markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
The post-installation message is wrapped in a `<p>` element. When the message has block elements, it generates invalid HTML markup.

### Testing Instructions
Go to Components > Post-installation Messages
View page source
Find:
```

				<p class="small">
					Since version 3.5.0				</p>
				<p><p>Since Joomla! 3.5 a statistics plugin will submit anonymous data to the Joomla Project. This will only submit the Joomla version, PHP version, database engine and version, and server operating system.</p><p>This data is collected to ensure that future versions of Joomla can take advantage of the latest database and PHP features without affecting significant numbers of users. The need for this became clear when a minimum of PHP 5.3.10 was required when Joomla! 3.3 implemented the more secure Bcrypt passwords.</p><p>In the interest of full transparency and to help developers <a href="https://developer.joomla.org/about/stats.html">this data is publicly available.</a> An API and graphs will show the Joomla version, PHP versions and database engines in use.<br><br>If you do not wish to provide the Joomla Project with this information you can disable the plugin called System - Joomla Statistics.</p></p>
				<div>
															<a href="index.php?option=com_postinstall&amp;view=message&amp;task=unpublish&amp;id=3&amp;bb8fbd385e4c3cce23b936c5fa28591d=1" class="btn btn-inverse btn-small">
						Hide this message					</a>
									</div>
```

### Expected result
```
				<p class="small">
					Since version 3.5.0				</p>
				<div>
					<p>Since Joomla! 3.5 a statistics plugin will submit anonymous data to the Joomla Project. This will only submit the Joomla version, PHP version, database engine and version, and server operating system.</p><p>This data is collected to ensure that future versions of Joomla can take advantage of the latest database and PHP features without affecting significant numbers of users. The need for this became clear when a minimum of PHP 5.3.10 was required when Joomla! 3.3 implemented the more secure Bcrypt passwords.</p><p>In the interest of full transparency and to help developers <a href="https://developer.joomla.org/about/stats.html">this data is publicly available.</a> An API and graphs will show the Joomla version, PHP versions and database engines in use.</p><p>If you do not wish to provide the Joomla Project with this information you can disable the plugin called System - Joomla Statistics.</p>															<a href="index.php?option=com_postinstall&amp;view=message&amp;task=unpublish&amp;id=3&amp;bb8fbd385e4c3cce23b936c5fa28591d=1" class="btn btn-inverse btn-small">
						Hide this message					</a>
									</div>
```

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c1833e4dc8c96d8c79d82cda592577a98a821b9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14817">issues.joomla.org/tracker/joomla-cms/14817</a>.</sub>

**Comment by brianteeman** [comment]
Pretty sure this is not the correct fix although you do correctly identify an issue 

The issue you identified is coming the language string COM_CPANEL_WELCOME_BEGINNERS_MESSAGE

`COM_CPANEL_WELCOME_BEGINNERS_MESSAGE="<p>Community resources are available for new users</p><ul><li><a href="_QQ_"https://docs.joomla.org/Portal:Beginners"_QQ_">Joomla! Beginners Guide</a></li><li><a href="_QQ_"https://forum.joomla.org/viewforum.php?f=706"_QQ_">New to Joomla! Forum</a></li></ul>"`

@C-Lodder any thoughts?

**Comment by Quy** [comment]
There is also the `<ul>` element which would make it invalid inside the `<p>` element.

**Comment by brianteeman** [comment]
We really must stop putting markup inside strings :(

**Comment by C-Lodder** [comment]
There's no point in using a `<div>` tag. Both `<div>` and `<p>` are block elements, and neither need to be wrapped in one another.

So replace:

```
<div><?php echo JText::_($item->description_key); ?></div>
```

with:

```
<?php echo JText::_($item->description_key); ?>
```

or there is an opening `<div>` just below, so it could go inside there. Take your pick.

**Comment by brianteeman** [comment]
That won't work as now you have other messages without any block element

**Comment by C-Lodder** [comment]
You're telling some language packs have translated this without the HTML markup?

**Comment by brianteeman** [comment]
That is possible but no thats not what I meant. If you look at the other post installation messages you will see that they are not wrapped in a block element so this change to remove the enclosing element from the code will cause invalid markup elsewhere. The problem is using markup in this string. Not in the code this PR edits

COM_CPANEL_MSG_ROBOTS_BODY="A change to the default robots.txt files was made in Joomla! 3.3 to allow Google to access templates and media files by default to improve SEO. This change is not applied automatically on upgrades and users are recommended to review the changes in the robots.txt.dist file and implement these changes in their own robots.txt file."
COM_CPANEL_MSG_STATS_COLLECTION_BODY="Since Joomla! 3.5 a statistics plugin will submit anonymous data to the Joomla Project. This will only submit the Joomla version, PHP version, database engine and version, and server operating system.<br><br>This data is collected to ensure that future versions of Joomla can take advantage of the latest database and PHP features without affecting significant numbers of users. The need for this became clear when a minimum of PHP 5.3.10 was required when Joomla! 3.3 implemented the more secure Bcrypt passwords.<br><br>In the interest of full transparency and to help developers <a href="_QQ_"https://developer.joomla.org/about/stats.html"_QQ_">this data is publicly available.</a> An API and graphs will show the Joomla version, PHP versions and database engines in use.<br><br>If you do no

**Comment by C-Lodder** [comment]
Hmm ok. Well you an wrap it in the `<div>` but they don't have any default styling unlike `<p>`, so as a temporary fix, you may want to add a class to the `<div>` and styling the text appropriately.

Or remove the HTML markup from the language string

Or go a dirty route and use PHP to remove the `<p>` tags from the language string if they exist.

Personally I'd prefer option 2, but not sure if editing the language string  like that will be allowed for a minor release.

**Comment by brianteeman** [comment]
We can change the string to remove the p and to replace the li with br - then it will validate etc

thats not a problem to do. Translators will moan that its a useless change but cant do anything about that.

**Comment by C-Lodder** [comment]
ah fair enough.

@Quy - could you do that please?

**Comment by Quy** [comment]
So replace the unordered list with line breaks? Should each list item be prefixed `*` or `-` or nothing?

**Comment by brianteeman** [comment]
Your choice. See what looks best

**Comment by Quy** [comment]
In the 1st message, it uses `<br>`. In the `Two Factor...` message, it uses `<br />`. Is there a preference on which format?

**Comment by C-Lodder** [comment]
Please use `<br>`. I've already remove ALL void tags on Joomla 4 and I don't want anymore going in when it gets merged :)

**Comment by brianteeman** [comment]
Pretty sure that it should be without / as it should be html5

**Comment by C-Lodder** [comment]
Yup, but half of J3 is still XHTML

**Comment by Quy** [comment]
@brianteeman @C-Lodder Thanks for the tips. Ready for testing.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8702edb3e12137a5e5a238af1f6d4ddad8a00ada<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14817">issues.joomla.org/tracker/joomla-cms/14817</a>.</sub>

**Comment by andrepereiradasilva** [comment]
IMHO each post install message should be wrapped inside a `div`, not a `p` that way you could have block level HTML tags inside a post install message (ul, ol, table, h[1-6], etc) - is more flexible that way.
Notice the same logic applies to the message container. Example:
```html
<div class="alert-message">Database table structure is up to date.</div>
```

**Comment by Quy** [comment]
@andrepereiradasilva See this `[comment](https://github.com/joomla/joomla-cms/pull/14817#issuecomment-287906372)`

**Comment by andrepereiradasilva** [comment]
@Quy i saw it but don't agree :smile:

**Comment by Quy** [comment]
I agree with you too. I noticed the following in that comment so I will rework it later today.

> or there is an opening <div> just below, so it could go inside there. Take your pick.

**Comment by Quy** [comment]
Ready to be tested. Thanks.

**Comment by franz-wohlkoenig** [comment]
@Quy can you please update Test Instructions in first Comment?

**Comment by Quy** [comment]
Instructions are the same except the markup is different.

**Comment by korneliusz401** [comment]
I have tested this item :white_check_mark: successfully on f05b6f847abda697913a632d8c290fe910bf1203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14817">issues.joomla.org/tracker/joomla-cms/14817</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f05b6f847abda697913a632d8c290fe910bf1203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14817">issues.joomla.org/tracker/joomla-cms/14817</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
