### PR TITLE
[4.2] Allow typing in media field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # . Replaces #36945

### Summary of Changes

- Removes the readonly attribute from the input of Media Field so users could type freely
- It doesn't fix the preview for EXTERNAL urls (out of scope)

### Testing Instructions
- Create a new article and add some title
- go to the images tab
- type (or copy paste) `images/sampledata/cassiopeia/not-valid.jpg`
- save the form
- type (or copy paste) `images/sampledata/cassiopeia/nasa1-400.jpg`
- Save the form (observe that the image url has the `#` parts!!!!)
- type (or copy paste) `/images/sampledata/cassiopeia/nasa1-400.jpg`
- save the form (observe the URL)
- type (or copy paste)  any valid external URL
- save the form 

Screenshot 2022-04-25 at 16 31 44

Screenshot 2022-04-25 at 16 32 11

Screenshot 2022-04-25 at 16 32 22

### CODE REVIEW

**Comment by coolcat-creations** [comment]
@dgrammatiko I tested the patch and typing is possible but it does not update the preview after typing in / pasting the desired path

+ the # are not added - should they be added with the patch? I am testing on localhost with the patchtester

**Comment by dgrammatiko** [comment]
did you read the description? Also what is the url you're entering?

> I am testing on localhost with the patchtester

Yeah that won't work, try d/l the package at the end of this PR (GitHub)

**Comment by coolcat-creations** [comment]
Yes I read the description - maybe I misunderstood them or the issue is because i used patchtester. I will try with the prebuild package then. Thank you

**Comment by coolcat-creations** [comment]
I installed now the prebuilt package and it works **mostly** like expected.
Only mostly because I succeeded to break it like that, that now the not valid message appears despite I chosed an image in the modal. (Also after hitting save)

grafik

**Comment by dgrammatiko** [comment]
@coolcat-creations should be fine now

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 048f0337c7fd297fcfa7cca26b02256a79e98758<br /><br />
    type (or copy paste) images/sampledata/cassiopeia/not-valid.jpg - done works (Validation message displayed)

    type (or copy paste) images/sampledata/cassiopeia/nasa1-400.jpg - done works (#parts added)

    type (or copy paste) /images/sampledata/cassiopeia/nasa1-400.jpg - done works (#parts added)

    type (or copy paste) any valid external URL - done and works (image previewed, no # parts added as expected)

Thank you very much!!!

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37654">issues.joomla.org/tracker/joomla-cms/37654</a>.</sub>

**Comment by richard67** [comment]
@coolcat-creations Could you test this PR again? It has received some changes after your last test. Thanks in advance.

**Comment by RickR2H** [comment]
@dgrammatiko Thanks for looking into this. Much appreciated! 

I noticed that when I select the image via the select button I get: images/joomla_black.png#joomlaImage://local-images/joomla_black.png?width=225&height=50 But when I paste the URL like this: images/joomla_black.png I get the URL images/joomla_black.png#joomlaImage://local-images/joomla_black.png?width=225&height=225

Ik looks like when pasting the URL the exact image width and height are not respected and the image is default defined as squared.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37654">issues.joomla.org/tracker/joomla-cms/37654</a>.</sub>

**Comment by dgrammatiko** [comment]
> Ik looks like when pasting the URL the exact image width and height are not respected and the image is default defined as squared

The wrong variable was passed fro the height, it should be ok after https://github.com/joomla/joomla-cms/pull/37654/commits/cf77958bd80bd05d36a926d2cf1d16b180bb44ed

**Comment by coolcat-creations** [comment]
Good catch! did not see this. I will test now as well ... waiting for the new prebuilt package :)

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on cf77958bd80bd05d36a926d2cf1d16b180bb44ed<br /><br />Thanks @dgrammatiko <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37654">issues.joomla.org/tracker/joomla-cms/37654</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on cf77958bd80bd05d36a926d2cf1d16b180bb44ed<br /><br />Thank you, tested successful as the given testing instructions.

The Preview seems not to work for svg tough but I think thats another issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37654">issues.joomla.org/tracker/joomla-cms/37654</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37654">issues.joomla.org/tracker/joomla-cms/37654</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
