### PR TITLE
Fix caching of the script options

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #20903 .

### Summary of Changes
This patch fixes a Cache for ScriptOptions, and Language strings (JavaScript).

### Testing Instructions

Need to test Component and Module caching
(I assume you have installed Joomla! with default testing content.)

Edit `components/com_content/views/article/tmpl/default.php`, add there:
```php
JFactory::getDocument()->addScriptOptions('foo', array('bar' => 'beer 🍻'));
JText::script('JGLOBAL_AUTH_ACCESS_GRANTED');

JFactory::getDocument()
	->addScriptDeclaration('console.log(Joomla.getOptions("foo", "That a fail!"));console.log(Joomla.JText._("JGLOBAL_AUTH_ACCESS_GRANTED", "That a fail!"));');
```
Then edit mod_custom `/modules/mod_custom/tmpl/default.php`, add there:
```php
JFactory::getDocument()->addScriptOptions('bar', array('foo' => 'panda 🐼'));
JText::script('JGLOBAL_AUTH_CANCEL');

JFactory::getDocument()
	->addScriptDeclaration('console.log(Joomla.getOptions("bar", "That a fail!"));console.log(Joomla.JText._("JGLOBAL_AUTH_CANCEL", "That a fail!"));');
```

Then enable Caching, and open a page with a Custom module view (in testing data it `/custom` url).
Open Browser developer console.
Clear Joomla cache!.

Back to opened page, and do 2 reload of the page (push F5, usually).
1 refresh will display the page without cache
2 refresh will display a cached page

### Expected result

In browser console, after each refresh you should see a messages, like on this screen (order can be diferent):

screen 2018-07-07 09 51 07 190x90

### Actual result

In browser console you can see these message only after first refresh, after second (and further page reload) you will see message `That a fail!`

### Documentation Changes Required

no

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by Quy** [comment]
Is issue #20546 related?

**Comment by Fedik** [comment]
@Quy yeap, that is the same issue

**Comment by Ruud68** [comment]
I have tested this item :white_check_mark: successfully on 341a5dc400a76c819e99d3a2df8da1e4176e1ad6<br /><br />also fixes this wrong behavior in (content) plugins using addScriptOptions https://github.com/joomla/joomla-cms/issues/26975<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21007">issues.joomla.org/tracker/joomla-cms/21007</a>.</sub>

**Comment by uglyeoin** [comment]
Can I fetch this in Patch Tester or not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21007">issues.joomla.org/tracker/joomla-cms/21007</a>.</sub>

**Comment by uglyeoin** [comment]
Perhaps I have got this wrong, but when I test I get "that a fail" with or without the patch.  Initially i do see the array foo, bar, but on second load I do not see it.  Can you provide further instructions please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21007">issues.joomla.org/tracker/joomla-cms/21007</a>.</sub>

**Comment by uglyeoin** [comment]
I have tested this item :white_check_mark: successfully on 341a5dc400a76c819e99d3a2df8da1e4176e1ad6<br /><br />I have tested this and I see the results as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21007">issues.joomla.org/tracker/joomla-cms/21007</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21007">issues.joomla.org/tracker/joomla-cms/21007</a>.</sub>

**Comment by HLeithner** [comment]
It took some time but finally it's merged thanks for your work.

**Pull request merged**
