### PR TITLE
Check if parse_ini_file is disabled. Fixes #17198

### LINKED ISSUE #17198: Language strings are still not parsed after upgrading to 3.7.3
I am very sorry to report this issue because it is an exact duplicate of #15587

I have waited for 3 upgrades and a few weeks for this issue to be resolved, the contributors made some efforts to solve it so far but indeed nothing has changed for me on my server. I need my hosting company to enable the parse_ini_file function and the site looks normal then. But what about a Joomla beginner? I know the solution and contact my hosting company, which is one of the biggest in Turkey, to make some changes on the server settings. Don't we still have a more stable solution for this ini file parsing issue? 

### Steps to reproduce the issue
Upgrade from 3.6 to 3.7.3

### Expected result
All the backend and frontend language strings to appear as defined in language files

### Actual result
None of the strings are parsed and they look like the screenshot below:
joomla

### System information (as much as possible)

COM_ADMIN_SETTING | COM_ADMIN_VALUE
COM_ADMIN_PHP_BUILT_ON |  
COM_ADMIN_DATABASE_VERSION | 5.6.36-cll-lve
COM_ADMIN_DATABASE_COLLATION | latin1_swedish_ci
COM_ADMIN_DATABASE_CONNECTION_COLLATION | utf8mb4_general_ci
COM_ADMIN_PHP_VERSION | 5.6.31
COM_ADMIN_WEB_SERVER | LiteSpeed
COM_ADMIN_WEBSERVER_TO_PHP_INTERFACE | litespeed
COM_ADMIN_JOOMLA_VERSION | Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
COM_ADMIN_PLATFORM_VERSION | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
COM_ADMIN_USER_AGENT | Mozilla/5.0 (Windows NT 6.3; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

### Additional comments
Please find a stable solution for this issue without having me contacting the hosting company after upgrading each site.

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #17198 .

### Summary of Changes
Fixes a case where `parse_ini_file` was disabled but for some reason `function_exists` returns true

### Testing Instructions
Disable the function `parse_ini_file` using an entry like `disable_functions=apache_child_terminate, apache_setenv, parse_ini_file` (note the spaces after the commas are important)

### Expected result
Joomla Language files load

### Actual result
They don't

### Documentation Changes Required
None

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by zero-24** [comment]
hmm while this may fix this issue but don't we need to implement that kind of thing in all places we use `function_exists` ? https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=function_exists&type= and what happen if ini_get is disabled for some reason? For me this is not a bug on our site it is a bug at the hosting site or PHP not triming the values they get from the php ini.

**Comment by wilsonge** [comment]
OK So I just tested locally and even with spaces after the commas' PHP 7.0 still told me that the function didn't exist. So either this is specific to PHP 5.6 or there's something else going on under the hood.

I agree it's not really a bug in the system. But clearly there's something weird going on that guys site and if this fixes the issue I'm ok fixing it for 2 extra lines of code

Most our other uses are in 3rd party libraries or checking for functions inside of Joomla (like the router functions, which practically aren't going to be disabled :) ). The few places remaining are the caching and the session drivers mainly. If we get bug reports there I guess we can look into it. But I don't see anything else in core that screams to me as needing a similar fix

**Comment by hakanara** [comment]
@wilsonge I don't know how to test a patch like this. I have downloaded a file called: https://codeload.github.com/joomla/joomla-cms/zip/fix-17198.zip and installed this file via Joomla update component. But nothing changed and the language files are still not parsed. Maybe I did something wrong? If not, I will go into the code and try to change it a bit to see if we did something wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17332">issues.joomla.org/tracker/joomla-cms/17332</a>.</sub>

**Comment by wilsonge** [comment]
@hakanara follow the documentation here https://docs.joomla.org/Testing_Joomla!_patches it should take you through step by step :)

**Comment by hakanara** [comment]
@wilsonge I have found an installation directory. Then I started the installation there and everything seems wonderful now. Just give me a couple of minutes to see if I tested it according to the documentation. My first impression is, you've done a great job :-) I will post my test results here.

**Comment by ggppdk** [comment]
The code to trim the 'disable_functions' is already used in installation code, so the trimming issue is not new
https://github.com/joomla/joomla-cms/blob/staging/installation/model/setup.php#L178-L209

But then there is another place that does not do the trimming and needs to be patched ... here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/models/sysinfo.php#L322-L333

I suggest are static method (located inside some API class) to be used everywhere,
please notice that it includes check for function existence too:

```php
static function functionIsDisabled($function)
{
	static $disabled = null;
	$func = strtolower($function);

	if ($disabled === null)
	{
		$disabled_functions = trim(ini_get('disable_functions'));
		$disabled_functions = $disabled_functions ? explode(',', $disabled_functions) : array();

		$disabled = array();
		foreach ($disabled_functions as $key => $value)
		{
			$disabled[trim($value)] = true;
		}

		// PHP 5.3 only
		if (ini_get('safe_mode'))
		{
			$disabled['shell_exec']     = true;
			$disabled['set_time_limit'] = true;
		}
	}

	// Check both disabled and if it exists
	return isset($disabled[$func]) || !function_exists($func);
}
```

**Comment by hakanara** [comment]
I have tested this item :white_check_mark: successfully on 30b3a0a0fb29b2d971026a09f1c3a476ff1324fc<br /><br />I tested the patch in a different way than it is being told in the Joomla documentation but the site and the patch is working. I have two Joomla installations under the same domain with the same php configuration. The one I downloaded from here as a patch is working and parsing the language strings but the other one which is Joomla 3.7.4 is not parsing the strings.

Thank you very much who have contributed to the solution.
Kind regards,
Hakan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17332">issues.joomla.org/tracker/joomla-cms/17332</a>.</sub>

**Comment by hakanara** [comment]
I installed Joomla from zero twice. I set up a database from zero twice. But unfortunately the com_patchtester gives me this error:
The file marked for modification does not exist: libraries/src/Joomla/CMS/Language/Language.php

Therefore I downloaded the fix manually, extracted, installed and now confirm that the fix works like a charm :-) I don't really now why I get this error though. @mbabker ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17332">issues.joomla.org/tracker/joomla-cms/17332</a>.</sub>

**Comment by zero-24** [comment]
You need to install the staging branch and not 3.7.4 ;)

**Comment by hakanara** [comment]
@zero-24 Thank you very much. :-D<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17332">issues.joomla.org/tracker/joomla-cms/17332</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge can you please fix the conflicts? Sounds like this is your new hobby these days ;) Should be a simple one for sure.

**Comment by zero-24** [comment]
Merging this based on @mbabker 's review and @hakanara 's test. Thanks @wilsonge

**Pull request merged**
