### PR TITLE
[5][com_privacy] language file not loaded

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue [#44054](https://github.com/joomla/joomla-cms/issues/44054)

### Summary of Changes
load lang file

### Testing Instructions
Have a user confirm acceptance of the Privacy Policy on login (Enable the System - Privacy Consent plugin)
Go to the administrator Privacy / Consents page.

### Actual result BEFORE applying this Pull Request
The Subject is a string key: PLG_SYSTEM_PRIVACYCONSENT_SUBJECT

### Expected result AFTER applying this Pull Request

the Subject is a translated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 7bd64022472e728626cba118b5a2bf3b7bf3d1e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44192">issues.joomla.org/tracker/joomla-cms/44192</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7bd64022472e728626cba118b5a2bf3b7bf3d1e6<br /><br />Good - I see the the Subject change from a key to the translated string.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44192">issues.joomla.org/tracker/joomla-cms/44192</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44192">issues.joomla.org/tracker/joomla-cms/44192</a>.</sub>

**Comment by richard67** [comment]
@alikon Why for the 5.1-dev branch? There will not be any new 5.1 release. The PR should be made for the 5.2-dev branch. Could you rebase?

**Comment by alikon** [comment]
didn't know

**Comment by richard67** [comment]
> didn't know

@alikon https://developer.joomla.org/roadmap.html#5x

**Comment by richard67** [comment]
I think it doesn’t need new test and RTC is still ok as the rebase from 5.1-dev to 5.2-dev was clean without any conflicts.

**Comment by pe7er** [comment]
Thanks @alikon !

**Pull request merged**
