### PR TITLE
[4.0] Mod SampleData xml desccription

### PR DESCRIPTION
**Pull request by brianteeman**
Translate the string into English

### CODE REVIEW

**Review by Bakual — APPROVED** [review]
Obviously looks fine.

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on b24763dc8903ddf708d4711c7bc2c71d7ec344aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23681">issues.joomla.org/tracker/joomla-cms/23681</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b24763dc8903ddf708d4711c7bc2c71d7ec344aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23681">issues.joomla.org/tracker/joomla-cms/23681</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23681">issues.joomla.org/tracker/joomla-cms/23681</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
