### PR TITLE
[5.2] Improve button toolbar for templates

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #43212 .

### Summary of Changes
Several users mentioned confusion i the com_templates toolbar, caused by the delete-file and close-file button.
This is an attempt to provide a solution with as few changes as possible. 
Some buttons are used in the whole system and cannot be changed for this view, so we have not many options for changes here. 

I suggest 

1) change the text on the "close file" button to "close". Because this button does not only close the file but it closes the screen and redirects back, for users it does not matter if there is another action in the code.  

2) Move the "Close" Button" directly after the action buttons, before the file management buttons. 

3) Use the trash icon on the "file delete" button. We had many discussions about that - In Joomla the trash button means "trashed" => state = -2 not "deleted permanently", but when we think as a user not as a developer, the icon is completely clear here. 

I improved the code a little bit by removing an unused variable and with switch instead of elseif. 

### Testing Instructions
Play around in templates and template styles, make child templates, manage files.
Whatever you want to do with your template should have a comprehensive and complete toolbar, in most cases the same as before. 

### Actual result BEFORE applying this Pull Request
see #43212. 
delete button and close-file button.
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
just a thought about enhancing this further. Before this we have both a "close" and a "close file" depending on the context. They do different things. Close returns to the template manager, close file - closes the open file.

How about changing "close" to "exit" with the exit door icon. This way we do not have two buttons with the same icon and name that do different things

**Comment by chmst** [comment]
Cannot find a use case with "archive", but it has also the template.cancel task. 

@brianteeman I could do that, it needs a new button in button layouts. 
Fun fact: only the "close" button does something - it closes the open file before exit. In all other cases, it is a cancel action and does nothing than exit.

Is this better? 
grafik

**Comment by richard67** [comment]
Hmm, "exit" would scare me because it would make me think it logs me off the administrator completely .. but maybe it's only me thinking like that.

**Comment by dautrich** [comment]
@brianteeman I don't agree with you. We have "Save & Close". So why shouldn't we use "Close"?

**Comment by brianteeman** [comment]
You missed the point.

**Comment by chmst** [comment]
@dautrich We have the buttons 
Save -> save changes in the file and don't quit
Save and Close -> save changes in the file and quit
Close -> do NOT save changes and quit. 

We hat this discussion already in a former version and my suggestion for the exit icon was refused with the same argument as @richard67 mentioned in his comment.

**Comment by ChristineWk** [comment]
Save / Save and Close on green color.
Close may be blue or leave it green.
Delete File on red color (at the end of the buttons).

**Comment by Quy** [comment]
Before PR:
43592-before

After PR, button moved and icon is  black.
43592-after

**Comment by Quy** [comment]
It is missing `btn-primary` class. This is not the case without this PR.

43592-button

**Comment by chmst** [comment]
Yes. My screen is from a fresh installation of J4 without PR. 
This was changed with PR https://github.com/joomla/joomla-cms/pull/42071
But it does not matter. It will be the same here as with all other PRs for layouts. Ask 5 users and get 10 opinions ;) and never will get consent

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on 16a507e680a82ca3663b2df53db67b0478d31c63<br /><br />Works well, thank you for the work you put in<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43592">issues.joomla.org/tracker/joomla-cms/43592</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 16a507e680a82ca3663b2df53db67b0478d31c63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43592">issues.joomla.org/tracker/joomla-cms/43592</a>.</sub>

**Comment by richard67** [comment]
This PR needs to be rebased to 5.2-dev. Not sure if I should do that now as the 5.2-dev branch is 2 commits behind 4.4-dev. Will try and if it doesn't work revert.

**Comment by chmst** [comment]
Thank you all testers for testing. Unfortunately this cannot go into 4.4 and has conflicts with 5,2. and cannot be rebased.
I will resolve conflicts and make it for 5.2 and tests must be repeated.

**Comment by chmst** [comment]
Closed in favour of #43592

**Comment by richard67** [comment]
> Closed in favour of #43592

@chmst I guess you meant #43975 .

**Pull request closed without merging**
