### PR TITLE
[5.2] If RSS feed is blocked, don't allow access to RSS output

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
Right now we have the ability to disable the RSS link in the header of different views, however that only hides the link in the output. You can still access the RSS output when simply typing in the URL. This PR disables the output when the link is disabled. 

### Testing Instructions
Go to any view which also provides a feed output and open the options for its menu item or change the the global configuration of the component to disable showing the feed link.

### Actual result BEFORE applying this Pull Request
You can still access the output of the RSS feed.

### Expected result AFTER applying this Pull Request
You get a 404 "Resource not found" result.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on 3c50bfc11e717b3b1cea90fdbae662a881207505<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43692">issues.joomla.org/tracker/joomla-cms/43692</a>.</sub>

**Comment by fgsw** [comment]
@Hackwar Is a test useful even "This branch is out-of-date with the base branch"?

**Comment by brianteeman** [comment]
> @Hackwar Is a test useful even "This branch is out-of-date with the base branch"?

as long as there are no conflicts then yes

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 3c50bfc11e717b3b1cea90fdbae662a881207505<br /><br />Test on a multilingual site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43692">issues.joomla.org/tracker/joomla-cms/43692</a>.</sub>

**Comment by fgsw** [comment]
Ready To Commit?

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Pull request merged**
