### PR TITLE
[4.0] [a11y] empty headings com languages

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

This PR adds a fallback value for heading when creating a new language.

### Testing Instructions

- Start creating a new language.
- View source and look for `id="user-form"` and the empty h2 is in the next line.

### Actual result BEFORE applying this Pull Request

Before ... heading is empty
Schermafdruk 2020-07-03 21 51 47

### Expected result AFTER applying this Pull Request

After... heading is filled with text. Text is visible too,
Schermafdruk 2020-07-03 21 52 06

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0945ffc55a21b65bae319b2ab16b10c2ef8606c1<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29939">issues.joomla.org/tracker/joomla-cms/29939</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0945ffc55a21b65bae319b2ab16b10c2ef8606c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29939">issues.joomla.org/tracker/joomla-cms/29939</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29939">issues.joomla.org/tracker/joomla-cms/29939</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
