### PR TITLE
Fix of broken alternative title in the Content - Pagebreak plugin

### PR DESCRIPTION
**Pull request by philip-sorokin**
Pull Request for Issue # **Broken alternative title in the Content - Pagebreak plugin**

#### Summary of Changes

The attributes are not parsed if their order is different from `'#<hr(.*)class="system-pagebreak"(.*)\/>#iU'`. As a result, an alternative title does not appear. In order to parse the second capture group, it must be concatenated with the first capture group.

#### I
1. Create an article.
2. Enable pagination by adding tags `<hr class="system-pagebreak" />`.
3. If you set the alternative title attribute before the class attribute `<hr title="title" alt="alt" class="system-pagebreak" />`, it will work.
4. If you set the title attribute after the classname attribute `<hr class="system-pagebreak"  title="title" alt="alt" />`, the alternative title will not be set.

#### II
1. Try to create a page break without a self-closing slash (which is valid in HTML5) `<hr class="system-pagebreak">` – it will fail.

### CODE REVIEW

**Comment by brianteeman** [comment]
Am I correct that this "bug" can only be observed if you write the tags manually and are not using the editor-xtd plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10754">issues.joomla.org/joomla-cms/10754</a>.</sub>

**Comment by addondev** [comment]
Brian, this bug (without quotes) can be observed independently of the way of creating tags. I use Code Mirror, and it insertes the title after the class attributes.

**Comment by brianteeman** [comment]
I ask this because it is important for testers to know how to recreate the
issue

On 8 June 2016 at 09:31, Philip Sorokin <notifications@github.com> wrote:

> Brian, this bug (without quotes) can be observed independently of the way
> of creating tags. I use Code Mirror, and it insertes the title after the
> class attributes.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10754#issuecomment-224523587>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Xk3Hj0eK61pj4MY9T0Efag_UaaYks5qJn3KgaJpZM4IwcQ0>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by addondev** [comment]
I noticed that making the self-closing slash optional is not working. So, I have edited this PR.

**Comment by brianteeman** [comment]
I just tested and I cannot replicate the problem
1. Tested with tinymce pagebreak - no problem
2. Tested with codemirror pagebreak - no problem (the code generated is the same as above)
3. Tested pasting pagebreak code manually in the "wrong" order - no problem

Please see the video for tests 2 and 3
https://www.dropbox.com/s/aalqneftgq9222r/10754.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10754">issues.joomla.org/joomla-cms/10754</a>.</sub>

**Comment by addondev** [comment]
**@brianteeman**, the title works while the meta tag `<title>Is not changing</title>` if the order of attributes is as described above.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 51e11723b02d4cd8fad8ae5753ac81b63ecc60b5<br /><br />I see what you mean now and the PR fixes that issue - however the only way I can get the code in the wrong order is by entering it manually. The editor plugin always does it correctly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10754">issues.joomla.org/joomla-cms/10754</a>.</sub>

**Comment by addondev** [comment]
As far, as I know, Code Mirror always insertes page breaks like this: `<hr class="system-pagebreak" title="title"  alt="description" />`. This order breaks the title. However, it is correct when I put the title and alias attributes manually before the class attribute.

**Comment by brianteeman** [comment]
Isnt it the other way around

On 8 June 2016 at 19:03, Philip Sorokin <notifications@github.com> wrote:

> As far, as I know, Code Mirror always insertes page breaks like this: <hr
> class="system-pagebreak" title="title" alt="description" />. This order
> breaks the title. However, it is correct when I put the title and alias
> attributes manually before the class attribute.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10754#issuecomment-224677109>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8RzWvHIZDghsXmZrbGqj3Rw1Igrjks5qJwP6gaJpZM4IwcQ0>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by addondev** [comment]
Will it be a part of Joomla! 3.6?

**Comment by crommie** [comment]
I have tested this item :red_circle: unsuccessfully on 7d0559520c971db800697d7a788a09fe56699f46<br /><br />Tested according to instructions, using CodeMirror.
Set alternative title attribute before class attribute (step 3): working as described in instructions.
Set alternative title after classname attribute (step 4): not working as described in instructions: alt title is set.
Try to create page break without a self closing slash (step I-1): fails, and still fails after applying patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10754">issues.joomla.org/joomla-cms/10754</a>.</sub>

**Comment by brianteeman** [comment]
@addondev please can you check the failure report above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10754">issues.joomla.org/tracker/joomla-cms/10754</a>.</sub>

**Comment by philip-sorokin** [comment]
@brianteeman 
This PR requires more work. So, it should be closed. I will open a new one.

**Pull request closed without merging**
