### PR TITLE
Remove usage of deprecated JArrayHelper - com_config

### PR DESCRIPTION
**Pull request by izharaazmi**
Remove usage of deprecated JArrayHelper from com_config
#### Testing Instructions
- Test the module manager to see if the global configurations are shown in the edit form correctly and saved successfully.
- Review code.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 7e8cfba3c3c2541593cc79edcb85aa7895cb2b61<br /><br />Module config options owrks fine.
Code review fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10674">issues.joomla.org/joomla-cms/10674</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 7e8cfba3c3c2541593cc79edcb85aa7895cb2b61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10674">issues.joomla.org/joomla-cms/10674</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10674">issues.joomla.org/joomla-cms/10674</a>.</sub>

**Comment by wilsonge** [comment]
These changes got merged as part of 9ef83f70040ab3ad18efc7875622e30cd82c1eff - Thanks!

**Pull request closed without merging**
