### PR TITLE
[4.0] Add error page for Atum

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #16836

### Summary of Changes

Adds an error page to the Atum template

### Testing Instructions

- Apply patch
- Navigate to `/administrator/index.php?option=com_blabla`

### Expected result

screeny

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
cannot test caus https://github.com/joomla-extensions/patchtester/issues/200

**Comment by C-Lodder** [comment]
@franz-wohlkoenig Only 1 file has been added. 

So:

1. Create an `error.php` file
2. Add the code from https://github.com/C-Lodder/joomla-cms/blob/bdda52d1f2931536f165c5d5f60b5e50d5b2a315/administrator/templates/atum/error.php
3. Place the file in `administrator/templates/atum/`

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on bdda52d1f2931536f165c5d5f60b5e50d5b2a315<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16861">issues.joomla.org/tracker/joomla-cms/16861</a>.</sub>

**Comment by andrepereiradasilva** [comment]
works fine, did notice some details tough:
- it's missing the joomla favicon.
- it's missing and html tag title

**Comment by C-Lodder** [comment]
@andrepereiradasilva - Good spot. Added the title and favicon (https://github.com/joomla/joomla-cms/pull/16861/commits/d1f70d54cf44ddcad1bae62e683cc6b9ccda8b87)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d1f70d54cf44ddcad1bae62e683cc6b9ccda8b87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16861">issues.joomla.org/tracker/joomla-cms/16861</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d1f70d54cf44ddcad1bae62e683cc6b9ccda8b87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16861">issues.joomla.org/tracker/joomla-cms/16861</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
