### PR TITLE
Move JRD links to HTTPS

### PR DESCRIPTION
**Pull request by jeckodevelopment**
### Summary of Changes
Links to the Joomla! Resources Directory now use HTTPS.
Changed both readme files of the repo and the links in the administration menu, also for Hathor template.

### Testing Instructions
Code review + test admin links to JRD

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
there qare move files with that url

```
egrep -R "resources\.joomla\.org" /path/to/joomla-staging/

/README.md:
/administrator/templates/hathor/html/mod_menu/default_enabled.php
/administrator/modules/mod_menu/tmpl/default_enabled.php
/README.txt
/tests/unit/stubs/database/jos_ucm_content.csv
/tests/unit/stubs/database/jos_content.csv
/tests/unit/stubs/database/jos_finder_links.csv
/installation/sql/mysql/sample_testing.sql
/installation/sql/mysql/sample_learn.sql
/installation/sql/postgresql/sample_testing.sql
/installation/sql/postgresql/sample_learn.sql
/installation/sql/sqlazure/sample_testing.sql
/installation/sql/sqlazure/sample_learn.sql
```

**Comment by jeckodevelopment** [comment]
@andrepereiradasilva thanks. Will look at them :)

**Comment by jeckodevelopment** [comment]
@andrepereiradasilva it should be ok now :)

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment see https://github.com/jeckodevelopment/joomla-cms/pull/1 for missing changes

**Comment by jeckodevelopment** [comment]
Done, thanks!

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 004e247bd8405d95c8802820d31a1928648ca743<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13033">issues.joomla.org/tracker/joomla-cms/13033</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 004e247bd8405d95c8802820d31a1928648ca743<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13033">issues.joomla.org/tracker/joomla-cms/13033</a>.</sub>

**Comment by mbabker** [comment]
JRD neither forces HTTPS and still has mixed content warnings.

**Comment by andrepereiradasilva** [comment]
ok, i assumed those issues were already resolved because @jeckodevelopment was making a PR.

ok so first those issues need to be solved and only them this PR should be merged

**Comment by brianteeman** [comment]
I am closing this for now - it can be reopened (if still mergeable) when the JRD finally understands mixed content<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13033">issues.joomla.org/tracker/joomla-cms/13033</a>.</sub>

**Pull request closed without merging**
