### PR TITLE
[4.0] CLI list

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the strings displayed when running `php cli/joomla.php list` to ensure consistent grammar and tense etc

(a subsequent pr will be created for `php cli/joomla.php help`)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6744518e6ae7c5bad6029f2d20a8076264fa71b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29799">issues.joomla.org/tracker/joomla-cms/29799</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Shouldn't this one be changed, too?

https://github.com/brianteeman/joomla-cms/blob/cli/libraries/src/Console/ChangeUserPasswordCommand.php#L167

`Changes a user's password` -> `Change a user's password`

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1ecc4dd1483783c3fefd929459618d5e47321508<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29799">issues.joomla.org/tracker/joomla-cms/29799</a>.</sub>

**Comment by richard67** [comment]
@Quy Could you test again (or short review should be sufficient, too)?

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1ecc4dd1483783c3fefd929459618d5e47321508<br /><br />String changes look good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29799">issues.joomla.org/tracker/joomla-cms/29799</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29799">issues.joomla.org/tracker/joomla-cms/29799</a>.</sub>

**Comment by brianteeman** [comment]
thanks - now i can work on the help

**Pull request merged**
