### PR TITLE
[4.2] Page navigation focus ring

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38135 .

### Summary of Changes
changes list to span
changes class name

### Testing Instructions
apply pr
go to a content page displaying next and previous buttons
navigate to those buttons using your keyboard

### Actual result BEFORE applying this Pull Request
No focus ring
image

### Expected result AFTER applying this Pull Request
Focus ring
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5a837f4225e3a94c69e8d9cde4f1ff3fc9b54d37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38236">issues.joomla.org/tracker/joomla-cms/38236</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5a837f4225e3a94c69e8d9cde4f1ff3fc9b54d37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38236">issues.joomla.org/tracker/joomla-cms/38236</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38236">issues.joomla.org/tracker/joomla-cms/38236</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
