### PR TITLE
Extend showon attribute with negation resolve #14257

### LINKED ISSUE #14257: showon sign '!:' does not work
### Steps to reproduce the issue
```
<field name="masterfield" type="radio" default="1" class="btn-group btn-group-yesno" label="MasterField" >
	<option value="0">unknown</option>
	<option value="1">value 1</option>
	<option value="2">value 2</option>
</field>
<field name="subfield" type="radio" default="1" showon="masterfield!:0" class="btn-group btn-group-yesno" label="SubField" >
	<option value="1">Show text field</option>
	<option value="2">Show URL field</option>
</field>
<field name="subText" showon="masterfield!:0[AND]subfield:1" type="text" default="" label="Text" />
<field name="subURL" showon="masterfield!:0[AND]subfield:2" size="20" type="url" default="" label="URL" />
```

### Expected result
the subfield AND subText/subURL should only displayed if value of masterfield is not 0.

### Actual result
the subfield is shown always and the fields subText and subURL ignore value of masterfield also.

### System information (as much as possible)
v3.7.0-beta3

### Additional comments
i add a demo plug-in to reproduce the issue easy
[plg_issue_showon_sign.zip](https://github.com/joomla/joomla-cms/files/801885/plg_issue_showon_sign.zip)

### PR DESCRIPTION
**Pull request by jjaracz**
Pull Request for Issue #14257 .

### Summary of Changes

I extend `cms.js` file in `media/jui/js` to add negation to showon attribute.

### Testing Instructions

Fallow the #14257 issue.
But change `masterfield!:0[AND]subfield:1` to `masterfield:!0[AND]subfield:1` and so on.

### Expected result

#14257 

### Actual result

Like expected.

### Documentation Changes Required

Yes.
On this [page](https://docs.joomla.org/Form_field).

### Usage

To use to the all options:
- expect one, use attribute `showon="foo:!2"`
- expect multiple, use attribute `showon="foo:!1,2,3"`

### CODE REVIEW

**Comment by brianteeman** [comment]
@GeraintEdwards thought this might be relvant to your other PR

**Comment by GeraintEdwards** [comment]
I believe this is fixed by https://github.com/joomla/joomla-cms/issues/15104 and so should be closed

**Comment by Quy** [comment]
@franz-wohlkoenig Close per GeraintEdwards.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14307">issues.joomla.org/tracker/joomla-cms/14307</a>.</sub>

**Pull request closed without merging**
