### PR TITLE
[4.3][Guided Tours] target corrections

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issues #40006 and #40029.

### Summary of Changes

The script considers all steps with a target as interactive.
This was incorrect.
While fixing this issue, it appeared that many steps were not having the right type.
This PR also removes the :has selector to improve compatibility with Firefox.

### Testing Instructions

Start the 'Create a contact' tour.
Step through the tour, up to the 'Enter detailed information'.

### Actual result BEFORE applying this Pull Request

You cannot tab through the back/next/cancel buttons, only shift tab.

### Expected result AFTER applying this Pull Request

You can tab through the back/next/cancel buttons.

Note: this PR fixes steps that were set with a wrong type. Now that steps are correct, you will encounter steps with 'Next' being disabled on required AND NOT required input fields. This is temporary and addressed in PR #40062. 
It's a chicken and egg thing here...

Under Firefox, category and tags should be properly targeted with this PR as well, once resuming the tour.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by kendall-cabe** [comment]
I have tested this item :white_check_mark: successfully on 25751892771d18eb6ccb516a72a1db81f01fad1d<br /><br />Installed the pre-built full zip tile. Went through step by step of the PR instructions.
I was able to tab from cancel to back to next with no issues. Shift-tab still worked to go the opposite direction as well. 

Test Successful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40077">issues.joomla.org/tracker/joomla-cms/40077</a>.</sub>

**Comment by ChristineWk** [comment]
Successful in principle, but: Field: Enter an alias: the button Next is inactive for automatic insertion of the alias.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40077">issues.joomla.org/tracker/joomla-cms/40077</a>.</sub>

**Comment by obuisard** [comment]
@ChristineWk see the note in the PR description, it was expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40077">issues.joomla.org/tracker/joomla-cms/40077</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 25751892771d18eb6ccb516a72a1db81f01fad1d<br /><br />@obuisard 
Ah, I see now the "chicken and egg thing" :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40077">issues.joomla.org/tracker/joomla-cms/40077</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40077">issues.joomla.org/tracker/joomla-cms/40077</a>.</sub>

**Pull request merged**
