### PR TITLE
[4.0][RTL][Atum] Add RTL Support

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Broad RTL styling for the Atum backend template.

- General RTL changes
- Moved sidebar to right
- Flipped main navigation
- Flipped status bar
- Flipped quick icons
- Removed directional bootstrap classes
- Removed floats from table
- Refactored dashboard modules to allow RTL

### Testing Instructions
Apply patch and log in to admin with RTL language (eg. Arabic).

**Edit**: Can also be tested without having to install an RTL language. See.. https://github.com/joomla/joomla-cms/pull/16593#issuecomment-307340596

### Expected result
rtl1

rtl2

rtl3

### Documentation Changes Required
Screenshots

### CODE REVIEW

**Comment by brianteeman** [comment]
For people testing you do not need to install a new language. You may find it easier to test in your own language and you can do this easily

For example to change en-GB to RTL you need to edit the administrator/languages/en-GB/en-GB.xml file and change

> 		<rtl>0</rtl>


to


> 		<rtl>1</rtl>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 3514000b11011a1e0ec62d7150fff71bec24d711<br /><br />Not sure if:

or

is now to be tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16593">issues.joomla.org/tracker/joomla-cms/16593</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @franz-wohlkoenig. Yes such issues can be reported here and I will amend them the next chance I get.

**Comment by ciar4n** [comment]
@franz-wohlkoenig Alerts and labels now fixed

**Comment by franz-wohlkoenig** [comment]
@ciar4n thanks, will test more this Weekend.

**Comment by franz-wohlkoenig** [comment]
@ciar4n:
This is also in LTR:
bildschirmfoto 2017-06-10 um 08 50 59
missing Space:
bildschirmfoto 2017-06-10 um 08 53 46

**Comment by ciar4n** [comment]
@franz-wohlkoenig Btn-group (missing space) has been fixed.

Issues also present in LTR I will leave for a separate PR. Maybe just create a issue so we don't forget.

**Comment by franz-wohlkoenig** [comment]
Fix looks fine.

#16620

**Comment by franz-wohlkoenig** [comment]
Text align right:
bildschirmfoto 2017-06-12 um 09 30 25

**Comment by franz-wohlkoenig** [comment]
Point at Beginning of Sentence?

**Comment by ciar4n** [comment]
> Text align right:

Fixed



> Point at Beginning of Sentence?

If I am not mistaken this is correct RTL behaviour

The media manager can be ignored for now. I will do the RTL for that separately

**Comment by brianteeman** [comment]
>> Point at Beginning of Sentence?
> If I am not mistaken this is correct RTL behaviour

RTL gets very funky when you have LTR text in it - especially punctuation.. Dont worry about that for now it should be fine when using an RTL language and font

**Comment by wilsonge** [comment]
I'm going to merge this as a starting point before it starts accumulating conflicts. I'm sure there's going to be a lot more to do though :)

**Pull request merged**
