### PR TITLE
[4.4] Fixing non-SEF URL in feed output

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #39775.

### Summary of Changes
When Joomla is installed in a subdirectory and URLs are set to be completely non-SEF, the URLs in a feed output are wrong. Specifically, the path to the root of Joomla is doubled, for example https://domain.tld/subdir/subdir/index.php instead of just https://domain.tld/subdir/index.php
It works fine with SEF URLs enabled.

### Testing Instructions
1. Install Joomla in a subdirectory and disable all SEF URL options
2. Go to a category view and look at the feed URL in the header.
3. Download the feed and look into the output.

### Actual result BEFORE applying this Pull Request
 The link in for example <atom:link rel="self" type="application/rss+xml" is wrong

### Expected result AFTER applying this Pull Request
 The link in for example <atom:link rel="self" type="application/rss+xml" is correct.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@Hackwar Is there a reason why not fixing it for 4.4-dev?

**Comment by richard67** [comment]
@Hackwar New features go into 5.1-dev. Bug fixes for bugs which affect 4.4 and 5.x go into 4.4-dev. Into 5.0-dev only bug fixes go where the bug doesn’t affect 4.4.

**Comment by Globulopolis** [comment]
I have tested this item :white_check_mark: successfully on fda45a77a9424fe399465d9596ccfe9b8f4525ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by richard67** [comment]
@Hackwar After our talk yesterday in the CMS Maintenance Team you said you will make this PR for 4.4-dev. Will you rebase this one, or will you make a new one? I'm asking because this one here has 2 good tests so it would be RTC (if not for the wrong branch).

**Comment by Hackwar** [comment]
I recreated the PR with 4.4-dev as base branch. The code is identical. Do we need new tests?

**Comment by richard67** [comment]
@Globulopolis @viocassel Could you test this PR again on 4.4.x? Thanks in advance.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b3ef2726f8fe3ce94afee435c5dca30f495dd3b9<br /><br />👌<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by den1ska07** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by den1ska07** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by richard67** [comment]
> I have not tested this item.

@den1ska07 If you submit a test result you have to select the right result before submitting.

**Comment by Globulopolis** [comment]
I have tested this item :white_check_mark: successfully on b3ef2726f8fe3ce94afee435c5dca30f495dd3b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by den1ska07** [comment]
I have tested this item :white_check_mark: successfully on b3ef2726f8fe3ce94afee435c5dca30f495dd3b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42802">issues.joomla.org/tracker/joomla-cms/42802</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
