### PR TITLE
[4] Unnecessary curly braces syntax for variable

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 9d8ef71fb67f8ef326fe094bb175ed3bcde5b43f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33969">issues.joomla.org/tracker/joomla-cms/33969</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9d8ef71fb67f8ef326fe094bb175ed3bcde5b43f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33969">issues.joomla.org/tracker/joomla-cms/33969</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33969">issues.joomla.org/tracker/joomla-cms/33969</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
