### PR TITLE
cleanup Index.html

### PR DESCRIPTION
**Pull request by brianteeman**
remove index.html reference from com_contenthistory xml as there is no file

com_mailto
remove index.html reference from com_mailto xml as there is no file
remove admin folder reference as there is no folder

com_wrapper
rename metadata.xml to wrapper.xml
remove admin folder reference as there is no folder

Remove some index.html files that are not needed as the folder is not empty and thats the only reason we were keeping them in some folders

### CODE REVIEW

**Comment by wilsonge** [comment]
The top level ones I think still need to exist for the build https://github.com/joomla/joomla-cms/blob/staging/build/build.php#L75-L88

**Comment by brianteeman** [comment]
I thought we only had the top level ones where there was nothing else in the folder to force creating of the folder?

**Comment by wilsonge** [comment]
The top level ones force creating the folder in git and i thought the rest were there for the Joomla Build script. @mbabker could you confirm?

**Comment by brianteeman** [comment]
I can see why we need top level ones where there would be no files only folders - i didnt touch those
I cant see why we would need them if there are files and folder - those are the ones i touched

**Comment by mbabker** [comment]
We'd have to test, but the top level stuff only had to actually exist in the patch/update packages when installing through the extension manager.  So we might not even need those or the part of the build script marking those as required anymore.

**Comment by tonypartridge** [comment]
Did anyone run any build tests on this?

**Review by dgrammatiko — APPROVED** [review]

**Comment by mbabker** [comment]
On principle I agree with this but I need to test with a test package to ensure removing the index.html files from top level directories doesn't cause an issue with updates (it shouldn't, that was a mostly artificial requirement from updates with the Extension Manager, but better safe than sorry).

**Comment by zero-24** [comment]
Was'nt the top level index.html files needed when we have a release that is not touching this folders? (like 3.7.5)

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/blob/staging/build/build.php#L75-L103

**Comment by mbabker** [comment]
And I will say again, that was explicitly because of the Extension Manager install path.  We are not supporting that anymore, hence the reason this needs to be actively tested and not just either merged on a review or based on inline comments in the build script.

**Comment by brianteeman** [comment]
As this is !y pr I will take some time to use the build scripts to test. But the build script is pretty easy to use so please do that as well.

**Comment by brianteeman** [comment]
lost interest

**Pull request closed without merging**
