### PR TITLE
Remove myself from the CODEOWNERS file

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Remove myself from the CODEOWNERS file.

### Testing Instructions

Its just a config file so only a review & merge is needed
Please merge it up to 5.x-dev and 6.x-dev once merged.

### CODE REVIEW

**Comment by brianteeman** [comment]
This change highlights a problem in the file

> Unknown owner on line 9: make sure @fancyFranci exists and has write access to the repository
build.xml  @fancyFranci

**Comment by zero-24** [comment]
Yes I can include it here when there is no reason that she is still part of that file maybe its intended for documentation reasons?

**Comment by zero-24** [comment]
Thanks :)

**Comment by laoneo** [comment]
I'm merging this as the @fancyFranci should be done in a different pr.

Thanks @zero-24 for all the work in these years!

**Pull request merged**
