### PR TITLE
Remove unneeded metadata.xml files

### PR DESCRIPTION
**Pull request by Bakual**
Currently, we have metadata.xml files in each view. However since Joomla 3.5.0 those are no longer required (PR https://github.com/joomla/joomla-cms/pull/7654).
### Summary of Changes

This PR removes the metadata.xml files since they have no function at all in core.
This will help extension developers to see best practices.
### Testing Instructions
- Test creating menu items for the affected views. Nothing strange should happen.
- Check the menu item type text in the menu item manager, see picture. Nothing should change there.
  metadata
### Documentation Changes Required

None to my knowledge.

### CODE REVIEW

**Comment by photodude** [comment]
#### Documentation Changes ~~Required~~ Suggested
The Hello world example component code/development tutorial likely needs a major update to match with 3.5+ best practices. (I think it was last revised with 3.2)

**Comment by Minei3oat** [comment]
I have tested this item :white_check_mark: successfully on bbbf9340a600dd3068e01b4b3fa7e6cb26e67e77<br /><br />I didn't found a posibility to test the views of com_mailto because there are no selectable views (XML-files are missing).
All other was working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11990">issues.joomla.org/joomla-cms/11990</a>.</sub>

**Comment by jsubri** [comment]
Should we have these files in script.php at the same time?

**Comment by brianteeman** [comment]
Yes

**Comment by Bakual** [comment]
I didn't add them to the script.php because it doesn't really matter if they are present or not. As you see currently :smile: 
If we merge somethign like this https://github.com/joomla/joomla-cms/pull/10548, they may be needed again in special cases.

**Comment by brianteeman** [comment]
It starts to become a mess if you have some sites with files and some sites without. Especially security scanners. If the files are not needed then they should be removed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11990">issues.joomla.org/joomla-cms/11990</a>.</sub>

**Comment by Bakual** [comment]
Added the files to the script.php. If it's not merged for 3.6.3 that files needs to be adjusted so the comment matches :)

**Comment by Bakual** [comment]
> The Hello world example component code/development tutorial likely needs a major update to match with 3.5+ best practices like the removal of metadata.xml. (I think it was last revised with 3.2)

@photodude I had a look but couldn't find anything related to metadata.xml on a first glance. At least not where I would have expected it (https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_a_menu_type_to_the_site_part)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5638ec2c9646635ed6c06f8c24e33e21806c99d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11990">issues.joomla.org/tracker/joomla-cms/11990</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11990">issues.joomla.org/tracker/joomla-cms/11990</a>.</sub>

**Pull request merged**
