### PR TITLE
Admin Module Cpanel Positions

### PR DESCRIPTION
**Pull request by brianteeman**
Pr for #30286

In the installation data some of the modules did not have an ordering set. This created a problem as seen in #30286 when attempting to change the order of modules in the cpanel position from the module setting. (it only worked with drag and drop or after you have done a drag and drop then the positions are corrected on existing installs)).

By ensuring that all the modules have a position this problem is resolved. However as this is user data we can only do this for new installs.

To test.
I suggest that you first verify the problem on an existing CLEAN install.
Then create a NEW install from the prebuilt package and then try to repeat the error. Its a success if you can no longer repeat the error

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman If there is an old 4.0.x update SQL which adds these modules, we could fix the ordering there so it would be right when updating from a 3.10 version. I know you don’t like that, and I do not insist on it, but it would have that advantage.

**Comment by brianteeman** [comment]
@richard67 thats a good idea and would have been useful but unfortunately there is no suitable query. Updates from j3 will be ok. Its only updates from earlier versions of j4 that started life as j4 that will see this obscure problem

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 64a42640c33bfbe1b2890e33a9d6dc3d1b4614d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38633">issues.joomla.org/tracker/joomla-cms/38633</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 64a42640c33bfbe1b2890e33a9d6dc3d1b4614d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38633">issues.joomla.org/tracker/joomla-cms/38633</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38633">issues.joomla.org/tracker/joomla-cms/38633</a>.</sub>

**Comment by fancyFranci** [comment]
Nice bug fix. Thank you!

**Comment by brianteeman** [comment]
Thanks. Shame it took so long

**Pull request merged**
