### PR TITLE
Further work on layouts

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
- Unnecessary parentheses
- Ternary operator simplification and type safe comparison
- Use elvis!
- Type-casting instead of strVal()
- Replace isArray()... with type-cast

The changes in this PR are only a few and should be fairly easy to review. In hope that this will get merged quickly so further work can be done without conflicting with other PRs. ;)

### Testing Instructions

None, should not change behavior

### Documentation Changes Required

None.

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Review by ggppdk — APPROVED** [review]

**Comment by jeckodevelopment** [comment]
@ggppdk and @andrepereiradasilva can you please continue using tests as usual?

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment i asked how should i mark this code reviews on JBS channel.
I'm not doing tests, just code review, so marked as code review as instructed in that channel.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 807500cc3c7a1831fdb6cbfbd0625cd2caa55854<br /><br />I can mark a successful test on this one, on careful code review ... due to little changes involve

The unneeded parenthesis,
also the 2 type of typecasts done, are safe modifications, no problem with PHP 5.3


but i have not installed the patch to run any tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13296">issues.joomla.org/tracker/joomla-cms/13296</a>.</sub>

**Comment by frankmayer** [comment]
@ggppdk Yes, some of those batch PR's were huge with lots of different changes. That is why I have made compartmentalized sub-PR's to lighten the batch PR's up and be finally easier to review/test and finally merge them. The sub PR's are referenced in the batch-PR's and vice versa.

**Comment by shur** [comment]
I have tested this item :white_check_mark: successfully on 807500cc3c7a1831fdb6cbfbd0625cd2caa55854<br /><br />Code review. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13296">issues.joomla.org/tracker/joomla-cms/13296</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13296">issues.joomla.org/tracker/joomla-cms/13296</a>.</sub>

**Pull request merged**
