### PR TITLE
:uk: Typo fix?

### PR DESCRIPTION
**Pull request by MATsxm**
#### Summary of Changes

:uk: Typo fix?
#### Testing Instructions

Easy fix on code review.

@brianteeman could you please check it.

### CODE REVIEW

**Comment by roland-d** [comment]
@wilsonge In time for a merge?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 20795e4ba6db0ad0d2b91772136446f852bb1209<br /><br />on code review 
p.s.
non-english mother tongue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10770">issues.joomla.org/joomla-cms/10770</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 20795e4ba6db0ad0d2b91772136446f852bb1209<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10770">issues.joomla.org/joomla-cms/10770</a>.</sub>

**Comment by brianteeman** [comment]
As this only effects a typo in the en-gb language file no reason for it not to be merged <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10770">issues.joomla.org/joomla-cms/10770</a>.</sub>

**Comment by roland-d** [comment]
@brianteeman true that. Merged it. 

Thanks everybody.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
