### PR TITLE
wrong language string on installation #17706

### PR DESCRIPTION
**Pull request by 810**
Corrects #17706 
### Test instructions
Dowload last staging.
Modify the en-GB.ini as this PR does.
Install using en-GB and click on Remove "Installaion" Folder

### Steps to reproduce the issue

Install, and press `Remove "installation" folder`

### Expected result

`"installation" folder removed.`

### Actual result

`&quot;installation&quot; folder removed.`

### After Patch
`"installation" folder removed.`

### System information (as much as possible)

install with en-gb language

### Additional comments

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 15ccbadd2e961798872dc48d1f4536982c470e35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17718">issues.joomla.org/tracker/joomla-cms/17718</a>.</sub>

**Comment by infograf768** [comment]
RTC. Can be merged on review.

@mbabker <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17718">issues.joomla.org/tracker/joomla-cms/17718</a>.</sub>

**Comment by brianteeman** [comment]
Wile this PR works isnt the real problem to resolve the why html entities are not being rendered here

**Comment by mbabker** [comment]
It's an AJAX driven task so something with the JavaScript handling it I would presume.

**Comment by infograf768** [comment]
@mbabker 
Counting @brianteeman as testing OK, can this be merged?

It would avoid TTs already working on these ini files to make an error.

**Comment by ggppdk** [comment]
Explanation

The value of the button can only be assigned text and not HTML

and current language string value is HTML and not text !
```html
&quot;installation&quot;
```
and by doing
```js
$el.val(r.data.text);
```

javascript will correctly encode the given value before assigning into the value

to make it more clear
imagine that your language string had not only HTML character entities but also HTML tags,
would you expect that an input-type-button would interpret and show the following HTML ?
```html
<b> &quot;Text&quot; </b> and some more \"text\"
```

try the below small HTML example to see what is happening

```html
<html>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var some_html = "<b> &quot;Text&quot; </b> and some more \"text\" ";

			// The assigned string will be encoded because .value is text property
			document.getElementById('input-test').value = "<b> &quot;Text&quot; </b> and some more \"text\" ";

			// The assigned string will not be encoded because .innerHTML can be assigned HTML
			document.getElementById('div-test').innerHTML = "<b> &quot;Text&quot; </b> and some more \"text\" ";
		});
	</script>
	<body>
		<input id="input-test" type="button" value="This is a text value, i can not display HTML tags or interpret HTML entities , etc">
		<div id="div-test">HTML can be placed here</div>
	</body>
</html>
```

**Comment by ggppdk** [comment]
In short to continue my above answer it was not good idea to assign response to the value of the input-typebutton 

Correct fix , now and for future
- after click hide the button and display a div with a loading animation
- and on response received set the response's HTML as innerHTML of the above div

**Comment by infograf768** [comment]
In any case, as we will not have any `"_QQ_"` in 4.0, I think it is best to always use escaped double quotes everywhere we need double quotes now and get rid of `&quot;`. This will normalise the work for TTs, once they are explained this.
com_localise, already since a few versions, is already doing this systematically.

**Comment by mbabker** [comment]
Using `&quot;` is fine if you can guarantee the string will always be displayed in an HTML context.  Using escaped quotes is better since you don't have to worry about the display context.

**Comment by infograf768** [comment]
That is exactly what I meant. It will work in any context.

**Pull request merged**
