### PR TITLE
[4.0] [DRAFT] iconclass improvements.

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
Better b/c handling.
Allows for setting custom prefix & icons.

### Testing Instructions
compare & inspect icons.
apply pr.
Should be no changes.
install akeeba backup.
akeeba icon should display in dashboard.
no icon changes should be visible.

### Expected result

image

### Actual result
image

### Documentation Changes Required

Explain the ability of using prefix.  I don't think this is documented currently.
Most of all icons are set through the 
```
LayoutHelper('joomla.icon.iconclass', ['icon' => 'some-kind-of-icon-type'])
```
 adding prefix would become
```
LayoutHelper('joomla.icon.iconclass', ['icon' => 'some-kind-of-icon-type', 'prefix' => 'myprefix'])
```

### CODE REVIEW

**Comment by brianteeman** [comment]
> Allows for setting custom prefix & icons.

how and where?

**Comment by sandewt** [comment]
>Allows for setting custom prefix & icons.

And for Fixed Width Icons, e.g. `class="fas fa-skating fa-fw"` ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30645">issues.joomla.org/tracker/joomla-cms/30645</a>.</sub>

**Comment by N6REJ** [comment]
@sandewt I was thinking of putting that in a separate pr.

**Comment by N6REJ** [comment]
> > Allows for setting custom prefix & icons.
> 
> how and where?

don't understand your question.  Same way you normally use the layout except add 'prefix' => 'myprefix'

**Comment by hans2103** [comment]
I have tested this item :red_circle: unsuccessfully on b4cb558c630df54453a5bd964d5ad27bda3d0945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30645">issues.joomla.org/tracker/joomla-cms/30645</a>.</sub>

**Comment by hans2103** [comment]
Compare screenshots and see the result on the fa-circle icon in column _Home_

# before PR

Schermafbeelding 2020-09-17 om 08 09 25

# after PR

Schermafbeelding 2020-09-17 om 08 09 30

**Comment by hans2103** [comment]
The example above comes from `./administrator/components/com_menu/tmpl/items/default.php` and seems to fail when only 'fa-circle' if provided instead of 'fas fa-circle'.

https://github.com/joomla/joomla-cms/blob/2787e0c928e7abeaca49d7482b039f94b1dc1ee9/administrator/components/com_menus/tmpl/items/default.php#L214

This PR should also work in case `fas` is forgotten.

**Comment by sandewt** [comment]
## <h1>After PR

Missing Akeeba icon

30645_after

**Comment by hans2103** [comment]
@N6REJ created a PR on your PR. https://github.com/N6REJ/joomla-cms/pull/15

**Comment by N6REJ** [comment]
Thanks guys, I'll fix it tomorrow

**Comment by N6REJ** [comment]
- [ ] Remove extra fa-
image

- [ ] Missing Akeeba icon

- [ ] MERGE @hans2103 pr

**Comment by hans2103** [comment]
> * [ ]  Remove extra fa-
>   image
> * [ ]  Missing Akeeba icon
> * [ ]  MERGE @hans2103 pr

extra 'fa-' will be solved by merging my PR.

@sandewt can you add a screenshot of the devtools, so we can see what HTML is provided?

**Comment by sandewt** [comment]
>Missing Akeeba icon

## <h2>Joomla 4: before and after PR

30645_after_j4

## <h2> Joomla 3: for comparison
30645_after_j3

**Comment by hans2103** [comment]
@sandewt I see your screenshot below _Joomla 4: before and after PR_.
What is the influence of this PR when the result before apply this PR is equal to the result after apply this PR?

**Comment by hans2103** [comment]
The missing icon was not caused by this PR.
administrator/components/com_akeeba/Toolbar/Toolbar.php line 350: `$icon  = 'akeeba-j4';`
When I change the line to `$icon  = ' icon-akeeba-j4';` I can see the missing icon.

It seems that Akeeba is assuming the presence of Icomoon. This icon library has been replaced by Font Awesome in J4.
But due to backwards compatibility during J4 the icon should be shown. 
Tough one to solve I guess

**Comment by hans2103** [comment]
@sandewt just found out that an earlier merged PR caused the issue. 
see commit : https://github.com/joomla/joomla-cms/commit/e49cbc57c7250d809c7df47e5e19b0712b1ae771

**Comment by brianteeman** [comment]
> Tough one to solve I guess

Not really - revert all of these useless changes to the icons

**Comment by sandewt** [comment]
>The missing icon was not caused by this PR.

That's right.

**Comment by brianteeman** [comment]
>>>Allows for setting custom prefix & icons.

>>how and where?

>don't understand your question. Same way you normally use the layout except add 'prefix' => 'myprefix'

If that's what you meant by "allow custom prefix" etc then its no different to before this PR - you have to override the layout

Can you please please explain what the benefit is of this code. AFAICT the only B/C issue this fixes is one you introduced in another proposed pr and other than that its just change for change sake

**Comment by sandewt** [comment]
>@sandewt just found out that an earlier merged PR caused the issue.

Not completely true. 
I tried something, this seems to work for Joomla and Akeeba before patch #30645:
But is of course not a good solution!
```
//$icon = stristr($icon, "joomla") ? str_ireplace("joomla", "fab fa-joomla", $icon) : "fas fa-" . $icon; // skipp this line !?
?>
<h1 class="page-title">
	<span class="icon-<?php echo $icon; ?>" aria-hidden="true"></span>
        <span class="<?php //echo $icon; ?>" aria-hidden="true"></span>
	<?php echo $displayData['title']; ?>
</h1>
```

**Comment by brianteeman** [comment]
you probably didnt mean to update 578 files by including akeeba backup in this PR or to commit your on .gitignore file

image

**Comment by N6REJ** [comment]
> you probably didnt mean to update 578 files by including akeeba backup in this PR or to commit your on .gitignore file
> 
> image

ugh

**Comment by brianteeman** [comment]
Can you please please explain what the benefit is of this code. I am not alone in failing to see any point in this PR. If you cannot explain the benefits etc then its just change for changes sake.

**Comment by N6REJ** [comment]
we're rethinking the entire icon handling so closing all pr's for now.

**Comment by brianteeman** [comment]
Good

**Comment by sandewt** [comment]
See PR #30677<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30645">issues.joomla.org/tracker/joomla-cms/30645</a>.</sub>

**Pull request closed without merging**
