### PR TITLE
[4.0] [a11y] com_finder :: add missing legend to fieldset

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

After a11y testing the search form of component com_finder using WAVE it alerted me with the following message:
_Fieldset missing legend_

This PR changes a couple of things:
- add a `<legend>` to the `<fieldset>` of the search field section
- change `<div>` into `<fieldset>` of the advanced search section
- add a `<legend>` to the `<fieldset>` of the advanced search section
- add className `sr-only` to both fieldsets to keep is visually hidden.

### Testing Instructions

- Apply search... this will lead you to the search results on com_finder
- Inspect element on the search form and notice there is no `<legend>` in the `<fieldset>`
- Apply this PR
- Inspect element on the search form and notice the changes from above

### Actual result BEFORE applying this Pull Request
Screenshot taken from my dev tools
Schermafbeelding 2020-08-31 om 17 33 58

### Expected result AFTER applying this Pull Request
Screenshot taken from my dev tools
Schermafbeelding 2020-08-31 om 17 34 15

### CODE REVIEW

**Comment by brianteeman** [comment]
> Apply search... this will lead you to the search results on com_finder

how does it lead me to the results?

**Comment by hans2103** [comment]
@brianteeman sorry for my bad English.

On my Joomla 4 test site (https://joomla4.test) I've installed Blog Sample Data. 
This will place a search form in the header.
When you use this form and press the search button, the url of the page changes to http://joomla4.test/index.php/component/finder/search?q=blog&Itemid=101&Itemid=101

With this I mean "lead you to the search results on com_finder".
How should I have written it? It will help me to write better test instructions in the future.

**Comment by brianteeman** [comment]
Never apologise for bad english - its far better than my dutch.

"This will load the search results" is probably ok

Now for the reason I asked the question. I had hoped by your description that you had fixed the accessibility problem when the search is performed and the results are displayed. Obviously as I misunderstood what you were writing you did not and I guess it will need to be in another PR but for the sake of completeness I will write it here.

When you enter a search term and press the search button the page reloads and anyone using a screen reader  will have to navigate all the way down the page and past the search form in order to find out if there are any results. They should be taken to the results immediately OR there should be an announcement that there are x results on page load. Its even worse when the advanced link (it should be a button) is selected

**Comment by hans2103** [comment]
@brianteeman thank you 
Will create multiple steps to improve the accessibility of com_finder. 
This baby step is one of them. 

I think this PR will solve one of the a11y issue. Missing `legend` in the `fieldset`.

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on dac3f90bf97af098264399e4ec5b40811b85965a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30528">issues.joomla.org/tracker/joomla-cms/30528</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dac3f90bf97af098264399e4ec5b40811b85965a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30528">issues.joomla.org/tracker/joomla-cms/30528</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30528">issues.joomla.org/tracker/joomla-cms/30528</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
