### PR TITLE
[4.0] Fix client filter after publishing a module

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #33891.

### Summary of Changes
Append client_id to the redirection link to solve issue #https://github.com/joomla/joomla-cms/issues/33891

### Testing Instructions
1. Install Joomla 4 nightly build
2. Look at https://github.com/joomla/joomla-cms/issues/33891 , confirm the issue
3. Apply patch, confirm the issue sorted.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8239fd3c3b59afc17411b5f771b65afa0a4fefe8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33892">issues.joomla.org/tracker/joomla-cms/33892</a>.</sub>

**Comment by sandewt** [comment]
I can NOT confirm this issue in Windows 10, browsers: Google Chrome, MS Edge and Firefox.

Version: Joomla! 4.0.0-beta8-dev Development

**Comment by joomdonation** [comment]
@sandewt You need to update to Joomla 4 nightly build to see this issue.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8239fd3c3b59afc17411b5f771b65afa0a4fefe8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33892">issues.joomla.org/tracker/joomla-cms/33892</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33892">issues.joomla.org/tracker/joomla-cms/33892</a>.</sub>

**Comment by sandewt** [comment]
>@sandewt You need to update to Joomla 4 nightly build to see this issue.

@joomdonation, Indeed

**Comment by alikon** [comment]
just for curiosity what pr did the regression ? @joomdonation

**Comment by joomdonation** [comment]
@alikon Could not be sure 100% as I haven't checked it yet. It is very likely it from my other PR https://github.com/joomla/joomla-cms/pull/33763 . Hope nothing else is broken now.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
