### PR TITLE
[a11y] Add background color to invalid input

### PR DESCRIPTION
**Pull request by brianteeman**
Currently on any form that is submitted with an invalid field we get visual markup of a red border around the field and red text for the label
### Before PR
screenshotr11-33-49

You can see that there is a message block at the top and that the fields with invalid input have a red border.

Now look at the same screenshot without any colour.

screenshotr11-33-49

As you can see, in this simulation, it is much harder now to see which fields have invalid input.

### after PR
After adding a background colour to the field that matches the colour of the message it is much easier for someone who cannot see colour to find the fields with invalid data

screenshotr11-36-49

screenshotr11-36-49

An alternative approach would be to apply the background to the field and label but this would require extensive changes to our markup.

### CODE REVIEW

**Comment by brianteeman** [comment]
better images

**Comment by brianteeman** [comment]
Maybe the css change should have been in https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/forms.less#L367

@C-Lodder @ciar4n please advise

**Comment by C-Lodder** [comment]
You can add the background to the HTML5 invalid pseudo tags if you like, but as Joomla adds an actual class (`.invalid`), I don't think `:invalid` is ever used. Also, we don't use HTML5 validation if I'm not mistaken.

Other than that, this seems fine to me

**Comment by dgt41** [comment]
@brianteeman @C-Lodder there was a decision in the London sprint to keep the old validation and not force the HTML 5 for b/c convenience reasons. So yes the :invalid is not used

**Comment by dgt41** [comment]
Plz ignore me, I love thought this was against j4

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7724d11ed4c6a3cf03414a289ab5fd69a082480c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on 7724d11ed4c6a3cf03414a289ab5fd69a082480c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
@rdeutz do you want this to be part of 3.7.0 or should we move this to 3.7.1 ?

**Comment by C-Lodder** [comment]
@zero-24 if it's an a11y related PR...this should go in asap.

**Comment by infograf768** [comment]
This can't break anyhting and looks good. Agree to merge in 3.7.0

**Comment by zero-24** [comment]
I agree too but it is up to the release leader to decide which PRs going to be merged in RC Version (were we usualy only merge critial patches)

**Comment by rdeutz** [comment]
not a fan, it makes it hard to see the difference between a field with an error and a disabled field. We exchange on confusing situation with another

**Comment by infograf768** [comment]
Hmm... You are right.

**Comment by brianteeman** [comment]
We rarely have disabled fields.  I chose a bad example to screenshot. Better to be confused between an invalid field and a disabled field than not to be able to see the disabled field at all.

**Comment by rdeutz** [comment]
We have already more than one way to inform the user that there is a problem. If the argument is that people can see the bold border, so we need to change the background, it is even more confusing because this would mean these people are not able to see the difference between a error field and a disabled field.

I am not convinced that this change will make the situation better. 

Changed the state to needs review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by brianteeman** [comment]
Another option is to add an icon (warning symbol) in the field as well as or instead of the background

**Comment by C-Lodder** [comment]
@rdeutz - It really helps with those who are colour blind. Also bare in mind that some forms from 3PD's may be Ajax (no refresh) driven, therefore the user may not see any alerts.

**Comment by C-Lodder** [comment]
Have also just had confirmation from a friend who's colour blind, he has said the darker inputs are far easier to distinguish

**Comment by brianteeman** [comment]
@rdeutz remember that the background is not the only way to identify the error. We already have the error messages which are a11y valid we just need to add additional help to make it easier to locate the named fields. That really raises the a11y validation

**Comment by brianteeman** [comment]
Can we please merge this. It is an a11y improvement and while we are still on bs2 its the best that can be done in a fully b/c manner

**Comment by angieradtke** [comment]
A good compromise could be adding an icon and changing the color:
label.invalid:before
	{
	content: "\48";
	display:inline-block;
	margin-right:3px;
	font-family: 'IcoMoon';
}
	
	input.invalid {
 	border: 1px solid #9d261d;
	background: #f2dede;
 }

**Comment by brianteeman** [comment]
That would introduce more q11y issues as many screen readers will read out the value of the icon

**Comment by ciar4n** [comment]
Personally I think this PR is fine the way it is. An issue exists and this PR addresses it. An alternative is to increase the invalid border width but I think given the choice I would choose the current background color change.

**Comment by angieradtke** [comment]
Hi Brain, 
screenreader-user  are not able to get the value of content filled in with :before and  :after

**Comment by ciar4n** [comment]
@ylahav You might have some input here?

**Comment by brianteeman** [comment]
> screenreader-user are not able to get the value of content filled in with :before and :after

That is not universally true across all supported browsers

**Comment by rdeutz** [comment]
I still think this is only a half backed solution for a problem, it only changes the area where we put the confusion, before required field with not required field, after required field with disabled fields. I thing the second one is worse than the first one. Adding the icon seems to me a good way to have a better chance to spot the difference between required field with disabled fields.

**Comment by angieradtke** [comment]
Hi Brian,
interesting,   do you know which screenreader  in combination with which browser can interpret generated content? If this is  for most of the screenreaders true, the icon solution can really be  a problem.

**Comment by brianteeman** [comment]
Not sure but i know that why bootstrap 3 does not use that method and instead uses specific markup (sr-only) to hide the icons displayed with invalid fields

**Comment by angieradtke** [comment]
ah ok , maybe we should check this before.

**Comment by tonypartridge** [comment]
To me this is much better, an Icon to the right will suffice.. but that's providing the disabled user can see it clearly and understand it. Changing the color of an entire background is more noticeable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on f3ec7a402c4cdc4a1bc65cbf629e964e0b3855e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on f3ec7a402c4cdc4a1bc65cbf629e964e0b3855e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15245">issues.joomla.org/tracker/joomla-cms/15245</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
