### PR TITLE
[4.0] 3.9.14 merge

### PR DESCRIPTION
**Pull request by wilsonge**
Merges 3.9.14 into the 4.0-dev branch.

I haven't ported the alpha ordering from https://github.com/joomla/joomla-cms/pull/26747/files - it's a trivial fix for someone to do at a later point compared to the amount of work I had to try and figure out ordering it (@brianteeman if you want a free one after this is merged)

https://github.com/joomla/joomla-cms/pull/20225 I don't believe we need to port this one as it's about normalising the bootstrap styling to a non-bootstrap env - but I might be wrong on that.

## Testing Instructions
The usual navigate around everywhere and check nothing is broken.

### CODE REVIEW

**Comment by brianteeman** [comment]
let me know when it is merged and i will do the sort

i agree about #20225

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 03fa087faa9d151adca3a904df7271cfa6a29024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28227">issues.joomla.org/tracker/joomla-cms/28227</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 03fa087faa9d151adca3a904df7271cfa6a29024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28227">issues.joomla.org/tracker/joomla-cms/28227</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28227">issues.joomla.org/tracker/joomla-cms/28227</a>.</sub>

**Comment by astridx** [comment]
I applied the patch, made a new installation, npm ci and deleted the autoload_psr4.php file. After that I navigated around. I found nothing broken.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
