### PR TITLE
Add privacy plugin for exporting consent data, enable actionlogs privacy plugin by default

### LINKED ISSUE #22720: [com_privacy] A user is removed, but his consents still have Personal Data in them
### Steps to reproduce the issue

Joomla 3.9 with all new features enabled

User "me@phil-taylor.com" registers
User "me@phil-taylor.com" consents to the privacy policy in his profile

User "me@phil-taylor.com" requests a REMOVE request
He Confirms it with a token from the email
The admin sees this, and clicks the X to delete all his data
The admin sets the status to COMPLETED

### Expected result

All Personal Identifying data is removed from the consent

### Actual result

The username is obfuscated 
The user id remains
**The IP address and the user agent of the browser is left in the body of the consents**

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #22708

### Summary of Changes

- Adds a privacy plugin to export user data from the `#__privacy_consents` table
    - This does not add the remove logic that would close #22720
- Enables the "Privacy - Action Logs" plugin by default, there is no reason it shouldn't be

### Testing Instructions

- Apply patch, ensure new plugin is installed and enabled, log a consent for the user who you will eventually be exporting data for, create an export request for that user, export their data, check the XML includes the consents

### Expected result

Consents included in export

### Actual result

Consents not included in export

### Documentation Changes Required

N/A, we don't have each individual plugin documented

### Stuck Between A Rock And A Hard Place

This is introducing a new plugin well after feature and language freeze for 3.9.  So we have a few options:

- Ship it in 3.10 (SemVer)
- Ship it in 3.9.1 (not SemVer but should be in core anyway)
- Ship it in 3.9.0 without translation requirement

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
approve languge strings

**Comment by alikon** [comment]
> Ship it in 3.9.0 without translation requirement

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d0c99099ceb6be7b638e2a3b7623be11c741a5de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22749">issues.joomla.org/tracker/joomla-cms/22749</a>.</sub>

**Comment by alikon** [comment]
guess we should add a similar one for `#__privacy_requests` table ?

**Comment by infograf768** [comment]
> Ship it in 3.9.0 without translation requirement

If merged, it will anyway be ported to crowdin and TTs will have to translate.
As we also have https://github.com/joomla/joomla-cms/pull/22752 , this means that TTs would have to touch their packs in any case.

That's only 3 strings.

**Pull request merged**
