### PR TITLE
Vote button missing default styling in 3.5.1

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#### Summary of Changes

added btn-default to the "rate" button to provide default bootstrap styling in 3.5.1
#### Testing Instructions

create a article that has voting turned on.
inspect the "rate" button.  You'll see that there is no default styling.
image

install the patch and you will see the styling added... and button will take on the default color style for 
buttons.
image

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i can't see any visual change in protostar after PR. But i can see the new css class.

**Comment by SharkyKZ** [comment]
Is this meant for future Joomla versions in case a new Bootstrap version is bundled? Because `.btn-default` class doesn't exist in Bootstrap v2 currently included in Joomla.

**Comment by brianteeman** [comment]
This PR is wrong as it is using a non existent class. That why @andrepereiradasilva couldn't see any change. 

Check the bootstrap docs :)

**Comment by N6REJ** [comment]
sorry my bad.. I'm so used to bs3 never dawned on me bs2 would change the name of that single button class when all the rest are the same LOL... 
it might be nice to leave it as bs3 prep but I understand if you want to close it brian. .sorry @andrepereiradasilva

**Comment by brianteeman** [comment]
Sorry but closing this

**Pull request closed without merging**
