### PR TITLE
Incorrect check for response header Oauth2 Client

### PR DESCRIPTION
**Pull request by AteDev**
In Oauth2 Client, there is an incorrect check when we want to get access token back from http post.
Some time (maybe all time) there is charset added in the content-type contained in reponse header.
## How to test

You can download and install this component [here](https://github.com/AteDev/joomla-components-test/tree/PR-7110)
You need to edit this file: [controller](https://github.com/AteDev/joomla-components-test/blob/PR-7110/site/controllers/test.php#L64-L67) to add your client ID/Secret from your linkedin app
If you dont use localhost remove/comment [this line](https://github.com/AteDev/joomla-components-test/blob/PR-7110/site/controllers/test.php#L75)
- Go to yourdomain/index.php/test
- Click "Sign in with Linkedin", apply app, you will see the return token from linkedin (incorrect array)
- Apply patch, repeat steps and you will see perfect array.
## PS

I tested whith the Linkedin api, this add in content-type "application/json;charset:utf8"

### CODE REVIEW

**Comment by zero-24** [comment]
@AteDev Thanks for your PR. Just to make travis happy see here: https://github.com/AteDev/joomla-cms/pull/1

>Will add a custom component to help try it out later...

If you have one ready please make a comment so all gets notified that you have on. As only on changing the comment we don't get a notification. Thanks :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7110">issues.joomla.org/joomla-cms/7110</a>.</sub>

**Comment by AteDev** [comment]
Added component to help test (finally got time ...), sorry for this hard test :)

**Comment by conconnl** [comment]
@AteDev I tried to test this but your test scenario is not working.
The error I get is that the redirect URI is incorrect, whatever I config and test can't seem to get through the first part to generate the incorrect array error.

Please describe a complete test scenario<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7110">issues.joomla.org/joomla-cms/7110</a>.</sub>

**Comment by izharaazmi** [comment]
I have tested this item :white_check_mark: successfully on e98f8df56fe1f1dee5c37443a7b9eb8a097bce9f<br /><br />Omg! Too much work to test this :P

I received the following response without this patch:
```
Array
(
    [{"access_token":"XXXXXX","expires_in":5183484}] => 
    [created] => 1467196746
)
```

After the patch:

```
Array
(
    [access_token] => XXXXXX
    [expires_in] => 5182960
    [created] => 1467197270
)
```

The response header content type is indeed `application/json;charset:utf8`

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7110">issues.joomla.org/joomla-cms/7110</a>.</sub>

**Comment by izharaazmi** [comment]
@conconnl You need to add this `http://localhost/~izhar/staging/index.php?option=com_test&task=test.network` url to the Authorized Redirect URLs at LinkedIn dev console.

Change the host and joomla path appropriately.

**Comment by conconnl** [comment]
Found the problem, sef is by default enabled.
Them you will get other URLs when I disabled it i could start the test with the test component.

Before patch i got:
array(2) { ["{"access_token":"AQWokNE7VFc746UHNuQzg_Ygbc8BsEFEG66Lrj5KPWGM_ievtdZRbCwajlWVbNZH8GFcZ0NvRE-JgzlZ-4GI3rQa4Gd0UtLdRKr2wIMHOM-MhTRGZWtP2AwaglkbT241fAxMYKk8NHh5QLKhRcjdY6yiN0S2GVUvVajIfUfamF1Gn38nlf0","expires_in":5183731}"]=> string(0) "" ["created"]=> int(1467239441) } 

After patch i got:
array(3) { ["access_token"]=> string(179) "AQXSUJxZwgRZi1jkG7lD3wEL02p9FFPbgNat03pW5mADVht9VV75bzF4EJQd2ma9LyXAnJXYv8X_RVXKC5b4xEYVbW5hyOGglypddf173umlmtQZamLH6_GVjH4KEZscwa6O69ifqXAtU5Yg7J4u3NJ8C2RGZgg4c7s5DPSfoKSMTll3DZs" ["expires_in"]=> int(5183863) ["created"]=> int(1467239309) } 

Is this correct?

**Comment by izharaazmi** [comment]
Yes that's right.

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on e98f8df56fe1f1dee5c37443a7b9eb8a097bce9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7110">issues.joomla.org/joomla-cms/7110</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7110">issues.joomla.org/joomla-cms/7110</a>.</sub>

**Pull request merged**
