### PR TITLE
[4.0] Toggle Button [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Change a hard coded string to a translatable string
Remove a hard coded string that was incorrect and not needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9c4109a003e31344a2e7f8bde42f10ac4349e416<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22429">issues.joomla.org/tracker/joomla-cms/22429</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 9c4109a003e31344a2e7f8bde42f10ac4349e416<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22429">issues.joomla.org/tracker/joomla-cms/22429</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
