### PR TITLE
[4.0] Views UI overflow fixed

### PR DESCRIPTION
**Pull request by ThisIsFaar**
Pull Request for Issue #32820 .

### Summary of Changes

manage users section is fixed, now any number of columns can be added without worsing UI.

### Before Fix

Before

### After Fix

After

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on be23d924c8765e1bc6cc54a6f96796c8dca0ce9e<br /><br />Works also on list-views for articles, categories.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34387">issues.joomla.org/tracker/joomla-cms/34387</a>.</sub>

**Comment by brianteeman** [comment]
This applies to all views not just users - is that intentional ?

Please try to do this without using inline styles

**Comment by Abernyte-Git** [comment]
I can still get one break point where the horizontal scroll bar appears.  Is this expected behaviour? If yes I can agree a successful test.
screen shot 2021-06-04 at 07 25 14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34387">issues.joomla.org/tracker/joomla-cms/34387</a>.</sub>

**Comment by ThisIsFaar** [comment]
> This applies to all views, not just users - is that intentional ?
> 
> Please try to do this without using inline styles

**I also thought the same but then I applied to all the views because,**

**The Problem:** currently manage users fields have lots of columns which was the fault of overflow as all the columns will not fit under the parent div.

So Why I don't apply this fix only for the manage users part?
**here's the reason:**
1. maybe in future updates if any other views also got more columns then this issue will come again in the story.
2. not only in future updates, let's just take an example If any user using some plugin that will add/update columns for the functionality/required purpose to any of the views, then this issue will also currently faced by those users.

and about Inline CSS, I think that for just a single property Inline is the best, or else I have to declare and apply with class or id

**Comment by ThisIsFaar** [comment]
> I can still get one break point where the horizontal scroll bar appears. Is this expected behaviour? If yes I can agree a successful test.
> screen shot 2021-06-04 at 07 25 14
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/34387](https://issues.joomla.org/tracker/joomla-cms/34387).

can you please describe a bit more, means draw some arrows for your issue on the ss, because I don't get your point.

**Comment by dgrammatiko** [comment]
Just add the `overflow: scroll;` here: https://github.com/joomla/joomla-cms/blob/1d0510539f501e79b3836e1a548430e615c7a53a/administrator/templates/atum/scss/blocks/_global.scss#L118-L122

**Comment by brianteeman** [comment]
inline styles are wrong for many reasons. not least of which is that they are very difficult to override

**Comment by ThisIsFaar** [comment]
> inline styles are wrong for many reasons. not least of which is that they are very difficult to override

Yes, I totally agree. thanks for reminding me.

**Comment by ThisIsFaar** [comment]
> Just add the `overflow: scroll;` here:
> 
> https://github.com/joomla/joomla-cms/blob/1d0510539f501e79b3836e1a548430e615c7a53a/administrator/templates/atum/scss/blocks/_global.scss#L118-L122

hello @dgrammatiko, @brianteeman  thank you for the help, I have done the changes, now I have to make another PR, or I can edit this PR. sry, it sounds silly but I am currently in the learning stage of the PullRequest Scenario.

**Comment by drmenzelit** [comment]
You can make new commits to this PR directly. Maybe you should change the title of the PR if you are changing all views and not only users.

**Comment by ThisIsFaar** [comment]
@drmenzelit, @brianteeman @dgrammatiko  I have done changes, but continuous-integration/drone/pr shows `build is failing` what mistake I am doing?

**Comment by dgrammatiko** [comment]
Check the logs: https://ci.joomla.org/joomla/joomla-cms/44832/1/20

Also please read https://github.com/joomla/joomla-cms/blob/4.0-dev/build/README.md

The order of the declarations is important, lint the file `npm run lint:css -- --fix`

**Comment by ThisIsFaar** [comment]
@drmenzelit, @brianteeman @dgrammatiko I have done the changes, please review!

**Comment by Quy** [comment]
There are horizontal/vertical scrollbars that don't do anything.

34387-vertical

34387-horizontal

**Comment by ThisIsFaar** [comment]
> There are horizontal/vertical scrollbars that don't do anything.
> 
> 34387-vertical
> 
> 34387-horizontal

Those horizontal/vertical scrollbars are responsible for the Inner/Main Container to be scrollable flow.

scrollbars reason

**Comment by brianteeman** [comment]
If there is now overflow then they should not be displayed

**Comment by ThisIsFaar** [comment]
@dgrammatiko @brianteeman @drmenzelit can anyone explain the steps/stages in "pull request to be merged".

**Comment by ThisIsFaar** [comment]
> If there is now overflow then they should not be displayed

Okay, I will try to fix this!

**Comment by noxidsoft** [comment]
I like the scroll-bar solution, why would we hide columns, how do we know they exist if they are hidden on smaller screens?

**Pull request closed without merging**
