### PR TITLE
TinyMCE builder: Make sure that the Public group used only once

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #13344 .

### Summary of Changes
When add new Set it will be assigned to nothing when the Public group already in use

### Testing Instructions
Try create new Set and make sure there no error when select `usergroup`.

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on dc3691c47d449d064968fd890fcaa4c83b471486<br /><br />Patch ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13434">issues.joomla.org/tracker/joomla-cms/13434</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on dc3691c47d449d064968fd890fcaa4c83b471486<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13434">issues.joomla.org/tracker/joomla-cms/13434</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13434">issues.joomla.org/tracker/joomla-cms/13434</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz @wilsonge 
Please merge as we have other stuff to do on this feature

**Pull request merged**
