### PR TITLE
Remove Space in value of JHELP_MENUS_MENU_ITEM_PRIVACY_CREATE_REQUEST

### PR DESCRIPTION
**Pull request by imanickam**
Pull Request for Issue # https://issues.joomla.org/tracker/joomla-cms/22658

### Summary of Changes
File: en-GB.ini
Location: \administrator\language\en-GB

Current Language String:
JHELP_MENUS_MENU_ITEM_PRIVACY_CREATE_REQUEST=" Menus_Menu_Item_Privacy_Create_Request"

Expected Language String:
JHELP_MENUS_MENU_ITEM_PRIVACY_CREATE_REQUEST="Menus_Menu_Item_Privacy_Create_Request"

Without the change (ie. with the leading space in the language value), Runtime Exception would occur in the Help screen.

Removing the leading space in the language value will display the correct Help screen.

### Testing Instructions

(i) New Menu Item
(a) Create a new menu item of the type Create Request (This menu item type is under the group Privacy)
(b) After choosing the menu item of the type Create Request, in the resultant screen (Menus: New Item) click on the button Help

(ii) Existing Menu Item
(a) Open a menu item of the type Create Request for Edit
(b) In the resultant screen (Menus: Edit Item) click on the button Help

In both the cases (i) and (ii) the following Help screen with the error will show, as seen in the section Actual result.

### Expected result

correct_help_screen_after_removing_leading_space_in_language_value

### Actual result

error_help_screen_with_leading_space_in_language_value

### Documentation Changes Required

Due to the leading space in the language string value, the Help screen URL created is:
https://help.joomla.org/proxy?keyref=Help39:%20Menus_Menu_Item_Privacy_Create_Request&lang=en

This URL would result in:
RuntimeException
Error fetching page from MediaWiki API.

With the leading space removed in the language string value, the Help screen URL created is:
https://help.joomla.org/proxy?keyref=Help39:Menus_Menu_Item_Privacy_Create_Request&lang=en

The URL would result in:
Menus Menu Item Privacy Create Request

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 709866a921894915fb93b0ca96e6d30849d68bc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22658">issues.joomla.org/tracker/joomla-cms/22658</a>.</sub>

**Comment by infograf768** [comment]
Obvious error. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22658">issues.joomla.org/tracker/joomla-cms/22658</a>.</sub>

**Comment by infograf768** [comment]
@imanickam 
Please inform TTs of this change.

**Comment by imanickam** [comment]
Done.

**Pull request merged**
