### PR TITLE
Allow tags to appear below and article when setting split or below is…

### PR DESCRIPTION
**Pull request by ot2sen**
… selected and all info box items set to not show.

### CODE REVIEW

**Comment by sovainfo** [comment]
To avoid showing tags both above and below suggest to use the code below instead:

`<?php if ($info == 1 || $info == 2)) : ?>`
`<?php if ($useDefList) : ?>`
`     <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>`
`   <?php endif; ?>`	
`  <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>`
`    <?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>`
`    <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>`
`  <?php endif; ?>`
`<?php endif; ?>`

Obviously, it must be properly indented, strangely enough it is to difficult for github to respect indentation in the code.

**Comment by brianteeman** [comment]
Please update with full testing instructions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9105">issues.joomla.org/joomla-cms/9105</a>.</sub>

**Comment by sovainfo** [comment]
Test instructions:
Create several tags
Create an article with those tags assigned
Create a menu item for that article
Verify the setting of infoblock as above,split and below
Hide all infoblock settings but tags
Verify the setting of infoblock as above, split and below
When tags are shown as expected depending on above, split and below even when none of the othe settings are shown report an successful test in issues.joomla.org

Note: infoblock set to split means tagsto be shown below.

**Comment by ot2sen** [comment]
Thanks @sovainfo for the suggestion and the testing instructions :)
I was looking at the upper part seeing it was outside the condition but didn´t pay attention to its own condition. Perhaps they should follow same approach and let the lower tags check if info is 1 or 2 similar to checking if it is 0 at top?

Something like:
	<?php if ($info == 1 || $info == 2 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

**Comment by ot2sen** [comment]
Sorry, I am slow, you did already add that check. Thanks again :)
Will see if I can redo the PR without getting in conflict

**Comment by ot2sen** [comment]
More detailed testing instructions:

**What I did:**
1. Set all info box items to off (Hide or No) in the Content->Articles->Options
1.b Set the Option for 'Position of article info' to 'Above'
2. Create an article and set all info box items to use global
3. Create tags and assign to the article
4. Create a menu item, single article, and set info box items to global, and try the 3 different settings for 'Position of article info'
4.1 Set 'Position of article info' to 'Above'
4.2 Set 'Position of article info' to 'Below'
4.3 Set 'Position of article info' to 'Split'
 
**What happened:**
For case 4.1 the tags appear at top
For case 4.2 no tags appear
For case 4.3 no tags appear

**What should have happened:**
For case 4.1 the tags appear at top
For case 4.2 the tags appear below
For case 4.3 the tags appear below

Apply the patch and you should see this happen now.

**Other information:**
Issue has been reported in forum and fb group more times and also reported in the following issue
https://github.com/joomla/joomla-cms/issues/8438

**Comment by genesisfan** [comment]
@test successfully tested.

**Comment by ot2sen** [comment]
Thanks for testing @genesisfan  :)

Perhaps you should also login to https://issues.joomla.org/tracker/joomla-cms/9105 and have the successful test recorded using the 'Test' button, to have it show that there is 1 successful test now.
See: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by brianteeman** [comment]
@ot2sen I just manually marked @genesisfan as a successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9105">issues.joomla.org/joomla-cms/9105</a>.</sub>

**Comment by ot2sen** [comment]
Thanks @brianteeman

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 74cf84e1373434d650c765e330173a07063959f4<br /><br />Took me a while to work this out as it worked ok if you had author or category set to show but I can now confirm the issue and the fix - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9105">issues.joomla.org/joomla-cms/9105</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9105">issues.joomla.org/joomla-cms/9105</a>.</sub>

**Comment by wilsonge** [comment]
Mreged - thanks!

**Pull request merged**
