### PR TITLE
Change all JHELP value strings in jooml.ini

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue # .

### Summary of Changes

All of the Joomla 4 Help files have been renamed (moved leaving redirects) so that their titles are the same as the pages they support, except for the Menu Item types where the type is included (being absent in the page might be considered an omission but that is a separate issue).

We have to change the Help file names in the ini files before any more translations are created (there is a full set of Dutch translations). Otherwise the translators will have to create redirect files too.

This pull request changes the file names and should have no visible effect.

The following Keys are omitted because they are not used in Joomla 4:

id,help_key
13,JHELP_COMPONENTS_CACHE_MANAGER_SETTINGS
14,JHELP_COMPONENTS_CHECK-IN_CONFIGURATION
57,JHELP_COMPONENTS_INSTALLER_CONFIGURATION
60,JHELP_COMPONENTS_JOOMLA_UPDATE_CONFIGURATION
61,JHELP_COMPONENTS_MENUS_CONFIGURATION
62,JHELP_COMPONENTS_MESSAGES_CONFIGURATION
80,JHELP_COMPONENTS_SEARCH
81,JHELP_COMPONENTS_SMART_SEARCH_CONFIGURATION
116,JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_ONLINE
120,JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_STATUS
124,JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_UNREAD
143,JHELP_EXTENSIONS_MODULE_MANAGER_SEARCH
185,JHELP_MENUS_MENU_ITEM_SEARCH_RESULTS
203,JHELP_SITE_MAINTENANCE_PURGE_EXPIRED_CACHE

The numbers refer to the sequence numbers in this reference table that shows old an new names:

https://docs.joomla.org/Help4.x:Help_Screens_by_Key

### Testing Instructions

Visit any page and select the Help button

### Actual result BEFORE applying this Pull Request

The Help screen will have the new Title because of the redirect. See the Help URL bar.

### Expected result AFTER applying this Pull Request

No change but now bypassing the redirect. See the URL bar.

### Documentation Changes Required

English documentation is ahead! Translators will need to be aware of this change.

### CODE REVIEW

**Comment by richard67** [comment]
It seems there is something wrong with this PR. It shows conflicting files from the beginning on, see at the bottom of the PR here on GitHub. Maybe the 4.0-dev branch in your repository was out of date or contained already some changes compared to the 4.0-dev branch of the CMS when the branch for this PR was created based on your 4.0-dev branch?

**Comment by richard67** [comment]
@ceford I've allowed myself to solve the conflicting files. Please pull changes from remote to your local git clone if you are working locally on your computer. And please check if your pull request still shows only your changes.

**Comment by ceford** [comment]
> @ceford I've allowed myself to solve the conflicting files. Please pull changes from remote to your local git clone if you are working locally on your computer. And please check if your pull request still shows only your changes.

Thanks for your help. I am using Eclipse. I pulled joomla-origin and pushed (my) origin. Is that what you meant? The pull request looks good. Only the two files I changed are showing.

**Comment by richard67** [comment]
> I pulled joomla-origin and pushed (my) origin. Is that what you meant?

~~Yes.~~

Update 2020-09-23: No, you should have pulled from your origin.

PR looks ok so far.

**Comment by richard67** [comment]
@ceford Due to recently merged PR #30458 your PR got conflicts.

I've solved them here on GitHub and have added the language strings which were added by PR #30458 to your PR here. But it seems these strings still have the old page names as value.

Please pull changes from your origin to your local environment and check and if necessary make corrections.

Thanks in avdance.

**Comment by ceford** [comment]
I have been confused! Pulling but not merging. My remote now has the correct new Help strings to merge. 

After this one I think it is time for me to update to a new version of Eclipse and start again. I guess that also asking for trouble!

**Comment by richard67** [comment]
> My remote now has the correct new Help strings to merge.

@ceford But the strings which came with the last update from 4.0-dev, i.e. added by Brian with his merged PR, still seem to use the old help site scheme, e.g. sting `JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_FRONTEND`. Is that ok?

**Comment by ceford** [comment]
> But the strings which came with the last update from 4.0-dev, i.e. added by Brian with his merged PR, still seem to use the old help site scheme, e.g. sting `JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_FRONTEND`. Is that ok?

Yes - that string is not used. Some others also added by Brian at my request are also unused - superceded by new strings, many changing CONFIGURATION to OPTIONS.

**Comment by richard67** [comment]
> Yes - that string is not used. Some others also added by Brian at my request are also unused - superceded by new strings, many changing CONFIGURATION to OPTIONS.

@ceford Would it make sense then to remove them?

**Comment by ceford** [comment]
My mistake: JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_FRONTEND is used and was using the old file name. I have changed it to the new file name. The file will actually get renamed later today. I think we are good to go.

**Comment by richard67** [comment]
How about the others which were added with Brian's PR?
- JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LOGIN_SUPPORT
- JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_MESSAGES
- JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_POST_INSTALLATION_MESSAGES
- JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_STATUS_USER
- JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_VERSION

Are they all ok?

**Comment by ceford** [comment]
Thank you for being so vigilant. I have changed the strings to the new file names. They were missed because they are not in the master table of help screens used by the Docs team. I have noticed that these strings are not in the API joomla.ini file. I can't image anyone accessing help screens through the api - but should they be there for completeness?

**Comment by richard67** [comment]
> I have noticed that these strings are not in the API joomla.ini file. I can't image anyone accessing help screens through the api - but should they be there for completeness?

No idea. @brianteeman Do you know that?

**Comment by ceford** [comment]
Checked for differences - only those missing strings so made api joomla.ini JHELP strings same as joomla.ini JHELP strings.

**Comment by ceford** [comment]
I guess it is bad form to test my own pull request but I have done so with Patchtester and it works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30712">issues.joomla.org/tracker/joomla-cms/30712</a>.</sub>

**Comment by richard67** [comment]
@ceford It is not bad form to test your own PR, it is even required to do so before proposing a PR. It only doesn't count for the 2 testers criterion, and so no need to and no use in marking the test result for an own PR in the issue tracker. So all ok here.

**Comment by MartijnMaandag** [comment]
I have tested this item :white_check_mark: successfully on 47d99ad6b4174eda119d1713c1c0b4349d0ec7bf<br /><br />I tested this and it took some time (not technical) to find out if it's ok.
It functions.

What I did is:
Dutch language files installed (from https://www.joomlacommunity.nl/downloads/joomla-4/90-nederlands-taalpakket-nl-nl-joomla-4-0-0-beta).
Changed default language into Dutch.
I have translated a screen into Dutch: Articles - Options.
The English version became visible before installing the patch.
After installing the patch nothing changed. I then discovered that the patch was related to the Joomla.ini language file.
After copying all JHELP_ language strings from the English version into the Dutch Joomla.ini file it worked.
My question is: why can these language strings be translated in Crowdin?
All language string with underscores are clear to me, but there are some (like JHELP_CONTENT_ARTICLE_MANAGER = "Articles") that I would translate.
I will create an issue that everything with JHELP_ in Joomla.ini should not be translated in Crowdin.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30712">issues.joomla.org/tracker/joomla-cms/30712</a>.</sub>

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 47d99ad6b4174eda119d1713c1c0b4349d0ec7bf<br /><br />Checked a random selection of help pages where the key has been changed.

All mapped correctly. Great work Cliff.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30712">issues.joomla.org/tracker/joomla-cms/30712</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30712">issues.joomla.org/tracker/joomla-cms/30712</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
