### PR TITLE
Restore Tab functionality in forms with calendars

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #18448 .

### Summary of Changes
Removes the line `document.activeElement.blur();` as discussed and proposed by @dgt41  in referenced issue.

### Testing Instructions
Test with Internet Explorer 11, Edge or ~Safari~ to use the Tabulator key to navigate through a form that contains calendar elements. Eg the article form.

### Expected result
You can navigate without issues

### Actual result
After hitting the calendar field, you start over at the very top of the page. Elements "behind" the calendar are not accesssible anymore.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
With and -out PR can 

- tab through Fields in Article-Publishing-Tab.
- if press "Space" at Calendar-Field, Field opens, after "Tab" or "Escape" Focus is on "Save"-Button.

### System information
3.8.2-rc
Multilanguage Site
macOS Sierra, 10.12.6
Safari 11.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18508">issues.joomla.org/tracker/joomla-cms/18508</a>.</sub>

**Comment by Bakual** [comment]
Please test with IE/Edge then. I haven't tested with Safari myself. That one was mentioned by Dimitris.

**Comment by ghost** [comment]
to be honest: no IE/Edge.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 64adadf6018d7bc17bdb17461a81d2d9a0eefda5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18508">issues.joomla.org/tracker/joomla-cms/18508</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on 001d46f6e0147a44466db41a7378c787744595c9<br /><br />Tested in Edge as requested and works as expected on a Joomla 3.8.2 install<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18508">issues.joomla.org/tracker/joomla-cms/18508</a>.</sub>

**Comment by gwsdesk** [comment]
Tested with IE11 as well as Edge. Works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18508">issues.joomla.org/tracker/joomla-cms/18508</a>.</sub>

**Comment by ghost** [comment]
@Quy can you please retest?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 001d46f6e0147a44466db41a7378c787744595c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18508">issues.joomla.org/tracker/joomla-cms/18508</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by infograf768** [comment]
@mbabker 
Milestone?

**Pull request merged**
