### PR TITLE
[4.0] Refactoring com_finder fields

### PR DESCRIPTION
**Pull request by Hackwar**
This does what it says. Just refactored the code, I did not change anything. Look at the backend of com_finder in the list view, apply the changes and see that nothing changed.

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 5befce29a4aab6c80ea039f9c80351442ba1e529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20791">issues.joomla.org/tracker/joomla-cms/20791</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5befce29a4aab6c80ea039f9c80351442ba1e529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20791">issues.joomla.org/tracker/joomla-cms/20791</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20791">issues.joomla.org/tracker/joomla-cms/20791</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
