### PR TITLE
[4.0][com_fields] - fix save custom field

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23680 .

### Summary of Changes

`modified_time` check added

### Testing Instructions
see #23680

### Expected result
save/create custom field work

### Actual result
error

### CODE REVIEW

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on f4364c0c0751b14e57976b2dbe68aa2e2e2ab94a<br /><br />NB: for some obscure reason, patchtester would not apply this correction, had to add it manually. But it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23689">issues.joomla.org/tracker/joomla-cms/23689</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 @SniperSister RIPS Please

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f4364c0c0751b14e57976b2dbe68aa2e2e2ab94a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23689">issues.joomla.org/tracker/joomla-cms/23689</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23689">issues.joomla.org/tracker/joomla-cms/23689</a>.</sub>

**Comment by laoneo** [comment]
Any idea why this is needed all of the sudden?

**Comment by wilsonge** [comment]
It's probably been there since the start of 4.0 when we did the extra strict rules on sql fields in https://github.com/joomla/joomla-cms/pull/12494 

We had to do similar fixes in various other components at the time

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
