### PR TITLE
[3.x] Adding New article button in category blog layout

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28414

### Summary of Changes
As title says

### Testing Instructions
Create an article blog menu item.
Patch.
Log as a user with create permission for that category in frontend

### After patch
Screen Shot 2020-03-21 at 09 43 37

### CODE REVIEW

**Comment by alikon** [comment]
i don't know why js drone AT complains but looking at the current status of all that infrastructure .....
who cares..... surely i don't

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4ee2d3c4c0e4eb4a0369a56467f5dc06581aa047<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28429">issues.joomla.org/tracker/joomla-cms/28429</a>.</sub>

**Comment by alikon** [comment]
please @drjjw  test this

**Comment by infograf768** [comment]
Re-started drone...

**Comment by alikon** [comment]
we cannot stay with this current AT status,
i'm complaining as my usual, but please prove me that i'm wrong

**Comment by infograf768** [comment]
drone ok now

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 4ee2d3c4c0e4eb4a0369a56467f5dc06581aa047<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28429">issues.joomla.org/tracker/joomla-cms/28429</a>.</sub>

**Comment by jwaisner** [comment]
RTC
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28429">issues.joomla.org/tracker/joomla-cms/28429</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by ghost** [comment]
Why adding new features bugs or intended behavior in joomla 3 is strange and this PR will create a lot of confusion for joomla users **at least make this as an option** 

Not Removing New article button in category list layout but Adding New article button in category blog layout will create a lot of disapintment in joomla

See the joomla problems here #28513 #28509

**Comment by ghost** [comment]
This PR should be release blocker , should be reopen its not ready this solved issue #28414 created issue #28514 issue should be reopen or will create a lot of disapintment in joomla 

this is BC issue couse this will break a lot of existing lyouts

**Comment by Bakual** [comment]
@Milglius Please stop it. This PR can't be a release blocker since it is merged and there is no issue to solve.

**Comment by ghost** [comment]
will be very unpleasant surprise for joomla 3.9.17 users!

Bakual At least make this 2 issues as an option? Couse This will break lyout of many joomla sites if these are not optional So this issue is BC issue.

 #28514 this New article button in the botom should be removed in joomla 3.9.17 couse this button creates confusion and breaks joomla sites layout.

**Comment by HLeithner** [comment]
Lock down see https://github.com/joomla/joomla-cms/issues/28514#issuecomment-605900545

**Pull request merged**
