### PR TITLE
[3.10] [PHP 8.1] Fix UriHelper Automatic conversion of false to array

### PR DESCRIPTION
**Pull request by beat**
Fixes `Deprecated: Automatic conversion of false to array is deprecated in libraries/vendor/joomla/uri/src/UriHelper.php on line 50`

Pull Request for Issue # none, directly fix proposal.

### Summary of Changes

Another PHP 8.1 warning fix.

### Testing Instructions

Just review code would be enough as it's obvious PHP 8.1 issue and fix.

Open admin aera in PHP 8.1, find this warning.

### Actual result BEFORE applying this Pull Request

`Deprecated: Automatic conversion of false to array is deprecated in libraries/vendor/joomla/uri/src/UriHelper.php on line 50`

### Expected result AFTER applying this Pull Request

Not that warning anymore.

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f591bc87bd29e7e5dc42346691099ebc6753de1<br /><br />Code review. Maybe not the most elegant way to fix it, having that check inside the loop, but it works and is safe and so ok for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36774">issues.joomla.org/tracker/joomla-cms/36774</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8be1c238b1592b9b894e15f7fe8f6f40a16353dc<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36774">issues.joomla.org/tracker/joomla-cms/36774</a>.</sub>

**Comment by beat** [comment]
> I have tested this item white_check_mark successfully on [7f591bc](https://github.com/joomla/joomla-cms/commit/7f591bc87bd29e7e5dc42346691099ebc6753de1)Code review. Maybe not the most elegant way to fix it, having that check inside the loop, but it works and is safe and so ok for me.

Thank you @richard67 for the reviews and feedback. After 2nd thought, found and committed a way more elegant fix proposal.

Actually the function definition itself isn't elegant, as it's returning `array|bool`. It could have returned an empty array instead of bool. But that was before PHP was moving to strict types.

The really elegant fix would be to change the API and return an empty array instead of bool false, and as as `(bool) [] === false` it would be staying compatible, but would represent strictly an API change looking at the phpdoc bloc.

**Comment by richard67** [comment]
> Actually the function definition itself isn't elegant, as it's returning `array|bool`. It could have returned an empty array instead of bool. But that was before PHP was moving to strict types.
> 
> The really elegant fix would be to change the API and return an empty array instead of bool false, and as as `(bool) [] === false` it would be staying compatible, but would represent strictly an API change looking at the phpdoc bloc.

Yeah, we have to live with that mess, but as far as I know it shall be cleaned up with 5.0, and that will be next year. So there is light at the end of the tunnel (I hope it's not a train) :-)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8be1c238b1592b9b894e15f7fe8f6f40a16353dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36774">issues.joomla.org/tracker/joomla-cms/36774</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36774">issues.joomla.org/tracker/joomla-cms/36774</a>.</sub>

**Comment by zero-24** [comment]
This here is a change in a composer dependency so this PR should be send against the framework's [1.x branch](https://github.com/joomla-framework/uri/tree/1.x-dev) from where we would take it back down to the CMS.

**Comment by beat** [comment]
> This here is a change in a composer dependency so this PR should be send against the framework's [1.x branch](https://github.com/joomla-framework/uri/tree/1.x-dev) from where we would take it back down to the CMS.

Done here: https://github.com/joomla-framework/uri/pull/30

Letting you merge and/or close this PR once the framework-PR is merged.

**Comment by zero-24** [comment]
Let us close here and once @nibra did the upstream merge and version release we can pull the changes in with an composer update.

**Pull request closed without merging**
