### PR TITLE
[4.0] Fix blog sampledata plugin

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #22919

### Summary of Changes
Telling the blog sampledata plugin to keep its mouth shut when it doesn't have anything to say.

### Testing Instructions
Test that both the blog and the multilingual sampledata can be installed

### Expected result
Both work

### Actual result
Blog one works
Multilingual one stops after step 3

### Documentation Changes Required
None

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on db4e3bb3320c5ff1d6b58af44eadf314f1963496<br /><br />It indeed solves installing multilingual sampledata.

Note: The success response is not displayed (step8)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22937">issues.joomla.org/tracker/joomla-cms/22937</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Comment by Chacapamac** [comment]
Sorry to ask but Newbie here, when you fix something like that, how do I fix my actual test site. Reinstall ?, Update? Not sure How ?

**Comment by Bakual** [comment]
You wait for the next release (Joomla ~3.9.1~ 4.0 Alpha 6 in that case) or apply the PR using the Patchtester (https://docs.joomla.org/Component_Patchtester_for_Testers).

**Comment by Chacapamac** [comment]
Thank’s Bakuai, I’m testing Joomla 4 alpha5-dev taken from —> 
https://developer.joomla.org/nightly-builds.htm

And I add theCustom url —> https://update.joomla.org/core/nightlies/next_major_list.xml in my update options ?

**Comment by Bakual** [comment]
4.0 is not for production yet at all. The upgrade option isn't guaranteed to work. So in this case, best bet would be to use the nightly builds and install fresh.

**Comment by Chacapamac** [comment]
No, it don’t seem to work, I try to reinstall the nighty builds, It didn’t work ....
— I See Thank

**Comment by Bakual** [comment]
Nightly builds are generated nightly. This PR was merged only 4 hours ago. So you need at least wait till tomorrow till it will show up in the ngihtly 😄

**Comment by mbabker** [comment]
Nightlies are on a cron job to be built at 02:00 UTC daily.  So they truly are "nightly" builds and not continuously regenerated each time a commit is pushed to one of the active development branches.

**Comment by Chacapamac** [comment]
Thanks mbaker - Got it, I remark that the nighty build date is always today, I wasn’t so sure.
Great !

**Comment by Chacapamac** [comment]
Thanks Bakuai — Installing Now! 
Now I just need to understand how can I help more and how to use this forum.

**Pull request merged**
