### PR TITLE
Jagatheeswar

### PR DESCRIPTION
**Pull request by jagatheeswar**
Pull Request for Issue # .

### Summary of Changes

added a single word.

### Testing Instructions

no need to test.

### Actual result BEFORE applying this Pull Request

Ready to install Joomla?

### Expected result AFTER applying this Pull Request

Are u ready to install Joomla?

### CODE REVIEW

**Comment by brianteeman** [comment]
I am sure that you didnt intend to change 106 files

**Comment by jagatheeswar** [comment]
> I am sure that you didnt intend to change 106 files

yes sir. but i dont know how it changed can u highlight my mistake please.

**Comment by brianteeman** [comment]
From what I can see you are attempting to change the readme.md file for joomla 4. To do this you must first be on the joomla 4 branch.

Secondly it looks as if the change you want to make is 

> Are u Ready to install Joomla?

Not only is this a pointless change it is not correct as "u" is not a real word

Thirdly if you look even closer you will see that there is a text only version of the readme file as well and any changes should be made in both files

**Comment by jagatheeswar** [comment]
> From what I can see you are attempting to change the readme.md file for joomla 4. To do this you must first be on the joomla 4 branch.
> 
> Secondly it looks as if the change you want to make is
> 
> > Are u Ready to install Joomla?
> 
> Not only is this a pointless change it is not correct as "u" is not a real word
> 
> Thirdly if you look even closer you will see that there is a text only version of the readme file as well and any changes should be made in both files

ok sir. I  will try another time, sir. i wish to participate in GSOC but all I have is average skills learnt on my own. i did this pull request just for a practice.  i will correct those as I progress. thanks for your feedback sir.

**Pull request closed without merging**
