### PR TITLE
[4.0] com_newsfeeds blank state

### PR DESCRIPTION
**Pull request by brianteeman**
See #33264 for instructions but this time for newsfeeds and not content

This PR requires the code from #33264 to be merged first - specifically the change in libraries/src/MVC/Model/ListModel.php

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3629b02ab8e86f7c61bf0d34925f5904c0e787f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33268">issues.joomla.org/tracker/joomla-cms/33268</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 3629b02ab8e86f7c61bf0d34925f5904c0e787f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33268">issues.joomla.org/tracker/joomla-cms/33268</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33268">issues.joomla.org/tracker/joomla-cms/33268</a>.</sub>

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
