### PR TITLE
[3.10] Fix non-core extension check

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Using element alone is not reliable.

### Testing Instructions

Copy a template. Name it `highlight`.
Go to Joomla! Update. Set custom update channel with https://update.joomla.org/core/nightlies/next_major_list.xml URL.
Check for Joomla! updates.
Inspect pre-upgrade entries.

### Actual result BEFORE applying this Pull Request

Template entry is not shown.

### Expected result AFTER applying this Pull Request

Template entry is shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6f4db3610f85b6df63c2049713ff195c064b1db4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31226">issues.joomla.org/tracker/joomla-cms/31226</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6f4db3610f85b6df63c2049713ff195c064b1db4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31226">issues.joomla.org/tracker/joomla-cms/31226</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31226">issues.joomla.org/tracker/joomla-cms/31226</a>.</sub>

**Comment by zero-24** [comment]
Will be merged into 3.10.0-alpha4 meaning right after 3.10.0-alpha3 is relased. Thanks @SharkyKZ

**Review by zero-24 — APPROVED** [review]

**Comment by zero-24** [comment]
Merging thanks @SharkyKZ 👍

**Pull request merged**
