### PR TITLE
Execute sql uninstall query (if exists) on extension install abort

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.

### Summary of Changes

Currently when a extension install is aborted and the install sql query already run we get a broken install.
The extension is uninstalled but the database tables will stay in joomla.

This PR proposes to change that by adding a step to rollback the sql (if an uninstall sql exists).

### Testing Instructions

1. Code review
2. Install this broken [com_test.zip](https://github.com/joomla/joomla-cms/files/673284/com_test.zip) extension  that install with a db table called `#__test`.  Notice you get the extension install rollback but you stay with the `#__test` table in the database
3. Manually delete the `#__test` table
4. Apply patch
5. Repeat step 2 and notice now on failure the `#__test` table is also removed.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by frankmayer** [comment]
I haven't tested this yet, but one question comes to mind:
What happens if an extension is installed on top of the same? I am thinking of updating an extension by installing it on top of itself. 
If that "update" fails, wouldn't it destroy for example the data of the previously working extension?

**Comment by andrepereiradasilva** [comment]
that's why i putted the if 
https://github.com/joomla/joomla-cms/pull/13376/files#diff-b88334a2e44587a12ed5fed7beb8bd1eR481

**Comment by frankmayer** [comment]
I have tested this item :white_check_mark: successfully on f50416456ac1598cf55421acd1860a4a30f0433d<br /><br />Done code review.

Note: I also tested installing the extension completely (by removing the exception) and the re-installing the broken one (with the addition of an exception in the `update` method). The existing table stayed intact, as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13376">issues.joomla.org/tracker/joomla-cms/13376</a>.</sub>

**Comment by ggppdk** [comment]
> That's why i putted the if ($route === 'install'
https://github.com/joomla/joomla-cms/pull/13376/files#diff-b88334a2e44587a12ed5fed7beb8bd1eR478
> But please test that scenario also

Exactly my fear it would be destructive, i will test too

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f50416456ac1598cf55421acd1860a4a30f0433d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13376">issues.joomla.org/tracker/joomla-cms/13376</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13376">issues.joomla.org/tracker/joomla-cms/13376</a>.</sub>

**Pull request merged**
