### PR TITLE
[4][com_newsfeed] hits must be 0 on new item

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue (https://github.com/joomla/joomla-cms/pull/40741#issuecomment-1586135574) .

### Summary of Changes
set  0  for hits  on new item

### Testing Instructions
use postgresql to replicate
create a newsfeed

### Actual result BEFORE applying this Pull Request
error on postgresql

### Expected result AFTER applying this Pull Request
mysql & postgresql both work

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by Kaushik1216** [comment]
I have tested this item :white_check_mark: successfully on 74784d94ebc14e882a941241a61f3f20d968402d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 74784d94ebc14e882a941241a61f3f20d968402d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by HLeithner** [comment]
> Does this mean we are not calling check on new items?

I looked at the execution pipeline and it should trigger the check function in AdminModel::save() at line 1251.

btw. all other components I checked use the check function to set the hit count so this pr is not the best way to fix it.

**Comment by richard67** [comment]
> > Does this mean we are not calling check on new items?
> 
> I looked at the execution pipeline and it should trigger the check function in AdminModel::save() at line 1251.
> 
> btw. all other components I checked use the check function to set the hit count so this pr is not the best way to fix it.

Hmm, maybe the `if (is_null($this->hits))` in the check function is the problem? Maybe it should be an `if (!isset($this->hits))`?

**Comment by laoneo** [comment]
Didn't realize that the code was moved out of the check function. I would say that `if (!$this->hits)` is enough in the check function. @alikon can you revert the change and update the original if statement to not catch `NULL` values only?

**Comment by wilsonge** [comment]
> update the original if statement to not catch NULL values only

If you do that you'll reset the hits every time you update the item. Postgres presumably isn't treating the value as null or something?

**Comment by laoneo** [comment]
I didn't mean every not null value, if you read my whole comment then I do suggest something like `if (!$this->hits)

**Comment by alikon** [comment]
anyway...

check now please 😛

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5a19dc027fd48f79a35e5c91b507e3c7dd9b66d2<br /><br />Newsfeed can be added on postgres<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by laoneo** [comment]
@Kaushik1216 can you test this one again?

**Comment by Kaushik1216** [comment]
I have tested this item :white_check_mark: successfully on 5a19dc027fd48f79a35e5c91b507e3c7dd9b66d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40758">issues.joomla.org/tracker/joomla-cms/40758</a>.</sub>

**Comment by obuisard** [comment]
Thank you Nicola @alikon !

**Pull request merged**
