### PR TITLE
[4.3] Colour fields doc blocks

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to fix a copy paste error in the doc blocks for these two layouts

code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 23e7ed4b0a96c76a8b8efa3f089652f9af71865f<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41128">issues.joomla.org/tracker/joomla-cms/41128</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 23e7ed4b0a96c76a8b8efa3f089652f9af71865f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41128">issues.joomla.org/tracker/joomla-cms/41128</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41128">issues.joomla.org/tracker/joomla-cms/41128</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman

**Pull request merged**
