### PR TITLE
[4.0] Fix query when searching items in backend

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes condition in query when searching for items. Before patch, `OR` is used as outer glue for search conditions. With patch outer glue is changed to `AND`.

### Testing Instructions

Enter some keywords in search form and use filters in these views in backend:

CSP Reports
Modules
Redirect Links
Template Styles
Templates
User Group Debug
User Debug
User Notes

### Expected result

Items are filtered by filters and keywords.

### Actual result

Items are filtered by filters or keywords.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Where do I find "User Debug" and "User Group Debug"?

**Comment by SharkyKZ** [comment]
When viewing users/groups click the icon in Permissions column.

**Comment by richard67** [comment]
Ah, yes, I remember. Thanks for the reminder.
Will test tonight after work, German time. When I tested last night I got an error about missing bind variable when testing template styles without this PR applied. I think this will not be fixed with this PR. Maybe you can check that?

**Comment by SharkyKZ** [comment]
Looking into it.

**Comment by SharkyKZ** [comment]
Test PR #26990 please.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ebf8b56fd6718be9d3d93e8e95b10f764c2a9b58<br /><br />
- CSP Reports: No change, worked before and works with this PR. Reason: The critical "orWhere" was the last possible where clause for filtering.

  But the change of this PR makes it safe in case if processing of some new filter will be added after that to the php source.

- Modules: This PR fixes the described error.
  
  Hint for other testers: This case has to be tested with the filter by language, because this is the only one which comes after the critical "orWhere".

- Redirect links: Same as for CSP Reports above.

- Template styles: Same as for CSP Reports above.

  Hint for other testers testing with patchtester: If you hit a 500 error, reason might be that the branch of this PR is not up to date with latest merge of PR #26990 4.0-dev.

  In this case either wait until @SharkyKZ has updated the branch for this PR here to latest changed in 4.0-dev, or apply the typo correction ":menuiteid" -> ":menuitemid", too, in attition to the changes in this PR here.

  With patchtester you can't do that because both PRs modify the same file.

- Templates: Can't really test because having only 1 template of each kind admin and site, but code review looks good.

  Result should be same as for CSP Reports above, i.e. no change but safer for future extensions.

- User Group Debug: This PR fixes the described error.

- User Debug: This PR fixes the described error.

- User notes: This PR fixes the described error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26984">issues.joomla.org/tracker/joomla-cms/26984</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ Too late for testing PR #26990 ... was already merged when I was back from work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26984">issues.joomla.org/tracker/joomla-cms/26984</a>.</sub>

**Comment by richard67** [comment]
@infograf768 Could you test this PR here? It is related to other stuff we recently had with filtering in backend lists.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7ae62e168f67d523cf41553d47b0027215bbdb7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26984">issues.joomla.org/tracker/joomla-cms/26984</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26984">issues.joomla.org/tracker/joomla-cms/26984</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
