### PR TITLE
Fix https://github.com/joomla/joomla-cms/issues/15569

### PR DESCRIPTION
**Pull request by fevangelou**
Pull Request for Issue #15569 

### Summary of Changes
Fixed attribute checks.

### CODE REVIEW

**Review by hikashop-nicolas — APPROVED** [review]
As mentioned here https://github.com/joomla/joomla-cms/issues/15569#issuecomment-297327773 I have tested the change and confirm that it fixes the problem.

**Comment by PhocaCz** [comment]
Tested and working OK:

Hi, confirmed:
before the change:
Before change
after the change:
After change

**Comment by wilsonge** [comment]
Merging with two good tests. Thanks guys!

**Comment by ggppdk** [comment]
Yes, seems to be working properly for me too

**Comment by dgt41** [comment]
@ggppdk @wilsonge @fevangelou unfortunately there is one more bug here:
these 2 lines https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L805-L806
needs to be moved before https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L804

Or we have:
```js
		if (this.params.showsTodayBtn) {
			row = createElement("div", this.wrapper);
			row.className = "buttons-wrapper btn-group";
```

and should be:
```js
		row = createElement("div", this.wrapper);
		row.className = "buttons-wrapper btn-group";
		
                if (this.params.showsTodayBtn) {
```

Will make PR tomorrow, unless someone else is faster

**Pull request merged**
