### PR TITLE
[4][CLI] boot com_content from console

### PR DESCRIPTION
**Pull request by alikon**
Create a console plugin that boot the com_content  component and run it from terminal

ie. something like 
```php
$content = Factory::getApplication()->bootComponent('com_content')->getMVCFactory();
$model = $content->createModel('Article', 'Administrator',['ignore_request' => true]);
$result = $model->save($article);
```

### Summary of Changes

- ~~added the `getUserState()` method to the ConsoleApplication.php~~
- don't check session from cli
- early return from Webauthn plugin  when from console

### Testing Instructions
- download this silly example  [plg_console_lorem.zip](https://github.com/joomla/joomla-cms/files/7839093/plg_console_lorem.zip)  wich fetch a lorem ipsum from https://loripsum.net and create an article
- the plugin source code is available here https://github.com/alikon/testcom/tree/main/plugins/console/lorem
- install & enable it & set parameters (like category and user)
- run from terminal  `php cli/joomla.php lorem:ipsum`

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

no error in console and article created

### References
#36568, #36332, #35818 

cc: @wilsonge  @laoneo  @anibalsanchez

### CODE REVIEW

**Comment by wilsonge** [comment]
Ok so webauthn looks fine. But where else is the user state being used - i don't particularly like having to implement that in the consoleapplication class

**Comment by alikon** [comment]
the main point is we want  the console app like 1st citizen ?
we want the console application able to re-use existing CMS code or not ?

i've shared the plugin console code already  maybe i've made something wrong there ??
https://github.com/alikon/testcom/blob/main/plugins/console/lorem/src/Extension/LoremIpsumCommand.php

**Comment by laoneo** [comment]
If you have `'ignore_request' => true` then the populateState function should not be called. On other places the userstate should not be called.

**Comment by wilsonge** [comment]
I don't have the ability to test right now - I'll give it a test when I get home but @laoneo is right about the theory of how this should work

**Comment by alikon** [comment]
as you can see i already have set  `['ignore_request' => true]`

```php
$content = Factory::getApplication()->bootComponent('com_content')->getMVCFactory();
$model = $content->createModel('Article', 'Administrator',['ignore_request' => true]);
$result = $model->save($article);
```

**Comment by laoneo** [comment]
And where is the user state requested?

**Comment by alikon** [comment]
even then the `setUserState()` is not a method of ConsoleApplication  what i'm missing ?

**Review by wilsonge — APPROVED** [review]

**Comment by alikon** [comment]
let's see what kind of thumb i'll collect  cc: @SharkyKZ

**Comment by alikon** [comment]
closed by mistake i suppose

**Pull request closed without merging**
