### PR TITLE
Coding style - PHP code tag and control structures II

### PR DESCRIPTION
**Pull request by marcochirienti**
### Summary of Changes

Removed unnecessary spaces after PHP code opening tag.
Removed unnecessary spaces before PHP code closing tag.
Added a white-space before PHP code closing tag where missing.
Fixed style for control structures alternative syntax.
Added a semicolon at the end of statement where missing. 

### Testing Instructions

Code review.

### Documentation Changes Required

None.

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]
Good work :+1:

**Comment by marcochirienti** [comment]
Thank you.

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 848570aedfb91f1a435d885ef6da34deffa10c08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13149">issues.joomla.org/tracker/joomla-cms/13149</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 848570aedfb91f1a435d885ef6da34deffa10c08<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13149">issues.joomla.org/tracker/joomla-cms/13149</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13149">issues.joomla.org/tracker/joomla-cms/13149</a>.</sub>

**Comment by rdeutz** [comment]
@marcochirienti could you have a look at the conflicts, thanks

**Comment by marcochirienti** [comment]
It should be OK now.

**Review by zero-24 — APPROVED** [review]
:+1:

**Comment by zero-24** [comment]
Merged Thanks!

**Pull request merged**
