### PR TITLE
[4.0] Prevent updating current registration date/last visit date

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #24780 .

### Summary of Changes
Prevent updating registration date using browser's inspector via HTML.

### Testing Instructions
Go to Users > Manage
Edit a user.
Use browser's inspector to change value of registration date/last visit date.
Save.
Registration date/last visit date updated.
Apply PR.
Repeat above steps.
Registration date/last visit date not updated.

### CODE REVIEW

**Comment by brianteeman** [comment]
This only addresses one of the fields I can still change the other readonly date field

image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6ded8a95556146d7c343160d19b22eecf7e0c44f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27328">issues.joomla.org/tracker/joomla-cms/27328</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 3c8bceb5b50e40c739ad429ee5d52c26c73496de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27328">issues.joomla.org/tracker/joomla-cms/27328</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
