### PR TITLE
[4.0] Remove redundant words (cont)

### PR DESCRIPTION
**Pull request by brianteeman**
In #18852 I removed the words just, simply and easily as they are redundant words and subjective.

I then broke that by using the word "simply" in the skipto plugin - oops

This simple PR fixes that

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 21f055a89a0c5e6f612ab29a9e291a9bd8c9ce2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26852">issues.joomla.org/tracker/joomla-cms/26852</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21f055a89a0c5e6f612ab29a9e291a9bd8c9ce2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26852">issues.joomla.org/tracker/joomla-cms/26852</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26852">issues.joomla.org/tracker/joomla-cms/26852</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
