### PR TITLE
Fixed small typos in months of Joomla core extension

### PR DESCRIPTION
**Pull request by pe7er**
I noticed that in the list of Extensions (**Extensions: Manage**) the "Multilingual Associations" has the wrong date "Januar 2017". 

Furthermore some "Joomla! Project" extensions have **abbreviated month names**, while the majority has full written month names. 

This small PR fixes that.

### Testing Instructions
The Extension: Manage shows the information from the #__extensions table. Upon installation the information from the XML is stored in the manifest_cache field of that #__extensions table.
To see the result of this patch, apply this patch before installing Joomla.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 03afb35f7ca21cc10cdbbeca83cde11030902a10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23552">issues.joomla.org/tracker/joomla-cms/23552</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 03afb35f7ca21cc10cdbbeca83cde11030902a10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23552">issues.joomla.org/tracker/joomla-cms/23552</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23552">issues.joomla.org/tracker/joomla-cms/23552</a>.</sub>

**Comment by pe7er** [comment]
Thanks for testing @alikon & @infograf768 !

**Pull request merged**
