### PR TITLE
[4.1] Language string not parsed

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request to fix two unparsed language strings "JLIB_APPLICATION_ERROR_MODEL_CREATE" in administrator/components/com_scheduler/src/Scheduler/Scheduler.php

### Testing Instructions
Please check PR via code inspection

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6ecfe75d6eb292a186f4fca5fab9e41cb04b9ee3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37665">issues.joomla.org/tracker/joomla-cms/37665</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on f133be1974df0d76f8af823ecac39452d66cc6b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37665">issues.joomla.org/tracker/joomla-cms/37665</a>.</sub>

**Comment by akshitrattan** [comment]
I have tested this item :white_check_mark: successfully on f133be1974df0d76f8af823ecac39452d66cc6b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37665">issues.joomla.org/tracker/joomla-cms/37665</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37665">issues.joomla.org/tracker/joomla-cms/37665</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
