### PR TITLE
Correct afterLoad time in Joomla Debug Console

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR corrects the `afterLoad` time and memory usage in the debugger `Profile Information` block.
As it is now Joomla is returning a not real page generation time because it's not counting the load time (files loaded in index.php or administrator/index.php).

Before PR:
image

After PR:
image
#### How to test
1. Apply this patch.
2. Turn on the debug in global config and the debug system plugin.
3. Test any page in frontend or admin and check if the `afterLoad` time and memory usage is in the debugger `Profile Information` block.

### CODE REVIEW

**Comment by mbabker** [comment]
The same should be done for the memory use.

**Comment by andrepereiradasilva** [comment]
Done.

**Comment by alikon** [comment]
tested successfully

**Comment by andrepereiradasilva** [comment]
@alikon please mark as "Tested successfully" in "Joomla! Issue Tracker" https://issues.joomla.org/tracker/joomla-cms/8888 (after login the "Test this" button appears).
For more information see https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0fe9de3b0b914518fadaf2416747315a2f265314<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8888">issues.joomla.org/joomla-cms/8888</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 0fe9de3b0b914518fadaf2416747315a2f265314<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8888">issues.joomla.org/joomla-cms/8888</a>.</sub>

**Comment by 810** [comment]
@test +1

**Comment by andrepereiradasilva** [comment]
@810 please mark as "Tested successfully" in "Joomla! Issue Tracker" https://issues.joomla.org/tracker/joomla-cms/8888 (after login the "Test this" button appears).
For more information see https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 0fe9de3b0b914518fadaf2416747315a2f265314<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8888">issues.joomla.org/joomla-cms/8888</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot wake up!

**Comment by dgt41** [comment]
@mbabker 😂

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/8f7604b993a624547f4e8f9011bdbed9db4878e6

**Pull request closed without merging**
