### PR TITLE
[4.0] com_redirects alerts

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the message to say that the plugin is enabled etc. Just keep the message that says the plugin is _not_ enabled

Pull Request for Issue #27378 
Prevents this from happening
redirect

### CODE REVIEW

**Comment by infograf768** [comment]
This kills the alert for the disabled `Collect URLs` option.

Screen Shot 2019-12-30 at 12 12 31

Please re-add that single one.

**Comment by brianteeman** [comment]
No. for the same reason as the plugin enabled.

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 8db9823e1ea286ed54acb8ba32520006d41f80dc<br /><br />

Setting as unsuccessful as we need an alert when the option is disabled, evidently not when it is enabled. Similar to this patch but only showing when the plugin is enabled.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27380">issues.joomla.org/tracker/joomla-cms/27380</a>.</sub>

**Comment by brianteeman** [comment]
Why do we need it? Where else do we have a similar alert?

**Comment by infograf768** [comment]
This was an improvement that was welcomed in former versions. Why killing it? Why lose what works and is useful to the users? Just display it when the plugin is enabled and the option is not set and we are done.
Not everyone will know or remember that option which is essential for this component specifically.

**Comment by brianteeman** [comment]
You can make the same argument for lots of things - it is a useless argument. You don't agree - thats fine. You dont have to agree with everything

**Comment by HLeithner** [comment]
I also mentioned it's not useless but it shouldn't be an alert.

A (constant) section about the component like in j3 which such information would be great.

**Comment by infograf768** [comment]
> A (constant) section about the component like in j3 which such information would be great.

Maybe where we display `No Matching Results` ?

**Comment by brianteeman** [comment]
@HLeithner are you going to start displaying similar messages then for components where fields are not enabled etc
@infograf768  No because you may have results.

**Comment by infograf768** [comment]
> No because you may have results.

That is not an issue. We can create a specific method in the model, get its result in template and create a specific div to display it.

**Comment by HLeithner** [comment]
@brianteeman 
> @HLeithner are you going to start displaying similar messages then for components where fields are not enabled etc

Only where it makes sense, we have the same thing in smart search with the search plugins.

image

maybe there are more components or view were a static message makes sense.

**Comment by brianteeman** [comment]
I see that smart search has the same problem with the constantly repeating alert. 

I will look at the static message idea in the morning

Something like this ?

image

**Comment by HLeithner** [comment]
Yes something like this

**Comment by brianteeman** [comment]
easy enough

**Comment by brianteeman** [comment]
closing for now - will either reopen with the static message for com_redirect and com_finder or will create a new pr

**Pull request closed without merging**
