### PR TITLE
Add Joomla 3 session namespace to has function

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for login screen on joomla 4 update. Complete the last fix for Joomla update.

### Summary of Changes
Check also the joomla 3 namespace "__default" in the session `has` function.

### Testing Instructions
update from j3.10

### Actual result BEFORE applying this Pull Request
Shows the upgrade login screen on upgrade

### Expected result AFTER applying this Pull Request
No upgrade login screen

### CODE REVIEW

**Comment by HLeithner** [comment]
@toivo can you test this PR please?

**Comment by toivo** [comment]
@HLeithner - "Upade login screen" - a typo?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31575">issues.joomla.org/tracker/joomla-cms/31575</a>.</sub>

**Comment by HLeithner** [comment]
yes, I updated the description

**Comment by toivo** [comment]
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31575">issues.joomla.org/tracker/joomla-cms/31575</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 977b0c65c21ceac6cc481e73bcf87902b3c01606<br /><br />Tested successfully.  Installed 3.9.10 alpha4-dev of 4 December.  Downloaded J4 Beta6-dev of 4 December, expanded, applied PR to session.php and compressed.  Updated 3.9.10 site using Upload & Update.  No upgrade login screen.

Will check if observations like the Options tabs missing during the first back end login session are known issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31575">issues.joomla.org/tracker/joomla-cms/31575</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 977b0c65c21ceac6cc481e73bcf87902b3c01606<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31575">issues.joomla.org/tracker/joomla-cms/31575</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31575">issues.joomla.org/tracker/joomla-cms/31575</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
