### PR TITLE
[5.2] phpcs comments / use statements

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- move use statements out of phpcs disable area
- fix phpcs:enable identifier

### Testing Instructions

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0c6ea05587b3ac4a058dbcb48c69f4693ae7fd55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44194">issues.joomla.org/tracker/joomla-cms/44194</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0c6ea05587b3ac4a058dbcb48c69f4693ae7fd55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44194">issues.joomla.org/tracker/joomla-cms/44194</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44194">issues.joomla.org/tracker/joomla-cms/44194</a>.</sub>

**Comment by brianteeman** [comment]
are we sure we even need to disable phpcs for this? There are a lot of instances where it is not disabled

eg
https://github.com/joomla/joomla-cms/blob/23c750ae288da864fae751ce43aeec4da1ae43ad/administrator/components/com_cpanel/services/provider.php#L7-L13

**Comment by richard67** [comment]
> are we sure we even need to disable phpcs for this? There are a lot of instances where it is not disabled

@brianteeman It is needed when in that file a function is defined or a class. PHPCS say then that you shall not have both in the same file, a statement with side effects like the defined, and definition of a symbol.

**Comment by brianteeman** [comment]
@richard67 Thanks you for the explanation

**Comment by pe7er** [comment]
Thanks @heelc29 !

**Pull request merged**
