### PR TITLE
[4.1] scheduler tasks listview default sort

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Default `list.ordering/direction` of `filter_tasks` doesn't match with `TasksModel`.

Changed default ordering to `a.title asc`

### Testing Instructions

Add two or more task
Check list view (without adjust the filter options)

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
I think ordering by title descending doesn’t really make sense. Either title ascending so you get the alphabetically sorted in the way one would expect it, or by id descending to always get the newest ones at the top regarding when they were created.

**Comment by heelc29** [comment]
> Either title ascending so you get the alphabetically sorted in the way one would expect it […].

I've changed it to `title asc`

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c954b8d0f3485a08147e6cd291248f2ce3e9d765<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37762">issues.joomla.org/tracker/joomla-cms/37762</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on c954b8d0f3485a08147e6cd291248f2ce3e9d765<br /><br />Tested successfully in Joomla 4.1.4-dev of 11 May in Wampserver 3.2.8 with PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37762">issues.joomla.org/tracker/joomla-cms/37762</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37762">issues.joomla.org/tracker/joomla-cms/37762</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
