### PR TITLE
RSS, ATOM fix publish date. Pull to #7392.

### PR DESCRIPTION
**Pull request by wartur**
It's pull to my issue
https://github.com/joomla/joomla-cms/issues/7392

---

Hello.

RSS and ATOM generate problem

"pubDate" is same as "update"

I fixed some files. It's code. My fix mark as ARTUR FIX

Sorry I cant any time for pull.

---

It's fix need for right publish date.
I'm using hootsuite.com for RSS feed for all social accounts from http://goingrus.com/info/en/russia-photo to https://www.facebook.com/goingrus https://plus.google.com/+GoingrusService/posts https://www.facebook.com/palytratravel and other accounts.
Sevice work not correct because update date NOT publish date. I'm using system pulush date and if publish date not set i'm using update date.

### CODE REVIEW

**Comment by zero-24** [comment]
@wartur for the Failed Travis checks see here: https://github.com/wartur/joomla-cms/pull/1 :smile:

**Comment by conconnl** [comment]
@wartur please create a complete test case!
What to-do an expected before patch and after patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7406">issues.joomla.org/joomla-cms/7406</a>.</sub>

**Comment by brianteeman** [comment]
@conconnl @roland-d after a year I think its safe to say that @wartur isnt going to updste this. So we can either close it or create a new PR to address the issues <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7406">issues.joomla.org/joomla-cms/7406</a>.</sub>

**Comment by conconnl** [comment]
I agree, with zero information we cannot test it. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7406">issues.joomla.org/joomla-cms/7406</a>.</sub>

**Comment by brianteeman** [comment]
Closing this as we cant do anything with it. If someone wants to make a new PR etc then it will of course be considered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7406">issues.joomla.org/joomla-cms/7406</a>.</sub>

**Pull request closed without merging**
