### PR TITLE
[4.1] native function invocation and a few commas

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4.0] native function invocation in namespaced file 

code review only

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cbec119bc4cdbf68b143bb507606da9f2ab57582<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36379">issues.joomla.org/tracker/joomla-cms/36379</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cbec119bc4cdbf68b143bb507606da9f2ab57582<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36379">issues.joomla.org/tracker/joomla-cms/36379</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36379">issues.joomla.org/tracker/joomla-cms/36379</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
