### PR TITLE
Remove unused php version check

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #14820 .

### Summary of Changes
We have code in 3.7 still that runs postinstall and checks that you are on a version of php > 5.3.10 and if not gives the following message
> Your PHP Version Will Be Unsupported in Joomla! 3.3

> Beginning with Joomla! 3.3, the version of PHP this site is using will no longer be supported. Joomla! 3.3 will require at least <a href="_QQ_"https://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html"_QQ_">PHP version 5.3.10 in order to provide enhanced security features to its users</a>."

This is now redundant and both the strings and the code \administrator\components\com_admin\postinstall\phpversion.php can be removed now as it is no longer possible to ever get that scenario

This PR removes the unused check and deprecates the language strings (in accordance with current language string policy)

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Review by C-Lodder — APPROVED** [review]

**Comment by brianteeman** [comment]
This PR has been approved by two people - should it not be RTC?

**Comment by wilsonge** [comment]
Approval doesn't mean testing. It's effectively code review which as you like to say is not the same thing as a test (and given half my contributions probably correctly - so no it still needs actual tests)

**Comment by brianteeman** [comment]
It will be very hard to do anything other than a code review as the code is never used

**Comment by Quy** [comment]
@wilsonge  How to test this? 

When I attempted to install Joomla 3.6.5 on PHP 5.3.3, I got this error message so installation halted:
`Your host needs to use PHP 5.3.10 or higher to run this version of Joomla!`

With the following code at the beginning in `index.php`, `administrator\index.php`, and `installation\index.php`. Joomla won't run and you won't see the postinstall message about Joomla! 3.3.
```
define('JOOMLA_MINIMUM_PHP', '5.3.10');

if (version_compare(PHP_VERSION, JOOMLA_MINIMUM_PHP, '<'))
{
	die('Your host needs to use PHP ' . JOOMLA_MINIMUM_PHP . ' or higher to run this version of Joomla!');
}
```

**Comment by brianteeman** [comment]
@quy you cant test  it as its not used

**Comment by wilsonge** [comment]
RTC for 3.7.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14821">issues.joomla.org/tracker/joomla-cms/14821</a>.</sub>

**Comment by brianteeman** [comment]
conflict resolved no need for new tests

**Comment by zero-24** [comment]
@brianteeman i have just fixed the script.php files

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
