### PR TITLE
[4.2] CLI tasks scripts cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
This is part of a series of pr (broken down to smaller ones to make testing easier) that fixes several issues in the cli commands.

Make sure the title is displayed
Make sure the case of the title matches the styleguide
Make sure table column headings match the styleguide

### List tasks
XzLnECGezK

### Run Tasks
TFsilMD9T5

### Change state
N3JC1fMOai

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 917b7da8c7057e1514f16cd03a1c16785bc3e216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38218">issues.joomla.org/tracker/joomla-cms/38218</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 917b7da8c7057e1514f16cd03a1c16785bc3e216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38218">issues.joomla.org/tracker/joomla-cms/38218</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38218">issues.joomla.org/tracker/joomla-cms/38218</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
