### PR TITLE
[5.1] Fix header translation for modal select field

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/42918

### Summary of Changes

Fix header translation for modal select field

### Testing Instructions

Add following field XML, somewhere, example in Custom HTML module.
```xml
<field
  type="ModalSelect"
  name="article"
  label="Article"

  select="true"
  titleSelect="JGLOBAL_SELECT_AN_OPTION"
  urlSelect="index.php?option=com_content&amp;view=articles&amp;layout=modal&amp;tmpl=component"
  clear="true"
/>
```

Then edit the form with it, click "select" button.
Check the dialog heading.

### Actual result BEFORE applying this Pull Request
The heading is untranslated language constant.

### Expected result AFTER applying this Pull Request
The heading is translated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ddceaf058caad9ff8d61f2c5de57b88afe24219<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43878">issues.joomla.org/tracker/joomla-cms/43878</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 1ddceaf058caad9ff8d61f2c5de57b88afe24219<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43878">issues.joomla.org/tracker/joomla-cms/43878</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43878">issues.joomla.org/tracker/joomla-cms/43878</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
