### PR TITLE
spellcheck typo

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to correct a typo on the word spellcheck

### CODE REVIEW

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11043">issues.joomla.org/joomla-cms/11043</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d7b7e194574e51efd79ced21d593570227951194<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11043">issues.joomla.org/joomla-cms/11043</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on d7b7e194574e51efd79ced21d593570227951194<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11043">issues.joomla.org/joomla-cms/11043</a>.</sub>

**Comment by dgt41** [comment]
RTC. Thanks Brian!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11043">issues.joomla.org/joomla-cms/11043</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot

**Pull request merged**
