### PR TITLE
[4.0] Load language files when needed in dispatcher

### PR DESCRIPTION
**Pull request by laoneo**
Load the language in the dispatch function and not before.

Can be merged on review @wilsonge.

### CODE REVIEW

**Comment by wilsonge** [comment]
This actually needs to be moved higher up if we're now going to put the dispatcher in the component container.

**Comment by laoneo** [comment]
Agree, if #19811 get merged, then I will move it up.

**Comment by wilsonge** [comment]
OK Im definitely going to be merging that so I'm just going to close this for now and let's move it to the final correct place once it's merged :)

**Comment by wilsonge** [comment]
Closing this as we've merged #19811 and so this isn't the correct place anymore. Obviously will accept a PR putting it in the new(TM) correct place :p

**Comment by laoneo** [comment]
Having a second look on it. Do we really want to load the language while booting the component? Mostly the language files are needed while dispatching the component. If we load it during boot and do not dispatch the component , the language files are loaded for nothing.

**Comment by wilsonge** [comment]
Yes because if you get a model instance then we still (unfortunately) queue up error messages, so right now we have to I think

**Pull request closed without merging**
