### PR TITLE
Fix for #22935 "cannot delete module position for module"

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #22935

### Testing 

please look #22935 for details

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on f3150527c7f4ea515907bf95b5c25096494bd75a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23052">issues.joomla.org/tracker/joomla-cms/23052</a>.</sub>

**Comment by Fedik** [comment]
I do not know how **drone/travis-ci** failures related to current PR

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f3150527c7f4ea515907bf95b5c25096494bd75a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23052">issues.joomla.org/tracker/joomla-cms/23052</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23052">issues.joomla.org/tracker/joomla-cms/23052</a>.</sub>

**Pull request merged**
