### PR TITLE
[#31144] Added options to include/exclude menu items or components from caching

### PR DESCRIPTION
**Pull request by laoneo**
Se tracker item http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31144

### CODE REVIEW

**Comment by Hackwar** [comment]
I disagree with this PR. I think including the whole menu system already and doing all the routing is already to much work before the caching takes effect. I would not complicate this further. Rather, an extension should be able to prevent the caching from the outside. That however is something that already requires so much logic all over the system, that someone should rather use the normal caching than the page cache.

**Comment by Hackwar** [comment]
In any case, if you want to have this still in Joomla, please create a new PR against staging and resolve the merge conflicts.

**Comment by vdespa** [comment]
After considerable time without update I am marking this issue as "Closed". 

See also @Hackwar comment. Thanks for your work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/1514">issues.joomla.org/joomla-cms/1514</a>.</sub>

**Comment by laoneo** [comment]
Great, spending hours to get it done and then it will be thrown away!

**Comment by brianteeman** [comment]
If you do what was requested last month then it can be reopened. But sadly as it is right now it cant even be tested

**Pull request closed without merging**
