### PR TITLE
[4.0] Frontend Edit Article [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Every field must have a label. This PR ensures that a label is rendered for the text editor. It is not visually displayed as it has a class sr-only so there is no visible change.

If you apply the PR and inspect the source of the edit article page you will see that a label has been added as shown in the screenshot below

image

cc @carcam

### CODE REVIEW

**Comment by sandewt** [comment]
The class below is also added. Is that the intention?

```
<div class="controls">
```

**Comment by brianteeman** [comment]
That is what renderfield does

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 8ec58766bb35c3bea643cdd6f628dc68c8c0bcf0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31539">issues.joomla.org/tracker/joomla-cms/31539</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8ec58766bb35c3bea643cdd6f628dc68c8c0bcf0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31539">issues.joomla.org/tracker/joomla-cms/31539</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 8ec58766bb35c3bea643cdd6f628dc68c8c0bcf0<br /><br />Joomla! 4.0.0-beta6-dev Development [ Mañana ] 27-October-2020 19:54 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31539">issues.joomla.org/tracker/joomla-cms/31539</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31539">issues.joomla.org/tracker/joomla-cms/31539</a>.</sub>

**Comment by Yiannistaos** [comment]
@brianteeman 
The hiddenLabel should be false or true?

```xml
<field
	name="articletext"
	type="editor"
	label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
	hiddenLabel="false"
	buttons="true"
	filter="JComponentHelper::filterText"
	asset_id="com_content"
/>
```

I suppose false, and it will be look like the screenshot below:

screenshot-joomla-cms-4 test-2020 12 03-03_30_00

What do you think?

**Comment by Yiannistaos** [comment]
I have tested this item :white_check_mark: successfully on 8ec58766bb35c3bea643cdd6f628dc68c8c0bcf0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31539">issues.joomla.org/tracker/joomla-cms/31539</a>.</sub>

**Comment by drmenzelit** [comment]
@brianteeman the PR is RTC and I would like to merge it, but there is an open question from @Yiannistaos, can you please answer it? Thanks

**Comment by brianteeman** [comment]
The code is as intended

**Comment by Yiannistaos** [comment]
Ok!

**Comment by drmenzelit** [comment]
Thanks!

**Pull request merged**
