### PR TITLE
Release Blocker: After update to Joomla 3.6 RC fails backend files path

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/10955 .
#### Summary of Changes

fix rtrim if site is in document_root on windows
#### Testing Instructions
- Install site directly in document_root on windows
- Check if back-end works.
- Aplly changes from this PR manualy.
- Check again if the back-end works.

### CODE REVIEW

**Comment by wojsmol** [comment]
@brianteeman IMHO this is relase blocker

**Comment by infograf768** [comment]
Tested on MAMP Macintosh in root, i.e. htdocs and this patch does not create an issue here.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on e34455cd52523766e4da934330bcd1e35404db4a<br /><br />After installation of Joomla 3.6 RC I was unable to see the administrator part, I received a blank page. After applying the patch, the screen is rendered as should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10956">issues.joomla.org/joomla-cms/10956</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on e34455cd52523766e4da934330bcd1e35404db4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10956">issues.joomla.org/joomla-cms/10956</a>.</sub>

**Comment by infograf768** [comment]
RTC and changed title to Release blocker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10956">issues.joomla.org/joomla-cms/10956</a>.</sub>

**Comment by wojsmol** [comment]
@infograf768 see https://issues.joomla.org/tracker/joomla-cms/10956#event-176964 @joomla-cms-bot chaqned status to pending

**Comment by infograf768** [comment]
RTC again...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10956">issues.joomla.org/joomla-cms/10956</a>.</sub>

**Comment by joeforjoomla** [comment]
I have tested this item :white_check_mark: successfully on e34455cd52523766e4da934330bcd1e35404db4a<br /><br />After the change to JUri::root(null, rtrim(dirname(JUri::base(true)), '/\')); 
it works fine again on Windows<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10956">issues.joomla.org/joomla-cms/10956</a>.</sub>

**Pull request merged**
