### PR TITLE
[4.0] com_finder [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #24468

The label existed but it was pointing to an id that didnt exist

This simple PR adds the ID

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on d0d226cbffc6fe18b5042ea7dde2bd94816e4393<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24477">issues.joomla.org/tracker/joomla-cms/24477</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on d0d226cbffc6fe18b5042ea7dde2bd94816e4393<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24477">issues.joomla.org/tracker/joomla-cms/24477</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 please fix rips

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by zero-24** [comment]
New build: http://ci.joomla.org/joomla/joomla-cms/16687

**Comment by brianteeman** [comment]
@zero-24 still fails

**Comment by zero-24** [comment]
Finally rips is happy 👍

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks.

**Pull request merged**
