### PR TITLE
Fix shortDays array order

### PR DESCRIPTION
**Pull request by machadoug**
shortDays array was displaying Monday (Seg) as the first day of the week, however the calendar displays Sunday as the first day, so the shortDays must be changed accordingly.

Pull Request for Issue # .

### CODE REVIEW

**Comment by Bakual** [comment]
Those files are provied by the language teams. 
Pinging @helvecio and @horus68 so they can approve this change and take the changes to his own file. Not sure which one provided the file 😄

**Comment by horus68** [comment]
The change is correct. @Bakual can you please merge this one?
Actually there is only a file for "pt" and "pt-BR"

**Comment by dgt41** [comment]
@machadoug @horus68 @Bakual you can rearrange the array, as it's done here, or change the weekend value in the language xml file (I think is better to keep the array order reflecting the original EN)

**Comment by dgt41** [comment]
I'm referring to this line: https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.xml#L19

**Comment by dgt41** [comment]
Also there is a firstDay: https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.xml#L18
So tweaking these values we can have the same result without rearranging the days array...

**Comment by machadoug** [comment]
@dgt41, actually the value of the `shortDays` array is actually wrong in pt.js file.  It should match the `days` array, regardless of the configuration in the xml file.

In other words, the `days` array position should match the  `shortDays` array position. The changes suggested set Sunday as the first position in both cases.

**Pull request merged**
