### PR TITLE
[4.0] Menu deleted message

### PR DESCRIPTION
**Pull request by brianteeman**
This simple PR corrects that so it says "Menu deleted" and not "Menu type deleted"

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 12ae60d177d3ad2faa7bd049aee2d1bc4efbe39c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26227">issues.joomla.org/tracker/joomla-cms/26227</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97d3deaa4a5c60b00a5c8c35ebb6e23da1160481<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26227">issues.joomla.org/tracker/joomla-cms/26227</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26227">issues.joomla.org/tracker/joomla-cms/26227</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
great

**Pull request merged**
