### PR TITLE
JFILTER-INPUT-CLEANING

### PR DESCRIPTION
**Pull request by Mathewlenning**
Removed a few nested conditionals.

### CODE REVIEW

**Comment by Mathewlenning** [comment]
How do we get TCI to try again?

**Comment by mbabker** [comment]
Ask and thou shall receive (I've restarted it)

**Comment by Mathewlenning** [comment]
Thanks =^D You are quick.

**Comment by Hackwar** [comment]
Seems like your code loops forever at some point.

**Comment by Mathewlenning** [comment]
A the joys of cleaning =^D I'll dig into it tomorrow.

**Comment by Mathewlenning** [comment]
Cleaning up my cleaning up repositories, so please let me know if this has a chance to get merged.

**Comment by Kubik-Rubik** [comment]
Thank you for creating this. It’s been some time since you created this and there are now some merge conflicts that prevent a direct merge. I will close this PR now. If you want to update your PR, then this can be re-opened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6337">issues.joomla.org/joomla-cms/6337</a>.</sub>

**Pull request closed without merging**
