### PR TITLE
Update of less compiler (leafo)

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### B/C

This should be 100% compatible with Bootstrap > 2.3 or any other less files that are using the same notation
#### Testing

Try to compile any less files (other than the ones Joomla is already shipping) and compare it with the previous copy. Should be identical.
It would be nice if you can apply #6979 and try to run generatecss.php, should work fine! Also since to already have applied that patch do some template switching and give to that one as well a response!

PS. ~~There seems to be some border color clash for a sub template of Hathor, that needs some attention.~~
Protostar seems to get one more class for IE10, https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/responsive-utilities.less#L9-L11

### CODE REVIEW

**Comment by mbabker** [comment]
You have to run "composer update leafo/lessphp" and update the Composer
lock file too.  Otherwise things start to get very out of whack.

Run "composer update leafo/lessphp" then "composer install --no-dev" after
changing the version constraint in composer.json.  The second command
uninstalls the dev dependencies that will get pulled in (by design so they
are locked to specific versions for the CI systems).

**Comment by wilsonge** [comment]
Joomla 3.x is IE8 and higher

**Comment by dgt41** [comment]
@wilsonge that is quite a paradox bootstrap 2.x is >IE7 but Joomla is >IE8.
Anyway the extra class comes from bootstrap 2.x mixins which is IE7 compatible, so we either leave it as is, or we touch the bootstrap less

**Comment by dgt41** [comment]
@mbabker done

**Comment by wilsonge** [comment]
https://docs.joomla.org/Joomla_Browser_Support

**Comment by dgt41** [comment]
@wilsonge actually this -ms- class is for IE10: https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/responsive-utilities.less#L9-L11

**Comment by Bakual** [comment]
The reason why we never updated beyong 0.3.9 was the B/C warning for 0.4.0:
http://leafo.net/lessphp/changelog.html
> Warning: this release has some breaking changes. If you the old selector expression syntax (eg. Bootstrap 2.3) then it’s recommended to use 0.3.9.

Interesting that on leafo.net, the latest version still shows as 0.4.0, while the 0.5.0 release is tagged in GitHub since Nov 2014.

**Comment by vess** [comment]
@Bakual Bootstrap moved away from that old selector expression before 0.4.0 even got out, so it should be ok to update our version.

**Comment by Bakual** [comment]
> @Bakual Bootstrap moved away from that old selector expression before 0.4.0 even got out, so it should be ok to update our version.

I have no clue what it refers to. If Bootstrap 2.3.2 doesn't use that selector expression (whatever that is), then I guess we can safely update it.
However according to @nonumber in https://github.com/joomla/joomla-cms/pull/6451#issuecomment-81694814, there are issues with 0.5.0.

**Comment by dgt41** [comment]
@Bakual The errors @nonumber found are already been fixed in this PR (/cms/less/less.php)
> v0.5.0 was not fine. Found issues with it (not inheriting overwritten variables)
Also @vess comment in another workgroup, which pointed to the fix:
> multiple files in a row with the same instance fails... issue https://github.com/leafo/lessphp/issues/594 fix that works is https://github.com/leafo/lessphp/pull/607

**Comment by vess** [comment]
> I have no clue what it refers to. If Bootstrap 2.3.2 doesn't use that selector expression (whatever that is), then I guess we can safely update it.

old: (~".span@{index}") {.span(@index);}
new: .span@{index} {.span(@index);}
https://github.com/lukeapage/bootstrap/commit/6b9bb547bf275d8723d50b16fbb22ba9e334da39

**Comment by Bakual** [comment]
Thanks!

**Comment by roland-d** [comment]
So are we OK to get this thing in or are there B/C concerns?

**Comment by dgt41** [comment]
No B/C break with this

**Comment by roland-d** [comment]
In that case, this needs to be tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7687">issues.joomla.org/joomla-cms/7687</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 657c0276a2cebaebfa68d5ea32852a9159ccee0b<br /><br />Applied the patch and changed the .less files in the isis and the protostar template to monitor the output. After that executed generatecss.php to generate the stylesheets. Everything seems to work and there where no errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7687">issues.joomla.org/joomla-cms/7687</a>.</sub>

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 675a87876d9e19074854a7a44f786f33fc6b9338<br /><br />>=IE10 support has been ended by Microsoft. So we can also end the support for >= J3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7687">issues.joomla.org/joomla-cms/7687</a>.</sub>

**Comment by brianteeman** [comment]
(MS only ended support - they did not stop anyone from using it.)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7687">issues.joomla.org/joomla-cms/7687</a>.</sub>

**Comment by dgt41** [comment]
@RickR2H can you retest this one? Thanks!

**Comment by RickR2H** [comment]
What is the best way to test this? I'll test asap ;)

**Comment by dgt41** [comment]
Just run `php build/generate.php` and see if the css's are all ok

**Comment by RickR2H** [comment]
@dgt41 I'll do that.

Just for my information, why is the LESS compiler there when developers mostly use grunt etc. to compile less?

**Comment by dgt41** [comment]
It has to be php, for the low end servers that don't have grunt etc

**Comment by 810** [comment]
its  ````php build/generatecss.php```` right not  ````php build/generate.php ````

**Comment by dgt41** [comment]
@810 yes you are right!

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 675a87876d9e19074854a7a44f786f33fc6b9338<br /><br />Test was successful!  To test it I added extra styling to the end of the template.less file. Sources are getting compiled nicely!

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7687">issues.joomla.org/joomla-cms/7687</a>.</sub>

**Comment by dgt41** [comment]
RTC then

**Pull request merged**
