### PR TITLE
Fix code comments

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #36152 .

### Summary of Changes
Fix code comments

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 46076f7028abee2d709b5d8629b8dda4a41ba950<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36188">issues.joomla.org/tracker/joomla-cms/36188</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 46076f7028abee2d709b5d8629b8dda4a41ba950<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36188">issues.joomla.org/tracker/joomla-cms/36188</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36188">issues.joomla.org/tracker/joomla-cms/36188</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 46076f7028abee2d709b5d8629b8dda4a41ba950<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36188">issues.joomla.org/tracker/joomla-cms/36188</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 46076f7028abee2d709b5d8629b8dda4a41ba950<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36188">issues.joomla.org/tracker/joomla-cms/36188</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
