### PR TITLE
[4.0] Redis descriptions

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to remove the reference to tooltips (_DESC) strings for the redis cache handler which have already been removed.

Code Review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 19408235d24263c90dc5f01389c5afdde918450c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28184">issues.joomla.org/tracker/joomla-cms/28184</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 19408235d24263c90dc5f01389c5afdde918450c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28184">issues.joomla.org/tracker/joomla-cms/28184</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
