### PR TITLE
Various cosmetic fixes regarding alignment for Extension, Module, Plugin, Language, Template Managers

### PR DESCRIPTION
**Pull request by manojLondhe**
:nail_care: This is a PR for fixing alignment issues for list views from com_installer component.

**Manage view - before**
installer-manage-before
**Manage view - after** 
installer-manage-after

**Update view - before** 
installer-update-before
**Update view - after**
installer-update-after

**Discover view - before** 
installer-discover-before
**Discover view - after** 
installer-discover-after

**Update sites view - before** 
installer-updatesites
**Update sites view - after** 
installer-updatesites-after

### CODE REVIEW

**Comment by brianteeman** [comment]
I agree with the movement of the status column
BUT
To be consistent with the other manager views the columns should be left
aligned (I think status and numeric columns are the only ones that are
currently center aligned). It IS a bug that the columns are currently
centered so instead of making the title center aligned please make the
heading left aligned instead

On 9 July 2015 at 10:30, Manoj L <notifications@github.com> wrote:

> [image: :nail_care:] This is a PR for fixing alignment issues for list
> views from com_installer component.
>
> *Manage view - before*
> [image: installer-manage-before]
> <https://cloud.githubusercontent.com/assets/1375006/8592119/65f0cb9a-264a-11e5-8a16-d7012a914b9b.png>
> *Manage view - after*
> [image: installer-manage-after]
> <https://cloud.githubusercontent.com/assets/1375006/8592117/65ee0f04-264a-11e5-8ed2-a38e612eb33f.png>
>
> *Update view - before*
> [image: installer-update-before]
> <https://cloud.githubusercontent.com/assets/1375006/8592120/65f17b62-264a-11e5-8a33-016f5bd3aa50.png>
> *Update view - after*
> [image: installer-update-after]
> <https://cloud.githubusercontent.com/assets/1375006/8592116/65ed6590-264a-11e5-9785-4b1c263fab46.png>
>
> *Discover view - before*
> [image: installer-discover-before]
> <https://cloud.githubusercontent.com/assets/1375006/8592118/65ef155c-264a-11e5-9b94-12605ddd0ae5.png>
> *Discover view - after*
> [image: installer-discover-after]
> <https://cloud.githubusercontent.com/assets/1375006/8592115/65d67e2a-264a-11e5-91bb-b5984aef93e8.png>
>
> *Update sites view - before*
> [image: installer-updatesites]
> <https://cloud.githubusercontent.com/assets/1375006/8592121/65fb60f0-264a-11e5-9970-927f7bd3c00c.png>
> *Update sites view - after*
> [image: installer-updatesites-after]
> <https://cloud.githubusercontent.com/assets/1375006/8592122/6611e302-264a-11e5-9eaf-8c23353cccb2.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/7384
> Commit Summary
>
>    - com_installer: Various cosmetic fixes regarding alignment
>    - Merge remote-tracking branch 'upstream/staging' into staging
>
> File Changes
>
>    - *M*
>    administrator/components/com_installer/views/discover/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/7384/files#diff-0> (4)
>    - *M*
>    administrator/components/com_installer/views/manage/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/7384/files#diff-1> (30)
>    - *M*
>    administrator/components/com_installer/views/update/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/7384/files#diff-2> (8)
>    - *M*
>    administrator/components/com_installer/views/updatesites/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/7384/files#diff-3> (14)
>    - *M* administrator/language/en-GB/en-GB.com_installer.ini
>    <https://github.com/joomla/joomla-cms/pull/7384/files#diff-4> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/7384.patch
>    - https://github.com/joomla/joomla-cms/pull/7384.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7384>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by manojLondhe** [comment]
There is inconsistency across other manager views as well.
- Module and plugin manager have - status and ID columns center aligned, rest left aligned
- Template Manager: Styles has Default, ID, Location, Template columns center aligned
- Template Manager: Styles have - Location, 	Version, Date, Author center aligned

Similar story for Language Manger as well!

**Comment by brianteeman** [comment]
Yes and they should be fixed ;)

On 9 July 2015 at 10:47, Manoj L <notifications@github.com> wrote:

> There is inconsistency across other manager views as well.
>
>    - Module and plugin manager have - status and ID columns center
>    aligned, rest left aligned
>    - Template Manager: Styles has Default, ID, Location, Template columns
>    center aligned
>    - Template Manager: Styles have - Location, Version, Date, Author
>    center aligned
>
> Similar story for Language Manger as well!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7384#issuecomment-119892533>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by manojLondhe** [comment]
OK, will fix those too keeping only - Status, Default and ID columns center aligned!

**Comment by brianteeman** [comment]
See #6076 for some previous discussion on this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7384">issues.joomla.org/joomla-cms/7384</a>.</sub>

**Comment by manojLondhe** [comment]
Sure! 
Just noticed com_users using class="left" for table headings, but that class does not exist in backend default template CSS, neither does "right".
Using "right" for numerics makes sense[#6076] but that class does not exist in template, so should I stick with "center"?

**Comment by brianteeman** [comment]
I would go with
https://github.com/joomla/joomla-cms/issues/6076#issuecomment-76647779

On 9 July 2015 at 11:09, Manoj L <notifications@github.com> wrote:

> Sure!
> Just noticed com_users using class="left" for table headings, but that
> class does not exist in backend default template CSS, neither does "right".
> Using "right" for numerics makes sense[#6076
> <https://github.com/joomla/joomla-cms/issues/6076>] but that class does
> not exist in template, so should I stick with "center"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7384#issuecomment-119897426>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by manojLondhe** [comment]
OK, but what about "right", "left" classes that don't exists?

**Comment by brianteeman** [comment]
My understanding from the comments in that other thread is that left is the
default for LTR and right is the default for RTL so no class is needed

**Comment by manojLondhe** [comment]
Pushed changes for - Extension, Module, Plugin, Language, Template Managers

**Comment by brianteeman** [comment]
- [X] Extension Manager
- [X] Module Manager
- [X] Plugin Manager
- [X] Template Manager
- [X] Language Manager
- [X] Module Manager
- [X] Installer
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7384">issues.joomla.org/joomla-cms/7384</a>.</sub>

**Comment by genesisfan** [comment]
@test succesfully tested with FF38.0.5. Well done @manojLondhe looks much better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7384">issues.joomla.org/joomla-cms/7384</a>.</sub>

**Comment by larapetersen** [comment]
Tested succesfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7384">issues.joomla.org/joomla-cms/7384</a>.</sub>

**Comment by manojLondhe** [comment]
@genesisfan Thanks!
Thanks guys :)

**Pull request merged**
