### PR TITLE
[4.4] Adminmenu: Toggle for duplicate menus

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #32934 .

### Summary of Changes
When the backend menu is duplicated, the JS to toggle the sidebar doesn't work for the second menu.

### Testing Instructions
1. Create a second menu module in the administrator, assign it to the menu position and select the "Joomla Main Menu" preset for the module.
2. Click on the toggle button to close the sidebar.
3. Click on the "Content" menu item in the second module.

### Actual result BEFORE applying this Pull Request
The sidebar stays closed.

### Expected result AFTER applying this Pull Request
The sidebar opens, like for the menu entries in the first menu module.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
> When the backend menu is duplicated,

If you do this as per the original report by duplicating the existing module then you break accessibility as you have multiple things using the same id

**Comment by brianteeman** [comment]
This may well fix the bug in 4.4 but the js was rewritten for j5.1 (#42784) so it will not be able to be upmerged.

My recommendation would be to close this pr for 4.4 and redo it for 5.1

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on ed76cd4a9440ac904c6f04428f75bfb06d4909ba<br /><br />I confirm that it was a success test for me.

PHP 8.2.17, MySQL 8.0.36
CentOS v7.9.2009 STANDARD kvm cPanel v110.0.24

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43192">issues.joomla.org/tracker/joomla-cms/43192</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on ed76cd4a9440ac904c6f04428f75bfb06d4909ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43192">issues.joomla.org/tracker/joomla-cms/43192</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43192">issues.joomla.org/tracker/joomla-cms/43192</a>.</sub>

**Comment by richard67** [comment]
@Hackwar As @brianteeman correctly mentioned in [his previous comment](https://github.com/joomla/joomla-cms/pull/43192#issuecomment-2033683595), this fix can't be merged up into 5.1-dev as it is because in 5.1-dev the js was refactored. It would need to make the same changes as here but in these 2 lines:
- https://github.com/joomla/joomla-cms/blob/5.1-dev/build/media_source/mod_menu/js/admin-menu.es6.js#L115
- https://github.com/joomla/joomla-cms/blob/5.1-dev/build/media_source/mod_menu/js/admin-menu.es6.js#L121

Could you make a PR for 5.1-dev, too?

**Comment by richard67** [comment]
> Could you make a PR for 5.1-dev, too?
> 
> It needs both, I think, this one here for 4.4-dev and another one for 5.1-dev.

@Hackwar As I did not get any response to my comment, I've decided to create the 5.1-dev PR myself. Thanks for the fix here. PR for 5.1-dev is #43308 .

To all testers: Could you also test my PR #43308 for 5.1? Thanks in advance.

**Comment by richard67** [comment]
@exlemor @fgsw Could you also test my PR https://github.com/joomla/joomla-cms/pull/43308 with the same change for 5.1? Thanks in advance.

**Comment by exlemor** [comment]
Tested #43308 for J5.1.x - thanks @richard67.

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
