### PR TITLE
Update default.php to fix missing space between img attributes

### PR DESCRIPTION
**Pull request by BastianFie**
Pull Request for Issue #14893 .

### Summary of Changes
Added the correct space between the attributes inside the banner elements

### Testing Instructions
Overwrite the default.php in a joomla 3.6.5 with the fixed one. Try the steps from issue #14893 and check the HTML source. The spaces should be now correct. As an additional test you can run an HTML syntax check against the section and it now validated correctly.

### Expected result
img src="banners/banner_example_468x60.gif" alt="486x60" width="486" height="60"/

### Actual result
img src="banners/banner_example_468x60.gif" alt="486x60"width ="486"height ="60"/

### Documentation Changes Required
See source code

### CODE REVIEW

**Comment by brianteeman** [comment]
I ran an html checker BEFORE the pr and didnt reveal any errors

**Comment by brianteeman** [comment]
Are you getting your error on a completely clean install of joomla without any extensions

**Comment by bertmert** [comment]
I don't know if it's really an markup error but would also prefer to remove these spaces (what the PR does):



More consistent and some common regular expressions in 3rd extensions could fail

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 513b9fcd1c0b4ad5ec8b66514a572ae39f177a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14894">issues.joomla.org/tracker/joomla-cms/14894</a>.</sub>

**Comment by brianteeman** [comment]
@bertmert ho can yours be a successful test as your screenshot does not show the original reported issue which is that there is no space between the alt, width and height tags

**Comment by BastianWie** [comment]
The screenshot from bertmert shows the issue and the space between the width and height elements

**Comment by infograf768** [comment]
Indeed, when looking at source, we have extra spaces
```
<div class="banneritem">
																																														<img
						src="http://localhost:8888/trunkgitnew/images/banners/white.png"
						alt="my alt text"
						width ="300"						height ="150"					/>
```
The xtra spaces don't show when using Firebug.

After patch we do get the correct
```
<div class="banneritem">
																																														<img
						src="http://localhost:8888/trunkgitnew/images/banners/white.png"
						alt="my alt text"
						 width="300"						 height="150"					/>
```

Not a big deal. But the PR incorrectly (code style) takes off the space before the `?>`
for all instances of 
```
-								src="<?php echo $baseurl . $imageurl; ?>"
-								alt="<?php echo $alt; ?>"
TO
+								src="<?php echo $baseurl . $imageurl;?>"
+								alt="<?php echo $alt;?>"
```
As these are variables the space does not have to be taken off.

**Comment by BastianWie** [comment]
yes its not a security issue or caused any known "issues". Its only to follow standards and get a cleaner code basis.

**Comment by BastianWie** [comment]
I have tested this item :white_check_mark: successfully on 513b9fcd1c0b4ad5ec8b66514a572ae39f177a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14894">issues.joomla.org/tracker/joomla-cms/14894</a>.</sub>

**Comment by BastianWie** [comment]
@infograf768 There is no change done for the src & alt section by me in my PR. You can check the change history. I fixed only the issue reported here with weigh and height.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14894">issues.joomla.org/tracker/joomla-cms/14894</a>.</sub>

**Comment by infograf768** [comment]
There is a change: I posted it above. You took off some spaces. It is only a code style issue but it is real.
Just copy https://github.com/joomla/joomla-cms/pull/14894.diff in a text editor and you will see.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by rdeutz** [comment]
@infograf768 anything what needs fixing before merge?

**Pull request merged**
