### PR TITLE
[4.0] namespace JHtml

### PR DESCRIPTION
**Pull request by brianteeman**
Fix some missing namespace changes for JHtml

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b89a25afa96beeb3452b34df74c21df5a58b026e<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27366">issues.joomla.org/tracker/joomla-cms/27366</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b89a25afa96beeb3452b34df74c21df5a58b026e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27366">issues.joomla.org/tracker/joomla-cms/27366</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27366">issues.joomla.org/tracker/joomla-cms/27366</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
