### PR TITLE
Remove files that are still there after an upgrade from 2.5 to 3.x

### PR DESCRIPTION
**Pull request by zero-24**
See: https://github.com/joomla/joomla-cms/issues/5326 by @ITPrism 
#### Quote from #5326

```
Hi.
I upgraded my site from J!2.5 to J! 3.3.6 and I did some comparisons with a new copy of Joomla! 3.3.6 to check the differences.

It seems, the process of upgrading misses some things and some files and folders still exist.
I am posting a list of files and folders that still exists.

**Folders**
_/administrator/components/com_config/views_
_/administrator/components/com_config/models/fields_
_/administrator/components/com_config/models/forms_

**The files in that folder**
_/administrator/help/en-GB_

**Files**
_/libraries/joomla/environment/request.php_
_/media/editors/tinymce/templates/template_list.js_

**The plugin Geshi ( plg_content_geshi ) still exists.**
_/plugins/content/geshi_

**SQL**
There is a difference in the definition of the column "**_content_history_options_**" in table "**_#__content_types_**".

After upgrade from J! 2.5 to J!3.3.6 it is **DEFAULT ""**.
After a new installation of J!3.3.6 it is **DEFAULT NULL**.

Regards,
T
```

This handels only the files and folders. I don't know how the sql updates work that need to be added here. Also i don't know what is the correct `NULL` or `""` Thanks.

### CODE REVIEW

**Comment by brianteeman** [comment]
@zero-24 did this get updated I cant tell

**Comment by zero-24** [comment]
oops missed this i will have a look into it now. Thanks @brianteeman

**Comment by zero-24** [comment]
please have a look into it @infograf768 https://github.com/joomla/joomla-cms/commit/97b0a4faaef608334c78cb68ec912e1456245d45

what is about the update SQL?

**Comment by zero-24** [comment]
Closing see: https://github.com/joomla/joomla-cms/pull/6402

**Pull request closed without merging**
