### PR TITLE
[com_associations] Separating in list associations from not associated yet

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #14490

### Summary of Changes
Separating Associated languages from not yet associated ones in the Associations list.

### Testing Instructions
Create a multilingual site and associate some items. Do not associate some items for some content languages.

Before patch
screen shot 2017-03-12 at 15 04 28

After patch
screen shot 2017-03-12 at 15 04 51

### CODE REVIEW

**Comment by brianteeman** [comment]
1. Layout
as you can see from the screenshots the layout looks odd because of the centre alignments - it would probably be easier to read and scan if the layout is left aligned

2. Trashed
I still say it is wrong to display trashed content languages in the list

3. I still say it fails a11y guidelines as you are using colour as a sole indicator but I can see that a11y isnt important to you

**Comment by infograf768** [comment]
I am closing this patch. Issue because of the layout change in managers

**Comment by infograf768** [comment]
Corrected the managers Notice, but I get one in com_associations associations list:
"Notice: Undefined index: link in ROOT/layouts/joomla/content/associations.php on line 19"

If someone has an idea how to solve that.

**Comment by infograf768** [comment]
Trashed issue is a separate issue it seems. 
Will look at it.

**Comment by zero-24** [comment]
@infograf768 

> Corrected the managers Notice, but I get one in com_associations associations list:
"Notice: Undefined index: link in ROOT/layouts/joomla/content/associations.php on line 19"

Can you doube check that you are on the very last version of staging? As line 19 is `</li>` https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/associations.php#L19

**Comment by infograf768** [comment]
@zero-24 
Yep. last version.

**Comment by infograf768** [comment]
yep last version

**Comment by infograf768** [comment]
Trashed Content Languages can't now be used. Thanks @brianteeman for finding that bug.

**Comment by infograf768** [comment]
Patch not totally OK. Closing.

**Comment by infograf768** [comment]
Can be retested. Notice and therefore Layout (and Trashed) solved here:
screen shot 2017-03-12 at 17 05 34

@zero-24

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 5fc3b3034aee0af90bebc5fb1f9539e71d4043e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14530">issues.joomla.org/tracker/joomla-cms/14530</a>.</sub>

**Comment by infograf768** [comment]
If desired, we can also change the colour of the label (below for label-info instead of label-warning ) for the languages not yet associated.
In any case, that column is only shortcuts.

screen shot 2017-03-13 at 08 13 42

@rdeutz ?

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 5fc3b3034aee0af90bebc5fb1f9539e71d4043e5<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14530">issues.joomla.org/tracker/joomla-cms/14530</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz 

2 good testers. RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14530">issues.joomla.org/tracker/joomla-cms/14530</a>.</sub>

**Comment by brianteeman** [comment]
still fails accessibility

**Comment by dgt41** [comment]
My 2c, if you **really** want to improve accessibility you need to add `<span class="sr-only">Indicated language: {{Language}}</span>` next to each flag image, or something similar. (screen readers will read nothing in that column as is)

**Comment by infograf768** [comment]
@dgt41 

Do you speak about the flags or the labeled SEF for the lang?
If about the flags, we get rid of them in
https://github.com/joomla/joomla-cms/pull/14563

**Comment by dgt41** [comment]
Oops, will be a good idea tho to run a screenreader on the page and see what fails...

**Comment by infograf768** [comment]
and all over J, I guess...

**Comment by dgt41** [comment]
true... :(

**Pull request merged**
