### PR TITLE
[#32440] Incorrect position of calendar in Internet Explorer 7-10

### PR DESCRIPTION
**Pull request by piotrmocko**
Currently calendar position offset is get from document.body.scrollTop for IE,
but it not always works. Then offset should be get from: document.documentElement.scrollTop if it is defined

Test instructions with module tester on Code Tracker 
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=32440

### CODE REVIEW

**Comment by zero-24** [comment]
@piotrmocko can you fix the `merge conflicts` ?

**Comment by piotrmocko** [comment]
Yes I can but I do not see here any confilcts. Where do you see those conflicts?

**Comment by zero-24** [comment]
hehe it is not me it is github :smile: 



Here are the commits against the file you touch:
https://github.com/joomla/joomla-cms/commits/staging/media/system/js/calendar-uncompressed.js
and
https://github.com/joomla/joomla-cms/commits/staging/media/system/js/calendar.js

**Comment by josien** [comment]
Could you please add a step-by-step testing procedure, including screen shots with arrows & annotations?
That way the issue + your patch will be easier to test.
Would you be so kind as to respond within 30 days, otherwise this issue will be closed. 
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3079">issues.joomla.org/joomla-cms/3079</a>.</sub>

**Comment by piotrmocko** [comment]
I have just updated compressed file with current code from staging. But I can see merge conflicts still and I do not know what should I do about it. Could you give me some step by step notes?

**Comment by roland-d** [comment]
@piotrmocko I looked at your PR and I see the following errors:

> error: patch failed: media/system/js/calendar.js:1
error: media/system/js/calendar.js: patch does not apply
error: patch failed: media/system/js/calendar.js:1
error: media/system/js/calendar.js: patch does not apply
error: patch failed: media/system/js/calendar.js:1
error: media/system/js/calendar.js: patch does not apply
error: patch failed: media/system/js/calendar.js:1
error: media/system/js/calendar.js: patch does not apply
error: patch failed: media/system/js/calendar.js:1
error: media/system/js/calendar.js: patch does not apply

This means that your calendar.js is not up-to-date with the calendar.js from staging. When I look at a diff from your calendar.js and the staging one, yours seems to be quite a bit smaller while your code change should make it a little longer. You can see the diff here:
https://github.com/piotrmocko/joomla-cms/commit/71645ac8893c7bbd21d8f091c74473c3d265c43f#diff-94ec1cc82f036da484ebdf6f4af1d05b

So if you take the calendar.js from staging and make the necessary change in that file and then commit it to your branch patch-14, the PR should be OK.

Can you give that a try?

**Comment by Kubik-Rubik** [comment]
@piotrmocko Thank you for your contribution. As @roland-d I also still get conflicts but this is not a big problem and I could solve it manually. The problem is how to reproduce your issue. Could you please explain in more detail (step by step) how to see the mentioned problem? Please do it within the next 7 days else I will close this PR. Thank you!

**Comment by piotrmocko** [comment]
Hello,
all instructions are at
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=32440

**Comment by Bakual** [comment]
Please copy the instructions here. JC is halfway dead already :smile:

**Comment by piotrmocko** [comment]
How to reproduce the problem and/or test the patch:
See attached images. Install attached module Calendar Tester. Publish in position debug. Open front-end in Internet Explorer 7 - 10. Scroll down to bottom of page where is calendar field. Click on calendar icon. Calendar would open not next to field but at top of document.

http://joomlacode.org/gf/download/trackeritem/32440/85989/calendar1.jpg/open
http://joomlacode.org/gf/download/trackeritem/32440/85988/calendar2.jpg/open
http://joomlacode.org/gf/download/trackeritem/32440/157639/mod_calendartester.zip

**Comment by Bakual** [comment]
Adding pictures here.
calendar1
calendar2

**Comment by Fedik** [comment]
note: `setFullYear()` already fixed in #4480

**Comment by piotrmocko** [comment]
I have reported it 21 months ago, just test my part of fix and if it will be working then maybe there is someone able to correct my pull request my match staging

**Comment by Kubik-Rubik** [comment]
Please test #7643

**Pull request closed without merging**
