### PR TITLE
[4.0] New banner fails to save

### PR DESCRIPTION
**Pull request by phalouvas**
Pull Request for Issue #23072 

### Summary of Changes
The problem is on file /administrator/components/com_banners/Table/BannerTable
line 204. Change from:
$client = Table::getInstance('Client', NAMESPACE . '\', array('dbo' => $db));
to
$client = new ClientTable($db);

[patch.txt](https://github.com/joomla/joomla-cms/files/2579263/patch.txt)

### Testing Instructions
Create new banner
Put a title
Choose a client.
Save.

### Expected result
To save a new banner on the selected client.

### Actual result
An error has occurred.
0 Call to a member function load() on boolean

### CODE REVIEW

**Comment by richard67** [comment]
Obviously you made this PR against the wrong branch: It should be 4.0-dev, but you made it for staging (which is 3.9)

**Comment by phalouvas** [comment]
>           Obviously you made this PR against the wrong branch: It should be 4.0-dev, but you made it for staging (which is 3.9)

Ooops. Can I change it, or need to create new?

**Comment by SharkyKZ** [comment]
You can change it. Click `Edit` button to the right of the title.

**Comment by ggppdk** [comment]
> Ooops. Can I change it, or need to create new? 

When you click edit button it will allow you edit the title of this PR but also you can change the branch

https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by phalouvas** [comment]
Thanks. I just did.

**Comment by SharkyKZ** [comment]
Change it to `4.0-dev`, not `l10n_4.0-dev`.

**Comment by phalouvas** [comment]
There is no option for 4.0-dev

**Comment by laoneo** [comment]
I guess you somehow screwed up this pr. Probably the best option would be to create a new one.

**Comment by wilsonge** [comment]
You're trying to merge 4.0 from the CMS into another repo. I assume you meant to do a PR from your own fork

**Comment by wilsonge** [comment]
I've manually changed this with https://github.com/joomla/joomla-cms/commit/329fd3b2db7b4da4a36c7c1b214b1bb9e6b638ac

**Pull request closed without merging**
