### PR TITLE
[5.0] fix version

### PR DESCRIPTION
**Pull request by brianteeman**
reverts change made in upmerge #40709

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on da2488c9bb8697d71e211969d91051bc56f0d4a1<br /><br />Tested successfully in Joomla 5.0.0-alpha2-dev of 4 June 4 in Wampserver 3.3.6 using PHP 8.2.6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40713">issues.joomla.org/tracker/joomla-cms/40713</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on da2488c9bb8697d71e211969d91051bc56f0d4a1<br /><br />I had found that, too, and was told it would be fixed anyway with the next release with the version bump, but maybe better to fix it now with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40713">issues.joomla.org/tracker/joomla-cms/40713</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40713">issues.joomla.org/tracker/joomla-cms/40713</a>.</sub>

**Comment by HLeithner** [comment]
that would be automatically updated on the next build...

**Pull request merged**
