### PR TITLE
[4.1]s/similiar/similar

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1dd17fb8e0de0349a474d564a62dae8aa116e957<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36828">issues.joomla.org/tracker/joomla-cms/36828</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1dd17fb8e0de0349a474d564a62dae8aa116e957<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36828">issues.joomla.org/tracker/joomla-cms/36828</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36828">issues.joomla.org/tracker/joomla-cms/36828</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
