### PR TITLE
align icons in mod_login

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
Aligns icons in mod_login

### Testing Instructions
visually inspect icon alignment.
apply patch
verify icons are now aligned.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
none

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 00173ebf595de63ecfca160b88f1e6659a031da9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30632">issues.joomla.org/tracker/joomla-cms/30632</a>.</sub>

**Review by hans2103 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 00173ebf595de63ecfca160b88f1e6659a031da9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30632">issues.joomla.org/tracker/joomla-cms/30632</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30632">issues.joomla.org/tracker/joomla-cms/30632</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
