### PR TITLE
[4.0] Fix jQuery Minicolors positioning

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #22604

### Summary of Changes

Fix the positioning of the colour form field, so cater for the height increase of inputs in the new template

46915710-1c889000-cfa7-11e8-92e2-98e225697238

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks :)

**Comment by C-Lodder** [comment]
@wilsonge @brianteeman Can one of you confirm this actually works? I haven't tested it as I'm at work and have issues with my localhost atm

**Comment by dgrammatiko** [comment]
AFAIK this is replaced by a custom element. Mini colours is only used for the advanced part eg the full coloraturas range

**Comment by C-Lodder** [comment]
@dgrammatiko Wasn't the custom element for a "simple colour pickr", e.g you define a set of colours, rather than having a palette?

**Comment by dgrammatiko** [comment]
Yup, but if you still have the advanced layout with an option to render also the same list of colours then something is totally wrong. Also this thingy (apart the jQuery dependency) is totally inaccessible. At least the other part had some a11y considerations (I'm not saying it's accessible for obvious reasons 😂)

**Comment by brianteeman** [comment]
Came across this the other day if it is of use https://vanilla-picker.js.org/

**Pull request merged**
