### PR TITLE
Downloadable system information

### PR DESCRIPTION
**Pull request by phproberto**
This replaces https://github.com/joomla/joomla-cms/pull/5647
## Description

This adds a new button in backend: `System` > `System Information` that allows administrator to download the page settings. This can be useful to debug system issues by support teams.

download-system-information

This also adds a new fast method to add a backend toolbar button through: `JToolbarHelper::link($url, $text, $name = 'link')` which will be useful to allow external links on components toolbars.
## How to test it
1. Go to system information and see that all the settings are still there as expected
2. Click on download and make sure that all the sections are there. It contains:
3. `php_settings`: Information about the php settings 
4. `config`: Configuration information
5. `info`: System information
6. `php_info`: Parsed `phpinfo()` information
7. `directories`: Information about the website folders (if they are writable or not)

I have changed the original way that @Radek-Suski used to parse the file as I think it should be processable by third part systems. So the most real the data is the better.

Private / Critical information has to NOT be exported in any way so if you detect any information that should be removed report it.
## Backward compatibility issues

This is a new feature and shouldn't create any B/C issue. The only method affected is `AdminModelSysInfo::getPhpInfo()` that has been renamed and optimized.

### CODE REVIEW

**Comment by phproberto** [comment]
Ok I think there was a confusion here because @Radek-Suski's branch was inheriting the code from:
https://github.com/joomla/joomla-cms/pull/6021

Not sure how to proceed now. I'm going to drink 234235345346 beers

**Comment by bertmert** [comment]
@Test Successfully tested 6412

Saved file tested with these lines of code

$infos = json_decode(file_get_contents(__DIR__.'/systeminfo.json'));
echo "DEBUG systeminfo.json \$infos \n\n".print_r($infos, true);exit;

//php_settings OK
//config OK
//info OK
//php_info OK (rendom sample checks)
//directories OK

**Comment by Radek-Suski** [comment]
@phproberto Just to be clear: we are working on your implementation now. Right?
I like your way but there were few things I wanted to add to this functionality so I am not sure where we are working now.

**Comment by phproberto** [comment]
@bertmert thanks for testing. I'm sorry but I have to close this because I did a mistake and I mixed issues.

@Radek-Suski no. This is your idea and it has been already discussed there. I'm closing this and:
* Submit a PR against your already existing PR
* Create another PR for the whitespaces issue

**Pull request closed without merging**
