### PR TITLE
[a11y] burger bar menu

### PR DESCRIPTION
**Pull request by brianteeman**
simple backport from bootstrap 3 of an accessibility improvement for the burger bar menu in protostar and isis templates
### Summary of Changes

Add an explanation text span above the burger ban - it will only be displayed to screen readers
### Testing Instructions

Apply the patch and look for 

```
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
```

In the source code

After the patch this will now be displayed as

```
<span class="element-invisible">Toggle Navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>

### Documentation Changes Required
```

### CODE REVIEW

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12426">issues.joomla.org/tracker/joomla-cms/12426</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 9ad0280e0df9c93814fa61a09397487806eb792d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12426">issues.joomla.org/tracker/joomla-cms/12426</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12426">issues.joomla.org/tracker/joomla-cms/12426</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
