### PR TITLE
[4.4][bugfix] Use iife for the scripts core and validate

### LINKED ISSUE #43714: validate.js throws Uncaught SyntaxError: redeclaration of const errors
### Steps to reproduce the issue
Display a form and use webassets to use script form.validate

### Expected result
script works with no errors in console.log

### Actual result
Uncaught SyntaxError: redeclaration of const errors is displayed in console.log

### System information (as much as possible)
Tested on 5.0 and 5.1.1, discussed on Extension development room and @Fedik requested an issue raised. 

### Additional comments
Fedir Zinchuk
It a bug in validate.js, the code should be wrapped in to anonimous function or use type module
please open an issue

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43714 .

### Summary of Changes

Use iife instead of esm for the scripts core and validate

### Testing Instructions

- Apply the PR
- run `npm install`
- Check that authenticating in the administrator works
- Create a new article, don't add anything and press save, the validation error should appear
- still in the article edit view, open the browser console, and type `const initialize = 1;` and hit Enter.

Before: `Error SyntaxError: Identifier 'initialize' has already been declared`
After: No error

### Actual result BEFORE applying this Pull Request

Leaking variables in the global scope

### Expected result AFTER applying this Pull Request

NO leaking variables in the global scope

### Link to documentations
Please select:
- [] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
thanks! I will test it later

**Comment by Fedik** [comment]
hmhm, nope, sorry, it does not work. The variables in the file still globally available. 
'use strict' just forcing developer to use `var`, `const`, `let`, and some other litle things.

It should be anonymous function wrapper. 
But it is not possible, because we have `import punycode from 'punycode';`  (this will throw  rollup/babel compilation error).

Need to hack the rollup/babel somehow :smile: 
I have no other ideas.

**Comment by Fedik** [comment]
No, Ignore me :smile:

**Comment by Fedik** [comment]
It works, but, wee need to set some globals back. please add:
```javascript
window.JFormValidator = JFormValidator;
window.punycode = punycode;
```

Someone may use it in their scripts, even though `punycode` not officially shipped.
Maybe with some comment, that it will be removed in future.

**Comment by dgrammatiko** [comment]
Classes exposed to the global scope

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 348daed8f74bf1aeb729745a91c41496bbd40ec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43755">issues.joomla.org/tracker/joomla-cms/43755</a>.</sub>

**Comment by Fedik** [comment]
**For testing.** 
Open Article editing, open browser console, and type `const initialize = 1;` and hit Enter.

**Before:**
Error `SyntaxError: Identifier 'initialize' has already been declared`
**After:**
No error;

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 348daed8f74bf1aeb729745a91c41496bbd40ec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43755">issues.joomla.org/tracker/joomla-cms/43755</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43755">issues.joomla.org/tracker/joomla-cms/43755</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
