### PR TITLE
[4.0] codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
fix typo in code comments - code review only required

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ea2d27783c3aa1a709d01b2861b01c77b5a66dab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30724">issues.joomla.org/tracker/joomla-cms/30724</a>.</sub>

**Review by hans2103 — APPROVED** [review]
I have tested this item ✅ successfully

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on ea2d27783c3aa1a709d01b2861b01c77b5a66dab<br /><br />Help me... how can I add my successful test via GitHub itself? Thus without issues.joomla.org <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30724">issues.joomla.org/tracker/joomla-cms/30724</a>.</sub>

**Comment by richard67** [comment]
> Help me... how can I add my successful test via GitHub itself? Thus without issues.joomla.org

@hans2103 Not sure if there is a way. At least I don't know one.

**Comment by infograf768** [comment]
> Help me... how can I add my successful test via GitHub itself? Thus without issues.joomla.org

You can’t.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30724">issues.joomla.org/tracker/joomla-cms/30724</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
