### PR TITLE
Use JHtml underscore method

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use `JHtml::_()` instead of using `JHtml` classes directly to allow overrides.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c4e94fd5c424b2590ed4cc1db4e03a531942cf60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29635">issues.joomla.org/tracker/joomla-cms/29635</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c4e94fd5c424b2590ed4cc1db4e03a531942cf60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29635">issues.joomla.org/tracker/joomla-cms/29635</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29635">issues.joomla.org/tracker/joomla-cms/29635</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
