### PR TITLE
Add support for dependency injection to the JMenu class tree

### PR DESCRIPTION
**Pull request by mbabker**
This pull request adds "poor man's" support for dependency injection into the JMenu class tree by utilizing the existing options array to allow class objects to be injected.  This helps to identify the class chain's dependencies on other class objects, remove hard couplings to JFactory, and improve testability of the class chain.  Also included in this pull request is minor internal structure cleanup and improvements to a couple existing doc blocks.
### Test Instructions

With the patch applied, a user should be able to navigate the application (site and admin) without issue.

### CODE REVIEW

**Comment by wilsonge** [comment]
Is this worth it when we are actually starting work on J4 and we would have to add code to work in conjunction with this when we add the 'real' DI?

**Comment by mbabker** [comment]
Depends what the approach in J4 is gonna be.  If we still end up with a
JFactory like object, this changes nothing.  If we go 100% "real" DI, these
identified dependencies would shift to proper constructor arguments.  Since
we don't have a factory for building these classes, this approach is the
best compromise we have now to try and do something.

**Comment by rdeutz** [comment]
I am working on it following the way laravel is implementing it, so the application object extends the IoC. Atm I'm still fighting with the autoloading to make sure the old stuff is still working.

**Comment by wilsonge** [comment]
Personally I'd shove it in the constructor in J4 and not have to stress about keeping some vague sense of b/c with this then

**Comment by mbabker** [comment]
We're already using this type of DI in JFilterInput, so not unprecedented (and never refactored in the Framework).  If I'm wasting my time just say so and I'll close it.  Not like I don't have other PRs in the same boat.

**Comment by wilsonge** [comment]
OK I see we are using it to inject `JFilterInput` into `JInput`. Fix the conflicts, and I'll do my test.

**Comment by mbabker** [comment]
Done

**Comment by KingLouis1** [comment]
I have tested this item :white_check_mark: successfully on 4dfefa8b99e048eb9edd0d73de8467d2ecfcf361<br /><br />No isuues found<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/joomla-cms/8012</a>.</sub>

**Comment by KingLouis1** [comment]
I have tested this item :white_check_mark: successfully on 4dfefa8b99e048eb9edd0d73de8467d2ecfcf361<br /><br />No issues found<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/joomla-cms/8012</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on 4dfefa8b99e048eb9edd0d73de8467d2ecfcf361<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/joomla-cms/8012</a>.</sub>

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on 4dfefa8b99e048eb9edd0d73de8467d2ecfcf361<br /><br />Looks good to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/joomla-cms/8012</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/joomla-cms/8012</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody. This has now been merged into 3.5-dev.

**Comment by tomford51** [comment]
Thanks for the work, maybe [online therapy session](https://ca.calmerry.com/try-online-therapy/ "https://ca.calmerry.com/try-online-therapy/") will also help to overcome procrastination at work and continue to develop as a developer, for example, it helped me overcome stress<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8012">issues.joomla.org/tracker/joomla-cms/8012</a>.</sub>

**Pull request merged**
