### PR TITLE
New tooltip replacing #6050

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/pull/6050

This solves the `<strong>` issue.

After patch (clear your caches) you should get:
screen shot 2015-10-25 at 09 31 25
screen shot 2015-10-25 at 10 16 01
screen shot 2015-10-25 at 10 16 28

### CODE REVIEW

**Comment by zero-24** [comment]
Travis is failing here :( maybe because of different html?

**Comment by roland-d** [comment]
@zero-24 Indeed, the unit tests fail due to the changed HTML. The unit test should be updated as well to reflect the change in HTML.

**Comment by infograf768** [comment]
I am trying to do that now.

**Comment by bertmert** [comment]
@test Successfully tested with ISIS and current staging. :white_check_mark:

**Comment by infograf768** [comment]
CC: @adhocgraFX, @christianhent, @designbengel, @KingLouis1, @RoterNagel, @Yorgoz
Please test.

**Comment by fontanil** [comment]
@test 
Patch is OK. Thanks!

**Comment by infograf768** [comment]
@bertmert
Although we do not need to escape single quotes when using JText it does not cost much to do so in this precise context. Modified PR.

**Comment by infograf768** [comment]
@bertmert, @fontanil
Please retest and confirm on issues.joomla.org + test also
https://github.com/joomla/joomla-cms/pull/8161

thanks

**Comment by fontanil** [comment]
@test 
I confirm. Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by bertmert** [comment]
@test Tested successfully :white_check_mark: this PR in combination with https://github.com/joomla/joomla-cms/pull/8161

**Comment by zero-24** [comment]
RTC for 3.5.0. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by dgt41** [comment]
@infograf768 I like it a lot but I think if we go for a light colored tool tip we should apply some shadow around it (same as modal, popup, menus)
So here is a preview of that:
screenshot 2015-10-26 16 17 19
And the changes:
jus/tooltip.less after line 5
```less
// Base class
.tooltip {
  position: absolute;
  z-index: @zindexTooltip;
  display: block;
  visibility: visible;
  font-size: 11px;
  line-height: 1.4;
  .opacity(0);
  .border-radius(@baseBorderRadius);
  &.in     { .opacity(80); }
  &.top    { margin-top:  -3px; padding: 0px 0; }
  &.right  { margin-left:  3px; padding: 0 5px; }
  &.bottom { margin-top:   3px; padding: 0px 0; }
  &.left   { margin-left: -3px; padding: 0 5px; }
}
```
and isis/template.less after line 1048
```less
  .box-shadow(0 0 5px rgba(0,0,0,0.3));
```
Same thing for protostar

**Comment by roland-d** [comment]
@infograf768 Would you like to add @dgt41 suggestion to this PR?

**Comment by infograf768** [comment]
@dgt41 

Pleaase contact me on glip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by infograf768** [comment]
@roland-d 
I tested @dgt41 suggestion and It's missing something here. 
Concerning Protostar, I suggest to do a separate PR

**Comment by roland-d** [comment]
@infograf768 Fine by me, then I will merge this as-is.

**Comment by infograf768** [comment]
@roland-d 
Please wait I talked to @dgt41

**Comment by Bakual** [comment]
You guys are aware that Bootstrap already has a thing called "Popover" which would look exactly like that? See http://getbootstrap.com/2.3.2/javascript.html#popovers
Bootstrap tooltips aren't meant to contain a title or lengthy texts, that's what popver are designed for. The JS is the same, just a difference in appearance.

**Comment by infograf768** [comment]
Would not changing from tooltip to popovers be much more complex and maybe not B/C?

**Comment by infograf768** [comment]
@dgt41
After some modifications to your proposal, I can obtain this:
screen shot 2015-10-27 at 09 28 00


@Bakual 
If you have a better idea, please propose some code.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/8174 for an idea how to use Popovers. You will see that they look about the same to what you try to do here.
So you basically remove tooltips from backend and make everything a popover.

The main issue is however that we did misuse tooltips back when we started using Bootstrap tooltips. They were never meant to show titles to begin with. We hacked around it instead of using the proper method :smile:

**Comment by infograf768** [comment]
Folks, I succeeded in patching also Hathor, Beez and Protostar, but, doing so, I found out that this PR is not B/C at all for the other templates around because of the change in the library.
I.e. any template not updating their css <b>will not get any more the tooltip title in bold</b> and will keep the background colour and text colour the template maker has set.

I guess therefore that it is not the solution. Commented on @Bakual suggestion in https://github.com/joomla/joomla-cms/pull/8174#issuecomment-151444283

**Comment by zero-24** [comment]
Ok so for now we remove the milestone and label.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on 142ce1eacb1c631f207cf2051709aca7345e824f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by infograf768** [comment]
In case of, I also took care of Hathor, Beez and Protostar.
To test with English and an RTL language.

**Comment by bertmert** [comment]
Even if I don't know if this PR is still relevant.
@test Tested successfully with all core templates BE and FE

Concerning BC and STRONG. The main conflict in the beginning was that STRONG was formatted as block. This has been removed now. So, I think changing line https://github.com/joomla/joomla-cms/pull/8150/files#diff-b01d47e3fbe4a8e5fb4987f4df64b291R920

to
```
$result = '<span class="tooltip-title"><strong>' . $title . '</strong></span>';
```
or
```
$result = '<span class="tooltip-title"><b>' . $title . '</b></span>';
```
could be a solution for BC

**Comment by bertmert** [comment]
Found another issue with Hathor (not directly related to the changes of this patch but also same behavior with this patch).
https://github.com/joomla/joomla-cms/issues/8434

**Comment by brianteeman** [comment]
@infograf768 I'm a bit confused on the status of this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Comment by brianteeman** [comment]
I guess this PR is no longer needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8150">issues.joomla.org/joomla-cms/8150</a>.</sub>

**Pull request closed without merging**
