### PR TITLE
[4.1] codemirror 5.65.2 update

### PR DESCRIPTION
**Pull request by brianteeman**
clike mode: Recognize triple quoted string in Java.
cypher mode: Fix handling of punctuation.

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0d637d3d32a9a4f24dbc4183050b0a857a527c88<br /><br />Codemirror works as well as before after having applied this PR and made an "npm ci" and checked that in "node_modules/codemirror" there is the new version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37194">issues.joomla.org/tracker/joomla-cms/37194</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 0d637d3d32a9a4f24dbc4183050b0a857a527c88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37194">issues.joomla.org/tracker/joomla-cms/37194</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37194">issues.joomla.org/tracker/joomla-cms/37194</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
