### PR TITLE
[5.0] Update bootstrap to 5.3.2

### PR DESCRIPTION
**Pull request by HLeithner**
Pin boostrap to 5.3.2 and cypress-joomla to 0.0.16 for now.

### CODE REVIEW

**Comment by laoneo** [comment]
Why?

**Comment by HLeithner** [comment]
Why? Why? The uomerge of bootstrap failed and I broke cypress-joomla 0.0.18

**Comment by laoneo** [comment]
Why did the upmerge of bootstrap fail? If you pin it to the version we have also in 4.4 it looks right. There must be a valid reason to pin to a fixed version and I do not see one for bootstrap.

**Comment by HLeithner** [comment]
Don't know why the upmerge wasn't successful, should used ^3.5.2 for upgrade, will change this later.

**Pull request merged**
