### PR TITLE
[4.0]added minor styles for easy nav in sidebar-nav

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - It is quite difficult to know which component settings are open in com_config. This feature was there in J3.

### Summary of Changes
Highlights selected option

screenshot from 2019-03-01 16-45-45

screenshot from 2019-03-01 16-45-45

### Testing Instructions
Open com_config

### CODE REVIEW

**Comment by bahl24** [comment]
@C-Lodder As you have made the template, what do you think?

**Comment by C-Lodder** [comment]
Had a flashback of Windows 98 for a moment

I didnt make the template at all. As for menu item hover styling, I'm sure there is a design styleguide for this somewhere.

At a first glance though, the padding needs fixing

**Comment by brianteeman** [comment]
isnt this pr a waste of everyones time until the secret template team deliver their secret work

**Comment by bahl24** [comment]
@brianteeman If such changes are already in WIP then I would close this, I just thought that this change would be helpful as in J3.

**Pull request closed without merging**
