### PR TITLE
[4.0] Remove unused import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 819d545bdd1ac8f08e4eb9719c8e8be4c58cd2ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36199">issues.joomla.org/tracker/joomla-cms/36199</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 819d545bdd1ac8f08e4eb9719c8e8be4c58cd2ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36199">issues.joomla.org/tracker/joomla-cms/36199</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36199">issues.joomla.org/tracker/joomla-cms/36199</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
