### PR TITLE
SQL: Wrong title for Contacts submenu

### PR DESCRIPTION
**Pull request by infograf768**
This PR to solve https://github.com/joomla/joomla-cms/issues/8200

The submenu title is incorrect in the db, therefore it does not use the right string `COM_CONTACT_CONTACTS`

Patch and make new installation or run the sql request (change #_ to your db prefix) on an existing site:

```
REPLACE INTO `#__menu` VALUES
(8, 'menu', 'com_contact_contacts', 'Contacts', '', 'Contacts/Contacts', 'index.php?option=com_contact', 'component', 0, 7, 2, 8, 0, '0000-00-00 00:00:00', 0, 0, 'class:contact', 0, '', 12, 13, 0, '*', 1);
```

In en-GB, the values of COM_CONTACT and COM_CONTACT_CONTACTS are the same (Contacts) in the en-GB.com_contact.sys.ini language file.
Therefore to test in en-GB, just modify the value of COM_CONTACT_CONTACTS

Result in French:
screen shot 2015-10-30 at 09 24 42

NOTE: I have just updated sql in /administrator/components/com_admin/sql/updates/mysql/3.5.0-2015-10-30.sql
I have not touched at postgres and sqlazure there. To who knows how to, please propose a PR for that.

### CODE REVIEW

**Comment by mbabker** [comment]
If you're only changing the one field an `UPDATE foo SET bar` query will be more efficient here.  And the same syntax works for the other database types too (they just use different quoting structures).

**Comment by infograf768** [comment]
@mbabker 
Will try

**Comment by infograf768** [comment]
Thanks @alikon  :)

**Comment by infograf768** [comment]
We need here one more test to RTC.

**Comment by peterpeter** [comment]
@test
Tested successfuly on a fresh installation. Submenutitle/COM_CONTACT_CONTACTS could be overwritten while the mainmenu stays the same.

**Comment by peterpeter** [comment]
I have tested this item :white_check_mark: successfully on f3795d0b486fbcf33fea6af1e346e618d5823d13<br /><br />(finally found the 'Test this'-button ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8212">issues.joomla.org/joomla-cms/8212</a>.</sub>

**Comment by infograf768** [comment]
RTC as we have 2 good tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8212">issues.joomla.org/joomla-cms/8212</a>.</sub>

**Comment by ratenfanger** [comment]
Just updated a Joomla installation (in a test environment) from 3.4.8 to 3.5 (using MySQL). The title of menu item with ID 8 was changed from "Geschiedenis" to "com_contact_contacts" as stated in this PR.
The changed menu item is shown on the frontend, so it is not the backend menu item which should be updated. I think I got a frontend menu item with ID 8 because I'm running this site since Joomla 1.5. A long time ago I migrated to 2.5 (and updated every release since then).

I think other people with (somehow) non-default menu item IDs may/will have the same problem. My proposal is to only change the title for menu items which matches the follow criteria:
a) only backend menu items (client_id = 1)
b) with title = 'com_contact' 
c) in a submenu (level = 2)

For MySQL the following query does the job from phpMyAdmin:
UPDATE `jml_menu` SET `title` = 'com_contact_contacts' WHERE `client_id` = 1 AND `level` = 2 AND `title` = 'com_contact'

If you agree I wil be happy to change the queries and submit another PR. I also can help testing for MySQL because I did not upgrade my production installation yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8212">issues.joomla.org/joomla-cms/8212</a>.</sub>

**Comment by brianteeman** [comment]
@ratenfanger you are commenting on a pull request that was merged five months ago

**Comment by ratenfanger** [comment]
@brianteeman sorry I thought this was the correct place to discuss my findings. Should I create a new issue and mention this PR?

**Comment by brianteeman** [comment]
Yes please

**Pull request merged**
