### PR TITLE
[4.0] Messaging : options missing string

### PR DESCRIPTION
**Pull request by brianteeman**
Go to the options for the messaging component and you will see the title is missing

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab7316e907ccf7a1dbaf5b630f9d83f8b02f5dc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34420">issues.joomla.org/tracker/joomla-cms/34420</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ab7316e907ccf7a1dbaf5b630f9d83f8b02f5dc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34420">issues.joomla.org/tracker/joomla-cms/34420</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34420">issues.joomla.org/tracker/joomla-cms/34420</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
