### PR TITLE
[4.0] Remove duplicate code in fieldsplugin

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for discussion https://github.com/joomla/joomla-cms/discussions/36425.

### Summary of Changes
Remove duplicated code in Fieldplugin class. Looks like that the code wrongly merged up from staging into the 4 branch. In staging it was added in a BC way in #28516 and in 4 it was correctly added with #28534.

### Testing Instructions
- Create a custom field
- Edit an article and fill the field
- Open the article on the front

### Actual result BEFORE applying this Pull Request
All is working as expected.

### Expected result AFTER applying this Pull Request
All is working as expected.

### CODE REVIEW

**Comment by Quy** [comment]
Tested successfully. Not listed in issue tracker.

**Comment by HusiBT** [comment]
Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36434">issues.joomla.org/tracker/joomla-cms/36434</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36434">issues.joomla.org/tracker/joomla-cms/36434</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
