### PR TITLE
[4.0] string variables

### PR DESCRIPTION
**Pull request by brianteeman**
discovered in J3 by @dryabov in #32505

there were extra strings with the same error in j4

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f618eb1abc44593d99c811468dcdd8d54e38273a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32506">issues.joomla.org/tracker/joomla-cms/32506</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f618eb1abc44593d99c811468dcdd8d54e38273a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32506">issues.joomla.org/tracker/joomla-cms/32506</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32506">issues.joomla.org/tracker/joomla-cms/32506</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Comment by infograf768** [comment]
### Remarks
`JFIELD_PASSWORD_NOTE_DESC`
I can't find the use of this string in code as well as 
`JFIELD_PASSWORD_NOTE_LBL="Password must contain:"`

Could you confirm this? If yes they just should be deleted, in admin, site and api.

**If it is used and not a remaining of former code**
`JFIELD_PASSWORD_NOTE_DESC` is modified in this PR for the Api only
What about admin joomla.ini and site joomla.ini still using
`JFIELD_PASSWORD_NOTE_DESC="%1 symbol(s), %2 uppercase letter(s), %3 lowercase letter(s), %4 number(s)"`

Should not API be exactly the same as admin ?
Also, should not this use `d` instead of `s` as these are integers?
I.e.
`%1$d`, `%2$d`, etc ?

**Pull request merged**
