### PR TITLE
[4.0] ContentHelper prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements to `Joomla\CMS\Helper\ContentHelper`.

### Testing Instructions

Install sample data.
Go to article categories view in backend. Inspect item count.
Go to tags view in backend. Under `Select Tag Type` in search tools select `Article`. Inspect item count.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 44456e203260c8f9a4d5dd559b1c5c4ebf64c61b<br /><br />Code review + test as described in instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26029">issues.joomla.org/tracker/joomla-cms/26029</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44456e203260c8f9a4d5dd559b1c5c4ebf64c61b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26029">issues.joomla.org/tracker/joomla-cms/26029</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26029">issues.joomla.org/tracker/joomla-cms/26029</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
