### PR TITLE
[4.3] Allow module Helper optional

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Currently, a module uses service provider (our new modern module structure) requires registering `HelperFactory` service provider. However, not all modules require Helper class to get required data, so module `HelperFactory` should be optional.

### Testing Instructions
1. Use Joomla 4.3 nightly build
2. Install this updated version [mod_custom.zip](https://github.com/joomla/joomla-cms/files/10890802/mod_custom.zip) of mod_custom module (it's the result of this PR https://github.com/joomla/joomla-cms/pull/39931 , rebuild the module with our new module structure)
3. Create an instance of Custom HTML module. Assign it to certain pages on your site (or just All Pages)
4. Delete the file administrator/cache/autoload_psr4.php

### Actual result BEFORE applying this Pull Request
You got fatal error: Resource 'Joomla\CMS\Helper\HelperFactoryInterface' has not been registered with the container

### Expected result AFTER applying this Pull Request
No error. The module is being displayed properly

### Link to documentations
Please select:
- [] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
Ping @laoneo for taking a look at this change.

**Comment by laoneo** [comment]
Not on the computer right now. Does this work when a module is overwriting the constructor and still has the ild signature? If that works then it is fine.

**Comment by joomdonation** [comment]
> Does this work when a module is overwriting the constructor and still has the ild signature

I don't really know how to do that because there are no modules like that in core test the behavior. I would say that it should work well because what I really do here is make the parameter nullable. 

But to be safe, would be great if you could look at this when you are on your computer. Thanks.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7020065178770283d9a639a0389b6a1ea3b7de31<br /><br />Tested successfully in Joomla 4.3.0-beta4-dev of 7 March using PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40017">issues.joomla.org/tracker/joomla-cms/40017</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 7020065178770283d9a639a0389b6a1ea3b7de31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40017">issues.joomla.org/tracker/joomla-cms/40017</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40017">issues.joomla.org/tracker/joomla-cms/40017</a>.</sub>

**Comment by obuisard** [comment]
Thank you again Tuan @joomdonation :-)

**Comment by sandewt** [comment]
Joomla 4.2 already contains modules with the module structure.

I have built a module for Joomla 4.2 according to the new structure. It doesn't work now, fatal error. 

Is it possible, without too much trouble, to merge this PR into the Joomla 4.2 branch as well? Or still wait until Joomal 4.3 comes out?

**Comment by joomdonation** [comment]
@sandewt 4.2.9 is the last 4.2 release, so you will have to wait for 4.3.0 to have this issue fixed.

**Comment by sandewt** [comment]
> 4.2.9 is the last 4.2 release, so you will have to wait for 4.3.0 to have this issue fixed.

Thanks Tuan.

**Pull request merged**
