### PR TITLE
Move the button order and reverse the display

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue found by @yvesh cc: @rdeutz 

### Summary of Changes

Move the button order and reverse the display

### Testing Instructions

- Go to the four components integration settings
- confirm before an after behavior

### Expected result

image

image

### Actual result

image

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on bfa86f3eb53fb3b311b323737ec17151dc809c55<br /><br />Test: Articles, Contacts, News Feeds and Users.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14418">issues.joomla.org/tracker/joomla-cms/14418</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bfa86f3eb53fb3b311b323737ec17151dc809c55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14418">issues.joomla.org/tracker/joomla-cms/14418</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on bfa86f3eb53fb3b311b323737ec17151dc809c55<br /><br />I have tested this item ✅ successfully 

Works like a charm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14418">issues.joomla.org/tracker/joomla-cms/14418</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item ✅ successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14418">issues.joomla.org/tracker/joomla-cms/14418</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14418">issues.joomla.org/tracker/joomla-cms/14418</a>.</sub>

**Pull request merged**
