### PR TITLE
Load simplepie through composer and do update

### PR DESCRIPTION
**Pull request by wilsonge**
Previously we appeared to refrain from updating to 1.3 because of b/c issues. However 1.3.1 appeared to solve these from wordpress' experience (https://core.trac.wordpress.org/ticket/21183#comment:16).

Loading through composer also makes things easier for future updates (if there are any - the last release was 2012).

Honestly I don't know how to test this - it's going to rely on people who previously wrote simplepie specific scripts to test as all of core now uses the internal JFeed classes.

### CODE REVIEW

**Comment by mbabker** [comment]
@wilsonge Rebase or close this.  You're probably better off doing the latter, this ain't going anywhere anyway.

**Comment by Hackwar** [comment]
I think, I agree with @mbabker here. This might be a good improvement, but I actually would rather remove simplepie altogether instead of updating an unused class.

This would be a good situation to have separately managed extensions for libs like this.

**Comment by photodude** [comment]
@wilsonge I know there are other burning issues, but when you get a chance could you fix the conflicts so this could be tested?

**Comment by ghazal** [comment]
SimplePie has been updated to 1.4.
https://github.com/simplepie/simplepie/blob/master/library/SimplePie.php
Version 1.2 throws Deprecated errors (functions not made "public" in this version).
Is simplepie going to be removed from next joomla package as it is announced ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8735">issues.joomla.org/joomla-cms/8735</a>.</sub>

**Comment by wilsonge** [comment]
Updated. I've kept it as 1.3.1 because I can't find any information as to what is contained in 1.4.0 anywhere - the website still lists 1.3.1 as the latest version (although obviously the github tag exists for 1.4). Until I'm convinced we arent going to hit b/c breaks i'm happier sitting on 1.3.1

**Comment by wilsonge** [comment]
But yes in J4 we will still remove simplepie

**Comment by roland-d** [comment]
Merged on review.

**Comment by mbabker** [comment]
@wilsonge You need a PR updating the deleted files list.

**Pull request merged**
