### PR TITLE
[4.0] Fix typos

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2a1435daa6b3001d47867f268e9a32048ce1211d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29515">issues.joomla.org/tracker/joomla-cms/29515</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 2a1435daa6b3001d47867f268e9a32048ce1211d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29515">issues.joomla.org/tracker/joomla-cms/29515</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29515">issues.joomla.org/tracker/joomla-cms/29515</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
