### PR TITLE
Improve doc blocks for JMenu

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Improve doc blocks to highlight the returned `JMenuItem` object from the `JMenu` API.

### Testing Instructions

Review

### Documentation Changes Required

This is the documentation.

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e19fb2b90491ca0aa9f41e4460653f849dbdc1f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13274">issues.joomla.org/tracker/joomla-cms/13274</a>.</sub>

**Comment by gwsdesk** [comment]
Review shows no issues so works4me :white_check_mark:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13274">issues.joomla.org/tracker/joomla-cms/13274</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on e19fb2b90491ca0aa9f41e4460653f849dbdc1f5<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13274">issues.joomla.org/tracker/joomla-cms/13274</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13274">issues.joomla.org/tracker/joomla-cms/13274</a>.</sub>

**Pull request merged**
