### PR TITLE
[4][com_joomlaupdate] untraslated warning strings

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #34792.

### Summary of Changes
1st Load com_installer's language

### Testing Instructions
4.0 nightly. With PHP temporary folder not explicitly set in php.ini or otherwise.
In back-end go to: index.php?option=com_joomlaupdate&view=upload

### Actual result BEFORE applying this Pull Request
string untranslated

### Expected result AFTER applying this Pull Request
string translated

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d50983a1d7d88fecc21c65126c45b05ce85a0593<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34804">issues.joomla.org/tracker/joomla-cms/34804</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 5fc4dcaf71429e42521774f6f023111fc7906703<br /><br />Joomla! 4.0.0-rc5-dev Development [ Mañana ] 13-July-2021 20:07 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34804">issues.joomla.org/tracker/joomla-cms/34804</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34804">issues.joomla.org/tracker/joomla-cms/34804</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by alikon** [comment]
wow 6 hours only :rofl: 
it's not a record but 
wow

**Pull request merged**
