### PR TITLE
[4.0] Article options record hits

### PR DESCRIPTION
**Pull request by brianteeman**
Changes the option to use the switcher instead of the old style yes/no

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 71a82c3c966afe148316e5ac4168a1e1d6d73bfe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24669">issues.joomla.org/tracker/joomla-cms/24669</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 71a82c3c966afe148316e5ac4168a1e1d6d73bfe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24669">issues.joomla.org/tracker/joomla-cms/24669</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24669">issues.joomla.org/tracker/joomla-cms/24669</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
