### PR TITLE
[4.3] Fix back button in toolbar

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #39537 .

### Summary of Changes
Fix `Back` button in toolbar.

### Testing Instructions
Edit a user.
See `Back` button.

### Actual result BEFORE applying this Pull Request
users-back-button

### Expected result AFTER applying this Pull Request
users-back-button-pr

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 0f9837fc5c60cc81653f0773e4a24187ed72602c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39782">issues.joomla.org/tracker/joomla-cms/39782</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0f9837fc5c60cc81653f0773e4a24187ed72602c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39782">issues.joomla.org/tracker/joomla-cms/39782</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39782">issues.joomla.org/tracker/joomla-cms/39782</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
