### PR TITLE
[4.0] WebAssets and Cache enabled

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #28727 .

### Summary of Changes

Store/Restore Asset Manager state for caching, with `HtmlDocument::get[set]HeadData()`

### Testing Instructions
Apply patch.
Enable caching in global configuration.
Create a CustomHTML module with next content:
`<p class="much-red">test cache</p>`

Edit `modules/mod_custom/tmpl/default.php`, add:
```php
$wa = $app->getDocument()->getWebAssetManager();
$wa->addInlineStyle('.much-red{color:red; font-weight:bold;}');
```

Open the page with module.

### Expected result

The text color in the module should be red after each page refresh.

### Actual result

The text is red only after first load (or after clearing the cache), and stays black on future page refresh

### Documentation Changes Required

none

@wilsonge please review

### CODE REVIEW

**Comment by richard67** [comment]
@Fedik Is that somehow related to the recently merged PR #28990 ? At least the description reads similar to me.

**Comment by Fedik** [comment]
@richard67  #28990 is about _old_  _script/_style declarations of the Document, that do not cover WebAsset

**Comment by richard67** [comment]
@Fedik Ah, I see. I haven't noticed that on a quick look. Thanks for the clarification.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 89ee9e4bb11404f9b932d41838158593894912c7<br /><br />Worked as advertised with Conservative and Progressive cacheing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29022">issues.joomla.org/tracker/joomla-cms/29022</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 89ee9e4bb11404f9b932d41838158593894912c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29022">issues.joomla.org/tracker/joomla-cms/29022</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29022">issues.joomla.org/tracker/joomla-cms/29022</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
