### PR TITLE
[4.0] s/an/and

### PR DESCRIPTION
**Pull request by brianteeman**
Typo in comment

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d82f679b4fa7d8763cc34f269720534c6976d68c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33320">issues.joomla.org/tracker/joomla-cms/33320</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d82f679b4fa7d8763cc34f269720534c6976d68c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33320">issues.joomla.org/tracker/joomla-cms/33320</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33320">issues.joomla.org/tracker/joomla-cms/33320</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
