### PR TITLE
[4.0] [com_joomlaupdate] Finalise confirm styling

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Some styling fixes.

### Testing Instructions

Go to `administrator/index.php?option=com_joomlaupdate&view=update&layout=finaliseconfirm`.

### Before

Screenshot_2020-03-02 Joomla Update - Joomla - Administration(1)

### After

Screenshot_2020-03-02 Joomla Update - Joomla - Administration(2)

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2b17317b3c171309fefb8d63b6c435c744598dcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28183">issues.joomla.org/tracker/joomla-cms/28183</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2b17317b3c171309fefb8d63b6c435c744598dcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28183">issues.joomla.org/tracker/joomla-cms/28183</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28183">issues.joomla.org/tracker/joomla-cms/28183</a>.</sub>

**Comment by brianteeman** [comment]
Shouldn't there be some space between the buttons?

**Comment by brianteeman** [comment]
It's not in scope so you can chose to leave it for another pr but the tabindex is not needed

**Comment by SharkyKZ** [comment]
Leave that to another PR.

**Comment by zero-24** [comment]
Thanks 👍

**Comment by brianteeman** [comment]
see #28192 for the tabindex removal

**Pull request merged**
