### PR TITLE
New contact css issue

### PR DESCRIPTION
**Pull request by lavipr**
Pull Request for Issue #15271 .

### Summary of Changes
Prevent to overlapping content of the columns, when there are three columns. This depends of the width of the popup, where the issue appeared before.

### Testing Instructions
in backend:
Menus > Main Menu > Add Menu Item > Menu Item Type: Contacts > Single Contact -> Select Contact: > Create (New Contact) - button

### Expected result
No overlapping anymore. 
nooverlapping

### Actual result
Overlapping between window.innerWidth 1225px and 1515px
overlapping

### Site Information
siteinfo

### Documentation Changes Required
No

developed @icampus

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 44d1e5497c426b447ecdf4caffe195d2ba3a9b60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17764">issues.joomla.org/tracker/joomla-cms/17764</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 44d1e5497c426b447ecdf4caffe195d2ba3a9b60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17764">issues.joomla.org/tracker/joomla-cms/17764</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by C-Lodder** [comment]
This is a very dirty approach.

I would strongly suggest:

- Removing all your Javascript
- Adding a class to one of the parent elements in the HTML markup
- Use CSS media queries to change the styling

**Comment by lavipr** [comment]
PR updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17764">issues.joomla.org/tracker/joomla-cms/17764</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Comment by mbabker** [comment]
Needs a test other than the review after the changes were made.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on dc079e817f92d289f762ec1ffb2316d818612760<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17764">issues.joomla.org/tracker/joomla-cms/17764</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on dc079e817f92d289f762ec1ffb2316d818612760<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17764">issues.joomla.org/tracker/joomla-cms/17764</a>.</sub>

**Pull request merged**
