### PR TITLE
[4.0] Select core extensions

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the redundant word "show" from the language strings. It's a select field so we can assume it means show. We don't say "show" anywhere else

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
For the Featured select type, `Articles` is proper case.  Should `extensions` be too?

```
- Select Featured - 
Unfeatured Articles 
Featured Articles
```

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 75ad4785812e6826087d8a7c99589d14c52e888f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26126">issues.joomla.org/tracker/joomla-cms/26126</a>.</sub>

**Comment by HLeithner** [comment]
Is "- select core -" correct ? shouldn't it be somthing like "select type"? At least I wouldn't understand out of context what "select core" means.

**Comment by brianteeman** [comment]
I wasn't happy with it either but I don't think type is any better and I can't think of anything better

**Comment by ghost** [comment]
– Select Extensions –
Core extensions
Non-core extensions

**Comment by brianteeman** [comment]
I will go with @franz-wohlkoenig suggestion and then hopefully this can be merged

**Comment by HLeithner** [comment]
Still not perfect but better then "core". Thanks.

**Comment by brianteeman** [comment]
small steps

thanks for merging

**Pull request merged**
