### PR TITLE
[5.2] Remove call_user_func()

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove `call_user_func()` in favour of direct call which is faster.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Slow `call_user_func()` call on form field filter.

### Expected result AFTER applying this Pull Request

Fast call.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by mabdelaziz77** [comment]
I have tested this item :white_check_mark: successfully on 38bed8827169669666b6e38b2c81a7173b699216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41988">issues.joomla.org/tracker/joomla-cms/41988</a>.</sub>

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on 38bed8827169669666b6e38b2c81a7173b699216<br /><br />I tested the PR successfully.

I tested the speed using microtime and hrtime
microtime
Before 0.54661
After 0.060788

hrtime
Before 0.002111 miliseconds
After 0.001321 miliseconds

```php
$start = hrtime(true);
// the statement
$end = hrtime(true);
$eta = ($end-$start) / 1e+6;
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41988">issues.joomla.org/tracker/joomla-cms/41988</a>.</sub>

**Comment by richard67** [comment]
@pe7er For setting RTC it is not enough to just add the label on GitHub. It needs to change status in the issue tracker. I will do that now.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41988">issues.joomla.org/tracker/joomla-cms/41988</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for this contribution! 😃

**Pull request merged**
