### PR TITLE
[5.2] Remove trailing slash

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38856 .

### Summary of Changes
renderelement adds a trailing slash when adding css links

link is a void element and the trailing slash should not be used in html5 (it was only needed for xhtml

### Testing Instructions
View the source of the webpage OR use https://validator.w3.org/
Note with chrome inspect is not the same as view source

### Actual result BEFORE applying this Pull Request
all css links in the head of the page have a trailing slash

### Expected result AFTER applying this Pull Request
no trailing slash

additional information
https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97f95b364d0f261a13623ec4f5ba0924d8789ae6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43961">issues.joomla.org/tracker/joomla-cms/43961</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 97f95b364d0f261a13623ec4f5ba0924d8789ae6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43961">issues.joomla.org/tracker/joomla-cms/43961</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43961">issues.joomla.org/tracker/joomla-cms/43961</a>.</sub>

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on b77c3aeb518a074d145905c9586e3b5888978a71<br /><br />I have successfully tested this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43961">issues.joomla.org/tracker/joomla-cms/43961</a>.</sub>

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on b77c3aeb518a074d145905c9586e3b5888978a71<br /><br />Removes all the trailing cross-throughs in the <link /><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43961">issues.joomla.org/tracker/joomla-cms/43961</a>.</sub>

**Comment by Quy** [comment]
Part of PR #43239

**Comment by brianteeman** [comment]
@quy except that PR is wrong

**Comment by Hackwar** [comment]
Thank you for your contribution @brianteeman!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
