### PR TITLE
Smart Search: Fix indexing for Postgres

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #30412 .

This is the second attempt after #31782 to fix indexing and searching in finder in J3. Please test. @HLeithner, @alikon

### CODE REVIEW

**Comment by alikon** [comment]
there are still issues


image

**Comment by Hackwar** [comment]
Can you please give information on which Postgres version you are using there?

**Comment by Hackwar** [comment]
And, sorry for asking since you most likely did, but: Did you reindex again?

**Comment by alikon** [comment]
last test was made on postgresql 12.4 & php 7.4.13
...anyway the postgresql version doesn't really matter, i'm afraid..

i'll recommend you to review #30412 :smile:

**Comment by alikon** [comment]
> Did you reindex again?

i've tested with the Prebuilt package + sample data, and  yes i've reindexed

**Comment by Hackwar** [comment]
I've reworked the PR and it should be working now. Please test.

**Comment by Hackwar** [comment]
This should now fix
1. Indexing of content in Postgres
2. Search in frontend in Postgres and
3. Suggestions for Postgres

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 298b78c75b25840afc4f7c60f4546e6608598a32<br /><br />with postgresql 11.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31809">issues.joomla.org/tracker/joomla-cms/31809</a>.</sub>

**Comment by richard67** [comment]
@Hackwar In the description you wrote:

> This is the second attempt after #31782

I guess you meant #31787 .

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 298b78c75b25840afc4f7c60f4546e6608598a32<br /><br />Suggestions work now on PosgreSQL as well as on MySQL.

There is a problem with suggestions not being shown when the search string starts with a capital letter.

But that's common for MySQL and PostgreSQL and so not related to this PR here.

There is PR #33940 to fix that for J4, but it should be fixed for J3, too, I think.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31809">issues.joomla.org/tracker/joomla-cms/31809</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31809">issues.joomla.org/tracker/joomla-cms/31809</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
