### PR TITLE
Add microdata to breadcrumbs

### PR DESCRIPTION
**Pull request by n9iels**
This PR add Micro Structured Data to the Joomla! breadcrumbs. I followed this guide lines: https://developers.google.com/structured-data/breadcrumbs

Also add some code style and change some `if ($condition) {` to `if ($condition) :` to make the code more readable.
## Test instructions

Confirm that all parameters are working correct like they used do

### CODE REVIEW

**Comment by Fedik** [comment]
looks good,
but changing `ul` to `ol` can have side effect for people who use `ul` as selector in the breadcrumbs styling, I think better keep `ul`

and I do not see `<meta property="position" content="<POSITION_NUM>">`, that need for each item  :wink:

**Comment by n9iels** [comment]
@Fedik Thanks for noticing that :)

I add the `<meta property="position" content="<POSITION_NUM>">` with help of the `$key` variable. But because it has to start with 1 instead of 0, I use `$key + 1`. I'm not realy satisfied about it. Is there someone who knows a better way to do this?

**Comment by Fedik** [comment]
thanks!
`$key + 1` is fine :wink:

**Comment by ghazal** [comment]
Test OK.
I am not very into microdata, but the HTML generated looks allright.

**Comment by zero-24** [comment]
RTC Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7613">issues.joomla.org/joomla-cms/7613</a>.</sub>

**Comment by peterlose** [comment]
Tested with Google's Structured data tester:

skaermbillede 2015-08-04 kl 13 02 55

**Comment by Fedik** [comment]
hm, @peterlose on your  test result still missed `position`

**Comment by n9iels** [comment]
Strange, my test results where good

**Comment by peterlose** [comment]
Shoundn't position be itemprop as well?

```<meta itemprop="position" content="x" />```

**Comment by Fedik** [comment]
@peterlose right, I just noticed this also :smile: 
@n9iels sorry, I gave you the wrong example, before

**Comment by n9iels** [comment]
Changed it, thx for testing

**Comment by Fedik** [comment]
@n9iels thanks, now is better :wink:

**Comment by Kubik-Rubik** [comment]
Thank you @n9iels and testers. Merged with https://github.com/joomla/joomla-cms/commit/ab3de645982b6ebca418fc2b1a2037d093e48622

**Pull request closed without merging**
