### PR TITLE
Update jQuery Autocomplete to 1.2.25

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes

This PR updates jQuery Autocomplete library to version 1.2.25 for _com_finder_ and _mod_finder_.
### Testing Instructions
1. Apply patch
2. Test the _com_finder_ and _mod_finder_ typing any word in search field (for example, _joomla_  :wink:)
3. Make sure there are no JS errors and the list dropdown displayed correctly.
### Result

**com_finder**
com_finder

**mod_finder**
mod_finder

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
test instructions?

**Comment by viocassel** [comment]
@andrepereiradasilva, I have updated test instructions.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 68ebce314bc628f5938cc0a54be1f5c627393177<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10833">issues.joomla.org/joomla-cms/10833</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 68ebce314bc628f5938cc0a54be1f5c627393177<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10833">issues.joomla.org/joomla-cms/10833</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10833">issues.joomla.org/joomla-cms/10833</a>.</sub>

**Pull request merged**
