### PR TITLE
Pluralization fix

### PR DESCRIPTION
**Pull request by saharin88**
Not taken into account 21, 31, etc.

### CODE REVIEW

**Comment by brianteeman** [comment]
@bakual is this a crowdin thing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28941">issues.joomla.org/tracker/joomla-cms/28941</a>.</sub>

**Comment by Bakual** [comment]
No, it's not related to Crowdin and it's also not needed in the english strings.
The variable can be used in ukranian (or any language) regardless if it is present or not in the english string.

**Comment by saharin88** [comment]
> 
> 
> No, it's not related to Crowdin and it's also not needed in the english strings.
> The variable can be used in ukranian (or any language) regardless if it is present or not in the english string.

Yes, I was wrong, everything is right there (method return MORE suffix if 21, 31, etc).

зображення

**Comment by Bakual** [comment]
Actually, you have to adjust the getPluralSuffixes function in your language pack to something like this:
````
if ($count % 10 == 1)
{
    return array('1');
}
.... more cases here
````

Ukranian has some quite complex plural rules as it looks (see https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#uk)

**Comment by infograf768** [comment]
As of 3.9.18 this is the localise.php for the Ukrainian pack
```
	public static function getPluralSuffixes($count)
	{
		if($count == 0)
		{
			$return = [ '0' ];
		}
		else
		{
			$return = [ $count % 10 == 1 && $count % 100 != 11 ? '1' : ($count % 10 >= 2 && $count % 10 <= 4 && ($count % 100 < 10 || $count % 100 >= 20) ? '2' : 'MORE') ];
		}

		return $return;
	}
```

**Pull request closed without merging**
