### PR TITLE
[4.0] Login/Logout page image description [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Continues the work of  #31318 and #31323 by correcting the behaviour of the alt text and changing the strings to match the work done in #31318

This is very slightly different to the other similar PR as before this PR the alt text for the login image was hardcoded and the alt text for the logout page was an untranslated string. In addition the login and logout sections of the options have now been correctly placed into their own fieldsets

chrome_2020-11-07_23-57-08

### Background
To read why this change is very important see #31318 

### Testing Part 1
Testing is really easy. No npm, js or css involved.
Merge the pull request and then create a Login form menu item and add an image for the login and logout

### Testing Part 2

1. Image Description (Alt Text) = Empty
No Description = unchecked

2. Image Description (Alt Text) = "some description"
No Description = unchecked

3. Image Description (Alt Text) = Empty
No Description = checked

The expected behaviour for each of these tests is

1.``
2. `some description`
3. ``
or ``

PLEASE do not comment on what you think the code does but apply the PR and test it. Getting very tired of people blocking PR with their comments without actually testing the code.

cc @carcam

### CODE REVIEW

**Comment by carcam** [comment]
@brianteeman I think this image is most of the time decorative, what do you think about making checkbox checked by default?

**Comment by ceford** [comment]
I am seeing a problem: in scenario 3, with Image Description empty and No Description checked, I get alt="2" for both login and logout image.

&lt;img src="/joomla-cms-4/images/sampledata/parks/landscape/180px_ormiston_pound.jpg" class="com-users-logout__image thumbnail float-right logout-image" alt="2"><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31360">issues.joomla.org/tracker/joomla-cms/31360</a>.</sub>

**Comment by brianteeman** [comment]
@carcam It is impossible to guess that the image is usually decorative and anyway it is better if we are consistent across joomla

@ceford good spot I will look at that

**Comment by carcam** [comment]
@brianteeman you are right. Consistancy is key for a better usability. Thanks!!!

**Comment by vaibhavsTekdi** [comment]
I have tested this item :red_circle: unsuccessfully on dad9c4d12a85e098602e389cfff4795ba7dab333<br /><br />What I found is,

- It gets failed at 3rd scenario i.e. 

Image Description (Alt Text) = Empty
No Description = checked

it gives the result having an only src tag for the image & not the **alt or alt=""**
it gives the result having an only src tag for the image & not the **alt or alt=""**

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31360">issues.joomla.org/tracker/joomla-cms/31360</a>.</sub>

**Comment by punambaravkar** [comment]
I have tested this item :red_circle: unsuccessfully on dad9c4d12a85e098602e389cfff4795ba7dab333<br /><br />I found problem: in scenario 3, with Image Description empty and No Description checked, I get result having an only src tag for the image & not the alt or alt=""<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31360">issues.joomla.org/tracker/joomla-cms/31360</a>.</sub>

**Comment by brianteeman** [comment]
I have fixed the conflicts and the reported bug. Please retest

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on b3c7957d2f76bec6ea05646c3bd311b57273a4ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31360">issues.joomla.org/tracker/joomla-cms/31360</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b3c7957d2f76bec6ea05646c3bd311b57273a4ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31360">issues.joomla.org/tracker/joomla-cms/31360</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
