### PR TITLE
s/releated/related

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/releated/related

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 561b317e764cbec4250a91b05b220bfacb015bce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31929">issues.joomla.org/tracker/joomla-cms/31929</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 561b317e764cbec4250a91b05b220bfacb015bce<br /><br />Tested successfully in Beta7-dev of 9 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31929">issues.joomla.org/tracker/joomla-cms/31929</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31929">issues.joomla.org/tracker/joomla-cms/31929</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
