### PR TITLE
[4.0] media action resize

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the range slider as you cant use a range slider to enlarge see #33568 for further details

To test
apply the pr and npm i

go to media manager and confirm the sliders are gone from the resize tab and that you can still resize using the number inputs

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a2344395f0e58d49bf2fff299cc39ecf73c4cee8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33732">issues.joomla.org/tracker/joomla-cms/33732</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a2344395f0e58d49bf2fff299cc39ecf73c4cee8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33732">issues.joomla.org/tracker/joomla-cms/33732</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33732">issues.joomla.org/tracker/joomla-cms/33732</a>.</sub>

**Comment by richard67** [comment]
@brianteeman These bloody sliders made me completely misunderstand how resizing images in media manager works. For example I wasn't aware of the possibility to enlarge the image by using the number fields because being focused on what the sliders can do. Now I understand and 100% agree with all you said, and am happy when the sliders will have gone.

**Comment by brianteeman** [comment]
Less haste more speed - thanks

**Pull request merged**
