### PR TITLE
[4.0] Centrally aligned icons on dashboard

### PR DESCRIPTION
**Pull request by srishty-07**
Pull Request for Issue  #
Icons are centered 

### Summary of Changes
Added bootstrap class mx-auto in the PHP file.

### Testing Instructions
Go to the dashboard
view the icons.
before the pr, the icons are at the bottom, after this pr the icons are centered in the div

### Actual result BEFORE applying this Pull Request
icon1

### Expected result AFTER applying this Pull Request
Screenshot (65)

icon

### CODE REVIEW

**Comment by drmenzelit** [comment]
The alignment of the icons to the left is a design decision, see PR #33100

**Comment by Fedik** [comment]
@srishty-07 It not a bug, it supposed to be left aligned

**Comment by brianteeman** [comment]
As well as it being a design decision this PR is not correct/complete

image

image

**Comment by srishty-07** [comment]
> The alignment of the icons to the left is a design decision, see PR #33100

Sorry for the inconvenience, should have checked before sending the pr.

> As well as it being a design decision this PR is not correct/complete
> 
 
> image

Thank you @brianteeman  for reviewing the pr,  
sir, I have only added class to the home page icons, not on the add icon.

**Comment by rdeutz** [comment]
beause it is a design decision I am closing this

**Pull request closed without merging**
