### PR TITLE
Administrator main menu list improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR does some improvements to administrator main menu list:
- corrects an html error (missing " between href and title)
- correct spaces between table lines -> (p to div)
- put counters items colors like in categories, banners, contacts components
- code style: adds ; and spaces at the end of php code
- some minor adjustments
##### Before patch:

image
##### After patch:

image
#### How to test
1. Fresh Joomla install with multilanguage (several languages).
2. Apply this patch
3. Go to menus view
4. Check if everything is ok.

### CODE REVIEW

**Comment by justinherrin** [comment]
I have tested this item :white_check_mark: successfully on 3462ea2b33ddc25fe28e0354ea7726f499bc8db9<br /><br />Tested PR successfully. Things look okay.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8830">issues.joomla.org/joomla-cms/8830</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 3462ea2b33ddc25fe28e0354ea7726f499bc8db9<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8830">issues.joomla.org/joomla-cms/8830</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8830">issues.joomla.org/joomla-cms/8830</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@justinherrin, @anibalsanchez  thanks for testing

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 3462ea2b33ddc25fe28e0354ea7726f499bc8db9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8830">issues.joomla.org/joomla-cms/8830</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@wilsonge i will close this PR since you merge it in https://github.com/joomla/joomla-cms/commit/8ca2a4f4336f21a699de58cc95fd5b7d76efdead

**Comment by wilsonge** [comment]
Thanks!

**Pull request closed without merging**
