### PR TITLE
Repairing some inconsistency II

### PR DESCRIPTION
**Pull request by yild**
Simple change in language file, string corrected to match other search descriptions.

Same as #10935

If I would knew about this 'earlier', I would post single PR - sorry ;)

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ff7db5bcf3714aa6d2c5f51fcfe6cd6b904fde47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10936">issues.joomla.org/joomla-cms/10936</a>.</sub>

**Comment by brianteeman** [comment]
Simple fix. Rtc on review can be merged in 3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10936">issues.joomla.org/joomla-cms/10936</a>.</sub>

**Comment by infograf768** [comment]
RC stage. Please change milestone to 3.6.1

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ff7db5bcf3714aa6d2c5f51fcfe6cd6b904fde47<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10936">issues.joomla.org/joomla-cms/10936</a>.</sub>

**Pull request merged**
