### PR TITLE
Wrong desc fixed. Changed title to document!

### PR DESCRIPTION
**Pull request by HRIT-Florian**

### CODE REVIEW

**Comment by chmst** [comment]
The change is correct, review of code. No test is possible becaus it is a comment. 
To satisfy the process: Tested successfully

**Comment by brianteeman** [comment]
Should it not be "description of the document" ?

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on afc007c7f4b59038e00f5a072566201887e11b30<br /><br />Code review. Fixes obvious error in DocBlock comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19685">issues.joomla.org/tracker/joomla-cms/19685</a>.</sub>

**Comment by HRIT-Florian** [comment]
Yesss and done @brianteeman

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6ca379e565982fcf9e2e0d4668b487d8f0b813a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19685">issues.joomla.org/tracker/joomla-cms/19685</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6ca379e565982fcf9e2e0d4668b487d8f0b813a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19685">issues.joomla.org/tracker/joomla-cms/19685</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19685">issues.joomla.org/tracker/joomla-cms/19685</a>.</sub>

**Pull request merged**
