### PR TITLE
[4.4] Backendmenu: Fixing import of presets for menu items (ajaxbadge, ...)

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
When importing a backend menu preset into a backend menu, the information for dashboard elements and ajax badges gets lost. 

### Testing Instructions
1. Go to menu manager and filter by admin
2. create a new menu and select "Preset - Joomla Main Menu" as preset and save.
3. Create a module for the menu and set it to position "menu"

### Actual result BEFORE applying this Pull Request
The second backend menu is missing both dashboard and potential ajax badge icons. (The Main Menu preset doesn't have an ajax badge)

### Expected result AFTER applying this Pull Request
The dashboard icons show up.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
Perhaps I didn't understand the description but for me, nothing seems to have changed before or after having applied the Patch 

1st without patch 43189 applied:

without-patch-43189-applied

2nd with patch 43189 applied:
with-patch-43189-applied

@Hackwar what did I miss?

**Comment by Hackwar** [comment]
Did you import the menu items before or after applying the patch? If you imported the preset before applying the patch, that is exactly the issue this PR is trying to fix: The import (which creates a bunch of menu items in the database) does not take care of the additional features. Applying the patch afterwards doesn't change the data which has been written to the database.

**Comment by akshehu** [comment]
For me, all seem to work well after following the process and testing. All good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43189">issues.joomla.org/tracker/joomla-cms/43189</a>.</sub>

**Comment by akshehu** [comment]
I have tested this item :white_check_mark: successfully on 344dff503543253d92dca6b89def0556368f82fb<br /><br />For me, all seem to work well after following the process and testing. All good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43189">issues.joomla.org/tracker/joomla-cms/43189</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 344dff503543253d92dca6b89def0556368f82fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43189">issues.joomla.org/tracker/joomla-cms/43189</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
