### PR TITLE
s/objecct/object

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/objecct/object

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 011a9db97d60a2f334d4fe2b4eca78377d1ef335<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31935">issues.joomla.org/tracker/joomla-cms/31935</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 011a9db97d60a2f334d4fe2b4eca78377d1ef335<br /><br />Tested successfully in Beta7-dev of 9 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31935">issues.joomla.org/tracker/joomla-cms/31935</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31935">issues.joomla.org/tracker/joomla-cms/31935</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
