### PR TITLE
Fix for: zero or negative values on session lifetime.

### PR DESCRIPTION
**Pull request by maxvalentini77**
### Zero or negative values on session lifetime

Session lifetime is an integer value and should be setted to a positive value greater than zero.
- Negative value cause that the session to be always "expired".
- Zero behavior is equals to the default value of 15 minute, this behavior is not explict and can be obtained setting 15 minutes of lifetime, so i remove zero from the valid range.

### CODE REVIEW

**Comment by zero-24** [comment]
### How to test

- try to insert and save a value of zero as session time
- make sure no issues are reported
- apply the patch
- try zero again
- repeat the test with 1 and 2 as values (both should work)

Thanks @maxvalentini77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6954">issues.joomla.org/joomla-cms/6954</a>.</sub>

**Comment by Fedik** [comment]
I still able to save negative value:
screen 2015-05-16 13 46 52 492x135

**Comment by Fedik** [comment]
I think problem that there no backend validation for this input, 
also filter="integer" allow negative value,
min="1" have not much effect at least in my Chrome browser :smile:

**Comment by izharaazmi** [comment]
@maxvalentini77 I suggest to add `filter="uint"` as well to the field, though I don't see it as necessary.

**Comment by maxvalentini77** [comment]
@Fedik You are right, I'm working on a server side validation.
@izharaazmi Thanks for the tip!

**Comment by maxvalentini77** [comment]
Added number validator to check min/max range for number fields.
Added the validator to cachetime and session lifetime, both setted with min of 1.

**Comment by zero-24** [comment]
RTC based on testing by @ChrisBreaks and @jonnyefftek on #jab15 #makeithappen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6954">issues.joomla.org/joomla-cms/6954</a>.</sub>

**Comment by watchfulli-dev** [comment]
@test test resutls are: without patch applied, there's no error displayed and you can enter 0 inside "Session Lifetime " field. After applying the patch if you try to enter 0 as a value inside "Session Lifetime " field, you get this error: "Invalid field: Session Lifetime"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6954">issues.joomla.org/joomla-cms/6954</a>.</sub>

**Comment by Bakual** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/b649299e9f90a024e3c0aa1fd3af88bc2d28ac27 into `3.5-dev`.

Thanks!

Is there a list of available JFormRules somewhere? If so that would need updated as we introduce a new one here.

**Comment by losedk** [comment]
@Bakual Should the doc block say ```@since xx.x```?

**Comment by maxvalentini77** [comment]
I wrote xx.x in the attribute because i didn't know in which version this class will be introduced. Now should contain 3.5.0, right?

**Comment by zero-24** [comment]
Correct @maxvalentini77 can you just send a quick PR that fixes that?

**Comment by maxvalentini77** [comment]
@zero-24 I create a new PR #7109 it's ok?

**Comment by Bakual** [comment]
Awww. I usually don't look at the doc blocks close enough...

**Comment by zero-24** [comment]
>@zero-24 I create a new PR #7109 it's ok?

:+1: Thomas allready merged it. Thanks

**Pull request closed without merging**
