### PR TITLE
[4.0] Notices in articles layouts

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Preventing Notices for articles `image_intro_caption` and `image_fulltext_caption` when these fields are empty

### Testing Instructions
Display a blog of articles for which you have not set any image captions whether for full or intro text.
Display a full single article.

In both cases you will get a Notice
`Trying to get property of non-object in ROOT//layouts/joomla/content/intro_image.php on line 16`
and
`Trying to get property of non-object in ROOT//layouts/joomla/content/full_image.php on line 14`

Patch and test again.

NOTE: When we have captions, they display on top of the image and not below. This PR does not correct this.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Remove `$caption` variable and use the property directly, like before #20153. Also change caption check to compare against empty string (`0` is a valid value for caption, IMO).
```
<?php if ($images->image_intro_caption !== '') : ?>
	<figcaption class="caption"><?php echo htmlspecialchars($images->image_intro_caption); ?></figcaption>
<?php endif; ?>
```

**Review by wilsonge — APPROVED** [review]

**Comment by Bakual** [comment]
Good catch (shame on me)

@SharkyKZ is spot on. You can remove that caption variable.
I had this added originally because the caption was tested in two places, but the second place was removed again later. So it's superfluous now.

As for the caption before the image or after, I don't know anymore why I did it this way, probably worked from an example where it was like this. It can sure be changed.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5814d625e6efb5c905557f5311da30c4f0c56af0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20503">issues.joomla.org/tracker/joomla-cms/20503</a>.</sub>

**Comment by laoneo** [comment]
Just saw the comments, will retest when the suggested changes are done.

**Comment by infograf768** [comment]
Got rid of the $caption variable.

Will make a new PR after merge to display the caption under the image as it is the most common way for a caption.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 906924a99860e730b1a8abae4c3958f577854799<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20503">issues.joomla.org/tracker/joomla-cms/20503</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 37426a61df15e6865da9a429a402f7e5c87bf57a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20503">issues.joomla.org/tracker/joomla-cms/20503</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 37426a61df15e6865da9a429a402f7e5c87bf57a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20503">issues.joomla.org/tracker/joomla-cms/20503</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20503">issues.joomla.org/tracker/joomla-cms/20503</a>.</sub>

**Comment by wilsonge** [comment]
Thanks JM!

**Comment by Razzo1987** [comment]
I found the same problem in Joomla 4.0 Beta 1
In `/layouts/joomla/content/intro_image.php` the cose is:
```
		<?php if ($images->image_intro_caption !== '') : ?>
			<figcaption class="caption"><?php echo htmlspecialchars($images->image_intro_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
		<?php endif; ?>
```

My article have only Intro Image, without Caption

I suggest change the code with:

```
		<?php if (!empty($images->image_intro_caption)) : ?>
			<figcaption class="caption"><?php echo htmlspecialchars($images->image_intro_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
		<?php endif; ?>
```

**Pull request merged**
