### PR TITLE
[4.0] Remove obsolete variable

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove obsolete variable that was removed in #25360.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 9ab81819d4672e15c89ecca8a33f855162213cdb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25659">issues.joomla.org/tracker/joomla-cms/25659</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9ab81819d4672e15c89ecca8a33f855162213cdb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25659">issues.joomla.org/tracker/joomla-cms/25659</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25659">issues.joomla.org/tracker/joomla-cms/25659</a>.</sub>

**Comment by Hackwar** [comment]
Please don't create branches in the official Joomla repo.

**Comment by HLeithner** [comment]
thx and please don't create branches in joomla-cms

**Pull request merged**
