### PR TITLE
[5.2] Move the Cypress Tests to ESM

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Move to ESM (no `require()`)
- use `.mjs` for the esm modules

### Testing Instructions

If tests pass, everything is ok. Just review the code

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@richard67 could you bless the drone config?

### CODE REVIEW

**Comment by HLeithner** [comment]
@laoneo would you like to merge this? in 5.1 or 5.2?

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by dgrammatiko** [comment]
I guess there's no interest for this

**Comment by laoneo** [comment]
Please reopen, this is a great step forward. I will see what we can do here.

**Comment by dgrammatiko** [comment]
Hmm, it seems I can't do that on GitHub so I guess I have to redo this

**Pull request closed without merging**
