### PR TITLE
[4.0] Remove JHELP_ strings for com_config

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #35416 can partly replace #35418.

### Summary of Changes
This PR removes the JHELP_COMPONENTS_COM_FOO_OPTIONS language strings and puts the reference keys into the respective config.xml as help entry.
`com_config` already supported this notation, so it doesn't need a single line changed withing PHP code.

### Testing Instructions
Test the help buttons in the options of the various core components

### Actual result BEFORE applying this Pull Request
Help buttons work

### Expected result AFTER applying this Pull Request
Help buttons work, no change in behavior.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 88f4c0642141a0ab6be8b56df5fc14dcda58eb1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35479">issues.joomla.org/tracker/joomla-cms/35479</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 88f4c0642141a0ab6be8b56df5fc14dcda58eb1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35479">issues.joomla.org/tracker/joomla-cms/35479</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35479">issues.joomla.org/tracker/joomla-cms/35479</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
