### PR TITLE
[com_finder] maps view: searchtools ordering, bug corrections and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issues/Improvements.
#### Summary of Changes

This PR normalizes this view by adding the ordering to the searchtools in com_finder maps view. 

Also:
- Corrects some bugs in the searchtools (for instance, https://github.com/joomla/joomla-cms/issues/10061).
- Some code style improvements.
- Some code improvements.
- Normalizes layout with other views.
- Added max level filter.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use latest staging and apply patch
2. Go to Components -> Smart Search -> Filters (Create some index)
3. Go to Components -> Smart Search -> Content Maps
4. Test if search, filters, ordering and page limit (aka searchtools) are working properly.
5. Test also if the toolsbar buttons work properly.

@chrisdavenport to normalize this view with other views, i created two levels of content (branches/childs). Can you confirm there can exist more levels in the finder content maps? thanks

The levels are obtined from [this query](https://github.com/andrepereiradasilva/joomla-cms/blob/com_finder-maps-searchtools/administrator/components/com_finder/models/maps.php#L179-L195).

### CODE REVIEW

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on cb080d918857c5a856a07616c7822a978790d3ec<br /><br />Content maps are intended to be "flat" and we have no immediate plans to make them hierarchical.  So Max Levels cannot be greater than 2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10068">issues.joomla.org/joomla-cms/10068</a>.</sub>

**Comment by andrepereiradasilva** [comment]
nice thanks!

**Comment by brianteeman** [comment]
You have made a language string change but I didnt find yet where that is used

**Comment by andrepereiradasilva** [comment]
```bash
# egrep -R "COM_FINDER_ITEM_X_ONLY" /path/to/joomla-staging/
/path/to/joomla-staging/administrator/language/en-GB/en-GB.com_finder.ini:COM_FINDER_ITEM_X_ONLY="%s Only"
/path/to/joomla-staging/administrator/components/com_finder/helpers/html/finder.php:                       $string = JText::sprintf('COM_FINDER                                                    _ITEM_X_ONLY', JText::_($key));
/path/to/joomla-staging/administrator/components/com_finder/helpers/html/finder.php:                       $string = JText::sprintf('COM_FINDER                                                    _ITEM_X_ONLY', JText::_($key));
/path/to/joomla-staging/administrator/components/com_finder/helpers/html/finder.php:               $options[] = JHtml::_('select.option', '1',                                                     JText::sprintf('COM_FINDER_ITEM_X_ONLY', JText::_('JPUBLISHED')));
/path/to/joomla-staging/administrator/components/com_finder/helpers/html/finder.php:               $options[] = JHtml::_('select.option', '0',                                                     JText::sprintf('COM_FINDER_ITEM_X_ONLY', JText::_('JUNPUBLISHED')));
```

**Comment by brianteeman** [comment]
I know how to use grep ;)

I am looking for the real world example of the strong being used <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10068">issues.joomla.org/joomla-cms/10068</a>.</sub>

**Comment by andrepereiradasilva** [comment]
eheheh

The "[...] Only" is used at least here:
image

**Comment by brianteeman** [comment]
Thanks - I see it now. Which brings the question why is that a plural. The branch is singular isnt it? @chrisdavenport <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10068">issues.joomla.org/joomla-cms/10068</a>.</sub>

**Comment by chrisdavenport** [comment]
The top-level branch name should be the singular form since that is used in the query "language" where it makes sense.  For consistency, I agree that it would make sense for the drop-down to also use the singular forms.

I've been giving this a little thought and I think that "map group" would be a better term than "branch" in this context.  We already refer to the page as "Content Maps" so I think we should reinforce that term rather than introducing any new ones.

I'm thinking that the page should show a list with columns "Status", "Title", "Maps" and "Content items".  The drop-down "Select branch" becomes "Select map group".  The column "Maps" contains the number of maps within the map groups (this is something that was dropped in this PR, but is actually quite useful).  The column "Content items" replaces "Nodes".

**Comment by brianteeman** [comment]
Can you post that in the en-gb issues and I will take a look at it there.
Shouldn't effect this PR.

**Comment by chrisdavenport** [comment]
Good idea, although I'd like to see the maps count re-introduced in the PR.

**Comment by brianteeman** [comment]
OK @andrepereiradasilva please put the count back and we will discuss the language strings in the user interface group

**Comment by andrepereiradasilva** [comment]
> put the count back

What count?

**Comment by andrepereiradasilva** [comment]
by "count" do you mean the level 1 count?

image

I remvoed it because this way is more in line with other views (don't have tree subitems count).

**Comment by andrepereiradasilva** [comment]
but ok i will put it. and put singular forms in the filters.
The rest will leave for discussion in https://github.com/joomla/user-interface-text/issues/58 for another PR perhabs.

**Comment by chrisdavenport** [comment]
@andrepereiradasilva Thanks.  That count can be quite useful, especially when debugging a search plugin.  Sometimes the number can be in the hundreds so it would be a bit tedious to count them by hand. ;-)

**Comment by andrepereiradasilva** [comment]
done

image

**Comment by andrepereiradasilva** [comment]
BTW @chrisdavenport i don't understand much of the com_finder. never used it mysqlf.
Can you enlighten me? why does exist a branch "Category" and then a "Category" inside the branch "Type"?

**Comment by andrepereiradasilva** [comment]
conflicts fixed.

@chrisdavenport @brianteeman Please retest so we finish the com_finder searchtools review (this is the only one missing).

The terms we can change in another PR when decided.

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on 1b99d5aedd79727dddde3afe08cfafb788ace32f<br /><br />This is fine for now, but as noted, the terminology should be reviewed.

Good work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10068">issues.joomla.org/joomla-cms/10068</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10068">issues.joomla.org/joomla-cms/10068</a>.</sub>

**Pull request merged**
