### PR TITLE
[4.0] Fix Article show_associations parameter

### PR DESCRIPTION
**Pull request by infograf768**
The `show_associations` parameter in the article lets display or not the associations for a single article in frontend.
Example:
Screen Shot 2019-10-29 at 10 57 55

### Summary of Changes 
Displays the parameter only when site is multilingual and associations are enabled by creating a specific fieldset as placing this parameter in Category is wrong anyway.
Add the flags/no flags parameter
Corrects cs for the xml (tabs instead of spaces, training spaces.)

### Testing Instructions
Create a multilingual site. 

Create or edit an article.
Display Options tab.

After patch
Switch Associations off and on in the languagefilter plugin and look at the Options again

### Before patch
The `Associations` parameter is wrongly placed in the Category fieldset

Screen Shot 2019-10-29 at 10 40 59

Switching associations to OFF in the plugin still displays the parameter

### After patch
Associations ON in the plugin

art_assoc_after

Associations OFF in the plugin
Screen Shot 2019-10-29 at 10 45 38

### CODE REVIEW

**Comment by infograf768** [comment]
Note: something similar could be done for the single article menu item. A bit more complex as I guess we should not add a specific `ignore_fields` for the parameter in the menu item edit.php

**Comment by vaibhavsTekdi** [comment]
I have tested this item :white_check_mark: successfully on dbc2cf86add4c5df832f76bc8206e7a9e40ddf10<br /><br />#pbf19 #test1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26853">issues.joomla.org/tracker/joomla-cms/26853</a>.</sub>

**Comment by punambaravkar** [comment]
I have tested this item :white_check_mark: successfully on dbc2cf86add4c5df832f76bc8206e7a9e40ddf10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26853">issues.joomla.org/tracker/joomla-cms/26853</a>.</sub>

**Comment by KishoriBKarale** [comment]
I have tested this item :white_check_mark: successfully on dbc2cf86add4c5df832f76bc8206e7a9e40ddf10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26853">issues.joomla.org/tracker/joomla-cms/26853</a>.</sub>

**Comment by infograf768** [comment]
rtc
tks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26853">issues.joomla.org/tracker/joomla-cms/26853</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
