### PR TITLE
[4.0] Media Manager create new folder: placeholder removed and text changed

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #20369 

### Summary of Changes
placeholder removed
save button changed

### CODE REVIEW

**Comment by puneeth-chanda** [comment]
@infograf768 @Quy can you please review this.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b3fcfd97b6b3ed2a0bea4775758a1ab1704c1d99

After patch:

screen shot 2019-02-26 at 07 28 11

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24018">issues.joomla.org/tracker/joomla-cms/24018</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :red_circle: unsuccessfully on b3fcfd97b6b3ed2a0bea4775758a1ab1704c1d99<br /><br />I see the new button, but I still see the paceholder.

After patch:

img
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24018">issues.joomla.org/tracker/joomla-cms/24018</a>.</sub>

**Comment by infograf768** [comment]
To test this, one needs to run npm ci on the test site. One can't just apply the patch.

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on b3fcfd97b6b3ed2a0bea4775758a1ab1704c1d99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24018">issues.joomla.org/tracker/joomla-cms/24018</a>.</sub>

**Comment by infograf768** [comment]
RTC Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24018">issues.joomla.org/tracker/joomla-cms/24018</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on b3fcfd97b6b3ed2a0bea4775758a1ab1704c1d99<br /><br />sorry!
with npm ci works :D
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24018">issues.joomla.org/tracker/joomla-cms/24018</a>.</sub>

**Comment by dneukirchen** [comment]
code lgtm, thx.

**Pull request merged**
