### PR TITLE
[4.4] Reverting parts of #40257

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #40430.

### Summary of Changes
In #40430 an issue came up where updating failed because the framework class File wasn't available in /administrator/components/com_admin/script.php. This PR reverts that change from #40257. We will eventually have to switch over the whole update process from File/Folder/etc to the framework classes and update the finalisation.php as well.

### Testing Instructions
Codereview.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 91e63b83105ef5735d112c24fa414619964079bb<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40569">issues.joomla.org/tracker/joomla-cms/40569</a>.</sub>

**Comment by laoneo** [comment]
Waiting here for @MacJoom as he is currently testing the upgrades as well to see if we can reproduce the issue on our end.

**Comment by richard67** [comment]
@laoneo @MacJoom This PR here is one of the few rare cases where a review is sufficient and clear. Just check what is in file extract.php of the update component. Check the namespace used there for the mocked file system libs, and check that the change in script.php fits to that. When doing updates it can happen on the same environment that one time the real filesystem libs or the stuff in extract.php is used, and another time the real lib. So it might be hard to catch the issue with a real test.

**Comment by laoneo** [comment]
On some point we want to make the switch to the framework classes. We will face then the same issue again. So it makes sense to invest a bit of resources as we are aware of the issue right now and do some testing on what to do to properly fix it. Because in my opinion all is needed is to change the namespace [here](https://github.com/joomla/joomla-cms/blob/4.4-dev/administrator/components/com_joomlaupdate/finalisation.php#L87). This basically what Nik suggested in the comment https://github.com/joomla/joomla-cms/pull/40430#issuecomment-1529665048. So I would prefer to see if that fix would work, but first we need to be able to reproduce it.

**Comment by richard67** [comment]
@laoneo No it is not sufficient to change the namespace at that one place in extract.php because this namespace contains the mocks for the file and for the folder class and the CMS has not been changed yet to move to the framework for the folder class, so we would need 2 namespaces in extract.php as long as that is not done.

**Comment by Hackwar** [comment]
Yes, @richard67, thanks for explaining this. Indeed, we will have to switch over at one point, but that would happen when we have switched all other code over. At that point we would also have to check the classes which are included in the finalisation.php and update that code where necessary. With this, we actually don't have one or two, but three different implementations of the File and Folder class and I'm pretty sure that they are all not in sync to each other. So there is more work to do than just to change the namespace of the filesystem package in the finalisation.php.

**Comment by richard67** [comment]
@Hackwar If you like to have some co-worker for the script.php and extract.php files I volunteer because I know these 2 files well.

**Comment by laoneo** [comment]
Can we then not just load composer in the finalization script and get completely rid of the fake namespaces?

**Comment by richard67** [comment]
For now I would say this PR here is the quick fix so people can test updating with nightlies, and the bigger clean-up we do soon after that and have it hopefully ready for 4.4-alpha1.

**Comment by richard67** [comment]
> Can we then not just load composer in the finalization script and get completely rid of the fake namespaces?

I don‘t know, but would be cool of course if we could get rid of the fake namespace.

**Comment by laoneo** [comment]
Agree that we should first accept here and then have a look if we can deal something with the framework package.

**Comment by laoneo** [comment]
Thanks @Hackwar for stepping up so quickly!

**Pull request merged**
