### PR TITLE
[4.0] Move a subform template out of the form scope, for IE compatibility.

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #24832 for Joomla 4.0 version

This fix the subform field in IE, when one of subfield are required.

### Testing Instructions

before test run `npm install`
Please look for related issue for details.

### CODE REVIEW

**Comment by Quy** [comment]
> SCRIPT438: Object doesn't support property or method 'append'
webcomponents-sd-ce-pf.min.js (1,56047)

Related issue #23822

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js#L191

This should be `appendChild()`, as `append()` is still experimental

**Comment by Fedik** [comment]
@C-Lodder yeah, you are right, thanks, I will change

**Comment by brianteeman** [comment]
This PR can probably be closed as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019

**Comment by Fedik** [comment]
yeah

**Pull request closed without merging**
