### PR TITLE
Update fields.php

### PR DESCRIPTION
**Pull request by Alex4Shch**
Pull Request for Issue # .

### Testing Instructions
0 - Call to a member function get() on null after update 3.9.5

1 | () | JROOT\administrator\components\com_fields\helpers\fields.php:577
2 | FieldsHelper::displayFieldOnForm() | JROOT\administrator\components\com_fields\libraries\fieldsplugin.php:121
3 | FieldsPlugin->onCustomFieldsPrepareField() | JROOT\libraries\joomla\event\event.php:70
4 | JEvent->update() | JROOT\libraries\joomla\event\dispatcher.php:160
5 | JEventDispatcher->trigger() | JROOT\administrator\components\com_fields\helpers\fields.php:200
6 | FieldsHelper::getFields() | JROOT\plugins\system\fields\fields.php:488
7 | PlgSystemFields->onContentPrepare() | JROOT\libraries\joomla\event\event.php:70
8 | JEvent->update() | JROOT\libraries\joomla\event\dispatcher.php:160
9 | JEventDispatcher->trigger() | JROOT\components\com_content\views\featured\view.html.php:102
10 | ContentViewFeatured->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
11 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\components\com_content\controller.php:118
12 | ContentController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
13 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\components\com_content\content.php:43
14 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
15 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
16 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:194
17 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:233
18 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:196
19 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\index.php:49

### CODE REVIEW

**Comment by ghost** [comment]
@Alex4Shch can you please give of Changes, Test Instructions, ...?

**Comment by ghost** [comment]
@HLeithner should this be closed due the lack of response?

**Comment by HLeithner** [comment]
@Alex4Shch we some more information, it seams you have custom fields and one of them creates this error.

@franz-wohlkoenig you can close it if we don't get a response this week.

**Comment by brianteeman** [comment]
Yes. It's obviously not important to the submitter.

**Pull request closed without merging**
