### PR TITLE
2 to 1 loop optimization in plugins/search/categories/categories.php

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
This PR optimizes two independent loops of the same  (one `for` and one `foreach`) into a single loop.
Additionally, the costly assignments are now only executed, when it makes sense (aka the condition is true).

This PR is an optimized extension of the rejected PR #12299

### Testing Instructions
Should not change behavior. 
Code review

### Documentation Changes Required
None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 83c643512d17470350295e15f430aa923dfeb804<br /><br />Code review.
Also aplied patch, enabled search component and search plugins, created categories and frontend search found the categories.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13390">issues.joomla.org/tracker/joomla-cms/13390</a>.</sub>

**Comment by fastslack** [comment]
@test all seems to work as expected after apply this patch. This change has sence . Code review ok.

**Comment by laoneo** [comment]
@frankmayer can you please exclude com_fields and the system plugin from your code style cleanup. I do a bigger refactoring and don't want to solve conflicts regularly. Thanks for understanding.

**Comment by frankmayer** [comment]
@laoneo of course, I understand. Will exclude those in future cleanups (I'll check on current ones). Would you be so kind to let me know, when this work can be resumed?

**Comment by frankmayer** [comment]
@laoneo reverted in existing PRs with the following commits:
- https://github.com/joomla/joomla-cms/pull/12228/commits/b7636dc9b7197a3c295831a8bd8315c3446f0a21
- https://github.com/joomla/joomla-cms/pull/13272/commits/669da6fb9907920386eaaaf6cc5c547c4dfe091e
- https://github.com/joomla/joomla-cms/pull/13249/commits/7a4953affb97954fffcf83e26a6f9ea2898b7e8b

It would be good, if you can include those changes directly though, if still applicable.

**Comment by laoneo** [comment]
Thanks, when PR #13319 is merged.

**Pull request merged**
