### PR TITLE
RTL: Fix overwrite by .table-striped

### PR DESCRIPTION
**Pull request by mansourcodes**
Fix overwrite by administrator/templates/isis/css/template.css line 1787

table.table-striped tbody > tr:nth-child(odd) > td,
table.table-striped tbody > tr:nth-child(odd) > th {
	background-color: #f9f9f9;
}

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
There was a reason that we ask you to complete the questions that you chose to ignore. Having looked at the pr and made a guess I dont see any changes in the resulting css. Please explain - perhaps with pictures. What the problem is and how this pr resolves it.

**Comment by ReLater** [comment]
### Testing instructions
https://github.com/joomla/joomla-cms/pull/20180#issuecomment-382737453
But use a rtl language for testing this pr.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1d44f64f46ace953b620e3c734f2a8c19c272737<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20179">issues.joomla.org/tracker/joomla-cms/20179</a>.</sub>

**Comment by Quy** [comment]
@ReLater Can you please test? Thanks.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 1d44f64f46ace953b620e3c734f2a8c19c272737<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20179">issues.joomla.org/tracker/joomla-cms/20179</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20179">issues.joomla.org/tracker/joomla-cms/20179</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20179">issues.joomla.org/tracker/joomla-cms/20179</a>.</sub>

**Pull request merged**
