### PR TITLE
[4.0] Table status icons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #16000 (part of).

### Summary of Changes
Initial PR to apply #16000. 
- Creates a style class (`tbody-icon`) and applies it to the list status icons. 
- Moves the 'checked-in' icon to the status column.

### Testing Instructions
Apply PR and navigate to table list containing 'status' icons.

### Before PR
status-icons1

### After PR
status-icons2

### CODE REVIEW

**Comment by brianteeman** [comment]
what would happen if it is featured and locked

**Comment by C-Lodder** [comment]
@brianteeman the lock icon should appear next to the "featured" icon.

@ciar4n - might be an idea to remove the `style="width:1%"` from the status `<th>` so that it doesn't wrap.

**Comment by ciar4n** [comment]
Currently only the locked icon will appear (2nd item in the screenshot).

I could add a 3rd icon instead? Just means the status column would be wider and a little busy looking..

status-icons3

**Comment by brianteeman** [comment]
I think you see the issue that i raised now.
Having a third column just to show an icon that really should never be seen is not great but at the same time you need to have it as you cant show all three otherwise. 

Might need to rethink the idea of moving the locked icon next to featured. 

I would also raise a question that the lock icon is not the same as the others you are displaying it with. All the others are both an indicator and an action but locked is only an indcator

**Comment by ciar4n** [comment]
@C-Lodder There is a `nowrap` class on it so should be ok. Removing the style gives some varying widths depending on browser/table width

**Comment by ciar4n** [comment]
As you point out, having a 3rd icon column for a relatively rare usage doesn't make much sense. Moving back inline with the title might be the way to go.

**Comment by brianteeman** [comment]
@ciar4n unfortunately I think thats best for now

**Comment by ciar4n** [comment]
Latest commit moves locked icon inline with title...

status-icons4

**Comment by dgt41** [comment]
@ciar4n here is another idea about the checkin icon:
If the row needs to be checked out (icon should appear) then the other icons shouldn't display
else you just display the publish/featured

**Comment by wilsonge** [comment]
> PS From a workflow also this sounds the correct approach, e.g. if someone is editing this article, publishing or featuring that article doesn't sound a good idea...

But someone looking at the list should be able to see whether they are published/featured or not

**Comment by ciar4n** [comment]
@dgt41 So basically this?... 

status-icons5

**Comment by brianteeman** [comment]
It would also fail on accessibility etc.

**Comment by dgt41** [comment]
> But someone looking at the list should be able to see whether they are published/featured or not

The article is currently edited by another user, unless they finish their task (e.g. unpublish a published article) the information **could** be wrong, think about it...

**Comment by wilsonge** [comment]
They can't change the information, but they should to be able to see a 'read-only' published state at minimum

**Comment by dgt41** [comment]
> but they should to be able to see a 'read-only' published state at minimum

But that info **might be wrong** if the person editing the article changes that state, so what's the point displaying some **previous, inaccurate** state?

**Comment by dgt41** [comment]
> It would also fail on accessibility etc.

@brianteeman why?

**Comment by brianteeman** [comment]
@dgt41 by that argument everything displayed on the row might be wrong

**Comment by dgt41** [comment]
> by that argument everything displayed on the row might be wrong

Good point! everything except the ID

**Comment by C-Lodder** [comment]
@ciar4n `nowrap` is for J3. The class hasn't been mapped. :)

**Comment by ciar4n** [comment]
@C-Lodder Ah I see what you mean. We do have the following so I guess them `nowrap`s can be removed... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_table.scss#L6

**Comment by C-Lodder** [comment]
It's on my to-do list

**Comment by brianteeman** [comment]
I just noticed that one of the aims of this PR is to remove the matching toolbar buttons in favour of the action list. I dont think thats a great idea as currently that would mean there was no way to do a mass action eg unpublish all the articles

**Comment by ciar4n** [comment]
This particular PR is just for the icon styling. Regarding #16000 the action list will apply to the selected items...

status-icons6

**Comment by brianteeman** [comment]
ah - ok - missed that part - cool

**Comment by C-Lodder** [comment]
Everything working fine for me. Just needs applying to the rest of the components

**Comment by ciar4n** [comment]
Thanks Charlie.. Done

**Comment by C-Lodder** [comment]
**Still to do:**

- com_categories
- com_content (featured view)
- com_banners
- com_newsfeeds
- com_redirect
- com_finder
- com_tags
- com_installer
- com_modules
- com_plugins
- com_languages
- com_menus

:)

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 04bd98ebbe72cb1e5c3f484763c0715ff42fc3f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16015">issues.joomla.org/tracker/joomla-cms/16015</a>.</sub>

**Comment by wilsonge** [comment]
Needs something in the redirect component too :)

**Comment by ciar4n** [comment]
@wilsonge Good catch.. Done

**Pull request merged**
