### PR TITLE
[4.0] [com_cache] Fix cached items not shown

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes cache items not shown in `com_cache`.

### Testing Instructions

Enable Cache in Global Configuration or System - Page Cache plugin.
Visit frontend as guest.
In backend go to System -> Clear Cache.

### Expected result

Some cached items are shown.

### Actual result

No cached items are shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d08d1cf86241c2ad5b389702f25d61e7d2930280<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27069">issues.joomla.org/tracker/joomla-cms/27069</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d08d1cf86241c2ad5b389702f25d61e7d2930280<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27069">issues.joomla.org/tracker/joomla-cms/27069</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27069">issues.joomla.org/tracker/joomla-cms/27069</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
