### PR TITLE
New Module select

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Remove the extra space after the name of the module in the link
#### Testing Instructions

Go to create a new module and check that the extra space has been removed at the end of the link

PS I have no idea why the space is appearing just because the closing a tag is on a new line but removing the new line fixes it

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ffc66e578789ca51167c4605cdfcdd9ff3f2de83<br /><br />Workd fine.

The space is appearing because some browsers (ex: Chrome) add a space if there are tabs or line breaks inside the anchor `a` HTML tag.

See, for instance, the same problem here https://github.com/joomla/joomla-cms/pull/8206<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9827">issues.joomla.org/joomla-cms/9827</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on ffc66e578789ca51167c4605cdfcdd9ff3f2de83<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9827">issues.joomla.org/joomla-cms/9827</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9827">issues.joomla.org/joomla-cms/9827</a>.</sub>

**Comment by bembelimen** [comment]
Could you remove the space before, too?

**Comment by andrepereiradasilva** [comment]
i have no space before, what browser are you using?

**Comment by brianteeman** [comment]
I tested in chrome, firefox and safari on osx and didnt have a space before

On 10 April 2016 at 14:24, andrepereiradasilva <notifications@github.com>
wrote:

> i have no space before, what browser are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9827#issuecomment-207984606>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bembelimen** [comment]
My fault, everything is OK, sry

**Pull request merged**
