### PR TITLE
create script added

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #20369

### this is the file which must be added to the PR #23721
Create script is added

### CODE REVIEW

**Comment by Quy** [comment]
Please close this PR and add it to #23721

**Comment by puneeth-chanda** [comment]
sorry, I don't know how to add it, can I know how

**Comment by Quy** [comment]
Go to the branch in your fork and update it there:
https://github.com/puneeth2001/joomla-cms/tree/placeholder

**Comment by puneeth-chanda** [comment]
added to #23721

**Comment by puneeth-chanda** [comment]
is it ok @Quy

**Comment by Quy** [comment]
I don't see it in the other PR. Make sure to commit the change to the other PR.

**Comment by puneeth-chanda** [comment]
I have updated it can you please check once

**Pull request closed without merging**
