### PR TITLE
[4.2] codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
npm run lint:js reports errors in this file

this pr fixes them

code review should be fine as identical code style can be seen on the span below

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 90db85aa5eb94a588736e6117c710933d772a84a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38262">issues.joomla.org/tracker/joomla-cms/38262</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 90db85aa5eb94a588736e6117c710933d772a84a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38262">issues.joomla.org/tracker/joomla-cms/38262</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38262">issues.joomla.org/tracker/joomla-cms/38262</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
