### PR TITLE
[5.0] Dark Mode: Versions toolbar

### PR DESCRIPTION
**Pull request by brianteeman**
Pull request for #42013

### Summary of Changes
btn-inverse was not setup in the toolbar css

### Testing Instructions
as this is an scss change you will need to either use a prebuilt package or npm run build:css

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request
image

No change in light mode
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
@wilsonge would like a approval from you for this change, thanks

**Comment by wilsonge** [comment]
This is fine but `btn-inverse` is an old bs2 class that was removed in bs3+ so we might be better off just changing the class to one of our existing classes rather than reintroducing it.

**Comment by brianteeman** [comment]
Good point - I will change the class instead

**Comment by brianteeman** [comment]
Updated as suggested

**Comment by wilsonge** [comment]
Haven't tested. But if this works looks like a better fix!

**Comment by HLeithner** [comment]
@MacJoom or anyone else can we get a test here please.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15f583ef5e2857b4010d18924a5da716f1cf3c45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42051">issues.joomla.org/tracker/joomla-cms/42051</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 15f583ef5e2857b4010d18924a5da716f1cf3c45<br /><br />Using the prebuild update package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42051">issues.joomla.org/tracker/joomla-cms/42051</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42051">issues.joomla.org/tracker/joomla-cms/42051</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
