### PR TITLE
JFormFieldUser Duplicate Queries

### PR DESCRIPTION
**Pull request by kavadas**
#### Summary of Changes

JFormFieldUser is using the JTableUser directly and not the JFactory::getUser. This can generate duplicate queries in case multiple fields are rendered with the same value/user id.
#### Testing Instructions

Enable the system debugger and try to edit one article which has the same value for "created_by" and "modified_by" fields. When the edit page is loaded, look at the debugger and you will see duplicate queries coming from JFormFieldUser. With the patch applied you should see no duplicate queries from JFormFieldUser.

### CODE REVIEW

**Comment by mbabker** [comment]
Might I suggest using `JUser::getInstance()` instead of `JFactory::getUser()` as the latter will always load a user instance out of the session before going on to call `JUser::getInstance()` anyway.  The instance caching is in `JUser` so there's only small gains to be had here.

**Comment by kavadas** [comment]
@mbabker 

I have updated the code. However when the field value is set to current user `JFactory::getUser()` is still used.

**Comment by mbabker** [comment]
That'd be totally appropriate.  Looks fine to me.

**Comment by hardiktailored** [comment]
I have tested this item :white_check_mark: successfully on 1ed139a7e69d4578be5add80bd180b3c804491d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10945">issues.joomla.org/joomla-cms/10945</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 1ed139a7e69d4578be5add80bd180b3c804491d3<br /><br />Before 52 queries and 16 duplicates, after patch it's 48 queries and 12 duplicates. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10945">issues.joomla.org/joomla-cms/10945</a>.</sub>

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10945">issues.joomla.org/joomla-cms/10945</a>.</sub>

**Pull request merged**
