### PR TITLE
Prevent message "Component 'com_extension' does not exist." after uninstalling / re-installing component

### PR DESCRIPTION
**Pull request by mahagr**
Right now when you uninstall component which has menu items pointing to the component and go to menu manager, you will see message:

```
Component 'com_extension' does not exist.
```

In site you will get similar error:

```
404 Component not found.
```

The issue is that when you install the component back, you will still get the same error message unless you manually save each of the components menu items.

This pull request attempts to fix the issue by automatically updating all the menu items pointing to the component.

PS. Some extensions like Kunena and Akeeba already fix their menu items manually to work around this issue. So when testing, make sure you get the above error messages even after installing your favourite extension.

### CODE REVIEW

**Comment by brianteeman** [comment]
Shouldnt the message be "failed to update menu ITEMS" not menus

**Comment by mahagr** [comment]
Updated error messages based on suggestion made by @brianteeman .

**Comment by infograf768** [comment]
Please alpha order the new string:
It should come just before `JLIB_INSTALLER_ABORT_CREATE_DIRECTORY`

```
JLIB_INSTALLER_ABORT_COMP_UPDATESITEMENUS_FAILED="Component Install: Failed to update menu items."
JLIB_INSTALLER_ABORT_CREATE_DIRECTORY="Extension %1$s: Failed to create directory: %2$s"
```

**Comment by mahagr** [comment]
@infograf768 I ordered them based on lines 422-423 (admin file, few lines above my change):

    JLIB_INSTALLER_ABORT_ALREADYINSTALLED="Extension is already installed."
    JLIB_INSTALLER_ABORT_ALREADY_EXISTS="Extension %1$s: Extension %2$s already exists."

Where word with letter is ordered before underscore. Name is without space because of the original string just above my check does the same.

My question is what is the supposed order: 

* alphabetical ignoring underscore
* underscore comes after letters (PHP sort order)
* underscore comes before letters

**Comment by infograf768** [comment]
I always based my work on:
"Blank spaces between words in a page name are treated as an underscore "_", and are therefore ordered after upper case letters and before lower case letters. Blank spaces after a page name come before any character."
in
http://en.wikipedia.org/wiki/Help:Alphabetical_order

and we use here Upper Case letters.
I use "Sort" plugin in Eclipse, which has automatically ordered the strings this way.
Not a big deal though. :)

**Comment by infograf768** [comment]
Just leave it as is. No big deal. +1:

**Comment by kat05** [comment]
@test i tested the patch and it resolved the issue for me.

**Comment by OctavianC** [comment]
I'd love to get this merged, but don't we need to properly quote column names and aliases? Eg.
```php
->where($db->qn('m.client_id') . ' = ' . $db->q(0))
```
Or
```php
->update($db->qn('#__menu', 'm'))
```

This would *probably* ensure it will work with other db drivers.

**Comment by mahagr** [comment]
Joomla menu library files do not escape names either, so I guess they will work..?

**Comment by julienV** [comment]
@test i installed a component, created a menu item, then uninstalled, and reinstalled it.
without the patch, i got the Component 'com_extension' does not exist message in the menu items backend page.
Same process with the patch works as expected, the menu item works properly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6854">issues.joomla.org/joomla-cms/6854</a>.</sub>

**Comment by mahagr** [comment]
@brianteeman should be good to go.

**Comment by brianteeman** [comment]
Issue observed without PR
Applied PR and issue resolved
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6854">issues.joomla.org/joomla-cms/6854</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6854">issues.joomla.org/joomla-cms/6854</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thankyou very much!

**Pull request closed without merging**
