### PR TITLE
Remove chosen from com_tags

### PR DESCRIPTION
**Pull request by brianteeman**
Chosen is not accessible so we shouldnt use it unless it offers something useful.

In the tags component in the front end it is used for display #

This doesnt require or benefit from chosen so this simple PR returns it to regular and accessible list

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 7953146c4865531f9e6f0265a7e1df91a894e987<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24627">issues.joomla.org/tracker/joomla-cms/24627</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7953146c4865531f9e6f0265a7e1df91a894e987<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24627">issues.joomla.org/tracker/joomla-cms/24627</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24627">issues.joomla.org/tracker/joomla-cms/24627</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by mbabker** [comment]
LOLOLOLOL you merged this one but not the other because "it might break templates".  That's hilarious.

**Comment by HLeithner** [comment]
I have no idea why you're laughing at me.

I someone wants to remove the chosen she/he can override the Frontend template. With this pr we remove a feature unexpected for the user.

In the backend you likely will not break anything if you remove chosen.

**Comment by brianteeman** [comment]
Fyi both pr were for the front end

**Comment by HLeithner** [comment]
> Fyi both pr were for the front end

hmm then I mixed something up and my argument makes no sense.

**Comment by brianteeman** [comment]
> my argument makes no sense.

Hence @mbabker comment

**Comment by HLeithner** [comment]
Yeah, so if this works in 3.9.7 without problems I will merge the com tags merge into 3.9.8 and hopefully make everyone happy.

**Pull request merged**
