### PR TITLE
[4.0] Reset the state on the media field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Always reset the state

### Testing Instructions
- Create a new article
- go to the images tab
- on the intro image select a random image
- go to the fulltext image open the media field selector, DO NOT select anything and close the modal by clicking on the select button

### Actual result BEFORE applying this Pull Request
The state of the field was not properly reseted

### Expected result AFTER applying this Pull Request
The state of the field is now properly reseted

### Documentation Changes Required

No

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6c06992f0ad13da538991f21946df1dfafeaa6c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30071">issues.joomla.org/tracker/joomla-cms/30071</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 6c06992f0ad13da538991f21946df1dfafeaa6c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30071">issues.joomla.org/tracker/joomla-cms/30071</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30071">issues.joomla.org/tracker/joomla-cms/30071</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
