### PR TITLE
Fix deprecated warning in contenthistory

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Fix deprecated warning in contenthistory. It is caused by the null value for example in checked_out_time.

grafik

### Testing Instructions
See screenshot. Oben the contenthistory of an article and open one if the versions. 

### Actual result BEFORE applying this Pull Request
See screenshot

### Expected result AFTER applying this Pull Request
No warning

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f66757c5fb02b6a950a0f9a73bc8e742ff2a2799<br /><br />issue replicated and confirmed resolved with this pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40213">issues.joomla.org/tracker/joomla-cms/40213</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f66757c5fb02b6a950a0f9a73bc8e742ff2a2799<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40213">issues.joomla.org/tracker/joomla-cms/40213</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40213">issues.joomla.org/tracker/joomla-cms/40213</a>.</sub>

**Comment by obuisard** [comment]
Thank you Christiane @chmst for the PR!

**Pull request merged**
