### PR TITLE
[com_config] Capitalize label

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Capitalize label `Reply To email` to be consistent with `From Email`

### Testing Instructions
Go to Global Configuration
Under Server tab > Mail Settings

### Expected result
`Reply To Email`

### Actual result
`Reply To email`

### Documentation Changes Required
none

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 1efd4a361e28c8b9926dba47e0560eee8bbf30f1<br /><br />Just checking code is enough <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20299">issues.joomla.org/tracker/joomla-cms/20299</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 1efd4a361e28c8b9926dba47e0560eee8bbf30f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20299">issues.joomla.org/tracker/joomla-cms/20299</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20299">issues.joomla.org/tracker/joomla-cms/20299</a>.</sub>

**Review by brianteeman — APPROVED** [review]

**Comment by zero-24** [comment]
Merging Thanks!

**Pull request merged**
