### PR TITLE
Update Installation en-GB.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Replaced all string for "Installation folder" with "'Installation' folder" because this is the name of the folder

### CODE REVIEW

**Comment by brianteeman** [comment]
Please do not change the first part of the string the constant in
uppercase. Only the value should be changed

Replaced all string for "Installation folder" with "'Installation' folder"
because this is the name of the folder
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/joomla/joomla-cms/pull/7390
Commit Summary

   - Update en-GB.ini

File Changes

   - *M* installation/language/en-GB/en-GB.ini
   <https://github.com/joomla/joomla-cms/pull/7390/files#diff-0> (12)

Patch Links:

   - https://github.com/joomla/joomla-cms/pull/7390.patch
   - https://github.com/joomla/joomla-cms/pull/7390.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/pull/7390>.

**Comment by brianteeman** [comment]
Oops sorry I misread one line. It's all ok

**Comment by zero-24** [comment]
So we can RTC @brianteeman ?

**Comment by brianteeman** [comment]
:thumbsup:

Do translation teams need to be notified to NOT translate this word as it is now a word that must not be translated

**Comment by zero-24** [comment]
>Do translation teams need to be notified to NOT translate this word as it is now a word that must not be translated

@Bakual @imanickam 

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7390">issues.joomla.org/joomla-cms/7390</a>.</sub>

**Comment by wojsmol** [comment]
IMHO if the ````Installation```` in this context is taken to mean the exact folder name should be written in lowercase.

**Comment by brianteeman** [comment]
Ooh good point I didn't consider that. You are absolutely correct.

**Comment by infograf768** [comment]
<b>To maintainers/committers</b>
Once corrected, this patch means that all TTs would have to update their installation ini file during a specific Installation language freeze before the release.

FYI, most have translated "installation". 
Notable exceptions: 
ta-IN, th-TH, pt-BR, ko-KR, id-ID, el-GR, be-BY 
that is 7 on 60

**Comment by brianteeman** [comment]
(Updated title to show it is referring to the installation language file)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7390">issues.joomla.org/joomla-cms/7390</a>.</sub>

**Comment by infograf768** [comment]
>Do translation teams need to be notified to NOT translate this word as it is now a word that must not be translated

@imanickam will let it know at freeze time.

**Comment by javigomez** [comment]
tagging @puneet0191 since this pull will affect too the JoomlaBrowser of the Automated Tests at https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L148-L150

we will update it when this got merged.

**Comment by zero-24** [comment]
So we can RTC again and inform the TTs and do the changes in the Tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7390">issues.joomla.org/joomla-cms/7390</a>.</sub>

**Comment by rdeutz** [comment]
@aaleksanyants can you check the merge conflicts

**Comment by aaleksanyants** [comment]
@rdeutz , would you please describe if what should I do exactly?

**Comment by rdeutz** [comment]
@aaleksanyants the file you have changed is in the meantime change by someone else and git can't figure out how to merge your changes and the changes the other user made. So this must be made manuell.

**Comment by zero-24** [comment]
@aaleksanyants if you are fimiliar with git you can try something like:

```
git checkout patch-8
git pull upstream staging
<git tell you here which files has conflicts so they need to be fixed local)
git commit -am 'fix merge conflicts'
git push origin patch-8
```

If not as this is a `one file change` the easyset could be closing here and open a new one based on the current code base.

**Comment by aaleksanyants** [comment]
OK, I prefer to close the current one, thanks

**Comment by rdeutz** [comment]
@aaleksanyants ok please mention this PR in your new PR so that we don't have to go thru the whole process

**Comment by aaleksanyants** [comment]
@rdeutz, I think there is no need to create a new PR regarding the same issues, after adding the appropriate comments above the rows containing folder name, my suggestions are no longer actual.

**Pull request closed without merging**
