### PR TITLE
[4.0] Update build script

### PR DESCRIPTION
**Pull request by brianteeman**
### The problem
when running the scripts with #22263 they were trying to process the choices css files as if they were js.
this was only present on windows

### The solution??
hopefully this is correct. It works for me but anything with regex and js and I am stabbing in the dark

### CODE REVIEW

**Comment by wilsonge** [comment]
Need a OS X/Linux test here before merging but pretty confident this should be fine

**Comment by mbabker** [comment]
It works.

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
