### PR TITLE
[4.0] user registration accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
The description strings were removed some time ago but they were not removed from the xml. This resulted in the fields being rendered with an aria-described being created that pointed to a non existent element.

### To test
enable user registration in com_users in the admin and then go to the user registration form in the front end

View the source of any of the inputs and you will see code like
image

Apply the pr and view the generated source again and the same input will look like
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4e1dc315fb7ad62cb31f026bd9c58909764b7920<br /><br />Tested successfully in 4.0.0-beta4-dev of 2 August on Wampserver 3.2.2 using PHP 7.4.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30260">issues.joomla.org/tracker/joomla-cms/30260</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4e1dc315fb7ad62cb31f026bd9c58909764b7920<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30260">issues.joomla.org/tracker/joomla-cms/30260</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30260">issues.joomla.org/tracker/joomla-cms/30260</a>.</sub>

**Comment by brianteeman** [comment]
Closing as it appears the template is being rewritten again

**Pull request closed without merging**
