### PR TITLE
[4.0] Add an icon option to popupButton.

### PR DESCRIPTION
**Pull request by twister65**
Pull Request for PR https://github.com/joomla-extensions/patchtester/pull/223.
Displays the refresh icon to the "Fetch Data" popup button in PatchTester.

### Summary of Changes

Add an icon option to popupButton.
Depending on the name of the button.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b9f4668e448da1196758173b5fa13b77611b1d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25463">issues.joomla.org/tracker/joomla-cms/25463</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b9f4668e448da1196758173b5fa13b77611b1d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25463">issues.joomla.org/tracker/joomla-cms/25463</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25463">issues.joomla.org/tracker/joomla-cms/25463</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
