### PR TITLE
[4.2] fix yubico.com link

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

add href target and rel

### Testing Instructions

click link

### Actual result BEFORE applying this Pull Request

`Users need their own YubiKey available from https://www.yubico.com.`

### Expected result AFTER applying this Pull Request

`Users need their own YubiKey available from <a href=\"https://www.yubico.com\" target=\"_blank\" rel=\"noopener noreferrer\">www.yubico.com</a>.
`
### Documentation Changes Required

.

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 2af44b198bdfe2a2d1ef09d08300112bcd49ac17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38304">issues.joomla.org/tracker/joomla-cms/38304</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2af44b198bdfe2a2d1ef09d08300112bcd49ac17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38304">issues.joomla.org/tracker/joomla-cms/38304</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38304">issues.joomla.org/tracker/joomla-cms/38304</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
