### PR TITLE
Templatestyle language string changes #makeithappen

### PR DESCRIPTION
**Pull request by brianteeman**
Two small changes to improve the language string structure

### CODE REVIEW

**Comment by zero-24** [comment]
RTC. #jab14 #makeithappen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7071">issues.joomla.org/joomla-cms/7071</a>.</sub>

**Comment by Bakual** [comment]
Merged into `staging`. Thanks!

**Comment by infograf768** [comment]
Disagree with these changes. 

```
-COM_TEMPLATES_FIELD_HOME_ADMINISTRATOR_DESC="This template style is defined or not as default template style."
+COM_TEMPLATES_FIELD_HOME_ADMINISTRATOR_DESC="This template style is defined as the default."
```
That tip is over the Yes/No choice... therefore "is defined or not" was correct.

```
-COM_TEMPLATES_FIELD_HOME_SITE_DESC="If the multilingual functionality is not implemented, please limit your choice between <b>No</b> and <b>All</b>. The template style will be defined or not as global default template style.<br />If the <b>System - Language Filter</b> plugin is enabled and you use different template styles depending on your content languages please assign a language to this style."
+COM_TEMPLATES_FIELD_HOME_SITE_DESC="If the multilingual functionality is not implemented, please limit your choice between <b>No</b> and <b>All</b>. This template style will be defined as the global default template style.<br />If the <b>System - Language Filter</b> plugin is enabled and you use different template styles depending on your content languages please assign a language to this style."
```
That tip is over the Default Label. It is a dropdown where "All" and "No" are proposed and those have a meaning.
"No" means that the template style is NOT a global default site template, while "All" means that it is THE default site language.
Therefore "The template style will be defined or not as global default template style." is correct.

Please revert.

**Comment by mbabker** [comment]
At least in the first case, grammatically it's an improvement.  If you really want to get picky, you could get into some long winded string like "Set whether this template style is defined as the default".  In many cases, "defined or not" isn't strong English.

**Comment by infograf768** [comment]
It is plain wrong imho.
A templae style which is not defined as default will have that new tip. Makes no sense.

**Comment by infograf768** [comment]
"Set or not this template style as default" would maybe be better English. At least it would make sense.

**Comment by mbabker** [comment]
It's that "or not" part that's tricky; in English it's really bad in this context.  I really don't know where in the UI this is actually used, but from the outside looking in and with what little English knowledge I do have, statements like "set or not this item as default" are poorly phrased.  "Set whether this item is the default" structurally seems better to me, but it would depend on its UI context too (and who knows, maybe I'm just as wrong on the English here, after all I speak American :wink: )

**Comment by infograf768** [comment]
OK for using whether:

And here it is:
screen shot 2015-06-03 at 17 41 44

**Comment by brianteeman** [comment]
Sorry I am not going to debate what is correct english with a non-english
speaker

On 3 June 2015 at 16:43, infograf768 <notifications@github.com> wrote:

> OK for using whether:
>
> And here it is:
> [image: screen shot 2015-06-03 at 17 41 44]
> <https://cloud.githubusercontent.com/assets/869724/7964408/e4b9707a-0a17-11e5-9495-c8a35519c9ea.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7071#issuecomment-108490498>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
This type of BAD english is used throughout the tooltips and this was just
the first of the PR to resolve this. These are all the results of the en-GB
native speakers who participated at the Makeithappen session during #jab15

On 3 June 2015 at 17:50, Brian Teeman <brian@teeman.net> wrote:

> Sorry I am not going to debate what is correct english with a non-english
> speaker
>
> On 3 June 2015 at 16:43, infograf768 <notifications@github.com> wrote:
>
>> OK for using whether:
>>
>> And here it is:
>> [image: screen shot 2015-06-03 at 17 41 44]
>> <https://cloud.githubusercontent.com/assets/869724/7964408/e4b9707a-0a17-11e5-9495-c8a35519c9ea.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/7071#issuecomment-108490498>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
As further proof that we dont need this BAD string we do NOT use this incorrect form of English elsewhere (and where we do I will be submitting PR to correct it)
h0ir

**Comment by infograf768** [comment]
Then follow your own rules and change it to an active phrase:
"COM_TEMPLATES_FIELD_HOME_ADMINISTRATOR_DESC="Define this template style as the default."

It is not necessary to be an English native to understand when there is a mistake in a definition.

**Comment by brianteeman** [comment]
As I said before I am not interested in debating this

On 4 June 2015 at 08:19, infograf768 <notifications@github.com> wrote:

> Then follow your own rules and change it to an active phrase:
> "COM_TEMPLATES_FIELD_HOME_ADMINISTRATOR_DESC="Define this template style
> as the default."
>
> It is not necessary to be an English native to understand when there is a
> mistake in a definition.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7071#issuecomment-108763299>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request closed without merging**
