### PR TITLE
[5.2] [Guided tours] Tour header visual changes + footer padding fix

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

The guided tours header does not have a clear indication that a tour can be cancelled. There is no label and the progress indicator is next to it, making it hard to distinguish.
The changes include:
- A _Cancel_ label close to the cancel cross to provide context and enhance usability,
- moving the progress indicator away from the cancel button to ensure the cancel is clearly visible.

### Testing Instructions

It is just a visual change. Make sure you can still cancel a tour, no matter if you are selecting the cross or the label. 

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on a19918e3102cbf8765ebd538fa2ec1ccd7eabe8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43809">issues.joomla.org/tracker/joomla-cms/43809</a>.</sub>

**Comment by brianteeman** [comment]
You need to use logical css properties otherwise your css breaks on RTL

image

example
change margin-right to margin-inline-end

**Comment by obuisard** [comment]
> You need to use logical css properties otherwise your css breaks on RTL
> example change margin-right to margin-inline-end

I have adjusted the CSS. Thanks!

**Comment by brianteeman** [comment]
Thanks for the last change.

I am not a designer but the header looks odd to me as we have multiple text sizes and line heights on the same line which results in 4 different baselines

You can see it when you enlarge the header and draw some lines

image

**Comment by obuisard** [comment]
> Thanks for the last change.

Of course! I am glad you pointed it out.

> I am not a designer but the header looks odd to me as we have multiple text sizes and line heights on the same line which results in 4 different baselines
> You can see it when you enlarge the header and draw some lines

That's because the elements in the header are vertically aligned in the center of the top container.
I was not 'happy' with the 'Cancel' label, however. I changed it a bit.
Looks better to my eye.

image

**Comment by Quy** [comment]
Please consider removing `Cancel` as this is not shown in other modals.

**Comment by obuisard** [comment]
> Please consider hiding `Cancel` as this is not shown in other modals.

It was hidden before, one of the ideas for this PR is to make it visible. These are guided tours and from the start some of the user feedback was is that the X is not a clear indication that it is meant to cancel tours (or close them). It helps teaching newbies that yes, the 'X' cancels/closes the window.

**Comment by glarkell** [comment]
Tested successfully on J5.2.

**Comment by Kostelano** [comment]
I haven’t tested it yet, but what if the step title is long enough?

**Comment by Kostelano** [comment]
> I haven’t tested it yet, but what if the step title is long enough?

I can say that this is a rather short title in Russian. Now it turns out that almost every step has a line break, which doesn’t look very good to me. Most likely there will be lines with 3/4 line breaks.

I would prefer that somehow this could be solved.

Perhaps enlarge the window. It is still possible to remove CANCEL, since all other modal windows simply have a cross. It is possible to move CANCEL down to the button block (from START).

Screenshot_2

**Comment by sdwjoomla** [comment]
> Please consider hiding `Cancel` as this is not shown in other modals.

Having the 'Cancel' next to the 'X' helps answer the question received for clients who noticed it and aske what it does. For the client who hadn't noticed the 'X' and would also ask how to cancel a tour, adding the word 'Cancel' makes it easier for them.

**Comment by sdwjoomla** [comment]
@Kostelano Thanks for taking a look. Yes, the line break doesn't look the best. There is a companion PR to this one, https://github.com/joomla/joomla-cms/pull/43810 which addresses the width. Would you have a few moments to take a look at it?

**Comment by Quy** [comment]
The Step badge now takes up more space and has the main focus when it should be the title. Maybe move it to the bottom left corner.

The Cancel text is competing the attention with the title. You want them to do the tour but constantly see the Cancel with each step. It needs to be more subtle as before.

**Comment by brianteeman** [comment]
Accessibility says that you should always indicate how far along in a process you are so leading with the step count is good. I agree that it is not needed to display the cancel text. We don't do it on other modals

**Comment by chmst** [comment]
> I agree that it is not needed to display the cancel text. We don't do it on other modals

agreed

**Comment by Quy** [comment]
Not aligned.

43809-start

43809-end

**Comment by obuisard** [comment]
> Not aligned.

Agreed, although this issue has not been introduced by this PR :-)

**Comment by obuisard** [comment]
> Not aligned.

I made corrections in PR #43810, which is were changes have been made about text padding. I have also adjusted the footer padding, which was not aligned since 4.3 :-).
The present PR has not modified any padding, just re-arranged elements in the header.

**Comment by Quy** [comment]
Perform `How to add steps to a guided tour?`. Missing X and partial X.

43809-step1

43809-step2

**Comment by obuisard** [comment]
> Perform `How to add steps to a guided tour?`. Missing X and partial X.

Strange, I can't reproduce it. No matter the window size. What browser are you using? Anybody else with the issue?

image

image

**Comment by Quy** [comment]
Firefox 128.0.2 and Chrome Version 127.0.6533.73 on Windows

43809-css

**Comment by Quy** [comment]
The last commit is causing the issue.

**Comment by obuisard** [comment]
> The last commit is causing the issue.

Thanks, I corrected it.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0562ade689c0be4b4200f0fec94f9ad35a966b25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43809">issues.joomla.org/tracker/joomla-cms/43809</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0562ade689c0be4b4200f0fec94f9ad35a966b25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43809">issues.joomla.org/tracker/joomla-cms/43809</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43809">issues.joomla.org/tracker/joomla-cms/43809</a>.</sub>

**Comment by pe7er** [comment]
Thanks @obuisard !

**Pull request merged**
