### PR TITLE
[4.0][com_finder] Add modal title

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add missing title to Statistics modal.

### Testing Instructions
Go to Components > Smart Search > Content Maps
Click Statistics button.
Modal missing title.

Go to Components > Smart Search > Search Filters
Click Statistics button.
Modal missing title.

### CODE REVIEW

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 102b6f8e6013337ecf02423106e4eee08e6eb6fc<br /><br />After patch applied, h3 modal-title tag is now displayed on the modal window.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26336">issues.joomla.org/tracker/joomla-cms/26336</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 102b6f8e6013337ecf02423106e4eee08e6eb6fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26336">issues.joomla.org/tracker/joomla-cms/26336</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26336">issues.joomla.org/tracker/joomla-cms/26336</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
