### PR TITLE
[4.0] View "New module" - some css

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Meanwhile we have removed shadows around cards at hover.  
The button on the card is better integrated into the card.

### Testing Instructions
See cards before applying the patch, especially on hover. Apply and run npm build:css and compare. 

### Actual result BEFORE applying this Pull Request

grafik

### Expected result AFTER applying this Pull Request
No whadow on hover, buttons match better in the card

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d37c007bb4914cccbc99a17b17504838e16a7efc<br /><br />Before applying the PR, the box for each module type has round corners at the top but not at the bottom because of the button.

The box shadow on hovering somehow visualizes in addition to the mouse pointer that the complete box and not only the button is clickable, but it has such a light colour that it is hard to see and makes the page look a bit "blurry".

After applying the PR, the box for each module type has the same round corners everywhere.

The "blurry" box shadow has been removed. Now when hovering there is (beside the mouse pointer) no visualization that the complete box is clickable, but for me that's ok. Maybe there will be feedback from others that it would be good to have a colour change for the complete box when hovering, or maybe not. We will see.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32390">issues.joomla.org/tracker/joomla-cms/32390</a>.</sub>

**Comment by ceford** [comment]
I am not sue about removing the card outline. Pretty much every edit form has a details tab with common options in the right panel. Whilst revising the Help screens I thought it would be an idea to demarcate these 'panels' with a legend. Having something is helpful! Having nothing just puts input boxes alongside input boxes with a different label layout - see Edit Contact for example. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32390">issues.joomla.org/tracker/joomla-cms/32390</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d37c007bb4914cccbc99a17b17504838e16a7efc<br /><br />Forget may last comment - not really relevant to this PR - although I think the shadow is helpful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32390">issues.joomla.org/tracker/joomla-cms/32390</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32390">issues.joomla.org/tracker/joomla-cms/32390</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
