### PR TITLE
[4.3] Inclusive Naming master (comment)

### PR DESCRIPTION
**Pull request by brianteeman**
We should be using inclusive naming throughout the cms not just in the language strings.

In this specific case it is not being changed as sadly php still uses the term "master value" and here it is used to produce a downloadable text file of phpinfo().

The comment is simply to explain why it has not been changed for future reference

### Rationale
https://inclusivenaming.org/word-lists/tier-1/_master/

### Test
Code review Only

### Documentation
New page will be added to manual.joomla.org shortly

### Note
This is part of a series of pull requests that are submitted separately to make reviewing easier

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 033a323ace34780946fd331ddeb6be3ece4ffce8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41022">issues.joomla.org/tracker/joomla-cms/41022</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 033a323ace34780946fd331ddeb6be3ece4ffce8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41022">issues.joomla.org/tracker/joomla-cms/41022</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41022">issues.joomla.org/tracker/joomla-cms/41022</a>.</sub>

**Review by obuisard — COMMENTED** [review]
Hi Brian @brianteeman, there is a small typo in 'representation'.

**Comment by brianteeman** [comment]
good spot - thanks

**Comment by ChristineWk** [comment]
should be: representation :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41022">issues.joomla.org/tracker/joomla-cms/41022</a>.</sub>

**Comment by brianteeman** [comment]
@ChristineWk it was already corrected

**Comment by ChristineWk** [comment]
OK, Is saw it afterwards in another file.

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Comment by brianteeman** [comment]
thx

**Pull request merged**
