### PR TITLE
[4.1] Flags (alternate)

### PR DESCRIPTION
**Pull request by brianteeman**
alternate to #36609

Some flags have a white background and so they do not display correctly. This is particularly true for the japanese flag but its true for other flags as well.  This adds super thin border to flags with a white edge

### Before
image

### After

image

As this is a media file change it needs npm i

**__lets not start another debat here about not using flags or not usings gifs__**

### CODE REVIEW

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 8a79b090d0f3bc67df65789b682223ae786757c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36706">issues.joomla.org/tracker/joomla-cms/36706</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 8a79b090d0f3bc67df65789b682223ae786757c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36706">issues.joomla.org/tracker/joomla-cms/36706</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36706">issues.joomla.org/tracker/joomla-cms/36706</a>.</sub>

**Comment by bembelimen** [comment]
I guess we have the same problem with all the other flags if a color of the flag is used as background colour of the template (e.g. in frontend with the language switcher). So probably, we should update all flags sometimes in the future.

So far to fix the obvious ones this is a good start. Thx.

**Comment by brianteeman** [comment]
Thanks for merging. 

Now that all the flags have a solid border then css would be a better solution if there is a dark background colour that clashes.

**Pull request merged**
