### PR TITLE
Replace ugly select boxes in filter rules

### PR DESCRIPTION
**Pull request by brianteeman**
Just a cosmetic UI change so that the select boxes for acl permissions are displayed in the same way as all other select boxes
#### Before

vgo4 1
#### After

dkh7 1

### CODE REVIEW

**Comment by 810** [comment]
I like the old way better.

**Comment by brianteeman** [comment]
This is about creating a consistent UI.

**Comment by Bakual** [comment]
They're not "ugly". They are native browser selects. You find them ugly, change your browser/OS :smile: 

Joking aside, this was done in a previous PR https://github.com/joomla/joomla-cms/pull/6317 because there were performance issues when you have many groups and actions.

**Comment by brianteeman** [comment]
Yeah their ugliness really depends on the browser :)

But based on the comments in the previous PR referenced above I am closing this. @bakual thanks for remembering

**Pull request closed without merging**
