### PR TITLE
[4] array() to []

### PR DESCRIPTION
**Pull request by ReLater**
Test: Code review.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 936f316935a7ba6d7fc074cf730aae3009efc422<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37837">issues.joomla.org/tracker/joomla-cms/37837</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 936f316935a7ba6d7fc074cf730aae3009efc422<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37837">issues.joomla.org/tracker/joomla-cms/37837</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37837">issues.joomla.org/tracker/joomla-cms/37837</a>.</sub>

**Comment by HLeithner** [comment]
ThaNks

**Pull request merged**
