### PR TITLE
[4.0] CMSHelper prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements to `Joomla\CMS\Helper\CMSHelper`.

### Testing Instructions

Simple query, code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c39f7fc4accabca0f9e46bef7c26879f19a043c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26032">issues.joomla.org/tracker/joomla-cms/26032</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c39f7fc4accabca0f9e46bef7c26879f19a043c6<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26032">issues.joomla.org/tracker/joomla-cms/26032</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thank you

**Pull request merged**
