### PR TITLE
[4.2] PHP8.2 Update the uri package with the utf8 fix

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Updates the uri package with the UTF8 deprecated fix.

### Testing Instructions
- Ensure, error reporting is set to maximum in the Joomla configuration
- Open the back end login screen
- Enter the credentials and hit login

### Actual result BEFORE applying this Pull Request
You get redirected to the front page with a deprecated message in the url.

### Expected result AFTER applying this Pull Request
Login works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 5235492625297b1234da18a10fe6ac7b3583becf<br /><br />Apply the change, it removes the warnings. Also, navigate to different pages and it is still working fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39593">issues.joomla.org/tracker/joomla-cms/39593</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 5235492625297b1234da18a10fe6ac7b3583becf<br /><br />Remember for those who test, do `composer install`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39593">issues.joomla.org/tracker/joomla-cms/39593</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39593">issues.joomla.org/tracker/joomla-cms/39593</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
