### PR TITLE
Allow JHtmlDate::relative to set a custom format

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes

At the moment, if you use JHtmlDate::relative, it's not possible to set a custom format for the "fallback date" output. With this patch you can now set your own format.
### Testing Instructions

Open any file and write:
`echo JHtml::_('date.relative', '2010-09-20');`

Depending on your language, the format is  always JText::_('DATE_FORMAT_LC1');

Apply patch and try:
`echo JHtml::_('date.relative', '2010-09-20', null, null, 'M jS, Y');`

Now you can set your own formats

### CODE REVIEW

**Comment by chmst** [comment]
Tested successfully with different date formats.

**Comment by chmst** [comment]
Tested successfully with different date formats. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12164">issues.joomla.org/joomla-cms/12164</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on dad2591ad8a6f58f227a06540b75be357b80f375<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12164">issues.joomla.org/joomla-cms/12164</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on dad2591ad8a6f58f227a06540b75be357b80f375<br /><br />:+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12164">issues.joomla.org/joomla-cms/12164</a>.</sub>

**Pull request merged**
