### PR TITLE
[5.x] Menu Listfilters

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # .

### Summary of Changes
Several years ago I created this PR https://github.com/joomla/joomla-cms/pull/20890 to add filters to the custom admin menu for articles. I was reminded of it when it was referenced in the accepted RFC for a simple cck

The ui is now very cluttered and _scary_ with all those filters which are completely optional

This PR moves the optional filters to their own tab. Hopefully less scary and more usable.

### Testing Instructions
Create an admin menu item to list all articles

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

image

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on f9cd6053f55699cf7fd6bef5b08c7ae79d861c58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39634">issues.joomla.org/tracker/joomla-cms/39634</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f9cd6053f55699cf7fd6bef5b08c7ae79d861c58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39634">issues.joomla.org/tracker/joomla-cms/39634</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39634">issues.joomla.org/tracker/joomla-cms/39634</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev. No new features will be merged into Joomla! 4.3 series. Joomla! 4.4 series is a bridge release to make migration from Joomla! 4 to 5 as smooth as possible.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
