### PR TITLE
Change year from 2015 to 2016 in a js file

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Leftover from merge https://github.com/joomla/joomla-cms/commit/aff4150eb7e5ac70cdc0eda9af1512a4b4d441fb.
#### Test instructions

Check code diff.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 91550380b8e6364e12015ac2248c4a358fc1ca20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8921">issues.joomla.org/joomla-cms/8921</a>.</sub>

**Comment by 810** [comment]
Looks ok, can be merged

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 91550380b8e6364e12015ac2248c4a358fc1ca20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8921">issues.joomla.org/joomla-cms/8921</a>.</sub>

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 91550380b8e6364e12015ac2248c4a358fc1ca20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8921">issues.joomla.org/joomla-cms/8921</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot ping

**Pull request merged**
