### PR TITLE
[4.0] Rename Contact and Newsfeeds route helpers

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Renames `Joomla\Component\Contact\Site\Helper\Route` and `Joomla\Component\Newsfeeds\Site\Helper\Route` to be consistent with other helper classes.

### Testing Instructions

Create some contacts and newsfeeds.
View them in frontend.
Run Smart Search indexer.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on 592ba35c8915125474208bbc58497b6940dae2c5<br /><br />When creating a contact I get "An error has occurred.

    0 Class 'Joomla\Component\Contact\Site\Helper\RouteHelper' not found "

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27510">issues.joomla.org/tracker/joomla-cms/27510</a>.</sub>

**Comment by jwaisner** [comment]
NOTE: The contact is created when you navigate back to the contacts.

**Comment by jwaisner** [comment]
NOTE: The contact is created when you navigate back to the contacts.

**Comment by SharkyKZ** [comment]
Looks like the patch hasn't been applied correctly. Can you check if `Route.php` file in `components/com_contact/Helper/` has been renamed to `RouteHelper.php` correctly?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 592ba35c8915125474208bbc58497b6940dae2c5<br /><br />seems to work fine for me - cannot replicate the error reported by @jwaisner<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27510">issues.joomla.org/tracker/joomla-cms/27510</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 592ba35c8915125474208bbc58497b6940dae2c5<br /><br />Apparently something went weird when I went to patch. After patching, everything works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27510">issues.joomla.org/tracker/joomla-cms/27510</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27510">issues.joomla.org/tracker/joomla-cms/27510</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
