### PR TITLE
[4.0] Filesystem plugin - simplify text

### PR DESCRIPTION
**Pull request by brianteeman**
repositories is quite a complex term and I am not sure it's really accurate either. This PR replaces that word with directories

### CODE REVIEW

**Comment by infograf768** [comment]
The `PLG_FILESYSTEM_LOCAL_XML_DESCRIPTION` value is not the same in the ini and sys.ini

**Comment by brianteeman** [comment]
Fixed

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 3d439083f91a3e4d13ccc9c97d3b41098a1a1a5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24090">issues.joomla.org/tracker/joomla-cms/24090</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3d439083f91a3e4d13ccc9c97d3b41098a1a1a5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24090">issues.joomla.org/tracker/joomla-cms/24090</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24090">issues.joomla.org/tracker/joomla-cms/24090</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
