### PR TITLE
[4.0] remove deprecated type tag

### PR DESCRIPTION
**Pull request by PhilETaylor**
as per Joomla coding standards and https://developer.mozilla.org/en-US/docs/web/html/element/style#attr-type/contributors.txt
Screenshot 2021-12-23 at 16 51 40

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6c40d8cd0cb11a67167317f45fc1919bbd389d4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36382">issues.joomla.org/tracker/joomla-cms/36382</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 6c40d8cd0cb11a67167317f45fc1919bbd389d4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36382">issues.joomla.org/tracker/joomla-cms/36382</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36382">issues.joomla.org/tracker/joomla-cms/36382</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
