### PR TITLE
[5.0] Finally delete deprecated javascript assets from PR's #38823 and #39374

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for [Issue #](https://github.com/joomla/joomla-cms/pull/40296#issuecomment-1493329420) .

### Summary of Changes

This pull request (PR) finally deletes the js files and the asset which had once been deleted with PR's #38823 and #39374 and then added back with PR #39431 for b/c with old layout overrides.

It is a simple revert of PR #39431 in the 5.0-dev branch plus adding the deleted compiled and minified js files from the media folder on update, i.e. adding them to the deleted files list in "script.php".

The deprecated language strings used by the removed js will be removed with PR #40296 .

### Testing Instructions

Code review: Verify that this PR here is exactly reverting PR #40296 plus adding the deleted compiled and minified js files to the deleted files list in "script.php".

In addition, test an update from the latest 4.4-dev nightly build to the update package or custom URL created by Drone for this PR.

### Actual result BEFORE applying this Pull Request

Deprecated js files and asset from PR #40296 are still present in the 5.0-dev branch. 

### Expected result AFTER applying this Pull Request

Deprecated js files and asset from PR #40296 are removed from the 5.0-dev branch, and the compiled and minified js files are deleted on update from 4.4-dev. 

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/98

### CODE REVIEW

**Comment by HLeithner** [comment]
can you create a manual against https://github.com/joomla/Manual/pull/28 please ?

**Comment by richard67** [comment]
> can you create a manual against [joomla/Manual#28](https://github.com/joomla/Manual/pull/28) please ?

@HLeithner If you tell me where to add that. I have no idea.

**Comment by HLeithner** [comment]
please add a section to this file https://github.com/joomla/Manual/blob/cf6b87662d3b086049c8b8078f8699db864a91dc/migrations/44-50/removed-backward-incompatibility.md

**Comment by richard67** [comment]
> please add a section to this file https://github.com/joomla/Manual/blob/cf6b87662d3b086049c8b8078f8699db864a91dc/migrations/44-50/removed-backward-incompatibility.md

@HLeithner And how shall that section be titled and look like? Shall it be "JS removals" and be like the "CSS removals" section? What do you expect?

**Comment by HLeithner** [comment]
> @HLeithner And how shall that section be titled and look like? Shall it be "JS removals" and be like the "CSS removals" section? What do you expect?

I would expect something what you also find useful when you read this page ;-)

so something like the "CSS removals" would be a good start. including which webasset names are no longer available including the the path to the files and maybe the reason why it's no longer exists. (link to pr when it was removed the first time and that is is no longer used by joomla it self).

**Comment by richard67** [comment]
@HLeithner What about the language strings removal in PR #40296 ? Does that need to be added to the developer manual, too?

**Comment by HLeithner** [comment]
Actually yes, I added the deprecation for the language strings also the manual. So the removal have to be added too.

**Comment by richard67** [comment]
> Actually yes, I added the deprecation for the language strings also the manual. So the removal have to be added too.

@HLeithner But that belongs to @brianteeman 's PR #40296 , so I think he should do that. Otherwise I will need again instructions on where to do that.

**Comment by HLeithner** [comment]
already send him a message

**Comment by richard67** [comment]
@HLeithner For the javascript stuff see https://github.com/joomla/Manual/pull/98 .

**Pull request merged**
