### PR TITLE
[4.0] Remove captionTable ID

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #30015 .

### Summary of Changes
Remove all "captionTable" IDs

### Testing Instructions
Test by review? No duplicate ID in tinyMCE plugin

### Actual result BEFORE applying this Pull Request
"captionTable" IDs everywhere

### Expected result AFTER applying this Pull Request
"captionTable" IDs nowhere

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2222f76ab0f04c073c2c73fc030e36742e6ac994<br /><br />I can confirm that
- This PR removes all occurrences of `id="captionTable"`, i.e. nothing forgotten.
- The string "captionTable" doesn't occur anywhere else, so it seems not to be used by any js/(s)css files.

No idea why that was there.
The patchtester uses it, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31829">issues.joomla.org/tracker/joomla-cms/31829</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2222f76ab0f04c073c2c73fc030e36742e6ac994<br /><br />By code review. The ID is not used anywhere and has nothing to do with a11y. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31829">issues.joomla.org/tracker/joomla-cms/31829</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31829">issues.joomla.org/tracker/joomla-cms/31829</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
