### PR TITLE
[4.0] menu module modal

### PR DESCRIPTION
**Pull request by brianteeman**
Missing on hover background

Select a menu item and then the module assignment tab
Click on any module and observe the Close button
Before this pr there is no background

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6c29730ec20da209125ed7bab1a31d34d818a815<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34153">issues.joomla.org/tracker/joomla-cms/34153</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 6c29730ec20da209125ed7bab1a31d34d818a815<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34153">issues.joomla.org/tracker/joomla-cms/34153</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34153">issues.joomla.org/tracker/joomla-cms/34153</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
