### PR TITLE
[4.3] Remove unused layout

### PR DESCRIPTION
**Pull request by brianteeman**
Removes a layout that is never used.

Code review

Pull Request for Issue #39913 .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bad4e41b08ee63770ff1fba535151d29f1fd9fb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39933">issues.joomla.org/tracker/joomla-cms/39933</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bad4e41b08ee63770ff1fba535151d29f1fd9fb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39933">issues.joomla.org/tracker/joomla-cms/39933</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39933">issues.joomla.org/tracker/joomla-cms/39933</a>.</sub>

**Comment by laoneo** [comment]
Does this not crash views when a template override includes the file?

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Pull request merged**
