### PR TITLE
[4.1][bugfix] Use the one true way to render images: with jLayout

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #37006 .

### Summary of Changes

- Change the field template layout to use the existing image JLayout 

### Testing Instructions

- Add an image to an article via the Images and Links tab
- Create a custom field of type Media then add an image via that field to an article
- Inspect the result on the front end

### Documentation Changes Required

NO

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 749070b46925aed5b80a392cf315fe0448a7a1cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37008">issues.joomla.org/tracker/joomla-cms/37008</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 749070b46925aed5b80a392cf315fe0448a7a1cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37008">issues.joomla.org/tracker/joomla-cms/37008</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37008">issues.joomla.org/tracker/joomla-cms/37008</a>.</sub>

**Comment by Scrabble96** [comment]
Is this going to be in the J4.1 release? It's passed checks but doesn't seem to have been merged.

**Comment by laoneo** [comment]
Thanks!

**Comment by Scrabble96** [comment]
I've just come back to this PR because when I checked a custom field of type 'Media' it still does not include the dimensions in the image's attributes.

**Pull request merged**
