### PR TITLE
[4.0] Fix client filter for menu assignment

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #27446.

### Summary of Changes

Fixes client filter condition.

### Testing Instructions

> Create an admin menu
> Create at least one item in the new admin menu
> Go to Module manager
> Open a site module and go to the menu assignment tab
> Select "Only on the selected pages" from the Module Assignment Tab

### Expected result

>Tree of all SITE menus and menu items

### Actual result

>Tree of ALL menus and menu items - including the admin menu you created in the steps to reproduce

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 40d9d331bb636694170dd594b0b58f08c55b200f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27449">issues.joomla.org/tracker/joomla-cms/27449</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 40d9d331bb636694170dd594b0b58f08c55b200f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27449">issues.joomla.org/tracker/joomla-cms/27449</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27449">issues.joomla.org/tracker/joomla-cms/27449</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
