### PR TITLE
Replacements for deprecated JApplication::getHash()

### PR DESCRIPTION
**Pull request by frankmayer**
Replacements for deprecated JApplication::getHash()

### CODE REVIEW

**Comment by mbabker** [comment]
Can you revert the changes in the test class?  Even though it's deprecated that helps to make sure the old code doesn't unexpectedly break for whatever reason.

**Comment by frankmayer** [comment]
@mbabker Yes, you're right.
I reverted the changes in the test for the deprecated one and added a new test for the new implementation.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8bf68e737aefd3f8a0fe5a30d7dea445040b8d3a<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13162">issues.joomla.org/tracker/joomla-cms/13162</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 8bf68e737aefd3f8a0fe5a30d7dea445040b8d3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13162">issues.joomla.org/tracker/joomla-cms/13162</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13162">issues.joomla.org/tracker/joomla-cms/13162</a>.</sub>

**Pull request merged**
