### PR TITLE
API controller - update comments

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Testing sampledata and the corresponding image folders are no longer delivered with new joomla versions.
The PR adapts comments.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f29da68e6f921efd871a2b8edc517dfee694a10b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37731">issues.joomla.org/tracker/joomla-cms/37731</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f29da68e6f921efd871a2b8edc517dfee694a10b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37731">issues.joomla.org/tracker/joomla-cms/37731</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37731">issues.joomla.org/tracker/joomla-cms/37731</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
