### PR TITLE
Appeasing Appveyor

### PR DESCRIPTION
**Pull request by Hackwar**
Hopefully makeing Appveyor happy again.

### CODE REVIEW

**Comment by zero-24** [comment]
When this helps we should also patch this upstream in the string package: https://github.com/joomla-framework/string/blob/master/src/phputf8/utf8.php#L45 it seams some other changes have been done there in the meantime too.

**Comment by richard67** [comment]
It seems before making Appveyor happy it needs to wake him up.

**Comment by richard67** [comment]
Hooray, appveyor passed with success!!!

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 264fd786600335d19dd7effa632d46ce378d1223<br /><br />Before this PR, Appveyor tests failed here:
[https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/string/src/phputf8/utf8.php#L38](https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/string/src/phputf8/utf8.php#L38 "https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/string/src/phputf8/utf8.php#L38")
with error
> Warning: A non-numeric value encountered in C:\projects\joomla-cms\libraries\vendor\joomla\string\src\phputf8\utf8.php on line 38

With this PR is passes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25234">issues.joomla.org/tracker/joomla-cms/25234</a>.</sub>

**Comment by richard67** [comment]
@zero-24 PR for framwork package see [https://github.com/joomla-framework/string/pull/22](https://github.com/joomla-framework/string/pull/22).

**Comment by richard67** [comment]
@zero-24 ~~Does it need another PR in the framework package for the 2.0-dev branch?~~ No, clarified.

**Comment by Hackwar** [comment]
Since this is the wrong way to fix this, I'm closing this one.

**Comment by richard67** [comment]
@Hackwar Please check PR #25243 .

**Pull request closed without merging**
