### PR TITLE
Field Groups options

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38584  .

### Summary of Changes
For consistency this changes the order of the tabs in Field-groups to match the order in other forms such as Fields-field

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by Franzwohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d155823130617cf51ca54528e26817703445caa1<br /><br />Thanks @brianteeman<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38591">issues.joomla.org/tracker/joomla-cms/38591</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d155823130617cf51ca54528e26817703445caa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38591">issues.joomla.org/tracker/joomla-cms/38591</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38591">issues.joomla.org/tracker/joomla-cms/38591</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
