### PR TITLE
Replace Platform version numbers in libraries/legacy

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes
- Replace Platform version numbers in the `libraries/legacy` directory with CMS version numbers
- Make `@deprecated` tag change to match new questionable structure
### Testing Instructions

Review
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on bc646490dd8040f4953801992ae0b0375a0a6e5e<br /><br />Code review.
Seems fine to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12242">issues.joomla.org/joomla-cms/12242</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bc646490dd8040f4953801992ae0b0375a0a6e5e<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12242">issues.joomla.org/tracker/joomla-cms/12242</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12242">issues.joomla.org/tracker/joomla-cms/12242</a>.</sub>

**Comment by rdeutz** [comment]
@mbabker could you fix the conflict, thanks

**Comment by mbabker** [comment]
Done

**Comment by infograf768** [comment]
@mbabker 
Fatal error when editing module anyhting else as we have 41 instances of it:
`( ! ) Fatal error: Access level to ModulesViewModule::$form must be public (as in class JViewLegacy) in ROOT/administrator/components/com_modules/views/module/view.html.php on line 18`
You added
```
/**
	 * A form object
	 *
	 * @var    JForm
	 * @since  3.2
	 */
	public $form;
```
and the module view.html.php has 
`protected $form;`
as most of the views
`( ! ) Fatal error: Access level to ContentViewArticle::$form must be public (as in class JViewLegacy) in /Applications/MAMP/htdocs/trunkgitnew/administrator/components/com_content/views/article/view.html.php on line 18`

:)

**Comment by mbabker** [comment]
I'm getting sick and freakin' tired of this code stack being so reliant on undeclared class variables.  Issue a PR to remove it.  This is outrageous.

**Pull request merged**
