### PR TITLE
Remove the not implemented nor sense making Off option for SSL

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #13816

### Summary of Changes

This just removes the never needed nor used option to switch SSL of per menu option.

### Testing Instructions

Confirm that the off option is gone if you edit a menu item

### Expected result

off option is gone

### Actual result

Off option is there but never implemented.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
It is used. It describes the state

**Comment by zero-24** [comment]
> It is used. It describes the state

I do not understand that? If you set this option to -1 / Off there is no code which checks that nor makes that sense. If you force https this setting is ignored. And only On makes sense here. Atleast for me.

**Comment by brianteeman** [comment]
Don't think about the code. Think about the user interface.

**Comment by zero-24** [comment]
> Don't think about the code. Think about the user interface.

Sure but for what reason you want to swich that off?

`On` => Overrride the global setting wich says "don't force https" if we force HTTPS this setting is ignored. (it is equal)
`ignore` => use the global settings.
`Off` => Never works nor can it. If the global setting is forced off this setting is makes no sense.

btw. even if you enabled https just to one page there is (at least for me) no need to set this option Off ;)

**Comment by brianteeman** [comment]
It is not about what it does. It's about what it tells the user.

**Comment by zero-24** [comment]
> It's about what it tells the user.

It tells the user he switched it off but this don't work?

**Comment by brianteeman** [comment]
Show me any other example where you have an On option but do not have an
off.

The solution is not to simply remove the off string.

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on ebce41a392c74bc90e0939aeb809231ba0b3a019<br /><br />Patch ok for me. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14771">issues.joomla.org/tracker/joomla-cms/14771</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on ebce41a392c74bc90e0939aeb809231ba0b3a019<br /><br />if you upgrade a site which had been saved with -1 aka off
then if you go to the menu item it will be displayed as being on

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14771">issues.joomla.org/tracker/joomla-cms/14771</a>.</sub>

**Comment by brianteeman** [comment]
screenshotr14-14-35

{"show_title":"1","link_titles":"0","show_intro":"","info_block_position":"","info_block_show_title":"","show_category":"0","link_category":"","show_parent_category":"0","link_parent_category":"","show_associations":"","show_author":"0","link_author":"","show_create_date":"0","show_modify_date":"0","show_publish_date":"0","show_item_navigation":"0","show_vote":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_hits":"0","show_tags":"","show_noauth":"","urls_position":"","menu-anchor_title":"","menu-anchor_css":"","menu_image":"","menu_text":1,"menu_show":1,"page_title":"","show_page_heading":"0","page_heading":"","pageclass_sfx":"","menu-meta_description":"","menu-meta_keywords":"","robots":"",**"secure":-1**}

**Comment by AlexRed** [comment]
yes, I confirm the problem after upgrade. Need an if OFF after upgrade --> Ignore

**Comment by Twincarb** [comment]
I have a site which has 1 page that can't be https all other pages are set to on apart from this single page set to off, this ensures that any visitor arriving from another page on the site see's the page correctly.
leaving the page set to ignore would mean that going from one https page to this one would cause the page to not load correctly.

For there to be logic here, if Force HTTPS is set to Entire site then showing the option in menus should be hidden and ignored, possibly with a non-changeable state of SECURE/ON/ENABLED if the global setting is set to None or Administrator only the menu option is valid and should be selectable.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14771">issues.joomla.org/tracker/joomla-cms/14771</a>.</sub>

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.1-dev (nightly Build)

**Comment by brianteeman** [comment]
@alexred as its still open then of course nothing has changed.

**Pull request closed without merging**
