### PR TITLE
Improve UsersRouterRulesLegacy build method

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes small improvement to UsersRouterRulesLegacy build to make code shorter (and easier to read). Also, when a menu item match a view, we move to check the next menu item (continue command), so performance will be increased a bit, too

### Testing Instructions
1. Code review

2. Apply patch, check and make sure links to registration form, forgot username, forgot password still works like before

### CODE REVIEW

**Comment by ghost** [comment]
> check and make sure links to registration form, forgot username, forgot password still works like before

Tested and Works.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a0027b995cde07e0ca312b54746c67e4fa5c56be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19108">issues.joomla.org/tracker/joomla-cms/19108</a>.</sub>

**Comment by Quy** [comment]
This can be made shorter by making them `elseif` and removing the `continue` statements except for the first one.

**Comment by joomdonation** [comment]
That would work, too. But I am not sure if it will make the code a bit more difficult to follow (too many elseif)

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on a0027b995cde07e0ca312b54746c67e4fa5c56be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19108">issues.joomla.org/tracker/joomla-cms/19108</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
