### PR TITLE
[4.1] Capitalize title

### PR DESCRIPTION
**Pull request by Quy**
Compare capitalization with the other titles.

### Testing
Code review in the following:

Create a new task.
See Task Type dropdown in Filter Options.
See Task Type column in list view.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 29d225684168e90fc993c7b87226fb638e29c2db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36835">issues.joomla.org/tracker/joomla-cms/36835</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 29d225684168e90fc993c7b87226fb638e29c2db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36835">issues.joomla.org/tracker/joomla-cms/36835</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36835">issues.joomla.org/tracker/joomla-cms/36835</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
