### PR TITLE
[4.0] Legend in bold

### PR DESCRIPTION
**Pull request by brianteeman**
The style for the legend class used in global configuration and extensions-install is the same as the field labels so it doesnt stand out.

Changing the $normal-weight to $bold-weight fixes that

###Testing
Requires npm i

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 59fc652ccd184bd6f255a106c96ec529c54d4d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24322">issues.joomla.org/tracker/joomla-cms/24322</a>.</sub>

**Comment by ciar4n** [comment]
As you are reverting https://github.com/joomla/joomla-cms/pull/23927, you can remove the font-weight rather than changing it.

**Comment by brianteeman** [comment]
@ciar4n will do. Your pr shouldnt have been merged (not your fault) - it was too generic

**Comment by ciar4n** [comment]
If #23927 is still required you can move the font weight and size inside a `.control-group legend` selector.

```
.control-group legend {
  font-size: 1rem;
  font-weight: $normal-weight;
}
```

If not then leave as it.

**Comment by brianteeman** [comment]
Thanks for the tip - its not needed yet as the switcher code hasnt been changed yet

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3bc743dadc73ee7e014c5824befe9d63b590e3f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24322">issues.joomla.org/tracker/joomla-cms/24322</a>.</sub>

**Comment by brianteeman** [comment]
@wilsonge can this get merged please - its a simple revert

**Comment by wilsonge** [comment]
What's going on with the originally proposed code in #23888 because originally this was done for that.

**Comment by brianteeman** [comment]
That was jumping the gun. Current work is in #24463

**Comment by brianteeman** [comment]
thanks

**Comment by wilsonge** [comment]
Makes sense. Thanks!

**Pull request merged**
