### PR TITLE
[com_menu] Hide id on mobile

### PR DESCRIPTION
**Pull request by brianteeman**
We dont usually display the ID on mobile view
#### Before

o7f7
#### After

c456

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i would hide the modules too, so the view is cleaner.

**Comment by brianteeman** [comment]
I think it is OK to leave them there as they have specific functionality and are not just for display

**Comment by andrepereiradasilva** [comment]
try to click on them on mobile view ...

**Comment by brianteeman** [comment]
works ok to me

On 4 May 2016 at 13:31, andrepereiradasilva <notifications@github.com>
wrote:

> try to click on them on mobile view ...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10231#issuecomment-216845689>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 47834ab887ebb42f581283292194d95eac65c0fb<br /><br />as said i think the "Modules" should be removed on mobile to, but this PR removes the ID that should be removed. So test ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10231">issues.joomla.org/joomla-cms/10231</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 47834ab887ebb42f581283292194d95eac65c0fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10231">issues.joomla.org/joomla-cms/10231</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10231">issues.joomla.org/joomla-cms/10231</a>.</sub>

**Pull request merged**
