### PR TITLE
Add Sort by Modified Date in the Module mod_articles_news

### PR DESCRIPTION
**Pull request by imanickam**
Pull Request for Issue # .  This Pull Request is not based on any issue.  It is an improvement to the existing function of the module.  At present the module has the facility to sort the articles by the publish up and created dates.  With this change, the ability to sort the articles by the modified date is also possible.  Especially, this change would help in listing the recently modified articles.
#### Summary of Changes

(a) File mod_articles_news.xml -> Added another sort option value a.modified (Article Modified Date) to the existing values a.publish_up (Article Publish Start/Up Date) and a.created (Article Created Date). 
(b) File mod_articles_news.ini -> Added the new language string to show the text string "Modified Date".
#### Testing Instructions

Modify a couple of articles that has the earliest publish up date.  Change the sort order in the module to "Modified Date" in the option "Order Results".  You should see list of modified articles.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 566387b2cf570607b8cef63876a9ea6b53554fe1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11128">issues.joomla.org/joomla-cms/11128</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11128">issues.joomla.org/joomla-cms/11128</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11128">issues.joomla.org/joomla-cms/11128</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 566387b2cf570607b8cef63876a9ea6b53554fe1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11128">issues.joomla.org/joomla-cms/11128</a>.</sub>

**Comment by wilsonge** [comment]
Merged to the 3.7 branch :) Thanks!

**Pull request merged**
