### PR TITLE
[4.0] fix a no jQuery error, com_finder

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/33814 .

### Summary of Changes
- Moves the js where it belongs, ie in it's own script file
- Fixes the invalid HTML, ie ids ARE unique

Screenshot 2021-05-16 at 19 22 21

### Testing Instructions
Follow the instructions on https://github.com/joomla/joomla-cms/issues/33814

### Documentation Changes Required

No

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on cd0e49f966700366047e46f0e7204d5231d5618c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33921">issues.joomla.org/tracker/joomla-cms/33921</a>.</sub>

**Comment by ghost** [comment]
Issue "Select switch" successfully test, but can't find the fixed HTML, so no submit a test result.

**Comment by richard67** [comment]
@sandramay0905 Fixed html can be checked in developer tools of the browser.

**Comment by ghost** [comment]
I looked in the source code for the 2 blue marked lines in the image in opening comment.

**Comment by dgrammatiko** [comment]
> I looked in the source code for the 2 blue marked lines in the image in opening comment

And... ?
BTW the screenshot is from the before, as I wrote ids SHOULD be unique, so the fixed version doesn't have ids

**Comment by ghost** [comment]
The "tax-2" is now inside the class, there is no "id=":

> image

@dgrammatiko I guess that's what you mean. If yes, i can give a successfully result.

**Comment by dgrammatiko** [comment]
> @dgrammatiko I guess that's what you mean

Yes this was the change

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cd0e49f966700366047e46f0e7204d5231d5618c

Thanks for help @dgrammatiko.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33921">issues.joomla.org/tracker/joomla-cms/33921</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33921">issues.joomla.org/tracker/joomla-cms/33921</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
