### PR TITLE
[4.0] cassiopeia. Screenreader/Accessibility markup

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26830

### Summary of Changes
- Moved aria-hidden to icon.

### Testing Instructions
Code review of experts.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
There are no experts here 😄 .

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on dd7ab263a941faa4215664caa4fdd7fe067cb297<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26831">issues.joomla.org/tracker/joomla-cms/26831</a>.</sub>

**Comment by brianteeman** [comment]
Before this PR the code meant that the entire button was hidden to screen readers. After this PR just the icon. So good spot!!

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on dd7ab263a941faa4215664caa4fdd7fe067cb297<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26831">issues.joomla.org/tracker/joomla-cms/26831</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26831">issues.joomla.org/tracker/joomla-cms/26831</a>.</sub>

**Pull request merged**
