### PR TITLE
[Improvement] Backend menu item edit form : Add Itemid to the alias link value

### PR DESCRIPTION
**Pull request by marrouchi**
The link field of an alias menu item displays "index.php?Item=" without the actual item id.
menus edit item stagging administration

### Summary of Changes
I've added the menu item id to the link value in the MenusModelItem::getItem method.
### Testing Instructions
Create a menu alias and stay in the menu item edit form.
- Before the PR 
After save, you should see "index.php?Itemid=" in the link value readonly field.
- After the PR 
After save, you should see "index.php?Itemid=**XXX**" in the link field with **XXX** being the actual menu item id.
### Documentation Changes Required
No documentation changes required

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 64184ccacb772410cad76ae3fd22884dbb6dbfd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13776">issues.joomla.org/tracker/joomla-cms/13776</a>.</sub>

**Comment by marrouchi** [comment]
@csthomas Could you test please ?

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 8316dd9a1a61f3c74cf43c958085db7d2697c396<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13776">issues.joomla.org/tracker/joomla-cms/13776</a>.</sub>

**Comment by marrouchi** [comment]
RTC please.

**Comment by jeckodevelopment** [comment]
@marrouchi it needs another test.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8316dd9a1a61f3c74cf43c958085db7d2697c396<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13776">issues.joomla.org/tracker/joomla-cms/13776</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13776">issues.joomla.org/tracker/joomla-cms/13776</a>.</sub>

**Comment by rdeutz** [comment]
Why did you made the PR, the link isn't used IIRC?

**Comment by marrouchi** [comment]
@rdeutz I notice this when i've tested the PR #11343 and it seemed to me like a glitch. I find that is more "cleaner" to display the actual Itemid then to display "index.php?Itemid=" in each alias edit form. Sure it's not used anywhere in the code source for now, but it can be helpful for the administrator to know that an alias does not point on any component and it's just simply represented by an Itemid (just like any other menu item link value is shown).

**Comment by rdeutz** [comment]
ok it doesn't hurt so I am going to merge it

**Comment by infograf768** [comment]
@rdeutz  @marrouchi 
Except that each save adds the Itemid number in the field.
Look at:
https://github.com/joomla/joomla-cms/issues/14264

**Comment by izharaazmi** [comment]
Why do we need an Id value appended anyway? Menu module handles the item alias itself, I think.

**Comment by infograf768** [comment]
yes, it uses the params `aliasoptions` to create the link.

**Comment by infograf768** [comment]
I suggest to revert this as it just confuses the user.

**Comment by izharaazmi** [comment]
Right. However we should re-verify frontend menu afterwards.

**Comment by infograf768** [comment]
I did. No issues after revert as this link field value is just not used at all.

in mod_menu helper
```php
						case 'alias':
							$item->flink = 'index.php?Itemid=' . $item->params->get('aliasoptions');
							break;
```
in /libraries/cms/pathway/site.php
```php
						case 'alias':
							// If this is an alias use the item id stored in the parameters to make the link.
							$url = 'index.php?Itemid=' . $link->params->get('aliasoptions');
							break;
```

etc.

**Comment by izharaazmi** [comment]
Great 👍

**Comment by marrouchi** [comment]
Oups, i'm sorry for this. I'll revert right away !

**Pull request merged**
