### PR TITLE
Missing word in string

### PR DESCRIPTION
**Pull request by brianteeman**
### Before

JGLOBAL_SHOW_CREATE_DATE_DESC="If set to Show, the date and time an Article was created will be displayed. This a global setting but can be changed at Menu and Article levels."

### After
JGLOBAL_SHOW_CREATE_DATE_DESC="If set to Show, the date and time an Article was created will be displayed. This is a global setting but can be changed at Menu and Article levels."

Pull Request for Issue # .

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9c79ebfeaac5d16a6cd36ab788a27aafc641bafd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17064">issues.joomla.org/tracker/joomla-cms/17064</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9c79ebfeaac5d16a6cd36ab788a27aafc641bafd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17064">issues.joomla.org/tracker/joomla-cms/17064</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz 
This should go in today as we freeze languages today.

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17064">issues.joomla.org/tracker/joomla-cms/17064</a>.</sub>

**Review by rdeutz — APPROVED** [review]

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
