### PR TITLE
[4.0] Fix WebAsset PHP error when a component name is empty

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #29502 .

### Summary of Changes
Checking whether $component not empty

### Testing Instructions
Apply patch, and follow any non existing URL, eg `index.php?Itemid=429`

### Expected result
"Component not found" error

### Actual result
WebAssetRegistry exception

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8014ca584876e25ebde34d4850c93edc2b0ca55f<br /><br />Before applying Patch, Actual result:
0 Argument 1 passed to Joomla\CMS\WebAsset\WebAssetRegistry::addExtensionRegistryFile() must be of the type string, null given, called in/xxxxxx/libraries/src/Application/SiteApplication.php on line 173

With Patch, Expected result:
404 Component not found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29530">issues.joomla.org/tracker/joomla-cms/29530</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8014ca584876e25ebde34d4850c93edc2b0ca55f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29530">issues.joomla.org/tracker/joomla-cms/29530</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29530">issues.joomla.org/tracker/joomla-cms/29530</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
