### PR TITLE
[5.1] Use Dialog for Multilanguage status overview

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Use Dialog for Multilanguage status overview, instead of BS modal

### Testing Instructions
Enable multilanguage,
Click "Multilingual Status" to view the status popup

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Reference:
- https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9c3fba6ce25ab334bb2a9f500594f627527428fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42082">issues.joomla.org/tracker/joomla-cms/42082</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9c3fba6ce25ab334bb2a9f500594f627527428fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42082">issues.joomla.org/tracker/joomla-cms/42082</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42082">issues.joomla.org/tracker/joomla-cms/42082</a>.</sub>

**Comment by LadySolveig** [comment]
Many thanks Fedir and also to the testers @Quy @viocassel  and for the review @dgrammatiko !

**Pull request merged**
