### PR TITLE
[4.0] Check all tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
Remove the hasTooltip class and simplify the code as we dont need to use the helper or a variable

This is for the title on the check box used to select all items in a list

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0cc9a5994d722d66ae18a08cd06c60f84f04d283<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25614">issues.joomla.org/tracker/joomla-cms/25614</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0cc9a5994d722d66ae18a08cd06c60f84f04d283<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25614">issues.joomla.org/tracker/joomla-cms/25614</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
This one requires documentation as we're removing a param from a library method. Other than that all good

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
