### PR TITLE
[4.1] storage of the e-mail address in com_privacy

### PR DESCRIPTION
**Pull request by tecpromotion**
### Testing Instructions

Steps to Reproduce:

1. Create a new menu item of the type Privacy -> Create Request
2. Log in to the frontend
3. Click on the menu item 'Create Request
4. Submit export or deletion request
5. check your mails -> there should be an email request
6. Click confirmation link
7. Confirm request on the website

### Actual result BEFORE applying this Pull Request

No e-mail address is stored in com_privacy when confirm the privacy request.
There is no matching between the sent e-mail with the token and the database entry!

empty

### Expected result AFTER applying this Pull Request

e-mail address is stored

email-not-empty

### Documentation Changes Required

.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 99b49510d82c39ece304cdf0564355c0a4cbf0b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36970">issues.joomla.org/tracker/joomla-cms/36970</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 99b49510d82c39ece304cdf0564355c0a4cbf0b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36970">issues.joomla.org/tracker/joomla-cms/36970</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36970">issues.joomla.org/tracker/joomla-cms/36970</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
