### PR TITLE
[4.0] Post installation module description

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the description so that it is clear the module displays a count and a link of the messages and not the actual messages

PR for #33524

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6f82dae50f3845f1e9cdc6a62f792399e7536d0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33625">issues.joomla.org/tracker/joomla-cms/33625</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6f82dae50f3845f1e9cdc6a62f792399e7536d0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33625">issues.joomla.org/tracker/joomla-cms/33625</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33625">issues.joomla.org/tracker/joomla-cms/33625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
