### PR TITLE
[5.0] User events fix message type

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #41450 .

### Summary of Changes
Fix mesage type, and some required arguments

### Testing Instructions
Please follow #41450 :
> In Joomla 5 go to Users > Manage, click on an Enabled icon to enable or disable a user account

Also try create/edit/delet user

### Actual result BEFORE applying this Pull Request
An error `Argument 1 ($value) must be of type string, null given`

### Expected result AFTER applying this Pull Request
All works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on fa96fc161e7f488936abaaec67e8e5d13d46f010<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41464">issues.joomla.org/tracker/joomla-cms/41464</a>.</sub>

**Comment by pjasmits** [comment]
I have tested this item ✅ successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41464">issues.joomla.org/tracker/joomla-cms/41464</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fa96fc161e7f488936abaaec67e8e5d13d46f010<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41464">issues.joomla.org/tracker/joomla-cms/41464</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41464">issues.joomla.org/tracker/joomla-cms/41464</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
