### PR TITLE
Enable caching of menu data in JMenuSite

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Enables caching of the data from the `#__menu` table when working with a `JMenuSite` object.
#### Testing Instructions

The menu data should be correctly cached with caching enabled and the cache reset when changes in the backend are made.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c216be76cc69e83dba4df4f5ba284da9da04fcd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10797">issues.joomla.org/joomla-cms/10797</a>.</sub>

**Comment by mbabker** [comment]
Is this going anywhere or can I close for lack of interest?

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c216be76cc69e83dba4df4f5ba284da9da04fcd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10797">issues.joomla.org/joomla-cms/10797</a>.</sub>

**Comment by mbabker** [comment]
This is rebased to the 3.7 branch to be able to use a lambda function for the callback.

**Comment by mbabker** [comment]
Travis-CI will fail on this PR due to existing failures in the 3.7 branch - last build on the branch as of this writing is at https://travis-ci.org/joomla/joomla-cms/builds/153564006

**Pull request merged**
