### PR TITLE
[4.0] language filenames

### PR DESCRIPTION
**Pull request by brianteeman**
Update the name of the language file in the module and plugin xml

Components was done some time ago

As they arent really installable its more for reference

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3fa7f5e99acc708f46d0b99d04a3b8f0b624ce41<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34963">issues.joomla.org/tracker/joomla-cms/34963</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3fa7f5e99acc708f46d0b99d04a3b8f0b624ce41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34963">issues.joomla.org/tracker/joomla-cms/34963</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34963">issues.joomla.org/tracker/joomla-cms/34963</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
