### PR TITLE
Fix up the 'core' javascript file

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This is the follow up to this here: #6509

Define the Joomla 'core' function inside of a strict closure, fix all the ensuing problems.
- missing semicolons: fixed
- undeclared variables: fixed
- nonsense code: sort of fixed
## Testing

These functions are used all over the place and, since the file was not in strict mode before, the mistakes in it were not apparent anyway. So the best way to test is to first try #6509 and see where it goes wrong. There is usually a comment above each function to tell where it is used. These are generally reliable. 

There are certainly several functions which are no longer used at all and some which are specifically deprecated. There is some chance that a 3rd party is using them but there should be a plan for removing all the junk.

### CODE REVIEW

**Comment by Fedik** [comment]
@okonomiyaki3000 please check the `core.js`, there was some changes to `Joomla.submitform`, and maybe some other ... that cause the merge conflict

**Comment by okonomiyaki3000** [comment]
Uh. Great. These errors have nothing to do with any of these changes. Thanks, Travis.

**Comment by okonomiyaki3000** [comment]
It seems that `FOFPlatform` (whatever it is) does not implement the method `logAddLogger` which it is supposed to do. So this causes Travis to fail. Please note that `FOFPlatform` has nothing to do with the `core` javascript file which is the only thing modified by this PR.

**Comment by Fedik** [comment]
**test** works good for me

**Comment by Bakual** [comment]
> These errors have nothing to do with any of these changes. Thanks, Travis.

Travis recently sometimes stalls because it takes to long to fetch the dependencies with composer.
I've restarted the failing job, hopefully it will pass now.

**Comment by anibalsanchez** [comment]
#TEST OK

Nice to have a cleaner Javascript implementation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6512">issues.joomla.org/joomla-cms/6512</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6512">issues.joomla.org/joomla-cms/6512</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @okonomiyaki3000. I've fixed the conflicts and merged the PR.

**Comment by javigomez** [comment]
@Kubik-Rubik I think this merge cause this issue: http://issues.joomla.org/tracker/joomla-cms/7388

**Comment by Kubik-Rubik** [comment]
@javigomez Thank you, we have to check it. 

@okonomiyaki3000 @Fedik @anibalsanchez Could you also take a look?

**Comment by Fedik** [comment]
yes, need some time, and I will make a pull ... if no one will make it faster :smile:

**Comment by Fedik** [comment]
@Kubik-Rubik  there it is #7391

**Comment by Kubik-Rubik** [comment]
@Fedik Wow, that was fast. Thank you, I will check it soon. @javigomez Could you please test this PR #7391 by Fedik?

**Comment by okonomiyaki3000** [comment]
@Fedik @Kubik-Rubik Thanks!

**Pull request closed without merging**
