### PR TITLE
[4.0] Error deleting access levels

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes class not found error when deleting access level.

### Testing Instructions

Code review or try to delete an access level.

### Expected result

Access level deleted.

### Actual result

Class not found errors.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9b272d53921e7e21e3cabd75a0ea19062590f5b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29101">issues.joomla.org/tracker/joomla-cms/29101</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9b272d53921e7e21e3cabd75a0ea19062590f5b8<br /><br />Code review + real test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29101">issues.joomla.org/tracker/joomla-cms/29101</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29101">issues.joomla.org/tracker/joomla-cms/29101</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9b272d53921e7e21e3cabd75a0ea19062590f5b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29101">issues.joomla.org/tracker/joomla-cms/29101</a>.</sub>

**Pull request merged**
