### PR TITLE
[4.0] Database information [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Same issue as with #29902

Ensures that there is only one label and that it is correctly named

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2c6b6d309e5457a8abcaa214381a9b113385a132<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29911">issues.joomla.org/tracker/joomla-cms/29911</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2c6b6d309e5457a8abcaa214381a9b113385a132<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29911">issues.joomla.org/tracker/joomla-cms/29911</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29911">issues.joomla.org/tracker/joomla-cms/29911</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
