### PR TITLE
[4.0] Drop inline script for caption.js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Drop inline scripts
- javascript tests fixes

### Testing Instructions

if all tests green no tests needed!

### CODE REVIEW

**Comment by Bakual** [comment]
Do we still need the caption.js? Imho all it does is what native HTML already can do for quite some time.

**Comment by laoneo** [comment]
Would be nice to get rid of it.

**Comment by infograf768** [comment]
as far as I remember, we kept it for B/C some time in the past.

**Comment by brianteeman** [comment]
> update all content to use figure (tinyMCE does that already, but probably needs an sql script for content table)

I would be very reluctant to do anything that alters a users data

**Comment by dgt41** [comment]
@brianteeman so we need one legacy.php override.
Anyways this PR mainly created as a guideline to the javascript tests for the GSOC student (no inline scripts and a way to cope with Joomla.storageOptions)

**Comment by Bakual** [comment]
> as far as I remember, we kept it for B/C some time in the past.

We kept it for B/C when we changed the image button to use the native elements. But with J4 we can imho drop it. Maybe make it available as extern plugin for those who still need it for some reason.

> create one more layout override in the front end template e.g. legacy.php

What for? What would that override achieve?

> update all content to use figure (tinyMCE does that already, but probably needs an sql script for content table)

Nah, never change user data. You can document it for users who want to do that themself or offer the JS as a plugin as I said above. But we need to drop that JS anyway and it will have the same impact if we do that in J4 or Jx.

**Comment by dgt41** [comment]
@Bakual https://github.com/joomla/joomla-cms/pull/15956/files#diff-f6f264d0b0673dc25ecc75e7746ec235R77
it not even marked as deprecated ATM, so dropping it at least requires some prior notification...
Anyways I'm not against removing this legacy thing, just don't want to be the person to blame once again 😜

**Comment by mbabker** [comment]
> just don't want to be the person to blame once again 😜

You're the George of our JavaScript code, everything's your fault :rofl:

**Comment by dgt41** [comment]
I know 😞

**Comment by Bakual** [comment]
> it not even marked as deprecated ATM

We can easily deprecate it in 3.8.

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 73222e9d3306ce8a583ef8f56c3d98474626db61<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15956">issues.joomla.org/tracker/joomla-cms/15956</a>.</sub>

**Comment by zero-24** [comment]
@dgt41 can you take a look into the conflict?

**Comment by dgt41** [comment]
@zero-24 done!

**Comment by wilsonge** [comment]
OK I'm going to merge this. But I've also created a follow up issue https://github.com/joomla/joomla-cms/issues/16948 for dropping caption altogether

**Pull request merged**
