### PR TITLE
[5.2] json encoded in bind method

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted whilst working elsewhere and struggled to understand the code comment as the description was confising.

This simple PR corrects the grammar so that it is more understandable

Code review only required as its a doc block

### Comment
Maintainers can decide the best branch

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1e67d585350190262375a6437b785aac3e81694a<br /><br />Tested by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43273">issues.joomla.org/tracker/joomla-cms/43273</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1e67d585350190262375a6437b785aac3e81694a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43273">issues.joomla.org/tracker/joomla-cms/43273</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43273">issues.joomla.org/tracker/joomla-cms/43273</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by pe7er** [comment]
Thanks @brianteeman !

**Pull request merged**
