### PR TITLE
[5.0] Replace JPATH_PLATFORM with _JEXEC

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Apply changes from #40343 to current branch due prs:
- #39657
- #40082
- #41056

### Testing Instructions

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1fa1c44b89715c6209097dd9e0ed3c8855c80d4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41419">issues.joomla.org/tracker/joomla-cms/41419</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 1fa1c44b89715c6209097dd9e0ed3c8855c80d4a<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41419">issues.joomla.org/tracker/joomla-cms/41419</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41419">issues.joomla.org/tracker/joomla-cms/41419</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
