### PR TITLE
Improve performance for filter input

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #16112

### Summary of Changes
Joomla does not have to use multibyte `mb_` or `utf8_` functions to parsing UTF-8 input.

### Testing Instructions
* Travis passed
* tests on big input from https://gist.github.com/csthomas/0f54676ca271a782985e7ddcd072fc5f
* code review.
* there is no security vulnerabilities.

### Expected result
All works as expected and parsing is faster.

### Actual result
Parsing is slow.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by lynnfredricks** [comment]
#16112 
@franz-wohlkoenig I just tested with 3.7.2 and execution time is not improved enough. Error has changed through:
/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 94

**Comment by csthomas** [comment]
@lynnfredricks There is some misunderstanding. You said that you tested J3.7.2 and it is still slow, but IMO you have not tested it with current patch.

### TEST INSTRUCTION

To test with current patch you can do:
1. Create a copy of your original file in `libraries/joomla/filter/input.php`
2. Download a file from https://raw.githubusercontent.com/csthomas/joomla-cms/1532e1156e6aba108af4fe649e6ffece4b4a10f8/libraries/joomla/filter/input.php

3. Save downloaded file to your joomla folder, by replacing libraries/joomla/filter/input.php
4. Now you can start the tests.
5. After tests you can revert changes

The other way is to install fresh joomla from my branch:
1. Download and install Joomla from `https://github.com/csthomas/joomla-cms/archive/fixfilter.zip`
2. Add article and test.

Or 
1. To your current installed joomla 3.7.2 install component `com_patchtester` from:
https://github.com/joomla-extensions/patchtester/releases/tag/2.0.1
2. Apply patch with the same title as this PR or search by id 16201
3. After this patch will be applied then you can start the tests.
4. After tests you can `revert` changes in the component and uninstall `com_patchtester`

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1532e1156e6aba108af4fe649e6ffece4b4a10f8<br /><br />This is spectacular!

Logged as a manager with the said article to which I added some utf8 in pagebreak.

Before patch: 270sec

After patch: between 15 and 20 sec depending if reload is included!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16201">issues.joomla.org/tracker/joomla-cms/16201</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 1532e1156e6aba108af4fe649e6ffece4b4a10f8<br /><br />Patch ok for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16201">issues.joomla.org/tracker/joomla-cms/16201</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by lynnfredricks** [comment]
@csthomas  Thank you for the instructions and help! I can confirm that I was able to both duplicate the existing article and also update / replace the text of the existing long article.

**Pull request merged**
