### PR TITLE
[4.0] Media Manager list view

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #26694

### Steps to reproduce the issue
Open the media manager and switch to list view
On hovering over any folder or file we can see a cursor instead of the finger pointer in list view.
### Expected result
Instead of the cursor popup over the folders or images finger pointer should be displayed.

### Actual result
On mouse hover over the folders we see a cursor pointer.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7bff08acdc61c0f64f02e0693b2f6dc99e36c9ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27780">issues.joomla.org/tracker/joomla-cms/27780</a>.</sub>

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 7bff08acdc61c0f64f02e0693b2f6dc99e36c9ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27780">issues.joomla.org/tracker/joomla-cms/27780</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27780">issues.joomla.org/tracker/joomla-cms/27780</a>.</sub>

**Comment by brianteeman** [comment]
thanks -

**Pull request merged**
