### PR TITLE
[mod_articles_category] Option to show tags

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #17270.

### Summary of Changes

This adds an option to show article tags.

### Testing Instructions

Create `Articles - Category` module. Set `Tags` option  in `Display Options` tab.

### Expected result

Tags are shown/hidden based on setting.

### Documentation Changes Required
New option added.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b77ba8368afe59aec355724f08c13b617c3c0eee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21030">issues.joomla.org/tracker/joomla-cms/21030</a>.</sub>

**Review by brianteeman — APPROVED** [review]
approve language changes

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b77ba8368afe59aec355724f08c13b617c3c0eee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21030">issues.joomla.org/tracker/joomla-cms/21030</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21030">issues.joomla.org/tracker/joomla-cms/21030</a>.</sub>

**Pull request merged**
