### PR TITLE
#3384 Tooltip for INPUT showing whole image path

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/joomla/joomla-cms/pull/3971

Closed old pull request (because I don't know how to change old one ;-)). New one is JQuery based now. Fixes width of tooltip (no automatic newlines with Chrome). Changes of path are now recognized dynamically by JQuery script without need to save form first.

### CODE REVIEW

**Comment by brianteeman** [comment]
The issue  is still valid but unfortunately the PR has been removed

@illovo can you resubmit it please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3994">issues.joomla.org/joomla-cms/3994</a>.</sub>

**Comment by infograf768** [comment]
Looks like I can't reproduce the issue now in Firefox as no tooltip displays when hovering the input. (Test on staging)

**Comment by brianteeman** [comment]
Tested patch manually as it cant be tested with com_patchtester

screen shot 2015-01-31 at 04 30 33


All good to me and very useful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3994">issues.joomla.org/joomla-cms/3994</a>.</sub>

**Comment by brianteeman** [comment]
Two good tests setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3994">issues.joomla.org/joomla-cms/3994</a>.</sub>

**Pull request closed without merging**
