### PR TITLE
UI improvement fix the position of logo-collapsed in the sidbar

### PR DESCRIPTION
**Pull request by anmode**
Pull Request for UI Improvement

### Summary of Changes
Just change the position of the side logo after collapsing it is not aligned with the rest icon present bottom to it if we align the logo with the rest icons it looks good I think! 

### Testing Instructions
just login to your dashboard and see the logo position after collapsing it.

### Actual result BEFORE applying this Pull Request
WhatsApp Image 2022-03-17 at 12 03 56 PM (1)

### Expected result AFTER applying this Pull Request
WhatsApp Image 2022-03-17 at 12 03 56 PM

### Documentation Changes Required
No document changes.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please use logical css properties. That way it will also be correct for right to left RTL languages

**Comment by anmode** [comment]
> 

Actually i didn't know which property will be suitable, I'll try to figure out and commit it soon.

**Comment by richard67** [comment]
> Actually i didn't know which property will be suitable, I'll try to figure out and commit it soon.

@anmode Check https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

**Comment by simbus82** [comment]
I think it's enough to add this
https://github.com/simbus82/joomla-cms/commit/e991e80c7da8acd94af8eb4ae17244bb92164972

Even if the animation, then, will not be beautiful...

**Comment by anmode** [comment]
> > Actually i didn't know which property will be suitable, I'll try to figure out and commit it soon.
> 
> @anmode Check https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

sure! Thanks

**Comment by anmode** [comment]
> I think it's enough to add this [simbus82@e991e80](https://github.com/simbus82/joomla-cms/commit/e991e80c7da8acd94af8eb4ae17244bb92164972)
> 
> Even if the animation, then, will not be beautiful...

yeah! This is fine and solved the problem too.

**Comment by richard67** [comment]
@anmode Currently your PR shows zero changes, i.e. you've reverted all. Will there come some changes?

**Comment by anmode** [comment]
> @anmode Currently your PR shows zero changes, i.e. you've reverted all. Will there come some changes?

yess I am committing changes....soon pushing

**Comment by anmode** [comment]
> @anmode Currently your PR shows zero changes, i.e. you've reverted all. Will there come some changes?

done! I had committed all the changes. idk why build fails! I need to correct it? help me out in that little please

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2a0a9b5fc2c9789fc1b785a86dfab9bc23380958<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37303">issues.joomla.org/tracker/joomla-cms/37303</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2a0a9b5fc2c9789fc1b785a86dfab9bc23380958<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37303">issues.joomla.org/tracker/joomla-cms/37303</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37303">issues.joomla.org/tracker/joomla-cms/37303</a>.</sub>

**Comment by bembelimen** [comment]
Thanks @anmode for your first contribution. Keep up the good work! :+1:

**Comment by anmode** [comment]
> Thanks @anmode for your first contribution. Keep up the good work! 👍

Thanks a lot 😄.

**Pull request merged**
