### PR TITLE
[4.0] latest version

### PR DESCRIPTION
**Pull request by brianteeman**
Update the description as discussed #32453

### CODE REVIEW

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on e23e15ba1692039ca05491b60e554bb2ca1786d3<br /><br />Thank you
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32464">issues.joomla.org/tracker/joomla-cms/32464</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32464">issues.joomla.org/tracker/joomla-cms/32464</a>.</sub>

**Comment by richard67** [comment]
@infograf768 Your RTC also includes a successful test? I yes, I'll set the test result in the tracker for you so the merge button becomes green ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e23e15ba1692039ca05491b60e554bb2ca1786d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32464">issues.joomla.org/tracker/joomla-cms/32464</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
