### PR TITLE
[plgTinyMCE] Error correction. Now you can drag and drop images into the article so that the image is saved to a custom directory.

### PR DESCRIPTION
**Pull request by korenevskiy**
If you are in the plugin `TinyeMCE` settings, select a subdirectory for saving images. Then when you drag the image into the article editor, the image will not be saved to the selected user subdirectory, but will be saved as before to the parent `/images` directory. 
But now the images will be saved to the selected user under the directory in the `/images` directory.

Before POST/GET request
```JS
option: com_media
format: json
url: 1
task: api.files
path: local-images:

content: "imageData"
name: "____Image.jpg"
parent: "publicacations_2023"
```
After Fix POST/GET request
```JS
option: com_media
format: json
url: 1
task: api.files
path: local-images:publications_2023

content: "imageData"
name: "____Image.jpg"
parent: "publicacations_2023"
```
The problem of saving the image to a subdirectory was in the absence of the name of the subdirectory in the `path:` parameter.
Because it is in the component that the images are saved to the subdirectory that is specified in the `path:` parameter of the POST request.
`administrator/components/com_media/src/Controller/ApiController.php`
In method `ApiController->getPath()`

Can you tell me if this PR needed to be added to [4.3-dev]?

### CODE REVIEW

**Comment by Quy** [comment]
Please close #39946 if this PR is for it.

**Comment by korenevskiy** [comment]
> Please close #39946 if this PR is for it.

No, this is a completely different problem.

**Comment by korenevskiy** [comment]
@Quy  
Please tell me the file `media/plg_editors_tinymce/js/plugins/dragdrop/plugin.js` in the repository corresponds to the CMS file `build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js`?

**Comment by brianteeman** [comment]
There are two different issues here
1. bug - fixes the path for drag and drop
2. new feature - adds the context

Please seperate this into seperate pull requests. The bug fix is absolutely needed. I am not sure about the new feature

**Comment by richard67** [comment]
As this PR here fixes a bug, it is ok for 4.2-dev as it is.

**Comment by korenevskiy** [comment]
> Please seperate this into seperate pull requests. The bug fix is absolutely needed. I am not sure about the new feature

I divided it.

**Review by dgrammatiko — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fdad2f431dddf015941e7b52d71aadeea55ba373<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39957">issues.joomla.org/tracker/joomla-cms/39957</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on fdad2f431dddf015941e7b52d71aadeea55ba373<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39957">issues.joomla.org/tracker/joomla-cms/39957</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39957">issues.joomla.org/tracker/joomla-cms/39957</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
