### PR TITLE
s/transiterating/transliterating

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/transiterating/transliterating

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on e5977ee35b82be52441a0e8c08fe0cad87bdabd4<br /><br />Correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31948">issues.joomla.org/tracker/joomla-cms/31948</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e5977ee35b82be52441a0e8c08fe0cad87bdabd4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31948">issues.joomla.org/tracker/joomla-cms/31948</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31948">issues.joomla.org/tracker/joomla-cms/31948</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
