### PR TITLE
Add a redirection for the menu item alias

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #19340 and #19624

### Summary of Changes
Proposal to solve problems. 

### Testing Instructions
See issues.

### Expected result
When you go to the link that is an alias then you will be redirected to the correct page.

### Actual result
You remain on a page of the menu item alias.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8c5c9072583ed010168d34242def9ecb935e4da5<br /><br />It works fine here.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22432">issues.joomla.org/tracker/joomla-cms/22432</a>.</sub>

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 8c5c9072583ed010168d34242def9ecb935e4da5<br /><br />Works as expected. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22432">issues.joomla.org/tracker/joomla-cms/22432</a>.</sub>

**Comment by infograf768** [comment]
@mbabker 
Please check before merging that there are no unwanted consequences.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22432">issues.joomla.org/tracker/joomla-cms/22432</a>.</sub>

**Comment by sanderpotjer** [comment]
This change has unwanted consequences for us... An alias is not always necessarily a redirect. We are using aliases on purpose and don't want to have a 301 redirect for it (otherwise we would have created a redirect). 

An example: we generate AMP-equivalents of pages by using the Alias menu-item. Thanks to the "Template Style" setting of the alias menu-item we can load a different (amp-focussed) template for that page. So e.g.:
- website.com/article: menu-type article
- website.com/amp/article: menu-type alias, with a **different template selected** and alias to "article".

Joomla 3.8.13:
website.com/amp/article is showing the article with the different (AMP) template 

Joomla 3.9.0:
website.com/amp/article is redirected to website.com/article

If the "alias" should be considered as "redirect" after this patch, I don't see why we are still offering options for selecting the template style.

I do think we have two options here:
1: Revert this PR, and introduce a new System menu-type "Redirect" besides "Alias".
2: Add a new toggle option "Redirect": Yes/No, so you can select if the menu-item needs to be redirected or not.

**Comment by csthomas** [comment]
I like point 2 more, but I'm not sure if the field label "Redirect" will be understandable.

**Comment by PatrickExact** [comment]
This change affects our site as well. We are using a similar set-up as @sanderpotjer describes.

Option 2 should fix this change for sure.

**Comment by csthomas** [comment]
I will try to prepare a new PR with option 2

**Comment by phproberto** [comment]
This change broke our site.

Extensions using jQuery.ajax method like:

```javascript
				jQuery.ajax({
					context:this,
					url: 'index.php?option=com_mycomponent&task=mycontroller.method&format=raw',
					dataType: 'json',
					data: {start: start.format(),end: end.format()},
					success: function(doc) {
						// Do something
					}
				});
```

Are now causing a redirection. It also happens with POST requests. I know using urls in javascript without using the routing system are not technically ok but they are actually used by extensions and this breaks things.

I had to "hack" core to revert this.

**Comment by csthomas** [comment]
Proposed solution at https://github.com/joomla/joomla-cms/pull/23278

**Pull request merged**
