### PR TITLE
[4.0] Remove element selector that does not exist

### PR DESCRIPTION
**Pull request by roland-d**
### Summary of Changes
Closing the batch modal in Tags causes a JavaScript error due to trying to access a non-existing element. Looks like a case of copy/paste because there is of course no Tag selector in the batch modal on the Tags page.

### Testing Instructions
1. Open the developer Console with F12
2. Open the console tab in the developer console
image

3. Go to Components -> Tags
4. Check 1 or more tags (if you have none, create one)
5. Click on the Batch button
6. Click on the Cancel button
7. Notice in the console a JavaScript error
image

8. Apply patch
9. Reload page
10. Click on the Batch button
11. Click on the Cancel button
12. Notice in the console there is no JavaScript error

### Expected result
No JavaScript error

### Actual result
A JavaScript error

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
not saying this is wrong as i havent tested it but it is the same in j3

**Comment by roland-d** [comment]
@brianteeman Correct, same issue exists there. The JS is trying to target the Tags option in the modal but it doesn't exist in the Tags view for obvious reasons. You can see it in the modal at Contacts for example:
image

That is the element it tries to access.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a4cda0999ce5af0cf00a8c955172f2190714bbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25059">issues.joomla.org/tracker/joomla-cms/25059</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3a4cda0999ce5af0cf00a8c955172f2190714bbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25059">issues.joomla.org/tracker/joomla-cms/25059</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
