### PR TITLE
Fixed mobile menu dropdown

### PR DESCRIPTION
**Pull request by C-Lodder**
see: https://github.com/joomla/joomla-cms/issues/5912

On smaller devices, the mobile menu toggle seems to be acting oddly.

**1st click** = menu slide down
**2nd click** = menu slide up
**3rd click** = menu slide down
**4th click** = Nothing happens

No errors are appearing in the console log when it stops working.

Tested on Firefox (latest stable, developer and beta) and Chrome (latest).

mobile-menu

I've started trying to debug the issue and will submit a pull request if I find a solution

### CODE REVIEW

**Comment by zero-24** [comment]
@C-Lodder can you also add the fix to the less file?

See: https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/less/template.less#L699-701

**Comment by C-Lodder** [comment]
@zero-24 - My bad, completely forgot about the less file. PR has been updated :)

**Comment by brianteeman** [comment]
@test works for me - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5913">issues.joomla.org/joomla-cms/5913</a>.</sub>

**Comment by brianteeman** [comment]
Correction - this breaks the desktop

http://i.tee.mn/6juh.png<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5913">issues.joomla.org/joomla-cms/5913</a>.</sub>

**Comment by C-Lodder** [comment]
@brianteeman - Re-fixed this for larger screens. Now the height: auto is only applied to screen widths >= 768. Not sure what on earth is up with the styling for your filter when it should be on the left hand side but I don't get that at all.

**Comment by zero-24** [comment]
@C-Lodder github see some `merge conflicts` can you have a look into it?

**Comment by C-Lodder** [comment]
@zero-24 - I was not able to see any conflicts until I tried merging my mobile-menu branch with my staging branch. I've fixed the conflict so shall I submit a PR from my staging branch? Sorry about the confusion, I'm not used to PR's and merging.

**Comment by zero-24** [comment]
@C-Lodder i think the easiest would be to do a new PR. But maybe someone with more git fu than me can help you to fix the conflicts.

**Comment by C-Lodder** [comment]
@zero-24 - Not to worry. I will submit a new PR and reference it. If you can decline this one, I'll re-submit my new one tomorrow morning :)

**Comment by zero-24** [comment]
:+1: Thanks!

**Comment by brianteeman** [comment]
Closed see #5924 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5913">issues.joomla.org/joomla-cms/5913</a>.</sub>

**Pull request closed without merging**
