### PR TITLE
Added drone.io ci-server for running JavaScript tests

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

This PR adds a .drone.yml (similar to travis.yml) to integrate Joomla's drone.io continuous integration server. Currently only the JavaScript tests are run.
### Testing Instructions

Review drone.io log
### Documentation Changes Required

None

screenshot 2016-08-29 20 36 38

screenshot 2016-08-29 20 37 41

// cc @rdeutz

### CODE REVIEW

**Comment by piotr-cz** [comment]
What is the point of adding another test server?

**Comment by yvesh** [comment]
@piotr-cz There are multiple advantages with drone.io:

* Travis sometimes has issues / breaks. With automated browser tests (system tests) as they are planed even more (got worse the last moths, almost 1 out of 5 tests are failing currently for weblinks)
* Drone is self hosted, so you can do all the nasty stuff you can't do (not really) with Travis. Making screenshots, videos, sharing files, secret data like API tokens.. And you can use your **own docker images**..
* It's faster. The image above is not even adjusted to node / npm yet. You don't require to install anything, because you build your image yourself. And drone has caching features for downloaded files (npm / composer folder etc.)
* Drone like travis has build matrix support, but way more possibilities as you directly use docker
* Deployment support, Notifications like IRC (#joomla), Slack, Mail

And just for the record: That PR is mostly for testing how drone.io performs in comparison with Travis.

**Comment by mbabker** [comment]
Before this is merged, the Drone instance should REALLY be part of Joomla's hosting platform and not some individual's third party system.  http://82.165.166.30/joomla/joomla-cms

That said, we've already got a CI server running for the project by way of [Jenkins](http://build.joomla.org/) so what benefit is there running this in parallel to or replacing that?

We should be standardizing on ONE platform for all of the tools/repos, and not just for the automated test systems.  So far there are at least three CI platforms being used just between the CMS and Weblinks now, two of them falling into the self-hosted category, and at least 4 or 5 different packaging and filesystem organization structures.

**Comment by yvesh** [comment]
@mbabker That is a Joomla server. I posted some ups for drone above.

**Comment by rdeutz** [comment]
I am going to merge this for the purpose to get some realistic statistics and look what we need as a setup for core testing

**Comment by rdeutz** [comment]
It is a server the automated testing team got for free form a big german hosting provider

**Comment by rdeutz** [comment]
forget to say, it is just for a period of time, if we have what we need we will remove it

**Pull request merged**
