### PR TITLE
[5.2] Pre-update check for extensions AllowDynamicProperties

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #44284 .

### Summary of Changes
added #[\AllowDynamicProperties]

### Testing Instructions
see  #44284 .

### Actual result BEFORE applying this Pull Request
deprecation 

### Expected result AFTER applying this Pull Request
no more derepcation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Hackwar** [comment]
Please add the necessary attributes instead of hiding the error with this code.

**Comment by alikon** [comment]
the only way I was able to reproduce the issue, has been to add a non standard "_tag_" `<updatefromcli>false</updatefromcli>` in the updateserver xml file

so we don't know the exact non standard tags that are defined in the updateserver xml file of the extensions for @obuisard  it was `<length></leght>`  i suspect,  so to avoid errors  the  #[\AllowDynamicProperties] could be a good solution imho

**Comment by richard67** [comment]
@obuisard Does this PR close your issue?

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on fa35b859821dd10015731ac75bdcf8210df86794<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44307">issues.joomla.org/tracker/joomla-cms/44307</a>.</sub>

**Comment by obuisard** [comment]
> @obuisard Does this PR close your issue?

Yes, all good with it!
Thank you Nicola @alikon

**Review by rdeutz — APPROVED** [review]

**Comment by Hackwar** [comment]
With the review of @rdeutz and the test of @obuisard I'm declaring this as RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44307">issues.joomla.org/tracker/joomla-cms/44307</a>.</sub>

**Pull request merged**
