### PR TITLE
Cassiopeia chart/map

### PR DESCRIPTION
**Pull request by rgmears**
Add this (or some similar) image to the template description page.
cassiopeia-small

### CODE REVIEW

**Comment by brianteeman** [comment]
Something very wrong with this pr.

**Comment by rgmears** [comment]
Yeah, I know. Didn't realize it was so tricky to do.

**Comment by C-Lodder** [comment]
@rgmears - You're trying to merge staging into 4.0-dev.

Please refer to the Github docs on how to fork a repo, create a branch, and submit a PR

Also remember to add `[4.0]` at the beginning of the title if you're submitting PR's for Joomla 4

**Comment by ciar4n** [comment]
You might also want to hold off on this depending on if #19062 gets merged.

**Comment by rgmears** [comment]
Seems a PR is the wrong place for this. Sorry @C-Lodder.

**Comment by rgmears** [comment]
@ciar4n it's mostly a suggestion at this point. It would help end-users a lot to have a simple chart to refer to as to where elements display.

**Pull request closed without merging**
