### PR TITLE
[html5] Hathor administrator template

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This is a redo of https://github.com/joomla/joomla-cms/pull/9842 for hathor only.

This PR does a basic conversion of **hathor** template to HTML5.
Also made some minor corrections:
- Use script/style version for template js/css
- Use the API in inline JS/CSS (except in error pages)
- Use html5.js for browser lower than IE9 in all files.
#### Testing Instructions
1. Install patch
2. Set the admin tempalte as "Hathor"
3. Go to admin and check if the the following pages are working properly:
   - normal page (test any existent URL)
   - component popup (add `&tmpl=component&print=1` to an existent page)
   - error pages (test one non existent URL)
   - login (logoff and check the login page)

Check also the code changes.
#### Observations

All pages should now start with this code:

``` html
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">
<head>
[...]
    <meta charset="utf-8" />
[...]
```

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
please don't test yet. need to check some things.

**Comment by andrepereiradasilva** [comment]
ok done

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 2bffcc0bd6454647dd151f0fe312027d607da180<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10634">issues.joomla.org/joomla-cms/10634</a>.</sub>

**Comment by AnishaVora** [comment]
I have tested this item :white_check_mark: successfully on 2bffcc0bd6454647dd151f0fe312027d607da180<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10634">issues.joomla.org/joomla-cms/10634</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10634">issues.joomla.org/joomla-cms/10634</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/d7a776f46a6ef95887e4399996c5fea5b85f819d

**Pull request closed without merging**
