### PR TITLE
[4.0] Fix injection of webcomponents JS

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR fixes the console error being produced in J4:

> document.head.insertAdjacentElement is not a function

### CODE REVIEW

**Comment by dgrammatiko** [comment]
According to MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement
this function exists even in IE8 so `document.head.insertAdjacentElement('beforeend', newScript);` is fine!

**Comment by dgrammatiko** [comment]
also http://caniuse.com/#feat=insert-adjacent

@C-Lodder can you share the actual console.log?

**Comment by dgt41** [comment]
Use this: ` newScript.insertAdjacentElement('beforeend', document.head);`

**Comment by C-Lodder** [comment]
@dgt41 - I posted the error in my initial comment. It's coming from line 989 of core.js

**Comment by dgrammatiko** [comment]
@C-Lodder check your error and the function name, there are not the same! one is `insertAdjacentElement` and you have an error on a function `insertAdjacentHTML`, so the error is not in this line

**Comment by dgrammatiko** [comment]
Also which browser gives this error?

**Comment by C-Lodder** [comment]
ah sorry, it was `insertAdjacentElement`, not `insertAdjacentHtml`

**Comment by dgrammatiko** [comment]
never mind, @wilsonge you can merge this, it's the same functionality

**Comment by dgrammatiko** [comment]
@C-Lodder just for the record which browser gave this error? I am using this function in coupe CEs

**Comment by C-Lodder** [comment]
Firefox

**Comment by dgrammatiko** [comment]
I can't replicate it in none of Firefox stable, Firefox Developer edition and Firefox Nightly

**Pull request merged**
