### PR TITLE
[4.0] Fix saving items without creation date

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31046.

### Summary of Changes

Fixes saving content without creation date.

### Testing Instructions

Edit an article/contact/banner/category/newsfeed/custom field/custom field group/smart search filter.
Remove value from `Created Date` field.
Save.

### Actual result BEFORE applying this Pull Request

An error like this:

>Save failed with the following error: Incorrect datetime value: '' for column 'created_time' at row 1

### Expected result AFTER applying this Pull Request

Item saved and `Created Date` field populated with current date.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 64e3d461b6147c121da8de394781eab09233769d

Fail on Contacts.

**Successfully test on:**
- Article
- Articles: categories
- Articles: custom field 
- Articles: custom field group
- Banners
- Banners: categories
- Contacts: categories
- News Feeds: feeds
- News Feeds: category
- Smart search: filters

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31273">issues.joomla.org/tracker/joomla-cms/31273</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test with contacts again.

**Comment by richard67** [comment]
@SharkyKZ ~~It seems Drone is failing with composer install. Can if be that your composer.lock is modified somehow our out of date? If not, ping me, then we have to check if these is something wrong with the testing environment.~~

Update 2020-11-01: Meanwhile it's clear that it was a problem with testing environment. Re-started drone to see if it passes now.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cfd2780b268f2e8c6007d466d285b0136263306c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31273">issues.joomla.org/tracker/joomla-cms/31273</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on cfd2780b268f2e8c6007d466d285b0136263306c<br /><br />Tested successfullky in Beta6-dev of 30 October.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31273">issues.joomla.org/tracker/joomla-cms/31273</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31273">issues.joomla.org/tracker/joomla-cms/31273</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
