### PR TITLE
Note on the User Registration menu item

### PR DESCRIPTION
**Pull request by webuniverse**
If the user registration is not active, the menu item redirects to the login form. No message appears why the registration form is not displayed.

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 38602cbae6928ef81d69204a47051538ecad09e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38734">issues.joomla.org/tracker/joomla-cms/38734</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 38602cbae6928ef81d69204a47051538ecad09e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38734">issues.joomla.org/tracker/joomla-cms/38734</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38734">issues.joomla.org/tracker/joomla-cms/38734</a>.</sub>

**Comment by laoneo** [comment]
Thanks for your first pr!!

**Pull request merged**
