### PR TITLE
[postgreSql] Remove extra 'n' in sample data

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for new Issue.
#### Summary of Changes

Extra 'n' in sample data install on postgresql
#### Testing Instructions

Obvious. For me is a direct merged by review.
But ok, very simple code review.
#### Documentation Changes Required

None
#### Notes

Found by @jreys in GsoC multilingual project.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11532">issues.joomla.org/joomla-cms/11532</a>.</sub>

**Comment by jreys** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11532">issues.joomla.org/joomla-cms/11532</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11532">issues.joomla.org/joomla-cms/11532</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on d1e7ea3c41b89eb6ffe32eac61637e1587a5adfd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11532">issues.joomla.org/joomla-cms/11532</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d1e7ea3c41b89eb6ffe32eac61637e1587a5adfd<br /><br />just to make travis happy<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11532">issues.joomla.org/joomla-cms/11532</a>.</sub>

**Pull request merged**
