### PR TITLE
[4.0] Fix filters in com_menus

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25160.

### Summary of Changes

Fixes filters in `com_menus`.

### Testing Instructions

In administrator, go to Menus -> Main Menu.
Select a filter under `Filter Options`.

### Expected result

Selected filter applied.

### Actual result

Filter not applied.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
Looks like it does not solve all.
The Filter Options do change OK  and it works (as far as I tested) for all menu items except that System Links do not display the correct Status Icon.
Both System LInks menu items below are Published.

Screen Shot 2019-06-12 at 09 44 52

**Comment by SharkyKZ** [comment]
@infograf768 issue not related to this PR. See #24721.

**Comment by infograf768** [comment]
LOL. I had forgotten that one...

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9cafb7a576a3c346b21fbad4534d1fdd7d22f83a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25181">issues.joomla.org/tracker/joomla-cms/25181</a>.</sub>

**Comment by infograf768** [comment]
@SharkyKZ 
Please test https://github.com/joomla/joomla-cms/pull/25185 for the System Links (and more) issue.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9cafb7a576a3c346b21fbad4534d1fdd7d22f83a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25181">issues.joomla.org/tracker/joomla-cms/25181</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25181">issues.joomla.org/tracker/joomla-cms/25181</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
