### PR TITLE
[4.0] Menu duplicate fields

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #34128 .

### Before
image

### After
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 85bc5b0a7eebe24da9e482f13506fa448e9ba45b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34136">issues.joomla.org/tracker/joomla-cms/34136</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 85bc5b0a7eebe24da9e482f13506fa448e9ba45b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34136">issues.joomla.org/tracker/joomla-cms/34136</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34136">issues.joomla.org/tracker/joomla-cms/34136</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks.

**Pull request merged**
