### PR TITLE
Update readme to link to Launch instead of Demo

### PR DESCRIPTION
**Pull request by jeckodevelopment**
### Summary of Changes
Link in the Readme to demo.joomla.org has been updated to launch.joomla.org

### Testing Instructions
None

### Documentation Changes Required
None

### CODE REVIEW

**Review by brianteeman — COMMENTED** [review]
I wouldn't call it a demo anymore.

**Comment by jeckodevelopment** [comment]
I had the same feeling...

**Comment by jeckodevelopment** [comment]
@brianteeman better now?

**Review by brianteeman — APPROVED** [review]
approve language change

**Comment by jeckodevelopment** [comment]
AppVeyor failure should not be linked to this PR

**Comment by jeckodevelopment** [comment]
AppVeyor failure should not be related to this PR

**Comment by mbabker** [comment]
> AppVeyor failure should not be related to this PR

You'd be surprised how often that's the case.

**Comment by brianteeman** [comment]
Some of us are not surprised at all but the testing team don't seem to care about it at all ;(

**Comment by jeckodevelopment** [comment]
> You'd be surprised how often that's the case.

I saw similar cases already several times. I guess that the current limitation on concurrent jobs slows up things.

**Comment by brianteeman** [comment]
Unrelated to that
 That would be too easy an answer.

**Pull request merged**
