### PR TITLE
[5.1] CLI: Renaming and improving output of core:update:check

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The commands for core updates are not consistent right now. This is a first attempt at getting a system into these commands and improving the output. This PR renames the `core:check-updates` command to `core:update:check` (and adds an alias to keep it backwards compatible) and extends the output to display the current Joomla version and the update channel we are currently on.

An additional command `core:update:set-channel` will allow to set the update channel in the future.

### Testing Instructions
1. call `php cli/joomla.php`
2. call `php cli/joomla.php core:update:check`
3. call `php cli/joomla.php core:check-updates`

### Actual result BEFORE applying this Pull Request
to 1.: See the command listed as `core:check-updates`
to 2.: See the command fail
to 3.: See the title "Joomla updates" and the text "You already have the latest Joomla version..."

### Expected result AFTER applying this Pull Request
to 1.: See the command listed as `core:update:check` and with an alias of `core:check-updates`
to 2.: See the command go through successfully with the title "Joomla Update Status" and the currently selected update channel and the  current Joomla version in addition to the next available version.
to 3.: See the command to also work successfully, like in 2.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on fcc5429799699875f26adc7fa1f9b645c4420b2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42594">issues.joomla.org/tracker/joomla-cms/42594</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on fcc5429799699875f26adc7fa1f9b645c4420b2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42594">issues.joomla.org/tracker/joomla-cms/42594</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42594">issues.joomla.org/tracker/joomla-cms/42594</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
