### PR TITLE
[4.0] No jquery, custom fields

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Eliminates jQuery
- Removes the inline JS from the helper file, puts it in the layout

### Testing Instructions
- Make sure that custom fields are enabled, you have a custom field, etc
- Create an article and switch categories (one that has custom fields to one that doesn't and the other way around)

### Documentation Changes Required
No code clean up, enforce best practices, eg scripts only on the layouts!!!

### CODE REVIEW

**Comment by bembelimen** [comment]
Hi @dgrammatiko thank you for this PR, that's exactly where I tinkered around the last hours, but one suggestion: perhaps we could do this "reload" custom field independent in some way, (at least the naming of the parameter), because I would like to use this new function with the workflow.

**Comment by dgrammatiko** [comment]
@bembelimen you mean `Joomla.categoryHasChanged(..)` this one? This is an inline script available only in the edit views that have a category field.
Anyways what is you requirements for the workflow? Let me know what are your requirements so I could try to make this a more abstract method and maybe make it globally available (?)

**Comment by bembelimen** [comment]
The idea is nearly the same as custom fields.
At the moment when creating a new article there is no "state" field visible. I would like to show it again + the first transitions (so one can e.g. with the default workflow publish/unpublish a new article without saving twice). But every category could have their own workflow, so it has to change when changing the category.
I just need exactly the same what custom field does: relaod content and adjust the state field.
So my idea way a more generic approach (in fact what you implemented here), with a parameter, which allows me to activate this reload function when changing the category.
So codewise I think there is no changes required, it's more the naming (looks a bit strange, when the workflow activates a CF-function)

**Comment by dgrammatiko** [comment]
> which allows me to activate this reload function when changing the category.

This is fired on category change so you don't have to call it from the workflow js... Or do I miss something?

**Comment by bembelimen** [comment]
Yes, that's clear.
Just to make it short: this function should be activatable from everywhere and from every extension, not only CF (which is now the case), so my suggestion was just: rename the parameters to be CF independent. (```custom-fields-enabled```)

**Comment by dgrammatiko** [comment]
@bembelimen so the method:
```js
  Joomla.categoryHasChanged = function (el) {
	    if (el.value == el.getAttribute('data-cat-id')) {
	      return;
	    }
	
	    Joomla.loadingLayer('show');
	    document.body.appendChild(document.createElement('joomla-core-loader'));
	    document.querySelector('input[name=task]').value = el.getAttribute('data-section') + '.reload';
	    element.form.submit();
	  };
```

Basically has only this line: `document.querySelector('input[name=task]').value = el.getAttribute('data-section') + '.reload';` that is specific to custom fields. I guess I can replace it with a callback to be more abstract. Only problem with the callback is that you can have only one. The other option is to dispatch an event so you can have multiple methods run at the event. Only draw back of the event is that is async so the form.submit() will have to go also form this method. If you can share some dummy code that workflows need to run here I could shape this...

**Comment by bembelimen** [comment]
Yes, this is the only line, which could be lead to a conflict.

To be honest, I have no code yet, I would just do, what you did here:

``` PHP
$form->setFieldAttribute('catid', 'custom-fields-enabled', true);
$form->setFieldAttribute('catid', 'custom-fields-cat-id', $assignedCatids);
$form->setFieldAttribute('catid', 'custom-fields-form-id', $form->getFormControl());
$form->setFieldAttribute('catid', 'custom-fields-section', $section);
```
And then manipulate over the loadForm-Hooks in the Model. As said before, I don't need "more" than this...and it would work like it is at the moment for me...but a more generic naming would be nice + the line mentioned by you could lead to problems (probably)

**Comment by dgrammatiko** [comment]
@bembelimen ok I think you can easily plugin any needed functionality through either the data attributes (my approach here) or using the document->addScriptOptions().
Anyways for the time being the reload will also work for the forms without custom fields. The only part I guess you need to patch is to set in javascript whatever you need to re collect in the PHP on the form post.
Let me know if there is something more you need here

**Comment by bembelimen** [comment]
I would just suggest to rename the parameters to be CF-independent:

``` PHP
$data['enabledRelaod']   = (boolean) $this->element['reload-enabled'];
$data['catId']       = (string) $this->element['reload-cat-id'];
$data['formId']      = (string) $this->element['reload-form-id'];
$data['section']     = (string) $this->element['reload-section'];
```

**Comment by dgrammatiko** [comment]
@bembelimen better?

**Comment by bembelimen** [comment]
Worse :D the idea was to NOT use custom fields naming, but anyways, let it like it is, I'll use your naming.

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 3d2680e319a073e70ff7c0a0ebe733be5f0cc4d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23414">issues.joomla.org/tracker/joomla-cms/23414</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 3d2680e319a073e70ff7c0a0ebe733be5f0cc4d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23414">issues.joomla.org/tracker/joomla-cms/23414</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23414">issues.joomla.org/tracker/joomla-cms/23414</a>.</sub>

**Comment by dgrammatiko** [comment]
@wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
