### PR TITLE
[4.0] Use setDocumentTitle for com_users

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This simple PR makes use the existing method setDocumentTitle to set browser page title for com_users views to avoid repeating code.

### Testing Instructions
1. Apply patch
2. Access to User Registration Page, Forgot username, forgot password page, user profile page (by create menu items or access to the links from login module), make sure these pages still being displayed OK.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on a005782502dbe2eaf24dcac8a628b575b23d3229<br /><br />Tested successfully in Beta8-dev of 21 February in Wampserver 3.2.4 using Apache 2.4.46c, MySQL 8.0.23, PHP 8.0.2 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32482">issues.joomla.org/tracker/joomla-cms/32482</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on a005782502dbe2eaf24dcac8a628b575b23d3229<br /><br />Pages were still visible after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32482">issues.joomla.org/tracker/joomla-cms/32482</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32482">issues.joomla.org/tracker/joomla-cms/32482</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
