### PR TITLE
[4.0] user note status

### PR DESCRIPTION
**Pull request by brianteeman**
Make sure that the status field has the correct class. ie green when published and red when unpublished

Pull Request for Issue #34193

### CODE REVIEW

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on dacedea1de2073471b1abcb8b86b2be21dbf8a8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34194">issues.joomla.org/tracker/joomla-cms/34194</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on dacedea1de2073471b1abcb8b86b2be21dbf8a8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34194">issues.joomla.org/tracker/joomla-cms/34194</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34194">issues.joomla.org/tracker/joomla-cms/34194</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
