### PR TITLE
Set default value for data attribute in updater

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #14471

### Summary of Changes

If not set we set the data attribute to '' vs NULL.

### Testing Instructions

- Install 4.0
- go to the options and set this: https://update.joomla.org/core/nightlies/next_major_list.xml as your custom update URL
- apply this patch
- We got the `Expected result`

### Expected result

Joomla find the update to 4.0.0-dev2 and allow a update to the last nightly version

### Actual result

Joomla don't find any update.

### Documentation Changes Required

None

### Additional Information

This PR is vs staging as the code should also be there as it fixes a issue also present in staging. And staging is goint to be synced to 4.0-dev.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
PR applied, go to `index.php?option=com_joomlaupdate` get:
bildschirmfoto 2017-03-12 um 21 21 48

**Comment by zero-24** [comment]
@franz-wohlkoenig this was a typo wich i have fixed here: https://github.com/joomla/joomla-cms/pull/14540/commits/3cbf83a900f2bf1f33558e86214569bdbb0d426d

**Comment by franz-wohlkoenig** [comment]
After click on `Install the Update`-Button:
bildschirmfoto 2017-03-13 um 07 13 15

**Comment by csthomas** [comment]
A little related to #14321

I never know, do we should use method `$table->check()` for that?

**Comment by zero-24** [comment]
Closing as there is a more complete PR at #14321 Thanks @csthomas

**Pull request closed without merging**
