### PR TITLE
Bootstrapization of warning panels in com_installer

### PR DESCRIPTION
**Pull request by peterlose**
## Before PR

skaermbillede 2015-02-26 kl 19 47 53
## After PR

skaermbillede 2015-02-26 kl 19 48 05

### CODE REVIEW

**Comment by n9iels** [comment]
@test works fine! :-)
Please add some code style and remove empty lines

**Comment by losedk** [comment]
@n9iels is it better now?

**Comment by C-Lodder** [comment]
Nice one.

Just a thought. Would it not be better to use Bootstrap alert boxes instead of an accordion?

**Comment by zero-24** [comment]
@losedk i have just add a CS PR against your repo ;) looks cool :smile:

**Comment by losedk** [comment]
@zero-24 thanks alot! Merged :)

**Comment by zero-24** [comment]
@losedk just tested:

`Notice: Undefined variable: i in JRoot/administrator/components/com_installer/views/warnings/tmpl/default.php on line 30`

I don't know why we need the $i there?

**Comment by n9iels** [comment]
$i is not defined, it can be removed over here

**Comment by losedk** [comment]
@zero-24 fixed now. Could you test again?

**Comment by zero-24** [comment]
@test @losedk works good here. Thanks! One more tester here :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6200">issues.joomla.org/joomla-cms/6200</a>.</sub>

**Comment by losedk** [comment]
@n9iels Could you test again?

**Comment by n9iels** [comment]
@test works fine for me, thanks!
Two tests, moving to RTC!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6200">issues.joomla.org/joomla-cms/6200</a>.</sub>

**Comment by nonumber** [comment]
@losedk If you can/want: please also do this for the other admin components. Pretty much all of them use the old ```sliders.panel``` somewhere. These should all be converted to the bootstrap methods.

**Comment by losedk** [comment]
@nonumber can't seem to find others than in Hathor

**Comment by nonumber** [comment]
You are correct. My mistake.

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
