### PR TITLE
Updated XML installation file for 3.6.1

### PR DESCRIPTION
**Pull request by yild**
#### Summary of Changes

Updated xml installation pl-PL language file with version, creationdate and name for J3.6.1.
#### Testing Instructions

Simple code verification.

### CODE REVIEW

**Comment by infograf768** [comment]
Polish (Polska) would be fine. No need to add anything else. 
Main part of the name should be in English for the installation xml files.

**Comment by yild** [comment]
ok, done

**Comment by infograf768** [comment]
Please read https://github.com/joomla/joomla-cms/pull/11408#issuecomment-237190882 and contact Stefan asap.

@Bakual
See private forum

**Comment by Bakual** [comment]
I'm closing this PR as I have merged the files provided in the forum.
See https://github.com/joomla/joomla-cms/commit/af8f341b1150d582b4d3cc891fcfecf9dbd0ab65

**Pull request closed without merging**
