### PR TITLE
[4.0] Removing legacy module chromes

### PR DESCRIPTION
**Pull request by Hackwar**
I would like to clean up some of the module chromes that we have in our codebase. If you look at these 2 chromes, I couldn't think of a reason to keep modChrome_horz. Something like this should be done in CSS and not by throwing yet another table at it.

Likewise with modChrome_rounded. There is border-radius which is a lot better at doing something like this.

Yes, this is a B/C break, but in favour of quality of the resulting websites, I would still do this. Looking forward to your comments. :smile:

### CODE REVIEW

**Comment by C-Lodder** [comment]
What about `xhtml`?

**Comment by wilsonge** [comment]
Yup agree with @C-Lodder let get rid of the XHTML one too. There's instructions already there on how to migrate to HTML5 one in j3 (https://github.com/joomla/joomla-cms/blob/staging/templates/system/html/modules.php#L85-L88)

**Comment by HLeithner** [comment]
what happend to the plan to move module chrome to layouts?

**Comment by wilsonge** [comment]
Not merged yet - but I still plan on doing https://github.com/joomla/joomla-cms/pull/23570 - but removing the old ones here doesn't really affect that change

**Comment by Hackwar** [comment]
What is the difference between xhtml and html5? On a quick glance, they look identical?

Regarding switching the chromes to layouts as in #23570, I'm not really happy with that PR, but that is mainly related to me not being happy with the layout system in general.

Are we fine with the B/C break? Then I would indeed delete the xhtml chrome, too.

**Comment by wilsonge** [comment]
Yup i'm happy. Kill it

**Comment by wilsonge** [comment]
Technically there is a difference - the xhtml chrome doesn't have a space between the moduletable class and the suffix whereas html5 does

**Comment by Hackwar** [comment]
done

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
