### PR TITLE
Feature/40545 remove inline padding on highlight search words

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/40545

### Summary of Changes

The issue was caused by merging code changes on highlight.js in PR https://github.com/joomla/joomla-cms/pull/38908 solving 
This PR will revert those changes and solve the initial issue https://github.com/joomla/joomla-cms/issues/38903
Issue solved by reset inline padding on the search words by overriding Bootstrap variable `$mark-padding`

### Testing Instructions

Follow testing instruction as described by both issues #40545 and #38903

After applying the patch the command `npm run build` should be executed to regenerate both js and css files. 

### Actual result BEFORE applying this Pull Request

- Search word `Administrator` will not be highlighted when it is followed by a dot or comma.
- Search word `Foo Bar FooBar` will be highligted

### Expected result AFTER applying this Pull Request

- Search word `Administrator` will be highligted
- Search word `Foo Bar FooBar` will be highligted

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by iqrafarah** [comment]
I have tested this item :white_check_mark: successfully on 2fdb99464833b3c876b6b47a5fe725ccb69ed4c8<br /><br />I have tested this and everything seems to work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40576">issues.joomla.org/tracker/joomla-cms/40576</a>.</sub>

**Comment by richard67** [comment]
@hans2103 It looks as if this PR also contains the changes from your other PR #40574 .

**Comment by hans2103** [comment]
> @hans2103 It looks as if this PR also contains the changes from your other PR #40574 .

oh boy... solved by reverting those changes

**Comment by richard67** [comment]
> > @hans2103 It looks as if this PR also contains the changes from your other PR #40574 .
> 
> @richard67 oh boy... solved by reverting those changes

Yep, looks ok now.

@iqrafarah Could you test again? Thanks in advance.

**Comment by Jurre279** [comment]
I have tested this item :white_check_mark: successfully on 3c7ea4a485af7b4755f2fd3753532084f19f62d5<br /><br />Tested this and it seems to work. Tested this on google chrome<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40576">issues.joomla.org/tracker/joomla-cms/40576</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40576">issues.joomla.org/tracker/joomla-cms/40576</a>.</sub>

**Comment by obuisard** [comment]
Thanks Hans @hans2103 for the PR!

**Pull request merged**
