### PR TITLE
Move JPlugin to namespace

### PR DESCRIPTION
**Pull request by laoneo**
Move JPlugin to namespace. I would not name JPlugin just Plugin, so I named it CMSPlugin, any other name recommendation?

### CODE REVIEW

**Comment by yvesh** [comment]
@laoneo now with upper case CMS? we are really inconsistent between CMS and Cms ..

Personally i would name it Plugin :-)

**Comment by brianteeman** [comment]
> we are really inconsistent between CMS and Cms ..

Are we? We should be consistent with CMS

**Comment by yvesh** [comment]
@brianteeman JApplicationCms, CmsApplication, ConfigViewCmsHtml, CmsEvent - i think i can come up with more if i would search..

**Comment by mbabker** [comment]
The CamelCase names are required if using JLoader.  For the namespaced stuff it should be consistently uppercase by now.

**Comment by brianteeman** [comment]
That's what I meant

**Pull request merged**
