### PR TITLE
Update  robots.txt intro text

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to improve the grammar of the intro text in robots.txt and to math the style guide.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e7674eb7e7fd0821f6f08f664599aa92f9e07099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10778">issues.joomla.org/joomla-cms/10778</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on e7674eb7e7fd0821f6f08f664599aa92f9e07099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10778">issues.joomla.org/joomla-cms/10778</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10778">issues.joomla.org/joomla-cms/10778</a>.</sub>

**Comment by wojsmol** [comment]
@joomla-cms-bot Please remove RTC label as this PR is merged :smile:

**Pull request merged**
