### PR TITLE
[4.0] Allow to a switcher and validate assets to be overridable

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

A little fix, to keep these 2 assets overridable to avoid problems similar to #27024

### Testing Instructions
Apply patch, run `npm install`

Check the form validation and switcher styling.

### Expected result
All works

### Actual result
All works

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on dfa1ff99d2d79fd9633a1aa20fce6c86adda905d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27417">issues.joomla.org/tracker/joomla-cms/27417</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on dfa1ff99d2d79fd9633a1aa20fce6c86adda905d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27417">issues.joomla.org/tracker/joomla-cms/27417</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27417">issues.joomla.org/tracker/joomla-cms/27417</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
