### PR TITLE
Prevent create categories in first level if user is not allowed

### PR DESCRIPTION
**Pull request by n9iels**
This PR will fix a part of the issues described in #8069 
## The issue

A user with ACL right to create, delete, edit, edit State, edit own in a specified category can also create new categories on the first level. (no parent)
## How to test
1. Create a usergroup with registered as parent
2. Select that group in the "Special" view/access level
3. In Global configuration, allow Administrator Login for this group
4. In the Global options of Articles, Categories and Featured Articles set "Access Administrator interface" to <i>Allowd</i> for that group
5. Create a new category and set the permissions of hat categories for the new user group for the following item on <i>allowed</i>:
   - Create
   - Delete
   - Edit
   - Edit state
   - Edit Own
6. Create a new user for the created user group
7. Login with the user on the back-end
8. Click on the create button and notice you can create a category for "no parent"
9. Apply patch, and notice you can't create categories for "no parent" any more
## Note

Can someone please review if this is a good solution? I know it solves the issue, but I don't know exactly why that piece of code was placed

### CODE REVIEW

**Comment by zero-24** [comment]
@n9iels that code was added here by @sanderpotjer see https://github.com/joomla/joomla-cms/pull/3401<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by n9iels** [comment]
@zero-24 thanks, I couldn't find that.

Difficult situation, the solution of that bug cause this one.
So we have to find a solution that makes sure that:
- Level 0 will not unset if the the parameter "Create" is set on allowed in: Article -> Permissions
- Level 0 will unset in other situations (assuming that creating categories on level 0 is only allowed when you have full create access)

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on 4f5004631c7061c331289e940f5cc0ae874abebf<br /><br />Works as expected ... Prevents users creating Categories outside of the hierarchy of the Category they have Edit Permission for<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on 4f5004631c7061c331289e940f5cc0ae874abebf<br /><br />Works as expected ... Prevents users creating Categories outside of the hierarchy of the Category they have Edit Permission for<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by n9iels** [comment]
@Webdongle Thanks for testing! But it seems like the solution for this issue is not ready yet. Please test again when we have good solution :)

**Comment by Webdongle** [comment]
OK ... as soon as I get the email will test it

**Comment by designbengel** [comment]
I can´t access anything to create content (before applying the patch)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by roland-d** [comment]
Hello @n9iels 

Thank you for your contribution.

The last comment here was on 24th October 2015. So the question is, Is this issue/pull request still valid? 
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by roland-d** [comment]
No need for PLT to decide here yet. I have contacted Niels and asked him to update this issue. Let's wait a bit longer before closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8083">issues.joomla.org/joomla-cms/8083</a>.</sub>

**Comment by n9iels** [comment]
Ignore the commit, there is on this moment no solution for this problem. Because the `- no parent - ` (level 0) has no access right. So `$user->authorise()` can't determine if the current has is allowed to edit this level.

I close this PR now.

**Pull request closed without merging**
