### PR TITLE
Update MailTemplate.php

### PR DESCRIPTION
**Pull request by rigin**
The method does not bind the template to the extension. And I propose to correct this omission.

Pull Request for Issue # .

### Summary of Changes

When using this method, the 'extension' field remains empty and, accordingly, the template is not visible in the list of templates.
I added a parameter to insert it.If it is not used, then the 'extension' field is filled with the contents of the 'name' field before the '.' separator.

### CODE REVIEW

**Comment by richard67** [comment]
@rigin Does this PR here replace your PR #37898 from 6 days ago? If so, why haven't you closed it?

**Comment by rigin** [comment]
This is a change in another class method.

They can be considered in parallel.

 

  _____

**Comment by HLeithner** [comment]
This pull requests has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by obuisard** [comment]
In light of https://github.com/joomla/joomla-cms/pull/39540 being merged in 4.3, is this still necessary to do? Updating a mail template should not change the extension value associated with that mail template.
Vadim @rigin, can this be closed? Thank you!

**Comment by Quy** [comment]
Thank you for your contribution. Closing for stated reason.

**Pull request closed without merging**
