### PR TITLE
Chosen updated to v1.3.0, Ajax-Chosen updated to version 0.2.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Chosen seemed to be way out of date so here's a new one.
Why so many changed files? Well, it seems that chosen has decided to change their prefixes from `liszt:` and `chzn-` to simply `chosen:` and `chosen-`. It makes more sense but it does break everything I guess.

### CODE REVIEW

**Comment by Fedik** [comment]
year ago here was talk that we cannot do upgrade it more, because new Chosen have b/c problem, eg: new class names, new events names ...
and for future would prefer drop it in favor Select2

**Comment by wilsonge** [comment]
Yeah we had to take a decision to not go beyond v0.x of chosen because of the b/c break with the class names and the effect that would have on 3rd party components :(

**Comment by brianteeman** [comment]
Closed for the reasons stated by @wilsonge <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6161">issues.joomla.org/joomla-cms/6161</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Well, maybe something can be done about the BC problem. Let me come back to it later. Moving to Select2 seems trickier but what if `select` enhancement wasn't specifically tied to any single solution. What if the `JFormList` just accepted an option like `enhance="true"` or something and then whether that enhancement came from Select2 or any version of Chosen was just something handled maybe in a layout or something. Would something like that work?

**Comment by wilsonge** [comment]
Hmm maybe. If we left the original version of chosen in for b/c. But then you also run the risk of having two versions being loaded (new chosen/select2 and old chosen).

The problem is also people rely on niche features of these things so in a major version I don't think we can just move from select 2 to chosen 3 (as a random example) say in the middle of the 3.x release. It would just be making it easier for people to transition between Joomla 3 and 4

**Pull request closed without merging**
