### PR TITLE
[5.0][RFC][Events] Make Editor and Buttons plugins to use plugin events

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The patch improve Editor and Buttons plugins.
Now they can use a real events.
It similar to #39657 but for Editors and Buttons.

This is fully backward compatible.

**How this work.**
Here I added a new event `onEditorSetup` and an Interface for `EditorProviderInterface` class.
And similar for buttons `onEditorButtonsSetup` and a Button class with Interface `ButtonInterface`.

On `onEditorSetup` an editor plugin should register own `EditorProvider` in `EditorsRegistry`.
On `onEditorButtonsSetup` a button plugin should register own Button(s) in `ButtonsRegistry`.

The system will retrieve a requested Editor from that registry and call required methods, that defined by `EditorProviderInterface`.

Example registering an Editor:
https://github.com/joomla/joomla-cms/blob/059d2b4b96516959dd2cfaafb224c7fe457e7636/plugins/editors/codemirror/src/Extension/Codemirror.php#L50-L55

Example registering an editor Button:
https://github.com/joomla/joomla-cms/blob/059d2b4b96516959dd2cfaafb224c7fe457e7636/plugins/editors-xtd/article/src/Extension/Article.php#L58-L73

### Testing Instructions
Apply patch.
Set default editor to Codemirror and make sure it works.

Testing B/C:
Enable TinyMCE editor and make sure it works.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/Plugin/Events
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/97

### CODE REVIEW

**Comment by HLeithner** [comment]
I like it but didn't had time to look at it in deep

**Comment by Fedik** [comment]
I have "transformed" Codemirror and Article button, rest work in "legacy mode", can test b/c on them.
I will update rest later, when will know whether it suits us.

**Comment by laoneo** [comment]
I guess it is better to rebase this pr to the 5.0-dev branch, as it will get more attention for new features. Thanks for understanding.

**Comment by Fedik** [comment]
TODO: Move `buttons`, `asset`, `author` from Ediitor `$attributes` to `$params`
https://github.com/joomla/joomla-cms/blob/c2997e1a1dd5c609173c6988c7734a32324e6063/libraries/src/Editor/Editor.php#L206-L215

**Comment by HLeithner** [comment]
Can you please create a manual entry for migration, not only that it changes, also what needs to be done to convert a button to use event triggers please.

I'm merging this for now to have more test coverage in alpha.

**Comment by Fedik** [comment]
Do not forget the same for Cpatcha:
 - #39657

Also would be good to have a decision about following, client side api:
 - #40202

Which depend from Dialog PR #40150

**Pull request merged**
