### PR TITLE
Fix empty table in users permissions

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #38830 .

### Summary of Changes
Add a check for empty result array to user permissions table, like all other tables. 

### Testing Instructions
Open user permissions, filter for a permission level which has no results (in general >= 4

### Actual result BEFORE applying this Pull Request
see #38830

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 792f271d1b13eabef2bcf634ff46582637370a26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38960">issues.joomla.org/tracker/joomla-cms/38960</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 792f271d1b13eabef2bcf634ff46582637370a26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38960">issues.joomla.org/tracker/joomla-cms/38960</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38960">issues.joomla.org/tracker/joomla-cms/38960</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
