### PR TITLE
[4.2] Deprecate old resync function

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Deprecates the resync function in the menus controller as it was only used in 1.5. Was added over 12 years ago in https://github.com/joomla/joomla-cms/commit/89b50c5155d9e3fd8289c6e66fc688ad32a58bce.

Can be merged by review.

### Testing Instructions
Nothing to test as it is not used in core anymore as far as I can see.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dd68febe8dd2be759468617555c2363d8930b398<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37634">issues.joomla.org/tracker/joomla-cms/37634</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :red_circle: unsuccessfully on dd68febe8dd2be759468617555c2363d8930b398<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37634">issues.joomla.org/tracker/joomla-cms/37634</a>.</sub>

**Comment by zero-24** [comment]
Good to go lets just await the next alpha release as we where asked by the RLs.

**Comment by laoneo** [comment]
No pressure

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
