### PR TITLE
[4.0] Checkboxes [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
As it is a group of checkboxes then it should be a fieldset and have a legend instead of a label

I could only find one use of checkboxes and that is in the codemirror plugin at the bottom

@zwiastunsw please check this - its based on https://www.w3.org/WAI/tutorials/forms/grouping/

### CODE REVIEW

**Comment by brianteeman** [comment]
As far as I can tell the drone errors are completely unrelated to this PR

**Comment by wojsmol** [comment]
cc @zwiastunsw because @brianteeman mistyped Stefan nickname.

**Comment by brianteeman** [comment]
Thanks @wojsmol fixed it now

**Comment by zwiastunsw** [comment]
The code is correct. Unfortunately, the NVDA does not announce a legend. 
I can't explain why. 
I extracted the code and put it in a separate HTML document. In this case NVDA announces the legend. 

PS It also requires improvement of the CSS, but not in this PR

**Comment by brianteeman** [comment]
lol - I did exactly the same. It works perfectly in html but not in this page. weird

**Comment by wilsonge** [comment]
OK If the HTML is fine in theory - I'll merge as this is so that the library is correctly patched and we can do a follow up PR to address the specific usage instance in core

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
