### PR TITLE
Don't take "Create Article" menuitem for an article edit

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #12687 and #16612 .

### Summary of Changes
This adjusts the ContentRouter so it only takes the "Create Article" menuitem for new articles, not when editing an existing article. I adjusted the Viewconfiguration for that and added `&a_id=0` to the URL for the view in the controller.
Please note that most of the change are only within com_content, but there is one change in the menu rule which may affect other extensions. But only if they use those new JComponentRouterView stuff and I think the change should be fine. If you come into that part of the code and don't have a key set in the menuitem, it will not be stored into the needles array and never be used for the URL. So that looked wrong anyway.

### Testing Instructions
* Create at least two articles. Have a menuitem pointing to one of them and a menuitem pointing to the category.
* Create a menuitem "Create Article". For better testing you can adjust the settings within that menuitem (eg the title or the standardcategory) so the view is distinguishable easy from a regular edit.
* Now try the article edit links (in the category list and/or the single article view) and that "Create Article" link

### Expected result
* The "Create Article" menuitem should be used for any "New Article" links. Test for example the "New" button in the category list
* The edit links should **not** use the "Create Article" menuitem. Instead it should be based on the article menuitem or the category one. Whatever fits best.

### Actual result
Any edit links use the "Create Article" menuitem

### Documentation Changes Required
Don't think there is any doc at all for this router stuff.

### CODE REVIEW

**Comment by bayareajenn** [comment]
I just tested this on a client dev site that had the exact problem described. The new files work perfectly and resolve the issue. How many more people do you need to test (or sites) before it can be included with the next release? Let me know and I'll try to find people.

**Comment by alikon** [comment]
hi jenn,
They need at least 2 successfull tests  to be evaluated as ReadyToCommit and then is up to maintainers to commit / and decide milestone.
so please mark your successfull test on https://issues.joomla.org/tracker/joomla-cms/16756 so you'll need to find just another 1 to test

**Comment by bayareajenn** [comment]
I just tested this on a client dev site that had the exact problem described. The new files work perfectly and resolve the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on c25284ac31728644ccec37f4d80d8164722ab4b6<br /><br />I just tested this on a client dev site that had the exact problem described. The new files work perfectly and resolve the issue. I get a little confused in here but all good, right?!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by bayareajenn** [comment]
Hi Nicola,
Thank you! You're so great walking me through these things. :) :) I can't wait to see you in November!
jenn

**Comment by jim-porter** [comment]
I was having this problem with a production site and tested this solution. It successfully resolved the problem. Jenn thanks for letting me know about this solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by bayareajenn** [comment]
@jim-porter at the top of https://issues.joomla.org/tracker/joomla-cms/16756 login and mark that you've tested successfully. Can you see where it has Successful: 1 bayareajenn  at the top of the page? We need you to say you tested successfully too! Thank you for testing this Jim!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by jim-porter** [comment]
I have tested this item :white_check_mark: successfully on c25284ac31728644ccec37f4d80d8164722ab4b6<br /><br />I had this problem with a production site and tested this solution. The test was successful and fully resolved the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by bayareajenn** [comment]
@Bakual is it to late to get this issue in with 3.7.3?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16756">issues.joomla.org/tracker/joomla-cms/16756</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by franz-wohlkoenig** [comment]
@bayareajenn hopefully @rdeutz as Release Leader can make this Decision (but yesterday "Release Candidate 1" was going out).

**Comment by bayareajenn** [comment]
@franz-wohlkoenig I know. I saw the announcement earlier. I tried to get more testers yesterday but it didn't work out. We'll see what @rdeutz says and if it's not meant to be, it's not meant to be. Thanks!

**Comment by infograf768** [comment]
This patch is real great!

**Comment by rdeutz** [comment]
Was not in time for the RC release, I will do my own test and then decide if I merge it into 3.7.3.

**Comment by bayareajenn** [comment]
Thank you, @rdeutz !

**Comment by jsfernando** [comment]
I was also having the same issue in Article Editing, switching category. I askedo here proposed and it worked!

**Comment by franz-wohlkoenig** [comment]
@netamity can you please open a new Issue? Thanks.

**Comment by mbabker** [comment]
> Registered for the joomlacode bug reporting and awaiting approval in order to report.

JoomlaCode is not used for bug reports anymore (and hasn't been for years).  Filing issues here on GitHub (or https://issues.joomla.org/ which is just a wrapper for GitHub mainly) is the way to do it.

**Pull request merged**
