### PR TITLE
[5]re-enable one of the disabled test

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
re-enable one of the disabled test from #41938

### CODE REVIEW

**Comment by wilsonge** [comment]
What does this number represent? Is it the number of installed extensions. A code comment is going to be gold here!

**Comment by alikon** [comment]
it's the extension_id of the "**files_joomla**"

**Comment by HLeithner** [comment]
is this test really useful as it is? I mean it seems that "files_joomla" is a moving target is there any more static thing?

**Comment by HLeithner** [comment]
hmm what's the problem with postgres https://ci.joomla.org/artifacts/joomla/joomla-cms/5.0-dev/41939/system-tests/70814/screenshots/administrator/components/com_privacy/Consent.cy.js/

I restarted drone but not sure if this helps

**Comment by laoneo** [comment]
> is this test really useful as it is? I mean it seems that "files_joomla" is a moving target is there any more static thing?

This guy [here](https://github.com/joomla/joomla-cms/pull/22374) removed the hardcoded id 700 for files_joomla.

@alikon, we should probably fetch that id first by database, before we tests and then test for the returned id.

**Comment by alikon** [comment]
@HLeithner 

> is there any more static thing?

yes switched to the offline property

**Comment by HLeithner** [comment]
> @HLeithner
> 
> > is there any more static thing?
> 
> yes switched to the offline property

thanks, can be merged when test is successful.

**Pull request merged**
