### PR TITLE
End of support plugin 4.4 (based on previous PR #40556)

### PR DESCRIPTION
**Pull request by mfleeson**
Pull Request for Issue # .

Originally this code was monitored and checked in https://github.com/joomla/joomla-cms/pull/40556
I messed up my local installation and then managed to close the original PR when I renamed the branch. Mea Culpa. My apologies.

### Summary of Changes
Rewriting the 3.10 End of Service Notification and placing it into Joomla 4 coding structure and style.
Simplified the language definitions to not be hardcoded for 3 to 4
Currently using const EOS_DATE = '2023-10-25'; in file plugins/quickicon/eos/src/Extension/Eos.php The correct date should be 2025-10-25 but then the notification does not appear.
Dimitris converted the jQuery code into working javascript for closing the notification and also calling the com_ajax so the hide me is stored in the plugin parameters.

### Testing Instructions
Build.
Check plg_quickicon_eos is enabled.
View Home Dashboard in the back end.

### Actual result BEFORE applying this Pull Request
No notification is displayed

### Expected result AFTER applying this Pull Request
A notification is displayed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by mfleeson** [comment]
Sorry, although my fork was from 4.4, this tried to apply the 4.4 changes onto 4.3. Will try again!

**Comment by Hackwar** [comment]
Shouldn't this go against the 4.4-dev branch anyway?

**Comment by mfleeson** [comment]
I thought that was what i did? Its the reason I stopped the previous cos
windows git linked it against 4.3.
Mark

**Comment by Hackwar** [comment]
You can change the branch which it points at via the GUI here. Just click on edit next to the title and select the right branch.

**Pull request closed without merging**
