### PR TITLE
[5.2] Fix drag and drop for multiple tables/ul's/ol's/lists entries on one page - DraggableList.php

### PR DESCRIPTION
**Pull request by korenevskiy**
Pull Request for Issue # .

### Summary of Changes
Adds ID control for tables.
A new fix fixes the error.
 Now you can use this method several times on one page for several tables.

### Testing Instructions
If you place 2 lists/tables on one page, and for each table indicate
```HTML
<body>
	<table><tbody class='js-draggable'> .... <tbody></table>
	<ul class='js-draggable'> .... </ul>
	<div class='js-draggable'> .... </div>
</body>
```
```PHP
JHtml::_('draggablelist.draggable') ;
```
That code will only work 1 time for the first call.
My correction will allow you to place dragable lists, tables repeatedly on one page.

### Actual result BEFORE applying this Pull Request
That code will only work 1 time for the first call.

### Expected result AFTER applying this Pull Request

Now the dragable lists/tables will work on one page for each table.

 
**[draggable.JS.zip](https://github.com/joomla/joomla-cms/files/8913287/draggable.JS.zip)** `/media/system/js/draggable.js`
### It is also required to add a loop to sort out all the tables on the page in the `draggable.JS` file .

They are here in the archive.
But I don’t know which repository to do this.

### CODE REVIEW

**Comment by laoneo** [comment]
Can you please extend your testing instructions where this code can be added in a core file so a tester can check the result.

**Comment by HLeithner** [comment]
This pull requests has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by korenevskiy** [comment]
> Can you please extend your testing instructions where this code can be added in a core file so a tester can check the result.

Tell me how you can translate the status of this PR into a draft or disable it. This PR is not completed, there is an error, but it has not been resolved. This PR is 60-70% complete.

**Comment by alikon** [comment]
for change the status to draft  --- click on convert to draft on the left side of your pr
image

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by Hackwar** [comment]
@korenevskiy are you still planning to finish this PR?

**Pull request closed without merging**
