### PR TITLE
[4.2] Installation sql ordering

### PR DESCRIPTION
**Pull request by brianteeman**
This simple pr corrects the ordering for the webauthn system plugin.

It should be one more than the previous plugin - not the same.

This PR is only for new installations and should really just need a code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 160d87dc64951584230358e91112dd1ead754793<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39122">issues.joomla.org/tracker/joomla-cms/39122</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 160d87dc64951584230358e91112dd1ead754793<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39122">issues.joomla.org/tracker/joomla-cms/39122</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39122">issues.joomla.org/tracker/joomla-cms/39122</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
