### PR TITLE
[4.0] Modal footer buttons

### PR DESCRIPTION
**Pull request by brianteeman**
This PR changes the order of the modal footer buttons so that they are in the same order as the toolbar buttons ie Save, Save & Close, Close

This PR also changes the class from btn-primary to btn-success for the Save & Close button to match the toolbar colour

Any other changes to the code or codestyle are beyond the scope of this PR

Pull Request for Issue #29560  .

### CODE REVIEW

**Comment by ceford** [comment]
The Order is OK but I noticed that the Close button is White / Dark Grey. In Users / Edit Group, for example, the Toolbar Close button is White / Red.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29976">issues.joomla.org/tracker/joomla-cms/29976</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 465488612043a3deb303e7658e91eb9d74e7fbc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29976">issues.joomla.org/tracker/joomla-cms/29976</a>.</sub>

**Comment by infograf768** [comment]
@ceford is right but the issue is general
If we want to mock up toolbar for the Close button
Instead of
`<button type="button" class="btn btn-secondary"'`
we should have
`<button type="button" class="btn btn-danger'`

EDIT:
But we have a confusion between Cancel, Close and Delete in all admin.
for Cancel and Close, btn btn-secondary looks fine to me, including in toolbar.
for Delete or similar buttons. btn-danger looks correct

**Comment by infograf768** [comment]
Btw, Menus Module edit has btn-danger in this patch.
`Screen Shot 2020-07-13 at 11 45 11

**Comment by brianteeman** [comment]
I specified in the pr exactly what the scope of the pr was and yet you chose to derail it with comments about unrelated things - shame

**Pull request closed without merging**
