### PR TITLE
[4] Check for errors at a logical place, like, after they might have happened, not before.

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review. 

There is no point checking fo errors before they happen /facepalm

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b1ef828fd4e9fd24890df301fa787eda2d80d52c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34063">issues.joomla.org/tracker/joomla-cms/34063</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b1ef828fd4e9fd24890df301fa787eda2d80d52c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34063">issues.joomla.org/tracker/joomla-cms/34063</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34063">issues.joomla.org/tracker/joomla-cms/34063</a>.</sub>

**Comment by chmst** [comment]
Thanks ;)

**Pull request merged**
