### PR TITLE
[4.0] Help Dashboard

### PR DESCRIPTION
**Pull request by brianteeman**
This PR makes multiple changes to the help dashboard. In order of importance they are.

- Created a new section "Start Here"
- **Moved "Joomla Help" to the "Start Here" section to give it greater priority as it really is the first place you should look for help**
- Removed target=_blank from "Joomla Help"
- Moved "Documentation Wiki" from "Resources" to the top of "Additional Help"
- Rename "Find Help" to "Additional Help"

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 31c7505bc3ee149bc39c365810dc114080561933<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by sandewt** [comment]
Screenshots after PR:  The icon `fa-question-circle` can now be seen twice.
screen shot 2020-08-29 at 10 31 12screen shot 2020-08-29 at 10 31 12

I prefer for `Start Here` another icon, par example icon `fa-compass`
screen shot 2020-08-29 at 10 22 08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by brianteeman** [comment]
as far as i am concerned that is the expected behaviour.

these icons have not been converted to fa format yet by @N6REJ - he can always change the icon then

**Comment by sandewt** [comment]
>these icons have not been converted to fa format yet by @N6REJ - he can always change the icon then

Is not necessary in my opinion, change line 10 (file help.xml).


```
<menuitem
title="MOD_MENU_HELP_PARENT_START_HERE"
type="heading"
icon="compass"
permission="core.admin"
>

```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 96c04c4149acf109ccb4d2a3b383b082f9b97ba6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 96c04c4149acf109ccb4d2a3b383b082f9b97ba6<br /><br />Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30508">issues.joomla.org/tracker/joomla-cms/30508</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
