### PR TITLE
[4.0] [com_associations] Fix language association "clear" action

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
The fix for issue described in #27111 by @infograf768

>The Clear button is not acting as it correctly does in 3.x.
It should not only clear the existing association itself in the Reference but also reload the Target with empty item fields.

### Testing Instructions
apply patch, run `npm install`
go to edit an existing language association, and push a clear btn

### Expected result
works

### Actual result
not works

### CODE REVIEW

**Comment by infograf768** [comment]
@Fedik
First I merged https://github.com/joomla/joomla-cms/pull/27111 as it contains a patch for `administrator/components/com_associations/Field/Modal/AssociationField.php ` (wrong name for the js file)
Almost there. Clear works OK
Remains a problem when we use `Copy Reference to Target` after Clearing twice.
The reference now displays the last target created and the Iframe is blocked.

problem_sidebyside

**Comment by Fedik** [comment]
hm, that also strange 
need to look

**Comment by Fedik** [comment]
@infograf768 I tried 8-10 times in row, to "copy to reference" and "clear", and it work without any blocking to me.
In theory it may happen if there a js error, can you please look in Browser dev console, is there any? (turn joomla to debug mode "on", so we will see a real line number for error)

**Comment by infograf768** [comment]
@Fedik
I can't indeed totally replicate it. Debug console shows no error but look carefully at this capture:
The new target is first briefly loaded in reference before being replaced by the original reference with an iframe reload.

sidebyside_display2

The difference with my test before is that it was remaining stuck as reference and is now replaced.

Shall we just hope that it will remain working this weird way or try to figure out what's really going on?

**Comment by Fedik** [comment]
@infograf768 I see you  have 3 languages, and I have only 2, maybe somehow related also,
I will try to check more

**Comment by Fedik** [comment]
@infograf768 I have tried one more time.
Sorry I still cannot replicate it

> Shall we just hope that it will remain working this weird way or try to figure out what's really going on?

I think, we can test the patch as is now, 
And if it will be a bug for multiple users, then we may get more info  about that weird bug.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 722df45144b22457d2d880e995423a5030925c81<br /><br />Agree. Thanks. Let’s get this in.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27159">issues.joomla.org/tracker/joomla-cms/27159</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d512b75b38a40d1944913db8b1a1252f74dbd11c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27159">issues.joomla.org/tracker/joomla-cms/27159</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27159">issues.joomla.org/tracker/joomla-cms/27159</a>.</sub>

**Comment by infograf768** [comment]
Thanks.

**Comment by infograf768** [comment]
@alikon 
Have you remarked when testing the weird behavior I saw?

**Pull request merged**
