### PR TITLE
[4.0] Remove unused language files

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes unused language files. There is no `plg_fields_image` plugin.

### Testing Instructions

Review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ca803bf60207ce6154e472e1137a5ebfb1a5554c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31177">issues.joomla.org/tracker/joomla-cms/31177</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ca803bf60207ce6154e472e1137a5ebfb1a5554c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31177">issues.joomla.org/tracker/joomla-cms/31177</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31177">issues.joomla.org/tracker/joomla-cms/31177</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
