### PR TITLE
[4.0] Toolbar to use Custom Element dropdowns

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR utilises the dropdowns Custom Element.

It still requires some JS refactoring and support for RTL, however that can be done in the CE repo at a later date

Requires https://github.com/joomla-projects/custom-elements/pull/111 to be merged

### To-do
 - [ ] Properly import the dropdown custom element when using `npm i`

### Result

screeny

### CODE REVIEW

**Comment by infograf768** [comment]
> It still requires some JS refactoring and support for RTL, however that can be done in the CE repo at a later date

Rant:: RTL is almost always forgotten until last minute (if it is). It should always be dealt with for any PR imho, and not "later". Nothing personal. Just a general rant.

**Comment by C-Lodder** [comment]
@infograf768 RTL support added

**Comment by dgrammatiko** [comment]
FWIW the code for the Dropdown Element is utterly crap (talking for my own code here, not the changes Charlie did) in the other repo BUT the only attribute that will remain also in the upcoming Custom Element is `for`. So I guess this is ok-ish.

Although I will recommend to simply copy the CE in the main repo for the time being and remove it when the new one is available in the other repo...

**Comment by C-Lodder** [comment]
@dgrammatiko sure, I'll copy the CSS/JS over so it can at least be tested. Please note the wrapper I've used though. Not ideal but actually essential

**Comment by dgrammatiko** [comment]
@C-Lodder I would suggest to implement the dropdown first on the control panel layout so we can drop Bootstrap js from the template index.php but I'm ok with whatever...

**Comment by C-Lodder** [comment]
@dgrammatiko I will do that as a separate PR

**Pull request closed without merging**
