### PR TITLE
Fix issie with filtereng categories by language

### PR DESCRIPTION
**Pull request by toslan**
This patch includes fix https://github.com/joomla/joomla-cms/pull/5756 and fixes another issue which cause Language switcher module to provide wrong URL for a language that is not currently active. The URL was computed using category path helper where inactive languages were blocked. Now only association mechanism is used without path helper

### CODE REVIEW

**Comment by zero-24** [comment]
@toslan can you have a look into the CS?

```
FILE: /home/travis/build/joomla/joomla-cms/modules/mod_languages/helper.php
--------------------------------------------------------------------------------
FOUND 4 ERROR(S) AFFECTING 3 LINE(S)
--------------------------------------------------------------------------------
 103 | ERROR | Opening parenthesis of a multi-line function call must be the
     |       | last content on the line
 103 | ERROR | Whitespace found at end of line
 104 | ERROR | Whitespace found at end of line
 105 | ERROR | Closing parenthesis of a multi-line function call must be on a
     |       | line by itself
-------------------------------------------------------------------------------
```

**Comment by infograf768** [comment]
This does not work.
I may get some urls of type:
`http://localhost:8888/testwindows/trunkgitnew/en/multi-lingual-steps-by-steps.html?id=31:enable-the-language-filter-system-plug-in`
instead of
`http://localhost:8888/testwindows/trunkgitnew/multi-lingual-steps-by-steps/31-enable-the-language-filter-system-plug-in.html`
which evidently gives a 404.

**Comment by toslan** [comment]
@infograf768 There is no language section (like '/en/' )In your desired url which appears on all paths of multilanguage site. Something wrong with the structure of menus? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5817">issues.joomla.org/joomla-cms/5817</a>.</sub>

**Comment by brianteeman** [comment]
It has been over 1 year since the last comment here and based on comments above I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5817">issues.joomla.org/joomla-cms/5817</a>.</sub>

**Pull request closed without merging**
