### PR TITLE
[4.1] Admin User accessibility settings

### PR DESCRIPTION
**Pull request by brianteeman**
Adds a description to avoid confusion as seen in #37291

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f1f816e7e38b5508524454e269d2e03dd8bbfddf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37307">issues.joomla.org/tracker/joomla-cms/37307</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f1f816e7e38b5508524454e269d2e03dd8bbfddf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37307">issues.joomla.org/tracker/joomla-cms/37307</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37307">issues.joomla.org/tracker/joomla-cms/37307</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
