### PR TITLE
[4.0] Password strength

### PR DESCRIPTION
**Pull request by brianteeman**
When creating a user in the admin we can see a password strength meter.

Currently the meter has an aria-describedby value of the following text.

This is not correct as the meter never receives focus. The text needs to have an aria-live value so that when the text is updated it is announced.

This PR corrects that using the technique from https://www.w3.org/WAI/tutorials/forms/examples/password/

There is no visual change
Viewing the source you will see that the aria-describedby in the progress bar div is now an id
And that the aria-live polite value has been added to the text div

requires npm install to test

### CODE REVIEW

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on b0290db1b962ad976f629e46ecc4d98811841f17<br /><br />Thanks for the PR. Works as described. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24437">issues.joomla.org/tracker/joomla-cms/24437</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on f5260e91ff4315694ecf55d3127c06385f259780<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24437">issues.joomla.org/tracker/joomla-cms/24437</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24437">issues.joomla.org/tracker/joomla-cms/24437</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
