### PR TITLE
[4.2] Indicate if category not published

### PR DESCRIPTION
**Pull request by brianteeman**
Articles that are in a category which is unpublished or trashed are not visible on the site but there is no way you can tell this from the article manager

### Summary of Changes
1. Adds an indicator if the category is unpublished or trashed. 
2. Changes the published icon to a disabled icon and adds a tooltip to the icon

### Testing Instructions
Create a catgory called test and create 4 featured articles in that category. 
Unpublish or Trash the category

Check the list of articles and the list of featured articles

### Actual result BEFORE applying this Pull Request
No indication that the article can not be displayed

### Expected result AFTER applying this Pull Request
Text as shown in the image below

image

### CODE REVIEW

**Comment by rdeutz** [comment]
Looks like a good idea, I think this is something we should add and can be added to the next minor version.

**Comment by rdeutz** [comment]
one addition: maybe better to solve this in the PublishedButton class. Then you only have to fix it one time and not in all views. Could be something like "Published but category unpublished or trashed"

**Comment by brianteeman** [comment]
@rdeutz That was my first thought but then it gets complicated by workflows

**Comment by brianteeman** [comment]
@rdeutz took another look but I dont see how to do it in the class as it is not aware of the category

**Comment by brianteeman** [comment]
@rdeutz do you have any pointers as to how to solve it in the PublishedButton. If not I will continue with this approach.

**Comment by rdeutz** [comment]
I looked at the class and (beside Workflow, I don't see how this effects the buttom but maybe I missed something) it should be doable. I will check over the weekend and let you know.

**Comment by brianteeman** [comment]
@rdeutz thanks

**Comment by rdeutz** [comment]
This should do the trick: https://github.com/rdeutz/joomla-cms/commit/847c041c76ff8c913d03fe32c3a310dff11be46a

**Comment by brianteeman** [comment]
> one addition: maybe better to solve this in the PublishedButton class. Then you only have to fix it one time and not in all views. Could be something like "Published but category unpublished or trashed"

as even your code requires a chang in the view I decided to combin the two

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on d3bd8857dd1d25175afc0e85e25590c1d4054b81<br /><br />The patch workes exactly as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37583">issues.joomla.org/tracker/joomla-cms/37583</a>.</sub>

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on d3bd8857dd1d25175afc0e85e25590c1d4054b81<br /><br />Tested in Joomla 4.1.3-dev with PHP 8.1.

Expected behaviour when category is unpublished or trashed.

It works in Featured Articles list too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37583">issues.joomla.org/tracker/joomla-cms/37583</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37583">issues.joomla.org/tracker/joomla-cms/37583</a>.</sub>

**Comment by bembelimen** [comment]
I really like this PR, but it will not make it in 4.1, but for sure in 4.2!

Thanks for the improvement.

**Comment by bembelimen** [comment]
JFYI: the "too much files" will be fixed on Tuesday, then there will be the next upmerge from 4.1 (which is already in your branch) after the relese of J! 4.2 Alpha 2. Then we're back to normal (no additional human tests needed).

**Comment by brianteeman** [comment]
No problem

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
