### PR TITLE
[4.0] Move image box in media manager to bottom

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #31820 and #29156 .

### Summary of Changes
Currently rotating and resizing an image let the box jump, based on the height. This PR moves the image below the parameters so there is no jumping.

### Testing Instructions
Edit an image in the media manager

### Actual result BEFORE applying this Pull Request
Jumping because the image is above the parameters

### Expected result AFTER applying this Pull Request
No jumping because the image is below the parameters.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 94750c3cc823e5355f2b13e5ffa361d3dfe7a872<br /><br />Hint for other testers: It needs NPM to build the JS.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31830">issues.joomla.org/tracker/joomla-cms/31830</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 94750c3cc823e5355f2b13e5ffa361d3dfe7a872<br /><br />Yes - I prefer it this way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31830">issues.joomla.org/tracker/joomla-cms/31830</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31830">issues.joomla.org/tracker/joomla-cms/31830</a>.</sub>

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on 94750c3cc823e5355f2b13e5ffa361d3dfe7a872<br /><br />img<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31830">issues.joomla.org/tracker/joomla-cms/31830</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
