### PR TITLE
Cassiopeia missing color

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/40540

### Summary of Changes

Adds the missing `var(--black)`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0b604dacf9549b7437f26fb080aca471eb60df1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40541">issues.joomla.org/tracker/joomla-cms/40541</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0b604dacf9549b7437f26fb080aca471eb60df1d<br /><br />I've verified that the variable `$black` is defined here https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss#L32 so the change from this PR is correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40541">issues.joomla.org/tracker/joomla-cms/40541</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40541">issues.joomla.org/tracker/joomla-cms/40541</a>.</sub>

**Comment by obuisard** [comment]
Thanks Dimitris @dgrammatiko !

**Pull request merged**
