### PR TITLE
[4.1] Action Logs Scheduler

### PR DESCRIPTION
**Pull request by brianteeman**
Set scheduler logging in action logs to on by default. New installations only.

Pull Request for Issue #37361 .

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd79bc7df6bd37d1030d5c2d2d2809c039f04b95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37365">issues.joomla.org/tracker/joomla-cms/37365</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on bd79bc7df6bd37d1030d5c2d2d2809c039f04b95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37365">issues.joomla.org/tracker/joomla-cms/37365</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37365">issues.joomla.org/tracker/joomla-cms/37365</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
