### PR TITLE
[4.0] [com_users] Missing imports, adapt to language pack changes.

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds missing imports and adapts some methods to language pack changes.

### Testing Instructions

Edit your profile in frontend. Select editor, backend and frontend languages.
Add this code to `components/com_users/tmpl/profile/default_params.php`:

```
HTMLHelper::register('users.editor', array(HTMLHelper::getServiceRegistry()->getService('users'), 'editor'));
HTMLHelper::register('users.language', array(HTMLHelper::getServiceRegistry()->getService('users'), 'language'));
```
View your profile.

### Expected result

No errors. Values are displayed correctly (e.g. `Editors - CodeMirror` and `English (United Kingdom)`)

### Actual result
Errors:
>Class 'Joomla\Component\Users\Administrator\Service\HTML\Factory' not found
>Class 'Joomla\Component\Users\Administrator\Service\HTML\LanguageHelper' not found 

Raw values are displayed (`codemirror` and `en-GB`).

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9ba4c42030d2baeebc346b37659866d1f9d3f6eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27783">issues.joomla.org/tracker/joomla-cms/27783</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9ba4c42030d2baeebc346b37659866d1f9d3f6eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27783">issues.joomla.org/tracker/joomla-cms/27783</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27783">issues.joomla.org/tracker/joomla-cms/27783</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
