### PR TITLE
[4.0] Update TinyMCE to v4.5.6

### PR DESCRIPTION
**Pull request by C-Lodder**
**Version 4.5.6** (2017-03-30)

- Fixed bug where it wasn't possible to select floated images in some cases.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
try installing PR, got: Error The file marked for modification does not exist: grunt_settings.yaml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15106">issues.joomla.org/tracker/joomla-cms/15106</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
sorry, was on 3.7

On 4.0 got: Error Could not connect to GitHub: This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15106">issues.joomla.org/tracker/joomla-cms/15106</a>.</sub>

**Comment by mbabker** [comment]
You won't be able to test this with patch tester then.  It's either a new restriction on GitHub's API or something about the size of TinyMCE, but its base JavaScript is definitely too large for the API.

**Comment by C-Lodder** [comment]
can't see what the issue would be considering only 28 lines of code were changed

**Comment by dgt41** [comment]
tiny is totally broken in J4!

**Comment by C-Lodder** [comment]
Not for me @dgt41

**Comment by dgt41** [comment]
can you save content?

**Comment by franz-wohlkoenig** [comment]
@C-Lodder #15091 is RTC now.

**Comment by C-Lodder** [comment]
ah no, says it's saved but doesn't update

**Comment by dgt41** [comment]
a pretty foobar editor ;)

**Comment by mbabker** [comment]
> can't see what the issue would be considering only 28 lines of code were changed.

Patch tester isn't patching files.  It downloads and replaces full files.  Patch tester can't do patches, it would require information about the git environment the Joomla build is based on to get the correct patch path and that's too impractical.

**Pull request merged**
