### PR TITLE
[4.0] Menu arrows RTL support

### PR DESCRIPTION
**Pull request by brianteeman**
As shown in the animation this PR ensures that the arrows point in the correct direction etc on an RTL web site
after

### CODE REVIEW

**Comment by HLeithner** [comment]
You should remove line administrator/templates/atum/scss/blocks/_sidebar.scss:390 or only add an override to rtl (which is a more readable way in my opinion).

**Comment by brianteeman** [comment]
I have removed line 390 - that was indeed an error

In the absence of any code style guidance on this I went for the same as a few lines above in the same file. For me this is clearer

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b04b5c76a097614915573fcf9b9bc8351af1c241<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27377">issues.joomla.org/tracker/joomla-cms/27377</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks - still a lot to do to make this template RTL

**Pull request merged**
