### PR TITLE
[4.x] Fix open_basedir warning when creating a menu item

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #36788 and #35895 .

### Summary of Changes

Correctly check path. Same as #36789

### Testing Instructions

Follow  #36788 and #35895 

### Actual result BEFORE applying this Pull Request
A warning about open_basedir stuff 

### Expected result AFTER applying this Pull Request
No warning

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ChristineWk** [comment]
Thank you @Fedik 
For J 3 = OK. (36789)
For J 4 = (Patchtester) got Message: 
404RuntimeException
Invalid Issue

**Comment by ChristineWk** [comment]
Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36791">issues.joomla.org/tracker/joomla-cms/36791</a>.</sub>

**Comment by richard67** [comment]
I see that @ChristineWk could not mark her test result because the "Test this" button is missing in the issue tracker. A problem which we sometimes have for (yet) unknown reasons. Maybe it will appear later, we will see.

**Comment by richard67** [comment]
I have also tested with success. Still no "Test this" button for this PR in the issue tracker, but it has 2 human tests so I set it RTC (if that will work at least).

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36791">issues.joomla.org/tracker/joomla-cms/36791</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
