### PR TITLE
postgresql add missing ; to update Sql file

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #9450
#### Summary of Changes

Add the missing ;
#### Testing Instructions

Perform a update on postgresql
Try the database fix button
Error message
Apply this patch (or change the file manually)
Try again

### CODE REVIEW

**Comment by zero-24** [comment]
Can we get a release blocker label? @wilsonge @brianteeman ?

**Comment by wilsonge** [comment]
Me and Brian are in a pub. It's merged

**Comment by zero-24** [comment]
Have fun. Thanks.

**Comment by richard67** [comment]
Partly my fault, shame I did not notice this mistake when taking the changes from old PR #4781 into my PR #9269 .

I just checked: It seems it was the only mistake in that PR so there should not pop up more errors from that.

**Comment by zero-24** [comment]
No Problem @richard67 you have fixed a lot of bugs that are much bigger than this very smal one. Great to have you on board!

**Pull request merged**
