### PR TITLE
[4.0] Template styles Toolbars: add alert when setting Default + use Toolbar class

### PR DESCRIPTION
**Pull request by infograf768**
See discussion https://github.com/joomla/joomla-cms/pull/24541

### Summary of Changes
Using new Toolbar class all over the view.
Displaying a confirm alert when setting a style as Default
### Before patch
One can choose multiple template styles and use Default button, therefore setting as Default the style with the lower id.
### After patch
Screen Shot 2019-04-15 at 06 57 08

@hardik-codes

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally I believe this to be the wrong approach for j4 and the button should be disabled instead

**Comment by infograf768** [comment]
Yes, this would be the ideal. 
I am sure you will find a better way with the existing toolbar code we have in J4.

**Comment by jduerscheid** [comment]
I have tested this item :red_circle: unsuccessfully on e1744e8071bd55a780562d5214c80d00f4b25c0c<br /><br />I think there is some work needed. The message is displayed everytime you click on the default button. Even when only one style is selected. When I select more than one style and I confirm the errormessage one of the selected is set to default. I think this is no good workflow. 

It would be better if the message only displays when more than one styles are selected. Furthermore it would be better, that only one button is on the Message, and if you click it you will get back to the selection you did and you has the option to update your selection.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24591">issues.joomla.org/tracker/joomla-cms/24591</a>.</sub>

**Comment by Quy** [comment]
A simple solution is to remove the Default button and use the `Default` column to select the default.

**Comment by roland-d** [comment]
@infograf768 Do you want to fix the merge conflicts or should this PR be closed?

**Comment by degobbis** [comment]
I have tested this item :red_circle: unsuccessfully on e1744e8071bd55a780562d5214c80d00f4b25c0c<br /><br />Patchtester returns an error on apply
> The file marked for modification does not exist: administrator/components/com_templates/View/Styles/HtmlView.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24591">issues.joomla.org/tracker/joomla-cms/24591</a>.</sub>

**Comment by gostn** [comment]
@degobbis: you can see conflicting files before test on github at end of pr which mean in most cases dont test:

image

**Comment by laoneo** [comment]
@infograf768 thanks for your pr. Can you fix the conflicts please and rebase to the 4.2-dev branch? In the meantime I'm closing the pr. When ready please reopen again so we can make another test round as this is a welcome change to stabilize the template manager.

**Pull request closed without merging**
