### PR TITLE
Fix sql queries in the update file for mssql

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

Clean up the update files for the ms sql server.

- add missing `;` at the end of sql query
- replace quote `[]` by double quote
- add missing `SET IDENTITY_INSERT "..." ON;`
- replace `INSERT INTO ... SELECT ...` by `INSERT INTO ... VALUES (...)`
- add a white space after table name on line `CREATE TABLE ...` to fix the error on backend -> extension -> manage -> database fix
- replace a backtick "`" by double quote, the backtick does not work on the SQL Server.
- delete the default value before deleting the column: `3.9.0-2018-10-20.sql`
- remove useless `SET QUOTED_IDENTIFIER ON;`

### Testing Instructions
Code review. 
Unit tests should pass.

I tested with `postupdate.php`.
Note: remove a line from code, which requires toolbar.php.

### Expected result
Joomla on the SQL server should update correctly (from version 3.8.13).

### Actual result
The Joomla update on the SQL server will fail.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d0ad45268083b202ca89d5cb9b5bca9fbf885156<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23210">issues.joomla.org/tracker/joomla-cms/23210</a>.</sub>

**Comment by csthomas** [comment]
Since this is only related to the MSSQL database, I am asking for RTC

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on d0ad45268083b202ca89d5cb9b5bca9fbf885156<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23210">issues.joomla.org/tracker/joomla-cms/23210</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23210">issues.joomla.org/tracker/joomla-cms/23210</a>.</sub>

**Pull request merged**
