### PR TITLE
[4.1] Request interval seconds

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the unit otherwise you have no way of knowing it is seconds and to be consistent to the task timeout label

## After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97370d9e5b93f3cc03a15f61d271c4da6c95c2c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36660">issues.joomla.org/tracker/joomla-cms/36660</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 97370d9e5b93f3cc03a15f61d271c4da6c95c2c0<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36660">issues.joomla.org/tracker/joomla-cms/36660</a>.</sub>

**Comment by tecpromotion** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36660">issues.joomla.org/tracker/joomla-cms/36660</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36660">issues.joomla.org/tracker/joomla-cms/36660</a>.</sub>

**Comment by C-Lodder** [comment]
Just an FYI, you can add `addonAfter="seconds"` to the XML field so that it displays like so:

image

Note: Not saying it has to be done like this, but worth mentioning as not many know about this feature.

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
