### PR TITLE
[4.2] Limit language overrides search results to selected language

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #37779 .

### Summary of Changes
Added a simple check to the filepath if the current language is part of it. If not, the file is skipped.
I've excluded the base path from the check so it doesn't get triggered if someone has Joomla stored eg within a folder "en-GB" (you never know...).

### Testing Instructions
* Search for a language constant from a 3rd party extension which has their files stored in its extension directory (eg DP Calendar or my own SermonSpeaker will do).

### Actual result BEFORE applying this Pull Request
String are shown for all available languages

### Expected result AFTER applying this Pull Request
Strings are limited to the selected language

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
@Bakual Will you make a PR for 3.10-dev, too? Am asking because the issue was for both 3.10 and 4.1. Am not sure if I shall close the issue now or if I shall wait for a 3.10-dev PR.

Update: I meanwhile saw this PR is for 4.2-dev and not 4.1-dev. So it's a kind of new feature? If so, just ignore my comment above.

**Comment by Bakual** [comment]
I dunno. I just had a 4.2 installation and worked with that. I guess it would be just copy paste for other branches.
If you want to fix it in 3.x, I can make one for J3 and you guys just upmerge it to J4. But it's likely a very longstanding issue, so not sure if it needs to be fixed in J3 😄

**Comment by richard67** [comment]
@Bakual We can collect opinions in the maintainers channel 😄

**Review by laoneo — APPROVED** [review]

**Review by joomleb — APPROVED** [review]
Tested with success, thanks!

**Comment by richard67** [comment]
@joomleb Please mark your test result here in the issue tracker, using the blue "Test this" button, then selecting your test result and then submitting: https://issues.joomla.org/tracker/joomla-cms/37809 . Thanks in advance.

**Comment by richard67** [comment]
@joomleb Approval on GitHub only means a code review has been done. Human test results have to be marked like I described in my previous comment.

**Comment by joomleb** [comment]
I have tested this item :white_check_mark: successfully on 4ea439c62083929a0a7af531f337eca1368dd2a1<br /><br />Perfect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37809">issues.joomla.org/tracker/joomla-cms/37809</a>.</sub>

**Comment by joomleb** [comment]
> @joomleb Approval on GitHub only means a code review has been done. Human test results have to be marked like I described in my previous comment.

Thanks for help on understanding

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4ea439c62083929a0a7af531f337eca1368dd2a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37809">issues.joomla.org/tracker/joomla-cms/37809</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37809">issues.joomla.org/tracker/joomla-cms/37809</a>.</sub>

**Comment by infograf768** [comment]
I see no reason to not backport this to 3.x and 4.1.
After all, this is a bug.

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
