### PR TITLE
Change Joomla Update Notification Text

### PR DESCRIPTION
**Pull request by coolcat-creations**
The Current Joomla Update Notification mail is very long and sounds kind of aggressive. Instead of telling the User in Uppercase letters not and do not contact Joomla I changed the text to be more positive and friendly and to contact the site manger. The update mail before repeated itself and was therefore way too long, it confused the non technical admin with some technical words, It sounded very aggressive with uppercase letters and made the update appear scary. I hope next time a Joomla Update is available, the user can get the notification about the "Good News". Thanks!

Edit: Uppercase letters should not be used this much because of accessibility reasons as well.

### Actual result BEFORE applying this Pull Request

This email IS NOT sent by the Joomla! project. It is sent automatically by your own site, 
[xxx) - xxxx

================================================================================
UPDATE INFORMATION 
================================================================================

Your site has discovered that there is an updated version of Joomla! available for download. 

Joomla! version currently installed: 3.10.6 
Joomla! version available for installation: 3.10.8 

This email is sent to you by your site to remind you of this fact. 
The Joomla! project will never contact you directly about available updates of Joomla! on your site. 

================================================================================
UPDATE INSTRUCTIONS 
================================================================================

To install the update on xxx please select the following link. (If the URL is not a link, copy & paste it to your browser). 

Update link: xxxx

Release News can be found here: https://www.joomla.org/announcements/release-news/ 

================================================================================
WHY AM I RECEIVING THIS EMAIL? 
================================================================================

This email has been automatically sent by a plugin provided by Joomla!, the software which powers your site. 
This plugin looks for updated versions of Joomla! and sends an email notification to its administrators. 
You will receive several similar emails from your site until you either update the software or disable these emails. 

To disable these emails, please unpublish the 'System - Joomla! Update Notification' plugin in the Plugin Manager on your site. 

If you do not understand what Joomla! is and what you need to do please do not contact the Joomla! project. 
They are NOT sending you this email and they cannot help you. Instead, please contact the person who built or manages your site. 

If you are the person who built or manages your website, please note that this plugin may have been activated automatically when you installed or updated Joomla! on your site. 

================================================================================
WHO SENT ME THIS EMAIL? 
================================================================================

This email is sent to you by your own site, xxxxx

### Expected result AFTER applying this Pull Request

Hi!
Good news: An updated Joomla! system version for the website {SITENAME} is now available!

Information about the update:
Website name: {SITENAME}
Website address: {URL}
Current Joomla! version: {CURVERSION}
Available Joomla! version: {NEWVERSION}

What do I have to do?
The system update can easily be started via the following link:
{LINK}

To open, please click on the link or copy it into the address bar of your browser.

The system will continue to send reminders until the update is successfully completed.

What has changed?
Detailed information on the latest changes can be found at the link:
{RELEASENEWS}

Why am I receiving this mail?
Joomla! is the software used to operate the website "Website Name". Regular updates are important for the function and security of this website.

Joomla! automatically sends out notifications when a new system version is available.
In order not to receive these notifications in the future, the item "System Joomla! update notification" must be deactivated in the plugin administration of the website.

Who can I contact if I have any questions?
This e-mail is an automatically sent information e-mail from the website {SITENAME}.
If you have any questions about this email or the necessary steps to update, please contact the person who manages your website.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in favour of this change.

**Comment by drmenzelit** [comment]
> I am not in favour of this change.

may I ask why?

**Comment by coolcat-creations** [comment]
> I am not in favour of this change.

Does it contain any language mistakes? Can I ask you for a review?

**Comment by chmst** [comment]
Removing text in capitals is very welcome and a step towards accessibility.

**Comment by brianteeman** [comment]
it removes important information
it is harder to read
it does not frontload the action

> Removing text in capitals is very welcome and a step towards accessibility.

that is valid in the absence of html (which can be used instead)

**Comment by coolcat-creations** [comment]
> it removes important information

Which one?

> it is harder to read

Sorry I did my best with my non native skills. Maybe someone could rephrase it in english. Fun Fact: The german mail is a kind of 1:1 translation of the english one and very hard to read too.

> it does not frontload the action

Ok maybe we can write
"Please start the update via the following link:" instead "The system update can easily be started via the following link:"

**Comment by brianteeman** [comment]
From a language perspective words such as "easily" should not be used. They are subjective words that have been prevuously removed (sorry I cant find the link right now).

> Sorry I did my best with my non native skills. Maybe someone could rephrase it in english. 

Which is why I am not in favour of the changes

> Fun Fact: The german mail is a kind of 1:1 translation of the english one and very hard to read too.

Perhaps that's the real problem to be solved

**Comment by coolcat-creations** [comment]
Ok, then I ask someone native to rephrase the mail. As stated above: The current mail is kind of agressive and negative, way too long, scares people and is confusing. 

I was not aware that it's forbidden to suggest changes as non native. Sorry for bothering you Brian.

**Comment by chmst** [comment]
@brianteeman I understand your opinion from a developers point of view. As a user I am bored to get this  text again and again and again.

Could we shorten the text to a minimum and bring the endless repeated information on a documentation page?

**Comment by coolcat-creations** [comment]
@chmst thats a also very nice suggestion, the mail is way too long. People who really need help could read all important things on a docs page - the mail would only contain "the good news".

**Comment by brianteeman** [comment]
What is the repeated information?

Where is the evidence that it scares people?

**Comment by coolcat-creations** [comment]
> What is the repeated information?

This email **IS NOT sent by the Joomla! project**. It is sent automatically **by your own site**,
**Your site** has discovered that there is an updated version of Joomla! available for download.

This email is **sent to you by your site** to remind you of this fact.
**The Joomla! project will never contact you directly about available updates of Joomla! on your site**.

**This email has been automatically sent by a plugin provided by Joomla!, the software which powers your site.**

If you do not understand what Joomla! is and what you need to do **please do not contact the Joomla! project.**
**They are NOT sending you this email** and they cannot help you. Instead, please contact the person who built or manages your site.

This email is **sent to you by your own site**, xxxxx


> 
> Where is the evidence that it scares people?

It scares even me. Its unfriendy and harsh.

**Comment by brianteeman** [comment]
> It scares even me. Its unfriendy and harsh.

and in seven years this is the first time you raise it. Obviously not that scary.

PS the original text was not written by a native english speaker either

**Comment by HLeithner** [comment]
> > It scares even me. Its unfriendy and harsh.
> 
> and in seven years this is the first time you raise it. Obviously not that scary.

better late then never, so can you help making this text friendlier?

**Comment by brianteeman** [comment]
> better late then never, so can you help making this text friendlier?

No not really as I dont see the problem

**Comment by HLeithner** [comment]
> > better late then never, so can you help making this text friendlier?
> 
> No not really as I dont see the problem

Ok that's sad then we find someone else, thanks anyway.

**Comment by brianteeman** [comment]
to be clear and to avoid misunderstanding - I am not refusing to help. I am just saying as I dont see where it is unfriendly I wouldnt be able to make it less unfriendly

**Comment by HLeithner** [comment]
> to be clear and to avoid misunderstanding - I am not refusing to help. I am just saying as I dont see where it is unfriendly I wouldnt be able to make it less unfriendly

I understood that, as said no problem.

**Comment by kitepascal** [comment]
Who can I contact if I have any questions?

This e-mail is an automatically sent information e-mail from the website {SITENAME}.
If you have any questions about this email or the necessary steps to update, please contact the person who manages your website.


Admin lost?

Kindly search the web for "Joomla Forum" or "Joomla Service Provider" - the community is glad to help you out. 



-> Some lovely closing words :)

**Comment by chmst** [comment]
Mentioning sustainability. Millions of Joomla sites, send x*millions of update mails - users could be encouraged to reduce co2 emission and set parameters for update messages carefully.

**Comment by kitepascal** [comment]
See #11707 & #35345.

My suggestion would be:

Update email notification type: 
- Only important security updates (fixed 12-hours-frequency) - preselected.
- All updates (fixed 14-days-frequency or configurable, except from security updates arriving twice daily).


Extend detailsurl (https://update.joomla.org/core/sts/extension_sts.xml) with its security relevance.


-> co2 emission drastically lowered.

**Comment by softforge** [comment]
> Mentioning sustainability. Millions of Joomla sites, send x*millions of update mails - users could be encouraged to reduce co2 emission and set parameters for update messages carefully.

This is a really good point. It could certainly be made shorter and friendlier without losing information or impact. It's also a missed opportunity marketing wise.
I understand Brians point about subjective comments but we should be allowed some pride in our releases. At least paint them as improvements. 

WHY AM I RECEIVING THIS EMAIL? section, (I hate all caps as I find them hard to read and studies show that its harder to read than lowercase so that's one thing we should fix) does not say why they are receiving it apart from the mechanism, a plugin, which if its read by someone who has no clue as the email seems to be aimed at, won't understand what a plugin is!.  It should say the why is to help secure, improve or bug fix their site.

There is no positive message.

I will have a think and see if I can improve on it and would encourage others to. Then we can come up with an improvement which is hopefully positive, environmentally friendly and humanly friendly.

**Comment by toivo** [comment]
The original text, the section headings in capitals and the text should not be changed because the email is informative and it contains the right level of details for the target audience, the webmasters who maintain Joomla sites.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37496">issues.joomla.org/tracker/joomla-cms/37496</a>.</sub>

**Comment by coolcat-creations** [comment]
@softforge - Did you have the chance to look into this?

**Comment by HLeithner** [comment]
This pull requests has automatically rebased to 4.2-dev.

**Comment by coolcat-creations** [comment]
@uglyeoin but what can I do now? Creating a new PR with the exact same suggestion?

**Comment by uglyeoin** [comment]
@coolcat-creations can you not reopen this issue?

**Comment by coolcat-creations** [comment]
No, it has been closed because I apparently deleted something from the git @uglyeoin no possibility to reopen. But as my text was not ok anyway anyone could open a PR?

**Pull request closed without merging**
