### PR TITLE
[4.0] Login UI fixes

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Fix the login module UI for BS4-beta.3

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 359ee3ffe1aa1938323c8ee995d3494f7296a627<br /><br />Grey background has different Width.

bildschirmfoto 2017-12-29 um 19 05 28

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19209">issues.joomla.org/tracker/joomla-cms/19209</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - I suppose that's intentional as the icons are different widths. I can add a `min-width` but I'd rather do that when working on the new template

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 359ee3ffe1aa1938323c8ee995d3494f7296a627<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19209">issues.joomla.org/tracker/joomla-cms/19209</a>.</sub>

**Comment by anuragteapot** [comment]
@C-Lodder  @franz-wohlkoenig  Password hide and show not working can you check, please? In admin login
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19209">issues.joomla.org/tracker/joomla-cms/19209</a>.</sub>

**Comment by C-Lodder** [comment]
@Anu1601CS That has been rewritten already. Please feel free to test and give feedback: https://github.com/joomla/joomla-cms/pull/19231

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 359ee3ffe1aa1938323c8ee995d3494f7296a627<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19209">issues.joomla.org/tracker/joomla-cms/19209</a>.</sub>

**Comment by Quy** [comment]
RTC

**Pull request closed without merging**
