### PR TITLE
Fix the backend logout button issue #37163

### PR DESCRIPTION
**Pull request by prakhar3062**
Pull Request for Issue 
Issue #37109 
Summary of Changes
Put the logout button outside the dropdown menu.

Testing Instructions
After applying the patch, see the header of home page , you will see the result

Actual result BEFORE applying this Pull Request
68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39363334316334343432313938626239366230323562663934356465363136322e706e67

Expected result AFTER applying this Pull Request

Web capture_1-3-2022_153056_localhost

Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by rjharishabh** [comment]
It should be a different button
see https://github.com/joomla/joomla-cms/issues/37109#issuecomment-1047184281

**Comment by prakhar3062** [comment]
> It should be a different button see [#37109 (comment)](https://github.com/joomla/joomla-cms/issues/37109#issuecomment-1047184281)

I tried but it is disturbing the ui at some or other point. Changes made by me is the one demanded by user

**Comment by laoneo** [comment]
Please give the pr a proper title. Also make the changes in the file of the module itself. The template should not come with an override at all.

**Comment by prakhar3062** [comment]
> Please give the pr a proper title. Also make the changes in the file of the module itself. The template should not come with an override at all.

Didn't get you. Please explain more

**Comment by rjharishabh** [comment]
What are you doing in this PR this should the PR title, not the issue number.
Mention the issue number in the PR description.

**Comment by rjharishabh** [comment]
Please make changes in the module files, do not override the template
You have just copied and pasted the template override code provided by @ChristineWk

**Comment by brianteeman** [comment]
The title of the pull request becomes the message in the commit log. So it must be clear what it refers to or no one will ever see it in the future. If you look at the list of commits you should see why it is important https://github.com/joomla/joomla-cms/commits/4.1-dev

**Comment by prakhar3062** [comment]
> Please make changes in the module files, do not override the template You have just copied and pasted the template override code provided by @ChristineWk

I took the idea from it as i don't get the idea where files are stored related to it but i will try to do with other possible way

**Comment by pritam825** [comment]
I have tested this item :red_circle: unsuccessfully on f93225abbedc7298949c1eac308a6145beda283c<br /><br />unsuccessfull, because on clicking the logout icon ,the dropdown open which is not the expected result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37165">issues.joomla.org/tracker/joomla-cms/37165</a>.</sub>

**Comment by richard67** [comment]
Meanwhile we have another pull request from another author which claims to solve the same issue: #37183 .

**Comment by ChristineWk** [comment]
I have tested this item :red_circle: unsuccessfully on f93225abbedc7298949c1eac308a6145beda283c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37165">issues.joomla.org/tracker/joomla-cms/37165</a>.</sub>

**Comment by C-Lodder** [comment]
FYI this is semantically incorrect. You cannot have interactive elements inside a `<button>`

**Comment by brianteeman** [comment]
As explained several times already this should not be an override

**Pull request closed without merging**
