### PR TITLE
Update loadmodule.php

### PR DESCRIPTION
**Pull request by nevigen**
We should use an utf8 compatible function for replacing

### CODE REVIEW

**Comment by ReLater** [comment]
Could you please provide detailed testing instructions (a use case where str_replace fails). Then people can test this change and see why this change is needed. Thank you! You need 2 successful tests by others before a pr cen be merged.

**Comment by nevigen** [comment]
substr_replace doesn't work correctly if we have a non-latin characters (characters which takes more than 1 byte, like cyrylic, etc) in our $article->text

**Comment by ReLater** [comment]
As I've said: Provide a reproducible use case, please, if you want to speed up testing. We not only have experts as testers here.

- Do that
- Do this
- Then do that
- See that it fails

- Apply patch
- Test again...

**Comment by Fedik** [comment]
If you use `Joomla\String\StringHelper::substr_replace()` because `substr_replace()` fail with UTF-8, then you also should use `Joomla\String\StringHelper::strlen()` instead of `strlen()`, in same reason.

And as @ReLater said, the test instruction are required.

**Comment by infograf768** [comment]
I wonder if we do not have other instances where this change would be welcome.

**Comment by richard67** [comment]
> If you use `Joomla\String\StringHelper::substr_replace()` because `substr_replace()` fail with UTF-8, then you also should use `Joomla\String\StringHelper::strlen()` instead of `strlen()`, in same reason.

@Fedik The same applies to `strpos()`, right?

**Comment by Fedik** [comment]
> The same applies to strpos(), right?

yeap

**Comment by richard67** [comment]
@nevigen Please apply the same change to `strlen` and `strpos` calls, otherwise the code still will not be utf-8 aware. And please provide some small easy testing instructions. Thanks in advance.

**Comment by richard67** [comment]
Added the "Updates Requested" label due to necessary changes mentioned in my previous comment.

**Comment by SharkyKZ** [comment]
If this is really causing issues, use `preg_quote()` approach proposed in https://github.com/joomla/joomla-cms/pull/21948. utf8 functions are very slow.

**Comment by SharkyKZ** [comment]
Would be nice to have unit tests for this plugin. But first we really need testing instructions.

**Pull request closed without merging**
