### PR TITLE
[4.0] Media Manager strings

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects one string to be in en-GB

Removes an unused string

Simplifies another string (see screenshots)

### Before
image

### After
image

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 23ddcd8e04208d7ae267f779b9b6dda9823048ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31607">issues.joomla.org/tracker/joomla-cms/31607</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 23ddcd8e04208d7ae267f779b9b6dda9823048ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31607">issues.joomla.org/tracker/joomla-cms/31607</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31607">issues.joomla.org/tracker/joomla-cms/31607</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
