### PR TITLE
Forward port of the output buffering check fix to 3.9

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #19033 & #19611 

### Summary of Changes

In case `output_buffering` is set to `Off` we should show it set off currently we show it to be enabled.

### Testing Instructions

review. As i can't remember how to trigger this page. But it is just a forward port of the same code used in the 3.8 PR.

### Expected result

Showed as off

### Actual result

showed as on

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
@zero-24 shouldnt this be against the 3.9 branch and not staging?

**Comment by zero-24** [comment]
Yes thanks @brianteeman fixed

**Comment by zero-24** [comment]
I have just implemted that changes provided by @ggppdk from here #19784

**Comment by ggppdk** [comment]
Should be like PR for staging branch
`(int) ini_get('output_buffering') !== 0`

**Comment by zero-24** [comment]
Fixed.

**Comment by zero-24** [comment]
@wilsonge as this is just a forward port of the 3.8 change (https://github.com/joomla/joomla-cms/pull/19791) can you consider merging this on review?

**Pull request merged**
