### PR TITLE
[4.0] tinymce plugin missing string [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes an untranslated string

### Testing Instructions
code review
or
open the plugin with language debug enabled

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b2cc6dde66a6f75caf33cc8c3d1b9bd63fc6c03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29972">issues.joomla.org/tracker/joomla-cms/29972</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5b2cc6dde66a6f75caf33cc8c3d1b9bd63fc6c03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29972">issues.joomla.org/tracker/joomla-cms/29972</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29972">issues.joomla.org/tracker/joomla-cms/29972</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
