### PR TITLE
[5.x] SQL field plugin

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Adds the ability to have a header in the generated dropdown list as per the documentation https://docs.joomla.org/SQL_form_field_type

### Testing Instructions
Create an sql custom field with a simple query eg select a.id as value, a.title as text from uajp8_content as a

### Actual result BEFORE applying this Pull Request
Open an article and check the new field - it will be a dropdown list with the first item in the list displayed.
As a result when you save the article that first item will be saved and will therefore be displayed on the front end.

### Expected result AFTER applying this Pull Request
There is now an additional param in the field called Header
You can use this to add a header to the dropdown list that has no value eg "- Select something -"
Open an article and check the new field - it will be a dropdown list with the first item in the list being the content you entered in the header field.
As a result when you save the article the field will have no value and will therefore not be displayed on the front end.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc0dbb2e7116e7983ed92375eba73633c7884764<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41122">issues.joomla.org/tracker/joomla-cms/41122</a>.</sub>

**Comment by brianteeman** [comment]
Would be great to get some testers here as there were a lot of people asking for this field

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
