### PR TITLE
[4.0] Fix for com_config

### PR DESCRIPTION
**Pull request by yvesh**
Pull Request for Issue #16682 .

### Summary of Changes

Fixes in the folder structure for the namespaced MVC 

### Testing Instructions

Check that com_config is working in frontend and backend

### Expected result

com_config is working on all operating systems

### Actual result

com_config is not working on Windows / Mac

### CODE REVIEW

**Comment by laoneo** [comment]
Nice one! Good work.

**Comment by infograf768** [comment]
Confused.
The files that were not indexed in the original Issue are not deleted in this patch when I apply it in Eclipse.
The new folder `Field` is not created either.

I get this:
screen shot 2017-06-15 at 11 39 13

**Comment by yvesh** [comment]
@infograf768 hmph looks like git is not able to update that correctly :( when you do a clean clone is it working?

**Comment by infograf768** [comment]
Cloning from your repo would be useless I guess.
I guess I better wait this is merged (if someone can test it first) and then see if I can update from upstream branch correctly. Otherwise I would have to re-create a project on my workspace for Eclipse.

**Comment by Bakual** [comment]
It will be interesting anyway what happens after this is merged when updating using the Joomla Update component.

**Comment by yvesh** [comment]
@Bakual yep, we need an pre-fllight script in many areas.. it's not only com_config :/

**Comment by wilsonge** [comment]
There's definitely an update issue to solve. But let's get this merged so people downloading fresh copies of J4 can actually run things

**Comment by infograf768** [comment]
FYI, I had to reclone my repo here. Could not get it to update through eclipse/egit

**Comment by infograf768** [comment]
and this https://github.com/joomla/joomla-cms/issues/16709

**Comment by Bakual** [comment]
SmartGit does show it funny:
image
Renaming the folder manually fixed it.

**Pull request merged**
