### PR TITLE
[4.0] s/send/sent

### PR DESCRIPTION
**Pull request by brianteeman**
Grammar correcttion

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d048bb477ca8826697297fcffd64b2a794ab38f2<br /><br />I'd merge this by review, but since the human tests have been made required in the 4.0-dev branch in the CI checks, it would need a forced merge and I don't have the privilege for that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35957">issues.joomla.org/tracker/joomla-cms/35957</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on d048bb477ca8826697297fcffd64b2a794ab38f2<br /><br />Sentence is now correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35957">issues.joomla.org/tracker/joomla-cms/35957</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35957">issues.joomla.org/tracker/joomla-cms/35957</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35957">issues.joomla.org/tracker/joomla-cms/35957</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
thanks - now if only my other  rtc pr were merged I would be a happy birthday boy

**Comment by richard67** [comment]
Oh, happy birthday then.

**Pull request merged**
