### PR TITLE
[com_tags] use the same visual level structure as categories

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR does for tags, the same visual change in the tree structure as done for categories (in https://github.com/joomla/joomla-cms/pull/10213).
##### Before

image
##### After

image
#### Testing Instructions
1. Use latest staging
2. Apply patch
3. Go to Component -> Tags and create a tag structure with 3 or more levels.
4. Check the visual of the tree structure is the same as the image in "After"

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on c13f53a52200253ee27c8bff0b764acd783cf9e8<br /><br />Great - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10526">issues.joomla.org/joomla-cms/10526</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c13f53a52200253ee27c8bff0b764acd783cf9e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10526">issues.joomla.org/joomla-cms/10526</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on c13f53a52200253ee27c8bff0b764acd783cf9e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10526">issues.joomla.org/joomla-cms/10526</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10526">issues.joomla.org/joomla-cms/10526</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva!

**Pull request merged**
