### PR TITLE
[bug][34004] Correct icon-ban-circle

### PR DESCRIPTION
**Pull request by Sophist-UK**
Also removing unnecessary ico-file-remove definition which is redefined a few lines below.

### CODE REVIEW

**Comment by josien** [comment]
Could you please add some test instructions for this issue, and update this PR for current staging? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4020">issues.joomla.org/joomla-cms/4020</a>.</sub>

**Comment by Sophist-UK** [comment]
Test instructions:

1. Create a test page with HTML that displays the icon-ban-circle icon e.g. `<i class="icon-ban-circle"></i>Icon-ban-circle`.

2. View this page prior to implementing this fix - should be a minus sign without a circle around it.

3. Implement this fix.

4. View the page after implementing this fix and it should be a minus sign with a circle around it (as the name suggests).

(I cannot quite believe I have been asked to define a test case for something this obvious. I cannot quite believe that a change this trivial has taken 7 months for someone to do something about.)

**Comment by roland-d** [comment]
> I cannot quite believe I have been asked to define a test case for something this obvious.
> I cannot quite believe that a change this trivial has taken 7 months for someone to do something about.

There might just be a correlation there. We require at least 2 tests per tracker item, when an item has no test instructions, a good chance it won't get tested. As for the 7 months, now you see why we have PBF events, to tackle these kind of things and in the future hopefully not have such old PRs floating around.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4020">issues.joomla.org/joomla-cms/4020</a>.</sub>

**Comment by a-fusion** [comment]
Patch works fine!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4020">issues.joomla.org/joomla-cms/4020</a>.</sub>

**Comment by waader** [comment]
Works, thanks!

**Pull request merged**
