### PR TITLE
Remove colons in user profile labels

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Make labels consistent without colons.
userprofile

### Testing Instructions
Enable User - Profile plugin

In backend, edit a user.
Go to User Profile tab.
View labels.

In frontend, log in.
Click Your Profile link.
View labels under User Profile section.
Click Edit Profile button.
View labels under User Profile section.

### Expected result
Colons removed from labels.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d92ef5caf839a20af03d5a4cd3190fb0d83b63d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14882">issues.joomla.org/tracker/joomla-cms/14882</a>.</sub>

**Comment by dam-man** [comment]
I have tested this item :white_check_mark: successfully on d92ef5caf839a20af03d5a4cd3190fb0d83b63d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14882">issues.joomla.org/tracker/joomla-cms/14882</a>.</sub>

**Comment by brienties** [comment]
I have tested this item :white_check_mark: successfully on d92ef5caf839a20af03d5a4cd3190fb0d83b63d9<br /><br />Test succesfull<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14882">issues.joomla.org/tracker/joomla-cms/14882</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
