### PR TITLE
[4.0] installation with postgresql

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24740

### Summary of Changes
fix sql for postresql

### Testing Instructions
install with postgresql

### Expected result
able to install

### Actual result
unable to install

### CODE REVIEW

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on dc07ecaed132c930f435de0bec502123b3f89d2a<br /><br />Thanks @alikon !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24747">issues.joomla.org/tracker/joomla-cms/24747</a>.</sub>

**Comment by alikon** [comment]
@twister65  thanks to you for your work on https://github.com/joomla-framework/database/pull/151

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dc07ecaed132c930f435de0bec502123b3f89d2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24747">issues.joomla.org/tracker/joomla-cms/24747</a>.</sub>

**Comment by alikon** [comment]
thanks for testing
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24747">issues.joomla.org/tracker/joomla-cms/24747</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by alikon** [comment]
@wilsonge please keep an eye on #24319 and #24148 are both related to postgresql

**Pull request merged**
