### PR TITLE
[4.0] Mail Templates language files

### PR DESCRIPTION
**Pull request by brianteeman**
Adds support for component language files located in the component folder not the languages folder

Pull Request for Issue #36462 .

See original issue for test instructions and sample component

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1154bfc1ccb3af37322c72c684adb9b28f2a1a0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36463">issues.joomla.org/tracker/joomla-cms/36463</a>.</sub>

**Comment by ChristineWk** [comment]
result
screen shot 2021-12-28 at 12 33 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36463">issues.joomla.org/tracker/joomla-cms/36463</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 1154bfc1ccb3af37322c72c684adb9b28f2a1a0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36463">issues.joomla.org/tracker/joomla-cms/36463</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36463">issues.joomla.org/tracker/joomla-cms/36463</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks - hope you will merge some of the older RTC pull requests

**Pull request merged**
