### PR TITLE
[4.0] update available

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #33694 .

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman I just see that the issue was about the red colour, so the "Pull Request for Issue #33694 ." in the description might be misleading, since this PR doesn't solve the colour (of which I think it should not be solved, but that's another question).

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f1a809b343112c8b2220d489e79012a69ef62afd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33706">issues.joomla.org/tracker/joomla-cms/33706</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on f1a809b343112c8b2220d489e79012a69ef62afd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33706">issues.joomla.org/tracker/joomla-cms/33706</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33706">issues.joomla.org/tracker/joomla-cms/33706</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
