### PR TITLE
[com_fields] - fix field group sort order error

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #14573 .

### Summary of Changes
fix field group sort order error

### Testing Instructions

> Open fields and compare the order of the Sort table filters with the order of the columns and they all work

### Expected result
no errror

### Actual result

 

> A sort filter for Field Group appears at the end of the list and without an Ascending or Descending selector
> 
> A sort filter for Field Group also appears in the correct place in the list but again without Ascending or Descending selectors
> 
> In addition if you select either of these two selectors you will get an error message
> 
> Unknown column 'category_title' in 'order clause'

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on a603795eaeaf3286f0d75e1e3b6576e947d63570<br /><br />`Field Group ascending` and `Field Group descending` don't sort different Field Groups
`Field Group` at End of List is shown<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by alikon** [comment]
can you retest 

> Field Group ascending and Field Group descending don't sort different Field Groups

**Comment by franz-wohlkoenig** [comment]
bildschirmfoto 2017-03-19 um 09 05 11

**Comment by alikon** [comment]
sorry i've forgot to push a file 
can you retest please :flushed:

**Comment by franz-wohlkoenig** [comment]
fetched Data in Patchtester, same Error is shown.

**Comment by alikon** [comment]
1 momemt let me recheck

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on aa6d38048cd34801712af0568de67d0074de7d35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by alikon** [comment]
@franz-wohlkoenig  is ok now

**Comment by franz-wohlkoenig** [comment]
@alikon fetched Data in Patchtester, same Error is shown. Reverting PR no Error.

**Comment by tonypartridge** [comment]
@franz-wohlkoenig did you update your patch tester? It may only be pulling original pull.

**Comment by franz-wohlkoenig** [comment]
@tonypartridge Patchtester: 1. Reset 2. Fetch Data; clear Browser Cache.

**Comment by tonypartridge** [comment]
Can you double check you have the latest staging and also please check Database from Extensions -> Database -> fix.

**Comment by franz-wohlkoenig** [comment]
@tonypartridge All done, same Error.

**Comment by tonypartridge** [comment]
@franz-wohlkoenig I just re-applied the patch tested it working.

Articles -> Fields -> Sort by Group Ascending && Descending both working fine, same with column clicking.

Can you try a new Joomla! install completely? a clone of the 37 repo staging, and then install the patch tester and test?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on aa6d38048cd34801712af0568de67d0074de7d35<br /><br />next Time restart Firefox earlier.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by infograf768** [comment]
I have an issue here, although the sorting works:
The small arrow usually displayed in the heading of the columns when sorting is not present.
screen shot 2017-03-21 at 17 06 08
compared to field groups list and other managers where it displays fine:
screen shot 2017-03-21 at 17 08 10

**Comment by normanmm** [comment]
I have tested this item :red_circle: unsuccessfully on aa6d38048cd34801712af0568de67d0074de7d35<br /><br />Sorting works for all columns , including Field Group ( also if the filter is done applying the filter from the filters list at the right) but no sorting arrows are displayed , for any column.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7df059b8162f328682581426937c61f84f4451b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by alikon** [comment]
fixed the small arrow :arrow_up_down:

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 7df059b8162f328682581426937c61f84f4451b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by brianteeman** [comment]
RTC?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14743">issues.joomla.org/tracker/joomla-cms/14743</a>.</sub>

**Comment by Quy** [comment]
No sorting arrow in the Languages column under Fields and Field Groups. Tested with clean install of the latest staging.

**Comment by infograf768** [comment]
@Quy Making PR now

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/14983

**Pull request merged**
