### PR TITLE
In com_tags, a tagged element's text-variable is transformed into nul…

### PR DESCRIPTION
**Pull request by svenbluege**
Deprecation messages are shown for some tagged elements: 
image

### Summary of Changes
In com_tags, a tagged element's text-variable is transformed into null if the value is empty. 
That causes deprecation messages in plugins like loadmodules and emailcloak. They usually don't need to check for null values in $article->text. 

### Testing Instructions

1. configure PHP to show deprecation messages
2. create a new contact using com_contact: just enter a name and tag it with "testtag"
3. open the frontend /index.php?option=com_tags&view=tags
4. click on the new tag 'testtag'.
5. see the deprecation messages.

### Actual result BEFORE applying this Pull Request

Following the test instructions, deprecation messages are shown

### Expected result AFTER applying this Pull Request

Following the test instructions, deprecation messages are now shown

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by svenbluege** [comment]
This issue was fixed with the same code in 4.2.7, I'm missing the change in 4.3. Here is my try to add it to 4.3 again. 
Original PR which was included in 4.2.7: https://github.com/joomla/joomla-cms/pull/39640

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 548adf283a1c34c73fd228f11cdc0a8ad3a67bee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40048">issues.joomla.org/tracker/joomla-cms/40048</a>.</sub>

**Comment by Quy** [comment]
@obuisard This was missed in the upmerge. Should be ok to merge without an additional test.

**Comment by obuisard** [comment]
Thank you Sven @svenbluege for the PR!

**Pull request merged**
