### PR TITLE
Fix bug in AJAX smart search with Cyrillic words (#31532)

### PR DESCRIPTION
**Pull request by Avalon18**
Bug in AJAX smart search with Cyrillic words (#31532)

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2dfe3280e6dd7cef3d5fa46d68b698e8e29dfc2d<br /><br />Issue concerns all non-latin characters.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31533">issues.joomla.org/tracker/joomla-cms/31533</a>.</sub>

**Comment by infograf768** [comment]
After patch, looking for the Greek term `ἀγορά` by entering `ἀγο`, it works fine.

Screen Shot 2020-11-30 at 10 43 26

Thanks @AlexeyGal !!

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2dfe3280e6dd7cef3d5fa46d68b698e8e29dfc2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31533">issues.joomla.org/tracker/joomla-cms/31533</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31533">issues.joomla.org/tracker/joomla-cms/31533</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by HLeithner** [comment]
Thanks @AlexeyGal for you first Joomla pull request!

**Pull request merged**
