### PR TITLE
[4.0] npm update

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes all the useless issues that were created. It was quicker to fix than to post 30 issues.

PS as I have said before and put on the road to beta issue #27812  there needs to be a policy and procedure for this

Pull Request for Issue # far too many to list .

### CODE REVIEW

**Comment by HLeithner** [comment]
Creating the PR is not the problem you should also write a proper testing description and at least check the release notes of the upstream packages for any b/c

looking at https://jquery.com/upgrade-guide/3.5/ you there some.

Many upstream packages (doesn't matter if composer or npm) doesn't follow semver or as bad as we sometimes on b/c breaks. So doing a code review is often the first thing to do if you can't trust the upstream maintainer.

**Comment by brianteeman** [comment]
>  if you can't trust the upstream maintainer.

Then we should not be using their code

**Comment by HLeithner** [comment]
> Then we should not be using their code

true

**Comment by C-Lodder** [comment]
@brianteeman I'm creating issues to make a point. I've said several times this task should not be done manually and instead a bot should check daily for outdated deps and create a PR. The PR can then be tested, just like it would be human created PR.

The use of a bot was somewhat frowned upon, yet nobody bothers to update these dependencies.

**Comment by brianteeman** [comment]
Which is why I put it on the Road to Beta issue

**Comment by C-Lodder** [comment]
Yes, over 3 months ago, yet nothing has been done about it and you wouldn't have needed to create this PR

Only takes one of the maintainers a minute to activate a bot on the repo.

**Comment by HLeithner** [comment]
Doesn't solve the problem that testers doesn't know what to test.

**Comment by brianteeman** [comment]
We have to accept that not every issue can be tested by everyone

**Comment by zero-24** [comment]
> Doesn't solve the problem that testers doesn't know what to test.

Well what about adding a bot comment by the issue tracker that adds that test instructions?

**Comment by brianteeman** [comment]
@zero-24 I think Harald was referring to the fact that I did not write test instructions

**Comment by zero-24** [comment]
Ah ok. :-)

**Comment by HLeithner** [comment]
A bot wouldn't write test instructions either

**Comment by zero-24** [comment]
Our bot can check what package is updated and than throw in some default test instructions. Sure it cant parse the change log etc but some basic test instructions can be generated when this is the only concern regarding not using the auto update bot.

**Comment by zero-24** [comment]
In the end an maintainer has to take a look into the PR anyway. So when there is something special to test in the change log that can be raised and moved back to pending.

**Comment by brianteeman** [comment]
Closing as by the time someone looks at it it will be out of date

**Pull request closed without merging**
