### PR TITLE
[4.3] Guided Tours replace deprecated access of input property

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Apply changes from #39029 for guided tours

### Testing Instructions

- save a tour
- open tour edit form
- open step edit form
- check module (mod_guidedtours)

### Actual result BEFORE applying this Pull Request

Use of deprecated access to the application's input property

### Expected result AFTER applying this Pull Request

All works like before, but without using deprecated access to the application's input property

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 3a45fa7c75b707344a34cf918404f868220e5bd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40305">issues.joomla.org/tracker/joomla-cms/40305</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3a45fa7c75b707344a34cf918404f868220e5bd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40305">issues.joomla.org/tracker/joomla-cms/40305</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40305">issues.joomla.org/tracker/joomla-cms/40305</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for the PR :-)

**Pull request merged**
