### PR TITLE
[com_actionlogs] Fix plugin links

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #23841 .

### Summary of Changes

Pass `$urlVar` parameter to `getContentTypeLink()`.

### Testing Instructions

Unpublish/publish a plugin
Return to control panel and see the message in the Action Log module
Follow the link

### Expected result

com_plugins opens with the specified plugin open for editing

### Actual result

com_plugin opens at the list

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Ruud68** [comment]
I have tested this item :white_check_mark: successfully on 4ed12fbafdf933cbf87b1bccf7947632b1a06aef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23857">issues.joomla.org/tracker/joomla-cms/23857</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 4ed12fbafdf933cbf87b1bccf7947632b1a06aef<br /><br />Tried to publish, unpublish, save modules, plugins, articles, all works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23857">issues.joomla.org/tracker/joomla-cms/23857</a>.</sub>

**Comment by jeckodevelopment** [comment]
@SharkyKZ can you please sync the branch?

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23857">issues.joomla.org/tracker/joomla-cms/23857</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
