### PR TITLE
[4] Change link to Joomla News

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/33017

## Steps to reproduce the issue

Go to the Administrator login page. At the bottom left there is a link to Joomla! News - try it.

## Expected result

Joomla news page

## Actual result

Joomla main page

Screenshot 2021-04-07 at 22 47 08

### CODE REVIEW

**Comment by Quy** [comment]
Please update the SQL files.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 37e7d2ff27c64db574d92557d9a25e3a16eb41e8<br /><br />Note for testers: apply the patch; then go to the Login Support Information (Admin) module and clear the News URL field. Save and it is repopulated with the new default url. Save again. Then logout and check the Joomla News URL on the Login page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33058">issues.joomla.org/tracker/joomla-cms/33058</a>.</sub>

**Comment by PhilETaylor** [comment]
Links now updated in the SQL files.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on f4bbeb596ce00c7841ba7066177124f44b789e33<br /><br />Am I right in thinking the sql changes are for new installations? Existing installations need to clear the newsurl field and save to restore the new default. Just wondering where/if to document that. Someone is bound to notice the problem and report it again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33058">issues.joomla.org/tracker/joomla-cms/33058</a>.</sub>

**Comment by PhilETaylor** [comment]
Joomla 4 "has not been released" so all installs will be "new installs" :-)

**Comment by richard67** [comment]
> Joomla 4 "has not been released" so all installs will be "new installs" :-)

That's not right. We grant that people can update from 4.0 Beta versions beginning with 1 to later Beta or RC and stable versions.

**Comment by richard67** [comment]
P.S.: Here in this PR an existing update SQL script (per db type) is modified, that's correct and needed when updating older versions.

Theoretically it would need also a new update SQL with a new date in file name so it runs when updating last Beta to next Beta which will include this PR, with "UPDATE" statements for changing the params (which is a varchar in database, not a json type, but contains json).

Practically we sometimes decide not to do that when it's risky to modify json params with "REPLACE" SQL statements.

Here it would not be risky because we could do an exact string match, so we replace `"news_url":"https://www.joomla.org/"` by `"news_url":"https://www.joomla.org/announcements.html"`. The search sting and the replace string have to cover the complete name and value pair of the json, including the double quotes, so we can be sure we don't replace other, similar parameter values.

The "WHERE" clause for such a replace statement should make sure that we only find relevant records
```
WHERE `module` = 'mod_loginsupport' AND `client_id` = 1 AND `params` LIKE '%"news_url":"https://www.joomla.org/"%'
```

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f4bbeb596ce00c7841ba7066177124f44b789e33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33058">issues.joomla.org/tracker/joomla-cms/33058</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33058">issues.joomla.org/tracker/joomla-cms/33058</a>.</sub>

**Pull request merged**
