### PR TITLE
[4.2] Check extension description exists Manage Extensions

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Check that there is an extension description before generating the tooltip when viewing the list of extensions in the Extensions Manage view

### Testing Instructions
Install an extension that does not have a description. For example https://joomla.digital-peak.com/download/dpattachments/dpattachments-5.1.3/dpattachments-free-5-1-3-zip?format=zip

Focus on the entry in the "name" column

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c8b20bdc4d2bbf153c01302143f91e1208bcd9d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39693">issues.joomla.org/tracker/joomla-cms/39693</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c8b20bdc4d2bbf153c01302143f91e1208bcd9d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39693">issues.joomla.org/tracker/joomla-cms/39693</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39693">issues.joomla.org/tracker/joomla-cms/39693</a>.</sub>

**Comment by fancyFranci** [comment]
Always good to check content. Thank you!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
