### PR TITLE
[4.3] addfavicon

### PR DESCRIPTION
**Pull request by brianteeman**
This code is not used by core so testing is by review

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

> Note: The shortcut link type is often seen before icon, but this link type is non-conforming, ignored and web authors must not use it anymore

This PR simply removes it. As it is ignored by the browsers there is no b/c issue

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by chmst — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1848b528730518ebcdbb103aba33819bfa70d8ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40735">issues.joomla.org/tracker/joomla-cms/40735</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 1848b528730518ebcdbb103aba33819bfa70d8ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40735">issues.joomla.org/tracker/joomla-cms/40735</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40735">issues.joomla.org/tracker/joomla-cms/40735</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Pull request merged**
