### PR TITLE
[4.0] Fix creating user with specific language

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes error when setting a language option  in new user form.

### Testing Instructions

Install 2 or more languages.
When creating a new user in backend select a language other than the default language in `Backend Language` field.
Save the user.

### Expected result

User is saved and receives an email in selected language.

### Actual result

>Call to undefined method Joomla\CMS\Language\Language::setLanguage() 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
Backend default language set to English.
Create a new user with French as default language
Before this patch I have another error than the one above.
`Call to a member function addLog() on bool `

EDIT: same after patch.

**Comment by SharkyKZ** [comment]
@infograf768 Not related. Please open a new issue.

**Comment by infograf768** [comment]
I can't test your PR because of that error.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0c3af5d7ee40f2a59ee91da34d9ef3a92f7e0889<br /><br />No more issue on J clean install. Works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26341">issues.joomla.org/tracker/joomla-cms/26341</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
