### PR TITLE
[4.0] com_fields Search [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
The Search field on the list of fields and field groups was missing a label.

The field also had a class that doesnt exist and was a remnant from j3

Code review and View generated source to check the search field has a real label and one that can be translated

### CODE REVIEW

**Comment by sksuryan** [comment]
So, I verified that the class is being removed but correct me if I wrong, the updated labels should come at the highlighted place right? If so, they aren't being shown here. 

image

**Edit:**
The problem seems to be in `layouts/joomla/searchtools/default/bar.php` at `line 42`.
https://github.com/joomla/joomla-cms/blob/e317fe221b00d67b9e72cc9c4a359e829f20830d/layouts/joomla/searchtools/default/bar.php#L42-L48

This condition seems to cause the issue.

**Comment by brianteeman** [comment]
The labels are deliberately not visible. Just because you dont display a label on the screen doesn't mean that you don't need to have a label on every input. This is very important for accessibility

**Comment by sksuryan** [comment]
I'm not asking why the labels are hidden, I understand that.

image

Take a look at the text of label, the correct text isn't being displayed and I think it's caused due to this particular code.


> **Edit:**
> The problem seems to be in `layouts/joomla/searchtools/default/bar.php` at `line 42`.
> 
> https://github.com/joomla/joomla-cms/blob/e317fe221b00d67b9e72cc9c4a359e829f20830d/layouts/joomla/searchtools/default/bar.php#L42-L48
> 
> This condition seems to cause the issue.

**Comment by brianteeman** [comment]
Sorry - I understand you know. I will submit a patch shortly

**Comment by sksuryan** [comment]
That's alright, my intention was just to help. Could have added a clearer screenshot though, will keep that in mind. 😄

**Comment by brianteeman** [comment]
So this PR is correct. What you have identified is a bigger possible issue effecting many components which I need to look at the reason for that code before proposing a solution in a separate PR

**Comment by sksuryan** [comment]
Yes, @brianteeman would you mind if I create an issue for this?

**Comment by brianteeman** [comment]
No need to create the issue - I will do a full PR when I get to the reasoning

**Comment by brianteeman** [comment]
I have looked back into the history and I cant see why the conditional statement was introduced back in #10090

**Comment by sksuryan** [comment]
I think it's there in case there isn't any label provided. The thinking may have been to check if any label was provided, in case there wasn't any, then to fallback to a standard "Search" label. But since this condition isn't proper, it keeps on falling back to the default. So, We would have to change that particular condition.

**Comment by brianteeman** [comment]
I suspect that at the time the code was introduced there were search fields that didnt have a label so this was a quick and dirty attempt to make sure they all got a label. In which case we can probably just kill the if statement as they all have a valid search label now.

**Comment by brianteeman** [comment]
Or just fix the condition so that it actually does what it was intended to do. Display the search label for the field and if there isnt one to fallback to the global string.

If you want to have a try at creating a PR for that then go for it

**Comment by sksuryan** [comment]
> 
> Or just fix the condition so that it actually does what it was intended to do. Display the search label for the field and if there isnt one to fallback to the global string.
> 
> If you want to have a try at creating a PR for that then go for it

Yes, I would love to! 
I think it's best if we have a fallback just in case a label isn't present.

**Comment by ceford** [comment]
Just noting that the label does not appear in the source and waiting for a bigger fix before testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32660">issues.joomla.org/tracker/joomla-cms/32660</a>.</sub>

**Comment by chmst** [comment]
@ceford #32660 and #32670 must be tested together.

**Comment by sksuryan** [comment]
@chmst I think this one would be ready to commit as soon as #32670 is merged which is RTC but haven't been merged yet.

**Comment by sksuryan** [comment]
I have tested this item :white_check_mark: successfully on 6e3a2c2d0804b4db0ab9dc5842a95f525d53b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32660">issues.joomla.org/tracker/joomla-cms/32660</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6e3a2c2d0804b4db0ab9dc5842a95f525d53b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32660">issues.joomla.org/tracker/joomla-cms/32660</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32660">issues.joomla.org/tracker/joomla-cms/32660</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
