### PR TITLE
Fix for fix #36345, TinyMCE, make sure iframe is fully loaded

### LINKED ISSUE #24343: (Subform)Repeatable editor blank after drag&drop reorder
### Steps to reproduce the issue
Create a new Field with type repeatable and add under form fields one field type Editor. Set options to be shown in a tab in article edit view. Create a new article go to the tab and add 2 rows. Write something in each editor field and save and reorder the rows.

### Expected result
After reordering the rows editor behavior is normal

### Actual result
After you release the mouse button after reordering the rows the editor field gets blank and uneditable but the content will be saved and after refresh loaded correctly.

### System information (as much as possible)
Linux apache php 7.2 and 7.3. Joomla 3.9.4. Editor JCE Pro and TinyMCE (joomla standard). Also tried it with a new clean cloud installation via launch.joomla.

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #36345 for fix #24343 

### Summary of Changes

Make sure the script listen iframe load event only once.

### Testing Instructions
Apply patch, run `npm install`

Create subform with editor (example in Custom HTML):
```xml
<field type="subform" name="subform" multiple="true" label="subform">
  <form>
    <field type="editor" name="text" label="editor" buttons="false"  default="I am a text!"/>
  </form>
</field>
```
Run test in Chrome and Firefox, and Safari (if you have one).

Make sure the Article content editor works correctly.

Then add couple rows in subform and try sort them. Then watch editor content.

### Actual result BEFORE applying this Pull Request
In Firefox the Article content editor realods itself, and not able to edit content.

### Expected result AFTER applying this Pull Request
In all Browsers the content editor works correctly.
Content in subform editor works after sorting.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
@Quy please test

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d4de355b21a9a15897c252b17b6af4c51473efe5<br /><br />Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39686">issues.joomla.org/tracker/joomla-cms/39686</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d4de355b21a9a15897c252b17b6af4c51473efe5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39686">issues.joomla.org/tracker/joomla-cms/39686</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39686">issues.joomla.org/tracker/joomla-cms/39686</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for fixing the fix :)

**Pull request merged**
