### PR TITLE
[4.0] - [workflow] fix undefined condition

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #21551 .

### Summary of Changes
remove

-  Notice:  Undefined property: stdClass::$condition in /var/www/html/j4dev/components/com_content/tmpl/category/blog_item.php 

-  Notice:  Undefined property: stdClass::$condition in /var/www/html/j4dev/components/com_content/tmpl/category/default_articles.php

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6890272a103ea3ef77d6a20898fc328e5d0ec0d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21621">issues.joomla.org/tracker/joomla-cms/21621</a>.</sub>

**Comment by alikon** [comment]
just discovered the same issue on default_articles.php.....(category List)  i'm going to add the fix on this pr

**Comment by alikon** [comment]
please test Category List too

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5b741a12ccb64c941bab34e8460c9f6390bbdffb<br /><br />Works on blog_item and default_articles.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21621">issues.joomla.org/tracker/joomla-cms/21621</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5b741a12ccb64c941bab34e8460c9f6390bbdffb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21621">issues.joomla.org/tracker/joomla-cms/21621</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21621">issues.joomla.org/tracker/joomla-cms/21621</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
