### PR TITLE
[4.0] Uncaught TypeError in mobile view if article is open

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #34330

### Summary of Changes

- Remove a class

### Testing Instructions

follow the issue instructions

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4892c7ece9c3ba45e22a00a955c35e817afe8c25<br /><br />Can also be tested without any emulator on a regular browser with a width of less than about 700px<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35011">issues.joomla.org/tracker/joomla-cms/35011</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 4892c7ece9c3ba45e22a00a955c35e817afe8c25<br /><br />Testen on Chrome with mobile layout.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35011">issues.joomla.org/tracker/joomla-cms/35011</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35011">issues.joomla.org/tracker/joomla-cms/35011</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
