### PR TITLE
[4.3] Typo

### PR DESCRIPTION
**Pull request by brianteeman**
Correct the spelling of __DEPLOY_VERSION__

needs to be merged before beta release or the script to insert the version will not work

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 90b19ef2b8976580b854c680cc5298307002a826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39798">issues.joomla.org/tracker/joomla-cms/39798</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 90b19ef2b8976580b854c680cc5298307002a826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39798">issues.joomla.org/tracker/joomla-cms/39798</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39798">issues.joomla.org/tracker/joomla-cms/39798</a>.</sub>

**Comment by laoneo** [comment]
Should we not hardcode it with the correct value?

**Comment by brianteeman** [comment]
No. Its new code so it is correct to be __DEPLOY_VERSION__ isn't it?

**Comment by laoneo** [comment]
Yes you are right it's on 4.3

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
