### PR TITLE
fix for html entity in title element RSS feed #40558

### PR DESCRIPTION
**Pull request by keewhip**
Pull Request for Issue #40558 .

Code modification as explained in issue #40558

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 040e006b85e720d30b7123caf0005a1097dcbc88<br /><br />Tested successfully in Joomla 4.3.2-dev of 28 May<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40559">issues.joomla.org/tracker/joomla-cms/40559</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 040e006b85e720d30b7123caf0005a1097dcbc88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40559">issues.joomla.org/tracker/joomla-cms/40559</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40559">issues.joomla.org/tracker/joomla-cms/40559</a>.</sub>

**Comment by obuisard** [comment]
Thank you @keewhip for the PR!

**Pull request merged**
