### PR TITLE
[4.0] Fix featured articles not shown in frontend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #28628.

### Summary of Changes

Corrects dates in query when saving featured article.

>### Testing Instructions
> Write an article, set is published and featured.
> Make a Featured blog.
> ### Expected result
> 
> The article is visible
> ### Actual result
> 
> The article is not visible in the featured blog, but in a normal categoy blog

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Drone reports PHPCS errors. Could you fix them?

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on e753b001dbd54c3ee7905c0d860b812cca034157<br /><br />Works for me. For future testers: Note that the problem only occurs when creating a new article on an installation that doesn't include this patch. If you once have saved the article with a feature up date or with this PR, it will always correctly stay featured (unless you unfeature it), because it is correctly saved in the database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28632">issues.joomla.org/tracker/joomla-cms/28632</a>.</sub>

**Comment by richard67** [comment]
Appveyor failure is a known issue not related to this PR, fix is in progress.

Drone PHPCS is ok now, other failure was maybe the randomly occuring issue, also not related to this PR ... just restarted drone, maybe we are lucky now.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e753b001dbd54c3ee7905c0d860b812cca034157<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28632">issues.joomla.org/tracker/joomla-cms/28632</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28632">issues.joomla.org/tracker/joomla-cms/28632</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
