### PR TITLE
[4.0] Correct obvious typo in libraries/cms/html/adminlanguage.php coming from PR #21240

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for new issue.

### Summary of Changes

Correct obvious typo "/oomla" instead of "Joomla" in libraries/cms/html/adminlanguage.php coming from PR #21240

### Testing Instructions

Code review.

### Expected result

Code correct.

### Actual result

Code incorrect.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman @wilsonge Please review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21276">issues.joomla.org/tracker/joomla-cms/21276</a>.</sub>

**Review by brianteeman — APPROVED** [review]
Mea culpa

**Comment by richard67** [comment]
Was the heat maybe ;-)

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
