### PR TITLE
[5.2] radio basic deprecate

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #42974

### Summary of Changes
Mark field and layout as deprecated

### Testing Instructions
CODE REVIEW

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 7f92c262ac01cb1f2b75e7672735a19e80ade4ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43860">issues.joomla.org/tracker/joomla-cms/43860</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7f92c262ac01cb1f2b75e7672735a19e80ade4ed<br /><br />Tested successfully in Joomla 5.2.0-alpha4-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43860">issues.joomla.org/tracker/joomla-cms/43860</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43860">issues.joomla.org/tracker/joomla-cms/43860</a>.</sub>

**Comment by Hackwar** [comment]
Can you please create a PR for the manual with the deprecation? Then I can merge this.

**Comment by brianteeman** [comment]
Doc https://github.com/joomla/Manual/pull/298

**Comment by Hackwar** [comment]
Thanks for this contribution!

**Comment by brianteeman** [comment]
thanks

**Comment by richard67** [comment]
@brianteeman Does this PR close issue #42974 ?

**Comment by brianteeman** [comment]
> Decision in the maintainer meeting we deprecate the field in 5.x and move it to the b/c plugin in 6.0 and remove it in 7.0.

This only deals with the deprecation

**Pull request merged**
