### PR TITLE
[4.0]When the screen is less than 992px wide, now hits and id are appearing

### PR DESCRIPTION
**Pull request by pritam825**
Pull Request for Issue #36758 .

### Summary of Changes
When the screen is less than 992px wide Hits and ID columns was disappearing but now it will appear

### Testing Instructions

go to content -> article -> do screen size less than 992px

### Actual result BEFORE applying this Pull Request

Hits and ID columns was disappearing 

### Expected result AFTER applying this Pull Request

now, Hits and ID columns are Appearing

### CODE REVIEW

**Comment by pritam825** [comment]
@richard67  Build is failing, will it create any problem for testing, or will i have to fix this?

**Comment by richard67** [comment]
> @richard67 Build is failing, will it create any problem for testing, or will i have to fix this?

@pritam825 The failing build is not related to your PR, it's a general problem we currently have in the 4.x-dev branches and on which we are already working. So nothing to do or to fix for you, just stay patiend and wait for 2 human testers 😄

**Comment by pritam825** [comment]
@richard67 oh ok thanks, I got tensed after seeing that build is failing 😄, now, I am fine thanks  :)

**Comment by brianteeman** [comment]
same comment as #36771

**Comment by richard67** [comment]
@brianteeman Well, here we had an issue, #36758 . But of course still not really a necessary fix.

**Comment by brianteeman** [comment]
Just because an issue is reported doesn't mean it is correct.

**Comment by richard67** [comment]
Sometimes they are a matter of taste, one sees an issue, another one not. I don't think I always have the wisdom to decide alone what is what, so sometimes I am waiting for opinions.

**Comment by pritam825** [comment]
oh ok sorry, I thought it was issue, so I have changed according to the problems

**Comment by pritam825** [comment]
> Just because an issue is reported doesn't mean it is correct.

yes right, now will I have to close this pr?

**Comment by pritam825** [comment]
I thought this was the problem, when doing screen size less than 992px , right scroll is not coming, because of that we were not be able to see the hits and it.
Screenshot (1909)

so I have solved this in this manner, so that right scroll comes, we will be able to see
Screenshot (1910)

@richard67 sir, @brianteeman sir sorry for disturbing you again, can you please confirm this, if you feel it wasn't problem  I will close the PR, Thanks in Advance .

**Comment by Ravi-chandra69** [comment]
I have tested this item :white_check_mark: successfully on c229987467c73930ad5d8361e5dd7d59866f1427<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36767">issues.joomla.org/tracker/joomla-cms/36767</a>.</sub>

**Comment by pritam825** [comment]
Screenshot (1935)

after the pr and right one is showing before the pr, the advantage is that after the pr hits and ID are also appearing , Can I please get some feedback, Thanks in advance

**Comment by brianteeman** [comment]
Which one looks broken to you?

For me the one on the left looks broken and I can guarantee someone will report that as broken.

**Comment by pritam825** [comment]
sir, I am not able to find any broken  thing in this, can you please tell, which part of the left, you have found broken, so That I will work accordingly.

**Comment by brianteeman** [comment]
image

**Comment by pritam825** [comment]
> image

before the pr it's still showing the same break , 
image before the pr ->
Screenshot (1950)
after the pr->

Screenshot (1953)

**Comment by Quy** [comment]
The solution is not to display many/more columns at smaller viewports. On an iPad, it will try to show all the columns by zooming out thus displaying everything smaller where you have to zoom in and swipe left and right making it a bad UX or the extra margin/space on the right as reported earlier. 

I would say leave it as it. Try viewing in landscape to see these columns.

**Comment by brianteeman** [comment]
This should be closed. j4.2 now has more fine grained user control of which columns to be displayed

**Pull request closed without merging**
