### PR TITLE
Remove Hathor template from Joomla!

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #15079 .

### Summary of Changes
The Hathor administrator template overrides are not maintained since long and as a consequence it now appears completely broken in J3.7. Attempts should have been made to fix the issues but its a long list to do. We are not even sure if even someone is still using it.

Therefore, I propose to remove this from Joomla as it is not in a usable state anyway.

However, if we can still fix it I am all in to my part of contribution and help it stay here until we have 4.0 at least.

**Delete files is not implemented in update script to not remove Hathor during upgrades. However, I think it would still be unusable.** A post-install message should work as suggested in the RFC.

### Testing Instructions
Install and test that everything works fine. No traces of Hathor should be visible anywhere, especially in Template Manager and Extensions Manager.

### CODE REVIEW

**Comment by laoneo** [comment]
I trust you that all the files do get removed with this pr. But is there something planed to inform the web site owner? We must do that properly, just removing the template is not an option IMO.

**Comment by mbabker** [comment]
As is, this won't remove the template from active sites.  Only new installs.

**Comment by brianteeman** [comment]
Which would actually be worse for existing users of hathor as the version in staging right now has several fixes

**Comment by rdeutz** [comment]
I checked what we can do and besides setting the default template to isis so that we don't break people sites and add a postinstall message we can't do so much. We could disable the harthor template on top (ahh close to ok) or remove the files entirely (are we looking for bad comments then ok).

**Comment by Bakual** [comment]
> so that we don't break people sites 

Actually, nothing breaks if you remove the files. It would fall back to the Isis template and show an error.

One argument against removing the files would be so people could save existing override files. Not sure if that is a possible issue with Hathor (doubt it honestly).
We could do the file removal within the postinstall message (using the action button would trigger uninstalling the template or directly remove the files).

**Comment by infograf768** [comment]
I guess we can close this now as Hathor would remain in 3.7.0 with a postinstall message:
https://github.com/joomla/joomla-cms/pull/15210

**Comment by izharaazmi** [comment]
What that message is supposed to say?

**Comment by zero-24** [comment]
> What that message is supposed to say?

I'm not sure what you message is supposed to say ;) There was a new PLT leadership decision that we keep hathor for 3.x (as it is allready removed from 4.0) but told any hathor users to not use this templates as it does not got any more support. So this PR "removing the template in 3.7" can be closed ;)

**Comment by rdeutz** [comment]
as @zero-24 said we will keep it till 4.0

**Comment by izharaazmi** [comment]
Well, that's fine. But please do not forget to tell the users that "current
features may also be broken" along with "...it does not got any more
support...". Or are we planning to fix those somehow?

**Comment by rdeutz** [comment]
> Or are we planning to fix those somehow?

If someone is bored, maybe ;-)

**Comment by zero-24** [comment]
Current message is: `TPL_HATHOR_MESSAGE_POSTINSTALL_BODY="Currently the Hathor administrator template style is set as your site default administrator template. Please note - any new features for Joomla will only be available with the Isis template. We recommend that you switch your default backend template style to Isis. You can do this by selecting the button below. This will only change the default site setting for the administrator template. It does not change the frontend template or any individual user settings.`

It may get changed but this is the current planed message we want to share ;)

**Comment by izharaazmi** [comment]
I suggest following actions to be added:

[Switch to Isis] [Switch to Isis and remove Hathor] [Hide this Message]

**Comment by zero-24** [comment]
Please check the PR mention by JM :smile: We can't remove hathor as it comes back (or atlease the changed files) with the next core update ;)

**Comment by izharaazmi** [comment]
>
>  as it comes back (or atlease the changed files) with the next core update
> ;)
>
If we are not going to be supported from now on, less chances for them to
come back :D

**Comment by zero-24** [comment]
Copyright Updates :P As well as we currently need to run the update with the Stable-Update_Package.zip wich IIRC includes any changes since 3.0 (I'm not 100% sure)

**Comment by izharaazmi** [comment]
Sorry! Stupid me! 🙈

**Pull request closed without merging**
