### PR TITLE
Adds current version to Extension Update Manager

### PR DESCRIPTION
**Pull request by ghost**
It is often useful to know what version of an extension you have installed before updating it to the latest version.
Currently the Extension Update Manager does not provide this information, making you to have to go search for it.
This PR fixes this.

Before:
before

After:
after

### CODE REVIEW

**Comment by brianteeman** [comment]
Please see #8350

**Comment by andrepereiradasilva** [comment]
Yes, already in https://github.com/joomla/joomla-cms/pull/8350
But from a usability point i think @nonumber background colors are helpful and would be a nice addon to https://github.com/joomla/joomla-cms/pull/8350

**Comment by 810** [comment]
Maybe also remove install type & folder & url details for UX

**Comment by brianteeman** [comment]
The url is important to ensure that you are not being tricked to go to an unauthorised domain

**Comment by 810** [comment]
does the "normal" user know that url. I believe its not to be needed there.

**Comment by brianteeman** [comment]
If the url for a kunena update was hackme.now they would want to know.

It is trivial to make that change in the current architecture so let's at
least make it visible.

**Comment by 810** [comment]
maybe a check with the jed. if ok see tick, else orange question mark. with tooltip with the url.

**Comment by brianteeman** [comment]
Feel free to contribute that code. Until it exists we must display the url

On 24 December 2015 at 12:41, Jelle Kok <notifications@github.com> wrote:

> maybe a check with the jed. if ok see tick, else orange question mark.
> with tooltip with the url.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8768#issuecomment-167105367>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment]
@test +1

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 6ccde61761e6d45af27e4908306407a51d4921eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8768">issues.joomla.org/joomla-cms/8768</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8768">issues.joomla.org/joomla-cms/8768</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks everyone!

**Pull request closed without merging**
