### PR TITLE
[4.3] guided tours inflector

### PR DESCRIPTION
**Pull request by brianteeman**
Removes
`use Joomla\string\inflector`

Symbol 'Inflector' is declared but not used
The use directive is unnecessary.

### Testing Instructions
hard to test when something that is not being used is removed.
a good ide will tell you if a use directive is not used

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by N6REJ** [comment]
@brianteeman how do you test this?

**Comment by brianteeman** [comment]
> @brianteeman how do you test this?

updated with test _instructions_

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c65c0117ffa33275607cec8506dad46d853e6ac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40453">issues.joomla.org/tracker/joomla-cms/40453</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c65c0117ffa33275607cec8506dad46d853e6ac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40453">issues.joomla.org/tracker/joomla-cms/40453</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40453">issues.joomla.org/tracker/joomla-cms/40453</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brian @brianteeman !

**Comment by brianteeman** [comment]
thx

**Pull request merged**
