### PR TITLE
[4.0] Fix search tools alignment

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix markup to make search tools alignment be right-aligned.

### Testing Instructions
Go to System > Information > Database
See search tools alignment.

### CODE REVIEW

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 875a7dc12dd41646482eb28b34a7326a4d9b6c8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33204">issues.joomla.org/tracker/joomla-cms/33204</a>.</sub>

**Comment by rjharishabh** [comment]
### Before this patch
db-before-patch

### After this patch
db-after-patch

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 875a7dc12dd41646482eb28b34a7326a4d9b6c8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33204">issues.joomla.org/tracker/joomla-cms/33204</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33204">issues.joomla.org/tracker/joomla-cms/33204</a>.</sub>

**Pull request merged**
