### PR TITLE
Move methods from JLanguage to JLanguageHelper

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Move all static methods that does not use JLanguage properties or methods from JLanguage to JLanguageHelper and deprecate the other ones.

- `JLanguage::exists()` -> `JLanguageHelper::exists()`
- `JLanguage::getMetadata()` -> `JLanguageHelper::getMetadata()`
- `JLanguage::getKnownLanguages()` -> `JLanguageHelper::getKnownLanguages()`
- `JLanguage::getLanguagePath()` -> `JLanguageHelper::getLanguagePath()`
- `JLanguage::parseLanguageFiles()` -> `JLanguageHelper::parseLanguageFiles()`
- `JLanguage::parseXMLLanguageFile()` -> `JLanguageHelper::parseXMLLanguageFile()`

### Testing Instructions

Mainly code review.
Apply patch - all works fine.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6cbb681503ef957784ef4e52722da76a0e89a1cf<br /><br />tested for a while did'nt discover any issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12953">issues.joomla.org/tracker/joomla-cms/12953</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@alikon just fisxed conflicts after https://github.com/joomla/joomla-cms/pull/12783 merge.
IMO you don't need to retest, if ok, please mark as tested ok again

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c2c6d4f38c6f5b3b69c7c1da7d793de24c6ea1e8<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12953">issues.joomla.org/tracker/joomla-cms/12953</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on c2c6d4f38c6f5b3b69c7c1da7d793de24c6ea1e8<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12953">issues.joomla.org/tracker/joomla-cms/12953</a>.</sub>

**Comment by jeckodevelopment** [comment]
@andrepereiradasilva can you please look at the conflicting file?

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment fixed conflicts

**Comment by zero-24** [comment]
Thanks :+1:

**Pull request merged**
