### PR TITLE
Bump sodium_compat

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Upgraded `sodium_compat` polyfill which fixes the issues with the polyfill on a 32-bit PHP build.

### Testing Instructions

No easy direct test so either use the API as documented in the tests or validate the tests pass.

### CODE REVIEW

**Comment by wilsonge** [comment]
Changes to the `autoload_classmap.php` seem slightly suspect?

**Comment by mbabker** [comment]
I have a feeling someone else has been manually removing those.  Because if you look at the `composer.json` for all packages at the versions we have they are not in the `autoload-dev` section.

**Comment by wilsonge** [comment]
Hmm looks like it was something to do with the optimizer??? https://github.com/mbabker/joomla-cms/commit/1fba80f7ab1ae5afa2cf670822d06ef19b43c3f4

**Comment by mbabker** [comment]
It has nothing to do with the optimizer.  I literally ran `composer install`, `composer update paragonie/random_compat`, `composer install --no-dev`.

The test classes have been in the namespace mapping for a while.  See https://github.com/joomla/joomla-cms/blob/3.7.5/libraries/vendor/composer/autoload_psr4.php

The fact that the test classes are being re-added to the class mapping files with this PR to me indicates manual removal at another point or someone is running a really goofy Composer command/configuration.

**Pull request merged**
