### PR TITLE
[4.0] Check in media field if image is set

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #35227.

### Summary of Changes
Media custom field checks if there is file set.

### Testing Instructions
- Create media custom field.
- Edit an article and open the fields tab.
- Set a description in the media field but NO image.
- Open the article on the front.

### Actual result BEFORE applying this Pull Request
The label of the custom field is shown with the description and an invalid image tag.

### Expected result AFTER applying this Pull Request
Nothing is rendered.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9ad7a3514d1646eca87947915cf11dd293d4a1dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35556">issues.joomla.org/tracker/joomla-cms/35556</a>.</sub>

**Comment by regularlabs** [comment]
Successfully tested here

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35556">issues.joomla.org/tracker/joomla-cms/35556</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
