### PR TITLE
[4] add missing import for exception

### LINKED ISSUE #31063: [4] 2 API controllers can throw a not found "Exception\ResourceNotFound"
### Steps to reproduce the issue

Code review.

Here: 
https://github.com/joomla/joomla-cms/blob/88c20731f66ca439ac8d62991b4974279e42387a/api/components/com_plugins/src/Controller/PluginsController.php#L58

And here: 
https://github.com/joomla/joomla-cms/blob/88c20731f66ca439ac8d62991b4974279e42387a/api/components/com_contenthistory/src/Controller/HistoryController.php#L81

We have an Exception of `Exception\ResourceNotFound` being thrown in the namespace `Joomla\Component\Contenthistory\Api\Controller`

Neither phpStorm or I can work our where this missing `Joomla\Component\Contenthistory\Api\Controller\Exception\ResourceNotFound` class is, or if its a mistake, what class should be used as the thrown exception.

### PR DESCRIPTION
**Pull request by PhilETaylor**
Closes #31063

### Summary of Changes

Add missing import so that `Exception\ResourceNotFound` is correctly resolved

### Testing Instructions

Code Review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5089f4b994223410769450b6467a853a77cccf1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31081">issues.joomla.org/tracker/joomla-cms/31081</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 5089f4b994223410769450b6467a853a77cccf1d<br /><br />Confirmed code change use matches call.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31081">issues.joomla.org/tracker/joomla-cms/31081</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31081">issues.joomla.org/tracker/joomla-cms/31081</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
