### PR TITLE
[4.0] Info not warning

### PR DESCRIPTION
**Pull request by brianteeman**
It really is not a warning to display "No matching results" that should have a class of alert-info.

There are also a few language strings that have been replaced with the generic "No matching results"

### Before
image

### After
image

### CODE REVIEW

**Comment by alikon** [comment]
make sense

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bd6ada07f23260382adc905aa93d90b4436b0ee4<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25023">issues.joomla.org/tracker/joomla-cms/25023</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd6ada07f23260382adc905aa93d90b4436b0ee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25023">issues.joomla.org/tracker/joomla-cms/25023</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25023">issues.joomla.org/tracker/joomla-cms/25023</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
