### PR TITLE
[4.0] Fix filters width

### LINKED ISSUE #29549: [4.0] Filter options in private messaging layout
### Steps to reproduce the issue

Click filter options in private messaging in admin 

### Actual result

Note the uber wide dropdown for a tiny field content

Screenshot 2020-06-09 at 21 44 37

### PR DESCRIPTION
**Pull request by Quy**
Fixes #29549

### Summary of Changes
Fix filters width.

Thanks @PixedBo for the code.

### Testing Instructions
Apply PR
Run npm i

Go to Private Messages
Click Filter Options

### Actual result BEFORE applying this Pull Request
Wide dropdown

### Expected result AFTER applying this Pull Request
Normal width dropdown

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7f2c31f38f63713bbcf50401059c00894d67828c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29777">issues.joomla.org/tracker/joomla-cms/29777</a>.</sub>

**Comment by PixedBo** [comment]
Tested and seems ok.
Please test also other pages with filters as this fix is for the whole filter system visualization

**Comment by infograf768** [comment]
Seems OK or works fine? I evidently have also tested other occurrences. Have you not?
To understand this PR look at https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/

**Comment by PixedBo** [comment]
Sorry, i was meaning "works fine". I've tested with windows browsers and mobile and found no problems. Can't test with linux, macOS or iOS as i don't have one. Thanks for the link, i know the difference as i've suggested the fix here #29549

**Comment by infograf768** [comment]
Please mark your test OK in https://issues.joomla.org/tracker/joomla-cms/29777

**Comment by PixedBo** [comment]
I have tested this item :white_check_mark: successfully on 7f2c31f38f63713bbcf50401059c00894d67828c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29777">issues.joomla.org/tracker/joomla-cms/29777</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29777">issues.joomla.org/tracker/joomla-cms/29777</a>.</sub>

**Comment by infograf768** [comment]
Tks both

**Pull request merged**
