### PR TITLE
[4.0] Move to Codesniffer version 2

### PR DESCRIPTION
**Pull request by wilsonge**
[CLEAR CACHE]

WIP on moving the CMS to the new codesniffer version

### CODE REVIEW

**Comment by wilsonge** [comment]
@rdeutz I'm going to need some help here for the docker image - I need the docker phpcs image to come with phpcs v2 (i think i need a composer install first - `dealerdirect/phpcodesniffer-composer-installer` in the composer package should deal with this - but presumably isn't there until after the prepare step)

**Comment by Hackwar** [comment]
I've been messing around with this a bit and these are my remarks:

- We have lots of errors with the new Sniffs. phpcbf seems to be able to fix most of those.
- I disagree with disallowing the short array syntax. Can we remove that again?
- We can use the system test docker image to run the phpcs check.

Should I create a PR against your branch to make the necessary changes?

While phpcbf creates a diff file, my patch executable fails pretty hard at applying that and then deletes that file. So I've not been able to apply those changes yet.

**Comment by wilsonge** [comment]
We can remove the short array stuff. This build was designed to run against the 3.x branch originally. Obviously in 4.x that changes. But that needs to go against the cms standards repo for now https://github.com/joomla/cms-coding-standards. Let's start by getting the tests running (i.e. using the system test docker image to run the phpcs check).

Until the backend template repo is in this repository I am not proceeding with this btw. it's going to cause far too many headaches. But we can get this at a point where we just need to apply the fixes

Rebased this to 4.0-dev today

**Comment by rdeutz** [comment]
lets use a smaller docker image the system test image is a pretty large one

**Comment by 810** [comment]
This one can be closed?

**Comment by ghost** [comment]
@810 which Reason for closing?

**Comment by Hackwar** [comment]
George and I did the switch with a series of 16 PRs yesterday.

**Comment by ghost** [comment]
@Hackwar mean this can be closed?

**Comment by wilsonge** [comment]
Yup

**Pull request closed without merging**
