### PR TITLE
Clearified the error message when no module is found

### PR DESCRIPTION
**Pull request by chmst**
The error message also appears when the module is installed but not published/created.

### CODE REVIEW

**Comment by brianteeman** [comment]
Where does this error message occur<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6551">issues.joomla.org/joomla-cms/6551</a>.</sub>

**Comment by brianteeman** [comment]
In the module manager if I do a search for modules that are not published they appear - see screenshot - so where are you seeing the need for this message

screen shot 2015-03-23 at 06 01 31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6551">issues.joomla.org/joomla-cms/6551</a>.</sub>

**Comment by chmst** [comment]
Try as for example the filter type for "user-login" or "who is online". See my screen. But you are righ. I'll try to find out why these modules are not found in the database.
module_manager

**Comment by brianteeman** [comment]
Ah I see what you mean now. You are correct the current string is wrong
"There are no modules installed matching your query"

That is wrong as it implies that the module is not installed on the site.
Where what it actually means is that you do not have an instance of a
module with a title that matches. If you look at the tooltip for the search
box it indicates that the search is a "search in module title"

The search is for the title of the module and not the type of the module.

The string does need changing but your suggestion is not correct.

Perhaps it should be something like
"There are no modules created on this site with a title that matches the
query"

I am not 100% happy with that but I think it better describes the scenario
and addresses the problem you correctly found

On 23 March 2015 at 13:18, chmst <notifications@github.com> wrote:

> Try as for example the filter type for "user-login" or "who is online".
> See my screen. But you are righ. I'll try to find out why these modules are
> not found in the database.
> [image: module_manager]
> <https://cloud.githubusercontent.com/assets/1035262/6780649/74419f36-d167-11e4-9f76-307bc3776deb.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6551#issuecomment-84993986>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Thinking about it I think the best string to match the expected behaviour of the search box would simply be
"There are no modules that match your query"

Thoughts? I can create the PR if you think that message is the clearest to match the expected behaviour of the search functionality on that page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6551">issues.joomla.org/joomla-cms/6551</a>.</sub>

**Comment by chmst** [comment]
Hi, thank you - thats better. I tried to find out why the query ist sometimes successful and sometimes it is not because it fails only for some types of modules. It has to do with dth client_id of the module. As for now - yes, please take your string for a PR, it is better than mine.

**Comment by brianteeman** [comment]
Thanks. Will create a PR shortly.

Regarding the client_id that is to be expected as there is always a filter applied in the module manager of either site or admin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6551">issues.joomla.org/joomla-cms/6551</a>.</sub>

**Comment by brianteeman** [comment]
See #6558<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6551">issues.joomla.org/joomla-cms/6551</a>.</sub>

**Comment by wilsonge** [comment]
Closing in favour of Brians

**Pull request closed without merging**
