### PR TITLE
Removed dead code

### PR DESCRIPTION
**Pull request by demis-palma**
I'm pretty sure that the method JUpdater::update() is dead code. It never ran and it never will.
It is supposed to "Finds an update for an extension", but this job is actually done by JUpdater::findUpdates() instead.
It also would cause a fatal error, since it contains a call to JUpdate::install(), which doesn't exists at all.

Despite comment reports "since 3.6.0", the method update() has been there for almost a decade, so I couldn't find out when it was introduced and why.

### CODE REVIEW

**Comment by zero-24** [comment]
The since tags are changed here: https://github.com/joomla/joomla-cms/pull/10196 for the reason that 3.5.2 was droped over 3.6.0

And the method itself comes from here: https://github.com/joomla/joomla-cms/commit/8880ed9d16bf97ced4543724b89cc5f33a2791d8

**Comment by zero-24** [comment]
Even if it is not used (need to be checked) as this is a public method that we IIRC can't remove it in 3.x.

**Comment by demis-palma** [comment]
I understand.
However, was there on 22 Oct 2008:
https://github.com/joomla/joomla-cms/blob/6a3da603a755b77db31b7cd98318545e36212632/libraries/joomla/updater/updater.php

**Comment by zero-24** [comment]
This PR: https://github.com/joomla/joomla-cms/pull/9612/files moved it and changed accidentally the since tag from `11.1` to 3.5.2 and later was moved to 3.6.0. So it looks like it is there from the initial commit. https://github.com/demis-palma/joomla-cms/commit/b0546089a5d3dfee4eed7e813d881c8d57ef85fd

**Comment by zero-24** [comment]
Correct. Just found the same. 😄

**Comment by mbabker** [comment]
If this is truly dead code we can merge this PR for 4.0.  We just need a PR deprecating the method first.

**Comment by zero-24** [comment]
@demis-palma can you send the removal PR against 4.0-dev than?

**Comment by wilsonge** [comment]
Changed this to point to 4.0 in GitHub and fixed the conflict. Merged into 4.0

**Pull request merged**
