### PR TITLE
Date format localise

### PR DESCRIPTION
**Pull request by brianteeman**
I noticed that in some places we are formatting the date manually eg
`<?php echo JHtml::_('date', $item->created_time, 'D d M Y H:i'); ?>
`

Or modifying the date format
`<?php echo JHtml::_('date', $item->track_date, JText::_('DATE_FORMAT_LC4') . ' H:i'); ?>
`

Or not specifying a date format 
`<?php echo JHtml::_('date', $this->item->date_time); ?>`

This PR corrects that so that 
 - [x] instead of hard coding the date we use an existing one OR the new DATE_FORMAT_LC6
 - [x] instead of modifying a date format we use an existing one that does the same thing
 - [x] a date format is always specified

This will ensure that ALL the dates can be localised in a consistent manner throughout Joomla

### CODE REVIEW

**Comment by Bakual** [comment]
Just a thought regarding the new `DATE_FORMAT_LC6`. Do we really need to show the seconds in com_contenthistory and com_users or would it be sufficient to just show the minute with the existing string `DATE_FORMAT_LC5`?
Imho the seconds don't add real value to the datetime, minutes would be enough to show.

**Comment by brianteeman** [comment]
@bakual perhaps not but i wanted to ensure full b/c

**Comment by Bakual** [comment]
It would be more consistent with other places were we also don't show the seconds and it would use a little less space. Also I don't think, showing the seconds is covered by our B/C promise :smile:

**Comment by brianteeman** [comment]
i just wanted to avoid anyone comments about changes - and get this simple pr merged without lots of silly debate. guess i failed

**Comment by Bakual** [comment]
Go ahead. If you think it's worth showing the seconds I wont question it further.

**Review by Bakual — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba4552720a85f826c5d8fc66eec6e1ebac4a3c62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19690">issues.joomla.org/tracker/joomla-cms/19690</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on ba4552720a85f826c5d8fc66eec6e1ebac4a3c62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19690">issues.joomla.org/tracker/joomla-cms/19690</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19690">issues.joomla.org/tracker/joomla-cms/19690</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
