### PR TITLE
[plg_content_vote|pagebreak] Load language files only when needed

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11714 (part 2).
### Summary of Changes

Only load the plg_content_pagebreak and plg_content_vote languages files when they are needed.
Example: don't load them if the show_vote is not active or there is no pagebreak class.

For more info see #11714
#### Reproduce
- Use latest staging
- Enable plugin content vote and plugin content pagebreak
- Enable debug and debug lang in global config
- Enable debug system plugin with all options activated
- Go to frontend and check the debug console
- Notice `JROOT/administrator/language/en-GB/en-GB.plg_content_vote.ini` and `JROOT/administrator/language/en-GB/en-GB.plg_content_pagebreak.ini` language file is loaded no matter what page you are (even in backend pages they are loaded).

image
#### Test patch
- Apply patch
- Repeat the steps above and checkthe two language files are NOT loaded (except when needed). 
- Check plugin work as before if language files are required to load (ex: show_vote enabled / article with pagebreak, etc).
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@mbabker i updated this PR to follow the logic you added for modules in https://github.com/joomla/joomla-cms/pull/11698, but this time for the plugins.

Can you check if all ok?

**Comment by mbabker** [comment]
Looks fine.

**Comment by andrepereiradasilva** [comment]
thanks

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3b028a3c3bdc7c5739c6e43b15fb34f3c295962b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11730">issues.joomla.org/joomla-cms/11730</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 3b028a3c3bdc7c5739c6e43b15fb34f3c295962b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11730">issues.joomla.org/joomla-cms/11730</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11730">issues.joomla.org/joomla-cms/11730</a>.</sub>

**Pull request merged**
