### PR TITLE
[4.0] Backendtemplate: Color of Logo-Letters 

### PR DESCRIPTION
**Pull request by angieradtke**
Pull Request for Issue # .

Not all Letters of the Joomla-Logo have  got the right color
### Summary of Changes

add Polyline-Color

### Expected result

Alle letters  of the Joomla-Logo should be white

### CODE REVIEW

**Comment by C-Lodder** [comment]
Styling for SVGs like this should not be done in the template CSS. They should be in the actual SVG file

**Comment by angieradtke** [comment]
why?

Am 23.02.2020 um 17:04 schrieb Lodder:

**Comment by richard67** [comment]
Before patch with this PR:
logo-1

After patch with this PR:
logo-2

So to me this PR looks ok.

@C-Lodder Do you think it is wrong?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f6330e519d82100a2d6a7faa35543f8040e094f3<br /><br />Works as shown in the screenshots in my previous comment.

@C-Lodder Please protest if PR is wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28034">issues.joomla.org/tracker/joomla-cms/28034</a>.</sub>

**Comment by brianteeman** [comment]
@c-lodder is correct

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28034">issues.joomla.org/tracker/joomla-cms/28034</a>.</sub>

**Comment by C-Lodder** [comment]
@richard67 @angieradtke Because users may want to use their own logo. Any SVG styling done in the template CSS could potentially affect their logo.

Keep the SVG styling in the SVG

**Comment by angieradtke** [comment]
If  s.b. changed the  header-bg- color to a lighter one, he needs a 
darker logo-color.
To make it more flexible  we can do it  in future like that:

svg path, svg polyline
{

fill: var(--atum-bg-light);

}

So what is the reason, to do it only in the svg- file ?

Am 23.02.2020 um 17:33 schrieb Brian Teeman:

**Comment by C-Lodder** [comment]
@angieradtke see above

**Comment by angieradtke** [comment]
hm -   in this case they can use a png or a jpg ?



Am 23.02.2020 um 17:55 schrieb Lodder:

**Comment by C-Lodder** [comment]
> hm -   in this case they can use a png or a jpg ?

Why prevent users from using basic vector logos?

Just move the styling to the SVG file and there won't be any issues.

**Comment by angieradtke** [comment]
this is a quick fix for now, missing l an d !  should be white . If we want we can change the svg later

**Comment by brianteeman** [comment]
whats the panic rush? Why fist it twice?

**Comment by angieradtke** [comment]
Maybe Brian you are familar with the logos.
Logo should be changed to  joomla-logo -white in the index.php.
I know that something with the logo will be done  in the js-Files.
I don't have a complete picture of these pendencies.

and  we should think about whether we should make the logo color 
configurable.


Am 23.02.2020 um 18:51 schrieb Brian Teeman:

**Comment by brianteeman** [comment]
Please test #28038

**Comment by angieradtke** [comment]
see #28038  helps

**Pull request closed without merging**
