### PR TITLE
Fix form submit in IE

### PR DESCRIPTION
**Pull request by Fedik**
fix for #5901

for test use #5901 description
#### Steps to reproduce the issue

Not sure if this is just me or if others are getting the same thing.

Using the beta of 3.4 from github on a Windows 7 - IE 10 VM.  Go to Article Manager and click new.  

It should go to a new article but on IE 10 it appears to be throwing a JS error.  

screen shot 2015-01-28 at 02 27 22

Other versions seem unaffected.
#### Expected result

Expected result would be opening a new article in Article Manager
#### Actual result

Actual result is a JS error and nothing happens.
#### System information (as much as possible)

Latest J3.4 download from Github.

### CODE REVIEW

**Comment by roland-d** [comment]
@test: Works as described. Before the patch I see the JS errors. After applying patch the New button works as expected and no more JS errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5914">issues.joomla.org/joomla-cms/5914</a>.</sub>

**Comment by Bakual** [comment]
IE11 and Chrome 40 work with and without PR. Thus works as expected.

**Comment by digitalgarage** [comment]
@test not sure if you had your second test for IE 10 yet .... but +1 works in IE 10 now as expected.

**Comment by brianteeman** [comment]
Thanks everyone - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5914">issues.joomla.org/joomla-cms/5914</a>.</sub>

**Comment by wilsonge** [comment]
@test replicated javascript error in ie10. applied patch and error was gone. Button still worked in chrome and ff latest versions.

**Comment by wilsonge** [comment]
Merged Thanks!

**Pull request merged**
