### PR TITLE
[4.0] Remove some more unused strings

### PR DESCRIPTION
**Pull request by brianteeman**
None of these strings are being used in J4

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9f0336073210b34a5a65f481f59635fe0ca2b87b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19275">issues.joomla.org/tracker/joomla-cms/19275</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9f0336073210b34a5a65f481f59635fe0ca2b87b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19275">issues.joomla.org/tracker/joomla-cms/19275</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
