### PR TITLE
Update _item.php

### PR DESCRIPTION
**Pull request by petrovicivan**
add intro image above title

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
~~This should be done as a template override and not in the core as it will change the layout of all existing sites. My 2c~~

**Comment by brianteeman** [comment]
~I retract my previous statement
There is a setting in the module to display the images but it is not used in the view - this pr corrects that
It wont have an effect on an existing site as the default value for the xml is for images to be off~

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 7d7af2f91bf1b6ccfc89ee1e22f434c37a79a3f7

Using "Modules: Articles - Newsflash", Category "Joomla", select on Tag which calls one Article and 
applied PR got:
bildschirmfoto 2018-01-23 um 13 53 56
### System information
- 3.8.4-rc
- Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
- Template: Protostar
- macOS Sierra, 10.12.6
- Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19437">issues.joomla.org/tracker/joomla-cms/19437</a>.</sub>

**Comment by ReLater** [comment]
> There is a setting in the module to display the images but it is not used in the view - this pr corrects that

That's not correct. Parameter `image = NO` removes all images from introtext with a `preg_replace`. See: https://github.com/joomla/joomla-cms/blob/3.8.3/modules/mod_articles_news/helper.php#L122-L125

So, if we want to show/hide the intro-image via module settings we need a new parameter for it (that is set to `NO` as default setting because of B\C).

BTW: This PR has coding errors. if condition not closed correctly, missing `}`. And code style errors.

**Comment by brianteeman** [comment]
i am going back to bed - i clearly am not reading things correctly today

**Comment by Quy** [comment]
Please testPR #20169<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19437">issues.joomla.org/tracker/joomla-cms/19437</a>.</sub>

**Pull request closed without merging**
