### PR TITLE
Make toolbar for mail-template as other layouts

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
The layout of the mail-template differs from other layouts. 

### Testing Instructions
Look at the mail-template screen before and after patch, make sure the buttons work as before and as expected. 

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Took me a while to see the problem. For reference the save button is always a single button and any other save buttons are a dropdown group

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7ec72dadb4baff6d8da7b37a06fc9ea4a7c388b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43849">issues.joomla.org/tracker/joomla-cms/43849</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7ec72dadb4baff6d8da7b37a06fc9ea4a7c388b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43849">issues.joomla.org/tracker/joomla-cms/43849</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43849">issues.joomla.org/tracker/joomla-cms/43849</a>.</sub>

**Comment by Hackwar** [comment]
Thank you @chmst for your contribution.

**Pull request merged**
