### PR TITLE
[4.0] password reset/username remind

### PR DESCRIPTION
**Pull request by brianteeman**
Not sure why there was a layout override here but it breaks in joomla 4

Before the PR to remove the override the descriptions are not present and this also makes the  aria markup invalid

Removing the layout override and the descriptions are back and the markup is valid

PS not sure if this can be tested with patchtester as it deletes a file

### Before
image

### After
image

### CODE REVIEW

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 7235205f6817e963ac18a26f9ef3f91b428e4527<br /><br />@brianteeman you're correct - PR can't be tested by applying patch in patch tester, as it's a file deletion.

- Navigated to components/com_users/layouts/joomla/form/
- Renamed renderfield.php to renderfield.bak for testing
- **Tested change successfully**
- Renamed renderfield.bak back to renderfield.php to restore file (optional).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30189">issues.joomla.org/tracker/joomla-cms/30189</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 7235205f6817e963ac18a26f9ef3f91b428e4527<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30189">issues.joomla.org/tracker/joomla-cms/30189</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30189">issues.joomla.org/tracker/joomla-cms/30189</a>.</sub>

**Comment by Quy** [comment]
Now there is help text under Email that is almost identical to the paragraph above.

**Comment by brianteeman** [comment]
Closed as this was not correct

**Pull request closed without merging**
