### PR TITLE
[postgresql] -  remove notice from manage database

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #14331 .

### Summary of Changes
managed `DROP DEFAULT`  on `JSchemaChangeitem` for postgresql

### Testing Instructions
With latest staging on postgresql go to Manage > Database. 

### Expected result
no notice

### Actual result
  `Notice: Undefined offset: `

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 2e35e0325a8b2d36148295cd848c2f4c56e996fc<br /><br />Thanks alikon!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14423">issues.joomla.org/tracker/joomla-cms/14423</a>.</sub>

**Comment by csthomas** [comment]
IMO this is the wrong solution. We can not remove `DROP DEFAULT` from update files.

We have to fix php code in https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/schema/changeitem/postgresql.php#L132
I suppose that reverse the order of `elseif`
with 
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/schema/changeitem/postgresql.php#L111
would solve the problem.

**Comment by alikon** [comment]
could be i've checked rather quickly, 
but why 

> We can not remove DROP DEFAULT from update files.

**Comment by csthomas** [comment]
* because drop default - in general this is not a solution but only temporary fix, we do not want to remove all "DROP DEFAULT ..." from sql updates files.
* because other databases does not have default too
* because bug is in the file mentioned by me earlier, not in sql updates files.

**Comment by alikon** [comment]
i've just looked at  `#__contact_details` and 
`ALTER TABLE "#__contact_details" ALTER COLUMN "name" DROP DEFAULT; `
even if for me is not needed , i agree with you should be correctly managed  by  changeitem for postgresql

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 0aae960d72a26cae437bfe4ae8ecf6cb1f9e0702<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14423">issues.joomla.org/tracker/joomla-cms/14423</a>.</sub>

**Comment by alikon** [comment]
conflict fixed in #18483

**Pull request closed without merging**
