### PR TITLE
[5.1] Convert mod_multilangstatus to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the multilanguage status module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_multilangstatus and System - Language Filter plugin published
2. You should see module output in administrator

mod_multilangstatus

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 86dcf69a210368c8dc738b8ee16b114caca936fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42845">issues.joomla.org/tracker/joomla-cms/42845</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 86dcf69a210368c8dc738b8ee16b114caca936fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42845">issues.joomla.org/tracker/joomla-cms/42845</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42845">issues.joomla.org/tracker/joomla-cms/42845</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and for testing to @fgsw @viocassel

**Pull request merged**
