### PR TITLE
Update Table.php

### PR DESCRIPTION
**Pull request by Kurantje**
Query requires back-quoted table name to acommodate for table names with special characters.

Pull Request for Issue #39487

### Summary of Changes
On line 734 it states: ->from($this->_tbl);
This should be: ->from($this->_db->quoteName($this->_tbl));

### Testing Instructions
Create a component using a table with a special character, e.g. da-events
Go to ...?option=<component>&view=event&layout=edit&id=1 to get the first element from the table

### Actual result BEFORE applying this Pull Request
Invalid mySQL query exception

### Expected result AFTER applying this Pull Request
In edit.php get the data from the da-events table for id=1

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by ReLater** [comment]
I have tested this item :red_circle: unsuccessfully on 158adfffc3605c6d2d6af2f2d69d889b04a5d875<br /><br />See my comment below<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39489">issues.joomla.org/tracker/joomla-cms/39489</a>.</sub>

**Comment by ReLater** [comment]
There are some more code places that must be fixed via `quoteName()`.

At least methods `checkOut(),` `checkIn().` but I didn't test any further. Just opened and closed an item in my test component where I renamed the main table from `ghsthing` to `ghsvs-thing` and added `protected $_tbl = '#__ghsvs-thing';` in my table class (`extends Table`).

I didn't save or update and so on.

The first fix of this pr works but ... see above.

**Comment by ReLater** [comment]
@Kurantje 
I have provided a pr in your branch that you can merge into this pr if you like to.
See https://github.com/Kurantje/joomla-cms/pull/1

**Comment by Kurantje** [comment]
@ReLater, Thanks for highlighting. Submitted Table.php again, now with all sql table references with QuoteName

**Comment by ReLater** [comment]
@Kurantje 
Why did you close your PR?

**Comment by Kurantje** [comment]
Oops! Didn't mean to. Will reopen. Thanks!

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 4e50a2df7ba48c6d1efa66c0c5f132e263bf1cc9<br /><br />- PHP 8.1.13
- MySQLi 10.5.18-MariaDB-1:10.5.18+maria~ubu2004-log
- Joomla 4.3.0-alpha2-dev
- Joomla_4.2.7-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39489">issues.joomla.org/tracker/joomla-cms/39489</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 4e50a2df7ba48c6d1efa66c0c5f132e263bf1cc9<br /><br />Code review + tried to view, delete, publish, unpublish.... records and all still works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39489">issues.joomla.org/tracker/joomla-cms/39489</a>.</sub>

**Comment by joomdonation** [comment]
RTC. Thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39489">issues.joomla.org/tracker/joomla-cms/39489</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
