### PR TITLE
[4.0] Update CodeMirror paths

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This removes CodeMirror paths from plugin configuration .

### Testing Instructions

Save CodeMirror plugin at least once.
Edit files in template manager.

### Expected result

CodeMirror appears.

### Actual result

Basic text field appears.

### Documentation Changes Required

Base path and mode path are now passed to `onCodeMirrorBeforeInit` as separate arguments. Plugins that used to modify `basePath` or `modePath` params will need to be updated from:

```
public function onCodeMirrorBeforeInit(&$params)
{
	$params->set('basePath', 'path/to/codemirror/');
	$params->set('modePath', 'path/to/modes/%N/%N');
}
```
to:
```
public function onCodeMirrorBeforeInit(&$params, &$basePath, &$modePath)
{
	$basePath = 'path/to/codemirror/';
	$modePath = 'path/to/modes/%N/%N';
}
```

If someone wants to do it, CodeMirror events can be documented here https://docs.joomla.org/Plugin/Events.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 46266cbaea53a35d878fe0a0d6fe980d7b51e7a2<br /><br />Worsk as described and fixes the error descibed in this PR.

I don't know if it is a good or a bad idea to make the paths configurable, but this shall someone else decide.

For me it is ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by SharkyKZ** [comment]
Here's some background about why hidden path parameters were added in the first place https://github.com/joomla/joomla-cms/pull/5863#issuecomment-154275162. To me it doesn't make much sense either.

**Comment by richard67** [comment]
Well, hidden is one thing, that might be ok. Visible and so editable (without hacks) is another thing. Not sure if that is good, but who knows, maybe someone has another code mirror instance he wants to use. Anyway, we have so much configurable stuff in the backend, having 1 or 2 things more or less of which 99% of the users will not know what it is good for, that does not make a big difference ;-)

**Comment by wilsonge** [comment]
I think I'd rather keep them hidden please. For no reason other than I don't really see the use case for them to most users so no need to add more params to the interface

**Comment by richard67** [comment]
We need more params in backend to fill up the space gained by the new backend template :tongue: (I know, silly joke).

**Comment by richard67** [comment]
@SharyKZ The more I think it over, the more I agree with George: They should be still hidden.

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by SharkyKZ** [comment]
Just changing the default value won't fix the problem though. Old value is already saved on 3.x sites.

We could remove these options from manifest files completely. If anyone's actually using this feature, they should really be using `onCodeMirrorBeforeInit` event to alter the parameters instead of altering the form with `onContentPrepareForm` to make the field editable and then modifying the value manually.

**Comment by wilsonge** [comment]
> We could remove these options from manifest files completely. If anyone's actually using this feature, they should really be using onCodeMirrorBeforeInit event to alter the parameters instead of altering the form with onContentPrepareForm to make the field editable and then modifying the value manually.

If that works using `onCodeMirrorBeforeInit` to achieve this then I'm happy doing that

**Comment by SharkyKZ** [comment]
Fields removed.

If it makes any difference, we could also add class variables for paths to the plugin and pass these to `onCodeMirrorBeforeInit` instead of modifying hidden params. This way the feature would be less obscure.

**Comment by brianteeman** [comment]
This PR solves the issue from #26455 when joomla is in a subdirectory.

Definitely needs something to update the params on upgrade though and do we still need this code
https://github.com/joomla/joomla-cms/blob/7a9459004b5c49cae0ce9dfc8310e61f4597d416/plugins/editors/codemirror/layouts/editors/codemirror/element.php#L26-L27

**Comment by JazParkyn** [comment]
I have tested this item :white_check_mark: successfully on 851f9e224d912cdbac2f756a773d9137590583e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 851f9e224d912cdbac2f756a773d9137590583e5<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by HLeithner** [comment]
The cleanup for updates in onCodeMirrorBeforeInit missing as suggested or?

@wilsonge would you like to merge it anyway? it seams to solve 2 issues.

**Comment by SharkyKZ** [comment]
@HLeithner are you asking about not requiring 3.x users to save plugin configuration?

**Comment by HLeithner** [comment]
@SharkyKZ after Upgrading from 3.10 to 4.0 it would wouldn't be realistic to request the site owner to go the "each" (we maybe find more of such things) plugin and click save.

I'm reference to this comment

> Just changing the default value won't fix the problem though. Old value is already saved on 3.x sites.

Or is this solve when we remove the parameters from the xml file?

**Comment by SharkyKZ** [comment]
No, it's not solved. Will have to implement https://github.com/joomla/joomla-cms/pull/25591#issuecomment-518096842 to solve upgrades.

**Comment by HLeithner** [comment]
good that was my request, if you have time for it ;-)

**Comment by SharkyKZ** [comment]
PR and description updated. @richard67 @JazParkyn @anibalsanchez please test again.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 14aaae51c43532f9e288324c6833bbf84c94d63c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 14aaae51c43532f9e288324c6833bbf84c94d63c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25591">issues.joomla.org/tracker/joomla-cms/25591</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! Adding a docs required tag for this one

**Pull request merged**
