### PR TITLE
Typos in en-GB.plg_system_updatenotification.ini lang file

### PR DESCRIPTION
**Pull request by infograf768**
Can be merged on review.

### CODE REVIEW

**Comment by brianteeman** [comment]
Simple fix - good spot

**Comment by zero-24** [comment]
RTC. for 3.5.0 Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8195">issues.joomla.org/joomla-cms/8195</a>.</sub>

**Comment by infograf768** [comment]
BTW, at reading the code comments and the tips, the way this plugin is supposed to work is not real...
Basically, even on a monolanguage site where there can be multiple languages installed to let users and Super Users define their preferred UI language, it is the language used by a Super User-1 already logged that will be used to send mail to all Super Users. So basically if Super User-1 prefers an exotic language, others may not even understand the mail...

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768 and testers. Merged!

**Pull request merged**
