### PR TITLE
Container added to all batch modals

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #13305 .

### Summary of Changes
Adds a container to the batch modals to stop content from been flush to the modal edges.

### Testing Instructions
Apply patch and check all batch modals.

**Before Patch**
230ef55e-c6cb-11e6-94ac-166ee15a5843

**After Patch**
batch

### Documentation Changes Required
None

### CODE REVIEW

**Comment by cpfeifer** [comment]
Tested. You missed one small detail in the module manager administrator/components/com_modules/views/modules/tmpl/default_batch_body.php
Line 34, the COM_MODULES_BATCH_TIP paragraph should go inside the container

Otherwise awesome. I was going to do this but you beat me to it :)

**Comment by coolcat-creations** [comment]
Spaces are correct now, but still can´t access bottom of the list: (Cache is cleared)
image

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on 7b6e4f935c6204f5d9f168eecce84858b686724e<br /><br />see my screenshot from custom fields batch process for details.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13307">issues.joomla.org/tracker/joomla-cms/13307</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @cpfeifer & @coolcat-creations. These issues have been amended....

batch2

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 5e6a93d5d30d179fe284f91a9f1d0f3915fa1264<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13307">issues.joomla.org/tracker/joomla-cms/13307</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 5e6a93d5d30d179fe284f91a9f1d0f3915fa1264<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13307">issues.joomla.org/tracker/joomla-cms/13307</a>.</sub>

**Comment by dgt41** [comment]
RTC

Thanks @ciar4n <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13307">issues.joomla.org/tracker/joomla-cms/13307</a>.</sub>

**Pull request merged**
