### PR TITLE
Fix for issue 42229 - webservices content patch tags lost

### PR DESCRIPTION
**Pull request by MacJoom**
Pull Request for Issue #42229.

### Summary of Changes

Tags are not saved on a webservices content patch 

### Testing Instructions

Use webservices api to save (patch) an article

### Actual result BEFORE applying this Pull Request

tags are gone

### Expected result AFTER applying this Pull Request

tags are still the same

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@MacJoom When you refer to an issue at the top of the PR, pleaser do it right (no space. Erwerb the hash character and the issue number) so the issue is properly linked and we can see in the issue that it is referred to by a PR. This makes it easier for us to find issues which have a PR so we can close them. In addition, if you have the privileges to close issues, close the corresponding issue when you made a PR. Thanks in advance.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8217de5b19b5abe89cc4dd816de62aba737b9dc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42233">issues.joomla.org/tracker/joomla-cms/42233</a>.</sub>

**Comment by woluweb** [comment]
I have tested this item :white_check_mark: successfully on 8217de5b19b5abe89cc4dd816de62aba737b9dc2<br /><br />Txs Martin!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42233">issues.joomla.org/tracker/joomla-cms/42233</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42233">issues.joomla.org/tracker/joomla-cms/42233</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
