### PR TITLE
a11y icons in com_templates archive preview

### PR DESCRIPTION
**Pull request by brianteeman**
In com_templates if you select a zip file you will see a preview as shown in the screenshot below

For accessibility we need to add the aria-hidden tag to the icon

screenshotr19-54-30

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by RonakParmar** [comment]
To test this PR I have added a zip file in hathor template folder and selected that zip file in hathor template file list at administrator side. (Please see attached screen short). I got fatal error " Fatal error: Class 'ZipArchive' not found in joomlacmsstaging/administrator/components/com_templates/models/template.php on line 1306".
Am I doing anything wrong to test this PR? Please correct me.

Joomla! 3.7.0-rc1 dev [ Amani ] 21-February-2017 15:03 GMT 
PHP Version 5.6.30-7+deb.sury.org~precise+1 

screen shot 2017-03-23 at 07 23 49screen shot 2017-03-23 at 07 23 50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14706">issues.joomla.org/tracker/joomla-cms/14706</a>.</sub>

**Comment by mbabker** [comment]
Your system doesn't have PHP's `zip` extension installed and/or enabled.

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on fc567bd170a6f2c7e6314081d2b6d0a2291f2241<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14706">issues.joomla.org/tracker/joomla-cms/14706</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fc567bd170a6f2c7e6314081d2b6d0a2291f2241<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14706">issues.joomla.org/tracker/joomla-cms/14706</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14706">issues.joomla.org/tracker/joomla-cms/14706</a>.</sub>

**Comment by zero-24** [comment]
Thanks :+1:

**Comment by brianteeman** [comment]
Thanks for testing and mergin

**Pull request merged**
