### PR TITLE
[4.0] remove redundant code, tabs.js/scss

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
The actual code is fetched from joomla-projects/joomla-custom-elements, this existed in the repo as a help for @ciar4n and Charlie to do styling itterations

### Testing Instructions
Tabs still work in article edit form, (they do!)

### CODE REVIEW

**Comment by wilsonge** [comment]
1 tester here please just to confirm tabs are still as is in com_content

**Comment by ghost** [comment]
@wilsonge can this be tested by Patchtester?

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig nope

**Comment by dgrammatiko** [comment]
@wilsonge you don't even need a test here, take a look at: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/html/uitab.php#L42

**Comment by brianteeman** [comment]
after deleting these files and then running npm install I still have the typo

**Comment by dgrammatiko** [comment]
@brianteeman the code is fetched per release. the code George just merged in the other repo is not yet in the release we're fetching. Anyways I'm gonna make a change and always fetch the latest code ignoring the releases part as it complicates a lot the whole procedure...

**Comment by dgrammatiko** [comment]
@wilsonge @brianteeman done: https://github.com/joomla/joomla-cms/pull/21610

**Pull request merged**
