### PR TITLE
[4.x] com_templates when using pdo

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37487 .

### Testing Instructions
on a joomla install using mysql pdo (eg in configuration.php it says `public $dbtype = 'mysql';` not mysqli
open the template manager

### Actual result BEFORE applying this Pull Request
the path is fubar

### Expected result AFTER applying this Pull Request
the path is correct and no error messages when using the template manager

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9d3eb6971dfd04ce587317714cfbe64b4a041cfe<br /><br />Tested successfully in Joomla 4.1.3-dev in Wampserver 3.2.7 using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37489">issues.joomla.org/tracker/joomla-cms/37489</a>.</sub>

**Comment by Sandra97** [comment]
I have tested this item :white_check_mark: successfully on 9d3eb6971dfd04ce587317714cfbe64b4a041cfe<br /><br />It solves my issue. 

Now the path is correct, and everything works fine, no more error messages and I can edit files.

Thanks a lot Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37489">issues.joomla.org/tracker/joomla-cms/37489</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37489">issues.joomla.org/tracker/joomla-cms/37489</a>.</sub>

**Comment by laoneo** [comment]
Thanks for the pr, but would it not be easier to cast to int where the template is fetched form the database? Like that we fix it on the source of the issue and we do not have to patch it all over the core.

**Comment by bembelimen** [comment]
> Thanks for the pr, but would it not be easier to cast to int where the template is fetched form the database? Like that we fix it on the source of the issue and we do not have to patch it all over the core.

Was wrking on the issue and had the same thought: #37497

**Comment by toivo** [comment]
@Sandra97 please test https://github.com/joomla/joomla-cms/pull/37497 which replaced this pull request #37489.  The new #37987 should then be included in the next version of 4.1 and above.

**Pull request closed without merging**
