### PR TITLE
[4.0] Line Break missing in checked out articles/category

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

Pull Request for Issue - Intended line break is does not work in checked out articles/categories etc .

### Testing Instructions
Checkout any article or category.
Tested in chrome and firefox.

### Expected result
capture19-2

### Actual result
capturewr

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct

**Comment by bahl24** [comment]
@brianteeman What is the issue? `<br>` is not rendered in the earlier way. 
https://stackoverflow.com/questions/358874/how-can-i-use-a-carriage-return-in-a-html-tooltip

**Comment by brianteeman** [comment]
strong has meaning and you have removed that meaning

**Comment by bahl24** [comment]
@brianteeman I apologize for it, but I have tried using `<strong>`,`<b>` enclosed in both `''` & `""` but could not find a way to make it strong. Any suggestions?
@C-Lodder @bembelimen @chmst

**Comment by dgrammatiko** [comment]
Tooltips SHOULD NOT have any markup in the text, deal with it...

**Comment by bahl24** [comment]
@dgrammatiko @infograf768 I agree and there is no way to have markup in tooltip, that's why I chose to ignore the strong tag given. Nor have I ever seen something in which tooltip is formatted. Deleting strong tag looks like the only solution having no effect on functionality.

**Comment by brianteeman** [comment]
@bahl24 I guess you haven't looked hard as it is very common - just because you don't know how to do something is no reason to arbitrarily remove it. And just because @dgrammatiko doesn't believe a tooltip should have markup doesnt mean he is correct either - thats just an arbirtary opinion

**Comment by dgrammatiko** [comment]
> thats just an arbirtary opinion

No, my case was about XSS. Whenever you want to pass a tag in the js then you have to either:
- use innerHTML, it's not safe and you shouldn't
- use a proper way to build the tooltip in the js. 

Anyways the element.innerHTML is really bad for XSS, Joomla is using it all over the place because of ignorance, check the latest version there is a hint there.
All and all I'm standing in my opinion that innerHTML is not safe and **shouldn't** be use and tooltips with rich text are based on that. Of course, is Joomla's decision if they will keep delivering unsafe scripts or they'll drop or find other ways to implement that...

**Comment by dgrammatiko** [comment]
To put it simple: `aria-labelledby` accepts rich HTML?
No!
It's the same reason, you cannot parse safely rich HTML thus the **platform** (not some random guy like me) doesn't allow it...

**Comment by brianteeman** [comment]
> use a proper way to build the tooltip in the js.
Why not do that - thats how it is normally done

**Comment by dgrammatiko** [comment]
> Why not do that - thats how it is normally done

Its far easier to drop the span, br, etc than doing anything else

**Comment by brianteeman** [comment]
That's a pathetic lazy reason

**Comment by dgrammatiko** [comment]
I could return the pathetic to the idea that tooltips **must** have rich HTML

**Comment by wilsonge** [comment]
Brian's correct we should have semantic html in the tooltips. This isn't the correct fix.

**Pull request closed without merging**
