### PR TITLE
[Associations] Contact item type should be plural

### PR DESCRIPTION
**Pull request by infograf768**
When using Multingual associations, the item types should be in plural form.
Contact was the only one singular.

Before patch
screen shot 2017-05-17 at 09 52 28

After patch
screen shot 2017-05-17 at 09 50 54

Simple change. Can be merged on review for 3.7.2

### CODE REVIEW

**Comment by brianteeman** [comment]
Fine by me - it looks like a bug as it is correct in the .sys.ini file and thats the file used for the dropdown menus

**Comment by infograf768** [comment]
Although both .ini and sys.ini do load, the string is picked from the .ini in multilingual associations (nothing to do with menus dropdown)
Same for all these types.

**Comment by brianteeman** [comment]
yes i was just pointing out that the menu dropdowns are all correctly plural

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2b339a2d363c1a09dacd71aff7ff26795214de52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16063">issues.joomla.org/tracker/joomla-cms/16063</a>.</sub>

**Comment by infograf768** [comment]
BTW, I found why .ini superseeds sys.ini in multilingual associations.
In the helper, we have in the `getSupportedExtension` method
```
		// Get the translated titles.
		$languagePath = JPATH_ADMINISTRATOR . '/components/' . $extensionName;
		$lang         = JFactory::getLanguage();

		$lang->load($extensionName . '.sys', JPATH_ADMINISTRATOR);
		$lang->load($extensionName . '.sys', $languagePath);
		$lang->load($extensionName, JPATH_ADMINISTRATOR);
		$lang->load($extensionName, $languagePath);

		$result->def('title', JText::_(strtoupper($extensionName)));
```

and further
```
if ($lang->hasKey(strtoupper($extensionName . '_' . $title . 'S')))
			{
				$languageKey = strtoupper($extensionName . '_' . $title . 'S');
			}
```
Mystery solved. ;)

**Comment by brianteeman** [comment]
just wondering if that needs to be fixed as perhaps it will cause issues with non core extensions using associations?

**Comment by infograf768** [comment]
I think we must have had a reason for that.  
One of the requirements for 3rd party extensions (among a lot of others) is to provide such string in the .ini, if not already present.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2b339a2d363c1a09dacd71aff7ff26795214de52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16063">issues.joomla.org/tracker/joomla-cms/16063</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16063">issues.joomla.org/tracker/joomla-cms/16063</a>.</sub>

**Pull request merged**
