### PR TITLE
Keep user.css last in order

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #38345 .

### Summary of Changes
Currently user.css loaded after template.css. however the modules css goes after.
This patch make user.css to be as last css in loaded stylesheets, as long as it not violate any dependency.

### Testing Instructions
Apply patch. Create user.css.
Inspect the source page for list of loaded stylesheets. Check that user.css is last in the list.
Also follow #38345

### Actual result BEFORE applying this Pull Request
Not always last, when there a module css.

### Expected result AFTER applying this Pull Request
Always last

### Documentation Changes Required
No, I guess.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on 0ef84ef065e3acb8352d85c764e16e2c179855dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38368">issues.joomla.org/tracker/joomla-cms/38368</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0ef84ef065e3acb8352d85c764e16e2c179855dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38368">issues.joomla.org/tracker/joomla-cms/38368</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38368">issues.joomla.org/tracker/joomla-cms/38368</a>.</sub>

**Comment by n3t** [comment]
I have tested this item :white_check_mark: successfully on 0ef84ef065e3acb8352d85c764e16e2c179855dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38368">issues.joomla.org/tracker/joomla-cms/38368</a>.</sub>

**Comment by fancyFranci** [comment]
Thanks Fedik! :)

**Pull request merged**
