### PR TITLE
[5.2] Fix JS errors in admin menu

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #44408

### Summary of Changes

This PR fixes the JS errors being thrown when creating an Admin Menu

### Testing Instructions

See original issue

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8269f58850200139e56e9a2785d45edc085293b1<br /><br />Thanks @c-lodder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44410">issues.joomla.org/tracker/joomla-cms/44410</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8269f58850200139e56e9a2785d45edc085293b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44410">issues.joomla.org/tracker/joomla-cms/44410</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44410">issues.joomla.org/tracker/joomla-cms/44410</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for your contribution!

**Pull request merged**
