### PR TITLE
[4.3] Fix wrong language string constant for category permission notes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #39076 .

### Summary of Changes

Revert the replacement of the `JLIB_RULES_SETTING_NOTES_ITEM` language string override in file `com_categories.ini` by a string with the wrong name done with PR #35424 and remove the wrong string (which doesn't need a deprecation since never been in any stable or development release).

### Testing Instructions

Edit a category and go to the "Permissions" tab. Expand the notes and check what's written there.

### Actual result BEFORE applying this Pull Request

Standard language string is used in the permission notes.

### Expected result AFTER applying this Pull Request

Special language string for categories is used in the permission notes.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on fed181bc395a1b47fd5ef51896e0568f16d5dfd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Comment by wilsonge** [comment]
We shouldn't have com_content stuff in the com_categories language file. Pretty sure we should be loading a com_content language file somewhere where this should come from - don't forget com_categories is shared between other components too - some 3PD's as well (sorry still waiting for my laptop so can't check myself exactly which file)

**Comment by richard67** [comment]
> We shouldn't have com_content stuff in the com_categories language file.

Ouch, I haven't noticed that. Will check and if possible correct.

**Comment by richard67** [comment]
@wilsonge Thanks. Fixed it. Is 5.0 ok for the deprecation of the wrong string? Or should it be 6.0?

**Comment by richard67** [comment]
@Kostelano Sorry, I had to make a change (move the new string to the right file). Could you test again with these changes? Thanks in advance.

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 1cced315ec5df15fff9339eb0658403084264e63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Comment by heelc29** [comment]
I have tested this item :red_circle: unsuccessfully on 1cced315ec5df15fff9339eb0658403084264e63<br /><br />The categories component is also used in other components (eg. contacts).

image
image
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Comment by richard67** [comment]
@heelc29 I am not sure if this justified a negative test result. This PR here fixes the issue where described. It does not introduce your observation as new issue so it is an old one which could be fixed with a separate PR.

**Comment by heelc29** [comment]
@richard67 It says `Open category edit form and switch to tab Permissions.` not especially for articles context. Wherever the category component is used, it was changed between 4.2.x and 4.3-dev.

**Comment by richard67** [comment]
So either we have to add also language strings to other components' language files and expect the 3rd party developers whose components use categories to do the same, or we have to find the root cause why the com_categories string is not used in 4.3.

I'd prefer the latter of course and will see what I can find out or do, but if anyone else has an idea, please let us know.

**Comment by heelc29** [comment]
> or we have to find the root cause why the com_categories string is not used in 4.3

**is not used after apply PR https://github.com/joomla/joomla-cms/pull/35424**

In this PR an override of the `JLIB_RULES_SETTING_NOTES_ITEM` key was removed in `administrator/language/en-GB/com_categories.ini`

**Comment by richard67** [comment]
> > or we have to find the root cause why the com_categories string is not used in 4.3
> 
> **is not used after apply PR #35424**
> 
> In this PR an override of the `JLIB_RULES_SETTING_NOTES_ITEM` key was removed in `administrator/language/en-GB/com_categories.ini`

I did understand that already. No need for bold letters. The question remains what is the right change, bring back that override or add component specific strings for other components which use categories.

@wilsonge What's your opinion?

**Comment by richard67** [comment]
Since there are still other overrides of the JLIB tests in the com_categories file, see e.g. https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/language/en-GB/com_categories.ini#L77-L78 , which were touched by PR at first and later then reverted to the original state in that PR with this commit https://github.com/joomla/joomla-cms/pull/35424/commits/22eb9300f5b0b36296684014389931d5dfe7ebd1 , I think we should do the same here and revert that one change to the previous state, too.

Will update this PR here in a minute.

**Comment by richard67** [comment]
@Kostelano Sorry, again I had to make a change. Now it works for all kinds of categories. Could you test again.

@heelc29 Please test again, too.

Thanks in advance to you both.

**Comment by Kostelano** [comment]
Why can't we just remove the `JLIB_RULES_SETTING_NOTES_ITEM_COM_CATEGORIES` line? It was added in 4.3-dev and has never been in the stable release yet.

**Comment by richard67** [comment]
> Why can't we just remove the `JLIB_RULES_SETTING_NOTES_ITEM_COM_CATEGORIES` line? It was added in 4.3-dev and has never been in the stable release yet.

Good question. Maybe I was just in the flow of regular releases and so didn't have that in mind.

**Comment by richard67** [comment]
@Kostelano Thanks, I've remove it.

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 59c34e8f65d2525cd98b05a2a88d033aa1d6ebf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 59c34e8f65d2525cd98b05a2a88d033aa1d6ebf5<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39212">issues.joomla.org/tracker/joomla-cms/39212</a>.</sub>

**Pull request merged**
