### PR TITLE
[4.4] Proposed fix for Workflow transition error

### PR DESCRIPTION
**Pull request by kochinc**
Pull Request for Issue #42031.

### Summary of Changes
Restructure codes in function getValidTransition() in file libraries/src/Workflow/Workflow.php so that it works with PostgreSQL.

### Testing Instructions

It needs to use a PostgreSQL database to reproduce the problem.

1. Enable Workflow.
2. From left menu, select Content -> Articles.
3. From the Stage column, click on one of the item to change transition.

### Expected result AFTER applying this Pull Request
No error returned and new transition is correctly set.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 73e5726acad109e88159042badedc087dab74dc2<br /><br />The PR fixes the issue for PostgreSQL, and on MySQL it works as well as before. I've tested both.

There are 2 deprecated warnings in PHP (using PHP 8.1.2), but they happen also without this PR in the same way. This PR just makes them appear on PostgreSQL, too, because the issue doesn't happen anymore so the transition takes place.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42036">issues.joomla.org/tracker/joomla-cms/42036</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 73e5726acad109e88159042badedc087dab74dc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42036">issues.joomla.org/tracker/joomla-cms/42036</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42036">issues.joomla.org/tracker/joomla-cms/42036</a>.</sub>

**Comment by richard67** [comment]
@kochinc There is no need to update your branch when there are no conflicts shown.

**Pull request merged**
