### PR TITLE
[4.x] Inject installer via service provider

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/pull/31524#discussion_r532580652.

### Summary of Changes

Inject the installer the same way as the database.

@laoneo Was that what you meant in your comment, and @wilsonge  is that how it's generally intended ? Then I would standardize it in all places for the CLI.

### Testing Instructions

Code review

### Additional Questions

I realized while working on this PR, that the container is not in the Joomla Repo but in the Framework. Should not the framework be unified with the Joomla CMS in version 4? The [roadmap](https://developer.joomla.org/roadmap.html#4) includes this text:
The power of the Joomla Framework merged into the CMS

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Interesting, I had moments ago raised this one about this cli... https://github.com/joomla/joomla-cms/issues/32967

**Comment by laoneo** [comment]
I would even go one step further and make the installer a service provider. So you can load in the Console service provider the installer from the installer service provider.

**Comment by wilsonge** [comment]
> I would even go one step further and make the installer a service provider. So you can load in the Console service provider the installer from the installer service provider.

I mean I think for Installer that might be a step to far as there's no way to reset all the extension data stored in all it's private/protected properties when installing an extension... (i mean generically speaking I agree)

To me this is in about the right place.

**Comment by laoneo** [comment]
Why did you close? @wilsonge and me were just discussing about this line https://github.com/joomla/joomla-cms/pull/32969/files#diff-7229d3e3025f6259363b5b58ccfc54d9408edd528e0683f18b1fe2f072c24675R171

**Comment by astridx** [comment]
What exactly are you discussing regarding this line?

**Comment by laoneo** [comment]
That this can be also a service provider which offers an installer so you don't have to create an instance of the installer by yourself. The rest is absolutely fine and should come into 4.0.

**Comment by astridx** [comment]
> I mean I think for Installer that might be a step to far as there's no way to reset all the extension data stored in all it's private/protected properties when installing an extension... (i mean generically speaking I agree)
> 
> To me this is in about the right place.

I understand @wilsonge so, that he seems that this might be a step to far and it is fine like it is currently?

**Comment by laoneo** [comment]
In this comment https://github.com/joomla/joomla-cms/pull/32969#issuecomment-814507936 he quoted my comment. @wilsonge can you shed some light into this one?

**Pull request closed without merging**
