### PR TITLE
[com_content] Repositioning Alternate Layout in article options and rename it

### PR DESCRIPTION
**Pull request by coolcat-creations**
Rename Alternate Layout to Layout
Move it to the Main Article Options

Pull Request for Issue #10743  .

### Testing Instructions
Select an Layout in your Article Options (Page 1 below languages) and check if it still works.

image

### Documentation Changes Required
yes, new Screenshot and location description of the field

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 16a79ef78de7d45fb972b74fe8b86c4215b7ccbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 16a79ef78de7d45fb972b74fe8b86c4215b7ccbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by coolcat-creations** [comment]
only changed the tooltip and removed different

**Comment by ghazal** [comment]
I have tested this item :red_circle: unsuccessfully on 84fd050dc5478e668d93b2907f096388750970ed<br /><br />The new feature is showing at the expected position but doesn't save the new layout chosen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by mbabker** [comment]
This won't work.  Moving it like this, you would have to either add it as a field in the database or add a bunch of extra code to make the field continue to correctly save as part of the item's `attribs` column.  By moving the field outside of the `attribs` fieldset, that's why it's broken.

**Comment by coolcat-creations** [comment]
Ok, how about if i move it at least to the very top in the Attribs?

**Comment by coolcat-creations** [comment]
Moved it now to the top inside attributes, can someone tell me how i pull the global params there?

**Comment by franz-wohlkoenig** [comment]
is somewhere an Answer for @coolcat-creations ?

**Comment by coolcat-creations** [comment]
Any thoughts on this? Leave open or close? thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ec5cb65bdfea9b100e66cc05e347bcd8a73d01e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by dgt41** [comment]
@franz-wohlkoenig @laoneo can you retest so we can RTC and merge?
This is an awesome UX improvement

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on ec5cb65bdfea9b100e66cc05e347bcd8a73d01e8<br /><br />`Layout` is first Field in Tab `Option`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13829">issues.joomla.org/tracker/joomla-cms/13829</a>.</sub>

**Pull request merged**
