### PR TITLE
[4.0] switcher legend alignment

### PR DESCRIPTION
**Pull request by brianteeman**
make sure that the switcher is always left aligned

### before
image

### after
image

### CODE REVIEW

**Comment by brianteeman** [comment]
updated branch to trigger appveyor to run again as the error in appveyor was infrastructure and nothing to do with this pr

**Comment by infograf768** [comment]
We need specific switcher css for rtl as it is really broken in rtl (same in new admintemplate)

**Comment by brianteeman** [comment]
Everything in the new admin template is broken. There is no point doing any RTL fixes until they finish deciding what a form should look like.

**Comment by infograf768** [comment]
FYI, we also have issue concerning LTR for the existing code here. 
```
.col-md-9 .switcher__legend {
   margin-left: -220px;
 }
```
breaks the switcher in new admin template when editing a module:
Screen Shot 2019-05-12 at 08 27 35
If taken away, we rightfully get
Screen Shot 2019-05-12 at 08 31 50

Therefore is it really useful to correct anything concerning switcher in this branch?

**Comment by brianteeman** [comment]
Already raised am issue on their repo. But as their repo is pretty messed up it's probably a waste of time

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on fe6a3532ea94fc1b272a140ea9de43bebc6069d6<br /><br />Can you give me the link to your issue on "their" repo? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24802">issues.joomla.org/tracker/joomla-cms/24802</a>.</sub>

**Comment by brianteeman** [comment]
https://github.com/joomla/backend-template/issues/170#issuecomment-491250462

**Comment by chmst** [comment]
thx

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fe6a3532ea94fc1b272a140ea9de43bebc6069d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24802">issues.joomla.org/tracker/joomla-cms/24802</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Comment by Quy** [comment]
Please fix the switcher alignment when in the sidebar (ie edit article).

switcher

**Comment by ghost** [comment]
@Quy can you please open a new Issue?

**Comment by infograf768** [comment]
PR should be simple (for the admin template we have now...)
Move in switcher.scss
```
.col-md-3 .switcher__legend {
  margin-left: 0;
}
```
after
```
.col-md-9 .switcher__legend,
.col-md-12 .switcher__legend {
  margin-left: -220px;
}
```

**Comment by chmst** [comment]
It is fixed. Did you run npm i?

**Comment by brianteeman** [comment]
you beat me too it @chmst

**Comment by infograf768** [comment]
I did
As I said, the order counts.

**Comment by brianteeman** [comment]
Works for me

image

**Comment by infograf768** [comment]
I use firefox macintosh and this is what exactly happens:
```
.col-md-9 .switcher__legend,
.col-md-12 .switcher__legend {
  margin-left: -220px;
}
```
is overriding  .col-md-3

Screen Shot 2019-05-23 at 10 13 08

**Comment by brianteeman** [comment]
That is NOT the latest css

**Comment by brianteeman** [comment]
I can see it now after another rebuild 
I will take a look at why later today. It makes no sense that that css is being used when it is a col-md-3

**Comment by infograf768** [comment]
Apologies are accepted.

**Comment by infograf768** [comment]
No need to look why. It is pretty obvious
Basically, as
```
.col-md-12 .switcher__legend {
  margin-left: -220px;
}
```
is loaded after col-md-3
it overrides it.

**Comment by brianteeman** [comment]
Not obvious to me as col-md-3 is more specific so should be the one used as far as I understand CSS. I will not submit a pr myself without understanding why

**Comment by Bakual** [comment]
The problem is likely that there is also an element with `col_md-12` somewhere up the tree. In this case both CSS rules have the same specificity (a class as the child of another class). It doesn't matter which parent class is "closer" in the tree.
And since they are equal, the later wins.

**Comment by infograf768** [comment]
Exact. Creating patch now

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/24993

**Pull request merged**
