### PR TITLE
[4.0] LibraryHelper prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements to `Joomla\CMS\Helper\LibraryHelper`.

### Testing Instructions

Simple queries, code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c3a9340729866eb26651cea49c2a92c9d0ad67e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26031">issues.joomla.org/tracker/joomla-cms/26031</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8c3a9340729866eb26651cea49c2a92c9d0ad67e<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26031">issues.joomla.org/tracker/joomla-cms/26031</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thank you

**Pull request merged**
