### PR TITLE
[4.0] Session Manager for destroying sessions

### PR DESCRIPTION
**Pull request by SharkyKZ**
Replacement PR for https://github.com/joomla/joomla-cms/pull/26891.

### Summary of Changes

See https://github.com/joomla/joomla-cms/pull/26891.

### Testing Instructions

See https://github.com/joomla/joomla-cms/pull/26891.

### Documentation Changes Required

Yes, see https://github.com/joomla/joomla-cms/pull/26891.

### CODE REVIEW

**Comment by carcam** [comment]
I have tested this item :red_circle: unsuccessfully on bd28bc43ec2fbf6726af614d17e54104e167cfa8<br /><br />I have followed this steps:

1. Set session handler to Filesystem
2. Create a registered user
3. Logged in with registered user in the frontend
4. Force log out the user from the logged in module in dashboard: User was removed from the module, but kept logged in in the frontend.
5. Applied the patch
6. Repeat from 3. This time log out button did nothing and user kept logged in in the frontend again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29007">issues.joomla.org/tracker/joomla-cms/29007</a>.</sub>

**Comment by richard67** [comment]
@carcam It does not make much sense to test a pull request if
- it has conflicts.
pr-conflicts
- it is still draft status.

**Comment by BertaOctech** [comment]
I have tested this item :red_circle: unsuccessfully on bd28bc43ec2fbf6726af614d17e54104e167cfa8<br /><br />I have open sessions for a registered users both in firefox and chrome

I have tried to obtain the expected result: 

- Logging a user out with the icon in the "Logged-in Users" module logs a user out regardless of session handler

This happened to me befor applying the patch

- Removing a user account with a privacy request does not trigger a fatal error

The first worked fine before applying the patch

I could not test the second because of an issue I reported at
https://github.com/joomla/joomla-cms/issues/30304

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29007">issues.joomla.org/tracker/joomla-cms/29007</a>.</sub>

**Comment by BertaOctech** [comment]
The issue was my mistake, so I closed it https://github.com/joomla/joomla-cms/issues/30304#issuecomment-670137614

Following on my previous test, in my case "Removing a user account with a privacy request"  did not trigger a fatal error

I wonder if some other patch has solved the issue. That would mean this patch is not needed anymore.

**Comment by gostn** [comment]
need label:"Conflicting Files"

**Comment by rdeutz** [comment]
I have tested this item :white_check_mark: successfully on 71d68e0c6afb52b8fbe068204ea526a5f44750a8<br /><br />There is one problem we can fix in another PR, if you set session manager to file and click on "Log Out" in the backend, the button is still there. The user is logged out and we you refresh the frontend to user is also gone in the backend. The reason is that the session is still in the database session table. I am looking into this just need to find out where is the best place to clean the database table.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29007">issues.joomla.org/tracker/joomla-cms/29007</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 71d68e0c6afb52b8fbe068204ea526a5f44750a8<br /><br />Give it a successful test so that we can move forward with https://github.com/joomla/joomla-cms/pull/32863 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29007">issues.joomla.org/tracker/joomla-cms/29007</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29007">issues.joomla.org/tracker/joomla-cms/29007</a>.</sub>

**Comment by bembelimen** [comment]
Thank you!

**Comment by PhilETaylor** [comment]
this maybe broke #32966

**Pull request merged**
