### PR TITLE
[4.2] Fix fatal error on webauthn plugin

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
PR https://github.com/joomla/joomla-cms/pull/38060/ removed `$app` property from the class, so using `$this->app` in the layout causes fatal error. We need to use `$this->getApplication()` to get application object instead.

I also removed an un-used use statement in the plugin layout code.

### Testing Instructions
I don't have experience with using the plugin, so please ignore if my testing instructions are wrong

1. Use Joomla 4.2 nightly build
2. Make sure **Multi-factor Authentication - Web Authentication** plugin is enabled
3. Login to administrator area of your site, edit an user account, look at **Multi-factor Authentication** tab, click on **Add a new Web Authentication** button.

### Actual result BEFORE applying this Pull Request
Get fatal error: **Call to a member function getDocument() on null**

### Expected result AFTER applying this Pull Request
Error is gone, the page loads OK

### CODE REVIEW

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on a5042e15aff243ce7bc68d91333fd12b852f3f81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38132">issues.joomla.org/tracker/joomla-cms/38132</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a5042e15aff243ce7bc68d91333fd12b852f3f81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38132">issues.joomla.org/tracker/joomla-cms/38132</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38132">issues.joomla.org/tracker/joomla-cms/38132</a>.</sub>

**Comment by richard67** [comment]
RTC !!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38132">issues.joomla.org/tracker/joomla-cms/38132</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
