### PR TITLE
[4.1] PHP 8.1 Deprecation warning TagModel

### PR DESCRIPTION
**Pull request by frostmakk**
### Testing Instructions
Install 4.1 with sample data.
Run on PHP 8.1 with maximum error reporting.
Go to front end and click on a tag.

### Actual result BEFORE applying this Pull Request
PHP Deprecated:  Automatic conversion of false to array is deprecated in ..\components\com_tags\src\Model\TagModel.php on line 318

### Expected result AFTER applying this Pull Request
No deprecation warning from TagModel

### CODE REVIEW

**Comment by chmst** [comment]
Closing. Please test https://github.com/joomla/joomla-cms/pull/37568

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 189d60f835bbf95eb33b86007d0d521fce834613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37567">issues.joomla.org/tracker/joomla-cms/37567</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 189d60f835bbf95eb33b86007d0d521fce834613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37567">issues.joomla.org/tracker/joomla-cms/37567</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 189d60f835bbf95eb33b86007d0d521fce834613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37567">issues.joomla.org/tracker/joomla-cms/37567</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37567">issues.joomla.org/tracker/joomla-cms/37567</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 189d60f835bbf95eb33b86007d0d521fce834613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37567">issues.joomla.org/tracker/joomla-cms/37567</a>.</sub>

**Comment by laoneo** [comment]
The correct way is the fix from #37568 as the item needs to be an array as you can see here https://github.com/joomla/joomla-cms/blob/0e17958f0ddd694895325080a8892d2e83f39805/components/com_tags/src/Model/TagModel.php#L318. So the item needs to be initialized as array. and returned as array.

**Comment by frostmakk** [comment]
@chmst 
Closing in favor of #37568

**Pull request closed without merging**
