### PR TITLE
Adding choice to only resize TinyMCE vertically

### PR DESCRIPTION
**Pull request by infograf768**
See http://issues.joomla.org/tracker/joomla-cms/5660

This PR re-implements the choice we had in the TinyMCE 3.5 series (in Joomla 2.5) to resize the editor only vertically instead of both directions.
It could not be implemented when we switched to Tiny 4 because it was buggy. 

To test switch both the resizing parameters in Tiny advanced parameters.

### CODE REVIEW

**Comment by uthorat** [comment]
@infograf768  Hi I tested this patch . Great Work !!!
For article manager is done :)
Unfortunately something is missing, you should check the
Users -> mass mail for users.
Still editor is getting messed up with the other option.

Adding an screenshot 
mass mail


Warm Regards,
Umesh Thorat

**Comment by richard67** [comment]
@test Success.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5680">issues.joomla.org/joomla-cms/5680</a>.</sub>

**Comment by brianteeman** [comment]
@test all good - also tested with custom html module.

@uthorat The issue with the mass mail is different as that is not the TinyMCE editor please can you create a new issue for that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5680">issues.joomla.org/joomla-cms/5680</a>.</sub>

**Comment by uthorat** [comment]
Okay thanx to inform :)
Happy that work with you guyss :)
Creating an new issue

**Comment by infograf768** [comment]
Thanks for testing. Merged.

**Pull request merged**
