### PR TITLE
Google Summer of Code 2016 JavaScript Testing project: Tests for subform-repeatable.js library

### PR DESCRIPTION
**Pull request by Ruchiranga**
Pull Request extending #11420 by adding tests written for subform-repeatable.js library.
### Summary of Changes

This PR includes a new set of test cases written for the subform-repeatable.js JavaScript library of Joomla!.
### Testing Instructions

None, since this is only run on Travis. If you want to run it locally, please take a look at the documentation available [here](https://docs.google.com/document/d/1ZTzJiXwh4lNI9pPT38WqBy28nCd1duAD5fQakxZRm7s/edit).

### CODE REVIEW

**Comment by wilsonge** [comment]
This one has conflicts your going to need to fix - presumably with one of the others I merged earlier :)

**Comment by zero-24** [comment]
@Ruchiranga if you need to rebase anyway can you please double check the doc blocks with my suggestions too?
https://github.com/joomla/joomla-cms/pull/11652

**Comment by Ruchiranga** [comment]
@wilsonge yeah there is another PR that made changes to the same file. I'll fix this :)
@zero-24 Sure. I'll modify the doc block that way.

**Comment by zero-24** [comment]
:+1: Thanks @ruchiranga

**Pull request merged**
