### PR TITLE
[4.0][com_installer] Move icon to the right of text in button

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #30018.

### Summary of Changes
Override link to hide the external icon.

### Testing Instructions
Apply PR
Run `npm run build:css`
Go to System > Extensions
Go to the `Install from Web` tab
Click any extension

### Actual result BEFORE applying this Pull Request
screeny

### Actual result AFTER 

applying this Pull Request

### CODE REVIEW

**Comment by infograf768** [comment]
Can you add a screenshot for AFTER patch please.

**Comment by infograf768** [comment]
```
.item-view {
    .card-body {
      a[target="_blank"]::before {
        display: none;
    }
  }
```
looks like is missing a `}`, i.e should be
```
  .item-view {
    .card-body {
      a[target="_blank"]::before {
        display: none;
      }
    }
  }
```

**Comment by brianteeman** [comment]
Doesnt this remove the functionality of notifying the user that the link opens in a new window?

**Comment by chmst** [comment]
my2cent:
The external link information was useful, but the other icons are not, they give no information here, as the text on the buttons is sufficient. 
What do you think about removing the other icons?

**Comment by brianteeman** [comment]
Or move the link icon to the right of the text?

**Comment by infograf768** [comment]
LTR

Screen Shot 2020-07-22 at 08 40 14


RTL

Screen Shot 2020-07-22 at 08 38 06

**Comment by infograf768** [comment]
**Note:** other issues with RTL on this screen:
`dd` should have `margin-right: 0;`instead of `margin-left: 0;`

Some values, like the `Compatible Versions` should be LTR while still aligned right

therefore we should have in RTL
```
.col-md-8 dd {
    margin-bottom: .5rem;
    margin-right: 0;
    direction: ltr;
    text-align: right;
}
```
to get
Screen Shot 2020-07-22 at 09 13 09

**Comment by infograf768** [comment]
May I suggest to use only one icon?

**Comment by chmst** [comment]
> my2cent:
> The external link information was useful, but the other icons are not, they give no information here, as the text on the buttons is sufficient.
> What do you think about removing the other icons?

dito

**Pull request closed without merging**
