### PR TITLE
CLEANING - JFilesystemPatcher

### PR DESCRIPTION
**Pull request by Mathewlenning**
Cleaned up this class a little. Removed some redundant Else clauses and removed some redundant code.

### CODE REVIEW

**Comment by zero-24** [comment]
@Mathewlenning Travis complaining on very minimal error ;)

```
FILE: .../travis/build/joomla/joomla-cms/libraries/joomla/filesystem/patcher.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 146 | ERROR | Functions and classes must not contain multiple empty lines in a
     |       | row; found 2 empty lines
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by zero-24** [comment]
### How to test.

- Install clean joomla
- install com_patchtester
- install a patch (not this on here)
- install this patch (ID: 7965)
- install another patch
- make sure we have no errors
- revert all patches
- alter your test here :smile:

**Comment by Mathewlenning** [comment]
Thanks @zero-24 I'll fix the error in just a second.

**Comment by ceus1984** [comment]
I have tested this item :white_check_mark: successfully on 099f6beb9df1812c9e6b20a5533619517986cf7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7965">issues.joomla.org/joomla-cms/7965</a>.</sub>

**Comment by seagul30** [comment]
I have tested this item :white_check_mark: successfully on 099f6beb9df1812c9e6b20a5533619517986cf7e<br /><br />tested successfully! 
installed like in test description<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7965">issues.joomla.org/joomla-cms/7965</a>.</sub>

**Comment by SniperSister** [comment]
2 successful tests, setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7965">issues.joomla.org/joomla-cms/7965</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @Mathewlenning! Merged.

**Pull request merged**
