### PR TITLE
Remove call to deleteUnexistingFiles()

### PR DESCRIPTION
**Pull request by mbabker**
Per comments on c864a01a15b85379e182c4231969d9e72f67d46c this method call is no longer needed in the update step as it is triggered in the new finalisation file.

### CODE REVIEW

**Comment by zero-24** [comment]
What do you think? Should we add a quick comment that this function is called by that script so that no one comes to the idea to remove that function? ;)

**Comment by mbabker** [comment]
If anyone tries to remove that function they deserve to be backhanded 42 times because it is used in the standalone update file, the database fix routine (what the flipping eff!?), AND in a CLI script, and if you can't figure out it's still used the reaction is 100% deserved.

**Comment by zero-24** [comment]
I know thank you :+1:

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9e00f53cfa5d911455bbf299808d171846a4fd08<br /><br />Tested with success as follows on a 3.5.0:

1. Created one of the old files which should be deleted (on Linux: "touch" command). A list of files can be found here: [https://github.com/joomla/joomla-cms/commit/8c4bcba6da69eb8dfab64e1d6c5feaa32b560d9b](https://github.com/joomla/joomla-cms/commit/8c4bcba6da69eb8dfab64e1d6c5feaa32b560d9b "https://github.com/joomla/joomla-cms/commit/8c4bcba6da69eb8dfab64e1d6c5feaa32b560d9b").
2. Updated to a seld made 3.5.1-rc2 patched by this PR using an seld made custom URL: [http://test5.richard-fath.de/list_test6.xml](http://test5.richard-fath.de/list_test6.xml "http://test5.richard-fath.de/list_test6.xml").
3. Checked that the file created in step 1 has been deleted after the update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9655">issues.joomla.org/joomla-cms/9655</a>.</sub>

**Comment by richard67** [comment]
In case if someone else wants to test in the same way as I did, I will leave my custom URL and the patched updated container behind it available for a few days or until this PR has RTC or is merged.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 9e00f53cfa5d911455bbf299808d171846a4fd08<br /><br />It works. I have just tested the update Server from @richard67 thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9655">issues.joomla.org/joomla-cms/9655</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9655">issues.joomla.org/joomla-cms/9655</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge 
Looks like this has to go in stable.

**Comment by wilsonge** [comment]
For 3.5.2 - this is a good optimisation but not something that requires us pushing back 3.5.1 again and releasing another new RC

**Pull request merged**
