### PR TITLE
Global Options: Different Tooltips on 3 Datetypes (Update en-GB.ini)

### PR DESCRIPTION
**Pull request by pau1a**
Pull Request for Issue #25343 .

### Summary of Changes

Language string adjustments to provide consistency of user experience

### Testing Instructions

Visit "Article - Global Options", view tooltips

### Expected result

Consistent tooltips over "Show Publish Date","Show Modify Date","Show Create Date"

### Actual result

As above

### Documentation Changes Required

None

### CODE REVIEW

**Comment by alikon** [comment]
@franz-wohlkoenig can you have a look, if it solve your issue #25343

**Comment by infograf768** [comment]
#25343 is describing also another issue
https://github.com/joomla/joomla-cms/issues/25343#issuecomment-510754687

We have this string 9 times in 8 different files (same for Publish and Created)
```
ROOT/administrator/components/com_content/config.xml:208: 			description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/administrator/components/com_content/models/forms/article.xml:467: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/administrator/components/com_content/models/forms/article.xml:750: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/archive/tmpl/default.xml:253: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/article/tmpl/default.xml:198: 			description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/categories/tmpl/default.xml:616: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/category/tmpl/blog.xml:534: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/category/tmpl/default.xml:540: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
ROOT/components/com_content/views/featured/tmpl/default.xml:348: 				description="JGLOBAL_SHOW_MODIFY_DATE_DESC"
```

Therefore I am rather in favor of modiying
JGLOBAL_SHOW_CREATE_DATE_DESC
 => JGLOBAL_SHOW_MODIFY_DATE_DESC // NO need to change
JGLOBAL_SHOW_PUBLISH_DATE_DESC

to NOT include `This is a global setting but can be changed at Menu and Article levels.`

and create 3 new strings in `administrator/language/en-GB/en-GB.com_content.ini`
COM_CONTENT_SHOW_CREATE_DATE_DESC
COM_CONTENT_SHOW_MODIFY_DATE_DESC
COM_CONTENT_SHOW_PUBLISH_DATE_DESC

which would include `This is a global setting but can be changed at Menu and Article levels.`
and would replace the existing ones in config.xml

**Comment by brianteeman** [comment]
> which would include This is a global setting but can be changed at Menu and Article levels.

Do we have this string on ALL settings where this would apply?

**Comment by infograf768** [comment]
> Do we have this string on ALL settings where this would apply?

Indeed not.

Then the simplest solution is to simply delete `This is a global setting but can be changed at Menu and Article levels.` from
 JGLOBAL_SHOW_CREATE_DATE_DESC
and
JGLOBAL_SHOW_PUBLISH_DATE_DESC

and we are done.

**Comment by brianteeman** [comment]
💯

**Comment by infograf768** [comment]
But we also use this note in Config
` COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC="These settings apply for article layouts unless they are changed for a specific menu item."`

which is incomplete as the settings also concern single articles.
Imho we should complete that.

**Comment by ghost** [comment]
Tooltip for "Show Publish Date" talks about "(…) Category, Menu and Article levels" but on Category-Level it cannot be set.
60244552-eaac2500-98ba-11e9-88a7-53e3cefd6991

**Comment by infograf768** [comment]
@franz-wohlkoenig
Indeed. Another reason to take off this phrase from both strings and Update `COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC`

@pau1a
Can you update this PR or shall I close and open a new PR with the changes above?

**Comment by pau1a** [comment]
@infograf768 sure I will update this one

**Comment by pau1a** [comment]
> But we also use this note in Config
> ` COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC="These settings apply for article layouts unless they are changed for a specific menu item."`
> 
> which is incomplete as the settings also concern single articles.
> Imho we should complete that.

How do we want this completed specifically?

**Comment by infograf768** [comment]
maybe
`COM_CONTENT_CONFIG_ARTICLE_SETTINGS_DESC="These settings apply for article layouts unless they are changed for a specific menu item or article."

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 142c98fe7d7685e7da7522353c8548f11bd1b523<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25556">issues.joomla.org/tracker/joomla-cms/25556</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 142c98fe7d7685e7da7522353c8548f11bd1b523<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25556">issues.joomla.org/tracker/joomla-cms/25556</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by ghost** [comment]
thanks for test @infograf768 and @pau1a for Screen Shot 2019-07-16 at 14 52 04 (if its true).

**Comment by pau1a** [comment]
> thanks for test @infograf768 and @pau1a for Screen Shot 2019-07-16 at 14 52 04 (if its true).

Yes its true. Thanks and glad to be involved. Hope to get more involved in the future :)

**Comment by infograf768** [comment]
tks

**Comment by imanickam** [comment]
Very minor point.

In the file [administrator/language/en-GB/en-GB.ini, in the following language string, why a SPACE has been added after the sentence completion?

```
- JGLOBAL_SHOW_MODIFY_DATE_DESC="If set to Show, the date and time an Article was last modified will be displayed."
+ JGLOBAL_SHOW_MODIFY_DATE_DESC="If set to Show, the date and time an Article was last modified will be displayed. "

```
My guess is that this language string was earlier modified to add the second sentence just like in the Create and Publish dates.  Now that the second sentence will be shown as an informational message for the tab, there is no need to add the extra space in the above mentioned language string, unless I am missing something.  The net result is that the language string mentioned will not get changed.

**Comment by ghost** [comment]
@imanickam thanks for your Report. Can you please open a new Issue as comments on closed didn't get much Notice?

**Comment by infograf768** [comment]
Will directly make PR now.

**Comment by infograf768** [comment]
In fact, this has already been corrected. No need to patch.

**Comment by infograf768** [comment]
see
https://github.com/joomla/joomla-cms/commit/39b2ba7a97007e6fcd72cd4dbbf23934dd7e265e

**Pull request merged**
