### PR TITLE
Correct archived article links in search results

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #22395.

### Summary of Changes

Corrects links to archived articles in search results.

### Testing Instructions

Make sure `Archived Articles` option is enabled in `Search - Content` plugin.

Create an article. Set status to archived.
Search for the article using standard search (`com_search`).
Inspect link to article in search results.

### Expected result

Link opens article, e.g. `http://localhost/index.php/site-map/articles/9-uncategorised/67-whats-new-in-15`

### Actual result

Link opens archived view, e.g. `http://localhost/index.php/using-joomla/extensions/components/content-component/archived-articles/2019?view=archive&month=5`

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
@HerKle @beejay41 please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by beejay41** [comment]
> @HerKle @beejay41 please test > https://docs.joomla.org/Testing_Joomla!_patches

I've applied the change to my test system and it now returns the expected link. Bug fixed.

My only criticism is that there are now 2 identical pieces of code ( for normal and archived articles), so if there is a need to make changes in future, the duplicate (archive) code could be overlooked. Also, only do things once.

**Comment by ghost** [comment]
@beejay41 please mark your test as successfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by SharkyKZ** [comment]
@beejay41 I was thinking the same thing. But I'll leave code cleanup for another time.

I'm also not sure whether the queries are correct. They don't look for articles in archived categories.

**Comment by alikon** [comment]
there is no archived category iirc  it's a value of the state field  maybe (2)

**Comment by brianteeman** [comment]
This doesnt look correct to me. You need to also see what the archive module and archive view create

**Comment by SharkyKZ** [comment]
@alikon same thing. Query looks for articles in published but not in archived categories. Both when looking for published and archived articles.

**Comment by SharkyKZ** [comment]
@brianteeman this is fine. Links to archive view were added as a workaround for some 1.5 issue. See https://developer.joomla.org/joomlacode-archive/issue-23764.html.

**Comment by beejay41** [comment]
> @beejay41 please mark your test as successfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

Sorry, new to this. I did as requested, and it looks to have updated the Joomla tracker, but not here. 2FA error, but I'm not using 2FA anywhere here.

**Comment by ghost** [comment]
tried to alter test of @beejay41 but get:

Screen Shot 2019-05-23 at 15 44 01

**Comment by brianteeman** [comment]
@franz-wohlkoenig you will need to speak to @HLeithner about this. There has been a change in the authentication settings on github which you are hitting and need to resolve

**Comment by HLeithner** [comment]
Michael is working on this problem.

**Comment by brianteeman** [comment]
@HLeithner I assumed someone was - I just wanted to let @franz-wohlkoenig know

**Comment by ghost** [comment]
thanks for info, guys.

@beejay41 so please wait until this Problem is solved.

**Comment by mbabker** [comment]
It's all sorted.

**Comment by infograf768** [comment]
@mbabker 
In the meanwhile this PR is not displaying in issues:
https://github.com/joomla/joomla-cms/pull/24993

Can you help?

**Comment by mbabker** [comment]
Comment on it, update it, do anything that triggers a webhook from GitHub to the tracker and that will sort it.  It'll take me longer to log into the server and run the CLI command than it will for someone to do that.

**Comment by infograf768** [comment]
tks, that worked.

**Comment by ghost** [comment]
thanks @mbabker 

@beejay41 your testresult is altered.

**Comment by beejay41** [comment]
> thanks @mbabker
> 
> @beejay41 your testresult is altered.

Cheers.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba42aa2a44186220b9b0b471fd211714b6007474<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24990">issues.joomla.org/tracker/joomla-cms/24990</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24990">issues.joomla.org/tracker/joomla-cms/24990</a>.</sub>

**Comment by SniperSister** [comment]
Merged, thanks!

**Pull request merged**
