### PR TITLE
CLEANING-JCacheControllerCallback

### PR DESCRIPTION
**Pull request by Mathewlenning**
1. Removed the long awkward if -> elseif -> elseif -> else structure from JCacheControllerCallback::get
2. Added private methods to normalise the callback.
3. Removed "else" where I felt comfortable doing so.

### CODE REVIEW

**Comment by Mathewlenning** [comment]
I don't think there is anything I can do to resolve this one. I added the additional check from the last merge to this class, but it isn't working.

**Comment by dgt41** [comment]
Try to rebase the repo to the latest staging. I am using tower (gui) so all i do is make a pull from latest staging with the option to rebase enabled, i guess something similar should be the command on the terminal. But I don’t know if this is the recommended solution here 😄

**Comment by Mathewlenning** [comment]
@dgt41 Thanks. I'm using PHPStorm and I do remember a rebase option. Let me try and see if it works.

**Comment by Mathewlenning** [comment]
I pulled from staging, but but it doesn't seem to be working.

**Pull request closed without merging**
