### PR TITLE
[4.0] Add period

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add period to the alert message.

### Testing Instructions
Code review.

or 

Go to System > Update > Extensions
Click `Clear Cache` button.
See message.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ffd564adff0b697022e9044ec106d35c590ad42f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33132">issues.joomla.org/tracker/joomla-cms/33132</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ffd564adff0b697022e9044ec106d35c590ad42f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33132">issues.joomla.org/tracker/joomla-cms/33132</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33132">issues.joomla.org/tracker/joomla-cms/33132</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
