### PR TITLE
[com-newsfeeds] using a weblinks string

### PR DESCRIPTION
**Pull request by brianteeman**
The hits field was using a string from com_weblinks in error

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 83859d356f077ac5640e81428c0bddf9418f4794<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15201">issues.joomla.org/tracker/joomla-cms/15201</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 83859d356f077ac5640e81428c0bddf9418f4794<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15201">issues.joomla.org/tracker/joomla-cms/15201</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
Please check also this issue https://github.com/joomla/joomla-cms/pull/15464 before merging. We should take the decision to remove it or keep it.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
