### PR TITLE
[4.1] Protect Manual/Test Runs of Tasks against CSRF

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36454.

### Summary of Changes
Adds CSRF protection for  task "test" trigger endpoint. Token is injected in the list template.

### Testing Instructions
- Create Scheduled Task, note ID.
- Goto `http://example.com/administrator/index.php?option=com_ajax&format=json&plugin=RunSchedulerTest&group=system&id={TaskID}` in another tab.

### Actual result BEFORE applying this Pull Request
Task is executed.

### Expected result AFTER applying this Pull Request
Task is not executed since request lacks token.

### Documentation Changes Required
\-

### CODE REVIEW

**Comment by ditsuke** [comment]
@PhilETaylor please test and review.

**Comment by PhilETaylor** [comment]
```
/********/src/build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
15s
8	  21:176  error  Strings must use singlequote  quotes
```

**Comment by ditsuke** [comment]
> ```
> /********/src/build/media_source/com_scheduler/js/admin-view-run-test-task.es6.js
> 15s
> 8	  21:176  error  Strings must use singlequote  quotes
> ```

@PhilETaylor fixed

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 73414c5d2de402fe0c4aeae86bd89dbcd2da9e92<br /><br />With the patch the task does not run on GET request. The "Last Run Date" confirms that.
```
{
  "success": true,
  "message": null,
  "messages": null,
  "data": []
}
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36518">issues.joomla.org/tracker/joomla-cms/36518</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 73414c5d2de402fe0c4aeae86bd89dbcd2da9e92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36518">issues.joomla.org/tracker/joomla-cms/36518</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36518">issues.joomla.org/tracker/joomla-cms/36518</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
