### PR TITLE
[5.0] finder date a11y

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #41198 .

### Summary of Changes
All inputs must have a label. This PR adds an "invisible" label to the two date operators

### Testing Instructions
Run a search, for example, for the word 'joomla'
On the results page, set filters to specify the date range (selection options: 'before', 'after', 'exactly')

_Note that to test this you need to go to the component options and set Date filters to show as they are hidden by default_

### Actual result BEFORE applying this Pull Request
a11y testing tools report two errors
view source and you will see a select without a label
image

### Expected result AFTER applying this Pull Request
a11y testing tools report no errors
view source and you will see a select with a label

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
first rule of aria is not to use aria and to always use native html if possible

https://www.deque.com/blog/top-5-rules-of-aria/

**Comment by HLeithner** [comment]
https://stackoverflow.com/questions/43105006/should-i-use-arial-label-or-a-label-element-that-is-visually-hidden#:~:text=Using%20aria-label%20is%20preferable,visually%20hide%20a%20label%20element.&text=But%20note%20that%20you%20don,field%20and%20the%20submit%20button.

which says: "Using aria-label is preferable to relying on CSS to visually hide a label element." and links to https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/ARIA14 

it's WCAG 2.0 but I didn't find anything saying something different in 3.0 but tbh didn't read the every...

also your source speaks of a "visible" label or a aria-label...

**Comment by brianteeman** [comment]
the first rule of aria always wins

**Comment by HLeithner** [comment]
> the first rule of aria always wins

sorry but the WCAG says something different and the rule 5 also says something different.

anyway, will come back to this later

**Comment by brianteeman** [comment]
You always know better than anyone else.

**Comment by zwiastunsw** [comment]
@HLeithner: The label can sometimes be invisible, but an accessible name is needed for assistive technology users, such as when the context and appearance of the control determine its purpose. Then those who control by voice can issue the appropriate command (e.g., Search, Close). You can, of course, use a label and hide it visually with CSS. But consider that this available name is needed by assistive technology users. It is better, simpler and more reliably conveyed using aria-label  (the first rule of aria always wins).
Aria was created to provide accessibility components where HTML does not or cannot provide them with HTML. Therefore, use ARIA when you must, not when you can. If you use a native HTML element in this case, you have to hide it visually right afterwards, which causes complications and can cause accessibility problems. 
A better choice: use aria-label.
I hope I have clarified. Brian is right.

**Comment by HLeithner** [comment]
> @HLeithner: The label can sometimes be invisible, but an accessible name is needed for assistive technology users, such as when the context and appearance of the control determine its purpose. Then those who control by voice can issue the appropriate command (e.g., Search, Close). You can, of course, use a label and hide it visually with CSS. But consider that this accessible name is needed by assistive technology users. It is better, simpler and more reliably conveyed using aria-label (the first rule of aria always wins). Aria was created to provide accessibility components where HTML does not or cannot provide them with HTML. Therefore, use ARIA when you must, not when you can. If you use a native HTML element in this case, you have to hide it visually right afterwards, which causes complications and can cause accessibility problems. A better choice: use aria-label. I hope I have clarified. Brian is right.

I appreciate your comment, that's exactly what I said. I think that got lost in translation.

and  brian please keep your 

> You always know better than anyone else.

for you self, thanks

**Comment by HLeithner** [comment]
maintainers meeting yesterday decided that accessibility team in this case @drmenzelit will take a look and takes a decision.

**Comment by zwiastunsw** [comment]
What is the a11y team to decide? 

Brian offered the correct solution to the reported problem. Before this fix, the screen reader does not announce what the selection lists are for. After the implementation of the fix, the screen reader correctly announces what the selection list is for and correctly announces the date input fields. In terms of accessibility, it is OK. 

Also, if the user turns off the stylesheet, they will receive full information (see screenshot)
view with style sheets disabled

If I were to further improve this element, I would make the indication specifying the date format visible. The title attribute is not a reliable way to convey instructions and directions for filling in forms.

**Comment by drmenzelit** [comment]
Sadly Brian closed the pull request, so we need to create it again.

**Comment by zwiastunsw** [comment]
@drmenzelit: Does this mean that we should trash a job well done and once again fix something that has already been fixed? 
I don't understand.

**Comment by zwiastunsw** [comment]
@brianteeman  thx

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on ff94310afa8e067b53a1cee463b97ebe30676803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41429">issues.joomla.org/tracker/joomla-cms/41429</a>.</sub>

**Comment by alikon** [comment]
i'll don't mark  this as a succesful test,  cause i've only checked the  html , hope that someonelse do the last mile

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on ff94310afa8e067b53a1cee463b97ebe30676803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41429">issues.joomla.org/tracker/joomla-cms/41429</a>.</sub>

**Comment by rachelwalraven** [comment]
I have tested this item :white_check_mark: successfully on ff94310afa8e067b53a1cee463b97ebe30676803<br /><br />label is added after patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41429">issues.joomla.org/tracker/joomla-cms/41429</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41429">issues.joomla.org/tracker/joomla-cms/41429</a>.</sub>

**Comment by HLeithner** [comment]
> Furthermore, in my opinion, this fix should be implemented in Joomla 4 and not only in Joomla 5.

shouldn't be done because it could break frontend templates (also true for 5.0)

**Comment by brianteeman** [comment]
> > Furthermore, in my opinion, this fix should be implemented in Joomla 4 and not only in Joomla 5.
> 
> shouldn't be done because it could break frontend templates (also true for 5.0)

not true

**Comment by HLeithner** [comment]
> not true

it is, if you don't have the class "element-invisible" which is only in Atum and Cassiopeia you get something like that:
image

Tested on a 4.3 site by just adding the label to the Startdate not using cassiopeia (I think it's yootheme)

**Comment by brianteeman** [comment]
If that class is not present then it will have an impact in other places. Also not covered by BC policy

**Comment by Fedik** [comment]
> If that class is not present then it will have an impact in other places

@brianteeman I think it should be `visually-hidden` as we use in other our code, instead of `element-invisible`.
I checked we mostly use  `visually-hidden` , but did not found `element-invisible`.

**Comment by brianteeman** [comment]
Feel free to edit the pr I don't use the computer on shabbat

**Comment by brianteeman** [comment]
Feel free to edit the pr I don't use the computer on shabbat

**Comment by HLeithner** [comment]
@brianteeman do you update this before weekend?

**Comment by brianteeman** [comment]
Sorry. Thought someone had already done it. Will try tonight when I get back from hospital

**Comment by brianteeman** [comment]
changes made as requested

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
