### PR TITLE
Revert "[com_finder] Allow loading plugin language strings from extension folder"

### PR DESCRIPTION
**Pull request by rdeutz**
Reverts joomla/joomla-cms#12204

### CODE REVIEW

**Comment by brianteeman** [comment]
Why is this reverted? Wrong branch?

**Comment by rdeutz** [comment]
jepp wrong branch, thought it is 3.7.x

**Comment by brianteeman** [comment]
Can you not directly change the branch on the Pr. Thought that was possible now

**Comment by rdeutz** [comment]
not sure if I can do it after it is merged, had done it if had seen it before

**Comment by mbabker** [comment]
You can't re-open a merged PR, so fixing the target branch isn't possible at this point.

**Comment by rdeutz** [comment]
think before merge helps ;-)

**Pull request merged**
