### PR TITLE
[5] add2scheduler-sessiongc #41326 - alpha sorting

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request for PR #41326 .

### Summary of Changes

alpha sorting strings

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

not alphabetically sorted

### Expected result AFTER applying this Pull Request

alphabetically sorted

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 47c666fb947cc141175e9c77e05eb23f79198d3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41601">issues.joomla.org/tracker/joomla-cms/41601</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 47c666fb947cc141175e9c77e05eb23f79198d3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41601">issues.joomla.org/tracker/joomla-cms/41601</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41601">issues.joomla.org/tracker/joomla-cms/41601</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
