### PR TITLE
[Fields] multiple

### PR DESCRIPTION
**Pull request by brianteeman**
This PR is a cosmetic change for consistency that ensures the param for multiple is towards the end of the options and not the first. It was already thiis way in some plugins but not all

### CODE REVIEW

**Comment by brianteeman** [comment]
no idea why it says there are conflicts - makes no sense to me

**Comment by Bakual** [comment]
Conflict comes from https://github.com/joomla/joomla-cms/pull/14683 which changed the string `PLG_FIELDS_INTEGER_PARAMS_USE_GLOBAL` to `COM_FIELDS_FIELD_USE_GLOBAL`

**Comment by brianteeman** [comment]
OK I tried  changing the string - that still says conflicts. Will have to try again when I have had more coffee

**Comment by Bakual** [comment]
You will need to use a conflict solving tool to solve the conflicts. You can't just manually adjust the file unfortunately.

**Comment by brianteeman** [comment]
@Bakual and thats where I always fail ;(

**Comment by brianteeman** [comment]
closed as I couldnt rebase the PR so created a new one instead :(

See #14997

**Pull request closed without merging**
