### PR TITLE
[4.0] update build scripts

### PR DESCRIPTION
**Pull request by brianteeman**
Added the new files from the root folder that should not be included in packages by the build script in 4.0

### CODE REVIEW

**Comment by zero-24** [comment]
@mbabker can you take care of that in the nightly build script too?

**Comment by zero-24** [comment]
Thanks @brianteeman

**Comment by brianteeman** [comment]
@zero-24 no problem

**Comment by zero-24** [comment]
I have opend a issue for the nightly build thing to be sure it did not get lost: https://github.com/joomla/joomla-websites/issues/925

**Pull request merged**
