### PR TITLE
[4] When we have finished with sample data, unpublish its module and plugins

### PR DESCRIPTION
**Pull request by PhilETaylor**
As requested in https://github.com/joomla/joomla-cms/pull/33150

### Summary of Changes

When we have finished with sample data, unpublish its module and plugins - therefore gaining a tiny bit of performance.

### Testing Instructions

Install Joomla 4
Install any of the sample data
refresh the Home Dashboard - note the module is no longer there
visit the Plugins and see they are unpublished
No side effects. 

### Actual result BEFORE applying this Pull Request

After using the sample data plugins, the module and plugins remain published, which is more db calls, more code running on each page load

### Expected result AFTER applying this Pull Request

module and plugins are uninstalled for the life of a live site - gaining a tiny bit of performance as code is not run. 

### Documentation Changes Required

none

### CODE REVIEW

**Comment by PhilETaylor** [comment]
@dgrammatiko @richard67 cc

**Comment by richard67** [comment]
This will make it harder to install Blog sample data multiple times when having a multilanguage site, one time for each backend language. It will need to enable the plugin again each time.

Currently we can change language in backend and install blog sample data for each language, and when we later install another backend language, we can do that again for that language.

This will not be possible anymore in this way.

Ping @infograf768 .

**Comment by PhilETaylor** [comment]
> This will not be possible anymore in this way.

Not impossible, just more steps :) you would need to republish the module and plugin each time.

Lets keep this in context. for 99.9% of the life of a REAL Joomla site, the Sample Data plugin/Module are not needed to be running on the site.

The sample data plugin is for developers in development mode, and for those testing Joomla.

This is not a flagship feature of Joomla that is used day in and day out by 100% of those using Joomla. Its used by a select few people for a select reason.

**Comment by dgrammatiko** [comment]
> Currently we can change language in backend and install blog sample data for each language

This is a flaw in the current architecture of the sampledata plugin/modules. The CMS has all the data (installed languages and content languages) to decide (or even ask the user) if the data should be installed in one or more languages. AFAIK there's already an open issue about sampledata: https://github.com/joomla/joomla-cms/issues/32878

**Comment by richard67** [comment]
> AFAIK there's already an open issue about sampledata: #32878

That issue doesn't cover the multilanguage aspect.

Regarding this PR here it's not on me to decide if it's ok or not, I just wanted to mention that aspect here so it is not forgotten.

**Comment by infograf768** [comment]
I agree with @richard67 
We absolutely need to be able to install multingual sample data and thereafter blog sample data for each content language.

**Comment by PhilETaylor** [comment]
> We absolutely need to be able to install multingual sample data and thereafter blog sample data for each content language.

This PR doesn't stop you doing that at all.

It just means you need to REPUBLISH the module/plugin AFTER each use.

**Comment by brianteeman** [comment]
As I have stated before ad nauseum there is zero need to have the multilingual sample data plugin enabled if the site is not multilingual

**Comment by dgrammatiko** [comment]
> We absolutely need to be able to install multingual sample data and thereafter blog sample data for each content language.

If the only way to do that is by doing it manually we should pack it here and start farming...

**Comment by PhilETaylor** [comment]
> As I have stated before ad nauseum there is zero need to have the multilingual sample data plugin enabled if the site is not multilingual

tell me a check I can make to find this out. I have never used Joomla and multiple languages. Im white british, the education system only taught me one language (badly)

**Comment by dgrammatiko** [comment]
> tell me a check I can make to find this out

Count the languages in `__extensions select * where 'type' = 'language'`and the content languages in `__languages`

**Comment by infograf768** [comment]
It is very simple, once one has tested the feature at will, to start from scratch _as was always done_ and then unpublish the module.

but, as usual, do whatever you like.

**Comment by brianteeman** [comment]
Nothing in that sentence makes any sense at all

**Comment by PhilETaylor** [comment]
> then unpublish the module.

I bet 10-99% of Joomla admins will never unpublish this module manually ;-)

**Comment by richard67** [comment]
In Blog Sample Data we use this to check if we have multilanguage on:

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Language/Multilanguage.php#L43

**Comment by dgrammatiko** [comment]
> I bet 10-99% of Joomla admins will never unpublish this module manually ;-)

Anything less than 98% would be a surprise for me

**Comment by brianteeman** [comment]
@PhilETaylor see #20749

**Comment by PhilETaylor** [comment]
@brianteeman thanks - that's looks simple and that logic can be added to this PR... basically if there are more than 1 lang then we will not unpublish if you just installed the multilane sample data... simple. Keeps everyone happy.

**Comment by brianteeman** [comment]
It is simple but one person objects to it as they believe no one will know you can do it unless you shove it in front of their face until they get so annoyed with it they uninstall joomla

**Comment by PhilETaylor** [comment]
If I were (as I wanted to do) uninstalling (which means deleting the db rows and the module/plugin files from the hard disk) then I could understand... however all we are doing here is unpublishing here :) :

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33165/commits/081da589c02bf905edd99267d1b1f4904510f206 just pushed will only unpublish if the Multilane data is installed on a site with just ONE language 

Please test.

**Comment by Bakual** [comment]
The module itself should not be unpublished. Keep in mind that the module isn't exclusively used for core sample data. Each 3rd party extension can provide its own sample data as well. And I know for example DP Calendar does that.

I'm not a big fan of extensions who publish/unpublish themself. I would offer a button to directly unpublish the plugin instead. So it can be hidden with a single click.

**Comment by brianteeman** [comment]
We already have that button ;)

Disable the plugin automatically THEN
If there are no plugins to display the module is empty and as there is no point in having an empty module just hide the module. That way if an extension is installed later that has a sample data plugin it will still be displayed

**Comment by PhilETaylor** [comment]
> Each 3rd party extension can provide its own sample data as well. And I know for example DP Calendar does that.

I bet you cannot name another 5 extensions that use sample data like this ;-) ;-) ;-)

**Comment by dgrammatiko** [comment]
> I bet you cannot name another 5 extensions that use sample data like this ;-) ;-) ;-)

I can't name 5 but I can point you at https://github.com/dgrammatiko/sloth-pkg/tree/main/plg_sampledata which is way different from the core monstrosity plugins... ;)

**Comment by PhilETaylor** [comment]
LMAO - typical JS developer :) hahahahah

```php
 defined('_JEXEC') || die('<html><head><script>location.href = location.origin</script></head></html>');
```

**Comment by Bakual** [comment]
> > Each 3rd party extension can provide its own sample data as well. And I know for example DP Calendar does that.
> 
> I bet you cannot name another 5 extensions that use sample data like this ;-) ;-) ;-)

I dunno, but that was one of the initial ideas of using this approach. So instead that the extensions put their sample data hardcoded into their SQLs (like core did before), they can offer a plugin as well (like core does now).

Obviously, the module could return empty if no sample data plugin is active (don't know if it does that today already).

**Comment by Bakual** [comment]
>>  I would offer a button to directly unpublish the plugin instead. So it can be hidden with a single click.

> We already have that button ;)

@brianteeman I meant for the plugins. I know that the modules all have such a button, that's where the idea came from 😄

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/20749#issuecomment-397266453

**Comment by PhilETaylor** [comment]
> As I see it, if merged, this feature would become a hidden secret which would only be eventually used by devs and bugsquad.

Well it certainly doesn't need to command prize position on the home page of the admin console does it? it gets used less times in a sites lifetime than the number of fingers on a hand...

**Comment by Bakual** [comment]
Imho, it would be nice to be in that position if there are sample data available. Otherwise people don't see them.

But it would also nice to be able to unpublish the plugins directly from the module, as it is not very intuitive to know where they can be hidden. So a button either on each sample data set or on the module ("Manage Sample Data" for the lack of better wording) would be great.

It would also be nice if the module hides completely if no plugin is active.
Currently it shows like this:
image

I certainly wouldn't automatically unpublish anything.

**Comment by Bakual** [comment]
I've created a simple PR to hide the module if no sample data plugin is published. See https://github.com/joomla/joomla-cms/pull/33168

**Comment by Bakual** [comment]
Button to go directly to the pluginmanager to disable plugins:
https://github.com/joomla/joomla-cms/pull/33169

**Pull request closed without merging**
