### PR TITLE
[com_templates] Add submenu

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR adds a submenu to com_templates, like the one that exists for "Manage" and "Languages".
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use 3.5.0 or latest staging
2. Apply patch
3. Go to `Extensions -> Templates` and check if the submenu exists.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 39cea2a6b3256202bd831a0d2edd9d4957a828d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9725">issues.joomla.org/joomla-cms/9725</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 39cea2a6b3256202bd831a0d2edd9d4957a828d6<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9725">issues.joomla.org/joomla-cms/9725</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9725">issues.joomla.org/joomla-cms/9725</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing @brianteeman @MATsxm

**Pull request merged**
