### PR TITLE
[5.1] Convert mod_tags_popular to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the popular tags site module to service provider.

### Testing Instructions

1. Make sure you have site module mod_tags_popular published
2. Add some tags and assign them to several content items
3. You should see module output
4. You should not see module output, when all tags are unpublished/deleted and "Show No results text" module setting is disabled.
5. You should see module output with no results message, when all tags are unpublished/deleted and "Show No results text" module setting is enabled.

mod_tags_popular

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 46f56aa9abaefdc7257fd4de415f2b0e009f1b82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42899">issues.joomla.org/tracker/joomla-cms/42899</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 46f56aa9abaefdc7257fd4de415f2b0e009f1b82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42899">issues.joomla.org/tracker/joomla-cms/42899</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42899">issues.joomla.org/tracker/joomla-cms/42899</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also to the testers @fgsw @viocassel

**Pull request merged**
