### PR TITLE
[4.0] Only add debug information during installation on HTML documents

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #20524.

### Summary of Changes
Adds debug information only for HTML documents.

### Testing Instructions
Install a clean joomla 4.0-dev after setting the `installation/localise.xml` file to debug
```
<?xml version="1.0" encoding="utf-8"?>
<localise version="3.6" client="installation">
	<forceLang></forceLang>
	<helpurl></helpurl>
	<debug>1</debug>
	<sampledata></sampledata>
	<params/>
</localise>
```

### Expected result
Installer runs through.

### Actual result
Installer does not flip to the last page.

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on a22c8ff51d2b5dd3846eef2d3ca6626f92f82d0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20528">issues.joomla.org/tracker/joomla-cms/20528</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on cd0f45738d47f89bbac0b6000df4a10b606838bc<br /><br />Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20528">issues.joomla.org/tracker/joomla-cms/20528</a>.</sub>

**Comment by infograf768** [comment]
Can be merged. RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20528">issues.joomla.org/tracker/joomla-cms/20528</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on cd0f45738d47f89bbac0b6000df4a10b606838bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20528">issues.joomla.org/tracker/joomla-cms/20528</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
