### PR TITLE
[Sql azure] Normalize update sql files

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Normalizes all sql azure update files.
- always use `SET IDENTITY_INSERT [#__xxxx] ON/OFF;` when inserting (like joomla.sql)
- `INSERT` to `INSERT INTO` (like joomla.sql)
- Quote all table names and db field names
- Always use `'` to quote string values.
- Code style
### Testing Instructions

Mainly code review. (easier to check code diff without white spaces changes) https://github.com/joomla/joomla-cms/pull/11722/files?w=1
If anyone could test and upgrade from 2.5.28 to 3.6.x would be great. Don't have sql azure to test,
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
The travis javascript tests error has nothing to do with this PR. 
Mantainers please rerun travis here.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c321f7711be7c4e995128dbfca25dd015c57a6d9<br /><br />on code review still unable to test on MSSQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11722">issues.joomla.org/joomla-cms/11722</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on c321f7711be7c4e995128dbfca25dd015c57a6d9<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11722">issues.joomla.org/joomla-cms/11722</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11722">issues.joomla.org/joomla-cms/11722</a>.</sub>

**Comment by zero-24** [comment]
Thanks :+1:

**Pull request merged**
