### PR TITLE
CodeMirror updated to 5.18.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .
### Summary of Changes

http://codemirror.net/doc/releases.html
### Testing Instructions

Just use CodeMirror and expect it to work as usual or better.
### Documentation Changes Required

Nope.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for doing this again

One step that we just realised you havent been doing is what to do when files are deleted. If a file is removed then it should be added to https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11752">issues.joomla.org/joomla-cms/11752</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Ah, I suppose that would be the Jade mode.

**Comment by brianteeman** [comment]
Thank you

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 360f4ee7b7dcf447b05a14146fe33b37a8f292a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11752">issues.joomla.org/joomla-cms/11752</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 360f4ee7b7dcf447b05a14146fe33b37a8f292a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11752">issues.joomla.org/joomla-cms/11752</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11752">issues.joomla.org/joomla-cms/11752</a>.</sub>

**Pull request merged**
