### PR TITLE
Fix wrong update SQL file names

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Fix wrong update SQL file names caused by commit https://github.com/joomla/joomla-cms/commit/a73ee4556765dba6a705ec8feab5f2ee0643f892 .

### Testing Instructions

Code review.

### Actual result BEFORE applying this Pull Request

Wrong file name "3.10.7-2022-02-20.sql.sql" for the postgresql and the sqlazure files.

### Expected result AFTER applying this Pull Request

Right file name "3.10.7-2022-02-20.sql" for the postgresql and the sqlazure files like it is already for the mysql file.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by zero-24** [comment]
> I will make a PR in a few minutes for the 4.1-dev branch which also should go up into 4.2-dev to fix the wrong file name also in the list of files to be deleted on update in script.php.

it has bever been released right?

**Comment by richard67** [comment]
Setting the release blocker label because we should not ship with wrong file names. Even if that will not cause problems at the update, it will later require to delete both the files with the wrong and with the right name when updating to 4.1 or 4.2, and that would simply be silly.

**Comment by richard67** [comment]
@zero-24 It has been release only as release candidate. Does this justify to keep the deletion of the files with the wrong names in script.php on 4.1-dev and 4.2-dev? I think we should keep it to be safe. Otherwise in case if someone updates from 3.10.7 RC 1 to 4.1 or 4.2, there might be a problem.

**Comment by richard67** [comment]
@zero-24 If we want to be safe also for an update from 3.10.7 RC1 to 3.10.7 RC 2, I would have to add deletion of the file with the wrong name even to script.php here in the 3.10-dev branch. Shall I do that?

**Comment by richard67** [comment]
PR for 4.1-dev is #37383 .

**Comment by zero-24** [comment]
merged thanks

**Pull request merged**
