### PR TITLE
[4.0] Workflow preinstalled default category

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #23464 .

### Summary of Changes
Set the uncategories category workflow selection to "use default" as described in the issue.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/23464

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8e1275c614c27b3a580ad653d9e199bdf6a077f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23701">issues.joomla.org/tracker/joomla-cms/23701</a>.</sub>

**Comment by wojsmol** [comment]
@zero-24 Please fix rips issue.

**Comment by brianteeman** [comment]
Just wondering what happens when you upgrade from j3 as they don't have a work flow set. Would it be better to not store anything in the category if it's going to be "use default" and instead make the code use default if no workflow is set.

**Comment by bembelimen** [comment]
The default workflow is available after a migration:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-05-15.sql#L35

**Comment by brianteeman** [comment]
Sorry you misunderstood me. It is indeed available but its not applied to all existing categories because it needs to be saved as ` "workflow_id":"use_default"` in the params field. That would mean opening every category and saving it again to set the value. Unless I have misunderstood the code (and I might have) I am suggesting that if there is no workflow_id set then it will default to "use_default"

**Comment by bembelimen** [comment]
Ah, now I understand, the expected default of the select is "use_default" (https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/forms/category.xml#L18).

When no workflow is assinged to the category, it falls back to the default one: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/ArticleModel.php#L1296

**Comment by brianteeman** [comment]
so to be clear this pr could also have simply removed the `"workflow_id":"1"` instead of changing it to `"workflow_id":"use_default"`

thats what confused me

**Comment by bembelimen** [comment]
Yes, that would have been working, too.

**Comment by brianteeman** [comment]
Now its clear - thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
