### PR TITLE
Change the way JTableUser::store saves groups

### PR DESCRIPTION
**Pull request by jaworskimatt**
See http://issues.joomla.org/tracker/joomla-cms/5138

If JTable::store() happens on the same user concurrently, it will eventually lead to loss of #__user_usergroup_map rows for that user. Because JTable::store() deletes everything from #__user_usergroup_map and then re-adds one by one, if that process happens multiple times in parallel for the same user, the inserts and deletes get mixed up.

This is a fix for this, that instead of performing "delete and re-insert one by one", grabs the records from the database, loops through them, decides which should stay and which should go based on $this->groups and then adds new ones (if any) from $this->groups

### CODE REVIEW

**Comment by rdeutz** [comment]
I think it is way better to read/compare and then insert/delete then delete everything and insert. Most of the time there isn't any change in the group member ship so nothing happened at all. Transactions or locking would be the best solution but this here is a step to make it better. Maybe the joomsocial guys should also check if they really need to change the user object every millisecond.

**Comment by Hackwar** [comment]
Please see #6065 for a better solution.

**Comment by pulsarinformatique** [comment]
Hi
It seems the bug remains on J3.4. We just encountered it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5144">issues.joomla.org/joomla-cms/5144</a>.</sub>

**Comment by izharaazmi** [comment]
Well, long forgotten thread. 

I see this PR `unset`s the values from `$this->groups` that I think is not appropriate. Am I correct?

**Pull request closed without merging**
