### PR TITLE
[5.2] svg sanitize update

### PR DESCRIPTION
**Pull request by brianteeman**
I dont know why it didnt get updated but we should be using the latest version

summary of changes

- 0.19.0 Preserve libxml errors after failed parsing
- 0.18.0 Allow the enabling of loading large files
- 0.17.0 Feature/8.3 support
- 0.16.0 PHP 5.6 compatibility

### CODE REVIEW

**Comment by heelc29** [comment]
> I dont know why it didnt get updated

Perhaps... https://getcomposer.org/doc/articles/versions.md#caret-version-range-
```For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0 and ^0.0.3 as >=0.0.3 <0.0.4.```

**Comment by brianteeman** [comment]
@heelc29 thanks - i didnt know that but it explains a lot

**Comment by HLeithner** [comment]
Rebased it for 5.2, we will not have a 5.1 release any more, not sure if it's not too late for 5.2

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
merge conflict fixed

**Comment by Hackwar** [comment]
I took the liberty to updating it to the latest version and fixing the broken composer.lock. When the tests pass, I'll merge this. Reviewing the changes between 0.15.4 and 0.20.0 this is all backwards compatible.

**Comment by brianteeman** [comment]
Thanks

**Comment by Hackwar** [comment]
Thank you for your contribution @brianteeman

**Pull request merged**
