### PR TITLE
Add tooltips to icons in new com_categories view

### PR DESCRIPTION
**Pull request by brianteeman**
The awesome PR from @pe7er to add columns in the category manager to display the number of published/unpublished/archived/deleted items in a category.

This PR adds a tooltip to label the icon

### CODE REVIEW

**Comment by brianteeman** [comment]
(note it uses the strings for ITEMS as this view is common to all extensions that use com_categories)

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 8e04286a78d1aa58def8f93de2a5076ceaeb5520<br /><br />Thanks Brian works great.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8460">issues.joomla.org/joomla-cms/8460</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 8e04286a78d1aa58def8f93de2a5076ceaeb5520<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8460">issues.joomla.org/joomla-cms/8460</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8460">issues.joomla.org/joomla-cms/8460</a>.</sub>

**Pull request merged**
