### PR TITLE
[mod_banners] - tooltip text

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #26819 .

### Summary of Changes
changed from tags to meta keywords

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman Could you have a look on the changed text? From my point of view the change made by this PR is 100% correct. But my English teachers would have said that it could be simplified, avoiding repeating the "meta keywords". Maybe something like "Banner is selected by matching its meta keywords to those of the current document."?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 500ffa75bf050133ec176d0f427427787c48fca8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26883">issues.joomla.org/tracker/joomla-cms/26883</a>.</sub>

**Comment by brianteeman** [comment]
you are both correct. As this is such a stupid illogical function I think this proposal is the one that provides the greater clarity<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26883">issues.joomla.org/tracker/joomla-cms/26883</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 500ffa75bf050133ec176d0f427427787c48fca8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26883">issues.joomla.org/tracker/joomla-cms/26883</a>.</sub>

**Comment by richard67** [comment]
RTC.

**Comment by richard67** [comment]
Why does that bot now remove the language change label?

**Comment by richard67** [comment]
@alikon Ah, can it be that I have to do both, set label "RTC" and change status to "ready to commit" in the tracker?

**Comment by alikon** [comment]
not sure... i think the issue bot just only need a bit of care

**Comment by richard67** [comment]
Bot needs care? You mean I should offer him (or her?) a beer or give him/her a massage? 😄

**Comment by priyankaSahutekdi** [comment]
I have tested this item :white_check_mark: successfully on 500ffa75bf050133ec176d0f427427787c48fca8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26883">issues.joomla.org/tracker/joomla-cms/26883</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
