### PR TITLE
[4.3] update help toc

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #40271 .
@obuisard Issue is a Release Blocker

### Summary of Changes

run `build/helpTOC.php`

New entries:

- [Guided Tours: New or Edit Step](https://docs.joomla.org/Help4.x:Guided_Tours:_New_or_Edit_Step)
- [Guided Tours: New or Edit Tour](https://docs.joomla.org/Help4.x:Guided_Tours:_New_or_Edit_Tour)
- [Guided Tours: Steps](https://docs.joomla.org/Help4.x:Guided_Tours:_Steps)
- [Guided Tours](https://docs.joomla.org/Help4.x:Guided_Tours)
- [Joomla Update](https://docs.joomla.org/Help4.x:Joomla_Update)

Renamed (because they are redirects):

| Old | New |
| --- | --- |
| [Articles: New or Edit Category](https://docs.joomla.org/Help4.x:Articles:_New_or_Edit_Category) | [Articles: Edit Category](https://docs.joomla.org/index.php?title=Help4.x:Articles:_Edit_Category&oldid=945626) |
| [Component: Field Groups](https://docs.joomla.org/Help4.x:Component:_Field_Groups) | [Field Groups](https://docs.joomla.org/index.php?title=Help4.x:Field_Groups&oldid=955524) |
| [Component: Fields](https://docs.joomla.org/Help4.x:Component:_Fields) | [Fields](https://docs.joomla.org/index.php?title=Help4.x:Fields&oldid=955286) |
| [Component: New or Edit Field](https://docs.joomla.org/Help4.x:Component:_New_or_Edit_Field) | [Fields: Edit](https://docs.joomla.org/index.php?title=Help4.x:Fields:_Edit&oldid=953058) |
| [Component: New or Edit Field Group](https://docs.joomla.org/Help4.x:Component:_New_or_Edit_Field_Group) | [Field Groups: Edit](https://docs.joomla.org/index.php?title=Help4.x:Field_Groups:_Edit&oldid=955690) |
| [Contacts: New or Edit](https://docs.joomla.org/Help4.x:Contacts:_New_or_Edit) | [Contacts: Edit](https://docs.joomla.org/index.php?title=Help4.x:Contacts:_Edit&oldid=945224) |
| [Contacts: New or Edit Category](https://docs.joomla.org/Help4.x:Contacts:_New_or_Edit_Category) | [Contacts: Edit Category](https://docs.joomla.org/index.php?title=Help4.x:Contacts:_Edit_Category&oldid=945854) |
| [News Feeds: New or Edit](https://docs.joomla.org/Help4.x:News_Feeds:_New_or_Edit) | [News Feeds: Edit](https://docs.joomla.org/index.php?title=Help4.x:News_Feeds:_Edit&oldid=946492) |
| [News Feeds: New or Edit Category](https://docs.joomla.org/Help4.x:News_Feeds:_New_or_Edit_Category) | [News Feeds: Edit Category](https://docs.joomla.org/index.php?title=Help4.x:News_Feeds:_Edit_Category&oldid=946688) |

### Testing Instructions

Check entries are present (administrator/index.php?option=com_admin&view=help)

~~Note: help links are still failing at the moment (see #39818)~~

### Actual result BEFORE applying this Pull Request

No links for `Guided Tours` in help site

image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
> Restored old entries (because they are redirects and new language strings are needed to replace them):

Could you explain this please

**Comment by heelc29** [comment]
> Could you explain this please

Sure, the docs sites for these keys are redirections (to still valid help pages) and so will be not found by the build tool.
If the target of the reditection should be find by the build tool we have to replace the language strings in com_admin (but not 1 week before release). So I manually copy these keys back in the json file.

**Comment by bembelimen** [comment]
Thanks for this PR, this is something we neclected for the past releases.
As we're too close to the release to get this into 4.3.0 we have now 5 weeks to get it in the clean way for 4.3.1.

**Comment by heelc29** [comment]
Ok, I will update this PR

**Comment by heelc29** [comment]
One question: is there a reason why the json file is not pretty formatted, this would help at code review?

**Comment by obuisard** [comment]
@heelc29 any update on this PR (it was suggested, that a script should build toc.json, but not be done manually)? Do you need any help with that?

**Comment by heelc29** [comment]
@obuisard I've added the language keys (for the moved doc pages) and the toc.json is generated now by the script (and not adjusted afterwards). So the PR should be ready to test.

**Comment by obuisard** [comment]
> @obuisard I've added the language keys (for the moved doc pages) and the toc.json is generated now by the script (and not adjusted afterwards). So the PR should be ready to test.

Wonderful, thanks! I will ask for help with testing.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on b34dc36c83d4d66f55a9e0c1d1e3fa59f4ebeeb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40377">issues.joomla.org/tracker/joomla-cms/40377</a>.</sub>

**Comment by brianteeman** [comment]
Almost but not quite

image

**Comment by heelc29** [comment]
> Almost but not quite

Seems @ceford [moved page `Help4.x:Guided Tours: Tours` to `Help4.x:Guided Tours`](https://docs.joomla.org/index.php?title=Help4.x:Guided_Tours&oldid=1001119) 😉

**Comment by heelc29** [comment]
PR updated 👍

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 40ded6aebe105f809af9a3fed100e62827398307<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40377">issues.joomla.org/tracker/joomla-cms/40377</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c8e3550f4a485b3130ecf966033475b1b62e7c4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40377">issues.joomla.org/tracker/joomla-cms/40377</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40377">issues.joomla.org/tracker/joomla-cms/40377</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for the PR!

**Pull request merged**
