### PR TITLE
[4.0] Remove redundant array element

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Simple change to remove hardcoded null value which gets filtered out by `array_filter()`.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4069e29897a9f869dfe490ce7487bb73351c6c7a<br /><br />Code review:
- array_filter is called without the optional callback function argument.
- According to [https://www.php.net/manual/de/function.array-filter.php](https://www.php.net/manual/de/function.array-filter.php "https://www.php.net/manual/de/function.array-filter.php"), nulls are filtered out in this case.
=> PR is correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27181">issues.joomla.org/tracker/joomla-cms/27181</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 4069e29897a9f869dfe490ce7487bb73351c6c7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27181">issues.joomla.org/tracker/joomla-cms/27181</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27181">issues.joomla.org/tracker/joomla-cms/27181</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
