### PR TITLE
[4.0] Add type attribute to button

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds missing `type` attribute to backend login button.

### Testing Instructions

Code review or test that you can still login to backend.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3b7919382d435c953ff85da7c77985ec564ecfdd<br /><br />Code review: The PR adds the right type attribute to the button. See [https://www.w3schools.com/tags/att_button_type.asp](https://www.w3schools.com/tags/att_button_type.asp "https://www.w3schools.com/tags/att_button_type.asp"):

> Tip: Always specify the type attribute for the <button> element. Different browsers may use different default types for the <button> element.

The "submit" type is the right one.

Real test: As I did not have problems with login like they were reported in issue #31165 , I could only check that login still works as well as before and that the type attribute really has been added.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31169">issues.joomla.org/tracker/joomla-cms/31169</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 3b7919382d435c953ff85da7c77985ec564ecfdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31169">issues.joomla.org/tracker/joomla-cms/31169</a>.</sub>

**Comment by chmst** [comment]
I had the problems as reported in  #31165 but not always, and cannot say when it occurred. So I can confirm that this is the right attribute and the problem does not occur with this change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31169">issues.joomla.org/tracker/joomla-cms/31169</a>.</sub>

**Comment by brianteeman** [comment]
This should not be required as any button inside a form has the default value of "type=submit"

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by richard67** [comment]
> This should not be required as any button inside a form has the default value of "type=submit"
> 
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

@brianteeman But does it do harm to specify the type attribute?

**Comment by brianteeman** [comment]
No - but my point is that if everyone is saying this is an "intermittent" problem then I doubt very much that adding the default value for the button is actually resolving the problem

**Comment by richard67** [comment]
> No - but my point is that if everyone is saying this is an "intermittent" problem then I doubt very much that adding the default value for the button is actually resolving the problem

Agree.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31169">issues.joomla.org/tracker/joomla-cms/31169</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
