### PR TITLE
[4.0] Align dashboard module titles in files 4.0.0-2019-07-13.sql with joomla.sql files

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

With Pull Request (PR) #26047 , titles of dashboard modules have been changed to more meaningful "... Dashboard" instead of "... Submenu". A big thank you to the author for that change. Previous titles were really confusing.

Since all these modules have been added with the new backend template, i.e. with update SQL script "4.0.0-2019-07-13.sql", it makes sense to do the same changes in this update SQL script so a 4.0 beta or rc or final updated from a 3.10 will have the same module title as it would be after a new installation for these particular modules.

This is what this PR does.

**General remark on changing the SQL update script**

Since we are not in beta yet and so don't have to support updates from 4.0-Alpha-x to 4.0-Alpha-y or between nightly builds, we can change the existing 4.0 update scripts (but of course not pre-4.0 scripts). Later when in beta this will not be allowed anymore because we have to support updating from Beta-x to Beta-y (with y > x of course), so now is a good time to fix it.

### Testing Instructions

Code review: Verify for each MySQL and PostgreSQL that the changed made by this PR here in file "4.0.0-2019-07-13.sql" are identical with the changes for inserting new modules made by PR #26047 in file "joomla.sql" for the same dabatase type.

### Expected result

SQL update scripts "4.0.0-2019-07-13.sql" and corresponding "joomla.sql" are consistent regarding the titles of dashboard modules inserted by the new backend template, which are 'System Dashboard', 'Content Dashboard', 'Menus Dashboard', 'Components Dashboard', 'Users Dashboard' and 'Help Dashboard'.

### Actual result

In SQL update scripts "4.0.0-2019-07-13.sql" those modules mentioned in section "Expected result" are named "... Submenu" and not "... Dashboard", like it should be and like it is in corresponding file "joomla.sql".

### Documentation Changes Required

None I guess.

### CODE REVIEW

**Comment by richard67** [comment]
Ping @wilsonge for review because I don't have privilege to set reviewers it seems.

**Comment by richard67** [comment]
Drone failure with mysql system test seems not to be related to this PR but to some connection problem.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ddbfc4ecd8b035709b3388583f42a771bd29d551<br /><br />Absolutely makes sense.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26318">issues.joomla.org/tracker/joomla-cms/26318</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ddbfc4ecd8b035709b3388583f42a771bd29d551<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26318">issues.joomla.org/tracker/joomla-cms/26318</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26318">issues.joomla.org/tracker/joomla-cms/26318</a>.</sub>

**Comment by brianteeman** [comment]
I still say that sql update files should be immutable

**Comment by wilsonge** [comment]
Actually Richard pointed out that in this case we're inserting new modules - NOT updating anything existing. Given that we're therefore not touching any 3.x data for people upgrading this is fine (and in fact not even existing 3.x sites because the db fixer doesn't touch insert commands anyhow)

If this was an update command - you'd be correct

**Pull request merged**
