### PR TITLE
[4.0]Fix com_banners issue

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #14992 .

### Summary of Changes
There was changes in component dispatcher implement makes banners component broken in the backend. This PR fixes it

### Testing Instructions
1. Install Joomla 4.0 nightly build
2. Access to banners component, you will get errors
3. Delete the file administrator/components/com_banners/dispatcher.php 
4. Apply patch, component works properly.

### CODE REVIEW

**Comment by mbabker** [comment]
So what you're saying with this PR is the dispatcher concept as it was first merged is now broken/gone?

**Comment by joomdonation** [comment]
Yes. Because with the change recently, if a component has dispatcher.php file, it must be a namespaced component while our banners component is not namespaced yet

**Comment by mbabker** [comment]
Ahh, got it.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 1f6edac598cd3a7cc43d1bdec651f1d0246dcaed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15009">issues.joomla.org/tracker/joomla-cms/15009</a>.</sub>

**Comment by joomdonation** [comment]
Please delete the file administrator/components/com_banners/dispatcher.php manually before testing.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1f6edac598cd3a7cc43d1bdec651f1d0246dcaed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15009">issues.joomla.org/tracker/joomla-cms/15009</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@joomdonation can you please update your Instructions so tester got proper Information?

**Comment by joomdonation** [comment]
@franz-wohlkoenig Done

**Review by yvesh — APPROVED** [review]

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 1f6edac598cd3a7cc43d1bdec651f1d0246dcaed<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15009">issues.joomla.org/tracker/joomla-cms/15009</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
