### PR TITLE
[4.0][a11y] Content Navigation plugin fix

### PR DESCRIPTION
**Pull request by brianteeman**
In #21144 I made a mistake and instead of putting a closing nav tag I put another open tag

Oops

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on da6a167e5b42345ec39eb83b6fca97dc39e0a342<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21205">issues.joomla.org/tracker/joomla-cms/21205</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da6a167e5b42345ec39eb83b6fca97dc39e0a342<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21205">issues.joomla.org/tracker/joomla-cms/21205</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21205">issues.joomla.org/tracker/joomla-cms/21205</a>.</sub>

**Comment by wilsonge** [comment]
Oops on the code review too :( Thanks!

**Pull request merged**
