### PR TITLE
[4.0] Mail Templates Help`

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the two mail templates links to the help page

image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0d6ff6c7a8752c4f624d61a0bd91dc590eb25a65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34326">issues.joomla.org/tracker/joomla-cms/34326</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 0d6ff6c7a8752c4f624d61a0bd91dc590eb25a65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34326">issues.joomla.org/tracker/joomla-cms/34326</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34326">issues.joomla.org/tracker/joomla-cms/34326</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
