### PR TITLE
[4.0] Fix search tooltip in modal

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26914 #26909 #26906 #26900 #26916 .

### Summary of Changes
Fix display of tooltip in modal.

### Testing Instructions
* Go to the user notes page.
* Click on Users > User Notes
* Click New
* Click on the Select Category option
* Move the cursor in Search text field
* Apply PR
* Run npm i
* Clear browser's cache

Check other modals.

### Expected result
modal-tooltip

### Actual result
modal-tooltip-before

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 796379f781e411ea86df80e213c69303dd4a99c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27035">issues.joomla.org/tracker/joomla-cms/27035</a>.</sub>

**Comment by infograf768** [comment]
@Quy 
Although it does not concern the patch itself, I remarked what can only be a typo in `/administrator/components/com_associations/tmpl/associations/modal.php` line 41:
`$this->document->addScriptOptions('assosiations-modal', ['func' => $function]);`

`assosiations-modal` should be I guess `associations-modal` but I have no idea of the use of this line and changing one for the other apparently does not change anything.
What do you think?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 796379f781e411ea86df80e213c69303dd4a99c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27035">issues.joomla.org/tracker/joomla-cms/27035</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27035">issues.joomla.org/tracker/joomla-cms/27035</a>.</sub>

**Comment by richard67** [comment]
RTC is still valid after last commit. Fixed typo is unrelated.

**Comment by infograf768** [comment]
tks

**Pull request merged**
