### PR TITLE
[ACL] [new/edit category] Remove categoryedit field check of - No parent - option

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

The categoryedit field (which actually is the category parent select box) is making an ACL check to the "- No parent -" option to decide whether to show the field or not. 
image

This doesn't make much sense. This PR correct that.

Note: it will also be a bit faster since now the ACL check is the last of the condition.

### Testing Instructions

Mainbly code review, but you can also:
1. Apply patch
2. Check category edit field work as usual

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on dfb3f53af01bd079c889c00b474198e8324332bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 958fce57b3f8497ed2a664d76f82b150e88c7468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by coolcat-creations** [comment]
Article View is broken

image

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on 958fce57b3f8497ed2a664d76f82b150e88c7468<br /><br />View is broken, logged in / out, cache is cleared<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
confirmed broken view: `Fatal error: Class 'JFormAbstractlist' not found in /administrator/components/com_categories/models/fields/categoryedit.php on line 19`

**Comment by zero-24** [comment]
@andrepereiradasilva @franz-wohlkoenig @coolcat-creations  i have just merged staging is that should fix the issue you reported can you double check that?

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 2aed2a7b86eb70c96c4c02252012a5ee1bf8fcdb<br /><br />Tested successfully, also ACL still works for those that are not allowed to create.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by zero-24** [comment]
RTC as the issue was just a not synced branche wich is fixed now. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2aed2a7b86eb70c96c4c02252012a5ee1bf8fcdb<br /><br />"New", "Edit" a Article-Category works without Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12821">issues.joomla.org/tracker/joomla-cms/12821</a>.</sub>

**Comment by zero-24** [comment]
Thanks both for retesting :+1:

**Pull request merged**
