### PR TITLE
[4.0] Newsfeed hits field

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #34500 .
Move the hits field to the correct fieldset

### Before
image

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1d32ab306c69f6729b6d4d325b3ef037b7510ea4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34506">issues.joomla.org/tracker/joomla-cms/34506</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 1d32ab306c69f6729b6d4d325b3ef037b7510ea4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34506">issues.joomla.org/tracker/joomla-cms/34506</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34506">issues.joomla.org/tracker/joomla-cms/34506</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
no problem - that was a really weird one

**Pull request merged**
