### PR TITLE
[4.0] Quickicon text for Template styles

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #28851 .

### Summary of Changes
Change Button text so that it matches the link to template styles. 

### Testing Instructions
Code inspect.

### CODE REVIEW

**Comment by infograf768** [comment]
We could avoid having multiple strings with the same value by using here a JGLOBAL string.

For example it would also be used here:
https://github.com/joomla/joomla-cms/issues/28844#issuecomment-620440542

There may be other quickicons strings concerned by such a modification.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d21b2a38f3d3022934fd75d0ac1ad4427b52ff99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28854">issues.joomla.org/tracker/joomla-cms/28854</a>.</sub>

**Comment by adj9** [comment]
I have not tested this item.<br /><br />@Chraneco 
Sorry but I didn't understand which text you want to change. Whether it is on the frontend or on the backend.

In the setting of the template (I only have CASSIOPEA) in Advanced I only have title and description.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28854">issues.joomla.org/tracker/joomla-cms/28854</a>.</sub>

**Comment by chmst** [comment]
@adj9 it is the backend dashboard with quick ions. See it on the dashboard. 
The icon templates  goes to view template styles (frontend), not to templatesoverview.

The aim of quickicons is to make it easier builing a site. In general, web designers want to do overrides or change params in a template style. (for the frontend). 

So the text on the icon "Templates" is confusing, as @coolcat-creations said, as the icon goes to the view "template styles".
This PR makes this clear.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on d21b2a38f3d3022934fd75d0ac1ad4427b52ff99<br /><br />Reviewed language string change and looks good. Also tested PR and makes proper changes with no issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28854">issues.joomla.org/tracker/joomla-cms/28854</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28854">issues.joomla.org/tracker/joomla-cms/28854</a>.</sub>

**Comment by infograf768** [comment]
Concerning https://github.com/joomla/joomla-cms/pull/28854#issuecomment-620481712
I got no reply...

When things get a bit more stable, I therefore may have to make a specific PR.

**Comment by jwaisner** [comment]
@chmst Concerning @infograf768 comment. Is that something you may be able to work with him on to minimize the need for multiple PRs?

**Comment by wilsonge** [comment]
@infograf768 separate PR sounds good to me - seems logical.

Thanks @chmst !

**Pull request merged**
