### PR TITLE
Regression: Fix undefined offset: 1

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #16970 .
Fix regression for Issue #15228 .

### Summary of Changes
Revert to previous individual preg_match rather than combine them into 1.

### Testing Instructions
Check your PHP error log.

or

Create the following PHP script and run it.  1st preg_match( (previous) outputs no error. 2nd preg_match( (current) outputs error.
```
<?php

$agent = "Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/59.0.3071.102 Mobile/14F89 Safari/602.1";

echo 'v3.6.5 ';
preg_match('|CriOS[/ ]([0-9.]+)|', $agent, $version);
var_dump($version);
list ($majorVersion, $minorVersion) = explode('.', $version[1]);

echo 'v3.7.3 ';
preg_match('/Chrome[\/ ]([0-9.]+)|CrMo[\/ ]([0-9.]+)|CriOS[\/ ]([0-9.]+)/i', $agent, $version);
var_dump($version);
list ($majorVersion, $minorVersion) = explode('.', $version[1]);

?>
```
results (1st array is v3.6.5 and 2nd array is v3.7.3):
```
v3.6.5 array(2) {
  [0]=>
  string(19) "CriOS/59.0.3071.102"
  [1]=>
  string(13) "59.0.3071.102"
}
v3.7.3 array(4) {
  [0]=>
  string(19) "CriOS/59.0.3071.102"
  [1]=>
  string(0) ""
  [2]=>
  string(0) ""
  [3]=>
  string(13) "59.0.3071.102"
}
<br />
<b>Notice</b>:  Undefined offset: 1 in <b>C:\xampp\htdocs\agent.php</b> on line <b>14</b><br />
```

### Expected result
No PHP Notice

### Documentation Changes Required
None

### CODE REVIEW

**Review by photodude — APPROVED** [review]
This is an appropriate correction. On code review and preg_match testing

**Comment by Quy** [comment]
@rdeutz I have two v3.7.3 installs where the second install has this PR. The first install is littered with `Fix undefined offset: 1` daily in the PHP error log file and not in the second install. This is a regression from v.3.7.2.

**Comment by photodude** [comment]
@Quy we should add new UA to the unit tests for the noted regression(s) here. (UA's listed in the previous version of this PR #16989)

This is a merge by code review / unit tests pass. No easy way to user test the browser cases.

**Comment by mbabker** [comment]
There are no unit tests for `JBrowser` yet (https://github.com/joomla/joomla-cms/pull/17140 starts it but it's a very limited subset).  If someone wants to generate a list, we can add them as part of that PR or later on after that one's merged.

**Comment by Quy** [comment]
@photodude I don't know how to do it. Would you mind doing it? Thanks.

**Comment by photodude** [comment]
@mbabker I'll put a list together for that PR.

**Comment by photodude** [comment]
@Quy can you fix the merge conflict

**Comment by Brian5600** [comment]
Hello
 I tried to change browser.php with the changes about Chrome today like shown in "Files changed", and the error went away from Chrome browser (ver. 60.x) on Ipad (Ios 10.3.2). I am on Joomla 3.7.4.
I have not tested regarding to IE. I am on Win7, IE 11, and don't see any issues with "default" code.
Hope it will be fixed in Joomla.
Thanks @Brian5600.

**Comment by Quy** [comment]
@Brian5600 Please mark it a successful test here: https://issues.joomla.org/tracker/joomla-cms/17139

**Comment by ghost** [comment]
@Quy i altered successfully Test for @Brian5600

**Comment by Brian5600** [comment]
@franz-wohlkoenig @Quy thanks. 
I also tested with success in Chrome installed on Win8 today.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17139">issues.joomla.org/tracker/joomla-cms/17139</a>.</sub>

**Comment by photodude** [comment]
@mbabker @wilsonge Could either of you, or someone else, consider marking RTC for this since there are two reported successful tests (also drone seems to need a restart here).

**Comment by ghost** [comment]
@photodude who is second successfully Test?

**Comment by photodude** [comment]
@franz-wohlkoenig I guess I miss read it, I thought you had done a test. 

Really this is a "by code review" item as there is no good/easy way to test this and there are not really any unit tests for it either. 

I'll mark approved by code review.

**Review by photodude — APPROVED** [review]
approved by code review

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
@photodude i altered your Review as successfully Test at Issue Tracker.

**Pull request merged**
