### PR TITLE
[4.0] Multilingual: Correcting display of Associations Select fields

### PR DESCRIPTION
**Pull request by infograf768**
https://github.com/joomla/joomla-cms/pull/24775 has modified the label id for modal select fields, therefore breaking the display of these fields in the associations tab when editing an item

### Summary of Changes
Replacing `_id` by `_name` in the associations-edit js file

### Testing Instructions
Multilingual site.
Install at least 2 languages (from fr-FR, de-DE, fa-IR)
Use the Multilingual Sample Data module to set a basic multilingual site.
Edit an article, for example `Article (en-GB)` and display the Associations tab

### Before patch
The language select field used by the article edited `English (en-GB)` displays although it should not.

Screen Shot 2019-05-30 at 08 43 49

### After patch
Issue solved.

Screen Shot 2019-05-30 at 08 40 03

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 23ddfc4211bf43ce9e7488f78d39b7ba18a7354a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25060">issues.joomla.org/tracker/joomla-cms/25060</a>.</sub>

**Comment by lavipr** [comment]
I have tested this item :white_check_mark: successfully on 23ddfc4211bf43ce9e7488f78d39b7ba18a7354a<br /><br />Steps: Test instructions followed. 
The patch works as described. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25060">issues.joomla.org/tracker/joomla-cms/25060</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25060">issues.joomla.org/tracker/joomla-cms/25060</a>.</sub>

**Comment by alikon** [comment]
@bot why setting RTC remove labels: **NPM Resource Changed** and **PR-4.0-dev**

**Comment by ghost** [comment]
> @bot why setting RTC remove labels: **NPM Resource Changed** and **PR-4.0-dev**

this happens every time.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
