### PR TITLE
Lang string JGLOBAL_PRINT_TITLE outputs invalid HTML

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
- See title attribute of print button link in frontend article view (page source code)
```
title="Print article < Title of article >"
```
=> invalid HTML

After patch
```
title="Print article &lt; Title of article &gt;"
```

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This is not invalid because it's within quotes. At least HTML validator doesn't see this as invalid.

**Comment by ReLater** [comment]
Use it inside BODY and it's invalid.

`<?php echo JText::sprintf('JGLOBAL_PRINT_TITLE', 'Blah Blah Blah'); ?>`

Or are there any restrictions where it's allowed to use this or that language string or not?

**Comment by SharkyKZ** [comment]
Yes, it is invalid when used outside of attributes. In such cases the user could escape the whole string. But I guess this fixing this in the string is better. Just note that if someone does escape the string already, this will cause double encode for them.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 02008dd1bc49c0e0c5d89ba60d947d0212cca4bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26527">issues.joomla.org/tracker/joomla-cms/26527</a>.</sub>

**Comment by brianteeman** [comment]
This will apply to several other strings as well if they are used where they are not intended to be used

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 02008dd1bc49c0e0c5d89ba60d947d0212cca4bf<br /><br />OT: I was previously by mistake in Joomla 4 :-) There I didn't find a print button.

OK, J 3.9.12 after Patch.
(added Code removed).

Don't know about "several other strings"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26527">issues.joomla.org/tracker/joomla-cms/26527</a>.</sub>

**Comment by ChristineWk** [comment]
Sorry, I wanted to add a Code. Seems to be wrong? thks. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26527">issues.joomla.org/tracker/joomla-cms/26527</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26527">issues.joomla.org/tracker/joomla-cms/26527</a>.</sub>

**Comment by brianteeman** [comment]
If someone is already using this string outside of its intended purpose then they may have

>  escape the string already, this will cause double encode for them.

**Comment by SharkyKZ** [comment]
And if someone is using it without escaping, they're getting invalid HTML. Let's just leave this for @HLeithner to decide whether he wants to merge this.

**Comment by HLeithner** [comment]
If we do this we have to be consistent over the complete code base, so if brian found other strings that have the same problem they have to be escaped too, also I'm not a fan of encoding strings in the ini file because you should do this on output. At least that's the way joomla handles variable output and language string output in scripts context.

Our documentation doesn't say much about the content of the language string https://docs.joomla.org/Specification_of_language_files

**Comment by ReLater** [comment]
The simplest solution would be not to use critical characters in language strings.

**Comment by SharkyKZ** [comment]
Why close this? I thought it was agreed that this PR is fine. Just that there are more instances of this. For example https://github.com/joomla/joomla-cms/blob/0aea5c3d8fe06fb758c4ff08239639b9857e915b/language/en-GB/en-GB.mod_login.sys.ini#L7

**Comment by infograf768** [comment]
I doubt that an xml description would be be used in another context... ;)

In any case, as you may guess, I am not in favor of modifying all the ini files containing `<a href ... a>` (107 of them...) or other of this type... `<br>` `<span` `strong` `img` etc. It would be an enormous task for all TTs... 
`< ` is used 1817 times.... and `>` 1843 times....

Anyone having a problem with a specific core ini containing one of these characters in a non-intended use should create overrides...

**Comment by SharkyKZ** [comment]
@infograf768 you misunderstood. HTML markup in language strings is fine. HTML in extension descriptions is allowed. So the issue with above example is here:

>(in Users > Manage > Options)

These unescaped `>` symbols cause invalid HTML markup, same way as described in this PR.

**Comment by infograf768** [comment]
If it concerns only that type of value, I'm ok with correcting them.

**Pull request closed without merging**
