### PR TITLE
[4.0] @since

### PR DESCRIPTION
**Pull request by brianteeman**
Best to start J4 the right way with exact versions for `@since`

code review

### CODE REVIEW

**Comment by ceford** [comment]
That leaves 88 to go. Will there be another PR for those? Otherwise I think this is OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by brianteeman** [comment]
There shouldn't be any

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 4b6141b1f72ed386b07131af205f94125c8233a7<br /><br />I looked again and decided the ones I found are not relevant: 3 in api/..., a whole bunch in libraries/src/Console/... and just a few in tests/...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by brianteeman** [comment]
I still dont see any

**Comment by ceford** [comment]
I am using a clone of the joomla-cms repo in conjunction with Eclipse. I search all php files for  '[at]since 4.0\n' with regular expression set and come up with this list (partial here just to illustrate findings):

>api/components/com_categories/src/Controller/CategoriesController.php line 94
api/components/com_contact/src/Serializer/ContactSerializer.php lines 37, 64, 83, 102, 121
api/components/com_content
api/components/come_contenthistory
more ...
libraries/src/Console/CheckJoomlaUpdatesCommand.php lines 64, 81, 100
more ...
libraries/src/Tag/TagApiSerializerTrait/.php line 34
tests/Unit/Libraries/Cms/Feed/FeedParserTest.php line 387
tests/Unit/Libraries/Cms/Microdata/MicrodataTest.php lines 725, 771

**Comment by ceford** [comment]
And I have just realised I find some more by searching for '[at]since\ +4.0\n'<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by brianteeman** [comment]
api/components/com_categories/src/Controller/CategoriesController.php line 94

says 4.0.0

api/components/com_contact/src/Serializer/ContactSerializer.php lines 37, 64, 83, 102, 121

all say 4.0.0

Not bothering to continue as something is not right with your repo if they are saying `@since 4.0`

**Comment by ceford** [comment]
It looks like Patchtester has only applied the patches down to and including:

diff --git a/api/components/com_menus/src/Controller/MenusController.php b/api/components/com_menus/src/Controller/MenusController.php

None of the changes below that have been applied. That is just a quarter of the total number of diffs. Hmmmm!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by brianteeman** [comment]
I wouldnt expect patchtester to work on such a large change

**Comment by ceford** [comment]
In administrator/components/patchtester/PatchTester/Model/PullModel.php on line 553 the count of files obtained from github is 30. Anything in the PR after that is dropped.

I don't remember seeing this documented anywhere.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by ceford** [comment]
> I wouldnt expect patchtester to work on such a large change

Why not? I have just looked at the Patchtester docs and nowhere can I find any mention of any limitations. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by brianteeman** [comment]
a million reasons and none of them relevant to this PR.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4b6141b1f72ed386b07131af205f94125c8233a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33926">issues.joomla.org/tracker/joomla-cms/33926</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou. Not sure how this crept into so many places!

**Comment by brianteeman** [comment]
copy paste to blame

thank you

**Pull request merged**
