### PR TITLE
Back to https after https://github.com/joomla/joomla-cms/pull/8479

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/8479
### Summary of Changes

Doc block change, merged on review
### Testing Instructions

None
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e7fd0e56b9b50f39fce0c807db42bf022c1b3fbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11745">issues.joomla.org/joomla-cms/11745</a>.</sub>

**Comment by brianteeman** [comment]
RTC- simple fix @rdeutz <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11745">issues.joomla.org/joomla-cms/11745</a>.</sub>

**Comment by zero-24** [comment]
@rdeutz @wilsonge Can you have a look / merge here?

**Comment by jeckodevelopment** [comment]
I can merge it too, but, let's wait for George or Robert :)

**Comment by zero-24** [comment]
Feel free to hit that great green button :smile:

**Comment by jeckodevelopment** [comment]
It's gray now, let's wait until Travis will be ready

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e7fd0e56b9b50f39fce0c807db42bf022c1b3fbf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11745">issues.joomla.org/joomla-cms/11745</a>.</sub>

**Comment by zero-24** [comment]
:+1:

**Pull request merged**
