### PR TITLE
[4.1-dev] Adding color-picker to 4.1

### PR DESCRIPTION
**Pull request by thednp**
renamed branch...

### CODE REVIEW

**Comment by brianteeman** [comment]
there are unrelated files in this pr

**Comment by thednp** [comment]
Unfortunately yes.

**Comment by thednp** [comment]
Solved, now unfortunately the dart-sass errors kick in now.

**Comment by thednp** [comment]
@brianteeman the build is failing because of dart-sass, it's not related to my changes.

**Comment by dgrammatiko** [comment]
@thednp can you delete completely the package-lock.json and then do a ‘ npm install`. Then commit back the package-lock.json

**Comment by thednp** [comment]
@dgrammatiko this branch uses same version of sass, perhaps the best thing to do is to fix those SCSS issues first, I cannot get a perfect build now unless I fix those SCSS issues which are not related to my commit at all.

**Comment by thednp** [comment]
Should I attempt to fix those issues? Guys?

**Comment by dgrammatiko** [comment]
> Should I attempt to fix those issues? Guys?


Try to rebase this branch using the latest 4.1-dev

edit 4.1-dev

**Comment by thednp** [comment]
That won't work for some reason, the button is disabled

image

EDIT: for any 4.1-dev branch

**Comment by dgrammatiko** [comment]
You have to do that using the git cli

https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Comment by thednp** [comment]
image

**Comment by dgrammatiko** [comment]
Try to rebase it to the origin 4.1-dev not your local one

**Comment by thednp** [comment]
I did `rebase -r --root` and deleted nearly everything in my local repository.

**Comment by thednp** [comment]
Oh wait some files are coming back now.

**Comment by thednp** [comment]
I think I'm gonna start over again tomorrow.

**Pull request closed without merging**
