### PR TITLE
[4.0] Bump to PHP 7 minimum

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Bump 4.0 to PHP 7 per yesterday's announcement

### Documentation Changes Required

Add the new minimum to the B/C page

### CODE REVIEW

**Comment by zero-24** [comment]
Here is the article: https://developer.joomla.org/news/704-looking-forward-with-joomla-4.html

**Comment by mbabker** [comment]
FWIW the Travis failure exists in the base branch too.  So the only thing that should be stopping this for the moment is making sure I didn't completely destroy the AppVeyor config.

**Comment by wilsonge** [comment]
Holding off on merging this just now until I've finished my round of conflicts i'm about 2/3 of the way through

**Review by wilsonge — APPROVED** [review]

**Comment by zero-24** [comment]
> FWIW the Travis failure exists in the base branch too. So the only thing that should be stopping this for the moment is making sure I didn't completely destroy the AppVeyor config.

see here for the travis issue: https://github.com/joomla/joomla-cms/issues/17550

**Comment by zero-24** [comment]
Given that the travis error is a different on https://github.com/joomla/joomla-cms/issues/17550 I'm not sure what did happen to appveyor here. Do you have a way to restart the build?

**Pull request merged**
