### PR TITLE
[4.0] Fix + Simplify code of frontend module editing

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
com_config (frontend) has really strange code. Instead of calling backend model getItem() method to get the module data, it uses complicated code by calling controller display method to get json view data.

This PR fixes that strange code. As a result, the json view + some code in com_modules is removed, too.

### Testing Instructions
1. Install Joomla 4 (with sample data for easier testing)
2. Login to frontend using a super admin account
3. Try to edit a module
3. Before patch, no form display to allow edit module parameters
4. After patch, a form displayed to allow changing module parameter. Save the module data, make sure the changes parameter is saved.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on dc3b3337ca562afc825d6b2664e1c0f3652b4564<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15445">issues.joomla.org/tracker/joomla-cms/15445</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dc3b3337ca562afc825d6b2664e1c0f3652b4564<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15445">issues.joomla.org/tracker/joomla-cms/15445</a>.</sub>

**Comment by joomdonation** [comment]
Many thanks for testing @franz-wohlkoenig , @richard67 .

**Comment by wilsonge** [comment]
Is there a reason this can't go into staging (but you'd need to leave the `view.json.php` in place and deprecate it for j4

**Comment by joomdonation** [comment]
@wilsonge Only the change in display controller of com_config can go into stagging. Since we have to keep the file view.json.php, the code in module controller class will need to be kept as well

Do we really need to deprecate  the view.json.php class? We will namespace com_modules, so that class won't be available in Joomla4 anyway, so I think it doesn't need to be deprecated?

**Comment by joomdonation** [comment]
@wilsonge Maybe just merge it into Joomla 4. It helps namespacing com_modules easier. We can backport the change of display controller in com_config back to staging later if needed

**Pull request merged**
