### PR TITLE
[5.1] Explicit return false when no form field was found

### PR DESCRIPTION
**Pull request by laoneo**
To improve compatibility with PHP type checking tools like PHPStan, we need to narrow the boolean return type, as a boolean is only returned when false, otherwise a `FormField` object.

Code review only.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 48942d528499fcbb67bc9b2fbcecc440ca0c8e2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43006">issues.joomla.org/tracker/joomla-cms/43006</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 48942d528499fcbb67bc9b2fbcecc440ca0c8e2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43006">issues.joomla.org/tracker/joomla-cms/43006</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43006">issues.joomla.org/tracker/joomla-cms/43006</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
