### PR TITLE
[5.2] ModalSelect: selecting the title for the field value, when possible

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

As for now `ModalSelect` does not able to display the title for selected value, after saving.
This PR add a posibility to do it. 
To make it work, the field XML should have 3 attributes:
- `sql_title_table`  The table wehre the title is stored
- `sql_title_column` The column name in that table
- `sql_title_key` The column name that represent the field value, for the "where" query.

### Testing Instructions

Add  `ModalSelect` field in to Custom HTML module:
```xml
<field
  type="ModalSelect"
  name="article"
  label="Article"

  select="true"
  titleSelect="Selecting the Article"
  urlSelect="index.php?option=com_content&amp;view=articles&amp;layout=modal&amp;tmpl=component"
  clear="true"
  
  sql_title_table="#__content"
  sql_title_column="title"
  sql_title_key="id"
/>
```
Go to the module editing, and select any article with this field, and save the module.

### Actual result BEFORE applying this Pull Request
After saving the field display the article ID

### Expected result AFTER applying this Pull Request
After saving the field display the article title

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: TBD
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on be34f77651006e88796fa057b956fdb4b78008ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43746">issues.joomla.org/tracker/joomla-cms/43746</a>.</sub>

**Comment by robbiejackson** [comment]
I have tested this item :white_check_mark: successfully on be34f77651006e88796fa057b956fdb4b78008ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43746">issues.joomla.org/tracker/joomla-cms/43746</a>.</sub>

**Comment by robbiejackson** [comment]
The only issue is that both the id field and the title field are sent in the POST parameters when the form is submitted, which looks rather peculiar, but works I think because the title field is sent first, and it somehow then gets overwritten by the id field (maybe in the processing by the PHP processor). 

What about setting the title field as disabled? I believe it won't then get submitted.

Or at least provide an option to disable the title field.

**Comment by Fedik** [comment]
@robbiejackson thanks for feedback. 
This was made for purpuse. For accessibility. Because the field linked to the label by `for` attribute.

In the normal form we probably could just remove `name` attribute from the title field. However in the `subform` field, this field will lost connection with its label, due to how `subform` work (it calculate `id` of the input based on its `name`, and later looking for the label `for` attribute ).

The browser will submit both, but the latter one fill overide first one, so here is no problem.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43746">issues.joomla.org/tracker/joomla-cms/43746</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Fedik !

**Pull request merged**
