### PR TITLE
[4.4] Cypress test for popular articles in mod_articles_popular

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue # .

Add mod_articles_popular system test.

### CODE REVIEW

**Comment by sandewt** [comment]
Result of the (local) Cypress test in browser

pr_40189

**Comment by brianteeman** [comment]
Surely thats just testing if the module loads _something_ and not that it loads something _popular_

**Comment by sandewt** [comment]
> Surely thats just testing if the module loads something and not that it loads something popular

It would indeed be nicer to load, for example, the last five articles with one of them with the title of the test article.
The question is whether that is possible in a simple way.

I've tried that but haven't gotten it done yet.

**Comment by laoneo** [comment]
For now this is ok, we can always add more tests in the future when we get more experience.

**Comment by sandewt** [comment]
This can be achieved very easily, without the _automated test article_

pr_40189-2

**Comment by sandewt** [comment]
@laoneo very easy to change

`.then(() => cy.db_createModule({ module: 'mod_articles_popular', params: JSON.stringify({ catid: 2 }) }))`
becomes
` .then(() => cy.db_createModule({ module: 'mod_articles_popular }))`

**Comment by sandewt** [comment]
Note; It would then be nice to use an if statement if there are no articles yet

**Comment by laoneo** [comment]
Tests should not have conditions and you have to always assume the database is empty. So you have to setup tthe database in a way you want to test it.

**Comment by sandewt** [comment]
Thanks

**Pull request merged**
