### PR TITLE
[3.x] Php version check

### PR DESCRIPTION
**Pull request by brianteeman**
Update the list of php versions to include 8.0

code review

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fe07f97149fb2e9733500e2da22ba78e3b1cb9c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31977">issues.joomla.org/tracker/joomla-cms/31977</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on fe07f97149fb2e9733500e2da22ba78e3b1cb9c3<br /><br />Tested successfully in 3.9.24-rc2 of 11 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31977">issues.joomla.org/tracker/joomla-cms/31977</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31977">issues.joomla.org/tracker/joomla-cms/31977</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
