### PR TITLE
Regression Smart search/contact list menu item cannot been saved

### LINKED ISSUE #7309: Regression - cannot create smart search menu link
#### Steps to reproduce the issue
Create a new menu item for Smart Search

#### Expected result
Menu link created

#### Actual result
Invalid field: Date Filters
Invalid field: Advanced Search
Invalid field: Expand Advanced Search

First reported http://forum.joomla.org/viewtopic.php?f=706&t=890725&p=3314024#p3314024

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Steps to reproduce the issue

Create a new menu item for Smart Search
#### Expected result

Menu link created
#### Actual result

Invalid field: Date Filters
Invalid field: Advanced Search
Invalid field: Expand Advanced Search
#### Testing

Apply patch and follow the instructions above. Menu item should be saved without any errors

### CODE REVIEW

**Comment by Bakual** [comment]
Patch doesn't work for me. And yes, cache was cleared. Even tried with debug on so I got the uncompressed file. Same result.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/7313

Closing as we have a PR:

**Comment by Bakual** [comment]
Ah crap, commented in wrong PR :smile:

**Comment by brianteeman** [comment]
Are you sure this is the cause of the issue? The last time this file was updated was #6294 which as far as I can tell was in 3.4.1 

I havent checked yet but I suspect that #6664 and the changes in core.js are more likely<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7312">issues.joomla.org/joomla-cms/7312</a>.</sub>

**Comment by brianteeman** [comment]
I suspect that the issue with the farsi calendar is also as a result of the same changes in core.js<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7312">issues.joomla.org/joomla-cms/7312</a>.</sub>

**Comment by infograf768** [comment]
We can now solve the Farsi calendar issue. See: 
https://github.com/joomla/joomla-cms/issues/7298#issuecomment-117976612

**Comment by Fedik** [comment]
as far as I can see, error comes from the server side validation ... but cannot find why ...
maybe it somehow related to this changes https://github.com/joomla/joomla-cms/commit/516a8644d8ca04e31a6a3718044ce591ba9b2dd1

**Comment by brianteeman** [comment]
Reverting 516a864
<https://github.com/joomla/joomla-cms/commit/516a8644d8ca04e31a6a3718044ce591ba9b2dd1>
solves
the issue

On 2 July 2015 at 10:37, Fedir Zinchuk <notifications@github.com> wrote:

> as far as I can see, error comes from the server side validation ... but
> cannot find why ...
> maybe it somehow related to this changes 516a864
> <https://github.com/joomla/joomla-cms/commit/516a8644d8ca04e31a6a3718044ce591ba9b2dd1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7312#issuecomment-117978202>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Fedik** [comment]
yes, after revert https://github.com/joomla/joomla-cms/commit/516a8644d8ca04e31a6a3718044ce591ba9b2dd1 Smart search work fine again

**Comment by Fedik** [comment]
@brianteeman was faster :smile:

**Comment by brianteeman** [comment]
Note its also the contact list menu type thats effected (maybe others)

On 2 July 2015 at 10:40, Fedir Zinchuk <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> was faster [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7312#issuecomment-117979373>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Revert is a possibility indeed, but it would break  I guess the original issue solved by https://github.com/joomla/joomla-cms/pull/3877

**Comment by Fedik** [comment]
@infograf768  true, but at least we know a reason :wink:

**Comment by brianteeman** [comment]
I am just stating that the issue is definitely as a result of the changes
made in that PR. It is for others to decide if it should be reverted or if
it can be fixed in another way.

On 2 July 2015 at 10:43, infograf768 <notifications@github.com> wrote:

> Revert is a possibility indeed, but it would break I guess the original
> issue solved by #3877 <https://github.com/joomla/joomla-cms/pull/3877>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7312#issuecomment-117979848>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@okonomiyaki3000 as it was your PR can you get a look into here?

**Comment by brianteeman** [comment]
As the PR that is causing the issue is over 18 months old and was to enable
something for 3pd then I would definitely say revert the PR and wait for a
different solution for that specific issue



On 2 July 2015 at 10:50, zero-24 <notifications@github.com> wrote:

> @okonomiyaki3000 <https://github.com/okonomiyaki3000> as it was your PR
> can you get a look into here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7312#issuecomment-117984820>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
>As the PR that is causing the issue is over 18 months old

That is exactly why imho we can't just revert it as 3pd may have used that code since...

**Comment by infograf768** [comment]
Forget it. It was just recently merged...

**Comment by brianteeman** [comment]
;)

On 2 July 2015 at 11:01, infograf768 <notifications@github.com> wrote:

> Forget it. It was just recently merged...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7312#issuecomment-117986965>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rdeutz** [comment]
please check #7317 it should fix the problem

**Comment by zero-24** [comment]
Closing as this don't work and @rdeutz has a working fix here: #7317 that need only one more tester :smile:

**Pull request closed without merging**
