### PR TITLE
[4.0] Fix Uncaught TypeError: f.reverse is not a function

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26655.

### Summary of Changes
When sorting in descending order, convert nodelist to an array.

Thanks @C-Lodder for code.

### Testing Instructions
Go to Articles list.
Click arrow to sort descending order.
Drag a row.
No javascript errors in the browser's console. 
Test in other sections.

Install PR.
Run npm i.
or 
Download installer package here: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28773/downloads/31490/

### CODE REVIEW

**Comment by ChristineWk** [comment]
FYI: Wanted to test with Download installer package included also correct update server.

pr28773

Patch response:

pr28773_02

After a click to another field:
Oops! An Error Occurred
The server returned a "500 Whoops, looks like something went wrong.".....

Now site is completely broken. Hv. to re-install fully again.
Sorry, don't know, what fault I did. 
Just wanted to help testing ......

**Comment by Quy** [comment]
Thanks for testing. You must be using the nightly builds. In that case, when you see PRs with `NPM Resource Changed` label, then using the custom update server will not work. Please use the download installer package instead.

**Comment by ChristineWk** [comment]
@Quy I had both :-) That means: also: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28773/downloads/31490/pr_list.xml

I made from new instructions (OK,it's german) https://ug-mayen.de/de/joomla-blog-de/26-vorgefertigte-download-pakete-fuer-fehlerbehebungen (method 3).

So, I can't change now anything, because site is broken. Will install new installation tomorrow. This takes time :-)
Thks for understanding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28773">issues.joomla.org/tracker/joomla-cms/28773</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk When you use the donwload or custom xml for the update package build for this PR and then update with that to J4, like you did and which you can see by the "+pr.29773" in the version number after the update, then it doesn't need to apply the patch for this PR with the patchtester, like it is shown in the error message. The patchtester will try to apply the patch on a Joomla installation at which it is already applied, and so it fails for sure.

**Comment by ChristineWk** [comment]
@richard67 Aha ...
Usually when testing PR - "normal" :-) I jump to "Issuing Tracker" for: "Test This" etc. ...
So, this can be done without applying the patch, if I understand you correctly?
OK ..... I hope for next time ..... Thks.

**Comment by richard67** [comment]
@ChristineWk If you use donwloads from pages like the one lined by @Quy in his description, [https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28773/downloads/31490/](https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28773/downloads/31490/), then these are packages which include the PR already. You can see that by the big title "Prebuilt Download Packages for PR 28773" at the top. If you use normal nightly builds, you have to use patchtester to apply a PR.

**Comment by richard67** [comment]
@ChristineWk P.S. The update packages for J4 PRs or the corresponding custom url on such a PR-specific download page can be used to test updating from J 3.10 to "4+that PR". They can't be used to update from J4 nightly.

The full installation packages can be used for a PR if you don't have patchtester or patchtester doesn't work for that PR. Then you can make a new installation with such package and have the PR already applied.

**Comment by Harmageddon** [comment]
@richard67 Sorry for OT here, but could you explain why "They can't be used to update from J4 nightly" in this case? From what I saw in the different tutorials about these new PR packages, using update packages should only be problematic if SQL or other update-related files have been changed in the meantime.

**Comment by richard67** [comment]
@Harmageddon Yes, but the average tester doesn't know if some SQL has changed or not.

**Comment by richard67** [comment]
@Harmageddon In addition, if you have updated a 4 nightly with a package build for a PR, the PR will be applied. How do you revert this then? If you do this multiple times you are just testing combinations of several PRs, and if some of those PR's touch the same file, you end up in a mess.

**Comment by wilsonge** [comment]
Thanks!

**Comment by Harmageddon** [comment]
@richard67 Ok, I do see the second point (but then these prebuilt packages don't seem to have great advantages to me, as you'd have to set up two completely new environments for each PR to test), but tend to disagree with the first one in the case of this issue.
Thank you for your response! :-)

**Comment by ChristineWk** [comment]
> 
> 
>... Yes, but the average tester doesn't know if some SQL has changed or not.
@richard67 You are absolutely right. I'am an average tester & will leave. 

@Harmageddon Thanks for your investigation.

**Comment by richard67** [comment]
@ChristineWk @Harmageddon Sorry but I only pointed out what went wrong with the test, and that's what I did at the beginning, nothing else.

I did not want to be involved in a discussion about sense or not sense of the packages built for a PR. 

My statement about the avergate tester should not disparage somebody, it only reflected my experience that often testers don't notice when a PR has database changes.

**Pull request merged**
