### PR TITLE
[4.0] Site Modules language alphasort

### PR DESCRIPTION
**Pull request by brianteeman**
c/s alpha sort site module strings

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4ee884cf81e9e6aea271a9417ea2a3930f7f70dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27424">issues.joomla.org/tracker/joomla-cms/27424</a>.</sub>

**Comment by jwaisner** [comment]
@brianteeman Can you provide the test instructions? Is this just an overall test of functionality?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27424">issues.joomla.org/tracker/joomla-cms/27424</a>.</sub>

**Comment by brianteeman** [comment]
Language strings should be sorted in alphabetical order. These were not. They are now. This is just a codestyle change. There is no functional difference

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 4ee884cf81e9e6aea271a9417ea2a3930f7f70dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27424">issues.joomla.org/tracker/joomla-cms/27424</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27424">issues.joomla.org/tracker/joomla-cms/27424</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
