### PR TITLE
[5.1] DARK MODE installer drag and drop

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
add css and change to [data-bs-theme-dark]

### Actual result BEFORE applying this Pull Request
image

image

### Expected result AFTER applying this Pull Request
image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I think use of `data-color-scheme` would be preferable, in non BS files.

**Comment by brianteeman** [comment]
i would but it doesnt work

**Comment by Fedik** [comment]
Okay then :)

**Comment by Fedik** [comment]
@brianteeman  I made a quick check and `data-color-scheme` works to me:
```css
[data-color-scheme=dark] #dragarea.hover #upload-icon,
[data-color-scheme=dark] #dragarea p.lead {
  color: #eee;
}

[data-color-scheme=dark] #dragarea.hover {
  background-color: #666;
  border-color: #eee;
}
```

**Comment by brianteeman** [comment]
I will take another look. Probably did something daft

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 9d48656d75c1da2da725106b4a0803e94be82980<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43018">issues.joomla.org/tracker/joomla-cms/43018</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d48656d75c1da2da725106b4a0803e94be82980<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43018">issues.joomla.org/tracker/joomla-cms/43018</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43018">issues.joomla.org/tracker/joomla-cms/43018</a>.</sub>

**Pull request merged**
