### PR TITLE
[4.0] Namespace User - Terms plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Namespaces User - Terms and Conditions plugin.

### Testing Instructions

Delete `libraries/autoload_psr4.php` file.
Enable User Registration.
Enable User - Terms and Conditions plugin.
Open registration form in frontend.
Check that Terms & Conditions field appears correctly in the form.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 45fdcade478dfecb0a3e4a82b7d97defcf7bc97b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27647">issues.joomla.org/tracker/joomla-cms/27647</a>.</sub>

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 45fdcade478dfecb0a3e4a82b7d97defcf7bc97b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27647">issues.joomla.org/tracker/joomla-cms/27647</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27647">issues.joomla.org/tracker/joomla-cms/27647</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
