### PR TITLE
com_banners incorrect tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
The tooltip says that the images must be in the images/banners folder but this isnt true they can be in any folder

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 98262a2d60db3fdae780db450a3e96daa7407b9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17157">issues.joomla.org/tracker/joomla-cms/17157</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 98262a2d60db3fdae780db450a3e96daa7407b9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17157">issues.joomla.org/tracker/joomla-cms/17157</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
