### PR TITLE
[5.0] Fix com_ajax event with webauthn plugin, take2

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/41719 .

### Summary of Changes
Alternative for https://github.com/joomla/joomla-cms/pull/41720

### Testing Instructions
Please follow https://github.com/joomla/joomla-cms/issues/41719

### Actual result BEFORE applying this Pull Request
error

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
@heelc29 please test this alternative, it should be better, in thery

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 20d7a19a809756fbfaf094408192958598208e41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41732">issues.joomla.org/tracker/joomla-cms/41732</a>.</sub>

**Comment by HLeithner** [comment]
this makes the Event Classes provided by the plugin obsolete right? Should we remove them and/or deprecated them?

**Comment by Fedik** [comment]
No no, they in use https://github.com/joomla/joomla-cms/blob/20d7a19a809756fbfaf094408192958598208e41/plugins/system/webauthn/src/PluginTraits/AjaxHandler.php#L87-L114

**Comment by HLeithner** [comment]
ok I think then this is a better version. thanks

**Pull request merged**
