### PR TITLE
Regression: jModalClose is unavailable if no mootools

### LINKED ISSUE #8378: J3.5: Editor buttons can no longer define popup size
Since the implementation of https://github.com/joomla/joomla-cms/pull/7170 the editor buttons have no control anymore over the size of the modal popup.
You could do this before in the editors-xtd plugins render method:
```$button->options = "{handler: 'iframe', size: {x:window.getSize().x-100, y: window.getSize().y-100}}";```
This would get placed in the html ```rel``` attribute used by the Squeezebox modal.

Now the ```option``` is completely disregarded.

These plugins can also be having different scripts inside the modal to control the popup, like closing it on click.
These all now fail ungracefully

Even the core ```Article``` button doesn't work anymore (aside from the fact that it looks bad because of the missing padding in the modal).
It will insert the article, but not close the modal, with js error:
```
jModalClose is not defined
```

This is a serious B/C issue and this PR needs to get reverted, IMO.

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Testing

Set tinyMCE as you editor
try the button insert article, the link should be inserted and the modal should close

### CODE REVIEW

**Comment by dgt41** [comment]
Just a remark the broken part is the undefined jModalClose function, the rest is just moving js to a part where can be overridden...

**Comment by Bakual** [comment]
While this fixes the issue for the article button, it doesn't fix the underlying issue.
All 3rd party plugins with similar code will still be broken, and especially closing the active modal is something many (most?) plugins use in this case.

Unfortunately it looks like the move to use Bootstrap modals instead of SqueezeBox isn' that easy. If we can't proxy the old closing method to close the Bootstrap modal, then I'm afraid that PR isn't B/C and imho needs to be reverted.

**Comment by Bakual** [comment]
Can you fix the CS issues Travis complains about?
Also I see some commented out code lines. I guess those are leftovers?

**Comment by dgt41** [comment]
Closing please test #8366

**Pull request closed without merging**
