### PR TITLE
Add dropdown tasks items to com_tags

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvements.
#### Summary of Changes

This PR adds state tasks dropdown actions to tags component.
##### Before PR

image
##### After PR

image
#### Testing Instructions
1. Use latest staging and apply patch 
2. Test the new dropdown menu in all possible tags states (published, unpublished, archived and trash)

### CODE REVIEW

**Comment by brianteeman** [comment]
This isnt quite the same as com_content
In com_content if you go to a trashed icon it always shows archive/trash
Here it shows archive/publish<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by brianteeman** [comment]
This isnt quite the same as com_content
In com_content if you go to a trashed icon it always shows archive/trash
Here it shows archive/publish<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by brianteeman** [comment]
I see now that this is what you are doing in #10062 I'm not sure about this change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman that's the bug in com_content. How do we trash a trashed item? trash 2x?

**Comment by andrepereiradasilva** [comment]
Also check that in com_content if you filter by "Trashed" you will see the correct options in the trashed items: "Archive" and "Publish".

As said before it's a bug in the current state dropdows.

**Comment by brianteeman** [comment]
Yes thats definitely a bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 71027c22c584bb4ff0fa51f914141489f891e424<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 71027c22c584bb4ff0fa51f914141489f891e424<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10065">issues.joomla.org/joomla-cms/10065</a>.</sub>

**Pull request merged**
