### PR TITLE
[4.0] Fixing btn-group (again)

### PR DESCRIPTION
**Pull request by Bakual**
While looking at issue https://github.com/joomla/joomla-cms/issues/19943 I saw that `btn-group` for radios is again broken in J4.
I've fixed that previously with https://github.com/joomla/joomla-cms/pull/19326, but I think with the PR to separate the layouts that PR got "reverted".
So this PR again reinstates the fix from my previous PR.

### Summary of Changes
Adds proper classes to support btn-group behaviours from J3.

### Testing Instructions
(copied from original PR)
To test, you can add the following code to the config.xml of any extension. Eg to /administrator/components/com_content/config.xml. Just put it right after the `<config>` tag.
````
	<fieldset
		name="test"
		label="Test"
	>
		<field
			name="plain"
			type="radio"
			class=""
			default="1"
		>
			<option value="1">Foo</option>
			<option value="0">Bar</option>
		</field>

		<field
			name="btn-group"
			type="radio"
			class="btn-group"
			default="1"
		>
			<option value="1">Foo</option>
			<option value="0">Bar</option>
		</field>

		<field
			name="btn-group-yesno"
			type="radio"
			class="btn-group btn-group-yesno"
			default="1"
		>
			<option value="1">JYES</option>
			<option value="0">JNO</option>
		</field>

		<field
			name="btn-group-yesno reordered"
			type="radio"
			class="btn-group btn-group-yesno"
			default="1"
		>
			<option value="0">JNO</option>
			<option value="1">JYES</option>
		</field>

		<field
			name="switcher"
			type="radio"
			class="switcher"
			default="1"
		>
			<option value="0">JNO</option>
			<option value="1">JYES</option>
		</field>
	</fieldset>
````
Now go to the settings of that component. You will have a new tab with 5 parameters.
Check if the radios work.
Make also sure the plain radios and the switcher work as well.

### Expected result
image
All radios work
We even get some styling as expected, but main point is they work 😄 

### Actual result
image
The marked radios are not working (and styling doesn't exist).

### CODE REVIEW

**Comment by tassosm** [comment]
I have tested this item :white_check_mark: successfully on 831743c3127fcbd7137f6e9599c817cbe35d6560<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19946">issues.joomla.org/tracker/joomla-cms/19946</a>.</sub>

**Comment by laoneo** [comment]
Are the tests here failing because of the pr? Ping @rdeutz

**Comment by rdeutz** [comment]
No this is falling because of a past merge, I already fixed the test, just waiting that drone picks the right package from packagist

**Comment by Bakual** [comment]
Thanks 👍

**Comment by tassosm** [comment]
Awesome! Thanks.

**Pull request merged**
