### PR TITLE
[mod_articles_latest/news] Featured articles not shown

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #21333.

### Summary of Changes

This fixes a bug introduced in #20845 of featured articles not being shown.

### Testing Instructions

Create `mod_articles_news` or `mod_articles_latest` module.
Set `Featured Articles` to `Show`.

### Expected result

Both featured and not featured articles are shown.

### Actual result

Only not featured articles are shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5c282dbd6676bdd7c4287c3def35299cb7fd43a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21336">issues.joomla.org/tracker/joomla-cms/21336</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5c282dbd6676bdd7c4287c3def35299cb7fd43a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21336">issues.joomla.org/tracker/joomla-cms/21336</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by makermann** [comment]
Also successfully tested.

**Comment by Folamour** [comment]
please what fix should i ask to apply ?

thanks,

**Comment by infograf768** [comment]
@Folamour 
There are 2 files to replace:
modules/mod_articles_latest/helper.php
and
modules/mod_articles_news/helper.php

I have added these in a .zip with their respective folders
[patches_featured_articles.zip](https://github.com/joomla/joomla-cms/files/2249948/patches_featured_articles.zip)

**Comment by Folamour** [comment]
THANKS a lot, my service provider not reply at this time, thanks you so much

guillaume,

**Comment by Folamour** [comment]
Hi infograph hope you are fine, sorry that dont fix the issue, the article displayed still date from march not july : (

take a look rigth pane, "derniers articles" https://www.crashdebug.fr 

thanks

**Comment by infograf768** [comment]
I was not sure it would solve your specific issue as this patch deals with featured articles, not the date.

**Comment by Folamour** [comment]
ok so the issue remain, the module last article, no more show last published articles, but article from march instead of july, (its not featured only its all latest articles)

**Comment by ghost** [comment]
can you please use the Forum?

**Comment by infograf768** [comment]
@franz-wohlkoenig 
We may firs make sure the original issue is true or not.
I mean https://github.com/joomla/joomla-cms/issues/21347

After all nobody tested and it may not be a duplicate.

**Comment by Folamour** [comment]
ok updated on forum

**Pull request merged**
