### PR TITLE
Swap field descriptions 'user registration' (frontend) and 'user mana…

### PR DESCRIPTION
**Pull request by ghost**
…gement' (backend)

All field descriptions for optional fields in 'user registration' are "If required, please fill this field." This has no meaning to a regular user.
In addition to that this description exists only once for all fileds. (not usable)
On the other hand there is a single description for each optional user field in 'user management' which is unnecessary for admins or publishers.
So my solution was to change line 259 in profile.php
from: if ($app->isClient('site')...
to: if (!$app->isClient('site')...
This solved the problem (at least in my case).

Pull Request for Issue # .

### CODE REVIEW

**Comment by SharkyKZ** [comment]
With this change, the description from plugin configuration is shown. E.g. `Choose an option for the field Address 1`. This is not correct, IMO, as it refers to the required/optional/disabled options from plugin config.

**Comment by brianteeman** [comment]
@SharkyKZ is correct

**Comment by ghost** [comment]
So what would you suggest ? (Or do you doubt the problem ?)

**Comment by ghost** [comment]
Things get mor funny !
I just made some screenshots after selecting English as default language.
Forget about the backend - Frontend is more impotant.
Screenshots 1 (line 259 in profile.php **CHANGED**)
(In this case I can change these descriptions by language override)
frontend_w_patch

Screenshots 2 (line 259 in profile.php **UNCHANGED**)
(In this case I **can't** change these descriptions by language override)
frontend_wo_change

I hope you now can see what I mean !?

**Comment by brianteeman** [comment]
As explained by @sharkykz it refers to the required/optional/disabled options from plugin config.

**Comment by ghost** [comment]
Sorry, but what does that mean to me ?
Do I get my problem solved or not ?
What else can I do to have a different description field popup for each field (as in my screenshots 1)?

**Comment by brianteeman** [comment]
It means your proposed solution is not correct.

Personally I would not use that plugin. You can achieve what you want with custom fields.

**Comment by ghost** [comment]
@brianteeman 

> Personally I would not use that plugin

If I got it right, you say I should not use Joomla - because it's the original Joomla plugin what we are talking about here !

> You can achieve what you want with custom fields

Do you mean I should replace the original Joomla 'Users -> Manage -> **Users:Edit** -> User Profile' fields by 'Users -> Manage -> **Users:Fields**' ?

**Comment by brianteeman** [comment]
If the plugin does not suit your needs then yes I would create the fields using Users -> Manage -> Users:Fields'

**Pull request closed without merging**
