### PR TITLE
[4.0] Toolbar button CE: Fix Disabled state when nothing is checked in a list. Fix #20756

### LINKED ISSUE #20756: [4.0] 20650 Custom Element: Joomla! Toolbar button
### Steps to reproduce the issue
Since the merge of this PR last night it has revealed some broken behaviour in the script by @Fedik 
toolbar buttons that can't be used are disabled - this is great start to progressive disclosure

### Expected result
Publish button is disabled on the toolbar by default
Once an item is selected then it is enabled
Once the item is deselected then the publish button will be disabled again

### Actual result
The publish button is only disabled again on a page load not on deselecting an item- see video
menubar

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #20756 

### Summary of Changes
Fix Disabled state when nothing is checked in a list

### Testing Instructions
Please look #20756 for detail

### CODE REVIEW

**Comment by ghost** [comment]
Changed Title to show its about [4.0].

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6b6072b3dbf4cb14c243a017aaffd34982c8b93d<br /><br />Reported issue is fixed

Not sure if it is related or not but the batch button is always enabled<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20777">issues.joomla.org/tracker/joomla-cms/20777</a>.</sub>

**Comment by carlitorweb** [comment]
Without this PR, toolbar for me works normally. Or maybe I not understand this, in the way, I should do. Or maybe this was fixed in other PR.

video_2018-06-16_110458

**Comment by Quy** [comment]
Click the `Check All Items` checkbox.

**Comment by Quy** [comment]
See video in #20756

Buttons in toolbar should not be enabled when no entries are selected.

**Comment by carlitorweb** [comment]
@Quy  I did. I follow what Brian did on the issue report, but still work normally without the PR

new

**Comment by Quy** [comment]
Click on the `Check All Items` checkbox.
Buttons enabled.
Click on the `Check All Items` checkbox again.
Buttons should be disabled, but they are not.

**Comment by carlitorweb** [comment]
Oh!, I understand all wrong :( sorry and thank you for patience @Quy

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 6b6072b3dbf4cb14c243a017aaffd34982c8b93d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20777">issues.joomla.org/tracker/joomla-cms/20777</a>.</sub>

**Comment by carlitorweb** [comment]
So sorry for no understand well at first, sometimes my English make me look like an idiot :(

**Comment by Quy** [comment]
No worries. Thanks so much for testing. 👍

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20777">issues.joomla.org/tracker/joomla-cms/20777</a>.</sub>

**Comment by Quy** [comment]
> Not sure if it is related or not but the batch button is always enabled

Batch button should behave the same as the other buttons.

**Comment by Fedik** [comment]
@brianteeman  the batch button is another type of Toolbar Button (`PopupButton`), 
currently changes (make a Custom Element) affect only Toolbar `StandardButton`

> Batch button should behave the same as the other buttons.

I agree, but not today :)

**Comment by brianteeman** [comment]
OK lets merge this one then and batch can be a new pr

**Pull request merged**
