### PR TITLE
[4.0] Use email field type for password reset

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #31891 .

### Summary of Changes
Fix email field type

### Testing Instructions
Go to the reset password field and enter a name and hit submit

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
No

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 732ab95dce2ff0bafd0cd6f27090e8da264819ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31897">issues.joomla.org/tracker/joomla-cms/31897</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 732ab95dce2ff0bafd0cd6f27090e8da264819ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31897">issues.joomla.org/tracker/joomla-cms/31897</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31897">issues.joomla.org/tracker/joomla-cms/31897</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
