### PR TITLE
[4.0] Fix chosen form field

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #15338

### Summary of Changes

This PR fixes the jQuery Chosen form field disapearing.

### CODE REVIEW

**Comment by yasirunilan** [comment]
I have tested this item :white_check_mark: successfully on 5b47c7d1025529b95f23e1e6dd270a8f68c5d8db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15372">issues.joomla.org/tracker/joomla-cms/15372</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 5b47c7d1025529b95f23e1e6dd270a8f68c5d8db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15372">issues.joomla.org/tracker/joomla-cms/15372</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
