### PR TITLE
[4.3] Migrate quickicon overridecheck plugin to services

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Migrate the quickicon overridecheck plugin to service providers and use SubscriberInterface.

### Testing Instructions

- Check if quickicons are still working

image

### Actual result BEFORE applying this Pull Request

Overridecheck quickicon is working

### Expected result AFTER applying this Pull Request

Overridecheck quickicon is working (and the other quickicons are still displayed)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7a4fbd0352b2d8eabf75f0a2a26c40780128a001<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39170">issues.joomla.org/tracker/joomla-cms/39170</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 7a4fbd0352b2d8eabf75f0a2a26c40780128a001<br /><br />Installed an old version of DPCalendar, made an override and installed the latest one. The file check message was shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39170">issues.joomla.org/tracker/joomla-cms/39170</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 7fa627b2be63c5f6de9e025c2b05d5fb01cb34bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39170">issues.joomla.org/tracker/joomla-cms/39170</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39170">issues.joomla.org/tracker/joomla-cms/39170</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 once again!

**Comment by heelc29** [comment]
Thanks

**Pull request merged**
