### PR TITLE
[4.0] Generic string

### PR DESCRIPTION
**Pull request by brianteeman**
The generic string for permissions is not generic enough. It refers to _content_ when the component might not have any etc

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c401b2d4860a1dec8efda6cde90787f488e0098b<br /><br />even if i'm not the right one :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22162">issues.joomla.org/tracker/joomla-cms/22162</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c401b2d4860a1dec8efda6cde90787f488e0098b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22162">issues.joomla.org/tracker/joomla-cms/22162</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22162">issues.joomla.org/tracker/joomla-cms/22162</a>.</sub>

**Comment by laoneo** [comment]
Thanks, now I can throw mines away :-)

**Comment by brianteeman** [comment]
Happy to help 😂

**Pull request merged**
