### PR TITLE
Remove space from ID attribute on "Tel" field

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #16523

### Summary of Changes

Remove the space from the ID attribute

### Testing instructions

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c5c5ab303c3d40953b5cd6bf7eee0da1fc5c2fc4<br /><br />Space removed. In the page source, output wise, it now expands many lines.
```
<input
	type="tel"
	name="jform[telephone]"
	id="jform_telephone"
	value="abcd"
		size="30"          />
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16526">issues.joomla.org/tracker/joomla-cms/16526</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@fdesanto can you please test?

**Comment by wojsmol** [comment]
@C-Lodder Plese update test.

**Comment by C-Lodder** [comment]
Sure. Will do when Im home

**Comment by C-Lodder** [comment]
updated the PR to only remove the space from the ID attribute

**Comment by kolvar** [comment]
works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16526">issues.joomla.org/tracker/joomla-cms/16526</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@kolvar i altered your Test as successfully.
@Quy can you please retest?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6b7a5314e5171bd90214e294ac91e834795ba76b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16526">issues.joomla.org/tracker/joomla-cms/16526</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
