### PR TITLE
[4.0] Translating Joomla default workflow title

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23272

### Summary of Changes
Adding Text::_()

### Testing Instructions
Load `.../administrator/index.php?option=com_workflow&extension=com_content`

### Before patch
Joomla Default workflow name is not translated

screen shot 2018-12-12 at 11 49 23

### After patch
It is now translated

screen shot 2018-12-12 at 11 47 02

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on 888e22ebc3e82a8c5f49d80a554cbfeae5db01ac<br /><br />Thanks JM<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23275">issues.joomla.org/tracker/joomla-cms/23275</a>.</sub>

**Comment by gwsdesk** [comment]
Thanks JM<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23275">issues.joomla.org/tracker/joomla-cms/23275</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge 
I guess no need for another test here. Can be merged imho.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 888e22ebc3e82a8c5f49d80a554cbfeae5db01ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23275">issues.joomla.org/tracker/joomla-cms/23275</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23275">issues.joomla.org/tracker/joomla-cms/23275</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
