### PR TITLE
[lib/mod/templates] Always use htmlspecialchars($str, ENT_COMPAT, 'UTF-8')

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #10399 .
#### Summary of Changes

Always use htmlspecialchars($str, ENT_COMPAT, 'UTF-8')
#### Testing Instructions

Please do a code review or test all changed files.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 731710efbd33eaffddf79d5da5e9e0eda2a0396c<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10430">issues.joomla.org/joomla-cms/10430</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 731710efbd33eaffddf79d5da5e9e0eda2a0396c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10430">issues.joomla.org/joomla-cms/10430</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10430">issues.joomla.org/joomla-cms/10430</a>.</sub>

**Comment by zero-24** [comment]
Travis was fails on the sysinfo problem that is fixed upstream.

**Comment by brianteeman** [comment]
Setting back to RTC after sync <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10430">issues.joomla.org/joomla-cms/10430</a>.</sub>

**Pull request merged**
