### PR TITLE
[4.1] Fix quote markup in language string

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Quotes that are not starting/ending in the language string should be escaped.

### Testing Instructions
Code review.
or
Go to System > Administrator Templates
Create a Child Template.
In the list, view page source.

### Actual result BEFORE applying this Pull Request
`Child of <strong class=text-capitalize text-light>cassiopeia</strong>	`

### Expected result AFTER applying this Pull Request
`Child of <strong class="text-capitalize text-light">cassiopeia</strong>`

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f62a67812d3ccc3fdee00f8e8da1f54383b46f0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36173">issues.joomla.org/tracker/joomla-cms/36173</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f62a67812d3ccc3fdee00f8e8da1f54383b46f0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36173">issues.joomla.org/tracker/joomla-cms/36173</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36173">issues.joomla.org/tracker/joomla-cms/36173</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
