### PR TITLE
[4.1] Finder: Translate taxonomy titles in search results

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #34841.

### Summary of Changes
The taxonomy names are not translated in the search results so far. Since we do translate them in the search form, it's just a matter of adding the right code. Please note that not all taxonomies types are always translated. It is expected that you provide translation overrides where necessary and to fix additional issues around this, there is #36748.

### Testing Instructions
1. Setup a site with content and smart search
2. Enable debugging together with language debugging.
3. Search in the frontend for something.

### Actual result BEFORE applying this Pull Request
The taxonomies are listed, but the missins asterisks (*) show, that the strings aren't translated.

### Expected result AFTER applying this Pull Request
The taxonomies are listed and now are either wrapped in asterisks or even show translation keys.

### Note
I strongly suggest to only merge this when also #36748 is merged.

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 7e58afa3ba4f8c1f7128b3aa66ad5c5e832be378<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36863">issues.joomla.org/tracker/joomla-cms/36863</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7e58afa3ba4f8c1f7128b3aa66ad5c5e832be378<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36863">issues.joomla.org/tracker/joomla-cms/36863</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36863">issues.joomla.org/tracker/joomla-cms/36863</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
