### PR TITLE
[4.0] proper css for alerts

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #25850

### Summary of Changes
- Remove duplicate CSS

### Documentation Changes Required

~~Same thing needs to be done for the tabs as well~~

### CODE REVIEW

**Comment by brianteeman** [comment]
```
Error: Undefined variable: "$atum-box-shadow".
        on line 24 of administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
>>              box-shadow: $atum-box-shadow;
   --------------^

```

**Comment by brianteeman** [comment]
After making the suggested change manually I can partially confirm the fix.

The grey box is no longer displayed but the box is still there - this means that 
1. Subsequent errors are displayed below where the previous message was
2. Any buttons that are below this now invisible box will not be selectable

**Comment by brianteeman** [comment]
The above suggests to me that your css change is just fixing a symptom and not the cause. The real problem is that closing the alert does not remove it - it just tries to hide it

**Comment by dgrammatiko** [comment]
> The above suggests to me that your css change is just fixing a symptom and not the cause

Exactly, and it's not really a proper fix (im doing this on github's GUI...)

EDIT
NOT exactly what is happening:
Alert shows:
Screenshot 2019-08-24 at 23 10 46
On close:
Screenshot 2019-08-24 at 23 11 00
Alert completely removed.
Now if there is more styling on the container, that's obviously wrong, the container is there only for the positioning IIRC. If someone decided to apply more styles that's really wrong, but I think with this PR, once it compiles correctly the file everything should be ok

**Comment by brianteeman** [comment]
you know i dont like band aid fixes

**Comment by dgrammatiko** [comment]
@brianteeman this is a total clusterF37t!! 
People decided to add animation and yet another container...
Screenshot 2019-08-24 at 23 17 04


FWIW alerts already have fade in animation: https://github.com/joomla-projects/custom-elements/blob/57742d291e7e906f29f82f71505dcd33e2acf5b2/src/scss/alert/alert.scss#L72

This is a rabbit hole...

**Comment by brianteeman** [comment]
(i will not comment on people only code)

**Comment by dgrammatiko** [comment]
And guess what this is done in JS because the html doesnt have that fade-in class: https://github.com/dgrammatiko/joomla-cms/blob/3792219bb55a1eb71a762ef4095863c802aca3c8/administrator/templates/atum/index.php#L180

**Comment by dgrammatiko** [comment]
@brianteeman please re open the issue, this needs a bit work that I can't do through the github GUI

**Comment by alikon** [comment]
#25850 reopened as requested

**Comment by HLeithner** [comment]
@dgrammatiko thank you very much trying to fix this. Do you plan and have time to repair it later?

**Comment by brianteeman** [comment]
@alikon looks like you didnt re-open this?

**Comment by dgrammatiko** [comment]
FWIW https://github.com/joomla/joomla-cms/pull/26077 is achieving the same goal, so maybe this can be ignored

**Pull request closed without merging**
