### PR TITLE
[4.3] clear button in list view is not disabled when no "filter" is active

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issues #40378 and #40475.

### Summary of Changes

Reset button should be clickable only when something is active

### Testing Instructions

Follow the issues

### Link to documentations
No bug

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 37d4ca908a6a749440a4c6b4b300d4ef162714b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 37d4ca908a6a749440a4c6b4b300d4ef162714b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by brianteeman** [comment]
This needs to be merged and included in 4.3.1

**Comment by richard67** [comment]
From what I can see, this also fixes the unwanted reset of the ordering and the list limit fields and so could indeed fix also the release blocker issue #40475 . But I don't have the huge amount of data to check the out of memory aspect.

**Comment by brianteeman** [comment]
>  But I don't have the huge amount of data to check the out of memory aspect.

Try to use https://github.com/nikosdion/overload

**Comment by richard67** [comment]
Anyway this PR here has deserved the release blocker label because the issue with the unwanted reset of the ordering and the list limit fields has been introduced with 4.3.0, in 4.2.9 it was ok.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 37d4ca908a6a749440a4c6b4b300d4ef162714b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by brianteeman** [comment]
Unfortunately this is not complete

Scenario 1
Clear button not enabled by default ✔️

Scenario 2
Clear button enabled when filter is set ✔️

Scenario 3
Clear button when selected correctly applies the default list limit ❌

It does display the number in the select box BUT the limit is not applied
image

**Comment by richard67** [comment]
@brianteeman I can confirm your finding for the core list view, e.g. content/categories. With the patchtester's list view it works.

As the PR originally claimed only to solve issue #40378 , it is successful regarding this, but not regarding the other issue #40475 .

Quite a matter of taste now if we lave this PR RTC and solve the other issue with another one, or if we remove RTC here and ask for a fix with this PR here. @dgrammatiko What would you prefer?

**Comment by dgrammatiko** [comment]
> What would you prefer?

Let's tackle it here, give me couple of hours as I'm in the middle of some other work right now

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ac9b4f5123baf0ee42061e949f1887b02b6f902e<br /><br />Solves issue #40378 and as far as I can see (not enough data to cause the memory run out) also issue #40475 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by Attila-SWE** [comment]
Unsure how to test without composer but please instruct me and I will report back.

**Comment by Attila-SWE** [comment]
Tested and solves issue #40475 for me too! Great job team!

**Comment by richard67** [comment]
> Tested and solves issue #40475 for me too! Great job team!

@Attila-SWE Have you also checked if the reset button is inactive when there is no filter selected, and active when there is one? If so, I would call it a successful test. Could you go to the PR in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/40398 , then use the blue "Test this" button at the top left corner, then select your test result (success) and finally submit? Thanks in advance.

**Comment by Attila-SWE** [comment]
I have tested this item :white_check_mark: successfully on ac9b4f5123baf0ee42061e949f1887b02b6f902e<br /><br />Replaced media/system/js/searchtools.js from compiled file. Clear button inactive when no filter applied and no more issue with displaying all entries when clearing search.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40398">issues.joomla.org/tracker/joomla-cms/40398</a>.</sub>

**Comment by obuisard** [comment]
Yes, indeed, great job, thanks Dimitris @dgrammatiko and all for looking into it.

**Pull request merged**
