### PR TITLE
[4.0] build.js instructions

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the description for the watch-com-media command as described in the comment in line 73

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 3be4e28bd894d27eb78ae8cc4222b6519a8955dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36390">issues.joomla.org/tracker/joomla-cms/36390</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3be4e28bd894d27eb78ae8cc4222b6519a8955dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36390">issues.joomla.org/tracker/joomla-cms/36390</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36390">issues.joomla.org/tracker/joomla-cms/36390</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
