### PR TITLE
[4] s/Banner/BannerTable

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b8d6f0639a3dac439e3afd79cde1ab3e8ae343c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34010">issues.joomla.org/tracker/joomla-cms/34010</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b8d6f0639a3dac439e3afd79cde1ab3e8ae343c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34010">issues.joomla.org/tracker/joomla-cms/34010</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34010">issues.joomla.org/tracker/joomla-cms/34010</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
