### PR TITLE
[4.0] Always try to create content language when installing a language

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #28176 .

Currently, a content language is only automatically created when doing a fresh install of a language pack. When using the reinstall feature or the discover install one, it isn't created.

### Summary of Changes
I've moved the code to create a content language into an own method in the class and calling that class new also from the `discover_install` and `update` path.
I also added a check so the language is only created if the content language doesn't already exist.

### Testing Instructions
* Install a language pack (eg German)
* Check that the content language is created, then trash it and empty the trash.
* Use the "Reinstall" button in the Install Language view to install the same language again
* Check that the content language is created again, then again delete it.
* Delete the entries for the language in the #__extensions table. It should be those with the highest ID if you installed it fresh
* Try to discover install the language and check that the content language is yet again created.
* Try to reinstall/discover install without deleting the content language and make sure you don't get multiple times the content language and also no error messages.

### Expected result
Content language is created after each install/update/reinstall/discover_install

### Actual result
Content language is only created during intial install

### Documentation Changes Required
None

### CODE REVIEW

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on fb08f7731c94be9387b51c625322f4b18f56ad03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28243">issues.joomla.org/tracker/joomla-cms/28243</a>.</sub>

**Comment by astridx** [comment]
For the tests described above, I deleted the language using the Extension Manager. I found that the content language is not deleted (is that an error?). After the new installation of the language I got the message shown in the picture and the content language was actually not installed twice.

Extensions  Languages   test   Administration

**Comment by alikon** [comment]
maybe off-topic but meanwhile testing this pr switching from  Languages: Content to  Languages: Installed  an viceversa was very annoying , maybe there should be a direct between the two 
what do you think ?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fb08f7731c94be9387b51c625322f4b18f56ad03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28243">issues.joomla.org/tracker/joomla-cms/28243</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28243">issues.joomla.org/tracker/joomla-cms/28243</a>.</sub>

**Comment by wilsonge** [comment]
> I found that the content language is not deleted (is that an error?)

It's not - it's by design - because of the ripple effect of items that are assigned to that content language

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
👍

**Comment by Bakual** [comment]
> After the new installation of the language I got the message shown in the picture and the content language was actually not installed twice.

That actually shouldn't happen. The code should check if the content language already exists and only try to create when not. So if that error is reproducable, we should fix it.

**Comment by astridx** [comment]
@Bakual I think I have expressed myself misleadingly. The content language was already there. It is therefore correct that it has not been installed again.

**Comment by Bakual** [comment]
Yep, but it shouldn't give you a notice about it. That part is wrong. It should silently skip it.

**Comment by infograf768** [comment]
@Bakual
Concerning the useless Notice, here are 2 possible solutions.
Which one do you prefer?


[contentlang_notice2.diff.zip](https://github.com/joomla/joomla-cms/files/4473633/contentlang_notice2.diff.zip)
[contentlang_notice.diff.zip](https://github.com/joomla/joomla-cms/files/4473634/contentlang_notice.diff.zip)

**Comment by Bakual** [comment]
contentlang_notice.diff.zip looks like the simplest approach to me.

**Comment by infograf768** [comment]
@Bakual 
If we use that one, do we really need to keep
```
		// Check if content language already exists.
		if ($tableLanguage->load(array('lang_code' => $tag)))
		{
			return;
		}
```
or is simply this `return` not the code to use at all. It is confusing.

**Comment by infograf768** [comment]
Hmm, after some more tests, I can't reproduce anymore the Notice.

**Comment by Bakual** [comment]
Ah true, we already have that code at the beginning. That's why I meant it should never show that notice to begin with.
I never saw it myself so I have no clue why it happend.

**Pull request merged**
