### PR TITLE
[4.1] incorrect role on language switcher

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37479 .

### Testing Instructions
Make sure that you test all the variants of the module

the role that was not needed is only for use when you have non-list elements eg div that you want to behave like a select option. you cant apply that to an existing list.

### CODE REVIEW

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on a2a06de16219bd5e49ad919d8fc1f61b76e1bc4b<br /><br />Tested successfully on 4.1.2 with Cassiopeia and two languages.



Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37483">issues.joomla.org/tracker/joomla-cms/37483</a>.</sub>

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on a2a06de16219bd5e49ad919d8fc1f61b76e1bc4b<br /><br />I tested with Lighthouse on Chrome: 100% in accessibility (84% before this patch) and with IBM Equal Access Accessibility Checker: the error I had before (Violation: The element with role "option" is not contained in or owned by an element with one of the following roles: "group, listbox") is now gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37483">issues.joomla.org/tracker/joomla-cms/37483</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37483">issues.joomla.org/tracker/joomla-cms/37483</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
