### PR TITLE
[4.0] Bootstrap 5.0 plus more

### PR DESCRIPTION
**Pull request by brianteeman**
This PR updates several npm packages

Of note are

### Bootstrap 5.0
https://github.com/twbs/bootstrap/compare/v5.0.0-beta3...v5.0.0

### Codemirror 5.6.10
https://codemirror.net/doc/releases.html

### TinyMCE 5.8.0
https://www.tiny.cloud/docs/changelog/

### CODE REVIEW

**Comment by wilsonge** [comment]
I'm going to merge this as the tests are passing so superficially things work - and given we've also got the new UI in as well these can be tested together in nightlies (I'll trigger a fresh nightly now)

**Comment by brianteeman** [comment]
agreed - thanks

**Comment by ReLater** [comment]
Just as info: Grave bug in BS5 javascript under some circumstances. But shouldn't concern Joomla 4 core at the moment(?). Haven't tested.
https://github.com/twbs/bootstrap/issues/33840

**Comment by HLeithner** [comment]
> Just as info: Grave bug in BS5 javascript under some circumstances. But shouldn't concern Joomla 4 core at the moment(?). Haven't tested.
> [twbs/bootstrap#33840](https://github.com/twbs/bootstrap/issues/33840)

Doesn't effect us because we load BS at the end of the body tag.

**Pull request merged**
