### PR TITLE
Adds language flags to listing tables

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds language flags to listing tables in menu items, categories, articles, featured articles, modules, banners, news feeds, tags and contacts (and their modals) in administrator panel.

Example:
langs
#### How to test
1. Fresh Joomla install with multilanguage (several languages).
2. Apply this patch
3. Check if flags are displayed in menu items, categories, articles, featured articles, modules, banners, news feeds, tags and contacts (and their modals) listings.
4. Do the same for hathor template.

For com_weblinks check https://github.com/joomla-extensions/weblinks/pull/176
#### Observations

Suggestions are welcome.

### CODE REVIEW

**Comment by infograf768** [comment]
This works fine.
I propose to add a similar UX for template styles.
I also added the tooltip:

screen shot 2015-12-31 at 08 57 29

Diff available here:
https://www.dropbox.com/s/b9azgs1ck1jb3i7/template_styles.diff?dl=0

**Comment by andrepereiradasilva** [comment]
@infograf768 i made some changes.

- Transformed the image in a button like the "star" buttons. Example:
image
- Also has a bootstrap tooltip with the native language like the "star" buttons.
- Also now uses the same 'jgrid.isdefault' JHtml method like the "star" buttons.

Tested and it works, but still want to do some review to the jgrid code.

What do you think?

**Comment by infograf768** [comment]
The button is a nice idea.
Adding the flag in the tooltip looks a bit overkill. :smiley:
Putting the language name inside the button would make the button quite enormous.

**Comment by andrepereiradasilva** [comment]
@infograf768 i will make a new PR for the default language buttons in templates, menus and contacts (i think). This one will stay just for the language flags in the language columns.

I improved a bit the code and added them to hathor too. 

For com_weblinks i created a PR https://github.com/joomla-extensions/weblinks/pull/176 and a change to hathor weblinks override (https://github.com/joomla/joomla-cms/commit/b40b35e01d9aebfc3302c7842c678f2174664b22) here.

**Comment by andrepereiradasilva** [comment]
@infograf768 the language buttons are in this PR: https://github.com/joomla/joomla-cms/pull/8826/

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b40b35e01d9aebfc3302c7842c678f2174664b22<br /><br />Once the conflict is solved (tag), perfect improvement. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8815">issues.joomla.org/joomla-cms/8815</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Thanks.

> Once the conflict is solved (tag)
Didn't understand ...

**Comment by dgt41** [comment]
@andrepereiradasilva you have to resync this as there is a msg: `This branch has conflicts that must be resolved` at the end of this page...

**Comment by andrepereiradasilva** [comment]
No conflicts now.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 84e643a69ec637b0343666b78ad45bd049190d1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8815">issues.joomla.org/joomla-cms/8815</a>.</sub>

**Comment by infograf768** [comment]
@andrepereiradasilva 

Could you modify the size of the language column for the menu items list?
from 5% to 15%
```
<th width="15%" class="nowrap hidden-phone">
							<?php echo JHtml::_('searchtools.sort', 'JGRID_HEADING_LANGUAGE', 'language', $this->state->get('list.direction'), $this->state->get('list.ordering')); ?>
						</th>
```
This will let longer Content Languages names display on one line when screen is larger than 800 px.
screen shot 2016-01-22 at 10 32 19

**Comment by brianteeman** [comment]
Good spot @infograf768 
Looking at the other views it looks like they are all at 10%

**Comment by infograf768** [comment]
>Looking at the other views it looks like they are all at 10% 

yes, but in the menu items list it looks like using 15% is much better because Home is set to 5%

**Comment by andrepereiradasilva** [comment]
@infograf768, @brianteeman 15% now.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 850a8e5cdb22bbe0891a39314cd095071d80f034<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8815">issues.joomla.org/joomla-cms/8815</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 850a8e5cdb22bbe0891a39314cd095071d80f034<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8815">issues.joomla.org/joomla-cms/8815</a>.</sub>

**Comment by infograf768** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8815">issues.joomla.org/joomla-cms/8815</a>.</sub>

**Pull request closed without merging**
