### PR TITLE
Little correction for de.js

### PR DESCRIPTION
**Pull request by hacki65**
I have corrected a little issue in line 219 "Show blocks". There was one space too much at the beginning of the translated string.

Pull Request for Issue # .

### CODE REVIEW

**Comment by infograf768** [comment]
@Bakual 
Looks fine to me.

**Comment by zero-24** [comment]
Merged thanks!

**Comment by zero-24** [comment]
cc @sisko1990 @tecpromotion

**Comment by hacki65** [comment]
Thanks

**Pull request merged**
