### PR TITLE
[plg_content_pagenavigation] Missing Bootstrap tooltip import

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #22256 .

### Summary of Changes

Imports Bootstrap tooltips.

### Testing Instructions

Enable `Content - Page Navigation` plugin. Open an article. Hover over the navigation links generated by the plugin.

### Expected result

Article title shown in Bootstrap tooltips.

### Actual result

Default browser tooltips.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by ghost** [comment]
@sandewt please test this Pull Request.

**Comment by Quy** [comment]
Without this PR, I see the Bootstrap tooltips.

**Comment by SharkyKZ** [comment]
@Quy that's possible if something else loads tooltips. Login module, for example.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b2dc1338bc77113d08b47d3bcbee1c52ea1c55d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24203">issues.joomla.org/tracker/joomla-cms/24203</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on b2dc1338bc77113d08b47d3bcbee1c52ea1c55d0<br /><br />PHP Version	7.1.20
Web Server	Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/7.1.20
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.9.5-dev Development [ Amani ] 12-March-2019 15:27 GMT
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24203">issues.joomla.org/tracker/joomla-cms/24203</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
