### PR TITLE
Update RoboFile and composer dependencies for system testing in Joomla 4

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Updates the RoboFile.php to work with the robo-joomla repository (currently only used for Selenium). Updated the dev dependencies for the latest Selenium-Server-Version, codeception etc.

### Testing Instructions

Code Review

### Expected result

System tests work with newest Selenium 3.11.0 and Joomla 4

### Actual result

No System tests in Joomla 4

### Documentation Changes Required

--

### CODE REVIEW

**Comment by 810** [comment]
ERROR: file_get_contents(C:\wamp\www\test2/acceptance.suite.yml): failed to open stream: No such file or directory
in C:\wamp\www\test2\RoboFile.php:459

**Comment by yvesh** [comment]
@810 fixed  with #20035

**Comment by 810** [comment]
mhh still getting error:

ERROR: file_get_contents(C:\wamp\www\test2/libraries/vendor/joomla/test-system/src/acceptance.suite.yml): failed to open stream: No such file or directory
in C:\wamp\www\test2\RoboFile.php:470

**Comment by 810** [comment]
ah needed to remove the dist. 

maybe a check there will be good.

**Pull request merged**
