### PR TITLE
[4.0] Fixing com_media URLs for frontend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/30005.

### Summary of Changes

Currently media manager doesn't work in frontend if you're not logged in to backend because all URLs point to backend. This is an attempt to fix the issue.

### Testing Instructions

`node build.js --compile-js` required.
Log out of backend.
Login to frontend.
Edit an article in frontend.
In editor click CMS Content -> Image to insert an image.

### Actual result BEFORE applying this Pull Request

Doesn't work.

### Expected result AFTER applying this Pull Request

Works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
It is working, however, the image will not insert into the article.

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. Are you getting any JS errors?

**Comment by Quy** [comment]
Sorry, never mind. I forgot to clear the browser's cache.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2f83cd7cef5a233871310b9bb114667dfbf265e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30617">issues.joomla.org/tracker/joomla-cms/30617</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2f83cd7cef5a233871310b9bb114667dfbf265e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30617">issues.joomla.org/tracker/joomla-cms/30617</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30617">issues.joomla.org/tracker/joomla-cms/30617</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
Problem editing image, see https://github.com/joomla/joomla-cms/issues/30664
@SharkyKZ

**Pull request merged**
