### PR TITLE
#9020 Inappropriate term in User Status module

### PR DESCRIPTION
**Pull request by jtherczeg**
PR for #9020 Inappropriate term in User Status admin module.
By the terms used in Who's Online frontend module, I selected the term member.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 033ec70653fbba50b553bdcf24525090a0657323<br /><br />Works as described
@brianteeman I have a vague memory of a previous discussion about this but can not find it.
Perhaps it would have been interesting to see what had been said before?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9030">issues.joomla.org/joomla-cms/9030</a>.</sub>

**Comment by brianteeman** [comment]
Shouldn't the pr be against the staging branch @bakual

**Comment by brianteeman** [comment]
Personally I would only change it to make sure it matched the description in the module

z9bg

**Comment by jtherczeg** [comment]
@MATsxm and @brianteeman I was also thinking for a long time which term to choose. "Registered" was my first idea, too, finally I selected "member", because this is used in the Who's Online frontend module.

If you decide to change this, you are allowed. Fact, that this needs to be changed. The major Joomla version and the update of the module would be a good occasion.

**Comment by brianteeman** [comment]
Unfortunately I think language strings have been frozen.

**Comment by Bakual** [comment]
> Shouldn't the pr be against the staging branch

@brianteeman You're right, I didn't check that. If all agree on this change, I can still merge it since it's quite a simple PR.
The language strings are only yet frozen for the installation folder. The others get frozen for the release candidates usually.

**Comment by infograf768** [comment]
OK for me.

**Comment by brianteeman** [comment]
doesnt work for me - the change is no better than the current - which I
agree is misleading

Take a look at the core admin module Logged in users - that has got it right
Logged-in Users 123 Administration 123 Site



On 30 January 2016 at 18:32, infograf768 <notifications@github.com> wrote:

> OK for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9030#issuecomment-177268292>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jtherczeg** [comment]
Actually, I also prefer (logged-in users", but thinking with the head of a translator, "logged-in users" is short in English (16 chars), while a translation may be much longer, in Hungarian for instance 28 chars, what will not look well on the status bar.

**Comment by MATsxm** [comment]
agree with both, then is it ok @brianteeman if we just use: 'Logged-in'?
we then already suppose we are talking about "Users"?

**Comment by chrisdavenport** [comment]
Closing as "Members" is not appropriate in this context and no better term than the one currently in use has been suggested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9030">issues.joomla.org/joomla-cms/9030</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9030">issues.joomla.org/joomla-cms/9030</a>

**Pull request closed without merging**
