### PR TITLE
[4] order requires a string or array

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9b7496e545bc92db4f840a484ef912cb50559269<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33955">issues.joomla.org/tracker/joomla-cms/33955</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9b7496e545bc92db4f840a484ef912cb50559269<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33955">issues.joomla.org/tracker/joomla-cms/33955</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33955">issues.joomla.org/tracker/joomla-cms/33955</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
