### PR TITLE
[4.4] set_time_limit php 8

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38876 .

### Summary of Changes
some hosts disable set_time_limit in php

> Prior to PHP 8.0.0, it was possible for the @ operator to disable critical errors that will terminate script execution. For example, prepending @ to a call of a function which did not exist, by being unavailable or mistyped, would cause the script to terminate with no indication as to why.

This PR replaces the @ with a function_exists check

### Testing Instructions
code review or in php.ini
disable_functions = set_time_limit

### Actual result BEFORE applying this Pull Request
Admin dashboard loads with an error
finder index ends with an error

### Expected result AFTER applying this Pull Request
everything works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman As this PR is for 4.4-dev: Have you checked if it works with PHP 7.4? I'm asking because of this info I get from here https://php.watch/versions/8.0/disable_functions-redeclare , especially the last sentence :

> `function_exists()` returns `false` for disabled functions
> `function_exists()` function now returns `false` for functions disabled with `disable_functions` INI directive. This is because internally, disabled functions do not even make to the internal functions table.
> Prior to PHP 8, to check if a function is disabled, one would need to query the INI setting, or use the return value of get_defined_functions() function.

Could you check?

**Comment by brianteeman** [comment]
@richard67 I assume it works otherwise we have a problem with the existing use
https://github.com/joomla/joomla-cms/blob/d20c4557cea681d02aeceee97e9ece795961da2f/administrator/components/com_scheduler/src/Scheduler/Scheduler.php#L134-L136

**Comment by brianteeman** [comment]
I just retested this PR with php 7.4.9 and set_time_limit disabled and no problems

**Comment by richard67** [comment]
> I just retested this PR with php 7.4.9 and set_time_limit disabled and no problems

Ok, thanks for checking.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2daf4cf2a87f5baa10cd88881de7f4023ce25941<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41523">issues.joomla.org/tracker/joomla-cms/41523</a>.</sub>

**Comment by richard67** [comment]
Is there a reason why this PR is made for 4.4-dev and not 4.3-dev? To me it seems to be a bug fix.

**Comment by brianteeman** [comment]
No reason

**Comment by laoneo** [comment]
Do we have to copy the changes to the framework package as well @Hackwar?

**Comment by wilsonge** [comment]
Would be good to get this in the framework file system too if it’s effected but it’s not a hard requirement

**Comment by laoneo** [comment]
@brianteeman are able to add the checks also to the framework package?

**Comment by brianteeman** [comment]
@wilsonge @laoneo I already did the framework changes last week at the same time I did this https://github.com/joomla-framework/filesystem/pull/59

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
