### PR TITLE
[5.1]Add focus to treeselect [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
In the module manager when you open the tree to assign a module to specific menu items it was not possible to navigate to the chevron with a keyboard to open and close the tree.

This pr ensures that you can tab to the chevron and press enter to expand or collapse the tree.

Don't moan at me for bad js as the original js was written by the person who has asked for this bug fix

**PARTIAL Pull** Request for Issue #43068 .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 91e75fa92151df09eea785351694ee6a8c57b2f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43125">issues.joomla.org/tracker/joomla-cms/43125</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 91e75fa92151df09eea785351694ee6a8c57b2f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43125">issues.joomla.org/tracker/joomla-cms/43125</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43125">issues.joomla.org/tracker/joomla-cms/43125</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Comment by wilsonge** [comment]
Thankyou!!

**Pull request merged**
