### PR TITLE
Improve the accessibility of the sidebar menu in ISIS

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

The light grey highlight when hovering or navigating with the keyboard through the sidebar menu is almost impossible to see.

This PR uses the exact same highlighting as the dropdown menu
#### Before

a11ymenub
#### After

a11ymenua

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 106dbc34edc2345267bfb289e6062583304108a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 106dbc34edc2345267bfb289e6062583304108a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 106dbc34edc2345267bfb289e6062583304108a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by MATsxm** [comment]
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 106dbc34edc2345267bfb289e6062583304108a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11723">issues.joomla.org/joomla-cms/11723</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
