### PR TITLE
[4.0] Sample Data newsfeed

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the creation of a Release News module in the admin by the sample data plugin. It is never displayed.

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0b92f1de286441ccef4feefae1f51505bd761758<br /><br />Nice find! For testing purposes there is the "Admin Feed Module" available in the backend. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33922">issues.joomla.org/tracker/joomla-cms/33922</a>.</sub>

**Comment by richard67** [comment]
> Nice find! For testing purposes there is the "Admin Feed Module" available in the backend.

@RickR2H Which admin feed module do you mean?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0b92f1de286441ccef4feefae1f51505bd761758<br /><br />The module is created in database but with a module position which doesn't exist in the Atum template, and I don't really see one where this module looks good in backend.

An alternative would be to create that module at the right place, if there was some.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33922">issues.joomla.org/tracker/joomla-cms/33922</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33922">issues.joomla.org/tracker/joomla-cms/33922</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by brianteeman** [comment]
thx

**Comment by chmst** [comment]
I was too late .. but if we had changed the position, we would have got this: 
grafik

This module needs a little bit love in the header part.

**Pull request merged**
