### PR TITLE
TranslateFormat in all other forms

### PR DESCRIPTION
**Pull request by Bakual**
This PR extends the use of the new feature for translated date (and time) formats in the calendar formfield  to all other core extensions.
https://github.com/joomla/joomla-cms/pull/12102 originally introduced that feature but only did it for com_content.

### Summary of Changes
Replace the hardcoded format in the form declaration with `translateFormat="true"` and `showTime="true"` where appropriate.

### Testing Instructions
* Add the new language strings to your second language you have installed. Eg for de-DE add this to both de-DE.ini files (frontend and backend):
```
DATE_FORMAT_CALENDAR_DATE="%d.%m.%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d.%m.%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATETIME="d.m.Y H:i:s"
DATE_FORMAT_FILTER_DATE="d.m.Y"
```
* Make sure all instances of a calendar formfield (usually the created/modified/publish_up/publish_down) are using the translated format and don't create an error when saving.

### Documentation Changes Required
None that I'm aware of.

### CODE REVIEW

**Comment by Bakual** [comment]
Affected extensions are:
#### Backend
* User Profile
* Banner
* Contact
* Smart Search Filter
* Module
* Newsfeed
* Tag
* User Note
* User
#### Frontend
* Module
* Article
#### Modules
* Articles - Category
* Articles  - Most Read

**Comment by infograf768** [comment]
Looks OK on review.

**Comment by andrepereiradasilva** [comment]
works as described.

Maybe for another PR, but notice several other places the date format is not translated

Version:
image

Category
image

field
image

user list 
image

and probably more.

**Comment by Bakual** [comment]
For this PR I did a search for the calendar type formfield.

* The version date is not a formfield at all. That should be done using one of the regular translated date formats. Currently it is hardcoded. See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_contenthistory/views/history/tmpl/modal.php#L149
* The category edit for some reason uses a text field instead of the calendar one we use elsewhere. See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/forms/category.xml#L185-L192
Same thing for the field edit. It would have to be changed to calendar to support this feature. Imho it should be done in another PR as it also has other implications (like applying the timezone difference).

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f0c226cababffe7b9c790dd59313d3be3802893e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13158">issues.joomla.org/tracker/joomla-cms/13158</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f0c226cababffe7b9c790dd59313d3be3802893e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13158">issues.joomla.org/tracker/joomla-cms/13158</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13158">issues.joomla.org/tracker/joomla-cms/13158</a>.</sub>

**Pull request merged**
