### PR TITLE
[4.0] npm build tools update

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue none.

### Summary of Changes
- Use the latest babel
- Use one and only one way to transpile ES-xxxx files
- Refactor and modularise
- Update ALL the **dev** dependencies
- Drop copying the es6 files in the media folder (until there is a way to utilise these files their presence in the media folder is useless)

### Testing Instructions
- npm install should recreate the media folder correctly
- all the other npm commands in the package.json should give the exact same results (mind the drop of the es6 files)

### Documentation Changes Required
From a functionality point of view there is nothing added to be documented.

PS. This is the first of multiple PRs but I'll try to make these in small chunks of code so ppl can review/test. Also I need a solid foundation to fix my own clasterf**k with the custom broken elements 🤔

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@rdeutz can you restart the tests here?

**Comment by zero-24** [comment]
Done even when I'm not @rdeutz :P

**Comment by dgrammatiko** [comment]
@infograf768 can I have a test here please?

**Comment by infograf768** [comment]
Hard to test what one does not understand. 
Would it solve the session and install languages issue described here?
https://github.com/joomla/joomla-cms/issues/23222

**Comment by dgrammatiko** [comment]
I don't think so, those two are related to the session in the php part and if I remember correctly the last page (where someone could select the extra languages and the sample data) somehow have a new session (?). Pretty sure this was fixed at some point by @wilsonge 

For this PR a simple check that the media folder is regenerated correctly is all we need...

**Comment by infograf768** [comment]
The media folder is regenerated correctly.
Custom extensions stuff present in media folder on an existing site are not deleted when re-running npm ci

Still the same issue with com_media `node_modules` which has to be deleted before running npm ci in order to get the files in media/com_media/css and js 

see https://github.com/joomla/joomla-cms/pull/22860

**Comment by wilsonge** [comment]
You're still copying the es6 files at the moment; Given the PR description I guess that's not expected. But everything appears to work fine so merging

**Comment by dgrammatiko** [comment]
> Given the PR description I guess that's not expected. 

The idea is that there is no ES6 but yearly versions of javascript since 2015. Copying the files as is might work right now (If the project decides to deliver actual es-20XX code) but in reality features might need to be polyfilled, depending the target minimum version (the reason is that not all browsers support simultaneously all js features). Anyways since this is not the case right now and since there is way to transpile using poly fills (that was the main point of this PR) copying the files over is not a big deal (is just dead code that inflates the zip files). As I mentioned there gonna be some more PRs on the build tools, so this should be good enough for now

**Pull request merged**
