### PR TITLE
[4.0] com_modules invalid markup

### PR DESCRIPTION
**Pull request by brianteeman**
you can't have two style attributes. Bug introduced with #1505

### CODE REVIEW

**Comment by Quy** [comment]
Add a space after `;` to be consistent here: https://github.com/brianteeman/joomla-cms/blob/dc600390abeb584583e7279d6aa1693fe56b393a/administrator/components/com_newsfeeds/tmpl/newsfeeds/default.php#L50

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dc600390abeb584583e7279d6aa1693fe56b393a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20970">issues.joomla.org/tracker/joomla-cms/20970</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks for the fast tests and merge

**Pull request merged**
