### PR TITLE
Content History: Missing check-out labels and Lang strings

### PR DESCRIPTION
**Pull request by infograf768**
When using Versions, the preview and compare popups do not display a translatable label for the Id of the user who checked out the item and the date for that check-out.
Instead, it uses the name of the fields, i.e. `checked_out` and `checked_out_time`.
Except for Newsfeeds where we do have a label, but no lang strings.

This gives (fr interface):

newsfeed_fr_before

weblinks_fr_before

**After this patch, we will get:**

screen shot 2016-09-23 at 09 06 46

New lang strings:

```
JGLOBAL_FIELD_CHECKEDOUT_LABEL="Id of the User who Checked-out"
// we could put here: "Checked-out by"
JGLOBAL_FIELD_CHECKEDOUT_TIME_LABEL="Date of the Check-out"
// or "Check-out date" ?
```

@brianteeman 
strings OK?

### CODE REVIEW

**Comment by infograf768** [comment]
Note: Languages are frozen for 3.6.3. Therefore this woud be for next version.

**Comment by brianteeman** [comment]
Checked with 3.7 and com_newsfeeds and I do not see an untranslated field for checkout
In general I do not see the need for the checkout time or user to be displayed in the version info<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12147">issues.joomla.org/joomla-cms/12147</a>.</sub>

**Comment by infograf768** [comment]
Looks like there are changes in 3.7.
These fields are no more displayed, except if I mistake in my new tests.

Code is there though in the models/forms/newsfeed.xml and similar xmls:
```
<field
			name="checked_out"
			type="Text"
			label="JGLOBAL_FIELD_CHECKEDOUT_LABEL"
			description="JGLOBAL_FIELD_CHECKEDOUT_DESC"
			size="6"
			readonly="true"
			filter="unset"
		/>

		<field
			name="checked_out_time"
			type="Text"
			label="JGLOBAL_FIELD_CHECKEDOUT_TIME_LABEL"
			description="JGLOBAL_FIELD_CHECKEDOUT_TIME_DESC"
			size="6"
			readonly="true"
			filter="unset"
		/>
```

and elsewhere it is:

```
<field
		name="checked_out"
		type="hidden"
		filter="unset"
	/>

	<field
		name="checked_out_time"
		type="hidden"
		filter="unset"
	/>
```

**Comment by brianteeman** [comment]
Checked in 3.6.3 as well and dont see the checked out fields being displayed either<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12147">issues.joomla.org/tracker/joomla-cms/12147</a>.</sub>

**Comment by brianteeman** [comment]
@infograf768 so do we need this PR - we both cant see the checked out values in the versions display and there really is no reason to add it as it has no value for versions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12147">issues.joomla.org/tracker/joomla-cms/12147</a>.</sub>

**Comment by brianteeman** [comment]
@inforgraf768 can we close this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12147">issues.joomla.org/tracker/joomla-cms/12147</a>.</sub>

**Comment by infograf768** [comment]
will look at it again when i have some time.

**Comment by brianteeman** [comment]
I am closing this at this time. its been 5 months since the last comment and it would appear to not be used. it can always be reopened if needed

**Pull request closed without merging**
