### PR TITLE
[4.1] Update PHPUnit to 9 and all other dependencies

### PR DESCRIPTION
**Pull request by laoneo**
Followup of #36776 which increases the PHPUnit version to 9 and sets the min PHP version to 7.3.

### CODE REVIEW

**Comment by brianteeman** [comment]
Did you mean to include libraries/src/Table/Nested.php

**Comment by zero-24** [comment]
I'm not sure whether it would be wise to upgrade the minimum php version within an minor version. If anything a decision should be made before basing work on it and it should be updated on all places within the CMS ;)

Also the drone file has to be signed before it get executed and can be used. cc @HLeithner as drone maintainer :)

**Comment by laoneo** [comment]
This is mainly for testing porposes to see what it means to make the test environment green again.
The nested changes are from the other pr which fixes the system tests.

**Comment by 810** [comment]
Maybe set the min to php 7.4

7.3 is not supported, also we can update more plugins with 7.4 like codestyling.

**Pull request closed without merging**
