### PR TITLE
[4.0] Fixes styling issue

### PR DESCRIPTION
**Pull request by regularlabs**
Before
image

After
image

### CODE REVIEW

**Comment by regularlabs** [comment]
PS: This only fixes the scss file. I'll leave the compiling to css to you guys.

**Comment by richard67** [comment]
@regularlabs Compiling the css can be done on a git clone with npm e.g. with command `npm run build:css`. See here for more information: [https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en). This has to be done for testing this PR. The compiled css is not maintained in git but will be compiled again when doing a (e.g. nightly) build.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 123adb21f95f1ab6d6b29add6c6b9b85eecfbbb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29724">issues.joomla.org/tracker/joomla-cms/29724</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 123adb21f95f1ab6d6b29add6c6b9b85eecfbbb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29724">issues.joomla.org/tracker/joomla-cms/29724</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29724">issues.joomla.org/tracker/joomla-cms/29724</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
