### PR TITLE
Change style of articles list in contact

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #32417  .

### Summary of Changes
Added BS5 classes to com_contact/default_articles.php

### Testing Instructions
Create a contact page for an author and activate the display of articles in this contact.

### Actual result BEFORE applying this Pull Request
The list of articles is not styled, see screenshot in issue #32417 

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by Magnytu2** [comment]
@drmenzelit Super it works very well. But since these are links to the articles, shouldn't that be underlined as a link? And maybe have the same line spacing as the links on the right in the connection panel?

Capture d’écran 2021-02-14 à 16 57 12

**Comment by chmst** [comment]
Yes, links must be underlined. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32420">issues.joomla.org/tracker/joomla-cms/32420</a>.</sub>

**Comment by drmenzelit** [comment]
Added underlines with the last commit

**Comment by drmenzelit** [comment]
New commit with list style instead of nav

**Comment by chmst** [comment]
@Magnytu2 could you re-test please?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32420">issues.joomla.org/tracker/joomla-cms/32420</a>.</sub>

**Comment by Magnytu2** [comment]
Yes it works very well. A big thank you to you ! http://magnytudeweb.com/fnak.com/index.php/auteurs/m-j-arlidge

Capture d’écran 2021-02-14 à 21 09 44

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9d64f877fc9502bbcab8680e2d0f594f3ab0cb0c<br /><br />on Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32420">issues.joomla.org/tracker/joomla-cms/32420</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9d64f877fc9502bbcab8680e2d0f594f3ab0cb0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32420">issues.joomla.org/tracker/joomla-cms/32420</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32420">issues.joomla.org/tracker/joomla-cms/32420</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
