### PR TITLE
Clear cache with more operations

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Adds some additional cache clear calls with more operations, including:

- com_installer:
    - Install, uninstall, publish, unpublish tasks will clear the `_system`, `mod_menu`, `com_modules`, and `com_plugins` groups
- com_menus:
    - Add the `mod_menu` group for the admin side when updating menus and menu items

### Testing Instructions

With caching enabled, perform any of the above listed operations and ensure the respective cache data is cleared

### CODE REVIEW

**Comment by alikon** [comment]
this solve #15588

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 929b285697ad2fc9f87fc4da891c0d5d3be335a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15606">issues.joomla.org/tracker/joomla-cms/15606</a>.</sub>

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on 929b285697ad2fc9f87fc4da891c0d5d3be335a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15606">issues.joomla.org/tracker/joomla-cms/15606</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@rdeutz 
reconsider merging in 3.7.2 ?

**Pull request merged**
