### PR TITLE
[4.0] com_modules tooltips

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the work to remove the hasTooltip code

Code review should be enough

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f74575050721565f0031149b78c1583a379f8268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25609">issues.joomla.org/tracker/joomla-cms/25609</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f74575050721565f0031149b78c1583a379f8268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25609">issues.joomla.org/tracker/joomla-cms/25609</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
