### PR TITLE
[4.0] Fix the console errors

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #33652 .

### Summary of Changes
Bug fixing

### Testing Instructions

Click "Add module to the dashboard" on the Home Dashboard page. Look at JS Console.

### Actual result BEFORE applying this Pull Request
Console errors

### Expected result AFTER applying this Pull Request
No errors

### CODE REVIEW

**Comment by joomdonation** [comment]
Once we added the losing HTML code from this PR https://github.com/joomla/joomla-cms/pull/32657 back, this PR would become invalid.

**Comment by dgrammatiko** [comment]
@joomdonation so I added back the alert part. BTW this PR also improves/simplifies the JS

**Comment by joomdonation** [comment]
Thanks @dgrammatiko . Will test it soon.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 6cbc292edc5d70c1fc88aa55e3630773c2a5b1a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33679">issues.joomla.org/tracker/joomla-cms/33679</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 7966444eebdcc2bfaba0e2ff258b74cc7d0fdd38<br /><br />Really works now. Maybe I should have coffee, too, before testing :D<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33679">issues.joomla.org/tracker/joomla-cms/33679</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 7966444eebdcc2bfaba0e2ff258b74cc7d0fdd38<br /><br />Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33679">issues.joomla.org/tracker/joomla-cms/33679</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 7966444eebdcc2bfaba0e2ff258b74cc7d0fdd38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33679">issues.joomla.org/tracker/joomla-cms/33679</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33679">issues.joomla.org/tracker/joomla-cms/33679</a>.</sub>

**Comment by richard67** [comment]
@dgrammatiko With current 4.0-dev using Firefox on Windows I don't get any errors in browser console also without this PR applied. Can it be the errors have been already fixed with another, recently merged PR, maybe #32657 ? Or did they only occur on certain browsers?

**Comment by dgrammatiko** [comment]
@richard67 what's your ff version?

**Comment by richard67** [comment]
88.0.1 (64-Bit) on Windows 10.

**Comment by dgrammatiko** [comment]
Screenshot 2021-05-09 at 16 10 59
88.0 here and looking good. Maybe this was out of sync (I just updated it)?

**Comment by richard67** [comment]
@dgrammatiko I'd have no problem with merging this PR if it still makes sense, e.g. because improving code quality. I just like to understand that. It just seems there are no JS errors anymore to be fixed by it.

**Comment by dgrammatiko** [comment]
@richard67 oops my bad, misread what you wrote. So the problem was that there was a call to an element that didn't exist in the dom and calling `foo.classList` when foo is undefined will always throw an error. The code is bringing back the missing dom element but also introduces conditionals so it will not break if some dom element goes missing...

**Comment by richard67** [comment]
@dgrammatiko Seems I was too much driven by the PR title "Fix the console errors" and so did not get why in addition the PR adds an alert. But I get it now, I've just tested. Without the PR, the "There are no modules matching your query." is missing, so it had to be added back here.

**Comment by richard67** [comment]
Anyway code review looks good to me so far with my little js knowledge. Stuff is checked if defined before using it.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
