### PR TITLE
White Color contrast for Dropdown

### PR DESCRIPTION
**Pull request by Krshivam25**
Pull Request for Issue #35010 

### Actual result BEFORE applying this Pull Request

color2

### Expected result AFTER applying this Pull Request

color

### Documentation Changes Required

No

### CODE REVIEW

**Comment by brianteeman** [comment]
There are 440 instances of form-select-color-state

**Comment by Krshivam25** [comment]
> There are 440 instances of form-select-color-state

Yes, correct! I will check and fix this again.

**Comment by brianteeman** [comment]
Hint this is not a suitable solution

**Comment by dgrammatiko** [comment]
Use the system colours Canvas and/or CanvasText, should be the solution here. Info: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#system_colors

**Comment by coolcat-creations** [comment]
Hi @Krshivam25 thank you - actually it would be good if the green remains but the arrow would be white.

**Comment by brianteeman** [comment]
The challenge is that you cannot just change the arrow to white for the dropdown. The dropdown can have multiple states each with their own colour so if you change it to white it will be almost invisible in some states.

image
image
image

**Comment by brianteeman** [comment]
this should be closed as it is completely the wrong approach

**Pull request closed without merging**
