### PR TITLE
[5.1] Followup convert mod_messages to service provider #42735

### PR DESCRIPTION
**Pull request by heelc29**
Followup Pull Request for #42735 .

### Summary of Changes

Fix the return value in case the exception is caught

### Testing Instructions

code review

Old code -> count empty array -> 0:
https://github.com/joomla/joomla-cms/blob/be506c0a331698a2119a6baf4e23b9d339afe93a/administrator/modules/mod_messages/mod_messages.php#L27-L34

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fcb9c2b3a52f90c86f04951f2b0c518027f1a791<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42906">issues.joomla.org/tracker/joomla-cms/42906</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on fcb9c2b3a52f90c86f04951f2b0c518027f1a791<br /><br />Code review - looks fine to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42906">issues.joomla.org/tracker/joomla-cms/42906</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42906">issues.joomla.org/tracker/joomla-cms/42906</a>.</sub>

**Comment by bembelimen** [comment]
Thank you!

**Pull request merged**
