### PR TITLE
s/conyact/contact

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/conyact/contact

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c826dab93cca01ddd3ec35584186640893bdaba0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36123">issues.joomla.org/tracker/joomla-cms/36123</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c826dab93cca01ddd3ec35584186640893bdaba0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36123">issues.joomla.org/tracker/joomla-cms/36123</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36123">issues.joomla.org/tracker/joomla-cms/36123</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on c826dab93cca01ddd3ec35584186640893bdaba0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36123">issues.joomla.org/tracker/joomla-cms/36123</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
