### PR TITLE
[4.0] Prevent loading LoadingLayer twice

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Joomla has an internal LoadingLayer which appears if you change e.g. the category in an article while having custom fields.

This layer could be generated unlimited times by calling ```Joomla.loadingLayer('load');``` but this make no sense. This PR prevents multi loading of this layer

### Testing Instructions
- open the edit form of an article
- open your developer console in your browser
- type in ```Joomla.loadingLayer('load');```

### Expected result
only one instance of the layer is created

### Actual result
unlimited layers are creatable

### CODE REVIEW

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/blob/25564d884892bd52f2f9a67d57b911e8ee501e5e/media/system/js/core-uncompressed.js#L797-L814

This method will be removed

**Comment by mbabker** [comment]
1) Bug fixes really should go to staging if they apply there (hint, this one does)
2) Even if something is deprecated, until it is removed there is no reason to block optimizations/changes to the deprecated element (well, short of adding new functionality unless it is to help bridge to the replacement); if the web component is ready then it should be in use and this method removed otherwise at best it is just a note stating an intention.

**Comment by dgrammatiko** [comment]
>  there is no reason to block optimizations/changes

I wasn't meant to block but defer to the staging. I guess I need to write a bit more text on these comments...

**Comment by mbabker** [comment]
Lesson I learned the hard way, short and direct doesn't always communicate well 😉

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on df9a13fbdca015fb162990acdbc85a27bf3ad658<br /><br />I do not know what is the state of this PR for now but I get the same results when applying the patch/without applying the patch:

OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23407">issues.joomla.org/tracker/joomla-cms/23407</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on cf97adac34542546d9f352216f0015c08265d5d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23407">issues.joomla.org/tracker/joomla-cms/23407</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23407">issues.joomla.org/tracker/joomla-cms/23407</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
