### PR TITLE
[4.0] [a11y] Incorrect buttons

### PR DESCRIPTION
**Pull request by brianteeman**
Pr for #23977

This PR does TWO things

1. It changes links into buttons
2. It changes the class from sr-only to hidden
(sr-only visually hides something. hidden completely hides it)

### To test
As some javascript was changed you will need to run npm i

### CODE REVIEW

**Comment by brianteeman** [comment]
@zwiastunsw This should be what you were asking for

**Comment by zwiastunsw** [comment]
`href` attribute is not a valid attribute of the `button` tag.

**Comment by brianteeman** [comment]
@zwiastunsw I did what you asked for

> Use the `button` tag in all cases.

**Comment by zwiastunsw** [comment]
The `button` element cannot have the `href` attribute.  The action should be called e.g. using the `data-target` attribute.  Replace attributes, e.g.
from
```php
. ' href="#ModalNew' . $modalId . '"'
```
to
```php
. ' data-target="#ModalNew' . $modalId . '"'
```

**Comment by brianteeman** [comment]
@zwiastunsw changed as requested

**Comment by zwiastunsw** [comment]
In case of Clair buttons ( // Clear category button, // Clear contact button, // Clear article button, // Clear menu item button,  // Clear newsfeed button)  change:
``` 
. ' data-target="#"'
```
to 
```
. ' type="button"'
```
In this case the action is defined in the `onclick` attribute. 
The attribute `data-target` is not needed in this cases. The attribute `type="button"` is missing.

**Comment by zwiastunsw** [comment]
thx

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 0ab9b8de4616400261773ea5c3d37b878c073ec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23985">issues.joomla.org/tracker/joomla-cms/23985</a>.</sub>

**Comment by brianteeman** [comment]
sorry it took so many iterations. my brain wasnt working

**Comment by zwiastunsw** [comment]
@brianteeman 
Could you improve the links to buttons in the footers of the modal window in the same files?

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 0ab9b8de4616400261773ea5c3d37b878c073ec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23985">issues.joomla.org/tracker/joomla-cms/23985</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23985">issues.joomla.org/tracker/joomla-cms/23985</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
