### PR TITLE
[4.1] order header ini-file

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

change order (compare with other files)

### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 286d2dd206bde3b4de107a36788a7a6ff75340de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38085">issues.joomla.org/tracker/joomla-cms/38085</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 286d2dd206bde3b4de107a36788a7a6ff75340de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38085">issues.joomla.org/tracker/joomla-cms/38085</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38085">issues.joomla.org/tracker/joomla-cms/38085</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
