### PR TITLE
[4.0] ES6 please, com menu

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Refactor all scripts in com_menu

#### Known bug: 
In menus list view there is a conflict between multiselect.js and the bootstrap dropdown. Everything still works but on an open dropdown after hovering any link the link will disappear, but nevertheless still works :)

### Testing Instructions
Check 
- all aspects of the component.
- editor XTD button Menu

### CODE REVIEW

**Comment by wilsonge** [comment]
Does this known bug already exist - or is it a result of this es6 work?

**Comment by dgrammatiko** [comment]
It should have been there before, I just found this (basically I don't think anyone would have spotted this).

It's coming from the row highlighting feature of multi-select and that on existed for some time in J4.
But the fix (in the ce) will be an extremely easy `event.stopPropagation();`

**Comment by wilsonge** [comment]
Can you please create an issue for that then so it can be tracked - thanks :)

**Comment by dgrammatiko** [comment]
Ok, issue https://github.com/joomla/joomla-cms/issues/21464

**Pull request merged**
