### PR TITLE
[sendtest mail] Wrap lines on json error

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.
#### Summary of Changes

Very simple PR to wrap the lines in "Send Mail" button of global configuration when a json error occur.

Before
image

After
image
#### Testing Instructions

Code review, or:
1. Apply patch
2. Add in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/controller/application/sendtestmail.php#L42

``` php
trigger_error('My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. My very big error message. ', E_USER_WARNING);
```
1. Go to global config in the admin panel and send a test mail
2. Check if the error text is wraped

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5336cc373b58d846a9e046d9475d740d171f6a2b<br /><br />Works good. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10367">issues.joomla.org/joomla-cms/10367</a>.</sub>

**Comment by brianteeman** [comment]
I am really not a fan of having inline css in a language string<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10367">issues.joomla.org/joomla-cms/10367</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i understand, but it's already there so...

**Comment by brianteeman** [comment]
Ignore me then

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5336cc373b58d846a9e046d9475d740d171f6a2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10367">issues.joomla.org/joomla-cms/10367</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10367">issues.joomla.org/joomla-cms/10367</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot did you miss to fix the label here? :P

**Pull request merged**
