### PR TITLE
[4.2] Cache the menu instances in the app

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #37822.

### Summary of Changes
Caches the menus in the application instance.

### Testing Instructions
See instructions in #37822.

### CODE REVIEW

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 7cf7bff3f005e2296404ff621f3b6ef0610ee302<br /><br />Parameters in category blog menu items are working again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37824">issues.joomla.org/tracker/joomla-cms/37824</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7cf7bff3f005e2296404ff621f3b6ef0610ee302<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37824">issues.joomla.org/tracker/joomla-cms/37824</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37824">issues.joomla.org/tracker/joomla-cms/37824</a>.</sub>

**Comment by richard67** [comment]
Setting the Release Blocker label as inherited from the issue.

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
