### PR TITLE
The group by isn't needed anymore

### PR DESCRIPTION
**Pull request by Bakual**
Cleanup PR to remove an unneeded group by clause

### Summary of Changes
This PR removes the group by clause in FieldsModelFields. It's a leftover from https://github.com/joomla/joomla-cms/pull/13302 and not needed anymore.

### Testing Instructions
Test that no duplicate fields appear anywhere, especially when the field is assigned to multiple categories.

### Expected result
No duplicates

### Actual result
No duplicates

### Documentation Changes Required
None

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
@wilsonge if the pr #16187 get merged before this one, then the this fix is already applied on https://github.com/joomla/joomla-cms/pull/16187/files#diff-c9e1290961b6b06eeacf55ebb0d2f3acL217. Just in case you will get a merge conflict bringing this one into 4.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 32f142c30bc14b82018c6741c716d0b59b0ae542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16192">issues.joomla.org/tracker/joomla-cms/16192</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 32f142c30bc14b82018c6741c716d0b59b0ae542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16192">issues.joomla.org/tracker/joomla-cms/16192</a>.</sub>

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16192">issues.joomla.org/tracker/joomla-cms/16192</a>.</sub>

**Pull request merged**
