### PR TITLE
[4.1] PHP 8 ReturnTypeWillChange JsonapiDocument::jsonSerialize

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review 

Screenshot 2021-12-24 at 17 49 56

```
  <b>Deprecated</b>:  Return type of Joomla\CMS\Document\JsonapiDocument::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/tests/www/postgres/libraries/src/Document/JsonapiDocument.php</b> on line <b>162</b><br />
39s
240	  <br />
```

### CODE REVIEW

**Comment by alikon** [comment]
this should go in 4.0 imho

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bd10738174be593df634c45f152fd161f5f490ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36394">issues.joomla.org/tracker/joomla-cms/36394</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on bd10738174be593df634c45f152fd161f5f490ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36394">issues.joomla.org/tracker/joomla-cms/36394</a>.</sub>

**Comment by Fedik** [comment]
R
T
C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36394">issues.joomla.org/tracker/joomla-cms/36394</a>.</sub>

**Comment by Fedik** [comment]
yeah, it better for 4.0

**Comment by PhilETaylor** [comment]
Backported here https://github.com/joomla/joomla-cms/pull/36476

**Pull request closed without merging**
