### PR TITLE
[4.0] Change btn-inverse to btn-dark

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26449.

### Summary of Changes
Replace obsolete class.

### Testing Instructions
Go to Content >Articles.
Trash an article.
Go to Content > Categories.

### Expected result
btn-dark

### Actual result
66043484-2d634600-e517-11e9-913e-5dc66433bf01

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dde0e3bf243cd8c6c98e8a289e3cd141166a958e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26452">issues.joomla.org/tracker/joomla-cms/26452</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on dde0e3bf243cd8c6c98e8a289e3cd141166a958e<br /><br />

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26452">issues.joomla.org/tracker/joomla-cms/26452</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26452">issues.joomla.org/tracker/joomla-cms/26452</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
