### PR TITLE
[4.0][com_installer] - fix  Merge branch '3.10-dev' into 4.0-dev

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #32183 .

### Summary of Changes
ix  Merge branch '3.10-dev' into 4.0-dev

### Testing Instructions
Install a language (de,fr,fa-ir)

### Actual result BEFORE applying this Pull Request
`	Class 'Joomla\Component\Installer\Administrator\Model\JUri' not found `

### Expected result AFTER applying this Pull Request

language is installed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 06e2913d95d0aee4041dbeaf165837802ec70155<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32184">issues.joomla.org/tracker/joomla-cms/32184</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 06e2913d95d0aee4041dbeaf165837802ec70155<br /><br />OK!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32184">issues.joomla.org/tracker/joomla-cms/32184</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32184">issues.joomla.org/tracker/joomla-cms/32184</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
