### PR TITLE
User ban for a certain time 3.6.x

### PR DESCRIPTION
**Pull request by 4digitalworld**
User ban for a certain time.

Now in Joomla you can ban any user forever. This is no right way.

Just put some strings in Joomla code for add field, where admin can set date for unban user.

and field for "reason for user ban"

**### Example ###**

Ban user until: may 1, 2016.
Reason for ban: spam / obscene speech / etc

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
it seems you used a wrong branch to make your PR.
best closed this and make another one with only the changes you want to submit.

**Comment by sanek4life** [comment]
@andrepereiradasilva why Joomla ignore ideas and closed the threads?

people can add code to Joomla in this thread. i'm just start say about problem.

**Comment by zero-24** [comment]
You have send a pullrequest that merges the 3.6.x branch into staging. That cannot been merged. Please open a issue if you have no code for your idea. And a Pull Request with the needed changes if you have code ;)

**Comment by sanek4life** [comment]
@zero-24 thanks for an explanation

this is very bad why GitHub only on English language. english not my 1st or native language.

i'm different understand "request" like "my idea" and "issues" like my code for solve problem.

**Comment by sanek4life** [comment]
ok, i'm created this thread again here - https://github.com/joomla/joomla-cms/issues/9954

**Pull request closed without merging**
