### PR TITLE
[4.0] fix typo remember pluign

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
fix typo 

### Testing Instructions
test remember plugin work

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on a436258bd9bffe66dab1d331f1f2f10d57cb1c5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29593">issues.joomla.org/tracker/joomla-cms/29593</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on a436258bd9bffe66dab1d331f1f2f10d57cb1c5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29593">issues.joomla.org/tracker/joomla-cms/29593</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a436258bd9bffe66dab1d331f1f2f10d57cb1c5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29593">issues.joomla.org/tracker/joomla-cms/29593</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29593">issues.joomla.org/tracker/joomla-cms/29593</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
