### PR TITLE
[4.0] installer header

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue #31304

### Summary of Changes
sets correct flow for installer header

### Testing Instructions
start fresh install ( or rename configuration.php )
examine header notice logo is missing & title is offset to the right.
apply pr
run "npm ci"
examine header again in both mobile and desktop
Notice everything looks nice.

### Actual result BEFORE applying this Pull Request
image

image

### Expected result AFTER applying this Pull Request
image
image
image

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ceford** [comment]
#31304 mentioned that the question mark was expected to be white. And if the logo is going to be almost invisible, due to low colour contrast, it may as well be missing. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by N6REJ** [comment]
> #31304 mentioned that the question mark was expected to be white. And if the logo is going to be almost invisible, due to low colour contrast, it may as well be missing.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/31310](https://issues.joomla.org/tracker/joomla-cms/31310).

colors have been changed to white.  I forgot to update the images.

**Comment by ceford** [comment]
I think it still needs some work! It is coming out different on each of my browser compatibility modes (Firefox and Google Chrome on Mac). Blue on some, white on others. Too big on narrow screens. Question mark is blue.

screen shot 2020-11-05 at 16 44 54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by N6REJ** [comment]
looks like you didn't run npm ci

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 711fb889fd135653b1f74ef8ca7c106fd4f5c553<br /><br />Seems I neglected to run npm in my previous comment. It does now look fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by ceford** [comment]
My screenshot with patch applied and npm run, 380px wide viewport:
screen shot 2020-11-06 at 03 32 21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 711fb889fd135653b1f74ef8ca7c106fd4f5c553<br /><br />Tested the header with a new build. Looks good.

**Desktop**
image

**Mobile**
image


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31310">issues.joomla.org/tracker/joomla-cms/31310</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
