### PR TITLE
[4.0] Remove jQuery and boostrap.js deps for templates (redo of #23742)

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Remove jQuery and boostrap.js dependencies for a templates. 
Partial redo of #23742, that lost somewhere while waiting for #25775

### Testing Instructions

Apply patch, and make sure all still works.

### Expected result
Works

### Actual result
Works

### Documentation Changes Required

nope

### CODE REVIEW

**Comment by richard67** [comment]
@Fedik I've just tested as described and everything works. The only thing which confuses me a bit is that if I am in backend or in frontend (but in frontend only after having logged in) I can see in network analysis of browser development tools that jquery.min.js and bootstrap.bundle.min.js are still loaded. Is that expected? If yes, I'll give a good test result. Just let me know.

Update: Or does it need some special action after having applied the patch e.g. with patchtester?

**Comment by Fedik** [comment]
The jquery.min.js and bootstrap.bundle.min.js still may be loaded, because they requested by other components, layouts etc.

The main idea in the patch is that the template does not require these scripts to work, so they should not be set as dependency.
You can find some more details in  #23742

**Comment by richard67** [comment]
@Fedik Yes, I had already checked #23742 . I just have asked because I wanted to be sure all is right.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3917a77ca12935a621b129120b65184187ec3ca6<br /><br />All works as well as before after having applied the patch and watching browser console errors and php error logs while checking all.

In addition, the backend and frontend templates don't load bootstrap and jquery anymore when not being logged in.

Only after login when some component requires that, they are loaded.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27473">issues.joomla.org/tracker/joomla-cms/27473</a>.</sub>

**Comment by richard67** [comment]
And to make it complete: Drone failure as usual seems not to be related to this PR.

**Comment by SharkyKZ** [comment]
This breaks menu in frontend. See similar PR https://github.com/joomla/joomla-cms/pull/23744.

**Comment by richard67** [comment]
@SharkyKZ Am just testing again but can't see what's broken. Could you provide some details?

**Comment by SharkyKZ** [comment]
The menu toggle button on small screens doesn't work:

Screen Shot 2020-01-11 at 13 39 03

**Comment by Fedik** [comment]
@SharkyKZ it seems on mobile version, I did not noticed,
Thanks, I will check

**Comment by richard67** [comment]
Ouch, didn't notice that.

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27473">issues.joomla.org/tracker/joomla-cms/27473</a>.</sub>

**Comment by Fedik** [comment]
Okay I have add bootstrap.js back to cassiopeia, it seems the mobile menu use "navbar-toggler" feature.
Should work now.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d7df7b40b674a93e7165e0b1db5e99815dbc3ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27473">issues.joomla.org/tracker/joomla-cms/27473</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on d7df7b40b674a93e7165e0b1db5e99815dbc3ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27473">issues.joomla.org/tracker/joomla-cms/27473</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27473">issues.joomla.org/tracker/joomla-cms/27473</a>.</sub>

**Comment by dgrammatiko** [comment]
Thank you @Fedik 🙌

**Comment by wilsonge** [comment]
Thanks!

**Comment by Quy** [comment]
It is no longer possible to tab between Set 2, Set 1, and Set 0 in the TinyMCE plugin.

**Comment by Fedik** [comment]
need to load bootstrap in that specific layout

**Comment by dgrammatiko** [comment]
Or use the custom elements tabs as the rest of the backend?

**Comment by Fedik** [comment]
when it will stop mess with DOM :wink:

**Comment by dgrammatiko** [comment]
When will it adhere to the standards for CE? (I have no answer for both questions, it seems both issues are due to my bad implementation)

**Comment by richard67** [comment]
> It is no longer possible to tab between Set 2, Set 1, and Set 0 in the TinyMCE plugin.

@Quy Seems I've missed that when testing, shame on me.

Will someone make a new issue for that, or even a new PR?

**Comment by Fedik** [comment]
@richard67 I will do PR, but some time later, maybe on the weekend

**Comment by Fedik** [comment]
@richard67 @Quy please test this one #27560

**Pull request merged**
