### PR TITLE
Inefficient jQuery selectors

### PR DESCRIPTION
**Pull request by demis-palma**
[Cached](https://24ways.org/2011/your-jquery-now-with-less-suck/) some repeated and highly time-consuming jQuery selectors.
Using less CPU power, reduces the world carbon dioxide emissions.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
wow an eco friendly PR ;)

**Comment by andrepereiradasilva** [comment]
demis, how do we test this?

**Comment by demis-palma** [comment]
Thanks for asking @andrepereiradasilva, but I can't figure out a simple test for that.

**Comment by mbabker** [comment]
That's related to the sticky subheader.  It should still stick on long pages when scrolled.

**Comment by demis-palma** [comment]
Thanks @mbabker. Personally, I followed the code with my JavaScript debugger and I checked that the program flux behaves the same, but I can't figure out other kind of tests.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9ac693882038c42a9eb9ea928ae1d576f61df816<br /><br />The menu bar and the buttons toolbar are still sticky when scrolling down.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 9ac693882038c42a9eb9ea928ae1d576f61df816<br /><br />Apply the patch
Clear the browser cache
Enable Joomla debug
Go to the Language manager and you will see the debug box is shrunk to a small box on the right hand side<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by brianteeman** [comment]
Same with the template manager 

screen shot 2016-02-28 at 12 46 02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on 9ac693882038c42a9eb9ea928ae1d576f61df816<br /><br />I can reproduce @brianteeman test, so changed to Tested unsuccessfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by demis-palma** [comment]
This is the reason I love the rule of the double human test.
Well, at the moment the code clean-up can't be applied to $('.body'), but only to $('.subhead') and $('nav.navbar')
I've added a second commit to this PR.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on aa1cf08fb8e288c00f087d5cb4919b692c1bec89<br /><br />Tested again in multiple browsers. Same problem as before<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman successfully or unsuccessfully?

**Comment by brianteeman** [comment]
Oops I hit the wrong button - i have edited it now to show a failure<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by roland-d** [comment]
@demis-palma Can you have a look at the PR since there are unsuccessful tests?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9243">issues.joomla.org/joomla-cms/9243</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@demis-palma should this PR be tested?

**Comment by jeckodevelopment** [comment]
and also conflicting files!

**Comment by mbabker** [comment]
Closing PR as abandoned since there have been no updates in over a year.

**Pull request closed without merging**
