### PR TITLE
[4.0] Fix ordering of workflows, transitions and stages

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Fix te broken ordering of workflows/transitions/stages

### Testing Instructions
1. Create more than one workflows, transitions and/or stages in a workflow (Articles => Workflow)
2. Try to reorder

### Expected result
Reorder works

### Actual result
Reorder does not work

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on aff43849d14372eda6e5fe2bc4b5b2c5c82f80f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22318">issues.joomla.org/tracker/joomla-cms/22318</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on aff43849d14372eda6e5fe2bc4b5b2c5c82f80f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22318">issues.joomla.org/tracker/joomla-cms/22318</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22318">issues.joomla.org/tracker/joomla-cms/22318</a>.</sub>

**Comment by wilsonge** [comment]
thanks!

**Pull request merged**
