### PR TITLE
[fix] When installing Joomla! and mail sending fails you are not getting to the next screen.

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #11891 .
### Summary of Changes

The `libraries/legacy` tree isn't being included in the install app because its code was rewritten to not be dependent on it. Most likely this has been an issue since the PR that removed the "if JError exists use it for error handling else throw an Exception" logic from JMail. The error handling is trying to call a non-existing class.

Change installation/application/framework.php to require import.legacy.php instead of import.php.

Thanks @mbabker https://github.com/joomla/joomla-cms/issues/11891#issuecomment-244435068
### Testing Instructions
- Download this branch: https://github.com/zero-24/joomla-cms/archive/install_mail.zip
- upload it to the server
- add `$return = false;` here: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L133
- try to install joomla on the pre final step make sure you enable mail sending of the configuration.
##### Expected result

Installation succes should be independant of the setting send Email Configuration option.
##### Actual result

No matter which of the install-options you choose you will be getting this same Finalisation-screen until you set the send Email Configurations to No.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by slibbe** [comment]
I have tested this item :red_circle: unsuccessfully on f7801b04e62f5302cb71eae6c55aa0e54e879fbf<br /><br />With the proposed "add $return = false;" in line 133 of libraries/joomla/mail/mail.php and having set send Email Configuration to yes, the only way to get past the Finalisation screen is turning on the mail-function on the server.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11895">issues.joomla.org/joomla-cms/11895</a>.</sub>

**Comment by slibbe** [comment]
However, when looking at the changed files in the PR, I think that either the test instructions are not well written or I didn't get it. 
I will test another time (with mail function disabled and changed files.

**Comment by slibbe** [comment]
Well, I have no idea how this fits in this PR testing infrastructure.

However, when making proposed changed in installation/application/framework.php and installation/controller/install/email.php and not adding $return = false; to libraries/joomla/mail/mail.php on line 133 , also making sure that the mail-function is disabled on the server, then it works as expected. 
So a succes I would say.

**Comment by zero-24** [comment]
Yes sorry for the confusing ;) you need to install this branch (with the changed file). The $return = false just make sure you got the error you can also disable the mail function.

I can rewrite the testinstructions if im back to me PC ;)

**Comment by zero-24** [comment]
@slibbe i have updated the test instructuion can you retest and mark as successful it it is successfull? Thanks.

**Comment by slibbe** [comment]
I have tested this item :white_check_mark: successfully on f7801b04e62f5302cb71eae6c55aa0e54e879fbf<br /><br />Now works as expected.


In case the mail cannot be sent, no warning is shown. I think it's always been that way even though a warning in the backend would be nice.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11895">issues.joomla.org/joomla-cms/11895</a>.</sub>

**Comment by zero-24** [comment]
>In case the mail cannot be sent, no warning is shown. I think it's always been that way even though a warning in the backend would be nice.

I'm not sure i understand you? There is a button to test mail sending in the backend?

**Comment by mbabker** [comment]
There's no message saying the mail failed to send if JMail returns a
Boolean value because the JError default handling ignores errors and it's
not throwing an Exception to trigger the catch block in the code sending
the mail.  So you'd need an extra check if the result of JMail::Send() !==
true.

**Comment by zero-24** [comment]
@mbabker do you mean something like https://github.com/joomla/joomla-cms/pull/11895/commits/3bc5c622df023dd1532d2f4924626ad63179727c

**Comment by zero-24** [comment]
If you don't want to fack the code you can also try to install: https://github.com/zero-24/joomla-cms/archive/install_mail.zip without any changes. If that works we are good to go here as we have another  successful test for the other aspect allready. Thanks!

**Comment by zero-24** [comment]
Would be great to get a seccond test here :+1: As this fixes a bug and we just need to make sure a normal install still works..

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a3228a5974ce528dc550947c0b06a084f8a0e261<br /><br />1. Used latest staging and applied patch with patchtester
2. Deleted configuration.php
3. Added `$return = false;` here: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L133
4. tried to install joomla on the pre final step make sure you enable mail sending of the configuration. 

Installation went fine. So, works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11895">issues.joomla.org/tracker/joomla-cms/11895</a>.</sub>

**Comment by zero-24** [comment]
RTC cc @rdeutz <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11895">issues.joomla.org/tracker/joomla-cms/11895</a>.</sub>

**Comment by zero-24** [comment]
Thanks @andrepereiradasilva and @slibbe

**Comment by zero-24** [comment]
:heart:

**Pull request merged**
