### PR TITLE
[4.3] com_finder RTL

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the two RTL issues in com_finder when displaying date filters in the front end of the site

One element has been changed to a logical operator and one has been removed.

To test either install a prebuild or `npm run build:css`

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4994eed94d5d7b39331db89ca81cbdccee83be6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39292">issues.joomla.org/tracker/joomla-cms/39292</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4994eed94d5d7b39331db89ca81cbdccee83be6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39292">issues.joomla.org/tracker/joomla-cms/39292</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39292">issues.joomla.org/tracker/joomla-cms/39292</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brian @brianteeman for the fix!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
