### PR TITLE
[4.2] Replace deprecated getDbo() with getDatabase()

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This small PR replace the deprecated `getDbo()` call by `getDatabase()` method in our model classes in MVC layer.

### Testing Instructions
1. Code review should be enough
2. Or install 4.2, apply patch. Go to articles list, try to edit and save an article, make sure it is still working.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f7b401517d1357b927f4914bf58ac635da7fd552<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37930">issues.joomla.org/tracker/joomla-cms/37930</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f7b401517d1357b927f4914bf58ac635da7fd552<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37930">issues.joomla.org/tracker/joomla-cms/37930</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37930">issues.joomla.org/tracker/joomla-cms/37930</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
