### PR TITLE
:uk: typo fix "Colour" instead of "Color"

### PR DESCRIPTION
**Pull request by MATsxm**
#### What for?

Simple typo fix for en-GB file 
#### How to test

On code review

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 4b7cbb0f3d60525fa98c5c0c06298e49ec680f8c<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10733">issues.joomla.org/joomla-cms/10733</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4b7cbb0f3d60525fa98c5c0c06298e49ec680f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10733">issues.joomla.org/joomla-cms/10733</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10733">issues.joomla.org/joomla-cms/10733</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please so your job here :)

**Pull request merged**
