### PR TITLE
[4.0] Spell out abbreviation CSP

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Spell out abbreviation CSP, alt least in the system view. 
Many users will not know what the abbreivation means.  
csp

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
approve the language changes

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 363285d0527edf88cf42bbe4503f6084fefdb762<br /><br />Thanks - I have meant to do thi so many times and keep forgeting<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21874">issues.joomla.org/tracker/joomla-cms/21874</a>.</sub>

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21874">issues.joomla.org/tracker/joomla-cms/21874</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 363285d0527edf88cf42bbe4503f6084fefdb762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21874">issues.joomla.org/tracker/joomla-cms/21874</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks.

**Pull request merged**
