### PR TITLE
Update pagebreak plugin description

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to update the very outdated text suggesting that the page break button is normally found under the article text area.

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on f3f76bc8cb5979a21abb947ab4e74e4466c05eda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19653">issues.joomla.org/tracker/joomla-cms/19653</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f3f76bc8cb5979a21abb947ab4e74e4466c05eda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19653">issues.joomla.org/tracker/joomla-cms/19653</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19653">issues.joomla.org/tracker/joomla-cms/19653</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Comment by infograf768** [comment]
This PR deals only with WYSISWYG editors. It does not consider Codemirror where the buttons are at the bottom of the editor...

**Comment by brianteeman** [comment]
That is why it says
> normally found in the WYSIWYG editor toolbar

instead of
> normally found beneath the text panel

**Comment by infograf768** [comment]
it should have been 'OR' imho, but who cares...

**Comment by mbabker** [comment]
In the case of a text area, or CodeMirror, the "WYSIWYG editor toolbar" would for all intents and purposes be that row of buttons below the input field.  So it's fine.

**Pull request merged**
