### PR TITLE
Use $ismoo instend of calling jinput

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #13306

### Summary of Changes

- Use $ismoo instend of calling jinput
- a bit CS

### Testing Instructions

1. Open an administrator form that has a User form field on it (i.e. User Notes)
2. Type a user name or keyword into the search box and submit
3. Click one of the resulting users; the dialog is dismissed

### Expected result

The user selected in the pop-up should populate the user form field.

### Actual result

In 3.6.5 it is broken as the $ismoo value is missing.
In 3.7-dev it is working but don't uses the $ismoo it gets the value from the jinput object

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
> 3. Click one of the resulting users; the dialog is dismissed

Got linked `Subject` but no linked User.
bildschirmfoto 2017-02-13 um 10 51 39

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on abccdaf8c45ba2c5ccd99e485294bd65699857a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14047">issues.joomla.org/tracker/joomla-cms/14047</a>.</sub>

**Comment by joomdonation** [comment]
Since you made this change, could you please this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/users/tmpl/modal.php#L23 to
```php
$input           = JFactory::getApplication()->input;
```
and remove the line above https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/users/tmpl/modal.php#L22

(The $app variable is used one time only, thus it should be removed)

**Comment by zero-24** [comment]
Done thanks @joomdonation

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 29dab6426d81742ffd718a0393bedc0fa641fea1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14047">issues.joomla.org/tracker/joomla-cms/14047</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 29dab6426d81742ffd718a0393bedc0fa641fea1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14047">issues.joomla.org/tracker/joomla-cms/14047</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Pull request merged**
