### PR TITLE
[com_templates] Add prefix to class name in menu assignment

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #24605.

### Summary of Changes
Add prefix to class name to prevent conflicting with existing classes.

### Testing Instructions
Create a new Menu named Hidden and set the menutype to "hidden".
Add a menu item to that menu.
Open a template style and check the Menu Assignment tab.

### Expected result
A visible checkbox to associate the template style with the created menu item.

### Actual result
No checkbox visible. Reason for that is the menu alias will be added to the Input tag as a class - without any prefix. So it becomes input[type=checkbox].hidden which is a class used by bootstrap to hide stuff.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 06acd665539905b63777aedf8611f42c00871115<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25454">issues.joomla.org/tracker/joomla-cms/25454</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 06acd665539905b63777aedf8611f42c00871115<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25454">issues.joomla.org/tracker/joomla-cms/25454</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25454">issues.joomla.org/tracker/joomla-cms/25454</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
