### PR TITLE
[5.0][Events] Custom fields event classes

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Event classes for Custom fields.

Affected events:

- [x] onCustomFieldsGetTypes
- [x] onCustomFieldsPrepareDom
- [x] onCustomFieldsBeforePrepareField
- [x] onCustomFieldsPrepareField
- [x] onCustomFieldsAfterPrepareField

### Testing Instructions
Use custom fields

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/Plugin/Events#Fields
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
Merging this as with code review and based on the other similar PRs, before beta1 to get enough feedback for final release.

Additionally we need a deprecation warning for plugins which extend the `FieldsPlugin` without the subscriber interface.

Suggestion, create a constructor function which test if $this is instance of SubscriberInterface.

**Comment by Fedik** [comment]
This is unnecessary, whole legacy listeners code should go, not only for FieldsPlugin.

**Comment by HLeithner** [comment]
yes but that means we have to call `$y = $event->getY()` anyway when we don't have references anymore. In this case maybe it make sense to not have (pseudo)references at the caller location at all and always run `$x = $event->getX()` for every reference/proxyArray we use now?

**Comment by Fedik** [comment]
You comented in wrong PR :)

**Pull request merged**
