### PR TITLE
Article - Global Options: Different Tooltips on 3 Datetypes

### PR DESCRIPTION
**Pull request by pau1a**
Pull Request for Issue #25343 .

### Summary of Changes

Language string adjustments to provide consistency of user experience

### Testing Instructions

Visit "Article - Global Options", view tooltips

### Expected result

Consistent tooltips over "Show Publish Date","Show Modify Date","Show Create Date"

### Actual result

As above

### Documentation Changes Required

None

[en-GB.ini.zip](https://github.com/joomla/joomla-cms/files/3390245/en-GB.ini.zip)

### CODE REVIEW

**Comment by Quy** [comment]
There are unrelated changes from other PRs and no changes for this PR.

**Comment by brianteeman** [comment]
This pull request does a lot more than in the description

**Comment by pau1a** [comment]
Yes Im not sure how the other commits got included. My intention was to provide a simple language file update but Im still working out how to do this. Would appreciate if someone with the necessary privileges could remove the accidentally included commits please.

**Comment by Quy** [comment]
Replaced by PR #25556<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25554">issues.joomla.org/tracker/joomla-cms/25554</a>.</sub>

**Pull request closed without merging**
