### PR TITLE
[5.3] Remove the not needed getPathway in the SiteApplication class

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #41653 .

### Summary of Changes

Removed the function, the parent class is doing the same and the params are not used.

### Testing Instructions

Check a site with a pathway/breadcrumbs applying the patch should change nothing 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 107e3e11d407cd45fbb2eeb4c9c9828ea29edddf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43385">issues.joomla.org/tracker/joomla-cms/43385</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.3-dev.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 107e3e11d407cd45fbb2eeb4c9c9828ea29edddf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43385">issues.joomla.org/tracker/joomla-cms/43385</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43385">issues.joomla.org/tracker/joomla-cms/43385</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
