### PR TITLE
[4.0] Sample Data module

### PR DESCRIPTION
**Pull request by brianteeman**
The plugins were set to use the broadcast icon but in the version of fontawesome being used in j4 (currently) instead of fa-broadcast it needs to be fa-wifi

See line 1627
```
.fa-wifi:before, .icon-broadcast:before, .icon-connection:before, .icon-wifi:before {
  content: ""; }
```

### before
chrome_2018-07-02_23-05-39

### after
chrome_2018-07-02_23-05-01

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bffe035759efcc109076fd6eedb55f7bcd1762a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20957">issues.joomla.org/tracker/joomla-cms/20957</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bffe035759efcc109076fd6eedb55f7bcd1762a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20957">issues.joomla.org/tracker/joomla-cms/20957</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
