### PR TITLE
Don’t set page number

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #16858.

### Summary of Changes
We don't need to set the page number

### Testing Instructions

- install 3.7.3-dev
- set up a `news flash` module to the category `Joomla!` (using sample data)

### Expected Result

No errors.

### Actual result:

image

### CODE REVIEW

**Comment by laoneo** [comment]
Should you not send at least 0 as page attribute?

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 4ebe5a611fe7fc7d6de7b52967dfc1a5f76b6967<br /><br />works good here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16866">issues.joomla.org/tracker/joomla-cms/16866</a>.</sub>

**Comment by zero-24** [comment]
> Should you not send at least 0 as page attribute?

@laoneo why do you want to set it if it is the default value?

**Comment by mbabker** [comment]
RocketTheme plugins commonly make the `$page` parameter a required argument which causes all sorts of excessive bug reports when you have an extension which does not include the parameter in the event arguments.

**Comment by zero-24** [comment]
> RocketTheme plugins commonly make the $page parameter a required argument which causes all sorts of excessive bug reports when you have an extension which does not include the parameter in the event arguments.

I'm not question anything anymore... Just "fixed" in the PR.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3cca1d0d93a2744c1ec2d171ed4de3da0da26396<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16866">issues.joomla.org/tracker/joomla-cms/16866</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@zero-24 can you please retest?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 3cca1d0d93a2744c1ec2d171ed4de3da0da26396<br /><br />@zero-24 its also documented as limitstart here https://docs.joomla.org/Plugin/Events/Content, so I guess it is not bad to send all of them<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16866">issues.joomla.org/tracker/joomla-cms/16866</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
Thanks.

**Pull request merged**
