### PR TITLE
[4.0] Remove Deprecated Attributes

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue #33467.

### Summary of Changes
Remove Attributes `cellspacing` and `cellpading`

### Testing Instructions
Code Review

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 20c10f0a705877b2d3097b3bd3ffc06e794245b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33469">issues.joomla.org/tracker/joomla-cms/33469</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 20c10f0a705877b2d3097b3bd3ffc06e794245b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33469">issues.joomla.org/tracker/joomla-cms/33469</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33469">issues.joomla.org/tracker/joomla-cms/33469</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by rjharishabh** [comment]
Thanks

**Comment by richard67** [comment]
If you now ask if that has been the fastest merged PR ever: I think no, I remember there was a faster one a few years ago 😉

**Comment by rjharishabh** [comment]
Thanks @richard67

**Pull request merged**
