### PR TITLE
Correct authentication name

### PR DESCRIPTION
**Pull request by Valdnet**
Correction of the authentication name.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thank you for your pull request. We maintain a style guide for the english used in the user interface and messages which is found at https://developer.joomla.org/en-gb-user-interface-text-guidelines/introduction.html

For Multi-factor we have decided
> Multi-factor must always be a single hyphenated word and only the complete word should be capitalised.

**Comment by Kostelano** [comment]
@Valdnet Is there a reason why the fix is only in the 1st file? At least there is still a frontend, there are "obsolete" Two-Factor files.

**Comment by Valdnet** [comment]
@Kostelano Changes also made to the files for the administrator.

**Comment by Valdnet** [comment]
@brianteeman Can you approve and merge this PR?

**Comment by brianteeman** [comment]
I would if I could but I dont have the acccessto do that

**Comment by Valdnet** [comment]
> I would if I could but I dont have the acccessto do that

I thought you had such access :open_mouth:. Or do you know who can approve and merge? I am not familiar with this repository.

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 5b6dab6532328def67347ee65b8e6a3aba5a639f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38598">issues.joomla.org/tracker/joomla-cms/38598</a>.</sub>

**Review by tecpromotion — APPROVED** [review]
Thanks @Valdnet for your PR

**Comment by Valdnet** [comment]
Please merge. Thanks.

**Comment by wojsmol** [comment]
@Valdnet This PR requires one more successful tests marked in the issue tracker before it can be set as RTC and then merged.

**Comment by Valdnet** [comment]
@wojsmol Thanks for the information 😉.

**Pull request closed without merging**
