### PR TITLE
[4.0] Namespace com_banners

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
As title says, this PR convert com_banners and it's module to Namespace MVC.

### Testing Instructions
1. Install Joomla 4 (with sample data for easier testing)
2. Apply patch
3. Access to com_banners from backend of the site, try to add/edit/publish/unpublish, delete Banners, Clients, make sure it is working as expected.
4. Edit the **Support Joomla!** banner, look at **Banner Details** tab, set **Track Impressions** and **Track Clicks** parameter to Yes (so that you can test **Tracks** management in later step
5. Access to frontend, click on **Banner** link in **All Modules** module.  There will be a banner displayed, click on it, see that it works
6. Access to com_banners from backend again, try to access to **Tracks** link, see list of Tracks. Click on Export Button and make sure the tracks data is downloaded

Overall, the test is just to make sure it works as how it was (non-namespaced version)

### CODE REVIEW

**Comment by joomdonation** [comment]
If you review code, please ignore the ugly code in the banner module which register component autoloader. Once the autoload PR from  @laoneo merged, we can remove that ugly code

**Comment by rjcf18** [comment]
I have tested this item :red_circle: unsuccessfully on f3d97d695248f8d54e372e7fcc609ade9350f367<br /><br />In banners found no problems adding, deleting, editing, publishing and unpublishing items, however on clients found problems adding or editing a client (no problems publishing/unpublishing, archiving and deleting clients):
deepinscreenshot20170425021850

Also found another problem unpinning banners:
deepinscreenshot20170425021620
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15481">issues.joomla.org/tracker/joomla-cms/15481</a>.</sub>

**Comment by joomdonation** [comment]
Many thanks for testing @rjcf18. There were some typos and I fxied it. Please help testing it again

**Comment by joomdonation** [comment]
Regarding the Tracks, according to your screenshot, it is downloaded properly :)

**Comment by rjcf18** [comment]
No problem. Let me test it again ;)

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on 8e3c24cebed3c9c3635e004434978305d763dd9d<br /><br />Tested everything in banners and clients, no longer any problems, banner on frontend working, tracks exporting also working well. Everything seems to be fixed now.

deepinscreenshot20170425040035

deepinscreenshot20170425040413

deepinscreenshot20170425040644


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15481">issues.joomla.org/tracker/joomla-cms/15481</a>.</sub>

**Comment by joomdonation** [comment]
Many thanks again for testing Ricardo.

**Comment by rjcf18** [comment]
No problem :)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 8e3c24cebed3c9c3635e004434978305d763dd9d<br /><br />> 5. Access to frontend, click on Banner link in All Modules module. There will be a banner displayed, click on it, see that it works

At this Step got: ` Fatal error: Class 'Joomla\Component\Banners\Administrator\Helper\BannersHelper' not found in /Applications/MAMP/htdocs/J4/administrator/components/com_banners/helpers/banners.php on line 17`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15481">issues.joomla.org/tracker/joomla-cms/15481</a>.</sub>

**Comment by joomdonation** [comment]
Could you please let me know exactly on what step you get this error? Right after you click on **Banner** link in **All Modules** or click on the banner ?

**Comment by franz-wohlkoenig** [comment]
Right after click on "Banner"-Link in "All Modules".

**Comment by joomdonation** [comment]
Strange. It works well here for me. Could you please zip the folder modules\mod_banners in your install and attach it here so that I can take a look? I am thinking that there might be some old files left and it causes the issue

Or if it is possible, please download a fresh copy of my branch https://github.com/joomdonation/joomla-cms/tree/namespace_com_banners , install and test it (just need to start from step #5 to save time)

Thanks for help testing

**Comment by franz-wohlkoenig** [comment]
[mod_banners.zip](https://github.com/joomla/joomla-cms/files/954580/mod_banners.zip)

**Comment by joomdonation** [comment]
The module you sent me is still using the old code, that explains why it doesn't work for you. See the the code of new file https://github.com/joomdonation/joomla-cms/blob/namespace_com_banners/modules/mod_banners/mod_banners.php

Maybe patchtester doesn't work well. Please install a copy of my branch https://github.com/joomdonation/joomla-cms/tree/namespace_com_banners and help testing it again

**Comment by franz-wohlkoenig** [comment]
Installing your branch got:
bildschirmfoto 2017-04-25 um 11 50 14

**Comment by rjcf18** [comment]
I didn't have that problem. It may very likely be a patchtester problem, I used git and cloned this PR, did a fresh installation and found no problems, everything works fine.

**Comment by joomdonation** [comment]
@franz-wohlkoenig Please give it a final try

1. Option 1 : Replace the modules/mod_banners folder on your install with the module I attached here

2. Or download my branch again https://github.com/joomdonation/joomla-cms/archive/namespace_com_banners.zip (I just synchronized with 4.0-dev brach), install and test it

**Comment by joomdonation** [comment]
Hmm, for some reason, the zip module could not be uploaded. So I think the easiest way would be download my branch https://github.com/joomdonation/joomla-cms/archive/namespace_com_banners.zip , install and test it

**Comment by franz-wohlkoenig** [comment]
Will test on your branch.

**Comment by joomdonation** [comment]
Thanks. I downloaded, tested and make sure it is installed properly :)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d22ae78223d5b54ec5c0e3b4ac2a1a8c2261df75<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15481">issues.joomla.org/tracker/joomla-cms/15481</a>.</sub>

**Comment by joomdonation** [comment]
Thanks. Please mark this as ready to commit as we now have two successful tests. Look like the test result from Ricardo was reset for some reasons

@wilsonge This can be merged now. I will take care of necessary changes once autoload PR is merged (just need to remove some lines of code from the module)

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rjcf18** [comment]
My test results were for a previous commit thats why it looks like it was reset :)

**Comment by joomdonation** [comment]
Thanks all :)

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
