### PR TITLE
[4.0] Bootstrap Accordion fixes

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/27257.

### Summary of Changes

Fixes notices when using Bootstrap Accordion on PHP 7.4.
Also corrects active slide class.

### Testing Instructions

Edit a module in frontend or go create a menu item.

### Expected result

No notices.

### Actual result

>Notice: Trying to access array offset on value of type bool

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b2d122158adc60a7210e8352c41de58ee0e3dc7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27274">issues.joomla.org/tracker/joomla-cms/27274</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b2d122158adc60a7210e8352c41de58ee0e3dc7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27274">issues.joomla.org/tracker/joomla-cms/27274</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27274">issues.joomla.org/tracker/joomla-cms/27274</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
