### PR TITLE
[4.0] Removal of tooltips - PART 1

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR is the start of the removal of tooltips. It remove all `JHtml::_('bootstrap.tooltip');` calls from core

@brianteeman @dgt41

### CODE REVIEW

**Comment by brianteeman** [comment]
I am a bit confused as the tooltips are still active after this PR

**Comment by C-Lodder** [comment]
Removed last instance and sorted things with @brianteeman

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 38fa3c883a022f1d5d467dea23416f9fd830776a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17050">issues.joomla.org/tracker/joomla-cms/17050</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 38fa3c883a022f1d5d467dea23416f9fd830776a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17050">issues.joomla.org/tracker/joomla-cms/17050</a>.</sub>

**Comment by dgrammatiko** [comment]
RTC @wilsonge <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17050">issues.joomla.org/tracker/joomla-cms/17050</a>.</sub>

**Pull request merged**
