### PR TITLE
[4.0] deprecated

### PR DESCRIPTION
**Pull request by brianteeman**
small change so that version to be deprecated can be found more easily - same as all other deprecated tags

code review

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 590b5358053525c2c6f26c294e601dd93b993677<br /><br />Tested successfully in Beta8-dev of 3 April.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32975">issues.joomla.org/tracker/joomla-cms/32975</a>.</sub>

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 590b5358053525c2c6f26c294e601dd93b993677<br /><br />Test successful as it's purely a comment change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32975">issues.joomla.org/tracker/joomla-cms/32975</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 590b5358053525c2c6f26c294e601dd93b993677<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32975">issues.joomla.org/tracker/joomla-cms/32975</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
