### PR TITLE
[4.0] Associations warning translateable

### PR DESCRIPTION
**Pull request by brianteeman**
Create a multilingual site
Change a menu item from language all to any other language
You will see an alert as below with a non translated warning

Apply the pr and try again

### Before
image

### After
image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2c27010efc263989b57de263a04f2352e0cd7f2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28650">issues.joomla.org/tracker/joomla-cms/28650</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2c27010efc263989b57de263a04f2352e0cd7f2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28650">issues.joomla.org/tracker/joomla-cms/28650</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28650">issues.joomla.org/tracker/joomla-cms/28650</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
