### PR TITLE
[3.x] Update TinyMCE

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
This PR updates tinymce to version 4.5.12 - this is the highest version we can include in Joomla 3 due to browser support.

It also fixes numerous security issues.

Changelog:

  Fixed so links with xlink:href attributes are filtered correctly to prevent XSS. #TINY-1626
  Fixed the `selection.setContent()` API not running parser filters #TINY-4002
  Fixed the `visualchars` plugin converting HTML-like text to DOM elements in certain cases #TINY-4507
  Fixed HTML comments incorrectly being parsed in certain cases #TINY-4511
  Fixed a security issue related to CDATA sanitization during parsing #TINY-4669
  Fixed content in an iframe element parsing as dom elements instead of text content #TINY-5943

### CODE REVIEW

**Comment by brianteeman** [comment]
is the admin-item-edit js supposed to be here?

**Comment by SniperSister** [comment]
@brianteeman whoops, good catch, fixed

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on d98c59e9cccfb48d40e66080da21d1a40798808f<br /><br />Looks good to me, thanks @SniperSister <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30329">issues.joomla.org/tracker/joomla-cms/30329</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d98c59e9cccfb48d40e66080da21d1a40798808f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30329">issues.joomla.org/tracker/joomla-cms/30329</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30329">issues.joomla.org/tracker/joomla-cms/30329</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
