### PR TITLE
[4.2] Replace $this->_db usages in components models

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR `$this->_db` in all components models by database object returned by getDatabase() method. This is not a find and replace PR, so please do careful code review before merging.

### Testing Instructions
1. Use Joomla 4.2
2. Apply patch
3. Access to random pages from both frontend and backend, make sure nothing is broken
4. Please at least one careful code review.

### CODE REVIEW

**Comment by rdeutz** [comment]
I have tested this item :white_check_mark: successfully on 61d5341fc54b198f5b606316789f292b01628fb6<br /><br />Looks good to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38025">issues.joomla.org/tracker/joomla-cms/38025</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 61d5341fc54b198f5b606316789f292b01628fb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38025">issues.joomla.org/tracker/joomla-cms/38025</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38025">issues.joomla.org/tracker/joomla-cms/38025</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
