### PR TITLE
[com_templates] Admin to Administrator

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Very simple PR just to replace "Admin" for "Administrator" in com_templates title (when administrator client is selected).

All other list views (ex: com_modules, com_cache, com_languages) use "Administrator" for this, so, for consistency.

Before

image

After
image
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on d0b924b0678ba7bd2bfedaaa8fb6e6061b567e4f<br /><br />On Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11179">issues.joomla.org/joomla-cms/11179</a>.</sub>

**Comment by brianteeman** [comment]
Good spot

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d0b924b0678ba7bd2bfedaaa8fb6e6061b567e4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11179">issues.joomla.org/joomla-cms/11179</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on d0b924b0678ba7bd2bfedaaa8fb6e6061b567e4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11179">issues.joomla.org/joomla-cms/11179</a>.</sub>

**Comment by DhavalTailored** [comment]
I have tested this item :white_check_mark: successfully on d0b924b0678ba7bd2bfedaaa8fb6e6061b567e4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11179">issues.joomla.org/joomla-cms/11179</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11179">issues.joomla.org/joomla-cms/11179</a>.</sub>

**Pull request merged**
