### PR TITLE
Let's the frontend module helper files following our codestyle :smile:

### PR DESCRIPTION
**Pull request by zero-24**
Let's the frontend module helper files following our codestyle :smile:
### What this PR do
- Basic doc block fixes.
- basic codestyle

### CODE REVIEW

**Comment by nueckman** [comment]
Looks good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5758">issues.joomla.org/joomla-cms/5758</a>.</sub>

**Comment by continga** [comment]
Code looks good.

**Comment by zero-24** [comment]
Thanks for testing. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5758">issues.joomla.org/joomla-cms/5758</a>.</sub>

**Comment by phproberto** [comment]
@zero-24 there is a conflict now because some mod_languages improvements were done. Can you rebase this PR and fix conflicts? Thanks

**Pull request closed without merging**
