### PR TITLE
[4.1] Smart Search: Fix missing taxonomy language string

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
Smart Search tries to create its own language keys for the indexed taxonomies. Unfortunately, when there is no language string for the key, we get a "Search by PLG_FINDER_QUERY_FILTER_BRANCH_S_SOMETHING" in the search form in the frontend. This PR checks if a translation for the language key exists and if there is none (and debug is not enabled) it will instead display the taxonomy title instead.

### Testing Instructions
1. If you don't have the effect already, we need to add a fake taxonomy. Go to plugins/finder/content/content.php and add `$item->addTaxonomy('Test', 'Strange');` after line 342.
2. Reindex your site with the button in the backend.
3. Go to the advanced search form in the frontend and see a dropdown with the label "Search by PLG_FINDER_QUERY_FILTER_BRANCH_S_TEST".
4. Enable debugging and see that the string didn't change.
5. Apply PR.
6. See that the string didn't change with debugging enabled.
7. Disable debugging.
8. See now that the string is "Search by Test"

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on ee8d76846cffeb3d0823aa66cf262007660f113f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36748">issues.joomla.org/tracker/joomla-cms/36748</a>.</sub>

**Comment by Fedik** [comment]
> Enable debugging and see that the string didn't change.
Apply PR.
See that the string didn't change with debugging enabled.
Disable debugging.

Or can just reindex again

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ee8d76846cffeb3d0823aa66cf262007660f113f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36748">issues.joomla.org/tracker/joomla-cms/36748</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ee8d76846cffeb3d0823aa66cf262007660f113f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36748">issues.joomla.org/tracker/joomla-cms/36748</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36748">issues.joomla.org/tracker/joomla-cms/36748</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
