### PR TITLE
[com_search] Implement searchtools

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR, like already done in most views across Joomla admin panel, implements searchtools in com_search searches view.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Apply this patch in latest staging
2. Go to Components -> Search
3. Go to Options and enable gathering statistics
4. Go to the frontend `index.php?option=com_search&view=search` URI and do some searches.
5. Go again to Components -> Search, you'll see some search results
6. Apply this patch
7. Go again to Components -> Search you'll see the new visual
8. Test if search, filters, ordering and page limit (aka searchtools) are working properly. Test also the hide/show search results button.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3d510867d28b8a9a224060cb5852d4d7f9949181<br /><br />It works but I have no idea at all why we have the show/hide search results button and even if there is a good reason (db performance) the text is wrong. Its a frequency count(hits) not a result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10025">issues.joomla.org/joomla-cms/10025</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> It works but I have no idea at all why we have the show/hide search results button and even if there is a good reason (db performance) the text is wrong. Its a frequency count(hits) not a result

I understand, but it was already like that i didn't change it. That's for another PR, i guess.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 3d510867d28b8a9a224060cb5852d4d7f9949181<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10025">issues.joomla.org/joomla-cms/10025</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10025">issues.joomla.org/joomla-cms/10025</a>.</sub>

**Pull request merged**
