### PR TITLE
[4.0] Written by

### PR DESCRIPTION
**Pull request by brianteeman**
This is a super minor change for consistency but all the other items in the list have a colon

image

### CODE REVIEW

**Comment by HLeithner** [comment]
isn't this more a sentence then a "Author:" entry?

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on cf407198b3eb805fca607a5b50281c9b39a941b7<br /><br />Tested successfully in Beta5-dev of 25 September.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30770">issues.joomla.org/tracker/joomla-cms/30770</a>.</sub>

**Comment by brianteeman** [comment]
@HLeithner It could be seen that way and personally I change my sites to Author. In this specific case it is ok to have a : because it is a list and its the same for each item in the list. If it was the only item displayed then I would probably go for the current text

**Comment by HLeithner** [comment]
ok but shouldn't change it to author? it's more common (at least to me) to show only the author but not the category nor the Hits.

But yeah we can merge this if you insist.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cf407198b3eb805fca607a5b50281c9b39a941b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30770">issues.joomla.org/tracker/joomla-cms/30770</a>.</sub>

**Comment by ChristineWk** [comment]
>  it's more common (at least to me) to show only the author but not the category nor the Hits.

agree with you :-)

**Comment by infograf768** [comment]
As a reminder, this string is also used in frontend when displaying a Category List of articles where the colon is not necessary to be consistent. Not a big deal.

Screen Shot 2020-09-26 at 07 30 56

**Comment by brianteeman** [comment]
@infograf768 is the string even needed in that table

**Comment by infograf768** [comment]
> @infograf768 is the string even needed in that table

I guess so as the Headings can be set to hide.

Screen Shot 2020-09-27 at 09 37 24

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cf407198b3eb805fca607a5b50281c9b39a941b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30770">issues.joomla.org/tracker/joomla-cms/30770</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you fix conflict(s) in file `language/en-GB/com_content.ini`? Thanks in advance.

**Comment by webgras** [comment]
I have tested this item :white_check_mark: successfully on cf407198b3eb805fca607a5b50281c9b39a941b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30770">issues.joomla.org/tracker/joomla-cms/30770</a>.</sub>

**Comment by richard67** [comment]
@brianteeman I've allowed myself to solve the conflict for you.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30770">issues.joomla.org/tracker/joomla-cms/30770</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
