### PR TITLE
[4.0] Move anonymous class to real one

### PR DESCRIPTION
**Pull request by laoneo**
As our code style checker does not support anonymous classes, this pr replaces the content service provider class to a real one and uses a mock in the `JErrorPageTest`.

### CODE REVIEW

**Comment by mbabker** [comment]
If we're having to refactor code because the static analysis tools don't support a syntax, that seems like a problem...

**Comment by laoneo** [comment]
Agree. Not sure if we want to leave drone broken for now? Any clue when we can expect anonymous class support in the CS rules?

But for the unit tests it is ok to use a mock instead of an anonymous class.

For referenece, I opened an issue in the CS repo https://github.com/joomla/coding-standards/issues/231.

**Comment by mbabker** [comment]
Aside from the doc block detection (which to be honest, part of me wants to say "screw it" because you don't do doc blocks for Closures and those are just anonymous functions, why should anonymous classes have a documentation requirement an anonymous function doesn't?), there aren't issues with anonymous classes that I've run across.

**Comment by wilsonge** [comment]
> there aren't issues with anonymous classes that I've run across.

Look at the tabbing code style error in the unit tests

**Comment by wilsonge** [comment]
Mock for the tests does look better. You don't even need to mock `getRenderer` that was just so I could implement the interface in the anonymous class. Let's start with that. Revert the change to the component thing - that will get cleaned up with phpcs version 2 - if drone fails for now cause of that it fails for now

**Comment by mbabker** [comment]
> Look at the tabbing code style error in the unit tests

General tabbing issue unrelated to anonymous classes, https://github.com/joomla/coding-standards/issues/230 and other items track it (though not explicitly mentioning anonymous classes)

**Comment by laoneo** [comment]
Done.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
