### PR TITLE
[4.0] proper strings for media manager

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Bring back the missing strings 

### Testing Instructions

Apply patch, check com_media's options

### Expected result

screen shot 2017-06-07 at 16 06 49

### Actual result

screen shot 2017-06-07 at 16 02 11

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 386d9016ae4ada497258156178c2447c0fc188ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 386d9016ae4ada497258156178c2447c0fc188ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by laoneo** [comment]
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 386d9016ae4ada497258156178c2447c0fc188ef<br /><br />reverting my successful test as this string is still missing
COM_MEDIA_CONFIGURATION="Media: Options"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by brianteeman** [comment]
Please remove RTC for now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16561">issues.joomla.org/tracker/joomla-cms/16561</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman just added it back, is there anything else missing here?

**Comment by brianteeman** [comment]
Thanks for that one. As for other strings I have no idea because it is completely unfunctional so I can't use it to see

**Comment by wilsonge** [comment]
What do you mean by unfunctional?

**Comment by brianteeman** [comment]
@wilsonge all i see is this screenshot and no buttons are functional
screenshotr12-58-05

and the following js error in the console
```
Uncaught TypeError: Cannot read property 'filter' of undefined
    at Api._normalizeArray (mediamanager.js:8763)
    at Object.<anonymous> (mediamanager.js:8633)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

**Comment by laoneo** [comment]
Did you do a fresh install? If not then you need to discover the new media manager plugins.

**Comment by Bakual** [comment]
> Did you do a fresh install? If not then you need to discover the new media manager plugins.

I can confirm that after discovering and enabling the plugins the console errors are gone. 
I opened a new issue about that as I think the UX needs to be improved here.

**Comment by brianteeman** [comment]
the plugins were already enabled - it was a new install
screenshotr18-20-41

**Comment by brianteeman** [comment]
screenshotr18-21-56

**Comment by franz-wohlkoenig** [comment]
On a fresh installed 4.0-dev explored Plugins and activate them:
bildschirmfoto 2017-06-09 um 06 40 22
got this, seems fine:
bildschirmfoto 2017-06-09 um 06 41 52

**Comment by wilsonge** [comment]
@laoneo do you want to get in touch with @brianteeman and try and work this through as it would appear to be something specific to his setup?

**Comment by laoneo** [comment]
I asked in the j4 geoup if somebody with a windows environment can have a look as I can't repeoduce the issue.

**Comment by joomdonation** [comment]
I just installed latest 4.0-dev and it works OK. Tried to navigate between folder, create folder, upload images... and it works (just a quick try only)

I also don't see any error in the console. Look like it works fine. I am using Windows 8.

**Comment by Bakual** [comment]
I think it is related somehow to the special setup Brian has. It is a "real" Windows server, not the wanna-be XAMPP type one we usually test on :)

**Comment by brianteeman** [comment]
Which is even more reason to try and work out what the issue is. It might be an apache or php module that needs to be enabled. If that is the case then it needs to be added to the requirements etc

**Pull request merged**
