### PR TITLE
[4.4] Fix for multiselect.js to not to interfere with interactive elements

### LINKED ISSUE #43561: multiselect.js issue with unwanted selections
### Steps to reproduce the issue
In a component admin list view with select checkbox in the first column of each row and multiselect.js loaded.

include a `<details><summary>...</summary>...</details>` element in a column

include an `<a ...><span>...</span>...</a>` element in a column

### Expected result

clicking in the `<details>` element to open or close the details should not toggle the checkbox in the first column

clicking the `<span>` inside the `<a>` should not toggle the checkbox 

### Actual result
In both cases the checkbox is toggles. In the case of the span (or any other element inside the text for an `<a>`) it is only a potential problem if the target is for a new tab/window. 

### System information (as much as possible)

Joomla 5.1

### Additional comments
In principle you might think that adding 'DETAILS' and 'SUMMARY' to the `if (...` statement on line 52 in `multiselect.js` might fix the problem. However in real use cases you should be able to click anywhere in details area once it is open without toggling the checkbox.. 

In practice there are very often child elements (eg a list) inside the details and the if statement on line 52 as written is **only** checking the actual element that generates the event. It needs to be checking also the parents of the target in order to determine if the click is taking place inside one of the excluded elements.

This is why the span, or any other element, inside the text  for an `<a>` causes the checkbox to be toggled. 

A common case for using a `<span>` inside an `<a>` is if you want to use a font-awesome icon for the link.

A workaround is to add a `stopPropogation(event);` action in a function for the parent element `onclick()` event, but this shouldn't be necessary on a case by case basis. The multiselect.js function should exclude `<details>` elements and child elements inside excluded elements should also be excluded.

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43561 .

### Summary of Changes

Fix multiselect to not to interfere with interactive elements.

### Testing Instructions
Run `npm install`.

Edit https://github.com/joomla/joomla-cms/blob/4b690a0ba68299fa9e5041478d25dcdba6e3c6c0/administrator/components/com_content/tmpl/articles/default.php#L243

Add:
```html
<details>
  <summary>Details</summary>
  Something small enough to escape casual notice.
</details>
```

Got to Articles overview `/administrator/index.php?option=com_content&view=articles`
And click on "Details" in each row.

### Actual result BEFORE applying this Pull Request
The row become selected/unselected after each click

### Expected result AFTER applying this Pull Request
The row stay unselected.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by rogercreagh** [comment]
I have tested this item :white_check_mark: successfully on 9ca0d32910e549d1c88545d0fe8f900f4498d9f2<br /><br />Yep this seems to fix the problem with `<details>` elements and also `<a>` with html tags inside the text. Good job.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43574">issues.joomla.org/tracker/joomla-cms/43574</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ca0d32910e549d1c88545d0fe8f900f4498d9f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43574">issues.joomla.org/tracker/joomla-cms/43574</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43574">issues.joomla.org/tracker/joomla-cms/43574</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
