### PR TITLE
[4.0] Finish SimplePie Removal

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Finish the removal of SimplePie by removing the actual library from the Composer install

### Testing Instructions

Review

### Documentation Changes Required

Document it's gone, finally

### CODE REVIEW

**Comment by zero-24** [comment]
:+1: Looks like i missed it on the removal PR.

**Comment by mbabker** [comment]
This is the one you started but never submitted 😉

**Comment by zero-24** [comment]
Hmm then there was a reason. Thanks :+1:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0b0419dd80a5ef055b6c5e9ebb660773df4eaec3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12876">issues.joomla.org/tracker/joomla-cms/12876</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 0b0419dd80a5ef055b6c5e9ebb660773df4eaec3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12876">issues.joomla.org/tracker/joomla-cms/12876</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12876">issues.joomla.org/tracker/joomla-cms/12876</a>.</sub>

**Pull request merged**
