### PR TITLE
[4.0] Cancel button class

### PR DESCRIPTION
**Pull request by brianteeman**
Most cancel buttons have a red background - these two did not

Edit Profile
Cancel - no background ==> red

User Registration
Cancel - no background ==> red

Mail to friend
Cancel - no background ==> red

Edit content
Cancel - no background ==> red

### CODE REVIEW

**Comment by Quy** [comment]
I found more by searching on `<?php echo JText::_('JCANCEL'); ?>`.

**Comment by brianteeman** [comment]
I only intended to touch the front end as the admin can still change :(

Did I miss any on the front end?

**Comment by Quy** [comment]
\components\com_content\tmpl\form\edit.php
\plugins\installer\webinstaller\tmpl\default.php

**Comment by brianteeman** [comment]
I have added the edit content form but not the plugin - thats in the admin and is subject to redesign anyway

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0ceacb3a2caecdcc02ea2f7bcf6639f8a09d7b1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20653">issues.joomla.org/tracker/joomla-cms/20653</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on c93783c5e14cee7fd24bf5d5cba1cc444c3b4a18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20653">issues.joomla.org/tracker/joomla-cms/20653</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
