### PR TITLE
[4.0] Move forms to top level

### PR DESCRIPTION
**Pull request by laoneo**
Follow up of to move the rest from #16218.

### CODE REVIEW

**Comment by Bakual** [comment]
I think we have to adjust the form location also in the contenttype table
See https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/joomla.sql#L407-L420 and look for the "formFile".
I think it's related to Content History.

**Comment by laoneo** [comment]
Thanks @Bakual changed the installer files as well.

**Comment by Bakual** [comment]
> Thanks @Bakual changed the installer files as well.

Now we just need to figure out how we are going to update those entries for user updating from J3.

**Comment by laoneo** [comment]
Yups, hopefully somebody can help out on that.

**Comment by Bakual** [comment]
I think we can just add a query to update the whole row with new values. Otherwise we may have to use the script and update the stuff using the contentype table.

**Pull request merged**
