### PR TITLE
[4.1] Simplify Requirements for Task Routine XMLs

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36449.

### Summary of Changes
- Fixes form for the Image Size Check task routine and improves a language string for clarity.
- Removes requirement of the "showFront" attribute for the `task_params` fieldset.

### Testing Instructions
- Admin > System > Scheduled Tasks
- Click "Create Task" or similar
- Select "Image Size Check" routine
- Fill in the form and save

### Actual result BEFORE applying this Pull Request
- Form fails to submit due to validation error (missing required data).
- Routine XMLs require a `showFront="true"` attribute.

### Expected result AFTER applying this Pull Request
- Form is submitted, task is created.
- Routine XMLs no longer require require the attribute to work correctly.

### Documentation Changes Required
\-

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 0d0c644ddf4acd5effd8ce1609a82a5ac64f46cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 8cdd8ec545f97f78c8635c90237c9786f46c2ac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8cdd8ec545f97f78c8635c90237c9786f46c2ac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by ditsuke** [comment]
Needs tests again I believe

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 9f11de30e4dd6e9b8e83f5e90132acf4899ef893<br /><br />After the changes, everything works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 9f11de30e4dd6e9b8e83f5e90132acf4899ef893<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36515">issues.joomla.org/tracker/joomla-cms/36515</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
