### PR TITLE
[4] parent::cleanCache only accepts one param, 2 provided

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

Reference PR that removed the param: #14262

### CODE REVIEW

**Comment by wilsonge** [comment]
Linked the PR that had removed this param. Can you clean up the other places calling this function please

**Comment by PhilETaylor** [comment]
Lol that PR is FOUR YEARS OLD hahahaha

**Comment by PhilETaylor** [comment]
I have added the deprecation notices and reviewed all uses of `cleanCache` methods now - thanks.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
