### PR TITLE
[5.1][com_users]  fix batch-copy-move

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #43032 .

### Summary of Changes
fix batch-copy-move

### Testing Instructions
Created 2 test users, test-user-2 and test-user-3, gave them Administrator and Publisher permissions respectively.
Then  User -> Actions -> Batch -> to Add to Group: Editor those 2 users with Add to Group option and Require Password Reset: No selected. 

### Actual result BEFORE applying this Pull Request

error

### Expected result AFTER applying this Pull Request

action performed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da75cf05293ff61b7966055db286a5b22cfd4f2a<br /><br />Append `?w=1` to `https://github.com/joomla/joomla-cms/pull/43050/files?w=1` to see simple change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43050">issues.joomla.org/tracker/joomla-cms/43050</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on da75cf05293ff61b7966055db286a5b22cfd4f2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43050">issues.joomla.org/tracker/joomla-cms/43050</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43050">issues.joomla.org/tracker/joomla-cms/43050</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @alikon and also for testing @Quy @bembelimen

**Pull request merged**
