### PR TITLE
2013 to 2016

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Very simple PR. Update some dates in comments in 3 files 2013 --> 2016.
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 62762521db8b38e8b7bfd6454b461f24a0a88716<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10842">issues.joomla.org/joomla-cms/10842</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 62762521db8b38e8b7bfd6454b461f24a0a88716<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10842">issues.joomla.org/joomla-cms/10842</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10842">issues.joomla.org/joomla-cms/10842</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks all for testing and merging!

**Pull request merged**
