### PR TITLE
Added time in created amd modified date in tag

### PR DESCRIPTION
**Pull request by RonakParmar**
#### Summary of Changes

Added time in Created Date and Modified Date in tag view.
#### Testing Instructions
- Create new tag in administrator side.
- Check Created Date field dose not have time, only date is there.
- Edit tag and save it, reopen that tag and check Modified Date has only date, time is not there.
- Apply this PR and perform same steps and check both field has date and time.

### CODE REVIEW

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 6de6858e9f748b88ab4fcbdd3bae38ca4be47eca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11186">issues.joomla.org/joomla-cms/11186</a>.</sub>

**Comment by killoltailored** [comment]
I have tested successfully with Joomla Version: Joomla! 3.6.1-dev Development [ Noether ] 13-July-2016 10:08 GMT 
And OS Windows 8.1, Browser: Firefox 47.0.1

screen shot 2016-07-19 at 01 24 01
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11186">issues.joomla.org/joomla-cms/11186</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 6de6858e9f748b88ab4fcbdd3bae38ca4be47eca<br /><br />I have tested in Joomla 3.6.0 and now date and time display on "Created Date" and "Modified Date" fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11186">issues.joomla.org/joomla-cms/11186</a>.</sub>

**Comment by NeerajTailored** [comment]
I have tested this item :white_check_mark: successfully on 6de6858e9f748b88ab4fcbdd3bae38ca4be47eca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11186">issues.joomla.org/joomla-cms/11186</a>.</sub>

**Comment by brianteeman** [comment]
RTC - a win for consistency <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11186">issues.joomla.org/joomla-cms/11186</a>.</sub>

**Pull request merged**
