### PR TITLE
[staging] Deleting unused Contacts "banned" fields

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/23569

### Summary of Changes
Deleting unused contact fields:
banned_email
banned_subject
banned_text

Keeping them in the Component Options as, since 2.5, it is the only place where they work.

Deprecating some ini strings
Corrected sql files
Modified some unit test files EXCEPT `/tests/unit/stubs/database/jos_finder_links.csv` which I have no idea how to clean.
For that one, @mbabker @wilsonge @Hackwar please make PR against mine 

### Testing Instructions
Edit a contact, a contact category, all contacts menu items and make sure the 3 fields do not appear.
Check the sql for possible errors.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 4f51528a8289f26d4439ea61d3ef0651c41c0e59<br /><br />- Contact fields under: components > contacts > contacts > mycontact > Form:
banned_email
banned_subject
banned_text
are deleted.

- In com_contacts Global Options it works - still working :-)

- sql > sorry, don't know



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23585">issues.joomla.org/tracker/joomla-cms/23585</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4f51528a8289f26d4439ea61d3ef0651c41c0e59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23585">issues.joomla.org/tracker/joomla-cms/23585</a>.</sub>

**Comment by infograf768** [comment]
Rtc
@maintainers please look at the file I did not correct, if it is still used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23585">issues.joomla.org/tracker/joomla-cms/23585</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23585">issues.joomla.org/tracker/joomla-cms/23585</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
