### PR TITLE
shorten label in global configuration

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #12706 .

### Summary of Changes
This is purely a cosmetic change to maintain alignment

As noted in the report this will not help for non-english languages but thats a bigger problem effecting all labels and wont help with squashed views on smaller screens
#### Before

image

#### After
image

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 73ff6eb33f29ae6af5c97598a6abd82dbbd71f98<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12708">issues.joomla.org/tracker/joomla-cms/12708</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 73ff6eb33f29ae6af5c97598a6abd82dbbd71f98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12708">issues.joomla.org/tracker/joomla-cms/12708</a>.</sub>

**Comment by ggppdk** [comment]
What about the overlapping issue of the columns in smaller screens ? mentioned by #12706

why not add a sane minimum width to force wrap just before overlapping occurs ?
e.g. 
```css
#config-document .span6 {
    min-width: 400px;
}
```

or even better a media css rule:
```css
@media (max-width: 1023px) {
	#config-document .span6 {
		width: 100%;
	}
}
```

overlapping

**Comment by mbabker** [comment]
If you have to override the widths set by Bootstrap's grid system you've messed up catastrophically.

**Comment by ggppdk** [comment]
This is not a general override for bootstrap !!
- we have a specific page that has specific needs for width for the columns

I did not suggest a **terrible general rule** like
```css
@media (max-width: 1023px) {
    .span6 {
        width: 100%;
    }
}
```

Imagine having a class that extends a class and not be allowed to customize its code according to specific needs, 

bootstrap CSS rules are not sacred, and if they are proper for all cases, why do they fail terribly in this case ? of course any CSS override must be made sure that it will only effect other pages

The alternative CSS to fix this will be even uglier overrides ! with uglier looking result,

of course in the end you can just remove the columns, but wait my suggested code does exactly this, it forces 1 column at a sane width limit

**Comment by ggppdk** [comment]
Or if you like to make it even safer / neater, maybe introducing a new CSS class along with span6 would be best

**Comment by brianteeman** [comment]
That's an issue that effects all screens especially the modals

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12708">issues.joomla.org/tracker/joomla-cms/12708</a>.</sub>

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
