### PR TITLE
Correct implode() argument order for PHP 7.4

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Changes `implode()` argument order to solve deprecation messages in PHP 7.4:

>Deprecated: implode(): Passing glue string after array is deprecated.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a1b3d387554bea8d1db6f4c1e22c16bbaa88cb34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25784">issues.joomla.org/tracker/joomla-cms/25784</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a1b3d387554bea8d1db6f4c1e22c16bbaa88cb34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25784">issues.joomla.org/tracker/joomla-cms/25784</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thank you for the time you invest to make J3 PHP 7.4 compatible.

**Pull request merged**
