### PR TITLE
[4.0] Obvious typo

### PR DESCRIPTION
**Pull request by brianteeman**
As you can see the folder name has a typo - this PR fixes that typo AND fixes the reference in the code so the typo doesn't have to bubble down

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4c086955a9f1eb89c4a74334d34bbf049138f449<br /><br />Code review:
1. The change done by this PR here is consistent.
2. The typo doesn't occur anywhere else.

Strange that nobody has seen that before (including me) ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27811">issues.joomla.org/tracker/joomla-cms/27811</a>.</sub>

**Comment by brianteeman** [comment]
Drone error is the usual fault image test and not related to this pr

**Comment by richard67** [comment]
Yes, can confirm that.

**Comment by blueforce** [comment]
I have tested this item :white_check_mark: successfully on 4c086955a9f1eb89c4a74334d34bbf049138f449<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27811">issues.joomla.org/tracker/joomla-cms/27811</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27811">issues.joomla.org/tracker/joomla-cms/27811</a>.</sub>

**Comment by brianteeman** [comment]
Thanks Robert

**Pull request merged**
