### PR TITLE
[4.0][workflow] - batch change stage

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes

yet another state vs stage issue

### Testing Instructions
On Articles  select some and hit the batch button
choose you stage change and process

in the LOG you should see
Notice:  Trying to get property 'condition' of non-object in /var/www/html/j4dev/administrator/components/com_content/Model/ArticleModel.php on line 238

### CODE REVIEW

**Comment by ggppdk** [comment]
Issue confirmed , fix works

Also line 840 need to change `$state->condition to  $stage->condition`
```php
$data['state'] = (int) $state->condition;
```

or is the above in some other PR ?

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on da925cdf2d9222ebff9bf7b5cf755cd041681b2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21625">issues.joomla.org/tracker/joomla-cms/21625</a>.</sub>

**Comment by infograf768** [comment]
Agree with @ggppdk 
Also please modify line 840

**Comment by alikon** [comment]
done 840

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e2607b832c5ac3d661671721b0e23773d3bba3ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21625">issues.joomla.org/tracker/joomla-cms/21625</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on e2607b832c5ac3d661671721b0e23773d3bba3ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21625">issues.joomla.org/tracker/joomla-cms/21625</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21625">issues.joomla.org/tracker/joomla-cms/21625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
