### PR TITLE
Modules batch modals changes

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### This is complimentary to #7000 and #7003

What is changed:
1. modals are properly rendered through the API
2. overrides have only the actual content (no hard coded structure)
3. obey to ACL
4. modal is rendered only if items exist
5. process button class from primary to success (color change from blue to green)
#### testing

You need to test the batch functionality for this url: administrator/index.php?option=com_modules&view=modules

### CODE REVIEW

**Comment by brianteeman** [comment]
When this is merged I will look at clarifying the text etc to remove confusion on what is required<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7648">issues.joomla.org/joomla-cms/7648</a>.</sub>

**Comment by brianteeman** [comment]
Module Batch processing still works as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7648">issues.joomla.org/joomla-cms/7648</a>.</sub>

**Comment by zero-24** [comment]
Batch still works. Thanks --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7648">issues.joomla.org/joomla-cms/7648</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Looks good, thank you @dgt41. I will merge it!

@brianteeman Could you please clarify the text? Thank you!

**Pull request merged**
