### PR TITLE
[4.0] Webcomponents JS not found

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Corrects filename.

### Testing Instructions

Use a browser that requires WC polyfills, e.g. Edge.

### Expected result

Everything works.

### Actual result

Some buttons and other elements are broken due to JS errors:

> Error: Could not load polyfill bundlehttp://localhost/joomla-cms/media/vendor/webcomponentsjs/js/webcomponents-sd.min.js  
> core.js:1058:17
> GET 
> http://localhost/joomla-cms/media/vendor/webcomponentsjs/js/webcomponents-sd.min.js [HTTP/1.1 404 Not Found 5ms]
> Error: Could not load polyfill bundle http://localhost/joomla-cms/media/vendor/webcomponentsjs/js/webcomponents-sd.min.js  
> core.js:1058:17

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3c510341a3a6a846a3ff8061794e0f09d2645290<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26743">issues.joomla.org/tracker/joomla-cms/26743</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 3c510341a3a6a846a3ff8061794e0f09d2645290<br /><br />It goes to the right files now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26743">issues.joomla.org/tracker/joomla-cms/26743</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26743">issues.joomla.org/tracker/joomla-cms/26743</a>.</sub>

**Comment by wilsonge** [comment]
OK on my macbook the minifed file here exists (In terms of this path `media/vendor/webcomponentsjs/js/webcomponents-sd.min.js`)
Screenshot 2019-10-21 at 09 56 15

Why is the minified file not existing for you I think is the question here

**Comment by SharkyKZ** [comment]
You probably need to run `npm ci`. Those files are not included in nightlies anyways. I think since #26557.

**Comment by dgrammatiko** [comment]
@SharkyKZ if so then there should be a bug in this line https://github.com/joomla/joomla-cms/pull/26557/files#diff-788d2ec61f82f93e185ade0fdbd27898R23

**Comment by SharkyKZ** [comment]
And here I thought this was intentional 😄

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ce7296406b182a0d8bc3fee1043c6f8cc379adf3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26743">issues.joomla.org/tracker/joomla-cms/26743</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! Looks better now!

**Pull request merged**
