### PR TITLE
[4][sql] alter menutype field from 24 to 48

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #41826

### Summary of Changes
 alter menutype field from 24 to 48

### Testing Instructions
#41826

### CODE REVIEW

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_menus/forms/menu.xml#L20 

I am not convinced, Every limitaion is a limitation. 

en: Disability equality laws
hu: A fogyatékossággal élők egyenlőségére vonatkozó jogszabályok

**Comment by HLeithner** [comment]
I see no reason for increasing this field, it's only used as identifier and not as description

**Comment by richard67** [comment]
Maybe blog sample data installation should be fixed so that it makes sure that the menutype values are unique, like we do for aliases and hen saving copies. This would for sure solve the (absolutely valid) scenario described in the issue, while increasing the length will only make it less likely happen.

**Comment by richard67** [comment]
I think we only have to modify the blog sample data installation so that it uses only a substring of the translated language string which is short enough so that the language code always can be appended without exceeding the limit of 24, then we can be sure we don’t have the same value for 2 languages.

**Pull request closed without merging**
