### PR TITLE
Fix some admin error page issues

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #33599 #33612 .

### Summary of Changes
Defines defaults for template color variables / Fixes header btn alignment.

### Testing Instructions
Logout of Joomla 4 admin
Go to a URL that generates a 403 Forbidden message - here is a quick example:

http://example.com/administrator/index.php?option=com_banners&task=tracks.display&format=raw

### CODE REVIEW

**Comment by richard67** [comment]
@ciar4n Do I assume right that this PR also makes PR #33649 obsolete?

**Comment by ciar4n** [comment]
Yes I think so... the header button alignment is fixed here

**Comment by PhilETaylor** [comment]
This fixes the reported issue with text color for sure, but

 - The bottom blue box in the left sidebar changes between the error page and the login page
 - There is a 'view website' link on the error page in the left menu bar, this needs to either be "View website" or removed I guess. 

https://user-images.githubusercontent.com/400092/117549149-9c2c4d80-b030-11eb-9594-687a8c635134.mp4

Happy to mark this as a successful test though as it resolves the reported issue and gets the error page to a useable state

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on ca8daa7266a036bf2fd863c35e45fd4f92a27fcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33654">issues.joomla.org/tracker/joomla-cms/33654</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on ca8daa7266a036bf2fd863c35e45fd4f92a27fcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33654">issues.joomla.org/tracker/joomla-cms/33654</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33654">issues.joomla.org/tracker/joomla-cms/33654</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ca8daa7266a036bf2fd863c35e45fd4f92a27fcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33654">issues.joomla.org/tracker/joomla-cms/33654</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
