### PR TITLE
[4.0] Fix redundant description

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Move the description to the basename field instead it being a note.

### Testing Instructions
Go to Components > Banners > Tracks
Click `Export` button.

### Actual result
export

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 0735430b65f28e7cef4e5891ec38870a82e7fec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0735430b65f28e7cef4e5891ec38870a82e7fec8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by deepa-g** [comment]
I have tested this item white_check_mark successfully

**Comment by rajnish-dargan** [comment]
I have tested this item :white_check_mark: successfully on 572b0574b498f0d218db1cd581a319baf00218fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by deepa-g** [comment]
I have tested this item :white_check_mark: successfully on 572b0574b498f0d218db1cd581a319baf00218fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26868">issues.joomla.org/tracker/joomla-cms/26868</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
