### PR TITLE
[4.1] s/Instantiante/Instantiate

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4.1] s/Instantiante/Instantiate

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 09aee306bc75c049474f7d5b9f926bb4bbf54f51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36341">issues.joomla.org/tracker/joomla-cms/36341</a>.</sub>

**Comment by dgrammatiko** [comment]
@PhilETaylor can you make the changes against: https://github.com/joomla/joomla-cms/pull/36112 ?

**Comment by PhilETaylor** [comment]
as well? https://github.com/joomla/joomla-cms/pull/36112#r771578127_

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 09aee306bc75c049474f7d5b9f926bb4bbf54f51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36341">issues.joomla.org/tracker/joomla-cms/36341</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36341">issues.joomla.org/tracker/joomla-cms/36341</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
