### PR TITLE
[4.0] Fix case of "Blog Sample data"

### PR DESCRIPTION
**Pull request by hardik-codes**
A small PR.

### Summary of Changes
Changes in ```administrator/language/en-GB/en-GB.plg_sampledata_blog.ini```

### Testing Instructions
In the control panel look for Blog Sample Data

### Expected result
typo

### Actual result
typo(1)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on f1869a89ed2ccc05fb47c0f04c51042a6e8c013d<br /><br />OMG...the d went to D ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24158">issues.joomla.org/tracker/joomla-cms/24158</a>.</sub>

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on f1869a89ed2ccc05fb47c0f04c51042a6e8c013d<br /><br />It may have been a small pull request but it still took a full button press to make the change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24158">issues.joomla.org/tracker/joomla-cms/24158</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24158">issues.joomla.org/tracker/joomla-cms/24158</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
