### PR TITLE
[5.0] Update composer dependencies. Especially Webauthn-lib

### PR DESCRIPTION
**Pull request by HLeithner**
### Summary of Changes
Updating weak dependencies and Webauthn-lib from 4.3.0 to 4.5.2

### Testing Instructions
Test all Variant of Webauthn/Passkeys

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Additional
Webauthn plugin needs to be updated because of many new deprecation in the upstream library

### CODE REVIEW

**Comment by HLeithner** [comment]
PR seems to break webauthn/passkeys

**Comment by Fedik** [comment]
Try to change version to 4.5, as on their documentation it is latest https://webauthn-doc.spomky-labs.com/the-project/the-project
4.7 probably some transition stuff on the way to 5.0, there no docs about it.

**Comment by HLeithner** [comment]
ok, downgraded to 4.5.2

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 26a418c1f4b6b1649141086e24d91e2bfabf895e<br /><br />Unfortunately I have only one Webauthn method available, the Windows Hello PIN.

I've successfully tested that this method works for both the primary login and the MFA on a new installation made with the branch of this PR, and I have also tested that primary login and MFA with this method set up on a 4.4-dev still work after updating to the patched package for this PR.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41862">issues.joomla.org/tracker/joomla-cms/41862</a>.</sub>

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on 26a418c1f4b6b1649141086e24d91e2bfabf895e<br /><br />tested both 2FA and Passkeys with hardware key on linux with vivaldi.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41862">issues.joomla.org/tracker/joomla-cms/41862</a>.</sub>

**Pull request merged**
