### PR TITLE
Tags view - remove "PHP Warning: Creating default object from empty value"

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

Remove `PHP Warning:  Creating default object from empty value in ../components/com_tags/views/tags/view.html.php on line 48`

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 036bae4880002d80ddea0a9d2fe97895a31c21a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22246">issues.joomla.org/tracker/joomla-cms/22246</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 036bae4880002d80ddea0a9d2fe97895a31c21a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22246">issues.joomla.org/tracker/joomla-cms/22246</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by svenbluege** [comment]
I have tested this item :white_check_mark: successfully on 036bae4880002d80ddea0a9d2fe97895a31c21a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22246">issues.joomla.org/tracker/joomla-cms/22246</a>.</sub>

**Pull request merged**
