### PR TITLE
[4.0] Module "Show full description ..." Link doesn't work

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36670

### Summary of Changes

Bug fix

### Testing Instructions

Check the related issue

### Documentation Changes Required

No

### CODE REVIEW

**Comment by richard67** [comment]
@dgrammatiko Title says "[4.1" but target branch is 4.0-dev.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1401aaf0fffffb8eddc953c2a59577bf0a04e19f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36683">issues.joomla.org/tracker/joomla-cms/36683</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1401aaf0fffffb8eddc953c2a59577bf0a04e19f<br /><br />no more js errror<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36683">issues.joomla.org/tracker/joomla-cms/36683</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36683">issues.joomla.org/tracker/joomla-cms/36683</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
