### PR TITLE
[4.1] Remove unused Import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on c2948c2d00d19f3730aa19f3fd64e54fb1e8e3e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36197">issues.joomla.org/tracker/joomla-cms/36197</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c2948c2d00d19f3730aa19f3fd64e54fb1e8e3e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36197">issues.joomla.org/tracker/joomla-cms/36197</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36197">issues.joomla.org/tracker/joomla-cms/36197</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
