### PR TITLE
Some useful extra validation added e.g validate-date

### PR DESCRIPTION
**Pull request by aniket19491**
Now you can validate your date and numeric fields.

For e.g
If you have a date field in your Joomla's form and the user enters a wrong date then you will get a fatal error on the page. So its better to validate the date field before saving.

Field 1- YYYY/MM/DD can be validate using class "validate-date"
Field 2- YYYY/MM/DD H:I:S can be validate using class "validate-datetime"

These changes have been added to "validate-uncompressed.js". To test this you will need to minify this file and replace the content of "validate.js" with this.

Let me know if any other information is needed.

### CODE REVIEW

**Comment by zero-24** [comment]
>Let me know if any other information is needed.

Can you minify the `validate-uncompressed.js` file into `validate.js` with your PR? It will be easyier on merge and test ;)

**Comment by aniket19491** [comment]
@zero-24 I have made changes in validate.js too.

**Comment by datredweb** [comment]
I have tested this item :red_circle: unsuccessfully on e7f4cf84234fff9c25fa1b3df241592de9df83e4<br /><br />If i understand the issue right then it is not fixed yet. 
Replication steps:

1. Login to the Admin
2. Navigate to the Feeds page and create a new Feeds
3. For the created date field, try to input some "DD/MM/YYYY", different than current date.
4. Save it, it still works.
5. Open the Feed again

Observe: The date is automatically transformed to a current date
Expect: We should validate the date format on the inputting steps when user trying to create a new Feed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8208">issues.joomla.org/joomla-cms/8208</a>.</sub>

**Comment by aniket19491** [comment]
@datredweb Thank you for you testing.

Have you added the class "validate-date" or "validate-datetime" to that date input field? It won't work without adding the validate class.

**Comment by brianteeman** [comment]
I can see what you are doing here but as it is it is not ready for inclusion in the core. If you can look at how to implement validation on the date fields in the core joomla fields we can always re-open it when it is ready for testing again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8208">issues.joomla.org/joomla-cms/8208</a>.</sub>

**Comment by parthlawate** [comment]
I think it should be kept open. Maybe tested via a different test case. Since this is more like a library fix which allows for new validations ..

Now that it's available it can be used in various parts of the Joomla core ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8208">issues.joomla.org/joomla-cms/8208</a>.</sub>

**Comment by brianteeman** [comment]
Provide the method for testing then

**Comment by parthlawate** [comment]
OK.. Will ask one of the team to Submit another PR to implement this in one of the Standard Joomla forms so that the test case can be provided. And provide that link here as well.

**Pull request closed without merging**
