### PR TITLE
Minimum Password Length

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #36067 .

### Summary of Changes
Change the name of the field to improve understanding especially when you have manually set an invalid password length and the error message only displays the field name

image

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on 67c17d01d5ec9f980e77b26ef82ad8486eea0f5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36072">issues.joomla.org/tracker/joomla-cms/36072</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 67c17d01d5ec9f980e77b26ef82ad8486eea0f5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36072">issues.joomla.org/tracker/joomla-cms/36072</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36072">issues.joomla.org/tracker/joomla-cms/36072</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 67c17d01d5ec9f980e77b26ef82ad8486eea0f5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36072">issues.joomla.org/tracker/joomla-cms/36072</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
