### PR TITLE
[4.2] fix module name

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

module name in manifest don't match with module name

### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1c83543195ac1f2f8f3726548825fd958ff8e294<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38521">issues.joomla.org/tracker/joomla-cms/38521</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1c83543195ac1f2f8f3726548825fd958ff8e294<br /><br />Code review. I've verified that "mod_status" doesn't appear anywhere else beside the place fixed by this PR, except of the update SQL scripts and script.php where we delete the old module with that name and its files and folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38521">issues.joomla.org/tracker/joomla-cms/38521</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38521">issues.joomla.org/tracker/joomla-cms/38521</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
