### PR TITLE
Update en-GB.com_installer.ini

### PR DESCRIPTION
**Pull request by brianteeman**
Remove extra text. It really isn't necessary to have a wall of text explaining all the possible uses of Discover.

> Avoid over-communication
> 
> Be explicit wherever necessary but don't explain the obvious. On the web scanning is the norm and too much text weakens the effectiveness of the message - it does not enhance

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 4ec62b6ade36f79abf2bff3fbbdceda7e0e69cf5<br /><br />Works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Comment by zero-24** [comment]
RTC as it is a language change. Let the PLT decide to go with it. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Comment by infograf768** [comment]
Disagree. But I guess this was expected. 
The comment makes sense for beginners and is already in all languages.

**Comment by rdeutz** [comment]
It might be much text, but it explains what is it for. Without people can mix it with update or at least don't know the difference without looking at the documentation. 
staging - administration - extensions- discover

I would let it as it is.

**Comment by brianteeman** [comment]
Do we have walls of text for every function in joomla? No.

As I quoted the more text you have the less likely someone will read it.

**Comment by rdeutz** [comment]
If you remove all information then reading is not needed at all, if you like to have it short then change it to "Discover extensions that have been uploaded with (S)FTP and install them here." so it is clear what this is for.

**Comment by brianteeman** [comment]
Except that isnt technically correct.
Cant force you to improve joomla

On 20 November 2015 at 09:51, Robert Deutz <notifications@github.com> wrote:

> If you remove all information then reading is not needed at all, if you
> like to have it short then change it to "Discover extensions that have been
> uploaded with (S)FTP and install them here." so it is clear what this is
> for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8459#issuecomment-158341562>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Whilst I agree that less text is better I'm not convinced the new text actually gives enough information so that people can understand what it actually does.

**Comment by sovainfo** [comment]
Agree with Brian. The only other function I found so far is System->Clear Expired Cache. All other functionality in the back-end doesn't tell you what to do! 

Suggest to use: "Use Discover from the tool bar to find extensions that are not properly registered. Use Install from the tool bar to register them." to instruct the administrator on using this function.

As with any of the other functions  you need to use Help from the tool bar when you don't know how to use something. That Help provides information that goes further than instructions on what to do (most of the time).

**Comment by infograf768** [comment]
>Suggest to use: "Use Discover from the tool bar to find extensions that are not properly registered. Use Install from the tool bar to register them." to instruct the administrator on using this function.

A newbie would not understand that at all. "register" is dev talk.
I confirm no change is fine and important tip as this must be obvious to anyone getting to this screen, not forcing to go through the Help button.
In fact, we would need more obviously present tips like this, except evidently if Joomla is targetting more and more at specialists... which could explain some recent downfall in the CMS market share.

**Comment by sovainfo** [comment]
Maybe a newbie doesn't understand. A Super user should! And again if he doesn't he should go for the Help.

Prefer to have this consistent with the rest of the UI. As mentioned nowhere else this is done.

Rather than these tips, proper instructions on what to do are needed. That even includes this case:
Upon installation of extensions the scripts are copied to their locations in the filesystem and registered in the database. (Nothing to do with developer talk, plain administration talk in my opinion.)
The Discover functionality only provides half the functionality needed when there is a discrepnacy between the filesystem and the database. It allows you to synchronize the database info with the filesystem. The visa versa is missing, it is left to the administrator to do that manually. A button to remove the unwanted extensions would cater for that. Also the Install button should be called Register because the scripts are already in place.

In addition there is much more functionality missing to correct mistakes in an environment. Not being able to correct these mistakes makes managing a website much more complicated than necessary. Specially for newbies. Providing the missing functionality will help, but improving the quality of the product so users won't run into these situations is much more preferred.

Looking at the functionality of Discover, consider it something for a specialist. It would be available to an administrator instead of Super user otherwise! The fact this functionality is needed might explain the downfall, not the fact it is provided (even when it is only half of the functionality needed).

**Comment by wilsonge** [comment]
I agree that the current phrase is too long. But I think there is a balance to be found between Brian's proposition and something that works for new users

**Comment by roland-d** [comment]
Perhaps we should have a manual ;) I like the new text.

**Comment by rdeutz** [comment]
That is the proposed text:

**Discover extensions that have not gone through the normal installation process.**

I don’t like that it is only explaining what it is not instead of explaining what it is and you need to know what is the "normal installation process". If we are going with that proposal we can remove that sentence entirely because it doesn’t help.

I 100% agree that we need to avoid to have „walls of text“ but this doesn’t mean that we replace it with „short non have a useful meaning at all sentences“. I think we need more short hints for parts of the CMS. We should not forget that at some point someone installs Joomla! and is just clicking through the interface to look what it is. Some parts don’t need a big explanation what it is. E.g. article manager, it is for managing articles, no need for saying this on the page.

Beside the question, if we should change the sentence I would say the bigger questions is what amount of information are we are going to give within the backend. If we say no specific explanation then we can remove it completely, if we say yes then we need to add information also at other places.

**Comment by sovainfo** [comment]
Agree with the fact the proposed text by Brian is too abstract. Which is why I suggested concrete instructions on what to do. Similar to what is done at System->Clear expired cache. 

As mentioned that is the only function I found that provides instructions. Consider those instructions relevant because the use needs to do them first to be able to do something with the results. These are examples of the very few functions that require an action by the user first. In general functions provide information the user can manipulate providing a tool bar with actions to perform on the shown information. 

Considering these functions are targeted at the Super user I consider it fair to say he should know what to do. Even newbies that don't know should go for the Help on the tool bar. So, the instructions I provided tell you what you already should know. 

This function allows you to repair a situation where something went wrong ( only half, missing options to remove discovered extensions! ). Guess that someone trying to repair an environment should know what he is doing. So, wouldn't mind removing the obvious instructions. Take it that surprised users about the lack of information would go for the Help button, provided for this reason!

**Comment by pjwiseman** [comment]
Moving back to Pending.  A bit too much contention to be RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please follow @pjwiseman 's descision he is allowed to do this :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 4ec62b6ade36f79abf2bff3fbbdceda7e0e69cf5<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Comment by chrisdavenport** [comment]
Setting to RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8459">issues.joomla.org/joomla-cms/8459</a>.</sub>

**Pull request merged**
