### PR TITLE
[4.0] Backup message

### PR DESCRIPTION
**Pull request by brianteeman**
Many users use their hosts backup facility and this is typically __only__ for files

This update reminds them to backup the database as well

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 87ba0b40ab6ef7c0c82f457de2f85b4a929f2a77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on 87ba0b40ab6ef7c0c82f457de2f85b4a929f2a77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by zero-24** [comment]
Secificly this is an importand information for 3.10 to 4 Upgrades right?. Do you want to do such a PR or can i take the changes from here back into 3.10?

**Comment by brianteeman** [comment]
its important for all updates/upgrades. I don't usually look at J3 any more but I will do a PR there for this

**Comment by zero-24** [comment]
Thanks merged there :-)

**Comment by wilsonge** [comment]
Closing this one as it's been merged to 3.10 and I'll make sure it gets merged upto 4.x. Thankyou though!

**Comment by brianteeman** [comment]
@wilsonge NO!!! There are MORE changes in this PR than the one for J3

**Comment by zero-24** [comment]
@wilsonge as mentiond by Brian in 4.x we have one string more in the PR here thats not part of J3. I'm not sure whats better to merge here or first pull 3.10 into 4.0-dev. Just let me know I'm happy to do both ;)

**Comment by richard67** [comment]
RTC again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by richard67** [comment]
> This update reminds them to backup the database as well

Sometimes I think that some people even don't know that there IS a database 😄

**Comment by pritam825** [comment]
@richard67 right :smile: )<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 87ba0b40ab6ef7c0c82f457de2f85b4a929f2a77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36487">issues.joomla.org/tracker/joomla-cms/36487</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
