### PR TITLE
Smart search parser leaking CSS and JS terms

### PR DESCRIPTION
**Pull request by chrisdavenport**
Pull Request for Issue #12408 .
### Summary of Changes

Strip head first because head may contain script or style blocks.
### Testing Instructions

Copy-paste an entire web page with a head block that contains inline CSS and/or JavaScript into a new article.  You might see CSS or JS terms in the autosuggester.  If you don't, try another web page until you do.  You can try this page: https://www.joomla.org/announcements/release-news/5418-joomla-254-released.html then search for "col2".

Apply this PR.

Copy-paste the same article again so it gets re-indexed.  The CSS/JS terms should no longer appear in the autosuggester.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
i've followed the test instruction  but still "col2" is present after patch
bfp

**Comment by chrisdavenport** [comment]
@alikon Can you send me a copy of the article that is causing this?

**Comment by alikon** [comment]
is the one in the info  https://www.joomla.org/announcements/release-news/5418-joomla-254-released.html

**Comment by chrisdavenport** [comment]
The problem went deeper than I originally thought.

In order to keep memory use down, the indexer::tokenizeToDb method was chunking the input string before handing over to the parser.  The parser was also chunking, which although redundant, was, I thought, at least harmless.  However, it turns out that the indexer chunking process was, on certain input strings, placing chunk boundaries inside HTML tags.  The HTML parser was then not recognising them as being tags and was generating tokens for HTML attributes which should have been removed.

The fix is to understand that the format-dependent (in this case, HTML) parser must always pre-process the input before chunking can take place.

What I've now done is remove chunking from the indexer, but also simplified the code a little, removing some duplication and reducing indentation by removing some else clauses.

@alikon Please re-test and also make sure that everything that should be indexed is still being indexed.  Thank you.

**Comment by alikon** [comment]
i've tested before the the merge of 3.7.x branch to staging 
well done chris

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ef83bfbafdbf17d3e617c73d7a9acd75b225fabc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12411">issues.joomla.org/tracker/joomla-cms/12411</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ef83bfbafdbf17d3e617c73d7a9acd75b225fabc<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12411">issues.joomla.org/tracker/joomla-cms/12411</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12411">issues.joomla.org/tracker/joomla-cms/12411</a>.</sub>

**Comment by rdeutz** [comment]
@chrisdavenport can you have a look at the conflicts, thanks

**Comment by chrisdavenport** [comment]
You should test again, just in case I screwed something up.

**Pull request merged**
