### PR TITLE
[users list modal] ismoo parameter need to still exist after form submit (solve #12122)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/12122.
### Summary of Changes

The ismoo parameter is not in the form of users modal so it's lost after submit.
For more info see https://github.com/joomla/joomla-cms/issues/12122
### Testing Instructions
1. Code review
2. Apply patch on latest staging
3. Confirm there is no https://github.com/joomla/joomla-cms/issues/12122 issue 
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@dgt41 the ismoo parameter is from your PR https://github.com/joomla/joomla-cms/pull/10791
please see if there is anything else that needs to be corrected

**Comment by andrepereiradasilva** [comment]
@javimata @dgt41 can youplease check this?

**Comment by dgt41** [comment]
@andrepereiradasilva I think is fine, you can change `cmd` to `int` I think, this is either 0 or 1

**Comment by andrepereiradasilva** [comment]
moved to int. please test

**Comment by dgt41** [comment]
default should be 1, for B/C...

**Comment by andrepereiradasilva** [comment]
default to 1. please test

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 4a5f13dbd2c270a783e57b6eb8b9571ae183dc9d<br /><br />Works fine!

Just a remark: on the pop up make sure you will use the search box, to test this...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12137">issues.joomla.org/tracker/joomla-cms/12137</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 4a5f13dbd2c270a783e57b6eb8b9571ae183dc9d<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12137">issues.joomla.org/tracker/joomla-cms/12137</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12137">issues.joomla.org/tracker/joomla-cms/12137</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by andrepereiradasilva** [comment]
> why with this work?

@javimata don't understand your question

**Pull request merged**
