### PR TITLE
Fixing ShowOn multilevel field groups issue - Issue #14002

### PR DESCRIPTION
**Pull request by tassosm**
Pull Request for Issue #14002 

### Summary of Changes
Adds support for multi-level field groups to parseShowOnConditions() method.

### Testing Instructions
Follow the description of the issue #14002 check and confirm the issue

### CODE REVIEW

**Comment by wilsonge** [comment]
Please can you set the file permissions back to 644!

**Comment by tassosm** [comment]
Permissions fixed. Why AppVeyor fails?

**Comment by yvesh** [comment]
@tassosm Not because of your PR, other issue. Just ignore it :)

**Comment by tassosm** [comment]
Thank you @yvesh

**Comment by tassosm** [comment]
Is this going to be merged before 3.7 release?

**Comment by dgt41** [comment]
@tassosm it's not even RTC (needs 2 people to test it)

**Comment by rdeutz** [comment]
> Is this going to be merged before 3.7 release?

no

**Comment by Sotiris-k** [comment]
I have tested this item :white_check_mark: successfully on 93335b19ccb72377a3241b76e4f5f8fc5d1b297e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by zero-24** [comment]
@tassosm can you take a look into the conflict too?

**Comment by Sotiris-k** [comment]
@zero-24 I may be wrong but judging from the AppVeyor's build log it seems like it failed for unrelated reasons

**Comment by zero-24** [comment]
I'm not talking about the tests I'm talking about the conflicts ;)
image

**Comment by andreasoee** [comment]
I have tested this item :white_check_mark: successfully on a85343a1c03576d6c29f121dc884dfdc0cb55040<br /><br />It works! thank you! ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by Sotiris-k** [comment]
I have tested this item :white_check_mark: successfully on a85343a1c03576d6c29f121dc884dfdc0cb55040<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Reverted back to pending as there's been functional code changes. Can we have tests again please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by Sotiris-k** [comment]
I have tested this item :white_check_mark: successfully on 5ed10ff3409f1c7fac157877e6b5e93bdd2b4fb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by andreasoee** [comment]
I have tested this item :white_check_mark: successfully on 5ed10ff3409f1c7fac157877e6b5e93bdd2b4fb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14007">issues.joomla.org/tracker/joomla-cms/14007</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by tassosm** [comment]
Since libraries/joomla/form/helper.php moved to libraries/src/Form/FormHelper.php by #17441 in Joomla 3.8, this fix is no longer available.

**Comment by wilsonge** [comment]
@laoneo looks like it got removed by https://github.com/joomla/joomla-cms/pull/16396/files#diff-35f4860b046f28ad5ca0748aae081179R452 any idea why?

**Comment by laoneo** [comment]
Guess I missed that one or the merge from staging into 3.8 at that time had a conflict. But I didn't do it on purpose.

**Comment by tassosm** [comment]
Is this going to be merged in 3.8 somehow or do I need to make a new PR?

**Comment by laoneo** [comment]
Yes, please make a new pr.

**Comment by tassosm** [comment]
I will. But in my humble view, asking for a PR for a bug that is already fixed doesn't seem right.

**Comment by ReLater** [comment]
Please review and test PR https://github.com/joomla/joomla-cms/pull/18222

**Comment by laoneo** [comment]
Thanks @ReLater!

**Pull request merged**
