### PR TITLE
[4.0] [Installation] Fix error when specifying a not existing database and not having privilege to create a new one

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #27924 .

### Summary of Changes

This PR adds handling of exceptions which are thrown by the installation's database model in routine createDatabase but never were caught and handled so that e.g. the bad connfiguration file after a bad attemt to create the database was not deleted.

#### Requirements

1. A database which fulfills the minimum server version requirements as they are
- MySql: 5.6
- MariaDB: 10.1
- PostgreSQL: 11.0
2. A database user who doesn **not** have the privilege to create a new database on that server with that kind of connection.
3. An existing, empty database suitable for a new Joomla installation for which the user mentioned in condition 2 does have all privileges needed for Joomla installation, e.g. create tables, or alternatively another database user who has the permission to create new databases.

#### Instructions

_Step 1:_ Start a new installation of a current 4.0-dev **without** the patch of this PR applied.

_Step 2:_ When coming to the database information, enter a valid server and a valid user name and password for a user who doesn't have the privilege to create databases. Enter a database name for which no database exists. When having filled out all fields, use the "Install Joomla >" button to start the installation.

_Result:_ Depending on the particular database driver you see a more or less meaningful error message.

_Step 3:_ Correct the database name so it fits to an existing database for which the previously entered user has all privileges required for a Joomla installation, or alternatively change user to one who has the privilege to create a new database. Then use the "Install Joomla >" button again.

Result: For MySQLi and MySQL (PDO): See section "Actual result" below. For PostgreSQL (PDO). it might be like described in section "Expected result".

_Step 4:_ Repeat steps 1 to 3 but this time **with** the patch of thos PR applied.

Result: See section "Expected result" below.

### Expected result

When entering a not existing database as database name in the installation form and a user who doesn't have the permission to create a database, you can correct database or user information after the error message and then continue with the installation by using again the "Install Joomla >" button.

### Actual result

When entering a not existing database as database name in the installation form and a user who doesn't have the permission to create a database, and then after the error message correct database or user information and start the installation again, it stops with an unspecified database error, at least when using MySQLi or MySQL (PDO). For PostgreSQL the error could not be reproduced before..
j4-installation-tweaks-1_3

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
Added release blocker label as inherited from issue #27924 .

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
Thanks @wilsonge .

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on e47670edbe352879744930d7703ec305e81344fe<br /><br />Tested successful with MySQLi<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28345">issues.joomla.org/tracker/joomla-cms/28345</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e47670edbe352879744930d7703ec305e81344fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28345">issues.joomla.org/tracker/joomla-cms/28345</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28345">issues.joomla.org/tracker/joomla-cms/28345</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks, too.

**Pull request merged**
