### PR TITLE
[plg_content_loadmodule] Prevent issues with regular expression characters

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #21329.

### Summary of Changes

This is an alternative to https://github.com/Rosie-Eagle/joomla-cms/pull/1 and https://github.com/joomla/joomla-cms/pull/21948.

This fixes the issue of module positions and modules with titles containing special regular expression characters not being loaded.

### Testing Instructions
Note, the use of `}` hasn't been fixed.

Copied from #21329 by franz-wohlkoenig:
1. Log in at the backend of joomla
2. Go to menu "Extensions > Modules".
3. Create a "Custom" module.
4. Give field 'title' the following value (without the quotes): "Some math: 1 + 1 = 2"
5. Save the module.
6. Next create a new article (or edit an existing one).
7. Make sure you can later view the article at the fronted of joomla, where visitors normally view the article.
8. Enter load module shortcode with your module type and title, e.g. `{loadmodule mod_custom, Some math: 1 + 1 = 2}`
11. Save the article.
12. View the article at the frontend of joomla.

Notice "{loadmodule mod_custom, Some math: 1 + 1 = 2}" not beeing replaced by the actual rendering of the module you created at steps 3 to 5. The text "{loadmodule mod_custom, Some math: 1 + 1 = 2}" is still there as if it were untouched.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 61ff38bd12a23bcd1e1145e283766db23435f348<br /><br />Module isn't rendered also by using this PR.

Note: Append a Module by click on "Module"-Button load it by ID, so this Problem didn't exist.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22034">issues.joomla.org/tracker/joomla-cms/22034</a>.</sub>

**Comment by SharkyKZ** [comment]
There's an error in testing instructions. The shortcode should contain module name, not just title. So, for example, `{loadmodule Some math: 1 + 1 = 2}` should become `{loadmodule mod_login,Some math: 1 + 1 = 2}`.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a30e151c4f064d53ca49ffa9727f13fadaac3c03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22034">issues.joomla.org/tracker/joomla-cms/22034</a>.</sub>

**Comment by HLeithner** [comment]
wouldn't it be easier to use preg_quote?

**Comment by SharkyKZ** [comment]
This was meant to be faster but now I'm wondering whether we need to use utf8 string functions from `Joomla\String\StringHelper` here.

**Comment by SharkyKZ** [comment]
No need to use utf8 functions. Works fine like this.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on c6c07d602a1a0c0cbcbba4260e80e2c1534218ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22034">issues.joomla.org/tracker/joomla-cms/22034</a>.</sub>

**Comment by jwaisner** [comment]
@franz-wohlkoenig Please test latest commit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22034">issues.joomla.org/tracker/joomla-cms/22034</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC as previous test still good (latest commits include only branch updates).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22034">issues.joomla.org/tracker/joomla-cms/22034</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
