### PR TITLE
fix media field in ISIS Template

### PR DESCRIPTION
**Pull request by nielsnuebel**
Pull Request for Issue #15917  .

### CODE REVIEW

**Comment by brianteeman** [comment]
Could you also update the compressed is file as well please

**Review by C-Lodder — COMMENTED** [review]
Don't need to make `$el` a variable. Just do:

`$(this).fieldMedia();`

**Comment by brianteeman** [comment]
@nielsnuebel please could you address the comment of @C-Lodder

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by Max00** [comment]
Works for me
Implemented manually for now

**Comment by ghost** [comment]
@Max00 please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/17205)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by Max00** [comment]
I have tested this item :white_check_mark: successfully on 8dd732d41c84c2a4079187aee1a897d6d8286fea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17205">issues.joomla.org/tracker/joomla-cms/17205</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 8dd732d41c84c2a4079187aee1a897d6d8286fea<br /><br />`Select` button works in a repeatable media form field.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17205">issues.joomla.org/tracker/joomla-cms/17205</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
