### PR TITLE
Remove redundant character escape "\" in RegExp

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Remove redundant character escape "\" in RegExp

### Testing Instructions

use bump.php :-) 

Also code review, here is a quick unit test where you can see it still compiles and gives the same result 

https://3v4l.org/39fil

### Actual result BEFORE applying this Pull Request

Everything works

### Expected result AFTER applying this Pull Request

Everything works

### Documentation Changes Required

None

### CODE REVIEW

**Comment by PhilETaylor** [comment]
appveyor build filling is unrelated to PR changes.

**Comment by HLeithner** [comment]
I hope you used a tool for this ;-) I will test this later thanks

**Comment by PhilETaylor** [comment]
Im just a very very critical person always looking for the smallest thing to complain about - apparently :)

**Comment by HLeithner** [comment]
That's good if you always (or at least sometimes) include the PR like here ;-)

**Comment by PhilETaylor** [comment]
Like I have said elsewhere, Sometimes its better to have 20 Issues raised that took the same time as 1 PR, as then Unlimited number of contributors can see the problems clearly documented, and can contribute to fixing the 20 issues reported and the project wins. Plus, it seems no one else is actually doing any structured strategic testing  of Joomla 4 apart from me. Plus I code for a day job, sometimes sat on the sofa infront of the TV, or on the kitchen table cooking for the kid its nice to have a change from code... and that is testing for me, and I seem to be kinda good at testing (very very critical person always looking for the smallest thing to complain about) as my track record shows (apparently)... haha

**Comment by gostn** [comment]
Title is ´[4]´, but its staging.

**Comment by PhilETaylor** [comment]
> Title is ´[4]´, but its staging.

Changed.

**Comment by PhilETaylor** [comment]
Closed as no chance of being merged after being kicked down the road this long.

**Pull request closed without merging**
