### PR TITLE
Proxy old phputf8 library path to new

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

This PR proxies the phputf8 library files located at `libraries/phputf8` to their counterparts at `libraries/vendor/joomla/string/src/phputf8` and removes all of the declared functions from these files.  Short of someone including this library themselves in yet another location, this should solve any reports dealing with its functions being redeclared.
#### Testing Instructions

To validate the proxy, add the following line to your template's index.php file:

``` php
require_once JPATH_PLATFORM . '/phputf8/mbstring/core.php';
```

This will import the file from the old location and should cause a deprecation log message telling you to use the new location.

Otherwise as there are no core uses of the old file path, things should just work.
#### Why `class_exists()` Checks on Logging?

This is a third party API and is 100% usable outside the context of Joomla.  The `class_exists()` checks keep it this way.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ccfad9a33a2e6acba82140ec4baa8aad1c199956<br /><br />Applied patch, turned debug on (in system config), turned debug plugin on with deprecated logs.
Edit a category, then edit a content.
Checked `logs/deprecated.php` and there are `Using the phputf8 library through ...` deprecated messages there.

So, tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9731">issues.joomla.org/joomla-cms/9731</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on ccfad9a33a2e6acba82140ec4baa8aad1c199956<br /><br />Applied patch, turned debug on (in system config), turned debug plugin on with deprecated logs.
Edit a category, then edit a content.
Checked logs/deprecated.php and there are Using the phputf8 library through ... deprecated messages NOT there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9731">issues.joomla.org/joomla-cms/9731</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman how did you have phputf8 messages in the deprecated.php log and they are not deprecated messages?!

Don't you have something like this?
`2016-04-04T16:04:32+00:00	WARNING ::ffff:XXX.XXX.XXX.XXX	deprecated	Using the phputf8 library through files located in /path/to/joomla-staging/libraries/phputf8 is deprecated, load the files from /path/to/joomla-staging/libraries/vendor/joomla/string/src/phputf8 instead.`

**Comment by brianteeman** [comment]
No - I will test again

On 5 April 2016 at 11:20, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> how did you have phputf8
> messages in the deprecated.php log and they are not deprecated messages?!
>
> Don't you have something like this?
> 2016-04-04T16:04:32+00:00 WARNING ::ffff:XXX.XXX.XXX.XXX deprecated Using
> the phputf8 library through files located in
> /path/to/joomla-staging/libraries/phputf8 is deprecated, load the files
> from /path/to/joomla-staging/libraries/vendor/joomla/string/src/phputf8
> instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9731#issuecomment-205744689>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Tested again - enabled deprecated logging
Applied patch
Edit article
Edit category
Nothing about utf8 in deprecate log

**Comment by brianteeman** [comment]
Sorry for confusion my first message should have said there are NO....

**Comment by polakluk** [comment]
I just tested this PR on my localhost and it is working. In my depreciated.php log, I can see the line advising users to load phputf8 from composer directory.

test

**Comment by mbabker** [comment]
@brianteeman If you have #9704 applied also that would cause log messages to not show.  The web application's redirect method is direct importing from the `libraries/phputf8` directory without that PR applied, so even if you're not getting the log messages but still able to navigate the UI when redirects happen this is "working", just can't explain why you're not getting the log messages.

**Comment by brianteeman** [comment]
No i dont have 9704 applied

**Comment by mbabker** [comment]
With #9704 merged testing instructions are changed.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 449ceb7d7673265b9e247da48957ac58160b0f24<br /><br />`Fatal error: Cannot redeclare utf8_strlen() (previously declared in /path/to/joomla-staging/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:23) in /path/to/joomla-staging/libraries/phputf8/mbstring/core.php on line 28`

With patch in deprecated.php log (global config debug = yes; debug plugin enabled with all logging)

`2016-04-19T15:32:07+00:00 WARNING [...] deprecated Using the phputf8 library through files located in /path/to/joomla-staging/libraries/phputf8 is deprecated, load the files from /path/to/oomla-staging/libraries/vendor/joomla/string/src/phputf8 instead.`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9731">issues.joomla.org/joomla-cms/9731</a>.</sub>

**Comment by mbabker** [comment]
@joomla/cms-maintainers this becomes more urgent to merge with the String package bumped to 1.4.0 because of autoloading of several of its files by the Framework's autoload definition.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 449ceb7d7673265b9e247da48957ac58160b0f24<br /><br />Tried again and tested ok - no idea what I did wrong before<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9731">issues.joomla.org/joomla-cms/9731</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9731">issues.joomla.org/joomla-cms/9731</a>.</sub>

**Pull request merged**
