### PR TITLE
[4.3] [a11y] Guided Tours table caption

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Apply changes from #38761 for guided tours
Remove `COM_GUIDEDTOURS_GUIDEDTOURS_TABLE_CAPTION` from sys file as it is only used by the component itself

### Testing Instructions

code review

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ac9cc2a400437c23f777a993cce9f59e51ac4859<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40301">issues.joomla.org/tracker/joomla-cms/40301</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ac9cc2a400437c23f777a993cce9f59e51ac4859<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40301">issues.joomla.org/tracker/joomla-cms/40301</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40301">issues.joomla.org/tracker/joomla-cms/40301</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 !

**Pull request merged**
