### PR TITLE
[5.0] Remove annoying "user not found" message

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes
Remove annoying "user not found" message. That show up every time when open list of content that created by removed user.

### Testing Instructions
Apply patch.
Create testing user.
Create an article with this user.
Delete testing user.
Open just created article to edit.

### Actual result BEFORE applying this Pull Request
Message, kind of "cannot load X user"

### Expected result AFTER applying this Pull Request
No message

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Would this solve issue #41008 ?

**Comment by laoneo** [comment]
And it needs some documentation.

**Comment by coolcat-creations** [comment]
It looks more like a quick fix then https://github.com/joomla/joomla-cms/pull/40751 - I feel like the other PR does not only solve the symptoms but also gives the opportunity for other extensions to hook in?

**Comment by Fedik** [comment]
> Would this solve issue 41008 ?

Sounds like

**Comment by HLeithner** [comment]
thanks, can we please get a documentation entry. and hope fully a full fix for "auto" replacement soon.

**Comment by Fedik** [comment]
Okay, added

**Pull request merged**
