### PR TITLE
fix Templates duplicate when name equal folder

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24295.

### Summary of Changes
replace happens only the in the filename

### Testing Instructions
see #24295

### CODE REVIEW

**Comment by ghost** [comment]
@chetanmadaan please test.

**Comment by HLeithner** [comment]
We need some tests for this.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e1bac880a18e54b326ae6b228c0a236ea3417c7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24316">issues.joomla.org/tracker/joomla-cms/24316</a>.</sub>

**Comment by ghost** [comment]
@chetanmadaan please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by hardik-codes** [comment]
I have tested this item :white_check_mark: successfully on c887169e91e2a23f02a154c94a5628ba57ff4f4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24316">issues.joomla.org/tracker/joomla-cms/24316</a>.</sub>

**Comment by ghost** [comment]
@Quy can you please retest?

**Comment by alikon** [comment]
no changes occured since @Quy, test except staging merge

**Comment by ghost** [comment]
@alikon sometimes only one or none check is shown. Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
