### PR TITLE
[4.0] Fix broken finder suggestion

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #31782 .

### Summary of Changes
Fix broken suggestion dropdown of smart search

### Testing Instructions
See #31782

### Actual result BEFORE applying this Pull Request
Suggestions do not work

### Expected result AFTER applying this Pull Request
Suggestions work.

### CODE REVIEW

**Comment by infograf768** [comment]
@bembelimen 
Works fine here. :)
You can now take off `use Joomla\String\StringHelper;` as it is no use anymore.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b4b52add67781b38d4912f49e5d9904c1c3f39bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31788">issues.joomla.org/tracker/joomla-cms/31788</a>.</sub>

**Review by richard67 — APPROVED** [review]
Mapping table suffix not needed anymore in J4 since in J4 there is only one mapping table left.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b4b52add67781b38d4912f49e5d9904c1c3f39bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31788">issues.joomla.org/tracker/joomla-cms/31788</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31788">issues.joomla.org/tracker/joomla-cms/31788</a>.</sub>

**Comment by wilsonge** [comment]
Thanks for fixing my merge conflicts!

**Pull request merged**
