### PR TITLE
[4.1] s/oder/order

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 739d9c06f5810b14735968115e094448f8d2ed25<br /><br />@bembelimen Could be merged by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36843">issues.joomla.org/tracker/joomla-cms/36843</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 739d9c06f5810b14735968115e094448f8d2ed25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36843">issues.joomla.org/tracker/joomla-cms/36843</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36843">issues.joomla.org/tracker/joomla-cms/36843</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
