### PR TITLE
[4.0] Fix width in com_modules batch position select

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #29910 .

### Summary of Changes
Fix the width of the position select in modules batch

### Testing Instructions
Check the batch in com_modules

### Actual result BEFORE applying this Pull Request
Select for positon is small

### Expected result AFTER applying this Pull Request
Select for positon is 100%

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4e92ad64c9ddfe460164b4174ee91e1a7a568b39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31831">issues.joomla.org/tracker/joomla-cms/31831</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4e92ad64c9ddfe460164b4174ee91e1a7a568b39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31831">issues.joomla.org/tracker/joomla-cms/31831</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31831">issues.joomla.org/tracker/joomla-cms/31831</a>.</sub>

**Comment by infograf768** [comment]
This indeed does the job in the description and that's why I tested it OK.

But I think we have a UX issue here. 
We should have a `- Keep Original Position -` display when we use the small `x` to kill the `:: None :: option`.
In fact it should be the default and not `:: None ::`

I mean when we empty the input field.
Screen Shot 2021-01-02 at 11 09 37

**Comment by wilsonge** [comment]
@infograf768 id agree with that. You able to do the patch?

**Pull request merged**
