### PR TITLE
Document use of @ error suppressor

### PR DESCRIPTION
**Pull request by PhilETaylor**
https://github.com/joomla/joomla-cms/pull/15592#discussion_r114782106
screen shot 2017-05-05 at 18 35 08

### CODE REVIEW

**Comment by zero-24** [comment]
isn't this comment true for all 3 usages of the @ in that method?

**Comment by PhilETaylor** [comment]
True - moved to docblock now

**Comment by zero-24** [comment]
I have just also added the missing *. Thanks.

**Comment by PhilETaylor** [comment]
cool no worries. 

I just dont want someone (aka without experience/without context) seeing all the error suppressing, and refactoring it in the future...

**Comment by elkuku** [comment]
I have tested this item :white_check_mark: successfully on 92f4714f80dd0e0bc9e1dcce769ecf116923d8f1<br /><br />I believe you have an extra blank line - @zero-24 might want to correct that? :wink: 

:+1: for expanding the "docs"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15814">issues.joomla.org/tracker/joomla-cms/15814</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on b2cee32f405cda8fa64280e120505e7196031c5f<br /><br />For me it is OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15814">issues.joomla.org/tracker/joomla-cms/15814</a>.</sub>

**Comment by elkuku** [comment]
I have tested this item :white_check_mark: successfully on b2cee32f405cda8fa64280e120505e7196031c5f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15814">issues.joomla.org/tracker/joomla-cms/15814</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@PhilETaylor please provide at least one sentence to explain what this is about, will make my life a bit easier

**Comment by PhilETaylor** [comment]
It will make no difference whatsoever to you or your life... now.

In 2 years time when some newbie refactors or removed the @ supressor and all hell breaks loose, then you would have been grateful of notes to stop a newbie refactoring/removing @ suppresors.

In my life, EVERY SINGLE use of an @surpressor should be documented as to why its being used, as 99% of the time you are doing something wrong if you are using one.  This use case is one of the 1% where its perfectly ok to use it, documenting that is better too. 

Like many experienced developers - I have wasted hours and hours debugging issues hidden by someone just using @ all throughout their code without knowing what they were doing. 

Notes/Documentation that stops developers in 2 years misunderstanding and creating issues is also a good thing. How many times has Joomla released bugs based on flawed understanding of the original intentions.

**Comment by rdeutz** [comment]
What are you talking about? I asked for one sentence explaining what this PR is about.

**Comment by brianteeman** [comment]
add inline documentation so that someone doesn't refactor to remove @ error suppression in the future.


a one line description as requested ;)

**Comment by PhilETaylor** [comment]
> What are you talking about? I asked for one sentence explaining what this PR is about.

So when I receive an email from you, out of context, how am I meant to know what you want :) 

screen shot 2017-05-05 at 18 17 48

**Comment by elkuku** [comment]
As title says?...

**Comment by rdeutz** [comment]
When I comment on a PR I am usually not speaking about the football match last weekend :-) Anyway, I hope you got the point.

**Comment by PhilETaylor** [comment]
> Anyway, I hope you got the point.

That you were too lazy to read. Yup. Got that thanks.

**Comment by rdeutz** [comment]
Seems not so I need to explain it a bit more. You added a link to another PR, why you made this PR was part of a discussion within the PR. So I had to figure out why you made this PR. Check if the intention and the PR are inline. I did it and I merged the PR. If that is lazy, then I don't know.

**Pull request merged**
