### PR TITLE
[4.0] System Information strings

### PR DESCRIPTION
**Pull request by brianteeman**
Update some strings for consistency

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d593bd4fd8ddda282883767f9dcbce630feade7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25587">issues.joomla.org/tracker/joomla-cms/25587</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8d593bd4fd8ddda282883767f9dcbce630feade7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25587">issues.joomla.org/tracker/joomla-cms/25587</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25587">issues.joomla.org/tracker/joomla-cms/25587</a>.</sub>

**Comment by wilsonge** [comment]
Today I learnt we had a cached media directory 🤔

**Comment by brianteeman** [comment]
@wilsonge so did iI

**Pull request merged**
