### PR TITLE
[4.0] Remove unused file

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #33860

This file is not used anywhere

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on f3e9737f9908fa364d589ecb3d8b8cdfba043a7a<br /><br />Confirm not used. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33864">issues.joomla.org/tracker/joomla-cms/33864</a>.</sub>

**Comment by Fedik** [comment]
@brianteeman please check also admin-field-edit-modal.js file, seems it also can be removed,
and this section:
https://github.com/joomla/joomla-cms/blob/e770fe3eae3bf7c762ddff2001443815fdf71c7a/build/media_source/com_fields/joomla.asset.json#L54-L76

**Comment by brianteeman** [comment]
@fedik thanks - good spot. I have updated the pr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b42d3ed3ab331a48b06483cc5eb0fba0640066a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33864">issues.joomla.org/tracker/joomla-cms/33864</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b42d3ed3ab331a48b06483cc5eb0fba0640066a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33864">issues.joomla.org/tracker/joomla-cms/33864</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33864">issues.joomla.org/tracker/joomla-cms/33864</a>.</sub>

**Comment by richard67** [comment]
The file removal in script.php should have been added more below, not in section "// 4.0 from Beta 7 to Beta 8" but in the meanwhile new one "// 4.0 from RC 1 to  RC 2", but that's just a formal thing to be consistent with the tool being under development and used used for generating the files and folder lists, and I can fix that later.

**Comment by richard67** [comment]
Thanks!

**Comment by richard67** [comment]
See #34521 for the files deletion on update.

**Comment by brianteeman** [comment]
@richard67 at the time the pull request was created the section was correct

**Comment by richard67** [comment]
@brianteeman Yes .. sometimes thinks take a while 😄

**Pull request merged**
