### PR TITLE
PNG Image Files Optimization

### PR DESCRIPTION
**Pull request by Dade88**
Lossless optimization of ALL Joomla PNG files. 301 files out of 541 were
definately changed to a smaller version.

66,28 KB Saved.

### CODE REVIEW

**Comment by zero-24** [comment]
@Bakual @rdeutz @roland-d @Kubik-Rubik @wilsonge can you do a PLT review here?

**Comment by rdeutz** [comment]
@Dade88 could you explain a bit how you did it, my guess is you used a tool to optimise the pictures. I don't think we can compare 300 pictures, so knowing how you did it would give me the confidence to support the merge.

**Comment by Dade88** [comment]
@rdeutz I have used a tool called PNGGauntlet, which make use of PNGOUT, OptiPNG and DeflOpt, compare the results and serves the best one. All tools have been configured for lossless compression. More info at https://en.wikipedia.org/wiki/Portable_Network_Graphics#Optimizing_tools

On a first try, I also tried to do the job via GIMP 'Save for Web' Plugin, however the results where not good as compressing images to PNG-8 results in poor results (most times, visible squared edges).

I might add I always used either this tools or GIMP without problems on my projects.

**Comment by AlexdeBorba** [comment]
This seems to be broken. I tried to apply the Patch and it returns a notice saying the patch was applied however while scrolling down on Joomla! Patch Tester, the patch appears "Not Applied".

**Comment by brianteeman** [comment]
If I remember correctly the patchtester can't be used for binary files
@mbabker

**Comment by mbabker** [comment]
Yep, about 15 months behind on the backlog :wink: https://github.com/joomla-extensions/patchtester/issues/8

**Comment by Dade88** [comment]
Is there anything I can do to solve this or it's some sort of dev team problem?

**Comment by zero-24** [comment]
>Is there anything I can do to solve this or it's some sort of dev team problem?

@Dade88 this is a know issue on the patchtester component your PR is fine here.

I hope @rdeutz can have a look into your comment and merge if it is ok for him: https://github.com/joomla/joomla-cms/pull/5743#issuecomment-71334460

Thanks :+1:

**Pull request merged**
