### PR TITLE
[4.1] Display doc icon based on mimetype

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
In Media Manager, documents are displayed as PDF icon. This PR displays the respective icon based on mimetype.

### Testing Instructions
Go to Media Manager.
Upload files of types txt, pdf, word, excel, powerpoint.

Thanks @dgrammatiko for the code!

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Quy please add any meaningful mime type needed here from: https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

**Comment by Quy** [comment]
The `i` icon confirms that the mimetype is correct, but it is still displaying the generic file icon. ???

**Comment by dgrammatiko** [comment]
Check that `fas fa-file-pdf`, etc actually exist, the code in the other PR was a bit of pseudo on terms of the actual font awsome classes

**Comment by Quy** [comment]
`fas fa-file-pdf` is correct and same as before the PR. It appears to not be detecting the mimetype thus defaulting to `fas fa-file`

**Comment by dgrammatiko** [comment]
Check what the actual mime type is `<span v-bind:class="getFileClass"  data-mime="{{ item.mime_type}}"/>`
Also add `break;` after each return <-- No don't do that, that's stupid

**Comment by Quy** [comment]
`<span class="fas fa-file" data-mime="{{item.mime_type}}"></span>`

**Comment by dgrammatiko** [comment]
Add it to line 16
```
    <div class="media-browser-item-info">
      {{ item.name }} {{ item.filetype }} {{item.mime_type}}
    </div>
```

**Comment by Quy** [comment]
{{ item.filetype }} = empty
{{ item.mime_type }} = application/pdf

**Comment by dgrammatiko** [comment]
Change `getFileClass: (item) => {` to `getFileClass() {`

**Comment by Quy** [comment]
> ReferenceError: item is not defined

```
  computed: {
    /* Get the hashed URL */
    getFileClass() {
      switch (item.mime_type) {
        case 'application/pdf':
          return 'fas fa-file-pdf';
        case 'application/msword':
        case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
          return 'fas fa-file-word';
        case 'application/vnd.ms-excel':
        case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
          return 'fas fa-file-excel';
        case 'application/vnd.ms-powerpoint':
        case 'application/vnd.openxmlformats-officedocument.presentationml.presentation':
          return 'fas fa-file-powerpoint';
        default:
          return 'fas fa-file';
      }
    },
  },
```

**Comment by dgrammatiko** [comment]
this.item then

**Comment by Quy** [comment]
Hallelujah! Thank you!!

**Comment by Quy** [comment]
Will redo later.

**Pull request closed without merging**
