### PR TITLE
[4.0] Fix markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add closing `</span>`.
Remove orphaned `</a>`.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 844f56461134f98b82e4ae380c0f3de052b10f45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33191">issues.joomla.org/tracker/joomla-cms/33191</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 844f56461134f98b82e4ae380c0f3de052b10f45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33191">issues.joomla.org/tracker/joomla-cms/33191</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33191">issues.joomla.org/tracker/joomla-cms/33191</a>.</sub>

**Comment by Quy** [comment]
Thanks for testing!

**Comment by brianteeman** [comment]
@wuy you really shouldnt merge your own PR. The person merging is the last check that the code is correct and you cant be that check if its your own pr

**Comment by brianteeman** [comment]
oops that should have been @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33191">issues.joomla.org/tracker/joomla-cms/33191</a>.</sub>

**Pull request merged**
