### PR TITLE
Fix session error

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31562.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 91c6c0bc03045a93e0a24e81446837807297197c<br /><br />tks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31563">issues.joomla.org/tracker/joomla-cms/31563</a>.</sub>

**Comment by infograf768** [comment]
Before I had here:
```
Oops! An Error Occurred

The server returned a "500 Whoops, looks like something went wrong.".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

after; all is fine.

**Comment by HLeithner** [comment]
Thanks

**Comment by alikon** [comment]
I have tested this item ✅ successfully on 91c6c0b
but unable to mark as tested on the issue tracker

**Pull request merged**
