### PR TITLE
[4.0] Add stricter comparison and unification of variable client_id

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes

 Add stricter comparison and unification of variable client_id in `administrator/components/com_modules/src/View/Modules/HtmlView.php`

### Testing Instructions

Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6f68a3d6beb04a6871f57950c5900d86b5059d81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30576">issues.joomla.org/tracker/joomla-cms/30576</a>.</sub>

**Comment by infograf768** [comment]
Maybe also change line 157 to
`->onclick("location.href='index.php?option=com_modules&amp;view=select&amp;client_id=" . $this->clientId . "'");`

**Comment by astridx** [comment]
> Maybe also change line 157 to
> `->onclick("location.href='index.php?option=com_modules&amp;view=select&amp;client_id=" . $this->clientId . "'");`


I wanted to avoid that because there could be conflict with https://github.com/joomla/joomla-cms/pull/30577. But have now added it.

**Comment by astridx** [comment]
Looks like not much are interested.

**Pull request closed without merging**
