### PR TITLE
[4.0] Namespace classes

### PR DESCRIPTION
**Pull request by hardik-codes**
### Summary of Changes
Used namespace classes in 
* ```installation/template/message.php```

### Testing Instructions
Code Inspection

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7aad6372a3afadf98a180d382ea5887bf8d867ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24225">issues.joomla.org/tracker/joomla-cms/24225</a>.</sub>

**Comment by mbabker** [comment]
Remove non-install changes or close per https://github.com/joomla/joomla-cms/issues/24188

**Comment by hardik-codes** [comment]
> Remove non-install changes or close per #24188

@mbabker Could you please elaborate which 'non-install changes' you are referring to ? I'll fix them asap.

**Comment by SharkyKZ** [comment]
Those in `com_privacy` and `com_userlogs`. They should be left alone for now as per request in #24188.

**Comment by hardik-codes** [comment]
@SharkyKZ @mbabker now have a look.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 73bde52bcebfb3abe7eea801798196ad04cf4900<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24225">issues.joomla.org/tracker/joomla-cms/24225</a>.</sub>

**Comment by ghost** [comment]
@Quy please retest.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
