### PR TITLE
[4.3][Guided Tours] Change URL label

### PR DESCRIPTION
**Pull request by Quy**
Partial fix for Issue #40020, #40021 .

### Summary of Changes
Change `URL` label to `Relative URL` to indicate relative and not absolute URL without having to read the inline help.

### Testing Instructions
Edit a tour.
See URL label.
Edit a step.
Change Type to Redirect.
See URL label.

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 5403f5081f4d435a0893b2075ba7eae301608ea9<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40119">issues.joomla.org/tracker/joomla-cms/40119</a>.</sub>

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 5403f5081f4d435a0893b2075ba7eae301608ea9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40119">issues.joomla.org/tracker/joomla-cms/40119</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40119">issues.joomla.org/tracker/joomla-cms/40119</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks @Quy

**Comment by brianteeman** [comment]
i thought we didnt change language strings in a patch release?

**Pull request merged**
