### PR TITLE
Exceptions in Joomla\CMS\Table\Usergroup refer to categories

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #21092 .

### Summary of Changes
remove todo that is clearly a copy paste error from somewhere else
change exception message to usergroups from catergory

NOTE the first exception` if ($this->id == 0)`
I am not sure if that should even be present - doesn't look like it to me - please advise

### CODE REVIEW

**Comment by mbabker** [comment]
> NOTE the first exceptionif ($this->id == 0)
> I am not sure if that should even be present - doesn't look like it to me - please advise

I'd say the text on it is bad.  Basically, if you don't pass something to the `$oid` param or `$this->load()` fails then that condition would be met.

**Comment by brianteeman** [comment]
suggestions for the text welcome

**Comment by mbabker** [comment]
"Usergroup not found" or "Could not load usergroup to delete" or something along those lines.  Either way it's definitely not something that needs a "Global" modifier.

**Review by mbabker — APPROVED** [review]

**Comment by wilsonge** [comment]
LGTM - thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
