### PR TITLE
[4.0] Fixing Suggestions in Finder/Smart Search

### PR DESCRIPTION
**Pull request by Hackwar**
The suggestions in Smart Search currently throw an error, because the controller can't find the right model. This fixes that.

## Testing instructions
1. Build the index in the backend.
2. Go to the frontend to the Smart Search view and type in "joo". Notice nothing is happening.
3. Apply patch
4. Type in "joo" and see that you get lots of suggestions.

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 2194013647d67c5f82b4ac3f99c402e97b42beeb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20523">issues.joomla.org/tracker/joomla-cms/20523</a>.</sub>

**Comment by infograf768** [comment]
Firefox: 
I lose focus when entering letters in the module field. I have to go back into it to add a letter.
finder_anim


And then, when I click on one of the results and click search I get a 404 and this
`1055 'joomla_db_finder.t.parent_id' isn't in GROUP BY `

**Comment by carlitorweb** [comment]
@infograf768 I think this bug you mention is for a new issue. This PR is just for match the right model.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2194013647d67c5f82b4ac3f99c402e97b42beeb<br /><br />For what it does, OK here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20523">issues.joomla.org/tracker/joomla-cms/20523</a>.</sub>

**Comment by Hackwar** [comment]
@infograf768 The search issue that you mentioned is fixed in #20185. This here is only about suggestions.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20523">issues.joomla.org/tracker/joomla-cms/20523</a>.</sub>

**Pull request merged**
