### PR TITLE
[4.0] Admin display password requirements

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #31113

In com_users when editing or creating a user in the admin there was no indicator of the sites password requirements

In com_admin view=profile there was no indicator of the sites password requirements

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 29ada620d0730df49d8dd655192856b969062567<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31217">issues.joomla.org/tracker/joomla-cms/31217</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 29ada620d0730df49d8dd655192856b969062567<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31217">issues.joomla.org/tracker/joomla-cms/31217</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31217">issues.joomla.org/tracker/joomla-cms/31217</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR but it keeps me from merging because I can't force merge. Have pinged maintainers. Other PRs for 4.0-dev have this problem, too, currently.

**Comment by HLeithner** [comment]
merging latest 4.0-dev branch should fixes the drone issue

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
