### PR TITLE
PHP polyfills as explicit dependency

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #39954

### Summary of Changes

Added `symfony/polyfill-php80` and `symfony/polyfill-php81` to composer json.
They already was in requirements, but implicitly.

### Testing Instructions
Apply patch, run `composer install`, make sure all works as before.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
drone failed

**Comment by Fedik** [comment]
I tried exact version, but composer complain it do not see `symfony/polyfill-php81` in lock file, or dron fail.
So I have no idea, and just updated these two :wink:

**Comment by Hackwar** [comment]
If there is a polyfill for 7.3, 8.0 and 8.1, is there also one for 7.4?

**Comment by Fedik** [comment]
Yes there is https://github.com/symfony/polyfill-php74
But I do not think that we use any of these 3 methods :wink:

**Comment by Fedik** [comment]
Maybe I better move it to 4.3, or?

**Comment by HLeithner** [comment]
@roland-d and @fancyFranci this is missing for 4.2.9

**Comment by fancyFranci** [comment]
Thanks! :)

**Pull request merged**
