### PR TITLE
[4.0] module assignment accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
Redo of #27635 as requested

### Summary of Changes
This PR addresses some of the issues for #23911

Specifically numbers
2, 4, 6

### CODE REVIEW

**Comment by brianteeman** [comment]
Maybe someone can convince the accessibility team to test this - they were the ones that requested these changes

**Comment by carcam** [comment]
I have tested this item :red_circle: unsuccessfully on c360d6fcb08a29d4d8fe1e5d6c0ad802b9fddaaf<br /><br />Hi Brian,
Thank you very much for your work on this. Unfortunately although your work helps on the resolution of the issue, it does not fix the issue completely as we have found these problems:

1. There is still an error resulting from using choices.js (Module Assignment option). When the user chooses one of the four options with an arrow, the page is immediately reloaded (context change without notice). A blind user does not know that the context has changed. (Failure of Success Criterion 3.2.2)
2. The "All" "None" links have been changed to buttons. But... we don't understand why the option buttons (radio) were not used here.  If there are buttons, they should have labels e.g. Select all/unselect all and expand all/collapse all. The change of labels should be dynamic and announced to the screen reader users 
3. We have a search field. The visually implicit user guesses from the layout that the field only applies to menu items. They also immediately see that the list of displayed items changes after entering the word they are looking for. A blind user does not see this and does not know that something has changed. 
4. The screen reader still does not announce in which menu I can select the items. For example, I have a group of Main menu items. The whole name "Main menu" should be a button with information whether it is collapsed or unfolded. And I get the information: Item list 1 toggle drop-down button collapsed. A blind user has no idea what the drop-down list is.     

Best!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28250">issues.joomla.org/tracker/joomla-cms/28250</a>.</sub>

**Comment by brianteeman** [comment]
I guess you didnt read the original post

**Comment by brianteeman** [comment]
Please review your failure report as far as i am concerned you are marking it as a failure based on a faulty assumption of what the pr does.

**Comment by carcam** [comment]
Hi Brian,
thank you very much for your comment. We marked this as faulty based on the  a11y tests we did after applying the patch.

If you think we should split this in several issues I will be happy to do it, but  as it was tested as a whole, maybe it makes sense to keep testing the whole issue.

Thanks!!

**Comment by brianteeman** [comment]
That assumes that this PR was to resolve every issue with module assignment. The description clearly states that it does not. So of course it does not fix things that are not in this pr. If only life was that easy.

So please follow regular practice and test what this PR does and report any issues with that (if any). Marking this as a failure because it doesnt fix something it is not intended to fix is simply wrong.

Finally glad to see after 2 months that the JAT is working again

**Comment by carcam** [comment]
Thank you Brian!!

Well the PR already fails 2 of the 3 points it tries to fix ;)

We will check on the other one whenever possible, but we'll probably  keep working on other issues as this PR cannot be merged without those fixes in any case.

Thanks!!

**Comment by brianteeman** [comment]
good luck, its clear you dont want to help by actually being constructive. I am closing this and look forward to your fixes

**Comment by carcam** [comment]
Hi Brian,
we do want to help and we actually provided test results for 2 of your 3 points and we will be glad to keep testing further proposals, but we also need to rationalize the resources we currently have ;)

Anyway thanks for your concerns.

Stay safe.

Best!!

**Comment by brianteeman** [comment]
So obviously I missed them in your completely unrelated reports.

Which 2 fail and why?
Do they fail because they dont work or do they fail because they dont do everything you want them to do?
After applying the pr is it better than it was without them.
Constructive testing is welcome anything else is just saying you can do better but you won't because you have better things to do with your time. Although I cant imagine what an accessibility team can give a higher priority to than to fixing accessibility issues

**Comment by carcam** [comment]
Hi Brian,
sorry for the misunderstanding.

You mention in your comment that this PR was addressing 2,4 and 6 of the original issue. On  that sense we have rechecked you may read our  report on 2 and 4:

2. The "All" "None" links have been changed to buttons. But... we don't understand why the option buttons (radio) were not used here. If there are buttons, they should have labels e.g. Select all/unselect all and expand all/collapse all. The change of labels should be dynamic and announced to the screen reader users

4. The screen reader still does not announce in which menu I can select the items. For example, I have a group of Main menu items. The whole name "Main menu" should be a button with information whether it is collapsed or unfolded. And I get the information: Item list 1 toggle drop-down button collapsed. A blind user has no idea what the drop-down list is.

>  After applying the pr is it better than it was without them.

I'm not sure if this applies. Is a step accessible for a wheelchair? Definitely not. Will make it a lower step more accessible? Well in some cases, but it will not be accessible yet ;)

As I said we  have very limited human resources right now, and we are working on other A11y requests we have for J4. And you are absolutely right when you say: "I cant imagine what an accessibility team can give a higher priority to than to fixing accessibility issues" So for sure we will address this ASAP ;)

Thank you very much!!

Stay safe!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28250">issues.joomla.org/tracker/joomla-cms/28250</a>.</sub>

**Comment by brianteeman** [comment]
2. The buttons do have labels

3. You are falling into the trap of using a screenreader when you can see and making assumptions on how a blind person uses it. https://incl.ca/should-sighted-developers-use-screenreaders-to-test-accessibility/

Finally a quote from Leonie Watson (bio https://tink.uk/about-leonie/)
"Accessibility doesn't have to be perfect, it just needs to be a little bit better than yesterday"

image

image

**Comment by carcam** [comment]
Hi Brian,
we cannot recheck our remarks about buttons as you closed your PR. If you kindly reopen it, we will be happy to check it again ;)

Thank you for the article link!! It's definitely some matter of thought about not relying on a single tool or process to have your things done. Specially since accesibility is such an opinionated experience which depends a lot on the user. Comments on the article are also really  insightful. Thanks!!

I kind of agree with the quote for the websites I own, but as we have the commitment of a fully accessible J4, we need to look further and try to make it better ;)

Stay safe!!

**Comment by brianteeman** [comment]
You will have to rebuilt as I have deleted the branch

There is no website in the world that is fully accessible. It is impossible to do. That's why all we can ever do is to make it better than it was yesterday. Leonie knows what she is talking about

**Comment by carcam** [comment]
Sorry you deleted it!!

Anyway, thank you very much  and  we do hope you send a new pr we can check.

Stay safe!!

**Comment by brianteeman** [comment]
No I will not be resubmitting it. You can rebuild it from here.

**Pull request closed without merging**
