### PR TITLE
[3]fix batch/copy on php 8

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #31467 .

### Summary of Changes
cast to int

### Testing Instructions
with php 8
Add some Categories, Articles, and Menu Items.
Use Batch in any of these to copy or move them.

### Actual result BEFORE applying this Pull Request

missing options

### Expected result AFTER applying this Pull Request

options are there as before

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9914ebf76d4949613be4d60491ccb1d372fafb61<br /><br />Tested successfully in 3.9.23 with PHP 8.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31536">issues.joomla.org/tracker/joomla-cms/31536</a>.</sub>

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on 9914ebf76d4949613be4d60491ccb1d372fafb61<br /><br />Works great. Thank you so very much! <3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31536">issues.joomla.org/tracker/joomla-cms/31536</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31536">issues.joomla.org/tracker/joomla-cms/31536</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
