### PR TITLE
Improve captcha empty error message

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #18450.

### Summary of Changes
Captcha empty error message is vague/unclear. This PR improves the error message.

### Testing Instructions
Enable reCAPTCHA for Contacts form.
Fill out form.
Leave captcha blank.
Submit form.
See error message.

### Expected result
Empty CAPTCHA solution not allowed.

### Actual result
Empty solution not allowed.

### CODE REVIEW

**Comment by brianteeman** [comment]
it is still not very "friendly" I am sure we can do better. The word "solution" just seems wrong.

How about 
> "Please complete the CAPTCHA."

**Comment by memonica** [comment]
I have tested this item :white_check_mark: successfully on 74bbeb98197a06316429bd6c1a467a51c799b664<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19051">issues.joomla.org/tracker/joomla-cms/19051</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 74bbeb98197a06316429bd6c1a467a51c799b664<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19051">issues.joomla.org/tracker/joomla-cms/19051</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

Thanks for tests.

**Pull request merged**
