### PR TITLE
[4.3][Guided Tours] When the input field has a value, enable the 'Next' button

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #40008.

### Summary of Changes

The 'Next' button in a step can never be disabled if the target input field has a value.
Little code refactoring as well.

### Testing Instructions

Run a tour, for instance 'Create a category'.
Once in the title field, the 'Next' button is disabled because the field is required.
Enter a value in the input field. 
The 'Next' button is not enabled.
Go to the next step and go back to the previous step.
The 'Next' button should still be enabled.
Remove the value in the input field.
The 'Next' button should be disabled.

### Actual result BEFORE applying this Pull Request

When returning to the step, the 'Next' button is disabled.
You need to give focus to the input field AND type something for the 'Next' button to be enabled.

### Expected result AFTER applying this Pull Request

When returning to the step, the 'Next' button is enabled because there is a value for the required input field.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on f36a7ba96f124096d66403cec664de81c0a7bb62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40062">issues.joomla.org/tracker/joomla-cms/40062</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 73ccccfd0fd6a0dc1b3dd9138a8cfe596bc73a85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40062">issues.joomla.org/tracker/joomla-cms/40062</a>.</sub>

**Comment by sdwjoomla** [comment]
I have tested this item :white_check_mark: successfully on 73ccccfd0fd6a0dc1b3dd9138a8cfe596bc73a85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40062">issues.joomla.org/tracker/joomla-cms/40062</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40062">issues.joomla.org/tracker/joomla-cms/40062</a>.</sub>

**Pull request merged**
