### PR TITLE
[5] Task parameter SessionGC removal

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue ##41608 .

### Summary of Changes
task param removal

### Actual result BEFORE applying this Pull Request
parameters not useful with the scheduler

### Expected result AFTER applying this Pull Request
works as expected

### CODE REVIEW

**Comment by HLeithner** [comment]
do we convert this parameters in the update script.php? if so I think we can remove this step too

**Comment by heelc29** [comment]
> do we convert this parameters in the update script.php? if so I think we can remove this step too

also from the installation sql file `installation\sql\xxx\extensions.sql`

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 67e5441d17cf1923c9f3ec20c86696a9fb76f6cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41685">issues.joomla.org/tracker/joomla-cms/41685</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 67e5441d17cf1923c9f3ec20c86696a9fb76f6cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41685">issues.joomla.org/tracker/joomla-cms/41685</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41685">issues.joomla.org/tracker/joomla-cms/41685</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
