### PR TITLE
web-installer

### PR DESCRIPTION
**Pull request by sabaturgay**
Pull Request for Issue #20608 .

### Summary of Changes

installed web installer and add  function onInstallerAddInstallationTab to webinstaller.php

### Testing Instructions
install => install from web plugin
Extensions => Plugins 
Search Tools => installer
Disable other installer plugins
Return install extensions page

### Expected result
Before fix: You should see error text
After fix: There should be no error text

### CODE REVIEW

**Comment by mbabker** [comment]
Not quite sure what the intent here is, but the install from web plugin is not part of the core package for 3.x releases and AFAIK there are no plans to include it in one.

If you are looking to make changes to the plugin, https://github.com/joomla-extensions/install-from-web-client is the repo to do that in.

**Comment by sabaturgay** [comment]
Hi, I dont want to insert web installer to joomla core. I just want to fix the issue and  I cant explain that how we can fix the issue without installing web installer plugin.

**Comment by mbabker** [comment]
Best advice I can give for that is to install the plugin locally, make your changes, then submit them as a pull request to the other repository I linked.  It'll be much easier to review the changes because it'll only be a comparison of the actual changes, whereas here it's just adding a bunch of new files which makes it difficult to review.

**Comment by sabaturgay** [comment]
Thank you for the advice. I will try it.

**Comment by roland-d** [comment]
Closing this in favor of https://github.com/joomla-extensions/install-from-web-client/pull/55

**Pull request closed without merging**
