### PR TITLE
Fix directory traversal for symlinked folders

### PR DESCRIPTION
**Pull request by smehrbrodt**
Pull Request for Issue #24539 .

### Summary of Changes

Fix directory traversal in com_media for symlinked "images" folder

### Testing Instructions

1. Set up Joomla with the "images" folder being a symlink
2. Create a new article
3. Try to set an intro image
4. Navigate to some folder in the media selector popup

### Expected result

You can traverse through the folders and select an image

### Actual result

Clicking on a folder does nothing

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by ghost** [comment]
@nonickch @joel-lupfer please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by HLeithner** [comment]
If found several other places with similar usages:

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/controllers/file.json.php#L97

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/controllers/file.php#L289

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/controllers/folder.php#L91

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/models/list.php#L117

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/controllers/file.php#L117

https://github.com/joomla/joomla-cms/blob/317784bedcd2c1a516ceccf8833e8085be86c005/administrator/components/com_media/controllers/folder.php#L201

**Comment by smehrbrodt** [comment]
> If found several other places with similar usages:

Great, but please let's chase them one by one so that each patch has clear and simple testing instructions.

**Comment by HLeithner** [comment]
We have to fix all or none.

**Comment by HLeithner** [comment]
And I want to merge this in to 3.9.6 so tests would be really appreciated.

**Comment by HLeithner** [comment]
@smehrbrodt are you planing to update your PR?

**Comment by smehrbrodt** [comment]
> @smehrbrodt are you planing to update your PR?

I have no idea how to test the other places, so I'll keep this patch just for the thing I tested.

**Comment by smehrbrodt** [comment]
@HLeithner if you are fine with blind fixes, I can update the other places too, but as said, no idea how to test them (or even give test instructions).

**Comment by ghost** [comment]
@HLeithner any comment?

**Comment by HLeithner** [comment]
I don't like to merge a pr that only fix the same problem on one position.

**Comment by mbabker** [comment]
> I don't like to merge a pr that only fix the same problem on one position.

And people don't like blindly patching code.  If someone wants to test that this same fix works for all lines of code that you pointed out, then sure, it can be included in a pull request.  Expecting a contributor to blindly change a pull request with additions that they have not tested is a little unfair, then again most pull requests end up with some form of scope creep around here.

**Comment by brianteeman** [comment]
I note the complete absence of any tests or comments by any of the people who demanded this change

**Comment by HLeithner** [comment]
> > I don't like to merge a pr that only fix the same problem on one position.
> 
> And people don't like blindly patching code. If someone wants to test that this same fix works for all lines of code that you pointed out, then sure, it can be included in a pull request. Expecting a contributor to blindly change a pull request with additions that they have not tested is a little unfair, then again most pull requests end up with some form of scope creep around here.

It was not my intention to get a blindly patched pr, till now I didn't found time to find out what is the use case is for each line that have to be patched. But yeah let fix one case and ignore all other is much better.

**Comment by mbabker** [comment]
> But yeah let fix one case and ignore all other is much better.

If that's all that has been tested so far then yes, that actually is better.  Again, if someone wants to test the same fix is valid for the other lines you pointed out then include it, otherwise without testing and validation it's blindly patching files.  I didn't when I spent 15 minutes coming up with this one-liner originally because the bug report was about traversing directories in the UI, there wasn't a bug report about any of the other write actions (probably because you couldn't execute them in the right context without this patch in the first place if I'm going to put a bet down on things).

**Comment by HLeithner** [comment]
I never said that we don't need correct test instructions.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 5704bc57fbcae360f1c0cfcf9026a181a1de7e16<br /><br />
- Tested with media manager: administrator/index.php?option=com_media
- Tested with article Intro Image

LAMP Server. PHP7.3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24723">issues.joomla.org/tracker/joomla-cms/24723</a>.</sub>

**Comment by ReLater** [comment]
But image upload doesn't work yet. But we know, as discussed above, that's not part of this pr.

`Error
Invalid folder provided.`

**Comment by nonickch** [comment]
@brianteeman I'm here, testing the PR now and I'll also look into all of the files @HLeithner mentioned. I'm pretty sure I can walk back from the files and find most (if not all) cases where they're being used.
I just come up with a PR, right?

**Comment by nonickch** [comment]
Confirming that this PR solves the original report of Issue #24539 .

Also I went through all of the 3.9.5 diffs and I agree/confirm with the list of files @HLeithner listed as needing the same kind of fix so we can address the entire set of issues.
Working on a PR for that.

Please note that I haven't checked for any pre-3.9.5 "realpath" usages, but given that the whole issue was due to an addition to a security fix 3.9.5 and that I haven't noticed any issues on our platform before, I feel relatively comfortable not going through the entire codebase

**Comment by ghost** [comment]
@nonickch please mark your test as successfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by HLeithner** [comment]
@nonickch any progress on your PR?

**Comment by nonickch** [comment]
Not yet, sorry for the delay everyone, I'm a bit swamped these days.
I'll have a go at it tomorrow while I mark my test complete as well (never used the test plugin before).

**Comment by nonickch** [comment]
Made my PR at #24924 that references all locations @HLeithner spotted.
This implies that the contents of this PR is also present there.

**Comment by Quy** [comment]
Closing in favor for PR #24924.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24723">issues.joomla.org/tracker/joomla-cms/24723</a>.</sub>

**Pull request closed without merging**
