### PR TITLE
fixed mobile menu yet again

### PR DESCRIPTION
**Pull request by C-Lodder**
I just noticed today that the previous commit I submitted before caused some issue with the sub-menu dropdowns. The height was not adjusting accordingly, but have fixed that now.

https://github.com/joomla/joomla-cms/pull/5913

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this in any way connected to the report here #6174 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6190">issues.joomla.org/joomla-cms/6190</a>.</sub>

**Comment by C-Lodder** [comment]
@brianteeman - yes, that will probably be it.

**Comment by hans2103** [comment]
Will test it tomorrow

**Comment by wilsonge** [comment]
@test unsuccessful. Clicking on a item then moving to another menu item seems to happen on hover as a result of this patch. Furthermore the original bug (that was fixed with #5913) is now back again

**Comment by C-Lodder** [comment]
@wilsonge - Not to worry, fixed it. Will commit tomorrow

**Comment by brianteeman** [comment]
Note to testers: The cache on mobile browsers is VERY persistent so dont
forget to clear it manually

On 27 February 2015 at 09:19, Lodder <notifications@github.com> wrote:

> @wilsonge <https://github.com/wilsonge> - Not to worry, fixed it. Will
> commit tomorrow
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6190#issuecomment-76361010>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by hans2103** [comment]
patch succesfully tested on smartphone. Will test new code when committed.

**Comment by C-Lodder** [comment]
updated PR

**Comment by hans2103** [comment]
@test unsuccessful on iPhone 5 with Chrome
@test successful on iPhone 5 with Safari

Using Safari the div for submenu enlarges giving me the ability to scroll down for all submenus
Using Chrome the div for submenu doesn't enlarge dynamicly. I'm not able to scroll for all submenus.

**Comment by C-Lodder** [comment]
Thanks for the feedback @hans2103. I'll try and sort it for chrome over the weekend

**Comment by wilsonge** [comment]
@C-Lodder any updates on this?

**Comment by C-Lodder** [comment]
@wilsonge not yet. I'm not sure if any changes were made to the menu as I have no yet compared it to the default Bootstrap one. This is just a weird one as it's not normal behavior for the Bootstrap menu.

**Comment by nonumber** [comment]
I think the solution to this is not via css but html:
Just add the class ```collapsed``` to the ```btn-navbar``` link and ```collapse``` to the ```nav-collapse``` div.
```
			<?php if ($this->params->get('admin_menus') != '0') : ?>
				<a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
			<?php endif; ?>

			<a class="admin-logo <?php echo ($hidden ? 'disabled' : ''); ?>" <?php echo ($hidden ? '' : 'href="' . $this->baseurl . '"'); ?>><span class="icon-joomla"></span></a>

			<a class="brand hidden-desktop hidden-tablet" href="<?php echo JUri::root(); ?>" title="<?php echo JText::sprintf('TPL_ISIS_PREVIEW', $sitename); ?>" target="_blank"><?php echo JHtml::_('string.truncate', $sitename, 14, false, false); ?>
				<span class="icon-out-2 small"></span></a>

			<div<?php echo ($this->params->get('admin_menus') != '0') ? ' class="nav-collapse collapse"' : ''; ?>>
```

**Comment by zero-24** [comment]
Closing as we have @nonumber's PR that is successful tested and RTC now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6190">issues.joomla.org/joomla-cms/6190</a>.</sub>

**Pull request closed without merging**
