### PR TITLE
[3.9] missing closing tag in string

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

add closing link tag.

### Testing Instructions

.

### Expected result

<a href='https://docs.joomla.org/J3.x:User_Action_Logs' target='_new'>User Action Logs documentation.</a>
### Actual result

<a href='https://docs.joomla.org/J3.x:User_Action_Logs' target='_new'>User Action Logs documentation.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c216cded572b47c238569649ca02232ef5f637df<br /><br />Tested by code review. Error is obvious and fixed by this PR here in the right way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22027">issues.joomla.org/tracker/joomla-cms/22027</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c216cded572b47c238569649ca02232ef5f637df<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22027">issues.joomla.org/tracker/joomla-cms/22027</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22027">issues.joomla.org/tracker/joomla-cms/22027</a>.</sub>

**Comment by tecpromotion** [comment]
Commit message is a bit ugly formated.
Sorry. There is a missing closing a-tag in line 53.

**Comment by infograf768** [comment]
> Sorry. There is a missing closing a-tag in line 53.

???

**Comment by jeckodevelopment** [comment]
>     Sorry. There is a missing closing a-tag in line 53.
???

@infograf768 i think that he's talking about the "PR description". No worries, PR is good to go.

**Comment by zero-24** [comment]
Merging thanks!

**Pull request merged**
