### PR TITLE
[5.1] Fix content history diff error

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR fixes a JS error when trying to view the "diff" between content versions, due the dependency not being called.

### Testing Instructions

1. Ensure "Versions" is enabled
2. Create an article with some dummy content and save it
3. Add or remove some content to the same article as save it
4. Compare the two versions of the article

### Actual result BEFORE applying this Pull Request

> Uncaught TypeError: window.Diff is undefined

before

### Expected result AFTER applying this Pull Request

The diff is displayed, showing green/red blocks

after

### Note

I'm aware the diff fails a11y standards for dark mode, but this should be fixed in a separate PR

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9025a911eec6beea38f69ddd2724f65b15ed47f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42755">issues.joomla.org/tracker/joomla-cms/42755</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9025a911eec6beea38f69ddd2724f65b15ed47f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42755">issues.joomla.org/tracker/joomla-cms/42755</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42755">issues.joomla.org/tracker/joomla-cms/42755</a>.</sub>

**Comment by crimle** [comment]
I have tested this item :red_circle: unsuccessfully on 1eb9c687968ffba8d73d3dfb2439b96ce46168a6<br /><br />Pressing [Apply Patch] results in error message:
«There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.»<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42755">issues.joomla.org/tracker/joomla-cms/42755</a>.</sub>

**Comment by Nuyonuyonoina** [comment]
"Apply patch" button doesn't work. Error message is "There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation."

**Comment by eddiekonczal** [comment]
I have tested this item :red_circle: unsuccessfully on 1eb9c687968ffba8d73d3dfb2439b96ce46168a6<br /><br />Cannot apply patch.

Also, actual error is:

Uncaught TypeError: Cannot read properties of undefined (reading 'diffWords')
    at l (admin-compare-compare.min.js?907a40:4:169)
    at admin-compare-compare.min.js?907a40:4:566
    at Array.forEach (<anonymous>)
    at HTMLDocument.c (admin-compare-compare.min.js?907a40:4:554)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42755">issues.joomla.org/tracker/joomla-cms/42755</a>.</sub>

**Comment by Quy** [comment]
@eddiekonczal FYII: PRs with `NPM Resource Changed` label cannot be tested with PatchTester.

**Comment by richard67** [comment]
@crimle @Nuyonuyonoina @eddiekonczal I will reset the negative test results as they are not caused by this PR. The PR modifies an NPM dependency, which can be seen by the label "NPM Resource Changed". Such PRs can't be tested with Patchtester, they require either a development environment with composer and NPM, or they need to be applied by using the packages created by drone, which can be found in the "Downloads" section of the integration checks at the bottom of the PR.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
