### PR TITLE
[4.0] enforce tfa

### PR DESCRIPTION
**Pull request by brianteeman**
#26253 added the ability to enforce the use of two factor authentication. However as pointed out in #29298 "the admin could be excused in thinking that is all he needs to do... however, enabling this doesn't actually enforce 2FA ... because the 2FA plugins are disabled by default."

This simple pr adds a description to the field in the user options

image

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on bc5a8457d33084febe88fbdad55c53d5aa99082d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34176">issues.joomla.org/tracker/joomla-cms/34176</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bc5a8457d33084febe88fbdad55c53d5aa99082d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34176">issues.joomla.org/tracker/joomla-cms/34176</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34176">issues.joomla.org/tracker/joomla-cms/34176</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
