### PR TITLE
[4.0] Improve sample tags

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Tags in blog sample data form a phrase. But not a good one.

### Testing Instructions
Install blog sample data on your site and compare the fronted before and after patch.

### Actual result BEFORE applying this Pull Request
tags-before

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
What a lovely hidden secret

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9a10597815b3beba5f8510622cf6b78cacbfd826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33502">issues.joomla.org/tracker/joomla-cms/33502</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9a10597815b3beba5f8510622cf6b78cacbfd826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33502">issues.joomla.org/tracker/joomla-cms/33502</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
