### PR TITLE
[4.0] Labels dont have a :

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR for consistency

code review

### CODE REVIEW

**Comment by infograf768** [comment]
Looks OK. OK also for the deleting of unused strings.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d5c5261faf6371f0b2c076f2563f52c969e85f20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26215">issues.joomla.org/tracker/joomla-cms/26215</a>.</sub>

**Comment by ghost** [comment]
@infograf768 can i count your comment as successfully test?

@brianteeman can you please resolve conflicting files?

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 642908de122d211ebd5e199c15426ecd0d68729f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26215">issues.joomla.org/tracker/joomla-cms/26215</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26215">issues.joomla.org/tracker/joomla-cms/26215</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
