### PR TITLE
Update for Tooltips

### PR DESCRIPTION
**Pull request by Werbschaft**
Must be called again that a HTML Tooltip is possible! Some people disable HTML in Tooltips for not registered Users cause of XSS Attacks!
So for registered Users I think it's ok to use HTML in Tooltips, but for all other I always disable HTML which breaks then the Layout ...

Check this in the Tracker: http://issues.joomla.org/tracker/joomla-cms/6177

Bootstrap itself says:
"""If false, jQuery's text method will be used to insert content into the DOM. Use text if you're worried about XSS attacks."""

### CODE REVIEW

**Comment by n9iels** [comment]
@test confirmed, if you work with a template that has not enabled html tooltips this patch solves the issue. I think this bug appears because the tooltips of module editing are not made with the standard Bootstrap tooltip.

Is it necessary to make this change also in frontend-editing.js, the compressed version?

**Comment by WS-Theme** [comment]
Yes, this Fix must also be done in compressed Version. Thanks a lot!

**Comment by brianteeman** [comment]
Please update the non-compressed js file with these changes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6179">issues.joomla.org/joomla-cms/6179</a>.</sub>

**Comment by n9iels** [comment]
Thanks for updating, please push the file changes to this PR. Now you only Referenced them ;-)
One more tester needed here! :smiley:

**Comment by WS-Theme** [comment]
Hi there,

sorry but I have no well skills on GitHub, how to do this :-D Sorry

**Comment by n9iels** [comment]
You did it nearly correct, the only mistake is that you made the changes not in the patch-1 branche. What you have to do:
1) Go to your Fork (copy) of the joomla-cms, in your case thats located on: https://github.com/WS-Theme/joomla-cms
2) Left of the title <i>joomla-cms / +</i> you will find a select box. Select the option: patch-1
Now your switching to the patch-1 branche. You can see this as a workplace directly connected to this Pull Request
3) Make your changes to the compressed frontediting.js and save you file. You don't have to change the frontediting-uncompressed.js, because that one is allready done.
4) If you do this right, it will be autmaticly added to this Pull Request

After that, we just need one person to test your solution (patch). When two people tested this patch succesfull it can be set to RTC (Ready to Commit) and finally Merged to the Joomla! CMS

If you have any farther questions, feel free to ask :)

**Comment by WS-Theme** [comment]
Hi n9iels,

wow, thanks for this awesome tutorial about how to manage it :-) I think it's correct now!!

I have also changed the uncompressed Version cause I have studied line by line and have seen that the Tooltip has two instances and one was missing!!

I hope now is all ok and sorry that it won't work on the first run ;)

Cheers, Oli

**Comment by n9iels** [comment]
Yes you did it correct!

@test Works completely fine now!
Note: this patch can not be tested on the standard protostar template, please test on another template with Bootstrap 3 included<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6179">issues.joomla.org/joomla-cms/6179</a>.</sub>

**Comment by nueckman** [comment]
Works like expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6179">issues.joomla.org/joomla-cms/6179</a>.</sub>

**Comment by brianteeman** [comment]
Multiple tests - setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6179">issues.joomla.org/joomla-cms/6179</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
