### PR TITLE
[4.0] JRegisty typo

### PR DESCRIPTION
**Pull request by brianteeman**
Obvious typo in param docblock

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 316f5e0307d22bc83dc130643d8c68cd14346ba4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33032">issues.joomla.org/tracker/joomla-cms/33032</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 316f5e0307d22bc83dc130643d8c68cd14346ba4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33032">issues.joomla.org/tracker/joomla-cms/33032</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33032">issues.joomla.org/tracker/joomla-cms/33032</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
