### PR TITLE
Add more options to the sort table count

### PR DESCRIPTION
**Pull request by jppcel**
Pull Request for Issue #9776.
#### Summary of Changes

Adds new values 200 and 500 to the default list limit

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated title and description<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Comment by Bakual** [comment]
This needs the strings also added in the language files:
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.ini#L19-L34 and
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.ini#L13-L33

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 28de989abbbdb932cfa882acf505faf09889016a<br /><br />Missing language string

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Comment by brianteeman** [comment]
screen shot 2016-04-08 at 08 31 52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Comment by jppcel** [comment]
I updated the archive with the new strings...

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on f4ad04a4a3c7dc235e31869072bab9b2fdc46d6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f4ad04a4a3c7dc235e31869072bab9b2fdc46d6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Comment by brianteeman** [comment]
Setting to needs review for the maintainers to make a decision. As noted elsewhere setting a large limit can produce timeouts on some server configurations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9800">issues.joomla.org/joomla-cms/9800</a>.</sub>

**Pull request merged**
