### PR TITLE
[4.0] Fix wrong aria usage accordion view

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #29924.

### Summary of Changes
The accordion view is still using tab-aria syntax.

Code provided by @angieradtke. 

### Testing Instructions
Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on dda3952c98e860113a70ec76ecc710ea702da9a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30216">issues.joomla.org/tracker/joomla-cms/30216</a>.</sub>

**Comment by brianteeman** [comment]
Sorry code review really is not enough. Where is this code being used so that it can be tested correctly

**Comment by chmst** [comment]
@brianteeman select menu types is an accordion

**Comment by brianteeman** [comment]
@chmst thank you

**Comment by brianteeman** [comment]
There is no question that after this PR the behaviour of selecting menu types is improved (and probably can be improved further with lists instead of a bunch of links) my question is whether this is the right file to change.

The code being changed is
> Add javascript support for Bootstrap accordions and insert the accordion

surely therefore this file should not be changed and we should have our own code for the accordion??

**Pull request closed without merging**
