### PR TITLE
[4.0] Fix issues when people don't enter the right information in the installer

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #18557 .

### Summary of Changes
Changes how json issues are returned so everything in the CMS runs through the main application rather than echo'ing json and trying to run `$app->close` which we sometimes do in core to work around bad plugins - we don't have these in the installer and it makes the logic much clearer

Fixes how responses from `dbcheck` are handled - there is now an error shown and installation stopped when things go wrong in the installer

Note the UX isn't great because the error is displayed at the top of the page and you have to scroll all the way up to the top to see that. But I'm not a frontender - so I'll leave that for a subsequent PR from @ciar4n or @C-Lodder - this at least means things are functional

// cc @laoneo as you wrote some of this JSON error handling

### Testing Instructions
Enter incorrect database credentials into the installer

### Expected result
It bails

### Actual result
Configuration file is written and you have to remove configuration.php to ever do anything again.

### Documentation Changes Required
None

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 1c70e52002be8d90b26f3681ba0de3dc8f7a571f

Installation of [18958.zip](https://github.com/wilsonge/joomla-cms/archive/fix-installation-checker.zip) using wrong Database-Information (wrong user and wrong Password) got:

bildschirmfoto 2017-12-08 um 13 34 49

No Way found to go a Step return an use correct Informations.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18958">issues.joomla.org/tracker/joomla-cms/18958</a>.</sub>

**Comment by laoneo** [comment]
I have the same behavior with and without the patch.

**Comment by wilsonge** [comment]
Can you try again please?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 7fb758aa141da802f3f80c5b482cff645c2959ae<br /><br />Works now, except the UI which is not rendered correctly as pointed already out in the pr description.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18958">issues.joomla.org/tracker/joomla-cms/18958</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 7fb758aa141da802f3f80c5b482cff645c2959ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18958">issues.joomla.org/tracker/joomla-cms/18958</a>.</sub>

**Comment by dgrammatiko** [comment]
@laoneo rtc, merge it

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks guys :)

**Pull request merged**
