### PR TITLE
[4.0] Fix subform: add row at correct position

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #34374 .

### Summary of Changes

Fixing how the subform script add new row

### Testing Instructions

please follow #34374

### Actual result BEFORE applying this Pull Request

row added at the end, always

### Expected result AFTER applying this Pull Request

row added below "current" row

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9857e73d2b89cad92a7484eb90044e595d9df8b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34402">issues.joomla.org/tracker/joomla-cms/34402</a>.</sub>

**Comment by nozaro33** [comment]
I have tested this item successfully via manual update of files

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34402">issues.joomla.org/tracker/joomla-cms/34402</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
