### PR TITLE
[4.0] Get categories from component

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/26157#issuecomment-529189354.

### Summary of Changes

Get categories from component instead of using deprecated `JCategories::getInstance()`.

### Testing Instructions

Create a custom field for articles.
Assign to `Uncategorised` category.
Create an article. Select `Uncategorised` category.
Check that custom field appears in form.

### Expected result AFTER applying this Pull Request

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 827a8d556404b1b0dbee7593f58abe595a3c606c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30613">issues.joomla.org/tracker/joomla-cms/30613</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 827a8d556404b1b0dbee7593f58abe595a3c606c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30613">issues.joomla.org/tracker/joomla-cms/30613</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30613">issues.joomla.org/tracker/joomla-cms/30613</a>.</sub>

**Comment by wilsonge** [comment]
Will this still work on J3 style components that don't use services?

**Comment by SharkyKZ** [comment]
It should. Legacy components implement `Joomla\CMS\Categories\CategoryServiceInterface`.

https://github.com/joomla/joomla-cms/blob/a5cd87afc9555511a3ef808f644b01780f0b15d0/libraries/src/Extension/LegacyComponent.php#L37-L40

Works with Weblinks 3.7.0.

**Comment by wilsonge** [comment]
Cool - thanks!

**Pull request merged**
