### PR TITLE
Fix regression in script render (async/defer attributes when directly modifying _scripts property)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.

### Summary of Changes

If an extension has acessing the `JDocument::_scripts` public property, with the changes in the script render it can now cause the script to add async and defer attributes, even if set to false.

This PR intends to correct that.

### Testing Instructions

1. Code review
2. Add to your template index.php (protostar/isis)
```php
$this->_scripts = array_merge(array('/test3.js' => array('mime' => 'text/javascript', 'defer' => '', 'async' => '')), $this->_scripts);
$this->_scripts = array_merge(array('/test2.js' => array('mime' => 'text/javascript', 'defer' => false, 'async' => false)), $this->_scripts);
$this->_scripts = array_merge(array('/test1.js' => array('mime' => 'text/javascript', 'defer' => true, 'async' => true)), $this->_scripts);
```
- Notice the results are different in 3.6.4 and in 3.7.0 staging (which are incorrect).

```html
<!-- 3.6.4 -->
<script src="/test1.js" defer async></script>
<script src="/test2.js"></script>
<script src="/test3.js"></script>

<!-- 3.7.0 -->
<script src="/test1.js" defer async></script>
<script src="/test2.js" defer async></script>
<script src="/test3.js" defer async></script>
```
- Apply patch, notice the results on 3.7.0 staging are now the same as 3.6.4

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
can anyone please test this?
@wilsonge @zero-24 maybe a release blocker here?

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 06fb68c0898a285718177f69851bb11b134ff7b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13081">issues.joomla.org/tracker/joomla-cms/13081</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 06fb68c0898a285718177f69851bb11b134ff7b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13081">issues.joomla.org/tracker/joomla-cms/13081</a>.</sub>

**Comment by dgt41** [comment]
RTC
Thanks @andrepereiradasilva

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
