### PR TITLE
[imp] Added a validation message for the URL field when schema is not provided

### PR DESCRIPTION
**Pull request by marrouchi**
Pull Request for Issue #13870.

### Summary of Changes
Added a validation message to the JFormRuleUrl class.

### Testing Instructions
1. Create a url field : fill schema and make sure it's not relative
2. Create a new content and fill the url field with a domain name (example.com).
### Expected result
A warning message displays "Invalid URL : URL schema is missing in example.com. Please add one of the following at the begining : http...." with no explanation.
### Actual result
A warning message displays "Invalid field" with no explanation.
### Documentation Changes Required
No.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c0048b4958612240ff5e5e1d9cde2e3911456a8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13885">issues.joomla.org/tracker/joomla-cms/13885</a>.</sub>

**Comment by justinherrin** [comment]
Just a minor spelling typo to correct...
"Invalid URL : URL schema is missing in %s. Please add one of the following at the begining : %s."

Should be...
"Invalid URL : URL schema is missing in %s. Please add one of the following at the **beginning** : %s."

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c1636c2f1a15af5a31fd38e0269753d8ce48dda1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13885">issues.joomla.org/tracker/joomla-cms/13885</a>.</sub>

**Comment by infograf768** [comment]
Please use ordered variables in the string
"Invalid URL : URL schema is missing in %1$s. Please add one of the following at the beginning : %2$s ."
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13885">issues.joomla.org/tracker/joomla-cms/13885</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 19a0e9f596f82bc8a5e626e450bdb47440f0927f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13885">issues.joomla.org/tracker/joomla-cms/13885</a>.</sub>

**Comment by marrouchi** [comment]
RTC please

**Comment by infograf768** [comment]
RTC as the change in the string concerns only the type of variable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13885">issues.joomla.org/tracker/joomla-cms/13885</a>.</sub>

**Pull request merged**
