### PR TITLE
[3.10] Privacy Consent wording I agree and No

### PR DESCRIPTION
**Pull request by pritam825**
Pull Request for Issue #22198 .

### Summary of Changes
see #22198 

Testing Instructions

Actual result BEFORE applying this Pull Request

Screenshot (2031)

Expected result AFTER applying this Pull Request
'No' is replaced by 'I do not agree'

### CODE REVIEW

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 1ab91f1dd58d65c5ba8ece71b1cdbca73aa4dcba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37181">issues.joomla.org/tracker/joomla-cms/37181</a>.</sub>

**Comment by richard67** [comment]
@zero-24 Do we really want to change that in 3.10? Or shouldn't that be moved to 4.1? Or maybe even 4.2?

**Comment by brianteeman** [comment]
Its just a string change and it can be considered a bug fix so no reason (in my mind) for it not to go in a patch release.

As for it going in 3.10 - its a bug fix not a feature so why not?

**Comment by Ravi-chandra69** [comment]
I have tested this item :white_check_mark: successfully on 1ab91f1dd58d65c5ba8ece71b1cdbca73aa4dcba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37181">issues.joomla.org/tracker/joomla-cms/37181</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37181">issues.joomla.org/tracker/joomla-cms/37181</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks.

**Pull request merged**
