### PR TITLE
[4.0] Fix com joomlaupdate

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #16376 .

### Summary of Changes
This PR fixes the issue #16376. com_cache was namespaced, so the code in JoomlaInstallerScript of com_admin needs to call the namespace class

Also, the default view in com_joomlaupdate was renamed to joomlaupdate (because Default could not be used in class name), so the the update controller in that component needs to be updated to the new view name

### Testing Instructions
1. Follow the issue description to see the issue
2. Apply patch, confirm that the issue fixed

I already tested it myself, so maybe it could be merged by code review to save time of testers

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on a1c10b11310409f33f32989bb26df47f2f9006f9<br /><br />same Behaviour as described in #16376<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16388">issues.joomla.org/tracker/joomla-cms/16388</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on a1c10b11310409f33f32989bb26df47f2f9006f9<br /><br />same Behaviour as described in #16376<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16388">issues.joomla.org/tracker/joomla-cms/16388</a>.</sub>

**Comment by joomdonation** [comment]
Could you please test it using my branch https://github.com/joomdonation/joomla-cms/archive/fix_com_joomlaupdate.zip ?

**Comment by franz-wohlkoenig** [comment]
will test.

**Comment by franz-wohlkoenig** [comment]
same Result using your Branch. Can this depend its a multilanguage Site?

**Comment by joomdonation** [comment]
No, it should not. Could you please zip the file administrator\components\com_admin\script.php and upload it here? I am thinking that the patch was not applied properly for some reason.

**Comment by franz-wohlkoenig** [comment]
Nightly Build: administrator\components\com_admin\[script.php.zip](https://github.com/joomla/joomla-cms/files/1041678/script.php.zip)

**Comment by franz-wohlkoenig** [comment]
Fine at my End, lets hope for another Tester.

**Comment by wilsonge** [comment]
I've manually fixed the view name part as I know we changed that name so it's clearly correct. https://github.com/joomla/joomla-cms/commit/15d495b474e97a5a80c7aa85a9fa33578cace173

**Comment by joomdonation** [comment]
The $model = new \Joomla\Component\Cache\Administrator\Model\Cache; should be correct, too (the previous code is clearly wrong)

**Comment by wilsonge** [comment]
I realised the reason the testing fails is because the model instance gets run after the update. so the code in this PR is never being run (we are using the code from the nightly which is still the old code). Merging this now. Then we can see once the nightly builds if things get fixed :)

**Comment by franz-wohlkoenig** [comment]
Updated Installation per downloaded nightly Build update Package works.

**Pull request merged**
