### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by demis-palma**
The PHPdoc declares the variable as "double"
`@param   double  $startTime`
but the method initialises its default value with an "integer" instead
`$startTime = 0`

### Summary of Changes
Changed the default value to type double

### Testing Instructions
To be merged on review

### CODE REVIEW

**Comment by Quy** [comment]
Tested with `0` and `0.0` and the result is always `0`. Thus, it doesn't make a difference. Close PR?
```
$startTime = 0;
echo (double) $startTime; 
```

**Comment by ghost** [comment]
closed for Reason stated above. Pull Request can always reopened if needed.

**Comment by HLeithner** [comment]
There is a difference, the var gets initialized as float if 0.0 so this pr is correct

**Comment by HLeithner** [comment]
The file moved to libraries/src/Profiler/Profiler.php in the meantime may @demis-palma could rebase it?

**Comment by Quy** [comment]
Closing in favor of PR #24971<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15743">issues.joomla.org/tracker/joomla-cms/15743</a>.</sub>

**Pull request closed without merging**
