### PR TITLE
[4.0] Fix unlimited checkbox markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Apply Bootstrap markup to unlimited checkbox.

From Bootstrap migrating to v4:
> Consolidated .checkbox and .radio into .form-check and the various .form-check-* classes.

### Testing Instructions
Edit a banner.
Click Banner Details tab.

### Expected result
unlimited-after

### Actual result
unlimited-before

### CODE REVIEW

**Comment by brianteeman** [comment]
i thought we were trying to avoid using framework classes?

**Comment by Quy** [comment]
My understanding is that it is ok to use Bootstrap on the backend.

**Comment by wilsonge** [comment]
In the backend is fine

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 10de8c4b0737db71acfc7836a260c1527b056726<br /><br />I see the space between the checkbox and label. But shouldn't this be a Yes/No slide?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29587">issues.joomla.org/tracker/joomla-cms/29587</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 10de8c4b0737db71acfc7836a260c1527b056726<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29587">issues.joomla.org/tracker/joomla-cms/29587</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29587">issues.joomla.org/tracker/joomla-cms/29587</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
