### PR TITLE
Missing grouping label on mod_articles_category

### PR DESCRIPTION
**Pull request by wojsmol**
This PR fixes a bug reported by @Nzara in https://github.com/joomla/joomla-cms/issues/7169. Detailed description and testing instructions can be found in that issue.

### CODE REVIEW

**Comment by n9iels** [comment]
@test success, works fine for me. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7256">issues.joomla.org/joomla-cms/7256</a>.</sub>

**Comment by wojsmol** [comment]
@n9iels thanks for testing, need another tester :)

**Comment by Bakual** [comment]
Adjusted title of PR.
Description copied from Issue

----

#### Steps to reproduce the issue
* create some categories, let say cat_a, cat_b
* create some articles in these categories, let's say: A, B, C
* create a module of type _Articles - Category_
 * choose option Filtering Options:Category: _all_categories_
 * choose option Grouping Options:Article Grouping: Category
 * choose an appropriate position to make it visible in your template
* view output of module on front end

#### Expected result
Name of Module
<ul>
 <li>
   <div class="grouping">Cat_a</div>
   <ul>
   <li>A</li>
   <li>B</li>
  </ul></li>
  <li>
   <div class="grouping">Cat_b</div>
   <ul>
   <li>C</li>
  </ul></li>
</ul>

#### Actual result
Name of Module
<ul>
 <li><ul>
   <li>A</li>
   <li>B</li>
  </ul></li>
  <li><ul>
   <li>C</li>
  </ul></li>
</ul>

#### Additional comments
After learning php i could work around by creating an overwrite of htm/mod_arcticles_category/default.php. Just insert after line 16:

    <div class="mod-articles-category-group"><?php echo $group_name;?></div>

I feel, this should be part of the core release.

**Comment by jwaisner** [comment]
@test 

PR works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7256">issues.joomla.org/joomla-cms/7256</a>.</sub>

**Comment by wojsmol** [comment]
@n9iels  @jwaisner thanks for testing
@zero-24 we have 2 good tests,  RTC?

**Comment by brianteeman** [comment]
Setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7256">issues.joomla.org/joomla-cms/7256</a>.</sub>

**Comment by wojsmol** [comment]
Can I expect that this PR will be merged to 3.4.3?

**Comment by Bakual** [comment]
> Can I expect that this PR will be merged to 3.4.3?

Depends if 3.4.3 will be a hotfix for major issues popping up in 3.4.2 or a regular release. If the latter, then chances are high.

**Comment by Kubik-Rubik** [comment]
Thank you @wojsmol for providing the fix and @Nzara for reporting the issue! Merged.

**Pull request closed without merging**
