### PR TITLE
[4.0] Breadcrumbs background

### PR DESCRIPTION
**Pull request by brianteeman**
Can be seen in the extensions install from web - changes from gray to white to add contrast and match style

Pull Request for Issue #21027 

image .

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9f252c0ebf2687b595365e5d7626c8a9d2a8a529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21798">issues.joomla.org/tracker/joomla-cms/21798</a>.</sub>

**Review by mbabker — APPROVED** [review]

**Comment by infograf768** [comment]
@wilsonge or @laoneo 
Can you please correct any PR touching compiled css files where we have the infamous `ˆM` windows EOL added where it should not. In this case here where npm on Windows has created them incorrectly?
https://github.com/joomla/joomla-cms/pull/21798/files#diff-a962cdc9935c244cac9994f2ca5100f2R9449

screen shot 2018-08-22 at 08 39 13


The only solution I see for now if to re-run npm install on core (from Linux or Macintosh) after merging such a PR.

**Comment by laoneo** [comment]
Probably better to remove the template min files from github too.

**Comment by infograf768** [comment]
for this peculiar issue, the min files are compiled fine.
Otherwise I guess we are tending towards https://github.com/joomla/joomla-cms/pull/21504 which means that patchtester users will not be able to test when changes in css.

**Comment by ghost** [comment]
> patchtester users will not be able to test when changes in css.

which isn't relevant if testing Platform is coming up.

**Pull request merged**
