### PR TITLE
[4.0]Create User Group - Group parent dropdown gets blank.#pbf19 #bug

### PR DESCRIPTION
**Pull request by shinderohanoffical**
Pull Request for Issue # .

### Summary of Changes
changes in groupparentfield.php

### Testing Instructions
1: Open new create a user group form.
2: Leave the required field blank and click on the save button.
3: Check parent group dropdown.

### Expected result
The options should display in a dropdown

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 7a9459004b5c49cae0ce9dfc8310e61f4597d416 #pbf19 #test1
<hr />
<sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26939">issues.joomla.org/tracker/joomla-cms/26939</a>.</sub>

**Comment by kishorchate** [comment]
I have tested this item :white_check_mark: successfully on 7a9459004b5c49cae0ce9dfc8310e61f4597d416<br /><br />#pbf19 #test2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26939">issues.joomla.org/tracker/joomla-cms/26939</a>.</sub>

**Comment by Quy** [comment]
RTC

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
