### PR TITLE
[4.0] Fixing unresolved merge conflicts

### PR DESCRIPTION
**Pull request by Bakual**
There are currently two unresolved merge conflicts in the 4.0-dev branch

### Summary of Changes
Resolves the conflicts

### Testing Instructions
* Create a new menu item. You will get warnings about syntax erros in the XML
* Look at a template (not the style) in the template manager. You get a duplicated text with some <<<< HEAD stuff

### Expected result
No unresolved stuff

### Actual result
unresolved stuff

### Documentation Changes Required
None

@wilsonge Can be merged by review. Just control that I resolved the conflicts correctly.

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 8c2a716c5c782d7f56f627567a8f1dbfa95b8ce5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16545">issues.joomla.org/tracker/joomla-cms/16545</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8c2a716c5c782d7f56f627567a8f1dbfa95b8ce5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16545">issues.joomla.org/tracker/joomla-cms/16545</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
