### PR TITLE
[5.2] mod_menu php fixes

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #44317

### Summary of Changes
Set Variables correctly

### Testing Instructions
see #44317

### Actual result BEFORE applying this Pull Request
Deprecated messages and Undefined Property messages 

### Expected result AFTER applying this Pull Request
no messages

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 5f706308d4a70d5135876244385005afeaf07985<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44318">issues.joomla.org/tracker/joomla-cms/44318</a>.</sub>

**Comment by brianteeman** [comment]
After applying the PR most of the core menu module disapears
image

**Comment by chmst** [comment]
I change this to draft as the behaviour with recover seems to be wrong.

**Comment by brianteeman** [comment]
Still not correct.

With this PR
Before enabling recovery

image

After enabling recovery

image

**Comment by chmst** [comment]
Thank you for testing. I cannot replicate that - in my test it is:

grafik

grafik

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on d62377f71eb876c1c7f51f93b060e693b14496fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44318">issues.joomla.org/tracker/joomla-cms/44318</a>.</sub>

**Comment by brianteeman** [comment]
This video shows that the recovery mode does not work.

https://github.com/user-attachments/assets/81b64785-cdca-43e0-9b28-6fd084b9f42d

**Comment by tkuschel** [comment]
I think, it would be more clear, instead of your variable define of camel-case $itemLink:
```
if (substr($item->link, 0, 8) === 'special:') {
```
change to:
```
if (isset($item->link) && substr($item->link, 0, 8) === 'special:') {
```

**Comment by chmst** [comment]
@brianteeman I have re-opened your issue. This PR is a partial fix for PHP warnings but does not resolve the issue with recovery mode.

**Comment by chmst** [comment]
@brianteeman do you remember which version was correct?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on adac1a51e55b7a31317a3d3048c7b137241e282f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44318">issues.joomla.org/tracker/joomla-cms/44318</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on adac1a51e55b7a31317a3d3048c7b137241e282f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44318">issues.joomla.org/tracker/joomla-cms/44318</a>.</sub>

**Comment by fgsw** [comment]
Ready to Commit?

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44318">issues.joomla.org/tracker/joomla-cms/44318</a>.</sub>

**Comment by pe7er** [comment]
Thanks @chmst !

**Pull request merged**
