### PR TITLE
[4.0] Update php minimum version to 7.2

### PR DESCRIPTION
**Pull request by brianteeman**
As discussed with @wilsonge I understand that the new php requirements are to be 7.2 +
This PR updates the check for JOOMLA_MINIMUM_PHP to 7.2 from 7.0

### CODE REVIEW

**Comment by wilsonge** [comment]
Please update the composer.json and composer.lock file with this too.

**Comment by brianteeman** [comment]
@wilsonge hope i did it right?

**Comment by wilsonge** [comment]
Sorry can you update the composer lock file again - now conflicting from my 3.9.4 merge over the weekend and i'll get this in

**Comment by brianteeman** [comment]
@wilsonge no idea but i couldnt resolve the conflict so created a new or #25252

**Pull request closed without merging**
