### PR TITLE
Different icons for different actions.

### PR DESCRIPTION
**Pull request by Shubham-com**
The two different icons (such as delete and unpublish) have same icons. (i.e, $fa-var-times )

Pull Request for Issue #33432 

### Summary of Changes
Different icons will perform different works.

### Actual result BEFORE applying this Pull Request

Screenshot (46)

### Expected result AFTER applying this Pull Request

Screenshot (45)

### CODE REVIEW

**Comment by brianteeman** [comment]
Be aware that this changes the icon used for unpublished everywhere

**Comment by Shubham-com** [comment]
I think that ban symbol can also be used as to unpublish and here,disable icon works similar to unpublish.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 3fa2c45763fadad4126e21a93c064e87bc451cc7<br /><br />I agree that the ban icon is a better option for disabled!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33515">issues.joomla.org/tracker/joomla-cms/33515</a>.</sub>

**Comment by brianteeman** [comment]
but is it also a good icon for an unpublished article

**Comment by Quy** [comment]
How about a `-` (minus sign)  for delete?

**Comment by rjharishabh** [comment]
> How about a `-` (minus sign) for delete?

I think, for delete ❌ is better than `-`

**Comment by drmenzelit** [comment]
It is not a good icon for unpublished content... it is too "negative", it makes the impression you should not touch the article any more...

**Comment by Shubham-com** [comment]
@drmenzelit @brianteeman will it be ok. If changes were made on delete icon and rest of the things are remain unchanged. Something like this....
Screenshot (48)

Don't know whether I am correct or not..I think it can be soved using two ways:-

i) change the delete icon to trash and rest of things remain unchanged
ii) create a new icon for disable one.

**Comment by drmenzelit** [comment]
I'm talking about the unpublished icon here for example:
grafik
And about trash icon for delete, please read the comment here: https://github.com/joomla/joomla-cms/issues/33432#issuecomment-830619440

**Comment by drmenzelit** [comment]
My suggestion was to create an own icon class for disable

**Comment by chmst** [comment]
How about using the disc / circle / not default for disabled everywhere? "x" looks alwys like "forbidden"

**Comment by ceford** [comment]
You could use thumbs-up/thumbs-down for enable/disable. I don't think the trash can is appropriate for delete because items in trash can be recovered but items deleted are not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33515">issues.joomla.org/tracker/joomla-cms/33515</a>.</sub>

**Comment by brianteeman** [comment]
thanks to facebook and youtube thumbsup/down means like/dislike to most people

**Comment by Shubham-com** [comment]
In general, thumbs-up/thumbs-down shows that you are agree or approval and vice-versa with something,

**Comment by ceford** [comment]
toggle-on/toggle-off might work for enable/disable (but I quite like thumbs).

**Comment by hans2103** [comment]
> @chmst How about using the disc / circle / not default for disabled everywhere? "x" looks alwys like "forbidden"

If you do this, the publish icon in the dropdown should be changed to a circle with a checkmark too.

> @Shubham-com i) change the delete icon to trash and rest of things remain unchanged

I like this proposal. Change the x, currently used for delete, by a trashcan


update... copied text from external chat
> The problem is that trash in Joomla doesn't mean delete, something get in the trash bin and you have to empty it... delete is really delete, gone for ever... we need a new icon for it or for disable

Delete icons by FontAwesome => https://fontawesome.com/icons?d=gallery&p=2&q=delete&m=free
Disable icons by FontAwesome => https://fontawesome.com/icons?d=gallery&p=2&q=disable&m=free <- not really useful I think

**Comment by Shubham-com** [comment]
I agreed what the @hans2103  said, no better icon found
we can use trash icon  
Screenshot (51)
 for those items can be recovered,which is already being used for trash.
Screenshot (50)

and trash-alt icon for delete which can be used for  delete forever,and it  can some how differ between them.

**Comment by Shubham-com** [comment]
The same issue with Extension: Manage
Go to System> Manage Extension

Both Disable and Uninstall have same (X) icon.
Screenshot (53)

**Comment by Quy** [comment]
Please don't use the different trash cans. I won't remember the purpose of each one.

Use the minus sign like in a shopping cart ... `+` to add an item and `-` to remove an item from the cart.

**Comment by hans2103** [comment]
summary.
(correct me if I'm wrong)

We need (new) icons for the following purposes
- disable / unpublish
- uninstall
- move-to-trash

my suggestions

- icon needed for disable / unpublish
  - https://fontawesome.com/icons/times?style=solid
- icon needed for uninstall
  - https://fontawesome.com/icons/eraser?style=solid
  - https://fontawesome.com/icons/backspace?style=solid
- icon needed for move-to-trash
  - https://fontawesome.com/icons/minus?style=solid
  - https://fontawesome.com/icons/recycle?style=solid

**Comment by brianteeman** [comment]
I am just seeing a need for an icon for delete and an icon for uninstall

As delete and uninstall are both permanent action that can not be undone I would suggest something like https://fontawesome.com/icons/exclamation-triangle?style=solid

**Comment by Shubham-com** [comment]
Thanks everyone for your suggestion, Please don't mind it.. but I still suggest trash can for delete and 
uninstall purposes as many of you have also seen this icon(i.e., trash can) before while uninstalling and deleting
any apps or software from your device.

And for move-to trash, means that the items that can be recovered..I suggest the Recycle icon
(https://fontawesome.com/icons/recycle?style=solid) the arrows in the recycle icon also indicates that
them items which are moved in trash can get recovered.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3fa2c45763fadad4126e21a93c064e87bc451cc7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33515">issues.joomla.org/tracker/joomla-cms/33515</a>.</sub>

**Comment by richard67** [comment]
@sandramay0905 This PR has the "Updates Requested" label set, which means some reviewer requested changes, and since that label has been set, no change has been made, so it doesn't make much sense to test that PR now. It will not get RTC even with 2 tests as long as that review has not been clarified.

@Quy Could you check if your request is still valid?

**Comment by Shubham-com** [comment]
Please also update me, what changes would you want . I got too much confused, as different suggestions from different reviewers.

**Comment by ghost** [comment]
> This PR has the "Updates Requested" label set, which means some reviewer requested changes, and since that label has been set, no change has been made, so it doesn't make much sense to test that PR now.

Thanks for the info, @richard67, haven't know that. I'm not sure if i noticed that label in the future, grayscale is not so easy to see :-)

**Review by Shubham-com — COMMENTED** [review]
@brianteeman Please review it.

**Comment by drmenzelit** [comment]
Can we reach a consensus on this one? @Shubham-com @brianteeman @hans2103

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev.

**Comment by ceford** [comment]
I have tested this item :red_circle: unsuccessfully on 2182d8768391a30dde48236559b7713664ac30d1<br /><br />Is this Issue abandoned? I tested it and it does not work - seems only relevant for backward compatibility.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33515">issues.joomla.org/tracker/joomla-cms/33515</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by drmenzelit** [comment]
Closing this in favour of #42250

**Pull request closed without merging**
