### PR TITLE
[4.0] Rename aurora

### PR DESCRIPTION
**Pull request by brianteeman**
rockettheme just brought out a template called aurora so this PR changes all references to cassiopeia

### CODE REVIEW

**Comment by brianteeman** [comment]
@wilsonge this could really do with merging quickly or we will get lots of conflicts

**Comment by dgrammatiko** [comment]
@brianteeman was this cassiopeia name discussed, agreed in some team or is it randomly picked up?

**Comment by brianteeman** [comment]
I randomly chose it as it follows the space based naming eg protostar. (Unlike aurora)

I also quite like the symbolism of "named after the vain queen Cassiopeia in Greek mythology, who boasted about her unrivalled beauty. "

**Comment by ciar4n** [comment]
I appreciate the symbolism however 'Cassiopeia' seems a bit of a mouthful

**Comment by alikon** [comment]
i'd prefer Andromeda
why not make a public poll ?

**Comment by dgrammatiko** [comment]
For me cassiopeia is fine (I know a bit of Greek mythology). If we're open for names, I would like to see a name after the 2017 Nobel price on gravitational waves and thus a neutron planet or simply: `pulsar`.

But once again I'm totally fine with `cassiopeia` or whatever else resonate for most people

**Comment by ciar4n** [comment]
I'm fine with Cassiopeia.. a mouthful was my initial thought.. gotten use to it already!)

**Comment by coolcat-creations** [comment]
How about calling it "Joomla" ? :-)

**Comment by wilsonge** [comment]
I'm merging this for now so we don't have to deal with conflicts etc etc etc. Tbh the name is easily changeable till we hit beta if people are unhappy we can always change it again

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
