### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by brianteeman**
Small fix to correct the grammar/typo as it should be field not fields

### Before
For increased security the edit permission for this SQL **fields** was set to denied for all non Super Users.

### After
For increased security the edit permission for this SQL **field** was set to denied for all non Super Users.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 804cde41b8b17d7107b67e7ae0413cc5f87b6161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19117">issues.joomla.org/tracker/joomla-cms/19117</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 804cde41b8b17d7107b67e7ae0413cc5f87b6161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19117">issues.joomla.org/tracker/joomla-cms/19117</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
