### PR TITLE
[4.4] Spelling mistake

### PR DESCRIPTION
**Pull request by brianteeman**
accessiblity ==> accessibility  (missing i)

code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 06c9c663346f7cf867428e96bc28da1676f45860<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42940">issues.joomla.org/tracker/joomla-cms/42940</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 06c9c663346f7cf867428e96bc28da1676f45860<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42940">issues.joomla.org/tracker/joomla-cms/42940</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42940">issues.joomla.org/tracker/joomla-cms/42940</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
