### PR TITLE
[4.3] Media manager warning fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Add `.toString()` for the key and uid: https://github.com/joomla/joomla-cms/blob/94212433b370796c69cdd37c95402b9f40bb7b90/administrator/components/com_media/resources/scripts/components/app.vue#L6-L7
- Add the focused missing property: https://github.com/joomla/joomla-cms/blob/94212433b370796c69cdd37c95402b9f40bb7b90/administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js#L200-L203
- Change the arguments of the `getContents`, `full` and `content` to boolean, default to false and fix all the calls:  https://github.com/joomla/joomla-cms/blob/94212433b370796c69cdd37c95402b9f40bb7b90/administrator/components/com_media/resources/scripts/app/Api.es6.js#L115

### Testing Instructions
- Run npm i
- run `npm watch:com_media`
- Open the admin site and go to media manager
- Open the browser console and refresh
- Observe the warnings
- Apply the PR
- run `npm watch:com_media`
- Open the admin site and go to media manager
- Open the browser console and refresh
- No warnings
- Check that uploading, editing, etc works as before

### Actual result BEFORE applying this Pull Request

Screenshot 2023-03-04 at 14 05 04

Screenshot 2023-03-04 at 14 05 14

### Expected result AFTER applying this Pull Request

No warnings 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 25990fe383297d3f8b0dae1907371b7de2493c12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40002">issues.joomla.org/tracker/joomla-cms/40002</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 25990fe383297d3f8b0dae1907371b7de2493c12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40002">issues.joomla.org/tracker/joomla-cms/40002</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40002">issues.joomla.org/tracker/joomla-cms/40002</a>.</sub>

**Comment by obuisard** [comment]
Thanks Dimitris @dgrammatiko for the PR :-)

**Pull request merged**
