### PR TITLE
[4.0] name not title

### PR DESCRIPTION
**Pull request by brianteeman**
The column name in workflows and plugins is name not title so the sort option should be name not title. This PR adds a new global language string for this

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22e9d9ce51517abdc818b21d87fb4a563d89fab8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26797">issues.joomla.org/tracker/joomla-cms/26797</a>.</sub>

**Comment by Quy** [comment]
Can you please do the same for Plugins? Thanks.

**Comment by brianteeman** [comment]
@quy added

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dfcb4e412cbb48f31c8ab0c62e0f2f9ab5e8fadf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26797">issues.joomla.org/tracker/joomla-cms/26797</a>.</sub>

**Comment by joeykrop** [comment]
I have tested this item :white_check_mark: successfully on dfcb4e412cbb48f31c8ab0c62e0f2f9ab5e8fadf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26797">issues.joomla.org/tracker/joomla-cms/26797</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26797">issues.joomla.org/tracker/joomla-cms/26797</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
