### PR TITLE
[4.2] further CLI discover scripts cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Adds a title for install discovered extensions
Moves the title for list discovered extensions so that it will appear when there are no extensions

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d275dca33bd7b1baa28e767e38f27282979257c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38223">issues.joomla.org/tracker/joomla-cms/38223</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d275dca33bd7b1baa28e767e38f27282979257c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38223">issues.joomla.org/tracker/joomla-cms/38223</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38223">issues.joomla.org/tracker/joomla-cms/38223</a>.</sub>

**Comment by brianteeman** [comment]
updating branch to try and trigger broken drone

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
