### PR TITLE
Undefined variable lang_code in plugins/system/languagefilter/languagefilter.php on line 297

### LINKED ISSUE #6481: 3.4.1-rc Undefined variable lang_code in plugins/system/languagefilter/languagefilter.php on line 297
#### Steps to reproduce the issue

On a clean multilingual 3.4.0 installation upgraded to 3.4.1-rc, go to the home page and switch to some other language than the one you initially get.

Close the browser tab, open a new one and enter in address bar the site root and press enter.

#### Expected result

You get to the home page with a redirect based on the previously selected language remembered with help of the cookie, but not PHP message in between.

#### Actual result

I got redirected in the correct way, but for a short moment a browser page with a PHP warning text and blank background was shown.

I had to stop loading before the redirect occurred to have a chance to see following PHP message:

Notice: Undefined variable: lang_code in plugins/system/languagefilter/languagefilter.php on line 297

(The root part of the URL I stripped off).

Because I do not really dare to figure out if the correct change of

    $lang = $uri->getVar('lang', $lang_code);

would be just

    $lang = $uri->getVar('lang');

or maybe better

    $lang = $uri->getVar('lang', $this->default_lang);

or maybe more complicated, after all the discussions and multiple PRs from many people, I do not make a PR myself but prefer someone to have a look on it, e.g. @Hackwar 

#### System information (as much as possible)

Clean multilingual 3.4.0 installation upgraded to 3.4.1-rc in a folder protected with .htaccess authentication, SEF URLs = ON, URL rewriting = ON or OFF, does not matter, all the rest regarding SEF and also the remove default language setting of the languagefilter = OFF.

### PR DESCRIPTION
**Pull request by Hackwar**
Fixes #6481. Please refer to there for testing instructions.

### CODE REVIEW

**Comment by richard67** [comment]
Just tested with success. Thanks @Hackwar :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6483">issues.joomla.org/joomla-cms/6483</a>.</sub>

**Comment by infograf768** [comment]
@test
SEF on: this solves the Notice.

We have an issue when SEF off and using associations;
Load a menu item with associations.
In this case, clicking on the languageswitcher flag for the language already loaded always redirects to the home page for that language instead of reloading the same page.
Associated items are loaded correctly for the other languages.
It does not look like related to this patch.

**Comment by Hackwar** [comment]
As far as I can see, the issue that you are describing is also present in 3.3

**Comment by infograf768** [comment]
It could be indeed.

**Pull request merged**
