### PR TITLE
[5.2] Fix Joomla.renderMessages not found with mod_login

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #41299 .

### Summary of Changes

Add missing dependency for Joomla.renderMessages

### Testing Instructions
Please follow #41299

### Actual result BEFORE applying this Pull Request
JS error

### Expected result AFTER applying this Pull Request
No error

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by ceford** [comment]
I can't reproduce this problem. I have `Multi-factor Authentication is not enabled.` I have registered my Authenticator in `W3C Web Authentication (WebAuthn) Login`. In the Admin login form I click the button on the dongle when prompted and login works normally. With a user not using that method there is a normal error message. Everything I see is translated. I do not see any Javascript error messages. 

Perhaps some more specific test instructions would help. I am using joomla-cms with 4.3-dev checked out and Chrome/Firefox on Mac.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41300">issues.joomla.org/tracker/joomla-cms/41300</a>.</sub>

**Comment by ceford** [comment]
Same with frontend login - no problems.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41300">issues.joomla.org/tracker/joomla-cms/41300</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by TLWebdesign** [comment]
I have tested this item :red_circle: unsuccessfully on e67eb169c50081d100c7bf18a141fe6b10f379ca<br /><br />Could not reproduce the Javascript error in the console on failed login. My method:
Create user with a valid webauthn setup. 
Check that login works for this user on the front-end using the mod_login form.
Log the user out in front-end.
Remove the webauthn setup for this user.
Reload page.
Try to login again as webauth for this user.
No Javascript errors in console. Only an formatted error message is displayed: "The credential ID is invalid." So It is rendering the message just fine. 
Joomla 4.4.3



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41300">issues.joomla.org/tracker/joomla-cms/41300</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by wilsonge** [comment]
Merging on review. Whilst messages is on many pages - it's clearly a dependency of the script

**Pull request merged**
