### PR TITLE
[4.0] add rel attribute in joomla.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

this pull request adds the rel attribute to the target=_blank links

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on c9e452cd58b026909b33bfa54c7e48b00f306d07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34434">issues.joomla.org/tracker/joomla-cms/34434</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c9e452cd58b026909b33bfa54c7e48b00f306d07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34434">issues.joomla.org/tracker/joomla-cms/34434</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34434">issues.joomla.org/tracker/joomla-cms/34434</a>.</sub>

**Comment by brianteeman** [comment]
Nothing wrong with this change but it's not really needed as I'm pretty sure we can trust our own sites. Iirc we haven't done this for other joomla org let nks

**Comment by tecpromotion** [comment]
Thanks @brianteeman 

> Nothing wrong with this change but it's not really needed as I'm pretty sure we can trust our own sites. Iirc we haven't done this for other joomla org let nks

Sure we can trust the pages but we can also easily make sure that all windows that open in a new window get the rel attribute "noopener, noreferrer".

My reason for this pull request was: 
> If you are linked to an external website that could be affected by the malicious code, then that website can use the window.opener JavaScript property to steal digital information from your audience by running on the same process of your page.
> 
> So adding rel="noopener" or rel="noreferrer" to the link will prevent the new tab from taking advantage of the JavaScript window.opener feature.

**Comment by brianteeman** [comment]
I know the reasons. I did the first pr for this :)

I just think we can trust our own site

**Comment by tecpromotion** [comment]
> I know the reasons. I did the first pr for this :)
> 
> I just think we can trust our own site

Set a good example and we set all outgoing links with the rel attribute. Then it will be consistent and there will be no questions about why there and not there.

What do you think @brianteeman ?

**Comment by PhilETaylor** [comment]
I think its funny that you **_think_** you can trust joomla.org sites...

**Comment by brianteeman** [comment]
@StefanSTS In which case shouldnt you update this PR for all the other links to joomla.org?

And I just did a very quick look and see that there are real external links that dont have this when they absolutely should

**Comment by PhilETaylor** [comment]
If only there was some kind of security team that had code reviews as one of its goals.….

**Pull request merged**
