### PR TITLE
[4.1] Scheduled task - alternate menu

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Add Scheduled tasks to the components menu in the alternate main menu.

### Testing Instructions
Create a new **admin** menu and use the preset alternate
Add a module to display the menu and unpublish the existing admin menu module

### Actual result BEFORE applying this Pull Request
Menu link to com_schedules can be found in the components menu

### Expected result AFTER applying this Pull Request
No menu link to com_schedules

### CODE REVIEW

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 62a780cfc1da0393b6491519f31c550a148f7dbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37758">issues.joomla.org/tracker/joomla-cms/37758</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 62a780cfc1da0393b6491519f31c550a148f7dbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37758">issues.joomla.org/tracker/joomla-cms/37758</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37758">issues.joomla.org/tracker/joomla-cms/37758</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
