### PR TITLE
Joomla.request do not force header for non string Data

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #32106 .

### Summary of Changes

The changes prevent forcing of `application/x-www-form-urlencoded` for non String data, without b.c.

### Testing Instructions

Add to index.php of Protostar template:

```html
<script>
var data = new FormData();
data.append('foo', 'bar');

Joomla.request({
  url: 'index.php?option=com_ajax&format=raw',
  data: data
});

Joomla.request({
  url: 'index.php?option=com_ajax&format=raw',
  data: 'foo=bar'
});
</script>
```

And inspect Developer tools, Network tab for 2 `index.php?option=com_ajax&format=raw` requests

### Actual result BEFORE applying this Pull Request

First request will contain random text in Form data, like:
Screenshot_2021-01-23_12-26-27

### Expected result AFTER applying this Pull Request

Both request should contain foo:bar Form data, like:
Screenshot_2021-01-23_12-25-39

### Documentation Changes Required
no

### CODE REVIEW

**Comment by richard67** [comment]
@Fedik With the patch, I don't get the random parts in the query parameters anymore for the first request, but I still don't get form data:



For the second request I get form data before and after the patch:

**Comment by Fedik** [comment]
yea, Firefox network tool a bit different,

To be sure, you can add `print_r($_POST);` somewhere in `com_ajax/ajax.php`
and then in Network tab, in Response section you should see `Array ( [foo] => bar ) ` for both request.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e88c42ec42bfdc7db14c22bc1961f0f576c0c5d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32119">issues.joomla.org/tracker/joomla-cms/32119</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e88c42ec42bfdc7db14c22bc1961f0f576c0c5d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32119">issues.joomla.org/tracker/joomla-cms/32119</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32119">issues.joomla.org/tracker/joomla-cms/32119</a>.</sub>

**Comment by ghost** [comment]
please commit its RTC now

**Comment by rdeutz** [comment]
@chnnst a self like of own comments is looking a bit strange and stupid

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
richard67 my question to rdeutz was please commit its RTC now? 

All checks have passed.

This branch has no conflicts with the base branch.

Why those with write access to this repository do not merge pull request ?

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
