### PR TITLE
[4.0] alphabetical sorting in com_categories

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

alphabetical sorting of the quickicon strings in com_categories

### Testing Instructions

.

### Expected result

`_N_  
_NEW_  
_NO_  
_PATH_ 
_REBUILD_`

### Actual result

`_N_  
_NEW_  
_NO_  
_PATH_  
_N_ 
_REBUILD_`

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a52c6b29287e559a10f20c5bb4a824883947b943<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29214">issues.joomla.org/tracker/joomla-cms/29214</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a52c6b29287e559a10f20c5bb4a824883947b943<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29214">issues.joomla.org/tracker/joomla-cms/29214</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29214">issues.joomla.org/tracker/joomla-cms/29214</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
