### PR TITLE
Restore Calendar.setup function for B/C

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/15251 .

### Summary of Changes
Adds a proxy for Calendar.setup(object) to restore backwards compatibility.

### Testing Instructions
Apply patch.
Go to Administrator and edit an article
go to publishing tab
open browsers console and paste/run:
```js
        Calendar.setup({
            inputField: 'jform_publish_up',
            showOthers: '0'
        });

```

UPD: The showOthers can be `true` or `"true"` for enabled and anything else for disabled

the cal should reinitialise, to confirm open it again you should see the table without the days for prev/next month

### CODE REVIEW

**Comment by infograf768** [comment]
This works only for Start Publishing field.

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 857aa0ea61a098dfbdf91b4263c837f833160f01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15489">issues.joomla.org/tracker/joomla-cms/15489</a>.</sub>

**Comment by bembelimen** [comment]
Works for me, perfect!

Thank you @dgt41

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 857aa0ea61a098dfbdf91b4263c837f833160f01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15489">issues.joomla.org/tracker/joomla-cms/15489</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15489">issues.joomla.org/tracker/joomla-cms/15489</a>.</sub>

**Comment by infograf768** [comment]
Can be merged. :)

**Pull request merged**
