### PR TITLE
[4.0] Update dependencies

### PR DESCRIPTION
**Pull request by Hackwar**
This updates both the composer and npm dependencies to the latest versions. We also had 25 warnings about security issues coming from the skipto package. @wilsonge provided that package a PR which updates their dependencies, but after 3 months they still weren't able to do a new release. So I switched the dependency to the repo instead. With this PR all security warnings are fixed.

### CODE REVIEW

**Comment by wilsonge** [comment]
Skipto 2.0.4 is out. Please swap to that rather than master :)

**Comment by HLeithner** [comment]
Maybe go directly to 2.1.0?

**Comment by brianteeman** [comment]
Hard to do that as it hasnt been released ;)

**Comment by HLeithner** [comment]
they are a bit strange with the version history ^^
https://www.npmjs.com/package/skipto they already have a version history for this version...

But ok then upgrading to 2.0.4 is the better idea ;-)

**Comment by Hackwar** [comment]
There you go

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
