### PR TITLE
[4.3] Update readme

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

fix broken link in readme file
update `.github/CONTRIBUTING.md`

### Testing Instructions

clink on link for changelog
image

### Actual result BEFORE applying this Pull Request

404 error
image

### Expected result AFTER applying this Pull Request

version history of 4.3-dev
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 67499011c7eac9e029d791e363d69f1f368b3d92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41088">issues.joomla.org/tracker/joomla-cms/41088</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 67499011c7eac9e029d791e363d69f1f368b3d92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41088">issues.joomla.org/tracker/joomla-cms/41088</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41088">issues.joomla.org/tracker/joomla-cms/41088</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 !

**Pull request merged**
