### PR TITLE
[4.0] Adding back string deleted by error in 30588

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
The string `COM_CONTENT_EDIT_ITEM="Edit Article"` was deleted in #30588 by error.
It is used when Displaying a Category list.

EDIT : Also role=button is useless when article is checked out

### Testing Instructions
Create a Category List menu item. Log as superuser in frontend and display that menu item

### Actual result BEFORE applying this Pull Request
Screen Shot 2020-09-09 at 10 26 01

### Expected result AFTER applying this Pull Request

Screen Shot 2020-09-09 at 10 27 24

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on abf6dae6e4b82a0109cab7679bf296bc4c6d2825<br /><br />Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30601">issues.joomla.org/tracker/joomla-cms/30601</a>.</sub>

**Comment by sandewt** [comment]
>EDIT : Also role=button is useless when article is checked out

Oops, what should I pay attention to when testing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30601">issues.joomla.org/tracker/joomla-cms/30601</a>.</sub>

**Comment by infograf768** [comment]
> Oops, what should I pay attention to when testing?

Nothing. It is just a useless role which was taken off from the original patch for published/unpublished and was forgotten  from the part concerning checked out status.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on abf6dae6e4b82a0109cab7679bf296bc4c6d2825<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30601">issues.joomla.org/tracker/joomla-cms/30601</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30601">issues.joomla.org/tracker/joomla-cms/30601</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
