### PR TITLE
[4.0] Correct obvious syntax error in installation and schema update for PostgreSQL

### PR DESCRIPTION
**Pull request by richard67**
Correct obvious syntax error in create table statement for the workflows table in installation and schema update for PostgreSQL.

Can be tested and merged by review.

@alikon please review.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 19f734fe7441fc68c8d58129762069bb988d15c9<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21881">issues.joomla.org/tracker/joomla-cms/21881</a>.</sub>

**Comment by richard67** [comment]
@alikon Thanks.

**Comment by richard67** [comment]
@laoneo Can this one be merged?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21881">issues.joomla.org/tracker/joomla-cms/21881</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
