### PR TITLE
[4.0] Replace outline icons in header

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Status icons in the header are the only 'outline' icons. For consistency this PR replaces them with normal weight icons. 

Note: Change was already made in #17046 however I managed to revert the icons fixing conflicts (",)

### Before
icons1

#### After
icons2

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5791b2a532fcc285efddd4d5cb45cbbffa3f00bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17118">issues.joomla.org/tracker/joomla-cms/17118</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5791b2a532fcc285efddd4d5cb45cbbffa3f00bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17118">issues.joomla.org/tracker/joomla-cms/17118</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by ciar4n** [comment]
Conflicts fixed

**Pull request merged**
