### PR TITLE
[4.0] Replace inline style width 12%, 35% with w-12, w-35

### PR DESCRIPTION
**Pull request by Quy**
Complete converting of PR #28692

### Summary of Changes
Add w- classes.
Replace inline style widths % with w-.
Replace missed ones from previous PRs.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fe9046c202910738e552b6c601802a153dce25d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29056">issues.joomla.org/tracker/joomla-cms/29056</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on fe9046c202910738e552b6c601802a153dce25d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29056">issues.joomla.org/tracker/joomla-cms/29056</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29056">issues.joomla.org/tracker/joomla-cms/29056</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Comment by infograf768** [comment]
@Quy 
please see https://github.com/joomla/joomla-cms/pull/32244#issuecomment-772433497

**Pull request merged**
