### PR TITLE
[4.2] remove spaces in COM_USERS_MFA_INVALID_CODE

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

remove spaces

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

`COM_USERS_MFA_INVALID_CODE = "Multi-factor Authentication failed. Please try again."`

### Expected result AFTER applying this Pull Request

`COM_USERS_MFA_INVALID_CODE="Multi-factor Authentication failed. Please try again."`

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b1717d8a96c34a3fc1cce61dbc9bf346d7ed64b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38287">issues.joomla.org/tracker/joomla-cms/38287</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b1717d8a96c34a3fc1cce61dbc9bf346d7ed64b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38287">issues.joomla.org/tracker/joomla-cms/38287</a>.</sub>

**Comment by tecpromotion** [comment]
@Quy can you please add the Lanuage Label again.
Some setups (github bots) need this trigger. Thanks.

**Comment by Quy** [comment]
Thank you.

**Pull request merged**
