### PR TITLE
[4.0] Replace inline style 10% with w-10

### PR DESCRIPTION
**Pull request by Quy**
Continuation of PR #28692

### Summary of Changes
Replace inline style 10% with w-10

### Testing Instructions
Code review.
or
Run npm i
Go to System > Database
View page source or browser's inspector on the `Location` and `Type` columns.
No visual changes.

### CODE REVIEW

**Comment by richard67** [comment]
@Quy ~~Is w-10 also a bootstrap class?~~ Ah, I just see, you added it. All fine.

**Comment by Quy** [comment]
Only 25%, 50%, 75%, and 100%. See https://getbootstrap.com/docs/4.4/utilities/sizing/

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ab7fc26755e16800a5ca55c13ba642e17ec4ee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28730">issues.joomla.org/tracker/joomla-cms/28730</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9ab7fc26755e16800a5ca55c13ba642e17ec4ee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28730">issues.joomla.org/tracker/joomla-cms/28730</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28730">issues.joomla.org/tracker/joomla-cms/28730</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
