### PR TITLE
[5.0] Add guided tours to alternate menu preset

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Adds the guided tours component to the alternate menu preset 

### Testing Instructions
Go to the module manager and filter on admin modules
Open the admin menu module 
Change the preset from **Joomla Main Meunu** to **Alternative Main Menu**

### Actual result BEFORE applying this Pull Request
Guided Tours is not present in the components submenu

### Expected result AFTER applying this Pull Request

Guided tours is now available

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e00caf0652df59b0f68b87859b97e6bc1a8d0631<br /><br />Tested successfully in Joomla 4.3.3-dev of 4 June in Wampserver 3.3.6 using PHP 8.2.6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40707">issues.joomla.org/tracker/joomla-cms/40707</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e00caf0652df59b0f68b87859b97e6bc1a8d0631<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40707">issues.joomla.org/tracker/joomla-cms/40707</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40707">issues.joomla.org/tracker/joomla-cms/40707</a>.</sub>

**Comment by HLeithner** [comment]
could you please resolve the conflict

**Comment by brianteeman** [comment]
This was a bug fix not a new feature. The conflicts and all the extra files were caused by the pointless changes made to try and rebase the pr it needs completely rebuilding :(

**Comment by HLeithner** [comment]
It was only one file with a conflict, if you undelete your branch I can do the conflict resolution for you

**Comment by brianteeman** [comment]
there were 87 unrelated files

**Comment by HLeithner** [comment]
true but they could

**Comment by HLeithner** [comment]
Ok, I see you have created a new pr then I close this again

**Pull request closed without merging**
