### PR TITLE
Always set all columns from app's checkSession method

### LINKED ISSUE #11556: Users invisible in who's online
#### Steps to reproduce the issue
Login to a site that either has Kunena installed or uses module Who's online or other extensions that uses core who's online. After a certain amount of time names of online users are disappearing.
Related topics: https://www.kunena.org/forum/36-German/138111-wer-ist-online?limitstart=0 and http://forum.joomla.org/viewtopic.php?t=930726
**Kunena**
screen shot 2016-08-11 at 05 25 05
**Module Who's online**
screen shot 2016-08-11 at 05 25 29

#### Expected result
All online users visible

#### Actual result

See screenshots above

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

`JApplicationCms::checkSession()` tries to micro optimize the INSERT query it runs if creating a record in the `#__session` table by checking if the session is new.  Honestly, there isn't a pressing need to do this though; the only column value that is different between the two steps of the conditional is the `time` column.  So, only have a conditional on this value and have the query always insert the full data set.

As an added bonus, uses of the deprecated `JObject` API are removed from pulling data from the `JUser` object.

Additionally, the query's columns and values are moved out from hard-to-read inline values to arrays that are handled when calling the query builder's API methods.
### Testing Instructions

This might fix #11556 so however folks are reproducing that issue.  Otherwise, this is mainly review and make sure the CMS still works (if it fails it'll fail very quickly because it's called very early in the request cycle).
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by onlinemindgem** [comment]
I have tested this item :white_check_mark: successfully on 1ddfc4f8723fb767f726f71eb7b07e80461185a6<br /><br />I tested this mainly for #11556 and now sessions seem to be correct again (for Kunena in my case) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11691">issues.joomla.org/joomla-cms/11691</a>.</sub>

**Comment by aidanwhiteley** [comment]
Thanks!
I have also tested this item ✅ successfully on 1ddfc4f but mainly for the issue mentioned in in #11556 (although a basic sanity test of the rest of the sites seems OK).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11691">issues.joomla.org/joomla-cms/11691</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11691">issues.joomla.org/joomla-cms/11691</a>.</sub>

**Comment by cuertech** [comment]
Many thanks - have tested by applying fix to affected local and remote sites and all salient issues in #11556 are fully resolved - web peace resumed

**Pull request merged**
