### PR TITLE
[4.0][api][com_content] - Add languages filter options to com_content

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
after the merge  of #28382
add the option to filter content by language

### Testing Instructions
on a multiligual site install Frech and German for example
run  Multilingual Sample Data 
call JROOT_URL/api/index.php/v1/content/article?filter[language]=de-DE

### Expected result
the api response is filtered by language

### Actual result
N/A

### Documentation Changes Required
yes

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 742d8abd8c865fdc1df18af088aeec918559dfac<br /><br />Before patch: not filtered, after patch: filtered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28406">issues.joomla.org/tracker/joomla-cms/28406</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 742d8abd8c865fdc1df18af088aeec918559dfac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28406">issues.joomla.org/tracker/joomla-cms/28406</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28406">issues.joomla.org/tracker/joomla-cms/28406</a>.</sub>

**Comment by wilsonge** [comment]
Talked about this with some people on glip and agree this is fine.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
