### PR TITLE
[#19471] - [4.0] Lateral menu overlaps debug panel on backend

### PR DESCRIPTION
**Pull request by amone4**
Pull Request for Issue #19471 .

### Summary of Changes

Changed the markup to include the debug panel in the same wrapper as the normal content

### Testing Instructions

Activate the debug panel by going into Global Configuration > System tab

### Expected result

See the complete debug panel at the end of each page

### Actual result

Part of the debug panel is hidden by Joomla's lateral menu administrative pages

### Documentation Changes Required

None, I guess

### CODE REVIEW

**Comment by anuragteapot** [comment]
@laoneo we have some problem with this PR
Debug panel works fine in back-end but in front end it seems like this 

screenshot from 2018-04-09 18-16-59

**Comment by dgrammatiko** [comment]
@ciar4n can you take a look at the debug console in the front end?

**Comment by anuragteapot** [comment]
And one more thing debug console in admin login is not showing.

**Comment by laoneo** [comment]
Thanks @Anu1601CS. Does reverting this line help https://github.com/joomla/joomla-cms/pull/20061/files#diff-78d82eb8bd4c1f14a8e99e82ada1daf9R355 ?

**Comment by anuragteapot** [comment]
@laoneo 
> Does reverting this line help https://github.com/joomla/joomla-cms/pull/20061/files#diff-78d82eb8bd4c1f14a8e99e82ada1daf9R355 ?

No, this make debug console more messy then before this PR.
screenshot from 2018-04-09 18-44-42

I think this is not a proper fix for this.

**Comment by dgrammatiko** [comment]
@amone4 @laoneo this PR was wrong. What we need actually is to move the debug module inside the wrapper:
screen shot 2018-04-09 at 15 27 45

**Comment by laoneo** [comment]
Can you make a new pr for it?

**Comment by anuragteapot** [comment]
> Can you make a new pr for it?

Me ?

**Comment by dgrammatiko** [comment]
Here is what I'm thinking:
in the template:
```
<joomla-debug><jdoc:include type="modules" name="debug" style="none" /></joomla-debug>
```

in the plugin:
```
		echo str_replace('<joomla-debug></joomla-debug>', '<joomla-debug>' . implode('', $html) . '</joomla-debug>', $contents);
```

That will decouple the markup form the body tag, but it's also a minor B/C break (?)

Let me know if it's ok and then will push the changes in a PR

**Comment by laoneo** [comment]
If you can, would be great. Guess you need to revert this one as well then.

**Comment by laoneo** [comment]
You want to make a CE out of it?

**Comment by dgrammatiko** [comment]
nah, I just wanted to increase specificity without adding id or some weird class...

**Comment by anuragteapot** [comment]
@laoneo I can but tomorrow and day after tomorrow is my university exam. 
After the exam, I take a look on it. :)

**Comment by laoneo** [comment]
@dgrammatiko yes, please make a new pr if you have time. I'm going to revert this one anyway.

**Comment by dgrammatiko** [comment]
Ok will do. By the way I just saw https://github.com/joomla/joomla-cms/issues/11840 due to comment in another issue, so maybe will be a good idea to introduce `<jdoc:include type="debug" />` and totally decouple the debug from the modules? (not to be done in the comming PR though.. 😃)

**Comment by dgrammatiko** [comment]
@laoneo there you go: https://github.com/joomla/joomla-cms/pull/20120

**Pull request merged**
