### PR TITLE
[4] correct single line comment style

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

change `/** */` syntax to `//` to comply with https://developer.joomla.org/coding-standards/inline-code-comments.html for single line comments

No code changes.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 28e1a8a90e971783d8bc4ee1e34fcc371e53ef26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31946">issues.joomla.org/tracker/joomla-cms/31946</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 28e1a8a90e971783d8bc4ee1e34fcc371e53ef26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31946">issues.joomla.org/tracker/joomla-cms/31946</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31946">issues.joomla.org/tracker/joomla-cms/31946</a>.</sub>

**Comment by wilsonge** [comment]
This is the same line that's in index.php for each app entry point. If you're doing it here we should be consistent in doing it everywhere

**Comment by PhilETaylor** [comment]
PR Updated with all entrypoints

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
