### PR TITLE
[4.0] [com_content] Use parent query in backend featured model

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Since featured article filtering was added to backend articles model, we can use its query in featured articles model.

### Testing Instructions

Create some articles. Create some featured articles.
View featured articles in backend.
Use the filter and ordering forms.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 97cc89c37179204857d699a7a0474cdfbb593d2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27890">issues.joomla.org/tracker/joomla-cms/27890</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 97cc89c37179204857d699a7a0474cdfbb593d2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27890">issues.joomla.org/tracker/joomla-cms/27890</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27890">issues.joomla.org/tracker/joomla-cms/27890</a>.</sub>

**Comment by Quy** [comment]
Remove `use` statements.

**Pull request merged**
