### PR TITLE
optimize validation.js performance

### PR DESCRIPTION
**Pull request by Fedik**
it a try to optimise the Joomla! form rendering with a lot inputs.
`validation.js` it third slow script after `chosen.js` and `bootstrap.tooltip` on the form page,

Here is some graphs.
test made with disabled `chosen.js` and `bootstrap.tooltip` on Global configuration page.

Before this fix:
screen 2014-10-02 16 23 30 1164x438
After fix:
screen 2014-10-02 16 19 55 1085x445

As can see difference around 400ms for `JFormValidator` initialization, at least on my PC in Chrome :smile:

**How to test.**
Apply patch. 
Go to global configuration, or other form where a lot inputs, and compare whether all still works and whether it "feels faster" :wink:

### CODE REVIEW

**Comment by anibalsanchez** [comment]
@test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4435">issues.joomla.org/joomla-cms/4435</a>.</sub>

**Comment by zero-24** [comment]
@Fedik can you fix the `merge conflicts` here? I will test after a resync to be sure that nothing is broken :smile: Thanks!

**Comment by Fedik** [comment]
@zero-24 done :wink: 

and I added `strict mode`, so please retest

**Comment by zero-24** [comment]
Thanks @Fedik 

@test successful I can't see any issues with the patch applyed.

>and I added strict mode, so please retest
@Fedik do @anibalsanchez also retest or can we move it now to RTC?

**Comment by Fedik** [comment]
yes, would be good to retest :wink:

@anibalsanchez can you please try one more time? :wink:

**Comment by anibalsanchez** [comment]
... hmmm ... I have manually copied the two files... In Global Configuration, I try to save an empty Site Name, it shows the message "Invalid field:  Site Name"... Cancel button does not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4435">issues.joomla.org/joomla-cms/4435</a>.</sub>

**Comment by Fedik** [comment]
@anibalsanchez I just checked without the patch, and got same result as you, 
so I think it is not a regression that made by this pull request .... 
looks like you found some bug in global configuration page :smile:

**Comment by Fedik** [comment]
yes it :bug: on the configuration page, 
there test for `task == "application.cancel"` but must be `task == "config.cancel.application"` on first look

**Comment by zero-24** [comment]
@Fedik do you think we should fix this with this pull or should we open a new for this issue?

**Comment by dgt41** [comment]
@Fedik You are right here: cancel button has `<button onclick="Joomla.submitbutton('config.cancel.application')" class="btn btn-small">`

and the script we inject is :
```javascript
	Joomla.submitbutton = function(task)
	{
		if (task == "application.cancel" || document.formvalidator.isValid(document.getElementById("application-form")))
		{
			Joomla.submitform(task, document.getElementById("application-form"));
		}
	};
```

**Comment by Fedik** [comment]
@zero-24 would be better separate as it is different things  .. I can try make another pull with fix, but at evening

**Comment by zero-24** [comment]
>@zero-24 would be better separate as it is different things .. I can try make another pull with fix, but at evening

Thanks moving here to RTC as the other issue will be handled in a seperate PR by @Fedik Thanks to all!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4435">issues.joomla.org/joomla-cms/4435</a>.</sub>

**Comment by dgt41** [comment]
@test success
before time = 1.004 ms
screen shot 2015-01-15 at 3 36 39

After time = 0.734 ms
screen shot 2015-01-15 at 3 37 22

**Comment by Fedik** [comment]
there fix for cancel button  #5738

**Pull request merged**
