### PR TITLE
[4.0] Workflow stages

### PR DESCRIPTION
**Pull request by brianteeman**
Adjust the column widths to be consistent with all other lists

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bec8102bb6126819dbf26ace2d539e436cb14383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32662">issues.joomla.org/tracker/joomla-cms/32662</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bec8102bb6126819dbf26ace2d539e436cb14383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32662">issues.joomla.org/tracker/joomla-cms/32662</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32662">issues.joomla.org/tracker/joomla-cms/32662</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
