### PR TITLE
Correcting plg_actionlog_joomla language strings

### PR DESCRIPTION
**Pull request by infograf768**
As title says.
These 3 strings needed to be completed as they were quite hard to understand if not wrong.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d2e75b6161907876c223372a0b7f3beb0fd5d147<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22342">issues.joomla.org/tracker/joomla-cms/22342</a>.</sub>

**Review by brianteeman — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d2e75b6161907876c223372a0b7f3beb0fd5d147<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22342">issues.joomla.org/tracker/joomla-cms/22342</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22342">issues.joomla.org/tracker/joomla-cms/22342</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
