### PR TITLE
[4.0] type=list options

### PR DESCRIPTION
**Pull request by brianteeman**
Fields that have a type of list should have a validation=options

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cd58b0f83779d5be6c85d1a5157f6c63880016d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33517">issues.joomla.org/tracker/joomla-cms/33517</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on cd58b0f83779d5be6c85d1a5157f6c63880016d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33517">issues.joomla.org/tracker/joomla-cms/33517</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33517">issues.joomla.org/tracker/joomla-cms/33517</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
