### PR TITLE
[4.0] Remove reference to non-existing class

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes import of `Joomla\Plugin\System\Webauthn\PluginTraits\ButtonsInUserPage` which doesn't exist.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ It seems Appveyor and Drone didn't get the base branch change. Maybe they will if you commit a change, dummy change or update to a change in 4.0-dev, if any, but maybe it's the easiest thing if you redo the PR. Or someone merges it by review.

**Comment by SharkyKZ** [comment]
Branch updated.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a5147c60741a40bcb6a0149184b01ed25ec25739<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29686">issues.joomla.org/tracker/joomla-cms/29686</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a5147c60741a40bcb6a0149184b01ed25ec25739<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29686">issues.joomla.org/tracker/joomla-cms/29686</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29686">issues.joomla.org/tracker/joomla-cms/29686</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
