### PR TITLE
[4.0] Fix output variable

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix output of variable not to be static text.

### Testing Instructions
Code review

or

Log in back end
View page source
Find `$dropdownPosition`

or

Log in back end
Click cog icon
Dropdown displays in the right direction.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 2e3cbd6160e03a51f51f2b14f8f3ea5285ea55c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25815">issues.joomla.org/tracker/joomla-cms/25815</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2e3cbd6160e03a51f51f2b14f8f3ea5285ea55c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25815">issues.joomla.org/tracker/joomla-cms/25815</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
