### PR TITLE
Protostar: missing some RTL code and order rtl classes load

### PR DESCRIPTION
**Pull request by infograf768**
This PR adds the class `rtl` on body when the language is RTL in order to use any `.rtl .something` .
It is added in component.php as well as error.php. Code is similar to index.php. It allows adding specific `.rtl .something` in the rtl.less files.

It also changes the order of loading of the `.rtl .something` present in the template_rtl.less when they are saved into template.css by generatecss.php. 
This because these rtl classes should override their counterpart as set from various .less files when importing.

@mbabker 
Thank you for checking

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
why not use the html dir for that? https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/index.php#L127

Examples:
```css
html[dir=rtl] whateverhtmltag {}
html[dir=rtl] .whatevercssclass {}
```

**Comment by infograf768** [comment]
No opposition to that, but we could use these new notations only for new css as I guess changing the whole process would not be B/C.

**Review by mbabker — APPROVED** [review]

**Comment by brianteeman** [comment]
@infograf768 can you resolve the conflicts with this PR please

**Comment by brianteeman** [comment]
Can you look at resolving the conflicts otherwise this will have to be closed @infograf768

**Comment by brianteeman** [comment]
Closed as the conflicts were not resolved after one year - it can always be reopened if updated

**Comment by infograf768** [comment]
@brianteeman 
PR redone https://github.com/joomla/joomla-cms/pull/19328

**Pull request closed without merging**
