### PR TITLE
Updates the dependencies

### PR DESCRIPTION
**Pull request by laoneo**
Updates the dependencies including the lift to cypress 13 as there was a vulnerability reported in cypress 12.

image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on b12d4eb94c691b10b5b45fe64390812eb7deed90<br /><br />This is not correct. 
You must do a full npm and composer install when you do these updates as there are files that might get updated by other scripts when dependencies are updated.

For example tinmyce and codemirror where the version number in the plugin is updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41538">issues.joomla.org/tracker/joomla-cms/41538</a>.</sub>

**Comment by laoneo** [comment]
Not sure why this is not part of the update command @dgrammatiko ?

**Comment by dgrammatiko** [comment]
`rpm run update`: https://github.com/joomla/joomla-cms/blob/17585ed34a69de1e715d55da29d4eedc3f1a9ea0/package.json#L26 ?

**Comment by laoneo** [comment]
Thanks, fixed it

**Comment by Hackwar** [comment]
Something is wrong here. The `vue` package is a hard dependency, but I can't find it as a full package in the package-lock.json.

**Comment by Hackwar** [comment]
In any case, since this PR already contains those updates, I'm closing #41451 and #41455.

**Comment by laoneo** [comment]
There are over 7'000 removald un the package lock file in this pr. Not sure if this has something to do with a never npm version since I did it last time.

**Comment by brianteeman** [comment]
I tried and built https://github.com/joomla/joomla-cms/pull/41545 for comparison

**Comment by laoneo** [comment]
@brianteeman which npm version did you use?

**Comment by laoneo** [comment]
I'v just did a fresh install of the package from drone and all works. Nothing indicates that there is an error in an asset. Also the system tests are running through, when they do not hit the timeout.

**Comment by brianteeman** [comment]
> @brianteeman which npm version did you use?

8.19.2

**Comment by dgrammatiko** [comment]
@laoneo could you restore the indentation to 2 spaces instead of 4 for the package.json and the lock file?

**Comment by laoneo** [comment]
Reverted the last commit

**Comment by laoneo** [comment]
> > @brianteeman which npm version did you use?
> 
> 8.19.2

That might be the issue as I'm on 9.6.7.

**Comment by laoneo** [comment]
@dgrammatiko gets the same effect, so we are fine with this pr here as I do mainly the updates
image

**Comment by dgrammatiko** [comment]
FWIW it's time to push node/npm as 16 that we are currently have as minimum goes EOL in few weeks. It's on my todo list

**Comment by laoneo** [comment]
But I would do it on 5.0 then only.

**Pull request merged**
