### PR TITLE
[4.0] Cassiopeia - fixes fluid width option

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #26887 .

### Summary of Changes
Fixes the fluid with option in cassiopeia template settings.

### Testing Instructions
Apply patch and run `node build.js --compile-css` to update the changed SCSS.

Enable 'Fluid Width' option in template settings. Check frontend.

### Before
image

### After
image

### CODE REVIEW

**Comment by ciar4n** [comment]
I think this issue came about when removing the IE11 fallback, the fluid width was not considered (I'm guessing by me).

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 3617771dc5b449782f790ed3e9337919b15df86c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27301">issues.joomla.org/tracker/joomla-cms/27301</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3617771dc5b449782f790ed3e9337919b15df86c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27301">issues.joomla.org/tracker/joomla-cms/27301</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27301">issues.joomla.org/tracker/joomla-cms/27301</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 648199cae1b7abe58f2bcbfed0412855cefa4b6b<br /><br />Do not remove "installation" folder, as I did, or else running node command will not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27301">issues.joomla.org/tracker/joomla-cms/27301</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
