### PR TITLE
[4.0] Remove show_associations field of association is not enabled

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This simple PR removes the field show_associations field of association is not enabled. It causes fatal error while saving article when I tested PR #12414 and @Hackwar had to add a check (which I think not necessary) to prevent the error.

Plus, it also removes some unused variables/lines of code which can be seen easily if you use a good IDE like phpstorm.

### Testing Instructions
Apply patch, try to save article and confirm nothing broken. Maybe code review should be enough.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 802acf8bb490638521a60eee3d28d7c929d5a47b<br /><br />ok on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23501">issues.joomla.org/tracker/joomla-cms/23501</a>.</sub>

**Comment by astridx** [comment]
I applied this patch and I could create and save an article.

I see no change in the `options` tab of `com_content`.
The field `show_associations` is shown when the Plugin `System - Language Filter` is active and it is not shown when the Plugin `System - Language Filter` is not active - with and without this patch. 

Perhaps we can delete the line https://github.com/joomla/joomla-cms/blob/88d5f959ded0da40d68551ea228c43fc8abe717c/administrator/components/com_content/Model/ArticleModel.php#L905 in this PR, too.

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 88d5f959ded0da40d68551ea228c43fc8abe717c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23501">issues.joomla.org/tracker/joomla-cms/23501</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 RIPS please

**Comment by zero-24** [comment]
> @zero-24 RIPS please

RIPS seams to be fine?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
