### PR TITLE
[4.1 Scheduled Tasks] Image path does not exist

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Create an image resizing task, select any directory you like. Then change the title of the directory you chose. Run the task. It's strange that when it's finished, we won't be told anything in the modal window, but we'll get a warning in the log file that the path to the image exists, which is not true.

### CODE REVIEW

**Comment by richard67** [comment]
The changed language string is used here: https://github.com/joomla/joomla-cms/blob/4.1-dev/plugins/task/checkfiles/checkfiles.php#L86-L91 :

```
		if (!Folder::exists($path))
		{
			$this->logTask(Text::_('PLG_TASK_CHECK_FILES_LOG_IMAGE_PATH_NA'), 'warning');

			return TaskStatus::NO_RUN;
		}
```

So from code review it's clear that this PR here is right.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9e8a6a5d7a06580c26b06116a38b183a3199915f<br /><br />Code review. It's obvious that this PR is right, details see in my previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36735">issues.joomla.org/tracker/joomla-cms/36735</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9e8a6a5d7a06580c26b06116a38b183a3199915f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36735">issues.joomla.org/tracker/joomla-cms/36735</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36735">issues.joomla.org/tracker/joomla-cms/36735</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36735">issues.joomla.org/tracker/joomla-cms/36735</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36735">issues.joomla.org/tracker/joomla-cms/36735</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
