### PR TITLE
[4.3] Remove dead code from plugin field

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Removes code that fixed the priority order loading of the joomla api token field. After this patch child templates will now correctly inherit. As well (not sure if it's a good thing or not) com_users overrides will be able to override this layout like all other JLayouts

### Testing Instructions
Ensure the form field continues to render. As an optoinal bonus If you have a child template compatible template available you'll be able to override it correctly now

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 52d9dd6349c2a4c7352967fa457ee1b29ca39ff6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39530">issues.joomla.org/tracker/joomla-cms/39530</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 52d9dd6349c2a4c7352967fa457ee1b29ca39ff6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39530">issues.joomla.org/tracker/joomla-cms/39530</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39530">issues.joomla.org/tracker/joomla-cms/39530</a>.</sub>

**Comment by obuisard** [comment]
Thank you George @wilsonge

**Pull request merged**
