### PR TITLE
Removed the save warning option in TinyMCE editor setting

### PR DESCRIPTION
**Pull request by shivamdiehard**
Pull Request for Issue [https://issues.joomla.org/tracker/joomla-cms/14466](url) .

### Summary of Changes
Removed the Save Warning option in TinyMCE editor plugin option.

### Testing Instructions
1. Apply the patch.
2. Go to add new article
3. Make some changes in the editor and try to navigate away without saving

### Result
The Save warning will still come.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 95265cb7d4b5f26f2e5d9f5a002d22184514a8a2<br /><br />"Save Warning"-Option is removed from Plugin, but no Warning is still coming.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14488">issues.joomla.org/tracker/joomla-cms/14488</a>.</sub>

**Comment by shivamdiehard** [comment]
Did you type something in the editor before moving away??. I think the warning should come.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14488">issues.joomla.org/tracker/joomla-cms/14488</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
"Moving away" means "Close Tab", not as i suggest click on "Close"-Tab.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 95265cb7d4b5f26f2e5d9f5a002d22184514a8a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14488">issues.joomla.org/tracker/joomla-cms/14488</a>.</sub>

**Comment by shivamdiehard** [comment]
Moving away/Navigate away means clicking on back button after you have made changes into editor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14488">issues.joomla.org/tracker/joomla-cms/14488</a>.</sub>

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on 95265cb7d4b5f26f2e5d9f5a002d22184514a8a2<br /><br />Either clicking back button in the browser, either trying to close it, this patch still shows the warning.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14488">issues.joomla.org/tracker/joomla-cms/14488</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@shivamdiehard could you please fix the conflicts, thanks

**Comment by zero-24** [comment]
Don't we need to deprecate the strings too?

**Comment by rdeutz** [comment]
@zero-24 makes sense

**Comment by zero-24** [comment]
Now we merged it without deprecation?

**Comment by zero-24** [comment]
As this was a zero files change commit I have redone the PR against staging see: https://github.com/joomla/joomla-cms/pull/16697 cc @rdeutz

**Comment by rdeutz** [comment]
I reviewed the change before and missed that now zero files are changed, but the good site of it is, it can't break things :-)

**Pull request merged**
