### PR TITLE
[4.0] WebAsset correct user.css dependencies and sorting

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #27867

### Summary of Changes

I have corrected dependencies for user.css asset, they was missed, that lead to incorrect sorting.
And made a little improvement for sorting.

### Testing Instructions

Please have a look #27867 for detail.
Create `user.css` and make sure the order is correct.
Do the test for both **Atum** and **Cassiopeia**.

Also repeat the test for `user.js` for **Cassiopeia** template

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ffa3f8e00193f31726b979ccf81d179d7c0b7f4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27872">issues.joomla.org/tracker/joomla-cms/27872</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ffa3f8e00193f31726b979ccf81d179d7c0b7f4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27872">issues.joomla.org/tracker/joomla-cms/27872</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27872">issues.joomla.org/tracker/joomla-cms/27872</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
