### PR TITLE
[4] com_content.article view. Remove redundant  `if $this->item->pagination`

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
- The second part of condition `!empty($this->item->pagination) && $this->item->pagination` is redundant. "If it's not empty then it is" ;-)
- See other similar code lines in the file where this double check has been removed already a long time ago.

### Testing Instructions
- Code review.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on f2b870316b0c6e4b17e0b5d7adac8b3f906bace7<br /><br />Tested successfully in Joomla 4.1.4-rc2-dev of 23 May.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37861">issues.joomla.org/tracker/joomla-cms/37861</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f2b870316b0c6e4b17e0b5d7adac8b3f906bace7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37861">issues.joomla.org/tracker/joomla-cms/37861</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37861">issues.joomla.org/tracker/joomla-cms/37861</a>.</sub>

**Comment by chmst** [comment]
I cannot find the code in may 4.1-dev branch. 
https://github.com/joomla/joomla-cms/blob/4.1-dev/components/com_content/tmpl/article/default.php#L138
This change was made a year ago https://github.com/joomla/joomla-cms/commit/733786ff08cf3b7aba085c64600317c2bcd79118
or am I missing something?

**Comment by richard67** [comment]
> I cannot find the code in may 4.1-dev branch. https://github.com/joomla/joomla-cms/blob/4.1-dev/components/com_content/tmpl/article/default.php#L138 This change was made a year ago [733786f](https://github.com/joomla/joomla-cms/commit/733786ff08cf3b7aba085c64600317c2bcd79118) or am I missing something?

@chmst Your link goes to line 138, but this PR changes line 95. The old commit changed line 43.

**Comment by chmst** [comment]
oops - thanks, this code needs more improvement ;)

**Comment by Quy** [comment]
Thanks

**Pull request merged**
