### PR TITLE
Menu redirect fix - re-applied and pulled.

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue pull request #16197 re-do to allow tests to pass.

### CODE REVIEW

**Comment by rdeutz** [comment]
travis is not running on this PR, has anyone an idea why?

**Comment by mbabker** [comment]
According to Travis...

> abuse detected: known offender (request looked fishy)

The webhooks to the issue tracker failed too.

**Comment by tonypartridge** [comment]
Darnit, and I thought me and Travis were friends.

**Comment by infograf768** [comment]
Then what?

**Comment by rdeutz** [comment]
Some else should make the PR

**Comment by infograf768** [comment]
OK, will do

**Comment by tonypartridge** [comment]
Seriously? So the answer is I can't make PR's at all so lets not bother sorting. Now I know I shouldn't have bothered.

**Comment by rdeutz** [comment]
We need to have PR where our test are running, figure out what happened with you and travis or do you thing we should look into it?

**Comment by brianteeman** [comment]
@tonypartridge maybe its just an issue on this one. Please create a new pr for anything at all (we can delete it after testing) so we can test if it was a one off. If that PR gets blocked as well then we can look further into it to make sure that you are unblocked. It is not acceptable for you to be blocked completely on travis and I dont think anyone was thinking that would be.

**Comment by tonypartridge** [comment]
Closed as Travis said no.

**Comment by infograf768** [comment]
Posted your PR here
https://github.com/joomla/joomla-cms/pull/16233

and crossing fingers I am not also expelled by Travis 😃

**Comment by infograf768** [comment]
We have one Travis error
```
1) JComponentRouterRulesMenuTest::testPreprocessLanguage

Failed asserting that two arrays are equal.

--- Expected

+++ Actual

@@ @@

 Array (

-    'Itemid' => '47'

 )

/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/component/router/rules/JComponentRouterRulesMenuTest.php:218

```

**Comment by brianteeman** [comment]
thats the same travis error that the original PR had that was reverted iirc

**Comment by rdeutz** [comment]
yes it is, now we need to find out if the test is not good or do we have to change the code

**Comment by brianteeman** [comment]
and on that note i will step back

**Pull request closed without merging**
