### PR TITLE
[4.0] Add dashboard module

### PR DESCRIPTION
**Pull request by brianteeman**
Maybe its just me but I was looking for a specific dashboard module. I think better text is Add module to the dashboard

### Before
image

### After
image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 553554598b686b7b0ac70c50966fe885440aae81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25871">issues.joomla.org/tracker/joomla-cms/25871</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 553554598b686b7b0ac70c50966fe885440aae81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25871">issues.joomla.org/tracker/joomla-cms/25871</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25871">issues.joomla.org/tracker/joomla-cms/25871</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
