### PR TITLE
[4.0] com_contacts sidebar

### PR DESCRIPTION
**Pull request by brianteeman**
This is some additional corrections to be applied after #23366 to complete the removal of the sidebar for com_contacts

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e25580c51cf34a2b06122d41ce5dd67912d9fb2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25304">issues.joomla.org/tracker/joomla-cms/25304</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on e25580c51cf34a2b06122d41ce5dd67912d9fb2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25304">issues.joomla.org/tracker/joomla-cms/25304</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25304">issues.joomla.org/tracker/joomla-cms/25304</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix the conflict here please so I can get this in :)

**Comment by brianteeman** [comment]
Conflicts resolved

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
