### PR TITLE
[4.0][a11y] 'Print' button changes from styled link to button

### PR DESCRIPTION
**Pull request by tarot-ray**
For A11Y reasons, the 'Print' button is changed from an anchor tag to a button tag.

Pull Request for Issue # .

### Summary of Changes

'Print' button changed from an anchor tag to a button tag.

### Testing Instructions

Check that the screenreader has improved behaviour.

### Expected result

Better A11Y behaviour for this button

### CODE REVIEW

**Comment by tarot-ray** [comment]
image

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 62dbf8616d4a0470d9d0ece598f40f169ee4313c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24006">issues.joomla.org/tracker/joomla-cms/24006</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 62dbf8616d4a0470d9d0ece598f40f169ee4313c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24006">issues.joomla.org/tracker/joomla-cms/24006</a>.</sub>

**Comment by brianteeman** [comment]
I still believe that there is no place for a print button on a modern web site. https://github.com/joomla/joomla-cms/pull/19393

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24006">issues.joomla.org/tracker/joomla-cms/24006</a>.</sub>

**Comment by brianteeman** [comment]
From @wilsonge here https://github.com/joomla/joomla-cms/pull/19393#issuecomment-414116530
> I'm totally happy to remove print - this has been superseded by print stylesheets on pretty much all modern websites (and you'd use that to disable most the module positions in Joomla). I'm unsure as to whether we should remove the email functionality. Probably yes. But not 100%

**Comment by dgrammatiko** [comment]
@infograf768 @brianteeman @wilsonge fwiw Bootstrap 5 is completely removing **all** the css related to print. Just saying...

**Comment by wilsonge** [comment]
But not because it's a bad idea - just because there's too many bugs (reference PR https://github.com/twbs/bootstrap/pull/28339 ) - and obviously too early to say but given by the +1's on the comment it's possible the utility classes might stay too. Either way nothing there tells me that using print stylesheets is a bad idea. Plus this is just fixing a link to a button to fix a11y compliance. Until someone does a PR to drop the print button in favour of just the CSS stylesheet then this entire discussion is useless...

**Comment by dgrammatiko** [comment]
> that using print stylesheets is a bad idea

No they're not bad idea BUT they're very specific to every site. The idea to have something that works across different implementations just falls sort. 
Also for anyone really interested about doing printing correctly from their sites I would suggest them to take a look at: https://github.com/BafS/Gutenberg
(nothing to do with the known Gutenberg thing of that other CMS)

**Comment by brianteeman** [comment]
I dont see what print.css has to do with if we should have this useless button or not

**Comment by infograf768** [comment]
IMHO, we may not need the print button in this window, but we need it next to the article when in blog and featured as I have demonstrated in #19393 using css or not.

**Comment by brianteeman** [comment]
I still disagree. The browser is more than capable of printing the page. The idea of a print button is not seen anywhere else on the web any more except for joomla.

**Comment by infograf768** [comment]
A page, yes, but not a single article. Period.

**Comment by brianteeman** [comment]
So they click and read the entire article. Again I ask where else but joomla do we see this

**Comment by dgrammatiko** [comment]
FWIW the majority of the web is consumed by mobile devices where the idea of printing a page is awkward. Users most probably will share a page than printing it. It's not 2006 anymore...

**Comment by infograf768** [comment]
Mobiles are not the only way to browse the web... As I have demonstrated, one may need to print a pdf of a single article (without the modules, menus, etc.) without sending people to the website.
This discussion goes nowhere. The matter is not to be in 2006 or not. It is a very useful feature for some and getting rid of it because you personally do not use it is not a reason to take it off.

**Comment by mbabker** [comment]
The ability to print things is not being removed.  Nobody is advocating for killing support for the browser's print functionality.  Nobody is removing the `component.php` file from templates that the current JHtml helpers route requests to print an article to.  What is being suggested is that core doesn't have a print button anymore.  You can still build one and include it, unless you are suggesting that it is 100% impossible for a template or plugin to recreate [this helper](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Service/HTML/Icon.php#L204-L231) which generates the correct "print friendly" URL (and comes with some bloatware, the button actually opens as a popout window; it's the `$url` variable you're most interested in there), and even "print friendly" is objective at best.

**Comment by infograf768** [comment]
What you are advocating (once more, I never said anyone wants to prevent browser printing...) is blantly to take off this print possibility from core and force users to make a specific plugin or get a template which implements the functionality as all the other solutions don't work as I demonstrated.

What I am advocating is simple: it is there, it does not create any problem. 

We could, if you wish and code it, prevent displaying that button when using a mobile.

This is not a valuable fight for a smaller joomla to maintain..., it is not like weblinks, it is small and handy.

Instead of losing time on such small aspects which, once more, are useful to some, exist and work, better concentrate on the real issues that prevent 4.0 to even go to beta (workflow, modals, custom admin menus, wrong behavior of installation (session, etc.), etc. etc.

**Comment by dgrammatiko** [comment]
> What I am advocating is simple: it is there, it does not create any problem.

Actually it creates a perception problem. Newcomers see this as an outdated irrelevant feature and thus getting a bad impression for the product...

**Comment by brianteeman** [comment]
and this is why people consider Joomla to be old hat and not suitable for the modern web

**Comment by mbabker** [comment]
If you can't duplicate those 30 lines of code (shorter if you take out the bit for opening it in a popout window) into a plugin or template and keep the functionality as it exists in core, there are bigger problems than whether core has a button someone can click to go to a URL that only includes the component output to print the page.

**Comment by infograf768** [comment]
For sure you know better what is "not suitable for the modern web" or what is an "outdated irrelevant feature"
What I see is that this CMS becomes more and more complex and prevents users which are no php, js or css specialist to customize it themselves.

What some want here apparently is to reserve Joomla to a few site integrators and template makers.
That was not the purpose of its foundation. Open Source was not its only advantage. It was supposed to be free, easy to work with and customize.

It reminded me at the time of the welcome arrival of Apple vs DOS and why it changed drastically the way computers were considered among people that were no specialists, while Microsoft products were reserved to the informatician class which defended its sandwich by keeping things as hidden as possible.

I will not post anymore concerning the print issue.

**Comment by zwiastunsw** [comment]
**Can we close this PR?** 
The subject of this PR was only to improve the accessibility of the Print button. **That's all. And only that, nothing more.** 
- Was the Print button encoded incorrectly? Yes.
- Did PR fix the error? Yes.
- Did it improve accessibility? Yes.

So please thank you ..... for the work done. 

It would also be polite if you apologised for unnecessary work, for wasting time unnecessarily. Because this is not @tarot-ray  is responsible for the fact that the Print button exists in the Joomla code. He is not responsible for the fact [that someone could not make the right decision earlier](https://github.com/joomla/joomla-cms/pull/19393).
 
If it happened once, one could say: *It happened*. But at the same time you were fervently discussing the [removal of the Cancel button in the registration form](https://github.com/joomla/joomla-cms/pull/24007). By chance, this was also PR reported by @tarot-ray  

Today I received a message: 
> I am losing the motivation to carry on. Have you seen the conversation that is going on about the 'Print' button? It's like Brexit. It goes on forever, no-one agrees with anyone else and, in the end, it is probably better to not do these things, at all.

These are the consequences of your discussions, dear gentlemen!  

A discussion is needed. The discussion is creative. Without discussion there is no cooperation and good action. But such a discussion kills people's willingness to act. 

Please close this PR.

**Comment by mbabker** [comment]
> It would also be polite if you apologised for unnecessary work, for wasting time unnecessarily.

I'm going to be blunt here.  Everyone who is investing time on user interface changes right now is potentially (probably) wasting their time doing work that is going to be overwritten by another group and cause the work people are doing now (audits, testing, etc.) to either be wasted effort or require to be completely re-done.  People discussing whether a feature should exist in core or not isn't a waste of time, unless you are someone who unfortunately gets sucked into the conversation by some unrelated action (i.e. submitting a pull request to change something).  People making proposals to change things in existing code generally are not wasting their time unless they know beforehand what they're proposing be changed is going to go away or their work be immediately tossed out by someone else's work.

**Comment by zwiastunsw** [comment]
Read again what I wrote. And try to understand. 
Discussion is needed. In the right place and at the right time.
If someone wanted to discuss again if the button is needed, they should open a new PR or issue.

**Comment by tarot-ray** [comment]
We are JAT. Our sole task is to improve A11Y in Joomla 4. @zwiastunsw and others identify these issues and me and others make a PR of each. The PR needs to be merged, so approval is required.

If things change and the code changes, later, the item (that has been identified, as requiring change to make it A11Y compatible - or for any other reason) is removed, this is not relevant to us. As @zwiastunsw says, this should require a different PR by someone else at some other time. 

There are guidelines, which JAT has (partially) prepared, that need to be followed, if that happens. That way, no A11Y issue should show up, in any future developments. N.B. These guidelines are for external developers to use, also, so that in time, Joomla based sites can become totally A11Y compatible.

BTW: @zwiastunsw is a very serious person, which is why his work is so extensive, accurate and meaningful. That's why I toned down the rhetorical humour, when I said "I am losing the motivation to carry on.", in my PM to him. If it had been a conversation with an English speaking person with a huge sense of humour, I would have said "I'm losing the will to live.", which is obviously not serious. 

I shall carry on, of course, but I may become demotivated again, if any PR I make is not treated for what it is - an intention to improve A11Y compatibility in existing code - and nothing else. 

I hope that this statement is reasonable and clear.

**Comment by wilsonge** [comment]
Thankyou. Merging this does not change the position I have on this that Brian mentioned. But neither is implementing that a blocker for this simple a11y fix

**Pull request merged**
