### PR TITLE
Fix offline image selector position for Hathor

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #8423 
#### Summary of Changes

The positioning of the image selector was way off on Hathor, which this PR fixes.
#### Testing Instructions

Go to **Global Configuration** >> **Site**

**Before:**
dec36a88-8a3a-11e5-996a-4f2911e94ebc

**After:**
after

### CODE REVIEW

**Comment by C-Lodder** [comment]
Let me know if I need to run the `build generatecss.php`

**Comment by brianteeman** [comment]
Thanks for creating this I will take a look tomorrow

**Comment by brianteeman** [comment]
@C-Lodder it works but i found another place with the same bug that isnt fixed by this change ;(

http://i.tee.mn/tojN.png

**Comment by C-Lodder** [comment]
ahh balls. I'll fix that at some point today then

**Comment by C-Lodder** [comment]
@brianteeman - updated

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 3e5e2c99b42a0acb2ac9baa0fafdb355423664bd<br /><br />Works now on both places. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11534">issues.joomla.org/joomla-cms/11534</a>.</sub>

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 3e5e2c99b42a0acb2ac9baa0fafdb355423664bd<br /><br />Tested successfully in global config options and tested article editing continued to work as usual<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11534">issues.joomla.org/joomla-cms/11534</a>.</sub>

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11534">issues.joomla.org/joomla-cms/11534</a>.</sub>

**Pull request merged**
