### PR TITLE
s/equivilents/equivalents & remove trailing periods from comments

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/equivilents/equivalents & remove trailing periods from comments

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b35b25a2ec611a4ef41472388cee67383347b031<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23005">issues.joomla.org/tracker/joomla-cms/23005</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor The word "equivilents" also appears in file "libraries\bootstrap.php".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23005">issues.joomla.org/tracker/joomla-cms/23005</a>.</sub>

**Comment by PhilETaylor** [comment]
changed in libraries\bootstrap.php as well now.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 583ffca79d184c6b7a5752b768a0a1236523343d<br /><br />Code review + check that this PR covers all occurrences of wrong English "equivilents" (case-insensitive) in Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23005">issues.joomla.org/tracker/joomla-cms/23005</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 583ffca79d184c6b7a5752b768a0a1236523343d<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23005">issues.joomla.org/tracker/joomla-cms/23005</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23005">issues.joomla.org/tracker/joomla-cms/23005</a>.</sub>

**Pull request merged**
