### PR TITLE
[4.0] Fix language constant

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #25959.

### Summary of Changes
Fix language constant.

### Testing Instructions
1. Log in into Joomla 4.x Alpha 12dev administration
2. Click on Add Module to the Dashboard in any admin dashboard

### Actual result
String not translated.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 613c011495f4fb22a82415649893027a5d4be653<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26049">issues.joomla.org/tracker/joomla-cms/26049</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 613c011495f4fb22a82415649893027a5d4be653<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26049">issues.joomla.org/tracker/joomla-cms/26049</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26049">issues.joomla.org/tracker/joomla-cms/26049</a>.</sub>

**Comment by jeckodevelopment** [comment]
Thanks @Quy

**Comment by infograf768** [comment]
Tks

**Pull request merged**
