### PR TITLE
[4.0] Notification icons

### PR DESCRIPTION
**Pull request by brianteeman**
The order of the notification icons on the dashboard is determined by the order of the quickicon plugins

This PR changes the order based on importance - so that Joomla Update is first.

Note that phpversioncheck is last because it is not displayed in the notifications section but in the messages.

Note this is for new installs only as a user could have customised the ordering themselves

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 04ab84ae1e5ef40dc39a52fd43df8fc76fea0193<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34226">issues.joomla.org/tracker/joomla-cms/34226</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 04ab84ae1e5ef40dc39a52fd43df8fc76fea0193<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34226">issues.joomla.org/tracker/joomla-cms/34226</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34226">issues.joomla.org/tracker/joomla-cms/34226</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
