### PR TITLE
Nishadi Drag and Drop functionality for Featured Articles - Fixes #9564

### PR DESCRIPTION
**Pull request by Kubik-Rubik**
Pull Request for Issue #9564 
#### Summary of Changes

Fixed merge conflicts.
#### Testing Instructions

Is already tested (origin PR is RTC), can be merged directly.

All kudos to @nishadi!

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
please don't revert the changes i made here
https://github.com/joomla/joomla-cms/pull/10062/files

**Comment by Kubik-Rubik** [comment]
@andrepereiradasilva Thanks for the hint, I will update the PR.

**Comment by andrepereiradasilva** [comment]
ok. just check the history https://github.com/joomla/joomla-cms/commits/staging/administrator/components/com_content/views/featured/tmpl/default.php

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on bb266a9233154417977175451a03534a5fde4843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10313">issues.joomla.org/joomla-cms/10313</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bb266a9233154417977175451a03534a5fde4843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10313">issues.joomla.org/joomla-cms/10313</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10313">issues.joomla.org/joomla-cms/10313</a>.</sub>

**Comment by rdeutz** [comment]
@Kubik-Rubik please fix the CS issues

**Comment by andrepereiradasilva** [comment]
@rdeutz there are no cs issues where, yesterday travis has crazy. this is ok.

**Comment by rdeutz** [comment]
@andrepereiradasilva, ok, I have restarted travis, we will see :-)

**Comment by mbabker** [comment]
Restarting Travis won't fix it because it's based on the branch this PR came from, not a merge of this branch onto staging.  @Kubik-Rubik would need to merge in staging to get a clean build.

**Comment by andrepereiradasilva** [comment]
travis ok :)

**Comment by rdeutz** [comment]
@mbabker seems it worked, or do you expect that Jenkins will show the middle finger

**Comment by mbabker** [comment]
Bleh, whatever.  Hit the damn button.  If it breaks, blame George.

**Comment by andrepereiradasilva** [comment]
LOL!

**Pull request merged**
