### PR TITLE
Fix log categories

### PR DESCRIPTION
**Pull request by codeling**
As recommended in https://github.com/joomla/joomla-cms/pull/5165, rebased the adding of categories for all log entries on staging branch.

For the intent, see above linked pull request

### CODE REVIEW

**Comment by n9iels** [comment]
@codeling can you provide test instructions for this pull request? So when can this this on the Dutch Joomla! Pizza Bugs and Fun

**Comment by codeling** [comment]
@n9iels No unfortunately I can't. As I said above: "I cannot even tell how exactly to reproduce the messages shown above; I can only say that they occasionally appear on my production system."

**Comment by roland-d** [comment]
@codeling There is no list of existing/approved category names. 

Looking at the changes, only a category has been added which is actually an optional argument. Specifying no category means the same as specifying a category that is supported by a logger.

Although we do need a way to test this before we can merge it.

**Comment by w13ear** [comment]
I have not tested this item.<br /><br />Hello @codeling 

Thank you for your contribution.

The last comment here was on 22 oct 2015. So the question is, Is this issue/pull request still valid?
if so please provide clear test instructions to be able to test / reproduce this issue.
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5170">issues.joomla.org/joomla-cms/5170</a>.</sub>

**Comment by brianteeman** [comment]
Its very unclear if this is correct or desired and can not be tested - setting to Needs Review for a Maintainer to make a decision on closing or merging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5170">issues.joomla.org/joomla-cms/5170</a>.</sub>

**Comment by roland-d** [comment]
I am going to close this PR, since there is no proper way to reproduce this issue. Forcing a category shouldn't be necessary if you want it all in one log. Perhaps it would be better to not write to logs that have a category assigned but that would require a new pull request.

@codeling Thank you for your contribution.

**Comment by mbabker** [comment]
Part of the problem (I don't remember if that has been fixed either) is a log message with no category will be broadcast to all loggers regardless of include/exclude configuration.  So one should ensure log messages are always assigned to a category and that JLog handles a no-category scenario correctly.  This should be re-opened and merged.

**Comment by codeling** [comment]
> I am going to close this PR, since there is no proper way to reproduce this issue.
OK.

> Forcing a category shouldn't be necessary if you want it all in one log.
I don't want all in one logfile, I want a separate logfile which should not get entries without categories.

> Perhaps it would be better to not write to logs that have a category assigned but that would require a new pull request.
That could be a solution. But where then would log entries with no category get logged? Nowhere? Otherwise one would have to have a specific "catch-all" category...
The simplest solution to me still is to have log categories for all log entries.

**Pull request closed without merging**
