### PR TITLE
Added dateStart and dateEnd for the calendar date range set.

### PR DESCRIPTION
**Pull request by kirapwn**
### Steps to reproduce the issue

For now, it is not possible to set Min date and Max date for Calendar control so as to define range of dates.
##### Something like

minDate="16-10-2014" AND maxDate="16-10-2015"
### Actual result

Both Attributes are missing.
### Additional comments

See #4801

For testing:

add dateStart and/or dateEnd eq. dateStart="16-10-2014" dateEnd="17-10-2015" as calendar field params.

### CODE REVIEW

**Comment by Hackwar** [comment]
Please fix the codestyle issue that travis reports.

**Comment by brianteeman** [comment]
I submitted a PR to your repo to fix the codestyle change. If you apply it then it should pass travis (the codechecker)

**Comment by roland-d** [comment]
Hello @kirapwn 

Thank you for your contribution.

Can you please follow up on the unsuccessful test results?

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4814">issues.joomla.org/joomla-cms/4814</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4814">issues.joomla.org/joomla-cms/4814</a>.</sub>

**Comment by merijndk** [comment]
Has this ever been added?

**Comment by roland-d** [comment]
@skunheal No it has not since there has been no follow-up

**Pull request closed without merging**
