### PR TITLE
[4.3] Migrate quickicon downloadkey plugin to services

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Migrate the quickicon downloadkey plugin to service providers and use SubscriberInterface.

### Testing Instructions

- Install an extension with providing a download key
- Check if quickicons are still working

image
image

### Actual result BEFORE applying this Pull Request

Downloadkey quickicon is working

### Expected result AFTER applying this Pull Request

Downloadkey quickicon is working (and the other quickicons are still displayed)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Guess this here should be lower case as well https://github.com/joomla/joomla-cms/pull/39168/files#diff-6886871adeab8130a00db34ba210255b45c247430a320dc497c4ffd88c06ee13R5

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 3ad401bf1a27532ec205ef088ede43b50d805bda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39168">issues.joomla.org/tracker/joomla-cms/39168</a>.</sub>

**Comment by heelc29** [comment]
> Guess this here should be lower case as well

Done

**Review by laoneo — APPROVED** [review]

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 254dcee08cb4817aa9decf80176f5cf943dff415<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39168">issues.joomla.org/tracker/joomla-cms/39168</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39168">issues.joomla.org/tracker/joomla-cms/39168</a>.</sub>

**Comment by obuisard** [comment]
Great work @heelc29. Thank you!

**Comment by heelc29** [comment]
Thanks

**Pull request merged**
