### PR TITLE
[4.0] grayscale and hue background

### PR DESCRIPTION
**Pull request by brianteeman**
In the repaint the background image was removed and this has had the side effect of breaking the ability to make the screen monochrome. This PR ~reverts~ fixes that change.

To test apply the pr and rebuild the css

Then go to the template admin styles for admin and set the color to monochrome

Before this PR the background stays blue
With this PR the background is monochrome

pr for #33602

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f1ed16ee9ca61bb20f6d3e6631ae0c7e2385392e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33636">issues.joomla.org/tracker/joomla-cms/33636</a>.</sub>

**Comment by brianteeman** [comment]
I am not in love with the background pattern but it was the only solution I could find for this problem. Maybe someone can find a better solution

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f1ed16ee9ca61bb20f6d3e6631ae0c7e2385392e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33636">issues.joomla.org/tracker/joomla-cms/33636</a>.</sub>

**Comment by richard67** [comment]
> I am not in love with the background pattern but it was the only solution I could find for this problem. Maybe someone can find a better solution

@ciar4n Do you have an idea if there is a way to fix the monochrome background being not monochrome issue without using that background pattern?

**Comment by Fedik** [comment]
hm, I wonder how the pattern fixing the color?

Revert all your changes, and try just:

```css
&.monochrome {
  filter: grayscale(1);
  &::after {
      position: fixed;
      top: 0;
      left: 0;
      z-index: -1;
      width: 100%;
      height: 100%;
      content: "";    
      background: var(--atum-bg-dark-5);
  }
}
```

In some reason `filter: grayscale(1);` does not applies to the element background, but applies for children.

**Comment by richard67** [comment]
@brianteeman Could you check the above comment by @Fedik and maybe implement it that way?

**Comment by brianteeman** [comment]
Changed the code to use @fedik version - thanks and to keep @PhilETaylor happy does not reintroduce the background

**Comment by PhilETaylor** [comment]
>  keep @PhilETaylor happy does not reintroduce the background

Wasn't the background pattern meant to be a major new feature of Joomla 4 (2017 edition)... 

https://magazine.joomla.org/images/2017/12/j4backend_design/20171204_Joomla_Pattern.pdf

**Comment by brianteeman** [comment]
you wanted it removed so its removed

**Comment by richard67** [comment]
@Quy @sandramay0905 Could you test again? There has been made a change. Thanks in advance.

**Comment by PhilETaylor** [comment]
> you wanted it removed so its removed

Factually correct. 

I [said 4 days ago](https://github.com/joomla/joomla-cms/pull/33100#issuecomment-832900948):

> Also now the patterned background (a personal dislike of mine) is visual and messes with my head on empty states, and bleeds into the learn more button

Nothing in that sentence is asking for it to be removed. 

I also [raised an issue detailing the issue with it and Empty States](https://github.com/joomla/joomla-cms/issues/33563) as a 

> reminder to revisit the transparency of the icons and the Learn More buttons 

At no time did I "want" or demand that it was removed. Please do not put words into my mouth.

**Comment by brianteeman** [comment]
I'm just fixing a bug after the changes made in the repaint

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on a0260b213165d1b38e01d06419d3d296635bb328<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33636">issues.joomla.org/tracker/joomla-cms/33636</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0260b213165d1b38e01d06419d3d296635bb328<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33636">issues.joomla.org/tracker/joomla-cms/33636</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33636">issues.joomla.org/tracker/joomla-cms/33636</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
