### PR TITLE
[4.0] Remove "cardGrey" chrome

### PR DESCRIPTION
**Pull request by Bakual**
As written in https://github.com/joomla/joomla-cms/pull/30729, the "cardGrey" chrome is basically the same chrome as the "card" (once #30729 is merged) chrome. It just has an added "card-grey" module class.

However the same can be achieved by using the "module class" parameter in the module options and add "card-grey" there.

### Summary of Changes
* Removes the chrome layout /templates/cassiopeia/html/layouts/chromes/cardGrey.php
* Changes the styles of the positions which were using it to "card". That is "top-a", "main-top", "main-bottom" and "bottom-a".

### Testing Instructions
* Make sure to have the other PR applied as well, otherwise the chrome will not be found and you get some ugly display. Since it's RTC already, chances are high it's merged soon.
* Add the class "card-grey" to the module class parameter in your module

### Actual result BEFORE applying this Pull Request
No change as the class is there anyway, now twice.

### Expected result AFTER applying this Pull Request
Position gets the darker background only if that class is added to the module, otherwise the regular white background is used.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a4980532d018d4cd191765322a3be8ed16c228a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30734">issues.joomla.org/tracker/joomla-cms/30734</a>.</sub>

**Comment by richard67** [comment]
Hint for other testers: With patchtester you can't apply both PRs #30729 and this one here. But you can apply #30729 and then do the changes from this PR here by editing the files.

**Comment by Bakual** [comment]
The other PR is now merged, so tomorrow in the nightly.

**Comment by richard67** [comment]
@Bakual Please update the branch of this PR to latest 4.0-dev by merging the 4.0-dev branch of the CMS repo into it.

Update: That's needed for being able to test this PR here with patchtester.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a4980532d018d4cd191765322a3be8ed16c228a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30734">issues.joomla.org/tracker/joomla-cms/30734</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30734">issues.joomla.org/tracker/joomla-cms/30734</a>.</sub>

**Comment by richard67** [comment]
@Bakual Should there be some documentation about the effect adding the class "card-grey" to the module class parameter? Or is that such a standard bootstrap thing that everybody should know who deals with bootstrap based templates?

**Comment by Bakual** [comment]
That's a good question and I don't know the answer. I just assumed it was a standard Bootstrap class, but when I check the Bootstrap documentation (https://getbootstrap.com/docs/4.0/components/card/) there are no specific colour styling classes for cards.
The BS class which could be used is "bg-light" (from https://getbootstrap.com/docs/4.0/utilities/colors/) which is a tiny bit lighter than "card-grey".

The class "card-grey" seems to be a Cassiopeia class defined in https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/bootstrap/_card.scss (together with "card-inverse" which seems to be unused).
Maybe that file could be removed - but that's a question for people who know how that stuff works. I just see that it was part of the initial template PR by @C-Lodder

**Comment by richard67** [comment]
Well, maybe just add something to the "Documentation Changes Required" section of this PR, telling that it needs to document somewhere the Cassiopeia module classes which can be used, and we set the documentation required label. That will not stop this PR from being merged, and we have a reminder somewhere.

**Comment by Bakual** [comment]
Personally I would just remove the cassiopeia specific styling for card-grey and people can use any of the default BS classes instead (or add own ones).

**Comment by C-Lodder** [comment]
I think it was a custom class: https://github.com/joomla/40-backend-template/blob/master/templates/cassiopeia/scss/vendor/bootstrap/_card.scss#L3-L5

May aswell remove it

**Comment by Bakual** [comment]
I'll leave this PR as is. I can try to remove the SCSS rules in another PR, as soon as I have figured out how to recreate all the compiled CSS files 😄

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/30754 for the removal of the scss file.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
