### PR TITLE
Allow form submission when Captcha plugin is not available

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Redo of #20288. This allows submitting forms when selected Captcha plugin is disabled, uninstalled or has a different access level.

### Testing Instructions

Select a Captcha plugin in global or component configuration.
Disable the plugin.
Attempt to submit a form that has a Captcha field.

### Expected result

Form submitted successfully.

### Actual result
Message on form page:
```
Error
Captcha plugin not set or not found. Please contact a site administrator.
```
Form submission fails because Captcha field is invalid.

### Documentation Changes Required
IDK.

### CODE REVIEW

**Comment by brianteeman** [comment]
My gut feeling is that this is not a good idea and the current behaviour is correct - others may disagree.

**Comment by tonypartridge** [comment]
I’m with Brian, if user is guest then forms shouldn’t be submitable. You could if people felt it necessary add in global config option to allow submitting forms even when no valid captcha found. But I don’t think it’s needed.

**Comment by ghost** [comment]
@HLeithner decision based on above comments?

**Comment by HLeithner** [comment]
This makes no sense for me, if I select a captcha it shouldn't be ignored because its disabled or I don't have access rights. Also I still like to remove access level from plugins as michael suggested in another issue.

**Comment by SharkyKZ** [comment]
@HLeithner until access levels are removed from plugins, this totally makes sense. E.g. if captcha plugin access is set to Guest, captcha should only be required for guests and it should not break the site for everyone else.

Uninstalling or disabling captcha plugin requires to resave every configuration containing captcha option. Otherwise users are left with a broken site. This is not communicated to the user. Editor, for example, does not error in such case. It just defaults to a textarea.

**Comment by Bakual** [comment]
We're talking about a security feature here, not an editor. So yes, if you make security related changes (eg disabling the plugin), you should check all related settings. Otherwise the system must be on the safe side - which is preventing the form from being sent.

**Comment by brianteeman** [comment]
> Uninstalling or disabling captcha plugin requires to resave every configuration containing captcha option. Otherwise users are left with a broken site. This is not communicated to the user. Editor, for example, does not error in such case. It just defaults to a textarea.

In this scenario can you not do a check to see if the plugin is enabled ?

**Comment by SharkyKZ** [comment]
As an administrator, you won't know that your site is broken until someone actually contacts you as advised in the message or until you try to submit a form containing captcha yourself.

In global/component configurations you won't see anything wrong because disabled/uninstalled plugins aren't shown. The field defaults to global or `None Selected` option but whatever was previously set is actually used.

**Comment by Bakual** [comment]
> until you try to submit a form containing captcha yourself.

I hope you try it after you make such changes.

**Pull request closed without merging**
