### PR TITLE
Redirects menu link

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

The component is referred to as Redirects on all screens but the menu said Redirect. This simple PR resolves that.

This issue was reported by the nl-NL Translation Team

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9395fb30cb1096ab0cbca88f07d24defa43cb83f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10060">issues.joomla.org/joomla-cms/10060</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 9395fb30cb1096ab0cbca88f07d24defa43cb83f<br /><br />:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10060">issues.joomla.org/joomla-cms/10060</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10060">issues.joomla.org/joomla-cms/10060</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 9395fb30cb1096ab0cbca88f07d24defa43cb83f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10060">issues.joomla.org/joomla-cms/10060</a>.</sub>

**Pull request merged**
