### PR TITLE
added the space between text and table border #14842

### PR DESCRIPTION
**Pull request by yasirunilan**
Pull Request for Issue #14839 .

### Summary of Changes
Added the space between table border and text displayed.Added padding

### Testing Instructions
Go to Menu, Extensions -> Manage -> Discover.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by yasirunilan** [comment]
Any feedback on this?

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on fb114c2e93900631ea1f366147d7bd5b1a2780e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14862">issues.joomla.org/tracker/joomla-cms/14862</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on fb114c2e93900631ea1f366147d7bd5b1a2780e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14862">issues.joomla.org/tracker/joomla-cms/14862</a>.</sub>

**Comment by C-Lodder** [comment]
@wilsonge - please merge

**Pull request merged**
