### PR TITLE
[4.1] s/../.

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4.1] s/../.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de8c25bba5d70ed67af3f8fba1d826c564846d00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36381">issues.joomla.org/tracker/joomla-cms/36381</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de8c25bba5d70ed67af3f8fba1d826c564846d00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36381">issues.joomla.org/tracker/joomla-cms/36381</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36381">issues.joomla.org/tracker/joomla-cms/36381</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
