### PR TITLE
[4.0 - com_fields] Migrate to Bootstrap 4

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

This PR migrated the views to Bootstrap 4 and uses the new `save group` toolbar dropdown.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
after applied Patch in Patch Tester: `The file marked for modification does not exist: administrator/components/com_fields/views/field/tmpl/modal.php`

**Comment by C-Lodder** [comment]
Are you sure you're trying to apply this patch on the 4.0-dev branch?

**Comment by franz-wohlkoenig** [comment]
applied on 3.7-staging cause don't know if PR is for 3.7 or 4.

**Comment by C-Lodder** [comment]
ahh sorry, forgot to mention that in the title. Updated it

**Comment by franz-wohlkoenig** [comment]
@C-Lodder thanks for updating.

**Comment by mahagr** [comment]
Great.. So instead of hard coded Bootstrap 2 support Joomla will in the future have hard coded Bootstrap 4 support with no way to override it...

I thought that Joomla is going to move everything to layout files in order to avoid the same situation it had with J! 1.5, 2.5 & 3.x: painful template upgrades and old looks because of it is locked to a single version of a single CSS framework.

PS. I'm not a fan of having HTML inside any PHP code.

**Comment by mbabker** [comment]
Umm, everything is in layouts except for the form XML definitions?  Or am I missing something here?

**Comment by mahagr** [comment]
@mbabker 

Oh, nevermind then, I guess I'm just too used to see twig files instead of PHP files as templates.

**Comment by mbabker** [comment]
Plain PHP's still a valid templating engine (just ask the [Plates](https://github.com/thephpleague/plates) devs), but yeah, Twig is much nicer 😉

**Pull request merged**
