### PR TITLE
[4.0] Mobile: Fix fieldset associations display

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
Adding specific css for mobile view

### Testing Instructions
Install a multilingual site.
Edit an associated item. Display the Associations tab.
Reduce window size to mobile view

patch and run npm

### Before patch
The title of the associated item is cut

fieldset-assoc_before

### After patch
fieldset-assoc

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3da2effc4efc7d04b135c2b8c149f0604ab1135f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27128">issues.joomla.org/tracker/joomla-cms/27128</a>.</sub>

**Comment by ciar4n** [comment]
Presuming a field with 3 appended buttons can potentially be found anywhere, should this fix be applied globally instead of just within associations?

**Comment by infograf768** [comment]
> Presuming a field with 3 appended buttons can potentially be found anywhere, should this fix be applied globally instead of just within associations?

Good question. I have not found any other occurence in core.
PR can be modified easily if desired.

**Comment by ciar4n** [comment]
Considering the XML allows multiple buttons, I think the field CSS should support them globally regardless if used elsewhere. within core

Rather than using a media query, as this is a flex object simply apply a min-width to the input. The buttons should wrap once the input field hits that width.

**Comment by infograf768** [comment]
> Rather than using a media query, as this is a flex object simply apply a min-width to the input. The buttons should wrap once the input field hits that width.

Please suggest patch. Flex is somehow a foreign concept to me. ;)

**Comment by ciar4n** [comment]
Adding something like this instead should work...

(edit to taste)

```CSS
.input-group input {
    min-width: 200px;
}
```

**Comment by ciar4n** [comment]
... buttons will wrap once the input is less than 200px

**Comment by infograf768** [comment]
@ciar4n 
Done. Used 220px to normalize.
@richard67 Please test again

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 06471a98a9b91f3fe19cde340f939ac87a5b6f06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27128">issues.joomla.org/tracker/joomla-cms/27128</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 06471a98a9b91f3fe19cde340f939ac87a5b6f06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27128">issues.joomla.org/tracker/joomla-cms/27128</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27128">issues.joomla.org/tracker/joomla-cms/27128</a>.</sub>

**Comment by wilsonge** [comment]
I think in menus we might have a use of this where you can create articles in the modal. select/create/clear or something

**Comment by wilsonge** [comment]
Thanks @ciar4n and @infograf768 !

**Comment by infograf768** [comment]
Mostly @ciar4n !

**Pull request merged**
