### PR TITLE
[4.0] remove unused cassiopeia css

### PR DESCRIPTION
**Pull request by brianteeman**
This css is not used now we are on bs5. Code review.

pr for #34828

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on a650b70c6ad5735e9f58c1250355eb34e337ebdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34832">issues.joomla.org/tracker/joomla-cms/34832</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a650b70c6ad5735e9f58c1250355eb34e337ebdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34832">issues.joomla.org/tracker/joomla-cms/34832</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34832">issues.joomla.org/tracker/joomla-cms/34832</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
