### PR TITLE
[4.0] Media edit fields alignment

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #28209 .

### Summary of Changes
Fixes alignment issues for fields in Media Manager -> Edit an Image -> Resize tab

### Testing Instructions
Apply PR and run `npm i` for updating the changed SCSS. Check login page displays correctly. Open Joomla admin in Firefox. Navigate to Media Manager -> Edit an Image -> Resize tab. Ensure fields are aligned correctly (check orignal issue).

### CODE REVIEW

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on a19c000570b2d2a120c88c5ffcae46d7a393fa59<br /><br />Works for me in Safari now and continues to work in Chrome on OSX<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28373">issues.joomla.org/tracker/joomla-cms/28373</a>.</sub>

**Comment by wilsonge** [comment]
@C-Lodder are you able to test this now works for you in windows?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a19c000570b2d2a120c88c5ffcae46d7a393fa59<br /><br />Tested with Firefox on Windows 10.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28373">issues.joomla.org/tracker/joomla-cms/28373</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28373">issues.joomla.org/tracker/joomla-cms/28373</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
