### PR TITLE
[5.0] Correct language string workflows

### PR DESCRIPTION
**Pull request by brianteeman**
The language key used in the code was incorrect. This simple PR updates the code to use the correct string

as its an error message code review should be ok for testing

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on def15dd7bcfb60eb58a32c03959bcb6848bea635<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42389">issues.joomla.org/tracker/joomla-cms/42389</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on def15dd7bcfb60eb58a32c03959bcb6848bea635<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42389">issues.joomla.org/tracker/joomla-cms/42389</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42389">issues.joomla.org/tracker/joomla-cms/42389</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by toowoombarc** [comment]
This may have also shipped with 4.4.1, or related unidentified library change? Occuring to latest 4.4.6 as at date of this message.

Effect. Multiple split-line language text file(s) get skipped with following paradigm.
SOME_LANG_CONSTANT="text starting here
and new line here"

Should be:
SOME_LANG_CONSTANT="text starting here and new line here"

**Pull request merged**
