### PR TITLE
Calendar css is broken #14195

### PR DESCRIPTION
**Pull request by 810**
# Test instructions

Use a 3rt party component that is using jhtml.calendar like kunena. (backend - kunena - statistics - click calendar)

You should see now the numbers and text on the popup.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on e409882e7a279b6aba7989f999bcada59ef02dce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14219">issues.joomla.org/tracker/joomla-cms/14219</a>.</sub>

**Comment by dgt41** [comment]
@ciar4n @C-Lodder can you review this?

**Review by C-Lodder — APPROVED** [review]

**Review by ciar4n — APPROVED** [review]

**Comment by brianteeman** [comment]
@810 Can you take a look at the merge conflicts

**Comment by 810** [comment]
updated conflicts

**Comment by brianteeman** [comment]
@810 thanks

**Comment by franz-wohlkoenig** [comment]
Test again?

**Comment by jeckodevelopment** [comment]
Yes please

**Comment by franz-wohlkoenig** [comment]
@jeckodevelopment after Install: "Error The patch could not be applied because it conflicts with a previously applied patch: media/system/css/fields/calendar-rtl.css"

**Comment by brianteeman** [comment]
@franz-wohlkoenig make sure you dont have any other patches applied before testing any PR

**Comment by franz-wohlkoenig** [comment]
@brianteeman no other PR applied.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4142a452a764b60fe43e4990458f905b5d30764f<br /><br />2nd time PR installed no Error shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14219">issues.joomla.org/tracker/joomla-cms/14219</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 4142a452a764b60fe43e4990458f905b5d30764f<br /><br />Previous to patch 
screen shot 2017-03-21 at 20 03 52
Post patch 
screen shot 2017-03-21 at 20 03 49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14219">issues.joomla.org/tracker/joomla-cms/14219</a>.</sub>

**Comment by zero-24** [comment]
@N6REJ

Your screenshots looks broken to me?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14219">issues.joomla.org/tracker/joomla-cms/14219</a>.</sub>

**Comment by N6REJ** [comment]
@zero-24 apparently its been removed from issue tracker.... sorry about that.. anyway, it worked fine.

**Pull request merged**
