### PR TITLE
Revert #31537 and fix warnings on php 8 in fof

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #31537.

### Summary of Changes

This revert changes in #31537, and make a better fix for that issue.

### Testing Instructions
Please follow #31537 for test

### Actual result BEFORE applying this Pull Request
much warning

### Expected result AFTER applying this Pull Request
no warning

### Documentation Changes Required
none

### CODE REVIEW

**Comment by jameswadsworth** [comment]
I have tested this item :white_check_mark: successfully on 4ecc31e2fda46cbd95d0e0112fcb9eb9f0278e2a<br /><br />Works for warnings in php 7.4. They are no longer visible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31600">issues.joomla.org/tracker/joomla-cms/31600</a>.</sub>

**Comment by N6REJ** [comment]
> I have tested this item ✅ successfully on [4ecc31e](https://github.com/joomla/joomla-cms/commit/4ecc31e2fda46cbd95d0e0112fcb9eb9f0278e2a)
> 
> Works for warnings in php 7.4. They are no longer visible
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/31600](https://issues.joomla.org/tracker/joomla-cms/31600).

can you retest with php8 please.. This is specifically a php8 issue.

**Comment by N6REJ** [comment]
@Fedik I just did a clean pull & install for both staging and 4.0-dev and didn't see any warnings, without any pr's.
[systeminfo-2020-12-06T12_36_19-06_00.txt](https://github.com/joomla/joomla-cms/files/5649362/systeminfo-2020-12-06T12_36_19-06_00.txt)

**Comment by Fedik** [comment]
> and didn't see any warnings

you will not see them on staging, because #31537 (that is reverted here, see the description)
but they are there :smile:  

they are on joomla 3.x

**Comment by jameswadsworth** [comment]
@N6REJ - you see the same errors as php 8 in php 7.4.12. See the [original issue](https://github.com/joomla/joomla-cms/issues/31483).

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 4ecc31e2fda46cbd95d0e0112fcb9eb9f0278e2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31600">issues.joomla.org/tracker/joomla-cms/31600</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31600">issues.joomla.org/tracker/joomla-cms/31600</a>.</sub>

**Comment by HLeithner** [comment]
Thanks @Fedik

**Pull request merged**
