### PR TITLE
[4.0] [Cassiopeia] Remove header SVG curve

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #27565 .

### Summary of Changes
Removes the SVG curve from the frontend template header

### Testing Instructions
Apply patch and run `node build.js --compile-css` to update the changed SCSS.

Add banner module to banner position

### Before PR
Banner cropped by SVG

### After PR
Banner is visible

### Documentation Changes Required
No

### CODE REVIEW

**Comment by infograf768** [comment]
Great.
Remains one aspect: the Module Class. What do we do with that?
Screen Shot 2020-01-19 at 12 34 18

**Comment by ciar4n** [comment]
Not sure I understand what you mean. Is it missing from the output?

**Comment by infograf768** [comment]
> Is it missing from the output?

As far as I see , yes.

**Comment by infograf768** [comment]
I think it comes from
`<jdoc:include type="modules" name="banner" style="xhtml" />`

Cardgrey and default chromes contain `<?php echo htmlspecialchars($params->get('moduleclass_sfx')`

not xhtml

**Comment by ciar4n** [comment]
I've changed the style to `html5` which appears to be the only chrome with no styling and adds the class. It appears `default` applies card styling to the module which is incorrect imo and possibly needs changing (separate issue/pr).

**Comment by infograf768** [comment]
On ipad, will test later.
In j3, chromes are defined in system.
Except for the specific chromes which are defined in the template itself, do you have an idea where are defined html5 and xhtml in j4 ?

**Comment by ciar4n** [comment]
System chromes are in ../layouts/chromes/

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bdcce04324ca020b404da480f0b32dc935dbb1b7<br /><br />Looks fine here.

we get `<div class="moduletable mybannerclass">` which is fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27566">issues.joomla.org/tracker/joomla-cms/27566</a>.</sub>

**Comment by infograf768** [comment]
@ciar4n 
Looks like we have also another `xhtml ` style in error.php
```
<?php if ($this->countModules('banner')) : ?>
		<div class="grid-child container-banner">
			<jdoc:include type="modules" name="banner" style="xhtml" />
		</div>
```

**Comment by ChristineWk** [comment]
banner
I have tested this item :white_check_mark: successfully on aee0cc4d4c3de669ba2d253ef596a287d748a224<br /><br />Tested hours before, but after applying Patch, I got error 404 and: Call to undefined method Joomla\CMS\WebAsset\WebAssetManager::usePreset()
Then I found: https://github.com/brianteeman/joomla-cms/commit/7fa8d420304fc82a1a525488698a71dadc506c6f
My site was from oct2019, therefore checked above files. Finally installed now completely new nightly build from today. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27566">issues.joomla.org/tracker/joomla-cms/27566</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on aee0cc4d4c3de669ba2d253ef596a287d748a224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27566">issues.joomla.org/tracker/joomla-cms/27566</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27566">issues.joomla.org/tracker/joomla-cms/27566</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by Scrabble96** [comment]
Sorry, I know the original issue was posted by me, but I'm unable to test this; I'm waiting for a new computer :-( which should arrive sometime next week.

**Pull request merged**
