### PR TITLE
[4.0] Namespace com_templates default

### PR DESCRIPTION
**Pull request by brianteeman**
Fix the last namespace update in administrator\components\com_templates\tmpl\templates\default.php

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 44aff84f4c56b5cc4aada1ad3537a13839e29510<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24118">issues.joomla.org/tracker/joomla-cms/24118</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44aff84f4c56b5cc4aada1ad3537a13839e29510<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24118">issues.joomla.org/tracker/joomla-cms/24118</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24118">issues.joomla.org/tracker/joomla-cms/24118</a>.</sub>

**Comment by brianteeman** [comment]
restarted appveyor

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
