### PR TITLE
Update string in fields

### PR DESCRIPTION
**Pull request by brianteeman**
It was a bit ambiguous ( use _what_ from plugin) so I updated the string to be more explicit

### Before
screenshotr19-56-01

### After
screenshotr19-54-43

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 13e04dbff5d204b7aa89c6df863c3efdf99f5b96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17119">issues.joomla.org/tracker/joomla-cms/17119</a>.</sub>

**Comment by Quy** [comment]
We have `Use Global`. How about `Use Plugin Global`?

**Comment by brianteeman** [comment]
@quy because that doesnt make sense (to me)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 13e04dbff5d204b7aa89c6df863c3efdf99f5b96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17119">issues.joomla.org/tracker/joomla-cms/17119</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
@brianteeman: please reassign Milestone 3.8.0

**Comment by zero-24** [comment]
Done

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
