### PR TITLE
Declare class variables in JDocumentError

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

`JDocumentError` assigns data to several undeclared class member variables.  This documents them.
#### Testing Instructions

Review

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 7757d9356abf695e023e882253b589914670560f<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10848">issues.joomla.org/joomla-cms/10848</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 7757d9356abf695e023e882253b589914670560f<br /><br />Looks good from code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10848">issues.joomla.org/joomla-cms/10848</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please so your Job here. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10848">issues.joomla.org/joomla-cms/10848</a>.</sub>

**Comment by mbabker** [comment]
If it's decided https://github.com/joomla/joomla-cms/issues/11239 is truly a B/C break this cannot be accepted until 4.0 for the same reasons.

**Pull request merged**
