### PR TITLE
Define Legal Image Extensions (File Types) dynamically according to t…

### PR DESCRIPTION
**Pull request by wenmengyu**
…he media component

Pull Request for Issue # .

### Testing Instructions
In the media component of the configuration Media: Options in the field of Legal Image Extensions (File Types) to increase the need to extend the image extension (svg) using field type media can choose (svg) Legal Image Extensions picture file

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
can you please write Test instructions?

**Comment by wenmengyu** [comment]
Testing Instructions

In the media component of the configuration Media: Options in the field of Legal Image Extensions (File Types) to increase the need to extend the image extension (svg) using field type media can choose (svg) Legal Image Extensions picture file

**Comment by infograf768** [comment]
Not sure I understand as we can't upload .svg files in the Media Manager as we get an error of possible IE XSS attack

**Comment by infograf768** [comment]
See https://issues.joomla.org/tracker/joomla-cms/4674

**Comment by brianteeman** [comment]
As long as svg is only something that a site owner can enable and is not enabled by default I don't see any issue

**Comment by infograf768** [comment]
Not sure you understand: as far as I tested,  this patch does not let upload a .svg file in Joomla, even after adding correctly the legal extensions, legal image extensions and mime-type.

**Comment by brianteeman** [comment]
So what does it do then?


(sent from the plane ✈)

**Comment by infograf768** [comment]
Looks like it lets display and choose an .svg file in the list when Inserting an image using the Image button . The .svg file would have been manually uploaded before in the images folder.

**Comment by infograf768** [comment]
About svg vulnerabilities, read
https://www.owasp.org/images/0/03/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf

**Comment by brianteeman** [comment]
If that's what it does then it's not a problem

**Comment by Quy** [comment]
Please test PR #29728

**Pull request closed without merging**
