### PR TITLE
[installation] Add javascript message titles and ajax errors strings

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Add javascript message titles and ajax errors strings to installation tempalte.

You will notice that now all installation warning, error, notices and message have title like in the rest of joomla.
image
### Testing Instructions

Code review.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@Bakual please check this one because at installation we didn't yet have the languages so (i think) and joomla messages will be in english.
Is it better to add them to the instllation en-GB file?

**Comment by brianteeman** [comment]
You can have installation in all languages

**Comment by brianteeman** [comment]
For example you can do this
Before running the installation, open installation/localize.xml and set the following on line 3:

<forceLang>ar-AA</forceLang>

**Comment by andrepereiradasilva** [comment]
yes brian but i'm loading language files that are not part of the installationlanguage files, so the language is not yet installed in joomla.

**Comment by yvesh** [comment]
@andrepereiradasilva Do you think it would be a better solution adding these language strings to the installation language files?

**Comment by andrepereiradasilva** [comment]
the way the installation is designed ... yes i think we need all those language files in the installation languages files. Because the language itself would only be installed later.

I will make that change

**Comment by andrepereiradasilva** [comment]
ok done

**Comment by brianteeman** [comment]
@andrepereiradasilva can you update the description to remove the bit about loading the core lang files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3761d4e5352a11a9cff9030637b3b5c59395e3da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman done

**Comment by brianteeman** [comment]
@andrepereiradasilva thanks

**Comment by bhavikTailored** [comment]
- I have tested successfully and attached screen shot.
- screen shot 2016-08-26 at 05 13 25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 3761d4e5352a11a9cff9030637b3b5c59395e3da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by zero-24** [comment]
RETC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on 3761d4e5352a11a9cff9030637b3b5c59395e3da<br /><br />I have Tested successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Comment by brianteeman** [comment]
@tomartailored This has already been merged - so either you are not testing with the current staging which you must always do or you didnt really test it but I am sure that you did didnt you

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11800">issues.joomla.org/joomla-cms/11800</a>.</sub>

**Pull request merged**
