### PR TITLE
Make sure mariadb versions are correctly identified in the updater

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #26078 

### Summary of Changes

Make sure mariadb versions are correctly identified by the updater

### Testing Instructions

- install 3.10.0-dev on a system with mariadb installed
- use this update server: https://www.jah-tz.de/downloads/core/nightlies/next_major_list.xml

### Expected result

pre update checker and install of the update is proposed

### Actual result

image

### Documentation Changes Required

In order to make this work this here implements a new version detection for mariadb and also requires mariadb to be specified in the XML. This new behavior needs to be documented.

```xml
<supported_databases mysql="5.6" mariadb="10.4" postgresql="11.0"/>
```

- [ ] Update docs https://docs.joomla.org/Deploying_an_Update_Server
- [ ] Create an PR against the updater repo to ship the mariadb tag in the xmls

### CODE REVIEW

**Comment by richard67** [comment]
@zero-24 

> <supported_databases mysql="5.6" mariadb="10.4" postgresql="11.0"/>
>

Shall it define the supported versions, like the name of the item suggests, e.g. with a regex mariadb="10.[456]", or shall it be the **minimum** supported version for each DB? If the latter, then the name "supported_databases" might be a bit misleading.

P.S.: Is just a question for my understanding, not that I require any change. I can't test it anyway because I don't have MariaDB and for installing one it needs to kill my MySQL Db first, which I would like to avoid.

**Comment by richard67** [comment]
@zero-24 Forget my question in my previous comment. I've found it in the docs.

**Comment by richard67** [comment]
@zero-24 My comment here [https://github.com/joomla/joomla-cms/pull/26104#issuecomment-528030647](https://github.com/joomla/joomla-cms/pull/26104#issuecomment-528030647) applies also to this PR here. Shall I provide fixes for both PRs with making PRs to your repo?

**Comment by zero-24** [comment]
Merged thanks @richard67 👍

**Comment by richard67** [comment]
Unfortunately I don't use MariaDB, sounds too catholic to me, am protestant ;-) So I can't help with a test.

**Comment by fancyFranci** [comment]
I tested this with 10.3.16-MariaDB and the updater works again, after adding the patch.
But my MariaDB version is not one of the supported databases. Is this intended?

Btw System Information displays before and after the patch:
Database Type: mysql
Database Version: 5.5.5-10.3.16-MariaDB<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26079">issues.joomla.org/tracker/joomla-cms/26079</a>.</sub>

**Comment by zero-24** [comment]
> I tested this with 10.3.16-MariaDB and the updater works again, after adding the patch.
But my MariaDB version is not one of the supported databases. Is this intended?

It is more an minimum_databases tag ;) As the updates points to 10.1 you are good to go with 10.3.16

> Btw System Information displays before and after the patch:

Yes this is intended as 5.5.5.XX.XX.XX is the actual version that the database returns.

**Comment by ghost** [comment]
@fancyFranci please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 193cc4fc29c02be510b4a3bd1a6655dd87824f0c<br /><br />Catholic enough<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26079">issues.joomla.org/tracker/joomla-cms/26079</a>.</sub>

**Comment by fancyFranci** [comment]
> 
> > I tested this with 10.3.16-MariaDB and the updater works again, after adding the patch.
> > But my MariaDB version is not one of the supported databases. Is this intended?
> 
> It is more an minimum_databases tag ;) As the updates points to 10.1 you are good to go with 10.3.16

This is the point that confuses me, as 10.3. is lower than the minimum 10.4., isn't it? :)

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 193cc4fc29c02be510b4a3bd1a6655dd87824f0c<br /><br />Before applying the patch Joomla said that the update was not available, after applying the patch the update of Joomla 4 shows up.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26079">issues.joomla.org/tracker/joomla-cms/26079</a>.</sub>

**Comment by zero-24** [comment]
> This is the point that confuses me, as 10.3. is lower than the minimum 10.4., isn't it? :)

The minimum configured on the update server right now is:
```
<supported_databases mysql="5.6" mariadb="10.0" postgresql="11.0"/>
```

So anything above that should pass using the testing update server provided above. This is not an official statement on what would be the actual minimum for sure. ;)

**Comment by zero-24** [comment]
Ah ok i now got where the confusion is comming from @fancyFranci it is my fault :D 

The update server itself points to mariadb 10.0 in my description here i used 10.4 bis this is not the version set in the xml and should have only represent an example how the xml could look like.

So in conclusion everything works as expected :)

**Comment by roland-d** [comment]
The PHP version seems incorrect:
image

This should say `PHP Version >= 7.2.0`

**Comment by zero-24** [comment]
Yes and no :D You are correct this should be the case for 4.0 stable but as of now the update server in this example still points to

```
<php_minimum>7.0.0</php_minimum>
```

https://www.jah-tz.de/downloads/core/nightlies/next_major_extension.xml

I'm not at my desk so i can not update it yet but it is totally working than expected for now :)

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thanks for making J3 a bit more mariaDB aware.

**Comment by zero-24** [comment]
>  Create an PR against the updater repo to ship the mariadb tag in the xmls

Based on: https://github.com/joomla/update.joomla.org/pull/145#issuecomment-531209634 mariadb minimum is going to be 10,1 for now. Here is the update server PR to do the required change: https://github.com/joomla/update.joomla.org/pull/146 cc @HLeithner @wilsonge 

> Update docs https://docs.joomla.org/Deploying_an_Update_Server

Added a note about the case implemented here.

**Pull request merged**
