### PR TITLE
Use new JLanguageHelper::getInstalledLanguages across core

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

- Replace all `JLanguageMultilang::getSiteLangs()` for  `JLanguageHelper::getInstalledLanguages(0)` and deprecate the old method.
- Use this new method to replace some hardcoded language db queries, removing duplicated code

### Testing Instructions

1. Code review
2. Use latest staging and apply patch
3. All installed language (selected list in install, backend login and user lang config), language redirect (language switcher module and language filter plugin), etc works as before.
4. Test also disabling installed site/admin languages in Extensions -> Manage -> Manage (Languages) and check all works properly

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@infograf768 please check

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0726f7d7260d88e994db68fc5a6152ccfdeab0e7<br /><br />i've played a bit with (3,4) no issues discovered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12671">issues.joomla.org/tracker/joomla-cms/12671</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bf96a0764bb2481644bf723a40aae9cac70a13a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12671">issues.joomla.org/tracker/joomla-cms/12671</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@alikon can you mark as tested againb or retest if needed.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bf96a0764bb2481644bf723a40aae9cac70a13a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12671">issues.joomla.org/tracker/joomla-cms/12671</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12671">issues.joomla.org/tracker/joomla-cms/12671</a>.</sub>

**Pull request merged**
