### PR TITLE
Fix using en-GB as default language on odd cases

### LINKED ISSUE #8906: Wrong default language in backend
#### Steps to reproduce the issue

User should have default settings for languages. Edit profile > Basic settings > Backend Language > - Use default -

1. Install new language (Extensions > Language(s) > Install language).
2. Set newly installed language as default to administrator.
3. Log out.
4. Log in again.

#### Expected result

- Administrator side should be in newly installed default language.

#### Actual result

- Administrator side is in english.

#### System information

- Joomla! 3.4.8

#### Additional comments

- Login view is in newly installed default language (not neglish).
- Debugging language shows no errors.
- I could investigate this if someone verifies it.

### PR DESCRIPTION
**Pull request by renekorss**
fixes #8906 

Fixes showing administrator side always in `en-GB` if `$_POST` has no `lang` key.

### CODE REVIEW

**Comment by wojsmol** [comment]
@renekorss see https://github.com/renekorss/joomla-cms/issues/5

**Comment by infograf768** [comment]
This works but I rather suggest this code:
```
		if (!($result instanceof Exception))
		{
			$lang = $this->input->getCmd('lang', null);

			if (!is_null($lang))
			{
				$lang = preg_replace('/[^A-Z-]/i', '', $lang);
				$this->setUserState('application.lang', $lang);
			}

			static::purgeMessages();
		}
```

**Comment by renekorss** [comment]
@infograf768 Thanks. Tested, works with latest suhosin.

**Comment by infograf768** [comment]
@Bakual
Can you check if this is OK?

**Comment by Bakual** [comment]
Not sure why you want a default value of `null` instead of just not giving any default value. Imho
````
$lang = $this->input->getCmd('lang');

if (!$lang)
{
	$lang = preg_replace('/[^A-Z-]/i', '', $lang);
	$this->setUserState('application.lang', $lang);
}
````
should do the same.

One could also put the preg_replace before the if, so in case the result of the sanitising(?) ends up being empty no UserState is going to be set.
So I would do
````
$lang = $this->input->getCmd('lang');
$lang = preg_replace('/[^A-Z-]/i', '', $lang);

if (!$lang)
{
	$this->setUserState('application.lang', $lang);
}
````
But I may miss something as I don't know the code in question in detail.

**Comment by infograf768** [comment]
@Bakual
I was mocking up the code in
https://github.com/joomla/joomla-cms/blob/staging/installation/application/web.php#L383-L392

But I see no reason indeed in this case (as we have a default) to not use your proposal.

**Comment by renekorss** [comment]
@Bakual @infograf768  I updated code.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7ebda6c86cf78e8772d11405c6ff1abc7640d058<br /><br />One more tester to get this in 3.5.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Comment by renekorss** [comment]
I have tested this item :white_check_mark: successfully on 7ebda6c86cf78e8772d11405c6ff1abc7640d058<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Comment by brianteeman** [comment]
I have not tested this item.<br /><br />I have not tested this as I can not replicate the issue in order to be able to confirm this PR resolves anything<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Comment by renekorss** [comment]
@brianteeman Easiest way to test this, is to delete language select input with developer tools, so that `$_POST` has no `lang` key. Without this patch, it will default to `en-GB` despite different default language.

**Comment by infograf768** [comment]
@brianteeman 
No need to have the issue to test.
As long as this works for who has the issue AND works in all cases for the others (i.e. all of us).

Tests should include for the user login:
User set to use default admin language
User set to a specific admin language
Login with a different language than those above.

**Comment by brianteeman** [comment]
> As long as this works for who has the issue AND works in all cases for the others (i.e. all of us).

Thats fine but I am not going to personally test something that I cannot replicate

**Comment by brianteeman** [comment]
@renekorss I have removed your test report from the count of successful tests. It is assumed that code you submit works ;) 

This still needs one more tester<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Comment by renekorss** [comment]
@brianteeman Sounds logical :)

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 7ebda6c86cf78e8772d11405c6ff1abc7640d058<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Comment by infograf768** [comment]
2 tests OK. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8956">issues.joomla.org/joomla-cms/8956</a>.</sub>

**Pull request merged**
