### PR TITLE
[4.0] Missing fontawesome icon

### PR DESCRIPTION
**Pull request by brianteeman**
Another icon has been renamed in fontawesome5 - we use it in the repeatable fields

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d01331bd8950ad84bd59236a31d1841d3a8d72b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24677">issues.joomla.org/tracker/joomla-cms/24677</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d01331bd8950ad84bd59236a31d1841d3a8d72b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24677">issues.joomla.org/tracker/joomla-cms/24677</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24677">issues.joomla.org/tracker/joomla-cms/24677</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
