### PR TITLE
Fix PHP errors in com_contact

### PR DESCRIPTION
**Pull request by wilsonge**
Fixes the issues described by @infograf768  in https://github.com/joomla/joomla-cms/issues/5936

### CODE REVIEW

**Comment by infograf768** [comment]
Works fine here. :)

**Comment by waader** [comment]
@test works!

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5937">issues.joomla.org/joomla-cms/5937</a>.</sub>

**Comment by infograf768** [comment]
One thought:
Would it not have been better to keep catid in default_articles.php (to be consequent with the rest of core, and to add a `->select('a.catid')' in the model?

**Comment by wilsonge** [comment]
if it works definitely! i just used the fix for that part you mentioned in the initial issue

**Comment by infograf768** [comment]
I have tested it here and it works fine.

**Comment by wilsonge** [comment]
Are you ok to make a PR then?

**Comment by infograf768** [comment]
Did not see that reply... Can you do, @wilsonge  ?

**Comment by wilsonge** [comment]
See https://github.com/joomla/joomla-cms/pull/6102

**Pull request merged**
