### PR TITLE
Added JLIB_INSTALLER_DISCOVER_INSTALL

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue #26299 . Note that me experience is with Joomla 4 and not Staging.

**Summary of Changes**

Added strings JLIB_INSTALLER_DISCOVER_INSTALL="Discover Install"
In admin and site lib_joomla.ini

I noticed that there places where strtoupper is missing: e.g - Text::('JLIB_INSTALLER' . $this->route), - leaving that as a separate issue but could fix if anyone would like to confirm - look in libraries/src/Installer/InstallerAdapter.php

**Testing Instructions**

See #26299
I do not know how to test this PR! I checked the code and I am fairly sure there is only one string missing from the set discover_install, install, update and uninstall.

**Actual result BEFORE applying this Pull Request**

Check the code: the strings are missing.

**Expected result AFTER applying this Pull Request**

Check the code: the strings are present.

**Documentation Changes Required**

None

### CODE REVIEW

**Comment by ceford** [comment]
I closed #31315 which was against 4.0-dev. Was that expected?

**Comment by SharkyKZ** [comment]
@ceford You can close that. Changes from staging should reach 4.0 eventually.

**Comment by SharkyKZ** [comment]
To test, download this package:  [plg_system_dummy.zip](https://github.com/joomla/joomla-cms/files/5495631/plg_system_dummy.zip).
Drop its contents into `plugins/system/dummy` directory (have to create it first).
Go to Extensions -> Manage -> Discover.
Click Discover button if needed.
Check `plg_system_dummy` plugin and click Install.

Before patch you should get this message:

>Warning
>Extension JLIB_INSTALLER_discover_install: Custom install routine failure.

After patch:

>Warning
>Extension Discover Install: Custom install routine failure.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 22216c44bd4ff22429b2cb77a55cc93dfb4611a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31315">issues.joomla.org/tracker/joomla-cms/31315</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22216c44bd4ff22429b2cb77a55cc93dfb4611a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31315">issues.joomla.org/tracker/joomla-cms/31315</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31315">issues.joomla.org/tracker/joomla-cms/31315</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
