### PR TITLE
[5.2] Adding missing properties to backend component view classes

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
These are missing properties used by our layouts in the backend component view classes.

### Testing Instructions
Codereview.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by HLeithner — COMMENTED** [review]
Is FormView not an option?

**Comment by Hackwar** [comment]
I didn't want to change the base class.

**Comment by rdeutz** [comment]
I would merge it to have to properties defined, maybe adding a note to change the base class with 6

**Comment by Hackwar** [comment]
In the meantime I tried using the FormView class instead and it would require major refactoring, which is out of the scope of this PR. Simply switching the base class and removing the properties does not work. Since this PR changes 19 files, this would mean hundreds of complex changes to those 19 files and is not testable anymore. We should be looking at refactoring this accordingly in other PRs, but for this PR it would be out of scope.

**Pull request merged**
