### PR TITLE
[4.3] Use the current user in MFA

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Uses the current user in the MFA models instead of from the factory.

ping @nikosdion for review

### Testing Instructions
- Create a Joomla user and log into the site with it
- Edit your profile
- There's a Multi-factor Authentication tab
- You will need to enable an authenticator
- The verification code is basically Google Authenticator
- Click it and it gives you on screen instructions and a QR code to scan
- Enter a 6 digit code generated by it into the box and click the button
- Now log out of the site and log back in
- It asks you for the 6 digit code

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### CODE REVIEW

**Review by nikosdion — APPROVED** [review]
The code looks alright to me. As long as the user tests pass I'm cool with these changes.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 004882a3324b9cec907d4b9b095d6e1ed7b98f33<br /><br />📱👍 All works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38610">issues.joomla.org/tracker/joomla-cms/38610</a>.</sub>

**Comment by nikosdion** [comment]
Stupid question. Have we ever checked if the MFA system plugin continues to work correctly _in the CLI application_ after this change? The ConsoleApplication returns null for getIdentity (instead of a guest user). The current implementation seems to be going through `Factory::getUser()` in this case which will return a guest user object but I'd like someone to test it for real.

**Comment by laoneo** [comment]
Good question

**Comment by laoneo** [comment]
As far as I can see, the events are only registered when on site or admin app https://github.com/joomla/joomla-cms/blob/4.2-dev/plugins/system/webauthn/src/Extension/Webauthn.php#L166.

**Comment by nikosdion** [comment]
The WebAuthn plugin is for authentication, not MFA. I know it doesn't kick in when we have a CLI application.

I said “system plugin”, huh? Sorry, I had my old LoginGuard code in mind. When I converted it to a core feature half of it went into a Trait (\Joomla\CMS\Application\MultiFactorAuthenticationHandler) which is only implemented in SiteApplication and AdministratorApplication and half of it into the plg_user_joomla plugin.

I was mostly worried about what plg_user_joomla does under the CLI application but I do see that I explicitly checked for the administrator and site application.

The other thing we need to check, though, is whether we break anything in the API application for com_users. We do return which users have MFA enabled but as far as I remember we don't actually call any code you touched, we just check the DB data.

**Comment by laoneo** [comment]
@nikosdion could you check if com_users breaks in API? You have here the best knowledge and can test it correctly.

**Comment by nikosdion** [comment]
Sorry for the delay, lots of things going on at the same time.

I tested com_users' API with your patch applied, I could not see any problems. In fact, we do not return anything MFA-related in the API.

**Comment by laoneo** [comment]
@nikosdion would be good if you can mark it then as a success test in the issue tracker.

**Comment by nikosdion** [comment]
I have tested this item :white_check_mark: successfully on f5d6963b69b958c189ba3ec586f4458efceb12ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38610">issues.joomla.org/tracker/joomla-cms/38610</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38610">issues.joomla.org/tracker/joomla-cms/38610</a>.</sub>

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on f5d6963b69b958c189ba3ec586f4458efceb12ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38610">issues.joomla.org/tracker/joomla-cms/38610</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo for the PR!

**Pull request merged**
