### PR TITLE
[#33761] Fix attribs from being truncated when many are stored

### PR DESCRIPTION
**Pull request by spignataro**
## How to reproduce the problem and/or test the patch::

Joomla attributes has a varchar 5120 set to it. If you create a custom field that stores to this table it won't save the full amount. Need to change from varchar to text.
## Summary

Attribs doesn't support large amounts of data for #__content
Details
Joomla attributes has a varchar 5120 set to it. If you create a custom field that stores to this table it won't save the full amount. Need to change from varchar to text.
In install file change

`attribs` varchar(5120) NOT NULL,
to

`attribs` text NOT NULL,

### CODE REVIEW

**Comment by waader** [comment]
mssql would look like this:

[attribs] [nvarchar](max) NOT NULL,

Additionally update sql-files are needed for all three databases in administrator/components/com_admin/sql/updates/

mysql:
ALTER TABLE `#__content` CHANGE `attribs` `attribs` TEXT NOT NULL;

postgresql:
ALTER TABLE "#__content" ALTER COLUMN "attribs" TYPE text;

mssql:
ALTER TABLE [#__content] ALTER COLUMN [attribs] [nvarchar](max) NOT NULL;

**Comment by spignataro** [comment]
Can this be merged in? it has been some time. Both mysql and postgresql are part of this PR. I can't test MS SQL.

This is getting annoying not having this in and I have to continue modifying the database structure. 

I will create a new PR for the updates (only for mysql and postgresql - again I can't test mssql)

**Comment by spignataro** [comment]
After looking at the update sql scripts - what is the best format/naming scheme to perform the update?

**Comment by mbabker** [comment]
Whatever the next version is planned to be plus the date you've made the change.  So for now you can go with `3.4.4-2015-07-20.sql`.

As far as the Microsoft drivers go, it doesn't look like they need a change.  Using https://www.mssqltips.com/sqlservertutorial/2203/mysql-to-sql-server-data-type-comparisons/ as a source, it seems several of the MySQL field types (including varchar and text) map to SQL Server's nvarchar field and we're already using [nvarchar(max)](https://github.com/joomla/joomla-cms/blob/3.4.3/installation/sql/sqlazure/joomla.sql#L520) for the field definition.

**Comment by roland-d** [comment]
@spignataro This can't be merged because it is incomplete nor does it have any tests.

**Comment by brianteeman** [comment]
@spignataro  Thank you for your contribution.

The last comment here was on 4 November. Can you please follow-up on this issue? If not this will be closed within 4 weeks

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4010">issues.joomla.org/joomla-cms/4010</a>.</sub>

**Comment by spignataro** [comment]
Brian - I do not know how to make any tests for this as well as I have no way of testing the other databases other than the ones I have access to. What needs to be done to get this merged? I have to hack all the time to get this to work properly.

**Comment by wilsonge** [comment]
I'm going to close this issue for a few reasons:
1) It was a deliberate decision to use text rather than varchar (https://github.com/joomla/joomla-cms/commit/53e91f4847d1300b1128e766382abc6521d9d434)
2) I don't want to encourage people to use the attribs to store custom stuff. You can create custom database tables to do this. There's no reason to hack into com_content's attribs column.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4010">issues.joomla.org/joomla-cms/4010</a>.</sub>

**Pull request closed without merging**
