### PR TITLE
Add a paramter to com_contact to allow the mailto link to be switched on / off

### PR DESCRIPTION
**Pull request by matrikular**
#### Summary of Changes

This PR allows to set the mailto link for each contact individually.

With the additional change to move the cloak handling into the layout, it there can easily be overridden. Also, it is now possible to access the unmodified email address.

**Note: language files were changed and help screens might need to be updated.**
#### Test Instructions
1. **Back-end:** Create a contact. Give it a title and make sure to fill out the email address field. The contact doesn't have to be assigned to a user or a category. For easy access, create a menu item to that contact in a menu of your choice.
2. **Front-end:** Verify that the email address including the mailto link is visible in the front-end. If not, please check the settings for com_contact.
3. **Back-end:** Go to the component settings and set "Add Mailto: Link" to "No"
4. **Front-end:** Refresh the page. Without the patch you will see that the email address will always have a mailto link attached to it.
5. **Front-end** / **Back-end:** Apply the patch and check again. The mailto link can now be switched on or off via component, contact or menu item settings.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I was unable to fit your Instructions:

1. How to assign a Contact not to a Contact-Category? If i delete all Categories got "Invalid field:  Category"
3. Can't find "Add Mailto: Link" in com_contact. Or you mean with "Go to the component settings ..." Plugin "Content - Email Cloaking", where a "Mode: Non-linkable Text" exist.

Please can you explain so i can Test or do i understand some completely wrong?

**Comment by matrikular** [comment]
@franz-wohlkoenig thank you for your feedback.

What I ment was that you don't have to assign the contact to a category other that "Uncategories". You did not have to delete any categories.

The "Add Mailto: Link" parameter in the com_contact options dialoge is only available after you apply the patch There is no connection to the email cloak plugin anymore.

com_contact_options_contact_tab

Of course you can also change the parameter in a contact item or in the menu item options it belongs to.

**Comment by nikitadhiman** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />The patch works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />Tested on Contact General Options, Menu Options and Contact Options to show/hide "Add Mailto: Link".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman can we get a `RTC` label here?

**Comment by brianteeman** [comment]
Someone else will have to do it. I wont personally set a new feature to RTC
if I dont understand it

On 27 March 2016 at 11:20, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> can we get a RTC label here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9490#issuecomment-202032155>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
no Problem. @wilsonge can you set it RTC?

**Comment by Luchen6** [comment]
I have tested this item :red_circle: unsuccessfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />Tested the option for contact and component,
could not find the option in the menu option.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by toxic2302** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />I follow your test instructions and without the patch I have a permanent mailto link. After applying the patch I can switch the mailto link off or on. 
It works for me correctly.

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by Curtista** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />I followed the test steps and before the patch there was a permanent mailto link. After applying the patch the link was gone.
Worked for me.

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by roland-d** [comment]
@matrikular Can you please update your PR so the merge conflicts are resolved? Thank you.

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 90d51bd5aec2f34337a6199aa2fe5596a2f131b9<br /><br />I have tested successfully. I think you should do RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9490">issues.joomla.org/joomla-cms/9490</a>.</sub>

**Comment by andrepereiradasilva** [comment]
without conflicts solved there is no RTC

**Comment by matrikular** [comment]
Could someone please confirm that the conflicts have been resolved by the last commit?

**Comment by brianteeman** [comment]
All good - conflicts resolved
This branch has no conflicts with the base branch

**Comment by franz-wohlkoenig** [comment]
"This branch has conflicts that must be resolved"

**Comment by bertmert** [comment]
Is there a possibility to communicate this change to admins, e.g. via post-installation message.
If one is using a template override for  `components/com_contact/views/contact/tmpl/default_address.php` with "old"

`<?php echo $this->contact->email_to; ?>`

instead of "new"

`<?php echo JHtml::_('email.cloak', $this->contact->email_to, (bool) $this->params->get('add_mailto_link', true)); ?>`

the result will be a not cloaked email address in FE because cloaking has been removed from `view.html.php` with this PR.

**Comment by brianteeman** [comment]
It is not correct to move the cloaking code

**Comment by matrikular** [comment]
@bertmert seems to be a good idea. Either that and / or introducing something similar to $item->email_to_raw, $this>contact->email_to_raw. What do you think?

As you may know, preventing access to the raw email address by cloaking it in the view was a bad choice in the first place.

As to the conflicts, I'll look into that.

**Comment by matrikular** [comment]
Please see #15973

**Pull request closed without merging**
