### PR TITLE
[4.0] Reorder Featured in Sort Table By dropdown

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Reorder Featured in Sort Table By dropdown to match columns order.

### Testing Instructions
Go to Content > Articles
View Sort Table By dropdown.
Go to Components > Contacts
View Sort Table By dropdown.

Featured ascending/descending should be before Status ascending/descending.

### CODE REVIEW

**Comment by richard67** [comment]
Does this solve issue #34501 ?

**Comment by Kostelano** [comment]
@richard67 No, it doesn’t solve the problem, it’s different.

**Comment by brianteeman** [comment]
No it doesnt

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 43d293014e9946e2f86f7643473feea2f049cf6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34535">issues.joomla.org/tracker/joomla-cms/34535</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 43d293014e9946e2f86f7643473feea2f049cf6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34535">issues.joomla.org/tracker/joomla-cms/34535</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34535">issues.joomla.org/tracker/joomla-cms/34535</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
