### PR TITLE
[4.3] typo

### PR DESCRIPTION
**Pull request by brianteeman**
spotted while looking for something else. might as well fix this obvious typo

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 07b0a0a6b25b66daad6d80240fbec6ba2f5bb796<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41121">issues.joomla.org/tracker/joomla-cms/41121</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 07b0a0a6b25b66daad6d80240fbec6ba2f5bb796<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41121">issues.joomla.org/tracker/joomla-cms/41121</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41121">issues.joomla.org/tracker/joomla-cms/41121</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman!

**Pull request merged**
