### PR TITLE
[4.0] Font weight

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #21727

### Summary of Changes
font-weight: normal ===> 400
font-weight: bold ===> 700

As per https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

### CODE REVIEW

**Comment by C-Lodder** [comment]
I still think defining an array of font weight values in an array in `variables.scss` would be better, but whatever you guys prefer.

Primarily because I noticed in a recent project of mine that the bold font wasn't 700 like it normally is, but was 500.

**Comment by brianteeman** [comment]
Would have helped if you had expressed that view in your issue ;)

I just went for the standards

**Comment by C-Lodder** [comment]
@brianteeman I clearly stated in my issue:

> An array of font weights should be defined in the variables.scss with all the possible numeric keywords.

**Comment by C-Lodder** [comment]
Don't get me wrong, this is better than before but could still be a little more dynamic

**Comment by brianteeman** [comment]
apologies - i must have missed it - feel free to submit your own pr for this issue if you wish

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by webgras** [comment]
we tried to test during PBF18.

**What we tested:**
check file administrator/templates/atum/css/template.css

**Result:**
There is still
h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: bold; }

h1 {
  font-weight: normal; }

also in administrator/templates/atum/css/template.min.css
however, we did not find where it comes from.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/tree/4.0-dev#how-to-get-a-working-installation-from-the-source

Did you do npm run build:css

**Comment by webgras** [comment]
yes, we just did build:css again - it is till with "bold" and "normal" there

**Comment by lavipr** [comment]
I have tested this item :white_check_mark: successfully on 78ec12b94424824fcf95d460d7418ae9bfc857e6<br /><br />Testing steps: 
- after installing the patch (not in a nightly build) npm run build:css done
-> all the changed font-weight have no more "normal" or "bold" as values, instead "400" or "700"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21731">issues.joomla.org/tracker/joomla-cms/21731</a>.</sub>

**Comment by brianteeman** [comment]
Don't know what I can tell you

image

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on 78ec12b94424824fcf95d460d7418ae9bfc857e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21731">issues.joomla.org/tracker/joomla-cms/21731</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Can you fix conflicts here please?

**Comment by brianteeman** [comment]
I am not sure it is correct any more based on the comments above by @c-lodder and the recent changes that @wilsonge has committed directly with CSS vars

**Comment by wilsonge** [comment]
I don't think CSS vars has any issues with this. I'd stick with using CSS vars for breakpoints and colours for now - we don't need every single variable to be exposed to users. Fixed conflicts too. If you can do Charlie's solution that would be good though

**Comment by brianteeman** [comment]
I am happy to go with any solution - if you want me to go with Charlie's approach I will do that at the weekend when I am at the sprint

**Comment by brianteeman** [comment]
@C-Lodder is this what you meant?

https://gist.github.com/sumul/2fbe259357888e8d677a

**Comment by brianteeman** [comment]
but named correctly to match the spec https://www.w3.org/TR/css-fonts-3/#propdef-font-weight

**Comment by brianteeman** [comment]
closed see #22317

**Pull request closed without merging**
