### PR TITLE
[Imp] Creating an All Menu dropdown in menu manager

### PR DESCRIPTION
**Pull request by infograf768**
This PR to replace obsolete https://github.com/joomla/joomla-cms/pull/8411
@brianteeman 
@bertmert 
@sural98
@andrepereiradasilva 

To test on staging.

Only change vs https://github.com/joomla/joomla-cms/pull/8411 is the Toolbar Title:
screen shot 2016-02-27 at 18 02 02

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 0605b123170618ba47beb386701ce9a44a0eb1b9<br /><br />Works fine.

I just have a consistency problem with this change.

In all other views, there is only one field (let's call it selector) that, is not inside the "Search filters": the client (or localion).
And this only exist in modules, cache and installed languages views.

That i know of, this is the only view that as a different selector: the menutype, but, if you have "- Select Menu -" option in theory is not a selector anymore as status, access, language and max levels are not. IMHO it turns itself into a search filter. And in that logic it should go inside search filters.
See, for instance, the example of the categories filter in articles view ...

PS: I know that this can be controversal. And don't want to hijact this PR with this, just leaving the thought here.

Marking as tested successfully as this PR works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by infograf768** [comment]
As  most operations and simple structure comprehension in this manager imply selecting a specific menu, I think we should keep the Select Menu separate.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0605b123170618ba47beb386701ce9a44a0eb1b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by infograf768** [comment]
Thanks for testing. Bad luck this would be in 3.6.0 only :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on 0605b123170618ba47beb386701ce9a44a0eb1b9<br /><br />- BE > Menu item manager.
- Select a menu in dropdown select box.
- In column Status click a button to unpublish a menu item.
- Select box always falls back to entry "-Select menu--" and all menu items are shown.

Expected:
- menu select box keeps last selected menu.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by infograf768** [comment]
@bertmert
I confirm the issue. Taking off RTC for now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by infograf768** [comment]
I have already a solution for setdefault  Home which I am now merging.

To solve the publishing state, I did not find any other solution than modifying legacy/controller/admin.php publish() method.

If someone has a better idea, please let me know.

**Comment by infograf768** [comment]
Now the publish() method is overriden. remains the Check-in one.

**Comment by infograf768** [comment]
Please test again all toolbar buttons and Status icons. Issues should be now solved.

**Comment by bertmert** [comment]
**Just a note here** because I couldn't workout detailed and reproducable test instructions yet to open an issue.
For a longer time now (3.4.x, several installations) I see frequently a similiar behavior after login but always just once as far as I remember. Filters "forget" their first settings after some actions in list views (without this PR) and fall back to first entry.
Just a "maybe somewhow related" to https://github.com/joomla/joomla-cms/pull/9231#issuecomment-191943506

**Comment by infograf768** [comment]
In the case here, some code was required (the changes just done i.e. adding `JFactory::getApplication()->getUserState('com_menus.items.menutype')` to be sure to redirect to the correct screen)

If you have experienced issues elsewhere, please create a new issue.
In the mean while, thanks for testing here (and find the issue ☺ ).
If OK for you now, please mark test as successful.

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 52050839f05730b7d453e985cadf32255af63eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 52050839f05730b7d453e985cadf32255af63eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by infograf768** [comment]
thanks for testing. rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by rdeutz** [comment]
looks for me like a new feature, changing Milestone to 3.6.

**Comment by zero-24** [comment]
if there is the decision that this is a new feature can we have a `New feature` label here than? @rdeutz

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 52050839f05730b7d453e985cadf32255af63eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by MDXBilal12** [comment]
I have tested this item :white_check_mark: successfully on 52050839f05730b7d453e985cadf32255af63eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9231">issues.joomla.org/joomla-cms/9231</a>.</sub>

**Comment by rdeutz** [comment]
@infograf768 cloud you please check the merge conflicts, thanks

**Comment by infograf768** [comment]
Hmm. I must have deleted my local instance of this branch.
Here is a new PR conflicts solved.
https://github.com/joomla/joomla-cms/pull/10190

I close this one.

**Comment by zero-24** [comment]
@brianteeman @rdeutz can you remove the RTC label and the milestone?

**Pull request closed without merging**
