### PR TITLE
[4.0] Fix saving modules in frontend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Partial Pull Request for Issue #27283.

### Summary of Changes

Fixes saving modules in frontend.

### Testing Instructions

Login to frontend as admin.
Edit and save a module.

### Expected result

Works.

### Actual result
Error:
>{"error":true,"code":0,"message":"Call to a member function getType() on null"}

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on cdeef2b1086745f803313faa664bc636b2611398<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27441">issues.joomla.org/tracker/joomla-cms/27441</a>.</sub>

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 2c27b738c637bcf5ed7d769956897113ecf9ecfa<br /><br />Error before patch. Successful message and update after patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27441">issues.joomla.org/tracker/joomla-cms/27441</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by leonjehae** [comment]
I have tested this item ✅ successfully also, thnx

**Pull request merged**
