### PR TITLE
[3.9][plugin][privacyconsent] - proper quote with dateAdd()

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #22087 #22079

### Summary of Changes
quoted the `now` date
typecast

### Testing Instructions
see 22087

### CODE REVIEW

**Comment by sanderpotjer** [comment]
@alikon was not sure if the dateAdd function should return the date quoted by default? If we solve it this way I suggest fixing this for all dateAdd usages and not just this one :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22088">issues.joomla.org/tracker/joomla-cms/22088</a>.</sub>

**Comment by alikon** [comment]
well you can find more on #21844 discussion,
https://github.com/joomla/joomla-cms/blob/3.9-dev/libraries/joomla/database/query.php#L1770

**Comment by sanderpotjer** [comment]
@alikon thanks! Can you add the one on line 620 as well of the same file, and the one in public_html/modules/mod_tags_popular/helper.php. I do think we have covered them all with that :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22088">issues.joomla.org/tracker/joomla-cms/22088</a>.</sub>

**Comment by alikon** [comment]
done

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 508b296200c61a1cd1f2a6d15f22d1f2427d0123<br /><br />@alikon great, thanks! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22088">issues.joomla.org/tracker/joomla-cms/22088</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by sandewt** [comment]
Note: it seems that here too a quote is missing

File: ...\plugins\system\privacyconsent\privacyconsent.php
See line 618, ```->where($query->dateAdd($now, $period, 'DAY') . ' > ' . $db->quoteName('created'))```

See also issue #22079<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22088">issues.joomla.org/tracker/joomla-cms/22088</a>.</sub>

**Comment by alikon** [comment]
has been quoted with this PR
https://github.com/joomla/joomla-cms/blob/508b296200c61a1cd1f2a6d15f22d1f2427d0123/plugins/system/privacyconsent/privacyconsent.php#L618

**Comment by sandewt** [comment]
>has been quoted with this PR

Oops, I see, in 39c25c7 8 Sep 2018
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22088">issues.joomla.org/tracker/joomla-cms/22088</a>.</sub>

**Pull request merged**
