### PR TITLE
[com_fields] Add field_id to getFieldValue query

### PR DESCRIPTION
**Pull request by sbouey**
add field_id in the query function getFieldValue , this allow Falang to translate the value.

Pull Request for Issue # .

### CODE REVIEW

**Comment by infograf768** [comment]
Looks fine here.

**Comment by Bakual** [comment]
Adjusted title of PR

**Comment by laoneo** [comment]
Guess this one becomes obsolete when #14558 will get merged. Can you please check if it is also working with #14558?

**Comment by laoneo** [comment]
Can you please test the latest staging if it works out of the box now with Falang? With the merge of #14558  this pr should become obsolete.

**Comment by brianteeman** [comment]
Closed as confirmed that this is no longer needed after #14558

**Pull request closed without merging**
