### PR TITLE
[4.0] ModuleHelper prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements and cleans up queries in `Joomla\CMS\Helper\ModuleHelper`.

### Testing Instructions

Create some modules with all sorts of different settings, e.g. different states, publishing times, menu assignments, languages, etc. Test that modules are rendered only when they should be, i.e. works like before.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a2e7ec82919b7877a9c4c20aa8d43fc675ab1a98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26015">issues.joomla.org/tracker/joomla-cms/26015</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a2e7ec82919b7877a9c4c20aa8d43fc675ab1a98<br /><br />Code review + test if modules still work as before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26015">issues.joomla.org/tracker/joomla-cms/26015</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26015">issues.joomla.org/tracker/joomla-cms/26015</a>.</sub>

**Comment by HLeithner** [comment]
Thank you for making Joomla a bit more secure and optimized.

**Comment by Stuartemk** [comment]
Hello, is it possible to do the same in the menus (to create a cache id and filter by language) ?. Joomla is a great CMS, but in a real world one of the biggest limitations is that it makes no sense that it has the possibility of being multilingual if that feature makes it unfeasible to navigate because the query is extremely slow in a large system, say where There are 5 menu levels in the first level, 20 submenus of the second level per menu and 20 submenus of the third level per submenu, and also repeated by say 5 or 6 languages, the query is around 6000 and that is not practical, You should only make the query for the displayed language and the best thing is that the query will be done in ajax in the sub-levels to avoid consulting everything together and the worst thing is that it loads the total result, of the almost 6000 menus, that is a bad design. How many pages with 1 or two first level menus and 1 or 2 sub-levels deserve to be in 5 languages? Basically none, if a platform has multilanguage capability it is for a robust construction, but it would not make sense, or in its case a less robust platform like WP would be used.
@SharkyKZ  I have seen your contributions and it seems to me that you can possibly give an efficient and effective solution to this situation that at the time was seen in issues #13054 https://github.com/joomla/joomla-cms/issues/13054 but that never really was solved, it was tried to repair with indexes but I understand that it goes beyond, first of all the problem of how the queries are made (queries). I am another Joomla user, I am not the one who started #13054, but the same problem arises. Please apologize in advance if this is not the right place to request this. Thank you all for your great work. 

@alikon @richard67 @HLeithner @joomla-cms-bot

**Comment by richard67** [comment]
@Stuartemk I don't understand how your post is related to this PR here.

**Comment by Stuartemk** [comment]
It seems to me that to do (id cache) and (filter by language) as if you did here, it would be possible to make the menus. @richard67

**Comment by SharkyKZ** [comment]
@Stuartemk it's best that you open a new issue for this.

**Comment by Stuartemk** [comment]
menu_overload


This overload the server, troubleshooting High Time to First Byte (TTFB), slow laod

**Comment by SharkyKZ** [comment]
@Stuartemk Please open a new issue at https://issues.joomla.org so this doesn't get lost.

**Pull request merged**
