### PR TITLE
Fixing preview in Templates > Styles

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Pull Request for Issue #11356 .
#### Summary of Changes

Changed the URL for the preview -> `templateStyle` instead of `template`
#### Testing Instructions

Fixing #11356 - Template Styles

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11358">issues.joomla.org/joomla-cms/11358</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11358">issues.joomla.org/joomla-cms/11358</a>.</sub>

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11358">issues.joomla.org/joomla-cms/11358</a>.</sub>

**Comment by dgt41** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11358">issues.joomla.org/joomla-cms/11358</a>.</sub>

**Comment by zero-24** [comment]
Same here please ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11358">issues.joomla.org/joomla-cms/11358</a>.</sub>

**Pull request merged**
