### PR TITLE
Allow TinyMCE plugin to be reset to default language (english)

### PR DESCRIPTION
**Pull request by jsubri**
Pull Request for Issue # .
### Summary of Changes

Allow TinyMCE plugin to be reset  to default language (english).
Updated the xml file to display the default value.
### Testing Instructions
- Edit the TinyMCE pluging, set "Automatic Language Selection = off", select a "Language Code" such as fr, and save.
- Create a new article, the TinyMCE editor shall display the menus as per the "Language Code".
- Go back to the the TinyMCE pluging, you can't select default (english)

After the patch you can.
### Documentation Changes Required

none

### CODE REVIEW

**Comment by infograf768** [comment]
the issue comes from the fact that the English language in TinyMce is not a xx.js specific file, but is included in the main js files.

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on e7ca7e0fdf2cc3a94c8155634afd6f3e05bc09c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11804">issues.joomla.org/joomla-cms/11804</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on e7ca7e0fdf2cc3a94c8155634afd6f3e05bc09c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11804">issues.joomla.org/joomla-cms/11804</a>.</sub>

**Comment by infograf768** [comment]
This works fine but I propose to also update the language string
from
`PLG_TINY_FIELD_LANGCODE_DESC="Editor UI Language. The value will be used if Automatic language is not set."`
to
`PLG_TINY_FIELD_LANGCODE_DESC="Editor UI Language. The value will be used if Automatic language is not set. 'Use Default' will default to English "`

@brianteeman 
Would that proposal be OK?

**Comment by infograf768** [comment]
Another idea is to use this code:
```
				<field
					name="lang_code"
					type="filelist"
					label="PLG_TINY_FIELD_LANGCODE_LABEL"
					description="PLG_TINY_FIELD_LANGCODE_DESC"
					class="inputbox"
					stripext="1"
					directory="media/editors/tinymce/langs/"
					hide_none="1"
					default="en"
					hide_default="1"
					filter="\.js$"
					size="10"
					showon="lang_mode:0"
					>
					<option value="en">en</option>
				</field>
```
so that we get:
screen shot 2016-08-27 at 07 47 09

@dgt41 

What do you think?

**Comment by brianteeman** [comment]
I am not sure it needs updating at all as the tooltip is clear when you enable the option - but if you insist then

> PLG_TINY_FIELD_LANGCODE_DESC="Editor UI Language. The value will be used if Automatic language is not set. 'Use Default' will default to English "

==>

> PLG_TINY_FIELD_LANGCODE_DESC="Editor UI Language. The value will be used if Automatic language is not set. The Default is English."

**Comment by dgt41** [comment]
IMHO @infograf768 's proposal is the best solution here

**Comment by jsubri** [comment]
Indeed this is a better solution, please re test.
Thank you

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 63a9627c14b02c3177b59ded992556c794e55024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11804">issues.joomla.org/joomla-cms/11804</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 63a9627c14b02c3177b59ded992556c794e55024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11804">issues.joomla.org/joomla-cms/11804</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11804">issues.joomla.org/joomla-cms/11804</a>.</sub>

**Pull request merged**
