### PR TITLE
Change .media-preview-close position

### PR DESCRIPTION
**Pull request by eopws**
### Summary of Changes

Changed modal image close button position in media component.
Changed in order to make the button look nicer.

### Testing Instructions

Go to administrator > media  > open any image

### Actual result BEFORE applying this Pull Request
The button is far away from the image. It looks like a mistake in layout
before

### Expected result AFTER applying this Pull Request
The button is close to the image.
after

### CODE REVIEW

**Comment by richard67** [comment]
@eopws What's the reason why you've made this PR for the 4.1-dev branch and not for 4.0-dev? Is it a new feature so it has to wait until 4.1?

**Comment by eopws** [comment]
> @eopws What's the reason why you've made this PR for the 4.1-dev branch and not for 4.0-dev? Is it a new feature so it has to wait until 4.1?

What is the difference between 4.1-dev and 4.0-dev branches?

**Comment by richard67** [comment]
@eopws The 4.0 dev branch is used for the upcoming Joomla version 4.0, and the 4.1 dev branch for new features which will go into the later 4.1 version. The 4.0-dev branch is up to date with all pull requests we have merged for 4.0, while the 4.1-dev branch will be updated with those later. The 4.1-dev branch we have here only for pull requests which introduce new features which can't go into 4.0 due to the feature freeze in the Beta phase of 4.0.

**Comment by eopws** [comment]
So I have redo this pull request to the 4.0-dev branch, right?

**Comment by brianteeman** [comment]
Just click on edit - top right
image

and then change the base branch to 4.0 from the dropdown

image

**Comment by eopws** [comment]
> Just click on edit - top right
> image
> 
> and then change the base branch to 4.0 from the dropdown
> 
> image

Thank you

**Pull request closed without merging**
