### PR TITLE
[staging] category field readonly when editing an existing item in frontend

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23991

### Summary of Changes
Make the category field readonly when editing an already saved article in frontend to solve confusion.
Such a modification without a new approval could create issues.

### Testing Instructions
Edit an article in frontend
### Before patch
Screen Shot 2019-03-17 at 11 04 45

### After patch
Screen Shot 2019-03-17 at 10 36 02

### CODE REVIEW

**Comment by ghost** [comment]
@Milglius please test.

**Comment by ghost** [comment]
now it is ok , thank you

**Comment by infograf768** [comment]
@Milglius 
Please test OK in https://issues.joomla.org/tracker/joomla-cms/24216

**Comment by ghost** [comment]
@Milglius please mark your Test as successfully at Issue Tracker.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a9b46d9727234aefe00f22c192f85c1ebc34fd11<br /><br />tested OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24216">issues.joomla.org/tracker/joomla-cms/24216</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a9b46d9727234aefe00f22c192f85c1ebc34fd11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24216">issues.joomla.org/tracker/joomla-cms/24216</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Comment by ThomasK0lasa** [comment]
Just an opinion, but that was stupid fix which I don't agree on. Already reversed.

**Comment by ghost** [comment]
@ThomasK0lasa can you please explain your opinion in a friendly way?

**Comment by ThomasK0lasa** [comment]
Hello,

 

of course. I have large website which has 100 users which are used to change their category in case: they will make bad selection at first time, they want to change category of articles which goes to “archive” category different for each year. I also created them access to not publicly available “No category” where they can tweak their articles and then just change the category. So I understand that almost all of this can be done differently, but why remove a feature which is available for years?

 

Also I am not alone with this one: https://forum.joomla.org/viewtopic.php?t=971365 

 

In my opinion bad decision which breaks backward compatibility. If this is needed for some people (I can understand) then just add an option to choose from and leave the old way. :) Something like “Allow Frontend category change after article creation” - true/false.

 

Sincerely,

Thomas

**Comment by infograf768** [comment]
I do understand that this can be an issue for some.
Let me explain again the reasoning. See original issue.
The main problem are the limitations of Joomla ACL. 
We can't separate modifications of the content of an article and its placement in another category.

The original issue is that an author, because he has edit.own permission, can modify the category (including creating a new one) **AFTER the approval** and publishing of the article. 
Any of us can easily understand what kind of potential problems this can cause.

Example of what is already done to prevent some problems with Author's modifications in frontend by default in J:
Author can't set the article as featured.
Author can't modify Publishing dates.

This category change should be reserved to users with upper permissions, **and if they remember in frontend the categories structure for the site**.  
Our ACL are not finetuned enough to define this limitation.
We would need to force a new approval/publish when such a change is done.

So we do have indeed an issue with this readonly patch if the author in frontend has created an article assigned to a specific category and a Publisher or upper wants to correct the category chosen by the author in frontend. 

> If this is needed for some people (I can understand) then just add an option to choose from and leave the old way. :) Something like “Allow Frontend category change after article creation” - true/false.

This is a clever proposal and can be done.
In the mean time you can easily revert this PR for your site.

**Comment by ThomasK0lasa** [comment]
I understand the reasoning why this was done. :)

I just don’t approve changing things in such way that they seem broken :D because this worked differently earlier.

Anyway, I reversed the code and it is ok for now. Have a nice weekend.

**Comment by infograf768** [comment]
We could, as done for featured and publishing, reserve category change to Publishers and up (still prone to errors imho), but better tuning.
Will propose PR for that.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/24640

**Comment by ron4mac** [comment]
Add me to the list of those who feel there needs to be an option with this. I have sites maintained by one or two 'maintainer' group users who are comfortable with frontend operations but would find the backend too confusing (speaking about confusion). No articles are created by anyone else. They like to change the category of an article to place it in somewhat of an archive situation.

**Comment by zero-24** [comment]
@ron4mac please check the PR https://github.com/joomla/joomla-cms/pull/24640 by @infograf768

**Comment by infograf768** [comment]
@ron4mac 
#24640 is now merged and will be available in 3.9.6.
Publishers and up (Therefore your "maintainers") will be able to modify the category in frontend.

**Pull request merged**
