### PR TITLE
[5.0] Fix the extra quotes on the static error pages

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Use the `Ini.unsafe()` to skip the double quotes

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
This will need the language file that was reverted to be included in this pr so that it can be tested

**Comment by dgrammatiko** [comment]
> This will need the language file that was reverted to be included in this pr so that it can be tested

But that PR never got merged, right? https://github.com/joomla/joomla-cms/pull/42019 is still open AFAIC.

**Comment by brianteeman** [comment]
yes - my bad I thought it had been

**Comment by brianteeman** [comment]
tested and it works - thanks!!

image

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
