### PR TITLE
Regression Fixes #9165

### LINKED ISSUE #9165: Weird Update proposed after merging #9118
https://github.com/joomla/joomla-cms/pull/9118 has broken correct update proposals in Control Panel.
I have a component com_localise which is set as 4.0.13-dev (modified, this is why I do not update to the available 4.0.14-dev).

It now displays also as a Joomla Update.

screen shot 2016-02-19 at 08 46 45

Clicking on "Update Now" will load the Joomla Update page where, evidently, no update is proposed.
The Extensions:Update page correcty displays the possible update for the component.

I had to clear the Update cache and then click on Find Updates to get rid of this error.
I am afraid that people updating to 3.5.0 would get the same issue. Any possible solution?

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

See https://github.com/joomla/joomla-cms/issues/9165
#### How to test

See https://github.com/joomla/joomla-cms/issues/9165

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@infograf768 Please  test again if you can.
I can't test it because i have no way to reproduce it.

**Comment by infograf768** [comment]
I could again reproduce the issue on another site after quitting Firefox and relaunch.

When applying this patch which basically reintroduces the original query before https://github.com/joomla/joomla-cms/pull/9118 , the issue is solved.

@wilsonge 

Please merge.

**Comment by infograf768** [comment]
RTC. Important.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9166">issues.joomla.org/joomla-cms/9166</a>.</sub>

**Comment by infograf768** [comment]
Here is a screen record of the issue which gets solved after applying this patch.
https://www.dropbox.com/s/7dqdxuex2h3czgz/iscreen%20record.mp4?dl=0

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva and @infograf768!

**Pull request merged**
