### PR TITLE
[4.2] PHP8.2 Update the debugbar dependency

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Updates the debug bar dependency which contains severeal PHP 8.x compatibility fixes.

### Testing Instructions
- Enable debugging in the joomla configuration
- Open Joomla on PHP 8.2

### Actual result BEFORE applying this Pull Request
The following error is shown:
` Creation of dynamic property DebugBar\DataFormatter\DataFormatter::$cloner is deprecated in`

### Expected result AFTER applying this Pull Request
No debug bar related deprecate warning is shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
My intention was to improve compatibility for PHP 8.2 in 4.2. So we do not have to wait for 4.3.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on faeac11d6973d3fbc0b5fff6e5a5bfcee5762aeb<br /><br />Remember for those who test, do `composer install`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39594">issues.joomla.org/tracker/joomla-cms/39594</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on faeac11d6973d3fbc0b5fff6e5a5bfcee5762aeb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39594">issues.joomla.org/tracker/joomla-cms/39594</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39594">issues.joomla.org/tracker/joomla-cms/39594</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
