### PR TITLE
[5.0] Content refactoring of testing sampledata

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The testing sampledata are currently broken in several regards. The text itself is outdated and sometimes references Joomla 2.5 or even 1.5, the modules aren't displayed everywhere and for the frontend views, not all views are listed. This PR tries to clean all of this up. So far the following changes have been made:

1, Add all frontend views of core components
2. Add all frontend views and modules as sub-menu items of their respective component
3. Make all loadmodule occurences work again
4. Remove references to com_search in menus and modules
5. Refactor menu item creation
6. Refactor module assignments to menu items

This should now be more stable against additional changes to the sample content in the future. It still requires a lot of content updates, especially stuff like atomic and beez templates should be removed and replaced with content about Cassiopeia.

### Testing Instructions
1. Install Joomla
2. Apply testing sampledata
3. Bask in the glory of this newly sorted testing data. 😛 

### Actual result BEFORE applying this Pull Request
Testing sampledata doesn't work in 5.0

### Expected result AFTER applying this Pull Request
Testing sampledata works and is so much cooler than in 4.x

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for doing this. I started a few times but bailed at the size of the task. I will test and comment etc tomorrow.

**Comment by brianteeman** [comment]
https://github.com/Hackwar/joomla-cms/pull/59

**Comment by brianteeman** [comment]
```
                'menutype'          => $menuTypes[3],
                'title'             => $this->getApplication()->getLanguage()->_('PLG_SAMPLEDATA_TESTING_SAMPLEDATA_MENUS_ITEM_8_1_TITLE'),
                'link'              => 'index.php?option=com_content&view=category&layout=blog&id=' . $articleCatids4[5],
                'parent_id'         => $menuIdsLevel1[8],
                'component_id'      => ComponentHelper::getComponent('com_content')->id,
```

articleCatids4[5] is an empty category so another choice should be made

**Comment by brianteeman** [comment]
> 3. Make all loadmodule occurences work again

Still seeing quite a few non-working eg Smart Search

**Comment by Hackwar** [comment]
I did the basics yesterday. Will fix a few more issues now. I hope that this can be finished by the end of the week.

**Comment by brianteeman** [comment]
A deep menu

1. set to not display on the using joomla page but i think thats the _home_ page for that menu
2. doesnt expand

**Comment by Hackwar** [comment]
I did some additional work and would call this ready to be merged. The way it is now, the content shouldn't be entirely broken anymore and changes should be easily incorporated without having to change everything. I would thus hand this over to the documentation team to update the texts. 😃

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on ace4e6e1df4cad45faf6e6dbbc3916051d1a676e<br /><br />I created a new clone of J5.0-dev, installed the patchtester and applied this patch. Then I installed the Test Sample Data. That worked fine and the site looks fine as I remember it from a previous installation. So the patch is good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41489">issues.joomla.org/tracker/joomla-cms/41489</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ace4e6e1df4cad45faf6e6dbbc3916051d1a676e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41489">issues.joomla.org/tracker/joomla-cms/41489</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41489">issues.joomla.org/tracker/joomla-cms/41489</a>.</sub>

**Pull request merged**
