### PR TITLE
Wrong message shown when saving profile in backend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28934.

### Summary of Changes

Corrects message shown when saving profile in backend.

### Testing Instructions

1) Edit your profile in backend (using `com_admin`). Save it. Check the message shown.
2) Send a private message. Check the message shown.

### Expected result

1) > Profile saved.
2) > Message sent.

### Actual result

1) > Message sent.
2) > Message sent.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 84865929c75115a2686693ac2480763b7be3fce3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28939">issues.joomla.org/tracker/joomla-cms/28939</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 84865929c75115a2686693ac2480763b7be3fce3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28939">issues.joomla.org/tracker/joomla-cms/28939</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28939">issues.joomla.org/tracker/joomla-cms/28939</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
