### PR TITLE
Using the "Special:MyLanguage" tag for links pointing to docs.joomla.org

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Using the "Special:MyLanguage" tag for links pointing to docs.joomla.org

### Testing Instructions

- install: https://github.com/zero-24/joomla-cms/archive/mylanguage.zip
- confirm that links to docs.joomla.org point to the localised version if possible
- like the link for the template manager ...
- ... or the readme links in this repo

### Expected result

Links to docs.joomla.org point to the localised version if possible

### Actual result

Links to docs.joomla.org points to the en-GB version even if there is a localised version

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f082452e64b7cb36a231f62ac8d276f2e26c1b8a<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15858">issues.joomla.org/tracker/joomla-cms/15858</a>.</sub>

**Comment by m-b-o** [comment]
I have tested this item :white_check_mark: successfully on f082452e64b7cb36a231f62ac8d276f2e26c1b8a<br /><br />Test succsessfully at an upgraded J! 3.7.0 (coming from 3.6.5)
Works fine <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15858">issues.joomla.org/tracker/joomla-cms/15858</a>.</sub>

**Comment by wojsmol** [comment]
@zero-24 Plase rebase

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wojsmol** [comment]
@franz-wohlkoenig This PR contains conflicts, see github.com.

**Comment by franz-wohlkoenig** [comment]
set back on pending.

**Comment by zero-24** [comment]
Yes it is on my todo list but i did not got the time to fix it. Sorry.

**Comment by zero-24** [comment]
Fixed the merge conflicts please retest.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 883ab5665110e304eb07ec1bed871870a547aa62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15858">issues.joomla.org/tracker/joomla-cms/15858</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@m-b-o can you please retest?

**Comment by m-b-o** [comment]
I have tested this item :white_check_mark: successfully on 883ab5665110e304eb07ec1bed871870a547aa62<br /><br />@franz-wohlkoenig Retest successfully - patch works fine with J! 3.7.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15858">issues.joomla.org/tracker/joomla-cms/15858</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
This can't be set as RTC as we have conflicts.

**Comment by brianteeman** [comment]
Conflicts resolved

**Comment by zero-24** [comment]
drone should be happy now again.

**Comment by brianteeman** [comment]
@zero-24 and thats what I get for using the github conflict resolving tool :(

**Comment by zero-24** [comment]
> @zero-24 and thats what I get for using the github conflict resolving tool :(

np :smile: thanks for fixing the conflicts.

**Pull request merged**
