### PR TITLE
[4.2] fix shortcut Home Dashboard

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

The string JHOMEDASHBOARD="Home Dashboard" was added and the call in shortcut.php was adjusted.

### Testing Instructions

Move to different views in the backend and press the key combination J+X.

### Actual result BEFORE applying this Pull Request

J+D is only translated if com_cpanel.ini is also loaded. However, this is not always the case in the backend.

J+X displays the correct value "Home Dashboard" for J+D when calling /administrator/index.php.
For example, when calling /administrator/index.php?option=com_content&view=article, it will not be translated.

### Expected result AFTER applying this Pull Request

J+D is always translated.

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
Hard for me to test as I cant replicate the problem but the changes make sense

**Comment by tecpromotion** [comment]
> Hard for me to test as I cant replicate the problem but the changes make sense

@brianteeman just go to https://yourdomain.tld/administrator/index.php?option=com_content&view=article and press J+X

With Debug Language on:
Bildschirmfoto 2022-08-29 um 16 53 25

**Comment by webgras** [comment]
I have tested this item :white_check_mark: successfully on 40a722058cac395da8b24843ef041a0ddf98491f<br /><br />I tested this in J4.2 with php 8.1., language string for shortcut description "J+D" is translated now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38632">issues.joomla.org/tracker/joomla-cms/38632</a>.</sub>

**Comment by brianteeman** [comment]
Don't know what to say but it works like this for me without this pr. But the pr still looks good and it probably should have been created your way in the first place.

image

image

**Comment by tecpromotion** [comment]
> Don't know what to say but it works like this for me without this pr. But the pr still looks good and it probably should have been created your way in the first place.

In 4.2.1-rc2 ?

**Comment by webgras** [comment]
> Don't know what to say but it works like this for me without this pr. But the pr still looks good and it probably should have been created your way in the first place.
it is only broken in the dashboard views, like com_contact Dashboard or com_users Dashboard with J+X
i.E. /administrator/index.php?option=com_users&view=users

grafik

**Comment by brianteeman** [comment]
I always test on the absolute latest - so the last commit in my install is #38567 
image

And tested with Danish
image

**Comment by brianteeman** [comment]
And german

image

**Comment by chmst** [comment]
Very strange  - the string is translated without PR, with and 
without debug mode on, 
online and local. 
with and without debug mode
on dashboards, in edit and on list views. 
PHP 8.1.

**Comment by tecpromotion** [comment]
I was able to reproduce it and will validate this tomorrow.

**Comment by tecpromotion** [comment]
1. Install a fresh 4.2.0-rc2 or update from 4.1.5
2. click J+X on Dashboard or anything else - J+D is always translated
3. click on "Post Installation Messages" and hide all messages
4. go to dashboard and click J+X - it's working
5. click anything else - J+D is **not** translated
6. click on "Post Installation Messages" and reset all messages
7. click J+X on Dashboard or anything else - J+D is always translated again!

small video
https://capture.dropbox.com/embed/h1jAJb6IUUKjOkuX

**Comment by brianteeman** [comment]
Bingo - I can now replicate this with your instructions.

The problem exists on any emptystate page.

I think it would be better to find out why that happens than to change the string. This might end up just being a band aid to a bigger problem

**Comment by brianteeman** [comment]
very weird I now see the problem on every page

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 40a722058cac395da8b24843ef041a0ddf98491f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38632">issues.joomla.org/tracker/joomla-cms/38632</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by tecpromotion** [comment]
Thanks @roland-d

**Pull request merged**
