### PR TITLE
Implement extra UTF8MB4 JFilterInput sanity check

### PR DESCRIPTION
**Pull request by wilsonge**
#### Summary of Changes

If we haven't performed the UTF8MB4 conversion on core tables then we should still strip utf8mb4 characters
#### Testing Instructions

Update to Joomla 3.5 beta 5 through extension manager on a utf8mb4 compatible server (do not manually apply the database fixer in extension manager to do the utf8mb4 upgrade). Try and insert some 4 byte characters into the database in a sentence - at first this will cause data loss (all characters will be stripped after the 4 byte character will vanish) as the server hasn't been utf8mb4 provisioned yet. Apply patch and perform the same test -the utf8mb4 character will now be replaced with `\xe2\xAf\x91` character (reference: http://www.utf8-chartable.de/unicode-utf8-table.pl?start=11136&number=128&names=-&utf8=string-literal) and you won't loose any other characters.

Do the database extension fix to upgrade the tables to utf8mb4 - the 4 byte charaters can now be inserted without any issues.

Note this adds effectively a extra DB query to every single page load - is it really required for this edge case?

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@wilsonge is this how it should work?

> Update to Joomla 3.5 beta 5 through extension manager on a utf8mb4 compatible server (do not manually apply the database fixer in extension manager to do the utf8mb4 upgrade). 

Done

> Try and insert some 4 byte characters into the database in a sentence - at first this will cause data loss (all characters will be stripped after the 4 byte character will vanish) as the server hasn't been utf8mb4 provisioned yet. 

Result:
image

> Apply patch and perform the same test -the utf8mb4 character will now be correctly stripped and you won't loose any other characters.

Result
image

> Do the database extension fix to upgrade the tables to utf8mb4 - the 4 byte charaters can now be inserted without any issues.

image

Final result after all steps:
image

**Comment by andrepereiradasilva** [comment]
oh i read wrong all characters will be stripped AFTER the 4 byte character will vanish.

I will test again

**Comment by andrepereiradasilva** [comment]
Deleted previous comments and made new test. I don't see any characters disappearing in any case.

> Update to Joomla 3.5 beta 5 through extension manager on a utf8mb4 compatible server (do not manually apply the database fixer in extension manager to do the utf8mb4 upgrade). 

Done

> Try and insert some 4 byte characters into the database in a sentence - at first this will cause data loss (all characters will be stripped after the 4 byte character will vanish) as the server hasn't been utf8mb4 provisioned yet. 

Result:
image

> Apply patch and perform the same test -the utf8mb4 character will now be correctly stripped and you won't loose any other characters.

Result
image

> Do the database extension fix to upgrade the tables to utf8mb4 - the 4 byte charaters can now be inserted without any issues.

image

BTW used always the same 4 byte character 💩

**Comment by wilsonge** [comment]
So parts 2 and 3 are good for me (amended test instructions as was my bad - we don't strip the utf8mb4 put replace it with that "box" symbol). I don't understand why you get the question mark in the first step tho :/

**Comment by andrepereiradasilva** [comment]
Don't know, this is the test server info:

- Database Version: 5.5.5-10.0.24-MariaDB
- Database Collation: utf8_unicode_ci
- Database Connection Collation: utf8mb4_general_ci
- PHP 5.6.18

Tests made in chrome.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dd90196c7194b59107a331622121b16a67b59e61<br /><br />My test looked exactly the same as andre's, i.e. all as described, and in step 1 a "?".

Database Version: 5.5.47-0+deb7u1-log
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci when looking after the conversion.
PHP Version: 5.6.18
Browser: Firefox 44.0.2

MySQL docs say that in case of supplement charactes (the 4 in mb4) would not be stored at all in utf8 table, so I have no idea how the question mark is generated.

But maybe their doc is wrong or I misunderstand it, thinking they mean what I wrote above, but maybe they mean only migration case, i.e. what was stored in old database which was not utf8mb4 capable, and in new they do this question mark thing?

Or has somewhere else (Nik) already some stripping implemented for the utf8mb4 stuff?

For me this is a positive test result, because the new code after patch works as described, even if the thing in general is worth a discussion.

I did not see any performance problems when testing, so maybe we could live with it like done with this PR?

And I would not rely on the conversion always be successful after using update component to update.

Also I would not say we should not stop support updating with extension installer anymore as long as we have it working (except of this necessary database fix to do the conversion). Some people still might need it, and so they will also need this PR. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9354">issues.joomla.org/joomla-cms/9354</a>.</sub>

**Pull request closed without merging**
