### PR TITLE
[RFC] uncouple guest_usergroup from com_users

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR aims to uncomple guest_usergroup param from com_users and add it to global config instead.

### Testing Instructions

- Code review
- Neeeds to be tested on install AND on update
- For install (test several sample data - since they have different guest user groups)
 - Apply patch, delete configuration.php, refresh page, install Joomla
 - Go to global config and make sure the guest usergroup selected is the "Guest" one
 - Try to change the guest user group and confirm its working fine
- For update
 - [TO DO] If positive comments

Note: Use the most recent version of the patchtester https://github.com/joomla-extensions/patchtester/releases/download/3.0.0-alpha2/com_patchtester.zip if you have memory issues installing the patch

### Documentation Changes Required

Any docs that shows you to set the default guest usergroup needs to be updated.

### Notes

- It should be B/C. But please check.

- Besides from a architucture point it seems better this way, this should speed all guest non com_users pages load by 2 to 4 ms and less ~0.2 MB memory because doesn't need to get the param from com_users component. But that can be added again later if other componet uses JComponetHelper (ex: com_languages)
image

- I didn't test the update process yet, only the new installation process, if comments are favorable to this change will test it and, if needed, make necessary changes.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@mbabker do you agree?

If so, can you help with the unit tests failing?

```
There was 1 failure:
1) JUserHelperTest::testActivateUser with data set "Valid User" ('30cc6de70fb18231196a28dd83363d57', true)
Failed asserting that true matches expected false.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/user/JUserHelperTest.php:309
```

**Comment by brianteeman** [comment]
This doesnt seem correct to me. It might work with the sample data but we have no way of knowing how this is really being used in live sites. They might have heavily customised this group<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12062">issues.joomla.org/joomla-cms/12062</a>.</sub>

**Comment by andrepereiradasilva** [comment]
As said in pr description the update part is not tested yet because this is an rfc.
Anyway the goal is, on update, fetch the current guest usergroup valid an use to populate the new configurações value.

**Comment by mbabker** [comment]
The update part of this is fine.  Actually it's much cleaner than the last time we moved a config from component to global (the text filters, which was done entirely by SQL statements).  The only way it fails is if the component parameters can't be read, which if the update gets that far without being able to read component parameters would be a pretty big miracle.

**Comment by mbabker** [comment]
This PR needs a new owner or it will have to be closed as abandoned.

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12062">issues.joomla.org/tracker/joomla-cms/12062</a>.</sub>

**Pull request closed without merging**
