### PR TITLE
[4.0] Don't deliver old images in J4

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #34931 

### Summary of Changes
Following images are old and in J4 replaced by icons. They should not be delivered in J4.

The old images should NOT be deleted in updated versions where they could be in use by older extensions. 

mooRainbow
arrow.png
arrow_rtl.png
blank.png
calendar.png
checked_out.png
edit.png
edit_unpublished.png
emailButton.png
icon_error.gif
icon-16-logout.png
indent.png
indent1.png
indent2.png
indent3.png
indent4.png
indent5.png
jquery.minicolors.png
livemarks.png
livemarks-rtl.png
mootree.gif
mootree_loader.gif
new.png
no_indent.png
pdf_button.png
printButton.png
rating_star.png
rating_star_blank.png
sort_asc.png
sort_desc.png
sort_none.png
sort0.png
sort1.png
tooltip.png
weblink.png
mooRainbow/blank.gif
mooRainbow/moor_arrows.gif
mooRainbow/moor_slider.gif
mooRainbow/moor_cursor.gif
mooRainbow/moor_woverlay.png
### Actual result BEFORE applying this Pull Request
Joomla as usual

### Expected result AFTER applying this Pull Request
Joomla as usual, no difference is visible

### Documentation Changes Required
no

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8648d1b5536b607bccbd468c7e44a8f6bc5b8b4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34962">issues.joomla.org/tracker/joomla-cms/34962</a>.</sub>

**Comment by richard67** [comment]
I will have to put these files into the list of files to keep in build/deleted_files.php so they won’t be putninto the List of files to be deleted on update. Putting it on my to do list for the case this PR will be merged, what I assume.

**Comment by chmst** [comment]
Thank you @richard67

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 8648d1b5536b607bccbd468c7e44a8f6bc5b8b4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34962">issues.joomla.org/tracker/joomla-cms/34962</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34962">issues.joomla.org/tracker/joomla-cms/34962</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Do you really think we should keep the images on updates?

It means that we have to add all these files to the exclusion list here https://github.com/joomla/joomla-cms/blob/4.0-dev/build/deleted_file_check.php#L155-L182 , because we already delete other images from the "/media/system/images" folder here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L4860-L4873 .

If that would not be the case, we could just exclude the complete folder "/media/system/images" here: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/deleted_file_check.php#L63-L74 .

And maybe the latter is the better way, ignore the complete folder and its subfolder because they all contain only images which might be used somewhere else.

But then we should also remove these lines from script.php: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L4860-L4873 and https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L6142 .

Which way would you prefer?

**Comment by chmst** [comment]
> we could just exclude the complete folder "/media/system/images" 

I think this is the best way, but of course @wilsonge decides

**Comment by brianteeman** [comment]
> @wilsonge Do you really think we should keep the images on updates?

I'm not George but if you dont keep them you potentially break sites

**Comment by wilsonge** [comment]
@richard67 add them to the exclude list - I honestly doubt these are used (unless people have sample data lying around - but that's normally not intended) but I don't think it's worth risking it

**Comment by wilsonge** [comment]
Merging just so we don't have to care about potential deletions or not within the 4.x series

**Comment by richard67** [comment]
> @richard67 add them to the exclude list

@wilsonge You mean the single files? Or the complete folder?

**Comment by wilsonge** [comment]
Both.

**Comment by richard67** [comment]
> Both.

@wilsonge It seems you did not get which folder I mean. See my comment above again for details: https://github.com/joomla/joomla-cms/pull/34962#issuecomment-889757287

> If that would not be the case, we could just exclude the complete folder "/media/system/images" here: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/deleted_file_check.php#L63-L74 .
>
> And maybe the latter is the better way, ignore the complete folder and its subfolder because they all contain only images which might be used somewhere else.
>
> But then we should also remove these lines from script.php: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L4860-L4873 and https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L6142 .
>
> Which way would you prefer?

**Comment by richard67** [comment]
@wilsonge Or in other words: which of these 2 do you prefer?

1. https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-deleted-files-update-files-to-keep-2021-08-02

2. https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-deleted-files-update-files-to-keep-2021-08-02_variant-2

The first one results in only the files handled in this PR here being kept on update, while the second one results in all files in folder "/media/system/images" and its subfolders being kept.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-deleted-files-update-files-to-keep-2021-08-02_variant-2 this one i think.

**Comment by richard67** [comment]
> [4.0-dev...richard67:4.0-dev-deleted-files-update-files-to-keep-2021-08-02_variant-2](https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-deleted-files-update-files-to-keep-2021-08-02_variant-2) this one i think.

Done, see #35070 .

**Pull request merged**
