### PR TITLE
[4.0] fix alpha ordering

### PR DESCRIPTION
**Pull request by tecpromotion**
noticed when translating the german language packs for 4.0-dev

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4dee82ba57f3795daf4107f7e31cdd76c9cebda2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24588">issues.joomla.org/tracker/joomla-cms/24588</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4dee82ba57f3795daf4107f7e31cdd76c9cebda2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24588">issues.joomla.org/tracker/joomla-cms/24588</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24588">issues.joomla.org/tracker/joomla-cms/24588</a>.</sub>

**Comment by zero-24** [comment]
Merged

**Pull request merged**
