### PR TITLE
Update loadmodule.php

### PR DESCRIPTION
**Pull request by jeffda**
Remove <p/> wrapper injected by editors like TinyMCE.

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
Can you please add a Summary of what this PR does and test instructions for it, following the PR template for this repo?
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13191">issues.joomla.org/tracker/joomla-cms/13191</a>.</sub>

**Comment by C-Lodder** [comment]
Testing instructions (from what I think the code does):

- Open an Article in the Article Manager
- Add `{loadposition XXX}` via the source code in TinyMCE (or codemirror instead)
- Add `<p>{loadposition XXX}</p>` via the source code in TinyMCE (or codemirror instead)
- Ensure both modules are visible in the frontend

**Comment by ggppdk** [comment]
I guess you want to remove the P tag,
added by the HTML editor when you press enter to go to the next line

It is not proper way to remove HTML code for 1 specific case there,
it looks very much like an unneeded hack

-- what about if, instead of P, the default wrapping TAG of the editor was configured to be DIV or other ?
-- plus how do you disguish the cases that P tag, was added intentionally ?

If you want to remove the styling adding by the P
-- you can edit the HTML and change it to DIV, which (usually) by default has no styling assigned to it

but i do understand that the default wrapping TAG is P, and usually Joomla templates, by default,
they do add some styling for the P tag (e.g. padding) , and this is an annoyance

**Comment by dgt41** [comment]
Totally agree with @ggppdk here. Also the proposed code will break on **all** other editors or tinyMCE with div as the wrapping tag

**Comment by jeckodevelopment** [comment]
Closing because: 

> will break on all other editors or tinyMCE with div as the wrapping tag

**Pull request closed without merging**
