### PR TITLE
A11y GitHub issue template

### PR DESCRIPTION
**Pull request by crystalenka**
### Summary of Changes
Per the [Joomla Accessibility Team meeting on May 24](https://volunteers.joomla.org/teams/accessibility-team/reports/1734-joomla-accessibility-team-meeting-may-24-2022), it would be helpful to have an a11y-specific template when opening a Github issue for Joomla CMS. That way we can include specific questions and more easily identify and mitigate a11y issues.

### CODE REVIEW

**Comment by brianteeman** [comment]
Great.

Personally other than the final wcag question these should be asked on all issues

**Comment by crystalenka** [comment]
> Great.
> 
> Personally other than the final wcag question these should be asked on all issues

Totally agree. If/when this is merged I might open a new PR for the main issue template(s) to add some of those questions.

**Comment by crystalenka** [comment]
One thing I'm not sure about - is it possible to set up the cms bot to add the a11y tag automatically to issues created with this template?

**Comment by brianteeman** [comment]
Yes it is possible but sorry I don't know how to do that

**Comment by chmst** [comment]
> Personally other than the final wcag question these should be asked on all issues 

Except the question about assistive technologies, this will be unanswered in nearly all issues

**Comment by chmst** [comment]
> One thing I'm not sure about - is it possible to set up the cms bot to add the a11y tag automatically to issues created with this template?

@zero-24 can you help here?

**Comment by zero-24** [comment]
> > One thing I'm not sure about - is it possible to set up the cms bot to add the a11y tag automatically to issues created with this template?
> 
> @zero-24 can you help here?

I'm not aware of any that we can use right now. I could think of an "[A11Y]" tag in the title which could assign the label but hat has to be thought out what would make sense here as this can go wild fast. Maybe there is a way that is supported by github?

**Comment by crystalenka** [comment]
This appears to be possible and it's also apparently possible to make it (and the others) an actual form with fields which might help all of the different issue templates:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

I'm going to do some digging. Would you all be open to revising the other templates too if this turns out to be easier? I could make a master pull request for all at once.

**Comment by zero-24** [comment]
go for it when you get a few minutes. always better when we use github core features over doing something with our bots and api stuff. l

**Comment by brianteeman** [comment]
Couple of things I just remembered. 

1. I think the issue template here does not get used on issues.joomla.org and that has its own template??
2. Making it a form is something that got generally bad feedback in the github maintainers chat

**Comment by crystalenka** [comment]
Brian, can you elaborate especially on point 2?

**Comment by brianteeman** [comment]
Although I have never used it myself people commented that they didnt like that you had to complete all the fields and it prevented using other reporting tools which interact directly with github. (maybe thats fixed now I dont know) but below is an example report that is generated directly from Accessibility Insights for Web and posted into github which people saaid was not possible to use when you have these fields etc.

#### Issue
`Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds` ([color-contrast](https://accessibilityinsights.io/info-examples/web/color-contrast))
#### Target application
[Joomla Content Management System (CMS) - try it! It's free!](https://www.joomla.org/)
#### Element path
footer > a[title="Free hosted Joomla! website"][href$="launch.joomla.org"]
#### Snippet
`<a href="https://launch.joomla.org" title="Free hosted Joomla! website">Launch Joomla! →</a>`
#### How to fix
    Fix any of the following:
      Element has insufficient color contrast of 3.34 (foreground color: #ffffff, background color: #5091cd, font size: 15.0pt (20px), font weight: normal). Expected contrast ratio of 4.5:1
#### Environment
Chrome version 101.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.32.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

**Comment by crystalenka** [comment]
The GitHub docs say that you can mark fields as required or not required, but I'm not sure about integration with automated reporting tools that open new issues.

**Comment by crystalenka** [comment]
I found a way to add the label automatically in the YAML frontmatter in the standard template [per GH docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository). To get this done faster, I just added it here.

We can table the conversation about issue forms for another time, perhaps when it's out of beta.

**Comment by chmst** [comment]
I too don't like issue forms on github. A template is a great help, but a form is a corset ;) 

I think this can be merged and other templates can be adapted, but don't mix it.

**Comment by brianteeman** [comment]
>   a form is a corset ;)

I'm guessing thats a direct translation from german? Never heard that expression in english before but it is perfect

**Comment by crystalenka** [comment]
Are there any other changes at this point or can it be merged? :) not sure who has the access to do that otherwise I'd tag the appropriate people.

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
