### PR TITLE
Set maximum session lifetime

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #13933

Really just to protect crazy settings

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 181f5226010b1e30fac5cae1bb7566e3faae4b3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17609">issues.joomla.org/tracker/joomla-cms/17609</a>.</sub>

**Comment by Schmidie64** [comment]
I have tested this item :white_check_mark: successfully on 181f5226010b1e30fac5cae1bb7566e3faae4b3c<br /><br />@icampus
I've tested this PR sucessully. But maybe you should add a check to prevent high values in the config(see attachment)[configuration.php](http://www.picfront.org/d/9Bkl "configuration.php") :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17609">issues.joomla.org/tracker/joomla-cms/17609</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
We don't have any other checks for someone manually editing the file on the server with crazy values

**Comment by brianteeman** [comment]
Thanks so for testing and merging

**Comment by tonypartridge** [comment]
Thanks for doing @brianteeman!

**Pull request merged**
