### PR TITLE
[5.0]Remove unused workflow strings

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Removes strings that have never ever been used and marked as deprecated in #40510

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wilsonge** [comment]
So now 4.4 has been merged into 5.0 there's no net changes from this PR. Presumably you still want to remove the big block of strings at the bottom of the file though?

**Comment by brianteeman** [comment]
should be done now - thanks @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on d3995f042de59d8fefd9912495dbdba772bb4046<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40511">issues.joomla.org/tracker/joomla-cms/40511</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7519e952d4f2491b90a6d756e2e87d3abcb586e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40511">issues.joomla.org/tracker/joomla-cms/40511</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40511">issues.joomla.org/tracker/joomla-cms/40511</a>.</sub>

**Pull request merged**
