### PR TITLE
Added php8 to list of forbidden executable extensions

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Added PHP8 to the hardcoded list of executables 

### Testing Instructions
Verify by code review

### CODE REVIEW

**Comment by richard67** [comment]
As it's for staging I've removed the "[3.10]" from the title.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 595e238b710818e13529ff494f2cf8b24dce92b0<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 595e238b710818e13529ff494f2cf8b24dce92b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by richard67** [comment]
@SniperSister It's not sufficient to set the RTC label on GitHub to get the right status shown in the issue tracker. It needs to use the tracker and change status there. I've done that here now.

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
Drone failing for unrelated reasons ... restarted to see if it succeeds this time.

**Comment by brianteeman** [comment]
I have not tested this item.<br /><br />reverting my successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 595e238b710818e13529ff494f2cf8b24dce92b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 595e238b710818e13529ff494f2cf8b24dce92b0<br /><br />The reasoning behind this list makes it incomplete<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35000">issues.joomla.org/tracker/joomla-cms/35000</a>.</sub>

**Comment by zero-24** [comment]
Merging to sync up with 4.0: https://github.com/joomla/joomla-cms/pull/35001 Thanks!

**Pull request merged**
