### PR TITLE
[3.0] Remove duplicate attributes

### PR DESCRIPTION
**Pull request by janschoenherr**
Fix markup. Browsers use the first data-toggle only.

### Summary of Changes

Remove duplicate data-toggle attribute.

### CODE REVIEW

**Comment by brianteeman** [comment]
Where is this used? Please provide instructions on how to test this

**Comment by brianteeman** [comment]
Found it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35936">issues.joomla.org/tracker/joomla-cms/35936</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 05ae249b445bce957f6187e11c18ca64e264204c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35936">issues.joomla.org/tracker/joomla-cms/35936</a>.</sub>

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on 05ae249b445bce957f6187e11c18ca64e264204c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35936">issues.joomla.org/tracker/joomla-cms/35936</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35936">issues.joomla.org/tracker/joomla-cms/35936</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 05ae249b445bce957f6187e11c18ca64e264204c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35936">issues.joomla.org/tracker/joomla-cms/35936</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
