### PR TITLE
[4.0] Wrap all buttons in btn-group to improve styling

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #29504 .

### Summary of Changes

This pr will put elements in horizontal line

### Testing Instructions

Joomla 4 with "Testing Sample Data"
url => index.php/recipes

### Actual result BEFORE applying this Pull Request

See screenshot in #29504

### Expected result AFTER applying this Pull Request

Schermafbeelding 2020-09-25 om 08 53 05

### CODE REVIEW

**Comment by hans2103** [comment]
spacing between items is out of scope for this pr

**Comment by infograf768** [comment]
Is it useful to display the Filter Button if `filter-field` is set to `hide`?
I suggest to modify that part to
```
			<?php if ($this->params->get('filter_field') !== 'hide') : ?>
				<div class="com-content-category__filter-submit control-group hidden-xs-up float-right">
					<div class="controls">
						<button type="submit" name="filter_submit" class="btn btn-primary"><?php echo Text::_('COM_CONTENT_FORM_FILTER_SUBMIT'); ?></button>
					</div>
				</div>
			<?php endif; ?>
```

**Comment by infograf768** [comment]
Also, for a11y, the table is missing something like
```
<caption id="captionTable" class="sr-only">
					<?php echo Text::_('COM_CONTENT_ARTICLES_TABLE_CAPTION'); ?>,
				</caption>
```

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f7fc1bd4b865c2eedbbab019e232d042205ddb10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30761">issues.joomla.org/tracker/joomla-cms/30761</a>.</sub>

**Comment by infograf768** [comment]
@Formatio-hippocampi 
Please wait for @hans2103 to take care of my comments. :)

**Comment by hans2103** [comment]
@infograf768 
I don't know if it is useful to display the Filter Button if `filter-field` is set to `hide`?
I haven't looked into the functionality of the rendered fields nor buttons. This is not the scope of this PR. 

Table Caption out of scope of this PR too... created new pr for it. https://github.com/joomla/joomla-cms/pull/30763

**Comment by infograf768** [comment]
I should have been more precise:
The Filter button IS useless when `filter-field` is set to `hide`...

**Comment by hans2103** [comment]
@infograf768 adjusted PR.
Actually you are saying that a PR was needed anyway to solve the display of the button? Not only to fix alignment

**Comment by Quy** [comment]
The button is also required for the pagination selection dropdown.

**Comment by Quy** [comment]
In a separate PR, filters section shouldn't be hidden when no items.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f74fdb1a3c3ff34242823d7c433560e1f9eeb80e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30761">issues.joomla.org/tracker/joomla-cms/30761</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f74fdb1a3c3ff34242823d7c433560e1f9eeb80e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30761">issues.joomla.org/tracker/joomla-cms/30761</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30761">issues.joomla.org/tracker/joomla-cms/30761</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
