### PR TITLE
[4.0] Add prepared statements for plg_actionlog_joomla

### PR DESCRIPTION
**Pull request by HLeithner**
### Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

* Activate the privacy extension with actionlog
* change the state of a article
* You should see the change in the actionlog as without the PR

### Expected result
Nothing changed.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 198a4e484d4a393c2f664cafbd524bf4e2f09a28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25046">issues.joomla.org/tracker/joomla-cms/25046</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 198a4e484d4a393c2f664cafbd524bf4e2f09a28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25046">issues.joomla.org/tracker/joomla-cms/25046</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25046">issues.joomla.org/tracker/joomla-cms/25046</a>.</sub>

**Comment by roland-d** [comment]
@HLeithner the code works but is it correct the query is:
```
`SELECT `title`,`id`
FROM `jos_content`
WHERE `id` IN (:preparedArray1)
```

The `:preparedArray1` looks odd.

**Comment by HLeithner** [comment]
:preparedArray1 is defined in the database driver. I selected this name because I hope nobody else will use it by accident.

**Comment by SniperSister** [comment]
Merged, thanks!

**Pull request merged**
