### PR TITLE
[4.0] [plg_system_webauthn] Lowercase plugin name

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Changes plugin name to be lowercase like in all other plugins.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5b26c7df1d7a723867f38b599ad400a6b219f7f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29227">issues.joomla.org/tracker/joomla-cms/29227</a>.</sub>

**Comment by HLeithner** [comment]
Isn't it wrong in all others? Normally our language strings are all uppercase iirc? But no problem with this just a question.

**Comment by SharkyKZ** [comment]
@HLeithner This is also stored in `#__extensions`  table and in some places we still use extension name for running queries. Having casing discrepancy would break on PostgreSQL.

Although this specific case probably doesn't cause issues, it's just a matter of consistency.

**Comment by infograf768** [comment]
In fact it is epiphenomenic as we use strtoupper when in lower case.

Edit: when I wrote the above, I was not aware about possible issues in PostgresSQL

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5b26c7df1d7a723867f38b599ad400a6b219f7f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29227">issues.joomla.org/tracker/joomla-cms/29227</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
