### PR TITLE
Add type declarations and clean up src/Router

### PR DESCRIPTION
**Pull request by ditsuke**
Considering Joomla 4.0 requires a minimum PHP 7.2.5, it should be safe to add 
type declarations supported by `PHP >= 7.2`. 

### Summary of Changes
This PR adds argument and return type declarations compatible with PHP >= 7.2 
to `src/Router`. It also cleans up some phpdocs and inline comments,
and some more minor cleanup.

### Testing Instructions
Test on PHP 7.2.5

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ditsuke** [comment]
@richard67 what do you think of this?

**Comment by brianteeman** [comment]
definitely can't be done in 4.0 at this late stage

**Comment by ditsuke** [comment]
> 
> 
> definitely can't be done in 4.0 at this late stage

Would it be possible for 4.1?

**Comment by dgrammatiko** [comment]
> definitely can't be done in 4.0 at this late stage

May I ask why? It's just type-hinting, the return or the arguments are already expected to be a specific type and this PR just forces what should have been the default

**Comment by wilsonge** [comment]
> May I ask why? It's just type-hinting, the return or the arguments are already expected to be a specific type and this PR just forces what should have been the default

Because anyone with a custom router (i don't know if it's still the case but pretty sure e.g. kunena had at one point) will have a b/c break :( PHP throws static if you don't have the same type declaration in child classes.

**Comment by dgrammatiko** [comment]
The API part is brand new code so it could be done at least there

**Comment by wilsonge** [comment]
> The API part is brand new code so it could be done at least there

Like I said there's php notices thrown if the parent class doesn't match with the child class. You can't just do it in the API. Has to be the parent Router class and all it's children or nothing. That's why adding in typehints across core is going to be so painful on the "old" pre-4.0 classes

**Comment by brianteeman** [comment]
... and why it cannot be done at this moment in time with a release caandidate

**Comment by RickR2H** [comment]
Should this be tested?

**Comment by ditsuke** [comment]
@Quy I've resolved the conflicts here

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by laoneo** [comment]
I'm going to close this one as it is not possible to add typehinting to existing library classes, because it is not possible to have a transition period. It is an all or nothing backwards compatibility break. What you can do is to create new functions with the typehinted arguments and deprecate the old ones.

**Pull request closed without merging**
