### PR TITLE
[4.0] Atum template strings

### PR DESCRIPTION
**Pull request by brianteeman**
Correct some strings to match the style guide
Remove some strings no longer in use
Rename one string

### Testing Instructions
Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 894b94040aed7f969253f7db0b674bae62e9ef7d<br /><br />Strings TPL_ATUM_CLEAR_CACHE, TPL_ATUM_INSTALLER and TPL_ATUM_MENU are not used anywhere, and string TPL_BACK_TO_CONTROL_PANEL will be obsolete, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25064">issues.joomla.org/tracker/joomla-cms/25064</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 894b94040aed7f969253f7db0b674bae62e9ef7d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25064">issues.joomla.org/tracker/joomla-cms/25064</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25064">issues.joomla.org/tracker/joomla-cms/25064</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
