### PR TITLE
[4.0] [a11y] Set login page title

### PR DESCRIPTION
**Pull request by brianteeman**
a11y rules says that every page should have a meaningfu title

This PR adds the title "Administrator Login - sitename" to the title on the login page

### CODE REVIEW

**Comment by wilsonge** [comment]
For RTL Sites do we need to make this a sprintf rather than hardcoding it as 3 parts?

**Comment by brianteeman** [comment]
It's the page title in the browser not on screen so it depends a lot on the browser and most dont support rtl in the title

https://w3c.github.io/i18n-tests/results/native-user-interfaces

**Comment by brianteeman** [comment]
As it's a subjective thing which comes first, site name or title, I can try and change this pr to use the setting in the global.config.

**Comment by wilsonge** [comment]
I'm not too fussed. My question was just that - I just want to make sure we're not screwing things up again for RTL users

**Comment by brianteeman** [comment]
Scrub that idea - the option is only for the frontend 

but I just checked and the page title for the admin is set with this
`$document->setTitle($this->get('sitename') . ' - ' . Text::_('JADMINISTRATION'));
`
and is not RTL aware - so I just updated this PR to match the order with sitename first

**Comment by wilsonge** [comment]
OK Cool. i'm down. and if we do need to change it in the future shouldn't be too hard

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
