### PR TITLE
[4.0] typo draggable

### PR DESCRIPTION
**Pull request by brianteeman**
After PR #29978 this corrects the comment

code review 
cc @zero-24

### CODE REVIEW

**Comment by PhilETaylor** [comment]
There are a lot of other misspelt `dragable` in comments if you want to add those here?

Im guessing `dragable-group` is a deliberate typo in code?

Screenshot 2020-07-05 at 12 51 41

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 4df327697b33bd6393989450b2c62c23b3316715<br /><br />I can confirm the typo. But as Phil mentions in https://github.com/joomla/joomla-cms/pull/29984#issuecomment-653879227 there are a lot of `draggable` typos in Joomla. Can you fix those in this PR too?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29984">issues.joomla.org/tracker/joomla-cms/29984</a>.</sub>

**Comment by brianteeman** [comment]
Beyond the scope

**Comment by zero-24** [comment]
Merging thanks.

**Comment by hans2103** [comment]
Created a new PR to search for `dragable` and replace it by `draggable`

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
