### PR TITLE
[4.0] Rename alert-default to alert-secondary

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
There is no `alert-default` in BS5. Rename it to its equivalency.

Go here to see possible variants:
https://getbootstrap.com/docs/5.0/components/alerts/

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 72bab128fefed7a8899b7131016ecb9432930e6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33429">issues.joomla.org/tracker/joomla-cms/33429</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 72bab128fefed7a8899b7131016ecb9432930e6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33429">issues.joomla.org/tracker/joomla-cms/33429</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33429">issues.joomla.org/tracker/joomla-cms/33429</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
