### PR TITLE
[4.0] Add sanity checks on the asset file

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #30972 .

### Summary of Changes
Adds sanity checks in com_template dealing with the asset file. You can no longer delete the file, rename it and it enforces valid JSON (reverting the file contents if there is invalid JSON).

### Testing Instructions
Try deleting the asset file from cassiopia - Currently gives a 500 error to the template. After patch blocked
Try renaming the file - same result as above
Try making the file have invalid JSON (by removing a comma or quote etc). - before 500 error on the template. After error message shown and file contents reverted to last stable version

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 9157a53b6cdf9168507ec7c498a901f2b83c858d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31710">issues.joomla.org/tracker/joomla-cms/31710</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9157a53b6cdf9168507ec7c498a901f2b83c858d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31710">issues.joomla.org/tracker/joomla-cms/31710</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by PhilETaylor** [comment]
But you can still delete index.php :-) :-)

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/31710/files#diff-f8cdbf76bd7ec97273fa80336eac2a426c46c17c77638c9f1f0a4340e0fce9d3L453 I don't think so?

**Comment by PhilETaylor** [comment]
I know so :) 

Watch:
https://user-images.githubusercontent.com/400092/104434940-be7ef480-5583-11eb-8f71-0bae3d910799.mp4

**Comment by PhilETaylor** [comment]
Forked to https://github.com/joomla/joomla-cms/issues/32026 as not to be lost as this PR is already merged.

**Pull request merged**
