### PR TITLE
[4.0] Correcting Cassiopeia scss error

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/22830

### Summary of Changes
$atum =>$cassiopeia

### Testing Instructions
patch a clean checkout of the 4.0-dev branch
Run npm install

### Expected result
Now the css files are created for cassiopeia

Can be merged on review (I guess)

### CODE REVIEW

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on a1a738bfbec5288577ba77cca41cba6818d757bf<br /><br />I got all cassiopeia css files back but 
I had to remove line 27 in /build/build-modules-js/update.js to allow
       `npm install`
to work.
``` 
fsExtra.copySync(Path.join(rootPath, 'libraries/vendor/maximebf/debugbar/src/DebugBar/Resources'), Path.join(rootPath, 'media/vendor/debugbar'));
```
Not sure if it is the right way though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22831">issues.joomla.org/tracker/joomla-cms/22831</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on a1a738bfbec5288577ba77cca41cba6818d757bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22831">issues.joomla.org/tracker/joomla-cms/22831</a>.</sub>

**Comment by infograf768** [comment]
rtc. @wilsonge <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22831">issues.joomla.org/tracker/joomla-cms/22831</a>.</sub>

**Comment by Chacapamac** [comment]
How do I know when & where I apply the fix or update?

**Comment by ghazal** [comment]
Check this:
J4.x:Setting Up Your Local Environment - Joomla! Documentation
https://docs.joomla.org/Special:MyLanguage/J4.x:Setting_Up_Your_Local_Environment
and this:
JavaScript Tests for Joomla4 - Joomla! Documentation
https://docs.joomla.org/JavaScript_Tests_for_Joomla4

Even though, in my opinion, these tuts should be revised.

**Comment by ghost** [comment]
> Even though, in my opinion, these tuts should be revised.

"Docs" is a Wiki, so anyone can contribute, revise ;-)

**Comment by ghazal** [comment]
Yes. Indeed.
But my knowledge of CLI, NPM, Composer, etc ... is barely sufficient to get me through the procedure. I have more questions than answers.

**Comment by wilsonge** [comment]
So what specific question do you have :) here to help!

**Pull request merged**
