### PR TITLE
fix replaceTags function for array

### PR DESCRIPTION
**Pull request by keewhip**
Pull Request for Issue #38279.

### Summary of Changes
If value to replace is an array, it is now replaced with the value
Like user custom fields

### Testing Instructions
Create a user required custom field named **testfield**
Show this field on registration page
Include this field in the new user mailtemplate using the code {COM_FIELDS}testfield{/COM_FIELDS}
Register an new user account

### Actual result BEFORE applying this Pull Request
The placeholder is replaced with a empty string

### Expected result AFTER applying this Pull Request
The placeholder is replaced with the value submitted by the user

### Documentation Changes Required
None

### CODE REVIEW

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on a209ffb67f1f05b193213aff7e07b72aa08cd194<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38305">issues.joomla.org/tracker/joomla-cms/38305</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a209ffb67f1f05b193213aff7e07b72aa08cd194<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38305">issues.joomla.org/tracker/joomla-cms/38305</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38305">issues.joomla.org/tracker/joomla-cms/38305</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for fixing this bug!

**Comment by ReLater** [comment]
This change has opened another issue. See https://github.com/joomla/joomla-cms/issues/39774

**Pull request merged**
