### PR TITLE
JUpdate *_dev_level handling

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

https://github.com/joomla/joomla-cms/pull/5546 changed some of the version processing for update XML manifests and silently deprecated support for attributes of the `<targetplatform>` tag.  This PR adds a deprecation log notice for these attributes.

Additionally, `JUpdate` also uses this data and is now inconsistent with the extension adapter as far as features go.  The class is also updated to support the changes from https://github.com/joomla/joomla-cms/pull/5546 and adds the deprecation logging as needed there too.

Lastly, `JVersion` doesn't need to be instantiated to use class constants.  So, changed that.
#### Testing Instructions

With the patch applied, updates should still be correctly pulled for core and extensions.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@mbabker i still got the problem

How did i test:
- Used latest staging (3.5.0-rc), and created the following update channel
 - https://raw.githubusercontent.com/andrepereiradasilva/update.joomla.org/master/www/core/teststs/list_sts.xml
 - https://raw.githubusercontent.com/andrepereiradasilva/update.joomla.org/master/www/core/teststs/extension_sts.xml
- Joomla Update ... Options ... custom URL (used the first link above)
- Clear cache (Note: i add to clear cache several times.)
- The error appeared
- Applied your patch
- Joomla Update.  Clear cache (Note: i add to clear cache several times.)
- The error appeared

image

Please notice that in my custom update channel i simulated a 3.5.1 release only for 3.5, but in the extension xml the update is only for joomla `3.[34]` and php minimum `8.0.0` just for testing proposes.

**Comment by mbabker** [comment]
This PR does nothing with that issue.

**Comment by andrepereiradasilva** [comment]
oh ok i thought this was to solve that. sorry them.

**Comment by andrepereiradasilva** [comment]
removed comments made by mistake

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 4c4d6262f9fcf2c90ce82c537190d473397e46f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9410">issues.joomla.org/joomla-cms/9410</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4c4d6262f9fcf2c90ce82c537190d473397e46f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9410">issues.joomla.org/joomla-cms/9410</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9410">issues.joomla.org/joomla-cms/9410</a>.</sub>

**Pull request merged**
