### PR TITLE
[4] docblock s/string/array

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on fb4f0e27837a73cde9414c97a9d7760dc556e3ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35135">issues.joomla.org/tracker/joomla-cms/35135</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on fb4f0e27837a73cde9414c97a9d7760dc556e3ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35135">issues.joomla.org/tracker/joomla-cms/35135</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35135">issues.joomla.org/tracker/joomla-cms/35135</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks.

**Pull request merged**
