### PR TITLE
[4.0] Rename Check and Install button

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
For consistency, the usage of `and` with `&` in `Upload & Install` and `Save & Close`, rename `Check and Install` to `Check & Install`.

### Testing Instructions
System > Install > Extensions
Click Install from Folder tab.
See `Check and Install` button.
Click Install from URL tab.
See `Check and Install` button.

System > Update >Joomla
Click Upload & Update tab.
See `Upload & Install` button.

Apply PR.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 88edf93a755feb4df7a93b6588a81bae36a3e02d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33855">issues.joomla.org/tracker/joomla-cms/33855</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 88edf93a755feb4df7a93b6588a81bae36a3e02d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33855">issues.joomla.org/tracker/joomla-cms/33855</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 88edf93a755feb4df7a93b6588a81bae36a3e02d<br /><br />Test successful but on a grammatical note is this the correct use of ampersand.  I was always taught that it should only be used where the words are naturally co-joined in a well known phrase like "Research & Development"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33855">issues.joomla.org/tracker/joomla-cms/33855</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33855">issues.joomla.org/tracker/joomla-cms/33855</a>.</sub>

**Pull request merged**
