### PR TITLE
[4.0] com_admin typos

### PR DESCRIPTION
**Pull request by brianteeman**
code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
Not sure, but could you check line 4379 again pls?
All others seems OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34454">issues.joomla.org/tracker/joomla-cms/34454</a>.</sub>

**Comment by brianteeman** [comment]
line 4379? 

what word

**Comment by ChristineWk** [comment]
saw still this: '/media/editors/codemirror/theme/darcula.css'
But I'm going to bed now :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34454">issues.joomla.org/tracker/joomla-cms/34454</a>.</sub>

**Comment by brianteeman** [comment]
your patch is out of date. I removed dracula and darcula

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
