### PR TITLE
[4.0] Drop GMail Plugin from 4.0 new installs

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #18310 .

### Testinstructions

- Install: https://github.com/zero-24/joomla-cms/archive/drop_gmail.zip
- notice there is no gmail plugin anymore.

### Expected result

No GMail Plugin in 4.0 new installs. If needed it can be installed from a joomla-extensions repo.

### Actual result

There is a gmail plugin in the core that is disabled by default + require to enable `allow less secure apps` setting in the google account.

### RFC

Please leave your opinions on this topic below ;)

### CODE REVIEW

**Comment by laoneo** [comment]
Agree, we should get rid of it.

**Comment by zero-24** [comment]
Any more opinions here? I don't want to waste my time in fixing the conflicts where there are already different decisions done. cc @wilsonge ;)

**Comment by wilsonge** [comment]
Go for it. Let's get rid of it

**Comment by Bakual** [comment]
Can we put some message in it for the updating users that says it is unsupported? Eg in the description.

**Comment by Bakual** [comment]
>  If needed it can be installed from a joomla-extensions repo.

Personally, I wouldn't put it in a joomla-extensions repo. That would mean we still have to support it and need to properly "extract" it from core (eg add updateservers) like we did with Weblinks. Just drop it instead.
We should think a bit more about the users who update. Because essentially we leave them with unsupported code in their system. That isn't nice.
for those who have it not enabled, we could actually unistall and delete the plugin automatically. For those who have it active, we should give them a note that they need to find another solution.

**Comment by brianteeman** [comment]
my understanding is that all removed code is being added to the script.php as before but its being done by @wilsonge in batches instead of it being in the pr

**Comment by peteruoi** [comment]
I am not sure what's the reasoning for this decision?
Not many people use it?
Probably but some sure do.
Decoupling? Are we sure we want all plugins the weblinks way?
Maintenance cost? 
I 'd say zero but in any case there will be the same maintenace in the joomla maintenace repo (if someone will look over it...) 
Do we get rid some jquery library cause of it?
Imho the gain of this is that the plugin manager will have one less plugin. 
Is it worth?
I 'm not developer-specialist just a joomla fun and site builder.
There is a tendency to smaller cleaner core and then let the builder go through jet to search for everything but i like when i can do most of the basec thing with core :)

**Comment by brianteeman** [comment]
Sorry i completely missed something when writing my comment
Removing it from new installs will of course mean that it is still present on upgrades as we dont know if it is being used or not. We could add a message or even change the title of the plugin to "unsupported" but then we will be in a situation where there is code installed on the site that is not in the github repo here which will make support/security checks difficult.
So yes Thomas is correct it is not as simple as just removing it from "new" installs

**Comment by dgrammatiko** [comment]
> Do we get rid some jquery library cause of it?

Joomla 4 **will not use jQuery** although the API (`JHtml::_('behavior.jquery');`) will still available for the old timers

**Comment by peteruoi** [comment]
i know this. Maybe i didn't express myself well. 
I meant we are not going to have an advantage such us removing a dependency of something if we drop the gmail plugin.

**Comment by katarinaaas** [comment]
Why are you dropping such handy Gmail plugin? If you are having any issues regarding its use you can ask for help and surely you'll get it.
V 4.0 will look ugly without Gmail plugin.I suggest you contact [Gmail customer support](https://emailsupports.net/ "Gmail custome support")first and then decide whether to remove it or not. Maybe they will make some modifications in it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18322">issues.joomla.org/tracker/joomla-cms/18322</a>.</sub>

**Comment by Bakual** [comment]
> Why are you dropping such handy Gmail plugin? 

Because it is a perfect example of something which should be done by 3rd parties, not core.

**Comment by brianteeman** [comment]
@katarinaaas do you use this plugin?

**Comment by brianteeman** [comment]
Deleted spam comment

**Comment by zero-24** [comment]
Any update on this one @wilsonge ? I have just updated that pr & travis is broken on 4.0 in general 😄

**Comment by laoneo** [comment]
Thanks!!

**Comment by brianteeman** [comment]
:(

**Comment by wilsonge** [comment]
For others reference there’s lots of marketing work going on behind the scenes on this. Expect to see blog posts etc sooner rather than later.

**Comment by brianteeman** [comment]
If people used https://volunteers.joomla.org/reports it would save a lot of comment

**Pull request merged**
