### PR TITLE
[4.0] install string - pre-installation check

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29617
INSTL_WRITABLE="Insufficient permission to create %s"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b73ffddcc3d72bdae89c5fcc474ee2995e63483<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29623">issues.joomla.org/tracker/joomla-cms/29623</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Will the `en-US` be created automatically from the `en-GB` one? Or should the change be made in the `en-US` file, too?

**Comment by brianteeman** [comment]
good point. I need to update that as well in this PR

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 643f55389ada56b4afc989c2e995cc93afa881c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29623">issues.joomla.org/tracker/joomla-cms/29623</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 643f55389ada56b4afc989c2e995cc93afa881c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29623">issues.joomla.org/tracker/joomla-cms/29623</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29623">issues.joomla.org/tracker/joomla-cms/29623</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
