### PR TITLE
[4] Remove unused array - Array is only updated, but never queried

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Remove unused array - Array is only updated, but never queried, thus its just taking up time and memory and can safely be removed

### Testing Instructions

Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
Got response: The file marked for modification does not exist: plugins/sampledata/testing/testing.php
4.0.0-beta5dev (9th October,2020)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31057">issues.joomla.org/tracker/joomla-cms/31057</a>.</sub>

**Comment by PhilETaylor** [comment]
well it certainly does exist :-) 
https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/sampledata/testing/testing.php

**Comment by richard67** [comment]
@ChristineWk The file belongs to testing sample data. Testing sample data is not shipped with installation packages, in opposite to the other kinds of sample data. Testing sample data is only available on a git clone.

**Comment by richard67** [comment]
@PhilETaylor We don't ship the testing sample data with installation packages. I guess @ChristineWk tested on such an environment where ain installation package has bee used once, and not a git clone.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7c77e1b2228710042666e9a34804323d522f2d35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31057">issues.joomla.org/tracker/joomla-cms/31057</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7c77e1b2228710042666e9a34804323d522f2d35<br /><br />Saw the code change OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31057">issues.joomla.org/tracker/joomla-cms/31057</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31057">issues.joomla.org/tracker/joomla-cms/31057</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
