### PR TITLE
move fa-fw to last class to fit convention

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
makes fa-fw final class

### Testing Instructions
apply pr.
inspect admin user dropdown & verify fa-fw is now final class for all icons.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required

none

### CODE REVIEW

**Comment by N6REJ** [comment]
@sandewt

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 477b5f0077c754bcc210731a723e4f84f0bdd050<br /><br />Tested successfully in Beta4-dev of 24 August.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30469">issues.joomla.org/tracker/joomla-cms/30469</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 477b5f0077c754bcc210731a723e4f84f0bdd050<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30469">issues.joomla.org/tracker/joomla-cms/30469</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30469">issues.joomla.org/tracker/joomla-cms/30469</a>.</sub>

**Comment by infograf768** [comment]
Tks!

**Pull request merged**
