### PR TITLE
Make sure we check on the action name

### PR DESCRIPTION
**Pull request by roland-d**
Pull Request for Issue #10552 
#### Summary of Changes

When checking the access status for a given action, we should check on that current active action. This was hardcoded to core.admin so only this action was checked. This change fixes that.
#### Testing Instructions
1. Go to System -> Global Configuration
2. Click on Banners
3. Click on the Permission Tab
4. Click on the Administrator group and see the following permissions:

com_banners_administrator_permission_staging
5. All Calculated settings are set to Allowed (Super User)
6. This is wrong because **Configure Options Only** is not set to allowed anywhere
7. Apply the patch and reload the page
8. Click on the Administrator group and see the following permissions:
com_banners_administrator_permission_patch
9. The **Configure Options Only** is now set to Not Allowed as it should be
#### Known issues

The setting of (Super User) is not correct either but this pull request doesn't fix that. The plan is to propose multiple small pull requests to fix the ACL issues. This way we can keep track of the changes easier.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d7bdbd2c6757b02810d473c83cb4bb4c7d5f8d59<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10731">issues.joomla.org/joomla-cms/10731</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d7bdbd2c6757b02810d473c83cb4bb4c7d5f8d59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10731">issues.joomla.org/joomla-cms/10731</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10731">issues.joomla.org/joomla-cms/10731</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@roland-d i noticed my Super User group permission has now the "Not Allowed" label by default.
This happens in all components.

image

**Comment by roland-d** [comment]
@andrepereiradasilva That is to be expected since we are now checking against the correct action, so the Super User needs to be fixed. I will look into this and post another PR for this case.

**Comment by andrepereiradasilva** [comment]
ok thanks for the feedback

**Pull request merged**
