### PR TITLE
[4.0] Refactor component router of com_finder

### PR DESCRIPTION
**Pull request by Hackwar**
This converts the existing router to the RouterView router. Nothing changes by this in terms of functionality.

I want to thank [cloudaccess.net](https://www.cloudaccess.net/) for supporting these changes. Without their generous help, this wouldn't be possible.

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on d660b620d4ae0af06c72c52030a7c13a48439d7e<br /><br />I tested also when you did on #20185<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20668">issues.joomla.org/tracker/joomla-cms/20668</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on d660b620d4ae0af06c72c52030a7c13a48439d7e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20668">issues.joomla.org/tracker/joomla-cms/20668</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20668">issues.joomla.org/tracker/joomla-cms/20668</a>.</sub>

**Comment by Hackwar** [comment]
Thank you!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
