### PR TITLE
[mod_syndicate] - no need field cache

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23163 .

### Summary of Changes
removed field cache

### Testing Instructions
module works as before

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 07c312efa1c9472a3932aebd6aaaad0606a66a86

@alikon Thanks for this PR too.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23166">issues.joomla.org/tracker/joomla-cms/23166</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 07c312efa1c9472a3932aebd6aaaad0606a66a86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23166">issues.joomla.org/tracker/joomla-cms/23166</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23166">issues.joomla.org/tracker/joomla-cms/23166</a>.</sub>

**Comment by infograf768** [comment]
@alikon 
We need similar PR for mod_languages

**Comment by alikon** [comment]
@infograf768 when you can please test #23174

**Pull request merged**
