### PR TITLE
[4.0] TinyMCE mobile

### PR DESCRIPTION
**Pull request by brianteeman**
This option has not done anything for a long time so it should be removed.

Yoiu can confirm this bt testing the editor AFTER applying the PR and you will see that you get the correct tinymce mobile experience

As shown in the screenshots below

(I will deal with the toggle button in another PR)

image
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on 1aefa3ab727a915203b402635b24e6905968bf8c<br /><br />Tested in Nightly build of 16 January and Android, no change in mobile behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27501">issues.joomla.org/tracker/joomla-cms/27501</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 1aefa3ab727a915203b402635b24e6905968bf8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27501">issues.joomla.org/tracker/joomla-cms/27501</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1aefa3ab727a915203b402635b24e6905968bf8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27501">issues.joomla.org/tracker/joomla-cms/27501</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27501">issues.joomla.org/tracker/joomla-cms/27501</a>.</sub>

**Comment by HLeithner** [comment]
please solve the conflict

**Comment by brianteeman** [comment]
resolved

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks a lot

**Pull request merged**
