### PR TITLE
[4.0] Load Bootstrap JS in some modules

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Loads Bootstrap JS in some modules that use BS dropdowns.

### Testing Instructions

Cause an error in administrator. E.g. modify `administrator/templates/atum/index.php` to have a syntax error.
In Joomla error page click `User Menu` or `Post-Installation Messages` at the top bar.

### Expected result

Dropdown opens.

### Actual result

Nothing happens.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
Wouldnt it be better to remove the bootstrap dropdowns from those pages?

**Comment by SharkyKZ** [comment]
No.

**Comment by wilsonge** [comment]
@brianteeman I'm not too fussed about removing bootstrap from the backend pages. If you want to do a PR though I'm happy to treat it with an open mind. This is more than fine in the short term

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
