### PR TITLE
[4.0] Permissions fixes and improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

- Fix the icon position
- Rewrite some of the jQuery in vanilla JS
- Use `Joomla` namespace for functions

I've kept the jQuery ajax function as it is for now

### Testing Instructions

1. In the backend, go to `Global Configuration` >> `Permissions`
2. Change some of the permissions

### Expected result

- There shouldn't be any whitespace below the dropdowns
- The icon should appear to the right hand side of the dropdown
- The permissions should work the same as before

### CODE REVIEW

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 95ed319a3ea6a53fc72c49bf159dfe10a6928cdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19278">issues.joomla.org/tracker/joomla-cms/19278</a>.</sub>

**Comment by dgrammatiko** [comment]
Can we add 2 todo tasks here:
- create a jLayout for this field
- Make this (the js) a custom element

I already commented on the jQuery.ajax thingy

**Comment by C-Lodder** [comment]
Bare in mind the badge is a completely separate table columns, so whats the plan for the custom element? Wrap the table in it or target the badge outside the element?

Last time I tried moving code from JHtml to a layout, I was told not to do it

**Comment by mbabker** [comment]
> Last time I tried moving code from JHtml to a layout, I was told not to do it

My rule of thumb is this.  Deprecating the corresponding JHtml helper if you're moving stuff to layouts is fine.  Having a JHtml helper whose code is literally this IMO isn't (aside from during the deprecation period):

```php
public static function foo()
{
    echo JLayoutHelper::render('foo');
}
```

Layouts and JHtml have two different override systems and if you're overriding JHtml the odds the right markup (layout) is being produced are slim to none.  So better to leave things so that there is only one way of overriding, not two where one of them may not even be called.

**Comment by dgrammatiko** [comment]
Ok what jhtml code are we talking about here? This is a form field, check the pho file that you’re eding in this pr

**Comment by C-Lodder** [comment]
Merged your commits. Will test tomorrow

**Comment by dgrammatiko** [comment]
@C-Lodder if you got time and into the mood to move this field into JLayouts then this might be a good starting point: https://github.com/joomla/joomla-cms/compare/3.9-dev...dgt41:§3.9-dev-field-rules?expand=1

PS: I postponed the work as I was expecting the tabs CE to be merged, which still is not

**Comment by C-Lodder** [comment]
Not in any mood to do it now. This is all working now anyway

**Comment by dgrammatiko** [comment]
Yes but it's not overridable, Bootstrap hardcoded no matter what!
Anyways I'll do it and promote the js code to CE as this is a Field and all fields should be CE

**Comment by C-Lodder** [comment]
> Yes but it's not overridable

wrong

**Comment by rdeutz** [comment]
@C-Lodder javescript test are failing

**Comment by dgrammatiko** [comment]
> wrong

@C-Lodder so you expect me to write a plugin to override bootstrap mark up?
In that sense everything is overridable in Joomla, but it's not inline with the promise of separated logic and markup.

**Comment by C-Lodder** [comment]
@rdeutz - can you restart drone please?

**Comment by brianteeman** [comment]
Drone restarted

**Comment by rdeutz** [comment]
I already did after your last merge but it doesn't help, still failing

**Comment by C-Lodder** [comment]
@brianteeman and again please :)

**Comment by brianteeman** [comment]
@C-Lodder each time you push something to the repo it starts again on its own afaik

**Comment by C-Lodder** [comment]
@brianteeman Yeah but sometimes it's has a hissy fit and and throws an error

**Comment by brianteeman** [comment]
restarted drone as requested

**Pull request closed without merging**
