### PR TITLE
[4.0] Remove Cache and Checkin Sidebar

### PR DESCRIPTION
**Pull request by brianteeman**
Now that we have the System menu and its grouped links there is no need for the sidebar within com_cache and com_checkin. It was fake that they were connected into one in the first place.

### Screenshots
image

image

### CODE REVIEW

**Comment by Bodge-IT** [comment]
Quick check, while this does as it says and removes the sidebar, it also breaks the language string for the Table Options button, is that a pass or Fail?
screen shot 2019-03-09 at 08 07 40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24030">issues.joomla.org/tracker/joomla-cms/24030</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing Gary but I can't see how any of the changes here would cause that

**Comment by Bodge-IT** [comment]
IKR but reverting patch brings it back.  I noticed in #16909, mention of redundant language strings, could that be related?
Happy to pass this as test objective was fulfilled just wanted to highlight break.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24030">issues.joomla.org/tracker/joomla-cms/24030</a>.</sub>

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on daa473c25f985098e503278bfe3520e05468828e<br /><br />Sidebar removed in System/Clear Cache, system/Clear Expired Cache, system/Global Checkin

Note: Language string on Table Options button breaks on application of patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24030">issues.joomla.org/tracker/joomla-cms/24030</a>.</sub>

**Comment by fabpacheco** [comment]
I have tested this item :white_check_mark: successfully on e8b2cf967e276d1a45ba0f531cb036ec4c3f0707<br /><br />It works and there is no problem with the language string for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24030">issues.joomla.org/tracker/joomla-cms/24030</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
