### PR TITLE
Update .CODEOWNERS after github nick change 

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue # .

### Summary of Changes
Update .CODEOWNERS after github nick change 
### Testing Instructions
code review

### CODE REVIEW

**Comment by wilsonge** [comment]
Always someone who has to change theirs 🙄 thanks!

**Comment by zero-24** [comment]
As he still does not have merge access so it does not matter anyway :)

**Comment by wojsmol** [comment]
@zero-24 This at least ensure that notifications will be send to right person. Without  write permissions he can also review, but this review will not be counted by github.

**Comment by zero-24** [comment]
My point is the following:

> People with admin or owner permissions can set up a CODEOWNERS file in a repository. The people you choose as code owners must have write permissions for the repository.

https://help.github.com/articles/about-codeowners/ As far as i understand that doc no mail and nor request is send out anyway ;)

**Comment by brianteeman** [comment]
Correct

**Comment by wojsmol** [comment]
One way or the other PR is valid because of nick change, permission part is repo admin thing.

**Comment by zero-24** [comment]
Yes.

**Pull request merged**
