### PR TITLE
[4.2] Fix check permission in mod_submenu

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

The check of permissions for the menu items is different between `mod_submenu` (dashboards) and `mod_menu` (main menu).
administrator/modules/mod_submenu/src/Menu/Menu.php#L136 ff.
administrator/modules/mod_menu/src/Menu/CssMenu.php#L333 ff.

### Testing Instructions

Enable workflows in article options:
image

Check the content dashboard with a user with these permissions on com_content:
image

### Actual result BEFORE applying this Pull Request

Categories is only displayed in the main menu (also applies to com_contact, ...)
image

When you click on workflows
image

### Expected result AFTER applying this Pull Request

Categories is displayed in the module of the dashboard
Module containing workflows is not displayed (because no access to `core.manage.workflow` of com_content)
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceciogit** [comment]
I have tested this item :white_check_mark: successfully on 22bb4fca121dc336d7be51523fe79785552af223<br /><br />can replicate the issue, the pull request solved it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39486">issues.joomla.org/tracker/joomla-cms/39486</a>.</sub>

**Comment by carlitorweb** [comment]
I confirm the issue when you click on workflows and the PR fix it. But I have listed here Categories without apply the PR.


Captura

**Comment by heelc29** [comment]
> I confirm the issue when you click on workflows and the PR fix it. But I have listed here Categories without apply the PR.

@carlitorweb Ah, for my test I denied access `core.manage` globally and enabled it only for **com_content**. So without the patch it will try to check the permissions for `com_categories` that don't exist, thus falling back to the global permissions where `core.manage` is allowed.

Ok if you allow it globally you could deny it (`core.manage`) for `com_content` and then open the content dashboard. Here should the link to categories still visible but when you click on it you will get an 403?

image
image

**Comment by carlitorweb** [comment]
> Ok if you allow it globally you could deny it (`core.manage`) for `com_content` and then open the content dashboard. Here should the link to categories still visible but when you click on it you will get an 403?

No, the result is same, not show any relate resources to the content component
Captura

This are the permissions:
Captura

**Comment by heelc29** [comment]
> No, the result is same, not show any relate resources to the content component

@carlitorweb Yes, in the main menu (mod_menu) is correct, but at dashboard (mod_submenu) is not correct. 
image

There are tho test cases:
1. I described in the test instruction (global: denied; content: allowed)
    - Link to Categories is missing at dashboard, although you have access and it is displayed in the (left) main menu
2. You tested now (global: allowed; content: denied)
    - Link to Categories is displayed at dashboard, although you don't have access and it doesn't displayed in the (left) main menu --> 403 Error

image

**Comment by carlitorweb** [comment]
> Yes, in the main menu (mod_menu) is correct, but at dashboard (mod_submenu) is not correct.

This is correct, my fault. Now all is okay.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 22bb4fca121dc336d7be51523fe79785552af223<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39486">issues.joomla.org/tracker/joomla-cms/39486</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39486">issues.joomla.org/tracker/joomla-cms/39486</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
