### PR TITLE
[4.0] Update SASS to 1.42

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Update SASS to 1.42

### Testing Instructions

Clone run `npm install` and check that both the front end and back end templates are intact

### Documentation Changes Required

The Pr https://github.com/joomla/joomla-cms/pull/35648 is actually eliminating the deprecations but this PR will allow the compiler not to throw...

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@thednp could you test this one? Will solve the failing tests on your color picker PR

**Comment by thednp** [comment]
Testing right now. I was thinking I should revert most minicolors deletions to see if I can just get away from the compiler issue.

**Comment by thednp** [comment]
Result: in my local setup, sass v1.42.0 doesn't solve the problem with the color-picker commit, I will now attempt to re-add minicolors back.

**Comment by thednp** [comment]
Speaking about SASS, have you found a way to create an updated `medialize/sass.js` build? Or anything up to date to work in the browser?

**Comment by dgrammatiko** [comment]
> have you found a way to create an updated medialize/sass.js build?

It seems that their tools work fine with latest node-sass: https://github.com/dgrammatiko/sass-worker/tree/master/dist

**Comment by thednp** [comment]
That is so sweet. Thank you

**Comment by wilsonge** [comment]
Even if it doesn't help on that issue it's still a valid dependency update so will merge

**Pull request merged**
