### PR TITLE
[4.0] Fix default prefix for MvcFactory

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This is a propose fix for default $prefix parameter use in MvcFactory in Joomla 4. I know this is an ugly fix but could not find a better solution because we have to keep B/C with legacy MVC.

This needs code review and decision from Joomla 4 team.

### Testing Instructions
1. Install Joomla 4 staging
2. Apply patch
3. Play with com_content and make sure it works (backend)
4. Play with a none namespace component (banners or contacts) and make sure it works

### CODE REVIEW

**Comment by joomdonation** [comment]
I also changed default prefix for Table object, too.  I have to set it to **Table** for legacy factory to keep B/C. I don't understand why the legacy method MVC default it to Table, it makes every model has to override getTable method like this https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_banners/models/banner.php#L282

If it is allowed to break B/C, we should change that default prefix to **ucfirst(substr($option, 4)).'Table'**. If we can do that, even component which use none namespace MVC can remove the method getTable from it's Model classes.

**Comment by franz-wohlkoenig** [comment]
with or -out PR get after "Save"-Article:
bildschirmfoto 2017-04-17 um 09 06 27

**Comment by joomdonation** [comment]
Could you please try to download latest version here https://github.com/joomla/joomla-cms/tree/4.0-dev , then install and test it again? I could not re-procedure this issue

**Comment by franz-wohlkoenig** [comment]
Installed new using https://github.com/joomla/joomla-cms/tree/4.0-dev and Sample Content – same Error is showing after "Save" an Sample-Article.

**Comment by joomdonation** [comment]
@franz-wohlkoenig You are correct. This is a typo (unrelated to this PR) and should be fixed with https://github.com/joomla/joomla-cms/pull/15346

**Comment by franz-wohlkoenig** [comment]
with or -out PR get after created an Tag in Article-View and "Save"-Article:
bildschirmfoto 2017-04-17 um 11 05 57

**Comment by joomdonation** [comment]
@franz-wohlkoenig Could you please open a new issue for that, please? Saving tag error should be a separate PR

**Comment by franz-wohlkoenig** [comment]
done #15347

**Comment by wilsonge** [comment]
Now that is fixed doesit work?

**Comment by franz-wohlkoenig** [comment]
@wilsonge  works, no Error on saving tagged Article.

**Comment by joomdonation** [comment]
@franz-wohlkoenig Could you perform a full test as described in the test instructions? Need to test add/edit/delete/publish/unpublish in both com_content and com_contact

**Comment by franz-wohlkoenig** [comment]
i'm doing a test but struggle on other issues like #15349. 

"add/edit/delete/publish/unpublish" is easier to Test than "Play with com_content and make sure it works".

**Comment by joomdonation** [comment]
I think you can ignore that select user step. Edit an article, save it, if the change is saved, then it works OK

Then try to delete an article, publish an article, unpublish.

Do the same for com_contact. If it works well, then the test is success

Sorry for an unclear test instructions

**Comment by franz-wohlkoenig** [comment]
@joomdonation Article: Changed `Title` and a Word in Fulltext > Title is saved, Fulltext not (using Default-Editor > TinyMCE).

**Comment by joomdonation** [comment]
Look like  related to this issue https://github.com/joomla/joomla-cms/issues/14760 and it is un-related to this PR. Could you try delete/publish/unpublish?

**Comment by franz-wohlkoenig** [comment]
Tests using Sample Sites.

#### Unpublished

- Open Article:
Change Status from `Published` to `Unpublished` is in Dropdown-Field saved, but:
bildschirmfoto 2017-04-17 um 13 13 42
Reopen Article, Status is `Published`.
- List of Articles:
Click on green Symbol/red Symbol work.

#### Delete

- Open Article:
Change Status from `Published` to `Trashed` is in Dropdown-Field saved, but:
bildschirmfoto 2017-04-17 um 13 13 42
Reopen Article, Status is `Published`.
- List of Articles:
Click on "Trash"-Symbol works, also show trashed Items by "Search Tools" and change Status back to published.

**Comment by joomdonation** [comment]
Thanks @franz-wohlkoenig . I guess this issue happens with and without this PR, so if it is possible, please open a separate issue for it

**Comment by franz-wohlkoenig** [comment]
Issue opened: #15350

**Comment by joomdonation** [comment]
Thanks. If you can perform the same test with com_contact, that would be great

**Comment by franz-wohlkoenig** [comment]
Com_contact works on delete/publish/unpublish/archived as expected.

**Comment by joomdonation** [comment]
OK. Thanks.  You can mark the test as success. I will need to ask for code review / decision from Joomla 4 team with this change

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c8c9f5aa798003bcf68cc52e50cfe89ca893f620<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15339">issues.joomla.org/tracker/joomla-cms/15339</a>.</sub>

**Comment by joomdonation** [comment]
Thanks again @franz-wohlkoenig

**Comment by joomdonation** [comment]
@wilsonge Could you have a look at this PR?

**Comment by joomdonation** [comment]
Thanks ;)

**Comment by wilsonge** [comment]
Thankyou :)

**Pull request merged**
