### PR TITLE
[4][Security] Remove Unused Credentials from configuration.php on save

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #31719

### Summary of Changes

When you change your configuration for example

1) When you turn off SMTP with Authentication
2) When you change from SMTP with Authentication to another mail provider
3) When you turn off your outbound proxy 

Joomla RETAINS your credentials in HIDDEN fields in Joomla global configuration and stores them in PLAIN TEXT in /configuration.php - but you don't know this because Joomla hides that fact from you. 

A super admin, who has done one of the above actions is rightly assuming Joomla will discard the credentials as the credential input boxes are no longer shown to them. 

Plus, why should Joomla retain - in plain text - credentials that it no longer needs to operate. This is an additional security issue should the site be compromised. 

### Testing Instructions

1) Enable SMTP with Authentication (you can fake the SMTP server, user and pass that's ok as Joomla doesnt validate them - doh!) and save Joomla Config. Inspect your configuration.php - see the credentials are there - now go back and switch to sendmail and save -  Inspect your configuration.php - see the credentials are still there - now apply the PR and then go and repeat the test - you will see when you inspect configuration.php your secret credentials for SMTP server are no longer stored. 

Same with outbound proxy.

### Actual result BEFORE applying this Pull Request

Joomla stores forever the credentials of services no longer used, in plain text, in configuration.php

### Expected result AFTER applying this Pull Request

Joomla deletes the credentials of services no longer used

### Documentation Changes Required

None. Fully backward compatible.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b1d29ba6c60dbd2d5cdb275107a55c18ee28acdc<br /><br />Tested successfully in 4.1.1-dev of 7 March in Wampserver 3.2.7 with PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37221">issues.joomla.org/tracker/joomla-cms/37221</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b1d29ba6c60dbd2d5cdb275107a55c18ee28acdc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37221">issues.joomla.org/tracker/joomla-cms/37221</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37221">issues.joomla.org/tracker/joomla-cms/37221</a>.</sub>

**Comment by brianteeman** [comment]
Are we sure that this is a good idea?

For example I setup smtp and confirm it is working but decide to check and see if sendmail is a better option. I decide it is not and now i have to find the details for smtp again.

This is a destructive change that is made without any notice to the user.

**Comment by brianteeman** [comment]
> Plain text credentials should not be stored for disabled features. Basic security.

if someone can read that plain text then the smtp details are the least of your problems.

**Comment by PhilETaylor** [comment]
I’m sorry that you do not understand. This PR stands and is valid and correct implementation of basic security principles - for that reason alone it should be merged.

**Comment by brianteeman** [comment]
> This is a destructive change that is made without any notice to the user.

Hint. Tell the user before making a destructive change.

**Comment by PhilETaylor** [comment]
Well feel free to make a PR to give a message. 

However I do not believe a message is needed and Joomla already makes other changes during save that are not communicated and my expectation as a user would be that my password would not be retained if I disabled the feature.

**Comment by brianteeman** [comment]
agree to disagree then. Just like your other pr

**Comment by PhilETaylor** [comment]
No you just love to disagree even when you are simply wrong. Luckily this is not your project and your opinion is only a single voice.

**Pull request closed without merging**
