### PR TITLE
Fix link hover colors and change color theme CSS files order

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue #42679

### Summary of Changes
In the current Cassiopeiatemplate the link hover colors don't work anymore. Also in the Bootstrap overrides of the custom properties in the theme color CSS of Cassiopeia files are ignored due to the loading order of the CSS files. See screenshot below:
image
Also added the --link-hover-color property in line with the --link-color

### Testing Instructions
Checkout this PR and run in console: **npm run build:css** to build the CSS

### Actual result BEFORE applying this Pull Request
Links hover colors don't work and Bootstrap custom properties overrides in the colors_standard.css and colors_alternative.css are rejected

### Expected result AFTER applying this Pull Request
Links hover colors work and Bootstrap custom properties overrides in the colors_standard.css and colors_alternative.css are accepted.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sergejsteinz** [comment]
I have tested this item ✅ successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42794">issues.joomla.org/tracker/joomla-cms/42794</a>.</sub>

**Comment by hans2103** [comment]
Question... at global.scss you can clearly see that a prefix can be set

Scherm­afbeelding 2024-03-06 om 08 39 58

When a prefix is set both link-color and link-hover-color will not work

Scherm­afbeelding 2024-03-06 om 08 40 04


The prefix is missing in de declaration of both link-color and link-hover-color

**Comment by RickR2H** [comment]
@hans2103 I do get is to be fully Bootstrap compliant its better to use the prefixes. At the moment all the custom properties in the Cassiopeia don't have prefixes. Adding prefixes to only the theme CSS files will break the template. Better address this in a separate PR.

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on e0344a0e9f6ae6dfe6cab21e3a924b208ff23a86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42794">issues.joomla.org/tracker/joomla-cms/42794</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42794">issues.joomla.org/tracker/joomla-cms/42794</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
