### PR TITLE
com_installer manage view: searchtools ordering and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_installer manage view.

Also solves a bug where by selecting only the Folder filter the search box hides.
###### Before PR

com_installer-manage-beforepr
###### After PR

com_installer-manage-afterpr
#### How to test
1. Install latest staging and apply this patch
2. Go to Extensions -> Manage -> Manage
3. Check the ordering select box and the filter are working fine.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 48782ff29018a1c43f29abf952dd17ba5c684c91<br /><br />Filter and ordering works fine, the bug with selecting only the Folder filter hides the search box is solved, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9106">issues.joomla.org/joomla-cms/9106</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 48782ff29018a1c43f29abf952dd17ba5c684c91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9106">issues.joomla.org/joomla-cms/9106</a>.</sub>

**Comment by brianteeman** [comment]
RTc thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9106">issues.joomla.org/joomla-cms/9106</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks all!

**Pull request merged**
