### PR TITLE
[4.1] Empty radio / checkbox / list fields

### PR DESCRIPTION
**Pull request by brianteeman**
This PR makes the text for a radio or checkbox or list item required. It is needed for accessibility AND prevents you saving a field with empty radio or checkboxes or list items which are still rendered.

PR for #34337

## Steps to reproduce

Create a field of type checkboxes.
Add one or two text / value pairs with content in text and value
Add another and leave text and value empty.

Repeat for a field of type radio
Repeat for a field of type list

### Before
An empty checkbox or radio or list item is rendered

### After
It is not possible to save the field until the checkbox or radio or list item has a text

### CODE REVIEW

**Comment by AndySDH** [comment]
Thanks.  Same needs to be done for the 'list' field type as well.

**Comment by brianteeman** [comment]
@AndySDH updated as requested

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c679e36b35044be147341223783fa48c91726a5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37138">issues.joomla.org/tracker/joomla-cms/37138</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c679e36b35044be147341223783fa48c91726a5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37138">issues.joomla.org/tracker/joomla-cms/37138</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37138">issues.joomla.org/tracker/joomla-cms/37138</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
