### PR TITLE
[4.0] Fix duplicate language key

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #22410 .

### Summary of Changes
Change Language Key to make them unique

### Testing Instructions
Code inspection

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
language change is ok

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 47d2250d47e7b65122259d0c85521483e65a4f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22416">issues.joomla.org/tracker/joomla-cms/22416</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 47d2250d47e7b65122259d0c85521483e65a4f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22416">issues.joomla.org/tracker/joomla-cms/22416</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22416">issues.joomla.org/tracker/joomla-cms/22416</a>.</sub>

**Comment by laoneo** [comment]
Sorry, wrong button. Thanks for the fix

**Pull request merged**
