### PR TITLE
Correct version numbers

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

Corrects versions numbers after recent merges.
##### How to test

Just check code difference.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good on review

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dadbc8c884941126f887114941955fd40e768919<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9174">issues.joomla.org/joomla-cms/9174</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9174">issues.joomla.org/joomla-cms/9174</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva!

**Pull request merged**
