### PR TITLE
[4.0] Fixed menu params for front page item on installation

### PR DESCRIPTION
**Pull request by Harmageddon**
Pull Request for Issue #32493. Note: This is not an alternative to #32547 - both are necessary. #32547 for fixing the notice and another error, and this PR here for fixing the underlying cause.

### Summary of Changes

The "home" menu item that is created on installation contains parameters from 3.x, and lacks parameters from 4.x. This PR fixes the installation SQL.

### Testing Instructions

IMHO, this could be merged on code review. Testing instructions are a bit more complicated here.

1. Install a clean 4.0-beta7 or nightly.
2. **Important:** Don't edit the "home" menu item!
3. Create 4 articles and set them as featured and published.
4. Look at the home page. The articles should be displayed in a one-column layout.
5. Update using a 4.0-beta7 or nightly update package.
6. Look again at the home page.

Using the prebuilt packages for this PR, do a clean new installation and repeat steps 2-6.

### Actual result BEFORE applying this Pull Request

Before the update, the "home" item displays articles in a one-column layout. After running an update, it displays them in three columns.

### Expected result AFTER applying this Pull Request

Updating should not change the layout.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
@Harmageddon And `installation/sql/postgresql/base.sql` doesn't need a fix? That seems strange to me.

**Comment by Harmageddon** [comment]
@richard67 Of course, you're absolutely right. Thank you!

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 726972d94d4f89e7f70261285e8c703776ff9707<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 726972d94d4f89e7f70261285e8c703776ff9707<br /><br />Tested successfully.

Have also followed up @infograf768 comment on #32525 to help @AndySDH update the relevant parameters in the sample data script to also avoid J3 parameters being included and J4 parameters being missed in what that PR does.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by infograf768** [comment]
`show_associations` should be added as it is a blog/featured parameter (Options).

Screen Shot 2021-03-02 at 11 10 03

**Comment by richard67** [comment]
Back to pending.

@Harmageddon Could you check https://github.com/joomla/joomla-cms/pull/32550#issuecomment-788792966 ? Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by Harmageddon** [comment]
Sorry for the delayed response, I didn't have much time during the week.

Thank you @infograf768 for the suggestion! I added it to both files.

**Comment by ChristineWk** [comment]
(fyi: sandk2)
I have tested this item :white_check_mark: successfully on ffcfc80e41915059dcdfc581467d542abf71b9d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ffcfc80e41915059dcdfc581467d542abf71b9d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32550">issues.joomla.org/tracker/joomla-cms/32550</a>.</sub>

**Pull request merged**
