### PR TITLE
Handle DB errors in user joomla plugin

### PR DESCRIPTION
**Pull request by alikon**
updated  to handle DB errors like #6612 and for #6591

Testing info
simulate a db error 
set the db offline ...

### CODE REVIEW

**Comment by davdebcom** [comment]
@test
Works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6632">issues.joomla.org/joomla-cms/6632</a>.</sub>

**Comment by nonumber** [comment]
@test Success

**Comment by anibalsanchez** [comment]
@test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6632">issues.joomla.org/joomla-cms/6632</a>.</sub>

**Comment by dgt41** [comment]
@test ok

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6632">issues.joomla.org/joomla-cms/6632</a>.</sub>

**Pull request closed without merging**
