### PR TITLE
[4.0] Label menu item title

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
The labels for titles in view menu Item are not correct.

### Testing Instructions
Open a Menu Item new or edit. 

### Actual result BEFORE applying this Pull Request
The label above the title field is "Menu Title"

### Expected result AFTER applying this Pull Request
The label above the title field is " Title", the label in tab Link Type is now "Display Menu Item Title". https://github.com/joomla/joomla-cms/pull/32093#issuecomment-763948538

### CODE REVIEW

**Comment by brianteeman** [comment]
Good spot.

Personally I would just change it to "Title"

Then it matches all the other components and also matches the column heading in the list of all menu items

**Comment by richard67** [comment]
> Personally I would just change it to "Title"

I agree here at this point.

But I've found another text which might have to be changed, too: https://github.com/joomla/joomla-cms/blob/064dd6543c0707490e588c8f9f25e9578cde5d84/administrator/language/en-GB/com_menus.ini#L90

That text is shown here, see the red mark:



The corresponding help text at https://help.joomla.org/proxy?keyref=Help4.x:Menu_Item:_New_Item/en#Link_Type says:

> Add Menu Title: (Yes/No). If the optional image is added, adds the menu title next to the image. Default is 'Yes'.

If I'm not completely wrong, it should be "menu item title" and not "menu title" at this point in both  the language string and the help text.

**Comment by chmst** [comment]
I am not sure with "title".

In Options, the second field is named only "Title" - I don't know which title this is. If this also is the "menu item title", I would prefer to use this consequently.

**Comment by richard67** [comment]
> In Options, the second field is named only "Title" - I don't know which title this is. If this also is the "menu item title", I would prefer to use this consequently.

In a category blog, that's the thing formerly called "Show Title". According to the help https://help.joomla.org/proxy?keyref=Help40:Menu_Item:_Category_Blog&lang=en#Options_Tab : "Whether or not to show the Article's Title.".

**Comment by chmst** [comment]
I have used now Menu Item Title. In this component there are so many titles, that I think this is better.

**Comment by richard67** [comment]
> I have used now Menu Item Title. In this component there are so many titles, that I think this is better.

For the place which I've found that's absolutely right.

But the COM_MENUS_ITEM_FIELD_TITLE_LABEL text could be just "Title", like Brian suggested, so it's consistent with articles, categories, ...

To me it seems that text is only used for that title field where it's ok.

**Comment by infograf768** [comment]
> But the COM_MENUS_ITEM_FIELD_TITLE_LABEL text could be just "Title"

Agree

**Comment by chmst** [comment]
Democracy .. now it is only title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32093">issues.joomla.org/tracker/joomla-cms/32093</a>.</sub>

**Comment by richard67** [comment]
@chmst Now it only needs to adjust the testing instructions to that last change and also extend them by the instructions to check the change before the last one, that one with the other text I had found (you may just link to my comment with the screenshot so testers can find it).

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 26f0d427fb3d8207e5ec26fe83e38cdf8eabf6ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32093">issues.joomla.org/tracker/joomla-cms/32093</a>.</sub>

**Comment by infograf768** [comment]
Needs modifications in Help.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 26f0d427fb3d8207e5ec26fe83e38cdf8eabf6ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32093">issues.joomla.org/tracker/joomla-cms/32093</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32093">issues.joomla.org/tracker/joomla-cms/32093</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
