### PR TITLE
[5.1] Api privacy tests

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the grammar for the description of a privacy test.

simple PR that can be "tested" by code review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 33e0688712d97e85121785562134edbacb3ff663<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42521">issues.joomla.org/tracker/joomla-cms/42521</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 33e0688712d97e85121785562134edbacb3ff663<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42521">issues.joomla.org/tracker/joomla-cms/42521</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42521">issues.joomla.org/tracker/joomla-cms/42521</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Silly question: Why for 5.1-dev? As far as I could see on a quick view, the files are also present on 5.0-dev.

**Comment by brianteeman** [comment]
@richard67 because I have given up working out which version a pr should be against as different maintainers appear to follow different criteria so I am only using the latest branch and the maintainer who merges can decide what to do.

**Comment by LadySolveig** [comment]
Thank you @brianteeman and also to the reviewers @sandewt and @richard67 !

**Pull request merged**
