### PR TITLE
[4.0] Fix validation in menu field

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/28935.

### Summary of Changes

Fixes menu field validation and simplify related code in other modal fields.

### Testing Instructions

> * Create a new menu item (back-end)
> 
> * Select "Menu Item Type": "Menu Item Alias"
> 
> * DO NOT select a "Menu Item"!!
> 
> * Save.

### Expected result

> * It should not be possible to save the menu item

### Actual result

> * One can save the menu item.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 5fb747c50293c323e43769ec138be6300210de22<br /><br />I have just set up for testing and this is my first test - it was at the top of the list. 

Tested with en, fr and de installed. Menu Title and Menu Item both show red when not filled out. Save works correctly when fields are correctly filled out.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28937">issues.joomla.org/tracker/joomla-cms/28937</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5fb747c50293c323e43769ec138be6300210de22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28937">issues.joomla.org/tracker/joomla-cms/28937</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28937">issues.joomla.org/tracker/joomla-cms/28937</a>.</sub>

**Comment by richard67** [comment]
Thanks all.

**Pull request merged**
