### PR TITLE
Pettrify 4.0-dev/administrator/templates/atum/scss/blocks/_alerts.scss

### PR DESCRIPTION
**Pull request by Stuartemk**
Pull Request for Issue # .
https://github.com/Stuartemk/joomla-cms/pull/1
### Summary of Changes
Prettify the css and js files allows a better reading and understanding of the code so you can develop faster and avoid errors.

### CODE REVIEW

**Comment by brianteeman** [comment]
You made this Joomla 4 pull request against the joomla 3 branch

**Comment by richard67** [comment]
@Stuartemk It seems you have selected the wrong target branch (staging instead of 4.0-dev) when making thin PR. I would expect PR authors to check their PR's changes on GitHub and notice such things.

**Comment by Stuartemk** [comment]
Thank you for your responses. It is clear that I made a terrible mistake, and that these PRs are totally wrong, so I close them right now. It was only a single file to modify.
Although the error is so obvious, the answers could also be less aggressive, since for that reason there are almost no contributors, not very tolerant answers take away the desire to contribute.

https://github.com/Stuartemk/joomla-cms/pull/1/files

**Comment by richard67** [comment]
@Stuartemk Where have you seen anything aggressive?

**Pull request closed without merging**
