### PR TITLE
Use pk ci tag map

### PR DESCRIPTION
**Pull request by sovainfo**
Performance improvement by accessing #_contentitem_tag_map via PK.
Instead of using the type_alias it uses the type_id which allows access through PK.

Testinstruction:
Filter on a tag in the backend

### CODE REVIEW

**Comment by wilsonge** [comment]
What's the kind of performance gain here. My worry about this is that many people use these components as a basis for building their own extensions (and yes that's a sign that we need to massively improve our documentation but that's not really the point here). Clearly there they aren't going to know what the primary key is and they should be using this method of searching by the alias (which should be unique) so unless there's some stupid performance gain to be had I'm kind of reluctant to change it to change it to hardcoded primary keys.

**Comment by zero-24** [comment]
Moving to `Information required` until we have a response to @wilsonge's questions :smile: Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6810">issues.joomla.org/joomla-cms/6810</a>.</sub>

**Comment by brianteeman** [comment]
@sovainfo Please can you respond to @wilsonge questions. Otherwise this will be closed automatically in a few weeks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6810">issues.joomla.org/joomla-cms/6810</a>.</sub>

**Comment by Bakual** [comment]
Even if there is a performance gain (which there probably is, but very tiny), from a code perspective this is wrong. The ID should not be hardcoded into the extension. The extension should in fact not care about it at all.
Especially if we're going to decouple those extensions and make them installable again, this would fail because the ID would be different.

Rejecting based on code review.

**Pull request closed without merging**
