### PR TITLE
Fixes #8661 (part 2). Regression: Broken ordering in com_tags

### LINKED ISSUE #8661: Regression - ordering broken in Newsfeed and Tags
Since the change to combine the two ordering selects into a single select (field plus direction) the ordering is completely broken

To test - install latest staging with sample data
Go to newsfeeds and try to sort by ID Ascending or ID Descending. The order should change but it doesnt
Go to tags and try to sort by ID or Title.  The order should change but it doesnt

### PR DESCRIPTION
**Pull request by ghost**
Issue https://github.com/joomla/joomla-cms/issues/8661

To test - install latest staging with sample data
Go to tags and try to sort by ID or Title. The order should change but it doesnt.

Apply patch
Try again

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 30c381a53b1d573a7993f51b5740902293da3e78<br /><br />The sort is fixed but there is now an additional item at the bottom of the list "Status"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Comment by bertmert** [comment]
You were too fast ;-) Fix will come.

**Comment by bertmert** [comment]
Please test again. Thanks!

**Comment by bertmert** [comment]
**ANOTHER ISSUE WITH column ORDEERING! PLEASE WAIT** Gnaah!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c478f9dc00d24921bd480d65ca0b3888ae20570e<br /><br />All good now - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Comment by bertmert** [comment]
Did you test also column ordering? At the moment I have troubles to find an easy fix.

**Comment by brianteeman** [comment]
I dont see any problem

On 13 December 2015 at 14:21, bertmert <notifications@github.com> wrote:

> Did you test also column ordering? At the moment I have troubles to find
> an easy fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8672#issuecomment-164262908>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on c478f9dc00d24921bd480d65ca0b3888ae20570e<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Comment by bertmert** [comment]
One can not order by headline. Easy to fix.
But then you cannot sort items by moving rows up and down.

**Comment by brianteeman** [comment]
I can not confirm that

On 13 December 2015 at 15:02, bertmert <notifications@github.com> wrote:

> One can not order by headline. Easy to fix.
> But then you cannot sort items by moving rows up and down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8672#issuecomment-164266930>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
> I can not confirm that

It was an issue with column ORDERING that used a.ordering instead of a.lft in PHP.
And a lower- uppercase issue concerning order direction. Under some circumstances one couldn't move lines because of "ASC" versus "asc".

**Comment by bertmert** [comment]
PR is ready for testing now. Sorry for the inconvenience caused.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 48bdab5e04e7dfe2264160281e9147a3db6df4e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 48bdab5e04e7dfe2264160281e9147a3db6df4e8<br /><br />Perfect!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8672">issues.joomla.org/joomla-cms/8672</a>.</sub>

**Pull request merged**
