### PR TITLE
Guided Tours: Fix for Toggle Inline Help and Help buttons (Creating a step)

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Partial solution for https://github.com/joomla/joomla-cms/issues/40260.

1. Go to the Guided Tours component,
2. Go to the page with steps for any tour,
3. Create a step,

Please note that there are no buttons **Toggle Inline Help** and **Help** in the toolbar on the right.
Apply PR and repeat the test - the buttons are now in place.

Because of the bracket, we have a duplicate of the buttons - **Close** and **Cancel**. ~~The Cancel button has been removed because in tours we use Close.~~ Fixed for dependency: Cancel on Create and Close on Edit (in tours and steps).

### Actual result BEFORE applying this Pull Request

Screenshot_1

### Expected result AFTER applying this Pull Request

Screenshot_2

### CODE REVIEW

**Comment by brianteeman** [comment]
> Because of the bracket, we have a duplicate of the buttons - Close and Cancel. The Cancel button has been removed because in tours we use Close.


This should be conditional on the state. ie if its a new step then it it cancel. if it is an edit step then its a close

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 8dacc3acd64d24910d415ce49a4508d26c1a27c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40288">issues.joomla.org/tracker/joomla-cms/40288</a>.</sub>

**Comment by Kostelano** [comment]
Maybe. But firstly, it is also implemented when creating / editing a tour. Secondly, there are a lot of places in the system that contradict the way you wrote. Third, as you would (probably) write - this is outside the scope of this PR.

**Comment by Kostelano** [comment]
> This should be conditional on the state. ie if its a new step then it it cancel. if it is an edit step then its a close

@brianteeman Can't sleep. Corrected

**Comment by brianteeman** [comment]
The last change looks better - can't test right now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5f6d2561fce0a8b69e505de02ceb0b336b5d103e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40288">issues.joomla.org/tracker/joomla-cms/40288</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40288">issues.joomla.org/tracker/joomla-cms/40288</a>.</sub>

**Comment by obuisard** [comment]
Kanstantin @Kostelano can you check the files on your end, there are not passing the drone because of end of line errors. Thanks!

**Comment by Kostelano** [comment]
@obuisard there seems to be no more problems with the CS

**Comment by obuisard** [comment]
Thanks for the fix Konstantin @Kostelano

**Pull request merged**
