### PR TITLE
[4.3] Fix deprecated message in categories when extension is empty

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .
 
### Summary of Changes
PHP 8.1 - Direct aceess to categories needs the parameter extension. Missing param throws a deprecated message.

### Testing Instructions
Use the direct link administrator/index.php?option=com_categories in your application.
If no extension is given, the system uses com_content as default. 

### Actual result BEFORE applying this Pull Request
Deprecated message

### Expected result AFTER applying this Pull Request
No deprecated message.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChrisHoefliger** [comment]
I have tested this item :white_check_mark: successfully on 35a36e437fe612361fe1b291f4770000611c64ff<br /><br />Successfully tested on Joomla 4.3.4 @localhost PBF 2023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40604">issues.joomla.org/tracker/joomla-cms/40604</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 35a36e437fe612361fe1b291f4770000611c64ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40604">issues.joomla.org/tracker/joomla-cms/40604</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40604">issues.joomla.org/tracker/joomla-cms/40604</a>.</sub>

**Comment by formfranska** [comment]
I have tested this item :white_check_mark: successfully on 35a36e437fe612361fe1b291f4770000611c64ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40604">issues.joomla.org/tracker/joomla-cms/40604</a>.</sub>

**Comment by obuisard** [comment]
Thank you Christiane @chmst!

**Pull request merged**
