### PR TITLE
[4.0] Composer update

### LINKED ISSUE #31564: [4.0][plugin] blog sample data  error in stemmer
### Steps to reproduce the issue
click on install  Blog Sample Data 

### Expected result
sample blog data created

### Actual result
image

### System information (as much as possible)

php 8

### PR DESCRIPTION
**Pull request by brianteeman**
Resolves #31564

### Summary
Package operations: 0 installs, 57 updates, 0 removals
  - Updating dealerdirect/phpcodesniffer-composer-installer (v0.7.0 => v0.7.1): Downloading (100%)
  - Updating joomla/archive (2.0.0-beta => 2.0.0-beta2): Loading from cache
  - Updating algo26-matthias/idna-convert (v3.0.4 => v3.0.5): Loading from cache
  - Updating phpmailer/phpmailer (v6.1.8 => v6.2.0): Loading from cache
  - Updating symfony/var-dumper (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/error-handler (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/options-resolver (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/ldap (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/web-link (v5.1.8 => v5.2.1): Loading from cache
  - Updating symfony/yaml (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating typo3/phar-stream-wrapper (v3.1.5 => v3.1.6): Downloading (100%)
  - Updating voku/portable-ascii (1.5.3 => 1.5.6): Downloading (100%)
  - Updating voku/portable-utf8 (5.4.47 => 5.4.51): Downloading (100%)
  - Updating wamania/php-stemmer (v2.1 => v2.1.1): Downloading (100%)
  - Updating maximebf/debugbar (v1.16.3 => v1.16.4): Downloading (100%)
  - Updating nyholm/psr7 (1.3.1 => 1.3.2): Downloading (100%)
  - Updating spomky-labs/base64url (v2.0.3 => v2.0.4): Downloading (100%)
  - Updating sebastian/type (1.1.3 => 1.1.4): Downloading (100%)
  - Updating sebastian/resource-operations (2.0.1 => 2.0.2): Downloading (100%)
  - Updating sebastian/recursion-context (3.0.0 => 3.0.1): Downloading (100%)
  - Updating sebastian/object-reflector (1.1.1 => 1.1.2): Downloading (100%)
  - Updating sebastian/object-enumerator (3.0.3 => 3.0.4): Downloading (100%)
  - Updating sebastian/global-state (3.0.0 => 3.0.1): Downloading (100%)
  - Updating sebastian/exporter (3.1.2 => 3.1.3): Downloading (100%)
  - Updating sebastian/environment (4.2.3 => 4.2.4): Downloading (100%)
  - Updating sebastian/diff (3.0.2 => 3.0.3): Downloading (100%)
  - Updating sebastian/comparator (3.0.2 => 3.0.3): Downloading (100%)
  - Updating phpunit/php-timer (2.1.2 => 2.1.3): Loading from cache
  - Updating phpunit/php-file-iterator (2.0.2 => 2.0.3): Loading from cache
  - Updating sebastian/code-unit-reverse-lookup (1.0.1 => 1.0.2): Downloading (100%)
  - Updating phpunit/php-token-stream (3.1.1 => 3.1.2): Loading from cache
  - Updating phpunit/php-code-coverage (7.0.10 => 7.0.14): Loading from cache
  - Updating doctrine/instantiator (1.3.1 => 1.4.0): Downloading (100%)
  - Updating phpspec/prophecy (1.12.1 => 1.12.2): Downloading (100%)
  - Updating phar-io/version (2.0.1 => 3.0.4): Downloading (100%)
  - Updating phar-io/manifest (1.0.3 => 2.0.1): Downloading (100%)
  - Updating myclabs/deep-copy (1.10.1 => 1.10.2): Downloading (100%)
  - Updating phpunit/phpunit (8.5.9 => 8.5.13): Downloading (100%)
  - Updating symfony/stopwatch (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/process (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/finder (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/filesystem (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/event-dispatcher (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/string (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/console (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating composer/xdebug-handler (1.4.4 => 1.4.5): Downloading (100%)
  - Updating composer/semver (3.2.2 => 3.2.4): Downloading (100%)
  - Updating friendsofphp/php-cs-fixer (v2.16.7 => v2.17.2): Downloading (100%)
  - Updating symfony/css-selector (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating codeception/codeception (4.1.9 => 4.1.12): Downloading (100%)
  - Updating softcreatr/jsonpath (0.5.0 => 0.7.2): Loading from cache
  - Updating codeception/module-rest (1.2.5 => 1.2.7): Loading from cache
  - Updating php-webdriver/webdriver (1.8.3 => 1.9.0): Downloading (100%)
  - Updating codeception/module-webdriver (1.1.3 => 1.1.4): Downloading (100%)
  - Updating symfony/dom-crawler (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating symfony/browser-kit (v5.1.8 => v5.2.1): Downloading (100%)
  - Updating joomla-projects/joomla-browser v4.0.0.x-dev (d5a1e28 => 679c0ce):

### CODE REVIEW

**Review by rdeutz — APPROVED** [review]

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on ab038491072695bc686b71d923a562f8d1697686<br /><br />Working now for several hours after applying this patch and tried to use many different features, especially in backend configuration. But surely not everything.
I am locally on win10 with xampp (php 7.4 and php8), so no real E-mail function or massmail tested, also no url-rewrite.   <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31732">issues.joomla.org/tracker/joomla-cms/31732</a>.</sub>

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on ab038491072695bc686b71d923a562f8d1697686<br /><br />Tested successfully.

cPanel installation. Typically nothing should break in updating composer packages I would imagine. Nothing tested when the patch has been applied has had issues.

However in testing the aspects @chmst mentioned she couldn't, there may be an unrelated issue with sending system email and mass mails - an "Empty Message Body" appears for both. Testing further, as the issue exists without the patch applied too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31732">issues.joomla.org/tracker/joomla-cms/31732</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
