### PR TITLE
[4.0] JS codestyle

### PR DESCRIPTION
**Pull request by Hackwar**
This should fix the codestyle error Drone is complaining about.

### CODE REVIEW

**Comment by joomdonation** [comment]
The current javascript code in com_joomlaupdate is completely broken. So we can merge this PR now to solve cs issue and try to fix the real js error later.

**Comment by richard67** [comment]
My attempt to fix it was #33487 . I can re-open it if preferred by the release lead.

**Comment by richard67** [comment]
Another attempt see #33488 .

**Comment by HLeithner** [comment]
Merging this and hope that #33488 is ready soon.

Thanks

**Pull request merged**
