### PR TITLE
[4.0] component missing in menu

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #34192

Create a new admin menu and use the help preset

### Before
image

### After
image

Note for testing you will need to create a new menu for the before and after

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 6e4c0555c1b4961e5e42e6cafd2f4db100ac93b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34704">issues.joomla.org/tracker/joomla-cms/34704</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 6e4c0555c1b4961e5e42e6cafd2f4db100ac93b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34704">issues.joomla.org/tracker/joomla-cms/34704</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanka

**Pull request merged**
