### PR TITLE
[com_fields] Move the after title event to the correct position

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #13332.

### Summary of Changes
Moves the after title content event output to the right position.

### Testing Instructions
- Create a custom field and set the option to "Automatic Display" to after title
image

### Expected result
The field is shown after the title.

### Actual result
The field is shown before the description.

### CODE REVIEW

**Comment by ggppdk** [comment]
Currently, HTML of the events: 
-- **onContentAfterTitle** with an  **IF !show-intro**  condition
-- **onContentBeforeDisplay**
are displayed on the same place, one after the other

So both changes '**onContentAfterTitle**' seem right
-- remove the **IF !show-intro** (and show HTML of  **onContentAfterTitle** events always)
-- move it directly after title **inside page-header box**

But

----

1.. About **IF !show-intro** 
-- It is a B/C break ? ... things will start appearing in some sites that were not shown before

----

2.. About **moving HTML of  onContentAfterTitle events inside "page header"** ?

Yes, if some uses onContentAfterTitle, instead of onContentBeforeDisplay,
... then he really means to place it inside the page-header

-- But it is a (smaller) B/C break too, the page header is supposed to contain title and little / less / small stuff like the date and until now it did not contain "onContentAfterTitle"

----

I say both changes are correct, but it should have been like this from the beggining, now they may have unwanted side-effects to existing site ...

**Comment by Bakual** [comment]
> It is a B/C break ? ... things will start appearing in some sites that were not shown before

Layouts aren't covered by the B/C promise. See https://developer.joomla.org/cms/development-strategy.html#backward_compatibility
> 6.1.7 Rendered markup
> For the time being, rendered markup is not subject to our backwards compatibility promise. We will try not to change markup in such a way that a site might render differently, but we can't promise not to break anything at the present time.

>  things will start appearing in some sites that were not shown before

To my knowledge there is no core code that is run in the onContentAfterTitle event. That's probably why nobody noticed this bug yet. So if somethign shows up nw it is coming froma  3rd party plugin and most likely didn't behave as expected before.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 871c67f3a9ef7261ad7de520c1c6b29cda28dda4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13345">issues.joomla.org/tracker/joomla-cms/13345</a>.</sub>

**Comment by laoneo** [comment]
One questiin I have, should it be inside or outside the div?

**Comment by ralain** [comment]
Outside. IMO if it's not a part of the title it shouldn't be in the page-header div.

**Comment by laoneo** [comment]
Moved the output outside of the page header

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 1543eea9481f3d118b78e40a0d6166c9eb4f8cfa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13345">issues.joomla.org/tracker/joomla-cms/13345</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 1543eea9481f3d118b78e40a0d6166c9eb4f8cfa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13345">issues.joomla.org/tracker/joomla-cms/13345</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13345">issues.joomla.org/tracker/joomla-cms/13345</a>.</sub>

**Pull request merged**
