### PR TITLE
[5.2][Events] Use event classes for Finder plugins

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Update `finder` plugins to use `SubscriberInterface` and an event classes.

### Testing Instructions

Run finder indexer, edit the content. 
Check the indexer works, and changed content also indexed.

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 2912da3bb95b1dc08c211b5aa8b289746334d6c6<br /><br />I tested this successfully.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43607">issues.joomla.org/tracker/joomla-cms/43607</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 2912da3bb95b1dc08c211b5aa8b289746334d6c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43607">issues.joomla.org/tracker/joomla-cms/43607</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43607">issues.joomla.org/tracker/joomla-cms/43607</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @Fedik!

**Pull request merged**
