### PR TITLE
#15420 fixed new/edit field cancel button issue, having error page on click of cancel button

### PR DESCRIPTION
**Pull request by RonakParmar**
fixed new/edit field cancel button issue, having error page on click of cancel button

Pull Request for Issue #15420 .

### Testing Instructions
Goto Administrator->content->fields->new and click on cancel button.

### Expected result
Redirected to fields listing page.

### Actual result
Having error page.

### CODE REVIEW

**Comment by brianteeman** [comment]
This is correct but isnt it the result of the branch not being upto date @wilsonge @mbabker

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c17ecc5b072fdbb48760a48ce4929959b6cc5f1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15422">issues.joomla.org/tracker/joomla-cms/15422</a>.</sub>

**Comment by wilsonge** [comment]
Umm we've updated since then. So I guess somehow it's got lost in a conflict :/ bit worrying tbh

**Comment by brianteeman** [comment]
That was why I mentioned it @Wilson wonder what else is wrong

**Pull request merged**
