### PR TITLE
fix failure in language files

### PR DESCRIPTION
**Pull request by astridx**
Same as here: https://github.com/joomla/joomla-cms/pull/13544

### Summary of Changes
Remove slash

### CODE REVIEW

**Comment by Bakual** [comment]
Noticed @rbuelund so this should not come back again.

**Comment by infograf768** [comment]
@Bakual
this is wrong. There should not be any doubel quotes after the space
It should be
`JLIB_FORM_FIELD_INVALID="Ugyldigt felt:&#160"`

**Comment by rdeutz** [comment]
I fixed it

**Comment by astridx** [comment]
Ui, sorry. For me the important thing was, that the syntax is Ok and the file will be loaded. That is why I did not look deep enough :(

**Comment by rbuelund** [comment]
Sorry about that.. don't know what happened there. I will fix it at Crowdin.

**Pull request merged**
