### PR TITLE
[4.0] Update TinyMCE to v4.7.0

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Changelog

- [Added] new mobile ui that is specifically designed for mobile devices.
- Updated the default skin to be more modern and white since white is preferred by most implementations.
- Restructured the default menus to be more similar to common office suites like Google Docs.
- [Fixed] so theme can be set to false on both inline and iframe editor modes.
- [Fixed] bug where inline editor would add/remove the visualblocks css multiple times.
- [Fixed] bug where selection wouldn't be properly restored when editor lost focus and commands where invoked.
- [Fixed] bug where toc plugin would generate id:s for headers even though a toc wasn't inserted into the content.
- [Fixed] bug where is wasn't possible to drag/drop contents within the editor if paste_data_images where set to true.
- [Fixed] bug where getParam and close in WindowManager would get the first opened window instead of the last opened window.
- [Fixed] bug where delete would delete between cells inside a table in Firefox.

### CODE REVIEW

**Comment by wilsonge** [comment]
What's the deal with this mobile UI. Is this going to be used by default? And if so how does it affect us?

**Comment by C-Lodder** [comment]
@wilsonge - https://go.tinymce.com/blog/tinymce-is-going-mobile/

They have basically created a mobile specific experience, making it much easier and friendly for users. Visit the following on your mobile: https://www.tinymce.com/mobile/

**Comment by dgrammatiko** [comment]
@C-Lodder can you paste a screenshot? I like to see how the new theme blends with the current template

**Comment by C-Lodder** [comment]
mobile

**Comment by dgrammatiko** [comment]
OK, where are the joomla buttons?

**Comment by C-Lodder** [comment]
That was from the TinyMCE site. The Joomla one doesn't utilise the mobile theme yet. Something the UX team can decide on

**Comment by dgrammatiko** [comment]
@C-Lodder actually I was asking for a screenshot of the white skin:
> Updated the default skin to be more modern and white since white is preferred by most implementations.

**Comment by C-Lodder** [comment]
tiny

**Pull request closed without merging**
