### PR TITLE
[4.0] Accessibility Highlight Links Inconsistent

### PR DESCRIPTION
**Pull request by mangeshmane**
Pull Request for Issue #29292

### Summary of Changes

Removed unwanted class

### Testing Instructions

Steps to reproduce the issue
Login to admin and set "highlight links" in your Accessibility Settings to yes.
Click Save.
Note that there is a red box around all three icons at top

### Actual result BEFORE applying this Pull Request

83340240-903af600-a2cd-11ea-9d2a-52fcd78398ed

### Expected result AFTER applying this Pull Request

83340208-50740e80-a2cd-11ea-8f9a-460450f46cc1

### CODE REVIEW

**Comment by jaisheela** [comment]
I have tested this item :white_check_mark: successfully on 00400b3e8dd46161f45945b7b5505d57d0724a0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31333">issues.joomla.org/tracker/joomla-cms/31333</a>.</sub>

**Comment by shinderohanoffical** [comment]
I have tested this item :white_check_mark: successfully on 00400b3e8dd46161f45945b7b5505d57d0724a0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31333">issues.joomla.org/tracker/joomla-cms/31333</a>.</sub>

**Comment by adj9** [comment]
If I apply the PR I can't find the flag to activate. I wanted to try it even though there are 2 confirmations...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31333">issues.joomla.org/tracker/joomla-cms/31333</a>.</sub>

**Comment by manojLondhe** [comment]
> If I apply the PR I can't find the flag to activate. I wanted to try it even though there are 2 confirmations...

Go to admin users list, click on user you are logged in backend, edit that user to enable **highlight links** @adj9

**Comment by richard67** [comment]
The "Private Messages" has indeed changed from a dropdown toggle to a link. I think it had been done with PR #25296 . So this PR here correctly removes that "dropdown-toggle" class, and this makes the accessibility tool mark it as a link. I've just done a test.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
