### PR TITLE
fix a bug when truncate splits within a tag

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #11934 .

### Summary of Changes
Check if the cut is within a tag

### Testing Instructions
see #11934 or #12612

### CODE REVIEW

**Comment by mbabker** [comment]
I think there was a reason the `truncateComplex` method was added and `truncate` wasn't made this "smart".  But considering how long ago that was, don't ask me why anymore.

**Comment by rdeutz** [comment]
whatever it is a bug, I think the first time I have found it was 5 years ago.

**Comment by mbabker** [comment]
I'm just going to go with "meh, whatever, fix it".  I tried to find where that was added and all I came up with was a couple of wordy and not really helpful PRs.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on acb901d37038dedb33a3583c6511ee49010c33ea<br /><br />Works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14907">issues.joomla.org/tracker/joomla-cms/14907</a>.</sub>

**Comment by zero-24** [comment]
Before the patch
screen shot 2017-03-29 at 13 11 09

after the patch
screen shot 2017-03-29 at 13 10 48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14907">issues.joomla.org/tracker/joomla-cms/14907</a>.</sub>

**Comment by laoneo** [comment]
When I add the following unit test data

```
'HTML allowed, split allowed' => array(
	'<div class="test"><p>whatever it is a bug.</p></div>',
	20,
	true,
	true,
	'<div class="test"><p>whatever</p></div>...',
),
```
then it fails. As soon as I remove the ` class="test"` code from the div then it works.

**Comment by rdeutz** [comment]
```HTML

<div class="test"><p>whatever it is a bug.</p></div>
1234567890123456789012345678901234567890123456789012
0000000001111111111222222222233333333334444444444555
...................|
<div class="test"><
<div class="test">
<div class="test"></div>
```
Your split is within the "&lt;p&gt;" Tag, then the "<" will be removed and the div will be closed. So my guess is that your Test result should be 

```HTML
<div class="test"></div>...
```

Haven't tested it

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by laoneo** [comment]
I have tested this item :red_circle: unsuccessfully on acb901d37038dedb33a3583c6511ee49010c33ea<br /><br />Please see my previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14907">issues.joomla.org/tracker/joomla-cms/14907</a>.</sub>

**Comment by laoneo** [comment]
@rdeutz when I remove `class="test"` from the unit test data, then it shows `<div><p>whatever</p></div>...`. As far as I understood it, the class attribute should not be counted, or should it?

**Comment by franz-wohlkoenig** [comment]
@laoneo remove RTC?

**Comment by laoneo** [comment]
I would remove it, if Robert thinks my unit test data is invalid and it works as expected, then we can set it back to RTC. But for me it is not fixed for now.

**Comment by rdeutz** [comment]
ups pressed the wrong button

**Comment by laoneo** [comment]
ok, then try this data
```
'HTML allowed, split allowed' => array(
	'<div class="test"><p>whatever it is a bug.</p></div>',
	25,
	true,
	true,
	'<div class="test"><p>what</p></div>...',
),
```
it should show `<div class="test"><p>what</p></div>...` or as it gets splited after 25 charachters?

**Comment by rdeutz** [comment]
it gets split and then open tags getting closed, so should be something you wrote, not 100% sure if it is "wha", "what" or "whate"

**Comment by laoneo** [comment]
Unit test does look
image

**Comment by rdeutz** [comment]
ok, I will look into it, does it work without the patch?

**Comment by laoneo** [comment]
same result without the patch

**Comment by rdeutz** [comment]
ok, then it is another bug. Can you open an issue for the new bug?

**Comment by laoneo** [comment]
I guess it will be then the same as #11934, just with another unit test data.

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on acb901d37038dedb33a3583c6511ee49010c33ea<br /><br />Thanks @rdeutz 
Nice work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14907">issues.joomla.org/tracker/joomla-cms/14907</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14907">issues.joomla.org/tracker/joomla-cms/14907</a>.</sub>

**Comment by zero-24** [comment]
@rdeutz @laoneo do you want to move this to another issue or should this PR be expanded?

As it works for the case @degobbis and me had.

**Comment by rdeutz** [comment]
lets merge this one to get one problem solved, I looked into it a bit more and I've found some other issues but because it is unit tested I can work on it later.

**Comment by laoneo** [comment]
I will open a new issue for my other unit test.

**Pull request merged**
