### PR TITLE
[com_users] user groups: use the same visual level structure as categories

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR does for user groups, the same visual change in the tree structure as done:
- for categories https://github.com/joomla/joomla-cms/pull/10213
- for tags https://github.com/joomla/joomla-cms/pull/10526

After PR
image
#### Testing Instructions
1. Use latest staging
2. Apply patch
3. Go to Users -> Groups and check the tree structure visual
4. Go to Users -> Manage, create/edit a user, and in "Assigned User Groups" check the tree structure visual
5. Go to Users ->Access Levels, create/edit a access level, and in "User Groups Having Viewing Access" check the tree structure visual.

Note: in this PR, the HTML the tree structure prefix was moved to a layout file so it can be easily overrided or changed across all tree structures.
After (and if) this PR is merged will update tags and categories to also use the layout.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 4c56cdc188fe9749dd32690a1d4b83f83080dff4<br /><br />thanks :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10528">issues.joomla.org/joomla-cms/10528</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4c56cdc188fe9749dd32690a1d4b83f83080dff4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10528">issues.joomla.org/joomla-cms/10528</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 4c56cdc188fe9749dd32690a1d4b83f83080dff4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10528">issues.joomla.org/joomla-cms/10528</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10528">issues.joomla.org/joomla-cms/10528</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva!

**Pull request merged**
