### PR TITLE
[4.0] featured articles update

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the tooltip size difference reported in #33876 and various codestyle issues

To test - code review AND check the tip sizes

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on aff6437787b26fa9eced4400165703c4de42b1ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33894">issues.joomla.org/tracker/joomla-cms/33894</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aff6437787b26fa9eced4400165703c4de42b1ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33894">issues.joomla.org/tracker/joomla-cms/33894</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33894">issues.joomla.org/tracker/joomla-cms/33894</a>.</sub>

**Comment by richard67** [comment]
@brianteeman System tests report an error in step `Test that it is possible to create a new articles using "new" toolbar button.`. The screenshot of the page shows a syntax error.

ContentListCest ArticleCRUD mysql fail

Could you check that?

**Comment by brianteeman** [comment]
must have happened when i tried to resolve merge conflicts - I must get better at that. Will check and fix now

**Comment by brianteeman** [comment]
creating a replacement

**Comment by richard67** [comment]
Yes, sometimes that's by far easier.

**Comment by brianteeman** [comment]
see #33927

**Comment by chmst** [comment]
Closing as replaced by #33927<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33894">issues.joomla.org/tracker/joomla-cms/33894</a>.</sub>

**Comment by brianteeman** [comment]
weird comment it was closed 3 days ago

image

**Comment by chmst** [comment]
It was stil active in the isse tracker as RTC. Sometimes the synchronization between github and tracker fails.

**Pull request closed without merging**
