### PR TITLE
[Improvement] Creating an All Menu dropdown in menu manager

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/6912

This PR implements the All Menus dropdown.
After patch you will get (captures from a multilngual site to show the associations column):

===> Choice for all menu items in Menus
screen shot 2015-11-13 at 09 54 45

===>New dropdown to display all menu items from all menus
screen shot 2015-11-13 at 09 56 33

===>Ordering by menu type ascendant or descendant
screen shot 2015-11-13 at 09 59 10

===>Search among all menu items:
screen shot 2015-11-13 at 10 00 05

===> usual display when a specific menu is chosen
screen shot 2015-11-13 at 09 57 54

Thank you for testing and improving if judged necessary

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for trying

Unfortunately for me this creates a very complicated UI.
1. When you have a single menu selected then that menu is displayed at the
top in the select next to the search. there is no indicator that you are
displaying all the menu items
2. If you try to drag and drop a menu item it looks like you can actually
use this to move a menu item from one menu to another but you cant
3. The only way to select ALL is from the top menu. I would have expected
to have been able to do this from the Menu select

On 13 November 2015 at 09:06, infograf768 <notifications@github.com> wrote:

> See #6912 <https://github.com/joomla/joomla-cms/issues/6912>
>
> This PR implements the All Menus dropdown.
> After patch you will get (captures from a multilngual site to show the
> associations column):
>
> ===> Choice for all menu items in Menus
> [image: screen shot 2015-11-13 at 09 54 45]
> <https://cloud.githubusercontent.com/assets/869724/11142331/c1537536-89ec-11e5-8261-e097824c79f8.png>
>
> ===>New dropdown to display all menu items from all menus
> [image: screen shot 2015-11-13 at 09 56 33]
> <https://cloud.githubusercontent.com/assets/869724/11142342/e50dde62-89ec-11e5-8b9e-b671d6a0dff1.png>
>
> ===>Ordering by menu type ascendant or descendant
> [image: screen shot 2015-11-13 at 09 59 10]
> <https://cloud.githubusercontent.com/assets/869724/11142396/3fbceff6-89ed-11e5-95bd-cb2a29086b2b.png>
>
> ===>Search among all menu items:
> [image: screen shot 2015-11-13 at 10 00 05]
> <https://cloud.githubusercontent.com/assets/869724/11142416/604f0bdc-89ed-11e5-9274-2a9ab7bd16a3.png>
>
> ===> usual display when a specific menu is chosen
> [image: screen shot 2015-11-13 at 09 57 54]
> <https://cloud.githubusercontent.com/assets/869724/11142362/0f7e9dbc-89ed-11e5-9fb8-a81ae22bad88.png>
>
> Thank you for testing and improving if judged necessary
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/8411
> Commit Summary
>
>    - Creating an All Menu dropdown
>
> File Changes
>
>    - *M* administrator/components/com_menus/models/forms/filter_items.xml
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-0> (6)
>    - *M* administrator/components/com_menus/models/items.php
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-1> (30)
>    - *M* administrator/components/com_menus/views/items/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-2> (6)
>    - *M* administrator/language/en-GB/en-GB.com_menus.ini
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-3> (4)
>    - *M* administrator/language/en-GB/en-GB.mod_menu.ini
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-4> (1)
>    - *M* administrator/modules/mod_menu/tmpl/default_enabled.php
>    <https://github.com/joomla/joomla-cms/pull/8411/files#diff-5> (4)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/8411.patch
>    - https://github.com/joomla/joomla-cms/pull/8411.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8411>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
>1. When you have a single menu selected then that menu is displayed at the top in the select next to the search. there is no indicator that you are displaying all the menu items

The behaviour in that case is exactly as it was. What is wrong with that? The manager is filtering the menu items for that single menu. If you want to seach in all menus then you have to change the selector to -Select Menu-

>3. The only way to select ALL is from the top menu. I would have expected to have been able to do this from the Menu select.
Not sure I understand what you mean. Can you explain?

>2. If you try to drag and drop a menu item it looks like you can actually use this to move a menu item from one menu to another but you cant
I did not look at that aspect, yes, it needs improvement

**Comment by brianteeman** [comment]
On 13 November 2015 at 09:50, infograf768 <notifications@github.com> wrote:

>
>    1. When you have a single menu selected then that menu is displayed at
>    the top in the select next to the search. there is no indicator that you
>    are displaying all the menu items
>
> The behaviour in that case is exactly as it was. What is wrong with that?
> The manager is filtering the menu items for that single menu. If you want
> to seach in all menus then you have to change the selector to -Select Menu-
>
Not quite as it was. Before you could always see in the select which menu
was being displayed. Now there is no visual indicator that you are
displaying all menu items.  BUT I guess I understand you as this would be
the behaviour used in the article manager with the category filter. Just
seems odd to me. I guess if it was really to be consistent with the other
lists then there would be no top level menu items for the menus and the
menu select would be inside the search div

**Comment by infograf768** [comment]
Took off order by drag and drop when menu items for all menus are displayed.

**Comment by infograf768** [comment]
Prevent displaying New and batch when menu items for All menus are displayed.
Interface will now look like this in this case:
screen shot 2015-11-13 at 12 38 04

**Comment by brianteeman** [comment]
Sorry but the hypocrisy of this latest change really makes me laugh. You
have always objected whenever anyone wanted to make a toolbar button
invisible when it shouldnt be used and insisted that it must be either
completely visible or at least visible and greyed out and now you have made
a toolbar button invisible.
I dont see the logic of removing the NEW button either

On 13 November 2015 at 11:39, infograf768 <notifications@github.com> wrote:

> Prevent displaying New and batch when menu items for All menus are
> displayed.
> Interface will now look like this in this case:
> [image: screen shot 2015-11-13 at 12 38 04]
> <https://cloud.githubusercontent.com/assets/869724/11145205/7a37a8f4-8a03-11e5-91e3-7664a5307313.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8411#issuecomment-156404579>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
>Sorry but the hypocrisy of this latest change really makes me laugh.

Measure your words... They are unwanted for.
I just thought that when we see all menu items, these could create issues.
Greyed indeed would be better.

As I said above: improvements welcome.

**Comment by infograf768** [comment]
Reinstated the New and Batch buttons.

Now, when the manager is set on Select Menu and clicking New, we will get an Edit screen where The Menu Location is also set To Select a Menu. Therefore one has to choose a Menu to save the new Menu Item.

screen shot 2015-11-14 at 17 48 49

Concerning the batch button, it will display the pop up with a message, preventing using Batch when the Menu is not set in the Menu Items Manager.

screen shot 2015-11-14 at 17 50 54

**Comment by brianteeman** [comment]
Why is the batch disabled

**Comment by infograf768** [comment]
Because one can't know for sure what will happen when choosing menu items from different menus and move or copy them to another menu that may be a menu to which belongs one of the menu items selected.
Another aspect would be the various parameters of these selected menu items (language, access) that could/would have to be normalised in that case and, if not, may also create confusion.
Another problem is also the hierarchy of the items selected.

I do agree though that it would be nice to pick many menu items and copy or move them to a new menu.
But I feel it would be prone to too many possible errors.

**Comment by sural98** [comment]
I input a word in the search box to filter through all menus.
The filter worked fine but the search box came empty after that filter is applied.
The search box should preserve the filtered term.

**Comment by infograf768** [comment]
@sural98
I can't reproduce your issue using staging.
screen shot 2016-01-19 at 11 41 13

**Comment by sural98** [comment]
@infograf768 It was MS Edge I had this issue.

**Comment by sural98** [comment]
@infograf768 This time I can't reproduce. I don't know why?
In short it is working.

**Comment by infograf768** [comment]
@sural98
Can you mark the test as successfull in https://issues.joomla.org/tracker/joomla-cms/8411 ?

**Comment by sural98** [comment]
I have tested this item :white_check_mark: successfully on 74b65c61f4e80d37c38b5453a491d025d452fba2<br /><br />Tested in Joomla 3.4.8 installation on Wampserver 64b for Windows 10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 74b65c61f4e80d37c38b5453a491d025d452fba2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on 74b65c61f4e80d37c38b5453a491d025d452fba2<br /><br />I like this PR very much!! So helpful!

Reason for "unsuccessfully" is that it's still possible to drag and drop entries and I needed some time to understand that "ordering is just a fake" ;-)

I think these lines (4 to 6) would help to get rid of this behavior in ..../items/tmpl/default.php
```
// move line upwards
$menuType = (array) $app->getUserState('com_menus.items.menutype');

// add !empty() to suppress loading of sortablelist.js
if ($saveOrder && !empty($menuType))
{
 $saveOrderingUrl = 'index.php?option=com_menus&task=items.saveOrderAjax&tmpl=component';
 JHtml::_('sortablelist.sortable', 'itemList', 'adminForm', strtolower($listDirn), $saveOrderingUrl, false, true);
}

```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by bertmert** [comment]
> it's still possible to drag and drop entries

...when "Ordering ascending"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by bertmert** [comment]
@infograf768 Could you please see my PR that I've sent to your branch concerning drag&drop.
https://github.com/infograf768/joomla-cms/issues/27

**Comment by infograf768** [comment]
Thanks @bertmert

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 29a6281c553db9be4bb2bb73ce4448dbcc45191c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 29a6281c553db9be4bb2bb73ce4448dbcc45191c<br /><br />I am marking this as a successful test

Perhaps if #9227 is accepted as well then it will address my only other concern with this that there is no real indicator that you have "all menu items" selected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks everyone<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8411">issues.joomla.org/joomla-cms/8411</a>.</sub>

**Comment by infograf768** [comment]
When/if this is accepted, I will update #9227 before merge.

@wilsonge 
shall i combine both PR and can you fix a milestone for these?

**Comment by wilsonge** [comment]
If this is accepted it will be for 3.6. I have merged #9227 though - so just update this PR :)

**Comment by infograf768** [comment]
I am closing this one in favour of https://github.com/joomla/joomla-cms/pull/9231

Thank you for testing there.

**Pull request closed without merging**
