### PR TITLE
Update Shop link to https

### PR DESCRIPTION
**Pull request by brianteeman**
This PR updates the link to the shop from the Help menu to use https

### CODE REVIEW

**Comment by mbabker** [comment]
I'd suggest holding off on this until an admin fixes the mixed content issues with the bookstore links (over half the navigation on the site).

```
Mixed Content: The page at 'https://shop.joomla.org/amazoncom-bookstores.html' was loaded over HTTPS, but requested an insecure resource 'http://astore.amazon.com/joo-20'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by brianteeman** [comment]
Thats a 30 second easy fix and it needs to be done. This change should
force some actual activity from the site admins

On 12 December 2015 at 16:30, Michael Babker <notifications@github.com>
wrote:

> I'd suggest holding off on this until an admin fixes the mixed content
> issues with the bookstore links (over half the navigation on the site).
>
> Mixed Content: The page at 'https://shop.joomla.org/amazoncom-bookstores.html' was loaded over HTTPS, but requested an insecure resource 'http://astore.amazon.com/joo-20'. This request has been blocked; the content must be served over HTTPS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8653#issuecomment-164165672>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 6e401a7b0a5f2a183ea2e565cf3e99e4799d6125<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8653">issues.joomla.org/joomla-cms/8653</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 6e401a7b0a5f2a183ea2e565cf3e99e4799d6125<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8653">issues.joomla.org/joomla-cms/8653</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as the web site maintainers of the shop site are asleep on the job nd show no signs of fixing the site

**Comment by brianteeman** [comment]
Re-opened as the shop site has now been switched to https

**Comment by wilsonge** [comment]
Merged on review

**Pull request merged**
