### PR TITLE
[4.0] btn-sm toolbar buttons

### PR DESCRIPTION
**Pull request by brianteeman**
Removes the last remaining uses of btn-sm on any toolbar button

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 030e965e30f91a6ca36a0c6321b98198958d12db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29395">issues.joomla.org/tracker/joomla-cms/29395</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 030e965e30f91a6ca36a0c6321b98198958d12db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29395">issues.joomla.org/tracker/joomla-cms/29395</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29395">issues.joomla.org/tracker/joomla-cms/29395</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
