### PR TITLE
[4.0] Edit not enable

### PR DESCRIPTION
**Pull request by brianteeman**
The options do not disable/enable Fields or workflows - they just display/hide the menu options to disable/enable their creation/editing

### Before
chrome_2018-08-26_23-14-20

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7f8e7974fe1dea52a76f181caff438a59d066c5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21856">issues.joomla.org/tracker/joomla-cms/21856</a>.</sub>

**Comment by ghost** [comment]
Marked as "Easy Test".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21856">issues.joomla.org/tracker/joomla-cms/21856</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 7f8e7974fe1dea52a76f181caff438a59d066c5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21856">issues.joomla.org/tracker/joomla-cms/21856</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21856">issues.joomla.org/tracker/joomla-cms/21856</a>.</sub>

**Comment by laoneo** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
