### PR TITLE
Fix: Article Manager: Articles:: Usability issue, Can we rename the column name for better usability?

### PR DESCRIPTION
**Pull request by zero-24**
see: https://github.com/joomla/joomla-cms/issues/5597

> -Go to article list view and check the date column.
> -Is it really meaningful?
> -Refer screenshot please and read the text written over the screenshot!
> 
> screen shot 2015-01-03 at 03 17 58

### CODE REVIEW

**Comment by zero-24** [comment]
@brianteeman Is `Creation Date` ok?

**Comment by aasimali** [comment]
You're welcome @zero-24 and Thank you for pull request.

Have an awesome day.

**Comment by infograf768** [comment]
if necessary, can't we use:
`COM_CONTENT_FIELD_CREATED_LABEL="Created Date"`

This would avoid adding a new string.

**Comment by zero-24** [comment]
done @infograf768

**Comment by brianteeman** [comment]
Personally I dont think this change is correct. I can see why you are
making the change but sometimes we have to compromise for the sake of a
clean UI. Making this into two words (in english)  breaks the flow of the
UI for minimal advantage. If it really must be changed (I don't think it
does) then you could perhaps do it in the tooltip

**Comment by brianteeman** [comment]
Also please check in Hathor. Making this change makes this column heading go to two rows which is not consistent with the rest of the UI<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5598">issues.joomla.org/joomla-cms/5598</a>.</sub>

**Comment by zero-24** [comment]
closing. as per comment by @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5598">issues.joomla.org/joomla-cms/5598</a>.</sub>

**Pull request closed without merging**
