### PR TITLE
[4.0] [com_templates] Admin template does not need Preview message

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says. Missing
`COM_TEMPLATES_TEMPLATE_NO_PREVIEW_ADMIN="No preview available for Administrator templates."`

EDIT: Instead of adding the string, modifying tmpl to not display it.

### Testing Instructions
Display admin templates

### Before patch
Screen Shot 2019-05-06 at 08 33 12

### After patch
Screen Shot 2019-05-07 at 07 56 11

### CODE REVIEW

**Comment by Quy** [comment]
It was removed in PR #24440. How about not displaying the string, thus no need to add the string?

**Comment by infograf768** [comment]
> It was removed in PR #24440. How about not displaying the string, thus no need to add the string?

Fine for me.

**Comment by infograf768** [comment]
@Quy Done.
Screen Shot 2019-05-07 at 07 56 11

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 529b49428189ec5ab963c33258691c7cbdc40b10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24811">issues.joomla.org/tracker/joomla-cms/24811</a>.</sub>

**Comment by infograf768** [comment]
@chmst

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 65b3cb6c842ae0eba6f73a5e96ebaa0e16887f7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24811">issues.joomla.org/tracker/joomla-cms/24811</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24811">issues.joomla.org/tracker/joomla-cms/24811</a>.</sub>

**Comment by ghost** [comment]
~~@infograf768 can this be set on RTC or aretest by @Quy is needed?~~

**Comment by Quy** [comment]
No changes since my test so it is good to go.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
