### PR TITLE
Fix TinyMCE wrong JS field name

### PR DESCRIPTION
**Pull request by mvanvu**
Pull Request for Issue #27809.

### Testing Instructions
Please see at https://github.com/joomla/joomla-cms/issues/27809#issuecomment-584795035

### Expected result
This PR should be fixed for this issue #27809

### CODE REVIEW

**Comment by Fedik** [comment]
Be careful with changing **name** stuff for tinymce plugin, it changes the behavior, and make b.c. break.
It also breaks the feature #11157 #10996 (especially if editor in a subform).

**Comment by mvanvu** [comment]
@Fedik I have tested with subform by the article subform field and it still works the same before. Just show here some conflicts you saw.

**Comment by Fedik** [comment]
if you run test from  #11157 it will not work anymore, it changes names

**Comment by mvanvu** [comment]
@Fedik Yes, the name has been changed or the issue #27809 will not resolve. I think the custom plugin that overrides the JS options should be updated the name. In other way, if the #11157 is already in the J! CORE, OK just close this and remember #27809 is an immortal issue :( .

**Comment by zero-24** [comment]
As the mentiond PR has been merged into 3.7 i will close here as requested.

**Pull request closed without merging**
