### PR TITLE
[html5] System administrator template

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This is a redo of https://github.com/joomla/joomla-cms/pull/9842 for **system admin** only.

This PR does a basic conversion of **system admin** template to HTML5.
Also made some minor corrections:
- Use scriptVersion for template js in all files
- Use the API in inline css/js (except error page)
- Use ie9 or lower html5.js in all files.
#### Testing Instructions
- Install patch
- Add the following code to force the system template in the frontend (before https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/administrator.php#L185) 

``` php
 $this->template = new stdClass;
 $this->template->template = 'system';
 $this->template->params   = new Registry;
```
- Go to admin and check if the the following pages are working properly (they don't have style):
  - normal/component (test any existent page)
  - error pages (test one non existent URL)
- Remove the code added in 2. and check all is again ok  and with style.

Check also the code changes.
#### Observations

All pages should now start with this code:

``` html
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">
<head>
[...]
    <meta charset="utf-8" />
[...]
```

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :red_circle: unsuccessfully on bebe3dc49a84f12aa9fa7f6366725f79d9da3be4<br /><br />After adding below code before JPATH_ROOT . /libraries/cms/application/administrator.php line number 185 my site is not working.

$this->template = new stdClass;
$this->template->template = 'system';
$this->template->params   = new Registry;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10638">issues.joomla.org/joomla-cms/10638</a>.</sub>

**Comment by RonakParmar** [comment]
I have applied this PR and added above code in given path file and line number.
Here is the screen-shots of my site before PR apply and after PR and above code applied.
First screen-shot is before PR apply. 

screen shot 2016-07-08 at 06 52 51
Second screen-shot is after PR applied and code added.
screen shot 2016-07-08 at 06 52 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10638">issues.joomla.org/joomla-cms/10638</a>.</sub>

**Comment by mbabker** [comment]
Again, intended result.  To properly test this, you HAVE to first apply the code hack to force the system template, then make a request so the system template displays pre-patch, then apply the patch and make another request.  You can't compare pre-patch with a 100% unpatched install against post-patch with a code hack in place.  Otherwise based on the steps you're presumably taking there is no way to ever test this patch successfully because it will appear as though the styling has gone AWOL.

**Comment by andrepereiradasilva** [comment]
@RonakParmar  the `code` in the test instructions is exactly to force the system template (you can't select the system template in templates so we need to do this).

so for me it seems your test (first print screen) is a success.

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on bebe3dc49a84f12aa9fa7f6366725f79d9da3be4<br /><br />Without adding the given code to given file path PR works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10638">issues.joomla.org/joomla-cms/10638</a>.</sub>

**Comment by AnishaVora** [comment]
I have tested this item :white_check_mark: successfully on bebe3dc49a84f12aa9fa7f6366725f79d9da3be4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10638">issues.joomla.org/joomla-cms/10638</a>.</sub>

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10638">issues.joomla.org/joomla-cms/10638</a>.</sub>

**Comment by wilsonge** [comment]
Can you rebase this please?

**Comment by andrepereiradasilva** [comment]
fixed conflicts @wilsonge 
i don't have a clue why github added the he-IL.ini in this PR is not changed and i didn't do anything there.
probably a github glitch.

**Comment by wilsonge** [comment]
Line endings?

**Comment by wilsonge** [comment]
Good job!

**Comment by andrepereiradasilva** [comment]
ok it's that thanks, strange this file must have an issue added to revert line endings to unix format in this particular file.

Is ok now

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/133e4b6e232a5303b9f20eed83cc151cf728a4de

**Pull request closed without merging**
