### PR TITLE
[4.0] missing upper case table

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

just a typo

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 61af2c1a26b83af94da789f6f1a24dcfced91be2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31131">issues.joomla.org/tracker/joomla-cms/31131</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 61af2c1a26b83af94da789f6f1a24dcfced91be2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31131">issues.joomla.org/tracker/joomla-cms/31131</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31131">issues.joomla.org/tracker/joomla-cms/31131</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
