### PR TITLE
[4.0] Add opening/closing p tag

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix markup by adding opening/closing `p` tag.

### Testing Instructions
Code review.
or
Go to Global Configuration > Text Filters
View page source under `Filter Type`.

### CODE REVIEW

**Comment by brianteeman** [comment]
markup in language strings should be avoided

**Comment by Quy** [comment]
There is already markup in the string. This PR fixes invalid markup.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b6e9ab309d18ce05e58c55e37d4094f682108583<br /><br />Adds opening p to balance already present closing p. Quick fix until someone tackles better markup in strings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34846">issues.joomla.org/tracker/joomla-cms/34846</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on b6e9ab309d18ce05e58c55e37d4094f682108583<br /><br />Markup is now conform<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34846">issues.joomla.org/tracker/joomla-cms/34846</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34846">issues.joomla.org/tracker/joomla-cms/34846</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
