### PR TITLE
[4.4] update badges for node/npm in readme file

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #41699 .

### Summary of Changes

update badges in README file after node update

### Testing Instructions

check README file

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5a770f9023cde66592cd3f173fe32d156535a17b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41716">issues.joomla.org/tracker/joomla-cms/41716</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5a770f9023cde66592cd3f173fe32d156535a17b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41716">issues.joomla.org/tracker/joomla-cms/41716</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41716">issues.joomla.org/tracker/joomla-cms/41716</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
