### PR TITLE
[4.0] 3 plugins do not load the 'modal_article' type

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says.
This concerns 3 plugins:
confirmconsent
privacyconsent
terms

### Testing Instructions
Edit these plugins.
The Select article field displays a textarea instead of the modal select

### After patch
Example for terms:

Screen Shot 2019-06-02 at 08 36 39

### Note
There are other remaining use of `addfieldpath=` which will need to be corrected.

Can be merged on review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c1cea24d1b263e4ef55e0d4d3c2f5128ff8c69ea<br /><br />Can be merged by review ... but can also be successfully tested with the Patchtester :tongue: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25083">issues.joomla.org/tracker/joomla-cms/25083</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c1cea24d1b263e4ef55e0d4d3c2f5128ff8c69ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25083">issues.joomla.org/tracker/joomla-cms/25083</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25083">issues.joomla.org/tracker/joomla-cms/25083</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
