### PR TITLE
[4.0] Bump Bootstrap to 4.5.0 and jQuery to 3.5

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Bumps versions of bootstrap and jQuery

### Testing Instructions
Navigate around a bit and check the UI isn't horrifically broken anywhere

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 84003a162cdb82cba5aaa9e7b145573108b8c35e<br /><br />Checked in both regular and debug mode
Checked the changelogs for both scripts

Everything seems ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29222">issues.joomla.org/tracker/joomla-cms/29222</a>.</sub>

**Comment by C-Lodder** [comment]
You can also bump `jquery-migrate` to `3.3.0`

**Comment by wilsonge** [comment]
Yeah good shout - updated jQuery migrate too to cover the jQuery bump

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 78a70069af108e6cb60802d204c0c952cf81001d<br /><br />Checked an UI looks normal after applying. No errors found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29222">issues.joomla.org/tracker/joomla-cms/29222</a>.</sub>

**Comment by wilsonge** [comment]
Merging so we can find any small things sooner rather than later then. Thanks!

**Pull request merged**
