### PR TITLE
Remove colon from labels - com_users

### PR DESCRIPTION
**Pull request by cyrez**
Remove all colons ":" at the end of labels, for consistency with all form field labels, and to improve rendering of client-side form validation (no ":" for label in the Field invalid : %s)

### CODE REVIEW

**Comment by Bloggerschmidt** [comment]
tested. it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6424">issues.joomla.org/joomla-cms/6424</a>.</sub>

**Comment by brianteeman** [comment]
Why only in com_users

We use a : throughout the core 

If we want to make this change then we should be consistent and make the change throughout

**Comment by JoomliC** [comment]
<pre>If we want to make this change then we should be consistent and make the change throughout</pre>

I didn't find another place where labels have colon... but i may miss something...

**Comment by designbengel** [comment]
Tested in Frontend on Edit Profile, all fine! - anywhere else?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6424">issues.joomla.org/joomla-cms/6424</a>.</sub>

**Comment by brianteeman** [comment]
> I didn't find another place where labels have colon... but i may miss something...

com_banners
com_content
com_finder
com_languages
com_menus
com_users
and probably a lot more <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6424">issues.joomla.org/joomla-cms/6424</a>.</sub>

**Comment by JoomliC** [comment]
@brianteeman i don't mean all colons, but colons in form field labels.

For example, in com_banners, colon in label are only in Hathor overrides, and in tracks export (with the calendar field below the label, so could be kept in this case).

The purpose with this PR, is the removal of colon in inline form fields.
For example, no admin form have ":" for label.
And in frontend, contact form has no label.
Another example, about registration form, if you enable the captcha plugin, you won't have colon for captcha label, but you will for all other fields.

I never mean to remove all the colon, it would be non-sense. But only for inline label related to form fields.
And it fixes the "stupid" alert message when invalid field => "Field invalid : Name :"
Isn't better with only this : "Field invalid : Name" ?

Don't know if i'm clear...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6424">issues.joomla.org/joomla-cms/6424</a>.</sub>

**Comment by brianteeman** [comment]
COM_BANNERS_BEGIN_LABEL="Begin Date:"
COM_BANNERS_END_LABEL="End Date:"


Quick examples

On 14 March 2015 at 20:19, Cyril Rezé <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> i don't mean all colons,
> but colons in form field labels.
>
> For example, in com_banners, colon in label are only in Hathor overrides,
> and in tracks export (with the calendar field below the label, so could be
> kept in this case).
>
> The purpose with this PR, is the removal of colon in inline form fields.
> For example, no admin form have ":" for label.
> And in frontend, contact form has no label.
> Another example, about registration form, if you enable the captcha
> plugin, you won't have colon for captcha label, but you will for all other
> fields.
>
> I never mean to remove all the colon, it would be non-sense. But only for
> inline label related to form fields.
> And it fixes the "stupid" alert message when invalid field => "Field
> invalid : Name :"
> Isn't better with only this : "Field invalid : Name" ?
>
> Don't know if i'm clear...
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6424
> <http://issues.joomla.org/tracker/joomla-cms/6424>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6424#issuecomment-80701488>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by JoomliC** [comment]
@brianteeman your examples in com_banners are for "Filters" labels, not form field label.

capture d ecran 2015-03-15 a 16 47 31
There, it's not really a problem, as no form validation.

ADMIN com_contact form (available for all admin forms as far as i know...) : 
capture d ecran 2015-03-15 a 16 42 04
No : in labels, and so, no : in Field invalid alert message if field required invalid.

FRONTEND com_contact form : 
capture d ecran 2015-03-15 a 16 44 49
Form fields labels have no : , and alert message is ok

FRONTEND com_users forms (example with edit profil, where there's an issue with consistency and alert message for required field) : 
capture d ecran 2015-03-15 a 16 45 50 copie
There, 2 issues : 
- no consistency of labels, Edit Your Profile with : and Basic Settings with no : in labels...
- issue with alert message

I hope it's better with images than with my poor English ;-)

Cyril

**Comment by brianteeman** [comment]
Ah. Now I understand the issue better. The problem isnt just a cosmetic one
of it looking better without the : in the label it is really about
re!moving the : from the error messagea

**Comment by JoomliC** [comment]
@brianteeman Yes! It's not a cosmetic one. ;-)

And i found only in com_users frontend the use of colon in form fields.

**Comment by zero-24** [comment]
RTC Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6424">issues.joomla.org/joomla-cms/6424</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
