### PR TITLE
Table bind() improperly binds fields

### PR DESCRIPTION
**Pull request by eeshaanSA**
Pull Request for Issue #37956 

### Summary of Changes
Made the changes as suggested by @aforgh. Please checkout the issue #37956. All necessary information, required code, changes made, and their effects have been mentioned neatly there. 

### Actual result BEFORE applying this Pull Request

Checkout Property remains set to 1.

### Expected result AFTER applying this Pull Request

Checkout property is set to null.

### Documentation Changes Required

--

### CODE REVIEW

**Comment by eeshaanSA** [comment]
I only made the changes suggested by the owner of this issue, @aforgh. Please let me know if there anything else to this issue, except the changes made above.

**Comment by chmst** [comment]
The first error messag is : Save failed with the following error: Column 'level' cannot be null. I don't see how this is related to this PR. Maybe @richard67 can help?

**Comment by richard67** [comment]
> The first error messag is : Save failed with the following error: Column 'level' cannot be null. I don't see how this is related to this PR. Maybe @richard67 can help?

I think that error is related because now with this change any array element of the dev array which has a null value will be used, regardless if that column allows null values or not.

@eeshaanSA i don’t think it is a good idea to make a pull request with a change suggested by someone else without really understanding that change.

**Comment by roland-d** [comment]
@eeshaanSA Thank you for your pull request but I am sorry this cannot be used. This is a change in behavior of how the function works and is not backwards compatible. Such a change can only be done in a major release if we want this change. This is the reason I am closing the PR.

**Comment by eeshaanSA** [comment]
> > The first error messag is : Save failed with the following error: Column 'level' cannot be null. I don't see how this is related to this PR. Maybe @richard67 can help?
> 
> 
> 
> I think that error is related because now with this change any array element of the dev array which has a null value will be used, regardless if that column allows null values or not.
> 
> 
> 
> @eeshaanSA i don’t think it is a good idea to make a pull request with a change suggested by someone else without really understanding that change.

Sorry. Will take care from now onwards.

**Pull request closed without merging**
