### PR TITLE
JFilterInput more === and !== cases

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue add more === and !== cases to JfilterInput

### Summary of Changes
- more === and !== cases
- make a few conditionals multiline

### Testing Instructions
code review / unit tests pass

### Expected result
unit tests pass

### Actual result
unit tests pass

### Documentation Changes Required
none

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on ed6ef2691158f504f7ae0bf4d3363c2caae4fbba<br /><br />Done code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15817">issues.joomla.org/tracker/joomla-cms/15817</a>.</sub>

**Comment by PhilETaylor** [comment]
> Expected result = unit tests pass

Are there any Unit tests that specifically fail if this PR is not applied? You should create some tests that fail on == but pass on === for it to be a valid test...

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on ed6ef2691158f504f7ae0bf4d3363c2caae4fbba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15817">issues.joomla.org/tracker/joomla-cms/15817</a>.</sub>

**Comment by photodude** [comment]
@PhilETaylor none of the current unit test should fail with this. I'm not sure if there is a good way to write a unit test for this change (I'm not sure if it would even be possible). 

Generally, this PR just removes some internal php type juggling on some checks. Following the general php coding practice to always preference `===` or `==!` in checks (with some exceptions where type juggling should be allowed then use `==` and `!=`).

**Comment by photodude** [comment]
related PR in the framework https://github.com/joomla-framework/filter/pull/23

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
