### PR TITLE
Utilize hint attribute in JFormFieldList

### PR DESCRIPTION
**Pull request by izharaazmi**
### Summary of Changes

Currently we ignore the hint attribute for List type form field. This PR is to utilize it if provided to add placeholder (as well as data-palceholder for chosen and select2) attributes to the rendered input control.
### Testing Instructions

Create a form field for type list using xml in any component, provide the hint attribute as we do for text type fields. The hint should be visible when no options are selected on the UI.

``` xml
        <field
            name="test_list"
            type="list"
            multiple="true"
            hint="Test Hint for multiple"
        />
        <field
            name="test_list_single"
            type="list"
            hint="Test Hint for single"
        />
```

Without this PR, the hint was ignored.

Also test with chosen, select2.
### Documentation Changes Required

We need to add the information about this attribute (hint) being available in `list` field also.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 4265d18b0d32cb18d7f2767a8862192a369489e0<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12447">issues.joomla.org/tracker/joomla-cms/12447</a>.</sub>

**Comment by izharaazmi** [comment]
Omg. 😸  Thats not just a conflict. The affected method was abstracted. What do I do @zero-24 ?

**Comment by zero-24** [comment]
@izharaazmi what about implementing it into https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/abstractlist.php ? or do i miss something?

**Comment by izharaazmi** [comment]
@zero-24 Yeah right, I was just thinking whether it calls for a new PR. I have applied the changes to the new abstract class method. Please test.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on e394f8fbf169ba60950dc1b28be5bc68625cd431<br /><br />still works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12447">issues.joomla.org/tracker/joomla-cms/12447</a>.</sub>

**Comment by Bakual** [comment]
I have tested this item :red_circle: unsuccessfully on e394f8fbf169ba60950dc1b28be5bc68625cd431<br /><br />Placeholder isn't a valid attribute for selects, radios and checboxes to my knowledge. That's why it isn't supported.

Also I see no hint in a HTML select when I add it to a list field (tested with Chrome). In chosen "selects" I can make it appear, but I need to add a stupid empty option to it which then allows the clear the selected value. Only then I will see the hint.

I honestly don't see the point of adding something which isn't supported by the HTML spec.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12447">issues.joomla.org/tracker/joomla-cms/12447</a>.</sub>

**Comment by ggppdk** [comment]
>Placeholder isn't a valid attribute for selects, radios and checboxes 

Exactly **placeholder** is invalid HTML and should be removed **and only keep data-placeholder="..."**

and then this HTML will be valid
```php
 $attr .= strlen($hint) ? ' placeholder="' . $hint . '" data-placeholder="' . $hint . '"' : ''; 
```

data-placeholder, is needed by chosen JS (and select2 JS) to show their typing prompt in
- select-multiple case

**Comment by anibalsanchez** [comment]
I have tested this item :red_circle: unsuccessfully on e394f8fbf169ba60950dc1b28be5bc68625cd431<br /><br />After this change is applied, when you try to edit an article this notice appears: JGLOBAL_USE_GLOBAL_VALUE_NOT_FOUND<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12447">issues.joomla.org/tracker/joomla-cms/12447</a>.</sub>

**Comment by ggppdk** [comment]
The hint needs to be escaped by using JText::_(..., true) or use  json_encode() to when appending it
and also the placeholder=...  must be used !
- it is not valid HTML
- it is not needed since choosen JS can use data-placeholder=...

**Comment by Gavakshi** [comment]
@izharaazmi please review this

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
can a Maintainer please look whats next with this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12447">issues.joomla.org/tracker/joomla-cms/12447</a>.</sub>

**Comment by roland-d** [comment]
Closing this as there has been no response. @izharaazmi feel free to reopen this once you have implemented the feedback given. Thank you.

**Pull request closed without merging**
