### PR TITLE
[4.0] Fix wrong status of custom field enable switcher in com_contact

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Fix the wrong color of the custom field enabler switcher in com_contact options

### Testing Instructions
Go to the Integration-tab in the com_contact configuration.

### Expected result
grafik

### Actual result
grafik

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eeb2125f36e7f1477dac572fd07533a03bdebc33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23339">issues.joomla.org/tracker/joomla-cms/23339</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on eeb2125f36e7f1477dac572fd07533a03bdebc33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23339">issues.joomla.org/tracker/joomla-cms/23339</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23339">issues.joomla.org/tracker/joomla-cms/23339</a>.</sub>

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on eeb2125f36e7f1477dac572fd07533a03bdebc33<br /><br />on Joomla! 4.0.0-alpha7-dev

OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23339">issues.joomla.org/tracker/joomla-cms/23339</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
