### PR TITLE
link not being closed correctly

### PR DESCRIPTION
**Pull request by peterlose**
In users helper in com_users a link it's closed properly.
## Before patch

skaermbillede 2015-02-13 kl 22 41 45
## After patch

skaermbillede 2015-02-13 kl 22 41 53

### CODE REVIEW

**Comment by zero-24** [comment]
@losedk did you mix up the images? I think the `after patch` is the `bevor patch` image? see the `span` :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6084">issues.joomla.org/joomla-cms/6084</a>.</sub>

**Comment by losedk** [comment]
Yeah :) They are updated now

**Comment by zero-24** [comment]
@losedk We need to have it done via http://issues.joomla.org/tracker/joomla-cms/6084/edit else the Tracker will revert it later :smile: (-> fixed)

I think this is a simple and easy change and we can move it to RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6084">issues.joomla.org/joomla-cms/6084</a>.</sub>

**Comment by losedk** [comment]
@zero-24 Ahh ofc. Thanks :)

**Comment by infograf768** [comment]
Merging. thanks.

**Pull request merged**
