### PR TITLE
[5.0] Spelling mismatch

### PR DESCRIPTION
**Pull request by brianteeman**
Simple spelling correction

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15904a2d996c81c940116454e3ea714b0515f0c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42349">issues.joomla.org/tracker/joomla-cms/42349</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 15904a2d996c81c940116454e3ea714b0515f0c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42349">issues.joomla.org/tracker/joomla-cms/42349</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42349">issues.joomla.org/tracker/joomla-cms/42349</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
