### PR TITLE
[showon] Allow "not in" condition and simplify php code

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.

### Summary of Changes

This PR does two things:
- Add a new "not in" condition to shown, we can use this condition by making use of the `!:` operator, insteadd of the normal `:`. This is particular useful if you want to put, for instance: field A should show on when fieldB value is not empty, ie, `showon="fieldB!:"`, which is not possible without this PR
Example: 
```php
// - Current
// Field A with value in 1 OR field B with value IN 1, 2 or 3
fieldname:1[OR]fieldB:1,2,3

// - NEW
// Field A with value in 1 OR field B with value NOT IN 1, 2 or 3
fieldname:1[OR]fieldB!:1,2,3
```
- Normalizes showon php code across the core. Remvoe a lot of duplicated code.

### Testing Instructions

1. Apply patch
2. Confirm current fields with showon behaviour continue to work fine
3. Change [this line](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L553) line in com_config xml so the showon condition is `mailonline:1[AND]mailer!:smtp`.
Now check this field will appear when the field `mailonline` is set to yes and the mailer is different than smtp.
4. Make any other tests you can remember

### Documentation Changes Required

Add this new operator to https://docs.joomla.org/Form_field#Showon

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
This should be an easy simple test.
I plan to make one more upgrade to shown js (allow showon on global values), but can only do this after this is merged.
So if you have 5 minutes please test.

**Comment by joomdonation** [comment]
This seems doesn't work well. After applying the patch, in Global Configuration, Mail Settings section, if we choose SMTP, additional fields like SMTP Host, SMTP Port... are not being shown

**Comment by andrepereiradasilva** [comment]
@joomladonation will check

**Comment by andrepereiradasilva** [comment]
@joomdonation yeah it was a bug forgot to change a thing. should be solved now.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on ecbcca15311bbf17f5ec8c9797e901f7971b9b78<br /><br />Tested showon behavior in Global Configuration of Joomla. Before and after patch, the behavior is the same

Tested the new operator and it worked, too. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13476">issues.joomla.org/tracker/joomla-cms/13476</a>.</sub>

**Comment by joomdonation** [comment]
OK. I tested it and it seems works well. I only tested the behavior (using Google Chrome ), no code review.

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on ecbcca15311bbf17f5ec8c9797e901f7971b9b78<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13476">issues.joomla.org/tracker/joomla-cms/13476</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13476">issues.joomla.org/tracker/joomla-cms/13476</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just remove a obvious bug a double json_enconde when using showon on fieldset. no need to remove RTC IMO

**Pull request merged**
