### PR TITLE
Remove chosen from com_search

### PR DESCRIPTION
**Pull request by brianteeman**
Chosen is not accessible so we shouldnt use it unless it offers something useful.

In the search component in the front end there are potentially two lists Ordering and display #

Neither of these require or benefit from chosen so this simple PR returns them to regular and accessible lists

Pull Request for Issue #24469

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on aa618b870a6ac1876f7e823062941e626c1492bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24623">issues.joomla.org/tracker/joomla-cms/24623</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aa618b870a6ac1876f7e823062941e626c1492bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24623">issues.joomla.org/tracker/joomla-cms/24623</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24623">issues.joomla.org/tracker/joomla-cms/24623</a>.</sub>

**Comment by HLeithner** [comment]
Whats the reason to remove this without needs? The only thing what could happen is to break sites that expect chosen.

**Comment by brianteeman** [comment]
It is removed from this page because chosen breaks accessibility and we dont need any of the added features of chosen for the select lists here.

It cannot break an existing site

**Comment by wilsonge** [comment]
We don't in this view but the long standing opinion is removing this can affect ssites that were using it on other pages without the include. This was how we ended up basically rolling out chosen into every view in the backend (as well as the consistency argument). I agree with @HLeithner that this is something not to be fixed in 3.x sadly

**Comment by brianteeman** [comment]
> We don't in this view but the long standing opinion is removing this can affect sites that were using it on other pages without the include. 

I don't follow this logic. We are talking about a component so how it can affect other pages that are not com_search

**Comment by wilsonge** [comment]
No it doesn’t affect other pages but it does affect modules and plugins on that page 

For the record I disagreed with this logic at the time. But it’s long been made standard. And especially given we should be trying to 3.x towards more support only mode in anticipation of 4.0 it doesn’t make sense to make changes like this

**Comment by brianteeman** [comment]
in which case the user can create a template override

**Comment by zwiastunsw** [comment]
@wilsonge : What kind of plugin? For which modules? Some example? Specifically? It was a very bad code!

**Comment by Fedik** [comment]
it was introduced as a fix #1653 for some issue, which no one know anymore 
it seems was just a "styling"

**Comment by HLeithner** [comment]
I'm closing this because of the statements above not breaking user templates.

**Comment by brianteeman** [comment]
Shame that accessibility doesnt matter

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24623">issues.joomla.org/tracker/joomla-cms/24623</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
