### PR TITLE
Front-end Module Parameters - added validate=options to all fields pa…

### PR DESCRIPTION
**Pull request by pe7er**
This PR adds validation to parameter fields of type=option to the parameters of .xml files **front-end Modules**

I've added
```xml
validate="options"
```
to all fields of type=list with defined options

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]
LGTM

**Comment by jwaisner** [comment]
@pe7er Can you please provide test instructions for this PR?

**Comment by brianteeman** [comment]
@jwaisner The testing is by code review which should be obvious

**Comment by jwaisner** [comment]
@brianteeman I appreciate the clarification. However I do not appreciate the assumption that everyone understands all coding language.

**Comment by pe7er** [comment]
@jwaisner Sorry, I should have added a testing instruction that it could be tested with a code review.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 614ab186251298a559341756470c88f420bbd580<br /><br />long list :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28829">issues.joomla.org/tracker/joomla-cms/28829</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 614ab186251298a559341756470c88f420bbd580<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28829">issues.joomla.org/tracker/joomla-cms/28829</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28829">issues.joomla.org/tracker/joomla-cms/28829</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
