### PR TITLE
[4.0] Validate access level fields

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Since https://github.com/joomla/joomla-cms/pull/25817, access level field supports validating options. This adds validation to existing forms.

### Testing Instructions

Saving articles, categories, global configuration and whatever else containing access level field still works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7d64e0245f8d2367102c63c867a47181784ad5a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31302">issues.joomla.org/tracker/joomla-cms/31302</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7d64e0245f8d2367102c63c867a47181784ad5a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31302">issues.joomla.org/tracker/joomla-cms/31302</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31302">issues.joomla.org/tracker/joomla-cms/31302</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
