### PR TITLE
[5.0] schemaorg sync translation in joomla.ini

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

sync translation in api file
https://github.com/joomla/joomla-cms/blob/46b5724a7ce0b2e5033bdfe5f18a268abf63219f/administrator/language/en-GB/joomla.ini#L831
https://github.com/joomla/joomla-cms/blob/46b5724a7ce0b2e5033bdfe5f18a268abf63219f/api/language/en-GB/joomla.ini#L823

### Testing Instructions

code review

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2900070bb75d0311e32704f3fff25d9e33af7230<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41403">issues.joomla.org/tracker/joomla-cms/41403</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2900070bb75d0311e32704f3fff25d9e33af7230<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41403">issues.joomla.org/tracker/joomla-cms/41403</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41403">issues.joomla.org/tracker/joomla-cms/41403</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
