### PR TITLE
[4.0] useless nonbreakingspace in en-GB

### PR DESCRIPTION
**Pull request by infograf768**
# Summary of Changes
Deleted useless `&nbsp;` in new strings which I wrongly introduced in
https://github.com/joomla/joomla-cms/pull/28936

Can be merged on review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 535f680d994601753575f240746c526c7fb86f10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29017">issues.joomla.org/tracker/joomla-cms/29017</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 535f680d994601753575f240746c526c7fb86f10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29017">issues.joomla.org/tracker/joomla-cms/29017</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29017">issues.joomla.org/tracker/joomla-cms/29017</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
