### PR TITLE
Suppress empty class attribute in pagination

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Don't output empty class attribute.

### Testing Instructions
Go to Administration > Content > Articles
View page source
Search `<a class=""`

### Expected result
`<a   href="#"`

### Actual result
`<a class=""  href="#"`

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Can't confirm.

Don't find `<a class=""` in Article List View or in Article.
### System information
3.8.1-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4363c6d7c1e5be39f5516ad598c6a887cb2a7e45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18093">issues.joomla.org/tracker/joomla-cms/18093</a>.</sub>

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 4363c6d7c1e5be39f5516ad598c6a887cb2a7e45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18093">issues.joomla.org/tracker/joomla-cms/18093</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
