### PR TITLE
Normalising sprintf in debug plugin

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #10626 (See there for instructions)
Enable Debug System and Debug language in Global configuration.
Set Log Deprecated API to Yes in System debug plugin.

Patch and test again, make sure you get this:
screen shot 2016-05-26 at 08 17 20

### CODE REVIEW

**Comment by infograf768** [comment]
Can be merged on Review.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on f9fc4e88992c73e9a1d9983a65184d22071583d4<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10627">issues.joomla.org/joomla-cms/10627</a>.</sub>

**Comment by sovainfo** [comment]
I have tested this item :white_check_mark: successfully on f9fc4e88992c73e9a1d9983a65184d22071583d4<br /><br />Applied to J351. Works OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10627">issues.joomla.org/joomla-cms/10627</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10627">issues.joomla.org/joomla-cms/10627</a>.</sub>

**Pull request merged**
