### PR TITLE
add .editorconfig to .gitignore

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue improvment .
#### Summary of Changes

Simple PR to add .editorconfig to .gitignore
#### Testing Instructions

code review

### CODE REVIEW

**Comment by piotr-cz** [comment]
This file shouldn't be placed in `.gitignore`, becase developers are supposed to retrieve it during git clone.

But it should be excluded during package build process within the [build.php](https://github.com/joomla/joomla-cms/blob/3.6.0-beta2/build/build.php#L109-L121) file. I usually add this in the `.gitattributes` file

```
.editorconfig export-ignore
```

I've added it into the Joomla! Coding-standards repo [here](https://github.com/joomla/coding-standards/blob/master/IDE/editorconfig.ini), but I guess there is no harm placing it inside Joomla! repo.

**Comment by wojsmol** [comment]
I added .editorconfig to gitignore taking into account the current situation where the file is not a in the repository joomla/joomla-cms. If .editorconfig been added to joomla/joomla-cms then of course it should be added to the build/build.php and removed from a .gitignore.

**Comment by piotr-cz** [comment]
True, as long as the file belongs to other repo, it should be excluded. :+1:

**Comment by wojsmol** [comment]
@piotr-cz Please test :smile:

**Comment by wojsmol** [comment]
cc @wilsonge

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 038042c7108c0577a1146577da50ef7dacd841f7<br /><br />On Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10859">issues.joomla.org/joomla-cms/10859</a>.</sub>

**Pull request merged**
