### PR TITLE
Add basic support for sass/scss files to Template manager editing (redo)

### PR DESCRIPTION
**Pull request by brianteeman**
Redo to resolve merge conflicts in #9871 

@zero-24 can you retest this please to make sure I didnt miss anything in this redo

### CODE REVIEW

**Comment by zero-24** [comment]
@brianteeman i have just send you a PR for travis i will try to test this evening.

**Comment by andrepereiradasilva** [comment]
travis still not happy

**Comment by brianteeman** [comment]
travis is happy now

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 8f74e988ed1434b9296087482d5cfbc201256305<br /><br />Works good! Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10186">issues.joomla.org/joomla-cms/10186</a>.</sub>

**Comment by brianteeman** [comment]
Moving to RTC as it was already tested before the redo for merge conflicts<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10186">issues.joomla.org/joomla-cms/10186</a>.</sub>

**Comment by C-Lodder** [comment]
The SQL files also need updating too.

https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L506

> "source_formats":"txt,less,ini,xml,js,php,css"

replace with:

> "source_formats":"txt,less,ini,xml,js,php,css,sass,scss"

Unless this is done, people will will manually need to go to the Template Options and manually add them.

**Comment by zero-24** [comment]
Correct for 3.x we need to do this as we cant and should not override the entry in the database that maybe has ben changed to something different.

**Comment by zero-24** [comment]
Ahhh ok i got you point now. I'm on a PR :)

**Comment by alikon** [comment]
@zero-24 maybe this time more fast than you... bored on train....

**Comment by zero-24** [comment]
Thanks :+1:

**Pull request merged**
