### PR TITLE
Remove usage of deprecated JArrayHelper - com_menus

### PR DESCRIPTION
**Pull request by izharaazmi**
Remove usage of deprecated JArrayHelper from com_menus
#### Testing Instructions

Test:
- Set default menu item
- Publish/Unpublish
- Batch copy/move etc.

Also review code, if possible.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 23320f01a21b09b966931209116dc427b0bdd42e<br /><br />Works as described.
Code review fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10675">issues.joomla.org/joomla-cms/10675</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 23320f01a21b09b966931209116dc427b0bdd42e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10675">issues.joomla.org/joomla-cms/10675</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10675">issues.joomla.org/joomla-cms/10675</a>.</sub>

**Comment by wilsonge** [comment]
Merged with 14ff580 - thanks!

**Pull request closed without merging**
