### PR TITLE
Fix delete session meta data error

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #19511 .

### Summary of Changes
There was a typo in the code causes session meta data never being deleted and causes wrong number of visitors displayed in Who's online module. This PR fixes that issue.

### Testing Instructions
Ping @hannes01, @central4all and @sandewt for testing as they have issue on their website. Please apply patch and confirm the issue sorted.

### CODE REVIEW

**Comment by central4all** [comment]
i have problem with the members not the visitors and is not fixed,
maybe is similar,.

**Comment by sandewt** [comment]
The fix can only work in case of the PHP session handler !!!

<code>
if ($handler !== 'database' && $time % 5 === 0)
{
...
}
</code>


I use the DATABASE session handler.

Today I have looked at my live site a few times.
I can not explain why the number of sessions suddenly decreased from over 1000 to less than 30 guests?
The session life time is 15 minutes.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19514">issues.joomla.org/tracker/joomla-cms/19514</a>.</sub>

**Comment by joomdonation** [comment]
In case you use DATABASE session handler, the session meta data won't be deleted on page load like in older version of Joomla anymore. It will be deleted by PHP session data garbage collection, see http://php.net/manual/en/function.session-gc.php to understand about it better

I guess number of sessions suddenly decreased from over 1000 to less than 30 guests is because session data was not deleted before and in one of your access, PHP run session data garbage collection, the expired session meta data is deleted from database, thus  the number of guests reduced.

See https://github.com/joomla/joomla-cms/pull/19165 for details explanation and https://github.com/joomla/joomla-cms/issues/19146 to see why the change was implemented .

**Comment by central4all** [comment]
i confirm that works with PHP

**Comment by Quy** [comment]
@central4all Please do the following to mark your test as successful:

* Open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19514)
* Log in with your Github account
* Click on blue `Test this` button above author's photo
* Mark your test as `Tested successfully`
* Click `Submit test result`

**Comment by central4all** [comment]
I have tested this item :white_check_mark: successfully on e6243cde13e14e0f3eb63480a391722e94b36044<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19514">issues.joomla.org/tracker/joomla-cms/19514</a>.</sub>

**Comment by sandewt** [comment]
Thanks @joomdonation, I see that a whole history preceded it.

**Comment by arvindpdmn** [comment]
I am running Joomla 3.8.6. Today is June 19. I have registered user sessions that are 3 days old. I have guest sessions as old as April 2. Number of entries in session table is excess of 25k. What's happening?

**Comment by brianteeman** [comment]
Just upgrade to Joomla 3.8.8

**Comment by eSilverStrike** [comment]
I am using Joomla 3.8.12 and this issue is still not fixed. My Who's Online Module lists hundreds of guest users when maybe I have only 5 online at any one time. I have Joomla set to use the PHP Session Handler and session lifetime set to 30.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19514">issues.joomla.org/tracker/joomla-cms/19514</a>.</sub>

**Comment by joomdonation** [comment]
You should check and make sure the plugin **System - Session Data Purge** is available on your site and published. In the past, I heard that some users didn't have that plugin on the site for some reasons and that might be the reasons causing the error.

If that happens for your site, go to Extensions -> Manage -> Discover to discover and install, publish the plugin to get the issue sorted.

**Comment by eSilverStrike** [comment]
Thanks for the reply. I checked and I do have the plugin installed. Probability is set to 1 and Divisor is set to 100. 

I set the probability to 100 to see if the plugin works and it did reset my user count back to 32 on my next visit (from 504). Obviously you don't want the plugin firing all the time so I set the probability to 10. Maybe there is an issue when the Probability is set really low?

**Pull request merged**
