### PR TITLE
CodeMirror 5.11

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This update doesn't really include anything notable for Joomla users, just keeping up-to-date.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 78260786105b4bcf9cdc8ed64999e4c5c411e834<br /><br />Tested in com_templates and com_content - all good - thanks for keeping this up to date<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8978">issues.joomla.org/joomla-cms/8978</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 78260786105b4bcf9cdc8ed64999e4c5c411e834<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8978">issues.joomla.org/joomla-cms/8978</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for keeping it up to date<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8978">issues.joomla.org/joomla-cms/8978</a>.</sub>

**Comment by wilsonge** [comment]
Indeed :) Thanks!

**Pull request merged**
