### PR TITLE
Add Comment for translators not to touch lines of code

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #24161 .

### Summary of Changes
An easy solution for the problem that translators could try to translate code. It seems that translators did not understand that code must not be tranlated.
Some proposed solutions seem to be rather sophisticated and need some work so this could be a very simple solution:
Add a comment above the Language Key.

### Testing Instructions
Code Review

### Actual result BEFORE applying this Pull Request
Following the issue description there are translators who ty to translate the code. 

### Expected result AFTER applying this Pull Request
Translators read the comment and don't touch the code. 

### Documentation Changes Required
no

### CODE REVIEW

**Comment by brianteeman** [comment]
There will be complaints that they dont see the comments in some translation tools but this is imho the correct way to mark something as not to be translated.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 79ea13d28abb1edaf8ed1c21f095697630aa3e1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31822">issues.joomla.org/tracker/joomla-cms/31822</a>.</sub>

**Comment by chmst** [comment]
"we cannot heal stupidity" as you said some time ago. This could help in some way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31822">issues.joomla.org/tracker/joomla-cms/31822</a>.</sub>

**Comment by horus68** [comment]
When using crowdin the proper way to comment a line os not placing a commented line above the string but to place the comment at the end of the line to be commented. The coment needs to start with // 
It Will display for traslados then.

**Comment by brianteeman** [comment]
If that worked it would be awesome but it doesnt :(
image

image

**Comment by chmst** [comment]
Maybe in the string itself?

**Comment by brianteeman** [comment]
Just the same - the correct way was to do what this PR does. YCFS

**Comment by horus68** [comment]
Well this works for me in another project. See:
`$app_strings['LBL_SEARCH_OF'] = ' of '; // Usage: Page # of #`

Maybe its only for PHP files?

Note: the comments will be displayed in Crowdin string into the section "Context" this is placed below the value to be translated. You need to click on it to see the contents.

PHP language file (from a different project):
suitecrm_notes1

Crowdin: (see "Context")
suitecrm_notes2

**Comment by horus68** [comment]
A final say from me: Adding comments to the end of the string line it works fine with Crowdin as it supposed to be (using a Joomla file). See pictures.
Note: I also Hope some users stop saying nasty things as "we cannot heal stupidity" or  YCFS (You Can't Fix Stupid). Do you feel its OK calling "Stupid" to others? No, you have no right to call it to nobody. Please keep your intelligent remarks just for you.
I'm leaving this conversation now.

contact_comments_crowdin
contact_comments_source

**Comment by brianteeman** [comment]
Yes it works in crowdin but the comment is output in joomla :(

**Comment by richard67** [comment]
> Maybe its only for PHP files?

I think so. The comment syntax of PHP files and ini files is different.

**Comment by richard67** [comment]
If Crowdin can't handle ini file syntax (comments starting with a semicolon), it's a Crowdin and not a Joomla issue.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 79ea13d28abb1edaf8ed1c21f095697630aa3e1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31822">issues.joomla.org/tracker/joomla-cms/31822</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31822">issues.joomla.org/tracker/joomla-cms/31822</a>.</sub>

**Comment by infograf768** [comment]
@horus68 
As I wrote in TT forum:

This would throw an error for the file concerned, in core as well as com_localise.
Example: `COM_CONTENT_ARTICLE_CONTENT="Content"  //commentaire`

```
**Parsing errors in language files**

    JROOT/language/en-GB/en-GB.com_content.ini : error(s) in line(s) 9
    
```

As for "we cannot heal stupidity" , I do agree with @horus68 . 
Many TTs are absolutely not code aware and this should remain present in everybody's mind.

### Note: 
com_localise displays these comments:

Screen Shot 2021-01-02 at 10 09 12

**Comment by infograf768** [comment]
Tks

**Pull request merged**
