### PR TITLE
[4.0] Reimplementing client filter in Modules Manager

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23400

### Summary of Changes
As title says

### Testing Instructions
Display Modules Manager

### After patch
Client filter now displays.

screen shot 2018-12-31 at 08 14 57
screen shot 2018-12-31 at 08 14 37

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 373e51f8649ffb7dfe471ffe4bad41bf4a864d34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23406">issues.joomla.org/tracker/joomla-cms/23406</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 373e51f8649ffb7dfe471ffe4bad41bf4a864d34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23406">issues.joomla.org/tracker/joomla-cms/23406</a>.</sub>

**Comment by infograf768** [comment]
rtc. Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23406">issues.joomla.org/tracker/joomla-cms/23406</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge 
Please merge as I have some other PRs concerning modules . One waiting ( #23289 ) and another one I have to do for a change missing in #23418

**Comment by wilsonge** [comment]
@SniperSister  @zero-24 RIPS please. I'm not really sure how this happened as I reran this a second time so reproducible 

http://ci.joomla.org/joomla/joomla-cms/13420
http://ci.joomla.org/joomla/joomla-cms/13418

But all i did was merge in 4.0 🤔

**Comment by infograf768** [comment]
Looks OK to merge now @wilsonge

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
