### PR TITLE
[4.0] Fix drag and drop re-ordering for grouped items

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #34369.

### Summary of Changes
This PR fixes the issue https://github.com/joomla/joomla-cms/issues/34369 

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/34369 to understand the issue.
2. Install Joomla 4 nightly build. Install Blog sample data so that you have data ready for testing
3. Create additional categories if needed so that you will have parent-children categories on your site.
4. Download update package for this PR at https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/34375/downloads/44812/Joomla_4.0.0-rc2-dev+pr.34375-Development-Update_Package.zip , go to System -> Update -> Joomla, upload this package and run the update.
5. Try to re-order categories (both parent and children categories), articles, modules and make sure ordering of these items are saved when you re-fresh the page.

### CODE REVIEW

**Comment by joomdonation** [comment]
No, sorry. Not this simple.  We should only calculate and update ordering of items in the same group/level only. This won't work. I'm closing this PR and will re-open it if I can come up with a solution.

**Comment by joomdonation** [comment]
OK. I tested it myself and it works. I updated testing instructions, please test. Thanks.

**Comment by nozaro33** [comment]
I have tested this item successfully, sorry I don't know really know how to test via composer

**Comment by joomdonation** [comment]
Thanks @nozaro33. You do not need to test it using composer. Just follow the testing instructions, download , install the update package, test it and make sure it works.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ef956d4fb48342eb1251ee307e8d7472936ff55d<br /><br />The ordering of parent- and children-categories, articles and modules is saved after refresh of the page.

Question: Drag'n'Drop a parent-category show children-categories only after page-refresh (please see video below). A different Issue?




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34375">issues.joomla.org/tracker/joomla-cms/34375</a>.</sub>

**Comment by joomdonation** [comment]
@sandramay0905 Yes. It is different issue. It depends on the script which we are using to handle drag and drop. I asked @dgrammatiko and @Fedik about it https://github.com/joomla/joomla-cms/issues/34369#issuecomment-853803347 .

**Comment by joomdonation** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34375">issues.joomla.org/tracker/joomla-cms/34375</a>.</sub>

**Comment by ghost** [comment]
@joomdonation do i have to open a issue for handle drag and drop or is your comment enough?

**Comment by joomdonation** [comment]
@sandramay0905 Yes. Please open a new issue for that. Thanks !

**Comment by joomdonation** [comment]
RTC again. It was lost when a new comment added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34375">issues.joomla.org/tracker/joomla-cms/34375</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! Nice job!

**Pull request merged**
