### PR TITLE
Adding help to test joomla cms

### PR DESCRIPTION
**Pull request by pritalpatel**
**Adding help to test joomla cms**
This changes will guide user to see **tests** folder if they want to know how to test joomla-cms.

### CODE REVIEW

**Comment by brianteeman** [comment]
I really dont think this is a good idea - it could confuse people as the readme is distributed in the CMS but the tests folder is not.

**Comment by brianteeman** [comment]
Also any change made to readme.md will also have to be made to readme.txt

**Comment by zero-24** [comment]
@brianteeman the reademe.md is not shipped withe the CMS stable. It is just the description text for the repo ;)

If we want to add it i think we should write something that the tests folder contain the system and unit tests. General patch testing or just simple testing don't require that tests folder :)

**Comment by brianteeman** [comment]
Readme.txt is shipped and the two files really should be the same but as
you state @zero24 if something is going to be added then the proposed text
really isnt fit for the prupose

On 17 March 2016 at 19:37, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> the reademe.md is not
> shipped withe the CMS stable. It is just the description text for the repo
> ;)
>
> If we want to add it i think we should write something that the tests
> folder contain the system and unit tests. General patch testing or just
> simple testing don't require that tests folder :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9456#issuecomment-198049377>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by pritalpatel** [comment]
Thanks for review. I have changed texts and tried to make it more informative. 
My purpose behind adding this help is that, when I have started reading this doc I didn't get idea to go to **tests** folder if I want to execute and find tests suits for unit or system testing.

**Comment by Bakual** [comment]
Personally, I think anyone who is able to actually run those tests, will have no problems figuring out that the tests are in that folder.

**Comment by andrepereiradasilva** [comment]
i also don't agree with this for most people test is testing the patches, in other words, using the patchtester for that, not the kind of tests described here.

**Comment by brianteeman** [comment]
@pritalpatel Thanks for your contribution but I am closing this  for the reasons stated above

**Comment by pritalpatel** [comment]
NP. I understand. Thanks for review.

**Pull request closed without merging**
