### PR TITLE
[4.0] com_banner batch client [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
the label had the wrong for=

This pr corrects that so that the label is correctly marked to be for the select with the id batch-client-id

code review should be ok

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 163f89ef1d36201605e698a608998a528b3c2661<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29917">issues.joomla.org/tracker/joomla-cms/29917</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 163f89ef1d36201605e698a608998a528b3c2661<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29917">issues.joomla.org/tracker/joomla-cms/29917</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29917">issues.joomla.org/tracker/joomla-cms/29917</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
