### PR TITLE
[4.0] [cassiopeia] Fix wrapper width

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Removes the BS `container` class been added to the body which causes some general craziness to the layout.

### Before
image

### After
image

### CODE REVIEW

**Comment by wilsonge** [comment]
This came from https://github.com/joomla/joomla-cms/pull/19418 - not against a revert if things are going wrong - but then presumably we should remove the fluid/static option from the template xml as well?

**Comment by ciar4n** [comment]
We can keep the fluid/static option just maybe do it a little different. I'll have a look first chance I get.

**Comment by wilsonge** [comment]
Awesome. Thanks!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d0e657a63478a7094ebe4a5caa5d0ba41f8cb5ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20105">issues.joomla.org/tracker/joomla-cms/20105</a>.</sub>

**Pull request merged**
