### PR TITLE
[4] Remove unused file

### PR DESCRIPTION
**Pull request by PhilETaylor**
Removing an unused file, as this project doesn't want to take code quality seriously.

### CODE REVIEW

**Comment by brianteeman** [comment]
this should be closed. its just a petulant  pr

**Comment by PhilETaylor** [comment]
This file is unused. It is not used by the Joomla project or the the drone/appveyour. It serves no purpose in this project.

**Comment by joomdonation** [comment]
Came down @PhilETaylor . You know that we care about code quality, we just want to do a bit later to avoid merge conflicts as I mentioned somewhere.

**Comment by PhilETaylor** [comment]
> we just want to do a bit later to avoid merge conflicts as I mentioned somewhere.

Same excuse as 5 years ago.

**Comment by PhilETaylor** [comment]
I dont see why this was closed. This file is unused. It is not used by the Joomla project or the the drone/appveyour. It serves no purpose in this project's repository.

Please tell me why you are keeping this file?

**Comment by joomdonation** [comment]
It was created, so it was used. Maybe it is not used recently, but that doesn't mean we won't use it in the future, maybe when after Joomla 4 releases. There is no reason to delete it now, then create it again when we need to use it.

**Pull request closed without merging**
