### PR TITLE
[4.0] Add period to the success message

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Go to System >Site Modules
Edit a module.
Click Save & Close button.
See success message.

Perform similar steps to Plugins where the success message ends with a period.

### Actual result BEFORE applying this Pull Request
Message has no period.

### Expected result AFTER applying this Pull Request
Message ends with a period.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0a155719e71896d42ab5650945f10fc141c3a508<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36172">issues.joomla.org/tracker/joomla-cms/36172</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0a155719e71896d42ab5650945f10fc141c3a508<br /><br />Tested successfully in 4.0.5 rc using Wampserver 3.2.6 on Windows 10 with PHP 8.1.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36172">issues.joomla.org/tracker/joomla-cms/36172</a>.</sub>

**Comment by drmenzelit** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36172">issues.joomla.org/tracker/joomla-cms/36172</a>.</sub>

**Comment by chmst** [comment]
thx

**Pull request merged**
