### PR TITLE
[4.2] PHP8.2 Remove the not used method assignment in mm API

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Removes the not used method variable in the media manager APIController.

### Testing Instructions
Open the media manager on PHP 8.2

### Actual result BEFORE applying this Pull Request
Media data is not loaded.

### Expected result AFTER applying this Pull Request
Media data is loaded.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
@laoneo still the data not loading. But also is giving a js error

```js
Uncaught SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
    at JSON.parse (<anonymous>)
    at onSuccess (media-manager.js?c9d04fea6dae2c821fd73c99da6c9835:8113:45)
    at xhr.onreadystatechange (core.js?c9d04fea6dae2c821fd73c99da6c9835:669:23)
```

**[with 8.2 only]**

**Comment by laoneo** [comment]
In the browser tools can you inspect the XHR request, what for a error message is displayed in the response?

**Comment by carlitorweb** [comment]
Sorry, forgot that:

`<b>Deprecated</b>:  Using ${var} in strings is deprecated, use {$var} instead in <b>www\bugtesting\joomla-cms\libraries\vendor\voku\portable-utf8\src\voku\helper\UTF8.php</b> on line <b>13409</b>`

**Comment by carlitorweb** [comment]
But I confirm the error of the not used method variable and the patch fix it. The other error is not relate with this one

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on d0c53b7650e4b4b6b574cdf1251bafcada976c48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39612">issues.joomla.org/tracker/joomla-cms/39612</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on d0c53b7650e4b4b6b574cdf1251bafcada976c48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39612">issues.joomla.org/tracker/joomla-cms/39612</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39612">issues.joomla.org/tracker/joomla-cms/39612</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
