### PR TITLE
Master_Save Plugin

### PR DESCRIPTION
**Pull request by christianboulbi**
Pull Request for Issue # .

### Summary of Changes
create new Table "item_associations" by install
Put the columns 'associations' and 'not associations' together to one Column.
new created articles are master.
if associations with a Master, another articles are slave 

### Testing Instructions
create new articles without associations
make the association and go inside the " Multilingual Associations plugin" Area to see the changes

### CODE REVIEW

**Comment by Bakual** [comment]
Was this intended to go against the 4.0 branch?

**Comment by christianboulbi** [comment]
Hi Bakual. yes, it was intended to go against the 4.0 branch
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17811">issues.joomla.org/tracker/joomla-cms/17811</a>.</sub>

**Comment by brianteeman** [comment]
ok i am going to close this then - please create a new PR against the 4.0 branch

**Comment by C-Lodder** [comment]
Over half a million changes? If you want to push code into the 4.0-dev branch, then do it from a subranch of your 4.0 branch, not staging.

Staging is still Joomla 3.x

**Pull request closed without merging**
