### PR TITLE
[3] s/timymce/tinymce

### PR DESCRIPTION
**Pull request by PhilETaylor**
This one might be controversial but there you go...

s/timymce/tinymce

### CODE REVIEW

**Comment by brianteeman** [comment]
Good spot

**Comment by PhilETaylor** [comment]
Huge thanks to the phpStorm project, again, without which I would be working at McDonalds still.

**Comment by wilsonge** [comment]
So *technically* this is a b/c break because anyone overriding the layout will find their JS no longer works. It's fairly unlikely anyone will be using this layout though. But one of those things probably safer to target at 3.10 rather than a patch release just to play it extra safe.

**Comment by brianteeman** [comment]
This is only the layout of the toolbar builder inside the plugin. If there is one person in the world that is overriding that it would be shocking

**Comment by PhilETaylor** [comment]
Joomla 3.10.0 based version is here: https://github.com/joomla/joomla-cms/pull/32056

Take your pick.

**Comment by zero-24** [comment]
Closing as the 3.10 PR has been merged. Thanks @PhilETaylor

**Pull request closed without merging**
