### PR TITLE
[imp] Menu manager: Menu items: adding tooltip to the menu item title

### PR DESCRIPTION
**Pull request by infograf768**
After patch we will get:

screen shot 2015-01-21 at 09 00 10

### CODE REVIEW

**Comment by brianteeman** [comment]
Is it really necessary to have a tooltip to say that if you click on something that is obviously a link then the link will open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by infograf768** [comment]
We do it elsewhere. This is just to normalise.

**Comment by AlexdeBorba** [comment]
I don't see the use of such feature.

**Comment by Bolzman** [comment]
Hand symbol of mouse pointer hovering a hyperlink is just what a tool tip would explain. IMO popping up a tool tip would irritate user (often it's correlated with popup = advertising). This is just like adding a tool tip "Edit" to a button, displaying "Edit".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by Bolzman** [comment]
Adds tool tip only to menu items, not to menus itself = inconsistent<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by brianteeman** [comment]
I am setting this to Needs Review so a CMS Maintainer can make a decision. As pointed out - it works- but is it a sensible thing to do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by FloryGlory** [comment]
Coll feature which is already used in the article manager. In consenquence it should be used in the menu manager, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by brianteeman** [comment]
I would argue it would be better to remove this useless tooltip from everywhere

**Comment by Wilma999** [comment]
I have tested this item :white_check_mark: successfully on eca42867a1df785dc883a67fea85eccda8c67f5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by snarf007** [comment]
I have tested this item :white_check_mark: successfully on eca42867a1df785dc883a67fea85eccda8c67f5b<br /><br />Before applying the patch no tooltip, after applying the patch a tooltip pops-up (edit).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. The maintainer should take the decision on this Closing or Merging. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5847">issues.joomla.org/joomla-cms/5847</a>.</sub>

**Pull request merged**
