### PR TITLE
Error, warning, success and info messages spacing

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This a small PR to improve the spacing in the error, warning, sucess and info messages.

Adds some space between title and message and removes extra space in the end.
##### Before PR (some examples)

image

image
##### After PR (some examples)

image

image
#### Testing Instructions
1. Use latest staging.
2. Apply patch
3. Check some messages

### CODE REVIEW

**Comment by rehrumesh** [comment]
I tried to test this PR.

Steps:
Log in to the admin panel.
Go to Users section.
Delete the email value.
Press Save.

Following are the results I got.


I have highlighted the text in order to view blank spaces. I cannot see much of a difference. Please tell me if I have followed wrong steps @andrepereiradasilva .

**Comment by andrepereiradasilva** [comment]
The difference in just the bottom margin. In the second print the top margin is the same as the bottom margin.
In the first print the bottommargin is double the top margin.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2f97aa9a140c1cc8dc70f476d8412b3110d626e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9181">issues.joomla.org/joomla-cms/9181</a>.</sub>

**Comment by infograf768** [comment]
the CLI generatecss.php has not been applied to this PR.
It lacks the change in isis rtl
```
diff --git a/administrator/templates/isis/css/template-rtl.css b/administrator/templates/isis/css/template-rtl.css
index 29092b9..8454415 100644
--- a/administrator/templates/isis/css/template-rtl.css
+++ b/administrator/templates/isis/css/template-rtl.css
@@ -2791,4 +2791,7 @@
 }
 .alert h4 {
+	margin: 0 0 .5em;
+}
+.alert p {
 	margin: 0;
 }
```

**Comment by andrepereiradasilva** [comment]
true, didn't use the CLI generatecss.php has not been applied to this PR.
That was to be done in linux right?

**Comment by infograf768** [comment]
i do it on mac. unix system. you just have to use the .diff above if no time.

**Comment by andrepereiradasilva** [comment]
ok, did it manually.

**Comment by rehrumesh** [comment]
I have tested this item :white_check_mark: successfully on [ad0ecfd](https://github.com/andrepereiradasilva/joomla-cms/commit/ad0ecfde3cbdd8d4c8fa40de236352c5d4706a74)

@andrepereiradasilva sorry for not noticing it initially.  :)

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on ad0ecfde3cbdd8d4c8fa40de236352c5d4706a74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9181">issues.joomla.org/joomla-cms/9181</a>.</sub>

**Comment by wilsonge** [comment]
You can run the CLI generator on any system. For windows though - you just need to make sure you have PHP in your environment variables (e.g. http://stackoverflow.com/a/2736574/1195517)

**Comment by grhcj** [comment]
@rehrumesh Please mark your test results here: https://issues.joomla.org/tracker/joomla-cms/9181 -> Login with GitHub account -> Button "Test this". Your current comment isn't counted as test result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9181">issues.joomla.org/joomla-cms/9181</a>.</sub>

**Comment by rehrumesh** [comment]
I have tested this item :white_check_mark: successfully on ad0ecfde3cbdd8d4c8fa40de236352c5d4706a74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9181">issues.joomla.org/joomla-cms/9181</a>.</sub>

**Comment by rehrumesh** [comment]
@grhcj Thanks for the info. :+1:

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9181">issues.joomla.org/joomla-cms/9181</a>.</sub>

**Pull request merged**
