### PR TITLE
[4.0] Add aria-hidden

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes`
Add aria-hidden to User Menu items

### Testing Instructions
Code review
or 
View page source
Check markup of User Menu dropdown

### CODE REVIEW

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 229b23e7e1d8ba78dd7e3d34d791d969280a773a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26737">issues.joomla.org/tracker/joomla-cms/26737</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 229b23e7e1d8ba78dd7e3d34d791d969280a773a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26737">issues.joomla.org/tracker/joomla-cms/26737</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26737">issues.joomla.org/tracker/joomla-cms/26737</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
