### PR TITLE
[4.0][Atum] Add border for btn-outline-* Bootstrap classes

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #21302 .

### Summary of Changes
Adds a border back to buttons fixing btn-outline-* classes

If these outline classes should exist is questionable however Bootstrap does not allow us to easily remove them.

### Testing Instructions
Easiest test is to paste the following somewhere in to the backend using your browser web dev tools...

```
<button type="button" class="btn btn-outline-primary">Primary</button>
<button type="button" class="btn btn-outline-secondary">Secondary</button>
<button type="button" class="btn btn-outline-success">Success</button>
<button type="button" class="btn btn-outline-danger">Danger</button>
<button type="button" class="btn btn-outline-warning">Warning</button>
<button type="button" class="btn btn-outline-info">Info</button>
<button type="button" class="btn btn-outline-dark">Dark</button>
```

### Before
image

### After
image

### CODE REVIEW

**Comment by ggppdk** [comment]
Tested it works
but template also forces white inside the toolbar for buttons
`.subhead .btn {color: #fff;}`

`templates\atum\scss\blocks\_toolbar.scss`

Can we change

```css
// Toolbar

.subhead {
   ...

  .btn {
    ...
    color: #fff;
    ...
  }
}
```

to ?

```css
// Toolbar

.subhead {
   ...

  .btn:not([class^="btn-outline-"]):not([class*="btn-outline-"]) {
    color: fff;
  }

  .btn {
    ...
    ...
  }
}
```

**Comment by ciar4n** [comment]
Pretty sure that `.subhead .btn {color: #fff;}` is not needed. Let me check...

**Comment by ciar4n** [comment]
`.subhead .btn {color: #fff;}` removed without any apparent issue.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 52aa1b03c5a3ecff3e7c52ca480bfceb7206c178<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21322">issues.joomla.org/tracker/joomla-cms/21322</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
