### PR TITLE
[4.0] Fix save2copy for workflows

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #29597 .

### Summary of Changes
Remove rquired from field default

### Testing Instructions
see #29597

### Actual result BEFORE applying this Pull Request
Error: Field required: default

### Expected result AFTER applying this Pull Request
No Warning, the workflow is saved as copy

### Documentation Changes Required
no

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5bf6fd51430c6cfd1f854cde9843c9ac062f3359<br /><br />Result with Patch: Message Item Saved.

But is this correct?
COM_WORKFLOW_BASIC_WORKFLOW (2)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29790">issues.joomla.org/tracker/joomla-cms/29790</a>.</sub>
workflowcopy

**Edit:** Ah, I see, I can change the title :-)

workflow_02

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 5bf6fd51430c6cfd1f854cde9843c9ac062f3359<br /><br />**Change fixes various issues outlined in #29597**
- Second Save after changing workflow to default no longer has error.
- Save and Close on a default workflow saves and closes the workflow

**A related issue:**
- #29597 was raised after testing the special Workflow Beta 2 Dev assembled for testing Workflow just before the 4.0.0-beta1 was released.
- It appears that between the Beta 2 Dev and 4.0.0-beta1, the "Save as Copy" functionality for Workflows was disabled, so this also needs to be patched.
image


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29790">issues.joomla.org/tracker/joomla-cms/29790</a>.</sub>

**Comment by particthistle** [comment]
Save as Copy was fixed in https://github.com/joomla/joomla-cms/pull/29263

I updated 4.0.0-beta1 to latest nightly build of 4.0-dev which has that included, and so Save as Copy toolbar item is then applied.

This pull request then additionally fixes the issue and a copy can be saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29790">issues.joomla.org/tracker/joomla-cms/29790</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29790">issues.joomla.org/tracker/joomla-cms/29790</a>.</sub>

**Comment by richard67** [comment]
Thanks! Have tested it with sucess, too, before merging. Also the "home" field ("Default page") for menu items has no "required" attribute, so this here is consistent with that.

**Pull request merged**
