### PR TITLE
Don't show Joomla! Update quickicon to unauthorised users

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Checks if user is authorised to access `com_joomlaupdate`.

### Testing Instructions

Create a user group with backend access. Configure permissions:
Set `Installer - Access Administration Interface` (`com_installer.core.manage`) permissions to `Allow`.
Set `Joomla! Update - Configure ACL & Options ` (`com_joomlaupdate.core.admin`) permissions to `Deny`.
Create a user in this group, login with this user.
In control panel, click on Joomla! update quick icon.

### Expected result

Either the icon is not shown or no errors when viewing `com_joomlaupdate`.

### Actual result

> An error has occurred.
> 
>     403 You are not authorised to view this resource. 

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by brianteeman** [comment]
My 2c is that we absolutely should show the icon and if there are updates available but it does need something better than the 403 if they are not authorised. Perhaps some sort of message "Please contact the site administrator to update"

**Comment by ghost** [comment]
@SharkyKZ whats the Status of this Pull Request? Will you take the Suggestion by @brianteeman?

**Comment by SharkyKZ** [comment]
Not in 3.x.

**Comment by ghost** [comment]
This PR can be tested?

**Comment by SharkyKZ** [comment]
Yes, I think so.

**Review by zero-24 — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 03d140a8c049ee30f606978dee65cdd52813804e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25169">issues.joomla.org/tracker/joomla-cms/25169</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 03d140a8c049ee30f606978dee65cdd52813804e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25169">issues.joomla.org/tracker/joomla-cms/25169</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
This is really a bad idea as I stated before

**Comment by HLeithner** [comment]
I don't like the change it would be better to remove the link and only show that a new version is available if you can't update as the current user.

If you like to disable the quick icon the admin can change the access level of the plugin.

**Comment by HLeithner** [comment]
I'm not happy with this solution @SharkyKZ is it possible for you to change the PR as I described before.

Only remove the link if the user does not have the permission?

Thanks in advanced.

**Comment by brianteeman** [comment]
@HLeithner disabling the link will just frustrate the user - there needs to be a message. The current code behaviour is correct its just the message that should be changed https://github.com/joomla/joomla-cms/pull/25169#issuecomment-500748363

**Comment by HLeithner** [comment]
The user doesn't know that there would be a link normally. Giving him a message saying you can't update brings him not more information as he already has but if you find that better you can add a PR. 

As long as it doesn't end in an error message it's ok for me.

**Comment by brianteeman** [comment]
> The user doesn't know that there would be a link normally. 

Of course they do - all the other quickicons are links

**Comment by Renuka-S** [comment]
I have tested this item :white_check_mark: successfully on 50691ed8830ee21bdab40f7a21e258ea533ea630<br /><br />Icon not visible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25169">issues.joomla.org/tracker/joomla-cms/25169</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for this pr but I will not merge it, I would like to see no link or a proper error message. But only showing it to admin can be achieved by setting a proper access level to the plugin.

**Comment by SharkyKZ** [comment]
It's showing only to super admin because that's what `com_joomlaupdate` requires. This PR makes perceived behavior consistent with extension update check plugin.

**Comment by brianteeman** [comment]
The check does two things
1. It tells you that the site needs to be updated
2. It has a link to perform the update

As stated before simply hiding the icon is not a solution. The solution is to display something than other than a 403

**Comment by HLeithner** [comment]
That's the reason I closed it, it would be better to bring a popup/alert window/what ever to tell the user he/she has to inform a super user.

**Pull request closed without merging**
