### PR TITLE
[4.0] Add dividing border to table rows

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/21661#issuecomment-413810617 .

### Summary of Changes
Adds a dividing border to all table rows

### Testing Instructions
Apply PR. Navigate to any table.

### Before
image

### After
image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9c8648a5bd8873c4aa68ff0ff55ea362344739ee<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21665">issues.joomla.org/tracker/joomla-cms/21665</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9c8648a5bd8873c4aa68ff0ff55ea362344739ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21665">issues.joomla.org/tracker/joomla-cms/21665</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
