### PR TITLE
[com_fields] Move the fields that are displayed "after content"

### PR DESCRIPTION
**Pull request by brianteeman**
this PR will move any field that is set to display "after content" to before any readmore link on a blog or featured article view

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a5e01385804ed736a9d680f3de9d57b269894fa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by zero-24** [comment]
Dont we break the current behavior with `onAfterDisplayContent` with that change?

**Comment by Bakual** [comment]
> Dont we break the current behavior with onAfterDisplayContent with that change?

I wouldn't say it "breaks" something, but it will change the appearance if someone has a plugin installed which triggers on that event.
For example the voting information would be shown before the readmore button now if it is set to that position.

**Comment by Open2logic** [comment]
Now is logical, is ok for UIX,  nothig after Readmore.

I hope in the future that custom fields can be displayed only in the complete article with a parameter option: After display, Before, display or After Read more.

**Comment by mbabker** [comment]
If, and IMO this is a big if, this PR is accepted it needs to be very well documented.  It WILL change the output on sites using the core layouts.

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on a5e01385804ed736a9d680f3de9d57b269894fa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
As @mbabker says this will change the output for current sites. I can't see a real need for doing so, setting it to needs review to get a bit more information and discuss this more <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by brianteeman** [comment]
I am not convinced this is the solution either but there is an issue to resolve somehow. See #15265 and #15319

**Comment by franz-wohlkoenig** [comment]
set Status on "Needs Review" cause of above Comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 32d69867b9b1d42da07671f95ab0a3d3f7b725a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 32d69867b9b1d42da07671f95ab0a3d3f7b725a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15277">issues.joomla.org/tracker/joomla-cms/15277</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request closed without merging**
