### PR TITLE
[4.3] Accessibility Features Plugin: choice of two icon images (Google Font)

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue #38832 .

### Summary of Changes

- Choice of two icon images (Google Font)
- Choice of a rectangular (default) or a circular shape image

### Testing Instructions

- Enable the 'System - Additional Accessibility Features' plugin
- Select the "Use Google Material Font"
- Test the different options, see the attached images
- Code review

### Actual result BEFORE applying this Pull Request

No option to choose an icon with a shape (Google Font)

### Expected result AFTER applying this Pull Request
pr_accessibility-2

pr_accessibility-3
pr_accessibility-4png

### Some notes

See links: 
- https://ranbuch.github.io/accessibility/
- https://ranbuch.github.io/accessibility/site/

It has not researched of the "package": "accessibility", "version": "3.0.17" is still correct.

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
@richard67 

Did I do something wrong when creating this PR ???
It concerns only size 3 files that I have modified for J4.3

**Comment by richard67** [comment]
@sandewt It looks as if your branch for this PR is not based on the 4.3-dev branch.

**Comment by sandewt** [comment]
@richard67 

I think so too. I probably didn't create this PR for 4.3 properly, which was the intention.
What is Wisdom? Shall I close this PR?

**Comment by chmst** [comment]
@drmenzelit what is the state of the plugin? This PR seems to be in conflict with the current state

**Comment by sandewt** [comment]
>  what is the state of the plugin? This PR seems to be in conflict with the current state

Something went wrong while creating this PR.

**Comment by sandewt** [comment]
Something went wrong while creating this PR.

**Pull request closed without merging**
