### PR TITLE
MailTemplate: Quote array key passed into the regex pattern

### PR DESCRIPTION
**Pull request by ManuelHu**
Pull Request for Issue (no issue). Found while doing code review.

### Summary of Changes
Currently, the array keys passed to `MailTemplate::replaceTags()` are directly used within the regular expression. This is prone to errors, if ever some array keys are used that contain special characters (e.g. `+`, `*`, ...).

Quoting the key should prevent some possible (future) weird behaviour, if an array key contains a regex control character. This should not create any b/c problems, as afaik no keys with special characters are currently defined/used. Also, regular expression control chars could not be used in a sensible way in this place anyways.

### Testing Instructions
* enable action log emails for the user component (in the settings of yxour personal account)
* perform some actions, e.g. loggin out and back again
* look at the sent emails

### Actual result BEFORE applying this Pull Request
it works (the email contains information and no placeholders)

### Expected result AFTER applying this Pull Request
it still works (no visble change to above)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 91c209648e7b265b281c370d8080f26edfac6d39<br /><br />Tested successfully in Joomla 4.2.10-dev of 19 March using PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40032">issues.joomla.org/tracker/joomla-cms/40032</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40032">issues.joomla.org/tracker/joomla-cms/40032</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by obuisard** [comment]
Thank you @ManuelHu for the PR!

**Pull request merged**
