### PR TITLE
[4.0] Fixing typehints in Smart Search Adapter.php

### PR DESCRIPTION
**Pull request by Hackwar**
This is a replacement for #26384. 

### Summary of Changes
Change typehints + unnamepsaced class usage to namespaced class usage

### Testing Instructions
Code reiew

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8b2507d76e23c13db73ef6f56fec055fd5754b50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33920">issues.joomla.org/tracker/joomla-cms/33920</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8b2507d76e23c13db73ef6f56fec055fd5754b50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33920">issues.joomla.org/tracker/joomla-cms/33920</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33920">issues.joomla.org/tracker/joomla-cms/33920</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
