### PR TITLE
Add viewport units options for modals

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue #10070 .

Based on idea by @RoterNagel about using viewport units for modals, and the proposal of @andrepereiradasilva to create special classes for viewport units.

This PR is full B/C as this one is not changing current behavior. It adds new optional options <code>modalWidth</code> and <code>bodyHeight</code> to be able to set viewport units in the modal constructor.
_Note: for old browsers with no viewport unit support, it will just displayed the modal as before._

The Options for modals are then these ones:
- <code>title</code> (string) : The modal title
- <code>backdrop</code> (mixed) : A boolean select if a modal-backdrop element should be included (default = true)
   The string 'static' includes a backdrop which doesn't close the modal on click.
- <code>keyboard</code> (boolean) : Closes the modal when escape key is pressed (default = true)
- <code>closeButton</code> (boolean) : Display modal close button (default = true)
- <code>animation</code> (boolean) : Fade in from the top of the page (default = true)
- <code>footer</code> (string) : Optional markup for the modal footer
- <code>url</code> (string) : URL of a resource to be inserted as an <code>iframe</code> inside the modal body
- <code>height</code> (string) : height of the <code>iframe</code> containing the remote resource
- <code>width</code> (string) : width of the <code>iframe</code> containing the remote resource
- NEW **<code>bodyHeight</code> (int) : Optional height of the modal body in viewport units (vh)**
- NEW **<code>modalWidth</code> (int) : Optional width of the modal in viewport units (vh)**
#### Summary of Changes
- Changes done on latest Staging (to get the previous modal changes already merged in 3.6.0-dev)
- New modal options: <code>modalWidth</code> and <code>bodyHeight</code>
- Add <code>jviewport</code> classes to <code>modals.joomla.less</code>
- Update <code>responsive-767px-max.joomla.less</code>
- Run generatecss
- Integrate new options in the modal layouts (with control for a correct vh value)
- Add those 2 new options in the <code>menuTypeModal</code> for test and demonstrate B/C

**Note:** i added viewport options here only for Menu Item Type select for testing purpose. If this PR is accepted, i will then be able to add this to other modals (already updated and merged, and the ones i'm working on and not yet improved). My goal is all modals reviewed for 3.6.0 ;-)
#### Testing Instructions
- Apply patch on latest <code>staging</code>
- Clean cache (to clean template.css in cache)
- Go to **menus** > **new menu item** > click to select a **Menu Item Type**
- Verify that now the modal is higher (<code>bodyHeight</code> 70vh) as expected in PR #10070 
- _Note: I have set <code>modalWidth</code> to 80vw as the default modal width was already 80% (and in this modal <code>menu-type</code>, seems to be a good width)_

**Before Patch**
Menu Item Type select modal before patch

**After Patch**
Menu Item Type select modal before patch with viewport units
- Test other modals (Batch, Messaging > Settings, ...) to confirm B/C, and nothing change for other modals where modalWidth and bodyHeight not specified.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 545a9a3099a47a7f472fc75001cfc0540452dc40<br /><br />Works as described.

Tested the new menu item type select modal with different window sizes and worked very good.
Tested the other modals (batch, my setting in messages, versions, article select, user notes, user select) and they work as before.

A very nice improvement!
+1 for this modals review for 3.6.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10388">issues.joomla.org/joomla-cms/10388</a>.</sub>

**Comment by andrepereiradasilva** [comment]
BTW also tested in Chrome and IE10

**Comment by JoomliC** [comment]
Note: for browser with no viewport unit support, it will just displayed the modal as before ;-)
(so full B/C)

**Comment by zero-24** [comment]
@brianteeman please add the 3.6.0 milestone here as we have it on the old PR.

**Comment by brianteeman** [comment]
@zero-24 no need to remind me on each one. I will review them all a few
times a day.

**Comment by zero-24** [comment]
Thanks! @brianteeman

**Comment by RoterNagel** [comment]
I have tested this item :white_check_mark: successfully on 545a9a3099a47a7f472fc75001cfc0540452dc40<br /><br />And you choose the menu type modal for testing :heart: :wink: 

Should I run a test via browserstack?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10388">issues.joomla.org/joomla-cms/10388</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 545a9a3099a47a7f472fc75001cfc0540452dc40<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10388">issues.joomla.org/joomla-cms/10388</a>.</sub>

**Comment by zero-24** [comment]
RTC based on tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10388">issues.joomla.org/joomla-cms/10388</a>.</sub>

**Comment by JoomliC** [comment]
@RoterNagel i didn't know what browserstack is, but now i know! ;-)
You can of course!

Thanks for testing!

**Comment by dgt41** [comment]
Great work @JoomliC Thank you!

**Comment by JoomliC** [comment]
Thanks @RoterNagel @andrepereiradasilva and @MATsxm for testing!

Thanks @dgt41 ! ;-)
Now, time to set it for many modals where needed! (just opened 2 PRs for 3 modals, other to come in the next days)

**Pull request merged**
