### PR TITLE
add dimensions to breadcrumb seperator

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #9919

Adds dimensions for the default breadcrumbs seperator image

### CODE REVIEW

**Comment by mbabker** [comment]
The quirk with this is if you aren't using the core image then you have to
hack the helper to set the right attribute values for your separator
image.  Or make JHtml::image() automagically parse the dimensions.

**Comment by brianteeman** [comment]
;) yes I realised that - still dont see the need for the dimensions on this type of image either

**Comment by brianteeman** [comment]
To be clear I hope this will be closed without merging I just did it to show @810

**Comment by 810** [comment]
I'm now adding also dimensions to our component:

````
$location = JUri::root() . $attachment->getUrl();
$data = getimagesize($location);
$width = $data[0];
$height = $data[1];

width="<?php echo $width ;?>" height="<?php echo $height ;?>"
````

**Comment by brianteeman** [comment]
MY question about your original issue still remains

**Comment by 810** [comment]
Yes, like Michael said, we need to JHtml::image() automagically parse the dimensions

This is needed for a w3c validation checks, or any other html checks like in the inspector from chrome (audit - ).

Now if you check a clean protostar template. he is showing a dimension notice to fix the height and width tag.

tests

**Comment by brianteeman** [comment]
Please add that to your issue report. #9919 
Just saying Improve without saying what should be improved is not helpful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9920">issues.joomla.org/joomla-cms/9920</a>.</sub>

**Comment by 810** [comment]
Text updated on the issue.

You can close this pr.

Your fix works, but when have custom image it will break the height and size.

**Comment by ggppdk** [comment]
Now in order to override,
- you need to place overriding image into specific folder of the frontend template which is not most most obvious to override
- but **overriding, seems to be disabled** ? because the $relative parameter is null aka evalutes to false ? (i have not tested)

Why not adding a **new parameter**
(and maybe this parameter is not needed at all because overriding is disabled ? so we can just go ahead and always use CSS ?):

**Separator type**:
- Image
- CSS based

Thus existing sites will not break, the 2nd option will add a < span > with a css class to make it inline block (+ RTL check to add extra class)
- the image will be added as background, and for some templates it can be a font-based image e.g. for protostar template CSS

To allow this to work for 3rd party templates, that do not add CSS for the class, we would need a default CSS ... to set the style of the arrow < span > box

but i am not sure in which file the  CSS should go so that it get loaded always, e.g. in "system.css"  or added from inside the HELPER using addStyleDeclaration() ? and anyone wanting to override would just prepend a **body** into the rule to make it of higher priority

**Comment by ggppdk** [comment]
@brianteeman 
Also i have just now noticed, function signature is:
```
public static function image($file, $alt, $attribs = null, $relative = false, $path_rel = false)
```

you have changed 4th parameter, but the **attribs** is the 3rd parameter

**Comment by andrepereiradasilva** [comment]
why not just use a utf8 character instead of images ....
example:
◄ = `&#9668;`
► = `&#9658;`
◂ =  `&#9666;`
▸ = `&#9656;`

And then you can add color or size in css.

See http://mcdlr.com/8/

**Comment by brianteeman** [comment]
Why not just close this as a non-issue ;)

On 15 April 2016 at 13:22, andrepereiradasilva <notifications@github.com>
wrote:

> why not just use a utf8 character instead of images ....
> example:
> ◄ = &#9668;
> ► = &#9658;
> ◂ = &#9666;
> ▸ = &#9656;
>
> And then you can add color or size in css.
>
> See http://mcdlr.com/8/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9920#issuecomment-210444605>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment]
Yes i think it is better to close this, it is not a bug, neither is too much of a problem as the image itself is too small to cause content repositioning on load

about my comments, i was just giving some feedback for anyone considering making another PR

**Pull request closed without merging**
