### PR TITLE
[4.0] Language Mail Templates

### PR DESCRIPTION
**Pull request by brianteeman**
When a content language has a flag a title is set for each image with the full language name.

But if a language is set not to have a flag then we get the SEF value instead of the flag but there is no title.

This simple PR adds the title in that situation.

To test
Create a multilingual site
Open one of the content languages and set the image value to none
go to the system menu and he mail templates
Hover over the images

After this PR all languages will display the title

flag

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7dca1dac3bb1131bdd6ad8fa7a4d98394cc6553f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27716">issues.joomla.org/tracker/joomla-cms/27716</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7dca1dac3bb1131bdd6ad8fa7a4d98394cc6553f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27716">issues.joomla.org/tracker/joomla-cms/27716</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27716">issues.joomla.org/tracker/joomla-cms/27716</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
