### PR TITLE
[4.4] Event argument setters use onSet callback, for existing events

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

The PR changes pre-processing methods from setFobar to onSetFoobar for existing event classes.

This is follow up for 
- https://github.com/joomla/joomla-cms/pull/41722

The PR can be merged only when that PR is accepted and merged.

### Testing Instructions

Code review.
Make sure all works as before.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
pretty sure we need documentation here and for the other pr, especially for the deprecated stuff

**Comment by HLeithner** [comment]
merged because it's the follow up pr of #41722 thanks

**Comment by laoneo** [comment]
Should the calls not be vice versa? That the deprecated method is calling the new one?

**Comment by Fedik** [comment]
When method onSetFoobar exists it will be called first and then fallback to setFoobar for b/c.
If we do deprecated method is calling the new one, then deprecated method will be never called

**Comment by laoneo** [comment]
I mean should the code not be like:
```
    public function setUser(User $value): User
    {
        return $this->onSetUser($value);
    }

    protected function onSetUser(User $value): User
    {
        return $value;
    }
```

Normally you deprecate a function and then in the function you forward to the new one. But perhaps I miss here something.

**Comment by Fedik** [comment]
> But perhaps I miss here something.

This:
> When method onSetFoobar exists it will be called first 

in your example `setUser` will never be called. Because `onSetUser` exists, and will be called first.

**Comment by laoneo** [comment]
Ok, don't have time to dig here deeper. I guess you know what you are doing. Looks all a bit contrary to what we do normally when we deprecate stuff, that's why I commented here.

**Pull request merged**
