### PR TITLE
[4.2] form placeholder

### PR DESCRIPTION
**Pull request by brianteeman**
make the font a little smaller and italics for the placeholder. This addresses a usability issue where it was not possible to visually determine a difference between placeholder text and input text

Pull Request for Issue #38816 .

### Testing Instructions
to test apply pr and then npm run build:css or use a prebuilt package

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Documentation Changes Required
none

### CODE REVIEW

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 4558e7a89c40fd3a9905d2d093f71d483e356aa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38827">issues.joomla.org/tracker/joomla-cms/38827</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4558e7a89c40fd3a9905d2d093f71d483e356aa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38827">issues.joomla.org/tracker/joomla-cms/38827</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38827">issues.joomla.org/tracker/joomla-cms/38827</a>.</sub>

**Review by crystalenka — APPROVED** [review]
Was asked to review from the UX side; this looks like a needed change to me, makes it more clear. Thank you Brian!

**Comment by laoneo** [comment]
Is this not needed on the front end as well?

**Comment by HLeithner** [comment]
thanks @brianteeman 
can you evaluate if it's needed for the Cassiopeia too as asked by @laoneo ?

**Pull request merged**
