### PR TITLE
Show location of cause of deprecation messages

### PR DESCRIPTION
**Pull request by MarkRS-UK**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/38137 .

### Summary of Changes
Add file and line reference to deprecation exception messages.

### Testing Instructions
Enable deprecated method calls logging (Admin panel -> global configuration -> logging)
Run just about any view in the back end.
View file /administrator/logs/deprecated.php to see reports of deprecated calls.

### Actual result BEFORE applying this Pull Request
Deprecation messages appear without any reference to location of the piece code causing the exception.

### Expected result AFTER applying this Pull Request
Deprecation messages contain a full file name and line number locating the cause of the exception.
Documentation Changes Required

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
There was a conflicting file due to the automatic conversion to psr12 code style standard. I've allowed myself to solve that.

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on a2a04e58a75e2fc711aafcaa42f494e763ac469b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38158">issues.joomla.org/tracker/joomla-cms/38158</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a2a04e58a75e2fc711aafcaa42f494e763ac469b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38158">issues.joomla.org/tracker/joomla-cms/38158</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38158">issues.joomla.org/tracker/joomla-cms/38158</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
