### PR TITLE
[4.0] Modifying com_actionlogs string

### PR DESCRIPTION
**Pull request by infograf768**
## Summary of Changes

To help translators and non-coders, replacing the confusing value

`COM_ACTIONLOGS_LOG_VERBS_LABEL="Verbs To Log"`
by 
`COM_ACTIONLOGS_LOG_VERBS_LABEL="HTTP Request Method"`

as both means the same.

### CODE REVIEW

**Comment by brianteeman** [comment]
Would it be even simpler for translators without the HTTP as thats not needed either in this context

COM_ACTIONLOGS_LOG_VERBS_LABEL="Request Method"

**Comment by infograf768** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

and French equivalent

https://developer.mozilla.org/fr/docs/Web/HTTP/M%C3%A9thode

Including HTTP is fine in all languages.

**Comment by alikon** [comment]
from https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

> HTTP defines a set of request methods to indicate the desired action to be performed for a given resource. Although they can also be nouns, these request methods are sometimes referred to as HTTP verbs.

don't forget that that text is only displayed if you switch on yes from **Log API Requests**

but i'll let you to find the best understandable words

**Comment by brianteeman** [comment]
HTTP should not be translated in any language and its a redundant word

**Comment by ceford** [comment]
Two comments:

As this is a multi-select field it needs to be plural, so "HTTP Request Methods"

The label above that reveals this field when set to Yes says "Log API Requests". So...

I suggest "Request methods to log" 

Being unfamiliar with the term 'Verbs' it makes more sense to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30758">issues.joomla.org/tracker/joomla-cms/30758</a>.</sub>

**Comment by infograf768** [comment]
Modified to `Request Methods To Log` as requested.

**Comment by joomlacorner** [comment]
I have tested this item :white_check_mark: successfully on 5bbf249516c46af3a60e7676fe6523e8c4442b05<br /><br />patch worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30758">issues.joomla.org/tracker/joomla-cms/30758</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 5bbf249516c46af3a60e7676fe6523e8c4442b05<br /><br />It looks fine on my screen. Putting HTTP at the front would have caused a space problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30758">issues.joomla.org/tracker/joomla-cms/30758</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30758">issues.joomla.org/tracker/joomla-cms/30758</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
