### PR TITLE
[4] missed prepared statement

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
use prepared statement

### Testing Instructions
code review
install/unistall modules

### Actual result BEFORE applying this Pull Request
works

### Expected result AFTER applying this Pull Request
works as before

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]
I can confirm by review that the code is right and the removed variable `$modID` is not used elsewhere.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 69c8edeb2b931cdf834f83670d89ec8ab4b0d1ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39108">issues.joomla.org/tracker/joomla-cms/39108</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by sandewt** [comment]
There are more (similar) missing prepared statements, eg:

\administrator\components\com_finder\src\Indexer\Adapter.php

```
$groups = implode(',', $user->getAuthorisedViewLevels()); // line 772:

...
->where($this->db->quoteName('link') . ' = ' . $this->db->quote($url))
...
->where($this->db->quoteName('access') . ' IN (' . $groups . ')');
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39108">issues.joomla.org/tracker/joomla-cms/39108</a>.</sub>

**Comment by richard67** [comment]
> There are more (similar) missing prepared statements, eg:

Possibly. But that could be done with another PR since that's in another file.

**Comment by alison-moore** [comment]
As a professional writer I can also share with you important and useful information and tips concerning outline of the research work.

The following tips and useful information I wanna share with you here, cause recently I have provided for my client [excel project help](https://cheap-papers.com/excel-homework-help.php) and this excel paper was to be made in research format and he asked me to provide him with information concerning research outline and judging the fact that it was quite recently I want to share some of them with you.

1. Choose a topic that is interesting to you and one that you can find enough information about. If you are not interested in the topic, it will be very difficult to write a good paper.

2. Do some preliminary research on your topic. This will help you focus your paper and choose a direction for your research.

3.Create an outline for your paper. This will help you organize your thoughts and information.

4. Write a draft of your paper. This will help you get your ideas down on paper and make sure that you have included all of the information that you need.

5. Edit your paper. This will help you make sure that your paper is clear and concise.

6. Submit your paper to a conference. This will help you get feedback on your paper and help you improve it.

When I conducted the excel work for the client I also followed the tips I share with you, the differences in that this work was also made using MS World utilite like MS Excel <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39108">issues.joomla.org/tracker/joomla-cms/39108</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 69c8edeb2b931cdf834f83670d89ec8ab4b0d1ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39108">issues.joomla.org/tracker/joomla-cms/39108</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39108">issues.joomla.org/tracker/joomla-cms/39108</a>.</sub>

**Comment by laoneo** [comment]
Thanks you!

**Pull request merged**
