### PR TITLE
Implementing "No Matching Results" in Categories modal

### PR DESCRIPTION
**Pull request by infograf768**
Similar patch as #7232, #7236, #7234, #7231 for Categories.
To test, install a basic multilingual site and set associations in the language filter plugin. Create at least one article category for each language (2 languages are enough).
Edit a category. Click on the Associations Tab. Select a category. The list of categories associated to that peculiar language display in a modal.

screen shot 2015-06-22 at 17 50 47

When filtering and if no results, the display is just empty instead of the usual message "No Matching Results"

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks. I saw the modal but didn't see where it was used. There is a module
modal I couldn't see in use as well.

**Comment by infograf768** [comment]
It is a "module" modal, not a "modules" modal and it does not propose a list comparable to the Modules Manager afaik.

Note: I think we could use the categories modal instead of the dropdown in many places btw. Would be easier to choose categories from the modal as we can filter.

**Comment by brianteeman** [comment]
I couldnt see where the module one is used.

The modal is definitely better that the select list especially on larger
sites

(Sent from phone -apologies for tyoos)

**Comment by brianteeman** [comment]
This PR works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7244">issues.joomla.org/joomla-cms/7244</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you, @infograf768!

**Comment by zero-24** [comment]
RTC to match the status on github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7244">issues.joomla.org/joomla-cms/7244</a>.</sub>

**Comment by infograf768** [comment]
@brianteeman 
>I couldnt see where the module one is used.

It is used when editing a Menu item => Module Assignment=> Click on a module name in the list.

**Comment by brianteeman** [comment]
@infograf768 ok thanks - as this one can only ever display a module the update isnt required

**Comment by Kubik-Rubik** [comment]
Thank you once again @infograf768! Merged.

**Pull request closed without merging**
