### PR TITLE
[4.0][api][com_users]  add groups and levels entrypoint

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #30203 .

### Summary of Changes
added 2 new entrypoint for com_users

- levels
- groups

### Testing Instructions
for list 
`{{base_url}}api/index.php/v1/users/groups`
`{{base_url}}api/index.php/v1/users/levels`

 for item
`{{base_url}}api/index.php/v1/users/groups/{id}`
`{{base_url}}api/index.php/v1/users/levels/{id}`

### Actual result BEFORE applying this Pull Request
N/A

### Expected result AFTER applying this Pull Request
levels

Screenshot from 2020-07-28 18-47-05

level
Screenshot from 2020-07-28 18-48-08

groups
Screenshot from 2020-07-28 18-48-41

group

Screenshot from 2020-07-28 18-49-19

### Documentation Changes Required

yes

### CODE REVIEW

**Comment by chetanmadaan** [comment]
I have tested this item :white_check_mark: successfully on e187ab0dc25dd3ede6ee961931a7f31f32dc0c2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30210">issues.joomla.org/tracker/joomla-cms/30210</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e187ab0dc25dd3ede6ee961931a7f31f32dc0c2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30210">issues.joomla.org/tracker/joomla-cms/30210</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30210">issues.joomla.org/tracker/joomla-cms/30210</a>.</sub>

**Comment by wilsonge** [comment]
I've merged this one to the 4.1 branch. Generally I'm not against adding these to the 4.0-dev branch. However because the API is new and not security tested yet I'm slightly concerned about allowing editing this part of Joomla. I'm going to play safe and specifically move these two endpoints to the 4.1 branch https://github.com/joomla/joomla-cms/commit/c752e2eeb60dd39e7b59edb8161bb0fc25dba414

**Pull request closed without merging**
