### PR TITLE
[4.0] Error in Update Notification plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25388.

### Summary of Changes

Removes incorrect table prefix.

### Testing Instructions

Code review or install older alpha version. Trigger update notification plugin.

### Expected result

No errors.

### Actual result

>Call to a member function getRootId() on bool 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by sakiss** [comment]
I have tested this item successfully on 890233a9c6369484c95cea31c2108b3f4ae67d0f

**Comment by ghost** [comment]
@sakiss  please mark your test **as successfully** (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by Quy** [comment]
I got different errors under `Components > Joomla! Update`.

> Notice: Undefined property: Joomla\CMS\Updater\Update::$downloadurl in \administrator\components\com_joomlaupdate\tmpl\joomlaupdate\default_update.php on line 49

> Notice: Trying to get property '_data' of non-object in \administrator\components\com_joomlaupdate\tmpl\joomlaupdate\default_update.php on line 49

**Comment by richard67** [comment]
And I could not reproduce issue #25388 for the real test.

**Comment by SharkyKZ** [comment]
@Quy issue unrelated to this PR.

@richard67 Hm, I can't either. Updates are not found so the erroneous code is not triggered. Which version did you use?

**Comment by SharkyKZ** [comment]
PR #25412 for removing hardcoded ID from the plugin. But that won't help testing this on older versions.

**Comment by sakiss** [comment]
@richard67 @Quy You need to have an older version (e.g. alpha 8) and have configured the Joomla Update component to perform automatic updates, based on the update stream given for J4.

The error is generated once a new version is found.

**Comment by sakiss** [comment]
@SharkyKZ Though your PR does not solve the problem in the first place, since Table::getInstance(), returns Table or boolean. In the 2n case the call of getRootId() is invalid

**Comment by SharkyKZ** [comment]
@sakiss are you still getting the error? `Joomla\CMS\Table\Table::getInstance()` returns `false` only when the table class is not found. It's not found before patch because incorrect prefix is passed. After patch it should always be found (it's a core table).

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
