### PR TITLE
Code style. Remove space. plg_extension_joomla

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
- Removed space.

### Testing Instructions
- Code review. It's obvious.

### Additional comment
- The same in Joomla 4. I don't know if we need an additional pr for it(?)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c04e31b45809cd84e2255d78d0d4937e98564e31<br /><br />Code review.

@wilsonge Does that need a PR for 4.0-dev, too, or will it later be merged into 4.0-dev anyway?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25079">issues.joomla.org/tracker/joomla-cms/25079</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c04e31b45809cd84e2255d78d0d4937e98564e31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25079">issues.joomla.org/tracker/joomla-cms/25079</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25079">issues.joomla.org/tracker/joomla-cms/25079</a>.</sub>

**Comment by Quy** [comment]
Not necessary as it will be merged later.

**Comment by wilsonge** [comment]
Thanks! As quy said. everything in staging will end up in j4

**Pull request merged**
