### PR TITLE
s/TJoomla/Joomla

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/TJoomla/Joomla

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dd8a883f981fc2aa64596acae381026956ce2b76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38481">issues.joomla.org/tracker/joomla-cms/38481</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dd8a883f981fc2aa64596acae381026956ce2b76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38481">issues.joomla.org/tracker/joomla-cms/38481</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38481">issues.joomla.org/tracker/joomla-cms/38481</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Pull request closed without merging**
