### PR TITLE
Remove unnecessary  $params->get('show_author')

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25958

### Summary of Changes
- Remove unnecessary condition for article title.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Could you also remove duplicate `if ($params->get('show_title'))` check 2 lines below?

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 4b5fd6d50885414c7514f5ba015084ae4edc5459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25964">issues.joomla.org/tracker/joomla-cms/25964</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4b5fd6d50885414c7514f5ba015084ae4edc5459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25964">issues.joomla.org/tracker/joomla-cms/25964</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25964">issues.joomla.org/tracker/joomla-cms/25964</a>.</sub>

**Comment by HLeithner** [comment]
Thank you for cleaning up the templates.

**Pull request merged**
