### PR TITLE
Add tests for JLanguageMultilang

### PR DESCRIPTION
**Pull request by wilsonge**
As per the doc block I've typecast the result to be a boolean as it was returning the string 0 on false and 1 on true for the enabled state of the plugin (as these are the values stored in the database). Currently you get true and false in the frontend and 0 and 1 in the backend.
## Testing

In the backend ensure that the modal views when you are selecting a single item in the menu show everything properly

Replaces https://github.com/joomla/joomla-cms/pull/6443

### CODE REVIEW

**Comment by mbabker** [comment]
Think you could redo this with mock data injection in a similar manner to what we did with the Framework application package's tests so we can start cutting some of the dependencies on global manipulation?

**Comment by wilsonge** [comment]
Nope - but I'll try anyhow :D

**Comment by mbabker** [comment]
Copy/paste is your friend :wink:

**Comment by wilsonge** [comment]
```Class "JApplicationSite" is declared "final" and cannot be mocked.```

**Comment by wilsonge** [comment]
I've pushed the code to mock the admin application tho

**Comment by roland-d** [comment]
Merged on review.

**Pull request merged**
