### PR TITLE
Revision to Language String - Article 3 Intro Text

### PR DESCRIPTION
**Pull request by imanickam**
Revise the language string PLG_SAMPLEDATA_BLOG_SAMPLEDATA_CONTENT_ARTICLE_3_INTROTEXT to reflect the number of links set in the menu item Blog.  In the menu item Blog, the option # Links is set to 2.  Where as in the article, it is mentioned as 4.

Pull Request for Issue # .

**### Summary of Changes**
In the Sample Data's Article 3, the number of links set is shown as 4 where as in the menu item Blog it is set as 2.

**### Testing Instructions**

(a) Create a new installation of Joomla!

(b) Log into the Back-end

(c) In the Control Panel click on the link "Blog Sample data" (that is in the module titled "SAMPLE DATA"

(d) After the installation of the Sample Data is successful, open the menu item "Blog" (that is in the Menu titled "Main Menu Blog") for Edit and go to the tab "Blog Layout". Notice that the value shown for the option "# Links" is set to 2 (Two).

sample_data_blog_menu_item_no_of_links_as_2

(e) See the new site created in a separate browser tab

(f) Click on the Link "Blog" and scroll to see the screen to see the contents of the blog.  Notice that in the article titled "About your home page", the number of links is mentioned as 4.

sample_data_blog_page_showing_no_of_links_as_4

**### Expected result**

In the article titled "About your home page" the number of link must specify the value 2 - NOT 4.

sample_data_blog_page_showing_no_of_links_as_2

**### Actual result**

See the step (f) in the section ### Testing Instructions

### CODE REVIEW

**Comment by brianteeman** [comment]
If this is indeed incorrect then it needs changing in the sample_blog.sql files as well.

**Comment by imanickam** [comment]
Good point Brian.

I checked the file sample_blog.sql \installation\sql\mysql and found this inconsistency.  Created a separate PR (https://github.com/joomla/joomla-cms/pull/17929) for that.

**Comment by brianteeman** [comment]
but did you check to see if it is wrong when installed that way? the params might be correct in the installation sql files and it is the params that are wrong in the module install method (about to bpoard a plane so i cant check myself)

**Comment by imanickam** [comment]
> but did you check to see if it is wrong when installed that way? the params might be correct in the installation sql files and it is the params that are wrong in the module install method (about to bpoard a plane so i cant check myself)

Yes, I did.  An image of the menu item created by the system is attached (Step (d) of Testing Instructions.)

**Detailed information:**

Please note that the Number of Links mentioned is Two (`"num_links":2`) in the following objects.

(i) Content of the column _params_ in the table __menu_.  Menu Item created by the installation of Sample Data using the plugin "Sample Data - Blog":

`{"layout_type":"blog","show_category_title":0,"num_leading_articles":4,"num_intro_articles":0,"num_columns":1,"num_links":2,"multi_column_order":1,"orderby_sec":"rdate","order_date":"published","show_pagination":2,"show_pagination_results":1,"show_category":0,"info_bloc_position":0,"show_publish_date":0,"show_hits":0,"show_feed_link":1,"menu_text":1,"show_page_heading":0,"secure":0}`

(ii) Content of the column _params_ in the table __menu_.  Menu Item created by the installation of Blog Sample Data while installing Joomla!:

`{"layout_type":"blog","show_category_title":"0","show_description":"","show_description_image":"","maxLevel":"","show_empty_categories":"","show_no_articles":"","show_subcat_desc":"","show_cat_num_articles":"","page_subheading":"","num_leading_articles":"4","num_intro_articles":"0","num_columns":"1","num_links":"2","multi_column_order":"1","show_subcategory_content":"","orderby_pri":"","orderby_sec":"rdate","order_date":"published","show_pagination":"2","show_pagination_results":"1","show_title":"","link_titles":"","show_intro":"","show_category":"0","link_category":"","show_parent_category":"","link_parent_category":"","info_bloc_position":"0","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"0","show_item_navigation":"","show_vote":"","show_readmore":"","show_readmore_title":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_hits":"0","show_noauth":"","show_feed_link":"1","feed_summary":"","menu-anchor_title":"","menu-anchor_css":"","menu_image":"","menu_text":1,"page_title":"","show_page_heading":0,"page_heading":"","pageclass_sfx":"","menu-meta_description":"","menu-meta_keywords":"","robots":"","secure":0}`


(iii) Content in the file _sample_blog.sql_ that is available in the directory _\installation\sql\mysql_

`(101, 'mainmenu', 'Home', 'home', '', 'home', 'index.php?option=com_content&view=category&layout=blog&id=9', 'component', 1, 1, 1, 22, 0, '0000-00-00 00:00:00', 0, 1, '', 0, '{"layout_type":"blog","show_category_title":"0","show_description":"","show_description_image":"","maxLevel":"","show_empty_categories":"","show_no_articles":"","show_subcat_desc":"","show_cat_num_articles":"","page_subheading":"","num_leading_articles":"4","num_intro_articles":"0","num_columns":"1","num_links":"2","multi_column_order":"1","show_subcategory_content":"","orderby_pri":"","orderby_sec":"rdate","order_date":"published","show_pagination":"2","show_pagination_results":"1","show_title":"","link_titles":"","show_intro":"","show_category":"0","link_category":"","show_parent_category":"","link_parent_category":"","info_bloc_position":"0","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"0","show_item_navigation":"","show_vote":"","show_readmore":"","show_readmore_title":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_hits":"0","show_noauth":"","show_feed_link":"1","feed_summary":"","menu-anchor_title":"","menu-anchor_css":"","menu_image":"","menu_text":1,"page_title":"","show_page_heading":0,"page_heading":"","pageclass_sfx":"","menu-meta_description":"","menu-meta_keywords":"","robots":"","secure":0}', 43, 44, 1, '*', 0),`

**Additional Information:**

In fact, whether it is set as Two or Four, it does not help the new user.  The reason being, in the Blog sample data there are only four articles for/in the category 'blog'.  With the Number of Leading Articles (`num_leading_articles`) set to Four, the user will not even see the links.  

The change has been suggested to reflect what is set in the option "_# Links_".

IMHO, it would be better to change the value of the option "_# Leading Articles_" to Two (from the present value of Four).  This change would help the new users to see both the articles and the links.  Of course, the sample data has to be changed to reflect the change.

**Comment by infograf768** [comment]
> IMHO, it would be better to change the value of the option "# Leading Articles" to Two (from the present value of Four). This change would help the new users to see both the articles and the links. Of course, the sample data has to be changed to reflect the change.

Agree.

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on c6f15b1d840636833267a1ae5b13993879dbe13b<br /><br />After installing Blog-Sample Data using applied Patch got "(…) the next two oldest articles. (…)".

But: As i can't uninstall PR #17929 i marke for sure this Test as unsuccessfully. Also Test Instructions (how to install Sample Data) are not up to date so maybe this PR needs updates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17926">issues.joomla.org/tracker/joomla-cms/17926</a>.</sub>

**Comment by Quy** [comment]
Fixed in PR #19357<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17926">issues.joomla.org/tracker/joomla-cms/17926</a>.</sub>

**Pull request closed without merging**
