### PR TITLE
WebDriver needs name for iframe

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### As per request on #7207

What is this?

This adds one more parameter (`name=""`) to the iframe tag. Needed for automation testing

### CODE REVIEW

**Comment by zero-24** [comment]
@dgt41 any way to easy test it? e.g. where the layout is called?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7211">issues.joomla.org/joomla-cms/7211</a>.</sub>

**Comment by dgt41** [comment]
@zero-24 Sorry should mention testing:

#### To Test this 
go to http://localhost/administrator/index.php?option=com_menus&view=menus

and click on any of the Linked modules

Inspect the source page and verify that a tag `name="[the title of the modal]"` is inside iframe tag

**Comment by brianteeman** [comment]
Tested and confirmed that `name` did not exist in the iframe before the patch and does exist after the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7211">issues.joomla.org/joomla-cms/7211</a>.</sub>

**Comment by smz** [comment]
Tested OK.
We have 2 tests: RTC?

**Comment by zero-24** [comment]
RTC. Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7211">issues.joomla.org/joomla-cms/7211</a>.</sub>

**Comment by javigomez** [comment]
thank @dgt41 :smile: and all for testing

**Comment by javigomez** [comment]
Tested with selenium and works very nice, see: http://www.youtube.com/watch?v=Snm2lE81Ahg

But I'm wondering if we should move this:

```

'name'  => $params['title']
```

into this:
```
if (isset($params['title']))
 {
 	$iframeAttributes['name'  => $params['title']
 }
```

Because according to this (source: http://www.w3.org/TR/html-markup/iframe.html):

capture 2015-06-01 at 11 16 13
 
is responsibility of the layout file to not create a empty name: `name=""` in case a title is not passed to the layout, because it would be violating the iframe specification.


what do you think?

**Comment by dgt41** [comment]
In theory you should that, but 
1. Bootstrap modal are broken (visually) if you don’t pass a title
2. We do pass ALWAYS a title for core components

But the check will not hurt I guess, 3PD might do something different

**Comment by smz** [comment]
@dgt41: if you do, I'm read for re-testing...

**Comment by smz** [comment]
@dgt41, actually with the modal you suggested for testing (/administrator/index.php?option=com_menus&view=menus + Linked Modules) I don't see the `name` attribute. Also, when I previously tested, I'm quite sure it was `name=""`, but I thought it was OK...

**Comment by smz** [comment]
... hold on! I activated the wrong patch...!!! sorry!

**Comment by smz** [comment]
#test confirmed OK: iframe now has `name="Edit module settings"`

Sorry for the confusion...

**Comment by smz** [comment]
ehmm... why this PR has the `Unit/SystemTests` label?

**Comment by dgt41** [comment]
Thanks Sergio,
Is needed for selenium (testing)

**Comment by smz** [comment]
ah! OK!!! tnks!

**Comment by javigomez** [comment]
Not skilled in accessibility but check this:

```
The title attribute is not interchangeable with the name attribute. The title labels the frame for users; the name labels it for scripting and window targeting. The name is not presented to the user, only the title is.
```

**Comment by dgt41** [comment]
@javigomez does `$iframeAttributes['name']  => 'Modal - ' . $params['title'];` pass your accessibility tests?

**Comment by Kubik-Rubik** [comment]
@dgt41 @javigomez So, what is the state of this PR? Do we need a change or can we merge this?

**Comment by dgt41** [comment]
@Kubik-Rubik Victor I have no idea. @javigomez made a post that there was an accessibility error if name is same as the title of the iframe. I proposed to suffix something to the title, but then Javier removed that post, so honestly I have no clue 😃

**Comment by smz** [comment]
hmm.... Reading https://developer.mozilla.org/en/docs/Web/HTML/Element/iframe#name-attribute

> name
> A name for the embedded browsing context (or frame). This can be used as the value of the target attribute of an `<a>` or `<form>` element, or the formtarget attribute of an `<input>` or `<button>` element.

It doesn't seems that equating it to `title` is a good choice...

**Comment by dgt41** [comment]
@Kubik-Rubik Victor since ther is no response from @javigomez I will suggest to change the milestone to 3.5.0

**Comment by javigomez** [comment]
Sorry folks, I missed the notifications here. I was checking the accessibiltiy documentation (witch I'm not experienced) and from what I could see the current pull accomplish what is expected. And it allows us to work with iFrames in system tests witch is the reason why we oppened this issue https://github.com/joomla/joomla-cms/issues/7207.

So for me we are good to go.

Thanks all ^_^

**Comment by dgt41** [comment]
Thanks @javigomez 
@Kubik-Rubik ditch my last comment, you can merge this for 3.4.4 😃

**Comment by smz** [comment]
So, if the iframe title is "Test iframe", do you expect this to be a **valid** "*... value of the target attribute of an &lt;a&gt; or &lt;form&gt; element*"?

**Comment by smz** [comment]
For reference:

values for the *target* attribute of an &lt;a&gt; or &lt;form&gt; element can be:

- **_blank** (*Opens the linked document in a new window or tab*)
- **_self** (*Opens the linked document in the same frame as it was clicked. This is default.*)
- **_parent** (*Opens the linked document in the parent frame*)
- **_top** (*Opens the linked document in the full body of the window*)
- **framename** (*Opens the linked document in a named frame*) Must start with an alpha character and can contain hyphen(-), underscore(_), colon(:)

**Comment by Kubik-Rubik** [comment]
@smz So, what is your suggestion how to do it right? Should we apply a filter on the title to get a valid name?

**Comment by dgt41** [comment]
@Kubik-Rubik I guess the easiest thing here would be `$iframeAttributes[’title’]` instead of `$iframeAttributes['name']`

**Comment by smz** [comment]
Sorry, Victor, I'm on vacation and I'm not even sure I'll be willing to contribute to Joomla again when I'll be back: I'm afraid I've fought too many uphill fights to feel comfortable contributing.

But yes, I think a filter or "transforming function" to enforce  the rules of the game is needed.

Regards,

Sergio

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request closed without merging**
