### PR TITLE
[minor fixes] modal module edition

### PR DESCRIPTION
**Pull request by cyrez**
A few minor fixes for modal module edit (in menu item edition)
#### Summary of Changes
- Fix Close button not handling module edit close button (after close of the modal, the module was locked)
- Fix Tooltip placement (truncated at top)
- Add Container for iframe content
- Allow close only if click on Close or Save&Close buttons (to prevent accidental close while editing)
#### Testing Instructions

Before apply the patch:
- Go to menus, and open one menu item
- Click on one of the module in "Module Assignment" tab, to open the module edition
- Then check Tooltip for title (truncated)
- Then click with changing nothing, on the bottom CLOSE button of the modal
- Go to Modules Manager : the module is locked
  Example of "close" button issue with module named here "Archived Articles"
  capture d ecran 2016-05-08 a 16 27 14
  capture d ecran 2016-05-08 a 16 27 57

Apply patch, and : 
- verify tooltip placement
- test as above, and check that now the module is not locked (the module edition was well closed)

### CODE REVIEW

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 4d6a9f50cc2ff799542bb5173d0e08758e373a27<br /><br />Followed the test instructions and works exactly as described, nice tooltip on the title and no lock on module after applying this patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10317">issues.joomla.org/joomla-cms/10317</a>.</sub>

**Comment by JoomliC** [comment]
Thanks for testing @BurtNL but test reset as i've just updated this PR with the same fix for this issue : https://github.com/joomla/joomla-cms/pull/10292#issuecomment-217729874 ;-)

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 8f483528ac6be78ef7b55c472a4c9cee221651d6<br /><br />Tested again with this updated patch.
Followed the test instructions and works exactly as described, nice tooltip on the title and no lock on module after applying this patch.
And the modal can now only be closed via the buttons. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10317">issues.joomla.org/joomla-cms/10317</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 8f483528ac6be78ef7b55c472a4c9cee221651d6<br /><br />Works as described - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10317">issues.joomla.org/joomla-cms/10317</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8f483528ac6be78ef7b55c472a4c9cee221651d6<br /><br />Solves the issues and works as described. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10317">issues.joomla.org/joomla-cms/10317</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10317">issues.joomla.org/joomla-cms/10317</a>.</sub>

**Pull request merged**
