### PR TITLE
Joomla 4.0: Move legacy tables to cms tables

### PR DESCRIPTION
**Pull request by Hackwar**
This PR moves the JTable classes from the /libraries/legacy folder to /libraries/cms and undeprecates the JTableContent class. I doubt that there will be any UCM in the forseeable future. When it should one day be implemented, we can still deprecate that class again. But until then...

### CODE REVIEW

**Comment by wilsonge** [comment]
Would it not be better to move these classes to their respective components rather than the global libraries folder?

**Comment by Hackwar** [comment]
Yes and no, these classes are used not only in their respective component, but all over the place and moving them to their respective component would require all third party extensions to add that folder to the JTable include paths. In order to not change for the sake of change, I would keep it in the libraries folder.

**Comment by mbabker** [comment]
Another way to look at it is what tables would be considered part of the "core" data model?  Content's pretty specific but the others are part of the global app.

**Comment by Hackwar** [comment]
I'm not saying that I disagree with you that some of these tables belong to their respective component. It is just that I thought the general consensus was to not change for changes sake. This is a change that I consider to be a nice-to-have-but-not-essential, so that in order to keep the change list shorter I wouldn't touch this.

**Comment by wilsonge** [comment]
For the menu I'd put it in com_menu, for content, com_content, for module com_modules.... I mean I'm not fixed on it. But I'd assume that was the idea behind them going into legacy

**Comment by wilsonge** [comment]
I'm not set on that however. If you both think moving them to libraries is better - let's go with it :)

**Comment by mbabker** [comment]
If I wanted to be disruptive I'd move `JTableContent` to the component and leave the rest in the libraries.  But that's being disruptive for minimal gain.

With the current data model in core, the concepts of categories, menus, and modules are all global things and are not isolated to a single component (their management is exposed through a component though).  So those table classes are rightfully part of the libraries.

**Pull request merged**
