### PR TITLE
[4.3] Updating version to 4.3.0-dev

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says.

### CODE REVIEW

**Comment by brianteeman** [comment]
Don't you need to change this as well ?

https://github.com/joomla/joomla-cms/blob/23bb791961b5cd666bd2e24b3058113e13a761af/libraries/src/Version.php#L81

**Comment by Hackwar** [comment]
Yes, seems like my manual editing isn't the way to go. I've opened this PR mainly to be a reminder and to fix another issue. Most likely we'll simply close this PR.

**Comment by zero-24** [comment]
> Don't you need to change this as well ?

technically no I set mine just with the first RC but when there is a codename already defined go for it. Usually the version numbers should be updated using the build/bump.php script that will help here to update everything correctly and we dont miss anything.

**Comment by wojsmol** [comment]
For the version bump we have https://github.com/joomla/joomla-cms/blob/4.3-dev/build/bump.php witch supports also changing of codename.

//edit as mention by Tobias

**Comment by zero-24** [comment]
Done here on behalf of the Release Leads: https://github.com/joomla/joomla-cms/commit/0afad92f99cf861734c9adb96653b04f9b7e3018

**Pull request closed without merging**
