### PR TITLE
[4.0] Exclude tab workflow if workflow is not enabled

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31324  .

### Summary of Changes
Exclude tab workflow in category edit, if workflow is not enabled for content

### Testing Instructions
See #31324, switch on and off workflow in content options (integration)

### Actual result BEFORE applying this Pull Request
Tab workflow in categotry is always visible

### Expected result AFTER applying this Pull Request
Tab workflow in categories is ony visible if wirkflow is aneabled 

### Documentation Changes Required
no

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This is wrong as already explained in https://github.com/joomla/joomla-cms/pull/30345.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4bd38d73410348fe55d3c5c4eca3d8a6cc5e8b5b<br /><br />Tested successfully in Beta6-dev of 10 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 4bd38d73410348fe55d3c5c4eca3d8a6cc5e8b5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by chmst** [comment]
@SharkyKZ, you are right, I have chanched the code. 
@toivo , @ChristineWk  please could you repeat your tests?

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d923d37098cdac753d9cd21c04c5fbe3f669a6d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on d923d37098cdac753d9cd21c04c5fbe3f669a6d3<br /><br />When workflows is turned off in Content - Options - Integration, creating a new category fails with the warning:
Field required: Workflows
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ChristineWk** [comment]
I have not tested this item.<br /><br />Confirmed.
Test reverted.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ChristineWk** [comment]
screen shot 2020-11-10 at 16 09 34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by pranotiTechjoomla** [comment]
I have tested this item :red_circle: unsuccessfully on d923d37098cdac753d9cd21c04c5fbe3f669a6d3<br /><br />I have tested this item 🔴 unsuccessfully on d923d37

When workflows is turned off in Content - Options - Integration, creating a new category fails with the warning:
Field required: Workflows<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ashvini77** [comment]
I have tested this item :red_circle: unsuccessfully on d923d37098cdac753d9cd21c04c5fbe3f669a6d3<br /><br />https://tinyurl.com/y33g4ppc

Getting "Call to undefined method" error on category page after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ashvini77** [comment]
screen shot 2020-12-05 at 07 39 16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 467eda64054635184289369ea9eae5f18268601f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 467eda64054635184289369ea9eae5f18268601f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by bembelimen** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31374">issues.joomla.org/tracker/joomla-cms/31374</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by SharkyKZ** [comment]
This is still wrong.

**Comment by chmst** [comment]
@SharkyKZ thanks for commenting, but could you please explain?

**Comment by wilsonge** [comment]
I suspect that sharky is expecting the object to be removed from the form in the model rather than being ignored from rendering

**Comment by joomdonation** [comment]
Something wrong causes by this PR. Try to edit a category from com_banners, got this error message:

`Call to undefined method Joomla\Component\Banners\Administrator\Extension\BannersComponent::getCategoryWorkflowContext()`

**Pull request merged**
