### PR TITLE
Make HTML structure consistent for Joomla.renderMessages() (Fix #5602)

### LINKED ISSUE #5602: System message: wrong html structure created by javascript Joomla.renderMessages function
#### Steps to reproduce the issue
- go to forgot password page
- press submit without entering anything

The javascript validation displays an erorr with incorrect HTML structure:

#### Expected result

< div id="system-message-container">
< div id="system-message">
< div class="alert alert-error">

#### Actual result

< div id="system-message-container">
< div id="system-message" class="alert alert-error">

#### System information (as much as possible)

Joomla 3.3.6

#### Additional comments

The structure is defined in two places and should be identical:

- media\system\js\core-uncompressed.js
- layouts\joomla\system\message.php

### PR DESCRIPTION
**Pull request by mbabker**
The original issue report noted an incorrect HTML structure based on the PHP based rendering.  Since the initial report, the JavaScript handling has changed and the inner div with the `system-message` ID removed.  This PR should make the HTML rendered by the JS consistent with the PHP layout.
### Test Instructions

Honestly, I don't remember where in Joomla we render messages by JavaScript.  But, the rendered HTML should be consistent with the HTML in the layout file specified in the initial issue.

### CODE REVIEW

**Comment by Bakual** [comment]
I'd say we use it in the CMS Installation and maybe with the JavaScript form validating

**Comment by zero-24** [comment]
tested successfull.

#### without the patch 
screen shot 2015-06-27 at 16 24 49

#### with the patch
screen shot 2015-06-27 at 16 24 48


### How I test

- go to forgot password page
- press submit without entering anything
- see the sourcecode (using the Browser developer tools)
- see the `without patch` structure
- apply the patch
- clear the cache (!!)
- go to forgot password page
- press submit without entering anything
- see the sourcecode (using the Browser developer tools)
- see the `with patch` structure<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7278">issues.joomla.org/joomla-cms/7278</a>.</sub>

**Comment by jwaisner** [comment]
@test 

Test successful with patch. Functionality remains and code change implemented.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7278">issues.joomla.org/joomla-cms/7278</a>.</sub>

**Comment by zero-24** [comment]
RTC :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7278">issues.joomla.org/joomla-cms/7278</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @mbabker! Merged.

**Pull request closed without merging**
