### PR TITLE
Fix Help URLs and update to Help38

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #19149.

### Summary of Changes
Remove `?amp;` from Help URLs and update to Help38

### Testing Instructions
Install PR.
Delete `configuration.php`.
Go to the front end to reinstall Joomla.
Install `Test English (GB) Sample Data`.
Go to front end.
Under `All Modules`, click `Smart Search`.
Click `Help` in the article.

### Expected result
`https://help.joomla.org/proxy/index.php?keyref=Help38:Extensions_Module_Manager_Smart_Search`

### Actual result
`https://help.joomla.org/proxy/index.php?amp;keyref=Help31:Extensions_Module_Manager_Smart_Search`

### CODE REVIEW

**Comment by brianteeman** [comment]
If your going to correct it then let's have the correct url with at least 38  not 31:)

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 17075bee7c1bf83e9209c8755430271d3ab65446<br /><br />Wrong Link stay: `https://help.joomla.org/proxy/index.php?amp;keyref=Help31:Extensions_Module_Manager_Smart_Search`

Uninstalling PR give:
bildschirmfoto 2017-12-27 um 07 50 46

### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19181">issues.joomla.org/tracker/joomla-cms/19181</a>.</sub>

**Comment by Quy** [comment]
You will have to reinstall Joomla. Testing instructions updated.

**Comment by ghost** [comment]
I tested first in installed 3.8.4 and got wrong URL. Then i installed a fresh staging with same Result (wrong URL).

**Comment by Quy** [comment]
Please follow testing instructions.

**Comment by ghost** [comment]
>  Reinstall Joomla.

means "Joomla Update > Reinstall Joomla Core files"?

**Comment by Quy** [comment]
No. Once the configuration file is deleted, access the front end which will force an installation.

**Comment by ghost** [comment]
- patch installed
- configuration.php deleted
- copy "Installation"-Folder from downloaded staging to Joomla3-Folder
- open Frontend and reinstall Joomla

Same Result: Wrong Link `https://help.joomla.org/proxy/index.php?amp;keyref=Help31:Extensions_Module_Manager_Smart_Search`

**Comment by mbabker** [comment]
> copy "Installation"-Folder from downloaded staging to Joomla3-Folder

This is the part you're messing up.  You need the installation folder from this PR, not from staging (staging has the bad URL, this PR has the good one).

Download the ZIP from https://github.com/Quy/joomla-cms/tree/helpurl and install that.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 17075bee7c1bf83e9209c8755430271d3ab65446<br /><br />Thanks for Help @Quy @mbabker <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19181">issues.joomla.org/tracker/joomla-cms/19181</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 17075bee7c1bf83e9209c8755430271d3ab65446<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19181">issues.joomla.org/tracker/joomla-cms/19181</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
