### PR TITLE
Installation host strings

### PR DESCRIPTION
**Pull request by brianteeman**
As mentioned in #11881 this PR updates the two strings referring to database host and usernames

nfh4

### CODE REVIEW

**Comment by infograf768** [comment]
@maintainers
If this is merged, TTs should be informed ASAP in order to get new installation ini files before beta.

**Comment by brianteeman** [comment]
Its not a new string and its not a massive problem if they dont update. But of course the quicker its tested the more time there is

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e16a19d0a72420d642326b542b30c27ab88428c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11886">issues.joomla.org/joomla-cms/11886</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e16a19d0a72420d642326b542b30c27ab88428c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11886">issues.joomla.org/joomla-cms/11886</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11886">issues.joomla.org/joomla-cms/11886</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
