### PR TITLE
[4.0] Dashboard Permissions

### PR DESCRIPTION
**Pull request by brianteeman**
The component dashboard does not "hide" components that a user does not have access to.

This PR removes the component from the dashboard if the user doesn't have access to that component.

### To test 
1. create a new user of level admin
2. Change the permissions for com_banners so that the admin userlevel is denied access to the Administration Interface
3. Log in as that user

### Expected result
banners no longer present on the menu AND banners no longer present on the dashboard

### Actual Result
banners still present on the dashboard with a 403 denied if you try to click

### Apply the PR
banners is not present on the dashboard

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f1e7ccd0c71e429e4623091ee09daab117fa5e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27779">issues.joomla.org/tracker/joomla-cms/27779</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7f1e7ccd0c71e429e4623091ee09daab117fa5e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27779">issues.joomla.org/tracker/joomla-cms/27779</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27779">issues.joomla.org/tracker/joomla-cms/27779</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
