### PR TITLE
Passing a null value for the first argument of Text::script() is depr…

### PR DESCRIPTION
**Pull request by joomlart**
…ecated

Use Text::getScriptStrings() instead.

Pull Request for Issue # .

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by ghost** [comment]
Can you give Test Instructions so People with less Dev-Knowledge can test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18101">issues.joomla.org/tracker/joomla-cms/18101</a>.</sub>

**Comment by Quy** [comment]
Go to `Extensions > Plugins > System - Debug`.
Under Logging tab, enable `Log Deprecated API`.
Go to the frontend.
Open the log file @ `\administrator\logs\deprecated.php`
Search for `As of 3.7.0, passing a null value for the first argument of Joomla\CMS\Language\Text::script() is deprecated and will not be supported in 4.0. Use the Joomla\CMS\Language\Text::getScriptStrings() method to get the strings from the JavaScript language store instead.`
After PR, no warning above.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 963fee1878406e38d9b38a3d04486a254400443d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18101">issues.joomla.org/tracker/joomla-cms/18101</a>.</sub>

**Comment by ghost** [comment]
@Quy without PR got 300+ Warnings but not the one you wrote.

**Comment by Quy** [comment]
Please try again with the Test English (GB) Sample Data demo.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 963fee1878406e38d9b38a3d04486a254400443d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18101">issues.joomla.org/tracker/joomla-cms/18101</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
