### PR TITLE
[4.0] Add missing language tag

### PR DESCRIPTION
**Pull request by N6REJ**
fix per @brianteeman for https://github.com/joomla/joomla-cms/pull/26858

Pull Request for Issue # .

### Summary of Changes
add's missing language tag

### Testing Instructions

peer review

### CODE REVIEW

**Comment by brianteeman** [comment]
This should be
`<html lang="en-gb" dir="ltr">`

**Comment by N6REJ** [comment]
@brianteeman done, ty.

**Comment by wilsonge** [comment]
It’s going to need more than that. The language files are getting substituted in here with JS. We’re going to need to make the Lang injected too (ltr probably fine for now as doubt the template has support for rtl)

**Comment by N6REJ** [comment]
@wilsonge thats beyond my competence george.  Should I just close it?

**Comment by brianteeman** [comment]
There are currently at least 5 errors on that page - the missing lang tag is perhaps the least important of all

**Comment by brianteeman** [comment]
I am going to close this @n6rej 

As @wilsonge said - it requires much more code than is here etc <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27500">issues.joomla.org/tracker/joomla-cms/27500</a>.</sub>

**Pull request closed without merging**
