### PR TITLE
[5.2] Non-static methods called as static from object context

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Non-static methods called as static from object context

### Testing Instructions

Apply patch

### Actual result BEFORE applying this Pull Request

See IDE warnings

### Expected result AFTER applying this Pull Request

No IDE warnings.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
This Pull request changes the behavior. self calls the function defined by it "self" or "parent" class but not if defined in child class.
Example: https://3v4l.org/TtuJ3

```php
<?php

class a {
    function x() {
        echo 'x' . chr(10);
    }
}

class b extends a {
    function y() {
        echo 'y' . chr(10);
        self::x();    
        $this->x();    
    }
    
}

class c extends b {
    function z() {
        echo 'z' . chr(10);
        self::y();
    }

    function x() {
        echo 'x2' . chr(10);
    }
}

echo (new c)->z();
```
Output:
```
z
y
x
x2
```

if someone has time to evaluate what we really want it would be great.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by Hackwar** [comment]
I disagree that this is a b/c break. Yes, in theory the behavior can be different, but in reality this is simply super old code (The line in the banner table for example is at least 14 years old.) and at that time the code quality wasn't the best... With a codereview this could simply be merged.

**Comment by Hackwar** [comment]
Ok, I finally found it. The line in the banner table was introduced close to 15 years ago in one of those major rewrites: https://github.com/joomla/joomla-cms/commit/81e01027d7788e75b6b032b3bd7df30224bf6974#diff-220ad14bb0e7e21591b2575dfb72a5edb7bfbffff4d8069de75e7bcaf8874acdR118

**Comment by crommie** [comment]
In what situation(s) should we see the warnings?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41661">issues.joomla.org/tracker/joomla-cms/41661</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Review by Hackwar — APPROVED** [review]

**Review by HLeithner — APPROVED** [review]

**Comment by Hackwar** [comment]
Thank you for your contribution @Denitz!

**Pull request merged**
