### PR TITLE
Router Rule Standard pass build if query['id'] not exists

### PR DESCRIPTION
**Pull request by asika32764**
### Summary of Changes

Modify `JComponentRouterRulesStandard` add `$query['id']` into isset() so this build rule will not error if id not exists.

### Testing Instructions

In a plugin onAfterInitialise event, set `JComponentHelper::getParams('com_content')->set('sef_advanced', 1);`

Add `JRoute::_('option=com_content&view=category')` without id after above code.

Then go to a category view page.

### Expected result

JRoute should return a wrong URL not error message.

### Actual result

Get `Undefined index: id` error.

-----

We shouldn't make it error, just return NULL to let next rule build a new URL.

If someone want to notice developer who uses a wrong route query, they should throw Exception in router class, maybe `getCategorySegment()` or other positions.

### CODE REVIEW

**Comment by wilsonge** [comment]
@Hackwar

**Review by wilsonge — APPROVED** [review]
Seems good on quick review

**Comment by Hackwar** [comment]
👍 Looks good.

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 10f591e565d777094964241421fb8be69014e69d<br /><br />I reproduced this by creating a "Submit Article" form and putting it's menu item as a child a category blog menu item. Then creating a new article in the blog with the same alias as the menu item. This ended up giving me the same error, and this patch fixed it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16889">issues.joomla.org/tracker/joomla-cms/16889</a>.</sub>

**Comment by ghost** [comment]
@wilsonge 
#### This Test-Enviroment you use?

1. Blog-Menu using Alias "example"
2. as Child of Blog-Menu a "Submit Article"-Menu
3. create an Article using Alias "example"

this ended in an `Undefined index: id`, this PR solves it … correct?

**Comment by wilsonge** [comment]
No create a child article with the same alias as the "submit article" menu item

**Comment by ghost** [comment]
Parent-Menu "Blog" (Category Blog), 
|- Child-Menu "Test" (Create Article),

#### created an Article in Frontend using "Test"-Menu, got:


#### Click on Article got:


What i'm missing?

**Comment by asika32764** [comment]
This issue will occurred in a view without `id` var. Just paste the example code will reproduce this issue.

Mostly this error will not appear in com_content but if any developer use new route in their own component, this error in library will make them hard to debug.

**Comment by ghost** [comment]
@asika32764 thanks for Info. So its an issue to test for Devs.

**Comment by wilsonge** [comment]
@franz-wohlkoenig whoops i forgot to add that you need to have new routing on. So either test on 3.8 with that param enabled. Or store with the com_content params no id's and new router mode enabled

**Comment by ghost** [comment]
Test on 3.8-dev using new Router, no ID.

Without PR got no Warning after saving Article. Click on Article in Blog-View call "Create Article"-Menu.

Applying Patch got: The file marked for modification does not exist: libraries/cms/component/router/rules/standard.php

**Comment by wilsonge** [comment]
Patch this dude https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Joomla/CMS/Component/Router/Rules/StandardRules.php Same file new location

**Comment by ghost** [comment]
Patch applied, same Result: Click on Article (Alias "test") in Blog-View open "Create Article"-Menu (Alias "test").

**Comment by wilsonge** [comment]
1. Apply Patch
2. Install Joomla with sample data
3. Move "Submit Article" menu item to be a child of "Article Category Blog"
4. Create an article in the "Park Blog" category with the alias "submit-article" (note the category is the one that matches the category blog menu item and the alias matches the child menu item).
5. Turn on "Experimental Routing" and "no Id's" for com_content
6. Go to the frontend and go to the 'submit article' menu item. You'll find beneath the article submission there's a PHP Notice 

image

**Comment by ghost** [comment]
#### Article "Submit Article", Category "Park Blog", Blog-View:
bildschirmfoto 2017-07-26 um 12 22 06
#### Open Article opens Menu "Submit Article", no Notice. Error Reporting "Development".
bildschirmfoto 2017-07-26 um 12 22 37
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
What happens if you turn off multilang out of interest? Seems unlikely but maybe that's affecting it??

**Comment by ghost** [comment]
Disabled Plugins "Language Code" and "Language Filter" > same Result as above.

Set "Create Article"-Menu on Access-Level "Special", logout, click Article with alias "create-article" > Login-Menu and Message "Please login first".

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 10f591e565d777094964241421fb8be69014e69d<br /><br />After PR applied "Notice: Undefined index: a_id in /libraries/cms/component/router/rules/standard.php on line 201" is gone.

@wilsonge new Install of staging solved Problem discussed above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16889">issues.joomla.org/tracker/joomla-cms/16889</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by mbabker** [comment]
@asika32764 can you resolve the merge conflict please?

**Comment by asika32764** [comment]
Done

**Pull request merged**
