### PR TITLE
[BS2] Fix for XSS issue with data-target attributes in BS2 JS

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This patch by @SniperSister fixes an publicly known XSS Problem in the BS2 JS reported to the JSST by @C-Lodder. As this issue is publicly known and can also impact 3rd partys the JSST decided to patch it in the public tracker. This also allows an wider group of people to test this patch.

### Testing Instructions

Make sure the following bootstrap js components still work
* Alert
* Carousel
* Collapse
* Dropdown
* Modal
* Scrollspy
* Tab

Try using the data-target and href methods and also try to verify that the mentioned components still work in the Joomla backend.

### Expected result

BS JS Code still works

### Actual result

The current JS Code has an know and publicly documented XSS Problem

### Documentation Changes Required

none

cc @joomla/security @mbabker

### CODE REVIEW

**Comment by zero-24** [comment]
We might can get some tests or some kind of Feedback here?

What does hold you off testing? Is it unclear what to test?
Whatvholds you up providing Feedback? Let me know we really want to get this fixed. cc @snipersister

**Comment by alikon** [comment]
tested 

- alert
- collapse
- dropdown
- modal
- tab

and still works in the Joomla backend

unable to test carousel & scrollspy  (don't know where these are used in the backend)
sorry i'm not a js guy :face_with_head_bandage:

**Comment by HLeithner** [comment]
Any chance to get a look on this from @dgrammatiko ?

**Comment by dgrammatiko** [comment]
@HLeithner looks fine here

**Comment by HLeithner** [comment]
@PhocaCz could you please test this PR with some of your extensions that maybe use this feature set?

**Comment by PhocaCz** [comment]
@HLeithner 

Is this related to frontend or backend? In frontend, I use BS3 for my extensions.

**Comment by HLeithner** [comment]
@PhocaCz its front and backend core BS2

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on f3d9afb2663af1f5eb29064eafe95b73ad5feea6<br /><br />Tested Joomla! 3.9.3 administration: Alert, Modal, Tab with 3pd extensions (Phoca Gallery, Phoca Download, Phoca Cart) and it seems like everything is OK

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22844">issues.joomla.org/tracker/joomla-cms/22844</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 698005694dc8a6416b18ac82746376fc813058a4<br /><br />I have tested the Carousel creating a custom code with: https://getbootstrap.com/2.3.2/javascript.html#carousel<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22844">issues.joomla.org/tracker/joomla-cms/22844</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22844">issues.joomla.org/tracker/joomla-cms/22844</a>.</sub>

**Comment by zero-24** [comment]
Thanks for your tests 👍 cc to be merged @HLeithner

**Comment by HLeithner** [comment]
I would like to see the JED tested with it

**Comment by mbabker** [comment]
> I would like to see the JED tested with it

This is not a practical request.  Extension code is not stored in the JED or in a resource available within the JED, and it is not within the JED's role in relation to core development to audit or test extensions against any core change.

**Comment by HLeithner** [comment]
My request is to test the jed, not extensions from jed.

And don't worry I will do it my self.

**Comment by HLeithner** [comment]
thx all for there work.

**Pull request merged**
