### PR TITLE
[4.1] Tasks site offline

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the language string

## Before
image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 46c9df6d286d4a3c2011a2e09db7145823d7b254<br /><br />Code inspect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36206">issues.joomla.org/tracker/joomla-cms/36206</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 46c9df6d286d4a3c2011a2e09db7145823d7b254<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36206">issues.joomla.org/tracker/joomla-cms/36206</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36206">issues.joomla.org/tracker/joomla-cms/36206</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 46c9df6d286d4a3c2011a2e09db7145823d7b254<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36206">issues.joomla.org/tracker/joomla-cms/36206</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
