### PR TITLE
[4.3] Media Manger Remove all the eslint inline rule overrides

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Remove all the eslint rule overrides
- Change some imports/exports to default
- Add the missing props on many components

Also, and this one is important and the reason I did this PR, stop mutation store values outside of the store. The vue docs are very clear on this one: https://eslint.vuejs.org/rules/no-side-effects-in-computed-properties.html#rule-details
The instance that was wrongly mutating the store is:

```js
    /* Get the contents of the currently selected directory */
    items() {
      // eslint-disable-next-line vue/no-side-effects-in-computed-properties
      const directories = this.$store.getters.getSelectedDirectoryDirectories
        // Sort by type and alphabetically
        .sort((a, b) => ((a.name.toUpperCase() < b.name.toUpperCase()) ? -1 : 1))
        .filter((dir) => dir.name.toLowerCase().includes(this.$store.state.search.toLowerCase()));

      // eslint-disable-next-line vue/no-side-effects-in-computed-properties
      const files = this.$store.getters.getSelectedDirectoryFiles
        // Sort by type and alphabetically
        .sort((a, b) => ((a.name.toUpperCase() < b.name.toUpperCase()) ? -1 : 1))
        .filter((file) => file.name.toLowerCase().includes(this.$store.state.search.toLowerCase()));

      return [...directories, ...files];
    },
```

And is replaced with

```js
    /* Get the contents of the currently selected directory */
    localItems() {
      const directories = this.$store.getters.getSelectedDirectoryDirectories.slice(0)
        // Sort by type and alphabetically
        .sort((a, b) => ((a.name.toUpperCase() < b.name.toUpperCase()) ? -1 : 1))
        .filter((dir) => dir.name.toLowerCase().includes(this.$store.state.search.toLowerCase()));

      const files = this.$store.getters.getSelectedDirectoryFiles.slice(0)
        // Sort by type and alphabetically
        .sort((a, b) => ((a.name.toUpperCase() < b.name.toUpperCase()) ? -1 : 1))
        .filter((file) => file.name.toLowerCase().includes(this.$store.state.search.toLowerCase()));

      return [...directories, ...files];
    },
```

The rename from `items` to `localItems` was on purpose to emphasise that this is a **local** representation of the data!!!

### Testing Instructions
Apply the PR, run `npm ci` and check that the media manager is still working

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@laoneo

### CODE REVIEW

**Comment by Quy** [comment]
See text briefly displayed.

39709-mm

**Comment by Quy** [comment]
Remove gap/spacing.

39709-gap

**Comment by Quy** [comment]
Create a folder.
Open it.

39709-empty

**Comment by dgrammatiko** [comment]
@Quy I fixed the border gap but the untranslated string comes from my wrong reset of the base branch when I was testing https://github.com/joomla/joomla-cms/pull/39518. In sort #39518 needs to be merged before this PR

@obuisard could you merge #39518 ?

**Comment by obuisard** [comment]
> @obuisard could you merge #39518 ?
> 

@dgrammatiko I can merge it for you but it's on the 4.2 branch. You will have to wait for the up-merge to get this fixed in 4.3

**Comment by dgrammatiko** [comment]
@obuisard don't merge it on 4.2, rebase it on 4.3 as it's a new feature and then merge it...

**Comment by obuisard** [comment]
> @obuisard don't merge it on 4.2, rebase it on 4.3 as it's a new feature and then merge it...

Now there are conflicts that need to be fixed first

**Comment by Quy** [comment]
Maybe it is not the case in the other PR, but can you look to moving the no media message below the table? Thanks.

39709-list

**Comment by dgrammatiko** [comment]
@Quy ok, I removed the empty state text as it's obviously not ready yet

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d2747b2ecb7bf26bd98d1c4e898ac72a5661560<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39709">issues.joomla.org/tracker/joomla-cms/39709</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9d2747b2ecb7bf26bd98d1c4e898ac72a5661560<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39709">issues.joomla.org/tracker/joomla-cms/39709</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39709">issues.joomla.org/tracker/joomla-cms/39709</a>.</sub>

**Comment by laoneo** [comment]
Thanks!!

**Pull request merged**
