### PR TITLE
[4.0] Fix doc block indentation

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
While doing a media pr. Saw that the indentation is not correct in mutations js file.

@wilsonge code review only

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on fcb77cf547474d6d2fa4542e658fdbd8495a38d0<br /><br />Tested by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35990">issues.joomla.org/tracker/joomla-cms/35990</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fcb77cf547474d6d2fa4542e658fdbd8495a38d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35990">issues.joomla.org/tracker/joomla-cms/35990</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35990">issues.joomla.org/tracker/joomla-cms/35990</a>.</sub>

**Comment by richard67** [comment]
Thanks

**Pull request merged**
