### PR TITLE
[4.0][a11y] Allow enabling of both 'High Contrast' & 'Monochrome'

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #27119 .

### Summary of Changes
Allows enabling of both 'High Contrast' & 'Monochrome'

### Testing Instructions
Navigate to User Menu -> Accessibility Settings. Apply both Monochrome and High Contrast options.

### Before PR
image

### With PR
image

### CODE REVIEW

**Comment by brianteeman** [comment]
as you have changed the contrast in the other pr to `filter: contrast(115%); ` from `filter: invert(100%); `shouldnt you do the same here as well

**Comment by ciar4n** [comment]
If #27143 gets merged then I will amend this PR to match. Likewise, if this gets merged I will amend #27129. I notice multifaceted PRs tend to not get merged.

**Comment by ciar4n** [comment]
Eg. https://github.com/joomla/joomla-cms/pull/26440

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f4c4120ff741b6b5782bb67d26b2b2f927802633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27142">issues.joomla.org/tracker/joomla-cms/27142</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f4c4120ff741b6b5782bb67d26b2b2f927802633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27142">issues.joomla.org/tracker/joomla-cms/27142</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27142">issues.joomla.org/tracker/joomla-cms/27142</a>.</sub>

**Comment by wilsonge** [comment]
#27143 merged - happy to update this as mentioned?

**Comment by ciar4n** [comment]
> #27143 merged - happy to update this as mentioned?

Thank you. Updated.

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
