### PR TITLE
Fix list-view js to work with ajaxed content

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

After removing inline js we broke posibility to use these with dinamic content, eg content loaded with ajax.
Not used in core, but other developers may use it.

### Testing Instructions

Apply patch, run `npm install`
Add to index.php of admin template (ajax simulator, will add "Reload" button on the page):
```html
<script type="module">
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.textContent = 'Reload';
  window.content.insertAdjacentElement('afterbegin', btn);
  btn.addEventListener('click', () => {
      fetch('index.php?option=com_content&view=articles&tmpl=component').then((resp) => resp.text()).then((resp) => {
        const temp = document.createElement('template');
        temp.innerHTML = resp;
        const container = window.adminForm.parentElement;
        container.removeChild(window.adminForm);
        container.appendChild(temp.content.querySelector('#adminForm'));
        container.dispatchEvent(new CustomEvent('joomla:updated', {bubbles: true, cancelable: true}));
      })
  });
</script>
```

Go to **Articles** view:
Click unpublish/publish;
Click "Reload" button;
Click unpublish/publish again;

### Actual result BEFORE applying this Pull Request
First click "unpublish/publish" works
Second click "unpublish/publish" does not works

### Expected result AFTER applying this Pull Request
First click "unpublish/publish" works
Second click "unpublish/publish" works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org:
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org:
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Fedik I didn't thought that these could be in a dynamically generated content. Good catch

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 264b13d7a0fe95682753e80b857059b47e7853b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40598">issues.joomla.org/tracker/joomla-cms/40598</a>.</sub>

**Comment by JonasAtZwetschke** [comment]
I have tested this item :white_check_mark: successfully on fd335420c8de2537c00fcb52e9a36aeb7a12cd99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40598">issues.joomla.org/tracker/joomla-cms/40598</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40598">issues.joomla.org/tracker/joomla-cms/40598</a>.</sub>

**Comment by obuisard** [comment]
Thank you Fedir @Fedik, great catch :-)

**Pull request merged**
