### PR TITLE
Fix for nested sets in the menu (installation and update processes)

### PR DESCRIPTION
**Pull request by Kubik-Rubik**
Please see #8274 and #8057 for more details.

We need to correct the nested sets after we've removed one entry in the menu.

Thanks to @matrikular and @roland-d for providing valued input on this topic.

**How to test?**

Do an installation and an update (with the changed files included in the package) and check whether the menu still works properly!

### CODE REVIEW

**Comment by waader** [comment]
@Kubik-Rubik  With #8274 I checked the component menus and the worked. So obviously that was not enough. I have to check all menu items, right?

**Comment by Kubik-Rubik** [comment]
@waader It should also work with #8274 but the values are just not correct there. With this PR they were corrected.

**Comment by waader** [comment]
Something I observed while getting prepared to test this patch. I installed the current staging branch and then went to Manage > Database. There I get this items:

able 'v1j2o_banners' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_categories' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_contact_details' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_content' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_menu' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_newsfeeds' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_tags' does not have column 'alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)
Table 'v1j2o_ucm_content' does not have column 'core_alias' with type 'varchar(191)'. (From file 3.5.0-2015-07-01.sql.)

Can you adapt joomla.sql appropriately?

**Comment by Kubik-Rubik** [comment]
@waader Thank you for the hint, I will fix it now.

**Comment by infograf768** [comment]
Me wonder in general about the 191 characters lomit for alias btw. Think about Chinese script when using Unicode aliases.

**Comment by Kubik-Rubik** [comment]
@waader @infograf768 Please test the update. Do a fresh installation and check whether database errors are displayed in "Extensions" - "Manage" - "Database".

**Comment by infograf768** [comment]
Database Up to date. OK for me

**Comment by Kubik-Rubik** [comment]
@infograf768 Thanks! And the menus are working properly? If yes, please mark as tested successfully. Thank you!

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 03e6fd1a0da86b824f416b521eb14ea535511e0b<br /><br />Thanks Kubik-Rubik!

I have tested mysql, postgres and mssql.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8284">issues.joomla.org/joomla-cms/8284</a>.</sub>

**Comment by wilsonge** [comment]
Can we try and split things up please. Let's keep all the stuff for the alias's in @zero-24 's PR #8268 (just PR the non-mysql database changes for that into there) and keep this specific to that menu change.

For the menu changes. The old values 18-20 were for weblinks. So any testers MUST make sure at minimum they test starting at 3.3.6 and upgrading through the versions to this version. To be honest whilst I don't mind what we start new installs on I see upgrading existing installs as very risky and bug prone - it could leave people with two items with the same lft value in a worst case scenario. This is why we have the rebuild button in the menu manager and don't do update queries for menus pretty much ever.

**Comment by Kubik-Rubik** [comment]
@wilsonge  Ah, I didn't see @zero-24's PR. I think then the best solution would be to close this PR and maybe add a notification to users that they should press the rebuild button once?

**Comment by waader** [comment]
I didn´t see this neither. @Kubik-Rubik. you also have the date changes for postgres.

**Comment by Kubik-Rubik** [comment]
I will close this PR in favor of #8268 and https://github.com/joomla/joomla-cms/pull/8284#issuecomment-154075230.

**Pull request closed without merging**
