### PR TITLE
[4.0] s/Registration/Remind

### PR DESCRIPTION
**Pull request by brianteeman**
Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 757448e68300aa805abc086d22d4ed63b7ce343f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34053">issues.joomla.org/tracker/joomla-cms/34053</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you and @PhilETaylor also please make a break with this kind of PRs, we want to get 4.0.0 out of the door and these things are using too much time from the limited time we as maintainers have. I am happy to look at all of this after 4.0.0 is out what should be soon.

**Comment by PhilETaylor** [comment]
You are seriously taking the piss right?

>  limited time we as maintainers have. 

Maybe you should step down then. Other maintainers, have been doing a fantastic job.

Im sorry you don't take code quality seriously. And a lot of my PRs fix actual issues which would break in real life. 

We don't dictate how you spend your time - how dare you dictate how I spend my time! 

If you don't want to merge a PR - don't - no one is forcing you to review or merge things. 

Im really annoyed and angered by your post.

**Comment by chmst** [comment]
You are doing a phantastic job with code quality and I have checked and merged lots of your PRs, all were fine. Thanks for your work. 
I know very well how easy a PR is made, and I also know how many time it takes to get it tested and merged. So please understand that not everything can be merged at once.

**Comment by brianteeman** [comment]
> So please understand that not everything can be merged at once.

Where did anyone say anything about merging at once.

I've still got RTC pr from weeks ago - do you hear me say anything

**Comment by chmst** [comment]
I think we all are doing as good and as much as we can. Maybe it is possible  to cluster small changes?

**Comment by PhilETaylor** [comment]
Im sorry but being personally accused of being the reason that Joomla 4 release has been delayed is simply pathetic. 

> So please understand that not everything can be merged at once.

It seems that Robert is the one that needs to learn that. I just keep setting them up, and others test, and others merge. I have no control over how you, he or others spend their time but demanding that I stop contributing in the areas I can is simply outrageous.

Its like trump demanding that testing be stopped so that less covid is found and the statistics are better. absolutely pathetic. 

Even if I generated 1000 PR's tonight, Joomla 4 will still be in the same place and would not be any further delays. My small testable, mergeable PRs are NOT THE REASON for the delays or time consuming of maintainers... 

I could list the real reasons for Joomla 4 delays but no one hear likes to hear the truth. 

> I've still got RTC pr from weeks ago - do you hear me say anything

Ive got a really really complex one with over 100 comments on it from March, that people don't test because its too complex and expert level.. this is the reason some PRs take time - again, out of my hands, I can only provide the code, its up to others to test, feedback and merge, but demanding that people stop contributing their time is inexcusable. 

> Maybe it is possible to cluster small changes?

And then we get told that the PR is too large to be tested and merged and it sits there unmarked for years... been there, done that.

**Comment by brianteeman** [comment]
not as if anyone is sayong wtf were these obvious errors merged in the first place and blaming someone

**Comment by richard67** [comment]
Nobody said we shall merge them fast, but if we don't do it, they fill up the list of open PR's so the important ones get lost in history. Therefore I did all I could do this week to get them handled fast.

It would be easier for us if some could be combined into a smaller number of PRs.

**Comment by brianteeman** [comment]
fine by me I will just stop all together

**Comment by PhilETaylor** [comment]
> Therefore I did all I could do this week to get them handled fast.

Because you are not a lazy maintainer like Robert is.

> It would be easier for us if some could be combined into a smaller number of PRs.

See my previous reply. Simply not acceptable to do. 

> not as if anyone is sayong wtf were these obvious errors merged in the first place and blaming someone

Robert doesn't even bother reviewing the PRs before he merges them... fact... he just looks for the RTC and hits the merge button, as evidenced in the time between each merged PR emails we receive.

**Comment by richard67** [comment]
> fine by me I will just stop all together

@brianteeman Was that in reply to me? Then you might got me wrong since I haven't said I want anything to be stopped.

**Comment by rdeutz** [comment]
I was pointing to typo changes and I just said to make a break for a time so that we can concentrate on release blockers and fixing bugs. I really don't understand the overreaction I have merged a lot of these PRs, it's very often me spending hours at the morning merging RTC PR. I want to have a clean list without to much PRs in RTC it helps to get a better overview.

> Im sorry but being personally accused of being the reason that Joomla 4 release has been delayed is simply pathetic.

Nobody said this.

**Comment by brianteeman** [comment]
the majority of the pr I have submitted today are NOT typo changes

**Comment by PhilETaylor** [comment]
> I was pointing to typo changes and I just said to make a break for a time so that we can concentrate on release blockers and fixing bugs. 

NOTHING I DO STOPS YOU SPENDING YOUR TIME ANYWAY YOU WISH - go and concentrate on the release blockers and fixing bugs if you want 

> Nobody said this.

Liar. 

> we want to get 4.0.0 out of the door and these things are using too much time from the limited time we as maintainers have. 

There you go. "These things = our contributions" are "using too much time" and stopping Joomla 4.0.0 getting out of the door. 

Pathetic.

**Comment by rdeutz** [comment]
> Because you are not a lazy maintainer like Robert is.

I have really enough form you personal attacts. 

> Robert doesn't even bother reviewing the PRs before he merges them... fact... he just looks for the RTC and hits the merge button, as evidenced in the time between each merged PR emails we receive. 

That's not true and disrespectful, you should give other the same respect you are expecting for youself.

**Comment by PhilETaylor** [comment]
> I have really enough form you personal attacts.

Then ban me then. Or file a CoC report that OSM will ignore the same way you ignore the contributions of others and the way they ignore all CoC issues. 

> That's not true and disrespectful,

Factually true. In 4 mins you tested the code and merged all these 

Screenshot 2021-05-20 at 19 24 15

**Comment by PhilETaylor** [comment]
7 out of 230 PR's are marked as RTC... and a lot of those RTC (including the oldest) have no chance of being merged before 4.0 is released... so you are crying over 7 open RTC PRs.... I give up... seriously dude, just go and do something more constructive.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 757448e68300aa805abc086d22d4ed63b7ce343f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34053">issues.joomla.org/tracker/joomla-cms/34053</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34053">issues.joomla.org/tracker/joomla-cms/34053</a>.</sub>

**Comment by PhilETaylor** [comment]
7 RTC PRs - isn't that like one per person with rights to merge? How many official maintainers are there exactly? and you are complaining about us overloading you to the point no one can concentrate on bugs and release blockers so joomla 4 is delayed? Get real!

**Comment by richard67** [comment]
> 7 RTC PRs

@PhilETaylor Your count is not relevant now after we have merged all these PR's today. This morning it was a bit more.

**Comment by brianteeman** [comment]
its irrelevant anyway. No one is forced to test. No one is forced to merge. No one expects that

**Comment by PhilETaylor** [comment]
Yes and not one tester or maintainer complained - until now. Pathetic.

The other maintainers do an amazing job and merge so many more PRs after reviewing them.

**Comment by rdeutz** [comment]
> Factually true. In 4 mins you tested the code and merged all these

I reviewed all, all are quite easy adding a backslash, removing a line and so on. Doesn't need an hour to see if that is right.

What really annoys me is the overreaction on such a simple question I have asked and how I have been attacted.

**Comment by alikon** [comment]
folks  we all should have the same goals, publish j4 stable yesterday, but if the few of us  who contribute on a regular basis, fight each others for null, then we have a problem, i'll ask you all to do a relax step back...  to see the whole picture.... but please keep going on

**Comment by PhilETaylor** [comment]
I'm feel sorry for you that you value contributors so little.

I'm rightly angry that you feel privileged with power to demand how contributors spend their own time.

I'm rightly angry that you personally called us out as the reason maintainers have no time to review release blockers and therefore you state we are holding up the release - absolute rubbish! 

Joomla 4 delays are not contributors fault. They are leadership and management reasons for the delays

There is nothing I - as the lowest contributor - can do to speed up joomla 4 release cycle. But thanks to your attitude you can be sure I'll not be wasting my weekend this weekend like George asked me to, to race things like Mail Template rewrite for tuesdays release. Not now I know how little you value active contributors.

Over 3000 contributions to source code in the last year... and never once has a maintainer accused me of taking up too much of their time. Most are grateful!!!

I suggest you check the stats on who is actually contributing- you can count us on the number of fingers you have without having to remove your socks!

**Comment by alikon** [comment]
you completely miss my point, i know it is my bad english

**Comment by PhilETaylor** [comment]
To be clear, my reply was not aimed at you but Robert. I got your point, but I was driving and could not reply. Trying to multitask being a dad taxi.

**Comment by alikon** [comment]
happy to discover that my english it's not so bad ...after all :smiley:

**Comment by brianteeman** [comment]
> I reviewed all, all are quite easy adding a backslash, removing a line and so on. Doesn't need an hour to see if that is right.

In which case what was the point of your original comment? On the one hand you say it takes time. On the other hand you say it took you 4 minutes to check and merge seven pull requests. Something doesn't make sense to me at all.

**Comment by rdeutz** [comment]
> Robert
> 
> I'm feel sorry for you that you value contributors so little.
> 
> I'm rightly angry that you feel privileged with power to demand how contributors spend their own time.
> 
> I'm rightly angry that you personally called us out as the reason maintainers have no time to review release blockers and therefore you state we are holding up the release - absolute rubbish!
> 
> You have REPEATEDLY blocked and dismissed code quality PRs because you don’t care about code quality, and you wrongly believe it will cause issues with merging. That’s literally the job of a maintainer but you refuse any PR that makes you have to work on it. Other projects, Symfony etc the maintainers will do code style changes, merge issues, rebasing and much more on behalf of a contributor who took their time to contribute!
> 
> Joomla 4 delays are not contributors fault. They are leadership and management reasons for the delays
> 
> There is nothing I - as the lowest contributor - can do to speed up joomla 4 release cycle. But thanks to your attitude you can be sure I'll not be wasting my weekend this weekend like George asked me to, to race things like Mail Template rewrite for tuesdays release. Not now I know how little you value active contributors.
> 
> Over 3000 contributions to source code in the last year... and never once has a maintainer accused me of taking up too much of their time. Most are grateful!!!
> 
> I suggest you check the stats on who is actually contributing- you can count us on the number of fingers you have without having to remove your socks!

I will try a last time to make clear what I wanted to say. We are close to the finish line for Joomla4RC1 and the idea was to concentrate on the things that really need to be fixed before the RC comes out. We all have limited time and if a class name is wrong in the comment is not so urgent to fix. I welcome any contribution also the correction of typos and such, I know that we had a lot of them in the past weeks because I reviewed and merged a lot of them. 

I don't have the power to say what contributers should do and how they spend time, that why I ask. It might got understand wrong because I have written 4.0.0, I meant 4.0.0RC1.

I never wanted to say and I can't see that I have said that it is a fault of contributers that Joomla4 is delayed. 

It is also not true that I don't care about code quality. It doesn't makes something true even if it get repeated over and over again. 

They only intention I had and still have is that we join forces and make the rc1 ready to release. 

On a personal level I feel treated unfair, my contributions are devalued. Merging doesn't count on github, the commit goes to the author of the PR (what is totally ok) but checkin a PR takes time. I get words put in my mouth I never said and I am shocked about the aggressiveness in replies. 


> In which case what was the point of your original comment? On the one hand you say it takes time. On the other hand you say it took you 4 minutes to check and merge seven pull requests. Something doesn't make sense to me at all.

It's not only the merge, two people have to test, one set to RTC and then the merge. It's the total amount of time and people involved.

**Comment by brianteeman** [comment]
Robert you are missing the point. You complained about the time it was taking maintainers. The only thing that maintainers **have** to do is the final check and merge. They are **not** expected to do the testing. In fact for such simple things I wouldn't have expected them to do that and it could be left to one of the many new people who have been doing a lot of testing recently. As Phil and I have both said - we have not said anywhere anything about merging - and what we spend our time on is our business. It doesn't matter if a pr is written on a tuesday or a wednesday you can merge it or **reject** it whenever you want.  If I was still a maintainer I would have been spending my time triaging the 700+ issues - a **lot** of those have been asked and answered and can be closed or should simply be closed as a **rejected** idea. But I haven't said that because its not my place to tell anyone what they should work on.
Finally when reviewing code for bugs what should we do with a **minor** issue if we find it - just ignore it? That makes no sense. either. You might feel that you have been badly treated but the reality is that you told phil and myself to stop wasting your time.

**Comment by brianteeman** [comment]
Final comment

> The idea was to concentrate on the things that really need to be fixed before the RC comes out. 

If only someone had communicated that. I had to read on twitter that there would be an RC on tuesday. I have in the past produced lists of things to do but they were ignored so I didnt spend my time on that.

**Comment by PhilETaylor** [comment]
> We are close to the finish line for Joomla4RC1 and the idea was to concentrate on the things that really need to be fixed before the RC comes out.

No one is stopping you. But you have no right to demand that others spend their time on things that interest you only. 

>  We all have limited time and if a class name is wrong in the comment is not so urgent to fix.

No one said it was urgent, and not all my PRs are like that. The PR was created with no urgency and merging it has no urgency. No contributor is asking anything of you at all, and certainly not urgently. 

>  I welcome any contribution also the correction of typos and such

Factually incorrect, you rejected the mere motion of fixing code quality on at least three occasions now, including the major merges of code style and cleaning up deprecated method calls. 

> I don't have the power to say what contributers should do and how they spend time,

Correct. Yet that is exactly what you did, demand that contributors not take up too much of your time so you could concentrate on release blockers and fixing bugs. 

> I never wanted to say and I can't see that I have said that it is a fault of contributers that Joomla4 is delayed.

That is EXACTLY what you accused us of =  "we want to get 4.0.0 out of the door and these things are using too much time from the limited time we as maintainers have"

> It is also not true that I don't care about code quality. It doesn't makes something true even if it get repeated over and over again.

Then why reject code quality PRs over and over again thus proving that you do not care about quite quality LMAO!. If the shoe fits... 

> They only intention I had and still have is that we join forces and make the rc1 ready to release.

Then leave contributors alone to contribute. There is nothing else I can do to make Joomla ready for release. I dont need to join anyones force. Joomla 4.0.0 RC 1 should have been released;eased weeks ago by decisions were made way higher than a contributor level. All contributors can do is contribute - and you have no right to tell them, us, not to. 

> On a personal level I feel treated unfair

LMAO. You slag off contributions and accuse us of being the reason you have no time to work on "the real problems" that we are holding up and you feel unfairly treated - wow. 

> Merging doesn't count on github, the commit goes to the author of the PR (what is totally ok) but checkin a PR takes time.

This is the role you signed up for! This is the role of a maintainer - if you dont like it then you can quit - no one is demanding that you do the role if you feel so undervalued,. just like no one forces contributors to contribute! 

> It's not only the merge, two people have to test, one set to RTC and then the merge. It's the total amount of time and people involved.

And the only person moaning about the time it takes is you...

**Comment by PhilETaylor** [comment]
> We are close to the finish line for Joomla4RC1 and the idea was to concentrate on the things that really need to be fixed before the RC comes out.

And yet no one has produced a list of things to work on, encouraged contributors to work on that list, no developer advocacy has taken place, no enthusiastic reaching out to developers to help get across the line... just a silent sitting back expecting people to contribute randomly to hit a moving target... and then complaining when their contributions are not of the type wanted...

**Comment by rdeutz** [comment]
> If only someone had communicated that. I had to read on twitter that there would be an RC on tuesday. I have in the past produced lists of things to do but they were ignored so I didnt spend my time on that.

For me it is moving target too. I have made a list of all 4.0-dev PR, checked any of them and wrote what I think we should do with it. I shared the list internally but too less people particpated so I stopped updating the list after some time.

What I am really missing is that we start with having in mind that we all have good intentions and tring to do the best for the project. I am in the position that I have to make decisions and sometimes people don't like what I decide. I am fine with critics on a factual level but the last times it goes more and more personal and that is not ok.

**Comment by brianteeman** [comment]
Might have been more successful sharing the list publicly

**Comment by PhilETaylor** [comment]
Once again, a list of open PRs is not a list of things contributors, like Brian and I, can work on to move Joomla 4 closer to release. 

Its not the kind of list that is needed at all. 

That is a list for people like you, maintainers, to groom and make decisions on. 

For example, the oldest RTC PR YOU decided not to merge into Joomla 4.0 but you decided to leave it until Joomla 4.1 - but rather than MERGE IT NOW to the Joomla 4.1 branch, so it can be further used and tested, its still open, still sitting there "clogging up" the RTC list daily. Its that kind of "work" that a maintainer should be doing - not shouting at active contributors and telling them not to contribute the little they can! 

You keep slating us for irrelevant time consuming PRs that do nothing but get in the way of releasing Joomla 4, yet when pushed, repeatedly, asked, what EXACTLY you want us to work on, you [The Joomla Project™) never comes up with a list of actionable tasks that need doing. 

So

**Comment by rdeutz** [comment]
What I want is easy for you and all others is to work on release blockers so that we can release a 4RC. 

Re 4.1 Branch, I will asked Bejamin if he can merge the RTC PRs for 4.1

**Comment by PhilETaylor** [comment]
> What I want is easy for you and all others is to work on release blockers so that we can release a 4RC.

LMAO - The release blockers I HAVE WORKED ON are sat in a queue WAITING for MAINTAINERS to make DECISIONS... 

Here is your list.

1 Open Issue - release blocker label

https://github.com/joomla/joomla-cms/issues/21806 - waiting on @wilsonge - has been open since 2018... 

4 open pull requests - release blocker label

https://github.com/joomla/joomla-cms/pull/34043 - MINE - waiting on @wilsonge 
https://github.com/joomla/joomla-cms/pull/33993 - MINE - waiting on @wilsonge 
https://github.com/joomla/joomla-cms/pull/33724 @joomdonation  - Waiting 6 days for @joomla/security JSST team to actually resolve a RIPS issue. Waiting on @HLeithner and @bembelimen to make a decision on the approach that the PR is using
https://github.com/joomla/joomla-cms/pull/25559 - Open since 2019 - @richard67 is going an amazing job on and a PR from @wilsonge 

So what EXACTLY is this list of release blockers that you think contributors should be investing their time into? I ask again???

40% of the release blockers I HAVE ACTIVELY WORKED ON - Also. 14% of all open issues were raised by me... 

Your argument is starting to fall apart.

**Comment by Fedik** [comment]
@PhilETaylor I not very understand what do you tries to achieve by attacking others. 
But it not respect, for sure.

Everyone have a personal life and it is more important than anything written here, especially last couple years.
People contribute on their own will, in their free time, someone have more someone have less.

**Comment by PhilETaylor** [comment]
Im not attacking anyone. Im defending myself AGAINST the attack 

> People contribute on their own will, in their free time, someone have more someone have less.

Then tell Robert that. That is the whole reason for this thread. 

How dare he demand how I, and other contributors, spend my time and accuse us of being the reason Joomla 4 has been delayed. 

That is the whole point of my "attack" as you put it. I will defend my right to contribute how I see fit, but dont make excuses for the delay of Joomla 4 being as a result of contributors making a lot of PRs.

**Comment by Fedik** [comment]
> How dare he demand how I, and other contributors, spend my time and accuse us of being the reason Joomla 4 has been delayed.

He kindly asked. And then you come with attack.
It not nice.

Demanding sounds differently, it would be "he you! stop doing this sh*t, I am already full of it"
Feel the difference?

>  I will defend my right to contribute how I see fit

No one tries to take away any of your rights.

We need to be more kind to each other. Insulting each other is not productive.

**Comment by rdeutz** [comment]
> How dare he demand how I, and other contributors, spend my time and accuse us of being the reason Joomla 4 has been delayed.

Quoting myself
> I never wanted to say and I can't see that I have said that it is a fault of contributers that Joomla4 is delayed.

**Comment by PhilETaylor** [comment]
Quoting your words:

>  we want to get 4.0.0 out of the door and these things are using too much time from the limited time we as maintainers have

**Comment by brianteeman** [comment]
Lost in translation. Non-native english speakers often don't use words with the same meaning that a native speaker would

**Pull request merged**
