### PR TITLE
[4.1] Tasks manager

### PR DESCRIPTION
**Pull request by brianteeman**
We stopped using the term "manager" several years ago.

This PR updates some strings to reflect that and removes several unused strings

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d8219c8aad724ae11b8c579ea894a9d6ca52f624<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36212">issues.joomla.org/tracker/joomla-cms/36212</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on d8219c8aad724ae11b8c579ea894a9d6ca52f624<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36212">issues.joomla.org/tracker/joomla-cms/36212</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36212">issues.joomla.org/tracker/joomla-cms/36212</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on d8219c8aad724ae11b8c579ea894a9d6ca52f624<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36212">issues.joomla.org/tracker/joomla-cms/36212</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
