### PR TITLE
[5.2] Improve UX for template buttons - replace PR #43592

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #43212 .
Replaces #43592

### Summary of Changes
Several users mentioned confusion i the com_templates toolbar, caused by the delete-file and close-file button.
This is an attempt to provide a solution with as few changes as possible. 
Some buttons are used in the whole system and cannot be changed for this view, so we have not many options for changes here. 

Changes made here: 

Button for Preview always at position 1, becaus it is always vivile also for non-super usres.

Change the text on the "close file" button to "close". Because this button does not only close the file but it closes the screen and redirects back, for users it does not matter if there is another action in the code.  

Move the "Close" Button" directly after the action buttons, before the file management buttons. 

Use the trash icon on the "file delete" button. We had many discussions about that - In Joomla the trash button means "trashed" => state = -2 not "deleted permanently", but when we think as a user not as a developer, the icon is completely clear here. 

I improved the code a little bit by removing an unused variable and used switch instead of nested elseif. 

### Testing Instructions
Play around in templates and template styles, make child templates, manage files.
Whatever you want to do with your template should have a comprehensive and complete toolbar, in most cases the same as before. 

### Actual result BEFORE applying this Pull Request
see #43212. 
delete button and close-file button.
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f45b391fabc6773c7b507acb50ff4c66c23517b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43975">issues.joomla.org/tracker/joomla-cms/43975</a>.</sub>

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on f45b391fabc6773c7b507acb50ff4c66c23517b7<br /><br />I have tested this successfully. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43975">issues.joomla.org/tracker/joomla-cms/43975</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43975">issues.joomla.org/tracker/joomla-cms/43975</a>.</sub>

**Comment by pe7er** [comment]
Thanks @chmst !

**Pull request merged**
