### PR TITLE
[3.x] New sessiongc plugin is not declared as core plugin for manifest cache refresh

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #20013

### Summary of Changes

Add sessiongc plugin to the list of core plugins

### Testing Instructions

- Add this line to the upgrade package
- Apply the upgrade package

### Expected result

Manifest cache is updated

### Actual result

Manifest cache is not updated

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks like this file alphasorts the plugis

**Comment by zero-24** [comment]
done.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a997ebce317d2463150bf221aab0419b425a61ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20038">issues.joomla.org/tracker/joomla-cms/20038</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on a997ebce317d2463150bf221aab0419b425a61ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20038">issues.joomla.org/tracker/joomla-cms/20038</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20038">issues.joomla.org/tracker/joomla-cms/20038</a>.</sub>

**Pull request merged**
