### PR TITLE
[4.0] Rework CMS Application Interface tree

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24587 (only part).

### Summary of Changes
Start reworking the CMS Application Interfaces onto the new interfaces introduced in the framework

### Testing Instructions
Mainly Code review but you can check the Application still works without throwing missing function fatals (but that is the CIs job)

### Documentation Changes Required
Yup - although there shouldn't be any breaks the interfaces need to be documented

### CODE REVIEW

**Comment by jwaisner** [comment]
Increasing priority as this is a partial fix to a beta blocker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28313">issues.joomla.org/tracker/joomla-cms/28313</a>.</sub>

**Comment by richard67** [comment]
Added back the beta-blocker label since the issue tracker has removed it, it seems, when priority was changed.

**Comment by wilsonge** [comment]
Added a different interface for the stuff in the web interface - aim is we have CMSApplicationInterface which is for all application clients (mainly think cli plus web clients) then CMSWebApplicationInterface which covers the additional methods for web requests (api + html etc)

**Review by laoneo — APPROVED** [review]
Nice one!!

**Comment by wilsonge** [comment]
Merging this as a first point. We may need to tweak things going forward

**Pull request merged**
