### PR TITLE
Fix tabs not wrapping and trigger horizontal scrolling

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #30667 

### Summary of Changes

Add flex wrap to enable wrap on tabs

### Testing Instructions

- apply pr, 
- npm run build:css

### Actual result BEFORE applying this Pull Request
see issue #30667

### Expected result AFTER applying this Pull Request
see issue #30667

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 777884081831b141cc0fbf8d406226321b154a5c<br /><br />Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30675">issues.joomla.org/tracker/joomla-cms/30675</a>.</sub>

**Comment by Ruud68** [comment]
Thanks @sandewt for testing!

**Comment by richard67** [comment]
@chmst @wilsonge Could you test this PR with the laptops you have used for reproducing issue #28799 ? To me it seems other issues than the tabs, e.g. the width of the toolbar and header area either have been solved elsewhere meanwhile, or they are magically solved with this PR, too, or my 2 screens are not suitable to reproduce the other issues.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 777884081831b141cc0fbf8d406226321b154a5c<br /><br />Not sure if it is the best solution, but it is a solution which works, and for me it's ok.

Hoping for more opinions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30675">issues.joomla.org/tracker/joomla-cms/30675</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30675">issues.joomla.org/tracker/joomla-cms/30675</a>.</sub>

**Comment by richard67** [comment]
2 good tests, so RTC.

But I'd still like to know other opinions and if it has fixed issue #28799 completely or not.

**Comment by Ruud68** [comment]
@richard67 thanks for testing and RTC :)

This is the default way bootstrap 4 implements tabs, see here: https://getbootstrap.com/docs/4.5/components/navs/#tabs

**Comment by chmst** [comment]
In any case it is better than before and resolves the issue with horizontal scrolling. So RTC is good for me.

**Comment by wilsonge** [comment]
I mean it's ugly as hell but it wraps. Which is more than it does now

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
