### PR TITLE
[5.3] Send an event before an update site is downloaded

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
This pr adds the same logic for installer plugins to be able to modify the update site url and headers as when the extension is downloaded. A use case for this pr is to add some authentication before fetching the update site url like a bearer token, the download id or similar. For extension developers it has an additional benefit to install a plugin and modify update sites for specific clients without the extra step and a modification of the update site url in the database.

### Testing Instructions
- Install an older version of an extension or [DPCalendar Free](https://joomla.digital-peak.com/download/dpcalendar/dpcalendar-9.2.1) when you don't have one
- Or you can add the following code to the file /plugins/installer/packageinstaller/src/Extension/PackageInstaller.php

```
public function onInstallerBeforeUpdateSiteDownload(\Joomla\CMS\Event\Installer\BeforeUpdateSiteDownloadEvent $event): void
{
        $event->updateUrl($event->getUrl().'demo=1');
}
```

and replace the line 47 with:
```
return ['onInstallerAddInstallationTab' => 'onInstallerAddInstallationTab', 'onInstallerBeforeUpdateSiteDownload' => 'onInstallerBeforeUpdateSiteDownload'];
```

- Go to /administrator/index.php?option=com_installer&view=update
- Click on "Check for updates"

### Actual result BEFORE applying this Pull Request
- DPCalendar update can be found.
- No warning about an invalid url.

### Expected result AFTER applying this Pull Request
- DPCalendar update can be found.
- The following warning is displayed because it modifies the url that it is wrong and will be displayed. Like that we know the url gets modified:
_Update: Could not open update site 3 "Joomla! Update Component", URL: https://update.joomla.org/core/extensions/com_joomlaupdate.xmldemo=1_
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/340
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 3bd616ff0c835d720f1c5a00fbba0ce23e2c120a<br /><br />With Pull Request and without it an Update of 'DPCalendar Free' is found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44516">issues.joomla.org/tracker/joomla-cms/44516</a>.</sub>

**Comment by laoneo** [comment]
I'v updated the testing instructions, to actually see if the event also works.

**Comment by HLeithner** [comment]
The event needs validation, if you set a url this should be validated, at least if it is a string hand has a proper schema set. Similar to the headers argument, needs to be an array of strings (with key?).

**Comment by laoneo** [comment]
All of this is done in the parent class.

**Comment by fgsw** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44516">issues.joomla.org/tracker/joomla-cms/44516</a>.</sub>

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on aa23300169f0d0aa2babf36c499e29c4810f6527<br /><br />I have tested this successfully. Please see note below.

To be more precise in case this is important:

BEFORE the PATCH, there was a whole long list of error lines:

For the extension DPCalendar Free version 7.0.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 7.0.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 7.0.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.3.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.2.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.2.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.1.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.11 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.10 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.9 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.8 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 6.0.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.6.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.5.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.5.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.4.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.4.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.4.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.4.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.4.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.8 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.3.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.2.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.2.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.2.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.2.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.2.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.1.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.1.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.1.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 5.0.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.9 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.8 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.2.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.1.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.1.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.1.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.1.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.1.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.12 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.11 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.10 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.9 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.8 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.7 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.6 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.5 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.4 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.3 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.2 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.1 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
For the extension DPCalendar Free version 4.0.0 is available, but it requires at least PHP version 8.3 while your system only has 8.2.26
Before updating ensure that the update is compatible with your Joomla! installation.
You are strongly advised to make a backup of your site's files and database before you start updating.

what is odd is the version I installed was 9.2.1 but the messages stop at 7.0.2


AFTER the PATCH, the messages start with:

Update: Could not open update site #2 "Accredited Joomla! Translations", URL: https://update.joomla.org/language/translationlist_5.xmldemo=1
Update: Could not open update site #3 "Joomla! Update Component", URL: https://update.joomla.org/core/extensions/com_joomlaupdate.xmldemo=1
Update: Could not open update site #4 "Akeeba Backup Core for Joomla!", URL: https://cdn.akeeba.com/updates/pkgakeebabackupcore.xmldemo=1
Update: Could not open update site #5 "Patch Tester Component", URL: https://raw.githubusercontent.com/joomla-extensions/patchtester/master/manifest.xmldemo=1
plus the long list above...






<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44516">issues.joomla.org/tracker/joomla-cms/44516</a>.</sub>

**Comment by laoneo** [comment]
The DPCalendar warnings are not related to this pr. So we are RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44516">issues.joomla.org/tracker/joomla-cms/44516</a>.</sub>

**Comment by laoneo** [comment]
@fgsw did you test the pr?

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
