### PR TITLE
[4.0] Remove "fs" from package.json

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

The File System API is already built into NodeJS, so it doesn't need to be defined as a dev dependency.

### CODE REVIEW

**Comment by wilsonge** [comment]
@dgrammatiko you added this in #19426 - this seems logical to me - but giving you the ability to comment first before i regret anything :)

**Comment by dgrammatiko** [comment]
@C-Lodder just change the reference from fs to fs-extra in here https://github.com/joomla/joomla-cms/blob/540f112c481d84d1b81c58fa7956579cc578d1c4/build/build-modules-js/gzip-assets.es6.js#L6 and this will be fine:

**Comment by C-Lodder** [comment]
@dgrammatiko `Fs` is being called from the native API. `fs-extra` isn't needed in this case. The PR is purely for removing the reference to it in the `package.json` because it's native to NodeJS

**Comment by C-Lodder** [comment]
@wilsonge Just so you're aware, there's absolutely **no code** associated with this package: 
https://www.npmjs.com/package/fs

It's a purely placeholder so that people who previously used it don't run into build errors.

**Pull request merged**
