### PR TITLE
[5.2] fix upmerge error

### PR DESCRIPTION
**Pull request by brianteeman**
[5.2] Upmerge 2024-05-14 #43469 was incorrect as it updated package.json to 5.2 but only changed the lock file to 5.1.1 instead of using the lock file generated by the package.json

until this is fixed any PR for 5.2 that touches the packages will have merge conflicts

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d6fb377e66fab4d1244baa311e27e71a0e26480e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43625">issues.joomla.org/tracker/joomla-cms/43625</a>.</sub>

**Comment by brianteeman** [comment]
@pe7er this is passing the tests now

**Comment by brianteeman** [comment]
This is blocking the work to complete other PRs

**Comment by brianteeman** [comment]
You cannot release 5.2alpha without fixing this!!

**Comment by richard67** [comment]
I think it will need an update of some npm dependencies anyway, so it could maybe be fixed together with that.

**Comment by brianteeman** [comment]
Should have been fixed when it occurred instead of completely ignored. There are reasons that there are documented processes. Just ignoring them helps no one. Whilst at the time I created this pr no one but me was seriously impacted by ignoring it the refusal to look at this has now compounded the error by releasing the alpha

**Pull request closed without merging**
