### PR TITLE
UX: Additional Buttons during the installation #6422

### PR DESCRIPTION
**Pull request by ghost**
Issue: https://github.com/joomla/joomla-cms/issues/6422

Additional Next/Back Buttons in the bottom of the page, during the Joomla 3.4.x installation.

### CODE REVIEW

**Comment by nueckman** [comment]
+1
No error, no b/c issues, better usability.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6444">issues.joomla.org/joomla-cms/6444</a>.</sub>

**Comment by infograf768** [comment]
Please test this first with an RTL language.

**Comment by joomla-agency** [comment]
RTL (Persian) Screenshot
rtltest

**Comment by infograf768** [comment]
the issue is that text-right has no RTL equivalent.
Therefore we get:

screen shot 2015-03-17 at 12 55 16

**Comment by infograf768** [comment]
I would change instances of text-right to pull-right

**Comment by joomla-agency** [comment]
@infograf768 i think, for a RTL Reader is the new right button position a excepted one.

**Comment by infograf768** [comment]
If the purpose of the PR is to present the same buttons on top and bottom, then RTL or LTR should be treated equally. Until now we have always mirrored RTL button positions in all Joomla.
That's only my 2 cents.

**Comment by nueckman** [comment]
@infograf768 You're absolutly right. My bad.

**Comment by joomla-agency** [comment]
Ok. I change the Pull Request.

**Comment by infograf768** [comment]
@joomla-agency
Please do.

**Comment by joomla-agency** [comment]
@infograf768 done! Can someone test this again for LTR / RTL Support and all views?

**Comment by joomla-agency** [comment]
Two screenshots for LTR and RTL 
ltr
rtl

**Comment by designbengel** [comment]
@roland-d @joomla-agency branch is broken - maybe there is a way to restore?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6444">issues.joomla.org/joomla-cms/6444</a>.</sub>

**Comment by roland-d** [comment]
@designbengel @joomla-agency I never recovered a deleted branch but StackOverflow tells us this:
>  Yes, you should be able to do git reflog and find the SHA1 for the commit at the tip of your deleted branch, then just git checkout [sha]. And once you're at that commit, you can just git checkout -b [branchname] to recreate the branch from there.


http://stackoverflow.com/questions/3640764/can-i-recover-branch-after-its-deletion-in-git

**Comment by zero-24** [comment]
Closing as we have a redo here: #8052 by @n9iels

**Pull request closed without merging**
