### PR TITLE
[4.0] Housekeeping

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
The core.js is supposed to be the JS API of Joomla but we keep sneaking methods there with the expectation that these will be useful to somebody...
Since js is becoming more modular inflating some file is against the common practice. So there you have it, methods that are specific to some other functionality are moved to the related files.
Moved: 
- `Joomla.iframeButtonClick` The method applies only to iframes in modals, so the method is moved to the modal initiator file (legacy/bootstrap-init.js)

- `Joomla.localStorageEnabled` The method is used **only** in the backend menu so it's moved there

- `Joomla.resetFilters` The method works **only** on the search tools (filters) so it's also moved there (searchtools.js)

- Consistenly use `Joomla.Text` instead of the `Joomla.JText`. (the later is still working but deprecated)

### Testing Instructions
Check in the backend that:
- The menu still works
- Try in the Menus the Site/Administrator dropdown
- For the modal close you need to disable the redirect plugin, then go to the System->redirects and on the message that says that the plugin needs to be enabled click on the link. A modal will open change the settings then save and close. Then refresh the page. The plugin should be enabled

### TODO

- `Joomla.renderMessages` needs to be cleaned as J4 has only one messaging system so no point supporting also the Bootstrap.

- `Joomla.Event` that it was introduced in J4 some time ago needs to be **completely removed**
There is zero benefit having a shortcut for the native methods:
screenshot 2019-01-20 at 15 04 37
@Fedik do you agree on this one, as you're the one that introduced it?

### Documentation Changes Required
None

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@zero-24 why the tests are failing here? Seems unrelated

**Comment by Fedik** [comment]
> do you agree on this one, as you're the one that introduced it?

hm, need to think,
It is still good to have it, so people see that we offer/support some "joomla specific" events.
However everyone still free to use them directly.
It not that much code.

About `once` listener, well, if we do not need ie11, then can remove.

**Comment by dgrammatiko** [comment]
> About once listener, well, if we do not need ie11, then can remove.

Actually doing something similar to your approach for delivering ES6+ code to the browser you could also add this tiny polyfill https://github.com/WebReflection/dom4. So all the Event, plus a myriad of other things will be supported in IE 11 (eg closest).

> so people see that we offer/support some "joomla specific" events.

Well if Joomla is doing a middleware for Javascript something is going wrong... About the `what we offer`: Provide proper documentation of the Joomla related events and how those could be used (with examples). IIRC only subforms utilise this

**Comment by zero-24** [comment]
> @zero-24 why the tests are failing here? Seems unrelated

hmm looks good to me now. When this here is ready I would suggest to also merge 4.0-dev in so the checks run on the latest code :)

**Comment by zero-24** [comment]
This mostly fixes drone / rips issues too ;)

**Comment by Fedik** [comment]
well, `once` listener you can remove, it not that often used feature.

> Provide proper documentation of the Joomla related events and how those could be used (with examples)

Yeah sure, documentation.
For me it is not critical. I leave it for your and @wilsonge decision.

**Comment by infograf768** [comment]
Redirect plugin can now be saved, but:
The Save button also Closes the modal and the plugin is checked out.

**Comment by dgrammatiko** [comment]
Opps, side effect, will patch it later on

**Comment by infograf768** [comment]
Also, it does not solve https://github.com/joomla/joomla-cms/issues/23260 where we do have an issue in `modal-fields.js`

**Comment by dgrammatiko** [comment]
`modal-fields.js` is totally broken IIRC. That script needs to be redone as it's really bad from many aspects...

**Comment by gnanakeethan** [comment]
@dgrammatiko may I try fixing it?

**Comment by dgrammatiko** [comment]
@gnanakeethan sure, it should be custom element, similar to: https://github.com/joomla/joomla-cms/pull/20788

**Comment by gnanakeethan** [comment]
@dgrammatiko Thanks. Where should I start? 4.0-dev branch or the previously worked PR? 

Can I cherry-pick those changes otherwise?

**Comment by dgrammatiko** [comment]
I'll say fresh start...

**Comment by dgrammatiko** [comment]
@infograf768 should be fine now

**Comment by infograf768** [comment]
@dgrammatiko 
No more issue for the redirect plugin.
One notch, but it may be unrelated to this PR: the Redirect Manager is not reloaded after closing the plugin, therefore we do not get any Message about the status of the plugin.

**Comment by dgrammatiko** [comment]
> the Redirect Manager is not reloaded after closing the plugin

Yeah I've observe that as well. The good part is that the API is expecting an object so we can pass also something like 
```js
{
iframeSelector: '#selector',
buttonSelector: '.other',
refresh: true
}
```
and when the refresh part is set we refresh the page. But let's do that in another PR...

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a2b01da2027eb7370d7f71baf07f98146f692f2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23600">issues.joomla.org/tracker/joomla-cms/23600</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 @SniperSister RIPS please (tried twice so I assume it’s not a glitch)

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
@dgrammatiko 
> https://github.com/joomla/joomla-cms/pull/23600#issuecomment-456864327

Has this been done?

**Comment by dgrammatiko** [comment]
@infograf768 unless someone else made a PR for this probably not. I need to find some spare time to do this

**Pull request merged**
