### PR TITLE
[4.0] Deprecated language strings

### PR DESCRIPTION
**Pull request by brianteeman**
Remove strings previously marked as deprecated for 4.0

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bb30f8dd341e4bf63b890c8a3aaba8018a8a2821<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24267">issues.joomla.org/tracker/joomla-cms/24267</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bb30f8dd341e4bf63b890c8a3aaba8018a8a2821<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24267">issues.joomla.org/tracker/joomla-cms/24267</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24267">issues.joomla.org/tracker/joomla-cms/24267</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
