### PR TITLE
Solving Failures occuring in system tests

### PR DESCRIPTION
**Pull request by kshitijSharma2014**
.

### CODE REVIEW

**Comment by kshitijSharma2014** [comment]
@javigomez please review them
Thanks :)

**Comment by infograf768** [comment]
Please chnage title to be meaningful

**Comment by puneet0191** [comment]
@kshitijSharma2014 Looks Good thanks :+1: ,  I have tested the PR in my local it works fine :smile: Attaching some of the screenshots that I captured. 
image
image
@javigomez  We can go ahead and merge this one!

**Comment by javigomez** [comment]
closing and getting in contact with @kshitijSharma2014 for review

**Pull request closed without merging**
