### PR TITLE
[4.0] Update codemirror

### PR DESCRIPTION
**Pull request by brianteeman**
**29-09-2021: Version 5.63.1:**
Fix an issue with mouse scrolling on Chrome 94 Windows, which made scrolling by wheel move unusably slow.

**20-09-2021: Version 5.63.0:**
Fix scroll position jumping when scrolling a document with very different line heights.
xml mode: Look up HTML element behavior in a case-insensitive way.
vim bindings: Support guu for case-changing.

**20-08-2021: Version 5.62.3:**
Give the editor a translate=no attribute to prevent automatic translation from modifying its content.
Give vim-style cursors a width that matches the character after them.
merge addon: Make buttons keyboard-accessible.
emacs bindings: Fix by-page scrolling keybindings, which were accidentally inverted.

### CODE REVIEW

**Comment by thednp** [comment]
Why change `package-lock.json` and no change of the `package.json` file?

**Comment by brianteeman** [comment]
Because package.json is still valid

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 41f1d39023efb3767d14a8e04f3b6b12341c5320<br /><br />No issues found after applying PR with codemirror<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35704">issues.joomla.org/tracker/joomla-cms/35704</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 41f1d39023efb3767d14a8e04f3b6b12341c5320<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35704">issues.joomla.org/tracker/joomla-cms/35704</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35704">issues.joomla.org/tracker/joomla-cms/35704</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by PhilETaylor** [comment]
please see https://github.com/joomla/joomla-cms/pull/35769 as something somewhere is not quite right.

**Pull request merged**
