### PR TITLE
[com_fields] Change type of default value back to textarea

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for PR #12740.

### Summary of Changes
Reverts the type of default value back to textarea. Editors can have multiline default values or special lists can have newlines as separator. We will be on the safe side when we go with textarea.

### Testing Instructions
Check if the default value field is a text area.

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont see the reasoning for this change. When preparing a demo of com_fields I found I was using the simple text field more than any other. Surely the default should be the most used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12811">issues.joomla.org/tracker/joomla-cms/12811</a>.</sub>

**Comment by Bakual** [comment]
@brianteeman It's the field for the default value, not the default field.
default

**Comment by brianteeman** [comment]
Ah - thanks for clarifying

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8d8ba76c67673288066ced66360774317370d784<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12811">issues.joomla.org/tracker/joomla-cms/12811</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8d8ba76c67673288066ced66360774317370d784<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12811">issues.joomla.org/tracker/joomla-cms/12811</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
