### PR TITLE
[4.0] Match styling for cpanel tables

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Gives tables matching styling to other modules in the cpanel.

### Testing Instructions
Apply PR. Open cpanel

### Before
image

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cd67a0996aa442b1d3831357c7de89be3ddfb331<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21660">issues.joomla.org/tracker/joomla-cms/21660</a>.</sub>

**Comment by brianteeman** [comment]
I find the complete lack of any "lines" make these tables very hard to read

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on cd67a0996aa442b1d3831357c7de89be3ddfb331<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21660">issues.joomla.org/tracker/joomla-cms/21660</a>.</sub>

**Comment by brianteeman** [comment]
The template design as proposed joomla/40-backend-template#427

Has clearly defined lines to demarcate the rows

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Please remove RTC - this does not match the design

**Comment by ghost** [comment]
Status back on pending as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21660">issues.joomla.org/tracker/joomla-cms/21660</a>.</sub>

**Comment by ciar4n** [comment]
> I find the complete lack of any "lines" make these tables very hard to read

True. As this is a global change I've created a separate pr.. #21665

**Comment by ghost** [comment]
~~@ciar4n should this PR be closed?~~

**Comment by brianteeman** [comment]
with #21665 this can be made rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21660">issues.joomla.org/tracker/joomla-cms/21660</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cd67a0996aa442b1d3831357c7de89be3ddfb331<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21660">issues.joomla.org/tracker/joomla-cms/21660</a>.</sub>

**Comment by ghost** [comment]
Using PR #21660 and #21665 got Screenshot below which didn't look like joomla/40-backend-template#427 (Table Header)

screen shot 2018-08-17 at 12 22 46

**Comment by ciar4n** [comment]
joomla/40-backend-template#427 is for the article list, where this pr is for the cpanel.

The 'design' doesn't have a table header on these cpanel cards. If we insist on been strict to the design then that means removing the table header.

**Comment by ghost** [comment]
Ready to Commit after 3 successful tests.

Thanks for Comment @ciar4n, haven't looked at Article-List/cPanel.

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
