### PR TITLE
[4.2] PHP8.2 Add the missing properties to the installation JSON response

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #39655.

### Summary of Changes
Adds the missing properties to the installation JSON response.

### Testing Instructions
Install Joomla on PHP 8.2.

### Actual result BEFORE applying this Pull Request
Deprecate warnings in the Installation step when all data is entered.

### Expected result AFTER applying this Pull Request
Joomla installs fine.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 083d2ff3e4cf7938f03a643e7059897334d62f98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39660">issues.joomla.org/tracker/joomla-cms/39660</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 083d2ff3e4cf7938f03a643e7059897334d62f98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39660">issues.joomla.org/tracker/joomla-cms/39660</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39660">issues.joomla.org/tracker/joomla-cms/39660</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
