### PR TITLE
Fix timestamp format for track_date (banner)

### PR DESCRIPTION
**Pull request by twister65**
Pull Request for Issue #24649.

### Summary of Changes
Timestamp format.

### Testing Instructions

Added Instructions from https://github.com/joomla/joomla-cms/issues/24649#issue-435484411 by @franz-wohlkoenig:
- Install Joomla with examples. **The database must be postgreSQL.**
- Go to Components->Banners->Banners.
- Click Support Joomla! banner.
- Click the Banner Details tab.
- Select Yes for "Track Impressions" and "Track Clicks".
- Go to the example site: index.php/using-joomla/extensions/modules/display-modules/banner

### CODE REVIEW

**Comment by twister65** [comment]
We have #24652.

**Comment by twister65** [comment]
Reopened because the PR #24652 adds a new row for each banner track at anytime.
The counter is always 1.
We want to add a new row every hour and increment the counter.

**Comment by twister65** [comment]
@HLeithner , for review please.
See https://github.com/joomla/joomla-cms/pull/24652#issuecomment-488112113

**Comment by Pinkeltje** [comment]
I have tested this item :white_check_mark: successfully on 5404d21f741ba3e0d2e4913f83534d5f63707cea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24651">issues.joomla.org/tracker/joomla-cms/24651</a>.</sub>

**Comment by Hackwar** [comment]
This unfortunately is the wrong way to fix this. We still need to format this with ->toSQL(), since the used format() might not be the right format for the RDBMS. So you would have to modify the trackdate or create a helper trackdate which you can then format with ->toSQL.

**Comment by twister65** [comment]
@Hackwar , is that what you expect ?

**Comment by Hackwar** [comment]
I expected something along the lines of ->setMinutes(0) or something like that, but I think date objects are immutable... So it isn't really a nice solution, but should work...

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 43ebd610af19159648e796aff4c31c5a53ce4a48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24651">issues.joomla.org/tracker/joomla-cms/24651</a>.</sub>

**Comment by SharkyKZ** [comment]
@Pinkeltje please test again.

**Comment by Quy** [comment]
@alikon @richard67 can you test please?

**Comment by Quy** [comment]
@twister65 Is this still applicable considering #24652 should have fixed this issue?

**Comment by twister65** [comment]
RTC ?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba41eaa96a86e30dce6f55cb8deeafe67480ba13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24651">issues.joomla.org/tracker/joomla-cms/24651</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24651">issues.joomla.org/tracker/joomla-cms/24651</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks for the patience

**Pull request merged**
