### PR TITLE
[Hathor] Adding icon to com_associations

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Adding specific icons for header and menu for com_associations
Icon based on the side by side symbol
### Testing Instructions
Create a multilingual site.
Display Multilingual associations.

Before patch: no icons
After patch, you should get this:

screen shot 2017-04-02 at 07 57 02

No idea if a patch containing binaries will work or not with patchtester.
If not, please pick 
https://github.com/joomla/joomla-cms/compare/staging...infograf768:hathor_assoc_icon?expand=1#diff-6f72cf792495bdb18d4015f139d3ad4c
and place manually in:
` administrator/templates/hathor/images/header/icon-48-assoc.png `

As well, pick https://github.com/joomla/joomla-cms/compare/staging...infograf768:hathor_assoc_icon?expand=1#diff-03d3757f3c0056ac27f76c906c2417d3

and place in
` administrator/templates/hathor/images/menu/icon-16-assoc.png`

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 499a5c3b5e26803bc89dcd082d85f56e151434c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15050">issues.joomla.org/tracker/joomla-cms/15050</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 499a5c3b5e26803bc89dcd082d85f56e151434c9<br /><br />Patch ok for me.
All ok with patchtester<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15050">issues.joomla.org/tracker/joomla-cms/15050</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.



(I know, doing anyhting for Hathor DOES look like an April joke...
I worked a bit on the interface of com_associations and although I can get rid of some aspects ilke the display of the list, others are out of my reach, specially the filters.)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15050">issues.joomla.org/tracker/joomla-cms/15050</a>.</sub>

**Comment by ghazal** [comment]
>>>I know, doing anyhting for Hathor DOES look like an April joke...
Well, as long as it is maintained in the 3.7 distrib, it should be dealt with.

**Pull request merged**
