### PR TITLE
[4.0] Fix template params for ErrorDocument, revert #33718

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Assign the parameters to ErrorDocument to be available in error.php.
Reverts #33718.

### Testing Instructions
For backend follow #33718

For frontend:
- set a theme color to "Alternative", in Cassiopeia config.
- open non existing page to get 404 error
- make sure the template use "Alternative color"

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
@Fedik @wilsonge Should we change that in the error page ot the Cassiopeia template, too?

It uses still the way with `$params = $app->getTemplate(true)->params;` here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/error.php#L32-L33

And then `$params` in the rest of the file.

**Comment by sandramay0905** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33916">issues.joomla.org/tracker/joomla-cms/33916</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9b2e3771734c2fcd19555db8eac5052c4986c6e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33916">issues.joomla.org/tracker/joomla-cms/33916</a>.</sub>

**Comment by Fedik** [comment]
> Should we change that in the error page on the Cassiopeia template

Yes, sure. I did not looked there, thanks for checking.
I will change.

**Comment by Fedik** [comment]
changed

**Comment by richard67** [comment]
@Fedik Could you add some testing instruction for the frontend part, too? Just something like "Check if the error page in frontend still works and looks as before", so other testers know they should check that.

@sandramay0905 Could you text that, too, frontend error page, and then set your test result again in the tracker? It doesn't need to repeat the other test for backend, for that there was no change since your test. Thanks in advance and thanks for all testing up to now.

**Comment by Fedik** [comment]
updated :)

**Comment by ghost** [comment]
@richard67 Without pr i get the result see below so i'm not sure what to test: 

> image

**Comment by richard67** [comment]
@sandramay0905 Just check that it works with the PR as well as without the PR, i.e. colours are the same in both cases.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bdafe288a14bd653fcd0b64b4e22ce1ec46ef8f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33916">issues.joomla.org/tracker/joomla-cms/33916</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bdafe288a14bd653fcd0b64b4e22ce1ec46ef8f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33916">issues.joomla.org/tracker/joomla-cms/33916</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33916">issues.joomla.org/tracker/joomla-cms/33916</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Review by hans2103 — COMMENTED** [review]
nice!!
that's a much better solution!
thank you

**Pull request merged**
