### PR TITLE
[4.0] Admin Modules language alphasort

### PR DESCRIPTION
**Pull request by brianteeman**
c/s PR for alpha sort

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 47a1a80132059f22d4fa4976c61eefdcdd6ad169<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27421">issues.joomla.org/tracker/joomla-cms/27421</a>.</sub>

**Comment by jwaisner** [comment]
@brianteeman Can you provide the test instructions? Is this just an overall test of functionality?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27421">issues.joomla.org/tracker/joomla-cms/27421</a>.</sub>

**Comment by brianteeman** [comment]
Language strings should be sorted in alphabetical order. These were not. They are now. This is just a codestyle change. There is no functional difference

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 47a1a80132059f22d4fa4976c61eefdcdd6ad169<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27421">issues.joomla.org/tracker/joomla-cms/27421</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27421">issues.joomla.org/tracker/joomla-cms/27421</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
