### PR TITLE
adds the  method="upgrade" to language/en-GB/en-GB.xml

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

adds the  method="upgrade" to language/en-GB/en-GB.xml

### Testing Instructions

None / Reveiw

### Documentation Changes Required

None

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 306f59084731e0eab99d920b191bb73691486fb2<br /><br />on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14234">issues.joomla.org/tracker/joomla-cms/14234</a>.</sub>

**Comment by Bakual** [comment]
Hmm, why do you want to add that here? This isn't the extension manifest file which would be the `install.xml` for languages (notice the root tag is <metafile> and not <extension>).  The `en-GB.xml` is the declaration of the language itself.

**Comment by zero-24** [comment]
I have just compared it with the german one: https://github.com/joomlagerman/joomla/blob/master/language/de-DE/de-DE.xml#L2 But if it is not needed -> Closing.

**Comment by Bakual** [comment]
I think it can be removed from the german one instead 👍

**Pull request closed without merging**
