### PR TITLE
[4.0] Add class vars and remove 2.5 fallback

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26291

### Summary of Changes

Add class vars and remove 2.5 fallback

### Testing Instructions

make sure the plugin still works than expected

### Expected result

cleaner code

### Actual result

missing class vars and un needed 2.5er fallback

### Documentation Changes Required

none

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on d93325b45118a8abe7670fd2b8111a85f588dbfc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26851">issues.joomla.org/tracker/joomla-cms/26851</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d93325b45118a8abe7670fd2b8111a85f588dbfc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26851">issues.joomla.org/tracker/joomla-cms/26851</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26851">issues.joomla.org/tracker/joomla-cms/26851</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by zero-24** [comment]
Thanks.

**Pull request merged**
