### PR TITLE
Fix flying focus minified version

### PR DESCRIPTION
**Pull request by dneukirchen**
Fix for: 

```
Uncaught TypeError: Cannot read property 'style' of null
    at HTMLDocument.<anonymous> (flying-focus.min.js:1)
```

@dgt41

### CODE REVIEW

**Comment by C-Lodder** [comment]
Can you please add this to my repo: https://github.com/C-Lodder/flying-focus

**Comment by C-Lodder** [comment]
Still haven't got round to doing it yet.

**Comment by C-Lodder** [comment]
Can you please push the fix to my repo: https://github.com/C-Lodder/flying-focus

and I can then release an update

**Comment by dgrammatiko** [comment]
@C-Lodder it's not the code from upstream, it's just a bug introduced due to merging conflicts
@wilsonge just merge this one

**Comment by C-Lodder** [comment]
Fair enough. I'm switching to a new repo and will be pulling in the new package in a bit anyway.

**Comment by C-Lodder** [comment]
PR with new package: https://github.com/joomla/joomla-cms/pull/18048

**Comment by dneukirchen** [comment]
We can close this one. I dont know what the plans for usage of flying focus are. Imo we can remove it. I dont see the big point in using it.

**Pull request closed without merging**
