### PR TITLE
typo in FileLayout.php

### PR DESCRIPTION
**Pull request by hans2103**
replace "from from" by "from"

Pull Request for no Issue.

### Summary of Changes

This PR will fix a typo in a Doc Block

### Testing Instructions

- open file libraries/src/Layout/FileLayout.php
- goto line 24
- read the sentence
- apply patch
- read the sentence again

### Actual result BEFORE applying this Pull Request

- text on line 24: `loaded from from a layout file`

### Expected result AFTER applying this Pull Request

- text on line 24: `loaded from a layout file`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d5700d9d43ae25065d9e8c41c59d6f45e7c63bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40689">issues.joomla.org/tracker/joomla-cms/40689</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d5700d9d43ae25065d9e8c41c59d6f45e7c63bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40689">issues.joomla.org/tracker/joomla-cms/40689</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40689">issues.joomla.org/tracker/joomla-cms/40689</a>.</sub>

**Comment by obuisard** [comment]
Thanks for the PR Hans @hans2103

**Pull request merged**
