### PR TITLE
[4.0] New User form switcher

### PR DESCRIPTION
**Pull request by brianteeman**
Update the code for displaying a switcher on the admin new user form /index.php?option=com_users&view=user&layout=edit

Pull Request for Issue #24940

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman I've just tested, here is the result:
Unbenannt

Does it also need PR #24802 to be applied?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 34937e2a60d1a854e8ae5bf8daa3d96389d26856<br /><br />Testing instructions:
1. Apply other PR #24802 .
2. Run `npm run build:css`.
3. Apply this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24942">issues.joomla.org/tracker/joomla-cms/24942</a>.</sub>

**Comment by brianteeman** [comment]
This pr removes the double label - #24802 makes sure the remaining one is displayed in the correct place. it doesnt need 24802 to test the removal of the label

**Comment by richard67** [comment]
Yes, I just saw. Together both PRs make it look fine.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 34937e2a60d1a854e8ae5bf8daa3d96389d26856<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24942">issues.joomla.org/tracker/joomla-cms/24942</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24942">issues.joomla.org/tracker/joomla-cms/24942</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
