### PR TITLE
Put back Loading/ok/error images while changing permission [solve regression]

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/12843.

### Summary of Changes

In conjunction with https://github.com/joomla/joomla-cms/pull/12855 (that takes care of the search in the permissions select box), this PR corrects the CSS so the ok/error/loading image is shown again as in 3.6.4.

### Testing Instructions

Very simple test. Just CSS change.
- Go to any permissions tab and change any permission. You will notice there is no image showing loading/success/error.
- Apply patch and clear browser cache
- Go to any permissions tab and change any permission, you will now the image appears now and also the width of the columns stay stable (this is an improvement comparing to 3.6.4).
image

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by microtribe** [comment]
I have tested this item :red_circle: unsuccessfully on 8a39724b54838fd758210e966056adec65048bc6<br /><br />Went to an article, changed permissions, confirmed no loading/success/error image displayed. Applied patch through Patch Tester. Went to an article, changed permissions, still no loading/success/error image displayed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12874">issues.joomla.org/tracker/joomla-cms/12874</a>.</sub>

**Comment by infograf768** [comment]
@microtribe 
You have to clear cache after patching

@andrepereiradasilva 
Works here for LTR languages. Not for RTL

You also have to override in template-rtl.less
with
```css
/* Permissions */
#permissions-sliders span[id^="icon_"] {
	margin-right: 120px;
	width: 16px;
	display: inline-block;
	margin-left: 0;
}
```
and run generatecss.php

**Comment by brianteeman** [comment]
@andrepereiradasilva an you update for RTL please and then we can get this tested and merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12874">issues.joomla.org/tracker/joomla-cms/12874</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @infograf768 should work on rtl now too. (don't forget to clean browser cache on test)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on e54d5158263a7762f78c49a74aa719eff2df7678<br /><br />with or without PR image appears after change permission.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12874">issues.joomla.org/tracker/joomla-cms/12874</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :red_circle: unsuccessfully on e54d5158263a7762f78c49a74aa719eff2df7678<br /><br />This PR doesn't seems to be needed anymore in the latest staging. Before applying the patch the icons are already shown when changing the permissions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12874">issues.joomla.org/tracker/joomla-cms/12874</a>.</sub>

**Comment by andrepereiradasilva** [comment]
closed as seems there is no use for this since chosen was removed from this fields.
If/when chosen is readded this is waht will be needed

**Pull request closed without merging**
