### PR TITLE
Contributing.md

### PR DESCRIPTION
**Pull request by brianteeman**
Clarify the issue about creating an issue/PR so that people dont create both

Update the link to the coding standards 

Remove double spaces

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
+1

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f624c485550920c97a7aea4ae57646aeb9d1570b<br /><br />Tested by review + checked that the link to coding standards is correct now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15289">issues.joomla.org/tracker/joomla-cms/15289</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f624c485550920c97a7aea4ae57646aeb9d1570b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15289">issues.joomla.org/tracker/joomla-cms/15289</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
Thanks!

**Pull request merged**
