### PR TITLE
[4.0] Fix SQL for creating table "#__csp" in installation and schema update for PostgreSQL

### PR DESCRIPTION
**Pull request by richard67**
Remove copy and paste artifacts with MySQL syntax in create table statement for table "#__csp" from PostgreSQL installation and schema update script.

Can be merged on review.

@alikon please review.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a767a4b83b4f8ec34db80841ae7904e9452521ad<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21880">issues.joomla.org/tracker/joomla-cms/21880</a>.</sub>

**Comment by richard67** [comment]
@alikon Thanks.

**Comment by richard67** [comment]
@alikon Sorry, I updated my branch with 4.0-dev because GitHub was showing that my branch was not up to date. Now your test result was reset. Can you set it again? I will not use that button on my other 2 PRs now so you don't have to do that 3 times.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21880">issues.joomla.org/tracker/joomla-cms/21880</a>.</sub>

**Comment by richard67** [comment]
@laoneo Can this one be merged?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21880">issues.joomla.org/tracker/joomla-cms/21880</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
