### PR TITLE
Supplementary to #7637

### PR DESCRIPTION
**Pull request by dgrammatiko**
This just improves the UX by hiding the option copy/move

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks. Would it be better to submit it as a PR to my branch and the we
just have one or. Sorry I missed your comment on glip

**Comment by infograf768** [comment]
Apart from the small cs, this works fine here. Not sure we need more.

**Comment by dgt41** [comment]
@brianteeman That was my intention but I guess I messed up the procedure

**Comment by brianteeman** [comment]
@dgt41 it looks like you have merged my PR into yours. Shall I close mine and add the description of mine here?

**Comment by dgt41** [comment]
Closing this as all the code is transferred to @brianteeman ’s PR

**Comment by brianteeman** [comment]
Or will be when I do it in the morning ;)

On 6 August 2015 at 21:31, Dimitris Grammatiko <notifications@github.com>
wrote:

> Closed #7638 <https://github.com/joomla/joomla-cms/pull/7638>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7638#event-375720059>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request closed without merging**
