### PR TITLE
Improve #10314 for readd the default behavior

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #10314
#### Summary of Changes

With 3.5 you got the items of the default menu (mainmenu) when you click the first time on submenu (on the left side after clicking "menus => manage => menu items". Now you get all menu items. This patch adds the old behavior again.
#### Testing Instructions

=> Click on the mentioned path above => all items are displayed
=> Log out => apply patch => log in => Click on the mentioned path above => the items of the first accessable menu is displayed

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i'm not sure about this, but i leave that to @infograf768 who created the all menu.

**Comment by infograf768** [comment]
I disagree with this PR. The purpose of the original PR implementing All Menu Items is NOT to display a specific menu when going fo the first time through Manage, then sidebar Menu items.
It is to display as, for the specific admin menu All menu items, indeed all menu items.

**Comment by conconnl** [comment]
I agree with infograf768
The way it worked was always wrong, now it's finally correct.
You went to "Menu Items", but you did not see you menu items.
It gave you the Menu items for a certain filtered menu.
Now it displays your "Menu Items" and you can filter if you need it for a specific menu or you just click the Menu Name from the top-bar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10325">issues.joomla.org/joomla-cms/10325</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as the intended behaviour as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10325">issues.joomla.org/joomla-cms/10325</a>.</sub>

**Pull request closed without merging**
