### PR TITLE
[4.0] Fix Toolbar Buttons enable and disable

### PR DESCRIPTION
**Pull request by maliouris**
Pull Request for Issue # .

### Summary of Changes
Added the calling of connectedCallback in the constructor, because the buttonElement had undefined value. The connectedCallback was called only after the constructor and as the result buttons were enabled or disabled only after the first click.

### Testing Instructions

Check toolbars in administration mode.

### Expected result

Some buttons like batch or change status have to work only when a category (or article) is selected.

### Actual result

It works fine after this addition

### CODE REVIEW

**Comment by infograf768** [comment]
Drone failing. Please correct the unwanted tabs (useless new line)
```
/drone/src/github.com/joomla/joomla-cms/build/media_source/system/js/joomla-toolbar-button.w-c.es6.js
  28:1  error  Unexpected tab character     no-tabs
  28:1  error  Trailing spaces not allowed  no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by infograf768** [comment]
BTW, this works fine!

**Comment by infograf768** [comment]
Sorry this is stil wrong. There should be a newline only without tab and spaces.
Screen Shot 2019-03-19 at 15 51 53

**Comment by infograf768** [comment]
I corrected it directly. :)

**Comment by infograf768** [comment]
Please do not modify anymore your maliouris:4.0-dev branch

**Comment by maliouris** [comment]
Yeah sorry, I dont know why this happened

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2b0b3055d837d1825fa7b1be44a123c4b96e53de<br /><br />Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24243">issues.joomla.org/tracker/joomla-cms/24243</a>.</sub>

**Comment by infograf768** [comment]
restarted drone

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2b0b3055d837d1825fa7b1be44a123c4b96e53de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24243">issues.joomla.org/tracker/joomla-cms/24243</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24243">issues.joomla.org/tracker/joomla-cms/24243</a>.</sub>

**Comment by infograf768** [comment]
Thanks.

**Comment by Fedik** [comment]
woh, that was fast and that is wrong :smile: 

> Added the calling of connectedCallback in the constructor, because the buttonElement had undefined value. 

the fix are wrong, `connectedCallback` are part of CE API called when element actually attached to DOM. it should not be called in constructor, it for sure introduce some more fancy bugs.

A proper fix is to find out why `buttonElement` not defined,
that something went wrong with #23767

**Comment by maliouris** [comment]
I saw the changes that were made in the other pull request and as far as I can see this.buttonElement = this.querySelector('button, a'); was called in the constructor and after the change it was called in connectedCallback() with no usage at all. I moved it back to the constructor and it works properly now. Should I make a new pull request ?

**Comment by Fedik** [comment]
@maliouris yes please

**Comment by infograf768** [comment]
:)

**Comment by Fedik** [comment]
@maliouris another possible way to fix is to move this part
```javascript
    // If list selection is required, set button to disabled by default
    if (this.listSelection) {
      this.setDisabled(true);
    }
```
to `connectedCallback`, somwhere after `this.buttonElement = ...`

**Comment by maliouris** [comment]
Which one do you want think it's better?

**Comment by Fedik** [comment]
second one, but need to test whether it will work

**Comment by maliouris** [comment]
It worked for me

**Pull request merged**
