### PR TITLE
Hide promotion in TinyMCE

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Removes the Ads link for TinyMCE.

### Testing Instructions
Apply PR and active TinyMCE as default editor

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Thanks @brianteeman for the pointer, that I hit the wrong branch.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ab2debae66ee0dd80dda0e439c9fb85e0909e1a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39920">issues.joomla.org/tracker/joomla-cms/39920</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab2debae66ee0dd80dda0e439c9fb85e0909e1a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39920">issues.joomla.org/tracker/joomla-cms/39920</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39920">issues.joomla.org/tracker/joomla-cms/39920</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
