### PR TITLE
[3.9] Filesystem namespace

### PR DESCRIPTION
**Pull request by fastslack**
## Summary of Changes

Moved all libraries names to use namespace

## Testing Instructions

Use as usual, all should work fine.

## Expected result

No errors

### CODE REVIEW

**Comment by laoneo** [comment]
There are two unit tests failing. Can you have a look on them? After that it should be fine to get merged.

**Comment by fastslack** [comment]
@laoneo I'm stuck here, i dont know why there are a conflict if i'm moving that file `libraries/joomla/filesystem/path.php` to `libraries/src/Filesystem/Path.php`

**Comment by mbabker** [comment]
Because of https://github.com/joomla/joomla-cms/commit/d88bc6b7f988b93450547787f704e69578f95d12#diff-ab05fce3c8ea662bd591767ad671c853

You just need to merge the 3.9-dev branch into your branch and git should be able to work itself out (it sees there were modifications to the base file that aren't present in the moved file basically).

**Comment by fastslack** [comment]
This conflict has no sense https://github.com/joomla/joomla-cms/blob/3.9-dev/components/com_contact/controllers/contact.php#L198

**Comment by fastslack** [comment]
Sorry i broke this, im going to open a new PR

**Comment by fastslack** [comment]
https://github.com/joomla/joomla-cms/pull/19338

**Pull request closed without merging**
