### PR TITLE
[#33962] Use a proxy function to close modals.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Because otherwise, we will always be stuck with SqueezeBox/Mootools.

Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33962&start=0

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
I may need to rebase this.

**Comment by okonomiyaki3000** [comment]
Looks mergeable now.

**Comment by dgt41** [comment]
@test Success

**Comment by infograf768** [comment]
@test 
Fails. Menu Manager=>New Menu Item 
Selecting a menu item type in the modal does not close the modal anymore when item clicked.

**Comment by okonomiyaki3000** [comment]
It's my habit to make strings js safe by using json_encode but it uses double quotes which we do not want in this case. It should be safe to use a non-json encoded string here since it's the output of base64_encode and that should not contain any problematic characters. In any case, that's how the original code was working.

**Comment by infograf768** [comment]
OK now. Thanks.

**Comment by roland-d** [comment]
@test All good here as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3918">issues.joomla.org/joomla-cms/3918</a>.</sub>

**Comment by zero-24** [comment]
So the RTC state is good here. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3918">issues.joomla.org/joomla-cms/3918</a>.</sub>

**Pull request closed without merging**
