### PR TITLE
[4.2] Download Key Filters

### PR DESCRIPTION
**Pull request by brianteeman**
The text says missing but the filter says invalid. They do not mean the same.

The text says download key but the filter says valid but it doesn't validate the key it just says if the field has content or not

Strings now comply with style guide

### Testing Instructions
Install at least one extension that requires a download key. 
Test with a valid key
Test with an invalid key
Test without a key

## Before
image

## After
image

_(I'm pretty sure there was a dummy extension needing a key that was created for testing and linked to somewhere here but I cant fint it right now)_

### CODE REVIEW

**Comment by brianteeman** [comment]
please could someone restart drone

**Comment by richard67** [comment]
> _(I'm pretty sure there was a dummy extension needing a key that was created for testing and linked to somewhere here but I cant fint it right now)_

@brianteeman Did you mean this one? http://updates.myoldsite.com/file_null-1.0.zip I found it e.g. in PR #26769 .

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f6dd94a15beab6fbe7b012b19cb9bfef2c87ffa6<br /><br />Tested with this dummy extension: http://updates.myoldsite.com/file_null-1.0.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39376">issues.joomla.org/tracker/joomla-cms/39376</a>.</sub>

**Comment by brianteeman** [comment]
> > _(I'm pretty sure there was a dummy extension needing a key that was created for testing and linked to somewhere here but I cant fint it right now)_
> 
> @brianteeman Did you mean this one? http://updates.myoldsite.com/file_null-1.0.zip I found it e.g. in PR #26769 .

yes that is the one

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f6dd94a15beab6fbe7b012b19cb9bfef2c87ffa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39376">issues.joomla.org/tracker/joomla-cms/39376</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
