### PR TITLE
Update the cli nom commands

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Missed the commands in the package.json

### CODE REVIEW

**Comment by ggppdk** [comment]
now 
```
npm install
```

fails with
```
error: unknown option `--build-check'
```

**Comment by ggppdk** [comment]
We also need PR  ?
#21331 

[EDIT]
Maybe add this fix to PR #21331   ??

**Comment by dgrammatiko** [comment]
@ggppdk that was my bad 
https://github.com/joomla/joomla-cms/pull/21350/commits/3f9143b5e53a890595b08d46fddfb8dd546e7097
should fix it. Also applied the same fix in the other PR

**Comment by brianteeman** [comment]
can confirm this fixes the missing commands

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 3f9143b5e53a890595b08d46fddfb8dd546e7097<br /><br />These now finish

```
npm run build:css
npm run build:js
```

And these continue to work

```
npm install
node build.js --compile-css
node build.js --compile-js
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21350">issues.joomla.org/tracker/joomla-cms/21350</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3f9143b5e53a890595b08d46fddfb8dd546e7097<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21350">issues.joomla.org/tracker/joomla-cms/21350</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wojsmol** [comment]
`npm run build:css`
returns
```
something exploded 1
something exploded Invalid CSS after "...eed to override": expected 1 selector or at-rule, was "text-rendering: aut"
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 31
something exploded Undefined variable: "$input-btn-padding-y".
something exploded 3
something exploded 36
something exploded argument `$color` of `darken($color, $amount)` must be a color
something exploded 129
something exploded 36
something exploded argument `$color` of `darken($color, $amount)` must be a color
something exploded 129
```
npm install is working

**Comment by brianteeman** [comment]
Yes I get that too but that's not what this issue was fixing

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 3f9143b5e53a890595b08d46fddfb8dd546e7097<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21350">issues.joomla.org/tracker/joomla-cms/21350</a>.</sub>

**Comment by dgrammatiko** [comment]
@wojsmol can you send me the log file from that @ dgrammatiko at gmail com

I suspect that this is a win-dos problem but I need more info as I can not replicate it here:
screenshot 2018-08-01 at 19 51 38

**Comment by wojsmol** [comment]
@dgrammatiko  I now running npm run build:css redirected to log file - give me a moment.

**Comment by wojsmol** [comment]
@dgrammatiko log send from my gmail e-mail adress.

**Comment by dgrammatiko** [comment]
@wojsmol can you try this change?

**Comment by wojsmol** [comment]
tested on https://github.com/joomla/joomla-cms/pull/21350/commits/b496bddc78e8b97c5b3ce41bd8d01a024b449339 results

```
something exploded 1
something exploded Invalid CSS after "...eed to override": expected 1 selector or at-rule, was "text-rendering: aut"
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 7
something exploded Invalid CSS after "...ly-monospace)}}": expected "}", was ""
something exploded 1
something exploded 31
something exploded Undefined variable: "$input-btn-padding-y".
something exploded 3
something exploded 36
something exploded argument `$color` of `darken($color, $amount)` must be a color
something exploded 129
something exploded 36
something exploded argument `$color` of `darken($color, $amount)` must be a color
something exploded 129
```

**Comment by dgrammatiko** [comment]
can I have the log created there (not the terminal output)

**Comment by wojsmol** [comment]
log send via mail

**Comment by ggppdk** [comment]
On windows 10

There seems to be a problem with new line endings
with file
media\vendor\font-awesome\scss\_mixins.scss

this can not be right ?
a lot of wrong stuff in the same line , the syntax is broken

```css
// Mixins // -------------------------- @mixin fa-icon(){display:inline-block;font:normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base}FontAwesome;// shortening font declaration font-size:inherit;// can't have font-size inherit on line above, so need to override
  text-rendering: auto; // optimizelegibility throws things off #1094
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;

}
```

Also same problem with line endings with file,
`\media\vendor\bootstrap\scss\_root.scss`
comments and code everything in 1 line

and other files

**Comment by brianteeman** [comment]
Good find.

**Comment by ggppdk** [comment]
And it seems i committed non-updated CSS files in this PR #21316 (when i resolved conflicts ?)
because i did them on ... windows ?

**Comment by wilsonge** [comment]
Merging this as it solves the immediate test problems. But obviously still windows problems to fix in a further PR

**Comment by dgrammatiko** [comment]
@ggppdk can you try changing the default line ending as described here: https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows/13154031#13154031

Does this work?

**Comment by ggppdk** [comment]
@dgrammatiko, i was thinking to look for a nodejs setting , but if these files are created from repository files thar are checked out by git, then your suggestion , makes sense, will try in the evening and post back, thanks

**Pull request merged**
