### PR TITLE
REGRESSION: Correcting #17694

### PR DESCRIPTION
**Pull request by infograf768**
After patch, articles display again from featured, blog, category list in frontend.

### CODE REVIEW

**Comment by infograf768** [comment]
Corrects #17694

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2be5f47d3df44ad25b3e83f9d1c13388094649e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17697">issues.joomla.org/tracker/joomla-cms/17697</a>.</sub>

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 2be5f47d3df44ad25b3e83f9d1c13388094649e2<br /><br />It at least brings back the frontend article list<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17697">issues.joomla.org/tracker/joomla-cms/17697</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
