### PR TITLE
Improve articles and newsfeeds backend list performance

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #23090.

### Summary of Changes

Same as #26466 and #26495 but for staging. Improves backend list performance by removing `DISTINCT` use from query.

### Testing Instructions

Create some articles and newsfeeds with tags.
Filter articles and newsfeeds by single and multiple tags.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b8777032993cddf56ae9f572ad8a194f9a4b4fca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27339">issues.joomla.org/tracker/joomla-cms/27339</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on b8777032993cddf56ae9f572ad8a194f9a4b4fca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27339">issues.joomla.org/tracker/joomla-cms/27339</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27339">issues.joomla.org/tracker/joomla-cms/27339</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
