### PR TITLE
[4.0] namespace error

### PR DESCRIPTION
**Pull request by brianteeman**
Go to administrator/index.php?option=com_privacy&view=capabilities

You will get an error Class Text not found

Apply this PR

Problem solved

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6f62861ca9f40c4569ce4801c76c3c0bcb8caf5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25089">issues.joomla.org/tracker/joomla-cms/25089</a>.</sub>

**Comment by lavipr** [comment]
I have tested this item :white_check_mark: successfully on 6f62861ca9f40c4569ce4801c76c3c0bcb8caf5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25089">issues.joomla.org/tracker/joomla-cms/25089</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25089">issues.joomla.org/tracker/joomla-cms/25089</a>.</sub>

**Comment by roland-d** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
