### PR TITLE
Very small language file cs

### PR DESCRIPTION
**Pull request by infograf768**
A space too much after the double quote.
Not very important. Can be merged on review.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Comment by zero-24** [comment]
Merged thanks.

**Comment by zero-24** [comment]
@infograf768 this is 3.8.9 not 3.9.0 :P

**Comment by infograf768** [comment]
> @infograf768 this is 3.8.9 not 3.9.0 :P

Not really. Language is frozen since RC... thus why I milestoned it to 3.9

**Comment by infograf768** [comment]
too late now...

**Comment by zero-24** [comment]
It was just a space in a en-GB file? Why should this wait until a new minor release and can not go into the next patch release?

**Comment by infograf768** [comment]
Because, any change after lang freeze is automatically going to be added in Crowdin and force TTs using that system to review their packs if they have already made them...
As I do not use crowdin, I personally don't care.

**Pull request merged**
