### PR TITLE
[4.x] Fix default language value for taxonomy rows

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
So far com_finder taxonomy rows had an empty string as default parameter for the language column. Taxonomy rows with that empty string became unselectable one the multilanguage feature was enabled, as the language filter only filtered for the current language and the * character, see:
https://github.com/joomla/joomla-cms/blob/4.4-dev/administrator/components/com_finder/src/Service/HTML/Filter.php#L306

### Testing Instructions
* Run the finder indexer, view the #__finder_taxonomy table and check the taxonomy column values. 
* Apply the patch. 
* Reindex
* Check the DB table again

### Actual result BEFORE applying this Pull Request
Rows with empty string.

### Expected result AFTER applying this Pull Request
Rows with empty strings are now using * as value

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on c61e65b978d5319b8605815eea38f5116040d54b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43990">issues.joomla.org/tracker/joomla-cms/43990</a>.</sub>

**Comment by SniperSister** [comment]
@fgsw thanks for testing, that's very much appreciated! I have pushed another commit that will also  fix the language in the first taxonomy levels that you marked red in your screenshot. Could you please re-rest? THANK YOU!

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0120dfdc7b303097eaebb81f5f577e3fe187cb4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43990">issues.joomla.org/tracker/joomla-cms/43990</a>.</sub>

**Comment by ChristineWk** [comment]
@fgsw Thank you for screenshots for my better understanding :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43990">issues.joomla.org/tracker/joomla-cms/43990</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0120dfdc7b303097eaebb81f5f577e3fe187cb4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43990">issues.joomla.org/tracker/joomla-cms/43990</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43990">issues.joomla.org/tracker/joomla-cms/43990</a>.</sub>

**Pull request merged**
