### PR TITLE
[4.1] Use emojis vs google fonts for the accessibility plugin

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #36928

### Summary of Changes

Set "useEmojis" as recommended by the docs: https://ranbuch.github.io/accessibility/#icon-image

### Testing Instructions

Apply this PR and make sure no google fonts are loaded when using the accessibility plugin

### Actual result BEFORE applying this Pull Request

Before this change the default value is used which uses google fonts.

### Expected result AFTER applying this Pull Request

We no longer use google fonts but emojis.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 53640b15a80f4f0bc665fbfa9a9dcd4f9bffccd1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36948">issues.joomla.org/tracker/joomla-cms/36948</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 53640b15a80f4f0bc665fbfa9a9dcd4f9bffccd1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36948">issues.joomla.org/tracker/joomla-cms/36948</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36948">issues.joomla.org/tracker/joomla-cms/36948</a>.</sub>

**Comment by brianteeman** [comment]
Can you hold on merging this. The script has been broken upstream

**Comment by brianteeman** [comment]
Just checked and this change will actually resolve the bug upstream

**Comment by laoneo** [comment]
@brianteeman so it is ok now to merge?

**Comment by brianteeman** [comment]
Well that depends. It has a side benefit of fixing #37050 which is an upstream bug. But it also exposes another upstream bug https://github.com/joomla/joomla-cms/issues/37050#issuecomment-1041443190 although thats much less severe.

**Comment by zero-24** [comment]
But both issues are expected to be patched upstream right? So i would say this can go in while upstream issues still have to be tracked.

**Comment by laoneo** [comment]
Is there an issue open we can reference here?

**Comment by chmst** [comment]
Thanks

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
