### PR TITLE
[4.0] Remove unused file

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes `build/media_source/system/scss/_jalert.scss` which is unused.

### Testing Instructions

Run `node build/build.js --compile-css` and check that it completes without errors.

### Expected result AFTER applying this Pull Request

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3f6c7bf37f9a18e0f3229b0741d09d7f1c091936<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31198">issues.joomla.org/tracker/joomla-cms/31198</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 3f6c7bf37f9a18e0f3229b0741d09d7f1c091936<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31198">issues.joomla.org/tracker/joomla-cms/31198</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31198">issues.joomla.org/tracker/joomla-cms/31198</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
