### PR TITLE
[4.1] `Maintainence` should be `Maintenance`

### PR DESCRIPTION
**Pull request by brianteeman**
Can be merged on review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 024a7d8029e27e6daaf95316e4ebd3ba857b5381<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37023">issues.joomla.org/tracker/joomla-cms/37023</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 024a7d8029e27e6daaf95316e4ebd3ba857b5381<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37023">issues.joomla.org/tracker/joomla-cms/37023</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37023">issues.joomla.org/tracker/joomla-cms/37023</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
