### PR TITLE
#10911 Fix of com_banners export tracks modal tooltip

### PR DESCRIPTION
**Pull request by RonakParmar**
Pull Request for Issue #10911 .
#### Summary of Changes

Added basic div structure of label and field.
#### Testing Instructions

Goto->components->Banners->Tracks
Click on Export button, pop-up will appear.
Hove label on the pop-up and check position of the tooptip.

### CODE REVIEW

**Comment by ggppdk** [comment]
It works, but if you do a search for 
```
if ($field->hidden)
```

In most cases you will see the hidden fields are added without a container:
```
<?php if ($field->hidden) : ?>
	<?php echo $field->input; ?>
<?php else: ?>
```
but there are a couple that add the container to hidden field, which results in undesired spacing

- i know, that in this case 

neither the XML file does not have hidden fields,
nor are any hidden fields are created dynamically and added to the form

**Comment by kalpesh681** [comment]
I have tested this item :white_check_mark: successfully on 2072bbf99490b7d95e35f6fcb5a613b510d6b4c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10927">issues.joomla.org/joomla-cms/10927</a>.</sub>

**Comment by hardiktasol** [comment]
I have tested this item :white_check_mark: successfully on 2072bbf99490b7d95e35f6fcb5a613b510d6b4c5<br /><br />Now tooltip showing above label.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10927">issues.joomla.org/joomla-cms/10927</a>.</sub>

**Comment by ggppdk** [comment]
It works,
but the container does not have enough room at the top to show the tooltip of the "File name" field, tooltip is cut-off

**Comment by andrepereiradasilva** [comment]
@JoomliC can you check if this one also?

**Comment by JoomliC** [comment]
@andrepereiradasilva Thank you to alert me on this PR! ;-)
I was too busy last 10 days to keep working on modals improvement, but i'm back a bit at it.
This one is one of the modals i don't have yet review.

Well... i have almost a PR ready for this one, but with more changes to integrate better in a bootstrap modal.
In the same time, my purpose is to use a new layout for toolbar modal button (as no generic one excepted the "popup" one, but not best for BS modal). My goal was to improve modal button in toolbar (batch modals, settings in com_messages...)

About this PR, i have indeed many comments (and this one is not ok to be commit) : 
- as content view loading in a iframe, the tooltip placement should be bottom (top is not possible when iframe in a bootstrap modal, as truncated at top).
- The code style is not ok.

There a preview of what i've already done (and if needed, i can finish a PR for this one this week-end) : 
capture d ecran 2016-06-25 a 17 04 16

As you can see, more changes : 
- No tooltip for base name, as description is a bit long (and not always easy to use tooltip when long description).
- Tooltip placement bottom for Compressed field
- Buttons in the BS modal footer
- Using new viewport dimensions
- appendButton using a new toolbar button layout : 
```
$selector   = $displayData['selector'];
$class      = isset($displayData['class']) ? $displayData['class'] : 'btn btn-small';
$icon_class = isset($displayData['icon_class']) ? $displayData['icon_class'] : 'icon-out-3';
$title      = isset($displayData['title']) ? $displayData['title'] : '';
?>
<button class="<?php echo $class; ?>" data-toggle="modal" data-target="#<?php echo $selector; ?>">
	<span class="<?php echo $icon_class; ?>" title="<?php echo $selector; ?>"></span>
	<?php echo $title; ?>
</button>
```

As you can see, i have tried to do a generic button layout to open a modal, which one is generated directly in the view file (for tracks download, directly generated in tracks view).

**Comment by brianteeman** [comment]
That looks good @joomlic<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10927">issues.joomla.org/joomla-cms/10927</a>.</sub>

**Comment by JoomliC** [comment]
I have just created a PR with the new toolbar button layout, and full refactory of the com_banners tracks export modal : https://github.com/joomla/joomla-cms/pull/10934
;-)

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10927">issues.joomla.org/joomla-cms/10927</a>

**Comment by gunjanpatel** [comment]
Closing as it is covered in #10934<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10927">issues.joomla.org/joomla-cms/10927</a>.</sub>

**Pull request closed without merging**
