### PR TITLE
[4.0] Don't ship .es6 files

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/29092.

### Summary of Changes

Excludes .es6 files from being copied to media directory.

### Testing Instructions

Download and install this package https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/31201/downloads/36975/Joomla_4.0.0-beta5-dev+pr.31201-Development-Full_Package.zip.
Check that JS functionality still works (e.g. messages, modals, form validation).
Check if `media/system/js/core.es6` directory exists.

### Expected result

`media/system/js/core.es6` directory doesn't exist and JS functionality works properly.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by particthistle** [comment]
@SharkyKZ, the Install package mentioned in the test instructions is not available yet.

**Comment by SharkyKZ** [comment]
It's available now. Added the link in testing instructions.

**Comment by HLeithner** [comment]
Can we exclude the "*.es6" folder too?

**Comment by SharkyKZ** [comment]
@HLeithner should be OK now.

**Comment by HLeithner** [comment]
thx

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 9ddfda2f1ce4a487e4ea441a4bf6593eba175463<br /><br />Performed a fresh install with the new package

- `media/system/js/core.es6` directory doesn't exist and JS functionality works properly.
- no errors discovered while performing some random checks of javascript functions, which is expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31201">issues.joomla.org/tracker/joomla-cms/31201</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9ddfda2f1ce4a487e4ea441a4bf6593eba175463<br /><br />No errors after fresh install on provided package. Checked various functionalities with no errors as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31201">issues.joomla.org/tracker/joomla-cms/31201</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31201">issues.joomla.org/tracker/joomla-cms/31201</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by richard67** [comment]
@HLeithner @wilsonge As these .es6 and scss files and the es6 folder will not be included into the next Beta (or RC?) build, it would need to include them into the list of files and folders to be deleted in script.php so they are deleted when updating previous 4 Beta versions, or not?

**Comment by HLeithner** [comment]
This is part of the release process.

**Comment by richard67** [comment]
Yes, I know .. it was forgotten when doing Beta 4 (Beta 5 was ok then), so I thought I set a reminder.

**Pull request merged**
