### PR TITLE
[4.1] Fix task queue behavior with orphaned tasks

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36435.

### Summary of Changes
Excludes orphaned tasks from TaskModel::getTask()'s task locking query so don't end up acquiring locks/trying to run orphaned tasks.

### Testing Instructions
- Create task with a short interval based rule
- Orphan the task by disabling the parent plugin.
- Wait for the task to be triggered

### Actual result BEFORE applying this Pull Request
The task is triggered, a "running" icon indicating a lock on the task is visible on visiting the Task Manager.

### Expected result AFTER applying this Pull Request
The task is not triggered.

### Documentation Changes Required
\-

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on be01cf8f100656495476d1ed372cbeaaab1d27e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36436">issues.joomla.org/tracker/joomla-cms/36436</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on be01cf8f100656495476d1ed372cbeaaab1d27e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36436">issues.joomla.org/tracker/joomla-cms/36436</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36436">issues.joomla.org/tracker/joomla-cms/36436</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
