### PR TITLE
First attempt at a poor-php-configuration travis build

### PR DESCRIPTION
**Pull request by PhilETaylor**

### CODE REVIEW

**Comment by PhilETaylor** [comment]
So @mbabker setting a crappy memory_limit of 8M means UnitTests cannot run... so is my through of attempting to set up a crappy web server kind of environment in travis a lost cause?

`PHP Fatal error:  Allowed memory size of 8388608 bytes exhausted (tried to allocate 121 bytes) in /home/travis/build/joomla/joomla-cms/libraries/vendor/phpunit/phpunit/src/Framework/TestSuite.php on line 557
`
I have upped the memory limit again but left in disable_functions taken from first google result of https://www.cyberciti.biz/faq/linux-unix-apache-lighttpd-phpini-disable-functions/ as well as parse_ini_file: 

`disable_functions = parse_ini_file,exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source`

**Comment by mbabker** [comment]
The memory limit thing you can't get around, it's just resource intensive.  The rest of it though you should be able to play with.

**Comment by PhilETaylor** [comment]
ah something to do with "proc_open" :) which is now disabled... 

If only it told you what test was being run at that time ?

**Comment by PhilETaylor** [comment]
I give up.

Somewhere in JSessionTest causes phpunit to die - I spent an hour trying to find out why, but I think its deep in phpunit. 

```
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available


Starting test 'JSessionTest::testGetInstance with data set "first_instance" ('none', array(99), 'Line: 90: Should not be a dif...change')'.
Undefined variable: pipes
```

**Pull request closed without merging**
