### PR TITLE
[com_finder] - fix warning on search when not found

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #17731 .

### Summary of Changes
fix total  check

### Testing Instructions
see #17731

### Expected result
no warning

### Actual result
waring

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1a744e7b6d276ee5c1f21abdf0e27eb724d7646d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17732">issues.joomla.org/tracker/joomla-cms/17732</a>.</sub>

**Comment by sandewt** [comment]
Hi @alikon,

What do you think of: 

```php
<?php if ($this->total === 0 || $this->total === null) : ?>
```

Instead of: 
```php
<?php if (($this->total === 0) || ($this->total === null)) : ?>
```

In line 36, file ..\components\com_finder\views\search\tmpl\default_results.php ???

Gr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17732">issues.joomla.org/tracker/joomla-cms/17732</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 1a744e7b6d276ee5c1f21abdf0e27eb724d7646d<br /><br />See note above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17732">issues.joomla.org/tracker/joomla-cms/17732</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
