### PR TITLE
Handle spaces in filenames of Media Manager uploads

### PR DESCRIPTION
**Pull request by ralain**
Redo PR #9608 per request of @Kubik-Rubik

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on ec6a257f644d9b01b39ce964f970abe44b273218<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9650">issues.joomla.org/joomla-cms/9650</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on ec6a257f644d9b01b39ce964f970abe44b273218<br /><br />and tested on review as nothing changed since #9608 - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9650">issues.joomla.org/joomla-cms/9650</a>.</sub>

**Comment by wilsonge** [comment]
Need to do a RC2 after this mornings marathon and also some more UTF8MB4 fixes so merging this for 3.5.1 again

**Comment by Kubik-Rubik** [comment]
@wilsonge Thanks! :-)

**Pull request merged**
