### PR TITLE
[com_redirect] Add HTTP status code filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

Following https://github.com/joomla/joomla-cms/pull/10217, this PR adds a new status code filter to com_redirect.

image
#### Testing Instructions
1. Apply patch on latest staging
2. Go to Components -> Redirect and test the new HTTP status code filter.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7bb54c753db9573ac232ab49a2e4cc254c5ca969<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10312">issues.joomla.org/joomla-cms/10312</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7bb54c753db9573ac232ab49a2e4cc254c5ca969<br /><br />it works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10312">issues.joomla.org/joomla-cms/10312</a>.</sub>

**Comment by zero-24** [comment]
I have movend it to needs review so the PLT can decide to add this filter or not. as per default this option is disabled but we can't disable or enable the filter based on that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10312">issues.joomla.org/joomla-cms/10312</a>.</sub>

**Comment by andrepereiradasilva** [comment]
the option in new/edit is (some nonsense of advanced mode IMHO).
But the status columns is always there.

**Comment by zero-24** [comment]
i can't see it here @andrepereiradasilva 

redirects

**Comment by andrepereiradasilva** [comment]
arwe you using latest staging?

**Comment by andrepereiradasilva** [comment]
see here https://github.com/joomla/joomla-cms/commit/bb1911eacd7ee7d9f2ba9671551c20a80c643f1e

**Comment by Kubik-Rubik** [comment]
Good change, thank you @andrepereiradasilva!

**Comment by andrepereiradasilva** [comment]
thansk for testing, comments and merging!

**Pull request merged**
