### PR TITLE
Fixes #8381 - JForm::getFieldAttribute

### LINKED ISSUE #8381: Possible BUG in jForm getFieldAttribute
Hello, I have an instance of a form, I'm trying to get the default value of the field in the xml, in this case the default value is 0 (zero).

The problem occurs in getFieldAttribute role in "libraries/joomla/form/form.php"

This will return false because the default value is 0
if (($element instanceof SimpleXMLElement) && ((string) $element[$attribute]))

I believe that the correct test would be:
if (($element instanceof SimpleXMLElement) && isset($element[$attribute]))

The correct is to test if the attribute exists.

http://www.widesys.com.br/getFieldAttribute.webm

Thank you

### PR DESCRIPTION
**Pull request by izharaazmi**
Fixes #8381 Currently returns false when attribute value is "0", this fix makes it return "0" only.

### CODE REVIEW

**Comment by izharaazmi** [comment]
@test success as reported by @widesys https://github.com/joomla/joomla-cms/issues/8381#issuecomment-157912821

**Comment by mxkmp29** [comment]
I have tested this item :white_check_mark: successfully on 3f26c3b4a3b46a965953a0774b258cb02f7cb6c3<br /><br />@icampus 
Works as specified.
Reproduced the error: 
in a xml view a field with default = 0. Called the funktion getAttribute(fieldname, default) returned **null**. After the patch the result was **'0'**. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8383">issues.joomla.org/joomla-cms/8383</a>.</sub>

**Comment by mehmetalipamukci** [comment]
I have tested this item :white_check_mark: successfully on 3f26c3b4a3b46a965953a0774b258cb02f7cb6c3<br /><br />tested @icampus
1. Reproduced Error on a basic component (default value "0" of a field returns null instead of "0")
2. Applied the patch 
Result: Fixed the Problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8383">issues.joomla.org/joomla-cms/8383</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8383">issues.joomla.org/joomla-cms/8383</a>.</sub>

**Pull request merged**
