### PR TITLE
[4.3] Use CSRF only for the site's domain

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request is alternative to #39343

### Summary of Changes

- CSRF is always sent with the `Joomla.request` ONLY for the site's domain
- The CSRF could be manually added for a foreign domain with a custom header `headers: {'X-CSRF-Token': Joomla.getOptions('csrf.token', '')} `

### Testing Instructions
- Go to `/administrator/index.php?option=com_config` and try to send a test mail, it should work (assuming your test site is properly set the mail server)
- The server should respond with a 200
- the url was modified to remove the form token, to make sure that CSRF was used
- Relative local domain modify [the url](https://github.com/joomla/joomla-cms/blob/226391c8e9375c763383cb7fb073871eaa85f8b4/administrator/components/com_config/tmpl/application/default_mail.php#L37) to:
```php
$ajaxUri = \Joomla\CMS\Uri\Uri::base(true) . '/index.php?option=com_config&task=application.sendtestmail&format=json';
```
refresh the page and run click on the send test mail again, observe the request (in the browser console) that has the x-csrf

Screenshot 2023-01-09 at 17 12 57

- Absolute local domain modify [the url](https://github.com/joomla/joomla-cms/blob/226391c8e9375c763383cb7fb073871eaa85f8b4/administrator/components/com_config/tmpl/application/default_mail.php#L37) to:
```php
$ajaxUri = \Joomla\CMS\Uri\Uri::base(false) . '/index.php?option=com_config&task=application.sendtestmail&format=json';
```
refresh the page and run click on the send test mail again, observe the request (in the browser console) that has the x-csrf

- Foreign domain modify [the url](https://github.com/joomla/joomla-cms/blob/226391c8e9375c763383cb7fb073871eaa85f8b4/administrator/components/com_config/tmpl/application/default_mail.php#L37) to:
```php
$ajaxUri = 'https://www.joomla.org/4/administrator/index.php?option=com_config&task=application.sendtestmail&format=json';
```
refresh the page and run click on the send test mail again, observe the request (in the browser console) that has the x-csrf
Screenshot 2023-01-09 at 17 24 04

### Actual result BEFORE applying this Pull Request

CSRF send to all domains

### Expected result AFTER applying this Pull Request

CSRF is only for local use

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
The last commit aligns the code with the jQuery proven code: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#jquery

**Comment by dgrammatiko** [comment]
@Fedik can you review this one?

**Comment by Fedik** [comment]
I think https://github.com/joomla/joomla-cms/pull/39343 will be better, because it gives you more controll over the code. (and I would prefer to avoid use of `rootFull`)

**Comment by Fedik** [comment]
hmhm, or can we combine both PRs? When `sendCsrfToken` is `null` then compare domains, when it true/false then ignore domain?
And use `location.origin` instead of `rootFull`.
And remove `GET|HEAD|OPTIONS` testing.

**Comment by dgrammatiko** [comment]
>  because it gives you more control over the code

Ehm, that PR is not actually solving the leak if the devs won't explicitly use the new option. BTW devs could still push whatever they want with a custom header (it will override as it happens later):

```js
Joomla.request({
  method: 'POST',
  url: 'https://www.joomla.org/administrator/index.php?option=com_config&task=application.sendtestmail&format=json',
  headers: {'X-CSRF-Token': Joomla.getOptions('csrf.token', '')} // Manually force sending the CSRF on a foreign domain NOT SAFE!!!!
});
```

**Comment by Fedik** [comment]
Yeap, looks better now, and much more clean :)

> document.location.origin

btw, is part of [Window object](https://developer.mozilla.org/en-US/docs/Web/API/Window/location), window.location.origin, or in `js-cs` window is undefined?

**Comment by HLeithner** [comment]
if we get 2 tests we can merge this @SniperSister can you please have  a look as jsst ?

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5cb5e38a99bc7f7ed572b8b3951c65808b323c3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39580">issues.joomla.org/tracker/joomla-cms/39580</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39580">issues.joomla.org/tracker/joomla-cms/39580</a>.</sub>

**Comment by SniperSister** [comment]
Makes perfect sense, fine for me!

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for this PR!

**Comment by wilsonge** [comment]
See https://github.com/joomla/joomla-cms/issues/39969 suspect we might need to head back to the original patch

**Comment by dgrammatiko** [comment]
> See https://github.com/joomla/joomla-cms/issues/39969 suspect we might need to head back to the original patch

Honestly the project should deprecate the Joomla.request and transition to fetch (without any magic wrapper).

FWIW if the patch doesn't cover all the case then just do complete revert of this 🤷‍♂️

**Comment by wilsonge** [comment]
> Honestly the project should deprecate the Joomla.request and transition to fetch (without any magic wrapper).

I mean we'd still need to document all this stuff in CSRF tokens anyhow. Not really sure doing that fixes anything in respect of this (totally understand fetch is better than the xhr stuff we're wrapping and don't dispute moving to that makes a huge amount of sense)

**Comment by dgrammatiko** [comment]
> I mean we'd still need to document all this stuff in CSRF tokens anyhow.

Yes, this is crucial to be communicated properly as the leaking of CSRF could easily lead to a complete compromise of the site.

> Not really sure doing that fixes anything in respect of this

Actually, this bug reveals one more thing that is done awfully wrong in the XHR wrapper and also in the server side response. The XHR response on either the onSuccess or the onError should should be checked that is ok (ie the request asked for JSON and the response is not) also the response from the server should NOT be a 200 but something like 4XX or 5XX.
What is needed is the complete array of the valid url strings and figure out if we could code the conditional to cover all of them (obviously this PR overlooked the case that the url could be done against the base url).

Anyways what I was actually proposing was the immediate deprecation of the `Joomla.request` without a replacement and start migrating the ajax requests to fetch. BTW fetch already supports [full duplex](https://github.com/web-platform-tests/wpt/issues/7693) on Chrome stable (FF, safari probably on their beta but that's not a show stopper)

**Pull request merged**
