### PR TITLE
Removing the gallery field plugin from core

### PR DESCRIPTION
**Pull request by infograf768**
As it seems that we can't really make this plugin useful as is or as proposed in https://github.com/joomla/joomla-cms/pull/14238

Here is a PR to remove it entirely from core.

Please verify that I have not forgotten anything.

@rdeutz @dgt41 @laoneo @Bakual

### CODE REVIEW

**Comment by zero-24** [comment]
Language files?

**Comment by infograf768** [comment]
yep, will update tomorrow

**Comment by infograf768** [comment]
Done.

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 7b4cdd5f8cad1cd835e09f78c33ec103a4a772c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14309">issues.joomla.org/tracker/joomla-cms/14309</a>.</sub>

**Comment by laoneo** [comment]
The js and CSS files should also be deleted from here https://github.com/joomla/joomla-cms/tree/staging/media/plg_fields_gallery

**Comment by infograf768** [comment]
Done.

**Comment by shivamdiehard** [comment]
I have tested this item :white_check_mark: successfully on 8101a7127baafb5da261e43992938bfc0e708c0c<br /><br />After applying the patch the gallery field plugin exists no more.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14309">issues.joomla.org/tracker/joomla-cms/14309</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz 
Looks like OK now. We just need a decision from you on this.

**Comment by shivamdiehard** [comment]
Was this issue related to only code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14309">issues.joomla.org/tracker/joomla-cms/14309</a>.</sub>

**Comment by infograf768** [comment]
> Was this issue related to only code review.

Indeed, and also approving the remove taking into account the issues and poor usability.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 1928c2b20f03493a42795393e6989e767d2d972b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14309">issues.joomla.org/tracker/joomla-cms/14309</a>.</sub>

**Comment by infograf768** [comment]
RTC as all aspects of the removal are now taken care of.

Thanks all. We now wait for PLT final decision.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14309">issues.joomla.org/tracker/joomla-cms/14309</a>.</sub>

**Pull request merged**
