### PR TITLE
[4.0][admin menu] fix creating from preset on postgresql

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
use the ?? (Null Coalescing Operator) to get 0 instead of ""

### Testing Instructions
create an admin using  Import a preset

### Expected result
able to create admin menu

### Actual result
SQL ERROR:  invalid input syntax for integer: ""

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bbeb9fd31e79b82d3b661b48985cb944c0c278ee<br /><br />Fixes the mentioned SQL error.

Other oddities with custom admin menus and presets on PostgreSQL or other PostgreSQL issues are not subject of this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25949">issues.joomla.org/tracker/joomla-cms/25949</a>.</sub>

**Comment by Quy** [comment]
Please confirm that this will fix #26713.

**Comment by waader** [comment]
@Quy: the error has gone, but also all menu items.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25949">issues.joomla.org/tracker/joomla-cms/25949</a>.</sub>

**Comment by alikon** [comment]
i can confirm @waader  findings 
....2 months after ..... this PR is ....  
closing

**Comment by richard67** [comment]
@alikon Maybe you should just have used 1 instead of 0 as default? The menu item with id 1 is the root, and this is also the default value for the parent_id column in the menu table in database. Do you want to make a new PR for it?

**Comment by alikon** [comment]
@richard67 done #26807

**Pull request closed without merging**
