### PR TITLE
[Sub-form] Validation message for repeatable-table layout of sub-form getting blank #27888

### PR DESCRIPTION
**Pull request by manav014**
Pull Request for Issue # 27888.

### Summary of Changes
Added an error message in validate.js located in media/system/js directory.

### Testing Instructions
Login to administrator
Goto Email Domain Options of user config and add domain.
Domain name is a required field.
Save domain name with a blank value.

### Expected result
The error message should show as Invalid field: Domain Name

### Actual result
The error message shows invalid form field value.

### Documentation Changes Required
N/A

### CODE REVIEW

**Comment by richard67** [comment]
@manav014 Sorry to say, but this PR is (partly) wrong.

You have to edit the uncompressed, i.e. unminified version of the js file here: [https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate-uncompressed.js](https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate-uncompressed.js), and not the minified version which you edited now in this PR.

When that is done you have to minify that script using an online tool. @dgrammatiko @Fedik You can recommend a tool?

This minified script then you put into your local git clone to your branch for this PR, or upload it to that branch on GitHub, with name and location equal to the file you have modified now with this PR here, i.e. [https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate.js](https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate.js), i.e. replace the file now having been edited in this PR by the one created from the previously mentioned unminified file using the online tool.

Let us know if you have questions.

**Comment by Fedik** [comment]
I suspect, the fix for #27888 need to be on server side, I hardly imagine what with JS can be done there

**Comment by richard67** [comment]
@manav014 I think @Fedik is right, and the fix has to be made at another place but not in the JS.

Anybody out there who could advise further?

**Comment by SharkyKZ** [comment]
As mentioned in previous PR, it's because fields in repeatable-table layout don't output a label. There is a label in the header so maybe we could connect it to fields with `aria-labelledby` or similar method.

In 4.0 this fixed, intentionally or not, by always rendering labels even if they're supposed to be hidden. It's also why Switcher has double labels.

**Comment by manav014** [comment]
> @manav014 Sorry to say, but this PR is (partly) wrong.
> 
> You have to edit the uncompressed, i.e. unminified version of the js file here: https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate-uncompressed.js, and not the minified version which you edited now in this PR.
> 
> When that is done you have to minify that script using an online tool. @dgrammatiko @Fedik You can recommend a tool?
> 
> This minified script then you put into your local git clone to your branch for this PR, or upload it to that branch on GitHub, with name and location equal to the file you have modified now with this PR here, i.e. https://github.com/manav014/joomla-cms/blob/first-commit/media/system/js/validate.js, i.e. replace the file now having been edited in this PR by the one created from the previously mentioned unminified file using the online tool.
> 
> Let us know if you have questions.

Hii @richard67 i have completed the changes in uncompressed file and just want to know which software is used by joomla to to minify the script so that i can minify that. I would be glad if you may please help me out with this.

**Comment by brianteeman** [comment]
For joomla 3 you can use pretty much any js minifier.

**Comment by richard67** [comment]
@manav014 I used [https://jscompress.com/](https://jscompress.com/) in past.

**Comment by manav014** [comment]
I have now updated both compressed and uncompressed versions. Is there any improvement I shall work on.

**Comment by wilsonge** [comment]
This string probably should be a translateable value like the one above - but I have a sneaky suspicion this is only masking the problem. In other places where we have invalid fields we're now going to get double values. What is the value on the `invalid` property when this happens? because it would seem jQuery fails to find it to put in a more suitable message?

**Comment by zero-24** [comment]
Dear @manav014 

in preperation of the upcomming release of Joomla 3.10 we have used GitHubs rename feature to rename the staging branch into 3.10-dev. Usually GitHub moves all existing PRs towards the new branch just fine, but here it didnt work. The reason seems to be that the fork of the CMS that was used as base for this PR has been deleted so GitHub does no longer have a base to rebase the PR against the new branch and we are also not able to reopen the PR. For that reason GitHub closed this PR in my name, when this issue is still valid It would require a new PR against the new 3.10-dev or 4.0-dev branch.

**Pull request closed without merging**
