### PR TITLE
Fix multi-factor migration when updating from J3 to J4

### PR DESCRIPTION
**Pull request by OctavianC**
Pull Request for Issue #42252 .

### Summary of Changes
Use MVCFactory to create the Table so that userFactory is attached

### Testing Instructions
See issue #42252

### Actual result BEFORE applying this Pull Request
UserFactory not set in Joomla\Component\Users\Administrator\Table\MfaTable

### Expected result AFTER applying this Pull Request
No errors when logging in

### CODE REVIEW

**Comment by agnamr** [comment]
I have just updated my website from 3.10.12 to 4.4.  I have the error mentioned in this thread.  When will a fix be available to the general user - is there a file I can update my installation with?
Thanks for your help.
Mary

**Comment by richard67** [comment]
> I have just updated my website from 3.10.12 to 4.4. I have the error mentioned in this thread. When will a fix be available to the general user - is there a file I can update my installation with? Thanks for your help. Mary

@agnamr The fix can be found here in this PR in the [changed files list](https://github.com/joomla/joomla-cms/pull/42253/files) (one file only).

You can download the changed file "MultiFactorAuthenticationHandler.php" from here https://raw.githubusercontent.com/joomla/joomla-cms/868aa76de29bf4b9ab77e554a3d58af4c8b0d61c/libraries/src/Application/MultiFactorAuthenticationHandler.php and save it in folder "libraries/src/Application". You might have to change the file type in the download dialog of your browser from text to any file to be able to save the file with the original name "MultiFactorAuthenticationHandler.php".

The fix here will be merged into the code when it has 2 successful human tests, and if that happens soon, the fix will be in the next release 4.4.1 (and also in 5.0.1).

**_You can help with that:_** If you have downloaded the changed file anyway because you want to fix the issue on your site, and if that works for you, that is already one of the 2 required successful human tests. In this case please go to the pull request in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/42253 , use the blue "Test this" button at the top left corner, select your test result (hopefully "success") and finally submit. The we know you have tested the fix with success and the test will be properly counted.

**Comment by agnamr** [comment]
Thanks Richard, I will try it out and report back - I now have another problem signing onto my admin site as I messed around with enabling the authentication plugins and since I didn't already have an MFA method set up I am locked out.
Really appreciate the help.
Mary

**Comment by jjnxpct** [comment]
I had the same issue on one of our sites and this fix worked for me. Thanks!

**Comment by richard67** [comment]
> I had the same issue on one of our sites and this fix worked for me. Thanks!

@jjnxpct If that was a successful test, could you go to this PR in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/42253 , use the blue "Test this" button at the top left corner, select your test result (success) and finally submit, so that your test result is properly counted? You know, each PR needs 2 successful tests by human testers to get accepted. Thanks in advance.

**Comment by jjnxpct** [comment]
I have tested this item :white_check_mark: successfully on 57cf84fbe451b8dd0618ed5ed1c8b387a28eb81c<br /><br />This worked for me!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42253">issues.joomla.org/tracker/joomla-cms/42253</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 57cf84fbe451b8dd0618ed5ed1c8b387a28eb81c<br /><br />The error was shown after update from J3 to J4. After applying the patch I was able to login.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42253">issues.joomla.org/tracker/joomla-cms/42253</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42253">issues.joomla.org/tracker/joomla-cms/42253</a>.</sub>

**Pull request merged**
