### PR TITLE
Search Tools (from JLayouts) implemented in com_menu (menus view)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

In move to normalize the search/filter/order/limit bar (aka `searchtools`) in all administrator list views, and as other PR's have made for other list component/views, this PR adds JLayouts `searchtools` to com_menu `menus` view and replacing the old HTML code.
With that it also adds an option for ordering to com_menu menus view.

A PHP notice in hathor was corrected too.
###### Before patch

image
###### After patch

image
###### Before patch

image
###### After patch

image
#### How to test
1. Go to com_menu menus view (the one with the menutypes, not menu items view).
2. Create some menus (at least one of them without linked modules)
3. Apply the patch
4. Test the Search Tools (Search field, ordering and limit).
5. View hathor template to and check the php notice is not there now.
#### Observations

First time using a part of JLayouts so suggestions and code revisions are welcome.
#### Tags

administrator, menus, search tools, jlayouts, list views, normalization

### CODE REVIEW

**Comment by infograf768** [comment]
This does not look like working. What do you expect exactly. Please attach a screenshot.
Here, except for the Clear Button in the menus list, I lose the correct search in the menu items list where the Menutype field disapears.

**Comment by andrepereiradasilva** [comment]
Ups. i will check when i have time, sorry for that. I will also put some screenshots them.
The goal here is to normalize the use of JLayouts searchtools in com_menus (menus view doesn't use it, the other views already use it).

**Comment by andrepereiradasilva** [comment]
@infograf768 code and test instructions updated.
Screenshots added.
Can you check now?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 98f49deeb0ee95d430ba4b53379a96a2a56d91d6<br /><br />Works now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8842">issues.joomla.org/joomla-cms/8842</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 98f49deeb0ee95d430ba4b53379a96a2a56d91d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8842">issues.joomla.org/joomla-cms/8842</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8842">issues.joomla.org/joomla-cms/8842</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 @NLRoosj thanks for testing.

**Pull request closed without merging**
