### PR TITLE
Remove hitcount variable from URI after voting

### PR DESCRIPTION
**Pull request by magnussinger**
Pull Request for Issue #41009.

### Summary of Changes
When someone votes for an article, there is no longer a variable added to the URI

### Testing Instructions
Enable the content-vote plugin and make sure that voting is set to sho in the article options.
Visit any article on the front end of the site and vote

### Actual result BEFORE applying this Pull Request
A variable gets added to the URI

### Expected result AFTER applying this Pull Request
No variable gets added to the URI

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceus1984** [comment]
I have tested this item :white_check_mark: successfully on cc39c392c19242e4127e05f6d7b6e7dabcd337c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41474">issues.joomla.org/tracker/joomla-cms/41474</a>.</sub>

**Comment by Sabine-2023** [comment]
I have tested this item :white_check_mark: successfully on cc39c392c19242e4127e05f6d7b6e7dabcd337c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41474">issues.joomla.org/tracker/joomla-cms/41474</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41474">issues.joomla.org/tracker/joomla-cms/41474</a>.</sub>

**Comment by flo-the-cat** [comment]
I have tested this item :white_check_mark: successfully on cc39c392c19242e4127e05f6d7b6e7dabcd337c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41474">issues.joomla.org/tracker/joomla-cms/41474</a>.</sub>

**Comment by obuisard** [comment]
Thank you Magnus @MagnusSinger for the PR!

**Pull request merged**
