### PR TITLE
Language string typo

### PR DESCRIPTION
**Pull request by brianteeman**
Remove double space from text.

Code review should be enough

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6b2548405dc7e25a044fce22f4eb8cf42a351ebc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26790">issues.joomla.org/tracker/joomla-cms/26790</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 6b2548405dc7e25a044fce22f4eb8cf42a351ebc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26790">issues.joomla.org/tracker/joomla-cms/26790</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26790">issues.joomla.org/tracker/joomla-cms/26790</a>.</sub>

**Comment by zero-24** [comment]
Thanks :+1:

**Comment by brianteeman** [comment]
Thanks

image

**Comment by zero-24** [comment]
:hooary:

**Pull request merged**
