### PR TITLE
SEF system plugin performance improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR does some performance improvements to the SEF system plugin.
###### Before PR

sef-before-pr
###### After PR

sef-after-pr
#### How to test
1. Enable SEF in global config and enable SEF system plugin
2. Create some content with links, images, objects, etc. (see code to see what this plugin replaces)
3. Apply this patch
4. Check if all links and references (ex: images) are using the SEF uri as before.

For checking the performance improvements:
- Enable debug global configuration option and debug system plugin.
- Temporary replace code in line https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/event/dispatcher.php#L160 for:

``` php
JDEBUG && $this->_observers[$key] == 'PlgSystemSef' ? JProfiler::getInstance('Application')->mark('- ' . $this->_observers[$key] . '->' . $event . ' started.') : null;
$value = $this->_observers[$key]->update($args);
JDEBUG && $this->_observers[$key] == 'PlgSystemSef' ? JProfiler::getInstance('Application')->mark('- <strong>' . $this->_observers[$key] . '->' . $event . ' Ended!</strong>') : null;
```
- Check the profile information in the debug console before and after PR

Notes:
- The more code a page has, the more time the `onAfterRender` event of the SEF plugin will take. So test this in category blog views and other pages with lot of content.
- It would be good to test in ready to production sites, i.e., with real content.
#### Observations

Suggestions, code reviews and improvements are welcomed.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
BTW i have a production site that, by just by applying this PR i get a performance improvement in almost all pages of ~45ms (around 10%).

Before PR
image

After PR
image

So the performance improvement largely depends of the HTML code of the pages.

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 42d86c0bc98744aff4e2f14614e57c84e04e4245<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9080">issues.joomla.org/joomla-cms/9080</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 42d86c0bc98744aff4e2f14614e57c84e04e4245<br /><br />I also tested this on a production site (3.4.8) with a lot of content, different menu types and different components and I can see similar improvements. 

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9080">issues.joomla.org/joomla-cms/9080</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9080">issues.joomla.org/joomla-cms/9080</a>.</sub>

**Pull request merged**
