### PR TITLE
Fix: Use a locale un-aware method to create a float value. (#17114)

### PR DESCRIPTION
**Pull request by gitlae**
Pull Request for Issue #17114.

### CODE REVIEW

**Comment by ghost** [comment]
can you please provide Testing Instructions, what the PR solves, ...

**Comment by gitlae** [comment]
Sure, the text was written in the first ticket and not copied to the PR (only the ref. link).

## Steps to reproduce the issue
Run Joomla on a host system with a non US locale, for example 'swedish'.
Create/Open an article and save it.

## Expected result
Silently save article.

## Actual result
com_finder will generate "Column count doesn't match value count at row 1" (Error Code: 1136.)

## System information (as much as possible)
Database Version 5.5.55-cll
Database Collation latin1_swedish_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.6.16
Web Server Apache
WebServer to PHP Interface cgi-fcgi
Joomla! Version Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

## Additional comments
Just casting a value to (float) will generate a locale aware floating-point number.
In Swedish ',' is used for decimal separation (3,14) and that will not work in an SQL statement.

The patch will at least fix the problem, might not be the perfect solution but it works for me :)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17345">issues.joomla.org/tracker/joomla-cms/17345</a>.</sub>

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by Hackwar** [comment]
I unfortunately can't replicate this. I've been using German as the non-US language, which also uses ',' as decimal-seperator. The weight already was a float with '.' as decimal-seperator and even after casting with (float) it stayed that way. Is that still an issue? I tested this with 4.0-dev.

**Comment by brianteeman** [comment]
@hackwar thanks for testing but this was a report of an issue in joomla 3 so could you please.test in that version and not j4

**Comment by ggppdk** [comment]
This is a real issue
you should never use 

(float) value 
in an SQL query as you cannot say in advance if at the server that this will be executed, the return value will have comma or dot

Always a dot should be used to send floats to DB, even if you fix the incorrect column count by quoting the comma-using float value you will get a truncated integer part to be saved

I think you missed the discussion at the already merged PR https://github.com/joomla-framework/database/pull/127
by @csthomas that improved our 
`DatabaseDriver::escape()` to use:
```php
		if (is_float($text))
		{
			// Force the dot as a decimal point.
			return str_replace(',', '.', $text);
		}

```

https://github.com/csthomas/database/blob/d6e959fa08539feb79fab0d25997167bbe125c12/src/Mysqli/MysqliDriver.php#L300-L312

**Comment by csthomas** [comment]
The line is still issue:
https://github.com/joomla/joomla-cms/blob/c396b5c201aae00add01fe1c5c67fa563e651825/administrator/components/com_finder/helpers/indexer/indexer.php#L537

and should be replaced by `. $db->quote($token->weight) . ', '`

**Comment by Hackwar** [comment]
I created a new PR for this here: #20573

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/20573  is for 4.0

@csthomas 
You do the 3.x one?

**Comment by csthomas** [comment]
I can do the same for J3 as in PR https://github.com/joomla-framework/database/pull/127

**Comment by csthomas** [comment]
and then I/we can add a fix in com_finder.

**Comment by infograf768** [comment]
Please take care of it. Framework is over my abilities. ;)

**Comment by csthomas** [comment]
I did a PR to fix the problem in J3.

**Pull request closed without merging**
