### PR TITLE
[4.0] Fix page navigation query

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27587

### Summary of Changes
Fix page navigation links by fixing query to join on the workflow stages table correctly

### Testing Instructions
Check for next article button on the article. Before patch no article, after patch article.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dffa260d3531f41f39922229772e65727191a501<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27871">issues.joomla.org/tracker/joomla-cms/27871</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dffa260d3531f41f39922229772e65727191a501<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27871">issues.joomla.org/tracker/joomla-cms/27871</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27871">issues.joomla.org/tracker/joomla-cms/27871</a>.</sub>

**Comment by richard67** [comment]
Is a no-brainer .. will merge.

**Comment by wilsonge** [comment]
thankyou!

**Pull request merged**
