### PR TITLE
[4.0] Remove redundant type checks

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes type checks since arguments are already typehinted.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4f88562840d422fc545e9bbb591c8b6f588404c3<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30163">issues.joomla.org/tracker/joomla-cms/30163</a>.</sub>

**Comment by dunkmark** [comment]
Duplicate Files Are Dangerous Files On Any Type Of System. There Are Several Ways Generating Duplicate Files Every Time We Should Be Ready To Remove That Duplicate File With The Help Of Any Duplicate File Finder.

These Can Find Our Duplicate Files Easily, Not Only Removing Unnecessary Files It Also Cleans The Drive And Removes Junk Files Our PC. So It’s Better To Use Duplicate File Finder On Your PC. Plenty Software’s Are Available Online You Can Go Through Top Rated One.[How to Quickly Give a Title to Your Essay.pdf](https://issues.joomla.org/uploads/1/e2c5c6d3390dfe422625152bf4e97cb1.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30163">issues.joomla.org/tracker/joomla-cms/30163</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 4f88562840d422fc545e9bbb591c8b6f588404c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30163">issues.joomla.org/tracker/joomla-cms/30163</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30163">issues.joomla.org/tracker/joomla-cms/30163</a>.</sub>

**Pull request merged**
