### PR TITLE
[4.0] Cassiopeia remove mixin a11y-visually-hidden

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes a mixin that as far as I can tell just duplicated the core bootstrap mixin but was using an older, now oout of date, version.

To test

- make a copy of templates\cassiopeia\css\template.css
- apply pr
- regenerate the css (node build/build.js --compile-css)
- compare the copy and the new template.css

The only difference should be for `.container-header .mod-finder > label` which is not using the correct code.

There should be no other differences.

(I really dont understand why we have so many bootstrap overrides that dont do anything)

### CODE REVIEW

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 327d67cf7535eacc5198419f6fbcec5bbf4c92a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32480">issues.joomla.org/tracker/joomla-cms/32480</a>.</sub>

**Comment by himanshu007-creator** [comment]
The only difference was in the specified component only.[Refer here.](https://i.ibb.co/L81Vz4V/2021-02-22-4.png "Refer here")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32480">issues.joomla.org/tracker/joomla-cms/32480</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on 327d67cf7535eacc5198419f6fbcec5bbf4c92a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32480">issues.joomla.org/tracker/joomla-cms/32480</a>.</sub>

**Comment by infograf768** [comment]
Please solve conflicts

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32480">issues.joomla.org/tracker/joomla-cms/32480</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
