### PR TITLE
[4.0] webauthn subpackage

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to correct a copy paste error with the @subpackage name

code review only needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a4e42ecea9fce7816e13ba61b1805750cc52f804<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28562">issues.joomla.org/tracker/joomla-cms/28562</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a4e42ecea9fce7816e13ba61b1805750cc52f804<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28562">issues.joomla.org/tracker/joomla-cms/28562</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28562">issues.joomla.org/tracker/joomla-cms/28562</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
