### PR TITLE
Fix link and button colors in header footer of Cassiopeia template

### PR DESCRIPTION
**Pull request by RickR2H**
Rework of issue PR #41749
Pull Request for Issue #42302 

### Summary of Changes
In previous PR's the colors for the buttons and links in the header and footer where broken. This PR fixed those issues,

- Obsolete styling is removed
- Added correct colors to the header and footer buttons and links
- Fix hover state of scroll to top button

### Testing Instructions
Create 3 custom html modules in the positions: topbar / footer / bottom-b
Make sure you toggle the editor to Source code+ (Click in the editor Tools -> Source code+)
Use the code below in the modules and paste as in the Source code+ ans click Save.

```
<a href="#" class="btn btn-primary">Primary</a>
<a href="#" class="btn btn-secondary">Secondary</a>
<a href="#" class="btn btn-success">Success</a>
<a href="#" class="btn btn-danger">Danger</a>
<a href="#" class="btn btn-warning">Warning</a>
<a href="#" class="btn btn-info">Info</a>
<a href="#" class="btn btn-light">Light</a>
<a href="#" class="btn btn-dark">Dark</a>
<a href="#" class="btn btn-link">Button link</a>
<a href="#">Default Link</a>
```
Test if all button color are correct, also the hover state.
Test the frontend edit buttons
Switch the scroll to top icon to On in the template settings to test the scroll to top hover color

### Actual result BEFORE applying this Pull Request
Some buttons and links texts are not visible
20231213-image-before

### Expected result AFTER applying this Pull Request
All colors are visible
20231213-image-after

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
The Download is not available (```Expected — Waiting for status to be reported```).

**Comment by alikon** [comment]
the Prebuilt Download Packages are available here https://artifacts.joomla.org/drone/joomla/joomla-cms/4.4-dev/42504/downloads/72256

**Comment by sandewt** [comment]
Thanks for this pr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42504">issues.joomla.org/tracker/joomla-cms/42504</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 22dc4449a832b5fbd1617c880b8c660cd0ff7817<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42504">issues.joomla.org/tracker/joomla-cms/42504</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22dc4449a832b5fbd1617c880b8c660cd0ff7817<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42504">issues.joomla.org/tracker/joomla-cms/42504</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
