### PR TITLE
[com_fields] Remove GroupConcat from fields model

### PR DESCRIPTION
**Pull request by Bakual**
When normalising the fields table (moving assigned_cat_ids to own table #__fields_categories) I introduced the use of a "GROUP_CONCAT". However that only works in MySQL and not in PostgreSQL and MSSQL. @alikon created a PR to port the group concat feature to PostgreSQL but it would still need a solution for MSSQL.

When looking why we need it I found that it is only used for the fiels list manager to show the categories:
assigned_cat_ids

### Summary of Changes
This PR proposes to remove that information from the list manager (it's obviously still in the form itself) which removes the need for that GROUP_CONCAT. On the other hand it allows to add a filter for those categories
assigned_cat_ids2

### Testing Instructions
* Apply PR and test that assigning categories to a field still works.
* Test filtering by category
* Test that fields with assigned categories only show up in items (eg articles) with that category assigned both when displaying and editing.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by laoneo** [comment]
It works, but I still would like to have the information about assigned categories in the list view. I use this information quite often on my production sites with DPFields.

**Comment by Bakual** [comment]
We will have to do seaparate queries to fetch that. Since it's only used in backend I see no issues with the potential performance impact (they are light queries anyway).
I can add it back hopefuly later today.

**Comment by laoneo** [comment]
Thanks.

**Comment by Bakual** [comment]
Added back the categories using a new helper method.

**Comment by alikon** [comment]
we still have a GROUP_CONCAT() in search content plugin
https://github.com/joomla/joomla-cms/pull/13291/files#diff-b32bbae639a4113309650b03c2b09ba1R173

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2a84fbe1b490dda915357c6d337587e6585b8421<br /><br />tested with postgresql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13302">issues.joomla.org/tracker/joomla-cms/13302</a>.</sub>

**Comment by Bakual** [comment]
Yep, I know about the content one. Didn't have the time yet to look at it. Have to play with search a bit tomorrow 👍

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 2a84fbe1b490dda915357c6d337587e6585b8421<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13302">issues.joomla.org/tracker/joomla-cms/13302</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC, thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13302">issues.joomla.org/tracker/joomla-cms/13302</a>.</sub>

**Pull request merged**
