### PR TITLE
[4.0] Redundant tip debugusers and debuggroups

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the redundant titles from the column headers

administraator/index.php?option=com_users&view=debuguser
administrator/index.php?option=com_users&view=debuggroup

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 00aa47cd27dee78feec1ee3365d525625f7a5d83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25633">issues.joomla.org/tracker/joomla-cms/25633</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 00aa47cd27dee78feec1ee3365d525625f7a5d83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25633">issues.joomla.org/tracker/joomla-cms/25633</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25633">issues.joomla.org/tracker/joomla-cms/25633</a>.</sub>

**Comment by ghost** [comment]
can one learn joomla-cms-bot to not remove labels while changing status to "Ready to commit"?

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
