### PR TITLE
[4.0] Change button string

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/29312.

### Summary of Changes

Just changing `Submit` string to `Save`.

### Testing Instructions

Edit profile in frontend.
Inspect form buttons.

### Expected result

`Save` button.

### Actual result

`Submit` button.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 34b38a38c0f44c2b8d6f2ca2a60bb15c54cda801<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29367">issues.joomla.org/tracker/joomla-cms/29367</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 34b38a38c0f44c2b8d6f2ca2a60bb15c54cda801<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29367">issues.joomla.org/tracker/joomla-cms/29367</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29367">issues.joomla.org/tracker/joomla-cms/29367</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
