### PR TITLE
Added date configuration and right grouping for archived articles module

### PR DESCRIPTION
**Pull request by jatitoam**
A date configuration option has been added to the archive articles module, so the user can manually adjust this module to match the archive articles view.

The default has been changed to published date.

Date grouping has been fixed also - it was displaying duplicate months before

### CODE REVIEW

**Comment by G-Lu** [comment]
Tested with English (en-GB) languge pack and test Data.
I set the status of some articles to archived and modified 2 of them while the testing process.
SEF on/off makes no difference for me.

Worked with "Date to show" values "Created" and "Published".
But there were problems with the "Modified" option:
 - The Archiv shows me an entry from "November, -0001" (empty Year value?)
 - This Month got no articles in it.
 - I modified 2 articles, the new Month was shown (Aug, 15) but was empty.
   (The article "Similar Tags", modified in oct, 13 was shown correct. Just the newly modifies articles ware not shown)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4810">issues.joomla.org/joomla-cms/4810</a>.</sub>

**Comment by roland-d** [comment]
@jatitoam can you please look at the last unsuccessful test results? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4810">issues.joomla.org/joomla-cms/4810</a>.</sub>

**Comment by brianteeman** [comment]
@jatitotam Thank you for your contribution.

The last comment here was on 21 August. Can you please follow-up on this issue? If not this will be closed within 4 weeks

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4810">issues.joomla.org/joomla-cms/4810</a>.</sub>

**Comment by brianteeman** [comment]
Closed as per comments above - it can always be reopened in future if there is any response<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4810">issues.joomla.org/joomla-cms/4810</a>.</sub>

**Pull request closed without merging**
