### PR TITLE
[4.0] Change fa-8x to icon-8x

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change the last instances of `fa-`.

Change `fa-8x` to `icon-8x`.
Apply coding style.

### Testing Instructions
Install the prebuilt package.

or

Click `Post Installation Messages` icon.
Click `Hide all messages` button.
Apply PR.
Run `npm run build:css`

Bell icon should be the same size before/after PR.

### CODE REVIEW

**Comment by brianteeman** [comment]
1. repeating my objection to this pointless change
2. its only a partial job - what if in 2 days someone submits a pr with fa-7x or any other valid and working fa class that has not been duplicated as per this pr
3. https://github.com/joomla/joomla-cms/blob/a07bc7796fc460881ebdffed5bf85d1cf3f0d218/layouts/joomla/content/emptystate.php#L39

**Comment by Quy** [comment]
Then they can use `fa-7x`, but at least in the core, we are being consistent.

**Comment by C-Lodder** [comment]
@Quy You want to start moving away from `icon-xx`. It was kept purely for 3rd party compatability reasons. There is absolutely no reason for core to use `icon-` over `fas-`

**Comment by richard67** [comment]
@Quy SCSS - CS: https://ci.joomla.org/joomla/joomla-cms/44115/1/20

**Comment by Quy** [comment]
PR #30707 changed `fas-` to `icon-`. Is it too late to revert before RC?

**Comment by brianteeman** [comment]
That other pr was reverting poorly implemented code despite multiple people pointing that out in advance ;(

icon- was created to be a bc compatibility layer with iconmoon. it was never intended to be a conversion between fontawesome syntax and iconmoon syntax which is what this pr (and others) are doing

**Comment by Quy** [comment]
Let's do it right out of the gate. 

@wilsonge Please confirm to revert #30707.

**Comment by brianteeman** [comment]
reverting that PR will not achieve that

**Comment by Quy** [comment]
Then I am lost what the solution should be.

**Comment by brianteeman** [comment]
The solution is not to do anything

**Comment by Quy** [comment]
So it is ok to have mixed `icon-` and `fa-` in the backend?

**Comment by brianteeman** [comment]
yes - I see no reason why not. Especially for the utility classes

**Comment by Quy** [comment]
Closing then. Thanks!

**Pull request closed without merging**
