### PR TITLE
JED turned to https

### PR DESCRIPTION
**Pull request by MATsxm**
Minor and easy fix
- Turned the JED link to https
- Minor few fixes on proper use of the trademarked name of Joomla!
### Testing Instructions

on code review

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12076">issues.joomla.org/joomla-cms/12076</a>.</sub>

**Review by zero-24 — APPROVED** [review]

**Comment by MATsxm** [comment]
Oooops :smile: too fast @zero-24 
`.txt` has also to be updated...
do I have to make a new one or you can merge even if this is closed?

**Comment by zero-24** [comment]
This is not closed. Everything is good here :)

**Comment by andrepereiradasilva** [comment]
all this files have extension.joomla.org URL

```
README.md
README.txt

administrator/language/en-GB/en-GB.com_installer.ini
administrator/language/en-GB/en-GB.com_installer.ini

administrator/templates/hathor/html/mod_menu/default_enabled.php
administrator/modules/mod_menu/tmpl/default_enabled.php

installation/sql/mysql/sample_testing.sql
installation/sql/mysql/sample_learn.sql
installation/sql/mysql/sample_blog.sql
installation/sql/postgresql/sample_testing.sql
installation/sql/postgresql/sample_learn.sql
installation/sql/postgresql/sample_blog.sql
installation/sql/sqlazure/sample_testing.sql
installation/sql/sqlazure/sample_learn.sql
installation/sql/sqlazure/sample_blog.sql
installation/INSTALL

tests/unit/stubs/database/jos_ucm_content.csv
tests/unit/stubs/database/jos_content.csv
tests/unit/stubs/database/jos_categories.csv
tests/unit/stubs/database/jos_finder_links.csv
```

So i think you should chmaghe in all of them

**Comment by MATsxm** [comment]
if this can wait for tomorrow... I will :stuck_out_tongue_closed_eyes:  
Thanks

**Comment by zero-24** [comment]
Moving to pending until than<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12076">issues.joomla.org/joomla-cms/12076</a>.</sub>

**Review by jeckodevelopment — APPROVED** [review]

**Comment by wilsonge** [comment]
Is this ready now MAT?

**Comment by MATsxm** [comment]
@wilsonge nope!

**Comment by MATsxm** [comment]
@andrepereiradasilva @wilsonge 
should be ok now?

**Review by mbabker — APPROVED** [review]

**Comment by mbabker** [comment]
Side note we probably should just regenerate all the test stub CSVs at one point.

**Comment by zero-24** [comment]
RTC. based on the last reviews. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12076">issues.joomla.org/joomla-cms/12076</a>.</sub>

**Comment by brianteeman** [comment]
Removed RTC label

**Pull request merged**
