### PR TITLE
[#33295] Adding the "showon" & hiddenLabel feature to JForm

### PR DESCRIPTION
**Pull request by chivitli**
This is like PR #3127, just in sync with the latest changes, and it also adds support for hidden labels on xml level. Here is the copy of the test instructions/description from the previous PR:
### Overview

In the Joomla Global Configuration we use showon attribute to show/hide certain fields based on the state of a "parent" field. You can see this for example with the FTP settings where the settings itself only show when "Enable FTP" is set to "Yes". It's also available for Component settings.

This PR takes this feature to the JForm so it can be used in any xml file.
### Testing

You can add a showon attribute to any config field you want to hide. For example in 
 modules\mod_finder\mod_finder.xml you add to line 94
 showon="show_label:1". So it looks like this:

```
                <field
                    name="label_pos"
                    type="list"
                    default="left"
                    showon="show_label:1"
                    label="MOD_FINDER_FIELDSET_ADVANCED_LABEL_POS_LABEL"
                    description="MOD_FINDER_FIELDSET_ADVANCED_LABEL_POS_DESCRIPTION">
                    <option
                        value="right">JGLOBAL_RIGHT</option>
                    <option
                        value="left">JGLOBAL_LEFT</option>
                    <option
                        value="top">MOD_FINDER_CONFIG_OPTION_TOP</option>
                    <option
                        value="bottom">MOD_FINDER_CONFIG_OPTION_BOTTOM</option>
                </field>
```

This will only show the "Label position" setting only if the "Show Label" is set to "Yes" (which has the value 1).

Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33295&start=0

### CODE REVIEW

**Comment by piotr-cz** [comment]
There's a problem when `showon` attribute is applied to field inside a group, but target field is not within it.

```XML
<fieldset>
     <field
        name="has_full_image"
        type="radio"
    >
        <option value="yes">JYES</option>
        <option value="no">JNO</option>
    </field>
</fieldset>
<fields name="images">
    <field
        name="image_fulltext"
        showon="has_full_image:yes"
    />
</fields>
```

because the attached rel attribute is generating id from the source field:
```HTML
<div class="control-group  showon_yes"  rel="showon_jform[images][has_full_image]">
...
</div>
```

Dirty workaround is to place both field withing same group

**Comment by zero-24** [comment]
@piotr-cz i guess we should open a new issue for this? I think here your comment get forgotten, as this is a closed / merged PR :smile:

**Comment by sovainfo** [comment]
@zero-24 Could you add it to milestone J342?

**Comment by zero-24** [comment]
@sovainfo what issue? ;) This PR gets merged into Joomla 3 and it is closed.

If we open a new Issue / PR i can add it to the milestone :smile:

**Comment by sovainfo** [comment]
And if it had been assigned to the proper milestone we would be able to see when it was committed. When reporting on the milestone it would show up.

**Comment by mbabker** [comment]
Milestones didn't start getting used until 3.3.4-ish.  Long after this PR was merged.

**Comment by sovainfo** [comment]
Sorry, misread the information: 28 march 2014 instead of 2015 !

**Comment by piotr-cz** [comment]
I've created new issue #6744.
I made a comment here, because the original author of the PR may be best person to propose optimal solution.

**Comment by chivitli** [comment]
I think @obsidev may be the best person to sugges ta solution, as (s)he is the author of the original js which works out the targets

**Comment by obsidev** [comment]
Hi,

The easier will be to allow the "showon" to specify the other ID ; not complicated at all.
I was talking with @garstud during a local Joomla event and we shared some ideas on the "showon" feature, it could be a good time to implement them !

Regards,

PS : It's a "he" :) I'm also know as Jerome from the HikaShop team.

**Comment by piotr-cz** [comment]
@obsidev I agree this is the best option but this would break B/C

**Comment by DeathMark** [comment]
This solution doesn't work with field has multiple="true"

**Comment by Bakual** [comment]
@DeathMark If you think this is an issue, please open a new issue on this tracker. A comment on an old closed one will only get lost in time and space.

**Comment by DeathMark** [comment]
@Bakual Thanks. I will do it.

**Comment by stutteringp0et** [comment]
Has anyone thought about multiple tests?  Maybe something like showon="field1:1;field2:2" - requiring multiple values to align before the field is shown?

**Comment by ggppdk** [comment]
already included in 3.5.x
see here:
https://github.com/joomla/joomla-cms/pull/8524

showon="field1:1[AND]field2:1[AND]field3:1"
showon="field1:1[AND]field2:1[OR]field3:1"

**Comment by stutteringp0et** [comment]
That's awesome!  Thanks!

**Pull request closed without merging**
