### PR TITLE
Improved the field widths same as the selects in TinyMce plugin setting

### PR DESCRIPTION
**Pull request by shivamdiehard**
Pull Request for Issue [#14612](https://github.com/joomla/joomla-cms/issues/14612)

### Summary of Changes

Replaced the class="input-xxlarge" with class="input-large"

### Testing Instructions
1) Apply the patch
2) Go to plugins
3) Select the TinyMCE plugin
4) Now the field widths will same as the selects

### Before
testbefore

### After
test

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c68011cf24fae8baf78e4fb0f1c392349a303f64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14622">issues.joomla.org/tracker/joomla-cms/14622</a>.</sub>

**Comment by Fedik** [comment]
👎 
that size was made with purpose, no need to change it

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on c68011cf24fae8baf78e4fb0f1c392349a303f64<br /><br />Works as expected. While generally I like to maximize space usage for certain input fields, it's rare that someone will need beyond 210px of text width. And of course it still works for those who have a lot of text.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14622">issues.joomla.org/tracker/joomla-cms/14622</a>.</sub>

**Comment by Fedik** [comment]
> And of course it still works for those who have a lot of text.

but it will become hard to edit the text in these fields, 
that why the width was extended for these particular inputs, 
so I am against this changes

**Comment by ggppdk** [comment]
> it's rare that someone will need beyond 210px of text width

rare to input what ?
e.g. parameter for **folder path** will not fit, and the most relevant part of folder (its ending) will always be hidden, you will need to click and scroll to view / edit it (and changing text-align is not a solution, hiding its start)

e.g. then the 3 "elements" parameters could even be considered to be of "textarea" type,
if we make them smaller it will be quite annoying to edit, unless you copy paste their contents to a text editor and then back to the parameters

let's make it (maybe) a little more beautiful, regardless of usablilty for people that will actually use these parameters
there should be PRs doing the reverse of what this PR does

**Comment by JoshuaLewis** [comment]
Yeah, wasn't thinking about paths. Valid point. Textareas did come to mind.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by Fedik** [comment]
> textarea

the textarea make not much sense, as the code expect "Single line", and in textarea user can think that he can use "new line"

**Comment by brianteeman** [comment]
Please remove the RTC status - just because it has had two successful tests doesnt mean that the issues that @fedik raised can be ignored

**Comment by Bakual** [comment]
Imho it doesn't make sense to make the fields smaller beside it looking a bit ugly. So the usuability argument for the CSS file field wins over the design one hands down. Textarea is no option for this field as well.

I'm closing this PR as it will not get merged in this state.

**Pull request closed without merging**
