### PR TITLE
add si_lk.gif

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9893.
#### Summary of Changes

media/mod_languages/images/si_lk.gif added back
#### Testing Instructions

Before PR
file media/mod_languages/images/si_lk.gif does not exist
After PR
file media/mod_languages/images/si_lk.gif exist

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d7e5440f954178fe0d2d7f7a76382669ae9fe0ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9902">issues.joomla.org/joomla-cms/9902</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d7e5440f954178fe0d2d7f7a76382669ae9fe0ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9902">issues.joomla.org/joomla-cms/9902</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9902">issues.joomla.org/joomla-cms/9902</a>.</sub>

**Comment by PhilETaylor** [comment]
> Joomla didn't remove the old (with uppercase) for Backward Compatibility (BC).

This is bad - Joomla SHOULD remove the upper case file, on Windows hosts you cannot have the uppercase and the lowercase file at the same time anyway...

**Comment by Bakual** [comment]
> This is bad - Joomla SHOULD remove the upper case file, on Windows hosts you cannot have the uppercase and the lowercase file at the same time anyway...

It should, yes. But we can't. And it doesn't really matter if that specific file is there duplicated.
The reason why we can't remove it is exactly the Windows system. On Linux on an update we have both the lowercased and uppercased file, and we could remove the uppercased one. But on Windows we only have one file after the update, the old one got overwritten with the new one. If we now try to remove the uppercased file, we remove the one file that was there, which obviously would be bad to do.

The BC isn't really the issue here.

**Pull request merged**
