### PR TITLE
[4.0]toggle selection buttons not working in com_templates

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - `Toggle selection` & `Toggle all selection` buttons not working.

### Summary of Changes
Modified the inline javascript

### Testing Instructions
Go to com_templates -> view=styles -> Menu Assignment
screenshot from 2019-03-05 22-58-32

### Expected result
Toggle selection buttons should work

### Actual result
Not working

### CODE REVIEW

**Comment by ghost** [comment]
is there a Issue-#?

**Comment by bahl24** [comment]
> is there a Issue-#?

No issue currently, I think.

**Comment by amitranjan2** [comment]
@bahl24 DUPLICATE  
see this PR #23844

**Comment by amitranjan2** [comment]
> is there a Issue-#?

Yes, see this #23801

**Comment by dgrammatiko** [comment]
Sorry, but can you fix it **WITHOUT** jQuery, if not please close this PR!!!

**Comment by bahl24** [comment]
@amitranjan2 Is your PR working, the problem was still there, can you recheck?

**Comment by amitranjan2** [comment]
> @amitranjan2 Is your PR working, the problem was still there, can you recheck?

yes, it's working

**Comment by dgrammatiko** [comment]
@bahl24 since we have a correct solution for this issue, can you please close this?

**Comment by bahl24** [comment]
@dgrammatiko @franz-wohlkoenig  Existing PR #23844 is not working correctly, so should I open another PR(I have another solution using JS and not JQuery).

**Pull request closed without merging**
