### PR TITLE
Fixes 9054 (part 3, com_modules). [REGRESSION] sort order

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/joomla/joomla-cms/issues/9054 for instructions.
Fixes com_modules

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9f9f3089d4e454c577dfde6d1d66b4e707150e85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9059">issues.joomla.org/joomla-cms/9059</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9f9f3089d4e454c577dfde6d1d66b4e707150e85<br /><br />Tested with success on current staging. Before patch: Sort order changed from Position Ascending to Ordering Ascending after paging (or changing items shown per page from e.g. 20 to 5). After patch: Sort order is Position Ascending and stays like this when paging. In opposite to test description in #9054 there was no need to clear any cookies for this test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9059">issues.joomla.org/joomla-cms/9059</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for the quick fix and test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9059">issues.joomla.org/joomla-cms/9059</a>.</sub>

**Comment by richard67** [comment]
Let's hope it goes into Beta 3 ... maybe someone can set the milestone to 3.5.0 to force that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9059">issues.joomla.org/joomla-cms/9059</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @bertmert and testers!

**Pull request merged**
