### PR TITLE
[4.1] jooa11y strings

### PR DESCRIPTION
**Pull request by brianteeman**
Remove the escape on the apostrophe

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman It would have been helpful to mention issue #37024 in the description.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 447eaaba6a8ab8f07c8249f4a8aeca42a485ba86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37025">issues.joomla.org/tracker/joomla-cms/37025</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 447eaaba6a8ab8f07c8249f4a8aeca42a485ba86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37025">issues.joomla.org/tracker/joomla-cms/37025</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37025">issues.joomla.org/tracker/joomla-cms/37025</a>.</sub>

**Comment by Daniel1Rosen** [comment]
best [news](http://concurrent-controls.com/ "news") =)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37025">issues.joomla.org/tracker/joomla-cms/37025</a>.</sub>

**Comment by Quy** [comment]
Fixed in #37092.

**Pull request closed without merging**
