### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by brianteeman**
Minor changes to the English, mainly to remove two identical sentences

@zero-24 @SniperSister

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 42ed92b66cba9e0b3844dabe795fddd84292bd28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25138">issues.joomla.org/tracker/joomla-cms/25138</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 42ed92b66cba9e0b3844dabe795fddd84292bd28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25138">issues.joomla.org/tracker/joomla-cms/25138</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25138">issues.joomla.org/tracker/joomla-cms/25138</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
