### PR TITLE
[4.0]Added placeholder for tag

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

Pull Request for Issue - Place holder missing in alias field in com_tag .

### Summary of Changes
Added placeholder

### Testing Instructions
Components -> Tag -> New

### Expected result
screenshot from 2019-02-19 14-27-51

### Actual result
screenshot from 2019-02-19 14-28-31

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ba09d8e99073f387a2b11372e9acfe906f23c80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23940">issues.joomla.org/tracker/joomla-cms/23940</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9ba09d8e99073f387a2b11372e9acfe906f23c80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23940">issues.joomla.org/tracker/joomla-cms/23940</a>.</sub>

**Comment by infograf768** [comment]
RTC Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23940">issues.joomla.org/tracker/joomla-cms/23940</a>.</sub>

**Comment by wilsonge** [comment]
Thanks for your first PR to Joomla!!

**Comment by bahl24** [comment]
Thank you, looking forward to contribute even more

**Pull request merged**
