### PR TITLE
[4.1] Rename render to display

### PR DESCRIPTION
**Pull request by brianteeman**
Update the field options to use the less technical "display" instead of "render"

Pull Request for Issue #36276.

### CODE REVIEW

**Comment by coolcat-creations** [comment]
If you name it "Field Container Class" you would not need any explanation below the input ?

**Comment by brianteeman** [comment]
then I would really need to rename the value class as well. I'm happy as it is

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 9ee7d4e399d909fc516f02ad6d45ecbc5bf9f8a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36279">issues.joomla.org/tracker/joomla-cms/36279</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 9ee7d4e399d909fc516f02ad6d45ecbc5bf9f8a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36279">issues.joomla.org/tracker/joomla-cms/36279</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36279">issues.joomla.org/tracker/joomla-cms/36279</a>.</sub>

**Comment by brianteeman** [comment]
Please dont forget merging this

**Comment by brianteeman** [comment]
Rebased to 4.1 - maybe it will get merged quicker

**Comment by bembelimen** [comment]
If you could fix the conflict, it will go into 4.1.1.

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
