### PR TITLE
PR for #36988 Update en-GB.com_users.ini

### PR DESCRIPTION
**Pull request by coolcat-creations**
This PR will change the label and description of the field for Administrator mails for the user settings.

Before: 

grafik

I changed it to: 

COM_USERS_CONFIG_FIELD_MAILTOADMIN_DESC="If set to Yes then a notification mail will be sent to all users who have receive system mails enabled if 'New User Account Activation' is set to 'None' or 'Self'."
COM_USERS_CONFIG_FIELD_MAILTOADMIN_LABEL="Send System-Mail"

Pull Request for Issue #36988 .

### Testing Instructions
Install the patch and see that the labels are changed.

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Documentation Changes Required
Yes it should be clarified that not only Administrators can get the mail

### CODE REVIEW

**Comment by brianteeman** [comment]
Wouldn't it be a better fix to prevent system emails being sent to anyone who does not have admin interface access as the content of the system emails regularly contains links which require admin interface access.

For me this is just covering up the real issue and not actually solving it.

**Comment by coolcat-creations** [comment]
Yes, my skills were only able to solve one of the possibilities. But I think also that it would be good to only send this mails to users who have user administration admin rights. I see this as a huge GDPR issue for the website owners when they made this setting by mistake.

**Comment by coolcat-creations** [comment]
Another Possibilty would be to name System Mails to "Receive Administrator Mails"

**Comment by brianteeman** [comment]
> Another Possibilty would be to name System Mails to "Receive Administrator Mails"

That is still just covering up the issue

**Comment by coolcat-creations** [comment]
Maybe we can continue here: https://github.com/joomla/joomla-cms/issues/36988

**Comment by brianteeman** [comment]
Found the bug will do a PR later

**Comment by coolcat-creations** [comment]
You found a bug regarding this?
I think this database query is wrong but what to add to only get the admins that are allowed to controll users?
https://github.com/joomla/joomla-cms/blob/f412e135298643bab6255fe498db69a5c8a91dbb/components/com_users/src/Model/RegistrationModel.php#L155

**Comment by brianteeman** [comment]
please test #36993

**Pull request closed without merging**
