### PR TITLE
Fix user params after Joomla 3.9.7 with selected french help site

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #25176

### Summary of Changes
Tries to fix user table if json got corrupted.

@alikon

### CODE REVIEW

**Comment by richard67** [comment]
The old schema updates 3.9.7-2019-05-16.sql should be corrected, too, so we in future don't create the error which new schema updates provided by this PR shall fix on other sites. Problem is that I don't know if the helpsite parameter always is placed somewhere in the middle of the json, or if it also can be first or last parameter in the list.

**Comment by mbabker** [comment]
I still say the param shouldn't be touched.  Empty the `3.9.7-2019-05-16` changeset and have this change to fix the broken database fields.  It was getting rid of the param that broke things in the first place and it was an unnecessary action.

**Comment by richard67** [comment]
@mbabker 
> ... have this change to fix the broken database fields. 

You mean like in this PR, with new schema update files? Or just as howto in a forum?

Is the change in this PR here safe? Or can it be that the helpsite parameter is not in the middle but at the beginning or the end of the json list so we need a more sophisticated replacement?

**Comment by HLeithner** [comment]
I removed the content from the old sql file as michael suggested.

**Comment by alikon** [comment]
yes make sense to remove the buggy replace imo

**Comment by mbabker** [comment]
Should be good now.

**Comment by richard67** [comment]
If helpsite can also be at beginning or end of the json, we also have to replace `{,` with `{`and `,}` with `}`.

**Comment by SniperSister** [comment]
I tested the patch on an updated 3.9.7, works fine and restores the JSON

**Comment by HLeithner** [comment]
normally the helpsite is between 2 other parameters I don't think that it's possible that the ,, are at the beginning or the end...

**Review by SniperSister — APPROVED** [review]

**Comment by richard67** [comment]
Should the obsolete schema updates which are deleted with this PR also be deleted on already updated sites, i.e. added somehwre here [https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1989](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1989) ?

**Comment by HLeithner** [comment]
It will be overridden anyway, not sure if it makes sense to remove it.

**Comment by mbabker** [comment]
It's fine as an empty file.  Or change the file contents to have a SQL comment that way it's clear why there are no queries in it.

```sql
# Query removed, see https://github.com/joomla/joomla-cms/pull/25177
```

**Comment by richard67** [comment]
I like Michael's suggestion in his previous comment, have a comment in the wrong sql file.

**Comment by alikon** [comment]
lgtm

**Comment by HLeithner** [comment]
I added the comment.

**Review by alikon — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 872c9ce57c5d787e09d86300dd32d43edd7acf9c<br /><br />Tested with 3.9.7 site with user having parameters with error caused by wrong helspite removal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25177">issues.joomla.org/tracker/joomla-cms/25177</a>.</sub>

**Review by richard67 — APPROVED** [review]
Lgtm

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 872c9ce57c5d787e09d86300dd32d43edd7acf9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25177">issues.joomla.org/tracker/joomla-cms/25177</a>.</sub>

**Comment by HLeithner** [comment]
thx for the help, release is out.

**Comment by pescweb** [comment]
Hello! after having done the update of joomla 3.7.5 to 3.9.10 I received this error:  [17-Jul-2019 13:28:13 Etc/GMT] PHP Fatal error:  Call to undefined method JLanguageHelper::parseIniFile() in /home/pescwj6v/public_html/libraries/src/Language/Language.php on line 803

My site is in pt-BR (portuguese-brazil), and both the site and the administrator are without access, the pages are blank. Does anyone have any solutions to this error?

**Comment by ghost** [comment]
@pescweb Please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Pull request merged**
