### PR TITLE
added missing warning lang tag COM_INSTALLER_TYPE_TYPE_

### PR DESCRIPTION
**Pull request by shamsbd71**
There are many extensions failed to update to latest version. The cause behind this can be: update URL broken or so many. 

```
Error updating COM_INSTALLER_TYPE_TYPE_
```
#### Summary of Changes

if we add `COM_INSTALLER_TYPE_TYPE_="Extension"` this code, we can show error like this: 

```
Error updating Extension
```
#### Testing Instructions

When joomla try to install or update any extension and those file dosent exist, in that case we get return this error:

```
Error updating COM_INSTALLER_TYPE_TYPE_
```

it's because system doesn't know its type.

### CODE REVIEW

**Comment by brianteeman** [comment]
This does not seem correct to me. Please can you provide a real world example of how to replicate the  original problem

**Comment by andrepereiradasilva** [comment]
you need to correct the origin of the error, IMO there shouldn't be a `COM_INSTALLER_TYPE_TYPE_` language var.

**Comment by andrepereiradasilva** [comment]
maybe a `COM_INSTALLER_TYPE_TYPE_UNSUPORTED` or something.

**Comment by shamsbd71** [comment]
@brianteeman 
this is an error warning, search google with  this `Error updating COM_INSTALLER_TYPE_TYPE_`
you will get many results. i faced this often. You can try install t3 framework's old version and then try to update it. its not only for t3, it can be for anything that has changes of update file url.

thanks

**Comment by andrepereiradasilva** [comment]
yes, i havbe seen that issue in the past, the thing is IMO this is not the correct way to solve it.

you need to check in this files https://github.com/joomla/joomla-cms/search?q=COM_INSTALLER_TYPE_TYPE_ why the variable doesn't get the extension type and solve it.

**Comment by brianteeman** [comment]
Creating a language string to mask a bug is not a solution

**Comment by andrepereiradasilva** [comment]
When we cannot get the package type or we get no package type something is wrong ... the xml can have a wrong pakage type or even none so joomla should trow an error (probably a new language string) when that happens.

**Comment by brianteeman** [comment]
Thanks for the contribution but I am closing this as no matter what the cause of the problem this is not the correct way to resolve it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11242">issues.joomla.org/joomla-cms/11242</a>.</sub>

**Pull request closed without merging**
