### PR TITLE
helptext_shortened

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #21879

### Summary of Changes
Help text shortened.

### CODE REVIEW

**Comment by puneeth-chanda** [comment]
@Quy can you please review this

**Comment by zero-24** [comment]
cc @brianteeman seams to be a fair change to me? Can we get your native speaker opinion here too?

**Comment by brianteeman** [comment]
Is it shorter and easier to understand - yes
Is it the correct description of what happens when you pin/unpin the banner on the page where this is displayed - no

**Comment by puneeth-chanda** [comment]
@brianteeman can I know what is the correct description.

**Comment by hamby** [comment]
I've tested this item successfully. The new short description is good and more understandable. I made a short test successfully of the "Pinned" option as well. (4.0.0-beta1-dev)

**Comment by Quy** [comment]
Can the description be removed? Go to the Help page to read its full description.

**Comment by Quy** [comment]
Replaced PR #27508

**Pull request closed without merging**
