### PR TITLE
Implement a check / notification for an invalid or missing access file

### PR DESCRIPTION
**Pull request by matrikular**
### Summary of Changes

This PR implements a check and notification for an invalid or missing access file that is accessed in both core and 3rd party extensions via the JHelperContent::getActions method.

In the current implementation, depending on the error reporting level, an invalid argument warning would be either shown to the user or written to the php error log file.
### Testing Instructions
- Set the error reporting level of your (test) installation to maximum (Global Configuration - Server Settings - Error Reporting)
- Head over to the file system and rename an access.xml for e.g. administrator/components/com_banners to access.xml_
- Open the banners component in the backend. You should see something similar to this:
  pr_banner_before_patch

In a normal running website, the error reporting level would be set to "System Default" (reporting). The only indication for an invalid or missing access file, is just a few missing toolbar buttons.
- Apply the patch. You should see an error message like the one in the screenshot below.
  pr_banner_after_patch

### CODE REVIEW

**Comment by mbabker** [comment]
I wouldn't put the entire file path in the message.  Try this: "The %s component's ACL configuration file is either missing or improperly structured.", merge in the component's name.  If this message ever displays on the frontend as is that would be a full path disclosure.

**Review by brianteeman — COMMENTED** [review]
It is current practice not to delete a string - crazy I know but that's the practice

**Comment by brianteeman** [comment]
ignore that comment. I see now that was to fix an error in the PR and you are not removing a string

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on dae023e00dae80fb8089266de2f2542f7b56c9ae<br /><br />Works like described, thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12608">issues.joomla.org/tracker/joomla-cms/12608</a>.</sub>

**Comment by ufuk-avcu** [comment]
I have testes this successfully.

**Comment by ufuk-avcu** [comment]
I have tested this item :white_check_mark: successfully on dae023e00dae80fb8089266de2f2542f7b56c9ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12608">issues.joomla.org/tracker/joomla-cms/12608</a>.</sub>

**Comment by gunthelm2000** [comment]
I have tested this item :white_check_mark: successfully on dae023e00dae80fb8089266de2f2542f7b56c9ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12608">issues.joomla.org/tracker/joomla-cms/12608</a>.</sub>

**Comment by gunthelm2000** [comment]
I have also tested this item successfully!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12608">issues.joomla.org/tracker/joomla-cms/12608</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12608">issues.joomla.org/tracker/joomla-cms/12608</a>.</sub>

**Pull request merged**
