### PR TITLE
Update en-GB.tpl_beez3.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Updated template description

### CODE REVIEW

**Comment by brianteeman** [comment]
This changes the description from html 4 to html5

Is this template actually html5?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by aaleksanyants** [comment]
yes it is :-)

**Comment by infograf768** [comment]
Same string has to be changed in:
language/en-GB/en-GB.tpl_beez3.sys.ini

and in same files here:
templates/beez3/language/en-GB/en-GB.tpl_beez3.sys.ini
templates/beez3/language/en-GB/en-GB.tpl_beez3.ini

**Comment by aaleksanyants** [comment]
Thank for pointing out the appropriate files in template folder, all files have been changed

**Comment by jwaisner** [comment]
@aaleksanyants 

For testers, is there anything we should see different besides the strings being changed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by zero-24** [comment]
@jwaisner @aaleksanyants 

>For testers, is there anything we should see different besides the strings being changed?

No ;)

**Comment by zero-24** [comment]
If we get a `ok` by the en-GB WG we can move language files onky PRs to RTC ;)

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 41a4704a4788e1c3cb13f8d7d6057661337b0064<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by brianteeman** [comment]
By adding the version number for joomla this fails the style guide for the use of the joomla name https://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 41a4704a4788e1c3cb13f8d7d6057661337b0064<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by wojsmol** [comment]
@aaleksanyants see https://github.com/aaleksanyants/joomla-cms/pull/2

**Comment by andrepereiradasilva** [comment]
I have not tested this item.<br /><br />just a "!" so of course is tested ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by wojsmol** [comment]
@andrepereiradasilva Please mark on https://issues.joomla.org/tracker/joomla-cms/7360 as tested successfully.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1d2ba999c4aa5c1b4685223e9faaa7b31b5fa2e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by brianteeman** [comment]
Contacted Angie as the creator of the template to confirm the html5 change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed with Angie Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 26f275997542ce5c7533983a623f2ba10ba4908e<br /><br />Only updated the branch to latest staging. All equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7360">issues.joomla.org/joomla-cms/7360</a>.</sub>

**Pull request merged**
