### PR TITLE
[4.0] [mod_articles_category] Add items sublayout

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This adds a layout for items to remove duplicate code.

### Testing Instructions

The module should work like before.

### Documentation Changes Required
IDK.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 84dbc8983f6f08108d002677fcb38c481e3ebbe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24991">issues.joomla.org/tracker/joomla-cms/24991</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 52c865623f2c1f7011020a284ecb375099dea6f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24991">issues.joomla.org/tracker/joomla-cms/24991</a>.</sub>

**Comment by jwaisner** [comment]
@Quy Please retest.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24991">issues.joomla.org/tracker/joomla-cms/24991</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 52c865623f2c1f7011020a284ecb375099dea6f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24991">issues.joomla.org/tracker/joomla-cms/24991</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24991">issues.joomla.org/tracker/joomla-cms/24991</a>.</sub>

**Comment by richard67** [comment]
Restarted drone.

**Comment by richard67** [comment]
@SharkyKZ I can't see conflicts for this PR here on GitHub, but the clone step in drone reports merge conflicts when fetching your PR into a 4.0-dev. Could you check if you can update this PR to current 4.0-dev and solve conflicts if you have some? If not I could try to have a look, ping me then.

**Comment by SharkyKZ** [comment]
Branch updated. Didn't see any conflicts.

**Comment by richard67** [comment]
Then good luck with the drone .. maybe it just has severe hickup at the moment ;-)

**Comment by richard67** [comment]
Clone step already passed in drone .. that's a good sign.

**Comment by richard67** [comment]
@SharkyKZ Now GitHub shows me "This branch cannot be rebased due to conflicts" below all the green passed checks.

**Comment by SharkyKZ** [comment]
@richard67 What about now?

**Comment by richard67** [comment]
Same:
pr-24991
@wilsonge What does that mean? I don't see any conflicts.

**Comment by Quy** [comment]
Strange. I am not getting the message you got. I get the green button to squash and merge.

**Comment by richard67** [comment]
@Quy I see. I had rebase and merge selected from previous merge. Then it shows the above. Now I have changed to squash and merge in the dropdown and see what you say. Got it. In some case rebase and merge isn't possible, George told me. All ok.

**Comment by richard67** [comment]
Question now is shall we wait for the outstanding review by the code owner? @Quy What do you think?

@SharkyKZ Sorry for unnecessary rumor ;-)

**Comment by Quy** [comment]
Oops I have not been paying attention to `Reviewers`. I don’t know what the rules are so I guess we wait.

**Comment by richard67** [comment]
I have pinged him here and on Glip, let's see what happens.

**Comment by richard67** [comment]
I have tested it with success, too, and review looks good to me, so I merge.

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
