### PR TITLE
Overrides do not find 3rd party plugins language files when files are in the plugin language folder

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #19738

### Summary of Changes
The search for plugin languages files did not go deep enough

### Testing Instructions
See #19738

### After Patch
here for resourcerer
screen shot 2018-02-19 at 17 28 07

@toivo

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e69948ca3b4dcb9cafb44af7b86f06b5958ee0f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19740">issues.joomla.org/tracker/joomla-cms/19740</a>.</sub>

**Comment by Quy** [comment]
Installed Sourcerer 7.2.0. Without the PR, I still found `REGULAR_LABS_LIBRARY` and `SRC_TOGGLE_SOURCE_TAGS`.

**Comment by brianteeman** [comment]
weird as I couldnt

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e69948ca3b4dcb9cafb44af7b86f06b5958ee0f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19740">issues.joomla.org/tracker/joomla-cms/19740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19740">issues.joomla.org/tracker/joomla-cms/19740</a>.</sub>

**Comment by Quy** [comment]
@brianteeman Nevermind. I was searching on the cached strings.

**Pull request merged**
