### PR TITLE
Add tag description extract to administrator tags view

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #23056 .

### Summary of Changes

Get tags description from the db for later output by 3rd party template overides.

### Testing Instructions

**Note: Coded in Github UI, not tested in php, please ensure you test correctly**

see #23056

### Expected result

see #23056

### Actual result

see #23056

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2ebc81fc4cbce0d474fe48043c0e8af9b59fb3f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23057">issues.joomla.org/tracker/joomla-cms/23057</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 2ebc81fc4cbce0d474fe48043c0e8af9b59fb3f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23057">issues.joomla.org/tracker/joomla-cms/23057</a>.</sub>

**Comment by infograf768** [comment]
RTC as Travis fails on 7.3 for no reason.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23057">issues.joomla.org/tracker/joomla-cms/23057</a>.</sub>

**Comment by PhilETaylor** [comment]
[Travis PHP 7.3 is screwed. ](https://github.com/joomla/joomla-cms/issues/23060)

**Pull request merged**
