### PR TITLE
[4.0] superfluous markup - backtrace

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the class `Table` and `TD` from the markup in the error backtrace. Code review only needed as the class doesn't exist in the css. Or enable debug mode and then in the frontend force an error eg go to `index.php?option=com_wilson`

other than the removal of the classes that will be seen in the source there will be no other change

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8947d988fe9741adeab9ed314beafc4ffc6666d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27695">issues.joomla.org/tracker/joomla-cms/27695</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 @SniperSister can you please check the rips report here

**Comment by wilsonge** [comment]
Why am I now an example error 🙀 😛

**Comment by brianteeman** [comment]
@wilsonge you should be glad

**Comment by zero-24** [comment]
rips seams to be happy now. We had issues with false positives in the last days.

**Comment by brianteeman** [comment]
@zero-24 Thanks for checking

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks - would be good to clear the pr backlog before the end of the week

**Pull request merged**
