### PR TITLE
metis-menu css logical proprties

### PR DESCRIPTION
**Pull request by brianteeman**
There is no need to add this conditional css for rtl when we can just use logical css properties instead.

The original PR that added this was https://github.com/joomla/cassiopeia/pull/243

code review should be fine

### CODE REVIEW

**Review by drmenzelit — APPROVED** [review]

**Comment by webgras** [comment]
I just did a code review - looks fine.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 25c596b50b491e08f99087212acedd251b0180d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38359">issues.joomla.org/tracker/joomla-cms/38359</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38359">issues.joomla.org/tracker/joomla-cms/38359</a>.</sub>

**Comment by fancyFranci** [comment]
Much better! Thank you

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
