### PR TITLE
Support Unix Domain Socket for memcache and memcached Sessions.

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #23761 .

### Summary of Changes
Only set memcache port number if its greater then 0

### Testing Instructions
Set session handling to memcache and/or memcached (2 different extensions for PHP) and use a UDS path to connect to memcached (Daemon).

### Expected result
Login still works

### Documentation Changes Required
Using memcache with UDS set the port to 0.

### CODE REVIEW

**Comment by ghost** [comment]
@loureirorg please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by ghost** [comment]
Why is this PR on 3.9-dev and not on staging?

**Comment by sebenns** [comment]
You are right, this should be staging.

**Comment by richard67** [comment]
@tht2p @datsepp Please test.

**Comment by HLeithner** [comment]
@zero-24 are you interested to merged this or should I close it?

**Comment by zero-24** [comment]
Have noted it for 3.10.6 but will not merge it into 3.10.5 as we are in RC mode already.

**Comment by zero-24** [comment]
Merging here. Thanks!

**Pull request merged**
