### PR TITLE
[4.0] Smart search missing strings

### PR DESCRIPTION
**Pull request by brianteeman**
This fixes the missing strings reported in #30965.

It does not fix the problem causing these error strings to be displayed.

To replicate the error to see that this PR correctly adds the strings.

1. Install Sample Data
2. Index content with smart search
3. Unpublish all content maps
4. Try to publish all content maps at the same time
This should produce the plural error message
5. Try to publish any content map that is not a parent item
This should produce the singular error message

### CODE REVIEW

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on d563ea9b76599946e5467f28ca061931a58bb740<br /><br />Language strings now appear.

Language strings now appearing makes the issue in #30965 far easier to resolve now.
- If you have unpublished all the content maps, first publish all the top level items.
- You'll then be able to publish second level items as the parent item is published.
Confirms further @brianteeman notes in #30965.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31393">issues.joomla.org/tracker/joomla-cms/31393</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d563ea9b76599946e5467f28ca061931a58bb740<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31393">issues.joomla.org/tracker/joomla-cms/31393</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31393">issues.joomla.org/tracker/joomla-cms/31393</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
