### PR TITLE
Checking article alias

### PR DESCRIPTION
**Pull request by juliopontes**
The Joomla router allows site visitors to create fake URLs.

For example, adding index.php/component/content/article/1-write-your-message-here, where "1" is the ID of the article, will produce a fake URL.  "write-your-mesage-here" can be changed by anyone to anything, including offensive words, and make it appear that the site owner/administrator has generated the URL pattern when that's not the case.

As another example, category URLs can also be manipulated.  In Joomla 2.5's default sample data, the following URL (which is about Joomla) :
index.php/using-joomla/extensions/components/content-component/article-category-list/24-joomla

can be manipulated to:
http://yoursite/joomla/using-joomla/extensions/components/content-component/lets-use/24-wordpress

Note that, in the above example, both "article-category-list" and "joomla" have been manipulated.

Having such alternative links could be detrimental for SEO if a malicious user creates malicious URLs.  Furthermore, a site's reputation could be tainted by a malicious link if it appears to be coming from the site itself.

### CODE REVIEW

**Comment by pulsarinformatique** [comment]
Hi

With Joomla 3.4.8 you can still forge wrong urls :


This is a potential security issue with Joomla! As it is very easy to show I'm quite sure it's already known and possibly solved somehow.

On a basic Joomla! 3 site, without any extension, nor any .htaccess file, let's just create a few articles and a blog of the articles of the category menu item.


The url is as expected my_domain/index.php/mylist and for each article: my_domain/index.php/mylist/id-myarticle

However if I force the url this way : my_domain/keyword1/index.php/mylist/id-myarticle I don't get a 404 error page as expected but the same content as my_domain/index.php/mylist/id-myarticle !!

If you ctrl-u the newly forged page you see "keyword1" several times on the page.


This is a potential security / reputation threat when you replace "keyword1" with porn keyword!

Of course these pages don't really exist on the server but if a hacker creates such links from another site, the Googlebots can come and crawl these links and ... index the forged urls 

thanks

cyril

**Comment by brianteeman** [comment]
It might be many things but it certainly not a security issue

**Comment by pulsarinformatique** [comment]
Hi Brian

It may be because if a hacker create another site with these forged urls to you site, when the googleBots crawl the hacker site they will crawl back these wrong urls to your site.

Since there is no 404 the forged urls are considered as valid and the robot will index these forged pages.

Cyril

**Comment by mbabker** [comment]
URL spoofing, while massively annoying and leading to other issues, is not a security issue.  Otherwise Amazon is full of security holes because of social engineering attacks that try to spoof their website.

**Comment by pulsarinformatique** [comment]
Ok but even if you don't call it a security issue do we agree that for the final site owner he feels his site has been hacked with wrong contents at least on the google pages ?

Unless I forget something here all theses wrong urls give real pages with real contents (CTRL-u) in the google index and this is what is important for most users

cyril

**Comment by brianteeman** [comment]
Your example does not work
domain.com/keyword1/index.php/mylist/id-myarticle
will give a 404

There are other ways to spoof a url but thats not one

On 8 March 2016 at 16:27, Pulsar Informatique <notifications@github.com>
wrote:

> Ok but even if you don't call it a security issue do we agree that for the
> final site owner he feels his site has been hacked with wrong contents at
> least on the google pages ?
>
> Unless I forget something here all theses wrong urls give real pages with
> real contents (CTRL-u) in the google index and this is what is important
> for most users
>
> cyril
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/472#issuecomment-193849856>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
And through mechanisms such as canonical URLs, sitemaps, and robots.txt directives, these "fake URLs" don't get indexed.  Yes, it may be annoying that for a com_content article with ID 1 assigned as your homepage you could access it through `/index.php?option=com_content&view=article&id=1`, `/component/content/article/1`, or `/` (the latter if you've enabled SEF URLs and/or URL rewriting), but internally to Joomla if you have things configured right the canonical URL that gets spit out into the `<head>` section tells platforms like Google "this is the 'proper' URL for this page, no matter how you got to it".

**Comment by pulsarinformatique** [comment]
Brian
I confirm that domain.com/keyword/index.php/mylist/id-myarticle DOESN'T give a 404 but displays the same as domain.com/index.php/mylist/id-myarticle

Cyril

**Comment by pulsarinformatique** [comment]
Yes Michael, I think you are right. Since we can tell which url is the cannonical one for Google, other wrong forged urls won't be indexed!

**Comment by pulsarinformatique** [comment]
Something else: can we set a cannonical url for a list, not only a content page ?
because the issue here is not only on content pages but also on some list pages.

**Comment by brianteeman** [comment]
Tried again and still cannot replicate your exact issue on a clean install
with no htaccess

**Pull request closed without merging**
