### PR TITLE
[5.1] SEF: Change value for trailingslash option

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This PR implements parts of #43024. In Joomla 6.0, the `none` behavior is going to be dropped again. When that is the case, it will be difficult to explain why the switch contains the values 1 and 2. 

### Testing Instructions
codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Am I missing some information here/ Is this instead of #43024 ?

**Comment by Hackwar** [comment]
This PR tries to get this change still into 5.1 without enabling the SEF stuff for new installations.

**Comment by brianteeman** [comment]
ah - so you are saying this is an alternative proposal. Would be good to be clearer in the description

**Comment by richard67** [comment]
Wouldn't it need to "migrate" values when updating from 5.1.0 Beta 1 or Beta 2 or RC?

Otherwise it could happen that the functionality is enabled when the value is 0.

@LadySolveig @bembelimen What do you think?

**Comment by bembelimen** [comment]
Thx

**Comment by Hackwar** [comment]
Thank you!

**Pull request merged**
