### PR TITLE
Global config language string updates

### PR DESCRIPTION
**Pull request by brianteeman**
Some small updates to improve the language readability and consistency in the Global Config

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested :white_check_mark: successfully this item.
Thank you @brianteeman

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 4e00ae0eadb3ddae130af869a3d53b2688c1a256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11267">issues.joomla.org/joomla-cms/11267</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11267">issues.joomla.org/joomla-cms/11267</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 4e00ae0eadb3ddae130af869a3d53b2688c1a256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11267">issues.joomla.org/joomla-cms/11267</a>.</sub>

**Pull request merged**
