### PR TITLE
[4.0] Database Driver Fixes

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #18660

### Summary of Changes

Because I seriously doubt the [Framework pull request](https://github.com/joomla-framework/database/pull/114) is going to get the attention it needs, I'm bringing the development branch the pull request is based on into the CMS as a PR in hopes that one or two people might actually test it instead of us having to resort to a blind merge and hope for the best scenario.

See the linked pull request for details about the actual code changes involved in this pull request, and the linked issue for the various issues exposed in the CMS environment that should be fixed with this pull request.

### Testing Instructions

When installing Joomla, depending on which PHP extensions are installed and enabled in your environment, you should be able to install Joomla on:

- MySQLi (requires PHP's `ext/mysqli` to be enabled, prior to this PR it required that the MySQL support be compiled with `mysqlnd` but now environments where the MySQL support is compiled with `libmysql` should be supported)
- PDO MySQL (requires PHP's `ext/pdo` with MySQL support to be enabled)
- PostgreSQL (requires PHP's `ext/pgsql` to be enabled)
- PDO PostgreSQL (requires PHP's `ext/pdo` with PostgreSQL support to be enabled)

If using either of the PDO drivers, you will most likely need https://github.com/joomla/joomla-cms/pull/19989 to be applied in your environment (if/when that PR is merged this PR will be rebased so the branch includes those changes).

Once installed, Joomla should be able to be used as normal (well, as normal as one can against the current 4.0 development state).

### CODE REVIEW

**Comment by brianteeman** [comment]
Too late for me tonight but I will test installation etc tomorrow morning
THANKS

**Comment by brianteeman** [comment]
quick test. installer showed all 4 options
install successfully with mysql and mysqlpdo

**Comment by zero-24** [comment]
I can confirm the mysql pdo install works. But I don't know if it is expected that the database is not created during the install.

**Comment by mbabker** [comment]
Creating the database for PDO MySQL is covered by #19989 and is honestly a best effort thing in general (it requires us to parse the exception messages and try to determine if we can create it, IIRC neither PostgreSQL driver actually supports the create database operation in our installer).

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 2e0cfd5ced5790abe5fa3c81c9b881eae80e9ee9<br /><br />looks good than. I'm going to check the other PR too. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20055">issues.joomla.org/tracker/joomla-cms/20055</a>.</sub>

**Comment by mbabker** [comment]
Just so it's clear here, while testing of normal use of the application is going to help validate these changes, I really do need people to do a real code review here because I am making quite a few underlying API changes in the database API, some of which have B/C implications.

**Comment by mbabker** [comment]
After #20059 PR is no longer valid in current state.  Will re-open when I've had time to rebase.

**Comment by mbabker** [comment]
Work is complete from the FW repository to get this effort stable.

When running `composer update` to pull in the changes, I ended up getting several other package updates.  I have found that our `composer.lock` file has been changed to have updated dependencies without the respective changes in the `libraries/vendor` directory committed.  Therefore those changes are now included in this pull request because I can't do anything to fix that without further corrupting things.

**Review by wilsonge — APPROVED** [review]

**Comment by alikon** [comment]
@wilsonge can you consider to evaluate/merge #19989 too ?

**Pull request merged**
