### PR TITLE
[4.0] Switch rating stars from png images to icons

### PR DESCRIPTION
**Pull request by htmgarcia**
Pull Request for Issue NA .

### Summary of Changes
The **Content - Vote plugin** currently uses png images to display the rating stars in articles. Let's take advantage of Font Awesome and use icons instead.
lorem_ipsum_rocks___3_

### Testing Instructions
Enable **Content - Vote** plugin for articles
Preview in frontend

### CODE REVIEW

**Comment by brianteeman** [comment]
This adds a hard requirement to use font awesome in all front end templates. Is that really desirable?

**Comment by mbabker** [comment]
It's an overridable layout (the whole voting capability should still just be inlined into com_content but `¯\_(ツ)_/¯`)

**Comment by htmgarcia** [comment]
@brianteeman com_content is already using Font Awesome icons in other elements
A couple of examples:
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/info_block/hits.php#L16
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/info_block/modify_date.php#L17

**Comment by brianteeman** [comment]
it may well be right now but one of the aims was to remove that requirement not add to it

**Comment by htmgarcia** [comment]
@brianteeman this "_let's not stick with Bootstrap_" but at the same time "_let's use it partially_" approach is inconsistent. I find impossible to know where is fine and where is not to make use of dependencies like BS4 (and now same case with Font Awesome). 
____
A clear guidance on this matter would be useful.

**Comment by mbabker** [comment]
My two cents.  We're never going to have a core UI that is 100% decoupled from any framework.  So, as long as we have all this "framework coupling" in overridable layouts, at this point I'm leaning toward "who cares, replace it if you want".

**Comment by brianteeman** [comment]
I am just repeating what "powers that be" have said about frontend decoupling - not giving an opinion as thatis too dangerous

**Comment by htmgarcia** [comment]
Keeping consistency is a good practice, and also is my personal opinion.

Regards

**Comment by laoneo** [comment]
I would rather go with https://github.com/joomla/40-backend-template/pull/441. I'v used a similar technique in DPCalendar. Like that it is possible for a template to override icons. If there is interest, I can migrate the pr here.

**Comment by brianteeman** [comment]
@laoneo is that needed? This is a front-end layout that can already be overridden

**Comment by laoneo** [comment]
Icons have always been a pain in Joomla. There should be an easy way to change them and to have a strategy which serves the core and extension devs.

Making always an override of every view when you want to change the icon set sounds for me not optimal. Keep in mind we have forms, etc. with icons. Having a common layout where you can pass a string and it returns an icon is for me the way to go.

**Comment by mbabker** [comment]
> Having a common layout where you can pass a string and it returns an icon is for me the way to go.

Explain this bit in more detail.  Because right now I'm afraid you're going to have this as a layout file, which would be about as crappy as that [`endtab.php` file](https://github.com/joomla/joomla-cms/blob/3.8.12/layouts/libraries/cms/html/bootstrap/endtab.php):

```php
<?php
$icon = $displayData['icon'];
?>
<span class="<?php echo $icon; ?>"></span>
```

**Comment by laoneo** [comment]
We do load them inline in a [JLayout](https://github.com/Digital-Peak/DPCalendar-Free/blob/master/com_dpcalendar/site/layouts/block/icon.php). So the template dev can override the layout itself or place the required icons in the template folder itself.

**Pull request closed without merging**
