### PR TITLE
Fix several TODOs in code

### PR DESCRIPTION
**Pull request by wilsonge**
- Removes two lines of code to be removed (since 2011)
- Adds a doc block

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on dedea31bb4de32c47160681e1e74b19658879b7d<br /><br />Simple change. Unrelated problem with drone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23238">issues.joomla.org/tracker/joomla-cms/23238</a>.</sub>

**Comment by laoneo** [comment]
Forwarded drone issue to @SniperSister

**Comment by zero-24** [comment]
FYI: there are no information about this in the rips console. I have just relaunched the drone test: http://ci.joomla.org/joomla/joomla-cms/12804 lets see what happens and what might show up in the console

**Comment by infograf768** [comment]
restarted drone

**Pull request merged**
