### PR TITLE
Language Consistency fix for using the plg name: 'System - Language Filter'

### PR DESCRIPTION
**Pull request by MATsxm**
#### Summary of Changes

Not sure it is that important but for a better consistency, the plugin name in the list is not `System - Languagefilter` **but** `System - Language Filter`.
#### Testing Instructions

Easy fix on code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bc57407c15796e611d34e5426862383faec42d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10779">issues.joomla.org/joomla-cms/10779</a>.</sub>

**Comment by brianteeman** [comment]
Simple Fix - RTC
(as this only effects in en-GB there is no reason for it not to be merged)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10779">issues.joomla.org/joomla-cms/10779</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10779">issues.joomla.org/joomla-cms/10779</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot can you please help here?

**Pull request merged**
