### PR TITLE
[administrator/components] Fix alignment for arrays and for some assignments.

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
[administrator/components] Fix alignment for arrays and for some assignments. + insert one blank line.

### Testing Instructions
None, code review only.

### Documentation Changes Required
None.

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 3a71e0753aad187c7cbd3f8eb79f1f9cf4404a7b<br /><br />Code review OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13440">issues.joomla.org/tracker/joomla-cms/13440</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a71e0753aad187c7cbd3f8eb79f1f9cf4404a7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13440">issues.joomla.org/tracker/joomla-cms/13440</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by frankmayer** [comment]
@franz-wohlkoenig there is a conflicting file. Should I fix this first?

**Comment by franz-wohlkoenig** [comment]
@frankmayer yes, please.

**Comment by frankmayer** [comment]
@franz-wohlkoenig done (seems the Appveyor queue is stuck, though...)

**Pull request merged**
