### PR TITLE
[4.0] Add workflow to the installation sample data

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR fixes the installation sample data. Now they are assigned to the specific stages.

### Testing Instructions
- Reinstall Joomla! 4
- At the last step, skip the language and install sample datas
- After the installation check the articles

### Expected result
- All articles should work with the default workflow (Change stage)

### Actual result
- Articles are broken

### CODE REVIEW

**Comment by ChristineWk** [comment]
Hi bembelinen,

I'm not sure, if my failures has same behaviour. I made the update from here: https://developer.joomla.org/nightly-builds.html (date 03sep2018)
Update Source (Channel) should be OK. 

Frontend:

Joomla\Database\Exception\PrepareStatementFailureException: Table &#039;9130520db12.qdg46_workflow_stages&#039; doesn&#039;t exist in /my path/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:135

Backend:

0 Argument 1 passed to Joomla\Utilities\ArrayHelper::getColumn() must be of the type array, boolean given, called in /my path/administrator/components/com_content/Model/ArticlesModel.php on line 495 

and Stack Trace shows also many comments.

If it's not possible to use Patch-Tester, could I make amendments as shown in your PR accordingly in that file?

Thank you. Sorry, I can't find a button to insert Codes and: I wanted to insert your PR and then my post were lost :-)

Christine
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21978">issues.joomla.org/tracker/joomla-cms/21978</a>.</sub>

**Comment by alikon** [comment]
it is a duplicate of #21681 ?

**Comment by ChristineWk** [comment]
@alikon 
I don't know, but will check nevertheless. Update from "my situation" x tried following:

Backend: System > database > Warning: There are tables not up to date > Problems > 1 Problem > Pressed Fix button.
Result: Info: All database table structures are up to date. 

Menues, Categories are available & shown - but I lost all articles. Now I give up.
Sorry for causing annoyance. Thank you. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21978">issues.joomla.org/tracker/joomla-cms/21978</a>.</sub>

**Comment by chmst** [comment]
@ChristineWk

>  If it's not possible to use Patch-Tester, could I make amendments as shown in your PR accordingly in that file?
Yes, you always can do that. Which problems do you have with patchtester?

**Comment by ChristineWk** [comment]
@chmst 

in principle I don't have problems using patchtester, but I didn't use it on Joomla 4 yet. 

Update from my situation: As I wrote above, menues, categories are available, activated and also user.css (some formatting) has not been removed :-)
But all my articles are gone. Re-importing from an older MySQL will not help (think so).

After my last comment above, I tried to create a NEW article (in present category/menue). Unfortunately the response is:

Fehler - Speichern fehlgeschlagen - No default workflow available, please define one or contact ..... 

I also think, that PR https://github.com/joomla/joomla-cms/commit/d945a22464b84b20b8458be3609484ae4acc4cef belongs to a NEW installation. Therefore my case might be wrong here. Sorry about & Thank you.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21978">issues.joomla.org/tracker/joomla-cms/21978</a>.</sub>

**Comment by chmst** [comment]
Testing this PR with nightly build is not possible, as there is no installation/sql/mysql/sample_testing.sql file. 
Adding the file from the dev 4.0 branch brings Workflow and transitions.

**Comment by bembelimen** [comment]
@alikon you're right and I also tested your code, d'oh...my brain is a mesh.

But one thing: one article is archived in the sample data, this should be taken in account.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d945a22464b84b20b8458be3609484ae4acc4cef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21978">issues.joomla.org/tracker/joomla-cms/21978</a>.</sub>

**Comment by HRIT-Florian** [comment]
I have tested this item :white_check_mark: successfully on d945a22464b84b20b8458be3609484ae4acc4cef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21978">issues.joomla.org/tracker/joomla-cms/21978</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
