### PR TITLE
[com_modules] - show only current user access level modules

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #18331 .

### Summary of Changes
added current user acl check

### Testing Instructions
see #18331

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7c48afdee423d13575e20acfcbfc569f9a51fd0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18335">issues.joomla.org/tracker/joomla-cms/18335</a>.</sub>

**Comment by ghost** [comment]
@sonosergio please test.

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 7c48afdee423d13575e20acfcbfc569f9a51fd0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18335">issues.joomla.org/tracker/joomla-cms/18335</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by conseilgouz** [comment]
Please check https://github.com/joomla/joomla-cms/issues/18542

Pascal

**Pull request merged**
