### PR TITLE
[3.9.24rc] Do not send the smtppass on test if field is disabled

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #31715 .

### Summary of Changes
Does not use the smtp password for test emails if the field is disabled

### Testing Instructions

First test
* Use SMTP auth in global configuration
* set credentials for smtp auth
* save them
* set a test mail

Second test
* Use SMTP auth in global configuration
* set credentials for smtp auth
* save them
* click on modify for the smtp password
* enter correct password
* set a test mail

### Actual result BEFORE applying this Pull Request

First: failed because wrong password is used
Second: worked because the new password is used

### Expected result AFTER applying this Pull Request
First: works because the stored password is used
Second: worked because the new password is used

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b070c58c4086b28a7a6cb96d57d44d0f9d48fa44<br /><br />Tested successfully in 3.9.24-rc of 19 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31724">issues.joomla.org/tracker/joomla-cms/31724</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b070c58c4086b28a7a6cb96d57d44d0f9d48fa44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31724">issues.joomla.org/tracker/joomla-cms/31724</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31724">issues.joomla.org/tracker/joomla-cms/31724</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
