### PR TITLE
[4.0] php 7.2 compatibility

### PR DESCRIPTION
**Pull request by brianteeman**
Due to a change With php 7.2 the control panel shows several errors with the article related modules

> Warning: count(): Parameter must be an array or an object that implements Countable in C:\Apache24\htdocs\cms4\administrator\components\com_content\Model\ArticlesModel.php on line 307

### CODE REVIEW

**Comment by mbabker** [comment]
Since https://github.com/joomla/joomla-cms/pull/18438 was merged this should be fixed by branch merging staging -> 3.9 -> 4.0.  GitHub says the 4.0 branch is 130 commits behind staging right now so there's a bit of work waiting whenever the merge happens next.

**Comment by brianteeman** [comment]
OK will leave open for now and hope that @wilonge brings 4.0 upto date and then if not needed then this can be closed

**Comment by wilsonge** [comment]
Shame that person doesn't exist on github :P cause sounds like a tough one for him :) (i'll get on it tomorrow)

**Comment by brianteeman** [comment]
> i'll get on it tomorrow)

Is it tomorrow yet?

**Comment by wilsonge** [comment]
Kinda - i got 3.8.3 merged as of Tuesday and I've made a start on 3.8.5 locally

**Comment by wilsonge** [comment]
In fact actually it is https://github.com/joomla/joomla-cms/blob/9b719ee70123cf84fc3b2d5266ef9362f5426e5c/administrator/components/com_content/Model/ArticlesModel.php#L302-L305 is the fix @mbabker mentioned that went into 3.8.3 - so closing this

**Comment by wilsonge** [comment]
Thanks for the prod tho!

**Pull request closed without merging**
