### PR TITLE
[4.1] Log in to read messages

### PR DESCRIPTION
**Pull request by brianteeman**
when you have enabled notifications for workflows then the default message will be similar to
```

The status of an Article has been changed

Title: New feature: Workflows, changed by Brian Teeman, new state: Basic Stage.

Please log in to http://localhost/joomla-cms/administrator/index.php?option=com_messages&view=message&message_id=2 to read your message.
```

The last line implies that if you log in you will be able to read more about this message - and you might not even have the permissions to log in and read. However the online version of the message does not contain anything extra so there is no need to log in at all.

This PR changes the string to remove the information about logging in

```
The status of an Article has been changed

Title: New feature: Workflows, changed by Brian Teeman, new state: Basic Stage.
```

Pull request for #30361

### CODE REVIEW

**Comment by Kostelano** [comment]
Yes, but this is a personal message template. And it contains tons of other available tags.

What is the point of using this template for workflows if, in fact, this template has become useless, because breaks another unrelated component...

**Comment by brianteeman** [comment]
99% sure that you are mistaken

**Comment by chmst** [comment]
Looks good for me. The message is only that a transition has been performed and is complete. 

@Kostelano Sorry,  I don't understand. Which template do you mean?

**Comment by Kostelano** [comment]
@chmst I'm talking about changing the email template. At the moment this template has other tags available that I can use in the body of the email. Considering that this template is also used for workflows (as we see in the original problem), it turns out to be a kind of mess - we'd better NOT use some tags, because they will be irrelevant in workflow emails.

Screenshot_1

**Comment by brianteeman** [comment]
The mail template takes its values from sql not the language string iirc. Either way even in that mail template it is a useless string for the same reasons mentioned above

**Comment by paternax** [comment]
The solution sounds good. 
At the moment not possible to test, because the workflow in J.4.0.3. sends no notifications, even not to super user.

**Comment by brianteeman** [comment]
@paternax I was successfully getting emailed notifications  BUT I suspect you hit another problem with notifications using com_messages in that it wont send a notification to you if you are the one that made the change and triggered the notification. Could you please create another super user and then see if they get the notifications

**Comment by paternax** [comment]
Yes you are right, that is exactly the problem. I tested this with two superusers and an explicit user in notifications. The same by using the usergroup superuser only the other superuser, who didn't made execute the transition gets an email.

**Comment by brianteeman** [comment]
@paternax which is logical but perhaps not expected

**Comment by brianteeman** [comment]
rebased to 4.1

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 56e181c000e5d5a9abec97f64bf013e1fe587224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35693">issues.joomla.org/tracker/joomla-cms/35693</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 56e181c000e5d5a9abec97f64bf013e1fe587224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35693">issues.joomla.org/tracker/joomla-cms/35693</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35693">issues.joomla.org/tracker/joomla-cms/35693</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
