### PR TITLE
light checksum for joomlaupdate

### PR DESCRIPTION
**Pull request by alikon**
...from https://github.com/joomla/joomla-cms/pull/17619#issuecomment-323532941
add light checksum for joomla update

### Summary of Changes
trigger the checksum check on update
if the update server manifest have an hash tag 

### Testing Instructions

- start with latest staging (for time of writing) version 3.8.0-beta5
- apply pr #17619
- in order to simulate a joomlaupdate
- - run` php bump version 3.8.0-beta4` (i.e one version before)
- set Update channel to custom URL for example (http://localhost/test/list_testpr17632.xml)
- create that file with something like this content

```xml 
<extensionset name="Joomla Core Test Updateserver" description="The Joomla Core Update Server for Tests of Alpha, Beta and RC Releases">
 <extension name="Joomla" element="joomla" type="file" version="3.8.0-beta4" targetplatformversion="3.8" detailsurl="http://localhost/test/extension_testpr17632.xml" />
</extensionset>
```

- create http://localhost/test/extension_testpr17632.xml with  something like this content

```xml 
<?xml version="1.0" ?>
<updates>
	<update>
		<name>Joomla! 3.8</name>
		<description>Joomla! 3.8 CMS</description>
		<element>joomla</element>
		<type>file</type>
		<version>3.8.0-beta4</version>
		<infourl title="Joomla!">https://www.joomla.org</infourl>
		<downloads>
			<downloadurl type="full" format="zip">http://localhost/test/Joomla_pr17632-Update_Package.zip</downloadurl>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<maintainer>Joomla! PLT</maintainer>
		<maintainerurl>https://www.joomla.org</maintainerurl>
		<targetplatform name="joomla" version="3.[3456789]"/>
		<php_minimum>5.3.10</php_minimum>
	</update>
</updates>

```

- download the last joomla update package for example https://github.com/joomla/joomla-cms/releases/download/3.8.0-beta4/Joomla_3.8.0-beta4-Beta-Update_Package.zip
- copy & rename accordingly on the previous  `downloadurl` tag (for example `Joomla_pr17632-Update_Package.zip`

- Go to Components -> Joomla! Updates
you shoud see something like 
screenshot from 2017-09-02 09-01-06

# Test case 1 - no checksum hashtag in the update server manifest
### Expected result
 a notice is showed 

screenshot from 2017-09-02 09-08-18

# to test the next  2 cases we need to : 
- calculate the hash value (for example sha256) 
- -(on linux) run  `sha256sum Joomla_pr17632-Update_Package.zip`
screenshot from 2017-09-02 09-27-09

# Test case 2 - correct checksum hashtag in the update server manifest

- add a `<sha256>correcthashvalue</sha256>` tag in the current update server instance something like:

screenshot from 2017-09-02 09-30-38

### Expected result
 a info is showed 
screenshot from 2017-09-02 09-37-45

# Test case 3 - wrong checksum hashtag in the update server manifest
- add a `<sha256>wronghashvalue</sha256>` tag in the current update server instance
### Expected result
 a warning  is showed 

screenshot from 2017-09-02 09-40-32

### Documentation Changes Required
new tags : 

- `<sha256></sha256>`
- `<sha384></sha384>`
- `<sha512></sha512>`

### CODE REVIEW

**Comment by zero-24** [comment]
@mbabker can we have your final words on the algos as SHA1 and MD5 are very well known to be weak. Expecial as the core should provide a more secure algo.

**Comment by mbabker** [comment]
Personally I'd rather not support SHA1 and MD5 since they are weak.  If SHA256 doesn't have the same weaknesses then that'd be fine.

**Comment by alikon** [comment]
ok now #17619 support only sha256

**Comment by alikon** [comment]
should we consider to add sha512  "longer is better" ?

**Comment by zero-24** [comment]
> should we consider to add sha512 "longer is better" ?

Sounds good. ;)

**Comment by anibalsanchez** [comment]
@alikon detailed the steps to create list.xml and extension_sts.xml.... so I guess he was thinking to enter the Url on the "Custom URL" field.

In "Joomla Update", you have "Options", where you can play with "Update Channel"
For testing, you can change it to a "Custom URL".

**Comment by alikon** [comment]
@anibalsanchez , @NunoLopes96
added more clear test info ;)

**Comment by ghost** [comment]
@anibalsanchez , @NunoLopes96 are Test Info @alikon suggested unclear?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17632">issues.joomla.org/tracker/joomla-cms/17632</a>.</sub>

**Comment by anibalsanchez** [comment]
It is OK for me.

**Comment by ghost** [comment]
@anibalsanchez can i alter above Comment as successfully Test?

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on f61f6ab2009a62fcd87c283e495c85bff67e0e82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17632">issues.joomla.org/tracker/joomla-cms/17632</a>.</sub>

**Comment by anibalsanchez** [comment]
**Test OK**

My notes:

* Apply PR #17619 AND PR #17632 
* I tested updating from 3.8.0 to 3.8.1
* After every test, Joomla is updated... so the patches have to be re-applied for the next test

These are my xmls:

list_testpr17632.xml


	<extensionset name="Joomla Core Test Updateserver" description="The Joomla Core Update Server for Tests of Alpha, Beta and RC Releases">
	 <extension name="Joomla" element="joomla" type="file" version="3.8.1" targetplatformversion="3.8" detailsurl="http://local-server.extly.com/j38/extension_testpr17632.xml" />
	</extensionset>

extension_testpr17632.xml

	<?xml version="1.0" ?>
	<updates>
		<update>
			<name>Joomla! 3.8</name>
			<description>Joomla! 3.8 CMS</description>
			<element>joomla</element>
			<type>file</type>
			<version>3.8.1</version>
			<infourl title="Joomla!">https://www.joomla.org</infourl>
			<downloads>
				<downloadurl type="full" format="zip">http://local-server.extly.com/j38/Joomla_pr17632-Update_Package.zip</downloadurl>
			</downloads>
			<tags>
				<tag>stable</tag>
			</tags>
			<sha256>e8339bed3cbba5eebb7d355e026d29594ec164420beebe97839b0019b630ed96</sha256>
			<maintainer>Joomla! PLT</maintainer>
			<maintainerurl>https://www.joomla.org</maintainerurl>
			<targetplatform name="joomla" version="3.[3456789]"/>
			<php_minimum>5.3.10</php_minimum>
		</update>
	</updates>

**Comment by NunoLopesPT** [comment]
I have tested this item :white_check_mark: successfully on f61f6ab2009a62fcd87c283e495c85bff67e0e82<br /><br />Great Work !!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17632">issues.joomla.org/tracker/joomla-cms/17632</a>.</sub>

n3
n1
n2

**Comment by alikon** [comment]
@NunoLopes96  just a follow up  from your work at Joomla GSoC 17 project https://github.com/joomla-projects/gsoc17_expand_extension_manager

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by Quy** [comment]
@brianteeman Please retag for v3.9.0. Darn bot!

**Comment by alikon** [comment]
conflict solved

**Pull request merged**
