### PR TITLE
[4.0] Remove the deprecated code in the CacheController class

### PR DESCRIPTION
**Pull request by laoneo**
Remove the deprecated code in the CacheController class.

### CODE REVIEW

**Comment by mbabker** [comment]
IIRC I tried this once and it's not as simple as just deleting these methods.

**Comment by laoneo** [comment]
What was the issue?

**Comment by mbabker** [comment]
Wait, nevermind.  I think it was something to do with turning one of the classes abstract as noted that was giving me problems.

Either way this actually further highlights a problem we have.  The `get()` method has a different signature in each subclass so there's no way to sanely make an abstract or interface method declaration.

Also, you need to make sure all the controller subclasses have the `store()` method inlined.  2 of the 4 were using this base method declaration.

https://github.com/joomla/joomla-cms/pull/12312 for more context.

**Comment by laoneo** [comment]
So either way we copy the function to the extending classes or do revert back the deprecate message.

**Comment by laoneo** [comment]
Ok, copied the store functions to the implementing classes.

**Pull request merged**
