### PR TITLE
[4.0] Fixing JS in com_finder

### PR DESCRIPTION
**Pull request by Hackwar**
The JS in com_finder in 4.0 is very broken. There are several issues:

* When typing in the input field, it looses focus very quickly, makeing input nearly impossible.
* When typing quickly and then sending the form before the suggestions ajax request is fulfilled, an empty error message is shown shortly.
* Suggestions are displayed for the previous term in the input field. So if you are typing the word "francais" and so far got "fra" and then press "n", the suggestions will retrieve the suggestions for "fra" and not for "fran". Likewise when deleting a character. So when you delete the "n" of "fran", you will get suggestions for "fran" instead.
* Also sometimes the suggestions aren't displayed at all.

This PR fixes all of these things. I first updated the awesomplete suggestion script with the current head version from its repo (https://github.com/LeaVerou/awesomplete). The last release is from 2017 and we already have that in our codebase, which currently creates the focus errors.

I then created the awesomplete object just once and attached it to the input object, instead of creating it on each ajax call. Now we just update the list instead.

The event for the suggestions update is now upon "keyup", which then now takes the right string for the suggestions.

There is a bit of code that seems to be from a time where the placeholder attribute wasn't present. I removed that.

And last but not least, the error case for the ajax call first checks if there is any status code given. When we are just aborting the ajax call because we are submitting the form, then the status code is 0, otherwise it would be something like 200, 404 or 500.

Happy testing. Hope this makes you happy, @infograf768 and @carlitorweb :wink:

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Hackwar if you need to do changes on a vendor file you need to do them upstream!
This cannot be accepted because the `npm install` is removing the media/vendor folder and recreates it from the relative sources. So this is a no go!

Also the package.json dependencies have a format `npm name`: `version` so putting there some string is not gonna work.

Just do a `npm i` or `node build.js --update` and see what you are breaking here

**Comment by Hackwar** [comment]
package.json supports github repo links, which is what I did. I also did not modify the awesomplete files, but simply took the current head of their github repo. Considering that the last commit that I did to this PR is the result of ```npm install```, I'm pretty confident with this. BTW: When doing an ```npm install``` on the current head of 4.0-dev, there is quite a few things that are being changed. So maybe you should again update this.

**Comment by infograf768** [comment]
👍 
Focus back and suggestions look fine with my first tests.

**Comment by infograf768** [comment]
Now, just please solve the highlighting for non-ascii stuff. ;)

**Comment by Hackwar** [comment]
Did that in #20571 :wink:

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 011bbab6e03959ea271acbda0b807ab59277a513<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20888">issues.joomla.org/tracker/joomla-cms/20888</a>.</sub>

**Comment by carlitorweb** [comment]
nice one!!!

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 011bbab6e03959ea271acbda0b807ab59277a513<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20888">issues.joomla.org/tracker/joomla-cms/20888</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
