### PR TITLE
[4.0] Fix js error when previewing admin template

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/29120

### Summary of Changes
Use conditional for the `$content` variable

### Testing Instructions
Make sure that the Preview Module Positions is set to enabled
Click on the eye to open the preview if in  template style or Preview Toolbar in templates manager

### Before patch
js error. See https://github.com/joomla/joomla-cms/issues/29120
### After patch

No more error

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 673f18a58f867216bf4ebd709c09ea6c5b60d00b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29124">issues.joomla.org/tracker/joomla-cms/29124</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 673f18a58f867216bf4ebd709c09ea6c5b60d00b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29124">issues.joomla.org/tracker/joomla-cms/29124</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29124">issues.joomla.org/tracker/joomla-cms/29124</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
