### PR TITLE
Suggest text change of PR Template to make it more clear

### PR DESCRIPTION
**Pull request by PhilETaylor**
Take it or leave it - Up to you. 

Expected/Actual is "[often subject of confusion](https://github.com/joomla/joomla-cms/pull/29731#issuecomment-647116328)".

New headings make it more clearer-er. 

// @richard67

### CODE REVIEW

**Comment by richard67** [comment]
I agree 100% with the motivation and the goal of this PR, but maybe the texts can be optimized?

I'd like to know @brianteeman 's opinion.

Maybe just drop the "Expected" so we just have "Result BEFORE applying this PR" and "Result AFTER applying this PR"?

Or maybe stay with "Actual" and "Expected" so we have "Actual result BEFORE applying this PR" and "Expected result AFTER applying this PR"?

And maybe in general use "Pull Request" instead of "PR"?

**Comment by PhilETaylor** [comment]
> I'd like to know @brianteeman 's opinion.

Dont worry I'm sure he will give it. haha

**Comment by richard67** [comment]
Why closing?

**Comment by PhilETaylor** [comment]
Changed as proposed:

```
### Actual result BEFORE applying this Pull Request
### Expected result AFTER applying this Pull Request
```

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f06184e30bedb07e7e853ac0b9c0c97d721f0ce8<br /><br />Makes sense to me and is an improvement in my opinion. Meaning of actual and expected result always was subject of confusion at least for new contributors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29732">issues.joomla.org/tracker/joomla-cms/29732</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f06184e30bedb07e7e853ac0b9c0c97d721f0ce8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29732">issues.joomla.org/tracker/joomla-cms/29732</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29732">issues.joomla.org/tracker/joomla-cms/29732</a>.</sub>

**Comment by wilsonge** [comment]
Seems clearer to me. Thanks!

**Pull request merged**
