### PR TITLE
[4.0] [a11y] Rules permissions - text filters notes

### PR DESCRIPTION
**Pull request by brianteeman**
I am not sure what the logic/reasoning was for putting the notes on the permissions tab inside a custom element "joomla-alert" but it was wrong - it is not an alert it is just information. Making it an alert has significant impact.

This custom element adds role="alert" to the container. In a11y this role=alert is equivalent to using aria-live=assertive. aria-live="assertive" should be used only when you think the user needs to know the information the very second it appears. 

So what happens is that as soon as the permissions tab gets focus and before anything else can happen the entire content of the alert is announced (and cannot be interrupted because it is so important).

This PR changes it back to a simple div and adds some simple css - which obviously can be changed and improved upon.

### [update]
Also added the text-filter notes at the bottom of the page to this PR as its basically the exact same problem

(can be tested with patchtester)

### CODE REVIEW

**Comment by brianteeman** [comment]
Conflicts resolved

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on e6ff34482dac61f2063af5ce59399ccfe0f106ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21559">issues.joomla.org/tracker/joomla-cms/21559</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on e6ff34482dac61f2063af5ce59399ccfe0f106ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21559">issues.joomla.org/tracker/joomla-cms/21559</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21559">issues.joomla.org/tracker/joomla-cms/21559</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
