### PR TITLE
[4.0] Core spinning logo

### PR DESCRIPTION
**Pull request by dgrammatiko**
A redo of #19677 .

### Summary of Changes
Just a web component that creates a spinning logo.

### Testing Instructions

Apply this patch.
Make sure Custom Fields are enabled.
Try to edit an article and change the category
Boom...

Enjoy the infinite loop...

### Expected result

jul-15-2018 12-45-27

### Documentation Changes Required
The only breaking change here is that the core.js Fuction Joomla.loadingLayer() will **not** load the webcomponent, that needs to be done in the relative layout with:
```php
HTMLHelper::_('webcomponent', 'system/webcomponents/joomla-core-loader.min.js', ['relative' => true, 'version' => 'auto']);
```

This PR depends on https://github.com/joomla/joomla-cms/pull/21117

### CODE REVIEW

**Comment by brianteeman** [comment]
There appear to be a lot of unrelated changes in this pr

**Comment by dgrammatiko** [comment]
@brianteeman This PR depends on #21117

**Comment by brianteeman** [comment]
The usual way is to keep the pr clean and then to ask testers to make sure they have a dependent pr applied first. This is beneficial for you if there are errors/changes in the other pr. It also means testers can be sure what they are testing and report errors in the correct place. Thanks

**Comment by dgrammatiko** [comment]
Well, in this case, is not so straightforward, because to test this PR you had to apply the other PR. Do npm install, apply this PR and the do node build.js --compilecejs. Nobody will ever go this far to test a PR...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 17b16bd37435815b9c3172c2da82b9686ea5102f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21129">issues.joomla.org/tracker/joomla-cms/21129</a>.</sub>

**Comment by wilsonge** [comment]
Way too much going on here in files (some stuff I know is fixed elsewhere) and all the conflicts. Closing this and we can reopen it with a fresh PR when you are ready :)

**Pull request closed without merging**
