### PR TITLE
Recently added articles sorting admin panel

### PR DESCRIPTION
**Pull request by frostmakk**
Pull Request for Issue #14749  

### Summary of Changes
Added sort order

### Testing Instructions
View admin cpanel

### Expected result
Proper sorting

### Documentation Changes Required
No

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on f1e766223ec92a9ce79b042d0aeaecae6b62d22d<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14943">issues.joomla.org/tracker/joomla-cms/14943</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f1e766223ec92a9ce79b042d0aeaecae6b62d22d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14943">issues.joomla.org/tracker/joomla-cms/14943</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14943">issues.joomla.org/tracker/joomla-cms/14943</a>.</sub>

**Pull request merged**
