### PR TITLE
Removed Else statement from getUserStateFromRequest

### PR DESCRIPTION
**Pull request by Mathewlenning**
Very simple change

### CODE REVIEW

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 81750b1fe06f597b2099041dff7515d2484efd7b<br /><br />Looks good to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7975">issues.joomla.org/joomla-cms/7975</a>.</sub>

**Comment by sovainfo** [comment]
Disagree with this change. Don't mind removing use of variable, do mind setting user state regardless whether it was changed in the request. Would prefer it not be set unneeded or change the comment to reflect what is done in code!

**Comment by Mathewlenning** [comment]
Actually NoNumber presented a better refactor that keep the signature and side effects the same as before. I'll update it when I get back to my desk.

Sincerely,
Mathew Lenning

P.S. This message was sent via iPhone, so please forgive any errors

**Comment by Mathewlenning** [comment]
@n9iels Thanks for testing. I appreciate it =^D

**Comment by sovainfo** [comment]
Not using the variable $cur_state would be an quality improvement and more efficient.

**Comment by wilsonge** [comment]
Merged on review - thanks Mathew!

**Pull request merged**
