### PR TITLE
[4.2] PHP8.2 Define the JComponentTitle property in WebApplication class

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
~Adds a check when the title is rendered in the toolbar if the app has the property `JComponentTitle`.~

~We are going basically back to the beginning https://github.com/joomla/joomla-cms/commit/cdd4173c70ff71735a6ff2a34a80c7ecb313304f#diff-5f6eb93d25275fcc88e719c1c9e8df1de7be12c716b4632404256471aa953ad4L41.~

Defines the missing property `JComponentTitle` in the WebApplication class. After this is upmerged to 4.3, it will be deprecated.

### Testing Instructions
Open the back end with PHP 8.2.

### Actual result BEFORE applying this Pull Request
The wollowing warning is shown:
`Creation of dynamic property Joomla\CMS\Application\AdministratorApplication::$JComponentTitle is deprecated in libraries/src/Toolbar/ToolbarHelper.php on line 52

### Expected result AFTER applying this Pull Request
No warning.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
This property was never defined, nor documented, so I wouldn't count it as public API, therefore no BC break.

It was added as a property just for the sake of micro optimization and was before in the internal storage of the app, see my linked commit. So we are going basically back to where we were at the beginning.

**Comment by joomdonation** [comment]
> This property was never defined, nor documented, so I wouldn't count it as public API, therefore no BC break

I'm unsure about this, so I won't record my test result, sorry. Even if that's accepted, why do we have to use the `isset` command in the code below on both files modified in this PR? That never returns true if the property is not defined.

```php
if (isset($app->JComponentTitle)) {
       
}
```

**Comment by laoneo** [comment]
Because it is a hack, you should not define a custom property in a class which doesn't support it. So I'm glad PHP 8.2 did report it. Because this is an abuse and is bad code practice, I would remove it completely, but you never know what for apps do exist into the wild, so I'm leaving.

I would even go that far and deprecated it then in 4.3 and remove in 6.0.

**Comment by HLeithner** [comment]
I found this on github

https://github.com/valeriekebz/WebsiteKEBS/blob/bc01497de0e49e3fe89a2b7b7c7af4a9159e450c/administrator/components/com_breezingforms/breezingforms.php#L58-L62

if this is normal for breezingforms I would expect we break this component right?

**Comment by HLeithner** [comment]
here is another one:
https://github.com/hooNam/Solidres/blob/8b21829e18284680732a66c3e6cf0dbcde4e0b49/com_solidres/frontend/com_solidres/helpers/toolbar.php#L37-L39

adding this variable to WebApplication and deprecate it with j4.3 and remove it in 6 would be ok, but we need a bzw. layer for it right?

Also I would go more specific with an own `g/setTitle()` function in the WebApplication instead of a generic set/get.

Or maybe moving this variable to the htmldocument? would this make more sense?

**Comment by laoneo** [comment]
> I found this on github
> 
> https://github.com/valeriekebz/WebsiteKEBS/blob/bc01497de0e49e3fe89a2b7b7c7af4a9159e450c/administrator/components/com_breezingforms/breezingforms.php#L58-L62
> 
> if this is normal for breezingforms I would expect we break this component right?

Nope, because breezing forms is defining that variable (will also result in a deprecate warning) which then takes precedence [here](https://github.com/joomla/joomla-cms/pull/39592/files#diff-7fd37d9e2fd166e585a857f7956a0f120c218d1607e8bf8cc7d1f3d2776a4841R18) over the value from the app data store.

The same applies for solidres. So from BC perspective we are covered, except when a module is using that variable only with core. Then it is not available, but again this is undocumented and not even close to a public API.

> Also I would go more specific with an own g/setTitle() function in the WebApplication instead of a generic set/get.

This is not the title of the application, it is really only a html string which gets then printed in the title module. So for now I think the closest would probably be the toolbar itself.

**Comment by laoneo** [comment]
Changed my mind and just added the missing property to the WebApplication class. Once upmerged to 4.3 we can then deprecate it.

@joomdonation and @carlitorweb would you mind to give it a test?

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 9dee2a2fd1959bc5289e3a97fa0c8ee3e111894f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39592">issues.joomla.org/tracker/joomla-cms/39592</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 9dee2a2fd1959bc5289e3a97fa0c8ee3e111894f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39592">issues.joomla.org/tracker/joomla-cms/39592</a>.</sub>

**Comment by joomdonation** [comment]
RTC. Thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39592">issues.joomla.org/tracker/joomla-cms/39592</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
