### PR TITLE
[4.1] codemirror update

### PR DESCRIPTION
**Pull request by brianteeman**
## Changelog
5.65.1 Fix miscalculation of vertical positions in lines that have both line widgets and replaced newlines.

5.65.0
Bug fixes
brace-folding addon: Fix broken folding on lines with both braces and square brackets.

New features
vim bindings: Support g0, g$, g.

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on a41487dd0fe2c044c9f48ee217394f8d25faf956<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36812">issues.joomla.org/tracker/joomla-cms/36812</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on a41487dd0fe2c044c9f48ee217394f8d25faf956<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36812">issues.joomla.org/tracker/joomla-cms/36812</a>.</sub>

**Comment by brianteeman** [comment]
So good you tested it twice ;)

**Comment by RickR2H** [comment]
Wouw a second test in 2 seconds! I guess I love your PR's :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36812">issues.joomla.org/tracker/joomla-cms/36812</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a41487dd0fe2c044c9f48ee217394f8d25faf956<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36812">issues.joomla.org/tracker/joomla-cms/36812</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36812">issues.joomla.org/tracker/joomla-cms/36812</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
