### PR TITLE
[4.1] add target and rel values in com_installer.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

add target=_blank and rel=noopener noreferrer for external links

### Testing Instructions

Clicking on the links opens the target in a new window and "noopener noreferrer" is passed as rel values.

### Actual result BEFORE applying this Pull Request

A link does not open in a new window.
Both links have no rel values.

### Expected result AFTER applying this Pull Request

`target=\"_blank\" rel=\"noopener noreferrer\"` for external links

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
originally we did not add rel= to these links as it was felt that we could trut our own web sites

**Comment by tecpromotion** [comment]
> originally we did not add rel= to these links as it was felt that we could trut our own web sites

There are currently 11 links to https://docs.joomla.org in use like this.
I would be happy if we could standardise this.

**Comment by simbus82** [comment]
> originally we did not add rel= to these links as it was felt that we could trut our own web sites

Anyway It's a best practice to use Noopener for linking external sites. The "noopener" attribute ensures that the page opened in a new tab cannot take control of the original page (Reverse Tabnabbing attack). It is useful for both safety and performance and you never know what can happen...
I have some doubts about the use of the noreferrer, in fact the only effect is that the analytics of the joomla sites would see direct traffic instead of referral traffic.
Using it maybe allows us to say that Joomla.org does not read any data from the Joomla installed (without the noreferrer if I click on those links, the Joomla.org analytics sees my domain inside the referrer).

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 302fe4d2106786e8c28f20081b5104af332a0a22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37475">issues.joomla.org/tracker/joomla-cms/37475</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 302fe4d2106786e8c28f20081b5104af332a0a22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37475">issues.joomla.org/tracker/joomla-cms/37475</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 302fe4d2106786e8c28f20081b5104af332a0a22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37475">issues.joomla.org/tracker/joomla-cms/37475</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37475">issues.joomla.org/tracker/joomla-cms/37475</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
