### PR TITLE
[com_content] Filter by no author

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes
This sets up site Articles model to allow filtering articles by no author, like in administrator.
### Testing Instructions
Create an article without author.
Modify 'Articles - Category' module form (/modules/mod_articles_category/mod_articles_category.xml) by adding option with value 0 to created_by field. So the field looks like this:
```
<field
	name="created_by"
	type="sql"
	label="MOD_ARTICLES_CATEGORY_FIELD_AUTHOR_LABEL"
	description="MOD_ARTICLES_CATEGORY_FIELD_AUTHOR_DESC"
	multiple="true"
	size="5"
	query="select id, name, username from #__users where id IN (select distinct(created_by) from #__content) order by name ASC"
	key_field="id"
	value_field="name"
	>
	<option value="">JOPTION_SELECT_AUTHORS</option>
	<option value="0">JNONE</option>
</field>
```
Publish the module. In author field try these combinations:
a) No option
b) Option with empty value
c) Option with 0 value
d) Option with empty value and option with 0 value
e) Option with empty value and option with >= 1 value (e.g. author with ID 50)
f) Option with 0 value and option with >= 1 value (e.g. author with ID 50)
### Expected result
a) All articles are shown
b) All articles are shown
c) Only articles without author are shown
d) Only articles without author are shown
e) Only articles from selected author (e.g. author with ID 50) are shown
f) Articles from selected author (e.g. author with ID 50) and without author are shown

### Actual result
a) All articles are shown (correct)
b) All articles are shown (correct)
c) All articles are shown (incorrect)
d) Only articles without author are shown (correct)
e) Articles from selected author (e.g. author with ID 50) and without author are shown (incorrect)
f) Articles from selected author (e.g. author with ID 50) and without author are shown (correct)

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by Septdir** [comment]
@SharkyKZ were change in `xml` files ? And why is it needed in fornt?

In `adminstrator/com_content/views/articles` this would be a very useful filter

**Comment by SharkyKZ** [comment]
This PR doesn't include any changes in XML.

Editing XML is needed to test the code, in which case the file is /modules/mod_articles_category/mod_articles_category.xml.

**Comment by Septdir** [comment]
@SharkyKZ then what is needed for this pr, and in the font model?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d543bebe3b4eea91c5b4c5f0797654583914cbbe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20245">issues.joomla.org/tracker/joomla-cms/20245</a>.</sub>

**Comment by SharkyKZ** [comment]
@Septdir this is a fix to allow the same functionality in frontend as in backend. It's not used in the core yet.

**Comment by infograf768** [comment]
@SharkyKZ 
I guess you can modify the xml by also adding to
`<option value="0">JNONE</option>`
a default value.
`default=""`
as that would be totally B/C.

**Comment by SharkyKZ** [comment]
@infograf768 You could do that, yes. But this PR doesn't touch XML. Editing XML is only needed to test the code. And note that option with empty value is for cosmetic reasons only. The existence of this option caused another issue, which is solved in this PR:

If you select an author (e.g. ID 50) and leave the default option selected, the value passed to model is `array('', '50')`. Using `ArrayHelper::toInteger()` results in `array(0, 50)` which means articles without author (where author ID is 0) will be included alongside articles from author with ID 50.

I'll update testing instructions with option combinations.

EDIT: Whoops, wrong button.

**Comment by infograf768** [comment]
OK. I guess using the author field instead would be a better solution.
But that is already in your other PR.

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on d543bebe3b4eea91c5b4c5f0797654583914cbbe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20245">issues.joomla.org/tracker/joomla-cms/20245</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20245">issues.joomla.org/tracker/joomla-cms/20245</a>.</sub>

**Pull request merged**
