### PR TITLE
[4.1] Schedule Tasks notification dates

### PR DESCRIPTION
**Pull request by brianteeman**
Change to use DATE_FORMAT_LC instead of RFC822 to enable translated dates in the notification emails.

## To test 
make sure that your test site will send emails
Create a scheduled task and set the notification for task success to enabled
Install russian language and set to default for admin
Go to the list of scheduled tasks and perform a test run of the scheduled task.

### Before PR
The email will look similar to
> Задача #3, checking images, успешно выполнена Fri, 15 Apr 2022 08:54:34 +0000.

### After PR
The email will look similar to
> Задача #3, checking images, успешно выполнена Пятница, 15 апреля 2022, 09:09.

Pull Request for Issue #36522 .

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 36dc0ff5ffaecf9e57d0c935bcbd45f1187c2251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37556">issues.joomla.org/tracker/joomla-cms/37556</a>.</sub>

**Comment by ditsuke** [comment]
I have tested this item :white_check_mark: successfully on 36dc0ff5ffaecf9e57d0c935bcbd45f1187c2251<br /><br />Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37556">issues.joomla.org/tracker/joomla-cms/37556</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37556">issues.joomla.org/tracker/joomla-cms/37556</a>.</sub>

**Comment by richard67** [comment]
Thanks all.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
