### PR TITLE
Email form field using JLayout

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Separate logic/ output

Base work for better templating
#### Summary of Changes

Introduce a  layout for this field
#### Testing Instructions

Apply patch and rename any backend input to email
eg

``` XML
<field name="mytextvalue" type="emil" default="Some text" label="Enter some text" description="" />
```

Also consult: https://docs.joomla.org/Standard_form_field_types

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 0656f2d277d6457be09875d2e5c338903fb87072<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11009">issues.joomla.org/joomla-cms/11009</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0656f2d277d6457be09875d2e5c338903fb87072<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11009">issues.joomla.org/joomla-cms/11009</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11009">issues.joomla.org/joomla-cms/11009</a>.</sub>

**Comment by wilsonge** [comment]
Merged with b495656 - thanks!

**Pull request closed without merging**
