### PR TITLE
[4.0] Fix category list uses popovers in table header in category list 

### PR DESCRIPTION
**Pull request by AJAY007L**
Pull Request for Issue #35467.

### Summary of Changes
        Removed popovers on the 'title' in Category list.        

### Testing Instructions
        Head over to http://localhost/joomla-cms/index.php/article-category-list after installing sample data.

### Actual result BEFORE applying this Pull Request
       
      
131897635-fbc014c6-d871-4458-913e-3b7dfee86a75

### Expected result AFTER applying this Pull Request
        
WhatsApp Image 2021-12-05 at 16 22 59

### Documentation Changes Required
       none.

### CODE REVIEW

**Comment by chmst** [comment]
@AJAY007L thanks for your contribution and working on that issue. 
But we don't use titles in headers as you can see in backend overviews. Users see already the headline (or hear it if they are blind). The purpose if the information is: Say the user that he can order the table with a click on the link. In a way which is a11y (popovers are not). 

So adding a title is not the right solution here. If you like to work on this - try understanding tooltips ;)

**Comment by AJAY007L** [comment]
Now, I understood what you want to say. @chmst Thanks for the reply.

**Comment by AJAY007L** [comment]
@chmst I made some changes in the code . Now, People can see or hear the link functionality of sorting the column.

***After change in code
https://user-images.githubusercontent.com/60544908/144995602-3bd3f459-0e1e-49fa-8d98-01af6a8d151a.mp4

**Comment by ceford** [comment]
It works but is it the right solution? Should the Tooltip be there at all? Sighted users just have to know that clicking a heading will sort by that column?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36202">issues.joomla.org/tracker/joomla-cms/36202</a>.</sub>

**Comment by AJAY007L** [comment]
Sir, I removed the tooltip and the rest is the same. 

**After Change in code**

https://user-images.githubusercontent.com/60544908/145024068-ff5de32b-a77b-458e-8fd0-7d323fa6604c.mp4

**Comment by richard67** [comment]
@AJAY007L Could you fix the code style errors reported here? https://ci.joomla.org/joomla/joomla-cms/49027/1/6
Thanks in advance.

**Comment by Quy** [comment]
Please read #33107 as this is not the correct fix.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e50bc9b1bb49a6ee6b925d2fc0ff7b4fc51390fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36202">issues.joomla.org/tracker/joomla-cms/36202</a>.</sub>

**Comment by brianteeman** [comment]
1. Document has multiple elements referenced with ARIA with the same id attribute: desc
2. Hardcoded language string
3. Unused data-bs-content

**Comment by AJAY007L** [comment]
@brianteeman, I 
1. changed ARIA id attribute to 'headingDesc'.
2.  removed the hard-coded string and use 'JGLOBAL_CLICK_THIS_LINK_TO_SORT_THE_TABLE' which I defined in language/en-GB/joomla.ini.
3. removed Unused data-bs-content.

**Comment by brianteeman** [comment]
> Please read #33107 as this is not the correct fix.

Also there is no need for a new string as we already have JGLOBAL_CLICK_TO_SORT_THIS_COLUMN

**Comment by brianteeman** [comment]
This should be closed as an abandoned pr AND completely the wrong approach as already detailed

**Pull request closed without merging**
