### PR TITLE
Subforms within subform rows will initialize themselves when new rows…

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes

Subform repeatable has a function `fixScripts` which calls a few js initialization functions on a few of the field types that require it. There is a now a better way to handle that kind of thing by having any field that may need initialization listen for an event fired by subform repeatable. In this PR, I am transferring responsibility of one such initialization from subform repeatable to the correct field type itself. 

Note: this PR doesn't really fix anything. Nest subforms already work with repeatable subforms. This just does it in a somewhat better way. 

### Testing Instructions

Set up a subform containing a subform. There's a subform in the redirect plugin that's simple to use for this purpose. 

Open up the form and create new rows. The subform in each new row should function properly. 

### Expected result

Nested subforms function normally.

### Actual result

Nested subforms function normally.

### Documentation Changes Required

None

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6e6290af2541958b2288f5ea2a822097a4adb4d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24919">issues.joomla.org/tracker/joomla-cms/24919</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6e6290af2541958b2288f5ea2a822097a4adb4d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24919">issues.joomla.org/tracker/joomla-cms/24919</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24919">issues.joomla.org/tracker/joomla-cms/24919</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
