### PR TITLE
[4.0] Replace inline style 5% with w-5

### PR DESCRIPTION
**Pull request by Quy**
Continuation of PR #28692

### Summary of Changes
Replace inline style 5% with w-5

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 02b6b831fa093152158b8e2a3c2feba9b3980244<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28905">issues.joomla.org/tracker/joomla-cms/28905</a>.</sub>

**Comment by infograf768** [comment]
Please solve conflicts

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 02b6b831fa093152158b8e2a3c2feba9b3980244<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28905">issues.joomla.org/tracker/joomla-cms/28905</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28905">issues.joomla.org/tracker/joomla-cms/28905</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
