### PR TITLE
change wrong language string for custom field editor - option hide buttons

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/15159
https://github.com/joomla/joomla-cms/issues/15159

### Summary of Changes
I changed only two wrong language strings

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f068fd3694904b3f6f70318d605cb355b6aa5ebe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15164">issues.joomla.org/tracker/joomla-cms/15164</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f068fd3694904b3f6f70318d605cb355b6aa5ebe<br /><br />After PR "Select some Options" is shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15164">issues.joomla.org/tracker/joomla-cms/15164</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by AlexRed** [comment]
sorry but I don't understand. Why a parameter to "Hide Buttons" when no plugin Buttons are show in the editor Field by default ?

**Comment by astridx** [comment]
@AlexRed 
In my installation per defautl all buttons are shown. An with this option I can hide special buttons for the field.

**Comment by AlexRed** [comment]
In Joomla! 3.7.0-RC1 and in the stagin not buttons are shown per default for me
no-plugin-editor

**Comment by AlexRed** [comment]
non sense use the "read more" in a editor in the contact mail form

**Comment by AlexRed** [comment]
sorry...  my error, I don't see the "Show Buttons"  :(
maybe the " Hide Buttons" parameter need to be visible only if the "Show Buttons" is set to yes

**Comment by infograf768** [comment]
> non sense use the "read more" in a editor in the contact mail form

That one is weird indeed as other editors-xtd will not show even if none is set to hide and  Show Buttons is set to Yes.
@laoneo Can you look into that precise aspect?

**Comment by infograf768** [comment]
I suggest to improve the editor xml field by adding
`showon="buttons:1"` in the `hide` field in both editor.xml

Can't make PR now as this PR has first to be merged, or the showon added here.

**Comment by astridx** [comment]
@infograf768 
I want to do your suggestion. But I wonder how we can handle the "show global" or "use from plugin" option?

**Comment by infograf768** [comment]
@astridx 
`showon="buttons:1"` will display the `hide` field ONLY when `buttons` are set to Yes (value=1). 
If one choses `Use from Plugin`, we shall not and cannot Hide anything for the field itself as the settings comes from the plugin settings.

In the case of the plugin settings, If `Show Buttons` is set to No, then no need to use the `Hide` field.

Does this clarifies?

**Comment by infograf768** [comment]
Just spoke with @Bakual and tested:
In fact `Use from Plugin` does not even work here, which means that we do have a bug.

**Comment by infograf768** [comment]
GRRR.... Issues.joomla.org playing on me...

This is RTC and for 3.7.0

Let's discuss elsewhere of the showin and Use Plugin Param.

**Pull request merged**
