### PR TITLE
[4.0] Fix wrong ConfigModel class

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR fixs the broken model class

### Testing Instructions
Submit an article over the frontend while you're a non-Super User and have the message plugin active

### Expected result
Article saved, email sent

### Actual result
Exception, because the model class is wrong.

### CODE REVIEW

**Comment by ghost** [comment]
@bembelimen is there an open Issue reported for broken model class?

**Comment by bembelimen** [comment]
Hi,
Is there one required?



-------- Ursprüngliche Nachricht --------Von: Franz Wohlkönig <notifications@github.com> Datum: 15.01.18  08:01  (GMT+01:00) An: joomla/joomla-cms <joomla-cms@noreply.github.com> Cc: Benjamin Trenkle <bembelimen@web.de>, Mention <mention@noreply.github.com> Betreff: Re: [joomla/joomla-cms] [4.0] Fix wrong ConfigModel class (#19380) 
@bembelimen is there an open Issue reported for broken model class?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joomla/joomla-cms","title":"joomla/joomla-cms","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/joomla/joomla-cms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@franz-wohlkoenig in #19380: @bembelimen is there an open Issue reported for broken model class?"}],"action":{"name":"View Pull Request","url":"https://github.com/joomla/joomla-cms/pull/19380#issuecomment-357597920"}}}

**Comment by ghost** [comment]
not required.

I asked to close Issue if its open.

**Comment by bembelimen** [comment]
I don't know, I did not create one.

**Comment by ghost** [comment]
Thanks for Info, will search for an open Issue.

**Comment by ghost** [comment]
@bembelimen can you please have a Look at #17812 #8582 if both report other Issue?

**Comment by bembelimen** [comment]
Yep, that are other issues

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
