### PR TITLE
Allow using underscore character in permission name

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #9645 .
#### Summary of Changes

This PR fix an issue causes by some changes in saving permissions in Joomla 3.5.0. In older version of Joomla, we are allowed to use underscore character in permission name. From 3.5.0, if we use underscore character, the permission won't be saved properly. Please see https://github.com/joomla/joomla-cms/issues/9645 to understand the issue
#### Testing Instructions
1. Open the file administrator/components/com_content/access.xml
2. Add a new permission which has underscore character (for example content.view_content) to component section. Example: `<action name="content.view_content" title="View Content" description="Allows viewing articles" />`
3. Go to System -> Global Configuration, select Articles component, Permissions tab (http://localhost/joomla35/administrator/index.php?option=com_config&view=component&component=com_content).
4. Try to change permission for View Content permission
5. Before this patch, you could not change setting for the new permission you just added
6. After this patch, the change you made for the  new permission can be saved
7. Try to change other permission and make sure it is saved properly

Hopefully, this issue can be fixed and go to 3.5.1

### CODE REVIEW

**Comment by brianteeman** [comment]
Testers dont forget to clear your browser cache after applying this Pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9648">issues.joomla.org/joomla-cms/9648</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8eb95776354e01435219b6b3b155b6eb63a91829<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9648">issues.joomla.org/joomla-cms/9648</a>.</sub>

**Comment by joomdonation** [comment]
Thanks @brianteeman for confirming the issue and testing the PR. I updated the PR with clear instruction so that testers won't have to look at the issue for testing instruction

Could we please have one more tester so that this one can be merged? It would be nice to have this fixed in Joomla 3.5.1

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 8eb95776354e01435219b6b3b155b6eb63a91829<br /><br />Able to reproduce and #9648 works as described as now the changes for permission are well saved.
Also thanks for the step by step testing instructions.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9648">issues.joomla.org/joomla-cms/9648</a>.</sub>

**Comment by joomdonation** [comment]
Thanks @MATsxm.

**Comment by brianteeman** [comment]
It's unfortunately too late for 3.5.1

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9648">issues.joomla.org/joomla-cms/9648</a>.</sub>

**Comment by joomdonation** [comment]
OK. I was hoping it could go into 3.5.1. However, as this PR is RTC now, I think I can  ship these modified files with my extensions and overwrite the old files on my customer's websites

Thanks again.

**Pull request merged**
