### PR TITLE
Replace JPATH_PLATFORM with _JEXEC

### PR DESCRIPTION
**Pull request by laoneo**
Replaces JPATH_PLATFORM with _JEXEC as JPATH_PLATFORM. Like that we have one way to check if the CMS is loaded correctly.

### CODE REVIEW

**Comment by sandewt** [comment]
What to do with this? Consequences? Depreceated?

https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/cms.php#L22

https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/cms.php#L28

https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/import.legacy.php#L21

https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/import.php#L21

**Comment by brianteeman** [comment]
Surely this is a breaking change

**Comment by laoneo** [comment]
What does break?

**Comment by laoneo** [comment]
> What to do with this? Consequences? Depreceated?
> 
> https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/cms.php#L22
> 
> https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/cms.php#L28
> 
> https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/import.legacy.php#L21
> 
> https://github.com/joomla/joomla-cms/blob/a5173837b150219affffeed036044bbaed5318f8/libraries/import.php#L21

These must stay for backwards compatibility.

**Comment by brianteeman** [comment]
> What does break? Happy to solve any bc issues.

Any tool that people have written to check for the presence of the check will fail.

**Comment by laoneo** [comment]
The check should still work as the defines are still in place. @sandewt pointed them out in his last comment. Only the occurrences in the CMS code are changed.

**Comment by brianteeman** [comment]
> The check should still work as the defines are still in place. @sandewt pointed them out in his last comment. Only the occurrences in the CMS code are changed.

it is those occurences I am referring to. 

this is a disruptive change for zero benefit and should definitely not be made in a minor release

**Comment by laoneo** [comment]
So you agree that it is not a bc break?

**Comment by wilsonge** [comment]
This was proposed in the past and we agreed things in the libraries folder was a b/c break because there were concrete examples of cli apps (in the j3 format) even on our own joomla.org sites defining JPATH_PLATFORM instead of JEXEC.

So yes it's a b/c break. You should be fine with the changes in the administrator folder however.

**Comment by sandewt** [comment]
See, also for completeness:

https://github.com/joomla/joomla-cms/pull/39535#discussion_r1156934002

https://github.com/joomla/joomla-cms/pull/40337#discussion_r1160466781

**Comment by laoneo** [comment]
I can't really imagine how you can run joomla 4 without jexec so I wouldn't count this as break. But I do also have no issue to rebase to 5. For me is more important that we get rid of inconsistency.

**Comment by brianteeman** [comment]
> I can't really imagine how you can run joomla 4 without jexec so I wouldn't count this as break.

@wilsonge already said there are cli apps

**Comment by laoneo** [comment]
I did rebase this one #and made a deprecation pr for 4.4 #40366.

**Review by wilsonge — APPROVED** [review]
To be clear this is still technically a b/c break against what production agreed. However I thiink this is a good and positive change and should be merged anyhow.

**Comment by laoneo** [comment]
Is there something documented about this vote? I'm not aware of any discussion.

**Comment by wilsonge** [comment]
I've not been in the meetings since 4.0 finished (so 1.5 years now) but https://volunteers.joomla.org/departments/production/reports/1793-production-dept-meeting-minutes-august-23-2022 was the motion i understood to have been approved which is deprecation for two major versions before removal hence https://github.com/joomla/joomla-cms/pull/38657 being merged which was 99% of the originally intended 5.0 deprecations going back to 6.0

**Comment by laoneo** [comment]
You was talking before about that PLATFORM should not be deprecated issue. The 2 years policy I'm aware of.

**Comment by HLeithner** [comment]
@laoneo can you sync the branch and add a deprecation notice in joomla 4.4 for this /files#diff-af833392184ea677c8d50f3b09187a3602ecb4eaed7b35a622fbf2e96ff1d3e6 (defining the constant) please

**Comment by laoneo** [comment]
Did the sync, but not sure what you want for a notice where?

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
