### PR TITLE
[4.1] spelling corrent/current

### PR DESCRIPTION
**Pull request by brianteeman**
code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cc0ced87e51a3ee88e0b2b024bd31216e9adfd58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cc0ced87e51a3ee88e0b2b024bd31216e9adfd58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I misread the code and suggested the wrong correction.

I have now corrected the PR and the title

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5aed61af00b4fc8498c611fadc004f5df420ac00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5aed61af00b4fc8498c611fadc004f5df420ac00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38061">issues.joomla.org/tracker/joomla-cms/38061</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
