### PR TITLE
[4.0] Center status/date created headers

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Center status header to match with its td cell.

### Testing Instructions
Code review.
or
Go to Content > Articles
See Date Created header right-aligned vs. center-aligned in Featured Articles.
Go to Content > Featured Articles
See Status header left-aligned.

(Optional to better see the alignment issue in Smart Search) Install https://github.com/C-Lodder/joomla4-backend-template/releases
Go to System > Administrator Template Styles
Set Bettum the default.

Go to Components > Smart Search > Index
See Status header left-aligned.
Go to Components > Smart Search > Filters
See Status header left-aligned.

### Expected result
Table header/cell respectively should be center-aligned.

### CODE REVIEW

**Comment by brianteeman** [comment]
This is **only** for smart search.

**Comment by brianteeman** [comment]
Note that this _issue_ is present in more places than addressed here. For example the date in articles list is centered but the header is not.

**Comment by Quy** [comment]
Testing instructions updated. Ready for testing.

**Comment by astridx** [comment]
I tested this and saw a clear difference at a width of 5000 pixels. I made the changes manually in the code for the view articles and code review for the other two files.

centered
Articles test Administration

not centered
Articles test Administration(1)

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 177c44645725620bb2e2e0f8d5769a3a5cbd189c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29249">issues.joomla.org/tracker/joomla-cms/29249</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 177c44645725620bb2e2e0f8d5769a3a5cbd189c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29249">issues.joomla.org/tracker/joomla-cms/29249</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29249">issues.joomla.org/tracker/joomla-cms/29249</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
