### PR TITLE
[com_fields] Update fields.php

### PR DESCRIPTION
**Pull request by farzadtaheri**
Problem: com_fields category fields change event causing problem in Persian fa-IR.
with this change, all calendars fields with localized data type (like Jalali) are converted to standard date type and then submit form.

Pull Request for Issue #16628 .

Summary of Changes

replace line 333 and change this code:

element.form.submit();

to

Joomla.submitform('" . $section . ".reload', element.form);

Testing Instructions

1- make sure you have more than two category for articles(com_content)
2- make sure you have at least a field for articles with context: com_content.article in com_fields
3- change back-end language to Persian(fa-IR).
4- go to Content > Articles. in Persian language the path is: محتوا > مطالب
5- edit an article and change category field value to another one.

Expected result

before this change:
after change category field value all calendar fields value change to empty.

after change code and replace line 333 with new one:
don`t show any error and fully reload page after ajax call and old calendar field values are show correctly.

### CODE REVIEW

**Comment by infograf768** [comment]
@dgt41 
Please check this urgently as RC is tomorrow

**Comment by dgrammatiko** [comment]
@infograf768 it seems reasonable but I cannot test it at the moment

**Comment by laoneo** [comment]
I think you need to make sure that the core js file is loaded.

**Comment by brianteeman** [comment]
This was urgent in 2017 - has it been fixed elsewhere?

**Comment by farzadtaheri** [comment]
@brianteeman, unfortunately not yet!

**Comment by coolcat-creations** [comment]
Is this PR still to test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17859">issues.joomla.org/tracker/joomla-cms/17859</a>.</sub>

**Comment by farzadtaheri** [comment]
Do I have to do anything?

**Comment by Quy** [comment]
@farzadtaheri See your previous comment. https://github.com/joomla/joomla-cms/pull/17859#issuecomment-414188099

**Comment by farzadtaheri** [comment]
> 
> 
> @brianteeman, unfortunately not yet!



> 
> 
> @farzadtaheri See your previous comment. [#17859 (comment)](https://github.com/joomla/joomla-cms/pull/17859#issuecomment-414188099)

@Quy @brianteeman 
I just started with Github and my original language is not English
So I may be misunderstood
I wrote the PR, which I tested it by myself and it works perfectly and solves the issue.
Do I need to do anything else to merage this PR? please Guide Me.

**Comment by laoneo** [comment]
I'v posted it in the public testing glip group. Maybe we will get some testers.

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
Change looks fine for me.

**Comment by richard67** [comment]
@laoneo I've just tested this PR, but not really successful regarding the described issue.

Regardless if the PR is applied or not, and regardless is the backend language is Persian or English (GB), the published date changes when changing category of an article if the website time zone in Global Configuration is set to something else than UTC, and it doesn't change when the website time zone is UTC (without a time zone for the user set in all these cases).

This seems to be solved by PR #28596 instead (have to test that again with Persian backend language).

But this PR here seems to fix another issue: When the backend language is Persian and the PR is not applied and I change the category of an article, the toolbar and top menu bar disappear with the page reaload.
j3-error-no-toolbar-when-persian

When the PR is applied this doesn't happen. When backend language is English (GB), this also doesn't happen.

Can someone check and replicate my findings?

**Comment by richard67** [comment]
With both PRs #28596 and this one here applied together, all is fine with any website time zone and with any backend language.

**Comment by infograf768** [comment]
> Can someone check and replicate my findings?

I confirm.
The errror is
Screen Shot 2020-04-14 at 10 57 10

It is solved by this PR.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b81c275d4face0c03dc6c4ecd20e7062a9c4a36a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17859">issues.joomla.org/tracker/joomla-cms/17859</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b81c275d4face0c03dc6c4ecd20e7062a9c4a36a<br /><br />See my and @infograf768 's previous comments about details.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17859">issues.joomla.org/tracker/joomla-cms/17859</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17859">issues.joomla.org/tracker/joomla-cms/17859</a>.</sub>

**Comment by infograf768** [comment]
@HLeithner 
Let's merge this one please for 3.9.17

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
