### PR TITLE
[com_banners] Remove article link

### PR DESCRIPTION
**Pull request by brianteeman**
When creating a banner there is a wysiwyg editor for a description. This is **only** displayed in the admin so there is no need for the **insert-article** editor-xtd plugin to be loaded as it wont produce anything useful. This simple PR removes the "insert article" from the editor toolbar.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 774b45d7e0e37a0349a5a70deb647544866a5c38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11918">issues.joomla.org/joomla-cms/11918</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 774b45d7e0e37a0349a5a70deb647544866a5c38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11918">issues.joomla.org/joomla-cms/11918</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11918">issues.joomla.org/joomla-cms/11918</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
