### PR TITLE
Convert mod_stats to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the statistics module to service provider.

### Testing Instructions

1. Make sure you have site module mod_stats published
2. You should see module output on frontend

mod_stats

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 2d04b85a84539f8020cdd5d605dcc0f0c7d25496<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42781">issues.joomla.org/tracker/joomla-cms/42781</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 2e7ac4aa2ac9b922b1b6cdba4d6ca6e874b7c01a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42781">issues.joomla.org/tracker/joomla-cms/42781</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2e7ac4aa2ac9b922b1b6cdba4d6ca6e874b7c01a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42781">issues.joomla.org/tracker/joomla-cms/42781</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42781">issues.joomla.org/tracker/joomla-cms/42781</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also to testers @fgsw @viocassel

**Pull request merged**
