### PR TITLE
[4] admin - show association button  when supported

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #38837 .

### Summary of Changes
show association button only  when supported

### Testing Instructions
see #38837

### Actual result BEFORE applying this Pull Request
Extensions not supporting multilingual associations  like banner categorie etc , show button 'Associations'.

### Expected result AFTER applying this Pull Request
Extensions not supporting multilingual associations don't show button 'Associations'.

### Link to documentations
Please select:
- [X] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Please fix the code style errors reported by drone: https://ci.joomla.org/joomla/joomla-cms/58324/1/6 .

**Comment by Franzwohlkoenig** [comment]
> * [x]  No documentation changes for docs.joomla.org needed

The helpscreens need changes (sections 'screenshot', 'toolbar')
- [Banner-Category: Edit](https://docs.joomla.org/Help4.x:Banners:_New_or_Edit_Category)
- [User Notes-Category: Edit](https://docs.joomla.org/Help4.x:User_Notes:_New_or_Edit_Category)

**Comment by alikon** [comment]
when and if it will be merged we should change the helpscreen

**Comment by Franzwohlkoenig** [comment]
> when and if it will be merged we should change the helpscreen

Thanks for correct from "No documentation changes for docs.joomla.org needed" to "Documentation link for docs.joomla.org".

**Comment by Franzwohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7b1108b34d7df7cb532f0048a3f166900d4eacf0<br /><br />@alikon Thanks for solving the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38889">issues.joomla.org/tracker/joomla-cms/38889</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7b1108b34d7df7cb532f0048a3f166900d4eacf0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38889">issues.joomla.org/tracker/joomla-cms/38889</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38889">issues.joomla.org/tracker/joomla-cms/38889</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
