### PR TITLE
target="_blank" for all links on com_postinstall

### PR DESCRIPTION
**Pull request by jsubri**
All post-installation messages coming from joomla.org opens in a new window,  PLG_TWOFACTORAUTH_TOTP_POSTINSTALL_BODY open in a new window as well, unifying behaviour on com_postinstall.

### CODE REVIEW

**Comment by zero-24** [comment]
@jsubri thanks for that but github is not happy here. It think we have `merge conflicts` can you have a look into it?

Also IIRC we need to escape all `"` with `"_QQ_"`
So this
`target="_blank"`
need to changed to
`target="_QQ_"_blank"_QQ_"`

**Comment by brianteeman** [comment]
Just to confirm that we need to use _QQ_ for urls - they aren't needed in test but are still needed in urls<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5827">issues.joomla.org/joomla-cms/5827</a>.</sub>

**Comment by brianteeman** [comment]
QQ is no longer needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5827">issues.joomla.org/joomla-cms/5827</a>.</sub>

**Comment by jsubri** [comment]
Trying to resolve merge conflicts from github on windows

**Comment by zero-24** [comment]
>Trying to resolve merge conflicts from github on windows

:+1: If it don't work you can close here and open a new pull with the changes. Thanks

**Pull request closed without merging**
