### PR TITLE
Updated Email Update Notification Text

### PR DESCRIPTION
**Pull request by ghost**
### Summary of Changes
The text used in the update email notification message is not ideal. The tone of the message is not particularly friendly and there are too many unnecessary disclaimers and explanations. All of this takes focus away from the purpose of the notification, the focus needs to be on encouraging users to update and helping them update - as helping users keep their install updated is the intent of the feature.

A piece of user feedback we received says it all:
_“The language used in the email notice is atrocious. It comes off as angry and is far too much text for a simple notice that there's an update available.”_

A more detailed analysis and recommendations can be found in this document:
https://docs.google.com/document/d/18rLT1UruY3WdcXFBGY523DOJSX5uXjlYZjZjE6XzRSM/

### Testing Instructions
I'm not sure how to test this exactly, maybe someone can fill me in on a way to force the email to send from a testing installation so we can see.

### Expected result
The new text is below. It's more focused, much shorter and more helpful.

```
There is an updated version of Joomla! available for
[SITENAME] - [URL]

Joomla! version currently installed:        [CURVERSION]
Joomla! version available for installation: [NEWVERSION]

This email was automatically sent from your Joomla! website to notify you that a new version of Joomla! is available.

To install updates on your website please visit the following link:
[LINK]
If the URL is not a link, simply copy & paste it to your browser

This message is sent to [SITENAME] administrators by the Joomla! Update Notification system plugin and is intended to help you. Keeping your software up to date helps keep your website stay secure. It is recommended to install the update as soon as possible.

You can disable these update email notifications by disabling the Joomla! Update Notification system plugin, located in the Plugin Manager of your website administrator area:
Extensions - Plugins - System - Joomla! Update Notification

More information: 
System - Joomla! Update Notification: https://docs.joomla.org/J3.x:Plugin_Joomla_Update_Notification Updating Joomla!: https://docs.joomla.org/J3.x:Updating_Joomla_(Update_Method)

If you are not sure why you received this email contact your website administrator
If you have questions, you can visit the Joomla! Support Forum: https://forum.joomla.org/
```

### Documentation Changes Required
We should add a piece of documentation to link this email to, there is no documentation for this feature currently. It could be used to provide more useful links to other docs, like installation and update info, and the disclaimers if they are necessary.

### CODE REVIEW

**Comment by zero-24** [comment]
> I'm not sure how to test this exactly, maybe someone can fill me in on a way to force the email to send from a testing installation so we can see.

There are different ways. The easyiest should be the following:
- Install 3.6.4
- install the pachtester
- apply this patch
- go to /plugins/system/updatenotification/updatenotification.php#L13
- uncomment the commented line.
- this should send a mail on every page call in the frontend.

**Comment by infograf768** [comment]
In any case case there should be **no** return in the ini file as it may trick some localisation translating systems/ extensions.

**Comment by cpfeifer** [comment]
Sure, I'm simply keeping it readable until the text is finalized, it's easy enough to remove the white space. I'll try and test it and rework it today.

**Comment by franz-wohlkoenig** [comment]
@cpfeifer any News?

**Review by zero-24 — CHANGES_REQUESTED** [review]
Why did you delete the XML_DESCRIPTION string?

**Comment by cpfeifer** [comment]
> Why did you delete the XML_DESCRIPTION string?

Because it's in en-GB.plg_system_updatenotification.sys.ini along with the label tag. The string is only used once and the sys.ini renders it. I'm not sure why it's in both files but I might be missing something.

**Comment by cpfeifer** [comment]
@franz-wohlkoenig I need to add a piece of documentation and a help screen in docs for this plugin so I have a link in the email, then it's ready to test.

**Comment by cpfeifer** [comment]
@zero-24 I put it back in, all the plugin language files have the description at the bottom. I don't understand why exactly, but there seems to be a reason for it to be there.

**Comment by ot2sen** [comment]
@cpfeifer Isn´t it because the sys.ini description is fired on installation while the other show in plugin config, to allow for an optional different message on install?

**Comment by cpfeifer** [comment]
@ot2sen That sounds about right. My guess is it's related to the installation process somehow but I don't know for sure. It's the same in other files so it has to be there for a reason, I just never noticed that before.

I've still got some work to do on this and I'll fix it up.

**Comment by cpfeifer** [comment]
This is getting there. I'd like to get some feedback on the new text, the description has been updated with the most current version. I'm not 100% on it quite yet :)

I added a new jdocs page and included the new URL in the email: https://docs.joomla.org/J3.x:Plugin_Joomla_Update_Notification

We can put any necessary or additional information in the jdoc. Ideally the email text will be as light as possible while providing access to our community resources. Any feedback is appreciated.

**Comment by cpfeifer** [comment]
I've updated the text. I'm not having any luck testing this on my local machine for some reason, maybe someone else can check.

Text should read:

There is an updated version of Joomla! available for [SITENAME] - [URL]
Joomla! version currently installed: [CURVERSION] Joomla! version available for installation: [NEWVERSION]

Visit the following link to apply the update:
[LINK] If the URL is not a link, simply copy & paste it to your browser

--------------

This message is automatically sent to [SITENAME] administrators by the Joomla! Update Notification system plugin when a new version of Joomla! is available. It is recommended to apply this update as soon as possible. Keeping your website software current to helps your website stay secure.

You can disable these notifications by disabling the Joomla! Update Notification system plugin located in the Plugin Manager of your website administrator area: Extensions - Plugins - System - Joomla! Update Notification.

Additional Information:
System - Joomla! Update Notification: https://docs.joomla.org/J3.x:Plugin_Joomla_Update_Notification
Updating Joomla!: https://docs.joomla.org/J3.x:Updating_Joomla_(Update_Method)

--------------

If you are not sure why you received this email contact your website administrator or visit the Joomla! Support Forum for further assistance: https://forum.joomla.org/

**Comment by Quy** [comment]
`If the URL is not a link, simply copy & paste it to your browser`
Add period.

`Keeping your website software current to helps your website stay secure.`
Remove `to`.

`If you are not sure why you received this email`
Add comma.

**Comment by brianteeman** [comment]
This isnt a positive change as it removes the emphasis that the email is NOT being sent by Joomla but by your own web site. Furthermore the sentence "This message is automatically sent to [SITENAME] administrators by the Joomla! Update Notification system plugin when a new version of Joomla! is available" is completely ambiguous and uses terminology that a site owner may not understand and certainly is not clear that it is NOT being sent by joomla.org.

The current notice right at the top of the email "This email IS NOT sent by Joomla.org. It is sent automatically by your own site,\n[SITENAME]" was not something that was just imagined. It was the result of several years of modifications of an email sent to thousands of site owners by an extension. 

**_I dont care about the rest of the text but that sentence must stay right at the top and be absolutely clear that Joomla.org is not sending the email._**

**Comment by rdeutz** [comment]
@chrisdavenport one more for the en-GB team to discuss

**Comment by brianteeman** [comment]
I am closing this at this time as there are requested changes that have not been addressed and the en-gb team has not responded.

**Comment by sozzled** [comment]
I think it's a terrible pity that this discussion was shutdown and that the suggested changes were not considered.  I agree with @cpfeifer that the current text is too abrasive in its tone and it discourages productive participation on the forum.  I am well acquainted with the criticisms about the _System - Update Notification_ plugin and the tendency by many site owners to disable the plugin in preference to being notified about the existence of new releases.

I also think we should be encouraging more people to use the _System - Update Notification_ plugin instead of being "turned off" by the language being used.

I accept that this PR was sidelined from J! 3.8.0 because of a lack of feedback from the en-gb team but I would also request that the team revisit the matter, at least before the end of J! 3.8._x_.  Language matters.

**Comment by ghost** [comment]
reopened as stated above (last Paragraph).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13942">issues.joomla.org/tracker/joomla-cms/13942</a>.</sub>

**Comment by brianteeman** [comment]
three months later there has been no update so I am closing it once again

**Pull request closed without merging**
