### PR TITLE
Replace at feature in SessionManagerTest unit test

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #42528 .

### Summary of Changes

Remove the at() function because it is deprecated for phpunit10.

Site note: Can be discussed if the test has make sense in the past, here I only made it run. 

### Testing Instructions

run the unit test e.g. phpunit --testdox --filter SessionManagerTest

### Actual result BEFORE applying this Pull Request

deprecated messages for the test

### Expected result AFTER applying this Pull Request

no deprecated messages for the test

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
This does not resolve the reported issue. "phpunit it out of date and unsupported"

**Comment by rdeutz** [comment]
I want to do it in two steps, one to fix the test and when this is done update the phpunit version

**Comment by brianteeman** [comment]
thats perfect and expected but you shoujldnt have closed the issue until both are done

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
