### PR TITLE
[4.3] Media manager, refactor the session fallback

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Refactor the fallback code for the url/session initial path handling

### Testing Instructions
- test a url like (existing path) `/administrator/index.php?option=com_media&path=local-images:/banners`
- test a url like (not existing path) `/administrator/index.php?option=com_media&path=local-none:/banners`
- test a url like (not existing path) `/administrator/index.php?option=com_media&path=local-none:/noooooo`
- Open the browser console and edit the session value from something like: `{"selectedDirectory":"local-images:/banners","showInfoBar":false,"listView":"grid","gridSize":"md","search":"","sortBy":"name","sortDirection":"asc"}` to values matching the changes on the previous steps (eg `"selectedDirectory":"local-none:/banners"`, "selectedDirectory":"local-none:/noooooo") and check if the media manager loads without an error
- Apply all possible combos between the url and the session storage

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@laoneo could you review this one?

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on eb903829d5f503358fc9f99be6b74d23131f69e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40013">issues.joomla.org/tracker/joomla-cms/40013</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 239b06d44590ffccf76a1563eb69af086e787dc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40013">issues.joomla.org/tracker/joomla-cms/40013</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev. No new features will be merged into Joomla! 4.3 series. Joomla! 4.4 series is a bridge release to make migration from Joomla! 4 to 5 as smooth as possible.

**Comment by dgrammatiko** [comment]
@HLeithner this is a bug fix, nothing new introduced here, so it should be on 4.3

**Comment by HLeithner** [comment]
@Hackwar marked this as feature, my script filtered for the label and moved the pr.
@laoneo and @obuisard can you check and rebase if needed please

**Pull request merged**
