### PR TITLE
[4.3] Quick Icons link to content languages

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #40647 .

### Summary of Changes

link to content languages

### Testing Instructions

see #40647 

### Actual result BEFORE applying this Pull Request

 link to installed languages

### Expected result AFTER applying this Pull Request

link to content languages

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 21b34fbf831dd931541009fe8f25675d53d8a05c<br /><br />Tested successfully in Joomla 4.3.2-rc2-dev of 28 May.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40671">issues.joomla.org/tracker/joomla-cms/40671</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 21b34fbf831dd931541009fe8f25675d53d8a05c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40671">issues.joomla.org/tracker/joomla-cms/40671</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40671">issues.joomla.org/tracker/joomla-cms/40671</a>.</sub>

**Comment by obuisard** [comment]
Thanks Nicola @alikon for the PR 👍

**Pull request merged**
