### PR TITLE
Make sure $value parameter passed to JHtml::calendar method is valid

### PR DESCRIPTION
**Pull request by joomdonation**
This PR fixed the issue https://github.com/joomla/joomla-cms/issues/7846. It just add a check to make sure the value passed to JHtml::calendar method is valid. 

In case the value is invalid, instead of throwing exception at the moment, it will reset the value to be empty and prevent the error above from happening.
# Testing instructions

JHml::calendar is used in many places in Joomla core. To test this, you can try to edit an article, look at Publishing tab, make sure the calendar inputs such as Start Publishing, Created Date... stil display the correct value.

### CODE REVIEW

**Comment by Bakual** [comment]
Can you revert the changes with line indent?

**Comment by joomdonation** [comment]
Seems the line indent added by the editor I am using. I just removed it, should be OK now.

**Comment by Bakual** [comment]
Looks much better now, thanks!

**Comment by nicksavov** [comment]
I tested it and it works well for me. It resolves issue https://github.com/OSTraining/OSContent/issues/57

**Comment by nicksavov** [comment]
@htmgarcia also tested it and it resolved the issue for him.

**Comment by zero-24** [comment]
RTC based on tests thanks @nicksavov @htmgarcia and @joomdonation !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7849">issues.joomla.org/joomla-cms/7849</a>.</sub>

**Comment by ymsstudios** [comment]
Thanks guys I used your update and it worked great for me!

**Pull request merged**
