### PR TITLE
[Media] Remove allowed mime type for flash from new installs

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Remove allowed mime type for flash from new installs. Flash is dead but if you really need it you can add it by your self. Per default the core is more secure than 😄 

### Testing Instructions

- review
- install https://github.com/zero-24/joomla-cms/archive/remove_flash.zip
- confirm that flash is not anymore a allowed mime type.

### Expected result

flash is not anymore a allowed mime type.

### Actual result

flash is a allowed mime type.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by SniperSister** [comment]
+1 from the JSST - Flash is a long term security nightmare and works around several browser-level security measures, it should be disallowed by default!

**Comment by wilsonge** [comment]
@rdeutz for 3.7.0

**Comment by rdeutz** [comment]
@wilsonge 3.7.1: riding a long death horse a month or two longer doesn't make a difference. :-)

**Comment by Quy** [comment]
Should `x-shockwave-flash,application` be added to `upload_mime_illegal`?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 105d1c3915a68c099a61acb0cb068acdebd6ed3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15452">issues.joomla.org/tracker/joomla-cms/15452</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 105d1c3915a68c099a61acb0cb068acdebd6ed3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15452">issues.joomla.org/tracker/joomla-cms/15452</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
