### PR TITLE
Fix compatibility break in validation.js

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

As result of #39350 it become impossible to use validation over non `<form>` element.
Hovewer some extensions use this feature to validate form "per section".

### Testing Instructions
Apply patch. Run `npm install`
Open a form for "New article".
In Browser console, run 2 commands (one by one):
```javascript
document.formvalidator.isValid(window['item-form']);

document.formvalidator.isValid(window['item-form'].parentElement);
```

### Actual result BEFORE applying this Pull Request
First command executed, and you get a validation message.
Second command throws an error

### Expected result AFTER applying this Pull Request
Both commands works, and shows validation message

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 819f565929dbc50711b2c55736945ed1d346f29e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40230">issues.joomla.org/tracker/joomla-cms/40230</a>.</sub>

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 819f565929dbc50711b2c55736945ed1d346f29e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40230">issues.joomla.org/tracker/joomla-cms/40230</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40230">issues.joomla.org/tracker/joomla-cms/40230</a>.</sub>

**Comment by compojoom** [comment]
thanks for the fix @Fedik ! Will there be a 4.2.10 release with this fix?

**Comment by obuisard** [comment]
> thanks for the fix @Fedik ! Will there be a 4.2.10 release with this fix?

No, you will have to wait for 4.3, coming April, 18 :-)

**Pull request merged**
