### PR TITLE
Redo Isis flat repaint (Closes #11832)

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #11832 
### Summary of Changes

This is a rebased version of #11832 which looks broken against 3.7.x
### Testing Instructions

Same as #11832 -> Apply the patch and browse administration.
### Documentation Changes Required

None (screenshots maybe)
### Credits

The original creator is @ciar4n and many other see #11832

### CODE REVIEW

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on c7879c80071e8eb9c31dfa55b7b1bf630964ea92<br /><br />Everything looks good... thank you @zero-24 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12319">issues.joomla.org/tracker/joomla-cms/12319</a>.</sub>

**Comment by brianteeman** [comment]
Why is this a release blocker?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12319">issues.joomla.org/tracker/joomla-cms/12319</a>.</sub>

**Comment by zero-24** [comment]
Oops i have add the label by mistake :) it is removend now

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on c7879c80071e8eb9c31dfa55b7b1bf630964ea92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12319">issues.joomla.org/tracker/joomla-cms/12319</a>.</sub>

**Comment by zero-24** [comment]
Thanks! -> RTC

cc: @rdeutz <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12319">issues.joomla.org/tracker/joomla-cms/12319</a>.</sub>

**Comment by zero-24** [comment]
:heart:

**Comment by andrepereiradasilva** [comment]
just updated my 3.7.x branch and isis looks nice!

BTW, just a detail, is it possible to also remove the text shadows in the text of labels and also in the message system (Error, Warning, Notice, Message)
image
image

**Comment by zero-24** [comment]
@andrepereiradasilva can you open a new issue for that.? I'm sure @ciar4n or an other CSS person can do this :smile:

**Comment by andrepereiradasilva** [comment]
done https://github.com/joomla/joomla-cms/issues/12343

**Comment by zero-24** [comment]
:+1:

**Comment by ciar4n** [comment]
@zero-24 It looks like the original merge conflict was amended in just the template.css. Unfortunately recompiling the template.less reintroduces the conflict back in to the template.css?

**Comment by ciar4n** [comment]
Maybe not a conflict... just means there is a slight difference currently between the template.less and template.css


```
 .sidebar-nav .nav-list > li > a {
   color: #555;
   padding: 3px 25px;
-  margin-left: -25px;
-  margin-right: -25px;
+  margin-left: -26px;
+  margin-right: -26px;
 }
```

**Comment by ciar4n** [comment]
I was going to create a PR to fix #12343 .. I can just fix it in that?

**Comment by C-Lodder** [comment]
It needs to be `-26px` for both left and right.

**Comment by zero-24** [comment]
Thanks for spotting. Fixed with: https://github.com/joomla/joomla-cms/pull/12346

**Pull request merged**
