### PR TITLE
Fix query with nulldate

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31644 .

### Summary of Changes
Fix query for modify date

### Testing Instructions
see #31611 
You need some articles in a blog. 
Make a blog menuitem. choose article ordering "modified "

### Actual result BEFORE applying this Pull Request
sql error

### Expected result AFTER applying this Pull Request
Blog output without errors

### Documentation Changes Required
no

### CODE REVIEW

**Comment by frostmakk** [comment]
I have tested this item :white_check_mark: successfully on 90ce3aa8256e3d3d88fc645b4177432a6f298878<br /><br />Also tested with PHP 8.0 & MySQL 8.0.18
No errors. 
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31645">issues.joomla.org/tracker/joomla-cms/31645</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 90ce3aa8256e3d3d88fc645b4177432a6f298878<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31645">issues.joomla.org/tracker/joomla-cms/31645</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31645">issues.joomla.org/tracker/joomla-cms/31645</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
