### PR TITLE
[4.0] Remove renderfield.php from com_contact

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #34611 .

### Summary of Changes
Removed the file `components/com_contact/layouts/joomla/form/renderfield.php`
Added some parameters for the modal window.

### Testing Instructions

- Create a contact with contact form
- Activate the plugin "Content - Confirm Consent" and configure an article to be linked with.
- Go to the contact in frontend
- The field "Privacy Note" is a required field, you can't send the form without check in the box. But beside the label you will see the text "(optional)"
- Click on the link, a modal window will open
- Create a custom field of type radio for the contact form, set it as required, go to the form in frontend, you will see the text "(optional)" next to the label.

### Actual result BEFORE applying this Pull Request

grafik

### Expected result AFTER applying this Pull Request
No "optional" text on required fields
All fields are rendered correctly
Modal window is bigger and will match the size of the modals of the other plugins when #34537 get merged.

grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
This is the original PR where the layout was created https://github.com/joomla/joomla-cms/pull/8473

**Comment by chmst** [comment]
Looks really good. The only difference is, that the "(optional)" hint is no longer displayed if a field is not required.

**Comment by chmst** [comment]
If this can be deleted, then the language string COM_CONTACT_OPTIONAL="(optional)" can be removed too. As nowere else in Joomla a label "(optional)" is displayed, it seems ok to remove it also in the contact form. 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by ChristineWk** [comment]
The file `components/com_contact/layouts/joomla/form/renderfield.php` 
was not removed with the Prebuild Package either. 
Probably need to rename this one?

**Comment by chmst** [comment]
For deleting files from the package, they must be added to a script if I  understood this correctly. If you want to test already, you can remove (or rename) the file manually.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6cb2166ee1c49d2be9a86cff4c093eb0b3bd82a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by ChristineWk** [comment]
Thanks for you Info. File removed. Result:

screen shot 2021-06-26 at 14 23 33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by brianteeman** [comment]
You need to add the file to the list of files to be removed in `administrator\components\com_admin\script.php`

**Comment by drmenzelit** [comment]
Thank you for the info. I will make the changes soon.

**Comment by richard67** [comment]
> This is the wrong place. I know its hard to see in such a long list but they are grouped by release as wrong as ordered alphabetically

@brianteeman I guess you mean “as well as ordered alphabetically” and not “as wrong as ordered alphabetically”.

**Comment by brianteeman** [comment]
Autocorrect sucks

**Comment by richard67** [comment]
@drmenzelit I've allowed myself to move the file deletion in script.php to the right place for you.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3a42b50e60f1e79ee66bc40183cfa770e6353b45<br /><br />Test with Patchtester not possible.
Tested again with Prebuilt Package.
There was no need now, to remove the file `components/com_contact/layouts/joomla/form/renderfield.php.` manually.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by BertaOctech** [comment]
Hi,

I was following the testing instructions, using 4.0.0-rc3. but the problem you describe does not happen anymore.

Before applying the patch there was no "(optional)" close to required checkboxes.

So I did not test anything.  Not sure if this patch is needed anymore.

Cheers,

Berta
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by drmenzelit** [comment]
@BertaOctech the problem appears on required radio fields and on the Privacy Note

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on 3a42b50e60f1e79ee66bc40183cfa770e6353b45<br /><br />Thanks @drmenzelit

The privacy policy appeared correctly before applying the patch. I guess it was corrected elsewhere.

But I could see the problem for a required radio button.

"Optional" dissapeared when I applied the patch and renamed manually the file `components/com_contact/layouts/joomla/form/renderfield.php`. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34617">issues.joomla.org/tracker/joomla-cms/34617</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
