### PR TITLE
[4.0] Plugins Change status

### PR DESCRIPTION
**Pull request by brianteeman**
Correction to #23991

Plugins are enabled/disabled NOT published/unpublished

### After PR
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ac706231c05b880622a6491ac42f5edb014ce366<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23797">issues.joomla.org/tracker/joomla-cms/23797</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ac706231c05b880622a6491ac42f5edb014ce366<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23797">issues.joomla.org/tracker/joomla-cms/23797</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23797">issues.joomla.org/tracker/joomla-cms/23797</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
