### PR TITLE
Support inline subforms

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
This PR adds support for inline subforms. It will be possible to define the subform as XML content directly inside the main XML file. It will behave similar to repeatable forms. How it will look like can be found in the testing instructions.

If this PR will get merged, then we can move the custom fields list to subforms.

### Testing Instructions
Put the following XML code into the file administrator/components/com_content/models/forms/article.xml after line 162 (inside the basic fieldset in the attribs tag).

```
<field name="demo" type="subform" label="Subform" multiple="true">
	<form>
		<field name="name"
			label="Name"
			size="30" type="text" />

		<field name="value"
			label="Value"
			size="30" type="text" />
	</form>
</field>
```
### Expected result
In the options tab should appear a sub form like:
image

### Actual result
An error is show, that the form could not be loaded.

### CODE REVIEW

**Comment by laoneo** [comment]
Calling @Fedik does this change make sense?

**Comment by Fedik** [comment]
looks as good idea 😉 
but the main form ignores the fields inside subform field? I had some problem with this before, they was rendered as part of the main form

**Comment by laoneo** [comment]
Looks like we have then to change the XPath query then to look for fields which are not descendant of a field where the type is subform.

@Hackwar you was working recently on JForm for Joomla 4, can you help out on this?

**Comment by Fedik** [comment]
actually that was a main reason why I have used an external file as source, instead of the children elements 😉

**Comment by Hackwar** [comment]
Yes, I worked on JForm recently, but I don't really know anything about this here. Also, my changes are aimed at 4.0.

**Comment by Hackwar** [comment]
The corresponding PR would be #12414

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 4150a577fa963d45a723672783e0dbd14510fe01<br /><br />Thank you, works like expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12813">issues.joomla.org/tracker/joomla-cms/12813</a>.</sub>

**Comment by laoneo** [comment]
@Fedik I guess I solved with some updated XPath queries. The fields in the subform should not being rendered anymore in the main form and slo not overwrite some existing fields. Can you also do some testing as you are the subform master chief :wink: 

@coolcat-creations probably you need to test it again.

**Comment by laoneo** [comment]
@Fedik like my last commit?

**Comment by Fedik** [comment]
yes, something like that 😉 
I try to test when will get some more time

**Comment by Fedik** [comment]
works,
 but still some issue, when you do the subform with fieldsets, then main form rendered wrong:
screen 2016-11-19 18 01 05 752x312

I tried to test in module params.
```xml
<field name="demo" type="subform" label="Subform" multiple="true" groupByFieldset="true">
	<form>
		<fieldset name="test1" label="test1">
			<field name="name"  label="Name"  type="text" />
		</fieldset>
		<fieldset name="test2" label="test2">
			<field name="value"  label="Value" type="text" />
		</fieldset>
	</form>
</field>
```

**Comment by Fedik** [comment]
I think that the reason is the same as was with `<filed>` inside `<field>`

**Comment by laoneo** [comment]
@Fedik can you please test again as I should have fixed the fieldsets in fields issue. Thanks.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 9cbc7849e3058e25d18c74e6d227750743ccfc49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12813">issues.joomla.org/tracker/joomla-cms/12813</a>.</sub>

**Comment by Fedik** [comment]
I leave this for reference #12451 
will be need to check, after #12813 or #12451 will be merged

**Comment by laoneo** [comment]
@coolcat-creations can you also test it again, then we can set it to RTC and are able to use subforms for custom fields.

**Comment by ufuk-avcu** [comment]
I have tested this item :white_check_mark: successfully on 9cbc7849e3058e25d18c74e6d227750743ccfc49<br /><br />Works as expected. Thank you Allon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12813">issues.joomla.org/tracker/joomla-cms/12813</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12813">issues.joomla.org/tracker/joomla-cms/12813</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Comment by janstieler** [comment]
Hi,
sorry I don't understand how I can use this now in my articles?
Have I do a corehack for this or is this also usable with the custom fields?

**Pull request merged**
