### PR TITLE
[4.4] Fix unclear Text Message in All Menu Items area Batch Action process (Update com_menus.ini)

### PR DESCRIPTION
**Pull request by exlemor**
Pull Request for Issue #43214 
To make the Menu - All Menu Items screen batch message clearer/easier to understand and follow.

### Summary of Changes

Changed com_menus.ini text string to make it easier to understand action...

While testing Joomla 5.1.0. RC1 during/after the Release Testing meeting, I came across a not so easy to understand message...

I needed to test Batch operations in the Menus Area and I happen to click on All Menu Items...
There, I selected the 'Blog' menu entry (created for me when I installed the Sample Data set), then clicked on Actions --> Batch.

The explanation message (which feels like an error or at least a notice/warning etc yet is not in orange etc ) says:

**Batch process the selected menu items**
To use batch processing, please first select a Menu in the manager.

yet, that last line is confusing...

It should say:

To use batch processing, please first select the - Select Menu - entry in the dropdown menu above on this screen.

### Testing Instructions
Just that the string is updated.

Check if need be the video:
https://github.com/joomla/joomla-cms/assets/2597232/eba94446-f911-4020-9ac4-b763c54da513

### Actual result BEFORE applying this Pull Request
To use batch processing, please first select a Menu in the manager.

### Expected result AFTER applying this Pull Request
To use batch processing, please first select the - Select Menu - entry in the dropdown menu above on this screen.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct. You could also select a menu in the sidebar menu

**Comment by chmst** [comment]
In German the message is something like "Please select a Menu". 
I think this is better (when correct english). It is the users's choice where he wants to specify the menu, in the manager or in the filter bar.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 93650ad9a3e75230caba119cb4cb18f7b5cbad40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43215">issues.joomla.org/tracker/joomla-cms/43215</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 93650ad9a3e75230caba119cb4cb18f7b5cbad40<br /><br />Works as described: the text was different.

I don't understand what it means though, so to me it's still unclear. What do we want people do to here?

Something like this? 

To use batch processing, please first choose a specific menu from the dropdown on top of this screen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43215">issues.joomla.org/tracker/joomla-cms/43215</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 93650ad9a3e75230caba119cb4cb18f7b5cbad40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43215">issues.joomla.org/tracker/joomla-cms/43215</a>.</sub>

**Comment by richard67** [comment]
> This is not correct. You could also select a menu in the sidebar menu

What about this comment by @brianteeman ? I think he is right and the way described in the changed language string is not the only way to select a menu.

**Comment by crommie** [comment]
So what about: 

To use batch processing, please first choose a specific menu. Use the dropdown on top of this screen or the link in the sidebar menu.

**Comment by exlemor** [comment]
Hi Anja, thanks for your version (hug)

> So what about:
> 
> To use batch processing, please first choose a specific menu. Use the dropdown on top of this screen or the link in the sidebar menu.

I would be OK with that, I was trying to find the shortest language version and I did not have a problem with guiding users to 1 of 2 possible ways of doing it - but since it seems that this is not appreciated :), your version is good. 

the link in the sidebar menu part of your proposal is for me a bit too vague which link?

I wish it was more specific so as to remove any confusion or doubt - that's why I tried to be very specific in my 1 pointing to a specific version.  (hug)

**Comment by brianteeman** [comment]
Sometimes more is less understandable

**Comment by crommie** [comment]
True @brianteeman

**Comment by crommie** [comment]
So we're back to: Select a menu.

**Comment by richard67** [comment]
> So we're back to: Select a menu.

Maybe "Select a menu wherever you find some."? 😄

**Comment by exlemor** [comment]
And I am sorry to disagree with Brian ;) or be a pain - but it's not about more or fewer words it's about being clear, confusion free - after I was confused I had 2 unrelated regular users - 1 of which works occasionally with Joomla 4 and one that has worked with Joomla for 3 years pretty actively as a content editor and occasionally a bit more and they were also confused so the confusion is 'real' - which is why I was trying to either:

1. direct people to 1 working solution (if certain users know a second way of doing things great but I didn't have a problem with providing a clear 1 way to get the task done) or 

2. since that seems to be the consensus find a way to be clear as to both ways of getting it done.

(funny Richard ;) just saw your Maybe "Select a menu wherever you find some."? 😄 comment :p

**Comment by Quy** [comment]
Would it be better to just hide the Batch option under All Menu Items?

**Comment by chmst** [comment]
> Would it be better to just hide the Batch option under All Menu Items?

Nice idea.
I see already the issues coming "batch button missing in all menu items" :)

In the last days I stumbled upon this message several times. I don't remember why we need to select a menu at all? In categories, I can select all and then activate the batch button, no need to select a parent.

**Comment by brianteeman** [comment]
>  I don't remember why we need to select a menu at all?

Maybe it isnt needed any more

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/44286. If it works, we do not need this message

**Pull request closed without merging**
