### PR TITLE
[4.0] License.php

### PR DESCRIPTION
**Pull request by rjharishabh**
### Summary of Changes
There is both License.txt and License.php in ini files of plugins.
This PR removes the instances of License.php

### Testing Instructions
Code Review

### Documentation Changes Required
No

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 77d86395013faee113739dd7271de9f801d4a783<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34569">issues.joomla.org/tracker/joomla-cms/34569</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 77d86395013faee113739dd7271de9f801d4a783<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34569">issues.joomla.org/tracker/joomla-cms/34569</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34569">issues.joomla.org/tracker/joomla-cms/34569</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
