### PR TITLE
[5.0] Remove IE 11 warning message due to EOL

### PR DESCRIPTION
**Pull request by bembelimen**
See #37900 .

### Summary of Changes
This PR removed the "Warning! Internet Explorer should not be used for proper operation of the Administrator Backend." message completely from the backend.

### Testing Instructions
Code review or check the backend login with brocken CSS

### Actual result BEFORE applying this Pull Request
Message is displayed (also if CSS is broken)

### Expected result AFTER applying this Pull Request
No message ever

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/51
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by Hackwar — APPROVED** [review]
Did a codereview and looks good.

**Comment by zero-24** [comment]
Well even when IE11 is EOL its still used in the wild not sure whether it makes much sense to remove it now. J5 a few months from now would be where i would remove such a message as that is a major with possible also more changes on the backend template site etc.

**Review by drmenzelit — APPROVED** [review]

**Comment by brianteeman** [comment]
> Well even when IE11 is EOL its still used in the wild not sure whether it makes much sense to remove it now. J5 a few months from now would be where i would remove such a message as that is a major with possible also more changes on the backend template site etc.

+100

Nothing has changed in our code to justify removing the error message. Joomla admin still will not work with internet explorer but with this PR no one will know that the browser is the cause of the problems and will now think Joomla is broken.

Internet Explorer is still in use even if it is eol and a user should be told when they get an error.

Just because in the wealthy western web the usage of IE has dropped below 1% does not mean that it is true globally.

For example in Iran, where joomla is heavily used due to our almost unique, support for the jihali calendar ie usage is still over 8% https://gs.statcounter.com/browser-market-share/desktop/iran

There are many other countries where Joomla is actively used where the % is 5% or over.

**Comment by brianteeman** [comment]
As this has now been rebased to 5.0 please re-open and merge #37900

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
