### PR TITLE
[#34013] Fix add/remove selected attribute and class

### PR DESCRIPTION
**Pull request by itbra**
Currently the chosen.jquery plugin doesn't properly handle the adding/removing of the class `'result-selected'` and attribute `'selected="selected"'` when list elements are changed (single-select-list) or added/removed (multi-select-list). Its current implementation leaves the class `'result-selected'` attached to any previously selected list element thus making to handle the specific selected item by an onchange-handler impossible when trying to catch the selected element via its `'result-selected'` class.

The fix solves this issue and properly adds/removes the mentioned class and attribute to every involved element and allows to post-process exactly only the currently selected element(s) by an onchange-handler.

### CODE REVIEW

**Comment by ysavran** [comment]
I tested this fix by adding/removing elements of a list in "debug" plugin options. After fix, chosen.jquery plugin still behaves the same way. It successfully handles for the **first removal** of a list object. But if you try **adding and removing new ones**, result-selected class is not handled correctly. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4032">issues.joomla.org/joomla-cms/4032</a>.</sub>

**Comment by Blutengel89** [comment]
I have tested the patch, but adding/removing of new ones aren´t handled correctly. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4032">issues.joomla.org/joomla-cms/4032</a>.</sub>

**Comment by roland-d** [comment]
@itbra Can you please have a look at the unsuccessful test results? In addition fix the merge conflicts? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4032">issues.joomla.org/joomla-cms/4032</a>.</sub>

**Comment by roland-d** [comment]
Hello @spignataro 

Thank you for your contribution.

The last comment here was on August 21st. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4032">issues.joomla.org/joomla-cms/4032</a>.</sub>

**Comment by spignataro** [comment]
@roland-d - I think you might need some sleep. @itbra submitted the ticket - not me.

**Comment by roland-d** [comment]
@spignataro or a beer :) I must have been reading another ticket of yours. Indeed it's @itbra :)

**Comment by spignataro** [comment]
Have two one me!!!

Now back to ticket work. ;-)

**Comment by brianteeman** [comment]
I am closing this at this time as there have been no responses to the failed tests. It can always be reopened when resolved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4032">issues.joomla.org/joomla-cms/4032</a>.</sub>

**Pull request closed without merging**
