### PR TITLE
Correct jQuery submit trigger on form submit

### PR DESCRIPTION
**Pull request by dgrammatiko**
PR #3484 introduced the ability to bind jquery functionality on submit form event. The problem is that this doesn’t fire as expected as observed on #6207.
#### What is changed?

Instead of submit

``` javascript
        jQuery(form).submit();
```

it should be:

``` javascript
        jQuery(form).trigger("submit");
```
#### Test instructions:

Apply patch
Open /administrator/components/com_content/views/article/tmpl/edit.php
and insert

``` php
JFactory::getDocument()->addScriptDeclaration('
jQuery(document).ready(function() {
    jQuery("#item-form").bind("submit", function() {
        console.log("works");
    });
});
');
```

just before ? > at around line 75

Try to create (save) an article, you should get in browsers log `works`

OR follow [these](https://github.com/joomla/joomla-cms/issues/6207#issuecomment-86039978) instructions

### CODE REVIEW

**Comment by Fedik** [comment]
hm, this is very strange, as under the hood submit() and trigger("submit")  the same thing, [jQuery source](https://github.com/jquery/jquery/blob/master/src/event/alias.js)

**Comment by dgt41** [comment]
I think in core.js we pass the form object and trigger submit() and somehow things get messed up with a form id "adminForm" which is not always the case, or something like that was the logged stuff on my test! It’s really weird but I think it is down to the form selector and there the code gets confused and never fire any bind functionality. I hope that this comment makes some sense 🙊

**Comment by Fedik** [comment]
I think I know reason, problem not in submit() and trigger("submit"),
it just missed in minified version of the core.js file :smile:

**Comment by Fedik** [comment]
here you update the minified version and it works now,

so **test** good, thanks! :wink:

**Comment by Fedik** [comment]
betwen, I thought about something like this http://stackoverflow.com/a/18072246/1000711
in theory it should be more generic, and it allow to trigger html5(!!!) validation  :metal:

**Comment by Fedik** [comment]
another thought, about merging the javascript files, that have minified version,
would be a lot more safe to create the minified version  **after** merge, not before ... because something tell me that GIT cannot merge them good, if was used different tools for this

**Comment by dgt41** [comment]
@Fedik Thanks, yes the problem is not trigger or submit, I didn’t check the minified file
About vanilla script: bring it on, and I will close this one 😄
About minified script files: maybe something like generates.php that uses YUI and creates the relative compressed file will be nice!

**Comment by infograf768** [comment]
Tested in https://github.com/joomla/joomla-cms/issues/6207 and works fine.

**Comment by Fedik** [comment]
@dgt41  there it is #6587

**Comment by dgt41** [comment]
Please test #6587 as that is a FAR BETTER implementation! Thanks @Fedik

**Pull request closed without merging**
