### PR TITLE
[5.3] Calendar Strings

### PR DESCRIPTION
**Pull request by brianteeman**
Remove the special check for language strings introduced in 4.0. No longer needed and strings are used elsewhere without this extra check

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ca2afd15a902e8909b9abb88d709e07c19e60406<br /><br />The strings were introduced with PR #34870 , so I agree that there was enough time to adjust translations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44099">issues.joomla.org/tracker/joomla-cms/44099</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ca2afd15a902e8909b9abb88d709e07c19e60406<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44099">issues.joomla.org/tracker/joomla-cms/44099</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44099">issues.joomla.org/tracker/joomla-cms/44099</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
