### PR TITLE
[4.0] Fix Select sub-items selects all on Menu Assignment for module

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #31277.

### Summary of Changes
This PR fixes the issue https://github.com/joomla/joomla-cms/issues/31277. Please take a look at the the original issue to understand the issue which this PR tries to solve.

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/31277 , confirm the issue
2. Download update package for this PR at https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/33911/downloads/43758/Joomla_4.0.0-beta8-dev+pr.33911-Development-Update_Package.zip, go to System -> Update -> Joomla, upload the update package and install it. Then check and confirm the issue is sorted.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2d64f8a37eaa1ae9df3b35855c588cd145047433<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33911">issues.joomla.org/tracker/joomla-cms/33911</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2d64f8a37eaa1ae9df3b35855c588cd145047433<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33911">issues.joomla.org/tracker/joomla-cms/33911</a>.</sub>

**Comment by joomdonation** [comment]
Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33911">issues.joomla.org/tracker/joomla-cms/33911</a>.</sub>

**Comment by ChristineWk** [comment]
Thks to @ReLater and @joomdonation 
In the past I always believed that I made wrong selections :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33911">issues.joomla.org/tracker/joomla-cms/33911</a>.</sub>

**Comment by joomdonation** [comment]
I thought it is a complicated bug, turned out an easy fix :). Thanks again  !

**Comment by Quy** [comment]
Thank you!

**Comment by ghost** [comment]
As the bot removed RTC shouldn't it reassigne?

**Comment by joomdonation** [comment]
@sandramay0905 The PR was merged. So it is not needed.

**Pull request merged**
