### PR TITLE
Fix allowed chars in mailer subject

### PR DESCRIPTION
**Pull request by Denitz**
Pull Request for Issues #31768, #40571.

### Summary of Changes

Currently, email subject is validated as email address, hence it's impossible to send an email with a subject like `Test email for test@test.com {test}`

The problem is that email subject is incorrectly validated as email address since 2006, see https://github.com/joomla/joomla-cms/commit/dec892789c7d0bcd2893c731f43a1bd285f46d9f#diff-89c219c58287d02dd7de50360cf6656e7ab96bfd20ef065ef54db235ff12dea4R127

Current `MailHelper::cleanSubject()` was never used, we can use it.

### Testing Instructions

Send an email with subject `Test email for test@test.com {test}`

### Actual result BEFORE applying this Pull Request

See error

### Expected result AFTER applying this Pull Request

No errors

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on e8b28cff3586b6607b3b6531d1b2f8e27f91c6b7<br /><br />Tested this using mass mailer function and send an e-mail. after patch mail was sent succesfully. before it did not send e-mail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41138">issues.joomla.org/tracker/joomla-cms/41138</a>.</sub>

**Comment by rachelwalraven** [comment]
I have tested this item :white_check_mark: successfully on e8b28cff3586b6607b3b6531d1b2f8e27f91c6b7<br /><br />Jooma 4.3 dev with PHP 8.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41138">issues.joomla.org/tracker/joomla-cms/41138</a>.</sub>

**Comment by Magnytu2** [comment]
I have an error sending a message with or without special characters in the subject after applying the patch.
screen shot 2023-08-26 at 10 39 02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41138">issues.joomla.org/tracker/joomla-cms/41138</a>.</sub>

**Comment by richard67** [comment]
> I have an error sending a message with or without special characters in the subject after applying the patch. screen shot 2023-08-26 at 10 39 02

@Magnytu2 This error seems not to be related to the changes in this PR. On which version of Joomla have you tested?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41138">issues.joomla.org/tracker/joomla-cms/41138</a>.</sub>

**Comment by ChrisHoefliger** [comment]
I have tested this item :white_check_mark: successfully on e8b28cff3586b6607b3b6531d1b2f8e27f91c6b7<br /><br />Tested on localhost Joomla 4.3.4 @PBF 2023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41138">issues.joomla.org/tracker/joomla-cms/41138</a>.</sub>

**Comment by Magnytu2** [comment]
@richard67 test Joomla 5.0 Beta 1 - php 8.1.18 - 10.5.21 MariaDB.

**Comment by richard67** [comment]
> @richard67 test Joomla 5.0 Beta 1 - php 8.1.18 - 10.5.21 MariaDB.

@Magnytu2 This pull request here is for the 4.3-dev branch, sou you cannot test it on a 5.0-beta1-dev.

**Comment by obuisard** [comment]
Thank you @Denitz for the PR!

**Comment by Denitz** [comment]
@obuisard Thank you!

**Pull request merged**
