### PR TITLE
Users: Edit Profile - Assigned User Groups Tab: Generate valid id's for the Input Checkboxes (Error in Guided Tours #40054)

### PR DESCRIPTION
**Pull request by MacJoom**
### Summary of Changes

The HTML Helper for this tab generates id's that are not valid CSS Selectors - starting with a digit. This PR corrects this, thus enabling Guided Tours for this tab. 

### Testing Instructions

Go to Users:Edit Profile, test setting various Assigned User Groups

### Actual result BEFORE applying this Pull Request

Tab Works. Try making a Guided Tour which uses the User Groups Tab - Guided Tour breaks

### Expected result AFTER applying this Pull Request

Tab Works. Try making a Guided Tour which uses the User Groups Tab - Guided Tour works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
looks like you have added an unrelated file

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 50c45c8e74ec054a184be946dfcf3868f5b3afa0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40090">issues.joomla.org/tracker/joomla-cms/40090</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 50c45c8e74ec054a184be946dfcf3868f5b3afa0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40090">issues.joomla.org/tracker/joomla-cms/40090</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40090">issues.joomla.org/tracker/joomla-cms/40090</a>.</sub>

**Pull request merged**
