### PR TITLE
[3.9] Cache Plugin improvements (Replaces #8431)

### PR DESCRIPTION
**Pull request by mbabker**
Replacement Pull Request for PR #8431 

### Summary of Changes

Replaces PR #8431 after resolving merge conflicts.  See original PR for details.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
approve language changes

**Comment by rdeutz** [comment]
@mbabker any idea why the test on AppVeyor failed?

1) JCacheStorageCacheliteTest::testCacheTimeout
Some data should be available in lifetime.
Failed asserting that false matches expected 'testData'.
C:\projects\joomla-cms\tests\unit\core\case\cache.php:121
C:\projects\joomla-cms\tests\unit\suites\libraries\joomla\cache\storage\JCacheStorageCacheliteTest.php:67

**Comment by mbabker** [comment]
False positive, especially since the other two builds did pass.  Anyway I triggered a rebuild.

**Comment by zero-24** [comment]
@mbabker could it be that this result into an B/C change? Because `#`  is different in regex than `/` I'm notice this because the examples have been changed too. Or is this just me who knows nearly nothing about regex?

**Comment by mbabker** [comment]
You're asking the wrong person.  I branched the original PR, resolved merge conflicts, and opened a new one.

Likewise, plugins don't fall under the same B/C scrutiny as the core API.  Plus cache is flushed on an update.  So I'm not quite sure what the B/C concern here could be.

**Comment by zero-24** [comment]
Well my point is that it it looks like the old configuration value (`\/component\/users\/`) does not work anymore but i have no idea if that is true. I have just noticed that the description was changed so better safe than sorry.

**Pull request merged**
