### PR TITLE
[4.1] Discover extension strings

### PR DESCRIPTION
**Pull request by brianteeman**
Minor grammar changes. Code reviw only

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6bc16c16c7a93e3a05ce2a989e9fb67b91f6f6f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37641">issues.joomla.org/tracker/joomla-cms/37641</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6bc16c16c7a93e3a05ce2a989e9fb67b91f6f6f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37641">issues.joomla.org/tracker/joomla-cms/37641</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37641">issues.joomla.org/tracker/joomla-cms/37641</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
