### PR TITLE
Fix SQL commands for sample and testing data

### PR DESCRIPTION
**Pull request by Erftralle**
This is a fix for issue #6216. Please read #6216 for further informations and test instructions.

### CODE REVIEW

**Comment by stellainformatica** [comment]
@test
Patch tested with sample_data.sql

It works as expected, thanks Erftralle

**Comment by waader** [comment]
@test works with sample_testing.sql! Thanks!

**Comment by zero-24** [comment]
Moving to RTC based on testing. Thanks! For coding and testing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6241">issues.joomla.org/joomla-cms/6241</a>.</sub>

**Comment by alikon** [comment]
it seems that lacks the corresponding changes on postgresql and mssql  sample files

**Comment by Erftralle** [comment]
> it seems that lacks the corresponding changes on postgresql and mssql sample files

Done!
Unfortunately I can not test it myself.

**Comment by alikon** [comment]
You should do the same on sample_data too

**Comment by Erftralle** [comment]
>You should do the same on sample_data too

Sorry, but I don't know what you want me to do.

The **sample_data.sql** for MySQL is ok for me, in the related files for PostgreSQL and SQL Azure there is nothing to do regarding the Tags table.

Maybe I missed something. Can you point me into the right direction.

**Comment by alikon** [comment]
No sir you are right :ok_hand:

**Comment by waader** [comment]
@test success with postgresql and mssql! Thanks!

**Comment by phproberto** [comment]
Merged thanks!

**Pull request closed without merging**
