### PR TITLE
[4.0] Unused strings

### PR DESCRIPTION
**Pull request by brianteeman**
Removes two unused strings. The reference to them in the sql was already removed

UPDATED
Also removes the pre joomla4 preparation message from the sql and language file

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2ff34a1cea7a818dd0cd6a6e4626e67b0bdb0d66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19331">issues.joomla.org/tracker/joomla-cms/19331</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on eee8330d5b11150166c1268a3383b2e3c8a5b338<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19331">issues.joomla.org/tracker/joomla-cms/19331</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on eee8330d5b11150166c1268a3383b2e3c8a5b338<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19331">issues.joomla.org/tracker/joomla-cms/19331</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19331">issues.joomla.org/tracker/joomla-cms/19331</a>.</sub>

**Comment by wilsonge** [comment]
If we're deleting the SQL then we need to remove the main file as well https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/postinstall/joomla40checks.php

**Comment by brianteeman** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
