### PR TITLE
[com_banners] tracks view: Add max level filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

All backend views that are or are associated with tree like structures (e.g. menus, categories) should have a max level filter.

This is valid currently for:
- com_menus items view
- com_content articles view
- com_content featured view
- com_tags tags view

So, this PR is a part of series of PR to add that filter in the views that use categories:
- com_contacts contacts view (RTC https://github.com/joomla/joomla-cms/pull/9975)
- com_banners banners view (RTC https://github.com/joomla/joomla-cms/pull/9977)
- com_newsfeeds newsfeeds view (RTC https://github.com/joomla/joomla-cms/pull/9978)
- com_notes notes view (RTC https://github.com/joomla/joomla-cms/pull/9984)
- com_banners tracks view (**this PR**)

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Create some banners categories with at least two levels
3. Create some banners and associate them to the categories created in 2..
4. Go to "Components" -> "Banners" -> "Tracks" (ensure you have some tracks, see note below) and test the new max levels filter.

Note: If you don't have tracks records you can generate some in the database (`#__banners_tracks` table), example:

``` sql
INSERT INTO `<prefix>_banner_tracks` (`track_date`, `track_type`, `banner_id`, `count`) VALUES ('2016-04-11 00:00:00', '1', '1', '5');
INSERT INTO `<prefix>_banner_tracks` (`track_date`, `track_type`, `banner_id`, `count`) VALUES ('2016-01-11 00:00:00', '2', '1', '7');
INSERT INTO `<prefix>_banner_tracks` (`track_date`, `track_type`, `banner_id`, `count`) VALUES ('2015-04-11 00:00:00', '2', '2', '9');
INSERT INTO `<prefix>_banner_tracks` (`track_date`, `track_type`, `banner_id`, `count`) VALUES ('2016-02-11 00:00:00', '2', '2', '12');
```

### CODE REVIEW

**Comment by wojsmol** [comment]
@andrepereiradasilva Please corect last inset for `<prefix>_banner_tracks`

**Comment by andrepereiradasilva** [comment]
ups, sorry done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1f3576e789ecbc9b258bf93c18d8374cd85d8a1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10009">issues.joomla.org/joomla-cms/10009</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva With the patch applied I see these 2 green fields for begin and end date, in addition to those at the top where I could adjust the dates. Without the patch, I do not see these green fields.

Question: 1. Is this intended, and 2. what are those fields good for? When I click the calendar button right beside one of these green fields, nothing happens.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10009">issues.joomla.org/joomla-cms/10009</a>.</sub>

**Comment by andrepereiradasilva** [comment]
1. Is a know issue https://github.com/joomla/joomla-cms/issues/7856 not related to this PR
2. Filter in a date interval

See https://github.com/joomla/joomla-cms/pull/9951 when seartools where implemented ther for more info.

**Comment by richard67** [comment]
Ok, seems my latest staging was not late enough: It did not contain #9951 :smile: 

I'll test again soon but think it will be ok then.

**Comment by andrepereiradasilva** [comment]
:)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1f3576e789ecbc9b258bf93c18d8374cd85d8a1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10009">issues.joomla.org/joomla-cms/10009</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10009">issues.joomla.org/joomla-cms/10009</a>.</sub>

**Comment by rdeutz** [comment]
technically this is a new feature and it doesn't fix a bug so it has to go into 3.6.0

**Comment by rdeutz** [comment]
@andrepereiradasilva cloud you please check the merge conflicts, thanks

**Comment by andrepereiradasilva** [comment]
finnaly, all conflicts fixed

**Pull request merged**
