### PR TITLE
[4.0] build.js codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
My ide was complaining about the code style here

code review

### CODE REVIEW

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 3f14e03df322333fbd29eaf48e154e294e3f29c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36059">issues.joomla.org/tracker/joomla-cms/36059</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 3f14e03df322333fbd29eaf48e154e294e3f29c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36059">issues.joomla.org/tracker/joomla-cms/36059</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3f14e03df322333fbd29eaf48e154e294e3f29c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36059">issues.joomla.org/tracker/joomla-cms/36059</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36059">issues.joomla.org/tracker/joomla-cms/36059</a>.</sub>

**Comment by chmst** [comment]
thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
