### PR TITLE
[4.0] Sanitize modals

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

# This is also a RELEASE BLOCKER

### Summary of Changes
- sanitize the iframe tag passed as a data attribute

### Testing Instructions
Apply the patch or download the installable package from the Github PR

Try to edit an article, select an image, select a user
Try to edit a menu item and create/edit an article
Modals should work fine

### Actual result BEFORE applying this Pull Request
The initialization of a modal could be compromised to run non verified code 

### Expected result AFTER applying this Pull Request
The iframe tag can not be compromised

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ea7b59a7e5ae22b531ade517c8abfc8df073ca71<br /><br />Test was:

- Create a new article, append image in article text, select user. Save, view in back- and frontend. Use Codemirror.
- Create new menu-item `Single article`, create article, save menu-item, view in front end. Reopen menu-item, edit article, save and view in frontend again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34480">issues.joomla.org/tracker/joomla-cms/34480</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ea7b59a7e5ae22b531ade517c8abfc8df073ca71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34480">issues.joomla.org/tracker/joomla-cms/34480</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34480">issues.joomla.org/tracker/joomla-cms/34480</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
