### PR TITLE
[com_fields] Suggestion to improve understanding of label

### PR DESCRIPTION
**Pull request by helvecio**
### File to change

administrator/language/en-GB/en-GB.com_fields.ini

### Summary of Changes

```
18 COM_FIELDS_FIELD_DISPLAY_AFTER_DISPLAY="After Display"
18 COM_FIELDS_FIELD_DISPLAY_AFTER_DISPLAY="After Content"

20 COM_FIELDS_FIELD_DISPLAY_BEFORE_DISPLAY="Before Display"
20 COM_FIELDS_FIELD_DISPLAY_BEFORE_DISPLAY="Before Content"

22 COM_FIELDS_FIELD_DISPLAY_LABEL="Automatic Display"
22 COM_FIELDS_FIELD_DISPLAY_LABEL="Fields Display"
```
### Actual result
This is a suggestion to change these strings related to the position of custom fields to allow a better comprehension by users when setting its position related to the content.

### CODE REVIEW

**Comment by zero-24** [comment]
@helvecio can you please confirm you changes? You want to change something in com_fileds but you change a string in com_tags?

**Comment by brianteeman** [comment]
Dont these strings refer to the plugin events that the fields appear as a result of?

**Comment by coolcat-creations** [comment]
But the trigger Events are named like that, if you rename it no one will understand what´s going on? I would not rename it... And automatic Display is also more logic for me because it refers to an automatic display. You can disable automatic and place them yourself in the override.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14504">issues.joomla.org/tracker/joomla-cms/14504</a>.</sub>

**Comment by brianteeman** [comment]
@helvecio I am closing this due to your lack of response to any of the questions

**Pull request closed without merging**
