### PR TITLE
[4.0] Postinstall messages

### PR DESCRIPTION
**Pull request by brianteeman**
Make the button work

Pull Request for Issue #21875  .

### Note
The controller is Message
The model is messages
Don't know if that's another bug or not

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 49f8b5e1cbbd3c7d75ec851eb192736f36979eed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21882">issues.joomla.org/tracker/joomla-cms/21882</a>.</sub>

**Comment by wilsonge** [comment]
> The controller is Message
The model is messages
Don't know if that's another bug or not

Me neither 🤷‍♂️ it's like that for everything. So I just stuck with it for the purposes of the merging in of staging. Probably at some point we should try and sort them out into logical groupings.

**Comment by richard67** [comment]
Just when I wanted to set my positive test result it was merged ;-)

**Comment by brianteeman** [comment]
Thanks

**Comment by ghost** [comment]
> Just when I wanted to set my positive test result it was merged ;-)

sounds familiar.

**Comment by richard67** [comment]
This composer and npm install stuff to have an up-to-date testing environment simply takes too long time ;-)

**Comment by ghost** [comment]
my Test used Patchtester.

**Pull request merged**
