### PR TITLE
Update Composer dependencies

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

```sh
Package operations: 0 installs, 11 updates, 0 removals
  - Updating paragonie/random_compat (v1.4.1 => v1.4.2)
  - Updating phpmailer/phpmailer (v5.2.22 => v5.2.23)
  - Updating symfony/yaml (v2.8.17 => v2.8.20)
  - Updating sebastian/diff (1.4.1 => 1.4.3)
  - Updating symfony/debug (v2.8.15 => v2.8.20)
  - Updating symfony/console (v2.8.15 => v2.8.20)
  - Updating symfony/event-dispatcher (v2.8.15 => v2.8.20)
  - Updating symfony/filesystem (v2.8.15 => v2.8.20)
  - Updating symfony/finder (v2.8.15 => v2.8.20)
  - Updating symfony/process (v2.8.15 => v2.8.20)
  - Updating symfony/stopwatch (v2.8.15 => v2.8.20)
```

Note that a good bulk of these are for the test environment only and don't affect production releases

### Testing Instructions

For the items that are testable in the normal CMS install:
- Mail sending still works
- Pseudo random number generation still works (generating a secret at install, generating random passwords, generating the stats collection ID)

All other changes are either test environment only or in code that is not executed through normal use of the CMS.

### CODE REVIEW

**Comment by brianteeman** [comment]
@mbabker looks like there are merge conflicts

**Comment by zero-24** [comment]
I guess this come because we changed inputfilter from the sec update.

**Comment by mbabker** [comment]
It's because another PR where George updated only the filter package was merged.  I'm not touching this until either after 3.7.2 goes out or someone decides we'll update all the libraries in 3.7.2, can't say I'm in a rush to update PRs not moving anywhere fast.

**Comment by brianteeman** [comment]
>  can't say I'm in a rush to update PRs not moving anywhere fast.

I am with you on that one

**Comment by mbabker** [comment]
PR rebased

**Comment by brianteeman** [comment]
Thanks I hope it can be merged quickly now

**Comment by rdeutz** [comment]
merged on review

**Pull request merged**
