### PR TITLE
Cancel profile redirect link

### PR DESCRIPTION
**Pull request by brianteeman**
As reported at #6311

Create a menu link to user profile
Login and select the menu item
You will see your profile
Click on edit and save and you are returned to the profile
Click on edit and cancel and you are redirected to the home page

This PR changes that last behaviour so that when you select cancel you are returned to the profile

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c17f1a2b68198188ccd7688c9a673055f6f86a0e<br /><br />works good, 
but maybe better will be explicitly set the link to the profile view?
means `index.php?option=com_users&view=profile`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8402">issues.joomla.org/joomla-cms/8402</a>.</sub>

**Comment by brianteeman** [comment]
I will update the pr

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 36e7e1bb0eb508f723a23369ccd5f315f10722b1<br /><br />still works :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8402">issues.joomla.org/joomla-cms/8402</a>.</sub>

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 36e7e1bb0eb508f723a23369ccd5f315f10722b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8402">issues.joomla.org/joomla-cms/8402</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 36e7e1bb0eb508f723a23369ccd5f315f10722b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8402">issues.joomla.org/joomla-cms/8402</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8402">issues.joomla.org/joomla-cms/8402</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thanks @brianteeman and testers! Merged.

**Pull request merged**
