### PR TITLE
Converts none editor to service providers

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Converts the none editor to service providers.

This pr contains the commits from #39625.

### Testing Instructions
- Make sure None is the default editor
- Edit an article

Also test if the other editors do still work

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo PHPCS complains: https://ci.joomla.org/joomla/joomla-cms/60911/1/8

**Comment by laoneo** [comment]
Thanks for the hint, fixed it

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 256c7e80068fb6b9fdb9db8e30684bcef6656408<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39639">issues.joomla.org/tracker/joomla-cms/39639</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 256c7e80068fb6b9fdb9db8e30684bcef6656408<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39639">issues.joomla.org/tracker/joomla-cms/39639</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39639">issues.joomla.org/tracker/joomla-cms/39639</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo for the PR :-)

**Pull request merged**
