### PR TITLE
[3.0] Tree sorting in templates file tree

### PR DESCRIPTION
**Pull request by brianteeman**
This is a weird one and I cant say I fully understand it but this resolves the problem described below.

If you have a large number of files in a folder then when you look at the list of files in the tree you will see that they are not in alphabetical order. They are in alphabetical order "in groups" which is why you need more than usual files to see it.

To test copy a folder with a lot files to `templates\protostar\html`

I used this folder as a source `administrator\components\com_templates\views\template\tmpl`

Now when you view the file tree in the template component you will see the sorting is wrong as per screenshot from the **middle** of the list
image

Apply this PR and retest and the sorting is as expected as seen in this screenshot from the **end** of the list

image

### CODE REVIEW

**Comment by brianteeman** [comment]
NOTE: The same issue exists on J4 but as the fix is identical I assume there is no need for a seperate PR and this will get merged upstream eventually

**Comment by wilsonge** [comment]
Can you add back weblinks please :P

**Comment by brianteeman** [comment]
Done ;)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e7b3b8b86ebdae04e2c757d2ccba8f4a027ede29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25792">issues.joomla.org/tracker/joomla-cms/25792</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e7b3b8b86ebdae04e2c757d2ccba8f4a027ede29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25792">issues.joomla.org/tracker/joomla-cms/25792</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
Thanks - this has been bugging me for ages

**Comment by HLeithner** [comment]
Thank you for the time you invest in Joomla!

**Pull request merged**
