### PR TITLE
[3.5] Remove com_banners and mod_banners from core new installs

### PR DESCRIPTION
**Pull request by zero-24**
Following the roadmap for Joomla 3.5: 
`Remove additional components and all associated pieces. ([...] com_banners).[...]`
http://developer.joomla.org/cms/roadmap.html

This will remove com_banners from the core new installs.
### how to test (first test)
- download my branche: https://github.com/zero-24/joomla-cms/archive/bannerRemoval.zip
- install as normal joomla 3.4
- make sure com_banners is gone and no errors are there e.g. SQL or others.
### how to test (seccond test)
- install normal 3.4
- update with a update package (needs to be created and uploaded to joomla.org)
- see that nothing is changed and com_banners still work as expeced.
### Open questions
- what we need to do outsited of this PR?
- how can we create a update package and upload it to joomla.org? (for the seccond test)
### More information
- New com_banners repo: https://github.com/joomla-extensions/banners
- First PR: https://github.com/joomla-extensions/banners/pull/1

### CODE REVIEW

**Comment by dgt41** [comment]
@zero-24 shall I close #6986 and re do it in the new repo?

**Comment by zero-24** [comment]
@dgt41 Can you send it against my repo/PR/branch? https://github.com/zero-24/banners/tree/initial

**Comment by dgt41** [comment]
@zero-24 Also https://github.com/joomla/joomla-cms/search?o=desc&q=banners&s=created&type=Issues&utf8=✓
I see a lot of open PRs. Will be nice to inform those people to push their code to the new repo

**Comment by zero-24** [comment]
@dgt41 Thanks see: https://github.com/joomla-extensions/banners/pull/1#issuecomment-104739639

**Comment by zero-24** [comment]
Closing as the PLT decides to not decuple any more extension for now see: http://developer.joomla.org/news/616-meeting-notes-from-jab-plt-summit-2015.html

```
The PLT went on to discuss the removal of core supported extensions. There are 2 existing PR’s for component removal in 3.5 - banners and messages. Issues were raised about how marketing and release teams would deal with having to release half a dozen extensions and the CMS in a worse case scenario as there are little plans in place. It was also raised that there were also little provision in place for setting up distributions and a new method of sample data. It was therefore agreed that we will remove com_messages but leave com_banners in the CMS while the PLT deals with the issues mentioned.
```

I will open a PR to backport the fixes from the new Repo to the CMS :smile: See: https://github.com/joomla/joomla-cms/pull/7337

**Comment by chrisdavenport** [comment]
That doesn't mean we're not going to decouple any more core extensions.  It just means that we're pausing while we work out the logistical issues that have come to light after weblinks was decoupled.

**Comment by zero-24** [comment]
Yes. But we have fixes in the new repo that needs to be go in the next release. ;) Thanks goes to @dgt41 ;) So until we pausing we can save close this PR and if we back agian we can do a new PR :)

**Comment by chrisdavenport** [comment]
Yes, backporting is good.  Just don't give up on decoupling. :-)

**Comment by zero-24** [comment]
hmm we have also issues with decoupling messages (https://github.com/joomla/joomla-cms/pull/6352#issuecomment-117181287). So there we also need a decision, as it break in the current state B/C this needs to wait for 4.0 or we have a other solution ;).

**Comment by smz** [comment]
My small 2c is that although I understand the logistic issues that brought the PLT to such decision, it is really unfortunate we don't proceed with decoupling extensions from the core as planned.

**Pull request closed without merging**
