### PR TITLE
PostgreSQL - redirect link not saved

### LINKED ISSUE #6349: Postgresql: NULL-Value in column referer violates not-null-constraint
Try to add a new link in the redirect manager. You will get the following error because of a not-null-constraint violation:

Save failed with the following error: SQL=INSERT INTO "ckqxo_redirect_links" ("old_url","new_url","comment","published","created_date","modified_date") VALUES ('http://www.testxyz.com','http://www.testxyz.org','',1,'2015-03-06 18:42:26','2015-03-06 18:42:26') RETURNING id

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

go to the Redirect manager and create a new link  and Save
#### Expected result

the redirect link is saved
#### Actual result

SQL ERROR not null constraint violation
#### System information

PostgreSQL 9.3.5
Joomla 3.4.0
#### Additional comments

added a sanity check for NOT NULL FIELDS
fix #6349

### CODE REVIEW

**Comment by wilsonge** [comment]
This is one of the cases where the field should be able to be nullable (this condition can actually be seen really easily - https://github.com/joomla/joomla-cms/blob/staging/plugins/system/redirect/redirect.php#L122).

**Comment by alikon** [comment]
let me disagree
when you add a new redirect link from the  Redirect manager component in the backend and save data
that plugin event is not triggered
so if you don't set ```$this->referer = '';``` you get this error

```
Save failed with the following error:
 SQL=INSERT INTO "scaku_redirect_links" ("old_url","new_url","comment","published","created_date","modified_date") VALUES ('aaaa','aaaaaaa','',1,'2015-03-07 18:03:54','2015-03-07 18:03:54') 
```

**Comment by wilsonge** [comment]
In the case where you manually add a new link there is no referring URL of course. So surely that's another reason to remove the ```NOT NULL``` in the database?

**Comment by alikon** [comment]
in my opinion the best thing to do is a complete review of our data model , if we change our constraints on spot
we are going to loose  the  overall picture
https://github.com/joomla/joomla-cms/pull/6265#issuecomment-76904790

**Comment by waader** [comment]
@test works on postgresql, mysql, mssql. Thanks @alikon!

@wilsonge and @alikon Your arguments are both valid logically or practically. I am in the practical camp. In the end we have come to a decision.

**Comment by brianteeman** [comment]
@test issue confirmed on pg and the fix resolves that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6355">issues.joomla.org/joomla-cms/6355</a>.</sub>

**Comment by orware** [comment]
@alikon 

I've tested this one successfully, however I would like to make one quick change suggestion to this PR.

I noticed above in your comment on March 7 you mentioned setting the referer to an empty string, but in the PR it looks like you're setting it to a string containing a single space.

At first I thought the space was needed for some reason but I tested with an empty string and that appeared to work just fine so I think there just may be a typo in the PR.

If that's updated I have no objections on this one and it does fix the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6355">issues.joomla.org/joomla-cms/6355</a>.</sub>

**Comment by orware** [comment]
(Just for clarity, my test was performed on Postgres to confirm the error and fix and then I tried it also in MySQL, which isn't exhibiting the issue currently, but applying the fix doesn't introduce any issues on the MySQL end).

Additionally:
Another possible solution for this sort of problem (which could potentially be tackled in the future, I still approve the current fix for this issue proposed by @alikon) would be to make greater use of the information that the getTableColumns() methods can return in our database drivers and use that to automatically set empty string values for these types of columns when they are detected (so instead of the additional code being needed in the JTable class, it could potentially be fixed at the database driver level within the insertObject() method used by the JTable classes).screen shot 2015-04-08 at 21 41 10screen shot 2015-04-08 at 21 41 10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6355">issues.joomla.org/joomla-cms/6355</a>.</sub>

**Comment by brianteeman** [comment]
tested again still works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6355">issues.joomla.org/joomla-cms/6355</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6355">issues.joomla.org/joomla-cms/6355</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @alikon! Merged.

**Comment by zero-24** [comment]
@Kubik-Rubik is there a reason to let this PR open?

**Comment by zero-24** [comment]
Or did you comment on the wrong itm?

**Comment by Kubik-Rubik** [comment]
No, I just forgot to add "Fixes" to the commit so GitHub didn't close it automatically... the commit is here: https://github.com/joomla/joomla-cms/commit/6715323c69cf322e2ccc4e4e4de299f1e8ca2619

**Comment by zero-24** [comment]
:+1:

**Pull request closed without merging**
