### PR TITLE
[4.4] [BUGFIX] Enforce UTF-8 on CSS Files

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #42611 .

### Summary of Changes

Adds `@charset "UTF-8";` as a first line on all the CSS files. Docs: https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

### Testing Instructions

- ~~Ensure your browser default encoding IS NOT `UTF-8`~~
- Download and install Joomla from this Pull Request
- Check that icons don't get weird...

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
> Ensure your browser default encoding IS NOT UTF-8

How?

**Comment by dgrammatiko** [comment]
> How?

Turns out only safari allows changing the default encoding. FF and Chrome do not expose this setting anymore

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on ec1e0928fd570710895de9a6b3aba2c345319cd9<br /><br />with utf-8 better than without :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42938">issues.joomla.org/tracker/joomla-cms/42938</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ec1e0928fd570710895de9a6b3aba2c345319cd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42938">issues.joomla.org/tracker/joomla-cms/42938</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42938">issues.joomla.org/tracker/joomla-cms/42938</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
