### PR TITLE
oops capitalisation typos

### PR DESCRIPTION
**Pull request by brianteeman**
Confirm email Address
-->
Confirm Email Address
#### Before

d8hp
#### After

cuur

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 68ec5bbb2998862893a2fbe49f3db7a828979871<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12243">issues.joomla.org/joomla-cms/12243</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 68ec5bbb2998862893a2fbe49f3db7a828979871<br /><br />on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12243">issues.joomla.org/joomla-cms/12243</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12243">issues.joomla.org/tracker/joomla-cms/12243</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
