### PR TITLE
Do not show a deprecated message when no ordering is set in back end list views

### PR DESCRIPTION
**Pull request by MacJoom**
Pull Request for Deprecated message in Joomla Patch Tester

### Summary of Changes

Avoid deprecated message

### Testing Instructions
Install Joomla Patch Tester

PHP 8.1
Turn on all PHP Warnings
display_errors = On
error_reporting = E_ALL | E_STRICT

### Actual result BEFORE applying this Pull Request

Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/clients/client2/web14/web/joomla-cms/libraries/src/MVC/Model/ListModel.php on line 543

Disturbs 'Fetch Data' in popup window too.

### Expected result AFTER applying this Pull Request

No warning

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on bb1ffffd9e519de611c6007690c63a42988571b4<br /><br />Tested successfully in Joomla 4.2.4-dev of 24 October in Wampserver using PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39050">issues.joomla.org/tracker/joomla-cms/39050</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bb1ffffd9e519de611c6007690c63a42988571b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39050">issues.joomla.org/tracker/joomla-cms/39050</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39050">issues.joomla.org/tracker/joomla-cms/39050</a>.</sub>

**Comment by zero-24** [comment]
To me this is the wrong solution for this problem.. When this is an issue only with the patchtester it should be patched in the patchtester.. When its a general problem it should be fixed for all cases not only this specific case.. Please do not merge this as it is right now.

**Comment by richard67** [comment]
> To me this is the wrong solution for this problem.. When this is an issue only with the patchtester it should be patched in the patchtester.. When its a general problem it should be fixed for all cases not only this specific case.. Please do not merge this as it is right now.

I think it could be a general issue because the ordering direction might not be always set. But I might be wrong of course.

**Comment by laoneo** [comment]
I have the same issue in DPCalendar. For years we could pass NULL as ordering, why should it all of the sudden fail. This should be fixed here and not on every extension.

**Comment by brianteeman** [comment]
The title of the pr should be updated to reflect what it actually is for.

**Comment by laoneo** [comment]
Done.

**Comment by zero-24** [comment]
> I have the same issue in DPCalendar. For years we could pass NULL as ordering, why should it all of the sudden fail. This should be fixed here and not on every extension.

It has been changed by PHP not us, so to me its a clear php combat patch of the one who is doing the no longer allowed call. When it would be patched here we should fix it for all cases in this method not just that single case that where hit by patchtester or dpcalendar.

I personally dont like us adding to all methods an is_null check as thats sound very wrong to me and is a lot of code which is avoidable but when we want this to be fixed in the Core code we should not only fix it for this sub-case but all affected places in this method.

**Comment by HLeithner** [comment]
> I personally dont like us adding to all methods an is_null check as thats sound very wrong to me and is a lot of code which is avoidable but when we want this to be fixed in the Core code we should not only fix it for this sub-case but all affected places in this method.

In theory you are right but this case is diffrent because the input hasn't been provided thru a mechanism which is (or can be) automatically validated by php. 
The programmer provides us an ARRAY with information, and we should (have to) validate this input, in this case it's even worse because we don't validate user input (getUserStateFromRequest).

So it's perfectly fine for us to check if the provided parameters are right.

@MacJoom thanks

**Comment by richard67** [comment]
Thanks @HLeithner .

**Pull request merged**
