### PR TITLE
4.0 dev update bootstrap library

### PR DESCRIPTION
**Pull request by 1337180**
update bootstrap library to 5.1

### CODE REVIEW

**Comment by brianteeman** [comment]
Please close

**Comment by richard67** [comment]
@1337180 Your PR should be for the 4.0-dev branch but you have made it for the staging branch. Therefore it shows over 5 thousand changed files. You should have noticed that.

Furthermore you should have checked if `npm ci` works after updating bootstrap from 5.0.2 to 5.1.0. I did that here and it failed.

So I'm in doubt if you have tested your changes.

Finally, we already are on it to update BS to 5.1 but it seems it requires changes on our scss do adapt to the changes from 5.0.2 to 5.1.

Closing because it's for the wrong branch.

**Comment by brianteeman** [comment]
@richard67 all this pr did was to merge 4.0 and staging - there was nothing created by the author

**Comment by brianteeman** [comment]
> Finally, we already are on it to update BS to 5.1 but it seems it requires changes on our scss do adapt to the changes from 5.0.2 to 5.1.

To be fair they are not a mind-reader so they wouldnt know anyone was doing that

**Pull request closed without merging**
