### PR TITLE
[4.0] Fix include path of categories fields

### PR DESCRIPTION
**Pull request by laoneo**
As with the change to namespaces in #15893 the core XML files do need to be adapted to that scheme.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 825e5ab7f81ccfb38b54cea392e88aa0a8a7ffab<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16419">issues.joomla.org/tracker/joomla-cms/16419</a>.</sub>

**Comment by Bakual** [comment]
Works fine

Is that something that needs to be documented? And how will it work for 3rd party extension that need to work both in J3.9 and J4? Can they add both paths (old and new) and it will find the right one?

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 825e5ab7f81ccfb38b54cea392e88aa0a8a7ffab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16419">issues.joomla.org/tracker/joomla-cms/16419</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by mbabker** [comment]
@wilsonge Please don't merge until there's an answer to @Bakual question (just so it doesn't get lost in the shuffle).

**Comment by laoneo** [comment]
@Bakual, yes it will find both ones, on J3 it will use the addfieldpath attribute and on J4 the new one.

**Comment by Bakual** [comment]
Added "Documentation Required" label. Should be fine to be merged based on Allons answer.

**Pull request merged**
