### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by janschoenherr**
Remove unused variable.

### Summary of Changes

Remove unused variable.

### Testing Instructions

Use Articles - Categories module

### Actual result BEFORE applying this Pull Request

No visible changes

### Expected result AFTER applying this Pull Request

No visible changes

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
is it not used on line 40 ?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 86d07c1f88e17e696db7c4a1c88df85e4cea4176<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44539">issues.joomla.org/tracker/joomla-cms/44539</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 86d07c1f88e17e696db7c4a1c88df85e4cea4176<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44539">issues.joomla.org/tracker/joomla-cms/44539</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for this cleanup!

**Pull request merged**
