### PR TITLE
Fix minicolor initialization in subforms. etc.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes
Similar to #12542 and #12993 but for the minicolors color picker.

### Testing Instructions
First of all, color pickers should still work normally. More importantly, color pickers inside of subforms should be initialized when new rows are added.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 29d47a14b1270fcf2c9f28453ac609faffbfa757<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12994">issues.joomla.org/tracker/joomla-cms/12994</a>.</sub>

**Comment by okonomiyaki3000** [comment]
These js failures are related to combobox, probably nothing to do with this PR.

**Comment by Quy** [comment]
Just checking if `media/system/js/subform-repeatable-uncompressed.js` should be updated since `media/system/js/subform-repeatable.js` was updated?

**Comment by okonomiyaki3000** [comment]
@Quy I believe not. It looks like I just used a different minifier on it.

**Comment by Schmidie64** [comment]
Could you please provide more specific test instructions (eg. were do i use the color-picker?).

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12994">issues.joomla.org/tracker/joomla-cms/12994</a>.</sub>

**Comment by sabaturgay** [comment]
I have tested this item :white_check_mark: successfully on 37b5ecf703d8612236e343a5534f270b0017f476<br /><br />I have tested successfully

Test
Components => Banners => New => MultilineText TextColor Picker
Result
It worked
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12994">issues.joomla.org/tracker/joomla-cms/12994</a>.</sub>

**Comment by ghost** [comment]
@Fedik can you please retest?

**Comment by bene-we** [comment]
I have tested this item :white_check_mark: successfully on 37b5ecf703d8612236e343a5534f270b0017f476<br /><br />Reproduction steps:

I installed the [_componentbuilder_](https://github.com/vdm-io/Joomla-Component-Builder "componentbuilder") which already has subforms included _(example url: index.php?option=com_componentbuilder&view=component_admin_views&ref=joomla_components&layout=edit&id=27)_.

After that I replaced one field from a row with a color picker, added and removed some rows and the color pickers are initialized right.

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12994">issues.joomla.org/tracker/joomla-cms/12994</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

@okonomiyaki3000 Please resolve conflicting Files.

**Comment by okonomiyaki3000** [comment]
There is no problem here. Do not believe Appveyor's lies.

**Comment by ghost** [comment]
@wilsonge?

**Pull request merged**
