### PR TITLE
Unable to select Url type menu item as Base item in mod_menu

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for #20556 and multiple closed issues

Create menu consisting of URL type items and subitems of any type(that is important)
Go to Modules -> New -> Menu
Try to select as Base item the URL type items you added

url, alias, heading etc were not selectable. The logic made sense as you can't click on one of those to open a submenu. However as you can open a submenu by hover then it does have a purpose so this PR removes that restriction

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on cbdf9f996ebe8830372daa6a87e2127d4750d2ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38563">issues.joomla.org/tracker/joomla-cms/38563</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cbdf9f996ebe8830372daa6a87e2127d4750d2ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38563">issues.joomla.org/tracker/joomla-cms/38563</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38563">issues.joomla.org/tracker/joomla-cms/38563</a>.</sub>

**Comment by fancyFranci** [comment]
Sorry, but to be sure we are not missing something I'm moving the PR to 4.3. Then we have more tests. Thanks for your work!

**Comment by brianteeman** [comment]
Very sad face

**Comment by viocassel** [comment]
🤨

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR.

**Pull request merged**
