### PR TITLE
Missing lang strings for Article XTD in frontend

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25344

### Summary of Changes
Adding missing strings for article alias

### Before patch
Screen Shot 2019-07-05 at 07 44 32

### After patch

Screen Shot 2019-07-05 at 08 16 08

### CODE REVIEW

**Comment by infograf768** [comment]
Note: Imho we should solve in another way the apparently missing Sorting strings when debug lang on for Contact, Article and Field as these are no use in the modals.

**Comment by infograf768** [comment]
@HLeitner
We should consider this for 3.9.9 imho. We will manage with TTs.

**Comment by SharkyKZ** [comment]
Just realized the sorting is used. We just can't see it in the modal because it has `hidden-phone` class applied. I'm certain this is not intentional.

**Comment by infograf768** [comment]
Not sure it is related to `hidden-phone`

**Comment by brianteeman** [comment]
It is the hidden-phone hidden-tablet in the layout - so if you override the layout or use a template that doesnt have those classes it will display with the missing strings of course

This is why I wrote https://github.com/joomla/joomla-cms/issues/25344#issuecomment-508555792

image

**Comment by infograf768** [comment]
As you know better, _of course_, please make patch.
(I did not find what has to be modified to display the sort fields)

**Comment by brianteeman** [comment]
Stop with the personal comments - its really pathetic

https://github.com/joomla/joomla-cms/blob/fefffc9c53bdbb92054997333523125acfcc9b4c/layouts/joomla/searchtools/default.php#L92-L94

**Comment by ghost** [comment]
please all focus on Issue, thanks.

**Pull request closed without merging**
