### PR TITLE
[postgresql] - wrong GROUP BY in multilanguage site

### PR DESCRIPTION
**Pull request by alikon**
yet another one  wrong GROUP BY  - redo of #21378 in the correct 3.9-dev branch
### Summary of Changes
fixed wrong GROUP BY

### Testing Instructions
install a multilanguage site with postgresql 
simply open Control Panel or Articles

### Expected result
works as it should

### Actual result
screenshot from 2018-08-03 10-38-25

### CODE REVIEW

**Comment by csthomas** [comment]
I tested it and it works, but 
```php
$assogroup = 'a.id, l.title, l.image, uc.name, ag.title, c.title, ua.name, c.created_user_id, c.level, parent.id';
```

also works and it is a short list. 

It works because parent.id is a primary key, the same as `a.id`.

Could you change it?

**Comment by alikon** [comment]
sure, done
thanks

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on cd946d09de3bd865e79c38178d50fcbac22b52ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21436">issues.joomla.org/tracker/joomla-cms/21436</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 807116e813ca74d967842e1b6592228dbd9d8750<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21436">issues.joomla.org/tracker/joomla-cms/21436</a>.</sub>

**Pull request merged**
