### PR TITLE
[4.2] extra space in class

### PR DESCRIPTION
**Pull request by brianteeman**
Simple code style fix to remove a leading space

code review is enough

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 981c9feff8d5d2d6e23544507feecbba1cf78d1f<br /><br />Code review <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38829">issues.joomla.org/tracker/joomla-cms/38829</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 981c9feff8d5d2d6e23544507feecbba1cf78d1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38829">issues.joomla.org/tracker/joomla-cms/38829</a>.</sub>

**Comment by richard67** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38829">issues.joomla.org/tracker/joomla-cms/38829</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
