### PR TITLE
[4.2] PHP8.2 deprecated relative callables

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

> Callables that are not accepted by the $callable() syntax (but are accepted by call_user_func()) are deprecated.

https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.relative-callables
https://wiki.php.net/rfc/deprecate_partially_supported_callables

### Testing Instructions

Change following line in MailTemplate to `$this->mailer->addRecipient($recipient->mail, $recipient->name);` to use the function of the Mail class (because I don't find any use in the core)
https://github.com/joomla/joomla-cms/blob/e9b9263a34ad919c7a8e6b817074f53eb1997565/libraries/src/Mail/MailTemplate.php#L275

### Actual result BEFORE applying this Pull Request

PHP Deprecated:  Use of "parent" in callables is deprecated in `libraries/src/Mail/Mail.php` on line 301

### Expected result AFTER applying this Pull Request

No deprecated message

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 2ca3012734382af2bd099e2a7e39f441c6522d31<br /><br />Tested while sending a mail with DPCalendar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39500">issues.joomla.org/tracker/joomla-cms/39500</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on da9204e44cb7e9c3374fc848c79dc2246496f565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39500">issues.joomla.org/tracker/joomla-cms/39500</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39500">issues.joomla.org/tracker/joomla-cms/39500</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
