### PR TITLE
[com_fields] Migrate from repeatable to subform field for list options

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
As the repeatable form field is deprecated we need to migrate the custom fields list options to a subform field.

What needs to be discussed is the layout of the subform to choose, any suggestions which one would be best? Pinging here @coolcat-creations and @ciar4n.

~~Till #12813 got merged, you need to apply that patch first.~~

### Testing Instructions
- Create a list field
- Edit an article and choose some values
- Open the article on the front

### Expected result
All should work the same as without the patch. The only things which changes is that a subform field is shown when entering the list options.

image

### Actual result
image

### CODE REVIEW

**Comment by ggppdk** [comment]
Your changes in libraries/joomla/form/abstractlist.php 
for method: getOptionsFromField()

effect 3 fields: list, radio, checkboxes

and you only updated the list field,
the other 2 fields are now broken, e.g. broken in edit form

**Comment by laoneo** [comment]
Thanks @ggppdk for the hint. I'v fixed it in the last commit and added a JText call to the name attribute that the name will be translated as well.

**Comment by ciar4n** [comment]
@laoneo Considering there will be only 2 fields per line, personally I think subform.repeatable-table would be best suited as displayed in your screenshot instead of subform.repeatable ( #12634 ).

**Comment by laoneo** [comment]
It looks good on big screens, but as soon as it becomes smaller than 1500 pixels, it get stacked 

image

**Comment by brianteeman** [comment]
@laoneo thats a bug in the template that we have in many places :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13069">issues.joomla.org/tracker/joomla-cms/13069</a>.</sub>

**Comment by Fedik** [comment]
@laoneo try default layout `layout="joomla.form.field.subform.repeatable"` (or just remove the `layout` attribute) instead of the table `layout="joomla.form.field.subform.repeatable-table"` layout

**Comment by laoneo** [comment]
That one uses too much space. I'm close to make on which uses the default, but puts the name and keys on one line.

**Comment by Fedik** [comment]
I wondered why do you have: "**label  input**" in the table cell, it should be just: "**input**", 
when `groupByFieldset="false"` (that is default), then the table width would be  twice smaller

hm, ok, [there](https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/subform/repeatable-table/section.php#L27) should be `<?php echo $field->input; ?>` instead of `<?php echo $field->renderField(); ?>`

**Comment by laoneo** [comment]
@Fedik true, created PR #13093 which adresses this issue, so we leave this one as it is and when the other PR got merged, then this one will look automatically better as well.

**Comment by jeckodevelopment** [comment]
@laoneo can you look at the conflict please?
` components/com_fields/layouts/field/prepare/checkboxes.php `

**Comment by laoneo** [comment]
Done, thanks for the hint.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 4310b6cbb8e250d977c8ed425a847d96e08736a3<br /><br />After applying the patch I get the following error when opening an article
> Warning: Invalid argument supplied for foreach() in /libraries/joomla/form/abstractlist.php on line 220
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13069">issues.joomla.org/tracker/joomla-cms/13069</a>.</sub>

**Comment by laoneo** [comment]
Did you test it on a fresh installation? Because the structure has changed, so old data becomes invalid and can produce that error.

**Comment by brianteeman** [comment]
It should have been but I will retest later

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 156c6ea59360243f1e26ff955940f1daf5bdadc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13069">issues.joomla.org/tracker/joomla-cms/13069</a>.</sub>

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 156c6ea59360243f1e26ff955940f1daf5bdadc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13069">issues.joomla.org/tracker/joomla-cms/13069</a>.</sub>

**Comment by laoneo** [comment]
Can we set this one to RTC?

**Comment by dgt41** [comment]
RTC

**Pull request merged**
