### PR TITLE
spelling s/sharable/shareable

### PR DESCRIPTION
**Pull request by brianteeman**
The correct spelling in en-GB is shareable

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on abac32aa98efe36be7baaac5ac1a2ab54b54bb85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38772">issues.joomla.org/tracker/joomla-cms/38772</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on abac32aa98efe36be7baaac5ac1a2ab54b54bb85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38772">issues.joomla.org/tracker/joomla-cms/38772</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38772">issues.joomla.org/tracker/joomla-cms/38772</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for fixing that!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
