### PR TITLE
[4.0] Use <meter> for password strength indicator

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #26190
Replaces: https://github.com/joomla/joomla-cms/pull/26430

### Summary of Changes

This changes the element for the password strength indicator from `<div class="progress">` to native `<meter>`, which is the proper semantical element for this scenario.

The JS is now ES6

### Caveats

This will NOT work in IE11 or Android webview

### Notes

This PR does **NOT** change the algorithm of the password strength. Please do not raise any issues saying you can type in an insecure password.

This PR uses the browsers native styling for the element, with the exception of setting the width to `100%`. Please do not start discussing the styling here. You can raise a separate issue for that.

### Testing Instructions

1. Run `node build.js --compile-js` and `node build.js --compile-css` from your terminal.
2. Go to `administrator/index.php?option=com_users` and a user
3. Start typing in a password

### Result

The meter element indicates the strength of the password

screeny

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@C-Lodder I wish you could resurrect https://github.com/joomla/joomla-cms/pull/23215 here as there are patched much more things (eg the input is decoupled from Font Awesome, etc)

**Comment by C-Lodder** [comment]
@dgrammatiko 

> I’m not merging new custom elements until the existing ones stabilise which is why this has sat there

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 730634807fc118f47c08869d5a89d2c7b4722c27<br /><br />Definite improvement - thanks

Also checked to make sure it works correctly when prefers-reduced-motion is set - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29041">issues.joomla.org/tracker/joomla-cms/29041</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 730634807fc118f47c08869d5a89d2c7b4722c27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29041">issues.joomla.org/tracker/joomla-cms/29041</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29041">issues.joomla.org/tracker/joomla-cms/29041</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks!

**Pull request merged**
