### PR TITLE
[4.0] Add missing class attribute

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #36277.

### Summary of Changes
Add missing class attribute. See https://github.com/joomla/joomla-cms/issues/36277 for issue description.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/36277, confirm the issue. Apply patch, confirm the issue fixed.

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on d8efd83515313a20539d9f7fbb6f5ce5f2ce5da0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36288">issues.joomla.org/tracker/joomla-cms/36288</a>.</sub>

**Comment by tecpromotion** [comment]
The error already occurs in 4.0.5-rc3 @wilsonge.

https://github.com/joomla/joomla-cms/blob/bfaf93134112b1d4befb607647a65fec2dd7fa9b/layouts/joomla/form/field/radio/buttons.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L82

**Comment by Quiviro** [comment]
I have tested this item :white_check_mark: successfully on d8efd83515313a20539d9f7fbb6f5ce5f2ce5da0<br /><br />In v4.0.5-rc1 and v4.0.5-rc3 the issue is fixedissue fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36288">issues.joomla.org/tracker/joomla-cms/36288</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36288">issues.joomla.org/tracker/joomla-cms/36288</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
