### PR TITLE
Unify the backend menu entries for users and content thanks @Open2logic

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for part of the Issue https://github.com/joomla/joomla-cms/issues/15334#issuecomment-294617395

### Summary of Changes

add seperators and move them into a logical order

### Testing Instructions

apply this PR and confirm the expected sceenshots

### Expected result

image

&&

image

### Actual result

screen shot 2017-04-17 at 22 40 04

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 34ebbe769504d94dc649c35642ce355955a5191e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 34ebbe769504d94dc649c35642ce355955a5191e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Review by Open2logic — APPROVED** [review]

**Comment by Open2logic** [comment]
Sorry, an observation.
The left side slider should have the same order as the options shown in the top menu and the same names.
And it would be perfect if the line of separation was also used.

screen shot 2017-04-23 at 16 50 00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Comment by zero-24** [comment]
Should be fixed with the last commit @Open2logic please check.

**Comment by franz-wohlkoenig** [comment]
@zero-24 Fixed, some Differences stay like 

- "Access Levels" in Dropdown vs. 
- "Viewing Access Levels" in Sidebar.

**Comment by Open2logic** [comment]
I have tested this item :white_check_mark: successfully on dc9dbf3f7873386fc8a0b00b046c434de071e8eb<br /><br />Ok the order.
The same name for the same function is important for usability.

A question.
Why "Media" does not appear in the sidebar of the Content?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Comment by brianteeman** [comment]
> Why "Media" does not appear in the sidebar of the Content?

It is a misconception that the sidebar is the same as the menu. Also if media was to appear on the sidebarthen by the same logic there should be a sidebar on the media manager

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on dc9dbf3f7873386fc8a0b00b046c434de071e8eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15468">issues.joomla.org/tracker/joomla-cms/15468</a>.</sub>

**Comment by Open2logic** [comment]
I think the same thing about showing different things, but many users barely see differences between the sidebar and the menus.
Would the sidebar be the perfect place for Search tools?

**Comment by brianteeman** [comment]
> Would the sidebar be the perfect place for Search tools?

no

**Pull request merged**
