### PR TITLE
[com_fields] Trigger onContentPrepare in news module

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #13705.

### Testing instructions
- Create some custom fields for articles
- Edit an article
- Create a news flash module
- Make an override
- Check if the articles do have a $item->fields property available

### CODE REVIEW

**Comment by zero-24** [comment]
Can you please add a quick test example?

**Comment by Bakual** [comment]
Just a stupid question, do we still need the `$item->introtext = JHtml::_('content.prepare', $item->introtext, '', 'mod_articles_news.content');` then? Because that one afaik triggers the same event but only with the introtext instead of the full item.

**Comment by laoneo** [comment]
Guess not.

**Comment by coolcat-creations** [comment]
tested with and without`$item->introtext = JHtml::_('content.prepare', $item->introtext, '', 'mod_articles_news.content');` and it works.

**Comment by Bakual** [comment]
You would have to test if content plugins tags within that introtext are still correctly replaced. That's what the content.prepare event usually does take care of.

**Comment by coolcat-creations** [comment]
It doesn´t work then - thank you for explaining the context

**Comment by coolcat-creations** [comment]
That´s for testinginstructions:

Include: 
`
<?php

// Article-Fields Mapping

foreach ($item->fields as $field) {
	$item->fieldalias[$field->alias]=$field->id;
}

$itemfield = $item->fieldalias;


//	User-Fields Mapping

foreach ($user->fields as $field) {
	$user->fieldalias[$field->alias]=$field->id;
}

$userfield = $user->fieldalias;

?>

<p><?php echo $item->fields[$itemfield['superfield']]->value; ?></p>
<p><?php echo $user->fields[$userfield['authorinfo']]->value; ?></p>
`
in your Newsflash module override (replace superfield and authorinfo with the alias of the fields you created and filled (one for the user one for the article).
See if the field contents are displayed.

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on c1e64da27f759d19c370f6333f77cf0b03507948<br /><br />Tested successful with the article fields, if it gets merged i´d add the user fields for displaying authorinformation in another PR. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13708">issues.joomla.org/tracker/joomla-cms/13708</a>.</sub>

**Comment by laoneo** [comment]
I'v updated the test instructions, can the label being removed please, or merge by review as it is a small change only.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 9d6a379a54b98565ceef7945a6de22bf22b67fb9<br /><br />After Override of "mod_articles_news" fields are shown in Module. Can't find `$item->fields` in Override-Folder in default.php, horizontal.php, vertical.php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13708">issues.joomla.org/tracker/joomla-cms/13708</a>.</sub>

**Comment by laoneo** [comment]
Thanks to the testers. Can be set to RTC.

**Comment by laoneo** [comment]
Somehow the tests disappeared on the issue tracker item.

**Comment by mbabker** [comment]
The tests are logged against the last commit from the PR.  So when you push a new commit, it "resets" the state.  The logic is people are testing a pull request at a given state so if you make changes those tests don't include those changes.

**Comment by laoneo** [comment]
I just did some code styling in my last commit and the label RTC is set. So I guess all is good. Thanks for the answer.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
