### PR TITLE
[4.0] Fix retrieving articles for contact

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31104.

### Summary of Changes

Fixes some errors in the query.

### Testing Instructions

Create a contact. Assign an user to contact.
Assign some articles to user.
Create single contact menu item.
Enable `User Articles` option in the menu item.
View the menu item in frontend.

### Actual result BEFORE applying this Pull Request

Some query errors.

### Expected result AFTER applying this Pull Request

No query errors and user articles are shown under contact form.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8ebc7a3b5ea83ddc2830780a424bdb1b7ca73d1c<br /><br />Fixes both select and articles retrieve. tks

remains the display but it is a separate issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31107">issues.joomla.org/tracker/joomla-cms/31107</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8ebc7a3b5ea83ddc2830780a424bdb1b7ca73d1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31107">issues.joomla.org/tracker/joomla-cms/31107</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31107">issues.joomla.org/tracker/joomla-cms/31107</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
