### PR TITLE
[4.3] Fix banner pinned tooltip to show the action to perform

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #34566.

### Summary of Changes
The Pinned tooltip displays the pinned state when it should display the action to perform.

### Testing Instructions
Go to Components >Banners
Hover over an icon under the Pinned column.

### Actual result BEFORE applying this Pull Request
122637306-249d1400-d0ee-11eb-87ec-a1e272c3569e

### Expected result AFTER applying this Pull Request
unpin-banner-tooltip

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b41d35cfd93ea1460a8d5def20b0bc8ea4b604d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40078">issues.joomla.org/tracker/joomla-cms/40078</a>.</sub>

**Comment by brianteeman** [comment]
we really need a consistent approach to these messages

**Comment by sdwjoomla** [comment]
I have tested this item :white_check_mark: successfully on b41d35cfd93ea1460a8d5def20b0bc8ea4b604d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40078">issues.joomla.org/tracker/joomla-cms/40078</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40078">issues.joomla.org/tracker/joomla-cms/40078</a>.</sub>

**Comment by obuisard** [comment]
Thanks @Quy !

**Pull request merged**
