### PR TITLE
[5.1] spinner support for color schemes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #43014 .

### Summary of Changes

- Add support for dark/light modes

### Testing Instructions

Follow the instructions on the linked issue

### Expected result AFTER applying this Pull Request
Screenshot 2024-03-13 at 23 35 11

Screenshot 2024-03-13 at 23 35 31

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
what was wrong with #43018

**Comment by dgrammatiko** [comment]
Your PR is valid and affects one view but doesn't touch the background color of the spinner.
This PR adapts the spinner to the dark/light convention already introduced in another PR. The spinner is used in many places like article edit view if you change a category and there are some custom fields...

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c9c7ce065bcb90c2f2baf0a6343cfefd3ee69a9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43023">issues.joomla.org/tracker/joomla-cms/43023</a>.</sub>

**Comment by Quy** [comment]
The logo is huge when installing a sample data.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6a79403e78e64c0308be61bb5b106b6487748c38<br /><br />Beautiful! Thank you!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43023">issues.joomla.org/tracker/joomla-cms/43023</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6a79403e78e64c0308be61bb5b106b6487748c38<br /><br />👌<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43023">issues.joomla.org/tracker/joomla-cms/43023</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
