### PR TITLE
Updates for the new downloads Portal

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

https://www.joomla.org/announcements/general-news/5691-joomla-downloads-website.html

### Testing Instructions

Please review

Fixing conflicts is planed for this afternoon.

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry I created conflicts

**Comment by zero-24** [comment]
No problem you can not know that this was prepared ;)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on e148f8495e42a374c0778acfd370ad19a1def72d<br /><br />On code review.

So finnaly the ".html" suffix goes away :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12707">issues.joomla.org/tracker/joomla-cms/12707</a>.</sub>

**Comment by zero-24** [comment]
I have just fixed the conflicts

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d9b8d77f3ff3daefb92d99797b88b9b278237506<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12707">issues.joomla.org/tracker/joomla-cms/12707</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d9b8d77f3ff3daefb92d99797b88b9b278237506<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12707">issues.joomla.org/tracker/joomla-cms/12707</a>.</sub>

**Comment by zero-24** [comment]
Thanks 👍

**Pull request merged**
