### PR TITLE
[4.0] Add index language to finder_terms

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Add index language to finder_terms

### Testing Instructions
Make a fresh installation. 
Go to settings or to administrator/index.php?option=com_installer&view=database

### Expected result
No database Error

### Actual result
install-database

### CODE REVIEW

**Comment by infograf768** [comment]
@Hackwar

**Comment by Hackwar** [comment]
Could you make this change against the branch of this PR here? #20561 I fixed a few other things in there, too.

**Comment by hardik-codes** [comment]
@chmst may I do this for you?

**Comment by chmst** [comment]
@hardik-codes yes, please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24204">issues.joomla.org/tracker/joomla-cms/24204</a>.</sub>

**Comment by Quy** [comment]
Fixed in PR #20561<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24204">issues.joomla.org/tracker/joomla-cms/24204</a>.</sub>

**Pull request closed without merging**
