### PR TITLE
Regression: com_modules batch positions and hathor client select

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Solves regressions:
- In batch modal the positions are not selected based on the client id
- In hathor we can't select the client in modules view (it always goes back to Site)
#### Testing Instructions
1. Apply this patch in latest staging
2. Do a batch with client site in modules (check the positions in batch are from site templates)
3. Do a batch with admins site in modules (check the positions in batch are from admin templates)
4. Change the admin template to hathor. Try to change between client and admin modules.

Note: you can check that without the patch they are incorrect.

### CODE REVIEW

**Comment by richard67** [comment]
@andrepereiradasilva Testing instructions are IMO not precise.

> In hathor we can't select the client in modules view (it always goes back to Site)

In fact we can select the admin site, i.e. the modules which are shown are the admin ones, only the dropdown value changes back to "Administrator".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva Sorry, mistake in my post above, I mean the dropdown changes back to "Site".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva But I think you know what I mean. It's only the dropdown value changing back erroneously, not the displayed modules list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 669b08a7018d503a197d159f0f48aad4870650bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on 99866abd86df4edfd190ff81639b6ade6e6c9e43<br /><br />Issue confirmed: before patch, client always set back to "site" and no batch possible on admin modules, in Hathor template.
On Isis, all is working good before and after patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 99866abd86df4edfd190ff81639b6ade6e6c9e43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Comment by infograf768** [comment]
Good find. For 3.5.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9994">issues.joomla.org/joomla-cms/9994</a>.</sub>

**Pull request merged**
