### PR TITLE
Remove redundant words

### PR DESCRIPTION
**Pull request by brianteeman**
Remove **just** from strings  … it is a redundant word and is subjective.

> “Just” makes me feel like an idiot. “Just” presumes I come from a specific background, studied certain courses in university, am fluent in certain technologies, and have read all the right books, articles, and resources. “Just” is a dangerous word. http://bradfrost.com/blog/post/just/

Also removes **easily** and **simply** as they are also redundant and subjective

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2b98d37627f29466b34e37a4809d8013b5040353<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18852">issues.joomla.org/tracker/joomla-cms/18852</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2b98d37627f29466b34e37a4809d8013b5040353<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18852">issues.joomla.org/tracker/joomla-cms/18852</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
