### PR TITLE
[5.1] Trailing Slash: Don't remove slash when it's the only path char

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #43069.

### Summary of Changes
When the site runs in the root of the domain and the path is empty, because the URL is entirely query parameters, the slash to make the URL relative to the root folder is removed, resulting in the URL becoming relative to the current URL. This PR makes an exception for this special case. 

### Testing Instructions
1. In the System - SEF plugin set to remove trailing slash.
2. Create an article in the uncategorised category.
3. Click on the Preview button.

### Actual result BEFORE applying this Pull Request
Either no modal is displayed or an error page is shown instead. (When the article is alternatively the homepage, the URL is completely empty, resulting in a JS error.)

### Expected result AFTER applying this Pull Request
The preview is properly displayed.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
These test instructions are not enough to replicate the problem and therefore test the fix

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on 994862575d128a4e6c5907e4dd1227241c6a1a68<br /><br />I've replicated the issue as described in #43069 and tested the patch in various scenarios:

* Non-Multilanguage site without sef in domain root
* Non-Multilanguage site with sef in domain root
* Multilanguage site in with sef domain root
* Multilanguage site in without sef domain root
* Non-Multilanguage site without sef in subdirectory
* Non-Multilanguage site with sef in subdirectory
* Multilanguage site in with sef in subdirectory
* Multilanguage site in without sef in subdirectory

The patch worked in all scenarios.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43074">issues.joomla.org/tracker/joomla-cms/43074</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 994862575d128a4e6c5907e4dd1227241c6a1a68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43074">issues.joomla.org/tracker/joomla-cms/43074</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43074">issues.joomla.org/tracker/joomla-cms/43074</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Hackwar and also for testing and review @SniperSister @viocassel

**Pull request merged**
