### PR TITLE
support Multi path for controller

### PR DESCRIPTION
**Pull request by mvanvu**
Thanks for great Joomla! MVC structure. The suggest for support multi base path for JControllerLegacy.
My solutions are create a method addIncludePath and custom the method getInstance.
Here is the example for test. https://github.com/mvanvu/com_hello
description: com_hello just has a view hello in the backend and frontend. So the plugin comment will provide new views comment list and add new comment for the both frontend and backend. 
P/s: com_hello just test for this request.

### CODE REVIEW

**Comment by wojsmol** [comment]
@mvanvu See https://github.com/mvanvu/joomla-cms/pull/1

**Comment by franz-wohlkoenig** [comment]
@mvanvu Can you please write how to test this PR?

**Comment by RonakParmar** [comment]
@mvanvu  Can you please provide steps to test this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8474">issues.joomla.org/tracker/joomla-cms/8474</a>.</sub>

**Comment by mvanvu** [comment]
@RonakParmar  Please see com_hello https://github.com/mvanvu/com_hello. As default the com_hello has two views (hellos and hello) and the plugin comment (https://github.com/mvanvu/com_hello/tree/master/admin/plugin/comment) which provides more views by use JController::addIncludePath.

**Comment by zero-24** [comment]
@mvanvu can you fix the merge conflicts and allow maintainer edit?

**Comment by GeraintEdwards** [comment]
Is this PR actually necessary to achieve what you want.
Can you not  use 

JControllerLegacy::getInstance("Content", array("model_prefix" => "yourmodelname", "model_path" => __DIR__ . "/models/"));
 
or if you have n instance already 

$controller->addViewPath( " your new path ");

or 

JModelLegacy::addIncludePath 
 
etc.

@nibra I would suggest closing this in 1 week if there is no response

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8474">issues.joomla.org/tracker/joomla-cms/8474</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Pull request closed without merging**
