### PR TITLE
Media Manager-validation required on delete button

### PR DESCRIPTION
**Pull request by jainrimjhim20**
mediamanager

### CODE REVIEW

**Comment by Hackwar** [comment]
There is an error in the unittests with your changes. Please see if you can fix those.

**Comment by wilsonge** [comment]
I can't see anything wrong with this - removing from needs review. Can I have one test here to confirm the patch is still required and works as expected before it goes RTC please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by brianteeman** [comment]
@wilsonge is the comment about unit tests no longer valid either?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by wilsonge** [comment]
I don't think so. There are no unit tests failing with this and there are none covering this kinda stuff anyhow. I think Dmitris will throw a small hissy fit about using script tags rather than using JDocument but given the age of this PR i"d rather merge this if it works and then get him to do that separately

**Comment by MATsxm** [comment]
success with BEFORE:
screen shot 2016-04-12 at 18 15 51

then AFTER:
screen shot 2016-04-12 at 18 16 19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 97f89dcec744192179f03ff4a98e44fa1915b65f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 97f89dcec744192179f03ff4a98e44fa1915b65f<br /><br />For consistency this is correct.

Personally this type of functionality should be labelled "you are an idiot why did you click without selecting"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by brianteeman** [comment]
RTC 
Not a new feature as this functionality is present everywhere else so setting 3.5.2 milestone<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by rdeutz** [comment]
@rbsl-rimjhim could you check the merge conflicts, thanks

**Comment by wilsonge** [comment]
Robert as this PR is 18 months old think this is one of those cases where we can do it ourselves ;)

**Comment by rdeutz** [comment]
Feel free to do it :-P

**Comment by brianteeman** [comment]
I will do it now

**Comment by brianteeman** [comment]
See #9891 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4777">issues.joomla.org/joomla-cms/4777</a>.</sub>

**Comment by wilsonge** [comment]
Merged #9891

**Pull request closed without merging**
