### PR TITLE
[4.0] [com_workflow] Parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Converts to parameterized queries.

### Testing Instructions

Use com_workflow in every way possible.
Create/edit/delete workflows/stages/transitions.
Use filter and ordering options in list views.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ How is that related to the PR #29207 you've referenced in the description? Or is it maybe a typo?

**Comment by SharkyKZ** [comment]
Some typo.

**Comment by Quy** [comment]
Searching in Transitions returns no results. This is the same without this PR.

**Comment by SharkyKZ** [comment]
@Quy please test PR https://github.com/joomla/joomla-cms/pull/29643.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54466e49477b496c0d59d39dac2b3afb8df85093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29633">issues.joomla.org/tracker/joomla-cms/29633</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 121bb31d73c30539dd97fba28b415cba9d87da2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29633">issues.joomla.org/tracker/joomla-cms/29633</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29633">issues.joomla.org/tracker/joomla-cms/29633</a>.</sub>

**Comment by richard67** [comment]
Test result of Quy was still valid because merge after that was just update to base branch.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
