### PR TITLE
[4.2] Remove obsolete db reference in featured view

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Removes an obsolete reference in the featured front end view. It was used for last visit date from #11396. During Joomla 4 development the code which was using the database got removed so we can remove the reference in the view too.

### Testing Instructions
- Create an article with featured state
- Open the front end

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e93cca8a87cbb56a17ba6fbf03089330bec816d8<br /><br />Tested successfully in Joomla 4.2.0-alpha2-dev of 22 April in Wampserver using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37608">issues.joomla.org/tracker/joomla-cms/37608</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on e93cca8a87cbb56a17ba6fbf03089330bec816d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37608">issues.joomla.org/tracker/joomla-cms/37608</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37608">issues.joomla.org/tracker/joomla-cms/37608</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
