### PR TITLE
[4.3] Guided Tours - Eliminate tour blur event errors

### PR DESCRIPTION
**Pull request by GeraintEdwards**
Resubmission of PR #41159 for Joomla 4.3 instead

When you complete a tour and then interact with a targeted element the blur event listener is still attached and throws a javascript error

Pull Request for Issue # .

### Summary of Changes

Check there is a tour active before attempting to focus on the tour step buttons

### Testing Instructions

Run a tour e.g. How to create a menu item - cancel the tour before completing the title step  (the same problem can exist in a completed tour).

Click in the 'title' field and then move it out (i.e. fire a blur event) the view the javascript console

### Actual result BEFORE applying this Pull Request

Screenshot from 2023-07-14 10-44-22

Screenshot from 2023-07-14 10-44-31

Screenshot from 2023-07-14 10-44-43

### Expected result AFTER applying this Pull Request

No error message in the console.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 753db7a315ecf3c3fd46878ba62f661c2cd9505f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41160">issues.joomla.org/tracker/joomla-cms/41160</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 753db7a315ecf3c3fd46878ba62f661c2cd9505f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41160">issues.joomla.org/tracker/joomla-cms/41160</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 753db7a315ecf3c3fd46878ba62f661c2cd9505f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41160">issues.joomla.org/tracker/joomla-cms/41160</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41160">issues.joomla.org/tracker/joomla-cms/41160</a>.</sub>

**Comment by obuisard** [comment]
Thank you Geraint @GeraintEdwards for the PR!

**Pull request merged**
