### PR TITLE
com_templates - Moved Filters from sidebar to Search Tools

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves the Filter fields from the left Sidebar to Search Tools in the middle column.
# Testing instructions
## Before PR: Extensions > Templates > Styles

The left Sidebar has 2 filter options: Select Template & Select Location ("site/administrator")

template_styles_before
## After PR: Extensions > Templates > Styles

The 2 filter options have been moved to **Search Tools**
and I have changed their order:
Select Location ("site/administrator") & Select Template
**Note**: the listed Templates are not yet dependent on "Location".

template_styles_after
## Before PR: Extensions > Templates > Templates

The left Sidebar has 1 filter option: Select Location ("site/administrator")

template_templates_before
## After PR: Extensions > Templates > Templates

The filter option Select Location ("site/administrator") has been moved to **Search Tools**,
and a List Limit dropdown box has been added.

template_templates_after

### CODE REVIEW

**Comment by pe7er** [comment]
There's a small issue with this PR: The Template filter does not take into account the Location filter.
If you go to Extensions > Templates > Styles, select **"Select Location"** (to select admin or site templates) then the **"Select Template"** will still show **all (admin + site)** templates.

I did not know how to pass the **selected client_id** into the **$options = TemplatesHelper::getTemplateOptions();** function

https://github.com/pe7er/joomla-cms/blob/search-tools-filters-templates/administrator/components/com_templates/models/fields/templatename.php

**Comment by hitchblade** [comment]
Works great and looks good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by watchfulli-dev** [comment]
@test success, after applying the patch, the filters from the right side now appear on top under "Search tools", filters also tested and applying filters works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by zero-24** [comment]
RTC based on tests. Thanks @watchfulli-dev and @hitchblade as well as @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by infograf768** [comment]
I still see a small issue:
When selecting a location the "Select Template" dropdown still lists both site AND admin templates

**Comment by pe7er** [comment]
I am able to reproduce the issue that @infograf768 reported:

In the old situation the options under "Select Template" filter are dependent on the "Select Location" filer. When you select "Site", it only displays the site templates Beez3 + protostar.
template-styles-before

This PR moves the filters to the top. However, the "Select Template" filter is no longer dependent on the "Select Location" filer. When you select "Site", it displays the site templates Beez3 + protostar, but also the admin template Isis + Hathor.
template-styles-after

I'll try to find a solution for that.
Thanks @infograf768 !

**Comment by zero-24** [comment]
back to pending :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by pe7er** [comment]
I solved it by adding a check for client_id filter. That client_id value is passed to the helper file.

/administrator/components/com_templates/models/fields/templatename.php
$clientId = JModelList::getUserStateFromRequest('.filter.client_id', 'filter_client_id', null);
$options = TemplatesHelper::getTemplateOptions($clientId);

Can someone please double check if this is a correct solution?

**Comment by RemcoJanssen** [comment]
I have tested this item :white_check_mark: successfully on 175546b277c157bca28ef66f1256a165639597af<br /><br />Works like a charm!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by n9iels** [comment]
@test The following error showed up at the styles view when expend the search tools:
`Deprecated: Non-static method JModelList::getUserStateFromRequest() should not be called statically, assuming $this from incompatible context in C:\MAMP\htdocs\joomla-cms\administrator\components\com_templates\models\fields\templatename.php on line 40`

**Comment by pe7er** [comment]
Thanks for tesing @RemcoJanssen & @n9iels. 

I've to dig into the deprecated error later. Travis did not complain about that ;-)
What PHP version do you use Niels?

**Comment by n9iels** [comment]
PHP 5.6.3, with `error_reporting = E_ALL` set in php.ini and the error reporting parameter in global configuration is set on: development

**Comment by pe7er** [comment]
Thanks @n9iels! I was able to reproduce the error and corrected it in my PR.

**Comment by n9iels** [comment]
@test problem solved. Tested successful :)

**Comment by pe7er** [comment]
wow, you are fast! Thanks @n9iels

**Comment by a1d3s** [comment]
works

**Comment by a1d3s** [comment]
I have tested this item :white_check_mark: successfully on 08def4c60fb51b67da07a78f8322a0a0f96dc469<br /><br />works good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by sriva113** [comment]
Successfully tested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by sriva113** [comment]
Filtering still doesn't work<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by wombel2000** [comment]
If you select "selected Template" you can't see the admin Tenplate
as you schould.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by wombel2000** [comment]
Picture to the previous coment!screen shot 2015-10-24 at 05 22 40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by jduerscheid** [comment]
I have tested this item :red_circle: unsuccessfully on 08def4c60fb51b67da07a78f8322a0a0f96dc469<br /><br />@pe7er: Test unsucessfully, there is an error in the search tool, area Select Template, I miss the admin templates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by jduerscheid** [comment]
Screenshot to previous post

screen shot 2015-10-24 at 07 36 38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by yvesh** [comment]
Yes, like @jduerscheid said the admin templates are missing. (Joomla 3.5.6-dev)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :red_circle: unsuccessfully on 08def4c60fb51b67da07a78f8322a0a0f96dc469<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by pe7er** [comment]
I've updated this PR with staging but could not solve the reported issue. 

I was able to reproduce the error with 
Extensions > Templates > Styles > Filter on "Location = Administrator",
"Select Templates" won't show Admin templates, only Site templates.

I have an issue with this part in /administrator/components/com_templates/models/fields/templatename.php
$app = JFactory::getApplication();
**$clientId** = $app->getUserStateFromRequest('.filter.client_id', 'filter_client_id', null);
$options = TemplatesHelper::getTemplateOptions(**$clientId**);

I am not able to retrieve the $clientId that needs to be passed to the getTemplateOptions.
0 = Site, 1= Admin, but $clientId is always totally empty.
I hope that someone spots the cause of the issue....

**Comment by pe7er** [comment]
Sorry, I pressed the wrong button (Close and comment) so I had to reopen it..

**Comment by pe7er** [comment]
I've corrected the "Location = Administrator" -> "Templates" dropdown did not show Admin templates issue with help from @roland-d. Thanks Roland!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on ecdcf0cf59c51e03ad1d21cf70e8a28cd63ac9d8<br /><br />Works now. Thanks @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on ecdcf0cf59c51e03ad1d21cf70e8a28cd63ac9d8<br /><br />Works as described! -> RTC

Thank you @pe7er!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7701">issues.joomla.org/joomla-cms/7701</a>.</sub>

**Pull request closed without merging**
