### PR TITLE
[4.0] Align Batch label in Actions dropdown

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Replace Fontawesome icon to fix Batch label alignment in Actions dropdown

### Testing Instructions
Go to Content > Articles
Select an article
Click `Actions` dropdown
`Batch` is misaligned

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 964ed863f9846bea2967c813e068edaf78f488d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26053">issues.joomla.org/tracker/joomla-cms/26053</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 964ed863f9846bea2967c813e068edaf78f488d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26053">issues.joomla.org/tracker/joomla-cms/26053</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26053">issues.joomla.org/tracker/joomla-cms/26053</a>.</sub>

**Comment by C-Lodder** [comment]
The whole point of the `icon-xxx` class in J4 was to prevent B/C breaks for extension developers who are still using Icomoon.

`icon-xxx` classes in J4 are just wrappers for the `fa-xxx` class.

So the fact that there is misalignment with one of the icons, means there is a bug within the dropdown SCSS. The icon doesn't need changing.

**Comment by infograf768** [comment]
Removing RTC after @C-Lodder comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26053">issues.joomla.org/tracker/joomla-cms/26053</a>.</sub>

**Comment by brianteeman** [comment]
@C-Lodder says this is not the correct fix and anyway there are other instances of the fa-square icon not addressed

**Comment by brianteeman** [comment]
see #26056

**Pull request closed without merging**
