### PR TITLE
Feature/3 users

### PR DESCRIPTION
**Pull request by craftysyntax**
#3  Removed Mass Mail and User Notes

### CODE REVIEW

**Comment by brianteeman** [comment]
@manuman did you mean to submit this PR here?

**Comment by manuman** [comment]
@brianteeman Nope... my bad

**Comment by brianteeman** [comment]
@manuman You just had to press close on the pull request ;)
I've done it for you. Better luck next time - you'll get the hang of this developing lark eventually

**Comment by manuman** [comment]
Ah.. saw that button but it was red. I'm wary of red buttons. Thanks! :D

**Pull request closed without merging**
