### PR TITLE
[4.0] add input validation pattern copied from DatabaseHelper

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

This PR will perform HTML5 validation on installation input field `db_name`.
It is in Joomla for DB type = MySQL or MySQLi not allowed to use a period in the database name. 

see the current check in installation DatabaseHelper
https://github.com/joomla/joomla-cms/blob/1b5cc365bce5b3c7fcf921e9db193058fa3c3ff6/installation/src/Helper/DatabaseHelper.php#L240-L243

### Testing Instructions

- Follow Joomla installation instructions for J4 on https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment
- When you fill the input field `db_name` use a name with a period => example : `joomla.joomla4.install`
- Continue filling the form and press button _Setup Database Connection >_
- The form does not continue... seemingly without any warning

- apply this PR
- run `npm run build:js` and press button _Setup Database Connection >_ again.... the form will not continue, but extended with a error message nearby the input field `db_name`

### Actual result BEFORE applying this Pull Request

Schermafdruk 2020-08-02 19 30 18

The attribute `aria-invalid` of field db_name field will remain `false` (instead of `true`) and the className of the wrapping `form-group` will remain `has-success` instead of `has-danger`. The Joomla core form-validator.js does not interfere.

Scroll to the top of the page to see the warning. 
Schermafdruk 2020-08-02 19 30 47

### Expected result AFTER applying this Pull Request

When applying this PR the Joomla form-validator.js will interfere and HTML5 logic will be applied. Attribute `aria-invalid` will change from `false` into `true` and the className of the wrapping `form-group` will change from `has-success` into `has-danger`. Since there is no title attribute provided on this input field, the browser default message will appear. 

Schermafdruk 2020-08-02 20 27 03

### CODE REVIEW

**Comment by richard67** [comment]
If I get it right, this PR enforces the rule which is meant for MySQL(i) only also for PostgreSQL.

**Comment by hans2103** [comment]
@richard67 you are right.
The proposed solution is not correct... but the issue remains. 
What's next? The pattern should be removed I guess and another solution has to be written. 
Anyone a suggestion for a proper solution?

**Comment by brianteeman** [comment]
Am I correct in assuming that the problem you are trying to resolve is the positioning of the error message?

**Comment by hans2103** [comment]
> Am I correct in assuming that the problem you are trying to resolve is the positioning of the error message?

Or scroll the error message into view. 
As you can see on the code of the current implementation it only returns a message.
It does not change the attributes `aria-invalid` (from false to true) nor does it change the className `has-success` into `has-danger`. 
https://github.com/joomla/joomla-cms/blob/1b5cc365bce5b3c7fcf921e9db193058fa3c3ff6/installation/src/Helper/DatabaseHelper.php#L240-L243

**Comment by brianteeman** [comment]
I agree that you have identified a genuine problem. However html5 validation is not the way to go as I have been regularly told.

**Comment by hans2103** [comment]
> I agree that you have identified a genuine problem. However html5 validation is not the way to go as I have been regularly told.

@brianteeman can you explain me why HTML5 form validation is not the way to go?

**Comment by hans2103** [comment]
@quy merged branch 4.0-dev changes into my PR

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/pull/30261#issuecomment-667710395 so it should be set to Draft?

**Comment by hans2103** [comment]
@quy you are right.. please set to Draft

**Comment by hans2103** [comment]
I didn't manage to find a solution to check both MySQL(i) only also for PostgreSQL other then implementing two new fields:

- db_name-mysql => will appear when selecting DB type = MySQL
- db_name-postgressql => will appear when selecting DB type = PostgresSQL

and after valid input they will fill hidden field db_name

That was what I was thinking about could be a solution to use HTML5 form validation.
Would that be a proper solution?

**Comment by richard67** [comment]
> I didn't manage to find a solution to check both MySQL(i) only also for PostgreSQL other then implementing two new fields:
>     * db_name-mysql => will appear when selecting DB type = MySQL
>     * db_name-postgressql => will appear when selecting DB type = PostgresSQL
> 
> and after valid input they will fill hidden field db_name
> That was what I was thinking about could be a solution to use HTML5 form validation.
> Would that be a proper solution?

That could be indeed the only possible way since we don't have something like "showon" for controlling if something is shown also for the rules, i.e. control by field values of field x the validation rules of field y.

**Comment by richard67** [comment]
P.S.: But I'm not sure if it needs the hidden field, or if that would not even open a security hole. If you store the validated value and assume the value in the hidden field is validated when using it on server side, one might hack that by modifying the hidden field value with broswer tools at the right time. So maybe on server side there should be a check which of these fields to be used when doing the server-side validation? I could help with info where to find that, if necessary.

**Comment by hans2103** [comment]
Closing this issue, since I don't know how to solve this.

**Pull request closed without merging**
