### PR TITLE
[4.0] Improve text in batch modal

### PR DESCRIPTION
**Pull request by Quy**
Alternate to #24817.

### Summary of Changes
Make Copy/Move label consistent with other labels.

### Testing Instructions
Content > Articles > select some articles > click on Batch
Select a category so that the Copy / Move question is shown.

The radio buttons will be fixed if this is approved.

### Expected result
batch

### CODE REVIEW

**Comment by alikon** [comment]
it isn't the word "Action to perform" a little bit misplace/misaligned to the rest of the modal ?

**Comment by chmst** [comment]
Do we need this question? I think Copy / Move is self explaining and dos not need an extra label. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on d3192ed76175b2add7259fce17660bebc33a3d9a<br /><br />Tested the text change successfully.
It shows a different problem....

Now the text is shorter the flex layout puts logically the radio buttons at the end of the text.
Without this change we would probably also have this issue in certain languages. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by alikon** [comment]
for me we don't need this, but if we need this  for newbies then it should be aligned properly

**Comment by conconnl** [comment]
I don't think it matters that we need this specific text in English.
Shortening the text shows an alignment issue, which can easily become an issue report when certain language shows a short text.

So, the aligning needs to be done first, no matter of the text.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on d3192ed76175b2add7259fce17660bebc33a3d9a<br /><br />This works as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by chmst** [comment]
Please see PR #28577 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on d3192ed76175b2add7259fce17660bebc33a3d9a<br /><br />Tested successful in combination with ##28577
The text is correctly updated and the radio group is perfectly aligned.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by brianteeman** [comment]
I do not agree with this change to JLIB_HTML_BATCH_MOVE_QUESTION
Changing the length of the text in english for layout purposes is wrong as we have no way of knowing how long or short the text will be in other languages.

I do agree with changing the order of the words in the text to match the order of the radio.

**Comment by Quy** [comment]
How about changing `JLIB_HTML_BATCH_MOVE_QUESTION` to `Action` or assign it `sr-only` so it does not display?

**Comment by chmst** [comment]
Please check again #28577. 
With this change, length of text does not matter, as we never know how it is translated in other languages.

**Comment by wilsonge** [comment]
So #28577  has been merged - believe this means we can now handle `JLIB_HTML_BATCH_MOVE_QUESTION` better?

**Comment by faustonenci** [comment]
Cattura
I have tested this item :white_check_mark: successfully on d3192ed76175b2add7259fce17660bebc33a3d9a<br /><br />good

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28447">issues.joomla.org/tracker/joomla-cms/28447</a>.</sub>

**Comment by ghost** [comment]
RTC?

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
