### PR TITLE
4.0 Custom articles Fields. 

### PR DESCRIPTION
**Pull request by Reijo83**
Hello Joomla! team.
I made one homepage where I used Joomla! Custom articles fields. From my perspective, I saw two shortcomings in Custom fields.

1. Since we can make Custom Fields groups then every field assigned to a group should be grouped when we display it on the website.
Currently html is something like that:
```
<dl class="fields-container">
    <dd class="field-entry"></dd>
    <dd class="field-entry"></dd>
    <dd class="field-entry"></dd>
    <dd class="field-entry"></dd>
    <dd class="field-entry"></dd>
</dl>
```
But I think this is better:
```
<dl class="fields-container">
    <div class="fields-group">
        <dd class="field-entry"></dd>
        <dd class="field-entry"></dd>
        <dd class="field-entry"></dd>
    </div>
    <div class="fields-group">
            <dd class="field-entry"></dd>
            <dd class="field-entry"></dd>
            <dd class="field-entry"></dd>
    </div>
</dl>
```

2. Second, maybe it would be wise to add a custom class options to the group. This would provide an opportunity to better design different fields
```
<dl class="fields-container">
        <div class="fields-group custom-class1">
            <dd class="field-entry"></dd>
            <dd class="field-entry"></dd>
            <dd class="field-entry"></dd>
        </div>
        <div class="fields-group custom-class2">
                <dd class="field-entry"></dd>
                <dd class="field-entry"></dd>
                <dd class="field-entry"></dd>
        </div>
    </dl>
```

### CODE REVIEW

**Comment by richard67** [comment]
Can it be that you wanted to make this PR for the 4.0-dev branch but you made it for staging branch?

**Comment by Reijo83** [comment]
Hello
Ooh I would like to have this opportunity for joomla 4 or what other people think of this opportunity?
I'm sorry because I don't know where he should go.

**Comment by richard67** [comment]
Maybe someone else can advise? My lunch break is over now.

**Comment by richard67** [comment]
@Reijo83 You made your pull request (PR) with the wrong branch of Joomla CMS.

When you make a PR, you start with a comparison.

The "Comparing changes" view on GitHub allows you to select your branch on the right hand side and the branch on Joomla in which you want to bring in your changes on the left hand side.
When you did that, you have forgotten to change the branch on the left hand side from "staging" to "4.0-dev".

See the following screenshot which shows how it should be correct, and see the red frame in the screenshot to show you what you should change:

Unbenannt

Your mistake is the reason why your PR shows that there are 9009 (ninethousand and nine) changes made by your PR.

To fix that, do following:

1. Close this PR.
2. In GitHub, select your 4.0-dev branch and then use the "Compare" button.
3. Adjust comparison like I have shown in my screenshot above with the red frame.
4. Now use the green "Create pull request" button to create a new pull request.
5. Fill in the description - you can copy it from this PR here.
6. Check in the view of differences below the description that the changes and changed files are qhat you expect.
7. Now you can submitt your PR. There should be as button for this at the bottom.

I hope I could help.

**Pull request closed without merging**
