### PR TITLE
[4.0] Fields/Fields Groups: using translateformat for date fields

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says. 
Some date fields use `text` as field type instead of `calendar` and therefore do not display the date as defined by the language in use.

### Testing Instructions
Install French Language. Switch to French in backend
Create, save and save again a Field Group.
Create, save and save again a Field

### Before patch
Screen Shot 2019-04-01 at 10 40 40

### After patch

Screen Shot 2019-04-01 at 10 49 58

Screen Shot 2019-04-01 at 10 50 53

### CODE REVIEW

**Comment by Bakual** [comment]
The time formatting works fine, however it applies timezone differences twice now.

You need to also remove the code in FieldModel and GroupModel which converts the timezones as that is done by the formfield now.
https://github.com/joomla/joomla-cms/blob/2bdb02a464362efc3e26f442a91d141a2521bf11/administrator/components/com_fields/Model/FieldModel.php#L366-L393
and
https://github.com/joomla/joomla-cms/blob/2bdb02a464362efc3e26f442a91d141a2521bf11/administrator/components/com_fields/Model/GroupModel.php#L339-L363

**Comment by infograf768** [comment]
will do. tks

**Comment by infograf768** [comment]
@Bakual 
Done.

**Comment by infograf768** [comment]
Note: we have the same error in 3.9. The time zone is taken care of in the xmls with `filter="user_utc"` but the models apply the timezone twice.

**Comment by infograf768** [comment]
reverted changes to models as they have first to be done in 3.9 to prevent merge issues.

**Comment by hardik-codes** [comment]
@infograf768 may I do a PR for 3.9 for reverting changes to models

**Comment by infograf768** [comment]
Already done
https://github.com/joomla/joomla-cms/pull/24473

Please test there and here too for translateformat

**Comment by Bakual** [comment]
I think this PR can be closed full as the same changes were done in J3.9.4 (https://github.com/joomla/joomla-cms/pull/23784) and just need to be merged up into J4.
@wilsonge I think you're not yet at 3.9.4 with your upmerge task, right?

**Comment by infograf768** [comment]
You are right. Closing now.

**Comment by wilsonge** [comment]
@Bakual Nope. I'm aiming to reach 3.9.0 alpha some time next week

**Pull request closed without merging**
