### PR TITLE
[4.0] Fix awesomplete dropdown z-index

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #30745 .

### Summary of Changes
Add z-index to awesomplate dropdown

### Testing Instructions
Apply patch and check search dropdown

### Actual result BEFORE applying this Pull Request
Wrong overlay

### Expected result AFTER applying this Pull Request
Correct overlay

### CODE REVIEW

**Comment by wilsonge** [comment]
Screenshot 2021-01-02 at 03 16 07

Visually a bit grim but does the job :)

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 7c4c512ffd01ce6cdbffaa9ff67c4608579e2690<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31827">issues.joomla.org/tracker/joomla-cms/31827</a>.</sub>

**Comment by infograf768** [comment]
@drmenzelit
Could you have a look at the display here? The enormous button near to a small input field is real ugly and not user friendly.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7c4c512ffd01ce6cdbffaa9ff67c4608579e2690<br /><br />Before patch: ugly Search button is on top of long search word. After patch: Search button is below search word.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31827">issues.joomla.org/tracker/joomla-cms/31827</a>.</sub>

**Comment by brianteeman** [comment]
This PR is to solve the z-index issue. This PR does solve the z-index issue. Any other issue about the display of a button is off-topic and should have its own issue/pr

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7c4c512ffd01ce6cdbffaa9ff67c4608579e2690<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31827">issues.joomla.org/tracker/joomla-cms/31827</a>.</sub>

**Comment by drmenzelit** [comment]
@infograf768 , @wilsonge , @brianteeman see PR #31839 for button display

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31827">issues.joomla.org/tracker/joomla-cms/31827</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
