### PR TITLE
[4.0] Re enable some muted code in Finder

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Remove a global var, whoever did this is not my friend (hint: probably I did it)
- Unmute some code that was closing automatically a modal

## Note:  The `Joomla.Modal` API is always on the parent window!!!
(eg if there is an iframe and you need to call it from there you must call it like: `window.parent.Joomla.Modal.getCurrent().close()`)

### Testing Instructions
# Run `npm install` !important

Go to `http://j4.local/administrator/index.php?option=com_finder&view=index`
click on the Index button
The modal SHOULD close automatically at the end of the indexing process

### Documentation Changes Required

No, cleanup

### CODE REVIEW

**Comment by Quy** [comment]
The last message flashes quickly as the modal closes. Is this the desired behavior?

**Comment by dgrammatiko** [comment]
> The last message flashes quickly as the modal closes. Is this the desired behavior?

Might be the globally applied animations, I didn't notice to be honest...

**Comment by snehaM26** [comment]
I have tested this item :red_circle: unsuccessfully on 5fb0a6e8fa2d7c4f9b97be80b3153c61b690e0e1<br /><br />Tested this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by dgrammatiko** [comment]
@snehaM26 dis you run ‘npm I’?

**Comment by snehaM26** [comment]
I have tested this item :red_circle: unsuccessfully on 5fb0a6e8fa2d7c4f9b97be80b3153c61b690e0e1<br /><br />Tested uncessessfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by jaydevingawale** [comment]
I have tested this item :red_circle: unsuccessfully on 5fb0a6e8fa2d7c4f9b97be80b3153c61b690e0e1<br /><br />it is not closing after the indexing is completed but if we hit the window.parent.Joomla.Modal.getCurrent().close() in console it gets closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by dkmkk** [comment]
I have tested this item :white_check_mark: successfully on 0c97f8c5ca6a6c47e710bff851f6621745793f6f<br /><br />I had applied the patch:
I can confirm the expected results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by ahghatol** [comment]
I have tested this item :white_check_mark: successfully on 0c97f8c5ca6a6c47e710bff851f6621745793f6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 0c97f8c5ca6a6c47e710bff851f6621745793f6f<br /><br />Modal closes after index finished.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26618">issues.joomla.org/tracker/joomla-cms/26618</a>.</sub>

**Comment by wilsonge** [comment]
Merging. But we should keep an eye on the animations I guess

**Pull request merged**
