### PR TITLE
[4.0] Media browser rtl

### PR DESCRIPTION
**Pull request by brianteeman**
Various fixes for the media manager when in RTL using css logical properties instead of adding new classes just for rtl. Media breadcrumbs needs some more rtl love but thats for another pr.

### Before
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 10234ea0f9d1b908e0f8f7b7cdb700e30a7a2046<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34830">issues.joomla.org/tracker/joomla-cms/34830</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 10234ea0f9d1b908e0f8f7b7cdb700e30a7a2046<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34830">issues.joomla.org/tracker/joomla-cms/34830</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34830">issues.joomla.org/tracker/joomla-cms/34830</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks all

**Pull request merged**
