### PR TITLE
Fix PHP warning if an old type menus exist

### PR DESCRIPTION
**Pull request by chivitli**
I just noticed that error log on one of my sites quickly grew to over 100 MB. It was always the same error:

_Trying to get property of non-object in /*******/public_html/libraries/cms/component/router/rules/menu.php on line 179._

I was not the only one with this problem, here is a related post on the forum: https://forum.joomla.org/viewtopic.php?t=949743

It would happen for example if when migrating from an old version you had a menu of type "Content Section", and it wouldn't matter that the menu isn't displayed anywhere on the new version. It may happen under some other circumstances as well. The change I made should keep the condition of the if statement unchanged, except that it won't throw an error if the variable is uninitialized.

Pull Request for Issue # .

### CODE REVIEW

**Comment by Davinder222** [comment]
Code first, then explanation.
<?php

rename ("/folder/file.ext", "newfile.ext");

?>

That doesn't rename the file within the folder, as you might assume, instead, it moves the [gomovies](https://gomovies.lol "") file to whatever the PHP working directory is... Chances are you'll not find it in your FTP tree. Instead, use the following:

<?php

rename ("/folder/file.ext", "/folder/newfile.ext");
emark for "php at stock-consulting dot com"'s note:
This depends on the operating system.
On windows-systems you can't rename a file to an existing destination (ok, with tools you can - but they unlink the exisiting one before).
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17323">issues.joomla.org/tracker/joomla-cms/17323</a>.</sub>

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by csthomas** [comment]
IMO the fix should look like
```diff
diff --git a/libraries/src/Component/Router/Rules/MenuRules.php b/libraries/src/Component/Router/Rules/MenuRules.php
index 34bd9b1e58..973d01095c 100644
--- a/libraries/src/Component/Router/Rules/MenuRules.php
+++ b/libraries/src/Component/Router/Rules/MenuRules.php
@@ -202,7 +202,7 @@ class MenuRules implements RulesInterface
 
                        foreach ($items as $item)
                        {
-                               if (isset($item->query) && isset($item->query['view']))
+                               if (isset($item->query['view'], $views[$item->query['view']]))
                                {
                                        $view = $item->query['view'];

```

because such view does not exist and can not be added to menu lookup at all.

**Comment by johannesveje** [comment]
Any updates on how long it will be till this 8 chars, 3½ month old fix will be implemented ? I hope the time isn't proportional to the size of the commit for other problems.

**Comment by brianteeman** [comment]
Every pull request needs at least two human tests to confirm the issue and fix

**Comment by johannesveje** [comment]
So right now all that is missing is one human confirming the fix? The issue have been reported multiple times: #18123  and #18043 . The last one also have a confirmed fix, which might even work better than this one.

**Comment by csthomas** [comment]
I have created another solution for the same problem. Welcome to test #18564. 
You can test it in your own way.

If no PR will be tested by two testers, none of them will be merged.

**Comment by johannesveje** [comment]
Yay one more solution \o/

**Comment by csthomas** [comment]
@johannesveje If you want any changes in joomla you should test some of them at https://issues.joomla.org/tracker/joomla-cms/

**Comment by johannesveje** [comment]
I'll create a solution myself when I get the time 😊

**Comment by Quy** [comment]
@csthomas Can this be closed?

**Comment by csthomas** [comment]
I think so or after #18564 will be merged.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17323">issues.joomla.org/tracker/joomla-cms/17323</a>.</sub>

**Pull request closed without merging**
