### PR TITLE
Limit frontend article category edit to Publishers and up

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24626

### Summary of Changes
Instead of preventing anyone from modifying the category when editing an already saved article in frontend, this PR allows Publishers and up to do so (edit.state). 

### Testing Instructions
Create an article as Author in frontend (category can be chosen until article saved).
Publish the article (through backend or frontend)
Log as author and edit the article: the category field is greyed.
Log as Publisher and edit the article: the category field is also greyed.

Patch and retest

### After patch
When logging as Publisher, the category field can be modified.

### Note
We could also add a new parameter as proposed here:
https://github.com/joomla/joomla-cms/pull/24216#issuecomment-484784874

Which would re-instate as default editing category by Author (edit.own)

### CODE REVIEW

**Comment by ghost** [comment]
@ThomasK0lasa please test.

**Comment by ThomasK0lasa** [comment]
Works as supposed to. Thank You. :)

**Comment by ghost** [comment]
@ThomasK0lasa please mark your test as successfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by ThomasK0lasa** [comment]
I have tested this item :white_check_mark: successfully on 83d63df3aa5d3dd93047e4a66eb73ea7226d5cd7<br /><br />Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24640">issues.joomla.org/tracker/joomla-cms/24640</a>.</sub>

**Comment by ghost** [comment]
@Webdongle please test.

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on 0045fc37cc17e17227867908efc79c8b545bfb96<br /><br />Sorry saw the word 'Merged' didn't see it was referring to the other issue.  Yes tested OK for me.  Thanks for listening.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24640">issues.joomla.org/tracker/joomla-cms/24640</a>.</sub>

**Comment by ghost** [comment]
@infograf768 can this be RTC or need retest of @ThomasK0lasa ?

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24640">issues.joomla.org/tracker/joomla-cms/24640</a>.</sub>

**Comment by HLeithner** [comment]
@ron4mac does this work for you too?

**Comment by HLeithner** [comment]
thx

**Pull request merged**
