### PR TITLE
[4.0] Log everything string

### PR DESCRIPTION
**Pull request by brianteeman**
Change label to "enable logs" which makes more sense and is more consistent with other labels

Pull Request for Issue #35349

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d80fa5123d9e0e5fe4b3940301053b106b121dba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35733">issues.joomla.org/tracker/joomla-cms/35733</a>.</sub>

**Comment by Fedik** [comment]
It is misleading now.

It is exactly what it say "log everything":
https://github.com/joomla/joomla-cms/blob/0c41f6b92008abd255c2451347024c4f1f96b342/libraries/src/Application/CMSApplication.php#L1405-L1409

User may assume that log is disabled when it Off, but it is not. 
Log also may be enabled if you add any category to "Log Categories": https://github.com/joomla/joomla-cms/blob/0c41f6b92008abd255c2451347024c4f1f96b342/libraries/src/Application/CMSApplication.php#L1411

The fix for "Log Categories" description is there #34966

**Comment by brianteeman** [comment]
So "Custom logging" really should be called "Logging Options" and the fields reworked to use showon?

**Comment by Fedik** [comment]
hm, not really, Custom logging is about logging of specific category(-ies).
When "Log categories" is empty then Custom logging is disabled,
when example you add `jerror,database` then it will log only these categories, no mater if "Log everything" On or Off.

It is 2 different sections, which migrated from debug plugin.

**Comment by brianteeman** [comment]
wow this really is a mess. Can't be fixed with a string

**Comment by Fedik** [comment]
but please test  #34966 that is a fix for misleading description :)

**Pull request closed without merging**
