### PR TITLE
[asset_id db field] add default value and normalise across db systems

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
PR for issue https://github.com/joomla/joomla-cms/issues/13032

### Summary of Changes

As detected in https://github.com/joomla/joomla-cms/issues/13032 there are some issues with the asset_id db columns.
This PR normalizes them.

### Testing Instructions

- On update
  - Run the update queries for your db system manually and check all fine

- On install
  - Use latest staging, apply patch
  - Delete configuration.php file and install as usual. Check all fine and the db fields are correctly created.

### Documentation Changes Required

None.

### Notes

Although the issue was found on 4.0 because of a more strict sql_mode, this also applies in 3.x since this db field should always have a default value.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@alikon please review/test

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 379031aa0d137a4e5dbdf600750472f490f9e098<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13034">issues.joomla.org/tracker/joomla-cms/13034</a>.</sub>

**Comment by csthomas** [comment]
Please resolve the conflict.

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13034">issues.joomla.org/tracker/joomla-cms/13034</a>.</sub>

**Pull request closed without merging**
