### PR TITLE
[4.0] Remove unused import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 59b9776e22acc8c1e9ca63ddf29dff5c042cf99c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36198">issues.joomla.org/tracker/joomla-cms/36198</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 59b9776e22acc8c1e9ca63ddf29dff5c042cf99c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36198">issues.joomla.org/tracker/joomla-cms/36198</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36198">issues.joomla.org/tracker/joomla-cms/36198</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
