### PR TITLE
[#26911] fix: For multilingual site setup - Enable multilingual plugi…

### PR DESCRIPTION
**Pull request by shinderohanoffical**
…n should open in another tab.

Pull Request for Issue # .

### Summary of Changes
Change language file of com_associastions

### Testing Instructions
1: Go to admin
2: Go to the components >> multilingual Associations.
3: Click on 'Language Filter plugin'

### Expected result
1: It should open in new tab

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on c743a5ea5fa8c9519f8ec91c8e3b18a22870b6e8
#pbf19 #test1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26920">issues.joomla.org/tracker/joomla-cms/26920</a>.</sub>

**Comment by infograf768** [comment]
Not sure everyone agrees with that. I’m ok personally with it.

**Comment by brianteeman** [comment]
Please don't do this.

**Comment by infograf768** [comment]
Let's close it. We should rather find a solution similar to the Redirect Manager one.

**Pull request closed without merging**
