### PR TITLE
[4.2] missing rel="noopener noreferrer" in link language string

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue # .

### Summary of Changes

Add `rel="noopener noreferrer"` in language string

### Testing Instructions

Code review

### Actual result BEFORE applying this Pull Request

Missing `rel="noopener noreferrer"` in the language string, because the link contains `target="_blank"`

### Expected result AFTER applying this Pull Request

Language string contains `rel="noopener noreferrer"`

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed

- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9649fd7cfe2286e88ab7ac7b71a6ca3da9a9dfb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39317">issues.joomla.org/tracker/joomla-cms/39317</a>.</sub>

**Comment by richard67** [comment]
Do we have that string elsewhere, e.g. in the language file for the api client or the site, where it should be fixed, too? Am off my desk now so can’t comfortably check.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9649fd7cfe2286e88ab7ac7b71a6ca3da9a9dfb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39317">issues.joomla.org/tracker/joomla-cms/39317</a>.</sub>

**Comment by richard67** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39317">issues.joomla.org/tracker/joomla-cms/39317</a>.</sub>

**Comment by sandewt** [comment]
> Update: I meanwhile checked. All fine, no other file with that string.

@richard67 Thank you, your comment triggered me.

We missed the installation folder:

https://github.com/joomla/joomla-cms/blob/49258c0b74649613648f0190f6efe7102f35f07c/installation/language/pl-PL/joomla.ini#L88

and

https://github.com/joomla/joomla-cms/blob/49258c0b74649613648f0190f6efe7102f35f07c/installation/language/zh-CN/joomla.ini#L75

**Comment by richard67** [comment]
> > Update: I meanwhile checked. All fine, no other file with that string.
> 
> @richard67 Thank you, your comment triggered me.
> 
> We missed the installation folder:
> 
> https://github.com/joomla/joomla-cms/blob/49258c0b74649613648f0190f6efe7102f35f07c/installation/language/pl-PL/joomla.ini#L88
> 
> and
> 
> https://github.com/joomla/joomla-cms/blob/49258c0b74649613648f0190f6efe7102f35f07c/installation/language/zh-CN/joomla.ini#L75

@sandewt These are translations. If the English strings are ok, the translations have to be fixed on Crowdin, as far as I know.

**Comment by sandewt** [comment]
> If the English strings are ok, the translations have to be fixed on Crowdin, as far as I know.

I also found the same issue in a language pack. I will pass this on to the relevant translator.

**Comment by laoneo** [comment]
Thank you!

**Pull request merged**
