### PR TITLE
[4.4] Fix start=0 in the pagination

### LINKED ISSUE #44049: On the start page /?start=0 works
### Steps to reproduce the issue
Call up your start page and set the parameters /?start=0 behind it

### Expected result
The same behaviour as with all other /?start=x parameters 404 not found

### Actual result
The start page is displayed

### System information (as much as possible)
PHP 8.2
J 5.1.4

### Additional comments
The problem is that Google indexes both the start page with and without the parameter and treats it as non-canonical...
grafik

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/44049 .

### Summary of Changes

Fix removing of `start=0` from pagination for the first page.

### Testing Instructions

Visit Category Blog or another list view with pagination.
Visit second page, and check the link for first page.

### Actual result BEFORE applying this Pull Request
Link contain `start=0`

### Expected result AFTER applying this Pull Request
Link without `start=0`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Mich-es** [comment]
It works!

**Comment by fgsw** [comment]
@Mich-es can you open https://issues.joomla.org/tracker/joomla-cms/44069 and click button "Tested successfully" so the test is counted.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 44c8277e0004add9e4ce631a0eec2f74efc68c00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by Mich-es** [comment]
I have tested this item :white_check_mark: successfully on 44c8277e0004add9e4ce631a0eec2f74efc68c00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by PhocaCz** [comment]
On some places, I get '0'

image

So, for me, instead of:

```
if ($limitstart !== null && $limitstart !== '') {
```
this works:
```
if ($limitstart !== null && $limitstart !== '' && $limitstart !== '0') {
```

**Comment by Fedik** [comment]
It is expected, when `limitstart` have a value, then it will be added to URL.
The router code is skipping only empty values.

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on 44c8277e0004add9e4ce631a0eec2f74efc68c00<br /><br />Tested successfully with $hideEmptyLimitstart set to true. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by n3t** [comment]
I have tested this item :white_check_mark: successfully on 62b3a63b2c24b54b207b6e5038b2eccf43f2598c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by n3t** [comment]
Just an idea, wouldn't be better to have $hideEmptyLimitstart true as default? I guess probably there are more components using pagination with hidden start=0 than those requireing this syntax...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44069">issues.joomla.org/tracker/joomla-cms/44069</a>.</sub>

**Comment by Fedik** [comment]
> is it possible to add this to the current Issue?

Nope, it's not as simple as it might seem.

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
