### PR TITLE
Fix options in mailtemplate form

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Fix a copy paste error in template form

### Testing Instructions
Code inspect - or apply the patch and make sure that tabs in mail templates are still correct 
grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
it is a bug but why not use the existing generic string JOPTIONS?

**Comment by chmst** [comment]
Valid point. At the moment, every component has it's own label. Search for "LABEL="Options".

Personally I would like to have here a more specific name, maybe "mail options" but kept the standard language string.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37683">issues.joomla.org/tracker/joomla-cms/37683</a>.</sub>

**Comment by brianteeman** [comment]
Took me a while to find this view - for other testers you have to set the per template setting in the options

image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d37e08f443f188eaaafb0ea341d7553ae505b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37683">issues.joomla.org/tracker/joomla-cms/37683</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on d37e08f443f188eaaafb0ea341d7553ae505b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37683">issues.joomla.org/tracker/joomla-cms/37683</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37683">issues.joomla.org/tracker/joomla-cms/37683</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
