### PR TITLE
Update .eslintrc max length

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Adjusts the length of the line to 150 chars (same as PHP)

### CODE REVIEW

**Comment by brianteeman** [comment]
seems reasonable

**Comment by dgrammatiko** [comment]
> seems reasonable

@Fedik was also asking for an increased line length. I'm not sure though if the php length is really 160

**Comment by brianteeman** [comment]
My comment on it being reasonable was based on the comment "same as php"

**Comment by dgrammatiko** [comment]
Turns out it's 150: https://github.com/joomla/coding-standards/blob/2bc5e324c218f72c8bdc05563cecf78392202d74/Joomla/ruleset.xml#L27

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5aa45bd8677db8ccb126756b10a094a3c459deda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34973">issues.joomla.org/tracker/joomla-cms/34973</a>.</sub>

**Comment by HLeithner** [comment]
I thought we follow the airbnb style guide why do we need exceptions?

**Comment by dgrammatiko** [comment]
> I thought we follow the airbnb style guide why do we need exceptions?

We already have some exceptions and also the idea is to adapt the tools to our needs. Right now the tool is dictating something that's not in line with the rest of the project (php files are 150 chr long). In short tools are not rules

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 5aa45bd8677db8ccb126756b10a094a3c459deda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34973">issues.joomla.org/tracker/joomla-cms/34973</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34973">issues.joomla.org/tracker/joomla-cms/34973</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
