### PR TITLE
[4.0] add legend styles in settings

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - Legend styles which existed in J3 are missing, which makes navigation in settings difficult.

### Expected result
screenshot from 2019-02-25 16-11-51
screenshot from 2019-02-25 16-10-47

### Actual result
screenshot from 2019-02-25 16-18-06

### CODE REVIEW

**Comment by bahl24** [comment]
@infograf768 @C-Lodder What do you think?

**Comment by Razzo1987** [comment]
I have tested this item :red_circle: unsuccessfully on 5d18f972ccad7221bb16a7c8f7e9b7b0d597cbfe<br /><br />no change :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24012">issues.joomla.org/tracker/joomla-cms/24012</a>.</sub>

**Comment by wojsmol** [comment]
@Razzo1987 You mead to run `npm run build:css` after applying this patch - see [Setting Up Your Local Environment](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment).

**Comment by bahl24** [comment]
The exact command is given in build.js for building scss files.

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 5d18f972ccad7221bb16a7c8f7e9b7b0d597cbfe<br /><br />Sorry!

with npm run build:css works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24012">issues.joomla.org/tracker/joomla-cms/24012</a>.</sub>

**Comment by Quy** [comment]
Related PR #24322

**Comment by brianteeman** [comment]
yes that PR fixes the problem which was a pr that should not have been merged

**Comment by brianteeman** [comment]
This should be closed as it was fixed with #24322

**Pull request closed without merging**
