### PR TITLE
[4.1] Display global class for intro and full image

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #37357  .

### Summary of Changes
Added `useglobal="true"` to intro and full article images class field to display if a class is already set in the global settings

### Testing Instructions
See issue

### Actual result BEFORE applying this Pull Request
See issue

### Expected result AFTER applying this Pull Request
UPDATE: the same should be present when editing an article in the frontend

If a class is set in the global settings, you will see it in the class field of the image:
grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
No idea why it didnt work when I tried.

Can you also do the same to these files as well please 
administrator\components\com_tags\forms\tag.xml
components\com_content\forms\article.xml

**Comment by drmenzelit** [comment]
> Can you also do the same to these files as well please administrator\components\com_tags\forms\tag.xml components\com_content\forms\article.xml

Sure, for articles frontend editing is no problem. 
Images in tags seems to have another logic, no global settings and the "classes" are still a list

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ebadb108ebfe0f7386f9cefc8382f761b838dccd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37368">issues.joomla.org/tracker/joomla-cms/37368</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on ebadb108ebfe0f7386f9cefc8382f761b838dccd<br /><br />Works in the frontend and backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37368">issues.joomla.org/tracker/joomla-cms/37368</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37368">issues.joomla.org/tracker/joomla-cms/37368</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
