### PR TITLE
[4.0] Mail Template add language

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the language code to the displayed title when editing a mail template. As discussed in #27704

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 274b7d2011c50102c4052eec0ae9e3c172644fd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27723">issues.joomla.org/tracker/joomla-cms/27723</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 274b7d2011c50102c4052eec0ae9e3c172644fd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27723">issues.joomla.org/tracker/joomla-cms/27723</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27723">issues.joomla.org/tracker/joomla-cms/27723</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
