### PR TITLE
Added Feature items filter to mod_articles_news | Fix merge conficts for #11540

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #11539 . And redo of #11540 
#### Summary of Changes

The feature item filter was already available for the
mod_articles_latest module, but that is just a list.
All code was slightly modified from the mod_articles_latest module.
#### Testing Instructions
- Login to the joomla administrator
- Add the module Articles - Newsflash 
- You should now see a filter parameter for featured
#### Documentation Changes Required

https://help.joomla.org/proxy/index.php?keyref=Help36:Extensions_Module_Manager_Articles_Newsflash 
Should be updated to include the featured articles filter
Just copy and paste what is here: https://help.joomla.org/proxy/index.php?keyref=Help36:Extensions_Module_Manager_Latest_News

### CODE REVIEW

**Comment by zero-24** [comment]
Please give that a quick test against 3.7.x to be back RTC :smile:

**Comment by zero-24** [comment]
Can we get a test for this merge conflict PR?

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 19736f17e9c0ba624bbd5bff413fee7b46d06c4c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12547">issues.joomla.org/tracker/joomla-cms/12547</a>.</sub>

**Comment by zero-24** [comment]
RTC as it is just a redo of the original tested PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12547">issues.joomla.org/tracker/joomla-cms/12547</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
There's a "Show Images" in Module, but neither Intro Image or Full Artivle Image nor Image append by Editor is shown.

**Comment by zero-24** [comment]
Just implemented to the docs: https://docs.joomla.org/Chunk30:Help-3x-module-site-articles-newsflash#Module

**Pull request merged**
