### PR TITLE
Deprecate Bootstrap Affix as this doesn't exist in BS4

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Just deprecating a method

### Testing Instructions
None

### CODE REVIEW

**Comment by zero-24** [comment]
As we are now in code freeze this needs to wait until 3.7.1.

**Comment by zero-24** [comment]
RTC for 3.7.1 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15383">issues.joomla.org/tracker/joomla-cms/15383</a>.</sub>

**Comment by brianteeman** [comment]
as its only a comment and not actual code I dont see why it needs to wait ;)

**Comment by mbabker** [comment]
Technically it would have to be 3.8 if it doesn't go into 3.7.  Semantic Versioning disallows deprecating API functionality in a patch release.

**Comment by C-Lodder** [comment]
@dgt41 - could you also add the deprecation notice for `typeahead` too please?

**Comment by zero-24** [comment]
@dgt41 can you please rebase against 3.8-dev so we can merge it for 3.8 😄 Just ping me if done.

**Comment by dgt41** [comment]
@C-Lodder done. What is the plan the tooltips-extended, keep/drop?

**Comment by C-Lodder** [comment]
tooltips-extended isn't neded in J4, so we can deprecate this too

**Comment by mbabker** [comment]
I just merged staging to 3.8 and changed this PR's branch to 3.8-dev so we're good here.  Once the tooltip thing is added I can merge this.

**Comment by zero-24** [comment]
Merged Thanks!

**Pull request merged**
