### PR TITLE
Fix new J4 components missing assets

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Noticed through the excellent [PWT ACL Manager](https://extensions.joomla.org/extension/acl-manager/) tool whilst upgrading our core joomla.org sites

None of the new components since Joomla 4 have assets included. This should fix that once sites upgrade

### Testing Instructions
Run an upgrade of Joomla to this version. After the patch asset items for the new extensions should be included correctly

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge I'm not really sure if that is needed for the core components because when you edit their params in backend, new assets are created by the model in the right way. That's why I assumed that the updateAssets method has only been kept so it can be overridden by 3rd party extension devs in their installer script class if they derive that from the core one.

The PR is correct and the list of components is complete, so I'm ok with it. But as said, I'm not sure if it's necessary.

When the PR gets merged and merged up into 5.0-dev, the list needs to be modified by removing the components added here, and any new components from J5 should be added, but I don't know of any, so it would remain empty in J5.

**Comment by HLeithner** [comment]
@wilsonge status here? do we need it?

**Comment by wilsonge** [comment]
Well we have through all the J2.5 and 3.x components so I think we should have it.

**Comment by HLeithner** [comment]
@laoneo @MacJoom that's for you

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by richard67** [comment]
After this has been merged up into the 5.x-dev branches it will need to be modified in 5.0-dev for the new components added between 4 and 5, and the ones added between 3 and 4 need to be removed.

**Comment by bembelimen** [comment]
@richard67 it's in the upmerge process: https://github.com/joomla/joomla-cms/pull/42345

Could you prepare the PR for the new extensions? Thanks!

**Comment by wilsonge** [comment]
Unfortunately because this was merged after 4.4.0 was released and some people may already have upgraded to 5.0 and not had this run. So we do need at add the 5.0 components into the 5.0 branch - but we also shouldn't remove the 4.0 components this time around (only because of the fact we didn't merge this early enough).

**Pull request merged**
