### PR TITLE
Add missing mediaversion to polyfill js files

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This simple PR add media version to polyfll js files.

### Testing Instructions

Simple Test. Code review, or:
- Go to site homepage, view page source and confirm polyfill media version DOES NOT EXISTS in polyfill js files
```html
<!--[if lt IE 9]><script src="/media/system/js/polyfill.event.js"></script><![endif]-->
```
- Apply patch
- Go to site homepage, view page source and confirm media version EXISTS in polyfill js files
```html
<!--[if lt IE 9]><script src="/media/system/js/polyfill.event.js?923058328df38d83cc809d587c7c445a"></script><![endif]-->
```

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Tested successfully (sha missing)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12714">issues.joomla.org/tracker/joomla-cms/12714</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a49543e0e077f0a6ebf4eb995b08eec4c97d97d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12714">issues.joomla.org/tracker/joomla-cms/12714</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on a49543e0e077f0a6ebf4eb995b08eec4c97d97d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12714">issues.joomla.org/tracker/joomla-cms/12714</a>.</sub>

**Comment by andrepereiradasilva** [comment]
RTC

**Comment by zero-24** [comment]
Merged. Thanks

**Pull request merged**
