### PR TITLE
JArrayHelper => ArrayHelper for the backend

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

JArrayHelper => ArrayHelper
#### Testing Instructions

Please make sure that the backend components still works as before.
Code Review ;)

### CODE REVIEW

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 1dfcb762d93b65dc3fe6f665891199eeee1ad1d6<br /><br />Everything looks ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10923">issues.joomla.org/joomla-cms/10923</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 1dfcb762d93b65dc3fe6f665891199eeee1ad1d6<br /><br />After applying the patch, there are no obvious issues, everything works as before. Code review looks good as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10923">issues.joomla.org/joomla-cms/10923</a>.</sub>

**Comment by zero-24** [comment]
Thanks! @joomla-cms-bot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10923">issues.joomla.org/joomla-cms/10923</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman can we fix / remove the milestone please?

**Comment by rdeutz** [comment]
I am not Brian but I think you asked for a 3.6.1 Milestone

**Comment by zero-24** [comment]
Thanks :smile:

**Comment by zero-24** [comment]
Is there any reason to not merge this one?

**Comment by roland-d** [comment]
@zero-24 I am not merging because I am one of the testers. Nudge @wilsonge :)

**Comment by wilsonge** [comment]
As per the same refactor in #10676 It's not a bug fix so it's not really a patch release. So I think this is a 3.7 thing - but will merge it soon enough :)

**Comment by wilsonge** [comment]
Merged with 9ef83f70040ab3ad18efc7875622e30cd82c1eff - Thanks Tobias :)

**Pull request closed without merging**
