### PR TITLE
[4.1] s/inverval/interval

### PR DESCRIPTION
**Pull request by brianteeman**
This is part of the schedule runner js and looks like a bug to me
@ditsuke

### CODE REVIEW

**Comment by richard67** [comment]
The bug seems to cause that in any case 300 seconds are used. As most testing instructions in past were done with 5 minute example, nobody has ever noticed, I guess.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5d516aa782ac9ccdfae6562cfba5ad9909b3520a<br /><br />Code review. Obviously a typo, but to be sure I've really checked if there is any PHP or XML or SQL file or any JS beside those fixed by this PR which is using "inverval", and there isn't.

The bug by this typo might have been missed in past because it does not cause any crashing errors, it just makes the scheduler use a wrong value.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36832">issues.joomla.org/tracker/joomla-cms/36832</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5d516aa782ac9ccdfae6562cfba5ad9909b3520a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36832">issues.joomla.org/tracker/joomla-cms/36832</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36832">issues.joomla.org/tracker/joomla-cms/36832</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by ditsuke** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
