### PR TITLE
Searchtools JLayout. Remove B\C breaking filterButton dependency for filters display

### PR DESCRIPTION
**Pull request by ghost**
### Summary of Changes
- Removed the `if filterButton` condition for PHP loading of filter fields.

- Why: In Joomla 3.6.5  in list views (backend) one could easily hide the button "Search Tools" but show the filter fields permanentely by sending the options `filterButton` and `filtersHidden` to the JLayout like this
```
echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, 
'options' => array('filterButton' => false, 'filtersHidden' => false)
)); 
```

- Since Joomla 3.7 not only the button is hidden but also all filters THAT ARE NOT LOADED BY PHP at all. No chance to show the filters permanentely if option `'filterButton' => false`. Option '`filtersHidden`' is senseless.

### Testing Instructions
- Testing with a core component that has a list view with search tools, e.g. com_content > Articles.
- Open `/administrator/components/com_content/views/articles/tmpl/default.php`.
- Change line 59 ( https://github.com/joomla/joomla-cms/blob/3.7.0/administrator/components/com_content/views/articles/tmpl/default.php#L59 )

```
echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, 
'options' => array('filterButton' => false, 'filtersHidden' => false)
)); 
```

- In backend go to `administrator/index.php?option=com_content&view=articles`
- You'll see no filter fields and no button. If you want check HTML source code that filters are not loaded at all.

- Now the same test with Joomla 3.6.5 in line 46 if you're not convinced: https://github.com/joomla/joomla-cms/blob/3.6.5/administrator/components/com_content/views/articles/tmpl/default.php#L46
- No button but filters are always visible.

- Apply patch.
- Try again in Joomla 3.7

### CODE REVIEW

**Comment by brianteeman** [comment]
if you remove that if statement thendo  you also need to remove the code at line 41

**Comment by brianteeman** [comment]
for reference the changes you want to revert are from #10090

**Comment by bertmert** [comment]
> if you remove that if statement thendo you also need to remove the code at line 41

No, because option 'filterButton' has highest priority in line 
https://github.com/joomla/joomla-cms/pull/15634/files#diff-7fc57bb3a5e5ed4c711d5ea9fe03a5cfL62

If option 'filterButton' is not set we have a fallback to $showFilterButton, quasi a default setting. Otherwise the coder rules.

**Comment by Schmidie64** [comment]
I have tested this item :red_circle: unsuccessfully on 230db57f602c94dc13b195a459db349f5825b958<br /><br />I've followed the instructions step by step. (Info: Line 59 is not longer correct. It move to line 67.) At the point were i should apply the patch i've got the error message: "The patch could not be applied because the repository is missing". So i couldn't finish the test. 
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15634">issues.joomla.org/tracker/joomla-cms/15634</a>.</sub>

**Comment by Quy** [comment]
@Schmidie64 The user/repo has been deleted. You will have to manually apply the changes as outlined here: https://github.com/joomla/joomla-cms/pull/15634/files

**Comment by brianteeman** [comment]
As this pr was created to resolve a claimed b/c issue over 16 months ago and there have been no other reports/comments I would say it is obviously not a real issue and can be closed

**Comment by ghost** [comment]
closed as stated above.

**Pull request closed without merging**
