### PR TITLE
[4.0] add refresh to grid mapping

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
patchtester #277
### Summary of Changes
add refresh to mapping

### Testing Instructions
verify fetch in patchtester now maps correctly.

### Actual result BEFORE applying this Pull Request

fetch icon empty

### Expected result AFTER applying this Pull Request

fetch icon displays.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by ceford** [comment]
I applied the patch with Patch Tester but the refresh icon is still missing. Inspector tells me there is no content. I guess this means the css needs to be recompiled to test properly (by others). <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30053">issues.joomla.org/tracker/joomla-cms/30053</a>.</sub>

**Comment by brianteeman** [comment]
@ceford there are no css changes in this pr so if the pr is correct then you should see the changes

**Comment by ceford** [comment]
I don't see fa-refresh in the font awesome docs - should it be fa-sync?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30053">issues.joomla.org/tracker/joomla-cms/30053</a>.</sub>

**Comment by ceford** [comment]
I should have said - using fa-sync works without the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30053">issues.joomla.org/tracker/joomla-cms/30053</a>.</sub>

**Comment by N6REJ** [comment]
@ceford hi cliff.. your 100% right, fa-sync is correct and does work if you do it manually.. I'm firing things up as we speak to see whats what.  
I THINK the problem is pt keeps putting icon- in and it shouldn't be doing that but I've not figured out where/why yet.

**Comment by richard67** [comment]
@N6REJ For the PT this PR doesn't help much, because this PR deals with JGrid, i.e. the list views, while for PT it would need to work on the Toolbar Helper.

**Comment by N6REJ** [comment]
@richard67 close it or keep it then?

**Comment by N6REJ** [comment]
closing as irrelevant.

**Pull request closed without merging**
