### PR TITLE
[4.3] Massmail: Fix validation

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #33450.

### Summary of Changes
Please see the original issue for the problem. Simply said, the mass mail feature has a custom, stupid form validation. This PR uses the default Joomla validation and also the default markup.

### Testing Instructions
1. Go to mass mail in the users menu.
2. Click on "Send Mail" (without filling out any data)

### Actual result BEFORE applying this Pull Request
The form is not send and you get a blue box stating an error. Clicking again will add yet another blue box each time.

### Expected result AFTER applying this Pull Request
Sending the form is prevented and all invalid fields are marked red. In addition, there is a message at the top. Clicking again will re-validate and only display one message at the top.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed
- [X] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/68

### CODE REVIEW

**Comment by Quy** [comment]
Add padding/spacing.

39374-padding

**Comment by Hackwar** [comment]
@Quy done

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5e9c4894b438d706d273711f5d356a0c0fd808ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39374">issues.joomla.org/tracker/joomla-cms/39374</a>.</sub>

**Comment by richard67** [comment]
The deleted JS file will be added to the list of files to be deleted on update in script.php with another PR. I will care for that.

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 5e9c4894b438d706d273711f5d356a0c0fd808ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39374">issues.joomla.org/tracker/joomla-cms/39374</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar for the PR!

**Comment by HLeithner** [comment]
Documentation PR is wrong because it misses the removed JS file... this PR should have not been merged with a wrong documentation PR, also the documentation PR has to be merged at the same time as the PR it self....

**Comment by Hackwar** [comment]
Are you saying that we can't remove the JS? Or just to extend the documentation PR?

**Comment by richard67** [comment]
> Are you saying that we can't remove the JS? Or just to extend the documentation PR?

@Hackwar That's actually subject of discussion in the maintainers channel on Mattermost and in my PR #39413 and in my previous PR #39408 .

**Pull request merged**
