### PR TITLE
[4.0] Fix undefined variable notice

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes undefined variable notice.

### Testing Instructions

Go to some component's configuration.
Click `Cancel` button.
Check PHP error log.

### Actual result BEFORE applying this Pull Request

>Notice:  Undefined variable: option in administrator\components\com_config\src\Controller\ComponentController.php on line 200

### Expected result AFTER applying this Pull Request

No notices.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by zero-24** [comment]
Can you please check the line:
https://github.com/joomla/joomla-cms/blob/bacfcc60bd7a3d9bf5e5b971404faa7157d99bf5/administrator/components/com_config/src/Controller/ComponentController.php#L204

It seems we now have the same call twice?

**Comment by SharkyKZ** [comment]
Right. Fixed.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 8eac71f5d76fb49a13d8c2c525552cee60da1865<br /><br />Tested successfully in Beta6-dev of 4 November.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31307">issues.joomla.org/tracker/joomla-cms/31307</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8eac71f5d76fb49a13d8c2c525552cee60da1865<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31307">issues.joomla.org/tracker/joomla-cms/31307</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31307">issues.joomla.org/tracker/joomla-cms/31307</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
