### PR TITLE
Fix parent construct

### PR DESCRIPTION
**Pull request by wilsonge**

### CODE REVIEW

**Comment by PhilETaylor** [comment]
did I break something?

**Comment by joomdonation** [comment]
Sadly Yes @PhilETaylor

**Comment by joomdonation** [comment]
This PR does not fix the issue. Better revert https://github.com/joomla/joomla-cms/pull/35292

**Comment by wilsonge** [comment]
Can you give me the stack trace?

**Comment by PhilETaylor** [comment]
> Better revert #35292

I'll leave you to work out the issues then. The PR had appropriate tests and only deleted a constructor that contained no code.

**Comment by wilsonge** [comment]
Unfortunately things called the constructor :)

**Comment by PhilETaylor** [comment]
> Unfortunately things called the constructor :)

One thing. not things.

**Comment by PhilETaylor** [comment]
Best pull 4.0.1 quickly from the update channels then ?

**Comment by PhilETaylor** [comment]
looks like there are several places it was called.

**Comment by PhilETaylor** [comment]
Line 799
Line 860
Line 2665

Those all need removing too.

**Comment by joomdonation** [comment]
This one https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/restore.php#L799 and https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/restore.php#L860

**Comment by PhilETaylor** [comment]
try this one https://github.com/joomla/joomla-cms/pull/35333

**Pull request closed without merging**
