### PR TITLE
[4.3] Don't allow to select non-existing tags in com_tags menu items

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #39128 .

### Summary of Changes
Create a menu item of either "Compact List of tagged items" or "Tagges items" and type in a random tag into the mandatory "Tag" field. You should not be able to select a non-existing tag here. This will definitely result in a broken link in the frontend. 

### Testing Instructions
See above instructions.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 6c8928e83af201ee4efeb78f8a1afa7d78c9f2f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39154">issues.joomla.org/tracker/joomla-cms/39154</a>.</sub>

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on 5ec0b796d4ae0c4de43a49d29b44849f78ccc5ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39154">issues.joomla.org/tracker/joomla-cms/39154</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39154">issues.joomla.org/tracker/joomla-cms/39154</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar for the PR!

**Pull request merged**
