### PR TITLE
[4.0] Notice when "Link to Author's Contact Page" option is enabled

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/29518.

### Summary of Changes

Fixes a notice.

### Testing Instructions

In Article options enabled `Link to Author's Contact Page`.
Create an article.
View the article in frontend.

### Expected result

No notices.

### Actual result

Notices like:

>Notice: Trying to get property 'contactid' of non-object in plugins\content\contact\contact.php on line 73

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have not tested this item.<br /><br />OK on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29520">issues.joomla.org/tracker/joomla-cms/29520</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5702c8875343f1cec3ac951c22328342ec75f93d<br /><br />OK on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29520">issues.joomla.org/tracker/joomla-cms/29520</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 5702c8875343f1cec3ac951c22328342ec75f93d<br /><br />Tested successfully on 4.0-beta2-dev of Nightly Builds of 9 May.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29520">issues.joomla.org/tracker/joomla-cms/29520</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29520">issues.joomla.org/tracker/joomla-cms/29520</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
