### PR TITLE
[5.2] Fix Dart Sass deprecations

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes
`lighten()` and `darken()` are global functions in Dart Sass, that were deprecated as of v1.79.0.
This PR replaces them with `color.adjust()` inside Joomla's SCSS

> Note: Bootstrap's own SCSS still uses these functions, and may or may not fix said deprecations in v5, due to the fact they still support node-sass.

### Testing Instructions
Code review

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e22174c57c521368ea01cde4632d802b6429485c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44129">issues.joomla.org/tracker/joomla-cms/44129</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e22174c57c521368ea01cde4632d802b6429485c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44129">issues.joomla.org/tracker/joomla-cms/44129</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44129">issues.joomla.org/tracker/joomla-cms/44129</a>.</sub>

**Comment by pe7er** [comment]
Thanks @C-Lodder !

**Pull request merged**
