### PR TITLE
[contact modal field] Adds Create Contact button and other improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
### Summary of Changes

This PR is the sequence of https://github.com/joomla/joomla-cms/pull/11830 but for now for contact modal.

For list of changes see https://github.com/joomla/joomla-cms/pull/11830 (same changes, but for contact now).

Similiar PR: 
- Article: https://github.com/joomla/joomla-cms/pull/11830
- Category: https://github.com/joomla/joomla-cms/pull/11857
- Contact: https://github.com/joomla/joomla-cms/pull/11858 (this one)
- Newsfeed: https://github.com/joomla/joomla-cms/pull/11862
### Animated Gif (click to view in full screen)

modal-contact
### Testing Instructions
- Use latest staging
- Apply patch https://github.com/joomla/joomla-cms/pull/11830 and then this patch
- Create a Menu item Single Contact type
- Test all the "Edit", "Create", "Select" and "Clear" buttons  (as animated gif)
- In a multilanguage install edit a contact and try the modal button in the associations tab
- Test all the "Edit", "Create", "Select" and "Clear" buttons.
- Code review to check all is ok.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by bhavikTailored** [comment]
- I have tested unsuccessfully because of design is not good.
- screen shot 2016-09-01 at 00 45 54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :red_circle: unsuccessfully on 06f27f9ed74371b952fdbaa28949439adfb87596<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested this item :red_circle: unsuccessfully on 06f27f9ed74371b952fdbaa28949439adfb87596<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by andrepereiradasilva** [comment]
The issue you describe have nothing to do with this pr.
This pr does not intend to solve the lack of responsive design in some backoffice Pages.
Só it all test is ok please Mark as success.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 06f27f9ed74371b952fdbaa28949439adfb87596<br /><br />Tested this PR successfully BUT the modal layout does need to be fixed before this can be accepted<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by bhavikTailored** [comment]
@brianteeman , I agree with you. we should first fix layout then I will test successfully.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by andrepereiradasilva** [comment]
As said, that's a admin template responsible css issue (it will happen if you use those width sizes) that probably exists in several other places.

If someone wants to solve those css issues in a new PR go ahead, but please don't hijack this PR.

So, again, if the rest is tested with success please mark tested with success!

**Comment by brianteeman** [comment]
@andrepereiradasilva I hear what you are saying but the layout issues must be resolved before this PR can be accepted so it would make sense to do it here

**Comment by zero-24** [comment]
screen shot 2016-09-01 at 06 23 55

Looks good to me. I can't reproduce the problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 06f27f9ed74371b952fdbaa28949439adfb87596<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by andrepereiradasilva** [comment]
So RTC?

**Comment by brianteeman** [comment]
Setting RTC and creating a new issue for the modal<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11858">issues.joomla.org/joomla-cms/11858</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/581130dd17425f17dad7da42fd1a1100009ec2ed

**Pull request closed without merging**
