### PR TITLE
[4.3] Double Translation task description

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Removes the code error causing a double translation

### Testing Instructions
Enable language debug and check the description of any task

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 13f736bfc2b284c72a1042b6cb872ccb360b1651<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40507">issues.joomla.org/tracker/joomla-cms/40507</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 13f736bfc2b284c72a1042b6cb872ccb360b1651<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40507">issues.joomla.org/tracker/joomla-cms/40507</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40507">issues.joomla.org/tracker/joomla-cms/40507</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks brianteeman

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
