### PR TITLE
[4.0] Submenu items not modules

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25993.

### Summary of Changes

This removes incorrectly place module action icon from `mod_submenu` and other code mistaking submenu items for modules.

### Testing Instructions

View System Dashboard.

### Expected result

Still works but no more misleading module action next to submenu items.

### Documentation Changes Required

🤷‍♂

### CODE REVIEW

**Comment by infograf768** [comment]
Tested
The problem here is that we can't edit the "real" module anymore as the cog is no more present for default presets.
I also failed solving this to get a unique cog there and not in child.
It works though when we create a submenu, even with a preset 

Examples:
Default Content Dashboard
Screen Shot 2019-09-10 at 09 21 11

Modified Component Dashboard (Title set to Show)
Screen Shot 2019-09-10 at 09 22 17

**Comment by SharkyKZ** [comment]
Module action buttons belong in the chrome, not in module layout. System Dashboard module is using `none` chrome which doesn't have action buttons.

**Comment by infograf768** [comment]
@SharkyKZ 
I have been testing all dashboards, not only system.

**Comment by SharkyKZ** [comment]
Still applies. Use a different chrome. I know the layout is broken when using different chromes but that's out of scope of this PR.

**Comment by brianteeman** [comment]
> Still applies. Use a different chrome. I know the layout is broken when using different chromes but that's out of scope of this PR.

In this case it is in scope as its not possible to see if the changes work

**Comment by SharkyKZ** [comment]
This removes module action buttons from items that aren't modules.

**Comment by brianteeman** [comment]
Sorry for my confusion then on the previous post

**Comment by infograf768** [comment]
I do not get any conflict here. Looks like drone is dead though.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d87c51bc29df9190cf630cddf03894d2406396c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26245">issues.joomla.org/tracker/joomla-cms/26245</a>.</sub>

**Comment by SharkyKZ** [comment]
This kills the Drone 😕

**Comment by infograf768** [comment]
@SharkyKZ 
I suggest to redo a clean PR as it looks like drone was not triggered by this one.

**Comment by SharkyKZ** [comment]
Closing in favor of #26600.

**Pull request closed without merging**
