### PR TITLE
Add htaccess and web.config files to the libraries folder

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for: https://github.com/joomla/joomla-cms/issues/8957

### Summary of Changes

Add htaccess und web.config files to the libaries folder that denys all direct accesses to the files in that folder

### Testing Instructions

- apply this patch
- try to direct access the files in the lib folder like some external libs in the vendor folder

### Expected result

You are not allowed to direct access that file (e.g. a 403 error message)

### Actual result

In some server setups you see a error message.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by wilsonge** [comment]
Is there a reason to do this to the libraries folder rather than just `libraries/vendor`

**Comment by zero-24** [comment]
We have also non joomla code in `libraries` so better save than sorry :) You should never call something in `libraries` from public.

**Comment by mbabker** [comment]
Doing this change in the base libraries directory is going to be too intrusive to extensions which are doing terrible crap like serving web assets (CSS/JS) from the libraries directory.  This also prevents them from having direct access scripts in the directory (which even though some will say the only valid entry point into a Joomla application is index.php you can still do this as long as you're taking care of all the risks involved, as in we do not forbid it).

If the intent is to merge this before 4.0 we can only protect the `libraries/vendor` directory in this way.  Anything more would cause more backlash than it's worth.

**Comment by zero-24** [comment]
> If the intent is to merge this before 4.0 we can only protect the libraries/vendor directory in this way. Anything more would cause more backlash than it's worth.

Done.

**Comment by Bakual** [comment]
Could there be some server setups where adding a .htaccess file (or adding that option in it) would not be allowed and generate an error? Or is it safe to assume that it works on every shared hoster?

**Comment by zero-24** [comment]
@Bakual i have been told that even if it is not supported it is just ignored. So the issue is still there but we cant do much about that.

**Pull request merged**
