### PR TITLE
Use absolute URLs in action logs

### LINKED ISSUE #27431: User Actions Log notification to be sent on email: problem with URLs
### Steps to reproduce the issue
Go to Users > edit user > User Actions Log

Send notifications for User Actions Log * - set to YES
Screen Shot 2020-01-08 at 01 03 36

Now the admin receives a notification on email about any changes made on the site by this user.

### Expected result
The action should have clickable URL

Screen Shot 2020-01-08 at 01 04 19

### Actual result
In fact, I see the list of users and actions with URLs, but they are non-clickable.
Perhaps there is a problem with <a>...</a> in the email layout...

### System information (as much as possible)
Joomla 3.9.14

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes #27431.

### Summary of Changes

Use absolute URLs for links in action log emails.

### Testing Instructions

Make sure `Force HTTPS` option in Global Configuration is disabled.
As super admin, edit your profile. Enable `Send notifications for User Actions Log` option.
Perform a loggable action (e.g. edit an article).
Try clicking the links in the action notification email.

### Expected result

Links take you to your Joomla! website.

### Actual result

Links don't work.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Sulpher** [comment]
"Make sure Force HTTPS option in Global Configuration is disabled."

Why so? There are a lot of websites with SSL.

**Comment by SharkyKZ** [comment]
The issue is reproducible only when `Force HTTPS` is disabled.

**Comment by Sulpher** [comment]
> The issue is reproducible only when `Force HTTPS` is disabled.

I opened the administrator panel via http:// (no SSL) and Force HTTPS is set to None.
However, the issue occurs.
Then I opened the back-end via https:// and set Force HTTPS to Entire site.
The email is consists of correct URLs and there is no issue described above.

The conclusion: the problem could happen with the sites without SSL...

**Comment by SharkyKZ** [comment]
Yes, the issue occurs when `Force HTTPS` is set to `None` (i.e. disabled).

**Comment by Sulpher** [comment]
Thanks for the PR!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f046f5b36bb399934f66baeb12a94f618fd0a08a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27432">issues.joomla.org/tracker/joomla-cms/27432</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27432">issues.joomla.org/tracker/joomla-cms/27432</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
