### PR TITLE
Search form, accessibility fix

### PR DESCRIPTION
**Pull request by LivioCavallo**
### Summary of Changes
Added title attribute to input element.

### Testing Instructions
In J!3.7.5 create a Search menuitem.

### Expected result
The page is accessible.

### Actual result
The page is not accessible: the text input element will not pass accessibility checks, as it's lacking a title attribute.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7a076f89a167b0e82848c6d0af94b3507f77fa09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17683">issues.joomla.org/tracker/joomla-cms/17683</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7a076f89a167b0e82848c6d0af94b3507f77fa09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17683">issues.joomla.org/tracker/joomla-cms/17683</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by akritianand** [comment]
Hey can anyone explain which page was not originally accessible after creating a search menuitem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17683">issues.joomla.org/tracker/joomla-cms/17683</a>.</sub>

**Comment by brianteeman** [comment]
@akritianand the page with the search results from the search module or the page you create when creating a menu type search

**Pull request merged**
