### PR TITLE
[4.0] help sidebar onhover

### PR DESCRIPTION
**Pull request by brianteeman**
Partial PR for #34327

Adds the same onhover styling as seen in configuration options.

It does not have active styling as I think that will need to be done in JS?

after

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 40b0ca9efc37752565ca39f3c086d2f338df0772<br /><br />Thanks @brianteeman for creating the pull request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34461">issues.joomla.org/tracker/joomla-cms/34461</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 40b0ca9efc37752565ca39f3c086d2f338df0772<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34461">issues.joomla.org/tracker/joomla-cms/34461</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34461">issues.joomla.org/tracker/joomla-cms/34461</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
