### PR TITLE
[4.0] Replaced JApplicationHelper occurrences

### PR DESCRIPTION
**Pull request by marcochirienti**
### Summary of Changes
Replaced JApplicationHelper occurrences.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 59f88aa21a2435a17439d1bdd1bc9fd565c66561<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26971">issues.joomla.org/tracker/joomla-cms/26971</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 59f88aa21a2435a17439d1bdd1bc9fd565c66561<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26971">issues.joomla.org/tracker/joomla-cms/26971</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26971">issues.joomla.org/tracker/joomla-cms/26971</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
