### PR TITLE
Run composer in optimized mode

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #16881.

### Summary of Changes
Composer has an optimized mode, where they recommend to use in production. More information can be found in the [composer documentation](https://getcomposer.org/doc/articles/autoloader-optimization.md).

This pr activates that mode, which leads to bigger class map files and less IO. More infromation can be found in issue #16881.

### Testing Instructions
Just log in on the back end and open some articles on the front end.

### Expected result
All should work as expected, just faster.

### Actual result
All should work as expected.

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by laoneo** [comment]
As with the merge of #16754, this one can safely be merged, as a composer install in optimized mode was run there. This pr only adds the required configuration option to the composer.json file that the next `composer update` will not overwrite the optimized classmap files.
I did another `composer install` and there are some test classes showing up in the diff which should not being mapped.

**Comment by mbabker** [comment]
I'll merge this after https://github.com/joomla/joomla-cms/pull/16780 and https://github.com/joomla/joomla-cms/pull/17081 since theoretically this should be the simplest of the PRs to deconflict.

**Comment by laoneo** [comment]
I can run then another composer install, no worries.

**Comment by laoneo** [comment]
Merged with staging too.

**Pull request merged**
