### PR TITLE
[4.0] Searchtools tweaks

### PR DESCRIPTION
**Pull request by brianteeman**
As the atum scss for searchtools was moved recently this PR is a redo of #27240 and #27241

See the individual PR for details

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fad87a689a639fba581497179f64be47734175b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27458">issues.joomla.org/tracker/joomla-cms/27458</a>.</sub>

**Comment by infograf768** [comment]
Looks to me that the magnifyer border button is fine but that the Clear button is weird as it looks darker than the border of the Filter Options.

**Comment by brianteeman** [comment]
@infograf768 screenshot please - not sure I am looking in the right place

**Comment by brianteeman** [comment]
Closed. Not waiting forever for a reply

**Pull request closed without merging**
