### PR TITLE
Update en-GB.com_config.ini

### PR DESCRIPTION
**Pull request by parthlawate**
Pull Request for Issue #21398

### Summary of Changes

The Joomla Global Configuration has a Field to set the 'Server Time Zone'
Saying Server time zone gives a very wrong impression. The timezone to be set here has to be the Timezone for the Primary Audience of the website. Saying Server can confuse the end users. I might have bought hosting in the US so my Server is there.. But my website's primary Audience is in India. The current nomenclature can confuse people into setting the wrong timezone

I propose changing this to say 'Website Time Zone'
### Testing Instructions

Go to Global Configuration & confirm that the label is changed

### Expected result

Label should say Website timezone
### Documentation Changes Required

Any documentation about the Global Configuration will need change in text and screenshots

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0dda00bc7822c05bb9901d8a6ea58ffef0d412fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21399">issues.joomla.org/tracker/joomla-cms/21399</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
Can you make the pr against 3.9?

**Comment by parthlawate** [comment]
@laoneo Done Allon ! https://github.com/joomla/joomla-cms/pull/21400

**Comment by brianteeman** [comment]
Not at my computer to check but my gut feeling is that this is not correct

**Comment by infograf768** [comment]
Closing as there is a new PR towards 3.9
https://github.com/joomla/joomla-cms/pull/21400

**Pull request closed without merging**
