### PR TITLE
Refactory com_banners tracks export modal + new toolbar button layout

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue #10911 & PR #10927 (improve it).
#### Summary of Changes

**Download Tracks Modal:**
- Fix and improve HTML rendering (use <code>renderField</code>)
- No tooltip for File Name, as description is a bit long (and not always easy to use tooltip when long description).
- New form field type <code>note</code> for <code>File Name</code> description in a alert-info style.
- Tooltip placement bottom for <code>Compressed</code> label (prevent tooltip cropped at top when in iframe)
- Buttons in the BS modal footer
- Using new viewport dimensions
- **HATHOR** : modal was broken! This PR fixes it in Hathor Template, and add overrides to adapt rendering.

**New Generic Toolbar Button Layout:**
- appendButton using a new toolbar button layout:

```
$selector = $displayData['selector'];
$class    = isset($displayData['class']) ? $displayData['class'] : 'btn btn-small';
$icon     = isset($displayData['icon']) ? $displayData['icon'] : 'out-3';
$text     = isset($displayData['text']) ? $displayData['text'] : '';
?>
<button class="<?php echo $class; ?>" data-toggle="modal" data-target="#<?php echo $selector; ?>">
    <span class="icon-<?php echo $icon; ?>"></span>
    <?php echo $text; ?>
</button>
```
#### Testing Instructions

To be tested on staging or 3.6.0-beta
- Test on Isis template (api) and Hathor template (overrides)
- Go to **Components** > **Banners** > **Tracks**
- Click on <code>Export</code> toolbar button
- Check tooltip placement
- Test <code>Cancel</code> and <code>Export</code> buttons now in modal footer

**Isis admin template**
Before:
capture d ecran 2016-06-26 a 20 42 47

After:
capture d ecran 2016-06-25 a 17 04 16

**Hathor admin template**
Before:
capture d ecran 2016-06-26 a 20 37 30

After:
capture d ecran 2016-06-26 a 20 38 40

### CODE REVIEW

**Comment by RonakParmar** [comment]
@JoomliC Thanks for fixing tooptip issue.
One suggestion: I have applied this latest PR and found that we have scroll-bar in our iframe modal.
Checked that .jviewport-height50 { height: 50vh;} applied, Is it possible to set height:60vh or Is it dynamically applied to iframe?
It will remove the scroll-bar and will look nice.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 215efce2eeb2d9afdc48bcbf71bf8d76d895abe0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by JoomliC** [comment]
> One suggestion: I have applied this latest PR and found that we have scroll-bar in our iframe modal.
Checked that .jviewport-height50 { height: 50vh;} applied, Is it possible to set height:60vh or Is it dynamically applied to iframe?

Thanks @RonakParmar for feedback!
About new modal parameters for modal introduced in 3.6.0, this is set in the view here: https://github.com/joomla/joomla-cms/pull/10934/files#diff-4b21245c193bec415dbe082fd9486de3R96
(viewport dimensions introduced with this PR : https://github.com/joomla/joomla-cms/pull/10388)

But, if an issue with scrolling, should be related to this one (dynamically add of scrolling): https://github.com/joomla/joomla-cms/pull/9817

So, could you attached a screenshot of issue, as well as some information: screnn size, browser and its version, OS ?
It could help to see where your issue comes from (as scrolling should appear only when modal body content is too high for the rendered modal).

Thanks!

**Comment by RonakParmar** [comment]
Here is my system information.
PHP Built On : Linux 126-UBUNTU 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64
Database Version : 5.5.49-0ubuntu0.12.04.1
PHP Version : 5.4.45-3+donate.sury.org~precise+3
Web Server : Apache/2.2.22 (Ubuntu)

Joomla! Version : Joomla! 3.6.0-beta2 Beta [ Noether ] 16-June-2016 13:54 GMT
Joomla! Platform Version : Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by RonakParmar** [comment]
screen shot 2016-06-27 at 05 29 01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by JoomliC** [comment]
@RonakParmar you screen shot shows no issue in scrolling (that's good!).
But your screen view is a bit "panoramic".
Is it a resized window or a standard view of your device? (as 50/100 viewport height for standard screen size seems ok...)

@brianteeman does 50vh height was ok for you in Isis test of this PR ? (or a 60vh height could be better: https://github.com/joomla/joomla-cms/pull/10934/files#diff-4b21245c193bec415dbe082fd9486de3R96 ?)

**Comment by brianteeman** [comment]
After applying the PR it looks fine to me

**Comment by RonakParmar** [comment]
It's a standard view of my device, I do not change my screen size.

**Comment by JoomliC** [comment]
Thanks @brianteeman ! I have just updated a little the PR by not using viewport height which may not change a bit for you, and then works too for @RonakParmar's screen size ;-)

@RonakParmar Thanks for screen size!
Tested and confirm that's not good with this screen size.
In the same time, as the content is not high, i have removed the viewport height, to use only the ifram height, set now to 370px which seems to be the good value for this content.

Could you test back this PR with this minor adjustment, thanks!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 53400627026c8785d5d99382d41f0c2671e2cdc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 53400627026c8785d5d99382d41f0c2671e2cdc4<br /><br />No scroll-bar now. @JoomliC Thank you to fix this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by kalpesh681** [comment]
I have tested this item :white_check_mark: successfully on 53400627026c8785d5d99382d41f0c2671e2cdc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by JoomliC** [comment]
Thanks everybody for testing :+1:

**Comment by brianteeman** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10934">issues.joomla.org/joomla-cms/10934</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please let me know if you have holiday too than we can take that tasks :palm_tree:

**Pull request merged**
