### PR TITLE
[4.0] Fixes global config cache settings display

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue # .

### Summary of Changes

Re-Ordered and added new showon values

### Testing Instructions
View cache settings in the Joomla! Global config -> System. At present cache selection, is at the bottom? and options are shown when the cache is disabled. 

### Expected result

All cache options hidden when cache is disabled. Cache selection shouldn't be at the bottom.

### CODE REVIEW

**Comment by brianteeman** [comment]
Pretty sure the change of order is wrong. It was deliberately moved to the end to address an isdue

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 89c905a6e62ccab76ab9ba2acc15494e0a5fadab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14733">issues.joomla.org/tracker/joomla-cms/14733</a>.</sub>

**Comment by brianteeman** [comment]
See #12742 and #14649

**Comment by tonypartridge** [comment]
Closed since it was concluded they want to show more fields. 

I think it's poor UX to show all the time, and changing a method that's always worked. Now users are going to need to know what to put in the cache path too and question it. 

Example, developers quite often edit the global session to stop logging them out whilst in development and users would have always gone to the first text box. Now it is the cache time.

**Pull request closed without merging**
