### PR TITLE
[4.0]Update languages for TinyMCE

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35579.

### Summary of Changes
Updated languages done by TTs

Can be merged by maintainers by review.
But please wait for now, as I will add more languages as they come in.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
> Updated languages done by TTs


Is there a repo for the files?

**Comment by Bakual** [comment]
The TinyMCE project uses Transifex to do translations and our TTs can download the translation files from there (https://www.tiny.cloud/get-tiny/language-packages/).
However the files usually need some adjustments so they work with Joomla. Also language codes don't match. So we only include files proofread and adjusted by our translation teams.

**Comment by infograf768** [comment]
https://www.tiny.cloud/get-tiny/language-packages/ downloadable files may be marked as fully translated but are not.
This is why we have a specific tool to create the files from a duplicate of any file there.
[uconvert.php.zip](https://github.com/joomla/joomla-cms/files/7190273/uconvert.php.zip)

```
From TTs forum September 2 2013
Achal created for us a simple script. See above.

As you can see when editing one the tiny lang files, all utf8 characters are presented as /uabcd
Unreadable...

So, just pick up one of the files in https://www.tiny.cloud/get-tiny/language-packages/ 
change its name to fit, and edit in your favorite utf8 text editor.

Then load uconvert.php
http://localhost/uconvert.php

Copy/paste the content of your text file in the top text field.
Click "Convert"
Then copy the content of the bottom text field and create a new file for your language. Keep somewhere the readable version!
```

**Comment by zero-24** [comment]
As requested by @Bakual i have directly commited the update for de to this PR here as downloaded from tiny.cloud: https://github.com/Bakual/joomla-cms/commit/4be3582e9261923f53d7725a3370089d14344eca

**Comment by Bakual** [comment]
Thanks, looks fine to me.

**Comment by bembelimen** [comment]
> But please wait for now, as I will add more languages as they come in.

I moved it to draft state (so no accidentally merge), when ready, just convert it back to a regular PR to merge.

**Comment by Bakual** [comment]
@bembelimen It just needs to be merged before the next release. It's always ready to be merged (by review). So "draft" is wrong.

**Comment by wojsmol** [comment]
@Bakual Polish translation https://github.com/Bakual/joomla-cms/pull/18

**Comment by Bakual** [comment]
Thanks @wojsmol , merged it into this PR

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
