### PR TITLE
Revert "[a11y] change ordered list in blog-links to unordered list"

### PR DESCRIPTION
**Pull request by obuisard**
Reverts joomla/joomla-cms#40600, following concerns raised.

### CODE REVIEW

**Comment by richard67** [comment]
Should the reverted PR then be redone in 5.0? Or 6.0?

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 8d99cdbb13baa42835b5e2e3f41d20d19e6e75bb<br /><br />Would be nice to have this change in J5. With information of the a11y issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40625">issues.joomla.org/tracker/joomla-cms/40625</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8d99cdbb13baa42835b5e2e3f41d20d19e6e75bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40625">issues.joomla.org/tracker/joomla-cms/40625</a>.</sub>

**Comment by richard67** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40625">issues.joomla.org/tracker/joomla-cms/40625</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks Olivier

**Pull request merged**
