### PR TITLE
[4.0] Fix wrong error message on connecting mysql

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull Request for Issue #22961 

### Summary of Changes

Changed the error message.

### Testing Instructions
On installing Joomla 4.0, the error message appears on the ```Database Configuration``` screen when the installer fails to connect to mysql

### Expected result
A sensible error message

mysql_error

### Actual result
mysql_error original

### Documentation Changes Required
None

### CODE REVIEW

**Comment by hardik-codes** [comment]
@infograf768 @PhilETaylor please review this PR

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f9b8007ab2b9dfa1f0d4e33911baa8ca08a4e899<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23764">issues.joomla.org/tracker/joomla-cms/23764</a>.</sub>

**Comment by hardik-codes** [comment]
One more tester please

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f9b8007ab2b9dfa1f0d4e33911baa8ca08a4e899<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23764">issues.joomla.org/tracker/joomla-cms/23764</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23764">issues.joomla.org/tracker/joomla-cms/23764</a>.</sub>

**Comment by infograf768** [comment]
Thanks

**Pull request merged**
