### PR TITLE
[build/bump] Make bump update the links in the readme files also (md and txt)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR. Make bump.php script update the versions and links in readme files also.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Run `php build/bump.php -v 3.7.0`in joomla staging root
3. Check the readme files test links are changed

Hint: run `php build/bump.php -v 3.6.0-alpha2` to reset to previous version

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct. The readme file only refers to 3.x and not 3.x.y. If I read this PR correctly then the full 3.x.y will be used which will cause issues with the links

**Comment by andrepereiradasilva** [comment]
@brianteeman see https://github.com/joomla/joomla-cms/pull/10193/files

**Comment by brianteeman** [comment]
yes I know - that was my PR ;)

My point was that wont this PR change that from 3.x to 3.x.y which will
break the link
`https://docs.joomla.org/Joomla_3.6_version_history

On 30 May 2016 at 18:39, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> see
> https://github.com/joomla/joomla-cms/pull/10193/files
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10680#issuecomment-222532648>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Z9xYgLC0onxigD3M_dVtfrE_yklks5qGyDWgaJpZM4Ip8Zk>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
brian it will not change.
please test

**Comment by andrepereiradasilva** [comment]
```console
Version data:
- Main:                 3.7
- Release:              3.7.1
- Full:                 3.7.1-alpha1
- Build:
- Dev Level:            1-alpha1
- Dev Status:           Alpha
- Release date:         30-May-2016
- Release time:         18:17
- Release timezone:     GMT
- Creation date:        May 2016
```

it uses the main version, not the release

**Comment by brianteeman** [comment]
> If I read this PR correctly then the full 3.x.y will be used which will cause issues with the links

And i didnt<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10680">issues.joomla.org/joomla-cms/10680</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 222adf5e7fab4e22735e901fe4100851834f6766<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10680">issues.joomla.org/joomla-cms/10680</a>.</sub>

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 222adf5e7fab4e22735e901fe4100851834f6766<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10680">issues.joomla.org/joomla-cms/10680</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10680">issues.joomla.org/joomla-cms/10680</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
