### PR TITLE
[4.0] Status and main-nav overflow fix (sidebar closed)

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Couple of fixes for when the sidebar is closed...

- Status bar width 
- Remove sidebar horizontal scroll 

### Testing Instructions
Apply patch and close sidebar. Check status bar at the bottom of the screen

### Before Patch
sidebar-closed1

### After Patch
sidebar-closed2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2a9dabd2f8712c3e1408ce6501efb5c88641bf37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15936">issues.joomla.org/tracker/joomla-cms/15936</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 2a9dabd2f8712c3e1408ce6501efb5c88641bf37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15936">issues.joomla.org/tracker/joomla-cms/15936</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by C-Lodder** [comment]
@wilsonge can be merged

**Pull request merged**
