### PR TITLE
Fixing "active" category detection in mod_articles_categories

### PR DESCRIPTION
**Pull request by artur-stepien**
mod_articles_category detects category as active only in **category** view. Where this should also work for **categories** view. This fixes the problem.

Pull Request for Issue # .

### Summary of Changes
Detect active category also in **categories** view

### Testing Instructions
Create articles categories tree as follows:
A
A -> B
A -> C
A -> C -> D
A -> C -> E

Create new module of type "mod_articles_categories"
Set **Parent Category** as `A`
Set **Show Subcategories** to `Yes`
As **Position** set any position that will display the module.
Set the module to display on all pages.
Save the module.
Create a new menu item with **Menu Item Type** set to `List All Categories`, then set **Select a Top Level Category** to `C`.
Go to front-end
Find the menu item you just created and click it.

### Expected result
Category **C** in **mod_articles_categories** you created before should have the "active" class on `<li>` element.

### Actual result
**C** in articles categories module does not have the `active` class.

### CODE REVIEW

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on 41eac93fd75a0fb8422867677d364d6a1f475630<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26330">issues.joomla.org/tracker/joomla-cms/26330</a>.</sub>

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on 41eac93fd75a0fb8422867677d364d6a1f475630<br /><br />After applying patch, the active class is also set in the categories view<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26330">issues.joomla.org/tracker/joomla-cms/26330</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26330">issues.joomla.org/tracker/joomla-cms/26330</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
