### PR TITLE
[4.0] resize webauthn logo

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #30180

No need to load a 200kb image when its only being displayed on a button

### Testing Instructions
npm ci and make sure the images in media\plg_system_webauthn\images are 2kb max and not > 200kb

### CODE REVIEW

**Comment by Quy** [comment]
Please make background transparent.

**Comment by brianteeman** [comment]
oops

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aabc8bddab64c241ad3e75d4787de5065b30002a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30846">issues.joomla.org/tracker/joomla-cms/30846</a>.</sub>

**Comment by HLeithner** [comment]
Do we have the copyright information for this image?

**Comment by brianteeman** [comment]
See https://github.com/webauthn-open-source/webauthn-logos

**Comment by HLeithner** [comment]
I did only a quick search and didn't found it, thanks.

But looking at the repo there is a .ai file wouldn't it be better to use an svg?

**Comment by brianteeman** [comment]
> But looking at the repo there is a .ai file wouldn't it be better to use an svg?

I have no opinion on that - its a much bigger code change though

**Comment by HLeithner** [comment]
> > But looking at the repo there is a .ai file wouldn't it be better to use an svg?
> 
> I have no opinion on that - its a much bigger code change though

if would be nice if you can do it.

**Comment by brianteeman** [comment]
I wouldn't know where to start

**Comment by HLeithner** [comment]
Then we start with this version and if someone want to replace it, it would be good.

thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
