### PR TITLE
Two typos detected by a Translator

### PR DESCRIPTION
**Pull request by Bakual**
Two small typos detected by our translator Peter Michnica.

One is a missing dot and the other a wrongly closing (instead of opening) HTML tag.

Review should be enough. But you can of course try to see where the string appears (should be sampledata related)

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d89446abd24b98f74e2d1f9404145584cbb422c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31559">issues.joomla.org/tracker/joomla-cms/31559</a>.</sub>

**Comment by infograf768** [comment]
rtc. Obvious.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31559">issues.joomla.org/tracker/joomla-cms/31559</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d89446abd24b98f74e2d1f9404145584cbb422c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31559">issues.joomla.org/tracker/joomla-cms/31559</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
