### PR TITLE
[4.2] Fix save tags assignment

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #39219 (and other similar issues)

### Summary of Changes
When you assign some tags to an item (article for example), if some of these tags are not in **top 30 most used tags**, it won't be displayed as selected when you edit that item. That makes you think that assigned tags assignment are not saved properly for the item (while it is already saved, when you browse the item on frontend of your site, you will see that all selected tags are displayed for the item properly). This PR just fixes that logic error.

### Testing Instructions
1. Create more than 30 tags in your Joomla installation
2. Edit an article, assign more than 30 tags to the article, save it
3. Edit the article again, check the list of assigned tags

### Actual result BEFORE applying this Pull Request
Not all assigned tags are displayed as selected

### Expected result AFTER applying this Pull Request
All assigned tags are displayed as selected

### CODE REVIEW

**Comment by mrownicki** [comment]
Tested but still after save i don't see all tags.

**Comment by absillitoe** [comment]
I hope it's okay for me to chip in here. If not, please let me know. I have a similar problem. At first, I thought it was when I had more than 4 tags assigned to an article, however, in checking, it seems to be a problem with particular sets of tags which, in this case, have a parent tag. (However, most other sets with a parent tag do not have this problem.)

I am on Joomla 4.2.5 with the Cassiopeia template. 

It seems to be mainly with one set of 9 tags having the same parent.

When I open an article with these tags selected, they are not displayed, whereas the others are displayed. If I then save the article, I lose these additional tags. I can put them back only by selecting the additional tags and then doing a "save and close". 

In the tags manager, when I edit these particular tags, the parent tag is not shown: it's as if the tag has no parent. Most of the other tags (except the few most recent ones) do not have this problem.

When I look in the database, these tags all have the correct parent. This problem does not exist in the Joomla 3 website which I upgraded and the database maintenance indicated that everything was okay before the upgrade. I compared these tags in the databases on Joomla 3 and Joomla 4 and cannot see any difference. 

Would be happy to give you access to this website if you think it might be a Joomla issue and if that would be useful. For the moment, I am flummoxed by this problem. Everything seemed to be okay, until I discovered this strange behaviour with the tags.

Thanks,

Alan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by joomdonation** [comment]
@absillitoe Happy to take a look at your site to see if I can discover the root reason of the error and get it fixed. As mentioned, I will need to have :

1. Super users account of your site
2. Tell me ID of the article which is having the issue
3. Tell me IDs of tags which should be selected when you edit the article

If that's OK for you, then send an email to tuanpn@joomdonation.com and I will take a look at it and hopefully, get it sorted.

**Comment by absillitoe** [comment]
@joomdonation Thanks a lot. I will prepare and send you an email.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by absillitoe** [comment]
Thank you very much, Mr. Tuan Pham Ngoc. Your fix resolved the issue I was experiencing.

**Comment by joomdonation** [comment]
Just for information, I went to the site which @absillitoe provided, applied the change and it solved the issue for him

**Comment by absillitoe** [comment]
To be more precise, after the fix was installed, the missing tags are now displayed when editing the articles in question and, when editing these tags, the parent tag is shown. So the problem I experienced in Joomla 4.2.5 seems to have been completely resolved. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d7b61518dbb731f7b96fb9510d85eb79d070c214<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by joomdonation** [comment]
@hytsch @angieradtke Would be great if you could check to see this PR solves your issue.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by richard67** [comment]
RTC because we have 2 tests. It's just not so visible because it seems @absillitoe hasn't used the "Test this" button but the "Alter test" button to mark the test result.

**Comment by joomdonation** [comment]
Thanks @richard67. I set this back to Pending because I want the people who reported the issue like @hytsch @angieradtke confirm that this PR fixed their issues first (there were people reported that this does not fix their issues but I don't know if they applied the patch properly).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by angieradtke** [comment]
Great Tuan! 
tuan

**Comment by joomdonation** [comment]
Thanks @angieradtke . So it solved your issue, right ? Please confirm. Thanks !

**Comment by richard67** [comment]
@angieradtke ... or use the blue "Test this" button in the issue tracker to submit your test result, like it should be done.

**Comment by angieradtke** [comment]
@richard67    you know me, sill looking for this button

**Comment by angieradtke** [comment]
I have not tested this item.<br /><br />Works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by angieradtke** [comment]
I have tested this item :white_check_mark: successfully on d7b61518dbb731f7b96fb9510d85eb79d070c214<br /><br />Works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by mrownicki** [comment]
I retest path remove and install again. 
Now it works ok. Save more than 30 tags and visible OK.

**Comment by richard67** [comment]
> I retest path remove and install again. Now it works ok. Save more than 30 tags and visible OK.

@mrownicki Could you also mark your test result in the issue tracker? for this, go to https://issues.joomla.org/tracker/joomla-cms/39254 , use the blue "Test this" button at the top left corner, select your test result and submit. Thanks in advance.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by absillitoe** [comment]
@richard67 Sorry if I didn't do things correctly. Please let me know if I still need to do something. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39254">issues.joomla.org/tracker/joomla-cms/39254</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
