### PR TITLE
[4.0] Add extension name/id to uninstall message if extension is locked, redo of PR 28916

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This is a redo of PR #28916 . Thanks @ReLater for the implementation.

- Change lang string COM_INSTALLER_UNINSTALL_ERROR_LOCKED_EXTENSION.
- Use sprintf to display extension name and id.

### Testing Instructions
- 4.0 nightly build of today (Wednesday, 06 May 2020) or later.
- Go to extensions manager (`administrator/index.php?option=com_installer&view=manage`).
- Select many locked extensions.
- Click `Uninstall` and check the messages at the top.
- CLI: Use `php cli/joomla.php extension:remove xxx`, with `xxx`being an extension ID for a locked core extension, e.g. `Action Log - Joomla`.

### Actual result

In backend in extensions manage:

CLI:
pr-28960_before_cli

### Expected result after applying PR

In backend in extensions manage:
pr-28960_after_backend

CLI:
pr-28960_after_cli

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 580ff139c4bd93650b45e5f3510d5e7b667da572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28960">issues.joomla.org/tracker/joomla-cms/28960</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk Please test.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 580ff139c4bd93650b45e5f3510d5e7b667da572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28960">issues.joomla.org/tracker/joomla-cms/28960</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28960">issues.joomla.org/tracker/joomla-cms/28960</a>.</sub>

**Comment by infograf768** [comment]
Tks to both

**Pull request merged**
