### PR TITLE
[4.0] acl border

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #28316 .

remove the margin left (or right) from the tab-pane

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 256ca1dca483838e2e99d336d6fc14d565b51e5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28317">issues.joomla.org/tracker/joomla-cms/28317</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 256ca1dca483838e2e99d336d6fc14d565b51e5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28317">issues.joomla.org/tracker/joomla-cms/28317</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28317">issues.joomla.org/tracker/joomla-cms/28317</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
