### PR TITLE
Improve UX for login / logout redirect options

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue #11176  .

### Summary of Changes
- Removed return false if Menu Item is selected and URL is filled
- Added clear the field to avoid conflicts

Test instructions:

Before the Patch:
1. Create or open a Login Menu Item
2. chose the Internal URL redirect type in login or logout (doesn´t matter)
3. type in for example just index.php
4. Save
5. change the redirect type to Menu Item and select any Menu item
6. Click on save

Actual result: You get an warning message "Only one of the login redirect fields should have a value." the new selection is not saved. -> This is no good UX and might confuse a lot of users

After the patch:
1. Create or open a Login Menu Item
2. chose the Internal URL redirect type in login or logout (test both)
3. type in for example just index.php
4. Save
5. change the redirect type to Menu Item and select any Menu item
6. Click on save.

The Internal URL redirect will be cleared, if you select an Menu Item Type and save.
The Menu Item Type will be cleared, if you select Internal URL and save.

### CODE REVIEW

**Comment by laoneo** [comment]
As the issue became too big to figure out what the problem is. Can you describe how we can reproduce the issue that we can help you with the code.

**Comment by infograf768** [comment]
We can't have both the redirect_url and redirect_menuitem filled as these params are one or the other.
If one does that, then a Warning is displayed:
`Only one of the login redirect fields should have a value.`
and the form is not saved.

**Comment by coolcat-creations** [comment]
Yes, sure :)
1) Create or open a Login Menu Item 
2) chose the Internal URL redirect type in login or logout (doesn´t matter)
3) type in for example just index.php
4) Save
5) change the redirect type to Menu Item and select any Menu item
6) Click on save

Actual result: You get an warning message "Only one of the login redirect fields should have a value." the new selection is not saved.

Expected behaviour: 
1) The login and logout first check for the chosen redirect method and take the saved parameter behind that (Thats what i wanted to achieve with my codechange in this PR)

2) Another possibility: Clear the second field when changing the redirect type

image

Thank you!

**Comment by infograf768** [comment]
> Another possibility: Clear the second field when changing the redirect type

AND a value is entered in the first field... Otherwise it would clear the second field whenever someone switch redirects just to check what it does...

**Comment by coolcat-creations** [comment]
@infograf768 yes indeed, thank you - but maybe first option is easier, i just don´t understand why my chosen field skips always to Internal URL in this PR

**Comment by infograf768** [comment]
I guess you first have to delete the content of the url field. Here it works fine.

**Comment by coolcat-creations** [comment]
That´s the UX issue i mention, i don´t want to force the user to delete the input field, because the user made the decision to chose another method. It´s not a nice workflow...

**Comment by infograf768** [comment]
then it is certainly not by the code you propose that this will be solved.
We DO have to set false if both are filled.

**Comment by cpfeifer** [comment]
This is a little over my head in terms of a fix, maybe a stronger programmer than myself can help us out here. 

As mentioned in the original issue, the problem seems to be stemming from the numeric check located at component/com_users/controllers/users.php line 165, or one of the other conditionals. 

I'm thinking we need another check which only checks for the actively selected option, or a way to only use the actively selected option in the menu item. I believe the error comes from not having a distinction between the actively selected item and the non-selected item, either menu item or internal URL.

Like I said, this is a little bit over my head and there's a lot going on there, but it seems like a solution would be relatively simple to implement. All ideas and suggestions are appreciated.

**Comment by cpfeifer** [comment]
Theoretically it should be fine to have values stored in both fields as only one of the values will actually be used. When there are values assigned to both fields it causes the error. We just need a way to get around that.

**Comment by dgt41** [comment]
@coolcat-creations https://github.com/coolcat-creations/joomla-cms/pull/6 that should be enough

**Comment by laoneo** [comment]
Does @dgt41 patch made this PR ready for testing, or is there still some stuff open?

**Comment by infograf768** [comment]
I am going to test this right now, in mono and multilingual.

**Comment by coolcat-creations** [comment]
Don´t test yet, does´t work for now

**Comment by infograf768** [comment]
Indeed

**Comment by coolcat-creations** [comment]
I revert my changes because the method from @dgt41 clears the other field....
but it doesn´t work yet... maybe someone can have a look

https://gyazo.com/b33d075fe1b80da5cb14686f8f490c8e

**Comment by dgt41** [comment]
@coolcat-creations one more try: https://github.com/coolcat-creations/joomla-cms/pull/7

**Comment by coolcat-creations** [comment]
Thank you!
I merged it but still the same issue that it switches back to Menu Item ;(

**Comment by dgt41** [comment]
> it  switches back to Menu Item

The login or the logout?

**Comment by coolcat-creations** [comment]
yeah the login works, the logout jumps back to Internal URL all the time

**Comment by coolcat-creations** [comment]
Thank you @dgt41 works now! PR can be tested now i update the test instructions immediately @infograf768 @laoneo would be great if you can test

**Comment by infograf768** [comment]
will test later on. tomorrow likely

**Comment by infograf768** [comment]
@coolcat-creations 
My test show that **when saving a login form**, we have 2 cases:

A. If both the Internal URL field and Menu Item fields have values. 
In this case the redirection is set depending on the button highlighted for the Choose Login redirect Type and the other value is deleted.

B. When we have only one value set, for example for the Menu Item field and the highlighted button is set to Internal URL, the Menu Item field value is deleted and then there is no specific redirection.

Is it what you expect?

**Comment by coolcat-creations** [comment]
A shouldn´t happen with this PR, if you select and save another redirection type the other field is cleared so the system has no issue regarding the "inputs behind". So no two fields should be possible to be filled at once....

**Comment by lausianne** [comment]
If just the error message was clearer and gave a hint to the solution, I'd consider that a fix already. No extensive programming or testing needed ... (but of course, I do appreaciate real fixes, too)

**Comment by korneliusz401** [comment]
I have tested this item :white_check_mark: successfully on 1eba19c8072d688483162d056e660d039837d85b<br /><br />I have tested both Login and Logout successfully. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13113">issues.joomla.org/tracker/joomla-cms/13113</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 1eba19c8072d688483162d056e660d039837d85b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13113">issues.joomla.org/tracker/joomla-cms/13113</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
