### PR TITLE
Correcting Isis dropdown z-index (see #7608)

### PR DESCRIPTION
**Pull request by infograf768**
As title says. See testing procedure in https://github.com/joomla/joomla-cms/issues/7608

Before patch:
screen shot 2015-08-01 at 10 46 53

After patch:
screen shot 2015-08-01 at 11 47 00

### CODE REVIEW

**Comment by Fedik** [comment]
not sure, maybe I missed something,
but for me here no issue, it works with old z-index value (tried in Chrome and Firefox):
screen 2015-08-02 11 53 34 414x400

also I see that `#status` bar has `z-index: 1030`

**Comment by Fedik** [comment]
UPD
I just tested on j 3.4.3 and there I got the described issue,
but seems it already fixed in 3.4.4 , in some way,
someone else can confirm?

**Comment by infograf768** [comment]
This is not the z-index I get for the status bar.
It is z-index 1050 here:
screen shot 2015-08-02 at 11 09 39

**Comment by infograf768** [comment]
My test is on 3.4.4 dev

**Comment by infograf768** [comment]
Looks like the test has to be done on a multilang site.
inside the div status, we do have a div multiLangModal with class modal
That class contains z-index 1050

Therefore my PR solves the issue here and has no bad effect in monolanguage

**Comment by Fedik** [comment]
hm, very strange, maybe I realy something missed
but you seen? https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/css/template.css#L3339 it is 1030

**Comment by Fedik** [comment]
ok, I understand :smile:

**Comment by infograf768** [comment]
One more tester!

**Comment by Fedik** [comment]
I can reproduce the issue when enable module "Language status",
 seems, this module add:
```css
.navbar-fixed-bottom {
    z-index: 1050;
}
```
maybe we can just remove it there?

**Comment by Fedik** [comment]
that does not looks very usefull :wink:  https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_multilangstatus/tmpl/default.php#L15

**Comment by Fedik** [comment]
it was introduced in #4575 ... @dgt41 can you check is it still need there?

**Comment by infograf768** [comment]
We need to keep the z-index 1050 in div modal as it is a bootstrap css
https://github.com/joomla/joomla-cms/blob/staging/media/jui/css/bootstrap.css#L6138-L6159

BTW, I took off the line here: https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_multilangstatus/tmpl/default.php#L15 and it does not work:
screen shot 2015-08-02 at 11 46 33

as the issue remains, It is easier imho to just increase the z-index as proposed in this PR.

**Comment by Fedik** [comment]
ok, I just thought we can make "all in one place", for avoid confusing in future :smile: 

Current patch still good, anyway :wink:

**Comment by infograf768** [comment]
My mistake... changed code on another test site.

The issue is diffe
rent if we take off that line in the multilangstatus module: it displays the modal all greyed

**Comment by dgt41** [comment]
Works ok here

**Comment by dgt41** [comment]
@Fedik the problem was that multilingual status modules is by default assigned to the bottom bar and the z-index made it unusable since the modal will remained hidden…. I didn’t realize at that time that this will backfire for chosen lists

**Comment by dgt41** [comment]
@infograf768 @Fedik shall we move multilane status from the bottom bar to cpanel? Will solve some inconsistencies, that still exist (e.g. reducing the browser width makes the modal go away)

**Comment by Fedik** [comment]
@dgt41 for me it is fine where it is now :wink:

**Comment by infograf768** [comment]
Moving the multilanguagestatus module to CPanel was considered and rejected when we implemented this feature as ot may be needed at any time when working on multilang (setting languagefilter plugin, setting switcher module(s), setting content languages, setting Home menu items).

2 good tests: Please RTC for 3.4.4

**Comment by dgt41** [comment]
@infograf768 ahh ok, I didn’t know that

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7609">issues.joomla.org/joomla-cms/7609</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you, @infograf768!

**Pull request merged**
