### PR TITLE
Tag Entry Mode description

### PR DESCRIPTION
**Pull request by brianteeman**
Display the existing description

Pull Request for Issue #38553  .

Expected result after pr
image

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 39fe05144a08c45d95013351d3f27ff6c2f0c4d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38620">issues.joomla.org/tracker/joomla-cms/38620</a>.</sub>

**Comment by Franzwohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 39fe05144a08c45d95013351d3f27ff6c2f0c4d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38620">issues.joomla.org/tracker/joomla-cms/38620</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 39fe05144a08c45d95013351d3f27ff6c2f0c4d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38620">issues.joomla.org/tracker/joomla-cms/38620</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38620">issues.joomla.org/tracker/joomla-cms/38620</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
