### PR TITLE
[4.0] Use the Bootstrap 4 classes in login

### PR DESCRIPTION
**Pull request by htmgarcia**
Pull Request for Issue # .

### Summary of Changes
Use the Bootstrap 4 classes in login layout from users component. This replaces the old Bootstrap 2 classes.

### Testing Instructions
Please note: you can't test this while using cassiopeia template due insert CSS for bootstrap 2 classes such as `control-group`

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@htmgarcia please **do not** use the bootstrap grid! We are trying to move things forward here and use the css grid layout and eventually **not** ship Bootstrap grid. Take a look at what @ciar4n already did

**Comment by carlitorweb** [comment]
@dgrammatiko may I ask, why the bootstrap grid (something is tested well) is not it going to be used inside Joomla? I ask mainly out of curiosity.

**Comment by mbabker** [comment]
HTML driven grids have a plethora of problems in their own right.  CSS natively supports a grid system.  Use it...

https://hackernoon.com/how-css-grid-beats-bootstrap-85d5881cf163

**Comment by carlitorweb** [comment]
Thank @mbabker . I was inside this argument:

> And that might be an argument in favour of Bootstrap for some people: you don’t have to worry about CSS in order to create a simple grid, as you simply define the layout in the HTML.

That is why i asked.

**Comment by htmgarcia** [comment]
Hi @dgrammatiko,
may I know how to find this, please
> Take a look at what @ciar4n already did

**Comment by htmgarcia** [comment]
Hi @mbabker, 
my confusion here is why Joomla 4 relies mainly on bootstrap 4 but we *want* to use it partially? 

I appreciate your comments.

**Comment by htmgarcia** [comment]
@carlitorweb agree with that argument!

**Comment by mbabker** [comment]
> my confusion here is why Joomla 4 relies mainly on bootstrap 4 but we want to use it partially?

You want to repeat the "why is core still using X framework 4 years after it stopped getting updates" discussion?

**Comment by htmgarcia** [comment]
@mbabker 

> You want to repeat the "why is core still using X framework 4 years after it stopped getting updates" discussion?

If we stick with those Bootstrap 2 classes in the HTML is worst than what you just said, IMHO.

In addition, according [to the roadmap](https://developer.joomla.org/roadmap.html#4), **New core UI based on Bootstrap 4** is one of the main features.

**Comment by mbabker** [comment]
The key word there is "based".  It means we are using elements of Bootstrap, but we aren't 100% vendor locking the new templates the same way Isis and Protostar were (inherently vendor locking the entire Joomla 3.x series to Bootstrap 2).

I don't do UI work very consistently.  But in almost every project where I have been doing work using a HTML based Flexbox grid (such as Bootstrap's), I have run into issues that cannot be resolved with an HTML built grid that are addressed in the use of CSS Grid.  It is time we adapt to newer technologies.

**Comment by htmgarcia** [comment]
@mbabker agree to disagree. Consistency is important!

**Comment by dgrammatiko** [comment]
@htmgarcia css grid already present: https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_css-grid.scss

**Comment by dgrammatiko** [comment]
> why the bootstrap grid (something is tested well) is not it going to be used inside Joomla?

It **will** be used in the backend template. We hope we can drop it in the front end...

**Comment by nicksavov** [comment]
CSS Grid looks very interesting. 

Why is the Bootstrap grid going to be used in the backend template, but not the frontend?

**Comment by dgrammatiko** [comment]
> Why is the Bootstrap grid going to be used in the backend template, but not the frontend?

Couple reasons:
- we don't really care for performance in the backend
- it's easier for goofy devs to use the grid of BS
- we might not have the manpower to actually implement this atm

**Comment by nicksavov** [comment]
Thanks

**Comment by htmgarcia** [comment]
Closing since BS 4 grid system is not being implemented in frontend.

**Comment by carlitorweb** [comment]
> we don't really care for performance in the backend

IMO J should worry this

**Comment by dgrammatiko** [comment]
> IMO J should worry this

It's not a problem for the backend, let me explain:
- First page for the back end is the login page, were the BS will be loaded and cached. Every other page after the login will use the cached version of BS.
- That is the main difference with the front end, in the front end you need the best performance for the first time visitors, which will never happen if you include >250kb of render blocking css! Bootstrap is great if it's used for it's intended scope: rapid prototyping, not production code!!!

**Comment by carlitorweb** [comment]
> if you include >250kb of render blocking css

That if you include all the file. But you can decide which part of the file used on each page, and no include all the file.
Anyway, I not the best men for talking about this, for me, any frontend solution has its pros and cons. Just need, all focus on one, and done.
Thank you @dgrammatiko

**Pull request closed without merging**
