### PR TITLE
Fix errors exposed by strict and also improve js

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes

This is just #12544 plus some additional improvements.
While that older PR was aimed only at fixing the "strict" errors, this one fixes other problems.
In particular, button groups (radio buttons) will now work properly when used inside of subforms. 
Same for Chosen selectors that use coloring based on state. 
Also, delegation is used to handle various events. This has several benefits. 

This is only a rewrite of the first part of this file. There is likely much more that can be improved. 

### Testing Instructions

This file only affects the administrator when using the Isis template so use that. 
First of all, nothing should be broken. This mainly affects Chosen, radio button groups, and tooltips. So check any pages that have those things.

The main improvements apply to subforms. Subforms with radio buttons set up as `btn-group` should be tested. There are probably none of these in Joomla because they didn't really work before this patch. So make one and test it. Same goes for Chosens used in subforms with the `chzn-color-state` class. 

### Expected result

When you dynamically add a subform row that contains radio buttons, Chosen, or tooltips, these things should be initialized properly in the new row. Before this patch they were not. 

### Actual result

Oh, it works.

### Documentation Changes Required

Probably not. Unless there were previously some documented warnings about using radio buttons or Chosens in subforms. If so, those warnings may be deleted as they will no longer apply.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
If you want to test subforms, there's one here: `plugins/system/redirect/form/excludes.xml`
This creates a repeatable subform in the Redirect plugin config. If you add some fields this file, you can easily test that they are working properly.

**Comment by okonomiyaki3000** [comment]
This 'drone' failure seems to have nothing at all to do with these changes.

**Comment by Quy** [comment]
Can you confirm that this addresses the same things as #19722?

**Comment by okonomiyaki3000** [comment]
@Quy This PR addresses the Isis template only, #19722 addresses beez3 and protostar as well. Since this one is on top of  #12544, it also includes the "strict" fixes which really should have been merged by now. Other than that, it's really an issue of which adds more overhead and complexity to the code and which one reduces it. I'll recuse myself from sharing any opinion on that matter.

**Comment by okonomiyaki3000** [comment]
I've created #20224 and #20225 to fix the same issues in Beez3 and Protostar. These three together are an alternative to #19722

**Comment by Sophist-UK** [comment]
As the author of #19722 I am happy to close my PR, and for this PR and #20224 / #20225 to replace them - though I hope @okonomiyaki3000 will consider and include my recent comments in #19722.

**Comment by dgrammatiko** [comment]
Just few comments here:
- First of all thanks for this PR
- The js functionality for the group buttons **does not** belong to the template, it must be triggered in the layout of the checkboxes (or whatever the layout name is that renders those buttons). These are joomla fields and the js should be there! 
- Unfortunately this cannot be done in J3 without risking breaking a lot of components/plugins/modules
- For J4 these buttons (as all the rest of the fields) will be done using custom elements (one of the good things with this approach is that we don't need and coupling [events or callback] for the subform)
- It would be greatly appreciated if you can do a PR against 4.0-dev to remove the jQuery dependency and make this a custom element and also couple it to the actual layout. That is already in our todo list: https://github.com/joomla/joomla-cms/issues/19427

**Comment by Quy** [comment]
Is is also possible to include/fix "modal" type as reported in #11805?

**Comment by okonomiyaki3000** [comment]
@Quy It's not appropriate to include it in this PR but yes, I can fix that.

**Comment by okonomiyaki3000** [comment]
LOL, wait.... This is going to take more than most of these. I better jump in over there but please don't think of it as related to this PR and don't expect the fix very soon.

**Comment by okonomiyaki3000** [comment]
What are we gonna do about this drone failure? Is this for real? I don't buy it.

**Comment by okonomiyaki3000** [comment]
Just make it run again. I bet it works this time.

**Comment by Quy** [comment]
OK to close #12544 ?

**Comment by infograf768** [comment]
Drone restarted

**Comment by okonomiyaki3000** [comment]
I don't know why this would fail. This PR has nothing to do with jquery.ui.sortable or whatever.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5e66f87b68cbad5be6821a211c1655ede8587084<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20221">issues.joomla.org/tracker/joomla-cms/20221</a>.</sub>

**Comment by roland-d** [comment]
@okonomiyaki3000 I only noticed this PR after merging #12544 and I think because of that merge we have a conflict now. Could you update this PR please?

**Comment by okonomiyaki3000** [comment]
Rebased with latest staging. Should be correct.

**Comment by roland-d** [comment]
@kneisel @FPerisa Can you please test this one also? Thank you.

**Comment by okonomiyaki3000** [comment]
Don't believe appveyor, it just timed out.

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 1a09ee9cfa340cf26a7929a92c23e7a1cf71bd1f<br /><br />Subforms are working with this patch, even when I click on the plus.

For testing I added this to excludes.xml:
```
<field name="myradiovalue"
       type="radio"
       default="0"
       label="Select an option"
       class="btn-group">
   <option value="0">1</option>
   <option value="1">2</option>
</field>
<field name="myselectvalue"
       type="list"
       default="0"
       label="Select an option"
       class="chzn-color-state">
   <option value="0">nimm</option>
   <option value="1">mich</option>
   <option value="2">nicht</option>
</field>
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20221">issues.joomla.org/tracker/joomla-cms/20221</a>.</sub>

**Comment by ghost** [comment]
@viocassel can you please retest?

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1a09ee9cfa340cf26a7929a92c23e7a1cf71bd1f<br /><br />It works :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20221">issues.joomla.org/tracker/joomla-cms/20221</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20221">issues.joomla.org/tracker/joomla-cms/20221</a>.</sub>

**Pull request merged**
