### PR TITLE
[4.0] Fix markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add closing `</form>` tag.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5943f492b43742a04ac7f474a9f4c49d307d0e0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26127">issues.joomla.org/tracker/joomla-cms/26127</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 5943f492b43742a04ac7f474a9f4c49d307d0e0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26127">issues.joomla.org/tracker/joomla-cms/26127</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
