### PR TITLE
[4.0] Fall back to system template when template file not found

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes small regression from https://github.com/joomla/joomla-cms/pull/30192.
Removes unnecessary file lookup.
Removes parent language file loading when template has no parent.

### Testing Instructions

Enter a URL with `tmpl` parameter containing non-existing template file. E.g. `tmpl=foo`.

### Actual result BEFORE applying this Pull Request

Cassiopeia template is loaded without parameters, logo changed to sitename.

### Expected result AFTER applying this Pull Request

Unstyled system template is loaded.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9d51a194d09ddbf3bafb4c426f0cbb960c8b7693<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30857">issues.joomla.org/tracker/joomla-cms/30857</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 9d51a194d09ddbf3bafb4c426f0cbb960c8b7693<br /><br />OK!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30857">issues.joomla.org/tracker/joomla-cms/30857</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30857">issues.joomla.org/tracker/joomla-cms/30857</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
