### PR TITLE
[4] Template. Allow manifest tag inheritable = 0 or empty

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
Allow tag `<inheritable>0</inheritable>` in `templateDetails.xml`. Use `empty()` instead of `!isset()`.

### Testing Instructions
- Install test template https://github.com/GHSVS-de/GHSVSThings/raw/master/relaterquatch/nonamespacedummynoparent.zip (stolen from @HLeithner).
- The `templateDetails.xml` looks like this (see `<inheritable>0</inheritable>`):

```
<?xml version="1.0" encoding="utf-8"?>
<extension version="4.3" type="template">
	<name>nonamespacedummynoparent</name>
	<creationDate>2022-10-21</creationDate>
	<author>Me</author>
	<authorEmail>joomla@invalid.domain</authorEmail>
	<authorUrl>http://example.com</authorUrl>
	<copyright>Copyright (C) All rights reserved.</copyright>
	<version>1.0</version>
	<description>Test template for namespaces no namespace with no parent</description>
	<inheritable>0</inheritable>
	<files folder="templates/nonamespacedummynoparent">
		<folder>helpers</folder>
		<filename>index.php</filename>
		<filename>templateDetails.xml</filename>
	</files>

	<positions>
		<position>mainmenu</position>
	</positions>
</extension>
```
- In backend go to templates (not styles).
- Click template link "Nonamespacedummynoparent Details and Files"

### Actual result BEFORE applying this Pull Request
A error message:

`The template folder is not writable. Some features may not work.`

grafik

### Expected result AFTER applying this Pull Request
No error message

### Comment
My build procedure for templates fills tags like `inheritable` using placeholders like `<inheritable>{{inheritable}}</inheritable>`. So I think values `0`, `1`, `empty` should be accepted without a misleading error message.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ReLater** [comment]
BTW: The issue came up while testing https://github.com/joomla/joomla-cms/pull/39011

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ae0b1efcd9cf571a63c477f4d68f1e2a0901c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39329">issues.joomla.org/tracker/joomla-cms/39329</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9ae0b1efcd9cf571a63c477f4d68f1e2a0901c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39329">issues.joomla.org/tracker/joomla-cms/39329</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39329">issues.joomla.org/tracker/joomla-cms/39329</a>.</sub>

**Comment by fancyFranci** [comment]
One less error message. Thanks!

**Comment by ReLater** [comment]
Please revert this pr. See https://github.com/joomla/joomla-cms/issues/39934

**Comment by ReLater** [comment]
See also pr https://github.com/joomla/joomla-cms/pull/39943 that reverts this change in J!4.3

**Pull request merged**
