### PR TITLE
[4.0] Show a warning if JSON response is corrupted while login

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #30898 #27786 and there some others .

### Summary of Changes
Show a warning to user if ajax login got incorrect JSON response

### Testing Instructions
run `npm install` and follow one of #30898 #27786

### Actual result BEFORE applying this Pull Request
Nothing happen

### Expected result AFTER applying this Pull Request
Display a message about what is going on.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Fedik** [comment]
Please someone, tell me a better message, I will update.

**Comment by richard67** [comment]
Couldn't language strings be used for the messages so they can be translated?

**Comment by wilsonge** [comment]
`Server response is corrupted` probably should be a language string agreed. I don't mind if the element is missing javascript error is in english only as that's more a developer error.

**Comment by Fedik** [comment]
okau, I made it translatable, 
also I have added "form reset" if user enter wrong name/password

**Review by wilsonge — APPROVED** [review]

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 3d3133045aa4a3cb48670f31e597c78d7a69c842<br /><br />The message appears with the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30992">issues.joomla.org/tracker/joomla-cms/30992</a>.</sub>

**Comment by PhilETaylor** [comment]
> MOD_LOGIN_AJAX_RESPONSE_CORRUPTED="Server response is corrupted, please try to reload the page."

I doubt highly that reloading the page is going to resolve the issue encountered and therefore this message is unhelpful. Suggest something like "Server response was not in the correct format, please try again and contact the site admin if this problem persists"

**Pull request closed without merging**
