### PR TITLE
[4.3][Guided Tours] Hide 'Take a tour' on small devices

### PR DESCRIPTION
**Pull request by obuisard**
Addresses issue #40011.

The guided tours are accessible throughout the administration.
However, on small devices, the tours cannot always run properly because some of the content is hidden from view and from the tours (targets are not found so the steps end up in the upper left corner of the window).

I am not sure this is the best approach, so please comment.

### Summary of Changes

Add CSS to hide the tour dropdown on small viewports.

### Testing Instructions

Make sure you see the 'Take a tour' button on the top toolbar of the administrator console.
Resize the window down. Around 576px, the dropdown should disappear.

### Actual result BEFORE applying this Pull Request

You can take a tour on any screen size.

### Expected result AFTER applying this Pull Request

'Take a tour' is not visible if the viewport is small or you are on a mobile device (tablets should be fine, but usually not smartphones).

This does not prevent the user to start a tour, resize the window down and continue the tour with possible 'failure' (no error or anything, just unexpected behavior in case an element is not 'visible').

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
> I am not sure this is the best approach, so please comment.

I don't know either, but maybe you can do something with the following approach in case of mobile devices. These are often small. You don't need ccs.

Code in plugin, something like this:

```
use Joomla\CMS\Factory;

public function startTour(Event $event)
{
    if (Factory::getApplication()->client->mobile == true)
    {
	return;
    }
```
See for the devices: 
https://github.com/joomla/joomla-cms/blob/1c0eda32d98defea89b5b19018bd8f0ed70bf7a8/libraries/src/Environment/Browser.php#L545-L555

**Comment by laoneo** [comment]
This one here is CSS only :smirk:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7a8946c9ba11b0c804b4a292c1e7c5b9daefde85<br /><br />does what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40045">issues.joomla.org/tracker/joomla-cms/40045</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 7a8946c9ba11b0c804b4a292c1e7c5b9daefde85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40045">issues.joomla.org/tracker/joomla-cms/40045</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40045">issues.joomla.org/tracker/joomla-cms/40045</a>.</sub>

**Comment by Quy** [comment]
Would adding ` d-none d-sm-block` be an option?

`<div class="header-item-content dropdown header-tours">`

**Comment by brianteeman** [comment]
@quy isn't that the functionaly the same as the  code here?

**Comment by Quy** [comment]
Yes a different solution without the additional css.

**Comment by obuisard** [comment]
> Yes a different solution without the additional css.

It is actually much cleaner, I did not think about it.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c4124df8574127776234979568e52e5d1eb853fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40045">issues.joomla.org/tracker/joomla-cms/40045</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c4124df8574127776234979568e52e5d1eb853fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40045">issues.joomla.org/tracker/joomla-cms/40045</a>.</sub>

**Pull request merged**
