### PR TITLE
[5.1] Load plugin group when executing batch tasks

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
@grantg182 found an issue in J3 that batch operations aren't loading the content plugin group. He provided a quick fix in #38378, but since we don't do bugfixes in J3 anymore, this is unfortunately not acceptable anymore. However, this is still valid in J4 and thus this PR introduces loading these plugins in batch properly.

### Testing Instructions
Add a `die();` in the beginning of a content plugin. Batch move a few articles. See that it goes through. Apply patch. Move the articles again. See that you get a white screen because the content plugins are loaded.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wilsonge** [comment]
Is there a reason to drop this in each function rather than in the common initBatch function?

**Comment by Hackwar** [comment]
We had a discussion that with overriding and... I'll change it. 😉

**Comment by grantg182** [comment]
So now the content plugins will be triggered regardless if the method returns false, is that desirable behaviour?

**Comment by Hackwar** [comment]
This PR does not execute any plugins. It just loads the plugin group. The actual events are only executed in the single steps.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d0f01a6dc7e04d7d6a64629b20ba400e7b291153<br /><br />Tested following the instructions, works as described. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39013">issues.joomla.org/tracker/joomla-cms/39013</a>.</sub>

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on 23247a9294e02d988ba66bc73b5348666c7b39f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39013">issues.joomla.org/tracker/joomla-cms/39013</a>.</sub>

**Comment by bembelimen** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39013">issues.joomla.org/tracker/joomla-cms/39013</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you Hannes!

**Pull request merged**
