### PR TITLE
[4.0] Remove weblinks package

### PR DESCRIPTION
**Pull request by Bakual**
We removed weblinks from core with J3.4 (https://github.com/joomla/joomla-cms/pull/4214)
We added some special handling so updating people have the package properly installed after the update.

### Summary of Changes
This removes the package file from the 4.0 package and also removes the special check in the updater script which would remove the package if weblinks is installed.

This will not work if we allow upgrades from pre J3.4 versions to J4. Now I'm not sure what the current plan is for the upgrades. Do we allow upgrades fom J3.x or only from J3.8+? @wilsonge was that already discussed/decided somewhere?
There are also other places where we could drop code and files (eg the SQL update ones) when we require a Joomla minimum version for the upgrade to 4.0.

### Testing Instructions
Hard to test I guess, mostly review.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by mbabker** [comment]
> Do we allow upgrades fom J3.x or only from J3.8+?

The [development strategy](https://developer.joomla.org/development-strategy.html#upgrade_policy) clearly spells out the upgrade paths we will support.  TL;DR, for major releases, you must first upgrade to the latest release on the previous major series (with 3.x and 4.0, that will mean you should be on 3.9 before updating to 4.0).

This PR should also remove the handling in the build script for that manifest file.

**Comment by Bakual** [comment]
Great to know the strategy we did back then is still valid :+1: 

> This PR should also remove the handling in the build script for that manifest file.

Good catch, should be fine now.

**Comment by mbabker** [comment]
> Great to know the strategy we did back then is still valid 👍

Until anything is superseded, what's published is what is valid.  And AFAIK there haven't been any requests for reviewing/updating that document so it's still the primary guideline as written.

**Comment by wilsonge** [comment]
Do we need/want to remove language files too?

**Comment by Bakual** [comment]
Not with this PR. But yes, I would love to remove them from core. But we need to think about that a bit first. Issues to solve:
* Ideally the languages (at least en-GB) for weblinks would be in the component language folder, but then the existing files from the language packs will override the ones from the component. We can of course also let the weblinks package install the files into the global language folder. It's probably easier to do.
* We need to think about how the weblinks language files should be translated. That needs a workflow change for the translators if we want them to keep translating those files. That is likely the harder part 😄 
In Crowdin, we could sync files from different repos into the same project. But we all know not all translators use Crowdin (for whatever reason).

**Comment by wilsonge** [comment]
OK - can you please create an issue for that so we can discuss with JM and Mig (and any other interested parties please :))

**Comment by wilsonge** [comment]
Also just for reference on this PR although it's been mentioned elsewhere we are only planning on supporting upgrades from Joomla 3.9 and higher hence why this PR was accepted

**Comment by Bakual** [comment]
@wilsonge Done: https://github.com/joomla/joomla-cms/issues/16753

**Pull request merged**
