### PR TITLE
[4.0] Fix Codemirror

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/19532

### Summary of Changes

- Fix code mirror missing code from addons.js
- Also update cm to 5.34
- Update tinyMCE to 4.7.6

### Testing Instructions
Apply patch and check if code mirror nd tinyMCE are ok

### Expected result

No console errors:
screen shot 2018-02-02 at 09 00 54

### Documentation Changes Required

A note to all the maintainers or contributors that want to update npm dependencies in J4:

- You need to update the version number in package.json
- You need to run `node build --update`
- You need to run `node build --compilejs` (to uglify the scripts)
- You need to run `node build --compilecss` (to minify the css files)

Then you're ready to commit these changes!

### CODE REVIEW

**Comment by ghost** [comment]
Tried to apply PR, got:

bildschirmfoto 2018-02-02 um 09 17 11

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig you need to install from the relative link on the tracker, as its already noted before patch tester will not always handle assets correctly

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 5ea24830ca3e94ab9db311a7c4dc0f1d34d849fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19534">issues.joomla.org/tracker/joomla-cms/19534</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 5ea24830ca3e94ab9db311a7c4dc0f1d34d849fd<br /><br />With this patch I can open and edit files in template manager on my ubuntu machine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19534">issues.joomla.org/tracker/joomla-cms/19534</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
