### PR TITLE
[4.0] Batch update redirects

### PR DESCRIPTION
**Pull request by brianteeman**
Adds some padding between the button and the form

### Before
before

###  After
after

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aee4010b02d957c2d2141739b244fc106d83a1cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33707">issues.joomla.org/tracker/joomla-cms/33707</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on aee4010b02d957c2d2141739b244fc106d83a1cf<br /><br />Fixes the problem

However this is one of those UI's that is totally alien to Joomla admin, it should be a toolbar button, that links to a modal view. That would be more in keeping with Joomla Admin UI. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33707">issues.joomla.org/tracker/joomla-cms/33707</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33707">issues.joomla.org/tracker/joomla-cms/33707</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
