### PR TITLE
Invisible reCAPTCHA

### PR DESCRIPTION
**Pull request by 810**
Issue https://github.com/joomla/joomla-cms/issues/14565

## Instructions
New option on the plugin, set to invisible, then it should work

## Docs
https://developers.google.com/recaptcha/docs/invisible

### CODE REVIEW

**Review by zero-24 — COMMENTED** [review]
Are you sure about that we are using the same value compact for two settings?

**Comment by 810** [comment]
ah forgot to change that one sec

**Comment by AlexRed** [comment]
I have tested this item :red_circle: unsuccessfully on b431c13c728cf6eaa48bc5649578f48a68cea92d<br /><br />Warning
Empty solution not allowed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14583">issues.joomla.org/tracker/joomla-cms/14583</a>.</sub>

**Comment by woluweb** [comment]
I have tested this item :red_circle: unsuccessfully on b431c13c728cf6eaa48bc5649578f48a68cea92d<br /><br />Hi Jelle,
Txs for proposing Invisible Captcha :-)

Could you please be more specific and give more detailed instructions for testing ?

I have tested the patch. Here is the detail
1. the reCaptcha v2 was working fine on the website
2. apply patch
3. check front-end : the reCaptcha v2 does not work any more ("Uncaught Error: Invalid ReCAPTCHA client id: undefined")
4. edit reCaptcha plugin settings and change Normal to Invisible
5. still same error in front-end ("Uncaught Error: Invalid ReCAPTCHA client id: undefined"). By the way, the *label* "Captcha" is still there on the page. I don't know whether it is supposed to appear or not.

Txs,

Marc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14583">issues.joomla.org/tracker/joomla-cms/14583</a>.</sub>

**Comment by woluweb** [comment]
by the way, should new Public/Secret Keys be generated or are the existing and working reCaptcha v2 keys still valid for Invisible Captcha ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14583">issues.joomla.org/tracker/joomla-cms/14583</a>.</sub>

**Comment by BarrissOffee** [comment]
I have tested this item :red_circle: unsuccessfully on b431c13c728cf6eaa48bc5649578f48a68cea92d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14583">issues.joomla.org/tracker/joomla-cms/14583</a>.</sub>

**Comment by gagnonjeanfrancois** [comment]
Hi, 

I looked on stackoverflow to see if peoples have similar issues. Maybe this thread will help :

http://stackoverflow.com/questions/41079335/implement-the-new-invisible-recaptcha-from-google

I think we need to subscribe to invisible recaptcha page and to make sure that your invisible recaptcha is whitelisted. 
https://www.google.com/recaptcha/intro/comingsoon/invisible.html

In 24 hours you should receive this E-mail : 
"Invisible reCAPTCHA Integration

If you haven’t integrated your site with reCAPTCHA v2, please follow our developer guide for implementation details.
Please make sure that your site key that has been whitelisted for Invisible reCAPTCHA.
To enable the Invisible reCAPTCHA, rather than put the parameters in a div, you can add them directly to an html button.

3a. data-callback=””. This works just like the checkbox captcha, but is required for invisible.

3b. data-badge: This allows you to reposition the reCAPTCHA badge (i.e. logo and ‘protected by reCAPTCHA’ text) . Valid options as ‘bottomright’ (the default), ‘bottomleft’ or ‘inline’ which will put the badge directly above the button. If you make the badge inline, you can control the CSS of the badge directly.
Verifying the user’s response has no changes."

**Comment by mseymour** [comment]
When will this be merged?

**Comment by franz-wohlkoenig** [comment]
@mseymour needs 2 successfully Tests.

**Comment by 810** [comment]
we need to redo everything, first we need to check what we really need, because you will see no visual box.

**Comment by kernusr** [comment]
Is not work correctly
Because:
1. You call `grecaptcha.execute();` before initial recaptcha. (line 11 on media/plg_captcha_recaptcha/js/recaptcha.js). And you apply this method for all recaptchas on page together
2. You use `grecaptcha.execute();` for recaptcha 2.0 too
3. You dont use required option "data-callback"
thanks!

Keys from recaptcha 2.0 not working on recaptcha invisible but keys from recaptcha invisible is working on recaptcha 2.0

**Comment by Quy** [comment]
@franz-wohlkoenig  Close due to similar pr #16599 ?

**Pull request closed without merging**
