### PR TITLE
[5.2] Remove legacy code for filtering state in backend models

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
Quite some time ago, we introduced code to read the filter state from the filter XML for list views in the backend, making all those setState() code unnecessary. This removes all that unnecessary code.

### Testing Instructions
Test if the filters in the list views still work for all the components.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 41d68aa78dc197783b0f9cb248506e4d5c1af170<br /><br />As far as I can tell removing this code has no noticable impact. Tested by checking various filters and by adding the filter to a url.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43230">issues.joomla.org/tracker/joomla-cms/43230</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 41d68aa78dc197783b0f9cb248506e4d5c1af170<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43230">issues.joomla.org/tracker/joomla-cms/43230</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Comment by Quy** [comment]
@Hackwar Go to System > Language Overrides

```
An error has occurred.

    0 Undefined constant "JPATH_" 
```

https://github.com/joomla/joomla-cms/blob/7af40efc87a622021ff3fa6a4d7c426047a910ea/administrator/components/com_languages/src/Model/OverridesModel.php#L71

**Comment by brianteeman** [comment]
This needs to be reverted. As well as the language overrides not working any more the update sites check and list of update sites also does NOT work

**Comment by brianteeman** [comment]
To be clear if you clear all site cookies and session data and then log back in then at least these views are empty.
image

**Comment by brianteeman** [comment]
I have created a PR to revert this for now #43918

**Pull request merged**
