### PR TITLE
Calendar change event

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #32694 and #17515 for joomla 3

### Summary of Changes

make calendar.js trigger "change" event when user select new date

### Testing Instructions

Add to Isis index.php:
```html
<script type="module">
if (window.jform_publish_up){
  window.jform_publish_up.addEventListener('change', () => {
    console.log('change');
  })
}
</script>
```

Go to Article editing, and try to change the publish_up date.
In browser console you should get "change" message on each change

### Actual result BEFORE applying this Pull Request
No message

### Expected result AFTER applying this Pull Request
Message

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Fedik** [comment]
for Joomla4 look there #32755

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 0a2ae82600d22c81218b66a31be9472cf4a2e0ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32756">issues.joomla.org/tracker/joomla-cms/32756</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0a2ae82600d22c81218b66a31be9472cf4a2e0ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32756">issues.joomla.org/tracker/joomla-cms/32756</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32756">issues.joomla.org/tracker/joomla-cms/32756</a>.</sub>

**Comment by GeraintEdwards** [comment]
This breaks existing functionality.  If an onchange attribute is set on a target field then it will now be triggered twice!

**Comment by Fedik** [comment]
@GeraintEdwards please create an issue with code example, to reproduce the problem

**Comment by GeraintEdwards** [comment]
If you edit the file administrator/components/com_content/forms/article.xml and find the publish_up field at line 129 and add the attrtribute 

`onchange="alert(0);"`

to this field and then edit and article and change the publish_up field (using the date picker) you will get the alert(0) being called twice where it should be called once.

the code now reads 

`if (self.inputField.onchange) {
	self.inputField.onchange();
}
self.inputField.dispatchEvent(new Event('change', {bubbles: true, cancelable: true}));`

where it should actually read
`self.inputField.dispatchEvent(new Event('change', {bubbles: true, cancelable: true}));``

the onchange handler will still get called by the dispatchEvent.

while were are at it the same error arises as line 238

**Comment by GeraintEdwards** [comment]
Issue #33538 created as well as PR #33540

**Comment by Fedik** [comment]
@GeraintEdwards thanks!
You do not need to create an issue if you have a PR ;)

**Comment by rajeshstarlite** [comment]
Hello @GeraintEdwards 

I've recently upgraded to Joomla! 3.10.2 from 3.9.24 and not sure if I'm only the one who faces an issue only in Internet explorer 11. We have this error 

Screenshot 2021-10-13 at 7 04 18 PM


we use 'onchange' event in calendar. debugger points to the new changes made in this PR. When we used 3.9.24 version we didn't have the issue. 

May be you can help me out?

**Comment by HLeithner** [comment]
@Fedik seems ie11 doesn't support this way to trigger an event https://stackoverflow.com/questions/27176983/dispatchevent-in-chrome-but-not-in-ie11

Can you have a look Plesse?

**Comment by Fedik** [comment]
please test #35819

**Comment by rajeshstarlite** [comment]
Thanks @Fedik, it works now.

**Pull request merged**
