### PR TITLE
Fix javascript lint

### PR DESCRIPTION
**Pull request by wilsonge**
Fixes errors in js lint

### CODE REVIEW

**Comment by wilsonge** [comment]
@SniperSister @zero-24 rips please

**Comment by dgrammatiko** [comment]
The html in the literals is way off: no closing div and the buttons don't have a type...
Fail

**Comment by zero-24** [comment]
> @SniperSister @zero-24 rips please

@wilsonge please point me to the issue? Rips looks green for me?

**Comment by wilsonge** [comment]
No worries. It failed before I rebased on j4 with 11 errors (http://ci.joomla.org/joomla/joomla-cms/13185) but if it works now i guess all good

**Comment by wilsonge** [comment]
> The html in the literals is way off: no closing div and the buttons don't have a type...

I know but you've got that fixed in your PR. this allows us to merge things and get the tests running whilst your more comprehensive js changes get tested

**Pull request merged**
