### PR TITLE
[mod_tags_similar] Use ID field defined in #__content_types table

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Use the field mapped to `core_content_item_id` instead of hardcoded `id` field.

### Testing Instructions

To test this properly one would have to find a component that uses tags and has `core_content_item_id` other than `id`. On such component the module does not work without patch.

Other than that, test that the module continues working properly on core components.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghazal** [comment]
Namespace wise, should not you use:
`$app    = Factory::getApplication();`
instead of
`$app    = JFactory::getApplication();`

or:
`$now        = Factory::getDate()->toSql();`
instead of 
`$now        = JFactory::getDate()->toSql();`

Not sure if this one has been corrected yet:
`$tagsHelper = new JHelperTags;`

**Comment by ghazal** [comment]
After checking this list:

[Use namespaced classes](https://issues.joomla.org/tracker/joomla-cms/24108)

looks like `JHelperTags;` has not been modified yet.

**Comment by SharkyKZ** [comment]
@ghazal This is for 3.x. I did not add the code you mention. It was already there and has already been converted in 4.0.

**Comment by ghazal** [comment]
ok. My bad and sorry.

**Comment by ghost** [comment]
what still we need to do here ?

**Comment by SharkyKZ** [comment]
Test it.

**Comment by zero-24** [comment]
Dear @SharkyKZ 

in preperation of the upcomming release of Joomla 3.10 we have used GitHubs rename feature to rename the staging branch into 3.10-dev. Usually GitHub moves all existing PRs towards the new branch just fine, but here it didnt work. The reason seems to be that the fork of the CMS that was used as base for this PR has been deleted so GitHub does no longer have a base to rebase the PR against the new branch and we are also not able to reopen the PR. For that reason GitHub closed this PR in my name, when this issue is still valid It would require a new PR against the new 3.10-dev or 4.0-dev branch.

**Pull request closed without merging**
