### PR TITLE
[4.0] copy paste error in comments

### PR DESCRIPTION
**Pull request by brianteeman**
Comments are used to build the docs so they must be correct

code review only

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 0b120b389949bb8a26030565d92f79d8e108d465<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26154">issues.joomla.org/tracker/joomla-cms/26154</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b120b389949bb8a26030565d92f79d8e108d465<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26154">issues.joomla.org/tracker/joomla-cms/26154</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26154">issues.joomla.org/tracker/joomla-cms/26154</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks as always

**Pull request merged**
