### PR TITLE
[4.0][workflow] remove workflow from user menu

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #21593 .

### Summary of Changes
removed workflow menuitem from user menu
and fields menu item pointing to content

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e05e4f1e93c4236c216a26b6cf02794537c6667d<br /><br />"Workflow" is removed from User-Menue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21626">issues.joomla.org/tracker/joomla-cms/21626</a>.</sub>

**Comment by ghost** [comment]
@alikon do you plan to remove "content fields" in another PR?

**Comment by alikon** [comment]
no no ....just not looking at this with the needed attention..... let me check  better let me recheck :smile:

**Comment by infograf768** [comment]
I think that Workflows is voluntarily added there.
The issue imho is that we have 2 Fields menu item, one for users (normal), the other for content which should not be there imho..

**Comment by alikon** [comment]
removed the content field menu item on user menu now

**Comment by alikon** [comment]
>  think that Workflows is voluntarily added there

@infograf768  why ?

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3e9e5285c488f132facde7fc1909ed50c9c68843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21626">issues.joomla.org/tracker/joomla-cms/21626</a>.</sub>

**Comment by infograf768** [comment]
> Why?

It is a good question indeed. 
I can't believe it's a mistake as It is the ONLY direct menu item to Workflows.

**Comment by ghost** [comment]
@alikon can you please change Title to show that "workflow" and double "Fields" are removed?

**Comment by infograf768** [comment]
Before deciding to take off the Workflows menu item, this should be seen by maintainers an Workflow people.

**Comment by alikon** [comment]
uhmm ... there is a Workflow item in the CONTENT menu
screenshot from 2018-08-15 11-21-09

**Comment by infograf768** [comment]
> there is a Workflow item in the CONTENT menu

I stand corrected.

**Comment by alikon** [comment]
@infograf768  on workflow things we are moving on quicksand  :smile:

**Comment by infograf768** [comment]
>  on workflow things we are moving on quicksand

Just trying to get at least one leg out of it... 🙈

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3e9e5285c488f132facde7fc1909ed50c9c68843<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21626">issues.joomla.org/tracker/joomla-cms/21626</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21626">issues.joomla.org/tracker/joomla-cms/21626</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
