### PR TITLE
Wrong component checked in the router

### PR DESCRIPTION
**Pull request by brianteeman**
New router for com_newsfeeds and com_contact need new router enabled also in com_content (see #14833)

Simple copy paste error

Shouldnt there be tests for this as well?

### CODE REVIEW

**Comment by wilsonge** [comment]
There's tests for the libraries not the component implementation

**Comment by wilsonge** [comment]
Also newsfeed and contacts can be removed as they are duplicate of first line in function

**Comment by mbabker** [comment]
Sooner or later we need to figure out the roadblock that causes us to not write unit tests for code outside the libraries and start writing the tests.  Once upon a time system tests were relied for that stuff but there hasn't been a system test suite hooked into core for years.  @yvesh here's an indirect task for your team 😉

**Comment by brianteeman** [comment]
duplicates removed from three places

**Comment by wilsonge** [comment]
Merged on review. Now let's see if anything falls out because we never tested the URLs correctly :)

**Pull request merged**
