### PR TITLE
[4.0] Meaningful error message in user plugin

### PR DESCRIPTION
**Pull request by brianteeman**
I have no idea how to create this error or even why we have this option but if we do then the error message should be meaningful.

Discovered while working through issues raised by @mbabker in #20689

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 617a96764f40c96120c11ed59b0220d7bc0df104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24165">issues.joomla.org/tracker/joomla-cms/24165</a>.</sub>

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on 617a96764f40c96120c11ed59b0220d7bc0df104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24165">issues.joomla.org/tracker/joomla-cms/24165</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
