### PR TITLE
[4.1] Finder: Fixing Content Map field

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This is about the "Content Map" filter field in the "Index" view of Smart Search. While changing the taxonomy table to a nested set schema, I forgot to convert this form field. This means that right now it returns more or less garbage. It should display for example the whole category tree properly indented in the dropdown.

### Testing Instructions
1. Install Joomla with some data, for example the testing sampledata.
2. Go to "Smart Search -> Index"
3. Open the filter dropdown and the "Content Map" filter. The entries are rather jumbled.
4. Apply this PR.
5. Reload the page and check the filter again. Now everything is aligned properly and indented properly.

### CODE REVIEW

**Comment by Fedik** [comment]
I got on test installation:
>Warning: Undefined array key 34 in administrator/components/com_finder/src/Field/ContentmapField.php on line 110

Something went wrong here https://github.com/joomla/joomla-cms/blob/bae8a8abc5ad5e7d538a60f32f9dd20c6e939f34/administrator/components/com_finder/src/Field/ContentmapField.php#L110

**Comment by Hackwar** [comment]
Can you provide me with the database? I don't see how that is possible right now.

**Comment by Fedik** [comment]
> Can you provide me with the database? I don't see how that is possible right now.

Nothing fancy. It a default installation, with our testing sample data, since 4.0, updated to 4.1 :)

**Comment by Hackwar** [comment]
ok, I'll try to see what is happening there. Did it stay the same even after clearing index and reindexing?

**Comment by Fedik** [comment]
Yeah, works only when I Clear index and run Index again.
But I not sure that everyone will do it when will see this error.

**Comment by Fedik** [comment]
Maybe just add `empty()` check somewhere before foreach.

**Comment by Hackwar** [comment]
I guess that this would fix it as well: #36751

**Comment by superknutsel** [comment]
I have tested this item :red_circle: unsuccessfully on 28c27794651a5f0cd5e8280c16f4edbe9b029da2<br /><br />The content of the dropdown already was nice. After applying the patch I see no difference. Maybe this is a good thing ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36766">issues.joomla.org/tracker/joomla-cms/36766</a>.</sub>

**Comment by Hackwar** [comment]
@superknutsel Can you explain a bit further? How did you test? Did it REALLY have the right indentation for categories for example in that dropdown?

**Comment by superknutsel** [comment]
Hi @Hackwar  I hope I did it like intended. Just had a look at the "Smart Search > Index > Filter Options > Select Content Map dropdown" and it all looked fine. Even made a screenshot just to make sure before I applied the patch.
What might be a thing is that I used the Joomla Patch Tester in my site that was on 4.2.0 alpha1 dev.
I just used my most up to date test site and did not realise the version.
If it's not the version to test this agains then sorry, I will make a site with a different release for this to test again.

**Comment by Hackwar** [comment]
The main issue is, that the dropdown should contain among other things a list of all categories and they should be correctly indented according to their level. The current code simply does not do that, so I would be really astonished if it worked correctly for you.

**Comment by superknutsel** [comment]
I have tested this item :white_check_mark: successfully on 28c27794651a5f0cd5e8280c16f4edbe9b029da2<br /><br />@Hackwar After retesting with more categories added at different levels I see what you mean. I was mistakenly thinking the demo data would be enough for this test. And after doing this I can see what the issue is and that the patch is fixing it.
Thanks for your reply and explanation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36766">issues.joomla.org/tracker/joomla-cms/36766</a>.</sub>

**Comment by RickR2H** [comment]
Restore test result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36766">issues.joomla.org/tracker/joomla-cms/36766</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 1104b4e63005dd4de7860ff77b91f0fede01dd9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36766">issues.joomla.org/tracker/joomla-cms/36766</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36766">issues.joomla.org/tracker/joomla-cms/36766</a>.</sub>

**Comment by wilsonge** [comment]
@bembelimen you might wanna consider merging this for 4.14 as it's directly fixing a regression

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
