### PR TITLE
[4.0] s/than/then

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b64651cb8e1bbec5097d0b763b122e133a25b63f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36628">issues.joomla.org/tracker/joomla-cms/36628</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on b64651cb8e1bbec5097d0b763b122e133a25b63f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36628">issues.joomla.org/tracker/joomla-cms/36628</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36628">issues.joomla.org/tracker/joomla-cms/36628</a>.</sub>

**Comment by HLeithner** [comment]
@Quy can you upgrade the branch please, this should fix the tests

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
