### PR TITLE
[5.2] Smart Search: Fix URL with highlight query

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
When the route of an entry in Smart Search isn't a query string, the highlight feature actually can produce invalid URLs. This PR enforces these URLs to be correct.

### Testing Instructions
Look at #43397, apply that patch and get the testing plugin. Index an RTF file and search in the frontend for this entry in the search. Click on the URL.

### Actual result BEFORE applying this Pull Request
The URL looks something like `/tolstoy.rtf&highlight=bunchofbase64gibberish` and throws a 404 when clicked.

### Expected result AFTER applying this Pull Request
The URL looks something like `/tolstoy.rtf?highlight=bunchofbase64gibberish` and does not throw a 404 when clicked.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by webnet-assmann** [comment]
I have tested this item :white_check_mark: successfully on a5bd855753404f6a164c0475d70b2e263cdaf2b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43398">issues.joomla.org/tracker/joomla-cms/43398</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a5bd855753404f6a164c0475d70b2e263cdaf2b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43398">issues.joomla.org/tracker/joomla-cms/43398</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43398">issues.joomla.org/tracker/joomla-cms/43398</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Pull request merged**
