### PR TITLE
[4.3] codestyle indentation

### PR DESCRIPTION
**Pull request by brianteeman**
simple pr - code review only

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 491b9b54e3b7cea8905a9517a65fb317e0744299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40551">issues.joomla.org/tracker/joomla-cms/40551</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 491b9b54e3b7cea8905a9517a65fb317e0744299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40551">issues.joomla.org/tracker/joomla-cms/40551</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40551">issues.joomla.org/tracker/joomla-cms/40551</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
