### PR TITLE
[4.0][RFC][WIP] New Toolbar Interface (for PHP)

### PR DESCRIPTION
**Pull request by asika32764**
This is a new toolbar interface design on PHP part. Related to #18392 and #19635

- [x] Complete Dropdown buttons logic
- [ ] Add Toolbar class to service provider
- [x] Sync php code with #19635
- [x] Code style and docblock
- [ ] Test
- [ ] Write a guide about how to us new interfaces.

## Introduction

Currently we use `JToolbarHelper` to add buttons to component view. But there are some problems of this interface.

First, too many arguemnts on some methods, for instance:

```php
public static function preferences($component, $height = '550', $width = '875', $alt = 'JToolbar_Options', $path = '')
```

Second, hard to add a custom button, the `Toolbar::appendButton()` has no type hint, we must look every Button classes to learn how to use them.

```php
$bar->appendButton('Standard', 'name', 'JTOOLBAR_BUTTON', 'item.new', true, false);
```

Then, it is impossible to customize some standard buttons or add dropdown. All standard buttons are hard coded.

## The Changes

I try to create a fluent interface that provides a flexible Toolbar button definition process:

```php
$toolbar = Toolbar::getInstance('toolbar');

// Use core button class or custom class.
$toolbar->appendButton(new StandardButton('new'))
    ->text('JTOOLBAR_NEW')
    ->task('article.add')
    ->icon('icon-plus');
    
// Use pre-defined megic methods
$toolbar->popupButton('preview')
    ->text('COM_FOO_TOOLBAR_PREVIEW')
    ->url(Route::_('...'))
    ->icon('icon-eye')
    ->listCheck(true)
    ->iframeWidth(640)
    ->iframeHeight(480)
    ->setOption('foo', 'bar');
```

All arguments are options.

```php
$button->task('item.save');

// Same as

$button->setOption('task', 'item.save');
```

And IDE friendily

p-2018-02-14-004

## Layout

Buttons can override layout and HTML classes:

```php
$toolbar->linkButton('back')
	->text('COM_FOO_TOOLBAR_BACK')
	->url(Route::_('...'))
	->icon('fa fa-arrow-left') // If icon not set, will fallback to `icon-back` like original code
	->buttonClass('btn btn-primary btn-sm')
	->layout('com_foo.toolbar.link');
```

## Button Group

Use callback to easily customize your dropdown buttons.

```php
$toolbar->dropdownButton('group')
	->text('Group')
	->toggleSplit(false)
	->icon('fa fa-globe')
	->buttonClass('btn btn-success btn-sm')
	->configure(
		function (Toolbar $childBar)
		{
			$childBar->standardButton('ok', 'Button 1');
			$childBar->standardButton('star', 'Button 2');

			$childBar->divider('HEADER');
			$childBar->standardButton('remove', 'Button 3');
			$childBar->standardButton('folder', 'Button 4');

			$childBar->divider();
			$childBar->standardButton('trash', 'Button 5');
			$childBar->standardButton('question', 'Button 6');
		}
	);
```

p-2018-02-14-003

## Confirm Button

```php
$toolbar->confirmButton('clear')
	->text('Clear')
	->icon('fa fa-refresh')
	->buttonClass('btn btn-sm btn-danger')
	->message('Are you sure you want to clear all data?');
```

p-2018-02-14-002

## Pre-Defined Buttons

```php
$toolbar->addNew('articles.add')->listCheck(true);
$toolbar->publish('articles.publish')->listCheck(true);
$toolbar->unpublish('articles.unpublish')->listCheck(true);
$toolbar->archive('articles.archive')->listCheck(true);
$toolbar->checkin('articles.checkin')->listCheck(true);
```

## No B/C break

If a component was using `ToolbarHelper` or `$bar->appendButton()`, it should fully B/C.

------

This PR is WIP, I changed com_content component to use new Toolbar syntax, it works very well:

- https://github.com/joomla/joomla-cms/pull/19670/files#diff-768783efa9acc6038e68770acac92aec
- https://github.com/joomla/joomla-cms/pull/19670/files#diff-dd27b3b67199eb49f1a592f47d1f5cf9

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@asika32764 @Fedik can you please coordinate this task?
Just for reference @Fedik already proposed something for the client side: #19635

**Comment by asika32764** [comment]
I think the php side still need much discussion (Since it is a big change). If the concept of this PR accepted, I can try to integrate @Fedik 's code into my PR or merge #19635 first then I sync the code base.

What do you think @Fedik ?

**Comment by photodude** [comment]
@asika32764 Please take the time to correct the Codestyle items here. It will help with the overall consideration of your proposal.
http://ci.joomla.org/joomla/joomla-cms/3102/4

You can use the [PHPCS codestyle autofixers](https://github.com/joomla/coding-standards) to automatically fix a number of the items in your PR. Just remember to keep it to the files related to your PR.

**Comment by asika32764** [comment]
Still Work in process, will fix all CS and docblock later.

**Comment by brianteeman** [comment]
I applied this PR and all components have many notices - for example these are with com_banners so its not yet b/c
```
Notice: Undefined variable: hasChildren in C:\htdocs\cms4\layouts\joomla\toolbar\base.php on line 21
Notice: Undefined variable: htmlAttributes in C:\htdocs\cms4\layouts\joomla\toolbar\link.php on line 31

```

and the component you updated for the new toolbar com_content fails to load at all with

`0 Call to undefined method Joomla\CMS\Toolbar\Toolbar::addNew()
`

**Comment by asika32764** [comment]
It seems your Toolbar class not up to date but I don't know why, all codes are commit to this PR.

See 
https://github.com/joomla/joomla-cms/pull/19670/files#diff-8f8f92469552f260a1c93e2223dd753fR85
And
https://github.com/joomla/joomla-cms/pull/19670/files#diff-8adf1d52f0a9432d0c831fb7e9abe680R42

The `addNew()` method is in `CoreButtonsTrait` and `Joomla\CMS\Toolbar\Toolbar` uses it. If there are not other class loading caches, it should work since the method is really exists there.

**Comment by asika32764** [comment]
@brianteeman I updated the autoload files, could you try again?

**Comment by brianteeman** [comment]
It must have been an issue that Patchtester cant cope with as I still had the same problem but when using native git I was able to test almost successfully. Just one error when using com_content

`Warning: count(): Parameter must be an array or an object that implements Countable in C:\htdocs\cms4\administrator\components\com_content\Model\ArticlesModel.php on line 307
`

**Comment by Fedik** [comment]
> What do you think @Fedik ?

I think it is good idea 😄 

I can wait when you finish it, then I can rework javascript part in #19635. It mainly the layout changes.
And it even better to finish PHP part first.

#19635 has only 2 extra thing I changed in Toolbar:
- prevent ID duplication. [like here](https://github.com/Fedik/joomla-cms/blob/28db80db0a3d160545ef1a43c19a523452b6f785/libraries/src/Toolbar/Button/StandardButton.php#L129)
- allow to pass `validate` marker, and add `form` to pass a form selector, [there](https://github.com/Fedik/joomla-cms/blob/28db80db0a3d160545ef1a43c19a523452b6f785/libraries/src/Toolbar/Button/StandardButton.php#L46)

**Comment by asika32764** [comment]
@brianteeman Look like not belongs to this PR.

https://github.com/joomla/joomla-cms/blob/9b719ee70123cf84fc3b2d5266ef9362f5426e5c/administrator/components/com_content/Model/ArticlesModel.php#L305-L312

**Comment by samarthsharma36** [comment]
After applying the patch , I am getting this error when i tried creating "New Article"


workspace 1_029

**Comment by asika32764** [comment]
did you use patchtester to test it? Maybe is the same reason of https://github.com/joomla/joomla-cms/pull/19670#issuecomment-365714487

**Comment by samarthsharma36** [comment]
@asika32764 , yes. I used patch tester to test it

**Comment by wilsonge** [comment]
@asika32764 can we get this upto date with 4.0 please. I really like this concept and would like to get it in :)

**Comment by asika32764** [comment]
OK. A little busy that I stop developing this PR. Well continue finish this maybe this weekend.

**Comment by wilsonge** [comment]
OK I've fixed the conflicts myself and made the decision to merge this for now so we can all work on it in the main repo :)

**Comment by wilsonge** [comment]
Thanks for the hard work that went into this!!

**Comment by asika32764** [comment]
Thank you, sorry for the delayed since there are some serious projects I must to complete in this month.

**Comment by asika32764** [comment]
I still must write some documentation. If you need the doc, please tag me.

**Comment by wilsonge** [comment]
Don't worry :) Thankyou so much for doing what you could!

**Comment by N6REJ** [comment]
were docs ever created for this?

**Comment by Quy** [comment]
No. See https://github.com/joomla/joomla-cms/pull/19670#issue-168889743

**Pull request merged**
