### PR TITLE
[4.3] Remove redundant assignment

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #35752.

### Summary of Changes
The first assignment is the original and a subset of the 2nd assignment.
Remove the first assignment.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8757e68baeef3d9cdcc7f0a3c05689e2cbdf8897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40161">issues.joomla.org/tracker/joomla-cms/40161</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8757e68baeef3d9cdcc7f0a3c05689e2cbdf8897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40161">issues.joomla.org/tracker/joomla-cms/40161</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40161">issues.joomla.org/tracker/joomla-cms/40161</a>.</sub>

**Comment by Quy** [comment]
@obuisard @laoneo Please merge as there was an oversight in the original PR.

**Comment by obuisard** [comment]
Thank you @Quy

**Pull request merged**
