### PR TITLE
[4.0] associations message

### PR DESCRIPTION
**Pull request by brianteeman**
Tweak the text to make it read a little better english

### CODE REVIEW

**Comment by infograf768** [comment]
Unneeded change.
The existing message is clear: one can't use the component if conditions are not met.
Using the component not only let's create associations but also edit them (under the conditions stated).

**Comment by brianteeman** [comment]
Unneeded perhaps for you. But bad english is a bug

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7b556f477442cce6ed7d2dc3167f94caa48ef8b3<br /><br />Tested successfully in Beta7-dev of 21 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32095">issues.joomla.org/tracker/joomla-cms/32095</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7b556f477442cce6ed7d2dc3167f94caa48ef8b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32095">issues.joomla.org/tracker/joomla-cms/32095</a>.</sub>

**Comment by infograf768** [comment]
> Unneeded perhaps for you. But bad english is a bug

The matter is not bad English, the matter is the nature of the message.

**Comment by brianteeman** [comment]
Not interested in arguing - remember you cant edit an association until you have created one so your comment is irrlevant

**Comment by infograf768** [comment]
> remember you cant edit an association until you have created one so your comment is irrlevant

Totally wrong, which proves your poor knowledge of the associations feature.
One may have created the association without using the component. And therefore can edit it later with the component.
I will not lose my time creating an animated gif to explain the process.

**Comment by rdeutz** [comment]
so it should be "You can't use the Multilingual Associations Component ...."

**Comment by infograf768** [comment]
> so it should be "You can't use the Multilingual Associations Component ...."

That would indeed have been a better English without changing the meaning of the alert.
Merged to stop losing time when we have more important stuff to look at.

**Pull request merged**
