### PR TITLE
[4.0] Fix autoprefixer

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/19219

### Summary of Changes

This changes the scope of the comment that disables the autoprefixer so that it doesn't affect the rest of the file

### Testing Instructions

1. In the front-end, go to Module Settings
2. Ensure the select dropdown doesn't have multiple arrows

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 348deca83d9d8b7b89649457f64b6b4743dccb60<br /><br />@C-Lodder can you please change Test Instructions to test Module Settings?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19243">issues.joomla.org/tracker/joomla-cms/19243</a>.</sub>

**Comment by C-Lodder** [comment]
Done

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 348deca83d9d8b7b89649457f64b6b4743dccb60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19243">issues.joomla.org/tracker/joomla-cms/19243</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
