### PR TITLE
[4.1] Add propper classes to search input

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #36254.

### Summary of Changes
Adds proper classes to the search bar layout description element. Additionally it simplifies the code and adds some more classes in BEM style to the other elements.

History:
- #36215
- #36225
- #36254

### Testing Instructions
Go to any search toolbar in the backend and inspect the search field.

### Actual result BEFORE applying this Pull Request
Renders properly.

### Expected result AFTER applying this Pull Request
Renders properly but has new CSS classes.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a3d6815a86a57020e67aec64ecf3e733b18ec34e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36259">issues.joomla.org/tracker/joomla-cms/36259</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on a3d6815a86a57020e67aec64ecf3e733b18ec34e<br /><br />It works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36259">issues.joomla.org/tracker/joomla-cms/36259</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36259">issues.joomla.org/tracker/joomla-cms/36259</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on a3d6815a86a57020e67aec64ecf3e733b18ec34e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36259">issues.joomla.org/tracker/joomla-cms/36259</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
