### PR TITLE
Media Manager: Displaying the path to the opened folder

### PR DESCRIPTION
**Pull request by infograf768**
When browsing through the folders, we do not know where we are...

After patch, we should get:

screen shot 2015-01-14 at 12 18 32

### CODE REVIEW

**Comment by brianteeman** [comment]
@test works perfectly BUT I think it would be even more useful if it displayed the full path either
`<?php echo COM_MEDIA_BASEURL . '/' . $this->state->folder; ?>`
or
`<?php echo COM_MEDIA_BASE . '/' . $this->state->folder; ?>

**Comment by MAT978** [comment]
@test
Able to reproduce then #5722 works as described
Tanks

**Comment by infograf768** [comment]
COM_MEDIA_BASE would for example give:
` /Applications/MAMP/htdocs/trunkgitnew/images/sampledata`
Not good imho

COM_MEDIA_BASEURL would give:
` http://localhost:8888/trunkgitnew/images/sampledata`

Do we really want that?

I can get also:

screen shot 2015-01-14 at 13 16 24

or, simply:

screen shot 2015-01-14 at 13 18 47

in this last case, the path showing the base folder could be added when no folder is open.
We would get:

screen shot 2015-01-14 at 13 25 37

What do you think?

**Comment by wilsonge** [comment]
I think I prefer the first one with ROOT: images/FOOBAR

**Comment by brianteeman** [comment]
Yes thats a better option - agree with @wilsonge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5722">issues.joomla.org/joomla-cms/5722</a>.</sub>

**Comment by rdeutz** [comment]
agree with @wilsonge

**Comment by sovainfo** [comment]
How does this relate to the Create New Folder. Does that still insert fields between the buttons and content? If so, I would prefer the path only once above the content with contents as suggested and agreed upon but with tooltips for ROOT including both URL and full filesystem path.

Maybe the Create New Folder button can be removed from the toolbar and always appear!

**Comment by brianteeman** [comment]
Why dont you look and see

On 14 January 2015 at 14:08, sovainfo <notifications@github.com> wrote:

> How does this relate to the Create New Folder. Does that still insert
> fields between the buttons and content? If so, I would prefer the path only
> once above the content with contents as suggested and agreed upon but with
> tooltips for ROOT including both URL and full filesystem path.
>
> Maybe the Create New Folder button can be removed from the toolbar and
> always appear!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5722#issuecomment-69920274>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sovainfo** [comment]
Still waiting for 3.4 Beta!

**Comment by zero-24** [comment]
@sovainfo 

>Still waiting for 3.4 Beta!

See: 
>January 20th 2015 - 3.4 Feature Freeze
January 27th 2015 - 3.4 Beta 1
February 3rd, 2015 - 3.4 Beta 2
February 10th, 2015- 3.4 Release Candidate
February 17th, 2015 - 3.4 Stable Release

http://developer.joomla.org/news/601-joomla-3-4-release-timeline-update.html

**Comment by brianteeman** [comment]
That is fine but in that case please dont waste everyones time with
comments asking them to do something that you are not prepared to do
yourself.


On 14 January 2015 at 14:22, zero-24 <notifications@github.com> wrote:

> @sovainfo <https://github.com/sovainfo>
>
> Still waiting for 3.4 Beta!
>
> See:
>
> January 20th 2015 - 3.4 Feature Freeze
> January 27th 2015 - 3.4 Beta 1
> February 3rd, 2015 - 3.4 Beta 2
> February 10th, 2015- 3.4 Release Candidate
> February 17th, 2015 - 3.4 Stable Release
>
>
> http://developer.joomla.org/news/601-joomla-3-4-release-timeline-update.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5722#issuecomment-69922234>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
sorry @brianteeman ok i will reduce time wasting comments. (i hope this will be the last one)

**Comment by sovainfo** [comment]
@zero-24 Thanks, had seen that long overdue information already!
@brianteeman Don't recall asking someone to do something I don't want to.

**Comment by brianteeman** [comment]
Maybe it was a mistranslation then for which I apologise but this statement
> How does this relate to the Create New Folder. Does that still insert fields between the buttons and content?

Appears to be asking others to check to see what happens when you could easily do that yourself

**Comment by sovainfo** [comment]
This PR doesn't change the behavior of that button, but other PR's may (both available in staging and pending). I currently use that button to get to see the desired context because that is missing, which is what this PR is about. 

The question you quoted was a polite way of saying the missing information is already available, only hidden! Merely pointing out bad UX design ( in my opinion ).

Fixing bugs at design time is always cheaper, which is why I responded to the question by the author of this PR. Assuming he is more aware of the ins and outs of Media Manager. Still consider it valid to place this PR in the right perspective.

**Comment by brianteeman** [comment]
Well it wasnt clear at all that this is what you were talking about. So now
it is great for you as you dont need to press the button except when you
want to create a folder

On 14 January 2015 at 15:19, sovainfo <notifications@github.com> wrote:

> This PR doesn't change the behavior of that button, but other PR's may
> (both available in staging and pending). I currently use that button to get
> to see the desired context because that is missing, which is what this PR
> is about.
>
> The question you quoted was a polite way of saying the missing information
> is already available, only hidden! Merely pointing out bad UX design ( in
> my opinion ).
>
> Fixing bugs at design time is always cheaper, which is why I responded to
> the question by the author of this PR. Assuming he is more aware of the ins
> and outs of Media Manager. Still consider it valid to place this PR in the
> right perspective.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5722#issuecomment-69931199>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sovainfo** [comment]
It was clear from your response that you didn't understand the issue I was raising. Doubt from your replies whether you do understand now. Hopefully there are developers that do. Regardless, I tried again to contribute, will think twice the next time!

**Comment by JoomliC** [comment]
This is a nice addition.
Just a question @infograf768 : why using ul li and so adding a style class ?

If I may make a suggestion : 
<pre>
	<?php if ($this->state->folder != '') : ?>
	<div class="muted">
		<p>
		<i class="icon-folder"></i>
		<?php echo JText::_('JGLOBAL_ROOT'); ?>:
		<?php echo JComponentHelper::getParams('com_media')->get('image_path', 'images'); ?>
		<?php echo '/' . $this->state->folder; ?>
		</p>
	</div>
	<?php endif; ?>
</pre>
Using the class muted (color #999 in isis) as no link active, but an information of the current path.

capture d ecran 2015-01-15 a 03 18 13

**Comment by infograf768** [comment]
@JoomliC 
If we use 'muted', we would anyway have to add the class for hathor as I had to do with 'unstyled' (that class, as 'muted', exists in Isis).
I like the idea though. I am modifying the PR now.

Also we must not forget:
<b>The 'Path to images' folder has to be the same or a subfolder of 'Path to files'.</b>
Therefore we should use "file_path" and not "image_path" I guess.

@sovainfo 
I understand what you mean. I think that creating a new folder is not as common as managing contents inside existing ones. As the line takes much less space than the uncollapsed inputs to create new folder, I am in favor of letting the Create New Folder alone.

**Comment by infograf768** [comment]
Please test again. Depending if a folder is opened or in Root, we will now get:

screen shot 2015-01-15 at 09 01 12


screen shot 2015-01-15 at 09 01 32

**Comment by sovainfo** [comment]
@infograf768 Agree to disagree, respect your decission.

**Comment by brianteeman** [comment]
@test Works perfect - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5722">issues.joomla.org/joomla-cms/5722</a>.</sub>

**Comment by zero-24** [comment]
@test successful --> RTC Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5722">issues.joomla.org/joomla-cms/5722</a>.</sub>

**Comment by infograf768** [comment]
Thanks for testing. Merged.

**Comment by JoomliC** [comment]
@infograf768 Great! :+1: 

Sorry for my late comment, worked late yesterday (France TZ)... But, is not supposed Hathor today to be visually impaired person accessible ? (this was the reason i thought muted class was not needed in Hathor).
I'm maybe wrong?

Bien à toi,
Cyril

**Pull request closed without merging**
