### PR TITLE
Use the fw package in favor of JImage

### PR DESCRIPTION
**Pull request by laoneo**
This pr replaces `JImage` with the fw package. It keeps the classe `JImage` because of BC to load the `JImageFilter*` classes.

### CODE REVIEW

**Comment by mbabker** [comment]
We've already done this in 4.0.  Any reason it needs to come into 3.8?

Also, without backporting some other logging changes, we're losing some internal logging functionality in a non-B/C way here (the Framework uses a PSR-3 logger, the CMS classes use `JLog`, 4.0 has a bridge class for this).

**Comment by laoneo** [comment]
Missed the logging part, but there can be deprecated all filters and class mapped. There is no need to have them all still in place or do I miss something.
Beside that, it would make sense to have that in 3 already available. Makes the life of us extension developers easier if it would be available in the 3 series already.

**Comment by mbabker** [comment]
4.0 will have and keep all of the `JImage` classes, so really the only convenience factor to port it all back to 3.8 would be if you are one of the eager ones and want to use all the namespaced stuff and drop older 3.x support.

Even if we backport the logging bridge, to be honest, because of the logging API differences I don't know if we can actually consider this one for 3.x because there is an internal B/C break in how errors are logged.  If `JImage` were PSR-3 aware then we'd be fine, but sadly it's not.  The rest of the API should be fine if I'm not mistaken, but that one implementation detail really makes this hard to accept.

**Comment by laoneo** [comment]
Would making JImage PSR-3 aware a BC break?

**Comment by mbabker** [comment]
Making JImage PSR-3 aware helps, but you also need the delegating logger.

If you are adamant about seeing this through, in essence you will need to do the same thing as done in https://github.com/joomla/joomla-cms/pull/12144 for the image package stuff (we can look at class mapping after that PR is applied against 3.8, but for now I would not map anything and part of my justification can be seen in the class constructors) and the parts of https://github.com/joomla/joomla-cms/commit/9491b574c66b19cbb0ea2ec935e66bb6f0ee7216 implementing the PSR-3 support bridge (the `$context` array in the log entry, the delegated logger class, and the ability to create it within `JLog`).

**Comment by laoneo** [comment]
Ok, will prepare a pr with the logger backport then.

**Comment by laoneo** [comment]
I'v added the logger code similar to the 4.0 branch. Additionally I have namespaced the deprecated classes for the sake of consistency.

**Comment by laoneo** [comment]
If @mbabker or @wilsonge can create a tag on the image package, then I can update the composer file to point to the tag and not dev-master.

**Comment by mbabker** [comment]
1.4.0 tagged

**Comment by laoneo** [comment]
Thanks. Changed composer to use the version 1.4.

**Comment by laoneo** [comment]
Any plan with this one?

**Comment by mbabker** [comment]
Technically we shouldn't be merging this during beta.  But if this is the last namespacing/FW PR we have for 3.8 then once this is sync'd to staging let's do it.

**Comment by laoneo** [comment]
Ok, done

**Comment by wilsonge** [comment]
When merging into 4 - this conflicted like hell with https://github.com/joomla/joomla-cms/pull/12144 (michael's first attempt at moving JImage to the framework packages). I've kept what he's done for now but just namespaced it. But if you want to do a follow up to standardise feel free.

**Comment by laoneo** [comment]
Will do when staging is merged into 4.

**Pull request merged**
