### PR TITLE
fixed issue #12761. function total throws SQL exception in SQL Server

### PR DESCRIPTION
**Pull request by freegink**
Pull Request for Issue #12761  .

### Summary of Changes
removed parameter values for "limit" and "offset" passed in "setQuery" in function "total"

### Testing Instructions
1. Go to "Menu->Mange"
2. Select a menu
3. Click "Edit" button

The editing interface should appear without SQL exception.
### Documentation Changes Required
N/A

### CODE REVIEW

**Comment by phproberto** [comment]
I'm ok with the fix because it's not really something that will make a performance improvement if you don't have millions of rows and if you have millions of user groups you have a bigger problem.

That said **you are not fixing an issue**. You are bypassing it. This query is correct in MySQL:

```sql
SELECT count(id)
FROM jml_usergroups
LIMIT 0,1
```

If the SQL Server driver is not working properly fix it or this will happen again.

**Comment by freegink** [comment]
You are right. The driver should be fixed.

**Comment by Tutunka** [comment]
Searched all over google for this. I installed an older version back in December 2016 and gave up due to this bug and just today updated  Joomla to the latest version so this fix definitely isn't part of the new files. Can it be added to the project release files? I'm moving from and DNN and Prestashop due to bugs that simply don't get fixed so this isn't really a great start with Joomla.

**Comment by alikon** [comment]
is alerady in https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/usergroups.php#L190

**Pull request closed without merging**
