### PR TITLE
[4.0] Default Menu icon

### PR DESCRIPTION
**Pull request by brianteeman**
Add aria hidden class to the icon and sr-only text to indicate that it is the default menu

pr for #26656

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e31c14a3d551cd1034e4f855aa4d07ba6c1108d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26730">issues.joomla.org/tracker/joomla-cms/26730</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on e31c14a3d551cd1034e4f855aa4d07ba6c1108d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26730">issues.joomla.org/tracker/joomla-cms/26730</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26730">issues.joomla.org/tracker/joomla-cms/26730</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
