### PR TITLE
Update uk-UA.ini

### PR DESCRIPTION
**Pull request by denysdesign**
Prepare Joomla 3.9.19 release candidate

### CODE REVIEW

**Comment by richard67** [comment]
This PR is wrong since it has translated the word "installation" in language strings where a previous comment clearly instructed not to translate that word, and further more, this PR removes these comments, too.

Ping @infograf768 .

**Comment by denysdesign** [comment]
I'm sorry, my bug. I'll fix it tomorrow!
Thank you 👍

**Comment by infograf768** [comment]
Please Denys, also update the xml (`<version>` and date).
Next time please use the TT forum as usual. ;)

**Comment by denysdesign** [comment]
Hi, 
please check correctly!
Thank!
https://forum.joomla.org/viewtopic.php?f=54&t=978963&p=3602725#p3602725

**Comment by infograf768** [comment]
closing. thanks!

**Pull request closed without merging**
