### PR TITLE
Improvements in Recaptcha - solves #8188

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Improvements in recaptcha 2.0 so that it uses HTML5 data-\* atributes instead of jquery to load.

This makes it work even if the google javascript file execution is delayed to the javascript onload event.

Also the code has no inline js.
## Test instructions

Ativate recaptcha 2.0 in the plugin settings and global settings.
Test "Forget your password" page or a "Contact form".
It should work ok.

BC: No problems that i know of. But i don't have a complete understanding of Joomla history, so i leave that to the people that have it.

Note: For testing the javascript execution after the onload event use an extension that allows doing that.

### CODE REVIEW

**Comment by roland-d** [comment]
@andrepereiradasilva 
> Note: For testing the javascript execution after the onload event use an extension that allows doing that.

Do you have an example of such extension?

**Comment by andrepereiradasilva** [comment]
@roland-d I think jbetolo allows it.

**Comment by roland-d** [comment]
@andrepereiradasilva I see thet jbetolo is a compressor sort of speak. Perhaps I misunderstand your comment.

> Note: For testing the javascript execution after the onload event use an extension that allows doing that.

Could you perhaps explain this in more detail in how it is related to the test?

**Comment by andrepereiradasilva** [comment]
jbetolo is performance tool. Allows you to compress js/css files and also, in the case of javascript, it allows you to "Defer" the javascript processing to the page onload event.

Instead of being executed when the browser is reading the page and waiting for the script to be downloaded and processed to continue rendering the page, if you defer the script execution to the page onload event, the page is rendered much faster by the browser.

The current recaptcha plugin doesn't work if you defer the javascript execution to after the page onload event. See https://github.com/joomla/joomla-cms/issues/8188. So this PR solves that issue.

I didn't try with jbetolo because i use a custom plugin for defereing the javascript to the page onload event (and it works fine in that plugin). But i can try tomorrow using jbetolo or some other extension that can do that.

**Comment by Fedik** [comment]
finally someone made it :smile: 
looks good, later I try check/test the code

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 17bfad64ea87de039d9bc20a1711e9be26d0044b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8191">issues.joomla.org/joomla-cms/8191</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Tested with two system plugins and now it loads the captcha. If you use the old code if doesn't load.

### ScriptMerge
Plugin Options changes:

##### Merge Options Tab
Merge JS: Yes
Enable in frontend: Yes
Rest of options: No

##### Loading Options Tab
Defer Merged File: Any of the options
Merged JS position: Any of the options

### jbetolo

Plugin Options changes:

##### Javascript Tab
Defer: script(onload event)

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 0f560540478cfcc8d08bbe6931c2602f3808fef1<br /><br />Tested with jbetolo, before reCaptcha is not visible after applying the patch no problems :+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8191">issues.joomla.org/joomla-cms/8191</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8191">issues.joomla.org/joomla-cms/8191</a>.</sub>

**Pull request merged**
