### PR TITLE
Fixes HTML errors in com_installer #7230

### PR DESCRIPTION
**Pull request by OctavianC**
This is just a small fix for the missing closing tags mentioned in #7230. You won't be able to see any visual changes since browsers were already suppressing the errors.

Locations fixed:
- Extensions > Extension Manager > Install (missing closing `</div>` tag for `<div id="j-main-container">`)
- Extensions > Extension Manager > Database (missing closing `</div>` for `
  <div class="tab-content" id="myTabContent">` and `</li>` for `<li>No default text filters found.`)

### CODE REVIEW

**Comment by n9iels** [comment]
Looks good to me.
But maybe we can make the alignment in `administrator/components/com_installer/views/install/tmpl/default.php` a little bit better?

For example the `div` above the `form`. We can add tabs right there. Also on line 119 the tab alignment isn't fully correct.
Good idea?

**Comment by OctavianC** [comment]
Waiting on Travis (I'm sure I got some CS issues), but here's what I did:
- Changed Javascript alerts to use `Joomla.JText._()`
- Moved `<form>` inside `#j-main-container`
- Added some more spacing in the code to understand what's going on :)
- The close link on the JED Installer alert wasn't properly escaped
- The tooltip had a str_replace for `"` into `&quot;`, better use `$this->escape()` if you don't trust the language key
- Changed buttons to use `<button>` instead of `<input>`
- Wanted to change the `myTab` ID but it seems to be hard-coded in the `webinstaller` plugin so leaving that like it is for now
- Noticed that images from `media/jui` are not following the `images/` naming convention, instead they're in `img/`. I've moved `ajax-loader.gif` to `media/jui/images` so that it can be overwritten by the template. I don't see any other place where this is used so I though it's alright.
- Removed inline styling for `.j-jed-message`
- Added styling for `#loading` div and no longer rely on Javascript to create it

**Comment by n9iels** [comment]
Looks great! :smiley:
Only two travis errors.

@test works fine for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7235">issues.joomla.org/joomla-cms/7235</a>.</sub>

**Comment by RickR2H** [comment]
Good testing instructions are missing.

To test open the following files and check for the missing divs. A good IDE will point them out.

administrator\components\com_installer\views\database\tmpl\default.php
On line 103: Starting div without closing div

administrator\components\com_installer\views\install\tmpl\default.php
On line 20: Starting div without closing div
On line 40: Starting li without closing li

After applying the test the missing html tags are added.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7235">issues.joomla.org/joomla-cms/7235</a>.</sub>

**Comment by jwaisner** [comment]
@test 

PR works as intended and missing code is added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7235">issues.joomla.org/joomla-cms/7235</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7235">issues.joomla.org/joomla-cms/7235</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @OctavianC! Merged with https://github.com/joomla/joomla-cms/commit/87db28bf5d7f6f9543ebd92d2773d5d371f09a2e

**Comment by beat** [comment]
Nota bene: This PR introduced 2 regressions:

1. No Joomla-spindle during installations. Fix proposal is in PR #9144
2. No Joomla-spindle anymore in Install-from-web browsing. Fixed with Install-from-web 1.1.0, released today for Joomla 3.5 (and in 1-2 weeks for Joomla 3.4 too)

**Pull request closed without merging**
