### PR TITLE
[4.0] Fix toolbar button in com_users

### PR DESCRIPTION
**Pull request by hardik-codes**
This PR replaces ```status``` with ```status-group``` in the following code, thus making it consistent with other toolbar buttons

 File: ``` administrator/components/com_users/View/Notes/HtmlView.php```
```php
$dropdown = $toolbar->dropdownButton('status-group')
		->text('JTOOLBAR_CHANGE_STATUS')
		->toggleSplit(false)
		->icon('fa fa-globe')
```

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e05cfefb9b8d7e71849ca05b70a7965f28a68aed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24561">issues.joomla.org/tracker/joomla-cms/24561</a>.</sub>

**Comment by hardik-codes** [comment]
One more tester please

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e05cfefb9b8d7e71849ca05b70a7965f28a68aed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24561">issues.joomla.org/tracker/joomla-cms/24561</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24561">issues.joomla.org/tracker/joomla-cms/24561</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
