### PR TITLE
[4] clean up use of factory calls

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 01f92ca377c6a37da54eb0ff18a72bad6253c81a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34022">issues.joomla.org/tracker/joomla-cms/34022</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 01f92ca377c6a37da54eb0ff18a72bad6253c81a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34022">issues.joomla.org/tracker/joomla-cms/34022</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34022">issues.joomla.org/tracker/joomla-cms/34022</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
