### PR TITLE
popover zindex

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11268
#### Summary of Changes

Changes the zindex so that popoer will display above the fixed navbar etc
#### Before

e63f2ba2-50f1-11e6-9d2f-a12b61e1d479
#### After

aeoq

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c169068991cae2b70b6be3f0c4f0cc3dc6c45bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11276">issues.joomla.org/joomla-cms/11276</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on c169068991cae2b70b6be3f0c4f0cc3dc6c45bad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11276">issues.joomla.org/joomla-cms/11276</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11276">issues.joomla.org/joomla-cms/11276</a>.</sub>

**Comment by odbhaskaran** [comment]
I have pop up background as black with white text.  No change after changing template-rtl.css

**Comment by brianteeman** [comment]
You are not on current staging

**Comment by roland-d** [comment]
@brianteeman There is an issue with this PR. The file templates/protostar/css/template.css shouldn't be part of this PR. This file has already been changed by https://github.com/joomla/joomla-cms/pull/11209/files which has been merged. If you can remove this file, we can merge the PR. Thanks.

**Comment by brianteeman** [comment]
I just edited one file and ran the generatesss.php

I can try again on a new branch tomorrow to see if it is any different

**Comment by zero-24** [comment]
This should be removed from the milestone and closed as it is merged with another PR ;)

**Comment by brianteeman** [comment]
Closed as merged.with #11287

**Pull request closed without merging**
