### PR TITLE
[4.0] No TLS transfer encryption for database connections if localhost

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

Follow-up to PR #26375 .

### Summary of Changes

With PR #26375 the possibility to use encrypted database connections was added to the CMS, and with PR #26888 it would be added to the installation process, too, if that is accepted.

Again thanks to @andrepereiradasilva for the implementation of these new features.

Because database connections default to socket connections in case if the database server is 'localhost' (which is of course more performant that a TCP/IP connection like e.g. to '127.0.0.1' or '::1'), and encryption is not possible with socket connections, this PR here changes the showon condition for the related fields in the server section of the Global Configuration form so that they are hidden when database server is 'localhost', and it adds an onchange JS to clear the fields when changing database server from something else to 'localhost'.

The JS added by this PR has the advantage that it can be used in future for other onchange events, too, e.g. if we want to clear the FTP related fields when disabling the FTP layer.

### Testing Instructions

1. On an installation of current 4.0-dev or last nightly build, go to Global Configuration, tab "Server", section "Database".
2. If field "Host" has a value different to "localhost", change it to "localhost".
3. Select option "Two-way encryption" of field "Connection Encryption".
4. Enter some values for the text fields related to database connection encryption as shown below in section "Actual result" in the screen shot.
Result: See section "Actual result" below.
5. Click the "Close" button in order to leave the form without saving the changes.
6. Apply the patch of this PR e.g. with [Patch Tester 3.0.0 Beta 4](https://github.com/joomla-extensions/patchtester/releases/tag/3.0.0-beta4) or [Patch Tester 4.0.0 Beta 2](https://github.com/joomla-extensions/patchtester/releases/tag/4.0.0-beta2) (if the latter works for you).
7. If not having used [Patch Tester 4.0.0 Beta 2](https://github.com/joomla-extensions/patchtester/releases/tag/4.0.0-beta2) with the CI option enabled:
Run `npm run build:js`.
8. Go again to Global Configuration, tab "Server", section "Database".
9. If field "Host" has a value different to "localhost", change it to "localhost".
Result: See screenshot 1 in section "Expected result" below.
10. Change the host to something different to "localhost".
Result: See screenshot 2 in section "Expected result" below.
11. Select option "Two-way encryption" of field "Connection Encryption".
12. Enter some values for the text fields related to database connection encryption.
Result: See screenshot 3 in section "Expected result" below.
13. Change the host back to "localhost".
Result: The options for database connection encryption are hidden again.
14. Change again the host to something different to "localhost".
Result: See screenshot 4 in section "Expected result" below.
15. Click the "Close" button in order to leave the form without saving the changes.

### Expected result

1. Database connection encryption related options are hidden if database host is "localhost".
j4-db-encryption-localhost-after-patch_2
2. The "Connection Encryption" field is shown if database host is different to "localhost".
j4-db-encryption-localhost-after-patch_3
3. If "Two-way encryption" is selected in field "Connection Encryption" you can enter values in the text fields shown in this case.
j4-db-encryption-localhost-after-patch_1
4. If the hostname has been changed to "localhost", the options for database connection encryption are reset.
j4-db-encryption-localhost-after-patch_4

### Actual result

When the database host (field "Host") is "localhost", fields related to database connection encryption are shown depending on the value selected in field "Connection Envrytion". If "Two-way encryption" is selected, you can enter values in the text fields shown in this case.

j4-db-encryption-localhost-before-patch

### Documentation Changes Required

See PR #26375 .

### CODE REVIEW

**Comment by richard67** [comment]
Potential testers please wait with testing until title does not contain "[WiP]" anymore and status on GitHub is not draft anymore.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6f293c0bf1e02c1bb43b8bd7747bf319e8611298<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26889">issues.joomla.org/tracker/joomla-cms/26889</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on ed138ce4f2253052d38a89365c6442634f05542e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26889">issues.joomla.org/tracker/joomla-cms/26889</a>.</sub>

**Comment by richard67** [comment]
@alikon @SharkyKZ Thanks for testing. Not sure if we should take it RTC. There is a review by @wilsonge requested automatically because he is code owner. What do you think?

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26889">issues.joomla.org/tracker/joomla-cms/26889</a>.</sub>

**Comment by HLeithner** [comment]
I tested this with mariadb, this pr removes a set ca path which could be used for server verification mentioned in #26888 

I merged this anyway and my 2 points from #26888 should be addressed soon.

Thanks for your work and tests.

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
