### PR TITLE
Fix deprecation warning in com_tags

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #37567 .

### Summary of Changes
The method getItem() returns an array but this is initialsed with "false".  

Remark: It  looks wrong that getItem() returns an array, but this is not in scope of this fix. 

### Testing Instructions
See #37567

### Actual result BEFORE applying this Pull Request
Deprecation warning

### Expected result AFTER applying this Pull Request
No deprecation warning 

### Documentation Changes Required
no

### CODE REVIEW

**Comment by richard67** [comment]
@chmst The issue which you have closed for this PR was not an issue but a PR, too. Maybe the issue tracker hasn’t shown that?

**Comment by chmst** [comment]
Not used to github on my IDE ;)

**Comment by frostmakk** [comment]
If this is a better solution than my PR just close mine, no problem.

**Comment by chmst** [comment]
Sorry ;) By chance I ad exactly the same code open when your PR appeared. I think your solution is better. Both resolve the deprecated warning.

**Comment by laoneo** [comment]
While this here is a correct fix, I'm wondering why it returns here https://github.com/joomla/joomla-cms/blob/c12c5c1f79a99a3e58fa50766ae524a1155be3de/components/com_tags/src/Model/TagModel.php#L318 an array with only one element that is again an array of properties. Should it not return just the array with properties?

**Comment by chmst** [comment]
I mentioned already that this method looks strange. A method getItem() should return an Item, not an array and have one integer as argument, not an array. This fix resolves only the php 8.1 warning,

**Review by laoneo — APPROVED** [review]

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on a105ac73aaaa6323a45437c98b4d2fda34417546<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37568">issues.joomla.org/tracker/joomla-cms/37568</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a105ac73aaaa6323a45437c98b4d2fda34417546<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37568">issues.joomla.org/tracker/joomla-cms/37568</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37568">issues.joomla.org/tracker/joomla-cms/37568</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
