### PR TITLE
[imp] New lang string for successful language installation

### PR DESCRIPTION
**Pull request by infograf768**
The language string for language installation is the same as used in general install. 
`COM_INSTALLER_INSTALL_SUCCESS="Installation of the %s was successful."`
In the case of general install, the variable is of the type

```
COM_INSTALLER_TYPE_TYPE_COMPONENT="component"
COM_INSTALLER_TYPE_TYPE_FILE="file"
COM_INSTALLER_TYPE_TYPE_LANGUAGE="language"
COM_INSTALLER_TYPE_TYPE_LIBRARY="library"
COM_INSTALLER_TYPE_TYPE_MODULE="module"
COM_INSTALLER_TYPE_TYPE_PACKAGE="package"
COM_INSTALLER_TYPE_TYPE_PLUGIN="plugin"
COM_INSTALLER_TYPE_TYPE_TEMPLATE="template"
```

This does not fit with installing a language pack as we get

screen shot 2016-05-17 at 08 20 48

Ugly in any language...

This PR adds a new string for language installation:
`COM_INSTALLER_INSTALL_LANGUAGE_SUCCESS="Installation of the <strong>%s</strong> language pack was successful."`
Which gives:

screen shot 2016-05-17 at 09 33 12

To test go to `administrator/index.php?option=com_installer&view=languages` and install any language.

### CODE REVIEW

**Comment by infograf768** [comment]
@brianteeman
I can change pack to package
`COM_INSTALLER_INSTALL_LANGUAGE_SUCCESS="Installation of the <strong>%s</strong> language package was successful."`
if you wish.

**Comment by brianteeman** [comment]
I was wondering if we even need that word at all.
COM_INSTALLER_INSTALL_LANGUAGE_SUCCESS="Installation of the
<strong>%s</strong> language was successful."


On 17 May 2016 at 08:52, infograf768 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> I can change pack to package
> COM_INSTALLER_INSTALL_LANGUAGE_SUCCESS="Installation of the
> <strong>%s</strong> language package was successful."
> if you wish.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10523#issuecomment-219644935>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
No objection.

**Comment by sgagner** [comment]
I think we can skip "pack" or "package" and just use "language"

**Comment by brianteeman** [comment]
Make it so and I will make it RTC- its a simple and obvious improvement

**Comment by imanickam** [comment]
The text phrase "Installation of the <strong>%s</strong> language was successful." is fine.

**Comment by infograf768** [comment]
Please mark test as successful IN https://issues.joomla.org/tracker/joomla-cms/10523

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 940a8223567863af3e9b7142d31180cbeb1d6b23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10523">issues.joomla.org/joomla-cms/10523</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10523">issues.joomla.org/joomla-cms/10523</a>.</sub>

**Comment by sgagner** [comment]
We could make even simpler like: "%s language is now installed."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10523">issues.joomla.org/joomla-cms/10523</a>.</sub>

**Comment by infograf768** [comment]
@sgagner 
Stefan, if we were doing that (which indeed could be done), it would not be consequent with other success messages we have all over. 
Let's see that, if necessary, for 4.0. :smiley:

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 940a8223567863af3e9b7142d31180cbeb1d6b23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10523">issues.joomla.org/joomla-cms/10523</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 940a8223567863af3e9b7142d31180cbeb1d6b23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10523">issues.joomla.org/joomla-cms/10523</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768!

**Comment by zero-24** [comment]
@joomla-cms-bot come here and fix the label :P

**Pull request merged**
