### PR TITLE
[4.3] Fix Tinymce and Codemirror version

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

With PR #38422 the versions of codemirror and tinymce was downgraded:
image
image

This PR updated these extensions back to:
- codemirror v5.65.6 #38156
- tinymce v5.10.5 #37949

### Testing Instructions

code review

### CODE REVIEW

**Comment by richard67** [comment]
I've just checked and can confirm that this PR here is complete, i.e. the version numbers in files "plugins/editors/codemirror/codemirror.xml" and "plugins/editors/tinymce/tinymce.xml" were not downgraded by PR #38422 and so still are right.

@brianteeman Could you have a look, too? Maybe I'm missing something?

**Comment by brianteeman** [comment]
is this even needed. It is for the 4.3 branch and when the next upmerge is done it will be resolved. And hopefully then it will have the latest updates merged.

Note: When you want to update a package you only do npm update package and not blindly npm update everything
Maintainers whenever there is a pr with a package-lock update you need to take extra care to make sure the submitter didnt make this mistake.

**Comment by richard67** [comment]
> It is for the 4.3 branch and when the next upmerge is done it will be resolved.

@brianteeman Not necessarily because the PR which downgraded the versions on 4.3-dev was committed after the ones which upgraded them on 4.2-dev, so there will not be any conflict on the upmerge, and git will keep it as it is. So I think this PR here is good to make sure it goes the right way. But you are right when there will be an update on these places in the package lock on the 4.2-dev branch later. Then this PR here will not be needed anymore because that later change would go up with the next upmerge after that.

**Comment by richard67** [comment]
> Note: When you want to update a package you only do npm update package and not blindly npm update everything Maintainers whenever there is a pr with a package-lock update you need to take extra care to make sure the submitter didnt make this mistake.

Fully correct. The mistake has happened when PR #38422 was merged, and that PR changed also other dependencies which should be checked. When doing like @brianteeman said, the package lock should show only expected changes for the updated backage and its dependencies.

The same applies to composer dependencies.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d9df23831c1e6c0b1c09a5eb01ea17a07ce0be6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38614">issues.joomla.org/tracker/joomla-cms/38614</a>.</sub>

**Comment by heelc29** [comment]
> and that PR changed also other dependencies which should be checked

`hotkeys-js` was updated to 3.9.4
image


For information: I updated the lockfile with `npm install codemirror@5.65.6` and `npm install tinymce@5.10.5` and reverted the changes of semantic versioning under dependencies

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d9df23831c1e6c0b1c09a5eb01ea17a07ce0be6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38614">issues.joomla.org/tracker/joomla-cms/38614</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38614">issues.joomla.org/tracker/joomla-cms/38614</a>.</sub>

**Comment by obuisard** [comment]
Thanks @heelc29. Can you update your branch so I can merge your changes? Thank you!

**Comment by brianteeman** [comment]
@obuisard you should have the rights to update the branch.

**Comment by obuisard** [comment]
> @obuisard you should have the rights to update the branch.

Hi Brian, it does not seem like I do, unless it is possible other than from the Github interface.

**Comment by brianteeman** [comment]
@obuisard then you need to speak to the other maintainers as they all can. Its crazy if you dont and it will take forever to get things merged. (unless the user has marked this as cannot be updated - can you update other PR?)

**Comment by obuisard** [comment]
Actually, you are right, I can update branches on other PRs, just not this one. Thank you Brian.

**Comment by heelc29** [comment]
> Thanks @heelc29. Can you update your branch so I can merge your changes? Thank you!

@obuisard Done 😀

**Comment by obuisard** [comment]
Thank you @heelc29 for the PR :-)

**Pull request merged**
