### PR TITLE
[4.0] Router factory service

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
RouterFactory service similar to #16449. Additionally a cleanup is made as the static function `getRouter` from the application is called in a none static way.

### Testing Instructions
Browse around on the front and back end.

### CODE REVIEW

**Comment by brianteeman** [comment]
Maybe my misunderstanding but **only** in some files where you have added `RouterFactoryInterface`  you have also added
`use Joomla\CMS\Router\RouterFactoryInterface;
`

Shouldn't it be in all?

**Comment by laoneo** [comment]
If they are in the same namespace you don't need to add the import for these classes as they are imported automatically. I didn't import only in the classes of the namesapce Joomla\CMS\Router.

**Comment by brianteeman** [comment]
Thank you for the explanation.

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 86dea2c7258d4d11936478fe245e9a60a46d6e4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22642">issues.joomla.org/tracker/joomla-cms/22642</a>.</sub>

**Pull request closed without merging**
