### PR TITLE
[4.2] PHP8.2 deprecated dynamic properties

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

> The creation of dynamic properties is deprecated

https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties

Add `header` property to magic `__get` and `__set` methods

### Testing Instructions

Open category edit view with workflows enabled (com_categories/category/edit)

### Actual result BEFORE applying this Pull Request

PHP Deprecated:  Creation of dynamic property `Joomla\CMS\Form\Field\SqlField::$header` is deprecated in `libraries/src/Form/FormField.php` on line 591

### Expected result AFTER applying this Pull Request

No deprecated message

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on c7038babe0758020a994dfae3bc1be6f30fdc945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39502">issues.joomla.org/tracker/joomla-cms/39502</a>.</sub>

**Comment by laoneo** [comment]
The CalendarField has the same issue.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 7975d0ccdc31df9476d2a365d29c6735e512a6df<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39502">issues.joomla.org/tracker/joomla-cms/39502</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39502">issues.joomla.org/tracker/joomla-cms/39502</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
