### PR TITLE
Redo of PR 6323

### PR DESCRIPTION
**Pull request by Mathewlenning**
Simple cleaning of a few redundant conditionals

### CODE REVIEW

**Comment by ThomasFinnern** [comment]
Please add a testing instruction<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7980">issues.joomla.org/joomla-cms/7980</a>.</sub>

**Comment by pos-it** [comment]
I have tested this item :red_circle: unsuccessfully on aa2bd878e63c52ea8ac2042fde889d680ea7d83a<br /><br />I used the Module mod_qlform v9.3.1 that create cusomed Forms.
As soon as I activate this patch a get a Fatal Error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7980">issues.joomla.org/joomla-cms/7980</a>.</sub>

**Comment by si-wi** [comment]
I have tested this item :red_circle: unsuccessfully on aa2bd878e63c52ea8ac2042fde889d680ea7d83a<br /><br />the new version of getAttribute will never return an attributes value, but always default (null)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7980">issues.joomla.org/joomla-cms/7980</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for creating this. It’s been some time since you created this and there are now some merge conflicts that prevent a direct merge and also 2 unsuccessful tests. I will close this PR now. If you want to update your PR, then this can be re-opened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7980">issues.joomla.org/joomla-cms/7980</a>.</sub>

**Pull request closed without merging**
