### PR TITLE
Admin menu module - fix preset modern for postgresql

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

Fix sql error in postgresql database in admin menu.

### Testing Instructions

Error exists only on postgresql.

#### Before patch
jpeek0

#### After patch
jpeek1

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1471f13fe256d2da3b79845ae0e03fe4ab23706c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18537">issues.joomla.org/tracker/joomla-cms/18537</a>.</sub>

**Comment by csthomas** [comment]
As my change is equal to the same line in 
https://github.com/joomla/joomla-cms/blob/54eb5d8cea29b064c2ad2122e15e71d478c60b01/administrator/components/com_menus/presets/joomla.xml#L213

another test may be done by code review or by test on mysql only.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1471f13fe256d2da3b79845ae0e03fe4ab23706c
### System information
3.8.3-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18537">issues.joomla.org/tracker/joomla-cms/18537</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
