### PR TITLE
Fix Calendar field for subform field 2

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #15842

### Summary of Changes
Fix Calendar field for subform field, again.

### Testing Instructions
Make sure that calendar field work in the subform 
Example xml, can place in "Custom HTML" module xml (somwhere in params fieldset):
```xml
<field name="items" type="subform"  multiple="true"  label="Subform Field" >
  <form>
    <field name="something"  type="calendar" label="Calendar" />
  </form>
</field>
```

### Documentation Changes Required
none

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on b81755549821093cfc2e23b756f9cbd50c512853<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15848">issues.joomla.org/tracker/joomla-cms/15848</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on b81755549821093cfc2e23b756f9cbd50c512853<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15848">issues.joomla.org/tracker/joomla-cms/15848</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@laoneo @dgt41 @Fedik can you have a look at this https://github.com/joomla/joomla-cms/issues/15842#issuecomment-299813736 comment, seems not fixed 100%

**Comment by dgt41** [comment]
@rdeutz this PR should fix it

**Comment by wilsonge** [comment]
Looks like it solved the issue Robert mentioned (and the test was just bad). As this was RTC previously and all that's happened since is a rebase I've merged this :)

**Pull request merged**
