### PR TITLE
[4.0] fix 16864 should be $lang

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/16864 .

### Summary of Changes

Solves issue from https://github.com/joomla/joomla-cms/commit/2f3efb98af5d15dbcf482b0cc33e7421532fca5b.

image

### Testing Instructions

quick test
- use latest 4.0
- Apply patch manually
- Install patchtester (https://github.com/joomla-extensions/patchtester/releases/download/3.0.0-beta3/com_patchtester.zip)
- go to patchtester and fetch data, confirm all works fine

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@franz-wohlkoenig please test

**Comment by franz-wohlkoenig** [comment]
i haven't find a Way to test Patchtester as fetching Data cause the Error.

**Comment by andrepereiradasilva** [comment]
yes, that's what this PR solves
in this case you must appply the patch manually

Just Replace /administrator/templates/atum/component.php
By this
https://raw.githubusercontent.com/andrepereiradasilva/joomla-cms/438871003ff510e4ba872f40dfa2ecd89c4054ae/administrator/templates/atum/component.php

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 438871003ff510e4ba872f40dfa2ecd89c4054ae<br /><br />thanks for helping Testing @andrepereiradasilva <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16865">issues.joomla.org/tracker/joomla-cms/16865</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@wilsonge please check and merge so we can use the patchtester in 4.0

**Comment by Bakual** [comment]
Merged since really needed :smile:

**Pull request merged**
