### PR TITLE
joomla 3.7 com_contact php mail form not fire

### PR DESCRIPTION
**Pull request by ghost**
If I try Joomla 3.7 admin Global Config > Server > Mail Settings > Mailer = PHP Mail > Send Test Mail
Result : The email was sent successfully to ... and I get the test email

Now if I try to send a form using com_contact the page is redirected to Contact Redirect (an article in the settings)  but I never get any email

Thanks for helping

### CODE REVIEW

**Comment by brianteeman** [comment]
Please revise this against the staging branch

**Comment by ymages** [comment]
brianteeman  no idea how it works and no idea what is staging branch

**Comment by franz-wohlkoenig** [comment]
@ymages looks like you want report an issue and not an PR?

**Comment by ymages** [comment]
yes but no idea how and where to do it

**Comment by franz-wohlkoenig** [comment]
- If you have a Question: [Forum](https://forum.joomla.org/)
- Report a Bug: [New Issue](https://github.com/joomla/joomla-cms/issues/new)

**Comment by franz-wohlkoenig** [comment]
clsed as no PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15720">issues.joomla.org/tracker/joomla-cms/15720</a>.</sub>

**Pull request closed without merging**
