### PR TITLE
[4.0] Dont break com_config and the installer on update

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Dont break com_config and the installer on update

#### first test
- Install 4.0-alpha12-dev on windows
- confirm that com_config works (system -> Global configuration)
- conform that the installer code is still there as expected
- got to system -> Update -> Joomla -> Live Update
- reinstall core files
- notice that the installer code is gone
- notice that com_config is broken (windows systems only)

#### second test
- install a fresh copy of 4.0-alpha12-dev
- check that com_config works
- check installer code is still there
- update using this update server: https://www.jah-tz.de/downloads/core/com_config/com_config.xml
- notice com_config still works and the installer code is not removed

### Expected result

Installer is still there & com_config is not broken

### Actual result

installer is gone & com_config is broken on windows systems

### Documentation Changes Required

none

### Next steps

~~- [ ] set that folders to the blacklist in the build script https://github.com/joomla/joomla-cms/blob/staging/build/deleted_file_check.php~~

### CODE REVIEW

**Comment by mbabker** [comment]
> * set that folders to the blacklist in the build script https://github.com/joomla/joomla-cms/blob/staging/build/deleted_file_check.php

There shouldn't be a blacklist in that script.  The entire intent is to write out a list of deleted files between any two git references.  It's up to whomever is using the file that script generates to decide what to do with the data, which means reviewing it and not just copy/pasting the entire file into the com_admin script.

**Comment by zero-24** [comment]
ok thanks just maked it as obsolte than :)

**Comment by wilsonge** [comment]
There needs to be a blacklist in my new script that i used to generate this however - because it's doing directory iterations https://github.com/joomla/joomla-cms/pull/25559/files

**Comment by SharkyKZ** [comment]
Is this supposed to solve #25531?

**Comment by SharkyKZ** [comment]
This is fine when updating between 4.0 versions. But not when upgrading from 3.x.

**Comment by ceford** [comment]
I experience this with J4 beta1-dev - after update folders are missing from com_config. A temporary solution is to copy com_config from an expanded package zip file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26202">issues.joomla.org/tracker/joomla-cms/26202</a>.</sub>

**Comment by wilsonge** [comment]
Installation fixes will be solved by https://github.com/joomla/joomla-cms/pull/25559 and com_config probably needs a better fix because on linux systems we won't clean up properly the old j3 directories after this is applied so closing this. com_config issue still needs to be solved and tracked in #25531

**Comment by zero-24** [comment]
@wilsonge when we don't want to apply this workaround until we have a final version than please mention this issue in the release notes so everyone is aware of this issue.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/27481 com_config proper patch

**Pull request closed without merging**
