### PR TITLE
[4.0] Fix broken iframe + modal + backdrop combination

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #19408 .

### Summary of Changes
Next try for fixing the broken modal and backdrop problem.

The problem (and difference to the article batch which uses the same button than the patchtester) is, that we're loading an IFrame in the modal and doing this, the button creates the modal directly after the button (HTML code). That leads to the fact, that with the position: fixed/relative + flex structure of the page the modal is behind the darkening backdrop background.

A quick solution here is to move the modal in this (and only this) special case just before the ```</body>``` tag, so there is no strange influence from the positioning.

### Testing Instructions
See here: #21343 you can install the patchtester from [here](https://github.com/joomla-extensions/patchtester/releases) and test the "fetch data" modal.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c083216fe51de0093614d1b48a7cab535db0a125<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21847">issues.joomla.org/tracker/joomla-cms/21847</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on c083216fe51de0093614d1b48a7cab535db0a125<br /><br />Welcome correction.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21847">issues.joomla.org/tracker/joomla-cms/21847</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by dgrammatiko** [comment]
@wilsonge Please don't merge this!!!

**Comment by ghost** [comment]
Status set back on "Pending".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21847">issues.joomla.org/tracker/joomla-cms/21847</a>.</sub>

**Comment by dgrammatiko** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/21852

**Comment by fancyFranci** [comment]
#21852 is closed now, so this patch here is ready to commit again...
I tested it too and it's working in every major browser.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21847">issues.joomla.org/tracker/joomla-cms/21847</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
This is really dreadful. Merging to unblock patchtester. But this needs a better fix so created https://github.com/joomla/joomla-cms/issues/22044 to track this

**Pull request merged**
