### PR TITLE
Modify Function name to avoid conflict with PHP keyword. 

### PR DESCRIPTION
**Pull request by eeshaanSA**
Pull Request for Issue  #37823 

### Summary of Changes
Added a new function '_match' with contents same as the original function. The 'match' function is now just a proxy to the '_match' function, and will be deprecated before version 5.0

### Testing Instructions

-

### Actual result BEFORE applying this Pull Request

-

### Expected result AFTER applying this Pull Request

-

### Documentation Changes Required
Nothing i am aware of. please let me know if any.

### CODE REVIEW

**Comment by eeshaanSA** [comment]
I still haven't logged the deprecation because i am still a little confused about that. Now that the change is pushed, @richard67 you can suggest any more required changes.

**Comment by richard67** [comment]
> I still haven't logged the deprecation because i am still a little confused about that. Now that the change is pushed, @richard67 you can suggest any more required changes.

@eeshaanSA It wouldn't really be good for your learning curve if I would suggest the complete code. One thing I see is that the new method does not have a doc block. As this PR is not really necessary I think you should not waste much time with it and maybe focus on some other issue.

**Comment by eeshaanSA** [comment]
i am working on the doc block, although what do you suggest? Should i close this PR? OR try working on the doc block and deprecation log?

**Comment by richard67** [comment]
> i am working on the doc block, although what do you suggest? Should i close this PR? OR try working on the doc block and deprecation log?

Depends on if you want to spend time with it. I would be ok with both.

**Comment by laoneo** [comment]
If I can make a suggestion. I would leave the name as it is as there is no need to make a new one. There are many other issues where we need your help. For example this one https://github.com/joomla/joomla-cms/issues/37801 is a good one for starters.

**Comment by eeshaanSA** [comment]
sure @laoneo, will explore that issue.

**Comment by laoneo** [comment]
@eeshaanSA I'm closing this pr for now. Thanks for your contribution on making Joomla better and would love to see more pr's from you.

**Pull request closed without merging**
