### PR TITLE
[4.4] package.json

### PR DESCRIPTION
**Pull request by brianteeman**
in another project I maintain we always update the version number here with each release

### CODE REVIEW

**Comment by richard67** [comment]
Shouldn't this then be done either by the build or by the bump script?

**Comment by brianteeman** [comment]
yes it should be automated - _if maintainers think it should be changed at all_ which I wasnt sure about as its never been updated

**Comment by brianteeman** [comment]
rebased to 4.4

**Comment by laoneo** [comment]
This should either be bumped with the bump script or removed all together as the CMS is not a library where other npm packages depend on.

**Comment by brianteeman** [comment]
Updated as requested to be managed by the bump script #40513

**Pull request closed without merging**
