### PR TITLE
Finder Link Date Information

### PR DESCRIPTION
**Pull request by brianteeman**
This PR improves the readability of the popover
#### Summary of Changes

Added new string for the title and added some basic formatting
#### Before

before
#### After

after

### CODE REVIEW

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on fd4a910e4c94366bd3c27a6506ee84bc78314857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10058">issues.joomla.org/joomla-cms/10058</a>.</sub>

**Comment by brianteeman** [comment]
@chrisdavenport have to say I dont understand the difference between published start and content start

**Comment by chrisdavenport** [comment]
For Articles at least, the publish start/end dates are the publish up/down dates and the content start date is the date on which content item was created.  The content end date is not used for Articles.

Of course, other content types may have subtly different meanings for those dates.

The publish start/end dates are *always* applied to filter search results.  The content start/end dates may be specified in the user search query.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fd4a910e4c94366bd3c27a6506ee84bc78314857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10058">issues.joomla.org/joomla-cms/10058</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @chrisdavenport 

Is the content start/end ever relevant

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10058">issues.joomla.org/joomla-cms/10058</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the merge conflicts, thanks.

**Comment by brianteeman** [comment]
Fiddlesticks. Will do in a bit

**Comment by chrisdavenport** [comment]
> Is the content start/end ever relevant

You can include dates in the search query.  For example, you can enter a query such as

`something and after:2015-01-01`

or even a range such as

`somethingelse and before:2016-01-01 and after:2015-01-01`

For some reason you must enter at least one search term, otherwise the dates are ignored.  I think that's a bug.

You can also set up static search filters using dates and date ranges.  That's what the "Filter Timeline" tab is for.

**Comment by brianteeman** [comment]
closed Please see #10081 to resolve merge conflicts<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10058">issues.joomla.org/joomla-cms/10058</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman can you remove the milestone here as this PR is not merged?

**Pull request closed without merging**
