### PR TITLE
[4.0] remove obsolete 3.x sql updates

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes

remove obsolete 3.x sql updates

### Testing Instructions
code review

### CODE REVIEW

**Comment by brianteeman** [comment]
Surely if I upgrade from 3.7 directly to 4.0 they are needed

**Comment by alikon** [comment]
maybe i can be wrong but you cannot upgrade to 4 from anything else than 3.10

**Comment by infograf768** [comment]
I thought one had to first update to 3.10

**Comment by brianteeman** [comment]
But the schedule is to release both on the same day?

**Comment by infograf768** [comment]
It's imho just a matter of forcing joomalupdate to first propose update to 3.10 for any site and then propose 4.0 for updating.

**Comment by HLeithner** [comment]
@brianteeman you can only update from Joomla 3.10 to 4.0

**Comment by richard67** [comment]
@HLeithner That's not really right: Currently you can update also from 3.9. As long as the 3.10-dev branch was not up to date with latest changes in staging, we always tested the update path with 3.9.x.

As far as I know it is like @infograf768 said: The update to 4.0 will just not be proposed for 3.9 or earlier.

But up to now I can see no code keeping someone from updating a 3.9 or earlier to a 4.0 alpha or nightly using the Upload&Update tab of the Joomla Update component.

**Comment by richard67** [comment]
@wilsonge Regarding updating a pre-3.10 to 4.0 using the Upload&Update tab of the Joomla Update component: Is it planned to add some code in future to block this? If so, this PR here is absolutely ok. If not, it could be a problem because we have no control on which version will be updated. People could try to do that with a 3.5 maybe. Up to now, when we tested the update path we were using latest 3.9. For this scenario, this PR here would also be ok. Only for updating a pre-3.9 it would be a problem.

**Comment by HLeithner** [comment]
Joomla 3.10 should include an upgrade check for Joomla 4 (PHP version checking, mysql version checking) and so on. This also allows us some cleanups like removing the sql files from 10 years.

**Comment by richard67** [comment]
@HLeithner If J 3.10 includes such check, it does not keep people from updating a pre-3.10 to a 4.0 using the Upload&Update tab of the Joomla Update component. It will need a check in 4.0 in the update component that the version to be updated is a 3.10 and nothing older.

**Comment by brianteeman** [comment]
Exactly

**Comment by mbabker** [comment]
You can’t put code in the 4.0 update component either because that won’t run until the entire filesystem is updated.  Not to mention there isn’t a good “what version am I upgrading from” check in that code.

Any limitation is artificial at best.

**Comment by infograf768** [comment]
> Any limitation is artificial at best.

Then what do you suggest?

**Comment by mbabker** [comment]
Nothing more than is already done.  Limit when updates are shown through the update server configuration.  If you’re trying to code against the “but what if someone on 3.6.3 tries to upload the 4.0 package and direct upgrade” scenario, it’s too late for that.  There isn’t a pre-upgrade abort hook and any code in the new version runs after the filesystem is updated so the site is already for all intents and purposes at the new version you don’t want them upgrading to in the way they did.

Maybe someone with some foresight can rework things so that a pre-upgrade abort is possible but it is not usable for any version already released.

**Comment by richard67** [comment]
So this PR here should be ok, right?

**Comment by infograf768** [comment]
Or not.

**Comment by wilsonge** [comment]
@zero-24 before this is merged I'd like to remove 3.9.x as an available update path for 4.x

We've always said that we're only going to allow updates from the latest 3.x (originally 3.9 and then after the privacy changes 3.10) to 4.x. I don't see this as strictly different to how we've managed this in the past. We've always said for example from 1.7 you have to go to 2.5 to go to 3.x otherwise bad things can/will happen and of course that doesn't stop people from doing differently. We will definitely not allow this on the update site side (4.x will only show to sites on 4.x).

Yes people can shortcut this - but so can they by overriding files of Joomla 3.1 - and from there you can currently only get to 3.5 through the normal autoupdate process and no one screamed at that. 

TL/DR Yes this PR is fine

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/update.joomla.org/pull/153 cc @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
