### PR TITLE
Refactor allowEdit of backend category controller

### PR DESCRIPTION
**Pull request by ggppdk**
Make category controller similar to PRs

https://github.com/joomla/joomla-cms/pull/11503
https://github.com/joomla/joomla-cms/pull/11502
https://github.com/joomla/joomla-cms/pull/11511
### Testing instructions

Test that edit and edit own in backend category manager work properly

### CODE REVIEW

**Comment by ggppdk** [comment]
@wilsonge 

please do not forget of this one, it is related to the other PRs

**Comment by andrepereiradasilva** [comment]
humm... 

test user group = Administrator

### com_content permissions
image

### parent category permissions
image

### child category permissions
image

### result (when logged as test user)
image

It seems to works like this with or without your patch ...

**Comment by andrepereiradasilva** [comment]
forget it! the category was created by the user :)

**Comment by andrepereiradasilva** [comment]
ok so i just found on ething that seems an issue, or at leaset and inconsistency

- use a user with "Administrator" group
- create with that user this two categories

image
- Create another category with super user so it stays like this

image


- At com_content set Edit as Denied for the "Administrator" group
- At "Test ACL" level don't change permission
- At "Test ACL Sub" level set "Edit Own to "Denied" 
- At "Test ACL Sub (Super User)" level don't change permission
- Now use the test user and you will get something like this
image

All ok.
- Now try to access `/administrator/index.php?option=com_categories&task=category.edit&id=12&extension=com_content` (replace 12 for the id of the "Test ACL Sub (Super User)" category). You get 
image

- Now try to access `/administrator/index.php?option=com_categories&task=category.edit&id=11&extension=com_content` (replace 11 for the id of the "Test ACL Sub" category). Here, instead of getting the "Edit not allowed" error (as all the other cases) you go to the "Edit" layout, but without save buttons
image

This happens with and without your patch.
Can you check if this is the supposed behaviour?

**Comment by ggppdk** [comment]
Good catch, thanks

i replicated it , for an (administrator) user that owns the record (category),
and "edit own" was denied for administrator usergroup

In my local testing copy, 
i did not have that check included (so it was working properly in my tests ...),

and when editing the file via Github UI, i failed to remove it from the old code

please retest

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 076786142a504972687560def47dfc6ec1a32274<br /><br />Seems to work fine now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11547">issues.joomla.org/joomla-cms/11547</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 076786142a504972687560def47dfc6ec1a32274<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11547">issues.joomla.org/joomla-cms/11547</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Pull request merged**
