### PR TITLE
Follow up on #8057 for the other Databases

### PR DESCRIPTION
**Pull request by zero-24**
This is a follow up on #8057 

@alikon, @waader @pe7er can you assist and review / test the installation and updates?

---
# Testing instructions
## Before this PR

Components > **Messaging** (shows list of private messages) has two submenus:
- **New Private Message** (create new private message form) 
- **Read Private Messages** (shows list of private messages) which is a duplicate of the parent **Messaging** menu item

messaging-menu-before

Other components, like com_content, do not have such duplicate options.
See Content > Articles (shows list of articles) > has one submenu item **Add New Article** (create new article form)

messaging-menu-articles-example
## After this PR

The administrator menu items are created from records in the database. 
The database settings are created upon installation and therefore the testing procedure is a bit different:
- Install the patch
- remove configuration.php
- install Joomla again
- check the new menu settings:

Components > **Messaging** now has only one submenu: **New Private Message**

messaging-menu-after

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 07e4b7d4e393153aa7d98226dff6663b3c471f1e<br /><br />I have tested with postgres and mssql. Please remove the ' at the end of administrator/components/com_admin/sql/updates/sqlazure/3.5.0-2015-11-04.sql
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8274">issues.joomla.org/joomla-cms/8274</a>.</sub>

**Comment by zero-24** [comment]
Thanks @waader just done with the last commit

**Comment by alikon** [comment]
works as expected

**Comment by Kubik-Rubik** [comment]
Thank you @zero-24 and testers! Merged with: https://github.com/joomla/joomla-cms/commit/dc251b30a202137920ce045364e848d8e43dd510

**Pull request closed without merging**
