### PR TITLE
[4.0] Remove deprecated code in Joomla\CMS\Menu\MenuItem

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes deprecated code from `Joomla\CMS\Menu\MenuItem`.

### Testing Instructions

Install sample data or create some menu items.
Navigate frontend and backend.
Inspect menu items.

### Expected result

Works like before.

### Documentation Changes Required

Some methods removed.
Added `Joomla\CMS\Menu\AdministratorMenuItem` class.

### CODE REVIEW

**Comment by amit4106udale** [comment]
I have tested this item :red_circle: unsuccessfully on 9137ad01fc67a0dc72a1ac0350c3b1b8b911793f<br /><br />Error: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params: Cannot access protected property Joomla\CMS\Menu\MenuI<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26537">issues.joomla.org/tracker/joomla-cms/26537</a>.</sub>

**Comment by SharkyKZ** [comment]
On which page are you getting this?

**Comment by amit4106udale** [comment]
> On which page are you getting this?

I was testing this on cloudaccess. And applied the patch. Once applied site became black.

**Comment by SharkyKZ** [comment]
Do you have any 3rd party extensions installed? Maybe using Cloudbase template?

**Comment by amit4106udale** [comment]
> Do you have any 3rd party extensions installed? Maybe using Cloudbase template?

No pure joomla 4 nightly build

**Comment by SharkyKZ** [comment]
Should work now but don't test yet. Performance could be bad at the moment.

**Comment by SharkyKZ** [comment]
OK, this can be tested now.

**Comment by Quy** [comment]
Go to Components Dashboard.

> Notice: Undefined property: Joomla\CMS\Menu\MenuItem::$permission in \administrator\modules\mod_submenu\Menu\Menu.php on line 56

> Notice: Undefined property: Joomla\CMS\Menu\MenuItem::$icon in \administrator\modules\mod_submenu\tmpl\default.php on line 22

**Comment by Quy** [comment]
Go to Components Dashboard:

> Notice: Undefined property: Joomla\CMS\Menu\MenuItem::$icon in \administrator\modules\mod_submenu\tmpl\default.php on line 22

**Comment by Hackwar** [comment]
I like these changes. However, the change from `browserNav` to `target` is a B/C break and needs to be properly documented.

**Comment by SharkyKZ** [comment]
No, it's not.

**Comment by SharkyKZ** [comment]
Though maybe there's a better way to do this. `browserNav` is a numeric value from database. In some places in backend it's overwritten with the string used in markup. `target` is only used in backend and it also holds same string. Do we need both of these properties? Maybe remove `target` and use only `browserNav`?

In frontend it's much simpler. Only `browserNav` is used and it does not get overwritten.

**Comment by isidrobaq** [comment]
I have tested this item :white_check_mark: successfully on 0460dd6709062d441e77ebfd7e42676cf40c3b83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26537">issues.joomla.org/tracker/joomla-cms/26537</a>.</sub>

**Comment by cheiff** [comment]
I have tested this item :white_check_mark: successfully on 0460dd6709062d441e77ebfd7e42676cf40c3b83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26537">issues.joomla.org/tracker/joomla-cms/26537</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26537">issues.joomla.org/tracker/joomla-cms/26537</a>.</sub>

**Comment by wilsonge** [comment]
> Though maybe there's a better way to do this. browserNav is a numeric value from database. In some places in backend it's overwritten with the string used in markup. target is only used in backend and it also holds same string. Do we need both of these properties? Maybe remove target and use only browserNav?

If that works - and they are exactly the same thing (struggling to tell from a quick code review - I'd probably go down that route. Maybe revert the rename here https://github.com/joomla/joomla-cms/pull/26537/files#diff-1b5557519e9638a5bde91cf3432456dfR403 and then make that change in a separate PR?

**Comment by SharkyKZ** [comment]
I think it's best to subclass `MenuItem` for administrator items and add missing properties there.

**Comment by wilsonge** [comment]
Thanks!

**Comment by xillibit** [comment]
I have this kind of call in my component : 
```$params      = Factory::getApplication()->getMenu()->getActive()->params; ``` with this change it display : Cannot access protected property Joomla\CMS\Menu\MenuItem::$params 

Can-i call instead ```$params      = Factory::getApplication()->getMenu()->getActive()->getParams();``` ? getParams() isn't deprecated anymore ?

**Comment by SharkyKZ** [comment]
Yes, use `getParams()` to access params.

**Comment by bugsmafia** [comment]
Error: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

Are these changes due to a bug on the frontend?

**Comment by SharkyKZ** [comment]
@bugsmafia Are you using any 3rd party extensions?

**Comment by bugsmafia** [comment]
> @bugsmafia Are you using any 3rd party extensions?

no, clean joomla 4 dev.
Files were updated (developer build of December 16) (with full replacement) after 1 month of development (build of November 7, 2019).

**Comment by SharkyKZ** [comment]
On which pages does this error occur?

**Comment by bugsmafia** [comment]
> On which pages does this error occur?
Any articles, including the default Featured Articles page
(whether a problem occurs with other components is unknown)

**Comment by bugsmafia** [comment]
/index.php?option=com_content&view=article&id=2&Itemid=103
Build on November 7th. on the links from the menu to any article gave an error 404.
after updating to the build on December 16th.
"Error: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params"

**Comment by SharkyKZ** [comment]
I can't replicate this issue on current nightly (https://developer.joomla.org/nightly-builds.html) and on my git clone.

If you upload a zip of your installation (only files, no database), I could take a look.

**Comment by bugsmafia** [comment]
> I can't replicate this issue on current nightly (https://developer.joomla.org/nightly-builds.html) and on my git clone.
> 
> If you upload a zip of your installation (only files, no database), I could take a look.

write me bugsmafia@gmai.com or Telegram @bugsm

yep, update only file (full pack), 
update structure DB does not fix the error

**Comment by bugsmafia** [comment]
I Found the source of the problem in my template.
`$pageclass = $menu->params->get('pageclass_sfx');`
or
`$pageclass = $menu->getParams()->get('pageclass_sfx');`

**Comment by wilsonge** [comment]
Documented this https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#JMenuItem

**Pull request merged**
