### PR TITLE
[4.0] Fix for Bug after creating an override

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/19475

### Summary of Changes
Set UA User agent to 'Joomla'

### Testing Instructions
1. Open Extensions->Templates-> Create overrides.
2. Try any option Module, Component, Layout. 
-> an error will occur.
3. Apply this patch and open Extensions->Templates-> Create overrides.
4. Try any option Module, Component, Layout. 
-> override is created.

### Expected result
Creates an override of the extension (folder+files)

### Actual result
Getting this error :
0 Argument 1 passed to Joomla\CMS\Version::getUserAgent() must be of the type string, null given, called in libraries/src/Factory.php on line 758

Folder is created, no files.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a80cc0ef66e8a4ddd4bef96686b93f9468ebcefa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19482">issues.joomla.org/tracker/joomla-cms/19482</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on a80cc0ef66e8a4ddd4bef96686b93f9468ebcefa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19482">issues.joomla.org/tracker/joomla-cms/19482</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
