### PR TITLE
Remove @package tag from library doc blocks

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #26395.

### Summary of Changes

Removes `@package` and `@subpackage` tags from core library files.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 55f08b67f5c64c392f2c3d213dd2121e8788b466<br /><br />Covers all occurrences of "@package" or "@subpackage" in PHP files below libraries/src of current staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26405">issues.joomla.org/tracker/joomla-cms/26405</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 55f08b67f5c64c392f2c3d213dd2121e8788b466<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26405">issues.joomla.org/tracker/joomla-cms/26405</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26405">issues.joomla.org/tracker/joomla-cms/26405</a>.</sub>

**Comment by richard67** [comment]
What about the PHCS sniffer thing which Michael suggested in his issue in order to avoid such doc block content in future? Does anyone have the knowledge and mood and time to do that?

**Comment by SharkyKZ** [comment]
I can find time and maybe even mood but have no knowledge 😕

**Comment by SharkyKZ** [comment]
Scribbled something up https://github.com/joomla/coding-standards/pull/255.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
