### PR TITLE
[5.2] Fix Multilingual Associations Infinite Loop

### PR DESCRIPTION
**Pull request by MatMyfta**
Pull Request for Issue #44224 

### Summary of Changes

This update implements conditional checks to verify the existence of specified variables before accessing or modifying their values. This enhancement prevents potential runtime errors associated with null or undefined variables.

### Testing Instructions

Described in the issue

### Actual result BEFORE applying this Pull Request

Described in the issue

### Expected result AFTER applying this Pull Request

- Console errors related to variable access will be resolved.
- The infinite loop that previously caused the administration console to become unresponsive is eliminated.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by newtastic** [comment]
I have tested this item :white_check_mark: successfully on 2b457d342b483e401c21faefd611706f8b0cee6a<br /><br />I tested this with J5.2.0 Stable and it works like excepted now!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44360">issues.joomla.org/tracker/joomla-cms/44360</a>.</sub>

**Comment by fgsw** [comment]
Test by using prebuilt package:

```
Uncaught TypeError: n.querySelector(...) is null
    <anonymous> https://j44360:8890/media/com_associations/js/sidebyside.min.js?983476:4
    <anonymous> https://j44360:8890/media/com_associations/js/sidebyside.min.js?983476:4
```

**Comment by MatMyfta** [comment]
What prebuilt package are you testing? 
The changes are made on the build directory, so all the resources in media have to be rebuild with the new changes.

**Comment by fgsw** [comment]
> The changes are made on the build directory

Had only looked at the prebuild package at the end of the Pull Request and not at the Directory-Path if it contain ```build```.

Would be better in cases like this to not offer prebuilt packages.

**Comment by Quy** [comment]
Installed the pre-built package:

44360-multilingual

**Comment by Quy** [comment]
Still an issue:

44360-multilingual

**Comment by Quy** [comment]
44360-multilingual2

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cdad048e8dd71d25a65342a36e9684c01d6913fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44360">issues.joomla.org/tracker/joomla-cms/44360</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cdad048e8dd71d25a65342a36e9684c01d6913fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44360">issues.joomla.org/tracker/joomla-cms/44360</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44360">issues.joomla.org/tracker/joomla-cms/44360</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution!

**Pull request merged**
