### PR TITLE
[4.0] Update and improve installer warnings

### PR DESCRIPTION
**Pull request by brianteeman**
The installer warnings are displayed as a pair of a title and description in com_installer&view=warnings. Because they are a pair some of the text is being repeated. This PR fixes that. See the example below

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d85a62ef4388f0195caeb8bbce5aa59459bf13ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24909">issues.joomla.org/tracker/joomla-cms/24909</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d85a62ef4388f0195caeb8bbce5aa59459bf13ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24909">issues.joomla.org/tracker/joomla-cms/24909</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by roland-d** [comment]
Thank you

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
