### PR TITLE
Search statistics enable link

### PR DESCRIPTION
**Pull request by brianteeman**
This PR adds a link to the options to make it easier for people to find out how to enable the search statistics. This is the same style as the link in the Redirect component
### Before

before
### After

after

### CODE REVIEW

**Comment by jwaisner** [comment]
@test 

PR works as intended. Adds link to options to enable search statistics.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7471">issues.joomla.org/joomla-cms/7471</a>.</sub>

**Comment by Fedik** [comment]
**test** it works :smile:

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7471">issues.joomla.org/joomla-cms/7471</a>.</sub>

**Comment by Bakual** [comment]
Do we really need a link in the language strings when the button is on the same page?
For com_redirect I can see the use since it additionally applies a search filter to get directly to the plugin.

**Comment by brianteeman** [comment]
We do need the text "in the options"
Its optional if it is a link or not
But I have had a lot of users who ask where the options are - they dont see them on the right.

**Comment by Bakual** [comment]
> We do need the text "in the options"

I agree that is helpful.

> But I have had a lot of users who ask where the options are - they dont see them on the right.

If they can't find the button, then maybe they should better not find it anyway. :smile: 
Personally I would do it without a link.

**Comment by brianteeman** [comment]
If it means it will be committed I will update it to remove the link

**Comment by Bakual** [comment]
I would prefer that (and promise to merge :smile:  )

**Comment by brianteeman** [comment]
Updated (but Robert already took me to 200 :smile: )

**Comment by Bakual** [comment]
Saw that. Now 1000 is the next goal? :smile:

**Pull request merged**
