### PR TITLE
Module Manager. Integrate searchtools.

### PR DESCRIPTION
**Pull request by ghost**
- This is a rework of https://github.com/joomla/joomla-cms/pull/6682 that failed with Hathor. 
- "Fixes" also feature request https://github.com/joomla/joomla-cms/issues/6656 (Possibility to reset all filters with one click in Isis).
- Additionally it resets filter fields Position, Language and Type when filter Client changed (ISIS and HATHOR).
- I've tested with current staging 2015-05-15.

Test:
- Please do not forget to test Hathor, too. Set filters, change client and click Submit and so on.
- Go to Extensions > Module Manager.
- Before patch:

All filters in sidebar.

com_modules-manager1
- After patch 

com_modules-manager2

### CODE REVIEW

**Comment by jwaisner** [comment]
@test 

Patch works as intended. No errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6958">issues.joomla.org/joomla-cms/6958</a>.</sub>

**Comment by brianteeman** [comment]
Great stuff
Works perfect in ISIS and no issue in Hathor
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6958">issues.joomla.org/joomla-cms/6958</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6958">issues.joomla.org/joomla-cms/6958</a>.</sub>

**Comment by wilsonge** [comment]
Can you merge in staging to fix conflicts please :)

**Comment by watchfulli-dev** [comment]
@test seams to be fine, applied the patch and we can see the filters as in the print screen provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6958">issues.joomla.org/joomla-cms/6958</a>.</sub>

**Comment by roland-d** [comment]
Thank you for your contribution. This has been merged into 3.5-dev with commit a6d0c12

**Pull request closed without merging**
