### PR TITLE
[4.0] com_users notes blank state

### PR DESCRIPTION
**Pull request by brianteeman**
See #33264 for instructions but this time for user notes  and not content

This PR requires the code from #33264 to be merged first - specifically the change in libraries/src/MVC/Model/ListModel.php

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c730b20a3f1174835b13e474938f6370f6506fa6<br /><br />Test was possible, after applying also the other PR in addition<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33273">issues.joomla.org/tracker/joomla-cms/33273</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c730b20a3f1174835b13e474938f6370f6506fa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33273">issues.joomla.org/tracker/joomla-cms/33273</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33273">issues.joomla.org/tracker/joomla-cms/33273</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
