### PR TITLE
Label - Mass Mail Users

### PR DESCRIPTION
**Pull request by pe7er**
The language label "**Mass Mail Users**" in the back-end menu Users is **not consistent** with the Component Title label "**Mass Mail**".
### Summary of Changes

This PR changes the language label to "Mass Mail Users" to "Mass Mail" because the title of that view 
administrator/index.php?option=com_users&view=mail
shows it as "Mass Mail"

mass-mail
#### Before the PR:

backend: Users > 
last **menu item: Mass Mail Users**

mass-mail-before
#### After the PR:

backend: Users > 
last **menu item: Mass Mail**

mass-mail-after

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 542f8cb1aef0fcb3321fae75d83675f4f61ee099<br /><br />Agree looks better<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12077">issues.joomla.org/joomla-cms/12077</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 542f8cb1aef0fcb3321fae75d83675f4f61ee099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12077">issues.joomla.org/joomla-cms/12077</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12077">issues.joomla.org/joomla-cms/12077</a>.</sub>

**Comment by brianteeman** [comment]
I agree it is not consistent but I am not convinced this PR is changing the correct one. Personally I would have changed the title to match the menu as it is more accurate.

@jeckodevelopment please do not make changes like this RTC without comment by at least one native english speaker

**Comment by jeckodevelopment** [comment]
ok @brianteeman

**Comment by pe7er** [comment]
@brianteeman @jeckodevelopment Thank you for testing & looking into this issue!

Yeah, I thought about keeping the menu title and changing the Title in the view, 
but as a lot of menus have been shortened (Article Manager -> Articles, etc) recently (which I like),
and because the "Mass Mail (Users)" menu is under "Users" just like "Manage (Users)",
I created the PR like this.

An alternative PR to make the Menu Item + Title on the view consistent: https://github.com/joomla/joomla-cms/pull/12084

**Comment by zero-24** [comment]
So we can close here @pe7er and use #12084 which implement Brian's suggestion?

**Comment by pe7er** [comment]
Yes, please do. If a lot of other people would come up with arguments for solving it this way, then we could always open the PR again :-)

**Comment by pe7er** [comment]
Ehm, I'll close it myself :-)

**Pull request closed without merging**
