### PR TITLE
[4.0] Redefine the naming of the "default stage"

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Name the "default stage" to "Initial Stage" to make it more clear what it is about.

### Testing Instructions
Go to the stages list view and look at the table header and to the stage form view and look on the right side for the switcher

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9e5d8f4e824f42ca1826902ed80dd7a9414e0a49<br /><br />I have tested this item successfully. "initial state" is more intuitive than "default state".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21845">issues.joomla.org/tracker/joomla-cms/21845</a>.</sub>

**Comment by wilsonge** [comment]
Do you not need to remove the other strings?

**Comment by bembelimen** [comment]
You mean "COM_WORKFLOW_DEFAULT"? No, becuase it's used for the workflow itself.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9e5d8f4e824f42ca1826902ed80dd7a9414e0a49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21845">issues.joomla.org/tracker/joomla-cms/21845</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by infograf768** [comment]
Drone fails unrelated. See https://github.com/joomla/joomla-cms/pull/21849

**Comment by brianteeman** [comment]
This still doesn't resolve the fact that the initial/default stage completely ignored the ACL. Until that's resolved it is just lipstick on a pig

**Comment by brianteeman** [comment]
This still doesn't resolve the fact that the initial/default stage completely ignored the ACL. Until that's resolved it is just lipstick on a pig

**Comment by brianteeman** [comment]
> I have tested this item successfully. "initial state" is more intuitive than "default state".

Changing the column header from "Default" to "Initial Stage" isn't more intuitive to me (my 2c) especially when we have another column "Condition of items in this stage:"

**Review by brianteeman — COMMENTED** [review]
I dont agree with this change

**Comment by wilsonge** [comment]
Would starting stage make more sense?

**Pull request closed without merging**
