### PR TITLE
[com_banners] banners view: Add max level filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

All backend views that are or are associated with tree like structures (e.g. menus, categories) should have a max level filter.

This is valid currently for:
- com_menus items view
- com_content articles view
- com_content featured view
- com_tags tags view

So, this PR is a part of series of PR to add that filter in the views that use categories:
- com_contacts contacts view (RTC https://github.com/joomla/joomla-cms/pull/9975)
- com_banners banners view (**this PR**)
- com_newsfeeds newsfeeds view (RTC https://github.com/joomla/joomla-cms/pull/9978)
- com_notes notes view (RTC https://github.com/joomla/joomla-cms/pull/9984)
- com_banners tracks view (https://github.com/joomla/joomla-cms/pull/10009)

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Create some banners categories with at least two levels
3. Create some banners and associate them to the categories created in 2..
4. Test the new max levels filter.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3051f443cd05d1de6b5c05b74773bebbd684a0db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9977">issues.joomla.org/joomla-cms/9977</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3051f443cd05d1de6b5c05b74773bebbd684a0db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9977">issues.joomla.org/joomla-cms/9977</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @richard67 thanks for testing again!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9977">issues.joomla.org/joomla-cms/9977</a>.</sub>

**Comment by rdeutz** [comment]
technically this is a new feature and it doesn't fix a bug so it has to go into 3.6.0

**Comment by rdeutz** [comment]
@andrepereiradasilva cloud you please check the merge conflicts, thanks

**Comment by andrepereiradasilva** [comment]
conflicts fixed

**Pull request merged**
