### PR TITLE
Fatal error: Call to undefined method JDocumentRaw::isHtml5()

### PR DESCRIPTION
**Pull request by boomsya**
Many components using format=raw in URI and component have some errors (like errors in SQL) they have see only this:
Fatal error: Call to undefined method JDocumentRaw::isHtml5()

but with some modification I see page 1057 with rendered page error.php from template

### CODE REVIEW

**Comment by wojsmol** [comment]
@boomsya see https://github.com/boomsya/joomla-cms/pull/1

**Comment by Fedik** [comment]
hm, as I remember `JDocumentRaw` does not meant to have the header, and so does not use `JDocumentRendererHead` itself, it just for render the "raw" component output ... 
no idea how you ended up there, you sure that you do things correct?

**Comment by Bakual** [comment]
A component using raw output ideally shouldn't ever get redirected to the error.php page. That means your output is broken anyway since a HTML page is served instead of a raw output (which may be anything else).
So it looks more like an error in your component where you should catch that error and give a proper error response in the format you need.

However if you want to server a HTML page, then Fedik is right in that you shouldn't use format=raw but instead tmpl=component which is supposed to only return the component output (without any modules).

**Comment by roland-d** [comment]
@boomsya I am closing this PR as it seems to be a coding error in a component If you want to pursue this further, feel free to re-open the pull request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8286">issues.joomla.org/joomla-cms/8286</a>.</sub>

**Pull request closed without merging**
