### PR TITLE
[5.x] Missing Strings [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Many of the labels for the filters in the xtd-editor modals were either missing or the language string was missing or the language string was incorrect  when the xtd-editor modals are used in the frontend

I have made this as a change to 5.0 as I see this as a bug fix and not a feature

### Testing Instructions
Enable debug lang
Log in to site and create or edit an article
Open each of the xtd-editor modals as below
image

### Actual result BEFORE applying this Pull Request
Many untranslated strings listed in the debug

### Expected result AFTER applying this Pull Request
No untranslated strings listed in the debug

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
Can I expect that the description attributes has never (at at least currently)  been used?

**Comment by brianteeman** [comment]
> Can I expect that the description attributes has never (at at least currently) been used?

that is correct and they are not used in the equivalent admin views.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0ddd40fb425c7752321c5c9a9abf9f22b47d7134<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42387">issues.joomla.org/tracker/joomla-cms/42387</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0ddd40fb425c7752321c5c9a9abf9f22b47d7134<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42387">issues.joomla.org/tracker/joomla-cms/42387</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42387">issues.joomla.org/tracker/joomla-cms/42387</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
