### PR TITLE
Add test case replicating JFilterInput timeout issue

### PR DESCRIPTION
**Pull request by PhilETaylor**
Closing right away as using Github as a placeholder to share these changes. 

(Replicate #15673 in an isolated test and unit test)

### CODE REVIEW

**Comment by mbabker** [comment]
Reopening, similar to https://github.com/joomla/joomla-cms/pull/15642

**Comment by PhilETaylor** [comment]
ok thanks - its completely basic - not intended to be fit for use at all at the moment, just gives an example of the issue, in its broken state, and a test script for whoever is better at mb* stuff than me

**Comment by photodude** [comment]
For what it's worth, it's stalling out when it runs the `testCleanWithDefaultBlackList` with the data set in your PR.

**Comment by wilsonge** [comment]
@PhilETaylor can you integrate your unit test here into #15966 please

**Comment by PhilETaylor** [comment]
Sorry was delayed by `you know what` in the `other place`

**Comment by rdeutz** [comment]
Doesn't makes sense to have this in unit tests because it brings the test suite into a infinitive loop

**Comment by rdeutz** [comment]
ah this here worked: https://travis-ci.org/photodude/filter/jobs/231328081

**Comment by PhilETaylor** [comment]
Im merging the test with his remote branch now...

**Comment by PhilETaylor** [comment]
ok I failed to merge it to ggppdk:patch-30 :( 

I tested locally and the unit tests run/pass when applied like this ttps://github.com/joomla/joomla-cms/pull/15978

**Pull request closed without merging**
