### PR TITLE
Remove width on toolbar btn-success

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #15578 .

### Summary of Changes
`#toolbar .btn-success` has a set width. This PR removes this and applies it to just the 'New' button.

### Testing Instructions
See #15578. Easiest way to test is to use your browser inspector. Add `btn-success` to any button within the toolbar (eg. `btn btn-small btn-success`), then change the button text and ensure the text does not wrap.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on dc8e3b25c8c0b70df6176afb7cc1142c3f94800e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15760">issues.joomla.org/tracker/joomla-cms/15760</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dc8e3b25c8c0b70df6176afb7cc1142c3f94800e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15760">issues.joomla.org/tracker/joomla-cms/15760</a>.</sub>

**Comment by dgt41** [comment]
@ciar4n why not min-width? (also to keep the current layout)

**Comment by ciar4n** [comment]
@dgt41 To be honest I never thought of it. Instead I set the width to just `#toolbar-new`. 

Your right.. these buttons look strange if the text is short due to the different icon styling. I'll change it.

Quick code review should be enough for RTC.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
