### PR TITLE
[4] typo

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a951ca8b2872584ea86fd7abb0cefd308532809d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34001">issues.joomla.org/tracker/joomla-cms/34001</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on a951ca8b2872584ea86fd7abb0cefd308532809d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34001">issues.joomla.org/tracker/joomla-cms/34001</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34001">issues.joomla.org/tracker/joomla-cms/34001</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
