### PR TITLE
Installation flat repaint

### PR DESCRIPTION
**Pull request by ciar4n**
Application of changes made on #11832 applied to installation.

installation-flat
### Summary of Changes

Flat repaint of UI elements for installation. CSS changes only to template.css. CSS loaded after JS to allow template.css to override chosen.css
### Testing Instructions

Apply patch and delete configuration.php. 
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 687ed66e9d2d9e160280e0135b8ff06df6f4f1e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11917">issues.joomla.org/joomla-cms/11917</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 687ed66e9d2d9e160280e0135b8ff06df6f4f1e8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11917">issues.joomla.org/joomla-cms/11917</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11917">issues.joomla.org/joomla-cms/11917</a>.</sub>

**Comment by brianteeman** [comment]
Setting to 3.7 so that we only get the new install paint when we get the new admin paint

**Comment by rdeutz** [comment]
@ciar4n could you have a look at the conflicts and resolve them, thanks!

**Comment by zero-24** [comment]
@ciar4n please have a look into: https://github.com/ciar4n/joomla-cms/pull/1 for the merge conflicts

**Comment by ciar4n** [comment]
@zero-24 Sighs... same issue as before with no conflicts showing. I'm guessing they are related as I originally applied the install-repaint to the original isis-repaint PR and did not revert/reset them changes correctly when it was decided to create a separate PR for the install repaint. Could I ask you to do the same for the the install-repaint as you did for the isis-repaint (create a new PR). Sorry for been a pain!

**Comment by zero-24** [comment]
New PR: https://github.com/joomla/joomla-cms/pull/12342 Thanks!

**Pull request closed without merging**
