### PR TITLE
[4.0] mod login admin

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the xml description so that it is correct and matches the xml description in the corresponding mod_login.ini

Pull Request for Issue #33534

### CODE REVIEW

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on fde21d3c8704ae83ac9f226c0202d94a33e18a13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33541">issues.joomla.org/tracker/joomla-cms/33541</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on fde21d3c8704ae83ac9f226c0202d94a33e18a13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33541">issues.joomla.org/tracker/joomla-cms/33541</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33541">issues.joomla.org/tracker/joomla-cms/33541</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
