### PR TITLE
[4.0] Improve newsfeed list performance when filtering by tags

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

This ports changes from #19284 to backend newsfeed list view.

### Testing Instructions

Create some newsfeeds with tags.
View newsfeed list in backend.
Filter newsfeeds by single and multiple tags.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8964c14e1f17d02ca6a4e7f4981cde9ec10790fe<br /><br />About performance I can't say anything because my test data set is too small.

But I can confirm filtering by tags in the newsfeeds list works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26495">issues.joomla.org/tracker/joomla-cms/26495</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8964c14e1f17d02ca6a4e7f4981cde9ec10790fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26495">issues.joomla.org/tracker/joomla-cms/26495</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26495">issues.joomla.org/tracker/joomla-cms/26495</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
