### PR TITLE
[4.0] Fix broken tabs in TinyMCE builder plugin

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Fix little regression introduced by #27473

### Testing Instructions
Apply path, and check the tabs between Set 2, Set 1, and Set 0 of TinyMCE builder plugin

### Expected result
They works

### Actual result
They not works

### CODE REVIEW

**Comment by richard67** [comment]
Drone failure seems not to be related to this PR.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c7d0790c19f8fd7777b32b0cb5efb4c87d980216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27560">issues.joomla.org/tracker/joomla-cms/27560</a>.</sub>

**Comment by richard67** [comment]
Thanks @Fedik for the quick and good fix.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c7d0790c19f8fd7777b32b0cb5efb4c87d980216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27560">issues.joomla.org/tracker/joomla-cms/27560</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27560">issues.joomla.org/tracker/joomla-cms/27560</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
