### PR TITLE
[4.0] getReorderConditions() cleanup

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #23021.

### Summary of Changes
Always return an array.
Switch to short array syntax.
Escape column names.
Don't escape integers.
Fix typo in comment.

### Testing Instructions
Code review.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5fa8d110f14285579ceebdacf726f6b866d412d6<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23026">issues.joomla.org/tracker/joomla-cms/23026</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b8742d76660011676b15c3bc0b66c45d57c5d53f<br /><br />Code review.
Drone build failure not related to this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23026">issues.joomla.org/tracker/joomla-cms/23026</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b8742d76660011676b15c3bc0b66c45d57c5d53f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23026">issues.joomla.org/tracker/joomla-cms/23026</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23026">issues.joomla.org/tracker/joomla-cms/23026</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
