### PR TITLE
[4.0][admin menu] - fix wrong group by in preset menu

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # https://github.com/joomla/joomla-cms/pull/25929#issuecomment-522770163.

### Summary of Changes

Fix wrong group by in preset menu joomla.xml

### CODE REVIEW

**Comment by infograf768** [comment]
@alikon 
This PR is OK for multilingual icons. I see no difference with sqli. Does it solve Postgres?

I suggest though, as I also modified the other 2 presets containing that code, to modify also modern.xml and menus.xml

**Comment by infograf768** [comment]
LOL. Does it solve Postgres?

**Comment by alikon** [comment]
no unfortunately.... this is only a macroscopic one

**Comment by infograf768** [comment]
My modification was to not use `l.image` but `l.lang_code` in the `sql_select`.
So, shall it also be modified in the `sql_group` ?

**Comment by alikon** [comment]
yes this is wrong from 3.x https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/presets/joomla.xml#L233

where we use `sql_group="a.id, m.language, l.image"`

but the 

 `a.id` is not in the select list of fields

**Comment by infograf768** [comment]
I mean, shall we not have also
```
sql_group="a.id, a.title, a.menutype, m.language, l.lang_code"
```
instead of
```
sql_group="a.id, a.title, a.menutype, m.language, l.image"
```
as we do not use `l.image` anymore.

**Comment by alikon** [comment]
yes, my bad, you are right

**Comment by infograf768** [comment]
At looking at @Hackwar error here:
https://github.com/joomla/joomla-cms/pull/25929#issuecomment-522770163
and if I understand German OK, It looks like this could be the solution to the Posgres issue...

**Comment by infograf768** [comment]
Please do it for the other presets too and test in Posgres

**Comment by infograf768** [comment]
Now, can you check Postgres?

**Comment by alikon** [comment]
```sql
select a.id,a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:', l.lang_code) END ELSE 'image:mod_languages/icon-16-language.png' END AS icon
from my4_menu_types AS a
left join my4_menu AS m ON m.menutype = a.menutype AND m.home = 1 LEFT JOIN my4_languages AS l ON l.lang_code = m.language
where a.client_id = 0
group by a.id,a.title, a.menutype, m.language, l.lang_code
order by a.id DESC

```

currently i'm only able to test on postgresql console , and the resulting query is working now....
still not able to save an admin menu, but this is just another issue

**Comment by infograf768** [comment]
let's wait to see if drone gets happy ;)

As for admin menu, see my comments on what is not solved in https://github.com/joomla/joomla-cms/pull/25929 Summary of Changes

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 01d1e5825dad3e79dfe529a4cfbb130b6201719e<br /><br />Great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25938">issues.joomla.org/tracker/joomla-cms/25938</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 01d1e5825dad3e79dfe529a4cfbb130b6201719e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25938">issues.joomla.org/tracker/joomla-cms/25938</a>.</sub>

**Comment by infograf768** [comment]
Thanks!

**Pull request merged**
