### PR TITLE
[4.0] Fix tinyMCE buttons

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #14512 .

### Summary of Changes
- Fix the broken tinymce buttons
- remove all instances of `jInsertEditorText`

### Testing Instructions
Follow the issue description

### Documentation Changes Required

`jInsertEditorText` is removed use the API!

There is an error with the media field, but this will be refactored with the new media manager, so...

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Same Issue as #14512:
bildschirmfoto 2017-03-13 um 15 01 55

**Comment by brianteeman** [comment]
Looks like this is changing a lot of vendor supplied files ?

**Comment by dgt41** [comment]
@brianteeman it's ok it's just the uglification that was missing

@franz-wohlkoenig which version of tinyMCE are you using legacy or new?

**Comment by brianteeman** [comment]
@dgt41 we still shouldnt be touching vendor files should we? Changes will bee reverted next time the vendor updates

**Comment by dgt41** [comment]
@brianteeman we are not modifying anything, we are creating minified versions of the scripts that don't have one, e.g. codemirror

**Comment by brianteeman** [comment]
@dgt41 well then this is not the PR to do that in. Please keep PR to a single task

**Comment by dgt41** [comment]
@brianteeman this is automated in j4, is one command `grunt`

**Comment by brianteeman** [comment]
Sorry I missed that you were committing to J4 as you didnt say that anywhere

**Comment by wilsonge** [comment]
Can you fix conflicts dimitris :)

**Comment by dgt41** [comment]
is this repo in sync with current j3 staging?

**Comment by wilsonge** [comment]
As of sunday night it was. there's probably another batch to merge by now

**Review by C-Lodder — APPROVED** [review]

**Pull request merged**
