### PR TITLE
Codestyle indent

### PR DESCRIPTION
**Pull request by brianteeman**
Small change to fix codestyle indent

code review

### CODE REVIEW

**Comment by richard67** [comment]
It seems that the PHPCS check in drone doesn’t like your changes.

**Comment by brianteeman** [comment]
The failure is what caused the problem in the first place - /me confused

**Comment by richard67** [comment]
Me also confused because your code style looks right to me and the other not.

@HLeithner Do you have any idea why PHPCS currently accepts wrong code style in files in the drone checks but complains about this PR here?

**Comment by brianteeman** [comment]
fyi the current lack of indent comes from the psr12 work

**Comment by HLeithner** [comment]
the reason is that phpcs starts to count after `<?php ` so the if is a position 0, I would move the if into the next line.

**Comment by HLeithner** [comment]
> fyi the current lack of indent comes from the psr12 work

for phpcs it's correct for us it's bad...

**Comment by brianteeman** [comment]
thanks for the explanation. Suprised that the same situation doesnt arise with the echo directly afterwards

**Comment by brianteeman** [comment]
I can see there about 15 instances of this. If the new updated change with your recommendation passes then I will make the same change for them all

**Review by chmst — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8cd6df696b3090b3ff53db5bfc97629a40c05470<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38399">issues.joomla.org/tracker/joomla-cms/38399</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8cd6df696b3090b3ff53db5bfc97629a40c05470<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38399">issues.joomla.org/tracker/joomla-cms/38399</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38399">issues.joomla.org/tracker/joomla-cms/38399</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
