### PR TITLE
Solving Notices when looking for updates

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/17452 and https://github.com/joomla/joomla-cms/issues/17462

### Testing Instructions
Install a brand new staging, look at php logs.
also when trying to Find Updates in Extensions=>Manage=>Update
And when displaying Joomla Update component.

Patch and test again.

@svenbluege @AlexRed @richard67

### CODE REVIEW

**Comment by svenbluege** [comment]
Works for me.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fcc178b05c8679838064ee4b39cbbf4553e679e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by richard67** [comment]
@svenbluege Could you mark your test result as success in the issue tracker [https://issues.joomla.org/tracker/joomla-cms/17481](https://issues.joomla.org/tracker/joomla-cms/17481 "https://issues.joomla.org/tracker/joomla-cms/17481") by using the "Test this" button?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by infograf768** [comment]
I did it for him already.

**Comment by svenbluege** [comment]
I have tested this item :white_check_mark: successfully on fcc178b05c8679838064ee4b39cbbf4553e679e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by richard67** [comment]
Great. Travis error seems not related to this PR.

**Comment by infograf768** [comment]
I restarted Travis. Good now. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by mbabker** [comment]
This needs retesting.  There were several other changes in this PR which I have now corrected.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 71334df9c4c7970fc197fd91dc7ac0672d94f810<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 71334df9c4c7970fc197fd91dc7ac0672d94f810<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by infograf768** [comment]
i guess rtc for good now. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17481">issues.joomla.org/tracker/joomla-cms/17481</a>.</sub>

**Comment by zero-24** [comment]
Looks like this now let all drone builds fail see #17526 Thanks.

**Pull request merged**
