### PR TITLE
[4.0] Use whenDefined instead of DOMContentLoaded

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #33063.

### Summary of Changes

The com_media edit should use the `whenDefined`  instead of DOMContentLoaded to solve some race conditions

Ref: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined

### Testing Instructions

Go to Media Manager in Joomla 4 admin

Click to Edit the joomla_black.png file

When on the CROP tab, just keep pressing save, save save save until the 4 fields show NaN

Takes 3-6 clicks.

### Actual result BEFORE applying this Pull Request

NaNs all over the form

### Expected result AFTER applying this Pull Request

Real numbers only

### Documentation Changes Required

@PhilETaylor

### CODE REVIEW

**Comment by PhilETaylor** [comment]
> Reload fast and multiple times the page. You shouldn't see any NaN values

I have seen it on page load (before this PR) but at other times too.

**Comment by dgrammatiko** [comment]
> I have seen it on page load (before this PR) but at other times too.

Ok, what should be the right testing procedure. (I think I could replicate it on fast reloads or saves)

**Comment by PhilETaylor** [comment]
try this one https://github.com/joomla/joomla-cms/issues/33063

**Comment by ceford** [comment]
I may be doing it wrong (again). I applied the patch, ran npm ci (even jinstall) and I still get NaN after some clicks. Also, if NaN is actually saved into joomla_black.png it kills the Media manager (blue line goes slowly across the top but nothing happens - no folders or images to choose from). I had to delete that image (only 3 bytes) and copy in one from another install to restore functionality. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33192">issues.joomla.org/tracker/joomla-cms/33192</a>.</sub>

**Comment by dgrammatiko** [comment]
How did you actually apply the patch? Git or patch tester? I think patch tester is not safe for the build folder (but I maybe wrong I never used it)

**Comment by dgrammatiko** [comment]
@PhilETaylor can I have a test here? Thanks

**Comment by PhilETaylor** [comment]
Sorry first time seeing this PR.

**Comment by PhilETaylor** [comment]
```
rm -rf administrator/templates/atum/css; rm -rf templates/cassiopeia/css; rm -rf administrator/templates/system/css; rm -rf templates/system/css; rm -rf media/; rm -rf node_modules/; rm -rf libraries/vendor/;rm -f administrator/cache/autoload_psr4.php;rm -rf installation/template/css; composer install; npm ci
```

and then edited an image and on first page load I get a JS error

Screenshot 2021-05-08 at 18 19 58

**Comment by PhilETaylor** [comment]
Tags also are not preserving state on page reload (unrelated to this PR probably, but when refreshing the page, the first tab is always selected and not the last clicked tab)

**Comment by PhilETaylor** [comment]
> Also, if NaN is actually saved into joomla_black.png it kills the Media manager (blue line goes slowly across the top but nothing happens

I tried to fix that and was shot down by the maintainers. https://github.com/joomla/joomla-cms/pull/33141

**Comment by PhilETaylor** [comment]
Also probably unrelated to this pr. When you click SAVE you get no feedback (the ajax call is ok, but there is no feedback so you dont know if it did anything or not.

**Comment by dgrammatiko** [comment]
@PhilETaylor @ceford it should be ok now, it seems that I can't type a word without a typo (the attribute is `nomodule` not `nomodules`)...

**Comment by dgrammatiko** [comment]
> Also probably unrelated to this pr. When you click SAVE you get no feedback (the ajax call is ok, but there is no feedback so you dont know if it did anything or not.

There is PR that really implemented all those todos I left as a placeholder, someone should merge that one: https://github.com/joomla/joomla-cms/pull/30511

**Comment by PhilETaylor** [comment]
JS console error gone. 

looks totally different in the new template, but still get NaN on the edit page if I reload on the 6th. 7th, 13th and 20th of 23 refreshes...
Screenshot 2021-05-08 at 18 37 37

**Comment by dgrammatiko** [comment]
I just dropped the SPA approach here and added a few more fuses, so hopefully this is ok now

**Comment by PhilETaylor** [comment]
Sorry - no :-( 


https://user-images.githubusercontent.com/400092/117549777-30e47a80-b034-11eb-9cd0-06227b65ea2a.mp4

**Comment by dgrammatiko** [comment]
Ehm how did you manage to click so fast on the save? The button gets disabled when pressed and enabled at the finish of the process...

**Comment by PhilETaylor** [comment]
CMD+R (browser refresh)

**Comment by ceford** [comment]
I have tested this item :red_circle: unsuccessfully on 94ddb7097c7e82b970375b9c1b889ceb99d7be98<br /><br />After 6 quick clicks the four fields are empty and I get this:

> Notice: exif_imagetype(): Error reading from /Users/ceford/Sites/j4test/images/joomla_black.png! in /Users/ceford/Sites/j4test/libraries/src/Helper/MediaHelper.php on line 74

>Notice: getimagesize(): Error reading from /Users/ceford/Sites/j4test/images/joomla_black.png! in /Users/ceford/Sites/j4test/libraries/src/Image/Image.php on line 185

The joomla-black.png file is only 3 bytes and neither Reset nor Close work. Going back to the Media menu gives me a dead Media screen until I replace that bad file with a good copy. 

Still needs some work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33192">issues.joomla.org/tracker/joomla-cms/33192</a>.</sub>

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/34885

**Pull request closed without merging**
