### PR TITLE
Important but easy improvements to the code of the article view (1)

### PR DESCRIPTION
**Pull request by impressionestudio**
These changes are part of the issue #35342 (https://github.com/joomla/joomla-cms/issues/35342).
Mainly they are changes to the names of the classes using the BEM nomenclature.

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont see how changing the class names achieves what you highlight in the original issue

**Comment by simbus82** [comment]
@impressionestudio, can you "merge" all PR in only one so we can test it? And please rename the classes that you have changed: no underscore please, and not change the actual logic of css classes.

**Comment by Fedik** [comment]
Changing class names does not makes sense, you only make hard time for existing templates, and for an overrides

**Comment by impressionestudio** [comment]
> I dont see how changing the class names achieves what you highlight in the original issue

Because it is the first time I use GitHub, I thought to do it in two parts. After this first part with the class name changes, I will do the code changes, which is the second and last part of this issue.

**Comment by impressionestudio** [comment]
> Changing class names does not makes sense, you only make hard time for existing templates, and for an overrides

The class names are very inconsistent. So many things are changed in Joomla 4 and the problem is to change the class names? Now, along with all the other changes, is time to make these class names better because we use them all the time. Otherwise, we will end up to have Joomla 5 using some strange class names from Joomla 1.0. :)

**Comment by Fedik** [comment]
> After this first part with the class name changes, I will do the code changes

If it all for one issue, then better do it in one run. So people can see what is going one, and this way it is more easy to make decision.

> We have changed so many things in Joomla 4 and the problem is to change the class names?

I have looked your changes and to me it is a change for the sake of change (maybe only 1-2 places I would half-agree).
Joomla 4 already out, and now you suggest to ruin someone's template, because you do not like class names? ;) 

Also please check my comment in original issue https://github.com/joomla/joomla-cms/issues/35342#issuecomment-940405118

**Comment by impressionestudio** [comment]
> Joomla 4 already out, and now you suggest to ruin someone's template, because you do not like class names? ;)

I believe that it is still early, or not too late for something so important as I see it. I had mentioned this issue in forums (outside GitHub) long before Joomla 4 was released, and I had a few hopes that the developers of Joomla 4 will take in mind these changes. After Joomla 4 was released, I saw that nothing changed and thought to drop it. But later, as I was checking Joomla 4 and seeing so many improvements, I wasn't feeling right to accept this limitation. Because, despite the class name changes that are only for consistency reasons and having pretty CSS code, the code changes will expand the possibilities of the template design.

**Comment by simbus82** [comment]
> > Changing class names does not makes sense, you only make hard time for existing templates, and for an overrides
> 
> The class names are very inconsistent. So many things are changed in Joomla 4 and the problem is to change the class names? Now, along with all the other changes, is time to make these class names better because we use them all the time. Otherwise, we will end up to have Joomla 5 using some strange class names from Joomla 1.0. :)

I can understand this is your first time using github, but if you had used that "naming" for CSS classes in my agency, I would have had to fire you. (obviously I'm exaggerating).
**CSS classes are not written like this, it is wrong, it does not matter Joomla, it is really wrong at the level of basic web development.**
There is no point in hard coding the "cascade" of the class itself. CSS is made to handle the cascade!
image

**Comment by impressionestudio** [comment]
> > > Changing class names does not makes sense, you only make hard time for existing templates, and for an overrides
> > 
> > 
> > The class names are very inconsistent. So many things are changed in Joomla 4 and the problem is to change the class names? Now, along with all the other changes, is time to make these class names better because we use them all the time. Otherwise, we will end up to have Joomla 5 using some strange class names from Joomla 1.0. :)
> 
> I can understand this is your first time using github, but if you had used that "naming" for CSS classes in my agency, I would have had to fire you. (obviously I'm exaggerating). **CSS classes are not written like this, it is wrong, it does not matter Joomla, it is really wrong at the level of basic web development.** There is no point in hard coding the "cascade" of the class itself. CSS is made to handle the cascade! image

The new class names that I suggest are not my original choice. I had to use them because some guys instructed me to follow the BEM naming rules. 

My original class names were single/simple words like "info" and "published" and a few times something more complex like "info-published". If you check my original class names in https://github.com/joomla/joomla-cms/issues/35342 you will see how simple they were.

@Fedik suggested to follow the RFC #15279, so I will read the new naming rules and possibly the class names will be simpler and shorter.

**Comment by brianteeman** [comment]
@simbus82 Glad I dont work for you

**Comment by simbus82** [comment]
> @simbus82 Glad I dont work for you

You can eat quietly. Changing the logic of the classes in this way, without considering everything around it, is not a good practice.
Then we can talk about BEM and the fact that I don't like it for a frontend in a CMS like Joomla. Too verbose and unreadable, i prefer the deep nesting. But I'm old for these things now.

> The new class names that I suggest are not my original choice. I had to use them because some guys instructed me to follow the BEM naming rules.
> 
> My original class names were single/simple words like "info" and "published" and a few times something more complex like "info-published". If you check my original class names in #35342 you will see how simple they were.

@impressionestudio I really liked the august proposal (you can see my thumb up) about the html structure, only not liked the change in the logic of the CSS naming that took place now.

**Comment by impressionestudio** [comment]
@simbus82 I also don't like BEM, but I am willing to do some compromises in order others to accept the general idea.

**Pull request closed without merging**
