### PR TITLE
Use icon exit  for close buttons

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #40112 .

### Summary of Changes
Replace the "close" icon  ( X ) by an exit icon. The exit icon is used in many apps. 

### Testing Instructions
All toobars have the exit-icon on the close button.

### Actual result BEFORE applying this Pull Request
see #40112 

### Expected result AFTER applying this Pull Request

grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I think that the exit icon has a meaning: leave the screen and do nothing. The "x" has the meaning  "delete" but dos not say "leave".

**Comment by brianteeman** [comment]
My apologies I didnt look properly at the pr only at the reporting issue.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 11e73c71ed01555f928e19ab0fc3d0ee95e56224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 11e73c71ed01555f928e19ab0fc3d0ee95e56224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by Fedik** [comment]
r2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by chmst** [comment]
> However I was thinking that this icon is often used to portray an 'exit' from an application or a logout. Hope this won't confuse some users.

Hopefully ... in this case it is an exit from a screen and together with the text it should be clear. Maybe we should use the close button without icon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 11e73c71ed01555f928e19ab0fc3d0ee95e56224<br /><br />Sorry - reverting my successful test to unsuccessful as I didnt spot that the text didnt change as shown in he screenhot and remains as cancel<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 11e73c71ed01555f928e19ab0fc3d0ee95e56224<br /><br />Sorry - reverting my successful test to unsuccessful as I didnt spot that the text didnt change as shown in he screenhot and remains as cancel<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by Fedik** [comment]
back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by drmenzelit** [comment]
> the text didnt change as shown in he screenhot and remains as cancel

But "close" would be wrong on this place, when one start creating an article and then decide to not save it, one is cancelling the action not closing it...

**Comment by brianteeman** [comment]
> > the text didnt change as shown in he screenhot and remains as cancel
> 
> But "close" would be wrong on this place, when one start creating an article and then decide to not save it, one is cancelling the action not closing it...

I agree but the test instructions show it as changed to Close in the expected behaviour

**Comment by chmst** [comment]
Sorry, was absent. 
The testing instructions said "all toolbars" have the exit icon. 
I have chosen one Toolbar as an example so that testers see an exit icon. 
We have  buttons with text 'close" and with text "cancel". I am not sure if this quite consistent, but this is not in scope of this PR. They all had the same "x" icon, now they all have the exit-icon.

**Comment by brianteeman** [comment]
but your screenshot shows "articles new" with the text "close"
and my screenshot shows "articles new" with the text "cancel"

/me confused

**Comment by chmst** [comment]
My apologies. I was playing with different texts on the buttons and got the wrong screenshot. This is the correct oen for article edit 

grafik

On categories it is close 

grafik

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 11e73c71ed01555f928e19ab0fc3d0ee95e56224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40167">issues.joomla.org/tracker/joomla-cms/40167</a>.</sub>

**Comment by obuisard** [comment]
Thanks Christiane @chmst !

**Comment by laoneo** [comment]
If yes, then such a change should never be merged in a patch release.

**Comment by brianteeman** [comment]
Sorry @laoneo you are wrong. (If the system tests are failing then it is because the system test is wrong. 

When you create a **new** article then the text has always been Cancel
When you edit an **existing** article then the text has always been Close

The only thing the pr did was to change the icon that went with the text.

**Comment by laoneo** [comment]
When you click the "New" button on the 4.3-dev branch Then you will see that Close is shown and not cancel. This is different than on 4.3.1.

**Comment by brianteeman** [comment]
## Dev
image

## 4.3.1
image

**Comment by ReLater** [comment]
Will this be ported to J5? Because the question came up in german Joomla forum https://forum.joomla.de/thread/18151-datei-l%C3%B6schen-datei-schliessen/?postID=147003#post147003

**Pull request merged**
