### PR TITLE
Less is More

### PR DESCRIPTION
**Pull request by brianteeman**
> **Avoid over-communication**
> Be explicit wherever necessary but don't explain the obvious. On the web scanning is the norm and too much text weakens the effectiveness of the message - it does not enhance it.
#### Summary of Changes

There really is no point writing in depth instructions in a tooltip - especially if the information is permanently displayed on the screen.
#### Before

before
#### After

after

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on d5830097dc0c3e82a83cf23b0dcc9a727f2ccda9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11249">issues.joomla.org/joomla-cms/11249</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d5830097dc0c3e82a83cf23b0dcc9a727f2ccda9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11249">issues.joomla.org/joomla-cms/11249</a>.</sub>

**Comment by brianteeman** [comment]
RTC.thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11249">issues.joomla.org/joomla-cms/11249</a>.</sub>

**Comment by odbhaskaran** [comment]
I tested this successfully after removing extra texts

**Pull request merged**
