### PR TITLE
[4.0] http status codes

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the list of status codes as a few were missing. Ref https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

Code review only

### CODE REVIEW

**Comment by alikon** [comment]
may i suggest you to add 599 
https://http.cat/599
image
more seriously https://httpstatuses.com/599

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e81f5803c33754bc8a3108148acbf3649e6239ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by brianteeman** [comment]
@alikon I have only included official status codes

**Comment by alikon** [comment]
sure don't mind,
i've seen it one time in my life much time ago, and i've laughed a lot

**Comment by ChristineWk** [comment]
Sorry: Wanted to check Code review, but "Apply Patch" shows me: 
The file marked for modification does not exist: administrator/components/com_redirect/src/Field/RedirectField.php
@alikon error 599 is nice :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by brianteeman** [comment]
@ChristineWk I think your branch is not up to date. With #27687 the files would have been moved

**Comment by ChristineWk** [comment]
@brianteeman Thanks for your info. Will read and check above.
My "branch" is a fully nightly from 5thfeb2020.
So, I have to delete site and install again completely new installation (?)... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by brianteeman** [comment]
@ChristineWk I would recommend that for you as 2 days ago #27687 moved a lot of files

**Comment by ChristineWk** [comment]
Hmmm. Will check ...... Thank you. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e81f5803c33754bc8a3108148acbf3649e6239ec<br /><br />... after installation completely fully branch of today ... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27931">issues.joomla.org/tracker/joomla-cms/27931</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
