### PR TITLE
Let's fix the Update from 2.5 to 3.5 with a method both supports

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for follow up Issue #9230.
#### Summary of Changes

Now we use a function that also support Updating from 2.5.x to 3.5
#### Testing Instructions
- Install 2.5.28 (https://github.com/joomla/joomla-cms/releases/download/2.5.28/Joomla_2.5.28-Stable-Full_Package.zip)
- Try to update and install to 3.5beta2 with this package: http://www.jah-tz.de/downloads/download.php?file=Joomla_3.5.0-beta2-fixed.zip&folder=media/joomla/
- you got logged out as you have a old session
- Login again and make sure you have a beta2
#### Expected result

Update works (without any error message) but you got logged out
#### Notes

Please note that the only change included in my package is the one from this PR and #9230 . So you might encounter other issues which were already fixed since the release of beta2.

@wilsonge @tecpromotion @Harmageddon can you check if that works for you too? Thanks.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 0abbc484c3a94a6488c7d6852b94b6dd974e4abf<br /><br />Tested a 2.5.28 to your custom 3.5.0-beta2 upgrade with success.
Yesterday got a fatal error, today has ok, so success.

Used Extensions -> Install -> Upload method.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9240">issues.joomla.org/joomla-cms/9240</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 0abbc484c3a94a6488c7d6852b94b6dd974e4abf<br /><br />Tested only with mariadb (mysql) and works as before, so if it works in postrgresl too ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9240">issues.joomla.org/joomla-cms/9240</a>.</sub>

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on 0abbc484c3a94a6488c7d6852b94b6dd974e4abf<br /><br />Sorry for not testing 2.5 yesterday! Thank you @zero-24! The update now works fine from 2.5, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9240">issues.joomla.org/joomla-cms/9240</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0abbc484c3a94a6488c7d6852b94b6dd974e4abf<br /><br />I have tested this with success.

For the test I used my own update zip packages based on latest staging plus my PR #9221 

- 1st container without this patch here

- 2nd container with this patch here

Result:

Test 1: Update the 2.5.28 with container 1 using upload and install package method, ended with lots of PHP error messages "Error on updating manifest cache ...". Then could login and saw success message for package installation and the statistics plugin question box, i.e. all was normal then, and I could do the successful database fix as made possible with my PR I mentioned.

Test 2: Same with container 2. Result: No PHP errors :+1:  , cleanly logged out, and after login again all normal, i.e. success message, statistics plugin message displayed, database fix worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9240">issues.joomla.org/joomla-cms/9240</a>.</sub>

**Comment by richard67** [comment]
P.S.: I also tested with same container 2 from my previous test if updating a 3.4.8 still works and can confirm this PR here braks nothing, i.e. if this PR here and mine are merged, all problems related to updates from 2.5.28 on to 3.5 are solved, and so Beta 3 can be shipped :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9240">issues.joomla.org/joomla-cms/9240</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the testers! And @wilsonge for the check and merge :+1:

**Pull request merged**
