### PR TITLE
[4.0] Fix title and alias label widths

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #16309 

### Summary of Changes

Fix the width the `title` and `alias` labels on edit views

### Result

screeny

### CODE REVIEW

**Comment by brianteeman** [comment]
it is fine on the article page now but not good on others such as contacts and menus
screenshotr16-02-32
screenshotr16-03-02
screenshotr16-04-05

**Comment by C-Lodder** [comment]
That's cause it's using `width: auto` rather than a set width. Only way around this is to use an inline form which is not a good approach at all, or stick with the old (set width) method

**Comment by brianteeman** [comment]
its also caused because alias has been moved to the new line

**Comment by C-Lodder** [comment]
Moving to a new line was to improve UX. Inline forms are bad practice.

I could set the min-width to 100px instead of 50px.

**Comment by brianteeman** [comment]
Is it really an online form?

**Comment by brianteeman** [comment]
oops auto correct - that should have course been inline not online

**Comment by C-Lodder** [comment]
Yes, it's still inline

**Comment by brianteeman** [comment]
Is it really bad UX when you only have two fields - i am not convinced

**Comment by C-Lodder** [comment]
If you had a blank page with just 2 field, then probably not. But seeing as this is a compact admin interface, then yes.

**Comment by brianteeman** [comment]
We might have to agree to disagree on that

**Comment by Bakual** [comment]
Serious question: What is the reason (explanation) why inline forms are bad practice / UX?
And do those reasons really apply to that subset of our form?
To me it sounds more like a generalised statement (and generalised statements are usually wrong).

**Comment by C-Lodder** [comment]
@Bakual - cause stacked forms are easier to scan that inline ones. Even more so in this case as the Title input is much longer than a normal input.

**Comment by C-Lodder** [comment]
closing, someone else can do this

**Pull request closed without merging**
