### PR TITLE
[4.0] Remove email-confirm from registration.

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR removes the email confirmation field from the registration form, as discussed at the sprint.

### Testing Instructions

- Ensure the registration form works as expected.

@wilsonge @laoneo could you just check to see if I've missed anything out?

### CODE REVIEW

**Comment by brianteeman** [comment]
woohoo - finally - can we remove the email validation script as well?

**Comment by wilsonge** [comment]
What email validation script?

**Comment by brianteeman** [comment]
sorry not a script but JFormRuleEmail
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/rule/email.php#L19

**Comment by C-Lodder** [comment]
Are we sure 3pd aren't using this for things like e-commerce shopping forms etc?

**Comment by brianteeman** [comment]
as long as we are not using it :)

**Comment by wilsonge** [comment]
We need to keep the `JFormRuleEmail` - if we aren't using it we should be in the majority of cases. that's our server side sanity checker right there....

**Pull request merged**
