### PR TITLE
[4.0] Add folder forms to the manifest file.

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Add folder forms to the manifest files of workflow plugins.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 78791fa19f46fb79df131ecb8d44760f3b37cc21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29625">issues.joomla.org/tracker/joomla-cms/29625</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 78791fa19f46fb79df131ecb8d44760f3b37cc21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29625">issues.joomla.org/tracker/joomla-cms/29625</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29625">issues.joomla.org/tracker/joomla-cms/29625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
