### PR TITLE
[HTTPS] Deprecating SSL text in language vars

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9416.
#### Summary of Changes

Changes the text that reference SSL. Use HTTPS instead.
Soem changes in the text to to make it more simple.
#### Testing Instructions

Check code difference.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5a7b96bafdc863bf0aac518565281bde3b00fa7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9588">issues.joomla.org/joomla-cms/9588</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5a7b96bafdc863bf0aac518565281bde3b00fa7f<br /><br />:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9588">issues.joomla.org/joomla-cms/9588</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9588">issues.joomla.org/joomla-cms/9588</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman why do you add it to the 3.5.2 milestone and not to 3.5.1?

**Comment by brianteeman** [comment]
because I have been informed by @wilsonge that the plan is to have a 3.5.1
release fairly quickly so anything with a language change needs to wait as
there wont be time for a language freeze for TT

**Comment by zero-24** [comment]
Ah ok. That explains it. Thanks :)

**Comment by brianteeman** [comment]
It might change if they decide the next release wont be as quick in which
case those items with a 3.5.2 milestone will get merged

**Pull request merged**
