### PR TITLE
Fix disabled select background

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #40349 .

### Summary of Changes

Remove the dropdown icon from the disabled select elements

### Testing Instructions

Follow the issue

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@heelc29 here you go

### CODE REVIEW

**Comment by brianteeman** [comment]
also see https://github.com/joomla/joomla-cms/issues/40030

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on e2ea7a9223273e813ed10c05e4353dd24856fc77<br /><br />You're fast. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40350">issues.joomla.org/tracker/joomla-cms/40350</a>.</sub>

**Comment by heelc29** [comment]
> also see #40030

I haven't seen 😅

**Comment by dgrammatiko** [comment]
@brianteeman the PR also fixes https://github.com/joomla/joomla-cms/issues/40030

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e2ea7a9223273e813ed10c05e4353dd24856fc77<br /><br />Fixes #40349 and #40030 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40350">issues.joomla.org/tracker/joomla-cms/40350</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40350">issues.joomla.org/tracker/joomla-cms/40350</a>.</sub>

**Comment by obuisard** [comment]
> @obuisard should this be considered a RB? It's due to upstream changes in the BS5.2.3

I do not consider it a release blocker, but since it is an issue due to the Bootstrap update, I will merge it.

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for the PR

**Comment by brianteeman** [comment]
Shouldn't a similar PR have been made for cassiopeia?

**Comment by dgrammatiko** [comment]
> Shouldn't a similar PR have been made for cassiopeia?

I don't see any override for the disabled sudo there:
https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_custom-forms.scss

but I guess someone needs to check if the `:disable` styling is correct

**Comment by obuisard** [comment]
This is how I see disabled fields in the frontend:

image

The list field is not selectable but looks the same as if options were selectable, so we could improve on that.

**Pull request merged**
