### PR TITLE
[4.1] [GSoC 21] Media Manager - Add a player plugin to better preview audio and video files

### PR DESCRIPTION
**Pull request by eyvazahmadzada**
Pull Request for the "Media Type Improvements" task of the final evaluation period of [Media Manager](https://github.com/joomla-projects/gsoc21_media-manager).

### Summary of Changes

- Add and improve video/audio preview by using the MediaElement player plugin.

### Testing Instructions

1. **Upload files.** Upload video or audio files in Media Manager.

image

2. **Preview.** Preview them by either double-clicking on them or using the "Preview Item" button. Video files:

image

Audio files:

image

### Documentation Changes Required
I don't think so.

Special thanks to my mentors (@sebenns, @fancyFranci, @GeraintEdwards, @shivamdiehard, Chris Keen) and @bembelimen for assisting me with the project.

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0cf67aaf33c0859e4e1634084760f979839110f7<br /><br />Really nice UX improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35177">issues.joomla.org/tracker/joomla-cms/35177</a>.</sub>

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 0cf67aaf33c0859e4e1634084760f979839110f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35177">issues.joomla.org/tracker/joomla-cms/35177</a>.</sub>

**Comment by dgrammatiko** [comment]
@eyvazahmadzada what is the benefit here by introducing a userland JS media player instead of using the Browser provided one (0kb)?

**Comment by brianteeman** [comment]
Having just demoed that we already can do this I was thinking the same

**Comment by dgrammatiko** [comment]
> Having just demoed that we already can do this I was thinking the same

Also if it's just about the looks: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Video_player_styling_basics

**Comment by eyvazahmadzada** [comment]
Thank you for your comments, @brianteeman, @dgrammatiko. To be honest, most of the tasks about media types in media manager that I had set at the beginning and done during the program have already been done and merged during the period when I was working on them. Back then, the video player was a bit messy so I thought it would be better to use a plugin to make it look better, but now I will try to do the same without using a plugin.

**Comment by bembelimen** [comment]
If I understand it right, this PR is now obsolete, as we're covered by the default browser player.

Thank you @eyvazahmadzada for your contribution. If I'm wrong, please ping me to reopen.

**Pull request closed without merging**
