### PR TITLE
[4.0] Finder pagination options

### PR DESCRIPTION
**Pull request by brianteeman**
This PR adds support for the two pagination options

PR for #31316 

image

image

### CODE REVIEW

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 651f1c9bf7a89e80f10736da1eccb0ca55e12a6a<br /><br />Determined testing requirements from reading through #31316. Change tested successfully.

### Testing Instructions
Create a Smart Search Menu item, with a low limit (5) on the number of results to show on the page to trigger the pagination when it's turned on.

### Actual result BEFORE applying this Pull Request
Pagination displays when setting is set to Hide for either the Pagination and Pagination Summary options are set to Hide

### Actual result AFTER applying this Pull Request
When Pagination and/or Pagination Summary options are set to various options, particularly Hide, the pagination options will adhere to what the settings is configured to do.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 651f1c9bf7a89e80f10736da1eccb0ca55e12a6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by sakiss** [comment]
I have tested this item :white_check_mark: successfully on 651f1c9bf7a89e80f10736da1eccb0ca55e12a6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by sakiss** [comment]
I have tested this item :white_check_mark: successfully on 651f1c9bf7a89e80f10736da1eccb0ca55e12a6a<br /><br />Fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31390">issues.joomla.org/tracker/joomla-cms/31390</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
