### PR TITLE
[5.0] Error page languages

### PR DESCRIPTION
**Pull request by brianteeman**
Move the comments to their own line

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by HLeithner** [comment]
as already written in the other pr, this doesn't work for crowdin.

**Comment by richard67** [comment]
> as already written in the other pr, this doesn't work for crowdin.

That's right, but we have such comment lines already elsewhere, and it solves the issue with the JS ini file parser.

**Comment by dgrammatiko** [comment]
There's another way https://github.com/joomla/joomla-cms/pulls that doesn't require moving the comments around

@HLeithner

**Comment by brianteeman** [comment]
I dont care how its done as long as the translators get the information and localise that string instead of translating it

**Comment by HLeithner** [comment]
Closing this, if the other pr gets a test I will merge it.

**Pull request closed without merging**
