### PR TITLE
[4.0] Tinymce plugin options bootstrap 5

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #32152 .

### Summary of Changes

Fixing the tabs in the tinyMCE builder

### Testing Instructions

Check the issue above

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 857c671e3eb8e7f529498fc24c726a25158a5cdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32153">issues.joomla.org/tracker/joomla-cms/32153</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 857c671e3eb8e7f529498fc24c726a25158a5cdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32153">issues.joomla.org/tracker/joomla-cms/32153</a>.</sub>

**Comment by infograf768** [comment]
Tabs now working but we still have a console error here:
```
Uncaught TypeError: tabLink is null
    showTab http://localhost:8888/newfolder/joomla40/media/vendor/joomla-custom-elements/js/joomla-tab.js:287
    connectedCallback http://localhost:8888/newfolder/joomla40/media/vendor/joomla-custom-elements/js/joomla-tab.js:165
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/joomla-custom-elements/js/joomla-tab.js:2
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/joomla-custom-elements/js/joomla-tab.js:404
joomla-tab.js:287:7
```

**Comment by dgrammatiko** [comment]
Clean your local storage and make sure the url doesn't have a #something

This is related to joomla's tabs not bs

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 857c671e3eb8e7f529498fc24c726a25158a5cdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32153">issues.joomla.org/tracker/joomla-cms/32153</a>.</sub>

**Comment by infograf768** [comment]
rtc. thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32153">issues.joomla.org/tracker/joomla-cms/32153</a>.</sub>

**Comment by infograf768** [comment]
indeed, was remaining a # ;)

**Pull request merged**
