### PR TITLE
[4.0] Global Config Permissions inconsistent widths

### PR DESCRIPTION
**Pull request by amitranjan2**
Pull Request for Issue #23627 .

### Summary of Changes
 class="row" changed to 
					 class="col-md-12"
### Testing Instructions

Go to the "Permissions" tab in Global Configuration

### Expected result 
It should be aligned  

### Actual Result 
 the containers aren't aligned

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by amitranjan2** [comment]
@C-Lodder please review this

**Comment by C-Lodder** [comment]
Yup, this fixes the inconsistency with the `row` class

**Comment by amitranjan2** [comment]
@C-Lodder could you please help me? which container need to be 100%

**Comment by C-Lodder** [comment]
Actually it's due to the `row` class on the `<joomla-field-permissions>` custom element (no idea why it's there).

Then you'll need to replace your current coding changes with:

```
<div class="row">
    <div class="col-md-12">
    </div>
</div>
```

**Comment by ReLater** [comment]
EDIT: Aaah, sorry! I skipped https://github.com/joomla/joomla-cms/pull/23687#issuecomment-457920092  

### Already said above:
Is there a reason why you don't remove `row` class here: https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/rules.php#L78

plus
```
<div id="page-permissions" class="tab-pane">
  <div class="row">
    <div class="col-md-12">
....
```
in default.php.

Thus you could make the code inside default.php more consistent.

I've tested my proposal a bit in the back-end and I think the `row` class for `joomla-field-permissions` is wrong(?).

**Comment by C-Lodder** [comment]
@ReLater Yes, the `row` class on the custom element is incorrect. It shouldn't be there at all.

**Comment by C-Lodder** [comment]
@amitranjan2 Your latest commit is incorrect.

**Comment by amitranjan2** [comment]
@C-Lodder  was previous one right?
I'm working on this issue for a quite long time, still not getting the 100% width

**Comment by C-Lodder** [comment]
@amitranjan2 Re-add this: `<joomla-field-permissions class="row mb-2" data-uri="<?php echo $ajaxUri; ?>">`

but remove `row` from it.

Then for the width, this will need to be fixed in the SCSS file.

**Comment by Quy** [comment]
@amitranjan2 You did not do the changes as proposed by C-Lodder.

**Comment by amitranjan2** [comment]
@Quy I revert the changes according to @C-Lodder

**Comment by amitranjan2** [comment]
@C-Lodder is `scss` file changes already done in your PR ? #23729

**Comment by C-Lodder** [comment]
@amitranjan2 No, my PR was purely for code improvements

**Comment by amitranjan2** [comment]
@C-Lodder I made changes in joomla-tab.css and this is the result 
screenshot from 2019-02-03 07-29-50

https://github.com/joomla-projects/custom-elements/blob/a0cb122751530fb093b74319899fef5fe377a808/src/scss/tab/tab.scss#L69

Here added `width:100%`

**Comment by amitranjan2** [comment]
Is this correct ?

**Comment by C-Lodder** [comment]
Good start. It should align with the `Permissions` blue blox. And I think the tabs on ther left need sorting out. If I righgtly remember, they 30% width which may look somewhat odd, higher resolution monitors

**Comment by amitranjan2** [comment]
@C-Lodder  I made changes in joomla-tab.css and this is the result
here I changed  to min-width:15% 
https://github.com/joomla-projects/custom-elements/blob/a0cb122751530fb093b74319899fef5fe377a808/src/scss/tab/tab.scss#L78
image

is this all correct now?
alignment and 100% width both

**Comment by amitranjan2** [comment]
@C-Lodder is anything left to be fixed?
please tell me.
in my opinion, your both issue(alignment and 100% width)  is working fine now.
please review

**Comment by C-Lodder** [comment]
Code changes seem fine

**Comment by amitranjan2** [comment]
@C-Lodder  So, have I to create another PR for that changes of width in Joomla project/Custom elements?

**Comment by C-Lodder** [comment]
You can incorporate them here or do a separate one. Your choice

**Comment by amitranjan2** [comment]
@C-Lodder Please close the Issue #23627 
 as now both alignment and width 100% is working  fine

**Comment by Quy** [comment]
This is no longer an issue with the new backend template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23687">issues.joomla.org/tracker/joomla-cms/23687</a>.</sub>

**Pull request closed without merging**
