### PR TITLE
Fix Yubikey Template Override File Path

### PR DESCRIPTION
**Pull request by AbhishekDas**
Template override file path is wrongly checked and needs to be corrected.

### CODE REVIEW

**Comment by brianteeman** [comment]
@nikosdion care to take a look at this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5612">issues.joomla.org/joomla-cms/5612</a>.</sub>

**Comment by nikosdion** [comment]
+1 from me and I recommend setting RTC. I really did forget the slash in that code. Oops!

**Comment by wilsonge** [comment]
Merged both of these PR's. Thanks!

**Comment by AbhishekDas** [comment]
Thanks.

**Pull request merged**
