### PR TITLE
[Re] [#18721] - [4.0] Editing module on frontend causes 500 on ordering ajax

### PR DESCRIPTION
**Pull request by amone4**
Pull Request for Issue #18721
(The branch for #20041 was mistakenly deleted)

### Summary of Changes

The value of task was wrongly identified. Also, the client was changed from site to administrator, to invoke the controller present on the administrator's side

### Testing Instructions

Edit a module on the frontend

### Expected result

No errors with a select field in front of 'ordering' option

### Actual result

Same as expected

### Documentation Changes Required

None

### CODE REVIEW

**Comment by laoneo** [comment]
I get the following error when I want to edit a module:
image

**Comment by amone4** [comment]
@laoneo Sorry, I was a bit busy for the past few days. As for the issue, I wasn't really able it.
demo

Could you be more specific? What exactly triggered the error?

**Comment by laoneo** [comment]
Was my bad, had still the not namespaced empty folders in the filesystem.

**Comment by brianteeman** [comment]
@laoneo this looks like it has been merged without any successful tests??

**Comment by zero-24** [comment]
@brianteeman I have been told Joomla 4 don't require testing on the same question. I don't agree on that but well if that is the direction that project is going.

**Comment by brianteeman** [comment]
that's just crazy and plain wrong.

**Comment by brianteeman** [comment]
@wilsonge is that really the policy now?

**Comment by laoneo** [comment]
Just for the record, I'v tested it (as I do with every pr I merge, even the vendor dir removal). Joomla 4 is in development mode (we produce alphas). So it is important to get stuff done. Things can be broken, I do not say they should! If we start forcing the two tests policy for Joomla 4 alpha then it will take years to get to the stable release. Just to be clear here, I do not say we should not test and every test is welcome and helps the project.

When we enter the beta phase then it will be clear to merge pr's like this one with two tests only as we do on staging, when we stabilize things. But for now when we try out new ways and do architecture changes it just makes no sense to be so restrictive.

Just to give you guys some examples, Custom Fields, Namespacing, the New Media Manager, the Back End Template are all done without the two test policy.

I see the phases that way:

**ALPHA**
Here we produce new features and do architecture decissions. It can be seen as an internal release phase. I know it is probably difficult to apply for an open source project.

**BETA**
No new features, testing phase, finishing things which we created the architecture/base for during alpha.

**RC**
Testing, testing, testing and stabilizing.

This is a common development strategy with alphas, betas and release candidates. It's just a normal development process, nothing else. If you want to keep the 4.0 development branch in a state where you basically can produce at any time a stable release, then I wish you guys good luck bringing out Joomla 4 in the next years.

I see there is a need to have that discussion, so better to do it early. So what do you guys think about, I'm completely wrong with my understanding?

**Comment by laoneo** [comment]
I'v created an issue for it where we can discuss the development strategy of Joomla 4 in the public, please comment on #20189.

**Pull request merged**
