### PR TITLE
[4.1] Fix title by contact save to menu

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

contact object has no title property (only name)

### Testing Instructions

Create/Open a contact and click `Save to Menu`

### Actual result BEFORE applying this Pull Request

Menu item title is empty
`PHP Warning: Undefined property: Joomla\CMS\Object\CMSObject::$title in administrator\components\com_contact\src\Controller\ContactController.php on line 137`

### Expected result AFTER applying this Pull Request

Menu item title is name of contact

### Documentation Changes Required

none

### CODE REVIEW

**Comment by drmenzelit** [comment]
That is wrong, the title of the menu doesn't neccessary has to be the name of the contact. When you create a contact and save it to menu, a menu edit form opens and you can enter whatever you want as title.

**Comment by heelc29** [comment]
> That is wrong, the title of the menu doesn't neccessary has to be the name of the contact. When you create a contact and save it to menu, a menu edit form opens and you can enter whatever you want as title.

@drmenzelit Ok. Then we have to remove the line 137 (s. PHP warning)??

Note: If you do the same (save2menu) for an article, the default menu item title is the title of the article. It is only the suggest for the title and you can adjust it before you save the menu item.

**Comment by drmenzelit** [comment]
I undertand what you mean now. In articles the field containing the name of the name is called "title", but in contact the field is called "name". Then your PR could be correct. I will wait for other opinions.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 75eefb97df1c75277f9921b8eca1db671922d3a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37531">issues.joomla.org/tracker/joomla-cms/37531</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 75eefb97df1c75277f9921b8eca1db671922d3a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37531">issues.joomla.org/tracker/joomla-cms/37531</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37531">issues.joomla.org/tracker/joomla-cms/37531</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
