### PR TITLE
[4.0] Com_media strings codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
We have a style guide for en-gb language strings in the ui. https://developer.joomla.org/en-gb-user-interface-text-guidelines/introduction.html

The relevant part for this bug report is

use capitalisation for:
> Menu Items
Labels
Buttons

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 09e063915ca63f81d07d5059c2c879580ef017bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25378">issues.joomla.org/tracker/joomla-cms/25378</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09e063915ca63f81d07d5059c2c879580ef017bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25378">issues.joomla.org/tracker/joomla-cms/25378</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25378">issues.joomla.org/tracker/joomla-cms/25378</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
