### PR TITLE
Added submenus to Extensions > Manage

### PR DESCRIPTION
**Pull request by pe7er**
This PR adds a submenus to the Extensions > Manage menu.

Most other menu items have submenus with direct links to all menu options.
e.g. Components > Banners, has 4 submenus.
# Testing instructions
## Before this PR

Extensions > **Manage** has currently **no** submenus

manage-before
## After this PR

Extensions > **Manage** has submenus, which makes it possible to directly navigate to a submenu.
The order of the submenus should be the same as the order of the left menu items.
The links under the submenu items should be the same as the links in the left menu (they should point to the same pages).

manage-after

### CODE REVIEW

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on bd0cbed43cce5c78b4c0f2590b729c387f0d63a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8058">issues.joomla.org/joomla-cms/8058</a>.</sub>

**Comment by zero-24** [comment]
@pe7er can you alpha sort the new language strings?

**Comment by pe7er** [comment]
Thanks for testing @n9iels !
Thanks for your recommendation @zero-24, I've alpha sorted the language strings.

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 98e13acd212aa76c04eb8cc6c7f1f5bc9db797bd<br /><br />Tested, works like it should. I like this one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8058">issues.joomla.org/joomla-cms/8058</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 98e13acd212aa76c04eb8cc6c7f1f5bc9db797bd<br /><br />Works Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8058">issues.joomla.org/joomla-cms/8058</a>.</sub>

**Comment by zero-24** [comment]
RTC. Based on testing :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8058">issues.joomla.org/joomla-cms/8058</a>.</sub>

**Comment by coolman01** [comment]
I have tested this item :white_check_mark: successfully on 98e13acd212aa76c04eb8cc6c7f1f5bc9db797bd<br /><br />Something I've missed for ever! Great stuff. I really hope this gets added in the enxt version!
Works perfectly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8058">issues.joomla.org/joomla-cms/8058</a>.</sub>

**Comment by zero-24** [comment]
@coolman01 it is planed for 3.5 ;)

**Comment by roland-d** [comment]
Thanks everybody, merged into 3.5-dev with commit 1ff1dfb

**Pull request closed without merging**
