### PR TITLE
[4.0] Permissions accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
As a result of the accessibility performed last night on the Permissions page it was realised that it would be best for screen reader users to know what the changed setting is. For example if they chose "inherited" they need to know that this means that "allowed - inherited" has been selected.

The super easy way to do this is to wrap the "allowed - inherited" span in the html element output. This way whenever the output is updated it is automatically announced by the screen reader.

Technically we could remove the span and put the class on the `<output>` element but as that would require changing the javascript as well I didn;t see the need to do that. The code in this PR works perfectly without making that change

Pull Request for Issue # .

### Testing Instructions
Code review or by testing with a screen reader

### CODE REVIEW

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 7a34245720a58352d5c7accc85938e2c86cf6196<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25354">issues.joomla.org/tracker/joomla-cms/25354</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7a34245720a58352d5c7accc85938e2c86cf6196<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25354">issues.joomla.org/tracker/joomla-cms/25354</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25354">issues.joomla.org/tracker/joomla-cms/25354</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
