### PR TITLE
[4.0] [admin template] Missing mod_menu lang strings for modern preset

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Adding missing strings that were wrongly deleted in 4.0

### Testing Instructions
Edit the Administrator mod_menu and change preset from default Joomla to Modern
Screen Shot 2019-08-21 at 12 21 35

### Before patch
Many untranslated strings:

Screen Shot 2019-08-21 at 12 13 05
Screen Shot 2019-08-21 at 12 13 21
### After patch
All is fine
Screen Shot 2019-08-21 at 12 24 43

Screen Shot 2019-08-21 at 12 25 33

### CODE REVIEW

**Comment by infograf768** [comment]
NOTE: Obviously, this is useless if it is decided to delete the "Modern Preset". 
It is interesting though as it get rid of the "System" link (which could still be added if desired) as well as all these Dashboard stuff.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e7b31fd575427c829ba2cb08bf0b151305d9c667<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25956">issues.joomla.org/tracker/joomla-cms/25956</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on e7b31fd575427c829ba2cb08bf0b151305d9c667<br /><br />1) Go to admin menu module (4.0.0-alpha12-dev)
2) set preset to "Modern"
3) Language strings do appear under various items of Extension menu
4) Patch applied
5) Languages strings are fixed

Note: I have seen this "modern" preset more than once, but I didn't realize until now its function, which would reset somehow the "classic" Joomla menu.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25956">issues.joomla.org/tracker/joomla-cms/25956</a>.</sub>

**Comment by infograf768** [comment]
Thanks for testing.

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25956">issues.joomla.org/tracker/joomla-cms/25956</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for finding the missing strings.

**Pull request merged**
