### PR TITLE
Mark unused file as deprecated

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #17382

This file is not used in the core and hasnt been for a very long time as it was replaced by categoryedit. This simple PR add a deprecated notice that this will be removed in J4

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on a30613ab9d0fdff13bcc95b5cc06c0285d3c2654<br /><br />Found Line 18, but Line 120 is unchanged `$options[$i]->text = str_repeat('- ', $options[$i]->level) . $options[$i]->text;`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17392">issues.joomla.org/tracker/joomla-cms/17392</a>.</sub>

**Comment by brianteeman** [comment]
The only change in this PR is add the deprecated notice on l18

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a30613ab9d0fdff13bcc95b5cc06c0285d3c2654<br /><br />Than its successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17392">issues.joomla.org/tracker/joomla-cms/17392</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
