### PR TITLE
Replace  [docspagelink] by the correct html tag construct

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

`[docspagelink]` => `<a href="_QQ_"%s"_QQ_">docs.joomla.org</a>`

### Testing Instructions

Review (please ignore travis as it is broken in this branch)

### Expected result

No [docspagelink] anymore

### Actual result

Some languages use [docspagelink]

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
are you allowed to change installation files. The translation co-ordinators usually say no

**Comment by zero-24** [comment]
> are you allowed to change installation files. The translation co-ordinators usually say no

This was done on special task / request by Robert.

**Comment by rdeutz** [comment]
That's ok.

**Comment by infograf768** [comment]
Will let TTs know.

**Comment by zero-24** [comment]
Thanks JM.

**Pull request merged**
