### PR TITLE
Multilanguage module uses mootools modal

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Move modals from mootools to Bootstrap

FINAL PR to get all back end using bootstrap modals. The rest are: #4513 #4514 #4561 #4562 and #4563  

Testing:
**You need a multilingual site**
After Applying this patch 

Try the button on the sticky bar at the footer (first icon from left to right)

---

screenshot 2014-10-12 11 13 44
screenshot 2014-10-12 11 09 44

### CODE REVIEW

**Comment by 810** [comment]
the modal width and position, is now breaking modals. see kunena installer:
modal

**Comment by dgt41** [comment]
@810 what are the iframe dimensions?

**Comment by 810** [comment]
before
``` 
div.modal.fade.in {
    top: 10%;
}
div.modal {
   width:580px;
}
```

Now
``` 
div.modal.fade.in {
    top: 5%;
}
div.modal {
   width: 80%
}
```

**Comment by dgt41** [comment]
@810 Will come up with some code (less) tomorrow

**Comment by 810** [comment]
ok thanx

**Pull request closed without merging**
