### PR TITLE
Sort Privacy consents

### PR DESCRIPTION
**Pull request by brianteeman**
The order of the sort options should match the order of the columns

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e8a1e6c429755a39fb8bd2212e606b38da58b057<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26795">issues.joomla.org/tracker/joomla-cms/26795</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e8a1e6c429755a39fb8bd2212e606b38da58b057<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26795">issues.joomla.org/tracker/joomla-cms/26795</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26795">issues.joomla.org/tracker/joomla-cms/26795</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
