### PR TITLE
[4.0] Add parameters to hide "no contacts" message and "subcategories" title in Contacts - New

### PR DESCRIPTION
**Pull request by drmenzelit**
New PR in replacement of #31615 due to branch conflicts

Pull Request for Issue #31614 .

### Summary of Changes
Add parameters to hide "no contacts" message and "subcategories" title in 
Contacts » List Contacts in a Category and 
Contacts » List All Contact Categories

### Testing Instructions
Create a category and some subcategories in components -> contacts
Create a menu item of type
Contacts » List Contacts in a Category and / or
Contacts » List All Contact Categories

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
You will find two new parameters in the menu item and also in the global options for Contacts
grafik

grafik

The "no contacts" message and the "subcategories" title can be hidden
grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
Contacts » List Contacts in a Category and / or
Contacts » List All Contact Categories > List All Categories in a Contact Category Tree<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32736">issues.joomla.org/tracker/joomla-cms/32736</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fb45852099b53a1257675cb0b5721a26da31d6b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32736">issues.joomla.org/tracker/joomla-cms/32736</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fb45852099b53a1257675cb0b5721a26da31d6b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32736">issues.joomla.org/tracker/joomla-cms/32736</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32736">issues.joomla.org/tracker/joomla-cms/32736</a>.</sub>

**Pull request merged**
