### PR TITLE
[4.0] br element

### PR DESCRIPTION
**Pull request by brianteeman**
remove the closing slash from the br tag introduced with merge https://github.com/joomla/joomla-cms/commit/9c3371f969b80a8d7b36b46820cc69a0641e6f15

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 26012772514ff4a97870ff2a198e0f3fda2b588a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33510">issues.joomla.org/tracker/joomla-cms/33510</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 26012772514ff4a97870ff2a198e0f3fda2b588a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33510">issues.joomla.org/tracker/joomla-cms/33510</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33510">issues.joomla.org/tracker/joomla-cms/33510</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33510">issues.joomla.org/tracker/joomla-cms/33510</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
