### PR TITLE
Regression in the ISIS backed css

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #19411
Fixes the bug below
### Expected result

The same as of 3.8.3

image

### Actual result

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8417726d10d066e29f5b5ebd9ec06c0a3a8655d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19417">issues.joomla.org/tracker/joomla-cms/19417</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8417726d10d066e29f5b5ebd9ec06c0a3a8655d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19417">issues.joomla.org/tracker/joomla-cms/19417</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by zero-24** [comment]
Thanks 👍  . @mbabker please consider this for 3.8.4 as this is a regression in 3.8.4 ;)

**Comment by wilsonge** [comment]
Merging for 3.8.4

**Comment by brianteeman** [comment]
Thanks

**Comment by infograf768** [comment]
RTL was not corrected
screen shot 2018-01-21 at 16 20 40

Code should I guess be 
```
.navbar .nav-user .dropdown-menu li span {
	padding-left: 0;
	padding-right: 10px;
}

```

**Comment by infograf768** [comment]
I make a patch now

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/19423

**Pull request merged**
