### PR TITLE
[4.1] Remove title attribute

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove title attribute as it is not obvious of its value.

### Testing Instructions
Go to System > Manage > Languages
Hover cursor over the radio button.

### Actual result BEFORE applying this Pull Request
radio-title-attribute

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 38fa9d7905d48c4e8eee21b608176117ef9b7eb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37082">issues.joomla.org/tracker/joomla-cms/37082</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 38fa9d7905d48c4e8eee21b608176117ef9b7eb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37082">issues.joomla.org/tracker/joomla-cms/37082</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37082">issues.joomla.org/tracker/joomla-cms/37082</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
