### PR TITLE
[4.0] remove unused atum rtl css

### PR DESCRIPTION
**Pull request by brianteeman**
Removing these classes from the rtl override as we either no longer need the override or the class itself is no longer present.

code review

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on fa865564f370764d0095f866a406742bc5e5a319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36039">issues.joomla.org/tracker/joomla-cms/36039</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on fa865564f370764d0095f866a406742bc5e5a319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36039">issues.joomla.org/tracker/joomla-cms/36039</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36039">issues.joomla.org/tracker/joomla-cms/36039</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on fa865564f370764d0095f866a406742bc5e5a319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36039">issues.joomla.org/tracker/joomla-cms/36039</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
