### PR TITLE
[4.2] Remove not used db reference in users view

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Removes an obsolete reference in the users back end view. It was used for last visit date from #11396. Since dates are `NULL` from #26611, the database reference is not used anymore.

### Testing Instructions
Go to the site /administrator/index.php?option=com_users&view=users.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 2d67451c354918b4521055c7cd13f15664616095<br /><br />Tested successfully in Joomla 4.2.0-alpha2-dev of 22 April in Wampserver using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37607">issues.joomla.org/tracker/joomla-cms/37607</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 2d67451c354918b4521055c7cd13f15664616095<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37607">issues.joomla.org/tracker/joomla-cms/37607</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37607">issues.joomla.org/tracker/joomla-cms/37607</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37607">issues.joomla.org/tracker/joomla-cms/37607</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :)

**Pull request merged**
