### PR TITLE
[4.x] List Filters

### PR DESCRIPTION
**Pull request by brianteeman**
### Steps to reproduce the issue
Create a menu of type Articles Category List
Create a menu of type List all contacts in a category

Enable the display filter option in both

### Expected result
the filter field works/displays the same in both

### Actual result Com_content
In com_content there is an option to select what the filter field should be and depending on the filter field the display & functionality in the front end is adjusted.

image

#### Filter - Author (input)
image

#### Filter - Title (input)
image

#### Filter - Month(select)
image

### Actual result com_contact
In com_contact the option is just show/hide
image

image

## The _problem_ is 
1. com_contacts the form option in the admin is **filter**
2. com_contacts the button in the site is **filter**
3. the placeholder text (and aria-label)  is **search in title** in com_contacts but just **title filer** in com_contact

For a consistent ui this PR changes search in title to title filter

## Result
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 17c045204a93095a826f08eccb0f1aa0cf4c0999<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by kiki-G** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :red_circle: unsuccessfully on 0dba5868eda9070283d806fc6936f2073d4bf4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 0dba5868eda9070283d806fc6936f2073d4bf4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by patvb2003** [comment]
I have tested this item :white_check_mark: successfully on 0dba5868eda9070283d806fc6936f2073d4bf4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 0dba5868eda9070283d806fc6936f2073d4bf4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on 0dba5868eda9070283d806fc6936f2073d4bf4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37424">issues.joomla.org/tracker/joomla-cms/37424</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
