### PR TITLE
Debug permissions in com_users

### PR DESCRIPTION
**Pull request by Bakual**
We have a very nice and helpful view for "debugging" issues with user permissions. But that view is only available when "Debug System" is enabled in the global configuration. If it's disabled (like in normal production) the link to it is hidden.

### Summary of Changes
This PR adds two new options in the user manager which will allow to enable/disable that ~"Debug"~ "Advanced" view for the user and usergroup manager. Making the view more known.
The new options are enabled by default since there is no drawback to have them enabled. It's just a link shown. Also it will be B/C for those who had Debug enabled for whatever reason.

### Testing Instructions
* Apply the PR and test the new links right below each user/usergroup.
* Disable the option in the component options and make sure the link no longer appears.

### Expected result
Have a link to those views not depending on Debug status.

### Actual result
Links only shown when Debug is active.

### Documentation Changes Required
Maybe tutorials need to be adjusted.

#### Disclaimer
Work is done by @brianteeman

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1fff9dd52e58f8dee0eeeb0b81ad42f88d901fa4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 1fff9dd52e58f8dee0eeeb0b81ad42f88d901fa4<br /><br />Great #UX improvement. Thanks Brian<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by jeckodevelopment** [comment]
@Bakual  can you fix conflicts, please?

**Comment by jeckodevelopment** [comment]
Back to Pending due to conflicting files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by Bakual** [comment]
@jeckodevelopment Conflicts are solved now.

**Comment by ot2sen** [comment]
I have tested this item :white_check_mark: successfully on fab440151b01d28d862b787b39beb0d5d24a6fb5<br /><br />Very useful. Works well for reporting overview.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fab440151b01d28d862b787b39beb0d5d24a6fb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by jeckodevelopment** [comment]
@alikon and @ot2sen can you please re-test?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2555c79dc986b261fe3a13c6e48c835a1bf10c3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2555c79dc986b261fe3a13c6e48c835a1bf10c3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14408">issues.joomla.org/tracker/joomla-cms/14408</a>.</sub>

**Pull request merged**
