### PR TITLE
Add StackExchange link

### PR DESCRIPTION
**Pull request by brianteeman**
#5934

Add link to stack exchange in the help menu

### CODE REVIEW

**Comment by Fedik** [comment]
:+1:

**Comment by zero-24** [comment]
@Fedik can we count it as successful test? :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6868">issues.joomla.org/joomla-cms/6868</a>.</sub>

**Comment by Fedik** [comment]
@zero-24  yes :wink:

**Comment by zero-24** [comment]
Thanks @test successful also here. --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6868">issues.joomla.org/joomla-cms/6868</a>.</sub>

**Comment by mbabker** [comment]
The Hathor override also needs an update.

**Comment by brianteeman** [comment]
OK - will add that shortly

On 30 April 2015 at 14:00, Michael Babker <notifications@github.com> wrote:

> The Hathor override also needs an update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6868#issuecomment-97765883>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Hathor override added

**Comment by zero-24** [comment]
@test still success. Thanks Brian and Michael :+1:

**Pull request merged**
