### PR TITLE
[3.8] Update Composer dependencies

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Runs `composer update` for 3.8.  Operations run (this includes packages used solely in our testing environments as well as code shipped with production releases):

```sh
Package operations: 0 installs, 19 updates, 0 removals
  - Updating symfony/polyfill-php55 (v1.3.0 => v1.4.0): Loading from cache
  - Updating joomla/filter (1.3.2 => 1.3.3): Loading from cache
  - Updating joomla/application (1.7.0 => 1.8.1): Loading from cache
  - Updating paragonie/sodium_compat (v1.0.1 => v1.1.0): Loading from cache
  - Updating phpmailer/phpmailer (v5.2.23 => v5.2.24): Downloading (100%)         
  - Updating symfony/polyfill-util (v1.3.0 => v1.4.0): Loading from cache
  - Updating symfony/polyfill-php56 (v1.3.0 => v1.4.0): Loading from cache
  - Updating symfony/yaml (v2.8.20 => v2.8.26): Loading from cache
  - Updating phpdocumentor/reflection-docblock (2.0.4 => 2.0.5): Loading from cache
  - Updating phpunit/phpunit (4.8.35 => 4.8.36): Loading from cache
  - Updating symfony/stopwatch (v2.8.20 => v2.8.26): Loading from cache
  - Updating symfony/process (v2.8.20 => v2.8.26): Loading from cache
  - Updating symfony/finder (v2.8.20 => v2.8.26): Loading from cache
  - Updating symfony/filesystem (v2.8.20 => v2.8.26): Loading from cache
  - Updating symfony/event-dispatcher (v2.8.20 => v2.8.26): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.3.0 => v1.4.0): Loading from cache
  - Updating symfony/debug (v2.8.20 => v2.8.26): Downloading (100%)         
  - Updating symfony/console (v2.8.20 => v2.8.26): Downloading (100%)         
  - Updating friendsofphp/php-cs-fixer (v1.11.6 => v1.13.1): Loading from cache   
```

### Testing Instructions

The CMS continues to function as normal, the unit testing environment does not fail

### CODE REVIEW

**Comment by wilsonge** [comment]
@photodude can you help with appveyor here. looks like we need to install the ldap php package on appveyor

**Comment by photodude** [comment]
@wilsonge I'm out on vacation with just my phone for a couple more days. I'll look at it as soon as I'm back.

**Comment by wilsonge** [comment]
Thankyou! Have a lovely holiday!!

**Comment by mbabker** [comment]
For now I've added the `--ignore-platform-reqs` flag for AppVeyor (same as Travis) so it doesn't fail out on the `ext/ldap` dependency.  Since we aren't actually running LDAP related tests on the CMS repo, it's not a big deal for now, but at some point we probably want to not rely on that flag.

**Review by laoneo — APPROVED** [review]

**Comment by wilsonge** [comment]
Merging with this but when @photodude is back from holidays and ready to go again would be good to properly fix this!

**Comment by photodude** [comment]
@wilsonge @mbabker I've look a little into the LDAP and [how to set it up](http://php.net/manual/fa/ldap.requirements.php). [From what I read you have to have a version of PHP that is compiled for LDAP](http://php.net/manual/en/ldap.installation.php). That makes enabling LDAP a bit more difficult. I think for linux there may be precompiled packages with LDAP, and looking over the windows options the packages might be LDAP ready packages. (I haven't used LDAP before so I'm learning about installing and using it as I go)

**Comment by mbabker** [comment]
With the Precise images you could compile in LDAP pretty easily (see https://github.com/joomla-framework/ldap/commit/bdba4bba14fdf8eb33e1cd9227ba04186aaf6193).  That same config doesn't work with the new Trusty images.  And that's just with Travis.  Windows (and AppVeyor) are an entirely different beast.

**Comment by mbabker** [comment]
(BTW that setup is very close to how Symfony's setting up Travis so they can run tests on their LDAP component, for this repo that should be all that's needed since the actual client tests would need to be done in the Framework package repo going forward until we have a proper acceptance test system which should validate the LDAP authentication plugin functions correctly within a Joomla install)

**Comment by photodude** [comment]
I'm guessing the issue on travis is their trusty image doesn't have `ldap-utils` whitelisted for apt-get. I'll double check if that is the case.

**Comment by photodude** [comment]
Well `ldap-utils` is whitelisted for travis trusty images https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty#L4043 so there shouldn't be an issue. (maybe it's pathed a little different than the precise images)

**Comment by mbabker** [comment]
It's not apt that's the issue, I came across https://github.com/travis-ci/travis-ci/issues/7067 and didn't really put much effort into testing the LDAP setup on Trusty (Symfony rolled back to Precise because of that issue, see https://github.com/symfony/symfony/pull/23612).

**Pull request merged**
