### PR TITLE
[4.1] One time emergency passwords

### PR DESCRIPTION
**Pull request by brianteeman**
Change the layout to vertical in cassiopeia so it is the same as in atum. This makes it much easier to read.

Pull Request for Issue #37468 .

## Before
image

## After
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4096f848b6c8187dba6cc5358dc333cf1ef0fa44<br /><br />Tested successfully in Joomla 4.1.3-dev of 4 April using Wampserver 3.2.7 and PHP 7.4.26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37476">issues.joomla.org/tracker/joomla-cms/37476</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4096f848b6c8187dba6cc5358dc333cf1ef0fa44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37476">issues.joomla.org/tracker/joomla-cms/37476</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37476">issues.joomla.org/tracker/joomla-cms/37476</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by chmst** [comment]
I am not in favour of this solution. Two times the same piece of code.

**Comment by brianteeman** [comment]
I think you are confused

**Pull request merged**
