### PR TITLE
[4.1] Description for class "Intro Image"

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37560 (part 1).

### Summary of Changes
The description of the parameter for the introductory image is missing (there is a description for the full one).

Screenshot_1

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 23d846abf68bf333aa234de1e322c0eee5e3b090<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37563">issues.joomla.org/tracker/joomla-cms/37563</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 23d846abf68bf333aa234de1e322c0eee5e3b090<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37563">issues.joomla.org/tracker/joomla-cms/37563</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37563">issues.joomla.org/tracker/joomla-cms/37563</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by wojsmol** [comment]
@Kostelano Please add partly after issue number in PR description.

**Pull request merged**
