### PR TITLE
[4.0] Update some more icons

### PR DESCRIPTION
**Pull request by brianteeman**
Update a few more icons from FA4 to FA5

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cc82ed074470cc6811ea65cc70fd72d96b5c7822<br /><br />Code review + verification of new icons at [https://fontawesome.com/icons?d=gallery](https://fontawesome.com/icons?d=gallery "https://fontawesome.com/icons?d=gallery")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24661">issues.joomla.org/tracker/joomla-cms/24661</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cc82ed074470cc6811ea65cc70fd72d96b5c7822<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24661">issues.joomla.org/tracker/joomla-cms/24661</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24661">issues.joomla.org/tracker/joomla-cms/24661</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
