### PR TITLE
[4.0] Add tooltip to sidebar icons

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26667 .

### Summary of Changes
Display tooltip on hover of sidebar icons.

### Testing Instructions
Login to backend.
Click on toggle menu.
Hover over an icon.
No tooltip.
Apply PR.
Hover over an to display tooltip.

### CODE REVIEW

**Comment by infograf768** [comment]
Works fine

Note: that sort of tooltip is formatted by the OS and browser and using such a small font size that it is hard to read.
The problem is not limited to this tooltip but all over J. Maybe it is possible, in another PR, to increase the size with a specific js?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2e0cb6306b64a5813e868fc116868017b6c62d72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27347">issues.joomla.org/tracker/joomla-cms/27347</a>.</sub>

**Comment by brianteeman** [comment]
>  Maybe it is possible, in another PR, to increase the size 

No its a native browser setting and we should not change those.

I personally would prefer something more "styled" than just using the title tag.
menu

**Comment by ChristineWk** [comment]
In principle it works, I see the tooltips. But the title shows:
`<a id="menu-collapse" href="#" class="">
<span id="menu-collapse-icon" class="fa fa-fw fa-toggle-on" aria-hidden="true" title="JTOGGLE_SIDEBAR_MENU"></span>
<span class="sidebar-item-title">JTOGGLE_SIDEBAR_MENU</span>
</a><hr` /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27347">issues.joomla.org/tracker/joomla-cms/27347</a>.</sub>

**Comment by infograf768** [comment]
@ChristineWk 
it is translated here.

**Comment by ChristineWk** [comment]
Aha :-) ... Is it successful now? - even I see above title: JTOGGLE_SIDEBAR_MENU

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2e0cb6306b64a5813e868fc116868017b6c62d72<br /><br />The reason of wrong translation was: I hv beta-dev from october, but there is: https://github.com/joomla/joomla-cms/commit/4e7bc1c9e0f88b995cf59974f35fbcfd2e4d0b94.
Finally I changed all above files accordingly.
`<a id="menu-collapse" href="#" class="">
						<span id="menu-collapse-icon" class="fa fa-fw fa-toggle-on" aria-hidden="true" title="Toggle Menu"></span>
						<span class="sidebar-item-title">Toggle Menu</span>
					</a>`
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27347">issues.joomla.org/tracker/joomla-cms/27347</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27347">issues.joomla.org/tracker/joomla-cms/27347</a>.</sub>

**Comment by infograf768** [comment]
@brianteeman 
I see no way to modify admin-menu.js (and metismenu) to get what you propose.
As far as I understand, you propose https://mm.onokumus.com/mm-vertical-hover.html which is very different from what we use today, as it is unrelated to our menu toggle.
If you do not propose some code shortly, I suggest we merge this.

**Comment by brianteeman** [comment]
@infograf768 no need to touch any js at all see #27352

**Comment by richard67** [comment]
Both PR's work for me, this one here and @brianteeman 's #27352 . Not sure what's the better way to do it regarding all aspects, but from a visual point of view I really like Brian's solution. It really is nice.

**Comment by Quy** [comment]
Closing in favour of #27352

**Pull request closed without merging**
