### PR TITLE
Prevent Super User from demoting itself

### PR DESCRIPTION
**Pull request by roland-d**
#### Summary of Changes

Currently it is possible as a super user to remove your own super user rights. This causes you to be locked out from your own site.
#### Testing Instructions
1. Login to the administrator section as Super User
2. Go to System -> Global Configuration -> Permissions
3. Click on the Super Users tab
4. Set the Super User option to Denied
5. Success and you are locked out :)
6. Fix the database so you can login by going to ID 1 in the assets table and set core.admin to {"8":1}
7. Apply the patch
8. Login to the administrator section as Super User
9. Go to System -> Global Configuration -> Permissions
10. Click on the Super Users tab
11. Set the Super User option to Denied
12. You are informed you cannot demote yourself and you stay logged in

Calling the troops @andrepereiradasilva and @infograf768 :+1:

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 85836c6ae9e150e74458f2f7b74b58cdbabfb5cb<br /><br />This works fine for a SuperUser in Global as well as in component permissions.

Note: it does not work for other groups. For example a group with Administrator as parent trying to change his own permission gets a spin (js error) and no message.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10758">issues.joomla.org/joomla-cms/10758</a>.</sub>

**Comment by brianteeman** [comment]
The error message I got was undefined

screen shot 2016-06-08 at 11 34 00
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10758">issues.joomla.org/joomla-cms/10758</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman are you using lates staging and refreshed the browser cache?

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 85836c6ae9e150e74458f2f7b74b58cdbabfb5cb<br /><br />Works as described.
Also can confirm jean-marie results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10758">issues.joomla.org/joomla-cms/10758</a>.</sub>

**Comment by brianteeman** [comment]
It was staging from this morning. Will update again and retest

On 8 June 2016 at 18:09, andrepereiradasilva <notifications@github.com>
wrote:

> I have tested this item ✅ successfully on 85836c6
> <https://github.com/joomla/joomla-cms/commit/85836c6ae9e150e74458f2f7b74b58cdbabfb5cb>
>
> Works as described.
> Also can confirm jean-marie results.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10758
> <https://issues.joomla.org/tracker/joomla-cms/10758>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10758#issuecomment-224660640>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8UaEAqmiuFAWy6UUVIf2iAZwVJDuks5qJvc8gaJpZM4IxHy3>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 85836c6ae9e150e74458f2f7b74b58cdbabfb5cb<br /><br />Took a LOT of cache refreshes but i got there in the nd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10758">issues.joomla.org/joomla-cms/10758</a>.</sub>

**Comment by andrepereiradasilva** [comment]
BTW maybe we should add ScriptVersion to permission.js ...

**Comment by infograf768** [comment]
rtc. thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10758">issues.joomla.org/joomla-cms/10758</a>.</sub>

**Pull request merged**
