### PR TITLE
Fix https base tag generation.

### PR DESCRIPTION
**Pull request by wojsmol**
Hallo
This PR replaces  https://github.com/joomla/joomla-cms/pull/6270 by @GregoryRusakov and is based on code proposed by @nonumber in https://github.com/joomla/joomla-cms/pull/6270#issuecomment-81733590 .

A copy of the original PR description

> Fixed https base tag generation.
> Discussion is here:
> https://github.com/joomla/joomla-cms/issues/4961#issuecomment-76674032

### CODE REVIEW

**Comment by GregoryRusakov** [comment]
Everything is ok.

**Comment by wojsmol** [comment]
@GregoryRusakov Please mark your test results on http://issues.joomla.org/tracker/joomla-cms/7902

**Comment by wojsmol** [comment]
@GregoryRusakov  Thank you for the test, @zero-24 already mark  the result on http://issues.joomla.org/tracker/joomla-cms/7902. We need one more tester.

**Comment by jayblaq** [comment]
Hello - Can you please explain the test so I can validate?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7902">issues.joomla.org/joomla-cms/7902</a>.</sub>

**Comment by weeblr-dev** [comment]
Hi folks,

I have strong doubts about this PR. Using JUri::base() is not the definition of the <base> tag. Such change will break all hardcoded relative URL in a page, the most common being the named anchors such as <a href="#top">Go to top</a> or similar.

The initial PR (#6270) discussion doesn't seem conclusive to me, as base tag is properly set on my https sites with current Joomla. Regardless, this PR will break many sites.

Rgds

**Comment by weeblr** [comment]
Hi folks,

I have strong doubts about this PR. Using JUri::base() is not the definition of the <base> tag. Such change will break all hardcoded relative URL in a page, the most common being the named anchors such as <a href="#top">Go to top</a> or similar.

The initial PR (#6270) discussion doesn't seem conclusive to me, as base tag is properly set on my https sites with current Joomla. Regardless, this PR will break many sites.

Rgds

**Comment by Sulpher** [comment]
Hello,
Access to the website is organized on next schema: 
Front (Nginx) -> Middle (Varnish) -> Back (Apache). Interaction with Middle and Back from Front side executes via http for better performance.
So, this PR is still actual.

The patch works, but as @weeblr said, it affect anchors. So, we need another solution that let Joomla to work with Varnish correctly. Is there any idea?

**Comment by Sulpher** [comment]
The problem is still actual.

**Comment by chris001** [comment]
Could you provide the steps to recreate the issue with the existing code and explain why the issue occurs.

And the steps to recreate when and why the fix proposed would work, and not work.

**Pull request closed without merging**
