### PR TITLE
[4.0] webcomponents everywhere, user field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Move the user field to web components
- Original functionality
- still jQuery until we move the modals to web components

### Testing Instructions

Edit an article and change the Created By or Modified By fields

### Expected result

Same functionality as 3.x

### Actual result

Same functionality as 3.x

### Documentation Changes Required

NOPE

### CODE REVIEW

**Comment by brianteeman** [comment]
Cant test as I get this error whenever I click on the user
```
Notice: Undefined variable: isMoo in C:\Apache24\htdocs\cms4\administrator\components\com_users\tmpl\users\modal.php on line 76
> Super User
```

**Comment by brianteeman** [comment]
No mootools error now and it seems to work ok. BUT the console has lots of errors related to flying-focus.js Not sure if thats related to this PR or not?

**Comment by dgrammatiko** [comment]
@brianteeman there are two kinds of errors:
- flying focus
- missing source map file of popper.js
but both are not related to this PR (you can move to a list view and still get those errors and list views don't have use input fields).

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0b46111be3ab70100438eb62881a7c4e223bb4ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17763">issues.joomla.org/tracker/joomla-cms/17763</a>.</sub>

**Comment by C-Lodder** [comment]
Hmm I'll get that error fixed for flying focus and release an update

**Comment by brianteeman** [comment]
thanks @C-Lodder

**Pull request closed without merging**
