### PR TITLE
Sticky Pinned

### PR DESCRIPTION
**Pull request by brianteeman**
Replacement PR for #5857

### CODE REVIEW

**Comment by brianteeman** [comment]
@waader @pe7er @wilsonge Can you retest this fixed PR please <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5865">issues.joomla.org/joomla-cms/5865</a>.</sub>

**Comment by waader** [comment]
@test ok!

**Comment by anibalsanchez** [comment]
@test OK!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5865">issues.joomla.org/joomla-cms/5865</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the tests and the PR i move this to RTC now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5865">issues.joomla.org/joomla-cms/5865</a>.</sub>

**Comment by wilsonge** [comment]
Merged. Thanks Brian!

**Pull request merged**
