### PR TITLE
[4.0] [com_config] Fix buttons

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Fixes buttons not working when clicking on icons.

### Testing Instructions

`node build.js --compile-js` required.
Edit global configuration or template settings in frontend.
Click on the icon inside the button to submit form.

### Expected result

Form submitted.

### Actual result

Form not submitted. JS error appears:

```
TypeError: form is undefined validate.js:265:22
    isValid media/system/js/fields/validate.js:265
    submitTask media/com_config/js/config-default.js:21
    registerEvents media/com_config/js/config-default.js:36

```

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a5e20f067e7daf4a95e1889666556d367b95482c<br /><br />Very tricky, you really have to hit the icon inside the button and not the rest of the button to get the error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29350">issues.joomla.org/tracker/joomla-cms/29350</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a5e20f067e7daf4a95e1889666556d367b95482c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29350">issues.joomla.org/tracker/joomla-cms/29350</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29350">issues.joomla.org/tracker/joomla-cms/29350</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
