### PR TITLE
[5.1] SEF plugin: Adding note about experimental options

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This adds a note that the following options in the SEF plugin are experimental.

### Testing Instructions
Apply patch, look at sef plugin options and see the new spacer.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
For reference I wrote the following

> another possibility is to adopt drupal's experimental policy. that would allow the code to be merged knowing that it may cause unkown issues and will not be tied to a b/c policy etc.
> 
> because of the different structure in joomla then they could be marked in the ui like below
> 
> image
> 
> reference https://www.drupal.org/about/core/policies/core-change-policies/experimental/policy-and-list
> 
> This would allow time for the previously mentioned test suite to be created before the code is removed from the experimental list

Just writing "experimental" is not enough - it needs an actual policy behind it - otherwise its meaningless

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on d2a468ce504b6ff30ad01476177f3634ea21f71a<br /><br />Tested successfully in Joomla 5.1.0-beta2-dev of 18 March using PHP 8.2.13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43075">issues.joomla.org/tracker/joomla-cms/43075</a>.</sub>

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on d2a468ce504b6ff30ad01476177f3634ea21f71a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43075">issues.joomla.org/tracker/joomla-cms/43075</a>.</sub>

**Comment by Hackwar** [comment]
The release managers decided that we will not introduce the concept of experimental features in Joomla. Which is prefered by me.

**Pull request closed without merging**
