### PR TITLE
[4.2] Missing description for combination J+M

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/38163.

### Summary of Changes
Added a description of the `J M Toggle Menu` combination to the new plugin **System - Keyboard Shortcuts**.

Screenshot_1

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e7cb3f1a52a400eed9ad47006d0642e72b3695a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38165">issues.joomla.org/tracker/joomla-cms/38165</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e7cb3f1a52a400eed9ad47006d0642e72b3695a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38165">issues.joomla.org/tracker/joomla-cms/38165</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38165">issues.joomla.org/tracker/joomla-cms/38165</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
