### PR TITLE
[5.0] Improve CSS/JS build times

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Replace Terser and PostCSS with ESBuild (Go) and LightningCSS (Rust) to improve build times.

### Testing Instructions

1. Run `npm i`
2. Perform a sanity test to ensure there and no JS errors or styling issues

### BEFORE (local machine)

> Timer: Build finished in **35396 ms**

### AFTER (local machine)

> Timer: Build finished in **17231 ms**

@dgrammatiko I haven't removed PostCSS completely because the build scripts are still using your custom PostCSS plugin, which I didn't want to touch.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
> I haven't removed PostCSS completely because the build scripts are still using your custom PostCSS plugin, which I didn't want to touch.

I could do a lightningCSS plugin for the versioning of the URLs

**Comment by laoneo** [comment]
Great PR! Would you mind to move this to 4.4? As 4 is still around for 2 years, it would help maintaining it.

**Comment by C-Lodder** [comment]
@laoneo sure, will redo on 4.4

**Comment by C-Lodder** [comment]
Closing for https://github.com/joomla/joomla-cms/pull/42325

**Pull request closed without merging**
