### PR TITLE
[4.3][Guided Tours] Fix DESCRIPTION: search

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
`DESCRIPTION:` length is 12 and not 8. Probably a copy/paste error from `CONTENT:`

### Testing Instructions
Code review.
or
Go to System > Guided Tours.
In the search box, enter `DESCRIPTION:article`.

### Actual result BEFORE applying this Pull Request
No match results.

### Expected result AFTER applying this Pull Request
1 found.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 4a2bc8510f51df5eaec3a254c9197f27a4aa1a32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40118">issues.joomla.org/tracker/joomla-cms/40118</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4a2bc8510f51df5eaec3a254c9197f27a4aa1a32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40118">issues.joomla.org/tracker/joomla-cms/40118</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40118">issues.joomla.org/tracker/joomla-cms/40118</a>.</sub>

**Comment by obuisard** [comment]
Thank you @Quy !

**Pull request merged**
