### PR TITLE
[4.2] s/wil/will

### PR DESCRIPTION
**Pull request by brianteeman**
error: `Wil` should be `Will`

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9056b5ee2802d81207c74f6e671a6cb037643f56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38843">issues.joomla.org/tracker/joomla-cms/38843</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9056b5ee2802d81207c74f6e671a6cb037643f56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38843">issues.joomla.org/tracker/joomla-cms/38843</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38843">issues.joomla.org/tracker/joomla-cms/38843</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
