### PR TITLE
This module shows a list of the currently Logged-in Users.

### PR DESCRIPTION
**Pull request by Bakual**
This module shows a list of the currently Logged-in Users.
So giving it a title of LAST Logged-in Users is incorrect as that would be a list of the last x users who have logged in and might not be logged in anymore.

### Summary of Changes
Changes the language strings to more accurately describe what the module does.

### Testing Instructions
* Create an admin module of type "Logged-in Users" and assign it to the cpanel position (or use the existing one)
* Enable the "Automatic Title" module option (in Advanced tab)
* Check the title of the module in the Control Panel
* Change the "Count" module option and verify that the module title adjusts:
   "0" should give "Logged-in Users"
   "1" should give "Logged-in User"
   "5" should give "5 Logged-in Users"

#### Disclaimer
Work is done by @brianteeman

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 0660141e5b44a63fcbe899410d2121808d4f4d88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14297">issues.joomla.org/tracker/joomla-cms/14297</a>.</sub>

**Comment by infograf768** [comment]
Disagree. I explain:
The number of users depends on the parameters set in the module.

screen shot 2017-03-02 at 09 34 03

Therefore if you use the # per default (5) and there are 20 users logged, it is indeed the last 5 ones logged in and currently still logged in which are displayed.

If the confusion exists, then let's maybe rather use:
MOD_LOGGED_TITLE="Last Currently Logged-in Users"

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 0660141e5b44a63fcbe899410d2121808d4f4d88<br /><br />
For the reasons explained above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14297">issues.joomla.org/tracker/joomla-cms/14297</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
`Last Currently Logged-in Users` 👍

**Comment by Bakual** [comment]
I'm closing this PR as @brianteeman is now able to create his own PRs again :smile:

**Comment by brianteeman** [comment]
Thanks @Bakual i am gong to abandon this. i really cant be bothered debating english with non english status

**Pull request closed without merging**
