### PR TITLE
[5.1] Remove string JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

The line was probably added twice by a merge of 4.4 and will be deleted with this PR.

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

The string exists twice.

### Expected result AFTER applying this Pull Request

The second incident has been deleted.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@tecpromotion We have the same also in the site language file `language/en-GB/lib_joomla.ini` in lines 346 and 348.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f7c1d8c3abe28fe2066dfe5f47e890b0ad0364b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42941">issues.joomla.org/tracker/joomla-cms/42941</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7f7c1d8c3abe28fe2066dfe5f47e890b0ad0364b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42941">issues.joomla.org/tracker/joomla-cms/42941</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42941">issues.joomla.org/tracker/joomla-cms/42941</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
