### PR TITLE
[5.2] CoreButtonsTrait back() generates wrong button text

### PR DESCRIPTION
**Pull request by pAnd0rASBG**
Pull Request for Issue #44432  .

### Summary of Changes
Changed back function to use $text instead of 'back'

### Testing Instructions
`$toolbar = Toolbar::getInstance(); $toolbar->back('foobar');`

### Actual result BEFORE applying this Pull Request
`<a href="javascript:history.back();">back</a>` 

### Expected result AFTER applying this Pull Request
`<a href="javascript:history.back();">foobar</a>` 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
@pAnd0rASBG Can you give more instructions how to test?

**Comment by pAnd0rASBG** [comment]
> @pAnd0rASBG Can you give more instructions how to test?

e.g. in /administrator/components/com_banners/src/View/Clients/HtmlView.php after Line 131, add
`            $toolbar->addNew('client.add');
            $toolbar->back('foobar');`

Then go to Components > Banners > Clients in backend. 

Old behavior:
Screenshot_116

Corrected behavior:
Screenshot_117

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 8a9c3d6e5720f4bfa4166a6a7ffec2e8a09f947d<br /><br />@pAnd0rASBG Thanks for help to test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44509">issues.joomla.org/tracker/joomla-cms/44509</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8a9c3d6e5720f4bfa4166a6a7ffec2e8a09f947d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44509">issues.joomla.org/tracker/joomla-cms/44509</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44509">issues.joomla.org/tracker/joomla-cms/44509</a>.</sub>

**Pull request merged**
