### PR TITLE
[4.0][CLI] Add new Cors settings

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #31898 .

### Summary of Changes
added missing new cors settings default on install

### Testing Instructions

1. install joomla
2. run `php cli/joomla.php config:set error_reporting=development`

### Actual result BEFORE applying this Pull Request
error

### Expected result AFTER applying this Pull Request

No error should be present

### CODE REVIEW

**Comment by richard67** [comment]
Forgotten to change the settings after copying?

**Comment by richard67** [comment]
Seems to be copied cache settings now.

**Comment by alikon** [comment]
my bad
fixed

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0a51ec2a9c107dab0d28fd126862d17734ce7478<br /><br />Tested successfully in Beta7-dev of 9 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31937">issues.joomla.org/tracker/joomla-cms/31937</a>.</sub>

**Comment by Razzo1987** [comment]
Keep returning the error:

```
Symfony\Component\ErrorHandler\Error\UndefinedFunctionError^ {#142
  #message: "Attempted to call function "simplexml_load_file" from namespace "Joomla\CMS\Language"."
  #code: 0
  #file: "./libraries/src/Language/LanguageHelper.php"
  #line: 680
  trace: {
    ./libraries/src/Language/LanguageHelper.php:680 {
      Joomla\CMS\Language\LanguageHelper::parseXMLLanguageFile($path)^
      › // Try to load the file
      › $xml = simplexml_load_file($path);
      › 
    }
    ./libraries/src/Language/LanguageHelper.php:572 { …}
    ./libraries/src/Language/Language.php:193 { …}
    ./libraries/src/Language/LanguageFactory.php:32 { …}
    ./libraries/src/Language/CachingLanguageFactory.php:43 { …}
    ./libraries/src/Service/Provider/Application.php:121 { …}
    ./libraries/vendor/joomla/di/src/ContainerResource.php:176 { …}
    ./libraries/vendor/joomla/di/src/Container.php:96 { …}
    ./cli/joomla.php:67 { …}
  }
}
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31937">issues.joomla.org/tracker/joomla-cms/31937</a>.</sub>

**Comment by wilsonge** [comment]
@Razzo1987 looks like your PHP setup is missing lib-xml

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0a51ec2a9c107dab0d28fd126862d17734ce7478<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31937">issues.joomla.org/tracker/joomla-cms/31937</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31937">issues.joomla.org/tracker/joomla-cms/31937</a>.</sub>

**Comment by wilsonge** [comment]
This isn't going to be enough. We're going to need to cover configuration.php files for people upgrading from Joomla 3.10

**Comment by alikon** [comment]
back to pending for cover update from 3.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31937">issues.joomla.org/tracker/joomla-cms/31937</a>.</sub>

**Comment by brianteeman** [comment]
> This isn't going to be enough. We're going to need to cover configuration.php files for people upgrading from Joomla 3.10

Don't they automatically get the cors settings added to the configuration.php as soon as they save the global config for the first time AND as its disabled by default it doesnt matter if they dont do it

**Comment by wilsonge** [comment]
> Don't they automatically get the cors settings added to the configuration.php as soon as they save the global config for the first time AND as its disabled by default it doesnt matter if they dont do it

For the actual API yes, but per the original issue apparently something breaks inside com_config CLI endpoint

**Comment by wilsonge** [comment]
That looks better but it needs to cover cases on further updates where these values are already set

**Comment by alikon** [comment]
public function postflight($action, $installer)
	{
		if ($action !== 'update')
		{
			return true;
		}


		if (empty($this->fromVersion) || version_compare($this->fromVersion, '4.0.0', 'ge'))
		{
			return true;
		}


the postflight runs on update from version less than 4.0.0

**Comment by richard67** [comment]
I.e. it never runs when updating a previous beta which doesn't have the new settings?

**Comment by alikon** [comment]
it runs on previous beta too....
as an example 
```php
$old='4.0.0-beta4-dev';
version_compare($old, '4.0.0', 'ge');  // return false
```

**Pull request closed without merging**
