### PR TITLE
[4.0] - fix save article

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23617

### Summary of Changes
the comment few lines above  :smile:  
> 		
/**
		 * Ensure any new items have compulsory fields set. This is needed for things like
		 * frontend editing where we don't show all the fields or using some kind of API
		 */

### Testing Instructions
see #23617

### Expected result
save article works

### Actual result
don't

### CODE REVIEW

**Comment by amitranjan2** [comment]
I have tested this item :white_check_mark: successfully on ae12205ed3a8f694c6ab0e5ffe3bffcfbc09d048<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23638">issues.joomla.org/tracker/joomla-cms/23638</a>.</sub>

**Comment by alikon** [comment]
just curious why drone complain  for analysis4x ???

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ae12205ed3a8f694c6ab0e5ffe3bffcfbc09d048<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23638">issues.joomla.org/tracker/joomla-cms/23638</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23638">issues.joomla.org/tracker/joomla-cms/23638</a>.</sub>

**Comment by infograf768** [comment]
Restarted drone.

**Comment by wilsonge** [comment]
Thanks!

**Comment by Leen29** [comment]
I have tested this item ✅ successfully on [ae12205](https://github.com/joomla/joomla-cms/commit/ae12205ed3a8f694c6ab0e5ffe3bffcfbc09d048)

**Pull request merged**
