### PR TITLE
System URL menu link

### PR DESCRIPTION
**Pull request by brianteeman**
At some point in time this has changed from being only an external url to any url. It makes no sense to have a menu type of "External URL" with a description of "An external or internal URL"

This simple PR resolves that by changing the name of the menu type to simply "URL"
screenshotr11-26-32

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 49b5a8bce3756ebac0c12d81f555658008e1431d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17419">issues.joomla.org/tracker/joomla-cms/17419</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 49b5a8bce3756ebac0c12d81f555658008e1431d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17419">issues.joomla.org/tracker/joomla-cms/17419</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks for the fast merge

**Pull request merged**
