### PR TITLE
[4.2] Update deleted files and folders for 4.2.0-beta2

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Update the lists of files and folders to be deleted on update by script.php to the latest changes in the 4.2-dev branch in preparation of the upcoming 4.2.0 Beta 2.

Following files and folder from following PR's are included (note that this includes the old location of moved files):
- From PR #37928 file "plugins/behaviour/taggable/taggable.php".
- From PR #37929 file "plugins/behaviour/versionable/versionable.php".
- From PR #37947 file "modules/mod_articles_latest/mod_articles_latest.php".
- From PR #37954 file "plugins/task/requests/requests.php".
- From PR #38065 files "layouts/plugins/user/profile/fields/dob.php" and "plugins/user/profile/src/Field/DobField.php" and folders "layouts/plugins/user/profile/fields" and "layouts/plugins/user/profile".
- From PR #38097 file "plugins/task/sitestatus/sitestatus.php".

### Testing Instructions

Code review.

Or if you want to make a real test, update a 4.2.0-beta1 to the last 4.2 nightly build to get the actual result, and update a 4.2.0-beta1 to the update package built by Drone for this PR to get the expected result.

### Actual result BEFORE applying this Pull Request

Files and folders mentioned in the description above are still present after updating from 4.2.0-beta1.

### Expected result AFTER applying this Pull Request

All files and folders mentioned in the description above have been deleted after updating from 4.2.0-beta1.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 189027bbb91567e367ba10e4be0081dbd4612bea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38039">issues.joomla.org/tracker/joomla-cms/38039</a>.</sub>

**Comment by richard67** [comment]
@sandewt Thanks for your test. Unfortunately it doesn't make much sense since this PR is in draft status and clearly marked as WiP (work in progress) in the title and the description because there might be more PRs merged into 4.2-dev before the next beta release and so more files have to be added to this PR here. So I suggest to wait with testing until the PR is ready (not draft anymore). But very likely the release leads will merge it by review when time has come.

**Comment by sandewt** [comment]
@richard67

I will wait :smiley:

**Comment by richard67** [comment]
@sandewt The PR is ready now. So if you still can find the time for testing, it would be welcome.

**Comment by richard67** [comment]
Ping @roland-d .

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on a59ef1303189c67e2f2adf3b0a81c1de330298be<br /><br />

>Code review.

Done

>Or if you want to make a real test, update a 4.2.0-beta1 to the last 4.2 nightly build to get the actual result, and update a 4.2.0-beta1 to the update package built by Drone for this PR to get the expected result.

Done<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38039">issues.joomla.org/tracker/joomla-cms/38039</a>.</sub>

**Comment by richard67** [comment]
@sandewt Thanks.

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
