### PR TITLE
[4.0][com_csp] fix install sql menu

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #23359

### Summary of Changes
fix sql for com_csp menu

### Expected result
com_csp available under 
screenshot from 2019-01-18 17-55-36

### Actual result
not available

### CODE REVIEW

**Comment by twister65** [comment]
I have a mysql error if I try to insert a datetime with '0000-00-00 00:00:00'

> The DATETIME type is used for values that contain both date and time parts. MySQL retrieves and displays DATETIME values in 'YYYY-MM-DD HH:MM:SS' format. The supported range is '1000-01-01 00:00:00' to '9999-12-31 23:59:59'.

https://dev.mysql.com/doc/refman/5.7/en/datetime.html

> INSERT INTO `i05k8_menu`(`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) VALUES (23, 'main', 'com_csp', 'Content-Security-Policy', '', 'Content-Security-Policy', 'index.php?option=com_csp', 'component', 1, 1, 1, 36, 0, '1000-01-01 00:00:00', 0, 0, 'class:associations', 0, '', 41, 42, 0, '*', 1)

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 1840d8825b0722270822c64bf8c2354f7ab25bf2<br /><br />With check_out_time '1000-01-01 00:00:00'.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23586">issues.joomla.org/tracker/joomla-cms/23586</a>.</sub>

**Review by zero-24 — APPROVED** [review]
looks good to me thanks!

**Comment by twister65** [comment]
> With MySQL strict mode enabled, which is the default state, invalid or missing data may cause warnings or errors when attempting to process the query.

> With strict mode set (default from MariaDB 10.2.4), the statements will fail, and an error will be returned instead.

> If strict mode is enabled, '0000-00-00' is not permitted and inserts produce an error.

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

**Comment by robertolongo** [comment]
I have tested this item :white_check_mark: successfully on 8f194dd57a5d3b4ad88e0d88b24e06c4078be94d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23586">issues.joomla.org/tracker/joomla-cms/23586</a>.</sub>

**Comment by lucasacchiricciardi** [comment]
I have tested this item :white_check_mark: successfully on 8f194dd57a5d3b4ad88e0d88b24e06c4078be94d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23586">issues.joomla.org/tracker/joomla-cms/23586</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on 8f194dd57a5d3b4ad88e0d88b24e06c4078be94d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23586">issues.joomla.org/tracker/joomla-cms/23586</a>.</sub>

**Comment by zero-24** [comment]
I have just rebooted drone so hopefully our bots are getting all happy to and this can finally be merged :D 

http://ci.joomla.org/joomla/joomla-cms/14878

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23586">issues.joomla.org/tracker/joomla-cms/23586</a>.</sub>

**Comment by zero-24** [comment]
Drone is now happy too so this is ready to be merged cc @HLeithner and @wilsonge thanks to all the testers and code writers 👍

**Comment by wilsonge** [comment]
Is there a reason this should be in the main user menu and not just in system administration? As a general rule of thumb i think anything that's user content should be in the menu which this isn't

**Comment by brianteeman** [comment]
I agree with @wilsonge this should find a home in the system control panel

**Comment by alikon** [comment]
well,  with this logic `Joomla! update` too should look for a new home

**Comment by brianteeman** [comment]
@alikon https://github.com/joomla/joomla-cms/pull/23760#issuecomment-467863284

**Pull request closed without merging**
