### PR TITLE
In Joomla 4 - Rename Control Panel as Home Dashboard

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue #29477 .

Summary of Changes

All of the Dashboards in Joomla 4 have xxx Dashboard in the Title bar, except the page linked to by the Home Dashboard menu item, which is entitled Control Panel. This pull request simply changes the page title from Control Panel to Home Dashboard. There are 11 occurrences of "Home Dashboard" and 8 occurrences of "Control Panel". After applying this pull request there is 1 occurrence of "control panel" which refers to the hosting control panel.

Testing Instructions

Select Home Dashboard from the Administrator menu.

Actual result BEFORE applying this Pull Request

The page title is Control Panel

Expected result AFTER applying this Pull Request

The page title is Home Dashboard

Documentation Changes Required

The Help screen changes are in hand - that is where this anomaly came to light. There are likely to be other mentions of Control Panel in Tutorials.

### CODE REVIEW

**Comment by ceford** [comment]
I do not understand why there are conflicts. The two files concerned just have Home Dashboard in place of Control Panel in translation strings. Could someone explain?

**Comment by brianteeman** [comment]
The problem most likely is that your own branch was not completely up to date

**Comment by infograf768** [comment]
I have some difficulties accepting to rename the cpanel component as Home Dashboard component...
Changing the Control Panel title page to Home dashboard may be fine, but the component IS cpanel.

**Comment by ceford** [comment]
> I have some difficulties accepting to rename the cpanel component as Home Dashboard component...
> Changing the Control Panel title page to Home dashboard may be fine, but the component IS cpanel.

I thought about that and don't disagree. However, I think the only place the component is referred to by name is in the Extensions: Manage page. If you select by Status=Protected and Type=Component you will see Articles in the list. But there is no Articles component. And there are several more names that do not correspond to components.

**Comment by brianteeman** [comment]
> Changing the Control Panel title page to Home dashboard may be fine, but the component IS cpanel.

So what. The component is com_content but we call it articles

Just another spurious reason to block any change when it might create some work for a translator

**Comment by wilsonge** [comment]
This seems much more logical to me to make our naming consistent across the backend

**Comment by ceford** [comment]
Thanks guys. I will try to get it right first time in future.

**Comment by richard67** [comment]
@wilsonge System tests in the 4.0-dev branch are consistently failing now, and I think it could be related to this PR. After the installation, the test browser simulation seems not to find the statistics alert to close it, This could be due to changed page title. See screenshot of the test: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30680/system-tests/35473/InstallCest.configureJoomla.mysql.fail.png

**Comment by richard67** [comment]
@wilsonge I am right: See file `./libraries/vendor/joomla-projects/joomla-browser/src/Locators/Locators.php` line 138:
`public $adminControlPanelText = 'Control Panel';`.

Does this have to be fixed upstream?

**Comment by richard67** [comment]
@ceford For you as explanation: The "joomla-browser" is a tool which we use for running system tests. It still assumes that the page title of the Home Dasboard is "Control Panel", and so the system test can't find the statistics alert to be closed after installation. So the system test fails at this point.

**Comment by wilsonge** [comment]
Thanks for flagging @richard67 . Hopefully https://github.com/joomla/joomla-cms/commit/c41e9bf99cd7c8f84ec3fb23534537ce9d10b579 should be the fix. Just watching the tests run through now

**Pull request merged**
