### PR TITLE
[4] Empty State for Checking for updates

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Empty State for com_installer - the Updates page. 

DEPENDS ON AND REQUIRES THE CHANGES IN https://github.com/joomla/joomla-cms/pull/33471 AS WELL 

### Testing Instructions

Apply Pr. Click buttons. 

### Actual result BEFORE applying this Pull Request

Screenshot 2021-05-01 at 20 43 00

### Expected result AFTER applying this Pull Request

Screenshot 2021-05-01 at 20 42 05

### Documentation Changes Required

screenshots

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on cb2fd3d67686401dd8b675afab964984bb3788d3<br /><br />

After applying #33747 & #33471 using patchtester got:

image


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by PhilETaylor** [comment]
Correct, looks like the language file was not added to the right branch for some reason - I have added it now. Thanks for testing.

**Comment by ChristineWk** [comment]
Had the same result before, as @sandramay0905. Now, with added language file, it's OK.
Checked with both Patches applied. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 080aa4675bd17335abe64d7a99b44bced724a82b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by PhilETaylor** [comment]
> Had the same result before, as @sandramay. Now, with added language file, it's OK.

Sorry for wasting your time before, I was working on 2 different development workstations in 2 locations and 4 branches at the same time and I missed adding this language to the right branch. Sorry.

**Comment by ChristineWk** [comment]
It's OK, take a sip of coffee in between :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 080aa4675bd17335abe64d7a99b44bced724a82b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33474">issues.joomla.org/tracker/joomla-cms/33474</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR, see issue #33477 .

**Comment by richard67** [comment]
I've updated the branch to latest 4.0-dev to get rid of the unrelated javascript-cs error in drone and restored the previous test results in the issue tracker.

**Comment by PhilETaylor** [comment]
drone failed with something to do with media manager..

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
