### PR TITLE
[4.0] Normalise display of searchtools specific fields for menu items and multilingual associations managers

### PR DESCRIPTION
**Pull request by infograf768**
Redoing https://github.com/joomla/joomla-cms/pull/19076 but this time just to align the separate fields to the left of the Managers (LTR) and to the right (RTL) as it is done for other managers who have only one separate field (Template styles, Installed languages)

### Summary of Changes
Correcting Associations and Menu items searchtools Layouts
Correcting searchtools css to enable custom class when 2 specific fields.

### Testing Instructions
Install J as multilingual (You may have to do all manually since some stuff is broken with workflow.)
Create menu items and categories tagged to a language. ATM one can't create articles.
Display the Menu items Manager.
Display the Multilingual associations Manager

**MAKE SURE to delete** the `com_associations/layouts/joomla/searchtools/default/bar.php`

**PatchTester : NO. Needs npm install.**

### Before patch
screen shot 2018-08-13 at 08 43 35

screen shot 2018-08-13 at 08 44 51

### After patch
screen shot 2018-08-13 at 08 36 48

screen shot 2018-08-13 at 08 36 19

RTL
screen shot 2018-08-13 at 08 39 07

screen shot 2018-08-13 at 08 40 07

### CODE REVIEW

**Comment by brianteeman** [comment]
It works for me on menu items but on associations I am seeing double
chrome_2018-08-13_11-21-42

**Comment by brianteeman** [comment]
wait I forgot to run npm -

**Comment by infograf768** [comment]
also, MAKE SURE to delete the com_associations/layouts/joomla/searchtools/default/bar.php

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3257823c4826c3c5c131dc2cc3b5b8c190bef6f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21581">issues.joomla.org/tracker/joomla-cms/21581</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
