### PR TITLE
[4.0] Language strings in CLI

### PR DESCRIPTION
**Pull request by brianteeman**
Nothing major just tweaking the case and tense to be consistent on a few messages

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd0230caa27906ce5bc9dc9a28f2db34a1cd1351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25691">issues.joomla.org/tracker/joomla-cms/25691</a>.</sub>

**Comment by richard67** [comment]
Screenshot for "After" seems not to be up to date.

**Comment by brianteeman** [comment]
possibly not

**Comment by richard67** [comment]
Possibly yes: It shows 'Cleans expired cache entries', but in code is 'Clean expired cache entries'. Just 1 example.

**Comment by brianteeman** [comment]
the code is the truth

**Comment by richard67** [comment]
I know, but correct testing instructions (including screenshots) are always good.

**Comment by richard67** [comment]
With the PR applied, the output is still `database:export                 Exports the database`.

I know, this PR did not touch that code, but the screenshot showed so, and now the output is still inconsistent.

**Comment by brianteeman** [comment]
Thats because its in the vendor folder and I need to submit that upstream

**Comment by richard67** [comment]
Unbenannt

**Comment by richard67** [comment]
Ah, I see. Will you do that, submitt to upstream?

**Comment by brianteeman** [comment]
its already done

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bd0230caa27906ce5bc9dc9a28f2db34a1cd1351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25691">issues.joomla.org/tracker/joomla-cms/25691</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25691">issues.joomla.org/tracker/joomla-cms/25691</a>.</sub>

**Comment by brianteeman** [comment]
The changes required upstream have been merged

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
