### PR TITLE
Joomla 3.9.3 Part 1

### PR DESCRIPTION
**Pull request by wilsonge**
First part of Merging Joomla 3.9.3 - all of January's commits

Merge with a merge commit. don't squash or rebase

### CODE REVIEW

**Comment by infograf768** [comment]
@wilsonge
Class 'JEventDispatcher' not found when Checkin items

**Comment by infograf768** [comment]
The code is present in CheckinModel.php and Table.php

**Comment by infograf768** [comment]
for the Checkin Model, looks straightforward
```
diff --git a/administrator/components/com_checkin/Model/CheckinModel.php b/administrator/components/com_checkin/Model/CheckinModel.php
index 44b819b..4688537 100644
--- a/administrator/components/com_checkin/Model/CheckinModel.php
+++ b/administrator/components/com_checkin/Model/CheckinModel.php
@@ -92,6 +92,4 @@
 		$results = 0;
 
-		$dispatcher = \JEventDispatcher::getInstance();
-
 		foreach ($ids as $tn)
 		{
@@ -120,5 +118,5 @@
 			{
 				$results = $results + $db->getAffectedRows();
-				$dispatcher->trigger('onAfterCheckin', array($tn));
+				Factory::getApplication()->triggerEvent('onAfterCheckin', array($tn));
 			}
 		}
```

Not sure for Table.php as we also have a `$this->getDispatcher()->dispatch('onTableAfterCheckin', $event);`

```
		$this->getDispatcher()->dispatch('onTableAfterCheckin', $event);

		//$dispatcher = \JEventDispatcher::getInstance();
		Factory::getApplication()->triggerEvent('onAfterCheckin', array($this->_tbl));
```

**Comment by wilsonge** [comment]
Thanks! Patched the checking as suggested with https://github.com/joomla/joomla-cms/commit/0fcf184761013bd157085df37b2dfe6310923d36 - I need to investigate the other one. `onTableAfterCheckin` would have been new in j4. so we'll need to rename it to the new j3 one. But that involves a little bit more work because of the event class used

**Pull request merged**
