### PR TITLE
Show loading view in installer component properly

### PR DESCRIPTION
**Pull request by magnussinger**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37516

Note: this PR is the rebase to 4.1-dev for this PR: https://github.com/joomla/joomla-cms/pull/37538 (had to create a new one because I messed something up on the other one)

### Summary of Changes
When removing the "hidden" class from the loading view in the installer component in the inspector, this view is now properly positioned

### Testing Instructions
Go to the extension installer, open the inspector and search for the div with the ID "loading", then remove the "hidden" class from it

### Actual result BEFORE applying this Pull Request
The loading view was positioned below the main content and was invisible

### Expected result AFTER applying this Pull Request
The loading view is now visible and properly positioned

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 01bed1d4549f9167b68f5af8799bf3f5e0551d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37570">issues.joomla.org/tracker/joomla-cms/37570</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you test this PR, too? It's the same as #37538 , but this time for the 4.1-dev branch. Thanks in advance.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 01bed1d4549f9167b68f5af8799bf3f5e0551d0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37570">issues.joomla.org/tracker/joomla-cms/37570</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37570">issues.joomla.org/tracker/joomla-cms/37570</a>.</sub>

**Comment by laoneo** [comment]
Thanks!!

**Pull request merged**
