### PR TITLE
Miscellaneous Doc Block Tweaks

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes
- Removes links to the docs wiki for JTable; many of these don't exist or represent the Joomla 1.5 API
- Changes links for `php.net` to consistently use the `https://secure.php.net` mirror
- Changes all GitHub links to use https to avoid a needless redirect when the API site's docs are compiled
- Other miscellaneous link updates to remove needless redirects
- Minor formatting tweaks on some JTable doc blocks (this mostly impacts how some stuff renders when the API site's compiled)
#### Testing Instructions

Review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a00e0f382ce97c5a91c2e06b6109b2fd5faf2299<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on a00e0f382ce97c5a91c2e06b6109b2fd5faf2299<br /><br />Looks ok from Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Comment by zero-24** [comment]
@mbabker we have a travis error here:

```
1) JDatabaseIteratorPostgresqlTest::testForEach with data set #0 ('title', '#__dbtest', null, 'stdClass', 0, 0, array(stdClass Object (...), stdClass Object (...), stdClass Object (...), stdClass Object (...)), null)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => stdClass Object (
-        'title' => 'Testing'
+        'title' => 'Testing2'
     )
     1 => stdClass Object (
-        'title' => 'Testing2'
+        'title' => 'Testing3'
     )
     2 => stdClass Object (
-        'title' => 'Testing3'
+        'title' => 'Testing4'
     )
     3 => stdClass Object (
-        'title' => 'Testing4'
+        'title' => 'Testing'
     )
 )
```

But the funny thing is this PR just change doc blocks?! Maybe we need just to restart the travis job?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on a00e0f382ce97c5a91c2e06b6109b2fd5faf2299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Comment by brianteeman** [comment]
Set back to RTC - no idea why it says there are failures with Travis - it looks ok to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10925">issues.joomla.org/joomla-cms/10925</a>.</sub>

**Pull request merged**
