### PR TITLE
[#26922] fix - Repeatable-table field - UX issue

### PR DESCRIPTION
**Pull request by snehal0904**
Pull Request for Issue # .

### Summary of Changes
Added "table-responsive" class for repeatable table field

### Testing Instructions
Go to the plugin: Fields radio
Add multiple options to a radio field.
Check add, remove button UX

### CODE REVIEW

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on faa5790f255b8ba65ac9ec4b9c9bcb9b033f2ea5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26923">issues.joomla.org/tracker/joomla-cms/26923</a>.</sub>

**Comment by AdityaTaware** [comment]
I have tested this item :white_check_mark: successfully on faa5790f255b8ba65ac9ec4b9c9bcb9b033f2ea5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26923">issues.joomla.org/tracker/joomla-cms/26923</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26923">issues.joomla.org/tracker/joomla-cms/26923</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
