### PR TITLE
[4.2] Use the internal database instance in the menu table

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Table classes should use the internal database object and not from Factory.

### Testing Instructions
- Create a menu item
- Trash the menu item
- Set the filter to trashed in the menu items list
- Select all menu items
- Hit the trash button

### Actual result BEFORE applying this Pull Request
The menu item is deleted.

### Expected result AFTER applying this Pull Request
The menu item is deleted.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5a3700887fd116cca5a9c5fc3508d0fc68cf5a77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37613">issues.joomla.org/tracker/joomla-cms/37613</a>.</sub>

**Comment by SumCompanyInc** [comment]
I have tested this item :white_check_mark: successfully on 5a3700887fd116cca5a9c5fc3508d0fc68cf5a77<br /><br />was successful here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37613">issues.joomla.org/tracker/joomla-cms/37613</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37613">issues.joomla.org/tracker/joomla-cms/37613</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
