### PR TITLE
Notifiation of software update not sent 

### PR DESCRIPTION
**Pull request by ghost**
### Summary of Changes

 Get JRule data rather than JRule object
### Testing Instructions

Apple patch and check result

### CODE REVIEW

**Comment by zero-24** [comment]
@tstahl-git it looks like this PR is broken and include some invalid commits how can we reproduce the error / problem as my sites send the messages out since the plugin was added.?

**Comment by tstahl-git** [comment]
@zero-24 yes, something went wrong. The only file to patch should be [updatenotification.php](https://github.com/joomla/joomla-cms/commit/0f167746d8cb1b0c92a9dc6c5803a79f27d3dd6e "patch").
I have 2 server installations where notification won't work.
I made a fresh installation from the staging branch with the same result.
With the proposed patch for updatenotification.php the notification works for me.
The origin line "298 $rawGroups = $rules['core.admin'];" returns a JRule object and not an array.
Please investigate.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12614">issues.joomla.org/tracker/joomla-cms/12614</a>.</sub>

**Comment by zero-24** [comment]
Ok i can confirm the problem and i have created a new PR that is cleaned up at #12763

**Comment by zero-24** [comment]
Thanks for reporting!

**Pull request closed without merging**
