### PR TITLE
Error trapping in com_cache

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Gracefully handle cache related errors in com_cache versus hitting the error page.

1. Catch some exceptions when trying to read data from the cache store and display a relevant message related to the failure.

2. Clean and purge operations should also catch these exceptions to notify the calling code of an error state.  The controller methods are already checking for boolean false returns so the error handling already exists.

3.  Remove a useless casting from boolean to integer.

### Testing Instructions

When the cache can't be reached for read, clean, or purge operations, the error conditions should be gracefully handled versus fatal errors.

### Documentation Changes Required

N/A

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by csthomas** [comment]
On test at got:
joomla_win_3 6 6

`getData` is called 3 times:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_cache/models/cache.php#L210
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_cache/models/cache.php#L225
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_cache/views/cache/view.html.php#L40

**Comment by csthomas** [comment]
Sometimes I think that joomla should remove `empty()` function from whole project and replace it with `!==` or similar.
For me `if (empty($var))` is equal to `if (isset($var) && $var)`

**Comment by mbabker** [comment]
Displaying the message three times probably means there's a way to optimize the code to not run other functions if fetching the base data fails, but I'd consider that outside scope of this PR.  The main thing to accomplish here is to block an unhandled Exception thrown by reading from the cache store and have a semi-graceful fallback.

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 76179e71af3bae1cf3e43cdd466d26e4c10de293<br /><br />I set up cache handler as memcached and turn it off in joomla. Then go to clear cache and I saw message as I mentioned before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13521">issues.joomla.org/tracker/joomla-cms/13521</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 76179e71af3bae1cf3e43cdd466d26e4c10de293<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13521">issues.joomla.org/tracker/joomla-cms/13521</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13521">issues.joomla.org/tracker/joomla-cms/13521</a>.</sub>

**Pull request merged**
