### PR TITLE
[4.0] Irrelevent Codes and Comments removed

### PR DESCRIPTION
**Pull request by saumyasarkar11**
Pull Request for Issue #32725.

### Summary of Changes

1. && $this->item->pagination removed from https://github.com/joomla/joomla-cms/blob/4.0.0-beta7/components/com_content/tmpl/article/default.php#L43.

2. Comment and brackets around OR removed from https://github.com/joomla/joomla-cms/blob/4.0.0-beta7/components/com_content/tmpl/article/default.php#L49-L51.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by joomdonation** [comment]
Your PR contains more changes than needed. You should make PR base on the code of latest 4.0-dev branch:

- You reverted the changes in this merged PR https://github.com/joomla/joomla-cms/pull/32713/
- As stated in the issue, the comment should be there, it should not be removed

**Comment by ReLater** [comment]
> As stated in the issue, the comment should be there, it should not be removed

That's wrong. In the issue.

> I think it's there from an older version, _**can be removed**_

**Comment by saumyasarkar11** [comment]
@ReLater please look through this pull request.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 7c104760c20e501fe13ffd268f15ae8a315d231b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32745">issues.joomla.org/tracker/joomla-cms/32745</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :red_circle: unsuccessfully on 7c104760c20e501fe13ffd268f15ae8a315d231b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32745">issues.joomla.org/tracker/joomla-cms/32745</a>.</sub>

**Comment by saumyasarkar11** [comment]
> I have tested this item  unsuccessfully on [7c10476](https://github.com/joomla/joomla-cms/commit/7c104760c20e501fe13ffd268f15ae8a315d231b)
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/32745](https://issues.joomla.org/tracker/joomla-cms/32745).

Can you just elaborate on this.....Would be helpful

**Comment by ReLater** [comment]
Sorry! Confusion on my side. 
That one is correct but closed. https://github.com/joomla/joomla-cms/pull/32746/

This one here (32745) is wrong because you included changes that are already merged with this pr: https://github.com/joomla/joomla-cms/pull/32713/

**Comment by saumyasarkar11** [comment]
> Sorry! Confusion on my side.
> That one is correct but closed. #32746
> 
> This one here (32745) is wrong because you included changes that are already merged with this pr: #32713

So i'm opening that one.

**Pull request closed without merging**
