### PR TITLE
4.0 dev- Bloked Application lock Pull Request 

### PR DESCRIPTION
**Pull request by adj9**
Bloked Application lock Pull Request with Joomla! Patch Tester [https://github.com/joomla-extensions/patchtester](url)

Hello everybody...
I had a problem applying a patch on Joomla! 4 dev-1.

Step1 - Configuring the component for GitHub.

Step2 - The example Pull Request [https://github.com/joomla/joomla-cms/pull/28632](url).

Step3 - With Patch Tester I entered the code and applying it I have this error: The patch could not be applied because it would break the site. Check the pull request to see if it is up-to-date.

Step4 - I made a custom update of J! with the link: [https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28632/downloads/31120/pr_list.xml](url).

Result: The error persists even with other pull requests.

How can I act?

Thank you

### CODE REVIEW

**Comment by infograf768** [comment]
This PR is targeted at the wrong "staging" branch

**Comment by alikon** [comment]
thanks for you contribution
but it seems that somethings is it really wrong with your pr
please double check that you are submitting on the correct branch

**Comment by richard67** [comment]
This Pull Request is wrong, it wants to merge the author's 4.0-dev branch into the CMS' staging branch.

**Comment by adj9** [comment]
> Bloked Application lock Pull Request with Joomla! Patch Tester [https://github.com/joomla-extensions/patchtester](url)
> 
> Hello everybody...
> I had a problem applying a patch on Joomla! 4 dev-1.
> 
> Step1 - Configuring the component for GitHub.
> 
> Step2 - The example Pull Request [https://github.com/joomla/joomla-cms/pull/28632](url).
> 
> Step3 - With Patch Tester I entered the code and applying it I have this error: The patch could not be applied because it would break the site. Check the pull request to see if it is up-to-date.
> 
> Step4 - I made a custom update of J! with the link: [https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28632/downloads/31120/pr_list.xml](url).
> 
> Result: The error persists even with other pull requests.
> 
> How can I act?
> 
> Thank you

**Pull request closed without merging**
