### PR TITLE
broken links in sample data

### PR DESCRIPTION
**Pull request by brianteeman**
Sample learn and sample test had some broken links to the JED

Pull Request for Issue #15758

### CODE REVIEW

**Comment by Quy** [comment]
Change `https://extensions.joomla.org/category/marketing-sharing/` to `https://extensions.joomla.org/category/marketing/`.

**Comment by brianteeman** [comment]
@quy disagree - not sure where you got that link but if akeeba backup is the first item then its the wrong stuff

**Comment by Quy** [comment]
Your PR has the link [https://extensions.joomla.org/category/marketing-sharing](https://extensions.joomla.org/category/marketing-sharing) which has the Akeeba backup. The suggested URL does not and is a valid category.

**Comment by brianteeman** [comment]
sorry - my mistake - i misread the report

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fbafd3a4986e488043eb225341d706d9093e1252<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16012">issues.joomla.org/tracker/joomla-cms/16012</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Quy how you have test PR?

**Comment by Quy** [comment]
Code review and also manually go to each revised link in my browser.

**Comment by franz-wohlkoenig** [comment]
Thanks, so there is no Way to test by Installation.

**Comment by brianteeman** [comment]
@franz-wohlkoenig download and install joomla using this zip https://github.com/brianteeman/joomla-cms/archive/sample-park.zip

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on fbafd3a4986e488043eb225341d706d9093e1252<br /><br />- Link "comments" > https://extensions.joomla.org/extensions/contacts-and-feedback/articles-comments
- Link "interacting with social network sites" > https://extensions.joomla.org/category/social-web
- Link "tagging" > https://extensions.joomla.org/category/content-sharing
- Link "keeping in contact with your readers" > https://extensions.joomla.org/category/marketing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16012">issues.joomla.org/tracker/joomla-cms/16012</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by elkuku** [comment]
@franz-wohlkoenig note that we have added a link for such "edge cases" :wink: 
download

**Comment by franz-wohlkoenig** [comment]
@elkuku thanks for Hint, haven't noticed before.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
