### PR TITLE
Route the link in the redirect plugin

### PR DESCRIPTION
**Pull request by bembelimen**
When redirecting an internal link, call JRoute::_(...)

Test:
- Activate the sef options in the global configuration
- Activate the redirect plugin
- Look for a menu item ID
- Create a redirect and add as goal: index.php?Itemid=xxx where "xxx" is the menu item ID (source could be anything, but we assume "foobar")
- Call www.your-domain.tld/foobar
- Redirect is index.php?Itemid=xxx
- Apply patch
- Call www.your-domain.tld/foobar again

### CODE REVIEW

**Comment by infograf768** [comment]
Looks fine here.

**Comment by Hackwar** [comment]
:+1: Fine with me. :smile:

**Comment by wilsonge** [comment]
Someone should test a sef url passed in will remain unchanged. Really busy but will try and test tonight if possible to make sure that is unaffected by this change.

**Comment by Kubik-Rubik** [comment]
Works as described. Thank you @bembelimen!

@wilsonge Yes, it remains unchanged.

**Comment by wilsonge** [comment]
Was about to test this one now. Thanks @Kubik-Rubik !!

**Pull request merged**
