### PR TITLE
[4.0] COM_MENUS_ITEM_ROOT

### PR DESCRIPTION
**Pull request by brianteeman**
The term used in com_categories is "No parent" which makes perfect sense

The term used in com_menus is "Menu Item Root" which is quite difficult language to understand

This PR changes that so that they both use the same simple term "No parent"

### Before
image

### After
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9433460ef173061d4bc5ca0fb035f2b02a7112fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31626">issues.joomla.org/tracker/joomla-cms/31626</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9433460ef173061d4bc5ca0fb035f2b02a7112fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31626">issues.joomla.org/tracker/joomla-cms/31626</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
