### PR TITLE
[CODEMIRROR] Two new font options, highlight selection matches.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
#### Summary of Changes

CodeMirror updated to 5.14.2 and additional addons bundled.
Plugin has a new option to highlight the selected word.
Two new font options: Roboto Mono and Rubik Mono One - one of them is pretty good, the other is awful. You decide!
#### Testing Instructions

Go to the codemirror plugin options and switch on `Highlight Selection Matches`. Then, edit some content with codemirror. Instances of the word your cursor is on should be highlighted throughout the document.

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated title to show codemirror<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10102">issues.joomla.org/joomla-cms/10102</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8a0573a01441206e6e303ca4e626d0d16cb2da3d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10102">issues.joomla.org/joomla-cms/10102</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 8a0573a01441206e6e303ca4e626d0d16cb2da3d<br /><br />>Two new font options: Roboto Mono and Rubik Mono One - one of them is pretty good, the other is awful. You decide!

Agree. The seccond one is awful the first one is nice ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10102">issues.joomla.org/joomla-cms/10102</a>.</sub>

**Comment by brianteeman** [comment]
RTC - set milestone to 352 as it is a library update as well as the new feature<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10102">issues.joomla.org/joomla-cms/10102</a>.</sub>

**Pull request merged**
