### PR TITLE
[4.0] Patch for incorrect validation message

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/19724.

### Summary of Changes
Change /media/system/js/validate.js so that an invalidate input get the correct message.

### Testing Instructions
Insert an invalid value in a field. 
For example insert an invalid email address in the email field while installation (see https://github.com/joomla/joomla-cms/issues/19724) or in the email field when you create a new user.

### Expected result
You get a message that says, that your input is invalid.

### Actual result
You get a message that says that the field is empty.

### Documentation Changes Required
No

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by proman24** [comment]
Hey, have a look at PR #19736<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19732">issues.joomla.org/tracker/joomla-cms/19732</a>.</sub>

**Comment by ahotzler** [comment]
I have successfully tested this patch

**Comment by ghost** [comment]
@ahotzler please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19732)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by ahotzler** [comment]
I have tested this item :white_check_mark: successfully on 262bca23b3e1ddb596a891a9a2d0b4695899fde7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19732">issues.joomla.org/tracker/joomla-cms/19732</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 262bca23b3e1ddb596a891a9a2d0b4695899fde7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19732">issues.joomla.org/tracker/joomla-cms/19732</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19732">issues.joomla.org/tracker/joomla-cms/19732</a>.</sub>

**Pull request merged**
