### PR TITLE
[4.0] Namespace mod articles category

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Namespace mod articles category

### CODE REVIEW

**Comment by brianteeman** [comment]
450 | ERROR | Arguments with default values must be at the end of the argument

**Comment by C-Lodder** [comment]
Cannot replicate this at all. PR working fine for me.

Which page are you getting this error on?

**Comment by brianteeman** [comment]
i have j4 installed with the sample test data

on the left hand menu there is a menu option for the module that displays the modulle in an article
there are 4 tags displayed
red - error
yellow - error
green - ok
lime - ok

**Comment by brianteeman** [comment]
sorry that comment was on the wrong pr - deleted it

**Comment by brianteeman** [comment]
Sorry I should have said it was an issue reported by drone

**Comment by C-Lodder** [comment]
No idea what that's on about. I haven't changed line 450 and the code for it seems perfectly fine

**Comment by wilsonge** [comment]
@mbabker just take the b/c here to fix drone do you think?

**Comment by mbabker** [comment]
It's a module.  Just make the B/C break and be done with it.

**Pull request merged**
