### PR TITLE
[4.0][mod_stats] - frontend like admin module

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #28717 .

### Summary of Changes
removed join with the workflows table

### Testing Instructions
#28717

### Expected result
works as admin module

### Actual result
don't work

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 60f1572fe17a2d5eeacc2bfdde03ec753511ad58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28723">issues.joomla.org/tracker/joomla-cms/28723</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 60f1572fe17a2d5eeacc2bfdde03ec753511ad58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28723">issues.joomla.org/tracker/joomla-cms/28723</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28723">issues.joomla.org/tracker/joomla-cms/28723</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
I am not convinced simply removing the workflow stuff is correct - it must have been put there for a reason

**Comment by richard67** [comment]
@brianteeman As far as I remember the workflow stuff here was the remainder of an intermediate phase of development which was later rolled back so that `state` column of the `#__content` table was used again, but I might be wrong, so it would be cool if @bembelimen could have a look and comment.

**Comment by bembelimen** [comment]
The state column is still there for B/C reasons, but [is general ignored](https://github.com/joomla/joomla-cms/pull/21702). I don't care, if the clean version (join over WF) or the state-version is used. I guess the state field will never disappear, so it doesn't matter.

**Pull request merged**
