### PR TITLE
[4.0] hasTooltip

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the class from everywhere that it has no effect being applied to a title. This will make it easier to find the cases where hasTooltip is being used with `HTMLHelper::_('tooltipText'` and to decide on the most appropriate accessible solution.

Code review should be enough

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e1f500e27e3948285fbe48d8fd553e45c2cf0a41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25215">issues.joomla.org/tracker/joomla-cms/25215</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8de7a5e2e49f52087b5b3f9a46356acc40864dda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25215">issues.joomla.org/tracker/joomla-cms/25215</a>.</sub>

**Comment by brianteeman** [comment]
Conflicts resolved

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
@wilsonge it would be great if this could be merged

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks - I can continue the cleanup now

**Pull request merged**
