### PR TITLE
[4.0] Namespace JFormRule uses

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Namespace `JFormRule` uses.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ced385ba49f8a6c6ac05af9b7a4db738e4d156a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25515">issues.joomla.org/tracker/joomla-cms/25515</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ced385ba49f8a6c6ac05af9b7a4db738e4d156a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25515">issues.joomla.org/tracker/joomla-cms/25515</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
