### PR TITLE
[3.10] Apply PHP 5.3 combat changes to the core code and lessphp + phpmailer

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Apply PHP 5.3 combat changes to the core code and lessphp + phpmailer 

### Testing Instructions

make sure the CMS works on php5.3 or do a code review

### Actual result BEFORE applying this Pull Request

some errors on php5.3

### Expected result AFTER applying this Pull Request

no issues on php 5.3 any more

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
@zero-24 The PHP 5.3. check did fail, but not due to what you wanna do with this PR, it just failed with the usual, randomly appearing error with connecting to MySQL.

I wrote in the other PR that the issue with the commas had nothing to do with PHP versions. This might be the case for array syntax `array(1,2,3,)` or in newer PHP versions `[1,2,3,]`, but the calls fixed in the other PR #35091 were not these array calls but normal calls to functions, and there the comma is wrong in any case as far as I know.

So I do not expect any benefit from this PR here except that we have system tests also for 5.3. But I don't think they will be different to 5.4 in their result.

**Comment by zero-24** [comment]
This page here has to be reviewed, some are not relevant some are: https://ci.joomla.org/joomla/joomla-cms/46488/1/4

> but the calls fixed in the other PR #35091 were not these array calls but normal calls to functions, and there the comma is wrong in any case as far as I know.

Well i did not got any error like the reporter on 7.3ish so it might be legar now i have not checked that.

**Comment by HLeithner** [comment]
You change files directly in the vendor folder which is not allowed.

Please update our forks of lessphp and phpmailer and release a new version

**Comment by zero-24** [comment]
> You change files directly in the vendor folder which is not allowed.
> 
> Please update our forks of lessphp and phpmailer and release a new version

Yes will do it was only to check that there are no more than the ones i found by than.

**Comment by zero-24** [comment]
PRs for the backport repos have been done once merged will update them using composer

**Comment by zero-24** [comment]
I have just removed the drone step for now too and only apply the combat issues here. The drone step has to be checked later again.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
