### PR TITLE
[4.0] filter integer

### PR DESCRIPTION
**Pull request by brianteeman**
In most cases a field with a type of number should also have a filter of integer

For example you can not have 3.7 columns or 1.4 links

This PR updates those fields where a filter was not, if appropriate.

To test either code review or create a blog category menu item and set the column count to 4.1
Before this PR the value saved will be 4.1
After this PR the value saved will be 4

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ce3a109642fb1005971e1bd01d1db95106a62413<br /><br />Test by blog category menu item and column count.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33498">issues.joomla.org/tracker/joomla-cms/33498</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on ce3a109642fb1005971e1bd01d1db95106a62413<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33498">issues.joomla.org/tracker/joomla-cms/33498</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33498">issues.joomla.org/tracker/joomla-cms/33498</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
