### PR TITLE
[4.0][a11y] Improve accessiblity in mod_finder

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Improve a11y by adding role="search" to the form tag.

### Testing Instructions
Add a finder module to your website.
Inspect the souce code before and after patch.

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 49cee0b01af548ee0089c6a3bee4878e66fd1743<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23686">issues.joomla.org/tracker/joomla-cms/23686</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 49cee0b01af548ee0089c6a3bee4878e66fd1743<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23686">issues.joomla.org/tracker/joomla-cms/23686</a>.</sub>

**Comment by wojsmol** [comment]
@zero-24 Please fix rips issues.

**Comment by zero-24** [comment]
Rebooted drone @ http://ci.joomla.org/joomla/joomla-cms/13961

**Comment by zero-24** [comment]
Drone and Rips is happy now.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23686">issues.joomla.org/tracker/joomla-cms/23686</a>.</sub>

**Comment by davidemessia** [comment]
I have tested this item :white_check_mark: successfully on 49cee0b01af548ee0089c6a3bee4878e66fd1743<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23686">issues.joomla.org/tracker/joomla-cms/23686</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
