### PR TITLE
[5.0] actionlogs for custom fields

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Logs fields in the user action logs

### Testing Instructions
clean install of this branch or apply pr and run update sql
create a field
edit a field
check the two actions are in the user action log

### Actual result BEFORE applying this Pull Request
nothing is displayed in the users action log component

### Expected result AFTER applying this Pull Request
Entries displayed with clickable links

_if nothing is displayed then open the actionlogs options and check to see if fields is in the list of loggable extensions and if not then add it._

### Documentation Changes Required
none

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ff1fd066270e8eb44a3c0b70636cd9cbfcba2bdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38221">issues.joomla.org/tracker/joomla-cms/38221</a>.</sub>

👍

**Review by richard67 — APPROVED** [review]
Code review (especially SQL stuff) ok by me.

**Comment by Quy** [comment]
Add to as it is not enabled by default?
https://github.com/joomla/joomla-cms/blob/940bf4bd764afa99bdfd355469438083260fa37a/installation/sql/mysql/base.sql#L182

**Comment by brianteeman** [comment]
> Add to as it is not enabled by default?
> 

Thanks - thought I had done that but obv didnt

**Comment by chmst** [comment]
Tested this in a fresh installation (no update).

It works for fields, but not for field groups. Is this correct?
grafik

And a linguistic question. For a German this looks strange:  User xx performed a check in to  table #__nn

**Comment by Quy** [comment]
Clicking on the field link goes to the last Field section visited. In the screenshot, it is an Article field yet it displays it as a User field.

**Comment by brianteeman** [comment]
> It works for fields, but not for field groups. Is this correct?

Yes - field groups is becond the scope of this pr. I would welcome someone adding support for that. (in other words I failed to achieve it)

> And a linguistic question. For a German this looks strange: User xx performed a check in to table #__nn

I hope this helps you to understand https://developer.joomla.org/en-gb-user-interface-text-guidelines/action-or-description.html

**Comment by brianteeman** [comment]
> Clicking on the field link goes to the last Field section visited. In the screenshot, it is an Article field yet it displays it as a User field.

grrhh - no idea how to address that

**Comment by chmst** [comment]
Thanks. I would say   "I performed a check on a table " not in to a table, but can live with this ;) 

The headline - yes. It probably comes from the context.

**Comment by brianteeman** [comment]
> Thanks. I would say "I performed a check on a table " not in to a table, but can live with this ;)

No - it is specifically a check in

**Comment by chmst** [comment]
@Quy i have an article field. The context correct and the link is /administrator/index.php?option=com_fields&view=field&layout=edit&id=1&context=com_content.article   goes to an article field.

grafik

**Comment by Quy** [comment]
@chmst Now create a User field. Then click on the Article field in the User Action Log. The heading will display it as a User field.

**Comment by chmst** [comment]
@Quy indeed. Seems to depend on the context in the user state.

**Comment by richard67** [comment]
@brianteeman Due to the rebase to 5.0-dev it needs to rename the update SQL scripts. I suggest to rename them to "5.0.0-2023-08-28.sql" because there are other PR's proposed which will already use "5.0.0-2023-08-22.sql" to "5.0.0-2023-08-27.sql". The base name needs to be greater than the one of the greatest update SQL script in the branch, using version_compare, otherwise it will not run on update when updating from a previous 5.0.0-alpha.

**Comment by brianteeman** [comment]
Feel free to do it. I don't use my pc on Sabbath

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on b917bc5f9b31cbdfa38bebc469248c3d4dd9a7c8<br /><br />5.0.0-beta1-dev+pr.29376<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38221">issues.joomla.org/tracker/joomla-cms/38221</a>.</sub>

**Comment by richard67** [comment]
> Feel free to do it. I don't use my pc on Sabbath

@brianteeman Done.

@MacJoom It seems you have tested with a new installation. Could you also test with updating from a previous 5.0.0-alpha or from 4.4? Thanks in advance.

**Comment by MacJoom** [comment]
Works as a Update too. You have to add 'Fields' in the  com_actionlogs options (Events to log), as stated in the instructions

**Comment by richard67** [comment]
@MacJoom Ok, I've restored your test result. Counter was reset after I've renamed the update SQL scripts. Do you think @viocassel 's test result still counts, too? He had tested before the PR was rebased, but after that there haven't been made any changes besides my scripts rename. Not sure if I shall count it and set the PR RTC or if a 2nd actual test would be better. What do you think?

**Comment by MacJoom** [comment]
> @MacJoom Ok, I've restored your test result. Counter was reset after I've renamed the update SQL scripts. Do you think @viocassel 's test result still counts, too? He had tested before the PR was rebased, but after that there haven't been made any changes besides my scripts rename. Not sure if I shall count it and set the PR RTC or if a 2nd actual test would be better. What do you think?

I would prefer another test on 5.0 - his test is over a year old

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 8877476790a4e545f7a67dba5884727a0bb84748<br /><br />PBF23 ‎5.0.0-beta1-dev PHP 8.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38221">issues.joomla.org/tracker/joomla-cms/38221</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38221">issues.joomla.org/tracker/joomla-cms/38221</a>.</sub>

**Comment by HLeithner** [comment]
Seems I missed this thanks

**Pull request merged**
