### PR TITLE
[4.0] npm  packages semver

### PR DESCRIPTION
**Pull request by brianteeman**
This PR updates a few packages that clearly follow semver

### CODE REVIEW

**Comment by jwaisner** [comment]
@brianteeman Is this code review or do we need test results?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27848">issues.joomla.org/tracker/joomla-cms/27848</a>.</sub>

**Comment by wilsonge** [comment]
In terms of the changes to package.json it's fine. just do some basic testing of tinymce loading, choices loading and for a stretch minicolours

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c682404939ae22238dace1ffef456f574242a363<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27848">issues.joomla.org/tracker/joomla-cms/27848</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on c682404939ae22238dace1ffef456f574242a363<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27848">issues.joomla.org/tracker/joomla-cms/27848</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27848">issues.joomla.org/tracker/joomla-cms/27848</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
