### PR TITLE
[4.0] Remove _FRONTEND_LANGUAGE_DESC on the registration page

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
The user registration page displays a constant that was previously deleted. PR removes it completely :).

The problem is in the screenshot.

Screenshot_3

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5cbd7069aca5b160875afecb8d9ea7cfa08a7471<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33666">issues.joomla.org/tracker/joomla-cms/33666</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5e7927cffd165611233167c0b649319dda9b21fa<br /><br />Can someone make the test of @brianteeman  show again at issue tracker?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33666">issues.joomla.org/tracker/joomla-cms/33666</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33666">issues.joomla.org/tracker/joomla-cms/33666</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
