### PR TITLE
Fix Regressions: cancel action broken

### PR DESCRIPTION
**Pull request by Fedik**
Fix Cancel action issue, described in #6662

Important: Test it on latest staging/master

### CODE REVIEW

**Comment by n9iels** [comment]
@test works fine for me, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6664">issues.joomla.org/joomla-cms/6664</a>.</sub>

**Comment by n9iels** [comment]
Just noticed this bug also occurs in the back-end. This patch fix that as well :smiley:

**Comment by infograf768** [comment]
:+1:  This solves the issue here.

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6664">issues.joomla.org/joomla-cms/6664</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
