### PR TITLE
[4.0] webp support

### PR DESCRIPTION
**Pull request by brianteeman**
#34634 added partial support for webp by adding webp to the Legal Image Extensions (File Types) and Legal MIME Types

This PR completes the support for webp by adding webp to the Allowed Extensions

Also adds thumbnail and icon for webp

Makes sure the default values in the xml matches the base.sql

This PR does __not__ add the ability to edit a webp image as I tried to do with #33481 as cropperjs is not compatible with firefox for windows. As a result the edit icon is not displayed for webp images

### After the PR
media

### CODE REVIEW

**Comment by ChristineWk** [comment]
Check 1st Issue-nr. pls. Maybe you meant this: #31048 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34690">issues.joomla.org/tracker/joomla-cms/34690</a>.</sub>

**Comment by brianteeman** [comment]
updated the original post

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on acd772ae1cbc3bc1937ae3925807efa3776b5e9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34690">issues.joomla.org/tracker/joomla-cms/34690</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on acd772ae1cbc3bc1937ae3925807efa3776b5e9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34690">issues.joomla.org/tracker/joomla-cms/34690</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34690">issues.joomla.org/tracker/joomla-cms/34690</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
woohoo

**Pull request merged**
