### PR TITLE
[4.0][com_mails] - wrong GROUP BY

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes 
fixed wrong group by

### Testing Instructions

go to the new component com_mails `yoursite/administrator/index.php?option=com_mails&view=templates
`
### Expected result

no error

### Actual result
sql error wrong `GROUP BY`   on postgresql

### CODE REVIEW

**Comment by wilsonge** [comment]
Codestyle please

**Comment by alikon** [comment]
really ???
you merged this blindly... with no 2 successufull test ... no prepared statement  no quoteName instead of q or qn ..... and you ask me for CS

have a good day

**Comment by wilsonge** [comment]
I didn’t merge it blindly. Various people tested as you can see from the various comments (even if they didn’t give official issue tracker tests). Including myself as I fixed a number of issues related to the html templates before merging.

You also know that I’ve spent various production team meetings (for the last 4-5 months) naming this as the last major feature I’ve wanted to merge before beta (alongside the new backend template)

I am more than happy to fix any regressions it’s introduced. But drone fails often enough. No need to make it fail 100% of the time by introducing silly code style issues that anyone is able to fix in 10 seconds.

Thankyou for drawing attention to this issue. I’ll try to fix it whenever I have time outside of helping you to keep your issue and pull request numbers down

**Comment by alikon** [comment]
Good to know that now we don't need to respect  the rules, cause you personally test  it ,and you, like the other's that have tested this feature, are outside from the simple rule of mark this on the silly issue tracker , which just take less than 10 seconds  ------  and the silly others that instead of only testing on the usual platform, are trying to test it on different platform, and as usual  fixing BUGS which the previous testers don't discovered  , need to follow the rule that some of you are not obliged to follow....
make perfect sense

**Comment by alikon** [comment]
let me spent this 5 secoonds

**Comment by brianteeman** [comment]
Comment on the code please not the person.

**Comment by alikon** [comment]
@brianteeman   sorry but sometimes it seems that code is not written in a programming language but instead from someone more than someone else

**Comment by wilsonge** [comment]
Thankyou for sorting it out

**Pull request merged**
