### PR TITLE
[4.0] Rename LeagcyModelLoaderTrait

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Corrects typo in `Joomla\CMS\MVC\Model\LeagcyModelLoaderTrait` class name.

### Testing Instructions

Code review?

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b792878f2a7f956c585e3cc711a88772120ea109<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28028">issues.joomla.org/tracker/joomla-cms/28028</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b792878f2a7f956c585e3cc711a88772120ea109<br /><br />by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28028">issues.joomla.org/tracker/joomla-cms/28028</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28028">issues.joomla.org/tracker/joomla-cms/28028</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
