### PR TITLE
[4.0] Extensions->Update Sites toolbar actions

### PR DESCRIPTION
**Pull request by brianteeman**
Following on from other components this PR adds an action dropdown button for
- Enable
- Disable
- Delete
- Checkin

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 447f0c1257db98f4a57fff116de3d43a436c16a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26809">issues.joomla.org/tracker/joomla-cms/26809</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 447f0c1257db98f4a57fff116de3d43a436c16a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26809">issues.joomla.org/tracker/joomla-cms/26809</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26809">issues.joomla.org/tracker/joomla-cms/26809</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
