### PR TITLE
[4.1] Module >> Menu Assignment >> chevrons not working correctly fix

### PR DESCRIPTION
**Pull request by vorayash**
Pull Request for Issue #37593 

### Summary of Changes
To select chevrons, 'i' was used instead of 'span' because of that it was not selecting anything.

### Testing Instructions
Go to Modules >> any module >> Menu Assignment tab >> Only on the pages selected
Click on one or two menus to expand them
The chevrons on the left change from .icon-chevron-right to .icon-chevron-down correctly
Now click on >> Expand the Menu Subtrees >> None

### Actual result BEFORE applying this Pull Request
The chevrons do not change so some are incorrect

### Expected result AFTER applying this Pull Request
The chevrons change correctly.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c059f3fb95994e4276c164c01c6866631fb735f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37734">issues.joomla.org/tracker/joomla-cms/37734</a>.</sub>

**Comment by SumCompanyInc** [comment]
I have tested this item :white_check_mark: successfully on c059f3fb95994e4276c164c01c6866631fb735f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37734">issues.joomla.org/tracker/joomla-cms/37734</a>.</sub>

**Comment by saraheagle** [comment]
Fab, thank you very much 😄

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37734">issues.joomla.org/tracker/joomla-cms/37734</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
