### PR TITLE
[5.1] Api redirect tests

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the grammar for the description of a redirect test.

simple PR that can be "tested" by code review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on b3085669d090fcba627873f80e2159f6009d0101<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42522">issues.joomla.org/tracker/joomla-cms/42522</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b3085669d090fcba627873f80e2159f6009d0101<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42522">issues.joomla.org/tracker/joomla-cms/42522</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42522">issues.joomla.org/tracker/joomla-cms/42522</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Silly question: Why for 5.1-dev? As far as I could see on a quick view, the file is also present on 5.0-dev.

**Comment by brianteeman** [comment]
see previous answer

**Comment by LadySolveig** [comment]
Thank you @brianteeman and also to the reviewers @sandewt and @richard67 !

**Pull request merged**
