### PR TITLE
Create Admin Menu type with Hathor

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #14579  .

### Summary of Changes
Add the field selector to allow the creation of menu types using the hathor template

### After PR

screenshotr14-24-32

See #14579 for the Before screenshots

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 104e97229f15fd0a901193f0f36398fdeec4e8af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14580">issues.joomla.org/tracker/joomla-cms/14580</a>.</sub>

**Comment by tuts-22** [comment]
I have tested this item :white_check_mark: successfully on 104e97229f15fd0a901193f0f36398fdeec4e8af<br /><br />The code works absolutely fine!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14580">issues.joomla.org/tracker/joomla-cms/14580</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14580">issues.joomla.org/tracker/joomla-cms/14580</a>.</sub>

**Pull request merged**
