### PR TITLE
[4.2]Update create-translation-pull-request-v4.yml

### PR DESCRIPTION
**Pull request by brianteeman**
update for  4.2

### CODE REVIEW

**Comment by zero-24** [comment]
I would say this should not be merged as the workflow only runs on the default branch anyway. At the time 4.2 will be made the default branch this will be updated and changing it now only adds more pain when merging the changes up from the other branches without any benefit.

**Comment by brianteeman** [comment]
> I would say this should not be merged as the workflow only runs on the default branch anyway.

point taken

> At the time 4.2 will be made the default branch this will be updated and changing it now only adds more pain when merging the changes up from the other branches without any benefit.

Why - is it automated? If not then whats the harm in doing it now. At least it wont get forgotten

**Comment by zero-24** [comment]
> Why - is it automated? 

Merging from 3.10 -> 4.1 -> 4.2 is at no point automated and a manuall task done by the release leads as this involves fixing the merge conflicts too.

> If not then whats the harm in doing it now. At least it wont get forgotten

Well I suggested not decided that this should not be merged but I would like to make the person tempting to merging here is aware that we should avoid making our live harder than it should be by avoiding such merge conflicting changes. Specificly when there is no point to change it now as it does not have any impact yet.

**Comment by brianteeman** [comment]
re automated - I meant is there a script that updates things like this when the branch becomes the main one. Obviously by your reply there isnt.

I still dont get what the problem is with this. I was just tyring to help - its not worth the hassle.

**Pull request closed without merging**
