### PR TITLE
Fix boolean conditions for PostgreSQL and MSSQL

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes a couple of conditions that fail on PostgreSQL and MS SQL.

### Testing Instructions

As a simple test, try these queries:

1) `SELECT * FROM #__content WHERE 0`

2) `SELECT * FROM #__content WHERE 0 != 0`

### Expected result

No results returned and no errors.

### Actual result

First query has errors.

On MSSQL:

>An expression of non-boolean type specified in a context where a condition is expected, near '0'.

On PostgreSQL:

>ERROR: argument of WHERE must be type boolean, not type integer Position: 33

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c116c1b26a50ff710afc5b983c5f52db9dc37b9d<br /><br />Code review + I can confirm that this is the right, standard SQL way to do it for any kind of database, have some condition which resolves to false or true, depending on the purpose. I've had that problemn recently, too, and have fixed it in the same way. Is a very commong thing to use such conditions for such purpose.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26789">issues.joomla.org/tracker/joomla-cms/26789</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c116c1b26a50ff710afc5b983c5f52db9dc37b9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26789">issues.joomla.org/tracker/joomla-cms/26789</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26789">issues.joomla.org/tracker/joomla-cms/26789</a>.</sub>

**Comment by wilsonge** [comment]
Isn't this just places where we shouldn't be running queries to begin with rather than forcing queries to return empty results?

**Comment by richard67** [comment]
Agree ... but better this PR like it is than SQL errors, that's why I gave it a good test.

Maybe @SharkyKZ wants to change it here to not run the query in case of false condition? Or make a new PR?

**Comment by SharkyKZ** [comment]
Yes, that would be better.

**Comment by SharkyKZ** [comment]
Closing this. Will make 2 separate PRs.

**Pull request closed without merging**
