### PR TITLE
[4.0] Don't upscale images

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Small images in the media edit won't be upscaled

### Testing Instructions
Try to edit any of the Joomla images in the root of the images folder. The images shouldn't be upscaled in the rotate and resize tabs

### Documentation Changes Required

NO

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b74f4d6a6b5f75df5643f0a3bf2f75a73dbde70c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34947">issues.joomla.org/tracker/joomla-cms/34947</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on b74f4d6a6b5f75df5643f0a3bf2f75a73dbde70c<br /><br />I noticed the upscaling testing an other patch. This patch fixes this issue!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34947">issues.joomla.org/tracker/joomla-cms/34947</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34947">issues.joomla.org/tracker/joomla-cms/34947</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
