### PR TITLE
[4.0] Fix a falsie error alert on media field

### LINKED ISSUE #29497: [4.0b1] Media Manager Select without a selection gives internal server error
### Steps to reproduce the issue

Attempt to select an image from media manager modal when creating an article

When modal opens, just click select 

The modal closes

### Expected result

The modal doesn't close. 
"You must make a selection" alert?

### Actual result

Modal closes, internal server error message

Screen Recording 2020-06-08 at 05 29 PM

### System information (as much as possible)

safari on Mac

### PR DESCRIPTION
**Pull request by dgrammatiko**
Closes #29497 

### Summary of Changes
Change a promise reject to resolve

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3735ac6effaf90488909d0110908adaf13a11e5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30066">issues.joomla.org/tracker/joomla-cms/30066</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 3735ac6effaf90488909d0110908adaf13a11e5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30066">issues.joomla.org/tracker/joomla-cms/30066</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30066">issues.joomla.org/tracker/joomla-cms/30066</a>.</sub>

**Comment by richard67** [comment]
Thanks a lot for this fix.

**Pull request merged**
