### PR TITLE
Remove reference to Media manager in Imagelist Custom Field

### LINKED ISSUE #31162: Custom field "Image list" don't use custom image path from media parameters
### Steps to reproduce the issue
Create a new "files" folder at root, then create an "images" sub-folder in it, then create a "test" sub-folder in it.
Result should be : website_root/files/images/test
Change images path in media manager parameters to : files/images

Setup a new custom field, select "images list" type and try to choose test from folder parameter in first tab.

### Expected result
We should see "test" folder in list.

### Actual result
We get "website_root/images" content in list.

### System information (as much as possible)
Joomla 3.9.22.
Linux Debian 9.

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/31162.

### Summary of Changes

Removes reference to Media manager. The field does not read Media configuration, nor it should.

### Testing Instructions

Language review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f719604aa2e37ac237e1a3b12b19bad9fa63e2a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31170">issues.joomla.org/tracker/joomla-cms/31170</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f719604aa2e37ac237e1a3b12b19bad9fa63e2a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31170">issues.joomla.org/tracker/joomla-cms/31170</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31170">issues.joomla.org/tracker/joomla-cms/31170</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
