### PR TITLE
Regression: Remove duplicate menutype from hathor and fix bug

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11125.
#### Summary of Changes

Fixes menu types in hathor in select menu type modal.
See https://github.com/joomla/joomla-cms/issues/11125
#### Testing Instructions
1. Use latest staging
2. Change template to hathor
3. Create a menu item of any system link type, you will se the issue described in https://github.com/joomla/joomla-cms/issues/11125
4. Apply patch, no more issue

### CODE REVIEW

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on aeaaa3a66a98628028aaf4a60277a9ddcea488c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11130">issues.joomla.org/joomla-cms/11130</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on aeaaa3a66a98628028aaf4a60277a9ddcea488c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11130">issues.joomla.org/joomla-cms/11130</a>.</sub>

**Comment by killoltailored** [comment]
Tested successfully with Joomla Version: Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT  and OS: Windows 8.1, browser: Firefox 47.0.1
I have tested with admin template HATHORscreen shot 2016-07-15 at 00 24 02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11130">issues.joomla.org/joomla-cms/11130</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11130">issues.joomla.org/joomla-cms/11130</a>.</sub>

**Comment by infograf768** [comment]
Changed title to indicate regression.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11130">issues.joomla.org/joomla-cms/11130</a>.</sub>

**Pull request merged**
