### PR TITLE
[4.1] Fix dependency on web application stopping content from booting in CLI mode

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #35818 .

### Summary of Changes
Removes unused constructor argument. Luckily also fixing #35818 for now although there's still some thought process to work through there.

### Testing Instructions
Check loading of icons in the frontend of com_content and com_contact continues to work (both create and edit icons)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a8c60d86ae998b7541e46180602f5bbca9f4d4dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36568">issues.joomla.org/tracker/joomla-cms/36568</a>.</sub>

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on a2973bbd79d0e4c5d00dbe1f465ce2b7b9bd8452<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36568">issues.joomla.org/tracker/joomla-cms/36568</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36568">issues.joomla.org/tracker/joomla-cms/36568</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
