### PR TITLE
 Adding more test for categories

### PR DESCRIPTION
**Pull request by Kaushik1216**
Pull Request for Issue # .

### Summary of Changes
 Adding more test for categories

### CODE REVIEW

**Comment by Kaushik1216** [comment]
Please check why category delete not working

**Comment by laoneo** [comment]
@Kaushik1216 does it work for you locally? If yes, run the installation test first locally on your computer and then run the new tests again on your computer.

**Comment by Kaushik1216** [comment]
Don't Know why but this is falling in my local system to

**Comment by Kaushik1216** [comment]
@rajputanuj31 can you please check why delete category test falling

**Comment by laoneo** [comment]
Do you get an error message?

**Comment by Kaushik1216** [comment]
> Do you get an error message?

No error message .test failing with undefined  exists DOM

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
