### PR TITLE
[4.0] News Feeds not Newsfeeds

### PR DESCRIPTION
**Pull request by brianteeman**
As per the style guide

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2f1af701f723337aef7c02bd0f29ccd823e50fff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24860">issues.joomla.org/tracker/joomla-cms/24860</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 2f1af701f723337aef7c02bd0f29ccd823e50fff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24860">issues.joomla.org/tracker/joomla-cms/24860</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
