### PR TITLE
[HTTPS] Atom generator tag and a comment

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to use https in atom feed generator tag and comment that reference the issue tracker.
#### Testing Instructions

Check code difference.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 34d5f36fe65a4ac575e0741fdb4bf290a97321f5<br /><br />simple fix. thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9406">issues.joomla.org/joomla-cms/9406</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 34d5f36fe65a4ac575e0741fdb4bf290a97321f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9406">issues.joomla.org/joomla-cms/9406</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9406">issues.joomla.org/joomla-cms/9406</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just conflicts fixed. Still RTC.

**Pull request merged**
