### PR TITLE
[#33394] Move JHtml Bootstrap Accordion functions into JLayouts

### PR DESCRIPTION
**Pull request by wilsonge**
**How to reproduce the problem and/or test the patch::**

Test that any uses of JHtml functions all work as expected. The best example to test is going to the the frontend contact option (if you have the sliders option activated). There should be no change before and after the patch

Note the unit tests still pass :)

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33394&start=0

### CODE REVIEW

**Comment by anibalsanchez** [comment]
@test Ok

Contact form rendered Ok with the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3216">issues.joomla.org/joomla-cms/3216</a>.</sub>

**Comment by zero-24** [comment]
Moving to RTC thanks to all!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3216">issues.joomla.org/joomla-cms/3216</a>.</sub>

**Comment by wilsonge** [comment]
Hold merge until 3.5. I suspect we probably won't merge at all though as me and Roberto have had a chat and think that this kind of code is probably better in JLayouts. But yeah we'll wait and see

**Comment by zero-24** [comment]
@wilsonge hehe thanks for the update but I miss something can you update the copiright dates to `2015`?

**Comment by roland-d** [comment]
Moving to Information Required as @wilsonge pointed out it may move to JLayouts.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3216">issues.joomla.org/joomla-cms/3216</a>.</sub>

**Comment by brianteeman** [comment]
Set milestone to 3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3216">issues.joomla.org/joomla-cms/3216</a>.</sub>

**Comment by dgt41** [comment]
@wilsonge can you eliminate the conflicts here?

**Comment by wilsonge** [comment]
I'm closing this I think. I think the example we have with the tabs shows this method isn't optimal. And you can already override this in JHtml

**Pull request closed without merging**
