### PR TITLE
Reduce the version hash length

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
why? where is it used?

**Comment by dgrammatiko** [comment]
> why? where is it used?

The production zips have versioned css/js so the browser caching would be the most effect it could: https://github.com/joomla/joomla-cms/blob/1739c464fa05c4267eceb6dd04967c7633880203/build/build.php#L306

**Comment by HLeithner** [comment]
should also be reduced to 6 chars

**Comment by dgrammatiko** [comment]
> should also be reduced to 6 chars

Already done here: https://github.com/joomla/joomla-cms/blob/721c32cce32f6b6f64ec8b5a4ee5817e8a5b79e5/build/build-modules-js/versioning.es6.js#L64

this pr just changes the algo from sha1 to md5. Also im not in favour of capping the hash but that’s another conversation

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
