### PR TITLE
[4.0] Featured code comment

### PR DESCRIPTION
**Pull request by brianteeman**
This comment does not belong in this file

code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f3ceedd5c94f19c6fc1ba62db0e828e736f7c7c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34032">issues.joomla.org/tracker/joomla-cms/34032</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on f3ceedd5c94f19c6fc1ba62db0e828e736f7c7c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34032">issues.joomla.org/tracker/joomla-cms/34032</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34032">issues.joomla.org/tracker/joomla-cms/34032</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
