### PR TITLE
[4.4] Fix copy/paste

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Fix comment in actionlogs controller

### Testing Instructions
Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7f909b443ca70e3078576431b2c9b069404cf379<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43782">issues.joomla.org/tracker/joomla-cms/43782</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7f909b443ca70e3078576431b2c9b069404cf379<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43782">issues.joomla.org/tracker/joomla-cms/43782</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43782">issues.joomla.org/tracker/joomla-cms/43782</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
