### PR TITLE
[4.0]Workflows page titles

### PR DESCRIPTION
**Pull request by brianteeman**
This PR changes the titles from

My Workflow: Transitions List
My Workflow: Stages List

to

Transition List: My Workflow
Stages List: My Workflow

This is consistent with every other component where we have a string in the title.

It also removes the hardcoded `:` and moves that into the language string as that might not be appropriate for the language

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5fae80d067b0927fa619436813c83e818aecdc76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27523">issues.joomla.org/tracker/joomla-cms/27523</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 5fae80d067b0927fa619436813c83e818aecdc76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27523">issues.joomla.org/tracker/joomla-cms/27523</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27523">issues.joomla.org/tracker/joomla-cms/27523</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
yay

**Pull request merged**
