### PR TITLE
[com_users] debuggroup view: Implement searchtools

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR, like already done in most views across Joomla admin panel, implements searchtools in com_users **debuggroup** view.

Also corrects several bugs.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Apply this patch in latest staging
2. Have debug setting set to Yes in global config
3. Go to Users -> Groups
4. Click the button "Debug Permissions Report" in any group
5. In the "Debug Permissions Report" page, test if search, filters, ordering and page limity (aka searchtools) are working properly

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 96a0d1bfaccf78542120d8310627d9d9e82a57ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10008">issues.joomla.org/joomla-cms/10008</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 96a0d1bfaccf78542120d8310627d9d9e82a57ac<br /><br />Works well, in opposite to PR #10007 , where I discovered issues with paging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10008">issues.joomla.org/joomla-cms/10008</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10008">issues.joomla.org/joomla-cms/10008</a>.</sub>

**Comment by rdeutz** [comment]
Could we be a bit more specific with "Also corrects several bugs.", please. It makes testing easier and the decision if it is a bugfix or not. Thanks

**Comment by wojsmol** [comment]
@andrepereiradasilva see https://github.com/joomla/joomla-cms/issues/10034

**Comment by zero-24** [comment]
@andrepereiradasilva @rdeutz @wojsmol see: https://github.com/joomla/joomla-cms/pull/10037

**Pull request merged**
