### PR TITLE
Change language string for active module positions

### PR DESCRIPTION
**Pull request by n9iels**
See #7209
The language string 'Active positions' says more about the below positions. 'Custom positions' would suggest the below positions are custom made by a user.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7252">issues.joomla.org/joomla-cms/7252</a>.</sub>

**Comment by n9iels** [comment]
Oops forgot to make a new branch :sweat_smile:
Oh well, shouldn't be a big problem

**Comment by MAT978** [comment]
**test**

able to reproduce then #7252 works as describe mod positin under "Active Positions"

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7252">issues.joomla.org/joomla-cms/7252</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7252">issues.joomla.org/joomla-cms/7252</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @n9iels! Merged.

**Pull request closed without merging**
