### PR TITLE
Abbreviate Miscellaneous in Smart Search options

### PR DESCRIPTION
**Pull request by brianteeman**
Misc. is a common abbreviation and by using it we dont break the layout. Obviously this cosmetic change is only a fix for en-GB

#### Before
image

#### After
image

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 93aa4ba89bd7170b1b7d0d0664115a60deba8fe7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12769">issues.joomla.org/tracker/joomla-cms/12769</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 93aa4ba89bd7170b1b7d0d0664115a60deba8fe7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12769">issues.joomla.org/tracker/joomla-cms/12769</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12769">issues.joomla.org/tracker/joomla-cms/12769</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
