### PR TITLE
[4.0] Removing obsolete code from core table classes

### PR DESCRIPTION
**Pull request by Hackwar**
Removing obsolete code from table classes in /libraries/src/Table. All bind methods can be replaced by the json-encode-fields-feature and the publish methods can all be dropped with the columnAlias feature.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Hackwar for shake of B/C shouldn't you leave the public facing functions in the library [libraries/src/Table/CoreContent.php] (so it won't break things)? eg 
```php
public function bind($array, $ignore = '')
{
}
```
```php
public function publish($pks, $state, $userId)
{
return true;
}
```

**Comment by Hackwar** [comment]
Those aren't gone. They are still in the parent Table class and are all used there. All those methods just implemented special behavior (like the publish methods) because fields were named differently. Since we can now alias a column, we don't need a special case for a table that has a column named state instead of published anymore and this can simply be removed. It is completely B/C

**Comment by dgrammatiko** [comment]
@Hackwar my comment was just by looking at the public part of the function. If it's not reachable or the parent will take care of it then it's fine

**Comment by Quy** [comment]
Remove use statements.

**Comment by Hackwar** [comment]
> 
> 
> Remove use statements.

done

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 7dab79162a1fa07dc77609bd527741d0f4f98d72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29396">issues.joomla.org/tracker/joomla-cms/29396</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 7dab79162a1fa07dc77609bd527741d0f4f98d72<br /><br />I have tested in backend in several components with adding / changing / ordering items and found no issue. 

Not tested with 3rd party components or updated installations. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29396">issues.joomla.org/tracker/joomla-cms/29396</a>.</sub>

**Comment by richard67** [comment]
@bonzani How did you test this pull request? It doesn't provide any testing instructions.

@Hackwar Ever thought about providing testing instructions? And (inspired by past experience): Have you tested your changes yourself?

**Comment by bonzani** [comment]
@richard67 I did move around items in the backend components. Since test instructions are missing, I just tried to cover code paths that where affected by this PR. But might also just have been a lucky test. Hard to say without specific instructions! But since it is analogous to the other two PR's that removed about the same code the changes looked fine.

**Comment by richard67** [comment]
@bonzani Thanks for the feedback.

**Comment by bonzani** [comment]
Your welcome. I try to allocate a little spare time (but I do not have much), to help with the testing so that we hopefully see version 4 released this year!

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29396">issues.joomla.org/tracker/joomla-cms/29396</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
