### PR TITLE
[4.0] View Private message: Add separator colon : while previewing the message #pbf19 #bug #26915

### PR DESCRIPTION
**Pull request by Mayaank12**
…he message

Pull Request for Issue # .

### Summary of Changes
Add seperator like colon while viewing message

### Testing Instructions
1. Open any private message
2. Verify that the label has a seperator after it

### Expected result
There should be a seperator after the label

### Actual result
Colon is shown after the label so that the user can get a better view

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 19d3d4083af4a66606bb8d268d8a6f425566b803
#pbf19 #test1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26919">issues.joomla.org/tracker/joomla-cms/26919</a>.</sub>

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 19d3d4083af4a66606bb8d268d8a6f425566b803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26919">issues.joomla.org/tracker/joomla-cms/26919</a>.</sub>

**Comment by SharkyKZ** [comment]
These strings are also used in message form. We generally do not use colons in forms like this.

**Comment by brianteeman** [comment]
This is not correct

**Comment by wilsonge** [comment]
Agree with Brian. These changes would also affect the form view as well. We do need to improve the message view - but this is probably not the way to go

**Pull request closed without merging**
