### PR TITLE
mea culpa

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9438.
#### Summary of Changes

added if required  of course
#### Comment

mea culpa

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e81464e793a3d67b066f233edd3a0a8f16c620bc<br /><br />Able to reproduce then #9439 works as expected - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on e81464e793a3d67b066f233edd3a0a8f16c620bc<br /><br />Got same "Error! Please read the Terms of Service. You will not be able to register if you do not agree with them." <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Comment by alikon** [comment]
@franz-wohlkoenig  under what conditions ?

**Comment by franz-wohlkoenig** [comment]
PHP 5.6.13
MySQLi 5.5.47-0+deb7u1
3.5.0-rc3

Saving an User in backend bring Error. I reinstalled pattester, alsp tach, Logout and -in - same Error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Comment by alikon** [comment]
unable to reproduce under this configurationn of profile plugin on backend

what i'm missing
profilep

**Comment by MATsxm** [comment]
for #9439 and with a backend registration with the "User - Profile" plugin unabled

A - before the patch:
1 - if TOS required:
"Error! Please read the Terms of Service. You will not be able to register if you do not agree with them." 
2 - if TOS **NOT** required:
"Error! Please read the Terms of Service. You will not be able to register if you do not agree with them."

B - after the patch:
1 - if TOS required:
"Error! Please read the Terms of Service. You will not be able to register if you do not agree with them." 
2 - if TOS **NOT** required:
**"SUCCESS"**

**Comment by franz-wohlkoenig** [comment]
confirm @MATsxm: if TOS Disabled, no Error. Error if TOS Enabled.

**Comment by MATsxm** [comment]
I have tested this item :red_circle: unsuccessfully on e81464e793a3d67b066f233edd3a0a8f16c620bc<br /><br />revert to unsuccessfull as if TOS is required, there's still an error for a backend registration - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Comment by alikon** [comment]
added the not in backend condtion

**Comment by franz-wohlkoenig** [comment]
Get "Could not connect to GitHub: Bad credentials", so cannot test until i know whats going wrong.

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 4e9c9415d834e3c52fd86e6834e5f44973c5abb6<br /><br />for a registration on backend with the plg_ "User - Profile" **unabled**

**A - before the patch:**
1 - if TOS required:
`"Error! Please read the Terms of Service. You will not be able to register if you do not agree with them."`
2 - if TOS **NOT** required:
`"Error! Please read the Terms of Service. You will not be able to register if you do not agree with them."`

**B - after the patch:**
1 - if TOS required:
`SUCCES`
2 - if TOS **NOT** required:
`SUCCESS`

Successful test
Thanks

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Comment by alikon** [comment]
...sorry guys for extra work ..
i hope there are not more uncovered conditions :stuck_out_tongue_winking_eye:

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4e9c9415d834e3c52fd86e6834e5f44973c5abb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9439">issues.joomla.org/joomla-cms/9439</a>.</sub>

**Pull request merged**
