### PR TITLE
[4.0] Equal widths across header icons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Gives the top right header icons equal widths.

### Before
header-icons1

### After
header-icons2

### CODE REVIEW

**Comment by C-Lodder** [comment]
If it's just the icons themselves that needs to be fixed with, then you can use the `fa-fw` class, e.g:

`fa fa-external-link fa-fw`

**Comment by ciar4n** [comment]
> If it's just the icons themselves that needs to be fixed with, then you can use the fa-fw class, e.g:

Won't work as it would be overruled by https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_header.scss#L68

Inline with what you suggest I have moved the width to the icon level

**Review by C-Lodder — APPROVED** [review]

**Comment by N6REJ** [comment]
what is a "fa" class and where is it documented?

**Comment by ciar4n** [comment]
`fa` is a FontAwesome class which is the icon library been used for Joomla 4... http://fontawesome.io/

**Comment by C-Lodder** [comment]
@N6REJ - Just FYI you can still use the same `icon-xxx` classes as you can in J3. We've mapped all the classes to it's B/C

**Pull request merged**
