### PR TITLE
Calendar various fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- CS
- Fix the submit binding to work for Persian calendar (basically for all calendars)
- Refactor the buttons on the bottom so they're not part of the table for easier customisation/styling

screen shot 2017-03-08 at 20 15 37

### Testing Instructions
Apply the patch and play with the calendar, everything should still work

@infograf768 @coolcat-creations @ghasemy50 please test!

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Article, Tab "Publishing", "Start Publishing": Click on a new Date got no Reaction, also on Buttons on Bottom no Reactopn after Click on them (only on "Close" is Reaction).

**Comment by dgt41** [comment]
Buttons: clear just clears the input and today sets the input to today, so only close does close the calendar!
Do you have any error on you console?

**Comment by franz-wohlkoenig** [comment]
Click on another Day: `TypeError: a.srcElement is undefined`

**Comment by dgt41** [comment]
@franz-wohlkoenig should be fine now...

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 15f1ca440847b29435272fc0d3aaa276a593ea94<br /><br />Test on Articles-Published and Field-Caöendar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14422">issues.joomla.org/tracker/joomla-cms/14422</a>.</sub>

**Comment by dgt41** [comment]
@yvesh help!

**Comment by ghasemy50** [comment]
hi,
it's ok.
just in persian language ,'fa-ir.js' file in `\media\system\js\fields\calendar-locales` have a bad translate.
exit parameter is translated to 'ستن' , good translate is 'بستن'. please solve it thank you.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 15f1ca440847b29435272fc0d3aaa276a593ea94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14422">issues.joomla.org/tracker/joomla-cms/14422</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14422">issues.joomla.org/tracker/joomla-cms/14422</a>.</sub>

**Comment by infograf768** [comment]
@ghasemy50 
See https://github.com/joomla/joomla-cms/pull/14428 for the calendar-locale correction

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on 15f1ca440847b29435272fc0d3aaa276a593ea94<br /><br />German string is still cut off - but Design improved once more.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14422">issues.joomla.org/tracker/joomla-cms/14422</a>.</sub>

**Comment by coolcat-creations** [comment]
image

**Comment by dgt41** [comment]
@coolcat-creations do you mean the `time` sting? This is part of the table and thus got less space

**Comment by infograf768** [comment]
@coolcat-creations 
Could German use "Zeit" instead ?
We do have 'very' limited space there.

**Comment by coolcat-creations** [comment]
@infograf768 yes German could. But: what for croatian "Vrijeme", greek χρόνος, Vietnamese:Thời gian ?

**Comment by Bakual** [comment]
Why do we have limited space? There is whitespace right of the time dropdowns.
I'm sure that could be solved.

**Comment by chmst** [comment]
I suggest an icon clock.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14422">issues.joomla.org/tracker/joomla-cms/14422</a>.</sub>

**Comment by wilsonge** [comment]
Given this is better, i'm going to merge this now and let's keep incrementing :)

**Comment by yvesh** [comment]
@wilsonge No we have to fix the JavaScript tests ASAP, because this PR broke them :-/

**Comment by infograf768** [comment]
> Why do we have limited space? There is whitespace right of the time dropdowns.
I'm sure that could be solved.

@Bakual
Not really, the 'empty' whitespace is for AM-PM when implemented

**Comment by infograf768** [comment]
The AM/PM will display when calendar field contains
`timeformat="12"`
screen shot 2017-03-09 at 17 34 12

**Comment by coolcat-creations** [comment]
+1 then for changing the string into a clock icon and
+1 for adding timeformat parameter into the custom field

**Comment by Bakual** [comment]
>+1 for adding timeformat parameter into the custom field

Depends a bit if that is more a language specific thing. eg if in UK they prefer 24hr and in Germany 12hr it would make more sense to put that setting into the language pack.

**Comment by infograf768** [comment]
the important to consider is not in the calendar imho, but the resulting display. the strings already exist in the core packs. adding a A after the hour will display am/pm

**Comment by infograf768** [comment]
Example:
`DATE_FORMAT_LC3="j F Y H:i:s A"`

**Comment by infograf768** [comment]
@dgt41 

By changing
`cell.innerHTML = JoomlaCalLocale.time || "&#160;";`
to
`cell.innerHTML = "<span class='icon-clock'> </span>";`

I can get a clock

screen shot 2017-03-10 at 10 11 19

What do you think? This would indeed solve that issue.

(I would not touch at the time parameter in the code and locale and just leave it there as is. Just change the display to the clock)

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/issues/14484

**Pull request merged**
