### PR TITLE
[4.3] Fix untranslated constants in script.php

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes
Follow up for https://github.com/joomla/joomla-cms/pull/41367
Replace untranslated constants to text

### Testing Instructions
Code review,
Or do Test 7 from @richard67 instruction https://github.com/joomla/joomla-cms/pull/41367#issuecomment-1712791024

### Actual result BEFORE applying this Pull Request
Untranslated lang constant

### Expected result AFTER applying this Pull Request
A fixed text

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@Fedik As the 2 language strings "FILES_JOOMLA_ERROR_MANIFEST" and "FILES_JOOMLA_ERROR_FILE_FOLDER" will not be used anymore with your PR, could you deprecate them in file "language/en-GB/files_joomla.sys.ini"?

**Comment by Fedik** [comment]
How that need to be done? 
tbh I have no idea how to deprecate a text strings :wink:

**Comment by richard67** [comment]
> How that need to be done? tbh I have no idea how to deprecate a text strings 😉

@Fedik You move the strings to the end and add a comment about deprecation before them, like you can see it here in 5.0-dev: https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/language/en-GB/plg_system_privacyconsent.ini#L29-L44

For the "language/en-GB/files_joomla.sys.ini" it would result in following content:

```
; Joomla! Project
; (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>
; License GNU General Public License version 2 or later; see LICENSE.txt
; Note : All ini files need to be saved as UTF-8

FILES_JOOMLA="Joomla CMS"
FILES_JOOMLA_XML_DESCRIPTION="Joomla! 4 Content Management System."

; All the following strings are deprecated and will be removed with 6.0
FILES_JOOMLA_ERROR_FILE_FOLDER="Error on deleting file or folder %s"
FILES_JOOMLA_ERROR_MANIFEST="Error on updating manifest cache: (type, element, folder, client) = (%s, %s, %s, %s)"
```

@HLeithner Would it also need to add the language string deprecation to some developer documentation?

**Comment by Fedik** [comment]
Done

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ca1469271061686af0fd566edcd0608d858f5f59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41734">issues.joomla.org/tracker/joomla-cms/41734</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on ca1469271061686af0fd566edcd0608d858f5f59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41734">issues.joomla.org/tracker/joomla-cms/41734</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41734">issues.joomla.org/tracker/joomla-cms/41734</a>.</sub>

**Comment by obuisard** [comment]
Thank you Fedir @Fedik

**Pull request merged**
