### PR TITLE
Handle DB errors in menu module

### PR DESCRIPTION
**Pull request by alikon**
updated to handle DB errors like #6612 ,#6632, #6665, #6666, #6675 and for #6591

Testing info
simulate a db error

### CODE REVIEW

**Comment by bertmert** [comment]
@test Success.

Changed line 31 of /administrator/.../mod_menu/helper.php
```
->from('#__menu_typesxxx AS a')
```
Before patch.
com_modules-manager1

After patch:
com_modules-manager2

**Comment by nonumber** [comment]
Not sure if this should get merged with regards to discussion on https://github.com/joomla/joomla-cms/pull/6710

**Comment by anibalsanchez** [comment]
@test OK. It is a good practice.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6676">issues.joomla.org/joomla-cms/6676</a>.</sub>

**Comment by dgt41** [comment]
@test ok

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6676">issues.joomla.org/joomla-cms/6676</a>.</sub>

**Pull request closed without merging**
