### PR TITLE
[4.0] Remove adminlist.css

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

This PR removes an old CSS file. As far as I can tell, it's not used or needed.

### Testing Instructions

1. Login to the frontend of your Joomla site.
2. Go to `/index.php/submit-article`
3. In the TinyMCE editor toolbar, expand the `CMS Content` dropdown item and click `Menu`

This will display a modal.

Ensure the styling of the content

### CODE REVIEW

**Comment by Quy** [comment]
Remove `use Joomla\CMS\HTML\HTMLHelper;` in DisplayController.php files.

**Comment by C-Lodder** [comment]
Thanks @Quy, done

**Comment by infograf768** [comment]
Not on desktop right now, but If I remember well, there was a class loaded in an xtd modal

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d26f4c31050f131a23e53990738524de6bc8f150<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28372">issues.joomla.org/tracker/joomla-cms/28372</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on d26f4c31050f131a23e53990738524de6bc8f150<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28372">issues.joomla.org/tracker/joomla-cms/28372</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28372">issues.joomla.org/tracker/joomla-cms/28372</a>.</sub>

**Comment by wilsonge** [comment]
@infograf768 can you please get back tomorrow morning on your checks

**Comment by C-Lodder** [comment]
I have checked the entire repo (PHP) code for references to `adminlist` after these changes. It's only used in PHP classes

**Comment by infograf768** [comment]
@C-Lodder @wilsonge 

Here is an animated gif of the articles XTD used when editing an article in frontend.

adminlist

Screen Shot 2020-03-17 at 08 44 47

Remark the change in family font.

I am not saying we should keep adminlist because of that. It looks like it is indeed a useless override.

**Comment by brianteeman** [comment]
Good memory @infograf768 

I agree with your conclusion that this change in font is not needed or even desired and this css can be removed

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Nice memory indeed JM!

**Pull request merged**
