### PR TITLE
[3.7] - Fixes image display in tags category view.

### PR DESCRIPTION
**Pull request by tonypartridge**
Pull Request for Issue #6331 .

### Summary of Changes

Adds a check if com_categories view and com_banners and if there is a count of items. Then re-maps the images to the intro image for the render to be able to render the image in the list view. 

### Testing Instructions

Create a tag, e.g. "Red".
Create or edit an article:
Add the previously created tag.
Add an intro image.
Save.
Create or edit a category:
Add the previously created tag.
Add an image (under "options").
Save.
Create a menu item:
Type: Tagged Items
Tag: "Red" (your tag)
Content type: "Article"
Item Options - Item Image: Show (or set this option in the global options).
Create a menu item:
Type: Tagged Items
Tag: "Red" (your tag)
Content type: "Category"
Item Options - Item Image: Show (or set this option in the global options).
Compare both menu item views in frontend. The article one displays the item/intro image, while the category one doesn't display any image.

(above taken from the issue)

### Expected result

Shows image in list

### Actual result

Shows no image in list.

### CODE REVIEW

**Comment by wilsonge** [comment]
Duplicate of https://github.com/joomla/joomla-cms/pull/13906

**Comment by tonypartridge** [comment]
Reopening - @wilsonge had a late night and wasn't firing on all 'Cyclinders'.

Please test.

**Comment by tonypartridge** [comment]
Also fixed undefined $row call, it should have been $item

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 03a8457f5adcbe9d65e524035e9abfc2e179c77c<br /><br />Using PR Article and Category shows Picture.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14747">issues.joomla.org/tracker/joomla-cms/14747</a>.</sub>

**Comment by tonypartridge** [comment]
Can we get another test on this please?

**Comment by tonypartridge** [comment]
@brianteeman could I be so kind to trouble you for a test when you have some spare time.....

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2098c07c9f4a285db4b5c632d6a9f0b35948b498<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14747">issues.joomla.org/tracker/joomla-cms/14747</a>.</sub>

**Comment by brianteeman** [comment]
There you are @tonypartridge wish @wilsonge merged my prs as quickly :)

**Comment by tonypartridge** [comment]
:D thanks guys! #teamwork #makestheworldgoround

**Comment by Melvine9** [comment]
When a tag is create but not use yet  ( no result) there is a notice php
Notice: Trying to get property of non-object in C:\wamp\www\components\com_tags\views\tag\view.html.php on line 120

**Comment by zero-24** [comment]
@Melvine9 please check #16143 thnaks

**Pull request merged**
