### PR TITLE
[4.2] com_cache selection

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #39144 .

### Summary of Changes
Uses the correct code instead of attempting to hard code the markup

### Testing Instructions
go to system->cache
click on the **text** for a row

### Actual result BEFORE applying this Pull Request
checkbox not checked

### Expected result AFTER applying this Pull Request
checkbox cheked

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Ruud68** [comment]
I have tested this item :white_check_mark: successfully on e3a11c99dcd6c172ef5364355308bfe117a3b602<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39147">issues.joomla.org/tracker/joomla-cms/39147</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e3a11c99dcd6c172ef5364355308bfe117a3b602<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39147">issues.joomla.org/tracker/joomla-cms/39147</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39147">issues.joomla.org/tracker/joomla-cms/39147</a>.</sub>

**Comment by sjmdia** [comment]
I have tested this item :white_check_mark: successfully on e3a11c99dcd6c172ef5364355308bfe117a3b602<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39147">issues.joomla.org/tracker/joomla-cms/39147</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
