### PR TITLE
 [4.0] Improvement in frontend

### PR DESCRIPTION
**Pull request by niharikamahajan02**
### Summary of Changes
Did some changes in TOOLBAR.

### Actual result BEFORE applying this Pull Request
SHOWING SCREENSHOT OF ARTICLES SECTION.
image

image

### Expected result AFTER applying this Pull Request
SHOWING SCREENSHOT OF CHANGES DONE IN ARTICLE SECTION( CAN BE VIEWED IN OTHER CONTENT CATEGORIES TOO)
image

image

### CODE REVIEW

**Comment by brianteeman** [comment]
Why? What is the reason behind these changes?

**Comment by niharikamahajan02** [comment]
There is a wide gap before search tool , so it is better to minimize that so that toolbar starts from leftmost side . The screen would look much better.

**Comment by brianteeman** [comment]
Changing from right aligned to left aligned is a subjective opinion not a fact.

**Comment by richard67** [comment]
> The screen would look much better.

@niharikamahajan02 It's not only a question what looks better (and that's a subjective thing, i.e. matter of taste), it is more important which way you can navigate faster and how you can find things more quickly.

Having the search tool bar right aligned like it is without your PR is in my opinion better. We can find the paging and the ordering drop downs more quickly in my opinion.

So I am not in favour of this PR. I think it should be closed.

**Comment by niharikamahajan02** [comment]
Ok sir , thanks for the feedback . Got the point.

**Pull request closed without merging**
