### PR TITLE
[4.0] Simplify error messages

### PR DESCRIPTION
**Pull request by PhilETaylor**
Building on the idea from #32263 and  #32268

### Summary of Changes

"No need for a user to see technical terms when something goes wrong if the message is good enough without"

On Code Review only. 

These were not even translatable.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 15f0b36afa8f12853242cfa02ad3f073e667b05d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32269">issues.joomla.org/tracker/joomla-cms/32269</a>.</sub>

**Comment by FrederikGostn** [comment]
I have tested this item :white_check_mark: successfully on 15f0b36afa8f12853242cfa02ad3f073e667b05d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32269">issues.joomla.org/tracker/joomla-cms/32269</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15f0b36afa8f12853242cfa02ad3f073e667b05d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32269">issues.joomla.org/tracker/joomla-cms/32269</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32269">issues.joomla.org/tracker/joomla-cms/32269</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
