### PR TITLE
Fix initial call of Joomla.loadOptions()

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
This patch fix an initial call of Joomla.loadOptions() when page do not contain the Script options, which could lead to JavaScript error.

### Testing Instructions
Use latest staging, 
Add in to index.php of Isis template:
```php
JHtml::_('behavior.core');
$this->addScriptDeclaration('
  try{Joomla.getOptions("blabla");alert("Works!");}catch(e){alert("Error!");};
');
```
And open "Control panel" page.

### Expected result
You see alert "Works!"

### Actual result
You see alert "Error!"

### Documentation Changes Required
none

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 61b334a19de9fb181e7e0c49497462b9f11908a4<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16488">issues.joomla.org/tracker/joomla-cms/16488</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@dgt41 (or other tester) please test since there another PRs waiting for this one to get merged
https://github.com/joomla/joomla-cms/pull/16452 and https://github.com/joomla/joomla-cms/pull/15529

**Review by C-Lodder — APPROVED** [review]

**Comment by andrepereiradasilva** [comment]
@Fedik i'm still getting the error. maybe there's another place you need to do that

**Comment by andrepereiradasilva** [comment]
seems the error is here https://github.com/joomla/joomla-cms/blob/staging/media/system/js/core-uncompressed.js#L159

`
core.js?9398acd…:1 Uncaught TypeError: Cannot read property 'system.keepalive' of null
    at Object.Joomla.getOptions (core.js?9398acd…:1)
    at HTMLDocument.<anonymous> (keepalive.js?9398acd…:1)
Joomla.getOptions	@	core.js?9398acd…:1
(anonymous)	@	keepalive.js?9398acd…:1
`

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on 61b334a19de9fb181e7e0c49497462b9f11908a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16488">issues.joomla.org/tracker/joomla-cms/16488</a>.</sub>

**Comment by C-Lodder** [comment]
What happens if you do comsole.log (key); on the line you linked to in the comment above?

**Comment by andrepereiradasilva** [comment]
```js
console.log(key);
console.log(Joomla.optionsStorage);
```
results in
```
system.keepalive
null
```

**Comment by Fedik** [comment]
I found the problem, 
should be good now

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9660d35c0889727372f50553aaaaf808bf16df0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16488">issues.joomla.org/tracker/joomla-cms/16488</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9660d35c0889727372f50553aaaaf808bf16df0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16488">issues.joomla.org/tracker/joomla-cms/16488</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
