### PR TITLE
[4.2] add renovate.json to the exclude list on the build tools

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue # .

### Summary of Changes

Add renovate.json to the exclude list on the build tools cc @roland-d @fancyFranci please merge before the stable build. cc @HLeithner 

### Testing Instructions

review the changes

### Actual result BEFORE applying this Pull Request

renovate.json is included within the packages

### Expected result AFTER applying this Pull Request

renovate.json is nolonger included within the packages

### Documentation Changes Required

n.a.

### CODE REVIEW

**Comment by HLeithner** [comment]
looks good thanks

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fe9b5e776007b34c56366e18b341f76a1dd25250<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38442">issues.joomla.org/tracker/joomla-cms/38442</a>.</sub>

**Comment by fancyFranci** [comment]
Could you sort it alphabetical? :D

**Comment by tecpromotion** [comment]
Also 

Installation and Images

**Comment by zero-24** [comment]
Something like that @fancyFranci ?

@tecpromotion IIRC Images and installer are handled at other places.

**Comment by tecpromotion** [comment]
> Something like that @fancyFranci ?
> 
> 
> 
> @tecpromotion IIRC Images and installer are handled at other places.

image

**Comment by zero-24** [comment]
Got it fixed @tecpromotion

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 239ed537553ca8839d64156b332845f30b31c720<br /><br />By review with knowledge on how build.php works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38442">issues.joomla.org/tracker/joomla-cms/38442</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Pull request merged**
