### PR TITLE
Fix bug clearing datepicker unintentionally

### PR DESCRIPTION
**Pull request by DrDreave**
Pull Request for Issue #17741.

### Summary of Changes
Added `type="button"` to the datepicker's action buttons as the browser interprets buttons
without a type as submit button, so it (the first button in the form) gets triggered when pressing enter within the containing form.

See #17741.

### Testing Instructions

* Open an admin form with date field (i.e. an existing article)
* Go to the Publishing options
* Make sure there is a date value selected for Start Publishing and Created Date.
* If not set these date fields and save the article.
* Click into the input field of the Created Date option then.
* Press the enter key

### Expected result
Nothing should change with the selected dates visible in Start Publishing and in Created Date

### Actual result
Input of Start Publishing is cleared.
(It is always the input of the first date field in the form that is cleared)

### Documentation Changes Required
None.

### Notes
Maybe the form should be submitted when pressing enter, this isn't happening automatically as the toolbar buttons are outside of the form.

Developed @icampus

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by dgrammatiko** [comment]
@DrDreave on code review this looks fine, thanks!

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 4247206b9e9ef602f1d381f1003d99d89277b7cd

Same behaviour as without PR: Curser in "Created Date" and hit "Enter" get "Start Publishing" empty.
### System information
3.8.0-beta5-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<br /><br /><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17777">issues.joomla.org/tracker/joomla-cms/17777</a>.</sub>

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig @DrDreave weird I just tried the original code in safari and I don't get a wrong behaviour. Can you please mention the browser and you Joomla setup (custom fields, multilingual etc)

EDIT Firefox and Chrome submit the form on enter

**Comment by ghost** [comment]
@dgt41 
### System information
3.8.0-beta5-dev
no custim Fields
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by DrDreave** [comment]
I can confirm the original issue in Chrome Version 60.0.3112.101 and Firefox 55.0.2 on MacOS. The date input gets cleared, the form doesn't get submitted. The PR fixes the clearance of the date input on a stock joomla 3.8. I'll perform further tests on my Windows PC in the next hours.

Safari seems to work fine without the patch as mentioned by @dgt41.

@franz-wohlkoenig Please try to clear your browser cache. Maybe the browser didn't reload the minified javascript after applying the patch.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4247206b9e9ef602f1d381f1003d99d89277b7cd<br /><br />Cleared Browsercache helped.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17777">issues.joomla.org/tracker/joomla-cms/17777</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 4247206b9e9ef602f1d381f1003d99d89277b7cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17777">issues.joomla.org/tracker/joomla-cms/17777</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
