### PR TITLE
s/Unexising/Unexisting

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/Unexising/Unexisting

Also Cross posted to framework https://github.com/joomla-framework/filesystem/pull/31

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 054dcd33860aa3334200db02ad7002b38740b889<br /><br />Joomla 4.0.0-beta7-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32048">issues.joomla.org/tracker/joomla-cms/32048</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 054dcd33860aa3334200db02ad7002b38740b889<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32048">issues.joomla.org/tracker/joomla-cms/32048</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32048">issues.joomla.org/tracker/joomla-cms/32048</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
