### PR TITLE
[4.1] s/inputed/input

### PR DESCRIPTION
**Pull request by brianteeman**
grammar

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8a9b744476a68dc3e5844af5b5ddf561c5dc4175<br /><br />Correct, to input is an irregular verb.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36823">issues.joomla.org/tracker/joomla-cms/36823</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8a9b744476a68dc3e5844af5b5ddf561c5dc4175<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36823">issues.joomla.org/tracker/joomla-cms/36823</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36823">issues.joomla.org/tracker/joomla-cms/36823</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
