### PR TITLE
Fix `function` parameter lost during redirect

### PR DESCRIPTION
**Pull request by janschoenherr**
Currently if you are switching the menu filter in the menu item select modal, the function parameter will be lost on redirect.

### Summary of Changes

This PR prevents the `function` parameter from being omitted upon switching menus. It does that by adding the parameter to the redirect url if present.

### Testing Instructions

Go to `/administrator/index.php?option=com_menus&view=items&layout=modal&tmpl=component&function=myCustomFunction` and switch the menu. The redirected url will have the new `menutype` parameter, but is missing the `function` parameter in the url.

### Actual result BEFORE applying this Pull Request

The `function` parameter is missing.

### Expected result AFTER applying this Pull Request

The `function` parameter is no longer missing.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
image

**Comment by Fedik** [comment]
The modal select for Menu in Joomla 5 does not required "function" parameter to work. 
It was updated to new approach with use of `postMessage()` https://github.com/joomla/joomla-cms/pull/41629

Where do you use it?

If you still need it, then please update your PR, to place it in the modal layout (form url), instead of controller.
Change here https://github.com/joomla/joomla-cms/blob/153193e117addc6ed533928cd0a0744edabb2ad9/administrator/components/com_menus/tmpl/items/modal.php#L36
To:
```php
$link      = 'index.php?option=com_menus&view=items&layout=modal&tmpl=component&' . Session::getFormToken() . '=1&function=' . $function;
```

But note: use of "function" will be removed in future.

**Comment by janschoenherr** [comment]
Thanks for the reply. Maybe I should have directed this at the 4.0 dev branch?

Anyway, it can't be moved to the modal.php. It's about the redirect in the controller. The redirect is done without the `function` paramater.

**Comment by Fedik** [comment]
>  it can't be moved to the modal.php

it can, if you try what I have suggested, you will see that it works very well :wink: 
The `function` variable is very layout specific thing, I do not think it should be in controller.

> Maybe I should have directed this at the 4.0 dev branch?

Yes, I think, it is a bug. For 4.4-dev branch should be okay, in theory.

**Comment by janschoenherr** [comment]
If you switch the menu, the controller won't display the modal.php, because it redirects previously and ignores the `function` parameter.

**Comment by Fedik** [comment]
Need to update URL for the form action https://github.com/joomla/joomla-cms/pull/42315#issuecomment-1816448171

**Comment by janschoenherr** [comment]
I am sorry, but have you tried adding the parameter to the form action? The POST request is being redirected in the Controller and therefore converted to a GET request, which does not have the `function` parameter.

In the modal.php, the `function` parameter is already set in the `hidden` input.

**Comment by Fedik** [comment]
I would not suggest you it, if it would not work

**Comment by janschoenherr** [comment]
Mea culpa, you are right. I've updated the pull request. Thank you very much.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 41022b75ff7fd928ddee4c575f017611ee3bccf7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42315">issues.joomla.org/tracker/joomla-cms/42315</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42315">issues.joomla.org/tracker/joomla-cms/42315</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
