### PR TITLE
[4.0] Incorrect language constant in installation files

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
When installing Joomla 4, select the PostgreSQL type and enter the database name that starts with a number.

We get an error.

Screenshot_1

The constant appears two times in the files below.

Screenshot_2

PR fixes the problem.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fb32c7936889c0d8c12d164598f5b07e9100ee8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31487">issues.joomla.org/tracker/joomla-cms/31487</a>.</sub>

**Comment by brianteeman** [comment]
An alternative that would avoid all the translations to be updated would be to update the constant in the two places it is used in the code

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fb32c7936889c0d8c12d164598f5b07e9100ee8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31487">issues.joomla.org/tracker/joomla-cms/31487</a>.</sub>

**Comment by infograf768** [comment]
Agree with @brianteeman 
please rather modify
```
/Applications/MAMP/htdocs/newfolder/joomla40/installation/src/Helper/DatabaseHelper.php:238: 			return Text::_('INSTL_DATABASE_NAME_MSG_POSTGRESQL');
/Applications/MAMP/htdocs/newfolder/joomla40/libraries/src/Console/SetConfigurationCommand.php:314: 			$this->ioStyle->error(Text::_('INSTL_DATABASE_NAME_MSG_POSTGRESQL'));
```
to use `INSTL_DATABASE_NAME_MSG_POSTGRES`

**Comment by Kostelano** [comment]
DONE.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on be2d3b2d0818776d6839f7afd4d5943f606e72cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31487">issues.joomla.org/tracker/joomla-cms/31487</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on be2d3b2d0818776d6839f7afd4d5943f606e72cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31487">issues.joomla.org/tracker/joomla-cms/31487</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31487">issues.joomla.org/tracker/joomla-cms/31487</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
