### PR TITLE
[4.0] SEF instructions

### PR DESCRIPTION
**Pull request by brianteeman**
Simplify the instruction and only display them if SEF and SEF Rewrite are enabled

### before
before

### after
after

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 22c9ebd139910bea346742be1145aea77b44bec9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28268">issues.joomla.org/tracker/joomla-cms/28268</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22c9ebd139910bea346742be1145aea77b44bec9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28268">issues.joomla.org/tracker/joomla-cms/28268</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28268">issues.joomla.org/tracker/joomla-cms/28268</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
