### PR TITLE
[4.1] Workflow Stage display

### PR DESCRIPTION
**Pull request by brianteeman**
## Purpose
If you are using workflowsand  viewing a list of articles it is not possible to easily see what stage each article is at. You can hover over the icon (which appears to be disabled but thats another issue) to find out the stage for each article but you cannot easi;y see an overview.  And if you sort by Stage then you have no idea how they are sorted etc etc

### Test Setup Instructions

- Enable workflows in the content options
- Create several articles and set them at different stages
- Also check the deatured articles view

### Before this PR
No visible means to see the stage of all the articles
image

### After this PR
The stage is now displayed
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on bad6b0a090408c0cf3d73173c77dd22955c61023<br /><br />Tested successfully in Joomla 4.1.3-rc2-dev of 6 May in Wampserver 3.2.8 using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37748">issues.joomla.org/tracker/joomla-cms/37748</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bad6b0a090408c0cf3d73173c77dd22955c61023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37748">issues.joomla.org/tracker/joomla-cms/37748</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37748">issues.joomla.org/tracker/joomla-cms/37748</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
