### PR TITLE
Add noopener option to link rel attribute

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #27990.

### Summary of Changes
Add `noopener` option to link rel attribute of external URL menu type.

### Testing Instructions
Add new menu item
Select System Links > URL
Click `Link Type` tab
Click `Link Rel Attribute` dropdown
See `noopener` option

### CODE REVIEW

**Comment by TVBZ** [comment]
Tested. Working as expected. Thanks!

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 3e3b6ecd0e57077dc86d2cb797fb126fc6684aa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28005">issues.joomla.org/tracker/joomla-cms/28005</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28005">issues.joomla.org/tracker/joomla-cms/28005</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3e3b6ecd0e57077dc86d2cb797fb126fc6684aa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28005">issues.joomla.org/tracker/joomla-cms/28005</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :-)

**Pull request merged**
