### PR TITLE
[4.0] Update Bootstrap to 4.4.1

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27287.

### Summary of Changes

Updates Bootstrap from 4.3.1 to 4.4.1 and Popper.js from 1.15.0 to 1.16.0.

### Testing Instructions

Run `npm install`.
Browse around frontend and backend.
Check that styling still OK.
Check that Bootstrap JS components (modal, dropdowns, popovers) still work.

### Expected result

Works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
There are quite a few other npm resources that are "hard coded" to a specific release that are now outdated. Is there a policy on how we handle this. Should all npm resources be set to update automatically

**Comment by SharkyKZ** [comment]
Depends on the package. Some are locked to the last release of a major version (e.g. Punycode). And some may introduce B/C breaks even in minor releases. I think that's why chosen-js is locked to 1.6.2?

**Comment by brianteeman** [comment]
If they dont follow semantic versioning eg chosen then that make sense

But then we have others which do follow semantic versioning such as tinymce which are "locked" at a patch release.

The entire point of using npm is that we shouldnt need to be manually checking all external scripts for updates

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 027bc9e23dadc610a25b444f752d62cb5db55b8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27294">issues.joomla.org/tracker/joomla-cms/27294</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a1c18316b933160d0e58462818aa74d1b791efb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27294">issues.joomla.org/tracker/joomla-cms/27294</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27294">issues.joomla.org/tracker/joomla-cms/27294</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! 

I think it largely depends on the product. As we know ourselves - some people claim to do semver but not :) I think we're good in most places to allow patch and minors in our package.json as the general rule tho

**Pull request merged**
