### PR TITLE
[4.0] Add json to .editorconfig

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds JSON to .editorconfig to use 2 space indents instead of 1 tab.
Formats some JSON files.

### Testing Instructions

Open any JSON file in the repository.
Notice that 2 space indentation is used.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
> Open any JSON file in the repository.

@SharkyKZ ~~You mean here on GitHub with their built-in editor? And edit a bit without saving, just to see if new lines are indended in the right way? Sorry if it's a silly question, but up to now I never cared about .editorconfig and what editor it is good for ;-)~~ Update: Found it out, see test result below. All fine.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bdecd0b164533029944416591c8895fd211921f6<br /><br />Found it out:

Edit a json file in the 4.0-dev branch on GitHub. Add some new code, e.g. new curly opening bracket, and after that some code, and then closing curly bracket, or anything for which you expect a clever editor who knows about the syntax of json to do the right indent automatically.

Result: Indent for 1 level is one tabulator.

Now edit some json file in the branch of this PR and check automatic indent in the same way.

Result: Indent for 1 level is two spaces.

Finally checked changes in the json files by code review. All fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30228">issues.joomla.org/tracker/joomla-cms/30228</a>.</sub>

**Comment by richard67** [comment]
Hmm, just thinking about it further: 1 tab is 1 byte, 2 spaces are 2 bytes ... don't we blow up the files with this change? ;-) (joking)

**Comment by jmeintrup** [comment]
I have tested this item :white_check_mark: successfully on bdecd0b164533029944416591c8895fd211921f6<br /><br />Tested with PhpStorm 2020.2 and VSCode 1.48.0-insider

### Before Patch:
- Both editors used tabs as default behaviour when editing `.stylelintrc.json` or `plugins/editors/codemirror/fonts.json`


### After Patch:
- Both editors used 2 spaces as default behaviour when editing `.stylelintrc.json` or `plugins/editors/codemirror/fonts.json`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30228">issues.joomla.org/tracker/joomla-cms/30228</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30228">issues.joomla.org/tracker/joomla-cms/30228</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
