### PR TITLE
Once you have tagged an item you can't add any more tags: removing a part of the code seems to be the fix

### PR DESCRIPTION
**Pull request by rdeutz**
It seems that removing code fixes the problem #5554 this PR it is more or less the same as in #5601. I have tested tags where I have found them and anything is working. But this needs more tests, because it feels strange :-)

### CODE REVIEW

**Comment by jackkum** [comment]
@test success. :)

**Comment by phproberto** [comment]
I was not able to reproduce #5554 issue on the latest staging.

### Steps done:
1. Installed Joomla without any test data
2. Created Tag1, Tag2, Tag3 from tags management
3. Created a new article and assigned it Tag1 & Tag2 tags. Save
4. Edited the same article and added Tag3 without issues.

In fact the real issue is that we should never load the full list of tags (done when the article has no tags). That's bad for performance when you have a lot of tags. The tag field should show only the found tags matching what has been typed.

**Comment by brianteeman** [comment]
I just retested on current staging as of 5 minutes ago and I still have the
issue

   1. Created Tag1, Tag2, Tag3 from tags management
   2. Created a new article and assigned it Tag1 & Tag2 tags. Save
   3. Edited the same article and only the existing tags are displayed in
   the select

**Comment by rdeutz** [comment]
the confusing part is that you see a select with options but there are only the already chosen ones, that doesn't makes so much sense.

**Comment by phproberto** [comment]
Yes. The field only has to load the assigned tags and ideally never all the available tags (which is now done when no tags are found because the `IN ()` clause is not executed). Loading all the tags can cause the performance issues.

So the correct way in my opinion is to to do something like this in the `getOptions` method:

```php
if (empty($this->value))
{
    return array();
}
```

**Comment by rdeutz** [comment]
Just to illustrate that is how it looks like
tags

**Comment by phproberto** [comment]
And the SQL queries. 

Without patch (loading only the assigned tags):

```sql
SELECT DISTINCT a.id AS value, a.path, a.title AS text, a.level, a.published, a.lft
FROM jml_tags AS a
LEFT JOIN `jml_tags` AS b ON a.lft > b.lft AND a.rgt < b.rgt
WHERE a.id IN (2) AND `a`.`lft` > 0 AND a.published IN (0,1)
ORDER BY a.lft ASC
```

With patch or when no tags are assigned (loading all the tags):

```sql
SELECT DISTINCT a.id AS value, a.path, a.title AS text, a.level, a.published, a.lft
FROM jml_tags AS a
LEFT JOIN `jml_tags` AS b ON a.lft > b.lft AND a.rgt < b.rgt
WHERE `a`.`lft` > 0 AND a.published IN (0,1)
ORDER BY a.lft ASC
```

**Comment by jackkum** [comment]
@phproberto 
i agree, behavior must be the same on create new article (show tags after typing),
that will not confuse users.

**Comment by Kubik-Rubik** [comment]
I would prefer the following approach:

If an article with tags is loaded, then only the selected tags are loaded. If the user clicks on the tags field, then all available tags are loaded. So, the extensive tags loading is triggered by the user and not automatically in the normal loading process.

**Comment by bertmert** [comment]
@test Success
I would prefer this PR instead of current confusing behaviour until a specialist found a way to load tags at the earliest on click or on focus like Kubik-Rubik advised. I gave up after several hours because of conflicting events.

**Comment by zero-24** [comment]
RTC based on testing. maybe @Kubik-Rubik can propose a better fix later?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5630">issues.joomla.org/joomla-cms/5630</a>.</sub>

**Pull request merged**
