### PR TITLE
[4.0] Add target attribute to display link icon

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #25889.

### Summary of Changes
Add target attribute to display link icon.
This will make it consistent with the alternate preset.

### Testing Instructions
Log in to backend.
Go to Help.
No link icons.
Apply PR.
Link icons shown.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a0a59dad388b59911198e63914798cf390920d91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26497">issues.joomla.org/tracker/joomla-cms/26497</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on a0a59dad388b59911198e63914798cf390920d91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26497">issues.joomla.org/tracker/joomla-cms/26497</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26497">issues.joomla.org/tracker/joomla-cms/26497</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26497">issues.joomla.org/tracker/joomla-cms/26497</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
