### PR TITLE
[4.0][com_users] Add cancel action to profile form

### PR DESCRIPTION
**Pull request by SharkyKZ**
This is an alternative to #24007 and #24087 PRs. Also in a sense solves #17875.

### Summary of Changes

Adds cancel task to profile controller to allow the use of `<button>` element for accessibility reasons.

CC @zwiastunsw @tarot-ray @hardik-codes

### Documentation Changes Required
New method added.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on fb65e36f5c575a67829d26b7b6d6690aedae749f<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24088">issues.joomla.org/tracker/joomla-cms/24088</a>.</sub>

**Comment by SharkyKZ** [comment]
Added `formnovalidate` to the cancel button so the form can be submitted when required fields are missing. @zwiastunsw can you re-test please?

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 35cf04eee760ed6cf0b5df153ca0d27269881e0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24088">issues.joomla.org/tracker/joomla-cms/24088</a>.</sub>

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on 35cf04eee760ed6cf0b5df153ca0d27269881e0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24088">issues.joomla.org/tracker/joomla-cms/24088</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24088">issues.joomla.org/tracker/joomla-cms/24088</a>.</sub>

**Comment by wilsonge** [comment]
Much cleaner! Thanks!

**Pull request merged**
