### PR TITLE
Fix the layout for our standard

### PR DESCRIPTION
**Pull request by laoneo**
Followup of #38768 which adapts the layout to our coding standard.

Can be merged on review.

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 72e0fc1da8c3949a0b6009190081d874ee338d06<br /><br />follows the de facto standard<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39301">issues.joomla.org/tracker/joomla-cms/39301</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 72e0fc1da8c3949a0b6009190081d874ee338d06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39301">issues.joomla.org/tracker/joomla-cms/39301</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39301">issues.joomla.org/tracker/joomla-cms/39301</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :)

**Pull request merged**
