### PR TITLE
Improve UsersHelperRoute

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes small improvements to UsersHelperRoute code (maybe it is just my preferred code style):

1. Remove unnecessary variables use (call methods chain directly)

2. Return early when a menu item found and null when nothing found (no need to use $itemid variable for storing data)

### Testing Instructions
Code review

### CODE REVIEW

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 100b4486fcc6c01142a9e48f5fefadac1b174650<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19109">issues.joomla.org/tracker/joomla-cms/19109</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 100b4486fcc6c01142a9e48f5fefadac1b174650<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19109">issues.joomla.org/tracker/joomla-cms/19109</a>.</sub>

**Comment by Quy** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
@Quy you have to set first "RTC"-Label in Tracker, then "Ready to Commit after two successful tests." here to get RTC-Label in Github.

**Pull request merged**
