### PR TITLE
[4.2] Clean the logo URL in Cassiopeia

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #39571, https://github.com/joomla/joomla-cms/issues/39538, https://github.com/joomla/joomla-cms/issues/39543

### Summary of Changes
Use the recommended way to render an image: through the HTMLHelper

### Testing Instructions
Check that selecting a custom logo image works and that the source doesn't have the hash part of the URL. Also check that svg renders as expected

### Actual result BEFORE applying this Pull Request

The URL contains the hash (it is dirty) and SVG images get 0 width and height thus are not visible

### Expected result AFTER applying this Pull Request

The URL **does not** contain the hash (it is clean) and SVG images are visible

### Link to documentations
This is a bug fix without changing any of the existing functionality
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Quy should be ok now, thanks

**Comment by Quy** [comment]
The double slashes is fixed, however, the image won't display even though the markup is there. Adding a width attribute displays the image.

`J42`

**Comment by dgrammatiko** [comment]
> however, the image won't display even though the markup is there. Adding a width attribute displays the image.

Ok, this could be solved either with CSS (patch) or the media manager needs to pass the correct size when an svg is selected (proper solution). I would make a PR for the second option. 
This PR is still valid as it cleans the URL #...

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cca0b5089c139f922b15d61c5511664822fd52c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39574">issues.joomla.org/tracker/joomla-cms/39574</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cca0b5089c139f922b15d61c5511664822fd52c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39574">issues.joomla.org/tracker/joomla-cms/39574</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39574">issues.joomla.org/tracker/joomla-cms/39574</a>.</sub>

**Comment by dgrammatiko** [comment]
@Quy @viocassel thanks for testing this one. https://github.com/joomla/joomla-cms/pull/39586 is the last missing part (the one I wrote about here: https://github.com/joomla/joomla-cms/pull/39574#issuecomment-1376393210) and would be awesome if you could test that one as well. Mille grazie

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
