### PR TITLE
[4.3] Fix language constants overrides in com_template.inis and com_categories.ini

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35422 .

### Summary of Changes
Fix language constants overrides in com_template.inis and com_categories.ini

### Testing Instructions
code review
### Actual result BEFORE applying this Pull Request
Original JLIB constants are used.

### Expected result AFTER applying this Pull Request
Component specific constants are used

### Documentation Changes Required
N/A

### CODE REVIEW

**Comment by Kostelano** [comment]
The change needed to be done for 3.10, but okay.
However, this is wrong.

Why did you change the other constants (except for the last one in every file)?

**Comment by wojsmol** [comment]
@Kostelano Other contacts have the same issue - no component specific when using as a override.

**Comment by Kostelano** [comment]
I have tested this item :red_circle: unsuccessfully on f0586c603bd00bcea17ac78eb6945b3e6fd8bd69<br /><br />This is not a valid change.

Test it (for example, create an override, install the nightly version and look at your new constants) and you can see why. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35424">issues.joomla.org/tracker/joomla-cms/35424</a>.</sub>

**Comment by wojsmol** [comment]
@Kostelano I removed my additional changes.

**Comment by Kostelano** [comment]
Thanks! I can't submit a test yet as I have doubts about line `JLIB_RULES_SETTING_NOTES_ITEM_COM_CATEGORIES`. There should probably be a [section ](https://github.com/joomla/joomla-cms/pull/13523/files#diff-f1024a3d762a6e4f91b495d405ee0d1fbb878f015f6b458022978e4157d22891R431) similar to [JLIB_RULES_SETTING_NOTES_ITEM_COM_CONTENT_ARTICLE](https://github.com/joomla/joomla-cms/pull/13523/files#diff-5f0c2b2c3ef0a978372712880c2c699bfac83fa91167077b5c030d190a1336f9R211).

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Review by HLeithner — APPROVED** [review]
Looks good to me, the original JLIB_RULES_SETTING_NOTES_ITEM is still defined lib_joomla.ini

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
