### PR TITLE
[3.10] Fix calendar error in IE11

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/32756#issuecomment-942315977

### Summary of Changes
Add CustomEvent polyfill for IE

### Testing Instructions
Open article editing in IE 11, 
open Browser dev console.
Try change publishing date for article

### Actual result BEFORE applying this Pull Request
Error in console

### Expected result AFTER applying this Pull Request
No error

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Fedik** [comment]
@rajeshstarlite  please test

**Comment by rajeshstarlite** [comment]
Hello @Fedik,

Thanks, it works now.

**Comment by Fedik** [comment]
@rajeshstarlite please go here https://issues.joomla.org/tracker/joomla-cms/35819
and click that button:
image

**Comment by rajeshstarlite** [comment]
I have tested this item :white_check_mark: successfully on 4c20c5a31bdcc481a2511694b665093033b63e28<br /><br />it works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35819">issues.joomla.org/tracker/joomla-cms/35819</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 4c20c5a31bdcc481a2511694b665093033b63e28<br /><br />Works good to me thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35819">issues.joomla.org/tracker/joomla-cms/35819</a>.</sub>

**Comment by zero-24** [comment]
Merging now so it can be shipped with the next update.

**Pull request merged**
