### PR TITLE
Update repeatable.php

### PR DESCRIPTION
**Pull request by muba4**
Nesteds subform

В строке 68 надо суффикс у имени поля поменять с 'X' на '0'.
Тогда вложенные subform (одна в другую) начинают формировать нормальный JSON для записи в БД.

I'm sorry for my English. =D

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
google translation

> On line 68, change the field name suffix from 'X' to '0'.
Then the nested subforms (one within the other) begin to form normal JSON for writing to the database.

**Comment by muba4** [comment]
Simple Joomla 4 plugin (for test).
https://disk.yandex.ru/d/hi6n5Xu4-r7_zQ

See tab "Publishing" (down in fieldset "Metadata")  by Article creation or edition.

**Comment by Fedik** [comment]
You have to explain what you tries to fix, your original issue.

The changes here is wrong. And cannot be accepted.

**Comment by muba4** [comment]
> You have to explain what you tries to fix, your original issue.

Try installing the plugin. Link above. 

Without the suggested fixes, nested subforms are not correctly stored in the database. As a result, they cannot be used.

I can copy the plugin code here, but there will be a lot of code.

Copy it?

**Comment by Fedik** [comment]
No need whole plugin, enough just XML for subform.

But, I think you talking about this #35721 issue.
It was already fixed, you have to wait for 4.0.4

**Comment by muba4** [comment]
>No need whole plugin, enough just XML for subform.

main.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<form>
	<fields name="metadata">
		<fieldset name="jmetadata">
			<field
				name="quest"
				type="subform"
				label="Поле quest"
				description="Описание поля quest"
				multiple="true"
				buttons="add,remove"
				layout="joomla.form.field.subform.repeatable"
				formsource="/plugins/content/metatitle/subforms/guestions.xml"
				/>
		</fieldset>
	</fields>
</form>
```

guestions.xml
```
<?xml version="1.0" encoding="UTF-8"?>
				<form>
					<field name="question" type="textarea" cols="40" rows="8" label="Вопрос:" />
					<field
							name="answers"
							type="subform"
							label="Поле answers"
							description="Описание поля answers"
							multiple="true"
							buttons="add,remove"
							min="3"
							layout="joomla.form.field.subform.repeatable"
							formsource="/plugins/content/metatitle/subforms/answers.xml"
						/>
				</form>
```

answers.xml
```
<?xml version="1.0" encoding="UTF-8"?>
						<form>
							<field
								name="answer"
								type="text"
								label="Ответ:"
								description="Описание поля answer" />
						</form>
```

**Comment by Fedik** [comment]
yeah, well, I think it the same as #35721 
and it already fixed,

You can try to test on latest 4.0-dev branch, or using nightly-builds https://developer.joomla.org/nightly-builds.html

**Comment by Fedik** [comment]
Closed in reason stated above. Thanks for PR.

**Comment by muba4** [comment]
Don't work.

Before test:

1.  Update Joomla from 4.0.3 to Joomla ‎4.0.4-dev‎4.0.4-dev (https://developer.joomla.org/nightlies/Joomla_4.0.3_to_4.0.4-dev-Development-Patch_Package.zip)
2. Updated plugin: https://disk.yandex.ru/d/tgSogz6hF6AjZA
**main.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<form>
	<fields name="metadata">
		<fieldset name="jmetadata">
<!-- new code from: https://github.com/joomla/joomla-cms/pull/35726#issue-1014053544 -->
<field
        name="subform_parent"
        label="Subform Parent"
        type="subform"
        multiple="true"
        buttons="add,remove"
>
    <form>
        <field
                name="test_text"
                label="Test Text"
                type="text"
        />
        <field
                name="child_subform"
                label="Child Subform"
                type="subform"
                multiple="true"
        >
            <form>
                <field
                        name="child_text"
                        label="Child Field"
                        type="text"
                />
            </form>
        </field>
    </form>
</field>
<!-- end new code -->
		</fieldset>
	</fields>
</form>
```
3. before Test: (**Ctrl + F5** - for browser cash clean an Article Edit and/or New Page)
4. 
image
5. 
image

_Пичалька_ =(

**Comment by Fedik** [comment]
Test with Full_Package. 
In some reason Patch_Package is incomplete.

**Comment by muba4** [comment]
> Test with Full_Package.

It's work! =)

Спасибо! ))

**Pull request closed without merging**
