### PR TITLE
Fix for Issue #13588 - mod_articles_categories - Fatal error: Class 'ContentHelperRoute' not found...

### PR DESCRIPTION
**Pull request by joomlabeat**
Pull Request for Issue #13588.

### Summary of Changes
Moved the inclusion of ContentHelperRoute Class from the helper.php to the mod_articles_categories.php

### Testing Instructions
Create a module to list categories of a parent category. The module should work.

### Documentation Changes Required
No changes are required.

### CODE REVIEW

**Comment by bertmert** [comment]
@joomlabeat 
I could reproduce the issue in current Staging (3.7.0) only 

- with enabled cache (configuration) and after second loading of page,
- only on a page like Featured Contacts or Login.

Could you please check and complete the testing instructions if you can confirm that. Thank you.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 82451246c398ff120cf0da6d879638a318558d0a<br /><br />I was able to re-procedure this error and this PR fixed it.

From code review, when cache data is found, the file modules/mod_articles_categories/helper.php won't be required, so ContentHelperRoute is not registered and not available for using in module layout file, thus fatal error happens

For tester, you want to test it;

1. Make sure cache is enabled for your site and the module

2. Assign the module to a menu item not related to com_content. Then access to that menu item, from the second time you should see the error. Apply the patch, the error should be gone..

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13590">issues.joomla.org/tracker/joomla-cms/13590</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 82451246c398ff120cf0da6d879638a318558d0a<br /><br />@joomlabeat thanks! Explains an issue a came across recently, this is fixing that indeed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13590">issues.joomla.org/tracker/joomla-cms/13590</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13590">issues.joomla.org/tracker/joomla-cms/13590</a>.</sub>

**Comment by Warolf** [comment]
I had the same problem but in the 3.6.5 version, i add the fix you have here and all good just passed 8 hours and all good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13590">issues.joomla.org/tracker/joomla-cms/13590</a>.</sub>

**Pull request merged**
