### PR TITLE
Minor changes on README.md & README.txt

### PR DESCRIPTION
**Pull request by spahno**
### Summary of Changes
changed the "What is this?" headline to "Overview" for better comprehensibility

### Testing Instructions
Install the 4.0-dev

### CODE REVIEW

**Comment by atpatil11** [comment]
I have tested this item :white_check_mark: successfully on c9e36a4902b41b51ced2f72417af5ae036e6699c<br /><br />Confirmed Patch. 
Thanks for the contribution, Spahno.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26857">issues.joomla.org/tracker/joomla-cms/26857</a>.</sub>

**Comment by vaibhavsTekdi** [comment]
I have tested this item :white_check_mark: successfully on c9e36a4902b41b51ced2f72417af5ae036e6699c<br /><br />Tested successfully.

#jpbf19 #test1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26857">issues.joomla.org/tracker/joomla-cms/26857</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26857">issues.joomla.org/tracker/joomla-cms/26857</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
