### PR TITLE
s/Append/Prepend

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/Append/Prepend

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 311f6a6e0f4083a4075d2edd3b6e9d099cb3013d<br /><br />Tested successfully in 3.9.26-dev of 3 March.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32570">issues.joomla.org/tracker/joomla-cms/32570</a>.</sub>

**Comment by richard67** [comment]
> Thanks!

@wilsonge Normally you say that after merging. But this one hasn't been merged yet. Mistake? Or me too impatient?

**Comment by wilsonge** [comment]
Mistake :) I thought I'd hit merge

**Pull request merged**
