### PR TITLE
[4.0][com_banners] fix  Undefined variable: db when sticky

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
fix PHP Notice:  Undefined variable: db  in `administrator/components/com_banners/Table/BannerTable.php on line 324`

### Testing Instructions
create a banner
set it pinned unpinned
check error log

### Expected result
no notice

### Actual result
notice

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4b1ffabcd7898155edb57dccbade7823acee1a3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26512">issues.joomla.org/tracker/joomla-cms/26512</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4b1ffabcd7898155edb57dccbade7823acee1a3b<br /><br />It took a while until I noticed you meant pin/unpin in the list view and not in the edit view ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26512">issues.joomla.org/tracker/joomla-cms/26512</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26512">issues.joomla.org/tracker/joomla-cms/26512</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
