### PR TITLE
[4.0] [plg_system_logrotation] Convert to prepared statement

### PR DESCRIPTION
**Pull request by HLeithner**
# Summary of Changes
Updated SQL queries to prepared statements and made some cleanups around the queries.

### Testing Instructions
Use the plugin in all ways you can think of.

wait for the timeout and reload the page this should trigger a query call, maybe check with the debugger plugin.

### Expected result
Nothing changed.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 20d06eab7d5ff164a0fc4ac7e4d60aeeacb30f34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25505">issues.joomla.org/tracker/joomla-cms/25505</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 20d06eab7d5ff164a0fc4ac7e4d60aeeacb30f34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25505">issues.joomla.org/tracker/joomla-cms/25505</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25505">issues.joomla.org/tracker/joomla-cms/25505</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
