### PR TITLE
[4.0] Update readme.md

### PR DESCRIPTION
**Pull request by brianteeman**
Remove reference to jenkins

### CODE REVIEW

**Comment by zero-24** [comment]
didn't this also get merged from staging to 4.0 like all other things?

**Comment by brianteeman** [comment]
as the two readme are quite different I thought it would be just easier (and much much quicker) to do it this way. especially as the readme is a public facing file at all times. unlike other pr which are not public facing until a release is made

**Comment by brianteeman** [comment]
thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
