### PR TITLE
[5.0] Use Joomla dialog for confirmation dialog, instead of old school confirm()

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Use Joomla dialog for confirmation dialog, instead of old school confirm()
Also an example how it could be used in other places.

### Testing Instructions
Apply patch, run `npm install`.
Trash some Article, and then try empty the trash.

### Actual result BEFORE applying this Pull Request
You get old school confirm() dialog

### Expected result AFTER applying this Pull Request
You get Joomla dialog

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

Reference:
 - https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Comment by HLeithner** [comment]
image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ee1e19949cf16381d31c9882989a2c3f595ece95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41434">issues.joomla.org/tracker/joomla-cms/41434</a>.</sub>

**Comment by heelc29** [comment]
I have tested this item :red_circle: unsuccessfully on ee1e19949cf16381d31c9882989a2c3f595ece95<br /><br />Translation (`JYES`, `JNO`) not loaded for footer buttons
image
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41434">issues.joomla.org/tracker/joomla-cms/41434</a>.</sub>

**Comment by heelc29** [comment]
system tests are failing
image

**Comment by Fedik** [comment]
> system tests are failing

Yeap, I did not checked, but I think cypress expecting old confirm()

**Comment by Fedik** [comment]
Test can be fixed only after updating Firefox for Cypress

**Comment by HLeithner** [comment]
> Test can be fixed only after updating Firefox for Cypress

Test running now with 

* Cypress:        12.17.4
* Browser:        Firefox 114 (headless)
* Node Version:   v20.5.0

**Comment by Fedik** [comment]
After removing tests it is working now.

**Comment by HLeithner** [comment]
thanks

**Comment by HLeithner** [comment]
I think we need a migration documentation?

**Comment by brianteeman** [comment]
> I think we need a migration documentation?

yes please as there are other places we can use this

**Comment by Fedik** [comment]
It is part of
- https://github.com/joomla/Manual/pull/99

Or need something more specific?

**Pull request merged**
