### PR TITLE
[4.0] fix the path for Cassiopeia js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Moved the file `menu-metismenu.es6.js` from `build/media_source/templates/cassiopeia/js/mod_menu/` to `build/media_source/templates/site/cassiopeia/js/mod_menu/` (there is a `site` missing there)
- Adjust the layout to use the correct path

### Testing Instructions

Enable the dropdown layout for the frontend menu. Check that the metismenu script is loaded

### Documentation Changes Required

@wilsonge this is kinda important for the Child templates
@richard67 I think you need to add the old paths to the files removed

### CODE REVIEW

**Comment by brianteeman** [comment]
Why?


This is not Cassiopeia specific

**Comment by dgrammatiko** [comment]
> Why?

The child templates are already configured (check the HTML helper file for the overrides) to look at the folders `media/templates/site` and `media/templates/administrator` depending on if the template is front end or back end. The current path was picked out of the blue, it doesn't follow any rules...

**Comment by brianteeman** [comment]
Sorry was reading on my phone. Ignore my comment

**Comment by wilsonge** [comment]
OK Let's get a quick test but this looks good to me

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on fe15fecdae33033050b05ba54a3fa6ce8ef02389<br /><br />Path is correct and script is loaded after the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35024">issues.joomla.org/tracker/joomla-cms/35024</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fe15fecdae33033050b05ba54a3fa6ce8ef02389<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35024">issues.joomla.org/tracker/joomla-cms/35024</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35024">issues.joomla.org/tracker/joomla-cms/35024</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
