### PR TITLE
[CS] Fixing JImage constants

### PR DESCRIPTION
**Pull request by piotr-cz**
### Summary of Changes
1) Switched from hardcoded variables to class constants when checking for crop type
2) Using `static` instead of `self` in methods

This is a coding style change and doesn't have any effects on functionality.
Only change would if one would extend the `JImage` class: developer doesn't have to define JImage constants again in extended class.

### Testing Instructions
The only place where _JImage_ is used in J! core is template editing feature:
1. Go to _Extensions > Templates > Templates > Protostar Details and Files_
2. Click on _template_preview.png_
3. Make sure cropping and resizing works as expected

### Expected result
Unit suites should pass
Manual tests pass

### Actual result
same as expected result

### Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by mbabker** [comment]
From the looks of things, there isn't actually anything gained by calling `static::CONSTANT` because it's still referring either to itself or a parent class.  It's not like late static bindings where it can resolve to a subclass if that's within the class chain, and https://secure.php.net/manual/en/language.oop5.constants.php#104260 seems to support that.

**Comment by piotr-cz** [comment]
What about scenario when I'd extend the `JImage` class and let's say add extra information in the `getImageFileProperties` method?

Any code that would call `self::getImageFileProperties` method would actually call the JImage class, not the extended one at least as I understand it

**Comment by mbabker** [comment]
The method calls are fine, it's the constants that I don't think this works on.

**Comment by piotr-cz** [comment]
Looks like you are right.
Constants shouldn't be overwritten in subclass and so referring to them with `static` keyword is misleading.

**Comment by piotr-cz** [comment]
I've kept `static` keyword only when referencing methods, however there is one more case - reference to [`$formats` array](https://github.com/joomla/joomla-cms/blob/3.7.0-beta3/libraries/joomla/image/image.php#L119-L125)

**Comment by mbabker** [comment]
That one's good, it's not private.  Looks fine to me.

**Comment by jonasgonka** [comment]
Issue can be closed since the modified class is deprecated. 
See /libraries/vendor/joomla/image/src:19

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14402">issues.joomla.org/tracker/joomla-cms/14402</a>.</sub>

**Comment by piotr-cz** [comment]
Thanks, @jonasgonka 
Superseeded by https://github.com/joomla-framework/image/pull/19

**Pull request closed without merging**
