### PR TITLE
[4] Remove unused com_media field "upload_mime_illegal"

### PR DESCRIPTION
**Pull request by ReLater**
All credits to @Kostelano . I only took over his closed pr https://github.com/joomla/joomla-cms/pull/39196

Closes https://github.com/joomla/joomla-cms/issues/38280

### Summary of Changes
- Remove field `upload_mime_illegal` from `com_media` settings.
- Deprecate associated language strings.

### Testing Instructions
- Code review shoud be sufficient after several confirmations that this field is not used in core. See comments: https://github.com/joomla/joomla-cms/issues/38280 and https://github.com/joomla/joomla-cms/pull/39196
- I you think it's worth it: Change/Add mime entries in `com_media` configuration in field `Forbidden MIME Types`.
  - Check if these settings have any influence on file uploads in the Media Manager. This should not be the case.

### Actual result BEFORE applying this Pull Request
- Settings ignored on file uploads in media manager.

### Expected result AFTER applying this Pull Request
- No change. Settings ignored on file uploads in media manager.

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ee054087bf952aab5f2c2062afdc1511b839a3a2<br /><br />J 4.2.7-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39453">issues.joomla.org/tracker/joomla-cms/39453</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ee054087bf952aab5f2c2062afdc1511b839a3a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39453">issues.joomla.org/tracker/joomla-cms/39453</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39453">issues.joomla.org/tracker/joomla-cms/39453</a>.</sub>

**Comment by ReLater** [comment]
I don't know what

> Documentation link for docs.joomla.org

means. I have adapted https://docs.joomla.org/Help4.x:Media:_Options , but ????

**Comment by carlitorweb** [comment]
Documentation changed ✔️ (https://docs.joomla.org/Help4.x:Media:_Options)

**Comment by obuisard** [comment]
Thank you @ReLater for the PR!

**Pull request merged**
