### PR TITLE
Code Style

### PR DESCRIPTION
**Pull request by asika32764**
.

### CODE REVIEW

**Comment by n9iels** [comment]
not sure, but I thought that that extra tab is only necessary when there are multiple variables with '=' signs

**Comment by mbabker** [comment]
It's an optional thing to align multiple variable assignments on the equal sign (using spaces, not tabs) in our code style rules.  The trends in our code right now are to align things.  Obviously, there isn't much to align to for a single variable.

**Comment by n9iels** [comment]
aha, thanks :)
But looks good to me :+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7262">issues.joomla.org/joomla-cms/7262</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks @asika32764 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7262">issues.joomla.org/joomla-cms/7262</a>.</sub>

**Pull request merged**
