### PR TITLE
[5.1] remove deprecated language strings from up-merge #42950

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

remove deprecated language strings - added again due merge conflict in #42950 @LadySolveig @bembelimen 
https://github.com/joomla/joomla-cms/pull/42950/files#diff-c958054a01e06914ff9d8d8f3f34f6eafac053a8927e6e3bfb51ceaaa7c39a3e

Now the two strings exist twice
https://github.com/joomla/joomla-cms/blob/d834f8123870c53cf908927de85c8bae368407af/administrator/language/en-GB/plg_system_privacyconsent.ini#L8-L9

https://github.com/joomla/joomla-cms/blob/d834f8123870c53cf908927de85c8bae368407af/administrator/language/en-GB/plg_system_privacyconsent.ini#L32-L33

### Testing Instructions

code review

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0a7a5f31ece0e78d1d9ae5836c69bd1c68349884<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42953">issues.joomla.org/tracker/joomla-cms/42953</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42953">issues.joomla.org/tracker/joomla-cms/42953</a>.</sub>

**Review by tecpromotion — APPROVED** [review]
Thanks @heelc29

**Comment by LadySolveig** [comment]
Thank you @heelc29

**Pull request merged**
