### PR TITLE
[4.4] Update deleted files list in script.php for 4.4.0-alpha1

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This pull request (PR) updates the list of files to be deleted on update in file "administrator/components/com_admin/script.php" to recent changes in the 4.4-dev branch in preparation for the first 4.4.0-alpha1 release.

In detail deleted files from following PR's are added:

- PR #40066 file
'/modules/mod_footer/mod_footer.php',
- PR #40092 file
'/modules/mod_users_latest/mod_users_latest.php',
- PR #40142 file
'/plugins/content/pagenavigation/pagenavigation.php',
- PR #40146 files
'/plugins/installer/folderinstaller/folderinstaller.php',
'/plugins/installer/override/override.php',
'/plugins/installer/packageinstaller/packageinstaller.php',
'/plugins/installer/urlinstaller/urlinstaller.php',
'/plugins/installer/webinstaller/webinstaller.php',
- PR #40174 files
'/plugins/privacy/actionlogs/actionlogs.php',
'/plugins/privacy/consents/consents.php',
'/plugins/privacy/contact/contact.php',
'/plugins/privacy/content/content.php',
'/plugins/privacy/message/message.php',
'/plugins/privacy/user/user.php',
- PR #40180 files
'/plugins/user/contactcreator/contactcreator.php',
'/plugins/user/joomla/joomla.php',
'/plugins/user/profile/profile.php',
'/plugins/user/terms/terms.php',
'/plugins/user/token/token.php',
- PR #39527 file
'/modules/mod_articles_category/mod_articles_category.php',
- PR #39535 file
'/modules/mod_articles_archive/mod_articles_archive.php',
- PR #40169 files
'/plugins/media-action/crop/crop.php',
'/plugins/media-action/resize/resize.php',
'/plugins/media-action/rotate/rotate.php',
- PR #40173 files
'/plugins/sampledata/blog/blog.php',
'/plugins/sampledata/multilang/multilang.php',
- PR #39552 file
'/modules/mod_articles_categories/mod_articles_categories.php',
- PR #39931 file
'/modules/mod_custom/mod_custom.php',
- PR #39628 file
'/modules/mod_related_items/mod_related_items.php',
- PR #40328 file
'/modules/mod_breadcrumbs/mod_breadcrumbs.php',
- PR #40216 files
'/plugins/system/accessibility/accessibility.php',
'/plugins/system/actionlogs/actionlogs.php',
'/plugins/system/debug/debug.php',
'/plugins/system/fields/fields.php',
'/plugins/system/highlight/highlight.php',
'/plugins/system/httpheaders/httpheaders.php',
'/plugins/system/jooa11y/jooa11y.php',
'/plugins/system/languagecode/languagecode.php',
'/plugins/system/languagefilter/languagefilter.php',
'/plugins/system/log/log.php',
'/plugins/system/logout/logout.php',
'/plugins/system/logrotation/logrotation.php',
'/plugins/system/privacyconsent/privacyconsent.php',
'/plugins/system/redirect/redirect.php',
'/plugins/system/remember/remember.php',
'/plugins/system/schedulerunner/schedulerunner.php',
'/plugins/system/sef/sef.php',
'/plugins/system/sessiongc/sessiongc.php',
'/plugins/system/skipto/skipto.php',
'/plugins/system/stats/stats.php',
'/plugins/system/tasknotification/tasknotification.php',
'/plugins/system/updatenotification/updatenotification.php',
- PR #40561 files
'/plugins/content/finder/finder.php',
'/plugins/content/joomla/joomla.php',
'/plugins/content/loadmodule/loadmodule.php',
'/plugins/content/pagebreak/pagebreak.php',
'/plugins/content/vote/vote.php',
- PR #40190 files
'/plugins/webservices/banners/banners.php',
'/plugins/webservices/config/config.php',
'/plugins/webservices/contact/contact.php',
'/plugins/webservices/content/content.php',
'/plugins/webservices/installer/installer.php',
'/plugins/webservices/languages/languages.php',
'/plugins/webservices/media/media.php',
'/plugins/webservices/menus/menus.php',
'/plugins/webservices/messages/messages.php',
'/plugins/webservices/modules/modules.php',
'/plugins/webservices/newsfeeds/newsfeeds.php',
'/plugins/webservices/plugins/plugins.php',
'/plugins/webservices/privacy/privacy.php',
'/plugins/webservices/redirect/redirect.php',
'/plugins/webservices/tags/tags.php',
'/plugins/webservices/templates/templates.php',
'/plugins/webservices/users/users.php',
- PR #40205 files
'/plugins/workflow/featuring/featuring.php',
'/plugins/workflow/notification/notification.php',
'/plugins/workflow/publishing/publishing.php',

### Testing Instructions

Code review.

Or if you want to make a real test, update a 4.3.0-rc1 or recent 4.3 nightly build to the last 4.4 nightly build to get the actual result, and update a 4.3.0-rc1 or recent 4.3 nightly build to the update package built by Drone for this PR to get the expected result.

### Actual result BEFORE applying this Pull Request

The files mentioned above are still present after updating from a 4.3.0-rc1 or recent 4.3 nightly build.

### Expected result AFTER applying this Pull Request

The files mentioned above have been deleted after updating from a 4.3.0-rc1 or recent 4.3 nightly build.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 7ff03abdb3131360a11345e0e06fd513b0c2085e<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40231">issues.joomla.org/tracker/joomla-cms/40231</a>.</sub>

**Comment by richard67** [comment]
I have to add files from #40180 and #40174 either to this PR here or to a future one if this one here gets merged before.

**Comment by sandewt** [comment]
Your instructions are very readable 👍 I will take a look.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 898e85a14001d5e699ea21c21195c0d70b4530b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40231">issues.joomla.org/tracker/joomla-cms/40231</a>.</sub>

**Comment by laoneo** [comment]
I guess this one should be changed to draft so people are not testing it. It will then be merged before we ship the first alpha.

**Comment by richard67** [comment]
> I guess this one should be changed to draft so people are not testing it. It will then be merged before we ship the first alpha.

@laoneo I would prefer not to wait with merging until just before alpha because people might test the nightly builds, too, which could show us if we make mistakes with that. In the mean time I would check when PR's have been merged and make a new PR when I see there is again a bunch of deleted files.

Of course if my PR's of this kind will be merged anyway by review, I can set it to draft so people don't waste time with testing. On the other hand, a test is never bad.

**Comment by sandewt** [comment]
Missing in list, see #40173

'plugins/sampledata/testing/src/Extension/Testing.php'

**Comment by richard67** [comment]
@sandewt Yes, and others might follow. I have a tool which I run periodically and then update this PR as long as not merged yet. Will maybe later change it to draft status. No need for testing now. But thanks so far.

**Comment by richard67** [comment]
@sandewt Ah, sorry, I forgot: The sample data plugin is something which we only have in development environments, i.e. git clones. But we don't have that in the regular (alpha or beta or rc or stable releases) installation packages and also not in nightly builds. That's why it will not go into the list of deleted files and folders, and we will not delete that file on update. So nothing to do for that file "plugins/sampledata/testing/testing.php" from PR #40173 .

**Comment by richard67** [comment]
@laoneo The PR is still up to date, so if you want I can change it back from draft to ready and you can merge, and the next PR I make after another bunch of merged relevant PRs.

**Comment by laoneo** [comment]
Because they need some updates when we merge further prs which remove files. I want to make sure that people are not wasting their time testing these pr's.

**Comment by richard67** [comment]
> Because they need some updates when we merge further prs which remove files. I want to make sure that people are not wasting their time testing these pr's.

@laoneo This is not what thatblabel has been made for. It has been made for PRs where maintainers request changes. Tjisbis not the case here.

**Comment by laoneo** [comment]
I have it removed.

**Comment by richard67** [comment]
@laoneo Sorry for my possibly too harsh words, I was unnecessarily too upset. I understand what you wanted to achieve with setting that label, and if you insist on it I will put this PR back to draft status. But I think we should not wait with merging it until short before alpha 1, I think we should merge it soon so we and other people can test updating older versions to 4.4-dev nightly builds with the old files of plugins and modules being removed at the update so we can see if we have issues with that on particular environments.

**Comment by brianteeman** [comment]
@richard67 If anythng the files should be added to the scrript with the pr to ensure there is no delay. like they used to be

**Comment by laoneo** [comment]
I would wait till the last plugin conversions are merged. @MacJoom is on it. And then we can merge this one.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
