### PR TITLE
Fix for Module Positions inaccessible wit Hathor admin Template

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #12607 .
### Testing Instructions

Set default template to Hathor and try to change the module position

Also test #11040 with Isis template, to be sure nothing broken
### Documentation Changes Required

none

### CODE REVIEW

**Comment by infograf768** [comment]
Although this lets now display a modal to choose positions, it also transforms many fields to chosen dropdowns in Hathor.
Status, Access, Language, etc. etc.

screen shot 2016-10-30 at 08 23 03
This is therefore insufficient and can't be merged as is.

**Comment by Fedik** [comment]
> it also transforms many fields to chosen dropdowns in Hathor.

not really, this pull remove Chosen from the position input.
The Chosen actually was added in #11040, but was broken in the Hathor 😄 

but I will check, what can do here

**Comment by Fedik** [comment]
@infograf768 please test again 😉

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 314cb6e61fca48957b410e3767083093688d9b47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12621">issues.joomla.org/tracker/joomla-cms/12621</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 314cb6e61fca48957b410e3767083093688d9b47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12621">issues.joomla.org/tracker/joomla-cms/12621</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12621">issues.joomla.org/tracker/joomla-cms/12621</a>.</sub>

**Comment by zero-24** [comment]
Merged. Thanks!

**Pull request merged**
