### PR TITLE
[4.0] Fixing useless blank img tag in admin menu

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27009

### Summary of Changes
Wrong copy/paste of a J4 useless case from 3.x. :)

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/27009

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 375a1bbe3fb9eb7d91d7b0ce2a7808363c118eb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27036">issues.joomla.org/tracker/joomla-cms/27036</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 375a1bbe3fb9eb7d91d7b0ce2a7808363c118eb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27036">issues.joomla.org/tracker/joomla-cms/27036</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27036">issues.joomla.org/tracker/joomla-cms/27036</a>.</sub>

**Comment by Quy** [comment]
Apply same fix here?
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_submenu/Menu/Menu.php#L181

**Comment by infograf768** [comment]
> Apply same fix here?
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_submenu/Menu/Menu.php#L181

Looks like we do not need that else at all here. To test I added some menus not containing any home page.
Can you confirm?

**Comment by Quy** [comment]
```
if ($iconImage)
{
	if (substr($iconImage, 0, 6) == 'class:' && substr($iconImage, 6) == 'icon-home')
	{
		$iconImage = '<span class="home-image icon-featured" aria-hidden="true"></span>';
		$iconImage .= '<span class="sr-only">' . Text::_('JDEFAULT') . '</span>';
	}
	elseif (substr($iconImage, 0, 6) == 'image:')
	{
		$iconImage = '&nbsp;<span class="badge badge-secondary">' . substr($iconImage, 6) . '</span>';
	}
	else
	{
		$iconImage = '<span>' . HTMLHelper::_('image', $iconImage, null) . '</span>';
	}
}
```
Here is the attribute `icon="file-alt"` in the XML file. It is not an image file, thus, the blank image tag. 
Removing the code suggested in this PR would discard the value which probably is not the desired result.
For `image:`, I would not expect it to be wrapped in a span as a badge.
The above code has to be rewritten.

**Comment by infograf768** [comment]
> For image:, I would not expect it to be wrapped in a span as a badge.

I am not sure you understood that part.
It specially deals with menus containing a home page in multilang. 
Please look at the presets where image: corresponds to precise kind of sql.

sql_select="a.id, a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:', l.lang_code) END ELSE 'image:mod_languages/icon-16-language.png' END AS icon"

and further 
icon="{sql:icon}"

The badge replaces the flag we have in 3x.

As far as the else is concerned, it is useless imho in the dashboard part (your last comment https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_submenu/Menu/Menu.php#L181 ) and I will remove it.

In this PR or another one. if another one please set this again as rtc.

**Comment by Quy** [comment]
So `icon="file-alt"` will have no effect/be ignored for menus?

**Comment by infograf768** [comment]
> So icon="file-alt" will have no effect/be ignored for menus?

Apparently yes, when using the alternate or default presets. What is used in these is `$iconClass`.
I guess we could take off these `icon="whatever"` in these presets, except evidently for the menus containing the Homes using the specific sql with `icon="{sql:icon}"`

It is used though in the other presets when displayed as default dashboard or module added to dashboard.

Just test taking `icon="list"` off in menus.xml preset and you will get:

Screen Shot 2019-11-12 at 08 34 01

instead of
Screen Shot 2019-11-12 at 08 35 52


Will now modify `Menu.php` as we do not need the else in the submenu module.

### Note: 
if we decide to take off in another PR the useless icon(s) in the alternate and default presets, we will not need any more to have the else with `$iconImage = '';` in `default_submenu.php`

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f5f1546c040660514912218b1c790ae3556105b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27036">issues.joomla.org/tracker/joomla-cms/27036</a>.</sub>

**Comment by infograf768** [comment]
Back to RTC as the last change is simple.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27036">issues.joomla.org/tracker/joomla-cms/27036</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
