### PR TITLE
CodeMirror 5.3

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
CodeMirror got an update so here's the CodeMirror update. 

Release notes: http://codemirror.net/doc/releases.html

### CODE REVIEW

**Comment by wilsonge** [comment]
Someone got there ahead of you this time :p see https://github.com/joomla/joomla-cms/pull/6589

**Comment by okonomiyaki3000** [comment]
@wilsonge Don't use that one. It's not correct. Use mine.

**Comment by okonomiyaki3000** [comment]
CodeMirror has a lot of addons, we want to use some but we definitely don't need all. So it's best to compile all the ones we do need into an addons file so they can be included easily. Also, everything should be minified. I have a shell script that does this for me so it's easy for me to keep CM up to date. I don't really think I should be a single point of failure for this though.

**Comment by wilsonge** [comment]
I'll make a docs page tomorrow so we have instructions for tiny and code mirror in one place :) Thanks for the information tho - it's really appreciated!

**Comment by brianteeman** [comment]
Elijah can you make sure to share your script on the docs page George
creates to avoid the "single point of failure"

On 8 April 2015 at 01:31, George Wilson <notifications@github.com> wrote:

> I'll make a docs page tomorrow so we have instructions for tiny and code
> mirror in one place :) Thanks for the information tho - it's really
> appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6686#issuecomment-90768262>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by okonomiyaki3000** [comment]
@brianteeman I was thinking that it might be better to remake it with something like grunt which might somehow preferable to bash. What do you think?

**Comment by brianteeman** [comment]
No comment from me on technical details - its beyond my payscale.

My concern is the bus not how it is driven ;)

On 8 April 2015 at 09:22, Elijah Madden <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I was thinking that it
> might be better to remake it with something like grunt which might somehow
> preferable to bash. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6686#issuecomment-90839613>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
@okonomiyaki3000 As long as it works and isn't some funny esotheric format, I don't mind if it is bash or grunt :smile:

**Comment by okonomiyaki3000** [comment]
Here https://github.com/okonomiyaki3000/joomla-codemirror-builder

**Comment by okonomiyaki3000** [comment]
This is the first time I've used Grunt so please speak up if you notice that I've done anything weird. There's probably a lot of room for improvement but somehow I feel this is better than a bash script.

**Comment by okonomiyaki3000** [comment]
5.2 is out. http://codemirror.net/doc/releases.html

Also, I updated the builder, making it a bit easier to understand: https://github.com/okonomiyaki3000/joomla-codemirror-builder

**Comment by okonomiyaki3000** [comment]
5.3 now. It doesn't seem to be an urgent update. Maybe it doesn't contain anything special for Joomla users but it's best to stay up to date. 

Also, I've updated the builder again. Now using bower instead of curl to get the latest CM, it greatly simplifies the grunt tasks.

**Comment by okonomiyaki3000** [comment]
I must be confused. I guess I have too many branches.

**Pull request closed without merging**
