### PR TITLE
[4.0] Edit article via button Edit in menu item single article

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/19316.

### Summary of Changes
In the file [/joomla-cms/administrator/components/com_content/Field/Modal/ArticleField.php](https://github.com/joomla/joomla-cms/blob/57a4fdecaf88794f54b80d7406572bd446a86dc7/administrator/components/com_content/Field/Modal/ArticleField.php#L96) we use JavaScript (document.getElementById("' . $this->id . '_id").value) in the edit URL. But up to now this command is not executed.
I am not sure where this is planned. This PR is my first idea for solving the error.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/19316

Steps to reproduce the issue

- Installed staging 4.
- Installed testing data.
- Open "All Menu Items".
- Open menu item "Home" (Edit view). Type is : "Single Article"
- Click button "Edit" for editing the article "Joomla! Testing" .
  

### Expected result

Edit form opens with correct content.

### Actual result

Edit form opens but empty title and empty editor.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 05d8e76e6a367c9997131a34d32500bcb07eacb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19390">issues.joomla.org/tracker/joomla-cms/19390</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by wilsonge** [comment]
@astridx can you fix conflicts here please and I'll get this merged :)

**Comment by astridx** [comment]
I hope I have solved everything correctly.
The conflict was in the file bootstrap-init.min.js, which consists of only one line. I minimized the file bootstrap-init.js and saved it as bootstrap-init.min.js

**Comment by astridx** [comment]
@wilsonge Did I made a mistake or did you forget?

**Comment by shivamdiehard** [comment]
I have tested this item :white_check_mark: successfully on c34bb87028d4b7abdc892e9a83984fce78d591bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19390">issues.joomla.org/tracker/joomla-cms/19390</a>.</sub>

**Pull request merged**
