### PR TITLE
correct closing button tags in 2 modals - backend

### LINKED ISSUE #7906: Misclosed HTML tag in default.php template file of backend module: mod_multilangstatus
I am trying to eliminate as many HTML validation errors in backend as possible

I noticed that in J3.4.4 and staging branch too:

https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_multilangstatus/tmpl/default.php

Their is a `<button>` HTML Tag closed with an `</a>`

`$footer = '<button class="btn" data-dismiss="modal" aria-hidden="true">' . JText::_('JTOOLBAR_CLOSE') . '</a>';`

### PR DESCRIPTION
**Pull request by wojsmol**
This PR fixes two minor errors introduced by @dgt41 in PR https://github.com/joomla/joomla-cms/pull/6595 - `</button>` instead of `</a>` in the footer of modal windows for user notes and mod_multilangstatus.

fixes https://github.com/joomla/joomla-cms/issues/7906

### CODE REVIEW

**Comment by dgt41** [comment]
@test OK!
Thanks for correcting this obvious mistake!

**Comment by infograf768** [comment]
Test ok here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7907">issues.joomla.org/joomla-cms/7907</a>.</sub>

**Comment by infograf768** [comment]
2 good tests. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7907">issues.joomla.org/joomla-cms/7907</a>.</sub>

**Comment by wojsmol** [comment]
@dgt41 and @infograf768 thank you for testing.

**Comment by ggppdk** [comment]
Tests ok, fixes #7906

**Pull request merged**
