### PR TITLE
Fix getString call to the post data

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Fix getString call to the post data

### Testing Instructions

review

### Expected result

getString just accepts two parameters see: https://api.joomla.org/cms-3/classes/JInput.html#method_getString

### Actual result

getString is called with three parameters

### Documentation Changes Required

none

### Reporter to the JSST

@sandewt

### CODE REVIEW

**Comment by wilsonge** [comment]
We should fix this in the other places in the file https://github.com/zero-24/joomla-cms/blob/516563e529c52a1c827f6c93db408816e3b68b12/components/com_search/controller.php#L61-L63

**Comment by zero-24** [comment]
I have not noticed them before. Done with the last commit thanks @wilsonge

**Review by wilsonge — APPROVED** [review]

**Comment by sandewt** [comment]
In the class Jinput the default = null;
* getWord($name, $default = null)
* getUint($name, $default = null)

So I think:
```php
$post['ordering'] = $this->input->post->getWord('ordering', null);
$post['limit']    = $this->input->post->getUInt('limit', null);
```

Could be:
```php
$post['ordering'] = $this->input->post->getWord('ordering');
$post['limit']    = $this->input->post->getUInt('limit');

```

Tested: search for 'joomla'
```php
$post['ordering']     = $this->input->post->getWord('');
$post['searchphrase'] = $this->input->post->getWord('searchphrase', 'all');
$post['limit']        = $this->input->post->getUInt('');
echo '<pre>';
var_dump($post);
echo '</pre>';
die;
```
Result:
```php
array(4) {
  ["searchword"]=>
  string(6) "joomla"
  ["ordering"]=>
  NULL
  ["searchphrase"]=>
  string(3) "all"
  ["limit"]=>
  NULL
}
```

Or I be wrong?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17546">issues.joomla.org/tracker/joomla-cms/17546</a>.</sub>

**Comment by sandewt** [comment]
The same issue is of course for line 48:
```php
$searchword = trim(str_replace($badchars, '', $this->input->post->getString('searchword', null)));
```
```php
$searchword = trim(str_replace($badchars, '', $this->input->post->getString('searchword'))); // ???
```
It is something confusing, because you can use another option:
```php
$searchword = trim(str_replace($badchars, '', $this->input->get('searchword', null, post)));
```
What is wisdom?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17546">issues.joomla.org/tracker/joomla-cms/17546</a>.</sub>

**Comment by zero-24** [comment]
done

**Pull request merged**
