### PR TITLE
[com_users] groups view: Add enabled/disabled users counting

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR, as done in many other views, adds enabled/disabled users counting with links to com_users groups view.

Also:
- Minor code style changes
- Makes the delete validation js more portable (no php vars)
- Adds missing no wraping columns
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Go to "Users" -> "Groups"
3. Test the users countings for each group
4. Also create a group and assigna a user to that group, then try to delete that group. First js warning say yes, the second js say no and check the group is not deleted.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0c6a9e300cf69e6e67bbcef5f57f0e2a09729b24<br /><br />Tested ok but it seems a bit squashed and tight on the right hand side as shown in your screenshots<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 0c6a9e300cf69e6e67bbcef5f57f0e2a09729b24<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by brianteeman** [comment]
@andrepereiradasilva could you have a look at increasing the column width please or something to increase the space between the count and the ID. Maybe its just a trick of the mind on a large screen as there are no other columns but they look very close together<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by andrepereiradasilva** [comment]
better?

image

If ok, no need to test again, just changed the columns titles

**Comment by brianteeman** [comment]
No not really. Adding the title would not be consistent with the other views

I was thinking more like changing the width from 1% to something like 5%

But maybe its just me

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> No not really. Adding the title would not be consistent with the other views

Yes it would. See the menus view.

image

**Comment by brianteeman** [comment]
ah

On 21 April 2016 at 11:11, andrepereiradasilva <notifications@github.com>
wrote:

> No not really. Adding the title would not be consistent with the other
> views
>
> Yes it would. See the menus view.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/14705501/cda1cce6-07b1-11e6-8bc1-ee37af2be2c2.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10012#issuecomment-212842932>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
BTW on mobile view the titles dissapear

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6c9eeac28742635375b5dc06fbd0b1dd2ce43099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by brianteeman** [comment]
OK - I will shut up and say thanks for the latest change ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok i detected a problem in the counting, need to make some changes. sorry

**Comment by andrepereiradasilva** [comment]
ok, so the counting wasn't working properly.
If you have 2 oe more users enabled in the same group the result has "1", now that is corrected.

**Comment by andrepereiradasilva** [comment]
@brianteeman @MATsxm can you just retest the count of users part
Put two or more users in the same group and the same state and check if now the count is correct.

**Comment by brianteeman** [comment]
Will do tonight

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 2c6d35c9427a62393e75766d51280991aaf56b44<br /><br />Everything looks ok here, also with the counting system...
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2c6d35c9427a62393e75766d51280991aaf56b44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10012">issues.joomla.org/joomla-cms/10012</a>.</sub>

**Pull request merged**
