### PR TITLE
[4.1] spelling preform/perform

### PR DESCRIPTION
**Pull request by brianteeman**
code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 598042b78634a5424aaef20a5d93e08a8bd78bca<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38056">issues.joomla.org/tracker/joomla-cms/38056</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 598042b78634a5424aaef20a5d93e08a8bd78bca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38056">issues.joomla.org/tracker/joomla-cms/38056</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38056">issues.joomla.org/tracker/joomla-cms/38056</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
