### PR TITLE
[4.0] hidden-xs-up

### PR DESCRIPTION
**Pull request by brianteeman**
Replace class on legend to sr-only to make it not displayed

Remove hidden-xs-up class on div which should not be present

code review

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8c6bfb3ceab6293fd29558bf240a54227a2fc2de<br /><br />Yep, as I said here
https://github.com/joomla/joomla-cms/pull/30813#issuecomment-702040393<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30837">issues.joomla.org/tracker/joomla-cms/30837</a>.</sub>

**Comment by infograf768** [comment]
RTC. Obvious PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30837">issues.joomla.org/tracker/joomla-cms/30837</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
