### PR TITLE
Update to include MariaDB and remove SQL Server in README (.txt and .md)

### PR DESCRIPTION
**Pull request by robertsilen**
Considering the technical requirements (https://manual.joomla.org/docs/next/get-started/technical-requirements/) include MariaDB, I humbly suggest the README.txt should include MariaDB too. I removed "SQL Server" from list of databases, as mentioned in another discussion (https://github.com/joomla/joomla-cms/pull/43343). There is a separate PR for the .md version of the README.

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Please combine your PRs into one under the v4.4 branch as it will be upmerged to v5.1. Thanks.

**Comment by robertsilen** [comment]
> Please combine your PRs into one under the v4.4 branch as it will be upmerged to v5.1. Thanks.

I was told [in PR for 4.4](https://github.com/joomla/joomla-cms/pull/43343) to make a PR for 5.1 as this content is relevant for 5.1 and not 4.4. So I presume I should not go back on this? 

Do you want me to merge this with the [PR for README.md](https://github.com/joomla/joomla-cms/pull/43367)?

**Comment by Quy** [comment]
> I was told [in PR for 4.4](https://github.com/joomla/joomla-cms/pull/43343) to make a PR for 5.1 as this content is relevant for 5.1 and not 4.4. So I presume I should not go back on this?

Commented in the other PR.

> Do you want me to merge this with the [PR for README.md](https://github.com/joomla/joomla-cms/pull/43367)? Not sure how to do that.

Apply the change from the other branch to this branch (patch-4).

**Comment by robertsilen** [comment]
> > I was told [in PR for 4.4](https://github.com/joomla/joomla-cms/pull/43343) to make a PR for 5.1 as this content is relevant for 5.1 and not 4.4. So I presume I should not go back on this?
> 
> Commented in the other PR.
> 
> > Do you want me to merge this with the [PR for README.md](https://github.com/joomla/joomla-cms/pull/43367)? Not sure how to do that.
> 
> Switch to patch-4 branch. Apply the change from the other branch.

This PR for 5.5 includes MariaDB and SQL Server modifications to README.txt and README.md now. For 4.4 version there is [this PR](https://github.com/joomla/joomla-cms/pull/43343).

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1205699293a2407b7cccbada7864a684f6ea2f5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43368">issues.joomla.org/tracker/joomla-cms/43368</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1205699293a2407b7cccbada7864a684f6ea2f5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43368">issues.joomla.org/tracker/joomla-cms/43368</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43368">issues.joomla.org/tracker/joomla-cms/43368</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @robertsilen and for review @Quy @viocassel

**Pull request merged**
