### PR TITLE
[4.2] Fix template override actions

### PR DESCRIPTION
**Pull request by brianteeman**
This fixes a bug exposed in my own pr #38447

That PR added an action dropdown button When you have overrides. See the original PR for details

However it also added the dropdown when the file was open for editing but at that point it can be selected because it is never active.

This PR removes the button when the file is open for editing.

A better PR would be to make it (or a similar button) work in the edit mode but I don't have the time (and probably the skill) to do that. So at this time I consider this PR a bug fix and the functionality can be added at a later date in another pr

Testing requires overrides that need checking. You can simulate this by

1. Create template overrides for com_content/article and com_newsfeed/feed
2. Run this sql query replacing #_ with your db prefix INSERT INTO `#__template_overrides` (`id`, `template`, `hash_id`, `extension_id`, `state`, `action`, `client_id`, `created_date`, `modified_date`) VALUES (1, 'cassiopeia', 'L2h0bWwvY29tX25ld3NmZWVkcy9uZXdzZmVlZC9kZWZhdWx0LnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54'), (2, 'cassiopeia', 'L2h0bWwvY29tX2NvbnRlbnQvYXJ0aWNsZS9kZWZhdWx0X2xpbmtzLnBocA==', 223, 0, 'Joomla Update', 0, '2022-09-01 13:51:54', '2022-09-01 13:51:54');

You will now have two override files to update and can test this PR

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c3e246c1172cd3fc2d788fa9310dc543138c5b5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39337">issues.joomla.org/tracker/joomla-cms/39337</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on c3e246c1172cd3fc2d788fa9310dc543138c5b5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39337">issues.joomla.org/tracker/joomla-cms/39337</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39337">issues.joomla.org/tracker/joomla-cms/39337</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
