### PR TITLE
com_finder FIX not translated Groups in content map filter

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue reported here: https://github.com/joomla/joomla-cms/pull/39353#issuecomment-1336443922

### Summary of Changes
- Use branchSingular for select optgroup labels in admin filter Content Map.

### Testing Instructions
- Use another language than en-GB.
- After Patch applied, optgroup labels are translated in your language.

### Actual result BEFORE applying this Pull Request
Admin language used: de-DE

before

### Expected result AFTER applying this Pull Request
Admin language used: de-DE

after

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 56c663824aecb1379de20e4b8b15c48f4db40143<br /><br />Thanks, it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39359">issues.joomla.org/tracker/joomla-cms/39359</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 56c663824aecb1379de20e4b8b15c48f4db40143<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39359">issues.joomla.org/tracker/joomla-cms/39359</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39359">issues.joomla.org/tracker/joomla-cms/39359</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 56c663824aecb1379de20e4b8b15c48f4db40143<br /><br />After having set it to RTC, I have tested again to make sure it was no mistake.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39359">issues.joomla.org/tracker/joomla-cms/39359</a>.</sub>

**Comment by fancyFranci** [comment]
Thanks a lot!

**Pull request merged**
