### PR TITLE
Removing error surpressing @ in com_finder router

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #14301 .

### Summary of Changes
This just removes the error surpressing @-sign in the router of com_finder. This is a rather dodgy way to code this.... This should only be a codereview.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on ccc00b9a22bc0c1431da2440e5f8765728648eb6<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14323">issues.joomla.org/tracker/joomla-cms/14323</a>.</sub>

**Comment by Hackwar** [comment]
I have to apologise. I forgot the attribution. This is basically the code from @stAn47, so all praise belongs to him. 😉

**Review by mbabker — APPROVED** [review]

**Comment by PhilETaylor** [comment]
Who committed code with @ suppressors in the first instance? They should be shot!

**Comment by Hackwar** [comment]
That code is the initial commit of com_finder.

**Comment by PhilETaylor** [comment]
No comment

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ccc00b9a22bc0c1431da2440e5f8765728648eb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14323">issues.joomla.org/tracker/joomla-cms/14323</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14323">issues.joomla.org/tracker/joomla-cms/14323</a>.</sub>

**Pull request merged**
