### PR TITLE
[4.0] Improve newsfeed list performance on multilingual sites

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Replaces `JOIN` and `GROUP` clauses in query with a subquery for improved performance.

### Testing Instructions

Set up a multilingual site.
Enable language associations.
Create some newsfeeds with and without associations
View newsfeed list in backend.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Please replace "contact" by "newsfeed" in your description ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c83e29907a8fa4cea611c229bb06c3a5ed280b20<br /><br />Tested with MySQL 5.7 and PostgreSQL 10.10.

About performance I can't say anything because my test data set is too small.

But I can confirm everything works as well as before, carefully watching PHP error log with PHP error reporting set to maximum and watching database log. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26483">issues.joomla.org/tracker/joomla-cms/26483</a>.</sub>

**Comment by SharkyKZ** [comment]
@richard67 Changed. Thanks.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c83e29907a8fa4cea611c229bb06c3a5ed280b20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26483">issues.joomla.org/tracker/joomla-cms/26483</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26483">issues.joomla.org/tracker/joomla-cms/26483</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
