### PR TITLE
[4.2] Minor patch for the currentModal

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- The current code saves the open modal reference to `Joomla.current` instead of `Joomla.Modal.current`
- The current code works as the `Joomla.current` is not referenced by any other API, but it shouldn't be used for the modals

### Testing Instructions

- Create a new article and test adding an intro and a full image, selecting a user for the article and try using the XTD-buttons (insert Article, Menu, Module, Media).
- All modals open and close correctly

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
Please update also the incorrect comment  https://github.com/joomla/joomla-cms/blob/6cd61cb0c261e0a1611e1225c0d3ea7160f10d6c/build/media_source/system/js/core.es6.js#L114-L118
It should be used Joomla.Modal.getCurrent().

**Comment by dgrammatiko** [comment]
@Fedik done

**Review by Fedik — APPROVED** [review]

**Comment by carlitorweb** [comment]
Remember for the other tester use after apply the patch, `npm run build:js`

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 385efc0a709ab4bf5c0a5802e07e1aaca3d52dca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39450">issues.joomla.org/tracker/joomla-cms/39450</a>.</sub>

**Pull request merged**
