### PR TITLE
[4.0] Input bs5 for installation page

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Small change for the language installation page when installing Joomla (by analogy with https://github.com/joomla/joomla-cms/pull/34759). 

**Before / After**

Screenshot_1
Screenshot_2

Screenshot_3
Screenshot_4

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a30b6b8c58f68ec93801860b9f40b2ca0a4d1fa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36464">issues.joomla.org/tracker/joomla-cms/36464</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on a30b6b8c58f68ec93801860b9f40b2ca0a4d1fa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36464">issues.joomla.org/tracker/joomla-cms/36464</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36464">issues.joomla.org/tracker/joomla-cms/36464</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
