### PR TITLE
[4.1] empty state duplicated variables

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #36935 

$title and $content were defined twice. Can be merged on code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 43d4ed725a784bd4a176c631a6072d431db95f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36937">issues.joomla.org/tracker/joomla-cms/36937</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 43d4ed725a784bd4a176c631a6072d431db95f8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36937">issues.joomla.org/tracker/joomla-cms/36937</a>.</sub>

**Comment by Fedik** [comment]
R2C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36937">issues.joomla.org/tracker/joomla-cms/36937</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
