### PR TITLE
Stop spans from wrapping on smaller screens

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Stop spans from wrapping on smaller screens

### Testing Instructions
Apply patch. Navigate to article edit and resize the browser window...

**Before Patch**

grid1

**After Patch**

grid2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on cda9454f49e650ef95c0cd53a36c036a6febd592<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13751">issues.joomla.org/tracker/joomla-cms/13751</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on cda9454f49e650ef95c0cd53a36c036a6febd592<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13751">issues.joomla.org/tracker/joomla-cms/13751</a>.</sub>

**Comment by Bakual** [comment]
Please don't just test this with an article form as it will have an effect on every single fluid row. So almost every place in the CMS backend.

**Comment by ciar4n** [comment]
@laoneo @franz-wohlkoenig  Thank you for testing! 

I am going to close this as it is not the correct solution. I was assuming there was a compiling issue with the grid percentages which I no longer believe to be true.

**Pull request closed without merging**
