### PR TITLE
[4.0] Better UX for the switcher

### PR DESCRIPTION
**Pull request by rdeutz**
# Summary of Changes

Changes of CSS for better UX - make options always visible for a better understanding

# Testing Instructions

go to article edit and take look at the featured options

Original Author: @angieradtke

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not needed

https://github.com/joomla/joomla-cms/pull/27926#issuecomment-586359559

**Comment by Bakual** [comment]
Also here for reference: https://github.com/joomla/joomla-cms/pull/27952
We already have a working and tested solution for on/off toggles...

**Comment by brianteeman** [comment]
For me it makes it far too busy and its actually much easier to scan and read the settings when you only "see" the active one.

Plus you avoid the situation where you are forcing a tick on an item for no reason

buttons

Well there is a reason - its to avoid the problem of just using colour to give a meaning. Which is fine but are red/green colours a sensible option anyway. stop/go colours are just not always appropriate. 

button2

**Comment by Quy** [comment]
@wilsonge Close? See https://github.com/joomla/joomla-cms/pull/27952#issuecomment-587050273

**Comment by Quy** [comment]
@wilsonge please decide.

**Comment by wilsonge** [comment]
I think what this comes down to is us abusing the switcher position in some elements. I think what we have for yes/no options makes a lot of sense. But I do also see the argument that for the above/below cases it's probably not intuitive what the options are. So maybe the thing to do is to have two styling options

1. Keeping the existing style options. Basically used for boolean options (on/off, yes/no etc).
2. Something similar to switcher but without the boolean based colours/labels (used for when we have two options but radio buttons look 'unclean' in a modern interface - e.g. the above/below options brian mentioned)

I understand it's more coding options - but it's a decison that the developer needs to make - it's not something we're ever going to expose in the UI - so I don't think it's matters too much in this case.

Either way as is I don't think this PR works - it's improving a small number of buttons (e.g. above/below) but to me gives a worse UX on all our "boolean" buttons

**Comment by angieradtke** [comment]
> Well there is a reason - its to avoid the problem of just using colour to give a meaning. Which is fine but are red/green colours a sensible option anyway. stop/go colours are just not always appropriate.

You are right,  that is the reason why there is  a checked icon in front .-)

**Comment by chmst** [comment]
As we never know how long the options can be in different languages, the PR could cause an issue on small devices. 

I would like 
- Keep the switcher as is is a good and accessible solution for options yes/no. 
- For options which are not yes/no and not quite obvious (ie enabled / disabled), developers should use lists, so that users can see both options at the same time.

**Comment by wilsonge** [comment]
I think overall I'm happy with the design as is for the boolean options (which is the majority of switcher uses)

But we do need to do a review of the switcher uses and either move to dropdowns or a second varient of switcher where you can see both options.

**Pull request closed without merging**
