### PR TITLE
Adds option to combine the main jui jquery scripts

### PR DESCRIPTION
**Pull request by regularlabs**
This PR adds option in the main configuration to combine the main jui jquery scripts (jquery, noconflict, migrate).

This will reduce the number of scripts getting loaded on a page.

So instead of:
```
<script src="/media/jui/js/jquery.min.js" type="text/javascript"></script>
<script src="/media/jui/js/jquery-noconflict.js" type="text/javascript"></script>
<script src="/media/jui/js/jquery-migrate.min.js" type="text/javascript"></script>
```

You will get:
```
<script src="/media/jui/js/jquery.with-noconflict.with-migrate.min.js" type="text/javascript"></script>
```

Depending on whether the noconflict and migrate are required, these are also possible:
`jquery.min.js` (no extras required)
`jquery.with-noconflict.min.js` (only noconflict required)
`jquery.with-migrate.min.js` (only migrate required)

### Testing Instructions

Switch on the option in the global configuration and check the html output of the website (both frontend and administrator side).
You should see the new combined script being loaded instead of the separate ones.

### Documentation Changes Required

This adds an option to the Global Configuration.
And therefore also adds 2 language strings.

### CODE REVIEW

**Comment by brianteeman** [comment]
With http2 is it even a good idea to combine the scripts?

**Comment by CB9TOIIIA** [comment]
Most of the server is still on php 5... this PR is good I think ;)

**Comment by regularlabs** [comment]
Combining doesn't hurt http2.
But having `jQuery.noConflict();` in a separate file (like it is now) makes no sense at all.
With that http2 logic, it would be best to split every line of javascript into it's own file. Which of course is not what we want.

**Comment by dgt41** [comment]
As Brian said this is not a good practice anymore and also personally I tend to remove the migrate part as it is very slow.
So for it worth this is a 👎

**Comment by regularlabs** [comment]
Ok, closed

**Pull request closed without merging**
