### PR TITLE
[4.0] Adding error handling for installer

### PR DESCRIPTION
**Pull request by Hackwar**
When the ajax requests during installation are failing, we currently get no feedback about that in the UI. This PR adds some error handling for that. This is not perfect, but better than nothing and maybe someone can help make this better.

### Testinstructions
1. Modify /installation/src/Controller/InstallationController.php and add `echo 'something';` at line 74 (This breaks the response and triggers the error)
2. Go through the installation and fill everything, then click on `Install Joomla`
3. See the loadinglayer show quickly and then disappear again and at the top of the page you get an error message.

### CODE REVIEW

**Comment by nadjak77** [comment]
I have tested this item :white_check_mark: successfully on 725af5108c8af9f002a503f6c72f6a5b1867f2ab<br /><br />Appled patch
changed /installation/src/Controller/InstallationController.php
installed joomla
-> error message appear
work as descriped<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26073">issues.joomla.org/tracker/joomla-cms/26073</a>.</sub>

**Comment by rmittl** [comment]
Tested successfully ✅
Error message appears.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26073">issues.joomla.org/tracker/joomla-cms/26073</a>.</sub>

**Comment by wilsonge** [comment]
Kinda unconvinced by blatting out the raw code from an end user perspective. Can we not just give that message without appending the text and `console.error` the raw response which would be enough for us to see it in system tests

**Comment by wilsonge** [comment]
I've pushed a modified version of this with the changes I requested above

**Pull request closed without merging**
