### PR TITLE
Fix the default value.

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Fix the default value.

### Testing Instructions

- Enable the user- joomla plugin
- see that the pw fields are option when you try to create a new user.

### Expected result

pw fields are optional

### Actual result

pw fields are required

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
i cannot replicate your issue. passwords are optional for me and if they are not entered then a random password is used and in the email to the user

**Comment by zero-24** [comment]
please go to the database and clear the params field for the pld_user_joomla plugin. This is just in case the default value is not set ;)

**Comment by brianteeman** [comment]
ah i see what you mean now - but it will always be set as its in the sql.

**Comment by zero-24** [comment]
At least i could reproduce this on my site that is a bit older. after resaving the plugin it was working for sure ;) But also at other places we use 1 as default value.

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 952063d8a3bf9f92682b7bbac6ed716f030a3bde<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17307">issues.joomla.org/tracker/joomla-cms/17307</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 952063d8a3bf9f92682b7bbac6ed716f030a3bde<br /><br />With and -out PR the Fields "Password" and "Confirm Password" are marked wit an "*" and "Password" is filled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17307">issues.joomla.org/tracker/joomla-cms/17307</a>.</sub>

**Comment by zero-24** [comment]
Is the user joomla plugin enabled? And is the seccond setting (notify user) enabled? @franz-wohlkoenig

**Comment by ghost** [comment]
@zero-24 Plugin enabled, all 3 Fields are set on "Yes". Browsercache cleared.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
@franz-wohlkoenig hmm can you double check that you are going to create a new user and not edit an existing one?

**Comment by ghost** [comment]
@zero-24 create a new User at Frontend by click on "Create an account" at Login Form. All Fields below "User Registration" are "* Required fields".

**Comment by zero-24** [comment]
Ah this just works in the backend ;) Not in the frontend :smile:

**Comment by ghost** [comment]
At Backend with and -out PR the 2 Password-Fields are optional (User-Plug is resaved).

**Comment by zero-24** [comment]
> At Backend with and -out PR the 2 Password-Fields are optional (User-Plug is resaved).

Yes so the same applys as mention by brian you need to clear the params field for the plg_user_joomla plugin in the database than ;)

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 952063d8a3bf9f92682b7bbac6ed716f030a3bde<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17307">issues.joomla.org/tracker/joomla-cms/17307</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
