### PR TITLE
URLS Position Content global options

### PR DESCRIPTION
**Pull request by brianteeman**
This is a currently a list but as there are only two options it should be a radio btn-group

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e3fe8209e4e90e47b451642b7fe98fbefb7963a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17371">issues.joomla.org/tracker/joomla-cms/17371</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on e3fe8209e4e90e47b451642b7fe98fbefb7963a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17371">issues.joomla.org/tracker/joomla-cms/17371</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
