### PR TITLE
New xtd-editors menu and contact display buttons only if correct permissions

### PR DESCRIPTION
**Pull request by infograf768**
Patch similar to https://github.com/joomla/joomla-cms/pull/12353
Adds specific permissions to let display the new xtd-editors menu and contact buttons in the editor.

Note: It is known that these basic permissions should be improved. As they should be done for all xtd-editors, this should be for another PR, if we find a volunteer to do it.

### CODE REVIEW

**Comment by infograf768** [comment]
Testers: please also test https://github.com/joomla/joomla-cms/pull/12321 as that one is a release blocker.

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ab226f0aa200bf5c8ba58ba62ff590d451708063<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12746">issues.joomla.org/tracker/joomla-cms/12746</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@infograf768 is this for testing (#12353 #12321 are merged)?

**Comment by franz-wohlkoenig** [comment]
@infograf768 where to find specific Permissions? Looked in Plugins 

- "Button - Contact" and 
- "Button - Menu" 

after applied PR didn't find Permissions Settings.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by infograf768** [comment]
@franz-wohlkoenig 
I guess this is an oldie as these were introduced in subsequent PRs.
Closing

**Pull request closed without merging**
