### PR TITLE
[4.3] Migrate the extension namespacemap plugin to services

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Migrate the extension namespacemap plugin to service providers.

### Testing Instructions
Delete the file /administrator/cache/autoload_psr4.php and install an extension with a namespace like DPMedia Free.

### Actual result BEFORE applying this Pull Request
The file is created again with the namespace from DPMedia.

### Expected result AFTER applying this Pull Request
The file is created again with the namespace from DPMedia.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on e2e73ad44cd3065697e8f26ffee10cd557269b72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39008">issues.joomla.org/tracker/joomla-cms/39008</a>.</sub>

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on e2e73ad44cd3065697e8f26ffee10cd557269b72<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39008">issues.joomla.org/tracker/joomla-cms/39008</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39008">issues.joomla.org/tracker/joomla-cms/39008</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo for the PR!

**Pull request merged**
