### PR TITLE
[4.1] s/accordian/accordion

### PR DESCRIPTION
**Pull request by brianteeman**
typo and fixes pagebreak plugin

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0e51f3137e70fe98bae18bcee7ce9bee8a7a925<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36821">issues.joomla.org/tracker/joomla-cms/36821</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a0e51f3137e70fe98bae18bcee7ce9bee8a7a925<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36821">issues.joomla.org/tracker/joomla-cms/36821</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36821">issues.joomla.org/tracker/joomla-cms/36821</a>.</sub>

**Comment by bembelimen** [comment]
Thanks for the PR.

This has to be deprecated in 4.x - 0.1 before 5.0 to be changed in 5.0 to not break extensions using this (I know annoying..).

**Comment by brianteeman** [comment]
Why? The function is not changing just the default value for the $selector variable

**Comment by bembelimen** [comment]
Removed RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36821">issues.joomla.org/tracker/joomla-cms/36821</a>.</sub>

**Comment by bembelimen** [comment]
> Why? The function is not changing just the default value for the $selector variable

Yeah, but if someone is calling it without setting any value, it uses the default value, which is probably not compatible anymore with JS/other code the user applied to this selector.

**Comment by brianteeman** [comment]
thats a lot of what ifs

**Comment by brianteeman** [comment]
I was just tyring to help - its not worth the hassle.

**Pull request closed without merging**
