### PR TITLE
[installation] Update also modified by user id field (and also new fields table)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR (a continuation of https://github.com/joomla/joomla-cms/pull/11245) makes installation also update the `modified_by` user id field with the super user id in all tables of joomla + sample data.

### Testing Instructions

1. Apply patch
2. Delete configuration.php
3. Install Joomla "sample blog"
4. After install check there is no `JUser: :_load: Unable to load user with ID: 713` when editing content.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@infograf768 @brianteeman please test

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9ede6f0542aa6cd69748deaf27ce96c46dfc473b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12947">issues.joomla.org/tracker/joomla-cms/12947</a>.</sub>

**Comment by infograf768** [comment]
We have a new table that could be concerned in the future: `_fields_groups`
Shall we add it also here?

**Comment by Bakual** [comment]
Since there is no sample data (to my knowledge) for fields and groups, there isn't a need for this. It will just do nothing.

**Comment by shur** [comment]
I have tested this item :white_check_mark: successfully on 9ede6f0542aa6cd69748deaf27ce96c46dfc473b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12947">issues.joomla.org/tracker/joomla-cms/12947</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12947">issues.joomla.org/tracker/joomla-cms/12947</a>.</sub>

**Pull request merged**
