### PR TITLE
[4.4] Fix help icon not opening help screen

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #42818 .

### Summary of Changes
Help icon fails to open help screen when clicked on the question mark.

Thanks @dgrammatiko for the solution.

### Testing Instructions
Go to any screen which has a help screen, for example Content -> Articles.
Click on the text "Help" of the help toolbar button and you will see the appropriate help screen. However, if you click on the question mark to the left of the text you will get a much larger blank window with "about:blank" in the address bar.

Download the prebuilt package.
or 
Apply PR and run `npm run build:js`

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7a13d6607f05e36e5babb71c715b071b2b6525b1<br /><br />with NPM Prebuilt Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42820">issues.joomla.org/tracker/joomla-cms/42820</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7a13d6607f05e36e5babb71c715b071b2b6525b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42820">issues.joomla.org/tracker/joomla-cms/42820</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42820">issues.joomla.org/tracker/joomla-cms/42820</a>.</sub>

**Comment by C-Lodder** [comment]
No. Please don't use CSS to fix a JS problem!

You should be using `currentTarget`, rather than `target` instead:

https://github.com/joomla/joomla-cms/blob/4.4-dev/build/media_source/legacy/js/toolbar.es5.js#L46

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 92a1cf46f69e56774304a1721519039244dbd423<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42820">issues.joomla.org/tracker/joomla-cms/42820</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42820">issues.joomla.org/tracker/joomla-cms/42820</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
