### PR TITLE
[4.0] docblock update

### PR DESCRIPTION
**Pull request by brianteeman**
updates the note in the docblock to reflect that the change has taken place

code review

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 88ef4f327231a48c6d35db29bf0e2c86bc69ee44<br /><br />A simple tense change. Looks good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29373">issues.joomla.org/tracker/joomla-cms/29373</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 88ef4f327231a48c6d35db29bf0e2c86bc69ee44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29373">issues.joomla.org/tracker/joomla-cms/29373</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29373">issues.joomla.org/tracker/joomla-cms/29373</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
