### PR TITLE
[a11y] ordering icons

### PR DESCRIPTION
**Pull request by brianteeman**
When reading our default markup for rendering icons, assisistive technology may have the following problems.

The assistive technology will not find any content to read out to a user
The assistive technology will read the unicode equivalent, which does not match up to what the icon means in context, or worse is just plain confusing. In our use case it is always plain wrong. For example the unicode character used to display the trashed icon is \4c which is equal to L

When an icon is not an interactive element the simplest way to provide a text alternative is to use the aria-hidden="true" attribute on the icon and to include the text with an additional element, such as a < span>, with appropriate CSS to visually hide the element while keeping it accessible to assistive technologies.

In this case as the drag icon is completely inaccessible for non-sighted users (out of scope to resolve for this PR)  we just need to add the aria-hidden to prevent the icon being "read aloud"

This PR addresses the use case for the drag icons shown in the image below
screenshotr10-35-27

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Don't remove closing span tags. That's invalid HTML.

**Comment by brianteeman** [comment]
Good spot @SharkyKZ thats a replace error by me fixing it now

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on e64f17dd1d21436d858eae0eb0302a2ddd8c86bc<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14986">issues.joomla.org/tracker/joomla-cms/14986</a>.</sub>

**Comment by Quy** [comment]
In these files too:
\administrator\components\com_categories\views\categories\tmpl\default.php
\administrator\components\com_modules\views\modules\tmpl\default.php
\administrator\components\com_tags\views\tags\tmpl\default.php

**Comment by brianteeman** [comment]
@quy thats because they were changed in a different PR. Downside of making so many changes is that you have to break it up into smaller ones to prevent conflicts and make it easier to renew. Sometimes that will mean there will be some extra changes made after all the current PR have been merged. Once they are all merged i will do another pass through to catch any that might have been missed

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7fa2c3e45054f8cf6c37ec44b520e218a7fa4820<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14986">issues.joomla.org/tracker/joomla-cms/14986</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@C-Lodder can you please retest?

**Comment by brianteeman** [comment]
@franz-wohlkoenig there is no need for a retest. The test count was reset because I made a change to the PR but then I reverted that change so @C-Lodder test is still good

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
