### PR TITLE
Drop eval from compressed file

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
The file `overrider.min.js` is badly compressed and is using **eval()**. Don't use eval(). Never! 

The file is minified from the source (using https://jscompress.com), nothing fancy here, can go on review

### Documentation Changes Required
None, but there should be a rule that minified scripts should **not** use eval function

### CODE REVIEW

**Comment by brianteeman** [comment]
agree about not using eval

**Comment by brianteeman** [comment]
(note that json2.js used in com_joomlaupdate uses eval - it is intended to use eval - but as this file is only needed for ie8 support it can probably be dropped in j4)

**Comment by dgt41** [comment]
I did a PR and update it that to jason3 few hours ago 😃

**Comment by brianteeman** [comment]
Great minds think alike - didnt see that PR though?

**Comment by dgt41** [comment]
yup, https://github.com/joomla/joomla-cms/pull/14594

**Comment by brianteeman** [comment]
ah - thats because you once again have a pr doing multiple things. One PR per task. It makes it so much easier to test.

**Comment by dgt41** [comment]
In this particular case it makes sense to pack all the changes in one PR, as the tester will have to verify that the update still works (all the views files updated are engaged). So breaking it down to minor changes will mean multiple unneeded tests. This is an exemption to the rule, which I agree PRs need to be singular task oriented...

**Pull request merged**
