### PR TITLE
[4.0] see Issue #26321

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#26321

### CODE REVIEW

**Comment by sebenns** [comment]
I have tested this item :white_check_mark: successfully on 45136a57d914e78f7ade15e2b48f2530783bd630<br /><br />**before patching**
before

**after patching**
after<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26382">issues.joomla.org/tracker/joomla-cms/26382</a>.</sub>

**Comment by brianteeman** [comment]
Please update the title and description
Please complete the template when you submit a pull request

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 45136a57d914e78f7ade15e2b48f2530783bd630<br /><br />Confirm after Patch:
<span class="sr-only">Edit the 'System Submenu' module</span><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26382">issues.joomla.org/tracker/joomla-cms/26382</a>.</sub>

**Comment by N6REJ** [comment]
RTC

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26382">issues.joomla.org/tracker/joomla-cms/26382</a>.</sub>

**Comment by brianteeman** [comment]
Please update the title and description
Please complete the template when you submit a pull request

This is really important for the history of every issue

**Comment by wilsonge** [comment]
@N6REJ brian is right - filling out the pr description - even if you just copy/paste does help me when coming to merge things :)

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
