### PR TITLE
[4.0] Javascript tweaks

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

- Remove some unecessary code for IE
- Remove `html5.js` and `html5fallback.js`
- Update `draggable.js` to ES6

### CODE REVIEW

**Comment by Fedik** [comment]
looks good :)

**Comment by brianteeman** [comment]
why did you close this/

**Comment by C-Lodder** [comment]
No testers or activity.
Probably easier if split into chunks

**Comment by C-Lodder** [comment]
`js-tweaks-2` branch is still there if you want to fork it

**Comment by brianteeman** [comment]
thats no reason to close it. lots of pr take a long time to be tested or to get merged even after testing

**Pull request closed without merging**
