### PR TITLE
[4.0] blog.php Scrabble96 patch 4 scss

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#26160 
REQUIRES #26230 , #26242 
### Summary of Changes

Removed IE support per #26160 

### Testing Instructions
Create or view a category blog.
View Source
blog-item-content class should be gone.

### Expected result
image

### Actual result
image

### CODE REVIEW

**Comment by brianteeman** [comment]
Please complete the questions on the pull request template. Otherwise it's impossible for anyone to test as they won't know what the problem is that is being fixed and how this pr fixes it.

**Comment by N6REJ** [comment]
@brianteeman I'm not sure how to.  Since this is part of @Scrabble96's #26160 perhaps you can help?
AFAIK it just needs a visual check. 
Please advise.

**Comment by brianteeman** [comment]
On github go to the first post and click on the three dots and then you can edit the post
image

If you had not intended this to be a seperate PR then you should have submitted it to @scrabble96 branch for them to merge into their branch which would then become part of their PR.

**Comment by Scrabble96** [comment]
@N6REJ (cc @brianteeman) - if this is the changed (Update_modifier.scss) SCSS file, then I've already done that based on what you posted/suggested in #26160 a couple of days ago. It seems to have been successful.

**Comment by N6REJ** [comment]
yeah, thats what I meant to do but its closed.  Doesn't adding the issue # do that?

**Comment by brianteeman** [comment]
Simple answer is no

**Comment by N6REJ** [comment]
new pr #26263  containing all 3 since scrabble closed hers

**Pull request closed without merging**
