### PR TITLE
google authenticator plugin description

### PR DESCRIPTION
**Pull request by brianteeman**
this plugin is not just for google authenticator but for any TOTP authenticator.

This PR adds FreeOTP as an example alternative totp provider and also adds a slink to google authenticator (the link was already present just not visible on the plugin description page)

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e98bcf69c61a5c775e12b310ea3d6e6afbdf62d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12833">issues.joomla.org/tracker/joomla-cms/12833</a>.</sub>

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on e98bcf69c61a5c775e12b310ea3d6e6afbdf62d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12833">issues.joomla.org/tracker/joomla-cms/12833</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12833">issues.joomla.org/tracker/joomla-cms/12833</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
