### PR TITLE
Possibility for the frontend to have the 3 buttons (save, save & close, cancel)

### PR DESCRIPTION
**Pull request by belinifm**
Pull Request for Issue #17572 .

### Summary of Changes
Use the trio, Save, Save & Close, and Cancel in the frontend edition to increase publisher productivity.

### Expected result
As a result, the frontend publisher will have greater productivity in the work of creating and editing articles, preventing it from leaving the edit mode with each update of the content.

### Actual result
Currently, the publisher is forced to exit edit mode every time it saves content while editing through the portal frontend.This makes editing by the frontend too time-consuming, unproductive and annoying.

### CODE REVIEW

**Comment by zero-24** [comment]
@belinifm it looks like you have done a mistake as you just try to merge staging into 3.8-dev branch. Please double check that. So we can test your patch.

As this is not going to be merged this way I'm going to close this PR. Please let me know when you need help creating the pull request.

**Comment by belinifm** [comment]
How can I make an improvement request for the Joomla developers group?

What I'm asking for is very simple, I'm just trying to request that the new versions have the possibility to have the buttons (save, save & close, close) when editing articles by the frontend. Just to remember the backend already exists this possibility.

What is the best way for me to make this request?

**Comment by zero-24** [comment]
> What is the best way for me to make this request?

Do you have code that implement that change or do you just want to suggest that without submitting code?

**Comment by belinifm** [comment]
Suggest without sending code. Sorry for the stress.
Could you guide me?

**Comment by zero-24** [comment]
> Suggest without sending code. Sorry for the stress.

No problem just go here: https://github.com/joomla/joomla-cms/issues/new

And put all the input / request data in there in the most detail as possible. Thanks.

**Comment by gwsdesk** [comment]
Issue Tracker is the better place perhaps? https://issues.joomla.org/

**Comment by zero-24** [comment]
> Issue Tracker is the better place perhaps? https://issues.joomla.org/

Isn't the issue Tracker === Github ? So all that is in the issue tracker is also in Github ;)

**Comment by ghost** [comment]
@zero-24 most of the Time yes. But now there are new issues reported at Github which aren't shown in Tracker (#17581, #17582).

**Comment by zero-24** [comment]
> @zero-24 most of the Time yes. But now there are new issues reported at Github which aren't shown in Tracker (#17581, #17582).

Please report that to this tracker than: https://github.com/joomla/jissues/issues/new So michael can take a look into that. Thanks.

**Comment by gwsdesk** [comment]
@zero-24 of course I am aware that they (used to) sync but the Issue tracker has imho easier access for the average user compared to Github. It is easier for most to post on the Issue tracker since many do not even know where to find it on Github

**Comment by infograf768** [comment]
It just takes some time. Both Issues are now displaying on issues.joomla.org

**Comment by ghost** [comment]
thanks @zero-24 @infograf768 Issue reported an closed.

**Comment by mbabker** [comment]
Items posting on the issue tracker relies on either our cron jobs picking things up or GitHub's webhook delivery (the latter one is the preferred method as it is usually instantaneous).  If there are issues with GitHub's webhook system then things posting to the issue tracker will be delayed.  That is out of my hands.

**Comment by mbabker** [comment]
Looking at the GitHub log, there appears to have been a 20 minute delay earlier in one of the webhooks opening one of the noted issues.

screen shot 2017-08-17 at 7 09 11 am

**Pull request closed without merging**
