### PR TITLE
[4.0] Fix notice in newsfeed

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Fix a notice in newsfeed. 
components/com_newsfeeds/tmpl/newsfeed/default.php on line 24 
Notice: Trying to get property of non-object 

Thank you for the hint @ChristineWk, could you test this?

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aeeddfafe0d69c84a5fed1067161836f36dbdf6d<br /><br />Thank you also @chmst <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23436">issues.joomla.org/tracker/joomla-cms/23436</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on aeeddfafe0d69c84a5fed1067161836f36dbdf6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23436">issues.joomla.org/tracker/joomla-cms/23436</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23436">issues.joomla.org/tracker/joomla-cms/23436</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
