### PR TITLE
[4.0] codemirror update

### PR DESCRIPTION
**Pull request by brianteeman**
bumps codemirror version to 5.61.1

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 14dcf2d0193a3be0fb042f28ecc9946644ed7719<br /><br />I've run `npm update codemirror` on a clean current 4.0-dev branch. The changes in `package-lock.json` after that are the same as made with this PR. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34423">issues.joomla.org/tracker/joomla-cms/34423</a>.</sub>

**Comment by brianteeman** [comment]
did you also check the version number in the xml?

**Comment by richard67** [comment]
> did you also check the version number in the xml?

@brianteeman Sure, but that's just a normal code change and not a result of npm so I thought it's not worth to be mentioned.

**Comment by brianteeman** [comment]
it is not a manual code change. it is created by the build.js scripts when npm installs a new version of codemirror,tinymce (and others)

**Comment by richard67** [comment]
@brianteeman I see. Well, that works, too. I've just tested.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 14dcf2d0193a3be0fb042f28ecc9946644ed7719<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34423">issues.joomla.org/tracker/joomla-cms/34423</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34423">issues.joomla.org/tracker/joomla-cms/34423</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
