### PR TITLE
Change the listing of each language file to a folder tag

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #14200 .

### Summary of Changes
Replaces the list of `<filename>en.GB.foo.ini</filename>` with a single `<folder>/</folder>` tag.

### Testing Instructions
* Download an language pack of your choice and edit both install.xml files within it with this change.
* Install the pack, check that it worked (eg all files are copied as expected)
* Uninstall the pack and verify the files are removed

### Documentation Changes Required
Documentation for creating a language pack should be adjusted.
https://docs.joomla.org/J3.x:Making_a_Language_Pack_for_Joomla#an_install.xml

### CODE REVIEW

**Comment by Bakual** [comment]
Example German language pack:
[pkg_de-DE.zip](https://github.com/joomla/joomla-cms/files/799585/pkg_de-DE.zip)

A more complex language like Persian would have to be a bit more creative since it also has media files which shouldn't end up in the language folder. Have a look at the site folder to see how it's done:
[pkg_fa-IR.zip](https://github.com/joomla/joomla-cms/files/799586/pkg_fa-IR.zip)

**Comment by brianteeman** [comment]
Makes a lot of good sense to me

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f2f6f624fb8d6bc7cefbeb5f6d5d8aaf18e748a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14228">issues.joomla.org/tracker/joomla-cms/14228</a>.</sub>

**Comment by horus68** [comment]
Any reason why this is not merged yet?

**Comment by zero-24** [comment]
@horus68 you can use that in your language pack. As no core change is needed that this work.

**Comment by Bakual** [comment]
> Any reason why this is not merged yet?

@horus68 Mainly only one person which tested it. We usually want to have two people.

**Comment by zero-24** [comment]
Also i think for the core supplyed version we can still use the current way this makes it clear which files has been added using the history 😄

**Comment by horus68** [comment]
@zero-24 I don't see the point to have such list. There is no other place in the Project with a list of added files for any other part of the code, just for languages. If redundant, remove.
The main reason to remove its the way Crowdin works: every time a file is added all the XML translations are messed up, and we need to delete previous and translate again (every file needs to have our language code) and it take me 5 to 15 minutes each time there is a change in XML from Git.
- If I do not translate all XML files (if my translations is not 100% ) I'm not able to download it from Crwodin.
- So there is no use on creating a local version of the XML. 
Actually I create my language zip pack directly from Crowdin, no other edits are required.
All I want is to work the minimum required to have a great translation.

**Comment by zero-24** [comment]
Than @Bakual needs to fix the conflicts and you need to test this PR 😄

**Comment by Bakual** [comment]
Rebased the PR and fixed the conflicts.

**Comment by horus68** [comment]
@zero-24 tested: installed and uninstalled ok. All working, all files installed, no files or folder left behind after uninstall.
Joomla 3.7.rc3 / Firefox latest on Windows 10 / Wampserver apache 2.4.18
PHP 5.6.18 and 7.0.11 / MYSQL 5.6.17

**Comment by franz-wohlkoenig** [comment]
@horus68 can i set this as succesfully Test?

**Comment by horus68** [comment]
@franz-wohlkoenig yes indeed!

**Comment by franz-wohlkoenig** [comment]
@horus68 thanks, done in Tracker.

**Comment by rbuelund** [comment]
I have tested this item :white_check_mark: successfully on 413021252daf0aca5bf4c0ec3038a8528a5abbf7<br /><br />Works perfectly on J3.7 RC-3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14228">issues.joomla.org/tracker/joomla-cms/14228</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
I am still concerned about this change:
We may get extraneous files installed in the language folders if a TT is negligent (simple example are .bak files, not a big deal, but can be worse). 
Please do not reply that a TT should not be negligent...
For Persian and Dari using specific calendars,  I guess it would not be a problem if their specific js is also present in the language xx-XX folder.

**Comment by dgt41** [comment]
> For Persian and Dari using specific calendars, I guess it would not be a problem if their specific js is also present in the language xx-XX folder.

That shouldn't be the case with the new calendar, all files are already shipped by Joomla at media/system/js/fields/calendar-lacales

**Comment by infograf768** [comment]
> That shouldn't be the case with the new calendar, all files are already shipped by Joomla at media/system/js/fields/calendar-lacales

Nope. They still need their own js for the dates displayed in the columns and wherever dates are displayed (Created,etc.) as the new calendar only concerns the date fields.

**Comment by stellainformatica** [comment]
`I am still concerned about this change:
We may get extraneous files installed in the language folders if a TT is negligent (simple example are .bak files, not a big deal, but can be worse).`
I agree with JM

**Comment by mbabker** [comment]
> We may get extraneous files installed in the language folders

By that logic we should deprecate the `<folder>` tag for all extension adapters because this is an issue for all extension types and the only person able to do something about it is whomever is creating the package.  So yes, it does mean that the packager has an additional responsibility to get things right.

**Comment by Bakual** [comment]
> For Persian and Dari using specific calendars, I guess it would not be a problem if their specific js is also present in the language xx-XX folder.

They could use a slightly different package structure and XML file to prevent that.
Or of course still create the list of files as it is currently (com_localise does that automatically), that will always work.

**Comment by syntaxerror** [comment]
Tested successfully on Joomla 3.7, all files installed and uninstalled correctly.

> We may get extraneous files installed in the language folders

As stated by others this is not any valid reason for not doing it. If translators is unable to make a language pack themselves, they should really start using tools who can automate this for them, or else someone has to do it for them. It's a bigger concern to me that people are still struggling with getting the darn install.xml right, no mater how they make their packs. It's just a pain in the ...

**Pull request merged**
