### PR TITLE
Routing: No-Itemid-behavior for components

### PR DESCRIPTION
**Pull request by Hackwar**
This PR implements a rule for URLs with missing Itemid as a generic rule for all component routers that extend from JComponentRouterView.
### How to test
- Apply this change
- Change the router of com_content by replacing

``` php
class ContentRouter extends JComponentRouterBase
{
```

with

``` php
class ContentRouter extends JComponentRouterView
{
    function __construct($app = null, $menu = null) {

        $categories = new JComponentRouterViewconfiguration('categories');
        $categories->setKey('id');
        $this->registerView($categories);
        $category = new JComponentRouterViewconfiguration('category');
        $category->setKey('id')->setParent($categories, 'id')->setNestable()->addLayout('blog');
        $this->registerView($category);
        $article = new JComponentRouterViewconfiguration('article');
        $article->setKey('id')->setParent($category, 'catid');
        $this->registerView($article);
        $this->registerView(new JComponentRouterViewconfiguration('archive'));
        $this->registerView(new JComponentRouterViewconfiguration('featured'));
    $this->registerView(new JComponentRouterViewconfiguration('form'));

        parent::__construct($app, $menu);
        $this->attachRule(new JComponentRouterRulesMenu($this));
        $this->attachRule(new JComponentRouterRulesNomenu($this));
    }

    public function getCategorySegment($id, $query)
    {
        $category = JCategories::getInstance($this->getName())->get($id);
        if ($category)
        {
            return array_reverse($category->getPath());
        }

        return array();
    }

    public function getCategoriesSegment($id, $query)
    {
        return $this->getCategorySegment($id, $query);
    }

    public function getArticleSegment($id, $query)
    {
        return array($id);
    }
```
- Comment line 62 and 111 from /components/com_content/helpers/route.php to disable the lookup of the Itemid there.
- See that the right menu items are still found for the items
- See that URLs without an Itemid are created properly and return a page that does not throw an error code. Please notice that this currently will display all other URLs of com_content still as mostly non-SEF. That behavior will come in another rule.

This was updated on May 22nd 2015. All discussions prior to that point have either been integrated or are obsolete.

This was made possible through the generous donation of the people mentioned in the following link via an Indiegogo campaign: http://joomlager.de/crowdfunding/5-contributors

### CODE REVIEW

**Comment by Hackwar** [comment]
I've updated this PR to work with the changed JComponentRouterView class. Please test.

**Comment by Duke3D** [comment]
Is this still active?  If so, I suggest a companion PR with patch for the listed code changes needed to implement the test conditions.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5599">issues.joomla.org/joomla-cms/5599</a>.</sub>

**Comment by Hackwar** [comment]
@Duke3D What do you mean with companion PR and what not? And this is still active, yes.

**Comment by Hackwar** [comment]
Please be aware that all comments above mine from May 23rd have either been incorporated into this or do not apply here. Those come from several cross merges.

**Comment by Hackwar** [comment]
I've combined the changes from this and all other routing related PRs into a new PR: #7615 Please review and comment in the new PR. I'm closing this one, so that we can focuse on the new PR.

**Pull request closed without merging**
