### PR TITLE
Remove administrator deprecated JVersion calls

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR removes the usage of deprecated JVersion methods inside admin mod_version (the one that puts the joomla version in the bottom right corner of the admin panel) and from install languages.
The old usage was deprecated in https://github.com/joomla/joomla-cms/pull/7217

https://github.com/joomla/joomla-cms/pull/8935, https://github.com/joomla/joomla-cms/pull/8925 and https://github.com/joomla/joomla-cms/pull/8932 removes most of deprecated log messages in Joomla core.
#### How to test.
- Install patch.
- Check if in the bottom right corner of your joomla admin panel if version is ok
- Go to modules, select "Administrator" modules and edit the "Joomla Version".
- Test the 3 options and check if they are all ok.
- Check also if in the debug console there is no deprecated message

Part 2:
- Go to install languages
- Check there are no JVersion deprecated messages and everything works fine

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dcdd24adf9d75788a1425d93e6bff504ae18a846<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8932">issues.joomla.org/joomla-cms/8932</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on dcdd24adf9d75788a1425d93e6bff504ae18a846<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8932">issues.joomla.org/joomla-cms/8932</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8932">issues.joomla.org/joomla-cms/8932</a>.</sub>

**Comment by infograf768** [comment]
This has broken mod_version
( ! ) Fatal error: Can't use method return value in write context in ROOT/administrator/modules/mod_version/helper.php on line 36

**Comment by infograf768** [comment]
See https://issues.joomla.org/tracker/joomla-cms/9002

**Comment by infograf768** [comment]
Please test 
https://github.com/joomla/joomla-cms/pull/9003

**Pull request closed without merging**
