### PR TITLE
Fix #15044

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #15044 

### Summary of Changes
Fix textarea box misalignment.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
isn't this resolved by #15044 or what textarea box is to test?

**Comment by Quy** [comment]
Sort of. I moved the `<p>` to the wrong location which affected the textarea box area. This PR moves it back to the location I had initially to fix this issue.

**Comment by franz-wohlkoenig** [comment]
this is a code review, nothing to test.

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on c5ad8a45a21f7b5702a205775a03e432d056dbf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15076">issues.joomla.org/tracker/joomla-cms/15076</a>.</sub>

**Comment by RonakParmar** [comment]
Joomla! 3.7.0-rc1
screen shot 2017-04-05 at 04 31 33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15076">issues.joomla.org/tracker/joomla-cms/15076</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c5ad8a45a21f7b5702a205775a03e432d056dbf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15076">issues.joomla.org/tracker/joomla-cms/15076</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
