### PR TITLE
[5.1] Private messages relative urls

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #43270 .

### Summary of Changes

- apply the MailHelper code for relative urls

### Testing Instructions

Follow the issue

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7e7269bc2f6b83494b4e0192e1e8a419bb8af07a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43897">issues.joomla.org/tracker/joomla-cms/43897</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7e7269bc2f6b83494b4e0192e1e8a419bb8af07a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43897">issues.joomla.org/tracker/joomla-cms/43897</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43897">issues.joomla.org/tracker/joomla-cms/43897</a>.</sub>

**Comment by bembelimen** [comment]
@dgrammatiko could you please update the branch, so I can merge? Thanks

**Comment by dgrammatiko** [comment]
Done, weird you should be able to do that yourself or did I messed up something?

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
