### PR TITLE
[com_tags] Tagged item link in feed

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This corrects the links to items in Tagged Items feed.

### Testing Instructions

Create some tags and apply them to some items.
Open Tagged Items feed. Check the item links.

### Expected result

SEF links like this: `https://community.joomla.org/blogs/community/the-marketing-working-group-mwg-welcomes-new-members.html`.

### Actual result

Links like this: `https://community.joomla.org/?view=article&amp;id=1898:the-marketing-working-group-mwg-welcomes-new-members`.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by ghost** [comment]
@EmilMassey @alschaeffer please test this Pull Request, thanks.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e73d35ab9a206940b32fc6727bf57d1d3c770853<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20723">issues.joomla.org/tracker/joomla-cms/20723</a>.</sub>

**Comment by carlitorweb** [comment]
Sorry for this, but I can't find the "Tagged Items feed". Maybe I just no understand well what view is. Is not the tagged items list, because there work well all.

**Comment by Quy** [comment]
On the back end, edit `Quick Icons` article and apply tags.
On the front end, click `Tagged items`. 
In the left column, click `Feed Entries`.

**Comment by carlitorweb** [comment]
Thank you @Quy . Now i got it

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on e73d35ab9a206940b32fc6727bf57d1d3c770853<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20723">issues.joomla.org/tracker/joomla-cms/20723</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20723">issues.joomla.org/tracker/joomla-cms/20723</a>.</sub>

**Pull request merged**
