### PR TITLE
[4.0] Admin modules

### PR DESCRIPTION
**Pull request by brianteeman**
As Phil discovered #33520 several of the admin modules really dont work well in a position other than the position they were designed for. It doesn't make sense to write code to resolve this if it is even possible. The mod_version description said ` and is intended to be displayed in the 'status' position.` So I just added that to the description of the other modules that this applies to.

### CODE REVIEW

**Comment by richard67** [comment]
Does it solve issue #33520 ?

**Comment by richard67** [comment]
> Does it solve issue #33520 ?

Ah, I see you asked this already in the issue.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 748c15d7c17e5f63b53b5fdb04517e72dfff1383<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34064">issues.joomla.org/tracker/joomla-cms/34064</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 748c15d7c17e5f63b53b5fdb04517e72dfff1383<br /><br />I would say that the PR "solves" enough to get away with closing this issue, but I dont like the fact that we have a module that cannot be reused and is highly specific to a certain place at a certain time.

For example, I might want to display the Joomla version somewhere else, in the footer, on my site, or anywhere
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34064">issues.joomla.org/tracker/joomla-cms/34064</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34064">issues.joomla.org/tracker/joomla-cms/34064</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
