### PR TITLE
issue #8891 fixed typo s/$cachable/$cacheable

### PR DESCRIPTION
**Pull request by N6REJ**
renamed all $cachable to $cacheable

### CODE REVIEW

**Comment by brianteeman** [comment]
please update your PR only for core files

On 13 January 2016 at 15:31, Bear <notifications@github.com> wrote:

> renamed all $cachable to $cacheable
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/8896
> Commit Summary
>
>    - issue #8891 fixed typo s/$cachable/$cacheable
>
> File Changes
>
>    - *M* administrator/components/com_banners/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-0> (4)
>    - *M* administrator/components/com_banners/controllers/tracks.raw.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-1> (4)
>    - *M* administrator/components/com_cache/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-2> (4)
>    - *M* administrator/components/com_categories/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-3> (4)
>    - *M* administrator/components/com_checkin/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-4> (4)
>    - *M* administrator/components/com_config/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-5> (4)
>    - *M* administrator/components/com_contact/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-6> (4)
>    - *M* administrator/components/com_content/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-7> (4)
>    - *M* administrator/components/com_finder/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-8> (4)
>    - *M* administrator/components/com_installer/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-9> (4)
>    - *M* administrator/components/com_joomlaupdate/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-10> (4)
>    - *M* administrator/components/com_joomlaupdate/controllers/update.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-11> (4)
>    - *M* administrator/components/com_languages/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-12> (4)
>    - *M* administrator/components/com_login/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-13> (4)
>    - *M* administrator/components/com_media/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-14> (4)
>    - *M* administrator/components/com_menus/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-15> (4)
>    - *M* administrator/components/com_menus/controllers/menu.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-16> (4)
>    - *M* administrator/components/com_menus/controllers/menus.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-17> (4)
>    - *M* administrator/components/com_messages/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-18> (4)
>    - *M* administrator/components/com_modules/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-19> (4)
>    - *M* administrator/components/com_newsfeeds/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-20> (4)
>    - *M* administrator/components/com_plugins/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-21> (4)
>    - *M* administrator/components/com_redirect/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-22> (4)
>    - *M* administrator/components/com_search/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-23> (4)
>    - *M* administrator/components/com_tags/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-24> (4)
>    - *M* administrator/components/com_templates/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-25> (4)
>    - *M* administrator/components/com_users/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-26> (4)
>    - *M* components/com_contact/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-27> (8)
>    - *M* components/com_content/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-28> (10)
>    - *M* components/com_finder/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-29> (10)
>    - *M* components/com_finder/controllers/suggestions.json.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-30> (4)
>    - *M* components/com_newsfeeds/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-31> (10)
>    - *M* components/com_search/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-32> (6)
>    - *M* components/com_tags/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-33> (8)
>    - *M* components/com_users/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-34> (4)
>    - *M* components/com_wrapper/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-35> (8)
>    - *M* libraries/fof/controller/controller.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-36> (6)
>    - *M* libraries/legacy/controller/admin.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-37> (4)
>    - *M* libraries/legacy/controller/legacy.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-38> (6)
>    - *M* libraries/legacy/response/response.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-39> (2)
>    - *A* nbproject/project.properties
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-40> (7)
>    - *A* nbproject/project.xml
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-41> (9)
>    - *A* robots.txt
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-42> (29)
>    - *A* templates/masterbootswatch/component.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-43> (29)
>    - *A* templates/masterbootswatch/css/bootstrap-theme.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-44> (476)
>    - *A* templates/masterbootswatch/css/bootstrap-theme.css.map
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-45> (1)
>    - *A* templates/masterbootswatch/css/bootstrap-theme.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-46> (5)
>    - *A* templates/masterbootswatch/css/bootstrap.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-47> (6584)
>    - *A* templates/masterbootswatch/css/bootstrap.css.map
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-48> (1)
>    - *A* templates/masterbootswatch/css/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-49> (5)
>    - *A* templates/masterbootswatch/css/bootswatch.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-50> (1)
>    - *A* templates/masterbootswatch/css/cerulean/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-51> (7)
>    - *A* templates/masterbootswatch/css/cosmo/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-52> (7)
>    - *A* templates/masterbootswatch/css/cyborg/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-53> (7)
>    - *A* templates/masterbootswatch/css/darkly/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-54> (7)
>    - *A* templates/masterbootswatch/css/flatly/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-55> (7)
>    - *A* templates/masterbootswatch/css/font-awesome.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-56> (1338)
>    - *A* templates/masterbootswatch/css/font-awesome.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-57> (4)
>    - *A* templates/masterbootswatch/css/fonts/FontAwesome.otf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-58> (0)
>    - *A* templates/masterbootswatch/css/fonts/fontawesome-webfont.eot
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-59> (0)
>    - *A* templates/masterbootswatch/css/fonts/fontawesome-webfont.svg
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-60> (414)
>    - *A* templates/masterbootswatch/css/fonts/fontawesome-webfont.ttf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-61> (0)
>    - *A* templates/masterbootswatch/css/fonts/fontawesome-webfont.woff
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-62> (0)
>    - *A*
>    templates/masterbootswatch/css/fonts/glyphicons-halflings-regular.eot
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-63> (0)
>    - *A*
>    templates/masterbootswatch/css/fonts/glyphicons-halflings-regular.svg
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-64> (229)
>    - *A*
>    templates/masterbootswatch/css/fonts/glyphicons-halflings-regular.ttf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-65> (0)
>    - *A*
>    templates/masterbootswatch/css/fonts/glyphicons-halflings-regular.woff
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-66> (0)
>    - *A* templates/masterbootswatch/css/icons.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-67> (440)
>    - *A* templates/masterbootswatch/css/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-68> (1)
>    - *A* templates/masterbootswatch/css/journal/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-69> (7)
>    - *A* templates/masterbootswatch/css/lumen/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-70> (7)
>    - *A* templates/masterbootswatch/css/paper/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-71> (7)
>    - *A* templates/masterbootswatch/css/readable/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-72> (7)
>    - *A* templates/masterbootswatch/css/sandstone/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-73> (7)
>    - *A* templates/masterbootswatch/css/simplex/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-74> (7)
>    - *A* templates/masterbootswatch/css/slate/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-75> (7)
>    - *A* templates/masterbootswatch/css/spacelab/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-76> (7)
>    - *A* templates/masterbootswatch/css/superhero/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-77> (7)
>    - *A* templates/masterbootswatch/css/template.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-78> (309)
>    - *A* templates/masterbootswatch/css/united/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-79> (7)
>    - *A* templates/masterbootswatch/css/yeti/bootstrap.min.css
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-80> (7)
>    - *A* templates/masterbootswatch/error.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-81> (49)
>    - *A* templates/masterbootswatch/favicon.ico
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-82> (0)
>    - *A* templates/masterbootswatch/fonts/FontAwesome.otf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-83> (0)
>    - *A* templates/masterbootswatch/fonts/fontawesome-webfont.eot
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-84> (0)
>    - *A* templates/masterbootswatch/fonts/fontawesome-webfont.svg
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-85> (414)
>    - *A* templates/masterbootswatch/fonts/fontawesome-webfont.ttf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-86> (0)
>    - *A* templates/masterbootswatch/fonts/fontawesome-webfont.woff
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-87> (0)
>    - *A* templates/masterbootswatch/fonts/glyphicons-halflings-regular.eot
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-88> (0)
>    - *A* templates/masterbootswatch/fonts/glyphicons-halflings-regular.svg
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-89> (229)
>    - *A* templates/masterbootswatch/fonts/glyphicons-halflings-regular.ttf
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-90> (0)
>    - *A*
>    templates/masterbootswatch/fonts/glyphicons-halflings-regular.woff
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-91> (0)
>    - *A* templates/masterbootswatch/html/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-92> (1)
>    - *A* templates/masterbootswatch/html/mod_breadcrumbs/default.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-93> (57)
>    - *A* templates/masterbootswatch/html/mod_breadcrumbs/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-94> (1)
>    - *A* templates/masterbootswatch/html/mod_login/default.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-95> (68)
>    - *A* templates/masterbootswatch/html/mod_login/default_logout.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-96> (32)
>    - *A* templates/masterbootswatch/html/modules.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-97> (59)
>    - *A* templates/masterbootswatch/html/pagination.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-98> (213)
>    - *A* templates/masterbootswatch/images/bg.jpg
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-99> (0)
>    - *A* templates/masterbootswatch/images/glyphicons-halflings-white.png
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-100> (0)
>    - *A* templates/masterbootswatch/images/glyphicons-halflings.png
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-101> (0)
>    - *A* templates/masterbootswatch/images/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-102> (1)
>    - *A* templates/masterbootswatch/includes/head.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-103> (26)
>    - *A* templates/masterbootswatch/includes/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-104> (1)
>    - *A* templates/masterbootswatch/includes/params.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-105> (63)
>    - *A* templates/masterbootswatch/index.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-106> (200)
>    - *A* templates/masterbootswatch/js/PIE.htc
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-107> (96)
>    - *A* templates/masterbootswatch/js/bootstrap.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-108> (2317)
>    - *A* templates/masterbootswatch/js/bootstrap.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-109> (7)
>    - *A* templates/masterbootswatch/js/bootswatch.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-110> (52)
>    - *A* templates/masterbootswatch/js/dropdown.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-111> (154)
>    - *A* templates/masterbootswatch/js/holder.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-112> (12)
>    - *A* templates/masterbootswatch/js/index.html
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-113> (1)
>    - *A* templates/masterbootswatch/js/jquery-2.1.3.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-114> (4)
>    - *A* templates/masterbootswatch/js/jquery-migrate.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-115> (2)
>    - *A* templates/masterbootswatch/js/jquery-noconflict.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-116> (1)
>    - *A* templates/masterbootswatch/js/jui/bootstrap.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-117> (2317)
>    - *A* templates/masterbootswatch/js/jui/bootstrap.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-118> (7)
>    - *A* templates/masterbootswatch/js/jui/jquery-migrate.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-119> (2)
>    - *A* templates/masterbootswatch/js/jui/jquery-noconflict.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-120> (1)
>    - *A* templates/masterbootswatch/js/jui/jquery.min.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-121> (4)
>    - *A* templates/masterbootswatch/js/modal.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-122> (324)
>    - *A* templates/masterbootswatch/js/modernizr-2.8.3.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-123> (4)
>    - *A* templates/masterbootswatch/js/popover.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-124> (113)
>    - *A* templates/masterbootswatch/js/template.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-125> (48)
>    - *A* templates/masterbootswatch/js/tooltip.js
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-126> (472)
>    - *A* templates/masterbootswatch/offline.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-127> (67)
>    - *A* templates/masterbootswatch/templateDetails.xml
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-128> (122)
>    - *M* tests/unit/core/mock/application/web.php
>    <https://github.com/joomla/joomla-cms/pull/8896/files#diff-129> (8)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/8896.patch
>    - https://github.com/joomla/joomla-cms/pull/8896.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8896>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by N6REJ** [comment]
huh?

**Comment by wojsmol** [comment]
@N6REJ  see https://github.com/joomla/joomla-cms/pull/8896/files

**Comment by N6REJ** [comment]
whoops, closing to redo

**Pull request closed without merging**
