### PR TITLE
[4.0] Complete list item clickable (Sytem & Help)

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
In the Help and System pages, this PR makes the entire list item clickable rather than just the text.

### Testing Instructions
Apply PR navigate to Help or System. Full items should be clickable rather than just the text.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 74afed29db57a7ec17bba91cfd7242e869f99524<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21659">issues.joomla.org/tracker/joomla-cms/21659</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 74afed29db57a7ec17bba91cfd7242e869f99524<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21659">issues.joomla.org/tracker/joomla-cms/21659</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by C-Lodder** [comment]
`<a class="list-group-item list-group-item-action">`?

**Comment by ciar4n** [comment]
> a class="list-group-item list-group-item-action"

And remove the `li`?

**Comment by C-Lodder** [comment]
And the `<ul>` too. Just use a div

**Comment by ciar4n** [comment]
Amended inline with Charlie's suggestion

**Comment by brianteeman** [comment]
Sorry but the changes requested by @C-Lodder are wrong. These are lists and should be marked up as lists.  Particularly important for a11y.

**Comment by ciar4n** [comment]
Previous commit reverted. Now back to lists.

**Pull request merged**
