### PR TITLE
[4.0] [com_postinstall] Parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Adds parameterized queries to `com_postinstall`.

### Testing Instructions

Check that `com_postinstall` continues to work.
Try to hide a message, hide all messages, reset messages.
If you have some extensions installed, filter by extension.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 04486b8ec7599d1406165f03bcb0546bc712eb66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29145">issues.joomla.org/tracker/joomla-cms/29145</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 04486b8ec7599d1406165f03bcb0546bc712eb66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29145">issues.joomla.org/tracker/joomla-cms/29145</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29145">issues.joomla.org/tracker/joomla-cms/29145</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
@wilsonge Merging this has brokeen PHPCS test in drone for the 4.0-dev branch.

**Comment by SharkyKZ** [comment]
Oops, I didn't notice that.

**Comment by SharkyKZ** [comment]
See PR #29163.

**Pull request merged**
