### PR TITLE
[4.0] LTR RTL Direction com_newsfeeds

### PR DESCRIPTION
**Pull request by brianteeman**
Removes unnecessary word

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 45a1d8c674f2f593ed0a7f3305e4d447bdf98eb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26023">issues.joomla.org/tracker/joomla-cms/26023</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 45a1d8c674f2f593ed0a7f3305e4d447bdf98eb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26023">issues.joomla.org/tracker/joomla-cms/26023</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26023">issues.joomla.org/tracker/joomla-cms/26023</a>.</sub>

**Comment by HLeithner** [comment]
More holiday for j4, hope you have fun too.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
