### PR TITLE
[4.0] [plg_installer_override] Query error

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes query error by running single `INSERT` statement.

### Testing Instructions

Download and install this component:  [com_helloworld.0.0.1.zip](https://github.com/joomla/joomla-cms/files/3689261/com_helloworld.0.0.1.zip)
Create at least 2 layout overrides of its views.
Update the component: [com_helloworld.0.0.2.zip](https://github.com/joomla/joomla-cms/files/3689264/com_helloworld.0.0.2.zip)
Inspect Template Override quick icon.

### Expected result

No errors during update and quick icon shows 2 (or more) overrides.

### Actual result

Error occurs during update:
>An error has occurred.
```
Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:432
2 | Joomla\Database\Mysqli\MysqliStatement->execute() | JROOT\libraries\vendor\joomla\database\src\DatabaseDriver.php:673
3 | Joomla\Database\DatabaseDriver->execute() | JROOT\plugins\installer\override\override.php:407
4 | PlgInstallerOverride->saveOverrides() | JROOT\plugins\installer\override\override.php:191
5 | PlgInstallerOverride->finalize() | JROOT\plugins\installer\override\override.php:273
6 | PlgInstallerOverride->onInstallerAfterInstaller() | JROOT\libraries\src\Plugin\CMSPlugin.php:285
7 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:495
8 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:111
9 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\administrator\components\com_installer\Model\InstallModel.php:217
10 | Joomla\Component\Installer\Administrator\Model\InstallModel->install() | JROOT\administrator\components\com_installer\Controller\InstallController.php:42
11 | Joomla\Component\Installer\Administrator\Controller\InstallController->install() | JROOT\libraries\src\MVC\Controller\BaseController.php:728
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
13 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:383
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:117
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:160
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:241
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
18 | require_once() | JROOT\administrator\index.php:36
```

Quick icon shows 1 override.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Thanks for catching that. It seems this PR is also needed for testing my PR #26462 .

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4171e1c29eba2ed015a71e6e3a1e8a2e29eaa650<br /><br />Thanks for clear testing instructions and downloads of helloworld packages, and of course thanks for the fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26464">issues.joomla.org/tracker/joomla-cms/26464</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4171e1c29eba2ed015a71e6e3a1e8a2e29eaa650<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26464">issues.joomla.org/tracker/joomla-cms/26464</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26464">issues.joomla.org/tracker/joomla-cms/26464</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
