### PR TITLE
[BUG 3.5.0 beta] Fix scrolling inside bootstrap modals (small height of window viewport)

### PR DESCRIPTION
**Pull request by cyrez**
Fix scrolling inside bootstrap modals (small height of window viewport: mobile, window resized...).
Corrects the media modal padding on small devices.
Patch for Isis and Protostar templates.
#### Steps to reproduce the issue

**Isis template**
In admin test new bootstrap modals introduced in 3.5.0 beta2 : 
- Add New Menu Item : **Menu Item Type** (component views) or **Link Image** (image) option
- Add New Article : **Created By** (users), **Intro Image** (image)
- In list of items : test **Batch** modals
- Everywhere a bootstrap modal is used...

**Protostar template**
In frontend : 
- Edit Article : **Versions**, **Intro Image** (image) ...
- Everywhere a bootstrap modal is used...
#### Expected result

We should be able to scroll inside the modal, and use all options when using administration on a mobile or small screen device.
#### Actual result in 3.5.0 beta2

You may not be able to scroll the modal on iOS (iPhone) (tests on other mobile OS are welcome!)
On window resized (small height), modal could be off screen (bottom content not accessible)

BEFORE PATCH on iPhone 4S iOS 9.2.1
iphone4s-before-patch
_Modal off screen. Not possible to scroll._
#### Additional comments

Scrolling not working on mobile is a known issue of Bootstrap modals, not fixed in BS 2 and 3 : https://github.com/twbs/bootstrap/issues/14839 (and maybe related to a webkit bug: https://bugs.webkit.org/show_bug.cgi?id=153856)
To set a max-height for modal-body class depending on the current viewport height solves the issue of not being able to view bottom of the modal window. (resize your window to arround 300px height before and after patch)
#### Testing

Apply the patch, and you may be able to scroll inside all bootstrap modals.

AFTER PATCH on iPhone 4S iOS 9.2.1
iphone4s-after-patch
_Modal adapts to screen. Scroll is working._

Note: Review of the comments by a native English speaker will be appreciated ;-)

### CODE REVIEW

**Comment by dgt41** [comment]
works for me! Thanks @JoomliC

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 91f2c716d87096427ed4e1292d35fe40f2d62c6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9140">issues.joomla.org/joomla-cms/9140</a>.</sub>

**Comment by rehrumesh** [comment]
I have tested this item :white_check_mark:  
https://github.com/joomla/joomla-cms/commit/91f2c716d87096427ed4e1292d35fe40f2d62c6a

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9140">issues.joomla.org/joomla-cms/9140</a>.</sub>

**Comment by JoomliC** [comment]
Thanks @dgt41 and @rehrumesh for testing!

@brianteeman hope my English not too bad in the layout modal main file ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9140">issues.joomla.org/joomla-cms/9140</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @JoomliC and testers!

**Comment by rehrumesh** [comment]
I have tested this item :white_check_mark: successfully on 91f2c716d87096427ed4e1292d35fe40f2d62c6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9140">issues.joomla.org/joomla-cms/9140</a>.</sub>

**Comment by brianteeman** [comment]
@rehrumesh thanks for your tests but you are testing issues that have already been merged <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9140">issues.joomla.org/joomla-cms/9140</a>.</sub>

**Comment by rehrumesh** [comment]
Earlier I hadn't use the JTracker application. So marked it again using JTracker.

**Comment by smz** [comment]
Sorry to resurrect this already merged PR, but I think what has been done here is really wrong:

You can't fix a Bootstrap modal problem by hacking the **content** of the modal. That could work today for today backend content but has the potential of breaking frontend usage of the Bootstrap modals or tomorrow usage in the backend with different header/footer sizes.

A correct approach would had been to correct the issue at the `modal` (container) itself, and absolutely not by imposing restrictions on the `.modal-body` based on specific assumptions about the header, footer and padding size.

This had probably meant to correct the Bootstrap modal JS itself, but that would had been the **only** correct solution.

**Comment by smz** [comment]
OMG, now I see this is a specific Webkit issue, and **there are** correct solutions here: https://github.com/twbs/bootstrap/issues/14839

I think we can't cut corners to badly fix specific iOS issues, especially if correct solutions are already available.

**Pull request merged**
