### PR TITLE
CodeMirror updated to 5.38.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
### Summary of Changes

CodeMirror updated: http://codemirror.net/doc/releases.html

### Testing Instructions

Use CodeMirror

### Expected result

It should work normally

### Actual result

Sure, it does.

### Documentation Changes Required

Nope.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cdaf42dd63b6b817586382830f3a008c6b715ea0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20636">issues.joomla.org/tracker/joomla-cms/20636</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cdaf42dd63b6b817586382830f3a008c6b715ea0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20636">issues.joomla.org/tracker/joomla-cms/20636</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20636">issues.joomla.org/tracker/joomla-cms/20636</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
