### PR TITLE
[4] Expression can be safely replaced

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Expression can be safely replaced and simplified and was Code Smell as reported by phpStorm.

### Testing Instructions

Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c5fe431426199cd4c364ee754e791dc2f87a84bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31056">issues.joomla.org/tracker/joomla-cms/31056</a>.</sub>

**Comment by ceford** [comment]
Not sure about this. My source was slightly different from the diff
-		$mode = $mode === 1 ? true : false;
my source
		$mode = $mode === 1;
Although the result was as expected. I am set up for testing with the nightly build.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31056">issues.joomla.org/tracker/joomla-cms/31056</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c5fe431426199cd4c364ee754e791dc2f87a84bd<br /><br />Changed to my new Test setup - doing it right this time - saw code change OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31056">issues.joomla.org/tracker/joomla-cms/31056</a>.</sub>

**Comment by Quy** [comment]
Please fix conflicts. Thanks.

**Comment by PhilETaylor** [comment]
It looks like one of my other PRs already merged already addressed this change 


https://github.com/joomla/joomla-cms/pull/31071/files

**Pull request closed without merging**
