### PR TITLE
[4.0] Use namespaced classes in privacy plugins

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use namespaced classes instead of aliases.

### Testing Instructions

Submit a data export request (using `com_privacy`).

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 97a88bb944709a1e3fe3358f4b7f88f6e6d0ce34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29099">issues.joomla.org/tracker/joomla-cms/29099</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 97a88bb944709a1e3fe3358f4b7f88f6e6d0ce34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29099">issues.joomla.org/tracker/joomla-cms/29099</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29099">issues.joomla.org/tracker/joomla-cms/29099</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks @SharkyKZ

**Pull request merged**
