### PR TITLE
[JFilterInput] add some test cases with unicode chars

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue add some test cases with unicode chars.

### Summary of Changes

adds some test cases with unicode chars (does not cover all cases just makes improvements in the test cases)

### Testing Instructions
code review / unit tests pass

### Documentation Changes Required
none

### CODE REVIEW

**Comment by rdeutz** [comment]
Did you add this tests to let the system fail for the issue #15673 

Have done it local but all test run successfully

**Comment by photodude** [comment]
@rdeutz This PR is intended to pass. These are just some base cases that currently work for multibyte characters but are not included in tests to verify that they work. Adding these will help avoid regressions.

**Comment by rdeutz** [comment]
Ok, thanks for explaining.

**Comment by rdeutz** [comment]
merged on review

**Pull request merged**
