### PR TITLE
Mod languages ative languages absolute URI fix

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Description

Problem: Mod languages uses an absolute URI in the ative language flag image link and site root relative URI for the other languages.

This patch converts the absolute URI in the ative language URI to site root relative URI.
### How to test

After the patch the ative language URI in mod languages flag image link should be relative to site root.
### B/C

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Don't know why travis failed in php 7 tests.
A lot of permisisons denied.

**Comment by zero-24** [comment]
@andrepereiradasilva

It don't look like realted to your patch. And it is not just you. Maybe Travis has problems with PHP 7 Builds ;)

**Comment by andrepereiradasilva** [comment]
Ok. Let's wait for a more healthy travis.

**Comment by infograf768** [comment]
Tested and I see no issue with this patch.
There was no issue before either.

**Comment by andrepereiradasilva** [comment]
@infograf768 yes that was no issue earlier, is just a question of normalization. If the other URI are site root relative the ative language URI should be too.

**Comment by richard67** [comment]
From my point of view, the active language link is useless anyway because it always points to the current page. If someone on a smart phone has thick fingers, he well be happy when there is one useless link he might accidently tip on while trying to tip on the one beside. On my website I have therefore made an overrride for the language switcher module, which shows for the current language the flag or text as a picture or a text only but not as a link, and with CSS style I give it a different appearance so everybody can see this is the current language.

So I think this PR here deals with making something which is useless anyway to be formally more correct.

@infograf768 What do you think about my opinion? You can have a look on [my website](http://www.richard-fath.de "http://www.richard-fath.de") to see how it looks like.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Comment by richard67** [comment]
P.S.: @infograf768  If you like it, I can make a PR for this as a suggestion for improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 this PR is only to correct that minor normalization issue.
If you want to make other changes please open a PR and i will close this one if yours is merged.

By the way i think the flasg transperency from and usability point should be inverted (transparency not selected, no transparency selected). The selected items normally are highlited (ex: bold, other color, other background color, etc), see your menu for instance.

**Comment by richard67** [comment]
@andrepereiradasilva Right, my idea is another issue than this PR, it is just related. I did not want to mess up your PR, sorry. Just was curious on what @infograf768 thinks about it. Regarding the transparency: I tried both variants, the one I have now with the transparent active language flag I liked more because the pale flag makes it look a bit like a deactivated control, which fits to the fact that there is no link anymore. But in case somebody wanted this functionality in Joomla and I would make a PR for that (independently from yours at a later point of time) I could maybe find a better way of styling.

Ah, and I remembered the active language link not right because I don't use it. I think now it does not point to the current page but to the home page. But this does not make this link more useful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Comment by infograf768** [comment]
@richard67 
The active language link does point to the current page and not Home.
I am not sure we need to take off the link.
We do have a parameter to not display the active language and I guess it is enough.
In any case, this can be overriden if desired, as you did.

**Comment by andrepereiradasilva** [comment]
There is no travis problem.
@zero-24 how can we retest in travis?

**Comment by zero-24** [comment]
@andrepereiradasilva you can't do this by your self but i have just restarted it ;) It is the old error on PHP 7 Builds ;)

**Comment by andrepereiradasilva** [comment]
@thanks @zero-24

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b38a25cf3fb8064a803ba483942bff8200b35338<br /><br />Totally B/C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on b38a25cf3fb8064a803ba483942bff8200b35338<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8440">issues.joomla.org/joomla-cms/8440</a>.</sub>

**Pull request closed without merging**
