### PR TITLE
Add dropdown tasks items to categories

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvements.
#### Summary of Changes

This PR adds state tasks dropdown actions to categories.
##### Before PR

image
##### After PR

image
#### Testing Instructions
1. Use latest staging and apply patch 
2. Test the new dropdown menu in all possible category states (published, unpublished, archived and trash)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b055d84be5aa52a1c8d523890bcd8da7f34f6db7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by brianteeman** [comment]
If you look at com_content as an example you will see that this is not correct. You do not need to have publish and unpublish as they are achieved by selecting the button. You do however need archive and trash.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by andrepereiradasilva** [comment]
actually, i analysed com_content implementation and i think there are some problems:

1. doesn't check if the user can change the sate
2. The buttons are based on the filters states an not on the item state. this creates some problems (make the filter All and you can check an article in trash state has trash option ... similiar an article in archived state has archive option)
3. There is no one click way to pass from archive or trash to publish

See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/tmpl/default.php#L136-L150

Because of this issues, proposed a new implementation here.
Advantages:

1. Checks if the user can change the state
2. The buttons are based on the item state, basicly all action that not the current item state appear.
3. Allows a one click way to pass from archive or trash to publish

**Comment by brianteeman** [comment]
This dropdown was specifically done for accessibility I would not be in
favour in a change of this behaviour

On 23 April 2016 at 11:01, andrepereiradasilva <notifications@github.com>
wrote:

> actually, i analysed com_content implementation and i think there are some
> problems:
>
>    1. doesn't check if the user can change the sate
>    2. The buttons are based on the filters states an not on the item
>    state. this creates some problems (make the filter All and you can check an
>    article in trash state has trash option ... similiar an article in archived
>    state has archive option)
>    3. There is no one click way to pass from archive or trash to publish
>
> See
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/tmpl/default.php#L136-L150
>
> Because of this issues, proposed a new implementation here.
> Advantages:
>
>    1. Checks if the user can change the state
>    2. The buttons are based on the item state, basicly all action that
>    not the current item state appear.
>    3. Allows a one click way to pass from archive or trash to publish
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10056#issuecomment-213705289>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
> This dropdown was specifically done for accessibility

ok, but it's also very useful has it enables to change the state of the item in one click. instead of checking and then click the button.

> I would not be in favour in a change of this behaviour

I would. It makes a lot more sense for me.
But ok, for the time being i can follow the content behaviour but without it's bugs described in "1." and "2.".

**Comment by brianteeman** [comment]
You should also know that everytime we have tried to introduce any type of
functionality where options are not available because of a state it has
been rejected by luddites

On 23 April 2016 at 11:16, andrepereiradasilva <notifications@github.com>
wrote:

> This dropdown was specifically done for accessibility
>
> ok, but it's also very useful has it enables to change the state of the
> item in one click. instead of checking and then click the button.
>
> I would not be in favour in a change of this behaviour
>
> I would. It makes a lot more sense for me.
> But ok, for the time being i can follow the content behaviour but without
> it's bugs described in "1." and "2.".
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10056#issuecomment-213710921>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 11d2282eaa4aca9bae1c30b12810c667408663af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 11d2282eaa4aca9bae1c30b12810c667408663af<br /><br />@andrepereiradasilva Hmm, your new screenshot shows "Archive" and "Publish" in the dropdown, but according to the discussion with @brianteeman above, as far as I understood, it should be "Archive" and "Trash", and this is what I get when testing. It is also consistent with the behavior in the articles list view. I assume this was what was intended ans set my test result to "success".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> It is also consistent with the behavior in the articles list view. I assume this was what was intended ans set my test result to "success".

I replicated exactly the com_content way, without the bugs

**Comment by richard67** [comment]
I know, but then your screenshot is wrong.

**Comment by richard67** [comment]
Ah, no, is correct: It is a trashed item where it belongs to. Maybe I need glasses?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by andrepereiradasilva** [comment]
no it tsn't :smile: works like this:

- item state = published: Archive; Trash
- item state = unpublished: Archive; Trash
- item state = archived: Unarchive; Trash
- item state = trashed: Archive; Publish

I know it doesn't make a lot of sense to me either... but it is the way com_contetn is right now.

**Comment by andrepereiradasilva** [comment]
ups i see you already commented.

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10056">issues.joomla.org/joomla-cms/10056</a>.</sub>

**Comment by brianteeman** [comment]
I have set it to 3.6 as I think @rdeutz will say this is a new feature and not a bug fix

**Comment by richard67** [comment]
Yes, this is some kind of predictable.

**Comment by rdeutz** [comment]
tempted to merge it in 3.5.2 but ... no :-)

**Pull request merged**
