### PR TITLE
[4.0] com_finder jquery

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the comment so it doesnt scare @dgrammatiko 

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c90367c4986a92e0698bf024a788cb847e6dcb4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34035">issues.joomla.org/tracker/joomla-cms/34035</a>.</sub>

**Comment by richard67** [comment]
@dgrammatiko Can we see your thumbs up as a good test?

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on c90367c4986a92e0698bf024a788cb847e6dcb4f<br /><br />Yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34035">issues.joomla.org/tracker/joomla-cms/34035</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34035">issues.joomla.org/tracker/joomla-cms/34035</a>.</sub>

**Pull request merged**
