### PR TITLE
[4.0] mod_feed comment

### PR DESCRIPTION
**Pull request by brianteeman**
Correct the code comment. code review should be fine

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4390430ea35f40df5aafa661f5e9a65a350c5cec<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33615">issues.joomla.org/tracker/joomla-cms/33615</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4390430ea35f40df5aafa661f5e9a65a350c5cec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33615">issues.joomla.org/tracker/joomla-cms/33615</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33615">issues.joomla.org/tracker/joomla-cms/33615</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
I know its only a comment but if we have them then its better for them to be correct.
thanks

**Pull request merged**
