### PR TITLE
[5.0] Added missing "items" text to the Joomla update view

### PR DESCRIPTION
**Pull request by beni71**
Pull Request for Issue #39829.

### Summary of Changes
Added missing "items" text to the Joomla update view.

### Testing Instructions
After the patch is applied you have to update your Joomla without reverting the code change of the patch!
Maybe there is an easier/better approach to do but you could follow these steps:

1. Apply the patch
2. Create a .zip file from your components folder and store that .zip file outside of the Joomla folder. It is used later to regularly update Joomla (which will just copy the same files).
3. Login into the backend (administrator area).
4. In the left hand toggle menu click "System".
5. In the "Update" section click "Joomla".
6. Click the button "Upload and Update".
7. Choose your .zip file (from step 2).
8. Check the box "I'm aware that a backup before any update is highly recommended. ".
9. Click the button "Upload & Install".
10. Confirm your credentials.
11. Click button "Install". 

### Actual result BEFORE applying this Pull Request
In the third column only the number of extracted/processed items is visualized:

Screenshot 2023-06-08 192950

### Expected result AFTER applying this Pull Request
In the third column the number of extracted/processed items is visualized with an additional text "items":

Screenshot 2023-06-10 145523

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@beni71 There is not really the need to build your own package for testing. Our automated ci tool drone already does that for every pull request. When you use the „show all checks“ at the bottom of the pull request on GitHub, the ci checks are shown, among of them is a „Download“ step. Follow that link and you come to a page where you can find a custom update url and links to installation and update packages which contain the fix from this pull request.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 4004b048a345e9ffbfefe49a76372f6527f02baf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40742">issues.joomla.org/tracker/joomla-cms/40742</a>.</sub>

**Comment by sandewt** [comment]
Yet another critical note, with this pr:

5030 + 2622 = 7652 Files (= bestanden) + Folders (= mappen)

In other words, the suffix 'Files' is not correct.  It be should be 'Files and folders' or 'Folders and files'. 
Can this be confirmed?

issue-40472


Schermafbeelding 2023-06-09 094300

**Comment by sandewt** [comment]
I have tested this item :red_circle: unsuccessfully on 4004b048a345e9ffbfefe49a76372f6527f02baf<br /><br />See comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40742">issues.joomla.org/tracker/joomla-cms/40742</a>.</sub>

**Comment by richard67** [comment]
@sandewt For a filesystem, a folder is just a special kind of file, at least for unixoids. So I would be ok with "files". But lets see if other opinions come in.

**Comment by sandewt** [comment]
> a folder is just a special kind of file,

Also plausible reasoning to consider files as a collective name of files and folders. It keeps the text short.

**Comment by HLeithner** [comment]
2 ways:

1. Call it "Objects" or "Entries"
2. Only show files as counter.

Using "Files" for Folders and Files maybe not completely wrong but I think we could use a more common wording.

**Comment by richard67** [comment]
> 2 ways:
> 
> 1. Call it "Objects" or "Entries"
> 2. Only show files as counter.

1. … or „Items“, or „Unpacked“
2. Good idea.

**Comment by brianteeman** [comment]
items

**Comment by alikon** [comment]
choose whatever 
we are postponed the problem to the translators

**Comment by sandewt** [comment]
One more suggestion. The Dutch word 'Inhoud' is English 'Content'. 

Everyone knows what is meant by `Content` (and it is easy to translate :smiley:)

244626602-bd18000c-3cf1-4513-91d0-14808dfae935

**Comment by brianteeman** [comment]
It's not content in English

**Comment by richard67** [comment]
And content is not countable.

**Comment by beni71** [comment]
When I unzip a .zip file in MS Windows, the progress dialog shows "items" (English) and, for example, "Elements" in German. I think we can reuse this phrase, some of you have already suggested it. And for other languages we would have a template.

**Comment by HLeithner** [comment]
> When I unzip a .zip file in MS Windows, the progress dialog shows "items" (English) and, for example, "Elements" in German. I think we can reuse this phrase, some of you have already suggested it. And for other languages we would have a template.

so you have your answer please use items, then this can be merged.

thanks

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 73c7eccc76aaa97d117da9eef7456ea624a32012<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40742">issues.joomla.org/tracker/joomla-cms/40742</a>.</sub>

**Comment by sandewt** [comment]
Image last test for information

issue-40472-3

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 08a0acf7bae18d9525142fb1a7395cd7b24d2ec7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40742">issues.joomla.org/tracker/joomla-cms/40742</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40742">issues.joomla.org/tracker/joomla-cms/40742</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
