### PR TITLE
Changed Fields into Field

### PR DESCRIPTION
**Pull request by MartijnMaandag**
In the tiny editor it is Module, Article and Contact to insert a link.

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e1fba3ef1f61bea64a88c7161a3622b64547b78d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14964">issues.joomla.org/tracker/joomla-cms/14964</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e1fba3ef1f61bea64a88c7161a3622b64547b78d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14964">issues.joomla.org/tracker/joomla-cms/14964</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14964">issues.joomla.org/tracker/joomla-cms/14964</a>.</sub>

**Review by brianteeman — APPROVED** [review]

**Comment by cokencorn** [comment]
I have tested this item :white_check_mark: successfully on e1fba3ef1f61bea64a88c7161a3622b64547b78d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14964">issues.joomla.org/tracker/joomla-cms/14964</a>.</sub>

**Pull request merged**
