### PR TITLE
[4.0] Badge added in Urgent privacy request

### PR DESCRIPTION
**Pull request by rjharishabh**

### CODE REVIEW

**Comment by brianteeman** [comment]
Please post a screenshot of this working as I can't see how it would be possible

**Comment by YatharthVyas** [comment]
I have tested this item :red_circle: unsuccessfully on df5a43ece53638ae9597084b0fc98b02b44cb888<br /><br />Please check the screenshot in my next message:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33711">issues.joomla.org/tracker/joomla-cms/33711</a>.</sub>

**Comment by YatharthVyas** [comment]
### Before
image


### After
image

@rjharishabh This is how it looks after applying the patch.

**Comment by brianteeman** [comment]
to understand what is wrong you need to look at the use of Text::sprintf

**Comment by rjharishabh** [comment]
@brianteeman sorry it's gone wrong. 
I will take care of it from next time

**Comment by brianteeman** [comment]
its ok - just make sure you check your work before submitting the pr

**Comment by rjharishabh** [comment]
> its ok - just make sure you check your work before submitting the pr

Yes

**Pull request closed without merging**
