### PR TITLE
[4.0] search ellipsis

### PR DESCRIPTION
**Pull request by brianteeman**
partial fix for #31346

Every other search box just says "search" not "search..."

(and anyway the style guide says there should have been a space before the ...)

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on b4029ce3fb8bb98b2877d9cca05b8cd6c3dc7a0d<br /><br />DONE :)!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31451">issues.joomla.org/tracker/joomla-cms/31451</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b4029ce3fb8bb98b2877d9cca05b8cd6c3dc7a0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31451">issues.joomla.org/tracker/joomla-cms/31451</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31451">issues.joomla.org/tracker/joomla-cms/31451</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
