### PR TITLE
Semantic image captions

### PR DESCRIPTION
**Pull request by nternetinspired**
## Overview

Following the Google Group discussion regarding jCaption https://groups.google.com/forum/#!topic/joomla-dev-general/vW--mTtuaaw this PR implements semantic figure and captioning elements.

Joomla ships with the html5 doctype, so it is my opinion that we should be using the correct elements wherever possible. Article images and their captions are what  and  are made for.

This change not only improves the document semantics, and therefore accessibility, it also removes the need for caption.js, which calls the entire Mootools stack whenever it is loaded.
## Changes

This PR makes several changes, namely:
1. Disabling calls to jCaption and marking as deprecated.
2. Updating markup surrounding article intro and article full text images to implement html5s figure and figcaption elements.
3. Updates the featured layout to use the JLayout intro image helper, as the category blog layout already does.
## Testing
1. Insert article images (intro and full-text) using the 'images and links' fields.
2. Insert image captions using the 'images and links' Caption field, one for intro image, one for full-text.
3. Set the article to 'featured' status.
4. Check that the image caption appears in article, category blog and featured blog view.
5. Check that the 'Image float' option is honored in these views.
6. Check that caption.js is no longer loaded in these views.

### CODE REVIEW

**Comment by zero-24** [comment]
Hi @nternetinspired @betweenbrain 

is this issue still valid? As the last comment here was on 1 Aug 2014? Also pull requests to the master branch of this repo are not longer accepted. Can you close this pull request and submit a new one against the staging branch, if this issue still exists?
If there is no Response in a month we will close the PR here.

Thanks for understanding!

**Comment by nternetinspired** [comment]
Yes the issues still exists; 

1. We call things that aren't captions “captions”,
2.  We center them when alignment>none is chosen,
3. We use javascript to do something that can be done with a single html tag.

I call bull:hankey: on all three.

**Comment by designbengel** [comment]
Tested on introimage and Full Article Image in Images and Links Tab:
Failed: 
- The output of the caption is not in "figcaption" tags but in paragraphs.
- caption.js is not removed by the patch.

Works: When i insert an image with captions in the editor it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2657">issues.joomla.org/joomla-cms/2657</a>.</sub>

**Comment by nternetinspired** [comment]
@designbengel Did you apply the patch? If you did, and you insert an image with a caption it will be inserted with `<figcaption>`. The caption inside `<p>` tags is the existing behaviour which this PR attempts to correct. This patch does not remove caption.js

**Comment by designbengel** [comment]
@nternetinspired Yes i applied the patch. It works for images which are inserted with editor in the content. But when i insert Intro or Fulltext image in the Images and Links tab of an article it does not put the caption into <figcaption> but in <p> tags.

**Comment by nternetinspired** [comment]
> It works for images which are inserted with editor in the content.

That has nothing to do with this PR, that is native editor functionality and not changed by this PR.

> But when i insert Intro or Fulltext image in the Images and Links tab of an article it does not put the caption

Are you checking with Protostar? What you describe sounds like this PR is not applied at all.

**Comment by roland-d** [comment]
@nternetinspired Could you please make this PR against staging? I also think that @designbengel may not have applied the PR because it is against master.

Thanks Seth.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2657">issues.joomla.org/joomla-cms/2657</a>.</sub>

**Comment by zero-24** [comment]
New PR against staging: https://github.com/joomla/joomla-cms/pull/7450 Closing.

@nternetinspired can i get you to review the new PR? And others on test?

**Pull request closed without merging**
