### PR TITLE
[4.1] Check File Size task options

### PR DESCRIPTION
**Pull request by brianteeman**
The Directory to check is a required field. But because of the options in the xml it will happily store "None Selected" which is an error and so the required attribute does nothing.

This PR corrects that behaviour

To test
Create a new scheduled task for Image Size check. You can save the task with directory set as None Selected
After the pr you will now get an error if you try to save with None Selected

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 139eb9e5e14a157ee7157afcf3a8f79b6f68e585<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36240">issues.joomla.org/tracker/joomla-cms/36240</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on be407f73be5333c88c562272704f6830e8ab91ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36240">issues.joomla.org/tracker/joomla-cms/36240</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36240">issues.joomla.org/tracker/joomla-cms/36240</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on be407f73be5333c88c562272704f6830e8ab91ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36240">issues.joomla.org/tracker/joomla-cms/36240</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
