### PR TITLE
add images folder in gitignore

### PR DESCRIPTION
**Pull request by Kaushik1216**
Pull Request for Issue # .

### Summary of Changes

Updated git ignore so that image folder ignored

### Actual result BEFORE applying this Pull Request
Images inside images folder is track by git 

### Expected result AFTER applying this Pull Request
images inside images folder is not track by git anymore

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Why would we want to do that? Please think carefully about what this will mean.

**Comment by Kaushik1216** [comment]
If we add images in our images folder other than joomla default images it is tracked by git so if we create pr that images will come 
considering this I add images folder in gitignore .As I am beginner in joomla ,Please give a reason why images folder should not ignore ,Thanks in advance

**Comment by richard67** [comment]
When we add the images finder to gitignore, we can’t maintain anymore on GitHub the images provided by the CMS core. When you work on a git clone of the CMS and add new images, you should clean up your branch before working on pull requests, or better use different branches for testing and making pull requests, and the testing branches you reset with git clean command so you never check in accidentally any stuff you have added for testing, like images or whatever.

**Comment by richard67** [comment]
Closing for the reasons stated above.

**Comment by brianteeman** [comment]
In addition any additional images will be added to your pull request ONLY if you commit them to your branch

**Pull request closed without merging**
