### PR TITLE
Regression: Pressing enter/return on create menu takes you to create menus page

### PR DESCRIPTION
**Pull request by wojsmol**
fix for joomla#8839 and other modal buttons

> ### Steps to reproduce the issue
> 
> Create a new menu item, fill in the required fields, press enter/return.
> ### Expected result
> 
> Expected behaviour is save menu item (and return to menu in question). i.e. exactly the same as save & close.
> ### Actual result
> 
> You arrive at the create menus page. The item does not get saved.
> ### System information (as much as possible)
> 
> System Information
> Setting Value
> 
> PHP Built On Linux mail.sfworksdev.co.uk 2.6.32-431.5.1.el6.x86_64 #1 SMP Wed Feb 12 00:41:43 UTC 2014 x86_64
> Database Version 5.5.37
> Database Collation utf8_general_ci
> PHP Version 5.4.37
> Web Server Apache
> WebServer to PHP Interface cgi-fcgi
> Joomla! Version Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
> ### Additional comments

PR based on https://github.com/joomla/joomla-cms/issues/8839#issuecomment-168977447

### CODE REVIEW

**Comment by dgt41** [comment]
This one can be merged on review. Everything is OK here!

**Comment by wojsmol** [comment]
@dgt41 Thank you for the green light, it is very important to me.

**Comment by infograf768** [comment]
Typo=> `typr` instead of `type`:
```
-				'footer' => '<button class="btn" data-dismiss="modal" aria-hidden="true">'
+				'footer' => '<button class="btn" typr="button" data-dismiss="modal" aria-hidden="true">'
 					. JText::_("JLIB_HTML_BEHAVIOR_CLOSE") . '</button>'
```

**Comment by wojsmol** [comment]
@infograf768 typo foxed :smile:

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on dda327432f8c11ede167d76ceec6d5f7792cf73d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8874">issues.joomla.org/joomla-cms/8874</a>.</sub>

**Comment by infograf768** [comment]
Changed title as this is a regression.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8874">issues.joomla.org/joomla-cms/8874</a>.</sub>

**Comment by infograf768** [comment]
Milestone should be 3.5.0. For me, RTC

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on dda327432f8c11ede167d76ceec6d5f7792cf73d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8874">issues.joomla.org/joomla-cms/8874</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8874">issues.joomla.org/joomla-cms/8874</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/9d805edeedabc6b7e9a7d4ad28d6db8f2810c8c3

**Pull request closed without merging**
