### PR TITLE
[4.3] Smart Search: Fixing toolbar button name

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The "Clear Index" button currently has the name `index.purge`, which results in a class with the name `button-index.purge`. Notice the . in the class name, which is an invalid class name. This PR renames that button to `index-purge`.

### Testing Instructions
Codereview.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9e9985741311492a4d588516a8452e2df7a32d68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39976">issues.joomla.org/tracker/joomla-cms/39976</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9e9985741311492a4d588516a8452e2df7a32d68<br /><br />Tested successfully in Joomla 4.3.0-beta4-dev of 2 March.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39976">issues.joomla.org/tracker/joomla-cms/39976</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39976">issues.joomla.org/tracker/joomla-cms/39976</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar!

**Pull request merged**
