### PR TITLE
[5.1] upmerges 2023-10-16

### PR DESCRIPTION
**Pull request by LadySolveig**
Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@LadySolveig You should not use s quash commit but a merge commit, otherwise the change history for the single commits from 5.0-dev will get lost. The GitHub UI is a bit tricky. The green button remembers what you have used last time, squash or merge, so if you come from daily maintainer work with merging PRs, which is done with squash, and then want to merge up branches, which has to be done with merge, you have to toggle the commit type with the dropdown of the green merge button before merging.

**Comment by richard67** [comment]
P.S.: I also can't see the changes from this PR in the changes here, so the upmerge here is either outdated or there is something else wrong: #42103 .

**Comment by LadySolveig** [comment]
> @LadySolveig You should not use s quash commit but a merge commit, otherwise the change history for the single commits from 5.0-dev will get lost. The GitHub UI is a bit tricky. The green button remembers what you have used last time, squash or merge, so if you come from daily maintainer work with merging PRs, which is done with squash, and then want to merge up branches, which has to be done with merge, you have to toggle the commit type with the dropdown of the green merge button before merging.

Absolutly right, sorry I forgot to change after editing the title.

**Comment by richard67** [comment]
No need for sorry. That green button is really a tricky thing.

**Comment by richard67** [comment]
#42146 looks good, all right.

**Pull request closed without merging**
