### PR TITLE
[4.0] plg_webservices descriptions

### PR DESCRIPTION
**Pull request by brianteeman**
Singular not plural

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 36b7957a37c26389057f250722e881f126b8446c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33757">issues.joomla.org/tracker/joomla-cms/33757</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 36b7957a37c26389057f250722e881f126b8446c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33757">issues.joomla.org/tracker/joomla-cms/33757</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33757">issues.joomla.org/tracker/joomla-cms/33757</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
