### PR TITLE
[4] s/JTable/Table

### PR DESCRIPTION
**Pull request by PhilETaylor**
cde reis zz

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on fa99f9fa6540bcef9000a5a0b5d52b6ed1292bff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34011">issues.joomla.org/tracker/joomla-cms/34011</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fa99f9fa6540bcef9000a5a0b5d52b6ed1292bff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34011">issues.joomla.org/tracker/joomla-cms/34011</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34011">issues.joomla.org/tracker/joomla-cms/34011</a>.</sub>

**Comment by richard67** [comment]
> cde reis zz

@PhilETaylor Covfefe ?

**Comment by PhilETaylor** [comment]
Zzzzzz....

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
