### PR TITLE
Messages inside the new Joomla 3.6 updater / max upload size is lower than 8mb

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #10604 
#### Summary of Changes

change extensions to packages
#### Testing Instructions
- set maximum upload file size to less than 8MB
- see the message in the updater
- see the message in the extension manger

### CODE REVIEW

**Comment by zero-24** [comment]
@brianteeman is the language change acceptable? As the same string is used in both places.

**Comment by brianteeman** [comment]
Not really. Will answer in full when I get home.

**Comment by brianteeman** [comment]
Thats what happens when I read a PR on my phone. Your string is fine by me. The one that is not good is https://github.com/zero-24/joomla-cms/blob/280b8348266ed7b25879f3b6d84dcc2815b78d76/administrator/language/en-GB/en-GB.com_installer.ini#L170 but thats for another PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10707">issues.joomla.org/joomla-cms/10707</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 280b8348266ed7b25879f3b6d84dcc2815b78d76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10707">issues.joomla.org/joomla-cms/10707</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 280b8348266ed7b25879f3b6d84dcc2815b78d76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10707">issues.joomla.org/joomla-cms/10707</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10707">issues.joomla.org/joomla-cms/10707</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
