### PR TITLE
[#33126] Corrections to both Tags List views to show images and obey all params

### PR DESCRIPTION
**Pull request by radiant-tech**
Both the UL and Table list views for com_tags have multiple problems in not checking and/or using set params.  This patch fixes:
1) Don't use Document title in the h2 heading; instead, if for a single tag, shows the title of that tag, if multiple tags, shows each tag title separated by a comma.
2) For a single tag, show image and/or show description appear as expected.
3) For multiple tags, show image and/or show description (as set in the menu item) appear as expected.  This fixes them being shown on a single tag view.
4) Fixes to improperly closed image tags.
5) Adds "Results x - y of z" if show_tag_num_items is set.  Adding this where and how I did may or may not be the correct behavior.  Happy to accept input on that.
6) Added the content events to the Compact Table List (replicating what is done in the UL list) and added checks/display of item image and item description.

This work was started in response to Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33126
Related item here: http://joomlacode.org/gf/project/joomla/tracker/%3Faction%3DTrackerItemEdit&tracker_item_id%3D12376/?action=TrackerItemEdit&tracker_item_id=31115 (regarding incorrect use of Document title)

### CODE REVIEW

**Comment by timhaeuser** [comment]
don't understand the content of the description, so it's not possible for me to test it...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3222">issues.joomla.org/joomla-cms/3222</a>.</sub>

**Comment by d03ms** [comment]
i like @ tim<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3222">issues.joomla.org/joomla-cms/3222</a>.</sub>

**Comment by oorzaak** [comment]
I came across this issue during the pbf at JUG030 in Utrecht. I also read the older Tracker item that is refered to: I followed the testing instructions as stated here: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33126.
I totally agree with @radiant-tech that the implementations of the tags views need improvement. Yet I think this attempt to improve it needs more clarification before we can do some useful testing. 

In the first place, we have 3 menu types for tags; which of these menu item types is (are) targeted:
1. Compact list of tagged items;
2. List of all tags;
3. Tagged items


Next, I noticed that it is easy to become confused here as we are speaking, amongst others, of four types of images; it is quite crucial to point out which image is targeted: 
1. teaser images of tags,
2. full images of tags,
3. intro images of articles,
4. full text images of articles.

Also we are speaking of tag descriptions and article descriptions; I suppose that the latter should be: article intro texts?

Furthermore, as a related problem, I noticed that many of the parameters that are listed under Components > Tags > Options > Tagged items, are not present in the params of the menu items. For instance: in the List of all tags these parameters are missing:
- Item Images and 
- Item description
(Table Headings is not relevant for in this item type)

I think that solving this issue should include this as well.

I hope that these remarks can help solving the issue.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3222">issues.joomla.org/joomla-cms/3222</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your contribution but as it has been a long time since this was submitted without any response to multiple questions I have to close this at this time. It can always be updated and then re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/3222">issues.joomla.org/joomla-cms/3222</a>.</sub>

**Pull request closed without merging**
