### PR TITLE
Fix for [4.0] Password Strength Bar Width is 100%.

### PR DESCRIPTION
**Pull request by happy2dev**
Pull Request for Issue # .19227
Summary of Changes

Make Password Strength Bar Width equal to above input box
Testing Instructions

1/ Go to administrator/index.php?option=com_users
2/ Click New
3/ Enter a password
Expected result

Password Strength Bar Width is equal to above input box. This make nicer look.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Please do your PR against https://github.com/joomla/joomla-cms/pull/19231

**Comment by zero-24** [comment]
@dgt41 please update that PR first as this looks very out of date ;)

**Comment by happy2dev** [comment]
( sorry for my test )
Try to reopen to see what's happen

**Comment by dgrammatiko** [comment]
@zero-24 done!

@minhSDD actually this is already patched in #19231 but there are still some todos in that PR if you want to patch something!

screen shot 2018-03-23 at 19 35 18
screen shot 2018-03-23 at 19 38 10

**Comment by happy2dev** [comment]
@dgt41 : To start my work for your RP, I should run
`git checkout origin dgt41:fields/password`
Is it right ?

**Comment by dgrammatiko** [comment]
yup

**Comment by happy2dev** [comment]
@dgt41 : 
Please tell me the detail of job. I saw:
-Still Bootstrap specific
-Still Font awesome specific
-Needs A11Y audit
-Needs final approval form the design team
Then what exactly we should do ?

**Comment by dgrammatiko** [comment]
Here is a more detailed explanation of the todos:
- Remove bootstrap specific code:
Actions needed: rename the classes to not conflict with bootstrap (or better use some scss with specificity starting at the element `joomla-field-password`).
- Remove Font awesome dependency:
Create a scss file (check https://github.com/joomla/joomla-cms/blob/4.0-dev/build/webcomponents/scss/field-switcher/field-switcher.scss as a reference) and remove the fa fa-eye classes and use the svg instead.
- A11Y: I'm not an accessibility expert but I guess the first parent span, that in reality is a button, needs to be renamed to button tag. Also make sure the the click and keyboard events work correctly. There might be other issues with the progress bar and the extra notification, but that needs to be audited by someone like @zwiastunsw 

PS: just for reference you need to have node and npm installed.
You need to run `npm install` at the project's root folder

To recompile the elements you need to run:
for the scss to css: 
`node build.js --compilecescss`
for the js:
`node build.js --compilecejs`

**Comment by happy2dev** [comment]
@dgt41 Thanks for your point.
I can take a look at "Remove bootstrap specific" and "Remove Font awesome".
I will update when it's ready.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19971">issues.joomla.org/tracker/joomla-cms/19971</a>.</sub>

**Comment by C-Lodder** [comment]
Please dont just add your code to the SCSS and CSS files like you have. They need to be in the correct files and compiled properly.

**Comment by happy2dev** [comment]
@C-Lodder Please clear me:
I understand follow steps:
1/ edit scss file
2/ compile scss to css file
3/ minimized css to min.css
4/ .. commit scss, css, min.css to branch
pls point me the correct files and proper way to commit.
Thank you

**Comment by C-Lodder** [comment]
@minhSDD The is an open PR to convert this field to a custom element: https://github.com/joomla/joomla-cms/pull/19231 by @dgt41 

You'll need to add your code to the SCSS files in that PR and have them compiled against **his** PR.

**Comment by happy2dev** [comment]
@dgt41 Hi, pls guide me:
I already fork Joomla-cms from Joomla.
As to my understand, I have to fork your repository Joomla-cms, to see branch fields/password.
If I try to fork your repository Joomla-cms, it's always point to Joomla repository.
What should I do here ? Thank you

**Comment by minhSDD** [comment]
@dgt41 Hi, pls guide me:
I already fork Joomla-cms from Joomla.
As to my understand, I have to fork your repository Joomla-cms, to see branch fields/password.
If I try to fork your repository Joomla-cms, it's always point to Joomla repository.
What should I do here ? Thank you

**Comment by laoneo** [comment]
You can't fork the same repo twice in your account.

**Comment by Quy** [comment]
Fixed in PR #19231<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19971">issues.joomla.org/tracker/joomla-cms/19971</a>.</sub>

**Pull request closed without merging**
