### PR TITLE
[4.0] opcache invalidate

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24678 .

### Summary of Changes
porting of #21949 on 4.x

### Testing Instructions
see #24678

### Expected result
setting saved in global configuration setting

### Actual result
not saved at 1st save

### CODE REVIEW

**Comment by wilsonge** [comment]
If we're doing this we should probably call the full suite of functions https://github.com/joomla/joomla-cms/blob/34faac66c36b01834796f1522bc407020c27efa4/administrator/components/com_joomlaupdate/restore.php#L8317-L8333

**Comment by alikon** [comment]
i've only opcache available to test  :face_with_head_bandage: ....

**Comment by ghazal** [comment]
Something should be done one way or the other.
Anyhow this works.

**Comment by twister65** [comment]
> OPcache improves PHP performance by storing precompiled script bytecode in shared memory, thereby removing the need for PHP to load and parse scripts on each request.
> This extension is bundled with PHP 5.5.0 and later.

OPcache is the most usual. It is used on cloudaccess.net servers. I think the others are optional, as I did in these commits:
https://github.com/joomla/joomla-cms/pull/21949/commits/76b4634b31d52bcc65eb42212a16049db0f6bd4f
https://github.com/joomla/joomla-cms/pull/21949/commits/eb5c9b504f1a5de3e4dcc7a0ae3e9697c9c79db9
Some of the other functions are not longer maintained and are deprecated.
See https://github.com/joomla-framework/filesystem/issues/19#issuecomment-357465557

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on ede7190aff26be70e8a20f2ca060cb83a7cb81bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24709">issues.joomla.org/tracker/joomla-cms/24709</a>.</sub>

**Comment by wilsonge** [comment]
This has effectively been merged with the merging in of 3.9.1 earlier today. I still think we should add in all the cache functions that we support officially (obviously no issues dropping the ones no longer required in php 7)

**Pull request closed without merging**
