### PR TITLE
JLanguage::parseLanguageFiles performance improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR tries to improve performance of `JLanguage::parseLanguageFiles` (that is called by `JLanguage::getKnownLanguages`, which is also called by `JLanguageHelper::createLanguageList`).

It does so by replacing the php `RecursiveDirectoryIterator` usage by the usage of `glob`, and other small improvements.

No behaviour should be changed.
###### PHP with open_basedir

| Installed languages | Before PR | After PR |
| :-: | --: | --: |
| 6 | ~110.1 ms | ~1.4 ms |
| 5 | ~95.5 ms | ~1.2 ms |
| 4 | ~75.7 ms | ~1.1 ms |
| 3 | ~58.5 ms | ~0.9 ms |
| 2 | ~40.5 ms | ~0.6 ms |
| 1 | ~20.3 ms | ~0.4 ms |
###### PHP without open_basedir

| Installed languages | Before PR | After PR |
| :-: | --: | --: |
| 6 | ~17.4 ms | ~0.9 ms |
| 5 | ~14.3 ms | ~0.8 ms |
| 4 | ~11.2 ms | ~0.7 ms |
| 3 | ~9.5 ms | ~0.5 ms |
| 2 | ~6.1 ms | ~0.4 ms |
| 1 | ~3.2 ms | ~0.3 ms |

Notes:
- Tests were made with PHP 5.6 with opcache enabled and in SSD disks. Without opcache and in HDD disks the performance impact is far greater.
- The huge difference between PHP with or without `open_basedir` is because when using `open_basedir` php doesn't cache filesystem paths (even with `realpath_cache` enabled). More info: https://bugs.php.net/bug.php?id=52312
#### How to test
1. Apply this patch.
2. Go to any view/component/module/plugin that uses `JLanguage::getKnownLanguages` or `JLanguageHelper::createLanguageList`.
   Examples: mod_login in administrator, language code system plugin, com_languages overrides view in administrator and forms language fields.
3. For instance, for mod_login in administrator, check if the installed language selector is working properly in the admin login screen.

To check the performance improvements, turn on Joomla debugging and check the execution time, before and after the PR.
#### Observations

Suggestions, code reviews and improvements are welcome.

This could be further improved if we remove the files glob `for` cycle and the next `if`. I didn't remove it because i'm not sure if all installed language xml files in Joomla follow the following format: `language/zz-YY/zz-YY.xml` or `language/zzz-YY/zzz-YY.xml`. @infograf768 can you confirm this?

### CODE REVIEW

**Comment by infograf768** [comment]
>This could be further improved if we remove the files glob for cycle and the next if. I didn't remove it because i'm not sure if all installed language xml files in Joomla follow the following format: language/zz-YY/zz-YY.xml or language/zzz-YY/zzz-YY.xml. @infograf768 can you confirm this?

Correct: we use only 2 letters or 3 letters language code + 2 letters country code

Did not test patch yet. Tests should be done on the minimum required version of PHP i.e. 5.3.10

**Comment by andrepereiradasilva** [comment]
ok.
Don't need fot test now.

Later i will do some improvements them you can test.

Reggarding php 5.3.10 there should be no problem. `glob` is supported since 4.3.0 (http://php.net/manual/en/function.glob.php). But yes test should be done.

**Comment by andrepereiradasilva** [comment]
Also tested Joomla with 3 installed language in PHP 5.3.10 (with open_basedir), in HDD disks and, as suspected, the improvement is even bigger:

| Installed languages   |  Before PR   | After PR    |
|:---------------------:| ------------:| -----------:|
|           3           | ~168.1 ms    | ~2.5 ms     |

Note: tested usign php microtime function before/after the code:

```php
public static function parseLanguageFiles($dir = null)
{
	$st=microtime(true);
	// code removed for brevity
	echo number_format(((microtime(true)-$st)*1000),4);

	return $languages;
}
```

**Comment by infograf768** [comment]
You can safely change your preg_match to
`([a-z]{2,3})[-]([A-Z]{2})`
Ref:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_languages/models/language.php#L194

**Comment by andrepereiradasilva** [comment]
or just `[a-z]{2,3}-[A-Z]{2}` which is even better.

**Comment by andrepereiradasilva** [comment]
ok. this is the code i will submit later. Since there's few filesystem calls it's even a little better
```php
	public static function parseLanguageFiles($dir = null)
	{
		$languages = array();

		// Search main language directory for subdirectories
		foreach (glob($dir . '/*', GLOB_NOSORT | GLOB_ONLYDIR) as $directory)
		{
			// But only directories with lang code format
			if (preg_match('#/[a-z]{2,3}-[A-Z]{2}$#', $directory))
			{
				$dirPathParts = pathinfo($directory);
				$file         = $directory . '/' . $dirPathParts['filename'] . '.xml';

				if (!is_file($file))
				{
					continue;
				}
				try
				{
					// Get installed language metadata from xml file and merge it with lang array
					if ($metadata = self::parseXMLLanguageFile($file))
					{
						$languages = array_replace($languages, array($dirPathParts['filename'] => $metadata));
					}
				}
				catch (RuntimeException $e)
				{
				}
			}
		}

		return $languages;
	}
```

I just have one question, how Joomla treats the directories slash Windows/Linux?
Is there a constant for that?

**Comment by mbabker** [comment]
Just use `/` as PHP itself handles it just fine unless you're doing explicit string comparisons.

**Comment by andrepereiradasilva** [comment]
Ok. Thanks.
@mbabker, by the way if this PR is approved should i make a PR for Joomla Framework language repository too?

**Comment by mbabker** [comment]
Yes

**Comment by andrepereiradasilva** [comment]
code updated. performance tests updated.

Ok for testing now

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3b3de2624dbee66508585d40e1ef38ee96167cbb<br /><br />Although the speed improvement is not very important, it is real.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8873">issues.joomla.org/joomla-cms/8873</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 3b3de2624dbee66508585d40e1ef38ee96167cbb<br /><br />The login language selector is still working fine; I tested on PHP 5.5.28.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8873">issues.joomla.org/joomla-cms/8873</a>.</sub>

**Comment by andrepereiradasilva** [comment]
2 tests, also already in the framework https://github.com/joomla-framework/language/pull/37, RTC?

**Comment by brianteeman** [comment]
It was marked RTC by @dgt41 2 days ago<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8873">issues.joomla.org/joomla-cms/8873</a>.</sub>

**Comment by andrepereiradasilva** [comment]
oh.ok i just got
> joomla-cms-bot added the RTC label 3 minutes ago

**Pull request merged**
