### PR TITLE
Added css classes to the mod_login submit buttons

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Added css classes to the mod_login submit buttons. (Testability)

### Testing Instructions

Code review

### Documentation Changes Required

None

### CODE REVIEW

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on f7fbab287e6ae90fb266ec4aae350255e4dcba5a<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13379">issues.joomla.org/tracker/joomla-cms/13379</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f7fbab287e6ae90fb266ec4aae350255e4dcba5a<br /><br />Before Patch:

After Patch:
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13379">issues.joomla.org/tracker/joomla-cms/13379</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13379">issues.joomla.org/tracker/joomla-cms/13379</a>.</sub>

**Comment by wilsonge** [comment]
Is there a reason why the classes need to be different for frontend and backend? Secondly from just a pure front-end perspective I'd rather the classes are just `login-button` (i.e. semantic) rather than containing `mod-login` which isn't really helpful in anyway

**Comment by yvesh** [comment]
@wilsonge i followed the other elements naming scheme in the modules.. No idea why they are that way.

**Pull request merged**
