### PR TITLE
[4.0] Add scope

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change to table header and add scope.

### Testing Instructions
Code review.

or

Go to Menus > Manage
Visually titles are bold

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f3f0334c416331520fef447b1bc3076b96ce8c65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26406">issues.joomla.org/tracker/joomla-cms/26406</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f3f0334c416331520fef447b1bc3076b96ce8c65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26406">issues.joomla.org/tracker/joomla-cms/26406</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26406">issues.joomla.org/tracker/joomla-cms/26406</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
