### PR TITLE
[5.1] Typehint false for getItem

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
To improve compatibility with PHP type checking tools like PHPStan, we need to narrow the boolean return type, as a boolean is only returned as false.

Code review only.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a4a543563d7bc98a1b8eb0aa2c6dce5b02bdf560<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42972">issues.joomla.org/tracker/joomla-cms/42972</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a4a543563d7bc98a1b8eb0aa2c6dce5b02bdf560<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42972">issues.joomla.org/tracker/joomla-cms/42972</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42972">issues.joomla.org/tracker/joomla-cms/42972</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
