### PR TITLE
[4.0] remove comment

### PR DESCRIPTION
**Pull request by brianteeman**
The code comment is a copy paste from the library file and is not correct in these controllers. It doesn't need a replacement as most similar code doesnt have a comment at all.

code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f20d8e5b0bc5f99ba5ed62282bd3fea3947cbe39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34029">issues.joomla.org/tracker/joomla-cms/34029</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on f20d8e5b0bc5f99ba5ed62282bd3fea3947cbe39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34029">issues.joomla.org/tracker/joomla-cms/34029</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34029">issues.joomla.org/tracker/joomla-cms/34029</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks folks

**Pull request merged**
