### PR TITLE
[3.9.26] typos

### PR DESCRIPTION
**Pull request by brianteeman**
Fix obvious typos/spelling

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b8a6c4ad99e8855676da0bea376e07069d95ebff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33121">issues.joomla.org/tracker/joomla-cms/33121</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b8a6c4ad99e8855676da0bea376e07069d95ebff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33121">issues.joomla.org/tracker/joomla-cms/33121</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33121">issues.joomla.org/tracker/joomla-cms/33121</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
