### PR TITLE
CodeMirror updated to 5.14 - including match-highlighter plugin

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
#### Summary of Changes

http://codemirror.net/doc/releases.html

Includes improvements to vim mode which will benefit anyone who uses that. 
Also, the concatenated file is including the new `match-highlighter` plugin but a new option will be required to activate it. That will be available in a different PR.
#### Testing Instructions

Just use CodeMirror.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2eee84df7a3f0dd8bf51a72f84da9919072bd0b2<br /><br />Thanks for keeping this up to date<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10020">issues.joomla.org/joomla-cms/10020</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2eee84df7a3f0dd8bf51a72f84da9919072bd0b2<br /><br />Tested by editing template files and changing some of the plugin options, e.g. code folding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10020">issues.joomla.org/joomla-cms/10020</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10020">issues.joomla.org/joomla-cms/10020</a>.</sub>

**Comment by brianteeman** [comment]
If you guys could test #9948 which is an update for tinymce it would be appreciated

**Pull request merged**
