### PR TITLE
Modify error to language changes

### PR DESCRIPTION
**Pull request by marijkestuivenberg**
In this error the path to solve the error should be changed to the new language, Extension Manager is now Manage

### CODE REVIEW

**Comment by marijkestuivenberg** [comment]
Just read the discussion on issue #7850
If that issue results in a language change, this PR needs to be changed too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by marijkestuivenberg** [comment]
With the RTC on #8058 this PR can be tested in combination with adding that patch.

To test:

- Install the patch of #8050 
- Go to Extensions -> Templates , make sure Styles is selected on the left
- Check one of the templates that has no other styles (in the default install each template is suitable)
- Check the language in the error: Before this patch it points to Extensions-> Extension manager-> Manage->
After this patch the path is changed according to the new language (Extensions -> Manage -> Manage)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by SeigetsuShoen** [comment]
I have tested this item :red_circle: unsuccessfully on 4b24cd405fc46d64404282d82d9bfb5595ce2fc0<br /><br />The error message was not changed after applying patch 8058.screen shot 2015-10-24 at 05 37 08screen shot 2015-10-24 at 05 37 08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by rwhafner** [comment]
I have tested this item :white_check_mark: successfully on 4b24cd405fc46d64404282d82d9bfb5595ce2fc0<br /><br />First you have to install patch #8058 than this one (#7876) 
all changed as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by KingLouis1** [comment]
I have not tested this item.<br /><br />Not cleat what to check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by svom** [comment]
I have tested this item :white_check_mark: successfully on 4b24cd405fc46d64404282d82d9bfb5595ce2fc0<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Comment by zero-24** [comment]
@SeigetsuShoen you have applyed the Wrong patch ;) You need to apply #7876 and not #8058. I'm going to RTC here.

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7876">issues.joomla.org/joomla-cms/7876</a>.</sub>

**Pull request merged**
