### PR TITLE
Fix form validation when using patterns

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/20789.

### Summary of Changes

Declares variable using `var` to limit its scope and prevent overwriting function.

### Testing Instructions

Add pattern attribute to some form field.

E.g. `pattern="[A-Za-z\s0-9]+"` to `name` field in `components\com_users\models\forms\registration.xml`,
Try to register with name containing invalid characters.

### Expected result

Form not submitted with error:

>Invalid field:  Name 

### Actual result

Browser's validation tooltip is shown and we get JS error:

>TypeError: isValid is not a function

### Documentation Changes Required

No.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7eca2d65e02ddd733b3374ec6a83164e243ccf8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28996">issues.joomla.org/tracker/joomla-cms/28996</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 7eca2d65e02ddd733b3374ec6a83164e243ccf8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28996">issues.joomla.org/tracker/joomla-cms/28996</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28996">issues.joomla.org/tracker/joomla-cms/28996</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
