### PR TITLE
CSS Class for tag link

### PR DESCRIPTION
**Pull request by brianteeman**
Update string to be more accurate and consistent with similar strings in template styles

Pull Request for Issue #23547

### CODE REVIEW

**Comment by zero-24** [comment]
Just for the record this now removes the information that this behavior depends on the default layout to be used is that expected? As the result could be different when someone overwrote the layout? OR I'm missing something?

**Comment by brianteeman** [comment]
ALL options everywhere are dependant on the output - nothing special here - so no need to mention it.

Just as with a module layout that doesnt have an output for the title - the field is still present in the form

**Comment by zero-24** [comment]
Ok agree. Merging when drone is happy.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
