### PR TITLE
[4.0] Remove extraneous <

### PR DESCRIPTION
**Pull request by Quy**
Follow up to #31045 .

### Summary of Changes
Since the original PR is no longer accessible to make the change, this is a follow up PR to remove extraneous <.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9294d298d634e81e536bf78980652ea8ca696f54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32706">issues.joomla.org/tracker/joomla-cms/32706</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9294d298d634e81e536bf78980652ea8ca696f54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32706">issues.joomla.org/tracker/joomla-cms/32706</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32706">issues.joomla.org/tracker/joomla-cms/32706</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by Quy** [comment]
Thank you both!!!

**Pull request merged**
