### PR TITLE
[4.0] Installer strings

### PR DESCRIPTION
**Pull request by brianteeman**
Removes unused strings. They are duplicates of COM_INSTALLER_HEADER

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 6caee5774ee8a9f7818133d1d79452b3f4a38da8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36470">issues.joomla.org/tracker/joomla-cms/36470</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 6caee5774ee8a9f7818133d1d79452b3f4a38da8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36470">issues.joomla.org/tracker/joomla-cms/36470</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36470">issues.joomla.org/tracker/joomla-cms/36470</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
