### PR TITLE
Fix advanced search mod_finder in header

### PR DESCRIPTION
**Pull request by RickR2H**
This is a proposal Pull Request for Issue #37263 

### Summary of Changes
The styling of the advanced search is broken when used in the header. This PR adds the same styling als used in the left and right position. @brianteeman please review and comment.

### Testing Instructions
Add PR and build the CSS. For testing see issue mentioned above.

### Actual result BEFORE applying this Pull Request
Search button is stretchend and colors are wrong.

### CODE REVIEW

**Comment by richard67** [comment]
@RickR2H Code style errors see here: https://ci.joomla.org/joomla/joomla-cms/52396/1/24

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e073c7a8c5521cae49dab88073de8e887029620f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by RickR2H** [comment]
> @RickR2H Code style errors see here: https://ci.joomla.org/joomla/joomla-cms/52396/1/24

I was on it ;) Man you are quick!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 695f62baae2eaf044c63b74547fbb8da56ba4b80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by richard67** [comment]
> Testing Instructions
>
> Add PR and build the CSS. For testing see PR mentioned above.

@RickR2H I assume you mean "issue" and not "PR".

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on 695f62baae2eaf044c63b74547fbb8da56ba4b80<br /><br />Menu items in pull down submenus now have white text on white background.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by richard67** [comment]
j4 1-test-pr-37275-failed

**Comment by RickR2H** [comment]
@richard67 should be fixed now...

**Comment by richard67** [comment]
Will test tomorrow.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d58636f76121488bd1739e352579b31b05b6fbb2<br /><br />menu items ok now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by richard67** [comment]
I've restored the previous test result in the issue tracker since the commit which invalidated the test counter was just a clean branch update.

**Comment by RickR2H** [comment]
Thanks @richard67

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d3e531441b6708c21d05fa76e6156408df9e239b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37275">issues.joomla.org/tracker/joomla-cms/37275</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
