### PR TITLE
Capital Case for select list options for consistency

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to just update two strings to be capital case for consistency
### Before

aecw 1
### After

twe9

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 96f2efa93f75d73c733e375c22a1d4d0b31dcd3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12008">issues.joomla.org/joomla-cms/12008</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 96f2efa93f75d73c733e375c22a1d4d0b31dcd3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12008">issues.joomla.org/joomla-cms/12008</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12008">issues.joomla.org/joomla-cms/12008</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
