### PR TITLE
[4.0] Simplify error messages

### PR DESCRIPTION
**Pull request by brianteeman**
No need for a user to see technical terms when something goes wrong if the message is good enough without

PR for #32263

To test. Follow replication instructions in #32663

image

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 26e64f4aa036b4d40843ed12ae9701c75eccd63e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32268">issues.joomla.org/tracker/joomla-cms/32268</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 26e64f4aa036b4d40843ed12ae9701c75eccd63e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32268">issues.joomla.org/tracker/joomla-cms/32268</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32268">issues.joomla.org/tracker/joomla-cms/32268</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
