### PR TITLE
[3] Change text when com_joomlaupdate update available

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35353

### Summary of Changes

Better, more positive, guiding language for when the Joomla Update Component needs to be upgraded before Joomla can be upgraded

### CODE REVIEW

**Comment by richard67** [comment]
Without this PR:



With this PR:



Indeed less scary than the ".. not available" which really reads as if something was broken.

It's worth a thought if the alert class could be changed from error to something less scary with another pull request.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 628bef6bd86013dfff2558db933e0fd67c27cd00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35373">issues.joomla.org/tracker/joomla-cms/35373</a>.</sub>

**Comment by richard67** [comment]
P.S.: It needs to manipulate versions of the CMS and the Joomla Update component in manifest and manifest cache in database to get the scenario. The CMS version should be patched to 3.6.something and the version of the update component to 3.6.0.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 628bef6bd86013dfff2558db933e0fd67c27cd00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35373">issues.joomla.org/tracker/joomla-cms/35373</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35373">issues.joomla.org/tracker/joomla-cms/35373</a>.</sub>

**Comment by zero-24** [comment]
Thanks merging.

**Pull request merged**
