### PR TITLE
[4.0] Remove string that was only used in the GMail plugin

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
This string was only used by the gmail plugin so this change simply removes it from the J4 codebase

### Testing Instructions
Check string isn't used in the codebase/Code review

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4050631f454651860585a884892d629b3deac3dd<br /><br />Code review: String only appears in language files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29500">issues.joomla.org/tracker/joomla-cms/29500</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4050631f454651860585a884892d629b3deac3dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29500">issues.joomla.org/tracker/joomla-cms/29500</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29500">issues.joomla.org/tracker/joomla-cms/29500</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 4050631f454651860585a884892d629b3deac3dd<br /><br />Confirmed it only appears in the language files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29500">issues.joomla.org/tracker/joomla-cms/29500</a>.</sub>

**Pull request merged**
