### PR TITLE
[4.0] Use namespaced classes in Finder plugins

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use namespaced classes instead of aliases.

### Testing Instructions

Install Sample Data or create some content.
Run Smart Search Indexer.
Check that content gets indexed.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ea6ae25a7605f5954dd933baca115a5287ac5621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27584">issues.joomla.org/tracker/joomla-cms/27584</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ea6ae25a7605f5954dd933baca115a5287ac5621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27584">issues.joomla.org/tracker/joomla-cms/27584</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27584">issues.joomla.org/tracker/joomla-cms/27584</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
