### PR TITLE
[4.0] 3.9.0 Part 8

### PR DESCRIPTION
**Pull request by wilsonge**
More 3.9 merges. Merge with merge commit etc etc

### CODE REVIEW

**Comment by wilsonge** [comment]
@zero-24 @SniperSister RIPS please

**Comment by zero-24** [comment]
rebooted drone: http://ci.joomla.org/joomla/joomla-cms/16596

**Comment by zero-24** [comment]
Drone is happy now cc @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
