### PR TITLE
[4.0] Create global name ascending string

### PR DESCRIPTION
**Pull request by brianteeman**
In #26797 I created a global string for "Name ascending" and "Name descending"

This PR uses that global string instead of duplicating the string in each component

### testing
This can be tested without #26797 its just that the sort option will be displayed as JGLOBAL_NAME_ASC instead of "Name ascending"

### CODE REVIEW

**Comment by Quy** [comment]
Also update:
System > Update > Extensions 
System > Update > Update Sites

**Comment by brianteeman** [comment]
@quy done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09370497c321dccec2e7a72a93b4f8ef1c958684<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26798">issues.joomla.org/tracker/joomla-cms/26798</a>.</sub>

**Comment by joeykrop** [comment]
I have tested this item :white_check_mark: successfully on 09370497c321dccec2e7a72a93b4f8ef1c958684<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26798">issues.joomla.org/tracker/joomla-cms/26798</a>.</sub>

**Comment by Quy** [comment]
RFC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26798">issues.joomla.org/tracker/joomla-cms/26798</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
