### PR TITLE
[5.2][RFC] Media manager reflected on loading the selected items(?)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Introduce a new url query parameter named `selected_items` that can take multiple item paths separated by comma (right now it accepts only one)
- Reflect the selected items (now it takes only one) on the initial loading

If you get it this is a missing part for some coherent UI behavior on the item selection (or items)

### Testing Instructions

- Apply the patch.
- Login to the admin area
- Check that these urls have preselected some image
`administrator/index.php?option=com_media&path=local-images:/&selected_items=local-images:/joomla_black.png`
`administrator/index.php?option=com_media&path=local-images:/&selected_items=local-images:/banners/osmbanner1.png`
`administrator/index.php?option=com_media&path=local-images:/&selected_items=local-images:/sampledata/parks/landscape/180px_ormiston_pound.jpg`

### Actual result BEFORE applying this Pull Request

Only one way selection (from media manager to the picker)

### Expected result AFTER applying this Pull Request

Two way selection (from media manager to the picker and through the url)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

@laoneo @fedik couple of things here:
- Keep the old customEvent till the end of 6.0 but introduce a new one that:

- - The event that media manager is dispatching should be `const ev = new Event(); ev.selectedItems = []`
- - The name of the event should be more in the format that other core events have (I'm guessing something like `ComMedia:selectedItems` or something like that @Fedik your input here?)
- - The `selectedItems` should ALWAYS be an array
- - if !array.lenght nothing selected
- - if array.lenght === 1 ONE item selected
- - if array.lenght > 1 multiple items selected

These changes will allow better integration with 3rd part extensions

### CODE REVIEW

**Comment by Fedik** [comment]
I not realy see use case for multiple select in core (at current point of time).
But probably nice to have.

Few notes for it:
- Maybe make parameter shorter, more generic: `files` (or `file`) or `items` or `selected` or anything similar. 
- The parameter can be multiple:

```javascript
const url = new URL('index.php?file=a&file=b', location.origin);
const files = url.searchParams.getAll('file');

// Safe for PHP $_GET
const url = new URL('index.php?file[]=a&file[]=b', location.origin);
const files = url.searchParams.getAll('file[]');
```
The comma also fine, just have to do extra spliting.

---

Abut the event. I think it should be `window.parent.postMessage()`. 
[We already have `joomla:content-select` messageType](https://manual.joomla.org/docs/5.0/general-concepts/javascript/modal-content-select/) (I wanted to change it while working on media select field, but there much much much more stuff need to change) :
```javascript
window.parent.postMessage({
  messageType: 'joomla:content-select', 
  contentType: 'com_contact.article',
  id: 1, 
  title: 'A title'
})
```


For multiple I thought about something like:
```javascript
window.parent.postMessage({
  messageType: 'joomla:content-select', 
  contentType: 'com_contact.article',
  items:[
    {    
     id: 1, 
     title: 'A title'
    }
  ]
})
```
Or maybe more safe, to have another message type  'joomla:content-select-multiple', not sure curently.
Had no chance to test.

I would skip this part for now, it is not used in core anywhere, it will be hard to test.

**Comment by dgrammatiko** [comment]
> I not realy see use case for multiple select in core (at current point of time).

@Fedik here's my take on the multiple select:
- any media picker right now is limited to just selecting 1 item. Assuming you want to build a module for an image slider then the user is **forced**, due to the limitation of the current API, to pick one image, then add another field (assuming using the repeatable field, but other implementations would fall into the same workflow) then click on the pick button, open the modal select the next image and repeat the flow for as many images are required for the slider. If the API allowed multiple items then it would be click on the picker -> open the modal -> select the images.
- Allowing multiple items is like orders of magnitude better UX than the current allowed API.

Will it be used by core?

Probably not immediately as it would require a new core field (and|or a custom field)

Anyways the API should not dictate/limit the use cases IMHO

About `The parameter can be multiple`, you're right, this was a quick mashup to showcase the idea, but agree to use any of the suggested implementations

> Abut the event. I think it should be window.parent.postMessage()

I totally forgot that we had this conversation a few years back and decided to go with `postMessage`. Noted so if this gets a consensus will do it like that.

@laoneo or anyone from the production team has any objections here?

**Comment by brianteeman** [comment]
When selecting multiple images how do you foresee the ability to add alt text descriptions for each image?

**Comment by dgrammatiko** [comment]
> When selecting multiple images how do you foresee the ability to add alt text descriptions for each image?

The same pattern that exists today for the single image could be done (ok with some obvious changes) to accommodate the case of multiple images. The whole alt/lazyloading/etc right now is a component that accepts a single image, could be adjusted for multiple images, nothing really awkward or especially hard to implement.

FWIW I'm not suggesting changing the current media field or the editor image/media picker, just allow the API to expose multiple selected items. For the field probably a new one should be introduced (questionable if this needs to be in the core), same goes for the editor button(?).

**Comment by Fedik** [comment]
> any media picker right now is limited to just selecting 1 item. Assuming you want to build a module for an image slider then the user is forced, due to the limitation of the current API, to pick one image

Not fully correct. You can select multiple already. 
It is our media field limited to only one (due to hacky approach), but if you want you can.

Here a quick pseudo code, how to:
```js
const myFiles = [];
document.addEventListener('onMediaFileSelected',  (e) => {
  const myFile = e.detail;
  if (myFile in myFiles) {
    //.. remove myFile from the list of selected myFiles
  } else {
   myFiles.push(myFile);
  }
});

// ... then can insert these files anywhere you need
```

**Comment by dgrammatiko** [comment]
> but if you want you can.

Sorry but that's too hacky for my taste. Workarounds are always possible but it's better to have a proper API...

**Comment by Fedik** [comment]
I just saying that it is already possible. 
It is diferent approach, not realy hacky.

With your changes instead of 1 file, you will send all selected on every "select" event. 
That is also fine.

**Comment by dgrammatiko** [comment]
@Fedik my point is that the media manager already has a store that keeps a reference of the selected items and it's easier to send a post message or an event when that value changes. Right now the media manager has multiple event dispatchers inside components and inside the store. So, one improvement would be to have the event dispatching from one place and have the value standardized to whatever is there (an array of items). This simplifies the MM and the picker would have minimal changes but the selected items would be the same on both sides (the picker could filter items, etc it's just an array)

**Comment by Fedik** [comment]
Yeah, I understood.

**Comment by dgrammatiko** [comment]
Too late for 5.2, maybe someone will be interested to bring this in 5.3 or 6.0

**Comment by micker** [comment]
What do you need to acheive this ? some tester ?

**Comment by rdeutz** [comment]
I think having the ability to select multiple files makes sense.

**Comment by dgrammatiko** [comment]
FWIW this foundation work (still RFC) will cover 2 missing parts:
- The 2 way selection (the url part having the selected files) will unlock the years confusing UX of the media selection on the editors (right now it's one way, users can only select images to be inserted in the editor but selecting an image on the editor and clicking the button will not reflect on the media manager)
- the ability to insert multiple files at once (as Brian noted more changes needed in the UI picker but doable and also it needs another attribute for the field, ie `multiple`)

**Comment by micker** [comment]
did you plan to re open ithis issue for testing ?

**Comment by dgrammatiko** [comment]
> did you plan to re open ithis issue for testing ?

@micker this was/is an RFC (request for comments) it's not ready for merging (the code is full of todos) and then there's more work for the media field and the editor button media...

Basically it's up to the maintainers to decide if they want these changes...

**Comment by micker** [comment]
it can be very cool for many case to add this feature in j6 not ?

**Comment by dgrammatiko** [comment]
@micker ask the 6.0 release leaders

**Pull request closed without merging**
