### PR TITLE
Typecast queries rather than use the magic PHP method

### PR DESCRIPTION
**Pull request by wilsonge**
Check banners, articles and users save correctly

### CODE REVIEW

**Comment by chrisdavenport** [comment]
I think you're actually type casting, not type hinting. ;-)
/end-pedant-mode

**Comment by wilsonge** [comment]
You are right :P I'm tired xD

**Comment by photodude** [comment]
Because these are controlled by `if ($includeSubcategories)` or is otherwise connected to authorized subcategories testing requires use of subcategories, not just saving. Can we get some revised testing instructions that will cover the changes?

**Comment by mbabker** [comment]
There's no reason for this not being merged already.  I'm hitting the button.

**Pull request merged**
