### PR TITLE
[4.0] Simplify PHP version number to remove vendor suffixes

### LINKED ISSUE #32721: Simplify PHP version reported
### Steps to reproduce the issue

Based on actual feedback today from "a normal user" of Joomla. 

install old PHP version and visit admin to see the PHP end of life warning, with a NORMAL EVERY DAY USER of Joomla eyes (not as a PHP developer or expert) 

### Expected result

 - We have detected that your server is using **PHP 7.2.34** which is obsolete 

### Actual result

Screenshot 2021-03-17 at 18 16 20

 - We have detected that your server is using **PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1** which is obsolete 

The `+ubuntu18.04.1+deb.sury.org+1` just confuses and makes no sense 

### System information (as much as possible)

PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 obviously :)

### PR DESCRIPTION
**Pull request by PhilETaylor**
Closes #32721

### Summary of Changes

Simplify `PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1` to `PHP 7.2.34`

### Testing Instructions

Install PHP 7.2 - visit admin console 

### Actual result BEFORE applying this Pull Request

Screenshot 2021-03-17 at 18 16 20

### Expected result AFTER applying this Pull Request

Screenshot 2021-03-17 at 18 28 37

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good to me. From a purely codestyle point of view and to make it easier to read shouldnt the variable ($PHP_VERSION) be lowercase and have a different name to the php internal name of PHP_VERSION ??

**Comment by PhilETaylor** [comment]
I debated that, lets try `$phpVersion` as `$version` is already used as well as `$versionData` ... dont want to confuse.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b33a816ce5f534a26c8f689a08553707874cd78d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32722">issues.joomla.org/tracker/joomla-cms/32722</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b33a816ce5f534a26c8f689a08553707874cd78d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32722">issues.joomla.org/tracker/joomla-cms/32722</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32722">issues.joomla.org/tracker/joomla-cms/32722</a>.</sub>

**Pull request merged**
