### PR TITLE
[4.2] Correct description for admin featured articles

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
When creating a custom admin menu for featured articles the description is incorrect

### Testing Instructions
Create an admin menu
Create a featured articles menu

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f47cf8667987e590a6b634f17a5615d7d319f55e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39629">issues.joomla.org/tracker/joomla-cms/39629</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f47cf8667987e590a6b634f17a5615d7d319f55e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39629">issues.joomla.org/tracker/joomla-cms/39629</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39629">issues.joomla.org/tracker/joomla-cms/39629</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for the correct description!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
