### PR TITLE
[5.2] Articles Module: Display not only titles by default

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The Articles module right now is set to only display titles by default and then hides all other options. This is confusing and this PR switches that behavior around. 

### Testing Instructions
Create a new Articles module instance.

### Actual result BEFORE applying this Pull Request
You only see the option "Show titles only" being set to "Yes". Rest is hidden.

### Expected result AFTER applying this Pull Request
Option "Show titles only" is set to "No" by default and all other options are displayed.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Update https://github.com/Hackwar/joomla-cms/blob/c5b50dacf4d0fa244ab14ed1d7bb8bb46d89a6cb/modules/mod_articles/tmpl/default.php#L36

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on c5b50dacf4d0fa244ab14ed1d7bb8bb46d89a6cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44202">issues.joomla.org/tracker/joomla-cms/44202</a>.</sub>

**Comment by richard67** [comment]
> Update https://github.com/Hackwar/joomla-cms/blob/c5b50dacf4d0fa244ab14ed1d7bb8bb46d89a6cb/modules/mod_articles/tmpl/default.php#L36

@Hackwar Quy is right, it needs to change the default value from 1 to 0 in that line.

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on c5b50dacf4d0fa244ab14ed1d7bb8bb46d89a6cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44202">issues.joomla.org/tracker/joomla-cms/44202</a>.</sub>

**Comment by Hackwar** [comment]
I changed the second parameter as well.

**Comment by richard67** [comment]
I've restored the previous human test results in the issue tracker as the commit which has invalidated the test count has no functional impact on the tests.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44202">issues.joomla.org/tracker/joomla-cms/44202</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
