### PR TITLE
[4.0] Fixed Language label: COM_USER_ to COM_USERS_ v2

### PR DESCRIPTION
**Pull request by pe7er**
This is **version 2** of PR https://github.com/joomla/joomla-cms/pull/24805
It was easier to re-do the PR then to resolve merge conflicts I got after I pulled the current 4.0-dev into my "fix-com-users-label" branch

This PR **fixes an in-consequence** in the **language strings** with the naming of **COM_USER**:

Some language labels had references to COM_USER (without the S).
There's no component called COM_USER; it's name is COM_USERS.

This PR replaces COM_USER_ with COM_USERS_ in the en-GB language files
and references in PHP + XML files.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cc4eef1ea972c776ab8327ea92342547300289e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24825">issues.joomla.org/tracker/joomla-cms/24825</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on cc4eef1ea972c776ab8327ea92342547300289e4<br /><br />On Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24825">issues.joomla.org/tracker/joomla-cms/24825</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
