### PR TITLE
[4.4] Fixing API authentication issue with Apache with PHP as cgi/fastCGI

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
On my local system the token API authentication is not working, since the authorization header is renamed to REDIRECT_HTTP_AUTHORIZATION instead of just HTTP_AUTHORIZATION. Since our API is pretty similar to symfony, I looked at what symfony is doing and Symfony is doing the same like I'm doing here: https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/HttpFoundation/ServerBag.php#L58
Their original issue is here: https://github.com/symfony/symfony/issues/1813

@SniperSister can you review this/give this a thumbs up?

### Testing Instructions
I don't know how Apache needs to be actually configured to trigger this, but I hope this can be accepted by code review?

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by SniperSister** [comment]
Fine for me :)

**Comment by richard67** [comment]
@Hackwar Why for 5.0-dev? Either it's a bug fix, then it should go into 4.4-dev, or it's a new feature, then it should go into 5.1-dev. 5.0-dev only makes sense for bug fixes of bugs which affect only 5.x but not 4.4.y.

**Comment by Hackwar** [comment]
I changed it to 4.4-dev

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
