### PR TITLE
[4.1] finder show_search_form

### PR DESCRIPTION
**Pull request by brianteeman**
This if statement (which defaults to true) is pointless as the actual param it is checking does not exist so it can only ever be true

Code Review only to confirm that the param doesn't exist

Pull Request for Issue #35692

### CODE REVIEW

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 015b9ce2bde9f7c7eb11c29977b625a7ad6dc4c6<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35967">issues.joomla.org/tracker/joomla-cms/35967</a>.</sub>

**Comment by sakiss** [comment]
Brian i don't find the approach very neat. 
For example in my case i use that param to hide the search form in my results, since i am only using the search module. A param can be useful independently to it's GUI representation.

**Comment by brianteeman** [comment]
The param is never defined anywhere!

**Comment by sakiss** [comment]
I think it is much better to define it to the menu item and/or the com_finder's parameters.

It is really useful in case both the search module and the search form are being loaded. In that case you will get double search forms.

**Comment by brianteeman** [comment]
How can it be used today?

**Comment by sakiss** [comment]
> How can it be used today?

Not sure that i understand the question.
Please try the following:
Visit a site that uses a search mod at the top (as usual) and search for something.
You will now get 2 search forms (1 from the module and 1 from the results).

I can try to create a PR implementing that param.
In my last attempt i was getting a js error when the search form was not loaded and may need some help there.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 015b9ce2bde9f7c7eb11c29977b625a7ad6dc4c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35967">issues.joomla.org/tracker/joomla-cms/35967</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35967">issues.joomla.org/tracker/joomla-cms/35967</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35967">issues.joomla.org/tracker/joomla-cms/35967</a>.</sub>

**Comment by sakiss** [comment]
Please do not to merge that.
It is really useful, especially if the search module is used as well.
I am planning to create a PR that allows to hide the search form utilizing that param.

**Comment by RickR2H** [comment]
@brianteeman Is it okay with you to remove the RTC and let @sakiss do a PR with the params implementation?

**Comment by brianteeman** [comment]
its been 7 weeks since they said they were going to create a new pr after failing.

that would have to be for 4.1 as it would be a new feature.

this is fixing a bug in 4.0 and it doesnt prevent the new feature being added at a later date if that ever arrives.

**Comment by brianteeman** [comment]
Please dont forget merging this

**Comment by brianteeman** [comment]
Rebased to 4.1

**Comment by bembelimen** [comment]
@brianteeman could you please check #37254 ? Thanks

**Comment by brianteeman** [comment]
I have checked it and as I expected it is useless. Probably why the promised pr was not delivered in 3 months

**Comment by sakiss** [comment]
@brianteeman where did you see a promise for PR?

**Comment by brianteeman** [comment]
> Please do not to merge that. It is really useful, especially if the search module is used as well. I am planning to create a PR that allows to hide the search form utilizing that param.

**Comment by bembelimen** [comment]
Fair enough, thx

**Comment by brianteeman** [comment]
Thanks

**Comment by sakiss** [comment]
@brianteeman Well this is far from a promise.

The only reason i did not go on, was because i needed some assertion that this PR was not going to get merged and i will not waste my time for nothing.

Anyway if @bembelimen thinks that this should be fixed through the settings, my offer is still valid, but i may need some help in some parts.

**Comment by bembelimen** [comment]
Feel free to make a PR, if you cover all cases I'm happy.

**Pull request merged**
