### PR TITLE
[4] [mod_tags_similar] Transferring the class from DIV to UL

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
In the mod_tags_similar module, the list of items is displayed as a list in fact, although in other modules it is "hidden".

To reproduce the problem, just install the demo data, then go to the frontend -> Help menu -> About the main page. Below you will see 3 modules, 1 of which with a list of elements.

PR transfers classes from DIV to UL + adds a mod-list class. 

**BEFORE / AFTER patch**

Screenshot_4

### CODE REVIEW

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 6c8d3952ae0748fb3a47c140d1dfb4430ab7951d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33385">issues.joomla.org/tracker/joomla-cms/33385</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6c8d3952ae0748fb3a47c140d1dfb4430ab7951d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33385">issues.joomla.org/tracker/joomla-cms/33385</a>.</sub>

**Comment by drmenzelit** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33385">issues.joomla.org/tracker/joomla-cms/33385</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by dips1400** [comment]
I have tested this item :white_check_mark: successfully on 6c8d3952ae0748fb3a47c140d1dfb4430ab7951d<br /><br />I have tested this item successfully .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33385">issues.joomla.org/tracker/joomla-cms/33385</a>.</sub>

**Comment by drmenzelit** [comment]
@dips1400 thank you for testing, but this PR is already merged. You should check if a PR is still open before testing.

**Pull request merged**
