### PR TITLE
Search Tools (from JLayouts) implemented in com_checkin

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

In move to normalize the search/filter/order/limit bar (aka `searchtools`) in all administrator list views, and as other PR's have made for other list component/views, this PR adds JLayouts `searchtools` to com_checkin only view (checkin) and replacing the old HTML code.

Also:
- Some HTML code corrected (table blocks order)
- Resolves bug in pagination when set to "All" (none appeared)
- Other minor improvements
###### Before patch

com_checkin_isis_before
###### After patch

com_checkin_isis_after
###### Before & after patch (no change)

com_checkin_hathor_after
#### How to test
1. Edit some content and don't save or close so they are in not checked status
2. Go to com_checkin ("System" -> "Global check-in").
3. Apply the patch
4. Go again to com_checkin ("System" -> "Global check-in").
5. Test the Search Tools (Search field, ordering and limit).
6. View hathor template too.
#### Observations

Suggestions and code revisions are welcome.
#### Tags

administrator, checkin, search tools, jlayouts, list views, normalization

### CODE REVIEW

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on aabe76b98eca4e40600a222f3ceedee5c648dba5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8854">issues.joomla.org/joomla-cms/8854</a>.</sub>

**Comment by dgt41** [comment]
@andrepereiradasilva can you fix the conflicts here?

**Comment by andrepereiradasilva** [comment]
Done

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 68417aaba17d6323d38d386d35b0b93880e6c271<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8854">issues.joomla.org/joomla-cms/8854</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8854">issues.joomla.org/joomla-cms/8854</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request closed without merging**
