### PR TITLE
[4.0] Curly brackets instead of square brackets in plg_system_updatenotification.ini

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
A small change in parentheses that was recently [ported from Joomla 3](https://github.com/joomla/joomla-cms/commit/49495ca73a412f880901d911821ea33a197858be#diff-9736b22c9a7deca42108fdb005582a05e90da709fa03c58965e609775b8b779d).

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 12286112edc8a3a7a6766fa1320f9e72337c1f86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36350">issues.joomla.org/tracker/joomla-cms/36350</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 12286112edc8a3a7a6766fa1320f9e72337c1f86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36350">issues.joomla.org/tracker/joomla-cms/36350</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36350">issues.joomla.org/tracker/joomla-cms/36350</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
