### PR TITLE
File Name strings

### PR DESCRIPTION
**Pull request by brianteeman**
The en-GB styleguide says that it must be two words. Some recent pr let filename slip through

code review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on f03f186f9065fa19c10e063423afee009cccbaca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38732">issues.joomla.org/tracker/joomla-cms/38732</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on f03f186f9065fa19c10e063423afee009cccbaca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38732">issues.joomla.org/tracker/joomla-cms/38732</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38732">issues.joomla.org/tracker/joomla-cms/38732</a>.</sub>

**Comment by fancyFranci** [comment]
Very attentive, thank you!

**Pull request merged**
