### PR TITLE
Fix issues with language SEF v2

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
The same as https://github.com/joomla/joomla-cms/pull/23264 but in a different way.

**This globally removes traling slash from URL in order to support NGiNX correctly**

### Testing Instructions
See https://github.com/joomla/joomla-cms/pull/23264

### Expected result
No trailing slash in URL and remove default language SEF if it is not required.

### CODE REVIEW

**Comment by infograf768** [comment]
Alternate is OK, but not the module links in Source.

**Comment by SharkyKZ** [comment]
This could break some 3rd party components. The use of trailing slash is perfectly valid.

**Comment by csthomas** [comment]
Probably because of that will be closed.

**Comment by csthomas** [comment]
Due to a problem with B/C I close it.

**Pull request closed without merging**
