### PR TITLE
Update hathor to use rss feed for postinstall view

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### On #5222 we totally forgot Hathor

This just updates the hathor override to be in line with isis
Also this is the proper solution here for #5477

The actual rendering on the url: `/administrator/index.php?option=com_postinstall&eid=700` should be:

screen shot 2015-01-13 at 9 18 43
### Testing:

Just ensure that there are no side effects in this url: `/administrator/index.php?option=com_postinstall&eid=700`

### CODE REVIEW

**Comment by J0WI** [comment]
We should use httpS://www.joomla.org/announcements/release-news.feed?type=rss here

**Comment by dgt41** [comment]
@J0WI As I don’t have a secure server ready for testing this can you confirm that changing to `https` is a fully functioning option? I remember @mbabker said that joomla is not ready, yet, for that

**Comment by mbabker** [comment]
The RSS feed will work fine with HTTPS.  It's the `joomla.org` sites themselves that need some review before forcing every published link to always use the protocol, not the CMS application itself.

**Comment by dgt41** [comment]
Latest commit should bring sanity in hathor + isis

**Comment by brianteeman** [comment]
@test seems ok to me - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5712">issues.joomla.org/joomla-cms/5712</a>.</sub>

**Comment by richard67** [comment]
@test Success, Hathor shows RSS feed instead of iframe after patch, and release news feed looks ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5712">issues.joomla.org/joomla-cms/5712</a>.</sub>

**Comment by brianteeman** [comment]
Setting to RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5712">issues.joomla.org/joomla-cms/5712</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks

**Pull request merged**
