### PR TITLE
[4.0] Fixes cases of switchers double label

### PR DESCRIPTION
**Pull request by wilsonge**
Related to #26206 

### Summary of Changes
Removes some code added in #21227 which is now unused (the `skipLabelFor` attribute) as we now just outright don't render the label. Remove the check for the switcher class and instead add a class level flag to hide the label. It comes with clear documentation about the risks of using the flag.

This is the structural fix to the issue in the other PR. Once this is merged THEN we should merge #26206 to remove the useless labels

### Testing Instructions
Go to the Tags component options and find the direction field.

### Before Patch
image

### After Patch
image

### Documentation Changes Required
None

### CODE REVIEW

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 930302e04ccd4a37426ba32854e1fe36404a32ac<br /><br />- Go to Tags Options
- Before Patch: label + legend tags are displayed
- After Patch applied: only legend tag is dislayed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by SharkyKZ** [comment]
Doesn't solve the issue because since #25085 the label is always rendered for screen readers (`hiddenLabel` attribute only adds `sr-only` class). The simplest fix would be to change string comparison to a `strpos()` check here https://github.com/joomla/joomla-cms/pull/26423/files#diff-1a31ec6292bd41ba0bafe545bf8c1262L952 (and move it to `RadioField` class).

But, IMO, we should stop using `class` attribute to set layout and use `layout` attribute instead. There's PR #26214 for that.

**Comment by wilsonge** [comment]
@SharkyKZ understood. But just for my own head - this isn’t any different to how the code functions now right?

**Comment by SharkyKZ** [comment]
Sorry, I don't understand the question.

**Comment by opn365** [comment]
I have tested this item :red_circle: unsuccessfully on 930302e04ccd4a37426ba32854e1fe36404a32ac<br /><br />error applying patch
Patch could not be applied due to exception with layouts/joomla/form/renderlabel.php. Joomla\Filesystem\File::move: Rename failed.

using a pbf instance

Setting	Value
PHP Built On	Linux joomlapbf.directrouter.com 2.6.32-754.3.5.el6.x86_64 #1 SMP Tue Aug 14 20:46:41 UTC 2018 x86_64
Database Type	mysql
Database Version	10.2.27-MariaDB
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.2.23
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by opn365** [comment]
I have tested this item :white_check_mark: successfully on 930302e04ccd4a37426ba32854e1fe36404a32ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by Chessy65** [comment]
| [4.0] Fixes cases of switchers double label 					 				Applied Commit SHA: 930302e04c
I have tested this item successfully

**Comment by oschuldt** [comment]
I have tested this item :white_check_mark: successfully on 930302e04ccd4a37426ba32854e1fe36404a32ac<br /><br />works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by karo3** [comment]
I have tested this item :white_check_mark: successfully on b8c41b66e8a39ef808643972c61f50a691ccec8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on b8c41b66e8a39ef808643972c61f50a691ccec8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26423">issues.joomla.org/tracker/joomla-cms/26423</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Please now merge #26206

**Pull request merged**
