### PR TITLE
Language filter alternate meta tags default value should be 1

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Language filter alternate meta tags parameter default is 1 so make it 1 as default also in the code.
### Testing Instructions

Code review.
See also https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.xml#L57
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by infograf768** [comment]
@andrepereiradasilva 
Associations or not, the alternate should display when we are on the home pages.
Example
```html
<link href="http://localhost:8888/gsocmulti/it/" rel="alternate" hreflang="it-IT" />
	<link href="http://localhost:8888/gsocmulti/fr/" rel="alternate" hreflang="fr-FR" />
	<link href="http://localhost:8888/gsocmulti/" rel="alternate" hreflang="en-GB" />
```

**Comment by infograf768** [comment]
This means imho we should change the showon as alternate meta tags and x-default fields should display even when no associations.

**Comment by andrepereiradasilva** [comment]
> Associations or not, the alternate should display when we are on the home pages.

Ok. removed that part from the code. now just sets the default as innitially

> This means imho we should change the showon as alternate meta tags and x-default fields should display even when no associations. It also means a lang change for the string PLG_SYSTEM_LANGUAGEFILTER_FIELD_ALTERNATE_META_DESC

please make a PR for that.

please test

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 06e4a542ffc584ce01a8a47ce4f54cedeaf1980e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11642">issues.joomla.org/joomla-cms/11642</a>.</sub>

**Comment by infograf768** [comment]
will make pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11642">issues.joomla.org/joomla-cms/11642</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 06e4a542ffc584ce01a8a47ce4f54cedeaf1980e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11642">issues.joomla.org/joomla-cms/11642</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11642">issues.joomla.org/joomla-cms/11642</a>.</sub>

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/issues/11663<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11642">issues.joomla.org/joomla-cms/11642</a>.</sub>

**Pull request merged**
