### PR TITLE
Fix metismenu caret wrapping (v2)

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue # .
My previous PR #34608 got reverted due to missing styling #34750. In this version the underline is fixed.
For testing instruction and information, see my previous PR #34608.

Make sure all active menu items have an underline.
sub-level-underline

If the menu is in the header position make sure the Collapsible Dropdown layout is selected in the module -> Advanced tab.
metismenu

### Documentation Changes Required

### CODE REVIEW

**Comment by RickR2H** [comment]
@drmenzelit @richard67 @ricardo1709 @MSnoeren
Obviously this is still a bug that has to be fixed. Please review and test.

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 41b77b6c1663b09592b93a4004e6a62f97811a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35047">issues.joomla.org/tracker/joomla-cms/35047</a>.</sub>

**Comment by MSnoeren** [comment]
I have tested this item :white_check_mark: successfully on 41b77b6c1663b09592b93a4004e6a62f97811a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35047">issues.joomla.org/tracker/joomla-cms/35047</a>.</sub>

**Comment by drmenzelit** [comment]
If I use a metismenu on the sidebar, the menu item with the very long title doesn't break:
image

Without this PR:
image

**Comment by RickR2H** [comment]
@drmenzelit Made some small changes. Could you please test again? The wrapping will always be a problem, also with the current menu. If words are too long the menu wrapper will be pushed outside of the right and left position.

**Comment by RickR2H** [comment]
Closed as having more then 3 levels deep is bad UX/UI practice!

**Pull request closed without merging**
