### PR TITLE
[4.0] Update lib_joomla.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Even if the physical folder with the Joomla installation is meant here, Joomla should be written in capital letters. Right?

> "Joomla!" should ALWAYS be capitalised.
Our project's name is a proper name. Please always capitalise the "J" of Joomla.

source: https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7004ad9cd5bc82f50c0a82090c6edeec2f07cd58<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30867">issues.joomla.org/tracker/joomla-cms/30867</a>.</sub>

**Comment by infograf768** [comment]
Please also modify the site file. Both files should be equal.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 178c8446f3c30add252298d600f4ec2e1ada146a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30867">issues.joomla.org/tracker/joomla-cms/30867</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 178c8446f3c30add252298d600f4ec2e1ada146a<br /><br />I did a case sensitive search of the code ini files for ' joomla ' and confirm the count went down from 3 to 1. The stray is the fr_FR file - not relevant just yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30867">issues.joomla.org/tracker/joomla-cms/30867</a>.</sub>

**Pull request merged**
