### PR TITLE
[5.2] Enhance translation "Empty trash"

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #41106 .
Replacement of #41116. 

### Summary of Changes
Replace the text "Empty trash" as proposed in #41106.

### Testing Instructions
Check a trash can before and after patch 

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Is `Permanently` necessary? See under `Users`, `Media`, `Smart Search` where the button is `Delete` only?

**Comment by chmst** [comment]
TBH - I have no meaning here, only want to get rid of the "empty trash". 
Agree that we say only "delete" in other cases. Would bee nice to get a few opinions.

**Comment by chmst** [comment]
Speaking for me: 
When I empty a bin, I empty it completely, I don't pick out single items. This is why I would prefer the word "delete". 
This is a UX thing, maybe @crystalenka s team can help.

**Comment by Quy** [comment]
Delete implies permanent so need to mention it. See menu options when deleting a file in the recycle bin.

41119-delete

**Comment by chmst** [comment]
Interesting feature :) Changeing the language string to delet is easy, of course.
But it is not the best solution. Because in users or menus we have the "delete" in the action dropdown. 

If we are following the windows behaviour we must have: 
The "empty trash" button which then really deletes the whole trash (after message "do you really want..." )
**and** a delete button in the action drop down menu.

This is a big action, as all our backend views are concerned.

**Comment by brianteeman** [comment]
> This is a big action, as all our backend views are concerned.

Which is why its never been done before. it is also a potentially big b/c break for 3pd

**Comment by HLeithner** [comment]
For me the problem is not the text, instead the way to get there, 7 clicks to delete an item is the problem not if it's called "empty trash" or "delete" or "burn it down the house".

**Comment by brianteeman** [comment]
suggestions

remove the requirement to select an item before the empty trash button is active. if nothing is selected then everything is deleted. if something is selected then just delete the selected items

remove the "are you sure" confirmation. going from published to trashed should be enough of an opportunity to change your mind without being asked again

**Comment by HLeithner** [comment]
Additional to brians suggestions: 
Add a button to go directly to the trash filter and allow "shift" + "trash button" to directly delete items (like any system allows this) and change the text if shift button is hold down.

**Comment by chmst** [comment]
@HLeithner fully agree.
I would like a quick icon "thrash" in the dashboard which allows managing all trash in one step - like global checkin. 
This would be self explaining also for newbies.

But not in scope here :)

**Comment by brianteeman** [comment]
> I would like a quick icon "thrash" in the dashboard which allows managing all trash in one step - like global checkin.

I tried to write that some time ago but my code was not good.

> Additional to brians suggestions:
Add a button to go directly to the trash filter and allow "shift" + "trash button" to directly delete items (like any system allows this) and change the text if shift button is hold down.

if that is possible then great - not something I have seen in a web ui before

**Comment by chmst** [comment]
> allow "shift" + "trash button" to directly delete items (like any system allows this) and change the text if shift button is hold down.

This is a developer solution but I am advocate of  normal  users, I doubt if this is self-explaining and a11y ?

**Comment by HLeithner** [comment]
> if that is possible then great - not something I have seen in a web ui before

it's basically the same as the joomla shortcuts, something like this:

```javascript
document.querySelector('body').addEventListener("keydown", (e) => {      
  if (e.key === "Shift") {
    result.innerText = "Shift Key Pressed";
  }
});

document.querySelector('body').addEventListener("keyup", (e) => {      
  if (e.key === "Shift") {
    result.innerText = "Shift Key Not Pressed";
  }
});
```

**Comment by HLeithner** [comment]
> > allow "shift" + "trash button" to directly delete items (like any system allows this) and change the text if shift button is hold down.
> 
> This is a developer solution but I am advocate of normal users, I doubt if this is self-explaining and a11y ?

you can explain it in a guided tour, but it's also only an additonal way

**Comment by brianteeman** [comment]
Removing the "are you sure" is a simple one line change in each component for example delete this line https://github.com/joomla/joomla-cms/blob/c944137dc9c6461290d4631f2b3242dc107dab93/administrator/components/com_content/src/View/Articles/HtmlView.php#L231

Making the button deleteAll without having selected anything is a bigger change as that is in the library

**Comment by coolcat-creations** [comment]
I love this PR, It confuses so much of my customers that its called Empty trash but does not do it

**Comment by HLeithner** [comment]
Changing the meaning of a language string is a b/c break and not allowed at all per policy if we like to use "Delete" as string instead of "Empty Trash" then we need a new language string and use this one. Also "Delete Permanently" is redundant language as mentioned by @Quy

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by brianteeman** [comment]
This should not be RTC

1. @HLeithner points out that changing the meaning of a language stribg is a b/c break
2. @quy points out that "permanently" is a redundant word. You can'd delete something unpermanently

**Comment by richard67** [comment]
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by HLeithner** [comment]
Yes please create a new translation string, and make it simple, maybe use "Nuke" ;-)

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by tecpromotion** [comment]
> Yes please create a new translation string, and make it simple, maybe use "Nuke" ;-)

@chmst is that still up to date? Any plans for 5.1?

**Comment by Quy** [comment]
Maybe do it like `Clear Cache`.  Add `Delete` and either keep `Empty Trash` or change to `Delete All`.

**Comment by crimle** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by dorisdreher** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by richard67** [comment]
There are still updates requested, see https://github.com/joomla/joomla-cms/pull/41119#issuecomment-1817641281 .

**Comment by ChrisHoefliger** [comment]
I have tested this item :white_check_mark: successfully on 500df900a1cd4d00fe3bd3c2abd5dbc4f304ea20<br /><br />I have tested this successfully, the new text seems more plausible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41119">issues.joomla.org/tracker/joomla-cms/41119</a>.</sub>

**Comment by brianteeman** [comment]
6.1.6 Language keys
Changing or deleting a language key is considered a backwards compatibility break. Adding new ones is not. Substantially changing the meaning associated with a language key is a compatibility break. Rephrasing something for a more accurate description or proper en-GB grammar is not.

**Comment by richard67** [comment]
@brianteeman I am not really sure how to categorize, if it’s substantially changing the meaning or if it’s just rephrasing for better understanding.

**Comment by brianteeman** [comment]
@crimle you completely missed the fact that every time you press the "empty trash" button you are asked to confirm that you want to permanently delete the items. Therefor if the wording is changed to delete permanently the word permanently is a redundant superflous word and not needed.

image

**Comment by HLeithner** [comment]
I set this pr on the next maintainer meeting and requested a change from "Empty Trash" (JTOOLBAR_EMPTY_TRASH) to "Delete" (JTOOLBAR_DELETE), so hopefully we have a decision next week...

**Comment by crimle** [comment]
I agree with «Delete». It is simple and very good as well. Together with the following confirmation request, it is quite clear what's going on. By the way, the confirmation text looks a bit clumsy to me:
«Are you sure you want to delete? Confirming will permanently delete the selected item(s)!»
What about 
«Do you want to permanently delete the selected item(s)?»
It's shorter and consists of one sentence only.

**Comment by chmst** [comment]
Sorry for delay, I have changed the button  to Delete. 
This is a minmum consent and schould not be a b/c break and can go into 5.2

For a few good suggestions I will make new issues / PRs as they are not in scope or need much more coding. 
- Shorter text for the delete - confirmation
- Improve usability of our trash management

**Comment by chmst** [comment]
> @Hleithner points out that changing the meaning of a language stribg is a b/c break

I don't agree that this changes the meaning of the language string. In my opinion it is a bug fix in usability. But I am ok with moving this to 6.0.

**Comment by brianteeman** [comment]
+100 @HLeithner 

While it might be "safe to change" in core this is a global language string and we have no way of knowing how it is used in 3pd extensions where it may even be used without listCheck(true);

**Comment by chmst** [comment]
>I think changing the text is wrong or at least unexpected for others, using the JTOOLBAR_DELETE language tag in the relevant function should work better

ok

**Pull request closed without merging**
