### PR TITLE
Tinymce code icon in simple view

### PR DESCRIPTION
**Pull request by brianteeman**
### Testing Instructions

Switch tinymce into simple functionality
you will see the code editor AFTER the xtd-plugins

Switch tinymce into advanced functionality
you will see the code editor BEFORE the xtd-plugins with the link unlink icons

After the PR the icon will be before the xtd-plugins - see screenshots
#### Before

cmqv
#### After

09z 2

### CODE REVIEW

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on bfde487b270e8533174246af2d9d10ed7c0a2802<br /><br />The source code <> button does not have a label (text) next to its icon
so it should probably be before the XTD-buttons (more consistent ?)

also it does look better with this change
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11657">issues.joomla.org/joomla-cms/11657</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on bfde487b270e8533174246af2d9d10ed7c0a2802<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11657">issues.joomla.org/joomla-cms/11657</a>.</sub>

**Comment by dgt41** [comment]
RTC Thanks @brianteeman

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on bfde487b270e8533174246af2d9d10ed7c0a2802<br /><br />:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11657">issues.joomla.org/joomla-cms/11657</a>.</sub>

**Pull request merged**
