### PR TITLE
Implementation of the new Exception-Handling

### PR DESCRIPTION
**Pull request by HRIT-Florian**
Implementation of the new Exception-Handling

### Summary of Changes
Removed unneeded unreachable statement 8b46567
Exception code must be second paramter ea18fe7
Implemented new exception handling (JError is deprecated) 523eab6
Implemented new exception handling (JError is deprecated). e66b103
Status Code for "not authorized" should be 403 Forbidden. e66b103

### Testing Instructions
Tested should be all backend components

A: Check for access
Change access level and try to access componentes.
Try to runn an error.

B: Check for errors 
Tested should be check for errors in view.html.php files of all backend components. 
Try to runn an error.

### Expected result
A: Error message should be thrown 
Exception Error 403 JERROR_ALERTNOAUTHOR

B: Error message should be thrown 
Exception Error 'Status Code' $error 

### Actual result
Implementation of the error handling still panding in some components, Exception-Handling works already fine in some components. Actual result is the same, but improved with Exception-Handling,
and not with Joomla Framework outdated deprecated JError.

Implementation of the new Exception-Handling

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e66b10398b34c0cfa4588240ded34af981334c19<br /><br />Successfully tested for the sysinfo view in com_admin. On inspection the other changes should be all right too. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15717">issues.joomla.org/tracker/joomla-cms/15717</a>.</sub>

**Comment by mbabker** [comment]
If we were in library level APIs I might say yes.  But as this is in components and is functionally similar, it's OK to me.  The only possible side effect is someone having a custom Exception handler registered would get more Exceptions passed through it than the current `JError` callback behavior.

**Comment by Didldu-Florian** [comment]
Exception-Handling has already proven itself in some places.

Such as. here: etc.. It´s nothing new.
[administrator/components/com_menus/views/item/view.html.php#L68](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/item/view.html.php#L68)
[administrator/components/com_languages/views/override/view.html.php#L6](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_languages/views/override/view.html.php#L61) 

I have become aware of this, because JED Extensions Checker did marks this already. Exception handling is the cleanest solution to my view on components level, much better than enque message suggestion. So, I also think how @mbabker

Hope it is okay, at this time @laoneo. And extension developers could slowly get used to the standard in her components.

**Comment by laoneo** [comment]
I absolutely understand your arguments. For me stuff like that belongs to a minor release and not a patch release. But I guess at the end of the day we will hurt nobody if it goes into staging.

**Comment by ADipti** [comment]
I have tested this item ✅ successfully on e66b103

**Comment by Quy** [comment]
RTC?

**Comment by franz-wohlkoenig** [comment]
@Quy needs one more Test.

**Comment by Quy** [comment]
There are 2 successful tests. See 2nd posting.

**Comment by franz-wohlkoenig** [comment]
If after a Test are Changes, it doesn't count. See at Bottom "JTracker/HumanTestResults".

**Comment by franz-wohlkoenig** [comment]
@chmst can you please retest?

**Comment by Quy** [comment]
There were no more changes after chmst tested.

**Comment by franz-wohlkoenig** [comment]
RTC.

**Pull request merged**
