### PR TITLE
[#34009] Render checkboxes and radio button fields with layout

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Tracker is here: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=34009&start=0

How to reproduce the problem and/or test the patch::
Using Isis or any other Bootstrap-based template, have a look at a form with a 'checkboxes' field. The spacing and positioning is just not right.
Successful Tests:
    Easy:
Summary
Checkboxes badly rendered with bootstrap
Details

The proper way to do checkboxes in Bootstrap is to wrap the input tag inside the label and give the label (not the input) the class 'checkbox'. When doing it this way, the label does not need a 'for' attribute and the input does not need an id. The label is automatically associated with an input that it wraps.

I suppose radio buttons should also be done this way.

### CODE REVIEW

**Comment by designbengel** [comment]
so is this patch already merged? becaue before apply the checkboxes are shown in /administrator/index.php?option=com_templates&view=style&layout=edit&id=7 like you described in the tracker...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4022">issues.joomla.org/joomla-cms/4022</a>.</sub>

**Comment by okonomiyaki3000** [comment]
@designbengel No, unbelievably, this has still not been merged. The checkboxes you are talking about (I guess on the assignment tab) are not rendered with JForm, they're done directly in the template file. The purpose of this patch is to make JForm's rendering work more flexibly. Anyway, thanks for reminding me about this PR. I've now rebased it and made a minor change to modernize it a little. It should merge without issue and is kind of an obvious improvement.

**Comment by roland-d** [comment]
I have tested this and it looks good. Here is how I tested it:
1. Find the file plugins/user/profile/profiles/profile.xml
2. Add the code

```xml
<field type="checkboxes" name="somefield" label="Select Some Stuff">
   <option value="a" checked="true">A</option
   <option value="b">B</option>
   <option value="c">C</option>
</field>
```

3. Go to Extensions -> Plugins
4. Find the user profile plugin and enable it
5. Go to the Users -> Manage
6. Edit a user
7. Go to the Profile tab and see the alignment of the checkboxes
8. Apply this PR
9. Refresh the page and see the alignment of the checkboxes again
10. The checkboxes are correctly aligned now

**Comment by zero-24** [comment]
Thanks to the test instructions @roland-d and for the fix @okonomiyaki3000! I have just tested it and it works good. --> RTC :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4022">issues.joomla.org/joomla-cms/4022</a>.</sub>

**Pull request merged**
