### PR TITLE
[4.2] add noopener noreferrer in plg_system_webauthn.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

add rel="noopener noreferrer" to external link

@brianteeman _I have replaced the ' with ", as it happens more often and there should not be two spellings, at least within an .ini file._

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

no rel

### Expected result AFTER applying this Pull Request

rel=

### Documentation Changes Required

.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4ac92425755a9e834394ef52f583ba4df220d9d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38271">issues.joomla.org/tracker/joomla-cms/38271</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4ac92425755a9e834394ef52f583ba4df220d9d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38271">issues.joomla.org/tracker/joomla-cms/38271</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38271">issues.joomla.org/tracker/joomla-cms/38271</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
