### PR TITLE
add rtl support for protostar to make the sub-menu aligned correctly

### PR DESCRIPTION
**Pull request by oc666**
Currently the protostar sub-menu on RTL is not aligned well. This PR fix it.
Before:
image
After:
image

### CODE REVIEW

**Comment by infograf768** [comment]
I suggest you rather add the classes to bootstrap-rtl.less where we already have some stuff for frontend.
Then run generatecss.php

This will not make necessary to add a rtl.css to Protostar and load it.

**Comment by infograf768** [comment]
Also Careful: the "initial" value may not work with IE.

**Comment by oc666** [comment]
I don't understand why require to add to bootstrap-rtl if this is specific issue for protostar.
Anyway, I changed the left initial to left auto.

**Comment by infograf768** [comment]
@oc666
Until today, even when I suggested it when Protostar was created, nobody wanted to create a specific rtl.less and subsequently a rtl.css for protostar. Thus the reason of my post. 

If PLT agrees to add now a rtl.css to protostar, I have no issue with it, but should also be created a rtl.less and generatecss.php should be modify to include this new setting, i.e. add

```
JPATH_SITE . '/templates/protostar/less/template_rtl.less' => JPATH_SITE . '/templates/protostar/css/template_rtl.css',
```
line 55 of https://github.com/joomla/joomla-cms/blob/staging/build/generatecss.php#L55

the new code shoudl be added in the new .less file and generatecss.php used.

**Comment by phproberto** [comment]
IMO the right way would be to add a class for the html or body tags when a RTL language is active. Then use it to define specific behaviors for rtl languages in a new rtl.less inside protostar. Then you only have to import it in template.less without needing to modify template index.php or generatecss.php.... And you save to have 2 css files loaded (2 requests).

**Comment by brianteeman** [comment]
@oc666 can you look at the suggestion from @phproberto so that we can get this important fix made in the core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6740">issues.joomla.org/joomla-cms/6740</a>.</sub>

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/7200 implementing @phproberto solution.

**Comment by brianteeman** [comment]
Closed in favour of #7200<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6740">issues.joomla.org/joomla-cms/6740</a>.</sub>

**Pull request closed without merging**
