### PR TITLE
Update SQL files

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Use `type_alias` instead of `type_title` in the query to prevent possible overwriting of 3rd party extensions.

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
What's the consensus on updating old SQL files? Because there are more instances of this.

**Comment by Quy** [comment]
Maybe you can find the answer in [22754](https://github.com/joomla/joomla-cms/issues/22754).

**Comment by SharkyKZ** [comment]
That's fine for copyright changes. But if existing code can potentially cause issues, it should be updated.

**Comment by brianteeman** [comment]
> What's the consensus on updating old SQL files? Because there are more instances of this.

What is the benefit of doing that? As long as the current sql is correct thats all that matters.

**Comment by SharkyKZ** [comment]
It's not. If you have a 3rd component with `Article` type title, this SQL is going to affect it as well. Although neither `type_alias` nor `type_title` column is unique in the database, we can assume that `type_alias` is used as such. I.e. you should not have multiple row with `com_content.article` alias in the table. But you can have `com_example.article` and `com_content.article`, as well as multiple entries with title `Article`.

**Comment by brianteeman** [comment]
My comment was about updating the old sql only

**Comment by SharkyKZ** [comment]
Old SQLs have the same potential issue.

**Comment by brianteeman** [comment]
But they will never be the sql used on a site. Or am I missing something.

**Comment by HLeithner** [comment]
if you update form < 3.9 you execute this sql file and it should be changed because it's wrong

**Comment by brianteeman** [comment]
As long as the last of the update sql files is correct thats all the matters. There is no point in going back through all the **existing** update sql and changing them. At least thats my understanding of the question about **OLD** sql files

**Comment by HLeithner** [comment]
if we have sql query that can break a website because our query is wrong it has to be changed.

And thats the problem here, we break websites having an extensions matching the query in the SQL. The reason for this is because the where clause doesn't match a unique core field instead it match a field used by any component.

**Comment by brianteeman** [comment]
I am obviously really stupid then as I still don't see the need to change an **OLD** update sql file.

Site is on Joomla 3.9.1 and updates
update-3.9.2.sql is applied (still with the error)
update-3.9.3.sql is applied (still with the error)
update-3.9.4.sql is applied (still with the error)
update-3.9.5.sql is applied (still with the error)
update-3.9.6.sql is applied (still with the error)
update-3.9.7.sql is applied (still with the error)
update-3.9.8.sql is applied (with the correction)

So why do you go back in time and apply the fix to update-3.9.4.sql etc

**Comment by HLeithner** [comment]
Site is on 3.8.0 then it get executed.

**Comment by SharkyKZ** [comment]
@brianteeman I'm not talking about every SQL file, only those that contain similar errors, for example:

https://github.com/joomla/joomla-cms/blob/4cb1bf0ef84ae8f1e9a7400515ba65ee5378c87e/administrator/components/com_admin/sql/updates/mysql/3.1.2.sql#L1

**Comment by brianteeman** [comment]
@SharkyKZ I stand by my comments. If that file with the incorrect sql is applied it will be later updated by the correct sql file.

**Comment by HLeithner** [comment]
@brianteeman I think you don't understand the problem. It's not possible to fix it after we broke it because we have a data loss after this sql statement.

**Comment by mbabker** [comment]
There is no way to create a new update file to "fix" any damage created by the pre-patch version of these files, the WHERE condition is too broad and potentially updates rows it wasn't intended to in the right conditions.  This patch adjusts those queries so they are more correctly limited to only the rows the original author actually intended to touch.  So it fixes a problem in that someone updating from 3.8 or earlier will not have an overly eager query applied which may introduce issues to their `#__content_types` tables, but there is not a way to introduce a new UPDATE query that reverses this one.

This is in part why data updates do not belong in an API that should ONLY be dealing with schema changes...

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 49efcaa77ad4ffcea2c792a54f50e7e91de50316<br /><br />This PR is correct, I agree with the explanation by @mbabker here: [https://github.com/joomla/joomla-cms/pull/22419#issuecomment-503071238](https://github.com/joomla/joomla-cms/pull/22419#issuecomment-503071238 "https://github.com/joomla/joomla-cms/pull/22419#issuecomment-503071238").<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22419">issues.joomla.org/tracker/joomla-cms/22419</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 49efcaa77ad4ffcea2c792a54f50e7e91de50316<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22419">issues.joomla.org/tracker/joomla-cms/22419</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22419">issues.joomla.org/tracker/joomla-cms/22419</a>.</sub>

**Comment by HLeithner** [comment]
Thanks finally.

**Pull request merged**
