### PR TITLE
[4.0] Correct namespace import

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR uses optimize import tool from phpstorm to correct namespace import:

- Remove un-used classes in use statement
- Sort import
- Correct class from `\Joomla\CMS\Session\Session;` to `Joomla\CMS\Session\Session;
`

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3bddccd564c76b44c79e7f24554556fb84900478<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34807">issues.joomla.org/tracker/joomla-cms/34807</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3bddccd564c76b44c79e7f24554556fb84900478<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34807">issues.joomla.org/tracker/joomla-cms/34807</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34807">issues.joomla.org/tracker/joomla-cms/34807</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
