### PR TITLE
[4.0] Simplify Switcher layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Some code simplification.

### Testing Instructions

Open any form containing a switcher field.
Inspect the switcher.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2d607135ab2ee1fdc6f1152d10c05d4ae192fe5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29370">issues.joomla.org/tracker/joomla-cms/29370</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2d607135ab2ee1fdc6f1152d10c05d4ae192fe5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29370">issues.joomla.org/tracker/joomla-cms/29370</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29370">issues.joomla.org/tracker/joomla-cms/29370</a>.</sub>

**Comment by brianteeman** [comment]
I am not sure about this

The simplification of the sanitization of the value seems wrong to me. If I read this correctly (I might not be) instead of the htmpspecialchars and utf8 checks it is being restricted to the basic string. Which i think would prevent utf8 characters etc.

**Comment by SharkyKZ** [comment]
@brianteeman It's still using `htmlspecialchars()` with `UTF-8` encoding:

https://github.com/joomla/joomla-cms/blob/5e137dbf254da94d605fe39ea0b68f0fe1f60f64/libraries/src/Layout/BaseLayout.php#L117-L120

**Comment by brianteeman** [comment]
Isnt that taking place after you have already reduced it to a string?

**Comment by SharkyKZ** [comment]
Actually it appears to already be a string so another cast isn't even necessary:

https://github.com/joomla/joomla-cms/blob/5a7ff7d653d607b727bdb12ba2f00565350079ce/libraries/src/Form/Field/ListField.php#L107

It makes no difference anyways.

**Comment by wilsonge** [comment]
`htmlspecialchars` will only work with a string - so it must already have been a string when escaped so pretty sure the string conversion is fine.

Moving to the escape function is probably good because it's using `ENT_QUOTES` rather than `ENT_COMPAT` which I guess might be usable for some sort of XSS attack if single quotes aren't encoded.

All in all having looked I think the proposed change there is fine. Although thankyou for flagging it when you were unsure!

**Pull request merged**
