### PR TITLE
[4.1] s/assigments/assignments

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b7d1ebcda8430406a13842dd4f8368edecce70ba<br /><br />I've checked that this PR covers all places with that error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36822">issues.joomla.org/tracker/joomla-cms/36822</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b7d1ebcda8430406a13842dd4f8368edecce70ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36822">issues.joomla.org/tracker/joomla-cms/36822</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36822">issues.joomla.org/tracker/joomla-cms/36822</a>.</sub>

**Comment by bembelimen** [comment]
Note to myself: have to check if this could probably break 3rd party extensions

**Comment by bembelimen** [comment]
After looking through the code, this would break extensions using this parameter the old way. So what we need is the old + the new case and a deprecation note for 5.0 for the old one.

**Comment by bembelimen** [comment]
Remove RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36822">issues.joomla.org/tracker/joomla-cms/36822</a>.</sub>

**Pull request closed without merging**
