### PR TITLE
New category count feature performance degrade #9420

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9420  .

> New category count feature performance degrade
#### Summary of Changes

Sliptted count queries
#### Testing Instructions

see #9420 .

### CODE REVIEW

**Comment by brianteeman** [comment]
confused - what is this pr supposed to do? Remove the category count feature

**Comment by brianteeman** [comment]
ignore me - i guess I tested too quickly - you are still working- sorry

**Comment by alikon** [comment]
sorry brian the connection goes down suddenly ....
can you test now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7c8dafeab7d536acd84aeff7383d707591cb0f5e<br /><br />With my data from #9420 

## before ##
Database queries total: 31358.46 ms

## after ##
Database queries total: 276.19 ms




WOW!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9421">issues.joomla.org/joomla-cms/9421</a>.</sub>

**Comment by alikon** [comment]
i'm sure we can do even better ;)

**Comment by Wertos** [comment]
# Before
Total SQL-queries: 21420.74 ms
# After
Total SQL-queries: 14.74 ms

Database: 1.4Gb
Materials: >82000
Categories: 46

**Comment by brianteeman** [comment]
@alikon can you look at the codestyle issues in Travis please and then this can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9421">issues.joomla.org/joomla-cms/9421</a>.</sub>

**Comment by brianteeman** [comment]
RTC now that travis is happy - awesome stuff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9421">issues.joomla.org/joomla-cms/9421</a>.</sub>

**Comment by wilsonge** [comment]
We need to do the same thing to all the other category helpers (e.g. banners https://github.com/alikon/joomla-cms/blob/patch-61/administrator/components/com_banners/helpers/banners.php#L197, newsfeeds etc.)

**Comment by infograf768** [comment]
+ let's not forget hathor.

**Comment by wilsonge** [comment]
We honestly should be doing this in view.html.php - so these variables are not set in the default.php

**Comment by roland-d** [comment]
@wilsonge Would be ideal in the view.html.php but then you can't override it anymore. Perhaps in a JLayout?

**Comment by wilsonge** [comment]
Why should you be able to override a database query?

**Comment by roland-d** [comment]
@wilsonge because that is what is causing the performance degredation or does the sql change already account for that?

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/9421#issuecomment-196371832

**Comment by roland-d** [comment]
In that case the code can remain in the model or not?

**Comment by wilsonge** [comment]
It could go in getItems in the model I think yes - not the getQuery where it currently resides tho

**Comment by roland-d** [comment]
It is in the getListQuery() but yes, perhaps getItems() is better.

**Comment by wilsonge** [comment]
I have written a PR that uses this but moves the code out of the com_content view and also does it across all the extensions with this feature. Closing in favour of #9429

**Pull request closed without merging**
