### PR TITLE
[#34008] w3c validation error input type file and value

### PR DESCRIPTION
**Pull request by zero-24**
Redo: https://github.com/joomla/joomla-cms/pull/4024
See: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=34008&start=0 and http://www.w3.org/TR/html-markup/input.file.html

### CODE REVIEW

**Comment by brianteeman** [comment]
Can you paste the content from joomlacode here - as it will be closing soon
the link will break - thanks

On 12 March 2015 at 13:26, zero-24 <notifications@github.com> wrote:

> Redo: #4024 <https://github.com/joomla/joomla-cms/pull/4024>
> See:
> http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=34008&start=0
> and http://www.w3.org/TR/html-markup/input.file.html
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/6403
> Commit Summary
>
>    - w3c validation error input type file and value
>
> File Changes
>
>    - *M* libraries/joomla/form/fields/file.php
>    <https://github.com/joomla/joomla-cms/pull/6403/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/6403.patch
>    - https://github.com/joomla/joomla-cms/pull/6403.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6403>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
### How to reproduce the problem and/or test the patch::
```
include an item in an xml form file that uses type="file" then generate the input tag using $form->getInput('fieldname'). The resultant <input> tag includes the 'value' attribute which is invalid for an input type of 'file' and causes an HTML compliance error.
```

### title

```
HTML compliance error for input tags with type='file'
```

### details
```
<input> tags with type='file' generated by JForm include a 'value' attribute which is invalid for this input type and causes an HTML compliance error.
I fixed the problem by removing the 'value=""' string from line 137 of libraries/joomla/form/fields/file.php
```

**Comment by n9iels** [comment]
@test: confirmed, the patch works and remove the value propety<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6403">issues.joomla.org/joomla-cms/6403</a>.</sub>

**Comment by compojoom** [comment]
@test: confirmed, the patch works and remove the value propety<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6403">issues.joomla.org/joomla-cms/6403</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6403">issues.joomla.org/joomla-cms/6403</a>.</sub>

**Pull request merged**
