### PR TITLE
[com_content] articles view (modal) - Implement searchtools

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR adds JLayout searchtools to com_content articles modal view.
Also adds the status column, moves the category to below the article title and makes some minor visual changes to be more synchronized with the non modal view.
###### Before PR

before-pr
###### After PR

after-pr
#### Testing Instructions
1. Use latest staging
2. In the backend edit any article and press "+Article" button on the editor, how will see a modal window with the old filter.  Note: you can also create a "Single article" menu item type and select the article there.
3. Apply this patch
4. Repeat 2. and you'll see the new searchtools
5. Now test search, ordering, filter, etc. Also select an article. In other words, test if everything works fine.

That i know of, correct me if i'm wrong, this view is used in:
1. "+Article" button in any editor (frontend and backend) -> all articles
2. Menu item "Single Article", "Select" button -> all articles
3. When language associations are enabled. Article "Associations" tab -> articles filtered by language

All this views should be tested.
#### Observations

That i know of, this is the first searchtools implemented on a modal view, so suggestions and improvements are welcomed.

### CODE REVIEW

**Comment by RonakParmar** [comment]
@andrepereiradasilva Thanks for the patch.
I have applied this path and works fine for me.
Here is my system information:

Joomla! Version: Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.4.45-3+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on b81e10392b6c1fb9b45cfe3dd81d93369ed6d000<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on b81e10392b6c1fb9b45cfe3dd81d93369ed6d000<br /><br />Multilingual sites: This PR breaks forcedLanguage when articles associations are set as one can choose another language than the language it should be associated to. In that case the Select Language should not be proposed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 could you describe the steps you made to test so i can try to resolve the uissue you're referring?

**Comment by infograf768** [comment]
Multilingual site:
Edit an article in one language, go to associations tab
"Select" an article for a specific language: the modal opens.
Remark that only the articles tagged to this specific language are displayed and one CANNOT change language to display articles not tagged to the said lang.

screen shot 2016-02-23 at 12 17 12

I click on the Select button for Italian:
screen shot 2016-02-23 at 12 18 40


The code to NOT display the language dropdown depends on the filter.forcedLanguage setting.

**Comment by andrepereiradasilva** [comment]
ok, i see will check that later. thanks

**Comment by infograf768** [comment]
Yep.

**Comment by andrepereiradasilva** [comment]
@infograf768 made some changes that i think resolved the issue you described.

The idea would be we could use this PR to replicate and, with the necessary adaptations, implement searchtools on other modal views.

So IMHO this should be tested with time and with all possible scenarios (functionality in all views where it's used, B/C, security, etc).

**Comment by infograf768** [comment]
This works great.

Comments:
I see no reason to take off filtering by Author or Tags.
Concerning levels, see https://github.com/joomla/joomla-cms/pull/9201

Is it also possible to reset the category field (i.e. in fact Clear) when Selecting an article for another language? Otherwise one has to clear each time when choosing an association for a different language.

Note: I had tested here another solution where searchtools filters were customised. But I had to specifically introduce the variable in filters.php
In fact, I think we should improve SearchTools by letting display or not specific fields, a bit similar to what is done for layout edit params.php
See https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/edit/params.php#L21-L23

**Comment by andrepereiradasilva** [comment]
> Comments: I see no reason to take off filtering by Author or Tags or MAx Levels.

ok, will show them.

> Is it also possible to reset the category field (i.e. in fact Clear) when Selecting an article for another language? Otherwise one has to clear each time when choosing an association for a different language.

ok. i see. if we use "+article" modal and them the language associations it populates the filter with previous selected filter. i think modal each forced language needs a exclusive state context.

> Note: I had tested here another solution where searchtools filters were customised. But I had to specifically introduce the variable in filters.php
> In fact, I think we should improve SearchTools by letting display or not specific fields, a bit similar to what is done for layout edit params.php
> See https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/edit/params.php#L21-L23

Yes, i also see some changes that searchtools could be simplified (ex: not adding layout overrides just because of the client selector) and also add some more flexibility, but that if for a future PR IMHO.

**Comment by andrepereiradasilva** [comment]
@infograf768 con you check now?

**Comment by infograf768** [comment]
This now works fine for me.
I would not touch at icomoon.less as you can see that protostar is never using coloured icons.
If you were, we would also have to change icon-cancel and possibly icon-save, etc.

**Comment by andrepereiradasilva** [comment]
ok sure.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 936494c9ed72e72a44fa77fc31eca7d844cd36e7<br /><br />This works fine

remains to do Contacts and Newsfeeds (It looks like this last one has issues with forcedlanguage)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by andrepereiradasilva** [comment]
contacts: https://github.com/joomla/joomla-cms/pull/9198

**Comment by infograf768** [comment]
As this series of patches contain the same change to the category field type, I suggest, before going further to get a milestone from maintainers.
@wilsonge  ?

**Comment by joomlacorner** [comment]
This works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by joomlacorner** [comment]
I have tested this item :white_check_mark: successfully on 936494c9ed72e72a44fa77fc31eca7d844cd36e7<br /><br />This works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9195">issues.joomla.org/joomla-cms/9195</a>.</sub>

**Pull request merged**
