### PR TITLE
[4.0] com_csp status filter

### PR DESCRIPTION
**Pull request by brianteeman**
It is not possible for a csp report to be archived. This PR removes the archive option from the filter state options

//cc @zero-24

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22890a864f0be2f36f2f041d149ec597d93b9ecb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26506">issues.joomla.org/tracker/joomla-cms/26506</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 22890a864f0be2f36f2f041d149ec597d93b9ecb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26506">issues.joomla.org/tracker/joomla-cms/26506</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26506">issues.joomla.org/tracker/joomla-cms/26506</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by zero-24** [comment]
LGTM thanks 👍

**Pull request merged**
