### PR TITLE
[4.0] Display Menu Title

### PR DESCRIPTION
**Pull request by brianteeman**
Sometimes you dont want to display the menu title - for example if you have an image instead.

The wording for this option is "Add Menu Title" (in the link type options)

I find this confusing as the default value is yes and it would be the expected behaviour etc for a menu title for it to be displayed.

This PR proposes changing the text to "Display Menu Title"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 505a6b6d1dd209d095da9e98328075216ef2250c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26632">issues.joomla.org/tracker/joomla-cms/26632</a>.</sub>

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 505a6b6d1dd209d095da9e98328075216ef2250c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26632">issues.joomla.org/tracker/joomla-cms/26632</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26632">issues.joomla.org/tracker/joomla-cms/26632</a>.</sub>

**Comment by HRIT-Florian** [comment]
I have tested this item :white_check_mark: successfully on 79cc1360cf126e5cf7b852c52c3854187c0288f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26632">issues.joomla.org/tracker/joomla-cms/26632</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks 👍

**Comment by brianteeman** [comment]
Thanks

**Comment by snehaM26** [comment]
I have tested this item :white_check_mark: successfully on 79cc1360cf126e5cf7b852c52c3854187c0288f9<br /><br />Test successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26632">issues.joomla.org/tracker/joomla-cms/26632</a>.</sub>

**Pull request merged**
