### PR TITLE
[4] Return value type is not compatible with declared type in doc

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Return value type is not compatible with declared type in doc

### Testing Instructions

Code review

### CODE REVIEW

**Comment by HLeithner** [comment]
void as return "value" doesn't exists and in case of php this is always NULL and that's actually expected in https://github.com/joomla/joomla-cms/blob/0587b4d98559e6a14213dffd424d40498cae5c36/modules/mod_syndicate/mod_syndicate.php#L19

maybe you can update the function that it return null please?

**Comment by PhilETaylor** [comment]
> void as return "value" doesn't exists

Disagree, and so does phpStorm, and so does https://docs.phpdoc.org/latest/references/phpdoc/types.html  ;-) 

PHP 7.1 https://www.php.net/manual/en/migration71.new-features.php 

>A void return type has been introduced. Functions declared with void as their return type must either omit their return statement altogether, or use an empty return statement. NULL is not a valid return value for a void function. 

However, you are right that this method could ALSO return null as well as void and string :-) 

if `$document->_links` was an empty array the method would return `void` as a return type

**Comment by HLeithner** [comment]
Sorry but that's makes it more confusing, that's more worse then having a wrong type.

And actually you can never use the void "type" as part of a union (https://wiki.php.net/rfc/union_types_v2) I know you you don't create a union type here but I think we should follow this rule here too.

I would suggest to add a `return null;` in line 46 and remove the void "type"

**Comment by PhilETaylor** [comment]
haha sorry if I made it more confusing - I don't make the rules I just link to them... and you are right about Union Types... I like your quick fix and will apply that... 

The joys of dealing with code from `* @since   1.5` hahah

**Comment by PhilETaylor** [comment]
Updated.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
