### PR TITLE
[4.1] Read More with Title

### PR DESCRIPTION
**Pull request by brianteeman**
Its a subtle change but a correct one as the "read more" is the primary and "title" the secondary function of the option

It also means that all three read more options are structured similarly grammatically

## Before
image

## After
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f0a0e8fe9c432a42f3130984cc8031e57d33cc09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37594">issues.joomla.org/tracker/joomla-cms/37594</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f0a0e8fe9c432a42f3130984cc8031e57d33cc09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37594">issues.joomla.org/tracker/joomla-cms/37594</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37594">issues.joomla.org/tracker/joomla-cms/37594</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
