### PR TITLE
Catch SQL exception in SQL form field

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #13867.

### Summary of Changes
The SQL form field should handle SQL errors and not crash the page. Actually it enqueus the error message to the application, don't know if there is a better way to handle exceptions in form fields. @mbabker and @Bakual any clue?

### Testing Instructions
- Create a SQL form field with an invalid query like "An invalid query". image
- Adit an article.

### Expected result
An error message should be shown on the top of the page.

### Actual result
The site crashes.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 394f474adef0abae04d99356bc8fe5eab06d7852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13882">issues.joomla.org/tracker/joomla-cms/13882</a>.</sub>

**Comment by Bakual** [comment]
I'd say your proposal looks perfect. Catching the exception and converting to a message is the right thing here since we don't want to throw a full error page just because a single field doesn't work.

**Review by zero-24 — CHANGES_REQUESTED** [review]
Please add a clean line before the try ;)

**Review by zero-24 — APPROVED** [review]

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on ea407b3d945fd1ceacdb6f7d7ec97dd549ce583f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13882">issues.joomla.org/tracker/joomla-cms/13882</a>.</sub>

**Comment by zero-24** [comment]
RTC #jc17de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13882">issues.joomla.org/tracker/joomla-cms/13882</a>.</sub>

**Comment by PhilETaylor** [comment]
This doesnt work - currently at 3.7b3

**Comment by mbabker** [comment]
It works just fine.  It just doesn't work the way you think it should.

**Comment by PhilETaylor** [comment]
Im sorry - but the leaking of mysql column names to front end users is **NOT acceptable to me.**

**Comment by mbabker** [comment]
Read my other rant.  You're saying this PR doesn't work.  I'm saying it does.  It is indeed catching exceptions.  But the handling of it is crap.

**Pull request merged**
