### PR TITLE
[#33966] Jhtmlbootstrap

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
A lot of improvements to this file.
- jQuery code should be executed in a ready function, not just a closure
- js strings should be properly encoded
- some restructuring to be nicer looking and more efficient
- use a layout for complex html rendering

Tracker is here: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33966&start=0

Not all tracker issues are addressed. One in particular is maybe not possible without breaking backwards compatibility.

### CODE REVIEW

**Comment by roland-d** [comment]
New link for the old tracker: http://developer.joomla.org/joomlacode-archive/issue-33966.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3922">issues.joomla.org/joomla-cms/3922</a>.</sub>

**Comment by dgt41** [comment]
@okonomiyaki3000 @roland-d the modal part needs some changes, as the code is already deprecated

**Comment by wnnz34** [comment]
Hello I tested the following Feartures:

modal - Used on admin pages which have a 'batch' button that brings up a modal dialog. Tested
 
popover - Used on the module type select page to pop up a message with more information about each module type. Tested

tooltip - Used on most list views such as the Category Manager and Article Manager. Displays the tooltip when mousing over the column names and certain column content. Tested

startTabset (and related functions) - Used on virtually every edit page. Tested

startAccordion (and related functions) - Used in the modal dialog for menu item type selection. Tested
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3922">issues.joomla.org/joomla-cms/3922</a>.</sub>

**Comment by roland-d** [comment]
@dgt41 Thank you for stepping in here. How do you propose to fix this PR? It has been tested successfully twice. Perhaps a PR against this one by @okonomiyaki3000 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3922">issues.joomla.org/joomla-cms/3922</a>.</sub>

**Comment by okonomiyaki3000** [comment]
There were some problems with the tests. I'll have a look at this deprecated modal issue.

**Comment by okonomiyaki3000** [comment]
@wnnz34 JHtmlBootstrap::modal is not really used for those batch buttons. The only place I can find it being used at all is in the modules view and it's completely unnecessary there. That line can be removed and the modal still works because the js code to actually create and open the modal is in the layout file. 

The comment on the modal function: "JS Not working" is not correct. It works perfectly it just doesn't really do anything. It sets up the modal but never opens it (unless `"show": true` is part of the `$params` object but this will just cause the modal to open instantly on page load). So the function is kind of useless. 

Sorry, off topic, but I think really all of these front-end functions are kind of stupid. This front-end stuff just be done on the front end. We don't need PHP functions to do it.

**Comment by roland-d** [comment]
Hello @okonomiyaki3000 

Thank you for your contribution.

The last comment here was on August 25th. Can you please follow-up?

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/3922">issues.joomla.org/joomla-cms/3922</a>.</sub>

**Comment by okonomiyaki3000** [comment]
@roland-d OK, well as a follow up to myself...

Yes, @okonomiyaki3000, you are correct that the modal function (which will apparently be removed in 4.0 anyway) is no longer used anywhere. Even so, fixing it is a good idea.

I also agree with you that these back-end functions should not exist at all. 

Also, I've rebased with the latest staging.

**Comment by infograf768** [comment]
Folks, see #11400
@okonomiyaki3000 
@roland-d 
We have an issue with strings containing single quote

**Pull request merged**
