### PR TITLE
Ensure param for showing page header works in beeze

### PR DESCRIPTION
**Pull request by wilsonge**
In beez3 hiding the page heading whilst still showing the category title will end up with the page heading still showing - all in the same h1 tag. This fixes that.
### Testing

Turn off page heading param and on category title. Observe both still appear

Apply Patch

Only category title appears (in a h2 tag now). Verify turning on page heading param makes the page heading reappear (in a h1 tag).

### CODE REVIEW

**Comment by davdebcom** [comment]
@test
Tested successfully.

**Comment by davdebcom** [comment]
To test:
- Make sure you are using the Beez template
- Create a menu item to Category Blog
- In the menu item "Category" tab set "Category title" to "Show"
- In the "Page Display" tab set "Show Page Heading" to "No"
- Enter "Page heading" in "Page Heading" field
- Go to site, view the category blog, you will see a double title "Page headingYourCategoryname" where YourCategoryname is the name of the Category.
- Apply patch
- "Page heading" in the category blog should now no longer be shown<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3523">issues.joomla.org/joomla-cms/3523</a>.</sub>

**Comment by superknutsel** [comment]
@test 
Tested succesfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3523">issues.joomla.org/joomla-cms/3523</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3523">issues.joomla.org/joomla-cms/3523</a>.</sub>

**Pull request closed without merging**
