### PR TITLE
[4.1] Template Manager: Fixing return URL

### PR DESCRIPTION
**Pull request by Hackwar**
During code review, I noticed this missing equal sign. I did not test it, I've just made this as a PR.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on ce79331a5acefb464f3d2b19ecef214cf0731857<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36871">issues.joomla.org/tracker/joomla-cms/36871</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ce79331a5acefb464f3d2b19ecef214cf0731857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36871">issues.joomla.org/tracker/joomla-cms/36871</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36871">issues.joomla.org/tracker/joomla-cms/36871</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on ce79331a5acefb464f3d2b19ecef214cf0731857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36871">issues.joomla.org/tracker/joomla-cms/36871</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
