### PR TITLE
[4.0] Allow form elements in a subform template (sanitisation)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #34512 (the subform part) .

### Summary of Changes
- Revert the sanitisation here

### Documentation Changes Required

@wilsonge can you push the button here?

### CODE REVIEW

**Comment by Fedik** [comment]
hm, do we really need cleaning for subform "template"?
it can be pretty complex for a forms, there may be fields with custom element, and fields with onclick attributes

**Comment by dgrammatiko** [comment]
>  and fields with onclick attributes

This is exactly what's not allowed and what the sanitizer is supposed to clean 😉

**Comment by Fedik** [comment]
then subfrom will be broken for these fields, 
there may be fields that use it

**Comment by dgrammatiko** [comment]
> then subfrom will be broken for these fields, there may be fields that use it

Hard call (thankfully not my call). Allowing inline on-events is XSS prone. Disallowing on-events is stricter but probably all elements will be required to be defined custom-elements (own constructor etc). I'm ok reverting this. @wilsonge your call...

**Comment by Fedik** [comment]
I understood the intention, and it good one.
but it pretty hard.

**Comment by richard67** [comment]
@dgrammatiko CS: https://ci.joomla.org/joomla/joomla-cms/45175/1/21

**Comment by dgrammatiko** [comment]
> I understood the intention, and it good one.
> but it pretty hard.

Till there's a viable solution for sanitization of the subform templates the changes have been reverted

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 934208e17c186632a23add22be52e8e1e6925245<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34514">issues.joomla.org/tracker/joomla-cms/34514</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 934208e17c186632a23add22be52e8e1e6925245<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34514">issues.joomla.org/tracker/joomla-cms/34514</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34514">issues.joomla.org/tracker/joomla-cms/34514</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
