### PR TITLE
Update ru-RU.ini (installation, small bug)

### PR DESCRIPTION
**Pull request by Kostelano**
Small bug
Screenshot: http://savepic.su/5041355.png

### CODE REVIEW

**Comment by Kostelano** [comment]
Fixed.

**Comment by infograf768** [comment]
Thanks. Merged.

**Comment by SergeyLitvinov** [comment]
I know about "_QQ_" but current issue is related to previous PR (https://github.com/joomla/joomla-cms/pull/5886). In original translation was used single quote symbol and it was replaced with &quote

**Comment by infograf768** [comment]
I have changed it back to single quotes again, Sergey.
Although using `"_QQ_"` LOOKS like working, doublequotes are in fact producing invalid markup in the case of buttons using an HTML attribute.

**Pull request merged**
