### PR TITLE
Make sure the item ids are integers and use the same variable like in the rest of the code

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Make sure the item ids are integers and use the same variable like in the rest of the code for the menus checkin method

### Testing Instructions

- make sure the com_menus check in still works.

### Expected result

the passed ids are now checked to be integer

### Actual result

the passed ids where not checked whether they where integers or not.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 79c190a90b478b6e1a7befbaf8e21bddf493feba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28459">issues.joomla.org/tracker/joomla-cms/28459</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 79c190a90b478b6e1a7befbaf8e21bddf493feba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28459">issues.joomla.org/tracker/joomla-cms/28459</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28459">issues.joomla.org/tracker/joomla-cms/28459</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the tests :+1:

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
