### PR TITLE
[4.0] Cassiopeia: Add height auto to images to maintain aspect ratio

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #31647 .

### Summary of Changes
Added height: auto to img to maintain aspect ratio when width 100%

### Testing Instructions
Create an article with a full image in format 16:9 (e.g. 1280 x 720px), set Image Class to float-none. 
Install this PR and run "npm run build:css"

### Actual result BEFORE applying this Pull Request
The image will have a width of 100%, but the height stay at 720px, so the aspect ratio is distorted.

### Expected result AFTER applying this Pull Request
The image is 100% wide and the height scale proportionally.

### CODE REVIEW

**Comment by richard67** [comment]
@drmenzelit The phpcs failure in Drone is not related to your PR, it comes from the 4.0-dev branch having had code style errors when you had created your branch based on it. But if you want to get rid of the Drone failure, update your branch to latest 4.0-dev, where the errors meanwhile have been corrected.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9737eba738ccddd5c42372b22c6e067640f34091<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31667">issues.joomla.org/tracker/joomla-cms/31667</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9737eba738ccddd5c42372b22c6e067640f34091<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31667">issues.joomla.org/tracker/joomla-cms/31667</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31667">issues.joomla.org/tracker/joomla-cms/31667</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
