### PR TITLE
Unable to install 3.5 on mssql

### PR DESCRIPTION
**Pull request by alikon**
Unable to install 3.5 on mssql  same as #8219

### CODE REVIEW

**Comment by roland-d** [comment]
Merged on code review.

**Comment by zero-24** [comment]
Did you merge it into 3.5-dev for a reason? Or should it merged into staging now?

**Comment by roland-d** [comment]
@zero-24 Very sharp, this should have been merged into staging since 3.5-dev is no longer in use. I didn't realize it was done against 3.5 because the request is from today. Good catch.

**Comment by zero-24** [comment]
:+1:

**Comment by roland-d** [comment]
Merged into staging.

**Pull request merged**
