### PR TITLE
[3] Flush administrator system cache after rebuilding update sites

### PR DESCRIPTION
**Pull request by PhilETaylor**
Flush both system caches after rebuilding update sites

Last bit missing from already merged https://github.com/joomla/joomla-cms/pull/32862

// @richard67

### CODE REVIEW

**Comment by HLeithner** [comment]
What's the reason to clear frontend cache? shouldn't this only effect backend?

**Comment by PhilETaylor** [comment]
With the exception of one place in Joomla 3, wherever 

`cleanCache('_system', 1)` 

is, we always clear the other one `0` too.  Belt and braces I guess.

**Comment by PhilETaylor** [comment]
I have removed the extra cleanCache for you

**Comment by richard67** [comment]
> Belt and braces I guess.

At least we are not formatting hard disks ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c65d8a32ace8f819141ba8b002d413a3cf7b4888<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33040">issues.joomla.org/tracker/joomla-cms/33040</a>.</sub>

**Comment by richard67** [comment]
Code review ok, and rebuild update sites still works.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
