### PR TITLE
Add more search engine bots to robots list

### PR DESCRIPTION
**Pull request by jurihahn**
Pull Request for Issue # .

### Summary of Changes
Add more robots to list for detection. List generated from: 
https://github.com/monperrus/crawler-user-agents

### Testing Instructions
Code review

### Expected result
more robots in the robots list

### Actual result
small robots list

### Documentation Changes Required
No

### CODE REVIEW

**Comment by brianteeman** [comment]
There must be a more up to date list available somewhere that can be used - for example I know that majestic-12 is one of the top (if not the top) crawlers

**Comment by jurihahn** [comment]
> There must be a more up to date list available somewhere that can be used - for example I know that majestic-12 is one of the top (if not the top) crawlers

Should i completely update the list with one PR?

**Comment by brianteeman** [comment]
If you can find a good list then it would make sense to do it all in one pr

**Comment by jurihahn** [comment]
i think this is good list http://www.useragentstring.com/pages/useragentstring.php?typ=Crawler

**Comment by brianteeman** [comment]
I note that that list doesn't include bingpreview which is in this pr

Found this list from keycdn of the most popular - lets just make sure we have those
https://www.keycdn.com/blog/web-crawlers/

**Comment by SharkyKZ** [comment]
This is a decent resource https://github.com/monperrus/crawler-user-agents. If not overkill.

**Comment by jurihahn** [comment]
i think it's ready to test/review

**Comment by jurihahn** [comment]
> This is a decent resource https://github.com/monperrus/crawler-user-agents. If not overkill.

i generated robot list from it

**Comment by jurihahn** [comment]
@SharkyKZ @brianteeman it's now OK?

**Comment by brianteeman** [comment]
seems ok to me

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 12d17fadec2da95b2d4696f17e6aa67a92e33394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22368">issues.joomla.org/tracker/joomla-cms/22368</a>.</sub>

**Comment by jurihahn** [comment]
@sandewt wrong thread?

**Comment by sandewt** [comment]
>libraries/src/User/UserHelper.php, Line 760: Should be ->where($db->quoteName('user_id') . ' = ' . (int) $userId);


@jurihahn see, [#22079] - typecasting code privacy content plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22368">issues.joomla.org/tracker/joomla-cms/22368</a>.</sub>

**Comment by infograf768** [comment]
@sandewt 
This PR does not touch at this file.
Please create a new issue or PR for that one.

**Comment by sandewt** [comment]
>This PR does not touch at this file.

Thanks @infograf768 and @jurihahn.

I got it. 

There are more files in the Joomla core  with this issue.

So it should be a new PR.

[EDIT] Some text.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 12d17fadec2da95b2d4696f17e6aa67a92e33394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22368">issues.joomla.org/tracker/joomla-cms/22368</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22368">issues.joomla.org/tracker/joomla-cms/22368</a>.</sub>

**Pull request merged**
