### PR TITLE
[3.9] Unification plugin name plg_system_actionlogs

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

change string to "System - User Actions Log"

### Testing Instructions

Extensions -> Plugins -> search for "Actions Log"

### Expected result

System - User Actions Log

### Actual result

System - Actions Log

### Documentation Changes Required

Appearance of the plugin name. My suggestion would be "System - User Actions Log" in both files, because these are User Actions.

See translation in en-GB.plg_system_actionlogs.ini https://github.com/joomla/joomla-cms/blob/a0c6aa6c58d92bb7725b7fdb6ea95061ea5e598a/administrator/language/en-GB/en-GB.plg_system_actionlogs.ini#L6

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
approve change

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ecaedf6a6a5087cb1f006e480376f67e7cfa6434<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21984">issues.joomla.org/tracker/joomla-cms/21984</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on ecaedf6a6a5087cb1f006e480376f67e7cfa6434<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21984">issues.joomla.org/tracker/joomla-cms/21984</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC after 2 successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21984">issues.joomla.org/tracker/joomla-cms/21984</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks @tecpromotion

**Pull request merged**
