### PR TITLE
Tagged items: add microdata

### PR DESCRIPTION
**Pull request by LivioCavallo**
### Summary of Changes
Added `ItemList` microdata (name, image, description, ...) to default_items tag view.

### Testing Instructions
In J! 3.7.5
Tag some items (articles, contacts) with tag "Joomla".
Create a menuitem of type "Tagged Items", tag "Joomla".

### Expected result
Like in article, blog, ... page types, we expect that Microdata should be present for listed items in "Tagged Items" page.

### Actual result
Microdata is not present.
(verify at: https://search.google.com/structured-data/testing-tool   that `ItemList  `is not present)

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cad677c853c6b08c540d4ed0d5e350eea3f198b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17689">issues.joomla.org/tracker/joomla-cms/17689</a>.</sub>

**Comment by alikon** [comment]
we should use 
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Microdata/Microdata.php
i guess  ?

**Comment by LivioCavallo** [comment]
May be, but blogs and articles insert plain intempscope, intemprop in elements. I followed.

**Comment by photodude** [comment]
@alikon as per the comment https://github.com/joomla/joomla-cms/pull/8934#issuecomment-217629179 and the comment at https://github.com/joomla/joomla-cms/pull/8933#issuecomment-173143170 which were decisions resulting from the discussion in PR #3358, from all of those the decision has been that we use hard coded values for microdata.

**Comment by alikon** [comment]
thanks for the recap

**Comment by LivioCavallo** [comment]
Please, @alikon and @photodude , could you test this?

**Comment by photodude** [comment]
@LivioCavallo I apologize, but at the moment I don't have time for testing. If/when I get some reasonable time set aside I'll be working on the [automatic code standards fixers](https://github.com/joomla/coding-standards) I would really like to see it get to a stable release before the end of the year.

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on cad677c853c6b08c540d4ed0d5e350eea3f198b2<br /><br />With this patch "Tagged Items" sites have the `ItemList` item and can be found by the Google tool.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17689">issues.joomla.org/tracker/joomla-cms/17689</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

@LivioCavallo Please resolve conflicting File.

**Comment by LivioCavallo** [comment]
I hope I followed the right procedure to resolve conflicting files (I suspect I made too many merges...). Sorry for this.

**Comment by brianteeman** [comment]
@LivioCavallo looks good

**Pull request merged**
