### PR TITLE
[4.1] Remove Duplicate chars from trim

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

Documentation for `trim` https://www.php.net/trim

Test cases proving this PR is correct https://3v4l.org/psnrn

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc483d96c3d409cc508f40290ca7c15eddffda77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36337">issues.joomla.org/tracker/joomla-cms/36337</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fc483d96c3d409cc508f40290ca7c15eddffda77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36337">issues.joomla.org/tracker/joomla-cms/36337</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36337">issues.joomla.org/tracker/joomla-cms/36337</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
