### PR TITLE
[#33295] Adding the "showon" feature to JForm

### PR DESCRIPTION
**Pull request by chivitli**
### Overview

In the Joomla Global Configuration we use showon attribute to show/hide certain fields based on the state of a "parent" field. You can see this for example with the FTP settings where the settings itself only show when "Enable FTP" is set to "Yes". It's also available for Component settings.

This PR takes this feature to the JForm so it can be used in any xml file.
### Testing

You can add a showon attribute to any config field you want to hide. For example in 
 modules\mod_finder\mod_finder.xml you add to line 94
 showon="show_label:1". So it looks like this:

```
                <field
                    name="label_pos"
                    type="list"
                    default="left"
                    showon="show_label:1"
                    label="MOD_FINDER_FIELDSET_ADVANCED_LABEL_POS_LABEL"
                    description="MOD_FINDER_FIELDSET_ADVANCED_LABEL_POS_DESCRIPTION">
                    <option
                        value="right">JGLOBAL_RIGHT</option>
                    <option
                        value="left">JGLOBAL_LEFT</option>
                    <option
                        value="top">MOD_FINDER_CONFIG_OPTION_TOP</option>
                    <option
                        value="bottom">MOD_FINDER_CONFIG_OPTION_BOTTOM</option>
                </field>
```

This will only show the "Label position" setting only if the "Show Label" is set to "Yes" (which has the value 1).

Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33295&start=0

### CODE REVIEW

**Comment by hkraskian** [comment]
I tried showon in a copy of user profile plugin.
There are two xml files, one for administrator, the other one for registration and profile editing.
The first one is in /plugins/user/profile5/ with name of profile5.xml
The second one is in /plugins/user/profile5/profiles with name of profile.xml.
showon works correct in first file. but doesn't work in second file. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3127">issues.joomla.org/joomla-cms/3127</a>.</sub>

**Comment by Oxonium** [comment]
Same as @hkraskian here. I am trying to use this feature in a custom profile plugin and it is not working.

Anyone has an idea to make this work ?

Thanks a lot in advance !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3127">issues.joomla.org/joomla-cms/3127</a>.</sub>

**Comment by Bakual** [comment]
I don't think the user profile uses a regular JForm, so it will not work there.

**Comment by Oxonium** [comment]
Damn, thanks for the heads up.

Any chance to do conditional fields in Joomla registration form another way (beside specific JS rules) ?

**Comment by Bakual** [comment]
Not that I'm aware of. Best bet is to use custom JS there I think.

**Comment by Oxonium** [comment]
Let's do this then. Thanks for answering ;)

**Pull request closed without merging**
