### PR TITLE
[staging] Search inputmode

### PR DESCRIPTION
**Pull request by brianteeman**
As requested by @wilsonge this is a backport of #27426 

Mobile and touch devices will load a different keyboard depending on the inputmode. This is already implemented for several fields eg url and email

This PR enables it for search fields

As search fields are not a separate field type but type="text" we either have to create a new field type or it has to be added via the form xml. Support for the xml option  was (surprisingly) already implemented so I just had to add the inputmode=search to the xml.

To test this you will need either a mobile device or a touch enabled computer with a virtual keyboard.

When you enter the search field you will see a slightly different keyboard than normal - the actual layout of which is dependent on your device. On my touch screen it looks like this

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 275da888272a67006bf36fa986f243d328a7d1b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27427">issues.joomla.org/tracker/joomla-cms/27427</a>.</sub>

**Review by wilsonge — APPROVED** [review]
Review looks good

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
