### PR TITLE
[modal] Improve iframe modals: categories, contacts, newsfeeds

### PR DESCRIPTION
**Pull request by cyrez**
Part 2 of iframe inside modals. (see for <code>versions</code> here: https://github.com/joomla/joomla-cms/pull/9995

Note: A one-PR will be done for Hathor overrides (as done in PR for versions #9995)
#### Summary of Changes
- When Bootstrap modal loads an iframe, BS tooltips with placement top are truncated at the top border of the iframe. (no auto placement in BS2). This PR sets the tooltip placement to bottom to fix this issue.
- Remove inline CSS
- Content is embedded in a container div (using already existing container-popup class for modal.php)
- Add empty lines to improve the readability
- <code>newsfeeds</code> add search input description for tooltip (form xml)
#### Testing Instructions (Multilanguages enabled!)
- <code>categories</code> Go to Contents > Categories > open a categorie, and go to Association to select associated category. On click, open the modal changed for categories.
- <code>contacts</code> Go to Components > Contacts > open a contact, and go to Association to select associated contact. On click, open the modal changed for contacts.
- <code>newsfeeds</code> Go to Menus Manager > Add New Menu Item > Type "single newsfeed". Click on select the feed to open the modal changed for newsfeeds.
- For Newsfeeds component, check if in modal (see above) and the list of feeds, the added tooltip description for the search input.

To be testing on latest staging.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 622f1ddb11a1ca17eb835ba13911c6b1e2ca4f57<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10075">issues.joomla.org/joomla-cms/10075</a>.</sub>

**Comment by brianteeman** [comment]
@joomlic i am a bit confused. is this pr still for testing or have your newer ones replaced it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10075">issues.joomla.org/joomla-cms/10075</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think this one is still for testing, but now has merge conflicts @JoomliC

**Comment by JoomliC** [comment]
It was still for testing, but i will redo it with viewport addition ;-)
@andrepereiradasilva the conflict seems with this one https://github.com/joomla/joomla-cms/pull/10178 (open after, but already merged ;-) )

So i close this one, and will redo it on staging (maybe in a few hours ;-) )

**Comment by JoomliC** [comment]
@brianteeman in the same time, i make a list of other modal to be updated, so will see to do each one by one, to help faster testing ;-)

**Comment by brianteeman** [comment]
Thanks

On 11 May 2016 at 16:48, Cyril Rezé <notifications@github.com> wrote:

> It was still for testing, but i will redo it with viewport addition ;-)
> @andrepereiradasilva <https://github.com/andrepereiradasilva> the
> conflict seems with this one #10178
> <https://github.com/joomla/joomla-cms/pull/10178> (open after, but
> already merged ;-) )
>
> So i close this one, and will redo it on staging (maybe in a few hours ;-)
> )
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10075#issuecomment-218501541>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request closed without merging**
