### PR TITLE
Workflows: Changed column labels in com_workflow transitions

### PR DESCRIPTION
**Pull request by SamuelSchepp**
Pull Request for Issue #21666.

### Summary of Changes

The table column labels "From Stage" and "To Stage" are changed to "Current Stage" and "Target Stage" to be more consistent with the table options dropdown field names.

### Testing Instructions

Add a workflow (Content -> Workflows) and add a transition to it.

### Expected result

screenshot 2018-09-08 12 24 04

screenshot 2018-09-08 13 17 02

### Actual result

screenshot 2018-09-08 12 25 53

screenshot 2018-09-08 13 17 42

### Documentation Changes Required

https://docs.joomla.org/Publishing_Workflow/Scenarios/en

"Select the State New blog post – unpublished in the From state field drop-down."
"Select the State Publish new blog post in the To state field drop-down."

### CODE REVIEW

**Comment by DrDreave** [comment]
I have tested this item :white_check_mark: successfully on e62942f4792a9309a1716dd56450de46ddfebccf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22059">issues.joomla.org/tracker/joomla-cms/22059</a>.</sub>

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on 5490896197aaaf0dff1bd660e8c21fc006d845de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22059">issues.joomla.org/tracker/joomla-cms/22059</a>.</sub>

**Review by brianteeman — APPROVED** [review]
approve langauge strings

**Comment by DrDreave** [comment]
I have tested this item :white_check_mark: successfully on 5490896197aaaf0dff1bd660e8c21fc006d845de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22059">issues.joomla.org/tracker/joomla-cms/22059</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
