### PR TITLE
Customizing Tags placeholder select field

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
This changes the default placeholder for the tags field from
`Type or select some options`
to
`Type or select some tags`

### Testing Instructions
Patch and check the placeholder of the Tags field when editing
an article (back-end and frontend)
a category
a contact
a news feed
a blog menu item

### after patch
Screen Shot 2019-05-20 at 17 40 27

### CODE REVIEW

**Comment by imanickam** [comment]
I have tested this item :white_check_mark: successfully on 82eb4fe261e2be557471fd8bf6aaf9b811fd367e<br /><br />I have tested this patch in all the places mentioned in the testing instrucation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24963">issues.joomla.org/tracker/joomla-cms/24963</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 82eb4fe261e2be557471fd8bf6aaf9b811fd367e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24963">issues.joomla.org/tracker/joomla-cms/24963</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24963">issues.joomla.org/tracker/joomla-cms/24963</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
