### PR TITLE
[5.1] language code rich snippet revert

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
In the large Rich Snippets PR #41151 a line was changed that has resulted in invalid markup and broken functionality of the language code plugin

### Testing Instructions
1. Create an article in and view the article in the front end.
Check the source and you will see the invalid markup
`<meta content="en-GB">`

2. open the  language code plugin, enable and save
go to the new tab in that plugin and change the lanbguage code to en-BT
Refresh the front and refresh the page. View the source and you will see the same invalid markup as in test 1

3. Apply the one line change in this PR
Disable the language code plugin
Refresh the front and refresh the page. View the source and you will see the` <meta itemprop="inLanguage" content="en-GB">`
This is the correct and valid markup
4. Re-enable the language code plugin and check the frone end again and you will see `<meta itemprop="inLanguage" content="en-BT">`
### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e371631f6e1f13b1010129131f4d5a893cb5db2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43123">issues.joomla.org/tracker/joomla-cms/43123</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on e371631f6e1f13b1010129131f4d5a893cb5db2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43123">issues.joomla.org/tracker/joomla-cms/43123</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you for this contribution. I would really like to merge this in 5.1 if you would find the time to rebase @brianteeman

**Comment by brianteeman** [comment]
rebased to 5.1 as requested

**Comment by bembelimen** [comment]
Thx

**Comment by Scrabble96** [comment]
I thought the idea in J5 was to remove itemprops from the template php files and let Joomla's schema.org add the correct code. Now, on updating from 5.0.3 to 5.1.0 I see that ```itemprop="inLanguage"``` has appeared in html/com_content/article/default.php. Is that right?

**Pull request merged**
