### PR TITLE
Use conroller input instead of calling application to get input

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
In some methods of ContrllerAdmin class, we are getting input data from application input instead of from controller input object. This is not really correct, this small PR just correct it.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by mbabker** [comment]
Is this unique to 3.8?  Preferably this should go into staging.

**Comment by joomdonation** [comment]
3.8 is namespace MVC, so I guess we need a separate PR for stagging, correct?

**Comment by mbabker** [comment]
No.  Unless things have massively broken it should be possible to merge staging to 3.8 to 4.0 still.  So only one PR needed to fix things in as many branches as possible.

**Comment by mbabker** [comment]
Git usually does pretty good following moved files around and flagging merge conflicts when it can't automagically figure something out.

Otherwise every patch would require a pull request on every active branch and require active testing on every branch.  That's far too much to ask.  And would probably result in a lot more broken stuff and a lot less fixes getting through.

**Comment by joomdonation** [comment]
OK. Thanks Michael. I opened a PR on staging and close this one now

**Pull request closed without merging**
