### PR TITLE
[4.0] All values are deleted when changing list-based custom field options

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes query deleting all field values when changing list-based custom field options.

### Testing Instructions

Create a list-based field (e.g. Checkboxes).
Add some options (e.g. 1, 2, 3).
Create an article. Select all options.
Edit the custom field. Remove option with value 3.
View the article in frontend. Check the custom field values.

### Expected result

Values 1 and 2 are shown.

### Actual result

All values gone.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
This was discussed before when fields was introduced. Would be good to find thta and check the comments

**Comment by SharkyKZ** [comment]
No, this issue was introduced in recently in #25657.

**Comment by brianteeman** [comment]
Is this not the same issue https://github.com/joomla/joomla-cms/issues/20263

**Comment by SharkyKZ** [comment]
No, it's not the same.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9e6047c9830af24f9958a32a32ff201a27891b3a<br /><br />Tested successfully in Nightly Build of May 21.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29172">issues.joomla.org/tracker/joomla-cms/29172</a>.</sub>

**Comment by maikol-ortigueira** [comment]
I have tested this item :white_check_mark: successfully on 9e6047c9830af24f9958a32a32ff201a27891b3a<br /><br />I have performed the test and it is working as expected. Successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29172">issues.joomla.org/tracker/joomla-cms/29172</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29172">issues.joomla.org/tracker/joomla-cms/29172</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
