### PR TITLE
[4.0] Fix error on click article version history

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue 
Click on version history of an article.
Error: <code>0 Call to a member function getSha1() on boolean</code>
On linux.

### Summary of Changes

<code>$table</code> name changed to <code>Contenthistory-->ContentHistory</code>

### Testing Instructions

<h4>Test this on Linux.</h4>
And make sure this change also work in Mac and windows.

1.Go to Content ->edit article 
2.Click on a version.

### Expected result
No error comes.

### Actual result
Error comes 

<code>0 Call to a member function getSha1() on boolean</code>

### CODE REVIEW

**Comment by anuragteapot** [comment]
@laoneo same problem here.

**Review by laoneo — APPROVED** [review]

**Comment by anuragteapot** [comment]
@Quy please test this on linux

**Comment by wilsonge** [comment]
Thanks!

**Comment by anuragteapot** [comment]
@wilsonge Welcome

**Pull request merged**
