### PR TITLE
[4.0] Com_association js cleanup, fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Code to ES6 (except sidebyside.js which is....)
- Fixed some obvious bugs
- Patched bootstrap-init.js to work with the js in the url (give a cookie to the one who had this brilliant idea) 

### Testing Instructions

@infograf768 you might be the only one here that knows what was broken, so please test and also provide some info for others to know how to test

### Expected result

Modal opens

### Actual result

Modal doesnt appear and also there was a console error

### Documentation Changes Required

Hopefully not

### CODE REVIEW

**Comment by infograf768** [comment]
Original Issue is https://github.com/joomla/joomla-cms/issues/18552

Test Unsuccessful:
The modal loads fine but it is empty.

Code comparison  for menu item (debug ON)
3.8
```
function jSelectAssociation_jform_modalassociation(id) {
   target = document.getElementById("target-association");
   document.getElementById("target-association").src = target.getAttribute("data-editurl") + "&task=" + target.getAttribute("data-item") + ".edit" + "&id=" + id
	jQuery("#associationSelectjform_modalassociationModal").modal("hide");
}
jQuery(document).ready(function($) {
   $('#associationSelectjform_modalassociationModal').on('show.bs.modal', function() {
       $('body').addClass('modal-open');
       var modalBody = $(this).find('.modal-body');
       modalBody.find('iframe').remove();
       modalBody.prepend('<iframe class="iframe jviewport-height70" src="index.php?option=com_associations&amp;view=associations&amp;layout=modal&amp;tmpl=component&amp;forcedItemType=com_menus.item&amp;function=jSelectAssociation_jform_modalassociation&amp;forcedLanguage=' + document.getElementById('target-association').getAttribute('data-language') + '&amp;8da36713bef8d17c9e99f4bd1ebdedf7=1" name="Select Target" height="400px" width="800px"></iframe>');
   }).on('shown.bs.modal', function() {
       var modalHeight = $('div.modal:visible').outerHeight(true),
           modalHeaderHeight = $('div.modal-header:visible').outerHeight(true),
           modalBodyHeightOuter = $('div.modal-body:visible').outerHeight(true),
           modalBodyHeight = $('div.modal-body:visible').height(),
           modalFooterHeight = $('div.modal-footer:visible').outerHeight(true),
           padding = document.getElementById('associationSelectjform_modalassociationModal').offsetTop,
           maxModalHeight = ($(window).height()-(padding*2)),
           modalBodyPadding = (modalBodyHeightOuter-modalBodyHeight),
           maxModalBodyHeight = maxModalHeight-(modalHeaderHeight+modalFooterHeight+modalBodyPadding);
       var iframeHeight = $('.iframe').height();
       if (iframeHeight > maxModalBodyHeight){;
           $('.modal-body').css({'max-height': maxModalBodyHeight, 'overflow-y': 'auto'});
           $('.iframe').css('max-height', maxModalBodyHeight-modalBodyPadding);
```
Your PR
```
<div id="associationSelectjform_modalassociationModal" role="dialog" tabindex="-1" class="joomla-modal modal fade" data-backdrop="static" data-url="index.php?option=com_associations&amp;view=associations&amp;layout=modal&amp;tmpl=component&amp;forcedItemType=com_menus.item&amp;function=jSelectAssociation_jform_modalassociation&amp;forcedLanguage=' + document.getElementById('target-association').getAttribute('data-language') + '&amp;34e9e1234719b19bf400c121347c3d6a=1" data-iframe="&lt;iframe class=&quot;iframe&quot; src=&quot;index.php?option=com_associations&amp;amp;view=associations&amp;amp;layout=modal&amp;amp;tmpl=component&amp;amp;forcedItemType=com_menus.item&amp;amp;function=jSelectAssociation_jform_modalassociation&amp;amp;forcedLanguage=' + document.getElementById('target-association').getAttribute('data-language') + '&amp;amp;34e9e1234719b19bf400c121347c3d6a=1&quot; name=&quot;Select Target&quot; height=&quot;400px&quot; width=&quot;800px&quot;&gt;&lt;/iframe&gt;">
```
Remark in your PR the use of `&amp;amp;`

**Comment by infograf768** [comment]
Also, can you integrate the changes
https://github.com/joomla/joomla-cms/pull/21180
in this PR

**Comment by dgrammatiko** [comment]
Modal restored:
screenshot 2018-07-19 at 12 20 22

**Comment by infograf768** [comment]
Thanks. It works fine now. Remains to add the same modifications as what has been done in https://github.com/joomla/joomla-cms/pull/21180 to get correct contacts and newsfeeds associations fields.

**Comment by infograf768** [comment]
will test it OK when conflict fixed.

**Comment by dgrammatiko** [comment]
@infograf768 conflict resolved

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 92a08ec5cbbc4ef2ec682123dfb3822636f3ccda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21176">issues.joomla.org/tracker/joomla-cms/21176</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 911b15f8840526089e1bff4c1ad31f486f9ac4c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21176">issues.joomla.org/tracker/joomla-cms/21176</a>.</sub>

**Comment by laoneo** [comment]
Good job!

**Pull request merged**
