### PR TITLE
[4.1] Make the getElement function easier to read in PluginAdapter

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Simplifies the getElement function in PluginAdapter.

### Testing Instructions
Install any plugin.

### Actual result BEFORE applying this Pull Request
Works no error.

### Expected result AFTER applying this Pull Request
Works no error.

### CODE REVIEW

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 7b139583582f736c905a952fcdeab0cc7339a842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36017">issues.joomla.org/tracker/joomla-cms/36017</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 7b139583582f736c905a952fcdeab0cc7339a842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36017">issues.joomla.org/tracker/joomla-cms/36017</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36017">issues.joomla.org/tracker/joomla-cms/36017</a>.</sub>

**Review by richard67 — APPROVED** [review]
Correct according to De Morgan's laws.

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 7b139583582f736c905a952fcdeab0cc7339a842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36017">issues.joomla.org/tracker/joomla-cms/36017</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
