### PR TITLE
[4.0][mod_articles_category] Remove unused variable

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes unused variable.

### Testing Instructions

Code review.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f10095ebe6ecb98216d26ea3ad364f649538f00a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24053">issues.joomla.org/tracker/joomla-cms/24053</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f10095ebe6ecb98216d26ea3ad364f649538f00a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24053">issues.joomla.org/tracker/joomla-cms/24053</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24053">issues.joomla.org/tracker/joomla-cms/24053</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
