### PR TITLE
[Accessibility] Category list

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR makes category list menu item type acessible according to WCAG 2.0.
1. List of articles table:
   - Now the table header always exists in the HTML, through CSS it show or hides according to "Show Headings" Show/Hide selection.
     
     See http://www.w3.org/TR/WCAG20-TECHS/H51.html
   - A `caption` tag (css hidden by default) is added to the Table.
     
     See http://www.w3.org/TR/WCAG20-TECHS/H39.html
   - Column scopes (`scope="col"`) are added to `th` tags.
     
     See http://www.w3.org/TR/WCAG20-TECHS/H63.html
2. Form with filters:
   - The form tag is now only in for the filter field (not form + table inside form tag like before).
   - A `legend` tag (css hidden by default) is added to the fieldset.
     
     See http://www.w3.org/TR/WCAG20-TECHS/H71.html
   - A submit button is added (css hidden by default) to the filter form.
     
     See http://www.w3.org/TR/WCAG20-TECHS/H32.html
#### How to test
1. Use a fresh joomla install with sample items.
2. Create a "Category list" menu item type and play with "List layout" separator options and check if everything is showing as it should in the frontend.
3. Use an external automatic acessibility checker to check if everything is ok. Some tools: http://www.w3.org/WAI/ER/tools/
#### More info

Improvements are welcome

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
seems that travis is having problems in php 7 tests

**Comment by Curtista** [comment]
First I've done the steps in the "How to Test".
For the 3th step I've used the Wave Chrome extension available at http://wave.webaim.org/ which only recognizes that (before the patch) there was no legend tag in the fieldset.
The remaining changes I had to test manually against the specifications, because I run Joomla on my local machine and found no tool except for the wave chrome extension.

Now lets talk about the changes. When I was testing it manually everything was fine except for that the first th-tag in the table had no scope="col". Because of this missing scope="col" the test was unsuccessful.

@icampus

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by Curtista** [comment]
I have tested this item :red_circle: unsuccessfully on d3070e057c45dbd1d83f72ea018a5c6b3ad8c8b5<br /><br />First I've done the steps in the "How to Test".
For the 3th step I've used the Wave Chrome extension available at http://wave.webaim.org/ which only recognizes that (before the patch) there was no `legend` tag in the fieldset.
The remaining changes I had to test manually against the specifications, because I run Joomla on my local machine and found no tool except for the wave chrome extension.

Now lets talk about the changes. When I was testing it manually everything was fine except for that the first `th` tag in the table had no `scope="col"`. Because of this missing `scope="col"` the test was unsuccessful.

@icampus

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by kevinscheithauer** [comment]
I have tested this item :red_circle: unsuccessfully on d3070e057c45dbd1d83f72ea018a5c6b3ad8c8b5<br /><br />I have tested this issue @icampus PBF with the proposed patch and have pretty much the same "issues" as Curtista. I followed your "How to test" but on a local server and inspected the site myself. Your patch definitely improves the accessibility but seems to omit the scope attribute of the first th-tag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by andrepereiradasilva** [comment]
added missing scope

**Comment by Curiensol** [comment]
I have tested this item :white_check_mark: successfully on 80c166a0fd53e27ee51bc90f5cdd55351f10ff7e<br /><br />Everything fine, even the  scope="col" is now Present :smile: 

@icampus Pizza,Bugs&Fun<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by kevinscheithauer** [comment]
I have tested this item :white_check_mark: successfully on 80c166a0fd53e27ee51bc90f5cdd55351f10ff7e<br /><br />Tested it like I did previously and its working perfect for me this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by brianteeman** [comment]
RTC - sorry for the delay<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by zero-24** [comment]
@andrepereiradasilva there are merge conflicts here can you fix that?

**Comment by rdeutz** [comment]
any change to fix the conflicts @andrepereiradasilva ?

**Comment by andrepereiradasilva** [comment]
sorry ... to many PR. will do when i can

**Comment by wilsonge** [comment]
Can we have one more test here please now these conflicts have been fixed? Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/joomla-cms/8599</a>.</sub>

**Comment by andrepereiradasilva** [comment]
hum ... i think there a potencial issue here.
if i'm not worng if a site that uses otehr template does not have this hide css classes the form legend will appear in the site, the same goes for table-noheader class.

I could, for css for B/C in the file, @wilsonge what do you think?

**Comment by andrepereiradasilva** [comment]
ok added the css classes inline too to prevent that issue

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9ae27a6c336a44a3d4a4689886ab6bbab01150b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/tracker/joomla-cms/8599</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 9ae27a6c336a44a3d4a4689886ab6bbab01150b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/tracker/joomla-cms/8599</a>.</sub>

**Comment by brianteeman** [comment]
@andrepereiradasilva sorry to say that we have merge conflicts again. If you can fix them i will make sure it gets merged quickly and wont happen again

**Comment by superknutsel** [comment]
I have tested this item :white_check_mark: successfully on 9ae27a6c336a44a3d4a4689886ab6bbab01150b5<br /><br />Tested issue successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8599">issues.joomla.org/tracker/joomla-cms/8599</a>.</sub>

**Comment by wilsonge** [comment]
I've manually fixed the conflicts here and merged it. @brianteeman could you just check i haven't screwed anything up please

**Pull request closed without merging**
