### PR TITLE
Clarifying Modules Toolbar Title

### PR DESCRIPTION
**Pull request by infograf768**
This PR  modifies the Modules Toolbar Title to specify the client displayed.

After patch:
screen shot 2016-02-26 at 09 50 35
screen shot 2016-02-26 at 09 50 17

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a2241a1b612b5768b325c93f4162bff87dce27bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9218">issues.joomla.org/joomla-cms/9218</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on a2241a1b612b5768b325c93f4162bff87dce27bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9218">issues.joomla.org/joomla-cms/9218</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.

@wilsonge I guess this can go in 3.5.0 as we are not yet in language freeze.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9218">issues.joomla.org/joomla-cms/9218</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 for consistency can you do a similar PR to com_cache cache view?

Will update the installed language PR (https://github.com/joomla/joomla-cms/pull/9102) to do the same thing so this can be consistent in all cases.

A question ask, another view that has a view selector is com_menus items view. Should a similiar change also be applied there?

**Comment by infograf768** [comment]
Will do for com_cache now and look what can be done for menu items.

BTW, for menu items I have an unrelated older PR not enough tested: https://issues.joomla.org/tracker/joomla-cms/8411

**Comment by infograf768** [comment]
Just deleted an empty line.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ab880130d288fcbd64d4983d0c4a89785c2f5307<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9218">issues.joomla.org/joomla-cms/9218</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 BTW somewhat related to this PR, shouldn't, from a usability point com_templates also have a client selector?

IMHO just a very few people changes or edits the admin template so why confuse users with admin templates when we can have a client selector like the one used in other views (installed languages, cache and modules)?

**Pull request merged**
