### PR TITLE
[4.0] Action Log options

### PR DESCRIPTION
**Pull request by brianteeman**
Kill the descriptions as they are not needed and tweak the labels

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c4e3affae29e262800311603439547eb1e0977fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27457">issues.joomla.org/tracker/joomla-cms/27457</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on c4e3affae29e262800311603439547eb1e0977fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27457">issues.joomla.org/tracker/joomla-cms/27457</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27457">issues.joomla.org/tracker/joomla-cms/27457</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
