### PR TITLE
TinyMCE image button

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Now that we have the XTD-Image button on the toolbar we dont need the tinymce image button as well.

This PR removes the Insert image from the menu and the toolbar in advanced mode and just leaves the XTD-Image button
### Before

screen shot 2016-04-20 at 05 57 47
### After

screen shot 2016-04-20 at 05 57 58

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 3262b85c6300dab22a98c9a7f2808c5f41e45ce6<br /><br />totally agree, that was confusing even if the featur/purpose are not strictly the same
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3262b85c6300dab22a98c9a7f2808c5f41e45ce6<br /><br />10000 ok!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks

Personally I think this is fixing a bug so should be in 3.5.2 but will leave it to the maintainers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by rdeutz** [comment]
Another way to see it, that removing a menu item is not B/C and this has to go into 4.0. I wouldn't go so far but I don't see how this here can be a bug fix. What should be the bug? That we have two ways of inserting an image?

I think waiting for 4.0 is too much but it I wouldn't merge it into a bugfix-release.

**Comment by brianteeman** [comment]
The bug would be two buttons that suggest they do the same thing but dont.
;)

On 20 April 2016 at 14:38, Robert Deutz <notifications@github.com> wrote:

> Another way to see it, that removing a menu item is not B/C and this has
> to go into 4.0. I wouldn't go so far but I don't see how this here can be a
> bug fix. What should be the bug? That we have two ways of inserting an
> image?
>
> I think waiting for 4.0 is too much but it I wouldn't merge it into a
> bugfix-release.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10000#issuecomment-212426751>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
Nice one Brian, but before we totally remove the standard tinyMCE image button (I think) we need the image dimensions fields in the joomla media view:

screen shot 2016-04-20 at 20 37 13

**Comment by brianteeman** [comment]
Good point but something for someone else to decide if we can merge this
without adding code to the XTD-Editor button is beyond the scope of this PR.

As Robert says this change of mine is for 3.6 hen I think its ok because by
then you will have merged your new media manager code which will address
this ;) :)

On 20 April 2016 at 19:34, Dimitri Grammatikogianni <
notifications@github.com> wrote:

> Nice one Brian, but before we totally remove the standard tinyMCE image
> button (I think) we need the image dimensions fields in the joomla media
> view:
>
> [image: screen shot 2016-04-20 at 20 37 13]
> <https://cloud.githubusercontent.com/assets/3889375/14685998/9e771394-073f-11e6-9af4-8b456dae71e9.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10000#issuecomment-212549775>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Oh and I did NOT totally remove it - I left it in the Extended mode

On 20 April 2016 at 19:37, Brian Teeman <brian@teeman.net> wrote:

> Good point but something for someone else to decide if we can merge this
> without adding code to the XTD-Editor button is beyond the scope of this PR.
>
> As Robert says this change of mine is for 3.6 hen I think its ok because
> by then you will have merged your new media manager code which will address
> this ;) :)
>
> On 20 April 2016 at 19:34, Dimitri Grammatikogianni <
> notifications@github.com> wrote:
>
>> Nice one Brian, but before we totally remove the standard tinyMCE image
>> button (I think) we need the image dimensions fields in the joomla media
>> view:
>>
>> [image: screen shot 2016-04-20 at 20 37 13]
>> <https://cloud.githubusercontent.com/assets/3889375/14685998/9e771394-073f-11e6-9af4-8b456dae71e9.png>
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/10000#issuecomment-212549775>
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ced1870** [comment]
I have tested this item :white_check_mark: successfully on 3262b85c6300dab22a98c9a7f2808c5f41e45ce6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by infograf768** [comment]
This PR indeed should not go  into 3.5.
The TinyMce native image button is the only way for now to modify some settings of an image that would have been inserted via the image editor-XTD.

For example, adding a border, or a specific style.
screen shot 2016-04-21 at 14 01 08

**Comment by brianteeman** [comment]
Already stated that this is for 3.6

**Comment by brianteeman** [comment]
Also if you actually tested the pr you will see I did not remove it from
the extended version of tiny mce which is what your screenshot shows

**Comment by uglyeoin** [comment]
Does this need to be removed from the menu?  Some people look to a menu as their first port of call.

**Comment by brianteeman** [comment]
@uglyeoin yes it has to be removed from the menu or you end up with the menu and the toolbar icon loading different code with different views<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by JoshuaLewis** [comment]
I appreciate the efforts at creating simplicity, however there is another issue that was not mentioned above. I often modify existing images on a page. The MCE image button is able to handle images that are selected and allow for modification. The editor button however only handles new images. If the editor button could handle existing images as well it would basically cover all our bases (except for the other minor features mentioned above).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by ced1870** [comment]
may this will be addressed with the new media manager like mentioned by
Brian ? I don't know as I have not tested it yet

2016-04-23 18:08 GMT+02:00 Josh Lewis <notifications@github.com>:

**Comment by brianteeman** [comment]
Remove RTC - see #10082 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10000">issues.joomla.org/joomla-cms/10000</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman cloud you please check the merge conflicts, thanks

**Comment by brianteeman** [comment]
@rdeutz done

**Comment by wojsmol** [comment]
@brianteeman Please see https://github.com/brianteeman/joomla-cms/pull/19

**Pull request merged**
