### PR TITLE
Add Microseconds to JDate('now')

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

As discussed in https://github.com/joomla/joomla-cms/pull/11888 this PR adds the microsconds when creating a JDate('now') so 'now' is really 'now' and not with a delay up to 0.99(9) seconds.
### Testing Instructions
- Add to protostar/isis index.php the following code.

``` php
$date1 = new JDate('now'); usleep(1000); $date2 = new JDate('now');
$app->enqueueMessage($date1->format('Y-m-d H:i:s.u') . '<br />' . $date2->format('Y-m-d H:i:s.u'), 'notice');
```
- Reload page. Before patch the dates are equal with 0 microseconds.

image
- Apply patch. You should see the dates are different and you should see the microsecond in the notice message.
- Test if Joomla works fine.

image
### Documentation Changes Required

This page in the docs should probably be updated https://docs.joomla.org/How_to_use_JDate

### CODE REVIEW

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 90cc89a0b393b95ef1a3379fa3709c9487eab0ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11890">issues.joomla.org/joomla-cms/11890</a>.</sub>

**Comment by BhaveshTailored** [comment]
- I have tested successfully
- screen shot 2016-09-05 at 04 07 04
- screen shot 2016-09-05 at 04 07 19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11890">issues.joomla.org/joomla-cms/11890</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 90cc89a0b393b95ef1a3379fa3709c9487eab0ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11890">issues.joomla.org/joomla-cms/11890</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11890">issues.joomla.org/joomla-cms/11890</a>.</sub>

**Comment by brianteeman** [comment]
This page in the docs should probably be updated https://docs.joomla.org/How_to_use_JDate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11890">issues.joomla.org/joomla-cms/11890</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok updated PR description

**Comment by mbabker** [comment]
Nothing there needs updating as there's no documentation about microseconds not being honored before the patch or any notes about incompatibilities with microsecond formats (which there wouldn't be any; all the formatting is done by the parent `DateTime` class, we just had a limitation that kept "now" from storing microseconds when instantiating the object).

**Pull request merged**
