### PR TITLE
[#33854] New module display strip_tags instead of escape

### PR DESCRIPTION
**Pull request by zero-24**
See: https://github.com/joomla/joomla-cms/pull/3766

This PR redo this PR: https://github.com/joomla/joomla-cms/pull/3766 by @masters1333  with the suggestions by @Kubik-Rubik @Bakual and @roland-d and some codestyle

---

As an extension developer I sometimes include HTML in the description for better presentation in the administrator. When a new module is created the HTML is displayed in the new module screen which not only looks bad but does not provide the user a brief description of the module. I will create a pull request for the changes.

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33854

### CODE REVIEW

**Comment by roland-d** [comment]
@test After downloading the example module from the joomlacode.org link, I installed the module and clicked on Extensions -> Modules. Click on New and see that the description runs out of the tooltip. After applying the patch, the tooltip is shown correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7087">issues.joomla.org/joomla-cms/7087</a>.</sub>

**Comment by jwaisner** [comment]
@test 

After testing with module and patch applied tooltip is displayed correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7087">issues.joomla.org/joomla-cms/7087</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7087">issues.joomla.org/joomla-cms/7087</a>.</sub>

**Comment by Bakual** [comment]
Merged into `staging` with https://github.com/joomla/joomla-cms/commit/0f69b1f07a09ce9071567350e8b429c0e86ec70f.
Referenced wrong PR, sorry about that.

**Comment by zero-24** [comment]
@Bakual you only commit the first commit by @masters1333 but not mine. The other fixes are not included in the commit?

**Comment by Bakual** [comment]
You mean https://github.com/joomla/joomla-cms/commit/5907423d99f5bf71aa33ee02d7e239abec6c4b1e ?

**Comment by zero-24** [comment]
Yes thanks i have not seen it :smile:

**Pull request closed without merging**
