### PR TITLE
[4.0] Remove unused file

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #25209

This file has not been used since 2010 (https://github.com/joomla/joomla-cms/commit/9c6e7214d11db5c5179b55c7026712951a16c8f5) even though its regularly been updated. Lets not waste any more time updating unused files ;)

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

Where's the facepalm reaction when you need it :)

**Comment by brianteeman** [comment]
thanks

**Comment by infograf768** [comment]
This has also to be done in 3.x and `script.php` should be updated to include it in the files to delete.

**Comment by brianteeman** [comment]
@infograf768 nothing stopping you

**Comment by infograf768** [comment]
Just finish up the job properly.
The PR should have been done towards 3.x (including script.php) and then when times come forwarded to 4.0 when @wilsonge gets to it.

**Comment by brianteeman** [comment]
Thanks for your kind words

**Comment by wilsonge** [comment]
@infograf768 there’s no hard requirement for this to be done in 3.x - stop overreacting here please

**Pull request merged**
