### PR TITLE
[4.0] Do not display the Changelog modal when changelog url does not exist for the extension

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25302

### Summary of Changes
Corrected conditional

### Testing Instructions
Install via Manager install
[plg_system_stopHitCounts-J4-1.3.0-alpha.zip](https://github.com/joomla/joomla-cms/files/3320263/plg_system_stopHitCounts-J4-1.3.0-alpha.zip)
(I modified the changelogurl in the xml of this plugin as there was a typo)

and
[fr-FR_joomla_lang_full_3.9.7v1.zip](https://github.com/joomla/joomla-cms/files/3320264/fr-FR_joomla_lang_full_3.9.7v1.zip)

Then display `administrator/index.php?option=com_installer&view=update`

Also display `administrator/index.php?option=com_installer&view=manage`
Display there the French package and then the plugin

### After patch
The French language pack does not get the Changelog button but `N/A` while the plugin does and clicking on it displays the Changelog in the modal

Screen Shot 2019-06-24 at 12 04 00

Screen Shot 2019-06-24 at 12 04 11

In the Manage view:

For the French package: the installed version is not clickable
For the plugin it is clickable and the modal is displayed with changelog informations for the installed version

### CODE REVIEW

**Comment by brianteeman** [comment]
apart from the horrendous accessibility and UI issues in view=manage which are beyond the scope of this pr this works correctly

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3bebcf19d0f1f3a0ee57123c9f911a324fbf2c1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25311">issues.joomla.org/tracker/joomla-cms/25311</a>.</sub>

**Comment by hgh-esn** [comment]
I have tested this item :white_check_mark: successfully on 3bebcf19d0f1f3a0ee57123c9f911a324fbf2c1c<br /><br />Now it works as it should. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25311">issues.joomla.org/tracker/joomla-cms/25311</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by hgh-esn** [comment]
@infograf768 

> I modified the changelogurl in the xml of this plugin as there was a typo

Can you please tell me the kind of what the typo was? 

When it was the "...../changelog(s).xml" instead of the "...../changelog.xml" then this error is changed in the source already.
You can find the latest version under: https://github.com/hgh-esn/plg_system_stopHitCounts-J4/archive/V1.3.0-alpha.zip

**Comment by infograf768** [comment]
That was the typo indeed.

**Comment by richard67** [comment]
@wilsonge Shouldn't there be added a comment in code that the not strict comparison is needed here? Otherwise I am pretty sure we will sooner or later see a PR which wants to change that back because he/she thinks strict is always better (which would be wrong in this case).

**Comment by wilsonge** [comment]
To be honest I’d always rather have strict comparisons. Looking again is there a reason we don’t use empty?

**Comment by infograf768** [comment]
@wilsonge & @richard67 
Hint: The reason I modified the conditional from
`<?php if ($item->changelogurl !== '') : ?>`
to
`<?php if ($item->changelogurl != null) : ?>`
was because I found out that the version of the en-GB package in the Manage view was still clickable. 
Same issue if I use `empty` for every item in the Manage manager.
In both cases `NULL` is not equal to `empty` or `''`

I have tested further though and I found that
`<?php if (isset($item->changelogurl)) : ?>` always work in the Manage view but NOT in the update view.

I am afraid we have to keep `!= null`

**Comment by wilsonge** [comment]
According to the php docs https://www.php.net/manual/en/function.empty.php null is considered empty. Any idea what the en-GB language pack is passing in then as a value?

**Comment by hgh-esn** [comment]
@wilsonge @infograf768 

I tested with `<?php if (!empty($item->changelogurl)) : ?>` in both views (manage and update) and for me it works. In the manage view I get the version without a link and in the update-view I get the N/A.

**Comment by hgh-esn** [comment]
@wilsonge @infograf768

Should we switch to `<?php if (!empty($item->changelogurl)) : ?>` ?

**Comment by wilsonge** [comment]
if it works then yes i'd rather use that

**Comment by infograf768** [comment]
Sorry folks, was not available. I guessed I messed up when testing !empty at the time.
Please test https://github.com/joomla/joomla-cms/pull/25363

**Pull request merged**
