### PR TITLE
[4.0] TinyMCE builder pluigin

### PR DESCRIPTION
**Pull request by brianteeman**
(there may be a better way to do this but I couldnt find it)

### Before
image

### After
image

### testing

don't forget npm i

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on 1f57e61eb2e2997fae3dd9024e45263f2929f10a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27466">issues.joomla.org/tracker/joomla-cms/27466</a>.</sub>

**Comment by jwaisner** [comment]
After patching and completing npm i, the alignment did not change as the expected result. I tested this in Firefox and Chrome.

**Comment by brianteeman** [comment]
Did you run npm i to rebuild the scripts?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1f57e61eb2e2997fae3dd9024e45263f2929f10a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27466">issues.joomla.org/tracker/joomla-cms/27466</a>.</sub>

**Comment by Quy** [comment]
@jwaisner Try clearing browser's cache.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1f57e61eb2e2997fae3dd9024e45263f2929f10a<br /><br />@brianteeman yes

@Quy just tried that and it didnt work

End result, I did a complete reset of my environment and it works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27466">issues.joomla.org/tracker/joomla-cms/27466</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27466">issues.joomla.org/tracker/joomla-cms/27466</a>.</sub>

**Comment by Fedik** [comment]
hold on, this is wrong fix :)

**Comment by Fedik** [comment]
no, sorry, ignore my previous comment

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
