### PR TITLE
Improve the language string value

### PR DESCRIPTION
**Pull request by imanickam**
Pull Request for Issue # .
It is not an issue but an improvement to the value in a language string.  Also, to be consistent with other language string MOD_LANGUAGES_FIELD_CACHING_DESC.
### Summary of Changes

Original:
COM_MODULES_FIELD_CACHING_DESC="Use the global setting for cache for the content of this module or disable caching for this module."

Revised:
COM_MODULES_FIELD_CACHING_DESC="Use the global cache setting to cache the content of this module or disable caching for this module."
### Testing Instructions

Kindly see the section DESCRIPTION
### Documentation Changes Required

None

DESCRIPTION:

The original language string reads as follows:
COM_MODULES_FIELD_CACHING_DESC="Use the global setting for cache for the content of this module or disable caching for this module."

The formation of the sentence is a bit confusing.  So, used the first sentence from the [site] language string MOD_LANGUAGES_FIELD_CACHING_DESC (shown below) that has a better clarity for the same message.
MOD_LANGUAGES_FIELD_CACHING_DESC="Use the global cache setting to cache the content of this module or disable caching for this module.<br />This should be set to 'No caching' when using Items Associations."

This is the pop-up help text for the option Caching in the tab Advanced when a module is edited.

Testing:
- Log into the back-end
- Go to Modules (Extensions => Modules)
- Select the module (instance) such as Main Menu
- Open the module (instance) for Edit
- Go to the tab Advanced
- Hover over the option Caching

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6d81c7fda6cb61f49ab28bc68c831b4ffc3bb2bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12317">issues.joomla.org/tracker/joomla-cms/12317</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6d81c7fda6cb61f49ab28bc68c831b4ffc3bb2bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12317">issues.joomla.org/tracker/joomla-cms/12317</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12317">issues.joomla.org/tracker/joomla-cms/12317</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Pull request merged**
