### PR TITLE
[4.4] Use joomla-cypress 1.1.1

### PR DESCRIPTION
**Pull request by muhme**
### Summary of Changes

_Revised after 27 commits on 7 August 2024_

The goal is to use the NPM joomla-cypress version 1.1.1 for all four active joomla-cms branches. Actual 4.4-dev uses 0.0.16; and 5.1-dev, 5.2-dev and 6.0-dev are using 1.0.3.

The following changes have already been separated from this PR and have already been merged into 4.4-dev:
* https://github.com/joomla/joomla-cms/pull/43879
* https://github.com/joomla/joomla-cms/pull/43880
* https://github.com/joomla/joomla-cms/pull/43881

Also released is NPM package `joomla-cypress` as version 1.1.1. :smile:

Change:
* The joomla-cypress version is set to ^1.1.1, so - among other things - the check for PHP warnings is activated again.
* The Cypress commands overwritten by System Tests for a faster session-based login have been removed as they are included in joomla-cypress version 1.1.1. 
* The note about overwritten commands in tests/System/README.md is deleted.

⚠️ Only NPM package `joomla-cypress` was updated, BUT there are more changes in package-lock.json. ⚠️
* Reasons are
  * Dependend packages like `cypress` and `cypress-file-upload`
  * `package.json` and `package-lock.json` were not in-sync. For example in `package.json` the version is stated as '4.4.7' and in `package-lock.json` as '4.4.6'.

Successfully retested with all System Tests passed on 7 Agust 2024 after 27 commits:
* on Intel macOS 14.5 Sonoma with PHP 8.3.9
* on Intel Windows 11 Pro with Laragon and PHP 8.1.10
* on Intel x86_64 Ubuntu 24.04 LTS Noble Numbat with PHP 8.3.6

### Testing Instructions

* Install (in using `npm ci`) and run [System Tests](https://github.com/joomla/joomla-cms/tree/4.4-dev/tests/System/README.md) w/o errors
* Check version is 1.1.1 in `node_modules/joomla-cypress/package.json`
* Check that the additional updates in the `package-lock.json` file had no effect.

### Actual result BEFORE applying this Pull Request

* System Tests is using joomla-cypress version 0.0.16 and a custom implementation of the faster session-based login
* No checks of PHP warnings
* System Tests suite is running without errors

### Expected result AFTER applying this Pull Request

* System Tests is using joomla-cypress actual version 1.1.1 and its session-based login
* PHP warning checks are activated again
* System Tests suite is running without errors

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### Up-Merging
@LadySolveig @bembelimen I will create a separate different PR for 5.1-dev

### CODE REVIEW

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 9a66d94b03e82dad0b640fde60defd2fd3b6b921<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43722">issues.joomla.org/tracker/joomla-cms/43722</a>.</sub>

**Comment by richard67** [comment]
@muhme Which command have you used to update the dependency? To me it seems this PR updates more dependencies than only joomla-cypress and it’s dependencies.

**Comment by muhme** [comment]
> @muhme Which command have you used to update the dependency? To me it seems this PR updates more dependencies than only joomla-cypress and it’s dependencies.

@richard67  `npm update` to stay up-to-date with all dependencies. Should it changed to only update joomla-cypress and it’s dependencies?

**Comment by richard67** [comment]
> Should it changed to only update joomla-cypress and it’s dependencies?

@muhme Yes. We don’t do dependency updates with patch versions. And to update all dependencies without even mentioning it in the description of this PR would not be good anyway. @laoneo csn explain and decide.

**Comment by alikon** [comment]
the https://github.com/joomla/joomla-cms/pull/43726  should avoid the need for the hack in newsfeed

**Comment by muhme** [comment]
Set to DRAFT to:
* Only update joomla-cypress and it’s dependencies
* Wait for #43726
* Test again

**Comment by muhme** [comment]
> And to update all dependencies without even mentioning it in the description of this PR would not be good anyway.

@richard67 Since the creation of this PR, the following statement has been included in the description:

⚠️ All other NPM packages are also updated with the `npm update`, see differences in package-lock.json.

The fact that all packages are updated is therefore explicitly named from my point of view and even provided with a visual eye-catcher. Also, the following instruction was added to the "Test Instructions" section since this PR was created:

* Check that there were no effects from the updates in the NPM packages.

Could it be that you haven't read the description, or am I the one who's in the wrong movie? 😃

**Comment by richard67** [comment]
@muhme Seems I need glasses 👓:-) You are right, description is ok, sorry for the noise :-)

**Comment by muhme** [comment]
Reverted to "Ready to merge", the description has been completely revised after all changes.

**Comment by laoneo** [comment]
Are the changes in the View classes really needed?

**Comment by muhme** [comment]
> Are the changes in the View classes really needed?

In 4.4-dev with joomla-cypress 0.0.16 the PHP message and warningas checks were disabled. With joomla-cypress 1.1.0 they are enabled and the System tests had 6 failures. At first there were workaround 'hacks' in the system tests to get the test suite running without errors. @alikon solved all system test 'hacks' by backporting and investigating. @alikon: Can you explain more in detail?

**Comment by laoneo** [comment]
If these are bugs in the code, we should do them separate and then they need also two human tests.

**Comment by brianteeman** [comment]
_Golden rule - solve one issue with one pull request_

**Comment by laoneo** [comment]
As the other pr's are merged, can this one be changed to ready?

**Comment by muhme** [comment]
> As the other pr's are merged, can this one be changed to ready?

No, it's intentionally set to 'Draft'. I would prefer to wait for the release of joomla-cypress 1.1.1 and then update this PR, set it on 'Ready to Merge' and create separate PR for all other branches, ok?

**Comment by muhme** [comment]
@laoneo Set to ready-for-review,  as all preconditions have been fulfilled and the PR has been adjusted and pre-tested

@alikon Could you please test?

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
