### PR TITLE
[4.0] Admin Module Help strings

### PR DESCRIPTION
**Pull request by brianteeman**
This PR corrects one constant which had been duplicated and provides values for the others.

PR for #30457

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 76bf14e216a424ddb42abc072a217ac60265ba6c<br /><br />I should have made it clearer for other testers: go to Administrator Modules and set the -Select Position- filter to _status_. Then select each module in turn and click the edit screen Help button. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by ceford** [comment]
I forgot to check the Login Support module. After applying the patch the Help screen has this in the title bar: https://help.joomla.org/proxy?keyref=Help40:JHELP_EXTENSIONS_MODULE_MANAGER_LOGIN_SUPPORT&lang=en which means the string value is not set: Extensions_Module_Manager_Login_Support - I thought that was being included in this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by brianteeman** [comment]
My fault - I made a typo - fixing it now

**Comment by ceford** [comment]
I see the string is fixed. The Help file I created has the wrong name - I need to get a translator admin to do that as I can't once once a file has been marked for translation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 40109db076169fb64ad407d932f1c3a1f11da3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 40109db076169fb64ad407d932f1c3a1f11da3cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30458">issues.joomla.org/tracker/joomla-cms/30458</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
