### PR TITLE
[5.0] @link docblock

### PR DESCRIPTION
**Pull request by brianteeman**
1. `@link` is to display a hyperlink to a URL and it should be `@see`
2. `JFilterInput` should be `InputFilter`
3.  when there is **no** use statement for this then the fqn must be used or it simply doesnt work which as we now remove unuse use statements might have increased. 
4. afaict `@see` only works when it is on a new line

There is no point in having docs if they are not correct so I propose that these `@link` are updated as above and while it might not always be necessary to use the fqn it would make it more consistent.

Code Review

### CODE REVIEW

**Comment by wilsonge** [comment]
https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlinelink.pkg.html the inline link is documented as working with other functions. Obviously it's not properly parsing in the API docs either https://api.joomla.org/cms-4/classes/Joomla-CMS-Application-CMSWebApplicationInterface.html#method_getUserStateFromRequest so maybe the FQDN is the missing part? By having it on a separate line it now is a function level `@see` rather than a parameter level one so the change here isn't ideal.

**Comment by brianteeman** [comment]
ok I can move it back to be a single line - or more likely a nested line so it isnt too long.
```
* @param   array    $urlparams  An array of safe URL parameters and their variable types.
*                               @see  \Joomla\CMS\Filter\InputFilter::clean() for valid values.
```

is that better for you.

**Comment by wilsonge** [comment]
If it works I'd prefer that. Not quite sure what's the difference between the phpdocumentor docs and what's rendering right now to be honest.

**Comment by brianteeman** [comment]
This works
image

But if there is any text before the @see then it doesnt

**Comment by HLeithner** [comment]
I merge this for now and hope this works better for phpdocumentor, thanks

**Pull request merged**
