### PR TITLE
Implementing "No Matching Results" in News Feed modal

### PR DESCRIPTION
**Pull request by brianteeman**
When creating a menu item of type single news feed the list of newsfeeds are displayed in a modal window.
When filtering and if no results, the display is just empty instead of the usual message "No Matching Results"
This patch is just implementing the message in the modal when necessary.

Thanks to @infograf768 for the code

### CODE REVIEW

**Comment by infograf768** [comment]
Ok here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7234">issues.joomla.org/joomla-cms/7234</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you, @brianteeman!

-> RTC

**Comment by zero-24** [comment]
RTC to match the status on github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7234">issues.joomla.org/joomla-cms/7234</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @brianteeman! Merged.

**Pull request closed without merging**
