### PR TITLE
Admin menu: batch process move to submenu impossible [FIX]

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #13632.

### Summary of Changes
Show menu and menu items for batch target for batch operation based on relevant client id only.

### Testing Instructions
Perform batch operations move/copy on backend custom menu items and front-end menu items. Both should work. Frontend menu items should not show when working with backend menu items and vice versa.
 
### Documentation Changes Required
None

### CODE REVIEW

**Comment by zero-24** [comment]
@izharaazmi it looks like there are unit test fails? Can you take a look? https://travis-ci.org/joomla/joomla-cms/jobs/193448159

**Comment by nikosdion** [comment]
I have successfully tested this PR. I just can't seem to convince the Joomla Issue Tracker to let me register a successful test...

I was able to move several items at once between different menu levels (top level and first sub-menu level). 

I can also confirm that I now only see the administrator menus when I'm trying to move administrator menu items.

**Comment by infograf768** [comment]
@nikosdion 
see discussion here
https://github.com/joomla/joomla-cms/pull/13739#issuecomment-275032354
and following, which, once implemented as new PR, shall solve the main UI issue.

**Comment by izharaazmi** [comment]
@infograf768 This one is a different case and not related to the other discussion. Batch move/copy etc issue raised by @nikosdion #13632 is being fixed here. So we can accept his test result here.

About the other discussion, I'll work on it.

**Comment by izharaazmi** [comment]
@zero-24 The travis failure says "No such column client_id". I think there is some problem with database mock in the tests.

**Comment by izharaazmi** [comment]
@rdeutz @infograf768  Looks like we missed this one.

**Comment by infograf768** [comment]
@izharaazmi 
Will look at it today. I also have some other stuff to look at.

**Comment by infograf768** [comment]
@izharaazmi 
Batch process of admin menus should not propose language as well as access, which can't be set anyway for these menu items.
As I noted here:
https://github.com/joomla/joomla-cms/pull/13884
these can be added in 4.0 if someone find a correct way to use these in the admin UI (out of scope imho for the 3.x series.

For now, access can be defined by the menu module itself:
Example: One can create an Access Level of type `AdminFrench` and define that access level for a specific custom User group which uses French language in back-end.

**Comment by infograf768** [comment]
It is rather easy to implement by just checking client id.

screen shot 2017-02-03 at 08 50 20

**Comment by izharaazmi** [comment]
Filter by trashed and client id = 1 was another thing of concern. Updated.
:)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4bb965dd27ad5071a029cab0ccbb4530633fc73f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13649">issues.joomla.org/tracker/joomla-cms/13649</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4bb965dd27ad5071a029cab0ccbb4530633fc73f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13649">issues.joomla.org/tracker/joomla-cms/13649</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13649">issues.joomla.org/tracker/joomla-cms/13649</a>.</sub>

**Pull request merged**
