### PR TITLE
Feature/draggable typo fixes

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

continue from https://github.com/joomla/joomla-cms/pull/29984#issuecomment-653884936
Searched for `dragable` and replaced by `draggable`

### CODE REVIEW

**Comment by ceford** [comment]
I found 29 instances before patching and 18 after - all in media / system / js which I did not rebuild. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29987">issues.joomla.org/tracker/joomla-cms/29987</a>.</sub>

**Comment by hans2103** [comment]
@ceford That is due to the fact that all files in /media are in .gitignore
I cannot create a pull request for that one. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29987">issues.joomla.org/tracker/joomla-cms/29987</a>.</sub>

**Comment by zero-24** [comment]
The media folder should not have that any more after running npm. An other way to test that would be the pre build packages there npm should have rebuild them already.

**Comment by hans2103** [comment]
@zero-24 is there anything I have to change on my PR?

**Comment by zero-24** [comment]
> @zero-24 is there anything I have to change on my PR?

No all is fine :)

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 1923fb5074363abc1f7a3b75d8079bcf1a20df13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29987">issues.joomla.org/tracker/joomla-cms/29987</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1923fb5074363abc1f7a3b75d8079bcf1a20df13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29987">issues.joomla.org/tracker/joomla-cms/29987</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29987">issues.joomla.org/tracker/joomla-cms/29987</a>.</sub>

**Comment by Quy** [comment]
Can you please update to include changes in #30094?

**Comment by hans2103** [comment]
@quy merged changes and found two new files with `dragable` instead of `draggable`.

**Comment by hans2103** [comment]
I have added the merge in commit https://github.com/hans2103/joomla-cms/commit/89c852ebf9f378c6ec90d294edd41af8a0fb5474
I added the changes of the two files in commit https://github.com/hans2103/joomla-cms/commit/e7490ea082a89f50b57c4c227fd1b17318aef595

They are in branch https://github.com/hans2103/joomla-cms/commits/feature/draggable-typo-fixes
But I don't see them in this GitHub issue. 
Any idea why?

**Comment by Quy** [comment]
They have been added to your PR here. See https://github.com/joomla/joomla-cms/pull/29987/commits/e7490ea082a89f50b57c4c227fd1b17318aef595

Thank you!!!

**Comment by hans2103** [comment]
@Quy yes! Now I see them too.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
