### PR TITLE
Load global admin language file in Editors-XTD modals

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25344 .

### Summary of Changes

Loads global administrator language file when viewing backend view in frontend (i.e. in Editors-XTD modals).

### Testing Instructions

Enable `Debug Language` in Global Configuration.
Edit an article in frontend.
In editor, use `Contact`, `Field` and `Article` buttons.

### Expected result

No untranslated strings.

### Actual result

Untranslated strings:

```
# JROOT\libraries\src\Language\Text.php

JAUTHOR_ASC="ASC"
JAUTHOR_DESC="DESC"
JCATEGORY_ASC="ASC"
JCATEGORY_DESC="DESC"
JDATE_ASC="ASC"
JDATE_DESC="DESC"
JFEATURED_ASC="ASC"
JFEATURED_DESC="DESC"
JGLOBAL_HITS_ASC="HITS ASC"
JGLOBAL_HITS_DESC="HITS DESC"
JGLOBAL_LIST_ALIAS="LIST ALIAS"
JGLOBAL_LIST_ALIAS_NOTE="LIST ALIAS NOTE"
JGLOBAL_SORT_BY="SORT BY"
JGLOBAL_TITLE_ASC="TITLE ASC"
JGLOBAL_TITLE_DESC="TITLE DESC"
JGRID_HEADING_ACCESS_ASC="HEADING ACCESS ASC"
JGRID_HEADING_ACCESS_DESC="HEADING ACCESS DESC"
JGRID_HEADING_ID_ASC="HEADING ID ASC"
JGRID_HEADING_ID_DESC="HEADING ID DESC"
JGRID_HEADING_LANGUAGE_ASC="HEADING LANGUAGE ASC"
JGRID_HEADING_LANGUAGE_DESC="HEADING LANGUAGE DESC"
JGRID_HEADING_ORDERING_ASC="HEADING ORDERING ASC"
JGRID_HEADING_ORDERING_DESC="HEADING ORDERING DESC"
JSTATUS_ASC="ASC"
JSTATUS_DESC="DESC"
```

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
IMHO, this is not the solution. 
We may have different values in site xx-XX.ini and admin xx-XX.ini for the same constant.

The only correct solution is to add all missing lang strings in frontend (I know it is a pain).

**Comment by infograf768** [comment]
Hmm
I tested. It looks that there is no impact doing it this way for these modals.
```
**Loaded** : JROOT/language/en-GB/en-GB.ini
**Loaded** : JROOT/administrator/language/en-GB/en-GB.ini
```
Only possible issue would be for TTs providing only frontend translation.
Any way to change the loading order?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ff7c1f6c729714bec3b7d7e55fa7f052ffe0299c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25472">issues.joomla.org/tracker/joomla-cms/25472</a>.</sub>

**Comment by SharkyKZ** [comment]
>Any way to change the loading order?

I don't think so. Global language file is first loaded very early.

**Comment by infograf768** [comment]
Re-started drone

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ff7c1f6c729714bec3b7d7e55fa7f052ffe0299c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25472">issues.joomla.org/tracker/joomla-cms/25472</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25472">issues.joomla.org/tracker/joomla-cms/25472</a>.</sub>

**Comment by brianteeman** [comment]
> IMHO, this is not the solution.
> We may have different values in site xx-XX.ini and admin xx-XX.ini for the same constant.
> 
> The only correct solution is to add all missing lang strings in frontend (I know it is a pain).

agree

**Comment by infograf768** [comment]
@SharkyKZ 
will make proper PR to include the strings in frontend. That would be for 3.9.10 as it is too late for 3.9.9
At the same time I will check why was added loading the backend main ini in https://github.com/joomla/joomla-cms/pull/12321 . May need some help if the proper PR does not take care of it..

**Comment by infograf768** [comment]
We do not need to load admin main ini when the strings are added in frontend.
My patch will therefore delete these calls.

**Comment by infograf768** [comment]
Maintainers have decided to rather add the strings.
See and test https://github.com/joomla/joomla-cms/pull/25475

Thanks. Closing this one.

**Pull request closed without merging**
