### PR TITLE
[5.1] CLI: Core Update - improve output

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The output of the CLI command to update the Joomla core currently is producing very bad output. The way the progressbar is used, all output is more or less deleted right away again and the progressbar is also not really very progressy...

This PR changes the output to keep all messages which were previously written on the screen and to actually display a progressbar.

### Testing Instructions
1. See how the core update on the CLI looks right now.
2. Apply the changes from this PR.
3. Change the version in `/libraries/src/Version.php to a lower version like 5.0.0.
4. Since your DB structure will be a mismatch to our perceived version and the update, we have to comment out the schema check on line 195 of `libraries/src/Console/UpdateCoreCommand.php` and add `$error = 0;` in the line below.
5. Run `php cli/joomla.php core:update`

### Actual result BEFORE applying this Pull Request
Output is really not helpfull.

### Expected result AFTER applying this Pull Request
Output is a lot more verbose.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a3c7358b1391eaea8061e04ded5727049231df47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42601">issues.joomla.org/tracker/joomla-cms/42601</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on a3c7358b1391eaea8061e04ded5727049231df47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42601">issues.joomla.org/tracker/joomla-cms/42601</a>.</sub>

**Comment by dautrich** [comment]
**Before application of the patch:**
grafik

**Change to UpdateCoreCommand.php:**
grafik
Remark: I suppose item 4 in your Testing Instructions should read  `$errors = 0`

**After application of the patch:**
grafik

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42601">issues.joomla.org/tracker/joomla-cms/42601</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
