### PR TITLE
[4.0] Cassiopeia description post bs5

### PR DESCRIPTION
**Pull request by brianteeman**
Code review

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4080fb05e06c5d23a9d93d118c150a33778d2161<br /><br />Tested successfully in Beta7-dev of 23 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32112">issues.joomla.org/tracker/joomla-cms/32112</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4080fb05e06c5d23a9d93d118c150a33778d2161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32112">issues.joomla.org/tracker/joomla-cms/32112</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32112">issues.joomla.org/tracker/joomla-cms/32112</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
