### PR TITLE
[5.1] Reset the cached layout data during FormField setup()

### PR DESCRIPTION
**Pull request by sousa9g**
### Summary of Changes

Joomla 5.1 added a new method to cache the form field layout data (collectLayoutData()). While it is great for performance, it is now impossible to reset the cached layout data.

In the FormField setup(). The input and labels are cleared:

$this->input = null;
$this->label = null;

However with the introductions of memory caching layout data, those lines don't work anymore, as the input is always rendered using the cached layout data.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on fd1f6c513e0a3f272b8aa44f5be83bde90ba99e4<br /><br />On review. It doing the same as $this->input = null; $this->label = null;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43562">issues.joomla.org/tracker/joomla-cms/43562</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on fd1f6c513e0a3f272b8aa44f5be83bde90ba99e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43562">issues.joomla.org/tracker/joomla-cms/43562</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43562">issues.joomla.org/tracker/joomla-cms/43562</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @sousa9g 🚀  and also for review and testing @Fedik and @viocassel 💚

**Pull request merged**
