### PR TITLE
Fix various router issues related to com_content

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Fixes a variety of bugs in the new 3.7 router (I was specifically testing com_content but this is also more general - as I've also made the same patches to contact and newsfeeds)

Thanks to @mbabker for the help debugging some of these issues on Sunday!!

### Testing Instructions
Install staging (or latest version of Joomla 3.7.0 - currently alpha 2) with no sample data.

In the article manager create 3 articles
1. Article 1 should be featured and uncategorised
2. Article 2 should not be featured and also uncategorised
3. Article 3 should be in a secondary category
4. Create a child menu item of the featured home page for article 1
5. Create a category list menu item for the secondary category as a top level menu item

Ensure that articles 1-3 all have links to each other. Note importantly here article 2 has no menu item and it's category has no menu item. This is running through lots of fallback behaviour and where bugs start to creep in.

Ensure you've turned on modern URL routing and Remove ID's for com_content

Firstly go to your single item menu item for article
1. Try navigating to article 2
2. Note that the article cannot be accessed.
3. Apply patch.
4. You can now access the article.
5. Revert Patch
6. Go to the category list view you create and go into article 3
7. Go to article 2
8. Note you go back to to the category 2 view and not article 2.
9. Apply patch
10. You go correctly to article 2

I think this also should help with the video described in This might help with issue https://github.com/joomla/joomla-cms/pull/13747 (but I only did limited testing as I wasn't deliberately trying to fix that bug)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
> Install Joomla 3.6.5 alpha 2

3.7.0-beta1?

**Comment by wilsonge** [comment]
There's no beta 1 but yeah I'll take 3.7 alpha 2 or staging branch

**Comment by franz-wohlkoenig** [comment]
> Go to the category list view you create and go into article 3
> Go to article 2

Cant get navigation show to got from article 3 to article 2.

**Comment by wilsonge** [comment]
@franz-wohlkoenig can you give it another go please. Looks like there was a bug with no id's enabled i had missed

**Comment by franz-wohlkoenig** [comment]
Article 1 name: feat-uncat-01
Article 2 name: not-feat-uncat-02
Article 3 name: not-feat-uncat-2ndcat-03
1. Open "feat-uncat-01" in single item menu item: Works
2. Try navigating to article "not-feat-uncat-02" by click on Navigation-Button "Next": `404 Article not found`. Request-Url: `/index.php/home/feat-uncat-01/article/not-feat-uncat-02`

**Comment by AlexRed** [comment]
ok, patch work, now I can open the Article 2.
But the link URL to Article 2 in the homepage link inside the Article 1 is not SEO: "/?view=article&id=2"
also the link URL to Article 2 in the "Latest Articles" module is not SEO.
The link URL to Article 2 inside the Article 3 is ok, also inside the Article 1 (directly, not from the homepage) is ok.

The 404 error also do not work: https://issues.joomla.org/tracker/joomla-cms/12822
and also "List All Categories" menu item type do not work: https://issues.joomla.org/tracker/joomla-cms/13101

**Comment by wilsonge** [comment]
@franz-wohlkoenig I can't replicate that on my setup a url `http://localhost/~george/joomla-cms/index.php/home/test01-menu/article/2-test02` correctly parses for me

**Comment by franz-wohlkoenig** [comment]
@wilsonge tested on macos sierra also on win7 on different Browser (ff, chrome, safari) > same Result.

**Comment by wilsonge** [comment]
I'm on chrome on sierra and have tested in chrome + safari + firefox with successful results :) Can I see a screenshot of your article and menu manager please? I'm sure we must be doing something different somewhere - just can't work out what :)

**Comment by franz-wohlkoenig** [comment]
Not shown 2nd Article:
article
Menu-Manager:
menu-items

**Comment by cpfeifer** [comment]
Thanks for addressing these issues, I was about to add this in then I found this PR :) 

I'm having the same issue with Article 2, everything else is good.

I navigate to my article 1 menu sub-item article with links to articles 2 & 3. When I navigate to Article 2 without the patch, it reloads the Article 1 page - similar to the Article 3 cat list scenario. With the patch applied I get a 404 error.

Everything else works as expected for me.

**Comment by wilsonge** [comment]
I still can't replicate the issues you guys have. Here is my setup. Going between any combination of articles 1, 2 and 3 things 'work' there are definitely some URLs that don't work use their proper SEF link yet. But they all go to the right place for me. What have you guys set up differently?

Category's
image

Articles
image

Menus
image

**Comment by cpfeifer** [comment]
I don't see any differences in my setup, other than I already had sample data in my install and I built this in rather than re-installing. Maybe can you see something I'm missing.

Screenshots of Menu and Articles
menus

articles

I'm using the Sample Data Category for Article 3 and the other two are Uncategorized.

When I go to the featured-test / Single Article and click on the link to article 2 (inserted through the editor article link button), it gives me a 404 with this URL:
`featured-test/single-article-test/article/article-url-testing-2`

Maybe that helps? It seems like this should work even if there is a variance in the testing method. Or maybe I'm missing something, it wouldn't be the first time that happened :)

**Comment by wilsonge** [comment]
It looks ok :/ Can i get access to one of you two over skype or something so I can try and debug on your setups?

**Comment by cpfeifer** [comment]
Give me 10 minutes and I'll ping you

**Comment by franz-wohlkoenig** [comment]
@wilsonge where to send login?

**Comment by wilsonge** [comment]
It's fine. Having discussed this with Cliff I've figured out that on my small setup of 3 articles and 2 categories this worked. But this is no good for real life sites. There's several fundamental issues.

**Pull request closed without merging**
