### PR TITLE
com_templates override toggles

### PR DESCRIPTION
**Pull request by brianteeman**
A small tweak to the text to improve clarity

PR for #36330

### Before
image

### After
image

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 0f10789c43b3709501492e42f30bf773547a1b4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38463">issues.joomla.org/tracker/joomla-cms/38463</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0f10789c43b3709501492e42f30bf773547a1b4e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38463">issues.joomla.org/tracker/joomla-cms/38463</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38463">issues.joomla.org/tracker/joomla-cms/38463</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
