### PR TITLE
[4.0] Multilingual status

### PR DESCRIPTION
**Pull request by brianteeman**
This query was duplicated

SELECT `enabled`
FROM `tk7kk_extensions`
WHERE `type` = 'module' AND `element` = 'mod_multilangstatus'

### Test
Enable debug

### CODE REVIEW

**Comment by infograf768** [comment]
Contrary to the intention of the original coder to display the multilingual status automatically ONLY when multilang is enabled, this patch displays it also when the site is monolingual.

That could be discussed indeed, but this PR also breaks what was added in https://github.com/joomla/joomla-cms/commit/5005838fa36b017fe898482075c64b32926d773d#diff-870be7804424d0f44d0e7e48901a743f i.e. setting the module to Published in the Modules Manager page when the module exists and is enabled in the site.

**Comment by infograf768** [comment]
So, basically, if it is decided to display the module ALSO when the site is monolingual, it is necessary to take off `&& Multilanguage::isEnabled() ` from the code below in the tmpl.
```
		<?php if (class_exists(MultilangstatusAdminHelperMultilangstatusAdminHelperclass) && Multilanguage::isEnabled() && MultilangstatusAdminHelper::isEnabled()) : ?>
			<?php $module = ModuleHelper::getModule('mod_multilangstatus'); ?>
			<?php echo ModuleHelper::renderModule($module); ?>
		<?php endif; ?>
```
AND modify the MultilangstatusAdminHelper::publish method to always publish it if present  to display the module in both cases (multilang on and off).

IN that case we can get rid of the double query by checking that `MultilangstatusAdminHelper::getState () == 1` instead of
`class_exists(MultilangstatusAdminHelperMultilangstatusAdminHelperclass) && MultilangstatusAdminHelper::isEnabled())`

**Comment by infograf768** [comment]
To avoid the double query we could do this if we want to only show the module when multilingual is on).
I commented the code to take off and added in the conditional
```
// Check if the multilangstatus module is present in the site
//if (class_exists(MultilangstatusAdminHelper::class) && MultilangstatusAdminHelper::isEnabled())
//{
	// Publish/Unpublish the module if it exists in the modules table
	// depending on the status of the languagefilter
	//MultilangstatusAdminHelper::publish();
//}
?>
<div class="ml-auto">
	<ul class="nav text-center">
		<?php if (class_exists(MultilangstatusAdminHelper::class) && MultilangstatusAdminHelper::isEnabled()) : ?>
			<?php if (Multilanguage::isEnabled()) : ?>
				<?php MultilangstatusAdminHelper::publish(); ?>
				<?php $module = ModuleHelper::getModule('mod_multilangstatus'); ?>
				<?php echo ModuleHelper::renderModule($module); ?>
			<?php else : ?>
				<?php MultilangstatusAdminHelper::publish(); ?>
			<?php endif; ?>
		<?php endif; ?>
```

**Comment by infograf768** [comment]
Would you like me to do a new PR (just to solve the double query) with the code I posted above, or do you take care of it?

**Comment by laoneo** [comment]
Better to do a new pr.

**Comment by infograf768** [comment]
will do.

**Comment by infograf768** [comment]
done:
https://github.com/joomla/joomla-cms/pull/21906

**Pull request closed without merging**
