### PR TITLE
Update the postinstall to the latest news on Joomla 4.0

### LINKED ISSUE #17547: 4.0 Postinstall Check Update
Per yesterday's announcement, 4.0 will now require PHP 7.  The postinstall message check needs to be updated in 3.x for this.

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Update the postinstall to the latest news on Joomla 4.0 for PHP fixes #17547

### Testing Instructions

Install Joomla on an non php 7 install

### Expected result

Postinstall poping up

### Actual result

postinstall come only when you are on lower than 5.5.9

### Documentation Changes Required

New minimum as of https://developer.joomla.org/news/704-looking-forward-with-joomla-4.html

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Review by wilsonge — APPROVED** [review]

**Comment by brianteeman** [comment]
Do we need the comment about ext/mysql? Isn't that completely removed in PHP 7

**Comment by mbabker** [comment]
It's correct.  It's saying `ext/mysql` support is dropped and to use MySQL you have to use one of the other adapters.

**Comment by brianteeman** [comment]
OK

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 714649619d21439317e777dcbebffd4072207164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17549">issues.joomla.org/tracker/joomla-cms/17549</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e9f31bcc8a5ad2cf0f89f5f168c563c6820f2c1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17549">issues.joomla.org/tracker/joomla-cms/17549</a>.</sub>

**Comment by CiverBlack** [comment]
I have tested this item :white_check_mark: successfully on e9f31bcc8a5ad2cf0f89f5f168c563c6820f2c1e<br /><br />I tried the public release and could reproduce the problem. With the patched version it works.
@iCampus
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17549">issues.joomla.org/tracker/joomla-cms/17549</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
