### PR TITLE
s/this/that

### PR DESCRIPTION
**Pull request by PhilETaylor**
I have SKIPPED **anything** that would, in the slightest, prove controversial 

This is not just spelling mistakes, there are a lot of typos fixed too...

All changes are in COMMENTS ONLY there are ZERO PHP/JS Code changes.

`178 changed files with 249 additions and 249 deletions`

THIS IS NOT AN AUTOMATED SEARCH AND REPLACE - I have humanly eyeballed each line and manually changed each spelling using the contextual menu in phpStorm, choosing the appropriate spelling from its recommendations, or manually making the typo fix myself.

Top of the list is probably `overriden` = `overridden` ;-) 

```
administrator/components/com_admin/models/profile.php
administrator/components/com_admin/models/sysinfo.php
administrator/components/com_banners/models/clients.php
administrator/components/com_banners/views/banner/view.html.php
administrator/components/com_config/model/application.php
administrator/components/com_contact/controllers/contact.php
administrator/components/com_content/controllers/article.php
administrator/components/com_content/models/article.php
administrator/components/com_installer/models/database.php
administrator/components/com_installer/models/extension.php
administrator/components/com_joomlaupdate/restore_finalisation.php
administrator/components/com_languages/models/installed.php
administrator/components/com_languages/models/strings.php
administrator/components/com_media/controllers/file.json.php
administrator/components/com_media/controllers/file.php
administrator/components/com_menus/models/item.php
administrator/components/com_menus/models/menus.php
administrator/components/com_menus/views/menutypes/view.html.php
administrator/components/com_modules/models/modules.php
administrator/components/com_search/models/searches.php
administrator/components/com_templates/models/style.php
administrator/components/com_users/models/group.php
administrator/components/com_users/models/level.php
administrator/components/com_users/models/mail.php
administrator/components/com_users/models/user.php
administrator/templates/hathor/component.php
administrator/templates/hathor/css/template_rtl.css
build/phpcs/Joomla/Sniffs/Commenting/FileCommentSniff.php
build/phpcs/Joomla/Sniffs/Commenting/FunctionCommentSniff.php
components/com_config/controller/helper.php
components/com_config/model/templates.php
components/com_contact/views/category/view.feed.php
components/com_contact/views/contact/view.html.php
components/com_content/controllers/article.php
components/com_content/models/articles.php
components/com_content/views/category/view.feed.php
components/com_users/models/login.php
components/com_users/models/profile.php
components/com_users/models/registration.php
components/com_users/models/remind.php
components/com_users/models/reset.php
layouts/plugins/editors/tinymce/field/tinymcebuilder.php
layouts/plugins/system/privacyconsent/label.php
layouts/plugins/system/privacyconsent/message.php
libraries/cms.php
libraries/cms/html/select.php
libraries/fof/autoloader/component.php
libraries/fof/config/domain/interface.php
libraries/fof/config/provider.php
libraries/fof/database/driver.php
libraries/fof/database/driver/pdomysql.php
libraries/fof/database/driver/postgresql.php
libraries/fof/dispatcher/dispatcher.php
libraries/fof/form/header/model.php
libraries/fof/input/input.php
libraries/fof/input/jinput/files.php
libraries/fof/integration/joomla/platform.php
libraries/fof/less/formatter/classic.php
libraries/fof/model/behavior/access.php
libraries/fof/model/behavior/enabled.php
libraries/fof/model/behavior/language.php
libraries/fof/model/behavior/private.php
libraries/fof/model/model.php
libraries/fof/platform/interface.php
libraries/fof/platform/platform.php
libraries/fof/table/behavior/assets.php
libraries/fof/table/behavior/tags.php
libraries/fof/template/utils.php
libraries/fof/toolbar/toolbar.php
libraries/fof/utils/update/joomla.php
libraries/fof/view/form.php
libraries/fof/view/html.php
libraries/fof/view/raw.php
libraries/fof/view/view.php
libraries/joomla/archive/zip.php
libraries/joomla/database/driver.php
libraries/joomla/database/driver/pgsql.php
libraries/joomla/database/driver/postgresql.php
libraries/joomla/database/query/mysqli.php
libraries/joomla/database/query/pdo.php
libraries/joomla/database/query/postgresql.php
libraries/joomla/database/query/sqlsrv.php
libraries/joomla/facebook/user.php
libraries/joomla/form/fields/checkboxes.php
libraries/joomla/form/fields/repeatable.php
libraries/joomla/github/object.php
libraries/joomla/github/package/gists.php
libraries/joomla/github/package/issues.php
libraries/joomla/github/package/issues/assignees.php
libraries/joomla/github/package/pulls.php
libraries/joomla/github/package/users.php
libraries/joomla/github/refs.php
libraries/joomla/linkedin/communications.php
libraries/joomla/observable/interface.php
libraries/joomla/observer/interface.php
libraries/joomla/observer/updater.php
libraries/joomla/observer/updater/interface.php
libraries/joomla/twitter/object.php
libraries/src/Cache/Controller/CallbackController.php
libraries/src/Cache/Controller/PageController.php
libraries/src/Categories/CategoryNode.php
libraries/src/Component/ComponentHelper.php
libraries/src/Crypt/Cipher/BlowfishCipher.php
libraries/src/Crypt/Cipher/McryptCipher.php
libraries/src/Crypt/Cipher/Rijndael256Cipher.php
libraries/src/Helper/TagsHelper.php
libraries/src/Http/Transport/SocketTransport.php
libraries/src/Http/Transport/StreamTransport.php
libraries/src/Installer/Adapter/ModuleAdapter.php
libraries/src/Installer/InstallerHelper.php
libraries/src/Language/Associations.php
libraries/src/Language/Multilanguage.php
libraries/src/Layout/FileLayout.php
libraries/src/MVC/Model/AdminModel.php
libraries/src/MVC/Model/BaseDatabaseModel.php
libraries/src/MVC/View/CategoryFeedView.php
libraries/src/Router/SiteRouter.php
libraries/src/Schema/ChangeItem/MysqlChangeItem.php
libraries/src/Session/Session.php
libraries/src/Table/Observer/Tags.php
libraries/src/Toolbar/Button/CustomButton.php
modules/mod_articles_category/helper.php
plugins/actionlog/joomla/joomla.php
plugins/authentication/cookie/cookie.php
plugins/editors-xtd/article/article.php
plugins/editors-xtd/contact/contact.php
plugins/editors-xtd/menu/menu.php
plugins/editors-xtd/pagebreak/pagebreak.php
plugins/finder/newsfeeds/newsfeeds.php
plugins/search/content/content.php
plugins/system/actionlogs/actionlogs.php
plugins/system/logrotation/logrotation.php
plugins/system/privacyconsent/privacyconsent.php
plugins/system/sef/sef.php
plugins/system/updatenotification/updatenotification.php
plugins/twofactorauth/totp/totp.php
plugins/twofactorauth/yubikey/yubikey.php
plugins/user/contactcreator/contactcreator.php
plugins/user/profile/profile.php
templates/beez3/css/nature.css
templates/beez3/css/personal.css
templates/beez3/css/turq.less
templates/beez3/html/com_content/archive/default.php
templates/beez3/html/com_content/archive/default_items.php
tests/unit/core/case/case.php
tests/unit/core/case/database.php
tests/unit/core/mock/input.php
tests/unit/core/reflection.php
tests/unit/suites/database/driver/postgresql/JDatabaseQueryPostgresqlTest.php
tests/unit/suites/libraries/cms/application/JApplicationCmsTest.php
tests/unit/suites/libraries/cms/helper/JHelperContentTest.php
tests/unit/suites/libraries/cms/installer/JInstallerAdapterTest.php
tests/unit/suites/libraries/joomla/JLoaderTest.php
tests/unit/suites/libraries/joomla/access/JAccessRulesTest.php
tests/unit/suites/libraries/joomla/application/JApplicationCliTest.php
tests/unit/suites/libraries/joomla/application/JApplicationWebTest.php
tests/unit/suites/libraries/joomla/application/web/router/JApplicationWebRouterRestTest.php
tests/unit/suites/libraries/joomla/database/JDatabaseQueryTest.php
tests/unit/suites/libraries/joomla/filesystem/JFilesystemPatcherTest.php
tests/unit/suites/libraries/joomla/form/JFormTest.php
tests/unit/suites/libraries/joomla/form/fields/JFormFieldTextareaTest.php
tests/unit/suites/libraries/joomla/image/JImageTest.php
tests/unit/suites/libraries/joomla/keychain/JKeychainTest.php
tests/unit/suites/libraries/joomla/language/JLanguageHelperTest.php
tests/unit/suites/libraries/joomla/language/JLanguageTest.php
tests/unit/suites/libraries/joomla/linkedin/JLinkedinTest.php
tests/unit/suites/libraries/joomla/mediawiki/stubs/JMediawikiObjectMock.php
tests/unit/suites/libraries/joomla/model/JModelBaseTest.php
tests/unit/suites/libraries/joomla/model/JModelDatabaseTest.php
tests/unit/suites/libraries/joomla/oauth1/stubs/JOAuth1ClientInspector.php
tests/unit/suites/libraries/joomla/openstreetmap/JOpenstreetmapElementsTest.php
tests/unit/suites/libraries/joomla/openstreetmap/JOpenstreetmapTest.php
tests/unit/suites/libraries/joomla/twitter/JTwitterTest.php
tests/unit/suites/libraries/joomla/user/JUserTest.php
tests/unit/suites/libraries/joomla/utilities/JArrayHelperTest.php
tests/unit/suites/libraries/legacy/controller/JControllerLegacyTest.php
tests/unit/suites/libraries/legacy/model/JModelListTest.php
tests/unit/suites/plugins/content/emailcloak/PlgContentEmailcloakTest.php
```

### CODE REVIEW

**Comment by brianteeman** [comment]
all looks good. Not sure if the agreement allows updating the fof files

**Comment by PhilETaylor** [comment]
Well luckily for @nikosdion I was just writing him a personal email to point him here...

**Comment by toivo** [comment]
@PhilETaylor  Well done, found only this from the diff:
-	 * @param   array   $dataArray  Array with data tha may contain private informati
+	 * @param   array   $dataArray  Array with data tha may contain private information<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29352">issues.joomla.org/tracker/joomla-cms/29352</a>.</sub>

**Comment by nikosdion** [comment]
I do not object to only typos in comments being addressed.

**Comment by HLeithner** [comment]
@PhilETaylor Thanks for you work, could you please add 

`*  @note	This file has been modified by the Joomla! Project and no longer reflects the original work of its author.`

to the top of all FOF files or remove the changes if you don't want to do this?

Thanks, this PR is planed for 3.9.20

**Comment by PhilETaylor** [comment]
@toivo Fixed. I was sure to miss one. There will probably be other spelling mistakes I did not find. Like I said this was a manual effort in phpStorm and not a search and replace and therefore not all instances will be found/replaced. see https://github.com/joomla/joomla-cms/pull/29352/commits/28f33f8223f2b6e666af34297c01e27eb3855d83

@HLeithner FOF docblocks of the modified files have been cleaned up, and `@note` added where needed except one file that originated in Joomla, and was forked to fof leaving only the OSM header. see https://github.com/joomla/joomla-cms/pull/29352/commits/b0dc855b3c5ec7acc67ad367527ca42af9632632

**Comment by PhilETaylor** [comment]
So this is ready for merging right?

**Comment by HLeithner** [comment]
One cs issue left https://ci.joomla.org/joomla/joomla-cms/33136/1/2

**Comment by PhilETaylor** [comment]
ah the old Tabs verses Spaces debate....

**Comment by PhilETaylor** [comment]
Strange as phpStorm reports them as tabs, and Github sees them as spaces... 

Anyway, edited using GitHub Web Interface and that seems to have fixed the one line in the 178 files in this commit that was being complained about

**Comment by PhilETaylor** [comment]
> All checks have passed

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
