### PR TITLE
Correct english as noted in the original PR

### PR DESCRIPTION
**Pull request by Bakual**
Improving language in CONTRIBUTING.md

### Summary of Changes
"only", not "just" as mentioned by @mbabker in https://github.com/joomla/joomla-cms/pull/13782#discussion_r98294188

### Testing Instructions
Review as it's only a documentation file

#### Disclaimer
Work is done by @brianteeman

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 3396a28a1e3eee317718eea857b56be6338a4243<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14274">issues.joomla.org/tracker/joomla-cms/14274</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 3396a28a1e3eee317718eea857b56be6338a4243<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14274">issues.joomla.org/tracker/joomla-cms/14274</a>.</sub>

**Comment by Hils** [comment]
Thank you for changing this Thomas - it is correct en-GB now :)

**Comment by Bakual** [comment]
Thank you goes to Brian, it's his branch :smile:

**Pull request merged**
