### PR TITLE
Wrong error message

### PR DESCRIPTION
**Pull request by demis-palma**
## Description

Immediately after checking the existance of a file, in case the file doesn't exist, the error mesage JLIB_INSTALLER_ERROR_SQL_ERROR is shown, while it should be JLIB_INSTALLER_ERROR_SQL_FILENOTFOUND
## How to reproduce

Use any component which makes use of SQL statements after its installation.
Edit the xml descriptor of the installation package 
`<extension type="component" version="3.0" method="upgrade">
...`
There search and remove the sql section
`<folder>sql</folder>`

but take care to keep the following section
`<install>
    <sql><file driver="mysql" charset="utf8">sql/install.mysql.utf8.sql</file></sql>
</install>`

Doing this way, the sql directory won't be copied from the installation package to the destination folder.
Proceed installing the component
All the extension files will be copied to the destination folder, except for the sql directory.
At this point Joomla will try to run the sql statements from the destination folder, but the file does not exist, and the following message will be displayed:

_Warning - JInstaller: :Install: Error SQL DB function reports no errors._

The error message used has been probably blindly copied from 30 lines below, where it is actually used in response to ($db->execute) failure.

After applying the proposed patch, the error message becomes:

_Warning - JInstaller: :Install: SQL File not found /.../component-dir/sql/install.mysql.utf8.sql_

In addition, the string id JLIB_INSTALLER_ERROR_SQL_FILENOTFOUND is not used anywhere else in the project, which confirms that it must had been created to be used here.

### CODE REVIEW

**Comment by OctavianC** [comment]
Just tested this and behaves properly.
- Error message before: `JInstaller: :Install: Error SQL DB function reports no errors.`
- After patch: `JInstaller: :Install: SQL File not found D:\xampp\htdocs\test\administrator\components\com_rsticketspro/sql/test.sql`

I've just discovered the bug, tried to create a pull request but noticed that it has already been reported and a fix proposed. Why isn't this RTC? :)

**Comment by mbabker** [comment]
A lack of testing basically.  Usually items aren't merged without two good tests.

**Comment by demis-palma** [comment]
This PR has just been labelled "Language Change" by joomla-cms-bot, but it does not require any language change, since it uses strings already present.

**Comment by brianteeman** [comment]
That's because the pull request removes two strings

**Comment by brianteeman** [comment]
I know it seems daft but we normally do not remove strings from the core in case extensions are using them.

**Comment by demis-palma** [comment]
Thanks Brian, the string removal belongs to a different fix which I can't send because I forgot to switch to a different branch.
PR restored to the original state: no string removal involved.

**Comment by zero-24** [comment]
>PR restored to the original state: no string removal involved.

label removed thanks :smile:

**Comment by bertmert** [comment]
@test Success.

Tested with com_joomgallery_3_1_1_stable
Before:
```
Warning
JInstaller: :Install: Error SQL DB function reports no errors.
Extension Install: SQL error processing query: DB function reports no errors.
```

After:
```
Warning
JInstaller: :Install: SQL File not found /path/to/joomla/administrator/components/com_joomgallery/sql/install.mysql.utf8.sql
Extension Install: SQL error processing query: DB function reports no errors.
```

**Comment by zero-24** [comment]
As @demis-palma reverted all changes since the test by @OctavianC and we get a seccond successful test by @bertmert i set this here to RTC. Thanks for testing and coding :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6559">issues.joomla.org/joomla-cms/6559</a>.</sub>

**Comment by wilsonge** [comment]
Merged into staging - thanks!

**Pull request closed without merging**
