### PR TITLE
Changed the default value to type double

### PR DESCRIPTION
**Pull request by Quy**
Redo of PR #15743

The PHPdoc declares the variable as "double"
`@param double $startTime`
but the method initialises its default value with an "integer" instead
`$startTime = 0`

### Summary of Changes
Changed the default value to type double

### Testing Instructions
Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aa5cc84199478fb570dd4763878ecf1a1e1f231b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24971">issues.joomla.org/tracker/joomla-cms/24971</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on aa5cc84199478fb570dd4763878ecf1a1e1f231b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24971">issues.joomla.org/tracker/joomla-cms/24971</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24971">issues.joomla.org/tracker/joomla-cms/24971</a>.</sub>

**Comment by richard67** [comment]
@HLeithner I think this should me merged.

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
