### PR TITLE
Change back data type of template styles home column in db

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #25482 .

### Summary of Changes

Change back data type of column `home` to string (type depending on db type) in table `#__template_styles`, because it can not only hold values '0' or '1' but also language code, e.g. 'de-DE', if the template style is a default for a particular language.

This is an undo of PR #24595 .

### Testing Instructions

4 different tests.

1. Update Joomla 3.9.8 site to a patched 3.9.9 package with this PR and the version number patched to 3.10. PLEASE DO THIS ONLY ON TESTING SITE, NOT ON LIFE SITE.
You can find such a package here:
[https://test5.richard-fath.de/Joomla_3.9.10-dev-Update_Package_pr-25484.zip](https://test5.richard-fath.de/Joomla_3.9.10-dev-Update_Package_pr-25484.zip).

2. Do the same with a 3.9.9: Update it to my patched package.

3. On a 3.9.8, apply this PR e.g. with patch tester, then go to "Extensions -> Manage -> Database". Use the "Fix" button to apply the changes in the new schema updates from this PR.

4. Do the same as in step 3 but on a 3.9.9

### Expected result

In all cases the update or schema fix succeeds, and issue #25482 is solved.

### Actual result

See issue #25482 .

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by mbabker** [comment]
For the record, the fact you have to rename the index is exactly why the bug in the schema parser needs to be fixed.  You should not have to version suffix table indexes.

**Comment by richard67** [comment]
@mbabker Yes, I know. But it is not a bug, it is missing by design. That's why I did not fix it yet, it is a bigger thing.

**Comment by richard67** [comment]
Attention, PR is not ready yet, changes in joomla.sql are missing. But you can already apply the PR and run the DB fixer for testing the schema updates are working.

**Comment by mbabker** [comment]
It's a bug if it's missing this critical of a feature 😉

(And yeah, I realize fixing the database code is a lot more effort than it's sometimes worth, but still have to make it known I hate hacky fixes to work around a deeper underlying problem)

**Comment by HLeithner** [comment]
ALTER TABLE `#__template_styles` DROP INDEX `idx_client_id_home`; may fail because the index doesn't exists on direct update

**Comment by richard67** [comment]
@mbabker I absolutely agree with you about the issue, but it is not just a bug fix. It needs a redesign of the schema checker. That's why we now have to use the ugly hacks, we don't have the time now to fix the schema checker.

**Comment by richard67** [comment]
@HLeithner Not sure. For postgres I have used "IF EXISTS", that should be ok. For the other DB types we don't have that yet. I have to check that.

**Comment by richard67** [comment]
Hint for testers: Link to modified update package in description has changed, package has been updated by latest changes on this PR.

**Comment by simbus82** [comment]
> @HLeithner Not sure. For postgres I have used "IF EXISTS", that should be ok. For the other DB types we don't have that yet. I have to check that.

Something like this for MySQL can help?
(only some new versions of mysql like MariaDB supports IF EXIST for indexes)

```
SET @idxexist := (SELECT COUNT(*) FROM information_schema.statistics WHERE table_name = '#__template_styles' AND index_name = 'idx_client_id_home' AND table_schema = database());
SET @sqlrmidx:= if( @idxexist > 0, 'SELECT ''INFO: Index already exists.''', 'ALTER TABLE #__template_styles DROP INDEX idx_client_id_home');
PREPARE rmidx FROM @sqlrmidx;
EXECUTE rmidx;
```

**Comment by richard67** [comment]
@simbus82 That would work for the installer when doing the update, but the database schema checker would be confused. we found other way. pr is ready for being tested.

**Comment by richard67** [comment]
@alikon @twister65 Can you test this PR for postgres? I gotta go sleep now.

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 71252b7c3ccddb806f652ddee0968c3a0c615f9d<br /><br />On a mariadb setup this worked for me on the downloads.joomla.org backup I have (which experienced this issue) going from both 3.9.8 backup to this proposed 3.9.10 directly and also going from 3.9.8 to 3.9.9 and then to the proposed 3.9.10. In both cases the schema checker also didn't show any issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25484">issues.joomla.org/tracker/joomla-cms/25484</a>.</sub>

**Comment by alikon** [comment]
not able to do a full test on postgresql ...  just  a quick test on SQL Fiddle
Cattura1

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 71252b7c3ccddb806f652ddee0968c3a0c615f9d<br /><br />This corrects the issue here with mysqli<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25484">issues.joomla.org/tracker/joomla-cms/25484</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
@alikon not good enough for a postgresql test for this I'm afraid. We need to be sure our index's are being preserved. Anyone else here able to do a postgresql test before this is merged

**Comment by ghost** [comment]
Set back on pending by comment of @wilsonge above.

**Comment by alikon** [comment]
i know, but cannot help today more than this ...

**Comment by wilsonge** [comment]
https://docs.joomla.org/Tables/template_styles i've updated this page to state it's a varchar and noted the type of the database

**Comment by wilsonge** [comment]
@alikon are you able to at least test it with the index's applied to that table rather than just with the table structure? I installed postgres with brew last night onto my macbook but didn't get time to set up a full joomla install - and won't be able to until tonight

**Comment by alikon** [comment]
sorry @wilsonge & all,  i'm able to do only some spot SQL Fiddle 

Cattura2

**Comment by HLeithner** [comment]
I tested all postgresql scenarios with postgresql 9.6 and worked now. 

thx richard

**Pull request merged**
