### PR TITLE
[4.1] com_content: hardcoded language string

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request to fix hard coded error in front-end com_content.

### Summary of Changes
The hard coded error "Sorry, Joomla 4 no longer supports print_popup" has been moved to .ini language file and is now translatable. 

### Testing Instructions
Please check PR via code inspection

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 65b97da5f292e80a6e70913c9fad4e1c2baa2e27<br /><br />Tested successfully but same comment as before regarding exceptions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37666">issues.joomla.org/tracker/joomla-cms/37666</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 65b97da5f292e80a6e70913c9fad4e1c2baa2e27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37666">issues.joomla.org/tracker/joomla-cms/37666</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37666">issues.joomla.org/tracker/joomla-cms/37666</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
