### PR TITLE
Google Summer of Code 2016 JavaScript Testing project: Tests for combobox.js library.

### PR DESCRIPTION
**Pull request by Ruchiranga**
Pull Request extending #11420 by adding tests written for combobox.js library.
### Summary of Changes

This PR includes a new set of test cases written for the combobox.js JavaScript library of Joomla!.
### Testing Instructions

None, since this is only run on Travis. If you want to run it locally, please take a look at the documentation available [here](https://docs.joomla.org/Running_JavaScript_Tests_for_the_Joomla_CMS).

### CODE REVIEW

**Comment by zero-24** [comment]
@Ruchiranga can we change the doc blocks similiar to ther other doc blocks?

**Comment by zero-24** [comment]
```
/**
 * @package     Joomla.Tests
 * @subpackage  JavaScript Tests
 *
 * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * @since       __DEPLOY_VERSION__
 * @version     1.0.0
 */
```

**Comment by Ruchiranga** [comment]
@zero-24 done.

**Comment by zero-24** [comment]
Thanks @Ruchiranga :+1:

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 73b7a469a3c81b1288d619c43e2f74ddab262e62<br /><br />travis is ok. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11810">issues.joomla.org/joomla-cms/11810</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on f73b0c4b0a94b8b54ad3452d64053ece75d1bad6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11810">issues.joomla.org/joomla-cms/11810</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11810">issues.joomla.org/joomla-cms/11810</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
