### PR TITLE
Adding option showon for global config of core component

### PR DESCRIPTION
**Pull request by micker**
Finalise showon for global config (text area for offline message)
change default option for 0

### CODE REVIEW

**Comment by infograf768** [comment]
Careful:  "Frontend user parameters, Frontend language, Change Login name" can be used separately from "Allow Registration", when a user (for example created in back-end) needs to edit his profile.

**Comment by micker** [comment]
you think i need to change something ? i didn't see any conflict
can you explain more ?
thanks for checking

**Comment by infograf768** [comment]
Anything which is related to profile editing in front-end should be separated from "Allow user registration" setting in back-end as users may be created in back-end.

Example: if Frontend user Parameters is set to show: a user can change in front-end his preferred editor, Time Zone, Login name (if "Change Login Name" is set to Yes).

Making these fields displayed depending on "Allow User registration" would be an error.

**Comment by Bakual** [comment]
Please add a meaningful title for your PR and some easy to understand test instructions which also explain what you rty to achieve.
Otherwise you can as well just close it as nobody will test it :smile:

**Comment by micker** [comment]
oh sorry for title ....

**Comment by Bakual** [comment]
Much better title, thanks :+1:

**Comment by ggppdk** [comment]
There is problem with hiding parameters globally,

- any Joomla extension maybe refering to / using Joomla global configuration parameters
- as (mentioned by @infograf768 ) Joomla views maybe using hidden parameters

an example:
even if a user frontend registration is disabled, the user maybe using some Joomla extension to manage registration and that extension is refering / using these hidden parameters


- only by adding a few -new- "toggle" parameters could this be done
"Toggle User parameters"
"Toggle Cache parameters"
etc

this PR can not be accepted

**Comment by ggppdk** [comment]
I said toggle maybe being a parameter so that the state will be saved in DB

these could live in a cookie too, but this may be confusing to user after login from a different device

**Comment by brianteeman** [comment]
Closing as this is addressed in #8555<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6756">issues.joomla.org/joomla-cms/6756</a>.</sub>

**Pull request closed without merging**
