### PR TITLE
[4.0] Bootstrap 5.1.2

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Update BS to 5.1.2

### Testing Instructions

Check that all the templates are still ok

### CODE REVIEW

**Comment by jwaisner** [comment]
As I started testing I noticed that spacing seems to have changed on the admin dashboard. See below:

After patch:
image

Before patch:

image

**Comment by thednp** [comment]
Isn't codemirror change of the package.json an unrelated change?

**Comment by dgrammatiko** [comment]
@jwaisner I can't replicate it. How are you testing this one, it needs either `npm ci` or downloading the package from Github

Screenshot 2021-10-07 at 11 58 37

> Isn't codemirror change of the package.json an unrelated change?

Yes but https://github.com/joomla/joomla-cms/pull/35769

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 56e44cd896cff928405660db0e1d20fada607d6a<br /><br />Okay, so I thought I had cleaned my test branch but had residual changes. After resetting my local branch I am not seeing any issues with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 56e44cd896cff928405660db0e1d20fada607d6a<br /><br />All looks good to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by RickR2H** [comment]
Back to Pending due to not matching styles.

Upon second review I notices that the headers in the admin modules now have an underline which is not conform the current style. To confirm the issue I downloaded and installed the git repo. @dgrammatiko could you please fix this.

Image 6

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by dgrammatiko** [comment]
@RickR2H that's a Bootstrap bug when a table has a caption and should be fixed upstream instead of monkey patching the code here.
The change, should be:

From 
```css
.table>:not(:first-child) {
    border-top:2px solid #dee2e6;
}
```

```css
.table > tbody:first-of-type {
    border-top:2px solid #dee2e6;
}
```

Anyways: ~https://github.com/twbs/bootstrap/pull/35197~ https://github.com/twbs/bootstrap/pull/35200

**Comment by RickR2H** [comment]
I see what you mean. In my opinion there are three options. Patch it in the templates as override, Merge and accept the changes for now or don't merge at this stage. In all cases is the test valid tho.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by dgrammatiko** [comment]
> In my opinion there are three options.

I wouldn't consider the first as a viable/maintainable option `Patch it in the templates as override`
So it's down to the maintainers to either accept this PR knowing that Bootstrap has a minor bag with tables+caption or await for 5.1.3. I'm ok with either

**Comment by RickR2H** [comment]
I think we let the leads decide...

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 56e44cd896cff928405660db0e1d20fada607d6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by RickR2H** [comment]
RTC
Note: PR will introduce a small visual bug that will be patched in the new Bootstrap release<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35766">issues.joomla.org/tracker/joomla-cms/35766</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
