### PR TITLE
[4.0][a11y] Missing ID attribute in the input field on the Smart Search module

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/23861.
### Summary of Changes
Added missing id to label in mod_finder
### Testing Instructions
code review 
### Expected result
The input field should have an ID attribute so that browsers and assistive technologies recognize the label for this field.
### Actual result
There is a "Search" label for the input field in the Smart Search module. The label can only be visible for screen readers. Unfortunately, the attribute `for` the label refers to an ID that does not exist because the `input` field does not have an ID attribute.
### Documentation Changes Required
no

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on b30f56c5ab5d7796ac9c3f59c9339b8ac6d5d5c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23870">issues.joomla.org/tracker/joomla-cms/23870</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b30f56c5ab5d7796ac9c3f59c9339b8ac6d5d5c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23870">issues.joomla.org/tracker/joomla-cms/23870</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23870">issues.joomla.org/tracker/joomla-cms/23870</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
