### PR TITLE
[[5.x]Compatibility Plugin (BC) added to system info

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
It's going to be more and more important to be able to know if the Backward Compatibility Plugin is enabled or not.

This PR adds it to the list of information displayed in the system information page

### Testing Instructions
Apply the PR and you will now be able to see if the plugin is enabled or disabled when you so the system dashboard and click on system information

image

### Link to documentations
Please select:
- [] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
the options active in the plugin would also be useful

**Comment by brianteeman** [comment]
> the options active in the plugin would also be useful

Doesnt really fit with the system info page which is just an overview

**Comment by HLeithner** [comment]
add the parameter names (which are active) in a () comma separated list should work

**Comment by brianteeman** [comment]
sorry I dont know how to get the active params for the plugin using the pluginhelper

**Comment by HLeithner** [comment]
I added the parameters, you can adapt them if you don't like the style.

**Comment by brianteeman** [comment]
> Enabled (classes_aliases:"0", es5_assets:"1")

~That looks wrong~

there is an error in the plugin that this has exposed see #41214

**Comment by wilsonge** [comment]
When people test this can we make sure we test the JSON view exports too please.

**Comment by brianteeman** [comment]
json export is fine

image

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
