### PR TITLE
[4.0] Remove redundant template/system files

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Removes the following...

templates/system/css/system.css
templates/system/css/toolbar.css
templates/system/images/

### Testing Instructions
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
In theory the system.css is  being used - at least for the first class
system-unpublished 

although it doesnt appear to be working

**Comment by mbabker** [comment]
None of the system template layouts include the system.css file.  So it's totally unused.

Theoretically, even if it were included, the only time you would actually see it do something is if the component.php template file were in use and a template didn't provide their own version of it.  The error and offline layouts won't show content using that class.  And if your template doesn't have the index.php file then why did you install the template to begin with!?

**Comment by N6REJ** [comment]
should the .css referenced by -@import url(../../../media/system/css/system.css); be removed also?

**Comment by ciar4n** [comment]
@N6REJ We are only removing ../templates/system/css/system.css

../media/system/css/system.css remains.

**Pull request merged**
