### PR TITLE
Converts the fields plugins to service providers

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Converts the fields plugins to service providers.

### Testing Instructions
Create various custom fields of all types and edit an article in the back end.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo Could you fix the PHPCS errors reported in drone? https://ci.joomla.org/joomla/joomla-cms/61055/1/8 It seems they are all of the same kind "Space before opening parenthesis of function call prohibited", and i think it's mainly where you create new object like e.g. `new SQL (`, which should be `new SQL(` here https://github.com/joomla/joomla-cms/pull/39670/files#diff-354ab32e246eaeee8352a92c417bd52e09007c8ca9c7f583687af46150cec92eR38 .

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on dd8336622fdfbfdca3ec5bc1ba39348371862f26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39670">issues.joomla.org/tracker/joomla-cms/39670</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dd8336622fdfbfdca3ec5bc1ba39348371862f26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39670">issues.joomla.org/tracker/joomla-cms/39670</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39670">issues.joomla.org/tracker/joomla-cms/39670</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo for the PR!

**Pull request merged**
