### PR TITLE
[4.0] Fix batchSelector is undefined

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #27149 .

### Summary of Changes
Fix batchSelector is undefined.

### Testing Instructions
Go to Global Configuration > System.
Enable Debug System.
Create a new custom field.
View fields list.
Enable browser's web developer.
View console for error.

Apply PR.
Run npm i.

### CODE REVIEW

**Comment by richard67** [comment]
@Quy I can't reproduce the issue with the instructions above. What am I missing?

**Comment by Quy** [comment]
So you are unable to reproduce it before applying the PR? Here is a screenshot.

**Comment by richard67** [comment]
> So you are unable to reproduce it before applying the PR?

@Quy Yes, was testing with Article fields, too, and did not have the type error.

**Comment by richard67** [comment]
@Quy Now I did exactly the same as you, i.e. I gave the field the title "Text". Now I can reproduce. Strange.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aa3adec4865bdef33c417b4584e927348d1b8453<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27390">issues.joomla.org/tracker/joomla-cms/27390</a>.</sub>

**Comment by richard67** [comment]
Any idea why api tests fail in drone? Looks like the usual randomly occurring timeout to me, but I'm not sure.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on aa3adec4865bdef33c417b4584e927348d1b8453<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27390">issues.joomla.org/tracker/joomla-cms/27390</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27390">issues.joomla.org/tracker/joomla-cms/27390</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
