### PR TITLE
Add missing clean line after https://github.com/joomla/joomla-cms/pull/9277

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #9277 
#### Summary of Changes

CodeStyle
#### Testing Instructions

none. On request by @rdeutz after https://github.com/joomla/joomla-cms/pull/9277
#### Documentation Changes Required

none

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11605">issues.joomla.org/joomla-cms/11605</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11605">issues.joomla.org/joomla-cms/11605</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11605">issues.joomla.org/joomla-cms/11605</a>.</sub>

**Comment by rdeutz** [comment]
Travis is still falling on this, I have no idea why. Expecting jenkins failure in a few moments :-)

**Comment by rdeutz** [comment]
ah I know why the script was moved in-between

**Comment by rdeutz** [comment]
Here we are: http://build.joomla.org/job/cms/5853/

**Comment by zero-24** [comment]
```
**Pushing HEAD to branch master at repo projects
 > git --version # timeout=10
 > git -c core.askpass=true push ssh://git@github.com/joomla-projects/joomla-cms.git HEAD:master
Pushing HEAD to branch master at repo origin
 > git -c core.askpass=true push ssh://git@github.com/joomla/joomla-cms.git HEAD:master
ERROR: Failed to push branch master to origin
hudson.plugins.git.GitException: Command "git -c core.askpass=true push ssh://git@github.com/joomla/joomla-cms.git HEAD:master" returned status code 1:
stdout: 
stderr: remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "continuous-integration/travis-ci/push" is pending        
To ssh://git@github.com/joomla/joomla-cms.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'ssh://git@github.com/joomla/joomla-cms.git'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1723)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1459)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1799)
	at hudson.plugins.git.GitPublisher.perform(GitPublisher.java:331)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Git Publisher' marked build as failure
Notifying endpoint 'HTTP:https://developer.joomla.org/glip/jenkins.php'
Finished: FAILURE**
``` 

This has nothing to do with this change. The build itself is successful.

**Comment by rdeutz** [comment]
You are right it is not the change but the circumstances: After you created the PR another got merged and this one moved a script to another place, if I merge your change the move of the file has happened but the code change in the travis.yml not (don't asked me why). So the travis is failing on this PR. The master branch is protected so our jenkins server can only merge PR's into the master branch when travis is on green. To keep a long story short, never ever merge a PR when travis is not on green.

**Pull request merged**
