### PR TITLE
[4.0] Left align workflow ID column

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Workflow ID column should be left-aligned for consistency.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 476673763855f34fb327244e1a337c2eb6859287<br /><br />Code review + applied the changes in browser's developer tools.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26308">issues.joomla.org/tracker/joomla-cms/26308</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 476673763855f34fb327244e1a337c2eb6859287<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26308">issues.joomla.org/tracker/joomla-cms/26308</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26308">issues.joomla.org/tracker/joomla-cms/26308</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
