### PR TITLE
[3.9] Invalid constant in Featured Contacts menu item

### PR DESCRIPTION
**Pull request by Kostelano**
Log in to your control panel, go to Menus: Items -> New Item, select the type Contacts -> Featured Contacts, pay attention to the Form tab (see screenshot).

**Before Patch / After Patch**

Screenshot_1

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 469fa5573e13210e858c14faa049fcb08a63ba52<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28955">issues.joomla.org/tracker/joomla-cms/28955</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 469fa5573e13210e858c14faa049fcb08a63ba52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28955">issues.joomla.org/tracker/joomla-cms/28955</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28955">issues.joomla.org/tracker/joomla-cms/28955</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
