### PR TITLE
[4.1] Micro optimisation

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

A set of manually changed micro optimisations, targeted at 4.1 to prevent as many PR conflicts as possible (And I will personally fix any PR conflicts if there are) 

Non exhaustive, as was prepared on the sofa on Sunday afternoon lazy time. Plus if I did them all in the same PR (800+ files!) then it would have no chance of being merged. 

Also reverts some previous optimisation in administrator/components/com_admin/script.php, but that file is not namespace so its not needed in that file.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e6222e885f23048e75fa4ad2eb6c4336958e291a<br /><br />code review 
+
having this pr applyed for a while<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36711">issues.joomla.org/tracker/joomla-cms/36711</a>.</sub>

**Comment by PhilETaylor** [comment]
> @alikon added the Conflicting Files label 23 seconds ago

I see no conflicts?

**Comment by alikon** [comment]
yeah wrong wording, sorry

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 49f50e2c6d31651cd1eb8f13f7b67bceca16e425<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36711">issues.joomla.org/tracker/joomla-cms/36711</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36711">issues.joomla.org/tracker/joomla-cms/36711</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
