### PR TITLE
[4] Allow period in quoted identifier for db name

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/32941

### Summary of Changes

Allow period in database name for mysql - this is allowed by the documentation of Mysql 5.6 as periods are allowed in quoted identifiers and Joomla quotes the db name on use

This fixes a b\c break with Joomla 3 as per commentary in https://github.com/joomla/joomla-cms/issues/32941

### Testing Instructions

Attempt to install Joomla 4 with a database name with a period in it such as `joomla.test4`

### Expected result AFTER applying this Pull Request

You can install and use Joomla 4 with no issues with a database name with a period in it.

### Documentation Changes Required

note: only changed mysql, other db platforms might need a review too.

### CODE REVIEW

**Comment by progreccor** [comment]
I have tested and it is work as I expected.
Good!

**Comment by richard67** [comment]
I've marked the test result for @progreccor .

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 6d43d8ea1fcb71581ffaaf3cb7c23727364b2949<br /><br />Tested. I was able to install J4 to DB with the name `joomla.test4`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32949">issues.joomla.org/tracker/joomla-cms/32949</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32949">issues.joomla.org/tracker/joomla-cms/32949</a>.</sub>

**Comment by PhilETaylor** [comment]
Thanks all for testing and getting this RTC so quickly. Fingers crossed it makes it into Joomla 4 now.

**Comment by wilsonge** [comment]
We're not accepting new features in.... just kidding - thanks merged!

**Comment by PhilETaylor** [comment]
Thanks

**Comment by progreccor** [comment]
thanks!

**Pull request merged**
