### PR TITLE
update copyright year in ALL files

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

Changing the year in ALL files to meet the current year 2021.

### Testing Instructions

- open htaccess.txt
- read the doc block at the top of the file

- open PHP files
- read the doc block at the top of the file

- open .ini files
- read the doc block at the top of the file

### Actual result BEFORE applying this Pull Request

> Copyright (C) 2005 - **2020** Open Source Matters. All rights reserved.

### Expected result AFTER applying this Pull Request

> Copyright (C) 2005 - **2021** Open Source Matters. All rights reserved.

### CODE REVIEW

**Comment by brianteeman** [comment]
The end years were all supposed to have been removed weren't they? @nibra

**Comment by hans2103** [comment]
@brianteeman when viewing branch _staging_ I can't confirm the removal of the end years. I do see the removal of the end years in 3.10.dev and up

**Comment by brianteeman** [comment]
The point is that EVERY file should have been updated to 2021 and @HLeithner should not have removed the bump script https://github.com/joomla/joomla-cms/commit/cea0be4b0d02cfa26673599e5e52bb69be55b259

That's why it is always always always a bad idea to commit directly without review as it leads to silly little mistakes

This PR should not be accepted unless all files are updated. Makes zero sense to update one file

**Comment by hans2103** [comment]
Challenge accepted

**Comment by brianteeman** [comment]
revert the bump script change and then run it/ job done

**Comment by HLeithner** [comment]
The reason we didn't made a copyright bump was that solving 4k+ merge conflicts between 3.9 and 3.10 is a waste of time. That's the reason why 3.9.24 was without year bump. If there a 3.9.26 really is necessary I will bump the year before release and solve the merge conflicts.

Thanks @hans2103 for the PR but the bump script does a good job normally.

**Pull request closed without merging**
