### PR TITLE
[4.1] Removed unnecessary DISTINCT and JOIN

### PR DESCRIPTION
**Pull request by n3t**
Same issue as in Joomla 3. All is described in #36813 for J3.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ba90c2ab4ed19629f825177402824764d382563a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36884">issues.joomla.org/tracker/joomla-cms/36884</a>.</sub>

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on ba90c2ab4ed19629f825177402824764d382563a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36884">issues.joomla.org/tracker/joomla-cms/36884</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36884">issues.joomla.org/tracker/joomla-cms/36884</a>.</sub>

**Comment by alikon** [comment]
@simbus82  can you test #36813 it's the same for j3

**Comment by simbus82** [comment]
> @simbus82 can you test #36813 it's the same for j3

Too late ;-) Glad it's already in RTC for J3 too.

**Comment by Quy** [comment]
Upmerged in #37104. Thanks.

**Pull request closed without merging**
