### PR TITLE
[4.1] Remove tab

### PR DESCRIPTION
**Pull request by brianteeman**
Simple codestyle PR to remove an additional tab.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ec184e9b6e6f26739d6e67470f6693a940fa2e9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36949">issues.joomla.org/tracker/joomla-cms/36949</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on ec184e9b6e6f26739d6e67470f6693a940fa2e9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36949">issues.joomla.org/tracker/joomla-cms/36949</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36949">issues.joomla.org/tracker/joomla-cms/36949</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
