### PR TITLE
[4.0] Fix filter for workflows

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #24814

### Summary of Changes
The #__workflows table uses column name published. This causes several issues. One of them is that the ordering of workflows via state is not possible. 
Another isssue is that filters are not set, as described in the related issue. 

### Testing Instructions
Ordering: 
You must have at least two workflows. Set one of the unpublished and try ordering of the column "state"
Active Filters:
Or see test instruction in the related issue.

### Expected result
Columns are ordered new if possible
Active Filters are set

### Actual result
No ordering possible, active Filters are not set.

### Documentation Changes Required
no, it is a bug

### CODE REVIEW

**Comment by Quy** [comment]
Please update to the right issue for this PR.

**Comment by chmst** [comment]
done, sry

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eafbd9c18b2b2849f99b1469ef3a865f2f21dcc0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24864">issues.joomla.org/tracker/joomla-cms/24864</a>.</sub>

**Comment by brianteeman** [comment]
I dont see how this has anything to do with #24814

**Comment by chmst** [comment]
Could you test please? I think setting the filter right does the trick also for you.

**Comment by brianteeman** [comment]
I did test

**Comment by chmst** [comment]
Description changed.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 3e45bc5d268502072344c0bcd18b92867d3fb41c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24864">issues.joomla.org/tracker/joomla-cms/24864</a>.</sub>

**Comment by ghost** [comment]
@Quy can you please retest?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3e45bc5d268502072344c0bcd18b92867d3fb41c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24864">issues.joomla.org/tracker/joomla-cms/24864</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24864">issues.joomla.org/tracker/joomla-cms/24864</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

As stated this solves a different issue than #24814

**Pull request merged**
