### PR TITLE
[4.0] fix comment copy/paste

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to fix a comment which has been copy pasted

code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f1c84e2042d601b0b878161866c3a899a150b402<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34736">issues.joomla.org/tracker/joomla-cms/34736</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f1c84e2042d601b0b878161866c3a899a150b402<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34736">issues.joomla.org/tracker/joomla-cms/34736</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34736">issues.joomla.org/tracker/joomla-cms/34736</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
