### PR TITLE
[4.0] users dashboard

### PR DESCRIPTION
**Pull request by brianteeman**
Add the missing title to the add new user link on the users dashboard

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on acf2ef39081b6b4be6ac9c17cd4b1c1c8dea0cbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27288">issues.joomla.org/tracker/joomla-cms/27288</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on acf2ef39081b6b4be6ac9c17cd4b1c1c8dea0cbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27288">issues.joomla.org/tracker/joomla-cms/27288</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27288">issues.joomla.org/tracker/joomla-cms/27288</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
