### PR TITLE
Fixed the docbloc to match the code

### PR DESCRIPTION
**Pull request by roland-d**
The docblocks were inconsistent nor following the code. This pull request fixes the docblocks to match the code.

There are no testing instructions as only the docblocks have been changed.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on cdf9b06bdab9182d8ea093dde4a9b2f28b40be0b<br /><br />Can be merged on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8911">issues.joomla.org/joomla-cms/8911</a>.</sub>

**Comment by chrisdavenport** [comment]
That's not grammatically correct.  Better would be "Array of properties available for use inside the layout file to build the displayed output".

**Comment by brianteeman** [comment]
Agree with Chris. Its as important that Doc blocks are easy to understand
as it is that the code is correct.

**Comment by roland-d** [comment]
Thanks, replaced the description with the suggestion by @chrisdavenport

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b8bc1765851242dc7281d63b1aaebb79ad661bf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8911">issues.joomla.org/joomla-cms/8911</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b8bc1765851242dc7281d63b1aaebb79ad661bf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8911">issues.joomla.org/joomla-cms/8911</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8911">issues.joomla.org/joomla-cms/8911</a>.</sub>

**Pull request merged**
