### PR TITLE
[3.8] Make the text clearer

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue # .

### Summary of Changes
Make the PLG_TWOFACTORAUTH_TOTP_STEP3_TEXT text clearer.
### Testing Instructions
code review
### Expected result
User know which button select to pass step 3 of initial configuration.
### Actual result
User don't know which button select to pass step 3 of initial configuration - see https://forum.joomla.org/viewtopic.php?f=706&t=863546.

### CODE REVIEW

**Comment by brianteeman** [comment]
Yes its a bug that needs fixing. Good spot. But can you look at the similar string for the yubikey plugin and adjust this one to match

**Comment by wojsmol** [comment]
For yubikey we have
`PLG_TWOFACTORAUTH_YUBIKEY_STEP1_TEXT="Please insert your YubiKey device into your computer's USB port. Select the Security Code field below. Then touch the gold disk on your YubiKey device for one second. Afterwards, please save your user profile. If the code generated by your YubiKey is validated by YubiCloud the Two Factor Authentication feature will be enabled and this YubiKey will be linked with your user account."`
Witch text you prefer?

**Comment by brianteeman** [comment]
**Afterwards, please save your user profile. If the code is correct, the Two Factor Authentication feature will be enabled.**

**Review by brianteeman — APPROVED** [review]

**Comment by Quy** [comment]
How about `in the field below and save your user profile.`?

**Comment by wojsmol** [comment]
@brianteeman Please comment on https://github.com/joomla/joomla-cms/pull/20940#issuecomment-401615319.

**Comment by brianteeman** [comment]
i stick by my original comment

**Comment by wojsmol** [comment]
PR in ready for testing.

**Comment by bene-we** [comment]
I have tested this item :white_check_mark: successfully on 8c6a8410065ff0ac4bf6573a868db6c958667f9e<br /><br />Description is much clearer now

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20940">issues.joomla.org/tracker/joomla-cms/20940</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c6a8410065ff0ac4bf6573a868db6c958667f9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20940">issues.joomla.org/tracker/joomla-cms/20940</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20940">issues.joomla.org/tracker/joomla-cms/20940</a>.</sub>

**Pull request merged**
