### PR TITLE
[com_users] category user notes: Add counting to user notes categories

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement .
#### Summary of Changes

All category views in the backend have a counting of items, except one, the user notes.
This PR adds it.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Creste some user note categories and add some user notes to that categories
3. Test if user notes counting is working properly.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
hum ... just notice that in this case the counting link goes to users and not to user notes.

So don't test until a way is found to solve this.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on d216abb3f4987ed6263dbef9a6fe3e66feeeb296<br /><br />The trashed column is not working correctly

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10015">issues.joomla.org/joomla-cms/10015</a>.</sub>

**Comment by brianteeman** [comment]
This should be showing TWO trashed itemsscreen shot 2016-04-20 at 13 58 19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10015">issues.joomla.org/joomla-cms/10015</a>.</sub>

**Comment by andrepereiradasilva** [comment]
sorry trashed was a copy paste probelm.

Anyway:

> hum ... just notice that in this case the counting link goes to users and not to user notes.
> So don't test until a way is found to solve this.

**Comment by brianteeman** [comment]
I can confirm the count is now working even if the link isnt yet ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10015">issues.joomla.org/joomla-cms/10015</a>.</sub>

**Comment by andrepereiradasilva** [comment]
the change is way bigger that i antecipated, it tuen out the user notes wasn't using the "notes" section of the categories. 

I have made changes to make it use it "com_users.notes" extension instead of "com_users" extension in the categories.

This solves the link problem. but need further tests.

**Comment by andrepereiradasilva** [comment]
Anyway this SQL (https://github.com/joomla/joomla-cms/pull/10015/files#diff-2db7ed02f6ea4074ce5b41c353d923e4R1) needs to be run before testing.

**Comment by richard67** [comment]
@andrepereiradasilva You know that the SQL will not be applied when using the update method "copy or unzip the files and then run the db fix"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10015">issues.joomla.org/joomla-cms/10015</a>.</sub>

**Comment by andrepereiradasilva** [comment]
yes, but that's for all SQL updates right?

**Comment by andrepereiradasilva** [comment]
i will close this and reopen when ready.

**Comment by richard67** [comment]
@andrepereiradasilva Yes, all insert or update or delete statements in schema update scripts - the schema manager's db fix only applies create table or alter table.

**Comment by andrepereiradasilva** [comment]
hum, how do others do to solve that issue? do you know?

**Comment by richard67** [comment]
Yes: They can do nothing up to now. Is an open, unsolved issue.

I had the hope I could discuss that with @wilsonge because I have several ideas how to solve that, but seems he has no time.

When updating with Joomla! Update the update sql scripts are run if the version number in the file name is larger than the installed schema version (pre-update), and since Joomla! Update meanwhile contains the "Upload & Install" method, the number of people using the "copy or unzip the files and then run the db fix" method may have decreased, but as long as this is still a valid update method this is an issue.

The easiest way to solve this would be to make the db fixer run in the 1st attempt all statements from all scripts where version is larger than the schema version in db, as the updater does, but I am not sure if this would be a valid solution. There might be some reason why the schema manager doesn't already work like this, and I just don't know it.

**Comment by richard67** [comment]
@andrepereiradasilva For what you wanted to achieve with this PR here, would there not be another way to solve it, without changing the extension in the categories, so your SQL updates would not be required, e.g. by using a clever join or subquery for obtaining the right count (i.e. the user notes count and not the user count) for the particular category?

**Comment by andrepereiradasilva** [comment]
The count is ok without the SQL changes. The only problem is the URL in the counting, is linking to users instead of linking to user notes view.

I'm not an expert on this, but it seems the categories takes for the link the primary view of the component.

For instance in com_content the primary view is the articles view. So the link in the categories count is `index.php?option=com_content&[filters]` which is the same as `index.php?option=com_content&view=articles&[filters]`.

In com_users the primary view is the users view. So the link in the categories count is `index.php?option=com_users&[filters]` which is the same as `index.php?option=com_users&view=users&[filters]`.
Because it assumes that there are categories for users.

Since, in this case, the categories are not for the primary view of the component users (the users view) i think we need the notes to be a category section inside com_users (`com_users.notes`).

If i do all those changes if works perfectly. If there is another way. Don't know. But the way categories work, seems consistent to me that the user notes categories of the component users are a category section of com_users (`com_users.notes`), and not the primary category of the the users component `com_users` (that would be users categories, if existed).

**Comment by richard67** [comment]
Sure, you are right, should be as you say.

One way to solve that could be to add it to script.php to other hardcoded db changes but I would not really like that.

The other way would be to leave it as it is so for the users having updated with the stone-age method the links would be wrong (for a while until we found a way to apply that).

Or maybe split it into 2 PRs, 1 for correct counting and the other one for this link thing, so we get at least the counting corrected soon.

**Comment by andrepereiradasilva** [comment]
i think i will split it in two PR:

- 1º PR: move users notes categories from extension `com_users` to `com_users.notes`
- 2º PR: add counting to user notes categories (depends on the first)

**Comment by richard67** [comment]
Hmm why does the 2nd depend on the first? As far as I understood you before, the correction for the counts woutl work without the correction for the links. So I expected the order to be vice versa.

**Comment by andrepereiradasilva** [comment]
well for people understand why PR 1 is needed i prefer to do this way.

**Comment by andrepereiradasilva** [comment]
but of course, clearly this seems to go only for 3.6 so i have some time to look into that better.

**Pull request closed without merging**
