### PR TITLE
[3.7] Extension installation grid margin issue #14318

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #14318 .

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 09ffa9803ab29725e13a70c1fcfc33e86a7f43cd<br /><br />thanks Brian <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14453">issues.joomla.org/tracker/joomla-cms/14453</a>.</sub>

**Comment by brianteeman** [comment]
The drone test failures are unrelated to this PR

**Comment by dgt41** [comment]
@brianteeman so who broke the calendar?

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 09ffa9803ab29725e13a70c1fcfc33e86a7f43cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14453">issues.joomla.org/tracker/joomla-cms/14453</a>.</sub>

**Comment by brianteeman** [comment]
@dgt41 it might even be fixed elsewhere - this PR is 2 weeks old so the branch is  at least 2 weeks old and the tests run on the branch

**Comment by dgt41** [comment]
@brianteeman ok then, I was the one who broke it then :(

**Comment by dgt41** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14453">issues.joomla.org/tracker/joomla-cms/14453</a>.</sub>

**Pull request merged**
