### PR TITLE
delete unnecessary termination and opening of php tags

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c80b3d7cc9ca1182c703692d277afe8a223c7fac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38484">issues.joomla.org/tracker/joomla-cms/38484</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38484">issues.joomla.org/tracker/joomla-cms/38484</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c80b3d7cc9ca1182c703692d277afe8a223c7fac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38484">issues.joomla.org/tracker/joomla-cms/38484</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Pull request closed without merging**
