### PR TITLE
[4.0] Add files removal for removed FTP GUI parts to script.php

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Add removal of files removed with PR #33390 to script.php .

I do this PR here now because script.php has been recently updated so it's up to date with all other changes, only this one is missing right now, and I want it not to be forgotten when doing the next 4.0 release.

### Testing Instructions

Code review:
- The files added by this PR are the same as those deleted with PR #33390 from the sources, except of those in the installation folder.
- They are added at the right place for alphabetical order within the section after the `// 4.0 from Beta 7 to Beta 8` comment in script.php.
- There is no PHP syntax error (missing quotes, missing comma, whatever possible).

Alternatively do a real test with updating a current 4.0-dev or latest nightly to the update package or custom URL created by Drone for this PR and checking that the files are really removed by the update.

### Actual result BEFORE applying this Pull Request

Files removed with PR #33390 from the sources will not be deleted with a CMS update.

### Expected result AFTER applying this Pull Request

Files removed with PR #33390 from the sources will be deleted with a CMS update.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1f0daef2768c272c107d8c02e31459147e780e7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33555">issues.joomla.org/tracker/joomla-cms/33555</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1f0daef2768c272c107d8c02e31459147e780e7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33555">issues.joomla.org/tracker/joomla-cms/33555</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33555">issues.joomla.org/tracker/joomla-cms/33555</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
