### PR TITLE
Avoid conflict between JQTooltip in the same DOM as a BSTooltip

### LINKED ISSUE #15896: Tooltip BS and JQ Conflicts
### Steps to reproduce the issue
Use JQuery UI tooltip (for instance in article or menu admin)
**Yes, It is possible to use JQTooltip in the same DOM as a BSTooltip using the bridge functionality from JQ !**
`jQuery.widget.bridge('jqTooltip', jQuery.ui.tooltip);`

But media/media/js/mediafield.js on line 139 attempts to **destroy** all existing tooltips (BS ones).
And this happens before one can set a bridge. So we get the error :

> Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

### Expected result
This conflict should not create an error

### Actual result
This conflict creates an error and locks JavaScript !

### System information (as much as possible)
Joomla! 3.7...

### Additional comments
Before invoking  the destroy method code should ensure the object is a tooltip
or, at least use a **try and catch** the error in order to let the page scripts go on
For instance
```
try{
     this.$input.tooltip('destroy');
} catch(err){
     // do we have to do something with this error ?
}
```

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue Closes #15896.

### Summary of Changes

Allow JQTooltip in the same DOM as a BSTooltip without JS errors when destorying tooltips in mediafield javascript

### Testing Instructions

To setup:
Add this jQueryUI code to your /administrator/templates/isis/index.php before </head>
```html
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
```

Replicate the error in the JS console

screen shot 2017-05-10 at 20 50 07

To Test: 
Apply PR (leaving jQueryUI in isis/index.php) 
See Error disappears 
Check this works with debug OFF and debug ON in Joomla Config. (one uses minified JS and one doesnt)

### Expected result

No console errors

### Documentation Changes Required

None

### CODE REVIEW

**Comment by PhilETaylor** [comment]
@Yves-K please test this PR https://github.com/joomla/joomla-cms/pull/15951

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8de0ff4c8081fba0626b1bf438aa57e0a515e5be<br /><br />replicated the error and confirmed the fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15951">issues.joomla.org/tracker/joomla-cms/15951</a>.</sub>

**Comment by brianteeman** [comment]
with the PR and jquery-ui loaded
phil

**Comment by PhilETaylor** [comment]
This PR was just to stop the javascript error and to stop the fact that all other javascript failed on the page because of that error. 

If you want to fix your tooltip styles then you will need BOTH the JS and the CSS for jQuery UI loaded in your DOM. I never bothered giving the CSS before as it was not required to replicate and fix the reported issue. Nothing in this PR attempts to correctly integrate the jQueryUI, it merely seeks to prevent the conflict should a 3pd decide to add it.

Add these before the `</head>` in `/administrator/templates/isis/index.php` before you test again

```html
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
```

and then you will see the tooltips pretty for example:

screen shot 2017-05-23 at 10 39 16

**Comment by PhilETaylor** [comment]
Pinging @Yves-K to test this please

**Comment by Yves-K** [comment]
Hello Phil,
**Successfully tested**.
Thank you very much for making it done (i really did not know how to create a pull request...)

**Comment by Yves-K** [comment]
I have tested this item :white_check_mark: successfully on 8de0ff4c8081fba0626b1bf438aa57e0a515e5be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15951">issues.joomla.org/tracker/joomla-cms/15951</a>.</sub>

**Comment by Yves-K** [comment]
Hi @hikashop-nicolas, might solve [#14259](https://github.com/joomla/joomla-cms/issues/14259).
Can you test too ?

**Comment by hikashop-nicolas** [comment]
The issue is still there when you edit a HikaShop products listing menu item with HikaShop below the 3.0.1, even with that patch.
We modified the way we handle the jquery-ui on our end in the 3.0.1 version of HikaShop to circumvent the problem altogether.

**Comment by jaimestuardo** [comment]
This worked correctly in my Joomla 3.8.1. I am wondering why this correction is not included in the official release.

**Comment by ghost** [comment]
@jaimestuardo we need 2 successfully Tests before a Maintainer can decide if its gonna be merged, so please mark your Test as successfully:

- Please open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/15951)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by jaimestuardo** [comment]
I have tested this item :white_check_mark: successfully on 57449880bdc9bad9ba88150f3393a94dffc0fe22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15951">issues.joomla.org/tracker/joomla-cms/15951</a>.</sub>

**Comment by ghost** [comment]
@Yves-K can you please retest?

**Comment by Quy** [comment]
Fix whitespace. Use tabs.

**Comment by ghost** [comment]
@brianteeman can you please retest?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15951">issues.joomla.org/tracker/joomla-cms/15951</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 57449880bdc9bad9ba88150f3393a94dffc0fe22<br /><br />It works and avoids the error message with and without debug mode.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15951">issues.joomla.org/tracker/joomla-cms/15951</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

Thanks for Tests.

**Pull request merged**
