### PR TITLE
[4.0] Fix radio buttons in batch processing

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/33890.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/33890.

### Actual result BEFORE applying this Pull Request
Screenshot_1

### Expected result AFTER applying this Pull Request
Screenshot_2

### Documentation Changes Required
Not

### CODE REVIEW

**Comment by brianteeman** [comment]
You do not need to add the fieldset element. Its not a fieldset as its just a single field and a fieldset also requires a legend

**Comment by brianteeman** [comment]
The problem is caused by the class here

`<div id="batch-copy-move" class="control-group radio">`

**Comment by Kostelano** [comment]
Hmm. The problem is that everything is done differently. For example, categories in banners.

Screenshot_1

**Comment by brianteeman** [comment]
Consistency is terrible. Great that you are spotting these.

Without adding the fieldset but removing the class

```
<div id="batch-copy-move">
	<?php echo Text::_('JLIB_HTML_BATCH_MOVE_QUESTION'); ?>
	<?php echo HTMLHelper::_('select.radiolist', $options, 'batch[move_copy]', '', 'value', 'text', 'm'); ?>
</div>
```

image

**Comment by richard67** [comment]
@Kostelano PHP code style check in drone reports mixed line endings for both files. Please make sure you only have Unix line endings.

**Comment by Kostelano** [comment]
@brianteeman Thanks, I redid it according to your advice.
@richard67 Thanks for the info, I will wait for the result of a new check.

**Comment by richard67** [comment]
@Kostelano Same result, see here: https://ci.joomla.org/joomla/joomla-cms/43741/1/6

**Comment by brianteeman** [comment]
Looks good - it would be great if you reviewed all the batch modals to make sure that no others have the same problems

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on b08f65e080388ea032deead564b002c3a1a05773<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33900">issues.joomla.org/tracker/joomla-cms/33900</a>.</sub>

**Comment by richard67** [comment]
@Kostelano You still haven't fixed the mixed line endings which are reported by the style check in drone and about which I have informed you here 2 times, now the 3rd time. As said, files in our source code have to have Unix line endings, so check and remove all windows line endings.

**Comment by Kostelano** [comment]
@richard67 I remember, I have not forgotten. I'll fix + see other batch processing modals a bit later.

**Comment by Quiviro** [comment]
I have tested this item :white_check_mark: successfully on b08f65e080388ea032deead564b002c3a1a05773<br /><br />Expected result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33900">issues.joomla.org/tracker/joomla-cms/33900</a>.</sub>

**Comment by richard67** [comment]
@Kostelano It still neds to fix that PHP code style issue with mixed line ending.

**Comment by richard67** [comment]
@Kostelano PHP code style seems to be fine now. Current drone failure seems not to be related to this PR.

**Comment by richard67** [comment]
Previous test results are still valid since the commit which invalidated the result was just a code style change. I've restored the results in the issue tracker so they are properly counted.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33900">issues.joomla.org/tracker/joomla-cms/33900</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
