### PR TITLE
[4.4] Untranslated string for warning message in update:extensions:check CLI

### PR DESCRIPTION
**Pull request by chrisdavenport**
Pull Request for Issue #43206 .

### Summary of Changes
Language file is now loaded before outputting the warning message.

### Testing Instructions
Arrange for an extension update site to have an invalid URL (eg. temporarily mangle the URL in the extensions database). Then run `php cli/joomla.php update:extensions:check` from the command line.

### Actual result BEFORE applying this Pull Request
Warning message: `[WARNING] JLIB_UPDATER_ERROR_OPEN_UPDATE_SITE`

### Expected result AFTER applying this Pull Request
Warning message something like
`[WARNING] Update: Could not open update site #4 "xxxxxxxxxxx Package Update Site", URL: https://example.com/xxxxx/update.xml`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chrisdavenport** [comment]
Not sure what the "official" convention is so you'll need to educate me on that.  However, from looking at the code, log messages are untranslated English strings, but messages intended for CLI output, which is the case here, are translated into the default language.  This PR ensures that the CLI user gets to see the same message as the web user in the default language.

**Comment by brianteeman** [comment]
are you sure? Everything here is hardcoded english

image

**Comment by chrisdavenport** [comment]
If the convention is that the CLI is always in English, then fine, I've learnt something today. :-)

But, thinking about it, the code I'm modifying here (UpdateAdapter.php) is also used by the web interface (when you click "Check For Updates"), so it needs to be translated.  The correct language file is already loaded in the web interface, but isn't for CLI.

Or maybe a better fix would be to load the lang file in cli/joomla.php?  Dunno.

**Comment by alikon** [comment]
i'll do it  in the `CheckUpdatesCommand`

image


and only the `html_entity_decode`  in the UpdateAdapter

my 0.02 €

**Comment by chrisdavenport** [comment]
@alikon Okay, done.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 223769c2ced3b6ca2d0ad91e087a39f23b41909e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43208">issues.joomla.org/tracker/joomla-cms/43208</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 223769c2ced3b6ca2d0ad91e087a39f23b41909e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43208">issues.joomla.org/tracker/joomla-cms/43208</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43208">issues.joomla.org/tracker/joomla-cms/43208</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
