### PR TITLE
Use getState instead of direct property read

### LINKED ISSUE #10416: Notice when JModelList call getFilterForm before populating model state
#### Steps to reproduce the issue
Edit file: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/view.html.php#L43
Move ```$this->filterForm = $this->get('FilterForm');```
before ```$this->items = $this->get('Items');```

Administrator side:
Configuration > Error Reporting: System default or Maximum or Development
Then Articles listing

Will throw:
```Notice: Undefined property: JObject::$list.direction in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 453```
```Notice: Undefined property: JObject::$list.limit in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 454```
```Notice: Undefined property: JObject::$list.ordering in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 455```
```Notice: Undefined property: JObject::$list.start in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 456```

#### System information (as much as possible)
Joomla 3.5.1

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #10416.
#### Summary of Changes

Use getState instead of direct property read in JModelList  to avoid any undefined property warnings.
Using `$this->getState` against `$this->state->get` ensures the model state is populated appropriately.
#### Testing Instructions
- Enable error reporting from global configuration.
- In any list view class such as `ContentViewArticles` at `administrator/components/com_content/views/articles/view.html.php` in the display method call `$this->get('FilterForm');` before `$this->get('State')` or `$this->get('Items')` etc.

**Expected**: Everything should work correctly.
**Actual**: You see 4 php notices such as `Notice: Undefined property: JObject::$list....`

Fixes #10416

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@izharaazmi you have unit test errors.

**Comment by izharaazmi** [comment]
@andrepereiradasilva yeah, I'm looking at that. Apparently that is the issue with the test definition. But can't say it yet.

**Comment by Devportobello** [comment]
I have tested this item :white_check_mark: successfully on https://github.com/joomla/joomla-cms/pull/10435/commits/45a6d09753778088d3b23ac9253990a1c80ca837

**Comment by andrepereiradasilva** [comment]
@Devportobello you have to mark as tested in the issue tracker (https://issues.joomla.org/tracker/joomla-cms/10435 login with github and mark test as success).

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 45a6d09753778088d3b23ac9253990a1c80ca837<br /><br />The notices dissapear after this PR so i will make as success.
I think if you used `$this->state->get('list.xxxx')` you would get the same result. 

But for what is worth, if you exchange the order the filters/ordering/search (aka searchtols) will not work properly. With or without this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10435">issues.joomla.org/joomla-cms/10435</a>.</sub>

**Comment by Devportobello** [comment]
I have tested this item :white_check_mark: successfully on 45a6d09753778088d3b23ac9253990a1c80ca837<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10435">issues.joomla.org/joomla-cms/10435</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10435">issues.joomla.org/joomla-cms/10435</a>.</sub>

**Comment by izharaazmi** [comment]
> But for what is worth, if you exchange the order the filters/ordering/search (aka searchtols) will not work properly. With or without this PR.

@andrepereiradasilva Can you please explain this.

**Comment by andrepereiradasilva** [comment]
Note this happens with or without your PR.

For instance, change the order of the `$this->get('FilterForm')`  in the articles view.html.php file.
```php
$this->filterForm    = $this->get('FilterForm'); // PUT THIS ONE ON TOP
$this->items         = $this->get('Items');
$this->pagination    = $this->get('Pagination');
$this->state         = $this->get('State');
$this->authors       = $this->get('Authors');
$this->activeFilters = $this->get('ActiveFilters');
```
Now try to use the searchtools in articles view. search for something, order or filter by something.
You will notice the table will be modified accordly but the searchtools filters pre selected values don't.

**Comment by izharaazmi** [comment]
@andrepereiradasilva The solution is straightforward. Use `$this->get('State')` in the view before you call any method on the model. 
OR 
Change the `JModelList::loadFormData()` to call `$this->getState();` **before** calling `$app->getUserSate()`

But that is not all. Therefore instead of a placing a PR, I'd prefer a little discussion regarding `loadFormData` behavior in `JModelList` vs `JModelForm`, preferably on a separate thread.

**Comment by andrepereiradasilva** [comment]
ok then create a issue / RFC

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
