### PR TITLE
Fix early exit from foreach in JForm::removeGroup

### PR DESCRIPTION
**Pull request by izharaazmi**
### Summary of Changes

Removed unconditional `return` statement from foreach loop

The method is supposed to remove all instances of <fields> element but it exits the loop on first iteration only. Looks like a quick copy-paste from removeField may have caused this.
#### Form XML `form.xml`:

``` xml
<form>
    <fields name="group1">
        <field name="field1"/>
    </fields>
    <fieldset name="set1">
        <fields name="group1">
            <field name="field2"/>
        </fields>
    </fieldset>
</form>
```

``` php
$form = new JForm('Test');

$form->load('form.xml');
$form->removeGroup('group1');

print_r($form);
```

**Expected**:
This should remove all `fields` nodes with name **group1**

**Actual**:
Only the first group is removed before patch. After patch this should remove all as expected.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 3ef90365e73a9cfe363ee2ce97684921643b6458<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11856">issues.joomla.org/joomla-cms/11856</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 3ef90365e73a9cfe363ee2ce97684921643b6458<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11856">issues.joomla.org/joomla-cms/11856</a>.</sub>

**Comment by izharaazmi** [comment]
We have 2 success, can it be moved forward please?

**Comment by zero-24** [comment]
RTC Sorry it get missed anyhow.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11856">issues.joomla.org/joomla-cms/11856</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by rdeutz** [comment]
Needs an update of the @return tag

**Comment by izharaazmi** [comment]
Is that ok @rdeutz ?

**Pull request merged**
