### PR TITLE
[4.1] s/mashine/machine

### PR DESCRIPTION
**Pull request by brianteeman**
spelling & code quality

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b0472ac4a6080b2ee8bb8fe0990a6b948b0ff024<br /><br />@bembelimen Could be merged by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36842">issues.joomla.org/tracker/joomla-cms/36842</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b0472ac4a6080b2ee8bb8fe0990a6b948b0ff024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36842">issues.joomla.org/tracker/joomla-cms/36842</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36842">issues.joomla.org/tracker/joomla-cms/36842</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on b0472ac4a6080b2ee8bb8fe0990a6b948b0ff024<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36842">issues.joomla.org/tracker/joomla-cms/36842</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
