### PR TITLE
JHtmlBootstrap::tooltip() hide vs. hideme

### PR DESCRIPTION
**Pull request by itbra**
It appears the `hide` event is not fired when triggering an element to show the tooltip. However, the `hideme` event is fired. This can easily be tested with the following code:

```
JHtml::_('bootstrap.tooltip', '.hasStickyTooltip', array(
    'onShow'   => 'function ( e ) {'
        .'alert("onShow executed")'.
    '}',
    'onShown'  => 'function ( e ) {'
        .'alert("onShown executed")'.
    '}',
    'onHide'   => 'function ( e ) {'
        .'alert("onHide executed")'.
    '}',
    'onHideMe' => 'function ( e ) {'
        .'alert("onHideMe executed")'.
    '}',
    'onHidden' => 'function ( e ) {'
        .'alert("onHidden executed")'.
    '}'
));
```

This proves the message `onHide executed` never appears. To get hands on the event fired before the widget is getting hidden i added the corresponding listener `onHideMe` to the configuration array. With this listener in place the message `onHideMe executed` is shown and the corresponding event is handled by the plugin.

### CODE REVIEW

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on a31c5b9cf9b09ace0ab977ea7cef610d7c0d526e<br /><br />Before Patch:
onHidden executed

After Patch:
onHide executed
onHidden executed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4507">issues.joomla.org/joomla-cms/4507</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on a31c5b9cf9b09ace0ab977ea7cef610d7c0d526e<br /><br />Works as expected!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4507">issues.joomla.org/joomla-cms/4507</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on a31c5b9cf9b09ace0ab977ea7cef610d7c0d526e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4507">issues.joomla.org/joomla-cms/4507</a>.</sub>

**Comment by yvesh** [comment]
Yep works as @matrikular describes it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4507">issues.joomla.org/joomla-cms/4507</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4507">issues.joomla.org/joomla-cms/4507</a>.</sub>

**Pull request merged**
