### PR TITLE
[4.0] Prevent saving content when creating category fails

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Category field is required in content item forms but it's possible to save content items without a valid category when creating category on the fly fails. This changes that.

### Testing Instructions

Create a category. Call it whatever but set its alias as `duplicate`.
Create or edit an article/contact/newsfeed/banner.
In the category field enter `Duplicate` to create category on the fly.
Save.

### Expected result

Saving fails with error:

>Save failed with the following error: Another category with the same parent category has the same alias (remember it may be a trashed item).

### Actual result

Article is either saved or we get this:

>Argument 1 passed to Joomla\Component\Content\Administrator\Model\ArticleModel::getWorkflowByCategory() must be of the type integer, null given

Contact saving fails with error:

>This category is invalid.

Newsfeeds and banners are saved.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this true in joomla 3 as well?

**Comment by SharkyKZ** [comment]
Yes. I did not make a PR for J3 because some may consider this B/C breaking change 🤷‍♂ .

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on e0322bf34280a1727a282d2051dfe198b8f87cb1<br /><br />Correct error is presented in articles, contacts, newsfeeds, and banners.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27839">issues.joomla.org/tracker/joomla-cms/27839</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e0322bf34280a1727a282d2051dfe198b8f87cb1<br /><br />Confirmed the issue
Confirmed the fix by testing in com_content <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27839">issues.joomla.org/tracker/joomla-cms/27839</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27839">issues.joomla.org/tracker/joomla-cms/27839</a>.</sub>

**Comment by rdeutz** [comment]
@SharkyKZ 
> Yes. I did not make a PR for J3 because some may consider this B/C breaking change 🤷‍♂ .

This looks more like a bug so we can fix it for J3. What is with others components using categories, like banners, contact?

**Comment by SharkyKZ** [comment]
Contact has a check in table class but other components allow saving without category.

**Comment by wilsonge** [comment]
Let's roll the check for a category in the Table level into j3 - no need to port the rest of it.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
