### PR TITLE
[4.0] Fix ce breaks

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/19403 .

### Summary of Changes
- use the proper polyfills
- move the switcher to the proper folder

### Testing Instructions
Apply and check the backend if alerts and switches are rendering ok

### Documentation Changes Required
No

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@infograf768 here you go

**Comment by C-Lodder** [comment]
Please could you also replace

```
// Various variables
const rootPath = __dirname.replace('/build/build-modules-js', '');
```

with 

```
// Various variables
const isWin = /^win/.test(process.platform);
const rootPath = isWin ? _dirname.replace('\\build\\build-modules-js', '') : _dirname.replace('/build/build-modules-js', '');
```

in all `build/build-module-js/*.js` files

Either that or I can do it with my PR later on tonight or tomorrow

**Comment by infograf768** [comment]
Much better. Could not apply all changes with eclipse, but I do get the switcher class OK.
The 3 files concerned are:
screen shot 2018-01-19 at 18 05 12

**Comment by dgrammatiko** [comment]
@C-Lodder now that I see that code I’m thinking that was way to fast patch so let’s do it in one line. Once you have your pr I’ll post the code there, let’s get this merged as it’s kinda urgent

**Comment by C-Lodder** [comment]
@dgt41 sure no worries. @wilsonge please merge

**Pull request merged**
