### PR TITLE
Missing bottom border in modal

### PR DESCRIPTION
**Pull request by NikitaEmberi**
Pull Request for Issue #32190 

### Summary of Changes

Changes as suggested in:https://github.com/joomla/joomla-cms/issues/32190#issuecomment-801452820
and https://github.com/joomla/joomla-cms/pull/32762#issuecomment-803442647

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### CODE REVIEW

**Comment by brianteeman** [comment]
Why did you close this and delete your branch? It looked correct

**Comment by NikitaEmberi** [comment]
> Why did you close this and delete your branch? It looked correct

@brianteeman sir there were merge conflicts.

**Comment by chmst** [comment]
@NikitaEmberi if you have problems with github, like here - just write a comment. We can help you.

**Comment by NikitaEmberi** [comment]
> @NikitaEmberi if you have problems with github, like here - just write a comment. We can help you.

Ok ma'am

**Comment by chmst** [comment]
You have no conflict - but code style errors. Click on the Details button to see the errors in drone.

**Comment by rdeutz** [comment]
continue working on the other PR #32789
closing this one as duclicate

**Pull request closed without merging**
