### PR TITLE
[4.0] Choicies fix a bug with detaching

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #25672 and #23448

### Summary of Changes

Fix issue caused by moving the element in DOM tree.

Before testing, run `npm install`

### Testing Instructions

please read #25672 or #23448

### CODE REVIEW

**Comment by infograf768** [comment]
Thanks. It works here for categories, parent and tabs.
Looks like Hound is still not happy. restarted drone

**Comment by Fedik** [comment]
> Looks like Hound is still not happy.

it still need to fix, I just wanted to know if the patch helps  :wink:

**Comment by Fedik** [comment]
should be ok now

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 585245f0dfdcaa8269011144ed0771f9a2e9027a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25676">issues.joomla.org/tracker/joomla-cms/25676</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by Scrabble96** [comment]
Is this fix going to be in Alpha 12 Dev? It's not fixed in Alpha 11 dev (I have updated to the 6 August update) or the backend template linked to PR #25570. This is what happens if you narrow the screen:

module-positions-selection

**Comment by wilsonge** [comment]
Yes this will be in alpha 12. You can always test the latest code by using a nightly build here https://developer.joomla.org/nightly-builds.html which are rebuild from the latest code base every night

**Comment by wilsonge** [comment]
Although it should be in the backend template repo by now :/

**Comment by ghost** [comment]
@Scrabble96 using nightly builds you have to install them daily fresh as you can't updtae from nightly to nightly in alpha. This will change in beta.

**Comment by Scrabble96** [comment]
@franz-wohlkoenig  and @wilsonge: I am a little unsure whether the new backend template (as per #25570) has been incorporated into the main development package (and its nightly builds) or whether I still have to load them separately to view changes.

**Pull request merged**
