### PR TITLE
Update en-GB.com_menus.ini

### PR DESCRIPTION
**Pull request by MartijnMaandag**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
you are correct the string is incorrect but it should be past tense so "were" not "are"

(welcome home)

**Comment by MartijnMaandag** [comment]
Thanks, you are right.

**Comment by brianteeman** [comment]
I have made the change for you

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c6bba028fc680fd0e45ce20a94395b01e5948303<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17521">issues.joomla.org/tracker/joomla-cms/17521</a>.</sub>

**Pull request merged**
