### PR TITLE
Back-end Module Parameters - added validate=options

### PR DESCRIPTION
**Pull request by pe7er**
This PR adds validation to parameter fields of type=option to the parameters of .xml files **back-end Modules**

I've added
```xml
validate="options"
```
to all fields of type=list with defined options

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]
LGTM thanks

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on f6528b5b88ed2ca48d5b221a7872b79984082ea6<br /><br />I have tested this PR following these instructions:

1. Go to module manager
2. Filter to see admin modules
3. Create a new custom module
4. Go to advanced tab and choose a  caching  option (no caching for instance)
5. Inspect the html of that option with your browser and change the number to a random one (42 for instance)
6. Click on save

## Result  before  Patch

You are allowed to save the module

## Result after Patch

You are not allowed to save the module and an error message appears informing about the error in the cache field.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28830">issues.joomla.org/tracker/joomla-cms/28830</a>.</sub>

**Comment by luisorozoli** [comment]
I have tested this item :white_check_mark: successfully on f6528b5b88ed2ca48d5b221a7872b79984082ea6<br /><br />Tested successfully in launch joomla in J4. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28830">issues.joomla.org/tracker/joomla-cms/28830</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28830">issues.joomla.org/tracker/joomla-cms/28830</a>.</sub>

**Pull request merged**
