### PR TITLE
Correct since tags of previous commit

### PR DESCRIPTION
**Pull request by richard67**
### Summary of Changes

Correct erroneous since tags of new functions added with previous commit [https://github.com/joomla/joomla-cms/commit/7f2242144d25a9a079c7dc9319992343e4e666d1](https://github.com/joomla/joomla-cms/commit/7f2242144d25a9a079c7dc9319992343e4e666d1)
#### Testing Instructions

By review.

### CODE REVIEW

**Comment by richard67** [comment]
@rdeutz Please check and merge.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9938">issues.joomla.org/joomla-cms/9938</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 2e7edff5895dede6902bcdf3825ece23910a2ed0<br /><br />on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9938">issues.joomla.org/joomla-cms/9938</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 2e7edff5895dede6902bcdf3825ece23910a2ed0<br /><br />on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9938">issues.joomla.org/joomla-cms/9938</a>.</sub>

**Comment by richard67** [comment]
Thanks for "testing" .. I think this time my testing instructions were not too long :smile:

**Comment by rdeutz** [comment]
puh, that was hard :-)

**Pull request merged**
