### PR TITLE
[5.0] Add basic support for conditional dark mode themes in our editors

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/42148 and https://github.com/joomla/joomla-cms/issues/41801 .

### Summary of Changes
Supports dark mode detection for both tinymce and codemirror. Unlike the template which will actually flick over immediately once the OS is changed this will not change until the page is next reloaded. For codemirror this may be possible in the future as outlined in the todo in the code comment. But at the moment I don't believe this is possible for tinymce.

I've reused the same data attribute that @Fedik is suggesting in https://github.com/joomla/joomla-cms/pull/42221 (but I still disagree with the concept of a toggle in that PR - but this doesn't block that or alter that PR in any way). But the data attribute will be required on the body element to support this

### Testing Instructions
Open the editor in both light and dark modes. Before it would always open in light mode. Now it will match whatever the template is using on page load.

Note that casseopia which doesn't support automatic dark mode remains having editors only loaded in light mode.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/206
- [] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 006990139a6a5b0bb3e0e41e5abe344a39765fa3<br /><br />awesome!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42322">issues.joomla.org/tracker/joomla-cms/42322</a>.</sub>

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on b8eb1b7f390c1a5c02266523aee13cb2fc11967e<br /><br />Tested on Firefox with a dark mode toggle extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42322">issues.joomla.org/tracker/joomla-cms/42322</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b8eb1b7f390c1a5c02266523aee13cb2fc11967e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42322">issues.joomla.org/tracker/joomla-cms/42322</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42322">issues.joomla.org/tracker/joomla-cms/42322</a>.</sub>

**Comment by wilsonge** [comment]
As @Fedik says and as I put in the description this uses the same data attribute that he's using in his pull request to implement the switcher. So I don't understand why this is incompatible with adding the switcher even if I disagree with it.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
