### PR TITLE
[4.0] [SQL] Fix bottom-b module text

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #15353

### Summary of Changes

Fix the sample data module text

### Testing Instructions

- Reinstall Joomla and enable sample data

### CODE REVIEW

**Comment by yasirunilan** [comment]
I have tested this item :red_circle: unsuccessfully on 8d44bd57dae8d2842fe71e5146ca0d7d9034d42c<br /><br />I still see the text as "Bottom a"

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15366">issues.joomla.org/tracker/joomla-cms/15366</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 8d44bd57dae8d2842fe71e5146ca0d7d9034d42c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15366">issues.joomla.org/tracker/joomla-cms/15366</a>.</sub>

**Comment by C-Lodder** [comment]
@yasirunilan @frankmayer - I assume you tried re-installing Joomla and used sample data?

**Comment by franz-wohlkoenig** [comment]
Only applied PR – so have to reinstall 4?

**Comment by C-Lodder** [comment]
Yes. I've edited the installation SQL files :)

**Comment by franz-wohlkoenig** [comment]
Fresh Install: No top-a/b and bottom-a/b Modules installed. Click on Home-Menu got Log-in, after logIn and click on "Home got "The requested page can't be found."

**Comment by C-Lodder** [comment]
You may need to manually apply the patch.

Copy and paste the code from here: https://github.com/C-Lodder/joomla-cms/blob/8d44bd57dae8d2842fe71e5146ca0d7d9034d42c/installation/sql/mysql/sample_testing.sql

into `/installation/sql/mysql/sample_testing.sql`

then re-install Joomla, make sure you select "Yes" for sample data.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8d44bd57dae8d2842fe71e5146ca0d7d9034d42c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15366">issues.joomla.org/tracker/joomla-cms/15366</a>.</sub>

**Comment by yasirunilan** [comment]
I have tested this item :white_check_mark: successfully on 8d44bd57dae8d2842fe71e5146ca0d7d9034d42c<br /><br />Now it's working :smile: I didn't reinstall earlier.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15366">issues.joomla.org/tracker/joomla-cms/15366</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
