### PR TITLE
[5.2] Articles Module: Remove unused css + modified container query

### LINKED ISSUE #44369: New article module from J5.2.0 deactivates sticky header!
After a long search we found out the following:

If you use the new (from J5.2.0) post module and assign it to a module position, the sticky header (which appears when scrolling down with the menu and should always remain visible at the top) is deactivated (bypassed) on this page.

This only happens, however, if you use "Display / Layout / Horizontal" in the settings in the new module. If you switch to "Vertical", the sticky header function is executed again and the header appears on the page when scrolling down.

Image

At first I thought that there was a conflict with Astroid Framework 3.1.6 and Template Two (and other templates designed for it), but now that it's also happening with the Joomshaper Helix Ultimate Framework with the helix ultimate template, I suspect a BUG in the new post module.

What's striking is that it only happens when the display layout is set to horizontal. In this case, the module completely removes the sticky header and deactivates this function. Not good at all...

You're welcome to test it yourself.

What now?

### PR DESCRIPTION
**Pull request by drmenzelit**
### Additional change to fix #44369 
Modified the container query to address the div/section that is direct parent of the module.

### Summary of Changes
We removed some code from the Articles Module, but forgot to remove the related css. This PR remove some lines in the css file.

### Testing Instructions
Create an articles module.
Checkout the PR and run `npm run build:css` on your development environment

### Expected result AFTER applying this Pull Request
No differences in the styling of the module

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 11e8e258dcdeaa615e4e9f37a19215b96adfde8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by WM-Loose** [comment]
I have tested this item :white_check_mark: successfully on f29819091aa15e5d0c91687ac2084b4fe0bb1c26<br /><br />Thank you. The sticky header is now displayed even when the Article module is activated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by WM-Loose** [comment]
I have tested this item :red_circle: unsuccessfully on f29819091aa15e5d0c91687ac2084b4fe0bb1c26<br /><br />Retested after testing DEV in a wrong installation. Unfortunately the DEV version doesn't work either.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by WM-Loose** [comment]
I have tested this item :red_circle: unsuccessfully on f29819091aa15e5d0c91687ac2084b4fe0bb1c26<br /><br />Retested after testing DEV in a wrong installation. Unfortunately the DEV version doesn't work either.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by WM-Loose** [comment]
Retested after testing DEV in a wrong installation. Unfortunately the DEV version doesn't work either.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by fgsw** [comment]
@WM-Loose Can you delete 2 of your 3 identical comments above?

**Comment by WM-Loose** [comment]
I have tested this item :white_check_mark: successfully on f29819091aa15e5d0c91687ac2084b4fe0bb1c26<br /><br />It works now with5.2.1-dev+pr.44327

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f29819091aa15e5d0c91687ac2084b4fe0bb1c26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44327">issues.joomla.org/tracker/joomla-cms/44327</a>.</sub>

**Comment by pe7er** [comment]
Thanks @drmenzelit !

**Pull request merged**
