### PR TITLE
[4.0] Use the url for drag and drop in TinyMCE

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #36686.

### Summary of Changes
Draging an image into a TinyMCE editor instance uses the thumb path as image and not the full url. This is the same on the local adapter, but not on external adapters.

### Testing Instructions
- Open the article from in the back end
- Drag an image into the editor instance
- Inspect the ajax request with the dev tools of the browser

### Actual result BEFORE applying this Pull Request
The POST request has only the thumb_url field.

### Expected result AFTER applying this Pull Request
The POST request has the url field.

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo Are actual and expected result mixed up in the description? Or am I getting something wrong?

**Comment by laoneo** [comment]
Thanks for the hint. Too long day 😳

**Comment by dgrammatiko** [comment]
@laoneo check https://github.com/Digital-Peak/joomla-cms/pull/18

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on de5c97e3d9334bef97c6297fdc8fd91ee6a9ff1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36687">issues.joomla.org/tracker/joomla-cms/36687</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on de5c97e3d9334bef97c6297fdc8fd91ee6a9ff1c<br /><br />Works! URL parameter added to the output!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36687">issues.joomla.org/tracker/joomla-cms/36687</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36687">issues.joomla.org/tracker/joomla-cms/36687</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
