### PR TITLE
Add JMicrodata to popular articles module for schema.org microdata

### PR DESCRIPTION
**Pull request by photodude**
We have the JMicrodata library, lets actually use it.

Testing
1. Add patch
  https://docs.joomla.org/Testing_Joomla!_patches
2. Add a popular articles module to display
3. Check that microdata values are applied using a microdata validation tool
  https://developers.google.com/structured-data/testing-tool/

### CODE REVIEW

**Comment by sandstorm871** [comment]
I have tested this item :white_check_mark: successfully on e5481b151c0e652dc168b000d54b5742a203b117<br /><br />Added "Most Read" Module after patch & confirm that Microdata is now shown in the validation tool.
J3.5 Beta2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8934">issues.joomla.org/joomla-cms/8934</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on e5481b151c0e652dc168b000d54b5742a203b117<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8934">issues.joomla.org/joomla-cms/8934</a>.</sub>

**Comment by photodude** [comment]
@anibalsanchez, @sandstorm871 No actual change, just Rebased to staging...

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 96f41d7fbed2ed5ee37810b8d1999fb6330e9639<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8934">issues.joomla.org/joomla-cms/8934</a>.</sub>

**Comment by brianteeman** [comment]
Set to needs review for same reason as #8933 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8934">issues.joomla.org/joomla-cms/8934</a>.</sub>

**Comment by bertmert** [comment]
This PR makes no sense.
Property *name* is not supported by Google.
An *Article* without an Image less than 695px width is invalid.
An *Article* without a publisher is invalid.
and so on.

Nearly all structured data markups in Joomla are (Google) invalid meanwhile because the required combinations of properties are nearly never given.

Thus, only unnecessary HTML.

https://developers.google.com/structured-data/rich-snippets/articles#article_markup_properties

**Comment by photodude** [comment]
@bertmert This PR Just follows the same format already used in the hard-coded Joomla microdata for the latest articles module. The difference being the use of JMicrodata library rather than hard-coded structured data.

This PR is part of the [Larger discussion](https://github.com/joomla/joomla-cms/pull/8933) in consideration for whether to use Hard-coded microdata for the structured markup or to use the JMicrodata library. 

IMHO, Discussions about **IF** the existing "structured data markups in Joomla" are necessary or correct, are completely separate from the discussion that this and the other PR bring up. As such, your concerns would be more valuable [discussed in the mailing group](https://groups.google.com/forum/#!forum/joomla-dev-cms)

**Comment by photodude** [comment]
@bertmert I'm not agreeing or disagreeing, I just feel there is a better place for that discussion which would have more overall impact.

As for performance, I would agree that hard coded microdata would have better performance on a "non-cached" site. In the same way that a fully hard coded HTML file will be faster than a CMS that is dynamically serving content and queries a database. But the logic to that argument against using a dynamic library, for an encoding that can be dynamic, just because there is a performance difference in a non-cached setup; falls a bit flat for me as I believe a CMS should be capable of being dynamic, overridable, and simple to the end user.

I haven't run the numbers, but I doubt the performance impact of using the JMicrodata library in a non-cached site would be noticeable or significant vs Hard-coded markup. But I'm willing to accept that I could be wrong. Testing that and proving that there is a noticeable or significant difference for using the JMicrodata library vs hard-coded markup (in non-cached and cached) could make a difference in the overall discussion (or it would prove that it's a non-issue). Unfortunately, I don't have the time to do the testing right now.

**Comment by bertmert** [comment]
Performance was just a little addition at the end of my post.

**Comment by photodude** [comment]
@bertmert I took a look at your comment and the details in the supplied link

> Property name is not supported by Google.
> https://developers.google.com/structured-data/rich-snippets/articles#article_markup_properties

From the link I can see how you came to the conclusion that `name` is not a supported property for Google. It's easy to assume that `name` is not supported when it's not in the example. But that's misreading the example. You must look at the full [schema.org/Article](http://schema.org/Article) type to see what's supported. `name` is a parent property for articles from the [schema.org/Thing](http://schema.org/Thing) type. This is why the example links to the full [schema.org/Article](http://schema.org/Article) type so you can read the full specification and not just the supplied example. You can see that `name` is a fully supported type for an article by just running a test against [Google's microdata validation tool](https://developers.google.com/structured-data/testing-tool/)

**Comment by wilsonge** [comment]
Myself, Chris, Roland and Viktor have just discussed this and I think our decision is to stick with hardcoding this for the same reasons we chose not to use it in the first place. I'm going to close this PR and the other module ones for this reason

**Pull request closed without merging**
