### PR TITLE
[4.0] xml codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted these multiline options while checking a different bug.

This PR puts the options into one line to be consistent with all the other options

Code Review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1e87f4436a971edf30dd75e31244df7cd958f8a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26740">issues.joomla.org/tracker/joomla-cms/26740</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1e87f4436a971edf30dd75e31244df7cd958f8a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26740">issues.joomla.org/tracker/joomla-cms/26740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26740">issues.joomla.org/tracker/joomla-cms/26740</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
