### PR TITLE
Stop putting manifest in root of package to stop extension manager updates

### PR DESCRIPTION
**Pull request by wilsonge**
@mbabker can you review this is all that is required please? If it is please hit merge

### CODE REVIEW

**Comment by mbabker** [comment]
Looks fine

**Comment by andrepereiradasilva** [comment]
@wilsonge i now get a warning related to JInstaller manifest or something like that after updating from 3.4.8 to 3.5.0 RC2, i think it's because of this PR.
Should it work like this or it's a bug?

**Comment by mbabker** [comment]
How are you updating?  If the Extension Manager, fully expected.  If the update component, https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/models/default.php#L540 looks like there's no reason for it to spit out errors.

**Comment by andrepereiradasilva** [comment]
update component

**Comment by andrepereiradasilva** [comment]
to prove i'm not nuts ;)

image

**Comment by mbabker** [comment]
Found what I'm looking for.  Give me a few.

**Comment by andrepereiradasilva** [comment]
also got a lot of errors in the database not sure if related

image

**Comment by mbabker** [comment]
Test #9414

**Pull request merged**
