### PR TITLE
[4.0] com_joomlaupdate reference to class HtmlView

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

stumbled upon this issue while working on https://github.com/joomla/joomla-cms/pull/30171 and https://github.com/joomla/joomla-cms/pull/30168

### Summary of Changes

On of the benefits of working with an IDE like PHPStorm is that it gives me more information about my code then vi edito can do. :-) For instance.. CMD + Click on a reference to head directly to that function in that file. 
If set correctly!

### Testing Instructions

- Open an IDE like PHPStorm and open the changed files. (for instance : default_nodownload.php)
- Try to cmd/ctrl + click on `$this->getModel()`

- all template files from joomlaupdate should reference to the same class HtmlView (if needed)
 Only default_reinstall is set correct. 

### Actual result BEFORE applying this Pull Request

PHPStorm shows a yellow background color to indicate something. When hover HTML it informs you that class HTML cannot be found.

Schermafdruk 2020-07-24 13 46 13
Schermafdruk 2020-07-24 13 46 25 
Schermafdruk 2020-07-24 13 46 40

### Expected result AFTER applying this Pull Request

All files reference to the same class HtmlView, if needed... default_updatemefirst.php does not need the reference. 

Schermafdruk 2020-07-24 13 48 35

### CODE REVIEW

**Comment by david0296** [comment]
I have tested this item ✅ successfully 
After applying the PR, the IDE (I was using PHP Storm) indicates no more errors

**Comment by jmeintrup** [comment]
I have tested this item :white_check_mark: successfully on 5e27e8c44de6713da86ae21317a835fc7f08e09a<br /><br />Tested successfully with PHP Storm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30181">issues.joomla.org/tracker/joomla-cms/30181</a>.</sub>

**Comment by roland-d** [comment]
@hans2103 We have a file conflict since merging the Joomla updater changes

**Comment by hans2103** [comment]
@roland-d solved merge conflicts

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30181">issues.joomla.org/tracker/joomla-cms/30181</a>.</sub>

**Pull request merged**
