### PR TITLE
[4.0] [com_tags] Styling updates/improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #15774

### Summary of Changes

Just some general styling updates and improvements for `com_tags`

all-tags

### CODE REVIEW

**Comment by brianteeman** [comment]
The escaping/validation of the image and alt are different in each case

**Comment by C-Lodder** [comment]
@brianteeman - removed the `/` from one of the other images, but not sure what you're referring to with the "escaping/validation"

**Comment by brianteeman** [comment]
`image_fulltext, ENT_COMPAT, 'UTF-8'); ?>" alt="<?php echo htmlspecialchars($images->image_fulltext_alt); ?>">
`
`image_intro); ?>" alt="<?php echo htmlspecialchars($images->image_intro_alt); ?>">
`
`src="<?php echo $images->image_intro; ?>" alt="<?php echo htmlspecialchars($images->image_intro_alt); ?>">
`

**Comment by C-Lodder** [comment]
@wilsonge can be merged

**Pull request merged**
