### PR TITLE
[cs] Remove tabs

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove tabs.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d87d6a703da45cc0e37fe07bbc463aff11b0dcb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25157">issues.joomla.org/tracker/joomla-cms/25157</a>.</sub>

**Comment by lavipr** [comment]
I have tested this item :white_check_mark: successfully on d87d6a703da45cc0e37fe07bbc463aff11b0dcb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25157">issues.joomla.org/tracker/joomla-cms/25157</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25157">issues.joomla.org/tracker/joomla-cms/25157</a>.</sub>

**Comment by Quy** [comment]
@HLeithner  Please merge.

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
