### PR TITLE
Update query.php to have MySQL REPLACE command...

### PR DESCRIPTION
**Pull request by joaobsantos**
For example if i want to turn off help menu in joomla backend i´ll do something like this:

``` php
//Replacing a Record

$db = JFactory::getDbo();

$query = $db->getQuery(true);


$query->update($db->quoteName('#__modules'))

      ->set($db->quoteName('params'))

      ->replace('(`params`, \'showhelp\":\"1\', \'showhelp\":\"0\')')

      ->where('id' ."=" .'12');


$db->setQuery($query);

$result = $db->execute();
```

### CODE REVIEW

**Comment by mbabker** [comment]
Since it isn't MySQL specific syntax, the method's doc block shouldn't state that (otherwise it should be moved to the MySQL query subclasses, which after a quick search PostgreSQL and SQL Server use the same structure for REPLACE).  Also, the method needs a full doc block to pass our tests (you can use the one from set as a starting point).

**Comment by joaobsantos** [comment]
Ok i´ll try my best to fulfill you're requirements, it took my all morning to do this, just started programming 2 weeks ago... Do u think this is a good add-on for the code or not really?!

**Comment by alikon** [comment]
i'm viewing this by sql perspective,
 the ```replace()``` is a function and not a query element like ```SET```

for example this sql  is "legal"
```
select replace(field, 'oldstring', 'newstring'), fieldb,...
from table
where ....
```

so i'm not sure
 ```JDatabaseQueryElement``` is the best place ?

**Comment by mbabker** [comment]
Ya, from that aspect I'd say you're right.  I'd use the [concatenate](https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/joomla/database/query.php#L730) method as an example here.

**Comment by joaobsantos** [comment]
So i should use the concatenate method as an a example and make a REPLACE one?!

**Pull request closed without merging**
