### PR TITLE
[4.0] users reset/remind legend

### PR DESCRIPTION
**Pull request by brianteeman**
A fieldset should have a legend not a p

Code review and/or compare with other com_user forms

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cf92584f9cee3defa0267dab989c82f56815b071<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34055">issues.joomla.org/tracker/joomla-cms/34055</a>.</sub>

**Comment by brianteeman** [comment]
THIS IS NOT A TYPO

**Comment by richard67** [comment]
> THIS IS NOT A TYPO

Would be a funny typo if you wanna type `<legend>` and the result is `<p>` 😄

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cf92584f9cee3defa0267dab989c82f56815b071<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34055">issues.joomla.org/tracker/joomla-cms/34055</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34055">issues.joomla.org/tracker/joomla-cms/34055</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
