### PR TITLE
[4.4] Fix showon for list field (no multiple)

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #37851 .

### Summary of Changes

Adds an id attribute to the hidden input element when a list field is read-only
The id attribute is required for the showon function as it uses the field's id to get the value.
https://github.com/joomla/joomla-cms/blob/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90/build/media_source/system/js/showon.es6.js#L150

In the core I do not find this situation but a workaround for that case (added with #33096). Here the showon attribute is cleared or the field removed ...
https://github.com/joomla/joomla-cms/blob/4f1a4f15de6722c750c8a8a14cd0c95afc3ccd90/administrator/components/com_fields/src/Model/FieldModel.php#L566-L577

### Testing Instructions

Add following code to  `administrator/components/com_content/forms/article.xml`

image

copy template:

```xml
<fieldset name="showontest" label="SHOWONTEST">
	<field
		name="list1"
		type="list"
		label="LIST ENABLE"
		default="0"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
	</field>
	<field
		name="text1"
		type="text"
		label="TEXT 1"
		showon="list1:1"
	/>
	<field
		name="list2"
		type="list"
		label="LIST DISABLE"
		default="0"
		readonly="true"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
	</field>
	<field
		name="text2"
		type="text"
		label="TEXT 2"
		showon="list2:1"
	/>
</fieldset>

```

- visit site to add a new article
- check output and browsers debug console

### Actual result BEFORE applying this Pull Request

A js error exists because getElementById fails:
image

- field `TEXT1` is only visible when field `LIST ENABLE` have value `VALUE 1`
- field `TEXT2` is visible but should not
image

### Expected result AFTER applying this Pull Request

No longer a js error

- field `TEXT1` is only visible when field `LIST ENABLE` have value `VALUE 1`
- field `TEXT2` is not visible because field `LIST DISABLE` have value `VALUE 0`
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
@dgrammatiko Can you support me here? I have a problem when the multiple attr is set. You solved a similar problem with #35723. Thanks in advance.

**Comment by dgrammatiko** [comment]
Try changing https://github.com/joomla/joomla-cms/blob/4dcee6991fdbbef2daa20168d930f3b4e790dcb3/build/media_source/system/js/showon.es6.js#L145 to:

```js
} else if (originField.nodeName === 'SELECT' && originField.hasAttribute('multiple') && !originField.hasAttribute('disabled')) {
```

I haven't tested the code, maybe you can share some subform to make debugging easier

**Comment by heelc29** [comment]
> Try changing

@dgrammatiko I think it don't work because the `originField` is no longer a select
image

```html
<div class="controls">
	<select id="jform_list4" name="" class="form-select" multiple="" disabled="disabled">
		<option value="0" disabled="disabled" selected="selected">VALUE 0</option>
		<option value="1" disabled="disabled">VALUE 1</option>
		<option value="2" disabled="disabled" selected="selected">VALUE 2</option>
	</select>
	<input type="hidden" name="jform[list4][]" value="0">
	<input type="hidden" name="jform[list4][]" value="2">
</div>
```

> 
> I haven't tested the code, maybe you can share some subform to make debugging easier

I added this to `administrator/components/com_content/forms/article.xml`
image

<details>
<summary>debug code</summary>

```xml
<fieldset name="showontest" label="SHOWONTEST">
	<field
		name="list1"
		type="list"
		label="LIST ENABLE"
		default="0"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
	</field>
	<field
		name="text1"
		type="text"
		label="TEXT 1"
		showon="list1:1"
	/>
	<field
		name="list2"
		type="list"
		label="LIST DISABLE"
		default="0"
		readonly="true"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
	</field>
	<field
		name="text2"
		type="text"
		label="TEXT 2"
		showon="list2:1"
	/>

	<field
		name="list3"
		type="list"
		label="LIST ENABLE MULT"
		multiple="true"
		default="[0,2]"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
		<option value="2">VALUE 2</option>
	</field>
	<field
		name="text3"
		type="text"
		label="TEXT 3"
		showon="list3:1"
	/>
	<field
		name="list4"
		type="list"
		label="LIST DISABLE MULT"
		multiple="true"
		default="[0,2]"
		readonly="true"
		>
		<option value="0">VALUE 0</option>
		<option value="1">VALUE 1</option>
		<option value="2">VALUE 2</option>
	</field>
	<field
		name="text4"
		type="text"
		label="TEXT 4"
		showon="list4:1"
	/>
</fieldset>

```
</details>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by Hackwar** [comment]
Could you make this PR ready so that we can test this during PBF?

**Comment by heelc29** [comment]
@Hackwar I've updated the testing instructions.

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 91bc2cd301a6052e8ca6bff2fc80f71cd9b971f3<br /><br />Tested Successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39546">issues.joomla.org/tracker/joomla-cms/39546</a>.</sub>

**Comment by tomsrocket** [comment]
I have tested this item :white_check_mark: successfully on 91bc2cd301a6052e8ca6bff2fc80f71cd9b971f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39546">issues.joomla.org/tracker/joomla-cms/39546</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
