### PR TITLE
[4.0]Fix loading language files from module extension folder

### PR DESCRIPTION
**Pull request by joeforjoomla**
Pull Request for Issue #22768 .

### Summary of Changes
dirname(..) is not referring to the correct file/path anymore, that is causing the loading of modules language files failing.

### CODE REVIEW

**Comment by infograf768** [comment]
Why do we use `dirname` ?

If I use
`$extensionLanguageDirectory = JPATH_BASE . '/modules/' . $this->module->module;`

it works fine.
@laoneo ?

**Comment by laoneo** [comment]
I think too that the extra call of dirname can be removed.

**Comment by infograf768** [comment]
@joeforjoomla 
can you modify your PR ?

**Comment by joeforjoomla** [comment]
I modified the PR, basically removing the extra dirname works the same

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a6f4746aafb49f1479fd72be47fb570518f349f3<br /><br />Can now be merged on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22786">issues.joomla.org/tracker/joomla-cms/22786</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
