### PR TITLE
[4.0] Fix IE11 Login page gradient position

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #23805

### Summary of Changes

Fix the position of the gradient on the Login page in IE11

### Testing Instructions

Visit the admin login page in IE11

### Expected result

Should look the same as good browsers

### CODE REVIEW

**Comment by ReLater** [comment]
Please excuse my sacrilegious question. Do we really need this ugly wallpaper and gradients on the login page? Or at least: Why this gradient?

**Comment by C-Lodder** [comment]
@ReLater Just the design that was provided

**Comment by coolcat-creations** [comment]
@C-Lodder we are working on the login page, especially to meet more design consistency it was stated in another PR / Issue from Dimitris. 
We will add a PR soon for that...

Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23945">issues.joomla.org/tracker/joomla-cms/23945</a>.</sub>

**Comment by C-Lodder** [comment]
Can you share some sort of roadmap please? I spent a long time testing the backend and reporting issues. There are also a load more to report so I dont want to waste any more time reporting or fixing issues for no reason

**Comment by C-Lodder** [comment]
Closing as unneeded

**Comment by brianteeman** [comment]
Why is it not needed?

**Comment by C-Lodder** [comment]
Because the template team are working on it already.

**Comment by brianteeman** [comment]
Guess you and other volunteers just wasted your time then

**Pull request closed without merging**
