### PR TITLE
Remove duplicate code and extend JFilters from Framework

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue "JFilter was not extend from [Framework Filter](https://github.com/joomla-framework/filter): thus duplicate code"
#### Summary of Changes

Remove duplicate code and extend JFilters from Framework
#### Testing Instructions
1. add patch to 3.5B3 or staging
   https://docs.joomla.org/Testing_Joomla!_patches
2. navigate to the backend and frontend and be sure nothing is broken
3. review various forms in the backend and frontend still work
4. report your result back here

Thanks to @mbabker and @wilsonge for their help and guidance on this correction.

### CODE REVIEW

**Comment by shubhamnba2009** [comment]
I have tested this item :white_check_mark: successfully on https://github.com/joomla/joomla-cms/commit/55256bec3dfc6fea33ae0ecf5c08ff0cd879ee19
I reviewed the front end and back end going through articles and category form.And they work successfully.

**Comment by wilsonge** [comment]
RTC

**Comment by photodude** [comment]
Thanks @shubhamnba2009 and @grhcj For Testing so this could reach RTC.

**Comment by wilsonge** [comment]
This will be merged in 3.5.1 - I'm trying to only merge critical fixes for 3.5.0 at this point!

**Comment by photodude** [comment]
Understood @wilsonge , I think 3.5.1 milestone is an appropriate choice for this; Especially at this point. (onward towards 3.5.0RC)

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 55256bec3dfc6fea33ae0ecf5c08ff0cd879ee19<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9264">issues.joomla.org/joomla-cms/9264</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9264">issues.joomla.org/joomla-cms/9264</a>.</sub>

**Comment by rdeutz** [comment]
@photodude could you have a look at the merging conflicts, thanks

**Comment by photodude** [comment]
@rdeutz The merge conflicts should be fixed now.

**Pull request merged**
