### PR TITLE
Cassopeia rtl update

### PR DESCRIPTION
**Pull request by brianteeman**
remove skipto override as its fixed upstream
remove metis-toggler as its a duplicate
change metis-toggler to use logical operators
change navbar-brand to use logical operators
change jmodedit to use logical operators

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on bacf8ff0fe3579625ee1bad213988839e52ff56f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36040">issues.joomla.org/tracker/joomla-cms/36040</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on bacf8ff0fe3579625ee1bad213988839e52ff56f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36040">issues.joomla.org/tracker/joomla-cms/36040</a>.</sub>

**Comment by HLeithner** [comment]
If I'm correct we don't use `inset-inline-end` till now, is it save for us to use it?

**Comment by brianteeman** [comment]
Perfectly safe to use https://caniuse.com/?search=inset-inline-end

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36040">issues.joomla.org/tracker/joomla-cms/36040</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on bacf8ff0fe3579625ee1bad213988839e52ff56f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36040">issues.joomla.org/tracker/joomla-cms/36040</a>.</sub>

**Comment by infograf768** [comment]
Screen Shot 2021-11-16 at 08 47 53

**Comment by HLeithner** [comment]
I have seen this too JM, and I think it breaks our policy CURRENT - 2 (also current depends of the time of the major or minor release, but I'm not sure on this topic).

based on this information all PRs including 'inset-inline-end' is too early for us but have to be discussed by production

**Comment by brianteeman** [comment]
i thought it was changed to current -1

**Comment by HLeithner** [comment]
> #PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. (per 19/05/16)

was the last motion I found... should be moved to the development strategy

**Comment by C-Lodder** [comment]
@HLeithner Your `package.json` states otherwise:

```
"browserslist": [
    "last 1 version",
    "not ie < 11"
],
```

**Comment by brianteeman** [comment]
and before that it was in `settings.json` where it was merged 5july **2018**

**Comment by infograf768** [comment]
FYI, concerning Safari versions: 14.1 was an update for Mac OS Big Sur, i.e. all former versions of MacOS using Safari 14 or lower will not be compatible. Mac OS Monterey has Safari 15.

**Comment by HLeithner** [comment]
> @HLeithner Your `package.json` states otherwise:
> 
> ```
> "browserslist": [
>     "last 1 version",
>     "not ie < 11"
> ],
> ```

then the package.json is wrong and has to be fixed

**Comment by C-Lodder** [comment]
lol, after 3 and a half years?
Sounds like the motion was incorrectly written without prior research.

**Comment by HLeithner** [comment]
> lol, after 3 and a half years? Sounds like the motion was incorrectly written without prior research.

no idea why it's funny when an error happens. we have 15 year old bugs.

**Comment by brianteeman** [comment]
I leave it to those far more important than me to decide. _note that the settings are used to determine if autoprefix etc needs to do something to ensure old browser support_

**Comment by brianteeman** [comment]
Changing to last 2 version will result in a massive amount of changes to the css generated by the autoprefixer. As a very quick example we will see the following changes in `build_incomplete.html`

image

**Comment by richard67** [comment]
Setting RLDQ label so release leads can decide about usage of inset-inline regarding our browser support policy.

**Comment by brianteeman** [comment]
Further information. Please remember that we have been wrorking and testing with `last 1 version` for 3.5 years. If you rebuild the current css with `last 2 version` you will see how much is different - about 9% bigger. _(these tests are without by pull requests as they're not merged)_

## CSS Line Count
|Template|last 1 version|last 2 version|
|----------|----------|----------|
|Atum|14516|15884|
|Atum RTL|14807|16145|
|Cassiopeia|13552|14845|
|Cassiopeia RTL|13829|15122|

**Comment by wilsonge** [comment]
> FYI, concerning Safari versions: 14.1 was an update for Mac OS Big Sur, i.e. all former versions of MacOS using Safari 14 or lower will not be compatible. Mac OS Monterey has Safari 15.

So based on this high sierra is the highest OSX version that is affected by this but already had no security support when Joomla 4.0.0 came out (security support ended december 2020). Given our CSS is already bugged in terms of giving support for this version as well I don't think it's a big deal merging these Pull Requests at this moment in time. Especially given the big savings we get in maintainability.

**Comment by richard67** [comment]
@wilsonge Thanks for this decision which I fully support.

**Comment by brianteeman** [comment]
Thanks for making a sensible decision.

**Pull request merged**
