### PR TITLE
[4.0] yubikey text

### PR DESCRIPTION
**Pull request by brianteeman**
don't display the heading additionally in the body

Pull Request for Issue #30874

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0dec0db65341c3871b2dedac10bd7474cab4e9ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30879">issues.joomla.org/tracker/joomla-cms/30879</a>.</sub>

**Comment by AndyGaskell** [comment]
I had a quick look at testing this, but it seemed like you'd not be able to test it unless you owned a physical YubiKey, which I don't.  Text change sounds good though.

**Comment by brianteeman** [comment]
@AndyGaskell just enable the plugin and then go to your user profile in the admin

**Comment by AndyGaskell** [comment]
@brianteeman Yea, I tried that, but can't see this text.  I guess, with the text being...
`Your YubiKey is already linked to your user account. `
...you have to have a YubiKey already, then try to add another, or something like that.  I'm not so familiar with YubiKey stuff, though it's a cool idea and bit of hardware.

yubikey_screen

**Comment by joomlacorner** [comment]
I have tested this item :white_check_mark: successfully on 0dec0db65341c3871b2dedac10bd7474cab4e9ba<br /><br />tested with Yubikey worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30879">issues.joomla.org/tracker/joomla-cms/30879</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30879">issues.joomla.org/tracker/joomla-cms/30879</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
