### PR TITLE
[4.1-dev] Fix DB query in `Scheduler::getTaskRecords()`

### PR DESCRIPTION
**Pull request by ditsuke**
### Summary of Changes
Something broke the `SELECT *` query, resulting in a NULL id when
it was finally evaluated against the DB in TasksModel. This broke
the `scheduler:run` console command which is fixed by this commit.

### Testing Instructions
- Create a scheduled task.
- Trigger the scheduler from the CLI: `php joomla.php scheduler:run`.

### Actual result BEFORE applying this Pull Request
```
Run tasks
=========


In OptionsResolver.php line 1060:

  The option "id" with value null is expected to be of type "numeric", but is of type "null".

```

### Expected result AFTER applying this Pull Request
```
Run tasks
=========

Task#02 'Some Task' processed in 5.12 seconds.

Finished running 1 tasks in 5.12 seconds.
```

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 93dd1d6d39a8aa825990d328e8b4e8415fce2c73<br /><br />Works with MySQL as well as with PostgreSQL.

Hint for other testers: The error fixed by this PR only happens when the task needs to run. I.e. if the task is scheduled to run every 5 minutes, it might take up to 5 minutes until you get the error for the first time, and then again 5 minutes until next time. In between, when the task doesn't need to be run, you get a "No tasks due!" message without and with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37463">issues.joomla.org/tracker/joomla-cms/37463</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 93dd1d6d39a8aa825990d328e8b4e8415fce2c73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37463">issues.joomla.org/tracker/joomla-cms/37463</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37463">issues.joomla.org/tracker/joomla-cms/37463</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by ditsuke** [comment]
Thanks!

**Pull request merged**
