### PR TITLE
Select not click

### PR DESCRIPTION
**Pull request by brianteeman**
Update to en-gb language files to take into account mobile/tablet use where you can not click.

This was first done in #7430 but some have slipped back in

Basically it replaces click with select - Click refers to a mouse and is not relevant if using a tablet or a phone without a keyboard.

NOTES
I have kept banner impressions to refer to clicks
I have kept weblink impressions to refer to clicks

I have kept joomla-update as "one-click" as that was the marketing

Please remember the most important object of the exercise is to make the language files consistent

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fb63c5bc29d04087d915acef0801ea1f1a2fb256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19310">issues.joomla.org/tracker/joomla-cms/19310</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on fb63c5bc29d04087d915acef0801ea1f1a2fb256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19310">issues.joomla.org/tracker/joomla-cms/19310</a>.</sub>

**Comment by Anu1601CS** [comment]
RTC

**Comment by Quy** [comment]
RTC

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
