### PR TITLE
[5.0] Remove wincache

### PR DESCRIPTION
**Pull request by brianteeman**
Removes all traces of wincache.

WinCache is abandoned and not supported from PHP 8 onwards

code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: (https://github.com/joomla/Manual/pull/186)
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
documentation is needed, at least the b/c break notice on manual.j.org

**Comment by brianteeman** [comment]
> documentation is needed, at least the b/c break notice on manual.j.org

doing that now - please note that the 5.0 links on m.j.org are broken

**Comment by brianteeman** [comment]
image

**Comment by brianteeman** [comment]
manual pr https://github.com/joomla/Manual/pull/186

**Comment by HLeithner** [comment]
ah yes ... will be part of the restructuring....

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
