### PR TITLE
[4.0] Remove arguments of Factory::getApplication as they are misleading

### PR DESCRIPTION
**Pull request by laoneo**
`Factory::getApplication();` doesn't take any arguments anymore and will return always the global application object which must be set by the front controller during the set up phase. The problem on that part in J3 is that the code 

```
$app = JFactory::getApplication('site');
$app = JFactory::getApplication('administrator');
echo $app->getName();
// Returns site and not administrator
```
will always return the site app, despite the administrator app is requested. This can be done now trough `Factory::getContainer()->get('SiteApplication');` which will return a site application even on the back end.

I'm splitting #16918 into different pr's to be easier to review.

### CODE REVIEW

**Comment by wilsonge** [comment]
So if we do this do we actually want to have the `CMSApplication::getInstance` method at all? Because that's going to be totally unused. Thoughts @mbabker

**Comment by mbabker** [comment]
If we are removing the app singletons we need to ensure that running the app constructors multiple times doesn't create side effects on the primary app and dependencies.

**Comment by laoneo** [comment]
`CMSApplication::getInstance` is [deprecated](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/CMSApplication.php#L477) anyway in favor of getting them from the container. If we need singletons, then we can make them shared in the container?

**Comment by mbabker** [comment]
Most of the container services are shared already anyway.  But even outside of that, my point isn't about having singletons but about ensuring that running `new SiteApplication` multiple times doesn't cause issues because there is some arbitrary logic in the constructors that can affect global services like the session.

**Comment by laoneo** [comment]
I guess we should keep `CMSApplication::getInstance` for BC during the 4 series. This would avoid then having multiple applications or?

**Comment by wilsonge** [comment]
Ahh i missed `CMSApplication::getInstance` was checking in the container. Sorry. Then I guess this is fine

**Comment by mbabker** [comment]
Regardless of whether the getInstance method lives forever or disappears tomorrow, we still need to ensure that running the constructors multiple times doesn't create side effects.  That is the only concern with removing this specific singleton store, every other service that has singleton doesn't have global reach like the application does.

- [These lines](https://github.com/joomla/joomla-cms/blob/2794f611c48c7451f7b971e2af4fcff09b916392/libraries/src/Application/CMSApplication.php#L133-L143) in the CMSApplication constructor which changes the configuration regarding some session data
- The [loadSystemUris method](https://github.com/joomla/joomla-cms/blob/2794f611c48c7451f7b971e2af4fcff09b916392/libraries/src/Application/WebApplication.php#L336) in the WebApplication which is parsing the request URI and storing data in the configuration
- [This line](https://github.com/joomla/joomla-cms/blob/2794f611c48c7451f7b971e2af4fcff09b916392/libraries/src/Application/AdministratorApplication.php#L56) in the AdministratorApplication constructor which is resetting `Joomla\CMS\Uri\Uri::root()`

This is a move in the right direction, just pointing out technical concerns in getting to the end state.

**Comment by laoneo** [comment]
Needs the "Documentation Required" label.

**Comment by wilsonge** [comment]
Thanks done!

@mbabker just to confirm that only applies to when we remove `CMSApplication::getInstance` and not this PR right?

**Comment by mbabker** [comment]
Right.

**Pull request merged**
