### PR TITLE
Update languagefilter.php

### PR DESCRIPTION
**Pull request by coolcat-creations**
Fix language declaration. Has to be the first 2 letters and not en-Gb, de-DE .... etc.

Pull Request for Issue # .

### CODE REVIEW

**Comment by C-Lodder** [comment]
According to Google, the region is optional and doesn't _have_ to be 2 characters only.

**Comment by infograf768** [comment]
Please explain further what you want to achieve.
1. Let's not forget that we may have language tags of type:
`ckb-IQ`, `prs-AF`, etc
2. A multilingual site may use `en-GB` AND `en-US` AND `en-AU`.

**Comment by infograf768** [comment]
Please close as this is breaking the hreflang for the cases above.

**Comment by infograf768** [comment]
@C-Lodder 
Reminder: Concerning the "region" it was decided a long time ago that we would use country codes and never regions. Which means that we always have 2 letters for the country code.

**Comment by C-Lodder** [comment]
@infograf768 Globally in Joomla or just in the language filter? Seems a bit silly considering languages have different dialects

**Comment by brianteeman** [comment]
Not sure what you are trying to achieve here but it looks like @infograf768 is correct

**Comment by infograf768** [comment]
> Globally in Joomla or just in the language filter? Seems a bit silly considering languages have different dialects

Globally in Joomla and any CMS. Servers never consider regions (they may even not consider various country codes, depending on servers..)

We never consider dialects but languages and we do not use Extended Language Subtags.
It could be considered though in the future (for various variations of Chinese for example: zh-yue (Cantonese Chinese)).
I guess this would imply a few code changes. No one ever proposed such a pack until now.

See the mess here if we were for French (not taking into account that these provincial iso codes are never considered by any sotware...):
https://en.wikipedia.org/wiki/ISO_3166-2:FR

What you call a dialect may have a specific langage code: 
Iraq country code may have
ar-IQ, ckb-IQ, kmr-IQ, sdh-IQ, etc.
Where the last 3 are variations of the Kurdish language.
https://en.wikipedia.org/wiki/Kurdish_languages

**Comment by infograf768** [comment]
Let's close this. If someone is interested in implementing Extended Language Subtags, please submit a PR.

**Comment by C-Lodder** [comment]
@infograf768 

> Servers never consider regions

The `hreflang` tag is used by search engines to serve the right content to the right users. So I'm not sure how removing the dialect helps with that.

**Comment by infograf768** [comment]
@C-Lodder 
I do not understand your comment.
Joomla never simplifies a lang tag of type xx-XX or xxx-XX in hreflang or elsewhere, and that is correct.

**Comment by C-Lodder** [comment]
@infograf768 You say that Joomla never simplifies the lang and then said that Joomla doesn't use regions, but the `-XX` _is_ the region

**Comment by infograf768** [comment]
I call this Country Codes, not regions.

**Comment by infograf768** [comment]
regions are Extended Language Subtags and we do not use them in Joomla.

Edit: Example
zh-yue (Cantonese Chinese)

**Comment by richard67** [comment]
If you want to have 2 letter codes only, you can use the languagecode plugin.

**Comment by coolcat-creations** [comment]
Right thank you for taking care of this, I misunderstood the requirements. 
It should be like that de and en for example is two letters only to be recognized by other countries that speak this language too - does not count for all languages. I will look into the languagecode plugin.

**Pull request closed without merging**
