### PR TITLE
[4.0] Workflow access xml

### PR DESCRIPTION
**Pull request by brianteeman**
Replacement PR for #22883

Summary of Changes
Remove description because all other core components are now without description

Testing Instructions
Code inspection

@chmst

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4ed8b1b614212e8429fd1cea247383d63536b967<br /><br />Tahnk you, @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22889">issues.joomla.org/tracker/joomla-cms/22889</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4ed8b1b614212e8429fd1cea247383d63536b967<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22889">issues.joomla.org/tracker/joomla-cms/22889</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22889">issues.joomla.org/tracker/joomla-cms/22889</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
