### PR TITLE
[fix] #5554, Adding tags when editing articles.

### PR DESCRIPTION
**Pull request by jackkum**
https://github.com/joomla/joomla-cms/issues/5554 and https://github.com/joomla/joomla-cms/issues/5455

### CODE REVIEW

**Comment by infograf768** [comment]
@test
This works here. Will close https://github.com/joomla/joomla-cms/issues/5554 and https://github.com/joomla/joomla-cms/issues/5555

**Comment by waader** [comment]
@test success!

**Comment by wilsonge** [comment]
This might fix the issue but is a horrific hack. This effectively nulls the entire where statement. In which case you may as well remove it all together (but not sure if that is the right answer either)

**Comment by jackkum** [comment]
@wilsonge 
Agree it is a crutch.
Another solution can only see in union 2 queries.

**Comment by jackkum** [comment]
Why not use "where" like zf? 
https://github.com/zendframework/zf1/blob/master/library/Zend/Db/Select.php#L473

**Comment by wilsonge** [comment]
We do have a second parameter for where (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L1492)

**Comment by jackkum** [comment]
it is apply for all where conditions.

**Comment by gunjanpatel** [comment]
Agree with @jackkum here. We have second argument but it applies to all where. So, if we want to write query with `AND` and `OR` condition together it's somehow not possible in current `where` function.

**Comment by Joomti** [comment]
For me it works as it should.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5601">issues.joomla.org/joomla-cms/5601</a>.</sub>

**Comment by wilsonge** [comment]
I'm closing this as it's completely the wrong fixed as I described. We need to rewrite this query properly rather than adding this statement

**Comment by vdespa** [comment]
I am not very familiar with the internals of com_tags, but this seems rather like a limitation and not a bug. You can later add tags if you write 3 letters from the tag it will be displayed. 

If this PR is not updated in the next 30 days, it would be closed, as it cannot be merged in the current state.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5601">issues.joomla.org/joomla-cms/5601</a>.</sub>

**Comment by wilsonge** [comment]
@vdespa i think you are commenting on the wrong issue ^.^

**Pull request closed without merging**
