### PR TITLE
Remove senseless proxy functions

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
- Removed senseless proxy functions

### Testing Instructions

None, should not change behavior

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 5343c075f051c0f99d7d9b27dada46ba407fc4fb<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13198">issues.joomla.org/tracker/joomla-cms/13198</a>.</sub>

**Comment by wilsonge** [comment]
Can we revert the change to restore.php please? That's a 3rd party file effectively :)

**Comment by frankmayer** [comment]
@wilsonge OK

**Comment by wilsonge** [comment]
Thankyou :)

**Pull request merged**
