### PR TITLE
Missing message status "success"

### PR DESCRIPTION
**Pull request by degobbis**
without array-index "success" this message output create a PHP-Notice "undefined index on..."

### CODE REVIEW

**Comment by Bakual** [comment]
There is no "success" message type. See https://docs.joomla.org/Display_error_messages_and_notices
There are
* warning
* notice
* error
* message (or empty)

closing as this is an issue of the extension in question and not from core.

**Comment by degobbis** [comment]
Since Joomla! 3 uses bootstraped templates, the messages will use the standard bootstrap CSS styles for Alerts.
https://docs.joomla.org/Display_error_messages_and_notices#Joomla.21_3.x_is_bootstrapped

If I like a green (success) output for my message, at first I look in Joomla! core output (/layout/joomla/system/message.php). If I use "message" the standard Joomla! output for messagebox is yellow (Notice), I like green. To handle this my code must be "success" a message type for the right output.

Now, if you like to reconfigure this in an override, best practice will be to rewrite the standard. 
In Bootstrap 2 this will be 
- alert-info for blue
- alert-warning for yellow (default)
- alert-error for red
- alert-success for green

If someone else uses an other template, without your override, the only possibility to get a green messagebox is to set my message type basicly to "success"

Finaly, this protostar override couses an PHP-Notice.

**Comment by Bakual** [comment]
I don't say we should not fix the notice, but this PR is the wrong approach. It comes from the fact that the extension uses a "custom" type for the enqueueMessage method.

What you should instead do is check if the key exists in the `$alert` array and if not just use the type directly. Something like
`<div class="alert <?php echo isset($alert[$type]) ? $alert[$type] : 'alert-' . $type; ?>">`

**Comment by degobbis** [comment]
ok, is the better way to fix this notice :-)

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/7892

**Pull request closed without merging**
