### PR TITLE
[PHP 8.1] Fix indexing newsfeeds with no summary

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Fixes indexing news feed items when creating sample data. If no summary is present then it needs a string and not null.

### Testing Instructions
Requires parallel application of https://github.com/joomla/joomla-cms/pull/38101

Install sample data from Joomla

### Actual result BEFORE applying this Pull Request
Errors installing sample data

### Expected result AFTER applying this Pull Request
Sample data successfully installs

### Documentation Changes Required
N/A

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Review by Hackwar — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 30269aa57ec9680dc008393265c76f663d5ca032<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38102">issues.joomla.org/tracker/joomla-cms/38102</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 30269aa57ec9680dc008393265c76f663d5ca032<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38102">issues.joomla.org/tracker/joomla-cms/38102</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38102">issues.joomla.org/tracker/joomla-cms/38102</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
