### PR TITLE
[4.0] Cassiopeia - Add overflow hidden to ul and ol

### PR DESCRIPTION
**Pull request by YatharthVyas**
Pull Request for Issue #33501

### Summary of Changes
Added `overflow: hidden` to `<ul>` and `ol` globally.
Lists that are to the right of images having `float: left` retain their indentations for li, all other lists are not affected by this.

### Testing Instructions
Prerequisites: Install blog sample data
- Apply Patch
- `npm run build:css`
- Frontend: Visit the blog 'Your Modules' and check the list indentation
- Also, check any blog article that has a list without an image. In this case, everything should remain as is.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
inline style is not a solution. this must be addressed further up the chain directly in the template

**Comment by YatharthVyas** [comment]
> inline style is not a solution. this must be addressed further up the chain directly in the template

Is https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/template-rtl.scss the correct file to add
```css
ul,
ol {
    overflow: hidden;
}
```

**Comment by chmst** [comment]
no. this is for right-to-left - specific things.

These general tags are better defined in /cassiopeia/scss/blocks/_global.scss

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9569f772d9ff5c721d45f9073d63ec9529a32a79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33560">issues.joomla.org/tracker/joomla-cms/33560</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9569f772d9ff5c721d45f9073d63ec9529a32a79<br /><br />Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33560">issues.joomla.org/tracker/joomla-cms/33560</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33560">issues.joomla.org/tracker/joomla-cms/33560</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by richard67** [comment]
This has broken the accessible pulldown menu (metismenu) and possibly other pull.downs in frontend (Cassiopeia), see issue #33617 .

**Pull request merged**
