### PR TITLE
[3.x] Typo / Spelling BASIS

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes obvious typing/spelling error BASIS should be BASIC

code review

This is a 3.x version of #31361 - it has to be done as separate PR because just merging this one into 4 will not fix everything in 4

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 68edb4a8c39f4374003d23417e853c587487f42f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31362">issues.joomla.org/tracker/joomla-cms/31362</a>.</sub>

**Comment by richard67** [comment]
@ceford As you have tested the other one for J4, can you test this one here for J3, too? Thanks in advance.

**Comment by SharkyKZ** [comment]
Isn't removing strings a B/C break?

**Comment by richard67** [comment]
Oh yes.

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31362">issues.joomla.org/tracker/joomla-cms/31362</a>.</sub>

**Comment by brianteeman** [comment]
Oops I forgot

Closing

**Comment by richard67** [comment]
Would it make sense to do this fix for J3, only not deleting the old language strings but marking with a deprecation comment line above them, telling to use the new ones, and adding the new language strings (new constants)?

**Comment by brianteeman** [comment]
Dont think its worth it

**Pull request closed without merging**
