### PR TITLE
[4.0] newsflash string

### PR DESCRIPTION
**Pull request by brianteeman**
Removes an unused string

code review

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3e582908492dd14044ce2cc7e4e22992cbfe06c3<br /><br />Tested successfully in Beta6-dev of 13 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31640">issues.joomla.org/tracker/joomla-cms/31640</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3e582908492dd14044ce2cc7e4e22992cbfe06c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31640">issues.joomla.org/tracker/joomla-cms/31640</a>.</sub>

**Comment by infograf768** [comment]
Not sure about this one
I guess we should OR add back the desc in the xml OR modify `MOD_ARTICLES_NEWS_TITLE_HEADING` to specify that it concerns the articles titles. The fact that it follows the Article Title and Linked titles is not enough imho.

**Comment by brianteeman** [comment]
Context is everything. You wouldnt even have questioned it if I wasnt removing an unused string

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31640">issues.joomla.org/tracker/joomla-cms/31640</a>.</sub>

**Comment by richard67** [comment]
I can confirm the string isn't used anywhere, and the PR has 2 good tests, so I've set it RTC. If it needs to make the meaning of the field more clear, I suggest to make a new PR e.g. for changing the title.

**Comment by HLeithner** [comment]
I have no idea why we delete all descriptions in j4 (because there are better ways to show them) but it is what it is.

Thanks for the cleanup

**Comment by richard67** [comment]
> I have no idea why we delete all descriptions in j4 (because there are better ways to show them) but it is what it is.

Exactly my feeling, I couldn't have expressed it better.

**Pull request merged**
