### PR TITLE
[4.0] Remove Settings text from legend

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove `Settings` in legends to be consistent with the other configuration pages.

### Testing Instructions
Go to Global Configurations.
See legends with the word `Settings`.

Go to the other configuration pages.
See legends without the word `Settings`.

### CODE REVIEW

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on da6015541db89e7cabd79ea79dad74c809004f0d<br /><br />- After patch applied, word settings removed from legends in tabs Site, System, Server, Text Filters, Permissions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26962">issues.joomla.org/tracker/joomla-cms/26962</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on da6015541db89e7cabd79ea79dad74c809004f0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26962">issues.joomla.org/tracker/joomla-cms/26962</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26962">issues.joomla.org/tracker/joomla-cms/26962</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
