### PR TITLE
[4.0] remove field spacer from Menu category blog

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #30860 .

### Summary of Changes
remove field spacer

### Testing Instructions
see  #30860 

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

Screenshot from 2020-10-04 09-44-04

### CODE REVIEW

**Comment by gostn** [comment]
I have tested this item :white_check_mark: successfully on e681c19301e0dfc45f8d51fe91f49aa1694a554d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by brianteeman** [comment]
Please do not commit this **until** a decision is made about keeping the 3 column layout or not.

**Comment by alikon** [comment]
did you mean this one #29706  ?

**Comment by brianteeman** [comment]
yes - but I am sure there are other issues about this as well.  The three columns looks nice but its not usable. And when you go back to the single column then a spacer like the one in this PR can be useful

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on e681c19301e0dfc45f8d51fe91f49aa1694a554d<br /><br />The PR does what it says. But even if present what does the spacer mean? On a 768 pixel wide screen the form comes out in two columns that is wider than the screen. The one column layout is too wide for a 375 pixel wide screen. I think the layout needs some work and the spacer does not seem to be of any significance to the end user.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by ChrisHoefliger** [comment]
Tested successfully

**Comment by wilsonge** [comment]
RTC - But please DO NOT merge maintainers yet until a decision is made on 3 columns layouts in #29706 per @brianteeman 's comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by blueforce** [comment]
I have tested this item :white_check_mark: successfully on e681c19301e0dfc45f8d51fe91f49aa1694a554d<br /><br />test ok, soved
OS: Mac OSX, Chrome 86.0.42.xx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by richard67** [comment]
@alikon I've allowed myself to fix the conflict for you.

**Comment by richard67** [comment]
> RTC - But please DO NOT merge maintainers yet until a decision is made on 3 columns layouts in #29706 per @brianteeman 's comment

The above comment by @wilsonge is still valid, so please hold on with merging. Maybe we need a new "On Hold" label?

**Comment by snehaM26** [comment]
I have tested this item :red_circle: unsuccessfully on 5ac747274e2fd8f1003a1c8744ae783f4c516aed<br /><br />I have tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by ashvini77** [comment]
I have tested this item :red_circle: unsuccessfully on 5ac747274e2fd8f1003a1c8744ae783f4c516aed<br /><br />Still, it's showing the field space<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Comment by gostn** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30911">issues.joomla.org/tracker/joomla-cms/30911</a>.</sub>

**Pull request closed without merging**
