### PR TITLE
[4.0] Remove _QQ_

### PR DESCRIPTION
**Pull request by brianteeman**
Replaces all instances of `_QQ_ `in the language files with `\" `as per @nikosdion comments

~~I am unsure that I need to also change~~
```
		$strings  = @parse_ini_string($contents);
```
~~to set it to use $scanner_mode = INI_SCANNER_RAW~~

~~Please advise~~

### CODE REVIEW

**Comment by nikosdion** [comment]
In order to retain compatibility with Joomla! 3.x language files you should replace it with:
```php
$contents = str_replace('"_QQ_"', '\\"', $contents);
$strings  = @parse_ini_string($contents, INI_SCANNER_RAW);
```
The `str_replace` line can be removed in Joomla! 5.0.

Moreover you will have to update the documentation https://docs.joomla.org/Specification_of_language_files to reflect that double quotes are now escaped with `\"` just like anyone would expect.

Moreover, since you are using INI_SCANNER_RAW, you no longer need the note about not being able to use YES, NO, TRUE, FALSE etc in values (right hand side). The RAW mode removes the parsing of such constants.

**Comment by brianteeman** [comment]
Thanks for that I will update shortly

**Comment by Quy** [comment]
Do a search on `<a href='`. Do you want it to be consistent and change it to `<a href=\"`?

**Comment by infograf768** [comment]
Tests should be done with debug language on.

**Comment by wilsonge** [comment]
Thanks @brianteeman and @nikosdion :)

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
