### PR TITLE
[4.0] Update NPM dependencies

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Update NPM dependencies to latest suitable version with respect to semver.

Mainly it is an update for canisuelite and a few bugfixes or security updates for other packages.

Re-do of PR #30693 .

Thanks @brianteeman for the initial version.

### Testing Instructions

Preparation: Make sure that the command shell window you will use to run npm has a sufficient scroll back history so the output of npm will not be lost.

1. Check the changes of this PR on GitHub. You have to expand the file with the "Load diff" link.
Verify that there are no unexpected changes resulting in an unresolved reference (`"resolved": ""`).
Verify that no package will be removed.
2. Verify that system tests for this PR were passing in Drone.
3. On a clean 4.0-dev branch, apply the changes of this PR or simply replace the `package-lock.json` file in the Joomla root folder by the one from this PR.
4. Run `composer install` if you haven't done that before.
5. Run `npm ci` and watch the output of that command.
6. Verify that no unusual warnings or errors are issued by npm at the first step when it fetches the external packages before starting the `build:js` step.
7. Make a new installation.
8. Login to backend and check if things work as usual.
9. Install some kind of sample data to have some frontend content.
10. Check on frontend if everything works as usual.

### Actual result BEFORE applying this Pull Request

`npm ci` works without unexpected warnings or errors.

### Expected result AFTER applying this Pull Request

Same as actual result.

Backend and frontend work as well as before.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ca69671f46dd0f8c2acba78bc59c5055669da2ad<br /><br />NPM CI had no errors and no packages were removed.

Confirmed on clean install that no issues occurred. 

Installed sample data with no issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30713">issues.joomla.org/tracker/joomla-cms/30713</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ca69671f46dd0f8c2acba78bc59c5055669da2ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30713">issues.joomla.org/tracker/joomla-cms/30713</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30713">issues.joomla.org/tracker/joomla-cms/30713</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
