### PR TITLE
remove wrong code

### PR DESCRIPTION
**Pull request by rdeutz**
redo of #8595 because of travis is failing somewhere totally unrealted to the change

### CODE REVIEW

**Comment by wilsonge** [comment]
Merging as previous patch was RTC already

**Comment by infograf768** [comment]
@wilsonge I guess milestone should be changed to 3.5.0

**Comment by rdeutz** [comment]
I have set the milestone to 3.5.1 because it isn't a fix for a bug and we are in beta state and normally only merge bug fixes. But maybe I missed a meno :-)

**Comment by Bakual** [comment]
Changed milestone as it's merged now and thus will end up in 3.5.0 :)

**Pull request merged**
