### PR TITLE
feat: [RFC] Add support for Markdown changelog

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

_Requesting feedback. Happy to close if it's not desired._

This PR adds support for Markdown changelogs in extensions, which are commonly used nowdays.

image

### Caveat

Unlike the XML based changelog which only displays the changes for the **_most recent version_**, this will display the entire changelog, as I don't think there will be a way to single out a specific version that easily with markdown.

### CODE REVIEW

**Comment by HLeithner** [comment]
I'm not so sure if this make sense, since we pull the html already from the developer website, I don't see a reason why we should render the markdown on our end when the developer can do this while creating the download package.

**Comment by HLeithner** [comment]
hmm true, I misinterpreted the code for xml changelogs, I will bring it up in the next maintainer meeting.

**Comment by Fedik** [comment]
A main drawback with MD you already wrote:

> Unlike the XML based changelog which only displays the changes for the most recent version, this will display the entire changelog,

Current implementation able to load whole XML and parse only the changelog for specific version.
So for "Extension Update" page it shows changelog for update,
And for "Extension Manage" page it shows changelog for currently installed version.

MD will not allow it. Unless we rewrite our Changelog API to work differently from what it is now.

**Comment by brianteeman** [comment]
@fedik thats true but there is an existing feature request for it to show the entire changelog

**Comment by Fedik** [comment]
Yeah right, I just wanted to clarify current state, and point out that it is not that simple as it may sounds :)

**Comment by laoneo** [comment]
> MD will not allow it. Unless we rewrite our Changelog API to work differently from what it is now.

It would be ok to just display the whole md content instead of the the specific version when only an MD file is available.

**Comment by C-Lodder** [comment]
@HLeithner What was the outcome of the maintainers meeting?

**Comment by HLeithner** [comment]
I'm sorry that the outcome of the meeting didn't make it's why to the PR.

We had a lengthy discussion if we want to add another library just for displaying changed logs for especially a feature which can easily implemented in a CI. Which doesn't mean that this is completely impossible in the future.

Also this variant has the drawback (compared to xml changelogs) that it's not possible to show only version relevant parts of the log.   

Never the less the missing feature to show the complete changelog could be achieved by adding a link to the complete changelog.

So I'm closing this for now, any way thanks for your work even if it doesn't make it in to the core.

**Pull request closed without merging**
