### PR TITLE
[4] update modified date field when exists and unpublish/publish

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #8244 .

### Summary of Changes

update modified field when exists and when publish/unpublish from the list

### Testing Instructions
see #8244 .

### Actual result BEFORE applying this Pull Request
the Modified Date is not changed

### Expected result AFTER applying this Pull Request

the Modified Date is changed

### CODE REVIEW

**Comment by coolcat-creations** [comment]
So you only would update the modified state if it exists in the table? I think that does not make sense because modified is modified, no matter if the field is visible or not. Thanks!

**Comment by laoneo** [comment]
Honestly I'm a bit hesitant to modify this field in the base table class where almost every extension inherits from. As this can have some unknown backward compatibility implications, I would rather do this in a model. If really needed in the base class then not before 5.0.

**Comment by laoneo** [comment]
@coolcat-creations the check is done if the table has a field `modified` at all, not if it is visible in the form.

**Comment by coolcat-creations** [comment]
Ok - thanks for clarifying- is the PR ready to test or still to discuss?

**Comment by alikon** [comment]
@laoneo  i've  based the change on this https://github.com/joomla/joomla-cms/issues/8244#issuecomment-414118738

**Comment by HLeithner** [comment]
I have 2 questions here.

1. in the [documentation](https://docs.joomla.org/Table_Advanced_API_Guide#:~:text=modified_user_id%2C-,modified_time,-userid%20of%20user) the field is called modified_time.
2. we never change the modified column in JTable, not for reordering or moving, so should this field be updated on such "trivial" change and should the user doing this change not also be updated.

George mentioned that we do the update in his comment https://github.com/joomla/joomla-cms/issues/8244#issuecomment-414118738 but I can't find it.

So if we update modified_time on publish we should be consistent and update it everywhere and also include the "who" did it. Beside that we don't trigger versioning on publish/unpublish (or did this changed already?)

**Comment by chmst** [comment]
For articles: The modified data (both user and datetime) are changed if the content is edited (means when the save button is used). 
Changing the state in the list view makes no change in modified data. The change is made function store() in respective Tables.



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38783">issues.joomla.org/tracker/joomla-cms/38783</a>.</sub>

**Comment by richard67** [comment]
I agree with Harald: When the „modified time“ is updated and the table has also a „modified by“ column, then that column should be updated, too.

**Comment by alikon** [comment]
make sense i'll do it when i'll found some free time

**Comment by chmst** [comment]
This PR causes a massive  b/c break.

**Comment by coolcat-creations** [comment]
@chmst why so? It fixes a bug that the time is not updated or not?

**Comment by coolcat-creations** [comment]
@chmst  But if you unpublish something inside the article the modified date is also modified. Do you really take care where you unpublish it exactly?

**Comment by richard67** [comment]
The PR changes the meaning of the modified columns. Right now, they show when the item was edited last time and by whom. With the PR it will show when the item was edited or it's status was modified by whom. When you now show the time of last modification in frontend, it might have a completely different and possibly undesired meaning. One may want to see this the other that on his site.

A clean way out would be to have another 2 columns.

With a good naming we would have an "edited" time and user which does what the modified time and user do now, and the "modified" time and user would work like it is done with this PR.

But this would be a b/c break, so we might have to find a different naming so the "modified" time and user continue to work like before.

**Comment by chmst** [comment]
Yes as I wrote - if I open the article for editing, the modified date is changed with function store(). 
I don't want to decide what is correct and will find a workaround for my stuff.
But all the features which use ordering with modified date could change their behaviour.

**Comment by brianteeman** [comment]
@chmst is correct. This will have significant impact on users websites.

**Comment by coolcat-creations** [comment]
Then how to fix the bug without a b/c break?

**Comment by laoneo** [comment]
As I said already, do it in the model much earlier in the call chain. This change like in this pr should be considered for 5.0 at earliest.

**Comment by alikon** [comment]
so can we have a final  agreement this ?
i.e decision

**Comment by alikon** [comment]
please reopen the original issue #8244

**Pull request closed without merging**
