### PR TITLE
Correcting Hathor categories manager

### PR DESCRIPTION
**Pull request by infograf768**
Before patch:
screen shot 2015-11-03 at 08 10 46

After patch

screen shot 2015-11-03 at 08 10 21

### CODE REVIEW

**Comment by dgt41** [comment]
@test ok
Another problem still remains:
screenshot 2015-11-03 09 14 34

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 42a570cd05b9eed517a3cdec989a5d3ad75496b9<br /><br />Works for me to. @dgt41 did you try the submit button next to the dropdowns? For me its working ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8254">issues.joomla.org/joomla-cms/8254</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8254">issues.joomla.org/joomla-cms/8254</a>.</sub>

**Comment by infograf768** [comment]
@dgt41 
I solved here the drodown wrong display by adding to hathor css (in LTR):
```
fieldset#filter-bar ul li.active-result {
	float: none;
	margin-left: 5px;
}
```

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768! Merged.

**Pull request merged**
