### PR TITLE
CS / Review for the editor plugins

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This is a review of the exitor plugins
### Testing Instructions

Apply this patch and try the following editor plugins:
- article
- image
- module
- pagebreak
- readmore
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by wilsonge** [comment]
RTC on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12260">issues.joomla.org/joomla-cms/12260</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on aad650515366ff822e087044d621d6a6c8a867ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12260">issues.joomla.org/tracker/joomla-cms/12260</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by infograf768** [comment]
This may anyway be obsolete after staging is merged.
Suggest to wait and redo.

**Comment by zero-24** [comment]
@infograf768 

> This may anyway be obsolete after staging is merged.

Why this should be obsolet? It is not obsolet it will conflict ;)

**Comment by infograf768** [comment]
conflict is the right word 👍

**Pull request merged**
