### PR TITLE
Content load modules description

### PR DESCRIPTION
**Pull request by RonakParmar**
Pull Request for Issue #11066  .
#### Summary of Changes

Added syntax to load duplicate module in article in Content-Load Module plugin.
#### Testing Instructions

Check the description of Content - Load Module plugin at back-end.

### CODE REVIEW

**Comment by brianteeman** [comment]
You have an extra file in this PR 
administrator/components/com_banners/views/download/tmpl/default.php

**Comment by RonakParmar** [comment]
When I have committed from my local it shows 2 files.
https://github.com/joomla/joomla-cms/pull/11067/commits/3b9d07904891e0b9ef68be6a07728c7f763fbb4b

**Comment by RonakParmar** [comment]
The the additional file is related with below pull request.

https://github.com/joomla/joomla-cms/pull/11067/commits/2072bbf99490b7d95e35f6fcb5a613b510d6b4c5

**Comment by infograf768** [comment]
It should not be in this PR.

**Comment by brianteeman** [comment]
It should not be in this Pull request - you need to make sure that you have a separate branch for each PR

**Comment by RonakParmar** [comment]
I have created new branch for this PR.

**Comment by brianteeman** [comment]
Also I am not sure that this PR is correct anyway. Your new text suggests that you only need to use the title for a duplicate module. Not sure what you mean by that. And when you use the insert module plugin it always uses that syntax so your change will create confusion instead of clarity.

**Comment by RonakParmar** [comment]
Thanks. I am cleaning it and closing it. I will send new PR with only specific changes.

**Comment by RonakParmar** [comment]
I have sent clean version of this PR in #11068

**Pull request closed without merging**
