### PR TITLE
[4.2] PHP8.0 fix for BaseDatabaseModel: Only variable references

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request to fix on PHP 8.0 an issue with "Notice: Only variable references should be returned by reference in /srv/www/joomla/joomla-cms/libraries/src/MVC/Model/BaseDatabaseModel.php on line 418"

### Testing Instructions
Environment:
- **PHP Version: 8.0.17**
- Web Server: Apache/2.4.53 (Unix) OpenSSL/1.1.1n
- Joomla! Version: Joomla! 4.2.0-alpha2-dev Development [ Kuamini ] 29-March-2022 18:41 GMT

In a fresh installed Joomla 4 with the sample data for testing, under "Menus" open a menu item like "All Modules".
Or directly go to: administrator/index.php?option=com_menus&view=items&menutype=all-modules
(most of the other menu items have this issue)
and see the notice appear
> Notice: Only variable references should be returned by reference in /srv/www/joomla/joomla-cms/libraries/src/MVC/Model/BaseDatabaseModel.php on line 418

### Actual result BEFORE applying this Pull Request

> Notice: Only variable references should be returned by reference in /srv/www/joomla/joomla-cms/libraries/src/MVC/Model/BaseDatabaseModel.php on line 418

before-pr

### Expected result AFTER applying this Pull Request

after-pr

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks. I guess this needs a bit more rethinking, because of undeclared variable references.

**Comment by pe7er** [comment]
Thanks, I was already afraid that removing the ampersand before the function name would be too easy and probably not be the definitive solution :-)

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on c5d5b8e2a020017a4371f7ca33d3d447b3bbc8b4<br /><br />Tested successfully in Joomla 4.2.0-alpha3-dev of 27 April in Wampserver 3.2.8 using PHP 8.0.15.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37661">issues.joomla.org/tracker/joomla-cms/37661</a>.</sub>

**Comment by joeforjoomla** [comment]
I have tested this item :white_check_mark: successfully on c5d5b8e2a020017a4371f7ca33d3d447b3bbc8b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37661">issues.joomla.org/tracker/joomla-cms/37661</a>.</sub>

**Comment by laoneo** [comment]
> Thanks, I was already afraid that removing the ampersand before the function name would be too easy and probably not be the definitive solution :-)

I guess removing the ampersand is fine, but we need to adapt the unit test

**Comment by laoneo** [comment]
Can you replace the unit test function with this more real world scenario:
```
	public function testNotDeclaredVariable()
	{
		$model = new class(['dbo' => $this->createStub(DatabaseInterface::class)], $this->createStub(MVCFactoryInterface::class)) extends BaseDatabaseModel
		{
			public function cache($key, $value)
			{
				if (!isset($this->test[$key]))
				{
					$this->test[$key] = $value;
				}

				return $this->test[$key];
			}
		};

		$this->assertEquals('test', $model->cache(1, 'test'));
	}
```

**Comment by pe7er** [comment]
I've added your unit test to my PR. Thanks @laoneo !

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
