### PR TITLE
[com_fields] Copy paste comment error

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to fix a copy paste error in the comment block

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 56c2c7264fac2480b384e68434fd984b91ca20fc<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15565">issues.joomla.org/tracker/joomla-cms/15565</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 56c2c7264fac2480b384e68434fd984b91ca20fc<br /><br />based on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15565">issues.joomla.org/tracker/joomla-cms/15565</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
