### PR TITLE
[3.7.x] Fix typo in the isis css file

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue raised here: https://github.com/joomla/joomla-cms/pull/12319#issuecomment-252299378
### Summary of Changes

Fiy typo on fixing conflicts
### Testing Instructions

review
### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
hmm i did get a different diff please double check that @C-Lodder @ciar4n

**Comment by C-Lodder** [comment]
This need to be done in the LESS file.

@zero-24 - It was a 1px difference for the blue background.

**Comment by ciar4n** [comment]
@C-Lodder The LESS file appears to be correct (-26px). When compiled it changes the CSS from -25px to -26px. Although we should also be seeing a similar change in the template-rtl.css

@zero-24 Have the changes here been the result of the LESS been compiled or have you edited the CSS directly?

**Comment by zero-24** [comment]
Should be correct now? All three places have now -26px

**Comment by ciar4n** [comment]
Here is the CSS compiled from the LESS files.. https://github.com/ciar4n/joomla-cms/commit/350807b4232210539cbb24d3f6e1aceddf41b326

**Comment by zero-24** [comment]
done thanks @ciar4n and @C-Lodder

**Pull request closed without merging**
