### PR TITLE
[4] Dont show stats exceptions/failures/warnings to users

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Closes https://github.com/joomla/joomla-cms/issues/32005 https://github.com/joomla/joomla-cms/issues/33083 https://github.com/joomla/joomla-cms/issues/32129 et al.

### Summary of Changes

Sometimes "something" stops a successful submission of anonymised stats to the Joomla stats collection endpoint.

Most of the time there is nothing anyone needs to do.

Joomla Stats collection is a vanity "nice to have" and the Joomla project should not be complaining if users fail to submit their stats

The stats process should die gracefully and quietly - unless in debug mode. 

Notices, and Exceptions should not be thrown into the users face if the Joomla Stats collection server endpoint is down, unreliable, unavailable, uncountable. 

### Testing Instructions

Install Joomla 4

Change the url in the file to be a fake non-routable url 

```php
protected $serverUrl = 'https://dev.null/stats/submit';
```

To reset your stats plugin to "out of the box" run sql after s/jos/prefix:

```sql
UPDATE `jos_extensions` SET `params` = '' WHERE `name` = 'plg_system_stats';
```

Test with "always" 

### Actual result BEFORE applying this Pull Request

Red exception shown to the screen on failed submission of stats

### Expected result AFTER applying this Pull Request

No red exception messages 
If debug is on - red exception message
if logging is enabled - entries in the log like:

```

2021-04-15T20:05:35+00:00	WARNING 172.20.0.1	jerror	Could not connect to statistics server: Failed to connect to 127.0.0.1 port 80: Connection refused
2021-04-15T20:05:48+00:00	WARNING 172.20.0.1	jerror	Could not connect to statistics server: Failed to connect to 127.0.0.1 port 80: Connection refused
2021-04-15T20:06:01+00:00	WARNING 172.20.0.1	jerror	Could not connect to statistics server: Failed to connect to 127.0.0.1 port 80: Connection refused
```

### Documentation Changes Required

none

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Conflicts resolved (eventually)

**Comment by ceford** [comment]
With the patch applied, if debug is on there is no red exception message but logging continues. That is not what it says in the instructions and I think it would be best to have the message, even tailored to give a bit more explanation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33149">issues.joomla.org/tracker/joomla-cms/33149</a>.</sub>

**Comment by PhilETaylor** [comment]
> I think it would be best to have the message, even tailored to give a bit more explanation.

No. Simply no. as #32005 #33083 #32129 et al shows, users dont need and dont care about this feature. 

This is simply a vanity tool of the Joomla project (the stats are meaningless anyway as they only show the first version installed, and not the "current" version at all times, so the stats are always incorrect when aggregated and displayed on joomla.org)

A Joomla user should not have to deal with errors from the vanity tool of the Joomla project - especially as its totally out of the Joomla users hands should the stats server error, or be unavailable. There is no action needed by the Joomla user at all, so why shout at them an error message.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d7da0f7e039f9d6ada25c18f1bfce8006866eff5<br /><br />I am happy with what this pr does. I was thinking a log may be full of useless lines like this:
2021-05-08T12:41:06+00:00	ERROR 127.0.0.1	-	Could not connect to statistics server: Could not resolve host: dev.null
But that is a separate issue. If users are logging they need to set up the logger properly. I never really learned how to do that myself.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33149">issues.joomla.org/tracker/joomla-cms/33149</a>.</sub>

**Comment by alikon** [comment]
the stats need more care fore sure
https://github.com/joomla/statistics-server/issues/60

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d7da0f7e039f9d6ada25c18f1bfce8006866eff5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33149">issues.joomla.org/tracker/joomla-cms/33149</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by wilsonge** [comment]
> This is simply a vanity tool of the Joomla project (the stats are meaningless anyway as they only show the first version installed, and not the "current" version at all times, so the stats are always incorrect when aggregated and displayed on joomla.org)

It does give the updated data to the project. And as production we used these extensively when trying to figure out minimum requirements for J4 (we filtered out any data not submitted in the last 3 months unlike the data that shows in the graph on j.org)

Although to be clear it’s correct to not show most the warnings to end users (we should probably log them however)

**Comment by brianteeman** [comment]
it's still fundamentally flawed as no site that said no 5 years ago has ever submitted data again. Perhaps it should be considered to ask everyone again at each update

**Pull request merged**
