### PR TITLE
media edit plugins legend

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Dtops the legend being indented - see screenshots

### Testing Instructions
This is a css change so either` run npm build:css` or use a pre-built package

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c57db0924eb2991366718651e9861a04c3e5d2be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38362">issues.joomla.org/tracker/joomla-cms/38362</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c57db0924eb2991366718651e9861a04c3e5d2be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38362">issues.joomla.org/tracker/joomla-cms/38362</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38362">issues.joomla.org/tracker/joomla-cms/38362</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
