### PR TITLE
[4.3] Replace JPATH_PLATFORM with _JEXEC in dispatcher.php

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue # .

### Summary of Changes

The constant JPATH_PLATFORM is a history thing and should not be used for new code in `Dispatcher.php`
This pr replaces this with _JEXEC in some files

### Testing Instructions

Code review

### Actual result BEFORE applying this Pull Request
Code: `\defined('JPATH_PLATFORM') or die;`

### Expected result AFTER applying this Pull Request
Code: `\defined('_JEXEC') or die;`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@joomdonation

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on fe6ebbe577728d9c7722e311e4998c1df8dfbef6<br /><br />Looks good to me. Hope no one disagrees with this change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39997">issues.joomla.org/tracker/joomla-cms/39997</a>.</sub>

**Comment by sandewt** [comment]
> Looks good to me. Hope no one disagrees with this change.

We will see and wait.

**Review by wilsonge — APPROVED** [review]

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on fe6ebbe577728d9c7722e311e4998c1df8dfbef6<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39997">issues.joomla.org/tracker/joomla-cms/39997</a>.</sub>

**Comment by joomdonation** [comment]
RTC.Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39997">issues.joomla.org/tracker/joomla-cms/39997</a>.</sub>

**Pull request merged**
