### PR TITLE
issue #8891 fixed typo s/$cachable/$cacheable

### PR DESCRIPTION
**Pull request by N6REJ**
replaced all $cachable with $cacheable

### CODE REVIEW

**Comment by wojsmol** [comment]
@N6REJ delete nbproject and revert .gitignore chenge

**Comment by andrepereiradasilva** [comment]
Please make a PR for com_weblinks repository too.
https://github.com/joomla-extensions/weblinks/blob/master/src/components/com_weblinks/controller.php

**Comment by N6REJ** [comment]
do you need me to redo it as just the com_weblinks stuff?

**Comment by N6REJ** [comment]
@wojsmol what .gitignore change?

**Comment by N6REJ** [comment]
ok, its fixed... gosh idky I always have so much trouble.

**Comment by N6REJ** [comment]
@andrepereiradasilva ok, done.

**Comment by andrepereiradasilva** [comment]
Cool. Thanks

**Comment by infograf768** [comment]
Please maintainers, relaunch Travis.

**Comment by wojsmol** [comment]
@infograf768 Travis returns an error on PHP 5.6 due to problems with the CS.

**Comment by rdeutz** [comment]
it is doc blocks problem variables don't align

**Comment by rdeutz** [comment]
ups sorry it is the comment after the variable

**Comment by wojsmol** [comment]
@N6REJ see https://github.com/N6REJ/joomla-cms/pull/1

**Comment by N6REJ** [comment]
Merged and ty.
Bear

**Comment by rdeutz** [comment]
there MUST be 2 spaces after the longest variable name

**Comment by N6REJ** [comment]
@rdeutz  please explain more

**Comment by wojsmol** [comment]
@N6REJ See https://github.com/N6REJ/joomla-cms/pull/2 by @izharaazmi

**Comment by N6REJ** [comment]
done & ty.
Bear

**Comment by N6REJ** [comment]
@wojsmol thanks for helping finish this pr.

**Comment by N6REJ** [comment]
omg this is constantly screwed up.

**Comment by wojsmol** [comment]
@N6REJ If you want I can prepare new version of this PR

**Comment by wojsmol** [comment]
New PR is #9070 by @N6REJ

**Comment by N6REJ** [comment]
I appreciate that offer, I THINK i got it right.
Bear

**Pull request closed without merging**
