### PR TITLE
Hathor: reduce mootools dependency

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Reduce mootools

Introduce formvalidator
Use native selector instead of document.id
Inline scripts added through API addScriptDeclaration

Use template.js from  @AshanFernando PR #2003 which is not mootools dependent

### CODE REVIEW

**Comment by dgt41** [comment]
Update: I used the code from #2003 for template.js, since @AshanFernando has done an excellent job there and converted to jquery! 
Also I converted all `JHtml('behavior.formvalidation');` to `JHtml('behavior.formvalidator');`
And removed the inline scripts and add them through the API (addScriptDeclaration())

**Comment by hanshenrikchr** [comment]
I ran through all the menu areas, users, components, ect. and everything worked fine after i applied the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5245">issues.joomla.org/joomla-cms/5245</a>.</sub>

**Comment by superfoght** [comment]
Tested this by setting the Hathor template to default.

Went through all the diferrent views in the administration area, tried clicking the save, save & close, close etc buttons to see if they are still working.

Also checked the console in the browser to make sure there were no JS conflicts<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5245">issues.joomla.org/joomla-cms/5245</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing :smile: #jab15 #makeithappen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5245">issues.joomla.org/joomla-cms/5245</a>.</sub>

**Comment by dgt41** [comment]
@wilsonge can you merge this?

**Comment by wilsonge** [comment]
Merged - thanks!

**Comment by AshanFernando** [comment]
thanks!

**Pull request closed without merging**
