### PR TITLE
[com_users] improving text

### PR DESCRIPTION
**Pull request by wojsmol**
Redo of pull request #9806 by @helvecio

Original PR description

> After a small survey among developers. it was noted that "Receive System Emails" was misunderstood by administrators. The result of the survey showed that site admins think this setting refers to receiving Private Messages from the Messagin Component.
> To clear up the confusion, it has been suggested to change the word "emails" to "notifications"

@helvecio Please test this PR..

### CODE REVIEW

**Comment by brianteeman** [comment]
As it is an email and not a notification in the control panel I am happy with the current message. 

@helvecio were the developers you spoke to native english speakers?

**Comment by conconnl** [comment]
To make everybody happy I would suggest to use "Receive System Notications by email" and as sub-note "If set to yes, the user will receive system notifications by email."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9809">issues.joomla.org/joomla-cms/9809</a>.</sub>

**Comment by Luchen6** [comment]
I have not tested this item.<br /><br />In the plugin Joomla-user the text ' Notification Mail to User' is used for the same action.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9809">issues.joomla.org/joomla-cms/9809</a>.</sub>

**Comment by brianteeman** [comment]
As @helvecio has not bothered to respond to the basic questions it is obviously not that important to him so I am closing this. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9809">issues.joomla.org/joomla-cms/9809</a>.</sub>

**Comment by helvecio** [comment]
Sorry, I'm kinda new to GitHub and my reply got lost somewhere. No, the developers with whom I have spoken to are not native english speakers.

**Pull request closed without merging**
