### PR TITLE
[4.0] IFW client js

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #29366 by @mbabker  .
> All other changes are contained in the IFW server component.

### CODE REVIEW

**Comment by ceford** [comment]
I can confirm the problem but can't test with Patchtester, I get this: 'There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.'
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29938">issues.joomla.org/tracker/joomla-cms/29938</a>.</sub>

**Comment by zero-24** [comment]
@ceford you have to use the pre build packages or run npm as js files have been changed

**Comment by ceford** [comment]
Another thought has occurred to me: the drop down list offers a choice between Current Joomla Version and All Joomla Versions; what happens when Joomla 4 is released? I should imagine that Joomla 3.10 and Joomla 4 will overlap as current versions for two years. So 'Current' becomes ambiguous. Thanks for the tip zero-24 - one day I might master testing without the Patchtester.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29938">issues.joomla.org/tracker/joomla-cms/29938</a>.</sub>

**Comment by zero-24** [comment]
I have not checked the details but I would expect current to be the version you have installed so current is working even with two parallel versions.

**Comment by mbabker** [comment]
Current is the version of Joomla you are actually using, not current as in the newest release of the software (i.e. "my site is currently using Joomla 3.9.whatever").

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8b04509d88d23f3e367c05909409fe0791ebb2d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29938">issues.joomla.org/tracker/joomla-cms/29938</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8b04509d88d23f3e367c05909409fe0791ebb2d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29938">issues.joomla.org/tracker/joomla-cms/29938</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29938">issues.joomla.org/tracker/joomla-cms/29938</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
