### PR TITLE
[4.0] Atum logo and login image alt [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
This PR applies the ALT text changes from #31318

In addition the related fields are now correctly grouped in a fieldset

**Any comments about the layout will be ignored as that's an unrelated issue which we have a release blocker for**

### Testing
Testing is really easy. No npm, js or css involved.
Merge the pull request and then go to edit the atum template style and go to the image settings tab

You now have a new field and tweaked text

Please test three scenarios when adding a large log, a small logo and a login image

1. Image Description (Alt Text) = Empty
No Description = unchecked

2. Image Description (Alt Text) = "some description"
No Description = unchecked

3. Image Description (Alt Text) = Empty
No Description = checked

The expected behaviour for each of these tests is 

1. ``
2. `some description`
3. ``
or ``

PLEASE do not comment on what you think the code does but apply the PR and test it. Getting very tired of people blocking PR with their comments without actually testing the code.

cc @carcam

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on b7f157cf2e72060a07c8900da9946e4e4f84cb0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31349">issues.joomla.org/tracker/joomla-cms/31349</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b7f157cf2e72060a07c8900da9946e4e4f84cb0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31349">issues.joomla.org/tracker/joomla-cms/31349</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31349">issues.joomla.org/tracker/joomla-cms/31349</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
