### PR TITLE
Rename cypress.config.js so that it can be included in the .gitignore file.

### PR DESCRIPTION
**Pull request by astridx**
I would appreciate it if the `cypress.config.js` could be customised. Since a database password might be inserted, it would be great if this file is not always included in the changed files in git, in case someone wants to create a PR.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@astridx usually there's a `dist` file like https://github.com/joomla/joomla-cms/blob/4.3-dev/tests/Codeception/acceptance.suite.dist.yml but also this could work with couple of changes in the drone.yml

**Comment by astridx** [comment]
> @astridx usually there's a `dist` file like https://github.com/joomla/joomla-cms/blob/4.3-dev/tests/Codeception/acceptance.suite.dist.yml but also this could work with couple of changes in the drone.yml

Yes, that's exactly why I renamed the cypress config here to a file that contains the text `dist`. Or am I understanding you wrong?

**Comment by laoneo** [comment]
Can you fix the conflicts here?

**Comment by astridx** [comment]
> Can you fix the conflicts here?

Fixed

**Comment by laoneo** [comment]
Thanks!

**Comment by HLeithner** [comment]
btw. you can use environment variables to override the config options

**Pull request merged**
