### PR TITLE
few files to remove

### PR DESCRIPTION
**Pull request by jsubri**
Pull Request for new

### Summary of Changes
languages.php was deleted in com_installer.
Files in "medialist" went renamed (with plurals), filename with (singular) need to be delete for updated site.

### Testing Instructions
a) code review
b) upgrade from 3.6.5 with current staging, apply patch, run the Database Fix button. These 9 files shall not be present anymore.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 782446bf967fed907a367b08a8bb8886621c8629<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13519">issues.joomla.org/tracker/joomla-cms/13519</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :red_circle: unsuccessfully on 782446bf967fed907a367b08a8bb8886621c8629<br /><br />these files are still present in Joomla 3.7.0 I do not think should be removed:
/administrator/components/com_media/views/medialist/tmpl/details_doc.php
/administrator/components/com_media/views/medialist/tmpl/details_folder.php
/administrator/components/com_media/views/medialist/tmpl/details_img.php
/administrator/components/com_media/views/medialist/tmpl/details_video.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13519">issues.joomla.org/tracker/joomla-cms/13519</a>.</sub>

**Comment by brianteeman** [comment]
> Files in "medialist" went renamed (with plurals), filename with (singular) need to be delete for updated site.

They were removed in #8852 but appear to have come back (in error) @rdeutz can you check

**Comment by jsubri** [comment]
Closing in favor of the referenced PR from @AlexRed , @rdeutz the comments from @brianteeman are still valid.

**Pull request closed without merging**
