### PR TITLE
[com_finder] maps view: translate branches (solves #10260 - part 2)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Solves https://github.com/joomla/joomla-cms/issues/10260 (branches part)

> Load another language than English in back-end.
> Go to Smartsearch Content Maps equivalent page
> The equivalent filter "- Select Branch -" displays the filter types in English

After PR (example in portuguese):

image
#### Testing Instructions
1. Apply patch
2. Change admin language to other language than en-GB
3. Check the "Branch" filter in Components -> Smart Search -> Content Maps

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1d1452d215dd619330e12229b8fec81d55b94104<br /><br />Great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10264">issues.joomla.org/joomla-cms/10264</a>.</sub>

**Comment by BurtNL** [comment]
I tested this issue, but not all strings are translated. Is this due to the Dutch language pack? Although this seems to be commons strings.

screen shot 2016-05-06 at 11 26 09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10264">issues.joomla.org/joomla-cms/10264</a>.</sub>

**Comment by andrepereiradasilva** [comment]
it seems something is not translated in the Dutch language pack you're using.
Try with other languages please.

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 1d1452d215dd619330e12229b8fec81d55b94104<br /><br />Tested successfully with the German language pack.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10264">issues.joomla.org/joomla-cms/10264</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 @BurtNL thanks for testing!

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10264">issues.joomla.org/joomla-cms/10264</a>.</sub>

**Comment by infograf768** [comment]
@BurtNL 
Just checked nl-NL and I see that a file is missing in that pack. Will let it know to the TT
/administrator/language/nl-NL/nl-NL.plg_content_finder.ini

**Comment by andrepereiradasilva** [comment]
thanks all for testing and comments!

**Pull request merged**
