### PR TITLE
clean also the backend cache after update

### PR DESCRIPTION
**Pull request by rdeutz**
as requested in #11098 this add the cache cleaning for the backend cache see #11098 for the error situation and for testing instructions. This might can be merged on review.

### CODE REVIEW

**Comment by brianteeman** [comment]
Awesome - thanks @rdeutz

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 37a22a8dc170ebd2a716ea3c700a4424b888b6b7<br /><br />I enabled cache and made sure it was working for the admin (make sure it shows more than _system and com_plugins
I applied the patch and then reinstalled Joomla using the new ability to upload a package in com_joomlaupdate

I checked the cache and it had been cleaned (note it will never show empty because as soon as you open com-cache it will show _system and com_plugins)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11333">issues.joomla.org/joomla-cms/11333</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 37a22a8dc170ebd2a716ea3c700a4424b888b6b7<br /><br />Following Brian's StepByStep works as described. -Thanks a lot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11333">issues.joomla.org/joomla-cms/11333</a>.</sub>

**Comment by rdeutz** [comment]
RTC then<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11333">issues.joomla.org/joomla-cms/11333</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @rdeutz

**Pull request merged**
