### PR TITLE
I deleted a line that I don't think we need

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/27772

Should I close the issue https://github.com/joomla/joomla-cms/pull/27772 ? I am not sure whether changes in J4 will be adopted because the directory is now moved.

### CODE REVIEW

**Comment by wilsonge** [comment]
The changes will get ported from here anyhow :) it’s just a bit of extra work on my end

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 82c10b4c63fb9b2c123a10b65b4d4d3c1f110b3f<br /><br />Tested in 3.9.15 and PHP 7.4.2 on localhost<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27775">issues.joomla.org/tracker/joomla-cms/27775</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 82c10b4c63fb9b2c123a10b65b4d4d3c1f110b3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27775">issues.joomla.org/tracker/joomla-cms/27775</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27775">issues.joomla.org/tracker/joomla-cms/27775</a>.</sub>

**Comment by astridx** [comment]
I honestly don't know what the import `jimport('joomla.html.html.bootstrap');` is for. 

Since the file `/libraries/src/HTML/HTML/Bootstrap` does not exist, I dare to delete this line, as asked [here](https://github.com/joomla/joomla-cms/pull/27772/files#r374783967).

**Comment by brianteeman** [comment]
that line originates from #29072 - you can find out why it existed there

**Comment by astridx** [comment]
Thank you @brianteeman But, what is `#29072`? Currently our highest number is `#27805`.

**Comment by brianteeman** [comment]
Sorry thats an old joomlacode reference number 
https://developer.joomla.org/joomlacode-archive/issue-29072.html

**Pull request merged**
