### PR TITLE
Improvement: adding forced language to categories modal title

### PR DESCRIPTION
**Pull request by infograf768**
Separated from https://github.com/joomla/joomla-cms/pull/11717 to get the modal title change in 3.6.3

Already tested OK on mulingual site.

screen shot 2016-08-22 at 15 34 42

### CODE REVIEW

**Comment by rdeutz** [comment]
bot not running on this?

**Comment by zero-24** [comment]
@rdeutz i guess it is mod_security again :(

**Comment by zero-24** [comment]
So you / the maintainers need to do it manually

**Comment by brianteeman** [comment]
I manually added the PR-Staging tag on github and that triggered the lazy bot to do everything else

**Comment by rdeutz** [comment]
This was already RTC so merging it on review

**Comment by brianteeman** [comment]
@zero-24 I cant close it ;(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11751">issues.joomla.org/joomla-cms/11751</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman i'm not sure what the problem is? This is merged so there is no need to close ;)

**Comment by brianteeman** [comment]
@zero-24  on issue tracker it is still open

**Comment by zero-24** [comment]
Ok lets wait for the cron to run else we need to ping michael to hava a look into the database.

**Pull request merged**
