### PR TITLE
[4.0] Removing obsolete code from com_messages table

### PR DESCRIPTION
**Pull request by Hackwar**
With the column-alias-feature, the whole publish method is unnecessary in this table.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b5c20090129241e2cf23613e9ad5dc798bfff25d<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on b5c20090129241e2cf23613e9ad5dc798bfff25d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by SharkyKZ** [comment]
Remove unused imports?

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on b5c20090129241e2cf23613e9ad5dc798bfff25d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by Quy** [comment]
Remove use statements.

**Comment by Hackwar** [comment]
> 
> 
> Remove use statements.

done

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 746ff649f5a3e94c31a9cd7b2598a1f0400206c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 746ff649f5a3e94c31a9cd7b2598a1f0400206c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29393">issues.joomla.org/tracker/joomla-cms/29393</a>.</sub>

**Comment by richard67** [comment]
Thanks all!

**Pull request merged**
