### PR TITLE
[4.0] Change com_joomlaupdate to services

### PR DESCRIPTION
**Pull request by laoneo**
Moves com_joomlaupdate to the service based extension setup.

Ping @marcodings and @wilsonge for GsoC.

See #20217 for details.

### CODE REVIEW

**Comment by zero-24** [comment]
What does happen in case the updater reloads when the file is not deleted and both files are there?

**Comment by mbabker** [comment]
> What does happen in case the updater reloads when the file is not deleted and both files are there?

Not an issue.  These are new to 4.0.

**Review by zero-24 — APPROVED** [review]
Fine for me than when the overall decision is done.

**Comment by alikon** [comment]
ping @bosunski for the CLI gsoc project

**Pull request merged**
