### PR TITLE
[3.10] Dont show the pre upgrade checker when the upgrade is not supported

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Dont show the pre upgrade checker when the upgrade is not supported

### Testing Instructions

- install 3.10 on a non supported setup for J4 that is checked by the updater lib (ex. mysql version older than 5.6)
- switch the update server to Joomla Next
- you see a pre upgrade checker
- apply this patch
- The pre upgrade checker is gone

#### Tip

when you dont have a setup with such an old mysql version you can fake it by adding `$dbMatch = false;` after this line here: https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Updater/Update.php#L403

### Actual result BEFORE applying this Pull Request

You see a pre upgrade checker with false information as the update is not fully aviable nor working at all.
image

### Expected result AFTER applying this Pull Request

The pre upgrade checker is gone
image

### Documentation Changes Required

none

cc @tecpromotion

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 49633ff7e370fcc3167bf70ca51e731ef1edf144<br /><br />Thanks @zero-24 for this improvement<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36312">issues.joomla.org/tracker/joomla-cms/36312</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 49633ff7e370fcc3167bf70ca51e731ef1edf144<br /><br />This is obviously incorrect. None of the three explanations are anything to do with the title "We can't find a download url"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36312">issues.joomla.org/tracker/joomla-cms/36312</a>.</sub>

**Comment by zero-24** [comment]
Yes I have not changed the language string but I'm happy to do so. What would be a better fit as title?

**Comment by brianteeman** [comment]
Update unavailable

?

**Comment by zero-24** [comment]
Done thanks :)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ed91121cc802f12ec7f27f0f9d5385ee7f7bd065<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36312">issues.joomla.org/tracker/joomla-cms/36312</a>.</sub>

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36312">issues.joomla.org/tracker/joomla-cms/36312</a>.</sub>

**Comment by brianteeman** [comment]
Thats better but I wonder why you are not displaying the results of the required settings tests. That way someone will know that the reason an update is not available is specifically due to their server not meeting the minimum requirements and specifically which ones. Better to help them with the upgrade instead of keeping it a secret<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36312">issues.joomla.org/tracker/joomla-cms/36312</a>.</sub>

**Comment by zero-24** [comment]
In this specific case its not something thats checked at the pre upgrade checker level but in the updater class and can have different reasons other than a wrong not supported server setup. :(

For now the aim here is to hide the clearly wrong information shown for such sites.

**Comment by brianteeman** [comment]
In which case I don't see this as an improvement but a quick fix that doesnt address the issue of informing the user why they cannot upgrade

**Comment by wilsonge** [comment]
I agree with @brianteeman however fixing that is going to be something super deep and super low level (because of the internals of how the update class works). and in the mean time users are getting confused because they see the wrong PHP/DB info in the pre-update checker. We need to aim to put it back. But until we have the right info showing I think we should probably hide it unfortunately :(

**Comment by zero-24** [comment]
The followup issue has been created here will take a look into it hopefully for the next release: https://github.com/joomla/joomla-cms/issues/36610

**Comment by brianteeman** [comment]
image

kept for future use ;)

**Pull request merged**
