### PR TITLE
[5.0] schemaorg fix schema forms

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- fix option value
- add missing language keys

### Testing Instructions

- enable debug mode and check form labels
- test fields `abridged` and `bookFormat` of book type (syntax error in form xml)

### Actual result BEFORE applying this Pull Request

image

values for `abridged` and `bookFormat` are missing in schemaorg output

### Expected result AFTER applying this Pull Request

image

values for `abridged` and `bookFormat` are available in schemaorg output

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on 02679d8b7fedaed65b92a517b540e92af49d9319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41323">issues.joomla.org/tracker/joomla-cms/41323</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 02679d8b7fedaed65b92a517b540e92af49d9319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41323">issues.joomla.org/tracker/joomla-cms/41323</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41323">issues.joomla.org/tracker/joomla-cms/41323</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
