### PR TITLE
[3.10] s/timymce/tinymce

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/timymce/tinymce

Joomla 3.10 based version of https://github.com/joomla/joomla-cms/pull/32047

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 674e74fe702c406088b043adf008e011a5f9efe5<br /><br />J 3.10-alpha5-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32056">issues.joomla.org/tracker/joomla-cms/32056</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 674e74fe702c406088b043adf008e011a5f9efe5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32056">issues.joomla.org/tracker/joomla-cms/32056</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32056">issues.joomla.org/tracker/joomla-cms/32056</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :)

**Comment by Quy** [comment]
@zero-24 Close #32047?

**Comment by zero-24** [comment]
Done thanks.

**Pull request merged**
