### PR TITLE
[5.1] Use Dialog for ContentHistory field

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Use Dialog for ContentHistory field

### Testing Instructions
Do frontend Content editing.
Click Versions button to open Content history.
Try to use diferent Content history features in this popup.

### Actual result BEFORE applying this Pull Request
Works with BS Modal

### Expected result AFTER applying this Pull Request
Works with Joomla Dialog

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

References:

- https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Comment by Quy** [comment]
Before PR:
42454-before


After PR, alert needs padding:
42454-after

**Comment by Fedik** [comment]
@Quy please try again

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 05184eaebfa98cc6f2090ed46b0e8b9498c62f09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42454">issues.joomla.org/tracker/joomla-cms/42454</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42454">issues.joomla.org/tracker/joomla-cms/42454</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik 🚀
Many thanks also for testing @Quy @fgsw

**Pull request merged**
