### PR TITLE
[4.1] Module "Articles - Categories" - Make the category selection optional

### PR DESCRIPTION
**Pull request by Bakual**
The module "Articles - Categories" requires to select a parent category. But that means you can't have the module show *all* categories, you can only show a subset.

I think this is a requirement which is not needed. The code itself already falls back to "root" if no category is selected.

### Summary of Changes
Removing the "required" flag from the parent category field.

### Testing Instructions
Test the module "Articles - Categories" and make especially sure nothing breaks when no category is selected.

### Actual result BEFORE applying this Pull Request
You always need to select a category and the module shows only subset of the article categories.

### Expected result AFTER applying this Pull Request
You don't need to select a category and the module can show all categories.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b8c2a08274c91e58ea6989c11ed623ea15ee33d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37116">issues.joomla.org/tracker/joomla-cms/37116</a>.</sub>

**Comment by brianteeman** [comment]
I think the history on this code needs to be checked carefully. I'm sure there must be a reason. It is possibly related to multilingual

**Comment by Bakual** [comment]
Good point. It looks like it got added just to use the modal_category formfield for J3.7. Before that, the field was not required.
See https://github.com/joomla/joomla-cms/commit/45e14dd1d4a970a718539a7512c7e60135697882

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b8c2a08274c91e58ea6989c11ed623ea15ee33d1<br /><br />Tested successfully in Joomla 4.1.1-dev of 23 February in Wampserver 3.2.7 using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37116">issues.joomla.org/tracker/joomla-cms/37116</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37116">issues.joomla.org/tracker/joomla-cms/37116</a>.</sub>

**Comment by laoneo** [comment]
> Good point. It looks like it got added just to use the modal_category formfield for J3.7. Before that, the field was not required. See [45e14dd](https://github.com/joomla/joomla-cms/commit/45e14dd1d4a970a718539a7512c7e60135697882)

Does the category form field still work as expected?

**Comment by Bakual** [comment]
Why should it not work? I didn't change anything in the formfield.

**Comment by laoneo** [comment]
But you are changing back something which was introduced on purpose. If that still works, then all is fine. Just wanted to double check before merging.

**Comment by brianteeman** [comment]
> But you are changing back something which was introduced on purpose.

which is a big red warning flag to me

**Comment by Bakual** [comment]
I honestly doubt that it indeed was changed on purpose. 
To me it looks more like copy-paste, because in other places it indeed has to be (and was before) required.
But here I couldn't find any issues with it being optional. And yep, of course the formfield can handle empty values.

Also, as I already wrote in the PR description, the code of the module already handles the case when no category is selected. I didn't had to change anything there.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
