### PR TITLE
2009 to 2016

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Very simple PR. Update some dates in comments in some files 2009 --> 2016.
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2c1f485b6ae311406a83b787387e540d00b713fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10843">issues.joomla.org/joomla-cms/10843</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 2c1f485b6ae311406a83b787387e540d00b713fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10843">issues.joomla.org/joomla-cms/10843</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10843">issues.joomla.org/joomla-cms/10843</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks all for testing and merging!

**Pull request merged**
