### PR TITLE
[5.1] update plugin services provider

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Apply changes from #40746 (Remove extra reference assignment in plugin constructor for dispatcher argument) to current branch

### Testing Instructions

code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on de1dc01d0bf4cb83fc0637ba7d548787abbd2cb3<br /><br />Code review !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42905">issues.joomla.org/tracker/joomla-cms/42905</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on de1dc01d0bf4cb83fc0637ba7d548787abbd2cb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42905">issues.joomla.org/tracker/joomla-cms/42905</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42905">issues.joomla.org/tracker/joomla-cms/42905</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
