### PR TITLE
[4.0] Error on privacy request page

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds missing import.

### Testing Instructions

Create a privacy request in backend.
View the request.

### Expected result

No errors.

### Actual result

>An error has occurred.
>0 Class 'ActionlogsHelper' not found 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d57cf6f6d88846e554db49aa3ccc2c82e7304092<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26419">issues.joomla.org/tracker/joomla-cms/26419</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on d57cf6f6d88846e554db49aa3ccc2c82e7304092<br /><br />- create new request in Users > Privacy > Requests
- click on email column link displays  Class 'ActionlogsHelper' not found
- After patch applied, request is displayed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26419">issues.joomla.org/tracker/joomla-cms/26419</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26419">issues.joomla.org/tracker/joomla-cms/26419</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
