### PR TITLE
[4.3] Migrate quickicon privacycheck plugin to services

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Migrate the quickicon privacycheck plugin to service providers and use SubscriberInterface.

### Testing Instructions

- Check if quickicons are still working

image
image

### Actual result BEFORE applying this Pull Request

Privacycheck quickicon is working

### Expected result AFTER applying this Pull Request

Privacycheck quickicon is working (and the other quickicons are still displayed)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 948ddd04c54501d0e78eea65d0f6b19b8242903f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39172">issues.joomla.org/tracker/joomla-cms/39172</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 948ddd04c54501d0e78eea65d0f6b19b8242903f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39172">issues.joomla.org/tracker/joomla-cms/39172</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39172">issues.joomla.org/tracker/joomla-cms/39172</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for this PR!

**Comment by heelc29** [comment]
Thanks

**Pull request merged**
