### PR TITLE
[4.2] Inconsistency in permission rules - configure options only - API

### PR DESCRIPTION
**Pull request by tecpromotion**
Add-on Pull Request for PR #38781 .

### Summary of Changes

remove "Only" in API.
See PR #38781

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

JACTION_OPTIONS="Configure Options Only"

### Expected result AFTER applying this Pull Request

JACTION_OPTIONS="Configure Options"

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed

- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tecpromotion** [comment]
@chmst @roland-d

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6861760f379e0fd8a31bf6a2a411c3c3d3890be7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39682">issues.joomla.org/tracker/joomla-cms/39682</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6861760f379e0fd8a31bf6a2a411c3c3d3890be7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39682">issues.joomla.org/tracker/joomla-cms/39682</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39682">issues.joomla.org/tracker/joomla-cms/39682</a>.</sub>

**Comment by fancyFranci** [comment]
That's better. Thank you!

**Pull request merged**
