### PR TITLE
[staging] Missing Web Links language strings

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says. This PR adds strings present in last version (3.7.0) of web links.
Installing the web links package will provide the new strings but these are not present in the other languages pack as they are absent from en-GB core distribution.
Using German in backend will show the strings have not been added/translated.

### Testing Instructions
Install weblinks package. https://downloads.joomla.org/extensions/weblinks/3-7-0

Switch backend to German.
Set Debug Language on

Create a weblink.

### Actual result BEFORE applying this Pull Request
Example:
Screen Shot 2020-08-01 at 11 32 31

### Expected result AFTER applying this Pull Request
As the strings will now be present (after translation by German Team in next release), they will show Ok.
The French pack does already contain these missing strings

Screen Shot 2020-08-01 at 11 37 45

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e880cd0110f64937b4f281d04416826a4f4f24e6<br /><br />By chance I am working on a site with the weblinks component right now - so could test at once. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30253">issues.joomla.org/tracker/joomla-cms/30253</a>.</sub>

**Comment by infograf768** [comment]
@chmst 
We also miss 4 ini files. Grrr

plg_editors-xtd_weblink.ini
plg_editors-xtd_weblink
plg_system_weblinks.ini	
plg_system_weblinks.sys.ini												

Shall I add them here or in new patch? What you think?

**Comment by 4digitalworld** [comment]
@infograf768 I was creating 2 issues ([418](https://github.com/joomla-extensions/weblinks/issues/418) & [419](https://github.com/joomla-extensions/weblinks/issues/419))  that are currently in this component, but no one answered. is this component currently being developed here or in another directory?

**Comment by chmst** [comment]
Add it to this PR. It is an easy test

**Comment by infograf768** [comment]
@sanek4life 
Any issue with weblinks is indeed to be created where you did it. Needs a volunteer to correct bugs there. Will have a look.

**Comment by infograf768** [comment]
@chmst 
Done.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c5aa50a899f67c136b766c9c84d3b55ebffa1601<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30253">issues.joomla.org/tracker/joomla-cms/30253</a>.</sub>

**Comment by infograf768** [comment]
@HLeithner 
Please merge.

**Comment by infograf768** [comment]
@sanek4life 
Replied to both your issues ([418](https://github.com/joomla-extensions/weblinks/issues/418) & [419](https://github.com/joomla-extensions/weblinks/issues/419)) for weblinks.

**Comment by HLeithner** [comment]
Thanks, I'm wondering why com_weblinks translations are still in core...

**Comment by infograf768** [comment]
> Thanks, I'm wondering why com_weblinks translations are still in core...

It was decided to keep the web links ini files in core for the 3x series when web links were separated as we have no structure to propose specific languages for them.

**Comment by HLeithner** [comment]
thx for the info

**Comment by Bakual** [comment]
More background to language files in weblinks: https://github.com/joomla-extensions/weblinks/pull/383

**Comment by infograf768** [comment]
At this stage, all web links ini files are no more present in J4.

See https://github.com/joomla-extensions/weblinks/pull/415#issuecomment-569253896

**Pull request merged**
