### PR TITLE
[4.1] PLG_TINY_FIELD_SKIN_INFO_DESC

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the path in the description for the location of the skins

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 610c44a54ab1a6663d0b00d49c2c06399410c63f<br /><br />Theoretically it should be fixed in 4.0-dev: https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/tinymce/tinymce.php#L239

Practically, due to the short remaining life time of 4.0, it might be ok to do it in 4.1 only.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36740">issues.joomla.org/tracker/joomla-cms/36740</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 610c44a54ab1a6663d0b00d49c2c06399410c63f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36740">issues.joomla.org/tracker/joomla-cms/36740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36740">issues.joomla.org/tracker/joomla-cms/36740</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 610c44a54ab1a6663d0b00d49c2c06399410c63f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36740">issues.joomla.org/tracker/joomla-cms/36740</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
