### PR TITLE
Copyright update after #3447

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #3447 .
#### Summary of Changes

2014 -> 2016
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on f2676c1779626472a8208bc172b3c543e836e144<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10831">issues.joomla.org/joomla-cms/10831</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on f2676c1779626472a8208bc172b3c543e836e144<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10831">issues.joomla.org/joomla-cms/10831</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10831">issues.joomla.org/joomla-cms/10831</a>.</sub>

**Comment by zero-24** [comment]
Thanks :smile:

**Pull request merged**
