### PR TITLE
[4.0] Update HTML error pages

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Updates static HTML pages after changes in https://github.com/joomla/joomla-cms/pull/31007.

### Testing Instructions

Run `node build.js --build-pages`. Check if Git tracks any changes.

### Actual result BEFORE applying this Pull Request

These files keep getting modified:

```
templates/system/incompatible.html
templates/system/build_incomplete.html
```

### Expected result AFTER applying this Pull Request

No more files are getting modified.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
And do we actually need to keep these files in the repository?

**Comment by richard67** [comment]
> And do we actually need to keep these files in the repository?

I'd say no, but maybe I'm missing something.

@wilsonge Do you know why we have `templates/system/incompatible.html` and `templates/system/build_incomplete.html` in the sources when we rebuild them anyway?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b267e56f9c1ac38e9bdbde52a500827abf131b47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31108">issues.joomla.org/tracker/joomla-cms/31108</a>.</sub>

**Comment by dgrammatiko** [comment]
> And do we actually need to keep these files in the repository?

Yes they're used both in the installation and the index.php
https://github.com/joomla/joomla-cms/blob/5813af58abdc61c8c71bcdf4302d5a0bb1b505b3/installation/index.php#L18-L27

https://github.com/joomla/joomla-cms/blob/5813af58abdc61c8c71bcdf4302d5a0bb1b505b3/index.php#L18-L27

**Comment by richard67** [comment]
> Yes they're used both in the installation and the index.php

But they are generated by the build script, or not? That should be sufficient for these cases, or am I missing something?

**Comment by dgrammatiko** [comment]
> But they are generated by the build script, or not?

Unless I messed up really bad, it should after running this command:
https://github.com/joomla/joomla-cms/blob/5813af58abdc61c8c71bcdf4302d5a0bb1b505b3/build.js#L9

**Comment by richard67** [comment]
> Unless I messed up really bad, it should after running this command:
> 
> https://github.com/joomla/joomla-cms/blob/5813af58abdc61c8c71bcdf4302d5a0bb1b505b3/build.js#L9

Yes, and that's the subject of this PR and I have tested it.

So why should we keep the result pages in the GitHub sources?

**Comment by dgrammatiko** [comment]
> So why should we keep the result pages in the GitHub sources?


It's the same reason the project still keeps all the generated css in the templates, etc... (iirc at some point, before getting auto generated installables per PR, there was a decision to keep these files in place as a fallback). They shouldn't exist in the repo, if you ask me...

**Comment by richard67** [comment]
> They shouldn't exist in the repo, if you ask me...

Then it seems we agree.

**Comment by SharkyKZ** [comment]
Forget my question 🤦‍♂️. We do need these. `build_incomplete.html` is shown to users running on Git clones but *before* they run any build scripts.

**Comment by richard67** [comment]
> 
> 
> Forget my question 🤦‍♂️. We do need these. `build_incomplete.html` is shown to users running on Git clones but _before_ they run any build scripts.

Ahhhh, silly me, sure I should have known that. That's the purpose of that file.

**Comment by ceford** [comment]
Not sure about this: I noticed that both were marked as changed after I did a Refresh - so they were not there at some time. Deleted them and ran the build - file are there. Committed so the change marker vanished. Ran build again - no change, Repeated without the patch - no change.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31108">issues.joomla.org/tracker/joomla-cms/31108</a>.</sub>

**Comment by wilsonge** [comment]
We're all good - think we're all back on the same page. LGTM. Thanks!

**Pull request merged**
