### PR TITLE
[4.0] Cassiopeia dropdown accessible

### PR DESCRIPTION
**Pull request by astridx**
Draft for https://github.com/joomla/joomla-cms/pull/29413.

### Summary of Changes

1. I added https://github.com/NickDJM/accessible-menu so that the **top menu** can used as drop down and a11y is fine.
2. I also made it possible, that `templates/cassiopeia/js/template.js` is minified via `build and npm`. 

There is no styling. (I changed the font color so that you can read the texts.)

### Testing Instructions

1. Apply this branch, delete the file `templates/cassiopeia/js/template.min.js` and run `npm ci`

2. Install `Testing Sample Data `
Control Panel testq Administration

3. Add some Menu Items in different levels to the top menu. If a menu item is drop down you should set it as system link
Menus Edit Item testq Administration

### Actual result BEFORE applying this Pull Request
Drop Down is ignored

### Expected result AFTER applying this Pull Request
Sample Sites
Getting Started

### Documentation Changes Required
Not sure

### CODE REVIEW

**Comment by brianteeman** [comment]
Unless I am mistaken cassiopeia is a bootstrap 4 template. BS4 by default has an accessible dropdown menu. The problem is that the markup generated by the menu module has not been updated to that markup.

https://getbootstrap.com/docs/4.4/components/navs/

**Comment by astridx** [comment]
@brianteeman Please see https://github.com/NickDJM/accessible-menu/issues/77#issuecomment-633317114

**Comment by brianteeman** [comment]
I have read it and I am personally not convinced in the benefit of adding yet another dependency

**Comment by coolcat-creations** [comment]
If we really call another dependency than I see rather an adobe megamenu more beneficial than that. Thats why I also tend to use BS4 with a proper styling. 

https://adobe-accessibility.github.io/Accessible-Mega-Menu/

**Comment by astridx** [comment]
I think it is a pity. I found it good because it is bootstrap independent (if you want to get away from it) doesn't use jQuery (adobe megamenu) and you still don't have to reinvent the wheel yourself.

**Comment by dgrammatiko** [comment]
Wow this is how the project should solve the problems, eg modular. In this case a script without any further dependencies (esp jQuery, that will be included in every page if the menu is based on the Bootstrap js) is the proper way out. Not to mention that this is really accessible (eg has key listeners for all the expected keys not just tab, which works only in non nested menus). I'm really sorry @astridx

**Pull request closed without merging**
