### PR TITLE
[JAccess] Improve ACL asset preloading performance/memory consumption

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Improve ACL asset preloading performance/memory consumption.
#### Before

image
#### After

image
### Testing Instructions
1. Code review
2. Use latest staging and apply patch
3. Turn on debug mode and debug system plugin
4. Check the profiler in several frontend/backend pages and notice the more ACL checks are done the more is the performance improvements.
5. Check if ACL permissions work fine (do multiple tests). Make sure there are no ACL breachs after this.

The performance improvements are particular higher when logged in with a non-root user and a lot of modules (since in this cases there are a lot of ACL checks).
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
hum ... don't quite understand why unit tests are failing

```
There were 3 failures:
1) JUserTest::testAuthorise with data set "null asset Super Admin" (42, 'core.create', null, true)
Line: 259 Failed for user 42
Failed asserting that null matches expected true.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/user/JUserTest.php:260

2) JUserTest::testAuthorise with data set "fictional action Super Admin" (42, 'nuke', 'root.1', true)
Line: 259 Failed for user 42
Failed asserting that null matches expected true.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/user/JUserTest.php:260

3) JUserTest::testAuthorise with data set "core.admin Super Admin" (42, 'core.admin', 'root.1', true)
Line: 259 Failed for user 42
Failed asserting that null matches expected true.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/user/JUserTest.php:260
```

If i do
```php
echo '<br/>'.var_dump(JAccess::check(767, 'core.create', null));
echo '<br/>'.var_dump(JAccess::check(767, 'nuke', 'root.1'));
echo '<br/>'.var_dump(JAccess::check(767, 'core.admin', 'root.1'));
echo '<br/>'.var_dump(JFactory::getUser(767)->authorise('core.create', null));
echo '<br/>'.var_dump(JFactory::getUser(767)->authorise('nuke', 'root.1'));
echo '<br/>'.var_dump(JFactory::getUser(767)->authorise('core.admin', 'root.1'));
```
With or without the patch it returns
```
NULL 
NULL 
bool(true) 
bool(true) 
bool(true) 
bool(true) 
```
Note: 767 is the test install super user id

**Comment by andrepereiradasilva** [comment]
Just an additional info.
This is the performance/memory usage difference with a logged (non super user) joomla clean test sample data install frontend home page.

### Before
image

### After
image

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 040f0694dcffe19fca635e8c4537337bb7c78922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12028">issues.joomla.org/joomla-cms/12028</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 040f0694dcffe19fca635e8c4537337bb7c78922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12028">issues.joomla.org/joomla-cms/12028</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12028">issues.joomla.org/joomla-cms/12028</a>.</sub>

**Comment by andrepereiradasilva** [comment]
should go to 3.7.x IMO

**Comment by zero-24** [comment]
Done thanks!

**Pull request merged**
