### PR TITLE
Remove array_column function

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #10942 .
#### Summary of Changes

replaced a not in 5.4 available function with some pure php code that should do the same thing
#### Testing Instructions

see #10670

### CODE REVIEW

**Comment by bertmert** [comment]
There's also an API function doing the same like array_column:
ArrayHelper::getColumn($redirects, 'old_url')

**Comment by rdeutz** [comment]
@bertmert because there is a native function I would depreciate the function, if we have a higher minimum PHP version it should go away. So I think a valid argument for using it is that we can identify the places where we have to replace code. For me not a great argument :-)

**Comment by ggppdk** [comment]
Why are we not using an array indexed by:
$redirect['old_url']
that points to object references of $redirect

and then use isset() ? it should be much faster

**Comment by mbabker** [comment]
It looks like `ArrayHelper::getColumn()` can deal with nested arrays while `array_column()` is a single array only.  I guess that's one reason to keep it but perhaps redo the internals to just use `array_column()`.

/off-topic

**Comment by rdeutz** [comment]
@ggppdk I don't have a good feeling to use an url as an index for an array.

**Comment by ggppdk** [comment]
@rdeutz 
> I don't have a good feeling to use an url as an index for an array.

i did not know that, i missed this,
do you have a link mentioning the dangers of it?

Understanding the PHP array implementation
the "index" , in our case url (string) will be hashed, and any collisions are handled with a linked list that holds the real value that was hashed

or do you mean something else ?

**Comment by rdeutz** [comment]
@ggppdk just a feeling without evidence, same level as I don't use spaces in a filename :-)

**Comment by ggppdk** [comment]
I see what you mean now,

any binary data can be used as index in PHP, hash function will just read bytes

In PHP, associative arrays are implemented as hashtables with some extra functions

**Comment by brianteeman** [comment]
I assume that this can be closed as @eilsonge merged #10947 ??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10943">issues.joomla.org/joomla-cms/10943</a>.</sub>

**Comment by wilsonge** [comment]
Yes - I was in the middle of typing that :) I've gone with the polyfill as it's effectively making our code optimised and forwards compatible

**Pull request closed without merging**
