### PR TITLE
[4.0] Fix contact information switcher display

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix contact information switcher displaying the wrong color state.

### Testing Instructions
Go to Global Configuration > Contacts
See `Contact Information` switcher

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 4ae6d8bc60a8e45e1ea184b0eaece06d72eb3c37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27644">issues.joomla.org/tracker/joomla-cms/27644</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 4ae6d8bc60a8e45e1ea184b0eaece06d72eb3c37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27644">issues.joomla.org/tracker/joomla-cms/27644</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27644">issues.joomla.org/tracker/joomla-cms/27644</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
