### PR TITLE
Remove testing sample data plugin

### PR DESCRIPTION
**Pull request by Bakual**
As mentioned in Issue #17456 we don't have the testing sample data available in stable releases, so it doesn't make much sense to ship this sample data plugin in a stable release.
We can make it available separately for testers (needs an own repo and some doc I guess).

Maybe we can add another sample data plugin, because the list looks a bit empty with only one sample set :smile: 

@mbabker I just removed the plugin files and the statetement from the initial SQL. If we only support updates from the latest stable, this will work. If you want to support updates from 3.8.0 beta we would have to add a new SQL where the entry is removed and also add the deleted files to the script. Your choice to make :smile: 

### Summary of Changes
Removes the testing sample data plugin

### Testing Instructions
Test that only the blog sample data plugin is left in the module.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
If it is available for testers, would there be a simple way to get it? Something as we do for weblinks I guess. IMHO no use for TTs to translate its inis as en-GB is always used for testing sample data as far as I know.

**Comment by Bakual** [comment]
Yep, I guess something like https://github.com/joomla-extensions/testing-sample-data and yes, doesn't need to be translated.

**Comment by mbabker** [comment]
There are merge conflicts.

**Comment by Bakual** [comment]
It's likely the added dot to the description. Should be simple to solve, since we remove the files anyway :)
Just can't do it at the moment. Will have a look later this day.

**Comment by Bakual** [comment]
Rebased and conflicts solved.

**Comment by infograf768** [comment]
still some conflicts

**Comment by Bakual** [comment]
Rebased again

**Comment by mbabker** [comment]
Once I see Travis is green I'll hit merge (anyone else feel free to do so if they see it before me).

**Comment by Bakual** [comment]
For reference, the plugin lives now at https://github.com/joomla-extensions/testing-sample-data/

**Pull request merged**
