### PR TITLE
[4.0] Upload and Update message

### PR DESCRIPTION
**Pull request by brianteeman**
It is perfectly correct to open a new window in this scenario as you are being asked to download something from another site to install into the current page. As such this PR adds the target and referrer values and the icon to indicate that the link is opening in a new window

### Before
image

### After
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 142f569311de2e12d3f154c41b0fdfe2844ea3d7<br /><br />Tested successfully in Beta8-dev of 12 February.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32392">issues.joomla.org/tracker/joomla-cms/32392</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 142f569311de2e12d3f154c41b0fdfe2844ea3d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32392">issues.joomla.org/tracker/joomla-cms/32392</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32392">issues.joomla.org/tracker/joomla-cms/32392</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
