### PR TITLE
Fix error in mergeHeadData method for html document

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

This PR does two things:
- extend tests in order to display the error in php Travis tests.
- fix the error generated by `array_unique` function
### Testing Instructions

How to reproduce notices?

``` php
$html = new JDocumentHtml();
$html->addHeadLink('http://www.example.com', 'Start');
$html->addHeadLink('http://www.example.com/end', 'End');
$html->mergeHeadData($html->getHeadData());
```

generates several:

```
PHP Notice:  Array to string conversion in /home/[...]/libraries/joomla/document/html.php on line 222
```

And `$html->_links` contain only first link.

After patch this notice disappears and links contain all links.
### Documentation Changes Required

No

### CODE REVIEW

**Comment by wilsonge** [comment]
Why do we have an array here. Is it expected or is it a bug in the test data?

**Comment by csthomas** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer/html/head.php#L115

**Comment by csthomas** [comment]
Should I fix tests for php to display some errors as in hhvm before adding current commit?

**Comment by csthomas** [comment]
This is a simple fix + extend test. if no one is interested?

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12013">issues.joomla.org/joomla-cms/12013</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 03bde816bc902d3df1fa9dd4b8bff3b5f0330cef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12013">issues.joomla.org/joomla-cms/12013</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12013">issues.joomla.org/joomla-cms/12013</a>.</sub>

**Comment by photodude** [comment]
Awesome, glad to see someone found a solution without needing to wait for [HHVM to fix the special casing for `<= 1` elements with array_merge()](https://github.com/facebook/hhvm/issues/7239) 

Note: we would have had the same error in php if the top level of the nested array had just one more element
https://3v4l.org/vHUAv

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Pull request merged**
