### PR TITLE
Update MediaElement.js to 2.23.5

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes

This PR updates the library MediaElement.js to version [2.23.4](https://github.com/johndyer/mediaelement/releases/tag/2.23.4).
### Testing Instructions

Upload a mp4 into the Media Manager and try view the video.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8bcd8ddb3d303d9232b129e5f61787b45d974347<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13283">issues.joomla.org/tracker/joomla-cms/13283</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :red_circle: unsuccessfully on 8bcd8ddb3d303d9232b129e5f61787b45d974347<br /><br />Hi,

When I try to upload it with Media Manager, it shows an error: Error. This file type is not supported.

If I manually copy the file and try to play it, then the video is played Ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13283">issues.joomla.org/tracker/joomla-cms/13283</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@anibalsanchez had the same Problem, after append "mp4" to "Media > Options > Legal Extensions (File Types)" Problem gone.

**Comment by anibalsanchez** [comment]
Confirmed. It works if mp4 is added to Legal Extensions .... then it should be included in administrator/components/com_media/config.xml

		default="bmp,csv,doc,gif,ico,jpg,jpeg,odg,odp,ods,odt,pdf,png,ppt,swf,txt,xcf,xls,BMP,CSV,DOC,GIF,ICO,JPG,JPEG,ODG,ODP,ODS,ODT,PDF,PNG,PPT,SWF,TXT,XCF,XLS"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13283">issues.joomla.org/tracker/joomla-cms/13283</a>.</sub>

**Comment by genesisfan** [comment]
I have tested this item :red_circle: unsuccessfully on d8390f556aaffd9ff887c1f954ed7d2fe4c9c733<br /><br />Confirmed. Uploading mp4 is working if mp4 is added to Legal Extensions.
I can't play the mp4; _Error loading this resource_

Used Codec:
Type: Video
Codec: H264 - MPEG-4 AVC (part10) (avc1)
Resolution: 560x320
Frame rate: 30
Decoded format: Planar 4:2:0 YUV

I can confirm that MediaElement.js 2.23.5 is used.
```javascript
// version number
mejs.version = '2.23.5';
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13283">issues.joomla.org/tracker/joomla-cms/13283</a>.</sub>

**Comment by viocassel** [comment]
giphy

**Pull request closed without merging**
