### PR TITLE
[4.1] Batch process admin menu items

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #36760 .

> ### Steps to reproduce the issue
> **Create additional admin menu**
> 
> * switch to administrator/index.php?option=com_menus&view=menus
> * switch to "Administrator" in top left
> * Click New and create Menu
> 
> **create menu entries in the new menu**
> 
> * switch to menu entry editing: administrator/index.php?option=com_menus&view=items&menutype=NEWMENU
> * add some entries in the newly created menu
> 
> **try to move entries with batch functionality**
> 
> * now select some of the new menu items and click on "Actions -> Batch"
> * in the popup folder select an entry and choose to move or copy
> 
> ### Expected result
> Button Submit should be clickable to batch process the entries See scrennshot also. In all other views there is a button at the marked place. Modal is useless without this button.
> 
> ### Actual result
> **submit button is missing, only cancel button is shown**
>

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1984cd8c05376638be6967e9e12465fb7f2545d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36762">issues.joomla.org/tracker/joomla-cms/36762</a>.</sub>

**Review by richard67 — APPROVED** [review]
By review the changes here are correct ... just asking myself why nobody has noticed that before. Will test in a bit.

**Comment by brianteeman** [comment]
> By review the changes here are correct ... just asking myself why nobody has noticed that before. Will test in a bit.

A combination of not many people taking advantage of custom admin menus and then a smaller subset trying to use batch and then an even smaller subset who ever report a bug.

**Comment by richard67** [comment]
> A combination of not many people taking advantage of custom admin menus and then a smaller subset trying to use batch and then an even smaller subset who ever report a bug.

Well, the last mentioned subset seems to increase recently, and that could be a good sign because it could mean Joomla is becoming more popular. (Sorry for off-topic.)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4d3d4917af03f7d5cd6eda1ecc451de30c73340a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36762">issues.joomla.org/tracker/joomla-cms/36762</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4d3d4917af03f7d5cd6eda1ecc451de30c73340a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36762">issues.joomla.org/tracker/joomla-cms/36762</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36762">issues.joomla.org/tracker/joomla-cms/36762</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
