### PR TITLE
[4.1] Unification of the language com_scheduler

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Unification of the language to other components
reduction of exclamation marks
Adjustment of the punctuation marks
Emtpy state alignment

### Testing Instructions

e.g. open com_scheduler 

### Expected result AFTER applying this Pull Request

Bildschirmfoto 2021-12-12 um 11 38 28

### Documentation Changes Required

.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on eae7432a3b7894d0749780b4d451fa2c46208463<br /><br />Tested by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36294">issues.joomla.org/tracker/joomla-cms/36294</a>.</sub>

**Comment by ditsuke** [comment]
I have tested this item :white_check_mark: successfully on eae7432a3b7894d0749780b4d451fa2c46208463<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36294">issues.joomla.org/tracker/joomla-cms/36294</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36294">issues.joomla.org/tracker/joomla-cms/36294</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
