### PR TITLE
[4.3] Remove renaming of fieldname in subform

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue # .

### Summary of Changes
For unknown reasons subfoms fieldname ais renamed when generated by custom fields. This leads to the fact, that the field has a new (not unique) fieldname anymore.

### Testing Instructions
Generate subforms (several) and try to get their field name like: ```$form->getField('subform', 'com_fields')->fieldname```

### Actual result BEFORE applying this Pull Request
only "row"

### Expected result AFTER applying this Pull Request
The real name of the field

### Additional information
Original PR: https://github.com/joomla/joomla-cms/pull/24711

@laoneo @wilsonge @continga probably you see here any issues by removing it?

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
@crystalenka tagging you as I am sure you created an issue for this but I cant see it now

**Comment by crystalenka** [comment]
Iirc this will change the way subform fields are called in templates and would majorly break existing templates. I ran into this with the subform issue in the contact display issue I believe

**Comment by crystalenka** [comment]
I just checked and this is the exact same thing I ran into in issue #38737

Check the comments for what I found it affects and why I decided not to change it at that point. (It would be a hard b/c break for templates due to the way JSON is returned.)

**Comment by Fedik** [comment]
Thanks @crystalenka for hint about json.

Comment says:
> // Override the fieldname attribute of the subform - this is being used to index the rows

I guessing it was made only for array access, like `$value['row1'], $value['row2'] ...`
And that a :hankey: 

Correct would be to store the value as indexed array, before save the value do (or before use):
```php
if ($multiple) {
  $value = array_values($value);
}
```
And that what you always should do when manipulating with subform "rows".
That key newer should be used in PHP, it was made for some fancy manipulation in javascript, in past.

But I not sure that we can fix it in 4.2.x, such changes can introduce a litle break, for anyone who use this key.

**Comment by bembelimen** [comment]
Yes the only "issue" I see is, that when someone access the value directly (the subform itself works) on row0, row1.
As Crystal anyways changed the output, we could add a directly deprecated fallback somehow.

**Comment by crystalenka** [comment]
I did not change the output of the subform plugin, but this PR would 

A fallback to avoid breaking layouts would be good because I do think I've seen tutorials (maybe in the magazine?) which instructed people to access the fields directly

**Comment by brianteeman** [comment]
> A fallback to avoid breaking layouts would be good because I do think I've seen tutorials (maybe in the magazine?) which instructed people to access the fields directly

and in the docs site

**Comment by bembelimen** [comment]
Do you have a link? Accessing the field shouldn't be a problem, accessing the value is worse

**Comment by crystalenka** [comment]
I know that I personally have accessed the value in some templates and I don't think I came up with it out of nowhere since layout overrides/templates using subforms had to be refactored from Joomla 3 to Joomla 4. 

I recall some discussion about it (maybe here in GitHub somewhere? or on Facebook?) about why the fields are indexed by id instead of field name in the JSON, it was an intentional choice at the time that was heavily defended by some contributors but I can't recall by whom or where—sorry. 

Unfortunately since this has been how it works for a while I don't think we can change it without providing some kind of fallback, certainly not in 4.x and possibly not in 5 either due to the b/c promise and the fact that this could break some templates or layout overrides pretty substantially. :(

**Comment by crystalenka** [comment]
JSON referenced here: https://magazine.joomla.org/all-issues/october-2021/custom-fields-episode-7-part-1-one-custom-field-to-rule-them-all

**Comment by Fedik** [comment]
In that example used `foreach($items as $item):`, if your code use the same approach then you in safe.

image

**Comment by bembelimen** [comment]
> In that example used `foreach($items as $item):`, if your code use the same approach then you in safe.

Yes, that's why I'm looking... I see that direct accessing the values can be a problem. That can be overcome by either have the values twice or change the layout itself, so overrides are marked as outdated.

**Comment by crystalenka** [comment]
Overrides would only be marked as outdated if it was an override of the default files though, right? So if someone creates alternative layouts (for example for an article), and assigned that layout to articles in a category, it wouldn't show as outdated. (Correct me if I'm wrong!)

Is it possible to have the values twice and flag it as deprecated, so that people can ensure they're accessing the values correctly before the old way gets removed?

Either way, I don't think that anything should be removed in 4.x....and maybe not in 5.0, either, unless we do a big awareness push as part of the update to 5. :/

**Comment by Fedik** [comment]
Can you please update your PR.
Also I think this should be remove too:

https://github.com/joomla/joomla-cms/blob/b9453908eb8ab25f98078e6fd9615674b1095bba/plugins/fields/subform/src/Extension/Subform.php#L409-L410

We should not rename child fields, it may broke a loot of lonked JS and etc. As it happen with Showon already.

**Comment by AndySDH** [comment]
> I recall some discussion about it (maybe here in GitHub somewhere? or on Facebook?) about why the fields are indexed by id instead of field name in the JSON, it was an intentional choice at the time that was heavily defended by some contributors but I can't recall by whom or where—sorry.

@crystalenka As far as I know, this was done because it was safer to save the json of the subform output with child IDs stored with field ID (eg. field15) instead of the name/alias (eg. 'my-text-field').

The reason is because, if you changed the name of a child field, and the json contained that name, you would lose all the entered data the next time you opened the article form.

Instead, by storing it like field15 in the json, even if you change the name of the field, you're safe that you won't lose the data.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Pull request closed without merging**
