### PR TITLE
[4.4] TinyMCE 5.10.9

### PR DESCRIPTION
**Pull request by brianteeman**
This is a security release

### Changed
- Zero width no-break space (U+FEFF) characters are removed from content passed to setContent, insertContent, and resetContent APIs.
- Zero width no-break space (U+FEFF) characters in initial content are not loaded into the editor upon initialization. 

### Fixed
- Specific HTML content containing unescaped text nodes caused mXSS when using undo/redo. 
- Specific HTML content containing unescaped text nodes caused mXSS when using the getContent and setContent APIs with the format: 'raw' option, which also affected the resetContent API and the draft restoration feature of the Autosave plugin

### CODE REVIEW

**Comment by brianteeman** [comment]
Note a similar update is required for tiny6 and joomla5 but I cant create it due to this bug #42356

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 7031c0ce7673ccce4da719be64ba42ce7680ab33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42359">issues.joomla.org/tracker/joomla-cms/42359</a>.</sub>

**Comment by wilsonge** [comment]
Just noting that I see the TinyMCE6 update has been done directly with https://github.com/joomla/joomla-cms/commit/ba3fa037fa247dc53929e061a4eaea5c38fa9a8d

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on 7031c0ce7673ccce4da719be64ba42ce7680ab33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42359">issues.joomla.org/tracker/joomla-cms/42359</a>.</sub>

**Comment by brianteeman** [comment]
> Just noting that I see the TinyMCE6 update has been done directly with https://github.com/joomla/joomla-cms/commit/ba3fa037fa247dc53929e061a4eaea5c38fa9a8d



Grrh

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42359">issues.joomla.org/tracker/joomla-cms/42359</a>.</sub>

**Pull request merged**
