### PR TITLE
[3.10] com_joomlaupdate pointing to joomla 4 when showing as Default in upgraded systems with longer history

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #35212

### Summary of Changes

Make sure the old setting "sts" thats showed as "Default" also behaves as "Default" and not as Joomla Next

### Testing Instructions

- Set the update server in the database as "sts"
- Joomla shows it as "Default" but points to the "joomla next" update server

### Actual result BEFORE applying this Pull Request

Joomla points to Joomla Next and therefor to Joomla 4

### Expected result AFTER applying this Pull Request

Joomla points to the actual Default update server and therefore 3.10

### Documentation Changes Required

https://docs.joomla.org/J3.x:Joomla_3.10_points_to_4.0_while_it_claims_to_be_on_the_Default_update_server

### Additional

- We might have to do a com_joomlaupdate release to catch sites still pointing to 4 but will not get the updates to 3.10.1
- We might should clear the #__updates table on changing the setting to be sure the update cache is cleared

### CODE REVIEW

**Comment by mariantanase** [comment]
I have tested this item :white_check_mark: successfully for #35214

**Comment by zero-24** [comment]
FAQ page created: https://docs.joomla.org/J3.x:Joomla_3.10_points_to_4.0_while_it_claims_to_be_on_the_Default_update_server

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0faf5c1a21d999de2105c8bf64094f356a27af3b<br /><br />Since I no longer had this situation, I changed the phpPMyAdmin to the following:
{"updatesource": "sts", "customurl": ""}
This made it possible to achieve actual result. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35214">issues.joomla.org/tracker/joomla-cms/35214</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks.

**Pull request merged**
