### PR TITLE
[SEO] - Deleted tags not redirecting to 404 error page

### PR DESCRIPTION
**Pull request by fancyFranci**
A Solution for issue #5148

**The issue:**
When an url of an unknown tag is requested, joomla handles this like an existing tag with the message "No matching items were found.". A 404 error should be thrown instead.

**My solution:**
When the tag ID (out of the given url) is searched in the database, I check the primary key of the "found" object. When there is no one, I throw the 404 error, with a "Tag not found." message.

**Testing instructions:**
- Enter an url with a tag that does not exist in your joomla.
- Important is the ID and not the name behind the minus.
- For example: localhost/example-page/index.php/all-tags/99-foo

**Expected result:**
A 404 error appears instead of a "No matching items were found." message.

Worked as a group on that issue: @icampus @flow87 @kathastaden @xsability

### CODE REVIEW

**Comment by brianteeman** [comment]
Language strings are normally ordered alphabetically so please can you update the proposed change in the language file

**Comment by FPerisa** [comment]
Thank you for your comment! 
I will check my git problems (with the unnecessary commit) and sort the language file.

**Comment by snarf007** [comment]
I have tested this item :white_check_mark: successfully on ec507fcd249eef971ee54cde163be7b1b3078a5c<br /><br />Before istalling the patch recieved the following message: No matching items were found.
After installing the patch: No matching items were found. (404 Tag not found. )

Result as expected


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Comment by dam-man** [comment]
I have tested this item :white_check_mark: successfully on ec507fcd249eef971ee54cde163be7b1b3078a5c<br /><br />404 is better to show indeed - Patch is working as expected and throwing a 404 now instead of a message.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Comment by zero-24** [comment]
RTC is on hold until @FPerisa gets time to fix the language string ordering ;) Thanks.

**Comment by roland-d** [comment]
@FPerisa Can you please fix the language ordering so we can merge this fix? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Comment by frascan** [comment]
I have tested this item successfully; with result as expected.
Test took place in the context of Pizza & Fun Bug JUG Rome.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Comment by ZioPal** [comment]
I successfully tested, I think is a sensible change. The test took place in the Pizza and Fun JUG Rome.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Comment by dgt41** [comment]
@FPerisa can you please merge https://github.com/FPerisa/joomla-cms/pull/1 to move this to RTC?

**Comment by dgt41** [comment]
RTC since the language strings are now alpha ordered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8040">issues.joomla.org/joomla-cms/8040</a>.</sub>

**Pull request closed without merging**
