### PR TITLE
Regression: Solves searchtools filters bugs and regressions

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for **Regression** and several bugs.
#### Summary of Changes

With all the changes in searchtools some filters have a wrong input filtering. Some were caused by my PRs, and many other were already there. 

Anyhow, most of this problems only manifests itself in hathor.

As you see from the code changes, besides the input filtering, there are a series of inconsistencies in the filters names (and other) that cause this bugs.
#### Testing Instructions

First test on isis to confirm they are all working properly:
1. Use latest staging and apply this PR
2. Go to "Users" -> "Manage" and test the "state" and "activated" filters
3. Go to "Users" -> "User notes" and test the "state" filter
4. Go to "Content" -> "Categories" and test the "access" and the "language" filter (the "All" value in particular).
5. Go to "Components" -> "Banners" -> "Banners" and test the "state" filter.
6. Go to "Components" -> "Banners" -> "Tracks" and test the "type", the "client" and "category" filter.
7. Go to "Components" -> "Contacts" -> "Contacts" and test the "access" and the "language" filter (the "All" value in particular).
8. Go to "Components" -> "Newsfeeds" -> "Newsfeeds" and test the "category id", "access" and the "language" filter (the "All" value in particular).
9. Go to "Extensions" -> "Modules" and test the "state" (the "All" value in particular) "language" filter (the "All" value in particular).
10. Go to "Extensions" -> "Plugins" and test the "status" filter.
11. Go to "Extensions" -> "Languages" -> "Content Languages" and test the "state" filter (the "All" value in particular).
12. Go to "Extensions" -> "Manage" -> "Manage" and test all the filters.

Now change the template to hathor and do the same tests.

Notes:
- In the tests above i only say to test the filters i corrected, but if you find more problems with filters please report.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@brianteeman please test this as it solves many issues with the filters.

**Comment by grhcj** [comment]
I have now tested all filters in isis, will continue in hathor now.
I don't understand the "All" filter options as we have the "- Select [...]" option, but there will be reasons for it :).

**Comment by andrepereiradasilva** [comment]
thanks

> I don't understand the "All" filter options as we have the "- Select [...] -" option, but there will be reasons for it :).

:smile: i think the "All" is because is the only way to show published, unpublished, archived and trashed in the same list. The `- Select [...] -` (primary view) doesn't show the archived and trashed ones.

**Comment by grhcj** [comment]
In hathor template, the view "Users" -> "Manage" has another search tools style than other views. Is this wanted behaviour?

**Comment by andrepereiradasilva** [comment]
> In hathor template, the view "Users" -> "Manage" has another search tools style than other views. Is this wanted behaviour?

That was like that before. I didn't change styles. just corrected the behaviour of the filters.

**Comment by grhcj** [comment]
ok, thanks for explanations.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 6df728ddca3cb0402177ca0867fad85df12c5192<br /><br />The inconsistencies I described above are not part of this pr.
I didn't find further problems with filters.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10042">issues.joomla.org/joomla-cms/10042</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@grhcj thanks for testing!

**Comment by infograf768** [comment]
@andrepereiradasilva 
Please, to ease testing, could you specify which Search Tools issues it solves in Isis only.

**Comment by andrepereiradasilva** [comment]
Hum. I think only this two:

> 2. Go to "Users" -> "User notes" and test the "state" filter
> 5. Go to "Components" -> "Banners" -> "Banners" and test the "state" filter.

but the propose of the test is also to validate that the changes made to work properly on hathor don't affect isis.

**Comment by infograf768** [comment]
Hmm, I don't see any error before patch for these 2 Status filters in Isis

**Comment by andrepereiradasilva** [comment]
To see the bug do this have an user note/banner with every state.

Log out and login and go there. Result:

image

In other words, is showing all states and should only show published and unpublished.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6df728ddca3cb0402177ca0867fad85df12c5192<br /><br />Users: Search OK but clicking on the Enabled icon in Hathor does not work (I guess for another PR).
For the rest, looks Ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10042">issues.joomla.org/joomla-cms/10042</a>.</sub>

**Comment by infograf768** [comment]
RTC, for 3.5.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10042">issues.joomla.org/joomla-cms/10042</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing @infograf768

**Pull request merged**
