### PR TITLE
[4.0] grammar corrections

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted these three english errors while working on something else.

code review

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 6defc64482ade16caccd9bee8e29d2d4fadb49ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31321">issues.joomla.org/tracker/joomla-cms/31321</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6defc64482ade16caccd9bee8e29d2d4fadb49ff<br /><br />Tested successfully in Beta6-dev of 6 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31321">issues.joomla.org/tracker/joomla-cms/31321</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31321">issues.joomla.org/tracker/joomla-cms/31321</a>.</sub>

**Comment by infograf768** [comment]
tks.

**Pull request merged**
