### PR TITLE
[4.0] API global language

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #26846

@wilsonge this will need to be added to the translation workflow etc

### CODE REVIEW

**Comment by wilsonge** [comment]
On phone so will test tomorrow but looks good at a glance. For the workflow I’ll raise internally. But can you please also drop it in https://github.com/joomla/joomla-cms/blob/4.0-dev/crowdin.yml as a directory like site and admin (even if just one file for now) so that crowdin automatically picks it up please

**Comment by brianteeman** [comment]
@wilsonge hope thats correct

**Comment by Bakual** [comment]
The Crowdin file looks fine to me. 👍

**Comment by wilsonge** [comment]
Merging this. For those coming in here please note there is a related issue here for ensuring all these files can be translated by packs https://github.com/joomla/joomla-cms/issues/27706

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
