### PR TITLE
[4.0] Deleting weblinks help as ini files have been deleted from 4.0

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says.

### Testing Instructions
Load `administrator/index.php?option=com_admin&view=help`

### Before patch
screen shot 2018-10-03 at 10 24 48

### After patch
screen shot 2018-10-03 at 10 28 45

### CODE REVIEW

**Comment by brianteeman** [comment]
Isn't this file supposed be generated from the script in the build folder and not edited directly?

**Comment by infograf768** [comment]
Not obvious. It could indeed be via helpTOC.php

Therefore, it would depend on the wiki help version which does not exist for 4.0, this could be the reason why weblinks is still proposed.

@mbabker @wilsonge 
If this is the case, I guess I can close this.

**Comment by wilsonge** [comment]
Yes this file should be generated from the script :)

**Comment by infograf768** [comment]
Hmm. I patched and then ran npm install and the file is NOT modified.
Therefore it seems that it does not depend on anything in build, as far as I could see.

**Comment by infograf768** [comment]
so, which script is it?

**Comment by brianteeman** [comment]
helpTOC.php in the build folder

**Comment by infograf768** [comment]
Read:
https://github.com/joomla/joomla-cms/pull/22474#issuecomment-426583113

**Comment by brianteeman** [comment]
why would that have anything to do with npm install

**Comment by brianteeman** [comment]
its is a standalone php script. it is how the helptoc has been built for a very long time ;)

**Comment by infograf768** [comment]
Therefore, as it can't be run, and I see no solution else for this issue, I am closing it.

**Comment by brianteeman** [comment]
of course it can be run

**Comment by infograf768** [comment]
If I run it then toc.son is empty. Therefore I guess https://github.com/joomla/joomla-cms/pull/22474#issuecomment-426581307 was correct.
No use for this PR.

**Pull request closed without merging**
