### PR TITLE
TYPO - Change Color to Colour as it is en-GB

### PR DESCRIPTION
**Pull request by MATsxm**
As `en-GB` is the official Joomla! Language, `color` must be changed to `colour` and then be consistent with all other uses.

Easy fix on review

### CODE REVIEW

**Comment by mbabker** [comment]
Honestly, I don't think a blanket "use colour for all places in the UI" rule is correct.  Unfortunately, when it comes to form fields, it's not that simple.  This is referring to a field which by the HTML specification is named "color" and all of the in-code references follow that pattern versus the en-GB preferred variant.

When it comes to specifying the color of something like some template options do, I think this type of change is fine.  But when it's referencing a specific field type which has a specific naming convention, IMO it might be better suited to follow that.

Says the guy from the now biggest laughing stock of a country on this planet.

**Comment by MATsxm** [comment]
AFAIR (can't remember exactly) we had the same discussion in a Tiny or JS language file end then the decison was made to follow the "colour" rule.
I will have to check "deeper" just to be sure to be consistent.

**Comment by ot2sen** [comment]
When it is in code use CSS or HTML standards, when visually presented to the user use en-GB (except when user need to enter a CSS or HTML value that need to be in that standard)

**Comment by mbabker** [comment]
In this case, it is referring to something that controls an HTML element with a specific identifier.  It is a `<input type="color" />` element so IMO the correct name for anything referring directly to that HTML element should use "Color" to remain consistent with technical specifications.  When referring to a color value of any type, colour or any other localised variant should be used.  In these examples, they have two vastly different contexts which I believe does call for evaluating which variant is the correct one to use versus applying a blanket "en-GB all the things" rule.

**Comment by infograf768** [comment]
See my comment here:
https://github.com/joomla/joomla-cms/pull/13659#issuecomment-274240958

**Comment by Bakual** [comment]
Imho, if the field types get translated, then it can be colour here as it will be "Farbe" in german and "couleur" in french. So it would not be tied to the HTML element name in translations and thus also doesn't have to be in english.
If we're not going to translate them, then it has to be color as it is a reference to the input element type.

**Comment by infograf768** [comment]
> If we're not going to translate them, then it has to be color as it is a reference to the input element type.

I am in favour of not translating the field types.

**Comment by infograf768** [comment]
I propose this:
https://github.com/joomla/joomla-cms/pull/13659#issuecomment-274253972

In that case we can use for example for this plugin
```ini
PLG_FIELDS_COLOR="Fields - Colour"
PLG_FIELDS_COLOR_LABEL="Colour (color)"
PLG_FIELDS_COLOR_XML_DESCRIPTION="This plugin lets create new fields of type 'color' in the extensions where custom fields are implemented."
```

**Comment by infograf768** [comment]
Please see and test https://github.com/joomla/joomla-cms/pull/13710

**Pull request closed without merging**
