### PR TITLE
[4.2] Media-infobar info z-index

### PR DESCRIPTION
**Pull request by brianteeman**
There is a z-index issue with the media manager when you enable the infobar.

To test you will need to have quite a lot of images in the folder. I just copied all the cassiopeia sample images a few times.

## Before
When scrolling in image mode the sticky toolbar is cropped partially - see video When scrolling in list mode the sticky toolbar is cropped a bit more - see video

https://user-images.githubusercontent.com/1296369/202034433-216bb9ed-0e4e-4376-a563-0e4f76af0877.mp4

## After
The entire toolbar is sticky and visible see video

https://user-images.githubusercontent.com/1296369/202034482-6add3c66-b31d-4ab7-9d07-d2d661aced4e.mp4

You will need to test with a prebuilt package OR after rebuilding the css

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 95d33bb8cf55c79fb8846c8a64ec6926018d58d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39222">issues.joomla.org/tracker/joomla-cms/39222</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 95d33bb8cf55c79fb8846c8a64ec6926018d58d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39222">issues.joomla.org/tracker/joomla-cms/39222</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39222">issues.joomla.org/tracker/joomla-cms/39222</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
