### PR TITLE
[5.1] Uninstall child of package

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #42596 .

### Summary of Changes
If you try to uninstall an extension that is a package you can't and get a message doesnt indicate what package.

This pr adds a new variable to the string so that there is now a direct link to the package

Because of our semver rules on language strings this is made against j5.1

### Testing Instructions
Install any package extension eg a language
Go to System => Manage => Extensions
Filter for languages and then try to uninstall one

### Actual result BEFORE applying this Pull Request
`The < named > extension is part of a [ package ] which does not allow individual extensions to be uninstalled.`

### Expected result AFTER applying this Pull Request
`The < named > extension is part of a [ package ]( index.php?option=com_installer&view=manage&filter[search]=id:XX) which does not allow individual extensions to be uninstalled.`

The link will directly open the package so it can be selected and uninstalled.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
After click on direct link in the message:

Untitled

After click on search-button the package is shown and can be uninstalled.

**Comment by brianteeman** [comment]
@fgsw Thanks for testing. I have updated the pr to resolve your issue

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on b0a0162bca0fa0c3b1cf85984d6d336c88744b86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42607">issues.joomla.org/tracker/joomla-cms/42607</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on b0a0162bca0fa0c3b1cf85984d6d336c88744b86<br /><br />Thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42607">issues.joomla.org/tracker/joomla-cms/42607</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42607">issues.joomla.org/tracker/joomla-cms/42607</a>.</sub>

**Review by rdeutz — APPROVED** [review]

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
