### PR TITLE
Update administrator.php

### PR DESCRIPTION
**Pull request by yoerin**
When input empty the system should use the default language. This did not seem to be the case in the code, the default lang should be used when getting the form post credentials

### CODE REVIEW

**Comment by infograf768** [comment]
Can you explain better with test instructions?

**Comment by yoerin** [comment]
We had/have an issue with the joomla backend that the default language is not used when logging in.

If you go to the login screen the default language (nl-NL) is shown but when loging in with the language select box unchanged (default language) the language is set to en-GB in some cases.

We discovered this when transfering a website to a new server. We have planed inspection of the server and further inspection for the input->get function(s) but the main issue was that the default language was not used.

**Comment by brianteeman** [comment]
Please define "in some cases" so that the bug can be replicated

On 3 November 2015 at 11:51, yoerin <notifications@github.com> wrote:

> We had/have an issue with the joomla backend that the default language is
> not used when logging in.
>
> If you go to the login screen the default language (nl-NL) is shown but
> when loging in with the language select box unchanged (default language)
> the language is set to en-GB in some cases.
>
> We discovered this when transfering a website to a new server. We have
> planed inspection of the server and further inspection for the input->get
> function(s) but the main issue was that the default language was not used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8257#issuecomment-153329320>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by yoerin** [comment]
In the cases where the website is transfered to our new server.

**Comment by brianteeman** [comment]
Sorry but that means it is impossible for anyone to test what the problem
is that you have.

We need a way to replicate the bug so that someone can confirm that your
proposal fixes it

On 3 November 2015 at 13:05, yoerin <notifications@github.com> wrote:

> In the cases where the website is transfered to our new server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8257#issuecomment-153346751>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Fedik** [comment]
I have site with default German and while login with unselected "chose language" I get German backend.
I cannot reproduce the issue.

@yoerin maybe there some plugin that change behavior on your site?

**Comment by yoerin** [comment]
Completely clean no plugin.
@brianteeman understandable that it cannot be reproduced but checking the code should show that if the input 'lang' is empty it should get en-GB when you do not change the language on the login form it will always be empty. So the check is faulty or the default value if empty is wrong.

I will check both servers what is different in feedback from the input->get and will report back (i have nog timeperiod in which i am able to test this)

**Comment by yoerin** [comment]
I have figured out the problem.

Suhosin was preventing submitting an ASCI-II null value which in place prevented from getting/setting an empty value.

For production this security is still in place but i haven't had the time to search furtur in the system to figure out where an empty value is recorded/transfered to ASCI-II nul value.

Any ideas?

The code in my last update is still viable to use, less 'hard coded' lang tags

**Comment by mbabker** [comment]
As is this is probably going to break language handling in the admin application because it is going to force the global JLanguage instance to be created in JFactory before the application has the chance to parse the input/configuration and figure out what's necessary before creating it at the right time.

The use of `$this->get()` in the application classes reads data from the configuration object, this is a separate data store from the input data accessed via `$this->input->get()`.

You're mixing various changes into this one item.  Your comments have indicated your issue relates to the handling of data in a specific server configuration.  As is, this pull request doesn't really address that and adds an undocumented class variable `_defaultLang` and instantiates the global JLanguage object in the application constructor with the en-GB language.  This will pretty much nullify anything that happens in the `initialiseApp()` method, especially when the default language matches the language actually being used (`JLanguage::getInstance()` only allows one instance to be created for a given language tag and debug flag combination).

**Comment by yoerin** [comment]
understood

**Comment by brianteeman** [comment]
Closing for the reasons stated above by @mbabker <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8257">issues.joomla.org/joomla-cms/8257</a>.</sub>

**Pull request closed without merging**
