### PR TITLE
Fix popover hidden behind modal header

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #15028.

### Summary of Changes
Change placement of popover from top to  bottom.

### Testing Instructions
Edit article.
Under Publishing tab, click blue button to Select User.
Hover mouser over a column header.

### Expected result
Popover to  be visible.

### Actual result
Popover partially hidden under modal header.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
@Quy 
We do have the same issue for all modals.
Can you enlarge your PR to include these?
```
diff --git a/administrator/components/com_categories/views/categories/tmpl/modal.php b/administrator/components/com_categories/views/categories/tmpl/modal.php
index 5c6dc12..027db8f 100644
--- a/administrator/components/com_categories/views/categories/tmpl/modal.php
+++ b/administrator/components/com_categories/views/categories/tmpl/modal.php
@@ -24,4 +24,5 @@
 JHtml::_('behavior.core');
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 
diff --git a/administrator/components/com_contact/views/contacts/tmpl/modal.php b/administrator/components/com_contact/views/contacts/tmpl/modal.php
index 0553535..52f5162 100644
--- a/administrator/components/com_contact/views/contacts/tmpl/modal.php
+++ b/administrator/components/com_contact/views/contacts/tmpl/modal.php
@@ -23,4 +23,6 @@
 JHtml::_('behavior.core');
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
+
 JHtml::_('formbehavior.chosen', 'select');
 JHtml::_('behavior.polyfill', array('event'), 'lt IE 9');
diff --git a/administrator/components/com_content/views/articles/tmpl/modal.php b/administrator/components/com_content/views/articles/tmpl/modal.php
index 87d90d7..c148e7f 100644
--- a/administrator/components/com_content/views/articles/tmpl/modal.php
+++ b/administrator/components/com_content/views/articles/tmpl/modal.php
@@ -26,4 +26,5 @@
 JHtml::_('script', 'com_content/admin-articles-modal.min.js', array('version' => 'auto', 'relative' => true));
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('behavior.multiselect');
 JHtml::_('formbehavior.chosen', '.multipleTags', null, array('placeholder_text_multiple' => JText::_('JOPTION_SELECT_TAG')));
diff --git a/administrator/components/com_fields/views/fields/tmpl/modal.php b/administrator/components/com_fields/views/fields/tmpl/modal.php
index 49d63ab..d2e551c 100644
--- a/administrator/components/com_fields/views/fields/tmpl/modal.php
+++ b/administrator/components/com_fields/views/fields/tmpl/modal.php
@@ -17,4 +17,5 @@
 JHtml::_('behavior.core');
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 JHtml::_('script', 'com_fields/admin-fields-modal.js', array('version' => 'auto', 'relative' => true));
diff --git a/administrator/components/com_menus/views/items/tmpl/modal.php b/administrator/components/com_menus/views/items/tmpl/modal.php
index 3d4a9ef..a7b12e9 100644
--- a/administrator/components/com_menus/views/items/tmpl/modal.php
+++ b/administrator/components/com_menus/views/items/tmpl/modal.php
@@ -23,4 +23,5 @@
 JHtml::_('script', 'com_menus/admin-items-modal.min.js', array('version' => 'auto', 'relative' => true));
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 
@@ -119,5 +120,5 @@
 							<?php else : ?>
 								<?php echo $this->escape($item->title); ?>
-							<?php endif; ?>	
+							<?php endif; ?>
 							<span class="small">
 								<?php if (empty($item->note)) : ?>
diff --git a/administrator/components/com_modules/views/modules/tmpl/modal.php b/administrator/components/com_modules/views/modules/tmpl/modal.php
index 8178467..dd60240 100644
--- a/administrator/components/com_modules/views/modules/tmpl/modal.php
+++ b/administrator/components/com_modules/views/modules/tmpl/modal.php
@@ -18,4 +18,5 @@
 JHtml::_('behavior.core');
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 
diff --git a/administrator/components/com_newsfeeds/views/newsfeeds/tmpl/modal.php b/administrator/components/com_newsfeeds/views/newsfeeds/tmpl/modal.php
index 10ab99a..7a695bf 100644
--- a/administrator/components/com_newsfeeds/views/newsfeeds/tmpl/modal.php
+++ b/administrator/components/com_newsfeeds/views/newsfeeds/tmpl/modal.php
@@ -16,4 +16,5 @@
 JHtml::_('behavior.core');
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 
diff --git a/administrator/components/com_users/views/users/tmpl/modal.php b/administrator/components/com_users/views/users/tmpl/modal.php
index 93ffdd2..e75112f 100644
--- a/administrator/components/com_users/views/users/tmpl/modal.php
+++ b/administrator/components/com_users/views/users/tmpl/modal.php
@@ -13,4 +13,5 @@
 
 JHtml::_('bootstrap.tooltip', '.hasTooltip', array('placement' => 'bottom'));
+JHtml::_('bootstrap.popover', '.hasPopover', array('placement' => 'bottom'));
 JHtml::_('formbehavior.chosen', 'select');
 JHtml::_('behavior.multiselect');
```

**Comment by ciar4n** [comment]
Presuming this PR moves the popover under rather that over, does that not mean the popover partially covers the table column it is explaining. The PR is still an improvement.. just not sure if it is ideal.

**Comment by infograf768** [comment]
Not under vs over but down vs up (up being the default).
Indeed it partially covers the column, but only when hovering the column title, which is OK imho as it is not partially hidden now.

**Comment by Quy** [comment]
@infograf768 Sure. Please tell me where these other modals are to see/test. If you can submit a PR to my branch, that would be appreciative. 👍

**Comment by Quy** [comment]
@infograf768 Done. Thank you!

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on afcea4d3c16f04c665231e3d7934fb2a2bf03cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18581">issues.joomla.org/tracker/joomla-cms/18581</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on afcea4d3c16f04c665231e3d7934fb2a2bf03cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18581">issues.joomla.org/tracker/joomla-cms/18581</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on afcea4d3c16f04c665231e3d7934fb2a2bf03cd3<br /><br />Successfully tested in 3.8.3-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18581">issues.joomla.org/tracker/joomla-cms/18581</a>.</sub>

**Pull request merged**
