### PR TITLE
[4.0] Check model is set before calling its methods

### PR DESCRIPTION
**Pull request by PhilETaylor**
Check model is set before calling its methods

simply moved the if block before calling methods 

Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9f4a8b4748ed5ba289d863bf5c9330b5643f10f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36378">issues.joomla.org/tracker/joomla-cms/36378</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 9f4a8b4748ed5ba289d863bf5c9330b5643f10f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36378">issues.joomla.org/tracker/joomla-cms/36378</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36378">issues.joomla.org/tracker/joomla-cms/36378</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
