### PR TITLE
Plugin skip-to enabled on backend AND frontend 

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
This PR activates the skip-to-plugin for both, backend and frontend during installation. 

### Testing Instructions
Make a fresh installation

### Actual result BEFORE applying this Pull Request
The skip-to-plugin is activated only for backend

### Expected result AFTER applying this Pull Request
The skip-to-plugin is activated for both, backend and frontend

### Documentation Changes Required
don't know

### CODE REVIEW

**Comment by brianteeman** [comment]
It was a deliberate decision not to enable it by default on the frontend as it could conflict with a template that already implements a form of skip link

**Comment by brianteeman** [comment]
and of course if you want to do this then this needs to be updated as well

https://github.com/joomla/joomla-cms/blob/32f1fff830ec2483fb5c0d4e6b495282b6c8158e/plugins/system/skipto/skipto.xml#L26

**Comment by chmst** [comment]
@brianteeman I remember now the discussion and decision - had completely forgotten.

**Comment by brianteeman** [comment]
You could add it to the sample data if you wanted

**Pull request closed without merging**
