### PR TITLE
[4.0] fix phpcs in the StatsHelper.php

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Fix phpcs issue in the StatsHelper.php

### Testing Instructions

review

### Expected result

drone is fine

### Actual result

drone is not fine

### Documentation Changes Required

cc @wilsonge @rdeutz

### CODE REVIEW

**Comment by infograf768** [comment]
?? https://github.com/joomla/joomla-cms/pull/21849

**Comment by infograf768** [comment]
as far I could see in #21849, there is another cs issue

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/pull/21849/files

**Comment by zero-24** [comment]
Sorry @infograf768 I have not noticed your PR before. On testing my rips things i have noticed this issue and fixed it. I have just fixed the other two issues here: https://github.com/joomla/joomla-cms/commit/bd93bb0a87a9ac5b94b554c695e6cbaacdf0f002

**Pull request merged**
