### PR TITLE
[4.0] Delete unused parameters and Language Strings

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
I deleted the parameter options in from the XML files for menu items. If I am right, this parameter has no task at the moment.

I think that parameters, options and language strings should only be add if we use them and I think that unnecessary program code is not good for a software. In my opinion, it unsettles newbies if they want to learn using core extensions.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by SharkyKZ** [comment]
These are used in component layout field.

**Comment by astridx** [comment]
@SharkyKZ Maybe I'm not looking right. But I can not find a place where these are used. Can you show me one example please?

**Comment by SharkyKZ** [comment]
https://github.com/joomla/joomla-cms/blob/5638552f721cf28f27f67e6a6e4a8ffd7c66d274/libraries/src/Form/Field/ComponentlayoutField.php#L183

**Comment by brianteeman** [comment]
But is it being used?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27971">issues.joomla.org/tracker/joomla-cms/27971</a>.</sub>

**Comment by brianteeman** [comment]
Finally worked it out - I think

image

image

**Comment by astridx** [comment]
@SharkyKZ Thank you showing the place.
@brianteeman Thank you for checking and thinking along with me.

I honestly admit that I found the use only through SharkyKZ. Before, I only looked in the component menu. After posting the use in the code, however, I still think this is unnecessary. With my changes, the `title` is used instead of the `option`. For me, the `title` is clearer than `Default`. And mostly `options` and `title` are the same anyway.

Screenshot from 2020 02 24 18 58 53
Screenshot from 2020 02 24 19 00 40


I would not change the layout file https://github.com/joomla/joomla-cms/blob/5638552f721cf28f27f67e6a6e4a8ffd7c66d274/libraries/src/Form/Field/ComponentlayoutField.php#L183 because the `option` may be used by Third Party Extensions.

I leave the PR open for a few more days. If no one answers, I close it. Then I assume that I am the only one who likes the deletion.

**Comment by brianteeman** [comment]
have to agree that the title is more meaningful

**Comment by SharkyKZ** [comment]
The point here is to show the unique name of the layout, not the name of the view. It does not make sense to show "Single Contact" for default contact layout because every layout for the contact view fits the description.

**Comment by astridx** [comment]
Now I have an explanation. Thank you @SharkyKZ

**Pull request closed without merging**
