### PR TITLE
[4.0][com_installer] Refactor using new Toolbar

### PR DESCRIPTION
**Pull request by Quy**
See PR #19670.

### Summary of Changes
Refactor to use new Toolbar.

### Testing Instructions
Go to System > Manage > Extensions
Test buttons to ensure performing correctly.
View page source to see buttons markup same as before PR.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c1e2e1dd79754056327bfe10a3ef2370457ed3bc<br /><br />It was not obvious what to look for - certainly nothing changed in the page. Watched the code change in Eclipse with apply/remove patch - understood. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30063">issues.joomla.org/tracker/joomla-cms/30063</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c1e2e1dd79754056327bfe10a3ef2370457ed3bc<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30063">issues.joomla.org/tracker/joomla-cms/30063</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30063">issues.joomla.org/tracker/joomla-cms/30063</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
