### PR TITLE
[4.0] Unused file

### PR DESCRIPTION
**Pull request by brianteeman**
afaict this file stopped being used in 2013 when the reference to loadTemplate('options') was removed by @regularlabs  with this commit 7a9822cd1ab9445a5db7f5a12c577e0b4809f1cf

assuming i am correct then it would be a good idea to stop maintaining a ghost file

Note: There may be more

### CODE REVIEW

**Comment by wilsonge** [comment]
Yup we kept it at the time because of the b/c of people running admin templates

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks. Another pr will follow to remove a lot of similar files.

**Comment by brianteeman** [comment]
to avoid conflicts I will make the other changes in the template repo

**Pull request merged**
