### PR TITLE
[4.1] remove spaces at EOL

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

remove spaces/tabs at the end of the line

### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de78957b3a0290a56c876ec7bba5dd24d8067828<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38086">issues.joomla.org/tracker/joomla-cms/38086</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de78957b3a0290a56c876ec7bba5dd24d8067828<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38086">issues.joomla.org/tracker/joomla-cms/38086</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38086">issues.joomla.org/tracker/joomla-cms/38086</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
