### PR TITLE
CodeMirror updated to 5.5

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
There doesn't appear to be much in this update that directly affects Joomla users, just keeping up-to-date.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Wait a second, something is amiss.

**Comment by okonomiyaki3000** [comment]
OK, that's more like it

**Comment by okonomiyaki3000** [comment]
5.5 now. Includes 5 new themes

**Comment by brianteeman** [comment]
Tested and everything still seems to work as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7284">issues.joomla.org/joomla-cms/7284</a>.</sub>

**Comment by zero-24** [comment]
Works great :smile: Thanks --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7284">issues.joomla.org/joomla-cms/7284</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @okonomiyaki3000! Merged.

**Pull request merged**
