### PR TITLE
[4.0] Cleanup build files that have been removed

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Removes various files from exclusion files that no longer exist in the top level of the repo (they've either been removed or moved to the build subfolder)

### Testing Instructions
Code Review

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9834d5f985b522cbe6a820639b6c82a84fa18742<br /><br />Code review: I can confirm that the files have been removed or moved to the build folder where they are already ignored and not packed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31833">issues.joomla.org/tracker/joomla-cms/31833</a>.</sub>

**Comment by adj9** [comment]
Apply PR with Joomla! Patch Tester and there isn't file to modify.
@richard67 have you install J! with PR integrated?

**Comment by richard67** [comment]
@adj9 This PR can't be applied with patchtester on a "normal" Joomla installation made with an installation package, because it handles files in the build and the tests folders. Those folders are only available on a Git clone of the 4.0-dev branch.

Update: The same applies to the installation package built for this PR. It needs a git clone for testing it. Anyway it can be tested only by code review by a reviewer who is familiar with the J4 build process.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9834d5f985b522cbe6a820639b6c82a84fa18742<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31833">issues.joomla.org/tracker/joomla-cms/31833</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31833">issues.joomla.org/tracker/joomla-cms/31833</a>.</sub>

**Comment by HLeithner** [comment]
Thnaks

**Pull request merged**
