### PR TITLE
[5.0] Remove deprecated string COM_MEDIA_OPEN_ITEM_ACTIONS

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

remove two strings and one line

### Actual result BEFORE applying this Pull Request

```
COM_MEDIA_NOT_SET="Not Set"
; The string COM_MEDIA_OPEN_ITEM_ACTIONS is deprecated and no longer in use as of 4.2.4
; Please use the string COM_MEDIA_MANAGE_ITEM (with the file name) instead.
COM_MEDIA_OPEN_ITEM_ACTIONS="Open item actions"
COM_MEDIA_ORDER_ASC="Ascending"
```

### Expected result AFTER applying this Pull Request

```
COM_MEDIA_NOT_SET="Not Set"
COM_MEDIA_ORDER_ASC="Ascending"
```

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2d616642030cf4f50930c0eed8d986791f315e96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41736">issues.joomla.org/tracker/joomla-cms/41736</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2d616642030cf4f50930c0eed8d986791f315e96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41736">issues.joomla.org/tracker/joomla-cms/41736</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41736">issues.joomla.org/tracker/joomla-cms/41736</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
