### PR TITLE
[4.2.6] Email cloaking fails.

### PR DESCRIPTION
**Pull request by LukasHH**
Pull Request for Issue #39422 .

### Summary of Changes
a) modification of the last pattern
b) added more patterns

### Testing Instructions
create article with

for the last pattern:
```
<img class="img-thumbnail" style="border: 1px solid #00f;" title="email@example.org" src="/www/j4test/images/joomla_black.png" alt="" />
<input type="text" placeholder="email@example.org" />
```

for the new pattern (email as plain text within html-attributes):
```
<a class="btn btn-danger" style="border: 2px solid #f00;" title="email@example.org" href="#">email</a>
<a title="email@example.org" href="#">email</a>
<ul>
<li title="email-1@example.org">email 1</li>
<li title="email-2@example.org">email 2</li>
</ul>
```

for the new last pattern (email as plain text but not within HTML tags):
```
<span>email--1@example.org</span>
<ul>
<li>email-0@example.org</li>
<li>email-1@example.org</li>
</ul>
```

### Actual result BEFORE applying this Pull Request
a) the pattern was too hungry
b) emails as plain text within html-attributes and not within html-tags was not cloaked

### Expected result AFTER applying this Pull Request
a) the pattern was not too hungry
b) emails as plain text within html-attributes and not within html-tags was cloaked

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on c29f7b093c129d0499aa1e63d4f5b6801ac21609<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39508">issues.joomla.org/tracker/joomla-cms/39508</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cec7414f37aa011afd2d28810e33fa8cc447b38f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39508">issues.joomla.org/tracker/joomla-cms/39508</a>.</sub>

**Comment by richard67** [comment]
I've restored @ReLater 's test result since the 2 commits after that were just clean branch updates.

@LukasHH Please avoid unnecessary branch updates because they invalidate the human tests counter and so make it harder for us to find pull requests which should be set to ready to commit (RTC) when they have 2 successful human tests.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39508">issues.joomla.org/tracker/joomla-cms/39508</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
