### PR TITLE
[com_fields] Fix for cropped 'Show User Custom Field'

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #13594 .

### Summary of Changes
Stop 'Show User Custom Field' value from been cropped

### Testing Instructions
Apply patch and navigate to #Contacts: Edit' -> Tab 'Display' -> Field "Show User Custom Field" Text.

Check input value is not cropped (see #13594)

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on cc8f1bad0ce71028009ab8bfbe8523ee8245e570<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on cc8f1bad0ce71028009ab8bfbe8523ee8245e570<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by ciar4n** [comment]
@franz-wohlkoenig Which browsers are you still having this issue?

**Comment by franz-wohlkoenig** [comment]
@ciar4n Firefox 52.0 (64-bit)

**Comment by ciar4n** [comment]
Strange.. unable to replicate this. Cleared cache and all that?

**Comment by franz-wohlkoenig** [comment]
Cache cleared, PR de- and reapplied. See 13 Letter more.

**Comment by tuts-22** [comment]
Can anyone help me here I am not able to apply the patch...
It shows the error:
The file marked for modification does not exist: administrator/templates/isis/less/blocks/_chzn-override.less

**Comment by zero-24** [comment]
@tuts-22 please update to the lst staging and try again. 😄

**Comment by tuts-22** [comment]
@zero-24 Thanks !!

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on cc8f1bad0ce71028009ab8bfbe8523ee8245e570<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by ciar4n** [comment]
Thank you for testing

@bertmert Could you check if the following is been used.. https://github.com/joomla/joomla-cms/pull/14566/files#diff-64f4e3e067e83c49f7625640e410736fR7032


cropped

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cc8f1bad0ce71028009ab8bfbe8523ee8245e570<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by ciar4n** [comment]
Conflicts fixed

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 0e0722f64128ebbde006032621fe1f636274d952<br /><br />Does not work on Firefox.

To get it to work, I had to add width:100% !important; in the <li

to

.chzn-container-multi .chzn-choices li.search-field {
    margin: 0;
    padding: 0;
    white-space: nowrap;
    width: 100% !important;
}



rather than in 

.control-group .chzn-container .chzn-choices .search-field input {
    width: 100% !important;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @infograf768 

Admittedly I am unable to replicate this issue in FF however I have added the parent li as suggested.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a9939203d87dcdde2e379d3cbc4d06659fad4c82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a9939203d87dcdde2e379d3cbc4d06659fad4c82<br /><br />Works fine now. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14566">issues.joomla.org/tracker/joomla-cms/14566</a>.</sub>

**Pull request merged**
