### PR TITLE
Move JSearchHelper to namespace

### PR DESCRIPTION
**Pull request by laoneo**
Move JSearchHelper to namespace. I'v also cleaned up some code in the search helper class, to make it more readable.

### CODE REVIEW

**Comment by wilsonge** [comment]
Can we do the code cleanup separately to the namespacing please? Because github now doesn't recognise this as a file move - plus it's much harder for me to review

**Comment by laoneo** [comment]
Reverted

**Comment by wilsonge** [comment]
Thankyou - sorry to be a pain about it!

**Comment by laoneo** [comment]
No problem, better to stay on the safe side :-)

**Pull request merged**
