### PR TITLE
Update nl-NL.ini

### PR DESCRIPTION
**Pull request by webmasterab**
Small adjustment

### CODE REVIEW

**Comment by infograf768** [comment]
@marijkestuivenberg  
Please check all is OK

**Comment by webmasterab** [comment]
@ infograf768 You mean the translation team should look at it, if I need the whole file, please?

**Comment by Bakual** [comment]
@webmasterab Yes, the translation team (in this case Marijke) has to approve it as those files are provided by the translators.
Best is usually to directly contact them instead of creating a PR.

**Comment by marijkestuivenberg** [comment]
Check, all is OK. Thanks for the correction and the heads up.

**Comment by Bakual** [comment]
Merged.
@marijkestuivenberg Make sure to make the change in your copy as well :smile:

**Comment by marijkestuivenberg** [comment]
Already done ;)

**Pull request merged**
