### PR TITLE
[4.4] Fix event target in menu.js

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
The core menu.js dynamically adds `aria-hidden=true` attributes to `ul` tags on menu level 2:

Bildschirmfoto 2024-09-04 um 10 54 57

However, on focus and hover, these attributes aren't always set to "false" (which would be correct as the previously invisible dropdown now is possible) as the JS has a bug. It uses the `target` attribute of the event, which is not the element that the eventhandler was bound to (=the parent `<li>`) but the element that triggered the event, i.e. a nested a or span tag.

It should use currentTarget.

See msdn:
https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

### Testing Instructions
Create a test site with a multi-level menu that uses the "default" menu layout. Make sure that the menu.js is loaded and the aria-hidden attribute is appended. Now hover over the element.

### Actual result BEFORE applying this Pull Request
aria-hidden isn't updated reliably.

### Expected result AFTER applying this Pull Request
aria-hidden is updated reliably.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 1dc9365bcab11528ba473ba96d89525227e05836<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44019">issues.joomla.org/tracker/joomla-cms/44019</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1dc9365bcab11528ba473ba96d89525227e05836<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44019">issues.joomla.org/tracker/joomla-cms/44019</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44019">issues.joomla.org/tracker/joomla-cms/44019</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
