### PR TITLE
[4.0] Language factory

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue comment https://github.com/joomla/joomla-cms/issues/21289#issuecomment-411245740.

### Summary of Changes
Introduces a language factory.

Question which comes up here is if the factory needs to do some caching? Because every createLanguage call in the factory actually loads the languages from scratch.

### Testing Instructions
Browse around in the back end.

### Expected result
All is working.

### Actual result
All is working.

### Documentation Changes Required
Similar as the rest of the factory and service provider classes.

### CODE REVIEW

**Comment by mbabker** [comment]
> Question which comes up here is if the factory needs to do some caching? Because every createLanguage call in the factory actually loads the languages from scratch.

You're going to need some kind of caching support, probably will need a factory that supports singleton storage.

This is a case of the `getInstance` method having more business logic than just creating a singleton of a class instance.  In this case, it creates singletons for each language.  And because the `Language` class is environmentally aware (i.e. each instance has its own record of loaded translations), this isn't something that is just easily phased out.

The `Language` class absolutely should not be aware of or care about this singleton storage.  But, as an overall application, the CMS absolutely does care about it.

**Comment by laoneo** [comment]
> probably will need a factory that supports singleton storage

You mean basically the logic which is now in Language::getInstance?

**Comment by mbabker** [comment]
Right.

**Comment by ceus1984** [comment]
I have tested this item :white_check_mark: successfully on 556f0159f0286f80b0a45f41607671a061fa267e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21768">issues.joomla.org/tracker/joomla-cms/21768</a>.</sub>

**Comment by ThomasFried** [comment]
I have tested this item :white_check_mark: successfully on 556f0159f0286f80b0a45f41607671a061fa267e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21768">issues.joomla.org/tracker/joomla-cms/21768</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by gorgonz** [comment]
I have tested this item :white_check_mark: successfully on 556f0159f0286f80b0a45f41607671a061fa267e<br /><br />I played around for some time, but this is not "covering" all possibilities ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21768">issues.joomla.org/tracker/joomla-cms/21768</a>.</sub>

**Pull request merged**
