### PR TITLE
Solution for the issue : Validation message for repeatable-table layout of sub-form getting blank #27888

### PR DESCRIPTION
**Pull request by manav014**
Pull Request for Issue #27888

### Summary of Changes
changed the error message in the file administrator/language/en-GB/en-GB.ini

### Testing Instructions
Login to administrator
Goto Email Domain Options of user config and add domain.
Domain name is a required field.
Save domain name with a blank value.

### Expected result
in spite of displaying just Error it will give complete error message that the field is required

### Actual result
in spite of displaying just Error it will give complete error message that the field is required

### Documentation Changes Required
No

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This won't do. This string must not be changed.

The issue is to do with fields in subform not having any rendered labels. `validate.js` has nothing to display.

**Comment by brianteeman** [comment]
You have also committed over 200 unrelated files.

**Comment by manav014** [comment]
> You have also committed over 200 unrelated files.

Sorry for that, actually this was my first commit so did this by mistake.

**Comment by manav014** [comment]
> This won't do. This string must not be changed.
> 
> The issue is to do with fields in subform not having any rendered labels. `validate.js` has nothing to display.

yes got what's wrong.Thanks a lot for help.

**Pull request closed without merging**
