### PR TITLE
[4.3] Missing Text

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40517 .

### Summary of Changes
@laoneo](https://github.com/laoneo) removed this use statement with [#39624](https://github.com/joomla/joomla-cms/pull/39624). I assuming it was in error

### Testing Instructions
see #40517

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Actually the correct solution is to change line 87 from 
`$_errorMessage = Text::_('JLIB_LOGIN_DENIED');`
to
`$_errorMessage =  $this->getApplication()->getLanguage()->_('JLIB_LOGIN_DENIED');`

**Comment by sandewt** [comment]
https://github.com/joomla/joomla-cms/blob/fbf279092c2b05ade36af5f3567908c9ca829670/plugins/authentication/joomla/src/Extension/Joomla.php#L87

I think this was the intention: 

`$response->error_message = $this->getApplication()->getLanguage()->_('JLIB_LOGIN_DENIED');`

This can then expire again:
~`use Joomla\CMS\Language\Text;`~

**Comment by laoneo** [comment]
Tanks @brianteeman  for the fast pr. Can you change the pr to the proposal from @dgrammatiko?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f1fe0570d40997c71ffb4124ca7bb2a97a515d8<br /><br />To reproduce the error I had to switch the site to offline in addition to what's described in issue #40517 .

See also https://github.com/joomla/joomla-cms/issues/40517#issuecomment-1529792557 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40518">issues.joomla.org/tracker/joomla-cms/40518</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 7f1fe0570d40997c71ffb4124ca7bb2a97a515d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40518">issues.joomla.org/tracker/joomla-cms/40518</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40518">issues.joomla.org/tracker/joomla-cms/40518</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks brianteeman

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
