### PR TITLE
To solve the redirection to login issue if the session has expired.

### PR DESCRIPTION
**Pull request by Ntrv3390**
Pull Request for Issue # .
This will solve the issue of error that occured when the session of user expired and throwed an error that "you are not admin" instead of redirecting to login page.

Expected results after applying this #
Whenever the session of user will expire it will automatically redirected to login instead of letting him upload things and getting errors.

### CODE REVIEW

**Comment by alikon** [comment]
pull request for issue  #39847

**Comment by brianteeman** [comment]
i am not seeing any change in behaviour with this pr

**Comment by joomdonation** [comment]
This is a wrong approach. I don't have experience with our media manager client code (javascript) but I think somehow, the client code needs to detect user login status and handle the redirection itself. You should never make the redirection from the library code like how you are doing at the moment. Maybe @dgrammatiko could come up with some idea?

**Comment by gillesforli** [comment]
i do a plugin for this problem 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39884">issues.joomla.org/tracker/joomla-cms/39884</a>.</sub>

**Pull request closed without merging**
