### PR TITLE
[3.8.3] Support for multiple downloadurl tags in update stream

### PR DESCRIPTION
**Pull request by Septdir**
Pull Request for Issue #18543 .

### Summary of Changes
This implements be possible to define multiple <downloadurl> tags for an element's <downloads> in an update server definition.

### Testing Instructions
# Do NOT do this on a production site! This is for testing only!
#### Joomla Update
* install 3.8.2
* apply this patch
* set this update server: `https://joomla.septdir.ru/updateserver/list.xml`
* I propose a fake update to 3.8.3
* the update should fail as the primary download url is not available
* joomla will take turns trying to download the update files until it downloads the available
* joomla will report a successful update

### Extensions Update
* install 3.8.2
* apply this patch
* [Download test plugin](https://joomla.septdir.ru/updateserver/plg_system_test_1.0.0.zip)
* I propose a fake update to 1.1.0
* joomla will take turns trying to download the update files until it downloads the available
* joomla will report a successful update

### Expected result
Joomla can be updated from other download url

### Technical Details
On the update server part we need to define the fallback like this:
#### Joomla Update
```
<?xml version="1.0" ?>
<updates>
	<update>
		<name>Joomla! 3.8</name>
		<description>Joomla! 3.8 CMS</description>
		<element>joomla</element>
		<type>file</type>
		<version>3.8.3</version>
		<infourl title="Joomla!">https://www.joomla.org/announcements/release-news/5716-joomla-3-8-2-release.html
		</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://downloads.joomla.org/fail.zip</downloadurl>
			<downloadurl type="full" format="zip">https://downloads.joomla.org/cms/joomla3/3-8-2/Joomla_3.8.2-Stable-Update_Package.zip</downloadurl>
			<downloadurl type="full" format="zip">https://github.com/joomla/joomla-cms/releases/download/3.8.2/Joomla_3.8.2-Stable-Update_Package.zip</downloadurl>
			<downloadurl type="full" format="zip">https://downloads.joomla.org/fail2.zip</downloadurl>
			<downloadurl type="full" format="zip">https://downloads.joomla.org/fail3.zip</downloadurl>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<maintainer>Joomla! PLT</maintainer>
		<maintainerurl>https://www.joomla.org</maintainerurl>
		<section>STS</section>
		<targetplatform name="joomla" version="3.[78]"/>
		<php_minimum>5.3.10</php_minimum>
	</update>
</updates>
```

### Extensions Update
```
<updates>
	<update>
		<name>Test Plguin</name>
		<description>Плагин для тестов</description>
		<element>test</element>
		<type>plugin</type>
		<folder>system</folder>
		<client>0</client>
		<version>1.1.0</version>
		<infourl title="Test Plguin">
			https://joomla.septdir.ru/updateserver/plugin.xml
		</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://joomla.septdir.ru/updateserver/fail.zip</downloadurl>
			<downloadurl type="full" format="zip">https://joomla.septdir.ru/updateserver/plg_system_test_1.0.0.zip</downloadurl>
			<downloadurl type="full" format="zip">https://joomla.septdir.ru/updateserver/fail2.zip</downloadurl>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<maintainer></maintainer>
		<maintainerurl></maintainerurl>
		<targetplatform name="joomla" version="3.[0,1,2,3,4,5,6,7,8,9]"/>
	</update>
</updates>
```

### CODE REVIEW

**Comment by mbabker** [comment]
So far of the three proposals I think this is the one that is making the most sense as far as code goes.

It does need one additional update though.  `com_installer` should also be aware of the new mirrors so that extensions can also make use of this feature.

**Comment by Septdir** [comment]
@mbabker done!

**Comment by pavluk** [comment]
A good solution, I hope to soon appear in Joomla

**Comment by pavluk** [comment]
I have tested this item :white_check_mark: successfully on 48df199a40560c8746cd6bcc83cd5746b3f5a977<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18547">issues.joomla.org/tracker/joomla-cms/18547</a>.</sub>

**Comment by Septdir** [comment]
I have tested this item :white_check_mark: successfully on 48df199a40560c8746cd6bcc83cd5746b3f5a977<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18547">issues.joomla.org/tracker/joomla-cms/18547</a>.</sub>

**Comment by ghost** [comment]
@Septdir you can't test your own Pull Request as its expected you test it before create it on Github.

**Comment by Septdir** [comment]
@franz-wohlkoenig I understand you and more so I will not.

Of course I tested before I did PR. Just got the impression that this PR is not needed. I saw that in some PR the author puts a mark of testing.

**Comment by ghost** [comment]
> I saw that in some PR the author puts a mark of testing.

If i see i will remember them also.

**Comment by nihaha** [comment]
I have tested this item :white_check_mark: successfully on 48df199a40560c8746cd6bcc83cd5746b3f5a977<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18547">issues.joomla.org/tracker/joomla-cms/18547</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

Thanks for Tests.

**Pull request closed without merging**
