### PR TITLE
[4.0] Blog-View: Vote-Stars need padding, move the div tag

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for Issue #33164.

### Summary of Changes

Move the div tag

### Testing Instructions

* Install "Blog Sample Data",
* Enable vote-plugin having position Top or Bottom,
* Enable in article options view vote,
* View menu Blog.

### Actual result BEFORE applying this Pull Request

issue_before

### Expected result AFTER applying this Pull Request

issue_after

### Documentation Changes Required

* Does not apply

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d7e4fb2267c88e0dd9e1ba7bdbf06394b0d93aba<br /><br />@sandewt Thank you for creating the pr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33426">issues.joomla.org/tracker/joomla-cms/33426</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on d7e4fb2267c88e0dd9e1ba7bdbf06394b0d93aba<br /><br />Works perfectly for all configurations:
- Position: Top and Bottom
- Show Number of Votes: Yes and No<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33426">issues.joomla.org/tracker/joomla-cms/33426</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33426">issues.joomla.org/tracker/joomla-cms/33426</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by sandewt** [comment]
Thanks all.

**Pull request merged**
