### PR TITLE
Issue #15554 Wrong updateSize calculation in cache library

### PR DESCRIPTION
**Pull request by oe1tkt**
Pull Request for Issue #15554 .

### Summary of Changes
removed the odd calculation line in the helper file

         $this->size = number_format((float) $this->size + (float) $size, 2, JText::_('DECIMALS_SEPARATOR'), JText::_('THOUSANDS_SEPARATOR'));

which is:

1.  A formatting string within a calculation
2.  Language dependent
3.  Incorrect in en-GB when size is > 1 MB, because of the THOUSANDS_SEPARATOR 

and several files with a division through 1024, resulting in floating calculation

### Testing Instructions

1.  Run a website with caching enabled
2.  Backend > Clear Cache, do only list the cached directories
3.  Either install German language for backend or use a huge site with cache sizes > 1MB 
   Believe it or not, I tested this on a site with about 3164 articles, 1530 menus, 6 languages i.e. en-US, de-DE, fr-FR, zh-CN, zh-TW, and ja-JP, 13654 users registered.
4.  Set error reporting to a maximum
5.  Set cache time to 150 or so (just to keep cached entries long enough for tests and checks
6.  Try to make traffic on the site to generate as much cache as possible
7.  Go to "System > Cache leeren" (= Clear/Purge cache).
=> Same warnings like described in Issue #15554
8.  Compare the shown cache size with the associated directory on your file system, e.g. 

     Cache Group **0**    Size  **477.86 kB**

     File System: [..]/cache/0

### Expected result

1.  Sum of files should be the same size as displayed.
2.  No Warnings

### Actual result

1.  Sum of files are different in size when the size is > 1MB or if backend language is e.g. de-DE
2.  Notices are shown, like:
    Notice: A non well formed numeric value encountered in /administrator/components/com_cache/views/cache/tmpl/default.php on line 70
    759,00 kB

    Notice: A non well formed numeric value encountered in /www/htdocs/w00f7959/relaunch-bs3.ghsvs.de/administrator/components/com_cache/views/cache/tmpl/default.php on line 70
    24,00 kB

### Documentation Changes Required
Any other files who uses this updateSize function, this is e.g. virtuemart extension will show
factor 1024 too less cache size for now; i.e. vmfile.php -> changes to:
     
     //$item->updateSize(filesize($path . '/' . $folder . '/' . $file) / 1024);
     $item->updateSize(filesize($path . '/' . $folder . '/' . $file));
      
Please test patch and any feedback welcome! 😄

PS. I have rewritten the test instructions to make it even clearer. (2017-05-12 20:17 UTC) thanks to you @bertmert

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on fc48eef1357611b2e4c30ffbdb3ca050d26cfe7d<br /><br />Solved my issue  #15554 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15964">issues.joomla.org/tracker/joomla-cms/15964</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
On a clean 3.7.1-dev got without PR no Warnings and similar Size in Folders and Cache Groups.

**Comment by franz-wohlkoenig** [comment]
@bertmert Backend Lang.: English, no Difference if Error-Reporting set on "Developement" or "Maximum".

**Comment by bertmert** [comment]
Try German. The error (if still exists) becomes earlier  obvious then.

**Comment by bertmert** [comment]
@franz-wohlkoenig 
I've tested now also with current Staging. The error still exists without patch.
- Install German language.
- Set backend language to German (Client: Administrator).
- Set error reporting to maximum in Joomla configuration.
- Activate Cache in configuration and cache plugin (just to collect enough "stuff").
- Set Cache time to 150 or so (just to keep cached entries long enough for tests and checks.
- Clicki-di-click around in frontend to get enough "stuff" in cache.
- Go to "System > Cache leeren" (= Clear/Purge cache).
=> Same warnings like described in Issue #15554
=> Wrong sizes like described by @oe1tkt (e.g. mod_menu 170 kByte or so instead of measured ~3MB).

- Applied patch: All fine.

**Comment by franz-wohlkoenig** [comment]
Using Instructions above got without Warning:
bildschirmfoto 2017-05-12 um 16 42 01
bildschirmfoto 2017-05-12 um 16 42 32

**Comment by oe1tkt** [comment]
@franz-wohlkoenig Please be so friendly and test again with more cache or in the backend language German.

**Comment by franz-wohlkoenig** [comment]
@oe1tkt Backend Language was set on German (you see in first [Screenshot](https://github.com/joomla/joomla-cms/pull/15964#issuecomment-301096493) Table-Heads in German).

**Comment by oe1tkt** [comment]
@franz-wohlkoenig As you see com_content has in real 51kB and shown 44kB, i.e. because german comma is a , - so it ignores the numbers after that comma. Or at your mod_menu, it shows 15kB instead of 26kB. But when you create much more cache e.g. > 1 MB per item, you will see extremly strange amounts. I have no access from home to my webserver, so I will post some examples on Monday, 2017-05-15 with cache sizes mod_menu  > 200 MB creating the warnings and showing the failure.

**Comment by franz-wohlkoenig** [comment]
@oe1tkt missed your Answer – will test Today.

**Comment by franz-wohlkoenig** [comment]
@oe1tkt without PR Cache-Size is after "Comma" always ",00" (463,00), with PR they are like "463,69".

Didn't get Warnings so i cannot test PR succesfully.

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on fc48eef1357611b2e4c30ffbdb3ca050d26cfe7d<br /><br />I didn't managed to get the notice but the cache size is wrong, easy to demonstrate when you toggle the back-end in various languages (English, German, French), the patch fix it. Extensions relying on updateSize are anyway suffering from the language formatting. 
I'm posting results below.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15964">issues.joomla.org/tracker/joomla-cms/15964</a>.</sub>

**Comment by jsubri** [comment]
**Before the patch English & German (or French)**
15964-before-english

15964-before-german

**After the patch English & German (or French)**
15964-after-english

15964-after-german

**On disk**
15964-ondisk

**Comment by brianteeman** [comment]
> Extensions relying on updateSize are anyway suffering from the language formatting.

I cant see how a presumably they are accessing the size directly and not with formatting

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
