### PR TITLE
Remove false param on fetching form data

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #13231, #13218

### Summary of Changes

For some odd reason that I don't care to debug at this point instructing the user registration model to load a registration form without data cause the form structure to be completely busted and not correctly respect the structure changes made by the profile plugin in `onContentPrepareForm`.  Loading it with data makes it work right.  So, accept this hack.

### Testing Instructions

User registration works correctly, the profile plugin definitions are respected.

### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by infograf768** [comment]
we have a cs issue for Travis although it does not concern this PR.

**Comment by zero-24** [comment]
@mbabker i have updated your branch as the CS fix should be fixed by https://github.com/joomla/joomla-cms/pull/13255

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c2ee75343e1325b7d753d41c456b9bac7e713ac0<br /><br />this corrects the display of the profile ´required' fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13254">issues.joomla.org/tracker/joomla-cms/13254</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on c2ee75343e1325b7d753d41c456b9bac7e713ac0<br /><br />Works for me like a charm <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13254">issues.joomla.org/tracker/joomla-cms/13254</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13254">issues.joomla.org/tracker/joomla-cms/13254</a>.</sub>

**Comment by Spudley** [comment]
I'm pleased to see that this has been resolved. Thank to @mbabker and everyone else involved.

Since this bug would affect anyone using the User Profile plugin who moves to 3.6.5, may I suggest that it might be worthwhile adding a note about it on the [FAQ page about the 3.6.5 release](https://docs.joomla.org/Category:Version_3.6.5_FAQ).  Thank you.  :)

**Comment by infograf768** [comment]
> Since this bug would affect anyone using the User Profile plugin who moves to 3.6.5, may I suggest that it might be worthwhile adding a note about it on the FAQ page about the 3.6.5 release. 

Please do.

**Comment by infograf768** [comment]
Done
https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields

**Pull request merged**
