### PR TITLE
Add WinCache to AppVeyor build

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue #13804 .

### Summary of Changes
Adds WinCache to AppVeyor build
### Testing Instructions
code review - notice there are now only 151 skipped tests where before there was 159

### Documentation Changes Required
none

### CODE REVIEW

**Comment by mbabker** [comment]
You didn't enable WinCache on the PHP 5.6 build?

**Comment by mbabker** [comment]
Actually, it doesn't look like it's enabling on any of the builds, just doing the download (seems the echo statements don't work right in the `ps` lines.  I checked an earlier build and don't see the skipped test count going down.

You should be able to do the `echo extension=php_wincache.dll >> php.ini` like we do the other extension files after the download I'd imagine.

**Comment by photodude** [comment]
I totally overlooked that. 

With the correction implemented, we now have a bunch of failures. Not sure if that is Environment setup, or Wincache issues.

**Comment by photodude** [comment]
Looking through the errors it seems one of the issues stems from the call to the clean method
https://github.com/joomla/joomla-cms/blob/staging/tests/unit/core/case/cache.php#L66

might be an environment configuration issue still

**Comment by photodude** [comment]
So wincache is installed and loaded, but I still get the error `ini_set(): Cannot find save handler 'wincache'`
Not sure what's wrong in the configuration.

**Comment by photodude** [comment]
I think I have the right php.ini items and in the right order to get wincache working now.

**Comment by photodude** [comment]
@mbabker This should be ready to go now. With wincache correctly running we get `Skipped: 137` rather than 150 something

**Comment by rdeutz** [comment]
looks good

**Comment by wilsonge** [comment]
I don't know well enough yet. So I trust your judgement :)

**Pull request merged**
