### PR TITLE
[4.1 Update com_installer.ini

### PR DESCRIPTION
**Pull request by brianteeman**
grammar correction

s\disable\disabling the

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c26a59549b6ecd1d929d99302b16196986c6b2e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37049">issues.joomla.org/tracker/joomla-cms/37049</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37049">issues.joomla.org/tracker/joomla-cms/37049</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
