### PR TITLE
[4.2] Media Manager should delete the right files

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #39226 .

### Summary of Changes

Take into account the search state when deleting files

### Testing Instructions

Follow the instructions on the issue

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Kudos to @fancyFranci for this one

### CODE REVIEW

**Comment by brianteeman** [comment]
To testers. If you are not running a pre-built package you will need to run

```

npm run build:com_media
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39405">issues.joomla.org/tracker/joomla-cms/39405</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8d0d5010093dc13775c45a46397ea2db2bf76eb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39405">issues.joomla.org/tracker/joomla-cms/39405</a>.</sub>

**Comment by dgrammatiko** [comment]
@Hackwar could you check why the drone is returning an exit code 0 when the same command in a normal terminal (eslint ...) will return -1?
Screenshot 2022-12-13 at 00 20 32

BTW the reported issue is irrelevant with the code in this PR

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d0d5010093dc13775c45a46397ea2db2bf76eb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39405">issues.joomla.org/tracker/joomla-cms/39405</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39405">issues.joomla.org/tracker/joomla-cms/39405</a>.</sub>

**Comment by fancyFranci** [comment]
That was really fast! Thank you very much

**Pull request merged**
