### PR TITLE
[CODE STYLE] Simple code style improvement

### PR DESCRIPTION
**Pull request by ghost**
Removed redundant nesting by using early return.

### CODE REVIEW

**Comment by zero-24** [comment]
Can you make Mr. Travis happy? @nonumber ;)

```
FILE: /home/travis/build/joomla/joomla-cms/libraries/joomla/language/text.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 259 | ERROR | Whitespace found at end of line
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

```

**Comment by nonumber** [comment]
Done :)

PS: would be cool if trailing whitespace would be fixed automagically. Time to upgrade to CodeSniffer 2?

**Comment by zero-24** [comment]
>PS: would be cool if trailing whitespace would be fixed automagically. Time to upgrade to CodeSniffer 2?

The work has been startet but I'm not sure what hold the change or is needed ;) See: https://github.com/joomla/coding-standards/pulls

**Comment by Kubik-Rubik** [comment]
Thank you @nonumber! Merged.

**Pull request merged**
