### PR TITLE
[4.0] Clean up controllers in privacy component for j4 related deprecations and features

### PR DESCRIPTION
**Pull request by wilsonge**
- Fixes return docblocks
- Removes unused copy/paste params (and undocumented) from the `invalidate` function
- Fix `setError` to use `setMessage` (In order to do this I had to fractionally rework the logic in invalidate and `invalidateAll` when no items were selected - there should be no overall effect on this)
- Use `$this->app` instead of the factory application in the controller

Before this patch note many functionalities of requests (such as invalidating requests and deleting items in requests) do not work. After the patch they do.

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by brianteeman** [comment]
Not sure if it is related but when I try to email a data request I get a 500 error with the following call stack

```

1 | () | JROOT\libraries\src\Mail\Mail.php:136
-- | -- | --
2 | Joomla\CMS\Mail\Mail->Send() | JROOT\administrator\components\com_privacy\Model\ExportModel.php:238
3 | Joomla\Component\Privacy\Administrator\Model\ExportModel->emailDataExport() | JROOT\administrator\components\com_privacy\Controller\RequestController.php:153
4 | Joomla\Component\Privacy\Administrator\Controller\RequestController->emailexport() | JROOT\libraries\src\MVC\Controller\BaseController.php:736
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:382
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:116
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:241
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
11 | require_once() | JROOT\administrator\index.php:36


```

**Comment by wilsonge** [comment]
I don't think so as it's coming from the model email sending. I skipped the email stuff when testing as i was on the train :/ If it's just that mark it as successful and I'll come back to that. At a quick code review I think somethings wrong inside the mailer itself

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 735af567fb4a0a60302b24c2a18b3ac909927c2a<br /><br />As far as I can tell the changes are good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24874">issues.joomla.org/tracker/joomla-cms/24874</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
