### PR TITLE
[staging] missing string in installation

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes the missing string error reported at #

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c559bfb98447ae47ca5e94bfcbd099e7a8b6e226<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28440">issues.joomla.org/tracker/joomla-cms/28440</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c559bfb98447ae47ca5e94bfcbd099e7a8b6e226<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28440">issues.joomla.org/tracker/joomla-cms/28440</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28440">issues.joomla.org/tracker/joomla-cms/28440</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks 👍

**Comment by brianteeman** [comment]
thx

**Pull request merged**
