### PR TITLE
live site Update configuration.php-dist

### PR DESCRIPTION
**Pull request by brianteeman**
If you ever have a server that requires you to enter a value for $live_site in the configuration.php it must include the protocol eg https://

This PR updates the comment in the configuration.php-dist example file in the installation folder to include an example value for this field.

This is important because a value of www.example.com will not work it has to include the protocol and be https://www.example.com

If you wish to verify this you can edit your own configuration.php file and include the domain name as the value of $live_site and you will see that no css etc will load. But if you include the protocol eh (https://www.example.com) then it will work as expected.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on ff805fc91ca27a0fbb3bb51b7671cfa3a2ee672b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40695">issues.joomla.org/tracker/joomla-cms/40695</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ff805fc91ca27a0fbb3bb51b7671cfa3a2ee672b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40695">issues.joomla.org/tracker/joomla-cms/40695</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40695">issues.joomla.org/tracker/joomla-cms/40695</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
