### PR TITLE
More inline scripts through API

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Remove inline script tags from body

Inline scripts should be loaded through API e.g. addScriptDeclaration()
#### Testing

Apply patch 
Goto:
 `/administrator/index.php?option=com_banners&view=client&layout=edit`
`/administrator/index.php?option=com_banners&view=tracks`
`/administrator/index.php?option=com_config&view=component&component=com_content` Make sure the first tab is the default one
`/administrator/index.php?option=com_languages&view=language&layout=edit&lang_id=1` 
`/administrator/index.php?option=com_media`

try the usual form options, submit, cancel etc
#### B/C

NONE
#### Performance impact

This should not degrade performance!
Also using the API might enable us to get all the scripts to the end of the page and thus get a performance increase! (we’re NOT there yet!)

### CODE REVIEW

**Comment by davdebcom** [comment]
@test
Works, no issues discovered after applying patch. Seems to be working correctly. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6709">issues.joomla.org/joomla-cms/6709</a>.</sub>

**Comment by erikvandoorne** [comment]
tested, works ok !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6709">issues.joomla.org/joomla-cms/6709</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6709">issues.joomla.org/joomla-cms/6709</a>.</sub>

**Comment by dgt41** [comment]
I made an error on media field view, now it is corrected!
To test edit an article, goto images, select an image
everything should work fine!

I guess RTC has to be removed...

**Comment by zero-24** [comment]
I have just tested the fixed bug. So we can move this back to RTC :smile: Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6709">issues.joomla.org/joomla-cms/6709</a>.</sub>

**Pull request closed without merging**
