### PR TITLE
Create Article:: Can we change the placeholder message for 'Tag'

### PR DESCRIPTION
**Pull request by brianteeman**
Remake of #8041
#### Summary of Changes

Placeholder message for tag field should be "Type or select some options".
#### Testing Instructions

This had **4 good tests at #8041** it was just sat waiting for an updated string in the site language file

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 0e859a9588e63acc277c68e93f82dfe56c61cc2a<br /><br />Works as intended in both front and backend<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9360">issues.joomla.org/joomla-cms/9360</a>.</sub>

**Comment by wilsonge** [comment]
RTC

**Comment by andrepereiradasilva** [comment]
@joomla-cms-bot why did you remove the RTC?

**Comment by mbabker** [comment]
Someone didn't set the RTC status on the tracker...

**Pull request merged**
