### PR TITLE
RFC Batch modals comply with the new layout

### PR DESCRIPTION
**Pull request by dgrammatiko**
Batch modals are hardcoded. This is a proposal to make them more flexible/overridable. Right now it’s only for banners, but, if this gets some attention I will make it site wide.

So what’s in it?

Well batch modals have a `tmpl/default_batch.php` file that holds all the html code for the modal.
But since @smz and @phproberto made some nice changes in the bootstrap modal everything is more modular and everything is controlled from the respected layouts e.g. body, footer.
So this PR tries to break the hardcoded html code to 2 files `tmpl/default_batch_body.php` and `tmpl/default_batch_footer.php`
Now we have more control over the output (read this as getting ready for bs3)

### CODE REVIEW

**Comment by bertmert** [comment]
@test Success with current Firefox, IE11, current Chrome. and com_banners.
Batched several items succesfully. Could cancel, close etc.

**Comment by Kubik-Rubik** [comment]
@test Tested successfully with both administrator templates. Batch feature still works properly!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7000">issues.joomla.org/joomla-cms/7000</a>.</sub>

**Comment by MAT978** [comment]
@test 

#7000 Tested successfully with both administrator templates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7000">issues.joomla.org/joomla-cms/7000</a>.</sub>

**Comment by smz** [comment]
@test OK (both admin templates)

@dgt41
I think it is not necessary to set the `width` and `height` parameters for the modal: if I remember correctly those are used only in case of an `iframe` modal, which is not the case here...

**Comment by Kubik-Rubik** [comment]
@smz Sergio, if you test it, then please mark your result in the issue tracker as well (not only in a comment at GitHub).

@dgt41 Thank you for your contribution. I will merge it!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7000">issues.joomla.org/joomla-cms/7000</a>.</sub>

**Comment by smz** [comment]
@Kubik-Rubik ... oops, forgot about it, sorry!

**Comment by Kubik-Rubik** [comment]
@smz Sergio, no problem at all, just a small reminder! :-)

**Comment by smz** [comment]
@Kubik-Rubik  Victor, honestly I'd removed those `width` and `height` options before merging...

**Comment by smz** [comment]
... but they do no harm: just ignored.

**Comment by Kubik-Rubik** [comment]
@smz Since I've merged it already, please do a small PR for it. In #7003 @dgt41 should remove them before merging. Thanks!

**Comment by smz** [comment]
OK!

**Comment by smz** [comment]
... or @dgt41 could incorporate that in #7003. I stand-by waiting for @dgt41...

**Comment by dgt41** [comment]
@smz @Kubik-Rubik will do it in #7003, thanks!

**Pull request closed without merging**
