### PR TITLE
JBrowser Opera 15+ detection

### PR DESCRIPTION
**Pull request by sergey-zero**
Opera 15 + browsers detection in JBrowser.
## How to test

You can use this code snippet for test of detection

```
jimport('joomla.environment.browser');
$browser = JBrowser::getInstance();
$browserType = $browser->getBrowser();
$browserVersion = $browser->getMajor();
var_dump($browserType, $browserVersion);
```

### CODE REVIEW

**Comment by piotr-cz** [comment]
There is one more browser detection library shipped with joomla, [JApplicationWebClient](https://github.com/joomla/joomla-cms/blob/3.4.5/libraries/joomla/application/web/client.php).

Adequate fix is here: https://github.com/joomla-framework/application/pull/53

**Comment by wojsmol** [comment]
@sergey-zero see https://github.com/sergey-zero/joomla-cms/pull/1

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on a66d92a490170fd92da8803b1b4b258603ceeb5a<br /><br />Tested on UKFast hosting:
PHP: 5.4.45 
MySQL: 5.5.37
Apache webserver<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8449">issues.joomla.org/joomla-cms/8449</a>.</sub>

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on a66d92a490170fd92da8803b1b4b258603ceeb5a<br /><br />Tested on Namesco hosting:
PHP: 5.3.29 
MySQL: 5.5.44-37.3-log 
Apache webserver

Before patch got chrome 47 after patch, got opera 34 (correctly)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8449">issues.joomla.org/joomla-cms/8449</a>.</sub>

**Comment by roland-d** [comment]
@sergey-zero can you please merge the PR by @piotr-cz Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8449">issues.joomla.org/joomla-cms/8449</a>.</sub>

**Comment by wojsmol** [comment]
@roland-d https://github.com/sergey-zero/joomla-cms/pull/1 is my PR :smile: 
@sergey-zero Please merge mentioned PR

**Comment by henkrijneveld** [comment]
Tested with:

Opera 36
Linux 15.10
Php 5.6.20

Success!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8449">issues.joomla.org/joomla-cms/8449</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on a66d92a490170fd92da8803b1b4b258603ceeb5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8449">issues.joomla.org/joomla-cms/8449</a>.</sub>

**Comment by roland-d** [comment]
@sergey-zero Can you please fix the failed test. The error is:

FILE: ...travis/build/joomla/joomla-cms/libraries/joomla/environment/browser.php

--------------------------------------------------------------------------------

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)

--------------------------------------------------------------------------------

 248 | ERROR | Please start your comment with a capital letter; found "// for

     |       | opera 15+"

Thank you.

**Comment by wojsmol** [comment]
@roland-d PR https://github.com/sergey-zero/joomla-cms/pull/1 correcting this error is waiting for approval by @sergey-zero from 18 November 2015. If you do not have nothing against I will open a new PR without this error.

**Comment by brianteeman** [comment]
Yes please create a new pr

**Comment by wojsmol** [comment]
@brianteeman new PR is https://github.com/joomla/joomla-cms/pull/9949
@digitalgarage @Bodge-IT @henkrijneveld Please test #9949

**Pull request closed without merging**
