### PR TITLE
[4.1] When loading a new menu item type, keep the session data and fallback to filter

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #22150.

### Summary of Changes
When changing a menu item type for an unsaved menu item, then the session data should be used instead of the filter data or null. This pr puts the behavior from #6976 as fallback which is fine IMO.

### Testing Instructions
- In backend menus, click "New"
- Enter a name, set an access level and other different attributes in the right sidebar
- Then click on the "select menu type" button
- Choose a different Menutype

### Actual result BEFORE applying this Pull Request
The access level and other changed attributes values do get reverted.

### Expected result AFTER applying this Pull Request
The access level and other changed attributes keep the previous defined values.

### CODE REVIEW

**Comment by simbus82** [comment]
I have tested this item :red_circle: unsuccessfully on 0635d4ed2b0257bec3193f3de9a1afd2d807132f<br /><br />Tested on Joomla 4.1.2.

The access level and other changed attributes are keeping the previous defined values after one or more changes of the menu type. This is really great.

The bad is that now the behaviour from #6976 is not working anymore.
If i do a filter selection in the menu manager, after creating a new menu item, i have no preselected values.

If the loss of this functionality was unintended, the test was unsuccessful for me.
Is it not possible to maintain both behaviors? I like this patch, it can save us a lot of time!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37478">issues.joomla.org/tracker/joomla-cms/37478</a>.</sub>

**Comment by coolcat-creations** [comment]
I tested the prebuilt package and tested also on a 4.1.2 live site without patch.
For what it should solve the PR Works but I agree to @simbus82 that it does not have the preselected value of the permissions in the item anymore.

**Comment by laoneo** [comment]
@simbus82 can you post some screenshots how to reproduce the reverted behavior? When I retry your steps I still have the filter in the form set.

**Comment by coolcat-creations** [comment]
The filters are still set but not the permission one @laoneo

**Comment by laoneo** [comment]
Not sure if I can fix the permissions as well, will look into this. But as far as I understood @simbus82, something along the lines is reset in the filters.

**Comment by simbus82** [comment]
> @simbus82 can you post some screenshots how to reproduce the reverted behavior? When I retry your steps I still have the filter in the form set.

Same as @coolcat-creations has written, i have double checked and only the permission is not set by previous filters selection.
With the screenshots you do not see too much, but I had a video, only it is full of "private" data of the site used as a test.
Maybe the last row in your code need to be like others?

```
$data['parent_id'] = $data['parent_id'] ?? ($filters['parent_id'] ?? null);
$data['published'] = $data['published'] ?? ($filters['published'] ?? null);
$data['language']  = $data['language'] ?? ($filters['language'] ?? null);
$data['access']    = $data['access'] ?? ($filters['access'] ?? Factory::getApplication()->get('access')); /* THIS */
```

**Comment by laoneo** [comment]
Can you guys test again? The access level should be unset now.

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on fe143e87f81a08f4f879edb88528dc93e2460249<br /><br />Sure!

The access level and other changed attributes are keeping the previous defined values and the behaviour from #6976 is working!

Thanks a lot!

PS: maybe we can open a new feature request for extend the behaviour to the "parent item" field too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37478">issues.joomla.org/tracker/joomla-cms/37478</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on fe143e87f81a08f4f879edb88528dc93e2460249<br /><br />Tested successfully.
Me and other Joomla users waited for this bugfix for at least 4 years it's a day to celebrate for me because this was a very very annoying bug :-)

THANK YOU SO MUCH !!!!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37478">issues.joomla.org/tracker/joomla-cms/37478</a>.</sub>

**Comment by laoneo** [comment]
> 
> THANK YOU SO MUCH !!!!

You worked for that too, just in the background :smirk:

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37478">issues.joomla.org/tracker/joomla-cms/37478</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
