### PR TITLE
[4.0] bootstrap 5.0.2

### PR DESCRIPTION
**Pull request by brianteeman**
Changelog https://github.com/twbs/bootstrap/releases/tag/v5.0.2

Pull Request for Issue # .

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 15040c652aad988bc3216e6f6052a123a0fbc4ff<br /><br />I noticed bootstrap har been updates to 5.0.2. Clicked trough the system to test if noting is broken.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34612">issues.joomla.org/tracker/joomla-cms/34612</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 15040c652aad988bc3216e6f6052a123a0fbc4ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34612">issues.joomla.org/tracker/joomla-cms/34612</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34612">issues.joomla.org/tracker/joomla-cms/34612</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
