### PR TITLE
[plg_quickicon_phpversioncheck] Avoid errors when Joomla! gets outdated

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #27195.

### Summary of Changes

Fixes error that occurs when PHP version is unsupported and outdated Joomla! version doesn't know a recommended PHP version.

### Testing Instructions

See https://github.com/joomla/joomla-cms/issues/27195#issuecomment-560397865.

### Expected result

No errors.

### Actual result

>Call to a member function format() on null

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on f99404e07b3028de30284f11c02a97d4624bfd2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27197">issues.joomla.org/tracker/joomla-cms/27197</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f524109debd5403b9211debd2136842bd1bb6e0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27197">issues.joomla.org/tracker/joomla-cms/27197</a>.</sub>

**Comment by alikon** [comment]
RTC
previous test is still good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27197">issues.joomla.org/tracker/joomla-cms/27197</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for the better php EOL support sharky

**Pull request merged**
