### PR TITLE
FIeld / Field group create  - remove empty column

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #33800 .

### Summary of Changes
Field/Field group create  - remove empty column

### Testing Instructions
Create new 'Field' or 'Field Group'. Navigate to publishing tab

### Actual result BEFORE applying this Pull Request
Form half width

### Expected result AFTER applying this Pull Request
Form full width

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 3a0e167258a83c85f6cc39a337518b6890048280<br /><br />Thank you, I checked it - everything is as it should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33806">issues.joomla.org/tracker/joomla-cms/33806</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a0e167258a83c85f6cc39a337518b6890048280<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33806">issues.joomla.org/tracker/joomla-cms/33806</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33806">issues.joomla.org/tracker/joomla-cms/33806</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by sandewt** [comment]
See [https://github.com/joomla/joomla-cms/pull/33816#issuecomment-841679736](https://github.com/joomla/joomla-cms/pull/33816#issuecomment-841679736)

**Pull request merged**
