### PR TITLE
Tinymce plugin string update

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Update the label in the plugin options to match the style guide
##### Before

Code sample
##### After

Code Sample

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8c7759cf333ab0fee6aec4274022f6c721ffc736<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9955">issues.joomla.org/joomla-cms/9955</a>.</sub>

**Comment by wilsonge** [comment]
Merged as simple change. Thanks :)

**Comment by brianteeman** [comment]
Dam I wasnt finished

**Comment by andrepereiradasilva** [comment]
:smile:

**Comment by mbabker** [comment]
> Dam I wasnt finished

Looks like you just get another pull request to your name then 😝

**Pull request merged**
