### PR TITLE
[3.9][JLayout images] Remove unnecessary isset(...)

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
- Code review. We don't need the additional isset(...) check because !empty(...) is sufficient.

### Expected result
- No changes with output of intro images in category blogs and featured blogs
- No changes with output of full images in article views

### Actual result
- Unnecessary code.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7d9faeb795b80c1000058ea20b3b0b8a84f102be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24390">issues.joomla.org/tracker/joomla-cms/24390</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 7d9faeb795b80c1000058ea20b3b0b8a84f102be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24390">issues.joomla.org/tracker/joomla-cms/24390</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
