### PR TITLE
[4.3] Fix filename of finder commonwords txt file

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #39182  .

### Summary of Changes
When the language code was removed from the filenames of the translation files, this code was forgotten.

### Testing Instructions
Install a language with commonwords file. Check in #__finder_terms_common if the words are there. After applying the patch, install the language again and check if the words are present now.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by heelc29** [comment]
I have tested this item :red_circle: unsuccessfully on 461d591638cec06a98b7da9a9e5fa948960eabc2<br /><br />It will work, when I install the **only** the site language. When I install the language pack (for example german) the common words will added when `site` language is install, but after this the `administrator` and `api` language will be installed and the words will be deleted. The order of installation will depend on the package manifest.

https://github.com/joomlagerman/joomla/blob/fef13226151af2fd5a6a73e30998d309c06befde/pkg_de-DE.xml#L26-L30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39188">issues.joomla.org/tracker/joomla-cms/39188</a>.</sub>

**Comment by Hackwar** [comment]
I moved the removal of the words upon installation to a point where it is only executed if new words are added again. This leaves the problem that when you install a language pack and then uninstall single languages again (for example because you don't need them in the backend), the common words would be removed as well.

**Comment by richard67** [comment]
> I moved the removal of the words upon installation to a point where it is only executed if new words are added again. This leaves the problem that when you install a language pack and then uninstall single languages again (for example because you don't need them in the backend), the common words would be removed as well.

Is ok for me.

@heelc29 Is that ok for you, too, and would this revert your negative test result and would it also close issue #39182 ?

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 624b7d0b4864731ce4f8f53c8f5caacf790039cf<br /><br />Works and closes #39182.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39188">issues.joomla.org/tracker/joomla-cms/39188</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 624b7d0b4864731ce4f8f53c8f5caacf790039cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39188">issues.joomla.org/tracker/joomla-cms/39188</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39188">issues.joomla.org/tracker/joomla-cms/39188</a>.</sub>

**Comment by obuisard** [comment]
Thank you again Hannes @Hackwar

**Pull request merged**
