### PR TITLE
[com_fields] Add a parameter to trigger the additional plugin events in the news module

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #13699 .

### Summary of Changes
Adds a new parameter to the news module which allows to enable/disable the triggering of the additional plugin events onContentAfterTitle, onContentBeforeDisplay and onContentAfterDisplay.

### Testing Instructions
* Add some custom fieldsa to articles
* Create and publish a news module
* See that the custom fields appear
* Set the new parameter "Trigger Plugin Events" to "No" and verify that the fields no longer appear.

### Notes
Please have a look over the language strings. I'm not sure if they are correct (eg can the voting be shown there as well? The plugin event suggests so.) and proper english.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by zero-24** [comment]
> Adds a new parameter to the news module which allows to enable/disable the triggering of the additional plugin events onContentAfterTitle, onContentBeforeDisplay and onContentAfterDisplay.

Why do you want to add a option for that why not enabled this by default? Maybe we should not use `com_content.aricle` as context maybe better `mod_articles_news`?

**Comment by Bakual** [comment]
> Why do you want to add a option for that why not enabled this by default? 

It's enabled by default since that is the current behavior. The idea is to allow to disable it 😄 
If you change the context, it means fields  wouldn't work at all anymore and all other content plugins would have to adjust as well. `com_content.article` is the correct context since we're passing an article from com_content.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1516e37adb19c5e15ab266e106b753592d68cdc1<br /><br />"Trigger Plugin Events" set to "No"/"Yes" show or hide Fields of Article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13703">issues.joomla.org/tracker/joomla-cms/13703</a>.</sub>

**Comment by coolcat-creations** [comment]
Is it regarding custom fields or all plugin events? It should just disable custom_fields by default... what if i want to display plugins but not the fields?

**Comment by mbabker** [comment]
Without creating a separate event dispatcher with only the listeners you want responding to an event, you can't say "I want this place to trigger `onContentPrepare` but only use the email cloaking and loadmodule plugins" (as an example).  So it's an all or nothing thing, that's just how event dispatchers work.

**Comment by Bakual** [comment]
If you only want to show other plugins but not fields, you need to set the field to not display automatic and include it manually in an override if needed. That's why that option exists.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 1516e37adb19c5e15ab266e106b753592d68cdc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13703">issues.joomla.org/tracker/joomla-cms/13703</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13703">issues.joomla.org/tracker/joomla-cms/13703</a>.</sub>

**Pull request merged**
