### PR TITLE
Remove administrator helper test

### PR DESCRIPTION
**Pull request by rdeutz**
### Summary of Changes
Cleaning up our tests. Remove last administrator test. Test was for a static helper function. Should be better tested with an system test because it can't be unit tested

### Testing Instructions
Check if the unit test still running

### CODE REVIEW

**Comment by wilsonge** [comment]
Why can't this be unit tested? The unit tests look fine to me?

**Comment by mbabker** [comment]
Ya I'm kinda with George here.  Sure the class is a static helper, but at least its dependencies are mockable through an absurd series of events (good ol' JFactory).

Once we switch over to the newer test structure then I'd hit the button, but for now this just seems like deleting a test for the sake of it.

**Comment by brianteeman** [comment]
@rdeutz should this be closed?

**Comment by rdeutz** [comment]
no keep it open, I need to be in good mood to write an answer here :-)

**Comment by brianteeman** [comment]
You are rteired now - you should be in a permanent good mood

**Comment by brianteeman** [comment]
@rdeutz are you in a good mood yet

**Comment by rdeutz** [comment]
not really but we can close it

**Pull request closed without merging**
