### PR TITLE
[newsfeed modal field] Adds Create News Feed button and other improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
### Summary of Changes

This PR is the sequence of https://github.com/joomla/joomla-cms/pull/11830 but for now for newsfeed modal.

For list of changes see https://github.com/joomla/joomla-cms/pull/11830 (same changes, but for newsfeed now).

Similiar PR: 
- Article: https://github.com/joomla/joomla-cms/pull/11830
- Category: https://github.com/joomla/joomla-cms/pull/11857
- Contact: https://github.com/joomla/joomla-cms/pull/11858
- Newsfeed: https://github.com/joomla/joomla-cms/pull/11862 (this one)
### Animated Gif (click to view in full screen)

modal-newsfeed
### Testing Instructions
- Use latest staging
- Apply patch https://github.com/joomla/joomla-cms/pull/11830 and then this patch
- Create a Menu item Single News Feed  type
- Test all the "Edit", "Create", "Select" and "Clear" buttons  (as animated gif)
- In a multilanguage install edit a news feed and try the modal button in the associations tab
- Test all the "Edit", "Create", "Select" and "Clear" buttons.
- Code review to check all is ok.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 85de2a9029ece8afc26ab094b3ef0225b98baf89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by bhavikTailored** [comment]
- I have tested this issue successfully.
- But we should require apply patch first of #11830 then I have success.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 85de2a9029ece8afc26ab094b3ef0225b98baf89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 85de2a9029ece8afc26ab094b3ef0225b98baf89<br /><br />If you click on create and open the modal and then change your mind its not possible to close the modal<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 85de2a9029ece8afc26ab094b3ef0225b98baf89<br /><br />Sorry - didnt see I needed to apply another PR first - works great<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> Sorry - didnt see I needed to apply another PR first - works great

@brianteeman If you didn't apply the other pacth that is not a valid test!

**Comment by brianteeman** [comment]
@andrepereiradasilva which is why I retested and then marked it as successful ;)

**Comment by andrepereiradasilva** [comment]
ok :+1:

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on 85de2a9029ece8afc26ab094b3ef0225b98baf89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by zero-24** [comment]
Thanks. RTC Commiter please double check that the other PR is merged before this one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11862">issues.joomla.org/joomla-cms/11862</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/bbb74c3c9114093ddcc914d32bfc34f738c97e20

**Pull request closed without merging**
