### PR TITLE
[4.0] State to Stage

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Following #21566 

### Summary of Changes
Changed State to Stage

### CODE REVIEW

**Comment by wilsonge** [comment]
You need to change the XML file too :)

**Comment by wilsonge** [comment]
@jeckodevelopment are you planning on fixing this one?

**Comment by jeckodevelopment** [comment]
@wilsonge yes, which XML file?

**Comment by infograf768** [comment]
Hmm
See https://github.com/joomla/joomla-cms/pull/21579

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/content/joomla/joomla.xml

**Comment by jeckodevelopment** [comment]
@wilsonge should be ok now

**Comment by wilsonge** [comment]
Sorry i missed the second pair of strings were the email. These constants need changing too :) https://github.com/jeckodevelopment/joomla-cms/blob/State2Stage/plugins/content/joomla/joomla.php#L517-L518

**Comment by infograf768** [comment]
Folks, as I said above, this is partly also taken care of in https://github.com/joomla/joomla-cms/pull/21579

As I guess 21579 is quite important, can we combine please?

**Comment by jeckodevelopment** [comment]
done @wilsonge 
@infograf768 how to proceed?

**Comment by infograf768** [comment]
The best would be to propose a PR against Bembelimen branch "workflow-prevent-trashing"

https://github.com/bembelimen/joomla-cms/tree/workflow-prevent-trashing

**Comment by brianteeman** [comment]
Workflows has broken so much - just merge this and say thank you to those helping to fix it and worry about any merge conflicts later

**Pull request merged**
