### PR TITLE
[4.1] s/succes/success

### PR DESCRIPTION
**Pull request by brianteeman**
spelling

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2d9ec22d4b2d10e5c8536674e62beb1d03f7808b<br /><br />Code review. The variable is used later below with the right spelling.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36824">issues.joomla.org/tracker/joomla-cms/36824</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2d9ec22d4b2d10e5c8536674e62beb1d03f7808b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36824">issues.joomla.org/tracker/joomla-cms/36824</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36824">issues.joomla.org/tracker/joomla-cms/36824</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
