### PR TITLE
[com_checkin] Show only tables with check out items to check in

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

com_checkin behaves in a different way than the other components.
If show the tables even if there are no items to check in.

This PR changes that to only show the tables that have items to check in.
#### Testing Instructions
-  Use latest staging
- Open an article and don't save and/or close it (ex: change the url in the browser address bar to https://domain.tld/administrator/)
- Go to "System -> Global Check-in" you will see something like this:

image
- Apply patch with the patchtester
- Go again to "System -> Global Check-in" you will now see something like this:

image
- Select that table and press "Check-in"
- You will now get a message like this

image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have not tested this item.<br /><br />Really like this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9837">issues.joomla.org/joomla-cms/9837</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 39a94b199d20b4ddbc7f593209b3db31fed3916f<br /><br />Really like this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9837">issues.joomla.org/joomla-cms/9837</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 39a94b199d20b4ddbc7f593209b3db31fed3916f<br /><br />Works as described - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9837">issues.joomla.org/joomla-cms/9837</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing @brianteeman @MATsxm

**Comment by brianteeman** [comment]
RTC 
Simple but useful improvement<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9837">issues.joomla.org/joomla-cms/9837</a>.</sub>

**Pull request merged**
