### PR TITLE
[4.0] Fix copy token error

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #32852.

### Summary of Changes
This small PR fix copy token error as described at #32852.

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/32852 , confirm the issue
2. Apply patch
3. Run **npm run build:js** to compile and transpile the JavaScript files to the correct format and create minified files. Or get the update package for this PR at https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/32853/downloads/41179/Joomla_4.0.0-beta8-dev+pr.32853-Development-Update_Package.zip , go to System -> Update -> Joomla and install that update package.
4. Try again, confirm that no error shows in console and the token string is copied to clipboard.

### CODE REVIEW

**Comment by rdeutz** [comment]
I have tested this item :white_check_mark: successfully on 9d18679e77d506597a980852b1a036bab3077262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32853">issues.joomla.org/tracker/joomla-cms/32853</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d18679e77d506597a980852b1a036bab3077262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32853">issues.joomla.org/tracker/joomla-cms/32853</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32853">issues.joomla.org/tracker/joomla-cms/32853</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
