### PR TITLE
[4] Same Easing for Logo and Sidebar transition

### PR DESCRIPTION
**Pull request by simbus82**
Pull Request for Issue #35264.

### Summary of Changes
Change an "ease" with and "ease-in-out" transition

### Testing Instructions
Use the Toggle Menu and see effect

### Actual result BEFORE applying this Pull Request
issue-solved-joomla-2

### Expected result AFTER applying this Pull Request
issue-solved-joomla-3

### Documentation Changes Required

No

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 461d8dd8bdef9254d6326758b32b9a6d3a712adc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35265">issues.joomla.org/tracker/joomla-cms/35265</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 461d8dd8bdef9254d6326758b32b9a6d3a712adc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35265">issues.joomla.org/tracker/joomla-cms/35265</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35265">issues.joomla.org/tracker/joomla-cms/35265</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
