### PR TITLE
[4.0] Expand the allowed list for the HTML sanitiser

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
By default, the sanitiser will remove all the form elements. This PR changes this behaviour so form elements would not disappear (on* events will still be removed).
The list of attributes comes directly from the MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attributes

### Testing Instructions
Apply the PR
Goto admin dashboard and open the browser console
pass some HTML to the sanitiser and check the result:

```js
Joomla.sanitizeHtml(`<input type="text" onchange="alert('nope')" >`);
```
Check more attributes and elements (button, select, textarea)

### Actual result BEFORE applying this Pull Request
Too strict

### Expected result AFTER applying this Pull Request
Less strict

### CODE REVIEW

**Comment by RickR2H** [comment]
@dgrammatiko I applied the patch and added to the console: Joomla.sanitizeHtml(`<input type="text" onchange="alert('nope')" >`);
Got the following in return: "<input type=\"text\">"

Is this correct?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34518">issues.joomla.org/tracker/joomla-cms/34518</a>.</sub>

**Comment by dgrammatiko** [comment]
> Is this correct?

Yes, the `onchange="alert('nope')"` is Javascript so correctly was removed by the sanitizer

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 1fe402d50e5d54f0b6bd333ee677ab2571bcb38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34518">issues.joomla.org/tracker/joomla-cms/34518</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1fe402d50e5d54f0b6bd333ee677ab2571bcb38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34518">issues.joomla.org/tracker/joomla-cms/34518</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34518">issues.joomla.org/tracker/joomla-cms/34518</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
