### PR TITLE
[4.4] Converting File class from CMS to framework package

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This PR changes the `Joomla\CMS\Filesystem\File` class over to `Joomla\Filesystem\File` where possible without any further changes. The remaining 12 files using the CMS class are using methods which aren't in the framework class or are in there differently.

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
This needs some proper testing as the system tests are crashing on various places. Really I would split this pr file by file and add proper testing instructions, just to be sure we do not break something.

**Comment by Hackwar** [comment]
The used code in the File classes are identical.

**Comment by laoneo** [comment]
Why are then the system tests failing on various places?

**Comment by sandewt** [comment]
Cypress, local test: test was NOT scuccessful

Before patch:

pr_40257_before

After patch: and so forth
pr_40257_after

**Comment by Hackwar** [comment]
I reverted one file which had also calls to File::getExt(). That makes this all pass again.

**Comment by laoneo** [comment]
Thanks!

**Comment by Elfangor93** [comment]
Since this PR is merged some of my extensions can not be updated anymore using the Joomla installer.

### Reason
Joomla\CMS\Filesystem\File::delete() just ignores files which should be deleted but do not exist. Joomla\Filesystem\File::delete() on the other hand throws an error. Therefore update scripts which delete some files already in the preflight suddenly do not work anymore. They stop in the middle of the updating process and outputting "Joomla\Filesystem\File::delete(): Failed deleting inaccessible file <FILENAME>".

@Hackwar @laoneo Do you think, should we update Joomla\Filesystem\File::delete() to ignore non existing files instead of throwing an error? From my point of view it is not necessary to throw an error if you try to delete a file which is not existent.

**Pull request merged**
