### PR TITLE
Wrong color on active menu item in mobile view - Protostar

### PR DESCRIPTION
**Pull request by arrowthemes**
Pull Request for Issue #12223 .
### Summary of Changes

Updated template.less
Updated template.css
### Testing Instructions

View protostar template in a mobile screen
The active menu item should have a white font color rather than a dark grey color which makes it hard to read.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />:+1: Thanks looks much better now!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12303">issues.joomla.org/tracker/joomla-cms/12303</a>.</sub>

**Comment by mehranfazili** [comment]
Tested, patch works perfectly. Thanks. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12303">issues.joomla.org/tracker/joomla-cms/12303</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12303">issues.joomla.org/tracker/joomla-cms/12303</a>.</sub>

**Comment by rdeutz** [comment]
@arrowthemes could you fix the conflicts, thanks

**Pull request merged**
