### PR TITLE
[4.0] Add show all articles filter

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #21542 .

### Summary of Changes
Readd the "All" filter to the condition filter in article view.

### Testing Instructions
Open articles list view and filter by condition => all

### CODE REVIEW

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21704">issues.joomla.org/tracker/joomla-cms/21704</a>.</sub>

**Comment by ghost** [comment]
Tried to apply Pull Request per Patchtester get `The file marked for modification does not exist: libraries/src/Form/Field/WorkflowconditionField.php`

**Comment by wojsmol** [comment]
@franz-wohlkoenig check if your Joomla! installation is updated.

**Comment by ghost** [comment]
Its the nightly Build.

**Comment by wojsmol** [comment]
Then something is wrong - this file was created 2 days ago with https://github.com/joomla/joomla-cms/pull/21585 merge

**Comment by ghost** [comment]
i install every Dav new at CloudAccess (launch.joomla.org).

**Comment by wojsmol** [comment]
I will check now on my CA account.

**Comment by wojsmol** [comment]
@franz-wohlkoenig Because I don't have passibility to reset my Joomla! 4.0 on CA to 4.0 only to 3.8 I reinstalled it manually and then patch works as expected. using patch tester

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 21afaa4ae7e7746571a27ba426dae6896b6caba9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21704">issues.joomla.org/tracker/joomla-cms/21704</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 21afaa4ae7e7746571a27ba426dae6896b6caba9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21704">issues.joomla.org/tracker/joomla-cms/21704</a>.</sub>

**Comment by wojsmol** [comment]
@franz-wohlkoenig Do you have passibility to reset to Joomla! 4.0 nightly [here](https://www.cloudaccess.net/cloud-control-panel-ccp/155-application-management/893-resetting-an-application.html) or you just terminating old account and create new one?

**Comment by ghost** [comment]
Reset didn't work as you can only 3.* reset. So i'm terminating Site and launch new using same URL.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
