### PR TITLE
Make variable names match admin and frontend

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
renames $whiteoffset to $white-offset to more consistently match templates.

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request
was spelled 2 different ways.

### CODE REVIEW

**Comment by brianteeman** [comment]
Surely you can just remove 
` white-offset:                    $white-offset,`

and anyway dont you need to change this in modals.scss

```
  .btn {
    padding: 0 22px;
    margin-right: .5rem;
    font-size: 1rem;
    line-height: 2.3rem;
    color: var(--atum-text-dark);
    background: var(--white);
    **border-color: var(--whiteoffset);**
    box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, .25);
  }

```

**Comment by N6REJ** [comment]
> Surely you can just remove
> ` white-offset: $white-offset,`
> 
> and anyway dont you need to change this in modals.scss
> 
> ```
>   .btn {
>     padding: 0 22px;
>     margin-right: .5rem;
>     font-size: 1rem;
>     line-height: 2.3rem;
>     color: var(--atum-text-dark);
>     background: var(--white);
>     **border-color: var(--whiteoffset);**
>     box-shadow: 1px 1px 1px 0 rgba(0, 0, 0, .25);
>   }
> ```

I thought about that too @brianteeman I wasn't sure if it was safe to do so as I'm not a scss guru, so I played it safe.

As for the second item it will need to be changed won't it?  for some reason it didn't come up in the global search.

**Comment by richard67** [comment]
So or so I'm not sure if a code review is sufficient for testing, or if it not would be better to define a real test.

Due to our sometimes complicated scss structures you never know if a change which seems to be easy in code might not cause any unwanted side effects.

**Comment by N6REJ** [comment]
@chmst can someone from your group validate this pr?

**Comment by richard67** [comment]
> @chmst can someone from your group validate this pr?

Which group do you mean? The **frontend** template team to pimp up Cassiopeia? If so: What relation does it have to this PR here which changes scss for the **backend** template? Or what other group do you mean if not that one? Accessibility team? I also don't see a relation to that. So I am maximum confused now.

**Comment by N6REJ** [comment]
@richard67 SHOULDN'T affect the front-end but was thinking maybe someone on the cassiopeia team could verify the scss is done right.

**Pull request closed without merging**
