### PR TITLE
[5.2] Fixed a set of options for the demo data plugin

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
Changes have been made to the demo data localization file, as the module type has changed from **Articles - Category** to **Articles**.
Added and organized options in the demo data plugin after merging https://github.com/joomla/joomla-cms/pull/44142.
The **Category Link** option should be in **Yes/No** mode, like other similar options.

Just install the build, then the blog demo data and make sure everything is ok. You can touch the 3 created modules of type **Articles**.

### CODE REVIEW

**Comment by drmenzelit** [comment]
@Kostelano sorry, I didn't see your PR earlier. Can you please update your branch?

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 963617200cc87595039a94f0621926d70328a416<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44166">issues.joomla.org/tracker/joomla-cms/44166</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 963617200cc87595039a94f0621926d70328a416<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44166">issues.joomla.org/tracker/joomla-cms/44166</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44166">issues.joomla.org/tracker/joomla-cms/44166</a>.</sub>

**Pull request merged**
