### PR TITLE
[5.0] Increase meta description to 300 characters

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #36939 .

### Summary of Changes
Normalize the meta description field and increase the max length to 300 characters.

As a compromise to remove the limit completely.

### Testing Instructions
Add meta description longer then 160 characters.

### Actual result BEFORE applying this Pull Request
Max 160 allowed

### Expected result AFTER applying this Pull Request
Max 300 allowed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 94b9271c228003c748557ab3b655ba688cb9da05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41795">issues.joomla.org/tracker/joomla-cms/41795</a>.</sub>

**Comment by simbus82** [comment]
I have tested this item :red_circle: unsuccessfully on 94b9271c228003c748557ab3b655ba688cb9da05<br /><br />The meta description in menu items is still limited to 160 characters. This happen with the Menu Item Type selected or not selected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41795">issues.joomla.org/tracker/joomla-cms/41795</a>.</sub>

**Comment by Quy** [comment]
Please change under Menu Items.

**Comment by Quy** [comment]
Frontend: Site Configuration

https://github.com/joomla/joomla-cms/blob/94b9271c228003c748557ab3b655ba688cb9da05/components/com_config/forms/config.xml#L13

**Comment by HLeithner** [comment]
Fixed missing frontend changes

**Comment by webgras** [comment]
Still missing in the menu form
grafik

**Comment by HLeithner** [comment]
Now also menu items should have the new limit... the field has a different name.

**Comment by webgras** [comment]
I have tested this item :white_check_mark: successfully on bb7a24e755b866a89a07a2aabae49edc4adf5b1f<br /><br />Tested successfully, also for menus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41795">issues.joomla.org/tracker/joomla-cms/41795</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bb7a24e755b866a89a07a2aabae49edc4adf5b1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41795">issues.joomla.org/tracker/joomla-cms/41795</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41795">issues.joomla.org/tracker/joomla-cms/41795</a>.</sub>

**Pull request merged**
