### PR TITLE
[4.0] Component configuration deleted on failed validation

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/30282.

### Summary of Changes

Fixes component configuration being deleted when validation fails.

### Testing Instructions

Go to `Users` component configuration.
Set `Minimum Characters` to less than 8.
Change some other settings.
Try to save.

### Actual result BEFORE applying this Pull Request

`Configuration saved` message is shown but `Minimum Characters` is reset to 12, other settings also reset to their default values.
If you go to `#__extensions` table and inspect `params` column of `com_users` record you'll notice it's empty.

### Expected result AFTER applying this Pull Request

Form is not saved, `Invalid field: Minimum Characters` message is shown. Old, valid data in `#__extensions` table is still there.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
Would be nice if you could implement the more meaningful error messages that I tried to implement in #30906

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on f58a0df06afae72ac439325a2214a5f0b83e4a3d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31105">issues.joomla.org/tracker/joomla-cms/31105</a>.</sub>

**Comment by tushar33** [comment]
I have tested this item :white_check_mark: successfully on 08856df950b2637429d5a3ac27b6d2018c057c86<br /><br />Showing result as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31105">issues.joomla.org/tracker/joomla-cms/31105</a>.</sub>

**Comment by opn365** [comment]
I have tested this item :white_check_mark: successfully on 08856df950b2637429d5a3ac27b6d2018c057c86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31105">issues.joomla.org/tracker/joomla-cms/31105</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31105">issues.joomla.org/tracker/joomla-cms/31105</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
