### PR TITLE
Bug: Content field `publish_up` not being set when publishing previously unpublished article

### PR DESCRIPTION
**Pull request by ron4mac**
Correction for issue #8740. See there for test

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9869cd748481a0c85ae9d1970445ddda10066cce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8745">issues.joomla.org/joomla-cms/8745</a>.</sub>

**Comment by infograf768** [comment]
Modifying title of PR to be more informative.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8745">issues.joomla.org/joomla-cms/8745</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 9869cd748481a0c85ae9d1970445ddda10066cce<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8745">issues.joomla.org/joomla-cms/8745</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8745">issues.joomla.org/joomla-cms/8745</a>.</sub>

**Pull request merged**
