### PR TITLE
[4.1] remove unused rtl css

### PR DESCRIPTION
**Pull request by brianteeman**
This css was a special case for a bug in the old edge.

The bug is no longer present and that non-chromium version of edge is no longer supported.

code review

Spotted while checking some rtl issues

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4e9d89ff22c51c7b2579406151302c54389c2729<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37202">issues.joomla.org/tracker/joomla-cms/37202</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 4e9d89ff22c51c7b2579406151302c54389c2729<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37202">issues.joomla.org/tracker/joomla-cms/37202</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37202">issues.joomla.org/tracker/joomla-cms/37202</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
