### PR TITLE
[4.0] Redirect options

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to change the Import tate option to use the switcher instead of the old style yes/no

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 89f971930f72cd4b99be125e556c429bd2bf536e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24670">issues.joomla.org/tracker/joomla-cms/24670</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 89f971930f72cd4b99be125e556c429bd2bf536e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24670">issues.joomla.org/tracker/joomla-cms/24670</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24670">issues.joomla.org/tracker/joomla-cms/24670</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
