### PR TITLE
CodeMirror updated to 5.9

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
see: http://codemirror.net/doc/releases.html

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 55f9eb8c6b4134e45d864f19c8675f2c38f3c679<br /><br />Tested in template manager and as the default editr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8727">issues.joomla.org/joomla-cms/8727</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 55f9eb8c6b4134e45d864f19c8675f2c38f3c679<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8727">issues.joomla.org/joomla-cms/8727</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8727">issues.joomla.org/joomla-cms/8727</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on f3fb4a78b8cb0d9ee77f540c5990f9fe1ca5d5a4<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8727">issues.joomla.org/joomla-cms/8727</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks :)

**Pull request merged**
