### PR TITLE
[4.0] Menu Change status dropdown

### PR DESCRIPTION
**Pull request by brianteeman**
The dropdown item to make a menu item the "home" menu item was labeled Default

This simple PR changes it to say Home

### CODE REVIEW

**Comment by Quy** [comment]
For the other menu items, the title is "Set default". Should it be changed to "Set home"?

**Comment by brianteeman** [comment]
where?

**Comment by Quy** [comment]
set-default

**Comment by brianteeman** [comment]
Thanks. I didnt see it. I will fix that too.

**Comment by brianteeman** [comment]
@quy Any suggestions as the string is coming from "public static function isdefault " which I obviously cant change.

Changing it for language default is easy as thats a string

**Pull request closed without merging**
