### PR TITLE
fixed button description to language string

### PR DESCRIPTION
**Pull request by bene-we**
Pull Request for Issue #21357 .

### Summary of Changes
Fixed language string

### Testing Instructions

See if the button text is still the same

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
approve language string

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 410efa23d673df3a65dfda8e193c10326fd9636d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21387">issues.joomla.org/tracker/joomla-cms/21387</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 410efa23d673df3a65dfda8e193c10326fd9636d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21387">issues.joomla.org/tracker/joomla-cms/21387</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by SharkyKZ** [comment]
Use existing `COM_MENUS_ITEM_VIEW_EDIT_TITLE`?

**Comment by mbabker** [comment]
> Use existing COM_MENUS_ITEM_VIEW_EDIT_TITLE?

That means loading the `com_menus` language strings in `com_content`.  If you're going to make a global string, put it in a global file.  Otherwise, randomly including component language files is a bad idea, especially the way they quite commonly override other language strings.

**Comment by SharkyKZ** [comment]
@mbabker Suggesting this because `com_menus` is being loaded anyways.

https://github.com/joomla/joomla-cms/blob/410efa23d673df3a65dfda8e193c10326fd9636d/administrator/components/com_content/View/Article/HtmlView.php#L216-L220

But I agree. Actually, the whole feature should be made available globally instead of being hardcoded into `com_content`. It doesn't depend on content type anyways.

**Comment by wilsonge** [comment]
Thanks

**Pull request merged**
