### PR TITLE
UX Improvement - client-side form validation

### PR DESCRIPTION
**Pull request by cyrez**
UX Improvement - client-side form validation + com_users frontend label strings

<h2>How to Test ?</h2>

Note: test example with registration form. You can test with another form (profil, contact, third party form using Joomla client-side form validate...)

<h3>Before Patch</h3>

<h4>Test</h4>
- Resize you window to be around 800px height.
- Use login form, and click on "Create an account"
- Click directly on "Register" (by default on a fresh install you have 6 fields required, so you will have 6 fields invalid)

<h4>Result</h4>
- The page don't go up to the system message container.
- Ordering of fields invalid is wrong
- You have ":" at the end of the labels

<h3>After Patch</h3>

<h4>More than 5 fields required not filled</h4>
- Auto-scroll to the system message container
- No Field invalid + label displayed (in case of a form with 20 fields required, not filled, could be better than a long list! ;-) )
- Single content : "All fields with an \* are required."

<h4>Less than 5 fields required not filled</h4>
- Auto-scroll to the system message container
- Ordering is the same as the form fields order
- you don't have the ":" at the end of label

<h4>In all cases</h4>
- System message container header : "Please make sure the form is complete and valid."

UX Improvement :
- correct order of invalid field
- auto-scroll to system message container if form not valid
- if more than 5 fields are invalid, do not list all invalid field. Replaced by a single alert message.
- 2 strings added for client-side form validation (title + single message if more than 5 fields invalid)

Code Standards & Consistency :
- clean all indentation (previously mix of 1 space + 1 tab per indentation)
- a few changes to follow Joomla Javascript Code Standards (http://joomla.github.io/coding-standards/?coding-standards/chapters/javascript.md)
- remove all ":" at the end of labels, for consistency with all form fields, and to improve rendering of client-side form validation (no ":" for label in the Field invalid : %s)

### CODE REVIEW

**Comment by n9iels** [comment]
Good one!, but please notice this change also affect the administrator side!
But in this case that's something good I thinks so, for example add a new article and "forget" to fill in a title. The error message now contains your <h4> title, but is not containing the new error message.

In how far this change affect other view? For this form it is useful to generalise the error to: All fields with an * are required.
But in longer forms with multiple tabs, a message that tells you exactly with field your forget is more useful in my opinion.

**Comment by JoomliC** [comment]
<pre>
In how far this change affect other view? For this form it is useful to generalise the error to: All fields with an * are required.
But in longer forms with multiple tabs, a message that tells you exactly with field your forget is more useful in my opinion.
</pre>
@n9iels Thanks for testing!
Of course, this is to be tested with all form using Joomla client-side validation (i have added a note in the PR).
I have corrected the validate.js, to display the sentence when more than 5 fields invalid ($i set to 0 and not 1, to set it one time).
But, as it is coded, this change is a more logical one, but don't change behaviour.

Note that the Field invalid : [label of the invalid field] is display a mximum of 5 times.
When more than 5 fields invalid (that why registration, profil.... in frontend could be useful to see the difference) the <b>Field invalid: %s</b> lines are replaced by <b>All fields with an * are required.</b>

In case of a long form, with a lot of required fields, it make sense, in my opinion, to not display all the fields invalid, to prevent a long list of invalid fields! (that's why i have set a limit of 5 errors, and if more, a sentence to check the form).

In case of your test with Article, you should have this : 
<pre>
<b>Please make sure the form is complete and valid.</b>
Invalid field:  Title 
</pre>

Right ?

**Comment by n9iels** [comment]
Yes thats right, thats right. Seems logic in my opnium. So:
@test succesfull!

**Comment by nternetinspired** [comment]
Required fields may not have * next to them, and in fact accessibility and therefore UX is improved when they do not.

Maybe it is better to allow the browser to handle form validation? Modern browsers will not post a form with missing required values and they provide excellent, and very detailed, user feedback for each required field, directly on the field itself, e.g:

screen shot 2015-03-02 at 15 52 40

**Comment by nternetinspired** [comment]
p.s. Some more detail on why I dislike * in general: https://github.com/joomla/joomla-cms/issues/4139

**Comment by n9iels** [comment]
I thought that was actived by default for the most forms.  Looks like a good idea for the contactform. But you still need the validate.js for user who don't work with modern browsers.

@JoomliC is it possiple to integrate this?

**Comment by JoomliC** [comment]
@nternetinspired Thank you for this good reading! (with many pros and cons really interesting) I will take it into account about the string, to not add one with an asterisk ;-)

Note that this PR is about improvement, not refactory...

@n9iels yes, i will check this, and see what could be done now, and what could be done later. So test are delayed.

**Comment by JoomliC** [comment]
PR updated to take into account this PR : https://github.com/joomla/joomla-cms/issues/4139

This PR is not Ready to Commit, as it introduces icon-asterisk to replace *, and currently only strings for library and com_users are edited to remove the * from language strings.

You can test this both in admin and site side.
And everywhere there's a form with required fields.

About Main change concerning use of asterisk, related to https://github.com/joomla/joomla-cms/issues/4139 : 
- I have change the asterisk to icon-asterisk (used no where else in Joomla core).
- This way, only a styling, and easy to override!
- I've added class declaration for icon-asterisk in icomoon css and less. And updated Isis and Protostar (so, easy to test B/C with hathor and beez3!)

In label layout, i've done a few change:
- a script declaration to check if the icon-asterisk class is set.
- If not, the icon-asterisk class will be replaced by the "old" *.

The goal of this : to allow now to use custom css in a site template to style the required icon.
If a template is not ready for this (you could test with beez or hathor) the * will be used.

@nternetinspired You may fell it better now... I hope! ;-)
@phproberto @brianteeman  i think your will be concerned in keeping a icon-asterisk on required fields, and to be B/C as far as possible! (indeed, improvement about accessibility for all templates)

All comments are welcome, and all error reports too! this is a first try to improve the joomla client-side validation and to allow better styling by removal of the core *.

**Comment by Chalkin** [comment]
@Test - Tested and works like it should.

**Comment by Chalkin** [comment]
Tested and works like it should. Joomla 3.4.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6247">issues.joomla.org/joomla-cms/6247</a>.</sub>

**Comment by infograf768** [comment]
1. As generatecss.php has not been used, isis template-rtl.css is not updated.
2. After running it to correct the template-rtl.css I get

for LTR:
screen shot 2015-03-05 at 09 33 51

for RTL
screen shot 2015-03-05 at 09 35 11


Apart from the fact that `"placement" => "right"` obviously does not fit with RTL, this looks very confusing.

**Comment by infograf768** [comment]
using `"placement" => "bottom"` is a bit better:

screen shot 2015-03-05 at 09 43 16

**Comment by JoomliC** [comment]
@infograf768 Yes, i not have yet run the generate css, due to a personal issue in the local folder i've done this dev... But i will as soon as i have a get the green light to go futher, and so, replace all the * with the icon-asterisk.
As the main purpose of this PR was to improvement client-side validation, i was just using it to test * replacement as it seems to be a commit block....
If it's okay (i mean some PLT, designer, and a few contributors "OK it's all good!"), i will update this one to a clean full PR with client-side improvement (joomla one) + replacement of * by icon (remove the hardcoded "&nbsp;*" from the core layout).
If no feedback soon, i will split this PR in two : 
- one for joomla client-side form validation improvement (as describe in the first topic)
- one for the asterisk removal (this could take too much time before having a succesfull feedback...)

@infograf768 what is you personal opinion about this change, the addition of icon, and the abbr tag with title for accessibility (reader) in a user point of view as well as in a translator expert view ? (Hope you are fine since your "Retraite Joomla" ;-) )

Cyril

**Comment by JoomliC** [comment]
@Chalkin Thank you for your testing! Indeed, this PR is not yet ready to commit, as it introduces at it is today, a major change and could need more feedback before to do all the full changes needed.
But of course, testing and giving feedback is welcome, as well as its B/C compatibility with all templates (admin/site).
;-)

**Comment by Fedik** [comment]
@JoomliC please pay attention on #6294 that also made changes in `validate.js` and it already RTC, 
there the field ordering already fixed

and note about 'Auto-scroll to the system message container',
it is very controversial feature, please do not enable it by default, so extension/template developers will have no problem with it

**Comment by JoomliC** [comment]
@Fedik Thanks, but i wasn't able to know before my PR that the ordering fixed with a PR posted 3 days after mine ;-)

About auto-scroll, i don't see how it could give trouble for an extension form using joomla form-validate, but i miss maybe something... ?

**Comment by Fedik** [comment]
@JoomliC true, you could not know, I just ping you for avoid conflicts :wink: 

about autoscroll  - sometimes very annoying when page "scroll away" from you :smile: 
I mean keep it disabled by default, and add some JS option for enable, so example you can enable it  only on for specific view, and if some extension developer want this to, he also can just enable it via js option

also for some templates can be a problem if it cannot be disabled without hacking, 
example if the message container  somewhere in absolute/fixed position

but it my personal opinion :wink:

**Comment by JoomliC** [comment]
@Fedik And thank you to have point me this PR :+1:  ;-)

I will check all this, and maybe close this PR...

**Comment by JoomliC** [comment]
I close this PR, in order to open new ones, with no conflict with other PR, created before or after this one.

- Removal of colon from labels in com_users : https://github.com/joomla/joomla-cms/pull/6424
- Ordering of invalid field in alert container : https://github.com/joomla/joomla-cms/pull/6294 (PR opened 2 days after this one already merged)
- Removal of hard-coded asterisk "*" in required fields : in process ;-)

**Pull request closed without merging**
