### PR TITLE
Fix invalid string that causes the ini file not to load

### LINKED ISSUE #13541: While install Joomla! the language Danish is not selectable
### Steps to reproduce the issue

1. Use the current version of Joomla! 3.7.0-alpha2 
2. Start a installation and select Danish as installation language.
3. See that the language of the page does not change to Danish.

### Expected result
The language should change form English to Danish.

See also: https://github.com/joomla-projects/joomla-browser/pull/127

### System information (as much as possible)

PHP Built On 	Linux acer 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64
Database Version 	5.7.16-0ubuntu0.16.04.1
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.8-0ubuntu0.16.04.3
Web Server 	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.0-alpha2 dev [ Amani ] 20-December-2016 23:59 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #13541 
closes #13541

### Summary of Changes

remove slash

### Testing Instructions

Attempt to install Joomla from staging branch in da-DK language
See that english language is shown
apply this PR
see that on reload the danish language is now loaded

### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
Hmm i guess '"_QQ_" can be removed completly from this file?

@bakual @infograf768

**Comment by PhilETaylor** [comment]
No idea. I simply fixed the parsing issue

**Comment by infograf768** [comment]
not enough. at least could have been replaced by ; as it is an htmlentity. will look at it

**Comment by infograf768** [comment]
now corrected and merged

**Pull request merged**
