### PR TITLE
[4.0] Replace non-existent language constants with globals

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Delete/replace non-existent language constants with globals.

### Testing Instructions
Code review.
or
Go to Users > User Actions Log
View page source
Search COM_ACTIONLOGS_LIST_FULL_ORDERING
Search COM_ACTIONLOGS_LIST_LIMIT
Apply PR
Above constants translated

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e003b1a02fc745ed98e87d547a2e527cd367819f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25644">issues.joomla.org/tracker/joomla-cms/25644</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e003b1a02fc745ed98e87d547a2e527cd367819f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25644">issues.joomla.org/tracker/joomla-cms/25644</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25644">issues.joomla.org/tracker/joomla-cms/25644</a>.</sub>

**Comment by HLeithner** [comment]
thx and once again please don't create branches in the main repo.

**Pull request merged**
