### PR TITLE
[4.3][csp] Remove inline onclick from the Help button

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Deprecate `Joomla.popupWindow`
- Use data attributes to pass the data from PHP to JS
- Add the required onclick functionality based on the data attributes

### Testing Instructions
This pr needs `npm ci`

Check any page on the backend with a help button that when clicking on it the help window opens as expected 

### Actual result BEFORE applying this Pull Request

Screenshot 2023-01-27 at 15 15 46

### Expected result AFTER applying this Pull Request

Screenshot 2023-01-27 at 15 14 43

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

Where do we register the deprecations?

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e1e6e6ec9893fdd1d21125fd219c2d5e663c2d69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39727">issues.joomla.org/tracker/joomla-cms/39727</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e1e6e6ec9893fdd1d21125fd219c2d5e663c2d69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39727">issues.joomla.org/tracker/joomla-cms/39727</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39727">issues.joomla.org/tracker/joomla-cms/39727</a>.</sub>

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko !

**Comment by heelc29** [comment]
@dgrammatiko @viocassel @Quy
Are you sure this is working? If I click the help button then it will open this url (notice the escaped slashes)
image
the Microsoft Edge (Version 111.0.1661.54) the second one is replaced to two slashes
image
and I will be redirected to the Main Page
image

Without this PR the url is correct (but not working at the moment for J4.3)
image

**Comment by brianteeman** [comment]
The 404 is because @obuisard hasnt set uip the proxy

**Comment by dgrammatiko** [comment]
@heelc29 check #40270

**Comment by obuisard** [comment]
We are working with the documentation team to resolve the missing docs for 4.3.

**Pull request merged**
