### PR TITLE
[5.x] System - Backward Compatibility params

### PR DESCRIPTION
**Pull request by brianteeman**
Display the params correctly

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by HLeithner** [comment]
There is actually a reason why no = green, it's the better state but I understand that it is confusing.

**Comment by brianteeman** [comment]
> There is actually a reason why no = green, it's the better state but I understand that it is confusing.

In which case I would suggest that yes/no are the wrong terms to use

**Comment by HLeithner** [comment]
hmm, what would be a better suggestion?

active / disabled?

or a selectbox?

**Comment by brianteeman** [comment]
There are two different things. What is the state and what is the recommendation.

I would probably go for enabled/disabled for the label and update the description string to explain the recommended state. Of course when you could actually see the descriptions without the stupid button it was much easier.

From what I understand you were using the color green to indicate the recommendation? That was an accessibility failure as you shouldnt use color alone

**Comment by HLeithner** [comment]
I'm happy for any improvement.
Description could (always) be something like:

> If you use extensions which are not using the latest Joomla Coding standard they might need this setting to work.

or 

> If the website uses extensions which needs the legacy layer to work they might need this settings to work.

don't know if any of this is good or bad. But Explaining to the end user where the problem is is pretty useless I think since he or she can't fix it anyway. But can the developer "Hey your extension needs this b/c plugin can you bring it uptodate?"

**Comment by brianteeman** [comment]
I have updated the description of the plugin instead of the description of the options. 

image

**Comment by brianteeman** [comment]
@wilsonge any comments on the changed strings

**Comment by ghazal** [comment]
> I have updated the description of the plugin instead of the description of the options.
> 
> image

+1

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
