### PR TITLE
[4.4] [cli] TasksListCommand fix deprecation when execution = manual

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #43665 .

### Summary of Changes
cover only the cli part
fix deprecation

### Testing Instructions
Create a scheduled task with Execution Rule on Manual
execute the command line scheduler:list

### Actual result BEFORE applying this Pull Request
fix deprecation

### Expected result AFTER applying this Pull Request

no deprecation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brbrbr** [comment]
Works

**Comment by richard67** [comment]
> Works

@brbrbr If you have tested this PR, please mark your result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/43750 by using the blue "Test this" button at the top left corner, then selecting the test result and finally submit. This is needed so that the test result is properly counted. It needs 2 successful tests for each PR to get accepted. You can help with that by marking your test result. Thanks in advance.

**Comment by brbrbr** [comment]
I have tested this item :white_check_mark: successfully on 76f91e9a09e05c281db792bc7e74474abc9a0d16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43750">issues.joomla.org/tracker/joomla-cms/43750</a>.</sub>

**Comment by richard67** [comment]
@brbrbr Thanks for testing.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 76f91e9a09e05c281db792bc7e74474abc9a0d16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43750">issues.joomla.org/tracker/joomla-cms/43750</a>.</sub>

**Comment by richard67** [comment]
@viocassel Thanks for testing.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43750">issues.joomla.org/tracker/joomla-cms/43750</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
