### PR TITLE
[com_actionlogs] - fix checkLoggable for com_checkin

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24071 .

### Summary of Changes
fix `checkLoggable` for com_checkin 

### Testing Instructions
Uncheck the form com_actionlogs  Options  com_checkin from Events To Log

### Expected result
check-in actions are not logged

### Actual result
check-in actions are logged

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8e68899c463633baa2157ce21ebcb111da624d83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24086">issues.joomla.org/tracker/joomla-cms/24086</a>.</sub>

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 8e68899c463633baa2157ce21ebcb111da624d83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24086">issues.joomla.org/tracker/joomla-cms/24086</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24086">issues.joomla.org/tracker/joomla-cms/24086</a>.</sub>

**Comment by HLeithner** [comment]
Why is only com_checkin valid for checking logging?

**Comment by twister65** [comment]
I think, because after onAfterCheckin event.

**Comment by HLeithner** [comment]
Can only com_checking trigger this event or checkin items? Or is this only for the global checkin?

**Comment by brianteeman** [comment]
I "think" the real problem to resolve is that we only want to record in the action logs when someone actively does a checkin - either from the component or by pressing the checkin button in the toolbar.

However what current actionlog does is record every time something is checked in - and that will happen automatically every time you save an item etc and we don't want to log that.

**Comment by alikon** [comment]
with #23526 every table can trigger the `onAfterCheckin` event see https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Table/Table.php#L1149 this pr fix  that till, now everytime a checkin event occurs it is always logged unrespectful for what  you have setted on the Events To Log

**Comment by HLeithner** [comment]
So this should go into 3.9.4?

**Comment by alikon** [comment]
from my personal POV yes, cause is a fix for a bug, but the final decision it's up to the mantainers ...
oops ... are you 😄

**Comment by HLeithner** [comment]
thx

**Pull request merged**
