### PR TITLE
Admin Menu filter by parent

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38150 .

### Summary of Changes
Adds a new parent filter for admin menus

### Testing Instructions
Create a custom admin menu and populate with a few nested menu items for testing
Open filter options and with this PR there is a new filter that lets you filter the menu items by the parent.
Test that the filter works for both site and admin menus

This is the same as seen for site menus

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on fe68bf03a73d93632cae01d08ced87fcf4aee55b<br /><br />Nice feature! Works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38540">issues.joomla.org/tracker/joomla-cms/38540</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on fe68bf03a73d93632cae01d08ced87fcf4aee55b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38540">issues.joomla.org/tracker/joomla-cms/38540</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38540">issues.joomla.org/tracker/joomla-cms/38540</a>.</sub>

**Comment by fancyFranci** [comment]
As this is a new feature, I'll move it to 4.3. I'm sure the new release managers will be happy to have it in their release :)

**Comment by obuisard** [comment]
Great addition, thank you Brian @brianteeman

**Pull request merged**
