### PR TITLE
Module preview styling

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
General styling. Most notable difference is moving positioning from absolute to relative. 

### Testing Instructions
Open frontend with module position preview... https://docs.joomla.org/Finding_module_positions_on_any_given_page

### Before
image

### After
image

### CODE REVIEW

**Comment by brianteeman** [comment]
Before this pr the module preview would display the position even if it is not active on the page. From your screenshot it looks like you had to create a module in order for it to show. ??

This is much more readable but personally I miss the outline of the position

**Comment by ciar4n** [comment]
Nothing has really changed except the styling. Previously when the module was not published, the module position was also echoed as module content. It was not visible because it was covered by the module details (position and style).

I can add back in the outline. My reasoning for removing the outline was that the module width should be evident by the width of the details block. The height equally evident by the following module position.

**Comment by brianteeman** [comment]
I have found the module outline is useful when the template hardcodes something. For example some templates hardcode the search but keep a module nearby

**Comment by ciar4n** [comment]
Something like this suitable?...

image

**Comment by brianteeman** [comment]
This is the extra text I was referring to. It is confusing because it is shown only if the module position is empty

home

I understand that it was there before and that you couldnt see it - but now that you can see it, it looks confusing

**Comment by brianteeman** [comment]
Just saw your new screenshot. Is the styling your own or the default styling for that position?

**Comment by ciar4n** [comment]
I have removed the content = position if the module is not published. Kittens die when I start diving to deep in to php so might be a good idea if someone could double check that commit.

**Comment by brianteeman** [comment]
Thanks - looks much better without the module name visible

**Comment by ciar4n** [comment]
That styling would be separate to the module styling. Similar to the previous outline.

**Comment by brianteeman** [comment]
That would be great then - thank you

**Comment by ciar4n** [comment]
Module outline added as seen in previous screenshot

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6efa10091be051054365f5084606ee3fdce9db31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22272">issues.joomla.org/tracker/joomla-cms/22272</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6efa10091be051054365f5084606ee3fdce9db31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22272">issues.joomla.org/tracker/joomla-cms/22272</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22272">issues.joomla.org/tracker/joomla-cms/22272</a>.</sub>

**Pull request merged**
