### PR TITLE
[4.0] htaccess.txt clarifications

### PR DESCRIPTION
**Pull request by brianteeman**
Updated the comments in the htaccess file to make it clearer that the modules referred to are Apache modules and not Joomla modules

(I just had someone asking why joomla didnt ship with mod_rewrite installed like all the other modules)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3588dff07b1e55fbf8850b5f6a6d3b3cfce9d966<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25737">issues.joomla.org/tracker/joomla-cms/25737</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3588dff07b1e55fbf8850b5f6a6d3b3cfce9d966<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25737">issues.joomla.org/tracker/joomla-cms/25737</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25737">issues.joomla.org/tracker/joomla-cms/25737</a>.</sub>

**Comment by brianteeman** [comment]
The Joomla 3 version of this change has now been merged

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thnks

**Pull request merged**
