### PR TITLE
[4.0] webp banners

### PR DESCRIPTION
**Pull request by brianteeman**
Adds support for webp images in com_banners

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b4f65095d8e3b7d3c9a6bd7fe533f795ae766e03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34027">issues.joomla.org/tracker/joomla-cms/34027</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b4f65095d8e3b7d3c9a6bd7fe533f795ae766e03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34027">issues.joomla.org/tracker/joomla-cms/34027</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34027">issues.joomla.org/tracker/joomla-cms/34027</a>.</sub>

**Comment by ChristineWk** [comment]
Not sure, but on line 47 I see this here:

`* @return  boolean  True if an image of type bmp, gif, jp(e)g or png, false otherwise`

**Comment by richard67** [comment]
> Not sure, but on line 47 I see this here:
> 
> `* @return boolean True if an image of type bmp, gif, jp(e)g or png, false otherwise`

@ChristineWk Not related to this PR, but you are right, it should be "True if file of type swf, false otherwise".

@brianteeman Do you wanna fix it with this PR here? Or make a new one?

**Comment by brianteeman** [comment]
@richard67 actually there was another PR addressing that - I just forgot to submit it. Doing that now in a new pr

**Pull request merged**
