### PR TITLE
Update lib_joomla.ini

### PR DESCRIPTION
**Pull request by MartijnMaandag**
Pull Request for Issue #36959 .

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2db078259e7c8a46cb31ceebdfe874ad9cf87b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36964">issues.joomla.org/tracker/joomla-cms/36964</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2db078259e7c8a46cb31ceebdfe874ad9cf87b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36964">issues.joomla.org/tracker/joomla-cms/36964</a>.</sub>

**Comment by zero-24** [comment]
@MartijnMaandag can you do a PR against 3.10 too or should I? Its the same string thats wrong there too so we can merge it up from there. Just changing the branch didnt worked out.

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36964">issues.joomla.org/tracker/joomla-cms/36964</a>.</sub>

**Comment by MartijnMaandag** [comment]
@zero-24 Can you do it, I am not that experienced ;-)

**Comment by zero-24** [comment]
No problem. PR done here: https://github.com/joomla/joomla-cms/pull/36969 closing here so it can be merged up from 3.10 into 4.1 and 4.2

**Pull request closed without merging**
