### PR TITLE
Solving #5864: Language Manager: Override. Preventing saving reserved words as constant

### PR DESCRIPTION
**Pull request by infograf768**
See #5864
Edit or create a language override through Language Manager.
Enter in the "Language Constant" field one of the reserved words:
YES, NO, NULL, FALSE or TRUE for example.
Save.
You will get a Fatal error:

> Fatal error: Maximum function nesting level of '100' reached, aborting! in /Applications/MAMP/htdocs/trunkgitnew/libraries/joomla/language/language.php on line 1160

Delete the overrride ini file which was created and patch:

You will get:
screen shot 2015-01-23 at 09 48 42

### CODE REVIEW

**Comment by brianteeman** [comment]
It is better for the language string to change the word should to can't

+COM_LANGUAGES_OVERRIDE_ERROR_RESERVED_WORDS="YES, NO, NULL, FALSE, ON, OFF, NONE, TRUE are reserved words and should not be used as language constants."

should not be used = implies it is bad practice to do so but there is no problem if you do. Whereas in reality you can't use them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5877">issues.joomla.org/joomla-cms/5877</a>.</sub>

**Comment by Hils** [comment]
In another place I believe we agreed that can't should be written in full as cannot.

**Comment by brianteeman** [comment]
We agreed the opposite ;)

On 23 January 2015 at 09:45, Hils <notifications@github.com> wrote:

> In another place I believe we agreed that can't should be written in full
> as cannot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5877#issuecomment-71169564>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Corrected.

**Comment by brianteeman** [comment]
OOps Hils I am not sure we did ever make a decision on that word - moving
to the en-GB issue list to discuss that

On 23 January 2015 at 09:57, Brian Teeman <brian@teeman.net> wrote:

> We agreed the opposite ;)
>
> On 23 January 2015 at 09:45, Hils <notifications@github.com> wrote:
>
>> In another place I believe we agreed that can't should be written in full
>> as cannot.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/5877#issuecomment-71169564>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
My mistake the change to standardise on can't is in the big PR that isnt
applied yet

On 23 January 2015 at 10:05, Brian Teeman <brian@teeman.net> wrote:

> OOps Hils I am not sure we did ever make a decision on that word - moving
> to the en-GB issue list to discuss that
>
> On 23 January 2015 at 09:57, Brian Teeman <brian@teeman.net> wrote:
>
>> We agreed the opposite ;)
>>
>> On 23 January 2015 at 09:45, Hils <notifications@github.com> wrote:
>>
>>> In another place I believe we agreed that can't should be written in
>>> full as cannot.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/joomla/joomla-cms/pull/5877#issuecomment-71169564>.
>>>
>>
>>
>>
>> --
>> Brian Teeman
>> Co-founder Joomla! and OpenSourceMatters Inc.
>> http://brian.teeman.net/
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Honestly, between cannot and can't, this is really fishing for useless details.
Please rather confirm if the PR is working for you or not.

**Comment by brianteeman** [comment]
With the language string as Should then no I can not confirm as it is not
the correct message

On 23 January 2015 at 10:09, infograf768 <notifications@github.com> wrote:

> Honestly, between cannot and can't, this is really fishing for useless
> details.
> Please rather confirm if the PR is working for you or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5877#issuecomment-71172401>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bluezeyes** [comment]
The check works for me.
Manually pasted patch into com_languages/models/overwrite.php
Try to save keys named YES, NO, TRUE, FALSE, ON, OFF, NULL
(Maybe they should mentioned in this order in the message)

Result: Save process is canceled, Error Message was presented.

**Comment by anibalsanchez** [comment]
@test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5877">issues.joomla.org/joomla-cms/5877</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for correcting the string

**Comment by zero-24** [comment]
Moving to RTC Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5877">issues.joomla.org/joomla-cms/5877</a>.</sub>

**Pull request merged**
