### PR TITLE
[5.3] Remove TODO joomla-alert.scss

### PR DESCRIPTION
**Pull request by brianteeman**
While reviewing existing @todo I came across these two.

The first one is not needed as the variable has the same value The second one makes no sense

@coolcat-creations these were your todo comments from https://github.com/joomla/joomla-cms/pull/42986 - have I missed something or can they simply be removed

### Testing Instructions
code review

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Sorry I don't understand these TODOS anymore ;(
next time I need to write why or so... I think it can be removed.

**Comment by brianteeman** [comment]
Thanks for confirming. You are not alone of the 300+ todo many of them make no sense at all and have been there for a very very long time

**Comment by fgsw** [comment]
@brianteeman I wanted to test by download prepbuild package as it has the "NPM Resource Changed" label but could not find ```build/media_source/templates/administrator/atum/scss/vendor/joomla-custom-elements/joomla-alert.scss``` in the package.

**Comment by brianteeman** [comment]
@fgsw files in the build/ folder and not distributed. They are used to create the css files found in the media/ folder

**Comment by fgsw** [comment]
Thanks for information that the pull request can't get a test by prebuilt package.

**Comment by rdeutz** [comment]
I agree that todos are often not useful, I will put this on the maintainers agenda, I think a todo should contain a version we have to work on the todo, a description and maybe a reason.

**Comment by brianteeman** [comment]
@rdeutz in this specific case the person who wrote the todo states she doesnt know why

**Comment by rdeutz** [comment]
understandable after months/years, if we force people to write more about the todo changes are goodl that they know why

**Comment by rdeutz** [comment]
Thanks

**Comment by brianteeman** [comment]
> understandable after months/years, if we force people to write more about the todo changes are goodl that they know why

hence my comment on your todo yesterday ;)

**Pull request merged**
