### PR TITLE
Sticky to pinned

### PR DESCRIPTION
**Pull request by brianteeman**
in the banner manager (and isis) we have a horrible term Sticky. It is particularly horrible as the negative is unsticky which I am pretty sure is not a word.

And sometimes we use the word pinned. This PR makes it consistent to always use pinned and unpinned.

(Discussed in the en-GB user interface text group)

### CODE REVIEW

**Comment by wilsonge** [comment]
@test much better wording. One more tester

**Comment by pe7er** [comment]
@test works.

Note that the term sticky is also used in the PHP source code, e.g. 
in controllers e.g. $this->registerTask('sticky_unpublish', 'sticky_publish');
and models, helper files, and tmpl files:
<?php echo JHtml::_('searchtools.sort', 'COM_BANNERS_HEADING_STICKY', 'a.sticky', $listDirn, $listOrder); ?>
So changing it might lead to another "Finder / Smart Search" confusion :-)

btw: I like the change to pinned and unpinned.

**Comment by waader** [comment]
The term sticky remains in the column heading and in mod_banner.

**Comment by brianteeman** [comment]
There are lots of times we use a term in the code that is not matched by
the term in the strings. Unfortunately we are stuck with that for B/C.

**Comment by brianteeman** [comment]
@waader thanks I will check that

**Comment by waader** [comment]
And here in the ordering too.

**Comment by brianteeman** [comment]
@waader I had an issue with my repo - had to make a new PR to fix it - #5857 - should have fixed all the issues you sotted now. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5857">issues.joomla.org/joomla-cms/5857</a>.</sub>

**Comment by brianteeman** [comment]
Oops new PR is #5865<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5857">issues.joomla.org/joomla-cms/5857</a>.</sub>

**Pull request closed without merging**
