### PR TITLE
[4.2] content history alerts

### PR DESCRIPTION
**Pull request by brianteeman**
Converts from the ugly browser dependent alerts to use the joomla rendermessage

## To test
run npm build:js or use a prebuilt package

Create and save an article and then edit it and save again Click on Versions
Click on all versions and then preview
Click on all versions and then restore
Click on one version and then compare

### before - ugly alerts
image

### after - joomla less ugly

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 124d1675caa36dca64ed4da6d0b8e7edc245dec2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39611">issues.joomla.org/tracker/joomla-cms/39611</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 124d1675caa36dca64ed4da6d0b8e7edc245dec2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39611">issues.joomla.org/tracker/joomla-cms/39611</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39611">issues.joomla.org/tracker/joomla-cms/39611</a>.</sub>

**Comment by brianteeman** [comment]
thanks for the quick tests and merge

**Pull request merged**
