### PR TITLE
Setting proper default values for access level

### LINKED ISSUE #7311: REGRESSION - default user groupd on new category and/or content
I have not been able to replicate this myself but there are multiple reports on the forum.

Basically when creating a new article or category the access is being set to Guest and not public.

See http://forum.joomla.org/viewtopic.php?f=706&t=890720&p=3314030#p3314030

### PR DESCRIPTION
**Pull request by Bakual**
Fixes #7311 
### Issue

Module, Article and Category creation applies a wrong default values for the access level. Instead of the one from the global config it just takes none, and thus the first in the list is selected.
This is a regression introduced with #6966 and some similar PRs.
### Solution

Set the correct default value.
### Testing
- Create an article/module/category and see the preselected access level. If your default one is the first in the list, change it to something else first.
- Before patch, always the first access level is selected. After patch the default one from the config is preselected.

### CODE REVIEW

**Comment by nonumber** [comment]
You need to check the $filters['access'] for being an empty string too.
The ```isset($filters['access'])``` will return true even if empty (as $filters is an array).
So you need to do: ```(isset($filters['access']) && $filters['access'] !=''````

**Comment by infograf768** [comment]
@nonumber
Although you are theoritically right, it looks like working as is.

**Comment by Bakual** [comment]
@infograf768 @nonumber is right. To reproduce activate a search filter. Like one for the categories, then it breaks the access again.

**Comment by nonumber** [comment]
Not only theoretically, also practically :)
It is not working for me without the extra check.
This can be due to difference in PHP version (isset() functions a bit differently across versions).

**Comment by infograf768** [comment]
>This can be due to difference in PHP version (isset() functions a bit differently across versions).

yep.

**Comment by Bakual** [comment]
I changed it to use `!emtpy()` instead, it should do the same as Peter suggested.

I also changed it for the other lines there.

**Comment by nonumber** [comment]
Yes, works for me
I assumed empty() would complain when the key is not found at all, but it doesn't :)

@test: All good

**Comment by infograf768** [comment]
@test
Works fine here.

**Comment by Bakual** [comment]
`empty()` is a boolean check with an `isset()` integrated :smile:

**Pull request merged**
