### PR TITLE
[4.0][com_installer] Fix width of Name column

### LINKED ISSUE #29766: [4.0] Updates page badly laid out so name of extension is only one word wide
### Steps to reproduce the issue

install Akeeba Backup 7.1.4
Go to the extension updates page
click find updates

### Expected result

Something laid out better than it is

### Actual result

The "Name" column is only wide enough for a single word, meaning Akeeba Backup Core package is shown as 

```
Akeeba 
Backup 
Core 
package
```

The URL and the information link could be simple buttons with pop overs, or links to the urls, that would save a lot of space. 

Screenshot 2020-06-22 at 22 30 38

screenshot is 1600px x 1600px (half a 27inch iMac retina screen) 

// Sorry @nikosdion for picking on you ;-) 

### Bonus

There is a useless popover on the name, that just shows the name again

Screenshot 2020-06-22 at 22 32 39

### PR DESCRIPTION
**Pull request by Quy**
Closes #29766 .

### Summary of Changes
Combine columns to increase width of Name column.

### Testing Instructions
Install an extension that requires updating (https://github.com/C-Lodder/joomla4-backend-template/releases Version 0.0.16)
Go to System > Update > Extensions

### Actual result BEFORE applying this Pull Request
Details URL column exists.

### Expected result AFTER applying this Pull Request
Details URL column gone and its info displayed under Name column.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ab077d157c90648f8dd199b256d6e99e06fbcdb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29772">issues.joomla.org/tracker/joomla-cms/29772</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ab077d157c90648f8dd199b256d6e99e06fbcdb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29772">issues.joomla.org/tracker/joomla-cms/29772</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29772">issues.joomla.org/tracker/joomla-cms/29772</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
