### PR TITLE
Update en-GB.com_joomlaupdate.ini

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Capitalise strings and rename to match ftp setting stings in global configuration

FTP host = >FTP Host

FTP port => FTP Port

FTP username => FTP Username

FTP password => FTP Password

FTP folder = > FTP Root

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 67b40da77736d8abbefc6aaadf9b18953022ed5b<br /><br />Looks good to me. Thanks Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9476">issues.joomla.org/joomla-cms/9476</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 67b40da77736d8abbefc6aaadf9b18953022ed5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9476">issues.joomla.org/joomla-cms/9476</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 67b40da77736d8abbefc6aaadf9b18953022ed5b<br /><br />On review - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9476">issues.joomla.org/joomla-cms/9476</a>.</sub>

**Comment by brianteeman** [comment]
RTC
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9476">issues.joomla.org/joomla-cms/9476</a>.</sub>

**Pull request merged**
