### PR TITLE
Update en-GB.com_newsfeeds.ini

### PR DESCRIPTION
**Pull request by MartijnMaandag**
Pull Request for Issue # .

### Summary of Changes
Feed must be plural?

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 468b1e794fca9cdbd63a5dd30245e9fcca6cb582<br /><br />If you test the option with a live feed you will see that the ordering applies to the items in a feed
It is not the ordering of different feeds<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18846">issues.joomla.org/tracker/joomla-cms/18846</a>.</sub>

**Comment by MartijnMaandag** [comment]
Yes but it is also used as default for all the feeds (it is in the options part and named "Feed Display Order".
To make it clear we could change the text from "The order used to display the feed." into "The order used to display the items in the feed."?

**Comment by Quy** [comment]
Let's close it. Please note that this string is no longer in J4.

**Comment by ghost** [comment]
closed as stated above. @MartijnMaandag please reopen if i'm wrong.

**Pull request closed without merging**
