### PR TITLE
typo in sample data

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #15515 

Simple typo

### CODE REVIEW

**Comment by PhilETaylor** [comment]
So you changed ONE out of the THREE typos?

**Comment by PhilETaylor** [comment]
`real email address.You` still needs doing :)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ac5b667e33dd3bdc81dd1a8719968ef347e8517<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15520">issues.joomla.org/tracker/joomla-cms/15520</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 1ac5b667e33dd3bdc81dd1a8719968ef347e8517<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15520">issues.joomla.org/tracker/joomla-cms/15520</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
