### PR TITLE
[4.0] Namespace admin system template

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the namespacing work

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 85ec7deb3840a1c0dafda5833ec741abbf0227b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21245">issues.joomla.org/tracker/joomla-cms/21245</a>.</sub>

**Comment by brianteeman** [comment]
(currently unable to connect to ci.joomla.org to see what the drone errors are)

**Comment by brianteeman** [comment]
Drone error is unrelated to this pr

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
