### PR TITLE
[4.0] Delete unused strings

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.
Confirm that string constants are not being used.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 85bfc843e1c3b89d63d71b40401914ccb5bc3955<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33974">issues.joomla.org/tracker/joomla-cms/33974</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on 85bfc843e1c3b89d63d71b40401914ccb5bc3955<br /><br />These 2 String constants are not being used anywhere in code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33974">issues.joomla.org/tracker/joomla-cms/33974</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33974">issues.joomla.org/tracker/joomla-cms/33974</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
