### PR TITLE
removed seemingly unneeded &

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
removed extra space and seemingly unnecessary &

### Testing Instructions
diff html output with and without &

### Expected result
no change.

### Actual result
https://www.diffchecker.com/RBOmOouV ( the marked section is literally identical even though it says its not )  
if a var_dump is done of the $item compared to & $item and then a diff of that there is no diff at all.

### CODE REVIEW

**Comment by N6REJ** [comment]
@wilsonge I believe you wrote that line?

**Comment by brianteeman** [comment]
Wouldnt it also therefore be wrong at line 79 as well?

**Comment by dgt41** [comment]
@N6REJ `&` means assign by reference, removing it and you are cloning the variable (slower)

**Comment by N6REJ** [comment]
@dgt41 oh ok.. so is it better as is, or as &$item ?

**Comment by Quy** [comment]
Do a search for `$this->item = &$item;` to find 7 instances. I would change `$this->item = & $item;` to `$this->item = &$item;` to match the others.

**Comment by brianteeman** [comment]
for the reasons stated above by @dgt41 I am closing this as not a bug

**Pull request closed without merging**
