### PR TITLE
[5.0] Realistic test for import maps

### PR DESCRIPTION
**Pull request by dgrammatiko**
THIS SHOULD NOT BE MERGED. IT'S JUST FOR DEMOING THE IMPORT MAPS

### Summary of Changes

Check the showon script: it's split to 2 files, the class and the initiator 

### Testing Instructions

Open the global config and check that the Site Offline still works

### Expected result AFTER applying this Pull Request

Screenshot 2023-06-22 at 22 39 29

Screenshot 2023-06-22 at 22 40 16

@HLeithner

### CODE REVIEW

**Comment by HLeithner** [comment]
for easier diff read:
https://github.com/Fedik/joomla-cms/compare/esm-iimportmap...dgrammatiko:joomla-cms:esm-iimportmap

**Comment by HLeithner** [comment]
thanks

**Comment by HLeithner** [comment]
can you please resolve the conflicts #40714 has been merged

**Comment by dgrammatiko** [comment]
Replaced by #41034

**Pull request closed without merging**
