### PR TITLE
[4.0] fix play icon

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #31571

See original issue for how to replicate the issue

To test run npm ci and refresh

obvious error

### CODE REVIEW

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on 9b4f015a9cbef21799f2da81ddc0bf873e3ed29b<br /><br />Simple bug, simple fix. Thank you! :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31574">issues.joomla.org/tracker/joomla-cms/31574</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9b4f015a9cbef21799f2da81ddc0bf873e3ed29b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31574">issues.joomla.org/tracker/joomla-cms/31574</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31574">issues.joomla.org/tracker/joomla-cms/31574</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by brianteeman** [comment]
thx

**Pull request merged**
