### PR TITLE
[4.0] Update bootstrap version

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
I think as long as we're in full development mode, we should stay up to date to the current version of bootstrap.

### Testing Instructions
Run "npm i" and test bootstrap scripts and layouts used in Joomla!

### CODE REVIEW

**Comment by wilsonge** [comment]
System Tests are repeatedly failing here so I assume this is breaking things

**Comment by bembelimen** [comment]
Not sure, why this happens....
It tries to click on the coordinates (1213, 139) to go to the server area in the global config. Measuring this coordinate in a 1920x1080 screenshot delivers:
grafik

(the bottom right corner is the coordinate), looks good to me + the server tab becomes active when testing this point in the backend..... any ideas?

**Comment by bembelimen** [comment]
Thanks @dneukirchen for fixing the error

**Comment by wilsonge** [comment]
Can you please update the package-lock file too for this change - it should match the package.json - right now you're not actually updating the bootstrap version - just increasing the range of versions available

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
