### PR TITLE
Implement component params for fieldgroups

### PR DESCRIPTION
**Pull request by rdeutz**
## Summary of Changes

This is pretty much the same as #15915 but only for field groups.

Com_categories has a nice little feature which allows the component developer to place a form file on /administrator/components/com_foo/models/forms/category.xml which get loaded when editing a category.

This pr introduces the same functionality for com_fields. If a file is found on the location /administrator/components/com_foo/models/forms/fieldgroup/item.xml then this file get loaded when the entity com_foo.bar is edited.

You have to name the fields params

```xml
<?xml version="1.0" encoding="utf-8"?>
<form>
    <fields name="params">
        <fieldset name="basic">
            <field
                    name="display"
                    type="text"
                    default=""
            />
        </fieldset>
    </fields>
</form>

```

### Testing Instructions

Put the xml in a component with custom fields support into 
/administrator/components/com_foo/models/forms/fieldgroup/item.xml

Item is the section, check https://docs.joomla.org/J3.x:Adding_custom_fields/Implement_into_your_component for details  

### Expected result

You should see a new tab Options in your fieldgroup edit form

optionen

Documentation Changes Required

Would be nice to have that feature documented.

### CODE REVIEW

**Comment by mbabker** [comment]
Needs the install SQL but seems fine to me.  If this can get tested today and tomorrow don't see any reason not to merge.

**Comment by rdeutz** [comment]
grrr, adding the install sql, I was sure I have forgotten something but couldn't figure out what :-)

**Comment by nielsnuebel** [comment]
Looks good for me. Everything works

**Comment by laoneo** [comment]
Should the update files not contain 3.8.0 as version number and end with a new line?

**Comment by rdeutz** [comment]
Ofc, they should :-)

-- 
Viele Grüße/ Best Regards 
Robert

Am 28. Juli 2017 um 21:51:02, Allon Moritz (notifications@github.com) schrieb:

Should the update files not contain 3.8.0 as version number and end with a new line?

**Review by mbabker — APPROVED** [review]

**Comment by infograf768** [comment]
I tried this on com_content and can't show the new field.

**Comment by nielsnuebel** [comment]
@infograf768 change item.xml to article.xml .

**Comment by infograf768** [comment]
Got it and I do get a new Option tab when editing a fieldgroup. But what can be the use of other Options in the fieldgroup itself? Any example that makes sense?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 298ffab4147cf015fb5128e27a326b130886c236<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17317">issues.joomla.org/tracker/joomla-cms/17317</a>.</sub>

**Comment by infograf768** [comment]
RTC as it works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17317">issues.joomla.org/tracker/joomla-cms/17317</a>.</sub>

**Comment by infograf768** [comment]
@mbabker 
Ready to go.

**Comment by rdeutz** [comment]
Think about a component where you have different fieldgroups, any of them should work a little bit different. With having the ability to add fields to the formgroup you can save the information how they should behave. Then you have to pick up the information in your overwrite/component and act accordingly.

**Comment by rdeutz** [comment]
Thanks all who have been worked on this :-)

**Pull request merged**
