### PR TITLE
[4.0-dev] Add css style for mod_articles_news vertical layout

### PR DESCRIPTION
**Pull request by drmenzelit**
Added css styling for mod_articles_news vertical layout (similar to already merged changes for mod_articles_news horizontal layout).

### Summary of Changes
Remove list style and padding for the list
Make image 100% width

### Testing Instructions
Install PR and run npm ci or npm run build:css
Create a newsflash module on position sidebar-right or sidebar-left. Select vertical layout.

### Actual result BEFORE applying this Pull Request
The articles have a padding on the left and a disc symbol (list style)
Screenshot_2020-09-28 News-Vert

### Expected result AFTER applying this Pull Request
The articles have no padding on the left and no list style
Screenshot_2020-09-28 News-Vert-2

### CODE REVIEW

**Comment by paternax** [comment]
Test successful

**Comment by richard67** [comment]
@paternax Could you go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/30797 and mark your test result by using the "Test this" button, choosing the appropriate result and then submit? Thanks in avdance.

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on daaaae4140e44f46d9417bdf14a35fb0c345a9b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30797">issues.joomla.org/tracker/joomla-cms/30797</a>.</sub>

**Comment by richard67** [comment]
Thanks

**Comment by joomlacorner** [comment]
I have tested this item :white_check_mark: successfully on daaaae4140e44f46d9417bdf14a35fb0c345a9b0<br /><br />Patch work as expected. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30797">issues.joomla.org/tracker/joomla-cms/30797</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30797">issues.joomla.org/tracker/joomla-cms/30797</a>.</sub>

**Comment by HLeithner** [comment]
why has this PR 40 Commits?!

**Comment by drmenzelit** [comment]
Probably my mistake :-(

**Comment by richard67** [comment]
> why has this PR 40 Commits?!

@HLeithner and other maintainers who might check this PR: I was a bit surprised, too. But the changes look OK on GitHub, nothing more than expected, so if this PR here is merged with a squash commit, it should be ok. Probably the branch of this PR was not based on an up to date 4.0-dev branch or a temporarilty modified 4.0-dev branch. That's hard to recover now.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
