### PR TITLE
Fix inline comment and remove blank lines that are not needed

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Fix inline comment and remove blank lines that are not needed

### Testing Instructions

review and drone passes as no production code is changed

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3e9979baad64aa0729642b5ab453381fc44d2a21<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17539">issues.joomla.org/tracker/joomla-cms/17539</a>.</sub>

**Comment by akritianand** [comment]
I have tested this item :white_check_mark: successfully on fe7d4ff07711a15b55ca32d66cd3fe1b52db9762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17539">issues.joomla.org/tracker/joomla-cms/17539</a>.</sub>

**Comment by ghost** [comment]
@Quy can you please retest?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4719042a9ee9331495724900728a9c140f6b69fd<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17539">issues.joomla.org/tracker/joomla-cms/17539</a>.</sub>

**Comment by ghost** [comment]
thanks @Quy 
RTC after two successful tests.

**Pull request merged**
