### PR TITLE
[4.0] [plg_privacy_contact] Parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds parameterized queries.

### Testing Instructions

Simple queries, code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8b4aabbc384502aae4eb4109b03822dc0c7337ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29629">issues.joomla.org/tracker/joomla-cms/29629</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8b4aabbc384502aae4eb4109b03822dc0c7337ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29629">issues.joomla.org/tracker/joomla-cms/29629</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29629">issues.joomla.org/tracker/joomla-cms/29629</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
