### PR TITLE
[4.0] Installation languages model install articles with real null value for publish down time

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This is a follow up to recently merged PR's which changed datetime columns in database for real null values.

It makes sure that the `addArticle` routine in file `installation/src/Model/LanguagesModel.php` does not add any article with an old fashioned null value (which might be invalid on newer versions of MySQL databases depending on server and session settings) for any datetime column in database.

### Testing Instructions

Code review should be enoug: Check that in the file modified by this PR there is no other place where an old fashioned null datetime is written to database.

### Expected result

No old fashioned null datetime is written to database.

### Actual result

Old fashioned null datetime is written to database for the published down time of articles.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 71229ebe6e566999f070a9e0aac670fd2abaf8fa<br /><br />LGTM 
code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26778">issues.joomla.org/tracker/joomla-cms/26778</a>.</sub>

**Comment by infograf768** [comment]
Folks, most of this file has to be deleted as we do not propose anymore setting multilang during installation but only through the Multilingual Sample Data plugin.
Therefore the addArticle method is obsolete as many of the methods there.

**Comment by richard67** [comment]
@infograf768 Which other functions are obsolete? Should I make a new PR to remove all unused stuff from this file and close this PR here?

**Comment by infograf768** [comment]
> Should I make a new PR to remove all unused stuff from this file and close this PR here?

yep.

To find out which methods are definitely obsolete, I suggest to compare the methods used in the multilang sample data plugin (as I originally copied the ones from LanguagesModel) and the methods in this LanguagesModel.
It should concern all the methods from `private function enablePlugin($pluginName)` line 485 and after in the plugin.

**Comment by richard67** [comment]
@infograf768 Thanks, I'll do that later.

**Comment by richard67** [comment]
Closing for reasons stated above: [https://github.com/joomla/joomla-cms/pull/26778#issuecomment-546582328](https://github.com/joomla/joomla-cms/pull/26778#issuecomment-546582328).

New PR to remove obsolete multilingual installation stuff will come.

**Comment by richard67** [comment]
@alikon Sorry for having wasted your time, and thanks for other tests and reviews in my other PR's.

**Comment by alikon** [comment]
no problem at all ....it's always better to have different eyes looking at things :+1:

**Pull request closed without merging**
