### PR TITLE
Fix FF40 odd select behavior

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Steps to reproduce the issue

You should have some kind of content that includes (a form with) a html select element. For testing you could create a custom html module containing just a select element with two options. [Edit: See next post for demo code]
Set Mouse over Edit icons to Modules and menus (in System > Global configuration)
Then, using Firefox (Windows or Mac) log into the front end as an admin and navigate to your module. Click the select element and try to select the second option.
#### Testing

Apply the patch and see if this is fixed

### CODE REVIEW

**Comment by justinherrin** [comment]
Applied the patch and tested good in Firefox 40. Other browsers tested good too. :+1:

**Comment by Bakual** [comment]
Why do you just comment the line? Just remove it completely instead. And also remove the related comment on the line above.

**Comment by infograf768** [comment]
Wprks OK here.
screen shot 2015-08-13 at 16 39 25

Just curious: what is necessary to add in the html module to get the nice chosen style?

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7689">issues.joomla.org/joomla-cms/7689</a>.</sub>

**Comment by dgt41** [comment]
@infograf768 you have to add 
```php
JHtml::_('formbehavior.chosen', 'select');
```
in order to load the script and set the appropriate selector (e.g. select).

**Comment by infograf768** [comment]
Was trying to do that with sourcerer, but did not work. Had to add it in template index.php

**Comment by Kubik-Rubik** [comment]
Thank you @dgt41. Merged!

**Comment by arthurgr** [comment]
Has anyone experienced the exact same issue in Drupal 7?

**Pull request merged**
