### PR TITLE
[4.0] [plg_system_cache] Fix debug with page caching enabled

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Loads a document into application for plugins that expect it to be available in `onAfterRespond` event.

### Testing Instructions

Enable Debug System option in Global Configuration.
Enable System - Page Cache plugin.
Enable System - Debug plugin.
As a guest view the same page in frontend at least twice.

### Expected result

No errors.

### Actual result

>Call to a member function getType() on null 

### Documentation Changes Required

Page caching and `onPageCacheSetCaching` event moved from `onAfterInitialise` to `onAfterRoute`.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2e3ab6f43f5bb76ff167b8aa98ec011e03f96b20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27166">issues.joomla.org/tracker/joomla-cms/27166</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9b215ba47eb8ba5b2a6be349a451d2fc255037be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27166">issues.joomla.org/tracker/joomla-cms/27166</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9b215ba47eb8ba5b2a6be349a451d2fc255037be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27166">issues.joomla.org/tracker/joomla-cms/27166</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27166">issues.joomla.org/tracker/joomla-cms/27166</a>.</sub>

**Pull request merged**
