### PR TITLE
[com_finder] index view: Add content map filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR adds a new filter to the com_finder (smart search) index view.

image
#### Testing Instructions
1. Apply patch
2. Go to Smart Search -> Indexed Content and test the new filter.

### CODE REVIEW

**Comment by chrisdavenport** [comment]
How does the drop-down perform when you have hundreds of options in it?

**Comment by brianteeman** [comment]
Probably quite badly based on the previous performance issues with a chosen select

**Comment by andrepereiradasilva** [comment]
@chrisdavenport to be honest just tested with joomla sample data index (46 items) with no notice change in page speed rendering.

Will try to test tomorrow with more items.

**Comment by andrepereiradasilva** [comment]
just tested with a randfom generated 5000 items content map! 200ms difference. Also a bit of 100ms opening the filter. The search is instant. I'm talking of similuting a huge 5000 content map tree...

I don't have a huge search index database to test more properly. @chrisdavenport do you have it?

**Comment by andrepereiradasilva** [comment]
we could also do as the frontend and add the same filters the frontend have, instead of a all in one content map filter.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a10733e1d0034bcfaadc8de32b9a831edebf1673<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10256">issues.joomla.org/joomla-cms/10256</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on a10733e1d0034bcfaadc8de32b9a831edebf1673<br /><br />looks good to me. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10256">issues.joomla.org/joomla-cms/10256</a>.</sub>

**Comment by zero-24** [comment]
Works an look good now -> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10256">issues.joomla.org/joomla-cms/10256</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva and testers!

**Comment by zero-24** [comment]
please remove the label @joomla-cms-bot

**Pull request merged**
