### PR TITLE
Fix showon notice

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13487.

### Summary of Changes

Fix showon notice

### Testing Instructions

1. Apply patch
2. go to Content > Articles > Options and no notice error.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on d6219ac06c7c6fdf94d8c12bcaff38d6645cb88e<br /><br />Test success.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by joomdonation** [comment]
This PR fixed the issue. However, I still have question if anyone knows the answer

Do we really need this block of code https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/component/tmpl/default.php#L60-L64 ?

As I understand showon is used for fields only, so I don't know why we need that block of code to check showon for fieldsets?

**Comment by andrepereiradasilva** [comment]
IIRC you can showon a fields set based on a option too

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on d6219ac06c7c6fdf94d8c12bcaff38d6645cb88e<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by joomdonation** [comment]
That is not correct. 

1. I tried to add showon="sef_advanced:1" to https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/config.xml#L1033 but it doesn't work. Permissions tab is not being shown when I change URL Routing between Modern and Legacy

2. There is also notice if we add showon to fieldset

See this screenshot 
warning

So either it is not supported or if it is supported, there would still be notice like in my screenshot

**Comment by joomdonation** [comment]
OK. Checked it more and see that showon support fieldset, too. However, there is still bug in your code prevents it to work and causes the notice 

You need to change **$fieldSet->formControl** in this line of code https://github.com/andrepereiradasilva/joomla-cms/blob/d6219ac06c7c6fdf94d8c12bcaff38d6645cb88e/administrator/components/com_config/view/component/tmpl/default.php#L63 to **$this->form->getFormControl()** and everything will work as expected

**Comment by joomdonation** [comment]
I have tested this item :red_circle: unsuccessfully on d6219ac06c7c6fdf94d8c12bcaff38d6645cb88e<br /><br />I have to update my test result. It is still not working as expected, see my comment above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by Bakual** [comment]
> As I understand showon is used for fields only, so I don't know why we need that block of code to check showon for fieldsets?

showon is available for fieldsets since 3.6.0 (https://github.com/joomla/joomla-cms/pull/9668)

**Comment by joomdonation** [comment]
Thanks Thomas. I tested and saw it.

**Comment by andrepereiradasilva** [comment]
@joomdonation i will check this better when i have some time later. thanks for your tests

**Comment by andrepereiradasilva** [comment]
@joomdonation can you test now?

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 46fc70d6b59a88074afe77548a66a3182573122c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 46fc70d6b59a88074afe77548a66a3182573122c<br /><br />Works OK now, both for fields and fieldsets<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13490">issues.joomla.org/tracker/joomla-cms/13490</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks!

**Pull request merged**
