### PR TITLE
Show loading view in installer component properly

### PR DESCRIPTION
**Pull request by magnussinger**
Pull Request for Issue #37516

### Summary of Changes
When removing the "hidden" class from the loading view in the installer component in the inspector, this view is now properly positioned

### Testing Instructions
Go to the extension installer, open the inspector and search for the div with the ID "loading", then remove the "hidden" class from it

### Actual result BEFORE applying this Pull Request
The loading view was positioned below the main content and was invisible

### Expected result AFTER applying this Pull Request
The loading view is now visible and properly positioned

### Documentation Changes Required
None

### CODE REVIEW

**Comment by broucer41** [comment]
https://play.google.com/store/apps/details?id=statussaver.storysaver.videodownloader Our status saver new form application can fill in as a status saver for Instagram applications. You can download the status/post of Instagram in two ways;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37538">issues.joomla.org/tracker/joomla-cms/37538</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 063c3e658d915b4c7a3bc17de69838a964d63fa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37538">issues.joomla.org/tracker/joomla-cms/37538</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 063c3e658d915b4c7a3bc17de69838a964d63fa2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37538">issues.joomla.org/tracker/joomla-cms/37538</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37538">issues.joomla.org/tracker/joomla-cms/37538</a>.</sub>

**Comment by richard67** [comment]
@MagnusSinger Any reason why this hasn't been made for the 4.2-dev branch and not the 4.1-dev branch? As far as I can see it's a bug fix and not a new feature, so no reason to wait until 4.2.

**Comment by magnussinger** [comment]
@richard67 you're right, I'll rebase

**Comment by richard67** [comment]
@MagnusSinger Something went wrong with the rebase because now the PR shows on GitHub all changes from 4.1-dev to 4.2-dev, too, in addition to your changes. But when trying to fix that here locally on the command line, git tells me your branch is ok and up to date with 4.1-dev.

**Comment by richard67** [comment]
@MagnusSinger Maybe it would help to locally make a hard reset of the branch to the initial commit for your change, i.e. commit 7673f83a7cffcab4a6abb14c870f17d6f0aec35a , so that all the later "merge branch 4.2-dev into branch i37516" would be dropped, and then force push to your remote (origin). Shall I try that for you?

**Comment by magnussinger** [comment]
Oh yes that would be great, thanks

**Comment by richard67** [comment]
@MagnusSinger Unfortunately that didn't work. Have you uses the GitHub UI here to change the base branch by using the "Edit" button as if you wanted to edit the title, and then selected the branch and saved? Or have you used a local git client to rebase? Maybe it helps to toggle the branch again here on GitHub, i.e. Edit and change base to 4.2-dev and then again back to 4.1-dev?

**Comment by magnussinger** [comment]
Yes, I used the GitHub UI. Let me try changing it once more

**Comment by magnussinger** [comment]
Okay this somehow didn't work, I'll try to change it locally

**Comment by richard67** [comment]
@MagnusSinger If nothing else helps, make a new PR ... will test again then.

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37538">issues.joomla.org/tracker/joomla-cms/37538</a>.</sub>

**Comment by magnussinger** [comment]
@richard67 I created a new PR with base 4.1-dev: https://github.com/joomla/joomla-cms/pull/37570

**Comment by richard67** [comment]
@MagnusSinger Then close this one here with an appropriate comment referring to the new one.

**Comment by magnussinger** [comment]
Closing this PR because the changes should go into branch 4.1-dev instead of 4.2-dev, but the rebase in this PR didn't work and I had to create a new one which can be found here: https://github.com/joomla/joomla-cms/pull/37570

**Pull request closed without merging**
