### PR TITLE
[4][webservices] get all menu items related to a specific menu

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #39667 .

### Summary of Changes

added the filter` {{base_path}}/api/index.php/v1/menus/{{site}}/items?filter[menutype]=testmenu
`
### Testing Instructions

suppose you have a site menu  with unique name = testmenu
run `{{base_path}}/api/index.php/v1/menus/site/items?filter[menutype]=testmenu`

### Actual result BEFORE applying this Pull Request
N/A

### Expected result AFTER applying this Pull Request
return all the items in the testmenu

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on c0dd531ca9c690cb533a4e657fcf9cad8a0fb234<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39675">issues.joomla.org/tracker/joomla-cms/39675</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c0dd531ca9c690cb533a4e657fcf9cad8a0fb234<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39675">issues.joomla.org/tracker/joomla-cms/39675</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39675">issues.joomla.org/tracker/joomla-cms/39675</a>.</sub>

**Comment by roland-d** [comment]
@alikon The documentation here should be updated:
https://docs.joomla.org/J4.x:Joomla_Core_APIs#Get_List_of_Menus

**Comment by fancyFranci** [comment]
Thank you for adding the filter!

**Pull request merged**
