### PR TITLE
[5.2] fix unescaped quotes in sampldata_blog language string

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request for Issue # .

### Summary of Changes

add \

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

`class="d-grid gap-2 d-sm-block"`

### Expected result AFTER applying this Pull Request

`class=\"d-grid gap-2 d-sm-block\"`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
are you sure it is necessary to escape the "

for example this is not escaped
https://github.com/joomla/joomla-cms/blob/88fbc2cd3bef6b64e9f89a8937852f91d50f44ad/administrator/language/en-GB/plg_sampledata_blog.ini#L28

**Comment by tecpromotion** [comment]
> or is this another bug to fix?

I say it's a bug too and in my opinion rel and target should be added as well.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on e7de0660e9390f7c9dbf65b84213a802fa634041<br /><br />code revieuw<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44111">issues.joomla.org/tracker/joomla-cms/44111</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 70c049da7f4a9ca456dfd0b789340d8b00099914<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44111">issues.joomla.org/tracker/joomla-cms/44111</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44111">issues.joomla.org/tracker/joomla-cms/44111</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @tecpromotion!

**Pull request merged**
