### PR TITLE
[com_finder] maps view: Use title in language subbranch

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This make a small adjustement to the language subbranches in smart search content maps.
##### After PR

image
#### Testing Instructions
1. Apply patch
2. Check the `Language` subbranches in Components -> Smart Search -> Content Maps
   
   Before PR: `en-GB` and so on.
   
   After PR: the content language title.
   The same you have in Extensions -> Languages -> Content Languages

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 26404fe82ccf218dc90bdf6b4cdef80d1b3bff0d<br /><br />This works. The Content Languages name show if they are published.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10266">issues.joomla.org/joomla-cms/10266</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 26404fe82ccf218dc90bdf6b4cdef80d1b3bff0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10266">issues.joomla.org/joomla-cms/10266</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10266">issues.joomla.org/joomla-cms/10266</a>.</sub>

**Comment by wilsonge** [comment]
This conflicts - can you fix the conflicts please? Thanks :)

**Comment by andrepereiradasilva** [comment]
conflicts fixed was just a comment

The "Composer Dependency Changed" is file permisisons (was 755?).

@wilsonge please check.

**Comment by andrepereiradasilva** [comment]
thanks for testing and comments!

**Comment by wilsonge** [comment]
Thank you very much!

**Pull request merged**
