### PR TITLE
[4.0] Disable Stats plugin

### PR DESCRIPTION
**Pull request by brianteeman**
Plugins are disabled not unpublished.

@philetaylor please check that I didnt break your code

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 0a5720ea9bbe1a20ee8b12825b293ac6d919fa12<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33760">issues.joomla.org/tracker/joomla-cms/33760</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0a5720ea9bbe1a20ee8b12825b293ac6d919fa12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33760">issues.joomla.org/tracker/joomla-cms/33760</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33760">issues.joomla.org/tracker/joomla-cms/33760</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
great thanks

**Pull request merged**
