### PR TITLE
Update alternate.xml

### PR DESCRIPTION
**Pull request by brianteeman**
Partial Pull Request for Issue #38032  .

Go to Menu - manage
New menu: enter a name and choose "Alternative Menu Preset"
Save and Close
A new menu is on the menus view

Open the list of menu items

click the first item (home dashboard)
on php 8.1 you will see a deprecated notice
on php < 8.1 you will see the menu item type field is empty

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 13100d97f53cf077039b1a540b7776fa4720ffc4<br /><br />Thanks! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38042">issues.joomla.org/tracker/joomla-cms/38042</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 13100d97f53cf077039b1a540b7776fa4720ffc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38042">issues.joomla.org/tracker/joomla-cms/38042</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38042">issues.joomla.org/tracker/joomla-cms/38042</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
