### PR TITLE
[4.0][workflow] - undefinded property on modal

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
removed Notice:  Undefined index:  in /var/www/html/j4dev/administrator/components/com_content/tmpl/articles/modal.php

### Testing Instructions
Add a new menu item of Single Article item type
click on select article and look at the notice in the modal

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on db196b7f762100511f638b30510a35462213ca43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21622">issues.joomla.org/tracker/joomla-cms/21622</a>.</sub>

**Comment by ghost** [comment]
Didn't get a Notice on Modal.

**Comment by infograf768** [comment]
The Notice appears here in php logs and PR is fine.

**Comment by alikon** [comment]
when you click on select article

screenshot from 2018-08-15 09-21-04

**Comment by ghost** [comment]
@infograf768 on cloudaccess didn't get a php.log.
@alikon click on select Article didn't get a Notice.

**Comment by alikon** [comment]
i'm working local with current stage .... don't know why cloudacces didn't notice

**Comment by infograf768** [comment]
@franz-wohlkoenig 
I suggest you look at this screenshot before patch. The column Status is empty.
screen shot 2018-08-15 at 09 37 09

After patch we have the icons.
Logs show:
```
[15-Aug-2018 09:37:06 Europe/Berlin] PHP Notice:  Undefined property: stdClass::$status in /Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_content/tmpl/articles/modal.php on line 114
[15-Aug-2018 09:37:06 Europe/Berlin] PHP Notice:  Undefined index:  in /Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_content/tmpl/articles/modal.php on line 114
```

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on db196b7f762100511f638b30510a35462213ca43<br /><br />Thanks for Hint @infograf768 Not there are green Icons after applying PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21622">issues.joomla.org/tracker/joomla-cms/21622</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
