### PR TITLE
[4.0] Impossible to create new Menu Type

### PR DESCRIPTION
**Pull request by infograf768**
Try creating a new Menu (Menu type)
Error is `Class 'Joomla\CMS\Table\JApplicationHelper' not found`

Patch and retest

### CODE REVIEW

**Comment by joomdonation** [comment]
It would be better if we can use the class directly instead of an aliased class. So;

1. Add an use statement at the top (after defined line)

```php
defined('JPATH_PLATFORM') or die;

use Joomla\CMS\Application\ApplicationHelper;
```
Then change the line you changed to just;

```php
$this->menutype = ApplicationHelper::stringURLSafe($this->menutype);
```

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8dbe2583620e8888bfa53fd64e093200100a2dc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16609">issues.joomla.org/tracker/joomla-cms/16609</a>.</sub>

**Comment by infograf768** [comment]
@joomdonation 

The issue is also present in other files.
I found by Grep quite a few places where we have 
`JApplicationHelper::`

and no alias or direct class.
It may be a good idea to solve all together and I would close this.

**Comment by joomdonation** [comment]
@infograf768 I made PR https://github.com/joomla/joomla-cms/pull/16615 as requested

**Pull request closed without merging**
