### PR TITLE
user profile plugin - Terms of Service prevent NOTICE

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue follow of #9405 .
#### Summary of Changes

a better check
#### Testing Instructions

please carefully test the user profile plugin about tos mainily

frontend  register , edit etc
backend  new , edit , etc
#### Comment

any feedback is warmly wellcomed

### CODE REVIEW

**Comment by zero-24** [comment]
@wilsonge @brianteeman can you add the release blocker label? If i get some time tomorrow or on saturday i can try to test this.

Thanks @alikon for the patch :+1:

**Comment by alikon** [comment]
noooo :sob:
2nd yellow card on same #pr i will miss next match

**Comment by zero-24** [comment]
Hehe :) good that we are not at soccer here :)

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on a85ccc590ea7fffdea5dad8d1ad1d3bb83c14f3e<br /><br />TOS works as expected in the front end and no issues found when modifying as user or admin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9458">issues.joomla.org/joomla-cms/9458</a>.</sub>

**Comment by joomdonation** [comment]
@alikon red card for you :D, and you will miss next match. With this change, even you select No in terms of services, the registration will still be processed.

**Comment by alikon** [comment]
@joomdonation hoping to not miss more than 1 match ;)

**Comment by joomdonation** [comment]
@alikon It looks OK now. However, I think you have too many **(** and **)** in the code (which is not needed). I think you can change the code to to make it easier to read:

```php
$task       = JFactory::getApplication()->input->getCmd('task');
$option     = JFactory::getApplication()->input->getCmd('option');
$tosarticle = $this->params->get('register_tos_article');
$tosenabled = $this->params->get('register-require_tos', 0);
if ($option == 'com_users' && $task == 'register' && $tosarticle && $tosenabled == 2 && !$data['profile']['tos'])
{	
		throw new InvalidArgumentException(JText::_('PLG_USER_PROFILE_FIELD_TOS_DESC_SITE'));
}
```

**Comment by zero-24** [comment]
@alikon is this ready for testing? or do you want to add the fixes by @joomdonation

**Comment by alikon** [comment]
Is ready for test IMHO ,  is readable for me but this my personal feeling

**Comment by joomdonation** [comment]
My personal feeling, too. If maintainer decides that the changes is not needed, then count me as one successful test.

**Pull request merged**
