### PR TITLE
Multiple showon

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Description

This PR adds the ability to use a multiple field dependencies in showon form field attribute.
`showon="field1:value1[OPERATOR]field2:value1,value2"`

This is needed, for instance, in https://github.com/joomla/joomla-cms/pull/8442 , but could really be used in many cases.
### How to test

Apply the patch and refresh javascript cache.
1. Test if all current showon fields (config, recaptcha plugin, tinymce, etc) are working properly
   Hint: To check where showon is being used use (in Linux): `egrep -R 'showon=' /path/to/joomla/`
2. Change a field in `/administrator/components/com_config/model/form/application.xml` to use multiple dependencies, for instance, replace:
   `showon="mailer:sendmail"`
   for
   `showon="mailonline:1[AND]mailer:sendmail"`
   or
   `showon="mailonline:1[OR]mailer:sendmail"`

And test if `jform[sendmail]` field (Sendmail Path) in global config only appears when `jform[mailonline]` (Send Mail) is set to "Yes" and/or  `jform[mailer]` (Mailer) is set to "Sendmail".

Other field showon test examples:

```
<field name="field1" type="checkbox" label="field1" value="1" default="0" />
<field name="field2" type="radio" label="field2" default="0" class="btn-group btn-group-yesno"><option value="1">1</option><option value="0">0</option></field>
<field name="field3" type="list" label="field3" default="0"><option value="1">1</option><option value="0">0</option></field>
<field name="field4" type="text" label="field4" default="0" />
<field name="field5" type="checkboxes" label="field5" default="0"><option value="2">2</option><option value="1">1</option><option value="0">0</option></field>
<field name="field6" type="list" label="field6" default="0" multiple="true"><option value="0">0</option><option value="1">1</option></field>

<field name="check1" type="text" label="shows on field1=1" showon="field1:1" /> 
<field name="check2" type="text" label="shows on field1=1 AND field1=1" showon="field1:1[AND]field2:1" />               
<field name="check3" type="text" label="shows on field1=1 OR field2=1" showon="field1:1[OR]field2:1" /> 
<field name="check4" type="text" label="shows on field1=1 OR field2=1 OR field3=1" showon="field1:1[OR]field2:1[OR]field3:1" /> 
<field name="check5" type="text" label="shows on field1=1 AND field2=1 AND field3=1" showon="field1:1[AND]field2:1[AND]field3:1" />
<field name="check6" type="text" label="shows on field1=1 AND field2=1 OR field3=1" showon="field1:1[AND]field2:1[OR]field3:1" />   
<field name="check7" type="text" label="shows on field1=1 OR field2=1 AND field3=1" showon="field1:1[OR]field2:1[AND]field3:1" />   
<field name="check8" type="text" label="shows on field1=1 AND field2=1 AND field3=1 AND field4=1" showon="field1:1[AND]field2:1[AND]field3:1[AND]field4:1" />   
<field name="check9" type="text" label="shows on field5 as 0" showon="field5:0" />
<field name="check10" type="text" label="shows on field5 as 1" showon="field5:1" />
<field name="check11" type="text" label="shows on field5 as 2" showon="field5:2" />
<field name="check12" type="text" label="shows on field5 as 1 or 0" showon="field5:1,0" />
<field name="check13" type="text" label="shows on field5 as 2,1 or 0" showon="field5:2,1,0" />
<field name="check14" type="text" label="shows on field1=1 AND field5 as 2 or 1" showon="field1:1[AND]field5:2,1" />
<field name="check15" type="text" label="shows on field6 as 0" showon="field6:0" />
<field name="check16" type="text" label="shows on field6 as 1 or 0" showon="field6:1,0" />
```
### BC

After update, just refresh javascript cache to refresh cms.js file (Ctrl + F5).

I don't know if i used some form classes properly. Please check code.
Improvements are welcome.
@dgt41 @infograf768

### CODE REVIEW

**Comment by Bakual** [comment]
So this would make it that **both** requirements need to be valid for the field to appear?

Personally I would had needed it the other way, that only one of the requirements need to be true (eg either parameter foo **or** paramater bar need to be enabled).
But I can the need for both ways. Just not sure if we can support both behaviours somehow :smile:

**Comment by andrepereiradasilva** [comment]
> So this would make it that both requirements need to be valid for the field to appear?

yes

> Personally I would had needed it the other way, that only one of the requirements need to be true (eg either parameter foo or paramater bar need to be enabled).
> But I can the need for both ways. Just not sure if we can support both behaviours somehow :smile:

I think we can. :)
We can, for instance, use "&&" for AND and "||" for OR, instead of ";".
I will check that.

**Comment by Bakual** [comment]
My fear is that the code becomes to complex, but if it's possible without to much complexity then I think that would be great and even more intuitive to use.

**Comment by andrepereiradasilva** [comment]
Done. Thanks for the feedback @Bakual

**Comment by infograf768** [comment]
Will test tomorrow.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on de9181c607b8a1677bda0af27cf85a80d1be824d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8524">issues.joomla.org/joomla-cms/8524</a>.</sub>

**Comment by joboca** [comment]
Hi @andrepereiradasilva 

I tried this code and it works perfectly.
It works well in all fields type="radio" and type="list" but does not work in type="checkboxes" or with multiple = "true"
One problem encountered is that checkboxes not function as such and it functions as radio.

<field
	name="field1"
	type="checkboxes"
	default="0"
	label="Field1">
	<option value="0">JNO</option>
	<option value="1">JYES</option>
</field>
<field
	name="field2"
	type="text"
	label="Field2"
	showon="field1:1">
</field>

You can tell me anything about it? Thank you

**Comment by andrepereiradasilva** [comment]
@joboca 

It works on checkbox fiels type too, try this:
```
<field name="field0" type="checkbox" label="field0" value="0" default="1" />
<field name="field1" type="checkbox" label="field1" value="1" default="1" />
<field name="field2" type="text" label="shows on field0 AND field1" showon="field0:1[AND]field1:1" />				
<field name="field3" type="text" label="shows on field0 OR field1" showon="field0:1[OR]field1:1" />
```

**Comment by andrepereiradasilva** [comment]
@joboca, i think all issues resolved test with this:

```
<field name="field1" type="checkbox" description="field1" label="field1" value="1" default="0" />
<field name="field2" type="radio" description="field2" label="field2" default="0" class="btn-group btn-group-yesno"><option value="1">1</option><option value="0">0</option></field>
<field name="field3" type="list" description="field3" label="field3" default="0"><option value="1">1</option><option value="0">0</option></field>
<field name="field4" type="text" description="field4" label="field4" default="0" />
<field name="check1" type="text" label="shows on field1=1" showon="field1:1" />	
<field name="check2" type="text" label="shows on field1=1 AND field1=1" showon="field1:1[AND]field2:1" />				
<field name="check3" type="text" label="shows on field1=1 OR field2=1" showon="field1:1[OR]field2:1" />	
<field name="check4" type="text" label="shows on field1=1 OR field2=1 OR field3=1" showon="field1:1[OR]field2:1[OR]field3:1" />	
<field name="check5" type="text" label="shows on field1=1 AND field2=1 AND field3=1" showon="field1:1[AND]field2:1[AND]field3:1" />
<field name="check6" type="text" label="shows on field1=1 AND field2=1 OR field3=1" showon="field1:1[AND]field2:1[OR]field3:1" />	
<field name="check7" type="text" label="shows on field1=1 OR field2=1 AND field3=1" showon="field1:1[OR]field2:1[AND]field3:1" />	
<field name="check8" type="text" label="shows on field1=1 AND field2=1 AND field3=1 AND field4=1" showon="field1:1[AND]field2:1[AND]field3:1[AND]field4:1" />
```

**Comment by joboca** [comment]
Thanks for your quick response @andrepereiradasilva 

Your examples seem to work but try several checkbox
>\<field name="field0" type="checkboxes" default="0" label="field0">\<option value="0">JNO\</option>\<option value="1">JYES\</option>\</field>
>\<field name="check1" type="text" label="shows on field0=1" showon="field0:1" />

**Comment by andrepereiradasilva** [comment]
ok. I see `type="checkboxes"`` didn't test that field type, only `type="checkbox"`.

Yes, current it doesn't work in that field type, will see what i can do.

**Comment by joboca** [comment]
I hope you can find a solution.

Thanks for your great work.

**Comment by andrepereiradasilva** [comment]
More test examples

```
<field name="field1" type="checkbox" label="field1" value="1" default="0" />
<field name="field2" type="radio" label="field2" default="0" class="btn-group btn-group-yesno"><option value="1">1</option><option value="0">0</option></field>
<field name="field3" type="list" label="field3" default="0"><option value="1">1</option><option value="0">0</option></field>
<field name="field4" type="text" label="field4" default="0" />
<field name="field5" type="checkboxes" label="field5" default="0"><option value="2">2</option><option value="1">1</option><option value="0">0</option></field>
<field name="check1" type="text" label="shows on field1=1" showon="field1:1" />	
<field name="check2" type="text" label="shows on field1=1 AND field1=1" showon="field1:1[AND]field2:1" />				
<field name="check3" type="text" label="shows on field1=1 OR field2=1" showon="field1:1[OR]field2:1" />	
<field name="check4" type="text" label="shows on field1=1 OR field2=1 OR field3=1" showon="field1:1[OR]field2:1[OR]field3:1" />	
<field name="check5" type="text" label="shows on field1=1 AND field2=1 AND field3=1" showon="field1:1[AND]field2:1[AND]field3:1" />
<field name="check6" type="text" label="shows on field1=1 AND field2=1 OR field3=1" showon="field1:1[AND]field2:1[OR]field3:1" />	
<field name="check7" type="text" label="shows on field1=1 OR field2=1 AND field3=1" showon="field1:1[OR]field2:1[AND]field3:1" />	
<field name="check8" type="text" label="shows on field1=1 AND field2=1 AND field3=1 AND field4=1" showon="field1:1[AND]field2:1[AND]field3:1[AND]field4:1" />	
<field name="check9" type="text" label="shows on field5 as 0" showon="field5:0" />
<field name="check10" type="text" label="shows on field5 as 1" showon="field5:1" />
<field name="check11" type="text" label="shows on field5 as 2" showon="field5:2" />
<field name="check12" type="text" label="shows on field5 as 1 or 0" showon="field5:1,0" />
<field name="check13" type="text" label="shows on field5 as 2,1 or 0" showon="field5:2,1,0" />
<field name="check14" type="text" label="shows on field1=1 AND field5 as 2 or 1" showon="field1:1[AND]field5:2,1" />
```

**Comment by joboca** [comment]
You are the best!!
They also run the multiselects

>\<field name="field6" type="list" multiple="true" label="field6" default="0">\<option value="2">2\</option>\<option value="1">1</option>\<option value="0">0\</option>\</field>
>\<field name="check15" type="text" label="shows on field6 as 2,1 or 0" showon="field6:2,1,0" />

**Comment by andrepereiradasilva** [comment]
@joboca 
Can you test and click in Test This (after login) in https://issues.joomla.org/tracker/joomla-cms/8524

**Comment by joboca** [comment]
I have tested this item :white_check_mark: successfully on ce936c766ad88e8c85e978b60f258fa3394d5665<br /><br />Very necessary for new versions of Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8524">issues.joomla.org/joomla-cms/8524</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ce936c766ad88e8c85e978b60f258fa3394d5665<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8524">issues.joomla.org/joomla-cms/8524</a>.</sub>

**Comment by zero-24** [comment]
RTC :) Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8524">issues.joomla.org/joomla-cms/8524</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@dgt41 @joboca  thanks for testing!

**Comment by wilsonge** [comment]
@andrepereiradasilva I had to manually fix conflicts here when merging it - could you please just double check everything is ok in the commit merging it into the CMS (https://github.com/joomla/joomla-cms/commit/aff4150eb7e5ac70cdc0eda9af1512a4b4d441fb). Thanks!

**Comment by andrepereiradasilva** [comment]
seems everything is fine. thanks.
Just one notice thsi PR (https://github.com/joomla/joomla-cms/pull/8442) was 3.6.0 because it was waiting for this one. Since this was merged for 3.5.0 the other one should be 3.5.x IMHO.

**Comment by hennysmafter** [comment]
@andrepereiradasilva 
Is this now included into 3.5.1?

**Comment by Bakual** [comment]
@hennysmafter This PR got merged for 3.5.0. See the milestone.

**Comment by hennysmafter** [comment]
@Bakual Thank you for informing me. I saw the milestone but did not understand it as there where so many references. But your answer removes all doubts. Really happy with it. Thanks everyone!

**Comment by roland-d** [comment]
@hennysmafter Please update the docs. It's a wiki, so anyone can update the docs.

**Comment by joboca** [comment]
Hi @andrepereiradasilva ,

It's possible to select a value empty ""

example:

`<field name="field1"
	default="">
		<option value="">JGLOBAL_USE_GLOBAL</option>
		<option value="0">JNO</option>
		<option value="1">JYES</option>
</field>`

`<field name="field2"
	showon="field1:" />`

Thanks

**Comment by Bakual** [comment]
> It's possible to select a value empty ""

Please use the Google Group for such requests: https://groups.google.com/forum/#!forum/joomla-dev-general

**Comment by hennysmafter** [comment]
@roland-d I just spent about 30 minutes in making all the functions available in the docs I press save and I get a bullshit reply that I am link spanning or something. I did not even add 1 link to the entire post!!!

Now everything is gone. What is this getting punished for making a contribution? Ridiculous now I understand why those docs are so many times outdated because really I wanted to make a difference on those docs but now not so much it is easier to add it in our own knowledge base. At least when I press save it gets saved.

**Comment by hennysmafter** [comment]
I am writing it once more. And I will dump the entire thing in here. So anyone who is willing to deal with the Joomla Doc system please try adding it.

**Comment by hennysmafter** [comment]
I am going to try if they accept it otherwise here is everything I changed I kept numbering up those translate items so those links inside `noinclude` are not mine but where already present.

```markup

<translate><!--T:19-->
To combine multiple fields you can use <code>[AND]</code>. Like <code>showon="foo:1[AND]bar:1"</code></translate>

<translate><!--T:20-->
Syntax to show the field "bar" only when "foo" is set to "1" and "baz" is set to "1":</translate>

<source lang="php"><field
    name="foo"
    type="list"
    >
    <option value="1">JYES</option>
    <option value="0">JNO</option>
</field>
<field
    name="baz"
    type="list"
    >
    <option value="1">JYES</option>
    <option value="0">JNO</option>
</field>
<field
    name="bar"
    type="text"
    showon="foo:1[AND]baz:1"
/></source>

<translate><!--T:21-->
Syntax to show the field "bar" only when "foo" is set to "1" or "baz" is set to "1":</translate>

<source lang="php"><field
    name="foo"
    type="list"
    >
    <option value="1">JYES</option>
    <option value="0">JNO</option>
</field>
<field
    name="baz"
    type="list"
    >
    <option value="1">JYES</option>
    <option value="0">JNO</option>
</field>
<field
    name="bar"
    type="text"
    showon="foo:1[OR]baz:1"
/></source>

<translate><!--T:22-->
To create a choice between multiple fields you can use <code>[OR]</code>. Like <code>showon="foo:1[OR]bar:1"</code></translate>

<translate><!--T:23-->
This was introduced with PullRequest: https://github.com/joomla/joomla-cms/pull/3379, available starting with Joomla 3.2.4.</translate>

<noinclude>
<translate>
<!--T:24-->
[[Category:Landing Pages]]
[[Category:Form fields]]
[[Category:Development]]
</translate>
</noinclude>


```

**Comment by hennysmafter** [comment]
Now I am getting another message:

This action has been automatically identified as harmful, and it has been disallowed. In addition, as a security measure, some privileges routinely granted to established accounts have been temporarily revoked from your account. A brief description of the abuse rule which your action matched is: Rep Filter

So basically I am the biggest terrorist walking around as I wanted to make one update to the docs and immediately I am punished for what??? Seriously I do not understand this at all. I have been making contributions to docs for years now. But the first time I make a contribution to the Joomla docs this stuff happens why oh why would anybody want to go through this stuff.

If anyone has a explanation please tell me...

**Comment by mbabker** [comment]
There are a bunch of anti-spam measures on the docs wiki because it is a heavy target for spam bots.  @MATsxm and @Hutchy68 can help you out with things.

**Comment by hennysmafter** [comment]
@MATsxm @Hutchy68 I have heard you guys are the ones to talk about the docs. Nothing much really but I wanted to make contributions now not so much anymore I don't have time to deal with this crap. So I will post it on my own site and as you can see above is the entire text for you guys to update it yourself. If I got other usefull stuff I will try to add it if the system is acting stupid I put on my own site. 

I can understand spam and rules and everything but please understand we have more stuff to do then updating docs.

**Comment by MATsxm** [comment]
@hennysmafter thanks for your contribution in the JDoc.

Do I have to mention here that we are all volunteers with also many stuff to do?
Btw, did you read the user account policy?
https://docs.joomla.org/JDOC:Wiki_policy which also has a specific link to:
https://docs.joomla.org/User:Abuse_filter which gives specifics as to why and how to re-enable your account?

Anyway, I will work on your changes (thanks again) when I'd have finished my other "stuff"

**Comment by hennysmafter** [comment]
I understand that it is all based upon volunteers. And I also understand the position of the security but I also feel being punished for doing nothing wrong. And if you edit a article with many links init and then resupply that article without changing any of the links it is ridiculous to punish that user for supplying spam links as he/she did not do that. 

I might read them but it might also be interesting to check the system of Gantry and how they handle user submitted data. Never had any trouble over there. 

Everyone thank you for volunteering and doing your part making Joomla better. For me I will keep helping people in the different chat rooms.

**Comment by hennysmafter** [comment]
@MATsxm I see you have updated it thank you so much I am sure this is going to be useful for hundreds of developers. I know I am already been a pain in your a* but I see that you deleted the beginning of the showon function. So now the start is not explained? In case this cannot be reverted or adapted please take a look here to see the original full function including the adaptations I made.

http://hennysmafter.eu/docs

**Comment by MATsxm** [comment]
@hennysmafter thanks for the ping, should be ok now :wink: 
What's your JDocs username please?

**Comment by andrepereiradasilva** [comment]
@hennysmafter just a hint: you could also use strings, multiple values (seperate by `,`) and/or multiple conditions

Examples:
```xml
showon="field0:custom"
showon="field1:1,2,3"
showon="field1:1[AND]field2:1[AND]field3:1,2"
showon="field1:1[OR]field2:1[OR]field3:1,2"
```

**Comment by Hutchy68** [comment]
>I understand that it is all based upon volunteers. 

Yes it is

>And I also understand the position of the security but I also feel being punished for doing nothing wrong. 

It's not personal, it's a bot. It isn't punishing you or saying "not you again" so I suggest you read the links @MATsxm supplied.

>And if you edit a article with many links init and then resupply that article without changing any of the links it is ridiculous to punish that user for supplying spam links as he/she did not do that.

It doesn't, the bot is smart enough to know what is new and what is not by user.

>I might read them but it might also be interesting to check the system of Gantry and how they handle user submitted data. Never had any trouble over there. 

LOL, apples and oranges. Probably has a human interaction at some point, no abuse filter is perfect nor can it be 100% right all the time. Plus, they are a business with paid employees not volunteers.

I sent you an email less than an hour after your edit was denied. I apologized to you, made some tweaks to the filter and asked you to try again. Your account was brand new, you never contributed to docs before, and I explained the filter that caught you was looking at the repetition of the text you submitted. Unless you can supply an army of editors to watch JDOCs around the clock and they are willing to approve and read every contribution to stop spammers, I suggest you show a little understanding to why your edit was blocked.

**Comment by hennysmafter** [comment]
@andrepereiradasilva Hey thank you for letting me know that is really useful!
@Hutchy68 Thank you for actively helping me and also thank to @MATsxm for going above and beyond. Especially thank you for volunteering and spending the amounts of times you guys are putting in.

The last thing I want to say is this: Yes indeed my account was brand new but that was a eyeopener for me as well. Because I have been registered at Joomla for years now never ever thought that I needed to register for separate parts of the Joomla project. The error I received basically left me guessing at what I did wrong. Giving clearer error messages might be a good idea but on the other end it might give `bad` people suggestions on how to circumvent the rules. I might never have contributed to the docs before but I am every single day of the year helping people via chat, phone and live working with Joomla and that is not because I am paid to do it.

But let's stop bitching against each other I am really happy that everyone can now share the new functions as they are amazing. Next time when I want to make a contribution I will be making it in my spare time and not during the normal business day as it will give me a bit more time. Luckily when things go wrong I can always ask you two. Plus I will be more patient.

Is there a place which is best to contact when there are questions about editing the docs?

Once again thank you. Sorry for angering, upsetting or irritating anyone who is/has reading these posts.

**Comment by stutteringp0et** [comment]
Is there a possibility of a negative match?  For example, a list item where the default is blank.  Another field might have showon="listfield:!" where ! represents any non-empty value.

**Comment by andrepereiradasilva** [comment]
> Is there a possibility of a negative match? For example, a list item where the default is blank. Another field might have showon="listfield:!" where ! represents any non-empty value.

I don't think so.

**Comment by harris-ingram** [comment]
How hard would it be to add a [NOT] operator?
as in showon="foo:1[NOT]bar:1"
where it will show on if foo == 1 unless bar == 1?

**Pull request closed without merging**
