### PR TITLE
Correct syntax errors from #10389

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

https://github.com/joomla/joomla-cms/pull/10389 introduced some syntax errors (missing or extra closing parentisis).

This PR corrects them.
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 830821a26256d2442db5e5e086719c7a90545830<br /><br />on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10397">issues.joomla.org/joomla-cms/10397</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 830821a26256d2442db5e5e086719c7a90545830<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10397">issues.joomla.org/joomla-cms/10397</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10397">issues.joomla.org/joomla-cms/10397</a>.</sub>

**Comment by infograf768** [comment]
Thanks!

**Pull request merged**
