### PR TITLE
[com_fields] Reducing drastically the redundant language strings

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/14677

### Summary of Changes
Reducing the number of language strings by using global values.
30 strings are replaced by 8 strings
7 in lib, one in com_fields

### Testing Instructions
Enable Language debug
patch and test that fields plugin do not miss any lang values
test that when creating each type of field, we also get all values.

@laoneo @brianteeman @Bakual

### CODE REVIEW

**Review by Bakual — APPROVED** [review]
Looks fine from Review

**Comment by laoneo** [comment]
Would it be wrong to turn COM_FIELDS_FIELD_USE_GLOBAL into JUSE_GLOBAL_FROM_PLUGIN? For me it looks wrong to have a com_fields string in a plugin XML file.

**Comment by Bakual** [comment]
> Would it be wrong to turn COM_FIELDS_FIELD_USE_GLOBAL into JUSE_GLOBAL_FROM_PLUGIN? 

JGLOBAL_USE_FROM_PLUGIN then, not JUSE_... :smile: 

> For me it looks wrong to have a com_fields string in a plugin XML file.

It's in the params.xml one used only by com_fields, not in the plugin manifest file. But I understand your point. Personally I could live with it in this specific case.

**Comment by laoneo** [comment]
> It's in the params.xml one used only by com_fields

Correctly it is used only by the plugin https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/libraries/fieldsplugin.php#L238 .

**Comment by infograf768** [comment]
as @Bakual rightfully said, this is only used by com_fields. i see no reason to add it in en-GB.ini

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 1f7a2c44d06bd3a057912cac419bb0b94e8b3fd0<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14683">issues.joomla.org/tracker/joomla-cms/14683</a>.</sub>

**Pull request merged**
