### PR TITLE
[4.0] Alt text

### PR DESCRIPTION
**Pull request by brianteeman**
All the field labels are "Alt Text" except for this one

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f5f72cd08c5ac48d8ff185e8008a98377626123<br /><br />> All the field labels are "Alt Text" except for this one
>

Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26019">issues.joomla.org/tracker/joomla-cms/26019</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7f5f72cd08c5ac48d8ff185e8008a98377626123<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26019">issues.joomla.org/tracker/joomla-cms/26019</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26019">issues.joomla.org/tracker/joomla-cms/26019</a>.</sub>

**Comment by HLeithner** [comment]
Thank you for investing your holidays into joomla.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
