### PR TITLE
[4.3] Fix build tools Media Manager up merge

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- when up merged from 4.2 one line was wrongly left there (my bad)
- Couple of changes, inline the source map (dev) + watch defaults to dev mode 

### Testing Instructions
Run `npm ci`, `build:com_media:dev` `build:com_media` and `watch:com_media` and confirm that the media manager is working 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@obuisard please consider merging this one before the next alpha, thanks

### CODE REVIEW

**Comment by obuisard** [comment]
Thanks Dimitris @dgrammatiko. I will test it later today. It will definitely be included in upcoming alpha 3.

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on dd3251e4851ece9ba2f849c05290bea17b1c520d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39597">issues.joomla.org/tracker/joomla-cms/39597</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dd3251e4851ece9ba2f849c05290bea17b1c520d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39597">issues.joomla.org/tracker/joomla-cms/39597</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
