### PR TITLE
Update PHPUnit

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Update PHPUnit to latest 4.8 release
### Testing Instructions

Unit tests pass
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3a344eb828b5692fe8951e716a354e5542755fd2<br /><br />unit test passed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11733">issues.joomla.org/joomla-cms/11733</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 3a344eb828b5692fe8951e716a354e5542755fd2<br /><br />UT passing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11733">issues.joomla.org/joomla-cms/11733</a>.</sub>

**Comment by dgt41** [comment]
RTC, since travis is not complaining.
Thanks @mbabker

**Comment by zero-24** [comment]
@joomla-cms-bot

**Pull request merged**
