### PR TITLE
[4.0] Missing css

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #22529 .

### Summary of Changes
Make sure there is a border bottom on all table header cells

It got removed somewhere????

### CODE REVIEW

**Comment by wilsonge** [comment]
Apparently I removed it here. I'm sure there was a reason. But can't remember what now (and currently since my upgrade to Mojave this week localhost is broken). Will merge it for now and can figure out at a later point in time why.

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
@brianteeman figured out why I removed it. Under the header there was inconsistent underlines. And whilst we can add the underscore under the checkbox - I didn't see the need for two single pixel lines so I decided to remove it.

image

**Comment by brianteeman** [comment]
and removing it produces the error you highlight

**Comment by wilsonge** [comment]
Other way around. Adding this line in produces it (because the checkbox headers consistently aren't a `th` element but a `td` and therefore aren't underlined.

**Comment by brianteeman** [comment]
this pr added the underline to the td and the th
without this line you get the error - see screenshots
image
image

with the line you dont get the error - see screenshots
image
image

**Pull request merged**
