### PR TITLE
[4.0] Fixed double click error

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Pull Request for Issue #33703.

### Summary of Changes
No more Double Click

### Testing Instructions
 go to <code>System -> Global config -> server tab</code>
for <code>Database Password</code> field click on <code>Modify </code> Button.

### Actual result BEFORE applying this Pull Request
Click TWICE on modify to enable the field and allow changes.

### Expected result AFTER applying this Pull Request
**ONE CLICK** is all it take
new

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 68ad2fec954393c19a038508396e2aac41d584a1<br /><br />Thanks. 

Please prepend [4] to the title of your PR so that it can be seen to apply to the correct branch although @richard67 will probably know :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33708">issues.joomla.org/tracker/joomla-cms/33708</a>.</sub>

**Comment by rjharishabh** [comment]
https://github.com/joomla/joomla-cms/blob/9c6d53a3d18c7edb96dbec4567d218e5b51d59a3/build/media_source/system/js/fields/passwordview.es6.js#L55

Then this line becomes redundant

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 68ad2fec954393c19a038508396e2aac41d584a1<br /><br />PR works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33708">issues.joomla.org/tracker/joomla-cms/33708</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33708">issues.joomla.org/tracker/joomla-cms/33708</a>.</sub>

**Comment by richard67** [comment]
@himanshu007-creator I've just removed a smiley (emoji) from the description of this PR after the text `**ONE CLICK** is all it take`. The CI tool (namely Drone) doesn't like that and now is hanging. ~~Could you update your branch to latest 4.0-dev and push again? Or let me know if I shall do that for you.~~ Update: I will do that for you 'cause in your time zone it is already late. Please in future no emojis in PR titles or descriptions.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator I've just removed a smiley (emoji) from the description of this PR after the text `**ONE CLICK** is all it take`. The CI tool (namely Drone) doesn't like that and now is hanging. ~Could you update your branch to latest 4.0-dev and push again? Or let me know if I shall do that for you.~ Update: I will do that for you 'cause in your time zone it is already late. Please in future no emojis in PR titles or descriptions.

please can you do it for me @richard67 . Thanks in advance, and regarding the emoji part, i will be careful in future

**Comment by richard67** [comment]
Done. Drone running. Will merge as soon as CI checks are ok.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
