### PR TITLE
[4.0] Fix class for selectlist of contacts

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Change class of contact select field

### Testing Instructions
Make a menuItem to a single contact. 
Set Param for display contact list 
grafik

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cb04e8b110b68766bb73bc90ae5673fa31d395bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34618">issues.joomla.org/tracker/joomla-cms/34618</a>.</sub>

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on cb04e8b110b68766bb73bc90ae5673fa31d395bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34618">issues.joomla.org/tracker/joomla-cms/34618</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34618">issues.joomla.org/tracker/joomla-cms/34618</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
