### PR TITLE
Remove overrides when a template is uninstalled

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for #38700 

## The Problem

When you uninstall a template it does NOT remove the database entry for any overrides for that template in #__template_overrides.

As a result the count on the quickicon does not change.

This site was a j3 site that has now been updated to j4

## Before
image
image

## After uninstalling the template (called editor)
image
image
image

### Part 1
When a template is uninstalled any record in the #__template_overrides table for that template will now be  deleted

### Part 2
On update the #__template_overrides is checked to see if there are any orphaned records from previous templates that have now been deleted and if found then it deletes those records.

## Test instructions
Create a site with a previous release of joomla
Clone the template TWICE
In each cloned template create various template overrides
Update the site to the current release of joomla
You should now see a count for the number of overrides to check on the home dashboard
Uninstall one of the cloned templates
You should now see that the count for the number of overrides to check on the home dashboard has not changed
Update the site to this build using this update url https://ci.joomla.org/artifacts/joomla/joomla-cms/4.2-dev/38714/downloads/57633/pr_list.xml
You should now see that the count for the number of overrides to check on the home dashboard has changed
- that is a successful test of part 2
Finally uninstall the remaining clone template
You should now see that the count for the number of overrides to check on the home dashboard has changed to none
- that is a successful test of part 1

### CODE REVIEW

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on ad285aa64879c992ec73fc45d055b44c8f080bc4<br /><br />Thank you Brian!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38714">issues.joomla.org/tracker/joomla-cms/38714</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38714">issues.joomla.org/tracker/joomla-cms/38714</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for making the update a smoother experience :)

**Comment by PMWilliams123** [comment]
just got round to trying 
You could use following SQL statements in PhpMyAdmin to clean it up (replace the #__ by your actual database prefix):
DELETE FROM `#__template_overrides` WHERE `template` NOT IN (SELECT `name` FROM `#__extensions` WHERE `type`='template');
from #38700 
and return 0 rows affected and obviously did not clear the problem

**Comment by PMWilliams123** [comment]
that might be because There are four entries in #__template _overrides and four entries in #__extensions and four templates in the backend Extension >> Templates but still it shows overrides to check
Screenshot 2022-09-25 103426

**Pull request merged**
