### PR TITLE
[5.1] Tests readme

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to make the readme joomla version independent and then it will never be out of date again

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 65d30aa918e5a229aefae2bb55b9364b0ed646f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42505">issues.joomla.org/tracker/joomla-cms/42505</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 65d30aa918e5a229aefae2bb55b9364b0ed646f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42505">issues.joomla.org/tracker/joomla-cms/42505</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42505">issues.joomla.org/tracker/joomla-cms/42505</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
