### PR TITLE
[6.0] jooa11y remove deprecated strings

### PR DESCRIPTION
**Pull request by brianteeman**
These strings were deprecated and marked for removable in 6.0 as they are no longer used.

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4f090f6f992cefd9c322c1f19a8197bb7c52ad03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 4f090f6f992cefd9c322c1f19a8197bb7c52ad03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 4f090f6f992cefd9c322c1f19a8197bb7c52ad03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by tecpromotion** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 4f090f6f992cefd9c322c1f19a8197bb7c52ad03<br /><br />RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by HLeithner** [comment]
I have not tested this item.<br /><br />RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by HLeithner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44101">issues.joomla.org/tracker/joomla-cms/44101</a>.</sub>

**Pull request merged**
