### PR TITLE
[4.0] Mobile footer

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #28202

scss change so test with npm i first

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d56f37985f3458df43716568493ca6cee6ae83c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28210">issues.joomla.org/tracker/joomla-cms/28210</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8d56f37985f3458df43716568493ca6cee6ae83c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28210">issues.joomla.org/tracker/joomla-cms/28210</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28210">issues.joomla.org/tracker/joomla-cms/28210</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks everyone

**Pull request merged**
