### PR TITLE
[4.0] Improving phpcs setup

### PR DESCRIPTION
**Pull request by Hackwar**
This PR simplifies the call to phpcs and automatically sets the installed_paths of phpcs with composer. This depends on joomla/cms-coding-standard to push the latest release to packagist. It also fixes a codestyle violation.

### CODE REVIEW

**Comment by wilsonge** [comment]
This either isn’t required here or is required as a consequence of https://github.com/joomla/cms-coding-standards/blob/4.0-dev/lib/Joomla-CMS/ruleset.xml#L11 or can be removed. In addition this should be called per running of the tests. Because in real life people can have multiple terminal sessions running not running composer install to facilitate that

**Comment by Hackwar** [comment]
The parameter in cms-coding-standard does not have an effect and the paths are not set per terminal session, but are set once in a config file of phpcs. We had a whole additional package in our composer.json which practically only did what the script now does. So this is required here and needs to be removed from the cms-coding-standard. PR for that is coming soon.

**Comment by wilsonge** [comment]
Thanks!

**Comment by twister65** [comment]
The build fails:
> phpcs --config-set installed_paths ../../joomla/cms-coding-standards/lib,../../joomla/coding-standards
sh: 1: phpcs: not found
Script phpcs --config-set installed_paths ../../joomla/cms-coding-standards/lib,../../joomla/coding-standards handling the post-install-cmd event returned with error code 127
`composer install` did not complete as expected.

**Comment by wilsonge** [comment]
This only happens if you're running `composer install --no-dev` and the fix is in https://github.com/joomla/joomla-cms/pull/25720

**Comment by twister65** [comment]
Thanks !

**Pull request merged**
