### PR TITLE
[CS] Array list style

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Code Style for this long array list

### Testing Instructions

review

### Expected result

shorter lines with array keys

### Actual result

long lines with array keys

### CODE REVIEW

**Review by photodude — APPROVED** [review]
Looks good by code review

**Review by Quy — APPROVED** [review]
Looks good.

**Comment by ghost** [comment]
@photodude @Quy can you please mark your Test as successfully?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e03e74d20a9432d70368939b3e1c0d645af33141<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19610">issues.joomla.org/tracker/joomla-cms/19610</a>.</sub>

**Comment by photodude** [comment]
I have tested this item :white_check_mark: successfully on e03e74d20a9432d70368939b3e1c0d645af33141<br /><br />By code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19610">issues.joomla.org/tracker/joomla-cms/19610</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

Thanks for Tests, Guys.

**Pull request merged**
