### PR TITLE
[4.0] Uniform head icons styling

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Sets uniform styling across header icons. Matching background color. Matching icon style (non outline icons). 

### Before
head-icons1

### After
head-icons2

### CODE REVIEW

**Comment by wilsonge** [comment]
Conflicts :)

**Comment by ciar4n** [comment]
Sorted!

**Comment by wilsonge** [comment]
I'm sorry i just merged charlie's one. want to go again :)

**Review by C-Lodder — APPROVED** [review]

**Comment by ciar4n** [comment]
Done!

**Pull request merged**
