### PR TITLE
[Sql azure] Normalize joomla install sample data sql file

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Normalizes all sql azure joomla **sample_data.sql** install file.
- always use `SET IDENTITY_INSERT [#__xxxx] ON/OFF;`
- `INSERT` to `INSERT INTO`
- Quote all table names and db field names
- Always use `'` to quote string values.
- Code style
### Testing Instructions

Mainly code review. (to many changes need to check code in raw) 
https://github.com/andrepereiradasilva/joomla-cms/blob/patch-24/installation/sql/sqlazure/sample_data.sql

If anyone could test an install of **sample data** 3.6.x would be great. Don't have sql azure to test,
### Documentation Changes Required

None.

@waader @alikon please test.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d028c308fccd6d0fe10861bf972c1463f2c97f41<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Comment by waader** [comment]
I have tested this item :red_circle: unsuccessfully on d028c308fccd6d0fe10861bf972c1463f2c97f41<br /><br />I get this message:
[Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'SELECT'. SQL=INSERT INTO [#__menu] ([id], [menutype], [title], [alias], [note], [path], [link], [type], [published], [parent_id], [level], [component_id], [checked_out], [checked_out_time], [browserNav], [access], [img], [template_style_id], [params], [lft], [rgt], [home], [language], [client_id]) VALUES (1, '', 'Menu_Item_Root', 'root', '', '', '', '', 1, 0, 0, 0, 0, '1900-01-01 00:00:00', 0, 0, '', 0, '', 0, 229, 0, '*', 0 SELECT 2, 'menu', 'com_banners', 'Banners', '', 'Banners', 'index.php?option=com_banners', 'component', 0, 1, 1, 4, 0, '1900-01-01 00:00:00', 0, 0, 'class:banners', 0, '', 3, 12, 0, '*', 1 UNION ALL SELECT 3, 'menu', 'com_banners', 'Banners', '', 'Banners/Banners', 'index.php?option=com_banners', 'component', 0, 2, 2, 4, 0, '1900-01-01 00:00:00', 0, 0, 'class:banners', 0, '', 4, 5, 0, '*', 1 UNION ALL SELECT 4, 'menu', 'com_banners_categories', 'Categories', '', 'Banners/Categories', 'index.php?option=com_categories&extension=com_banners', 'component', 0, 2, 2, 6, 0, '1900-01-01 00:00:00', 0, 0, 'class:banners-cat', 0, '', 6, 7, 0, '*', 1 UNION ALL SELECT 5, 'menu', 'com_banners_clients', 'Clients', '', 'Banners/Clients', 'index.php?option=com_banners&view=clients', 'component', 0, 2, 2, 4, 0, '1900-01-01 00:00:00', 0, 0, 'class:banners-clients', 0, '', 8, 9, 0, '*', 1 UNION ALL SELECT 6, 'menu', 'com_banners_tracks', 'Tracks', '', 'Banners/Tracks', 'index.php?option=com_banners&view=tracks', 'component', 0, 2, 2, 4, 0, '1900-01-01 00:00:00', 0, 0, 'class:banners-tracks', 0, '', 10, 11, 0, '*', 1 UNION ALL SELECT 7, 'menu', 'com_contact', 'Contacts', '', 'Contacts', 'index.php?option=com_contact', 'component', 0, 1, 1, 8, 0, '1900-01-01 00:00:00', 0, 0, 'class:contact', 0, '', 13, 18, 0, '*', 1 UNION ALL SELECT 8, 'menu', 'com_contact', 'Contacts', '', 'Contacts/Contacts', 'index.php?option=com_contact', 'component', 0, 7, 2, 8, 0, '1900-01-01 00:00:00', 0, 0, 'class:contact', 0, '', 14, 15, 0, '*', 1 UNION ALL SELECT 9, 'menu', 'com_contact_categories', 'Categories', '', 'Contacts/Categories', 'index.php?option=com_categories&extension=com_contact', 'component', 0, 7, 2, 6, 0, '1900-01-01 00:00:00', 0, 0, 'class:contact-cat', 0, '', 16, 17, 0, '*', 1
... and so on<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@waader thanks
should be fixed now: https://github.com/joomla/joomla-cms/pull/11795/commits/6dbe48219aac6bbeef55706ed978779da990a01a

**Comment by bhavikTailored** [comment]
- I have tried to patch but there was error display like "PatchTester\Model\PullModel::revert - Error retrieving table data ([])".
- Can you give me information what is problem there?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Comment by zero-24** [comment]
@bhavikTailored to test this you can't use the patchtester as this is a installation only fix. You need to download the branch and install it on a mssql database

**Comment by andrepereiradasilva** [comment]
@bhavikTailored just replace the file /installation/sql/sqlazure/sample_data.sql for this one https://raw.githubusercontent.com/andrepereiradasilva/joomla-cms/patch-24/installation/sql/sqlazure/sample_data.sql

And make a new install in mssql.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 6dbe48219aac6bbeef55706ed978779da990a01a<br /><br />Works now, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thaks @waader 
one more for RTC @brianteeman

**Comment by andrepereiradasilva** [comment]
@alikon can you please test this one again so we get a RTC here? (is the last one)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6dbe48219aac6bbeef55706ed978779da990a01a<br /><br />on code review (hoping that now is better than my previous one) ;)
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11795">issues.joomla.org/joomla-cms/11795</a>.</sub>

**Pull request merged**
