### PR TITLE
[4.2] [System - Additional Accessibility Features] Ctrl or Cmd button on Mac?

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .
User @Sulpher, who uses a Mac, reported that the correct combination in **System - Additional Accessibility Features** plugin would be `CMD + OPTION + A`. I don't have a Mac so I can't check. Created a PR based on his commit.

`There should be a CMD (Command) instead of CTRL according to MacOS terminology.`

Please check.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 859fad8acf715bb7ab6d9b57f025c47eafb69c8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38322">issues.joomla.org/tracker/joomla-cms/38322</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :red_circle: unsuccessfully on 859fad8acf715bb7ab6d9b57f025c47eafb69c8c<br /><br />In Safari 15.5, CMD+OPTION+A is the same keystrokes as Show Page Resources.
In Firefox 78.150esr and Chrome 65.0.3325.181, CTRL+OPTION+A works but not CMD+OPTION+A.

I am not on the latest MacOS/browsers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38322">issues.joomla.org/tracker/joomla-cms/38322</a>.</sub>

**Comment by brianteeman** [comment]
the string is correct. this pr is wrong

**Comment by Sulpher** [comment]
This is question of a terminology. 
The Command key it seems has a short name as Cmd which is equal to Ctrl on Windows.  While Ctrl means Control. 
And there is also the Control (Ctrl) key on Mac keyboard too.

Google: 
_Instead, the Macintosh equivalent of the Windows Ctrl key is the ⌘ key. It's right next to the space bar. It's pronounced “command,” although novices can often be heard calling it the “pretzel key,” “Apple key,” or “clover key.” Most Windows Ctrl-key combos correspond perfectly to ⌘-key sequences on the Mac.
https://www.oreilly.com/library/view/switching-to-the/9781449372927/ch01s08.html#:~:text=Instead%2C%20the%20Macintosh%20equivalent%20of,key%20sequences%20on%20the%20Mac._

_Apple keyboards usually have one Command key on each side of the Spacebar. Normally the key will have a cloverleaf icon  The Command key is indicated by a cloverleaf.   and, on older keyboards, an apple. Also on older keyboards, the word "command" may not be present or may be abbreviated (e.g., "Cmd").
https://kb.iu.edu/d/ahzn_

https://en.wikipedia.org/wiki/Control_key

Снимок экрана 2022-07-31 в 18 37 42

**According to this screenshot, we see That Windows Ctrl is equal to ^Control on Mac, not to Command.** 


Another article:
Ctrl Key on Keyboard: Everything you need to know
https://www.wiredale.com/ctrl-key-on-keyboard/

Снимок экрана 2022-07-31 в 18 40 40

Снимок экрана 2022-07-31 в 18 40 45

Different sources tell different things... It is a little bit chaos with definition.

**Comment by Sulpher** [comment]
Oh. I've checked hotkeys manually on the Mac without referring to the terminology and yes - it is enough to push **^ Control + Option + A** and popup menu appears.
Снимок экрана 2022-07-31 в 18 53 44

Indeed, the PR is wrong.

**Comment by brianteeman** [comment]
glad to see you finaly agree

**Pull request closed without merging**
