### PR TITLE
Update Punycode

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #9497
#### Summary of Changes

Update punycode from v1.2.4 to v1.4.1
#### Testing Instructions

This is used for IDN email validation see #2788

Also see the changes made in #3429 which might not be needed anymore as it looks like they were merged into this upstream library https://github.com/bestiejs/punycode.js/issues/20

### CODE REVIEW

**Comment by wilsonge** [comment]
Can you fix the file permissions please Brian?

**Comment by brianteeman** [comment]
Done and learnt something new ;)

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
How shall we test this? Just see if IDN email addresses still can be entered successfully in email fields in backend? Or roll back the change from #3429 to test also if punycode contains a correction for that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9889">issues.joomla.org/joomla-cms/9889</a>.</sub>

**Comment by brianteeman** [comment]
@infograf768 can you help test this please

**Comment by infograf768** [comment]
Will do tomorrow, Please remind me. :)

**Comment by infograf768** [comment]
Hmm

A valid punycode mail adress would be:
`юзер@екзампл.ком` (for Ukrainian)
Whether I revert the change done in https://github.com/joomla/joomla-cms/pull/3429 it does not validate.

To test, edit a contact mail.

It looks like we have to change the validation regex in validate.js as well as validate-uncompressed.js
```
setHandler('email', function(value, element) {
		    value = punycode.encode(value);  // changed here from value = punycode.toASCII(value);
 	 	 	var regex = /^[a-zA-Z0-9.!#$%&’*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
 	 	 	return regex.test(value);
 	 	});
```

See https://github.com/bestiejs/punycode.js/commit/92f879680551145df9be6fdc300c21c463e0a7d2

**Comment by brianteeman** [comment]
So to confirm you are saying that neither the existing code or the new code
in this PR works?

**Comment by infograf768** [comment]
They work if the local part is ascii, not if it is utf8
`юзер@екзампл.ком` will not validate
`info@екзампл.ком` will.

This why the regex has to be modified.

**Comment by brianteeman** [comment]
Should I add that regex change to this PR?

On 12 May 2016 at 09:53, infograf768 <notifications@github.com> wrote:

> They work if the local part is ascii, not if it is utf8
> юзер@екзампл.ком will not validate
> info@екзампл.ком will.
>
> This why the regex has to be modified.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9889#issuecomment-218698030>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I have not posted the regex change

SO, normally we should revert https://github.com/joomla/joomla-cms/pull/3429 to get:
`value = punycode.encode(value);`  instead of `value = punycode.toASCII(value);`
and then find the correct regex to replace
`var regex = /^[a-zA-Z0-9.!#$%&’*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;`

**Comment by brianteeman** [comment]
Sorry I thought you had - ignore my last commit

**Comment by infograf768** [comment]
please revert your last commit so that we can find and test a new regex

**Comment by brianteeman** [comment]
reverted

**Comment by infograf768** [comment]
All depends on the mail servers. If they obey to RFC5322 or more recent RFC6530
Quote from : https://en.wikipedia.org/wiki/Email_address#Internationalization

Internationalization examples

The example addresses below would not be handled by RFC 5322 based servers, but are permitted by RFC 6530. Servers compliant with this will be able to handle these:

    Latin Alphabet (with diacritics): Pelé@example.com
    Greek Alphabet: δοκιμή@παράδειγμα.δοκιμή
    Traditional Chinese Characters: 我買@屋企.香港
    Japanese Characters: 甲斐@黒川.日本
    Cyrillic Characters: чебурашка@ящик-с-апельсинами.рф

**Comment by brianteeman** [comment]
All I really want to do with this PR is to update the library to the current release. If we have an issue with local nonascii email addresses BEFORE and AFTER this PR then there is no change in behaviour caused by this PR and we can merge this one and then look at that as a new issue. If I understand correctly

**Comment by infograf768** [comment]
We have indeed no more issues after this PR, as far as I tested, when the local part is ascii

**Comment by infograf768** [comment]
BTW, Travis error is unrelated to this patch

**Comment by brianteeman** [comment]
So we can merge this PR then?

On 12 May 2016 at 10:57, infograf768 <notifications@github.com> wrote:

> BTW, Travis error is unrelated to this patch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9889#issuecomment-218712479>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Would be good to get other tests first using 
` info@екзампл.ком` as test mail in contact for example.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 84fce68db0a2b5c93208b4d1f1a83dd92f12cf98<br /><br />юзер@екзампл.ком -> not validate
info@екзампл.ком -> validate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9889">issues.joomla.org/joomla-cms/9889</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 84fce68db0a2b5c93208b4d1f1a83dd92f12cf98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9889">issues.joomla.org/joomla-cms/9889</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9889">issues.joomla.org/joomla-cms/9889</a>.</sub>

**Pull request merged**
