### PR TITLE
[4.1] Update SetConfigurationCommand.php

### PR DESCRIPTION
**Pull request by brianteeman**
simple grammar - code review

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7f5679549734b4b6a4e0e74bcbdca7ac8cd9f4fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37647">issues.joomla.org/tracker/joomla-cms/37647</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7f5679549734b4b6a4e0e74bcbdca7ac8cd9f4fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37647">issues.joomla.org/tracker/joomla-cms/37647</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37647">issues.joomla.org/tracker/joomla-cms/37647</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
