### PR TITLE
Update user.php

### PR DESCRIPTION
**Pull request by luis0076**
With aruba italian provider when you digit wrong password you receive 404 error. With this patch the 404 error disapear

### CODE REVIEW

**Comment by smohila** [comment]
Works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5376">issues.joomla.org/joomla-cms/5376</a>.</sub>

**Comment by Joomti** [comment]
Works. No 404 error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5376">issues.joomla.org/joomla-cms/5376</a>.</sub>

**Comment by wmgraf** [comment]
@test success. Login works

**Comment by vdespa** [comment]
The code quality is NOT OK. This patch should not be merged in the current state.

Replication instruction are also very vague. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5376">issues.joomla.org/joomla-cms/5376</a>.</sub>

**Comment by mbabker** [comment]
In general we do need to catch exceptions from the login method and properly enqueue the error message.  The catch block should call `$app->enqueueMessage(JText::_('ERROR_MESSAGE'));` (replace ERROR_MESSAGE with a proper language key) instead.

@luis0076 could you please update this PR?

**Comment by brianteeman** [comment]
Set back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5376">issues.joomla.org/joomla-cms/5376</a>.</sub>

**Pull request closed without merging**
