### PR TITLE
[4.0] Fix cs errors

### PR DESCRIPTION
**Pull request by brianteeman**
As reported in #31659

If drone passes then it should be good to go as its just code style

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a2aa1b1ed7a7175c851eaff3c5c63241d743f737<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31665">issues.joomla.org/tracker/joomla-cms/31665</a>.</sub>

**Comment by brianteeman** [comment]
If you merge this then you wont have to keep telling people to ignore the drone reports

**Comment by wilsonge** [comment]
Apologies I did these directly after the last batch of conflicts https://github.com/joomla/joomla-cms/commit/cf4b96a68dbf359ee98ae1946b2cd5a7e1012fa9 and didn't notice this PR before

**Comment by brianteeman** [comment]
Always good to keep an eye on the PRs ;) Especially when they are fixing direct merge issues.

**Pull request closed without merging**
