### PR TITLE
Correct "Unlock" Button ACL permissions

### PR DESCRIPTION
**Pull request by stevefontaine**
Unlock Button not showing if user just have core.manage rights (and not core.admin rights). 
So I change the test on core.admin to only influence the Options button and not the Unlock Button.

### CODE REVIEW

**Comment by stiplady** [comment]
@pagchen White space change from 2 to 3 tabs for no apparent reason?

**Comment by pagchen** [comment]
I extracted the button from the if statement.

**Comment by pagchen** [comment]
In the process I did put an extra set of tabs, I removed them.

**Comment by Bakual** [comment]
Can you please change the title of this PR to something representing what you propose? "Update view.html.php" is a bit to generic :smile:

**Comment by photodude** [comment]
I would suggest a PR tile like "correct Unlock Button management rights"

**Comment by Bakual** [comment]
Changed it myself.

**Comment by pagchen** [comment]
Yes it is a better title. Thanks

**Comment by seagul30** [comment]
I have tested this item :white_check_mark: successfully on b0d9b7f94f1983309d63ead2ac96a4c04fac5a28<br /><br />successfully tested. 

Here are some test instructions:

Add User (i.e. Manager rights)
Change User Rights for Manager Group "Global Checkin" to "Access Administration Interface" --> Allowed
Login in Backend
Check Menu "System" - "Global Checkin" --> Button "Checkin" (top left) is missing
Apply patch
Button is showing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7575">issues.joomla.org/joomla-cms/7575</a>.</sub>

**Comment by si-wi** [comment]
I have tested this item :white_check_mark: successfully on b0d9b7f94f1983309d63ead2ac96a4c04fac5a28<br /><br />tested successfully according description of seagul30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7575">issues.joomla.org/joomla-cms/7575</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7575">issues.joomla.org/joomla-cms/7575</a>.</sub>

**Comment by rdeutz** [comment]
I think it is a change in the behauviour of the cms so 3.5

**Comment by roland-d** [comment]
Thanks everybody. Merged into 3.5-dev with commit  de30a73

**Pull request closed without merging**
