### PR TITLE
Fix subform repeat counter.

### PR DESCRIPTION
**Pull request by Sophist-UK**
### Summary of Changes

This PR ensures that added Subform rows are numbered sequentially from zero.

### Testing Instructions

Create and load a form with a repeatable subform with min=1. (Note: AFAIK, Joomla does not have any of these - I am creating one as part of a Fabrik enhancement I am working on.)

Click add twice to add a second and third row.

Examine HTML for div.subform-repeatable-group

### Result before fix.

Groups are numbered 0, 2, 3

### Expected result after fix.

Groups should be numbered 0, 1, 2.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by Fedik** [comment]
It not really important how the numbers are goes here, because after saving they will resets anyway.

But if you want to change it, then you need to test subform with radiobuttons, and checkboxes, to be sure that they continue to work correctly after this changes. Whether a radiobutons not resets after you add new row.

can use XML from one of previous pulls #16480 #7829

**Comment by Fedik** [comment]
just for reference #12995, existing issue

**Comment by Sophist-UK** [comment]
I have checked this with checkbox and checkboxes form fields and they looks fine.

And it works fine with a vanilla radio button. But when I add class="btn-group" then it doesn't work properly because the button <label> classes do not get copied when you add a row. This is because they are not included in the template. I do not believe that this caused by this PR - I will track it down and submit a separate PR to fix it.

**Comment by Sophist-UK** [comment]
The radio buttons not working is documented in #11299. I will try to track it down and fix it, but since it is pre-existing I do not believe it is related to this PR.

**Comment by Fedik** [comment]
I meant only a vanilla radio button.
`btn-group` has some extra js behind, that fail. Ignore it here.

**Comment by Sophist-UK** [comment]
Yes - I tested it with standard radio button and it worked fine.

**Comment by Sophist-UK** [comment]
Radio button group styling fixed by #19722.

**Comment by franz-wohlkoenig** [comment]
@Sophist-UK so can this Issue be closed?

**Comment by Sophist-UK** [comment]
AppVeyor error was not due to this PR - see log details for causes.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 3c5f6ec90a66473b298ea688f97d4b49272c1f0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19693">issues.joomla.org/tracker/joomla-cms/19693</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3c5f6ec90a66473b298ea688f97d4b49272c1f0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19693">issues.joomla.org/tracker/joomla-cms/19693</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19693">issues.joomla.org/tracker/joomla-cms/19693</a>.</sub>

**Comment by mbabker** [comment]
1) Is there a reason the title here says 3.9?  (As in does it need to fix something added in 3.9/3.10 or is it a bug fix for 3.8)

2) There is a merge conflict that needs to be addressed.

**Comment by Sophist-UK** [comment]
Merge conflict because `subform-repeatable-uncompressed.js` has changed elsewhere and so minified file has a conflict..

Rebased on staging, re-minifed `subform-repeatable.js` and did a force push.

Code changes are the same, but probably should be retested to confirm that other changes to this file have not impacted this fix.

**Comment by Sophist-UK** [comment]
@mbabker Michael:
> Is there a reason the title here says 3.9? (As in does it need to fix something added in 3.9/3.10 or is it a bug fix for 3.8)

It is a bug fix for 3.8 - 3.9 label removed from title.

**Pull request merged**
