### PR TITLE
[5.1] Convert mod_tags_similar to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the tags similar site module to service provider.

### Testing Instructions

1. Make sure you have site module mod_tags_similar published
2. Add some tags and assign them to several content items
3. You should see module output on content items, which have at least 1 tag assigned and this tag is assigned also on another content items.

mod_tags_similar

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ab215d497f9addc653b1f526702aebd0c61d9de5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42898">issues.joomla.org/tracker/joomla-cms/42898</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on ab215d497f9addc653b1f526702aebd0c61d9de5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42898">issues.joomla.org/tracker/joomla-cms/42898</a>.</sub>

**Comment by fgsw** [comment]
What means "Service Provider"?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42898">issues.joomla.org/tracker/joomla-cms/42898</a>.</sub>

**Comment by joomlaweby** [comment]
> What means "Service Provider"?

@fgsw Simple explanation is, that it is a new way, how extensions in Joomla works since 4.0. I found more technical explanation here: https://docs.joomla.org/J4.x:Dependency_Injection_in_Joomla_4#Providers

For example in mod_articles_latest extension it is this file: https://github.com/joomla/joomla-cms/blob/5.1-dev/modules/mod_articles_latest/services/provider.php

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also for testing @viocassel and @fgsw

**Pull request merged**
