### PR TITLE
Deprecate feature-policy and add the new Permissions Policy

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Deprecate feature-policy and add the new Permissions Policy

`Permissions-Policy` header is a new thing and is replacing `Feature-Policy` headers  

References:
 -- https://www.w3.org/TR/permissions-policy-1/
 -- https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

Some work already done in Joomla 4 on this https://github.com/joomla/joomla-cms/pull/30491

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6654e4e0df33c7b618863cff421c42c258ae3aa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30819">issues.joomla.org/tracker/joomla-cms/30819</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6654e4e0df33c7b618863cff421c42c258ae3aa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30819">issues.joomla.org/tracker/joomla-cms/30819</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30819">issues.joomla.org/tracker/joomla-cms/30819</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
