### PR TITLE
[4.0] Template Tree list improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

- Rewritten all the jQuery in vanilla JS and moved the JS/CSS to separate files.
- Also fixed up some of the Bootstrap styling.

### Testing Instructions

- apply PR
- Go to **Extensions** >> **Templates** >> **Templates**
- Ensure the tree list views are still fully functional and there are no console log errors

@dgt41 - JS ok?

### CODE REVIEW

**Comment by dgt41** [comment]
@C-Lodder can you rename the files to follow the pattern : [admin/site] [view name] [layout name]?
 e.g. admin-templates-default.js, etc

**Comment by C-Lodder** [comment]
@dgt41 - done and merged the JS files into 1

**Review by dgrammatiko — APPROVED** [review]

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on b60027085ee2d1cd46202a0113546f8a640469fe<br /><br />Everything in the tree list views seem to be operational and no console errors were spotted in this view:
deepinscreenshot20170421173826

However an error (I'm not quite sure if it is related to these code changes) appears when I go to Extensions -> Templates -> Templates:
deepinscreenshot20170421174104

But despite that error, everything seems to be fine on the tree list views.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15449">issues.joomla.org/tracker/joomla-cms/15449</a>.</sub>

**Comment by dgt41** [comment]
@rjcf18 that error is unrelated to this PR, I'll do another PR for that

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on b60027085ee2d1cd46202a0113546f8a640469fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15449">issues.joomla.org/tracker/joomla-cms/15449</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
