### PR TITLE
JCategories: Setting at least the current category as part of the path

### PR DESCRIPTION
**Pull request by Hackwar**
Our category system is slightly inconsistent and fails in one area. In JCategories/JCategoryNode, when the parent category is the root category, setParent() seems not to be called on JCategoryNode. This results in the the _path attribute being empty, although it should at least contain its own category. This is fixed with this one-liner.

### CODE REVIEW

**Comment by infograf768** [comment]
Travis and Test fail.
Could you please give test instructions and compare a present url with the one we should get after patch?

**Comment by roland-d** [comment]
@Hackwar Can you fix this PR please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14883">issues.joomla.org/tracker/joomla-cms/14883</a>.</sub>

**Comment by infograf768** [comment]
AND reply to the comment https://github.com/joomla/joomla-cms/pull/14883#issuecomment-289195375

**Comment by Hackwar** [comment]
So I went through this code several times and while I'm pretty sure that I had a really, really good reason for this PR, I have no idea how to replicate this and see no issue anymore. So I'm closing this one.

**Pull request closed without merging**
