### PR TITLE
Fix a failure in the Module List

### PR DESCRIPTION
**Pull request by astridx**
I made a great mess in issue #7221. Sorry for that. That’s why I have to close this and open the PR newly in this issue.
1.  See the failure
2.  Go to the Extensions | Modules and ensure, that you have at least two modules of the type search for the location site. One is published and another is unpublished.
3.  Switch to Extension Manager|Manage -> Manage and disable the Modul “Search” for the location site.
4.  Go back to Extensions | Module Manager and see, that the Status show wrong values. The published Module looks like unpublished and the unpublished value looks like trashed.
5.  Apply my patch
6.  Go to the Extensions | Module and ensure, that you have at least two modules of the type "Search" for the location site. One is published and another is unpublished.
7.  Switch to Extension Manager|Manage -> Manage and disable the Module “Search” for the location site.
8.  Go back to Extensions | Module Manager and see, that the Status did not show the wrong values any more. There is a new value for disabled modules with a message as tooltip.
   Sorry for the trouble about the new PR.

### CODE REVIEW

**Comment by infograf768** [comment]
Needs some small code style corrections:
```
FOUND 2 ERROR(S) AND 1 WARNING(S) AFFECTING 2 LINE(S)

--------------------------------------------------------------------------------

 168 | WARNING | Expected 1 space after ">"; 0 found

 168 | ERROR   | Expected 1 space before ">"; 0 found

 170 | ERROR   | Whitespace found at end of line
```

**Comment by infograf768** [comment]
Also, there are 2 strings on the same line (Note: weird we have strings for archived modules when we cannot archive these...)
```
+COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED="This module is disabled. Use Extensions => Manage to enable it." COM_MODULES_N_ITEMS_ARCHIVED="%d modules successfully archived."
```
Also:
`Notice: Use of undefined constant php - assumed 'php' in /administrator/components/com_modules/views/modules/tmpl/default.php on line 179`

Add a space between `<?php` and `// Create dropdown items ?>`

**Comment by zero-24** [comment]
@astridx i have just prepared a PR to fix the issues @infograf768 and Travis found ;) https://github.com/astridx/joomla-cms/pull/1

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 1c0d7a38c2d3c04df4a5c537f8101878f0bb4b53<br />
Works great. Thanks @astridx :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8020">issues.joomla.org/joomla-cms/8020</a>.</sub>

**Comment by YouriiM26** [comment]
I have tested this item :white_check_mark: successfully on 1c0d7a38c2d3c04df4a5c537f8101878f0bb4b53<br />Works correctly. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8020">issues.joomla.org/joomla-cms/8020</a>.</sub>

**Comment by zero-24** [comment]
RTC :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8020">issues.joomla.org/joomla-cms/8020</a>.</sub>

**Pull request merged**
