### PR TITLE
Fixing sql server query foreach error on no database join

### PR DESCRIPTION
**Pull request by sweco-semhul**
Pull Request for Issue #13002.

### Summary of Changes
Adding check to make sure $this->join is set.

### Testing Instructions
Setup Joomla against SQL Server, update search index and make a search

### Documentation Changes Required
none

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c66536148dac4f2468a487df0edb5fb8ddada670<br /><br />on code review
good catch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13003">issues.joomla.org/tracker/joomla-cms/13003</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c66536148dac4f2468a487df0edb5fb8ddada670<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13003">issues.joomla.org/tracker/joomla-cms/13003</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on c66536148dac4f2468a487df0edb5fb8ddada670<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13003">issues.joomla.org/tracker/joomla-cms/13003</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13003">issues.joomla.org/tracker/joomla-cms/13003</a>.</sub>

**Pull request merged**
