### PR TITLE
[4.0] Form fields cleanup

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Change some of the remaining radio form fields to switcher and some that have too many options, into a list

### CODE REVIEW

**Review by ciar4n — APPROVED** [review]

**Comment by wilsonge** [comment]
Why is the PR supposedly authored by me?

**Comment by C-Lodder** [comment]
Cause I was using your laptop when I submitted the PR

**Comment by brianteeman** [comment]
Roflmao

**Comment by mbabker** [comment]
Nice way to make sure we blame George 😉

**Pull request merged**
