### PR TITLE
[4.4] Revert #42934, do not force Product schema for every article

### LINKED ISSUE #43797: Error in microdata after updating to Joomla! 5.1.2 Stable
### Steps to reproduce the issue
Open any page of the material where the standard rating is enabled. Check the page via: https://search.google.com  Micro markup for Product rating has appeared.

### Expected result
Product markup should not appear

### Actual result
https://search.google.com/test/rich-results/result/r%2Fproduct?id=Kue1LLBJ8JpysM_LInStSw&hl=en

### System information (as much as possible)
PHP 8.3.1 Apache
Joomla! 5.1.2 Stable

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #43797 .

### Summary of Changes
Do not force Product schema for every article
Revert #42934

### Testing Instructions
Review

### Actual result BEFORE applying this Pull Request
 Product schema added to every article with Vote enabled

### Expected result AFTER applying this Pull Request
No product schema

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ec7a482675e3f8229133fa822d51cc7e1ccbe93f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43827">issues.joomla.org/tracker/joomla-cms/43827</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43827">issues.joomla.org/tracker/joomla-cms/43827</a>.</sub>

**Comment by Slava287** [comment]
Thanks, will this be fixed in future updates?

**Comment by bembelimen** [comment]
Do we now have Google complaining again?

**Comment by brianteeman** [comment]
If this is a full revert then the original issue will be present so that will still need to be fixed

**Comment by Fedik** [comment]
Yes, but that is less critical than this one. I think

**Comment by laoneo** [comment]
Merging this as it is done properly in #42933. Thanks for the help @Fedik.

**Pull request merged**
