### PR TITLE
Webservice description

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #41291. Rewrite of PR #41307 wrongly merged in 4.3.

System test needed. Please see https://github.com/joomla/joomla-cms/pull/41307#issuecomment-1676388462

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fc49dc2d94ef822c2d3792b38822ac47a1f6b568<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41362">issues.joomla.org/tracker/joomla-cms/41362</a>.</sub>

**Comment by alikon** [comment]
@obuisard  i would like to do it, but still fighting with an issue already reported upstream https://github.com/cypress-io/cypress/issues/25357

**Comment by alikon** [comment]
@obuisard i've mad a pr https://github.com/obuisard/joomla-cms/pull/8 for the system test

**Comment by obuisard** [comment]
> @obuisard i've made a pr [obuisard#8](https://github.com/obuisard/joomla-cms/pull/8) for the system test

Thank you so much Nicola @alikon!

**Comment by laoneo** [comment]
@obuisard can you merge this one?

**Comment by obuisard** [comment]
Thank you Nicola @alikon

**Comment by obuisard** [comment]
OMG I mis-understood what was asked of me @laoneo, my fault from looking at the issue from a phone...

**Pull request merged**
