### PR TITLE
[4.0] Fix drone tests

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

Fix the drone tests failing due to indentation.

### CODE REVIEW

**Comment by C-Lodder** [comment]
@mbabker or @laoneo is this ok or does it need to go into the 3.8-dev branch?

**Comment by laoneo** [comment]
This is not needed as only two spaces are needed, can you show me a pr why this fails?

**Comment by C-Lodder** [comment]
@laoneo http://213.160.72.75/joomla/joomla-cms/2314

**Comment by joomdonation** [comment]
It happened with my PR https://github.com/joomla/joomla-cms/pull/15075 , too and I had to change docblock in that PR to fix it (make it consistent with other namespaced classes)

I don't know which is the correct rule but right now, none namespaced classes use 3 spaces while the namespaced classes only use 2 spaces

**Comment by laoneo** [comment]
Strange, then the other files must be showed with an error as well, eg. https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Cms/Authentication/AuthenticationHelper.php . Not sure if there is something broken with the code style checker or what. But on 3.8 they were all green https://github.com/joomla/joomla-cms/pull/15070/files.

**Comment by joomdonation** [comment]
The reasons is because those files (the namespaced clsses) don't have @package and @subpackage tags. For none namespace classes, there must be 3 spaces to align with value of @package and @subpackage tags

**Comment by C-Lodder** [comment]
@laoneo - different files. Either way, this aligns the comments according the drone results. If the spacing needs to be different, or it needs to go into the 3.8-dev branch, just say and I can close this,

**Comment by mbabker** [comment]
FWIW the standard in file and class doc blocks is two spaces after the longest tag name to align all text.

In method/function doc blocks `@param` requires 3 spaces and `@return` requires 2 spaces (for the same alignment reason).  Funny enough, spacing for any other tags (`@since`, `@deprecated`, etc.) isn't enforced in method/function blocks.  But across the board it should always be two spaces after the tag minimum.

**Comment by laoneo** [comment]
When you compare the file in the 3.8 branch https://github.com/joomla/joomla-cms/blob/3.8-dev/libraries/src/Joomla/CMS/Controller/Admin.php and the one in the 4 branch https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Cms/Controller/Admin.php. Then the headers are different. I guess something with the merge went wrong. The @packages are not needed according to @mbabker, or?

**Comment by joomdonation** [comment]
Could someone please make decision about this? Otherwise every PR to 4.0-dev branch will get CS error

**Comment by C-Lodder** [comment]
will close this and let someone fix it in 3.8-dev or wait for 3.8-dev to be merged into 4.0-dev properly.

**Pull request closed without merging**
