### PR TITLE
new edit in component toolbar title

### PR DESCRIPTION
**Pull request by brianteeman**
### Issue

When creating or editing an item in banners, content, users and tags the toolbar title shows either New or Edit as appropriate

contact, newsfeeds, redirect and finder(filters) only had a single string in the language file so they displayed New/Edit

This PR provides consistency so that all components display either New or Edit
### Testing

Go to each core component and check that a NEW item displays NEW in the toolbar title and then check that when an existing item is selected it displays EDIT in the toolbar title

### CODE REVIEW

**Comment by MAT978** [comment]
Works as describe **but**:

now we have different displays between the old: banners, content, users and tags
eg. 'User Manager: Add New User' or 'Banner Manager: New Banner'

and the new ones: contact, newsfeeds, redirect and finder(filters)
eg. 'News Feeds: New' (IMHO this way is the best)

If you need some of my "time" to help getting: 'Banner Manager: New'
just let me know thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7514">issues.joomla.org/joomla-cms/7514</a>.</sub>

**Comment by brianteeman** [comment]
I am confused
I am seeing Banners: New

Is your branch upto date

On 22 July 2015 at 12:29, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> Works as describe *but*:
>
> now we have different displays between the old: banners, content, users
> and tags
> eg. 'User Manager: Add New User' or 'Banner Manager: New Banner'
>
> and the new ones: contact, newsfeeds, redirect and finder(filters)
> eg. 'News Feeds: New' (IMHO this way is the best)
>
> If you need some of my "time" to help getting: 'Banner Manager: New'
> just let me know thanks!
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7514
> <http://issues.joomla.org/tracker/joomla-cms/7514>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7514#issuecomment-123679148>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MAT978** [comment]
<facepalm>Sorry... My fault, 
everything is ok - Success

(note to self: never test a patch before 7am and coffee #3)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7514">issues.joomla.org/joomla-cms/7514</a>.</sub>

**Comment by jwaisner** [comment]
@test

PR works as intended. Displays are correct for NEW and EDIT.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7514">issues.joomla.org/joomla-cms/7514</a>.</sub>

**Comment by infograf768** [comment]
That one is useful...

**Comment by brianteeman** [comment]
Thanks for testing = set RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7514">issues.joomla.org/joomla-cms/7514</a>.</sub>

**Pull request merged**
