### PR TITLE
Update IFW Plugin version to 4.0.0

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #35103

### Summary of Changes

Update IFW Plugin version to 4.0.0

### Testing Instructions

Install 3.10
Install IFW plugin
update to 4.0

### Actual result BEFORE applying this Pull Request

Update to 2.1.2 proposed which is the 3.x version

### Expected result AFTER applying this Pull Request

No update should be proposed

### Documentation Changes Required

none

### CODE REVIEW

**Comment by richard67** [comment]
@zero-24 Does your PR solve issue #35103 so the issue can be closed?

**Comment by zero-24** [comment]
Its a proposal but should fix the issue yes but first this would have to be fully tested and merged.

**Comment by richard67** [comment]
> Its a proposal but should fix the issue yes but first this would have to be fully tested and merged.

@zero-24 Or practice since ever is to close an issue if there is a PR which claims to solve it completely.

**Comment by zero-24** [comment]
Done

**Pull request merged**
