### PR TITLE
Pagebreak: make Article Index always accessible (also with title hidden and page-header shown, avoid h1 > h3)

### PR DESCRIPTION
**Pull request by LivioCavallo**
### Summary of Changes
In J! 3.7.5 Article Index Heading can be shown by Pagebreak plugin at top of article T.O.C.; it's in a `<h3>` element.
To avoid an accessibility error (`<h3>` follows `<h1>`) in some circumstancies (when article title `<h2>` is hidden and page header `<h1>` is shown), let's put Article Index Heading in `<strong>` instead of `<h3>`.

### Testing Instructions
Create and publish an article; create a menuitem to that single article.
Set Menuitem 'Page Display' settings to 'Show  Page Heading' and Options to hide Title.

### Expected result
The page is accessible (https://achecker.ca/checker/index.php)

### Actual result
The page is not accessible: _Header nesting - header following `<h1>` is incorrect (Modify the header levels so only an `<h1>` or `<h2>` follows `<h1>`)_.

### Notes
Usual headings flow is relative to the article; article index are "aside" informations, "nav"igation informations that are related to article but not constitute article's structure.
Changing `<h3>` to `<strong>` should not be a big impact here.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in  favour of this PR as it will change the output of a users site and they have no easy way to see how to change it. I am not convinced it is a genuine a11y error and it is something that a siteowner should change if they so desire.

There are so many places we can improve the a11y that do not  effect the template we should concentrate on them eg in the admin

**Comment by LivioCavallo** [comment]
Three a11y validators I use detect this as an error; I think it's a genuine accessibility error.
Surely there are other pieces of code in J! to improve a11y but I never had to make the backend a11y validable; on the contrary I had to make J! frontend validable some times, so now I share some of my little fixes, if it can be useful.

**Comment by LivioCavallo** [comment]
An alternative would be to emit the Page_Title `<h2>` anyway, eventually hidden (just as I suggested in PR #17686), so to grant this sequence: Page_header `<h1>` -> (eventually hidden) Page_Title `<h2>` -> eventually followed by Article Index `<h3>` .

**Comment by ghost** [comment]
@brianteeman is the Suggestion above a Solution?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17670">issues.joomla.org/tracker/joomla-cms/17670</a>.</sub>

**Comment by brianteeman** [comment]
No not really.

**Comment by LivioCavallo** [comment]
The problem is: such a page does not validate.
I propose two ways to SOLVE it:

- This PR solves the problem: the page validates.
- The Suggestion above _(https://github.com/joomla/joomla-cms/pull/17670#issuecomment-324352538 : "... to emit the Page_Title `<h2>` anyway, eventually hidden (just as I suggested in PR #17686), so to grant this sequence: Page_header `<h1>` -> (eventually hidden) Page_Title `<h2>` -> eventually followed by Article Index `<h3>`...")_ solves the problem: the page validates.

Please, comment on which one is better or why they are not acceptable solutions (the fact that there are many other problems is not an argument, in my humble opinion).

**Comment by brianteeman** [comment]
> I am not in favour of this PR as it will change the output of a users site and they have no easy way to see how to change it

I dont think this can ever be "fixed" in the core as it is very site configuration specific

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by brianteeman** [comment]
PS I have been educated now that it is an a11y issue. I still have concerns about changing it as we are also effecting the display of a users web site

**Comment by ReLater** [comment]
Maybe you like this pr that uses override possibilllity of plugins:
https://github.com/joomla/joomla-cms/pull/20202

**Comment by ReLater** [comment]
We just need one more test for pr https://github.com/joomla/joomla-cms/pull/20202 .
If it gets merged users and template creators have the possibility to use any HTML tag they want in a template override for the article TOC or use conditions or.... And it's B\C.

**Comment by ReLater** [comment]
@LivioCavallo 
We just need one more test for pr https://github.com/joomla/joomla-cms/pull/20202 .
If it gets merged users and template creators have the possibility to use any HTML tag they want in a template override for the article TOC or use conditions or.... And it's B\C.

**Comment by Quy** [comment]
Please close per Brian's comment/concern.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17670">issues.joomla.org/tracker/joomla-cms/17670</a>.</sub>

**Pull request closed without merging**
