### PR TITLE
[4.0] Add category caching to routers

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27073.

### Summary of Changes

Adds category caching in routers to reduce number of queries.

### Testing Instructions

Create some content or install sample data.
Navigate article/contact/newsfeeds pages.

### Expected result

Still works.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
This makes sense as a compromise for me as these are always readonly on the categories object

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 49fc58b32ea33656f6c400c0704660c57c5fa542<br /><br />Tested com_contacts, com_newsfeed, and com_article on frontend and backend. No issues after applying PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27710">issues.joomla.org/tracker/joomla-cms/27710</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ Can we be sure that there is not any outdated information used from the cache? What if some admin deleted a category? Maybe it's a silly question. I don't really know when a router instance is created so the cache variable is created.

**Comment by SharkyKZ** [comment]
This cache doesn't persist across requests. It's possible for a category to be deleted within the same request (e.g. if it's deleted automatically or if you delete it yourself) between instantiating the router and building the link. But so far this hasn't been an issue.

**Comment by richard67** [comment]
@SharkyKZ Thanks for clarification. Will test later.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 49fc58b32ea33656f6c400c0704660c57c5fa542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27710">issues.joomla.org/tracker/joomla-cms/27710</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27710">issues.joomla.org/tracker/joomla-cms/27710</a>.</sub>

**Pull request merged**
