### PR TITLE
[4.0] MOD_LATESTACTION strings

### PR DESCRIPTION
**Pull request by brianteeman**
Rename keys so they all have the same (correct) prefix

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5f7a99a6af566791c100e98c1b311c5c6f6a28b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27423">issues.joomla.org/tracker/joomla-cms/27423</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5f7a99a6af566791c100e98c1b311c5c6f6a28b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27423">issues.joomla.org/tracker/joomla-cms/27423</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27423">issues.joomla.org/tracker/joomla-cms/27423</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thnks

**Pull request merged**
