### PR TITLE
InputFilter fails on cleaning string with HEX entities as string

### PR DESCRIPTION
**Pull request by AlterBrains**
### Summary of Changes

`InputFilter::clean($string, 'string')`  fails when decoding the entities with HEX numbers

### Testing Instructions

Execute the code:
```php
$filter = \Joomla\CMS\Filter\InputFilter::getInstance();
var_dump($filter->clean('&#xff;', 'string'));
die;
```

### Actual result BEFORE applying this Pull Request

See error `chr(): Argument #1 ($codepoint) must be of type int, string given`

### Expected result AFTER applying this Pull Request

No errors.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on fee33cb85ecb880ccc873e5fc2ecbfa833a6570f<br /><br />Hi AlterBrains, I have tested this successfully.

It yields the answer of: string(2) "ÿ" so if that is expected - perfect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43377">issues.joomla.org/tracker/joomla-cms/43377</a>.</sub>

**Comment by richard67** [comment]
I've restored @exlemor 's test result in the issue tracker so it's properly counted again. The commits which have invalidated the count were just clean branch updates.

> It yields the answer of: string(2) "ÿ" so if that is expected - perfect.

@exlemor Yes, that character fits to the Unicode character given as hexadecimal number. See e.g. https://www.w3schools.com/charsets/tryit.asp?deci=255&ent=yuml .

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3d3e148d71f455eb534b2f0e51cafcd9197677b3<br /><br />Works as described. In addition, I've tested that decimal values like `'&#255;'` and entity names like `'&yuml;'` continue to work as before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43377">issues.joomla.org/tracker/joomla-cms/43377</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43377">issues.joomla.org/tracker/joomla-cms/43377</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
