### PR TITLE
[4.0] Minimum Stability info

### PR DESCRIPTION
**Pull request by brianteeman**
This PR restores the description of minimum stability to the extension installer AND corrects the text of the description of minimum stability to the joomla updater

### Before
image

### After
image

### Before
image

### After
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7690ba6ec013925e624009d8f81755cd29f4be00<br /><br />Tested successfully in Beta6-dev of 27 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31501">issues.joomla.org/tracker/joomla-cms/31501</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7690ba6ec013925e624009d8f81755cd29f4be00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31501">issues.joomla.org/tracker/joomla-cms/31501</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31501">issues.joomla.org/tracker/joomla-cms/31501</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
