### PR TITLE
Sync frontend en-GB.lib_joomla.ini with changes made in backend.

### PR DESCRIPTION
**Pull request by Bakual**
The en-GB.lib_joomla.ini in frontend is out of sync with the same file in backend.
until now, they were identical and translators could just copy-paste it.
Thanks to @imanickam to catch that.

This PR copies the content from the backend file to the frontend file.
Main difference is the added strings from #7637:

```
JLIB_HTML_BATCH_MOVE_QUESTION="Do you want to move the items or make a copy of them?"
JLIB_HTML_BATCH_NO_CATEGORY="- Don't move or copy -"
```

However there are a lot of punctuation changes which are most likely coming from #5615. From what I see there were some changes in that PR which only were did in one of the two files.
I need input here which changes are correct and which should be reverted and thus be fixed in the backend file. @brianteeman can you look over it?

### CODE REVIEW

**Comment by Bakual** [comment]
Updated with corrections by @brianteeman (Thanks!)

**Comment by infograf768** [comment]
I suggest to merge this asap and let it know to TTs (mainly the 2 new strings).

**Comment by Bakual** [comment]
I'll check with @imanickam if he wants them merged now or for 3.4.5.
The new strings are already present in the backend and not used in frontend. So there is no hurry to merge it.

**Comment by infograf768** [comment]
@Bakual
Some TTs have only a frontend lib_joomla.ini and therefore it has to be told to them or they will not get the 2 new strings.

**Comment by infograf768** [comment]
This is for packs who have only a limited backend inis:
See: 

https://docs.joomla.org/J3.x:Making_a_Language_Pack_for_Joomla#The_Site-only_pack

**Comment by infograf768** [comment]
But, you are right, these will not be used in that case. You decide.

**Comment by infograf768** [comment]
Hmm, no. I was right.
The site lib_joomla.ini is loaded first if it exists.
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L665-L671
This has to be ASAP told to TTs.

**Comment by infograf768** [comment]
forget it, it can wait if judged necessary. as in admin is loaded only the admin file.

**Comment by Bakual** [comment]
Merged after chatting with @imanickam

**Pull request closed without merging**
