### PR TITLE
remove extra fieldset

### PR DESCRIPTION
**Pull request by wojsmol**
Redo of #9053 by @N6REJ

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 36e00718015bdfbaefa589df2b8f3348fb254468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9055">issues.joomla.org/joomla-cms/9055</a>.</sub>

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 36e00718015bdfbaefa589df2b8f3348fb254468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9055">issues.joomla.org/joomla-cms/9055</a>.</sub>

**Comment by wojsmol** [comment]
@richard67 @n9iels Thank you for testing. @brianteeman Two successful tests - please add RTC label.

**Comment by N6REJ** [comment]
@wojsmol why was a new pr and ticket made?

**Comment by wojsmol** [comment]
Please note the number of commits in https://github.com/joomla/joomla-cms/pull/9053. Your branch 9052 is out of date in relation to the branch staging from joomla-cms repository. See comment by @brianteeman https://github.com/joomla/joomla-cms/pull/9053#issuecomment-179106003

**Comment by infograf768** [comment]
rtc. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9055">issues.joomla.org/joomla-cms/9055</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks guys!

**Pull request merged**
