### PR TITLE
Update com_users.ini

### PR DESCRIPTION
**Pull request by joomleb**
Hi guys,
the language string
COM_USERS_PROFILE_VALUE_NOT_FOU=”Website default”

It is used in User Profile fields page when the user still has not choose any value (left it empty).

It would be really better as: ”Not configured" or something similar,

Do you agree ?

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
In fact, everything is "Configured", i.e. leave the language the same as on the site.

**Comment by brianteeman** [comment]
I dont see why you would want to change it. This pattern is used throughout joomla.

**Comment by joomleb** [comment]
Hi guys, 
"Website default" it is a good choice for most of the Joomla "Frontend User Parameters", but, as far as I know it is the standard language string that have to be used by all the 3rd party User Profile plugins, Am I right ?

Often, are fields that have no a "default" setting, just the user still has not input any value (he left it empty a no mandatory field). Like for example "Birthday", "Address" etc. In this cases "Website default" sounds inappropriate.

While "Not configured" (or similar) could cover both cases. This is why...

**Comment by brianteeman** [comment]
> "Website default" it is a good choice for most of the Joomla "Frontend User Parameters", but, as far as I know it is the standard language string that have to be used by all the 3rd party User Profile plugins, Am I right ?

Please give an example of such a plugin. I dont see why they cannot use their own language strings.

> Often, are fields that have no a "default" setting, just the user still has not input any value (he left it empty a no mandatory field). Like for example "Birthday", "Address" etc. In this cases "Website default" sounds inappropriate.

It is inappropriate but I dont see why it i using that string

**Comment by joomleb** [comment]
Hi @brianteeman 
sure, you can see it in action going [here](https://clone.egulp.net/login-en-gb)
Login with emlnbrtl@gmail.com / emlnbrtl@gmail.com
and then surf to the [Profile page](https://clone.egulp.net/mi-settings)
- The "Events" Private Token field is from [DPCalendar](https://joomla.digital-peak.com/products/dpcalendar) by @laoneo 
- The "Tourism" fields are from [Soldiers](https://www.solidres.com/) by @vietvh 

Anyway,

"...I don't see why they cannot use their own language strings..." = In my opinion it is a good thing _to have a standard language string for 3rd party Extensions_ to be used **for empty** fields. Like: "Not configured".

While for all the fields that when not yet settled they redirect to a "site default value" would be really better, as a Joomla rule, just to show the default value and not the written "site default".
A developer and a Joomla backend Administrar they sure know what is the "default" value, but a _"normal" User_ that is Registering / Editing his Profile in a Joomla Frontend site does not know what is the "default value" and then know and decide whether to change it.

So, for example:
- Time Zone: Website default
- Frontend Language: Website default

Would be shown directly as:
- Time Zone: UTC-5
- Frontend Language: Spanish

Where "UTC-5" and "Spanish" are the default values

**Comment by brianteeman** [comment]
> "...I don't see why they cannot use their own language strings..." = In my opinion it is a good thing to have a standard language string for 3rd party Extensions to be used for empty fields. Like: "Not configured".

Not configured but _using a default value_ and not configured _so no value is used_ are not the same thing.

The string in this PR is always used to indicate that a default value is being used.

If an extension is using it for another purpose (in error) then you should take that up with them.

> While for all the fields that when not yet settled they redirect to a "site default value" would be really better, as a Joomla rule, just to show the default value and not the written "site default".

agree 100% but thats off topic for this PR

**Comment by joomleb** [comment]
Hi @brianteeman 
"...The string in this PR is always used to indicate that a default value is being used..." = Please, Am I missing a specific language string yet existing for the "not configured so no value is used are not the same thing" ? 
Because I looked for it without success before to open this PR and being that the Language String name is COM_USERS_PROFILE_VALUE_NOT_FOU=, "not found", I thought it doesn't exist.

"...agree 100% but thats off topic for this PR..." = Please, Will you escalate this one and/or Do I have to open a Discussion/PR ?

**Comment by brianteeman** [comment]
SORRY!!!

I just checked the core user profile plugin. 

I expected it to display like this

image


But it actually displayed as 
image


So you are 100% correct and there is a problem. I just think your solution may not be the best. I will take a look at it now.

**Comment by brianteeman** [comment]
... and full disclosure it was ME that broke this behaviour https://github.com/joomla/joomla-cms/pull/25699

As you can see from that PR the string was changed for a good reason but it had unexpected consequences which you have found (suprised no one else spotted it before).

In summary its a valid issue but needs something more than a language string change to fix it

**Comment by joomleb** [comment]
Well, about the "good reason", the "...Far better to say "Website default" as at least that way there is no confusion to the user. In the form they "selected" the -use default - option so to their understanding they have made a selection..." = For these fields there is no the option to do not select nothing, to leave them empties, so from a Normal User point of view, it does not matter if I selected / input it or not, what is important is to know **what it is**, the value that is running. Don't forget that these fields could be not only private fields, but also public fields that all other users can view.

My personal point of view is "less words as possible", _so it is yet multilanguage and mobile ready_ (saving layout space). For that reason I would apply the rules:

- For all the fields that when not yet setted they redirect to a "site default value" = just to show the default value and not the written "site default".
- For all fields that can be left empty = just to don't show nothing, any value, left it empty.

simple, painless, efficient.

About the "SORRY!!!" and the "surprised no one else spotted it before" (me too) - There is no any problem. I perfectly understand you. I'm not a real developer, but I'm here from the first day, August 2005, living the Mambo splitting. It can happen. Often because you are focused on hard core development, while I'm focused on my "normal" Users Experience.
Many times details that for you are "nothing", for my Users are "panic".
Our marketing experiences statistics says that the most difficult pass for our success sites is to convince the User to a "Free Register now", so on last month's I just focused on it and in fact I opened a lot of issues/suggestions tickets here with the goal of a smoother secure Registration, Login/Logout user experience...

**Comment by brianteeman** [comment]
Please take a look at #41513

**Comment by brianteeman** [comment]
Please test the pull request I created. I believe it solves all your issues.

**Comment by brianteeman** [comment]
You're not missing anything - something went wrong building the packages. I have retriggered the process

**Comment by brianteeman** [comment]
You can download thenm now https://ci.joomla.org/artifacts/joomla/joomla-cms/4.3-dev/41513/downloads/69080/

**Comment by joomleb** [comment]
@brianteeman 
I updates the [Test site](https://github.com/joomla/joomla-cms/pull/41435#issuecomment-1696016994) 

**Frontend**

> For all fields that can be left empty = just to don't show nothing, any value, left it empty.

Are you sure the rule is applying by default also on the Users Joomla Custom Fields ? 
I created a Calendar (Birthday) Joomla Custom Field and "Website Default"is still shown.

> For all the fields that when not yet setted they redirect to a "site default value" like the "Basic Settings" fields (Time Zone, Frontend Language,...)  = just to show the default value and not the written "site default".

Right now also here it is showing nothing as above, instead to show the value

**Comment by brianteeman** [comment]
> I created a Calendar (Birthday) Joomla Custom Field and "Website Default"is still shown.

I can not replicate that with the pull request applied

image

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Pull request closed without merging**
