### PR TITLE
Fixing URL to contact VCF

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The link for the VCF file for a contact is wrong.

### Testing Instructions
Go to the contact component and enable showing the VCF link to a contact. Click on that link in the frontend.

### Actual result BEFORE applying this Pull Request
You get a 404.

### Expected result AFTER applying this Pull Request
You get the correct file.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on a18f861ab0acbe8588641360abfae8303eaa9fb2<br /><br />The link to the vCard worked every time with or without this PR, as show below.
Using Joomla 4.2.9-dev of 26 February and PHP 8.1.10 in Wampserver.

**SEF URLs and URL rewriting enabled**
before PR: http://joomla4test/contact?format=vcf
after PR: http://joomla4test/contact?format=vcf

**SEF URLs and URL rewriting not selected**
before PR: http://joomla4test/index.php?option=com_contact&view=contact&id=1&format=vcf&Itemid=150
after PR: http://joomla4test/index.php?option=com_contact&view=contact&catid=9:webmasters&id=1:toivo&format=vcf&Itemid=150

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39938">issues.joomla.org/tracker/joomla-cms/39938</a>.</sub>

**Comment by Hackwar** [comment]
I'm sorry, I was a bit in a rush when I wrote all of this. The URL can be right by accident, however it fails when you have a menu item to a category of contacts and the contact is in a child category of that first category.

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on a18f861ab0acbe8588641360abfae8303eaa9fb2<br /><br />@hackwar, thank you for the detailed description.
Tested successfully in Joomla 4.2.9-dev of 2 March in PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39938">issues.joomla.org/tracker/joomla-cms/39938</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a18f861ab0acbe8588641360abfae8303eaa9fb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39938">issues.joomla.org/tracker/joomla-cms/39938</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39938">issues.joomla.org/tracker/joomla-cms/39938</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you!

**Pull request merged**
