### PR TITLE
[4.0] remove deprecated files

### PR DESCRIPTION
**Pull request by brianteeman**
Removes files for com_modules deprecated in 3.7 #16152

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by brianteeman** [comment]
@wilsonge the PR to mark these as deprecated is now RTC so this can be safely merged

**Comment by wilsonge** [comment]
Thanks :) Merged both!

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
oops mea culpa - i deprecated and removed the wrong file - it should have been preview and position not preview and select

**Comment by wilsonge** [comment]
OK This one I have reverted :)

**Pull request merged**
