### PR TITLE
Consistency in column headings

### PR DESCRIPTION
**Pull request by brianteeman**
Throughout joomla the ID column just as a heading ID. But in the new com_installer&view=updatesites the heading is Update Site ID.

This simple PR makes the strings consistent as simply ID

### CODE REVIEW

**Comment by infograf768** [comment]
Instead of modifying the value of the string, it would be better to use a Global string:
JGRID_HEADING_ID="ID"

**Comment by seagul30** [comment]
Tested the patch - it's working!
Column ID for Updatesites is now "ID".

Also checked that I can override the template string "JGRID_HEADING_ID" - is not working.
So I guess there is not yet a global string.

Is that going to change?
If not, I can set me test result to successful.

Please let me know.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6075">issues.joomla.org/joomla-cms/6075</a>.</sub>

**Comment by infograf768** [comment]
@seagul30 
The suggestion is to change the code to use JGRID_HEADING_ID instead of modifying the value.
I.e. change in ROOT/administrator/components/com_installer/views/updatesites/tmpl/default.php, line 69:

`<?php echo JHtml::_('grid.sort', 'COM_INSTALLER_HEADING_UPDATESITEID', 'update_site_id', $listDirn, $listOrder); ?>`
to
`<?php echo JHtml::_('grid.sort', 'JGRID_HEADING_ID', 'update_site_id', $listDirn, $listOrder); ?>`

it gives the correct rendering:
screen shot 2015-02-17 at 07 10 43

**Comment by imanickam** [comment]
This is true even in the screen "Extension Manager: Update Sites".  The column heading for the ID is "Update Site ID".

Shall we also make this as ID?  If so, a separate Issue Tracker has to be created?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6075">issues.joomla.org/joomla-cms/6075</a>.</sub>

**Comment by brianteeman** [comment]
There was a discussion at the time about this. Sorry I am not at my PC so
can't find it but it is on the tracker somewhere

**Comment by nonumber** [comment]
I would agree with JM.
The ```JGRID_HEADING_ID``` should be used. And the ```COM_INSTALLER_HEADING_UPDATESITEID``` string can be removed from the language files.

**Comment by nonumber** [comment]
PS: Same thing for ```COM_INSTALLER_HEADING_ID```.

**Pull request closed without merging**
