### PR TITLE
[cpanel modules] Align dates and add tooltips

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

In CPanel modules (mod_logged, mod_latest and mod_popular):
- Adds and uniformizes tooltip (indicating that is the created date) on dates.
- Uniformizes the modules alignment.
- Uniformizes the date format (added a new LC5 `Y-m-d H:i` date).
- Right align the dates

Before
image

After
image
#### Testing Instructions
1. Use joomla staging with test sample data
2. Go to CPanel check the align and the date tooltips in the 3 modules
3. Apply patch
4. Go to CPanel check the align and the date tooltips in the 3 modules

@brianteeman please check now

### CODE REVIEW

**Comment by brianteeman** [comment]
I really dont see the need for this change

**Comment by andrepereiradasilva** [comment]
why? this is the homepage of the admin and IMO it's clearly disaligned.

Also what is that date (published? modified? created?)?
now the tooltip informs the user that is the Created date

Another example:

Before
image

After
image

**Comment by brianteeman** [comment]
> this is the homepage of the admin

That depends on the sample data installed



On 10 May 2016 at 14:52, andrepereiradasilva <notifications@github.com>
wrote:

> why? this is the homepage of the admin and IMO it's clearly disaligned.
>
> Also what is that date (published? modified? created?)?
> now the tooltip informs the user that is the Created date
>
> Another example:
>
> Before
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15148780/b9cd0d7c-16be-11e6-90ec-18690f3e6822.png>
>
> After
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15148764/ad1a4f54-16be-11e6-81c5-5409535776c9.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10385#issuecomment-218163526>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
yes i know. is just to exemplify.

**Comment by zero-24** [comment]
Moving to `Needs review` so a maintainer can take a decision here. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10385">issues.joomla.org/joomla-cms/10385</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 9850d82d522d4d9c74aa94a6f91a40e5462b4e54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10385">issues.joomla.org/joomla-cms/10385</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 9850d82d522d4d9c74aa94a6f91a40e5462b4e54<br /><br />Don't know if users need this but #10385 works as descibed and I really do prefer the "new" logged-in users - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10385">issues.joomla.org/joomla-cms/10385</a>.</sub>

**Comment by sonalitasol** [comment]
I have tested this item :white_check_mark: successfully on 9850d82d522d4d9c74aa94a6f91a40e5462b4e54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10385">issues.joomla.org/joomla-cms/10385</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge @rdeutz can you take a decision here?

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 9850d82d522d4d9c74aa94a6f91a40e5462b4e54<br /><br />Tested this.
I looks much better.
Please add this UX fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10385">issues.joomla.org/joomla-cms/10385</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Needs Review  ...

**Comment by andrepereiradasilva** [comment]
can a mantainer please take a decision here? merge or close?

**Comment by andrepereiradasilva** [comment]
thanks

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
