### PR TITLE
[com_redirect] links view: searchtools ordering, bug corrections and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_redirect links view.

Also:
- moves the system messages to the view (removes then from the template)
- fixes several bugs in searchtools
- correct visual on mobile, tablet and desktop
- other small graphical issues.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Install latest staging and apply this patch
2. Go to Components -> Redirect
3. Check the message with and without redirect plugin enabled, and with or without collect URL enabled.
4. Check the search, filtering, ordering and limits are working fine.
5. Test desktop, tablet and mobile view (ex: reduce browser width).

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
the travis error is something related top PHP not related to this PR i think

```
$ phpenv global 7.0
rbenv: version `7.0' not installed
The command "phpenv global 7.0" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by mbabker** [comment]
Probably related to http://news.php.net/php.internals/92406

**Comment by andrepereiradasilva** [comment]
yeah it seems so, thanks

**Comment by andrepereiradasilva** [comment]
now it's ok.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c61530b1686dbbfb3111c2bbe618011dfbd09fa9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9971">issues.joomla.org/joomla-cms/9971</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on c61530b1686dbbfb3111c2bbe618011dfbd09fa9<br /><br />After applying the patch the "Batch" button on the toolbar is removed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9971">issues.joomla.org/joomla-cms/9971</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> After applying the patch the "Batch" button on the toolbar is removed

Ahh? it's not removed....

image

**Comment by brianteeman** [comment]
It is for me - will check to make sure I am on current staging

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on c61530b1686dbbfb3111c2bbe618011dfbd09fa9<br /><br />Thanks
(Batch's here for me)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9971">issues.joomla.org/joomla-cms/9971</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c61530b1686dbbfb3111c2bbe618011dfbd09fa9<br /><br />Weird - must have been something in my install. ITs all ok. Sorry for confusion<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9971">issues.joomla.org/joomla-cms/9971</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9971">issues.joomla.org/joomla-cms/9971</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@MATsxm @brianteeman thanks for testing!

**Pull request merged**
