### PR TITLE
[4] s/Add/Added when adding a user to a group by CLI

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

s/Add/Added

### Testing Instructions

php cli/joomla.php user:addtogroup

### Actual result BEFORE applying this Pull Request

Screenshot 2021-04-02 at 14 04 07

### Expected result AFTER applying this Pull Request

` [OK] Added 'admin' to group 'Administrator'!`

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ead5e56744ac4fd6cb37275fa518830be8606d85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32964">issues.joomla.org/tracker/joomla-cms/32964</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ead5e56744ac4fd6cb37275fa518830be8606d85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32964">issues.joomla.org/tracker/joomla-cms/32964</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32964">issues.joomla.org/tracker/joomla-cms/32964</a>.</sub>

**Comment by Quy** [comment]
Thanks,

**Pull request merged**
