### PR TITLE
[4.2] tabs to spaces

### PR DESCRIPTION
**Pull request by brianteeman**
Looks like these files were missed when @hleithner did the conversion

Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
> Looks like these files were missed when @HLeithner did the conversion

More has gone wrong, for example look at the if-statements. The curly braces are still in the old place.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39145">issues.joomla.org/tracker/joomla-cms/39145</a>.</sub>

**Comment by brianteeman** [comment]
> > Looks like these files were missed when @HLeithner did the conversion
> 
> More has gone wrong, for example look at the if-statements. The curly braces are still in the old place.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/39145](https://issues.joomla.org/tracker/joomla-cms/39145).

maybe but as the description says - this is for tabs and spaces.

**Comment by HLeithner** [comment]
@roland-d or @fancyFranci this can be merged after release or if you like before.

**Review by HLeithner — APPROVED** [review]

**Comment by fancyFranci** [comment]
Thank you for cleaning it up :)

**Pull request merged**
