### PR TITLE
Removing the notice when a global value is not found.

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #12782.

### Summary of Changes
Removing the notice when the global value isn't found (not yet saved) as it is more confusing to users than it helps.

### Testing Instructions
On a new install, create a menu item for com_content or edit an article.
You should see a notice that no global value was found. Reason is that either component settings, com_menu settings or global settings aren't saved yet.
After PR this message no longer appears.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a917fc27987839451a4d9c17c92f404b2f30a72e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12858">issues.joomla.org/tracker/joomla-cms/12858</a>.</sub>

**Comment by andrepereiradasilva** [comment]
unable to mark as tested because of "sha thing"

But, works as described.
Althoug i think that we should use something like "Use Global (Unable to calculate)" or something

**Comment by zero-24** [comment]
@mbabker here is no sha. So it is not the JS Cache thing.

screen shot 2016-11-11 at 08 25 24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12858">issues.joomla.org/tracker/joomla-cms/12858</a>.</sub>

**Comment by mbabker** [comment]
I realize this and I still have no idea what is causing it because everything that I have traced shows it being correctly sent/set.  I don't need to be @ mentioned every time.

I'm also only one person, the code is open source, anyone's welcome to help try to figure out the issue (hint, it's not the controller processing that save action, it's something saving the data somewhere in the tracker component ("app")).

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on a917fc27987839451a4d9c17c92f404b2f30a72e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12858">issues.joomla.org/tracker/joomla-cms/12858</a>.</sub>

**Comment by zero-24** [comment]
It should not sound agressive jut to inform you. If you don't need that i'm ok with that :+1:

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12858">issues.joomla.org/tracker/joomla-cms/12858</a>.</sub>

**Comment by mbabker** [comment]
Believe it or not I read almost every email notification I get for this repo, so I see most of the activity (and the failures).  The thing is though it gets kinda annoying when I get "@mbabker it's broken" messages consistently, all it takes is a simple comment or opening an issue on the issue tracker's tracker and I can jump into it when I get a moment.  About the only thing I don't have is email notifications from the tracker app itself on a fail condition.

**Comment by dgt41** [comment]
@zero-24 can you point me to the relative script for the sha?

**Comment by mbabker** [comment]
I think the SHA thing is fine now.  The issue model's save method was accidentally coded to remove a few fields if they weren't passed in with the save data (fixed that an hour ago).  We'll see what happens.  I really wish I would've followed through on rewriting the thing and getting it into a testable state.

**Comment by brianteeman** [comment]
Thank you for your time on this Michael

**Pull request merged**
