### PR TITLE
[3.9] modify installer to allow additional query params

### PR DESCRIPTION
**Pull request by clayfreeman**
### Is your feature request related to a problem? Please describe.

Components are unable to specify additional query parameters when defining primary admin menu items in the manifest file. Submenu items, however, are able to specify additional query parameters.

### Describe the solution you'd like

Patch [this file] to allow additional query parameters as specified in the component manifest, similar to [how it is done for submenu items]. See the [changes in this pull request] to apply the patch and test it.

### Additional context

It should be possible to build components without the use of a "generic" controller that defines a default view. Menu items should be able to specify the `task` and `view` query parameters so that there is no ambiguity as to which controller and view class should be used.

#### Example

`task` and `view` can now be set in the primary menu item so that the default administration controller doesn't have to be used for the primary menu item.

```xml
<administration>
  ...
  <menu task='test.display' view='test'>Test</menu>
  ...
</administration>
```

For a component `com_blah`, the above code example will create a menu item that points to `index.php?option=com_blah&task=test.display&view=test`. This means that `BlahControllerTest`, `BlahModelTest` and `BlahViewTest` will be used to handle the request as opposed to the generic, component-wide `BlahController` and its `BlahView$default_view` class.

[this file]: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Adapter/ComponentAdapter.php#L969
[how it is done for submenu items]: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Adapter/ComponentAdapter.php#L1044
[changes in this pull request]: https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/21309.diff

### CODE REVIEW

**Comment by wilsonge** [comment]
I can see why you would want to allow task/view as you described in your issue (although don't feel strongly about it). However neither act nor sub are things used in core therefore I definitely am against them being magically whitelisted when they have no definition.

**Comment by clayfreeman** [comment]
@wilsonge I've stripped down the list of allowed parameters. Please see my revision.

**Comment by clayfreeman** [comment]
I'm not quite sure why the AppVeyor build failed; logically there was no difference from that merge commit.

Regardless, is there an update on this?

**Comment by ghost** [comment]
@clayfreeman next this PR needs two sucessfully Tests.

**Comment by clayfreeman** [comment]
By Joomla developers or community members?

I have been running this patch for days with no issue.

**Comment by ghost** [comment]
Everyone can test (Test by PR-Creator doesn't count as its expected that he test before create Pull Request).

Edit: Its helpful to give Instructions for Tester in the PR, a Link to an Issue without Instructions isn't helpful to know what to test.

**Comment by ghost** [comment]
Changed Title to show its about 3.9.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21309">issues.joomla.org/tracker/joomla-cms/21309</a>.</sub>

**Comment by mbabker** [comment]
> By Joomla developers or community members?
> 
> I have been running this patch for days with no issue.

All patches must be tested/reviewed by at least two people other than the person who submitted the pull request.

**Comment by travisrisner** [comment]
I have tested this item :white_check_mark: successfully on adf71c792272d875180ff570a0f2523d23e860ec.

**Comment by jeremyvii** [comment]
I have also tested this item :white_check_mark:  successfully on adf71c792272d875180ff570a0f2523d23e860ec.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thankyou for your first contribution to the CMS!

**Pull request merged**
