### PR TITLE
[4.0] Bootstrap 5.01

### PR DESCRIPTION
**Pull request by brianteeman**
This PR updates bootstrap to 5.0.1

As expected there are numerous bug fixes - see https://github.com/twbs/bootstrap/releases/tag/v5.0.1

### CODE REVIEW

**Comment by richard67** [comment]
@dgrammatiko Maybe you can help here: The javascript linter consistently fails with:
```
+ npm run lint:js

> joomla@4.0.0 lint:js
> eslint --config build/.eslintrc --ignore-pattern '/media/' --ext .es6.js,.es6,.vue .


Oops! Something went wrong! :(

ESLint: 7.26.0

TypeError: Cannot read property 'type' of null
Occurred while linting /********/src/build/media_source/vendor/bootstrap/js/index.es6.js:11
    at isExportNameClass (/********/src/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:51:69)
    at checkForNewLine (/********/src/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:79:45)
    at checkImport (/********/src/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:133:9)
    at /********/src/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/********/src/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/********/src/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/********/src/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/********/src/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/********/src/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
```

**Comment by brianteeman** [comment]
The linter really shouldnt be running on vendor files

**Comment by dgrammatiko** [comment]
Emh, the PR is missing the required update in the package.json...

**Comment by brianteeman** [comment]
oh - oops

**Comment by richard67** [comment]
Sometimes when I'm blind I'm at least lucky enough to ping the right people 😄

**Comment by richard67** [comment]
@dgrammatiko The linter still fails with the same error.

**Comment by brianteeman** [comment]
I was sure it wasn't me as I had to manually edit the package.json and shouldnt have needed to make a change their.

The linter is correct.

We should not be running the linter on code that is not ours to correct

**Comment by dgrammatiko** [comment]
@richard67 I have 0 clues why this failed here as  https://github.com/joomla/joomla-cms/pull/33901 it seems fine

**Comment by richard67** [comment]
I have no clue either.

**Comment by brianteeman** [comment]
Might as well close this one then. very odd.

I still dont think our tools should run the linter on vendor files

**Comment by dgrammatiko** [comment]
> We should not be running the linter on code that is not ours to correct

WE AREN'T! We only lint things in the `build/media_src` which obviously is Joomla's own code

**Comment by brianteeman** [comment]
sorry - I misread the file - /me crawls under a stone

**Comment by dgrammatiko** [comment]
Np, fwiw this wasn't a lint problem but rather an inconsistent version of BS in pagage.json and package.lock

**Pull request closed without merging**
