### PR TITLE
[4.0] Missing field classes in forms

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Replaces outdated `addfieldpath` uses with `addfieldprefix`, fixing class loading in some forms.
Also removes unneeded `addfieldpath` uses.

### Testing Instructions

Code review.
Or go to some of the affected forms.
Notice that before patch some fields appear as empty text field when they shouldn't.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5f6236c3a8a15aeb9debf4f5c71558fdb7b94a24<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28274">issues.joomla.org/tracker/joomla-cms/28274</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5f6236c3a8a15aeb9debf4f5c71558fdb7b94a24<br /><br />PR tested and works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28274">issues.joomla.org/tracker/joomla-cms/28274</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28274">issues.joomla.org/tracker/joomla-cms/28274</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
