### PR TITLE
Code Style

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Code Style improvements .
#### Summary of Changes
- When splitting array definitions onto several lines, the last value should also have a trailing comma.
- Broke a few lines into multiline just for easier reading.
#### Testing Instructions

Can be merged by code review.

Testing if desired would be to apply the patch and then check that the system info panel works as expected in admin

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c473205c10fa777c2b1f482a77102e6fab349b47<br /><br />tested component still works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10454">issues.joomla.org/joomla-cms/10454</a>.</sub>

**Comment by zero-24** [comment]
I have not tested this item.<br /><br />Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10454">issues.joomla.org/joomla-cms/10454</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10454">issues.joomla.org/joomla-cms/10454</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 I think you need to alter your test :(😂

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c473205c10fa777c2b1f482a77102e6fab349b47<br /><br />lol. Thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10454">issues.joomla.org/joomla-cms/10454</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Comment by photodude** [comment]
Thanks everyone

**Pull request merged**
