### PR TITLE
[4.0] Toolbar position on scroll (sidebar opened)

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
When the sidebar is opened the toolbar shifts position on scroll. This PR fixes it.

### Testing Instructions
Scroll down on any page when the sidebar is opened.

### Before patch
toolbar-scroll1

### After patch
toolbar-scroll2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by C-Lodder** [comment]
@wilsonge can be merged

**Comment by wilsonge** [comment]
Conflicts with the other merges I've done. Can we fix please

**Comment by ciar4n** [comment]
Fixed!

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
