### PR TITLE
[4.0] FIX Attempting to delete viewing access level gives double feedback

### PR DESCRIPTION
**Pull request by amitranjan2**
Pull Request for Issue #22790.

### Summary of Changes

deleted some extra code and added one condition

### Testing Instructions

Login to admin of Joomla 4.0-dev
administrator/index.php?option=com_users&view=levels
Select box next to special
click delete
click ok

### Expected result
image

One Warning message

### Actual result
Two identical messages 
image

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by amitranjan2** [comment]
@PhilETaylor 
please review this

**Comment by amitranjan2** [comment]
@brianteeman similar issue is also available  in Joomla stagging
should i do first issue for that  and then PR for that also?

**Comment by amitranjan2** [comment]
@infograf768 @C-Lodder @Anu1601CS 
 what do you think ? please review

**Comment by C-Lodder** [comment]
@amitranjan2 I'm not a PHP dev so will leave it up to more experienced people than me to review.

**Comment by amitranjan2** [comment]
@Quy  could you please review and test this?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e6ad382a70d14a7f0cf166a2c655dbb98d773f5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23724">issues.joomla.org/tracker/joomla-cms/23724</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 31512736965d65cacebe058b9cae2b5365a3f16b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23724">issues.joomla.org/tracker/joomla-cms/23724</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23724">issues.joomla.org/tracker/joomla-cms/23724</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
