### PR TITLE
Update FLoC links

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #34595

### Summary of Changes

Link text should always be unique and meaningful so it could be understood out of context. Thanks @brianteeman 

### Testing Instructions

Check the postinstall message about FLoC

### Actual result BEFORE applying this Pull Request

Links have more context.

### Expected result AFTER applying this Pull Request

Links are not marked by "here"

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 16244a06d97218100e717c6c69c92bdd10bdf2f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34596">issues.joomla.org/tracker/joomla-cms/34596</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 16244a06d97218100e717c6c69c92bdd10bdf2f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34596">issues.joomla.org/tracker/joomla-cms/34596</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34596">issues.joomla.org/tracker/joomla-cms/34596</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
