### PR TITLE
[4.0] Remove "new" MVC classes v2

### PR DESCRIPTION
**Pull request by Hackwar**
This is a redo of #24714.

With Joomla 3.0, a new set of classes was introduced as a replacement for the old MVC classes. These new classes never gained traction. The number of extensions that are really build on these classes can most likely be counted on one hand and as far as I know, the JED is one of them.

In order to clean up our codebase and stop people from being confused, I'm proposing to remove these classes now and not wait until 5.0.

### CODE REVIEW

**Comment by brianteeman** [comment]
Surely it is too late for this. The version that will contain the deprecation notice is released on the same day

**Comment by richard67** [comment]
> 
> 
> Surely it is too late for this. The version that will contain the deprecation notice is released on the same day

@brianteeman That would be true if he wanted to add the deprecation notice to 3.10. But he wants to add it to staging.

**Comment by brianteeman** [comment]
That would be against semver

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/issues/28249 As per my note here this is in front of production to vote on at the moment for a direction on the last few classes

**Comment by mbabker** [comment]
Given the creation of https://github.com/joomla-extensions/legacy-mvc (yay for more abandonware "core supported" extensions), this should be merged so developers might notice this deprecation now and not get bitten by the sudden removal in 4.0.

**Comment by wilsonge** [comment]
As @mbabker pointed out. Production has agreed to this but decided to keep the code available in a repo for projects that may require it. It's almost certain that it won't be touched much - but it exists as a migration resource to those who may need it.

**Pull request merged**
