### PR TITLE
[com_fields] Custom fields language update

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue #13327

### Summary of Changes
Added "Custom Field(s)" throughout as necessary to clarify language, as simply using "field(s)" was ambiguous.

### Testing Instructions
All Custom Fields messages and descriptions should reflect they are coming from the Custom Fields component.

The "Required" edit field description does not contain the word custom, I do not believe it is necessary in this particular instance, but it could be added easily.

### Documentation Changes Required
None

### Language has changed

### CODE REVIEW

**Comment by infograf768** [comment]
This is not enough. It does not change the Permissions label and tip as stated in https://github.com/joomla/joomla-cms/issues/13327

I suggest to change also in en-GB.ini
`JACTION_EDITVALUE="Edit Value"`
to
`JACTION_EDITVALUE="Edit Custom Fields Value"`
and 
`JACTION_EDITVALUE_COMPONENT_DESC="Allows users in the group to edit any value of the item they submitted in this extension."`
to
`JACTION_EDITVALUE_COMPONENT_DESC="Allows users in the group to edit any custom field value of the item they submitted in this extension."`
Which would give

screen shot 2016-12-23 at 08 22 29

and in en-GB.com_config.ini
`COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any value of an item in any extension."`
to
`COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any custom field value of an item in any extension."`
which would give

screen shot 2016-12-23 at 08 25 55

**Comment by Bakual** [comment]
Personally I think using "Fields" as the name for the component is fine. Using "Custom Fields" in every place is a bit to much in my opinion.
When we are in the Fields component, it should be already clear that we're going tow ork with custom fields here.

I only see a need to adjust the permissions text as this shows up in the component (eg article) options and in that context it isn't clear that it's only about the fields from com_fields. However as @laoneo said in the originally issue we should also take into account that this is a core permission. While it is currently only used by com_fields, it *may* be used in future in other places as well.

**Comment by infograf768** [comment]
> Personally I think using "Fields" as the name for the component is fine. Using "Custom Fields" in every place is a bit to much in my opinion.
When we are in the Fields component, it should be already clear that we're going tow ork with custom fields here.

Agree.

> I only see a need to adjust the permissions text as this shows up in the component (eg article) options and in that context it isn't clear that it's only about the fields from com_fields. However as @laoneo said in the originally issue we should also take into account that this is a core permission. While it is currently only used by com_fields, it may be used in future in other places as well.

Disagree for Global Config: 
What is `Edit Value` and what means `Allows users in the group to edit any value of an item in any extension.`?
What is an `item` here?
If it is necessary to add another type of permission "in the future", let's just add it at the time and make it clear what it is for.

**Comment by Bakual** [comment]
> If it is necessary to add another type of permission "in the future", let's just add it at the time and make it clear what it is for.

What I meant is, that it could also be used by 3rd parties. If we're just writing "Custom Fields" into that permission text, it may be to restrictive.

**Comment by infograf768** [comment]
I understood what you meant. 
But I insist that it still does not make sense for anyone what that permission is for... 
I honestly can't translate that text and make sense of it.

**Comment by Bakual** [comment]
Yeah sure. I still think that text needs to be improved.

**Comment by laoneo** [comment]
@cpfeifer I would also not use custom fields for everything. Fields should be enough.

**Comment by cpfeifer** [comment]
Thank you for the clarification. The labels for the permissions tooltips are the same in every component, so the issue in question is not specific to custom fields. It was labeled as a custom fields issue so I believed you were referring specifically to the CF description text. 

I could go either way on the description text, "fields" or "custom fields", I would lean toward leaving it as is because it's less text. I don't believe the changes proposed here will have much of an impact on UX.

I agree the labels could be clearer overall, and I'm happy to take a deeper look at it, but this is a system wide improvement which this PR does not address. Maybe it would be best to close this and start a new issue to deal with the issue in question?

**Comment by infograf768** [comment]
The issue was already created https://github.com/joomla/joomla-cms/issues/13327 specific to Permissions. Shall I reopen it?

**Comment by Bakual** [comment]
Yes, lets close this and reopen the issue.

**Pull request closed without merging**
