### PR TITLE
[Sql azure] Normalize joomla install sample learn sql file

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Normalizes all sql azure joomla **sample_learn.sql** install file.
- always use `SET IDENTITY_INSERT [#__xxxx] ON/OFF;`
- `INSERT` to `INSERT INTO`
- Quote all table names and db field names
- Always use `'` to quote string values.
- Code style
### Testing Instructions

Mainly code review. (to many changes need to check code in raw) 
https://github.com/andrepereiradasilva/joomla-cms/blob/patch-25/installation/sql/sqlazure/sample_learn.sql

If anyone could test an install of **sample learn** 3.6.x would be great. Don't have sql azure to test,
### Documentation Changes Required

None.

@waader @alikon please test.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2719b9a98491c4f6cb119dcc287e6d1a19821644<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11796">issues.joomla.org/joomla-cms/11796</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@waader please test this one also.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 2719b9a98491c4f6cb119dcc287e6d1a19821644<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11796">issues.joomla.org/joomla-cms/11796</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks folks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11796">issues.joomla.org/joomla-cms/11796</a>.</sub>

**Pull request merged**
