### PR TITLE
[4.0] awesomplete accessibility fix

### PR DESCRIPTION
**Pull request by brianteeman**
We use the library awesomeplete in a few places but the version we have is outdated and has some accessibility bugs.

This PR will update to the latest release 1.1.5

### testing
1. publish the search module
2. inspect the source of the module and there is NO aria-expanded attribute
3. apply pr and then npm i
4. inspect the source of the module and there is an aria-expanded=false attribute
5. When the popup appears with search results this changes to aria-expanded=true

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4746952795fb2e7fe67770a0e7a230da204aa144<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27690">issues.joomla.org/tracker/joomla-cms/27690</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 4746952795fb2e7fe67770a0e7a230da204aa144<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27690">issues.joomla.org/tracker/joomla-cms/27690</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27690">issues.joomla.org/tracker/joomla-cms/27690</a>.</sub>

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
