### PR TITLE
Correct class, icon and text for contact error warning in multilanguage status module

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #25415 .

### Summary of Changes

1. Change icon and class for the message related to contact errors in the multilanguage status module.
~~2. Remove text "Warning! " from the beginning of the language string for that message.~~

~~These 2 changes are made with separate commits for each change, so if it turns out that only one of them is accepted, then it can be cherry-picked.~~

### Testing Instructions

See issue #25415 .

### Expected result

Consistent display of all warnings, i.e. show contact related warning like all the others with warning class and icon ~~but no text "Warning! " at the beginning~~.

### Actual result

All warnings have warning class and icon and no text "Warning! " at the beginning. Only the text related to contact errors has class and icon for info but text "Warning! " at the beginning.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman I'd like to know your opinion if both changes, 1. icon and class, and 2. the removal of "Warning! " from the beginning of the text are good, or if you think only one of them is better. I think both together is most consistent with other warnings in the multilanguage status module's modal. I've made separate commits so each change can be cherry-picked.

**Comment by brianteeman** [comment]
In joomla 3 you will have to keep the word"warning" in the text.  In joomla 4 these messages should all have a headline saying "warning" (and if they dont yet then its just because its on my todo)

The other changes are fine and enough to resolve this issue

**Comment by richard67** [comment]
@brianteeman Hmm, the other texts dont's start with "Warning! ". What these warnings all have is a hidden (class="element-invisible") span with `JText::_('WARNING')`, and so I've changed that hidden span for the questionable warning from `JText::_('INFO')` to `JText::_('WARNING')`, Is it that what you mean?

**Comment by brianteeman** [comment]
and the others are wrong which is why I fixed them in j4 ;)

**Comment by richard67** [comment]
Ahh. Got it. Will undo the corresponding commit to remove the test part.

**Comment by brianteeman** [comment]
The hidden span is for screen reader users as they cant see the icon or colour

**Comment by richard67** [comment]
Yes, that's why I changed that, too. Thanks for advise. I really appreciate that. PR should be ready now.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 19ba859ed035c60c2569d12e55f0c5ff95c9d5c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25426">issues.joomla.org/tracker/joomla-cms/25426</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 19ba859ed035c60c2569d12e55f0c5ff95c9d5c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25426">issues.joomla.org/tracker/joomla-cms/25426</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25426">issues.joomla.org/tracker/joomla-cms/25426</a>.</sub>

**Comment by ghost** [comment]
Thanks Guys for your Work.

**Comment by HLeithner** [comment]
thx

**Comment by richard67** [comment]
Thanks

**Pull request merged**
