### PR TITLE
Consistency with the use "Install Languages"

### PR DESCRIPTION
**Pull request by MATsxm**
#### Steps to reproduce the issue

In the Admin go to: **Extensions -> Language(s)**
#### Actual result

See the <code>Install Language</code> button without the <code>S</code>

com_languages
even though we are using <code>Install Languages</code> in the com_installer
com_installer
#### Expected result

Apply the patch then the button <code>Install Languages</code> will appear with the **S**

> > I know it's a real detail and an easy fix ;)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b127d67bef0849dd421d605e2a847ad2a14470bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9104">issues.joomla.org/joomla-cms/9104</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b127d67bef0849dd421d605e2a847ad2a14470bb<br /><br />Tested by code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9104">issues.joomla.org/joomla-cms/9104</a>.</sub>

**Comment by infograf768** [comment]
rtc. thanks.
this can go into 3.5.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9104">issues.joomla.org/joomla-cms/9104</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks all!

**Pull request merged**
