### PR TITLE
Change joomla toolbar logo size

### PR DESCRIPTION
**Pull request by coolcat-creations**
### Summary of Changes
This is a mini-PR and changes the Logo Size iof the Joomla Logo in the toolbar from 30px to 20px square size, because it looks more elegant.

Before:
grafik

After:
grafik

### Testing Instructions
Apply the patch, Logo should be smaller in the Toolbar

### CODE REVIEW

**Comment by HRIT-Florian** [comment]
I have tested this item :white_check_mark: successfully on db6577e71b6dde6b246740395ca0e16015dc2044<br /><br />It looks better in any case in harmony with the other elements, but possibly a bit too small, but maybe I have to get familiar with it :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22072">issues.joomla.org/tracker/joomla-cms/22072</a>.</sub>

**Comment by gorgonz** [comment]
I have tested this item :white_check_mark: successfully on db6577e71b6dde6b246740395ca0e16015dc2044<br /><br />exactly as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22072">issues.joomla.org/tracker/joomla-cms/22072</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
