### PR TITLE
Provide Greek calendar locale

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
This PR provides the Greek calendar locale for the new calendar.

### Testing Instructions
Code review
Language review @dgt41 ?
Test @dgt41 ?

### Documentation Changes Required
None

### CODE REVIEW

**Comment by zero-24** [comment]
@infograf768 is this not something that is handled in the language packs?

**Comment by frankmayer** [comment]
@zero-24 I noticed that @Bakual did a commit 8b47a87328c18bf9330baa452101239662ac0ef2 for the Bulgarian language and thought I'd also provide one. Also, it's Javascript. I think, if this would be handled by the language packs, the translation for this would have to be dynamically created.

**Comment by dgt41** [comment]
@frankmayer I thought that the official Greek translators would have done this, that's why I didn't provide the file (I'm not part of that team)

**Review by dgrammatiko — APPROVED** [review]

**Comment by Bakual** [comment]
>  I thought that the official Greek translators would have done this,

It indeed has to be done by that team (https://community.joomla.org/translations/joomla-3-translations.html#el-gr). If you think the team is disfunctional you need to contact Mig (https://forum.joomla.org/memberlist.php?mode=viewprofile&u=224484) so it can be sorted out. 

The file then needs to be posted in the respective forum thread in the translator forum.

I'm closing this here.

**Comment by frankmayer** [comment]
@bakual I didn't see this PR get tagged by the bot as a "language change". How should they know?

**Comment by zero-24** [comment]
done https://github.com/joomla/jissues/pull/933

**Comment by infograf768** [comment]
@Bakual
As you know the issues we have with the Greek TT, I suggest you get this one in.

**Pull request merged**
