### PR TITLE
[4.0][JLayout images] Remove unnecessary isset(...)

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
- Code review. We don't need the additional isset(...) check because !empty(...) is sufficient.

### Expected result
- No changes with output of intro images in category blogs and featured blogs
- No changes with output of full images in article views

### Actual result
- Unnecessary code.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2bf691108332c0fe57352b20a89ada1659b74a0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24392">issues.joomla.org/tracker/joomla-cms/24392</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 2bf691108332c0fe57352b20a89ada1659b74a0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24392">issues.joomla.org/tracker/joomla-cms/24392</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
This has been merged into the 3.x branch. It will make it upto j4 from there. Going to close this as a result

**Pull request closed without merging**
