### PR TITLE
php 7.2 compatibility mcrypt checks

### PR DESCRIPTION
**Pull request by brianteeman**
PR for 18007

We were checking and reporting on the presence of mcrypt. We no longer need to do that as it is no longer a requirement and mcrypt itself is not present in php 7.2 so the checks would fail anyway then.

Didnt see the point in wrapping it in a conditional php version check as we dont need the info any more

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :red_circle: unsuccessfully on 00bae88657ff3d284e7a20d750189e568b4f4195<br /><br />`PHP Notice:  Undefined index: mcrypt in C:\xampp\htdocs\joomla-cms\administrator\components\com_admin\views\sysinfo\tmpl\default_phpsettings.php on line 165`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18169">issues.joomla.org/tracker/joomla-cms/18169</a>.</sub>

**Comment by brianteeman** [comment]
oops I forgot to commit a change - should be ok now

**Comment by Quy** [comment]
Remove language strings.

**Comment by brianteeman** [comment]
@quy unfortunately the policy is not to remove language strings

**Comment by Quy** [comment]
Sorry, I keep forgetting that.  Then add a deprecate comment?

**Comment by brianteeman** [comment]
@quy there really isn't much point as no one reads them

**Comment by Quy** [comment]
I see this in the language files:
`; This string is deprecated and will be removed with 4.0.`

**Comment by brianteeman** [comment]
and there are thousands of lines of strings which dont have it and they have been removed

**Comment by infograf768** [comment]
Although COM_ADMIN_MCRYPT_ENABLED should be kept, the specific installation lang strings do not need to remain as the installation folder is totally linked to a new joomla version and not part of Tts lang packs.

as for the 'thousands' of strings which have been deleted in 4.0, it is mostly because a lot of tips have been taken of there (including some that will need to come back in. will make a pr for these).

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 681031c5e4d4dc4356a1f52c191e4964bad4468f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18169">issues.joomla.org/tracker/joomla-cms/18169</a>.</sub>

**Review by mbabker — APPROVED** [review]

**Comment by brianteeman** [comment]
With php 7.2 being released next month this should be merged asap

**Comment by brianteeman** [comment]
Thanks

**Comment by zero-24** [comment]
Should'nt this be dropped too than: https://github.com/joomla/joomla-cms/blob/3.9-dev/administrator/components/com_joomlaupdate/models/default.php#L1113-L1118

?

**Comment by zero-24** [comment]
Or I'm missing something?

**Comment by mbabker** [comment]
Code doesn't exist in staging, only 3.9.

**Comment by brianteeman** [comment]
If no one beats me to it I will do a pr for that in 3.9  branch on Sunday

**Comment by dgrammatiko** [comment]
> including some that will need to come back in. will make a pr for these

@infograf768 please don't bring back tooltips, fix the labels instead

**Comment by brianteeman** [comment]
@zero-24 PR #18334 removes the code from 3.9 branch

**Comment by infograf768** [comment]
@dgt41 
> @infograf768 please don't bring back tooltips, fix the labels instead

Alas, some tips are much too long (and need to be) to be used as labels (the alias tip is only one example).
One idea I have is to change the way these tips are displayed via a **?** to click on which would open a modal. Would that be possible and would it be a11y ?

**Comment by dgrammatiko** [comment]
The best a11y is to not use tool tips at all!

**Comment by infograf768** [comment]
OK, then think as a newbie: how do you do for these? Just examples...
screen shot 2017-10-14 at 10 41 49
screen shot 2017-10-14 at 10 41 29
screen shot 2017-10-14 at 10 44 37

**Comment by dgrammatiko** [comment]
@infograf768 for newbies we will have the tour guide. You need to understand we're not in 2006, we're effectively at the end of mobile era and slowly moving into PWA era. Tooltips are not a recommended thing either for mobile or PWA:
screen shot 2017-10-14 at 12 36 57

**Comment by ghost** [comment]
@dgt41 what is PWA?

**Comment by infograf768** [comment]
and what about the « tour guide » ? will it be available in all languages? I honestly doubt about this: see the state of the help to understand my concern, which also should be yours.

**Comment by brianteeman** [comment]
This is completely off topic

**Pull request merged**
