### PR TITLE
[4.0] Fix tags creation

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Currently the creation of dynamic tags is broken in the 4.0 branch. This fixes it (has been the case since we merged the update of choices 7)

### Testing Instructions
Type a tag with a new value into the tags box and hit enter

### Expected result
Tag is created

### Actual result
It isn't

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ghost** [comment]
Are #23748 #23589 related Issues?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ea050f7a60c438e54a8c8ddb3ac5228c8f451bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24743">issues.joomla.org/tracker/joomla-cms/24743</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 9ea050f7a60c438e54a8c8ddb3ac5228c8f451bf<br /><br />>>This fixes it (has been the case since we merged the update of choices 7)
Not true. It never worked correctly since Joomla 4 used choices v 3.0.4.
And thanks to the great work of @bembelimen and @dgrammatiko on this script.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24743">issues.joomla.org/tracker/joomla-cms/24743</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
> Not true. It never worked correctly since Joomla 4 used choices v 3.0.4.

it did because i tested downgrading the version and it worked ;)

**Comment by wilsonge** [comment]
@franz-wohlkoenig it definitely doesn't fix the first issue and i can't reproduce the second (although as hannes suggested on the second it was related to setup doesn't mean it's fixed)

**Comment by ghost** [comment]
Status set on Pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24743">issues.joomla.org/tracker/joomla-cms/24743</a>.</sub>

**Comment by wilsonge** [comment]
@franz-wohlkoenig just a codestyle fix for hound. No need to retest. As soon as tests pass i'm going to merge

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
