### PR TITLE
CodeMirror 5.35.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
### Summary of Changes
http://codemirror.net/doc/releases.html

### Testing Instructions
Use CodeMirror

### Expected result
It should work as usual

### Actual result
It works as usual

### Documentation Changes Required
Nope

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on fc50b2f0191a48aed7307dc58c9719d4ee85a7c5<br /><br />Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19809">issues.joomla.org/tracker/joomla-cms/19809</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Sorry but appveyor is wrong. There's no way this fails.

**Comment by zero-24** [comment]
Confirmed. @rdeutz can we re run appveyor?

**Comment by brianteeman** [comment]
@zero-24 maybe just merge #19805

**Comment by zero-24** [comment]
It is still failing even with that PR you linked. ;) But it looks like a general Problem as all PR's are failing.

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on fc50b2f0191a48aed7307dc58c9719d4ee85a7c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19809">issues.joomla.org/tracker/joomla-cms/19809</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19809">issues.joomla.org/tracker/joomla-cms/19809</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Be sure to have a look at #19833 too.

**Pull request merged**
