### PR TITLE
[5.2][CLI] extension:remove -n option "Invalid Response" fix

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #44445 .

### Summary of Changes
check if "no-interaction"

### Testing Instructions
`php joomla.php extension:remove ID -n`

### Actual result BEFORE applying this Pull Request
` [WARNING] Invalid response`
and the extension is not removed

### Expected result AFTER applying this Pull Request
the extension is  removed

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 002eb9c0a9d4b8d2c8da377386aea8895d464be6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44546">issues.joomla.org/tracker/joomla-cms/44546</a>.</sub>

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on 002eb9c0a9d4b8d2c8da377386aea8895d464be6<br /><br />I was able to reproduce this issue.

The PR fixes it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44546">issues.joomla.org/tracker/joomla-cms/44546</a>.</sub>

**Comment by pe7er** [comment]
RTC

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44546">issues.joomla.org/tracker/joomla-cms/44546</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution!

**Pull request merged**
