### PR TITLE
[4.1] PLG_TINY_FIELD_CUSTOM_CSS_DESC

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the path in the description to the new location

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 40e6c81bd60d90bb67681d005cebc8a76da4141a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36739">issues.joomla.org/tracker/joomla-cms/36739</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 40e6c81bd60d90bb67681d005cebc8a76da4141a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36739">issues.joomla.org/tracker/joomla-cms/36739</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36739">issues.joomla.org/tracker/joomla-cms/36739</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
