### PR TITLE
com_templates removal of PHP warnings

### PR DESCRIPTION
**Pull request by jsubri**
Pull Request for Issue #31747

### Summary of Changes
Copy of #27851 for staging , credit goes to @Quy 

### Testing Instructions
as per Issue #31747, apply patch 
Search in page source for id="resizeModal" , should not be there

### Actual result BEFORE applying this Pull Request
PHP Warning: Trying to access array offset on value of type null
logs have PHP Warning: Trying to access array offset on value of type null

### Expected result AFTER applying this Pull Request
no more PHP Warnings in \administrator\components\com_templates\tmpl\template\default_modal_resize_body.php

### Documentation Changes Required
n/a

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on fdad6eb1c1e95beff024613193da432bf280301a<br /><br />Tested successfully in 3.9.24-rc of 21 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31749">issues.joomla.org/tracker/joomla-cms/31749</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fdad6eb1c1e95beff024613193da432bf280301a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31749">issues.joomla.org/tracker/joomla-cms/31749</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31749">issues.joomla.org/tracker/joomla-cms/31749</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Pull request merged**
