### PR TITLE
[4.0][WIP][GSOC] dev guided tour

### PR DESCRIPTION
**Pull request by dgrammatiko**
### Summary of Changes
Introductory code for guided tour. 

### Expected result
A bit more refined than: 
screen shot 2017-06-07 at 20 15 19

### CODE REVIEW

**Comment by brianteeman** [comment]
if it is only for gsoc shouldnt it be in its own branch?

**Comment by zero-24** [comment]
@dgt41 I agree with Brian what about sending this as PR against the gsoc repo ?

**Comment by Bakual** [comment]
Closing as it is not an appropriate place for such a PR. We have specific repos for things like that.

**Comment by dgt41** [comment]
I would have done that in the first place but there's no repo for that (?) 
screen shot 2017-06-08 at 09 34 37


Anyways closing here is fine, the purpose was to share code that already existed, this doesn't need to be open!

**Comment by zero-24** [comment]
Isn't the helpscreen repo that one for the guided tour? so gsoc17_helpscreens_on_jdocs would be your repo ;)

**Comment by brianteeman** [comment]
Just create a repo. Problem solved :)

**Comment by shivamdiehard** [comment]
Hi,
I am associated with helpscreen repo. It would be great @dgt41 if you can a PR over there.
https://github.com/joomla-projects/gsoc17_helpscreens_on_jdocs

**Pull request closed without merging**
