### PR TITLE
[4.0] Use brand colour for switcher

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #17420

### Summary of Changes

The switcher now uses for colours based on `$brand-*`

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5af7415d1f58cbcb8f568d751b00e36697527572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17422">issues.joomla.org/tracker/joomla-cms/17422</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5af7415d1f58cbcb8f568d751b00e36697527572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17422">issues.joomla.org/tracker/joomla-cms/17422</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by C-Lodder** [comment]
@wilsonge conflicts fixed

**Pull request merged**
