### PR TITLE
[4.0][com_finder] dirty temporary fix for class not found

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #25031 .

### Summary of Changes
a dirty temporary fix

### Testing Instructions
 #25031

### Expected result
no error

### Actual result

error

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0d41d6171c00cd46f6f1773b226afb4f48c72448<br /><br />Fixed. Now there is a different error with the search results.

`Warning: Creating default object from empty value in \components\com_finder\View\Search\HtmlView.php on line 140`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25040">issues.joomla.org/tracker/joomla-cms/25040</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 0d41d6171c00cd46f6f1773b226afb4f48c72448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25040">issues.joomla.org/tracker/joomla-cms/25040</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
