### PR TITLE
[4.0] Admin module feed display image

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue #33523 .

### Summary of Changes
add class `w-100`

### Testing Instructions
Add a new Admin Module of type Feed Display with feed with images in its feed - use url https://rss.art19.com/apology-line for example right now.

### Actual result BEFORE applying this Pull Request
feed-before

### Expected result AFTER applying this Pull Request
feed-after

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fb7ca3fa79d1e1f51ac3aed875ec305c2ef3de0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33543">issues.joomla.org/tracker/joomla-cms/33543</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fb7ca3fa79d1e1f51ac3aed875ec305c2ef3de0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33543">issues.joomla.org/tracker/joomla-cms/33543</a>.</sub>

**Comment by drmenzelit** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33543">issues.joomla.org/tracker/joomla-cms/33543</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
