### PR TITLE
System - Language Filter - cookie value

### PR DESCRIPTION
**Pull request by brianteeman**
This sets the default value in the xml to match the documentation

### CODE REVIEW

**Comment by zero-24** [comment]
Moving to RTC based on review and the comments here: http://issues.joomla.org/tracker/joomla-cms/5639

As this PR just set the default values that is used by the code. Good find @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5640">issues.joomla.org/joomla-cms/5640</a>.</sub>

**Comment by infograf768** [comment]
I suggest we should do the opposite and rather change the language string
PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_DESC to inform that session is default as this was indeed forgotten when we added the Session value.

**Comment by brianteeman** [comment]
So now I am confused. The string says and the xml say one thing is the
default but you are saying its the opposite.

On 8 January 2015 at 09:25, infograf768 <notifications@github.com> wrote:

> I suggest we should do the opposite and rather change the language string
> PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_DESC to inform that session is
> default as this was indeed forgotten when we added the Session value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5640#issuecomment-69154838>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
The default value was changed when we committed
https://github.com/joomla/joomla-cms/commit/12aaec75b61a3362ab5ab47889a151043d0b7c5d

I.e. the default was from there on "Session" and not "Year"

But the string was not changed correctly.
It should be;
PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_DESC="Language cookies can be set to expire at the end of the session or after a year. Default is session."

**Comment by brianteeman** [comment]
OK I will update this PR to change the language string NOT the xml - thanks

On 8 January 2015 at 10:09, infograf768 <notifications@github.com> wrote:

> The default value was changed when we committed
> 12aaec7
> <https://github.com/joomla/joomla-cms/commit/12aaec75b61a3362ab5ab47889a151043d0b7c5d>
>
> I.e. the default was from there on "Session" and not "Year"
>
> But the string was not changed correctly.
> It should be;
> PLG_SYSTEM_LANGUAGEFILTER_FIELD_COOKIE_DESC="Language cookies can be set
> to expire at the end of the session or after a year. Default is session."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5640#issuecomment-69159547>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I have updated the PR to change the language string as requested and not the xml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5640">issues.joomla.org/joomla-cms/5640</a>.</sub>

**Comment by infograf768** [comment]
Thanks. Merged.

**Pull request closed without merging**
