### PR TITLE
[com_fields] Remove not used content prepare option

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
As content parsing is removed this options becomse obsolete. See https://github.com/joomla-projects/custom-fields/pull/135 for more information.

### Testing Instructions
All should work as expected with the patch applied.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f0efb672a0224eaa00d4e2a218fa0b33f73fda09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12699">issues.joomla.org/tracker/joomla-cms/12699</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on f0efb672a0224eaa00d4e2a218fa0b33f73fda09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12699">issues.joomla.org/tracker/joomla-cms/12699</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12699">issues.joomla.org/tracker/joomla-cms/12699</a>.</sub>

**Comment by rdeutz** [comment]
we might add this back again within the process

**Comment by roland-d** [comment]
@laoneo Can you have a look at the merge conflicts? Thanks.

**Comment by laoneo** [comment]
Done, thanks for the hint.

**Pull request merged**
