### PR TITLE
[com_redirects] Fix text to not flushed left

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix padding

### Testing Instructions
Go to Components > Redirects
Click `Bulk Import` button.
Text is flushed left.
bulk

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2984cd56fba632d033c9dbbcd54ef465459649b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15044">issues.joomla.org/tracker/joomla-cms/15044</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 2984cd56fba632d033c9dbbcd54ef465459649b0<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15044">issues.joomla.org/tracker/joomla-cms/15044</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
