### PR TITLE
[4.0] com_menus: correct incomplete group by clause

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.

### Summary of Changes

If you enable associations in language filter 4.0 bracnh is producing an sql error because of the group by clause.

Related to the more strict `ONLY_FULL_GROUP_BY` sql_mode added in 4.0 branch (https://github.com/joomla/joomla-cms/pull/12494)

### Testing Instructions

Mainly code review, but you can also

- Use 4.0 branch
- Enable language filter plugin and associations
- Go to menus -> all menus you get an sql error
- Apply patch, no error

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by ggppdk** [comment]
I have not tested this **or the other similar PRs**,
i only want to say, that fixing this is 2 parts

- 1st part not SQL error occurs
- 2nd part is making sure that the result of the query gives the desired data and not something else !

**Comment by ggppdk** [comment]
Again without testing, and beside getting correct results from the modified group-by

The group-by is
- becoming very big

----

There must be better solutions than making the groub-by very big

The fact that we need some extra data **and we join with tables** to get them,
- this then forces us to add **ALL non-aggregated columns** into the Group-by because of ONLY_FULL_GROUP_BY

this really seems wasteful, the solution should be (**i guess**) to use a JOIN with a single subquery that will contain the group-by and which will group-by on a lot less columns ?

**Comment by andrepereiradasilva** [comment]
@ggppdk i understand your point of view, but the issue here is there is a group by and using `ONLY_FULL_GROUP_BY` sql mode (4.0) it's not working properly.

So this PR solves that issue.

Any further otimizations on this queries is out of the scope of this PR

**Comment by ggppdk** [comment]
yes, i see, 
the views need to work again and possibly revise the queries later,

then i only argue to make a list of the queries that had their group-by enlarged because of the new mode

**Comment by andrepereiradasilva** [comment]
well ... are being marked by this PRs 😉

**Comment by wilsonge** [comment]
Can you rebase this one please?

**Comment by andrepereiradasilva** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
