### PR TITLE
Remove from #__extensions useless columns: system_data and custom_data

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #14409

### Summary of Changes
Remove 2 columns from `#__extensions` table and all files.

1. Fix template copy functionality.
2. Fix postgresql installation, some plugins in extension table has missing column value.
3. Set correct PK value for template style: protostar in mysql
4. Set correct auto increment value for postgresql - copy template error

### Testing Instructions
1. Try to copy template style for protostar - before patch it does not work.

2. 
    a. Install dev-4.0 joomla branch and then apply patch and go to database fix button. Mentioned columns should be deleted from databases.
    b. Test installation of patched Joomla on mysql and/or postgresql.

3. Try to copy template style again - now it should work

### Expected result
Template copy works.

### Actual result
Error.

### Documentation Changes Required
Maybe. Two columns has been deleted from `#__extensions` table.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on eb86c057aede6eb15d514c0222f99c418ae3e31a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14750">issues.joomla.org/tracker/joomla-cms/14750</a>.</sub>

**Comment by Bakual** [comment]
As I wrote in the issue, **custom_data** and **system_data** aren't useless columns. While they are currently not used by core, the **system_data** one was used store compatibility informations in J2.5 and probably will be used again in J3 again.
The **custom_data** one may be used by 3rd parties (eg a module or plugin wants to store something and an own table would be to much overhead).

So imho this PR is a wrong approach to fix a valid issue. We should instead seriously rethink the "NOT NULL" constraint we put on every field. We could save us some trouble by removing that on some of them (and it would fix this issue as well).

**Comment by csthomas** [comment]
If the columns is really needed then we can revert it, but ...

all (or almost all) TEXT/BLOB columns should be `NULL DEFAULT NULL`.

**Comment by mbabker** [comment]
+1 for revert.

We should make it clear what the field purposes are but just dropping them out of the blue seems a little drastic.

**Comment by Bakual** [comment]
We would have to ask Samuel Moffatt for the real reason they were initially added. It was part of the #__extension table when it was created :)

I am just judging from the name of those fields, and as said I have used one of them in core itself in the past. Imho they are of situational use. We could add some comment to it of course 😄

**Pull request merged**
