### PR TITLE
[4][webservice] user patch

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #41681 .

### Summary of Changes

fix PATCH user alters password

### Testing Instructions
#41681

### Actual result BEFORE applying this Pull Request
after PATCH unable to login for that user

### Expected result AFTER applying this Pull Request
able to login

### CODE REVIEW

**Comment by hefferbub** [comment]
I have tested this item :white_check_mark: successfully on bf014922becc8b02cd625745a38654f7a46d93c7<br /><br />Tested by replacing the one changed source file on a stock 4.3.4 installation and the fix worked as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41688">issues.joomla.org/tracker/joomla-cms/41688</a>.</sub>

**Comment by laoneo** [comment]
Can you rebase this to 4.4 and add a system test?

**Comment by alikon** [comment]
rebased to 4.4
for the system test... 🤕  in the week-end or so

**Comment by laoneo** [comment]
I don't like the mix of api tests with front end tests. Can this not be tested somehow differently if the password works?

**Comment by alikon** [comment]
probably yes, but How ?

**Comment by MacJoom** [comment]
we would need to add an rest api to test the password

**Review by wilsonge — APPROVED** [review]

**Pull request merged**
