### PR TITLE
[4.3] Guided Tours use global language keys

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

use the global strings for "Status" and "ID" in heading of tours/steps lists (they are already used in edit form and for sorting)
@obuisard Should the language keys deprecated or removed?

Note: _Title_ and _Description_ is also inconsistent

### Testing Instructions

check the used language key

#### Tour
image
image

#### Step
image
image

#### Tour
image
image

#### Step
image
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by obuisard** [comment]
I believe the language keys should be deprecated.

**Comment by brianteeman** [comment]
Surely there is no need to deprecate these strings and they can just be deleted as the code has not been released

**Comment by alikon** [comment]
yes please let's do things simply., delete without deprecations there's no need to over-engineer in this case, imho

**Comment by heelc29** [comment]
@brianteeman @alikon deleted

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e3a75e2f90988b86c80ec338d3d4610aeab94ea4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40319">issues.joomla.org/tracker/joomla-cms/40319</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40319">issues.joomla.org/tracker/joomla-cms/40319</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29. Better deal with this now than later.

**Pull request merged**
