### PR TITLE
Add Autofocus to Frontend Login Component Form

### PR DESCRIPTION
**Pull request by justinherrin**
Just like the /administrator login screen, this will make the Username field be autofocus and ready to type in to.

This is the better/simpler/easier way to accomplish this idea compared to my previous PR #7601.
### To Test

Create a frontend menu item that points to the Users Login view. You should notice that the username field is autofocused on and ready for you to type into.

### CODE REVIEW

**Comment by dgt41** [comment]
:+1: 
Could you do the same for the admin part as well?

**Comment by justinherrin** [comment]
The /administrator login page uses a jQuery snippet to do the autofocus (that's where I originally got the code idea for #7601).

**Comment by brianteeman** [comment]
See #7607 for the admin login<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7604">issues.joomla.org/joomla-cms/7604</a>.</sub>

**Comment by jwaisner** [comment]
@test 

PR works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7604">issues.joomla.org/joomla-cms/7604</a>.</sub>

**Comment by zero-24** [comment]
Works great. Thanks --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7604">issues.joomla.org/joomla-cms/7604</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @justinherrin! Merged.

**Pull request merged**
