### PR TITLE
[com_install] - fix for all languages filter

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #15290 .

### Summary of Changes
set a default when "all languages" is selected

### Testing Instructions
Extensions: Install Languages and set the filter to display ALL

### Expected result
all langauges

### Actual result
no result

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3c5f39e4dd8e44e5369f1811c32cc0f6e89adc14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15293">issues.joomla.org/tracker/joomla-cms/15293</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3c5f39e4dd8e44e5369f1811c32cc0f6e89adc14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15293">issues.joomla.org/tracker/joomla-cms/15293</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@rdeutz 
This can go in 3.7.0

**Pull request merged**
