### PR TITLE
[4.0] Atum table head border bottom again

### PR DESCRIPTION
**Pull request by brianteeman**
Third redo of #21982

Removed again by #23903

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d831903eba71f5f57309562b5f7e2e6068ff7a90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25616">issues.joomla.org/tracker/joomla-cms/25616</a>.</sub>

**Comment by wilsonge** [comment]
Can we make sure the calendar still renders ok as well, given that's what removed this code

**Comment by infograf768** [comment]
It does not render exactly the same:

Before:
Screen Shot 2019-07-24 at 15 21 43

After
Screen Shot 2019-07-24 at 15 21 53

The grey line is thicker below 2019 and also below June. Therefore it is slightly taller.

**Comment by brianteeman** [comment]
It would be better to fix that with specific css in /media/system/css/fields/calendar.css

I can do that here or in its own PR ??

**Comment by infograf768** [comment]
and in calendar-rtl.css

**Comment by brianteeman** [comment]
updated both the calendar files

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c526b04bdccd9a75039d4d8a44112702daab5392<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25616">issues.joomla.org/tracker/joomla-cms/25616</a>.</sub>

**Comment by Hackwar** [comment]
Can you update the PR to the latest 4.0-dev? Drone refuses to run due to some conflict.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thnks

**Pull request merged**
