### PR TITLE
s/guarentee/guarantee

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/guarentee/guarantee

### CODE REVIEW

**Review by rjharishabh — APPROVED** [review]

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 18125f7161fe213387e22bd10d4a8e1a80138dea<br /><br />Code review: spelling correction in doc block?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32906">issues.joomla.org/tracker/joomla-cms/32906</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 18125f7161fe213387e22bd10d4a8e1a80138dea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32906">issues.joomla.org/tracker/joomla-cms/32906</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32906">issues.joomla.org/tracker/joomla-cms/32906</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks @PhilETaylor

**Pull request merged**
