### PR TITLE
Schema link

### PR DESCRIPTION
**Pull request by brianteeman**
An earlier PR updated all 

> itemtype="http://schema.org/...

to 

> itemtype="https://schema.org/...

Looks like this one was missed and this small PR fixes that

### CODE REVIEW

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on d104d15802ce5f365f5ac30a7d041197a4aa5754<br /><br />Created a contact before the patch, checked the code, says: http://
Applied the patch, checked the code, says: https://
Successfully tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10033">issues.joomla.org/joomla-cms/10033</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d104d15802ce5f365f5ac30a7d041197a4aa5754<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10033">issues.joomla.org/joomla-cms/10033</a>.</sub>

**Comment by richard67** [comment]
Searched all staging and can confirm this was the only ocurrence of "http://schema.org/".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10033">issues.joomla.org/joomla-cms/10033</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks for the quick tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10033">issues.joomla.org/joomla-cms/10033</a>.</sub>

**Pull request merged**
