### PR TITLE
Create pt-br.js

### PR DESCRIPTION
**Pull request by helvecio**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
Shouldnt this be part of the language pack?

**Comment by helvecio** [comment]
Just realized I didn't have to do this here.

**Comment by zero-24** [comment]
Closing than :smile:

**Comment by infograf768** [comment]
FYI, the TT coordination is gathering all these files and @Bakual will merge them.
Same we did for the TinyMCE js lang files.

**Pull request closed without merging**
