### PR TITLE
[4.0][Aurora] Fix IE11 menu toggle on smaller screens

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
An issue pointed out by @Bakual. In IE11 on smaller screens the menu toggle breaks outside of the header. This PR fixes that.

### Testing Instructions
Apply patch and open the frontend in IE11. Reduce the browser size.

### Before
ie11-1

### After
ie11-2

### CODE REVIEW

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 011bd9e9a5c18f37500961977d7a941aa1994b97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16827">issues.joomla.org/tracker/joomla-cms/16827</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 011bd9e9a5c18f37500961977d7a941aa1994b97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16827">issues.joomla.org/tracker/joomla-cms/16827</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Comment by C-Lodder** [comment]
@ciar4n could you add `cursor: default;` here: https://github.com/ciar4n/joomla-cms/blob/011bd9e9a5c18f37500961977d7a941aa1994b97/templates/aurora/scss/blocks/_header.scss#L98

Once done, this will also fix https://github.com/joomla/joomla-cms/issues/16831

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - could we remove RTC until my comment above has been looked at?

**Comment by ciar4n** [comment]
`cursor: default;` added

**Review by C-Lodder — APPROVED** [review]

**Comment by C-Lodder** [comment]
thanks Ciaran

**Pull request merged**
