### PR TITLE
[/cms/component/helper] Exclude components in discover state from list

### PR DESCRIPTION
**Pull request by vinespie**
### Summary of Changes

Exclude components in discover state from list.

Method "getComponents" in class JComponentHelper return all components, even those who are in the state to discover.  Must add state in queries.
### Test instructions
1. In joomla components dir, create a directory named "com_test" for example,
2. In this dir, create one file named "router.php",
3. Edit this file and paste this code :
   `<?php 
   defined('_JEXEC') or die;
   die('Router call');
   ?>`
4. In this dir, create one file named "test.xml",
5. Edit this file and paste this :
   `<?xml version="1.0" encoding="utf-8"?>
   <extension type="component" version="3.1" method="upgrade">
   <name>com_test</name>
   <files folder="site">
       <filename>router.php</filename>
   </files>
   </extension>
   ` 
6. In backend, go to "Extensions => Manage => Discover"
7. Click "Discover" button, you must see "com_test" in list,
8. Go to fronted, you must see message "Router call",
9. Apply patch,
10. Go to fronted, no message, router not loaded
### Related pull request

**#8986 Parse preprocess rules from component routers :** router of all components are loaded, even those that are not installed.

### CODE REVIEW

**Comment by mbabker** [comment]
The pull request you've linked (and commented on) is completely unrelated to this proposed change.  Please describe why you think this change is necessary.

**Comment by andrepereiradasilva** [comment]
yes, and add test instructions too (the test instructions header is there when you create a pull request for a reason ...)

**Comment by vinespie** [comment]
@mbabker @andrepereiradasilva descriptionn update with test instructions

**Comment by brianteeman** [comment]
Can you ever have an extension in the database that does not have a status of 0
From what I can guess you are trying to exclude  extensions that are not installed - so therefore they are not in the database at all and they wont get returned by the existing query either 

(I could be completely missing the point and you description has been lost in translation)

**Comment by mbabker** [comment]
When you discover extensions, all found extensions are loaded into the database with `state = -1`.  They remain in that state until they are fully installed or the records purged.

**Comment by vinespie** [comment]
Yes @mbabker , extension with `state = -1` (discover) are considered as installed.

**Comment by brianteeman** [comment]
As I said the description and test instructions were incomplete and misleading. There is NO mention of doing a discover at all. Only to create the files

**Comment by vinespie** [comment]
@brianteeman description update

**Comment by mahagr** [comment]
Alright, it looks like this change only affects on discovered components. It really should also prevent disabled components (`enabled != 1`) from messing up the site.

**Comment by vinespie** [comment]
Yes @mahagr , adding request condition for prevent disabled extensions.

**Comment by mbabker** [comment]
I'd only add it to the `load` method.  Adding the enabled condition on the `isInstalled` method makes that method report invalid results (it's possible to have an extension installed and disabled).

**Review by mbabker — APPROVED** [review]

**Comment by vinespie** [comment]
ok @mbabker

**Comment by mahagr** [comment]
I agree that it should be only on `load()` method.

BTW, this pull request will change how component helper works and may have some visible side effects on peoples sites. This is because of both `getComponent()` and `getComponents()` calls will not anymore return component that exists in the database, but isn't either installed or enabled.

After running some tests with J!3.6.3, it looks like disabling extension makes it to stop to work from frontend and hidden in backend, though in backed you can still access the extension by typing the option manually (a bug?). On the other hand discovered component seems to be fully working as long as it has been enabled (another bug?). 

I need to test the same with the patch applied; I'll find some time for that.

**Comment by mahagr** [comment]
I just tested all the combinations with the patch (disabled, discovered | enabled, discovered, disabled, installed | enabled, installed) and it looks like that it doesn't change much in the admin -- except that discovered/enabled component is shown in the admin menu, but you cannot access it. Its an improvement over discovered being fully working in admin, but it would be nice to have another patch hiding the admin menu items in that case (I've seen sites with discovered but enabled components before -- not sure how you end up getting them, maybe failed install?)

**Review by mahagr — APPROVED** [review]
Fix looks good to me.

**Comment by christianboulbi** [comment]
I have tested this item :white_check_mark: successfully on 4d3775f447ea1b9545f4feee65904aeb369179c8<br /><br />test von Christianboulbi<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12469">issues.joomla.org/tracker/joomla-cms/12469</a>.</sub>

**Comment by perrez** [comment]
I have tested this item :white_check_mark: successfully on 4d3775f447ea1b9545f4feee65904aeb369179c8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12469">issues.joomla.org/tracker/joomla-cms/12469</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by mbabker** [comment]
Merge conflict needs to be addressed.

**Comment by ghost** [comment]
@vinespie can you please resolve conflicting Files?

**Comment by mbabker** [comment]
Replaced by https://github.com/joomla/joomla-cms/pull/21010 with merge conflicts resolved.

**Pull request closed without merging**
