### PR TITLE
Set min number upload_maxsize to 0

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Set min number upload_maxsize to 0

### Testing Instructions

see that there is navigation for the numbers field.
try to enter -1

### Expected result

Navigation with minimum 0
-1 is not allowed

### Actual result

just a text field
-1 is allowed

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ae03ca8a9d383de210ba01a2f0d6bad86f6eeec5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16742">issues.joomla.org/tracker/joomla-cms/16742</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ae03ca8a9d383de210ba01a2f0d6bad86f6eeec5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16742">issues.joomla.org/tracker/joomla-cms/16742</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
@rdeutz do you want to include this in 3.7.3 or 3.7.4?

**Comment by richard67** [comment]
If someone asks me for my opinion, it should go into 3.7.3 because it fixes a bug, and it contains no language change so no need to wait.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16742">issues.joomla.org/tracker/joomla-cms/16742</a>.</sub>

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
