### PR TITLE
tab to spaces

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for https://github.com/joomla/joomla-cms/pull/10947/files#r68808844
#### Summary of Changes

Simple CS for  composer.json
#### Testing Instructions

code review

### CODE REVIEW

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on efa50cbc88c0ba714be976d897df3b90b68465a6<br /><br />On Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10952">issues.joomla.org/joomla-cms/10952</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on efa50cbc88c0ba714be976d897df3b90b68465a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10952">issues.joomla.org/joomla-cms/10952</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10952">issues.joomla.org/joomla-cms/10952</a>.</sub>

**Comment by wojsmol** [comment]
Thanks everyone for testing and merging.

**Comment by piotr-cz** [comment]
Thanks for submitting PR

**Pull request merged**
