### PR TITLE
[com_content] Complete search tooltip

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to improves the search tooltip and element label (accessibility) in com_content.
Also add the ability to search for author in `featured` view to have the same behaviour as the `articles` view.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Go to Content -> Articles, check the tooltip in the search field.
3. Go to Content -> Featured, check the tooltip in the search field.
4. Go to frontend edit, click "+Article" in TinyMce and check the tooltip in the search field of the popup.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de2f6693b4ce619020f640ded1ef721e4c648abc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :red_circle: unsuccessfully on de2f6693b4ce619020f640ded1ef721e4c648abc<br /><br />The functions work as expected, however on showing the tooltip in the front end the top of it is clipped as shown below.

desktop tooltip clipping

View on mobile

mobile tooltip clipping<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by brianteeman** [comment]
Good spot. I didnt check it properly but I see that too

On 30 April 2016 at 22:28, Twincarb <notifications@github.com> wrote:

> I have tested this item [image: :red_circle:] unsuccessfully on de2f669
> <https://github.com/joomla/joomla-cms/commit/de2f6693b4ce619020f640ded1ef721e4c648abc>
>
> The functions work as expected, however on showing the tooltip in the
> front end the top of it is clipped as shown below.
>
> [image: desktop tooltip clipping]
> <https://camo.githubusercontent.com/845f2bdad633f9581582521651c6e3d08b059f00/687474703a2f2f7333322e706f7374696d672e6f72672f63686c3633766664682f6a6f6f6d6c61312e6a7067>
>
> View on mobile
>
> [image: mobile tooltip clipping]
> <https://camo.githubusercontent.com/b7814cf0890c940d62058fecd17cac7d1c2596aa/687474703a2f2f7333322e706f7374696d672e6f72672f6d36766f78793571742f6a6f6f6d6c61322e6a7067>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10147
> <https://issues.joomla.org/tracker/joomla-cms/10147>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10147#issuecomment-215996504>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
reggarding the tooltips in modals with iframes, i think @JoomliC is working on PR to solve them.
So i ask you to please ignore that for now.

**Comment by andrepereiradasilva** [comment]
actually i think he solved it here https://github.com/joomla/joomla-cms/pull/10076 (needs one more test)

**Comment by andrepereiradasilva** [comment]
i just tested this PR + @JoomliC modals PR (https://github.com/joomla/joomla-cms/pull/10076) and all seems good.
In other words the tootlip problem is not related to this PR.

So @Twincarb please test again with the two patches applied.

**Comment by brianteeman** [comment]
I will retest in the morning

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on de2f6693b4ce619020f640ded1ef721e4c648abc<br /><br />Tested alongside PR(10076)
Which solves the desktop issue, there is still a tooltip issue on mobile devices, tested both with chrome and mobile. The mobile issue is unrelated to this PR I will add a comment to PR(10076)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by JoomliC** [comment]
> The mobile issue is unrelated to this PR

@Twincarb  exactly about TinyMCE modals, not related to this PR (and i agree that TinyMCE modals on mobile are really bad and a shame to use as you have to touch tiny modal header and move to be able to navigate and view the close button...) ;-)
About tooltip, as placement is set to button, and the content of the modal articles and modules in TinyMCE is loaded inside an iframe (modal.php view) and i don't see how it's possible to have the tooltip issue there (but as TinyMCE is really bad on mobile... So waiting for your answer here: https://github.com/joomla/joomla-cms/pull/10076#issuecomment-216005359 :+1: )

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on de2f6693b4ce619020f640ded1ef721e4c648abc<br /><br />I confirm a successfull test just done on my iOS mobile :+1: 
And no change here concerning tooltip placement nor the none-responsiveness or TinyMCE modals ;-)

Good for RTC, et nice to be able to search by author!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by Twincarb** [comment]
@JoomliC Just found out I Can move a TinyMCE modal! Thank you for the heads up<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10147">issues.joomla.org/joomla-cms/10147</a>.</sub>

**Comment by JoomliC** [comment]
> @JoomliC Just found out I Can move a TinyMCE modal! Thank you for the heads up

You're welcome! ;-)
But really not an easy way to manage it this way on mobile...

**Pull request merged**
