### PR TITLE
[4.0] Decode HTML special chars

### PR DESCRIPTION
**Pull request by amitranjan2**
Pull Request for Issue # .

### Summary of Changes
Decode HTML special chars for diff view.

### Testing Instructions

1. Create two versions of articles and compare the difference.
2. Due to the overlay issue, you need to remove the backdrop by inspecting.
 

### Expected result

image

### Actual result
image

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by C-Lodder** [comment]
I don't think using Javascript to decode the entities is the way forward, as there are hundreds of mappings being missed out. Doing this via PHP before the diff is executed might be a better approach

**Comment by anuragteapot** [comment]
> I don't think using Javascript to decode the entities is the way forward, as there are hundreds of mappings being missed out. Doing this via PHP before the diff is executed might be a better approach

I think `jsDiff` return the encode HTML special characters. So, how we can achive this in PHP?

**Comment by brianteeman** [comment]
Look at how the old and new are displayed. You will need to do something similar with the diff

`<?php echo htmlspecialchars($newSubValue, ENT_COMPAT, 'UTF-8'); ?>`

**Comment by C-Lodder** [comment]
Ahh it's jsdiff rendering the string. Can you please try updating to v4.0.0 of the package and see if this works. I'm maintaining one of the developer's projects so I can get in contact with him and see if there's a more viable workaround

**Comment by amitranjan2** [comment]
> Ahh it's jsdiff rendering the string. Can you please try updating to v4.0.0 of the package and see if this works. I'm maintaining one of the developer's projects so I can get in contact with him and see if there's a more viable workaround

I checked on v4.0.1 . It's not working

**Comment by BertaOctech** [comment]
I compared two versions of the same articles, I observed the problem stated in the issue, but when I applied the patch nothing changed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23897">issues.joomla.org/tracker/joomla-cms/23897</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :red_circle: unsuccessfully on 4ca534682ad87f3e54db72810bd663c956691692<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23897">issues.joomla.org/tracker/joomla-cms/23897</a>.</sub>

**Comment by brianteeman** [comment]
Looks like this can be closed as I cannot replicate the reported issue

screen shot 2020-07-03 at 18 48 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23897">issues.joomla.org/tracker/joomla-cms/23897</a>.</sub>

**Pull request closed without merging**
