### PR TITLE
Update lib_joomla.ini

### PR DESCRIPTION
**Pull request by MartijnMaandag**
Pull Request for Issue #36959 .

### CODE REVIEW

**Comment by Kostelano** [comment]
Make a copy/paste of the file in **/language/en-GB/**, they are the same.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e4118645c3a99218ccf4c5a67c4b8882aa0d70d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36963">issues.joomla.org/tracker/joomla-cms/36963</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e4118645c3a99218ccf4c5a67c4b8882aa0d70d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36963">issues.joomla.org/tracker/joomla-cms/36963</a>.</sub>

**Comment by zero-24** [comment]
@MartijnMaandag can you do a PR against 3.10 too or should I? Its the same string thats wrong there too so we can merge it up from there. Just changing the branch didnt worked out.

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36963">issues.joomla.org/tracker/joomla-cms/36963</a>.</sub>

**Comment by zero-24** [comment]
PR done here: https://github.com/joomla/joomla-cms/pull/36969 closing here so it can be merged up from 3.10 into 4.1 and 4.2

**Pull request closed without merging**
