### PR TITLE
[Schema checker] (Database FIX) Add support for checking NULL and DEFAULT column attributes

### PR DESCRIPTION
**Pull request by ggppdk**
Currently Database Schema checker (Database FIX) button is ignoring
- NULL column attribute
- DEFAULT column attribute

e.g. this is not checked
```sql
ALTER TABLE `table1` MODIFY `colname1` NOT NULL DEFAULT 'somevalue'
```

Also this is applied **only when column is of wrong name**
```sql
ALTER TABLE `table1` CHANGE `colname_old` `colname_new` NOT NULL DEFAULT 'somevalue'
```
Thus the above query will not run if column is correct name despite NULL and DEFAULT attributes being of wrong value

### Summary of Changes
Modify Schema checker to support checking the above
(modified and tested Mysql / Maria DB, someone should help with the other DBs)

### Testing Instructions
View an 'upgrade' SQL file that has 

```sql
ALTER TABLE 'table1' MODIFY/CHANGE ...
```

e.g.
administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-04
```sql
ALTER TABLE `#__extensions` CHANGE `enabled` `enabled` TINYINT(3) NOT NULL DEFAULT '0';
```

-- Go to a DB manager e.g. phpmyadmin and change it to NULL
Run the DB Fixer and you will be ask to fix it (back to NOT NULL)

-- Go to a DB manager e.g. phpmyadmin and change DEFAULT to '1'
Run the DB Fixer and you will be ask to fix it (back to '0')

If your apply this PR to some older installations e.g. a J2.5 upgraded up to staging,
then probably you will find several errors ... already being there

### Expected result
Database Schema checker (Database FIX) supports checking 
queries like: ALTER TABLE 'table1' MODIFY/CHANGE
- NULL column attribute
- DEFAULT column attribute

### Actual result
The above are not checked

### Documentation Changes Required

None

### CODE REVIEW

**Comment by wilsonge** [comment]
This needs doing for the mssql and postgresql drivers too. we need parity between the drivers

**Comment by ggppdk** [comment]
> This needs doing for the mssql and postgresql drivers too. we need parity between the drivers

Yes indeed , and i have asked for someone to volunteer to convert code to the other DBs
it will take me some time to setup again these environments,  but if i get some time i will do it

**Comment by ghost** [comment]
@ggppdk do i guess correct there is no Progress on this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17351">issues.joomla.org/tracker/joomla-cms/17351</a>.</sub>

**Comment by ggppdk** [comment]
yes, this code is still implemented for only MySQL, don't have time to test / implement for other DBs now, this will need to wait for a while longer

**Comment by ghost** [comment]
thanks for Info @ggppdk.

**Comment by wilsonge** [comment]
@alikon are you interested in picking this up for non-mysql drivers?

**Comment by alikon** [comment]
i'll look at it

**Comment by alikon** [comment]
@ggppdk can you solve the conflict please

**Comment by alikon** [comment]
after some dirty hacks for solving conflicts, and as per testing info 
under mysql driver it works as described....
i'll try to port these changes to the postgresql driver too...

**Comment by wilsonge** [comment]
Thanks :)

**Comment by ggppdk** [comment]
Rebased the PR,
the file had no other changes, it was simply moved to new location

**Comment by alikon** [comment]
the postgresql version is #18483

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ed379a2cbdc9afc16b31fec66eee0566fbc771fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17351">issues.joomla.org/tracker/joomla-cms/17351</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on ed379a2cbdc9afc16b31fec66eee0566fbc771fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17351">issues.joomla.org/tracker/joomla-cms/17351</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
