### PR TITLE
Remove some absolute paths from sysinfo download

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue  #9252
#### Summary of Changes

The following values in the downloaded sysinfo text are obfuscated for the following (correctly): 

log_path: xxxxxx
tmp_path: xxxxxx

The absolute path is still available in the information downloaded from the PHP information 
# Example

```
    error_log
    =============
    Local Value: /Applications/MAMP/logs/php_error.log
    Master Value: /Applications/MAMP/logs/php_error.log

    upload_tmp_dir
    =============
    Local Value: /Applications/MAMP/tmp/php
    Master Value: /Applications/MAMP/tmp/php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9252">issues.joomla.org/joomla-cms/9252</a>.</sub>
```

Note that the absolute path being shown in the folder permissions will be solved in another PR

### CODE REVIEW

**Comment by wilsonge** [comment]
So without this patch applied, both those values are already obfuscated for me. Is this a Mac specific bug?

**Comment by brianteeman** [comment]
in the php section of the downloaded report?

**Comment by wilsonge** [comment]
Ahhhh right three things - first of all - you are right that in the PHP Section it has gone. Second of all I was testing for the wrong thing because only half the testing instructions copied across from the issue :P. Third of all I still have an instance of my full log path under the section "Folder Permissions"

**Comment by wilsonge** [comment]
```
=============
Folder Permissions
=============
administrator/components:  writable
administrator/language:  writable
administrator/language/en-GB:  writable
administrator/language/overrides:  writable
administrator/manifests/files:  writable
administrator/manifests/libraries:  writable
administrator/manifests/packages:  writable
administrator/modules:  writable
administrator/templates:  writable
components:  writable
images:  writable
images/banners:  writable
images/headers:  writable
images/sampledata:  writable
language:  writable
language/en-GB:  writable
language/overrides:  writable
libraries:  writable
media:  writable
modules:  writable
plugins:  writable
plugins/authentication:  writable
plugins/captcha:  writable
plugins/content:  writable
plugins/editors:  writable
plugins/editors-xtd:  writable
plugins/extension:  writable
plugins/finder:  writable
plugins/quickicon:  writable
plugins/search:  writable
plugins/system:  writable
plugins/twofactorauth:  writable
plugins/user:  writable
templates:  writable
configuration.php:  writable
cache:  writable
administrator/cache:  writable
C:\VirtualHost\joomla350.testing.org\joomla-cms/logs:  writable
C:\VirtualHost\joomla350.testing.org\joomla-cms/tmp:  writable
```

**Comment by brianteeman** [comment]
Yes Folder permissions was the part that I said I didnt know how to fix :(

**Comment by brianteeman** [comment]
Updating PR
I forgot to do
upload_tmp_dir

**Comment by wilsonge** [comment]
See https://github.com/brianteeman/joomla-cms/pull/4 - Caveat - this means that it no longer shows in the web interface :/

**Comment by brianteeman** [comment]
Is that a good idea?

On 2 March 2016 at 00:40, George Wilson <notifications@github.com> wrote:

> See brianteeman#4 <https://github.com/brianteeman/joomla-cms/pull/4> -
> Caveat - this means that it no longer shows in the web interface :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9274#issuecomment-190991718>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Probably not... but unfortunately the same code (for that part) serves the HTML, JSON and txt output :/

**Comment by brianteeman** [comment]
There must be a better option because we do need to see that full path in
the web interface - its v useful

On 2 March 2016 at 00:43, Brian Teeman <brian@teeman.net> wrote:

> Is that a good idea?
>
> On 2 March 2016 at 00:40, George Wilson <notifications@github.com> wrote:
>
>> See brianteeman#4 <https://github.com/brianteeman/joomla-cms/pull/4> -
>> Caveat - this means that it no longer shows in the web interface :/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/9274#issuecomment-190991718>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
OK will come back to it tomorrow. Need some sleep. If any testers come across this please feel free to test this "as is" the last part can be done in a separate PR!

**Comment by infograf768** [comment]
There is another PR here, but towards master
https://github.com/joomla/joomla-cms/pull/9279

**Comment by brianteeman** [comment]
Closed in favour of #9280 which is complete

**Pull request closed without merging**
