### PR TITLE
Fix line height parameter in CodeMirror

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #29177.

### Summary of Changes
Change 1.0 and 2.0 to 1 and 2.

### Testing Instructions
1. Go to your Plugin Manager and open Codemirror
2. Click on the `Appearance Options` tab
3. Set the `Line Height` to `2.0`
4. Click `Save`

### Expected result

The parameter shows as `2.0`

### Actual result

The parameter shows as `1.0`

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 894a483e6622cd4433b5102ec1ce141fbc48946f<br /><br />Fixes the issue + all other line heights still work, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29194">issues.joomla.org/tracker/joomla-cms/29194</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 894a483e6622cd4433b5102ec1ce141fbc48946f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29194">issues.joomla.org/tracker/joomla-cms/29194</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29194">issues.joomla.org/tracker/joomla-cms/29194</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
