### PR TITLE
Add filter by Tag to mod_article_category

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for missing feature

### Summary of Changes
This Pull Request add the option to filter by tag.
- When you create a menu item for Category Blog you can select both Category and Tag.
- When you create the module mod_article_category you cannot filter by Tag. 
This pull request adds the ability to filter by tag too. 

### Testing Instructions
- Have com_content items with tags
- Create a module mod_article_category
- - assign to a visible module position
- - select category to filter the content
- - show X amount of items to display
- - select tag to filter... oh boy... there is no tag filter

apply patch
- Refresh backend
- Open created module
- - select tag to filter... yes... there is the option to filter by tag

### Expected result
Before patch
- Refresh frontend and notice X amount of items from a selected category. 

After patch
- Refresh frontend and notice X amount of items from a selected category and filtered by tag

### Documentation Changes Required
Be sure you have content items with tags assigned to them.

### CODE REVIEW

**Comment by allrude** [comment]
I have tested this item :white_check_mark: successfully on eadf35af4006d3f44a16eecb64901806b6f741d4<br /><br />I tested this extra option successfully, nice to have this option, Thanks Hans<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16945">issues.joomla.org/tracker/joomla-cms/16945</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on eadf35af4006d3f44a16eecb64901806b6f741d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16945">issues.joomla.org/tracker/joomla-cms/16945</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
I fixed the codestlye issues

**Comment by franz-wohlkoenig** [comment]
@brianteeman should we test again or set RTC?

**Comment by brianteeman** [comment]
it was only codestyle so one more test will be fine but it shouldnt have been set to rtc with those errors

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 839e617174814b2f12c498da5a0efc7b21d57b0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16945">issues.joomla.org/tracker/joomla-cms/16945</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by mbabker** [comment]
This needs to be synced with staging before I can merge it.  We added a state filter to stop loading tags in the modules with https://github.com/joomla/joomla-cms/commit/008e5cd072119cfe49c5e5d4ec8369e5c064f2f9 and that is going to conflict with this PR.

**Comment by hans2103** [comment]
@mbabker synched and ready to be tested again. Added php logic to conditional load tags or not. Depending if any tag is selected to filter.

**Review by mbabker — APPROVED** [review]

**Comment by mbabker** [comment]
Looks fine, if someone can do a quick test with the added logic in place we should be good to merge this.

**Comment by ghost** [comment]
will test now.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d1017adff2ddd0fef54d0f6256d2b25dc61a1944<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16945">issues.joomla.org/tracker/joomla-cms/16945</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d1017adff2ddd0fef54d0f6256d2b25dc61a1944<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16945">issues.joomla.org/tracker/joomla-cms/16945</a>.</sub>

**Comment by pepperstreet** [comment]
Hello, in the XML... shouldn't the tag-filter parameter get the "**multiple**" option? 
Comparable to the improved Blog MenuItem parameter in this issue #18021 and PR #18234

**Comment by hans2103** [comment]
@Pepperstreet please create a new pull request. This one has already been merged and closed.

**Pull request merged**
