### PR TITLE
[4.0] Group action buttons for com_fields group

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR continues the grouping of action buttons in the backend (see https://github.com/joomla/joomla-cms/pull/22832, https://github.com/joomla/joomla-cms/pull/22393, https://github.com/joomla/joomla-cms/pull/23337 and https://github.com/joomla/joomla-cms/pull/23336). This time the fields group buttons.

### Testing Instructions
Go to any fields group manager in the backend and check the toolbar. There should be a "Change status" dropdown now which activates when you select a fields group item.

### CODE REVIEW

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on c584a520b13dda098734fe20981ada1fd0a9fa7f<br /><br />Works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23371">issues.joomla.org/tracker/joomla-cms/23371</a>.</sub>

**Comment by PhocaCz** [comment]
Tested in 4.0.0-alpha6-dev successfully :ok: :heavy_check_mark: 

OK

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on ed94cbf320132bb23e560faf0664a0c70d684d74<br /><br />Tested now in Joomla! Issue Tracker - CMS

Tested succesfully on Joomla! 4.0.0-alpha7-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23371">issues.joomla.org/tracker/joomla-cms/23371</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23371">issues.joomla.org/tracker/joomla-cms/23371</a>.</sub>

**Pull request merged**
