### PR TITLE
[4.4] Fix missing 'separator' lines between sub menus in Admin Components

### PR DESCRIPTION
**Pull request by Irata**
Adds separators as submenu's items for Components

Pull Request for Issue #41123 .

### Summary of Changes
Alters the 'type' attribute for sub-menus when installing a Component to allow for separator lines to be added to the sub menu of a Component. For use when you need to break up or group sub-menu items of a Component.

In the manifest .xml file for a components you can indicate the placement of the separator by adding the element `<menu type=separator>--<menu>`  between a set of  <submenu></subment> elements. 

<submenu>
    <menu ....>
    <menu type="separator">---</menu>
    <menu ...>
</submenu>

The processing to read and render the separator already exists in the Joomla core, all that was missing was the ability to specify the  'type' of separator when installing a component. The rendering of the separator will either use the characters defined between the <menu> and </menu> elements or the characters are stripped and the separator is rendered as a line with CSS.

### Testing Instructions
Add the `<menu type=separator>--<menu>` element to the manifest .xml file of a component and Install the component in an instance of Joomla. 

Below is a sample manifest .xml file that can be .zipped and installed to create a dummy component menu and sub-menu that will create the various separators.
```
<?xml version="1.0" encoding="utf-8" ?>
<extension type="component" method="upgrade">
    <name>com_testing</name>
    <creationDate>2024</creationDate>
    <author>someone</author>
    <authorEmail>somethingsomewhere.com</authorEmail>
    <authorUrl>something</authorUrl>
    <copyright>something</copyright>
    <license>GNU General Public License version 2 or later;</license>
    <version>1.0.0</version>
    <description>Testing</description>

    <!-- Back-end files -->
    <administration>
        <!-- Menu entries -->
        <menu view="emporium">Testing</menu>
        <submenu>
            <menu link="option=com_testing">Menu Item 1</menu>
            <menu type="separator">-----------------------</menu>
            <menu link="option=com_testing">Menu Item 2</menu>
            <menu type="separator" alias="second">.....................</menu>
            <menu link="option=com_testing">Menu Item 3</menu>
            <menu type="separator" alias="third">______________________</menu>
        </submenu>
        <files>
            <filename>testing.xml</filename>
        </files>
    </administration>
</extension>
```

### Actual result BEFORE applying this Pull Request

Nothing happened. 'type=separator' is ignored and replaced with 'component'

### Expected result AFTER applying this Pull Request
Expand your Component name under the Admin area Component Menu on the left and you should see the separator displayed as a sub menu item. 

In the #__menu table the entry for your separator will have a field of type with the value 'separator' and the alias will be the current date

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>https://docs.joomla.org/Manifest_files</link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by marcorensch** [comment]
It works as expected when adding one separator but when adding multiple via xml
```
<menu type="separator">--</menu>
```
it creates only one (the last one) in the database

**Review by marcorensch — CHANGES_REQUESTED** [review]
We need to take care of the alias too.
See my full idea here: https://github.com/joomla/joomla-cms/pull/42588#issuecomment-1875449451

**Comment by Irata** [comment]
@marcorensch Thanks for testing and the feedback, I hadn't thought about testing it for multiple separators.

I like your first suggestion of updating just the alias assignment line, 
`$data['alias']        = ((string) $child->attributes()->alias) ?: (string) $child;`
as the better solution and is simple to implement and document.  

Using this example in the manifest .xml is shows the various combinations.
```
        <submenu>
            <menu link="option=com_testing">Menu Item 1</menu>
            <menu type="separator">-----------------------</menu>
            <menu link="option=com_testing">Menu Item 2</menu>
            <menu type="separator" alias="second">.....................</menu>
            <menu link="option=com_testing">Menu Item 3</menu>
            <menu type="separator" alias="third">______________________</menu>
        </submenu> 
```

Specifying an `alias` for the first `separator` is optional and only required for subsequent `separators`.

For Joomla instances that don't have this PR then only one separator will be saved in the table but the characters in the `title` can be used to create a character based separator.

This snippet of code in `..\administrator\modules\mod_menu\src\Menu\CssMenu.php` (#461) is used to empty the title property and leave it to the css to draw the separator. For instance prior to this PR the condition is never met therefore the characters in the title are displayed.
```
            if ($item->type === 'separator' && $itemParams->get('text_separator') == 0) {
                $item->title = '';
            }
```

**Comment by marcorensch** [comment]
@Irata I would say that sounds like a good solution to cover all eventualities.

**Comment by Irata** [comment]
I have updated the the extra line to allow the alias to be specified when creating multiple separators.

Please review and test.

**Review by marcorensch — APPROVED** [review]

**Comment by MacJoom** [comment]
@irata and @marcorensch thanks for the good work - @marcorensch could please mark a successful test in the issue tracker and remember: we still need another successful test

**Comment by Irata** [comment]
I have updated the Testing instructions with a sample manifest .xml that can be used to test this PR.

**Comment by marcorensch** [comment]
I have tested this item :white_check_mark: successfully on e05f6943cdb6bc30c563d20b040884309c578882<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42588">issues.joomla.org/tracker/joomla-cms/42588</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42588">issues.joomla.org/tracker/joomla-cms/42588</a>.</sub>

**Pull request merged**
