### PR TITLE
removed redundant/invalid css prop

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - border radius property is invalid as there is no border or background.
Screenshot from 2019-03-27 21-58-30

### Summary of Changes
Removed border-radius prop for content class.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not correct. The real question is should the variable be "none" or "0"

**Comment by bahl24** [comment]
As there is no border or background, I don't think there is any use of border-radius. See https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius

**Comment by Quy** [comment]
Please open PR in the new backend template repo if still an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24384">issues.joomla.org/tracker/joomla-cms/24384</a>.</sub>

**Comment by ghost** [comment]
@bahl24 Repo: https://github.com/joomla/backend-template

**Pull request closed without merging**
