### PR TITLE
[4.0] Add library support to namespace mapper, other fixes

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #27459.

### Summary of Changes

Refactors `JNamespacePsr4Map::getNamespaces()` code to be based on extension type rather than paths.
Adds library extension support to namespace mapper.
Removes empty component frontend namespaces.
Removes trailing slash from paths.

### Testing Instructions

This should be tested on both Linux and Windows.

Delete `libraries/autoload_psr4.php` file.
Test that Joomla! still works.
Test that `com_media` works.
Test that `System - Debug` plugin works when debug is enabled.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge How is this PR related to the Prepared Statements project?

**Comment by richard67** [comment]
@SharkyKZ I can test later but only with Linux.

Other testers please report back if Linux or Windows was used so we later can see if both was tested sufficiently.

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 282c48d0748c1905bc8209d705ef889cd072940b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27479">issues.joomla.org/tracker/joomla-cms/27479</a>.</sub>

**Comment by richard67** [comment]
@810 Have you tested with webserver on Linux? Or Windows? Or both?

**Comment by 810** [comment]
windows only

**Comment by richard67** [comment]
@810 Thanks for reporting back. Is good to have an overview who tested on what.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 282c48d0748c1905bc8209d705ef889cd072940b<br /><br />I've tested successfully with sebserver on Linux.

Have also compared newly created autoloader file with backup, using BeyondCompare (my favourite diff tool). A few frontent namespaces have been removed, guess these are the unused ones mentioned in the description. Frontend and backend still work fine.

Now we have each one good test on Linux and Windows. ~~We need~~ Would be nice to have one more test for each.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27479">issues.joomla.org/tracker/joomla-cms/27479</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ We have 2 good tests, one for each server OS type. Shall I give RTC or do you want more tests?

**Comment by SharkyKZ** [comment]
Have 2 tests so setting RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27479">issues.joomla.org/tracker/joomla-cms/27479</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
