### PR TITLE
Fix typo in Hathor template name

### PR DESCRIPTION
**Pull request by Bakual**
Commit https://github.com/joomla/joomla-cms/commit/4e825aadb6e5811c2f11c8d9366e6b59f8878e1b introduced some misspelling in the name of the Hathor template. This PR fixes that.

@rdeutz Please review and merge.

### CODE REVIEW

**Comment by Bakual** [comment]
That being said, the file `administrator/language/en-GB/en-GB.lib_joomla.ini` is the wrong place for such a warning message. That file needs to be in sync with frontend and we certainly don't need that message in frontend. I left it for now since this PR is about fixing the typos.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 41fc493def2b26e98ccef6e6c4fa67a155502fb1<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15125">issues.joomla.org/tracker/joomla-cms/15125</a>.</sub>

**Comment by joomdonation** [comment]
There is another typo here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L122 which need to be fixed, too

That line need to be changed to **->where($db->quoteName('template') . ' = "hathor"')**

**Comment by infograf768** [comment]
Agree with @joomdonation and @Bakual

**Comment by rdeutz** [comment]
I have fixed the typos

**Pull request closed without merging**
