### PR TITLE
Replace Joomla logo graphics based on draft brand manual

### PR DESCRIPTION
**Pull request by mbabker**
This PR replaces any graphic that is solely the Joomla logo or brand mark with an updated version based on the draft brand manual and published graphics repo.  Note that there are still some graphics to be updated (all in the root images folder; graphics editing really isn't my thing).  This affects the favicon and any of the base logo graphics in the repo.

There is one change that causes a visual difference and that's with the Isis template logo that's at the bottom of the screen.  I didn't manipulate the colors any from the downloaded graphics, so those are currently using a straight black/white combination instead of shades that match the template design.  Again, I'm not a graphics person, so if someone wants to modify this (and gets blessing from the TM/Marketing folks to do so) then have at it.

Note: This patch cannot be applied via the patch tester; it does not work with binary files.

### CODE REVIEW

**Comment by n9iels** [comment]
In #6432 I replace that small Joomla! Logo at the bottom of the loginscreen with the `icon-joomla` font set icon. In combination with #6340 the style is the same.

**Comment by brianteeman** [comment]
Any chance of squeezing this in to the release - one of the current images is pretty broken #6491 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6447">issues.joomla.org/joomla-cms/6447</a>.</sub>

**Comment by mbabker** [comment]
I did get a couple of other graphics from Chiara to replace the "Support Joomla" and "Powered by Joomla" images and those are in here now too.

**Comment by mbabker** [comment]
Last update.  The last graphic I saw that's in use was the `images/joomla_black.gif` image (it's the default graphic for the Beez3 template).  This is replaced with a .png version again from the main repo.  The _green and _logo_black images were unused anywhere in the repo (as best as I can tell, probably old sample data images from 2.5) and I've just completely removed them.  As we don't include these images in our update packages, this doesn't affect existing sites using those graphics; nor will they receive the updated imagery.

This leaves the graphics in the `images/banners` folder left to update (OSM & Joomla! Shop banners only used in sample data).

**Comment by n9iels** [comment]
It should be nice if the image on the login screen and the Joomla! logo in the top right corner are retina proof. Now, they get blurry on high resolution screens.
login-logo-before

To make a image retina proof, you had to resize the image to twice its view size. For example, the logo on the login screen is display with a size of: 256x53. So the retina proof file is: 512x56.
If have this resized files, and it works like expected:
joomla-logo-after

Is it possible to implement these files? I'm asking because of the different file size.
If it is possible, maybe it is a good idea to add the files to this PR to avoid merge conflicts

**Comment by mbabker** [comment]
Honestly, I'd rather not get into a situation where I'm trying to sort out stylesheet rules to put larger images in place.  Not that I don't agree with having higher resolution images, but I'm not someone who is comfortable figuring out the CSS rules for images anywhere in a document.

**Comment by n9iels** [comment]
In this cases I didn't change the CSS files.  I'm such a mad person who likes to do that :P

So I will take a look at it tomorrow, and will search where the joomla.png and logo.png are used. With a little bit of luck there not used often, and the display size stays the same.

**Comment by n9iels** [comment]
But I understand your thoughts. It is just a possible idea :)

**Comment by n9iels** [comment]
After some research:
`joomla.png` is only used on the login screen of the isis template and `logo.png` is only used in the right top corner of isis. So change these two images to new images with twice it's size doesn't affect other pages. I don't see any reason why we shouldn't change these two images

administrator/templates/isis/images/joomla.png
joomla

administrator/templates/isis/images/logo.png
logo

**Comment by mbabker** [comment]
Merged in the retina graphics for Isis.  Any reason this cannot be merged in soon-ish?

**Comment by Bakual** [comment]
Set to RTC based on Review.

**Pull request merged**
