### PR TITLE
[4.0] Media Field changes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request is a follow up for https://github.com/joomla/joomla-cms/pull/34634 .

### Summary of Changes
- Expose the types attribute for the media fields
- Adjusts the preview 

### Testing Instructions

Will post them once the other PR is merged.

### Expected result AFTER applying this Pull Request

Screenshot 2021-06-30 at 03 19 08

Screenshot 2021-06-30 at 03 19 37

Screenshot 2021-06-30 at 03 19 22

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont see the need for this PR. Those are image fields. Or am I missing something?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34655">issues.joomla.org/tracker/joomla-cms/34655</a>.</sub>

**Comment by dgrammatiko** [comment]
@brianteeman my intention is not to change existing image fields to support more media types. The change in the article form is an artifact as I was working/testing this

**Comment by brianteeman** [comment]
sorry I dont understand

**Comment by dgrammatiko** [comment]
>  sorry I dont understand

So, this PR introduces a new attribute for the Media Field (xml `types="images,audios,videos,documents"`).
- Without setting this field the media field is totally compatible (eg only images)
- Setting the value in a field's xml a dev can control what types of media the field could handle

The change in the article.xml file is purely for testing/valiation purposes, won't be part of the PR

**Comment by Quy** [comment]
Will this fix #19954 for media custom field?

**Comment by dgrammatiko** [comment]
> Will this fix #19954 for media custom field?

Yes, that's the idea

**Comment by dgrammatiko** [comment]
Closing this as I merged the changes to the other PR

**Pull request closed without merging**
