### PR TITLE
[4.0] Fix broken pagination in com_plugins

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #31986 .

### Summary of Changes
Prevent the change of the hash when the limitstart is changed.

### Testing Instructions
See #31986

### Actual result BEFORE applying this Pull Request
Pagination is visible

### Expected result AFTER applying this Pull Request
Pagination is not visible

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6700cd506ea2d829e93b1c8d64b1bd143a762ec4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32024">issues.joomla.org/tracker/joomla-cms/32024</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6700cd506ea2d829e93b1c8d64b1bd143a762ec4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32024">issues.joomla.org/tracker/joomla-cms/32024</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32024">issues.joomla.org/tracker/joomla-cms/32024</a>.</sub>

**Comment by chmst** [comment]
Shouldn't the title be "in com_plugins"? @bembelimen

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
