### PR TITLE
[4.0] Some class errors

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Rename `SysinfoModel.php` to `SysInfoModel.php`.
Typo in `Joomla\Component\Privacy\Site\Service\Router`.

### Testing Instructions

Code review? CC @wilsonge 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Don't know if changing file casing causes issues at this point. If it does, we can rename the class instead?

**Comment by brianteeman** [comment]
typo looks correct to me
not sure about the camelcase name change - renaming this way always causes issues

**Comment by richard67** [comment]
Maybe just leave the file name as it is and only correct the typo?

**Comment by SharkyKZ** [comment]
@richard67 that won't fix the issue. We need to either rename the file or rename the class and change all instances of it in code.

Anyways, this is fine, I think, if updates between alphas aren't officially supported.

**Comment by richard67** [comment]
@SharkyKZ Ah, yes I forgot that with the update support ;-)

**Comment by SharkyKZ** [comment]
Hm, there are more instances of this:

```
\Joomla\Component\Menus\Administrator\Field\ComponentsCategoryField
\Joomla\Component\Menus\Administrator\Field\MenuOrderingField
```

Rename classes or rename files? Renaming files also requires updating XML files but it would be nice to have correctly cased classes at some point.

**Comment by richard67** [comment]
Hmm, I don't remember right now how such renames were handled in past, was not involved in that, just reading some PR when passing by long time ago. George maybe remembers that better.

**Comment by wilsonge** [comment]
We had to rename them in two commits - to a different name and back again for git to be happy. Then that still doesn't work on shared hosts (but at this stage in j4 we don't guarentee b/c there so it's not a problem).

TL/DR - just rename the files and let's do this correctly and set the correct precedent :)

**Comment by SharkyKZ** [comment]
Hm, I think it's better to rename `SysInfoModel` and revert the filename change. The view is called `Sysinfo` so it tries to load `SysinfoModel` by default anyways.

**Comment by SharkyKZ** [comment]
Unless we want to rename the view, which also means updating all links to it.

**Comment by wilsonge** [comment]
No I think keeping the existing view type makes sense

**Comment by SharkyKZ** [comment]
So this PR should be fine as it is. Just found more of the same:

```
\Joomla\CMS\Encrypt\AES\Openssl
\Joomla\CMS\Filesystem\Support\StringController
\Joomla\CMS\Form\Field\SQLField
```
StringController has already been reported for 3.x (#23725). Other two are 4.0-specific.

**Comment by wilsonge** [comment]
This will do as a first pass - thankyou @SharkyKZ !

**Comment by ghost** [comment]
Do these changes also work under Windows?
In my ticket (#23725) the developers also tried to rename the StringController and encountered problems with the update mechanism when changing a file name to upper or lower case under Windows.

Quote #23762:
> I have tested this item  unsuccessfully on [a0538dc](https://github.com/joomla/joomla-cms/commit/a0538dc6550be26675056e029b523c0c1ee0c2f7)
> 
> In windows this PR breaks the whole deletion process, because `realpath` converts all slashes to `\`, so it's always not true (and the JFile::delete will never be called).
> 
> Additional there will not be 2 files in windows, so the deletion process (if it works) would delete the whole file without replacement.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/23762](https://issues.joomla.org/tracker/joomla-cms/23762).

**Comment by SharkyKZ** [comment]
@Orgoth this PR fixes only new files added in 4.0. Updates between 4.0 dev builds aren't supported, so if you try to update from older 4.0 version, you'll have to apply the filename changes manually or just use a new 4.0 installation.

This, however, won't be an issue when updating from 3.x because these files do not exist in 3.x.

**Comment by ghost** [comment]
Updates from Nightly > Nightly Build will be supported at Beta.

**Comment by wilsonge** [comment]
@SharkyKZ The field class rename broke the system tests so we've reverted back to how it was for now https://github.com/joomla/joomla-cms/pull/25530 and will need to come up with an alternative fix

**Comment by SharkyKZ** [comment]
@wilsonge My bad, it's a field class 🤦‍♂ . We'd need to update the type in forms to use the new casing. As a simple alternative we could rename the class to `SqlField`.

**Comment by wilsonge** [comment]
Lets just rename the class back to lowercase I think - i mean uppercase SQL is just a nice to have

**Comment by wilsonge** [comment]
The casing in the field type hasn't changed from 3.x so I'd rather not change it

**Pull request merged**
