### PR TITLE
[4.0] optgroup color

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #26928 .

### Testing Instructions
1. Open the filter options for articles and  check the **stage** dropdown - you should see the name of the workflow and the stages
2. Select a stage, the page reloads and repeat step 1

### Expected result
you should see the name of the workflow and the stages in both scenario

### Actual result
You cannot see the name of the workflow once a state has been selected

After applying this PR the workflow name will always be visible

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22303a6213d3fd6eebc114b3038f6198e14c0172<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26987">issues.joomla.org/tracker/joomla-cms/26987</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 22303a6213d3fd6eebc114b3038f6198e14c0172<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26987">issues.joomla.org/tracker/joomla-cms/26987</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26987">issues.joomla.org/tracker/joomla-cms/26987</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
