### PR TITLE
Disable sudo in Travis to use the new enviroment

### PR DESCRIPTION
**Pull request by Bakual**
According to http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade we can migrate to the new Travis infrastructure by just adding `sudo: false` to our `.travis.yml` file.

This PR does this and it indeed run a bit faster.

### CODE REVIEW

**Comment by Bakual** [comment]
Last Travis runs were around 6-8 minutes. With this change it's around 4-6 minutes. So it's a bit faster :smile:

**Comment by mbabker** [comment]
I did it on the 3.5-dev branch not wanting to touch staging with it yet.  But if we're good with this change being applied to everything going forward, then merge it.

**Comment by Bakual** [comment]
Oh, didn't even notice this. :+1: 
Will adjust then to use the same code as you did in 3.5.
I think it should be fine as long as Travis passes.

Do you know where those PHP warnings come from for PHP 5.5 and 5.6?
> PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/apcu.so' - /home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/apcu.so' - /home/travis/.phpenv/versions/5.6.5/lib/php/extensions/no-debug-zts-20131226/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.

Looks line an issue in the enviroment itself to me and they don't affect the result.

**Comment by dgt41** [comment]
APCu is not available by default for PHP 5.5 and 5.6. I guess this is needed:
``` 
# +5.5 uses APCU
  - if [ "`phpenv version-name`" != "5.4" ] && [ "`phpenv version-name`" != "5.3" ] && [ "`phpenv version-name`" != "hhvm" ]; then printf "\n"| pecl install apcu-beta && echo -e "extension = apcu.so\napc.enabled=1\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
```

**Comment by mbabker** [comment]
It used to be there and at some point in Travis' updates it went away.
 *shrug*

It's just something to deal with updating at some point.

**Pull request merged**
