### PR TITLE
[5.2] Invalid usage of static methods

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Static methods should be not called in object context.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

See IDE warnings.

### Expected result AFTER applying this Pull Request

No IDE warnings.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
need some tests here please

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.3-dev.

**Review by Hackwar — APPROVED** [review]

**Review by laoneo — APPROVED** [review]

**Comment by Hackwar** [comment]
Thank your for your contribution @Denitz!

**Pull request merged**
