### PR TITLE
[4.0][CLI] user:add fix notice

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #29814 .

### Summary of Changes
added check

### Testing Instructions
see #29814

### Actual result BEFORE applying this Pull Request

notice

### Expected result AFTER applying this Pull Request

no more notice

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 052fb59ab03c04bb3859de964909d71f787093f4<br /><br /> [OK] User created!                                                                                                     
No errors<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 052fb59ab03c04bb3859de964909d71f787093f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by toivo** [comment]
@alikon @ceford @Quy Did anyone of you test this in Windows?

Github blocked me from adding the following comment last night.  Now I repeated the test with this PR and the result was the same in the Beta2-dev Nightly Build of 29 June:

After an email address was entered, went into a loop, displaying 
"Please enter a password:
>The system cannot find the path specified"

Wampserver 3.2.2  Apache 2.4.43 MySQL 8.0.20 PHP 7.4.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by toivo** [comment]
@alikon @Quy Can you please reopen and fix this PR.

Tested **unsuccessfully** the command 'php cli/joomla.php user:add' in a freshly installed, out-of-the-box Beta2-dev of 30 June.

After an email address is entered, goes into a loop, displaying 
"Please enter a password:
>The system cannot find the path specified"

Wampserver 3.2.2  Apache 2.4.43 MySQL 8.0.20 PHP 7.4.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by toivo** [comment]
@wilsonge can you please reopen PR#29828 which fails in Windows - ref. https://issues.joomla.org/tracker/joomla-cms/29828#event-540243<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by ceford** [comment]
Working OK on Mac OS X with nightly build update of 2020-06-30. Can't test Windows.

**Comment by alikon** [comment]
@toivo i'm unable to test under windows, please open a new issue

**Comment by toivo** [comment]
@alikon ok, will do.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Comment by toivo** [comment]
@alikon Opened https://github.com/joomla/joomla-cms/issues/29851
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29828">issues.joomla.org/tracker/joomla-cms/29828</a>.</sub>

**Pull request merged**
