### PR TITLE
4.0 dev

### PR DESCRIPTION
**Pull request by Joe-Palmer**
JControllerLegacy implements JControllerInterface

### CODE REVIEW

**Comment by zero-24** [comment]
@wilsonge travis error here and since when we use ` * @package     Joomla.CMS` ? i guess it should be

```
 * @package     Joomla.Libraries
```

?

**Comment by wilsonge** [comment]
Yes it should be!

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/commit/733b166d8665c457aaef38accebfad5797618d5f done!

**Comment by wilsonge** [comment]
Thank you!

**Comment by wilsonge** [comment]
Btw travis errors because I merged the Pull request before it ran :)

**Comment by zero-24** [comment]
Yes and that produces big problems in the past :smile:

**Pull request merged**
