### PR TITLE
[4] s/Filter/FilterTable

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on eee6156e8b00faab21778cc647362041d56a205c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34007">issues.joomla.org/tracker/joomla-cms/34007</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on eee6156e8b00faab21778cc647362041d56a205c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34007">issues.joomla.org/tracker/joomla-cms/34007</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34007">issues.joomla.org/tracker/joomla-cms/34007</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
