### PR TITLE
Menu Label

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to update a language string. There are two changes
1. Both words are captialised which is consistent with all two word tab options
2. Menus is changed to Menu to be consistent with its usage in the modules

So the tab title in Template Manager will look the same as the tab title in the Module Manager
edvn
loz4

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on cdac31336f6eef4ebd80f1c9259b4ce3dee12c40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11074">issues.joomla.org/joomla-cms/11074</a>.</sub>

**Comment by ggppdk** [comment]
Since making this change, instead of using "Menu assignment"

should it not be ?:
"Menu assignments"

**Comment by brianteeman** [comment]
@ggppdk nope

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on cdac31336f6eef4ebd80f1c9259b4ce3dee12c40<br /><br />Yes, re-thinking it, you are right<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11074">issues.joomla.org/joomla-cms/11074</a>.</sub>

**Pull request merged**
