### PR TITLE
[3.9] Update composer

### PR DESCRIPTION
**Pull request by 810**
see: https://github.com/joomla/joomla-cms/pull/24379

Pull Request for Issue # .

### CODE REVIEW

**Comment by HLeithner** [comment]
you updated composer without new files. seams wrong.

**Comment by mbabker** [comment]
```sh
git checkout joomla/staging
git checkout -b update-composer
composer install
composer update
composer install --no-dev
git commit -am "Update Composer dependencies"
git push -u origin update-composer
```

3.x has to have `libraries/vendor` path committed, 4.0 it is ignored.

**Comment by 810** [comment]
thnx michael but then i see only 5 changes, and non from the wanted files.
image

**Comment by mbabker** [comment]
Unstaged files I'm going to assume means new files not yet in the repo, which is right for the `joomla/session` package.  You should still have a list of changed files.

**Comment by mbabker** [comment]
Also, those `TestListenerFor*.php` files can be added to the `.gitignore` alongside the other files from the same package.

**Comment by 810** [comment]
Yeah but you should see also yellow changed files like composer.lock ect.

**Comment by mbabker** [comment]
No idea what you're using for git but if that view is really only showing uncommitted files then I imagine there's some other view or setting you need to be looking at to see the full diff.

**Comment by 810** [comment]
im using gitkraken.

it should like:
image

**Comment by mbabker** [comment]
I have no clue then.  This should be your changeset.

```sh
Michaels-Mac-mini:joomla-cms mbabker$ git status
On branch composer-update
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   composer.lock
	modified:   libraries/vendor/composer/autoload_classmap.php
	modified:   libraries/vendor/composer/autoload_static.php
	modified:   libraries/vendor/composer/installed.json
	modified:   libraries/vendor/joomla/application/src/AbstractApplication.php
	modified:   libraries/vendor/joomla/application/src/AbstractCliApplication.php
	modified:   libraries/vendor/joomla/application/src/AbstractDaemonApplication.php
	modified:   libraries/vendor/joomla/application/src/AbstractWebApplication.php
	modified:   libraries/vendor/joomla/application/src/Cli/CliInput.php
	modified:   libraries/vendor/joomla/application/src/Cli/CliOutput.php
	modified:   libraries/vendor/joomla/application/src/Cli/ColorProcessor.php
	modified:   libraries/vendor/joomla/application/src/Cli/ColorStyle.php
	modified:   libraries/vendor/joomla/application/src/Cli/Output/Processor/ColorProcessor.php
	modified:   libraries/vendor/joomla/application/src/Cli/Output/Processor/ProcessorInterface.php
	modified:   libraries/vendor/joomla/application/src/Cli/Output/Stdout.php
	modified:   libraries/vendor/joomla/application/src/Cli/Output/Xml.php
	modified:   libraries/vendor/joomla/application/src/Web/WebClient.php
	modified:   libraries/vendor/joomla/archive/src/Archive.php
	modified:   libraries/vendor/joomla/archive/src/Bzip2.php
	modified:   libraries/vendor/joomla/archive/src/ExtractableInterface.php
	modified:   libraries/vendor/joomla/archive/src/Gzip.php
	modified:   libraries/vendor/joomla/archive/src/Tar.php
	modified:   libraries/vendor/joomla/archive/src/Zip.php
	modified:   libraries/vendor/joomla/filesystem/src/Buffer.php
	modified:   libraries/vendor/joomla/filesystem/src/Clients/FtpClient.php
	modified:   libraries/vendor/joomla/filesystem/src/Exception/FilesystemException.php
	modified:   libraries/vendor/joomla/filesystem/src/File.php
	modified:   libraries/vendor/joomla/filesystem/src/Folder.php
	modified:   libraries/vendor/joomla/filesystem/src/Helper.php
	modified:   libraries/vendor/joomla/filesystem/src/Patcher.php
	modified:   libraries/vendor/joomla/filesystem/src/Path.php
	modified:   libraries/vendor/joomla/filesystem/src/Stream.php
	modified:   libraries/vendor/joomla/filesystem/src/Stream/String.php
	modified:   libraries/vendor/joomla/filesystem/src/Stream/StringWrapper.php
	modified:   libraries/vendor/joomla/filesystem/src/Support/StringController.php
	modified:   libraries/vendor/joomla/ldap/src/LdapClient.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Session.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Apc.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Database.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Memcache.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Memcached.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/None.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Wincache.php
	modified:   libraries/vendor/joomla/session/Joomla/Session/Storage/Xcache.php
	modified:   libraries/vendor/paragonie/sodium_compat/lib/php72compat.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Compat.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/BLAKE2b.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/Curve25519.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/Curve25519/Fe.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/Ed25519.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/Poly1305/State.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core/Util.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/BLAKE2b.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Curve25519.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Curve25519/Fe.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Ed25519.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Int32.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Int64.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/Poly1305/State.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/SipHash.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Core32/X25519.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Crypto.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/Crypto32.php
	modified:   libraries/vendor/paragonie/sodium_compat/src/File.php
	modified:   libraries/vendor/phpmailer/phpmailer/LICENSE
	modified:   libraries/vendor/phpmailer/phpmailer/VERSION
	modified:   libraries/vendor/phpmailer/phpmailer/class.phpmailer.php
	modified:   libraries/vendor/phpmailer/phpmailer/class.pop3.php
	modified:   libraries/vendor/phpmailer/phpmailer/class.smtp.php
	modified:   libraries/vendor/symfony/polyfill-ctype/LICENSE
	modified:   libraries/vendor/symfony/polyfill-php55/LICENSE
	modified:   libraries/vendor/symfony/polyfill-php55/Php55.php
	modified:   libraries/vendor/symfony/polyfill-php55/Php55ArrayColumn.php
	modified:   libraries/vendor/symfony/polyfill-php56/LICENSE
	modified:   libraries/vendor/symfony/polyfill-php56/Php56.php
	modified:   libraries/vendor/symfony/polyfill-php71/LICENSE
	modified:   libraries/vendor/symfony/polyfill-php73/LICENSE
	modified:   libraries/vendor/symfony/polyfill-php73/bootstrap.php
	modified:   libraries/vendor/symfony/polyfill-util/Binary.php
	modified:   libraries/vendor/symfony/polyfill-util/LICENSE
	modified:   libraries/vendor/symfony/yaml/Inline.php
	modified:   libraries/vendor/symfony/yaml/Yaml.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	libraries/vendor/joomla/session/Joomla/Session/Storage/Apcu.php
	libraries/vendor/symfony/polyfill-php73/Resources/
	libraries/vendor/symfony/polyfill-util/TestListenerForV5.php
	libraries/vendor/symfony/polyfill-util/TestListenerForV6.php
	libraries/vendor/symfony/polyfill-util/TestListenerForV7.php
```

**Comment by mbabker** [comment]
If you can't get it to work for whatever reason just do a PR using https://github.com/joomla/joomla-cms/compare/staging...mbabker:composer-update?expand=1

**Comment by 810** [comment]
ok works now, closing this one

**Pull request closed without merging**
