### PR TITLE
[4.0] Fix for article being submitted by Enter key

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #24035 .

### Summary of Changes

Adds missing `type` attribute to buttons.

### Testing Instructions

Open article form.
Fill out required fields.
While in a text field press Enter.

### Expected result

Nothing happens.

### Actual result

Article form is submitted.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on c5fab05112c7baada911faed9b70a9af961ce23c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24123">issues.joomla.org/tracker/joomla-cms/24123</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on c5fab05112c7baada911faed9b70a9af961ce23c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24123">issues.joomla.org/tracker/joomla-cms/24123</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24123">issues.joomla.org/tracker/joomla-cms/24123</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
