### PR TITLE
[4.0] Clean up module chromes

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27922.

### Summary of Changes

Remove MooTools based chromes.
Move inline CSS to file.
Use early returns.
Minor syntax cleanups.

### Testing Instructions

Test that different module chromes still work.

### Documentation Changes Required

`sliders` and `tabs` chromes removed.

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested and can confirm that:
Initial fault is now cleared, unable to select sliders or tabs as they are now removed - is this going to be a backwards compatability break with sites that currently use them which needs documenting?
Additional checks due to other changes
I confirm that outline.css is active when outline is selected
Clean up html5 - when html 5 is selected it works as expected with no noticable issues
Clean up Cassiopeia chromes - when selecting default or card grey it works with no noticable issues
Clean up Atum chromes - no noticable issues in the backend with the changes
Minor Cleanups - I cant see any issues rendering pages, and a code review appears fine

htmlspecialchars() - Not sure what I should look for here, I can't see anything having broken in the back end when looking at and checking the code produced.

If I have covered all the areas needed I am happy to mark this as tested successfully, unless someone can identify and other checks required.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27923">issues.joomla.org/tracker/joomla-cms/27923</a>.</sub>

**Comment by SharkyKZ** [comment]
@Twincarb I think you can mark test as successful.

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 0e2e755e9c196d025afbe24e7ca1163160339288<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27923">issues.joomla.org/tracker/joomla-cms/27923</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0e2e755e9c196d025afbe24e7ca1163160339288<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27923">issues.joomla.org/tracker/joomla-cms/27923</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27923">issues.joomla.org/tracker/joomla-cms/27923</a>.</sub>

**Pull request merged**
