### PR TITLE
[4.0] Capitalize first word only

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
It is a sentence. Capitalize the first word only.

### Testing Instructions
Code review.
See the two related strings before it.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 546a2bda5f12cce3c4ae595e30be6292be88f242<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32886">issues.joomla.org/tracker/joomla-cms/32886</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 546a2bda5f12cce3c4ae595e30be6292be88f242<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32886">issues.joomla.org/tracker/joomla-cms/32886</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 546a2bda5f12cce3c4ae595e30be6292be88f242<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32886">issues.joomla.org/tracker/joomla-cms/32886</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32886">issues.joomla.org/tracker/joomla-cms/32886</a>.</sub>

**Pull request merged**
