### PR TITLE
[com_tags] Add search tooltip

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to add the search tooltip and element label (accessibility) in com_tags.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Go to Components -> Tags, check the tooltip in the search field.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :red_circle: unsuccessfully on 226daf514dd64eef917b530a7063235e13bfb639<br /><br />Hmmm strange that nothing before (not even the "Search") neither after the patch...
maybe a conflict on my localhost<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10180">issues.joomla.org/joomla-cms/10180</a>.</sub>

**Comment by andrepereiradasilva** [comment]
sorry, my bad. please test now

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on c0cd86cadc635065743d01cb2de6177b7d0759a8<br /><br />Thanks and sorry for having not checked the diff... BBQ was waiting :wink: 

All fine now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10180">issues.joomla.org/joomla-cms/10180</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c0cd86cadc635065743d01cb2de6177b7d0759a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10180">issues.joomla.org/joomla-cms/10180</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10180">issues.joomla.org/joomla-cms/10180</a>.</sub>

**Pull request merged**
