### PR TITLE
Joomla 4.0: Removing deprecated code from JViewLegacy

### PR DESCRIPTION
**Pull request by Hackwar**
Regardless of what we do with JView, we should finally remove the deprecated code from JViewLegacy, that has been sitting there deprecated since 1.6...

### CODE REVIEW

**Comment by Hackwar** [comment]
I've decided to move the JView* classes from /libraries/legacy to /libraries/cms, too.

**Comment by Hackwar** [comment]
I have no idea why the JApplicationWeb tests now fail with this latest change. (moving the tests into the other folder.)

**Comment by mbabker** [comment]
My guess is something in the moved tests that changes global state and doesn't reset things.  A far too common problem with our test suite.

**Comment by mbabker** [comment]
https://github.com/Hackwar/joomla-cms/blob/4d629f86c8715fd9760cbdb48cd9147f0f0ccb11/tests/unit/suites/libraries/cms/view/JViewLegacyTest.php#L429-L431

Probably those lines.  Instead of restoring the state of `$_SERVER` after the test it's just setting the values if not previously set.

**Comment by Hackwar** [comment]
Funny, the issue is JPATH_COMPONENT. If it is defined, it fails, if it is not, the JApplicationWeb works fine. Of course JViewLegacy then fails spectacularly... I have no idea what is depending on JPATH_COMPONENT not being defined.

**Comment by mbabker** [comment]
`JViewLegacy` only needs `JPATH_COMPONENT` if it's instantiated without a `base_path` parameter in the config array.  So change the tests to inject that and you can get around needing the constant?

**Comment by Hackwar** [comment]
Unfortunately doesn't work. It seems as if it is not the issue of the JPATH_COMPONENT constant, but something that is executed in the tests afterwards. I simply commented out the define() for JPATH_COMPONENT and that threw a bunch of errors and actually stopped the JViewLegacy tests. Now I've rewritten those and don't get the JPATH_COMPONENT errors, but get the other 2 failures again.

**Comment by Hackwar** [comment]
Found the issue. JUri::base() throws this of...

**Comment by Hackwar** [comment]
Fixed it. JUri::reset() in tearDown() fixes this.

**Comment by wilsonge** [comment]
For those unit tests fixes can we put them into staging? Because that's just good practice anyhow. I'm happy to merge a PR with just those changes in on review

**Comment by Hackwar** [comment]
The unittests in 3.7 are somehow funky, so to be honest, I don't really want to mess around there...

**Comment by wilsonge** [comment]
It's fine. I just directly cherry-picked it into staging :p https://github.com/joomla/joomla-cms/commit/0724b0d9ab5d4557e3e2fa1b6fc8cdd79442d4db

**Comment by wilsonge** [comment]
I've also done a PR for the newsfeed change to staging https://github.com/joomla/joomla-cms/pull/12296

I'm trying to keep things in sync as best I can for my sanity in the future when i'm solving conflicts xD

**Comment by mbabker** [comment]
Then you shoulda started from the 3.7 branch.  My office will have a drink
in memory of your sanity when you have to merge that.

**Pull request merged**
