### PR TITLE
Implementing "No Matching Results" in Contacts modal

### PR DESCRIPTION
**Pull request by brianteeman**
When creating a menu item of type single contact  the list of contacts is displayed in a modal window.
When filtering and if no results, the display is just empty instead of the usual message "No Matching Results"
This patch is just implementing the message in the modal when necessary.

Thanks t0 @infograf768 for the code

### CODE REVIEW

**Comment by infograf768** [comment]
OK here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7232">issues.joomla.org/joomla-cms/7232</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you, @brianteeman! I will reset the failed jobs in Travis now, once they were successful checked I will set the state "RTC".

**Comment by zero-24** [comment]
RTC to match the status on github
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7232">issues.joomla.org/joomla-cms/7232</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @brianteeman! Merged.

**Pull request closed without merging**
