### PR TITLE
[com_content] Fix modal article edit & simplify modal layout

### PR DESCRIPTION
**Pull request by cyrez**
To reproduce issue before applying this patch, create a **new menu item**, select **type "single article"**, and **save** this menu item.
Then, click **"Edit"** button to edit the article from the menu item.

**Current behavior (before patch) :**
- Open the article edition page (modal) in a new browser window or tab (!!!), and NOT inside a Bootstrap modal :-|

capture d ecran 2016-05-07 a 22 43 12
capture d ecran 2016-05-07 a 22 43 26

**Expected behavior :**
- Open the article edition page inside a modal, with <code>close</code> and <code>save & close</code> buttons
- Same behavior as current one for Edition of modules from the menu item (in Module Assignment tab) when clicking on the name of each modules.

capture d ecran 2016-05-07 a 22 45 08
#### Summary of Changes
- Open the Article Edition modal inside a bootstrap modal
- Simplify the modal.php view (loading directly the edit.php view)
- Change in edit.php to not load Articles Association tab when inside a modal (previous behavior and expected one).
- Fix tooltip placement inside modal-body loading an iframe
#### Testing Instructions
- Test in Menus > Menu Item type "single article" > Edit article to open the modal to edit article
- Test in Articles > Article Edition > Associations > Select an associated article, save and then try to edit this article associated with Edit button (should open the modal).

**If it's ok for this one (modal edit article) i will do the same for all menu item type "single item" : Newsfeed modal (menu item type single newsfeed), Contact modal (type single contact), etc...**

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
> Before testing, i wonder if i should remove the existed "clear" button from the article.php form field, as this one is not used, and not needed because when creating a menu item type single article, this input could not be empty (so clear button makes no sense, and in fact the code for this button is not needed and not used...)

Don't know which button you're talking.

it's a pitty https://github.com/joomla/joomla-cms/pull/10070 is not merged yet. Would be perfect to have a full size modal for this "Edit".

> Test in Menus > Menu Item type "single article" > Edit article to open the modal to edit article
Ok

> Test in Articles > Article Edition > Associations > Select an associated article, save and then try to edit this article associated with Edit button (should open the modal).

Js error when creating/editing article.

Used latest staging

**Comment by andrepereiradasilva** [comment]
The aim of this PR is great.

If you are in the mdoe after this chnages, it would be great to have a "New" article button in the single article menu item :)

**Comment by JoomliC** [comment]
@andrepereiradasilva 

> Don't know which button you're talking.

Don't worry, just edited the PR description... A stupid comment, as "clear" button is needed in Article associated edition, and so, all is good about this!

I have update the PR, due to a few possible issue with Association Article.
Did many tests, and seems working good.

> If you are in the mood after this changes, it would be great to have a "New" article button in the single article menu item :)

Yes, exactly what i thought when working to fix modal item edit in menu edition: a new button.
The first step, with this PR, and with a few others if this one is ok, is to fix what exists first (but the possibility to directly create an article from the menu and/or when adding an associated article could be nice... not yet tested if could work well).

So i will say that now this PR is ready for testing !

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 99115df18df65fe9943888f54d5a0956226f5586<br /><br />Tested successfully, works as described. Nice feature.

One remark: if you accidentally click outside of the modal window, while editing an article, the modal closes directly and all your changes are gone.
Users have to be aware of that.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10292">issues.joomla.org/joomla-cms/10292</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 99115df18df65fe9943888f54d5a0956226f5586<br /><br />This works as described.

I make the same comment as @BurtNL and also. It should exist a "Save" button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10292">issues.joomla.org/joomla-cms/10292</a>.</sub>

**Comment by andrepereiradasilva** [comment]
oh and by the way, when "Save & Close" a meesage saying that it was been saved would be used full to.

**Comment by JoomliC** [comment]
Thank you for testing @andrepereiradasilva and @BurtNL !
The aim of this PR is mainly to fix the edit modal not openning in a modal, and fix and simplify existing code.
Of course, your comments are welcome! I agree with you that a few improvements could be done for this feature ;-)

> It should exist a "Save" button

I did this one as it is for module edition (in menu edit, go to "Module Assignment" tab, and click on one module name : this one opens in a modal, and did the same here with article).
So future improvements will be of course possible ;-)

**Comment by JoomliC** [comment]
@andrepereiradasilva and @BurtNL Sorry, tests are reset ;-)

I have added 2 options ot BS modal, to disable close by accident. Fix this : 

> One remark: if you accidentally click outside of the modal window, while editing an article, the modal closes directly and all your changes are gone.
Users have to be aware of that.

;-)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3f1cea615522e75958e4db9de52f67e90ad7711c<br /><br />test just the modal part and now it doesn't close unless we save & close or close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10292">issues.joomla.org/joomla-cms/10292</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 3f1cea615522e75958e4db9de52f67e90ad7711c<br /><br />Tested successfully, modal can now only be closed via the buttons. Great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10292">issues.joomla.org/joomla-cms/10292</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10292">issues.joomla.org/joomla-cms/10292</a>.</sub>

**Comment by andrepereiradasilva** [comment]
3.6 label?

**Pull request merged**
