### PR TITLE
Whos online module

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Move Filter groups option from the advanced tab to the main tab
Add missing cache time option to the advanced tab

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on db42c4a4f549365e9ef99807bb3717384facd368<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11379">issues.joomla.org/joomla-cms/11379</a>.</sub>

**Comment by hardiktailored** [comment]
I have tested this item :red_circle: unsuccessfully on db42c4a4f549365e9ef99807bb3717384facd368<br /><br />Filter groups option not added as main tab.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11379">issues.joomla.org/joomla-cms/11379</a>.</sub>

**Comment by hardiktailored** [comment]
See result:
screen shot 2016-08-01 at 08 55 29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11379">issues.joomla.org/joomla-cms/11379</a>.</sub>

**Comment by hardiktailored** [comment]
I have tested this item :white_check_mark: successfully on db42c4a4f549365e9ef99807bb3717384facd368<br /><br />I can see on the main content tab detail page. I thought you added new tab. Works perfect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11379">issues.joomla.org/joomla-cms/11379</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11379">issues.joomla.org/joomla-cms/11379</a>.</sub>

**Pull request merged**
