### PR TITLE
[4.1] Fix the update failure on Windows

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36567 .

### Summary of Changes
Upgrading from 4.0.x to 4.1 fails due to some FS inconsistencies

### Documentation Changes Required

@richard67

### CODE REVIEW

**Comment by wilsonge** [comment]
Isn't just you need to wrap the function call in realpath for Folder::exists. because realpath will do the path conversion for slashes (see the second example here https://www.php.net/manual/en/function.realpath.php)

**Comment by wilsonge** [comment]
if your using real_path my point is you shouldn't need the str_replace on top of that

**Comment by dgrammatiko** [comment]
> if your using real_path my point is you shouldn't need the str_replace on top of that

I don't have a windows PC so I try things blindly here. Will remove them

**Comment by brianteeman** [comment]
its nothing to do with the file path as expained in the other issue

**Pull request closed without merging**
