### PR TITLE
Use the new wrapper classes in the filesystem package

### PR DESCRIPTION
**Pull request by mbabker**
From our testing sprint this week, we've taken some initial steps to modernize some of our architecture and focus on replacing static methods as able (this will be blogged about more thoroughly in the coming weeks).  To do so without backward compatibility breaks, we've introduced several wrapper classes which are object based and enable developers to utilize these to work with what will be the object based API in a later major release.

This PR demonstrates how the wrappers can be used internally by using the newly created wrappers for the Filesystem package within its classes.  In conjunction with https://github.com/joomla/joomla-cms/pull/4717 this demonstrates how we can begin modernizing the code in phased steps without introducing larger B/C breaks between major releases by providing a compatibility layer in our current releases.
### Testing Instructions
- Apply the patch
- Perform actions in the user interface that interact with the filesystem (the media manager and extension manager are great places to test from)
- Ensure filesystem management still works

### CODE REVIEW

**Comment by mbabker** [comment]
:shrug:

**Comment by brianteeman** [comment]
Was this closed because of?

**Comment by mbabker** [comment]
Lack of interest, to be able to delete the 3.4-dev branch

**Comment by javigomez** [comment]
But it can be recreated against staging, isn't it?

**Comment by Kubik-Rubik** [comment]
@mbabker Can you do a new PR against staging, please?

**Comment by mbabker** [comment]
See #5849

**Pull request closed without merging**
