### PR TITLE
[4.3] RSS Feed title

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40123 .

### Summary of Changes
 add a meaningful title to the feed by using the document page title

### Testing Instructions
Create the following menu items 
Blog Category
Featured Articles
Tags (List All)
Contacts (list)

Add page titles to some of them

### Actual result BEFORE applying this Pull Request
If you view the source you will find the following in the header
```
<link href="seite.feed?type=rss" rel="alternate" type="application/rss+xml" title="RSS 2.0">
<link href="seite.feed?type=atom" rel="alternate" type="application/atom+xml" title="Atom 1.0">
```

### Expected result AFTER applying this Pull Request
```
<link href="seite.feed?type=rss" rel="alternate" type="application/rss+xml" title="xxxxxxxxxx">
<link href="seite.feed?type=atom" rel="alternate" type="application/atom+xml" title="xxxxxxxx">
```

Where xxxxxxxx is the page title according to the settings so it is the same as the browser page title eg

<link href="seite.feed?type=rss" rel="alternate" type="application/rss+xml" title="sitename - menuitem">
<link href="seite.feed?type=atom" rel="alternate" type="application/atom+xml" title="sitename - menuitem">

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 630886d68b7a7e937aa464b9a2f8b8833a59d399<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40168">issues.joomla.org/tracker/joomla-cms/40168</a>.</sub>

**Comment by Quy** [comment]
Should escape title just in case it contains an `"`.
`<link href="/joomla-cms-4.3-dev/index.php/all-tags?format=feed&amp;type=rss" rel="alternate" type="application/rss+xml" title="All "Tags"">`

**Comment by SharkyKZ** [comment]
> Should escape title just in case it contains an `"`. `<link href="/joomla-cms-4.3-dev/index.php/all-tags?format=feed&amp;type=rss" rel="alternate" type="application/rss+xml" title="All "Tags"">`

This should be done in the renderer and not here.

**Comment by brianteeman** [comment]
and that would be where?

**Comment by Mich-es** [comment]
I have tested this item :white_check_mark: successfully on 6137e4d2e37040fad97d583ad7d642858f5eeb1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40168">issues.joomla.org/tracker/joomla-cms/40168</a>.</sub>

**Comment by PjotrClaas** [comment]
I have tested this item :white_check_mark: successfully on 6137e4d2e37040fad97d583ad7d642858f5eeb1d<br /><br />Tested successfully! 6137e4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40168">issues.joomla.org/tracker/joomla-cms/40168</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40168">issues.joomla.org/tracker/joomla-cms/40168</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Comment by brianteeman** [comment]
Thi

**Pull request merged**
