### PR TITLE
Rename #__history to #__content_history

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Rename table `#__history` to `#__content_history`.

Table name `#__history` is too common, besides this table is closely related to content.

Original Joomla 3 table `#__ucm_history` was renamed to `#__history` and it's really weird.

Let's add more logic into table names while it's not too late for Joomla 4.

### Testing Instructions

Install Joomla 4 beta (or update core files in existing installation). Ensure that content history works.

### Actual result BEFORE applying this Pull Request

Table `#__history` exists.

### Expected result AFTER applying this Pull Request

Table `#__history` renamed to `#__content_history`.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by HLeithner** [comment]
These changes would suggest that the table belongs to com_content, but this is not the case as every component can use the versioning feature.

**Comment by 1252spike** [comment]
Just a thought: Seeing as we call the function "Versions" should this not be called #__versions_history. I'm sure there's a good reason why not, but just a thought.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30766">issues.joomla.org/tracker/joomla-cms/30766</a>.</sub>

**Comment by Denitz** [comment]
@HLeithner `#__content_types` is also used everywhere but it is.

@1252spike  Nope, it's used in com_contenthistory, the model name is ContentHistory, the word version is frustrating.

**Comment by HLeithner** [comment]
tbh our complete database structure would need a face lift or more @alikon and @richard67 are pretty much in favor for this but renaming something which is not really wrong and make it wrong isn't a good option ymmv

**Comment by richard67** [comment]
@HLeithner I'm not in favour of this.

**Comment by HLeithner** [comment]
@richard67 thought you would like to restructure the database a bit, sorry if I misunderstood this

**Comment by Fedik** [comment]
@Denitz do you know a rule "do not touch if it works"? :)

There no much sense in the changes, even if new name sounds better.

**Comment by brianteeman** [comment]
Alpha5 is really not the time to even think about changing core table names

**Comment by richard67** [comment]
> Alpha5 is really not the time to even think about changing core table names

If it was **Alpha**5 and not **Beta**5 I would maybe be ok with it ;-)

**Comment by ThomasFinnern** [comment]
I have tested this item :red_circle: unsuccessfully on d7daae75aea1b3855428dcf9423a1c1c4f188dd0<br /><br />Applied patch, Result: "#_history" gone, "#__content_history" exists 
Point of concern: Database update structure issued with result error: "missing #_history table"

Tested article history was successful. Changed version version info could be seen in table "#_content_history"
        <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30766">issues.joomla.org/tracker/joomla-cms/30766</a>.</sub>

**Comment by ThomasFinnern** [comment]
Applied patch, Result: "#_history" gone, "#__content_history" exists 
Point of concern: Database update structure issued with result error: "missing #_history table"

Tested article history was successful. Changed version version info could be seen in table "#_content_history"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30766">issues.joomla.org/tracker/joomla-cms/30766</a>.</sub>

**Pull request closed without merging**
