### PR TITLE
[5.0] Swap fields for mass mail

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
This PR sets the group select field in user mass mail screen befor the checkbox for recursion. 
Why?
Selection recursion before knowing the group tree "makes me think". 

### Testing Instructions
Check the user mass mail view before and after patch.

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/Help310:Users_Mass_Mail_Users/de
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
>  No documentation changes for docs.joomla.org needed

New screenshot is needed, see link https://docs.joomla.org/Help310:Users_Mass_Mail_Users

**Comment by brianteeman** [comment]
I assume that you actually meant this url which is for Joomla 4
https://docs.joomla.org/Help4.x:Mass_Mail_Users

**Comment by sandewt** [comment]
> I assume that you actually meant this url which is for Joomla 4

Oops, correct.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on d54346e97e102d73307601274025f2d608da8a49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40500">issues.joomla.org/tracker/joomla-cms/40500</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d54346e97e102d73307601274025f2d608da8a49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40500">issues.joomla.org/tracker/joomla-cms/40500</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40500">issues.joomla.org/tracker/joomla-cms/40500</a>.</sub>

**Comment by brianteeman** [comment]
Not sure why this has been bumped to 5.0 but the rebase hasnt worked

**Comment by chmst** [comment]
4.4 should not have new features. I close here and open a fresh PR for 5.0

**Comment by brianteeman** [comment]
> 4.4 should not have new features. I close here and open a fresh PR for 5.0

I fail to see how changing the order of two fields is a new feature.

**Pull request closed without merging**
