### PR TITLE
[4.0] Enable missed minicolors style, fix for #28216

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #28216 .

### Summary of Changes
Enable minicolors style, missed since #27884

### Testing Instructions
look #28216 for detail

### Expected result

a color field works

### Actual result

a color field not work

### CODE REVIEW

**Comment by N6REJ** [comment]
Please provide detailed testing instructions.  There are at least 3 different kinds of color fields now.

**Comment by brianteeman** [comment]
Go to the admin template styles and make sure the 4 fields all have color pickers

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d5cc0c607520637375d1310db9e6e44c620812e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28271">issues.joomla.org/tracker/joomla-cms/28271</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d5cc0c607520637375d1310db9e6e44c620812e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28271">issues.joomla.org/tracker/joomla-cms/28271</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28271">issues.joomla.org/tracker/joomla-cms/28271</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by N6REJ** [comment]
that doesn't test whether the color field is working properly now or not but apparently it doesn't matter as this was fast tracked.

**Pull request merged**
