### PR TITLE
[4.0]com_contact xml codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
Just codestyle changes - tabs and new lines

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cbddf0dbf60894549920752219de60f910dbf929<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34033">issues.joomla.org/tracker/joomla-cms/34033</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cbddf0dbf60894549920752219de60f910dbf929<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34033">issues.joomla.org/tracker/joomla-cms/34033</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34033">issues.joomla.org/tracker/joomla-cms/34033</a>.</sub>

**Comment by richard67** [comment]
Grr stubborn issue tracker ... RTC I said.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34033">issues.joomla.org/tracker/joomla-cms/34033</a>.</sub>

**Pull request merged**
