### PR TITLE
Codemirror updated to 5.33.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes
http://codemirror.net/doc/releases.html

### Testing Instructions
Use CodeMirror

### Expected result
It should work as usual.

### Actual result
It works. 

### Documentation Changes Required
No

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
The check is wrong. This does not fail.

**Comment by brianteeman** [comment]
could you update this to 5.33 please and then i can test it

**Comment by okonomiyaki3000** [comment]
And don't forget these other fine CodeMirror PRs:

#12542
#17042
#18881

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 79008a88c294c270530f12ca25a1215ad9c5a0e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18880">issues.joomla.org/tracker/joomla-cms/18880</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Really, still? These usually merge right away...

**Comment by okonomiyaki3000** [comment]
Thanks!

**Pull request merged**
