### PR TITLE
[5] fix Deprecated: Creation of dynamic property

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #41553 .

### Summary of Changes
declared

### Testing Instructions
with php 8.2
set error report to maximum
go to Joomla Updatde
and / or php cli/joomla.php core:check-updates

### Actual result BEFORE applying this Pull Request

Deprecated Creation of dynamic property ....

### Expected result AFTER applying this Pull Request

no more Deprecated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on 3d9d8f18e06f0b5679e94c9d28d2ea5940f5216c<br /><br />Tested in Joomla 5.0.1 using PHP 8.2.13 and 8.3.0 in Wampserver 3.3.2 and Windows 11. 
The CLI test using PHP 8.2.11 succeeded. 

The backend tests had only partial success: 'Check for Updates' and 'Upload & Update' work ok but 'Reinstall Joomla! core files' reports an error: "0 Cannot access protected property Joomla\CMS\Updater\Update::$sha256"

Call Stack
#	Function	Location
1	()	JROOT\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php:473
2	Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->isChecksumValid()	JROOT\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php:448
3	Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->download()	JROOT\administrator\components\com_joomlaupdate\src\Controller\UpdateController.php:59
4	Joomla\Component\Joomlaupdate\Administrator\Controller\UpdateController->download()	JROOT\libraries\src\MVC\Controller\BaseController.php:730
5	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143
6	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT\libraries\src\Component\ComponentHelper.php:361
7	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT\libraries\src\Application\AdministratorApplication.php:150
8	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT\libraries\src\Application\AdministratorApplication.php:195
9	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT\libraries\src\Application\CMSApplication.php:306
10	Joomla\CMS\Application\CMSApplication->execute()	JROOT\administrator\includes\app.php:58
11	require_once()	JROOT\administrator\index.php:32

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42429">issues.joomla.org/tracker/joomla-cms/42429</a>.</sub>

**Comment by alikon** [comment]
when you have time, should be fixed the Reinstall Joomla

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 4608c4a31831c3b95da921cfa5f240d9c78d39e7<br /><br />Tested successfully in Joomla 5.0.1 on Wampserver 3.3.2 using PHP 8.3.0. All options in Joomla Update worked all right in Joomla 5.0.1.

Noticed possible regression: after I updated the test site to 5.0.2-dev from 2 December, the option to reinstall Joomla core files was not presented at all.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42429">issues.joomla.org/tracker/joomla-cms/42429</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 4608c4a31831c3b95da921cfa5f240d9c78d39e7<br /><br />With the changes applied I do not have the mentioned issue anymore<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42429">issues.joomla.org/tracker/joomla-cms/42429</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42429">issues.joomla.org/tracker/joomla-cms/42429</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by alikon** [comment]
this pr has been merged in 5.0.2  so it is not present in 5.0.1

**Comment by ChristineWk** [comment]
> this pr has been merged in 5.0.2 so it is not present in 5.0.1

Yes, pr has been merged in 5.0.2, How to solve this now - what actions are required now?
Thank you.

**Comment by ChristineWk** [comment]
> you can apply this change to your 5.0.1

I will inform user about. Thank you.

**Pull request merged**
