### PR TITLE
Implementing "No Matching Results" in Articles modal

### PR DESCRIPTION
**Pull request by infograf768**
When editing an article and clicking on the Article button to insert an article link in the edited article, the list of articles is displayed in a modal wndow.
When filtering and if no results, the display is just empty instead of the usual message "No Matching Results"

This patch is just implementing the message in the modal when necessary.

### CODE REVIEW

**Comment by brianteeman** [comment]
Confirmed issue and confirmed fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7231">issues.joomla.org/joomla-cms/7231</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@infograf768 Thank you, works as described. Could you please move the code one indent to the right within the else statement (<table.... </table>)? 
@brianteeman Please also for your PRs, thanks!

**Comment by brianteeman** [comment]
Not 100% sure where you want the indent - tried with #7236 - was that what
you meant?

If not please do a PR against one of my branches

On 23 June 2015 at 11:22, Viktor Vogel <notifications@github.com> wrote:

> @infograf768 <https://github.com/infograf768> Thank you, works as
> described. Could you please move the code one indent to the right within
> the else statement ()?
> @brianteeman <https://github.com/brianteeman> Please also for your PRs,
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7231#issuecomment-114432511>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
@brianteeman I mean the code style. Just move the whole code section within the else statement one indent to the right.

**Comment by brianteeman** [comment]
Please check #7236

On 23 June 2015 at 11:31, Viktor Vogel <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I mean the code style. Just
> move the whole code section within the else statement one indent to the
> right.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7231#issuecomment-114437998>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
@Kubik-Rubik 
Indent corrected and as well for https://github.com/joomla/joomla-cms/pull/7244

**Comment by Kubik-Rubik** [comment]
@infograf768 Thank you! The closing tag for enforeach is one indent too far right but it's okay. If you have the time, you can still fix it.

I will run the Travis job once again and then set the PR to RTC. Thanks again!

**Comment by zero-24** [comment]
RTC to match the status on github
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7231">issues.joomla.org/joomla-cms/7231</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768! Merged.

**Pull request closed without merging**
