### PR TITLE
Drop index if exists.

### PR DESCRIPTION
**Pull request by twister65**
### Summary of Changes
Add the parameter `IF EXISTS` after `DROP INDEX`.

### Testing Instructions
Update Joomla! from version 3.9.15 or older.

### Expected result
No error.

### Actual result
The update with postgresql throws an error.

### CODE REVIEW

**Comment by richard67** [comment]
Hint for testers: For testing this PR you can use the update package built for this PR by our checkin tools (Drone). You can find update packages and at the bottom a cutom update URL at following page: [https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/28902/downloads/31730/](https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/28902/downloads/31730/).

**Comment by richard67** [comment]
@twister65 Your PR looks right to me, and I've just checked that the database checker can handle the "IF EXISTS" for the index. But I can't reproduce the issue without your PR. Just updated a 3.9.15 to 3.9.18 using PostgreSQL 10, and I did not get any SQL error in the logfile or the UI. Can it depend on server settings if I get an error or not? Or does the problem only happen for certain versions, or installations with a certain update history?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4a5ef7f5e026e3218ed563f47f951999d15f21de<br /><br />I couldn't reproduce the issue with updating a 3.9.15 to 3.9.18, but this may depend on the update history of a particular installation.

The change in this PR is correct and makes updating more safe, and I've verified that the database schema checker can handle "DROP INDEX IF EXISTS" for PostgreSQL.

For testing the update with this PR applied I've used the custom update URL for the update package built for this PR by drone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28902">issues.joomla.org/tracker/joomla-cms/28902</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4a5ef7f5e026e3218ed563f47f951999d15f21de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28902">issues.joomla.org/tracker/joomla-cms/28902</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28902">issues.joomla.org/tracker/joomla-cms/28902</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
