### PR TITLE
[4.0] Fix tooltip cutoff

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue  #25282.

### Summary of Changes
Remove `.btn-group` that is styling of series of  buttons which does not apply here and affects display of tooltips.

### Testing Instructions
Go to Contents > Site Modules
Hover mouse over icon under Status column.

or 

code review.

### Expected result
Tooltip displays properly.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 4990b835feac36a7291a33a22ef0e6ea30d2ae55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25355">issues.joomla.org/tracker/joomla-cms/25355</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4990b835feac36a7291a33a22ef0e6ea30d2ae55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25355">issues.joomla.org/tracker/joomla-cms/25355</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
