### PR TITLE
fix repeatable.js #14556

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #14556 .

### Summary of Changes
repeatable.js  broken when `<select>` is used, it happens because the chosen.js upgrade.
The patch destroys the chosen for the repeatable field

### Testing Instructions
please see #14556 for detail

### CODE REVIEW

**Comment by Fedik** [comment]
@N6REJ  please test

**Comment by franz-wohlkoenig** [comment]
Tested successfully; can't mark at Issue Tracker

**Comment by N6REJ** [comment]
@test fixes the problem nicely!
image

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Review by dgrammatiko — APPROVED** [review]

**Pull request merged**
