### PR TITLE
[4.x] Fix subform nested sorting

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #36779 .

### Summary of Changes

Detect parent container correctly

### Testing Instructions
Run `npm install` and please follow #36779

### Actual result BEFORE applying this Pull Request
Sorted row jumps around

### Expected result AFTER applying this Pull Request
Sorting works correctly

### Documentation Changes Required
none

### CODE REVIEW

**Comment by n3t** [comment]
I have tested this item ✅ successfully on 4.0.6

Thanks

**Comment by Fedik** [comment]
Please visit this page https://issues.joomla.org/tracker/joomla-cms/36780
And click button:
image

**Comment by n3t** [comment]
I have tested this item :white_check_mark: successfully on edda4f5ba541791cbf1761c24d7a112d87c39762<br /><br />Done, sorry I knew I should do something like this, but was using GitHub and looking for this button there :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36780">issues.joomla.org/tracker/joomla-cms/36780</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on edda4f5ba541791cbf1761c24d7a112d87c39762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36780">issues.joomla.org/tracker/joomla-cms/36780</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36780">issues.joomla.org/tracker/joomla-cms/36780</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
