### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request for Issue # .
PR #38863 introduces a bug if Codemirror is selected as default editor.
Image-002

### Testing Instructions
Set the default editor to Codemirror

### Actual result BEFORE applying this Pull Request
When an article is edited, there is an error when Codemirror is set ad default editor.

Warning: Undefined property: stdClass::$readOnly in C:\wamp64\www\joomlacms\plugins\editors\codemirror\layouts\editors\codemirror\element.php on line 41

### Expected result AFTER applying this Pull Request
The error is the article editor is gone and the changes made in #38863 still work.

### CODE REVIEW

**Comment by richard67** [comment]
Doesn’t isset also cover the check for not null so the check for not null can be removed?

**Comment by RickR2H** [comment]
> Doesn’t isset also cover the check for not null so the check for not null can be removed?

You are right. isset will return true if variable is set and not NULL.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c07eb448c6047bce1dd03ed02e5d77b4d55ecacf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38989">issues.joomla.org/tracker/joomla-cms/38989</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c07eb448c6047bce1dd03ed02e5d77b4d55ecacf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38989">issues.joomla.org/tracker/joomla-cms/38989</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38989">issues.joomla.org/tracker/joomla-cms/38989</a>.</sub>

**Pull request merged**
