### PR TITLE
[4.0]Class breaks switcher

### PR DESCRIPTION
**Pull request by brianteeman**
Removal of the extra class (not present in the css) that breaks the switcher code and results in a double label.

### Before
image

### After
image

Any decision about changing switcher like this which might be deemed to not be true boolean is beyond the scope of this PR

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Given that `switcher-primary` class doesn't exist this PR is fine. But it doesn't solve the root cause. For some reason known only to @dgrammatiko radio field is using class attribute to select a layout instead of using the layout attribute.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on c3913242b80fa5b51795c2a9730bb90ec8fe6ab0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26206">issues.joomla.org/tracker/joomla-cms/26206</a>.</sub>

**Comment by brianteeman** [comment]
@SharkyKZ please raise that as its own issue

**Comment by dgrammatiko** [comment]
@SharkyKZ I think you should tag @C-Lodder not me for the switcher

**Comment by SharkyKZ** [comment]
@dgrammatiko No, it's coming from #19296. Anyways, here's PR #26214 to remove class-based logic.

**Comment by C-Lodder** [comment]
Wasn't the switch rewritten to drop the custom element?

**Comment by brianteeman** [comment]
Yes and its nothing to do with this PR

**Comment by wilsonge** [comment]
OK if the extra class here doesn't exist why are we getting the double label (this "fix" is clearly not wrong - but suggests there might also be a css issue in the switcher field we need to fix if extra classes are causing styling issues that is being revealed here).

**Comment by dgrammatiko** [comment]
@wilsonge hint: check the regex that switches the field behaviour

**Comment by SharkyKZ** [comment]
It's coming from here:

https://github.com/joomla/joomla-cms/blob/27e4d2891c75abfab8c9835551b977f78ff41928/libraries/src/Form/FormField.php#L952

Why is switcher-specific code included in this class is beyond me. I proposed to remove this along with class-based layout assignment.

**Comment by dgrammatiko** [comment]
> Why is switcher-specific code included in this class is beyond me.

Because it has it's own label

**Comment by SharkyKZ** [comment]
@dgrammatiko That doesn't explain why something specific to `Joomla\CMS\Form\Field\RadioField` is handled in `Joomla\CMS\Form\FormField`.

**Comment by dgrammatiko** [comment]
@SharkyKZ I will agree, this leak in the parent class is unacceptable. FWIW this new css-only implementation has few more flaws, one is that it broke the layouts comparison but most importantly the fact that it doesn't provide any meaningful API for DEVs to use it (meaning you have to implement your own logic)
But hey, it is javascript free...

**Comment by brianteeman** [comment]
If only it had been tested

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/issues/25323#issuecomment-506254222

**Comment by C-Lodder** [comment]
If I rightly remember, the logic was in the layout when I first added the switcher. From then on, I did not follow the code changes, so I'm the wrong person to be tagging in this

**Comment by dgrammatiko** [comment]
FWIW @SharkyKZ wrongly blames me for this code as it was there before https://github.com/joomla/joomla-cms/pull/19296 as anyone can see:
https://github.com/joomla/joomla-cms/pull/19296/files#diff-5672706c28da6ae7d160c2c45b37d279L57

All I did in https://github.com/joomla/joomla-cms/pull/19296 was to separate the layouts, the logic for the class was already there...

I'm happy to take the blame on any of the code I introduced but it's unfair to take the blame for other peoples code

**Comment by brianteeman** [comment]
All of these comments are interesting but completely off topic. This PR is about removing a class that does not exist and whose presence is breaking the layout. Anything else should be dealt with in its own issue

**Comment by dgrammatiko** [comment]
> but completely off topic

Sorry , no, @SharkyKZ is right the root of this bug is that If statement which expects only ONE class named `switcher`. The extra classes you are removing in this PR is a bandaid not a proper solution

**Comment by brianteeman** [comment]
and that can be looked at in its own pull request. removing the extra unused class will have to be removed anyway

**Comment by wilsonge** [comment]
Structural fix here https://github.com/joomla/joomla-cms/pull/26423 

Once that is merged then we should remove the redundant classes here (leaving them in until that is merged allows easy testing)

**Comment by pravinTek** [comment]
I have tested this item :white_check_mark: successfully on 7902fe5fa3ad07a41862ab3dea7a7bee9736ccb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26206">issues.joomla.org/tracker/joomla-cms/26206</a>.</sub>

**Comment by tushar33** [comment]
I have tested this item :white_check_mark: successfully on 7902fe5fa3ad07a41862ab3dea7a7bee9736ccb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26206">issues.joomla.org/tracker/joomla-cms/26206</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26206">issues.joomla.org/tracker/joomla-cms/26206</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
