### PR TITLE
remove 3.9 files from 4

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue  glip chat
for reference see https://github.com/joomla/joomla-cms/commit/b53599eff0c10ac972f76d26342b67a2e6a50f86

### CODE REVIEW

**Comment by HLeithner** [comment]
Thanks

**Comment by richard67** [comment]
@alikon You have forgotten this one: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/3.9.19-2020-06-01.sql . Can you make a new PR? I will be busy now for a while.

**Comment by richard67** [comment]
@alikon I have time now an am on it. PR comes in a few minutes.

**Comment by richard67** [comment]
PR is #31224 .

**Pull request merged**
