### PR TITLE
[4.0] Re-add the colour state for publish dropdown

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

In Joomla 3, when selecting the state of something via the dropdown (published, unpulishged, trashed), the colour of the dropdown changed depending on the option selected (red/green).

This re-add the JS, providing the same functionality

### Testing Instructions

- Go to Module Manager. Open an existing module or create a new one.
- On the right hand side, switch the **State** and notice the colour change.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7be0611b3dc4e454bdcd4cdc8dd0878bbacf75f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17354">issues.joomla.org/tracker/joomla-cms/17354</a>.</sub>

**Comment by dgrammatiko** [comment]
Not as a core function, please, this is view related (only available in lists), not part of the joomla API!

**Comment by dgrammatiko** [comment]
Also the whole `document.addEventListener` needs to go to the toolbar.js again this is not system API

**Comment by C-Lodder** [comment]
Will continue tomorrow

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 7be0611b3dc4e454bdcd4cdc8dd0878bbacf75f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17354">issues.joomla.org/tracker/joomla-cms/17354</a>.</sub>

**Comment by C-Lodder** [comment]
@dgt41 - JS moved out of core.js

**Comment by dgrammatiko** [comment]
Thanks, fields is the right place, for this!

@wilsonge please merge

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0b6fc9d983cd571acd66184804060d82090ec7e9<br /><br />still good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17354">issues.joomla.org/tracker/joomla-cms/17354</a>.</sub>

**Pull request merged**
