### PR TITLE
[#29248] FrontEnd - Disabling Show Navigation setting does not affect article

### PR DESCRIPTION
**Pull request by zero-24**
### Tracker

http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=29248

Code by Karthikeyan S @skarthik2020
### How to redpoduce

Log into your Joomla 3.0 admin dashboard In the top menu, click Content and then click Article Manager In the list of articles on the page, click the article title that you want to toggle the Show Navigation setting for You will see several tabs above the article, click the Article Options tab Find the setting labeled Show Navigation. Set it to "Hide", and then click "Save" in the top left

When I set the "Show Navigation" setting for a specific article to "Hide", I still see the navigational buttons on the page.

### CODE REVIEW

**Comment by patjun** [comment]
Tested. Works fine.

**Comment by jehacgn** [comment]
tested- it works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5016">issues.joomla.org/joomla-cms/5016</a>.</sub>

**Comment by tecpromotion** [comment]
test confirmed. works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5016">issues.joomla.org/joomla-cms/5016</a>.</sub>

**Comment by aruttkamp** [comment]
tested - ok

**Comment by Neppert** [comment]
tested. works ok.

**Comment by aruttkamp** [comment]
tested - ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5016">issues.joomla.org/joomla-cms/5016</a>.</sub>

**Comment by brianteeman** [comment]
Multiple good tests - thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5016">issues.joomla.org/joomla-cms/5016</a>.</sub>

**Comment by mbabker** [comment]
Merged to staging

**Comment by phproberto** [comment]
I just updated my site to v3.4.1 and articles aren't show anymore. Reverting this commit brings them back. Another user reported me the same issue so I think something is wrong in this patch.

**Comment by phproberto** [comment]
Forget it. It was a third part plugin replacing parameters...

**Pull request closed without merging**
