### PR TITLE
[4.2] Code style for cache plugin #36042

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Code style for changes in #36042

### Testing Instructions

Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 94b8140ceb5609a3cc8487c854c70637bead9598<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37820">issues.joomla.org/tracker/joomla-cms/37820</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 94b8140ceb5609a3cc8487c854c70637bead9598<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37820">issues.joomla.org/tracker/joomla-cms/37820</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37820">issues.joomla.org/tracker/joomla-cms/37820</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
