### PR TITLE
Use joomla's constants instead of JPATH_ROOT in the namespace mapper

### PR DESCRIPTION
**Pull request by wilsonge**
Use `JPATH_SITE`, `JPATH_ADMINISTRATOR`, `JPATH_API` and `JPATH_PLUGINS` for the locations instead of the `JPATH_ROOT`. This is better for people placing things in custom locations and also reads a bit nicer:

```
'Joomla\\Component\\Content\\Site\\' => [JPATH_SITE . '/components/com_content/'],
'Joomla\\Component\\Content\\Api\\' => [JPATH_API . '/components/com_content/'],
'Joomla\\Component\\Content\\Administrator\\' => [JPATH_ADMINISTRATOR . '/components/com_content/'],
``` 

To test. Remove `libraries/autoload_psr4.php` and let it be regenerated with the new paths. Ensure nothing breaks

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Site modules now have `JPATH_ADMINISTRATOR` path, e.g.

	'Joomla\\Module\\ArticlesArchive\\Site\\' => [JPATH_ADMINISTRATOR . '/modules/mod_articles_archive/'],

**Comment by wilsonge** [comment]
@SharkyKZ nice spot! missed that. think i've fixed this (although in the office right now so unable to test this - please can you give it a go?)

**Comment by richard67** [comment]
Looks good to me:
Unbenannt
Unbenannt_2

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e2e112cc6a493bc38b13f695103d556a7c69ffc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25153">issues.joomla.org/tracker/joomla-cms/25153</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Any idea why unit tests fail? To me it seems not to be related to this PR.

**Comment by wilsonge** [comment]
Need to debug. I re-ran it and it's reliably failing. So my guess is I've broken it somewhere :)

**Comment by richard67** [comment]
@wilsonge Maybe the old wrong double slash which you removed in the last 3 lines for the plugins (see also 2nd screenshot above)? But that would be strange.

**Comment by wilsonge** [comment]
Fixed it. Apparently I messed up the path to the api directory in the installer application 🤦‍♂ . I guess this is why we have tests :)

**Comment by richard67** [comment]
Looks good now:
Unbenannt

Pity that I did not see that in my previous diff.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 96ad172bb348cd1e40e8226bc168d44898605849<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25153">issues.joomla.org/tracker/joomla-cms/25153</a>.</sub>

**Comment by wilsonge** [comment]
In your previous diff it was correct. You only see it if you do a fresh install of Joomla and the installation app generates the file. in the administrator and site apps it was fine because the constants in the defines files there are correct.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
