### PR TITLE
[4.1] Workflows spacer width breaks layout

### PR DESCRIPTION
**Pull request by brianteeman**
#22213 added a width of 440px to the label on a spacer field

This breaks the layout of the article form when workflows is enabled at certain screen resolutions.

Based on the comments on the initial commit this class is no longer required so by removing it here the article form layout is no longer broken.

This is an scss change to will require npm run build:css to test

Workflows must be enabled else the impacted fields will not be displayed.

### Before
image

### After
image

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on e65d9aefe61cc65e48e4df716a248891e6f10ced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37802">issues.joomla.org/tracker/joomla-cms/37802</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e65d9aefe61cc65e48e4df716a248891e6f10ced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37802">issues.joomla.org/tracker/joomla-cms/37802</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37802">issues.joomla.org/tracker/joomla-cms/37802</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
