### PR TITLE
#8470 fixed help site link per user issue

### PR DESCRIPTION
**Pull request by RonakParmar**
Fixed help site link per user issue.
https://issues.joomla.org/tracker/joomla-cms/8470

### CODE REVIEW

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on e2d9e9e89ec1d4ed7ecb3f718836fc9efdcb8023<br /><br />It works. Thanks @RonakParmar <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by dwarkeshsoni** [comment]
I have tested this item :white_check_mark: successfully on e2d9e9e89ec1d4ed7ecb3f718836fc9efdcb8023<br /><br />It works. Thanks @RonakParmar <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by watchfulli-dev** [comment]
I have tested this item :red_circle: unsuccessfully on e2d9e9e89ec1d4ed7ecb3f718836fc9efdcb8023<br /><br />@test applied the patch but the test fails, when I click refresh button the "Use default" value is gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
I am taking off RTC here because after PR, the value "Use Default" is also displayed in Global Configuration.
screen shot 2015-12-01 at 01 54 45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by dwarkeshsoni** [comment]
I have tested this item :white_check_mark: successfully on e2d9e9e89ec1d4ed7ecb3f718836fc9efdcb8023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
Folks, please read above https://github.com/joomla/joomla-cms/pull/8572#issuecomment-160899621
The tests can't be successful

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e2d9e9e89ec1d4ed7ecb3f718836fc9efdcb8023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
test can't be successful because default should not be proposed in global config...

**Comment by infograf768** [comment]
Also, as the refresh is done from a frontend file, it picks —on a multilingual site— the lang cookie from the last visit of the user in front-end.
Here, I visited Tamil language in front-end (en-GB being used in back-end) 

and I get:
screen shot 2015-12-01 at 17 20 06

2 good reasons therefore to insist on saying that the PR is no good at this time.

**Comment by phproberto** [comment]
I think what we need is that the field has an option to show/hide the default option (enabled by default). 

Something like:

```xml
<field
	name="helpurl"
	type="helpsite"
	label="COM_CONFIG_FIELD_HELP_SERVER_LABEL"
	description="COM_CONFIG_FIELD_HELP_SERVER_DESC" 
	showDefault="false"
/>
```

**Comment by phproberto** [comment]
Please @RonakParmar check:
https://github.com/RonakParmar/joomla-cms/pull/1

**Comment by infograf768** [comment]
Language issue still present after using @phproberto patch

**Comment by phproberto** [comment]
I have modified the PR to create a base profile json controller that will be extended in frontend + backend profile controllers so each application returns its own data in its own language. That should solve the language issue.

**Comment by infograf768** [comment]
@RonakParmar

Please merge @phproberto https://github.com/RonakParmar/joomla-cms/pull/1 as it solves now both issues (no more "Use default" in Global Configuration, and correct language used in back-end when editing user profile when clicking refresh on multilanguage sites.

**Comment by RonakParmar** [comment]
@phproberto Thanks for help to fix this "Use Default" in Global Configuration issue.
I have merged your changes.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9b1b7a44418b2795bfc9b0da2a6721a13dad501f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
One more tester please.

**Comment by dwarkeshsoni** [comment]
I have tested this item :white_check_mark: successfully on 9b1b7a44418b2795bfc9b0da2a6721a13dad501f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by dwarkeshsoni** [comment]
Special thanks to @phproberto for fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by infograf768** [comment]
RTC, Maintainers please add to 3.5.0 beta 2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by pjwiseman** [comment]
I have not tested this item.<br /><br />A "test" result entry "not tested" to try and fix the "Human Test Results" that appear to be using stats from and older SHA.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by pjwiseman** [comment]
I have tested this item :white_check_mark: successfully on 9b1b7a44418b2795bfc9b0da2a6721a13dad501f<br /><br />A "test" result entry "not tested" to try and fix the "Human Test Results" that appear to be using stats from and older SHA.
Second attempt.  Looks like this might be treated as an alteration so it's unlikely to work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by pjwiseman** [comment]
I have tested this item :white_check_mark: successfully on 9b1b7a44418b2795bfc9b0da2a6721a13dad501f<br /><br />This appears to be a new test (though also by me on the same SHA).  Might work to fix the human test results?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by pjwiseman** [comment]
I have not tested this item.<br /><br />Still no joy.  Another entry to record a comment and change to "not tested" by me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8572">issues.joomla.org/joomla-cms/8572</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @RonakParmar / @phproberto and testers. Merged!

**Pull request merged**
