### PR TITLE
[4.4] Quickicon for article categories fails with error permissions on + (add)

### PR DESCRIPTION
**Pull request by obuisard**
Found out while looking at Issue #44089 .

### Summary of Changes

The quickicon + task is missing com_content.

### Testing Instructions

Create a user and assign it to the Manager group.
Login as that user.

Go to the Articles Categories quick icon. Click on +.

image

### Actual result BEFORE applying this Pull Request

Permissions error.

image

### Expected result AFTER applying this Pull Request

No error, you can add a category.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ee5e9772eb20ab36561c8e05158bcfbd4fca9b23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44117">issues.joomla.org/tracker/joomla-cms/44117</a>.</sub>

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on ee5e9772eb20ab36561c8e05158bcfbd4fca9b23<br /><br />I have tested this successfully. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44117">issues.joomla.org/tracker/joomla-cms/44117</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44117">issues.joomla.org/tracker/joomla-cms/44117</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
