### PR TITLE
[4.0] Missing background image

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Make sure that the background image (select-bg-active) can be found

### Testing Instructions
This is as the result of a recent mvoe of the searchtool.scss
Make sure you are on a completely up to date branch and that npm i is also current
Go to any searchtool filter and select anything

### Expected result (after)
Blue background with white dropdown button
image

### Actual result (before)
Blue background only and 404 on the image
image

### CODE REVIEW

**Comment by Quy** [comment]
It is still an issue for RTL.

**Comment by brianteeman** [comment]
I am not surprised this is a bad fix

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 23036c01592e761c16830e375eac559b4e0be02f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by Quy** [comment]
For RTL, the arrow needs to be moved to the left.

**Comment by brianteeman** [comment]
for rtl it needs to load a different image

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 23036c01592e761c16830e375eac559b4e0be02f<br /><br />I found it on /administrator/index.php?option=com_plugins 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by infograf768** [comment]
The rtl image has been created in https://github.com/joomla/joomla-cms/pull/27387

I guess remains to create a new variable and correct the rtl where the ltr variable is used.
Will do if not done here.

**Comment by brianteeman** [comment]
will check tomorrow

**Comment by alikon** [comment]
removed RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by infograf768** [comment]
Hmm, in fact I was mistaken.
We do not have the equivalent of `select-bg-active.svg` for RTL.
We have only the equivalent of `select-bg.svg` as `select-bg-rtl.svg`

------------
**NOTE:** that last one is not present in `installation/template/images/`
````
  [dir=rtl] .custom-select {
    padding: 0.6rem 1rem 0.6rem 4rem;
    background-position-x: 0%;
    background-image: url(../images/select-bg-rtl.svg); }
```
 which makes the class useless in 
`/installation/template/css/template.css` and `template-rtl.css`

But as it looks like RTL has other issues in installation, it's just one of the aspects.

**Comment by brianteeman** [comment]
Just came back to say you were mistaken about the image existing and I see you realised that as well. 

I don't have the time, energy or desire to work on that so either accept this PR as is and create a new one for RTL or not.

**Comment by infograf768** [comment]
Here is the .diff including this PR and the new image
```
diff --git a/administrator/templates/atum/images/select-bg-active-rtl.svg b/administrator/templates/atum/images/select-bg-active-rtl.svg
new file mode 100644
index 0000000..06c38dc
--- /dev/null
+++ b/administrator/templates/atum/images/select-bg-active-rtl.svg
@@ -0,0 +1 @@
+<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1854.54 295" preserveAspectRatio="xMinYMid" width="1854.54" height="295"><path d="m14.47 145.7 6.898 6.899c0.102 0.101 0.199 0.101 0.3 0.101 0.102 0 0.2 0 0.302-0.101l6.898-6.899c0.102-0.1 0.102-0.2 0.102-0.3s0-0.2-0.102-0.3l-0.7-0.7c-0.101-0.1-0.198-0.1-0.3-0.1-0.101 0-0.2 0-0.301 0.1l-5.8 5.8-5.801-5.8c-0.101-0.1-0.199-0.1-0.301-0.1-0.101 0-0.199 0-0.301 0.1l-0.699 0.7c-0.101 0.1-0.101 0.2-0.101 0.3-0.294 0.1-0.194 0.2-0.094 0.3z" fill="#fff"/></svg>
\ No newline at end of file
diff --git a/administrator/templates/atum/scss/_variables.scss b/administrator/templates/atum/scss/_variables.scss
index d638e4f..9b70eee 100644
--- a/administrator/templates/atum/scss/_variables.scss
+++ b/administrator/templates/atum/scss/_variables.scss
@@ -214,5 +214,6 @@
 $custom-select-bg-size:              116rem;
 $custom-select-indicator:            url(../images/select-bg.svg);
-$custom-select-indicator-active:     url(../images/select-bg-active.svg);
+$custom-select-indicator-active:     url(../../../images/select-bg-active.svg);
+$custom-select-indicator-active-rtl: url(../../../images/select-bg-active-rtl.svg);
 $custom-select-background:           $custom-select-indicator no-repeat right center / $custom-select-bg-size; // Used so we can have multiple background elements (e.g., arrow and feedback icon)
 $custom-select-box-shadow:           $atum-box-shadow;
diff --git a/administrator/templates/atum/scss/system/searchtools/searchtools.scss b/administrator/templates/atum/scss/system/searchtools/searchtools.scss
index ba85aad..1f53104 100644
--- a/administrator/templates/atum/scss/system/searchtools/searchtools.scss
+++ b/administrator/templates/atum/scss/system/searchtools/searchtools.scss
@@ -90,4 +90,8 @@
         background: $custom-select-bg $custom-select-indicator-active no-repeat right center;
         background-size: $custom-select-bg-size;
+
+        [dir=rtl] & {
+          background: $custom-select-bg $custom-select-indicator-active-rtl no-repeat left center;
+        }
       }
 
```
Screen Shot 2020-01-29 at 08 48 32

Just let me know if you can modify this PR or not.

**Comment by brianteeman** [comment]
The diff wouldnt apply for some reason but I have applied it manually - thanks

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0c3b8c20511e911a66872a5beaa57ab11a8ce677<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by infograf768** [comment]
@Quy @Fedik 
Please test again, in RTL.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0c3b8c20511e911a66872a5beaa57ab11a8ce677<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27487">issues.joomla.org/tracker/joomla-cms/27487</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
progress - thanks

**Pull request merged**
