### PR TITLE
Update to jqiery mini colors 2.2.4

### PR DESCRIPTION
**Pull request by Bakual**
Updates the jQuery MiniColors library to the latest version (from 2.2.3 to 2.2.4)

### Summary of Changes
Just applying latest patch version

### Testing Instructions
Make sure the color field (eg color picker in the protostar template style) still works as expected.

#### Disclaimer
Work is done by @brianteeman

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 181c76b31d71235d7defce6510016f94ab34a8c0<br /><br />it works but:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14389">issues.joomla.org/tracker/joomla-cms/14389</a>.</sub>

**Comment by infograf768** [comment]
that means not good as is.

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 181c76b31d71235d7defce6510016f94ab34a8c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14389">issues.joomla.org/tracker/joomla-cms/14389</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 181c76b31d71235d7defce6510016f94ab34a8c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14389">issues.joomla.org/tracker/joomla-cms/14389</a>.</sub>

**Comment by Bakual** [comment]
Ah I see, last time when the picker was updated the CSS was left original. Issue is that they rewrote the CSS for Bootstrap support somewhere around their version 2.1.0
When we revert the change in the CSS it works fine again.

**Comment by brianteeman** [comment]
So should I remove our hacks to the css?

**Comment by Bakual** [comment]
We can either revert the CSS to the one in staging, which should work from what I saw.
Or we can try to copy the BS2 CSS rules into their current CSS and see how that works out. But that would mean hacking a 3rd party library to a degree.

**Comment by Bakual** [comment]
I'm closing this PR as @brianteeman is now able to create his own PRs again :smile:

**Pull request closed without merging**
