### PR TITLE
Category Blog multiple tags filter

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to allow seecting multiple tags to a blog category menu item

PR for #13680

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 069058b9f3c948640115fc185afb38d700ed8b15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18234">issues.joomla.org/tracker/joomla-cms/18234</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 069058b9f3c948640115fc185afb38d700ed8b15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18234">issues.joomla.org/tracker/joomla-cms/18234</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by pepperstreet** [comment]
1. ) None - does not work. Previous Filter is sticky.
Please, could someone test the following issue? Another user from the german Joomla facebook-group and me have noticed that the filter can't be reset to "None". I mean, you can set the parameter; save the menuItem and the link URL changes accordingly... **but** the reloaded frontend menuItem does not revert to an un-filtered list?! The filtered results seem to be sticky. I have no clue, why this happens with no extra tag-filter option in the URL. Any other tag filter selection seem to work. Until you try "None" again. 

2. ) Multiple - any/all and child tags
Multiple is a useful addition, but it seem to filter by ANY matches. 
For instance, the "Tagged Items" menu Item has "Item Selection Options", where you choose "Match Type ANY/ALL" and "Child Tags EXCLUDE/INCLUDE". Would it make sense to have these options, too?

Thanks for reading.

**Comment by brianteeman** [comment]
>  but the reloaded frontend menuItem does not revert to an un-filtered list?

Yes if you change the settings then you cant just reload the page as the filter is in the url. You will need to go back to the home page and then to the blog page to see the changes.

**Comment by brianteeman** [comment]
> Multiple is a useful addition, but it seem to filter by ANY matches.
Yes that is correct

> For instance, the "Tagged Items" menu Item has "Item Selection Options", where you choose "Match Type ANY/ALL" and "Child Tags EXCLUDE/INCLUDE". Would it make sense to have these options, too?

If you want that then use the tagged items menu item - no need to duplicate everything

**Comment by pepperstreet** [comment]
@brianteeman 
With reload, I mean to refresh the menuitem AND its link. 
As far as I understand, the problem is the storage of the filter state.
I have tested only 1 blog menuitem, with different tag filters and none. I get the same issue:
https://github.com/joomla/joomla-cms/issues/18138

2. ) Multiple - filter options 
Yes, I know that this is some sort of duplication, but a complete parameter set, IMHO. 
The drawback with tagged items: It is a different component and menuItem type. 
So, it doesn't really help, if you already have a blog display.

**Comment by brianteeman** [comment]
Both of those are beyond the intended scope of this PR

**Comment by pepperstreet** [comment]
@brianteeman Sorry, I just found the related issue too late.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
