### PR TITLE
PHPCS fix

### PR DESCRIPTION
**Pull request by shur**
.

### CODE REVIEW

**Comment by wilsonge** [comment]
Hi,
Could you please remove the fix at the FOF library. That's a 3rd party maintained library (https://github.com/akeeba/fof/tree/fof-2.x) so you need to do the pull request to there and then when Nic releases and update we'll merge it into the CMS!

Once you removed that part I'll merge the other part of this PR
Thanks :)

**Comment by shur** [comment]
Yes indeed, I removed the changes.

**Comment by wilsonge** [comment]
Awesome. RTC

**Comment by Kubik-Rubik** [comment]
Thank you @shur! Merged.

**Pull request closed without merging**
