### PR TITLE
Module Manager. Integrate searchtools bar (instead filters in sidebar).

### PR DESCRIPTION
**Pull request by ghost**
Also fixes feature request
https://github.com/joomla/joomla-cms/issues/6656

Possible conflicts with other PRs (but easy to fix):

1) https://github.com/joomla/joomla-cms/pull/6673
https://github.com/bertmert/joomla-cms/blob/patch-9/administrator/components/com_modules/views/modules/tmpl/default.php#L249-L254

2) https://github.com/joomla/joomla-cms/pull/6677
https://github.com/joomla/joomla-cms/pull/6677#issuecomment-90281269

Test:
- Go to Extensions > Module Manager.
- Before patch:

All filters in sidebar.

com_modules-manager1

Check also issue https://github.com/joomla/joomla-cms/issues/6661
Check also issue/request https://github.com/joomla/joomla-cms/issues/6656
- After patch 

com_modules-manager2

### CODE REVIEW

**Comment by infograf768** [comment]
Looks pretty good here.

**Comment by bertmert** [comment]
@test @aasimali confirmed successfull test here: https://github.com/joomla/joomla-cms/issues/6656#issuecomment-90817339

@zero-24 Thank you for code review!

**Comment by dam-man** [comment]
@test 
Patch is working and better than current previous filtering.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6682">issues.joomla.org/joomla-cms/6682</a>.</sub>

**Comment by zero-24** [comment]
Thanks to the tester and coder! RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6682">issues.joomla.org/joomla-cms/6682</a>.</sub>

**Comment by infograf768** [comment]
This has caused a regression in Hathor where we can't change the client anymore.
See https://github.com/joomla/joomla-cms/pull/6673#issuecomment-100129567

**Comment by bertmert** [comment]
@zero-24 @roland-d @infograf768 Yes, buggy. Please remove RTC and close this PR. I don't find a way to solve conflicts between Hathor and Isis in model modules.php described by infograf768. I don't know why all my tests then seemed to be successfull.

**Comment by Bakual** [comment]
Reverted this PR due to the issues mentioned.
Feel free to propose a new PR.

**Pull request closed without merging**
