### PR TITLE
Fix jQuery XSS Issue

### PR DESCRIPTION
**Pull request by SniperSister**
Pull Request for Issue #19464 .

### Summary of Changes

As documented in the jQuery tracker (jquery/jquery#2432), jQuery 1.x has a potential security flaw connected to AJAX requests, the results returned are executed (!) as JS code by default.

As we can't upgrade to a newer jQuery version in 3.x for BC reasons, I ported the patch developed by the guys at TYPO3:
https://github.com/TYPO3/TYPO3.CMS/commit/43b1d7a8b2a9dbb9cef2715766bfe448a3b71a90

### Testing Instructions
Apply patch, browse pages with AJAX requests (i.e. the backend dashboard or the indexer of com_finder).

### Expected result
Features still work

### Documentation Changes Required
If 3rd party developers rely on the current, dangerous behavior then this change will break their code! So this needs to be communicated upfront!

### CODE REVIEW

**Review by brianteeman — COMMENTED** [review]
Should we add a comment to clearly indicate this has been added by joomla?

**Comment by SniperSister** [comment]
@brianteeman done!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 66be8bf6ebd64ae7c9f27c3226396764c339b587<br /><br />as far as i can tell no issues observed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20660">issues.joomla.org/tracker/joomla-cms/20660</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by dgrammatiko** [comment]
I hate to see us editing external scripts.
Honestly I can't wait to watch jQuery joining the mootools in the tech graveyard...

**Comment by ggppdk** [comment]
Seems to work only with DEBUG on, that loads `media/jui/js/jquery.js`

with DEBUG off , that loads `media/jui/js/jquery.min.js`
i get 
`SyntaxError: expected expression, got '}'[Μάθετε περισσότερα]
jquery.min.js:2:96463`

**Comment by csthomas** [comment]
1. Joomla should remove `*.min.js` from the repo and create it only on the build package or on deploy command. 
For joomla testing, If `*.min.js` does not exists then `*.js` should be used instead, (ex. by .htaccess)

2. Supporting the old version of JQuery in J3.x for the next 2 or 3 years will not be funny.
   > As we can't upgrade to a newer jQuery version in 3.x for BC reasons...

**Comment by SniperSister** [comment]
@csthomas neither of these remarks adds any value to the PR, could you please open new issues for that?

**Comment by SniperSister** [comment]
@ggppdk good catch, fixed!

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 2dc7c10771d7896c6ca784a3049edd21f1f9dc2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20660">issues.joomla.org/tracker/joomla-cms/20660</a>.</sub>

**Comment by ghost** [comment]
@brianteeman can you please retest? [first i wrote: "can you please rest ;-)]

**Review by wilsonge — APPROVED** [review]

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2dc7c10771d7896c6ca784a3049edd21f1f9dc2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20660">issues.joomla.org/tracker/joomla-cms/20660</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20660">issues.joomla.org/tracker/joomla-cms/20660</a>.</sub>

**Pull request merged**
