### PR TITLE
Module edit backend get slow with a lot of menu items #9516

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue  #9516 .
#### Summary of Changes

query  clean  (distinct instead of group by)
#### Testing Instructions

edit a module item from backend with debug plugin enabled and look for
before0
apply the patch and edit a module 
after0

### CODE REVIEW

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on 77abb6dae3e2c24dafd558f3f2cfb3575fbaed6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9689">issues.joomla.org/joomla-cms/9689</a>.</sub>

**Comment by brianteeman** [comment]
Thanks I will test in the morning with the large dataset<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9689">issues.joomla.org/joomla-cms/9689</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 77abb6dae3e2c24dafd558f3f2cfb3575fbaed6e<br /><br />Tested with 4000 menu items
### Before 
Time: 8506.36 ms / 8620.83 ms Memory: 8.762 MB / 13.74 MB Application: afterRenderComponent com_modules

### After
Time: 673.98 ms / 780.86 ms Memory: 8.760 MB / 13.75 MB Application: afterRenderComponent com_modules

# WOW!!!!!


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9689">issues.joomla.org/joomla-cms/9689</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9689">issues.joomla.org/joomla-cms/9689</a>.</sub>

**Comment by benshaty** [comment]
it still slow but if i cancel the multilang query it work good.

before change: 10000ms
image

after change:  93ms
image

line 165:
if (JLanguageMultilang::isEnabled())
		{
			$query->select('l.title AS language_title, l.image AS language_image')
				->join('LEFT', $db->quoteName('#__languages') . ' AS l ON l.lang_code = a.language');
		}

is the lang query necessary?
thanks in advance

**Comment by ggppdk** [comment]
About the broken tree display
Do you imply that this is related to this PR ?
- it looks like a language related

so maybe posting this here is not relevant ?

Does it occur with the original SQL query (without changes of this pull request) ? 
does it occur if you turn off language debug ?
does it occur when you removed the join clause with the language table ?

**Comment by benshaty** [comment]
Do you imply that this is related to this PR ? - **yes i did (i reported the bug)**
Does it occur with the original SQL query (without changes of this pull request) ?  - **now i see that it occur even if i put the original file (the before PR file) so maybe it`s another bug**
does it occur if you turn off language debug ? -** yes**
does it occur when you removed the join clause with the language table ? -** yes**

**Comment by ggppdk** [comment]
@benshaty 
About the language join the data of it are need and used later:
why your SQL server cannot optimize this (we will need to look at explain)

@benshaty 
@alikon 
@brianteeman 
please test the following:

Put it in comments (the language JOIN)
```
/*if (JLanguageMultilang::isEnabled())
{
	$query->select('l.title AS language_title, l.image AS language_image')
		->join('LEFT', $db->quoteName('#__languages') . ' AS l ON l.lang_code = a.language');
}*/
```

and replace it with an extra query on the languages table that 
- will only retrieve a handful of language records:
(the SQL cost of the new query is almost zero, and PHP cost of it is 2 PHP loops with 4000 iterations each, which in anyway is also minimal, (the created language array is also a few rows))

Find lines:
```
try
{
	$links = $db->loadObjectList();
}
```

Replace them with:
```
try
{
	$links = $db->loadObjectList();
	if (JLanguageMultilang::isEnabled())
	{
		// 1. Find code of needed languages and escape them
		$lcodes = array();
		foreach($links as $link) $lcodes[$link->language] = 1;
		
		// 2. Query the languages table
		$lcodes_escaped = array();
		foreach($lcodes as $code => $i) $lcodes_escaped[] = $db->quote($code);
		
		$query = $db->getQuery(true)
			->select('title, image, lang_code')->from( $db->quoteName('#__languages') )
			->where('lang_code IN ('.implode(',', $lcodes_escaped).')');
		$db->setQuery($query);
		
		$langs = $db->loadObjectList('lang_code');
		
		// 3. Set needed language data into the menu links, (existing template code will work)
		foreach($links as $link)
		{
			$lang = @ $langs[$link->language];
			$link->language_title = $lang ? $lang->title : '';
			$link->language_image = $lang ? $lang->image : '';
		}
	}
}
```

**Comment by alikon** [comment]
@benshaty  "template manager" ???? can you put a screenshoot ?
 quite strange thing from your prev screenshoot  **3 duplicate queries**
do you have any 3dp extensions/template ?

**Comment by ggppdk** [comment]
Instead of getting 2-10 rows from the languages table, 
- we duplicate language title and language image on every row that the (menu items) query creates,
and then we ask SQL server to sort and filter (DISTINCT) much larger records, that need more memory to be accommodated

and how many rows are created before sorting and filtering occurs ?
- because of the sub-tree join on lft, rgt that would be a lot ? proportional to n*n ? aka O(n*n) ? , and his web-site has 3000 + menu items, maybe after removing the language join the query data fits inside CPU cache ?

Anyway the join with the language tables does so much unneeded data replication 
- that is better to remove it

**Comment by benshaty** [comment]
@alikon this is the screenshot of the template menu assignment:
image

my template is t-3_bs_blank 

@ggppdk didn`t work on module manager:
image

now when i try to close module  / t-3 template it stuck for a few seconds but work after few seconds.
all the data:
image

**Comment by alikon** [comment]
so is not a core issue as  you are using a non core template

**Comment by benshaty** [comment]
@alikon the problem is not in the template but the module manager

**Comment by ggppdk** [comment]
> @ggppdk didn`t work on module manager:

why would did it ever work ? ))
did i say it would do anything about the broken display ?

- i meant to test it, in order to fix the performance with the language table join

Now about the delay on form save, 
- it is expected considering the current validation JS code
- it is a different issue and there is a pending pull request that excludes menu items from the validation JS (if i remember correctly)

**Comment by alikon** [comment]
let me disagree , is your template code that execute the query **3 times**

**Comment by benshaty** [comment]
@alikon now the template is working good but the order of the modules are defective

**Pull request merged**
