### PR TITLE
[4.0] concatenated strings

### PR DESCRIPTION
**Pull request by brianteeman**
#
This is a codestyle pr to remove the concatenation of strings when it is not required as a single string is enough.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on a05dc3bba4411b35c58b762cb77de6f6156e8418<br /><br />by review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27640">issues.joomla.org/tracker/joomla-cms/27640</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a05dc3bba4411b35c58b762cb77de6f6156e8418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27640">issues.joomla.org/tracker/joomla-cms/27640</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27640">issues.joomla.org/tracker/joomla-cms/27640</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks George

**Pull request merged**
