### PR TITLE
Fixed method case

### PR DESCRIPTION
**Pull request by demis-palma**
#### Summary of Changes

The method JFactory::getDBO() has been renamed to JFactory::getDbo() a few time ago.
I've updated 3 method calls.

### CODE REVIEW

**Comment by zero-24** [comment]
@demis-palma hmm generaly we don't change 3party libs such as fof ;) But it is up to the PLT / Maintaienr to decide :)

**Comment by demis-palma** [comment]
@zero-24 from what I know, fof library has been [donated to the Joomla project](https://www.akeebabackup.com/home/news/1558-info-about-fof-and-f0f.html) and its up to Joomla to maintain it.
The original author has discontinued fof and created F0F instead.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 2b6ba525d4cbcfdac168dedc5bd45f724c04eaff<br /><br />Looks good on code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by zero-24** [comment]
Anyway it is up to the maintainer to decide. If we really want to maintain that lib we have much more todo ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2b6ba525d4cbcfdac168dedc5bd45f724c04eaff<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by zero-24** [comment]
Moiving to `Needs review` so a maintainer can take that :smile: Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by demis-palma** [comment]
Thanks to both for testing and confirm.

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 2b6ba525d4cbcfdac168dedc5bd45f724c04eaff<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge @roland-d can you take a look and decide to merge or not?

**Comment by roland-d** [comment]
We should fix the one in the update notification pluging but not in FOF. As you said, we don't fix stuff in 3rd party libraries.

**Comment by jeckodevelopment** [comment]
@roland-d , since we have already the PR, we could apply it also to the other file. Or not? 
It doesn't require additional work.

**Comment by roland-d** [comment]
@jeckodevelopment No we cannot. The procedure is fixed, we don't fix upstream bugs. This should be done by the package maintainer.

**Comment by jeckodevelopment** [comment]
Ok! got it, thanks!

**Comment by mbabker** [comment]
> The procedure is fixed, we don't fix upstream bugs.

Except FOF2 is EOL'd and Nic has pretty much explicitly stated if there's something that needs to be fixed in the code shipping with Joomla to do so.  The same would have to apply if a bug was found in the phputf8 library; sure it's "upstream" but it's been unsupported for a long time.

**Comment by demis-palma** [comment]
@roland-d I'm a bit confused. I [see several commits](https://github.com/joomla/joomla-cms/commits/staging/libraries/fof) by Joomla members on fof,

- made everytime, from the year 2013 up to the last month,
- about everything, from "PHP 7 compatibility" to "Grammar and error in comments"
- made by everyone: piotrmocko, wilsonge, brianteeman, okonomiyaki3000, phproberto, dbhurley, Bakual, mbabker and infograf768. Besides, of course nikosdion.

So, do you confirm that I really should revert the proposed fix to the fof file?

**Comment by wilsonge** [comment]
The PHP 7 Compatibility was done in conjunction with Nic and actually got changed in the PR to ensure it was exactly the same as the fix made in the official FOF 2 repository. All other commits as far as I can see have been updates to the FOF library... (just some were not done by Nic)

So yes you need to revert this unless nic chooses to accept it in FOF core

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/issues/8525#issuecomment-230589059

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 685a2c07770a193a5a52d0019a9e2b9631f6c6ce<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11301">issues.joomla.org/joomla-cms/11301</a>.</sub>

**Comment by demis-palma** [comment]
Still don't understand, but I obey. Changes to the fof reverted as required.

**Pull request merged**
