### PR TITLE
Update some URLs for update.joomla

### PR DESCRIPTION
**Pull request by sshcli**
Pull Request for Issue # .

### Summary of Changes
Update some update.joomla URLs that were using the old http version.
Now they are https.

### CODE REVIEW

**Comment by sshcli** [comment]
I have excluded this file:
tests\unit\schema\sqlsrv.sql

Please let me know if it is OK to change the URL here too.

**Review by brianteeman — COMMENTED** [review]
Surely these old sql files do not need changes as the url will already be fixed by later sql?

**Comment by sshcli** [comment]
What do you suggest?

**Comment by zero-24** [comment]
@sshcli you can also change that in that file. Why do you want to exclude that file?

> Surely these old sql files do not need changes as the url will already be fixed by later sql?

Yes but is there something bad that this is now fixed earlier?

**Comment by brianteeman** [comment]
Nothing bad just pointless

**Comment by sshcli** [comment]
> you can also change that in that file. 

Done.

> Why do you want to exclude that file?

Nothing wrong with the file.
I'm just trying to do a simple pr, not too complex for read by reviewers. 
I'm trying to avoid any excuse for close this pr. 
I hope you understand.

**Review by zero-24 — APPROVED** [review]
looks good to me even if the sqlsrv.sql file looks broken but this is not a issue in that file thanks @sshcli

**Comment by sshcli** [comment]
Thanks @zero-24

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 197e0a5950c97b980c59d8eb1f5d9084c15ce448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16817">issues.joomla.org/tracker/joomla-cms/16817</a>.</sub>

**Pull request merged**
