### PR TITLE
[4.4] Fix deprecated null warning, in ModuleAdapter: Deprecated: PDO::quote(): Passing null to parameter 1

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

Same as https://github.com/joomla/joomla-cms/pull/41614 but for j4

Fix deprecation for ModuleAdapter
`Deprecated: PDO::quote(): Passing null to parameter 1 ($string) of type string is deprecated `
And `Patch::clean()` on `null`.

### Testing Instructions
Enable error_reaporting to maximum
Try install any module.

### Actual result BEFORE applying this Pull Request
An error message `Unexpected token ...` 
Open Browser console, in network tab for the POST request will be full deprecation message:
`Deprecated: PDO::quote(): Passing null to parameter 1 ($string) of type string is deprecated ` for line https://github.com/joomla/joomla-cms/blob/f19e3f3e0a28707535c72b09c3341e03b04bcb56/libraries/src/Table/Module.php#L210

### Expected result AFTER applying this Pull Request
Module installed without error.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 617cb4e0a5632fdeb95d2318690d506b9d699125<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41617">issues.joomla.org/tracker/joomla-cms/41617</a>.</sub>

**Comment by ceford** [comment]
Probably my misunderstanding - I do not see a deprecation warning when installing a module via System / Install Extensions. I have Debug Yes and Error Reporting Maximum. This is with a clone of joomla-cms and 4.3-dev checked out.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41617">issues.joomla.org/tracker/joomla-cms/41617</a>.</sub>

**Comment by Fedik** [comment]
@ceford sorry, I forgot to add, it for PHP 8

**Comment by martin-zw** [comment]
I have tested this item :white_check_mark: successfully on 617cb4e0a5632fdeb95d2318690d506b9d699125<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41617">issues.joomla.org/tracker/joomla-cms/41617</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41617">issues.joomla.org/tracker/joomla-cms/41617</a>.</sub>

**Pull request merged**
