### PR TITLE
Update composer libraries

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #10835  .
#### Summary of Changes

Updates phpmailer, joomla registry, symfony polyfill (php 5.6), symfony yaml to their latest versions
#### Testing Instructions

Registry is used everywhere. So navigate around and check for errors. Yaml isn't used by core. If possible test in PHP < 5.6 to test the polyfill and check emails still send for phpmailer.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e716894e0e2e5abd66b3cac6cac70438d04f7996<br /><br />Seems ok - sendtestmail still works. No errors navigating around. Not sure what polyfil is used for<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by wilsonge** [comment]
The 5.6 polyfill is used to make the `hash_equals` function available on PHP 5.3, 5.4 and 5.5. So check logging in with passwords still works properly on those php versions

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e716894e0e2e5abd66b3cac6cac70438d04f7996<br /><br />OK something went wrong.
Admin is fine but front end fails to load with this in the logs

> Call to a member function getDefault() on a non-object in libraries/cms/router/site.php on line 266
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by brianteeman** [comment]
Under php7 I get 
> Error displaying the error page: Call to a member function getActive() on null: Call to a member function getDefault() on null<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by wilsonge** [comment]
Woohoo so Joomla's been shipping sample data with invalid JSON since 2012 - we just never had error handling :P Fixed

**Comment by brianteeman** [comment]
The error on the homepage has gone now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4c258c5286b348c7a3719e9eb60608dccfa1ad05<br /><br />Tested creating users and logging in under multiple php versions 5.4, 5.5, 5.6, 7
Tested sending mail using the testmail function in global config<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4c258c5286b348c7a3719e9eb60608dccfa1ad05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11334">issues.joomla.org/joomla-cms/11334</a>.</sub>

**Comment by mbabker** [comment]
@wilsonge What version of Composer do you have?  Current Composer versions are generating a `autoload_static.php` file which isn't added in this PR.

**Comment by wilsonge** [comment]
```
Georges-MacBook-Pro:~ george$ composer --version
Composer version 1.0.2 2016-04-21 12:30:18
```

**Comment by mbabker** [comment]
About time! 😜

**Pull request merged**
