### PR TITLE
[4.0] update Bootstrap to  beta 2

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Documentation Changes Required

@wilsonge

### CODE REVIEW

**Comment by richard67** [comment]
Boottrap? It explains a lot if it really is a trap ;-)

**Comment by dgrammatiko** [comment]
https://user-images.githubusercontent.com/3889375/107555274-42ee8280-6bd7-11eb-8878-3ca3584b5eb4.mp4

**Comment by wilsonge** [comment]
What's the popover change about. Obviously largely looks fine

**Comment by dgrammatiko** [comment]
> What's the popover change about. Obviously largely looks fine

- the `$opt['offset']            = isset($options['offset']) ? $options['offset'] : [0, 0];` was initially removed from popovers as it was producing an error
 
- The trigger is back to `hover focus` for all the elements that are supposed to present the popover on hover
- ~~There is a weird behaviour on the lists (articles, etc basically jGrid) and I think it's down to multiselect.js but that will need another PR~~ Fixed, with proper delay values

**Comment by brianteeman** [comment]
multiselect is broken anyway

**Comment by dgrammatiko** [comment]
> multiselect is broken anyway

might be but at this point the click events are mixed and the popovers are losing the proper target (at least this is my theory atm)

**Comment by Magnytu2** [comment]
Hello how to try this? I don't see a .zip file and cannot install it in the Joomla patch tester? Is it available in the night version of Joomla 4?

**Comment by infograf768** [comment]
@dgrammatiko 
Please update your branch as drone is blocked

**Comment by infograf768** [comment]
Grr, drone still dead

**Comment by rdeutz** [comment]
the special char in the description was the problem that drone didn't run

**Comment by richard67** [comment]
@dgrammatiko If you have emojis in title or description of a PR, it can happen that ci jobs (here drone) don't work. In case of this PR it was the bell for calling George ;-)

**Comment by richard67** [comment]
> Hello how to try this? I don't see a .zip file and cannot install it in the Joomla patch tester? Is it available in the night version of Joomla 4?

@Magnytu2 In the nightly builds PRs which haven't been merged yet will never be included. But the zip files for this PR should be available now for testing.

**Comment by Magnytu2** [comment]
Yes I just tested and it works. The wok flow bubble has disappeared. Great, thank you very much to all the developer team.

**Comment by wilsonge** [comment]
Ok let’s get this in for wider testing. Thanks!

**Comment by Magnytu2** [comment]
@wilsonge @richard67 and ... Wouldn't it be time to switch to joomla! 4 RC. I think a lot of people would be more excited to test and escalate the issues. For extension developers too.

**Comment by brianteeman** [comment]
There are 20 open release blocker issues https://github.com/joomla/joomla-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22Release+Blocker%22

And 6 open release blocker pull requests https://github.com/joomla/joomla-cms/pulls?q=is%3Aopen+is%3Apr+label%3A%22Release+Blocker%22

**Comment by wilsonge** [comment]
Basically what @brianteeman said @Magnytu2 - we need help fixing the release blockers before I feel comfortable releasing an RC - but yes I'd like to release one as soon as we work through the list of blockers

**Comment by peteruoi** [comment]
https://blog.getbootstrap.com/2021/03/22/bootstrap-5-beta-3/

**Comment by dgrammatiko** [comment]
@peteruoi PR: #32827

**Comment by peteruoi** [comment]
Respect sir! :)

**Pull request merged**
