### PR TITLE
Flatten UI

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Flatten UI styling in the Protostar frontend template to match backend.

If this is an improvement or not is questionable. I am happy enough closing if deemed not.

### Testing Instructions
Apply PR and navigate frontend. In particular check frontend article and module editing.

### Before
image

### After
image

### CODE REVIEW

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on cb501cd5455d01a342cbdf848b809f0111408a9d<br /><br />Tested on Firefox and Vivaldi  for macOS.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22407">issues.joomla.org/tracker/joomla-cms/22407</a>.</sub>

**Comment by kofaysi** [comment]
I have tested this item :white_check_mark: successfully on cb501cd5455d01a342cbdf848b809f0111408a9d<br /><br />I like it.

There is still some "unflattened" cases and that is when a button is pressed.
https://screenshots.firefox.com/SZERzFPvSm9nbDzs/svjsvetova523-1.cz<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22407">issues.joomla.org/tracker/joomla-cms/22407</a>.</sub>

**Comment by ghost** [comment]
@ciar4n can you please update the branch so Pull Request can get RTC?

**Comment by brianteeman** [comment]
@franz-wohlkoenig as long as it doesnt have merge conflicts you dont need to ask people to update the branch

**Comment by ghost** [comment]
thanks @brianteeman - ones more forgotton.

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
I'm not happy doing such a big style change in a patch level so I will close this, thx for your work anyway.

**Pull request closed without merging**
