### PR TITLE
Converts the finder plugins to service providers

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Converts the finder plugins to service providers.

### Testing Instructions
- Create articles, contacts, tags and newsfeeds
- Open the Smart Search component in the back end
- Run the indexer

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on ee83e02712270d561c054eef3fedac64c748d0d9<br /><br />Works - no changes detected (PHP 8.1, Index cleared and recreated)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39770">issues.joomla.org/tracker/joomla-cms/39770</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ee83e02712270d561c054eef3fedac64c748d0d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39770">issues.joomla.org/tracker/joomla-cms/39770</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39770">issues.joomla.org/tracker/joomla-cms/39770</a>.</sub>

**Comment by obuisard** [comment]
Thank you Allon @laoneo

**Pull request merged**
