### PR TITLE
Improve wording

### PR DESCRIPTION
**Pull request by smehrbrodt**
This renames the "Purge" button on the Extensions->Update view from "Purge" to "Purge Cache" to make it clearer what the button does.

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally I dont like the word purge in this specific use case and would prefer Clear Cache

**Comment by smehrbrodt** [comment]
Changed it to "Clear Cache". Sounds nicer indeed.

**Comment by brianteeman** [comment]
That means you will also need to update this string
> COM_INSTALLER_MSG_DISCOVER_FAILEDTOPURGEEXTENSIONS="Failed to purge extensions"

**Comment by smehrbrodt** [comment]
That one is part of discover install, but surely I can change it also. What about these two:

`JLIB_INSTALLER_PURGED_UPDATES="Purged updates"`
`JLIB_INSTALLER_FAILED_TO_PURGE_UPDATES="Failed to purge updates."`

**Comment by brianteeman** [comment]
Personally I would look at ALL uses of the word purge and look to change
them to Clear AND add any extra wording required.

Purge is a DB specific word which while accurate is not as meaningful to
end users

On 8 July 2015 at 10:38, Samuel Mehrbrodt <notifications@github.com> wrote:

> That one is part of discover install, but surely I can change it also.
> What about these two:
>
> JLIB_INSTALLER_PURGED_UPDATES="Purged updates"
> JLIB_INSTALLER_FAILED_TO_PURGE_UPDATES="Failed to purge updates."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7376#issuecomment-119523593>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smehrbrodt** [comment]
> Personally I would look at ALL uses of the word purge and look to change them to Clear AND add any extra wording required.

Ok, I've done that. Can you please check the changes?

**Comment by brianteeman** [comment]
Checked from my phone only but looks great to me - thank you

**Comment by Kubik-Rubik** [comment]
Thank you @smehrbrodt! Merged.

**Pull request closed without merging**
