### PR TITLE
[4.0] Remove tooltip from add-new-buttons

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #34594 .

### Summary of Changes
There are two category lists, contact and article categories.
Users can get a link to the form where they can add a new item.

This PR removes the tooltip from the button and adds a more specific text.

### Testing Instructions
Make a category list for contacts and article categories,
Login to get the permission for adding new items,
Compare the buttons before and after the PR.

### Actual result BEFORE applying this Pull Request
see #34594 

### Expected result AFTER applying this Pull Request
grafik

### Additional Information
The file create.php could be removed after this PR, at least I  cannot find where it is used.

### CODE REVIEW

**Comment by brianteeman** [comment]
This PR removes the only use of a layout and two strings

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d4ad18c5bf9da68ec1a79e190da6f8473a2b0698<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by ChristineWk** [comment]
Got this result:

screen shot 2021-06-22 at 20 35 36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by ChristineWk** [comment]
`<a href="/example.org/index.php/list-contacts?task=contact.add&amp;return=aHR0cHM6Ly93d3cud2Fsa2MuYXQvc2FuZGtpc3RlNC9pbmRleC5waHAvbGlzdC1jb250YWN0cw==&amp;id=0&amp;catid=25" class="btn btn-primary">New Contact</a>`

**Comment by ChristineWk** [comment]
New article:

screen shot 2021-06-22 at 20 48 43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by chmst** [comment]
@Bakual could you please have a look here? I would like to remove the language keys and the layout too but have no clue if there is a "legacy" reason for that. 

Thanks for testing @ChristineWk .. maybe I will ask you to repeat :)

**Comment by Bakual** [comment]
The strings can be removed for sure as they are specific to the extension and can't be used by others.

The JLayout could be used by 3rd party as it doesn't contain any extension specific code. I honestly don't know if it's used or not, It certainly isn't a very important one and could be easily replaced with one or two lines of code in the extension. So I'd say it's save to remove as well.

**Comment by chmst** [comment]
I know that weblinks useses the language string JNEW, as it is such a generic string. There it is not a problem as the component  is reviewed for J4.

**Comment by brianteeman** [comment]
I was referring to COM_CONTACT_CREATE_CONTACT and COM_CONTENT_CREATE_CONTACT

**Comment by richard67** [comment]
> I was referring to COM_CONTACT_CREATE_CONTACT and COM_CONTENT_CREATE_CONTACT

@brianteeman I guess you mean COM_CONTACT_CREATE_CONTACT and COM_CONTENT_CREATE_**ARTICLE**

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on bd519956d9728a33f7f35d7e7d4ee6c15f918aae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by ChristineWk** [comment]
Checked language strings:

screen shot 2021-06-23 at 11 21 21

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by ChristineWk** [comment]
previous screenshot corrected:

screen shot 2021-06-23 at 11 27 24

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on bd519956d9728a33f7f35d7e7d4ee6c15f918aae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34601">issues.joomla.org/tracker/joomla-cms/34601</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
If the layout is unused can someone do an additional PR to deprecate it for 5.0 please

**Comment by brianteeman** [comment]
See #34656

**Pull request merged**
