### PR TITLE
[4.2] spelling worflow/workflow

### PR DESCRIPTION
**Pull request by brianteeman**
Code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a8138e193eced5815f8eeab0bd090e59e848ee2b<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38053">issues.joomla.org/tracker/joomla-cms/38053</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a8138e193eced5815f8eeab0bd090e59e848ee2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38053">issues.joomla.org/tracker/joomla-cms/38053</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38053">issues.joomla.org/tracker/joomla-cms/38053</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
