### PR TITLE
[4.1] Resolve Com_contact_email bug in default_address.php

### PR DESCRIPTION
**Pull request by prakhar3062**
Pull Request for Issue #36957 
### COM_CONTACT_EMAIL issue created by [dzandut]
76 <span class="visually-hidden"><?php echo Text::_('COM_CONTACT_EMAIL'); ?>"></span>

### Testing Instructions
Enable email display in contact form and then enter the any value and you will see the value

### Actual result BEFORE applying this Pull Request
Instead of value of variable , variable name will appear

### Expected result AFTER applying this Pull Request
Value of email will appear when you enable email display

### Documentation Changes Required
Not at all

### CODE REVIEW

**Comment by rjharishabh** [comment]
@prakhar3062 please provide the test instructions and also add the issue number.

**Comment by prakhar3062** [comment]
Issue
 #36957 COM_CONTACT_EMAIL in default_address.php.
Test Instructions 
Enable email display in contact form and then enter the any value and you will see the value

**Comment by rjharishabh** [comment]
@prakhar3062  Please update the PR description

**Comment by brianteeman** [comment]
This is only partially complete. The language string is still missing

**Comment by prakhar3062** [comment]
@rjharishabh sorry for trouble i have updated it now.

**Comment by prakhar3062** [comment]
> This is only partially complete. The language string is still missing

It is giving expected result in my system

**Comment by brianteeman** [comment]
Do you see COM_CONTACT_EMAIL when you view the source on the rendered page?

**Comment by prakhar3062** [comment]
> Do you see COM_CONTACT_EMAIL when you view the source on the rendered page?

Yes sir

**Comment by brianteeman** [comment]
That means there is a language string missing then

**Comment by chmst** [comment]
@prakhar3062 would you like to complete this PR? 

You can either change your language key to COM_CONTACT_EMAIL_LABEL, - this will be translated.

Or you can add a new line here for COM_CONTACT_EMAIL
https://github.com/joomla/joomla-cms/blob/4.1-dev/language/en-GB/com_contact.ini#L28

**Comment by prakhar3062** [comment]
> COM_CONTACT_EMAIL_LABEL

Thanks for reminding actually i was suffering with illness. Now i will try to contribute daily

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ade3f25614fb30b046cb6edb39d37252c6bfbfa8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36976">issues.joomla.org/tracker/joomla-cms/36976</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b881367de9455b8d37958039f4e158f86e76398c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36976">issues.joomla.org/tracker/joomla-cms/36976</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36976">issues.joomla.org/tracker/joomla-cms/36976</a>.</sub>

**Comment by prakhar3062** [comment]
> RTC
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36976](https://issues.joomla.org/tracker/joomla-cms/36976).

RTC???

**Comment by rjharishabh** [comment]
RTC means this PR is ready to merge in the Joomla Core.
RTC - Ready To Commit

**Comment by prakhar3062** [comment]
> RTC means this PR is ready to merge in the Joomla Core. RTC - Ready To Commit

okay thanks for telling me

**Comment by Quy** [comment]
Thanks.

**Comment by 7u5a** [comment]
When adding COM_CONTACT_EMAIL it's now showing "> after the translation...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36976">issues.joomla.org/tracker/joomla-cms/36976</a>.</sub>

**Comment by 7u5a** [comment]
I have tested this item :red_circle: unsuccessfully on 68f2c93c5b40a5783d7e6994c086e2a57a1edb7d<br /><br />When adding COM_CONTACT_EMAIL it's now showing "> after the translation...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36976">issues.joomla.org/tracker/joomla-cms/36976</a>.</sub>

**Comment by chmst** [comment]
This is an old PR and was merged in 4.1. 
You should be on 4.2.7 now, so that's a new issue. could you open a new one please? And give some more information about the language you are using and your exact Joomla Version.

**Pull request merged**
