### PR TITLE
[4.3] fix finder common words

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #40215 .

### Summary of Changes

remove duplicate entries which will cause database error
image

### Testing Instructions

install dutch language pack

### Actual result BEFORE applying this Pull Request

no entries in `#__finder_terms_common` for dutch language

### Expected result AFTER applying this Pull Request

88 entries in `#__finder_terms_common` for dutch language (v4.3.4.1) in database

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by flo-the-cat** [comment]
I have tested this item :white_check_mark: successfully on 357fa733ca5a6caf2bbc35b0699c923cebce6a9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41468">issues.joomla.org/tracker/joomla-cms/41468</a>.</sub>

**Comment by brianteeman** [comment]
While this does resolve the issue surely the correct way is to remove the duplicates at source in the NL language pack

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 357fa733ca5a6caf2bbc35b0699c923cebce6a9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41468">issues.joomla.org/tracker/joomla-cms/41468</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41468">issues.joomla.org/tracker/joomla-cms/41468</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for the PR!

**Pull request merged**
