### PR TITLE
RTL Text align right for select Modules list

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Displaying correctly the list of Modules when selecting a new module.

The existing display code dated back from 2012 when it was necessary to order stuff differently.

### Testing Instructions
Install Arabic or Persian language.
Switch to that language in admin
administrator/index.php?option=com_modules&view=select

### Before patch

Screen Shot 2019-04-24 at 16 16 17

### After patch

Screen Shot 2019-04-24 at 16 02 25

### CODE REVIEW

**Comment by alikon** [comment]
this pr seem's not present on the issue tracker
Screenshot from 2019-04-27 13-00-19

btw i've tested it successfully

**Comment by ghost** [comment]
@infograf768 can you please have a look as PR can't be altered test:
Screen Shot 2019-04-27 at 13 26 21

**Comment by alikon** [comment]
some synch glitch happening here now i'm able to see this pr on issue tracker but still unable to mark as tested successfully

**Comment by infograf768** [comment]
no idea why it does not sync.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24722">issues.joomla.org/tracker/joomla-cms/24722</a>.</sub>

**Comment by SniperSister** [comment]
Thanks, merged!

**Pull request merged**
