### PR TITLE
[4.0] Fix switcher position.

### PR DESCRIPTION
**Pull request by Harmageddon**
### Testing Instructions
1. Navigate to "System - Site Templates - Cassiopeia Details and Files".
2. Create an override for a component view.
3. Edit the override.
4. Look at the switcher in disabled and enabled state.
5. Apply the PR.
6. Make sure that the switcher still looks correctly in other places, like com_config.

### Expected result
Screenshot_2019-09-19 Templates Customise (Cassiopeia) - Joomla 4 Git - Administration

### Actual result
Screenshot_2019-09-19 Templates Customise (Cassiopeia) - Joomla 4 Git - Administration broken

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c9347326fc6f5e209b621f220e4743d6e9ba316f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26360">issues.joomla.org/tracker/joomla-cms/26360</a>.</sub>

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on c9347326fc6f5e209b621f220e4743d6e9ba316f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26360">issues.joomla.org/tracker/joomla-cms/26360</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c9347326fc6f5e209b621f220e4743d6e9ba316f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26360">issues.joomla.org/tracker/joomla-cms/26360</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26360">issues.joomla.org/tracker/joomla-cms/26360</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
