### PR TITLE
Spelling fixes and typos

### PR DESCRIPTION
**Pull request by brianteeman**
Big batch of spelling and typos fixed according to style guide (99% are in comments and doc blocks)
https://joomla.github.io/user-interface-text/?user-interface-text/words2watch.md

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark:  successfully on #11295 
Good job @brianteeman

**Comment by brianteeman** [comment]
@jeckodevelopment Luca its best not to add the milestone until its marked RTC ;)

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 5302513e9fa7c2bb1303c18d0f2f4a522d4575fc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11295">issues.joomla.org/joomla-cms/11295</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5302513e9fa7c2bb1303c18d0f2f4a522d4575fc<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11295">issues.joomla.org/joomla-cms/11295</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11295">issues.joomla.org/joomla-cms/11295</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 5302513e9fa7c2bb1303c18d0f2f4a522d4575fc<br /><br />I have tested this item successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11295">issues.joomla.org/joomla-cms/11295</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the merge conflicts, thanks.

**Comment by brianteeman** [comment]
@wilsonge @rdeutz i tried to resolve conflicts but i just made it worse and reverted my attempt

**Comment by rdeutz** [comment]
I tried to merge it but after fixing the conflicts I have seen that some changes recently made are overwritten e.G. travis.yml and the merge will delete the /tests/unit/unit.test.sh what is wrong. Maybe someone else can give it a try. One suggestion for future PR's, don't make PR's with 500+ files, when you can't be sure it gets merged very soon.

**Comment by brianteeman** [comment]
When I made it I had hoped it would get merged quickly! Plus the TT
insisted I should do one big change and not lots of little ones. Can't win
:)

Thanks for trying. If @wilsonge can't do it I can do it again as I have the
notes still

**Comment by brianteeman** [comment]
creating a new pr - should be quicker

**Comment by brianteeman** [comment]
@zero-24 thanks for trying ;(

**Comment by zero-24** [comment]
please give me one more try.

**Comment by brianteeman** [comment]
woohoo!!!

Thanks @zero-24 

@rdeutz this should be ready to merge now

**Comment by andrepereiradasilva** [comment]
722 files changed??

**Comment by brianteeman** [comment]
Maybe I should continue with me redo of this PR - I am 50% there

**Comment by zero-24** [comment]
hmm sorry that it don't work @brianteeman :(

**Comment by brianteeman** [comment]
Closed - please try the redo #11604

**Pull request closed without merging**
