### PR TITLE
[4.0] Spacing between fields and error message

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #  #28204

### Summary of Changes
Move error message

### Testing Instructions
npm i or node build.js compile-css

New Article and then try to save without doing anything

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
Maybe make the spacing closer to the field similar to Title label.

**Comment by brianteeman** [comment]
can you screenshot please as i dont think i understand your request

**Comment by brianteeman** [comment]
I dont see a need for that myself - not a designer - accept the fix or not

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3eb6e729816cd894558781f638300918975d57e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28218">issues.joomla.org/tracker/joomla-cms/28218</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 3eb6e729816cd894558781f638300918975d57e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28218">issues.joomla.org/tracker/joomla-cms/28218</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28218">issues.joomla.org/tracker/joomla-cms/28218</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
