### PR TITLE
Upgrade PHPMailer version to fix deprecation notice on PHP7.4

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #28395

### Summary of Changes
Upgrades PHPMailer to latest version to fix php deprecated notice

### Testing Instructions
Mailing works. No notice on PHP 7.4

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on f07e6ffa07f1a895143594115ca93974419df03f<br /><br />Added line

`$mailer->addAttachment(JPATH_SITE . '/images/joomla_black.png');`

here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_actionlogs/models/actionlog.php#L169

- Activated `Send notifications for User Actions Log *` in my user profile.
- Saved Global Configuration or an article or ...
- Received email plus attachment.

After applying patch no more deprecation messages in my PHP errorLog file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28398">issues.joomla.org/tracker/joomla-cms/28398</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on f07e6ffa07f1a895143594115ca93974419df03f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28398">issues.joomla.org/tracker/joomla-cms/28398</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by wilsonge** [comment]
Cheers guys :)

**Comment by joomleb** [comment]
Hi guys,
the Server Patchman scanning has reported to me a "Code Injection Vulnerability", I reported it [here](Code injection vulnerability #33935)

**Pull request merged**
