### PR TITLE
[5.0] Dark mode for quickicons

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
This feels a bit _hacky_ someone better than me can improve it I am sure.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
waiting for a review by @wilsonge and a successful test

**Comment by HLeithner** [comment]
@coolcat-creations @MacJoom what's your plan for this, seems similar like the alerts for me?

**Comment by coolcat-creations** [comment]
Yes that's also already in the draft

**Comment by HLeithner** [comment]
Thanks then I'm closing this, @MacJoom please keep track of this in #42010

**Comment by brianteeman** [comment]
Sorry I don't understand why this is closed. It is no different to any of the other dark mode fixes that you have merged in the last week. First impressions count and this fixes a bug on the very first page of the admin. In addition it actually works whereas the equivalent in the large pr that will not be merged in 5.0 does not

**Pull request closed without merging**
