### PR TITLE
Make media field initialize itself when a new subform row is added

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes

Subform repeatable has a function `fixScripts` which calls a few js initialization functions on a few of the field types that require it. There is a now a better way to handle that kind of thing by having any field that may need initialization listen for an event fired by subform repeatable. In this PR, I am transferring responsibility of one such initialization from subform repeatable to the correct field type itself. 

Note: this PR doesn't really fix anything. the media field type already works with repeatable subforms. This just does it in a somewhat better way. 

### Testing Instructions

Set up a subform containing a media field. There's a subform in the redirect plugin that's simple to use for this purpose. 

Open up the form and create new rows. The media field in each new row should function properly. 

### Expected result

Media field functions normally.

### Actual result

Media field functions normally.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 83f9b216799a36347b5a620aef3125616dc13945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20230">issues.joomla.org/tracker/joomla-cms/20230</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 83f9b216799a36347b5a620aef3125616dc13945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20230">issues.joomla.org/tracker/joomla-cms/20230</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20230">issues.joomla.org/tracker/joomla-cms/20230</a>.</sub>

**Comment by alikon** [comment]
@HLeithner please a final response 

1 year old rtc pr

**Comment by okonomiyaki3000** [comment]
OK, I'll get right on it

**Review by wilsonge — APPROVED** [review]

**Comment by HLeithner** [comment]
thx

**Comment by okonomiyaki3000** [comment]
See also #20231

**Pull request merged**
