### PR TITLE
[4.2] fix quotes and add noopener in com_users.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

add "noopener noreferrer" and \

### Testing Instructions

click link

### Actual result BEFORE applying this Pull Request

e.g.
`<a href="https://en.wikipedia.org/wiki/Phishing" target="_blank" rel="noreferrer">`

### Expected result AFTER applying this Pull Request

`<a href=\"https://en.wikipedia.org/wiki/Phishing\" target=\"_blank\" rel=\"noopener noreferrer\">`

### Documentation Changes Required

.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c1bcfd21b73819e9a531e65a0404d39b6fba829<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38301">issues.joomla.org/tracker/joomla-cms/38301</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8c1bcfd21b73819e9a531e65a0404d39b6fba829<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38301">issues.joomla.org/tracker/joomla-cms/38301</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38301">issues.joomla.org/tracker/joomla-cms/38301</a>.</sub>

**Comment by fancyFranci** [comment]
Thanks!

**Pull request merged**
