### PR TITLE
No value on joomla update: files extracted #18142

### PR DESCRIPTION
**Pull request by 810**
Pr for:  #18142

### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/administrator/components/com_joomlaupdate/views/update/tmpl/default.php#L59

https://github.com/joomla/joomla-cms/blob/17a45385aeb6f7bffadf68408bd2a5c91bb66684/media/com_joomlaupdate/js/update.js#L269

### Actual result

ff

### System information (as much as possible)

J3.x

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a0edca6234914a7ffee6c68f749de6e8a1143a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18143">issues.joomla.org/tracker/joomla-cms/18143</a>.</sub>

**Comment by brianteeman** [comment]
Can you also update the minified version as well please

**Comment by 810** [comment]
i didn't changed that because the code is different. but i have change it to `t.files`

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 32f267e0c4a182885951cf4d702bc43483f6e83a<br /><br />It appears that this is not utilized `media/com_joomlaupdate/js/update.min.js`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18143">issues.joomla.org/tracker/joomla-cms/18143</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 32f267e0c4a182885951cf4d702bc43483f6e83a<br /><br />i can confirm  minified is not used<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18143">issues.joomla.org/tracker/joomla-cms/18143</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
