### PR TITLE
[com_newsfeeds] Make ACL core.edit.own work (PR for 11466)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11466 (com_newsfeeds part).
#### Summary of Changes

The ACL core.edit.own is not working in newsfeeds.
This PR makes it work.
#### Testing Instructions
1. Use latest staging
2. Besides the Super User, create a user "test" added to "Administrator" group
3. Go to com_newsfeeds Options, Permissions tab and diable "Edit" for "Administrator" group
4. Now create a new newsfeed with the "test" user (use another browser or a private window)
5. Try to edit that item. You can't edit our own. **Bug**
6. Now do the same test but with a newsfeed category Permission. You can't edit our own. **Bug**
7. Apply patch, repeat step 5. and 6. and now you can  edit our own items.
8. Code review

Also use the two users to do a general test with the com_newsfeeds edit permissions to confirm all is fine.
#### Documentation Changes Required

None.
#### Notes

This problem was discovered in GsoC 2016 Multilingual project.
This is very similiar with https://github.com/joomla/joomla-cms/pull/11503.

### CODE REVIEW

**Comment by ggppdk** [comment]
Without testing , it looks good on code review

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e31bdd9bec373178a72182b980638a00c07f2062<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11502">issues.joomla.org/joomla-cms/11502</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on e31bdd9bec373178a72182b980638a00c07f2062<br /><br />Changed my testing as we get a Notice (same as for contacts):

[07-Aug-2016 07:12:14 UTC] PHP Notice:  Undefined variable: record in ROOT/administrator/components/com_newsfeeds/controllers/newsfeed.php on line 83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11502">issues.joomla.org/joomla-cms/11502</a>.</sub>

**Comment by ggppdk** [comment]
Yes variable name is $item not $record

**Comment by andrepereiradasilva** [comment]
sorry guys. corrected that. please test.

**Comment by alikon** [comment]
no more notice after the last update

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 02ba80438d187a838f2c82b408f6461888d75bfb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11502">issues.joomla.org/joomla-cms/11502</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 02ba80438d187a838f2c82b408f6461888d75bfb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11502">issues.joomla.org/joomla-cms/11502</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11502">issues.joomla.org/joomla-cms/11502</a>.</sub>

**Pull request merged**
