### PR TITLE
Hyperlinked "Smart Search plugin not enabled"

### PR DESCRIPTION
**Pull request by pe7er**
This PR changes the language file for the **Smart Searchr** (com_finder) so that the "Smart Search content plugin is not enabled. Changes to content will not update the Smart Search index if you do not enable this plugin." contains an hyperlink to the Plugin Manager.
## Test instructions

In back-end > Components > **Smart Search**
If the Smart Search - Content Plugin is not enabled, it will display a message "Smart Search content plugin is not enabled. Changes to content will not update the Smart Search index if you do not enable this plugin."

screen shot 2015-05-14 at 10 14 32
### This PR changes the language string

so that the warning message has a hyperlink to the Plugin Manager,
including a filter option for the name "Content - Smart Search".

screen shot 2015-05-14 at 10 14 32
### Result of that hyperlink

If you click on the hyperlink you will be redirected to the Plugin Manager,
which filters the "Content - Smart Search" so you can easily enable it.

screen shot 2015-05-14 at 10 14 32

### CODE REVIEW

**Comment by hans2103** [comment]
even tiny steps like these will increase usability. Thank you @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6948">issues.joomla.org/joomla-cms/6948</a>.</sub>

**Comment by hans2103** [comment]
@test succes

**Comment by zero-24** [comment]
@pe7er Same here would it be easier to use: `id:441`

As the ID will work every time on every language (as it is on all installs the same) or do we have reasons to not use the id?

**Comment by zero-24** [comment]
Please ignore my last comment. id is not a good way as we can not assume that the id is the same on all installations (see: https://github.com/joomla/joomla-cms/pull/6947#issuecomment-102164611)

**Comment by sovainfo** [comment]
What makes you think assuming the labels are the same is better than assuming the id's are?
Sounds to me that using the id's is better, provided they are determined on execution time.
That requires the isEnabled to retrieve both enabled and id, introduce the getPluginid and replace that in the message with sprintf.

Then this works no matter the language used by the administrator in the backend!
It is also prepared for the time Joomla doesn't hard code these id's anymore!

**Comment by pe7er** [comment]
I understand your concert @sovainfo. IMHO in this case labels are better than IDs provided that the reference to the Plugin Name is translated correctly.
I've added a comment for translators (thanks @infograf768 for this suggestion in a similar PR #6947 )

**Comment by zero-24** [comment]
@test also here successful. Thanks :smile: RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6948">issues.joomla.org/joomla-cms/6948</a>.</sub>

**Pull request merged**
