### PR TITLE
[4.0] Global checkin - select all style

### PR DESCRIPTION
**Pull request by brianteeman**
The class text-center was missing from the select all box

Pull Request for Issue # .

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ad22865c7c336ed5f1765fedefec3b5913f5a45a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24031">issues.joomla.org/tracker/joomla-cms/24031</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 55e327240ccb900fd2bc311df456a7ec3ae27f01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24031">issues.joomla.org/tracker/joomla-cms/24031</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24031">issues.joomla.org/tracker/joomla-cms/24031</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
