### PR TITLE
[4.0] [com_menus] Untranslated string

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/29001.

### Summary of Changes

Restores a string that was removed but is still in use.

### Testing Instructions

> Install Blog Sample Data.
> Go to Menus > All Menu Items
> Edit Home.
> Click the browser's back button so that the Home menu item is checked out.
> Click the Home icon of another menu item to make it the default.
> See error/success alerts.

### Expected result

No untranslated strings.

### Actual result

Untranslated `COM_MENUS_ITEMS_SET_HOME` string.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c73a00dc75db55aa571659b66f32c62619843c42<br /><br />Code Inspect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29004">issues.joomla.org/tracker/joomla-cms/29004</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c73a00dc75db55aa571659b66f32c62619843c42<br /><br />String is translated as required.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29004">issues.joomla.org/tracker/joomla-cms/29004</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29004">issues.joomla.org/tracker/joomla-cms/29004</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
