### PR TITLE
Fix submenu being (transparent) displayed despite not being 'open', blocking usage of contents at the edge of all backend screens

### PR DESCRIPTION
**Pull request by ggppdk**
Pull Request for Issue #21360

### Summary of Changes
Hide sub-menus when not in use

### Testing Instructions
See #21090 
you can not use the first column at the left of the screen (or other contents at the left (right for RTL))
because (a transparent) sub-menu is open and receiving the clicks

### Expected result
The sub-menus are not open when not used

### Actual result
The sub-menus are open when not used, (and are transparent) 
blocking usage of contents at the edge of all backend screens

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bff2f868fda3908bc96abb125862d4408cc170ba

Test on Plugins as [Comment](https://github.com/joomla/joomla-cms/issues/21090#issuecomment-408007015) wrote, works as expected.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21316">issues.joomla.org/tracker/joomla-cms/21316</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on bff2f868fda3908bc96abb125862d4408cc170ba<br /><br />Before the patch when I try to move a plugin it would drag the menu item, after applying the patch I was able to drag and drop the plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21316">issues.joomla.org/tracker/joomla-cms/21316</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
@ggppdk can you fix the conflicts here please?

**Comment by ggppdk** [comment]
@wilsonge  conflicts fixed

**Comment by wilsonge** [comment]
Thanks!

**Comment by ggppdk** [comment]
hhmm
it seems that the CSS files that i committed were not updated ?
because i build the CSS in windows , and building CSS in windows is not working ?

**Comment by infograf768** [comment]
I have totally lost second level sub menus here. See https://github.com/joomla/joomla-cms/issues/21353

**Pull request merged**
