### PR TITLE
news feeds options - showon

### PR DESCRIPTION
**Pull request by brianteeman**
Summary of Changes

Use the showon functionality now available in forms to simplify/reduce the options displayed in the com_newsfeeds component options

Testing Instructions

This is only a cosmetic change
Go to the Options page for this component and try all the options on that page to ensure that the new show/hide functionality makes sense.

[Note this is part of a series of PR for each component options page and then the menu options]

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 0d557b45d9117f972df01273d555f275268464ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10156">issues.joomla.org/joomla-cms/10156</a>.</sub>

**Comment by MATsxm** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10156">issues.joomla.org/joomla-cms/10156</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 0d557b45d9117f972df01273d555f275268464ac<br /><br />Ooops, didn't check the right box :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10156">issues.joomla.org/joomla-cms/10156</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10156">issues.joomla.org/joomla-cms/10156</a>.</sub>

**Pull request merged**
