### PR TITLE
Missing Editor breaks the script on modal xtd button

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### The problem

Select either none or code mirror as your editor
Edit an article
Try inserting a module by name or position
An error is logged in your browsers console
#### The fix

Pass a var to specify the editor’  id in the script
#### Test

Apply this patch and repeat the above procedure

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 1f43f4822c197c652b6826096f935d2971d046fe<br /><br />Works now. Thanks @dgt41 one more tester<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8269">issues.joomla.org/joomla-cms/8269</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on b1109fdda7f93c1d36ed8c19d9009e7abdcca4bf<br /><br />Still works (just a CS fix)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8269">issues.joomla.org/joomla-cms/8269</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 875ebf02b35212d18985b43b37d76d5fbb5b5a43<br /><br />Still works with the last commit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8269">issues.joomla.org/joomla-cms/8269</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 875ebf02b35212d18985b43b37d76d5fbb5b5a43<br /><br />Before I get a JavaScript error trying to add in a module, after applying the patch the module is added correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8269">issues.joomla.org/joomla-cms/8269</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please add the RTC label.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8269">issues.joomla.org/joomla-cms/8269</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thanks @dgt41 and testers! Merged.

**Pull request merged**
