### PR TITLE
[4.0] Autocomplete new-password

### PR DESCRIPTION
**Pull request by brianteeman**
Following the advice from  [chromium](https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands)
> You can help ensure that browsers' and extensions' password management functionality can understand your site's sign-up, sign-in and change-password forms by enriching your HTML with a dash of metadata.

This PR basically changes most autocomplete=off to `new-password` or `current-password` as appropriate and if relevant to `username`

PR #26467 is required

### CODE REVIEW

**Comment by Quy** [comment]
Related PR #23913?

**Comment by brianteeman** [comment]
@quy almost except this one works. It would not work without 26467

**Comment by Quy** [comment]
OK to close the other PR?

**Comment by Quy** [comment]
Please fix conflicts.

**Comment by brianteeman** [comment]
conflicts fixed

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6d4467571c3ca1eddec1f5d94c1dbf004c691302<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26494">issues.joomla.org/tracker/joomla-cms/26494</a>.</sub>

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 6d4467571c3ca1eddec1f5d94c1dbf004c691302<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26494">issues.joomla.org/tracker/joomla-cms/26494</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26494">issues.joomla.org/tracker/joomla-cms/26494</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
