### PR TITLE
Add missing PHPMailer Translation string

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This just adds the missing translation for the `extension_missing` string to the Joomla Translation

### Testing Instructions

Review
The string gots added here: https://github.com/joomla/joomla-cms/commit/4861b21b7037a6c4e4ee7a6df69462a830219b6f so is part of the CMS since 3.5.0

### Expected result

String is there and added to the PHP Mailer Translation

### Actual result

String is always in english and not translated via the Joomla Translation system

### Documentation Changes Required

None

### CODE REVIEW

**Comment by wilsonge** [comment]
@infograf768 as this string is already in English since 3.5.0 is it ok to merge this for 3.7?

**Comment by wilsonge** [comment]
RTC on review

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on bf25eef3b0860fb37ade7456517b0eed2066c47f<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15328">issues.joomla.org/tracker/joomla-cms/15328</a>.</sub>

**Comment by infograf768** [comment]
imho 3.7.1

**Pull request merged**
