### PR TITLE
[4.2] Fix missing context for com_fields after publish/unpublish items

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR add missing context variable in URL for com_fields after an action such as publish/un-publish fields and field groups. The missing context variable  causes the parent menu item being closed (instead of stay open as expected) after admin doing certain action.

This is the replacement for original PR https://github.com/joomla/joomla-cms/pull/37818. The code implemented in that PR is wrong, I suggested the change but look like the author too busy and he did not update it after months, so I decide to make this one to replace so that we can have this small issue fixed. See the original PR if you want to understand more about the issue which this PR solves. 

### Testing Instructions
1. Login to administrator area of your site
2. Access to Content -> Fields.
3. Create a custom field (if you do not have any custom fields created before)
4. Try to publish/unpublish that field
5. Repeat steps above for Content -> Field Groups

### Actual result BEFORE applying this Pull Request
After publish, un-publish selected fields, the Content menu item being closed. You had to click on Content again before you can access to Content -> Fields.

Same for Content -> Field Groups
### Expected result AFTER applying this Pull Request
The Content menu item stays open as expected.

### Link to documentations
Please select:
- [] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2e92b881ffaaa130e7399e52c7d8cae8cbaa162a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39926">issues.joomla.org/tracker/joomla-cms/39926</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2e92b881ffaaa130e7399e52c7d8cae8cbaa162a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39926">issues.joomla.org/tracker/joomla-cms/39926</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39926">issues.joomla.org/tracker/joomla-cms/39926</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
