### PR TITLE
[4.3] Media Manager Regression

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #40690 .

### Summary of Changes

- The url/session path is not respected

### Testing Instructions

- test a url like (existing path) `/administrator/index.php?option=com_media&path=local-images:/banners`
- test a url like (not existing path) `/administrator/index.php?option=com_media&path=local-none:/banners`
- test a url like (not existing path) `/administrator/index.php?option=com_media&path=local-none:/noooooo`
- test a url like (not existing path) `/administrator/index.php?option=com_media`
- Open the browser console and edit the session value from something like: `{"selectedDirectory":"local-images:/banners","showInfoBar":false,"listView":"grid","gridSize":"md","search":"","sortBy":"name","sortDirection":"asc"}` to values matching the changes on the previous steps (eg `"selectedDirectory":"local-none:/banners"`, "selectedDirectory":"local-none:/noooooo") and check if the media manager loads without an error
- Apply all possible combos between the url and the session storage

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@laoneo please check all possible combinations between stored session/given url

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks for the fast pr. Do we really want to make another api call? I would say it is enough to just override the session parameter with the one from the url, or do I miss here something?

**Comment by dgrammatiko** [comment]
Closing here, there's another PR which patches parts of the buggy behavior

**Comment by laoneo** [comment]
Can this not be done in a way that, when the server returns a 404, it goes to the session path? Having an extra check query for every list files request can lead to a resource issue.

**Comment by dgrammatiko** [comment]
Allon, the problem is that the Store should not start with empty directories/files as it does with either this PR or yours. That is the real problem (because there's no code in the media manager to cope with such state). So, a proper solution (not even this one) is to have the state pre filled with the correct data (in case of a missing folder or mistyped or... you get fallback, as I was trying to do with the previous and this PR). Also in such way you get only 1 fetch for existing folders and more (depending on the fallback code) for missing/mistyped paths.

**Comment by laoneo** [comment]
It does fallback to the first disc or not?

**Comment by dgrammatiko** [comment]
> It does fallback to the first disc or not?

It's up to the fallback code, I was lazy and hardcoded it to the first disc but could be more clever (ie if the given disc exists fallback to the root of that drive, etc)

**Comment by laoneo** [comment]
For me that sounds right. I was more thinking about to add more logic here https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_media/resources/scripts/app/Api.es6.js#L139. When a 404 is returned, then it should got to another location, either what is in the session or the root folder.

**Pull request closed without merging**
