### PR TITLE
[4.1] Check if attributes have a value before trimming in menu table

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The menu table adds some checks if the values are empty. On PHP 8.1 these checks do throw a deprecated message when the value is null. For example on:
_trim(): Passing null to parameter 1 ($string) of type string is deprecated in /libraries/src/Table/Menu.php on line 128_

This happens only when doing a discover install with DPDocker, so it can be merged as code review.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on deba8573c2f7979aef9b232eeb5bbcc263270c14<br /><br />Confirm the issue by installing an extension and check PHP error logs. This PR does solves the issue, so I gave it a successful test

Personal, I would change the code a bit to:

```php
if ($this->path === null || trim($this->path) === '')
```

OR:

```php
if (trim($this->path ?? '') === '')
```

Also, during installation, the only line which is having issue is line 128. The changes for other lines are just for consistency only (data for the other fields are populated in already).

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37337">issues.joomla.org/tracker/joomla-cms/37337</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on deba8573c2f7979aef9b232eeb5bbcc263270c14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37337">issues.joomla.org/tracker/joomla-cms/37337</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37337">issues.joomla.org/tracker/joomla-cms/37337</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :red_circle: unsuccessfully on deba8573c2f7979aef9b232eeb5bbcc263270c14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37337">issues.joomla.org/tracker/joomla-cms/37337</a>.</sub>

**Comment by bembelimen** [comment]
grafik

**Comment by laoneo** [comment]
Good catch, fixed it with a null check in https://github.com/joomla/joomla-cms/pull/37337/commits/a0678b1b6f35e22822f821e374b683cd2bc051eb? Do you want to again some tests?

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
