### PR TITLE
contact item access level fix #7944

### LINKED ISSUE #7944: Error in com_contact for component URL when access not allowed
If I construct a component URL for a contact that is not accessible to public, I can access that contact when logged in.

For example, for contact ID=169 and alias=bob2
http://[...]/component/contact/contact/169-bob2

If I then log out and try to access the same page I get an exception thrown, when I would expect "access denied" or an instruction to log in.

> exception 'Exception' with message 'Contact not found' in [...]/components/com_contact/models/contact.php:330 Stack trace: #0 [...]/components/com_contact/models/contact.php(254): ContactModelContact->getContactQuery(169) #1 [...]/libraries/legacy/view/legacy.php(401): ContactModelContact->getItem() #2 [...]/components/com_contact/views/contact/view.html.php(66): JViewLegacy->get('Item') #3 [...]/libraries/legacy/controller/legacy.php(690): ContactViewContact->display() #4 [...]/components/com_contact/controller.php(42): JControllerLegacy->display(true, Array) #5 [...]/libraries/legacy/controller/legacy.php(728): ContactController->display() #6 [...]/components/com_contact/contact.php(15): JControllerLegacy->execute(NULL) #7 [...]/libraries/cms/component/helper.php(392): require_once('/var/www/prayer...') #8 [...]/libraries/cms/component/helper.php(372): JComponentHelper::executeComponent('/var/www/prayer...') #9 [...]/libraries/cms/application/site.php(191): JComponentHelper::renderComponent('com_contact') #10 [...]/libraries/cms/application/site.php(230): JApplicationSite->dispatch() #11 [...]/libraries/cms/application/cms.php(252): JApplicationSite->doExecute() #12 [...]/index.php(45): JApplicationCms->execute() #13 {main}

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

create/edit a contact item and set the access level to registered fox example
then set a menu item to that contact item and access
reported  #7944 @waveywhite
#### Expected result

An error message  your not authorzied...
#### Actual result

contact_ko
#### After patch

contact_patch

### CODE REVIEW

**Comment by waveywhite** [comment]
Good grief that was quick!

**Comment by infograf768** [comment]
Was not it solved here already?
https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/7824

**Comment by joomdonation** [comment]
Infact, we had different PR https://github.com/joomla/joomla-cms/pull/7867 which fixes the issue and also improve the code. That PR is RTC.

**Comment by infograf768** [comment]
oops, forgot indeed #7867 
Yep, I think that one is better, as @joomdonation states.

**Comment by alikon** [comment]
not so sure too much code :stuck_out_tongue_winking_eye:

**Comment by bembelimen** [comment]
@test patch works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7951">issues.joomla.org/joomla-cms/7951</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @alikon! Merged.

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 6a171db8bfc59a793b035f06291f60aa80ea8c5d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7951">issues.joomla.org/joomla-cms/7951</a>.</sub>

**Pull request merged**
