### PR TITLE
[4.0] Improve text for uploadinfo

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #33095 .

### Summary of Changes
Break down information. 

### Testing Instructions
apply patch and to to joomlaupdate, try upload of a file. 

### Actual result BEFORE applying this Pull Request
see  #33095

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 149a9a9e83567b48299739e141ea224c5ebbb296<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33116">issues.joomla.org/tracker/joomla-cms/33116</a>.</sub>

**Comment by ChristineWk** [comment]
It looks much better now:

screen shot 2021-04-12 at 17 34 33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33116">issues.joomla.org/tracker/joomla-cms/33116</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 149a9a9e83567b48299739e141ea224c5ebbb296<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33116">issues.joomla.org/tracker/joomla-cms/33116</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33116">issues.joomla.org/tracker/joomla-cms/33116</a>.</sub>

**Pull request merged**
