### PR TITLE
Native language (adjustments after 12036 merge)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.
### Summary of Changes

One side effect of https://github.com/joomla/joomla-cms/pull/12036 merge was that en-GB native language title `English (United Kingdom)` was replace is several language select fields (installation, admin login and user profile admin language) by `English (en-GB)`

This PR restaures the previous text by checking if the new `nativeName` metadata exists for the language, if so, will use it, if not, will fallback to `name` metadata.
### Testing Instructions
- Use 3.7.x branch
- Go to `/installation/index.php?view=site` and confirm the title of en-GB language is `English (en-GB)`

image
- Apply patch
- Repeat step and confirm the title of en-GB language title is `English (United Kingdom)`

image
- Also confirm the same result in the admin login and user profile admin language select fields, ie, whenever joomla is using the xml files metadada to generate this select fields.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by infograf768** [comment]
Looks like test is broken

**Comment by zero-24** [comment]
I think the change here is expected.

```
1) JLanguageHelperTest::testCreateLanguageList
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (
-        'text' => 'English (en-GB)'
+        'text' => 'English (United Kingdom)'
         'value' => 'en-GB'
         'selected' => 'selected="selected"'
     )
 )
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/language/JLanguageHelperTest.php:38
```

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0ec1b6bfe3943b36b4b3afc9cf4500b7f1ec52bd<br /><br />OK here.

Needs one more tester.

@alikon <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12394">issues.joomla.org/tracker/joomla-cms/12394</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0ec1b6bfe3943b36b4b3afc9cf4500b7f1ec52bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12394">issues.joomla.org/tracker/joomla-cms/12394</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Pull request merged**
