### PR TITLE
Render the sidebar when it is not empty

### PR DESCRIPTION
**Pull request by laoneo**
#### Summary of Changes

When a plugin adds some sidebar entries for com_modules, then render it.
#### Testing Instructions
- Install DPFields from https://joomla.digital-peak.com/download/dpfields
- In the back end go to the Extensions -> Modules
#### Expected result

You should see on the left side a list of links (Modules, Fields, Field Categories). After DPFields is uninstalled, the view Extensions -> Modules should be shown without a sidebar.
#### Actual Result

The sidebar is not shown.

### CODE REVIEW

**Comment by mbabker** [comment]
How about just always render it and avoid conditionals like https://github.com/Digital-Peak/joomla-cms/blob/98aca2d283ae91c39414207fbc477b46b130e11b/administrator/components/com_modules/views/modules/tmpl/default.php#L29-L36 in the layouts.

**Comment by laoneo** [comment]
I tested it and showed then the sidebar with an empty list.

**Comment by mbabker** [comment]
`*sigh*`  I guess this is one of those views where it might be an optional thing.

**Comment by laoneo** [comment]
Means?

**Comment by mbabker** [comment]
Just as you pointed out, the sidebar here can be empty.  On most other views that have the sidebar conditional, it's usually not unless someone used a malicious plugin to remove the component's defined sidebar so that conditional is just bloated logic.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 98aca2d283ae91c39414207fbc477b46b130e11b<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10720">issues.joomla.org/joomla-cms/10720</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 98aca2d283ae91c39414207fbc477b46b130e11b<br /><br />(side note not related to this PR. uninstalling dpfields package gives error - i expected it to remove all of dpfields)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10720">issues.joomla.org/joomla-cms/10720</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10720">issues.joomla.org/joomla-cms/10720</a>.</sub>

**Pull request merged**
