### PR TITLE
Add type hinting to JComponentRouterBase

### PR DESCRIPTION
**Pull request by malukenho**
Add type hinting to `JComponentRouterBase` and simplify assigns

### CODE REVIEW

**Comment by Hackwar** [comment]
Hello @malukenho, I did not add type hinting here, because you should be able to hand in almost arbitrary objects, mainly to allow for proper unittesting.

**Comment by malukenho** [comment]
@Hackwar can't be mocked?

**Comment by Hackwar** [comment]
Basically, I would rather type hint an interface and not a specific class like JMenu or JApplicationCms... In any case, you would have to change the unittests to work with those type hints, too.

**Comment by brianteeman** [comment]
I am closing this at this time. As stated above it needs unittests before it gets merged and I assume that as there has been no update they wont be forthcoming

**Pull request closed without merging**
