### PR TITLE
Properly merge tag params

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #13641.

### Summary of Changes
I don't know what to say after looking at that code... That stuff certainly didn't work at all before.
In short, item and menu params are now properly merged.

### Testing Instructions
Test that tag parameters are merged properly, meaning that options set in the tag override those in the menu item. Except when the menu item is an exact match to the tag (eg it's a single tag menuitem for that specific tag shown), then the menu item takes precedence over the tag params

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
will test today.

**Comment by franz-wohlkoenig** [comment]
Test-Scenario: 

1. 2 Tags without single tag menuitem
2. menuitem `list-of-all-tags`, no other tag-menuitemtype published
3. 2 tags are shown
4. click on one tag got `Call to a member function get() on string`. Same if click on tag in an article.
5.  if menuitem `list-of-all-tags` is unpublished, got correct view "index.php/component/tags/tag/*"

**Comment by Bakual** [comment]
The error was a typo on my part. Can you try again?
I also fixed another bug I saw that the single tag view loaded the layout parameter from the tags list view... *sigh*

**Comment by franz-wohlkoenig** [comment]
menuitem `list-of-all-tags` works. Furthermore testing.

**Comment by franz-wohlkoenig** [comment]
- In "Tags > Options" a "Tag Image" is set on "Show" and is displayed. 
- In an Tag on Tab "Images" set Float of "Full Image" to "Right". This don't work, Image stay left.

**Comment by Bakual** [comment]
The parameter for the image float seems to be not used at all in com_tags. That would be a different PR to add this, but not one I'm going to write :smile:

**Comment by franz-wohlkoenig** [comment]
made #13646

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 28dc5181d07f574fcd27666af0d997611737c0cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13643">issues.joomla.org/tracker/joomla-cms/13643</a>.</sub>

**Comment by justinherrin** [comment]
Thanks for getting to this one so quickly! I will test it out now.

**Comment by justinherrin** [comment]
I have tested this item :white_check_mark: successfully on 28dc5181d07f574fcd27666af0d997611737c0cf<br /><br />Patch applied to the view.html.php file all is working good from the issue I reported. Tags View Layout (one without a menu item) is now grabbing the correct layout selected in the single Tag parameters and not choosing the one set in Global Tags Component Options.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13643">issues.joomla.org/tracker/joomla-cms/13643</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13643">issues.joomla.org/tracker/joomla-cms/13643</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@justinherrin does 

> Tags View Layout (one without a menu item) is now grabbing the correct layout selected in the single Tag parameters and not choosing the one set in Global Tags Component Options.

mean i can close #13646?

**Pull request merged**
