### PR TITLE
[com_contact] add missing `row` class (V2)

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request to replace https://github.com/joomla/joomla-cms/pull/11753
### Summary of Changes

This PR fixes the width for `.row-striped .row-fluid { }` and buckled rows on `com_contact`, **without** having to change the HTML markup
### Testing Instructions

See here: https://github.com/joomla/joomla-cms/pull/11753
### Results

**Before patch:**
before

**After patch:**
after

### CODE REVIEW

**Comment by nvyush** [comment]
@C-Lodder I found two files more: '/media/jui/css/bootstrap-extended.css' and '/media/jui/less/bootstrap-extended.less'

Could you add some improvement to '/components/com_contact/views/category/tmpl/default_items.php' from my version - sizing of `span` / lines with `$contact_width` variable? Then I close my PR.

**Comment by C-Lodder** [comment]
I'll add the `$contact_width` but I'm not going to update the bootstrap LESS file. That's why I manually added it to the `protostar.less` ;)

**Comment by nvyush** [comment]
I have tested this item :white_check_mark: successfully on ac8a8e9.

I downloaded the current native bootstrap v 3.7.7. It doesn't contain 'bootstrap-extended.less' file and doesn't contain any *.*ss file with `97%`. I think files'/media/jui/css/bootstrap-extended.css' and '/media/jui/less/bootstrap-extended.less' could be modified also.

**Comment by C-Lodder** [comment]
@dgt41 ?

**Comment by mbabker** [comment]
> It doesn't contain 'bootstrap-extended.less' file

Because that's Joomla's custom addons to the core Bootstrap LESS.

**Comment by C-Lodder** [comment]
@nvyush - Moved the Protostar LESS changes to `bootstrap-extended.less`

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ae41b79bacb0ba5b1b36188d8abca62d2afc36d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11807">issues.joomla.org/joomla-cms/11807</a>.</sub>

**Comment by dgt41** [comment]
@C-Lodder can you re-run generates.php?

**Comment by nvyush** [comment]
I have tested this item :white_check_mark: successfully on ae41b79

**Comment by C-Lodder** [comment]
@dgt41 oops, done

**Comment by nvyush** [comment]
I have tested this item :white_check_mark: successfully on ea9e020

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11807">issues.joomla.org/joomla-cms/11807</a>.</sub>

**Pull request merged**
