### PR TITLE
Fix save user without selecting user groups

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #13653.

### Summary of Changes
This PR prevents add/edit an account without selecting a user groups in the backend of your site. It also fixes a notice Undefined index: groups... when administrator update his own account from backend

### Testing Instructions
Test case 1: Login to administrator are of your site using super admin account, try to add/edit an user

1. Before patch, you can add/edit an account without selecting a user group
2. After patch, if you try to add/edit an account without selecting at least one user groups, error will be thrown and account won't be saved

Test case 2: Login to administrator area of your site using an administrator account, edit your account, make sure it is saved properly

### Documentation Changes Required

None

### CODE REVIEW

**Comment by renekreijveld** [comment]
I have tested this item :white_check_mark: successfully on e68775f98d5221bd99e87aa63e07c22061ed1aad<br /><br />Tested on Joomla 3.7.0-beta1, works perfect!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13656">issues.joomla.org/tracker/joomla-cms/13656</a>.</sub>

**Comment by genesisfan** [comment]
I have tested this item :white_check_mark: successfully on e68775f98d5221bd99e87aa63e07c22061ed1aad<br /><br />Tested on Joomla 3.7.0-beta1 and works perfect!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13656">issues.joomla.org/tracker/joomla-cms/13656</a>.</sub>

**Comment by joomdonation** [comment]
Thanks @renekreijveld and @genesisfan  for testing the PR.

**Comment by wilsonge** [comment]
Administrators can't edit their own groups only super admins can modify their own groups? https://github.com/joomla/joomla-cms/commit/da79cb043e0e663239728cc853bc6e53eda7d9ea

**Comment by joomdonation** [comment]
@wilsonge Yes, that's what I see from the code. Right now, when you login using an administrator account, there is no option to allow changing your own groups. Only super admin can do that

**Comment by joomdonation** [comment]
I just updated code to remove an unnecessary nested if, no need for testing it again.

**Comment by joomdonation** [comment]
This PR had two successful tests. Could someone please add RTC label ?

**Comment by tonypartridge** [comment]
@joomdonation can I be picky and can you please add a full stop to the end of your new language string as per the others above.

**Comment by joomdonation** [comment]
Yes, done. Thanks @tonypartridge

**Pull request merged**
