### PR TITLE
Messages component column alignment

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Simple PR to line up the columns
#### Testing Instructions

You will need to create some private messages first and then be logged in as the recipient of those messages.
#### Before

messages-before
#### After

messages-after

### CODE REVIEW

**Comment by MATsxm** [comment]
I have not tested this item.<br /><br />Able to reproduce then works as described - Thanks

**Side note:**
Tooltip message notification is not "clean"

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by brianteeman** [comment]
Not tested?

What do you mean about not "clean"

On 11 April 2016 at 23:11, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> I have not tested this item.
>
> Able to reproduce then works as described - Thanks
>
> *Side note:*
> Tooltip message notification is not "clean"
>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9860
> <https://issues.joomla.org/tracker/joomla-cms/9860>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9860#issuecomment-208586370>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MATsxm** [comment]
screen shot 2016-04-11 at 17 21 52

Hmmm strange, my screenshot is on GitHub but not on the IssueTracker...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by brianteeman** [comment]
Thats off topic for this PR but personally it looks ok to me
screen shot 2016-04-11 at 17 24 59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by MATsxm** [comment]
strange... tested on Chrome 49.0.2623.110 m Zoom 100%
nevermind

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1672ae7325a18d40867ad2fc4da18ab88cdc724c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by andrepereiradasilva** [comment]
BTW i also have the tooltip thing.

**Comment by brianteeman** [comment]
I did and then I didnt - not sure why - anyway thats another PR

On 12 April 2016 at 00:49, andrepereiradasilva <notifications@github.com>
wrote:

> BTW i also have the tooltip thing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9860#issuecomment-208624675>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1672ae7325a18d40867ad2fc4da18ab88cdc724c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9860">issues.joomla.org/joomla-cms/9860</a>.</sub>

**Comment by brianteeman** [comment]
Ignore last messages - i committed to the wrong branch and then reverted. This PR is still good to go

**Pull request merged**
