### PR TITLE
[com_fields] Change Jtext String issue #13393

### PR DESCRIPTION
**Pull request by coolcat-creations**
Change Change text

Pull Request for Issue #13393.

### Summary of Changes
Changed Hint to Placeholder and made the description in the tooltip more clear.

before:
image

after:
image

### CODE REVIEW

**Comment by laoneo** [comment]
The hint field is available in all form fields, that's why I called it hint and not placeholder https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/field.php#L36. It is not specific to input fields, otherwise it would be available only for the text form field. But honestly I don't know if other extension developers are using it as in core it is only used with text input fields.

**Comment by mbabker** [comment]
`JFormField` (stupidly) calls a placeholder a "hint" versus the correct term used by, oh, the entire internet.  So we're running into a case now where either we use the Joomla term and be wrong everywhere or we use the right term in the UI and hope people are informed enough to realize that the attribute it's actually setting in the code has a different name.

**Comment by cpfeifer** [comment]
I agree with this. As Allon pointed out, it's used on every field type, not just text fields, so I would amend the text to "A placeholder which will appear inside the field input as a hint"

We can change the text string without changing the XML field name so it doesn't affect anything but the display. Placeholder is much more appropriate text in this case.

I would also consider the possibility of only having placeholder inputs shown on field types that can actually utilize them. If the field type doesn't support a placeholder then it shouldn't be an option. I imagine changing this to be field type specific would take some work but I'm not entirely sure how much work. It's something we should consider either way.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on b43387b1d988d8ac2e78c4a0acb98f61618ab1c2<br /><br />Works as described in "Summary of Changes"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13420">issues.joomla.org/tracker/joomla-cms/13420</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on b43387b1d988d8ac2e78c4a0acb98f61618ab1c2<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13420">issues.joomla.org/tracker/joomla-cms/13420</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13420">issues.joomla.org/tracker/joomla-cms/13420</a>.</sub>

**Pull request merged**
