### PR TITLE
Add showon option in global config

### PR DESCRIPTION
**Pull request by micker**
Adding showon option in whole global config

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @test successful

### how to test
- apply the patch using com_patchtester
- play arround with the offline settings (BE --> Global Configuration --> Site)
- play arround with the Cache Settings (BE -> Global Configuration --> System -> Cache)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6722">issues.joomla.org/joomla-cms/6722</a>.</sub>

**Comment by brianteeman** [comment]
What does this setting do?

On 9 April 2015 at 14:45, zero-24 <notifications@github.com> wrote:

> Thanks @test <https://github.com/test> successful
> how to test
>
>    - apply the patch using com_patchtester
>    - play arround with the offline settings (BE --> Global Configuration
>    --> Site)
>    - play arround with the Cache Settings (BE -> Global Configuration -->
>    System -> Cache)
>    ------------------------------
>    This comment was created with the J!Tracker Application
>    <https://github.com/joomla/jissues> at
>    issues.joomla.org/joomla-cms/6722
>    <http://issues.joomla.org/tracker/joomla-cms/6722>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6722#issuecomment-91236033>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
It displays a field only when another field has some specific settings.
Btw just remarked that Hathor does not have any showon

**Comment by Bakual** [comment]
@brianteeman Doc is here: https://docs.joomla.org/Form_field#Showon

**Comment by micker** [comment]
i think i will start to implement in all xml goal => have a lighter admin for beguiner

**Comment by losedk** [comment]
I'm not fond of the function at the offline message:

Custom message should be hidden as well 

skaermbillede 2015-04-09 kl 16 20 54

**Comment by brianteeman** [comment]
@bakual all issues should be accompanied with full instructions. The tester
should not have to search

**Comment by micker** [comment]
sorry it my first pr what he do :
-hide offline option @losedk if we want to acheive this we nned to change default value of display_offline_message to 0 (maybe we can, i am waitting confirmation)
-hide cache option

**Comment by Dylis** [comment]
@test - Success, patch working as expected, but, Custom message field still appear when Site offline is set to "no". Is that supposed to be ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6722">issues.joomla.org/joomla-cms/6722</a>.</sub>

**Comment by micker** [comment]
yes we need to change this behavior

**Comment by zero-24** [comment]
@micker what is the status regarding the Custom message field? Do you what to send a commit to change that behavior?

**Comment by brianteeman** [comment]
@micker Thank you for your contribution.

The last comment here was on 12 June. Can you please follow-up on this issue? If not this will be closed within 4 weeks

Thanks for understanding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6722">issues.joomla.org/joomla-cms/6722</a>.</sub>

**Comment by brianteeman** [comment]
Closed as per comment above - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6722">issues.joomla.org/joomla-cms/6722</a>.</sub>

**Pull request closed without merging**
