### PR TITLE
[4.3] Better cache invalidation

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #40787 .

### Summary of Changes

If there's a modified_date use it (as unix timestamp) else fallback to the existing mediaversion

Screenshot 2023-06-19 at 15 55 21

### Testing Instructions

- Apply the PR
- Edit an image
- check that the rest of the images are loaded from the cache

### Actual result BEFORE applying this Pull Request

Cache is always invalidated

### Expected result AFTER applying this Pull Request

Cache is invalidated only for items/files with different modified date

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 560080bee2f821237f38c2481e3a0ca0b226542f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40893">issues.joomla.org/tracker/joomla-cms/40893</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 560080bee2f821237f38c2481e3a0ca0b226542f<br /><br />Tested it and the edited image got a new timestamp and the new one is loaded. Before it could happen that the old image was loaded in the list when the browser has cached the old image.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40893">issues.joomla.org/tracker/joomla-cms/40893</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40893">issues.joomla.org/tracker/joomla-cms/40893</a>.</sub>

**Comment by Mich-es** [comment]
I have tested this item :white_check_mark: successfully on e469855f572c79cdc266e62864584256064db195<br /><br />Great - it works for me THX<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40893">issues.joomla.org/tracker/joomla-cms/40893</a>.</sub>

**Comment by laoneo** [comment]
Can you guys also test #40704 as it restores the old behavior in the media manager.

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for this PR!

**Pull request merged**
