### PR TITLE
Installation language errors missing

### PR DESCRIPTION
**Pull request by brianteeman**
Includes some library strings that may be needed when a language fails to install

Pull Request for Issue #15503.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
@brianteeman i installed joomla-cms-install_lang_string but got no fail on insstalling Bulgarian Lang.

**Comment by brianteeman** [comment]
@franz-wohlkoenig the bg language has been fixed now so this can really only be reviewed based on reading the reported error and seeing that this PR now includes those strings

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 305133525fae9a0a1d8b3f67a32e605cf7f78703<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16014">issues.joomla.org/tracker/joomla-cms/16014</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
