### PR TITLE
a11y improvement for login form

### PR DESCRIPTION
**Pull request by brianteeman**
Every form with a fieldset should also have a legend. The login form does not
### Summary of Changes

Add a legend to the fieldset using a new language string and with a css class that renders the text invisible.
### Testing Instructions

Apply PR and go to login page (not module) on the front end
Check the code and you will find after the fieldset tag a legend tag

`<legend class="element-invisible">Login Form</legend>`

### CODE REVIEW

**Comment by C-Lodder** [comment]
Legend is not required, but instead optional. So not really any point in rendering unnecessary markup

**Comment by jeckodevelopment** [comment]
`Groupings of form controls, typically groups of related checkboxes and radio buttons, sometimes require a higher level description (such as "Shipping Method" for a group of shipping option radio buttons). This descriptive text can be associated to the group of form controls using <fieldset> and <legend>. The <fieldset> identifies the entire grouping and <legend> identifies the grouping's descriptive text. Using <fieldset> and <legend> ensures that the text description is read to screen reader users when the grouping is navigated to.`
From http://webaim.org/techniques/forms/

**Comment by C-Lodder** [comment]
@jeckodevelopment - Screen readers to not read hidden elements (`display:none;`). We have 2 options:

1. Close this PR
2. Update the PR and use `text-indent: 9999;` instead of `display:none;`

**Comment by brianteeman** [comment]
Disagree

**Comment by C-Lodder** [comment]
Disagree with what? What we know so far:

1. `<legend>` is optional: ([Ref](https://developer.mozilla.org/en/docs/Web/HTML/Element/fieldset))
2. Screen readers do not read text that is hidden using `display:none;` or `visibility:hidden;` ([Ref](http://webaim.org/techniques/css/invisiblecontent/))

Therefore is screen readers won't detect it (as it's hidden) **and** it's an optional element, why add it?

**Comment by brianteeman** [comment]
My mistake in my memory our class element invisible was the equivalent to
the bootstrap three class sr-only.

**Comment by brianteeman** [comment]
Closed

**Pull request closed without merging**
