### PR TITLE
Fixes favicon issues in Windows (#5559)

### PR DESCRIPTION
**Pull request by smz**
See https://github.com/joomla/joomla-cms/issues/5559 for details

### CODE REVIEW

**Comment by smz** [comment]
Now we have #5580 too for solving #5559.

As I commented in #5580, I think both it and this PR should be merged.

**Comment by richard67** [comment]
And now we also have #5967 , which I've just tested with success. I think there where #5967 corrects code, the usage of DIRECTORY_SEPARATOR makes sense.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5566">issues.joomla.org/joomla-cms/5566</a>.</sub>

**Comment by richard67** [comment]
P.S.: Please @smz check if this one here can be closed in favour of #5967 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5566">issues.joomla.org/joomla-cms/5566</a>.</sub>

**Comment by smz** [comment]
Sorry, Richard, I'm not contributing to this project any more: I've totally lost my trust in it and the way it is managed.

Regards,

Sergio

**Comment by dgt41** [comment]
@smz 😞

**Comment by smz** [comment]
@dgt41 It's OK, Dimitris... there are a lot of wonderful things around! I'll miss some of you but not having to deal with persons like Mr. Brian "Strings" Teeman and friends is... refreshing.

**Comment by richard67** [comment]
@smz sorry to read that you stopped. I think we both were a good team when working together on PRs and testing. But I agree with you, Brain sometimes acts like a so-called troll, today saying this and tomorrow saying the opposite, and sometimes not being logical at all. But what does not kill us makes us strong, or not?

**Comment by brianteeman** [comment]
Thank you for your kind words

On 5 February 2015 at 18:05, Richard Fath <notifications@github.com> wrote:

> @smz <https://github.com/smz> sorry to read that you stopped. I think we
> both were a good team when working together on PRs and testing. But I agree
> with you, Brain sometimes acts like a so-called troll, today saying this
> and tomorrow saying the opposite, and sometimes not being logical at all.
> But what does not kill us makes us strong, or not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5566#issuecomment-73095079>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
I edited the offending things out of the comments. This is certainly not the place for personal attacks. Thanks for keeping that in memory.

**Comment by smz** [comment]
@richard67 You see Richard? The troops are moving in! You can't go against a monument unless you are a bulldozer. Or a pigeon.

**Comment by smz** [comment]
The issue this was solving has been solved somewhere else (probably  #6081), so I'm closing this.

**Pull request closed without merging**
