### PR TITLE
[5.x] Fix `secure` flag for session cookies

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
The rework of the session management introduced in 5.x broke the code that sets the `secure` flag for the session cookie on sites with enforced HTTPS. The $options variable, containing the config isn't passed to the storage anymore, resulting in the absence of the flag regardless of the configuration state:
https://github.com/joomla/joomla-cms/commit/84776fbe9969ce04ec76ae89a7424474d0b128da#diff-bc8698a8418bcc017e622d13e0d460e94f502f09ae0f9c50cb6cd9f7ede73cb0L90

### Testing Instructions
Enable "force SSL" on a 5.x site, inspect the session cookie using your developer tools. Verify that the flag is absent. Apply the patch and **delete the cookie** in your browser. Refresh.

### Actual result BEFORE applying this Pull Request
No `secure` flag

### Expected result AFTER applying this Pull Request
`secure` flag is set as expected

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by SniperSister** [comment]
I've labeled the PR as release blocker because it's security relevant

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on a459e59aedd023ab41ff99724f6a573e5459ee97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43882">issues.joomla.org/tracker/joomla-cms/43882</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on a459e59aedd023ab41ff99724f6a573e5459ee97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43882">issues.joomla.org/tracker/joomla-cms/43882</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43882">issues.joomla.org/tracker/joomla-cms/43882</a>.</sub>

**Comment by wilsonge** [comment]
My bad! Must have had something in mind at some point - but no clue what 3 years later :(

**Pull request merged**
