### PR TITLE
Global menu options

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #34248 .

### Summary of Changes
Fix missing useglobal attributes to site display params.
Remove site_title form global params

Fix missing param pageclass_sfx.

### Testing Instructions
Testing is playing with global setting of menu options and setting of params in menuItems. 

grafik

- The site title (in meta data of the head)
- The site title on the page if it is not hidden
- The pageclass in the source code
- Note: not all views use the pageclass_sfx. This is not in scope of this PR.

### Actual result BEFORE applying this Pull Request
Settings of global params is ignored. see #34248 .

### Expected result AFTER applying this Pull Request
If global Params are set for Menu and menu Item has no own param for this
then the global param is used

if a menu Item has set own Param,
then own Params are used

### CODE REVIEW

**Comment by brianteeman** [comment]
@chmst I understand that this code will make the options work. It confirms what I reported that they dont currently work as there is no code to use them and the same is true in J3. So as no one reported an issue lets remove them instead of fixing them as they cant have been used. Am I missing something?

**Comment by ghost** [comment]
@chmst no test cause its a draft, right?

**Comment by drmenzelit** [comment]
> @chmst no test cause its a draft, right?

right

**Comment by chmst** [comment]
Sorry I forgot to activate this PR. @sandramay0905 , @brianteeman a test would be highly appreciated, I think it is now as it should be.

**Comment by ghost** [comment]
> The site title (in meta data of the head)

You mean setting in `Global Configuration` > `Site` > `SEO` > `Site Name in Page Titles` to `After` or `Before`?

> The site title on the page if it is not hidden

You mean setting in `Global Configuration` > `Site` > `SEO` > `Site Name in Page Titles` to `No`?

> Note: not all views use the pageclass_sfx. This is not in scope of this PR.

I test on a category-blog-view and can't find `myGlobalPageClass` which i set in menu-options so i guess this is one of the views they don't use pageclass_sfx. Can you please say which view use this sfx?

**Comment by brianteeman** [comment]
page class - have not been able to get it to be used anywhere

page title - it works but I dont see the use case for this - ever

show page title - works as before

As stated in the original report #3428 the two non working options have not worked for years (and no one commented). So surely the fix is to remove them instead of wasting time trying to fix.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e203d389d910e847206ac92837042eb2adc97780<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34311">issues.joomla.org/tracker/joomla-cms/34311</a>.</sub>

**Comment by chmst** [comment]
Pageclass_sfx is used on single item pages only.

**Pull request closed without merging**
