### PR TITLE
[4.0] Displaying articles captions below the images

### PR DESCRIPTION
**Pull request by infograf768**
As discussed in https://github.com/joomla/joomla-cms/pull/20503
It is a much more common usage to display a caption below the illustration.

### Summary of Changes
Modify the order of image and caption in the layouts for intro and full text articles parameters

### Testing Instructions
Parameter an article with an intro image and a full text image, each with a caption.
screen shot 2018-05-21 at 17 24 40

### Before patch
Captions are displayed on top of the image.

### After patch
They are displayed below.
screen shot 2018-05-21 at 17 15 41

screen shot 2018-05-21 at 10 50 01

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a1e27b5d187b9fed192dc3d4e6ac121bf032510a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20520">issues.joomla.org/tracker/joomla-cms/20520</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on a1e27b5d187b9fed192dc3d4e6ac121bf032510a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20520">issues.joomla.org/tracker/joomla-cms/20520</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on a1e27b5d187b9fed192dc3d4e6ac121bf032510a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20520">issues.joomla.org/tracker/joomla-cms/20520</a>.</sub>

**Comment by dgrammatiko** [comment]
RTC

**Pull request merged**
