### PR TITLE
[4.0] StatsHelper cs

### PR DESCRIPTION
**Pull request by infograf768**
Correcting StatsHelper code style.

Can be merged on review.
@wilsonge @laoneo

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7f0f215452d2887302f14992de10888bdac602ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21849">issues.joomla.org/tracker/joomla-cms/21849</a>.</sub>

**Comment by roland-d** [comment]
*rantmode*
Just my pet peeve, I think we should use names as aliases and not letters. In other words `worflow_stages` instead of `ws` and `content` instead of `c`
*/rantmode*

**Comment by brianteeman** [comment]
@roland-d you are not alone.

**Comment by alikon** [comment]
in theory i agree, for readability etc....
but sometimes when you have more "**_long_**" queries is more readable with letters imho

_rantmode_
btw this silly module have already take us too much time  recently :smile: 
_/rantmode_

**Comment by infograf768** [comment]
@wilsonge 
please merge as drone is not happy in other Prs with these errors

**Pull request closed without merging**
