### PR TITLE
[4..0] Fixing Searchfilter Field in com_finder

### PR DESCRIPTION
**Pull request by Hackwar**
Right now the Searchfilter field in the menu item does not work. Instead of that field, a simple text field is loaded. This fixes that. It also removes the Directories Field, which is used nowhere and is basically a copy of the Folderlist field that we have in core.

### How to test
1. Enable the smart search plugin, index all your content
2. Go to the search filters in the backend and create a new filter
3. Go to your Smart Search Menu item and see that the field "Search Filters" is just a text input.
4. Apply this patch
5. See that the Search Filters field now displays a list

### CODE REVIEW

**Comment by infograf768** [comment]
Don't you need to also modify the module?

**Comment by infograf768** [comment]
In fact I was right
You need to also modify the module xml
`<fields name="params" addfieldpath="/administrator/components/com_finder/models/fields">`
to
`<fields name="params" addfieldprefix="Joomla\Component\Finder\Administrator\Field">`

**Comment by Hackwar** [comment]
Fixed.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 4b601d9d1302cf0cd62ccd12be36f1bc51356c36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20790">issues.joomla.org/tracker/joomla-cms/20790</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4b601d9d1302cf0cd62ccd12be36f1bc51356c36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20790">issues.joomla.org/tracker/joomla-cms/20790</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20790">issues.joomla.org/tracker/joomla-cms/20790</a>.</sub>

**Comment by wilsonge** [comment]
Can you drop a PR to deprecate the unused field in 3.9 branch please

**Comment by Hackwar** [comment]
https://github.com/joomla/joomla-cms/pull/20812 The deprecating PR

**Pull request merged**
