### PR TITLE
[4.1] Lazy Stylesheet comment

### PR DESCRIPTION
**Pull request by brianteeman**
#3241 added the ability to lazy load a stylesheet. This PR just adds a comment to explain why and how it works.

I spent ages looking at it and had to go back to the original PR before I understood and most users won't think to do that. It was even commented in the original PR that this needed exmplaining

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cc39c3798531dd220c57d919f22a83b31b9b9f6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37310">issues.joomla.org/tracker/joomla-cms/37310</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on cc39c3798531dd220c57d919f22a83b31b9b9f6a<br /><br />There is nothing to teast, really. I just had a look at the commit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37310">issues.joomla.org/tracker/joomla-cms/37310</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37310">issues.joomla.org/tracker/joomla-cms/37310</a>.</sub>

**Comment by brianteeman** [comment]
did you really need to merge the branch? Everytime you do that you reset all the tests.

image

**Comment by laoneo** [comment]
Yes, when the branch is not up to date, I can't merge.

**Comment by laoneo** [comment]
Thanks!

**Comment by alikon** [comment]
rtc status didn't change even after a merge, if rtc still value something...

**Comment by brianteeman** [comment]
Then you need to change the user settings on github. Its a pointless action just to work around an acl rule

**Comment by laoneo** [comment]
I don't set the rules. It's an inner circle who does. In the past it was more relaxed, people who were maintainers were also administrators. Now times are different.

**Comment by brianteeman** [comment]
You missed the point. If the ACL prevents you from merging unless the branch is upto date but allows you to update the branch yourself then the ACL rule is useless.

**Pull request merged**
