### PR TITLE
Replace unnecessary double quotes in administrator #2

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
- Replace unnecessary double quotes

The changes in this PR should be fairly easy to review. In hope that this will get merged quickly so further work can be done without conflicting with other PRs. ;)

### Testing Instructions

None, should not change behavior

### Documentation Changes Required

None.

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Review by dgrammatiko — APPROVED** [review]

**Comment by frankmayer** [comment]
Any chance this one and the other related PR (#13295) can be reviewed / tested / merged?

**Comment by shur** [comment]
I have not tested this item.<br /><br />Code review. Good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13293">issues.joomla.org/tracker/joomla-cms/13293</a>.</sub>

**Comment by shur** [comment]
I have tested this item :white_check_mark: successfully on 71af5827132c770eee297aff77bb9d3d295073d9<br /><br />Code review. Good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13293">issues.joomla.org/tracker/joomla-cms/13293</a>.</sub>

**Comment by shur** [comment]
@andrepereiradasilva  @dgt41 
Can you approve these changes on https://issues.joomla.org/

**Pull request merged**
