### PR TITLE
Coding standards - References and control structures

### PR DESCRIPTION
**Pull request by marcochirienti**
### Summary of Changes

Fixed coding style:
- for all control structures there is a space between the keyword and an opening parenthesis;
- when using references, there should be a space before the reference operator and no space between it and the function or variable name.

### Testing Instructions

Code review

### Documentation Changes Required

None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Please add also a space between `):` so it becames `) :`

**Comment by marcochirienti** [comment]
I was thinking to proceed in a step by step approach, to make code review easier and to prevent accidental mistakes.

I found 361 hits in 155 files inside the branch for `):`, so i was planning to make a separate pull request for this.

There are also other things that i think should be reviewed in these files, e.g. in control structures the opening curly bracket should be on a new line.

If you prefer i can make all the changes and then update the pull request.

Please, forgive my poor English, but i'm not a native speaker.

**Comment by andrepereiradasilva** [comment]
> If you prefer i can make all the changes and then update the pull request.

ok. there's really no need if it's merged faster.
i was just trying to avoid PR conflicts because PR sometimes take some time to merge.

> Please, forgive my poor English, but i'm not a native speaker.

me neither 😉 

@zero-24 please check this one also, so it's merged faster to avoid conflicts if decided

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3289ba90382ad158b49313d2cd09c7bf5a444b8e<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13022">issues.joomla.org/tracker/joomla-cms/13022</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 3289ba90382ad158b49313d2cd09c7bf5a444b8e<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13022">issues.joomla.org/tracker/joomla-cms/13022</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@marcochirienti one advice, if/after this PR is merged, make a specific branch for each PR you make and keep staging branch  sincronized with joomla main staging branch or you will get trouble in the future.

**Comment by marcochirienti** [comment]
> [...] or you will get trouble in the future.

That sounds like a threat, @andrepereiradasilva :smile: 
Thank you for the advice, Sir.

**Comment by andrepereiradasilva** [comment]
> That sounds like a threat, @andrepereiradasilva 😄

lol, just tryng to make your life easier ....

**Comment by marcochirienti** [comment]
Thank you, i appreciate it.
As i said, i'm completely new to all this stuff, so any advice is welcome.

**Comment by brianteeman** [comment]
We appreciate you spending the time doing this

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13022">issues.joomla.org/tracker/joomla-cms/13022</a>.</sub>

**Comment by photodude** [comment]
@marcochirienti Since you are interested in improving the compliance with the code standards I would like to ask you to participate in testing and verifying our updated version of the code standards running on PHPCS 2.x . The updated version of the code standards brings in automated code fixers to help with code style compliance. You can find the WIP PR in the code style repo at this link https://github.com/joomla/coding-standards/pull/109

**Comment by marcochirienti** [comment]
I'd be glad to do it. I will take a look at it as as soon as possible.

**Pull request merged**
