### PR TITLE
[5.x] String sentence

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted while debugging

### Summary of Changes
The error message is a sentence so it must end with a period

### Testing Instructions
code review

### Maintainers
No idea anymore which branch this shoud go in. Feel free to move it. As long as its fixed somewhere I dont care

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on a495d5c619542261a20c92ee90d6ed92af799d45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43249">issues.joomla.org/tracker/joomla-cms/43249</a>.</sub>

**Comment by chmst** [comment]
I have not tested this item.<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43249">issues.joomla.org/tracker/joomla-cms/43249</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43249">issues.joomla.org/tracker/joomla-cms/43249</a>.</sub>

**Comment by chmst** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43249">issues.joomla.org/tracker/joomla-cms/43249</a>.</sub>

**Comment by richard67** [comment]
@chmst Are you sure the milestone 5.2.0 which you have set is right? Or did you want to set 5.1.1 (which doesn't exist yet)?

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
