### PR TITLE
[Mssql] Fix syntax error when installing a language in backend

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13508 (use issue part).

### Summary of Changes

Fix for https://github.com/joomla/joomla-cms/issues/13508 (use issue part)

### Testing Instructions

1. apply patch
2. Install a language in mssql. no use error. note you will get another error, but the use error is fixxed here

### Documentation Changes Required

None

### CODE REVIEW

**Comment by waader** [comment]
The semicolon in line 66 should be deleted. After that I get:
Fatal error: Using $this when not in object context in joomla37\administrator\components\com_installer\models\languages.php on line 151

**Comment by andrepereiradasilva** [comment]
semicolon deleted, thanks
that fatal error doesn't seem related to this mssql issue this PR solves.
Please open a new issue for that

**Comment by zero-24** [comment]
@waader 

> The semicolon in line 65 should be deleted. After that I get:
Fatal error: Using $this when not in object context in joomla37\administrator\components\com_installer\models\languages.php on line 151

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/languages.php#L151

Can you try staging? at this line we have no $this in staging :smile:

**Comment by waader** [comment]
With your patch applied it "becomes" line 151.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 65f086a2b78cbc373a2234bd22f96bac527ff3c5<br /><br />solve [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'use'.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13512">issues.joomla.org/tracker/joomla-cms/13512</a>.</sub>

**Comment by waader** [comment]
@alikon Did you do a code review? I keep getting the mentioned syntax error after applying the patch. I tried with latest staging, no data installed.

**Comment by andrepereiradasilva** [comment]
@waader the thing is that seems a different error. another one. this PR only solves the `use` part.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 65f086a2b78cbc373a2234bd22f96bac527ff3c5<br /><br />Ok, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13512">issues.joomla.org/tracker/joomla-cms/13512</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13512">issues.joomla.org/tracker/joomla-cms/13512</a>.</sub>

**Pull request merged**
