### PR TITLE
Unit testing for plugins

### PR DESCRIPTION
**Pull request by wilsonge**
OK So unit testing for plugins it turns out is easily doable

Now I need some ideas on how to test the email cloaking plugin (which currently is the bane of our lives) as of course it's designed not to be detectable my bots! Ideas anyone?

Currently tests are failing because I've added in JM's test examples and not bothered to add the correct expected results - just so people can experiment and look at what I've done.

### CODE REVIEW

**Comment by Hackwar** [comment]
Can you update this PR to latest staging and solve the merge conflicts? Maybe we can work on this together in the near future and solve the test issues.

**Comment by roland-d** [comment]
Hello @wilsonge 

Thank you for your contribution.

The last comment here was on 3rd February. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4071">issues.joomla.org/joomla-cms/4071</a>.</sub>

**Comment by wilsonge** [comment]
Yes this is definitely still valid

**Comment by roland-d** [comment]
@wilsonge So this is still valid but no way to test it and merge it?

**Comment by mbabker** [comment]
Once that CLI specific thing comes out (which is a bad hack for the unit tests to always have a known value, changing the behavior of what's being tested ironically) there is no human testing involved in this one; it's all unit test changes (so ensure CI passes and code review).

**Comment by wilsonge** [comment]
So how do we deal with random numbers. I can't predict a random number as the unit test outcome :P

**Comment by mbabker** [comment]
Assert the string contains a stretch of text around it, or come up with some kind of regex to assert that the string is built correctly with a number that's in the valid range defined by the randomizer.  Altering the behavior of a method when you're testing it is probably worse than not testing the thing.  Plus, this should only be testing what the plugin method does, not what the JHtml helper is doing too (but since it's all static, it can't be mocked, oh how I love the CMS environment sometimes...).

**Comment by wilsonge** [comment]
So you can try doing something like this I guess https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/form/fields/JFormFieldCalendarTest.php#L262-L322

**Comment by mbabker** [comment]
I don't know if I should laugh at how hysterical the notion of overriding JHtml calls with its API for testing is or cry because that's a necessity.

**Comment by zero-24** [comment]
@wilsonge can you fix the merge conflicts? Than we can see what the unit test say about your code ;)

**Comment by roland-d** [comment]
Hello @wilsonge

Thank you for your contribution.

The last comment here was on 23rd August. Are you planning to work on this any time soon? If not, please close and re-open when you plan to work on it.

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4071">issues.joomla.org/joomla-cms/4071</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response for further information - it can always be reopened if that is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4071">issues.joomla.org/joomla-cms/4071</a>.</sub>

**Pull request closed without merging**
