### PR TITLE
[4.0] Change </td> to </th>

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix wrong closing tag.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 8dd2c3116fa24aed695b8e1febee39a6c4f754db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36344">issues.joomla.org/tracker/joomla-cms/36344</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8dd2c3116fa24aed695b8e1febee39a6c4f754db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36344">issues.joomla.org/tracker/joomla-cms/36344</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36344">issues.joomla.org/tracker/joomla-cms/36344</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
