### PR TITLE
[4.0] Remove unnecessary markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove unnecessary markup to make it consistent with identical code here:
https://github.com/joomla/joomla-cms/pull/27445/files#diff-3541cae319fabd8eddc585b3a8b770e9R39 

### Testing Instructions
Code review.

or

Edit a site module.
Go to Menu Assignment tab.
See Menu Selection.
No visible changes before/after the PR.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8248aedef6a7d8484182839fe875440ecc2a2a0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27482">issues.joomla.org/tracker/joomla-cms/27482</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8248aedef6a7d8484182839fe875440ecc2a2a0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27482">issues.joomla.org/tracker/joomla-cms/27482</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27482">issues.joomla.org/tracker/joomla-cms/27482</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
