### PR TITLE
[4.0] Fix filtering articles by multiple categories

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/29406.

### Summary of Changes

Fixes query when filtering by multiple categories.

### Testing Instructions

Create some categories.
Create articles in those categories.
Go to article list in backend.
Filter articles by multiple categories.

### Expected result

Articles from multiple categories are shown.

### Actual result

Articles from single category are shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e924b22645627a74cde7f3feb257337b8a7affef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29466">issues.joomla.org/tracker/joomla-cms/29466</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e924b22645627a74cde7f3feb257337b8a7affef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29466">issues.joomla.org/tracker/joomla-cms/29466</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29466">issues.joomla.org/tracker/joomla-cms/29466</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! Nice debugging btw :)

**Comment by SharkyKZ** [comment]
I'll have to check if I haven't introduced more issues like this 😅.

**Pull request merged**
