### PR TITLE
[5.1] Template-param-brand

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #37352 .

### Summary of Changes
Change the filter for brand to "options".

### Testing Instructions
see #37352.

### Actual result BEFORE applying this Pull Request
{"brand":"true",   in database after updating a template copy

### Expected result AFTER applying this Pull Request
{"brand":"1","  after updating a template copy

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 8f8406705421687cb565827abc9334a878070b91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41458">issues.joomla.org/tracker/joomla-cms/41458</a>.</sub>

**Comment by HLeithner** [comment]
I would like to clarify first what is "true" and what is "false", in joomla we have a bunch of diffrent implementation what means "false" as `string` `false` as boolean and `"0"` as `string` and `int` and `yes` or `no` at least it's not always handled the same. 

In this case saving a bool as 0 and 1 seems to be the right thing, problem could be using it in a different like
in this example https://3v4l.org/PSoL5

So we should check the complete codebase for inconsistency and find a solution normalize this. Pretty sure someone did this already and the PR has not been merged or has been closed or is still open don't know.

I bring this topic up in the next maintainer meeting.

For now I target this pr for 5.0.1

**Comment by Fedik** [comment]
I would suggets to stick with 1/0, for XML, and use `filter="INT"`
This is more safe. When the date is loaded from database again to the field, the field may not understand what is true/false, because it expect 1/0

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 8f8406705421687cb565827abc9334a878070b91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41458">issues.joomla.org/tracker/joomla-cms/41458</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41458">issues.joomla.org/tracker/joomla-cms/41458</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
