### PR TITLE
Update list-fancy-select.php

### PR DESCRIPTION
**Pull request by brianteeman**
replace tab with space

code review

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 09505e99d3638ae847eeae3c253949c272b08ede<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36543">issues.joomla.org/tracker/joomla-cms/36543</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09505e99d3638ae847eeae3c253949c272b08ede<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36543">issues.joomla.org/tracker/joomla-cms/36543</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
