### PR TITLE
UI/UX Review for com_installer discover view on mobile devices

### PR DESCRIPTION
**Pull request by zero-24**
see: #5628

This is a proposal UI/UX review on mobile for the install component view discover.
### Bevor this Patch

mobile_com_installer_discover_bevor
### After this Patch

mobile_com_installer_discover_after_new

### CODE REVIEW

**Comment by brianteeman** [comment]
So you think the date column is really useful. I'd prefer to have more
space for the name

**Comment by zero-24** [comment]
Yes you are right i will hide the date too Thanks,

**Comment by zero-24** [comment]
done @brianteeman https://github.com/joomla/joomla-cms/commit/5cd866715a52156df8d13ae1d841c73b280efe3d

**Comment by brianteeman** [comment]
Can you update the screenshot please

**Comment by zero-24** [comment]
done @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5670">issues.joomla.org/joomla-cms/5670</a>.</sub>

**Comment by brianteeman** [comment]
@test all good - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5670">issues.joomla.org/joomla-cms/5670</a>.</sub>

**Comment by waader** [comment]
@test success!

**Comment by zero-24** [comment]
Thanks to all moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5670">issues.joomla.org/joomla-cms/5670</a>.</sub>

**Pull request merged**
