### PR TITLE
Unused Joomla\cms\factory

### PR DESCRIPTION
**Pull request by brianteeman**
Joomla\cms\factory is not used in this file and can be safely removed.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 4438260eaa201e9d7f65570c8af0095d20920138<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38625">issues.joomla.org/tracker/joomla-cms/38625</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4438260eaa201e9d7f65570c8af0095d20920138<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38625">issues.joomla.org/tracker/joomla-cms/38625</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38625">issues.joomla.org/tracker/joomla-cms/38625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by brianteeman** [comment]
Please correct the milestone to 4.2.2

**Pull request merged**
