### PR TITLE
3.6.4: Correcting encoding mismatch for helpsites.xml

### PR DESCRIPTION
**Pull request by infograf768**
Changed the encoding of the file as `Français` was badly displayed.

@rdeutz 

You can merge. I am creating the same in joomlaupdate now.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 037bd4a523c71cf8c8803fb45517f6526c6d38be<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12507">issues.joomla.org/tracker/joomla-cms/12507</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 037bd4a523c71cf8c8803fb45517f6526c6d38be<br /><br />see #12515 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12507">issues.joomla.org/tracker/joomla-cms/12507</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12507">issues.joomla.org/tracker/joomla-cms/12507</a>.</sub>

**Comment by zero-24** [comment]
Implemented with: https://github.com/joomla/joomla-cms/commit/6f86ebb6b8dc163c368d474516cf17aef436c68f as this PR is broken anyhow.

**Comment by PhilETaylor** [comment]
wow - yeah something very very broken with this PR now :)

**Comment by mbabker** [comment]
It's because he changed the base branch and because JMs PR was based on the 3.6.4 branch it drug all the other commits from there over too.

**Comment by zero-24** [comment]
Yes i have changed the base so i can merge it into staging and not the 3.6.4 branch. Is there any better way instend of changing the base (that broken this PR)?

**Comment by mbabker** [comment]
Manually commit it (with proper author attributes).  It's like opening a PR designed for something in the 3.7.x branch against staging when your branch was branched from 3.7.x, the PR is going to show all the commits not in the target branch.  So similar thing here; the PR was against the 3.6.4 branch which has commits not in staging then you changed the base branch so it included those commits not in staging because JM branched from the 3.6.4 branch.

**Comment by zero-24** [comment]
> Manually commit it (with proper author attributes).

Ok thanks. And thanks for the help / explanation.

**Comment by mbabker** [comment]
The other way to think of it.  You're proposing to merge a remote branch into a base branch.  That remote branch has certain commits not in the base branch, and that is what you want to merge.  So when you change the base branch you want to merge that remote branch into, you're changing the commits you're proposing be merged potentially.

It's kinda how git works at the underlying layer.  You aren't explicitly sending a pull request for X commits.  GitHub's UI just does a great job showing that stuff.

**Comment by infograf768** [comment]
that was supposed to be mer ged in 3.6.4...

**Comment by zero-24** [comment]
George told me this should not go into 3.6.4

**Comment by infograf768** [comment]
He was mistaking. It had to go into 3.6.4. It is related to https://github.com/joomla/update.joomla.org/issues/27

@rdeutz  can make new packs with this change. It is not a big deal. I had already told him.

**Comment by PhilETaylor** [comment]
I thought 3.6.4 was resolving security issues only... Although this probably is a small change with no knock on effects, after all the other rush "just merge this because it will make no difference" when we release security releases have always come back to bite in the arse!

**Comment by rdeutz** [comment]
We decided not to merge it, all good.

**Comment by andrepereiradasilva** [comment]
mantainers please remove 3.7.0 label here

**Pull request closed without merging**
