### PR TITLE
[4.0] Add empty alt checkbox for tinyMCE dnd

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Adds the checkbox for specifying that an image is decorative (alt=""). Feature parity with the rest fields, etc

### Testing Instructions
Drag and drop an image in the tinyMCE, check or not the `No Description` checkbox (adding or not alt text) and observe the generated tag (just toggle the editor to do so)

### CODE REVIEW

**Comment by infograf768** [comment]
Called my shaman ( shawoman?): she entered into a transe, concentrated on the last mammoth hunt and collapsed, some code dripping from her twisted mouth...
Then, after recovering, she said : what the heck is that about?

**Comment by dgrammatiko** [comment]
@infograf768 https://github.com/joomla/joomla-cms/pull/31577#issuecomment-738743150

It either can be closed or someone needs to add the missing string here

**Comment by infograf768** [comment]
shawoman (shaman ?) said: title, description, testing instructions missing. Me go back to cavern and concentrate on cooking special poison to use on hunters arrows.

**Comment by dgrammatiko** [comment]
@infograf768 refresh... 😂

**Comment by brianteeman** [comment]
Thanks for doing this. I was looking at it this morning but ran out of time.

Can you also do this for the xtd-editor plugin please

**Comment by dgrammatiko** [comment]
@brianteeman I thought I did that already @ https://github.com/joomla/joomla-cms/pull/31425

**Comment by brianteeman** [comment]
@dgrammatiko sorry forgot you had done that

**Comment by Tejashrimajage** [comment]
I have tested this item :white_check_mark: successfully on 2fe56e37339ea48144663516a0f9973a45b1515b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by Tejashrimajage** [comment]
I have tested this item :white_check_mark: successfully on 2fe56e37339ea48144663516a0f9973a45b1515b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by Tejashrimajage** [comment]
I have tested this item :white_check_mark: successfully on 2fe56e37339ea48144663516a0f9973a45b1515b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 2fe56e37339ea48144663516a0f9973a45b1515b<br /><br />Done :)
Backend
Schermata 2020-12-05 alle 19 22 37

FrontEnd
Schermata 2020-12-05 alle 19 24 00
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by adj9** [comment]
I have not tested this item.<br /><br />sorry<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 2fe56e37339ea48144663516a0f9973a45b1515b<br /><br />done
backend
Schermata 2020-12-05 alle 20 17 37

Frontend
Schermata 2020-12-05 alle 20 19 21

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by infograf768** [comment]
TEST:

drop an image for the first time: all works fine.
delete image in tinyMCE textarea and try again OR drop the same image in another article:
Error: Conflict

Screen Shot 2020-12-07 at 09 04 35

The issue is that the image is already uploaded to the `images` folder

I am setting this back to pending as it is impossible to use the same image via drag and drop more than once (when it is not already present in the folder) and the error displayed is unclear.

**Comment by infograf768** [comment]
back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31578">issues.joomla.org/tracker/joomla-cms/31578</a>.</sub>

**Comment by dgrammatiko** [comment]
@infograf768 that issue is totally unrelated to this pr, I’ll try to make a pr for that case but not gonna do it here

**Comment by infograf768** [comment]
@dgrammatiko 
agree. Same error without this PR. merged. tks.

Please try to solve asap ;)

**Comment by brianteeman** [comment]
Thanks for merging this

**Pull request merged**
