### PR TITLE
Handle Google Font weights and styles in Protostar

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25972.

### Summary of Changes

Add handling for fonts with selected weight and styles.

### Testing Instructions

Edit Protostar template style
Enable `Google Font for Headings` option.
In `Google Font Name` field enter a font with specific weights/styles, e.g. `Open+Sans:400`.
Inspect heading fonts in frontend.

### Expected result

Headings use selected web font.

### Actual result

Headings use standard font.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 06efd3518e28caf07054274f7bf8f3557f163b09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25976">issues.joomla.org/tracker/joomla-cms/25976</a>.</sub>

**Comment by ghost** [comment]
@dioubernard please test (how to: https://docs.joomla.org/Testing_Joomla!_patches)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 06efd3518e28caf07054274f7bf8f3557f163b09<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25976">issues.joomla.org/tracker/joomla-cms/25976</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thanks for creating a better google font integration.

**Pull request merged**
