### PR TITLE
[4.0] fix Media Manager hidden alerts

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30880 #29152.

### Summary of Changes
Fixes hidden notification on multiple file uploads

### Testing Instructions
As in the issue

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 763854e461c08632510162ea6e9714215e00bfe6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32868">issues.joomla.org/tracker/joomla-cms/32868</a>.</sub>

**Comment by saumyasarkar11** [comment]
I have tested this item :red_circle: unsuccessfully on 763854e461c08632510162ea6e9714215e00bfe6<br /><br />It fails while mass upload and mass deletion as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32868">issues.joomla.org/tracker/joomla-cms/32868</a>.</sub>

**Comment by dgrammatiko** [comment]
> It fails while mass upload and mass deletion as well

That's unrelated to this PR

**Comment by saumyasarkar11** [comment]
> I have tested this item  unsuccessfully on [763854e](https://github.com/joomla/joomla-cms/commit/763854e461c08632510162ea6e9714215e00bfe6)
> 
> It fails while mass upload and mass deletion as well
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/32868](https://issues.joomla.org/tracker/joomla-cms/32868).

### While Uploading 4 files simultaneously:

Screenshot from 2021-03-26 18-26-30

### While Deleting 4 files simultaneously:

Screenshot from 2021-03-26 18-27-34

**Comment by saumyasarkar11** [comment]
And how about writing 'Item(s)' instead of 'Item' in the alert as it would refer to multiple uploads/deletions as well

**Comment by dgrammatiko** [comment]
@saumyasarkar11 how did you tested this PR?

You need to run `npm ci`

**Comment by saumyasarkar11** [comment]
I have tested this item :white_check_mark: successfully on 763854e461c08632510162ea6e9714215e00bfe6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32868">issues.joomla.org/tracker/joomla-cms/32868</a>.</sub>

**Comment by saumyasarkar11** [comment]
> @saumyasarkar11 how did you tested this PR?
> 
> You need to run `npm ci`

I 

> @saumyasarkar11 how did you tested this PR?
> 
> You need to run `npm ci`

Will keep this in mind whenever I see the "NPM Resource Changed" tag from the next time. Thank you @dgrammatiko

**Comment by saumyasarkar11** [comment]
> @saumyasarkar11 how did you tested this PR?
> 
> You need to run `npm ci`

Will keep this in mind whenever I see the "NPM Resource Changed" tag from the next time. Thank you @dgrammatiko

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32868">issues.joomla.org/tracker/joomla-cms/32868</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
