### PR TITLE
Fixed mistake after 11265

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Pull Request to fix mistake in comment after #11265 .
### Summary of Changes

`en-GB.mod_languages.ini` line 9
### Testing Instructions

Code review
### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 22372b25eed759f3ce881a8043c1cc3eb6115e59<br /><br />looks better now :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11641">issues.joomla.org/joomla-cms/11641</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 22372b25eed759f3ce881a8043c1cc3eb6115e59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11641">issues.joomla.org/joomla-cms/11641</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11641">issues.joomla.org/joomla-cms/11641</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11641">issues.joomla.org/joomla-cms/11641</a>.</sub>

**Comment by jeckodevelopment** [comment]
@zero-24  we marked it as RTC at the same time :)

**Comment by zero-24** [comment]
double RTC is better :P

**Comment by Hils** [comment]
**MOD_LANGUAGES_FIELD_DROPDOWN_DESC="If set to 'Yes', the content languages native names will display in a dropdown."**
Shouldn't 'languages' have an apostrophe (location dependent upon plural or singular) as it is possessive? (ie the names of the native languages)
Should I put this in a separate PR?

**Comment by jeckodevelopment** [comment]
Hey Hils,
Yes please, open a separate PR since this has been merged.

**Pull request merged**
