### PR TITLE
Fix update extracted files counter

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #21922 .

### Summary of Changes
During update, 4 counters are visible (percent complete, bytes read, bytes extracted and files extracted). Expected is that the values of all counters increase during the update.

This PR uses the cumulative total and not the extracted files count.

### Testing Instructions
Install the previous version of Joomla.
Install patch.
Then update to the current version.

or code review

### Actual result
The value of files extracted increases and decreases.

### CODE REVIEW

**Comment by ghost** [comment]
@manfredvdn @frostmakk please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by frostmakk** [comment]
Tested update from 3.9.4
My issue with this was that the counters keep on increasing long after the progress bar has reached 100%
This PR does not solve that.

**Comment by ghost** [comment]
@frostmakk please mark your test as unsuccessfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by frostmakk** [comment]
Not sure it would be correct to mark as unsuccessful, as long as the PR probably didn't address my view of the issue anyway.

**Comment by ghost** [comment]
@frostmakk if you have a different issue which isn't solved by this Pull Request and not reported yet please open a new Issue.

**Comment by Quy** [comment]
@frostmakk I will look into it and fix it here.

**Comment by Quy** [comment]
There is a discrepancy with the numbers thus affecting the progress bar.

joomlaupdate_totalsize = 12358245
stat_inbytes = 21167790

@HLeithner Do you know how the update total size is calculated?

**Comment by frostmakk** [comment]
I have tested this item :white_check_mark: successfully on 7abf0a86c666ba4d45ea86904f7b56cf904adbba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25198">issues.joomla.org/tracker/joomla-cms/25198</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5e50e37c05ded095a6fbddb8aaf2afd6a38af3f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25198">issues.joomla.org/tracker/joomla-cms/25198</a>.</sub>

**Comment by alikon** [comment]
since 1st test only branch merge so 2 tests
setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25198">issues.joomla.org/tracker/joomla-cms/25198</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
