### PR TITLE
[4.0] Calendar hide

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #34863 and #34791 .

### Summary of Changes

Make calendar hidden for non core template.

### Testing Instructions

Apply path, run `npm install`
Please follow #34863

### Actual result BEFORE applying this Pull Request
Calendar visible

### Expected result AFTER applying this Pull Request
Calendar hidden

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by angieradtke** [comment]
It works

**Comment by richard67** [comment]
@angieradtke Could you mark your test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/34871 ? Just use the "Test this" button at the top left corner, then select the right test result and submit. Thanks in advance.

**Comment by angieradtke** [comment]
I have tested this item :white_check_mark: successfully on d24a7422bafe88fc2a2312360509ab004ea8a187<br /><br />Works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34871">issues.joomla.org/tracker/joomla-cms/34871</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on d24a7422bafe88fc2a2312360509ab004ea8a187<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34871">issues.joomla.org/tracker/joomla-cms/34871</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34871">issues.joomla.org/tracker/joomla-cms/34871</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
