### PR TITLE
[4] Fix undefined classes in phpdoc

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

Fixes undefined class errors in files in phpdoc blocks
Screenshot 2022-01-13 at 18 31 45

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 90069b1c28cbfc20743c26f5a993d11ab0fbd718<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36671">issues.joomla.org/tracker/joomla-cms/36671</a>.</sub>

**Comment by ditsuke** [comment]
I have tested this item :white_check_mark: successfully on 90069b1c28cbfc20743c26f5a993d11ab0fbd718<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36671">issues.joomla.org/tracker/joomla-cms/36671</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36671">issues.joomla.org/tracker/joomla-cms/36671</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
