### PR TITLE
[Hathor] Send test mail button missing from config

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Added the new send test mail button to the global config in the hathor template
#### Testing Instructions

Apply patch, switch to the hathor template and check that the send test mail button is present and working in the global configuration

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 2e057e69ab3a4a38b3cec7b4b710f6743b4da20d<br /><br />Able to reproduce then #9824 works as expected: btn appears + works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9824">issues.joomla.org/joomla-cms/9824</a>.</sub>

**Comment by shubhamnba2009** [comment]
I have tested this item :white_check_mark: successfully on 2e057e69ab3a4a38b3cec7b4b710f6743b4da20d<br /><br />Button appears after applying the patch under global configuration server dialogue box and working too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9824">issues.joomla.org/joomla-cms/9824</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 2e057e69ab3a4a38b3cec7b4b710f6743b4da20d<br /><br />the button now exists in Hathor too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9824">issues.joomla.org/joomla-cms/9824</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9824">issues.joomla.org/joomla-cms/9824</a>.</sub>

**Pull request merged**
