### PR TITLE
Update en-GB.com_finder.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
"Filter New" means "Filter new items", while the command is for new filter creation. Also chaged "Filter Edit" to "Edit Filter" to make them looking similar.

### CODE REVIEW

**Comment by sovainfo** [comment]
In case of alpha sort it should be:
COM_FINDER_FILTER_MAP_COUNT="Nombre de plans"
COM_FINDER_FILTER_NEW_TOOLBAR_TITLE="Recherche avancée : Nouveau filtre"

**Comment by infograf768** [comment]
LOL, indeed

**Comment by Wilma999** [comment]
I have tested this item :white_check_mark: successfully on fa176d8d229e64153960fd02e38286a01f865819<br /><br />In component smart search the title has changed after applying the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by zero-24** [comment]
@aaleksanyants can you have a look at comments by @infograf768 and @sovainfo so we can get this in? Thanks @Wilma999 for your test :+1:

**Comment by aaleksanyants** [comment]
Thanks for notifying, I am OK with the suggestion by @infograf768 (what about the comment by @sovainfo, as I could understand, it is related to the French translation and has nothing to do with my fix), however I cannot know if why the title has chaged after applying the patch as @Wilma999 reports.

**Comment by MartijnMaandag** [comment]
I have tested this item :red_circle: unsuccessfully on fa176d8d229e64153960fd02e38286a01f865819<br /><br />In every component the text is different.
Category Manager: Add A New Contacts Category
Tags: New
I do think the text should be the menu-path to the item.
In this case: 
Smart Search - Search Filters - New

Maybe it is a good idea to check all the texts, decide what to use and implement it that way

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fa176d8d229e64153960fd02e38286a01f865819<br /><br />I understand @MartijnMaandag but I agree with this PR <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by brianteeman** [comment]
@aaleksanyants If you merge my PR https://github.com/aaleksanyants/joomla-cms/pull/4 then the sort order will be good and then this can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on fa176d8d229e64153960fd02e38286a01f865819<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by brianteeman** [comment]
Ooops Removed RTC still waiting for my patch to reorder the strings to be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Comment by infograf768** [comment]
it has not been alpha ordered yet.

**Comment by brianteeman** [comment]
No point waiting any longer - I have made a new PR with these edits and alpha ordered see #10513<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7879">issues.joomla.org/joomla-cms/7879</a>.</sub>

**Pull request closed without merging**
