### PR TITLE
Update en-GB.com_banners.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Replaced wrong word (probably taken from another file mechanically)

### CODE REVIEW

**Comment by brianteeman** [comment]
Good find. Thanks.

**Comment by Kubik-Rubik** [comment]
Thank you @aaleksanyants! Merged.

**Comment by aaleksanyants** [comment]
Why the status is "Closed with unmerged commits"?

**Comment by Kubik-Rubik** [comment]
We do not merge directly in GitHub, here is the commit: https://github.com/joomla/joomla-cms/commit/92cec05258cfdb9c4b715cb8deb4f4f3303ed1ed

**Comment by brianteeman** [comment]
It's the STUPID way it has been committed without any comment

**Comment by Kubik-Rubik** [comment]
@brianteeman Sorry, Brian, what do you mean with your statement?

**Comment by brianteeman** [comment]
That you didn't post anything to show that it had been committed.

Just saying closed with a ref is NOT obvious

**Comment by Kubik-Rubik** [comment]
I wrote "Thank you @aaleksanyants! **Merged.**" and I do not close the PRs manually but GitHub does it automatically because we add *Fixes ID* to the commit before we merge it (in the console)...

**Pull request closed without merging**
