### PR TITLE
[4.0] Enhance Update message

### PR DESCRIPTION
**Pull request by hardik-codes**
### Summary of Changes
Changed the update message (also made it a warning instead of a notice )so that users make backup before updating.

### Testing Instructions
Code Inspection

### Documentation Changes Required
None

### CODE REVIEW

**Comment by mbabker** [comment]
This is exactly what https://github.com/joomla/joomla-cms/pull/23229 is.  That PR is not yet merged to 4.0.

If a change has already been made on staging (3.x), it does not need a separate pull request for 4.0.  It will eventually merge forward as the backlog clears out.

**Comment by hardik-codes** [comment]
Ok then I'll close this

**Comment by hardik-codes** [comment]
@mbabker just had one question
Since naming convention for files have changed in J4
In J(3.x) we had ```view.html.php```whereas in J4 we have ```HtmlView.php```
Will that not make merging difficult?

**Comment by brianteeman** [comment]
That is why there is a backlog. But it's a waste of resources to do things twice

**Comment by mbabker** [comment]
> Since naming convention for files have changed in J4
> In J(3.x) we had `view.html.php`whereas in J4 we have `HtmlView.php`
> Will that not make merging difficult?

Depends on a lot of variables.  If files were all moved with git's move command, its history usually does a pretty good job of saying "this file has been moved, so apply this segment of the diff to the new location instead".  When things get too far diverged that's when you start running into problems with git not being able to sanely follow your renames.  I've redone the folder structure on an application just as large as Joomla and thanks to carefully moving files when I needed to merge changes for the live production system into the in-progress refactoring I usually only ran into problems where other changes had been made (such as splitting a large monolithic config resource into smaller files).

**Comment by hardik-codes** [comment]
ok got it 
I'm closing this PR

**Pull request closed without merging**
