### PR TITLE
[4.0] Jform docblock

### PR DESCRIPTION
**Pull request by brianteeman**
Update docblock to refer to Form and not JForm for namespaced files

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 1e8f2588f1850caf008d9dfad61fe574250fd419<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33033">issues.joomla.org/tracker/joomla-cms/33033</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1e8f2588f1850caf008d9dfad61fe574250fd419<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33033">issues.joomla.org/tracker/joomla-cms/33033</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33033">issues.joomla.org/tracker/joomla-cms/33033</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
