### PR TITLE
[5.3] Customfields: Also look at context when checking uniqueness

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #44154 .

### Summary of Changes
Customfields should only be uniquely named per context, so you should be able to have a field `test` in both articles and users. So far this is prohibited and you can only name a field uniquely system wide. This PR should fix that.

### Testing Instructions
Create a customfield with name `test` in articles and in users.

### Actual result BEFORE applying this Pull Request
Creating the second field is denied.

### Expected result AFTER applying this Pull Request
Both fields can be saved.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
The error message needs to be updated as currently it says
COM_FIELDS_ERROR_UNIQUE_NAME="Another Field has the same name (remember it may be a trashed item or it may be already present as a custom field in another extension)."

It can now be simplified and made more consistent with other strings eg
COM_FIELDS_ERROR_UNIQUE_NAME="Another Field has the same name (remember it may be a trashed item)."

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 58ccfe174e3f91fd221119bc70da3b4bef31f3eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44161">issues.joomla.org/tracker/joomla-cms/44161</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on 58ccfe174e3f91fd221119bc70da3b4bef31f3eb<br /><br />I tried to create a custom field in Content and Users with the same name.
It was not possible until I applied the patch.
Later on I used both the user field and the content field and each one kept its value and appeared in the correct place.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44161">issues.joomla.org/tracker/joomla-cms/44161</a>.</sub>

**Comment by laoneo** [comment]
@Hackwar can you also change the text in the mentioned string from @brianteeman?

**Comment by Hackwar** [comment]
Done

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44161">issues.joomla.org/tracker/joomla-cms/44161</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by laoneo** [comment]
Just for reference, this one has been reverted with #44462. Should probably be implemented in 6.0.

**Pull request merged**
