### PR TITLE
[4][cli] schema update check

### PR DESCRIPTION
**Pull request by alikon**
Partial Pull Request for Issue #40444  only the db schema part

### Summary of Changes

added the schema check

### Testing Instructions
see #40444

### Actual result BEFORE applying this Pull Request

N/A

### Expected result AFTER applying this Pull Request
Schema is checked and Update is not able to proceed if there is a  database structure issue

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I don't think this PR is sufficient. In the issue, the not matching schema version was just an example for causing a database error. But the check in the update component includes a complete schema check like it is executed when you go to the database checker in backend. The not matching schema version in the issue was just an easy example how to cause a schema error. But it is not the only possible error. E.g. when you add a new update SQL script to your installation which creates a new table, it would result in a schema error shown by the database checker, and this would block the update in the pre-update checker, too.

**Comment by alikon** [comment]
see #40468

should do all the schema checks
something like

image

**Comment by richard67** [comment]
@alikon See my comment in your new PR.

**Comment by alikon** [comment]
closing in favour of https://github.com/joomla/joomla-cms/pull/40468

**Pull request closed without merging**
