### PR TITLE
[5.1] Update TinyMCE to 6.8.4

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Updating TinyMCE to 6.8.4 to fix two XSS vulnerabilities, see:
https://www.tiny.cloud/docs/tinymce/6/6.8.4-release-notes/

### Testing Instructions
Apply patch, run npm install to download the updated Tiny version, test the editor.

### CODE REVIEW

**Comment by brianteeman** [comment]
when you did the upgrade and npm i then you should have seen that the xml file for tinymce was updated as well - same as with https://github.com/joomla/joomla-cms/pull/42240

**Comment by SniperSister** [comment]
Thanks @brianteeman !

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cb9674607c712a0aab7a1a8199723be49320acdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43808">issues.joomla.org/tracker/joomla-cms/43808</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cb9674607c712a0aab7a1a8199723be49320acdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43808">issues.joomla.org/tracker/joomla-cms/43808</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
