### PR TITLE
[4.0] Adds deprecated messages to the getInstance functions for the model and controller

### PR DESCRIPTION
**Pull request by laoneo**
- Adds a deprecated message to the BaseController::getInstance function and deprecates it for 5.
- Adds a deprecated message to the BaseDatabaseModel::getInstance function and deprecates it for 5.

### CODE REVIEW

**Comment by mbabker** [comment]
Please add inline `JLog` or `@trigger_error()` calls as well so these get logged.

**Comment by laoneo** [comment]
Added

**Comment by brianteeman** [comment]
As this is changing the deprecated from 4 to 5 shouldnt the deprecated notice in staging be updated as well

**Comment by laoneo** [comment]
Not before 3.10 as we don't have the factory available in staging yet. But we need to discus the backporting anyway as with the DI and service locator story things became a bit different.

**Comment by wilsonge** [comment]
We should change the notice from 4 to 5 in staging, whether people can transition from 3.10 or not

**Pull request merged**
