### PR TITLE
[4.0] missing legend [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
A fieldset should have a legend.

> The first element inside the fieldset must be a legend element, which provides a label or description for the group

This adds a missing legend to the fieldset on the first tab of most edit pages where the joomla.edit.global layout is used.

This legend is set to visually-hidden so you will need to view source (or use assistive technology) to test

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 71347340a6d5560fcc0185a4f7ee491e5a23bfa3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33785">issues.joomla.org/tracker/joomla-cms/33785</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 71347340a6d5560fcc0185a4f7ee491e5a23bfa3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33785">issues.joomla.org/tracker/joomla-cms/33785</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33785">issues.joomla.org/tracker/joomla-cms/33785</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
