### PR TITLE
[5.2] Guided Tours: How to Create Articles Updated Language

### PR DESCRIPTION
**Pull request by sdwjoomla**
Updated the step descriptions for How to Create Articles to provide more information for new users.

Pull Request for Issue # .

### Summary of Changes

- Updated How to Create Articles steps in the com_guidedtours.sys.ini file
- Added SQL files to change the position of the category step with language string title COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_CATEGORY_TITLE
- Updated installation/extensions.sql file

### Testing Instructions
Using a Joomla 5.0 instance, click _Take a Tour > How to Create Articles?_

### Actual result BEFORE applying this Pull Request
**Step 1: How to create articles**

**Step 2: Select the 'New' Button**

**Step 3: Add a title for the article**

**Step 4: Enter an alias**

**Step 5: Add content**

**Step 6: Select the status**

**Step 7: Select a category**

**Step 8: Toggle featured**

**Step 9: Set the access level**

**Step 10: Add tags**

**Step 11: Add a note**

**Step 12: Add a version note**

**Step 13: Select 'Save and Close'**

**Step 14: Congratulations**

### Expected result AFTER applying this Pull Request
**Step 1: How to create articles?**

**Step 2: Create a New Article**

**Step 3: Add a Title for the Article**

**Step 4: Generate or Add the Article Alias**

**Step 5: Add Your Content**

**Step 6: Set the Article Status**

**Step 7: Select Article Category**

**Step 8: Feature the Article**

**Step 9: Set Article Access Level**

**Step 10: Add One or More Tags**

**Step 11: Add a Note**

**Step 12: Add a Version Note**

**Step 13: Save and Close**

**Step 14: Congratulations!**

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in favour of this change. It breaks multiple guidelines for the UI. Specifically https://manual.joomla.org/docs/user-interface-text/#notes

**Comment by sdwjoomla** [comment]
Thank you @brianteeman  for taking a look at the PR. The link provided speaks to "Avoid Over Communications" which does not apply in this case as it falls more within the documentation area. The intended audience would need the extra information that the updated language provides.

**Review by obuisard — APPROVED** [review]

**Review by HLeithner — CHANGES_REQUESTED** [review]
Can't merged this till the translations has been moved out of the sys.ini file as mentioned here https://github.com/joomla/joomla-cms/pull/40606#issuecomment-1596273139

**Comment by brianteeman** [comment]
I guess you only tested these changes at a large screen resolution. At 1280x720 for example it no longer works because the text is so long the popup covers the input (or worse posint to the wrong input)


https://github.com/joomla/joomla-cms/assets/1296369/b53f875b-af06-4613-9a15-ea6800c80111

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 57714423eabc2bdb8490827132000e22c0cc02fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41046">issues.joomla.org/tracker/joomla-cms/41046</a>.</sub>

**Comment by sdwjoomla** [comment]
@brianteeman was done on a laptop. The SQL changes are changes in position to address overlay issues.
Resetting the PR to draft until the language change issues noted by @HLeithner are resolved.

**Comment by brianteeman** [comment]
> @brianteeman was done on a laptop. The SQL changes are changes in position to address overlay issues.

that;s why I made the video

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by web54** [comment]
tried and failed : 
image
image
and so on ...

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by sdwjoomla** [comment]
Closing PR - will work with the GT team to implement in the future.

**Pull request closed without merging**
