### PR TITLE
[4.0] Help scroll top

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue # .

Summary of Changes

Added 'onclick' => 'window.scroll(0,0)' to Administrator Joomla! Help page

Testing Instructions

Go to Administrator / Help / Start Here panel / Joomla! Help
Scroll down to the bottom of the list and click an item there

Actual result BEFORE applying this Pull Request

Nothing appears to happen because the Iframe with the Help page has changed out of site.

Expected result AFTER applying this Pull Request

The page scrolls to the top and the new Help page is seen

Documentation Changes Required

None

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on e75acd1bcf1cf8133e356252462ad7bca2fca29c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on e75acd1bcf1cf8133e356252462ad7bca2fca29c<br /><br />__<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by dgrammatiko** [comment]
Inline javascript should be avoided, `onclick` is a potentially XSS

**Comment by richard67** [comment]
Back to pending due to previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by ceford** [comment]
> Inline javascript should be avoided, onclick is a potentially XSS

I read that somewhere. But there are 170 instances of onclick in the administrator/components ... what should I do?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by sandewt** [comment]
>I read that somewhere. But there are 170 instances of onclick in the administrator/components ... what should I do?

Maybe so: `OutputFilter::ampReplace` ???

See example:

https://github.com/joomla/joomla-cms/blob/7cd0361e0ac492a14dadd920decf50d2a5e83c67/modules/mod_menu/tmpl/default_url.php#L69

OR ???

```
use Joomla\CMS\Factory;

/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = Factory::getApplication()->getDocument()->getWebAssetManager();

// Add inline JavaScript
$wa->addInlineScript('
    document.addEventListener("DOMContentLoaded", function(event) {
        alert("An inline JavaScript Declaration");
    });
');

```

See [https://docs.joomla.org/J4.x:Http_Header_Management](https://docs.joomla.org/J4.x:Http_Header_Management)

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e75acd1bcf1cf8133e356252462ad7bca2fca29c<br /><br />non-sanitised inline scripts are not safe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33644">issues.joomla.org/tracker/joomla-cms/33644</a>.</sub>

**Comment by hans2103** [comment]
> > Inline javascript should be avoided, onclick is a potentially XSS
> 
> I read that somewhere. But there are 170 instances of onclick in the administrator/components ... what should I do?
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/33644](https://issues.joomla.org/tracker/joomla-cms/33644).

replace them all with `<button></button>` ? Most of them shouldn't be an `<a></a>`. And start with this one...

**Comment by ceford** [comment]
I remembered where I read about not using onclick and the like - it is in CSP documentation. Closing this - I may come with a CSP compliant implementation.

**Pull request closed without merging**
