### PR TITLE
[#33965] Update the ImageManager js object

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
- No dependence on Mootools
- Support both jQuery and Mootools version of Chosen (whichever is
  installed will just work)
- Remove/consolidate unneeded/repetitious code
- Fix bugs such as uninitialized variables

Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33965&start=0
## test instructions

This file is used only by the 'images' view of com_media which is used inside an iframe in a modal dialog when the 'Image' button is clicked under an editor. So this can be tested on any page that uses an editor such as the 'Edit Article' page. The script manages such things as changing directories (using the select or the 'up' button) and it handles generating the img tag (or figure tag set) and inserting into the editor. So you can test that those functions are behaving as usual.

### CODE REVIEW

**Comment by Chalkin** [comment]
@test
Joomla 3.4.0
Google Chrome 40.0.2214.111 Mac
with com_articles - New Article

**OK:**
- Browsing through folders -> OK
- Using "UP" Button -> OK
- Selecting Image -> OK
- Image Path is applied to field "Image URL" after selecting -> OK
- Selecting Image and Inserting into Joomla Article -> OK

**Error:**
- On browsing through folders the directory path is not changing like it did without the patch
screen shot 2015-03-06 at 16 00 56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3919">issues.joomla.org/joomla-cms/3919</a>.</sub>

**Comment by okonomiyaki3000** [comment]
@chalkin is this not fixed by #5077 ?

**Comment by Chalkin** [comment]
@okonomiyaki3000 the fix from #5077 is already applied in joomla 3.4.0 - but it's not fixing the problem with the current directory not showing up.

Specific:
administrator/components/com_media/models/manager.php Line 104
```
$asset = htmlspecialchars(json_encode(trim($input->get('asset', 0, 'cmd'))));
```

**Comment by peterpeter** [comment]
In this modal window, when I switched in a subfolder and upload an image it is allways stored in the images root folder, no matter in wich subfolder I actually am. This happend with and without this patch in J-3.4. As this behaviour is not in J-3.3.6, it seems to be a 3.4 bug. 

@okonomiyaki3000 
I've searched a while and found this bug not reported so far, so you can smash another bug with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3919">issues.joomla.org/joomla-cms/3919</a>.</sub>

**Comment by roland-d** [comment]
@okonomiyaki3000 Could you please have a look at the issues mentioned? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3919">issues.joomla.org/joomla-cms/3919</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Rebased with latest staging but couldn't reproduce the bug. Everything is working perfectly in Chrome. @Chalkin @peterpeter , what browsers are you guys using?

**Comment by okonomiyaki3000** [comment]
Ah, you are using Chrome. Well, I can't imagine why you got this error. Any messages in Chrome's console?

**Comment by Chalkin** [comment]
I'm using chrome on mac (current chrome) - I will check in the evening if the problem still exists since it's been a while.

**Comment by peterpeter** [comment]
I've used FF on windows....I check it later on too, with different browsers

**Comment by anibalsanchez** [comment]
I have reproduced the reported issue.

If you navigate to a subfolder and upload an image, it works Ok.

However, if you choose a subfolder from "Directory", it shows the subfolder. But, when you upload an image, it is saved in / and jumps to /.

**Comment by okonomiyaki3000** [comment]
Thanks! That might help. I'll try it tomorrow.

**Comment by okonomiyaki3000** [comment]
Thanks for your help guys, this should fix it. The problem was that, in some cases a url was getting double encoded. There's an iframe that contains the current directory list and it gets changed when changing directories. This can happen by a link (clicking a folder in the list) which worked fine because it was a perfectly "natural" process. It can also happen by javascript (a result of using the folder select or 'up' button). The javascript way had a problem because I was forming the query string part of the url by using JQuery's `$.param()` function. That function is pretty convenient and even does url encoding automatically. You'd think that would be perfect but then the next step is to assign the url to `frame.location.href`. You might not know this (I didn't) but assigning a url to `location.href

**Comment by anibalsanchez** [comment]
@text OK

**Comment by okonomiyaki3000** [comment]
conflicts, eh? We'll see about this...

**Comment by okonomiyaki3000** [comment]
Rebased with staging. Should merge now.

**Comment by okonomiyaki3000** [comment]
@anibalsanchez I think you meant to say @test OK

**Comment by anibalsanchez** [comment]
Ahhh fat fingers!!! @test OK

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on 95a3099f352d190c97938dcd1d5a37b03fec6c7f<br /><br />Tested successfully on Chrome / Os X<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3919">issues.joomla.org/joomla-cms/3919</a>.</sub>

**Comment by zero-24** [comment]
@okonomiyaki3000 can you fix merge conflicts? Than we can RTC based on @designbengel and @anibalsanchez 's tests :smile:

**Comment by dgt41** [comment]
This can be easily fixed by a commiter:
remove JHtml::_('script', 'media/popup-imagemanager.min.js', true, true); from administrator/components/com_media/views/images/view.html.php and push just the scripts

**Pull request closed without merging**
