### PR TITLE
[4.0] installer missing language string

### PR DESCRIPTION
**Pull request by brianteeman**
as reported by @pe7er #26620 with the code from @infograf768

Sorry no idea how to replicate the bug

### CODE REVIEW

**Comment by wilsonge** [comment]
To replicate just install Joomla with no internet connection. You get the message displayed when you load the Joomla is installed successfully page (as that's the point where we load all the language packs update sites)

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 38f4b69464bf2542678d13eee543449e910e62c7<br /><br />After patch when installing Joomla with no internet connection message now shows as translated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26732">issues.joomla.org/tracker/joomla-cms/26732</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 38f4b69464bf2542678d13eee543449e910e62c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26732">issues.joomla.org/tracker/joomla-cms/26732</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26732">issues.joomla.org/tracker/joomla-cms/26732</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by pe7er** [comment]
> Sorry no idea how to replicate the bug

You have to take the train from Nijmegen to Utrecht and near train station Ede-Wageningen, try to install Joomla 4 alpha on your laptop :-)

> To replicate just install Joomla with no internet connection. 

Yes, indeed. I got the message when I installed it while traveling on the train.
Apparently the internet connection was a bit wonky.

@brianteeman Thanks for fixing it.

**Pull request merged**
