### PR TITLE
[4.0] Prevent two messages displayed for creating override

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #31894.

### Summary of Changes
This small PR fixes the issue https://github.com/joomla/joomla-cms/issues/31894. It prevents two messages displayed when override is created in the template

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/31894 , confirm the issue
2. Apply patch, try again. Now only one message is displayed.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9ef04d78dd194d932a3dcbc435b76bcf320569ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32340">issues.joomla.org/tracker/joomla-cms/32340</a>.</sub>

**Comment by infograf768** [comment]
I would also delete the string
`COM_TEMPLATES_OVERRIDE_SUCCESS="Override created."`

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8287379536b9c1eafa640769d8011170f79450d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32340">issues.joomla.org/tracker/joomla-cms/32340</a>.</sub>

**Comment by infograf768** [comment]
Rtc as last change was OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32340">issues.joomla.org/tracker/joomla-cms/32340</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
