### PR TITLE
[JAccess] Calculate if user is super user using JAccess preloading (3.7.x)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR aims to improve performance in super user calculation by taking advantage of asset access preloading.

The following tests were made with a super user logged in frontend homepage in sample multilingual site.
### Before

image
### After

image
### Testing Instructions
1. Code review.
2. Apply patch on 3.7.x branch.
3. Login and logout with a super user and without a superuser.
4. Check if super user permissions are ALWAYS correctly identified in all circunstances.

Note: Please test this careful as this is the super user permissions ...
### Documentation Changes Required

None.

mantainers please confirm the root asset is always called `root.1` and id is always `1`

### CODE REVIEW

**Comment by zero-24** [comment]
Also after the patch I get 28 Queries logged and on afterRender is not changed here? I'm confused.

**Comment by andrepereiradasilva** [comment]
sorry @zero-24 we need to add the "root.1" asset to avoid the 3 queries.

**Comment by zero-24** [comment]
Works now (i can see there are just 25 queries and less memory usage)

but how can i test this:

>Check if super user permissions are ALWAYS correctly identified in all circunstances.

Any special or just navigate the backend?

**Comment by andrepereiradasilva** [comment]
for instance, you need to create some users assigned to several grups give some of them super user permissions, other not, log with them and check if the ones that should be superusers are super users, the others not.

**Comment by zero-24** [comment]
ok it is on my list for tomorrow :smile: Thanks!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 0ab3410bbf42f84c56a817a29e4201a3faca35a9<br /><br />ok it was not exact tomorrow :smile: But it looks ok on my site. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12066">issues.joomla.org/tracker/joomla-cms/12066</a>.</sub>

**Comment by andrepereiradasilva** [comment]
not needed anymore, https://github.com/joomla/joomla-cms/pull/12809 takes care of this in another way

**Pull request closed without merging**
