### PR TITLE
Correct access checks for Categories Quick Icon

### PR DESCRIPTION
**Pull request by sanderpotjer**
Pull Request for Issue # .

### Summary of Changes
For the "Article Categories" quick icon on the dashboard the incorrect access checks are made. Right now the permission is checked against `com_categories`, which is not a valid asset in Joomla. As the icon links to the Article categories the correct permission check should be made against `com_content`. This PR implements this.

### Testing Instructions
1. Create a new user group with "Public" as the parent user group. Allow actions "Administrator Login", "Access Administration Interface" and "Create" in the Global configuration. 
2. Login with as test user assigned to this new user group only and confirm that "Articles" and "Article Categories" are visible in the control panel. 
Screenshot 2021-09-17 at 16 06 25

3. Now go to the component options of the article manager and set "Access Administration Interface" and "Create" to denied for the test user group. 
4. Go back to the control panel with the test user and confirm that "Article Categories" is still visible, clicking on the icon will give an `403 You don't have permission to access this.` error.
Screenshot 2021-09-17 at 16 09 33

5. Apply patch.
6. Go back to the control panel with the test user and confirm that "Article Categories" is no longer visible.
Screenshot 2021-09-17 at 16 22 04

7. Go to the component options of the article manager and set "Access Administration Interface" and "Create" to inherited (so allowed) for the test user group.  
8. Go back to the control panel with the test user and confirm that "Articles" and "Article Categories" are both visible in the control panel.

### CODE REVIEW

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Review by Hackwar — APPROVED** [review]
Codereview. This is good.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on fa9c7e3c7d02f6920ac3efdd73a4ee774ff4b633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35584">issues.joomla.org/tracker/joomla-cms/35584</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35584">issues.joomla.org/tracker/joomla-cms/35584</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
