### PR TITLE
CodeMirror 4.11

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Seems that 4.10 didn't fix the FireFox bug so there is 4.11 which supposedly does fix it.

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
Thank you for updating the library, @okonomiyaki3000!

Changelog: http://codemirror.net/doc/releases.html

Should be merged for Joomla! 3.4 release!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5700">issues.joomla.org/joomla-cms/5700</a>.</sub>

**Comment by brianteeman** [comment]
@test applied patch and tested in chrome and firefox as that is where there was an issue. All seems ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5700">issues.joomla.org/joomla-cms/5700</a>.</sub>

**Comment by zero-24** [comment]
Thanks for testing und the code moving to RTC!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5700">issues.joomla.org/joomla-cms/5700</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @okonomiyaki3000 for the PR and all other for testing!

**Pull request merged**
