### PR TITLE
a11y improvement for contact form

### PR DESCRIPTION
**Pull request by brianteeman**
Generally speaking all images should have an alt tag and the alt tag must be meaningful and preferably unique for that image. Its also best practice not to use the words image or photo in the alt tag or a screen reader will end up with saying something like "image of contact image".

If you add an image to a contact then we automatically add an alt tag from the language string of "Contact Image". This fails a11y as it is neither unique to the image and contains the word image.

This simple PR changes that so the alt image is created from the Contact Name instead.
### Testing Instructions

Create a contact with an image and create a menu link to it.

Before this PR the alt tag for the image will be "Contact Image"
After applying this PR the alt tag for the image will be the name of the contact

### CODE REVIEW

**Comment by bhavikTailored** [comment]
- I have tested successfully.
- I have attached screen shot.
- screen shot 2016-08-28 at 23 49 34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 792fddc435954c813aea6642bc75f3e20c2a48a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by BhaveshTailored** [comment]
- As per you testing Instructions before patch alt="Contact Image" and after patch alt="Contact".
- So, I have tested  successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 792fddc435954c813aea6642bc75f3e20c2a48a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 792fddc435954c813aea6642bc75f3e20c2a48a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by killoltailored** [comment]
I have tested with Joomla! 3.6.3-dev Development [ Noether ] 5-August-2016 00:32 GMT 

screen shot 2016-08-29 at 00 14 19

screen shot 2016-08-29 at 00 14 33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 792fddc435954c813aea6642bc75f3e20c2a48a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by truptikagathara** [comment]
Sorry, I do not see RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11822">issues.joomla.org/joomla-cms/11822</a>.</sub>

**Comment by brianteeman** [comment]
Thanks everyone

**Pull request merged**
