### PR TITLE
Missing enough INFO on FAILED component installation

### PR DESCRIPTION
**Pull request by bygiro**
.

### CODE REVIEW

**Comment by Hackwar** [comment]
Please update your PR to latest staging and fix the merge conflicts.

**Comment by bygiro** [comment]
what "PR" stands for?

**Comment by Hackwar** [comment]
Pullrequest. This thing that you are looking at right now. :wink:

**Comment by roland-d** [comment]
@bygiro Can you redo this pull request or shall I find someone else to do it? Thanks.

**Comment by KingLouis1** [comment]
I have tested this item :red_circle: unsuccessfully on f7db062a89d41689abf16fc07f60665cb727a6fc<br /><br />Patch could not e loaded 

Error

The patch could not be applied because the repository is missing
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4199">issues.joomla.org/joomla-cms/4199</a>.</sub>

**Comment by zero-24** [comment]
As we can't merge this PR (deleted repo) and the current installer code throws exections instend use abort i'm going to close here. Thanks.

**Pull request closed without merging**
