### PR TITLE
com_languages installed view, implement searchtools and ordering

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the search tools (filte, order, etc) to com_languages installed view.

Other small code changes/improvements where made.

Please notice that now, since the client filter is incorporated in the "installed" view (just like in modules view), the two options in the left bar for this doesn't make much sense.
I will make another PR to propose a change to that.
###### Before PR

com_languages-installed-beforepr
###### After PR

image
#### How to test
1. Install latest staging and apply this patch
2. Go to Extensions -> Languages -> Installed - Site and Installed - Administrator
3. Check if everything is working fine.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
travis? where are you?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 15c43b90bbb69e250b4cec113604b9bf357059a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Client filter works now on mobile too.

image

**Comment by infograf768** [comment]
@andrepereiradasilva 
I am not in favor of changing "Language" to "Native Title". This is reserved to the content languages.
We ask TTs to always use English first in the <name> tag
For example: `<name>Persian</name>`

Also, as you are there, please add the nowrap class here
```
					<th class="nowrap">
						<?php echo JHtml::_('searchtools.sort', 'COM_LANGUAGES_HEADING_LANG_TAG', 'language', $listDirn, $listOrder); ?>
					</th>
```

**Comment by andrepereiradasilva** [comment]
Ups, that was not intentional.
Will correct later.

For UX and coherence should be the same as  "Install Languages" right?
Picture:
image

**Comment by infograf768** [comment]
For the heading only, yes. (once you correct the installer to change Language Code to Language Tag)

The rows in the Installer language come from http://update.joomla.org/language/translationlist_3.xml where the last _xx-XX is taken off and underscore are changed to spaces (example Arabic Unitag)

**Comment by andrepereiradasilva** [comment]
@infograf768 ok will check later

BTW, not to do with this PR and i'm not expert on how the languages show be named, but IMHO shouldn't the "name" of the language in the XML files have some kind of normalization?

I mean, for instance, "English" "name" is 3 times in that XML for different languages ... en-CA, en-AU and en-US, shouldn't it be something like this:
- "English (Canada)" or Canadian English
- "English (United States)" or American English
- "English (Australia)" or Australian English?
Another example is "FrenchCA". Why not "French (Canada)" or Canadian French?

**Comment by infograf768** [comment]
concerning the names of the languages: as i said,they depend on the project name on jomlacode. I will check if it is BC to change them.

**Comment by andrepereiradasilva** [comment]
@richard67 @infograf768 can you test now?

Latest preview:
image

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9b2132c79f21115079a3790edffd7e3b6972eddb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 sorry for that, but i decided to add some aditional checks:

Now on client change resets the search box, ordering and limit.
Also only allow client_id parameter to be 0 or 1 (even if send by POST or GET).

**Comment by infograf768** [comment]
@andrepereiradasilva 
As the Version is displayed when reducing the window, you should take off hidden-phone from the heading here:
```
					<th class="nowrap center hidden-phone">
						<?php echo JHtml::_('searchtools.sort', 'COM_LANGUAGES_HEADING_VERSION', 'version', $listDirn, $listOrder); ?>
					</th>
```

**Comment by andrepereiradasilva** [comment]
Yes you're right. Will change it later.

**Comment by richard67** [comment]
@andrepereiradasilva I'll wait for these changes before testing again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
of course.

**Comment by sandstorm871** [comment]
screen shot 2016-02-12 at 07 39 38

Testing this, I notice that when in XS size, switching between admin/site languages, the dropdown field for administrator is not displaying correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by infograf768** [comment]
That one is easy to solve.
Just introduce a min-width: 220px; in the new layout file

ROOT/administrator/components/com_languages/layouts/joomla/searchtools/default.php

**Comment by andrepereiradasilva** [comment]
i think it's all done now. Pleqase retest.
xs size preview:
image

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c0083aaad383e41e9e306d95ecf2a7ca9c5f7b20<br /><br />Success. XS mobile view is OK now, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by sandstorm871** [comment]
I have tested this item :white_check_mark: successfully on c0083aaad383e41e9e306d95ecf2a7ca9c5f7b20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 i think you forgot the "RTC" label in this one.

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 825d3262b11ef110ab8f941f0d2d0a95446d2e5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 @sandstorm871 please don't test. it seems that is a problem with my branch.
When ok i will say so. Thanks.

Anyway the goal of the change is just to resolve conflicts in a language variable file after #9099 merge.

**Comment by richard67** [comment]
@andrepereiradasilva OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by infograf768** [comment]
Setting back to pending until new tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva Is this ready for new tests now? Or shall we wait for further commits?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
sorry, yes it's ready. I messed up my branch yesterday, but it's solved now.

**Comment by richard67** [comment]
Better a messed up br**a**nch than a messed up br**u**nch :smile: (I like games with words)

I'll test it soon.

**Comment by richard67** [comment]
@andrepereiradasilva I have a problem but wanna ask you if you can replicate this before I mark my test result as negative.

I have 3 languages installed: The standard English, then German, then Russian.

I ordered the installed languages in a way (admin or site does not matter) that English was on top, and then entered "English" in the search box.

Result: Beside the English language also the German was found, but it does nowhere contain the text "english".

See following screenshot:

screen shot 2016-02-16 at 04 29 57

The russian language is not shown within the results, which is OK.

When I do a search for "German", it only finds "German" => OK.

Any idea why this can happen?

Maybe it is because English was on top of the list? Or because English is a kind of default?

Maybe a bug in the search tools so not related to your PR?

Let me know if you have an idea what it is and if it could be related to your PR or not, so I can mark my test result.

Everything else was working as desired.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i will check later. thanks for all your testing.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7ae20364fd32d4c232a59aa24ac8b46e9891e499<br /><br />Works as well as with the last test plus the search does not go through the package descriptions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by sandstorm871** [comment]
I have tested this item :white_check_mark: successfully on 7ae20364fd32d4c232a59aa24ac8b46e9891e499<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9101">issues.joomla.org/joomla-cms/9101</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Comment by wilsonge** [comment]
Oops - missed some of the files first commit - the missing ones are added here: https://github.com/joomla/joomla-cms/commit/f4643822bb7d455801d70ee20e49bea4ef2bd6a9

**Comment by infograf768** [comment]
Urgent, this broke 2 merged PR
https://github.com/joomla/joomla-cms/pull/9159

**Pull request closed without merging**
