### PR TITLE
Replacement of Austrian Flag

### PR DESCRIPTION
**Pull request by imanickam**
The current Austrian flag (de_at.gif) is a Service/State flag used in the Government buildings and officials.  The Civilian flag does not the insignia in the middle.  So, a new flag image has to be used in the place of the current Flag.

Pull Request for Issue # .

### Summary of Changes

Basis of change:
Forum Post - https://forum.joomla.org/viewtopic.php?f=711&t=952006

Content of the post:
-----------------------------
Hi Joomla! team!

Thank you for the multi language module!
In order to help improving Joomla! I want to inform you, that the flag icon for Austria (de_at.gif) is not correct:
According to Austrian laws the flag having the eagle crest on it may be used by i.e. governmental institutions only (see §4 in [url]https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10000782[/url]).
Instead you should use the national flag of Austria without the crest on it; this may be used by anyone else.
Here is an example:
https://de.wikipedia.org/wiki/Flagge_%C3%96sterreichs#/media/File:Flag_of_Austria.svg
According to the Federal Ministry of Defense the color for the red parts of the flag shall be:
http://encycolorpedia.com/ed2e38
More important information about the use and look of the Austrian flag you can find here (in German):
http://www.laenderservice.de/flaggen/europa/oesterreich.aspx

Please consider this in your next Joomla! update - thank you!

Kind regards,
Gerald
-----------------------------

Based on the contents in the links provided, the Civilian flag has to be used in the place of Service Flag.

### Expected result

The current Austrian Flag image file (de-at.gif) will be removed and its place the revised Austrian Flag image file will be added.

### CODE REVIEW

**Comment by brianteeman** [comment]
Why are you not replacing it now in this pr?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 15b2b1e7f6cce1a4ab47aa5bb4a52c2a4d234c58<br /><br />Flag is same as before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16800">issues.joomla.org/tracker/joomla-cms/16800</a>.</sub>

**Comment by imanickam** [comment]
When I tried to upload a file, I got the message that my permissions does not allow uploading.

So, I thought of deleting and adding the revised image file.
de_at

**Comment by brianteeman** [comment]
That's because you are using the github web site to try an upload an image to Joomla which correctly you don't have permission to do.

Simply go the Joomla repo in your own account, select this branch (patch-4) and you can upload the image and it will automatically update this.

**Comment by brianteeman** [comment]
@franz-wohlkoenig patch tester will not delete files

**Comment by mbabker** [comment]
> @franz-wohlkoenig patch tester will not delete files

More specifically, binary file support in patch tester is experimental at best.  It just has more quirks compared to handling plain text files.

**Comment by brianteeman** [comment]
I was keeping it simple :)

**Comment by franz-wohlkoenig** [comment]
@brianteeman i thought PR changes Flags.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f862d11baff2daed63cb8f0fdba09b2ba6c0fdb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16800">issues.joomla.org/tracker/joomla-cms/16800</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig it didn't but it does now :)

**Comment by imanickam** [comment]
Thanks Brian for the guidance.  I have done the changes accordingly.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f862d11baff2daed63cb8f0fdba09b2ba6c0fdb5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16800">issues.joomla.org/tracker/joomla-cms/16800</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@rdeutz 
can we get that into 3.7.3?

**Pull request merged**
