### PR TITLE
[4.0] Fix setError call

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
**setError** method only accept one parameter but on some calls, we are passing two parameters to it. This PR just fixes that small error.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
@joomdonation Where can we see that the function accepts only 1 parameter, i.e. where is it defined?

**Comment by joomdonation** [comment]
@richard67 See https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Object/CMSObject.php#L236

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e9065b481b2a906640bc59856659bed9298145f2<br /><br />Code review: As far as I could see, this PR covers all cases with the wrong 2nd parameter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33302">issues.joomla.org/tracker/joomla-cms/33302</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e9065b481b2a906640bc59856659bed9298145f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33302">issues.joomla.org/tracker/joomla-cms/33302</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33302">issues.joomla.org/tracker/joomla-cms/33302</a>.</sub>

**Pull request merged**
