### PR TITLE
Revert "Added check for menu router, when adding in a default itemid."

### PR DESCRIPTION
**Pull request by rdeutz**
Reverts joomla/joomla-cms#16197

Reverting because it lets unit tests fail

### CODE REVIEW

**Comment by mbabker** [comment]
@rdeutz You reverted 2 commits here...

**Comment by rdeutz** [comment]
I reverted the PR, I just pressed the revert button

**Comment by rdeutz** [comment]
**Strage**

**Comment by infograf768** [comment]
The .diff shows that only the menu PR is reverted here.

**Comment by mbabker** [comment]
The other commit's empty.  Since this PR passed Travis, I just manually ran the revert on command line and pushed it at https://github.com/joomla/joomla-cms/commit/6792d8a12212d4ab4371e23bcf82451dbb47077d

So this is good to go.

**Comment by rdeutz** [comment]
looks like a bug in github

**Comment by rdeutz** [comment]
informed github support team

**Pull request closed without merging**
