### PR TITLE
[4.0] Class caps naming

### PR DESCRIPTION
**Pull request by brianteeman**
Pr for #27014

Partial fix - I didnt see how to fix the unit tests and #27015 fixed another

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d3443abefc25ef663003268f4348f0c26a4001b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27030">issues.joomla.org/tracker/joomla-cms/27030</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d3443abefc25ef663003268f4348f0c26a4001b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27030">issues.joomla.org/tracker/joomla-cms/27030</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27030">issues.joomla.org/tracker/joomla-cms/27030</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
