### PR TITLE
No need to utf8 encode statuses which are already utf8 encoded (issue #9043)

### PR DESCRIPTION
**Pull request by mabdelaziz77**
It has to detect the status encoding at first, if it is already utf8 encoded, then send it as it is without anymore encoding.

### CODE REVIEW

**Comment by brianteeman** [comment]
There are a few code style fixes required. See the Travis checks for details.

It would be great if you could supply some sample code so that people can test this easier.

**Comment by wilsonge** [comment]
We don't require the `mb` php extension here so we need to find a work around for these users (I guess even a `function_exists` will do in a worst case). `StringHelper::is_ascii` might work?

**Comment by mabdelaziz77** [comment]
@brianteeman Ok, will do that.
Sorry, it is the first time for me to post on joomla repo.

**Comment by roland-d** [comment]
Hello @mabdelaziz77 

Thank you for your contribution.

The last comment here was on 2nd February. Could you update the pull request with the needed changes as pointed out by @wilsonge 
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9044">issues.joomla.org/joomla-cms/9044</a>.</sub>

**Comment by mabdelaziz77** [comment]
Hello @roland-d 
I will try to find a workaround.
Thanks @wilsonge for your advice.

**Comment by brianteeman** [comment]
Thank you

**Comment by roland-d** [comment]
@mabdelaziz77 Thank you for your answer. Does this mean we can close this request or you will try to find another solution and update this request?

**Comment by ggppdk** [comment]
The original commit used mb_*:

https://github.com/joomla/joomla-cms/pull/9044/commits/b96165af83484b1514f6f16d0c27dc242b9d7adc

but then it was changed to use:
```
if (utf8_is_valid($status))
```
https://github.com/joomla/joomla-cms/pull/9044/commits/15772dc9315664ce6282f4beaeada0a59aac0de2

so mbstring dependency was removed
does the new code work ?

**Comment by mabdelaziz77** [comment]
Sorry, it was long time since I made this pull request. 
mbstring dependency was already removed as @ggppdk noticed, and the commit message on Feb 2 declared this removal.

**Comment by sanderpotjer** [comment]
@mabdelaziz77 could you please fix the conflict in `libraries/joomla/twitter/statuses.php`. Is the code ready for testing or are additional changes coming, not really clear for me at the moment. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9044">issues.joomla.org/tracker/joomla-cms/9044</a>.</sub>

**Comment by mbabker** [comment]
If this is still a valid issue the code should be updated to call [`\Joomla\String\StringHelper::valid()`](https://github.com/joomla/joomla-cms/blob/3.7.1/libraries/vendor/joomla/string/src/StringHelper.php#L763) versus `utf8_is_valid()` directly.  Also, since this package is deprecated in the CMS, the corresponding [Framework package](https://github.com/joomla-framework/twitter-api) should be checked and a PR issued there with the same fix.

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9044">issues.joomla.org/tracker/joomla-cms/9044</a>.</sub>

**Pull request closed without merging**
