### PR TITLE
[3.10] Update contributing.md file to be merged up to 4.1 and 4.2

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/36913 (taken down to 3.10 to be merged up to 4.2

### Summary of Changes

Updates the contributing.md file to be merged up to 4.1 and 4.2

### Testing Instructions

review the changes

### Actual result BEFORE applying this Pull Request

4.2-dev is missing

### Expected result AFTER applying this Pull Request

4.2-dev is there

### Documentation Changes Required

thanks @brianteeman for the original PR https://github.com/joomla/joomla-cms/pull/36913

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 305f226557c809cf9053eeb55745434bba2eccfb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36953">issues.joomla.org/tracker/joomla-cms/36953</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 305f226557c809cf9053eeb55745434bba2eccfb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36953">issues.joomla.org/tracker/joomla-cms/36953</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36953">issues.joomla.org/tracker/joomla-cms/36953</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 677b488ea19c2832851706e94aae5c082d602b3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36953">issues.joomla.org/tracker/joomla-cms/36953</a>.</sub>

**Review by its0x08 — APPROVED** [review]

**Comment by zero-24** [comment]
Merged cc @bembelimen

**Pull request merged**
