### PR TITLE
[4.1] Use to PHP 8.1 fixes for debug bar dependency

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #37274.

### Summary of Changes
Updates the PHP debugbar dependency to the commit with the latest PHP 8.1 fixes. It is basically the release 1.18.0 with the fixes.

### Testing Instructions
- Run Joomla on PHP 8.1
- Enable debugging in the global Joomla configuration
- Set error reporting to maximum in the global Joomla configuration
- Make sure the debug plugin is enabled by default (is the case when doing a new installation)

### Actual result BEFORE applying this Pull Request
The following error is shown:
_Implicit conversion from float -INF to int loses precision in_

### Expected result AFTER applying this Pull Request
No error.

### CODE REVIEW

**Comment by exstreme** [comment]
I have tested this item :white_check_mark: successfully on 19181503942b9401bde75bbd9acf21987ec4eb0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37488">issues.joomla.org/tracker/joomla-cms/37488</a>.</sub>

**Comment by HLeithner** [comment]
Can you please pin the commit and not the branch. thx

**Comment by laoneo** [comment]
I did that in my first commit https://github.com/joomla/joomla-cms/pull/37488/commits/662e14085f2ef87a8469db1a7bba8ce2cd867d00 and then composer complained that that it is unsafe to do this and did abort on drone. The lock file is actually pointing to the commit, so we are covered to some degree.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on ccae2453e0b6a3d8bbe122bdfd94f2ca0eb971cd<br /><br />Tested on branch 4.1-dev,win11, xampp, php 8.1, debug mode "on" and error-reporting="maximum". 

Before Patch: the application crashed with an eror 500, but not the message wich is mentioned in  testing instructions. 

After patch: application runs, no errors, no deprecated warnings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37488">issues.joomla.org/tracker/joomla-cms/37488</a>.</sub>

**Comment by laoneo** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37488">issues.joomla.org/tracker/joomla-cms/37488</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
