### PR TITLE
[4.0] Wrong link for Help in User Actions Log Options

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30591 .

### Summary of Changes

Help link fix

### Testing Instructions
Go to Global Configuration -> User Actions Log
Select the Help button

### Actual result BEFORE applying this Pull Request
The Help screen for the User Actions Log page.

### Expected result AFTER applying this Pull Request
A Help screen for the Options page

### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cbebde55fb2b9d317131d6b3b5ec65d84f5b0fe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30594">issues.joomla.org/tracker/joomla-cms/30594</a>.</sub>

**Comment by brianteeman** [comment]
Can you backport this to j3 as well please

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on cbebde55fb2b9d317131d6b3b5ec65d84f5b0fe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30594">issues.joomla.org/tracker/joomla-cms/30594</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman  Please see https://github.com/joomla/joomla-cms/pull/30595 for j3 backport

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30594">issues.joomla.org/tracker/joomla-cms/30594</a>.</sub>

**Comment by wojsmol** [comment]
@Formatio-hippocampi @ChristineWk @brianteeman Please test https://github.com/joomla/joomla-cms/pull/30595

**Comment by ChristineWk** [comment]
@wojsmol FYI: I tested already #30595 hours ago, but it was unsuccessful. Hv to check again.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
