### PR TITLE
[4.0] Fix captcha plugins and scripts

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #28758 

### Summary of Changes

Fixing `Joomla\CMS\Captcha\Captcha` because `onInit()`, `onDisplay()`, `onCheckAnswer()` is a callbacks and not an events

Also fixing JS that use incorrect methods as a capctha callback.

### Testing Instructions
please look for detail #28758 

### Expected result
Captcha wokrs

### Actual result
Captcha not wokrs

### CODE REVIEW

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on 77a4c8b0dd4e58fe3d23d0a077cf4b082b21cb27<br /><br />The reCaptcha works ok again. Thanks for the fix!

### Before the patch - reCaptcha is missing

screencapture-local-joomla-cms-nl-index-php-contact-form-2020-04-25-13_54_15

### After the patch - reCaptcha is visible and working again

screencapture-local-joomla-cms-nl-index-php-contact-form-2020-04-25-13_54_50




 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28785">issues.joomla.org/tracker/joomla-cms/28785</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 77a4c8b0dd4e58fe3d23d0a077cf4b082b21cb27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28785">issues.joomla.org/tracker/joomla-cms/28785</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28785">issues.joomla.org/tracker/joomla-cms/28785</a>.</sub>

**Comment by richard67** [comment]
Thanks all.

**Comment by wilsonge** [comment]
This isn’t right. The change in j4 was deliberately to use plugins events. It’s fine to merge this as it is to get things working. But can we please investigate what’s needed to make this use events properly

**Comment by richard67** [comment]
As requested by @wilsonge I've created issue #28800 so that it's not forgotten.

**Comment by Fedik** [comment]
@wilsonge the thing that an event should be called strictly to "this specific plugin", not system wide.
This for Cpatcha group and for Editor plugin group.



Check how j3 work

**Comment by mbabker** [comment]
That's not how an event system works.  And that's why the hackjobs inside the captcha and editor API were rightfully changed from some convoluted callback system to using events.  It is up to a listener (the captcha plugins in this case) to decide whether or not the emitted event applies to it.

Just because things are done a certain way in 3.x does not mean they were done right.  Otherwise, just throw all of 4.0 out the window since clearly nothing needed to change :wink:

**Comment by Fedik** [comment]
> Just because things are done a certain way in 3.x does not mean they were done right

Well, I did not meant it is right (or wrong), I am about how it work, the behavior, that the plugin updated "locally"


Okay I think this a solution, is to throw away global dispatcher (from captcha and editor):
```php
$this->setDispatcher(Factory::getApplication()->getDispatcher());
```
And use local one, per `Joomla\CMS\Captcha\Captcha`, `Joomla\CMS\Editor\Editor` instance:
```php
$this->setDispatcher(new EventDispatcher);
```

**Comment by Fedik** [comment]
there is another try #28808 please check

**Pull request merged**
