### PR TITLE
[RFC] Responsive Tables

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Creates a responsive tables class allowing more data to be displayed on smaller screens. Class applied to article list. 

My intent here is to give an alternative table display on smaller screens where you are not limited to the amount of data that is displayed.

### Testing Instructions
Navigate to Content -> Article and resize browser window.

### Before patch
com-content-table1

### After patch
com-content-table2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on aa771fc0a3d2f20d5155c7ec96422e9362b8328b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13835">issues.joomla.org/tracker/joomla-cms/13835</a>.</sub>

**Comment by Bakual** [comment]
Associations don't have a title when shrunk. It's also missing the clickable table headers to sort the fields.

Personally, I don't like the new small view, I prefer the current phone view.

**Comment by ciar4n** [comment]
Really my intent here is to give an alternative table display on smaller screens where you are not limited to the amount of data that is displayed by converting the table from a column view to a row view. The current table, although it looks neater, is very limited on how much data can be displayed. Maybe com_contents is a bad example to demonstrate however the idea may be useful elsewhere.

I used a similar approach on #13769 where it was suggested that the same technique could be used on other tables.

**Comment by Bakual** [comment]
For the repeatable I think this makes sense, because hiding elements doesn't make sense there.

However in regular manager tables, hiding columns is perfectly fine, and those tables already are responsive. No need to fix something that isn't broken imho.

**Comment by laoneo** [comment]
I really like to have the possibility to make tables correctly responsive and not just by hiding elements. Would be nice to have that possibility also on the front end for templates available as less file to include.

**Comment by C-Lodder** [comment]
I'd suggest removing all the columns apart from the title and checkbox columns. For mobile, this would be enough

**Comment by tuts-22** [comment]
I have tested this item :white_check_mark: successfully on e5ff521ca7afedb0b105162274d2d88c878a1640<br /><br />I have tested the request and it works fine!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13835">issues.joomla.org/tracker/joomla-cms/13835</a>.</sub>

**Comment by jeckodevelopment** [comment]
@ciar4n please look at the conflicts

**Comment by JoshuaLewis** [comment]
I'm not in favor of this PR due to the display feeling more cluttered. I attached a screen shot showing with the patch and the other without. Both are responsive, this patch shows more meta data per row which ends up making the article view feel not as clean. Normally I like more meta data, but in this case it doesn't seem to add much value on small display. I suppose maybe the author, but not the permission column.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13835">issues.joomla.org/tracker/joomla-cms/13835</a>.</sub>

**Comment by JoshuaLewis** [comment]
I'm not in favor of this PR due to the display feeling more cluttered. I attached a screen shot showing with the patch and the other without. Both are responsive, this patch shows more meta data per row which ends up making the article view feel not as clean. Normally I like more meta data, but in this case it doesn't seem to add much value on small display. I suppose maybe the author, but not the permission column.

screen shot 2017-02-11 at 20 29 22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13835">issues.joomla.org/tracker/joomla-cms/13835</a>.</sub>

**Comment by ciar4n** [comment]
Conflicts fixed.

I tend to agree that for the article list and for want of as simple a view as possible on mobile devices, this PR might be a little to much. The question is, is there any table view that this layout would be needed? Are we missing any important data on any of the tables on mobile devices that should be displayed?

If so then this PR allows a workable alternative. If not then there is no need for it.

**Comment by C-Lodder** [comment]
I normally am in favour of all your PR's Ciaran, but on this one I think it over complicates the visible data

**Comment by ciar4n** [comment]
I'm gonna close this. If a need for it arises it can be re-opened.

**Pull request closed without merging**
