### PR TITLE
[4.0] Calendar change event

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #32694 and #17515 

### Summary of Changes

make calendar.js trigger "change" event when user select new date

### Testing Instructions

Apply path, run `npm install`,
add to Atum index.php:
```html
<script type="module">
if (window.jform_publish_up){
  window.jform_publish_up.addEventListener('change', () => {
    console.log('change');
  })
}
</script>
```

Go to Article editing, and try to change the publish_up date.
In browser console you should get "change" message on each change

### Actual result BEFORE applying this Pull Request
No message

### Expected result AFTER applying this Pull Request
Message

### Documentation Changes Required
none

### CODE REVIEW

**Comment by alikon** [comment]
isn't #17515 a j3 issue?

**Comment by Fedik** [comment]
yes, there will be one more PR for j3, not that fast :smile:

**Comment by Fedik** [comment]
for jooml3 is there #32756

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on be49d16274740ba4be908990e01727d14b7ffed5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32755">issues.joomla.org/tracker/joomla-cms/32755</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on be49d16274740ba4be908990e01727d14b7ffed5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32755">issues.joomla.org/tracker/joomla-cms/32755</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32755">issues.joomla.org/tracker/joomla-cms/32755</a>.</sub>

**Pull request merged**
