### PR TITLE
Fix sampledata menu creation

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #21073 .

### Summary of Changes
Adds a table check prior to storing.

### Testing Instructions
Create the blog sampledata and check the menutype of the created menus. 

### Expected result
They should contain no spaces and be lowercased.

### Actual result
Contain spaces and uppercase characters

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
Oops

**Comment by Bakual** [comment]
Better now :)

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 3e436e0eda41a50b40129a4c234fc7c6b24e9d47<br /><br />There is an error in the sample data plugins. Response is invalid.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21080">issues.joomla.org/tracker/joomla-cms/21080</a>.</sub>

**Comment by brianteeman** [comment]
Note that the multilingual sample plugin does not have this problem. menus are created correctly there<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21080">issues.joomla.org/tracker/joomla-cms/21080</a>.</sub>

**Comment by Bakual** [comment]
I don't know why you got an invalid response. It works for me fine.
One reason may be that the check did return false, and since my code didn't test it may have triggered some unhandled error somewhere. I've changed now the code so it checks for exceptions and return values. Which was also the main difference to the multilingual code.

**Comment by brianteeman** [comment]
the invalid response was me checking it in j4 not staging

**Comment by brianteeman** [comment]
the pr works correctly in j3

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2648ed0e6f9d878bfad2bc7d852ad9d270b80d0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21080">issues.joomla.org/tracker/joomla-cms/21080</a>.</sub>

**Comment by Bakual** [comment]
Ah, that explains it :)

**Comment by infograf768** [comment]
While testing, I found another possible issue:
we have
`'title'       => JText::_('PLG_SAMPLEDATA_BLOG_SAMPLEDATA_MENUS_MENU_' . $i . '_TITLE') . $langSuffix,`
and
`$type = JHtml::_('string.truncate', $menu['title'], 23, true, false);`

If the title is the same in 2 or more languages and truncate takes off the lang code , the menu type maybe exactly the same.

Afaik, it is forbidden to create multiple menus with the same Menu Type value.

EDIT: also, a Menu can have the same title but not the same menu type, which is bizarre as it is the title which is displayed in the Select Menu dropdown field.

What do you think?

**Comment by infograf768** [comment]
> a Menu can have the same title but not the same menu type,

This is a general behavior, unrelated to this PR.

**Comment by infograf768** [comment]
Will propose a PR for the menu Title general issue.

See https://github.com/joomla/joomla-cms/pull/21085

**Comment by Bakual** [comment]
> If the title is the same in 2 or more languages and truncate takes off the lang code , the menu type maybe exactly the same.

I doubt the changes for that happening is great, but yes it may happen if the languages are close enough or didn't translate the english text.
But we're talking about a blog sampledata here. I don't think the case were you install the same sampledata for multiple close or non-translated language packs is often. If you install it for german, french and italian and all of those packs have the sampledata translated, then it will work fine 😄

**Comment by infograf768** [comment]
Hmm. I have not tested in German, but I should with de-DE, de-AT, etc. to see what happens

**Comment by brianteeman** [comment]
you can resolve this in the plugin by truncating the title first and then adding the language code

**Comment by Bakual** [comment]
> you can resolve this in the plugin by truncating the title first and then adding the language code

Would be an option, yes. However I really doubt we run into that issue anytime. Keep in mind that 
* a menu title has to be longer than 23 characters
* a second language must have a menu title with the exact same first 23 characters.

For the blog sample data, I don't even see a title that may get longer than 23 characters even in german 😄.
But yeah, if someone wants to have a take at it, go ahead.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2648ed0e6f9d878bfad2bc7d852ad9d270b80d0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21080">issues.joomla.org/tracker/joomla-cms/21080</a>.</sub>

**Comment by infograf768** [comment]
RTC



Similar patch for 4.0 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21080">issues.joomla.org/tracker/joomla-cms/21080</a>.</sub>

**Comment by Bakual** [comment]
> Similar patch for 4.0 ?

George will merge staging up to 4.0. If something is needed afterwards, we will do that.

**Comment by infograf768** [comment]
Thanks.

**Pull request merged**
