### PR TITLE
[4] Add missing validate="CssIdentifier" to blog_class_leading field

### PR DESCRIPTION
**Pull request by ReLater**
References https://github.com/joomla/joomla-cms/pull/29108

# Summary of Changes
- See code change tabulator above ("Changed files").

### Testing Instructions
- Apply patch.
- Enter an invalid CSS selector class for "Blog Class (Leading Articles)" in a featured menu item.
- Addition: ...or in a blog menu item.
- See that saving of menu item is blocked.
- Enter a valid selector.
- See that saving is not blocked.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0e0553aabaee7794ebfb8131a9675e8d4184de0f<br /><br />Do we have the invalid characters documented somewhere? Just thinking what might go in the Help screen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0e0553aabaee7794ebfb8131a9675e8d4184de0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ChristineWk** [comment]
@ReLater Could you also check with "blog item" please? Because after entering an invalid class under: Menu Blog > Blog Layout > Blog Class (Leading Articles) I got: Menu saved. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ReLater** [comment]
Have added commit for blog_class_leading

**Comment by ReLater** [comment]
> Do we have the invalid characters documented somewhere? Just thinking what might go in the Help screen.

I think it's easier to define what is allowed.

The official spec.:
https://www.w3.org/TR/CSS21/syndata.html#characters

For me this sentence is sufficient:

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier `"B&W?"` may be written as `"B\&W\?"` or `"B\26 W\3F"`.

**Comment by ChristineWk** [comment]
Tried again for blog_class_leading. With updated Patch, response: Invalid field: Blog Class (Leading Articles)
Seems OK?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ReLater** [comment]
Whenever you enter an invalid CSS class and get a warning: It's a successfull test.

When you enter a valid one and get a warning it's not successful. But then zero-24 should have a look on this issue. Then something is wrong with the new filter rule. And we need the classes you have tested with.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on fd4bf8fb3ba0b2d7f09ab4f4d66d35161a050052<br /><br />OK!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fd4bf8fb3ba0b2d7f09ab4f4d66d35161a050052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fd4bf8fb3ba0b2d7f09ab4f4d66d35161a050052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31459">issues.joomla.org/tracker/joomla-cms/31459</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
