### PR TITLE
[4.0] Fix SQL for creating table "#__workflow_associations" in installation and schema update for PostgreSQL

### PR DESCRIPTION
**Pull request by richard67**
Use correct syntax for comments and so fix SQL errors on PostgreSQL.

Can be tested and merged by review.

@alikon please review.

### CODE REVIEW

**Comment by richard67** [comment]
This is the second last error which makes Joomla 4.0 installation not work for PostgreSQL.
The other one is PR #21886 .
@alikon and maybe others: Please review.
When both PRs are applied, installation of Joomla 4.0 works for PostgreSQL (with all other already committed corrections from today of course).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21884">issues.joomla.org/tracker/joomla-cms/21884</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1481a4808134ccbb48534273970baca325500a3e<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21884">issues.joomla.org/tracker/joomla-cms/21884</a>.</sub>

**Comment by richard67** [comment]
Thanks @alikon .

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
