### PR TITLE
[4.0] Remove unneeded strings from robots parameter

### PR DESCRIPTION
**Pull request by Bakual**
Since we deprecated the strings in staging (https://github.com/joomla/joomla-cms/pull/30110), this PR removes the strings in 4.0.

### Summary of Changes
Removing unneeded strings

### Testing Instructions
Nothing to test as the strings are not used anymore (after staging is merged up).

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 694d77fc6f3772a67e7968de90cc0e880314a38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30399">issues.joomla.org/tracker/joomla-cms/30399</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 694d77fc6f3772a67e7968de90cc0e880314a38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30399">issues.joomla.org/tracker/joomla-cms/30399</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30399">issues.joomla.org/tracker/joomla-cms/30399</a>.</sub>

**Comment by Bakual** [comment]
Please wait with merge till the staging is merged up and PR #30110 is part of `4.0-dev`. Otherwise it gets messy I think 😄

**Comment by richard67** [comment]
There were conflicts meanwhile. I've allowed myself to solve them.

But we still have to wait with merging. The changes from PR #30110 have meanwhile arrived in 3.10-dev, but they haven't been merged up into 4.0-dev yet.

**Comment by richard67** [comment]
I've allowed myself to solve conflicts. After recent merge from 3.10-dev up to 4.0-dev, only `components/com_content/forms/article.xml` is remaining using the removed strings.

So we still have to wait for that one before we can merge this one here.

**Comment by richard67** [comment]
@Bakual Hmm, I just see that file `components/com_content/forms/article.xml` was not part of #30110 , and here only admin and API files are handled. That XML file contains these language stings, too, but they are not defined in the site language file ... am confused.

**Comment by Bakual** [comment]
Looks certainly like I missed those for some reason.
That form file is used in the menuitem edit form in the backend. That's why the strings are missing in frontend.

**Comment by richard67** [comment]
@Bakual Can't find that file in J3. Is it new in J4? And will you fix that, too?

**Comment by Bakual** [comment]
@richard67 The file is there, I just created the PR to remove it.
I have no clue why I didn't see it back then, probably the same reason you're not seeing it today 😄

**Comment by richard67** [comment]
So this one has still to wait, this time for #31557 .

**Comment by Bakual** [comment]
Looks like, yes. Sorry for that.

**Comment by wilsonge** [comment]
Can confirm nothing is using them after my latest set of merges

**Pull request merged**
