### PR TITLE
Hide table columns debug

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the table columns selector to the debuguser and debug permissions views

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <[link](https://github.com/joomla/Manual/pull/45)>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 6ba674b513753e8133e028f3e97a310b0b23a0c9<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38971">issues.joomla.org/tracker/joomla-cms/38971</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 6ba674b513753e8133e028f3e97a310b0b23a0c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38971">issues.joomla.org/tracker/joomla-cms/38971</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38971">issues.joomla.org/tracker/joomla-cms/38971</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
