### PR TITLE
[4.1] Task Manager numeric strings

### PR DESCRIPTION
**Pull request by brianteeman**
Update strings to use %d when the sprintf is numeric

Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b2dab11c3926e544ded2a30700e8b556d836bfe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36245">issues.joomla.org/tracker/joomla-cms/36245</a>.</sub>

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36245">issues.joomla.org/tracker/joomla-cms/36245</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6b0d86884fcfdfa08f21844dc7152006d8216da5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36245">issues.joomla.org/tracker/joomla-cms/36245</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36245">issues.joomla.org/tracker/joomla-cms/36245</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
