### PR TITLE
add time zone offset value

### PR DESCRIPTION
**Pull request by AlekVolsk**
add an offset value to the timezone in hours from UTC, for convenience only

sample view

### CODE REVIEW

**Comment by laoneo** [comment]
Will it consider DST?

**Comment by brianteeman** [comment]
I agree it will be useful

Can you not get the value with get_timezone_offset

**Comment by AlekVolsk** [comment]
@laoneo no, I did not support DST, it seemed to me that it can cause unnecessary load, and not always it is necessary

there is no DST in my country. it was enough for me to just know the offset, and for convenience only, no more

**Comment by progreccor** [comment]
it will be convenient

**Comment by AlekVolsk** [comment]
I looked at what this test did not pass, and there it looks like that just php 5.6 bot was unable to deploy the repository and after an hour of timeout returned an error, although the solution works even on php 5.3

sorry, but it seems there is a bot decides whether to pass this decision in life

**Comment by rdeutz** [comment]
looks odd, I can not restart the build.

**Comment by AlekVolsk** [comment]
did I break the Joomla...

**Comment by rdeutz** [comment]
no AppVeyor :-) Just move on, we need two people testing this and then we look further

**Comment by ghost** [comment]
@AlekVolsk can you give Test Instructions on first Comment so Tester can be sure what to look on?

**Comment by AlekVolsk** [comment]
what kind of test instructions do you want? you see the code-there are less than a dozen lines, you are not able to understand what it does and how it works?

**Comment by infograf768** [comment]
Repository unknown. Can't get a .diff
Tested by copy paste the entire raw modified file.
I get for Paris +2:00 which is correct TODAY as we are in DST = UTC + 2
But on October 28th, we will be UTC + 1
Will that be reflected in the display?
If not, quite useless for Europe.

**Comment by laoneo** [comment]
It uses the [actual date](https://github.com/joomla/joomla-cms/pull/21573/files#diff-2cfabcb5ca92b9eb48e31f2489023085R126) so it always shows the offset of the current DST.

**Comment by AlekVolsk** [comment]
there is no more desire anything to offer, one of snobbery

**Pull request closed without merging**
