### PR TITLE
[4] DESCRIPTION typo

### PR DESCRIPTION
**Pull request by PhilETaylor**
`COM_FINDER_CONFIG_FIELD_OPENSEARCH_DESCRIPTON_LABEL`

`COM_FINDER_CONFIG_FIELD_OPENSEARCH_DESCRIPTION_LABEL`

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4c070061bdf13f587ee4834fd50912121a4ada83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34023">issues.joomla.org/tracker/joomla-cms/34023</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 4c070061bdf13f587ee4834fd50912121a4ada83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34023">issues.joomla.org/tracker/joomla-cms/34023</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34023">issues.joomla.org/tracker/joomla-cms/34023</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
