### PR TITLE
Templates search tools ordering

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_templates.
###### After PR

image

image
#### How to test
1. Install latest staging and apply this patch
2. Go to Extensions -> Templates
3. Check the ordering select box is working fine in "Styles" and in "Templates" view

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 702fa61fedbfc82b91f5c9811ad2ca6e26cdecc7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9090">issues.joomla.org/joomla-cms/9090</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 702fa61fedbfc82b91f5c9811ad2ca6e26cdecc7<br /><br />Works as describe - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9090">issues.joomla.org/joomla-cms/9090</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 702fa61fedbfc82b91f5c9811ad2ca6e26cdecc7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9090">issues.joomla.org/joomla-cms/9090</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9090">issues.joomla.org/joomla-cms/9090</a>.</sub>

**Pull request merged**
