### PR TITLE
[4.0] Remove description from com_csp

### PR DESCRIPTION
**Pull request by hardik-codes**
Remove description attribute in ```administrator/components/com_csp/forms/filter_reports.xml```

### Testing Instructions
Code inspection

### CODE REVIEW

**Comment by hardik-codes** [comment]
@brianteeman please check

**Comment by brianteeman** [comment]
No this is completely wrong

**Comment by hardik-codes** [comment]
> No this is completely wrong

In #24444  you mentioned that there are still some remaining 
Please point out the mistake so that I can correct it

**Comment by brianteeman** [comment]
The descriptions remaining are the ones that have a purpose. This one does. If you look you will see that all components have this one AND in #24441 I created a PR to display the search box tips.

Please close this

**Comment by hardik-codes** [comment]
> The descriptions remaining are the ones that have a purpose. This one does. If you look you will see that all components have this one AND in #24441 I created a PR to display the search box tips.
> 
> Please close this

oh my bad
 I'll close this

**Pull request closed without merging**
