### PR TITLE
[5.1] Subform rows sorting with buttons, addittionaly to drag and drop

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Add posibility to sort subform rows with buttons "up" and "down".
Useful for large forms.

Screenshot 2023-11-11_20-58-38

Fix for https://github.com/joomla/joomla-cms/issues/39092

### Testing Instructions
Run `npm install`
Create a subform somewhere:
```xml
<field type="subform" name="subform" label="subform" multiple="true">
  <form>
    <field type="text" name="text" label="Text"/>
  </form>
</field>
```
And use new up/down button for rows sorting

### Actual result BEFORE applying this Pull Request
nothing

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 89a503ec519cc2f9d8ad1a7d3f9afc033687fdca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42334">issues.joomla.org/tracker/joomla-cms/42334</a>.</sub>

**Comment by AndySDH** [comment]
This approach is a bit reductive and I don't feel like it fully addresses #39092. Dragging and dropping is still very bad, and I don't think adding an up and down arrow is enough to call the problem solved.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 89a503ec519cc2f9d8ad1a7d3f9afc033687fdca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42334">issues.joomla.org/tracker/joomla-cms/42334</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42334">issues.joomla.org/tracker/joomla-cms/42334</a>.</sub>

**Comment by LadySolveig** [comment]
A heartfelt thanks @Fedik and thanks to the testers @viocassel @Quy

**Pull request merged**
