### PR TITLE
CodeMirror 5.15.2

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
#### Summary of Changes

http://codemirror.net/doc/releases.html
#### Testing Instructions

Just use codemirror.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 8b470ec1a4b13ee502fa238ca1914e73c4c36e61<br /><br />Works with template manager and as editor. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10619">issues.joomla.org/joomla-cms/10619</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8b470ec1a4b13ee502fa238ca1914e73c4c36e61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10619">issues.joomla.org/joomla-cms/10619</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10619">issues.joomla.org/joomla-cms/10619</a>.</sub>

**Comment by roland-d** [comment]
Thanks everyone

**Pull request merged**
