### PR TITLE
[4.0] Update location path in description

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
The old path is for J3.  Update location path for J4.

### Testing Instructions
Code review.

or

Install Testing Sample Data.
Go to System > Manage > Extensions
Search and disable Wrapper - Site.
Go to System > Manage > Site Modules
Go to the Wrapper row.
Hover mouse over the disabled icon under Status column.

### Actual result BEFORE applying this Pull Request
manage-extensions

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c1c21120844fc6dd4ec21b8f4141e28225fb9ed4<br /><br />Marking as a successful test 

but it really needs to be changed from a title to make it accessible and usable. Also you don't normally get information on anything disabled and the grey colour makes this look disabled so the title is unexpected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34238">issues.joomla.org/tracker/joomla-cms/34238</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c1c21120844fc6dd4ec21b8f4141e28225fb9ed4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34238">issues.joomla.org/tracker/joomla-cms/34238</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34238">issues.joomla.org/tracker/joomla-cms/34238</a>.</sub>

**Comment by infograf768** [comment]
Thought:

There are other ways to get to  `Manage -> Extensions` than passing by the default admin Joomla menu `System > Manage > Extensions` .

For example, when using the Alternative Main Menu, it is `Extensions > Manage > Manage`
Or in case of a custom admin menu, it can be `Manage > Extensions`

All have evidently the same url `index.php?option=com_installer&view=manage`

It would be nice to use a link with the url as second variable in the sprintf.

This evidently if we can click on that link.

The problem is that it is a tip created as Title and therefore can't be clicked.
Any idea how to improve this?

**Comment by brianteeman** [comment]
@infograf768 see #34240 that would allow your suggestion

**Comment by infograf768** [comment]
I was thinking of something like this

extensions-manage

**Comment by infograf768** [comment]
code would be something like

```
diff --git a/administrator/components/com_modules/tmpl/modules/default.php b/administrator/components/com_modules/tmpl/modules/default.php
index 05a53b5..ebb7513 100644
--- a/administrator/components/com_modules/tmpl/modules/default.php
+++ b/administrator/components/com_modules/tmpl/modules/default.php
@@ -124,7 +124,15 @@
 							<?php else : ?>
 								<?php // Extension is not enabled, show a message that indicates this. ?>
-								<span class="tbody-icon" title="<?php echo Text::sprintf('COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED', $this->escape($item->name)); ?>">
-									<span class="icon-minus-circle" aria-hidden="true"></span>
-								</span>
+								<div class="dropdown">
+									<button role="button" data-bs-toggle="dropdown" aria-expanded="false" class="icon-minus-circle btn-sm dropdown-toggle">
+									</button>
+									<ul class="dropdown-menu dropdown-menu-end" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(-228px, 27px);" data-popper-placement="bottom-start">
+										<li>
+											<button type="button" class="dropdown-item" title="Extensions: Manage">
+												<a href="<?php echo Route::_('index.php?option=com_installer&view=manage'); ?>"><?php echo Text::sprintf('COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED', $this->escape($item->name)); ?></a>
+											</button>
+										</li>
+									</ul>
+								</div>
 							<?php endif; ?>
 						</td>
```

**Comment by Quy** [comment]
While functional, it feels clunky. Maybe keep the tooltip and click the button to go to the Extensions list.

**Comment by infograf768** [comment]
Here is another solution.
The tooltip is now in a similar format as the other status icons tooltips (aria-labelledby).
Clicking on the icon redirects to `Manage => Extensions`
The only visual difference is the cursor. Therefore we may need to modify the tip to let users know that clicking on the icon will redirect to `Manage => Extensions`

Code would be something like
```
diff --git a/administrator/components/com_modules/tmpl/modules/default.php b/administrator/components/com_modules/tmpl/modules/default.php
index 05a53b5..2c46970 100644
--- a/administrator/components/com_modules/tmpl/modules/default.php
+++ b/administrator/components/com_modules/tmpl/modules/default.php
@@ -124,7 +124,11 @@
 							<?php else : ?>
 								<?php // Extension is not enabled, show a message that indicates this. ?>
-								<span class="tbody-icon" title="<?php echo Text::sprintf('COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED', $this->escape($item->name)); ?>">
+								<a class="tbody-icon" href="javascript:void(0);" onClick="location.href='<?php echo Route::_('index.php?option=com_installer&view=manage'); ?>'"
+									aria-labelledby="disabled-<?php echo $this->escape($item->name); ?>">
 									<span class="icon-minus-circle" aria-hidden="true"></span>
-								</span>
+								</a>
+								<div id="disabled-<?php echo $this->escape($item->name); ?>" role="tooltip">
+									<?php echo Text::sprintf('COM_MODULES_MSG_MANAGE_EXTENSION_DISABLED', $this->escape($item->name)); ?>
+								</div>
 							<?php endif; ?>
 						</td>
```
and result

extensions-manage2

### NOTE-UNRELATED ISSUE: 
I discovered an important bug when working on this.
It happens when we have one module disabled in the displayed list. That module has no checkbox.
Clicking on blank space in any row ticks the checkbox of the row immediately at the bottom.
Clicking on a checkbox ALSO checks the checkbox below.

sitemodules_tick_issue


Release blocker??

**Comment by brianteeman** [comment]
The second unrelated issue is already reported

**Comment by infograf768** [comment]
Found where it is reported
https://github.com/joomla/joomla-cms/issues/30798
but not solved...

**Comment by infograf768** [comment]
For the checkboxes, we could simply use https://github.com/joomla/joomla-cms/issues/30798#issuecomment-850300717

**Pull request merged**
