### PR TITLE
[4.0] Remove unused fields

### PR DESCRIPTION
**Pull request by brianteeman**
To the best of my ability to search github these "spacer" were added https://github.com/joomla/joomla-cms/commit/57c5180fb5693372e09b2ea97ed26d4f6b9b7695

If you look at that PR the code was wrong and the field was never used although it was intended to be a spacer before a button.

That button has long since been removed and has never even been in a 3.x release

Let's stop maintaining it

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4739e54b3a0b85f55eb81a246517fda2575e90fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25497">issues.joomla.org/tracker/joomla-cms/25497</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 8a7b83a61eb0aec5a39f4a4a6df6f2132769740b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25497">issues.joomla.org/tracker/joomla-cms/25497</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25497">issues.joomla.org/tracker/joomla-cms/25497</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
