### PR TITLE
 [5] Module 'Feed Display': deprecated Notice

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42793 .

### Summary of Changes
skip if publishDate is null

### Testing Instructions

see #42793 

### Actual result BEFORE applying this Pull Request
 deprecated Notice

### Expected result AFTER applying this Pull Request

No deprecated Notice

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 93a41250790ea82d28dc9144fbfe601f5195fb34<br /><br />Thanks @alikon<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42795">issues.joomla.org/tracker/joomla-cms/42795</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 93a41250790ea82d28dc9144fbfe601f5195fb34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42795">issues.joomla.org/tracker/joomla-cms/42795</a>.</sub>

**Comment by brianteeman** [comment]
Doesnt the same change need to be made to the admin feed module?

**Comment by alikon** [comment]
yes i'll add the same fix on the admin module too

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 705ef82a83573072b840cd1fe605e86b8bf82325<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42795">issues.joomla.org/tracker/joomla-cms/42795</a>.</sub>

**Comment by richard67** [comment]
@alikon Do we have the issue only in 5.x? Or also in 4.4? If in 4.4, shouldn’t it be fixed in the 4.4-dev branch?

**Comment by alikon** [comment]
Honestly i didn't check in 4.4 as the issue was reported from 5.0.3  i'll check later on 4.4

**Comment by alikon** [comment]
issue is present on 4.4 too i'll redo the pr on the 4.4 branch

**Comment by alikon** [comment]
please test #42803

**Pull request closed without merging**
