### PR TITLE
Problem with edit.state when creating new articles

### PR DESCRIPTION
**Pull request by Chraneco**
#### Steps to reproduce the issue
1. Create a new user group independent from the others
2. Give this user group login permissions to the frontend
3. Create a new user and assign it to the new user group
4. For one content category assign 'create' and 'edit.state' permissions to the new user group
5. With the new user log into the frontend and create a new article in the category you gave the 'create' and 'edit.state' permissions to.
#### Expected result

The new article is saved and already published because the user has 'edit.state' permissions for the selected category.
#### Actual result

The article is created but it's unpublished.

(That's due to the fact that for new articles Joomla is consulting the root permissions of com_content).
#### System information (as much as possible)

Joomla! 3.4.1
#### Solution

The attached pull request fixes this problem by always displaying the 'state' fields if a new article is created, even though Joomla might later detect that 'edit.state' is not allowed. In the latter case JForm will reset the 'state' fields before saving.

Since this approach assumes that valid articles that are going to be saved always have a category ID, this pull request also fixes the bug of being able to submit an article without a category (by tampering with the HTML in the edit form).

### CODE REVIEW

**Comment by James-Antrim** [comment]
@test The effect targeted by the author tested successfully according to the approach described by the author. However, if the user is not autorized to publish for a category, this perpetuates the same 'fraud' which the category field itself gives the user. That is it givves the usr the feeling he can perform actions he is not actually allowed to do. In the case of categories saving in an unauthorized category still gives the user the 'submitted successfully' message.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7004">issues.joomla.org/joomla-cms/7004</a>.</sub>

**Comment by Chraneco** [comment]
Yes, in this case the article is saved successfully, but it gets unpublished.
I don't think there is any way around that because we cannot predict in which category the user will create the article.

**Comment by Bakual** [comment]
Shouldn't it work when the author just edits the article a again after it's saved (unpublished)?
It's not ideal, I agree. But showing the state field for people who can't edit it is far less ideal.

I don't think I like the proposed change here.

**Comment by Chraneco** [comment]
This is very inconvenient and it works only if the frontend user also has the ```edit``` permission, not only ```edit.state```.

**Comment by Bakual** [comment]
True, it's inconvenient. But I don't think it's a good idea to change something for everyone else just because a certain usecase requires some inconvenient workflow. That's not a good way.

If you want to fix this, you need to check if any of the available category for the user allows to edit the state.

**Comment by Chraneco** [comment]
It's not only inconvenient, but also impossible if the user does not have the ```edit``` permission.

I can fix it by checking the permissions for all categories in the dropdown box, if that overhead is okay for you.

**Comment by Bakual** [comment]
I don't care much the performance impact in an edit form. It's not like that one is requested multiple times per second :smile:

**Comment by slibbe** [comment]
Patch works as described.

**Comment by zero-24** [comment]
RTC based on testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7004">issues.joomla.org/joomla-cms/7004</a>.</sub>

**Comment by Bakual** [comment]
Still don't like this in current form.

**Comment by Kubik-Rubik** [comment]
Thank you for your suggestion @Chraneco but it has been decided that this is not something that will be included in the core of Joomla! in this form at the moment.

**Pull request closed without merging**
