### PR TITLE
[js message system] Add close button

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This simple PR adds a close button to the JS message system, just like the one that exists for the php message system.

This applies to all js messages (error, warning, success or info messages).
#### Testing Instructions
1. Use latest staging
2. Go to Menus -> Message -> Add new menu item and Save without any field, you'get a js erro message.
   image
3. Apply patch, refresh browser cache and repeat the same process, you'll now get a close button in the message (test it)
   image

Test also on frontend js messages (ex: email remainder or other).

### CODE REVIEW

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 015a2896d3540f1c685bcfda01cf45a2ae9dbe35<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10517">issues.joomla.org/joomla-cms/10517</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 015a2896d3540f1c685bcfda01cf45a2ae9dbe35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10517">issues.joomla.org/joomla-cms/10517</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10517">issues.joomla.org/joomla-cms/10517</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
