### PR TITLE
[5.0] Fix tinyMCE drag and drop images

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #41527 .

### Summary of Changes

TinyMCE v6 has strict types for the options, now it needs a setter and a getter

### Testing Instructions

Try to upload an image

### Actual result BEFORE applying this Pull Request

Broken

### Expected result AFTER applying this Pull Request

Not broken

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

@brianteeman if you find another such error please tag me

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7228be4383ada6eeac10ae2e42973ecf70e0a2e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41528">issues.joomla.org/tracker/joomla-cms/41528</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41528">issues.joomla.org/tracker/joomla-cms/41528</a>.</sub>

**Comment by dgrammatiko** [comment]
@brianteeman @Quy I made a mistake, the options should be registered at the plugin level not the main instance of tinyMCE. Also the plugin was transformed to ESM so it can be linted.

If you don't mind please rede your tests (sorry)

**Comment by laoneo** [comment]
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41528">issues.joomla.org/tracker/joomla-cms/41528</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2464ad47017abd3dff92f17fe4da8670471f843e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41528">issues.joomla.org/tracker/joomla-cms/41528</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
