### PR TITLE
[4.0] Remove com_admin profile view

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
The PR https://github.com/joomla/joomla-cms/pull/32771 was merged, so view profile in com_admin is not used anymore, thus it could be removed.

### Testing Instructions
As it is not used, I don't know what should be testing instructions. Could it be merged on review @wilsonge ?

Or 

1. Enable at least one 2fa plugin
2. Setup "enforce 2fa" within the Users -> Manage -> Options
3. Make sure that you are redirected to edit user account page (before it's com_admin but now it is com_users)

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7b7c1d00495fa60d0cd4fc73fdbad49325c245b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32933">issues.joomla.org/tracker/joomla-cms/32933</a>.</sub>

**Comment by zero-24** [comment]
That code path has to be adjusted too: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/CMSApplication.php#L1291-L1324

**Comment by joomdonation** [comment]
Thanks @zero-24 . Could you please take a look at my last commit to see if it is OK? I don't use two factor authentication nor know how it works to check and confirm that myself.

**Comment by zero-24** [comment]
Looks good on a quick look but should be added to the testing instructions 

- apply this PR
- enable atleast one 2fa plugin
- setup "enforce 2fa" within the Users -> manage -> options 
- make sure that you are redirected to com_users vs com_admin before

**Comment by joomdonation** [comment]
Thanks @zero-24. I updated the testing instructions with your suggestions.

**Comment by wilsonge** [comment]
Looks like RIPs is down. But I'm happy to get this in to solve our release blocker given brians' good test and tobias review of the 2FA section. We can find the rest on general testing

**Comment by ceford** [comment]
Grrrrr! I have been developing a site that uses profile view. One difference is that registered users are not allowed to change Username in the profile view but they are in the user view. Another is the absence of the User Status toggle. Does changing that to Blocked result in the user blocking himself? A Manager does not have access to the User component so needs to use the Edit Account button from the User Menu in the Title Bar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32933">issues.joomla.org/tracker/joomla-cms/32933</a>.</sub>

**Comment by joomdonation** [comment]
@ceford : Don't worry. User can edit their account from administrator area of your site now directly via com_users (not depend on his user group). It is the result of this PR https://github.com/joomla/joomla-cms/pull/32771

**Comment by ceford** [comment]
A Manager group user does not have a Users item in the left menu (good) so needs to use the top right User Menu -> Edit Account item (good). But, the User Options form has a Change Username option which is set to No and that is being ignored in the form. The Username can be changed. So I am worried!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32933">issues.joomla.org/tracker/joomla-cms/32933</a>.</sub>

**Comment by joomdonation** [comment]
> A Manager group user does not have a Users item in the left menu (good) so needs to use the top right User Menu -> Edit Account item (good). But, the User Options form has a Change Username option which is set to No and that is being ignored in the form. The Username can be changed. So I am worried!

Thanks @ceford . I think we can come up with a solution for this problem. I will make a PR for that later. Anything else you concern about the change from com_admin to com_users?

**Comment by ceford** [comment]
> Anything else you concern about the change from com_admin to com_users?

In profile view the Login Name field has a descriptor - useful when that field is disabled. And the Receive System Emails field is not present in the profile view. I am not sure what is meant by System in this case. For example, does that include the email containing a pw reset token? Or emails from custom applications. I would like it be configurable so anyone less than Super Administrator cannot change it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32933">issues.joomla.org/tracker/joomla-cms/32933</a>.</sub>

**Pull request merged**
