### PR TITLE
[4.1] com_templates duplicate id

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #29423 .

## Steps to reproduce the issue
Go to /administrator/index.php?option=com_templates&view=templates
Click on Cassiopeia Details and Files
Inspect the page source
Expected result
Every ID should be unique

## Actual result
Conflicting ID's (adminForm)

### Summary of Changes
As far as I can tell it is perfectly safe to remove the id from the copy template form as its no different to the rename file form which also doesnt have an id

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 09220e66c88daea215c08f77566a647c1f90ede2<br /><br />Could edit, rename and save files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37131">issues.joomla.org/tracker/joomla-cms/37131</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09220e66c88daea215c08f77566a647c1f90ede2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37131">issues.joomla.org/tracker/joomla-cms/37131</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37131">issues.joomla.org/tracker/joomla-cms/37131</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
