### PR TITLE
[4.0] Fix content margin if no "top" modules are assigned

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #17698

### Summary of Changes

This PR fixes the top margin that should be assigned to any `<div>` that comes after the header. The issue before was the scope of the CSS.

### Testing Instructions

- Disable the `banner` and all modules assigned to the `top-a` and `top-b` positions.

There should be a space between the header and next element.

### CODE REVIEW

**Comment by C-Lodder** [comment]
Ignore the Windows lines endings in the CSS file.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3689e4bb707424f617c0211fe4927a6a1c2b4ffa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17699">issues.joomla.org/tracker/joomla-cms/17699</a>.</sub>

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on 3689e4bb707424f617c0211fe4927a6a1c2b4ffa<br /><br />
## Tested successfully

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17699">issues.joomla.org/tracker/joomla-cms/17699</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
