### PR TITLE
[4.0] com_workflow: Missing Value for "Count States"  - fixes #21634

### LINKED ISSUE #21634: [4.0] com_workflow: Missing Value for "Count States"
### Steps to reproduce the issue
As Title say:

screen shot 2018-08-16 at 07 15 04
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21634

### Summary of Changes
Use correct language constant
### Testing Instructions
code review
### Expected result
Correct language constant is used
### Actual result
Wrong language constant is used.
### Documentation Changes Required
No

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0db268ce6d4b797e423becdd86c971654920e801<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21635">issues.joomla.org/tracker/joomla-cms/21635</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0db268ce6d4b797e423becdd86c971654920e801<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21635">issues.joomla.org/tracker/joomla-cms/21635</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
Thanks for solving Issue.

**Comment by wojsmol** [comment]
@franz-wohlkoenig Please add `New Feature Workflow` label removed by bot.

**Comment by ghost** [comment]
@wojsmol have no access at Github to do Labels; only at Issue Tracker.

**Comment by brianteeman** [comment]
I did it for you

**Comment by ghost** [comment]
@brianteeman i saw, thanks. Comment was why i haven't done.

**Pull request merged**
