### PR TITLE
[6.0] Removing CMS Input package

### LINKED ISSUE #44928: Readd the deprecated app and input classes to the compatibility plugin
The Input and cli classes should be readded to the compat plugin as they got removed without the transient step in the compat plugin.

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
The CMS input package has been deprecated for some time now and the framework input package is replacing it. This PR removes what we can remove of the input classes. The Cli class unfortunately has to stay at least for the time being and extend from the framework class. 

This PR depends on #42805
### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [X] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/248
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
What do you think about adding a class alias to from `Joomla\CMS\Input\Input` to `Joomla\Input\Input`?

**Comment by laoneo** [comment]
I meant [here](https://github.com/joomla/joomla-cms/blob/6.0-dev/plugins/behaviour/compat/src/classmap/classmap.php).

**Comment by laoneo** [comment]
Can you also ad a manual entry?

**Comment by Hackwar** [comment]
done.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
