### PR TITLE
[3.x] Add joomla-backports/phpmailer to CMS repo

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Replaced the "original" PHPMailer library with the version from https://github.com/joomla-backports/PHPMailer

### Testing Instructions
1. Set up site with working with working mail system (SMTP, mail(), sendmail). 

2. Send test mail using the according button in the global configuration, verify mail arrived

3. apply patch

4. repeat step 2

### Actual result BEFORE applying this Pull Request
Mail is sent.

### Expected result AFTER applying this Pull Request
Mail is sent.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
@SniperSister I have three questions:

1. The composer lock shows an update of the filter package from 2.0.0-beta3 to 2.0.0-beta4 (`"source": "https://github.com/joomla-framework/filter/tree/2.0.0-beta4"`), but that's not mentioned in the description of this PR. Is this intended?
2. I remember that in somce cases we had to add some array_values here or there before doing array_merge, but at this place this PR seems to revert that:
https://github.com/joomla/joomla-cms/pull/33772/files#diff-e415170f630137edaae6308a219e26f6a96f6bcc1641212dc4e7d931e4ac0f7dL63-R63
Can it be that we had a correction here which gets lost now with this PR because we hadn't ported that correction to the backport package?
3. Does it really need to add also stuff like the pull request template and the readme and so on? If so: Should the build script be extended so they not included in the packages?

**Comment by richard67** [comment]
The change with array_values which I've mentioned with the 2nd point in my above comment has been added by @HLeithner with PR #31440 . The PR doesn't tell anything about it in the description or any comments. Shall we keep that change?

**Comment by richard67** [comment]
The composer step is constantly failing in Drone at cloning the lessphp backport, see https://ci.joomla.org/joomla/joomla-cms/43478/1/2 .

**Comment by HLeithner** [comment]
I think the concept using 
```
      {
        "type": "github",
        "url": "https://github.com/joomla-backports/PHPMailer.git"
      }
```
doesn't scale, we hit the free download limit even if I added my personal token...

**Comment by SniperSister** [comment]
> The composer lock shows an update of the filter package from 2.0.0-beta3 to 2.0.0-beta4 ("source": "https://github.com/joomla-framework/filter/tree/2.0.0-beta4"), but that's not mentioned in the description of this PR. Is this intended?

@richard67 If I see that correctly it's just the "support" section, there is no actual update of the package being applied

> I remember that in somce cases we had to add some array_values here or there before doing array_merge, but at this place this PR seems to revert that:

I re-added the array_values

> Does it really need to add also stuff like the pull request template and the readme and so on? If so: Should the build script be extended so they not included in the packages?

Removed from PR

> doesn't scale, we hit the free download limit even if I added my personal token...

@HLeithner I think I have a workaround - no-api flag seems to fix the issue

**Comment by richard67** [comment]
@SniperSister Is it desired that the stuff for tests is added to the `libraries/vendor/composer/autoload_classmap.php` and the `libraries/vendor/composer/autoload_static.php` file? Or should the composer maybe have been run with the `--no-dev` option to exclude that?

**Comment by SniperSister** [comment]
@richard67 good catch, fixed!

**Comment by HLeithner** [comment]
> @HLeithner I think I have a workaround - no-api flag seems to fix the issue

Created a pull request on the main repo https://github.com/joomla/joomla-cms/pull/33869

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 27637451a764de0be7804e8e29224927d1c7f164<br /><br />Tested with PHP 7.4 and with PHP 8.0, in both cases only with SMTP.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33772">issues.joomla.org/tracker/joomla-cms/33772</a>.</sub>

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 27637451a764de0be7804e8e29224927d1c7f164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33772">issues.joomla.org/tracker/joomla-cms/33772</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33772">issues.joomla.org/tracker/joomla-cms/33772</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
