### PR TITLE
Back-end: Missing language string in admin com_media.ini

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/8489
The issue is present in Isis as well as Hathor because the string is missing in back-end.

To test, click the article Image button when using TinyMCE

<b<Before patch</b>

screen shot 2015-11-19 at 11 34 11

<b>After patch</b>

screen shot 2015-11-19 at 11 33 44

@waader @joomlacorner @fontanil

### CODE REVIEW

**Comment by dgt41** [comment]
@test ok here!

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on c9d84fc925431147e1b5ace842f398b801c7eeca<br /><br />Thanks infograf768!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8490">issues.joomla.org/joomla-cms/8490</a>.</sub>

**Comment by infograf768** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8490">issues.joomla.org/joomla-cms/8490</a>.</sub>

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on c9d84fc925431147e1b5ace842f398b801c7eeca<br /><br />Tested on Isis +<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8490">issues.joomla.org/joomla-cms/8490</a>.</sub>

**Comment by infograf768** [comment]
This has to go into 3.5.0

**Comment by zero-24** [comment]
Thanks just added the milestone :+1:

**Pull request merged**
