### PR TITLE
sync lang strings

### PR DESCRIPTION
**Pull request by brianteeman**
As far as I can tell these two strings are not used on the front end anywhere but they should have the same value in the front end and the admin. Looks like when they were updated to be megabytes the strings were not updated

COM_MEDIA_FIELD_MAXIMUM_SIZE_DESC="The maximum size for an upload (in megabytes). Use zero for no limit. Note: your server has a maximum limit."
COM_MEDIA_FIELD_MAXIMUM_SIZE_LABEL="Maximum Size (in MB)"

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e570fde0133c48c460e21a97a4c7b868fa4c20f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12937">issues.joomla.org/tracker/joomla-cms/12937</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on e570fde0133c48c460e21a97a4c7b868fa4c20f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12937">issues.joomla.org/tracker/joomla-cms/12937</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12937">issues.joomla.org/tracker/joomla-cms/12937</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
