### PR TITLE
[4.0] Drop sql files and script.php code for unsupported upgrade paths

### PR DESCRIPTION
**Pull request by Bakual**
Based on the current valid [upgrade policy](https://developer.joomla.org/development-strategy.html#upgrade_policy) which says an upgrade to 4.0 is only supported from 3.9.

### Summary of Changes
* Removes all SQL files that are not related to 4.0
* Removes code in the script.php file which can be assumed to have run in 3.9.0.

### Testing Instructions
Could be tested by upgrading from 3.7 to 4.0. But I haven't tried if that even works yet. Most likely it's broken without this PR already :smile: 
Other than that it is code review.

### CODE REVIEW

**Comment by Bakual** [comment]
> What happens to the Database Fixer tool with the SQL files gone? I mean for sure it's not an upgrade path we support but unsure if the fixer tool is usable without it? It would at least mean people would be forced to run the fixer before they upgrade from 3.9 to 4

It would only apply SQL files from 4.0 onwards, and yes it would mean people have their site up to date prior to the upgrade.
Do you think we can't assume people have a working installation before they upgrade?
Maybe we can add a check to the Joomla Update component which shows a warning if the fixer detects an issue to prevent people accidentally upgrading a broken installation?

Imho it's a step we have to take eventually anyway. We have files going back to 2.5.0 in 2011 there...

**Comment by zero-24** [comment]
Is there a reason we do not support updates from 3.8.last to 4.0? As 3.9 and 4.0 are currently planed to be released at the same time?

**Comment by mbabker** [comment]
From a practical perspective, it probably won't be much different unless we remove something from the deleted files/folders list that gets removed between 3.8 and 3.9 and inherently wouldn't be in 4.0.  As a matter of policy though, let's keep the main focus on 3.last to 4.0 then take into consideration supporting additional releases as practical.

**Comment by wilsonge** [comment]
Can you fix conflicts and I'll get this merged :)

**Comment by Bakual** [comment]
Rebased and conflicts solved.

**Comment by brianteeman** [comment]
@wilsonge reminder to merge this

**Comment by wilsonge** [comment]
Thanks for the reminder :)

Thanks @Bakual :)

**Pull request merged**
