### PR TITLE
[com_fields] Multilanguage: fixing display of fields when the item concerned is set to ALL

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #18396 , replaces https://github.com/joomla/joomla-cms/pull/18474

Issue: An item (article in that case) tagged to ALL languages is displaying all fields tagged to specific languages.

### Summary of Changes
When an item is tagged to ALL languages, only display custom fields tagged to ALL languages as well as custom fields tagged to the Active language.

### Testing Instructions
Create a multilingual site. 2 Content languages are enough. Here for en-GB and fr-FR
Structure:
===>Categories
screen shot 2017-11-02 at 09 44 48
===>Articles set as Featured
screen shot 2017-11-02 at 09 46 07
===> Home menu as Featured Articles menu item for each language.
screen shot 2017-11-02 at 09 50 10
===> Create some articles custom fields and assign languages, including ALL
screen shot 2017-11-09 at 08 35 51

### Expected result
Example for articles for a multingual site with 2 Content Languages:

For an article tagged to ALL, only custom fields tagged to ALL as well as custom fields tagged to the Active language should display. 
This to follow the current behavior of any item on a multilang site: items set to ALL display whatever the language, items set to a specific language only display when the language is the active one.

### Actual result
Custom fields tagged to ALL as well as custom fields tagged to any Content Language are displayed

### Before patch
French
screen shot 2017-11-08 at 08 52 57
English
screen shot 2017-11-08 at 08 53 16
### After Patch
French
screen shot 2017-11-09 at 08 27 57
English
screen shot 2017-11-09 at 08 30 24

@laoneo 
@AlexRed 
@ajejebrazorf01
@ggppdk

### CODE REVIEW

**Comment by infograf768** [comment]
This PR does not solve yet the filtering of User custom fields (profile) as discussed in https://github.com/joomla/joomla-cms/pull/18474#issuecomment-342917260

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 28d51327b7c8d3e41df3dcbf0be4c3b892a2666c<br /><br />Patch ok for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18536">issues.joomla.org/tracker/joomla-cms/18536</a>.</sub>

**Comment by ghost** [comment]
@ajejebrazorf01 can you please test?

**Comment by jreys** [comment]
I have tested this item :white_check_mark: successfully on 28d51327b7c8d3e41df3dcbf0be4c3b892a2666c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18536">issues.joomla.org/tracker/joomla-cms/18536</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@laoneo 
Shall I now create a PR for the profile issue with the code I proposed here?
https://github.com/joomla/joomla-cms/pull/18474#issuecomment-342779558

Free to all to propose a better solution, if it exists.

**Comment by laoneo** [comment]
I can have a look on JWC.

**Comment by laoneo** [comment]
Can you make a pr with the proper testing instructions, I can't reproduce it. Probably I do something wrong.

**Comment by infograf768** [comment]
@laoneo 
> Can you make a pr with the proper testing instructions, I can't reproduce it. Probably I do something wrong.

Will do.

**Comment by infograf768** [comment]
@laoneo 
See https://github.com/joomla/joomla-cms/pull/18743

**Review by laoneo — APPROVED** [review]

**Pull request merged**
