### PR TITLE
[4.0] cli remove old files

### PR DESCRIPTION
**Pull request by brianteeman**
Quick fix to change the success message

Pull Request for Issue #31901

### CODE REVIEW

**Comment by PhilETaylor** [comment]
the tools doesn't only remove files, it[ removes folders too ](https://github.com/joomla/joomla-cms/blob/4c434000c9ba717602846a144b709e0a66a3631d/administrator/components/com_admin/script.php#L2310)- so there is much more that could change...

The administrator/components/com_admin/script.php also outputs error messages that are not caught by the console command output streamer as well.

**Comment by brianteeman** [comment]
Folders is a level of pedantry I'm not going to entertain. The pr addresses the reported issue.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 60aaf53e2ffcbedbbd4f0722ccadd2d89bcbde74<br /><br />Before the PR the command response is:
 [OK] Files removed                                                                                                     
After the PR the command response is:
 [OK] There are no old files left to remove                                                                             
So just changing the response message works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31914">issues.joomla.org/tracker/joomla-cms/31914</a>.</sub>

**Comment by alikon** [comment]
this is not correct
put a dummy file at `'/administrator/components/com_actionlogs/actionlogs.php',`
run `php cli/joomla.php update:joomla:remove-old-files`

you'll get always the message
 [OK] There are no old files left to remove

**Comment by brianteeman** [comment]
@alikon thats not related. The file you added is not an "old file"

**Comment by alikon** [comment]
it is an old file https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L476

**Comment by brianteeman** [comment]
In that case there is a problem with the script if its not removing files. All this PR does is to modify the string the script outputs on completion. Any issues with the script not working is completely off topic and should have its own issue.

**Comment by alikon** [comment]
> All this PR does is to modify the string the script outputs on completion. Any issues with the script not working is completely off topic and should have its own issue.



which is wrong imho they are strictly related
the correct command output should be 

- files/folder removed if 1 or more file/folder file was removed
- no files/folders to remove if no file/folder file was removed

and yes the `script.php` must be modifyed to return at least a boolean

**Comment by PhilETaylor** [comment]
If the script returned an array of files and their statues, and information on the action then the command could show WHICH files it deleted, WHICH it checked etc. 

Then the correct use of command verbose level could be used (-v -vv -vvv) to display a summary, more detail and debug information

Verbose is what makes a command so useful.

The command deletes folders too and therefore this PR just makes an inaccurate string just as inaccurate

**Comment by PhilETaylor** [comment]
The command should also have a --dry-run option

**Comment by brianteeman** [comment]
Got to love bikeshedding

**Comment by alikon** [comment]
still need to fully understand what _bikeshedding_ means 
:smile:  but...

**Comment by PhilETaylor** [comment]
Basically he's using it as an abusive term towards me because he doesn't have the skills to correctly address the issue and wants to belittle me for wanting the best from joomla and for offering my valid comments on how joomla can do much better, which he doesn't see as valid - unless I invest my time in writing the PR myself. I've come to expect nothing less. 

All the commands in joomla are currently a joke and don't fully implement Symfony command logic in a way that people that have been using Symfony based commands for years come to expect as a minimum. This is just the latest example. 

The commands do the bare minimum currently and don't honour the built in modes like verbosity 

"Doing something right" is better than ignoring the issue. 

And like you say, it seems this command doesn't even do what it should - delete files!

**Comment by brianteeman** [comment]
I am using it as a term to indicate that the conversation you are having is unrelated to the actual issue. As for your consistent criticism of others people work and only being willing to contribute a spellcheck - everyone knows that you are just a leach who takes from joomla without giving back.

**Comment by PhilETaylor** [comment]
Screenshot 2021-01-09 at 13 20 23

**Pull request closed without merging**
