### PR TITLE
[4.0] ViewType.php (like html.php) in favor of view.ViewType.php for autoloading

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Example: view.html.php -> html.php

Remove `view.` from the view files (like view.html.php) in the controller loading in favor of only having the type as file name.

If the file is not existing we check if there is one with the old filename pattern.

### Testing Instructions

Confirm that everything is still working and if you add a html.php in an component view this should be loaded instead of the view.html.php

### Documentation Changes Required

Dev documentation

### CODE REVIEW

**Comment by mbabker** [comment]
Unless you're going to fix the class name logic in the controller and view layers as well which results in duplicate class names all over the place this isn't doing anything useful on its own.

**Comment by yvesh** [comment]
@mbabker 4.x branch, class names should be namespaced there (something like Joomla\Content\Article\Html)

**Comment by mbabker** [comment]
Then here is my suggestion.  `view.<format>.php` files follow the current class name convention with all its flaws and the new files can only contain "properly" named classes.  But please do not try to make the code support finding `ContentViewArticle` in the non-view-prefixed filenames or finding namespaced classes in the view-prefixed filenames.

Either way, I do think the class name logic needs to be included in this PR before it should be merged.  Otherwise the code is in a state of flux where files can have multiple names for the same thing.

**Comment by yvesh** [comment]
Closing this, as we decided to not touch the legacy system and in the namespaced version it's different anyways.

**Pull request closed without merging**
