### PR TITLE
[4] cleanup code

### PR DESCRIPTION
**Pull request by PhilETaylor**
Some people read a book in bed, I review code, don't @ me :) 

Code review

### CODE REVIEW

**Comment by alikon** [comment]
I have not tested this item.<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33959">issues.joomla.org/tracker/joomla-cms/33959</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6faef61a4522c19971542602dfb6987b7f336245<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33959">issues.joomla.org/tracker/joomla-cms/33959</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6faef61a4522c19971542602dfb6987b7f336245<br /><br />I can confirm that the `text`function of the `SymfonyStyle` class has only 1 parameter. I hope that was the right place to check.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33959">issues.joomla.org/tracker/joomla-cms/33959</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33959">issues.joomla.org/tracker/joomla-cms/33959</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33959">issues.joomla.org/tracker/joomla-cms/33959</a>.</sub>

**Comment by chmst** [comment]
@richard67 I hope so too :). 
Thanky you all

**Comment by PhilETaylor** [comment]
Rest assured this PR is right. The `text` and `error` methods both have one param.

```
/**
     * {@inheritdoc}
     */
    public function text($message)
    {
        $this->autoPrependText();

        $messages = \is_array($message) ? array_values($message) : [$message];
        foreach ($messages as $message) {
            $this->writeln(sprintf(' %s', $message));
        }
    }

    public function error($message)
    {
        $this->block($message, 'ERROR', 'fg=white;bg=red', ' ', true);
    }
```

**Pull request merged**
