### PR TITLE
[4.0] Fix translation of tip in installer update manager

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/29039

### Summary of Changes
Using Text method to translate the description

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/29039

Can be tested/merged on review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Doesn't work. Language files aren't loaded.

**Comment by infograf768** [comment]
I have no extension to test, but the example in https://github.com/joomla/joomla-cms/issues/29039 displays a constant, which means the string exists and displayed. Is'nt it?

**Comment by SharkyKZ** [comment]
I see the issue now. In J3 we use description from remote update file and in J4 from extension's manifest file. I don't know why this change was made. Looks like it's by mistake.

**Comment by richard67** [comment]
> I see the issue now. In J3 we use description from remote update file and in J4 from extension's manifest file. I don't know why this change was made. Looks like it's by mistake.

Possibly @zero-24 knows if that has been changed by purpose?

**Comment by zero-24** [comment]
I can not follow what the issue here is nor how i can help on that? Any more context might help?

**Comment by richard67** [comment]
@zero-24 When you hover over the extension names in the list of available updates (if any) you het a tool tip with the description of the extension. In J3 we use description from remote update file and in J4 from extension's manifest file. I thought maybe you know where this difference between J3 and J4 comes from since I remember you worked much on extension update checks.

**Comment by zero-24** [comment]
I'm not aware of why this might has been changed.

**Comment by SharkyKZ** [comment]
My 2c says this was changed by mistake. See PR https://github.com/joomla/joomla-cms/pull/29619 for changing back to use remote XML description.

**Comment by wilsonge** [comment]
Merged #29619 so closing this

**Pull request closed without merging**
