### PR TITLE
Deprecating loadFieldType & loadRuleType

### PR DESCRIPTION
**Pull request by Hackwar**
This is the PR to deprecate these 2 methods for #12414

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 4f91dcc041c820008a1ab7d67379511c13aa88cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23478">issues.joomla.org/tracker/joomla-cms/23478</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4f91dcc041c820008a1ab7d67379511c13aa88cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23478">issues.joomla.org/tracker/joomla-cms/23478</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23478">issues.joomla.org/tracker/joomla-cms/23478</a>.</sub>

**Comment by Hackwar** [comment]
@wilsonge Since #12414 has been merged, we need this one merged, too.

**Pull request merged**
