### PR TITLE
[4.0] Fix tinymce modals size

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Fix he modals sizes for the XTD Buttons

### Testing Instructions

Apply the patch and test the joomla XTD Buttons, (menu, articles, images, etc)

### Expected result

screen shot 2017-09-09 at 16 29 43

### Documentation Changes Required
None, bug fix

### CODE REVIEW

**Comment by C-Lodder** [comment]
@wilsonge or @mbabker  please merge

**Comment by infograf768** [comment]
@dgt41 
This does not solve the issue on smaller screens (IPhone) where we can't even close the modals

**Comment by infograf768** [comment]
TinyMCE

**Comment by dgrammatiko** [comment]
@infograf768 one of the reqsons we started moving the xtd-buttons (now only the media is done as a showcase) into tinymce native plugins

**Pull request merged**
