### PR TITLE
updated passwordstrength.js to related to issue #19231

### PR DESCRIPTION
**Pull request by amone4**
replaced the jquery in my already uploaded code, with js

Pull Request for Issue # .

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Nice, but we don't need javascript to do width restriction here, css is invented just for that:
screen shot 2018-03-21 at 23 29 46

```css
joomla-field-password > .progress {
	max-width: 277px;
}
```

**Comment by amone4** [comment]
I don't know where all this script would be used, as this can be used to generate a password strength bar on any page. The width of form fields might vary and might occupy more space than 277px. That's why I used js to resize the bar, according to the corresponding form field

**Comment by C-Lodder** [comment]
**Markup:**
```
<joomla-field-password>
    <div class="password-input-wrapper">
        <input type="password" class="form-control">
        <div class="progress"></div>
    </div>
</joomla-field-password>
```

**SCSS:**
```
$input-max-width: 240px;

.password-input-wrapper {
   max-width: $input-max-width;
}
```

Progress bar will be 100% width as it's a block element and contained within the wrapper.

No need for JS on this at all

**Comment by amone4** [comment]
If we can change the markup and style of elements other than the progress bar, then the issue can be solved just by appending the following in passwordstrength.js

`fields[i].parentElement.parentElement.style.width = 'fit-content';`

The solution works. Should I make a pull request?

**Comment by C-Lodder** [comment]
Nothing needs to be appended. It simply needs a wapper as shown above. There's already a pending PR for this so any changes should be made there

**Comment by amone4** [comment]
Joomla's code already makes up a wrapper with class `password-group`. I'm just asking if we could style that with `width: fit-content`, because it does the issue.

image

**Comment by dgrammatiko** [comment]
> Joomla's code already makes up a wrapper with class password-group. I'm just asking if we could style that with width: fit-content, because it does the issue.

The code you're looking at is deprecated!
Please follow our suggestions and use https://github.com/joomla/joomla-cms/pull/19231 as your base...

**Pull request closed without merging**
