### PR TITLE
[4.0] Update composer and remove dummy random_compat

### PR DESCRIPTION
**Pull request by brianteeman**
Alternative PR to #34252

### CODE REVIEW

**Comment by brianteeman** [comment]
@zero-24 this pr passes drone and the appveyor failure looks to be unrelated

**Comment by brianteeman** [comment]
All tests have now passed @zero-24

**Comment by zero-24** [comment]
Interesting that all the "funding" informations are removed here too. Looks good on a quick look, thanks dont know what happend with mine. :)

**Comment by brianteeman** [comment]
@zero-24 as you have successfully tested this please mark it as a successful test

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 6535d2a044b60ac816ad33b446cf079aea5c218f<br /><br />PHP 8.0.6
node 16.2.0
npm 7.14.0
Your Composer version 2.0.14
BTW: 51 vulnerabilities (44 moderate, 5 high, 2 critical) in npm, and after  npm audit fix --force, 12 vulnerabilities (7 low, 5 high)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34267">issues.joomla.org/tracker/joomla-cms/34267</a>.</sub>

**Comment by Krshivam25** [comment]
I have tested this item :white_check_mark: successfully on 6535d2a044b60ac816ad33b446cf079aea5c218f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34267">issues.joomla.org/tracker/joomla-cms/34267</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34267">issues.joomla.org/tracker/joomla-cms/34267</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
