### PR TITLE
[mod_custom]XML code style

### PR DESCRIPTION
**Pull request by wojsmol**
### Summary of Changes

Code style changes for mod_custom
### Testing Instructions

code review

cc @JoomliC @andrepereiradasilva

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on eb07e9fd2ffbd85a4342213a95c07cffddb9d90f<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10579">issues.joomla.org/joomla-cms/10579</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on eb07e9fd2ffbd85a4342213a95c07cffddb9d90f<br /><br />@wojsmol in future can you do one pull request for any other changes instead of one per file. Now that we have agreed the structure of the changes it will make life easier if any more fixes are done in a single PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10579">issues.joomla.org/joomla-cms/10579</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10579">issues.joomla.org/joomla-cms/10579</a>.</sub>

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on eb07e9fd2ffbd85a4342213a95c07cffddb9d90f<br /><br />On code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10579">issues.joomla.org/joomla-cms/10579</a>.</sub>

**Pull request closed without merging**
