### PR TITLE
[4] remove method allow parent to run

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review. 

This code is not needed, the parent class `_getList` can be used instead.

`$odd` is not actually used in the view either. 

//cc @joomdonation

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on f6effc70192f804ff116eb3c4ed15a51e6a59e5c<br /><br />Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34118">issues.joomla.org/tracker/joomla-cms/34118</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f6effc70192f804ff116eb3c4ed15a51e6a59e5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34118">issues.joomla.org/tracker/joomla-cms/34118</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34118">issues.joomla.org/tracker/joomla-cms/34118</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor After your other PR #34060 has been merged, this one had a conflict. I've allowed myself to solve it and think I did it right. But I'd feel safer if you could have a quick look on it. The diff on GitHub looks strange but I think that's just GitHub.

**Pull request merged**
