### PR TITLE
fix pagebreak regex from being too greedy

### PR DESCRIPTION
**Pull request by beetabonk**
the previous regex destructively strips the article text from the first ```<hr />``` on a page to the next ```<hr class="system-pagebreak" />``` if content does not contain TinyMCE type line-breaks.

Pull Request for Issue #14531 .

### Summary of Changes

contain page-break regex to a single ```<hr ... />```

current regex will match 
```html
<hr /><p>paragraph under first hr tag</p><hr /><p>paragraph under second hr tag</p><hr class="system-pagebreak" />
```

### Testing Instructions

create an article with an ```<hr />``` anywhere prior to an ```<hr class="system-pagebreak" />``` and display on front-end.  

test article exhibiting problem and fix
```html
<p>first paragraph</p>
<hr id="system-readmore" />
<p>second paragraph</p>
<hr />
<p>third paragraph</p>
<hr />
<p>fourth paragraph</p>
<hr class="system-pagebreak" />
<p>fifth paragraph</p>
<hr />
<p>sixth paragraph</p>
```

**[update 2017/03/13]**

the test article actually works with line-breaks but not without them which can occur with any DOMDocument type processing or content created by API instead of directly with TinyMCE.  so the following article HTML will exhibit the problem if entered directly into the `#__com_content` table.

```html
<p>first paragraph</p><hr id="system-readmore" /><p>second paragraph</p><hr /><p>third paragraph</p><hr /><p>fourth paragraph</p><hr class="system-pagebreak" /><p>fifth paragraph</p><hr /><p>sixth paragraph</p>
```
**[end update]**

### Expected result

no stripping of article content

output from test html above

    first paragraph
    second paragraph
    ------------------
    third paragraph
    ------------------
    fourth paragraph
    « Start Prev 1 2 Next End»

### Actual result

html between ```<hr />``` and page break is stripped.

output from test html above

    first paragraph
    second paragraph
    « Start Prev 1 2 Next End»

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
i can see no Difference between Article with and -out PR.

**Comment by beetabonk** [comment]
@franz-wohlkoenig i added test html above.

```html
<p>first paragraph</p>
<hr id="system-readmore" />
<p>second paragraph</p>
<hr />
<p>third paragraph</p>
<hr />
<p>fourth paragraph</p>
<hr class="system-pagebreak" />
<p>fifth paragraph</p>
<hr />
<p>sixth paragraph</p>
```

**Comment by franz-wohlkoenig** [comment]
tested on Joomla-3.6.5 without PR:
bildschirmfoto 2017-03-12 um 20 35 58
bildschirmfoto 2017-03-12 um 20 36 08

**Comment by beetabonk** [comment]
@franz-wohlkoenig I now see the reason this is happening on our sites and not for you.  

Some plugins we employ have the _harmless_ side-effect of stripping line-breaks by passing the article's HTML text through DomDocument processing resulting in the saveHTML method not maintaining line breaks.  We also create some of our content directly via an XML import process using JoomlaCLI which bypasses any TinyMCE line-break rules.  The problem I've reported is not apparent in the vanilla Joomla! 3.6.5 install but becomes apparent when for any reason the TinyMCE line-breaks rules are not maintained which is not a general enough solution.  This makes the **pagebreak** plugin unreasonably reliant on the source of the content.  This is not a bug _per se_ but the new regex provided offers a more general solution for handling HTML content without assumptions about its source and the placement of line-breaks so I recommend the new regex for generality.

the following content if created directly in the database will exhibit the problem reported:
```html
<p>first paragraph</p><hr id="system-readmore" /><p>second paragraph</p><hr /><p>third paragraph</p><hr /><p>fourth paragraph</p><hr class="system-pagebreak" /><p>fifth paragraph</p><hr /><p>sixth paragraph</p>
```

**Comment by franz-wohlkoenig** [comment]
any thoughts on this, @maintainers?

**Review by dgrammatiko — APPROVED** [review]

**Comment by brianteeman** [comment]
Closing as it is not a core issue

**Comment by beetabonk** [comment]
@brianteeman how is this not a core issue?  is it a requirement that all content be created by tinyMCE?  is the pagebreak content plugin shipped with joomla no longer maintained as part of the core?  it is a bad assumption and should be fixed.  it was already approved 6 months ago.

**Comment by brianteeman** [comment]
Because as you stated it is the plugins you are using etc that is stripping the required code.

**Comment by beetabonk** [comment]
where is it specified that line breaks are required?  the regex in question is written very very poorly.  it fails if the content does not come specifically and directly from tinyMCE.

**Pull request closed without merging**
