### PR TITLE
Fix: Post Install Messages sort order

### PR DESCRIPTION
**Pull request by zero-24**
### Issue

> The Messages are displayed in ascending ID which means that the oldest ones are at the top. I know there are only 3 right now but it makes more sense to me that the newest message is always at the top (ORDER BY postinstall_message_id DESC )
> 
> I did try to fix this myself but only managed to ADD it to the ORDER by not change it.

Fixing: https://github.com/joomla/joomla-cms/issues/8382
### How to test
- Install staging
- see there are postinstall messages
- see that the 3.2.0 one is on the top
- apply this patch using com_patchtester
- see there are now the newest on the top.

Thanks @brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3bec4dafb77fa63772ac9d6cce4f9201e6ed66a4<br /><br />Thanks - works perfectly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8458">issues.joomla.org/joomla-cms/8458</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 3bec4dafb77fa63772ac9d6cce4f9201e6ed66a4<br /><br />Thanks zero-24!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8458">issues.joomla.org/joomla-cms/8458</a>.</sub>

**Comment by zero-24** [comment]
Thanks. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8458">issues.joomla.org/joomla-cms/8458</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman @waader I have just got the tip by @roland-d  to do this with just one line so it is much cleaner and don't hack the state variable. Can you test again? Thanks.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7ff2882e870dd0f71a4ce24830d7d219d677ebe7<br /><br />Tested again - still works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8458">issues.joomla.org/joomla-cms/8458</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 7ff2882e870dd0f71a4ce24830d7d219d677ebe7<br /><br />Works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8458">issues.joomla.org/joomla-cms/8458</a>.</sub>

**Comment by zero-24** [comment]
Thanks :+1:

**Pull request merged**
