### PR TITLE
[4.0] Remove duplicate attribute

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove duplicate `type` attribute.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 2711344e7f361939c74ea289ad0d5b13168f6fb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26090">issues.joomla.org/tracker/joomla-cms/26090</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2711344e7f361939c74ea289ad0d5b13168f6fb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26090">issues.joomla.org/tracker/joomla-cms/26090</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
