### PR TITLE
[4.0] Fix subform with double field name

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #27307 .

### Summary of Changes

This fixes a name duplication, that may happen in specific cases.

### Testing Instructions
Apply patch, run `npm install`

Add subform field somewhere
```xml
<field name="test_fields" type="subform" label="test_fields" multiple="true" min="1" max="5">
  <form>
    <field name="test_field" type="text" label="TESTFIELD1"/>    
  </form>
</field>
```

Do steps described by @cinemarene in #27307:

Go to the form.
Now there is one row with key 0.
Add one row with "+" button.
Now there are two rows with 0 and 1.
Remove first row with key 0 over button "-".
Now there are one row with key 1.
Add one row with "+" button.
Now there are two rows with key 1 and 1.

### Expected result
You do not have duplicated field names

### Actual result
You have duplicated field names

### Documentation Changes Required
none

### CODE REVIEW

**Comment by richard67** [comment]
@Fedik Could you click the "Update branch" button at the bottom of your PR? I'd like to see if appveyor and drone will pass this time. Thanks in advance.

**Comment by Fedik** [comment]
it pass this time :)

**Comment by richard67** [comment]
Is like winning in lotto with the drone ;-)

**Comment by richard67** [comment]
will test later.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 74bbd662d87ae1cdb988780eb78aa5038113f792<br /><br />Tested with subform in "Users Options" > "Email Domain Options".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27342">issues.joomla.org/tracker/joomla-cms/27342</a>.</sub>

**Comment by richard67** [comment]
@cinemarene @ReLater Please test.

**Comment by ReLater** [comment]
> @ReLater Please test.

Sorry, I can't whenever `npm` is needed for testing.

**Comment by richard67** [comment]
@alikon Do you think you can test this PR? No need to add field code somewhere, you can use subform in "Users" -> "Manage" -> "Options" -> "Email Domain Options". You can add and remove rows with domain rules as described in the testing instructions and check the IDs of the fields with browser tools.

**Comment by Fedik** [comment]
in theory it should be just enough to run `node build.js --compile-js` for update the script of the custom element, instead of full `npm install`

**Comment by richard67** [comment]
@Fedik Yes, I know, it works, but that doesn't help those people who don't have node installed ;-)

**Comment by Fedik** [comment]
yeah, that true :)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 74bbd662d87ae1cdb988780eb78aa5038113f792<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27342">issues.joomla.org/tracker/joomla-cms/27342</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27342">issues.joomla.org/tracker/joomla-cms/27342</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by continga** [comment]
As far as I know, the fix from #22757 was necessary to fix that data is not being saved correctly when having nested subforms - see #22441 @dawe78 reports:
> Its not the id only, the issue affects name too - so saving fails.

@Fedik wrote in #27334 (the J!3 version of this PR):
>  In general, random row numbers does not lead to any functional issue.

So I have to disagree, see also #22690 !

#22757 was to fix those 2 bugs. I see now that it introduced a new bug, but just reverting the changes from #22757 will not help us very much, as those two older bugs now will be reintroduced. I still have to test this PR whether that is really the case, but we should really discuss whether we have a better solution to this than just reverting

**Comment by Fedik** [comment]
> So I have to disagree, see also #22690 !

You will have random numbers anyway.
In backend (server side) you should always do `$value = array_values($value)` (or use foreach) to get the list of rows, without these numbers.

**Comment by continga** [comment]
@Fedik it is **not** about random numbers. Please read #22690 thoroughly. The issue is about having nested subforms (a subform inside of a subform) and then adding a new row in the inner-most subform. This row will have the wrong name of its parent row and hence the backend cannot know to which outer subform row this inner childrow belongs.

**Comment by Fedik** [comment]
okay, I see, children loosing parent :)

Well, but that not a fix #22757 anyway,  it need to debug more, to find how to prepare a name, especially for children (need to avoid of losing a parent group somehow).

j4 and j3 has different handling of children: 
j3 have one subform instance common for all nested forms
j4 have one subfrom instance per nested

That bug for j3, need to test how it work in j4.

**Pull request merged**
