### PR TITLE
[com_fields] Check if multilanguage is enabled

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #12659.

### Summary of Changes
Adding an additional check if multilanguage is enabled.

### Testing Instructions
All should work as before when multilanguage is enabled and disabled.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9de50e36ef298f1518875a22bb540eca1f535f29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12675">issues.joomla.org/tracker/joomla-cms/12675</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9de50e36ef298f1518875a22bb540eca1f535f29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12675">issues.joomla.org/tracker/joomla-cms/12675</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12675">issues.joomla.org/tracker/joomla-cms/12675</a>.</sub>

**Comment by andrepereiradasilva** [comment]
mantainers remove RTC label here please

**Comment by brianteeman** [comment]
Your comment did it - the first comment after the merge removes the label

**Pull request merged**
