### PR TITLE
[4.3 RC] Unable to toggle check status of a single updated override file using the "Checked" status icon

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #40393 .

### Summary of Changes

Fix the logic

### Testing Instructions

follow the issue

### Expected result AFTER applying this Pull Request

This should be a release blocker

### CODE REVIEW

**Comment by Scrabble96** [comment]
I just tried to test this using the Patch Tester component and got this message:

"There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation."

My overrides are in a custom template, not Cassiopeia

**Comment by brianteeman** [comment]
you can not use patch tester for this type of pull request.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 04eac353618586f7eb7f8def4014c803e3cebd9e<br /><br />I've tested as described in my comment to the issue here: https://github.com/joomla/joomla-cms/issues/40393#issuecomment-1510356837 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40397">issues.joomla.org/tracker/joomla-cms/40397</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40397">issues.joomla.org/tracker/joomla-cms/40397</a>.</sub>

**Comment by MacJoom** [comment]
> you can not use patch tester for this type of pull request.

You can use patch tester for PR's with the tag "NPM Resource changed" only if you have setup a local environment for Joomla as described here: https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en - then the file(s) to be patched exist

**Comment by richard67** [comment]
@MacJoom You still need to run npm to compile the js after having applied the PR.

**Comment by MacJoom** [comment]
> @MacJoom You still need to run npm to compile the js after having applied the PR.

just updated my comment...

**Comment by brianteeman** [comment]
> > you can not use patch tester for this type of pull request.
> 
> You can use patch tester for PR's with the tag "NPM Resource changed" only if you have setup a local environment for Joomla as described here: https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment/en - then the file(s) to be patched exist

You really can't. People using patchtester expect to apply the patch and then be able to test - even with the files in their environment there is still a lot more to do. Far better to tell them the correc5t advice as provided by @richard67

**Comment by brianteeman** [comment]
>  or even jinstall after the patch

that's a new one???

**Comment by richard67** [comment]
> > or even jinstall after the patch
> 
> that's a new one???

@brianteeman I think he means making a new installation of Joomla e.g. when a PR has changed in SQL scripts for new installations.

**Comment by brianteeman** [comment]
seriously? ;)
if you are using patchtester then you almost certainly not in a position to create a bash alias script
a script which btw is hopelessy out of date

**Comment by obuisard** [comment]
Thanks Dimitris @dgrammatiko for the fix and all for testing!

**Pull request merged**
