### PR TITLE
Fix PHP CS errors introduced with PR 31672

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Use tabs and not spaces for indentation in PHP files.

### Testing Instructions

Code review + check that PHP CS succeeds in Drone tests.

### Actual result BEFORE applying this Pull Request

Spaces used for indentation at the end of file `layouts/joomla/form/field/password.php`.

PHP CS fails in Drone tests.

### Expected result AFTER applying this Pull Request

Tabs used for indentation at the end of file `layouts/joomla/form/field/password.php`.

PHP CS succeeds in Drone tests.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e116a82a8e5597ced96b6191af5762a505c4943f<br /><br />Tested successfully in 3.9.24-rc2 of 7 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31878">issues.joomla.org/tracker/joomla-cms/31878</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e116a82a8e5597ced96b6191af5762a505c4943f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31878">issues.joomla.org/tracker/joomla-cms/31878</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31878">issues.joomla.org/tracker/joomla-cms/31878</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
