### PR TITLE
Catch broken confirmConsent configuration

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue raised here: https://forum.joomla.de/thread/8188-dsgvo-anfrageformular-bringt-fehlermeldung/ (german)

### Summary of Changes

Make sure there is an article object. When not forward to an 404 error as the article ID does not exists.

### Testing Instructions

configure confirm consent
show it in the frontend
remove the article
try to show it in the frontend again

### Expected result

404

### Actual result

```
Notice: Trying to get property 'id' of non-object in /plugins/content/confirmconsent/fields/consentbox.php on line 252
Notice: Trying to get property 'language' of non-object in /plugins/content/confirmconsent/fields/consentbox.php on line 255
Notice: Trying to get property 'id' of non-object in /plugins/content/confirmconsent/fields/consentbox.php on line 269
Notice: Trying to get property 'catid' of non-object in /plugins/content/confirmconsent/fields/consentbox.php on line 269
Notice: Trying to get property 'language' of non-object in /plugins/content/confirmconsent/fields/consentbox.php on line 270
```

### Documentation Changes Required

none

### CODE REVIEW

**Comment by ChristineWk** [comment]
Confirm "Actual Result". After Patch: error 404 of previous removed article. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25858">issues.joomla.org/tracker/joomla-cms/25858</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6c9605ab90d9bbb85d20242b83c342c80f0db59e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25858">issues.joomla.org/tracker/joomla-cms/25858</a>.</sub>

**Comment by zero-24** [comment]
Thanks @ChristineWk for your tests 👍

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6c9605ab90d9bbb85d20242b83c342c80f0db59e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25858">issues.joomla.org/tracker/joomla-cms/25858</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25858">issues.joomla.org/tracker/joomla-cms/25858</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by zero-24** [comment]
Thanks 👍

**Comment by HLeithner** [comment]
Thank you very much for this failsafe.

**Pull request merged**
