### PR TITLE
s/platfom/platform

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/platfom/platform

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97c83bbe93e7a46aa7de1c6bffd495faf8ea0f7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22997">issues.joomla.org/tracker/joomla-cms/22997</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 97c83bbe93e7a46aa7de1c6bffd495faf8ea0f7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22997">issues.joomla.org/tracker/joomla-cms/22997</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22997">issues.joomla.org/tracker/joomla-cms/22997</a>.</sub>

**Comment by PhilETaylor** [comment]
Please merge to staging to - apparently this was targeted for 3.10-dev by mistake too

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Pull request merged**
