### PR TITLE
remove @-moz-document

### PR DESCRIPTION
**Pull request by CEWebDesign**
remove @-moz-document as suggested by @JoomliC here: #8595

### CODE REVIEW

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 700a98d1d97e0bf5c8e8285feb353214dfb20ec2<br /><br />Tested after installing patch for 'Create new Category from Article Edit mode' (#8623), as requested. Works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8601">issues.joomla.org/joomla-cms/8601</a>.</sub>

**Comment by JoomliC** [comment]
I have not tested this item.<br /><br />Tested on Firefox, and it's ok to remove this line, not anymore needed as commented here https://github.com/joomla/joomla-cms/pull/8595#issuecomment-162240352

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8601">issues.joomla.org/joomla-cms/8601</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 700a98d1d97e0bf5c8e8285feb353214dfb20ec2<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8601">issues.joomla.org/joomla-cms/8601</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8601">issues.joomla.org/joomla-cms/8601</a>.</sub>

**Pull request merged**
