### PR TITLE
[4.3] Display right error message when file type is not allowed

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR fixes wrong error message displayed when users try to upload a file which is not in list of supported file types via Media Manager.

### Testing Instructions
1. Use Joomla 4.3 
2. Access to Content -> Media, try to upload a file which is not in supported file types, for example a php file

### Actual result BEFORE applying this Pull Request
A generic error message displayed: **An error occurred**. You do not know the reason why the error happens and why the file is not uploaded

### Expected result AFTER applying this Pull Request
A clear error message displayed: **This file type is not supported** . You know the reason why the error happens.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e20197fc4285bb723243d34ff5227e7364d2f922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40155">issues.joomla.org/tracker/joomla-cms/40155</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40155">issues.joomla.org/tracker/joomla-cms/40155</a>.</sub>

**Comment by formfranska** [comment]
I have tested this item :white_check_mark: successfully on e20197fc4285bb723243d34ff5227e7364d2f922<br /><br />I have tested this successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40155">issues.joomla.org/tracker/joomla-cms/40155</a>.</sub>

**Comment by obuisard** [comment]
Thank you Tuan @joomdonation for the PR

**Pull request merged**
