### PR TITLE
Language override RTL

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

Change css to logical proprty to make sure it works as intended in RTL and LTR

### Testing Instructions
This is a css change so either run npm build:css or use a [re-built package
LTR
image

RTL
image

### Actual result BEFORE applying this Pull Request
LTR
image

RTL
image

### CODE REVIEW

**Comment by tecpromotion** [comment]
works for me.
screen shot 2022-08-01 at 07 52 44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38352">issues.joomla.org/tracker/joomla-cms/38352</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 12cf1e3c90200e17ee617fdc019b1e87c83c3251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38352">issues.joomla.org/tracker/joomla-cms/38352</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 12cf1e3c90200e17ee617fdc019b1e87c83c3251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38352">issues.joomla.org/tracker/joomla-cms/38352</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38352">issues.joomla.org/tracker/joomla-cms/38352</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
