### PR TITLE
[4.0] namespace errors

### PR DESCRIPTION
**Pull request by brianteeman**
@wilsonge oops I had a copy paste error that got through the @quy check ;)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 88a3a7bb1bb485349dd06dd216ff0c671d2bd0e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21105">issues.joomla.org/tracker/joomla-cms/21105</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 88a3a7bb1bb485349dd06dd216ff0c671d2bd0e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21105">issues.joomla.org/tracker/joomla-cms/21105</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21105">issues.joomla.org/tracker/joomla-cms/21105</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
my fault

**Pull request merged**
