### PR TITLE
[4.0] More external scripts to vendor folder

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
This PR is clearing up  com_joomlaupdate javascript:
- Update json2.js to json3.js and use the vendor folder and the grunt script to auto update it
- Update aes-js and use the vendor folder and the grunt script to auto update it

Move all inline script declarations to their relative javascript files.

### Testing Instructions

- Install 4.0
- apply this patch
- go to the options and set this: https://update.joomla.org/core/nightlies/next_major_list.xml as your custom update URL

### Expected result
Everything still works 

### Documentation Changes Required
None

### CODE REVIEW

**Comment by zero-24** [comment]
> You need to update to a new version of j4 (I have no clue...)

Just use reinstall with this: https://github.com/joomla/joomla-cms/pull/14540 or similiar Patch applyed :smile:

Also Upload and install a update package should trigger that path.

**Comment by dgt41** [comment]
@zero-24 you know how that thing works, I don't :D

**Comment by zero-24** [comment]
No Problem. I just want to help out here :smile:

**Review by C-Lodder — APPROVED** [review]

**Comment by dgt41** [comment]
@wilsonge we need this, in order to have vendor files correctly handled

**Comment by wilsonge** [comment]
This needs actual tests. I don't know how these dependencies interact with the main updater well, so I'm not comfortable merging without actual tests

**Comment by alikon** [comment]
reinstall package doesn't  work

**Pull request closed without merging**
