### PR TITLE
Delete unused imports

### PR DESCRIPTION
**Pull request by PhilETaylor**
Delete unused imports

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I give up - someone needs to do a property job of all 18 instances in /administrator/components/com_user.

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Comment by brianteeman** [comment]
My IDE is reporting a lot of unused imports in the com_users component. Most, but not all, were added in the MFA pull request. At some time @nikosdion could you take a look please. Definitely not a priority

**Comment by nikosdion** [comment]
No problem. It took longer writing the PR description than running phpStorm's auto-fix imports feature https://github.com/joomla/joomla-cms/pull/38498

**Pull request closed without merging**
