### PR TITLE
[4.0] Template: cassiopeia fix card border color to support dark mode (flag)

### PR DESCRIPTION
**Pull request by 810**
When you enable dark mode (flag setting) on the browser, all websites are showed as dark.

But on the card the color was to white and wasn't showed correctly.

### Summary of Changes

card border color

### Testing Instructions

edge://flags
chrome://flags

enable Force Dark Mode for Web Contents

### Expected result

after

### Actual result

before

### CODE REVIEW

**Comment by brianteeman** [comment]
just going from your screenshot

If the card outline needs to be changed then so does the input border as seen in the login module and many more places. 

I am not against updating to make it compatible with the dark mode flag but its better to do it all at once in a consistent manner and not piecemeal

**Comment by 810** [comment]
Many things are getting changed by the browser (the feature itself), only we need to change some conflicts. I didn't found any other issue, then the top logo banner. But i need to check more conflicts.

Like this issue on github: 
image

**Comment by 810** [comment]
i don't see any other issues, so we can merge this one.

**Comment by david0296** [comment]
I have tested this item :red_circle: unsuccessfully on 72f7f0a58ab66cfaadc1fd22ed4c564d9806ec62<br /><br />The white borders still exist.
I was using Microsoft Edge Version 84.0.522.52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27406">issues.joomla.org/tracker/joomla-cms/27406</a>.</sub>

**Comment by jmeintrup** [comment]
I have tested this item :white_check_mark: successfully on 72f7f0a58ab66cfaadc1fd22ed4c564d9806ec62<br /><br />Works as expected, but your testing instructions are incomplete.

Before testing the change you need to run `npm run build:css` or the changes won't take place (obviously).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27406">issues.joomla.org/tracker/joomla-cms/27406</a>.</sub>

**Comment by johndeutesfeld** [comment]
I have tested this item :white_check_mark: successfully on 72f7f0a58ab66cfaadc1fd22ed4c564d9806ec62<br /><br />Works as expected on the frontend but changes did not apply in the backend.

as mentioned before, you have to run `npm run build:css` before testing else it won't show any differences.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27406">issues.joomla.org/tracker/joomla-cms/27406</a>.</sub>

**Comment by roland-d** [comment]
@david0296 Did you run the `npm run build:css` ?

**Comment by david0296** [comment]
@roland-d I tried again with `npm run build:css` and it worked

**Pull request merged**
