### PR TITLE
[4.0] Remove JHELP_ strings for com_categories

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #35416

### Summary of Changes
This PR removes the JHELP_COMPONENTS_FOO_CATEGORIES, JHELP_COMPONENTS_FOO_CATEGORY_ADD and JHELP_COMPONENTS_FOO_CATEGORY_EDIT language strings and puts the reference keys into the respective category.xml as help entry.
`com_categories` already supports the category.xml file for expanding the category form. I've add additional code to support a help and listhelp node similar to com_menu and com_config.

3rd parties can also use an "url" attribute to specify the url of their help page.

### Testing Instructions
Test the help buttons in the categories sections of the various core components (content, banner, contact, newsfeed, user notes)

### Actual result BEFORE applying this Pull Request
Help buttons work

### Expected result AFTER applying this Pull Request
Help buttons work, no change in behavior.

### Documentation Changes Required
If help buttons are documented anywhere, this could be added.

### CODE REVIEW

**Comment by conconnl** [comment]
Related too https://github.com/joomla/joomla-cms/pull/35418 as well

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 0f1495613fa930f8b9a2adb6bac345add9168f96<br /><br />Upload the PR Test zip.
Checked if all files were applied.
Tested, Banners, Content, Contacts, Newsfeeds, User Notes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35534">issues.joomla.org/tracker/joomla-cms/35534</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0f1495613fa930f8b9a2adb6bac345add9168f96<br /><br />Tested on all the help buttons. All work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35534">issues.joomla.org/tracker/joomla-cms/35534</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35534">issues.joomla.org/tracker/joomla-cms/35534</a>.</sub>

**Comment by wilsonge** [comment]
Need conflicts resolved from the merge of the com_config one - sorry!

**Comment by Bakual** [comment]
Merged upstream and conflicts fixed

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
