### PR TITLE
[4.0] unused strings

### PR DESCRIPTION
**Pull request by brianteeman**
These two strings are not used

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f83784b1b792defcb9fbebab07c520660607af81<br /><br />I can confirm that these strings are not used anywhere.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34155">issues.joomla.org/tracker/joomla-cms/34155</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on f83784b1b792defcb9fbebab07c520660607af81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34155">issues.joomla.org/tracker/joomla-cms/34155</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34155">issues.joomla.org/tracker/joomla-cms/34155</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
