### PR TITLE
3.9.4 Merge

### PR DESCRIPTION
**Pull request by wilsonge**
Merges all of 3.9.4 in

Merge with a merge commit. Don't squash or rebase.

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge I am missing the changes in the joomla.sql installation file for mysql in the postgresql file. Has that been forgotten? Maybe that's the reason why postgresql system tests are currently failing?

**Comment by wilsonge** [comment]
Well the PostgreSQL tasks did pass before merging this so I doubt it. All it did was change defaults of int fields from strings to ints. As far as I can tell the changes from https://github.com/joomla/joomla-cms/pull/24058 to Postgres are already in the 4.x branch

**Comment by richard67** [comment]
@wilsonge Seems you are right, sorry for annoying.

**Comment by wilsonge** [comment]
No worries! Better safe than sorry and these are the most risky PR’s :)

**Pull request merged**
