### PR TITLE
[3.9] RFC Integrations Tab clarification

### PR DESCRIPTION
**Pull request by brianteeman**
On the integrations of all components there can be many different integrations but it is not clear "with what". The "show read more" is a good example.

This RFC Pr adds a title to each integration. If accepted I will do the same for all other components.

## Before
image

## After
image

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on fbbd63e11d38010772ffa8cfb93ce59eae458919<br /><br />+1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23711">issues.joomla.org/tracker/joomla-cms/23711</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on fbbd63e11d38010772ffa8cfb93ce59eae458919<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23711">issues.joomla.org/tracker/joomla-cms/23711</a>.</sub>

**Comment by brianteeman** [comment]
@HLeithner please let me know if I should proceed and apply this to all the views

**Comment by HLeithner** [comment]
@brianteeman make sense for me.

**Comment by brianteeman** [comment]
I was expecting to add the other views to this pr. Never mind I will do a new one for the rest

**Pull request merged**
