### PR TITLE
[4.0] Change css rule

### PR DESCRIPTION
**Pull request by brianteeman**
Since the change to use custom elements for toolbar buttons we are still left with some toolbar buttons that are not using custom elements eg the batch button

All buttons in the toolbar (custom elements and old style) have a margin-left of 0.75rem

Except for the first occurrence of the old style button which had a margin-left of 0. As that first occurrence may now no longer occur at the beginning of the row it results in two buttons without a margin between them. (see image)

~This quick pr deletes that first occurrence rule so that we have the space again (see image)~

This pr changes the class from first-of-type to first-child

Any comment about why the batch is not a custom element is beyond the scope of this pr

### before
chrome_2018-07-20_18-08-56

### after
chrome_2018-07-20_18-07-32

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a3e559a6800724ec2137fbfd12bb9f198e36ac2b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21202">issues.joomla.org/tracker/joomla-cms/21202</a>.</sub>

**Comment by Quy** [comment]
The side effect is extra left padding on the first button. 

Before:
21202-before

After:
21202-after

**Comment by ghost** [comment]
@Quy true, haven't seen that.

**Comment by brianteeman** [comment]
:(

need to find a different css rule then

**Comment by ggppdk** [comment]
Replacing `:first-of-type` with `:first-child`
should work, as we want to target the first child of the toolbar
as browser support is since IE7

can we try the above ?

**Comment by brianteeman** [comment]
Changed from removing the first of type to replacing it with first-child

**Comment by brianteeman** [comment]
Description updated

**Comment by ggppdk** [comment]
There is an extra problem that maybe is not directly related to this PR

RTL seem to load sames same CSS as LTR

we have (LTR):

```css
.subhead .btn-toolbar > :first-of-type {
    margin-right: 0;
}
.subhead .btn-toolbar > * {
    margin-right: .75rem;
    margin-left: 0;
}
```

For RTL it should be:

```css
.subhead .btn-toolbar > :first-of-type {
    margin-left: 0;
}
.subhead .btn-toolbar > * {
    margin-left: .75rem;
    margin-right: 0;
}
```

If it should not be done in this PR then please tell me
and i will mark a successful PR as i have tested already and it works

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 85e279168691ee039e9d4f6536bc6f7c554e4815<br /><br />Test without RTL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21202">issues.joomla.org/tracker/joomla-cms/21202</a>.</sub>

**Comment by infograf768** [comment]
This one has to be redone after this merge: https://github.com/joomla/joomla-cms/pull/21206 and this comment
https://github.com/joomla/joomla-cms/pull/21202#issuecomment-406772034

**Comment by infograf768** [comment]
@ggppdk 
For RTL one has also to edit the template-rtl.scss
with this
```
diff --git a/administrator/templates/atum/scss/template-rtl.scss b/administrator/templates/atum/scss/template-rtl.scss
index 3bb0cde..be2a28e 100644
--- a/administrator/templates/atum/scss/template-rtl.scss
+++ b/administrator/templates/atum/scss/template-rtl.scss
@@ -176,5 +176,5 @@
     margin-left: 0;
 
-    &:first-of-type {
+    &:first-child {
       margin-right: 0;
     }
```
and then we will get in template-rtl.css
```
.subhead .btn-toolbar > * {
  margin-right: .75rem;
  margin-left: 0; }
  .subhead .btn-toolbar > *:first-child {
    margin-right: 0; }
```
Result:
screen shot 2018-07-22 at 09 34 05

**Comment by brianteeman** [comment]
closing this as something went wrong with resolving conflicts - will redo

**Comment by brianteeman** [comment]
See #21215

**Pull request closed without merging**
