### PR TITLE
[4.0] Simplify query

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Some query simplification I missed in previous PRs.

### Testing Instructions

Code review or view articles/contacts/newsfeeds/menu items list view in backend on multilingual site.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by conseilgouz** [comment]
I have tested this item :white_check_mark: successfully on 2690db549d1610f57096037cbddc1dd09e555951<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26551">issues.joomla.org/tracker/joomla-cms/26551</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 2690db549d1610f57096037cbddc1dd09e555951<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26551">issues.joomla.org/tracker/joomla-cms/26551</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26551">issues.joomla.org/tracker/joomla-cms/26551</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
