### PR TITLE
Compact list of tagged items. New option Items to List

### PR DESCRIPTION
**Pull request by ghost**
This is a 1:1 copy of PR https://github.com/joomla/joomla-cms/pull/7031 because of a merge conflict there.

See discussion and test results there please.

Copied instructions;

See feature request https://github.com/joomla/joomla-cms/issues/6987
Menu item type _Compact list of tagged items_.
This PR adds a new option _# Items to List_ like in menu item type _Articles > Category List_.
It removes old option _Item Selection Options > Maximum Items_ because not needed anymore.

Test instructions:
- Create a tag.
- Apply it to several items (20, 30 ...) like articles, categories, contacts...  It's easy with button Batch.
- Create a menu item of type _Compact list of tagged items_ and select above tag.
- Save & Close.
- Open in frontend but do not touch limit box yet!!!
- Number of diplayed items = _Default List Limit_ in Global Configuration of Joomla.
  (If not delete cookie [= kill session], clear browser cache and reload page).
  tags-limitbox
- Apply patch.
- Reload page in frontend. Nothing changed. Do not touch limit box yet!!!
- Backend > open menu item.
- Change new option List Layouts > _# Items to List_. E.g. to 5
  tags-limitbox2
- Reload page in frontend.
  tags-limitbox3

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks RTC :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8116">issues.joomla.org/joomla-cms/8116</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody. Merged into 3.5-dev with commit db54caf

**Comment by AndySDH** [comment]
So this was marked as RTC 5 years ago but never merged... Nice. @wilsonge  @roland-d  @zero-24  @ghost

**Comment by HLeithner** [comment]
@AndySDH maybe you should read the comment by roland 

> Thanks everybody. Merged into 3.5-dev with commit [db54caf](https://github.com/joomla/joomla-cms/commit/db54cafe39823cc381df0cbe591e8893ffe44494)

**Comment by AndySDH** [comment]
It's clearly not merged because it's still not in the current version of Joomla lol

**Comment by HLeithner** [comment]
Then it got lost with 3.5-dev for what ever reason anyway can you redo the pr for 4.0?

**Comment by zero-24** [comment]
> It's clearly not merged because it's still not in the current version of Joomla lol

Well the code is in 3.9.22:
https://github.com/joomla/joomla-cms/blob/3.9.22/components/com_tags/views/tag/tmpl/list.xml#L202
https://github.com/joomla/joomla-cms/blob/3.9.22/components/com_tags/models/tag.php#L221

(I have not tested whether that feature still works but atleast the code was not removed but correctly added and is still shipped with 3.9.x)

**Comment by AndySDH** [comment]
Oh I see. So there is a lot of confusion with this I guess.

It looks like this is only available in the "Compact" layout and not in "Normal" layout.

Also, it appears this is only available in the Menu Item settings but it's not in Global Configuration at all.

Weird.

**Comment by infograf768** [comment]
Please test 4.0 here https://github.com/joomla/joomla-cms/pull/30998 and let know if something missing.

**Comment by AndySDH** [comment]
> Please test 4.0 here #30998 and let know if something missing.

Doesn't look like that PR addresses or concerns what I mentioned above?

**Comment by infograf768** [comment]
It may as nothing was changed versus 3.x in the sense that the default number of tagged items for the `Tagged Items` menu item does not include a field to define a default list limit. 
It could be added in another PR.

**Comment by AndySDH** [comment]
> It may as nothing was changed versus 3.x in the sense that the default number of tagged items for the `Tagged Items` menu item does not include a field to define a default list limit.
> It could be added in another PR.

Could definitely be good if you could make a PR for it. It should also be ported into Global Configuration, as it's missing from there.

PS: This setting ties in with the idea that Tag views should offer similar features (and appearance) to Category views in my opinion: https://github.com/joomla/joomla-cms/pull/30998#issuecomment-707710055

**Comment by infograf768** [comment]
articles category views are very different from tags as they concern the same type of items.

**Pull request closed without merging**
