### PR TITLE
Ordering by date DESC is not working

### PR DESCRIPTION
**Pull request by lunguyenhat**
Pull Request for Issue # .

### Summary of Changes

Add parentheses to Order By

### Testing Instructions
Create new Blog Menu with order by Published Up (Most Recent First ) DESC

### Expected result
Order by Published Up DESC

### Actual result
Order by Published Up ASC

### Documentation Changes Required
No

### CODE REVIEW

**Comment by Quy** [comment]
Changes in this PR will not affect the sort order. If your articles do not have published dates, then they will fall back to sorting by created dates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26171">issues.joomla.org/tracker/joomla-cms/26171</a>.</sub>

**Comment by lunguyenhat** [comment]
Hi Quy, The problem is ORDER BY on mysql > 5.6 is not working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26171">issues.joomla.org/tracker/joomla-cms/26171</a>.</sub>

**Comment by richard67** [comment]
@luredweb @Quy I can't reproduce the issue. On current staging with MySQL 5.7, I get the correct order without this PR applied. Applying this PR does not change anything for me.

**Comment by richard67** [comment]
@waader Could you test with your MySQL 8 if you have the issue which shall be solved with this PR, as this is the version which comes with the most strict default setup? On MySQL 5.7 I did not have the issue, so the PR does nothing for me.

**Comment by richard67** [comment]
@Quy Let's see if we can get some tester with MySQL 8. I don't have my new, additional testing environment ready yet. In MySQL 8, the default setup uses strict modes and so on, which on previous versions beginning with 5.7 could be set, too, but not were set with the default setup. So maybe @luredweb ran into an issue which I can't reproduce on 5.7 because I have the default setup, and he maybe uses a hosting provider's db where some settings are changed to more modern and safe ones, e.g. strict mode.

**Comment by richard67** [comment]
Regarding the SQL: Normally you include such an "CASE ... WHEN" into the columns to be selected and give it a column alias in the "SELECT", and in the "ORDER BY" you just use this column alias, but changing this in our PHP at this place would be a bigger change outside the skope of this PR, I think.

What could be a problem is that in strict mode, mysql might behave (haven't checked docs) like standard sql and only accepts columns or expressions in order by which are part of the selected columns. I.e. a "SELECT thiscolumn FROM thattable ORDER BY someothercolumn;" would result in an SQL error.

But then I would expect for this issue here an SQL error and not a wrong ordering direction, this is what confuses me a bit.

**Comment by Quy** [comment]
Can't reproduce using MySQL 5.7.23-cll-lve. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26171">issues.joomla.org/tracker/joomla-cms/26171</a>.</sub>

**Comment by lunguyenhat** [comment]
Hi. I reopened this because it's happen when you have multilingual

**Comment by ghost** [comment]
@luredweb 

> it's happen when you have multilingual

Test on English on a [Multilangual site](https://sandramay0905-3.joomla.com) (mysql 5.7.30-cll-lve). If i understand you correct it works, but maybe i need more information.

**Pull request closed without merging**
