### PR TITLE
[4.3] Inclusive Naming master display controller

### PR DESCRIPTION
**Pull request by brianteeman**
We should be using inclusive naming throughout the cms not just in the language strings.

Changes "master display controller" to "display controller",

### Rationale
https://inclusivenaming.org/word-lists/tier-1/_master/

### Test
Code review Only

### Documentation
New page will be added to manual.joomla.org shortly

### Note
This is part of a series of pull requests that are submitted separately to make reviewing easier

### CODE REVIEW

**Comment by wilsonge** [comment]
Can we just drop the word all together. We don’t use any other controllers for display actions?

**Comment by brianteeman** [comment]
If there are no others then absolutely yes

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 543a5f531e32e52a791e954cac16b39f1255d265<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41019">issues.joomla.org/tracker/joomla-cms/41019</a>.</sub>

**Comment by wilsonge** [comment]
> If there are no others then absolutely yes

I'm not aware of any. I think this comment dates back to the fact this was the controller.php files in the component root back in joomla 3 https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_content/controller.php - but there's nothing so special about them really these days.

**Comment by brianteeman** [comment]
@wilsonge updated as requested

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Pull request merged**
