### PR TITLE
com_installer Update Sites - Moved sidebar Filters

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves Filters from left sidebar to Search Tools.
# Testing instructions
## Before this PR

Extensions > Manage > **Update Sites**
1. Left sidebar has 4 filter options (Select: Location, Status, Type, Folder) that cannot be reset easily to original state with one button.

extension-updatesites-before
## After this PR

Extensions > Manage > **Update Sites**
1. The Filters have been moved from sidebar to Search Tools in middle column. All filters can be reset with the "Clear" button.

extension-updatesites-after

### CODE REVIEW

**Comment by pe7er** [comment]
## SQL error solved
I just ran into an SQL error. I triggered the error after I implemented the Search Tools with Filters, by navigating to another page and than back to Extensions > Manage > Update Sites.
extension-updatesites-error
I solved it by adding 
$this->setState('list.ordering', 'name');
to the protected function populateState($ordering = null, $direction = null) method of the Updatesites model.

**Comment by timhaeuser** [comment]
tested & works !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7707">issues.joomla.org/joomla-cms/7707</a>.</sub>

**Comment by zero-24** [comment]
@pe7er can you resolve the merge conflicts?

**Comment by pe7er** [comment]
merge conflict solved: I removed the code for JHtmlSidebar::addFilter that was no longer needed.

**Comment by pe7er** [comment]
Thanks for the codestyle changes! @zero-24

**Comment by zero-24** [comment]
RTC based on testing Thanks @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7707">issues.joomla.org/joomla-cms/7707</a>.</sub>

**Comment by bullet64** [comment]
tested & no errors found.

**Comment by zero-24** [comment]
@pe7er I'm sad to say we run again in merge conflicts.

**Comment by pe7er** [comment]
Please see new PR #8264 to replace this one.

**Pull request closed without merging**
