### PR TITLE
Reduce the getModel methods from 3 lines into one

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

``` php
-       $model = parent::getModel($name, $prefix, $config);
-
-       return $model;
+       return parent::getModel($name, $prefix, $config);
```

reduce the method from 3 lines into one
#### Testing Instructions

Code Review and / or make sure the components still works as before

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 5d2f4c72362e7959c684102530dafad16e5b29c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10924">issues.joomla.org/joomla-cms/10924</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5d2f4c72362e7959c684102530dafad16e5b29c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10924">issues.joomla.org/joomla-cms/10924</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5d2f4c72362e7959c684102530dafad16e5b29c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10924">issues.joomla.org/joomla-cms/10924</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10924">issues.joomla.org/joomla-cms/10924</a>.</sub>

**Pull request merged**
