### PR TITLE
[4.0] Switch admin language button

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR that disables the button until a language is selected

lang

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a49c7d7c66080ca432d098178a3d64448f78435e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24983">issues.joomla.org/tracker/joomla-cms/24983</a>.</sub>

**Comment by brianteeman** [comment]
Updated branch again to trigger drone

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 389fa40a287831fb7ba8619402d9a03f9e626af9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24983">issues.joomla.org/tracker/joomla-cms/24983</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24983">issues.joomla.org/tracker/joomla-cms/24983</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
