### PR TITLE
[4.0] Missing icons

### PR DESCRIPTION
**Pull request by brianteeman**
Guess these got missed in all the backwards and forwards with the icons
image

image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9b0528884697f415bbe72ffca82a41140fd19776<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33676">issues.joomla.org/tracker/joomla-cms/33676</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 9b0528884697f415bbe72ffca82a41140fd19776<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33676">issues.joomla.org/tracker/joomla-cms/33676</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33676">issues.joomla.org/tracker/joomla-cms/33676</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
