### PR TITLE
Use left/right icon for sidebar - fix #6310

### LINKED ISSUE #6310: Side bar close icon should not be an X
#### Steps to reproduce the issue
Log into the admin and visit a page that uses the side bar, such as the Article Manager

#### Expected result
The icon to collapse the left side bar should be a circle left chevron symbol like this: < to denote that it can be closed.

#### Actual result
Instead it is an X icon, which is usually used to denote "close for good".

#### System information (as much as possible)
Any version of 3.4, it's an interface change, not a bug in functionality.

#### Additional comments
I've attached a screen shot of the before/after of this. This change would likely require an update to the IcoMoon font, which I suspect is why the X is being used (the IcoMoon font does not contain a circle < icon)

Another option would be to replace the X with this IcoMoon character "\e00c" which gives a left arrow in the circle.screen shot 2015-03-04 at 13 10 26

### PR DESCRIPTION
**Pull request by cyrez**
This PR is related to this issue : https://github.com/joomla/joomla-cms/issues/6310#issuecomment-77438760

This is just a fix to have a left/right icon for sidebar working both LTR/RTL !
And icon size set to 16px, with little adjustment of margin.
(we are not reinventing the wheel here ;-) )

### CODE REVIEW

**Comment by n9iels** [comment]
@test Works fine for me, good change!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6327">issues.joomla.org/joomla-cms/6327</a>.</sub>

**Comment by JoomliC** [comment]
@n9iels Thank you for your test! ;-)

**Comment by losedk** [comment]
@test all good!

**Comment by losedk** [comment]
I only wish there were some more styling on the collapsed button

**Comment by wilsonge** [comment]
Two good tests. Merged

**Pull request merged**
