### PR TITLE
[4.0][bugfix] Fix showon for subforms/select elements

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #35968 .

### Summary of Changes

Subform select elements with complex operators might fail due to a redundant line in the js file

### Testing Instructions

Follow the issue description and use the provided subform

### CODE REVIEW

**Comment by RickR2H** [comment]
I was unable to reproduce the issue. I added the xml with the subform fields form the example in the original issue to the footer module. Added my own text field with the options (jn_val_type:18[OR]jn_val_type:11) with and without the patch the fields seems to work. Maybe it is an option to add a specific subform field to this PR with only a couple of fields to reproduce the issue?

**Comment by dgrammatiko** [comment]
@RickR2H try https://issues.joomla.org/uploads/1/0eaec512432b4cea51139d350874f7d7.txt

**Comment by cloudfaction** [comment]
i still have this issue. J 4.05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35972">issues.joomla.org/tracker/joomla-cms/35972</a>.</sub>

**Comment by dgrammatiko** [comment]
@cloudfaction if you don't test the proposed changes and verify that they work the code will never make it to any production version...

**Comment by cloudfaction** [comment]
sorry, new to this environment. i changed the showon-es5.js, removed the lines, and also did the same in the showon-es5.min.js, this did not solve my issue.

**Comment by dgrammatiko** [comment]
@cloudfaction that won't work as you're loading probably the minified modern version of the script which is `showon.min.js` or if you're testing with debug on then it's `showon.js`. So you could copy the code from this PR to these files and try again

**Comment by cloudfaction** [comment]
changed it in showon.js and showon.min.js, https://easyworkflows.nl/media/system/js/showon.min.js?faea9ca18e3e92a6243f66d83d5ff12f01b925bc

the min.js is loaded, i renamed the showon.js (changed it first) to showon.min.js

still not the desired result.

**Comment by RickR2H** [comment]
@cloudfaction did you test the PR like described in the issue? We need successful tests to add it to the core. If you need info on how to test you can contact me on Glip.

**Comment by cloudfaction** [comment]
- downloaded latest joomla from git
- installed on MAMP
- npm ci
- installed module to test - problem existed
- installed patch tester
- created git token to test
- applied patch
- npm ci
- tested module, problem still exists

**Comment by dgrammatiko** [comment]
So then this is not the solution.
The problem as reported was fixed here but I guess your module is doing something different than the reported issue and without it I can't really help.

**Comment by cloudfaction** [comment]
Modulepart repeatable subform, with [or] option fine in j3, and this part does not work in J4. If the problem was fixed, is it in 4.05 now?

**Comment by dgrammatiko** [comment]
> is it in 4.05 now?

What do you mean? If the problem still exists and this PR didn't fix it then it's not fixed.

**Comment by cloudfaction** [comment]
#35968 is closed, now this is closed, but problem still exists?

**Comment by RickR2H** [comment]
@cloudfaction The issue is closed because the patch isn't working!

Note that @dgrammatiko is really willing to help you, but he needs your info! Task for you is to set up a working XML file with the problem. Add it to this feed as text file. If he can't check out the problem he cannot fix it.

Features / patches will only be added after two successful tests. After that stage the Project lead decides if it is a good PR to merge.

@dgrammatiko are you willing to open the issue if we provide more info?

**Comment by cloudfaction** [comment]
no need. if it's in my module i will investigate and fix

**Comment by cloudfaction** [comment]
thank you all for your patience!

**Pull request closed without merging**
