### PR TITLE
[4.0] Non-clickable module in a menu item

### PR DESCRIPTION
**Pull request by brianteeman**
This is a replacement PR for #23609 which resolves the merge conflicts

### To test
npm i

Go the module assignment tab of any menu item
Click on the name of a module
A modal will open
Change the published state of the modal and save and close
Check that the module is now shown with the changed state
Check that there are no js errors in the console

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on a6b9d2ffe7f9ca39b8577f240b5e4ba5d1b78d94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27455">issues.joomla.org/tracker/joomla-cms/27455</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0aa0894c94fd0d8be9c166c8118e3ca3ce93f876<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27455">issues.joomla.org/tracker/joomla-cms/27455</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0aa0894c94fd0d8be9c166c8118e3ca3ce93f876<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27455">issues.joomla.org/tracker/joomla-cms/27455</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27455">issues.joomla.org/tracker/joomla-cms/27455</a>.</sub>

**Comment by infograf768** [comment]
Please also look at https://github.com/joomla/joomla-cms/issues/27491

**Comment by infograf768** [comment]
tks

**Comment by infograf768** [comment]
Will now make PR for https://github.com/joomla/joomla-cms/issues/27491

**Comment by infograf768** [comment]
Please test #27492

**Pull request merged**
