### PR TITLE
Change params variable to reflect merged state

### PR DESCRIPTION
**Pull request by matrikular**
Pull Request for Issue #16968.

### Summary of Changes
Change params variable to reflect merged state (in address sub-layout).

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/16968#issue-240460230

### Expected result
The mentioned field values and icons are shown to the user.

### Actual result
They are not.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8d0e5f533082f98643144a3a3c1ddb9dba90aa6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 8d0e5f533082f98643144a3a3c1ddb9dba90aa6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by richard67** [comment]
It seems drone failed for reasons not related to this PR (some phpcs script missing).

**Comment by gorgonz** [comment]
I saw the bug after updating. Gave it a try by exchanging my override with this new version. Works fine

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by AlexRed** [comment]
I think we need same edit also in the template beez override
templates/beez3/html/com_contact/contact/default_address.php

**Comment by lunalars** [comment]
hm, if all template overrides have to be updated, isn't it a b/c break then? in other words: something was changed and now breaks template overrides. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by dgt41** [comment]
> if all template overrides have to be updated, isn't it a b/c break then

Not according to the B/C promise:

> 6.1.7 Rendered markup

> For the time being, rendered markup is not subject to our backwards compatibility promise. We will try not to change markup in such a way that a site might render differently, but we can't promise not to break anything at the present time. We will work on defining ways in which we might make a backwards compatibility promise for markup in the future, but we do not currently have a satisfactory consensus on a workable standard.

**Comment by lunalars** [comment]
ah, ok. thanks for the info!

**Comment by dgt41** [comment]
@lunalars actually the mark up with this PR remains the same so this is just a bug fix and it shouldn't affect you unless you already have created an override with the latest version

**Comment by lunalars** [comment]
@dgt41 I am affected, but I'm not sure why. Maybe I'm doing somthing wrong in a plugin I created, which adds some fields to the contact edit form in backend. These fields are saved with the params of the contact.
In my template overrides I was able to get these params with 
$this->params->get('paramname'), 
but now I have to use 
$this->**item**->params->get('paramname') or $this->**contact**->params->get('paramname'). 
This only applies to the "custom" params, the "core" params work as before. 

Now I'm confused :-) But maybe I should just add my fields in a different way.

**Comment by zero-24** [comment]
I'm switching back to pending based on a special request by @matrikular <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by matrikular** [comment]
Thanks @zero-24. I'll post an update soon (this evening).

**Comment by matrikular** [comment]
First of all, I feel responsible for this and do want to make it right. You can be assured, that it is not my intention to hide behind some "yet unwritten", "debatable", "between the lines" interpretation of the stated b/c promise regarding rendered markup.

That said, personally - I would expect every site owner / admin / webmaster to thoroughly check their overrides after each update and that a layout is hardly to keep free from "breaking" changes. A simple change in the data layer or parameter handling e.g. can very well affect the output.

So much for cheap excuses,...
I also think, in case of the address layout, it would be (already is) a b/c break in a way that, everyone that already has got an override, would need to update it because of the "new" variable being used. This is because in different from the default and custom fields layout, it uses $this->params variable directly, where the other two accessed the parameters via the variable $tparams or $params, therefore no layout wide renaming was needed.

I've reverted the changes back to the original state for the address layout and assigned the merged parameters to $this->params in the view. That way, there should be no need to change an already existing override. Well, at least not in this context (hopefully).

Some more tests are highly appreciated, thanks.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 597a503ab1bc9bb6dd6dc68004f9a82faf131167<br /><br />@matrikular Just when you had posted your previous comment I have finishing my test ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 597a503ab1bc9bb6dd6dc68004f9a82faf131167<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by lunalars** [comment]
I have tested this item :white_check_mark: successfully on 597a503ab1bc9bb6dd6dc68004f9a82faf131167<br /><br />Fixes problem mentioned in #16968 and custom overrides.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on 597a503ab1bc9bb6dd6dc68004f9a82faf131167<br /><br />I tested this on four sites that had this issue and all tested great with the fix provided. Thank you!
Jenn<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16971">issues.joomla.org/tracker/joomla-cms/16971</a>.</sub>

**Pull request merged**
