### PR TITLE
[4.0] [RFC] WebAsset custom class per asset, and asset behavior

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

I want to suggest an idea.
The WebAsset can have a custom class. Actually it already possible, but was not possible while loading assets from json.

Additionally introduce `WebAssetAttachBehaviorInterface`, this can be useful when Asset need to have a Script options with a values that depend from environment. Example of old: 'behavior.core',  'behavior.keepalive'.
This also allow to leave in the past old `JHtmlBehavior`, at least in the part for loading a scripts.

Look for example 
https://github.com/Fedik/joomla-cms/blob/be02eea44e9d5cd4aebbba12d98ec8bacf50ebbd/libraries/src/WebAsset/AssetItem/CoreAssetItem.php#L36-L49
and
https://github.com/Fedik/joomla-cms/blob/be02eea44e9d5cd4aebbba12d98ec8bacf50ebbd/libraries/src/WebAsset/AssetItem/KeepaliveAssetItem.php#L24

ping @wilsonge @dgrammatiko 
@mbabker I think it will be cooler than WP_Dependencies no? :wink: 

### Testing Instructions

run `npm install` and
make sure everything works as before.

### Documentation Changes Required

as part of #22435

### CODE REVIEW

**Comment by dgrammatiko** [comment]
It's a YES from me 😉

**Comment by wilsonge** [comment]
Please can you add docs for this on the web asset docs page

**Comment by Fedik** [comment]
@wilsonge I have added a new chapter https://docs.joomla.org/J4.x:Web_Assets
please check, for my english :wink:

**Comment by wilsonge** [comment]
Tweaked english. Was really good. Thanks!

**Pull request merged**
