### PR TITLE
[hathor] com_banners client

### PR DESCRIPTION
**Pull request by brianteeman**
Before this PR the client view will not work at all with the following error
`Call to a member function get() on null
`

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Without PR i don't get an Error looking at Banners-Client-List or Edit-View.

**Comment by brianteeman** [comment]
@franz-wohlkoenig with hathor?

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on a0bfb6cafe422cec2752928460cb38d6e47db95e<br /><br />With testing date installed I get several errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15200">issues.joomla.org/tracker/joomla-cms/15200</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@brianteeman yes, Hathor.

**Comment by joomdonation** [comment]
@brianteeman The issue you are fixing was fixed in this PR https://github.com/joomla/joomla-cms/pull/15168 . Your propose fix also not a valid fix as it bypass the permission check.

So for this PR, please only keep the CS fix

**Comment by brianteeman** [comment]
and that is why it is essential to have pull requests with meaningful titles and descriptions. because you didnt you wasted my time and you wasted the time of people who are testing

**Comment by joomdonation** [comment]
Not sure if your last message is for me but #15168 was not my PR.

**Pull request closed without merging**
