### PR TITLE
[4.0] Switcher is now a Custom Element

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR migrates the Switcher field over to a dedicated custom element which has been approved by the a11y team.

### Testing Instructions

Go to the Global Configuration (or any other page that uses a switcher) and ensure it works the same as it did before.

**_Note_**, _please ignore the colours_. We still need to publish an update to NPM and properly pull the elements using the new package manager. Once done and we start working on the new template, we'll work the the necessary SCSS changes.

Hope @brianteeman likes the removal or the border radius :)

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e455b9d9d3c57d8dd1bd78fed4288102847f86e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19232">issues.joomla.org/tracker/joomla-cms/19232</a>.</sub>

**Comment by dgrammatiko** [comment]
@C-Lodder nice one! Please check either https://github.com/joomla/joomla-cms/pull/19231 or https://github.com/joomla/joomla-cms/pull/19184 for the source code folder. Basically you need to move the src to `build/webcomponents/field-switcher` and then run `grunt createElements`

**Comment by C-Lodder** [comment]
@dgt41 should we not do all of that once we have updated the alert and tabs custom elements and you've completed your "Kill grunt" PR?

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on e455b9d9d3c57d8dd1bd78fed4288102847f86e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19232">issues.joomla.org/tracker/joomla-cms/19232</a>.</sub>

**Comment by Anu1601CS** [comment]
I have tested this item :white_check_mark: successfully on e455b9d9d3c57d8dd1bd78fed4288102847f86e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19232">issues.joomla.org/tracker/joomla-cms/19232</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Why is there always a "throbber" outline on the No value?

**Comment by brianteeman** [comment]
Ignore that comment - it was a cache issue

**Comment by brianteeman** [comment]
Nope it was a brian issue and is a problem - you can probably only see it when you tab from one switcher to another

**Comment by brianteeman** [comment]
(i will post a video soon - there are a few issues)

**Comment by C-Lodder** [comment]
Brian, I purposely added the pulsating focus state, not an issue. Inspired by Google

**Comment by brianteeman** [comment]
But why is it always on the NO value

throbber-and-outline

**Comment by brianteeman** [comment]
ok - i get it now. its not on the no value but its on the switch

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e455b9d9d3c57d8dd1bd78fed4288102847f86e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19232">issues.joomla.org/tracker/joomla-cms/19232</a>.</sub>

**Comment by dgrammatiko** [comment]
@C-Lodder the src needs to move to the right path `build\...`
and the compiled ones using build.js have to move to `media\system\webcomponents\...`

**Comment by C-Lodder** [comment]
@dgt41 yeah dont worry I haven't forgotten. `compileElements` grunt task didn't work so I'm waiting on your PR

**Comment by dgrammatiko** [comment]
Hold on tight 😂

**Pull request merged**
