### PR TITLE
Fix page-break-inside (template menu assignment)

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #24344 .

### Summary of Changes
In firefox menus are been split across columns in the template menu assignment tab

### Testing Instructions
Have less than 4 menus. Navigate to template style menu assignment tab. Note if using sample data, it is probably easier to just delete the extra li nodes to display less than 4 menus (browser tools).

### Before
image

### After
image

### CODE REVIEW

**Comment by HLeithner** [comment]
You have to update the css file.

**Comment by ciar4n** [comment]
My bad. LESS has been compiled.

Im getting mixed up with 4. I guess this can be tested with patchtester.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a993dea15ffe0ea10d62ec013c50c7f7b658dedf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24345">issues.joomla.org/tracker/joomla-cms/24345</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a993dea15ffe0ea10d62ec013c50c7f7b658dedf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24345">issues.joomla.org/tracker/joomla-cms/24345</a>.</sub>

**Comment by alikon** [comment]
Status "Ready To Commit".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24345">issues.joomla.org/tracker/joomla-cms/24345</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by ciar4n** [comment]
@franz-wohlkoenig @alikon thank you for the tests

**Pull request merged**
