### PR TITLE
[Isis] Post Install Messages

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Adds some styling to the 'Post Installation Messages'.

### Testing Instructions
Apply patch and navigate to Components -> Post Installation Messages

### Before Patch
post-install1

### After Patch
post-install2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by dgt41** [comment]
@ciar4n can you also apply a well class in the right hand side (the Release news section)?

**Comment by dgt41** [comment]
should be added here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_postinstall/views/messages/tmpl/default.php#L15-L24
as
```
'class' => 'well',
```

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on e190835c5e7720a5404db4e56ac6656f4540b8fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13992">issues.joomla.org/tracker/joomla-cms/13992</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on e190835c5e7720a5404db4e56ac6656f4540b8fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13992">issues.joomla.org/tracker/joomla-cms/13992</a>.</sub>

**Comment by ciar4n** [comment]
@dgt41 Here's with a BS well applied to the right column. Personally I don't think it needs it but happy to add it if you wish...

post-install3

**Comment by franz-wohlkoenig** [comment]
@dgt41 release notes without `well` looks fine.

**Comment by C-Lodder** [comment]
hmm preferred it without to be honest. Seems very 1990's now

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on e190835c5e7720a5404db4e56ac6656f4540b8fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13992">issues.joomla.org/tracker/joomla-cms/13992</a>.</sub>

**Comment by dgt41** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13992">issues.joomla.org/tracker/joomla-cms/13992</a>.</sub>

**Comment by wilsonge** [comment]
Looks better :) Thanks!

**Pull request merged**
