### PR TITLE
Codemirror fluid height

### PR DESCRIPTION
**Pull request by ciar4n**
### Summary of Changes
On larger screens, CodeMirror height seems small (300px) compared to the space available. 

This PR...

- Gives Codemirror a fluid height, increasing the working space when available.
- Keeps a min-height of 300px
- Ensures space remains above the fold for appending buttons (article edit)

### Testing Instructions
Apply PR and open CodeMirror (template file edit, article edit)

**Before Patch**
codemirror1

**After Patch**
codemirror2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by dgt41** [comment]
@ciar4n if you can do the same for tinymce, I'll write a small snippet that will synchronise the value with the iframe...

**Comment by ciar4n** [comment]
@dgt41 Certainly worth considering. TinyMCE currently has quite a large height which in most cases extends beyond the viewport. Applying this change to it will effectively reduce its height in most cases. 

To demonstrate how this change effects the CodeMirror editor .... 

fluid2

Some might consider this an improvement with TinyMCE, others may not? Potentially this change allows the use of only one scroll bar rather than 2 when navigating to the end of a document.

**Comment by dgt41** [comment]
> Some might consider this an improvement with TinyMCE, others may not

Actually this **WAS** a todo task for J4 in JAB2015, so most probably is the right way to go...

**Comment by ggppdk** [comment]
> so most probably is the right way to go... 

Yes, calc() will work on IE9+ and all other browsers too
- IE8 will discard it, and just use the existing min-height value

calc() was used for site title of protostar too:
https://github.com/joomla/joomla-cms/pull/13064

Finally lets start to making more use of it

A note about this PR, 
- the purpose is to the editor to have a height that matches the available viewport **while being 400px smaller than it** 

**Of course if the editor is at the bottom of some page, you will need to scroll the window to reveal of the editor**
I just mention this case because it is not what the above animation shows

Continuing the above, i think it is preferable to use 
height: calc(100vh - 300px);
or
height: calc(100vh - 240px);

so that we can get **some real benefit  in x768 and in x800 laptop screens**
since:  height: calc(100vh - 300px);
in those screens will give almost zero benefit because:
708 - 400 = 308 (on x768 screen)
740 - 400 = 340 (on x800 screen)

The user may need to scroll to put the editor inside viewport, if we use:
height: calc(100vh - 240px);
but anyway, if you place the editor at the bottom of page, you already need to scroll

**Comment by ciar4n** [comment]
@ggppdk The reasoning behind using 400 is that that is the approx height (plus a few px) from the top of the viewport to where the editor starts (inc. 'saved' alert).

To avoid double scroll bars on bigger screens and still allow a benefit to smaller screens I would suggest increasing the min-height rather than decreasing the calc value.

**Comment by ggppdk** [comment]
> The reasoning behind using 400 is that that is the approx height (plus a few px) from the top of the viewport to where the editor starts (inc. 'saved' alert).

hhmm, the saved alert can be dismissed,
so still thinking that height: calc(100vh - 330px); is good trade-off

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 67c0efcee484abbbd8437ebb65f24cdb53be4c34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13266">issues.joomla.org/tracker/joomla-cms/13266</a>.</sub>

**Comment by ciar4n** [comment]
@ggppdk I can set to 330px however it would mean the buttons would appear below the fold. Personally I would sooner these buttons to be visible if the screen height allows it..

codemirror3

**Comment by ggppdk** [comment]
Ok, this is only a common screen, the backend article edit screen,

But if the editor **is shown at the middle or bottom of the page**,
-- not only the buttons, but the editor itself **will not be visible without doing some scrolling**

That is even if using the minimum 300px,
-- the user will still need to scroll in order to put it (=the editor) inside the view port

But as i said i understand that you want to catch the common case of most backend screens,
that the editor is near the top and indeed -400px makes it show in full

**Comment by ciar4n** [comment]
@ggppdk Min-height has been increased to 400px. I feel we are over complicating a relatively simple PR. As this PR only effects Isis, the editor will never appear closer to the top of the screen, nor will this PR effect the frontend. The value has been set to accommodate the majority of instances of the editor within the viewport. If the editor is further down the page then there is an argument for reducing the height further rather than increasing it. Considering this I set a max-height (800px). 

@dgt41 I will leave TinyMCE for another PR as I am not sure how the JS will effect the option to resize.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 7f19f961e1858fac13bfbde0c84ebcabd70989e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13266">issues.joomla.org/tracker/joomla-cms/13266</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7f19f961e1858fac13bfbde0c84ebcabd70989e5<br /><br />Great :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13266">issues.joomla.org/tracker/joomla-cms/13266</a>.</sub>

**Comment by zero-24** [comment]
Great. RTC now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13266">issues.joomla.org/tracker/joomla-cms/13266</a>.</sub>

**Pull request merged**
