### PR TITLE
[4.0] Backend articles model parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds parameterized queries to `Joomla\Component\Content\Administrator\Model\ArticlesModel`.

### Testing Instructions

Go to articles list in backend.
Search and filter articles, use different ordering.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
Home Dashboard > Recently Added Articles

> Notice: Undefined property: stdClass::$author_name in \administrator\modules\mod_latest\tmpl\default.php on line 43

**Comment by SharkyKZ** [comment]
@Quy Fixed.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 46dfe7b0b694e4467eaccb05bbfab1bd863bea35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27689">issues.joomla.org/tracker/joomla-cms/27689</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 46dfe7b0b694e4467eaccb05bbfab1bd863bea35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27689">issues.joomla.org/tracker/joomla-cms/27689</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27689">issues.joomla.org/tracker/joomla-cms/27689</a>.</sub>

**Pull request merged**
