### PR TITLE
Joomla 4.0: Removing modern SEF option

### PR DESCRIPTION
**Pull request by Hackwar**
This removes the option for modern routing from the components configuration.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@Hackwar i think you also need to remove `showon="sef_advanced:1"` in sef ids field

**Comment by Hackwar** [comment]
Yes, you are right. Done.

**Comment by andrepereiradasilva** [comment]
@Hackwar since 4.0 is a B/C break version shouldn't the default be 1 ?
Not sure what's the level of B/C allowed here ...

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on de045c1f0aee3b8cb4bcf2331701f9704ba41178<br /><br />anyway this is not what this PR does, so tested with success on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13021">issues.joomla.org/tracker/joomla-cms/13021</a>.</sub>

**Comment by Hackwar** [comment]
I don't want to remove the IDs by default. We are just using the modern routing in all cases, but otherwise that is just another option that people can select. So keeping that 0 is correct for me. 😄

**Comment by andrepereiradasilva** [comment]
ups just noticed you also have sef_advanced in com_users
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/config.xml#L244

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on de045c1f0aee3b8cb4bcf2331701f9704ba41178<br /><br />as comments above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13021">issues.joomla.org/tracker/joomla-cms/13021</a>.</sub>

**Comment by Hackwar** [comment]
Removed the option in com_users, too.

**Pull request merged**
