### PR TITLE
[4.0] Fix com_menu searchtools being auto expanded

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #16346

### Summary of Changes

This PR ensures that the searchtools in com_menu do not auto expand. Same as other components.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de5b91ccc6a74a5577195526c388f198f1379c18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16356">issues.joomla.org/tracker/joomla-cms/16356</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on de5b91ccc6a74a5577195526c388f198f1379c18<br /><br />Sorry this isnt quite correct

If you set a search filter on any other view then the search filter stays open
If you set a search filter on the menu view with this PR then the search filter always closes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16356">issues.joomla.org/tracker/joomla-cms/16356</a>.</sub>

**Comment by C-Lodder** [comment]
Hmm bit confused myself on this. Will revisit another time

**Comment by wilsonge** [comment]
OK In that case I'm closing this PR and re-opening the original issue

**Pull request closed without merging**
