### PR TITLE
standardise contact strings

### PR DESCRIPTION
**Pull request by brianteeman**
as spotted by @MartijnMaandag

Pull Request for Issue #20576 .

In Contacts we do have a field "State or Province" it is called "State or County" in the Contact Options (tab Contact and tab List Layouts), category-options and the menus.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 30fb7f634e6c6ee4cfbeea90ff8341f31572a3b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20577">issues.joomla.org/tracker/joomla-cms/20577</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 30fb7f634e6c6ee4cfbeea90ff8341f31572a3b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20577">issues.joomla.org/tracker/joomla-cms/20577</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20577">issues.joomla.org/tracker/joomla-cms/20577</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
