### PR TITLE
[com_tags][com_contact] Remove search by author

### PR DESCRIPTION
**Pull request by brianteeman**
#10180 and #10176 introduced the correct tooltip for searching in contacts and tags.

This revealed that you can search for a tag or contact by author name which isnt really appropriate as they have a creator and not an author - plus we never display the name of the creator anywhere so we dont need this and it can be removed.

This PR removes the ability to search contacts and tags by author name using the prefix Author

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 18b323dddc3778957044a4b874115a024f420c42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10189">issues.joomla.org/joomla-cms/10189</a>.</sub>

**Comment by infograf768** [comment]
I have a suggestion for com_contacts: search by Linked User (that would be useful) instead of author:

It would give
screen shot 2016-05-03 at 11 46 37

With this code change (+ the string evidently)
```
diff --git a/administrator/components/com_contact/models/contacts.php b/administrator/components/com_contact/models/contacts.php
index d1a2e8e..2111508 100644
--- a/administrator/components/com_contact/models/contacts.php
+++ b/administrator/components/com_contact/models/contacts.php
@@ -301,9 +301,9 @@
 				$query->where('a.id = ' . (int) substr($search, 3));
 			}
-			elseif (stripos($search, 'author:') === 0)
+			elseif (stripos($search, 'linked:') === 0)
 			{
 				$search = $db->quote('%' . $db->escape(substr($search, 7), true) . '%');
 				$query->where(
-					'(' . $db->quoteName('uc.name') . ' LIKE ' . $search . ' OR ' . $db->quoteName('uc.username') . ' LIKE ' . $search . ')'
+					'(' . $db->quoteName('ul.name') . ' LIKE ' . $search . ')'
 				);
 			}
```

**Comment by andrepereiradasilva** [comment]
@infograf768 please open an issue with that suiggestion :wink:

**Comment by infograf768** [comment]
well, is'nt it simpler to modify here? I mean if @brianteeman agrees

**Comment by brianteeman** [comment]
I agree it would be useful for contacts
but as this pr is to remove author for tags and contacts I agree with andre
- please make a new pr for that

On 3 May 2016 at 10:53, infograf768 <notifications@github.com> wrote:

> well, is'nt it simpler to modify here? I mean if @brianteeman
> <https://github.com/brianteeman> agrees
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10189#issuecomment-216483520>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
this would mean double job for TTs using crowdin:
first translate
+COM_CONTACT_FILTER_SEARCH_DESC="Search in contact name and alias. Prefix with ID: to search for a contact ID."

and then
change it again.

Not nice to them...

**Comment by brianteeman** [comment]
No it wont really as it is unlikely they will even see the first edit if
you do the PR now

On 3 May 2016 at 10:58, infograf768 <notifications@github.com> wrote:

> this would mean double job for TTs using crowdin:
> first translate
> +COM_CONTACT_FILTER_SEARCH_DESC="Search in contact name and alias. Prefix
> with ID: to search for a contact ID."
>
> and then
> change it again.
>
> Not nice to them...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10189#issuecomment-216484553>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I can't do a PR if yours is not merged, and if mine was merged before, you would have to redo your PR...

**Comment by brianteeman** [comment]
If you test this one then it will be RTC and based on current merge time it will be merged within a few hours maximum

**Comment by infograf768** [comment]
and then we come back to my first comment: some TT will have to change their translation if mine is not merged just after yours, which I can't prepare until yours is merged
Just forget it.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 18b323dddc3778957044a4b874115a024f420c42<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10189">issues.joomla.org/joomla-cms/10189</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10189">issues.joomla.org/joomla-cms/10189</a>.</sub>

**Pull request merged**
