### PR TITLE
[5][com_contact] no user linked

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #43242

### Summary of Changes

don't process further if no user

### Testing Instructions

Create a contact and select a 'Linked User', then delete that user.

### Actual result BEFORE applying this Pull Request

error

### Expected result AFTER applying this Pull Request

no more errore

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
PR test successfully but ```Warning: Undefined property: stdClass::$value in /mnt/data/vhosts/casite-1466051.cloudaccess.net/httpdocs/components/com_contact/tmpl/contact/default_user_custom_fields.php on line 27```.

**Comment by chmst** [comment]
I have tested this item successfully. But it should go into 4.4, as it is already in 4.4. 

With the PR the user gets this when he opens the contact form and fills the form 
grafik

There should be something more informative for a user.

**Comment by exlemor** [comment]
on Joomla 5.1 rc2, PHP 8.2.17

I just tried 3 times to create a new user, then create a new contact and link that contact to the new user and then I deleted the user in question and never received an error so therefore I was not able to test this PR for no error message [I have debug and error reporting to maximum].

**Comment by ellenrothwax** [comment]
I created a new user, then a new contact and linked that contact to the new user and then I deleted the user in question and never received an error.

**Comment by SumCompanyInc** [comment]
using v5.1 RC1 - i also followed the instructions, "Create a contact and select a 'Linked User', then delete that user." But did not run into any issues deleting the user. going back to the contact, the ID is still listed as the linked user

**Comment by akshehu** [comment]
I have tested this item :white_check_mark: successfully on 9979a19bf046b00047b2636e1299a32a233e2901<br /><br />There seem to be no errors present. All good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43254">issues.joomla.org/tracker/joomla-cms/43254</a>.</sub>

**Comment by alikon** [comment]
@fgsw did you have some custom fields on com_contact ?
@chmst  what should looks like  as a more informative msg ? and didn't check yet on 4...

strange that others in 5 could not reproduce it

**Comment by bobbla** [comment]
I have tested this item :white_check_mark: successfully on 9979a19bf046b00047b2636e1299a32a233e2901<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43254">issues.joomla.org/tracker/joomla-cms/43254</a>.</sub>

**Comment by fgsw** [comment]
> @fgsw did you have some custom fields on com_contact ?

Yes.

> strange that others in 5 could not reproduce it

I also could not reproduce an error in first tries until i looked at frontend.

**Comment by exlemor** [comment]
Hi @fgsw, I looked at the front end each of the 3 times, I tested this and found no errors [with error reporting to maximum and debug mode on] ;(

**Comment by fgsw** [comment]
@exlemor I have only error-reporting set on maximum, but i don't know if this is a real difference. I'm a user, not a developer.

**Comment by brianteeman** [comment]
> Perhaps the contact form should not be generated if the user is not found

That would be the most sensible behaviour. Just the same as when there is no email address in the contact information

**Comment by fgsw** [comment]
> not strange at all - your testing instructions were extremely vague!!

@brianteeman You're right. In my opinion this happens cause developers think different than a non-developer-tester. 

To be honest i had given up to test this pr until i thought "maybe 'frontend' is missing in the instructions".

**Comment by alikon** [comment]
i apologize

**Pull request closed without merging**
