### PR TITLE
[4.0] [com_content] Fix filtering by author alias

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes some leftover code from before parameterized queries, fixing filtering by author alias.
Also parameterizes one query.

### Testing Instructions

Create an article. Enter something into `Created by Alias` field.
Create `Aritcles - Category` module.
Select some aliases in `Author Aliases` field (`Filtering Options` tab).
View the module in frontend.

### Expected result

Works.

### Actual result

>Argument 1 passed to Joomla\Database\DatabaseQuery::bindArray() must be of the type array, string given, 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by adj9** [comment]
I have not tested this item.<br /><br />Inserting the alias of an article I have no subtraction of the remaining belonging to the category.

Do I understand the objective of PR well?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29160">issues.joomla.org/tracker/joomla-cms/29160</a>.</sub>

**Comment by SharkyKZ** [comment]
I don't think so. There's `Created by Alias` field in `Publishing` field of article form. You need to create some articles and enter some values in this field:

Screenshot_2020-05-21 Articles Edit - Joomla - Administration

Then publish `Articles - Category` module and select some values in `Author Aliases` field:

Untitled

**Comment by adj9** [comment]
Okay, it's true.
Now I understand the question.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29160">issues.joomla.org/tracker/joomla-cms/29160</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc854f6e1c1cf4368f6cd6d139eab7fbdcae9da6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29160">issues.joomla.org/tracker/joomla-cms/29160</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dc854f6e1c1cf4368f6cd6d139eab7fbdcae9da6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29160">issues.joomla.org/tracker/joomla-cms/29160</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29160">issues.joomla.org/tracker/joomla-cms/29160</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks. 👍

**Pull request merged**
