### PR TITLE
[4.0] Typo/Spelling BASIS

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes obvious typing/spelling error BASIS should be BASIC

code review

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 06f7dc41d5a4eaf40d8215b510dc0ded1d18b8e6<br /><br />Noted that the ..._DESC are not used,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 06f7dc41d5a4eaf40d8215b510dc0ded1d18b8e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by infograf768** [comment]
> Noted that the ..._DESC are not used,

Indeed and, in this case, they are redundant with the label and therefore justifies their deletion.
Back to pending. Please delete them.

**Comment by infograf768** [comment]
Pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by HLeithner** [comment]
Guys these stings exists 11 years or more breaking all translations without any benefit doesn't makes sense to me.

**Comment by jiweigert** [comment]
If those strings existing 11 years and every attempt to change them was blocked because "breaking", it is time to make the step to finally correct the typo and havn't this discussion again in future.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by vaibhavsTekdi** [comment]
I have tested this item :white_check_mark: successfully on aa694ad0b47e45ae70d064163633bac973023f47<br /><br />It's working fine after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by Tejashrimajage** [comment]
I have tested this item :white_check_mark: successfully on aa694ad0b47e45ae70d064163633bac973023f47<br /><br />It's working fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31361">issues.joomla.org/tracker/joomla-cms/31361</a>.</sub>

**Comment by richard67** [comment]
@chmst Did you see @HLeithner 's comment above? https://github.com/joomla/joomla-cms/pull/31361#issuecomment-723923448

@HLeithner What shall we do with this?

**Comment by chmst** [comment]
I think doing it now for J4 is better than repeating this again and again.

**Comment by chmst** [comment]
But of course @HLeithner decides.

**Comment by HLeithner** [comment]
I let @Bakual decide this

**Comment by Bakual** [comment]
Personally I'd even move them to a com_users file as it's only used there and likely isn't used by 3rd parties.

I'm fine with that PR.

**Comment by brianteeman** [comment]
@bakual - I did wonder about that but assumed there was a technical reason for it not being in com_users in the first place. Happy to move it if you are sure thats ok.

**Comment by Bakual** [comment]
@brianteeman I don't see a reason why it should be in the joomla.ini file. It's a classic com_users menu parameter.

**Comment by richard67** [comment]
Maybe use "blame" to see if it once had been moved to there for some reason?

**Comment by chmst** [comment]
The strings are from 11 years ago .. this is befor my Joomla time and maybe there was only one language file?

**Comment by brianteeman** [comment]
There are other GLOBAL strings in that xml. If these BASIS are to be changed then they all should be changed. Personally this is all beyond the scope. The PR was just to fix a simple typo

**Comment by Bakual** [comment]
Already did the blame thing. The strings were added back then by @infograf768 because the string apparently wasn't translated. One would have to see in the JC Archive if there was a specific reason for it.

> There are other GLOBAL strings in that xml. If these BASIS are to be changed then they all should be changed. Personally this is all beyond the scope. The PR was just to fix a simple typo

The PR is fine for me as it is.

**Comment by brianteeman** [comment]
So please merge and we can all move on to more productive things ;)

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
