### PR TITLE
[4.1] Bootstrap 5.1.3 update

### PR DESCRIPTION
**Pull request by brianteeman**
This has only one change, which was presumably important enough to justify an update

https://github.com/twbs/bootstrap/releases/tag/v5.1.3

### CODE REVIEW

**Comment by brianteeman** [comment]
It would be a real shame if 4.1 shipped with an out of date version!

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d0882e158abc37c600e222e6f1743b045062abd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36691">issues.joomla.org/tracker/joomla-cms/36691</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d0882e158abc37c600e222e6f1743b045062abd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36691">issues.joomla.org/tracker/joomla-cms/36691</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36691">issues.joomla.org/tracker/joomla-cms/36691</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
