### PR TITLE
Fix the calendars buttons

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/15573  .

### Summary of Changes
Buttons are messed up if today button is not enabled

### Testing Instructions
Insert the following code to /administrator/templates/isis/index.php after line 288:
```html
		<?php echo JHtml::_('calendar', '', 'Some name', 'someid', '%Y-%m-%d', array('todayBtn' => false)); ?>
```
And then visit any page in the admin area (and check the calendar at the top)
Apply patch and refresh that page

### Expected result

Expected a nice calendar:
screen shot 2017-04-27 at 11 55 16

### Actual result

Calendar should render correctly but its not:
screen shot 2017-04-27 at 11 54 39

### Documentation Changes Required

### CODE REVIEW

**Comment by OctavianC** [comment]
Tested & working.

zz

**Comment by franz-wohlkoenig** [comment]
@OctavianC i altered your Test as successfully on issue Tracker.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e994d8b1d39cd853e3f159a4c9d10d65dfe9560f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15611">issues.joomla.org/tracker/joomla-cms/15611</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
