### PR TITLE
[4.0] Modal trapped

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #19408

I know that the modal code is going to be replaced eventually but this "trap" is preventing people from working with patchtester easily and from testing other part of joomla 4

(I am only committing the scss as I assume we no longer commit the compiled assets if that's correct then we need documentation)

### CODE REVIEW

**Comment by ghost** [comment]
~~I have tested this item :red_circle: unsuccessfully on f66c516badcb6338ad97fe829be5fff8b8708871<br /><br />Applied Patch but Modal still trapped. Test on "Article > Version" and "Article > Preview".~~<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21343">issues.joomla.org/tracker/joomla-cms/21343</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig you cannot just use patchtester for this as it is an scss file and i have not committed the css as I wrote in the pr. You will need to run the buildcss script

**Comment by ghost** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21343">issues.joomla.org/tracker/joomla-cms/21343</a>.</sub>

**Comment by wojsmol** [comment]
@franz-wohlkoenig Please see [docs](https://docs.joomla.org/Special:MyLanguage/J4.x:Setting_Up_Your_Local_Environment)

**Comment by ghost** [comment]
@wojsmol thanks for Link. To be honest: Patchtester is my Limit.

**Comment by C-Lodder** [comment]
> I am only committing the scss as I assume we no longer commit the compiled assets

Rather hard on the testers isn't it?

**Comment by brianteeman** [comment]
As far as I am aware that is the way forward - not that I agree.

**Comment by dgrammatiko** [comment]
@C-Lodder till someone fixes https://github.com/joomla-projects/joomla-testing 

PS wrong repo, I meant this: https://github.com/joomla-projects/gsoc17_pr_testing_platform

**Comment by wojsmol** [comment]
@franz-wohlkoenig do you use brew on your Mac?

**Comment by ghost** [comment]
@wojsmol i don't use brew (and i didn't know what it is until i searched after your Question :-).

**Comment by ciar4n** [comment]
Open notifications dropdown

image

**Comment by ciar4n** [comment]
To fix you can remove the z-index from the subhead but I suspect that will just pass the problem else where

**Comment by brianteeman** [comment]
grrrh - well I give up. Increasing the z-index on the modal-backdrop didnt work either

**Comment by dgrammatiko** [comment]
@ciar4n patchtester is more important than the dropdown

**Comment by ciar4n** [comment]
> @ciar4n patchtester is more important than the dropdown

True. I'm just pointing out that these z-indexs are a house of cards once we start removing them. The modals will rely on them unless we move modal markup outside of the toolbar.

**Comment by ciar4n** [comment]
In other words... by loading the modal markup with the modal trigger (in this case a button in the toolbar), the modal will inherit the z-index of the triggers container (in this case the toolbar). It is for this reason that modal markup is usually moved to the root.

**Comment by C-Lodder** [comment]
If I rightly remember, we had this discussion regarding modals when starting custom elements and ensured they were injected just before the closing body tag

**Comment by ciar4n** [comment]
Injecting the modal to just before the closing body tag would solve this issue.

**Comment by brianteeman** [comment]
I just want a fix so that testers can use the patch tester. Dimitris has said he is rewriting the modal stuff so the fix will only be temporary until then.

**Comment by dgrammatiko** [comment]
The fix is fine for now, at least for me.

PS just comment out the line instead of deleting it and add a // @todo restore when new modals merged

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on f66c516badcb6338ad97fe829be5fff8b8708871<br /><br />As a temporary fix this is fine by me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21343">issues.joomla.org/tracker/joomla-cms/21343</a>.</sub>

**Comment by ciar4n** [comment]
As the CSS is not been included with the PR, does this mean all style related PRs can not be tested with the patchtester?

**Comment by laoneo** [comment]
When you don't have node/npm installed, then not as it needs a recompile 8f the assets. Perhaps parchtester should detect that in the future that a sass or js file has changed and a recompile is needed.

**Comment by mbabker** [comment]
Patch tester is borderline unsuitable for the 4.0 environment with all the changes that have been made.  If you are not using a git client and command line, there are really only two viable options:

1) The PR testing platform, if it is ever put online
2) Building installable packages for every PR (similar to what's done for #20800 but more generic) that can be put through Upload & Install in the update component, there's just no reliable rollback mechanism here (well, in theory you can rollback by re-installing either the tagged release package or nightly build you started from, but if there are database changes, you're out of luck)

**Comment by wojsmol** [comment]
@mbabker +1 for number 2 until number 1 is ready at let for PR's with js or scss changes.

**Pull request merged**
