### PR TITLE
[5.0] colour contrast in media manager file list [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #42541 

### Summary of Changes
Fix a11y contrast issue in media manager

### Testing Instructions
Select an element in media, list view. The selected element has should have color white

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Please fix https://ci.joomla.org/joomla/joomla-cms/72369/1/16

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 276521bec70953180634d1589743548f6e55a9f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42544">issues.joomla.org/tracker/joomla-cms/42544</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42544">issues.joomla.org/tracker/joomla-cms/42544</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
