### PR TITLE
TinyMCE options - showon

### PR DESCRIPTION
**Pull request by brianteeman**
Cosmetic change to the plugin options so that Horizontal Resizing is only displayed when resizing is set and Language Code is only displayed if Automatic Language Selection is off

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
"HTML Height" and "HTML Width" could also have showon since they only apply tin advanced or extended mode. Check those fields tooltip.

**Comment by brianteeman** [comment]
I deliberately didnt do anything about any of the fields that are dependent
on the editor mode. Been there - had the argument dont want to go there
again

On 2 May 2016 at 13:32, andrepereiradasilva <notifications@github.com>
wrote:

> "HTML Height" and "HTML Width" could also have showon since they only
> apply tin advanced or extended mode. Check those fields tooltip.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10198#issuecomment-216223574>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
ok then

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 04bdff52acff684c11ec50ecf37d3eca4a5add3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10198">issues.joomla.org/joomla-cms/10198</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 04bdff52acff684c11ec50ecf37d3eca4a5add3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10198">issues.joomla.org/joomla-cms/10198</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10198">issues.joomla.org/joomla-cms/10198</a>.</sub>

**Pull request merged**
