### PR TITLE
[4.0] Fixed module position names on medium-width screens

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull Request for Issue #23451  

### Summary of Changes
Changes in file ```administrator/language/en-GB/en-GB.ini``` and ```media/vendor/choicesjs/css/choices.min.css```

### Testing Instructions
Open existing or create new module.
Resize (desktop) screen to about half width but so that position list is still to the right of the editor, not below.
Click the Position drop-down menu to view list of module positions

### Expected result (Now)
screenshot from 2019-01-29 00-28-44

### Actual result (Earlier)
screenshot from 2019-01-29 00-40-07

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
This is not a correct fix

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e019d60a30a7d29254255d22f0b66a1fa21781d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23706">issues.joomla.org/tracker/joomla-cms/23706</a>.</sub>

**Comment by hardik-codes** [comment]
@brianteeman Please suggest me the changes.

**Comment by brianteeman** [comment]
Removing necessary text is not a solution. You need to find a solution that doesnt remove the text. The change should probably require a media query so you are only applying it at the screen sizes that are impacted and not on all screen sizes

**Comment by hardik-codes** [comment]
@brianteeman please review the changes.

**Comment by brianteeman** [comment]
@hardik-codes Not sure where to start. You are trying to commit a file that doesnt exist in the repository. Thats because it is a VENDOR file which is not committed to the repo but generated by our build tools. And its pretty much a golden rule that you never edit a vendor file

**Comment by hardik-codes** [comment]
@brianteeman sorry I didn't know about that. Then what could possibly be the other way round  to implement those changes ?

**Comment by brianteeman** [comment]
If I read your css change correctly it is doing what I said shouldnt be done

> Removing necessary text is not a solution. You need to find a solution that doesnt remove the text.

**Comment by hardik-codes** [comment]
@brianteeman I haven't removed the necessary text in the latest commits. All I have done is added media queries to achieve the desired effect

**Comment by brianteeman** [comment]
Maybe I misread your code but doesnt this code remove the text "Press to select" ?

```
@media (min-width: 768px) and (max-width: 1024px)  {
  .choices__list--dropdown .choices__item--selectable:after {
    content: none;
  }
}
```

**Comment by hardik-codes** [comment]
@brianteeman Yeah it does so. What I thought (as per your above guideline) was that "Press to select" was to be removed for only some screen sizes and not all as for only some screen sizes the result was like this
pressselect

**Comment by hardik-codes** [comment]
@brianteeman please suggest me the changes to improve this PR

**Comment by Quy** [comment]
Closing since this is not a proper fix as vendor files should not be modified.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23706">issues.joomla.org/tracker/joomla-cms/23706</a>.</sub>

**Pull request closed without merging**
