### PR TITLE
[4.1] Tasks manager column heading

### PR DESCRIPTION
**Pull request by brianteeman**
Follow the style guideline by captitalising both words

### before
image

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 85008dc4e8c23dd00e199a60ecea833b2c087484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36208">issues.joomla.org/tracker/joomla-cms/36208</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 85008dc4e8c23dd00e199a60ecea833b2c087484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36208">issues.joomla.org/tracker/joomla-cms/36208</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36208">issues.joomla.org/tracker/joomla-cms/36208</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
