### PR TITLE
[4.2] [Smart Search] Moved statistics in the toolbar

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
The statistics button is right in the middle between the actions, which I found a little illogical. I suggest moving it to the very end of the toolbar.

Screenshot_1

### Testing Instructions
Pay attention to the screenshot, after applying the PR, check pages **Smart Search: Indexed Content**, **Smart Search: Content Maps**, **Smart Search: Search Filters**.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on af8b36fa60b9a2371dd8feb8286fa35198bbc1ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38371">issues.joomla.org/tracker/joomla-cms/38371</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on af8b36fa60b9a2371dd8feb8286fa35198bbc1ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38371">issues.joomla.org/tracker/joomla-cms/38371</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38371">issues.joomla.org/tracker/joomla-cms/38371</a>.</sub>

**Comment by fancyFranci** [comment]
Thats really better, thank you!

**Pull request merged**
