### PR TITLE
[3.7.x] Some small CS changes after #12396

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #12396 
### Summary of Changes

Just simple CS that require a opening and closeing php tag in layout files
### Testing Instructions

review. or test the same as #12396 
### Documentation Changes Required

None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12431">issues.joomla.org/tracker/joomla-cms/12431</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item ✅ successfully on 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12431">issues.joomla.org/tracker/joomla-cms/12431</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12431">issues.joomla.org/tracker/joomla-cms/12431</a>.</sub>

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12431">issues.joomla.org/tracker/joomla-cms/12431</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c395bfca6c172d35cddf893b173b45a3462f0fa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12431">issues.joomla.org/tracker/joomla-cms/12431</a>.</sub>

**Pull request merged**
