### PR TITLE
[3.7.x] Fixes the missing string in com_users Options

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This just adds the missing string like the other stings
### Testing Instructions

Go to backend -> System -> Global Configuration -> Users ->Integration
### Documentation Changes Required

None

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on dc9260d9ab0dd9c75a15dfadf46d46e4d90bccec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12246">issues.joomla.org/joomla-cms/12246</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dc9260d9ab0dd9c75a15dfadf46d46e4d90bccec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12246">issues.joomla.org/joomla-cms/12246</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman please take a look to the language string.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12246">issues.joomla.org/joomla-cms/12246</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dc9260d9ab0dd9c75a15dfadf46d46e4d90bccec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12246">issues.joomla.org/joomla-cms/12246</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12246">issues.joomla.org/joomla-cms/12246</a>.</sub>

**Pull request merged**
