### PR TITLE
[4.0] FieldsHelper: Choose a first available category  correctly

### PR DESCRIPTION
**Pull request by Fedik**
Try to fix release blocker #23036 .

### Summary of Changes

This is correcting a way to retrieve a first category in list

### Testing Instructions

Apply patch, and create a field assigned to specific category.
Then create a new Article to this category and make sure the field is there.

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Documentation Changes Required

nope

ping @wilsonge

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on a5eef98a9fe97f5cf261ec71aece8aee97ea8941<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30268">issues.joomla.org/tracker/joomla-cms/30268</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on a5eef98a9fe97f5cf261ec71aece8aee97ea8941<br /><br />If it works before and works after applying the patch it is not clear what to look for as a test result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30268">issues.joomla.org/tracker/joomla-cms/30268</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30268">issues.joomla.org/tracker/joomla-cms/30268</a>.</sub>

**Comment by wilsonge** [comment]
Do we need this same code in the other places we have this (WorkflowBehaviorTrait and ArticleModel)?

**Comment by Fedik** [comment]
Good question, I did not seen it there,
if it use
```php
$xml->loadHTML($formField->__get('input'));
$options = $xml->getElementsByTagName('option');
```

Then yes, it also need to be changed.

Do not merge it for now, I will check that also

**Comment by Fedik** [comment]
I have updated WorkflowBehaviorTrait and ArticleModel. Please re-check

I just have no idea where to test WorkflowBehaviorTrait.

**Comment by Fedik** [comment]
@Quy  please restore an yellow label :wink:

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 861f892125cc0a3dab628adef1a5ca5e2367a928<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30268">issues.joomla.org/tracker/joomla-cms/30268</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
(Merged as there was two good changes in the main patch and one good test on rolling the same thing out to two other places)

**Pull request merged**
