### PR TITLE
Removed a few nested conditionals in the JFormField base class

### PR DESCRIPTION
**Pull request by Mathewlenning**
I think I have the code style setting working now. We're about to find out. After talking to @mbabker on twitter, I decided to do a little more cleaning. This time I removed nested conditionals from getFieldName and getAttributes

### CODE REVIEW

**Comment by Mathewlenning** [comment]
I hate it when a PR goes out of sync. Anyone that can see the conflicts care to show me what they are? All I can see is a "Only those with write access to this repository can merge pull requests" message. No other hints as to what is out of sync.

**Comment by wojsmol** [comment]
@Mathewlenning Compare this part https://github.com/Mathewlenning/joomla-cms/blob/Form-Field-Cleaning/libraries/joomla/form/field.php#L908-L915 with a file from staging

**Comment by wojsmol** [comment]
@Mathewlenning Please see https://github.com/Mathewlenning/joomla-cms/pull/5

**Comment by Mathewlenning** [comment]
I appreciate it @wojsmol is there any documentation on how to hunt down a merge conflict? I'd really appreciate any guidance =^D

**Comment by mbabker** [comment]
Truthfully, using the web UI there isn't.  When merge conflicts happen it's best to merge the upstream branch into your local branch and git will tell you what lines in what files are conflicted.

**Comment by Mathewlenning** [comment]
Thanks @mbabker I'll take a look and see if I can figure it out.

**Comment by Mathewlenning** [comment]
@mbabker I think I figured it out. But I can't seem to restart Travis.

**Comment by dgt41** [comment]
@Mathewlenning I think you need to do the following (with PhpStorm):
go to VCS->Git->Branches
and merge the Joomla/Stagging to your current repo
screenshot 2015-09-29 14 12 58

**Comment by Mathewlenning** [comment]
I tried that, but it said that it was up-to-date. I think I'm just going to close this PR and redo it on a new branch. The changes were really simple, so it will only take a second.

**Pull request closed without merging**
