### PR TITLE
Batch copy duplicate in chrome and IE as the submit event is triggerd twice

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue  https://forum.joomla.de/thread/10173-stapelverarbeitung-kopiert-beiträge-doppelt (German)

### Summary of Changes

On debugging this issue reported in the [forum (germam)](https://forum.joomla.de/thread/10173-stapelverarbeitung-kopiert-beiträge-doppelt) I have found out that for some reason chrome and IE run the submit event twice and this page here https://www.the-art-of-web.com/javascript/doublesubmit/ pointed me to try `return false;` in the onclick handler to stop that from happening. This worked for me.

#### First test
- Install 3.9.11
- Login to the backend using chrome or IE 11
- try to use a batch copy of articles for example
- apply the patch
- try again

##### seccond test
- install 3.9.11
- Login to the backend using an browser other than chrome and IE
- try to use a batch copy of articles for example
- it should work than expected
- apply the patch
- try again
- it should still work as expected

### Expected result

The batch copy only copy it once

### Actual result

With chrome and IE the batch copy result into two copys

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on c1a9c06854ffd02b38a9d716dd9a100de367babc<br /><br />Tested in Chromium 76 (Manjaro Linux) in the following views:
- Banners
- Categories (Banners)
- Contacts
- Articles
- Fields
- Field Groups
- Menu Items
- Modules
- Newsfeeds
- Redirects
- Tags
- Users

I can confirm that the problem existed before applying this patch and has been fixed after.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26267">issues.joomla.org/tracker/joomla-cms/26267</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c1a9c06854ffd02b38a9d716dd9a100de367babc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26267">issues.joomla.org/tracker/joomla-cms/26267</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thanks for fixing ie bugs.

**Comment by simbus82** [comment]
I thought I was crazy when I saw my colleagues duplicate the content "twice" using the "batch" ... I didn't imagine it was a bug!
The problem was with Chrome.
Thanks a lot guys!

**Comment by zero-24** [comment]
> Thanks for fixing ie bugs.

In this case also a issue that came up in chrome :D

**Pull request merged**
