### PR TITLE
Dgt41 Password strength indication for 3.7.0 - Fixes #8513

### PR DESCRIPTION
**Pull request by Kubik-Rubik**
Pull Request for Issue #8513

Please do not merge in 3.6.0! This is meant for 3.7.0.
#### Summary of Changes

Fixed merge conflicts.
#### Testing Instructions

Is already tested (origin PR is RTC), can be merged directly.

All kudos to @dgt41!

### CODE REVIEW

**Comment by 810** [comment]
why is this feature delayed until J3.7?

**Comment by zero-24** [comment]
We are in a installation language string freez

**Comment by dgt41** [comment]
Can someone close this one and re-open #8513
I've pushed some changes I've already done some time ago:

-It uses the latest version of the script (2.0) 
-It uses jLayout
-Doesn't use any hardcoded things (e.g.: `id="jform_username"`)

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10311">issues.joomla.org/joomla-cms/10311</a>

**Comment by Kubik-Rubik** [comment]
Please see: https://github.com/joomla/joomla-cms/pull/8513#issuecomment-218099899

**Comment by zero-24** [comment]
@Kubik-Rubik @brianteeman  please remove the milestone!

**Pull request closed without merging**
