### PR TITLE
Preparing 3.10 for 4.0 content versioning

### PR DESCRIPTION
**Pull request by Hackwar**
This PR backports a few classes that would be necessary to implement versioning of content items in the same code for extensions in 3.x and 4.0. To support both 3.x-style and 4.0-style versioning, you'd have to implement the 3.x-style first. Good luck with that. To get 4.0-style working, simply let your table class implement the interface VersionableTableInterface (and the method that that defines) and let your item controller and model use the respective Versionable trait. In 3.x, these traits are empty, in 4.0 they contain all the logic necessary for versioning.

### CODE REVIEW

**Comment by Hackwar** [comment]
The original PR to refactor the versioning feature is #23432.

**Comment by zero-24** [comment]
Merging for 3.10 thanks @Hackwar

**Comment by Hackwar** [comment]
This has not been merged into 4.0, so it seems not a good idea to merge this into 3.10

**Comment by zero-24** [comment]
Done thanks.

**Comment by Hackwar** [comment]
Hey, yeah, so... We actually did merge in this feature shortly before the beta release, so we need to add this to 3.10 again...

**Comment by zero-24** [comment]
Can you do a PR and tag me? I'm happy to review and merge as this PR here has been reverted.

**Pull request merged**
