### PR TITLE
[3][com_contact] fix manifest

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #31375 .

### Summary of Changes
removed obsolete entry form the manifest

### Testing Instructions
code review
com_contact works as before

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c8e2868f217e2d69df04da29132ae0bdff7c6f43<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31412">issues.joomla.org/tracker/joomla-cms/31412</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c8e2868f217e2d69df04da29132ae0bdff7c6f43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31412">issues.joomla.org/tracker/joomla-cms/31412</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31412">issues.joomla.org/tracker/joomla-cms/31412</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
