### PR TITLE
[4.1] s/overriden/overridden

### PR DESCRIPTION
**Pull request by brianteeman**
spelling error

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ae1f9eff626174e3fc89838f7a4fa12242e2131<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36818">issues.joomla.org/tracker/joomla-cms/36818</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9ae1f9eff626174e3fc89838f7a4fa12242e2131<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36818">issues.joomla.org/tracker/joomla-cms/36818</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36818">issues.joomla.org/tracker/joomla-cms/36818</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
