### PR TITLE
Module list

### PR DESCRIPTION
**Pull request by astridx**
See the failure
1.  Go to the Extensions | Module Manager and ensure, that you have at least two modules of the type banners for the location site. One is published and another is unpublished.
2.  Switch to Extension Manager|Manage and disable the Modul “Banners” for the location site.
3.  Go back to Extensions | Module Manager and see, that the Status show wrong values. The published Module looks like unpublished and the unpublished value looks like trashed.

Apply my patch
1.  Go to the Extensions | Module Manager and ensure, that you have at least two modules of the type banners for the location site. One is published and another is unpublished.
2.  Switch to Extension Manager|Manage and disable the Module “Banners” for the location site.
3.  Go back to Extensions | Module Manager and see, that the Status did not show the wrong values any more. The Module with disabled extensions has no status.

### CODE REVIEW

**Comment by astridx** [comment]
Attachments
snap1

**Comment by zero-24** [comment]
@astridx why you close here?

**Comment by astridx** [comment]
I did not want to close here. This was a mistake. Is it possible to open this issue again?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7179">issues.joomla.org/joomla-cms/7179</a>.</sub>

**Comment by brianteeman** [comment]
Re-opened

**Comment by astridx** [comment]
@brianteeman
Thank you for reopening.

My suggestion is only a quick fix, so that no wrong values are shown any more. 
I know, that it would be much better, to show a message, so that a user can see, that this extension is disabled. I work on this, but I like to make more experience in contributing for Joomla! Before I change more classes.

Here are text with the missing images:




See the failure
1. Go to the Extensions | Module Manager and ensure, that you have at least two modules of the type banners for the location site. One is published and another is unpublished.
screen shot 2015-06-16 at 02 18 37

2. Switch to Extension Manager|Manage and disable the Modul “Banners” for the location site.
screen shot 2015-06-16 at 02 18 37

3. Go back to Extensions | Module Manager and see, that the Status show wrong values. The published Module looks like unpublished and the unpublished value looks like trashed.
screen shot 2015-06-16 at 02 18 37

Apply my patch
1. Go to the Extensions | Module Manager and ensure, that you have at least two modules of the type banners for the location site. One is published and another is unpublished.
2. Switch to Extension Manager|Manage and disable the Module “Banners” for the location site.
3. Go back to Extensions | Module Manager and see, that the Status did not show the wrong values any more. The Module with disabled extensions has no status.
screen shot 2015-06-16 at 02 24 46
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7179">issues.joomla.org/joomla-cms/7179</a>.</sub>

**Comment by MAT978** [comment]
able to reproduce then #7179 works as describe but I'm not sure about the solution with not showing status anymore...
thanks!

**Comment by Bakual** [comment]
It sure needs some sort of icon with a tooltip explaining that the extension has been disabled. Otherwise it's very confusing that the icons are just missing.

**Comment by astridx** [comment]
Thank you very much for the test and the feedback.

I already wrote that I would prefer a solution with an error message, too.

Motivated by this feedback I am going to update this PR on the weekend and supply an icon. 

How should I do this? Should I open a new PR and ask for closing this PR, or can I update this PR?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7179">issues.joomla.org/joomla-cms/7179</a>.</sub>

**Comment by Bakual** [comment]
You can update this PR by just pushing new commits to this branch.
If you're using the GitHub UI, just select the appropriate branch in your fork before you start editing.

**Comment by zero-24** [comment]
> or can I update this PR?

Yes you can update.

Github UI
- Go to: https://github.com/astridx/joomla-cms/tree/ModuleList
- choose the file
- update the file
- commit


via CLI. (generaly)
- git checkout ModuleList
- `change the files`
- git commit -a -m 'The commit message (something meaningfull here please)'
- git push origin ModuleList
- github User and PW
- fixed

**Pull request closed without merging**
