### PR TITLE
[#33580] [imp] deprecate buggy usergroup field and replace ocurrences with usergrouplist. Fixes #3419

### PR DESCRIPTION
**Pull request by phproberto**
See https://github.com/joomla/joomla-cms/issues/3419

Issue tracker:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33580

### CODE REVIEW

**Comment by davdebcom** [comment]
How to test:
- Open this file /plugins/authentication/joomla/joomla.xml
- before </extension> add the following code:
```
 <config>
        <fields name="params">
        <fieldset name="basic">
        <field
                name="myfield"
                type="usergrouplist"
                label="User Group">
            <option value="">No Group</option>
        </field>
        </fieldset>
        </fields>
    </config>
```

**Comment by davdebcom** [comment]
@test
Works

**Comment by davdebcom** [comment]
How to test:
- Open this file /plugins/authentication/joomla/joomla.xml
- Before ```</extension>``` add the following code:
```
 <config>
        <fields name="params">
        <fieldset name="basic">
        <field
                name="myfield"
                type="usergroup"
                label="User Group">
            <option value="">No Group</option>
        </field>
        </fieldset>
        </fields>
 </config>
```
- Go to Extension > Plugin Manager search for "authentication"
- Open the "Authentication - Joomla"
- You should see a dropdown with default option "Show all groups" which is bad because you set ```<option value="">No Group</option>``` in the above code

- Apply the patch
- Go back to /plugins/authentication/joomla/joomla.xml
- Change type="usergroup" to   type="usergrouplist"
- Go the "Authentication - Joomla" plugin again
- You should now see the dropdown shows "No group"
- If you do see "No group" in the dropdown, it works!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3421">issues.joomla.org/joomla-cms/3421</a>.</sub>

**Comment by phproberto** [comment]
I have updated this PR but I'm closing it and create a new PR against `3.5-dev` branch.

Thanks everybody for your comments / tests!

**Comment by phproberto** [comment]
New PR: https://github.com/joomla/joomla-cms/pull/6229

**Comment by phproberto** [comment]
Reopened so this is merged into staging branch.

**Pull request merged**
