### PR TITLE
[5.0] Change can do to Registry

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Changes the canDo ACL checks in views to `Registry`. Internally a `State` class is used for 100% backwards compatibility.

### Testing Instructions
Open the following form views:
- Banners client
- Any category
- Fields field
- Fields groups

### Actual result BEFORE applying this Pull Request
All action bar buttons are shown.

### Expected result AFTER applying this Pull Request
All action bar buttons are shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/176
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wilsonge** [comment]
Please don’t mix model state into this! If we need a b/c class create something else even if a duplicate. Or don’t call it state and put it in the model folder

**Comment by laoneo** [comment]
Fair enough, was a bit lazy :man_shrugging:

**Comment by HLeithner** [comment]
Thanks can you add a b/c change entry to the manual please

**Comment by laoneo** [comment]
Manual entry https://github.com/joomla/Manual/pull/176

**Pull request merged**
