### PR TITLE
[4.0] Fix wrong transition XML for article edit

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #23960 .

### Summary of Changes
Fix the wrong XML attributes for transitions field in com_content article.

### Testing Instructions
Login as non-Super User and check the transitions dropdown

### Expected result
See all transitions with your permission level.

### Actual result
No transitions.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 65e279727930fef2d21da10cbbe62c42c081d7c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23996">issues.joomla.org/tracker/joomla-cms/23996</a>.</sub>

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on 65e279727930fef2d21da10cbbe62c42c081d7c4<br /><br />Hi,

same issue in file components/com_content/forms/article.xml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23996">issues.joomla.org/tracker/joomla-cms/23996</a>.</sub>

**Comment by bembelimen** [comment]
> Hi,
> 
> same issue in file components/com_content/forms/article.xml

Thx, fixed, please test again.

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on 170edbac13b3896c546ec593a2da52dd1fbbe6ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23996">issues.joomla.org/tracker/joomla-cms/23996</a>.</sub>

**Comment by robertolongo** [comment]
I have tested this item :white_check_mark: successfully on 170edbac13b3896c546ec593a2da52dd1fbbe6ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23996">issues.joomla.org/tracker/joomla-cms/23996</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23996">issues.joomla.org/tracker/joomla-cms/23996</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
