### PR TITLE
Remove useless strpos() checking

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The patch removes useless strpos() check. 
This event is set up in AssetRegistry by class name already. Also it is not a system wide event, and never should be.

### Testing Instructions
Apply patch, and check that the site works as before.

### Actual result BEFORE applying this Pull Request
Works.

### Expected result AFTER applying this Pull Request
Works.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
Tested and nothing is broken. But please remove the unused use statement

```php
use Joomla\CMS\Event\WebAsset\WebAssetRegistryAssetChanged;
```

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 048a4e921942b9fc2775e10b4e2d122b9858d252<br /><br />Tested successfully in Joomla 4.3.0-beta5-dev of 16 March using PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40133">issues.joomla.org/tracker/joomla-cms/40133</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 048a4e921942b9fc2775e10b4e2d122b9858d252<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40133">issues.joomla.org/tracker/joomla-cms/40133</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40133">issues.joomla.org/tracker/joomla-cms/40133</a>.</sub>

**Comment by obuisard** [comment]
Thanks Fedir @Fedik !

**Pull request merged**
