### PR TITLE
Improve clarification on how to use the banned fields in Contacts.

### PR DESCRIPTION
**Pull request by roland-d**
#### Summary of Changes

When users are editing a contact on the Form tab they can add banned email/subject/words. It is unclear how to separate multiple values. This change updates the tooltip with this information.
#### Testing Instructions
1. Go to Components -> Contacts
2. Click on New
3. Go to the Form tab and check the tooltip for Banned Email, Banned Subject and Banned Text. There is no mentioning on how to enter multiple values.
4. Apply the patch
5. Go to Components -> Contacts
6. Click on New
7. Go to the Form tab and check the tooltip for Banned Email, Banned Subject and Banned Text. The tooltip now shows how to enter multiple values.

### CODE REVIEW

**Comment by roland-d** [comment]
@brianteeman Brian, pinging you since you are the native speaker :)

**Comment by brianteeman** [comment]
I took a quick look and the strings are fine. I just wanted to check that it was a semi-colon that was the separator or not

**Comment by roland-d** [comment]
Thanks for checking Brian.

@wilsonge Merge for 3.5.1?

**Comment by brianteeman** [comment]
If you have a banned word in the subject is it still supposed to say "sent email"

**Comment by roland-d** [comment]
I don't think it is because it doesn't send anything glancing over the code. That would be a separate PR though to deal with that issue.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 55846640b71cca252bd88172fae90bcfc16d34e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9512">issues.joomla.org/joomla-cms/9512</a>.</sub>

**Comment by brianteeman** [comment]
Its ok - I was just looking to see ghat it was a semi-colon and not a colon - i couldnt find the code but I have done now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9512">issues.joomla.org/joomla-cms/9512</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 55846640b71cca252bd88172fae90bcfc16d34e3<br /><br />Thanks

Maybe an already fixed question but what about adding: `(;)`
for non-native speakers that stay in en-GB, this maybe could help. Thoughts?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9512">issues.joomla.org/joomla-cms/9512</a>.</sub>

**Comment by roland-d** [comment]
@MATsxm I thought about it as well but decided not to include it. It is a fairly common character. If we are going to include this I would like to hear how to incorporate it into the sentence.

**Comment by brianteeman** [comment]
There is no easy way to do that and tbh if we were to do it here we would
need to do it in a LOT of other places. Those are the sort of changes that
the TT scream about

**Comment by roland-d** [comment]
Let's leave it as-is then :)

**Comment by brianteeman** [comment]
Setting as RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9512">issues.joomla.org/joomla-cms/9512</a>.</sub>

**Comment by infograf768** [comment]
Why setting the milestone to 3.5.2?

**Comment by wilsonge** [comment]
Because with all the issues we need a small 3.5.1 without language string changes ;)

**Comment by brianteeman** [comment]
because 3.5.1 will be within the next x hours and its a language change so
that wont give the TT long enough to translate

**Comment by infograf768** [comment]
I did not know, so no lang change in 3.5.1, right?

**Comment by brianteeman** [comment]
right

**Pull request merged**
