### PR TITLE
[4.0] Change class to allow closing of menus when opening another

### PR DESCRIPTION
**Pull request by roland-d**
Pull Request for Issue #26536 

### Summary of Changes
Use the show class to allow the menu to be closed when opening another menu

### Testing Instructions
1. Compile the JS
2. Login to the backend
3. Open a menu and select an item
4. Now the menu that you opened is open by default, click another toplevel menu
5. The active menu should be closed and the clicked menu open

### Expected result
The only open menu is the one clicked

Not sure if this is what the expected outcome is as no desired outcome is mentioned in issue #26536 

### Actual result
There are 2 open menus, the one clicked and the active menu

### Documentation Changes Required
None

@infograf768 @brianteeman

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8d63bdbe99b025e508bd62d11b0e266fb4effa5a<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26560">issues.joomla.org/tracker/joomla-cms/26560</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8d63bdbe99b025e508bd62d11b0e266fb4effa5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26560">issues.joomla.org/tracker/joomla-cms/26560</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26560">issues.joomla.org/tracker/joomla-cms/26560</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8d63bdbe99b025e508bd62d11b0e266fb4effa5a<br /><br />Thanks - tested on mobile and desktop<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26560">issues.joomla.org/tracker/joomla-cms/26560</a>.</sub>

**Pull request merged**
