### PR TITLE
isis template styling changes to sidebar

### PR DESCRIPTION
**Pull request by ChristopherRaymond**
Changed the styling of the sidebar to move it off the "title" baseline when "Display Header" is set to "No". Also added stylizing to the sidebar "arrow" to give it a little more visual presence: http://awesomescreenshot.com/0ef4ib4w7b
http://awesomescreenshot.com/0024ib411b
http://awesomescreenshot.com/0204ib7k8f

### CODE REVIEW

**Comment by recreatorshop** [comment]
@test
in joomla 3.4 "	Article Manager: Articles" is already visable but this patch corrected the sidebar: now there is space between the sidebar and the toolbar.

i think it is an improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by pe7er** [comment]
@test

This patch adds some space between toolbar & sidebar.
Before:
screen shot 2015-02-28 at 07 58 01

After installing Patch
screen shot 2015-02-28 at 07 58 01
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by pe7er** [comment]
Sorry, I've added the images in the wrong order...

The 1st image is the extra space after the patch.
The 2nd image is before applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by fvdn** [comment]
@test 
Tested it in Joomla 3.4
1) I can not simulate te problems of the "Display Header" i see in the added pictures (http://awesomescreenshot.com/0ef4ib4w7b | http://awesomescreenshot.com/0024ib411b | http://awesomescreenshot.com/0204ib7k8f).

2) I can see the change in the "top" styling of the left sidebar. Its now on the top in-line with the other collums, indeed after the patch the visual presence is better!


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by josien** [comment]
@test 
Patch also adds a little styling to the arrow:
screen shot 2015-02-28 at 08 11 21screen shot 2015-02-28 at 08 11 29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by ChristopherRaymond** [comment]
@josien Correct. This small style addition adds a visual anchor to this element.

**Comment by zero-24** [comment]
RTC based one various testing. Thanks for testing and coding!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by losedk** [comment]
Shouldn't the less file be updated as well? And what about the rtl version?

**Comment by zero-24** [comment]
Thanks @losedk moving back to pending. can you generate the CSS files using the https://github.com/joomla/joomla-cms/blob/staging/build/generatecss.php and update the less files @ChristopherRaymond<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by JoomliC** [comment]
As i have stated in issue https://github.com/joomla/joomla-cms/issues/6178#issuecomment-76102122 i think changing the margin is not the best solution.

If an option in admin template is supposed to hide the header (title + joomla logo), is it needed to display the title ?
I'm not sure this to be logical... And i wonder the reason for this?

But, if the title should always be displayed, so, in that case, maybe the best solution would be to move the lines below.

Maybe it would be better to remove those lines in index.php (if we should really consider the template option as this one is meant to do) : 

```
// Show the page title here if the header is hidden
if (!$displayHeader) : ?>
    <h1 class="content-title"><?php echo JHtml::_('string.truncate', $app->JComponentTitle, 0, false, false); ?></h1>
<?php endif; ?>
```

**Comment by JoomliC** [comment]
Or maybe don't change margin in sidebar, but for the class used when title is in content : 
```
.content-title {
	font-size: 24px;
	font-weight: normal;
	line-height: 26px;
	margin-top: 0;
}
```
By changing the above class, this way, you won't change the sidebar if the header is displayed.

;-)

**Comment by ChristopherRaymond** [comment]
@JoomliC I believe the result of turning off the header is accurate in its current state. When we hide the header, all its contents: icon/title/logo/styles are no longer visible gaining a small amount of screen real estate and a cleaner appearance(IMHO). We simply are removing the stylization of the title. But the title I see as an important element that needs to remain regardless of what experience you choose.

**Comment by JoomliC** [comment]
@ChristopherRaymond Let's go back to the main purpose of your PR : better position of the sidebar, if Isis Template option "Display Header" is set to "No" ;-)
So, don't change the class .j-toggle-button-wrapper, this one is good when Header is displayed!

Please, better edit the class .content-title, which one exists for the case the Header is not displayed, but only the title (this what you want!)
For example : 
```
.content-title {
	font-size: 24px;
	font-weight: normal;
	line-height: 26px;
	margin-top: 0;
	padding-bottom: 10px;
}
```

Or another one, maybe more clean (in LTR, and with a float left on RTL) : 
<pre>
.content-title {
	font-size: 24px;
	font-weight: normal;
	line-height: 26px;
	margin-top: 0;
	<b>float: right;</b>
}
</pre>

;-)

**Comment by ChristopherRaymond** [comment]
@JoomliC Good thinking, will make that edit.

**Comment by JoomliC** [comment]
@ChristopherRaymond You're welcome ;-)

Don't forget to edit template.less, and use the generatecss.php as @zero-24 told you ;-)
And if changes in left/right, don't forget to update too the RTL less file if needed.

In all cases, don't hesitate to ask for help if needed.
When updated, will test and give feedback ;-)
Cyril

**Comment by ChristopherRaymond** [comment]
@zero-24 @JoomliC - I believe I updated the less file correctly. My apologies in advance if not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by JoomliC** [comment]
@ChristopherRaymond Sorry for slow response...

In fact, no it's not good, rtl less not updated.
So, i will try to help as far as i can.
The css should be updated only in less files.
Then, use generatecss.php script which will automatically create the template.css and template-rtl.css useing the less files of the template, which are loading too the core less files (icomoon, buttons... and a lot of predefined css for bootstrap or else use by joomla).

Do you develop on local and if yes on windows or mac ? (i know the process on mac using terminal, not on windows, but may be very similar)
link: https://docs.joomla.org/Joomla_LESS

About your changes, i will recommend you to open this PR and change only for the issue with display header, because if you add a styling change there too, this one could take more time before to be commit to staging! (look at the debate here just for one icon change : https://github.com/joomla/joomla-cms/issues/6310)

So, in my opinion, focus this PR only on Display header, without changes to sidebar, and your PR will be able to be merge faster.

And if you want to propose a better styling for button, maybe check first my PR here, and open a new one when ready : https://github.com/joomla/joomla-cms/pull/6327

This way, could be better ;-)

**Comment by ChristopherRaymond** [comment]
Thanks @JoomliC I will take a look. I am on a MAC. I'll deal with this first then open a new request as suggested regarding the arrow styling.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6222">issues.joomla.org/joomla-cms/6222</a>.</sub>

**Comment by zero-24** [comment]
>I'll deal with this first then open a new request as suggested regarding the arrow styling.

@ChristopherRaymond what is the status here? Can we close here if you open a new issue?

**Comment by recreatorshop** [comment]
Yo van close it.
We have test it a few Times.
Op 1 apr. 2015 18:02 schreef "zero-24" <notifications@github.com>:

**Comment by zero-24** [comment]
Thanks so i'm closing here as requested.

**Comment by ChristopherRaymond** [comment]
sorry for the late response @zero-24 - I got hung up with the less conversion. Should I continue with this or leave it closed?

**Pull request closed without merging**
