### PR TITLE
[4.0] Unused atum string

### PR DESCRIPTION
**Pull request by brianteeman**
Can't find any usage of this string.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cce33eaee86a61e4f5ec5b52cdfd0cc7c70f583a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32323">issues.joomla.org/tracker/joomla-cms/32323</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on cce33eaee86a61e4f5ec5b52cdfd0cc7c70f583a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32323">issues.joomla.org/tracker/joomla-cms/32323</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32323">issues.joomla.org/tracker/joomla-cms/32323</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
