### PR TITLE
[4.3] Tinymce - style previews

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40079 .

### Summary of Changes
Specify the atributes to be used when previewing a style. This prevents white text on a white background making the preview invisible.

### Testing Instructions
Add the following class to `media\system\css\editor.css` or `media\system\css\editor.min.css` (depends if you have debug on
```
.white-text {
  color: #fff;
}

```

### Actual result BEFORE applying this Pull Request
You cannot see the class in the menu as its color of white is used in the preview and makes it invisible

image

### Expected result AFTER applying this Pull Request
You can see the class as we don't preview colours in the menu

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by korenevskiy** [comment]
@brianteeman  I tested and also tried an alternative option. I added the image background style to the array.
Which may be relevant the same way as background-color.
We see that the background of the pictures will not be applied to the menu item, since the background of the picture has a relative path error. This may not be relevant. Since we don't use this style. But if we use the `background-color` style, then we need to use the `background-image` style.

image

**Comment by brianteeman** [comment]
thats not a good approach. As tinymce provide an option xpecifically for this then we should use it.

**Comment by korenevskiy** [comment]
This is probably due to the fact that it was decided not to use the `<BASE>` header tag.

**Comment by korenevskiy** [comment]
Are there plans to go back to the idea of using the `<BASE>`tag in the future?

**Comment by brianteeman** [comment]
it is irrelevant. it is not the correct way to do this. when there is a documented api it should always be used. Especially when it is from a third party. Then you will know that if they change it you will need to update.

**Comment by korenevskiy** [comment]
I meant in major versions a return to using the BASE tag, with new rules with new functions.

**Comment by brianteeman** [comment]
this is not the topic of this Pull Request. Every time you go off topic you delay the changes. I made this pull request because you asked for it. if you dont want it then I will simply close it and do something more interesting.

**Comment by korenevskiy** [comment]
Thanks. I tested it. Cool. Everything works.

I didn't want to delay. I am very grateful. I was interested about a general question.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on daf8b27900af0b2b7a8685670c2c5026709e1f00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40206">issues.joomla.org/tracker/joomla-cms/40206</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40206">issues.joomla.org/tracker/joomla-cms/40206</a>.</sub>

**Comment by obuisard** [comment]
Thanks Brian @brianteeman, great PR.

**Comment by brianteeman** [comment]
thx

**Comment by korenevskiy** [comment]
thx

**Pull request merged**
