### PR TITLE
[4.0] skipto plugin typo

### PR DESCRIPTION
**Pull request by brianteeman**
Obvious mistake by me. Thanks to @tecpromotion for spotting it

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0e8262d4fe3c9f5f54db33f4c562a2ef6512d10c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32763">issues.joomla.org/tracker/joomla-cms/32763</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0e8262d4fe3c9f5f54db33f4c562a2ef6512d10c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32763">issues.joomla.org/tracker/joomla-cms/32763</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32763">issues.joomla.org/tracker/joomla-cms/32763</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
