### PR TITLE
[mod_articles_category] Fatal error

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes fatal error caused by the use of `$this`. Merge on review.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e959de2f1c2ff9c61cc6b37e2b4540709431f91e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20834">issues.joomla.org/tracker/joomla-cms/20834</a>.</sub>

**Comment by infograf768** [comment]
RTC as obvious.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20834">issues.joomla.org/tracker/joomla-cms/20834</a>.</sub>

**Comment by infograf768** [comment]
@mbabker please merge.

**Comment by conseilgouz** [comment]
I have tested this item :white_check_mark: successfully on e959de2f1c2ff9c61cc6b37e2b4540709431f91e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20834">issues.joomla.org/tracker/joomla-cms/20834</a>.</sub>

**Pull request merged**
