### PR TITLE
[4.0] mod sampledata help link

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29729

Fixes an obvious copy paste error

Thanks @ceford

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d91331107de138630fb9f62b126f277c52dc8f6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29730">issues.joomla.org/tracker/joomla-cms/29730</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d91331107de138630fb9f62b126f277c52dc8f6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29730">issues.joomla.org/tracker/joomla-cms/29730</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29730">issues.joomla.org/tracker/joomla-cms/29730</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
