### PR TITLE
[4.4] Update TinyMCE to 5.10.8

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Updating TinyMCE to 5.10.8 to fix a mXSS vulnerability, see:
https://github.com/tinymce/tinymce/security/advisories/GHSA-v65r-p3vv-jjfv

### Testing Instructions
Apply patch, run npm install to download the updated Tiny version, test the editor.

```
Version 5.10.8 - October 19, 2023
Fixed

Specific HTML content caused mXSS when using undo/redo.
Specific HTML content caused mXSS when using the getContent and setContent APIs with the format: 'raw' option, which also affected the resetContent API and the draft restoration feature of the Autosave plugin.
Notification messages containing HTML were not properly XSS sanitized before being displayed.

```

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 285febb90a1f6f06af06f9da9271cc09c238315f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42239">issues.joomla.org/tracker/joomla-cms/42239</a>.</sub>

**Comment by heelc29** [comment]
Plugin manifest version should be updated too.

**Comment by SniperSister** [comment]
Good catch @heelc29 , done!

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on a8980bb9a6070b42d0cff1f7d791a3301edc61d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42239">issues.joomla.org/tracker/joomla-cms/42239</a>.</sub>

**Comment by laoneo** [comment]
Merging as there is currently an issue with mysql 5.7 on appveyor.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
