### PR TITLE
Spelling mistake en-GB

### PR DESCRIPTION
**Pull request by brianteeman**
Fix multiple instances of a spelling mistake
Occurred not occured

NOTE I did not touch external libraries

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 7521f381ba0f0d3721084a4f0c4700622a2cae6e<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11039">issues.joomla.org/joomla-cms/11039</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7521f381ba0f0d3721084a4f0c4700622a2cae6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11039">issues.joomla.org/joomla-cms/11039</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11039">issues.joomla.org/joomla-cms/11039</a>.</sub>

**Comment by Stevec4** [comment]
Brian
I found another instance of this in en-GB.com_intaller.ini line 143. 

Steve

**Comment by brianteeman** [comment]
@stecec4 If you look that line is in this Fix

**Pull request merged**
