### PR TITLE
Icons instead of images in com_redirect

### PR DESCRIPTION
**Pull request by peterlose**
PR that changes the states to icons instead images. It also adds a new column to the state
## Before PR

skaermbillede 2015-02-17 kl 23 29 19
## After PR

skaermbillede 2015-02-17 kl 23 29 39

### CODE REVIEW

**Comment by brianteeman** [comment]
Nice find - easy fix - works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6115">issues.joomla.org/joomla-cms/6115</a>.</sub>

**Comment by brianteeman** [comment]
Two test - moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6115">issues.joomla.org/joomla-cms/6115</a>.</sub>

**Comment by brianteeman** [comment]
Oops I missed that it is failing the travis tests - can you fix that first please

>  55 | ERROR | Whitespace found at end of line
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6115">issues.joomla.org/joomla-cms/6115</a>.</sub>

**Comment by losedk** [comment]
Already did

**Comment by brianteeman** [comment]
Weird the tracker isnt updated yet - but I can see it passed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6115">issues.joomla.org/joomla-cms/6115</a>.</sub>

**Comment by losedk** [comment]
Yeah noticed that. Is that a general problem? Or does it take some time to sync?

**Comment by brianteeman** [comment]
Yes it just takes a little while to update the results<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6115">issues.joomla.org/joomla-cms/6115</a>.</sub>

**Pull request merged**
