### PR TITLE
[4.0] Adapting alternate menu preset to J4

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Now that https://github.com/joomla/joomla-cms/issues/26067 has been merged, we can update the alternate preset menu `Preset - Alternative Main Menu`

This separates the Home Dashboard from System to add it as first Menu item.
It moves the Media menu below the Content menu.
It corrects the redundant Workflows menu item from Content.

### Testing Instructions
Edit the default Administrator Menu module and choose `Preset - Alternative Main Menu`

### Before patch
Home dashboard is a sub of System
Media comes above Content
Workflows menu item is added twice in Content menu

### After patch
Screen Shot 2019-09-01 at 09 27 30

@chmst @ChristineWk

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f6811180c1f84356a326f09cf344e86da836fde3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26115">issues.joomla.org/tracker/joomla-cms/26115</a>.</sub>

**Comment by brianteeman** [comment]
I have marked it as a success because it does what it says.

BUT it has several issues
1. how are you going to provide access to some of the core components that are not in the menu db table such as post installation messages 
2. any menu item that has an add new is no longer a link eg there are no links to the list of all ~articles~ menus <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26115">issues.joomla.org/tracker/joomla-cms/26115</a>.</sub>

**Comment by chmst** [comment]
@brianteeman agree completely with you. 
I did the renaming because we had the presets since a long time and I always had this feeling "This here is modern, so Joomla ist the old-fashined one" . 
But now the alternate preset must be made with care and  give good alternative. This was not in scope.

**Comment by brianteeman** [comment]
I'm not sure if with the changes made to make the menus for the template if it's going to be possible

**Comment by infograf768** [comment]
This is a part 1 of the alternate preset.
I am now looking at the remaining issues.

**Comment by brianteeman** [comment]
Good luck with that

**Comment by infograf768** [comment]
> how are you going to provide access to some of the core components that are not in the menu db table such as post installation messages

I can get them eaasily as well as J update.
Screen Shot 2019-09-01 at 16 32 10

> any menu item that has an add new is no longer a link eg there are no links to the list of all menus 

Not sure I understand this one. 
List of all menus as well as all menu items is already present and one can add new for Menus.


Can you point to me the items that really need to be looked at.

**Comment by infograf768** [comment]
Found one: Adding a new Menu is missing. Looking at that one now.

**Comment by infograf768** [comment]
We can also add back where necessary what was deleted by someone in J4.
For example below for New user
Old way
Screen Shot 2019-09-01 at 17 05 03


or with a quicktask
Screen Shot 2019-09-01 at 17 09 39

**Comment by infograf768** [comment]
@chmst 
Please add your test OK so that we get it merged and I go on improving this alternate.

**Comment by brianteeman** [comment]
> Can you point to me the items that really need to be looked at.

Not at my PC but from memory it was not possible to list all menus.

**Comment by infograf768** [comment]
> Not at my PC but from memory it was not possible to list all menus.

It does already list all menus as is.

**Comment by brianteeman** [comment]
> It does already list all menus as is.


Not menu items - menus
index.php?option=com_menus&view=menus

**Comment by infograf768** [comment]
Understood now what you mean.
Will add quicktasks for all places where necessary in Part2 as soon as this one is merged.

**Comment by infograf768** [comment]
Decided to complete the alternate instead of waiting for another PR.
It should now provide all possible navigation. 
@chmst @brianteeman 

please test again

**Comment by brianteeman** [comment]
Removing the add new to the menus solved that problem

I now see an issue with the selected menu not being highlighted (and or expanded) when you open a link from the dashboard eg thw templates quickicon

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26115">issues.joomla.org/tracker/joomla-cms/26115</a>.</sub>

**Comment by infograf768** [comment]
> I now see an issue with the selected menu not being highlighted (and or expanded) when you open a link from the dashboard eg thw templates quickicon

Looks OK here:
template

Works also fine for Joomlaupdate etc.

**Comment by infograf768** [comment]
If you speak about the  Templates in the Site submenu module, i.e
Screen Shot 2019-09-02 at 18 35 38

Then you are correct. Issue comes from the url.
The icon uses the client
`administrator/index.php?option=com_templates&client_id=0`
while the menu item does not.
The issue is easy to solve.
Correcting now.

**Comment by infograf768** [comment]
Changed to use similar urls for Modules and templates styles.

**Comment by infograf768** [comment]
I see that we also have to do something similar for Users and articles categories but the links used for that last one is weird
`index.php?option=com_categories`
I think it should be
`index.php?option=com_categories&amp;extension=com_content`

I will try to find out where in code this is used.
EDIT:
It is used in Quickiconhelper. Weird.

**Comment by infograf768** [comment]
Ok, now when clicking a quickicon, the corresponding menu item should be hightlighted/expanded when using the alternate.xml.
I had to correct a totally wrong link for the Quickicon Menu Items and modified the Quickicon Article Categories.

### Important Note
I found out that **it was also NOT the case** when using the default.xml preset as links may be different. Is mostly missing  the view in quickicon links.
Therefore, another PR should be done where we make sure that the links are normalized in the 3 cases as this PR does not concern modern.xml:

- modern.xml
- alternate.xml
- QuickiconHelper.php

This can be tested when showing ALL quickicons in the Site quickicon module and testing them one after the other:
Screen Shot 2019-09-03 at 08 29 20

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
OK. Will now create another PR to normalise the urls.

**Pull request merged**
