### PR TITLE
[4.0] Fix 2 strings in com_templates.ini (#31710)

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Referring to the adjustments in PR #31710, I noticed 2 things in the translation of the strings.
It checks for joomla.asset.json but uses index.php in line 
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/com_templates.ini#L41

Second point is "doesn't not" which should be a does not or doesn't. 
https://github.com/joomla/joomla-cms/blob/12c12e87b3a8b58ec296369d8f0344da79d24720/administrator/language/en-GB/com_templates.ini#L42

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 032e60b8ea277d6a292a3d92489213f95d9064b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31939">issues.joomla.org/tracker/joomla-cms/31939</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 032e60b8ea277d6a292a3d92489213f95d9064b4<br /><br />Tested successfully in Beta7-dev of 9 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31939">issues.joomla.org/tracker/joomla-cms/31939</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31939">issues.joomla.org/tracker/joomla-cms/31939</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
