### PR TITLE
[4.0] Replace file_exists() where applicable

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Replaces `file_exists()` checks with more suitable `is_file()` and `is_dir()`, e.g. to avoid including directories as PHP files.

### Testing Instructions

Browse around, do some Joomla things.

### Expected result AFTER applying this Pull Request

Still works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on ae66656986d8c3186c49f53ca6087713d813990b<br /><br />I browsed around with no problems. Noted there are 294 instances of file_exists before and 235 after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30800">issues.joomla.org/tracker/joomla-cms/30800</a>.</sub>

**Comment by ohrionmartin** [comment]
I have tested this item :white_check_mark: successfully on ae66656986d8c3186c49f53ca6087713d813990b<br /><br />System Information
=============
php: Linux orion 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
dbserver: mysql
dbversion: 8.0.21-0ubuntu0.20.04.4
dbcollation: utf8mb4_0900_ai_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.4.3
server: Apache/2.4.41 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 4.0.0-beta4 Beta [ Mañana ] 15-September-2020 13:46 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30800">issues.joomla.org/tracker/joomla-cms/30800</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30800">issues.joomla.org/tracker/joomla-cms/30800</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
