### PR TITLE
Support Codemirror's included key mappings

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
### Summary of Changes
First of all, this includes CodeMirror 5.35.0 so it's the same as #19809
Additionally, it removes the old option for "Vim Mode" and replaces it with additional choices for key mappings. Vim is still one of them (and will be used if you had previously selected Vim Mode) but now Emacs and Sublime Text are also provided. So, if you're familiar with any of those editors, you can make CodeMirror use similar keys and behave in mostly the same way. 

Since it doesn't make much sense to load all key mappings at the same time (you use either zero or one of them), key mapping info will not be loaded unless needed. As a result, the addons file (a bundle of several codemirror plugins) is much smaller now.

### Testing Instructions
Use CodeMirror. If you are familiar with Vim, Emacs, or Sublime Text, use one of those key mappings. Notice the change in CodeMirror's behavior. 

### Expected result
CodeMirror should work as usual. Additional Key Mapping modes should work somewhat like other editors.

### Actual result
As expected.

### Documentation Changes Required
I guess not.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Appveyor is wrong. There is no problem.

**Comment by infograf768** [comment]
restarted Travis as it was failing

**Comment by zero-24** [comment]
Works great (just tested subline syntax examples) but what do you think about a dropdown vs. 4 radio buttons?

**Comment by brianteeman** [comment]
Dont know why but patchtester isnt pulling all the files but looking at the code I agree with @zero-24 - it should be a dropdown

**Comment by zero-24** [comment]
> Dont know why but patchtester isnt pulling all the files

Yes i have done a clean install of the branch that solves the issue. ;)

**Comment by okonomiyaki3000** [comment]
ok, it can be a dropdown

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 115b803844c0a715359eb95452c6a26a6bd1d98a<br /><br />Thanks :+1: 

Can you please solve the conflicts comming from the merge of the other Codemirror PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19833">issues.joomla.org/tracker/joomla-cms/19833</a>.</sub>

**Comment by okonomiyaki3000** [comment]
This should be good to go. There's another update to codemirror but I don't want to make a PR for it until this gets merged.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 160afb840cef1a44c90c2f81f9d9a4317a772c8e<br /><br />Thanks @okonomiyaki3000 :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19833">issues.joomla.org/tracker/joomla-cms/19833</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Hmm. Still waiting on this, eh?

**Comment by okonomiyaki3000** [comment]
Another new version of CodeMirror is out but I won't be updating until this gets merged.
http://codemirror.net/doc/releases.html

**Comment by Quy** [comment]
For `Default` value, should it be `None` or `Off`?

**Comment by okonomiyaki3000** [comment]
Looks like I set the default value to empty string. The default text is 'Default'. CodeMirror's default is actually `"default"` so maybe I should double check.

**Comment by Quy** [comment]
With this patch applied, the editor does not display properly. Does not matter which KeyMap is selected. Tested with v3.8.8 dev.

**Comment by Quy** [comment]
For the plugin configuration, it is not b/c if previously enabled with the old option. You will have to reselect `vim` with the new option, otherwise, it will default to `Default`.

**Comment by okonomiyaki3000** [comment]
No, I guess I was not setting it to empty string. I don't know why I thought I was. Actually, I don't see any issue with the code but let me test it a bit and get back to you.

**Comment by okonomiyaki3000** [comment]
@Quy I could not duplicate your issue. I will rebase with the latest staging but I don't really see why it should make any difference. I don't believe there have been any other changes to CodeMirror.

**Comment by okonomiyaki3000** [comment]
Yeah, no such issue. Could you tell me which browser you're using and whether there are any messages in your javascript console?

**Comment by Quy** [comment]
Sorry false alarm. It is working now.

**Comment by zero-24** [comment]
> Sorry false alarm. It is working now.

@Quy so we can move this to RTC now?

**Comment by zero-24** [comment]
and please @brianteeman do your en-GB review here so we can move forward :)

**Comment by Quy** [comment]
Couple of observations:

* It is not obvious what `Default` does. I suggested `None` or `Off` to imply key mapping is disabled.

* When configuring the plugin initially, the new option will not select `vim` if the old option is `On`. You have to reselect `vim` with the new option. 

If these are non issues, then ok to be RTC.

**Review by brianteeman — APPROVED** [review]

**Comment by okonomiyaki3000** [comment]
> It is not obvious what Default does. I suggested None or Off to imply key mapping is disabled.

But it is not 'none' or 'off'. It is CodeMirror's default. It does have some keys mapped by default. For example, Ctrl-D deletes a line, Ctrl-Z is undo, etc. Changing to a different one overwrites this. So then, with Sublime key mapping, Ctrl-D doesn't delete a line but duplicates your current selection to the next matching string. And so on. 

> When configuring the plugin initially, the new option will not select vim if the old option is On. You have to reselect vim with the new option.

Hmm. That's not the way I thought I coded it and it's not the way it worked when I tested it. Let's both check again.

**Comment by Quy** [comment]
To reproduce. 

* Enable `Vim Keybinding`
* Apply patch
* Edit CodeMirror plugin
* `Key Map` is set at `Default` when it should be `Vim`

**Comment by okonomiyaki3000** [comment]
@Quy Ah, yes. You're right about that. In fact, if you were to use CodeMirror without going to the settings first, you'd still have Vim but it's true that the settings reset to default. Well, really the only way to fix that is to modify the form data in onContentPrepareData which doesn't even get fired on editor plugins so it would require adding a content plugin just for this one thing... I think not worth it.

**Comment by Quy** [comment]
Yes. It is not worth it. It can be a one-time quick fix by setting the new option.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1b102a2c6945d3ab9999946573d3743225a27c7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19833">issues.joomla.org/tracker/joomla-cms/19833</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19833">issues.joomla.org/tracker/joomla-cms/19833</a>.</sub>

**Pull request merged**
