### PR TITLE
[5.x] Localize own package

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Localise my own gzip package `@dgrammatiko/compress`

### Testing Instructions

Check out this PR
- run `npm i`
- run `npm gzip`

Check that the gzipped files inside the media folder are created
Rename the htaccess.txt and check if the gzipped files are loading correctly

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 918bb2c742bda2cfe61038468a6dc2ca665443e1<br /><br />Gzip files are created. Website loads OK. I had to run 'composer install' after checkout. Then 'npm ci', then 'npm run gzip' (not npm gzip). Turned on 'Gzip Page Compression' in Global Configuration, Server Tab. Check Requests to js or css in Browser debug page. Content-Encoding must be gzip.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42428">issues.joomla.org/tracker/joomla-cms/42428</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 918bb2c742bda2cfe61038468a6dc2ca665443e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42428">issues.joomla.org/tracker/joomla-cms/42428</a>.</sub>

**Comment by HLeithner** [comment]
5.1 please

**Comment by LadySolveig** [comment]
Thank you @dgrammatiko and also for testing @MacJoom @viocassel

**Pull request merged**
