### PR TITLE
[6.0] Set version to 6.0

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says.

### CODE REVIEW

**Comment by brianteeman** [comment]
LGTM - are you also going to update the readme etc?

**Comment by Hackwar** [comment]
done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5bec09d4b1f97b19b1e94d8f38eddfab94907dee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42969">issues.joomla.org/tracker/joomla-cms/42969</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
