### PR TITLE
[5.1] Give a name for the breadcrumbs schema.org asset

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The PR gives a name for the breadcrumbs asset for schema.org, 
By default the name is md5 of the asset content, wich is not very useful for this asset.
Specific name will allow others extensions easily access to it.

### Testing Instructions
Apply patch, visit the page with the breadcrumbs.
Check page source, and make sure BreadcrumbList schema is there.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I may have done something wrong - the original and patch produce identical output:

```
<script type="application/ld+json">{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "@id": "http://localhost/joomla-cms5/#/schema/BreadcrumbList/17",
    "itemListElement": [
        {
            "@type": "ListItem",
            "position": 1,
            "item": {
                "@id": "http://localhost/joomla-cms5/",
                "name": "Home"
            }
        },
        {
            "@type": "ListItem",
            "position": 2,
            "item": {
                "@id": "http://localhost/joomla-cms5/testing-home-1.html",
                "name": "Testing Home"
            }
        },
        {
            "@type": "ListItem",
            "position": 3,
            "item": {
                "name": "Lorem Ipsum"
            }
        }
    ]
}</script>
```
Can that be right?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42881">issues.joomla.org/tracker/joomla-cms/42881</a>.</sub>

**Comment by Fedik** [comment]
Yes, it should be the same.
The changes is invisiblle for the user.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 24a4de150c7e7170926e1250d17d114c9ec50ded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42881">issues.joomla.org/tracker/joomla-cms/42881</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 24a4de150c7e7170926e1250d17d114c9ec50ded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42881">issues.joomla.org/tracker/joomla-cms/42881</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42881">issues.joomla.org/tracker/joomla-cms/42881</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and also for testing @ceford @viocassel

**Pull request merged**
