### PR TITLE
[4.0] Adding further tests for Joomla\CMS\Table\Table::bind()

### PR DESCRIPTION
**Pull request by Hackwar**
This adds further tests for Table::bind(). These tests uncovered 3 issues in that method:

1. If neither an array nor an object is given to bind, the ```onTableBeforeBind``` event throws an exception, but not the ```InvalidArgumentException``` that ```bind()``` is supposed to throw. So the check for the "validity" of the input data is pulled to the front of the method.
2. Likewise the $ignore parameter. This can be both an array or a space separated string of field names. If you use that string variant, the events throw an error of invalid input.
3. If a field is marked as JSON encoded, but the input is an object, this code will fail because it treats the object as an array.

I still have to find a way to test the events.

### CODE REVIEW

**Comment by wilsonge** [comment]
Number 3 must be an issue in staging I guess? because that's not new code for j4.

**Review by wilsonge — APPROVED** [review]

**Comment by Hackwar** [comment]
I've extended the tests, but it fails on the event testing. If someone has an idea...

**Comment by Hackwar** [comment]
Found the issue and fixed it. I also cleaned up a few things...

**Comment by wilsonge** [comment]
Yah my guess is `getTableColumns` in the db driver is bugged. Should be able to write a test there too :P

**Comment by Hackwar** [comment]
With the other PR merged, this one would then now be ready. Can you merge this one?

**Comment by Hackwar** [comment]
Or not. Now we have the same issue as in the backend template repo. So going to wait for that to be merged before we can merge this one. Giving me more time to write more tests. Maybe.

**Comment by Hackwar** [comment]
I've updated the composer stuff with just the updated database package and now the tests pass. Would be ready to merge this now.

**Comment by Hackwar** [comment]
@wilsonge since the tests are passing, could we merge this now? :-)

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
