### PR TITLE
[4.0] Fix caption for the Ordering column and ascending/descending strings

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
In list view, the caption text is wrong for the Ordering column and ascending/descending are not translated.

### Testing Instructions
Go to Global Configuration > System
Enable Debug Language.

In https://github.com/Quy/joomla-cms/blob/30c1d8ce688c9e84e6f996bb1877a9fdec23fc94/administrator/components/com_content/tmpl/articles/default.php#L110
Change `<caption class="visually-hidden">` to `<caption class="caption-top">`.

Go to Content > Articles
In Sort Table By dropdown, select Ordering ascending/descending.
In Sort Table By dropdown, select Status ascending/descending.

Apply PR.

See captions for the above.

### Actual result BEFORE applying this Pull Request
```
**Table of Articles**, **Sorted by:** **ID**,
**Table of Articles**, **Sorted by:** **ID**,

**Table of Articles**, **Sorted by:** **Status** - ascending,
**Table of Articles**, **Sorted by:** **Status** - descending, 
```

### Expected result AFTER applying this Pull Request
```
**Table of Articles**, **Sorted by:** ****Ordering** - ascending**, 
**Table of Articles**, **Sorted by:** ****Ordering** - descending**, 

**Table of Articles**, **Sorted by:** ****Status** - ascending**, 
**Table of Articles**, **Sorted by:** ****Status** - descending**, 

```

### CODE REVIEW

**Comment by brianteeman** [comment]
changes in joomla.ini should be synced to the site and api versions

**Comment by Quy** [comment]
Added. Thanks!

**Comment by brianteeman** [comment]
> changes in joomla.ini should be synced to the site and api versions

**Comment by Quy** [comment]
I don't understand. Added the new strings to both files.

**Comment by brianteeman** [comment]
there are 3 - site/admin/api

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 43dd1b8a6fb90ec8f5c2c1290b00d16f4751280d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34672">issues.joomla.org/tracker/joomla-cms/34672</a>.</sub>

**Comment by pabloarias** [comment]
I have tested this item :white_check_mark: successfully on 43dd1b8a6fb90ec8f5c2c1290b00d16f4751280d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34672">issues.joomla.org/tracker/joomla-cms/34672</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34672">issues.joomla.org/tracker/joomla-cms/34672</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
