### PR TITLE
[4.0] "tooltip" styling

### PR DESCRIPTION
**Pull request by brianteeman**
Added rounded corners and a little extra padding - to make it more consistent with the rounded corners look of the current iteration of the template

It is css so npm i or node build.js --compile-css to test

### before
image

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cf8af21f3b97d717a3a24cce9bf97c286f11b6c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28266">issues.joomla.org/tracker/joomla-cms/28266</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cf8af21f3b97d717a3a24cce9bf97c286f11b6c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28266">issues.joomla.org/tracker/joomla-cms/28266</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28266">issues.joomla.org/tracker/joomla-cms/28266</a>.</sub>

**Comment by wilsonge** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
