### PR TITLE
[4.0] Subform fixes

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Changes in `repeatable-table` subform layout:

1. Use correct `.table-responsive` wrapper.
2. Use a unique ID for the subform table.
3. Don't display the field description because it's already displayed as a tooltip in the column header.
4. Remove the implicit style of `width:45%` for `th`.

Common changes:
1. Don't pass `$subForm` param by reference in `SubformField::loadSubFormData(Form $subForm)` because it's an object.
2. Fix phpdoc in `SubformField::setup()` for undefined class `SimpleXMLElement`
3. Propagate originating field ID into subform layouts via `$fieldId`
4. Make `SubformField::loadSubFormData` protected for possible override.
4. Fixed actually displayed `.control-label.sr-only` which still consumed 240px width and broke the table-responsive behavior with screen horizontal scrolling remained.

### Testing Instructions

Show multiple subform fields on the same page, use wide forms to require responsive scroller.

### Actual result BEFORE applying this Pull Request

Duplicate table IDs, field descriptions below each field, the table is not responsive.

### Expected result AFTER applying this Pull Request

Unique table IDs, field descriptions are hidden, the table is responsive.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Denitz** [comment]
@Quy no conflicts now

**Comment by Quy** [comment]
Please fix conflicts.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 2affe23cdcf51cd15c43491e4a83ade1a8b0d922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31567">issues.joomla.org/tracker/joomla-cms/31567</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2affe23cdcf51cd15c43491e4a83ade1a8b0d922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31567">issues.joomla.org/tracker/joomla-cms/31567</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31567">issues.joomla.org/tracker/joomla-cms/31567</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
