### PR TITLE
Fix the backend logout button issue

### PR DESCRIPTION
**Pull request by prakhar3062**
Pull Request for Issue #37109

### Summary of Changes
Put the logout button outside the dropdown menu.   
### Testing Instructions

After applying the patch, see the header of home page , you  

### Actual result BEFORE applying this Pull Request
68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39363334316334343432313938626239366230323562663934356465363136322e706e67

### Expected result AFTER applying this Pull Request
Web capture_1-3-2022_153056_localhost

### Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by richard67** [comment]
@prakhar3062 Please fix the code style error reported by drone: https://ci.joomla.org/joomla/joomla-cms/52075/1/6

**Comment by brianteeman** [comment]
I'm sure you didnt mean to delete 157 files from the installation ;)

**Comment by brianteeman** [comment]
This should NOT be an override

**Comment by richard67** [comment]
It seems he made an installation on his branch and removed the installation folder at the end and then checked in the complete branch 😄

**Comment by brianteeman** [comment]
hpover

**Comment by prakhar3062** [comment]
> hpover

Oh i forgot to check by hovering over it

**Comment by prakhar3062** [comment]
> It seems he made an installation on his branch and removed the installation folder at the end and then checked in the complete branch 😄

Actually at first i commit the change in my local repo then fetch it. It may be due to it

**Comment by richard67** [comment]
@prakhar3062 You still need to revert the change for deleting all the files in the installation folder.

**Comment by richard67** [comment]
It would also be better to create a separate branch for a PR an not use the 4.1-dev branch.

**Comment by prakhar3062** [comment]
> @prakhar3062 You still need to revert the change for deleting all the files in the installation folder.

how to revert the change

**Comment by richard67** [comment]
@prakhar3062 The best would be if you make in your fork a new branch based on the 4.1-dev branch of the upstream repository (= this here) and do your changes again on that branch, and then make a new PR with that branch and close this PR here in favour of the new PR. The 4.1-dev branch in your fork you should reset to the upstream.

See here https://docs.joomla.org/Working_with_git_and_github and here https://docs.joomla.org/Git_for_Coders and .

If you use an IDE for doing the Git stuff, check the help or online documentation of that.

**Comment by chmst** [comment]
It is not an issue, but an enhancement and new function. 
There are valid comments for this RFC - you you could respect that, the result would be an extra button with an exit icon. Maybe you could try that?  Something like that ...
grafik

**Pull request closed without merging**
