### PR TITLE
[4.0] Fix markup in color field

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31339.

### Summary of Changes

Fixes markup in color field layout.

### Testing Instructions

Create a Color custom field for articles.
Edit an article.
Go to Fields tabs and inspect the color field.

### Actual result BEFORE applying this Pull Request

Color field appears as text field.

### Expected result AFTER applying this Pull Request

Color field appears as color picker.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 42942a312e98ee009c7377976d80e21fec73a497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31356">issues.joomla.org/tracker/joomla-cms/31356</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 42942a312e98ee009c7377976d80e21fec73a497<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31356">issues.joomla.org/tracker/joomla-cms/31356</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31356">issues.joomla.org/tracker/joomla-cms/31356</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
