### PR TITLE
Change new JTOOLBAR_BULK string constant name to JTOOLBAR_BULK_IMPORT

### PR DESCRIPTION
**Pull request by smz**
Not so much important, but just in case we'll ever need to use the "Bulk" string alone.
Better do it now that the new constant has not yet been "_released_", I guess.

/cc @brianteeman

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 380014b7e00c5a72e8cc612130a6e98471887855<br /><br />Makes sense, we can have other bulk process.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10028">issues.joomla.org/joomla-cms/10028</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 380014b7e00c5a72e8cc612130a6e98471887855<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10028">issues.joomla.org/joomla-cms/10028</a>.</sub>

**Comment by smz** [comment]
Thanks @andrepereiradasilva and @richard67 !

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10028">issues.joomla.org/joomla-cms/10028</a>.</sub>

**Pull request merged**
