### PR TITLE
Use base64 filter for return URL

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use base64 filter since we later run the value through `base64_decode()` and default `cmd` filter strips out certain valid base64 characters.

### Testing Instructions

Code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 38e6d2f5cae221ad058ef295142671934ac30b1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29713">issues.joomla.org/tracker/joomla-cms/29713</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 38e6d2f5cae221ad058ef295142671934ac30b1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29713">issues.joomla.org/tracker/joomla-cms/29713</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29713">issues.joomla.org/tracker/joomla-cms/29713</a>.</sub>

**Comment by richard67** [comment]
For some reason Travis status is not updated here.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
