### PR TITLE
Allow menu item separators to have labels in admin menu

### PR DESCRIPTION
**Pull request by izharaazmi**
### Summary of Changes
* Added an optional title parameter to `addSeparator()` method in backend menu class. Hence there are now two separator types:
    * Normal Separator (horizontal bar)
    * Labelled Separator

* In the preset menu, converted the separators between menus to labelled separators. This helps identify which menu are site menus and which are administrator menus.
* This labelled separators can also be used in the new custom backend menu by simply providing a label to the separator type menu item.

### Testing Instructions
* Install current staging and navigate to backend and see the drop down menu.which should look like

menu

* Add a custom administrator menu and set it as active backend menu.
* Add some items, separators with title and separators without title in custom backend menu
* Match your findings with expected results below.
* If there is no admin menu,the separator should also be hidden automatically.
* Test this on RTL layout also.

### Expected result
* The separators with title should appear as labelled separators whereas the separator without title should be displayed as normal separator.
* The separators should not be clickable

### Documentation Changes Required
Backend menu manager documentation should be updated.

@infograf768 @brianteeman

### CODE REVIEW

**Comment by C-Lodder** [comment]
Can you please make styling changes in the correct LESS file and compile it

**Comment by izharaazmi** [comment]
Sorry, I've no idea how to do that. Please advise.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 67c3cb495a319028f6437a26f0a8b4f151cd5204<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15002">issues.joomla.org/tracker/joomla-cms/15002</a>.</sub>

**Comment by C-Lodder** [comment]
The LESS files are in the template directory. To compile, you're going to need to open up your terminal, `cd` to the Joomla root, and run `php build/generatecss.php`.

**Comment by brianteeman** [comment]
to expand on what @C-Lodder said

You should never edit any css file. Just edit the relevant less files and then run the generate command as @C-Lodder said and then this will generate the relevant css files as well

**Comment by izharaazmi** [comment]
Thanks. I was trying to use PHPStorm LESS Watcher for no avail. It
displayed so many errors. Didn't know there was a script for that. Doing it
now.

**Comment by franz-wohlkoenig** [comment]
Appended `Menu Heading` and `Text Separator` to Costum Menu, none of them is showen.

**Comment by C-Lodder** [comment]
again, could you please **remove** the asterisk from your CSS.
```
*width: 100%;
^
*margin: -5px 0 5px;
^
```

**Comment by izharaazmi** [comment]
@franz-wohlkoenig Separators at beginning or end or immediately after another separator - are never shown.

@C-Lodder Those are already there in the divider less definition, I thing for IE only rule. See `administrator/templates/isis/less/bootstrap/mixins.less:502`

I recommend we have a test on IE too.

**Comment by C-Lodder** [comment]
@izharaazmi - we don't support IE7

**Comment by franz-wohlkoenig** [comment]
@izharaazmi please have a look:

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a4baa3af9e7cd5fd512913feac9fdc73deba1efc<br /><br />`System Links` > `Text Separator` with Text or `-` in Title-Field works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15002">issues.joomla.org/tracker/joomla-cms/15002</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Changed from Separator using `-` in Title to `Name` in Title no Name is shown. Looks like Cache but had cleared Browser-Cache.

**Comment by izharaazmi** [comment]
@franz-wohlkoenig You need to use separator type instead of heading.

I tested changing title from - to text and also the other way around. All looks fine here.

**Comment by franz-wohlkoenig** [comment]
@brianteeman can you please retest?

**Comment by joomlara** [comment]
I have tested this item :white_check_mark: successfully on a4baa3af9e7cd5fd512913feac9fdc73deba1efc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15002">issues.joomla.org/tracker/joomla-cms/15002</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Comment by insitevision** [comment]
I have tested this item :white_check_mark: successfully on a4baa3af9e7cd5fd512913feac9fdc73deba1efc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15002">issues.joomla.org/tracker/joomla-cms/15002</a>.</sub>

**Comment by ZoFx** [comment]
After updating to 3.7 I desperately tried to create unnamed separators in a custom backend menu. Only here on Github I found I could achieve this by naming it with a single hyphen (-). In my opinion, this is not at all intuitive. How are users supposed to know that?

What's more when named with a single hyphen, the menu item is quite hard to click in the menu item list. Of course I can select the item and use the "edit" button, but who the heck actually does it this way?

I think it would be far more elegant to have a "Use title as separator label" property. And this should be switched off by default, which would be more the default behaviour of a "separator" imho.

**Comment by brianteeman** [comment]
@ZoFx commenting on a closed issue will not be seen - please create a new issue

**Comment by ZoFx** [comment]
I will, thanks.

**Pull request merged**
