### PR TITLE
Articles Category List. Not possible to hide headline *Subcategories*

### PR DESCRIPTION
**Pull request by ghost**
Test instructions:
- Create menu item Articles » Category List
- Select a category with subcategories.
- Set option Category >  _Show Subcategories Text_ to **Hide**. Save.
- Frontend. Load menu item.
- No reaction. Headline shown
  subcats1
- Apply patch.
- Reload frontend. Success.

### CODE REVIEW

**Comment by jwaisner** [comment]
@test 

Patch corrects error with showing subcatagory when set to HIDE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7034">issues.joomla.org/joomla-cms/7034</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@test works to hide Subcategories Text.

**Comment by zero-24** [comment]
Thanks for testing :smile: RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7034">issues.joomla.org/joomla-cms/7034</a>.</sub>

**Comment by brianteeman** [comment]
Oops too late but 
Issue observed and resolved with this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7034">issues.joomla.org/joomla-cms/7034</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman you know every test is a good test :smile: Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7034">issues.joomla.org/joomla-cms/7034</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Merged. Thank you @bertmert!

**Pull request closed without merging**
