### PR TITLE
[4.0] Action Logs export

### PR DESCRIPTION
**Pull request by brianteeman**
This PR makes the column headings of the exported action logs match the column headings as presented on the web

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 164e9fd0f607a0306a4f47a57ad9fdc1682b19fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26803">issues.joomla.org/tracker/joomla-cms/26803</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 164e9fd0f607a0306a4f47a57ad9fdc1682b19fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26803">issues.joomla.org/tracker/joomla-cms/26803</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26803">issues.joomla.org/tracker/joomla-cms/26803</a>.</sub>

**Comment by mbabker** [comment]
While this is fine in practice, it should be noted in the B/C breaks list because if anyone has any kind of automated tooling expecting the CSV headers in the current format then that will need to be updated (and I say this as someone who writes a fair amount of CSV related export/import tooling (not for this specific feature though) and has code expecting headers in specific formats).  The odds of it are pretty much 0 but still figured I'd point it out.

**Comment by wilsonge** [comment]
This looks fine - just wondering for something designed to be parsed whether IP Address with the space is ideal because of all the fun parsing spaces. In theory because it's a file and we're exploding over comma's should be fine I guess?

**Comment by brianteeman** [comment]
As it is following the standards for a csv file it should be fine

**Comment by wilsonge** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
