### PR TITLE
[SQL errors] When installing languages (backend/installation) in PDO Strict mode/Sql Azure

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9457 and new issue (in MSSQL).
### Summary of Changes

This solves languages (and probably other extensions) install problems in MSSQL and "PDO (MySQL)" in strict mode.
### Testing Instructions
- For "PDO (MySQL)" see https://github.com/joomla/joomla-cms/issues/9457
-  For "MSSQL" try to install languages on install or after install before patch (don't work), after patch (should work).
- Test also upgrade process.
- Code review.
### Documentation Changes Required

None.

@alikon @waader since you are the db experts please check and review.

### CODE REVIEW

**Comment by waader** [comment]
I have not tested this item.<br /><br />- I applied your patch
- made a fresh installation with mysql_pdo
- added 
  $this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
  in line 155 of the pdo-mysqldriver (although I am using mysql 5.6.28)
- and got the following error when I went to extensions > manage > install languages
  SQLSTATE[HY000]: General error: 1364 Field 'data' doesn't have a default value 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by andrepereiradasilva** [comment]
hum, so it seems we have another data columns without default value ...
i bet is this one https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1765

**Comment by alikon** [comment]
@waader  i can confirm your findings on pdo but i'm quite sure is the same mssql

@andrepereiradasilva you have opend a "Pandora's box" (pdo-mysql + mssql) 

and yes your bet is winning 

i'm still testing on pdo but for me the schema  should be something like this:
data1

plus
data2

in this way i'm able to go a little forward ...
....now i'm stuck on asset_id

data3

....

**Comment by andrepereiradasilva** [comment]
ok so the data column should be fixed now.

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva you have opend a "Pandora's box" (pdo-mysql + mssql)

i have that strange habit :wink: 

But, IMO this PDO strict mode is a good thing because it makes all databases work in samiliar way.
IMO 4.0 should only accept strict mode.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 2f708441cc9a3d9dc8da14ad7becb1b51cb54b9c<br /><br />Now works for pdo_mysql and mssql. After login to the mssql instance there is another error showing up but that´s another story.

One suggestion: It would be nice to see the sqlmode in systemsinformation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by alikon** [comment]
@waader did you test installing a fresh new site with multilingual enabled
and with at least 2 languages ?

On 24 Aug 2016 11:02 am, "waader" <notifications@github.com> wrote:

I have tested this item ✅ successfully on 2f70844
<https://github.com/joomla/joomla-cms/commit/2f708441cc9a3d9dc8da14ad7becb1b51cb54b9c>

Now works for pdo_mysql and mssql. After login to the mssql instance there
is another error showing up but that´s another story.

One suggestion: It would be nice to see the sqlmode in systemsinformation.
------------------------------
This comment was created with the J!Tracker Application
<https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/11763
<https://issues.joomla.org/tracker/joomla-cms/11763>.

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/pull/11763#issuecomment-242000917>,
or mute the thread

**Comment by zero-24** [comment]
@waader how we get the sqlmode?

**Comment by andrepereiradasilva** [comment]
@zero-24 For "PDO (MySQL)" see https://github.com/joomla/joomla-cms/issues/9457

**Comment by andrepereiradasilva** [comment]
@alikon i tested by manually performing the alter in mysql PDO strict mode and them installing the language in the backend.

I will test install too when i have time.

**Comment by andrepereiradasilva** [comment]
BTW just notice that if you enable the finder plugins you can't even save content in PDO Mysql Strict Mode! But that is not for this PR.
image

image

Pandora's box ...

We really need a db expert checking all this PDO MySql Strict things.

**Comment by alikon** [comment]
Are you ready to start an autumn of code ?

**Comment by andrepereiradasilva** [comment]
> Are you ready to start an autumn of code ?

ehhehe. Not me, i'm no DB expert, but this IMO should be solved for to 4.0
Joomla is bypassing the strict mode (MySql 5.6.6+ default) because of lack of consistency in joomla DB.

**Comment by zero-24** [comment]
Maybe we should add a comment to the hack in the driver?

**Comment by waader** [comment]
@alikon Yep, with three languages.

**Comment by andrepereiradasilva** [comment]
@alikon can you confirm it works now?

**Comment by alikon** [comment]
If you install languages  when install a fresh site don't work on pdo
strict mode... I'm working on a pr that solve the issue you reported about
finder plugin enabled too... I'll update you asap...

**Comment by andrepereiradasilva** [comment]
ok should work now

**Comment by alikon** [comment]
still don't work on pdo strict-mode 10.1.8-MariaDB in this way
pdostrictmode1

did you miss my previous comment https://github.com/joomla/joomla-cms/pull/11763#issuecomment-241851512 ?

i've submitted a fix to your branch https://github.com/andrepereiradasilva/joomla-cms/pull/67

**Comment by andrepereiradasilva** [comment]
@alikon did you teste the latest version?
I already solved that: https://github.com/joomla/joomla-cms/pull/11763/files#diff-135c6f58583408312a709459b19594c7R1765

**Comment by alikon** [comment]
I think so, but I'll double check

**Comment by alikon** [comment]
i followed this path

- downloaded the latest staging 
- installed with mysql no pdo
- installed the com_patchtesterr (just in case i've not patchted correctly manually)
- applyed PR #11763 with the last changes (as  it is now)
- dropped all tables in the database
- deleted the configuration.php
- added the strict mode to pdomysql.php at line 155

```php
//$this->connection->query("SET @@SESSION.sql_mode = '';");
$this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
```

- double checked that all changes in the PR #11763 are correctly in place
- started a new installation with mysql pdo strict mode as a database
- select the no data for basic multiligual install
- double check that PR are corretclty  applyied as db schema on changed tables checked with phpmyadmin
- click on extra step install languages
-  got the sql error

strictpdo

this is what phpmyadmin report about DB
conf


if i repeat the same step but with andrepereiradasilva#67 applyied   installation with multilgual enabled + 4 languages content menus etc goes OK

p.s. 
PDO sould be considered as a different DB .... what is valid for other's DB is not valid with PDO
so this PR  should be diveived in two parts one for MYSQL PDO (STRICT MODE) and one for MSSQL

**Comment by andrepereiradasilva** [comment]
don't understand repeated the exact same steps you did and don't have any issue!

image

**Comment by andrepereiradasilva** [comment]
could it be the mariadb version ?

**Comment by alikon** [comment]
andrè
it could be, but really is quite odd, what is your php version ?
+ can you try mine, just to have a wide spectrum of tests...

**Comment by andrepereiradasilva** [comment]
7.0.8

**Comment by andrepereiradasilva** [comment]
i suspect your error is other data column (session table?)

**Comment by alikon** [comment]
like someone we both knows is used to say .... hmmm ;)

**Comment by andrepereiradasilva** [comment]
i mean how can youhave a `data` has no default value error if the column clearly it as now a default value ...
```sql
`data` text NOT NULL DEFAULT '',
```

**Comment by alikon** [comment]
maybe i've overlooked at the xml language files from the update site they don't have a data field
long debug session is needed....

**Comment by alikon** [comment]
i've digged more on this issue, here is what happens  on my environment when i click on extra step install languages
pre

as you may notice the field `data` is not present in the INSERT field list
 nor is present  in the xml 

```xml
<extension name="Armenian" element="pkg_hy-AM" type="package" version="3.4.4.1" detailsurl="https://update.joomla.org/language/details3/hy-AM_details.xml"/>
```

so why that field should have the NOT NULL constraint ?

**Comment by andrepereiradasilva** [comment]
Don't know. But the not null is on the 3 db systems

**Comment by alikon** [comment]
tested successfully on mysql pdo strict mode and postgresql with php 5.5
@waader  can you re-test on MSSQL

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6e11d4148c20435cf6a42a97c746e55edf3dd09b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 6e11d4148c20435cf6a42a97c746e55edf3dd09b<br /><br />Works with mssql! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman sorry please remove RTC until @alikon confirm this.

**Comment by zero-24** [comment]
Done :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by brianteeman** [comment]
The @zero-24 robot was faster<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by zero-24** [comment]
Hehe :)

**Comment by alikon** [comment]
>  i notice now you changed the update libraries in your PR (that was merged in this), did you test the extension updates work fine after that?

@andrepereiradasilva   extension updates doesn't not work  with PDO strict mode even without that change, i've made a fix for this scenario , see https://github.com/andrepereiradasilva/joomla-cms/pull/76 now you should be able to upgrade extensions, tested with com_patchtester and weblinks

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I misread that comment

**Comment by brianteeman** [comment]
Remove RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11763">issues.joomla.org/joomla-cms/11763</a>.</sub>

**Comment by alikon** [comment]
@andrepereiradasilva  can you evaluate my last one ...

**Comment by zero-24** [comment]
Closing as there is a new PR to fix it https://github.com/joomla/joomla-cms/issues/14321

**Pull request closed without merging**
