### PR TITLE
Microdata implementation in the CMS with the use of plg_system_microdata and JMicrodata

### PR DESCRIPTION
**Pull request by alexprut**
This pull request includes the `plg_system_microdata` plugin https://github.com/joomla/joomla-cms/pull/4118 pull request.
## THINGS DISCUSSED

1) Where is saved the com_content microdata information.
Discussion link: https://twitter.com/PAlexcom/status/513414081534263297
microdata-database
## HOW TO TEST

First I recommend reading this article http://magazine.joomla.org/issues/issue-aug-2014/item/2233-rich-snippets-structured-data-microdata-rdfa-isnt-so-simple

Also make sure you have the `plg_content_vote` and `plg_system_microdata` both enabled.

You will also need this tool provided by google to test the markup and the SERP (Search Engine Result Page) preview https://www.google.com/webmasters/tools/richsnippets

Not necessary, but you could also validate the HTML by using this tool http://validator.w3.org
## Step by step
1. Go in the Administration area, then from the top menu select: _Content → Article Manager_
2. Now select and press _Edit_ on any article
3. From the option tab select: _Publishing_ administration - article manager edit article
4. At the bottom right of the page you should find: administration - article manager edit article microdata
## Previews and results

At this point you can change one of the 5 available microdata schema.org types.
##### Backend configuration:

admin - administration - article manager edit article microdata-article
##### Preview of the rich snippet in the SERP of Google:

google structured data testing tool article
##### Backend configuration:

administration - article manager edit article event
##### Frontend output:

beginners frontend event
##### Preview of the rich snippet in the SERP of Google:

google structured data testing tool event
##### Backend configuration:

administration - article manager edit article product
##### Preview of the rich snippet in the SERP of Google:

google structured data testing tool product
##### Backend configuration:

administration - article manager edit article recipe
##### Frontend output:

beginners frontend recipe
##### Preview of the rich snippet in the SERP of Google:

google structured data testing tool recipe
##### Backend configuration:

administration - article manager edit article review
##### Preview of the rich snippet in the SERP of Google:

google structured data testing tool review

---

For more information on how everything is implemented and the syntax please read here https://github.com/joomla/joomla-cms/pull/4118

### CODE REVIEW

**Comment by AlexdeBorba** [comment]
On frontend templates, while using this patch, the keywords display on template become misplaced, and forced to vertical align display instead of horizontal as set on most templates.

screenshot-www atmostfear-entertainment com 2015-01-25 23-21-06

**Comment by AlexdeBorba** [comment]
Missing is Local, Person, Audio and Video, which is quite handy for news publishing websites, such as online magazines.

Product does not load fields to fill, such as UPC and ISBN which is quite handy.

**Comment by waader** [comment]
As I read about a new validation service for microdata today I came back to your patch and analyzed the problem raised by @roland-d. 

Two side notes:
- This patch is out of sync with current staging and needs a little "tweaking" before it could be installed with the current staging branch. Just apply your patch and take the current joomla.sql as there was a schema change in the meantime.
- I only saw today that there a two more patches #4108 and #4118 and I wonder why that is as it seems that they are included in this patch.

So I installed the tweaked current staging branch including your patch with the testing sample data, activated the plugin and took the first article - popular tags - and selected event as microdata type.

After that I validated the result with the service available at http://www.w3.org/blog/SW/2012/02/08/new-w3c-validation-service-with-rdfa-1-1-and-microdata/. There are two problems indicated:

One that is unrelated to the microdata extension: In the article "popular tags" - also in many others - there is the line

`<p>{loadmodule tags_popular,Popular Tags}</p>`

which makes the validator scream because after rendering you will have a `<p>` tag that encloses a lot of `<div>` tags. Changing this `<p>` to `<div>` and everything is fine.

Then there is the line
`<meta  content="UserPageVisits:5" />`

The first thing I noticed are the two empty space between meta and content. So I looked in the corresponding layout file and found this line:
`<meta data-sd="interactionCount" content="UserPageVisits:<?php echo $displayData['item']->hits; ?>" />`

So why is data-sd="interactionCount" parsed out?

Last but not least I had a look at a google service at https://developers.google.com/structured-data/testing-tool/ that evaluates structured data markup. There I get to 2 errors and 1 warning. Googles is complaining that the field "address" is missing and the field "location" has to be filled. It also recommends to add the field "offer".

joomla_microdata

**Comment by designbengel** [comment]
Is this function to be extended in the future? I miss some fields in the microdata function. Like SoftwareApplication, Movie, Book, Person, Organisation, and many more ... ? 
I just wonder if it´s suffices to everyones needs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4276">issues.joomla.org/joomla-cms/4276</a>.</sub>

**Comment by roland-d** [comment]
Hello @PAlexcom

Thank you for your contribution.

The last comment here was on 14th March. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4276">issues.joomla.org/joomla-cms/4276</a>.</sub>

**Comment by PAlexcom** [comment]
Hello @roland-d, this PR isn't valid and outdated, can be closed.

**Comment by Bakual** [comment]
Closed as requested

**Pull request closed without merging**
