### PR TITLE
[4.0] External link in installation message (a11y)

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #33931

See #33931 for a description

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 45703f0f5a5b69920fe7a029cba561449bd86925<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33933">issues.joomla.org/tracker/joomla-cms/33933</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 45703f0f5a5b69920fe7a029cba561449bd86925<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33933">issues.joomla.org/tracker/joomla-cms/33933</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33933">issues.joomla.org/tracker/joomla-cms/33933</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
