### PR TITLE
[4.1] com_privacy site router is not working

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Implement router service in privacy component

### Testing Instructions

Create a menu link eg for _Privacy » Create Request_ (alias: _privacy-request_)

### Actual result BEFORE applying this Pull Request

Link of menu item: `/index.php/privacy-request?view=request`

### Expected result AFTER applying this Pull Request

Link of menu item: `/index.php/privacy-request`

### Documentation Changes Required

none

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on f14f8fda78f7bbc7f4ad3b64e7287431796a3de2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37602">issues.joomla.org/tracker/joomla-cms/37602</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on f14f8fda78f7bbc7f4ad3b64e7287431796a3de2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37602">issues.joomla.org/tracker/joomla-cms/37602</a>.</sub>

**Comment by chmst** [comment]
Thank you @kiki-G for testing! The PR needs a second test from another person to be RTC.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on f14f8fda78f7bbc7f4ad3b64e7287431796a3de2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37602">issues.joomla.org/tracker/joomla-cms/37602</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37602">issues.joomla.org/tracker/joomla-cms/37602</a>.</sub>

**Comment by richard67** [comment]
Setting again RTC in the issue tracker because that doesn't have it yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37602">issues.joomla.org/tracker/joomla-cms/37602</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
