### PR TITLE
com_installer: translatable ordering in manage and updatesites views

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR intents to solve the issue in two views of com_installer where ordering of some columns in some views (manage and updatesites) are not correct when using other languages that not english.
#### How to test
1. Use latest staging
2. Install, for instance, german language and set it as default admin
3. Go to Erweiterungen -> Verwalten -> Manage (Extensions -> Manage -> Manage in english)
4. Now order by "Typ" (Type), you will see that is not ordered correctly.
5. Install this patch.
6. Repeat steps 3 and 4. You will see is ordered correctly now.
7. Do the similar process for Erweiterungen -> Verwalten -> Update Sites (Extensions -> Manage -> Update Sites in english)
8. Test also the search, other ordering, pagination and filters in those two views and check everything is fine.

It would be nice to check other languages to. I tried also pt-PT and works fine.

@richard67 here is the last PR for the translate ordering problem in com_install.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on db0494b25365c6f6241f7031fb4d08fa86a7182f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9139">issues.joomla.org/joomla-cms/9139</a>.</sub>

**Comment by renekorss** [comment]
I have tested this item :white_check_mark: successfully on db0494b25365c6f6241f7031fb4d08fa86a7182f<br /><br />Tested with et-EE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9139">issues.joomla.org/joomla-cms/9139</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9139">issues.joomla.org/joomla-cms/9139</a>.</sub>

**Comment by wilsonge** [comment]
We need to fix the conflicts here :)

**Comment by richard67** [comment]
@andrepereiradasilva I can test again in some 2 to 3 hours, have to do something else before.

**Comment by andrepereiradasilva** [comment]
sure, no problem.

**Comment by renekorss** [comment]
I have tested this item :white_check_mark: successfully on b3b50c9bac6c2e7eb3868c0e0a4ed62761f85289<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9139">issues.joomla.org/joomla-cms/9139</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b3b50c9bac6c2e7eb3868c0e0a4ed62761f85289<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9139">issues.joomla.org/joomla-cms/9139</a>.</sub>

**Pull request merged**
