### PR TITLE
[4.0] Testing gmp.dll added to appveyor

### PR DESCRIPTION
**Pull request by rdeutz**
### Summary of Changes
Adding the php_gmp.dll package for appveyor testing. This is needed for https://github.com/joomla/joomla-cms/pull/28094

### Testing Instructions
Can only be tested with #28094 

### Expected result
no failure atcomposer install

### CODE REVIEW

**Comment by HLeithner** [comment]
@rdeutz this pr seams to fail in appveyor 
```
copy : Cannot find path 'C:\projects\joomla-cms\build\test-stuff\gmp.dll' because it does not exist.
At line:14 char:5
+     copy C:\projects\joomla-cms\build\test-stuff\gmp.dll c:\tools\php ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\projects\joo...t-stuff\gmp.dll:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
 ```

**Comment by rdeutz** [comment]
@HLeithner did you looked at the test here in the PR, it passed?

**Comment by HLeithner** [comment]
My comment is a copy-paste from the successful test ;)

**Comment by HLeithner** [comment]
image

@rdeutz this is on both PHP Versions

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
