### PR TITLE
[plugin][system][actionlog] use namespaced class

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
use namespaced class

### Testing Instructions
code review
or action log work as before

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab67f90de4a57a027811d70792059a5cd37442f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23335">issues.joomla.org/tracker/joomla-cms/23335</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ab67f90de4a57a027811d70792059a5cd37442f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23335">issues.joomla.org/tracker/joomla-cms/23335</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23335">issues.joomla.org/tracker/joomla-cms/23335</a>.</sub>

**Comment by mbabker** [comment]
Merge conflicts...

**Comment by sandewt** [comment]
Hi @alikon,

I looked at the code, and have a suggestion.

```
class PlgSystemActionLogs extends JPlugin
{
```
Could be:

```
use Joomla\CMS\Plugin\CMSPlugin;
...
class PlgSystemActionLogs extends CMSPlugin
{
```
Also apply to issue #23349 and #23350
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23335">issues.joomla.org/tracker/joomla-cms/23335</a>.</sub>

**Pull request merged**
