### PR TITLE
Fixes php 8.1 strtoupper deprecation error in patch tester

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
Removes the warning 
``` Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\src\MVC\Model\ListModel.php on line 543 ``` that shows up in patch_tester 4.2.1 when using php 8.1+

### Testing Instructions

install https://github.com/joomla-extensions/patchtester/releases/tag/4.2.1
when you open it you will see the error at the top of the page.
enter your credentials and apply this patch.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on ed1e20e9a81525d64ad7d896db9f0850ba69ed1d<br /><br />Tested successfully in Joomla 4.2.4-dev of 30 September using PHP 8.1.9 in Wampserver 3.2.9.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38917">issues.joomla.org/tracker/joomla-cms/38917</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ed1e20e9a81525d64ad7d896db9f0850ba69ed1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38917">issues.joomla.org/tracker/joomla-cms/38917</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38917">issues.joomla.org/tracker/joomla-cms/38917</a>.</sub>

**Review by HLeithner — CHANGES_REQUESTED** [review]
We don't use `?? ''` to fix php warnings, there is actually a reason why it's not a `string` and in this case `NULL`, if it's really expected that the direction value is `NULL` we should find the root cause, and create an `if` statement before `if in_array` query.

**Comment by richard67** [comment]
Back to pending status.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38917">issues.joomla.org/tracker/joomla-cms/38917</a>.</sub>

**Comment by N6REJ** [comment]
> We don't use `?? ''` to fix php warnings, there is actually a reason why it's not a `string` and in this case `NULL`, if it's really expected that the direction value is `NULL` we should find the root cause, and create an `if` statement before `if in_array` query.

you want to create a pr then.  Thats not something I'm capable of doing.

**Pull request closed without merging**
