### PR TITLE
[4.0] Cleanup content/banner toolbar code

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This is just a code cleaning of the toolbar button calls to be aligned to the other calls

### Testing Instructions
Open content/banner list view in backend and test all toolbar buttons

### Expected result
Should work as before

### CODE REVIEW

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 3c24b447debaa2b689157d6d7e3d2b2a4e9ec014<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23369">issues.joomla.org/tracker/joomla-cms/23369</a>.</sub>

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on ceb5b70e23d04c4853b0dc12b572f397926140d0<br /><br />on Joomla! 4.0.0-alpha7-dev

OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23369">issues.joomla.org/tracker/joomla-cms/23369</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23369">issues.joomla.org/tracker/joomla-cms/23369</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
