### PR TITLE
[4.0] Reset workflow when changing the category

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #21973 .

### Summary of Changes
Resets the workflow, when the category is changed and a new workflow applied

### Testing Instructions
- Create 2 workflows and assign them to 2 different categories
- Create an article for category 1
- Execute transitions
- Change the category

- Do the same with the batch => move

### Expected result
if category is changed and they have different workflows the new workflow is assigned

### CODE REVIEW

**Comment by brianteeman** [comment]
I was concerned that when you changed the category what would happen to the stage/transition/condition of the item if the new workflow had different stage/transition/condition. 

I didn't get as far as testing that because if you change the category then the stage/transition/condition changes to the default one.

To test this yourself create two identical workflow and assign each to a category

Create an article in category 1 and change the state to unpublished
Then change the category of the article to category 2 and it will be automatically published (the default of the new workflow)

I know that this PR says it "resets" the workflow so in that case it could be said to be correct as it does what you say but without any notification in joomla itself it is definitely never going to be expected that changing the category of an article could publish it.

Sorry but I don't have any suggestion as I cannot see a way around this other than only having one workflow enabled per site 



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22180">issues.joomla.org/tracker/joomla-cms/22180</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 3b5027714e1f6e1dee3505db44219d6b453aa831<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22180">issues.joomla.org/tracker/joomla-cms/22180</a>.</sub>

**Comment by brianteeman** [comment]
I am at a drupal sprint and just checked how their workflow stuff works specifically the multiple workflows.

Drupal does allow multiple workflows on the site but you can only have one workflow for each content-type. There is no way to change a workflow based on taxonomy which in our terms means one workflow per component. /cc @wilsonge

**Comment by wilsonge** [comment]
So you're suggesting that we shouldn't allow changing of workflows in a given category?

**Comment by brianteeman** [comment]
I am saying more than that - there should only be one workflow per component

**Comment by bembelimen** [comment]
I still think, that changing a category should not change the workflow, but I also think, that Joomla! shouldn't limit itself in terms of the number of workflows, just because Drupal does it... because Joomla! can  handle unlimited workflows per component...

**Comment by brianteeman** [comment]
My point as shown by examples above is that we are not able to have multiple workflows per component that actually work

**Comment by csthomas** [comment]
> I still think, that changing a category should not change the workflow...

Me too. The approver may want to move the article to a more appropriate category or subcategory not visible by author.

**Comment by brianteeman** [comment]
Thats the entire point. If you move content then you expect it to work the same as everything else in the category. Remember that you could have  a stage called X than has condition Y in category 1 but a stage called X with a condition Z in the new category. How can you tell the difference

**Pull request closed without merging**
