### PR TITLE
Custom Field repeatable icons

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the work to ensure that all uses of font icons are accessible and following the advice of Font Awesome (http://fontawesome.io/accessibility/) this PR ensures that the interactive icons used in repeatable forms as shown in the screenshot have both an aria-label on the link and aria-hidden on the icon.

screenshotr09-37-12

### CODE REVIEW

**Comment by brianteeman** [comment]
Corrected the screenshot to 
screenshotr09-37-12

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a7470b885f9f5b1fa10b3bd0448fe6885e16f2df<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18444">issues.joomla.org/tracker/joomla-cms/18444</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a7470b885f9f5b1fa10b3bd0448fe6885e16f2df<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18444">issues.joomla.org/tracker/joomla-cms/18444</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
