### PR TITLE
Fix logical ordering of access levels

### PR DESCRIPTION
**Pull request by cyrez**
This PR relates to @brianteeman PR #5834

On fresh install, set a logical ordering of pre-defined access levels.

In com_users access levels view, list is order by ordering ASC.
This way, the ordering is the same by default in Access Levels view, in Access filter  and select field.

Ref : https://github.com/joomla/joomla-cms/issues/5834

### CODE REVIEW

**Comment by brianteeman** [comment]
Awesome - Do you think it should be 
Public 0
Guest 1

You currently have it the otherway around<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5899">issues.joomla.org/joomla-cms/5899</a>.</sub>

**Comment by JoomliC** [comment]
<blockquote>
Do you think it should be
Public 0
Guest 1
</blockquote>

Oh yes you're right. Edited! ;-)

**Comment by brianteeman** [comment]
Awesome - thanks

On 28 January 2015 at 16:55, Cyril Rezé <notifications@github.com> wrote:

> Do you think it should be Public 0 Guest 1
>
> Oh yes you're right. Edited! ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5899#issuecomment-71870858>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
With this change how does the ordering look for existing sites. Is it now completely random?

**Comment by JoomliC** [comment]
<blockquote>
With this change how does the ordering look for existing sites. Is it now completely random?
</blockquote>
There will be no change in filter and access type dropdown. (as order by ordering ASC first, and after ordering by Title ASC).
So, for someone how has never changed ordering of access levels, it will change only in access levels view.
But, if someone has already changed ordering of access levels, to have the order he wanted in the filter or access field input, it won't change nothing! (this is why ordering should not be updated for already existing sites, to prevent to break user own ordering).

So, the only change in Access levels view, will be for someone who has never changed access ordering.
In all cases, no changes after update for already existing sites in filter and access type field.

And it was before completely random where we really select access : filter and access type field. ;-)

To keep order in access levels after update, is it possible to add a second ordering to parent::populateState ?

**Comment by waader** [comment]
Work with mysql, postgresql, mssql except when you install with the following data:
- mysql: sample_learn.sql
- postgresql: sample_learn.sql
- mssql: sample_learn.sql and sample_testing.sql

**Comment by JoomliC** [comment]
@waader Thank you! :+1: 
I didn't think of samples...

I have added ordering, but just a question about 'Customer Access Level (Example)' order.
I have ordering like this : 
<pre>
0 Public
1 Guest
2 Registered
3 Customer Access Level (Example)
4 Special
5 Super Users
</pre>

Before, Customer Access Level was ordered after Special... was it an error ? Seems to me more logicial if Special is after Customer Access Level (Example)... ?

Cyril

**Comment by brianteeman** [comment]
Looks good to me

On 29 January 2015 at 12:08, Cyril Rezé <notifications@github.com> wrote:

> @waader <https://github.com/waader> Thank you! [image: :+1:]
> I didn't think of samples...
>
> I have added ordering, but just a question about 'Customer Access Level
> (Example)' order.
> I have ordering like this :
>
> 0 Public
> 1 Guest
> 2 Registered
> 3 Customer Access Level (Example)
> 4 Special
> 5 Super Users
>
> Before, Customer Access Level was ordered after Special... was it an error
> ? Seems to me more logicial if Special is after Customer Access Level
> (Example)... ?
>
> Cyril
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5899#issuecomment-72014053>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
:+1: @test ok (mysql)

**Comment by waader** [comment]
@test works for mysql, postgresql, mssql! Thanks!

**Comment by brianteeman** [comment]
Multiple tests RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5899">issues.joomla.org/joomla-cms/5899</a>.</sub>

**Pull request closed without merging**
