### PR TITLE
Issue #26708 fix: Category Icon & Author Icon Missing from Article

### PR DESCRIPTION
**Pull request by flavia-b**
Pull Request for Issue #26708 .

### Testing Instructions
Please check this URL for more details
https://www.screencast.com/t/p1sZRsZ8p4Q

### Expected Result
article-blog

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 51cec0438c9564a3c7ea56e1a7e5f2db8d580b27 
#pbf19 #test1
<hr />
<sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26943">issues.joomla.org/tracker/joomla-cms/26943</a>.</sub>

**Comment by mangeshmane** [comment]
I have tested this item :white_check_mark: successfully on 51cec0438c9564a3c7ea56e1a7e5f2db8d580b27<br /><br />#pbf19 #test2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26943">issues.joomla.org/tracker/joomla-cms/26943</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26943">issues.joomla.org/tracker/joomla-cms/26943</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
