### PR TITLE
Logical error in the com_tags controller

### PR DESCRIPTION
**Pull request by philip-sorokin**
Logical error?

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
seems like it

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 3432be8d3fe604f87c2aca9867602002a9183fc6<br /><br />It just fixes a logical error. Thanks and good spot :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10702">issues.joomla.org/joomla-cms/10702</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3432be8d3fe604f87c2aca9867602002a9183fc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10702">issues.joomla.org/joomla-cms/10702</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10702">issues.joomla.org/joomla-cms/10702</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
