### PR TITLE
Adds catid to JRoute, for subcategories in com_contact menus with modern routing #29213

### PR DESCRIPTION
**Pull request by webgras**
Pull Request for Issue #29213 .

### Summary of Changes
solves routing problem.

### Testing Instructions
see issue #29213

### Expected result
see issue #29213

### Actual result
see issue #29213

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 02f609a511987158f7897af85e25533fa25af8ae<br /><br />Sigrid: Hope you got the Mail :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29234">issues.joomla.org/tracker/joomla-cms/29234</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 02f609a511987158f7897af85e25533fa25af8ae<br /><br />Looks fine on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29234">issues.joomla.org/tracker/joomla-cms/29234</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29234">issues.joomla.org/tracker/joomla-cms/29234</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
