### PR TITLE
[4.0] remove 3.8.x sql update scripts

### PR DESCRIPTION
**Pull request by alikon**
follw-up discussion https://github.com/joomla/joomla-cms/pull/26297#issuecomment-531864131

### Summary of Changes

removed 3.8.x sql update scripts

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c8e04b6da8e4689e4a62d1a2ed06733e2c51b77f<br /><br />Code review: Checked that this PR covers all the 3.8 update sql scripts for mysql and postgresql.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26344">issues.joomla.org/tracker/joomla-cms/26344</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c8e04b6da8e4689e4a62d1a2ed06733e2c51b77f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26344">issues.joomla.org/tracker/joomla-cms/26344</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26344">issues.joomla.org/tracker/joomla-cms/26344</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
