### PR TITLE
[4.0] Remove deprecated functions isSite and isAdmin

### PR DESCRIPTION
**Pull request by laoneo**
~Target isClient and isAdmin for version 5.0.~

Removes the deprecated functions isAdmin and isSite. See comments below for more information.

### CODE REVIEW

**Comment by wilsonge** [comment]
Unsure whether this is a good idea. We have a permanent 3rd application type (in the console App https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/ConsoleApplication.php )

And the API app will be a type 4 when it gets introduced which will definitely be in the 4.x series (maybe 4.0 if i put the base app code in without the base extension classes)... So this method is going to behave differently in j4 to j3 :/

i.e. what i'm saying is because we have more application types maybe we should consider removing this in j4. unsure

**Comment by laoneo** [comment]
Thought I will have a fight to remove it, so I took the easy way and wanted at least to add a proper message. I'm ok with removal too as it exists now for a couple of years in the J3 code base and it would be an acceptable BC break IMO.

**Comment by laoneo** [comment]
Ok, removed the functions

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on c30f5b8fad519b4b9f15bcac4bb99b2b4853e685<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22492">issues.joomla.org/tracker/joomla-cms/22492</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c30f5b8fad519b4b9f15bcac4bb99b2b4853e685<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22492">issues.joomla.org/tracker/joomla-cms/22492</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22492">issues.joomla.org/tracker/joomla-cms/22492</a>.</sub>

**Comment by infograf768** [comment]
We have a few `isAdmin` in the vendor folder. Do these have to be taken care of?

**Comment by Quy** [comment]
@infograf768 Where? I don't see them.

**Comment by infograf768** [comment]
In a weird form
`/libraries/vendor/codeception/codeception/docs/modules/Db.md`

`/libraries/vendor/codeception/codeception/docs/modules/MongoDb.md`

It is also present, although commented out in 3 other files.

I have absolutely no idea what these files are for btw... and if isAdmin is used or not.

**Comment by mbabker** [comment]
Codeception is not the Joomla API.

Just because an `isAdmin` method exists does not mean it is working with an object that is a subclass of our `CMSApplication`.  Hint: anything in the `libraries/vendor` directory isn't working in that context :wink:

**Comment by infograf768** [comment]
Thanks @mbabker 
Just wanted to be sure.

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Documented https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#CMSApplication

**Comment by brianteeman** [comment]
By removing this code we completely kill sites on upgrade and leave them in a state that they cannot be recovered from

**Comment by wilsonge** [comment]
Can you elaborate? Presumably that’s if sites are running plugins with this code in?

**Comment by brianteeman** [comment]
see #30913

**Comment by joeforjoomla** [comment]
It's enough to have an isSite/isAdmin in a system plugin to kill a website.

**Pull request merged**
