### PR TITLE
Handle DB errors in articles archive module

### PR DESCRIPTION
**Pull request by alikon**
updated to handle DB errors like #6612 ,#6632, #6665, #6666, #6675 and for #6591

Testing info
simulate a db error

### CODE REVIEW

**Comment by snarf007** [comment]
Could you please provide some test data/scripts/files and some test instructions?
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6708">issues.joomla.org/joomla-cms/6708</a>.</sub>

**Comment by henkrijneveld** [comment]
Tested by changing columnname created to creeated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6708">issues.joomla.org/joomla-cms/6708</a>.</sub>

**Comment by zero-24** [comment]
@snarf007 

>Could you please provide some test data/scripts/files and some test instructions?

Try: https://github.com/alikon/joomla-cms/blob/patch-23/modules/mod_articles_archive/helper.php#L39

-`->where('state = 2 AND checked_out = 0')`
+`->where('state_error = 2 AND checked_out_error = 0')`

**Comment by snarf007** [comment]
Tested by changing the columname created to created in the content table.
Resulted in a SQL error message in the message position in red.
Test result OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6708">issues.joomla.org/joomla-cms/6708</a>.</sub>

**Comment by sovainfo** [comment]
Object to this PR. Suggest to change the template to cope with no archived articles which will take care of the situation something went wrong in the database. Website visitor should not be confronted with infra problems. Just stating there are no archives should be enough.

**Comment by nonumber** [comment]
Not sure if this should get merged with regards to discussion on https://github.com/joomla/joomla-cms/pull/6710

**Comment by brianteeman** [comment]
Setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6708">issues.joomla.org/joomla-cms/6708</a>.</sub>

**Pull request closed without merging**
