### PR TITLE
[4.0] Fix category edit page title when Associations toolbar fails

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27025 and https://github.com/joomla/joomla-cms/pull/27029#issuecomment-552076368

### Summary of Changes
Correcting redirect links for category edit.

### Testing Instructions
Create a multilingual site
Go to Content > Categories (same for all core components using categories)
Edit `Uncategorised` (Make sure its language is set to `All`)
Click the `Associations` toolbar button

### Before patch

uncategorised

### After patch
The correct string is used.

cattitle

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fb2bc6eb07f54f4fc66446c07f8c343913dc497e<br /><br />Hint for other testers: It needs a basic multilingual setup, i.e. install 1 or more languages and then multilingual sample data, or enable the language filter plugin and so on, to have associations enabled. The test then has to be done as described with a category of any kind having language "All".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27031">issues.joomla.org/tracker/joomla-cms/27031</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fb2bc6eb07f54f4fc66446c07f8c343913dc497e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27031">issues.joomla.org/tracker/joomla-cms/27031</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27031">issues.joomla.org/tracker/joomla-cms/27031</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! By the way shouldn’t the line above this take sections into account rather than hardcoded category suffix to Extensions

**Comment by infograf768** [comment]
> By the way shouldn’t the line above this take sections into account rather than hardcoded category suffix to Extensions.

Honestly no idea. Do we  have a component to test such a situation?

**Comment by wilsonge** [comment]
I think @bakual might

**Comment by infograf768** [comment]
@Bakual 
Can you please test this with your component and help if necessary?

**Pull request merged**
