### PR TITLE
[plg_system_debug] Allow to hide session tab too

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Simple PR to allow also to hide the session tab in debug system plugin.

image
### Testing Instructions
1. Apply patch
2. Enable debug in global config and enable debug system plugin
3. In debug sysem plugin set "Show Session Data: No"
4. Load any page and check the session data is not in the debug plugin tabs in the bottom of the page.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
seems travis php 7 is nuts

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on c981fd632fa39009fa2f48259f13a67ceb42ae74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12115">issues.joomla.org/joomla-cms/12115</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c981fd632fa39009fa2f48259f13a67ceb42ae74<br /><br />looks good to me :smile: :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12115">issues.joomla.org/joomla-cms/12115</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12115">issues.joomla.org/joomla-cms/12115</a>.</sub>

**Pull request merged**
