### PR TITLE
[4.0] Revert switcher

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/15391 .

### Summary of Changes
* Changes the order of the options back to what we have in J3, meaning Yes/Show on left side and No/Hide on the right.
* Removes the "Switcher" layout and JS and restores the btn-group behavior we have in J3.

### Testing Instructions
Open various settings page. Most occurances of those radio elements are typical in component settings.

### Expected result
Have an intuitive toggle button

### Actual result
Have an unintuitive switcher thing with inverted option order and unclear states

### Documentation Changes Required
None

### Known issue
Maybe someone can help me here:
The `btn-group` doesn't work with the `<fieldset>` tag. I changed the tag generated in the radio JLayout to `<div>` and it works fine. This may be a bug in BS4, I wasn't able to figure out where the difference comes from.

### CODE REVIEW

**Comment by dgt41** [comment]
@Bakual you need to remove switcher from grunt-settings.yaml and remove the related lines from Gruntfile.js.

> The btn-group doesn't work with the <fieldset> tag. I changed the tag generated in the radio JLayout to <div> and it works fine. This may be a bug in BS4, I wasn't able to figure out where the difference comes from.

Just rename the `<div>` to `<joomla-buttons>` and use the related custom element 😀

Anyways I'm not in favour of removing the switcher but I'm ok with reverting the xml changes. By the way switcher can still be done with the original xml structure...

**Comment by Bakual** [comment]
> you need to remove switcher from grunt-settings.yaml and remove the related lines from Gruntfile.js.

@dgt41 Afaik it wasn't a file pulled in using Grunt, it something done ourself. I did have a look now at those grunt files and couldn't find anything related to switcher.js. If I missed something, feel free to point me to it.

> Anyways I'm not in favour of removing the switcher but I'm ok with reverting the xml changes. By the way switcher can still be done with the original xml structure...

I did the changes to the XML, JS and CSS in separate commits for that reason so it would be easy to take only parts of this PR.
I think the switcher needs some serious work anyway if you want to use that. It lacks in many aspects currently. It may have situational use cases, but for regular options in components settings or menu params and the like I don't see us using it. It doesn't even look nice between selects and other inputs. The style and width just don't match.

**Comment by brianteeman** [comment]
My 2c i am not convinced that a switcher is suitable for a desktop application - so at this time I would agree to removing it and reverting back as here. It can be looked at again in the future

**Comment by mbabker** [comment]
So this decision was actually driven based on us having some conflicts between CSS frameworks, but we ended up pulling out all of the switcher based checkboxes in the frontend of an app we're building right now in favor of "plain" checkboxes.  I realize our switchers are primarily radio based, but the same general concept applies.

screen shot 2017-05-10 at 1 53 18 pm

screen shot 2017-05-10 at 1 53 34 pm

**Comment by Bakual** [comment]
Got the `btn-group-yesno` working now. Still need to figure out the fieldsetvs div thing. I'm still lost there 😄

**Comment by brianteeman** [comment]
At this time I am closing this PR. We need to let the J4 guys deliver and alpha with this and then we can of course review it then when a wider audience have seen it. 

Change is always disturbing but we have to be brave and try things.

**Pull request closed without merging**
