### PR TITLE
[4.0] Use Strong

### PR DESCRIPTION
**Pull request by brianteeman**
the strong tag has more semantic meaning than the b tag which is purely typographical

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on ccb8b16bf8963258c2b6a4e38a635a11972f426b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15649">issues.joomla.org/tracker/joomla-cms/15649</a>.</sub>

**Comment by elkuku** [comment]
I have tested this item :white_check_mark: successfully on ccb8b16bf8963258c2b6a4e38a635a11972f426b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15649">issues.joomla.org/tracker/joomla-cms/15649</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
