### PR TITLE
Move inline JCaption to caption.js

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Description

This PR moves the inline JCaption js onload call to the external caption.js file.
### How to test
1. Fresh Joomla install with sample data.
2. Install the patch
3. Add an image with caption to a content
4. Check frontend if image caption is there
5. Check the HTML page code. JCaption inline js should no longer be there
### B/C

None.

### CODE REVIEW

**Comment by Bakual** [comment]
Due to our B/C policy, the selector has to stay and work.

**Comment by andrepereiradasilva** [comment]
Ok @Bakual, reverted the selector changes and is working for B/C.
Can you remove the "Unit/System Tests" label?

**Comment by Bakual** [comment]
Removed the label.

**Comment by wilsonge** [comment]
There's no way we can merge this as-is. This is really complex now and you are actually initialising the caption on a potentially non-existing class which although it won't break anything seems like it's just going to cause more problems than it solves

**Comment by Bakual** [comment]
I would actually prefer to get rid of that JS (deprecate it) and merge https://github.com/joomla/joomla-cms/pull/7450 so we have native HTML captions :smile:

**Comment by andrepereiradasilva** [comment]
hi @wilsonge , thanks for the feedback.
Please tell me what you think of the following suggestion:

> This is really complex now

I agree. In my view the best solution for this and other cases with data values (in this case the selector class) is to put them in a HTML5 data-* attributes that can be read form external js and this way simplify the whole thing, and without inline js.

The problem is that there is no function for that in JDocumentHtml.
I'm testing to create one `addData` public function.
Somehing like:
```public function addHTMLData($name, $data, $tag = 'body')
{
	$this->_htmldata[$tag][$name] = $data;

	return $this;
}``´

And just call it like:
```JFactory::getDocument()->addBodyData('caption', 'img.caption', 'body');```

That will generate a `<body data-caption='img.caption'` that can be easy be accesses in jQuery with `jQuery('body').data('caption')`

This could also be used to put json arrays in data-* attributes which could be useful for plugin development.

> you are actually initialising the caption on a potentially non-existing class

Yes i see. I will put a check that element exists before initializing.

**Comment by zero-24** [comment]
Feel free to test there @bakual else it get never in :P

**Comment by dgt41** [comment]
@Bakual @zero-24 @wilsonge we are gonna need that PR merged before we update to tinyMCE 4.3 http://blog.tinymce.com/2015/11/24/tinymce-4-3-brings-new-features-stability-improvements/

**Comment by Bakual** [comment]
@dgt41 Which PR?

**Comment by dgt41** [comment]
#7450

**Comment by Bakual** [comment]
Why? Captions inserted by the "Images" button from the editor plugins already insert native captions for quite some time. The other PR is only about the images specified in the article item (not the article content), eg the intro and full text images.
We have to keep the caption.js for B/C reasons anyway.

**Comment by dgt41** [comment]
Ok, I got it wrong

**Comment by andrepereiradasilva** [comment]
Closed as there is already a PR to remove caption.js and make caption in HTML

**Pull request closed without merging**
