### PR TITLE
This messages should be error type not notice type

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Simple Pr to convert to message from `notice` to `error` in the media upload.
### Testing Instructions

Code review.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7ce29101adc703dc99a106bcc20ad65ceae28143<br /><br />On review :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12273">issues.joomla.org/joomla-cms/12273</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 7ce29101adc703dc99a106bcc20ad65ceae28143<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12273">issues.joomla.org/joomla-cms/12273</a>.</sub>

**Comment by zero-24** [comment]
RTC

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Pull request merged**
