### PR TITLE
[4.0] Remove unused layout blog_style_default_links

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Remove unused layout file

### Testing Instructions
Make some blogs with links. Apply the patch. 

Inspect code - the layot is not used anywhere

### Expected result AFTER applying this Pull Request
Blogs and links are didsplayed as before

### Documentation Changes Required
no

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ea3b88f240b375a6b57f43576cb6f0df718bb595<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32437">issues.joomla.org/tracker/joomla-cms/32437</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ea3b88f240b375a6b57f43576cb6f0df718bb595<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32437">issues.joomla.org/tracker/joomla-cms/32437</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32437">issues.joomla.org/tracker/joomla-cms/32437</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
