### PR TITLE
Added a css-class ("alert-message") to the p-tag which contains the alert message

### PR DESCRIPTION
**Pull request by Eriiond**
I added a css-class ("alert-message") to the p-tag which contains the alert message.

You can test it by adding a new article and after saving it successfully, the p-tag has no css.class.
Next, open the article again and remove the title. Then try to save the article. This will produce an error message which also has no css-class.

After applying the patch, repeat the steps but now the p-tag has a clss-class "alert-message".

### CODE REVIEW

**Comment by Preview** [comment]
@test The patch works for both frontend and backend. I tested it by creating articles and by trying to save an article without a title to get different produced messages (PHP and JS).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7070">issues.joomla.org/joomla-cms/7070</a>.</sub>

**Comment by dgt41** [comment]
@test OK <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7070">issues.joomla.org/joomla-cms/7070</a>.</sub>

**Comment by zero-24** [comment]
RTC based on tests Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7070">issues.joomla.org/joomla-cms/7070</a>.</sub>

**Comment by infograf768** [comment]
Merge conflicts.

**Pull request closed without merging**
