### PR TITLE
Added missing increment operator `++`

### PR DESCRIPTION
**Pull request by LeoOnTheEarth**
.Moving to RTC - thanks

### CODE REVIEW

**Comment by joomdonation** [comment]
@test: Success

Before patch: The resetCount field in #__users table is not increased each time a password request is processed

After path: The resetCount field in #__users table is properly increased each time a password request is processed

**Comment by waader** [comment]
@test success!

**Comment by brianteeman** [comment]
I can NOT confirm this issue

With a clean beta1 site using sample data I submitted a password reset for my test user and the field "reset count" in #__users has been incremented by 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5918">issues.joomla.org/joomla-cms/5918</a>.</sub>

**Comment by brianteeman** [comment]
OH wait - it didnt go to 2 on a second try<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5918">issues.joomla.org/joomla-cms/5918</a>.</sub>

**Comment by brianteeman** [comment]
Having noticed my mistake I can confirm that the patch works and the count is incremented and a warning is given when the maximum is reached<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5918">issues.joomla.org/joomla-cms/5918</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks guys!

**Pull request merged**
