### PR TITLE
Banners, Changed Filter Option "Type"

### PR DESCRIPTION
**Pull request by pe7er**
Patch related to #6941 to correct inconsistency with Filter.
All filters are "- Select Something - " except for "- Type -"
## Test instructions

In back-end > Components > Banners > **Clients** > click on [Search Tools] 
It has 2 filter options:
"Select Status" & **"Type"**

screen shot 2015-05-14 at 09 24 45

In back-end > Components > Banners > **Tracks**
on the left It has 3 filter options:
"Select Client", "Select Category" & **"Type"**

screen shot 2015-05-14 at 09 24 45
### This PR changes the language string

for COM_BANNERS_SELECT_TYPE to **"- Select Type -"**

screen shot 2015-05-14 at 09 24 45

screen shot 2015-05-14 at 09 24 45

### CODE REVIEW

**Comment by pe7er** [comment]
Can someone please tag this PR to the Joomla Issue Category "Languages & Strings" ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6946">issues.joomla.org/joomla-cms/6946</a>.</sub>

**Comment by MAT978** [comment]
@test
abale to reproduce then #6946 works as expected for both selectors - Thanks
Good catch

**Comment by adhocgraFX** [comment]
@test OK! good work! @pe7er  :)

**Comment by zero-24** [comment]
RTC'ing Thanks for testing and coding here :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6946">issues.joomla.org/joomla-cms/6946</a>.</sub>

**Pull request merged**
