### PR TITLE
[com_fields] Responsive subform.repeatable-table

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
This PR makes subform tables responsive, switching from column to row views on smaller screens. This form is used in com_fields however applies to all subform tables

### Testing Instructions
Navigate to Content -> Fields -> New. Set 'Type' to 'Checkbox', add a number of values and resize the browser window.

@laoneo This resolves the issue we discussed at the sprint regarding using subform.repeatable-table and smaller screens.

### Before Patch
subform1

### After Patch
subform2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6527898ab782b8383fd07ed2d7b5d699831575e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13769">issues.joomla.org/tracker/joomla-cms/13769</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 6527898ab782b8383fd07ed2d7b5d699831575e7<br /><br />Tested it also with some bigger subform fields and it works superb. Thanks Ciaran!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13769">issues.joomla.org/tracker/joomla-cms/13769</a>.</sub>

**Comment by laoneo** [comment]
I think it would be a new PR, but can this being applied for all tables to make them responsive?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13769">issues.joomla.org/tracker/joomla-cms/13769</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13769">issues.joomla.org/tracker/joomla-cms/13769</a>.</sub>

**Comment by ciar4n** [comment]
Yes.. there would be no real problem there. All that is required is that the title is added to a data attribute for each td (layouts/joomla/form/field/subform/repeatable-table/section.php).

 For some tables there may be to much data to display every column in the row view. Would need to decide what rows to show and what rows to leave out for each table.

**Pull request merged**
