### PR TITLE
[4.0][SQL] - R.I.P mod_submenu

### PR DESCRIPTION
**Pull request by alikon**
since 4.0.0-2016-10-03.sql there is no more `mod_submenu`

### Summary of Changes
removed from install joomla.sql sample_testing.sql

for postgresql R.I.P `phputf8` too

### CODE REVIEW

**Comment by brianteeman** [comment]
But the module still exists- me confused

**Comment by alikon** [comment]
where ??

**Comment by alikon** [comment]
it is removed 
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L1361

**Comment by brianteeman** [comment]
Sorry. Was trying to read github on my phone. Selected j4 but when I navigated it went back to staging.

**Comment by wilsonge** [comment]
Nice one thanks!

**Pull request merged**
