### PR TITLE
[4] npm audit fix --force

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/32738 .

### Summary of Changes

npm audit fix --force

### Actual result BEFORE applying this Pull Request

3 high severity vulnerabilities

### Expected result AFTER applying this Pull Request

0 high severity vulnerabilities

### CODE REVIEW

**Comment by PhilETaylor** [comment]
No idea if this is right or acceptable... but its the result of my running `npm audit fix --force`

**Comment by richard67** [comment]
@PhilETaylor NPM failing, so there seems to be something wrong: https://ci.joomla.org/joomla/joomla-cms/40847/1/7

**Comment by richard67** [comment]
Will restart drone to see it it's related or not.

**Comment by PhilETaylor** [comment]
Sorry - beyond me. NPM and I hate each other. @dgrammatiko ?

**Comment by dgrammatiko** [comment]
Haha, should be fixable with `npm install -D @vue/compiler-sfc` and then re push the json files

Edit: you need to check if media manager still compiles as expected. We seem that we merging a major version here

**Comment by PhilETaylor** [comment]
you wish it was that easy :) ... no joy! 

Screenshot 2021-03-18 at 19 42 50

**Comment by PhilETaylor** [comment]
I give up. Im out of my depth :) Closing for now... and reopening the issue

**Pull request closed without merging**
