### PR TITLE
Allow TinyMCE to respect the template's options

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for improving the UX and making editing a bit easier.

### Summary of Changes
TinyMCE out of the box comes with some very basic styling. Eg the `Bold` button is just a `<strong>` around the selected text. But the editor gives the ability for further customisations e.g.: attach a class or inline styles etc...

So this PR brings that functionality to Joomla.
It covers both styles and formats (styles are the ones that correspond to the buttons e.g. bold, align left, etc and formats are the ones that will be in the formats dropdown)

### Testing Instructions
Grab the files from https://gist.github.com/dgt41/be9e16814371f43ce99e8dc74ef54e99
and place them in `administrator/templates/isis/css` directory
Edit tinyMCE's configuration and type the relative paths:
screen shot 2017-03-10 at 13 09 07
Edit an article and observe the code when selecting a format or applying a style (e.g. bold, align right)
screen shot 2017-03-10 at 12 42 49

#### Styles (standard buttons):
screen shot 2017-03-10 at 13 14 35

#### Formats (Formats dropdown
screen shot 2017-03-10 at 13 14 03
):

### Documentation Changes Required
Yup!

Inspired by @coolcat-creations post on @brianteeman 's site...

### CODE REVIEW

**Comment by brianteeman** [comment]
From your screenshot you show the file being a json file

The language strings make no mention of this at all

**Comment by dgt41** [comment]
@brianteeman you can improve it as you like...

**Comment by brianteeman** [comment]
@dgt41 but I dont know what it should be

**Comment by dgt41** [comment]
The filename could be anything, same goes for the path, the only requirement is to be json type.

**Comment by brianteeman** [comment]
> the only requirement is to be json type

So that needs to be mentioned ;)

**Comment by infograf768** [comment]
maybe with ahint in the field?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14456">issues.joomla.org/tracker/joomla-cms/14456</a>.</sub>

**Pull request closed without merging**
