### PR TITLE
4.0 dev For issue 19016

### PR DESCRIPTION
**Pull request by phalouvas**
Pull Request for Issue #19016  .

### Summary of Changes
[BannerTable.txt](https://github.com/joomla/joomla-cms/files/1541452/BannerTable.txt)

### Testing Instructions
Open an existing banner and save it.

### Expected result
Save the banner

### Actual result
Without the patch, fails to save.

### CODE REVIEW

**Comment by ghost** [comment]
This PR is created Today but has Comments from October?

**Comment by rdeutz** [comment]
you are trying to merge the 4.0 branch into staging, you shouldn't try this :-)

**Comment by phalouvas** [comment]
sorry for this. Still the issue #19016  is valid. I attached a patch for it.

**Comment by rdeutz** [comment]
* you should check out the 4.0-dev branch
* make changes
* submit a PR based on the 4.0-dev branch

If you find yourself in a situation with 8000 changed files in a PR something is wrong

**Pull request closed without merging**
