### PR TITLE
[5.0] schemaorg remove double space

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

unnecessary space removed

### Testing Instructions

check links works for all schemes or code review
image

### Actual result BEFORE applying this Pull Request

link works

### Expected result AFTER applying this Pull Request

link works

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 53991c46d82fe8f2c03e16ace82ce09252d5bc0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41401">issues.joomla.org/tracker/joomla-cms/41401</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 53991c46d82fe8f2c03e16ace82ce09252d5bc0d<br /><br />Code review. Redundant spaces removed, necessary spaces still there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41401">issues.joomla.org/tracker/joomla-cms/41401</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41401">issues.joomla.org/tracker/joomla-cms/41401</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
