### PR TITLE
s/postions/positions

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/postions/positions

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4ff19c1e1584926b389387a9d3390d0a5e424a66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23030">issues.joomla.org/tracker/joomla-cms/23030</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 4ff19c1e1584926b389387a9d3390d0a5e424a66<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23030">issues.joomla.org/tracker/joomla-cms/23030</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4ff19c1e1584926b389387a9d3390d0a5e424a66<br /><br />Code review. Now all occurrences of "postions" have been removed from J4, see [comment here](https://github.com/joomla/joomla-cms/pull/23009#issuecomment-437579677 "https://github.com/joomla/joomla-cms/pull/23009#issuecomment-437579677").<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23030">issues.joomla.org/tracker/joomla-cms/23030</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23030">issues.joomla.org/tracker/joomla-cms/23030</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
