### PR TITLE
missing bang

### PR DESCRIPTION
**Pull request by jeckodevelopment**
### Summary of Changes

Added `!` to `Joomla Statistics`

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fdd2661e4316d8ff55b8872c4d46233eba2a6676<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12418">issues.joomla.org/tracker/joomla-cms/12418</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on fdd2661e4316d8ff55b8872c4d46233eba2a6676<br /><br />This is not correct. See https://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12418">issues.joomla.org/tracker/joomla-cms/12418</a>.</sub>

**Comment by MATsxm** [comment]
@jeckodevelopment 
like Brian mentioned, core strings are exceptions

**Comment by brianteeman** [comment]
Closed

**Comment by jeckodevelopment** [comment]
yes. Thank you.
I saw the string, but i didn't check well the "compliance" because i was at an event :)

**Pull request closed without merging**
