### PR TITLE
updated rating stars to cleaner look.

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#### Summary of Changes

Updates rating stars to a cleaner look.
#### Testing Instructions

create an article in the front end with voting enabled.
look at stars and notice they are not clearly defined especially on dark background.
pre

apply patch.
notice voted and non-voted stars are much cleaner.
post

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Blank version is invisible on dark backgrounds due to dark outline. Should be lighter to be visible on both light and dark backgrounds.

The image on the left has increased brightness.
untitled

**Comment by N6REJ** [comment]
I like that @SharkyKZ  the ones I had done were optimized via PS png export.
you think the only one we need to change is the blank one?

**Comment by SharkyKZ** [comment]
Yellow looks good on both light and dark background, but blank needs to be lighter to be visible on dark background. Although even in that case it won't be visible on some (grey) backgrounds.

Downloaded images from GitHub are 1.1~1.3 KB each. Can be optimized to 200-300 B.

I'm also wondering whether or not the circle needs to be changed to a star. That said, I'm suggesting these:
rating_star_blank
rating_star

**Comment by bembelimen** [comment]
Why not using icomoon? icon-star(-2/-empty)

**Comment by N6REJ** [comment]
@SharkyKZ both those look nice... 
@bembelimen is the icon-star in the joomla set already?

**Comment by Bakual** [comment]
@N6REJ See https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts for the currently used pack.

**Comment by SharkyKZ** [comment]
Unless it's optional or overridable, IcoMoon inside a plugin would cause difficulties for those using newer templates without IcoMoon.

**Comment by Bakual** [comment]
That being said, you probably can't just change the image to a CSS effect using IcoMoon. The current images can be overriden by templates plus templates may or may not implement the Icomoon set. So if you change this to the IcoMoon stars, you can probably break sites.

**Comment by brianteeman** [comment]
Im a little confused - your screenshot for "before" shows circles but I always have stars<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by SharkyKZ** [comment]
He's using a custom template. Joomla has circles by default, but protostar has overrides with stars. Circles do need a cleanup.

**Comment by brianteeman** [comment]
> Circles do need a cleanup.

So this PR changes the circles to a star but the PR says it is giving stars a cleaner look 😕  confused

**Comment by N6REJ** [comment]
it showed circle(ish) but the class and file name is stars... I'll take a closer look at this this weekend.

**Comment by gunjanpatel** [comment]
Showing circles only when I choose Beez template. Already stars in Protostar template. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 7f5df386ffaae30a38e92f96fbbc83a8a0b8a546<br /><br />Tested successfully. Must check in Beez3 template. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by rahulkoshti** [comment]
I have tested this item :white_check_mark: successfully on 7f5df386ffaae30a38e92f96fbbc83a8a0b8a546<br /><br />Tested Successfully in a Beez3 template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by gautam911** [comment]
I have tested this item :white_check_mark: successfully on 7f5df386ffaae30a38e92f96fbbc83a8a0b8a546<br /><br />successfully tested only in Beez3 template.

Thanks @gunjanpatel for updating actual information.





<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by roland-d** [comment]
I am confused as well. Is the goal of this PR to replace the circles for stars?

@N6REJ You said you would look into this, did you?

**Comment by wilsonge** [comment]
I'm removing the RTC label here for now whilst we await clarification from Troy here. I *think* this is ok...

**Comment by brianteeman** [comment]
@N6REJ could you please respond or this will be closed in a few weeks
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by brianteeman** [comment]
As there has been no response from @N6REJ I am closing this. It can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9967">issues.joomla.org/joomla-cms/9967</a>.</sub>

**Comment by N6REJ** [comment]
@brianteeman sorry brian for whatever reason github decided my password was different and stopped sending me notices... fixed now.

**Pull request closed without merging**
