### PR TITLE
[4] fix check extension for update

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
cast to int `client_id`

### Testing Instructions
go to Extensions: Update
click on Check for updates
use postgresql

### Actual result BEFORE applying this Pull Request
`An error has occurred.

    22 22P02, 7, ERROR: invalid input syntax for integer: "" LINE 3: ...ement = 'job' AND type = 'plugin' AND client_id = '' AND fol... ^ `

### Expected result AFTER applying this Pull Request

it shows  extension updates

### CODE REVIEW

**Comment by zero-24** [comment]
Can you show us the update server that gets this error? The client_id fallback in the XML is removed with 4.0 and the "client" [admininstator|site] should now be used without fallback

**Comment by alikon** [comment]
here https://raw.githubusercontent.com/alikon/testcom/main/plugins/console/job/manifest.xml

**Comment by zero-24** [comment]
See: https://github.com/alikon/testcom/pull/6

**Comment by alikon** [comment]
merged 
i was confused by : https://docs.joomla.org/Deploying_an_Update_Server

> Warning! Plugins and front-end modules are automatically installed with a client of 0 (site), but you will need to specify the client in an update or it will default to 1 (administrator) and then found update would not be shown because it would not match any extension.

**Comment by ChristineWk** [comment]
@alikon Similar to this Issue? https://github.com/widgetfactory/jce/issues/95#issuecomment-887526300
Don't know ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35145">issues.joomla.org/tracker/joomla-cms/35145</a>.</sub>

**Comment by alikon** [comment]
yes  alikon/testcom#6 fixed  it, they need 
`<client>site</client>` in the plugin manifest

**Comment by zero-24** [comment]
The new client setting works for 3.x already too but we had a fallback thats gone since nearly one year in 4.0: https://github.com/joomla/joomla-cms/pull/28767

**Comment by shawn61cp** [comment]
I am experiencing this issue on both an upgrade to, and a fresh install of, J! 4.2.8.  I get this error any time I install an extension.
Joomla!: 4.2.8
PostgreSQL: 14
Ubuntu: 22.04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35145">issues.joomla.org/tracker/joomla-cms/35145</a>.</sub>

**Pull request closed without merging**
