### PR TITLE
[4.3]LogtypeField code comment

### PR DESCRIPTION
**Pull request by brianteeman**
copy paste error - code review only

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 40de372be14d2698aaac05df728c5eb5a3d85eac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41007">issues.joomla.org/tracker/joomla-cms/41007</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 40de372be14d2698aaac05df728c5eb5a3d85eac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41007">issues.joomla.org/tracker/joomla-cms/41007</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41007">issues.joomla.org/tracker/joomla-cms/41007</a>.</sub>

**Comment by obuisard** [comment]
Thank you, Brian @brianteeman.

**Pull request merged**
