### PR TITLE
Change language file to NOT recommend using the mysql "root" user

### LINKED ISSUE #5897: Change language file to NOT recommend using the mysql "root" user
Maybe a quick one for @brianteeman's efforts of one PR a day?

screenshot 2015-01-27 22 25 25

### PR DESCRIPTION
**Pull request by zero24**
This try to fix: https://github.com/joomla/joomla-cms/issues/5897

@brianteeman @PhilETaylor Can you have a look into the language string.

After this PR i will look something like:
new_test_installation

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry but I dont see the need for a change in string but if you really do
then keep it simple and dont and any additional information. Its a
description not a manual ;)

So Try changing
INSTL_DATABASE_USER_DESC="Either something as &quot;root&quot; or a
username given by the host."
to
INSTL_DATABASE_USER_DESC="A username for accessing the database provided by
your host."


-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
>Its a description not a manual ;)

hehe yes thanks :smile: fixed. I think PLT can decide if we change it or not :smile:

**Comment by alikon** [comment]
despite the intention is good
don't see the need for this change  here, should be stated elsewhere docs.joomla.org or readme.....
my 0.2€

**Comment by PhilETaylor** [comment]
@alikon it is ALWAYS wrong to recommend using the root user. Period.

**Comment by wilsonge** [comment]
No it's wrong for hosts to be providing root user access. This message is targeted at end users however not hosts.

**Comment by phproberto** [comment]
Maybe we can use:

> This is your database user name. If your hosting provider tells you to use the `root` user you should pay someone to go there and burn their offices. Alternatively if you need support you can create an account in joomla forums, github, JCM and volunteers portal. Then learn git, php, unit testing, html, css, js and 2 more random technologies. You are ready to send a security report. Did you know that Joomla was born as a fork of Mambo? Press ALT+F4 if you still don't understand what this means.

**Comment by brianteeman** [comment]
+100

On 9 April 2015 at 23:39, Roberto Segura <notifications@github.com> wrote:

> Maybe we can use:
>
> This is your database user name. If your hosting provider tells you to use
> the root user you should pay someone to go there and burn their offices.
> Alternatively if you need support you can create an account in joomla
> forums, github, JCM and volunteers portal. Then learn git, php, unit
> testing, html, css, js and 2 more random technologies. You are ready to
> send a security report. Did you know that Joomla was born as a fork of
> Mambo? Press ALT+F4 if you still don't understand what this means.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6721#issuecomment-91373088>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
I don't what to fight with you :smile: Closing

**Comment by phproberto** [comment]
I was only joking trying to say that we cannot explain how internet works in 2 lines :dancers:

**Comment by dgt41** [comment]
> Press ALT+F4 if you still don't understand what this means.

I am afraid this isn’t complete, also needs (at least): 

> or command - q if you use a mac computer.

😃

**Comment by zero-24** [comment]
Sorry i have miss interpreted the comments.

**Comment by infograf768** [comment]
@maintainers
As for every cgnage in the installation ini files, if committed, this means a specific language freeze much before the release in order to get the TT to provide the updated files before the release itself.

**Comment by smz** [comment]
Methink this can go directly to RTC (unhappily for 3.4.3 or 3.5.0, at this time...)

**Comment by wilsonge** [comment]
Having consulted with leadership I'm closing this as something we aren't interested in

**Comment by PhilETaylor** [comment]
Funny how your closing remark changed from "not interested" to " as still isn't worded correctly"

http://screenshot.myjoomla.io/image/1W2G3H0X1o2T

If the faceless/unamed "leadership" are "not interested" in security then you should name their names so that we can remove them from their position

Closing 'issues' just to make number of issues -1 is not acceptable. 

This PR changes the the text to "A username for accessing the database provided by your host." which IMHO is perfect as the recommendation to use a root user is all that we need to remove, and this PR does that,

I recommend this gets reopened.

**Comment by PhilETaylor** [comment]
I suppose this will be ignored now as the "leadership" are NOT INTERESTED in Joomla Security enough to make a small text change to avoid recommending using the root user. 

So why then did we stop recommending using "admin" as the admin username? - same thing 

#NoBodyListens #MakeTheSameMistakesAsThePast! #TapTapIsThisThingOn?

**Comment by brianteeman** [comment]
Sorry Phil but while I might agree with your change the connection to the
username is completely wrong.

The username is something that EVERY site owner will choose on their own so
it was absolutely correct to make the change
The database details is something that very few site owners have any
control of at all as it is provided by their host. Even for those that can
create thir own credentials via cpanel will be prevented from using root by
cpanel itself. So the only people that "might" consider this loosely word
text as a recommendation have such control of their server that they really
should know better

On 19 June 2015 at 23:30, Phil Taylor <notifications@github.com> wrote:

> I suppose this will be ignored now as the "leadership" are NOT INTERESTED
> in Joomla Security enough to make a small text change to avoid recommending
> using the root user.
>
> So why then did we stop recommending using "admin" as the admin username?
> - same thing
>
> #NoBodyListens #MakeTheSameMistakesAsThePast! #TapTapIsThisThingOn?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6721#issuecomment-113661829>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by PhilETaylor** [comment]
The current text in Joomla 3.4.1 is 

"Either something as "root" or a username given by the host" 

This is plain wrong. We should not be recommending, ever, to use the root username. 

All that I'm asking is that this sentenance is changed to something else - anything - that doesnt mention the word root

"The database username given by the host"
"The username to connect to your database"
"The identity string your mysql server is expecting"

ANYTHING that doesnt not imply "root" is acceptable.

This doesn't stop idiots (or developers developing locally) from using "root" - but it does set out that Joomla doesn't proactively recommend root as an acceptable identity string.

In exactly the same way we removed "admin" as the default Joomla Super Admin username ...

**Comment by brianteeman** [comment]
I do not believe the current text "recommends" anything
And as stated before the correlation you are drawing with the Joomla
username is incorrect and like comparing an orange to a strawberry

On 20 June 2015 at 00:04, Phil Taylor <notifications@github.com> wrote:

> The current text in Joomla 3.4.1 is
>
> "Either something as "root" or a username given by the host"
>
> This is plain wrong. We should not be recommending, ever, to use the root
> username.
>
> All that I'm asking is that this sentenance is changed to something else -
> anything - that doesnt mention the word root
>
> "The database username given by the host"
> "The username to connect to your database"
> "The identity string your mysql server is expecting"
>
> ANYTHING that doesnt not imply "root" is acceptable.
>
> This doesn't stop idiots (or developers developing locally) from using
> "root" - but it does set out that Joomla doesn't proactively recommend root
> as an acceptable identity string.
>
> In exactly the same way we removed "admin" as the default Joomla Super
> Admin username ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6721#issuecomment-113666949>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by PhilETaylor** [comment]
ok whatever - its clear the leadership are not interested as stated by @wilsonge and so this will never be changed or challenged. 

screen shot 2015-06-20 at 00 25 20
screen shot 2015-06-20 at 00 26 11
screen shot 2015-06-20 at 00 27 45
screen shot 2015-06-20 at 00 29 13

screen shot 2015-06-20 at 00 22 39

**Pull request closed without merging**
