### PR TITLE
[3.9] Sync en-GB.ini files with the changes from #18361

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #18361

### Summary of Changes

Sync en-GB.ini files with the changes from #18361

### Testing Instructions

Review the ini changes

### Expected result

en-GB.ini files are in sync

### Actual result

en-GB.ini files are not in sync

### Documentation Changes Required

None

cc @infograf768 there are also other things not synce between that files. Can you confirm that they are not needed or tell me what is missing so we can setup a complete PR. Thanks

### CODE REVIEW

**Comment by infograf768** [comment]
are’nt these strings added here in the wrong client compared to #18361 ?

**Comment by zero-24** [comment]
Hmm I don't understand the question? I have added the new strings to the frontend and backend files where they are missing.

**Comment by Bakual** [comment]
Those two files don't need to be in sync. The lib one needs to be 😄

**Comment by zero-24** [comment]
Thanks.

**Pull request closed without merging**
