### PR TITLE
Fix/showon

### PR DESCRIPTION
**Pull request by toroworx**
Pull Request for Issue # .
https://github.com/joomla/joomla-cms/issues/37299

### Summary of Changes
Fixed showon issue for nested options as described above.

### Testing Instructions
https://github.com/joomla/joomla-cms/pull/37300#issuecomment-1072565349

### Documentation Changes Required
none

### CODE REVIEW

**Comment by richard67** [comment]
I've allowed myself to fix the merge conflict after the rebase.

**Comment by robinclapp** [comment]
I have tested this item :white_check_mark: successfully on fec38be68c8eac316c41833913bdd7c1d8c50b0e<br /><br />Note, that the other issue where status gets stuck when pinned inside com_banner edit<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37451">issues.joomla.org/tracker/joomla-cms/37451</a>.</sub>

**Comment by blanderson22** [comment]
I have tested this item :white_check_mark: successfully on fec38be68c8eac316c41833913bdd7c1d8c50b0e<br /><br />Note, that the other issue mentioned on GitHub, where status gets stuck when pinned inside com_banner edit, still exists. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37451">issues.joomla.org/tracker/joomla-cms/37451</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37451">issues.joomla.org/tracker/joomla-cms/37451</a>.</sub>

**Comment by obuisard** [comment]
Thank you @toroworx for the PR!

**Comment by toroworx** [comment]
You're most welcome! Thanks for testing and merging :-) @richard67 @robinclapp @blanderson22 @obuisard

**Pull request merged**
