### PR TITLE
[4.0] Plugin edit layouts

### PR DESCRIPTION
**Pull request by brianteeman**
Render all the fields in the sidebar using the layout. There should be no visible difference or any difference in the generated code.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21b5268d09f60b1bc3f55761e146567eedd46756<br /><br />No visual changes. Code shows differences but they are expected, e.g. `<div class="form-vertical form-no-margin">` missing after the patch because removed with that PR. The code of the fields themselves is same as without the patch. @brianteeman maybe you should slighty modify the testing instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25329">issues.joomla.org/tracker/joomla-cms/25329</a>.</sub>

**Comment by brianteeman** [comment]
The div with the class is not needed as the classes are already present on the fieldset

**Comment by richard67** [comment]
Yes, I saw. Maybe you just should have put the word "generated" in bold letters in "difference in the generated code" for fast readers like me ;-)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 21b5268d09f60b1bc3f55761e146567eedd46756<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25329">issues.joomla.org/tracker/joomla-cms/25329</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25329">issues.joomla.org/tracker/joomla-cms/25329</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
