### PR TITLE
[4] correct syntax of union type in docbock

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 24ebb642194e47baf476444a3c2fc5f84de3b25c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36413">issues.joomla.org/tracker/joomla-cms/36413</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 24ebb642194e47baf476444a3c2fc5f84de3b25c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36413">issues.joomla.org/tracker/joomla-cms/36413</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36413">issues.joomla.org/tracker/joomla-cms/36413</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
