### PR TITLE
[4.0] Text overlapping in image info

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - When viewing information about an image the text overlaps when toggle menu is open both in PC as well as mobile devices.
**Mobile**
screenshot from 2019-02-14 16-41-25
**PC**
screenshot from 2019-02-14 16-41-08

### Summary of Changes
Removed flex property which solves the issue both in PC and Mobile irrespective of whether toggle menu is open or closed
**Mobile-**
screenshot from 2019-02-14 16-40-11
**PC-**
screenshot from 2019-02-14 16-39-09

### Testing Instructions
Components->media->select an image->info

### Documentation Changes Required
No

### CODE REVIEW

**Comment by bahl24** [comment]
@infograf768 @dgrammatiko @Quy @C-Lodder  Kindly provide feedback regarding the design changes

**Comment by C-Lodder** [comment]
all seems fine to me

**Comment by bahl24** [comment]
@infograf768 @Quy Kindly test this

**Comment by infograf768** [comment]
This does not solve RTL.
screen shot 2019-02-21 at 08 59 16

(Would need bootstrap override specific to RTL)

In my patch for RTL I have used ul/li and no flex to solve all issues, including in LTR.

RTL
screen shot 2019-02-21 at 09 18 16

LTR
screen shot 2019-02-21 at 09 18 48

Mobile
As you can see, I have also modified css to get more space for the name of the file in mobile vue

screen shot 2019-02-21 at 09 25 36

I have not proposed this patch yet as it waits for other PRs to be merged, specially 
https://github.com/joomla/joomla-cms/pull/23950
and
https://github.com/joomla/joomla-cms/pull/23756

**Comment by bahl24** [comment]
Ok, I will close it then

**Comment by infograf768** [comment]
Please don't close.
the decision to use ul/li instead of ol/etc. should be decided by maintainers.
@C-Lodder @wilsonge 
I could update my future patch to your proposal with a bootstrap override and my other modififications should still be possible.

**Comment by C-Lodder** [comment]
@infograf768 `ol` vs `ul` don't need a decision by maintainers. One is an ordered list (1, 2, 3, etc) and the other isn't. In general, using a list would probably be better as there shouldn't be any issues with RTL

**Comment by infograf768** [comment]
> In general, using a list would probably be better as the RTL should kick in automatically.

I do prefer `ul` in general as they are easier to cope with and we do not need flex at all in this case.
Still needs some tweaks for RTL concerning com_media.

Look here the non-minified css file obtained after my patch. At the bottom of the file are all the RTL overrides, including for infovue.
[mediamanager.min.css.zip](https://github.com/joomla/joomla-cms/files/2888572/mediamanager.min.css.zip)

**Comment by infograf768** [comment]
OK, I am told that it is better to use `<dl>` etc.
Will try to deal with rtl, using your patch.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7cbfa13a2775cfd24f74ec8ee77e3a0e11d04dd2<br /><br />OK for LTR. RTL is another story to be dealt with separately. Thanks.

One more tester please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23902">issues.joomla.org/tracker/joomla-cms/23902</a>.</sub>

**Comment by infograf768** [comment]
@C-Lodder 
Please confirm test.

**Comment by Razzo1987** [comment]
For me doesn't work :(

screen shot 2019-02-26 at 09 17 23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23902">issues.joomla.org/tracker/joomla-cms/23902</a>.</sub>

**Comment by infograf768** [comment]
@Razzo1987 
Have you ran npm ci on the test site?
If not, then the patch is not enough...

**Comment by Razzo1987** [comment]
Sotty, I didn't.

I understand now I miss this step on my tests. Now I'm redone it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23902">issues.joomla.org/tracker/joomla-cms/23902</a>.</sub>

**Comment by wilsonge** [comment]
Merged on JM's request. Thanks!

**Pull request merged**
