### PR TITLE
[4.0] Remove redundant id attribute

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Form fields generate ID based on their name. This removes id attribute if its value matches field name.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e5e78494717f187c90a87ec1ac1cd342d6fb32d3<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31303">issues.joomla.org/tracker/joomla-cms/31303</a>.</sub>

**Comment by brianteeman** [comment]
When was ID added. I dont remember seeing that before

**Comment by SharkyKZ** [comment]
Long time ago.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e5e78494717f187c90a87ec1ac1cd342d6fb32d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31303">issues.joomla.org/tracker/joomla-cms/31303</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31303">issues.joomla.org/tracker/joomla-cms/31303</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
