### PR TITLE
Fix the multiple instances bug for tinyMCE

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue reported https://github.com/joomla/joomla-cms/pull/12561#issuecomment-281817220 by @svenbluege .

### Summary of Changes
Multiple instances of tinyMCE fail to initialise correctly.

### Testing Instructions

Make sure that the default editor is tinyMCE

Edit `administrator/components/com_content/models/forms/article.xml` and add after 

``` xml
    <fieldset addfieldpath="/administrator/components/com_categories/models/fields" >
```

this:

``` xml
        <field
                name="test2"
                label ="Test Field"
                type="editor"
                width="300"
                filter="safehtml"
                editor="tinymce"
                buttons="true"/>
        <field
                name="test3"
                label ="Test Field"
                type="editor"
                width="300"
                filter="safehtml"
                editor="tinymce"
                buttons="true"/>
```

Edit `administrator/components/com_content/views/article/tmpl/edit.php` and add after

``` html
                <fieldset class="adminform">
                    <?php echo $this->form->getInput('articletext'); ?>
                </fieldset>
```

this:

``` html
                <fieldset class="adminform">
                    <?php echo $this->form->getInput('test2'); ?>
                </fieldset>
                <fieldset class="adminform">
                    <?php echo $this->form->getInput('test3'); ?>
                </fieldset>
```

### Documentation Changes Required

---
This change is [Reviewable](https://reviewable.io/reviews/joomla/joomla-cms/14194)

### CODE REVIEW

**Review by yvesh — APPROVED** [review]

**Comment by svenbluege** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/joomla/joomla-cms/14194)*

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6b7a3c723b3f664f20575e7940fb42c8040f8d70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14194">issues.joomla.org/tracker/joomla-cms/14194</a>.</sub>

**Comment by infograf768** [comment]
RTC thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14194">issues.joomla.org/tracker/joomla-cms/14194</a>.</sub>

**Comment by infograf768** [comment]
Folks, when testing, please do not only comment on `reviewable` but add your tests in the issue tracker. Thanks

**Pull request merged**
