### PR TITLE
[5.2] TinyMCE Accordion

### PR DESCRIPTION
**Pull request by brianteeman**
Since Joomla 5.0 we have shipped a version of tinyMCE that includes a plugin called accordion. However we never exposed it to our plugin so it was not available to use.

This PR remedies that.
New installs will see the accordion icon on the toolbar with the list icons For existing installs you will need to EITHER drag the icon into the toolbar in the plugin configuration OR if you havent changed the toolbar you can use the clear and the the use advanced preset buttons.

Technically tinymce have misnamed the the plugin as it should not be confused with other accordion functionality such as the js based solution that can be enabled with bootstrap.

This plugin implements the native html details/summary disclosure element which requires no javascript and is accessible out of the box.

## To test
As this requires a js change either apply the pr and run `nmp ci` or use one of the prebuilt packages

If it is a new install then the icon will now be able in the toolbar. If it is an upgrade then you will need to use the tinymce plugin editor to add it (as described above)

## Demo Usage
accordion

## Notes
1. It is a known issue in with tinymce that currently the only way to _exit_ the accordion is to use the arrow keys to navigate out of the details/summary https://github.com/tinymce/tinymce/issues/8890
2. You can quickly create an accordion by highlighting a line of text and pressing the accordion button. This will convert the text into the details part

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
could someone please tag this as feature

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on ff21e79817326a0afff39c0e780ac2ebc62fa25a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43577">issues.joomla.org/tracker/joomla-cms/43577</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ff21e79817326a0afff39c0e780ac2ebc62fa25a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43577">issues.joomla.org/tracker/joomla-cms/43577</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43577">issues.joomla.org/tracker/joomla-cms/43577</a>.</sub>

**Comment by pe7er** [comment]
Thanks @brianteeman !

**Pull request merged**
