### PR TITLE
[4.0] Language overrides string

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes typo in string name

To test view source on the list limit selector and see that the label is translated or code review

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e20d125eeb466a62ebaa12681ddb36f79d3e42ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28185">issues.joomla.org/tracker/joomla-cms/28185</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e20d125eeb466a62ebaa12681ddb36f79d3e42ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28185">issues.joomla.org/tracker/joomla-cms/28185</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28185">issues.joomla.org/tracker/joomla-cms/28185</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
ta

**Pull request merged**
