### PR TITLE
[5.2][Events] Use event classes for Editors and editor buttons plugins

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Update `editors` and `editors-xtd` plugins to use `SubscriberInterface` and event classes.

### Testing Instructions

Check editor `None` works as before.
Check the editor buttons, they should work as before.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/97
- [ ] No documentation changes for manual.joomla.org needed

References:
- https://github.com/joomla/joomla-cms/pull/40082

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 0d07fe43f902ff37728fe331901b01dbcddd4bab<br /><br />I have tested this successfully.

( I tested ALL of the buttons for the CodeMirror and TinyMCE editors ).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43635">issues.joomla.org/tracker/joomla-cms/43635</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0d07fe43f902ff37728fe331901b01dbcddd4bab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43635">issues.joomla.org/tracker/joomla-cms/43635</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43635">issues.joomla.org/tracker/joomla-cms/43635</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for your contribution, @Fedik!

**Pull request merged**
