### PR TITLE
[4.x] codestyle xml

### PR DESCRIPTION
**Pull request by brianteeman**
simple code style correction. code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7d4b15cd35332c2f5b38b0ec04b87f5e50c3a210<br /><br />By code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37391">issues.joomla.org/tracker/joomla-cms/37391</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7d4b15cd35332c2f5b38b0ec04b87f5e50c3a210<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37391">issues.joomla.org/tracker/joomla-cms/37391</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37391">issues.joomla.org/tracker/joomla-cms/37391</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
