### PR TITLE
Menu items manager: Search Tools should not propose Archived as status

### PR DESCRIPTION
**Pull request by infograf768**
Menu Items can't be set to "Archived" but searchtools uses the generic status field type.
This PR creates a new custom field for com_menus without the Archived status when selecting a status in the dropdown.

To test, just display  Menu Manager: Menu Items => SearchTools=>Select Status

After patch, you should get:
screen shot 2015-04-04 at 17 47 06

### CODE REVIEW

**Comment by fontanil** [comment]
@test: patch works for me, thanks!

**Comment by rdeutz** [comment]
The new field isn't necessary because you can filter the status filed see #6003 for how you can do it

**Comment by infograf768** [comment]
Thanks Robert!
Changed:
https://github.com/joomla/joomla-cms/commit/9a135856f5d1ebd5d101227d01f54d2ddda32272
But looks like we have an issue with github as this push does not show here for now

**Comment by Bakual** [comment]
Closing/Reopening did sync it. Strange thing.

**Comment by bertmert** [comment]
@test Success

**Comment by phproberto** [comment]
Works great here. Merging :+1:

**Pull request closed without merging**
