### PR TITLE
Joomla Debug Console Improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds some visual and informative improvements to the Joomla Debug Console.
##### Before PR (Database Queries -> "Call stack" slider)

before-callstack
##### After PR (Database Queries -> "Call stack" slider)

after-callstack
##### Before PR (Log Messages)

before-logmessages
##### After PR (Log Messages)

after-logmessages
#### How to test
1. Apply this patch.
2. Turn on the debug in global config and enable the debug system plugin.
3. Test any page in frontend or administrator and check the "Joomla Debug Console" in the bottom of the page.
4. Verify the info and visual of "Database Queries" -> "Call stack" slider
5. Verify the info and visual of "Log Messages"
#### Observations

Suggestions and improvements are welcome.

### CODE REVIEW

**Comment by photodude** [comment]
:+1: I'll see if I can test this soon.

**Comment by photodude** [comment]
Would be nice if the "visual and informative improvements" also applied to the debug session info

**Comment by photodude** [comment]
I have tested this item :white_check_mark: successfully on 7fcc15af14c9d0744502a698593f5b51b180a093<br /><br />Definitely a valuable improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8899">issues.joomla.org/joomla-cms/8899</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@photodude 
> Would be nice if the "visual and informative improvements" also applied to the debug session info

I can change it to pretty print the session json values? ok for you? or are you referring to something else?

**Comment by watchfulli-dev** [comment]
@test success, applied the patch and indeed better layout now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8899">issues.joomla.org/joomla-cms/8899</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@watchfulli-dev please mark as tested https://issues.joomla.org/tracker/joomla-cms/8899 (after login the Test button appears). See https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by watchfulli-dev** [comment]
I have tested this item :white_check_mark: successfully on 7fcc15af14c9d0744502a698593f5b51b180a093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8899">issues.joomla.org/joomla-cms/8899</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@mbabker in this PR i did some changes in JLogEntry class so it can save the debug backtrace.
I need to made a PR to the log framework repository too, right?

**Comment by mbabker** [comment]
Don't bother.  The Framework's Log library is deprecated and all but abandoned at this point.  We typehint the PSR-3 logging interface in the Framework where packages support logging and the consensus at the time was Monolog is exponentially better so we weren't rewriting our code to support the interface.

**Comment by andrepereiradasilva** [comment]
ok thanks.

**Comment by photodude** [comment]
@andrepereiradasilva Yes, something like pretty-print the session json values. Anything would likely look better than the raw JSON values.

**Comment by andrepereiradasilva** [comment]
Done, can you test the session part now?

**Comment by alikon** [comment]
+ session
+ call stack
- Log messages
 gives different result items

**Comment by andrepereiradasilva** [comment]
@alikon thanks for the testing
"**ok** Log messages" now?

**Comment by alikon** [comment]
if we can have a subtotal for each logged category messages (not only for deprecated) should be OK
test administration plugins system debug

**Comment by andrepereiradasilva** [comment]
Joomla core has a LOT of deprecated messages .... :worried:

What we can do is making tabs there for type of messages and with the totals
ex: CRITICAL xx || WARNING xx || INFO xx || DEBUG xx

I think the deprecated warning should stay alone.

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on f2244359861ce742c104911fecfc1eade2e0c632<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8899">issues.joomla.org/joomla-cms/8899</a>.</sub>

**Comment by photodude** [comment]
I have tested this item :white_check_mark: successfully on f2244359861ce742c104911fecfc1eade2e0c632<br /><br />I do agree that we should have a summary subtotal for each logged category in the log section.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8899">issues.joomla.org/joomla-cms/8899</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Ok. i will try do that in other PR.
This on has already lot of changes and is RTC.

**Comment by dgt41** [comment]
RTC then it is!

**Comment by wilsonge** [comment]
Merged - thanks @andrepereiradasilva

**Pull request closed without merging**
