### PR TITLE
[4] add autocomplete and required attributes to username/password fields

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

add autocomplete and required attributes to username/password fields in the Joomla update process 

### Testing Instructions

Upgrade Joomla, checking the username and password fields before/after in the captive pages. 

### Actual result BEFORE applying this Pull Request

No required and autocomplete attributes.

### Expected result AFTER applying this Pull Request

Required and autocomplete attributes applied to fields. 

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
If I remember correctly it was deliberate not to have autocomplete

**Comment by PhilETaylor** [comment]
With the uprising of password managers, I no longer see a valid reason for it not to have them.

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 5c9f118274473cf62a15ae6badfbcd5a7664cfc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34140">issues.joomla.org/tracker/joomla-cms/34140</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5c9f118274473cf62a15ae6badfbcd5a7664cfc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34140">issues.joomla.org/tracker/joomla-cms/34140</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Possibly this decision was made at a time when not all browsers supported autocomplete in the right way? Do you know or remember any details?

**Comment by richard67** [comment]
Assuming that all browser supported by J4 support autocomplete, I set this RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34140">issues.joomla.org/tracker/joomla-cms/34140</a>.</sub>

**Comment by brianteeman** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

**Comment by richard67** [comment]
Back to pending until discussed with SST. Thanks @brianteeman for the links.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34140">issues.joomla.org/tracker/joomla-cms/34140</a>.</sub>

**Comment by PhilETaylor** [comment]
But yet the login for uses autocomplete and password auto fill /fail

Can't have it both ways!

**Comment by richard67** [comment]
@brianteeman When following your link, I read:

> For this reason, many modern browsers do not support autocomplete="off" for login fields
...
> The  browser still offers to remember this login.

All in all the article describes how to disable the autofill property and that this can be a bit tricky, and so not providing it doesn't necessarily mean it is disabled for all browsers, and so I think this PR doesn't do any harm but fixes it by providing the correct hint to the browser.

**Comment by richard67** [comment]
RTC again. Final decision takes the one who reviews again and merges.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34140">issues.joomla.org/tracker/joomla-cms/34140</a>.</sub>

**Comment by brianteeman** [comment]
> If I remember correctly it was deliberate not to have autocomplete

I found the reason in the history and it was raised by many people - however it does not apply here

**Comment by richard67** [comment]
Thanks for checking and reporting back.

**Review by Stuartemk — APPROVED** [review]

**Pull request merged**
