### PR TITLE
Wrong permission to know whether or not you can save an article in a category

### PR DESCRIPTION
**Pull request by carlitorweb**
Pull Request for Issue #20317

### Steps to reproduce the issue
- Create 2 categories, as for example, CAT1 and CAT2. 
- Create a user, as for example USER1, can enter and make login in the admin section, and enter to the com_content. (For this, you can go to global config and put the group **Registered** with the _Administrator Login_ permission allowed. Then, go to the config of com_content, and put the group **Author** with the _Access Administration Interface_ permission and _Edit Own_ allowed. Then, assign the user to the group **Author**. Note that only these permission settings should be set in both groups)
- Then go to the permissions for CAT1 and put the group **Author** can **Create** and **Edit Own**. After saving, the user will can create and edit his own articles in this category.
- Then go to CAT2 and put the group **Author** can **Create**. After saving, then the user can only create articles in this category. 

After having this, USER1 will can create his own articles inside CAT1, and when he finished, can "send" the article to CAT2.

### Expected result
The user will have the option to "send" the article to CAT2.

### Actual result
The CAT2 category does not show inside the list of category available for this user when editing the article.

### System information (as much as possible)
3.8.7

### Additional comments
If you go to `administrator\components\com_categories\models\fields\categoryedit.php` on line 277 you will see there is a check, where the user need have `core.edit.state` access for the CAT2 can show up inside the list of available categories for this user when editing the article. But even, if you put this access inside the CAT2, still no show. You need put this access inside the config of com_content for the CAT2 can show up.

I think a user having `core.create` access for CAT2 it is a sufficient requirement so that the user can have this category listed, within the categories available for creating an article, and in this way, "send" the article to CAT2.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by mqueme** [comment]
Tested this on current staging successfully. I can now see all available categories for that user.

**Comment by ghost** [comment]
@mqueme please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/20318)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by ghost** [comment]
altered Test by @mqueme at Issue Tracker.

**Comment by carlitorweb** [comment]
Does someone have an feedback about this thought? If is not correct to close it.

**Comment by ghost** [comment]
Any Comment by Maintainers on Question above by @carlitorweb?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20318">issues.joomla.org/tracker/joomla-cms/20318</a>.</sub>

**Comment by ghost** [comment]
@HLeithner can you please decide?

**Comment by ghost** [comment]
closed due the lack of response. @carlitorweb thanks for your work.

**Comment by carlitorweb** [comment]
Ok :(

**Pull request closed without merging**
