### PR TITLE
[4.2] lang string

### PR DESCRIPTION
**Pull request by brianteeman**
Small tweak to this language string as can be seen in the changes to remove a slight ambiguity when you use the word also

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 59f2b22db45fda64da4c864e5d22d5e172dd64e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39923">issues.joomla.org/tracker/joomla-cms/39923</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 59f2b22db45fda64da4c864e5d22d5e172dd64e1<br /><br />Tested successfully in Joomla 4.2.9-dev of 26 February.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39923">issues.joomla.org/tracker/joomla-cms/39923</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39923">issues.joomla.org/tracker/joomla-cms/39923</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you!

**Pull request merged**
