### PR TITLE
[4.0] Fix subform fields

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for comment: https://github.com/joomla/joomla-cms/pull/28695#issuecomment-617430650

### Summary of Changes

Fixes an error thrown in subform fields when trying to add new rows

### Testing Instructions

1. Go to: **Global Configuration** > **Users** > **Email Domain Options**
2. Click the "+" button
3. Click nested "+" buttons
4. Click the "-" button

### Expected result

No errors thrown

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9c9c703054aa1cf6385f3903a2e4956c190eb953<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28753">issues.joomla.org/tracker/joomla-cms/28753</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9c9c703054aa1cf6385f3903a2e4956c190eb953<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28753">issues.joomla.org/tracker/joomla-cms/28753</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28753">issues.joomla.org/tracker/joomla-cms/28753</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
