### PR TITLE
Code cleanup: remove setFieldAttribute('catid', 'action', …)

### PR DESCRIPTION
**Pull request by nhusung**
### Summary of Changes

Since the introduction of the categoryedit form field in the edit models/views of com_content, com_contact, com_newsfeeds and com_banners (joomla/joomla-cms@d6673d7), there is no `action` attribute on the `catid` form field and thus no need to set it anymore.

Furthermore cleanups concerning the `$id` in `ContentModelArticle::getForm()` are performed. As the
`getState('article.id')` method returns the correct article id, no matter whether in frontend or backend, and seems to be the standard way of retrieving the article id, there is no need to fetch it from the `CMSApplication`'s input.

### Testing Instructions

As the changes are pretty small, a code review should be enough. However you can have a look at the category field inside the edit forms of com_content, com_contact, com_newsfeeds and com_banners with users associated to different groups and access levels and privileges.

### Expected results

Same as before this pull

### CODE REVIEW

**Comment by nhusung** [comment]
As far as I know, many extensions developers use `com_content` as a template for their components. In order to stop developers from copying the unnecessary lines as fast as possible I decided to create a pull request on the staging branch. However, I started to wonder whether this is the correct place to put code cleanups (anyway it would not be merged into the 4.0-dev branch, would it?). That is why I created another pull request #24329.

**Comment by ghost** [comment]
@HLeithner any Comment as Release Lead?

**Comment by HLeithner** [comment]
We need at least 2 tests and better testing instructions, also the merge conflict must be solved.

**Comment by ghost** [comment]
@nhusung please give clear test instructions and resolve the conflicting files, thanks.

**Comment by nhusung** [comment]
While I resolved the conflicts I tried hard to remove big parts the following code (as `$form->setFieldAttribute('catid', 'action', '…')` is not needed):

https://github.com/joomla/joomla-cms/blob/30a4833accd64d7c044bb10568e271bcafaf248c/administrator/components/com_content/models/article.php#L392-L420

However, I’m not a hundred percent sure what @infograf768 intended in his last two commits (#24216 and #24640). To me it seems like issue #23991 occurs when a user with no edit.state permission on an already published article tries to change the article’s category. So why do we check for `$id == 0 && !$user->authorise('core.edit.state', 'com_content')`? If I’m not mistaking, this check is not relevant anyway. We already tested that `$this->getState('article.id')` is not `0` above. Furthermore, I’d like to question the `$app->isClient('…')` check. Couldn’t someone theoretically have permissions to view the article in backend but not to edit its state?

**Comment by nhusung** [comment]
I could confirm my second concern (https://github.com/joomla/joomla-cms/pull/24150#issuecomment-486733925) so I just corrected it.

**Comment by HLeithner** [comment]
@nhusung I tought about this pr again, we shouldn't do PRs in J3 that could delay the work in j4. So please check if this code is still in j4 and if so please rebase on j4-dev branch.

**Comment by nhusung** [comment]
@HLeithner yes, the `setFieldAttribute('catid', 'action', '…')` lines are still present in J4. I already created https://github.com/joomla/joomla-cms/pull/24329 which simply removes them. Sorry for the bad testing instructions but this is my first pull request ever and I was not quite sure what instructions to give when it can be verified from reviewing the code that the it does not do anything at all. Should I close this PR now?

**Comment by HLeithner** [comment]
thx and don't worry.

**Pull request closed without merging**
