### PR TITLE
Simplify for loop in articles model

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Just a small code improvement: Use foreach instead of a complex for loop (so we always use the correct key)

### Testing Instructions
The backend articles view should work exactly the same before and after the patch

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on bab49509ba290ccc2359a07748863a3354315eb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15363">issues.joomla.org/tracker/joomla-cms/15363</a>.</sub>

**Comment by rdeutz** [comment]
I have tested this item :red_circle: unsuccessfully on bab49509ba290ccc2359a07748863a3354315eb7<br /><br />That will not work and is not a really good change:

1) foreach makes a copy of the array so after the change we will use more memory
2) because foreach makes a copy unset has not effect on the original array<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15363">issues.joomla.org/tracker/joomla-cms/15363</a>.</sub>

**Comment by Bakual** [comment]
`foreach ($items as $x => &$item)` should solve the issue with the copy (from memory, not tested).

**Comment by bembelimen** [comment]
I did not change the unset line. It is still executed on the original variable, so no need for a reference...

**Comment by bembelimen** [comment]
Additional now we are sure, that the key is the correct one. In the old version we guessed the key

**Comment by rdeutz** [comment]
ah now I see what you are doing, but then I would do it different

foreach (array_keys($items) as $key)  ....

**Comment by franz-wohlkoenig** [comment]
@bembelimen how to go on with this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15363">issues.joomla.org/tracker/joomla-cms/15363</a>.</sub>

**Comment by bembelimen** [comment]
Updated

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8a4b5eebffd1252a1b8bee57f10a88009398528b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15363">issues.joomla.org/tracker/joomla-cms/15363</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 8a4b5eebffd1252a1b8bee57f10a88009398528b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15363">issues.joomla.org/tracker/joomla-cms/15363</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
