### PR TITLE
[4.4] com_tags extra parent_id query var

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

`parent_id` query var is not stripped for the same view=tags menu item 

### Testing Instructions

1. Create a menu item of 'Tags > List All Tags' type, select 'Root' in 'Parent_tag'.
2. Ensure that you have any tags and tagged articles.
3. Enable 'Show Tags' in any article menu item, click tag to access tag-specific page (`option=com_tags&view=tag`)
4. Ensure that you have breadcrumbs displayed, see the menu item from p.1 with extra `parent_id` query params like https://site.com/tags?parent_id=1

### Actual result BEFORE applying this Pull Request

Useless `parent_id` query var exists in the URL.

### Expected result AFTER applying this Pull Request

`parent_id` query var is stripped if the menu item has the same `parent_id`

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on da700a079428c1c68f6f9c85ec3e8a9dccf54397<br /><br />I tested in 5.0.0-beta3-dev but I think the result is good for 4.x. Tricky to follow the instructions - made my head spin. Any way, in my two menu items with the patch applied I see `http://localhost/joomla-cms5/index.php/test-41926` for a List All Tags menu item type and `http://localhost/joomla-cms5/index.php/article-test-41296` for a Single article menu item type. Without the patch the first is `http://localhost/joomla-cms5/index.php/test-41926?parent_id=1`
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41296">issues.joomla.org/tracker/joomla-cms/41296</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da700a079428c1c68f6f9c85ec3e8a9dccf54397<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41296">issues.joomla.org/tracker/joomla-cms/41296</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41296">issues.joomla.org/tracker/joomla-cms/41296</a>.</sub>

**Pull request merged**
