### PR TITLE
Code Style - "default_address"

### PR DESCRIPTION
**Pull request by LLNet**
- "br" outside of php print
- removed not logical if
- add tabs (\t)
- remove space in ends of html tag

### CODE REVIEW

**Comment by dam-man** [comment]
Can you add some testing information to reproduce or see how this is showing up. 
At this moment it is a bit hard to test this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by pjasmits** [comment]
I have tested this item :white_check_mark: successfully on 7d5bcae8c6a4f463c3e28fcb91161acc9b1f57fb<br /><br />Code cleaning according to given issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by zero-24** [comment]
@LLNet can you sync back to staging to fix the conflicts? Thanks.

**Comment by w13ear** [comment]
Hello @LLNet

Thank you for your contribution.

The last comment here was on [date]. So the question is, Is this issue/pull request still valid?
if so please provide clear test instructions to be able to test / reproduce this issue.
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by brianteeman** [comment]
This PR is still valid.
It addresses several things although they are mainly just code style (moving the br from the php statement)
It also ensures valid markup by preventing having a definition list that doesnt define its terms<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by w13ear** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by AnneKlapwijk** [comment]
I have tested this item :white_check_mark: successfully on 7d5bcae8c6a4f463c3e28fcb91161acc9b1f57fb<br /><br />The code looks a lot cleaner. 
I see no changes in the front-end.

Tested with the testing sample data in /index.php/single-contact<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4828">issues.joomla.org/joomla-cms/4828</a>.</sub>

**Comment by rdeutz** [comment]
@LLNet could you have a look at the merge conflicts, thanks.

**Comment by rdeutz** [comment]
I close this one here in favor of #9941

**Pull request closed without merging**
