### PR TITLE
replace float-end by float-md-end

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #40621 .

### Summary of Changes

This PR will prevent the the element with className `com-content-category-blog__counter` be shown behind the pagination. It will get float-end on breakpoint md. 

### Testing Instructions

- Joomla with blog sample data
- Make sure to copy blog content items so you have a pagination with a lot of pages 
- Reduce the viewport from desktop to mobile

### Actual result BEFORE applying this Pull Request

The counter is behind the pagination as shown in the issue #40621

### Expected result AFTER applying this Pull Request

The counter does not have a float and will be shown above the pagination

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bdff3bafa35eedf406870c1109d7d6a9f6051f24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40623">issues.joomla.org/tracker/joomla-cms/40623</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bdff3bafa35eedf406870c1109d7d6a9f6051f24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40623">issues.joomla.org/tracker/joomla-cms/40623</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40623">issues.joomla.org/tracker/joomla-cms/40623</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
