### PR TITLE
[4.0] dropdown menu duplicate css

### PR DESCRIPTION
**Pull request by brianteeman**
the class .dropdown-menu in _header.scss is repeated with conflicting values. This Pr combines the two classes. There will be no visible difference to the display of the dropdown mnu as this is just removing code which is over ridden.

PR for #27639

The class is used for the user menu 
image

Dont forget npm i or node build.js --compile-css

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d961505666646051884bda68277d91746de4558d<br /><br />Code review + visual test + element inspection in developer tools: All fine. Min-width is 18rem, z-index is 1060.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27661">issues.joomla.org/tracker/joomla-cms/27661</a>.</sub>

**Comment by richard67** [comment]
P.S.: And no conflicts shown in element inspection in developer tools for that element, while without this PR there are some.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d961505666646051884bda68277d91746de4558d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27661">issues.joomla.org/tracker/joomla-cms/27661</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27661">issues.joomla.org/tracker/joomla-cms/27661</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
