### PR TITLE
[4.0][Atum] Some searchtool fixes

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/28615#issuecomment-612354012 .

### Summary of Changes
Fixes some layout issues on com_menu and com_assosiations. 

### Testing Instructions
Apply this patch and run `node build.js --compile-css ` for updating the changed SCSS. Check searchtools are displaying correctly.

@infograf768

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on dff34bc34896a3515243b3dc18a069c4757ca7e2<br /><br />Yes, now is inline
immagine

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28644">issues.joomla.org/tracker/joomla-cms/28644</a>.</sub>

**Comment by richard67** [comment]
@ciar4n The clear button still has same color as the filter options button when a filter is applied. Was the 2nd thing which @infograf768 remarked in his comment in the other PR. Should that be fixed here, too? The inline display of the filter options is ok now, as the previlus tester remarked.

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on dff34bc34896a3515243b3dc18a069c4757ca7e2<br /><br />with the patch I have the voices horizontally.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28644">issues.joomla.org/tracker/joomla-cms/28644</a>.</sub>

**Comment by ciar4n** [comment]
@richard67 Thx. Yes that can be added here. Color added to clear button with https://github.com/joomla/joomla-cms/pull/28644/commits/1700a922d9e5e6b5633c987d77544ec5122d8a6c

image

**Comment by richard67** [comment]
Will test in a few minutes. @Razzo1987 Could you test again? This time not only if the search filter drop downs are properly inlined but also if the color of the "Clear" button for the filter is like shown in the [previous comment](https://github.com/joomla/joomla-cms/pull/28644#issuecomment-612498756)? Thanks in advance.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1700a922d9e5e6b5633c987d77544ec5122d8a6c<br /><br />Both of the issue mentioned in https://github.com/joomla/joomla-cms/pull/28615#issuecomment-612354012 are fixed now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28644">issues.joomla.org/tracker/joomla-cms/28644</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1700a922d9e5e6b5633c987d77544ec5122d8a6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28644">issues.joomla.org/tracker/joomla-cms/28644</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28644">issues.joomla.org/tracker/joomla-cms/28644</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
