### PR TITLE
[3.7.4] Falang database driver can't handle ->select('1')

### PR DESCRIPTION
**Pull request by olleharstedt**
### Summary of Changes

As title.

### CODE REVIEW

**Comment by olleharstedt** [comment]
I've notified Falang about this issue.

**Comment by Bakual** [comment]
Using `count()` would need a GROUP statetement as well. But it looks useless anyway to run count when we don't need to count the rows.

That is something which Falang should fix as the core code is perfectly fine.

**Comment by olleharstedt** [comment]
Using `1 AS x` is another way to fix this issue, instead of `COUNT(*)`.

**Comment by Bakual** [comment]
I still think it's a bug in Falang which they need to fix.

**Comment by olleharstedt** [comment]
I agree. Just saying, we won't be able to upgrade until either Falang or Joomla has changed. Or we make our own fork.

**Comment by franz-wohlkoenig** [comment]
@olleharstedt can you please close this Issue if its not a Core Issue?

**Comment by olleharstedt** [comment]
The following piece of code works differently in PHP 7 and PHP 5:

```php
$mysqli = mysqli_connect("localhost", "root", "", "mydatabase");
$res = mysqli_query($mysqli, "select 1");
$row = mysqli_fetch_object($res);
var_dump($row);
```

In PHP 7 it will dump

```
object(stdClass)#3 (1) {
  [1]=>
  string(1) "1"
}
```

but in PHP 5

```
object(stdClass)#3 (0) {
}
```

Therefore I think the PR is motivated. Maybe it can be changed to `select('id')` instead of `select('COUNT(*)')` (only cosmetic change).

**Comment by sbouey** [comment]
To complete this case.

Joomla don't see the problem because the loadResult work fine with select('1) but the loadObject don't work fine.
Falang use loadObject during the database override.

There are 2 file to change and replace for the check method
select('1')
by
libraries/joomla/table/asset.php line 109
->select($this->_db->quoteName('id'))


libraries/joomla/table/nested.php line 694
select($this->_db->quoteName($this->_tbl_key)) 

libraries/joomla/table/nested.php line 997
select($key)

**Comment by alikon** [comment]
did'nt experienced php 5 vs php 7 different behaviour
can you test with `mysqli_fetch_row` instead of `mysqli_fetch_object`  in your posted https://github.com/joomla/joomla-cms/pull/17003#issuecomment-314710804 test code ?

..despite i think should be fixed on falang side...
we simply should avoid `SELECT COUNT(*)` when not needed

**Comment by sbouey** [comment]
With  mysqli_fetch_row it's work but in Joomla if you change in the assets.php check method 

if ($this->_db->setQuery($query, 0, 1)->loadResult())
by
if ($this->_db->setQuery($query, 0, 1)->loadObject())
this will not work on php 5.5 , 5.6

Falang use loadobject for all it's why there are a problem since the last Joomla version.

the change of the query 
libraries/joomla/table/asset.php line 109
 ->select($this->_db->quoteName('id'))

fix the problem on falang , it's not a Joomla bug because Joomla use loadResult.

Stéphane

**Comment by olleharstedt** [comment]
NB: `SELECT COUNT(*)` has no performance hit in this case, since it's always returning 0 or 1 row. `SELECT id` would work just as well, too.

**Comment by alikon** [comment]
even if there are no performance issues, using `count(*)` is wrong imho we are asking for existence and not asking how many items there are

**Comment by sbouey** [comment]
Select (id) will work and it's a workaround for MySQL bug. no performance problem.

**Comment by alikon** [comment]
there is no MySQL bug nor Joomla bug

**Comment by sbouey** [comment]
look at the @olleharstedt  message and try this
with php 5.6 and php 7.0

$mysqli = mysqli_connect("localhost", "root", "", "mydatabase");
$res = mysqli_query($mysqli, "select 1");
$row = mysqli_fetch_object($res);
var_dump($row);

The result is not the same with an empty object for php 5

**Comment by alikon** [comment]
maybe this  can help https://bugs.php.net/bug.php?id=72151

**Comment by sbouey** [comment]
The change proposed by olleharstedt don't affect performance and fix the prolem on Falang with php 5.
No problem with php 7

**Comment by brianteeman** [comment]
I am closing this as not a Joomla core issue.

**Pull request closed without merging**
