### PR TITLE
[4.1] Set 'secure' flag in session cookies if TLS in enforced

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Pass the $options array, holding the information if the secure flag shall be set, in the session service provider to the JoomlaStorage class.

### Testing Instructions
Log in to your backend, switch Force SSL in the global config to true.

### Actual result BEFORE applying this Pull Request
secure flag is missing in the backend and frontend session cookie

### Expected result AFTER applying this Pull Request
secure flag is set

### Documentation Changes Required
-

### CODE REVIEW

**Comment by sandewt** [comment]
array(3) { ["name"]=> string(32) "4129b0b40bbcb51091c437390b26f476" ["expire"]=> int(900) ["force_ssl"]=> bool(true) } 

How can I best check this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37777">issues.joomla.org/tracker/joomla-cms/37777</a>.</sub>

**Comment by SniperSister** [comment]
@sandewt you can use the developer tools in your browser to inspect the cookies set by the site. Those tools show if the secure flag is set or not

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0c63a7a92e6a9af04150d1bb2010c276090bb26<br /><br />Without the patch, the "secure" flag is always false in the session cookies for the administrator and the site, regardless of the "Force HTTPS" setting in Global Configuration.

With the patch, the "secure" is set depending on the "Force HTTPS" setting.
- "None": False for both the admin and the site session cookie.
- "Administrator Only": True for the admin and false for the site session cookie.
- "Entire Site": True for both the admin and the site session cookie.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37777">issues.joomla.org/tracker/joomla-cms/37777</a>.</sub>

**Comment by richard67** [comment]
@sandewt Here some details where to find the cookies in the developer tools in Firefox, Google Chrome and Microsoft Edge.

### Firefox

1. Get to the developer tools
2022-05-13_devtools-firefox_1

2. Get to the cookies in the storage tab
2022-05-13_devtools-firefox_2

### Google Chrome and Microsoft Edge

In Edge, the hot key combination to get the dev tools is different to Google Chrome, but the navigation to get there and the tabs of the dev tools are the same.

1. Get to the developer tools
2022-05-13_devtools-chrome_1

2. Get to the cookies in the application tab
2022-05-13_devtools-chrome_2

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on a0c63a7a92e6a9af04150d1bb2010c276090bb26<br /><br />thanks @SniperSister <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37777">issues.joomla.org/tracker/joomla-cms/37777</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37777">issues.joomla.org/tracker/joomla-cms/37777</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by sandewt** [comment]
Thanks

**Comment by PhilETaylor** [comment]
As reported to the JSST on 8th September 2021 at 21:17GMT with the solution being passed to the JSST at 21:30 GMT to be implemented by the JSST... .and then ignored until this PR in pubic...


Screen Shot 2022-05-15 at 18 55 46

**Comment by PhilETaylor** [comment]
This should also have a CVE assigned as its listed in the CWD https://cwe.mitre.org/data/definitions/614.html

**Comment by PhilETaylor** [comment]
> The Joomla! project will properly credit individuals and/or organizations who responsibly disclose security issues to the JSST [[quote](https://developer.joomla.org/security.html)]

As reported to the JSST on 8th September 2021 at 21:17GMT with the solution being passed to the JSST at 21:30 GMT to be implemented by the JSST... .and then ignored until this PR from the JSST Team Leader, in pubic.. 8 months later...

You're Welcome.

Phil, The... "rechthaberische, klugsch., selbstverliebte, arrogante Giftzwerge"...


This should also have a CVE assigned as its listed in the CWE https://cwe.mitre.org/data/definitions/614.html and is in the [OWASP Top Ten 2021 Category A05:2021](https://cwe.mitre.org/data/definitions/1349.html) - Security Misconfiguration

Screen Shot 2022-05-15 at 18 55 46

**Comment by PhilETaylor** [comment]
So I see I was ignored and 4.1.4 was released without a security release or CVE . Ok we’ll time to go public myself then if you are now slipping proven security fixes and calling them bug fixes.

**Pull request merged**
