### PR TITLE
Update to TinyMCE 4.1.7

### PR DESCRIPTION
**Pull request by wilsonge**
Changelog: http://www.tinymce.com/develop/changelog/index.php?ctrl=version&act=view&pr_id=1&vr_id=877

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
Thank you for updating the library, @wilsonge!

Should be merged for Joomla! 3.4 release!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5707">issues.joomla.org/joomla-cms/5707</a>.</sub>

**Comment by brianteeman** [comment]
@test Applied patch and tested that tinymce still works ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5707">issues.joomla.org/joomla-cms/5707</a>.</sub>

**Comment by zero-24** [comment]
Moving to RTC Thanks for testing and the code! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5707">issues.joomla.org/joomla-cms/5707</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @wilsonge for the PR and all other for testing!

**Pull request merged**
