### PR TITLE
[4.1] module shared session

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #35500

When you are using shared sessions the mod_logged module on the dashboard cannot determine if a user is logged in to the admin or the site.

Before this PR the **location** was left blank. With this PR the **location** displays "N/A

To test make sure that you have set shared sessions to on in the global config

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Maybe "Shared" would be better than "n/a" ?

**Comment by brianteeman** [comment]
The column name is location so no I dont think "shared" would be better

**Comment by brianteeman** [comment]
Another alternative would be to simply NOT show the location column if the shared session is set

**Comment by Quy** [comment]
Or "Both". Under Shared Sessions, maybe add description stating that the site logout function will not be available.

**Comment by brianteeman** [comment]
@Quy I understand the code why the logout button doesnt appear I am just wondering why it has been setup this way as this limitation was not present in j3.

**Comment by brianteeman** [comment]
Rebased to 4.1

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 047e666e133f03d54949b9d2d12ac9b4736f3032<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35732">issues.joomla.org/tracker/joomla-cms/35732</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 047e666e133f03d54949b9d2d12ac9b4736f3032<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35732">issues.joomla.org/tracker/joomla-cms/35732</a>.</sub>

**Comment by laoneo** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35732">issues.joomla.org/tracker/joomla-cms/35732</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
