### PR TITLE
Deprecating "new" MVC for 4.0 instead of 5.0

### PR DESCRIPTION
**Pull request by Hackwar**
This is an accompanying PR to #28365. The aim is to deprecate the "new" MVC classes for 4.0 instead of 5.0.

### CODE REVIEW

**Comment by brianteeman** [comment]
Surely it is too late for this. The version that will contain the deprecation notice is released on the same day

**Comment by richard67** [comment]
> Surely it is too late for this. The version that will contain the deprecation notice is released on the same day

@brianteeman That would be true if he wanted to add the deprecation notice to 3.10. But he wants to add it to staging.

**Comment by mbabker** [comment]
Just merge this and the companion pull request and be done with it already.  For the record, 3.9 has been full of semantic versioning violations so what's another one at this point, clearly the project only cares about following its development strategy when it is convenient for the project to do so.

I formally rescind all arguments against this change if it means people will pledge to focus on the other 2349078 tasks that have kept 4.0 in development hell for 5 years now.

**Comment by mbabker** [comment]
Given the creation of https://github.com/joomla-extensions/legacy-mvc (yay for more abandonware "core supported" extensions), this should be merged so developers might notice this deprecation now and not get bitten by the sudden removal in 4.0.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
