### PR TITLE
Make restore.php PHP 7.4 compatible

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #25800 .

### Summary of Changes
just extracted the work already done by  @SharkyKZ  in #25782 as a separate file as requested https://github.com/joomla/joomla-cms/issues/25800#issuecomment-519880534

### Testing Instructions
update joomla

### Expected result
update should work with any issue or/notice warning for 7.4

### Actual result

deprecation on php 7.4

###  To Do 
~~change the copyright information~~

### CODE REVIEW

**Comment by brianteeman** [comment]
The title says this PR is to make restore.php compatible with php7.4. Which implies that without this PR restore.php will not work with 7.4

Am I missing something here. I thought deprecated in 7.4 meant it will now generate a deprecation warning - which is not the same as not working.

PS 7.4 is not scheduled for release until Nov 28 iirc

**Comment by HLeithner** [comment]
A deprecation warning means more or less that the code should not longer be used and should be changed and depending of your error reporting this could lead to an upgrade joomla upgrade error if the json response adds deprecation notices.

That's the reason I choose the title in the original issue. As developer you should take deprecation warnings as serious as fatal errors because sooner or later they lead to a fatal error.

There is no reason to wait till php 7.4 is released to patching this syntax. The 7.4 will not be in 3.9.11 and 3.9.12 comes in September so people have 2-3 month before  php 7.4 is released and can update to have a nice working cms even on php 7.4.

**Comment by brianteeman** [comment]
>  As developer you should take deprecation warnings as serious as fatal errors because sooner or later they lead to a fatal error.

I guess that's not the policy here for our own code then as J3 has been using deprecaated code for a very very long time :)

**Comment by HLeithner** [comment]
> I guess that's not the policy here for our own code then as J3 has been using deprecaated code for a very very long time :)

We should mitigate this if possible... at least j4 should make it better at this front....

**Review by zero-24 — APPROVED** [review]

**Review by richard67 — APPROVED** [review]
I can't test without having a PHP 7.4, but code review is good.

**Comment by HLeithner** [comment]
Thanks for PHP 7.4 fix.

**Pull request merged**
