### PR TITLE
[4.0] fix typehint syntax & other comment issues

### PR DESCRIPTION
**Pull request by PhilETaylor**
- fix typehint syntax in single line comment to meet code standards 
 - fix multi line comment syntax
 - reindent docblock

### CODE REVIEW

**Comment by ceford** [comment]
Where to look for changes?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30091">issues.joomla.org/tracker/joomla-cms/30091</a>.</sub>

**Comment by PhilETaylor** [comment]
The only changes are comments - so just code review, nothing to test

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1d84059b825df2b90f0a12d8339757b7430223d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30091">issues.joomla.org/tracker/joomla-cms/30091</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1d84059b825df2b90f0a12d8339757b7430223d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30091">issues.joomla.org/tracker/joomla-cms/30091</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30091">issues.joomla.org/tracker/joomla-cms/30091</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
