### PR TITLE
[4.0] Clean the node modules in the media folder on install

### PR DESCRIPTION
**Pull request by laoneo**
Would be good if the node_modules folder get cleaned on install for the media manager. This pr changes the postinstall hook to use ci. This needs a version bumb in the min npm requirements.

### CODE REVIEW

**Comment by wilsonge** [comment]
@brianteeman Are you able to test what is the effect of this on a windows install?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2e7238e9de0ea84d1804013a272c5abb641dbb98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22860">issues.joomla.org/tracker/joomla-cms/22860</a>.</sub>

**Comment by brianteeman** [comment]
As requested I tested on windows. other than significantly increasing the install time (which is crazy under windows) it appeared to do what was expected

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2e7238e9de0ea84d1804013a272c5abb641dbb98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22860">issues.joomla.org/tracker/joomla-cms/22860</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22860">issues.joomla.org/tracker/joomla-cms/22860</a>.</sub>

**Comment by wilsonge** [comment]
Temporarily holding with this, because after this doing a double `npm ci` takes nearly 10 minutes on windows which is clearly not ok. In it's own right the PR is good. just need to see if there's anything we can do with windows

**Comment by wilsonge** [comment]
@rdeutz can we upgrade the version of npm on drone to version 6 (`npm@lts` ideally) so that we can actually run ci there please

**Comment by rdeutz** [comment]
sure will do over the Weekend

-- 
Viele Grüße/ Best Regards
Robert

**Comment by wilsonge** [comment]
Thanks :)

**Comment by rdeutz** [comment]
Done, composer and node updated to 11.x

**Comment by rdeutz** [comment]
I think you need to make a npm update, to update the bindings and add package-lock.json to the PR

**Comment by wilsonge** [comment]
Thanks @laoneo !

**Pull request merged**
