### PR TITLE
[4.0] Improve strings for adding an extra language

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Improves the language strings for installing an extra language. Now that we don't install sample data we don't need to call it customising. We can strictly call it installing extra languages.

### Testing Instructions
View strings in installer should be as below after patch

### Expected result
Screenshot 2020-04-11 at 18 33 19

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge Well it is not only installation of languages. At the end you also have to select default languages for site and admin. So that's some kind of customization. But I am ok with both, like it is and like it will be with this PR.

**Comment by brianteeman** [comment]
Two comments

1. Would it not be better as "Install Extra Languages" or "Install Additional Languages"

2. We still have the crazy situation that you have gone through the entire installation process in your own language eg french and then you get this message. Why would I even think to install another language - this is french. Except its not french its all in english as soon as you complete the installation. Other CMS either offer you a download in your language or ask you what language you want to be installed as PART of the process and not as an additional step after you have completed the install

**Comment by wilsonge** [comment]
> Would it not be better as "Install Extra Languages" or "Install Additional Languages"

Done

> We still have the crazy situation that you have gone through the entire installation process in your own language eg french and then you get this message. Why would I even think to install another language - this is french. Except its not french its all in english as soon as you complete the installation. Other CMS either offer you a download in your language or ask you what language you want to be installed as PART of the process and not as an additional step after you have completed the install

So I'm not the biggest fan either - but the reality is that our install language functionality depends on loading this data from the updates which requires a CMS install. I'd like to find a way to make it easier to install the language you're using in the installer (at minimum promote the language to the top of the list). But from a technical perspective at this moment in time I don't think we'll be able to move this to something that happens during the install UNLESS after the DB installation we artificially add a step before showing the success message.

**Comment by brianteeman** [comment]
As you and I are the only people who have ever raised a comment on this and we never install joomla in other languages I guess its not worth the time and effort to resolve that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28656">issues.joomla.org/tracker/joomla-cms/28656</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 52dadfd0cdd2903d7feea303227f4e9ff7c4e58a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28656">issues.joomla.org/tracker/joomla-cms/28656</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 52dadfd0cdd2903d7feea303227f4e9ff7c4e58a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28656">issues.joomla.org/tracker/joomla-cms/28656</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28656">issues.joomla.org/tracker/joomla-cms/28656</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
