### PR TITLE
[4.0] s/exits/exists

### PR DESCRIPTION
**Pull request by PhilETaylor**
Typo forked from https://github.com/joomla/joomla-cms/pull/35150 as it looks like that PR is going to be rejected and this typo fix needs to be implemented regardless.

Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c9fe81149bceab9dd24c7d4d8b36f1d980cbd191<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36256">issues.joomla.org/tracker/joomla-cms/36256</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c9fe81149bceab9dd24c7d4d8b36f1d980cbd191<br /><br />Three instances of exits changed to exists in doc blocks. OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36256">issues.joomla.org/tracker/joomla-cms/36256</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36256">issues.joomla.org/tracker/joomla-cms/36256</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on c9fe81149bceab9dd24c7d4d8b36f1d980cbd191<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36256">issues.joomla.org/tracker/joomla-cms/36256</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
