### PR TITLE
CodeMirror 5.16.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
#### Summary of Changes

CodeMirror is updated. Seems to be mainly bugfixes. http://codemirror.net/doc/releases.html
#### Testing Instructions

Just use codemirror and expect it to work normally.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for keeping us up to date<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10937">issues.joomla.org/joomla-cms/10937</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 76df473f9e759181cdbe78256d169acf1003c621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10937">issues.joomla.org/joomla-cms/10937</a>.</sub>

**Comment by nikitadhiman** [comment]
I have tested this item :white_check_mark: successfully on 76df473f9e759181cdbe78256d169acf1003c621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10937">issues.joomla.org/joomla-cms/10937</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10937">issues.joomla.org/joomla-cms/10937</a>.</sub>

**Pull request merged**
