### PR TITLE
[plg_captcha_recaptcha_invisible] Update language strings

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Adds periods at the end of field descriptions.

### Testing Instructions

Language review.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
language string changes approved

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 25416fc9d2af2da95c9546092189a3273bf96964<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22228">issues.joomla.org/tracker/joomla-cms/22228</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 25416fc9d2af2da95c9546092189a3273bf96964<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22228">issues.joomla.org/tracker/joomla-cms/22228</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22228">issues.joomla.org/tracker/joomla-cms/22228</a>.</sub>

**Comment by infograf768** [comment]
Thanks

**Pull request merged**
