### PR TITLE
[4] Cleanup of switch and remove unreachable code

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

Remove `break` which is unreachable after a `return`

Remove redundant `case` and `default`

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on a925116001418507a9d5a8e3e5eab4c8e7572e49<br /><br />Tested successfully in Beta7-dev of 15 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32036">issues.joomla.org/tracker/joomla-cms/32036</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a925116001418507a9d5a8e3e5eab4c8e7572e49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32036">issues.joomla.org/tracker/joomla-cms/32036</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32036">issues.joomla.org/tracker/joomla-cms/32036</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
