### PR TITLE
[6.0] breadcrumbs unused function

### PR DESCRIPTION
**Pull request by brianteeman**
Updated Pull Request for original PR #33913 .

### Summary of Changes
The setSeparator function has not been used in Joomla since the release of 4.0

### Testing Instructions
Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/346
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Would be nice to have that documented in https://github.com/joomla/Manual/blob/main/migrations/54-60/removed-backward-incompatibility.md.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on cf0a43cca25200425e790e8743aea189536f871d<br /><br />Prebuilt package used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44605">issues.joomla.org/tracker/joomla-cms/44605</a>.</sub>

**Comment by brianteeman** [comment]
> Would be nice to have that documented in https://github.com/joomla/Manual/blob/main/migrations/54-60/removed-backward-incompatibility.md.

done

**Review by laoneo — APPROVED** [review]

**Comment by alikon** [comment]
setting RTC cause it was successfully tested by @Quy too

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44605">issues.joomla.org/tracker/joomla-cms/44605</a>.</sub>

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on 2ca900c0339d61b93beb31236d77243aa2a82f9e<br /><br />function removed as documented<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44605">issues.joomla.org/tracker/joomla-cms/44605</a>.</sub>

**Pull request merged**
