### PR TITLE
[4.0] Add upload file size check to Extensions Installer Upload & Install Package

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue [https://github.com/joomla/joomla-cms/issues/27494#issuecomment-573425846](https://github.com/joomla/joomla-cms/issues/27494#issuecomment-573425846).

Requires PR #27570 for the language strings.

### Summary of Changes

This Pull Request (PR) adds a check if the selected file is too big to be uploaded with respect to the PHP limits to the "Upload & Install Package" tab of the Extensions Installer.

### Testing Instructions

~~Please wait with testing and reviews. I have to fix drag and drop.~~
**Fixed. Ready for reviews and tests.**

**Requirements:**
1. npm
2. PR #27570 for the language strings.

**Procedure:**
1. Apply patch of this PR and of PR #27570 .
2. Run `npm run build:js` (or `npm install` if you prefer this).
3. Clear browser cache to get rid of old cached JS.
4. Go to `administrator/index.php?option=com_installer&view=install` and there to tab "Upload Package File".
5. Drag to the drag and drop area a file which **is** too big compared to the maximum upload size shown below the file selection.
**Hint:** This can be any file, it doesn't necessarily have to be a valid extension package.
**Result:** See screenshot  in section "Expected result" below. A browser alert is shown telling that the file can't be uploaded because it's too big. The upload is not started.
6. Select a file which **is** too big, using the "Or browse for file" button.
**Result:** Same as in previous step. A browser alert is shown telling that the file can't be uploaded because it's too big.
7. Drag to the drag and drop area a file which is **not** too big compared to the maximum upload size shown below the file selection.
**Result:** Uploading of not too big package file using drag and drop still works as well as without this PR.
8. Finally select another package file which is **not** too big, using the "Or browse for file" button, and verify that uploading still works.
**Result:** Uploading of not too big package file using the "Or browse for file" button still works as well as without this PR.

### Expected result

Broswer alert when trying to upload too big file:
installer-file-too-big

### Actual result

See [https://github.com/joomla/joomla-cms/issues/27494#issuecomment-575888623](https://github.com/joomla/joomla-cms/issues/27494#issuecomment-575888623).

- If `post_max_size` is big enough but `upload_max_size` is violated:
j4_upload-max-filesize-violated_com-installer

- If `upload_max_size` is big enough but `post_max_size` is violated:
Nothing happens, and PHP error log shows: `PHP Warning: POST Content-Length of 22972015 bytes exceeds the limit of 16777216 bytes in Unknown on line 0, referer: ...` (with byte figures suitable to your test).

### Documentation Changes Required

Nothing special for this PR. The help screens for J4 backend have to be udpated anyway.

### CODE REVIEW

**Comment by richard67** [comment]
~~Please wait with testing and reviews. I have to fix drag and drop.~~
Fixed. Ready for reviews and tests.

**Comment by richard67** [comment]
PR is ready for reviews and tests now.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2d1e3d27668967b72be4235d2be7eb24479fe0da<br /><br />tested ok as long as the other pr is merged for the language strings<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27665">issues.joomla.org/tracker/joomla-cms/27665</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Again thanks a lot. I've updated the testing instructions to mention the dependency on the other PR.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2d1e3d27668967b72be4235d2be7eb24479fe0da<br /><br />With both PRs things are working as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27665">issues.joomla.org/tracker/joomla-cms/27665</a>.</sub>

**Comment by richard67** [comment]
@jwaisner Thanks for testing. Could you test PR #27570 , too?

**Comment by richard67** [comment]
We should wait with RTC until the other PR #27570 has RTC, too, or maybe even until that other one is merged, because this PR here depends on that other one.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27665">issues.joomla.org/tracker/joomla-cms/27665</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Please don't merge this without PR #27570 because this one here depends on that.

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
