### PR TITLE
[4.0] com_finder maps language note

### PR DESCRIPTION
**Pull request by brianteeman**
I won't pretend to understand what this note means ;)

This PR simply styles it better

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a0636c3955f28660038e4c3e7e71f4aea8812872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25562">issues.joomla.org/tracker/joomla-cms/25562</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0636c3955f28660038e4c3e7e71f4aea8812872<br /><br />Whatever this note is good for: With this PR it looks much better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25562">issues.joomla.org/tracker/joomla-cms/25562</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by Hackwar** [comment]
I'm tending to remove the language taxonomy in general...

**Pull request merged**
