### PR TITLE
[5.2] Remove useless string

### PR DESCRIPTION
**Pull request by brianteeman**
The code loads a joomla language string with two params The text string ignores the first param and just outputs the second with no additional data

In other words both the language string and the first param can be removed without any impact.

Pull Request for Issue #41233 

### Actual result BEFORE applying this Pull Request
image

image

### Expected result AFTER applying this Pull Request
image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a9cb0a73d5ef55e933db52ea6e82d61b0cfbb38d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42867">issues.joomla.org/tracker/joomla-cms/42867</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a9cb0a73d5ef55e933db52ea6e82d61b0cfbb38d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42867">issues.joomla.org/tracker/joomla-cms/42867</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42867">issues.joomla.org/tracker/joomla-cms/42867</a>.</sub>

**Comment by brianteeman** [comment]
Rebased to 5.1 in the hope this will get merged.

**Comment by brianteeman** [comment]
is there a reason that this RTC pr is not being merged?

**Comment by HLeithner** [comment]
@bembelimen any reason this to keep the language string? Don't think so but just want to ask if any language override can make sense here.

**Comment by brianteeman** [comment]
Closed due to lack of interest or response from release leads

**Pull request closed without merging**
