### PR TITLE
[4.0] [RFC] Simplify the admin menu

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

This is a response to my own comment https://github.com/joomla/joomla-cms/issues/15451#issuecomment-296236789
and a completely different approach from https://github.com/joomla/joomla-cms/issues/15536

Simplicity is the ultimate UX!

# THIS IS NOT STYLED PROPERLY YET!!!!

### Summary of Changes
The main idea is to remove a bunch of menus and provide a view for all of them.
Think for a moment all the operating systems that you use: Windows, MacOS, IOS, Android, all of them have a common view named control panel, system preferences or something similar and is the expected place where a user will do some tasks related to the system.
The same concept is applied to Joomla. Joomla update is not a daily task for no site! Ever! Also Joomla never released more than 6 releases in a year (so a site would have used update 6 times in a year). Thus this link **SHOULD NOT** be exposed as a directly accessible menu, users can go to the control panel for this task (in fact they won't have to do that as the notification in the cpanel renamed to Dashboard will be the direct link for that)
The same concept is applied for all the system related links.
Also the Help menu got a view following the same approach.

### Testing Instructions
Apply patch and navigate in the admin

### Preview
Dashboard:
screen shot 2017-04-28 at 15 10 26

Content:
screen shot 2017-04-28 at 15 11 16

Components:
screen shot 2017-04-28 at 15 12 05

Control Panel: (this is new)
screen shot 2017-04-28 at 15 12 51

Help: (this is new)
screen shot 2017-04-28 at 15 13 52

### CODE REVIEW

**Comment by ciar4n** [comment]
I like this. A clear approach, removes less used items from the main navigation and gives an opportunity to detail the purpose of some of these lesser used items.

**Comment by laoneo** [comment]
How will it look like when you click on Components -> Banners? Will a third column open?

**Comment by ciar4n** [comment]
@laoneo The PR is on the structure of the menu and how best to group menu items rather than the design. The design is branched from #15430

**Comment by dgt41** [comment]
Closing here, @ciar4n will come up with a slick design

**Comment by jonrz** [comment]
JUX is working on a similar, but more advanced and leaner information architecture for this menu, with a good amount of reorganization.
Our initial proposal will be up in a month.

**Comment by jonrz** [comment]
Based on a talk with @dgt41 and the JUX group, we agreed on a temporary compromise for the menu.
[Here is the file](https://docs.google.com/spreadsheets/d/11jGmMnGTuwjm1T6XGtngBtUHfIpplHpJf3yUKdYh8yQ). The horizontal display is just for better visualization of the worksheet.

The JUX will now work on the design, and make an official proposal as soon as possible.

**Comment by brianteeman** [comment]
Much better than your previous proposal you shared. Only one item looks wrong
Multilingual Associations - I would think that should be in your content menu or in your tools menu

**Comment by laoneo** [comment]
Contacts also do have fields.

**Comment by infograf768** [comment]
Why in the content menu?
Associations also deal with menu items associations

**Comment by brianteeman** [comment]
@infograf768 thats why I said ...or tools menu

**Comment by infograf768** [comment]
Install Languages missing in "Extensions"

**Comment by infograf768** [comment]
Not sure either about placing Modules in CONTENT.

**Comment by dgrammatiko** [comment]
@jonrz you keep all these useless menus under control panel and help. This PR was to remove all the links that clutter the menu (reasoning in the description)
So basically my proposal was something like this:
screen shot 2017-08-24 at 13 07 04

UX team proposal is 
screen shot 2017-08-24 at 13 09 34


Your proposal is not removing any system menus or help links, so the clutter of the menu remains.

**Comment by jonrz** [comment]
This is just the organization. 
Your style for control panel and help remain (but I had to show it somehow). 

_Sent from my Samsung SM-G930W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dgrammatiko** [comment]
@jonrz if the links for control panel and help are not dropdown (containing children links) then this is ok

**Comment by jonrz** [comment]
I tried to replicate your groups for the control panel. 
Items in bluish are supposed to be highlighted. 

_Sent from my Samsung SM-G930W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jonrz** [comment]
Did a few adjustments, and fixed the issues pointed out by Allon, Brian and infograf768.
The JUX team is still taking a last look for outstanding issues, but I feel this is pretty much it.

@brianteeman Thanks. I feel we reached a good initial compromise for J4.
I still hope for some revision when we present the layout/design, but nothing major, and I don't want to drag this longer than needed, since we have lots of other issues to tackle.
The Control Panel also has a "Languages" group. I think Multilingual Associations will fit better in there. Agree?

**Comment by brianteeman** [comment]
re multilingual - no not really

**Comment by jonrz** [comment]
@brianteeman 
Can I ask why?

**Comment by brianteeman** [comment]
If you use it you will see ;)

It is for creating content etc in a multilingual environment whereas the language stuff is just for setting things up

**Comment by jonrz** [comment]
I know what this is for. My reasoning for this is group not only by direct function (I know it is a tool) but by meaning.
It deals with languages, so for the basic user it  makes more sense to find all language stuff within the same group.
Same as the search issue we had a few days ago. For the user, there is no reason in seeing seemingly related functions scattered all over.

**Comment by brianteeman** [comment]
No. It deals with all types of content etc.

**Comment by brianteeman** [comment]
I will @infograf768 explain its importance. But it's a fundamental extension for any multilingual site that will be used constantly. It is not just a tool for setting up your site.if anything it is more to do with site building than most other things

**Comment by jonrz** [comment]
So, back to components because it's frequently used?
If it is within the control panel, it won't make it easier to use or to understand if we place it under tools than if we place it with Languages. Maybe half a screen lower on the scroll, and that's all. We won't inconvenience site builders, and we will help new/inexperienced users.

**Comment by infograf768** [comment]
My question will be simple:
Where would you put the CCKs? Seblod or K2 for example.

Multilingual Associations should be in the same group.

**Comment by jonrz** [comment]
@infograf768 
That's a fair point. We were trying to keep components a bit cleaner, but it makes sense.
We will try to determine the percentage of multi-lingual vs single language websites, and place it based on actual and projected use frequency. If we don't get the data to evaluate that in time, components is most likely to be its destination, so we won't make life more difficult for current users.

**Comment by dgrammatiko** [comment]
This will be solved else where by someone else

**Comment by micker** [comment]
very good thanks !

**Comment by micker** [comment]
for me multilanguale association need to be in content for 2 raison 
- it realy a good function and in tool nobody realy use it
- this tool is realy powerfull for content translation
for me its realy logicial to be in content part

**Pull request closed without merging**
