### PR TITLE
[4.0] template strings review

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the use of a file string for a folder
Removes unused strings
Grammar corrections

code review

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 6562d998717050b7b476e2df91e94c0e217cbaf8<br /><br />Dove:) Its OK!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31638">issues.joomla.org/tracker/joomla-cms/31638</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6562d998717050b7b476e2df91e94c0e217cbaf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31638">issues.joomla.org/tracker/joomla-cms/31638</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31638">issues.joomla.org/tracker/joomla-cms/31638</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
