### PR TITLE
[3.x FIX] Getting the correct associations in sidebyside view for contact and newsfeeds

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21178

### Summary of Changes
Changing #Jform_title to #Jform_name as these components are using `name` instead of `title`.
Thanks @SharkyKZ for the hint.

### Steps to reproduce the issue
Create a multingual site. 2 languages are enough.
Create a contact in each language and associate them in their edit page.
Load Multilingual Associations component.
Select Contact as type and one fo the languages.
Click on the greyed icon in the Associations column.
This will load the side by side page.

### Expected result
When using the Associations Tab for the reference and the target items, the field for the other language should display the name of the associated contact.

### Actual result
It does not.
As you can see in the animated gif below, it does flash the name for a second at reload, then disapears as soon as the Target finishes loading.
assocfieldcontact

### After patch
screen shot 2018-07-19 at 11 31 09

### Note
It will also work for newsfeeds.

@SharkyKZ @franz-wohlkoenig @rdeutz

### CODE REVIEW

**Comment by ghost** [comment]
@infograf768 will test later on.

**Comment by infograf768** [comment]
Restarted drone...

**Comment by ghost** [comment]
I didn't get what to look for without PR. Reference and Target are loaded on Tab "Edit Contact", didn't see any Flash. 

Can you please advice?

screen shot 2018-07-19 at 12 39 49

**Comment by infograf768** [comment]
You have to display the Associations tab, not the Edit Contact

**Comment by SharkyKZ** [comment]
https://github.com/joomla/joomla-cms/blob/a065d2edfb3d6f5901df985de711402863f76c66/administrator/components/com_associations/views/association/view.html.php#L113
https://github.com/joomla/joomla-cms/blob/a065d2edfb3d6f5901df985de711402863f76c66/administrator/components/com_associations/views/association/view.html.php#L137

Combine these into one?

**Comment by infograf768** [comment]
> Combine these into one?

I don't think so. We have to differentiate them in the edit.php as well as in the sidebyside. js
Similar code to $this->referenceLanguage and $this->targetLanguage

If we wanted (but it adds a line),  we would have
`$this->title         = AssociationsHelper::getTypeFieldName($extensionName, $typeName, 'title');`
and then
`$this->referenceTitle    = $this->title;`
and further
`$this->targetTitle      = $this->title;`

**Comment by SharkyKZ** [comment]
`$this->referenceLanguage` and `$this->targetLanguage` refer to field values which can differ between reference/target. Meanwhile field names are always the same.

This can be simplified in the layout/js too by adding data attribute to the entire form, like `data-associatedview`
https://github.com/joomla/joomla-cms/blob/a065d2edfb3d6f5901df985de711402863f76c66/administrator/components/com_associations/views/association/tmpl/edit.php#L30

**Comment by SharkyKZ** [comment]
And without proposed change notice appears:
```
Notice: Undefined property: AssociationsViewAssociation::$targetTitle in /administrator/components/com_associations/views/association/tmpl/edit.php on line 59
```

**Comment by ghost** [comment]
@infograf768 no flashing: click on Tab "Associations" works as expected.

**Comment by infograf768** [comment]
> Notice: Undefined property: AssociationsViewAssociation::$targetTitle in /administrator/components/com_associations/views/association/tmpl/edit.php on line 59

I have corrected this as I did not test when there is NO association set. In that case indeed we have the Undefined property.

**Comment by infograf768** [comment]
@franz-wohlkoenig 
> no flashing: click on Tab "Associations" works as expected.

When there are already associations, it does not as the wrong form is selected in sidebyside.js 
Please re-read test instructions.

**Comment by infograf768** [comment]
> This can be simplified in the layout/js too by adding data attribute to the entire form, like data-associatedview

I will test this

**Comment by infograf768** [comment]
@SharkyKZ 
Your proposal to simplify does not work.
As I corrected the "undefined property", please test again. We need to get this in for 3.x and then correct 4.0

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 06ed4121c2dfef9368c16ad0352fb8423eff7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21180">issues.joomla.org/tracker/joomla-cms/21180</a>.</sub>

**Comment by zero-24** [comment]
I get the following js error and the spinner did not end.
image


I have installed a new 3.8.10 with de & fr for all other i have followed the instructions.

**Comment by zero-24** [comment]
I have tested this item :red_circle: unsuccessfully on 06ed4121c2dfef9368c16ad0352fb8423eff7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21180">issues.joomla.org/tracker/joomla-cms/21180</a>.</sub>

**Comment by infograf768** [comment]
@zero-24 
I have corrected this real error in the js. (I had only corrected it before in the php)
(Although, it did not prevent the patch from working here, i.e. did not get the spinning. May depend of browser.)
can you test again?

**Comment by infograf768** [comment]
@franz-wohlkoenig 
Please test again. This time also look in the browser console. There should not be any more error message.

**Comment by durubayram** [comment]
I have tested this item :white_check_mark: successfully on 731e47dfaf266c4932135ff440912769695b221a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21180">issues.joomla.org/tracker/joomla-cms/21180</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 731e47dfaf266c4932135ff440912769695b221a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21180">issues.joomla.org/tracker/joomla-cms/21180</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
