### PR TITLE
Remove filter="url" for wrapper iframe

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #37545 .

### Summary of Changes
Remove filter="url" for wrapper iframe url.

### Testing Instructions
see issue #37545

### Actual result BEFORE applying this Pull Request

Url without http(s):// gets prefix http:// automatically

### Expected result AFTER applying this Pull Request

Url without prefix is possible.

Make sure that the url then is correct in frontend.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 106b730ca42c25ba7851f6af2e8a568e6aa2eed7<br /><br />The autoadd functionality is now never available<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by chmst** [comment]
Removing also validate - enables relative urls as mentioned in https://github.com/joomla/joomla-cms/issues/33235

**Comment by chmst** [comment]
The autoadd function works only in frontend, not in backend. You can see the code in components\com_wrapper\src\View\Wrapper\HtmlView.php. In my opinion this is wrong in the view but this is not in scope here

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 106b730ca42c25ba7851f6af2e8a568e6aa2eed7<br /><br />sorry - misunderstood<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by Quy** [comment]
This reverts issue #32245 and PR #32342.

**Comment by bayareajenn** [comment]
@Quy  is correct. It reverts those other issue/PRs. I can never find this stuff so thank you for finding it.
And thank you @chmst for writing the PR. Whilst I'd love to have it back to the way it was, if it isn't going to, we can write it into our custom extension. 
To me there's no point is having an option of "No" if it doesn't actually do what it says. We use a shortcode to a different server in that field in our custom extension. In working on getting our J3 extension ready for J4 is when I found this "bug" which doesn't appear to be a bug but rather other people deciding no one uses it in a different way. Bummer.

So someone let me know if I should test and then the other PR would be reverted or if we close this and I deal with it a different way, k? 

Thanks for testing @brianteeman

**Comment by chmst** [comment]
Thanks @Quy. If this enforced http//: is intended, then the the code in components\com_wrapper\src\View\Wrapper\HtmlView.php is wrong. I never use this and so have no opinion

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on 106b730ca42c25ba7851f6af2e8a568e6aa2eed7<br /><br />Works great and how it did before #32245 and PR #32342.

Let's see what happens now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by zero-24** [comment]
hmm i dont think we should remove the validation here. Better we should create a filter that also allows relative URLs where the question should be asked first why should we iframe an internal URL in the first place?

And by the intial report the 'issue' is that the protocol has been added? why is that an issue isnt adding the protocol not something thats a good thing?

maybe I'm missing something here?

**Comment by bayareajenn** [comment]
@zero-24 At my company, we aren't using an internal URL. We're using a shortcode off to a different server. Our current extension adds the https so in the menu item we kept it turned off. We can't go adding http(s) twice now, can we?! So two choices: the option is added back into Joomla or my company changes our extension to NOT have the http(s) to make up for the change and maybe not be able to use the shortcode anymore since I don't think we can have Joomla detect the "s" on a shortcode.

Simply said, it was something we used. I didn't know it had disappeared in J4. I thought it was a bug.

The fact that the setting/parameter Auto Add can be set to "No" but doesn't obey "No" should be addressed though. Either allow it to be turned off for reals, or remove the Auto Add parameter completely since it doesn't work. It adds http when it is set to No.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by zero-24** [comment]
> We're using a shortcode off to a different server. 

What is a shortcode in this context? In the past it was just a "you can add here anything" field now we make sure its an URL including the protocol.

**Comment by frostmakk** [comment]
From the iframe wrapper menu's help screen:

image

The question is not why should we allow a relative path. The question is why did we remove a valid and documented option that people are using?

**Comment by zero-24** [comment]
> The question is not why should we allow a relative path. The question is why did we remove a valid and documented option that people are using?

I still have the question why we need to use relative paths in the first place but when its documented that way an filter that allows relative paths should be created and we should not just remove the current url filter

**Comment by zero-24** [comment]
In the best case there should just be an option within the current URL filter like "allowRelative=true" and in case its not set its not allowing relative URLs while this option will be set here ;)

**Comment by frostmakk** [comment]
Why not simply switch the validation filter on/off with the existing Auto Add option button ?

**Comment by zero-24** [comment]
> Why not simply switch the validation filter on/off with the existing Auto Add option button ?

That would mean the validation rule has to check the option of an specific backend component which is not a good idea and auto Add has nothing to do with the validation but is adding stuff the the when the user does not add it.

**Comment by bayareajenn** [comment]
> What is a shortcode in this context? In the past it was just a "you can add here anything" field now we make sure its an URL including the protocol.

We have a lot of sites. Instead of having to put the server name in each site (different for every instance), we use a shortcode - imagine it's something like `_SERVER_` and it pulls from the parameters of the custom extension which does have the server name spelled out. It makes it easier for our people who build the sites (globally).

This is the second thing to be removed from the iframe menu item but the documentation says it exists https://github.com/joomla/joomla-cms/issues/37544.

In the case of this issue, I can work around it if I have to but the fact remains, there's an Auto Add option toggle that should allow me to turn it off and I can't. So is it a bug? Or is it just other people deciding what's good for me to put in the URL field? OR should the Auto Add parameter also be removed since it's a pointless toggle?

**Comment by Pallieguy** [comment]
We have custom scripts/tools that are developed on a development environment before being moved to production, using a relative path allows us to copy and paste everything between our production and development environments instead of manually setting them.

While not a lot of work, it's unnecessary work and one more thing for someone to miss when trying to code/debug

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by zero-24** [comment]
@RickR2H please take off the RTC label as there is still an open discussion how to solve this issue.

**Comment by brianteeman** [comment]
and please put the RLDQ tag back

**Comment by RickR2H** [comment]
Back to pending. @bembelimen can you decide what to do?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by bayareajenn** [comment]
@bembelimen and @zero-24 any updates on this one?

**Comment by mpradel** [comment]
I have tested this item :white_check_mark: successfully on 106b730ca42c25ba7851f6af2e8a568e6aa2eed7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by HLeithner** [comment]
This pull requests has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by brianteeman** [comment]
This has been waitinf ro a release lead to make a decision for over 1 year :(

**Comment by TLWebdesign** [comment]
I've tested this and noticed that when no schema was added to the url it still added a single slash in front of the url in the generated html. When i looked at the dom it looked like this: src="/domain.nl" while the url field only contains domain.nl<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37547">issues.joomla.org/tracker/joomla-cms/37547</a>.</sub>

**Comment by MacJoom** [comment]
> I've tested this and noticed that when no schema was added to the url it still added a single slash in front of the url in the generated html. When i looked at the dom it looked like this: src="/domain.nl" while the url field only contains domain.nl
> 
@TLWebdesign - thanks for testing - is this a problem within this PR or another issue?

**Pull request merged**
