### PR TITLE
[4.3] Smart Search: Don't republish items upon save

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue # .

### Summary of Changes
In Smart Search you can disable entries in the index by unpublishing them. Unfortunately, the entries were re-published when an item was saved again. I earlier claimed that it wasn't possible to prevent that behavior in our current system because I thought the state of the content item and the state of the item in the index were the same field in the database. I was wrong and we actually have a field named "published" for the state of the item in the index and "state" for the state item of the content item. Sorry, @brianteeman 😉  (Maybe you can help me find the issue where this was reported? I can't find it right now...)

After some debugging it turned out that in our finder plugins we are using the `reindex()` method of the `Adapter` class in finder and that method falsely completely deletes the entry first from the index and then adds it back in again. This actually is far less performant than simply indexing again as the normal indexer does...

### Testing Instructions
Index your content and unpublish an entry in the index. Edit the content and without changing anything, save it again.

### Actual result BEFORE applying this Pull Request
The item in the index is published again.

### Expected result AFTER applying this Pull Request
The item stays unpublished until you publish it again.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I'm not sure, I don't know much about smart search, maybe this? #36980 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39944">issues.joomla.org/tracker/joomla-cms/39944</a>.</sub>

**Comment by Hackwar** [comment]
Unfortunately that issue is not the one I was looking for.

**Comment by Quy** [comment]
#39415?

**Comment by fabpacheco** [comment]
Or maybe [#32458](https://github.com/joomla/joomla-cms/issues/32458)

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 5a66c06fa92be8cac8ac8cc063764a4160940196<br /><br />Tested successfully in Joomla 4.3.0-beta4 of 25 February using PHP 8.1.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39944">issues.joomla.org/tracker/joomla-cms/39944</a>.</sub>

**Comment by brianteeman** [comment]
This one https://github.com/joomla/joomla-cms/issues/38838 ?

**Comment by Hackwar** [comment]
Unfortunately none of these. I'm going to look further. But the issue of #38838 is very similar.

**Comment by brianteeman** [comment]
OK - this time I am sure I found it https://github.com/joomla/joomla-cms/issues/36980

**Comment by Hackwar** [comment]
That one is related to the taxonomies, which I'm still working on.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5a66c06fa92be8cac8ac8cc063764a4160940196<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39944">issues.joomla.org/tracker/joomla-cms/39944</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39944">issues.joomla.org/tracker/joomla-cms/39944</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar !

**Pull request merged**
