### PR TITLE
[com_content][Multilanguage] - fix link when layout and association

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
added the layout param in the link when needed

### Testing Instructions

- in a multilanguage site
- create a Category Blog menu item in all languages and associates those items
- create a Category List menu item in all languages and associates those items
- click on the Category Blog menu item (en-GB for example)
- click on a different flags (it-IT for example) on the module languages switcher

### Expected result
you are redirected to the associated Category Blog menu item (it-IT for example)

### Actual result
you are redirected to the associated Category List menu item (it-IT for example)

### CODE REVIEW

**Comment by infograf768** [comment]
Just before I test:
If in one language we have a category blog (and no category list) and the other has a category list only, what is supposed to happen? I expect a redirect to the category concerned whatever the layout.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 62d91ca7a6758ff298e1a47618af7c291552140b<br /><br />Tested both situations. Works OK here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19681">issues.joomla.org/tracker/joomla-cms/19681</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 62d91ca7a6758ff298e1a47618af7c291552140b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19681">issues.joomla.org/tracker/joomla-cms/19681</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19681">issues.joomla.org/tracker/joomla-cms/19681</a>.</sub>

**Comment by infograf768** [comment]
@alikon 
Please ping me on glip. This change to route.php is creating unwanted issues (testing now some stuff in 4.0)

**Comment by alikon** [comment]
done

**Comment by infograf768** [comment]
Will make PR with all explanations.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/21916

**Pull request merged**
