### PR TITLE
[staging] Fix tinymce params

### PR DESCRIPTION
**Pull request by brianteeman**
Backport of #27496 and #24797

cc @zero-24

### CODE REVIEW

**Comment by richard67** [comment]
> Backport of #27496 and #24797

@brianteeman Shouldn't the 2nd one not be #27497 ?

**Review by zero-24 — APPROVED** [review]
LGTM thanks @brianteeman

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 76dc752664606c84f3d1d932d859c3c19adae68b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27498">issues.joomla.org/tracker/joomla-cms/27498</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 76dc752664606c84f3d1d932d859c3c19adae68b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27498">issues.joomla.org/tracker/joomla-cms/27498</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :)

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
