### PR TITLE
s/compatability/compatibility

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/compatability/compatibility

### CODE REVIEW

**Comment by PhilETaylor** [comment]
upstream submitted to https://github.com/joomla-framework/application/pull/94

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9bf676751ebcdc37d6815e9a338175c80dea66a1<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32781">issues.joomla.org/tracker/joomla-cms/32781</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :red_circle: unsuccessfully on 9bf676751ebcdc37d6815e9a338175c80dea66a1<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32781">issues.joomla.org/tracker/joomla-cms/32781</a>.</sub>

**Comment by PhilETaylor** [comment]
@SharkyKZ ????

**Comment by Quy** [comment]
It is my understanding that files in `vendor` directory should be made upstream and then migrated downstream.

**Comment by PhilETaylor** [comment]
for those installable by composer maybe.... but are not these forked versions that are in the 4.0-dev? 

upstream submitted too joomla-framework/application#94

**Comment by PhilETaylor** [comment]
and looking at the last modified commits of the files in https://github.com/joomla/joomla-cms/tree/4.0-dev/libraries/src would suggest that Im right :)

**Comment by richard67** [comment]
Last time this file was fetched from the framework was in 2019 or earlier. This commit in the framework hasn't arrived in the CMS yet: https://github.com/joomla-framework/application/commit/134f2980575b7e58b51ef3624faac84e7a3f304d .

But that's the only difference between the CMS and the framework version.

So here it could indeed make sense to do the change in the framework and later pull it into the CMS.

We have other framework stuff were we have more differences between framework and CMS, like e.g. database, and where we changed things in the CMS and later pulled it up into the framework, and I thought that's the case here, too, that's why I haven't insisted in doing it upstream in the framework.

All that said only for J3 (staging, 3.10-dev). For J4 it's definitely different.

**Comment by PhilETaylor** [comment]
Im not going to argue for a typo.

**Comment by richard67** [comment]
See also https://github.com/joomla-framework/application/pull/94 and https://github.com/joomla-framework/application/pull/95 ... we gotta pull the changes from the framework as soon as the PR's there got merged.

Thanks @PhilETaylor for reporting and making the PR's there.

**Pull request closed without merging**
