### PR TITLE
[com_fields] Improved description in the "description" tooltip Fixes #13392

### LINKED ISSUE #13392: [com_fields] Improving Custom Fields - Tooltip for the Field "Description"
image

The tooltip for the description doesn´t tell the User really what happens with this input.
I´d rather say here it´s "The description which will appear in a tooltip when a user hovers the label".

If someone tells me this sentence in clean english i can make a PR.

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Pull Request for Issue #13392  .

### Summary of Changes
Changed the value within the "description" tooltip
Before: "The description of the field"
After: "A description of the field that will be displayed in the label tooltip."

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on cdf20e9f0cef8435983b6bf605885ceacf7a6f0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Comment by Minei3oat** [comment]
I have tested this item :white_check_mark: successfully on cdf20e9f0cef8435983b6bf605885ceacf7a6f0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Comment by zero-24** [comment]
We need to hold off RTC until we have a final review by the en-GB WG. Thanks.

**Comment by jeckodevelopment** [comment]
I'd suggest:
`A description of the field that will be displayed in the label tooltip.`

**Comment by genesisfan** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Comment by genesisfan** [comment]
I have tested this item :white_check_mark: successfully on 5b0864aa229d824cdc1f24f4b58c9ab3f8460197<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5b0864aa229d824cdc1f24f4b58c9ab3f8460197<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Comment by infograf768** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13557">issues.joomla.org/tracker/joomla-cms/13557</a>.</sub>

**Pull request merged**
