### PR TITLE
[4.0] Fix errors during upgrade (PostgreSQL)

### PR DESCRIPTION
**Pull request by twister65**
Pull Request for Issue #25467 .

### Summary of Changes
Fix errors of sql files in administrator/components/com_admin/sql/updates/postgresql.
See the commit comments.

### Testing Instructions
1. Install a copy of Joomla 3.x (I was using 3.9.9 RC) on postgres
2. Apply this PR to your joomla source directory.
3. Build an update package to your joomla-4.0-dev source directory:
- `git tag 4.0.0-alpha11-dev`
- `php build/build.php`
- Update Joomla 3.9.x with the new update package.
4. Check if Joomla upgrades successfully

### Expected result
No Warning or Error.

### Actual result

> Error
The template for this display is not available.

is going away.

database_check

### CODE REVIEW

**Review by richard67 — APPROVED** [review]
I think @wilsonge could merge that by review. Code review looks good, and when this is merged we can use the nightly build after that merge for further testing updates.

**Comment by richard67** [comment]
For testers: You can find a modified nightly build from today 2019-07-08 morning with this PR applied here:
[https://test5.richard-fath.de/Joomla_4.0.0-alpha11-dev-Development-Update_Package_2019-07-08_pr-25477.zip](https://test5.richard-fath.de/Joomla_4.0.0-alpha11-dev-Development-Update_Package_2019-07-08_pr-25477.zip)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b60b991d3f2f6574b0fcb05958b86b24de5e972e<br /><br />Tested with the regular and my modified update package from today's nightly build, which I linked in my previous comment.

Regular update package: SQL errors, and the template not found warnings mentioned in issue #25467 don't go away.

Modified update package with this PR: No SQL errors, behavior like descibed in issue #25467, i.e. there are template not found warnings shown, but after update has finished, they go away and not appear again when navigating in the backend.

So this PR makes the update complete without crash. Without this PR update crashes because of SQL errors and so is not complete.

Other errors remain for updating 3.9.x to 4.0-dev, e.g. the menu entry for com_search is still there, but these are not subject of this PR. They shall (and I will do so) be reported in issue #25467 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25477">issues.joomla.org/tracker/joomla-cms/25477</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b60b991d3f2f6574b0fcb05958b86b24de5e972e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25477">issues.joomla.org/tracker/joomla-cms/25477</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25477">issues.joomla.org/tracker/joomla-cms/25477</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys! Much appreciated :)

**Comment by wilsonge** [comment]
I've retriggered a nightly build of this so if any of you want to test using the nightly you can

**Pull request merged**
