### PR TITLE
[4.0] Add explanation for Debug Allowed Groups field.

### PR DESCRIPTION
**Pull request by Sophist-UK**
Pull Request for Issue # .

### Summary of Changes

Add tooltip explanation for the Allowed Groups field.

For this plugin (unlike the rest of Joomla) the group filter does not imply membership of parent groups. So if you are a Joomla Administrator and Debug is set only for Joomla Manager, whereas in the rest of Joomla you are an implied member of the Joomla Manager group, for this plugin you aren't and will not get debug information shown.

### Testing Instructions

Apply this PR, load the Debug system plugin settings and hover mouse over the "Allowed Groups" label.

### Expected result

An explanation is shown below this field and a tooltip with the same information is shown when you hover the mouse over the "Allowed Groups" label.

### CODE REVIEW

**Comment by brianteeman** [comment]
I really do not see the need to add this description text

**Comment by Sophist-UK** [comment]
Well - I selected Public because I thought that would make it show for everyone, but all it did was make it not display for anyone.

IMO it needs an explanation because it doesn't work like the rest of Joomla when it comes to group hierarchies whereby if you are in a subgroup, then you are also by implication in all parent groups.

**Comment by brianteeman** [comment]
thats because the styling is not present. If you look at how it is done in j3 where the styling is correct it is more obvious that it is not the same

**Comment by Sophist-UK** [comment]
If you look at J3 you will see there is a tooltip explanation.

**Comment by brianteeman** [comment]
And we have done everything we can to remove those tooltips in j4 as the vast majority of them were useless

**Comment by Sophist-UK** [comment]
Ok - let's forget it.

**Pull request closed without merging**
