### PR TITLE
[4.0] Cassiopea: adding margin to back-top

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
As title says.

### Before patch
LTR

Screen Shot 2019-12-19 at 11 43 29

RTL
Screen Shot 2019-12-19 at 11 43 45

### After patch
LTR

Screen Shot 2019-12-19 at 11 34 29

RTL

Screen Shot 2019-12-19 at 11 34 52

### CODE REVIEW

**Comment by C-Lodder** [comment]
With the amount of margins that have been tweaked for RTL, I don't know why you don't just create a SCSS mixin

**Comment by C-Lodder** [comment]
Something I've quickly mocked up if you are interested.

**Mixin:**
```scss
@mixin margin($position, $size) {
  margin-#{$position}: $size;
  
  $rtl-position: null;
  @if $position == 'left' {
    $rtl-position: right;
  } @else if $position == 'right' {
    $rtl-position: left;
  }

  @if $rtl-position != null {
    [dir=rtl] & {
      margin-#{$rtl-position}: $size;
    }
  }
}
```

**Random element class:**
```scss
.myClass {
  display: block;
  @include margin('left', 2rem);
}
```

This will add your desired RTL code and ignore `top` and `bottom`

**Comment by infograf768** [comment]
@C-Lodder 
Sorry, but this kind of code is above my skills.
I can close this if you like and let you propose a new PR.

**Comment by brianteeman** [comment]
Closed as we have a new pr

**Pull request closed without merging**
