### PR TITLE
[4.0] Allow switching displaying Help menu also in Joomla Main Menu preset

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26050

### Summary of Changes
As title says

### Testing Instructions
Edit the Admin Menu module set to use Preset - Joomla Main Menu and switch on and off the Help Menu field.

### Before patch
This was only working when using the Alternative menu preset

### After patch
Now works also when using the default preset.

When Help Menu is set to hide, we rightfully get:
Screen Shot 2019-11-12 at 08 03 24

@Quy @brianteeman

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 90c0b5f70a17c106586555d3b4ebeb98f41fb4b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27052">issues.joomla.org/tracker/joomla-cms/27052</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 630783409931bee51cf4342fbd36699eb7cc14ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27052">issues.joomla.org/tracker/joomla-cms/27052</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27052">issues.joomla.org/tracker/joomla-cms/27052</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
