### PR TITLE
Update bootstrap-rtl.css

### PR DESCRIPTION
**Pull request by obuisard**
Duplicate entry .radio.btn-group > label:first-of-type

Pull Request for Issue #19714  .

### Summary of Changes

Removed the 2nd occurrence of .radio.btn-group > label:first-of-type

### Testing Instructions

Use the Protostar template in RTL mode

### Expected result

The button created by the icons.php content layout should have round corners

### Actual result

Only half the corners are round. With the fix, all corners are round.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 91aeef3a1698547312818aed93564fac010f6552<br /><br />Issue confirmed and solution OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19715">issues.joomla.org/tracker/joomla-cms/19715</a>.</sub>

**Comment by brianteeman** [comment]
Please edit the less file and not the css file directly and then run generatecss.php to create the csss https://docs.joomla.org/Joomla_LESS

**Comment by obuisard** [comment]
I did not change the .css file after the use of generatecss.php as the processing gave identical results as the manual update

**Comment by infograf768** [comment]
OK here. One more tester.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e5bb87eaf628089697d1eaf715ea544a8b9e4803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19715">issues.joomla.org/tracker/joomla-cms/19715</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
