### PR TITLE
Reduce the number of page duplicates in com_content categories when pagination is used.

### PR DESCRIPTION
**Pull request by philip-sorokin**
### Summary of Changes

Reduce the number of page duplicates in com_content categories when pagination is used.
### Testing Instructions

[https://www.joomla.org/announcements.html?start=999999999999999999999](https://www.joomla.org/announcements.html?start=999999999999999999999) - it opens, while it should not. With this patch applied, pages will open if they really exist: [https://www.joomla.org/announcements.html?start=390](https://www.joomla.org/announcements.html?start=390) - this will be the last page.

### CODE REVIEW

**Comment by zero-24** [comment]
@addondev can you fix the if syntax and add a space bettween the `if` and the openeing `(`

```
FILE: ...ld/joomla/joomla-cms/components/com_content/views/archive/view.html.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 86 | ERROR | Expected "if (...)\n...{...}\n...else\n"; found
    |       | "if(...)\n...{...}\n...else\n"
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: ...d/joomla/joomla-cms/components/com_content/views/category/view.html.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 125 | ERROR | Expected "if (...)\n...{...}\n...else\n"; found
     |       | "if(...)\n...{...}\n...else\n"
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
FILE: ...d/joomla/joomla-cms/components/com_content/views/featured/view.html.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 117 | ERROR | Expected "if (...)\n...{...}\n...else\n"; found
     |       | "if(...)\n...{...}\n...else\n"
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
``` 

https://travis-ci.org/joomla/joomla-cms/jobs/159016449

**Comment by addondev** [comment]
Can you test it, please?

**Comment by brianteeman** [comment]
Is it the intended behaviour of this pr that ?start=999999999999999999999  gives a 404?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12004">issues.joomla.org/joomla-cms/12004</a>.</sub>

**Comment by addondev** [comment]
Yes, it does.

**Comment by addondev** [comment]
The same behaviour you can see in the content_pagebreak plugin - if an article page does not exist, it gives a 404. Why not apply this approach to category blogs? When you have 200 pages, search engines index them, then you change the item per page number and 200 becomes 100. The problem is that the other 100 pages not longer exist, by they cannot be removed from search index without editing robots.txt/htaccess. I think it is very inconvenient.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 504c94867fc2e719cc4023e6b500012bf506fd93<br /><br />With or -out patch pages open. Example: Show 1 of 2 Pages, append in URL `?start=99999999` – always 2 (the last page) is shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12004">issues.joomla.org/tracker/joomla-cms/12004</a>.</sub>

**Comment by philip-sorokin** [comment]
@franz-wohlkoenig

I use the RC demo pages (featured view). I set in the menu params the following configuration to make pagination:

```
Leading Articles - 1
Intro Articles - 1
Columns - 1
Links - 1
```
When I open page 4 that does not have any items, I get the 404. Could you, please, describe your testing instructions?

**Comment by franz-wohlkoenig** [comment]
@philip-sorokin Test Instructions shown in opened Comment.

**Comment by philip-sorokin** [comment]
@franz-wohlkoenig
Can you give me a link to this comment. I am sorry, can't find it.

**Comment by franz-wohlkoenig** [comment]
on Top of this Thread, its your opening Comment about Issue.

**Comment by philip-sorokin** [comment]
Still can't see any comments.

comment

**Comment by franz-wohlkoenig** [comment]
what i mean is:
bildschirmfoto 2017-04-11 um 07 34 24

**Comment by philip-sorokin** [comment]
@franz-wohlkoenig
This is my testing instructions, I thought you would write yours. Please, give me more details on the fail, because I tested it with 3 views successfuly:

-archive
-category
-featured

**Comment by franz-wohlkoenig** [comment]
I used your Instructions for Test. Have to retest, my Test is too long ago to remember.

**Comment by franz-wohlkoenig** [comment]
Test on "Archive". 9 archived Articles (5 en-GB, 4 All Lang.), Menu set on Lang. "en-GB". 

#### 1/4. Call menu, Pagination show 1/2 (expected):

#### 2/4. Click Pagnation 2/2, Url change to `index.php/en/archived-articles?start=5` (expected):

#### 3/4. Change Url to `index.php/en/archived-articles?start=6` (unexpected – Articles with Lang.: All are shown):

#### 4/4. Change Url to `index.php/en/archived-articles?start=9` (expected – 404

**Comment by philip-sorokin** [comment]
And what is your conclusion? What about other views?

**Comment by wojsmol** [comment]
@philip-sorokin @franz-wohlkoenig don't expect this 

> 3/4. Change Url to index.php/en/archived-articles?start=6 (unexpected – Articles with Lang.: All are shown):

**Comment by franz-wohlkoenig** [comment]
@wojsmol didn't get what you mean.

**Comment by wojsmol** [comment]
@franz-wohlkoenig See https://github.com/joomla/joomla-cms/pull/12004#issuecomment-293258180 first question

**Comment by franz-wohlkoenig** [comment]
I  have no Conclusion cause no Knowledge.

**Comment by philip-sorokin** [comment]
I am closing this PR as it is not going to be merged.

**Comment by philip-sorokin** [comment]
I am closing this PR as it is not going to be merged.

**Pull request closed without merging**
