### PR TITLE
[4.0][com_content] remove comment from c&p mistake

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
remove comment from c&p mistake

### Testing Instructions
code review

### CODE REVIEW

**Comment by HLeithner** [comment]
can you fix https://ci.joomla.org/joomla/joomla-cms/38218/1/6 please

**Comment by alikon** [comment]
Sorry didn't understand i've changed only 1 file  this administrator/components/com_content/src/Model/ArticleModel.php

how it can be related to the drone report 
image

**Comment by richard67** [comment]
@HLeithner Drone PHPCS is currently failing in the 4.0-dev branch with the same result: https://ci.joomla.org/joomla/joomla-cms/38216/1/6 . So it's not related to this PR, and the branch of this PR is up to date.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e32dc05bebecf23f0742c78ac086f61594d0d8dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31659">issues.joomla.org/tracker/joomla-cms/31659</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e32dc05bebecf23f0742c78ac086f61594d0d8dd<br /><br />Tested successfully in Beta6-dev of 15 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31659">issues.joomla.org/tracker/joomla-cms/31659</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31659">issues.joomla.org/tracker/joomla-cms/31659</a>.</sub>

**Comment by SharkyKZ** [comment]
What was that about not setting RTC on PRs with failing tests? 🤔

**Comment by richard67** [comment]
As I stated above, failing tests are not related to this PR but to the 4.0-dev branch.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
