### PR TITLE
[4.0] workflows tip

### PR DESCRIPTION
**Pull request by brianteeman**
Change the title for transitions and stages to a tip

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fd310ef3f60aafdb6cf81757d9e9060e7fd730b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34689">issues.joomla.org/tracker/joomla-cms/34689</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on fd310ef3f60aafdb6cf81757d9e9060e7fd730b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34689">issues.joomla.org/tracker/joomla-cms/34689</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34689">issues.joomla.org/tracker/joomla-cms/34689</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
