### PR TITLE
Correcting asset data in installation & sample mysql data

### PR DESCRIPTION
**Pull request by sanderpotjer**
This patch corrects the asset data for the mysql installation & sample data. This won't have visual effects, but can prevent conflicts when using the Joomla ACL system. 

For other database drivers the data needs to be corrected too, but already out of sync on many other places, so would like to know the plans for that before spending time on that too.

### CODE REVIEW

**Comment by waader** [comment]
@sanderpotjer Following the conversation I am not sure if this is ready for testing or an update is needed.

**Comment by brianteeman** [comment]
@sanderpotjer It is unclear from comments above if this has been updated as requested by @infograf768 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5271">issues.joomla.org/joomla-cms/5271</a>.</sub>

**Comment by sanderpotjer** [comment]
I tried to improve the asset sample data multiple times now, each time it is "outdated" soon due other changes. Without proper planning to review and commit it in a short timeframe I won't spend my time for another attempt...

**Comment by brianteeman** [comment]
In this case it was left by most testers because of the lack of any test
instructions

Experience here on the tracker shows that all pull requests that are
accompanied with clear test instructions get tested very very quickly

On 16 June 2015 at 21:01, Sander Potjer <notifications@github.com> wrote:

> I tried to improve the asset sample data multiple times now, each time it
> is "outdated" soon due other changes. Without proper planning to review and
> commit it in a short timeframe I won't spend my time for another attempt...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5271#issuecomment-112551593>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanderpotjer** [comment]
My experience here on the tracker is that correcting sample data is a nightmare, even with testing instructions. On top of that asset sample data is hardly testable via the Joomla interface (so not with the Patch Tester), just have a look at the file changes yourself.

**Comment by mbabker** [comment]
Truthfully, I consider the sample data a lost cause.  If you can get the core joomla.sql files updated (and they should be in sync for all the DB drivers), that's usually enough for someone who decently comprehends the different schemas to go with.  Those who are able to clone a patch with git or download a branch's ZIP will test it, but that audience is admittedly a lot smaller than those who work with the patch tester.

**Comment by zero-24** [comment]
>My experience here on the tracker is that correcting sample data is a nightmare, even with testing instructions.

hmm the easiest is to give the test instructions like this:

- Install my branche as normal joomla install see: https://github.com/sanderpotjer/joomla-cms/archive/staging.zip
- confirm that the installation still works
- confirm that all sample data still works
- if all works report a successful test

:smile:

**Comment by sanderpotjer** [comment]
@zero-24 yeah, two successful tests guaranteed in no-time. But I think its better if its reviewed by people that know a bit more about the sample data and its structure to have some quality control, right?

**Comment by zero-24** [comment]
> But I think its better if its reviewed by people that know a bit more about the sample data and its structure to have some quality control, right?

@sanderpotjer 
Agree but I think a review / quality control is anytime bevor the merge. And I think the committers `know a bit more about the sample data` :smile:

**Comment by roland-d** [comment]
I am setting this to review to discuss within the PLT what to do with the sample data.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5271">issues.joomla.org/joomla-cms/5271</a>.</sub>

**Comment by roland-d** [comment]
@rdeutz has volunteered to help clean up the sample data. So we can move this forward and get it merged. @sanderpotjer please let us know if you have still have interest in helping Robert. Thanks.

**Comment by roland-d** [comment]
Thank you all for your work. I am going to close it as this PR is now out-of-date. If anybody is interested in maintaining the sample data, please contact me and we will get you going.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5271">issues.joomla.org/joomla-cms/5271</a>.</sub>

**Pull request closed without merging**
