### PR TITLE
com_installer update view: searchtools ordering and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_installer update view.

Also:
- rearrange columns (install type moves to end)
- corrects bug where the folder filter has not selecting the search button
- corrects bug where by searching or selecting a filter the search tools resets when it should show the selected option
- correct visual on mobile, tablet and desktop
- other small graphical issues.
###### Before PR

image
###### After PR

image
#### How to test
1. Install latest staging and apply this patch
2. Install some old version extensions (which already have updates)
3. Go to Extensions -> Manage -> Update
4. Click "Find Updates" (check the updates for the extensions you installed are there)
5. Check the search, ordering select box and the filter are working fine.
6. Test desktop, tablet and mobile view (ex: reduce browser width).
7. Update your extensions and check if are ok.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c941ffe31c40eef5166ddb3013e26a673d7e0fbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9118">issues.joomla.org/joomla-cms/9118</a>.</sub>

**Comment by grhcj** [comment]
I tested this with the extensions shown in the screenshot. When I tried to install both at once (select both -> install) I get this error:
<code>Fatal error: Cannot redeclare class PlgSystemNoNumberInstallerInstallerScript in C:\xampp\apps\joomla\htdocs\tmp\install_56c1dc94b2ddd\script.install.php on line 15</code>
Only the "What? Nothing" extension was updated. 
When I try to install the cache cleaner extension alone, I get a warning: 
<code>Warning: JInstaller: :Install: Can't find XML setup file.</code>
Because I think that it's my mistake, I don't mark my test results here. Maybe someone can check this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9118">issues.joomla.org/joomla-cms/9118</a>.</sub>

**Comment by waader** [comment]
I expierenced the same problem as #grhcj when I tried to update more than one nonumber extension at once. But this behaviour is shown also without this patch. #Nonumber can you please have a look at this.

All other extensions where updated at one stroke. When I choose location ascending as sort order, 'site' comes before 'administrator', which is not alphabetically. But this beviour also existed before.

**Comment by andrepereiradasilva** [comment]
all ordering should work properly now, and in any language.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on d54ff99b91780acf823a129e607af4080a3b7b01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9118">issues.joomla.org/joomla-cms/9118</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d54ff99b91780acf823a129e607af4080a3b7b01<br /><br />Successs. All works like before plus the sorting by the location is alphabetic now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9118">issues.joomla.org/joomla-cms/9118</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC  thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9118">issues.joomla.org/joomla-cms/9118</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Comment by infograf768** [comment]
This has broken correct update proposals in Control Panel.
I have a component com_localise which is set as 4.0.13-dev (modified, this is why I do not update to the available 4.0.14-dev).

It now displays also as a Joomla Update.

screen shot 2016-02-19 at 08 46 45

Clicking on "Update Now" will load the Joomla Update page where, evidently, no update is proposed.
The Extensions:Update page correcty displays the possible update for the component.

**Comment by infograf768** [comment]
Hmm, I had to clear the Update cache and then click on Find Updates to get rid of this error.
I am afraid that people updating to 3.5.0 would get the same issue. Any possible solution?

**Pull request closed without merging**
