### PR TITLE
Tweaks to the footer

### PR DESCRIPTION
**Pull request by peterlose**
Some updates for the admin footer, primarily in mod_status
## Before PR

skaermbillede 2015-04-09 kl 00 35 26
## After PR

skaermbillede 2015-04-09 kl 00 35 33

### CODE REVIEW

**Comment by n9iels** [comment]
Looks good, thanks!

@test when you enable the admin module "Multilanguage status" this happen:
footer

**Comment by n9iels** [comment]
off topic: Am I the only on who gets a white page when clicking on a picture, and has to reload that page to see the picture? I'm working on the latest version of Google Chrome

**Comment by infograf768** [comment]
This does not look right.
Changing the messages plural strings by taking off the variable is wrong imho as JText::plural is used, and rightfully so as the order of the figure (the variable) in the value is depending on the language.

**Comment by losedk** [comment]
@infograf768 don't entirely understand the issue. There aren't any variables on the other language strings and they are using JText::plural

**Comment by infograf768** [comment]
code is;
"<?php echo JText::plural('MOD_STATUS_MESSAGES', $unread); ?>"

this expects a variable ($unread) in the string value depending on plural form:
therefore
this change is wrong
```
-MOD_STATUS_MESSAGES_0="%d Messages"
-MOD_STATUS_MESSAGES_1="%d Message"
-MOD_STATUS_MESSAGES_MORE="%d Messages"
+MOD_STATUS_MESSAGES_0="Messages"
+MOD_STATUS_MESSAGES_1="Message"
+MOD_STATUS_MESSAGES_MORE="Messages"
```
to display 1 message ( $unread = 1) using MOD_STATUS_MESSAGES_1="%d Message"
or 2 messages ($unread = 2) using MOD_STATUS_MESSAGES_MORE="%d Messages"

**Comment by mbabker** [comment]
The other badges haven't had the number in the string since 3.0, for better or worse.  The redesign split it so the number is in a badge and the text is only what it is describing.  To be fully correct for languages, the badge HTML should probably be in the strings.

**Comment by infograf768** [comment]
You are totally right. Weird. 
Tested by taking off the variable in the string value and no change in case string is not updated.

**Comment by infograf768** [comment]
This breaks the display in Hathor though.

before PR:

screen shot 2015-04-09 at 18 28 34

after PR
screen shot 2015-04-09 at 18 27 10

**Comment by losedk** [comment]
Thanks for the comments. I'll add the changes and fixes

**Comment by davdebcom** [comment]
@roland-d @brianteeman Guys, does the status need to be changed to "Information required" or something so we don't get PDF testers checking this one?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6713">issues.joomla.org/joomla-cms/6713</a>.</sub>

**Comment by zero-24** [comment]
Done @davdebcom if @losedk fixes the issues please let us know so we can move it back to Pending :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6713">issues.joomla.org/joomla-cms/6713</a>.</sub>

**Comment by losedk** [comment]
Yeah. I'm gonna look at it tomorrow :)

**Comment by losedk** [comment]
@n9iels Would this be okay for the multi language module issue:

## Status in bottom
skaermbillede 2015-04-12 kl 16 47 59
 
## Status in top
skaermbillede 2015-04-12 kl 16 48 16

**Comment by n9iels** [comment]
yes, that should be oke :-)

**Comment by franz-wohlkoenig** [comment]
Works as described

**Comment by losedk** [comment]
Pushed some updates, but I'm not entirely sure of how to resolve the merge conflicts.

**Comment by n9iels** [comment]
@test works good for the Joomla! core, but seems like it doesn't work well with 3e part extensions:
knipsel

**Pull request closed without merging**
