### PR TITLE
[4] Ensure using the latest stable composer when running unit tests

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review
Drone review

### CODE REVIEW

**Comment by PhilETaylor** [comment]
@rdeutz Drone here too says "Build is blocked, please, contact repo admin in order to proceed". ????

**Comment by wilsonge** [comment]
Needs a drone admin to generate a fresh hash. Seeing family in London today so can’t do it right now but ping me to remind me tomorrow and I’ll update it

**Comment by HLeithner** [comment]
I'm closing this, our composer version should always be uptodate. 
We build our images every week. Sadly we had some problems building new images, for the moment most of them are uptodate again. The rest is in the pipeline.

**Comment by PhilETaylor** [comment]
If they were up to date then composer installs would currently be stalling and every build broken. Composer 2.2 has a new feature that has a manual prompt… see my other PRs

**Comment by PhilETaylor** [comment]
Eg https://github.com/joomla/joomla-cms/pull/36338

**Pull request closed without merging**
