### PR TITLE
Additional sorting fixes

### PR DESCRIPTION
**Pull request by frostmakk**
Pull Request for Issue # .

### Summary of Changes
After merging of #15655 the popular article module in cpanel is broken.
I assume that both mod_latest and mod_popular needs to be reverted back from list.fullordering.

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 9d74ac96266cdf8e1f43ed612fda63bde2aa49b1<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15941">issues.joomla.org/tracker/joomla-cms/15941</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 9d74ac96266cdf8e1f43ed612fda63bde2aa49b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15941">issues.joomla.org/tracker/joomla-cms/15941</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by AlexRed** [comment]
Please @frostmakk can you also help to fix articles sorting here? https://github.com/joomla/joomla-cms/issues/15856

**Pull request merged**
