### PR TITLE
Missing commas

### PR DESCRIPTION
**Pull request by demis-palma**
The problem regards RTL css. Looking at the corresponding LTR css, it's clear that a few commas went lost.

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I've tested :white_check_mark: successfully this item on 6c89cea

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 6c89cea1b1d76d2fa079f8cdf450abcdfb424797<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11362">issues.joomla.org/joomla-cms/11362</a>.</sub>

**Comment by mbabker** [comment]
At least with Isis there should be a corresponding LESS file (I don't think
I ever got to LESS for RTL in Hathor).  Can you make sure there isn't a
LESS file that needs correcting?

**Comment by demis-palma** [comment]
OK mbabker, I'll take a look and let you know.

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on 6c89cea1b1d76d2fa079f8cdf450abcdfb424797<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11362">issues.joomla.org/joomla-cms/11362</a>.</sub>

**Comment by brianteeman** [comment]
There is no RTL less file for hathor

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11362">issues.joomla.org/joomla-cms/11362</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman 
> There is no RTL less file for hathor
but there is for issis, prepering PR.

**Comment by wojsmol** [comment]
@jeckodevelopment @Lavsteph @MATsxm  @brianteeman Please test https://github.com/joomla/joomla-cms/pull/11369

**Pull request merged**
