### PR TITLE
Add some description to TinyMCE builder, to make it more clear.

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

This pull add the description to the Source and Target panel in TinyMCE builder.
Should help to make a bit more clear, how the builder works:

-----------------------
screen 2016-12-25 15 22 25 661x331
-----------------------
If there an idea with better text for explanation, please comment, I will change.

### Testing Instructions
Review my English 😄 

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by infograf768** [comment]
I guess we have to normalise `drag and drop`
We have already 2 ways
PLG_TINY_FIELD_DRAG_DROP_DESC="Enable drag and drop for uploading images"
PLG_TINY_FIELD_DRAG_DROP_LABEL="Images Drag &amp; Drop"

You add a new way:
(drag&amp;drop)

Looks like we could use `drag and drop`
Oxford Dictionnary:
https://en.oxforddictionaries.com/definition/drag_and_drop

**Comment by infograf768** [comment]
@Fedik
Can you correct the new lang string and modify to fit the 2 others in this PR?

**Comment by Fedik** [comment]
@infograf768 done 😉

**Comment by infograf768** [comment]
The label should have caps, i.e.
 +PLG_TINY_FIELD_DRAG_DROP_LABEL="Images Drag and Drop"

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 96f39a681958cad0c55479541cb5ec33cabb4817<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by Fedik** [comment]
@infograf768 I made one more changes, based on @ggppdk idea:
screen 2016-12-26 12 21 31 472x152

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 84ef965c08c236c8cd7e9b30a526e5ff02291815<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by infograf768** [comment]
OK. Remains to see if we can make the general UI (the tabs 0 1 2 vs the Presets) more user friendly. But this I guess is for another PR.

**Comment by ggppdk** [comment]
----
**1. Some corrections for language strings** 

> An existing sets of the TinyMCE panel, and options for each.

**Should be**: Existing sets of the TinyMCE panel, and options for each.

> The list of available buttons

**(Maybe) should be**: The list of available menus and buttons
 

> In each Set you can add new buttons from 

**(Maybe)** should be**: In each **"set"** you can add new buttons from 

----
**2. About easier configuration:** (i can make a PR too)

It would be most intuitive 
-- **to pad+border 2nd level TABsets** (like i showed on picture above) and
-- **use JS to update the TAB titles**, onchange of the drop-down select "Assign this layout to" (and of course on form load), to be:
 **"Public", "Registered"** (instead of "Set 2", "Set 1")

thus the user can **easily both**:
- understand what each TAB is about, (it is about configuration per VIEWing access level) 
- find the editor configuration set, of the desired access VIEWing access level without clicking them all

----
**3. About existing tinyMCE configuration there is a simple solution to avoid problems**

The existing configuration continue to be usable **until you save the plugin** (@Fedik  correct ??)
If the above is true, just **detect that there is an old configuration and display a message**:

> You existing configuration of tinyMCE editor is same for all access levels: public, registered, etc
> We have upgraded this tinyMCE editor plugin to support 1 configuration set per access level. 
>
> After you click save your old configuration will be discarded, 
> Please configure the sets below and then click save

@Fedik can you do this last one ?

**Comment by Fedik** [comment]
> 1. Some corrections for language strings

I am not strong in English 😄 
@infograf768 what do you think about suggestions?

> 2. About easier configuration

Not bad idea, but it make it more complicated to use the sets list in other places.
Example, I had a plan to add the option to user profile to allow to select one of existing set, so the "Set X" can be assigned to the User Y.
So I would not do what you have suggested, for now.

> 3 The existing configuration continue to be usable until you save the plugin

Not really, the plugin ignore an old existing configuration when render the TinyMCE,
but tries to use them  [on the plugin configuration form](https://github.com/Fedik/joomla-cms/blob/84ef965c08c236c8cd7e9b30a526e5ff02291815/plugins/editors/tinymce/field/tinymcebuilder.php#L81-L86).
I think I can try to make similar thing: use existing options (which in the form) while render the TinyMCE.

**Comment by infograf768** [comment]
For the strings, I propose these changes
`PLG_TINY_SET_TARGET_PANEL_DESCRIPTION="<strong>Existing sets of the TinyMCE panel, and options for each.</strong><br />In each set you can add new menus or buttons from <strong>the list of available menus and buttons</strong> or remove unneeded."`
and
`PLG_TINY_SET_SOURCE_PANEL_DESCRIPTION="<strong>The list of available menus and buttons.</strong><br />Use them (drag and drop) to edit or build your custom TinyMCE panel."
`

which will give:
screen shot 2016-12-27 at 12 20 52

**Comment by Fedik** [comment]
ok, I will change the strings, this evening

**Comment by infograf768** [comment]
@Fedik 
Note unrelated to this PR:
Created set `Set 3` for `Registered` using Medium Preset modified by adding the LTR and RTL buttons OR used the existing Medium Preset tagged to registered.
Logged as Author
Using the menu item Create an article in frontend.
It is always the Advanced Preset which is displayed.
So basically, this feature does not work for me here.

**Comment by Fedik** [comment]
hm, that bad, need to check more

**Comment by infograf768** [comment]
the feature is flawed. one should chose among groups and not among access which does not make sense...

**Comment by infograf768** [comment]
The problem comes from the multiple access levels one may have set on one's site.
I really think this should be redone using Users Groups instead of Access levels, i.e. using type="usergrouplist"

**Comment by ggppdk** [comment]
Similar problem a user is a member of multiple usergroups

**Comment by infograf768** [comment]
@Fedik 
Talked with @ggppdk a lot.
We should try to use usergroups (multiple)  with priority to Set # when necessary instead of Access levels which are reserved to View and not Use and make Tiny B/C as much as possible by cheking if `mode` exists in the db before updating its parameters after a 3.7.0 update.
We can create a skype chat if you like.

**Comment by Fedik** [comment]
I have update the description 

>We should try to use usergroups

well, the idea about use "usergroup" instead of "viewlevel", sounds better,
just need to find out how to :neckbeard: 
I have used "viewlevel", because old configuration also use "viewlevel" for some options, but seems it was a bad idea 😄 

maybe open new issue?

**Comment by infograf768** [comment]
@Fedik
About B/C:
My idea is to check
`if ($this->params->get('mode') !== null)`
then use old tiny (3.6.5 code)
and display a message if in admin to tell users to change the Tiny Settings.
```php
	if ($app->isClient('administrator'))
	{
			$app->enqueueMessage(JText::_('PLG_TINY_OLD_TINY'), 'warning');
	}
```
else use new code.

**Comment by infograf768** [comment]
@Fedik 
I tested successfully here modifying Tiny to be fully B/C and display a message both when using the editor in back-end (in tinymce.php) and when editing the plugin (in /layouts/plugins/editors/tinymce/field/tinymcebuilder.php)
I did it with brute force, i.e. I added the conditional in the onInit() method, then in onDisplay() method by adding in this last one the whole 3.6.5 code in the conditional.
It adds evidently a lot of lines into tinymce.php: 1987 versus 1122, but it is now B/C

**Comment by Fedik** [comment]
@infograf768 but what you made? 😉 maybe add some comments to #13387
I tried to make it without the message, to not confuse user much 😄

**Comment by infograf768** [comment]
Posted proposal for B/C on #13387

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on acd9742282c1956064eafdabe1cde45771716384<br /><br />OK, may need update after https://github.com/joomla/joomla-cms/pull/13387<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by Fedik** [comment]
now I need to fix the conflict 😄

**Comment by infograf768** [comment]
yep, eclipse did it for me 😃

**Comment by Fedik** [comment]
fixed 😄

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5c6eed129a04b651d3787114a5df591f78e6a078<br /><br />@ggppdk 

Now you can test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 5c6eed129a04b651d3787114a5df591f78e6a078<br /><br />The language strings added by this PR appear in the intended places<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 5c6eed129a04b651d3787114a5df591f78e6a078<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by dgt41** [comment]
RTC

Thanks @Fedik <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13367">issues.joomla.org/tracker/joomla-cms/13367</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz @wilsonge 
Please merge that one too

**Pull request merged**
