### PR TITLE
[4.0] Transition of Joomla's Wrapper module and component from HTML4 to HTML5

### PR DESCRIPTION
**Pull request by BaleshSrle**
Pull Request for Issue # .

### Summary of Changes
Made a transition in Joomla's WRAPPER Module and Component from HTML4 to HTML5 standard.
### Testing Instructions
Using "px" or "%" in "height" field (required by HTML5 standard).

If scrollbars do appear after selecting "No" option in "Scroll Bars" while creating wrapper element, you need to change the dimensions of wrapper element (ie. height and/or width of wrapper element).
### Expected result

To work flawlessly.

### Documentation Changes Required
Need to modify 6 files to work without any problems or hiccups:

- modules/mod_wrapper/mod_wrapper.xml

- modules/mod_wrapper/mod_wrapper.php

- modules/mod_wrapper/Helper/WrapperHelper.php

- modules/mod_wrapper/tmpl/default.php

- components/com_wrapper/tmpl/wrapper/default.xml

- components/com_wrapper/tmpl/wrapper/default.php

### CODE REVIEW

**Comment by laoneo** [comment]
@dgrammatiko can this work together with https://github.com/joomla/joomla-cms/pull/18916?

**Comment by dgrammatiko** [comment]
merge it and I will update the other PR

**Comment by laoneo** [comment]
We need to take care here on upgrades, because after the upgrade the width and height are still added in numbers only without px. So either in the code we do some checks or an upgrade script should be added. Like it is now we have a BC break we can avoid.

**Comment by laoneo** [comment]
@BaleshSrle are you willing to do the update scripts that we can test it and merge?

**Comment by ghost** [comment]
@laoneo should this PR be closed or wait for Response?

**Comment by ReLater** [comment]
> If scrollbars do appear after selecting "No" option in "Scroll Bars" while creating wrapper element, you need to change the dimensions of wrapper element (ie. height and/or width of wrapper element).

Because the width of the scrollbars vary from browser to browser I don't think that this instruction is acceptable for users. A No should be a No without otherwise necessary fine tunings.

As discussed earlier in other issues/prs you should additionally set the HTML-4 attribute "scrollbar=no" as fallback (like the rest of the world does, too) as long as there is no CSS solution or HTML5 solution for all supported browsers provided.

**Comment by laoneo** [comment]
In the current stage I would not merge it. If @BaleshSrle is willing to update it, then I would leave it open.

**Comment by laoneo** [comment]
Closing this for the same BC reason is in #19965 as it is a duplicate of #19965.

**Pull request closed without merging**
