### PR TITLE
[4.0] jpeg images

### PR DESCRIPTION
**Pull request by brianteeman**
Before this PR a jpeg image would not have a thumbnail image in the media manager AND the icon for editing an image was missing.

This PR has sql changes but does not have an update sql as its changing userdata

To test either do a complete fresh install OR go to the options for media manager and DELETE the Legal Image Extensions (File Types) and then save

Pull Request for Issue #34107

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1d8b07afd503c00a5c4ffabe7daff9bb37ac431c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34113">issues.joomla.org/tracker/joomla-cms/34113</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 1d8b07afd503c00a5c4ffabe7daff9bb37ac431c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34113">issues.joomla.org/tracker/joomla-cms/34113</a>.</sub>

**Comment by PhilETaylor** [comment]
Its 2021, maybe we should consider also allowing the modern jpg versions ? 

I wonder what versions of image the JS libraries we use for image manipulation can cope with?

https://en.wikipedia.org/wiki/JPEG_2000

Sample images
http://opf-labs.org/format-corpus/jp2k-formats/

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34113">issues.joomla.org/tracker/joomla-cms/34113</a>.</sub>

**Comment by richard67** [comment]
> This PR has sql changes but does not have an update sql as its changing userdata

@brianteeman I fully agree in this case here. It would be too risky to try to update that, and it would not really be necessary because nothing is broken which was working before if we don't update that data.

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
