### PR TITLE
Missing parts for multiple editors

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
For Joomla 3.7 there is a new way to interact with the editors (purely javascript).
There were tho 2 places that weren't following the latest changes, this PR solves these instances.

### Testing Instructions
Create some fields and some groups for these fields.
Create an article an try to insert a field through the XTD-Button (those bellow the editor or in case of tinyMCE the very last buttons).

Also try to insert a read more tag

### Expected result
Everything still works as before

### Documentation Changes Required
None, internal changes to allow core to work correctly even if there are multiple (and different) editors in the page!

### CODE REVIEW

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on 9922fe5f8b5757e04c2e57316a2dfa56dc04140c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15357">issues.joomla.org/tracker/joomla-cms/15357</a>.</sub>

**Comment by dgt41** [comment]
@wilsonge tinyMCE fixed...

**Comment by wilsonge** [comment]
Woops. Thought this was a j4 pr. good thing we did rc4 😳

**Comment by infograf768** [comment]
@dgt41
Read More is broken. See https://github.com/joomla/joomla-cms/issues/15862

**Pull request merged**
