### PR TITLE
Change community.joomla.org URL to HTTPS

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Just change community.joomla.org URL to HTTPS
### Testing Instructions

Code review.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11767">issues.joomla.org/joomla-cms/11767</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 5b5d1608e32d16395d1e5c1ad60f7694e9707bef<br /><br />I have code review successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11767">issues.joomla.org/joomla-cms/11767</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this :white_check_mark: : works34me

**Comment by zero-24** [comment]
@mbabker can you double check that? I know there was a website that was not https ready?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11767">issues.joomla.org/joomla-cms/11767</a>.</sub>

**Comment by zero-24** [comment]
I have just checked the websites repo and there it is https too. RTC than. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11767">issues.joomla.org/joomla-cms/11767</a>.</sub>

**Comment by mbabker** [comment]
> I know there was a website that was not https ready?

The community subdomain has been forcing HTTPS since its re-launch on 3.x.  Last I knew, the magazine, JRD, JED, and showcase pretty much aren't HTTPS friendly and I gave up fighting that battle since there's reluctance to enforce this.

**Comment by andrepereiradasilva** [comment]
and the forum ...

**Pull request merged**
