### PR TITLE
[4.2] CLI site scripts cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
This is part of a series of pr (broken down to smaller ones to make testing easier) that fixes several issues in the cli commands.

Make sure the title is displayed
Make sure the case of the title matches the styleguide
Make sure table column headings match the styleguide

### Site Up
image

### site Down
image

### CODE REVIEW

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38215">issues.joomla.org/tracker/joomla-cms/38215</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1f40d4c1227bb27b16733f7ad5146c4b1aa4e369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38215">issues.joomla.org/tracker/joomla-cms/38215</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1f40d4c1227bb27b16733f7ad5146c4b1aa4e369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38215">issues.joomla.org/tracker/joomla-cms/38215</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38215">issues.joomla.org/tracker/joomla-cms/38215</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
