### PR TITLE
[5.2] Compress the thumbnails

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #43272 .

### Summary of Changes

Increase the compression rate for the generated thumbnails

### Testing Instructions

Follow the issue description

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
Now we have thumbnails that are fit for purpose. Thanks!!!

Using the images in this archive to test with
[test.zip](https://github.com/joomla/joomla-cms/files/14982690/test.zip)


| Filename | Filesize kb  |          |  |
| ---------- | -------- | --------- | -------- |
|                      | Original         | Before PR          | After PR         |
| image1.png           | 44.05            | 105.85             | 6.58             |
| image2.png           | 452.83           | 75.3               | 8.41             |
| image3.png           | 30.47              |          93.39 |        9.51            |    
| image4.jpg |250.94 | 27.79 | 6.6 |
| image5.jpg | 114,55 | 26.0 | 6.87 |
| image6.jpg | 260.38 | 34.84 | 8.97 |

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 08c64043fe0e8325605a5cb0e665362b7fae5a2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43282">issues.joomla.org/tracker/joomla-cms/43282</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 08c64043fe0e8325605a5cb0e665362b7fae5a2c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43282">issues.joomla.org/tracker/joomla-cms/43282</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43282">issues.joomla.org/tracker/joomla-cms/43282</a>.</sub>

**Comment by pe7er** [comment]
Thanks @dgrammatiko !

**Pull request merged**
