### PR TITLE
com_users notes category incorrect ACL level in several installation sql

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for new Issue.

### Summary of Changes

Simple PR to correct a bug in sql installation files.
Com_users notes category as an incorrect ACL `level` `1` in several installation sql files.

Should work like this:
- Level 0: Root asset (root.1)
- Level 1: Component (com_users)
- Level 2: Category (com_users.category.7)

So it should be level 2.

### Testing Instructions

Code review.

### Documentation Changes Required

None.

### CODE REVIEW

**Review by ggppdk — APPROVED** [review]

**Comment by sanderpotjer** [comment]
Tested succesfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12852">issues.joomla.org/tracker/joomla-cms/12852</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@ggppdk @sanderpotjer please Mark as tested with success in the tracker.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on e8a434286c3899c04c39fb7eea9214a7c0656625<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12852">issues.joomla.org/tracker/joomla-cms/12852</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on e8a434286c3899c04c39fb7eea9214a7c0656625<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12852">issues.joomla.org/tracker/joomla-cms/12852</a>.</sub>

**Comment by sanderpotjer** [comment]
@andrepereiradasilva earlier I couldn't markt it as tested (see https://github.com/joomla/jissues/issues/911), but now it worked!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12852">issues.joomla.org/tracker/joomla-cms/12852</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12852">issues.joomla.org/tracker/joomla-cms/12852</a>.</sub>

**Pull request merged**
