### PR TITLE
[4.0] Add margins to header title

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add top and bottom margins to header title.

### Testing Instructions
Apply PR
Run npm i
Log in to administration area
Reduce browser's viewport to mobile

### Actual result BEFORE applying this Pull Request
header-no-margin

### Expected result AFTER applying this Pull Request
header-margin

### CODE REVIEW

**Comment by infograf768** [comment]
@Quy 
This PR adds margin top and bottom also when viewport is desktop

BEFORE patch
Screen Shot 2020-07-11 at 06 51 03

AFTER patch
Screen Shot 2020-07-11 at 06 52 39

I suggest to add these margins only when we are in mobile view, i.e. change
```
    @include media-breakpoint-down(xs) {
      width: 100%;
    }
```
to
```
    @include media-breakpoint-down(xs) {
      width: 100%;
      margin-top: 1rem;
      margin-bottom: 1rem;
    }
```

we will get
headertitle

**Comment by Quy** [comment]
Much better! Thanks.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 5e367b0ab977fe7fcfb52c6ace483193b2e676dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30069">issues.joomla.org/tracker/joomla-cms/30069</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 5e367b0ab977fe7fcfb52c6ace483193b2e676dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30069">issues.joomla.org/tracker/joomla-cms/30069</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30069">issues.joomla.org/tracker/joomla-cms/30069</a>.</sub>

**Comment by infograf768** [comment]
Restarted drone.

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
