### PR TITLE
Fix some strange code

### PR DESCRIPTION
**Pull request by zero-24**
This PR fix some nonsense code.
### The old way

``` php
$false = false;
[some checks]
return $false;
```
### The new way

``` php
[some checks]
return false;
```
###### Note

I'm execluding `administrator\components\com_joomlaupdate\restore.php` as it is 3rd party code.
### How to test
- Access the following Backend edit views:
  - com_languages --> language
  - com_menus --> menu
  - com_modules --> modul
  - com_plguins --> plugin
  - com_templates --> style

or just review that code that is maybe the easyest version ;)

### CODE REVIEW

**Comment by n9iels** [comment]
@test looks good to me :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7761">issues.joomla.org/joomla-cms/7761</a>.</sub>

**Comment by chmst** [comment]
@test - Good find  :) as much as I see in my  test environment, it is all fine.

**Comment by zero-24** [comment]
Thanks. RTC'ing. Just fixed some merge conflicts.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7761">issues.joomla.org/joomla-cms/7761</a>.</sub>

**Comment by zero-24** [comment]
Thanks @Bakual

**Pull request merged**
