### PR TITLE
[4.0] drop unused assets

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Drop some legacy, unused scripts

### Info
- sortablelist has been replaced by dragula
- ajax-chosen and chosen has been replaced by fancy-select
- tab-state has been replaced by Joomla-tabs
- recaptcha just removed the minified version and renamed it to .es5.js so the build tools will reminify it

### CODE REVIEW

**Comment by brianteeman** [comment]
you're going to hate me for this - shouldn't we keep the legacy scripts so that non-core extensions don't have to rewrite everything?

**Comment by dgrammatiko** [comment]
>  shouldn't we keep the legacy scripts so that non-core extensions don't have to rewrite everything

Well, if that is the case then we did a **really bad job** when we used the old HTMLHelper API to wire the new scripts with the old end points

**Comment by wilsonge** [comment]
I don't think the tabs custom element does keep the state across requests does it?

Agree with @dgrammatiko that if we have existing `HtmlHelper` scripts rewire to things that are largely b/c this is ok.

**Comment by brianteeman** [comment]
> I don't think the tabs custom element does keep the state across requests does it?

I think it does. What it doesn't do is let you link to a tab see
https://github.com/joomla/joomla-cms/issues/25359

> Agree with @dgrammatiko that if we have existing HtmlHelper scripts rewire to things that are largely b/c this is ok.

Thats great to hear

**Comment by dgrammatiko** [comment]
> I don't think the tabs custom element does keep the state across requests does it?

In theory it does. I mean the code initially covered these scenarios:
- local storage data from a previous visited page (same regex as in tab state)
- activation of a tab through a url hash (eg some-url#tab1)

**Comment by SharkyKZ** [comment]
Sortablelist is used https://github.com/joomla/joomla-cms/blob/1ec557f6e8cfceec031c58cc4280d05b4f3289cc/libraries/cms/html/sortablelist.php

**Comment by SharkyKZ** [comment]
>activation of a tab through a url hash (eg some-url#tab1)

This does not work.

**Comment by brianteeman** [comment]
@SharkyKZ I keep saying that but no one listens

**Comment by dgrammatiko** [comment]
> Sortablelist is used

Uhhhh, my bad

**Pull request closed without merging**
