### PR TITLE
[4.1] Web Services - Media - core component

### PR DESCRIPTION
**Pull request by brianteeman**
The media webservices plugin is missing from the list of core extensions

Test either by code review or by filtering the list of installed extensions by core/non-core

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 877a2bfde821cfa15711eccff85c93d5706f0bd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36882">issues.joomla.org/tracker/joomla-cms/36882</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 877a2bfde821cfa15711eccff85c93d5706f0bd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36882">issues.joomla.org/tracker/joomla-cms/36882</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36882">issues.joomla.org/tracker/joomla-cms/36882</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Comment by Razzo1987** [comment]
@brianteeman , sorry for commenting on this old PR.
But I was looking into how the media endpoint works and came across it.
I noticed that the list fixed with this PR is also missing:
- fields
- workflow
Does that make sense? I can submit the PR myself in the next few days ;)
Thanks!

**Comment by richard67** [comment]
> But this is a file I don't know and I don't know how it works, so I was asking someone who has already worked on it.

@Razzo1987 So if you don’t know how that file work, how can you say something is missing?

> For the field, I expect it just needs to be added,

Fields are not extensions.

The file defines which extensions in the extensions table are core. The extension „com_fields“ is already in.

> but for the workflow, having never really used it, I have no idea if it needs to be added or not.

Single workflows are not extensions. The „com_workflows“ extension is already included.

Again: If you don’t know what the file is good for, you cannot really blame it to have errors. You may ask questions, but stop to make false assumptions.

**Comment by brianteeman** [comment]
@Razzo1987 to avoid confusion and avoid any misunderstanding the items listed in this file are used to identify the core extensions as seen in the Extensions Manager screen. So if you filter by non-core extensions on a clean install there should be no extensions listed

**Pull request merged**
