### PR TITLE
Remove reference to joomlacode.org (2)

### PR DESCRIPTION
**Pull request by PhilETaylor**
Remove reference to joomlacode.org - as Joomla code is dead (soon) https://developer.joomla.org/news/840-bye-bye-joomlacode.html

(sorry for 2 PR's, on mobile)

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry Phil the reference is still valid as the information referred to can be found on developer.joomla.org

**Comment by PhilETaylor** [comment]
ah ok, maybe better linked to https://developer.joomla.org/joomlacode-archive/issue-26026.html instead then?

**Comment by PhilETaylor** [comment]
I wasn't aware that the project to export and archive the issues was a success - @mbabker must be a frigging wizard ;-)

**Comment by brianteeman** [comment]
That happened a few years ago

**Pull request closed without merging**
