### PR TITLE
[5.1] Fix category select in CategoryModal field

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/42379.

### Summary of Changes

Fix category select in CategoryModal field.
Add missing `extension` URL parameter.

### Testing Instructions
Create a menu item "List Contacts in a Category", click on "Select a Category"

### Actual result BEFORE applying this Pull Request
In popup you will get categories for Article

### Expected result AFTER applying this Pull Request
In popup you will get categories for Contact

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Reference:
 - https://github.com/joomla/joomla-cms/pull/42293

### CODE REVIEW

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 851c4ab70e05c07af465855eb41f9e15fe89dac3<br /><br />Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42391">issues.joomla.org/tracker/joomla-cms/42391</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 851c4ab70e05c07af465855eb41f9e15fe89dac3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42391">issues.joomla.org/tracker/joomla-cms/42391</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42391">issues.joomla.org/tracker/joomla-cms/42391</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you very much for the fix @Fedik ! 
And many thanks to @chmst and @drmenzelit for testing.

**Pull request merged**
