### PR TITLE
s/belons/belongs

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/belons/belongs

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 3957cdc45d4d189ec881424763d860c537c605c9<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23015">issues.joomla.org/tracker/joomla-cms/23015</a>.</sub>

**Comment by richard67** [comment]
I have not tested this item.<br /><br />Code review + check that this PR covers all occurrences of wrong English "belons" (case-insensitive) in Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23015">issues.joomla.org/tracker/joomla-cms/23015</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3957cdc45d4d189ec881424763d860c537c605c9<br /><br />Code review + check that this PR covers all occurrences of wrong English "belons" (case-insensitive) in Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23015">issues.joomla.org/tracker/joomla-cms/23015</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23015">issues.joomla.org/tracker/joomla-cms/23015</a>.</sub>

**Pull request merged**
