### PR TITLE
[4.0] [plg_system_webauthn] Correct subpackage

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Corrects subpackage in doc block.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 1e14ca6b97e8ce5e4abc8076380724a83e7e89f5<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28245">issues.joomla.org/tracker/joomla-cms/28245</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1e14ca6b97e8ce5e4abc8076380724a83e7e89f5<br /><br />by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28245">issues.joomla.org/tracker/joomla-cms/28245</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28245">issues.joomla.org/tracker/joomla-cms/28245</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
