### PR TITLE
Updating copyright date to 2016

### PR DESCRIPTION
**Pull request by infograf768**
This PR updates the copyright to Open Source Matters only.

3rd party libraries (for example fof) are not updated.

### CODE REVIEW

**Comment by brianteeman** [comment]
Do we really need to update the old SQL files?

**Comment by infograf768** [comment]
I think we should as people may still update from 2.5

**Comment by brianteeman** [comment]
Yes but don't they still finish with the final 3.x SQL so overwriting those changes anyway?

**Comment by brianteeman** [comment]
Just spotted (on my phone) this PR only looks at files in the /administrator folder. Only 300 files are modified

**Comment by infograf768** [comment]
You are mistaking. It touches all included test units

**Comment by brianteeman** [comment]
Weird - thats a bug on the mobile app as that only said 301 files

**Comment by infograf768** [comment]
Can be merged on review.

**Pull request merged**
