### PR TITLE
[#33449] Added check for "chzn-done" class name in order to let Chosen skip SELECT elements

### PR DESCRIPTION
**Pull request by w00fz**
In the previous version of Chosen, one could render a `select` element with class name `chzn-done` so that Chosen would skip it and not try to treat it with the Chosen UI.

This is no longer possible since version 3.2.3 and no alternative way to render regular select is provided.

Proposed is the addition of the check for the class `chzn-done` like it used to be.

[JoomlaCode [#33449]](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33449&start=0)

### CODE REVIEW

**Comment by roland-d** [comment]
Almost a year to the date but still valid. I have been checking this and getting data attributes into the XML forms needs some serious thinking. As @stutteringp0et already said, we already modified the chosen library, this change is not going to make it worse as it is.

Sure, we shouldn't be modifying external libraries but here it already happened. Having tested the latest version of Chozen it is unusable at the moment. So with both the new version not being usable and adding data attributes to XMLs not an easy fix, I suggest we merge as it is.

**Comment by JoomliC** [comment]
@roland-d +1 to merge this.
I'm currently working on the color picker, and since 3.2.3, the simple color picker introduced in core by @nonumber is broken (https://github.com/joomla/joomla-cms/pull/807)
In the PR i'm working on, i have added to select a data-chosen="true" attribut which solves the issue, but until my PR will be committed, @w00fz 's  PR fixes the simple color picker too! ;-)

**Comment by timhaeuser** [comment]
Error
The patch could not be applied because the repository is missing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3274">issues.joomla.org/joomla-cms/3274</a>.</sub>

**Comment by roland-d** [comment]
Closing this in favour of #7736 which has an active repo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3274">issues.joomla.org/joomla-cms/3274</a>.</sub>

**Pull request closed without merging**
