### PR TITLE
[4.0] Fix duplicate "Sample Data - Multilingual" plugin in database on 4.0 sites which have been updated from 3.10

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #30929 .

### Summary of Changes

This pull request (PR) adds the necessary SQL statements to delete the duplicate record for plg_sampledata_multilang in the extension table to the update SQL scripts.

I order to not add again a new update SQL script, I've decided to modify the existing script 4.0.0-2020-09-27.sql, which hasn't been released yet and so can be modified, as we don't support updates between nightlies.

If a new Beta or whatever else release of J4 will be made before this PR will be merged, I'll have to move the new statement to a new update SQL script then.

In addition, this PR deletes the update SQL script `4.0.0-2018-06-11.sql` which causes the duplicate record. In fact the other one `4.0.0-2019-03-31.sql` which was added later with commit https://github.com/joomla/joomla-cms/commit/fc0d2ea3c8e9f9451a1bdda8311e4c7640e7edef#diff-97d026690fd483a67b57a74953ef4a50 caused the problem, but because no other SQL script in between those references the record for that plugin, it doesn't matter which of the duplicate insert statements is deleted, and so I've chosen the first one because 1. it saves us a complete update SQL script, and 2. the deleted one had the wrong "enabled" status.

#### Test 1: Reproduce the issue by updating a 3.10 to 4.0 Beta 4

1. Update a clean installation (i.e. no 3rd party extensions) of current 3.10-dev or latest 3.10 nightly or 3.10-alpha2 to 4.0 Beta 4, using the following custom URL for Live Update or the following update package for Upload & Update:
- Custom update URL = [https://update.joomla.org/core/test/310to4_list.xml](https://update.joomla.org/core/test/310to4_list.xml)
- Update package = [https://github.com/joomla/joomla-cms/releases/download/4.0.0-beta4/Joomla_4.0.0-beta4-Beta-Update_Package.zip](https://github.com/joomla/joomla-cms/releases/download/4.0.0-beta4/Joomla_4.0.0-beta4-Beta-Update_Package.zip)
2. After successful update, go to the "System - Manage - Plugins" and check if there are plugins with name "Sample Data - Multilingual".
Result: There are two plugins with that name, one of them is disabled.
3. Go to "System - Manage - Extensions" and search for "Sample Data - Multilingual".
Result: There are two plugins with that name, one of them is disabled.

#### Test 2: Verify that this PR fixes the issue when updating a 4.0 Beta 4 which has the issue

This test has to be executed after the previous test "Test 1".

1. Update the installation used in the previous test "Test 1" to current 4.0-dev plus the fix from this PR applied, using the following custom URL for Live Update or the following update package for Upload & Update:
- Custom update URL = [https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30945/downloads/36230/pr_list.xml](https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30945/downloads/36230/pr_list.xml)
- Update package = [https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30945/downloads/36230/Joomla_4.0.0-beta5-dev+pr.30945-Development-Update_Package.zip](https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30945/downloads/36230/Joomla_4.0.0-beta5-dev+pr.30945-Development-Update_Package.zip)
2. After successful update, go to the "System - Manage - Plugins" and check if there are plugins with name "Sample Data - Multilingual".

Result: There is only one plugin with name "Sample Data - Multilingual", which is enabled. The first one of the two duplicate plugins has been deleted.

#### Test 3: Verify that this PR fixes the issue when updating from 3.10-dev

Repeat test "Test 1", i.e. start again from 3.10, but this time use the update package of latest 4.0 nightly plus the fix of this PR included. The custom update URL and the download package are the same as used in the previous test "Test 2".

Result: There is only one plugin with name "Sample Data - Multilingual", which is enabled.

### Actual result BEFORE applying this Pull Request

After an update from 3.10 to 4, there are two plugins with name "Sample Data - Multilingual". They are equal, except one of them is disabled.

### Expected result AFTER applying this Pull Request

After an update from 3.10 to 4, there is only one plugin with name "Sample Data - Multilingual", which is enabled.

After update from a 4 Beta 4 which had the issue to a future 4 version which contains the fix from this PR, one of the duplicate plugins "Sample Data - Multilingual" will be deleted.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
I've just fixed a few things in the testing instructions. Now it's really ready for testing.

**Comment by richard67** [comment]
@brianteeman Would be great if you could find some time to give this PR a test. Thanks in advance.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7da4b2ae5f21f93f15dd025d608562cf6221efee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30945">issues.joomla.org/tracker/joomla-cms/30945</a>.</sub>

**Comment by richard67** [comment]
@brianteeman I'm a bit disappointed that you don't test PR's for issues opened by you. Or is it just when I am the PR author?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7da4b2ae5f21f93f15dd025d608562cf6221efee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30945">issues.joomla.org/tracker/joomla-cms/30945</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30945">issues.joomla.org/tracker/joomla-cms/30945</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks for testing and merging.

**Comment by richard67** [comment]
I've just noticed that this PR causes an SQL error when updating e.g. 4.0 Beta 4 to latest nightly on MySQL, and very likely also on MariaDB.

The reason is that MySQL can't handle a subquery on the same table in an UPDATE or DELETE statement.

Will check if that's a problem with PostgreSQL, too, and then make a PR to fix it.

No idea why that hasn't shown up when testing.

Other database types, e.g. MS SQL server and Oracle, can handle that, just by the way.

Update: Not a problem on PostgreSQL.

**Comment by richard67** [comment]
PR to fix my mistake with MySQL will be #31171 . I just need a bit time to test all scenarios and provide complete testing instructions. For PostgreSQL this PR here seems to be fine.

**Pull request merged**
