### PR TITLE
Prevent SQL error in TagsHelper::addTagMapping() when zero tags need to be mapped to a record

### PR DESCRIPTION
**Pull request by ggppdk**
Pull Request for Issue #19760

### Summary of Changes
TagsHelper::addTagMapping() may try to insert zero tag mappings to DB table
`#__contentitem_tag_map`
causing an unhelpful SQL , and record form saving to fail

We may as well return true, and just not try to insert zero mappings

### Testing Instructions

In Joomla Tags management

1. Create a new tag:
 title: ocean
 alias: the-sea

2. In article form try to add (and then save the form) a tag that causes duplicate alias, try to add a new tag titled:
 the sea

NOTE: the article must not have any other tags just try to add a single tag, the above one

### Expected result

You can add tag or you get duplicate tag alias error or some other good feedback

### Actual result

You get an SQL syntax error, without any indication of what happened

### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
So this kills the error message and lets you save the article but there is no indication that the tag was not created.

**Comment by ggppdk** [comment]
> So this kills the error message and lets you save the article but there is no indication that the tag was not created.

Exactly

Also i see that unlikely Tables for other records the 
check() method of Tags does not check for duplicate alias, like it is done in other tables

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_tags/tables/tag.php#L91-L102

e.g. the check() for Fields here will return an error and set an error, if calculated alias is already in use:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/tables/field.php#L111-L116

Setting such an error in the Tags table would make a lot of sense ... if we are inside that Tags Edit From

if tag is created via the record form of some component
e.g. via article form then the user is not able to set the tag aliases only the tag titles, 
but at least it would be good feedback instead of the SQL Error

i will make more commits for a more complete fix

**Comment by ghost** [comment]
> i will make more commits for a more complete fix

@ggppdk does this mean not to test this Pull Request?

**Comment by ggppdk** [comment]
Yes, please wait

**Comment by ghost** [comment]
@ggppdk whats the State of this Pull Request?

**Comment by ghost** [comment]
I suggest to close this PR due the lack of response by @ggppdk. In the meantime i add the label "needs new owner".

**Pull request closed without merging**
