### PR TITLE
[4.0] Privacy filter widths

### PR DESCRIPTION
**Pull request by brianteeman**
This PR allows the filters in the com_privacy component to get the correct width

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 860dc4c568b62e3b45e47c3ae886d91c8805e3de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24954">issues.joomla.org/tracker/joomla-cms/24954</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 860dc4c568b62e3b45e47c3ae886d91c8805e3de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24954">issues.joomla.org/tracker/joomla-cms/24954</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24954">issues.joomla.org/tracker/joomla-cms/24954</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
