### PR TITLE
[4.0] com_finder improvements + polyfills/mootools removal

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

- Fix variable with double dollar sign
- Remove references to polyfills that got merged from staging
- Remove references to Mootools
- Improvements to com_finder results page

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on e67273af24bccf1016bfcc6a33e21228b5b23da3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16324">issues.joomla.org/tracker/joomla-cms/16324</a>.</sub>

**Comment by brianteeman** [comment]
Really not sure why you made this change - plus it looks bad

screenshotr14-48-52

**Comment by C-Lodder** [comment]
@brianteeman - if there were some errors, please try again now as conflicts are solved.

I moved the "How to search" to a popover as it was some long winded paragraph and on smaller viewports, like the one I'm using, I was having to scroll down to access the select boxes.

**Comment by brianteeman** [comment]
but now you have made a popover that is unusable on a mobile device and it was an optional setting before whereas now it is always present

**Comment by brianteeman** [comment]
Also I am now getting 
The file marked for modification does not exist: administrator/components/com_contact/tmpl/contacts/modal.php

as a result of #16319

**Comment by C-Lodder** [comment]
@brianteeman - Reworked the results page a little. Added parameter back in and displayed the content as a outlined card.

**Comment by brianteeman** [comment]
Still cant apply https://github.com/joomla/joomla-cms/pull/16324#issuecomment-304667818

**Comment by C-Lodder** [comment]
No idea. Must have been something to do with: https://github.com/joomla/joomla-cms/pull/16319

Perhaps try re-fetching the PR's with `com_patchtester` and then applying it.....or try manually fetching the PR via command line using:

```
$ git fetch upstream pull/16324/head:moo2
$ git checkout moo2
```

**Comment by brianteeman** [comment]
Please check all the options. For example expand advanced search no longer has any effect

**Comment by brianteeman** [comment]
Also with this PR applied I have lost the green on the toggles and the muted text
screenshotr15-52-13
screenshotr15-52-37

**Comment by C-Lodder** [comment]
@brianteeman - fixed switcher labels and auto expand advanced search

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 327326bbf2d9aa5612bf7a5168d96f15e44d4251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16324">issues.joomla.org/tracker/joomla-cms/16324</a>.</sub>

**Comment by C-Lodder** [comment]
Thanks Brian

**Pull request merged**
