### PR TITLE
Deprecate route wrapper

### PR DESCRIPTION
**Pull request by laoneo**
Deprecate route wrapper.

### CODE REVIEW

**Comment by brianteeman** [comment]
Is there a reason that this is being deprecated and removed? 

I assume that there is so please can you document it here. This will help if someone is looking to see why it has gone in the future

Thanks in advance

**Comment by wilsonge** [comment]
Same reason as https://github.com/joomla/joomla-cms/pull/16446

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 808ef9665917a7766c0939bc2f3024c133dd6028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16829">issues.joomla.org/tracker/joomla-cms/16829</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for providing the reference @wilsonge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16829">issues.joomla.org/tracker/joomla-cms/16829</a>.</sub>

**Pull request merged**
