### PR TITLE
[com_config] add js message titles

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This simple PR adds the js message titles in com_config (application and component view).
#### Testing Instructions
1. Use latest staging
2. Go to Configuration and send a test mail (or any behaviour that returns a js message - ex: permissions). Result: JS message WITHOUT the title. 
   image
3. Apply patch
4. Repeat step 1. (remember to clear browser cache in config page). Result: JS message WITH the title. 
   image

This should work for all message, notice, warning and error messages in com_config and component config.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6d461c2cfb18e6879edc0db472d48bfcbe69eb0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10768">issues.joomla.org/joomla-cms/10768</a>.</sub>

**Comment by Ruchiranga** [comment]
I have tested this item :white_check_mark: successfully on 6d461c2cfb18e6879edc0db472d48bfcbe69eb0c<br /><br />before

after<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10768">issues.joomla.org/joomla-cms/10768</a>.</sub>

**Comment by Ruchiranga** [comment]
screen shot 2016-06-10 at 11 30 50
screen shot 2016-06-10 at 11 30 49<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10768">issues.joomla.org/joomla-cms/10768</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10768">issues.joomla.org/joomla-cms/10768</a>.</sub>

**Pull request merged**
