### PR TITLE
Finder english correction

### PR DESCRIPTION
**Pull request by brianteeman**
##### Before

No search results (in English-UK) could be found for query: %s.
##### After

No search results in English (en-GB) could be found for query: %s.

thanks @Hils  for spotting this

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 81ac0abff2f7ba0d71fc3fafb773f0fcda49e799<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9985">issues.joomla.org/joomla-cms/9985</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 81ac0abff2f7ba0d71fc3fafb773f0fcda49e799<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9985">issues.joomla.org/joomla-cms/9985</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9985">issues.joomla.org/joomla-cms/9985</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 81ac0abff2f7ba0d71fc3fafb773f0fcda49e799<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9985">issues.joomla.org/joomla-cms/9985</a>.</sub>

**Pull request merged**
