### PR TITLE
Banners - fix track date

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #24649 .

### Summary of Changes
correct timestamp for postgresql

### Testing Instructions
see #24649

### Expected result
no error on postgresql

### Actual result
error on postgresql

### CODE REVIEW

**Comment by twister65** [comment]
Yes, it works too. You've just forgotten the click track:
https://github.com/alikon/joomla-cms/blob/aee4b63f8747a06afcc03494cddeba66e79f518b/components/com_banners/models/banner.php#L81

**Comment by twister65** [comment]
In Components->Banners->Tracks, the hour is not localized.
I think, it is another issue.

**Comment by alikon** [comment]
yes another issue

**Comment by twister65** [comment]
I think, this is due to the timezone offset which is null by default.
https://github.com/alikon/joomla-cms/blob/aee4b63f8747a06afcc03494cddeba66e79f518b/libraries/src/Factory.php#L544

**Comment by twister65** [comment]
Made this issue #24655 .

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 2ae67e14ff45d4c9cc51787ad02cfb9b9daa43f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24652">issues.joomla.org/tracker/joomla-cms/24652</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2ae67e14ff45d4c9cc51787ad02cfb9b9daa43f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24652">issues.joomla.org/tracker/joomla-cms/24652</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Comment by twister65** [comment]
Please, see https://github.com/joomla/joomla-cms/pull/24651#issuecomment-485439618.
I apologize, I did not pay attention during my test.
See PR #8825 too.

**Comment by twister65** [comment]
The banners page shows an overview of how many impressions and clicks a banner has received, while the tracks page shows you impression and click data based upon each hour of the day.
See:
https://github.com/joomla/joomla-cms/pull/8825#issuecomment-410870773

**Comment by twister65** [comment]
This PR should not be merged, it raises a new issue (see https://github.com/joomla/joomla-cms/pull/24651#issuecomment-485439618).
Please, test this PR #24651 instead.

**Pull request merged**
