### PR TITLE
[4.0] Move the manifest files to the back end

### PR DESCRIPTION
**Pull request by laoneo**
Moves the manifest files of com_wrapper and com_mailto to the back end.

### CODE REVIEW

**Comment by brianteeman** [comment]
can you update the files so that they are correct

**Comment by laoneo** [comment]
What update?

**Comment by brianteeman** [comment]
The files in the admin folder section

https://github.com/joomla/joomla-cms/blob/c154aa2bd475d668bfbbdd58ddd6b6a2220f96f0/administrator/components/com_mailto/mailto.xml#L25

**Comment by laoneo** [comment]
Guess I need to do that then for all files as I completely forgot to update the manifest files with the new files from all the service changes. Will do that then in another pr.

**Comment by brianteeman** [comment]
OK - just did a quick sample test and they are all outdated

**Comment by mbabker** [comment]
Should not be merged until a decision on https://github.com/joomla/joomla-cms/issues/18246 is made.

**Comment by laoneo** [comment]
Actually this pr fixes the discrepancy in core that every component needs an administrator folder :smirk:

**Comment by laoneo** [comment]
So can this being merged then?

**Comment by wilsonge** [comment]
This has broken the installer

```
<br />
<b>Warning</b>:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/Users/george/Sites/joomla-cms/components/com_mailto/mailto.xml&quot; in <b>/Users/george/Sites/joomla-cms/libraries/src/Installer/Installer.php</b> on line <b>2032</b><br />
<br />
<b>Warning</b>:  simplexml_load_file(): I/O warning : failed to load external entity &quot;/Users/george/Sites/joomla-cms/components/com_wrapper/wrapper.xml&quot; in <b>/Users/george/Sites/joomla-cms/libraries/src/Installer/Installer.php</b> on line <b>2032</b><br />
```

**Comment by wilsonge** [comment]
Fixed with 024d943c10

**Comment by brianteeman** [comment]
Don't you need to create update SQL as well?

**Comment by alikon** [comment]
plus
last time i've  tryed to run 4.x on postgresql
`
postgres@joomla WARNING:  nonstandard use of \\ in a string literal at character 113
 [16147] postgres@joomla HINT:  Use the escape string syntax for backslashes, e.g., E'\\'.
`

should we take care about namespacing ? ... more

**Comment by alikon** [comment]
ops pgsql

**Comment by wilsonge** [comment]
@laoneo please can you sort out the update SQL tomorrow

**Comment by laoneo** [comment]
Pr with update scripts #22138.

**Pull request merged**
