### PR TITLE
TinyMCE fix text dragging

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #37054 .

### Summary of Changes
Update our `jdragndrop` plugin to work only with "Files".

### Testing Instructions
Run `npm install`, and follow #37054 
Would be nice to test in all Browsers.

### Actual result BEFORE applying this Pull Request
Text drag is broken
Image upload works

### Expected result AFTER applying this Pull Request
Text drag works
Image upload works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Added release blocker label as inherited from the issue.

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on 9f521c21f1461d06031e42220cf2d909b6072c9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9f521c21f1461d06031e42220cf2d909b6072c9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by roland-d** [comment]
@Fedik After checking out this branch, running `npm ci` and testing the editor, the drag and drop of text works but drag and drop of images no longer works. I do not get the dotted line around the block nor does anything happen when I drop the image on the editor.

This is running Firefox 105.0.2 on Linux.

**Comment by Fedik** [comment]
Thanks for checking that. I have fixed Firefox. Please test again

**Comment by N6REJ** [comment]
I have tested this item :red_circle: unsuccessfully on c683ae2d98bc72343d57259871b7d82400fa4bf5<br /><br />Works in firefox but not in chrome
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by Fedik** [comment]
I set it back to Pending

**Comment by Fedik** [comment]
@N6REJ are you sure it not a browser cache?
For me works in Chrome and Firfox

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on c683ae2d98bc72343d57259871b7d82400fa4bf5<br /><br />Before applying the patch I cannot select and move the text. After applying the patch I am able to upload a image via drag n drop and also text can be selected and moved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on c683ae2d98bc72343d57259871b7d82400fa4bf5<br /><br />@Fedik Must have been.  works fine today.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38900">issues.joomla.org/tracker/joomla-cms/38900</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
