### PR TITLE
[4.0] Deprecate JPATH_COMPONENT path constants

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #12415

If I understood correctly then the deprecation notice only needs to be in this one file

### CODE REVIEW

**Comment by HLeithner** [comment]
Shouldn't this pr also change all core usages as allon mentioned?

**Comment by HLeithner** [comment]
Also I not sure if the IDEs dedtect the deprecation die position, I will check this when I'm home or someone else can do this.

I would change the deprecation should be something more help full like: "Use JPATH_SITE .'/components/com_....' or JPATH_ADMINISTRATOR...."

**Comment by laoneo** [comment]
I wouldn't do them in one pr, because I think we need to test then every removal.

**Comment by mbabker** [comment]
We should do these as doc blocks, like [`_QQ_`](https://github.com/joomla/joomla-cms/blob/2cd00da1ad34ca39dc4d1ffd0f24e930db04aa3d/libraries/src/Language/Language.php#L15-L18) has.  The phpDocumentor pass picks these up and we can show the deprecations on the API docs site, see https://api.joomla.org/cms-3/packages/default.html and how it has many of the global constants that are found in the libraries.

**Comment by brianteeman** [comment]
Is that better for you @mbabker

**Comment by mbabker** [comment]
It should be right above the `define()` line, not the `if (defined())` check.  Otherwise, yes, that's better.

**Comment by HLeithner** [comment]
Could we please get a useful deprecation message? A bit better documentation is not wrong.

I hate the deprecation notices in J3 with no replacement and in reality there was never a new way and you have to use the deprecated functions.

thx

**Comment by wilsonge** [comment]
> Could we please get a useful deprecation message? A bit better documentation is not wrong.

Please give a suggestion - there is no intended replacement here??

> I hate the deprecation notices in J3 with no replacement and in reality there was never a new way and you have to use the deprecated functions.

I've edited out your bad language above. This is a public tracker. Please no swearing and be polite to the other volunteers here.

**Comment by brianteeman** [comment]
> It should be right above the define() line, not the if (defined()) check. Otherwise, yes, that's better.

so in that case I should do it for each of the variants?

**Comment by brianteeman** [comment]
Hey at least I am adding a comment to the code that is actually referring to the correct thing. Unlike some other pull requests I can mention that have beautiful comments copy pasted from something completely different

**Comment by mbabker** [comment]
> so in that case I should do it for each of the variants?

Yes please.  On https://api.joomla.org/framework-1/packages/default.html if you click the `_QQ_` constant it actually does show the `@deprecated` tag from the file's doc block.  So having a proper doc block for each `define()` will do the same with the rendering for these constants (and in general it wouldn't be a bad idea to do proper doc blocks for all the constants found in the libraries, another PR for someone who's interested in improving docs).

**Comment by HLeithner** [comment]
> I've edited out your bad language above. This is a public tracker. Please no swearing and be polite to the other volunteers here.

thx

> Please give a suggestion - there is no intended replacement here??

I already did an example. Here a more complete one.

"Use JPATH_SITE or JPATH_ADMINISTRATOR concationed with /components/< your component >"

**Comment by laoneo** [comment]
Would be nice to get an agreement here about the message to deprecate it.

**Comment by mbabker** [comment]
I added full doc blocks for many of the library defined constants in https://github.com/joomla/joomla-cms/commit/0bfb0b5410f117797e80a5fd95343c061592ad57

Just copy those, add `@deprecated` tag as you would a method, and have a nice day.

**Comment by laoneo** [comment]
@brianteeman can you add the suggestion from @mbabker and then we are good to go here

**Comment by brianteeman** [comment]
@laoneo done as requested

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
