### PR TITLE
[4.0] JText capitalisation

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted these two JText constants that are not allcaps. Code review only

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7fbb1984a5e4a35a818fcfd7d486981c1faecc23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32659">issues.joomla.org/tracker/joomla-cms/32659</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7fbb1984a5e4a35a818fcfd7d486981c1faecc23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32659">issues.joomla.org/tracker/joomla-cms/32659</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32659">issues.joomla.org/tracker/joomla-cms/32659</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
