### PR TITLE
[3.5.0 Beta] Fixed storing of the permissions

### PR DESCRIPTION
**Pull request by roland-d**
## Problem

Changing permissions won't take effect and only the old settings remain.
## How to test
1. Go to System -> Global Configuration
2. Click on the Server Tab
3. Make sure Database Type is set to MySQLi
4. Click on the Permission tab
5. Change permissions and see that Joomla says they are stored
6. Reload page, permissions have old value again
7. Apply patch
8. Change permissions and see that Joomla says they are stored
9. Reload page, permissions now have the new value

This works for the global permissions and for the component permissions.
If you are using the PDO driver, there is another fix for that at #8322 

Do note, these patches cannot be used together as they change the same file.

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on c5698993906f821855c515e2868ff414db9fcd69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8343">issues.joomla.org/joomla-cms/8343</a>.</sub>

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on c5698993906f821855c515e2868ff414db9fcd69<br /><br />Tested with MySQLi and MySQL PDO (when combined with the mentioned #8322) and both worked successfully with the patch applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8343">issues.joomla.org/joomla-cms/8343</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c5698993906f821855c515e2868ff414db9fcd69<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8343">issues.joomla.org/joomla-cms/8343</a>.</sub>

**Comment by wilsonge** [comment]
Merged as we have 3 good tests - thanks guys :)

**Comment by Fedik** [comment]
ah, hold on! you are too fast hahah :smile: 
The Modules permission  still does not save anything ...
Sorry!

**Comment by roland-d** [comment]
@Fedik Thanks for that feedback. I will create a separate PR for that, completely did not think of module permissions :)

**Comment by roland-d** [comment]
@Fedik I can't reproduce the issue with modules. Anything specific to do?

**Comment by Fedik** [comment]
hm, no, nothing specific, just change and refresh the page ..
I checked with MySQLi and on Global Configuration, Article Permission, Category Permission all works ... but on Module permissions nothing saved
strange ..

**Comment by Fedik** [comment]
ah I think the Asset Tree in Module permissions was broken by previous test.
I have tested again on clear "test database" ... all fine. :smiley: 
Sorry for disturb!

**Comment by roland-d** [comment]
@Fedik, perfect :+1:

**Pull request merged**
