### PR TITLE
[3.x][com_contact] fix category filter results

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #28927 .

### Summary of Changes
revisited the query 

### Testing Instructions
see  #28927

### Actual result BEFORE applying this Pull Request
results are incorrect cause no items are listed

### Expected result AFTER applying this Pull Request
results are correct  items are listed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on dc40d8989322ea9460b29512fa5b4cd1e5207202<br /><br />Joomla! 3.10.0-alpha2-dev Development [ Amani ] 23-July-2020 22:40 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30413">issues.joomla.org/tracker/joomla-cms/30413</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on dc40d8989322ea9460b29512fa5b4cd1e5207202<br /><br />Tested successfully in 3.10 alpha2-dev of 25 August.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30413">issues.joomla.org/tracker/joomla-cms/30413</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30413">issues.joomla.org/tracker/joomla-cms/30413</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks!

**Pull request merged**
