### PR TITLE
[4.0] Add class in fieldset in com_joomlaupdate

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue # .

### Summary of Changes
Add class `options-form`

I have just added class but I think it's weird to have `No updates available` in `legend`

### Testing Instructions
`Dashboard` > `System` > `Update` > `Joomla`

### Actual result BEFORE applying this Pull Request
joomlaupdates_before

### Expected result AFTER applying this Pull Request
joomlaupdates_after

### Documentation Changes Required
None

Code Review

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on d191f0b851761a66c1124ba83e5e2fb143374312<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33441">issues.joomla.org/tracker/joomla-cms/33441</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d191f0b851761a66c1124ba83e5e2fb143374312<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33441">issues.joomla.org/tracker/joomla-cms/33441</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33441">issues.joomla.org/tracker/joomla-cms/33441</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR.

**Comment by richard67** [comment]
Restarted drone. All fine now.

**Comment by Quy** [comment]
Thanks

**Pull request merged**
