### PR TITLE
[5.0] Activate compat plugin for new installations

### PR DESCRIPTION
**Pull request by HLeithner**
We activate the b/c plugin for new installations for a better experience. At a later time we might deactivate the plugin for new installations, or add a post installation message to notify user about it.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Updating a j4 site to j5 rightfully has the plugin enabled but I personally see enabling this on new installations as a step backwards. I also understand the counter arguments but, I can’t endorse them.

my 2c

**Comment by HLeithner** [comment]
We had a discussion about the point in time when and if we activate it, on the end we should look at our users and reputation. Which means we better don't produce 500 errors on extension installation which can't be solved by a "normal" enduser.

**Comment by HLeithner** [comment]
Also the discussion is to disable (for new installations) in a later version for introduce more stuff into this plugin and activate it again in minor versions.

**Comment by HLeithner** [comment]
btw. that was the last pr for now. I now prepare the RC

**Pull request merged**
