### PR TITLE
[5.2] use _JEXEC for restricted access

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

replace check of constant from `JPATH_BASE` to `_JEXEC` for restricted access
like other files eg.
https://github.com/joomla/joomla-cms/blob/f2b11456988ca5a6f53a08fa791ab6d38df0e588/installation/src/Form/Rule/PrefixRule.php#L14-L16

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

`JPATH_BASE` is used for check of restricted access

### Expected result AFTER applying this Pull Request

`JPATH_BASE` is **not** used for check of restricted access

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b8a737bdc8ac72f5c5b2245cf52bf040f969b825<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44193">issues.joomla.org/tracker/joomla-cms/44193</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b8a737bdc8ac72f5c5b2245cf52bf040f969b825<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44193">issues.joomla.org/tracker/joomla-cms/44193</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44193">issues.joomla.org/tracker/joomla-cms/44193</a>.</sub>

**Comment by heelc29** [comment]
Rebased to 5.2-dev

**Comment by pe7er** [comment]
Thanks @heelc29 !

**Pull request merged**
