### PR TITLE
4.0 dev - Update en-GB.com_templates.ini - line 43

### PR DESCRIPTION
**Pull request by Scrabble96**
The existing instructions are for Joomla 3x

Pull Request for Issue joomla#23423.

**Summary of Changes**

Changed middle of line 
Extensions-> Manage-> Manage-> Select template
to
System-> Manage-> Extensions-> Select template

**Testing Instructions**

Try to delete a default template style

**Expected result**

Error message with correct instructions

**Actual result**

Error message with incorrect instructions

**Documentation Changes Required**

As shown.

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on da8d7fe4c1e62a9ec2888fde2770515210710e68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23523">issues.joomla.org/tracker/joomla-cms/23523</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da8d7fe4c1e62a9ec2888fde2770515210710e68<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23523">issues.joomla.org/tracker/joomla-cms/23523</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23523">issues.joomla.org/tracker/joomla-cms/23523</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 RIPS Please

**Comment by zero-24** [comment]
Drone is happy now cc @wilsonge

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
