### PR TITLE
[4.0] Frontend: Fix List Contacts Category List Limit

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/30813#issuecomment-702040393

### Summary of Changes
The existing code prevents modifying the list limit as it is forced or by the Global Contacts List Layout Options, or the `List Contacts in a Category` menu item params.

This normalizes the use of list limit, as done for other lists displaying in frontend, by deleting both fields and modifying the model code. Default is set to 20.

### Testing Instructions
Create some contacts in a category.
Create a `List Contacts in a Category` menu item.
Display the menu item in frontend.

Try to modify the list limit
Patch and test again.

### Actual result BEFORE applying this Pull Request
limitbox_contacts-list-before

### Expected result AFTER applying this Pull Request

limitbox_contacts-list-after

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5d621960322baa8988ac3eb26b348a4c23a4c8cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30904">issues.joomla.org/tracker/joomla-cms/30904</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5d621960322baa8988ac3eb26b348a4c23a4c8cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30904">issues.joomla.org/tracker/joomla-cms/30904</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30904">issues.joomla.org/tracker/joomla-cms/30904</a>.</sub>

**Comment by HLeithner** [comment]
Sorry why should we hard code the default to 20? and what's the problem with our configuration option? don*t we use the same functionality in com_content?

**Comment by brianteeman** [comment]
It is not hard coded to 20. It uses the list_limit defined in global configuration. But as also shown below I dont get the same layout - and shouldnt the button be called search not filter?

image

image

**Comment by HLeithner** [comment]
I only looked at the code 

```php
-			$limit = $app->getUserStateFromRequest('global.list.limit', 'limit', $app->get('list_limit'), 'uint');
+			$limit = $app->input->get('limit', $app->get('list_limit', 20), 'uint');
```

and getuserstatefromrequest should do the same as input->get but also set the user preference in the session.

Edit: I miss read this as remove of the default, but it removes the com_contact .xml options if i'm not wrong?

**Comment by infograf768** [comment]
> don*t we use the same functionality in com_content?

Nope. We do not have a `articles__num` as Options in the xmls for articles `List Layouts`

The contact specific field option in the xmls (`contacts_display_num`) are unecessary as it is only used to force a specific limit which is ALWAYS set, which created the original issue

before the patch we had in Contacts CategoryModel:

```
		$numberOfContactsToDisplay = $mergedParams->get('contacts_display_num');

		if ($format === 'feed')
		{
			$limit = $app->get('feed_limit');
		}
		elseif (isset($numberOfContactsToDisplay))
		{
			$limit = $numberOfContactsToDisplay; // As this is always set, it forces that limit...
		}
		else
		{
			$limit = $app->getUserStateFromRequest('global.list.limit', 'limit', $app->get('list_limit'), 'uint');
		}
```
`20` is indeed basically a default.
Same code is used for frontend Articles Model concerning the category list. 
https://github.com/joomla/joomla-cms/blob/06fe4d226bf0d70f2ddf7cd5a213704089349a7b/components/com_content/src/Model/ArticlesModel.php#L94-L95

> and shouldnt the button be called search not filter?

That's what it is called for articles list.
https://github.com/joomla/joomla-cms/blob/06fe4d226bf0d70f2ddf7cd5a213704089349a7b/components/com_content/tmpl/category/default_articles.php#L103
`COM_CONTENT_FORM_FILTER_SUBMIT="Filter"`
I have not changed this. Just mimicked it for contacts by using a Global string `JGLOBAL_FILTER_BUTTON`. It can be modified globally for all similar lists in frontend by using `JSEARCH_FILTER_SUBMIT` if desired.
I remind you that you tested that PR OK and the layout does not change with this patch. It should be tested with a 4.0-dev test site where **npm ci** has been run.
https://github.com/joomla/joomla-cms/pull/30813#issuecomment-702022472

Folks, I basically have done all these contacts related frontend list refactoring PRs based on what we already have for articles.
For example, there is a debate here about the use of a fieldset or not.
https://github.com/joomla/joomla-cms/pull/30868
Taking out the fieldset element would also change the display, pushing the list limit to the right for the contacts lists. Articles may need more refactoring.

**Comment by infograf768** [comment]
As requested modified to use back `getUserStateFromRequest`
No change in behavior.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on daf7d61cd6a10ee7908dce178f27b84b5f9119b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30904">issues.joomla.org/tracker/joomla-cms/30904</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on daf7d61cd6a10ee7908dce178f27b84b5f9119b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30904">issues.joomla.org/tracker/joomla-cms/30904</a>.</sub>

**Comment by infograf768** [comment]
@HLeithner 
Good to go.

**Comment by AndySDH** [comment]
> Nope. We do not have a articles__num as Options in the xmls for articles List Layouts

@infograf768 Yes we do, actually:

What is this, then?

image

There's also the same setting for other stuff like Tags List as well.

Yet, Contact Category is left stranded of its own setting and has to fall back to the Global List value.

Why did you straight up remove the functionality made  by @vaibhavsTekdi  at #23710, instead of fixing the issue of the limit being always set?

Articles Category View has this option and the issue is not present there. So surely this could have been solved another way instead of removing the option altogether.

**Pull request merged**
