### PR TITLE
[4.0] Fix com_joomlaupdate js error

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #34510.

### Summary of Changes
This PR fixes few js error for com_joomlaupdate. See https://github.com/joomla/joomla-cms/issues/34510 for more details. It also fixes an error in the console when the page is loaded (You need to install a third party extension like JCE to see this error - or code review)

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/34510 to understand the issue
2. Download update package for this PR, go to System -> Update -> Joomla to install the update package for this PR (or apply patch, and run npm command, sorry I don't remember the command to run)
3. Check and confirm the issue is gone.

### CODE REVIEW

**Comment by richard67** [comment]
@joomdonation It fixes the error in my issue, but regarding the console error there is still `Uncaught TypeError: document.getElementById(...) is null` here: https://github.com/joomla/joomla-cms/pull/34516/files#diff-550b2e9757e1fef80e3714191e4f70f3dd9bd7441ff3e7679698de031551e346R420

**Comment by joomdonation** [comment]
@richard67 I don't see the issue myself for some reasons. Maybe it's because I have some third party extension installed (JCE, and my own extensions). But I saw that error before and the modification in that line of code fixes that. The # character is needed for old code (jQuery) but not needed on document.getElementById

**Comment by richard67** [comment]
> @richard67 I don't see the issue myself for some reasons. Maybe it's because I have some third party extension installed (JCE, and my own extensions). But I saw that error before and the modification in that line of code fixes that. The # character is needed for old code (jQuery) but not needed on document.getElementById

@joomdonation No need to explain me the "#" change, I understand that already.

**Comment by joomdonation** [comment]
> No need to explain me the "#" change, I understand that already.

Sorry, I just tried to explain the reason for the change on that line of code.

**Comment by richard67** [comment]
@joomdonation Yes but unfortunately it still doesn't work. Seems there is something more wrong with that element id.

**Comment by richard67** [comment]
I can't see any html element having an id "plg_226", which is the one for which the document.getElementById call fails. 226 is the id of the JCE extension in my installation.

**Comment by joomdonation** [comment]
Somehow, it relates to logic of com_joomlaupdate which I don't understand yet. The element is only available if the layout administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_update.php is loaded , but in this case, it is not loaded for some reasons (maybe it is because no update found for that extension, will need to look more at com_joomlaupdate to understand)

**Comment by richard67** [comment]
@joomdonation One solution could be that you revert that one change which is not related to the issue and which does not work for me, so the other change can be tested before RC 2 is made tonight, and for the remaining js error make a new issue.

**Comment by joomdonation** [comment]
@richard67 OK. We will handle that change on a separate PR.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8f8f971dc6941d772d56d5c57c32ec6f819cc738<br /><br />Fixes #34510 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34516">issues.joomla.org/tracker/joomla-cms/34516</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
