### PR TITLE
Repairing some inconsistency

### PR DESCRIPTION
**Pull request by yild**
Simple change in language file, string corrected to match other search descriptions.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cc6e335f31eee72e19721eda7f0dccdb7f217a20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10935">issues.joomla.org/joomla-cms/10935</a>.</sub>

**Comment by brianteeman** [comment]
Simple fix. Direct to rtc in review. Can be merged in 3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10935">issues.joomla.org/joomla-cms/10935</a>.</sub>

**Comment by infograf768** [comment]
we are at RC stage (Today I think).
Please change Milestone to 3.6.1

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on cc6e335f31eee72e19721eda7f0dccdb7f217a20<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10935">issues.joomla.org/joomla-cms/10935</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on cc6e335f31eee72e19721eda7f0dccdb7f217a20<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10935">issues.joomla.org/joomla-cms/10935</a>.</sub>

**Pull request merged**
