### PR TITLE
[4.0] Mobile Database fix

### PR DESCRIPTION
**Pull request by brianteeman**
The columns being displayed at mobile resolutions were wrong.

Location and Type are not essential so have been removed from mobile view
Problems is essential and has been added to mobile view

### Before
image

### After
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7fe2b9da93cf61fddf88e2c3f07e9c58127e60b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35731">issues.joomla.org/tracker/joomla-cms/35731</a>.</sub>

**Comment by alikon** [comment]
Do this fix #35631  ?

**Comment by brianteeman** [comment]
it might do - but the pr was intended to resolve the bigger issue of the wrong column being displayed

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7fe2b9da93cf61fddf88e2c3f07e9c58127e60b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35731">issues.joomla.org/tracker/joomla-cms/35731</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35731">issues.joomla.org/tracker/joomla-cms/35731</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
