### PR TITLE
[Isis] Chzn 'trashed' color

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #14855 .

### Summary of Changes
Sets trashed state of chosen dropdown to red.

### Testing Instructions
Apply patch and navigate to article edit.

### Before Patch
chzn-trashed1

### Actual result
chzn-trashed2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1baad3290b3b41db10df34426b183e4b37b1b8b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14856">issues.joomla.org/tracker/joomla-cms/14856</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1baad3290b3b41db10df34426b183e4b37b1b8b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14856">issues.joomla.org/tracker/joomla-cms/14856</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14856">issues.joomla.org/tracker/joomla-cms/14856</a>.</sub>

**Pull request merged**
