### PR TITLE
Improve showon behaviours on Global configuration

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR add more showon behaviours to com_config.

Also in this PR is a small change in the order of the mail SMTP fields.

Previous order:
- SMTP Authentication
- SMTP Security
- SMTP Port
- SMTP Username
- SMTP Password
- SMTP Host

Order after PR:
- SMTP Host
- SMTP Port
- SMTP Security
- SMTP Authentication
- SMTP Username (only visible if SMTP Authentication Set to Yes)
- SMTP Password (only visible if SMTP Authentication Set to Yes)
#### How to test
1. Fresh Joomla install
2. Install patch
3. Test if fields showon behaviours (Site Offline, Cache, FTP, Proxy, Mail online, Mail/Sendmail, Mail/SMTP, etc) are working ok

### CODE REVIEW

**Comment by brianteeman** [comment]
Testers - #8524 has already been merged so you dont need to install that patch to test this one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8555">issues.joomla.org/joomla-cms/8555</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 09d0af4dd1a0e4ef6e18f2e1a8ef94be6cc5191e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8555">issues.joomla.org/joomla-cms/8555</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 can you test this one?

Is a simple test

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 09d0af4dd1a0e4ef6e18f2e1a8ef94be6cc5191e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8555">issues.joomla.org/joomla-cms/8555</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8555">issues.joomla.org/joomla-cms/8555</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for the tests @brianteeman @richard67

**Comment by andrepereiradasilva** [comment]
ignore again the unit tests label, somehow my git changed the filename of the xcache unit test, i reverted.

Conflicts fixed.

@brianteeman please remove again the label sorry. i have no other way of do this.

**Comment by andrepereiradasilva** [comment]
i don't quite understand why this is for 3.6.0 since is not a new feature, but ok.

**Pull request merged**
