### PR TITLE
Fix container menu item description

### PR DESCRIPTION
**Pull request by izharaazmi**
### Summary of Changes
At the time of the PR it was implemented as in current description but it has changed in a later PR. So updated the text to match current workflow. 

### Testing Instructions
No code changes, review should be enough imo.

### CODE REVIEW

**Comment by ghost** [comment]
@brianteeman can you please have a Look at Description?

**Comment by brianteeman** [comment]
It's fine

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4dcfb28b2fff0a3ff3edd3645507ddbd0503fcf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18307">issues.joomla.org/tracker/joomla-cms/18307</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig Brian is fine with this so RTC?

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
