### PR TITLE
[3.x] Register to read more

### PR DESCRIPTION
**Pull request by brianteeman**
## The issue
Create an raticle with a readmore and set to registered
Create a menu item for that article set to public AND with the menu option Show Unauthorised Links set to yes

## Expected result
The intro text will be displayed followed by a Register to read more link that is styled consistently with all other similar readmore links

## Actual result
Completely different markup because it is not using the joomla.content.readmore layout

## note
I dont see any reason why the layout is not being used here

## summary
After applying the pr the link will be styled the same etc

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 68551daf52cc7c53f0d6b71ab288c74dda2c2e3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30597">issues.joomla.org/tracker/joomla-cms/30597</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 68551daf52cc7c53f0d6b71ab288c74dda2c2e3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30597">issues.joomla.org/tracker/joomla-cms/30597</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30597">issues.joomla.org/tracker/joomla-cms/30597</a>.</sub>

**Comment by HLeithner** [comment]
there is a markup change between default.php and readmore.php layout, I would prefer todo this in 3.10.

For the issue it self you are right there is no reason to no use the layout.

I change the target branch to 3.10-dev

**Comment by zero-24** [comment]
Merging now thanks @brianteeman

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
