### PR TITLE
Use Symfony 4 components in 4.x, dump the PHP 7.1 polyfill

### PR DESCRIPTION
**Pull request by mbabker**
[Symfony 3.4](https://symfony.com/roadmap/3.4) goes into security only support in November 2020 and EOLs in November 2021.  The next LTS is [Symfony 4.4](https://symfony.com/roadmap/4.4) which will EOL in November 2023.  Given Joomla does not have "quick" release cycles for major versions, it is better that Joomla depends on libraries that will be supported for the longest time practical, therefore this PR bumps all Symfony components to the 4.3 versions to ensure everything can be updated to 4.4 when the time comes and not tie Joomla's hands with depending on "dead" code for too long.

Also, the PHP 7.1 polyfill is not necessary if PHP 7.2 is the minimum requirement, so it is removed.

### CODE REVIEW

**Comment by HLeithner** [comment]
Shouldn't we remove "paragonie/sodium_compat": "~1.6", too? It's also a poly fill for PHP < 7.2.

if we use the namespaced syntax we should rewrite our code to use the native functions.

**Comment by mbabker** [comment]
> Shouldn't we remove "paragonie/sodium_compat": "~1.6", too? It's also a poly fill for PHP < 7.2.

No.  It polyfills if `ext/sodium` or `ext/libsodium` are not installed, it's not a pure PHP 7.1 and earlier only package in the same way that `paragonie/random_compat`, `ircmaxell/password_compat`, or the `symfony/polyfill-php*` packages are.

> if we use the namespaced syntax we should rewrite our code to use the native functions.

https://github.com/joomla-framework/crypt/commit/0c0473e9078277bedae395f93bb80fca2b32d03c should be applied to `Joomla\CMS\Crypt\Cipher\SodiumCipher`, IMO only for 4.0.  The polyfill package exposes the PHP extension APIs so there isn't a need to call the functions/methods of the polyfill package if the extensions aren't installed.

**Comment by HLeithner** [comment]
ok, thx

**Comment by wilsonge** [comment]
Sorry just bumped the session package before i saw this. can you fix the conflicts and let's get this in

**Comment by mbabker** [comment]
Rebased

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
