### PR TITLE
[4.0] Fix searchtools error checkActiveStatus

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Look like `[].slice.call` does not accept `undefined` as a valid argument, so when there no filter container defined in search tool, this line of code https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/searchtools.es6.js#L289 throws some error in console.

```
Uncaught TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at Searchtools.checkActiveStatus (searchtools.js?c804da20519ee3655f5ac687001b9f31321af327:262)
    at new Searchtools (searchtools.js?c804da20519ee3655f5ac687001b9f31321af327:194)
    at HTMLDocument.onBoot (searchtools.js?c804da20519ee3655f5ac687001b9f31321af327:504)
```

This PR prevents that error by adding a if check, similar with what we do in other places in that script, for example https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/searchtools.es6.js#L177

### Testing Instructions
As this only happens on third party extensions (found this while testing my extensions), it's hard to call for end-users test. Hopefully code review would be enough. @dgrammatiko @Fedik Could you help?

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Probably just change the `getFilterFields `?

```js
    getFilterFields() {
      if (this.filterContainer) {
        return [].slice.call(this.filterContainer.querySelectorAll('select,input'));
      }
      return [];
    }
```

and also `const els = [].slice.call(this.getFilterFields());` to `const els = this.getFilterFields();`

**Comment by joomdonation** [comment]
@dgrammatiko Yeah, better. And with that change, we can remove the if check before calling forEach in other places, thus optimize the process a bit :). Could you please check it again?

**Comment by dgrammatiko** [comment]
Approved

**Comment by richard67** [comment]
@dgrammatiko If you mark your test result in the issue tracker (with a comment "Code review" or so maybe), then it will count 😜

**Comment by joomdonation** [comment]
Help, please :). Otherwise I will ping you every time I hear from anyone reporting this bug with my extensions :D (joke).

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on bba304b2e3ef3a1393067b63e19ae89432abb632<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34986">issues.joomla.org/tracker/joomla-cms/34986</a>.</sub>

**Comment by dgrammatiko** [comment]
> Otherwise I will ping you every time I hear from anyone reporting this bug with my extensions

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on bba304b2e3ef3a1393067b63e19ae89432abb632<br /><br />Real test with one of @joomdonation 's extensions:
- Issue reproduced.
- Verified that PR fixes it.
- Verified that search tools elsewhere still work as before.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34986">issues.joomla.org/tracker/joomla-cms/34986</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34986">issues.joomla.org/tracker/joomla-cms/34986</a>.</sub>

**Comment by richard67** [comment]
@wilsonge As it's a bug fix I've set the 4.0 milestone. I hope this is ok.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
