### PR TITLE
Snyc install sql for the Backend menus [#__menu]

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue raised by @rdeutz 

### Summary of Changes

This syncs the backend main menu's over the testing data

### Testing Instructions

- Install all testing data via this package https://github.com/zero-24/joomla-cms/archive/fix_install_sql.zip
- make sure the backend menu's is complete 

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Double Entry of "Multilingual Associations", but had core components before install of this package.

**Comment by zero-24** [comment]
Which sql did you use?

**Comment by franz-wohlkoenig** [comment]
https://github.com/zero-24/joomla-cms/archive/fix_install_sql.zip

**Comment by zero-24** [comment]
Which SQL file / testing data did you try to install.

**Comment by franz-wohlkoenig** [comment]
i installed the fix_install_sql.zip – your Question show i shouldn't.

**Comment by zero-24** [comment]
In the installation prozess you choose a sample data set learning, blog, testing etc. Which did you choose?

**Comment by franz-wohlkoenig** [comment]
i installed it in Joomla3.7-beta1 > Joomla Update. In the Meantime i installed a clean beta1.

**Comment by zero-24** [comment]
I mean this options described here: https://www.ostraining.com/blog/joomla/joomla-3-sample-data/

**Comment by franz-wohlkoenig** [comment]
I had a 3.7beta1 (multilingual, no sample data) and installed fix_install_sql.zip  on top.

**Comment by zero-24** [comment]
Yes and this does not fix everything ;) we need a clean install using my package testing all options maybe also multilingual and confirm the backend menu contains all menu entrys.

**Comment by franz-wohlkoenig** [comment]
now i understand …

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 578dac4c389338e8bfc2d64cf389f65fb5556429<br /><br />I do test as:
git pull upstream staging
curl https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/13894.diff | git apply
# install each sample data, login as admin and I checked menus on backend, (on frontend I checked only on one sample data)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13894">issues.joomla.org/tracker/joomla-cms/13894</a>.</sub>

**Comment by zero-24** [comment]
This patch got tested by @obuisard here: https://github.com/joomla/joomla-cms/issues/13905#issuecomment-277479673<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13894">issues.joomla.org/tracker/joomla-cms/13894</a>.</sub>

**Pull request merged**
