### PR TITLE
Radiobutton layout was messed up somehow.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Fix for #7999 

---
#### Steps to reproduce the issue

install joomla from the current Staging in Github

Go to the first installation screen: Main Configuration

You will notice that the  Site Offline button has a new look that is not right:

screen shot 2015-10-02 at 02 44 55

Before it was like:

screen shot 2015-10-02 at 02 45 59

This change happened in the last 24hours, I noticed because is breaking the automated tests (https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L152)
#### Expected result

we would need this button to have back the default value as "no", and being able to change the values
#### Actual result

"Site Offline" do not work. If you click you can't change the value anymore, is broken:

screen shot 2015-10-02 at 02 51 06
#### System information (as much as possible)

This happens in Firefox, Chrome, Safari and Opera in Mac and Ubuntu

### CODE REVIEW

**Comment by javigomez** [comment]
I have tested this item :white_check_mark: successfully on efdeb8e7576420312b2383c49f9fbadf44af1ef1<br />I can confirm that the patch fixes the issue, now the radio buttons in /installation/ are back to normal:

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by javigomez** [comment]
the buttons after the patch:

screen shot 2015-10-02 at 04 48 18
screen shot 2015-10-02 at 04 48 18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by javigomez** [comment]
Please also update the old copyrights: https://github.com/joomla/joomla-cms/pull/4022/files#diff-1a484eca2b31420444083dbca7198a81R6

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on efdeb8e7576420312b2383c49f9fbadf44af1ef1<br />Works good here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by Harmageddon** [comment]
I have tested this item :red_circle: unsuccessfully on efdeb8e7576420312b2383c49f9fbadf44af1ef1<br />This seems to fix the radio buttons for installation. However, #4022 has broken *all* radio buttons in backend. These buttons are not fixed for me with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by zero-24** [comment]
RTC.

Lets do the codestyle and copyright updates do in a different PR there are more changes we need to do ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by Harmageddon** [comment]
screen shot 2015-10-02 at 05 00 00

The buttons are not selected with a default value. Additionally, when selecting a button, it is marked blue (primary) instead of green or red. And it is not possible to select the opposite value once you have selected a radio button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by zero-24** [comment]
back to pending. maybe because of the layout overrides for isis and protostar @okonomiyaki3000 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by zero-24** [comment]
@Harmageddon can you try it with renamed folder `administrator/templates/isis/html/layouts/joomla/fields` works for me for the backend (with this patch applyed as well)

**Comment by zero-24** [comment]
same for frontend. `/templates/protostar/html/layouts/joomla/fields` @okonomiyaki3000 do you know why you add thes overrides there?

**Comment by Harmageddon** [comment]
That's right, @zero-24. Without the overrides, it works.

**Comment by zero-24** [comment]
@okonomiyaki3000 here is a PR ( https://github.com/okonomiyaki3000/joomla-cms/pull/5) that fix all issues.

#### How to test (if my PR is merged into this)

- install staging from this PR: https://github.com/okonomiyaki3000/joomla-cms/archive/fix-radiobuttons.zip (we need to wait for the merge of my pr above) 
- see the installation work (radio buttons)
- go to the backend e.g. the global config see the radio buttons works as bevor
- go to frontend (e.g. site-settings) and see the radio also works there.
- apply the following code to ( plugins/user/profile/profiles/profile.xml)
```
<field type="checkboxes" name="somefield" label="Select Some Stuff">
   <option value="a" checked="true">A</option>
   <option value="b">B</option>
   <option value="c">C</option>
</field>
```
- enable profiel plugin
- see the profile in backend --> works
- see the profile in frontend  --> works

Thanks :smile:

**Comment by okonomiyaki3000** [comment]
@zero-24 This override template wraps the input tag inside of the label tag because that's the Bootstrap way. Of course, that applies to radio buttons that are meant to be rendered as radio buttons. To achieve the toggled button effect, Bootstrap provides a different solution using the `button` tag. I suppose this override should be removed because the built-in Joomla templates are not really using Bootstrap in the standard way. That's unfortunate because it means there's not really an option of using normal radio buttons.

**Comment by zero-24** [comment]
See https://github.com/okonomiyaki3000/joomla-cms/pull/5 that removes the overrides 😉

**Comment by okonomiyaki3000** [comment]
Alright, let's do that then. I hope future templates using Bootstrap 3 (or 4?) will work in a more standard way though.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on cbb29cc6141c0da7cc7fbb9a0b39a138f5cfe343<br />Thanks for the PR! Applied the patch and the buttons are back again! Also tested the installation an this patch works.
Hopefully this PS will be added soon!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by YouriiM26** [comment]
I have tested this item :white_check_mark: successfully on cbb29cc6141c0da7cc7fbb9a0b39a138f5cfe343<br />Patch works! Thank for the pr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by zero-24** [comment]
Thanks to the testers and @okonomiyaki3000 :smile: -> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8000">issues.joomla.org/joomla-cms/8000</a>.</sub>

**Comment by zero-24** [comment]
@RickR2H 

>Hopefully this PS will be added soon!

Nothing is / was broken in any stable release. Just the `staging` branch had this problem ;)

**Comment by RickR2H** [comment]
@zero-24 Glad to hear that ;)

**Pull request merged**
