### PR TITLE
[4.1] c/ot/to

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c418bfc2f1273935238ffeb09e3bfb2fe8f62a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36816">issues.joomla.org/tracker/joomla-cms/36816</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c418bfc2f1273935238ffeb09e3bfb2fe8f62a8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36816">issues.joomla.org/tracker/joomla-cms/36816</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36816">issues.joomla.org/tracker/joomla-cms/36816</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
