### PR TITLE
[postgres] - fix quote escape in sample_testing

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for partial Issue #17864 .

### Summary of Changes
fix quote escape in sample_testing

### Testing Instructions
install with sample_testing.sql

### Expected result
no sql errors

### Actual result
sql errors

### CODE REVIEW

**Comment by wilsonge** [comment]
OK I don't get this one. Why is this suddenly changed from 3.x?

**Comment by alikon** [comment]
Looking at history of this file i've your same question

**Comment by csthomas** [comment]
My fault from #14223 
`installation/sql/postgresql/sample_data.sql` also requires a fix.

**Comment by csthomas** [comment]
Sample blog too, lines 86 and ~~88~~

**Comment by alikon** [comment]
i suspect didn't came out from #14223 https://github.com/csthomas/joomla-cms/blob/f8e8ee9528221856e1ba44795149e9311c06552f/installation/sql/mysql/sample_testing.sql#L360

`'What''s New in 1.5?'` seems correctly escaped  at that time, still don't understand...

**Comment by csthomas** [comment]
What about `you''''ll notice` in the same line?

**Comment by alikon** [comment]
maybe a github "unicorn"  :smile:

**Comment by csthomas** [comment]
I have tested installation with sample_testing.sql before your patch with success. No errors.
PostgreSQL 9.5.8.

[UPDATED]
I did not understand this problem.

Now I test with psql to load sql files.

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 4d22fdcb76de231065ebb1a641699688827602be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17891">issues.joomla.org/tracker/joomla-cms/17891</a>.</sub>

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17891">issues.joomla.org/tracker/joomla-cms/17891</a>.</sub>

**Pull request merged**
