### PR TITLE
Hyperlinked "Redirect Plugin is disabled"

### PR DESCRIPTION
**Pull request by pe7er**
This PR changes the language file for the **Redirect Manager** so that the "The Redirect Plugin is disabled. Enable it in the Plugin Manager." contains an hyperlink to the Plugin Manager.
## Test instructions

In back-end > Components > **Redirect**
If the Redirect System Plugin is not enabled, it will display a message "The Redirect Plugin is disabled. Enable it in the Plugin Manager."

screen shot 2015-05-14 at 09 57 42
### This PR changes the language string

so that the warning message has a hyperlink to the Plugin Manager,
including a filter option for the name "System - Redirect".

screen shot 2015-05-14 at 09 57 42
### Result of that hyperlink

If you click on the hyperlink you will be redirected to the Plugin Manager,
which filters the "System - Redirect" so you can easily enable it.

screen shot 2015-05-14 at 09 57 42

### CODE REVIEW

**Comment by hans2103** [comment]
@test succes

even tiny steps like these will increase usability

**Comment by zero-24** [comment]
@pe7er i think it would be easier to use: `id:427`

As the ID will work every time on every language (as it is on all installs the same) or do we have reasons to not use the id?

**Comment by mbabker** [comment]
Even if the install schema sets IDs a certain way, never assume any item IDs will always be known values.  That has actually kicked us in the rear in the past (I think in our update SQL files when we had hardcoded menu item IDs).

**Comment by zero-24** [comment]
ok. than the name is as a translatable string as proposed ok for me.

**Comment by infograf768** [comment]
Please add before the string:
`; Change 'System%20-%20Redirect' to the value in plg_system_redirect.sys.ini for your language`

**Comment by pe7er** [comment]
Thanks @infograf768 ! 
I've added a similar comment in a similar PR: #6948

**Comment by zero-24** [comment]
@pe7er @test works here. Thanks :smile: RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6947">issues.joomla.org/joomla-cms/6947</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request merged**
