### PR TITLE
[4.0] margin-bottom input groups

### PR DESCRIPTION
**Pull request by brianteeman**
A previous pr of mine #33899 was too aggressive. This resolves that. See #34106 for test instructions

Dont forget this is a css change so npm run build:css

Pull Request for Issue #34106

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Drone is moaning

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 36617bb55cc3e1e8df4c006ae90a809ac1d15839<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34112">issues.joomla.org/tracker/joomla-cms/34112</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 36617bb55cc3e1e8df4c006ae90a809ac1d15839<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34112">issues.joomla.org/tracker/joomla-cms/34112</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 36617bb55cc3e1e8df4c006ae90a809ac1d15839<br /><br />This took quite a bit of time to test as I could not cache bust on mobile - turning on debug mode though seems to work fine, but without debug mode on Im assuming Im still seeing the old cached css. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34112">issues.joomla.org/tracker/joomla-cms/34112</a>.</sub>

**Comment by brianteeman** [comment]
mobile cache is a nightmare

**Comment by richard67** [comment]
Is the mobile cache at least cleared if you reset to factory settings?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34112">issues.joomla.org/tracker/joomla-cms/34112</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
