### PR TITLE
[4.0] Shorter pinned description

### PR DESCRIPTION
**Pull request by Quy**
Redo #21879

### Testing Instructions
Code review.
or
Edit a banner.
See shorter description under `Pinned` switcher.

### CODE REVIEW

**Comment by brianteeman** [comment]
All description have not been blindly removed. Only the meaningless and/or useless have been removed

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on d5b0b95ced6df3a085c98f23b2ecd3410154ece3<br /><br />Tested in the Nightly build of 15 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27508">issues.joomla.org/tracker/joomla-cms/27508</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on d5b0b95ced6df3a085c98f23b2ecd3410154ece3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27508">issues.joomla.org/tracker/joomla-cms/27508</a>.</sub>

**Comment by wilsonge** [comment]
Agree with @brianteeman. The first part of the description `Whether or not the Banner is 'pinned'` can be removed - but the rest is actually useful information we shouldn't be removing

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
