### PR TITLE
[4.0] logo path not polyline

### PR DESCRIPTION
**Pull request by brianteeman**
The svg logo contained a mix of path and polyline. this PR changes it so that they are all paths

### after
image

For reference the command to convert the polylines was

`svgo --pretty  --config='{"full":true}' --enable=convertShapeToPath filename.svg`

### CODE REVIEW

**Comment by angieradtke** [comment]
now the file-name is misleading

**Comment by brianteeman** [comment]
How is it misleading to have a file called logo blue where the only color is blue

**Comment by angieradtke** [comment]
the background  should not be blue. Test  what happens if you change the hue of the template in the template-parameter. I thought we can make the color of svg   path and polyline configurable using the template vars

**Comment by brianteeman** [comment]
1. the logo should not have had a mix of path and polyline - that was a mistake - i fixed it which is all this PR does
2. the logo is a single colour - it doesnt matter what colour it is
3. there is no background

**Comment by angieradtke** [comment]
ah cool brian , sorry I missunderstood

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 223b8495b28c5a5e5c56338b08bf3b5cd8c8e7cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28038">issues.joomla.org/tracker/joomla-cms/28038</a>.</sub>

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 223b8495b28c5a5e5c56338b08bf3b5cd8c8e7cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28038">issues.joomla.org/tracker/joomla-cms/28038</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28038">issues.joomla.org/tracker/joomla-cms/28038</a>.</sub>

**Comment by astridx** [comment]
I have tested this Patch successful.

git fetch origin pull/28038/head:logo
git checkout logo
No new install or npm ci is needed.


I tested with the current ‎4.0.0-beta1-dev on Ubuntu with PHP 7.2 and MySQL 5.7.
Before:
Menus  Items  Main Menu    admin   Administration
After
Menus  Items  Main Menu    admin   Administration(1)

**Comment by brianteeman** [comment]
Thanks

**Comment by angieradtke** [comment]
thank you Robert

**Pull request merged**
