### PR TITLE
[5.1] Complete com_search deprecation #40727

### PR DESCRIPTION
**Pull request by brianteeman**
@hackware deprecated various search methods in `libraries/src/Language/Language.php` in #40727

This PR completes that PR by deprecating their use in the localise.php file

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
it's too late to deprecated anything in 4.4, that's only allowed in x.y.0 releases. In this case I would deprecate it with 5.1 and remove it with 7.0

**Comment by brianteeman** [comment]
its a bug that @hackwar forgot to deprecate it when he deprecated the code and now removes the actual code with #42892. If this can't be deprecated until 5.1 then the code itself will have to stay al;so until 7. Anything else makes no sense

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 51255d38bf4cdba9e161957b1b2b3bfcc27379c8<br /><br />I looked at the code and read the comments so it looks OK to me as a bug fix for a previous commit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42891">issues.joomla.org/tracker/joomla-cms/42891</a>.</sub>

**Comment by laoneo** [comment]
@brianteeman then we have to change these depreciations you are talking about to 7.0 as well. Better to follow our deprecation policy and postpone already added deprecations than vice versa.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on f7ac86b9bb0197147e838653f54f3c169dfbfbec<br /><br />Doc blocks are correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42891">issues.joomla.org/tracker/joomla-cms/42891</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42891">issues.joomla.org/tracker/joomla-cms/42891</a>.</sub>

**Comment by brianteeman** [comment]
@laoneo I did what you asked and rebased it. Any reason why it cant be merged now?

**Comment by laoneo** [comment]
This is up to @bembelimen or @LadySolveig as they are the RM.

**Comment by Hackwar** [comment]
This is now also to late for 5.1, so it would have to go into 5.2-dev

**Comment by brianteeman** [comment]
I am not remaking it. Someone else can fix your mistake. The pr was made and tested in good time.

**Comment by LadySolveig** [comment]
Thank you @brianteeman and for review @ceford and @laoneo

**Comment by brianteeman** [comment]
thanks - appreciate it

**Pull request merged**
