### PR TITLE
[4.0] Enable Bootstrap's rounded styling in Atum

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28042.

### Summary of Changes

Since Atum practically switched to rounded styling, we should use existing Bootstrap's styles instead of manually adding border radius everywhere.

### Testing Instructions

Inspect forms with button groups and input groups.

### Expected result

OK styling.

### Actual result

Border radius added where not needed:

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
is it expected that now none of the corners are rounded

image

**Comment by SharkyKZ** [comment]
For now yes. Last button should actually have border radius on the right. But `Create` button is not last, there are some hidden buttons which are displayed with JS.

**Comment by infograf768** [comment]
Any specific page we can check with before/after ?

**Comment by SharkyKZ** [comment]
Mostly pages containing forms.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on aa57712d554e9ed8795c57579077cbcdf3040ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28048">issues.joomla.org/tracker/joomla-cms/28048</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on aa57712d554e9ed8795c57579077cbcdf3040ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28048">issues.joomla.org/tracker/joomla-cms/28048</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28048">issues.joomla.org/tracker/joomla-cms/28048</a>.</sub>

**Comment by infograf768** [comment]
Found an issue in RTL for the search button
Screen Shot 2020-02-29 at 11 26 22

**Comment by infograf768** [comment]
@SharkyKZ 
Can you solve the rtl display?

**Comment by SharkyKZ** [comment]
Looking into it.

**Comment by infograf768** [comment]
@SharkyKZ 
I think I found the solution. I will have to create a specific rtl override in anew bootstrap file.
So don’t bother.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28161
(Was easier to add css overrides in rtl template rather than creating a new scss file)

**Pull request merged**
