### PR TITLE
[4.0] Fix banner module

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31623 .

### Summary of Changes
Fix bannerHelper for new media. 

credits @drmenzelit 

### Testing Instructions
see #31623

### Actual result BEFORE applying this Pull Request
Images don't pass the isImage check and no image appears.

### Expected result AFTER applying this Pull Request
Images are displayed

### Documentation Changes Required
no

### CODE REVIEW

**Comment by chmst** [comment]
This is no appropriate solution

**Comment by chmst** [comment]
Improved the check isImage by splitting the image url

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 00dbee65e6e23dc9f362a08e149e0bd20ffa1dde<br /><br />Tested successfully in Beta6-dev of 9 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31624">issues.joomla.org/tracker/joomla-cms/31624</a>.</sub>

**Comment by chmst** [comment]
Question: 
The Helper also  contains a method isFlash($url) - do we rneed this now in 2020?

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3ad4a69ff79d11a06d39536b6ffb0bf0fa17c66a<br /><br />and check of removed flashplayer<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31624">issues.joomla.org/tracker/joomla-cms/31624</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3ad4a69ff79d11a06d39536b6ffb0bf0fa17c66a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31624">issues.joomla.org/tracker/joomla-cms/31624</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31624">issues.joomla.org/tracker/joomla-cms/31624</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
