### PR TITLE
Set variable (type) in case of an empty request in json input object

### PR DESCRIPTION
**Pull request by matrikular**
### Summary of Changes
If you want to process raw post data send to an (open) API, you probably would use something similar to this.:
`$payload = $this->input->json->getArray();`

This is fine when (valid) data was send. In case of an empty request though, a null value is passed to `Input::getArrayRecursive()`, which results in the following warning:
> Warning: Invalid argument supplied for foreach() in [...]\libraries\src\Input\Input.php on line 165

### Testing Instructions
First, create a test controller "foobar" with the following content in e.g. `/components/com_users/controllers/foobar.php`
```
<?php

defined('_JEXEC') or die;

use Joomla\CMS\Factory;

JLoader::register('UsersController', JPATH_COMPONENT . '/controller.php');

class UsersControllerFoobar extends UsersController
{
	public function foobar()
	{
		$payload = $this->input->json->getArray();

		print_r($payload);

		Factory::getApplication()->close();
	}
}
```
Send a POST request, preferably with the content type "application/json" to that controller / method and leave out the payload / data. It shouldn't matter if you use curl, your browser console and / or an addons to do that.

### Expected result
The expected result would be an empty array.

### Actual result
The warning mentioned above appears.

### CODE REVIEW

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 4e98f6368f9224497f42e4c43a58f98c50c42d84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30095">issues.joomla.org/tracker/joomla-cms/30095</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 4e98f6368f9224497f42e4c43a58f98c50c42d84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30095">issues.joomla.org/tracker/joomla-cms/30095</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30095">issues.joomla.org/tracker/joomla-cms/30095</a>.</sub>

**Comment by HLeithner** [comment]
I would expect that this is a b/c break, because it could changes the behavior on broken json input. I would suggest to make this PR against the 2.0 version of the framework package. Oh I noticed that this is already done.

I'm closing, thanks for your contribution.

**Comment by SharkyKZ** [comment]
This should not have been closed. This fixes PHP notices in core library. The notice can be invoked by user input and can not be fixed by extension developers (except by silencing the error). Plus this has already been fixed in 1.x version of framework package (included in CMS).

**Comment by HLeithner** [comment]
Can the developer detect an broken json string if we use this? Shouldn't getArrayRecrusive check if it's an array before it run the foreach loop?

**Comment by SharkyKZ** [comment]
>Can the developer detect an broken json string if we use this?

Developer can use `getRaw()` method to get the JSON encoded string if needed.

>Shouldn't getArrayRecrusive check if it's an array before it run the foreach loop?

`Joomla\Input\Input::$data` should always be an array.

**Comment by HLeithner** [comment]
You are right `data` have to be an array. Thanks

**Pull request merged**
