### PR TITLE
Contacts - move Filters from left to [Search Tools]

### PR DESCRIPTION
**Pull request by pe7er**
[edit] I had a merge conflict and redid the changes in new PR.
Please test #7072 instead. Thanks!

This PR moves the 5 Filter options of the Contacts Manager to the [Search Tools] button.
**note**: The ordering dropdown in [Search Tools] **needs to be fixed** before merging.
(See Issue #6941 regarding the inconsistency with Filter options).
## Test instructions

In back-end > Components > Contacts
See the filters on the left

screen shot 2015-05-15 at 06 37 24

Compare with the filters in Category Manager for Contacts: 
In back-end > Components > Contacts > Categories

screen shot 2015-05-15 at 06 37 23
### This PR changes moves the Filters

from the left to the middle column and will be visible when you click on the [Search Tools] button.

screen shot 2015-05-15 at 06 37 23
### **Notes:**

I can use some help & suggestions regarding the following issues:
- The ordering dropdown in [Search Tools] is currently not working
- Code cleanup 1 - tmpl view ( /administrator/components/com_tags/views/tags/tmpl/default.php ) 
  contains "Joomla.orderTable = function()" that probably can be removed

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont see the value in having the new tag filter as there is no way to see the tags in the list<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6951">issues.joomla.org/joomla-cms/6951</a>.</sub>

**Comment by brianteeman** [comment]
Although as I see it is already present before this PR it should probably stay
So i am marking this as a successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6951">issues.joomla.org/joomla-cms/6951</a>.</sub>

**Comment by bertmert** [comment]
@test Order-By drop down failed.

@pe7er 
Remove these lines in .../tmpl/default.php

```
<input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>" />
<input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>" />
```

**Comment by bertmert** [comment]
@test Tag filter doesn't work correctly.

Scenario 1:
- Logout from backend. Delete cookies [= kill session]. Clear browser cache.
- Login and go directly to Contacts Manager ==> Saerch tool bar is open.

Scenario 2:
- Select a tag in search tools bar (nothing else!!)
- Search tools bar disappears

**Comment by bertmert** [comment]
@pe7er 
Fix for Scenario 2. 
Add 'tag' to $config['filter_fields'] in constructor of model.

**Comment by bertmert** [comment]
@pe7er 
Fix for Scenario 1 (but not tested if this colides with Hathor)

In model method populateState() change line
```
$access = $this->getUserStateFromRequest($this->context . '.filter.access', 'filter_access');
```

**Comment by pe7er** [comment]
Great! Thanks @bertmert !
I'll try your fixes after this weekend (or during the weekend at JandBeyond)

**Comment by pe7er** [comment]
I've corrected the order dropdown + problem with filter after filtering on Tags only with the fix from  @bertmert. 
Thanks @bertmert for this fix!

**Comment by pe7er** [comment]
I corrected the problem with open search filter with solution from @bertmert  
https://github.com/joomla/joomla-cms/pull/6951#issuecomment-105224082
Thanks!

**Comment by pe7er** [comment]
I had a merge conflict and redid the changes in new PR.
Please test #7072 instead. Thanks!

**Comment by zero-24** [comment]
I'm just closing here and just copied the instructions as we have a new PR #7072 Thanks :+1:

**Pull request closed without merging**
