### PR TITLE
[4.3] Guided Tours add full stop to description

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

all other descriptions for guided tours have a full stop at the end

### Testing Instructions

code review

### Link to documentations
Please select:

- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 97dd58462244446b0951c5d63b531490e0b582f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40401">issues.joomla.org/tracker/joomla-cms/40401</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97dd58462244446b0951c5d63b531490e0b582f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40401">issues.joomla.org/tracker/joomla-cms/40401</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40401">issues.joomla.org/tracker/joomla-cms/40401</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 !

**Pull request merged**
