### PR TITLE
[4.3][bug] Fix the infobar gap

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #39792 .

### Summary of Changes

Fixes the 4.2 up merge by removing a redundant line

### Testing Instructions

- Check that the infobar doesn't have any gap
- Check that an empty folder has correctly entered the upload icon

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 12b5c0b1ebdf9a41efca88e9d331aa8f07db19b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39796">issues.joomla.org/tracker/joomla-cms/39796</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 12b5c0b1ebdf9a41efca88e9d331aa8f07db19b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39796">issues.joomla.org/tracker/joomla-cms/39796</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39796">issues.joomla.org/tracker/joomla-cms/39796</a>.</sub>

**Comment by brianteeman** [comment]
I know we are in a freeze but this really should be merged before the beta release

**Comment by dgrammatiko** [comment]
> I know we are in a freeze but this really should be merged before the beta release

I will agree. @obuisard it's up to you

**Comment by obuisard** [comment]
> > I know we are in a freeze but this really should be merged before the beta release
> 
> I will agree. @obuisard it's up to you

This issue is unfortunate but is not critical to the functioning of the beta 1 version. We just entered the beta phase. This is the time to find bug and fix them. This fix will be merged in beta 2, as we are in beta 1 freeze right now, which is a time we take to make sure the packages we will provide to the public in a couple of days are properly built, installable and won't break people's test websites. Thank you very much Dimitris @dgrammatiko for this quick fix.

**Comment by dgrammatiko** [comment]
@obuisard ok but it would be better if people could also experience and play around with a fully functional Media Manager(?). Also this bug makes me look bad as it is my code conflicting with changes made in the 4.2 but for most people it would be `Dimitris broke the media manager`...

**Comment by obuisard** [comment]
> @obuisard ok but it would be better if people could also experience and play around with a fully functional Media Manager(?). Also this bug makes me look bad as it is my code conflicting with changes made in the 4.2 but for most people it would be `Dimitris broke the media manager`...

The media manager is fully functional, isn't it? Other than the extra space and the possible overlaps, I mean.
You have been greatly improving the media manager, anybody blaming you would not be in any position to do so. Those who do nothing can't break anything.

**Comment by chmst** [comment]
I think, people can play around with the media manager. This button is very useful but surely not used too often. I must say that I never used it, and it does not break the function. The ordering button is a better toy :)

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for your fix!

**Pull request merged**
