### PR TITLE
[5.2][Events] Use event classes for Media-action plugins

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

Update `media-action` plugins to use `SubscriberInterface` and event classes.

### Testing Instructions

Edit image in Media manager, try to crop and rotate it.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on eb24b353944226b8c96379c539531b204926e13b<br /><br />I have tested that the behavior before and after the plugin being activated is the same.

That said, while it behaves the SAME with or WITHOUT the plugin, the Media Manager is doing weird stuff.

I crop and rotate an image which is shown as cropped and rotated in the Media Manager(and also shown correctly cropped/rotated via Preview in the media manager) but when I import the image into my article, it is uncropped and original orientation ?! 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43608">issues.joomla.org/tracker/joomla-cms/43608</a>.</sub>

**Comment by brianteeman** [comment]
> I crop and rotate an image which is shown as cropped and rotated in the Media Manager(and also shown correctly cropped/rotated via Preview in the media manager) but when I import the image into my article, it is uncropped and original orientation ?!

Did you save

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on eb24b353944226b8c96379c539531b204926e13b<br /><br />@exlemor didn't get the issues you described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43608">issues.joomla.org/tracker/joomla-cms/43608</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43608">issues.joomla.org/tracker/joomla-cms/43608</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution, @Fedik!

**Pull request merged**
