### PR TITLE
[5.1] CLI: Adding command to manage Joomla core update channels

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
On the CLI, we can check for updates of the core and we can run the update as well, but we actually don't know what we are updating to, what update channel we are on and what the update process is actually doing right now. This PR tries to fix some of the issues by allowing to manage the update channels.

By calling `php cli/joomla.php core:update:channel`, you get the update channel the site is currently on. By adding the parameter `default`, `next`, `testing` or `custom`, you can set the update channel to that respective one. For `custom` you need to also add the `--url=<url>` parameter for the custom URL.

### Testing Instructions
1. Run `php cli/joomla.php core:update:channel` to display the currently configured update channel.
2. Run `php cli/joomla.php core:update:channel next` to set it to the "next" update channel. Check that the params column in `#__extensions` for the `com_joomlaupdate` row contains the updated `updatesource` value and that `location` column for `Joomla! Core` in `#__update_sites` contains `https://update.joomla.org/core/sts/list_sts.xml` as URL.
3. Run it in addition with other combinations of options and see the change reflected in the core tables.
4. Run `php cli/joomla.php core:check-updates` to check for updates from the new update source.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b4ce80acb9c4212b2bb424f626fd923a545b4fbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42597">issues.joomla.org/tracker/joomla-cms/42597</a>.</sub>

**Comment by dautrich** [comment]
I tested following the Testing Instructions. As part of the test, I set the update channel to `next`, `testing`, and `custom`. For `custom` I added the parameter `--url="https://example.org/update`. Thereafter, I set the update channel back to `Testing`, but the Custom URL was not removed from the database.
I'm not sure whether this may lead to adverse effects. Clean solution would be to remove any Custom URL from the database if the update channel is set to anything but `custom`.

**Comment by brianteeman** [comment]
>  Thereafter, I set the update channel back to testing, but the Custom URL was not removed from the database.

Is it removed when you do the same in the web interface?

**Comment by dautrich** [comment]
@brianteeman 
No, it is not. I've set the update channel back to Default via the web interface, but the URL remains in the extensions table as well.
IMHO we would need another PR to have the URL removed.

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on b4ce80acb9c4212b2bb424f626fd923a545b4fbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42597">issues.joomla.org/tracker/joomla-cms/42597</a>.</sub>

**Comment by brianteeman** [comment]
> @brianteeman No, it is not. I've set the update channel back to Default via the web interface, but the URL remains in the extensions table as well. IMHO we would need another PR to have the URL removed.

thought so. some would consider it a good feature to have

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42597">issues.joomla.org/tracker/joomla-cms/42597</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
