### PR TITLE
fixed admin mobile menu toggle not working

### PR DESCRIPTION
**Pull request by C-Lodder**
In regards to the issue discussed here: https://github.com/joomla/joomla-cms/issues/5912

### CODE REVIEW

**Comment by brianteeman** [comment]
Did you delete the wrong repo?

**Comment by C-Lodder** [comment]
@brianteeman - yeah, I ended up deleting and reforking when I got home. Does this cause any issues for the commit I made before?

**Comment by brianteeman** [comment]
I think you have deleted the wrong one. If you go to github it cannot fund
your code for this PR so it cannot be merged

**Comment by wilsonge** [comment]
It should be fine for merging (github shows a valid merge button anyhow) but if there are any issues with this pr you probably won't be able to update it and will have to make another new one.

**Comment by wilsonge** [comment]
@test replicated the initial menu issue and patch fixes it. One more tester

**Comment by brianteeman** [comment]
I tested it originally before the LESS was added. As the LESS compiles  (or
George couldnt have tested it correctly) I thik mine and all ther previous
tests should count and this can be merged

On 30 January 2015 at 21:51, George Wilson <notifications@github.com> wrote:

> @test <https://github.com/test> replicated the initial menu issue and
> patch fixes it. One more tester
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5924#issuecomment-72276476>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
moving to RTC since we have two tests here Thanks to all here!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5924">issues.joomla.org/joomla-cms/5924</a>.</sub>

**Comment by wilsonge** [comment]
Merged. Thanks for you're first PR @C-Lodder

**Pull request merged**
