### PR TITLE
[Fix #5635] Adding a significant message when passwords do not match

### LINKED ISSUE #5635: User Manager: Add New User:: Wrong message, If 'confirm password' is not same as 'password'
**Prerequisites: Plugin Manager: User - Joomla>Notification Mail to User>'NO'** 

-Go to 'User Manager: Add New User'
-Fill Name,login name, Password, email id correctly but do not enter the same password in 'confirm password' field and click on save button
-Check the message,**That should be error message instead of warning**

**Message should be:- **Confirm password** must be same as **password**'

screen shot 2015-01-07 at 04 15 20
screen shot 2015-01-07 at 04 15 32

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/5635
Test instructions:
Back-end
User Manager=>Add New User
Fill Name, login name, Password, email correctly but do not enter the same password in 'confirm password' field and click on save button.

After patch we will now get (same message as in other similar conditions in frontend and for profile edit)
screen shot 2015-05-10 at 08 40 46

### CODE REVIEW

**Comment by brianteeman** [comment]
It is good to change all uses to the same string but personally I would be prefer changing them all to a simpler message
"The passwords you entered do not match."

In general we write short messages and not documentation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6913">issues.joomla.org/joomla-cms/6913</a>.</sub>

**Comment by infograf768** [comment]
The purpose of this patch is not to change multiple strings which value has never been questioned, but just to normalise behavior.
Feel free to provide a separate PR to change all these strings if you wish, after this has been merged.

**Comment by jwaisner** [comment]
@test 

 Patch works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6913">issues.joomla.org/joomla-cms/6913</a>.</sub>

**Comment by SpiritJC** [comment]
@test patch works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6913">issues.joomla.org/joomla-cms/6913</a>.</sub>

**Comment by zero-24** [comment]
RTC Based on testing :smile: #jab15 #makeithappen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6913">issues.joomla.org/joomla-cms/6913</a>.</sub>

**Pull request merged**
