### PR TITLE
Update UCMContentHistory: Fixes

### PR DESCRIPTION
**Pull request by izharaazmi**
Update UCMContentHistory: Fixed unquoted property value in SQL causing error. Consistent use of getter.

### CODE REVIEW

**Comment by zero-24** [comment]
@izharaazmi can you add some testinstructions?

**Comment by izharaazmi** [comment]
Here are the test instructions:

```php
$table = JTable::getInstance('Contenthistory', 'JTable');
$table->getHashMatch();
```

Without this patch:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `ucm_type_id` = AND `sha1_hash` = '' LIMIT 0, 1' at line 3 SQL=SELECT * FROM `sa34_ucm_history` WHERE `ucm_item_id` = AND `ucm_type_id` = AND `sha1_hash` = '' LIMIT 0, 1
```
No error after this patch.

Same approach can be applied to `ContenthistoryModelHistory::getListQuery()`

**NOTE:** Such errors occurs when `ucm_item_id` or `ucm_type_id` is `0` or non-numeric string as they are unquoted literals.

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on d35aad452cc63a9f5ee9ac11d6795f4314af614d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8091">issues.joomla.org/joomla-cms/8091</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on d35aad452cc63a9f5ee9ac11d6795f4314af614d<br /><br />@Test working fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8091">issues.joomla.org/joomla-cms/8091</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8091">issues.joomla.org/joomla-cms/8091</a>.</sub>

**Pull request merged**
