### PR TITLE
REGRESSION: Logout redirection

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11089

Issue introduced by https://github.com/joomla/joomla-cms/pull/10985

Patch and test that logout redirections work properly

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<br /><br />Tested successfully with Joomla Version: Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT 
OS: Windows 8.1 and Browser: Firefox 47.0.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Comment by Lavsteph** [comment]
It's ready for me

**Comment by JamalTailored** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by NeerajTasol** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by klaasnicolaas** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on d2adedf585fd34eb4752e8beca96c1d83f3d7d1b<br /><br />Perfect, working fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11093">issues.joomla.org/joomla-cms/11093</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks everyone!

**Comment by nirovi** [comment]
I have problem: 

# Error: 0 - syntax error, unexpected 'else' (T_ELSE)
You may not be able to visit this page because of:an out-of-date bookmark/favourite

    a search engine that has an out-of-date listing for this site

    a mistyped address

    you have no access to this page

    The requested resource was not found.

    An error has occurred while processing your request.

**Comment by nirovi** [comment]
It Works, sorry was my mistake.

vn

**Comment by edoorz** [comment]
How can I get this patch for 3.6.0? I am having logout redirection issues as well.

**Comment by zero-24** [comment]
You can go to this page: https://github.com/joomla/joomla-cms/pull/11093/files and apply the changes or wait for the 3.6.1 update ;)

**Comment by edoorz** [comment]
I will apply the update. 
Thank you very much for your time and work. 

Joanne Knight-Reader

**Comment by StefanSTS** [comment]
Works in J 3.6.1 RC1 as expected, thanks.

**Pull request merged**
