### PR TITLE
[4.0] [workflow] Translate title

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30229

### Summary of Changes
Translating Workflow list items and stages when editing them, as done for custom admin menus

### Testing Instructions
Patch and edit Basic workflow

`administrator/index.php?option=com_workflow&view=workflow&layout=edit&id=1&extension=com_content.article`

then edit Basic stage

`administrator/index.php?option=com_workflow&view=stages&workflow_id=1&extension=com_content.article`

### Actual result BEFORE applying this Pull Request
As titles in db are lang constants, they are displayed as such. No translation is provided, although the translation is present in the list. **The fact that these are constants is voluntary to cope with different languages.**

### Expected result AFTER applying this Pull Request

Screen Shot 2020-07-30 at 10 24 18

Screen Shot 2020-07-30 at 10 29 29

### CODE REVIEW

**Comment by infograf768** [comment]
Note: we may consider to do the same for Transitions although none are provided by core as lang constants. For another patch after discussion

**Comment by infograf768** [comment]
Modified "Title" to "Name" to fit with field label and column heading
Screen Shot 2020-07-30 at 10 57 28
Screen Shot 2020-07-30 at 10 56 13

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 710dfd92be973cffb7511a0bdac93a5da54179d5<br /><br />4.0.0-beta4.dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30231">issues.joomla.org/tracker/joomla-cms/30231</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 710dfd92be973cffb7511a0bdac93a5da54179d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30231">issues.joomla.org/tracker/joomla-cms/30231</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30231">issues.joomla.org/tracker/joomla-cms/30231</a>.</sub>

**Pull request merged**
