### PR TITLE
[4.0] fields batch button

### PR DESCRIPTION
**Pull request by brianteeman**
In all components the batch button is now in the actions dropdown. Looks like it wass missed for com_fields

### CODE REVIEW

**Comment by wilsonge** [comment]
codestyle please

**Comment by brianteeman** [comment]
done - with all the failing tests i had stopped looking at drone

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a68df7941335e6d811b21d9f1b2656451cd76327<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26144">issues.joomla.org/tracker/joomla-cms/26144</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :) it worked after you fixed things!

sometimes. occasionally but shh :P

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
