### PR TITLE
com_languages languages view, ordering in searchtools

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_languages content languages view.

Also corrects some code issues and adds Home ordering.

And other small code changes/improvements.
###### Before PR

com_languages-languages-beforepr
###### After PR

com_languages-languages-afterpr
#### How to test
1. Install latest staging and apply this patch
2. Go to Extensions -> Languages -> Content languages
3. Check the ordering select box and the filter are working fine.

### CODE REVIEW

**Comment by richard67** [comment]
Hmm, would look better if the flags were in case of current admin language direction LTR left and in case of RTL right beside the image prefix, so in the screenshots above with LTR left beside the image prefix.

I know it was same ugly before and after this PR, but if you agree and easily can change that ... can you check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b5cd1b8fb462ff51eee661066d4db9da04ff05e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Done

image

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cf0d882f94dcd502ac9e86bc9f61cd6a3e6ff0e3<br /><br />Tested with success.

Latest change also tested for RTL with admin language = Arabic. Flag comes before the prefix, i.e. when LTR left and when RTL right beside prefix. Looks really much better than before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cf0d882f94dcd502ac9e86bc9f61cd6a3e6ff0e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by infograf768** [comment]
"Archived" is not possible for Content Languages. This was also present before this patch.
Can you correct this here and also change the filter_languages.xml to
```
		<field
				name="published"
				type="status"
				filter="*,-2,0,1"
				onchange="this.form.submit();"
				>
			<option value="">JOPTION_SELECT_PUBLISHED</option>
		</field>
```

**Comment by andrepereiradasilva** [comment]
@infograf768 thanks for the comments. Will correct the issue later.

**Comment by andrepereiradasilva** [comment]
@infograf768 archive removed and now mobile friendly.

@brianteeman @richard67 Can you retest?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on afec57abeb15a145d0dab4fc19d1c96b70b5c5f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on afec57abeb15a145d0dab4fc19d1c96b70b5c5f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9099">issues.joomla.org/joomla-cms/9099</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks guys!

**Pull request merged**
