### PR TITLE
clean path in HTMLHelper:: & prevent duplicate / 

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#19048

### Summary of Changes
cleaned all paths to ensure platform proper styling with no mixed platform cases.
no extra '/' in path

### Testing Instructions
put preceding '/' in file in HTMLHelper:: call like below..
if($customCSS){ HTMLHelper::_('stylesheet', '/custom.css', $HTMLHelperOptions); }

### Expected result
'<link'> or <script> is created with proper pathing

### Actual result
// between base and filename.
Mixed case of / and \ in path

### Documentation Changes Required
none.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e1baf5f6f374841c3bdee73097e909b6a2a0f097<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26294">issues.joomla.org/tracker/joomla-cms/26294</a>.</sub>

**Comment by brianteeman** [comment]
Sorry @N6REJ this pr is not correct. When you created the branch you did it from the branch you did your sr-only work in. You should always create your new branch from the current upstream branch

**Comment by N6REJ** [comment]
crap crap crap...        
yep, I knew that, forgot to switch back first.. I'll fix it right away.

**Comment by N6REJ** [comment]
@brianteeman it's weird cause I was sure I was careful  ( and I was https://github.com/N6REJ/joomla-cms/commit/e1baf5f6f374841c3bdee73097e909b6a2a0f097 ) but I see what your saying.
Did I fix it right?

**Comment by brianteeman** [comment]
> Did I fix it right?

Look on github - you can see that you did not

**Comment by N6REJ** [comment]
@brianteeman I did look but now its an even bigger mess *sigh*.. I'm closing thing then redoing it... YET AGAIN...

**Comment by SharkyKZ** [comment]
Why would you add a leading slash in the first place though?

**Comment by N6REJ** [comment]
valid point but I've seen it done with the previous method that most are used to.  I'd say its more proactive then necessary.

**Comment by N6REJ** [comment]
just fyi there is a new pr for this. #26303

**Pull request closed without merging**
