### PR TITLE
[4.0] Wrong string in com_users

### PR DESCRIPTION
**Pull request by brianteeman**
The wrong string (that was missing) was being used.

### before
chrome_2019-02-14_11-49-16

### after
image

NOTE Any a11y issue regarding this is beyond the scope of this PR

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on f5310d1b53eed9b40bcdd584f394f163cf543604<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23901">issues.joomla.org/tracker/joomla-cms/23901</a>.</sub>

**Comment by ChristineWk** [comment]
@brianteeman FYI: I got "You can't block yourself". Before and after patch. Means this successfully now? :-)
(Nightly update build dev-7 Feb11th)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23901">issues.joomla.org/tracker/joomla-cms/23901</a>.</sub>

**Comment by brianteeman** [comment]
@ChristineWk to test you must have another user. you can not test this on the user that you are logged in as

**Comment by bahl24** [comment]
@brianteeman But you mentioned that we should avoid using titles due to a11y issues

**Comment by brianteeman** [comment]
@bahl24 this is just to fix the missing string. As I stated in the post the a11y issues are beyond the scope pf this pr

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f5310d1b53eed9b40bcdd584f394f163cf543604<br /><br />ah OK - just added now 2nd User :-) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23901">issues.joomla.org/tracker/joomla-cms/23901</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23901">issues.joomla.org/tracker/joomla-cms/23901</a>.</sub>

**Comment by davidemessia** [comment]
I have tested this item :white_check_mark: successfully on f5310d1b53eed9b40bcdd584f394f163cf543604<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23901">issues.joomla.org/tracker/joomla-cms/23901</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
