### PR TITLE
[4.0] com_finder labels [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Same issue as with #29902

Ensures that there is only one label and that it is correctly named

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 268b87de68d5c3187a6c84ea4bd68165c3b2705e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29914">issues.joomla.org/tracker/joomla-cms/29914</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 268b87de68d5c3187a6c84ea4bd68165c3b2705e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29914">issues.joomla.org/tracker/joomla-cms/29914</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29914">issues.joomla.org/tracker/joomla-cms/29914</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
