### PR TITLE
[4.0] Add validation capability to access level field

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

This adds validation capability to `Joomla\CMS\Form\Field\AccessLevelField` by generating field options in field's `getOptions()` method instead of in the layout.

### Testing Instructions

Modify `administrator/components/com_content/forms/article.xml` to add `validate="options"` attribute to `access` field:

```
<field
	name="access"
	type="accesslevel"
	label="JFIELD_ACCESS_LABEL"
	validate="options"
/>
```

Test A:

Edit an article.
Save the article.

Test B:

Edit an article.
Using browser's developer tools, edit the markup of access field to add invalid value, e.g.:

    <option value="111111" selected="selected">Public</option>
Save the article.

### Expected result

A) Article saved successfully.

B) Saving article fails with warning:

>Invalid field: Access

### Actual result

A) Saving article fails with warning:

>Invalid field: Access

B) Saving article fails with warning:

>Invalid field: Access

### Documentation Changes Required

Maybe.

### CODE REVIEW

**Comment by wilsonge** [comment]
Looks very sensible to me - just needs a test. No docs required :)

**Comment by richard67** [comment]
@SharkyKZ Am confused. On a clean, new install of 4.0-dev, I proceed as described and get the expected result without having this PR applied. What am I doing wrong?

**Comment by SharkyKZ** [comment]
@richard67 Have you modified the article form for testing purposes?

**Comment by richard67** [comment]
@SharkyKZ Yes, I did everything exactly as described in testing instructions. Or does it need some extra step? Is that XML cached somewhere in DB? I mean I did even logout and login again to make sure the modified XML is read.

**Comment by SharkyKZ** [comment]
Without patch, after modifying form saving always fails. I'll update instructions for both cases.

**Comment by richard67** [comment]
Can it be that actual result and expected result in testing instruction are mixed up?

I assume actual result = "article can be saved without any warning" is what I should get without this PR applied, and expected result = "article can't be saved, warning is shown" is what I should get with this PR applied.

But if it is vice versa, the testing instructions are wrong. But then I would not understand the test, because I assume you want to show that validation of the "111111" value fails with this PR and does not fail without.

**Comment by richard67** [comment]
Ah I see you just answered.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e640463d50b3386320885ce787eb321becb36fa0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25817">issues.joomla.org/tracker/joomla-cms/25817</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
