### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by coolcat-creations**
Fix languagecode has to be 2 letters like en or de or fr and not de-DE, en-GB etc.

Pull Request for Issue # .

### CODE REVIEW

**Comment by C-Lodder** [comment]
The region is used as the dialect, e.g there's a difference between `en-US` and `en-GB`. The dialect can be used by the browser or other software. Shouldn't be removed at all.

**Comment by infograf768** [comment]
Again, as in https://github.com/joomla/joomla-cms/pull/24104, this is wrong.
Please close PR.

**Comment by brianteeman** [comment]
Not sure what you are trying to achieve here but it is wrong

The lang attribute is made up made of hyphen-separated “language subtags”

References
1. [IETF RFC](https://tools.ietf.org/html/bcp47)
2. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)

**Comment by infograf768** [comment]
Closing this.

**Comment by richard67** [comment]
If you want to have 2 letter codes only, you can use the languagecode plugin.

**Pull request closed without merging**
