### PR TITLE
[4.3] Disabled menu items

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #19874 (yes it's an old one) .

If you have a menu item to a disabled or uninstalled component then it is displayed as unpublished. This is not correct as the menu link is still displayed on the site and causes confusion as seen in the original report.

### Summary of Changes
Display a warning icon instead of an unpublished icon. 
Remove the clickable action on the icon which can't do anything
Use the correct tooltip

### Testing Instructions
Install any 2 components and create a menu item for each.
Disable component1 in the extension manager
Uninstall component2 from the extension manager

### Actual result BEFORE applying this Pull Request
image

Not shown in the screenshot but the icon is clickable

### Expected result AFTER applying this Pull Request
image

Not shown in the screenshot but the icon is not clickable

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 512b04ae05bbdb0e1f49993076a2ad7a11f0dd46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40353">issues.joomla.org/tracker/joomla-cms/40353</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40353">issues.joomla.org/tracker/joomla-cms/40353</a>.</sub>

**Comment by obuisard** [comment]
We would have loved to see this in 4.3. However, we are now in the bug fixing period with the version.
This is a great enhancement, improves UX/UI with appropriate language and icon.
This is why I have tagged it for 5.0.

**Comment by brianteeman** [comment]
This is a bug fix for a five year old bug report- its not a new feature.

**Comment by obuisard** [comment]
> This is a bug fix for a five year old bug report- its not a new feature.

I revised it once more. You are right, this is a bug.

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR. That was an old one indeed!

**Comment by brianteeman** [comment]
thanks for reconsidering

**Comment by obuisard** [comment]
Of course! Thanks to you.

**Pull request merged**
