### PR TITLE
[5] Contacts Options: Image not shown in Frontend

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42362 .

### Summary of Changes
use component settings as default

### Testing Instructions

set show image in Contact options

### Actual result BEFORE applying this Pull Request
no Image is shown

### Expected result AFTER applying this Pull Request
Image is shown 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a24ac75b5a06fa1e41e9443b890d320ce52daa11<br /><br />5.1.0-alpha4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43126">issues.joomla.org/tracker/joomla-cms/43126</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a24ac75b5a06fa1e41e9443b890d320ce52daa11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43126">issues.joomla.org/tracker/joomla-cms/43126</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43126">issues.joomla.org/tracker/joomla-cms/43126</a>.</sub>

**Comment by bembelimen** [comment]
I think the correct approach is to merge the parameters in the correct order.

**Pull request closed without merging**
