### PR TITLE
[a11y] Check all clarification

### PR DESCRIPTION
**Pull request by brianteeman**
In every list view is a check box that will let you check all the items

During JAB17 it was suggested that just saying "Check All" was too vague and it was meaningless to a screen reader. This pr accepts the proposal to change this to "Check All Items" instead.

screenshotr00-23-44

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ff8e6c327b2c8d63186940a3fd84585d7ebfaa10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16589">issues.joomla.org/tracker/joomla-cms/16589</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on ff8e6c327b2c8d63186940a3fd84585d7ebfaa10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16589">issues.joomla.org/tracker/joomla-cms/16589</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
