### PR TITLE
[#26930] fix: Usergroup field plugin - Plugin option 'Multiple' - Des…

### PR DESCRIPTION
**Pull request by shinderohanoffical**
…cription of the field is missing

Pull Request for Issue # .

### Summary of Changes
1: Change in language fine(en-GB.plg_fields_usergrouplist.ini)
2: Change in xml file (usergrouplist.xml).

### Testing Instructions
1: Go to usergroup field plugin
2: Check plugin option multiple, what is the field for is missing.

### Expected result
Add a description for the multiple plugin option

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 4f7d70c11d5b55b324f3e70f59c744e8c36eb9fa
#pbf19 #test1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26931">issues.joomla.org/tracker/joomla-cms/26931</a>.</sub>

**Comment by SharkyKZ** [comment]
This was removed intentionally. In 4.0 we're trying to avoid useless descriptions.

**Comment by kishorchate** [comment]
#pbf19 #test2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26931">issues.joomla.org/tracker/joomla-cms/26931</a>.</sub>

**Comment by kishorchate** [comment]
I have tested this item :white_check_mark: successfully on 4f7d70c11d5b55b324f3e70f59c744e8c36eb9fa<br /><br />#pbf19 #test2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26931">issues.joomla.org/tracker/joomla-cms/26931</a>.</sub>

**Comment by Quy** [comment]
Closing for reason stated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26931">issues.joomla.org/tracker/joomla-cms/26931</a>.</sub>

**Pull request closed without merging**
