### PR TITLE
[5.1] Use created_by 0 if created_by is empty

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #43674 .

### Summary of Changes
Make sure that created_by = 0 

### Testing Instructions
see #43674, change the Author of an article to "no user" 

### Actual result BEFORE applying this Pull Request
Save failed with the following error: Incorrect integer value: '' for column `joomla_51`.`xw6tv_content`.`created_by` at row 1

### Expected result AFTER applying this Pull Request
Article is saved and created_by is set to 0.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 238b1b82d13564f8c8f99a93819eca2a385f427e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43752">issues.joomla.org/tracker/joomla-cms/43752</a>.</sub>

**Comment by SimVT** [comment]
I tested this successfully on both a new and existing 5.1.1 installation.

**Comment by richard67** [comment]
@SimVT If you have tested this PR, please mark your result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/43752 by using the blue "Test this" button at the top left corner, then selecting the test result and finally submit. This is needed so that the test result is properly counted. It needs 2 successful tests for each PR to get accepted. You can help with that by marking your test result. Thanks in advance.

**Comment by SimVT** [comment]
I have tested this item :white_check_mark: successfully on 238b1b82d13564f8c8f99a93819eca2a385f427e<br /><br />I tested this successfully on both a new and existing 5.1.1 installation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43752">issues.joomla.org/tracker/joomla-cms/43752</a>.</sub>

**Comment by SimVT** [comment]
Thank you Richard67 and my apologies for not knowing the process.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43752">issues.joomla.org/tracker/joomla-cms/43752</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43752">issues.joomla.org/tracker/joomla-cms/43752</a>.</sub>

**Pull request merged**
