### PR TITLE
Can not install joomla on MSSQL - remove semicolon before UNION ALL

### PR DESCRIPTION
**Pull request by csthomas**
Fix for previous PR #13626

### Summary of Changes
Remove semicolons lying before UNION ALL.

### Testing Instructions
Code review. 
Or try to install latest joomla staging 
- before patch it fails
- after patch it works

### Documentation Changes Required
No

### CODE REVIEW

**Comment by alikon** [comment]
ops 
thanks  @csthomas

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e90bb76f9482cb56ebb6e5ec9b333a852d5be643<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13767">issues.joomla.org/tracker/joomla-cms/13767</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on e90bb76f9482cb56ebb6e5ec9b333a852d5be643<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13767">issues.joomla.org/tracker/joomla-cms/13767</a>.</sub>

**Comment by laoneo** [comment]
Ready fro RTC then. Thanks guys!!

**Comment by csthomas** [comment]
If we want to have MSSQL version working (I talk about whole joomla) then it need more changes:
- sql type datetime to datetime2 - missing
- unicode chars support and escape fix - ready and waiting for tests #13585
- GROUP BY workarounds - #13262 unfinished, need redesign a little

**Comment by dgt41** [comment]
RTC

**Pull request merged**
