### PR TITLE
[4.0][Fix] Language change for toggle editor button

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull Request for Issue #23891

### Summary of Changes
Changed the language of toggle editor button from ```Toggle editor``` to ```Toggle Editor```

### Testing Instructions
Open any article from the article list view. 
If there are no articles create one. 

### Expected result

toggle3

### Actual result

toggle 2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by hardik-codes** [comment]
Members please review this PR

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8074f5301923a58920efc92fc2889aa8a84e2cf2<br /><br />Simple test. Can be merged on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23892">issues.joomla.org/tracker/joomla-cms/23892</a>.</sub>

**Comment by HLeithner** [comment]
Is there a reason changing this to uppercase? I'm not a native speaker so I wonder.

**Comment by hardik-codes** [comment]
> Is there a reason changing this to uppercase? I'm not a native speaker so I wonder.

Other tabs such as Configure Edit Screen, which comprises of more than one word has its first letter of each word capital, the PR is  just to maintain consistency

**Comment by brianteeman** [comment]
@HLeithner we have a style guide https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html

**Comment by HLeithner** [comment]
@brianteeman perfect thx, I restarted drone without (can't be merged without it)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8074f5301923a58920efc92fc2889aa8a84e2cf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23892">issues.joomla.org/tracker/joomla-cms/23892</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23892">issues.joomla.org/tracker/joomla-cms/23892</a>.</sub>

**Pull request merged**
