### PR TITLE
[4.0] [UX] Use number field for num_columns in blog and featured layout

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Improve UX. Users can select a number of columns from a dropdown. (was a text input field).

### Testing Instructions
Compare menu items for blog and featured before and after Patch.

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by chmst** [comment]
Thanks for the nudge @angieradtke

**Comment by brianteeman** [comment]
Not sure about this being a dropdown as it enforces a maximum number of columns. Why not just correct the type of the field from text to number.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 259aaae7da2487e6c5186f393b100040bcc47686<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by chmst** [comment]
@brianteeman The css is made for 4 columns maximum.

**Comment by brianteeman** [comment]
for cassiopeia but what about a custom template?

**Comment by chmst** [comment]
Touchée. Will commit asap.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 259aaae7da2487e6c5186f393b100040bcc47686<br /><br />I think, 4 columns are enough :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by brianteeman** [comment]
> I think, 4 columns are enough :-)

Really depends on the use case.

**Comment by angieradtke** [comment]
@chmst  welcome -> I am just talking and you have the work

@brianteeman @ChristineWk 
4 columns are enough-> if we can be flexible here,  it would be great.  If not we have to deal width 4


maybe an example : If we want to build   a  horizontal snapslider  it would be great  to select 10 columns

**Comment by chmst** [comment]
Thank you all. I have changed the dropdowns to number field.

**Comment by ChristineWk** [comment]
> 
> 
> > I think, 4 columns are enough :-)
> 
> Really depends on the use case.

yes of course :-)

**Comment by ChristineWk** [comment]
you are too fast :-) following just for info:

**Comment by ChristineWk** [comment]
4 columns not possible if there are modules on the right position :-)
screen shot 2021-05-02 at 11 14 11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by ChristineWk** [comment]
@chmst 

amendments to number fields works now, but a question: 
screen shot 2021-05-02 at 11 16 33
The arrows are inactive? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by angieradtke** [comment]
> 4 columns not possible if there are modules on the right position :-)

depends on the template .-)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f75a1899509bb5b039057b37aa2d9606df8745f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by ghost** [comment]
>  The arrows are inactive?

@ChristineWk i think they show that its a number field, arrow-up -down works. But first i tried to click with the mouse :-)

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f75a1899509bb5b039057b37aa2d9606df8745f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by ChristineWk** [comment]
> 
> 
> > 4 columns not possible if there are modules on the right position :-)
> 
> depends on the template .-)

of course :-) @angieradtke

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f75a1899509bb5b039057b37aa2d9606df8745f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by richard67** [comment]
I've allowed myself to change the title of this PR so it fits to latest changes for using number fields.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33482">issues.joomla.org/tracker/joomla-cms/33482</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR, see issue #33477 .

**Comment by richard67** [comment]
I've updated the branch to latest 4.0-dev to get rid of the unrelated javascript-cs error in drone and restored the previous test results in the issue tracker.

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
