### PR TITLE
[4.0] Namespace content site route helper

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Namespace content site route helper.

### Testing Instructions
Open an article on the front.

### Expected result
Article is displayed.

### Actual result
Article is displayed.

### CODE REVIEW

**Comment by wilsonge** [comment]
Conflicts. But I want to sit on this one for a bit. I really really don't like mapping this class globally. But I need to have a think about what a better solution actually looks like - presumably something in the extensions container? :/

**Comment by laoneo** [comment]
I was also thinking about the container. Problem is that mostly legacy code is using it where boot is not called before.

**Comment by laoneo** [comment]
Conflicts fixed

**Comment by laoneo** [comment]
@wilsonge can you have a second look on this one. People are asking why we still have lowercase folders in core with classes. And on this one there is no reason to not namespace it.

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
I still feel that this is wrong because 3PD extensions have no way of adding entries into the extensions mapper file. This file should be something that we use to allow other extensions to function who extended non-namespaced classes. But as you say it gets the namespacing done for now and can be improved in the future.

**Comment by brianteeman** [comment]
Can you create an issue with your comments  so it doesn't  get forgotten

**Comment by wilsonge** [comment]
Done

**Pull request merged**
