### PR TITLE
[4] s/binary/string - Binary is not a valid PHPDoc type

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review 

https://phpstan.org/writing-php-code/phpdoc-types

Screenshot 2022-01-13 at 18 35 07

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on b35ed9531881e5f959273f99590da81262ae3a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36672">issues.joomla.org/tracker/joomla-cms/36672</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on b35ed9531881e5f959273f99590da81262ae3a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36672">issues.joomla.org/tracker/joomla-cms/36672</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36672">issues.joomla.org/tracker/joomla-cms/36672</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
