### PR TITLE
Fixed mobile admin menu

### PR DESCRIPTION
**Pull request by ghost**
This fixes the fixed height issue for the admin menu on narrow screens.

See for more info:
Github: https://github.com/joomla/joomla-cms/pull/6190
JIssues: http://issues.joomla.org/tracker/joomla-cms/6190

### CODE REVIEW

**Comment by C-Lodder** [comment]
Yup, this appears to work, however I would remove the class `.collapse` from the toggle button as it reduces the height of it.

screeny

**Comment by nonumber** [comment]
The class on the toggle button is not ```collapse``` but ```collapsed``` (with a d)

**Comment by C-Lodder** [comment]
@nonumber - Ahh my bad.

**Comment by n9iels** [comment]
@test: works fine for me, thanks! I noticed this bug this afternoon, glad you fixed it :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6298">issues.joomla.org/joomla-cms/6298</a>.</sub>

**Comment by nonumber** [comment]
Thanks for testing!

**Comment by JoomliC** [comment]
@test success! (both small sized window and iPhone)

The menu on narrow screens is now working back as it was working on 3.3.6! Thank you, didn't notice this bug in 3.4.0, and i'm happy this one is fixed before i'm away for a week-end, with only my iPhone to manage! ;-)

Thank you! :+1:

**Comment by zero-24** [comment]
RTC based on testing. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6298">issues.joomla.org/joomla-cms/6298</a>.</sub>

**Pull request merged**
