### PR TITLE
Subform.Repeatable styling (alternative to #12419)

### PR DESCRIPTION
**Pull request by ciar4n**
This is an alternative PR to #12419 based on the suggestion by @coolcat-creations 
### Summary of Changes

A PR to add some styling to repeatable subforms (joomla.form.field.subform.repeatable). 
### Testing Instructions

Create ../modules/mod_login/test.xml to which add the following...

```
<?xml version="1.0" encoding="UTF-8"?>
<form>
    <fieldset name="sample" class="sample-subform">
        <field name="image" type="media" default="" label="Sample Field 1"  description="Desc1" size="30" />
        <field name="text" type="text" default="" label="Sample Field 2" description="Desc2" />
        <field name="color" type="color" default="#dddddd" label="Sample Field 2" description="Desc2" />
    </fieldset>
</form>
```

Add the following to the ../modules/mod_login/mod_login.xml file:

```
<field name="subformtest" type="subform" formsource="modules/mod_login/test.xml" class="advancedSelect" min="0" max="50" multiple="true" layout="joomla.form.field.subform.repeatable" groupByFieldset="true" label="Repeatable Subform" description="Desc" />
```

**Before Patch**
repeatable1

**After Patch**
repeatable3

Note: Tried changing the icons directly (../layouts/joomla/form/field/subform/repeatable/secion.php) however any changes here did not reflect within the form. Possibly the wrong place? Changed the icons with CSS instead which is not ideal.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by C-Lodder** [comment]
The template.less is becoming extremely bulky now. We're using LESS, so I think it's time to start separating stuff into separate files to it's easier to maintain.

**Comment by ciar4n** [comment]
@C-Lodder I tend to agree with you. Not sure what would be the best way to categorize/split the file up, at least in a way that would be easily maintained in the future. Currently it is beginning to look like a long list of PRs (no thanks to myself I have to admit).

**Comment by Fedik** [comment]
please, do not forget, there also `joomla.form.field.subform.repeatable-table` layout, for render fields as table.
whether current changes do not break that layout?

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 9f46c68acae6bd6e41a6330c977d03844f6a4c59<br /><br />Thank you!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12634">issues.joomla.org/tracker/joomla-cms/12634</a>.</sub>

**Comment by ciar4n** [comment]
@Fedik 👍 Changes here will have no effect on `joomla.form.field.subform.repeatable-table`

**Comment by ciar4n** [comment]
@coolcat-creations Thank you for testing. I'd be happy to go with this over #12419 if you are.

**Comment by coolcat-creations** [comment]
Cool, thank you! Then we need just a second test. Thank you for this improvement!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5feab1a7b9ecfa6092ab86d071b2172ec581083d<br /><br />:+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12634">issues.joomla.org/tracker/joomla-cms/12634</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12634">issues.joomla.org/tracker/joomla-cms/12634</a>.</sub>

**Pull request merged**
