### PR TITLE
Fixes typo in getter and setter of form fields.

### PR DESCRIPTION
**Pull request by Achal-Aggarwal**
Updating PR 3306. See PR https://github.com/joomla/joomla-cms/pull/3306 for previous comment.

### CODE REVIEW

**Comment by roland-d** [comment]
@Achal-Aggarwal and @wilsonge What is the status of this PR? What needs to be tested?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4100">issues.joomla.org/joomla-cms/4100</a>.</sub>

**Comment by wilsonge** [comment]
Several of these have been fixed elsewhere in core. Not sure what's left now - we probably need to merge in staging and see

**Comment by roland-d** [comment]
I am fine to merge it, code review shows no issues. However the branch has conflicts, @Achal-Aggarwal can you fix those, so we can move this ahead?

**Comment by zero-24** [comment]
@roland-d @Achal-Aggarwal has fixed the milestones so we are fine to merge?

**Comment by roland-d** [comment]
Merged this, thanks. Unit tests ran fine and I tested it as well and all is good.

**Pull request merged**
