### PR TITLE
Revise Blog Data to Reflect the No. of Links to 2

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #17929.

### Summary of Changes
This PR applies the same change to PostreSQL and AzureSQL sql files that was not done in the original PR.

Credit goes to @imanickam 

### Testing Instructions
See #17929 or code review

### Expected result
`next two oldest articles`

### Actual result
`4 next oldest articles`

### Documentation Changes Required
no change

### CODE REVIEW

**Comment by brianteeman** [comment]
The same change needs to be made here

https://github.com/joomla/joomla-cms/blob/a8ce731debd810b4457f933732277d2126469dd8/administrator/language/en-GB/en-GB.plg_sampledata_blog.ini#L19

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 34ad7d9170af15ac491dfdaf8bc987ec68a89850<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19357">issues.joomla.org/tracker/joomla-cms/19357</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 34ad7d9170af15ac491dfdaf8bc987ec68a89850<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19357">issues.joomla.org/tracker/joomla-cms/19357</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19357">issues.joomla.org/tracker/joomla-cms/19357</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
