### PR TITLE
Use two editor fields with different editor xtd buttons in one form

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Steps to reproduce the issue

create a jform xml definition with two editor fields
for example open file administrator/components/com_content/models/article.xml
Add a new field nodes in the first fieldset above the field with name "articletext"
< field name="test1" type="editor"
label="Editor_No_Module_Pagebreak"
filter="JComponentHelper::filterText" buttons="true" hide="module,pagebreak" />
Make sure that tinymce is default editor on the Joomla! installation.
Open file administrator\components\com_content\views\article\tmpl\edit.php and replace

`<?php echo $this->form->getInput('articletext'); ?>`at line 88 
with
`<?php echo $this->form->getInput('test1'); ?>`
`<?php echo $this->form->getInput('articletext'); ?>`
in order to display the new editor field in article edit form.

Open an article in the edit view in the administration
#### Expected result

Display two editor fields in the article edit view. The first one having the editor xtd buttons article, image and readmore, the second one having the editor xtd buttons article, image, readmore, module and pagebreak
#### Actual result

Both editor fields have the same editor xtd buttons (article, iamge and read more).
### Testing

Apply patch and  re try the above code

### CODE REVIEW

**Comment by ggppdk** [comment]
The editor buttons now work properly for tinymce, but the 2 areas still show the same buttons

**Comment by ggppdk** [comment]
My comment about same buttons shown is wrong, i have not tested it yet

**Comment by dgt41** [comment]
>  but i have tested that buttons now work properly with multiple textareas

That was the point of this PR

**Comment by ggppdk** [comment]
@dgt41 
you are right

furthermore, i looked at the code, 
- using different editor buttons for tinymce is not implemented

i knew it was not,

but i got the impression this was implemented at some point (recently) because of the comments in #9697,
so the comment about "same buttons" in it, is wrong because this was never implemented for tinymce ?

**Comment by dgt41** [comment]
@ggppdk we can fix that easily:
screen shot 2016-04-02 at 02 27 20

To @all testers:

#### Please make sure that this DOES NOT introduce some B/C break

**Comment by ggppdk** [comment]
Yes, now different buttons are shown for each textarea

**Comment by avjoomla** [comment]
Hi thanks,

I tested with 74a161d and it solved the issue.

Regards,
Aicha

**Comment by dgt41** [comment]
@avjoomla @ggppdk can you mark your tests in issues.joomla.org ? Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9707">issues.joomla.org/joomla-cms/9707</a>.</sub>

**Comment by brianteeman** [comment]
Its ok I will do it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9707">issues.joomla.org/joomla-cms/9707</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9707">issues.joomla.org/joomla-cms/9707</a>.</sub>

**Comment by ggppdk** [comment]
Sorry i did not post through the issue tracker at the time

Please note that this fix is good
but it fixes **tinymce** only, 
- it does not fix other editors

**Comment by dgt41** [comment]
@ggppdk it's down to the plugin of each editor to be specific to each id, thus, I guess, we can only try to patch code mirror as the rest are 3pd code...

**Pull request merged**
