### PR TITLE
[4.1] @todo

### PR DESCRIPTION
**Pull request by brianteeman**
Most IDE have tools to quickly find @todo in the code base. This PR corrects the usage of TODO instead of @todo. It will make it easier in future to work through these items, check that they are still valid, and resolve them.

code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cc10476ba2f82793432655ad74e34ff9c008152f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36612">issues.joomla.org/tracker/joomla-cms/36612</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on cc10476ba2f82793432655ad74e34ff9c008152f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36612">issues.joomla.org/tracker/joomla-cms/36612</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36612">issues.joomla.org/tracker/joomla-cms/36612</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Comment by HLeithner** [comment]
adding a @xzy in a commit is a pain for the user which holds this name on github ;-)

**Comment by richard67** [comment]
There is really a user on GitHub with name "todo".

**Comment by brianteeman** [comment]
There is @todo and there is also @since 


which is why since gets capitalised after you submit it

**Comment by richard67** [comment]
I would guess that with such a user name one should be used to getting pinged 😄

**Pull request merged**
