### PR TITLE
[4.2] Add missing error messages to frontend for PR #37017

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for incomplete Pull Request #37017 .

### Summary of Changes

Copy language strings from backend to frontend because frontend uses also the backend model:
https://github.com/joomla/joomla-cms/blob/cd0e7499f716e28adcaeb62145805aabe18368d5/components/com_content/src/Model/FormModel.php#L33

### Testing Instructions

Create two contacts/article with the same alias in the **frontend**!

### Actual result BEFORE applying this Pull Request

Untranslated string:
image

### Expected result AFTER applying this Pull Request

Translated string:
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

ping @roland-d due untested PR #37017

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 84159e252bc16594878ff848e560f00742893eff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39065">issues.joomla.org/tracker/joomla-cms/39065</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 84159e252bc16594878ff848e560f00742893eff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39065">issues.joomla.org/tracker/joomla-cms/39065</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 84159e252bc16594878ff848e560f00742893eff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39065">issues.joomla.org/tracker/joomla-cms/39065</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39065">issues.joomla.org/tracker/joomla-cms/39065</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
