### PR TITLE
Fixed issue with tld param which has no effect

### PR DESCRIPTION
**Pull request by dziudek**
Pull Request for Issue #9500.
#### Summary of Changes

I've added + instead of \* in the regexp, so now after setting the tld param at least one domain is required in the e-mail. 
#### Testing Instructions

The regexps was the same so the tld param was not working for e-mail validation.

### CODE REVIEW

**Comment by infograf768** [comment]
Tests don't work and for a good reason: this patch prevents mails of the type `maymail@localhost`

The general result is: Address is valid for SMTP but has unusual elements

The specific diagnosis is: Address is valid but at a Top Level Domain

Here is the relevant passage from the email RFCs:

    In the case of a top-level domain used by itself in an email address, a single string is used without any dots. This makes the requirement, described in more detail below, that only fully-qualified domain names appear in SMTP transactions on the public Internet, particularly important where top-level domains are involved. 

RFC 5321 section 2.3.5
http://tools.ietf.org/html/rfc5321#section-2.3.5

**Comment by dziudek** [comment]
@infograf768 - ok, but what is the sense of existence for the tld param? As you can see before my change the regex property contains exactly the same regular expression. I thought that tld option enables a check for the tld domain in the e-mail.

**Comment by roland-d** [comment]
@dziudek I agree with you, this change is valid. If the field is set to check for a TLD it should check for a TLD. Since this file has been updated in the meantime, can you check if it works with the current staging version of Joomla?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9501">issues.joomla.org/joomla-cms/9501</a>.</sub>

**Comment by dziudek** [comment]
@roland-d - as I see the following change: https://github.com/joomla/joomla-cms/commit/98c48eee875c1953ec011f9dc8ea4ac58563dd2a doesn't fix the issue - I've checked it in http://regexr.com/

for test case:

```
test@gmail
test@gmail.com
```

The current regexp accepts both mails, when it should accept only the second one. And my change - replacing `*$` into `+$` at the end still helps :)

**Comment by roland-d** [comment]
@dziudek Thank you for checking. Could you update this pull request with the current codebase and your fix? I can have this tested after that. Thanks.

**Comment by dgt41** [comment]
@roland-d I think this is covered with https://github.com/joomla/joomla-cms/pull/10760 as we now use the code from w3c for that part

**Comment by dgt41** [comment]
Also what @infograf768 wrote above is right, so both cases are valid:
```
test@gmail
test@gmail.com
```

**Comment by roland-d** [comment]
@dgt41 No, I disagree that both cases are valid. If the XML definition states that the TLD is required we **must** check for it. If the TLD requirement is not set, then we should allow both cases.

As for the W3C query, yes it is valid for both cases but not if the TLD is required.

**Comment by dgt41** [comment]
@roland-d so how do you set the XML to require a TLD?
```XML
<field name="email" type="email"
	label="JGLOBAL_EMAIL"
	description="COM_ADMIN_USER_FIELD_EMAIL_DESC"
	required="true"
	size="30"
	class="inputbox"
	validate="email" />
```

**Comment by roland-d** [comment]
@dgt41 Check this line:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/rule/email.php#L56

You add the element tld to the XML field.

**Comment by dziudek** [comment]
@roland-d - I've just updated the codebase and applied the change with replacing replacing `*$` into `+$`

**Comment by roland-d** [comment]
@dziudek Thanks for that. There seems to be conflicts still, can you check and fix them? Thank you.

**Comment by dziudek** [comment]
@roland-d - I've updated the codebase in my repository and now it should be ok.

**Comment by roland-d** [comment]
@dziudek Indeed it's looking good and Travis is running. Let's hope Travis will be a nice boy :) Now people can test it again.

**Comment by brianteeman** [comment]
Travis isnt happy with this ;(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9501">issues.joomla.org/joomla-cms/9501</a>.</sub>

**Comment by roland-d** [comment]
The problem is with the unit test and not with the code. Checking what is going on...

**Comment by mbabker** [comment]
The failure is testing that `test3@localhost` passes the check with the `tld` attribute set and with this patch it's not.  If I'm glancing this over correctly, the change mandates a `domain.tld` structure.  So if that's the case, this data set needs to be changed so that false is the expected result since this won't pass since it's missing a TLD.  Or if `localhost` is supposed to be valid on its own even with the `tld` attribute set then the code needs to be adjusted to account for this special case.

**Comment by roland-d** [comment]
@mbabker Yes I came to the same conclusion, just don't know how to change the dataset because the email test3@localhost has a false value set in the dataset.

If you require a tld by specifying that in the XML then localhost shouldn't be allowed I guess unless we decide it's an exception to the rule.

**Comment by yvesh** [comment]
I don't think @localhost should be true in the last tld test.

@roland-d imo test3@localhost from the multiple values (emailData2) is not really important, because tld tests are only done in testEmailData3 with emailData3. `@dataProvider emailData3`

So only [this line](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/form/rule/JFormRuleEmailTest.php#L141) need changes, for the tests to pass.

**Comment by roland-d** [comment]
@yvesh Thanks for that. I don't know why but that line had a false argument when I was looking at it yesterday. That got me confused. No idea what I was looking at then :)

@dziudek Can you change the line mentioned by Yvesh and replace true with false and commit that change. We can then see if Travis passes. Thanks.

**Comment by dziudek** [comment]
@roland-d - I've synced the branch with current code base and I've added the updated test code - we will see if now Travis finish it successfully.

**Comment by roland-d** [comment]
@dziudek Fingers crossed :)

**Comment by dziudek** [comment]
@roland-d - It seems that all is ok - all necessary build are correct :)

**Comment by roland-d** [comment]
@dziudek Yes, persistence is paying off :) Now we need to get some people to test this.

**Comment by brianteeman** [comment]
How to test?

**Comment by degobbis** [comment]
I have tested it, now works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9501">issues.joomla.org/joomla-cms/9501</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 278ef93c8cae964a4f2fbfc523b4410debf52472<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9501">issues.joomla.org/joomla-cms/9501</a>.</sub>

**Comment by roland-d** [comment]
To test this, do the following:
1. Modify the file components/com_users/models/forms/registration.xml by adding this line to the email1 field ```tld="required"``` or ```tld="tld"``` both options work the same. This forces emails to have a TLD specified.
2. Try to register a user with an email me@example
3. Joomla will happily register this user
4. Apply the patch
5. Try to register a user with an email meagain@example
6. This will not be allowed and a message will be shown that the email address is invalid
7. Try to register the user with the mail meagain@example.com
8. User is now registered because a TLD exists.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 278ef93c8cae964a4f2fbfc523b4410debf52472<br /><br />Registering a user without a TLD is possible before the patch despite requiring the TLD. After applying the patch an email without TLD cannot be registered if required.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9501">issues.joomla.org/joomla-cms/9501</a>.</sub>

**Pull request merged**
