### PR TITLE
[4.0] Wrong tip for COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/31736#issuecomment-753543629

### Summary of Changes
Corrected the tip that should also have been corrected in https://github.com/joomla/joomla-cms/pull/31736

### Testing Instructions
To merge on review.

### After patch
string is now
`COM_INSTALLER_MSG_WARNINGS_UPLOADBIGGERTHANPOSTDESC="The value of the upload_max_filesize in the php.ini file is greater than the post_max_size variable. The post_max_size variable will take precedence and block requests larger than it. This is generally a server misconfiguration when trying to increase upload sizes. Please increase the value of post_max_size to be greater than the value of upload_max_filesize."`

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on fc6d7974ca78bcf824c1f3333151e0dbb9784ecc<br /><br />Tested successfully in Beta6-dev of 5 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31858">issues.joomla.org/tracker/joomla-cms/31858</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on fc6d7974ca78bcf824c1f3333151e0dbb9784ecc<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31858">issues.joomla.org/tracker/joomla-cms/31858</a>.</sub>

**Comment by infograf768** [comment]
@chmst 
The RTC label you set was not forwarded from Issues. I added it here.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
