### PR TITLE
[4.3] Fix check create article menu item with specific category

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #17708 .

### Summary of Changes

- fix check introduced with #25798
- during upmerge with #27056 by @wilsonge this check is broken

> as we have a onContentBeforeSave in J4 to deal with workflows. Nothing should have changed - it should be cosmetic - but just to document the change in case.

`checkMenuItemBeforeSave` is called when context is `com_menus.item`
https://github.com/joomla/joomla-cms/blob/c3593e96dc68b67df3337c2f0caa2ba2dcbdf05e/plugins/content/joomla/joomla.php#L66-L70

`checkMenuItemBeforeSave` always return true when context is `com_menus.item`
https://github.com/joomla/joomla-cms/blob/c3593e96dc68b67df3337c2f0caa2ba2dcbdf05e/plugins/content/joomla/joomla.php#L594-L599

### Testing Instructions

- add a new menu item `Create Article`
- enable `Specific Category` under `Options`
- do not select a category

### Actual result BEFORE applying this Pull Request

menu item is saved
image

### Expected result AFTER applying this Pull Request

menu item is not saved and an error message is displayed
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0df72f0bcc592ac81cc04b972a3f81d722a26adf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40637">issues.joomla.org/tracker/joomla-cms/40637</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0df72f0bcc592ac81cc04b972a3f81d722a26adf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40637">issues.joomla.org/tracker/joomla-cms/40637</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40637">issues.joomla.org/tracker/joomla-cms/40637</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for this PR!

**Pull request merged**
