### PR TITLE
Correcting Associations tab display when using Indonesian id-ID language

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24239

### Summary of Changes
Modifying js to cope with the id-ID language tag

Thanks **Robbie Jackson** !

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/24239

### Before patch
Screen Shot 2019-03-19 at 15 21 36

### After patch
Screen Shot 2019-03-19 at 15 19 51

### CODE REVIEW

**Comment by Geoplous** [comment]
I have tested this item :white_check_mark: successfully on 8a4a79d046d274918df9a3cb705411968ea37e83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24244">issues.joomla.org/tracker/joomla-cms/24244</a>.</sub>

**Comment by imanickam** [comment]
I have tested this item :white_check_mark: successfully on 8a4a79d046d274918df9a3cb705411968ea37e83<br /><br />Tested successfully on Joomla! 3.9.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24244">issues.joomla.org/tracker/joomla-cms/24244</a>.</sub>

**Comment by infograf768** [comment]
RTC 
Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24244">issues.joomla.org/tracker/joomla-cms/24244</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Pull request merged**
