### PR TITLE
Dependency - Bump joomla/filter to 1.4.3

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/32076#issuecomment-769794576 .

### Summary of Changes

Update the joomla/filter dependency to 1.4.3.

This pull request (PR) is required for PR #32076 .

### Testing Instructions

Check that the CMS continues to function as normal and that PR #32076 works on XAMPP on Windows , too, when the patch of this PR here is applied in addition to PR #32076 .

### Actual result BEFORE applying this Pull Request

CMS works.

### Expected result AFTER applying this Pull Request

CMS works.

### Documentation Changes Required

None.

### CODE REVIEW

**Review by nibra — APPROVED** [review]
LGTM

**Comment by richard67** [comment]
~~Hmm, I just see the `libraries/vendor/composer/installed.json` file is not changed in this PR. I think that's a mistake, but due to other reasons we might have to update anyway again to the next version.~~

~~I put this PR in draft status so it is not merged by mistake.~~

Missing file added. ~~If update to newer version will come with this PR or later we will see.~~

Update: No further change needed, PR is ready for testing.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 07157597e2e4187a9cd96b97a316e7e6a8f70143<br /><br />Works good for me. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32206">issues.joomla.org/tracker/joomla-cms/32206</a>.</sub>

**Comment by zero-24** [comment]
Given that within the CMS we are still using the build in code and not the framework code I will merge here for now thanks!

**Pull request merged**
