### PR TITLE
Joomla update message style

### PR DESCRIPTION
**Pull request by brianteeman**
Adds a strong to increase the visibility and maintain the em for semantic emphasis

### before
image

### after
image

### CODE REVIEW

**Comment by wojsmol** [comment]
code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38703">issues.joomla.org/tracker/joomla-cms/38703</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 47af4d90b99ea06b1e8fcc9b01ab0d5595fef92c<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38703">issues.joomla.org/tracker/joomla-cms/38703</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 47af4d90b99ea06b1e8fcc9b01ab0d5595fef92c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38703">issues.joomla.org/tracker/joomla-cms/38703</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38703">issues.joomla.org/tracker/joomla-cms/38703</a>.</sub>

**Comment by wojsmol** [comment]
@Quy Please re-add ` Language Change` label.

**Comment by fancyFranci** [comment]
Nice, thanks!

**Pull request merged**
