### PR TITLE
[4.1] Tasks enabled/disabled

### PR DESCRIPTION
**Pull request by brianteeman**
Tasks are enabled/disabled not published/unpublished. This PR corrects the tooltip for this using the same method as the plugin manager

### After
image

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 3a483e1580a5ad0683c9258948d5a6d5a76b2274<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36211">issues.joomla.org/tracker/joomla-cms/36211</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 64501d67815d7e74859f60f831c08f4863b193f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36211">issues.joomla.org/tracker/joomla-cms/36211</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36211">issues.joomla.org/tracker/joomla-cms/36211</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
