### PR TITLE
Support non-english chars in JS

### PR DESCRIPTION
**Pull request by Hackwar**
The previous code doesn't really support non-english characters and for example fails on german umlauts. This code is used in com_finder, so when you are searching for something like "Europäer", you wont get any highlighting for the searched term in the search results.

### How to test
1. Enable Smart Search content plugin
2. Edit/create an article with the word "Europäer"
3. Search for that word in the frontend
4. See that the word "Europäer" is not highlighted in the search results
5. Apply patch
6. Search again and now see it being highlighted.

### CODE REVIEW

**Comment by brianteeman** [comment]
This is something we really should have a test for. Specifically to ensure it not only supports accented characters in latin characters sets but also in non latin character sets and multibyte character sets.

**Comment by infograf768** [comment]
Although it does not always work (see below), it is a great improvement.
I have tested this item :white_check_mark: successfully on 3ea6a4774263dd65c1809a4d6ab3d822195eac96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by infograf768** [comment]
Example with Chinese

Screen Shot 2019-08-15 at 08 17 52

**Comment by infograf768** [comment]
Note: It does not work for single 4 bytes characters.
Example: 𠹷

Edit: 
"They are in the Supplementary Plane and will test support for code points above U+FFFF"
See: http://www.i18nguy.com/unicode/supplementary-test.html

**Comment by infograf768** [comment]
Dumping some of these 4 bytes characters is correct though
```
 Assuming 𠺝 is required, the following results were found.
string(7) "\u20e9d" 
```

**Comment by infograf768** [comment]
@Hackwar 
Another hint:
It looks like these 4 bytes characters are not saved correctly in the _finder_terms table

**Comment by wilsonge** [comment]
Agree with @brianteeman this is an easy function to test as it's static and no dependencies.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3ea6a4774263dd65c1809a4d6ab3d822195eac96<br /><br />Tested with "Überlingen", "Europäer", "Музыка", "Curaçao" and "香肠"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by richard67** [comment]
@infograf768 Just I noticed your posts above. Does it mean your test was not good? Should that work, 4-byte UTF-8? I know we did much for MySQL to support utf8mb4, and PHP should be ok, but maybe we have forgotten something in js? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3ea6a4774263dd65c1809a4d6ab3d822195eac96<br /><br />Agree with JM: A big improvement compared to now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by Fedik** [comment]
hm, can just be?
```
return json_encode($string);
```

**Comment by infograf768** [comment]
@Fedik 
with `json_encode($new_str)` we lose highlighting.

@richard67 
In my posts above I was just wondering why it does not work fully with 4 bytes glyphs when isolated.

FYI, this code is already present in 4.0 and we get the same results as here.

**Comment by richard67** [comment]
@Hackwar Is this code also used by the media manager? If so: Could it be that it solves issue #25997 ?
Edit: No, it seems to be used by the highlight behavior. I don't think that is used by media manager. But it seems media manager has a problem similar to the one handled in this PR here.

**Comment by brianteeman** [comment]
Richard. The media issue is completely different and a large part of that is the filesystem

**Comment by Hackwar** [comment]
I'll put writing tests for this on my todo list, but can we still merge this for 4.0, @wilsonge?

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25845">issues.joomla.org/tracker/joomla-cms/25845</a>.</sub>

**Comment by HLeithner** [comment]
@infograf768 does this support mb4?

@Hackwar you wrote this pr against J3, do you had time to write some tests for this?

**Comment by infograf768** [comment]
> @infograf768 does this support mb4?

yes, when we do not search an isolated utf8mb4 glyph
see above : https://github.com/joomla/joomla-cms/pull/25845#issuecomment-521532450

**Comment by HLeithner** [comment]
ok so can we fix this case for single mb4 character and have a test for this @Hackwar ?

Then we can fix this issue in staging. Thanks

**Comment by Hackwar** [comment]
Sorry, I would really love to help you right now, but I'm really swamped with work in the next few weeks. I doubt that I can get to this before christmas. If anybody wants to make a PR against my branch, that would be appreciated.

**Comment by HLeithner** [comment]
Since this is out JS safe output filter function I would request some feedback from @joomla/security and a complete PR with the mentioned single mb4 character.

**Comment by Hackwar** [comment]
I added a unit test. @infograf768 can you have a look if I did this right with the utf8mb4 glyph?

**Comment by infograf768** [comment]
Will test tomorrow

**Comment by infograf768** [comment]
Still no result for unique glyph like
𠹷

And we now lose highlighting for 
不能创建文件

Screen Shot 2020-03-29 at 09 35 30


i.e. it is a regression vs your original PR

**Comment by Hackwar** [comment]
I tested with your strings and the second string did work, while the first indeed did not work. I looked into this and again noticed that I'm not a JS developer. Javascript uses UCS-2 to encode its strings and that means that the code we've been using will only work for Unicode characters up to U+FFFF. Everything above would have to be converted in a way that I found too complicated for me to grasp. I took the cheap way out and for such characters I'm now using ECMAScript 6 notation with curly braces around the escape sequence. I did not want to use that for all characters, since I fear that that would be a break in B/C, since it would require that every browser would have to support ECMAScript. Since this feature didn't work at all up till now, I think it would be okay to require that compatibility for higher codepoints... What do you think?

**Comment by infograf768** [comment]
不能创建文件 is still not highlighted here (same result as above https://github.com/joomla/joomla-cms/pull/25845#issuecomment-605598380 ) while it is when we use com_search

com_search
Screen Shot 2020-03-30 at 08 46 23

**Comment by infograf768** [comment]
See also my tests for j4 https://github.com/joomla/joomla-cms/pull/28493

**Comment by wilsonge** [comment]
@Hackwar as long as you can do some feature detection i think it should be ok to use progressive enhancement

**Comment by richard67** [comment]
@infograf768 The Chinese problem could come from a collation problem in MySQL, see my comments in the J4 PR: [https://github.com/joomla/joomla-cms/pull/28493#issuecomment-609405098](https://github.com/joomla/joomla-cms/pull/28493#issuecomment-609405098) and previous.

**Comment by infograf768** [comment]
@richard67 
read. We should keep com_search

**Comment by richard67** [comment]
@infograf768 I'd like to keep com_search too, at least as alternative for small sites like my private site.

**Comment by Hackwar** [comment]
However this has nothing to do with com_search or com_finder. You have the exact same issue in com_search as well. It is an issue with the DB and the bad support for chinese characters.

**Comment by Hackwar** [comment]
@wilsonge @HLeithner Are you saying that you are requiring some check if this new notation is allowed to be used? Because I don't see how that could be done... Considering that it is broken right now and this would fix it for all users except for <IE11, I would accept this change as is...

**Comment by infograf768** [comment]
@Hackwar 
> You have the exact same issue in com_search as well. 

Wrong.
Once you set `getLowerLimitSearchWord()`to 1 instead of 3, the correct result is obtained and highlighted.

Screen Shot 2020-04-06 at 08 38 11

**Comment by infograf768** [comment]
OK to merge. Won't solve the issue in J3 as it would require a lot of work to make a new conversion. Also, as com_search works fine, there is an alternate solution.

For J4, see https://github.com/joomla/joomla-cms/pull/28587

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
