### PR TITLE
Fix filtering in extension manager's manage view

### PR DESCRIPTION
**Pull request by Erftralle**
This pull request fixes the problem discussed in issue #5781.

### CODE REVIEW

**Comment by zero-24** [comment]
@infograf768 i will add your test from here: https://github.com/joomla/joomla-cms/issues/5781#issuecomment-75200486 If it is not ok let me know. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6130">issues.joomla.org/joomla-cms/6130</a>.</sub>

**Comment by Bakual** [comment]
One thing to consider here is that we are essentially removing a security filter.
As far as I see you cna now pass anything you want for that filter. It isn't sanitised anywhere. Or I at least didn't see it when I had a look. Which is very likely a security issue.

**Comment by sovainfo** [comment]
Disagree on removing a security filter. It is about filtering output, not security related.

Do object to the change:
- Select type plugin, folder Authentication to see the plugins
- Select type component, to see your components before the change, or get the message there are no components in authentication folder after the change.

My preference is the current implementation ignoring not applicable filter.

**Comment by mahagr** [comment]
It's not security filter. At worst you end up having no results:

     WHERE folder='whateverstring'

Value is escaped, so there's nothing that can break.

**Comment by Bakual** [comment]
Thanks JSST and @sovainfo for checking. Fine for me then :+1:

**Comment by sovainfo** [comment]
Do you really want to piss off experienced administrator by forcing them to clear the filter when not applicable or do you want to tell dummies that the folder only applies to libraries and plugins and therefor is ignored for the other types!

Remember, you are changing functionality. You force people to do something extra because there are dummies that do something extra and don't understand the result.

**Comment by infograf768** [comment]
I guess the point here is that it is the only place in core where the results of filtering is incorrect.

**Comment by sovainfo** [comment]
So, the filter for folder should be hidded when it doesn't apply?
Disagree with not beeing correct. It is doing exactly what is expected. For now, it is the only place where we have optional filters. For something that is meant for Super users, that should be an issue.

**Comment by Erftralle** [comment]
I agree to @infograf768 .
The results should reflect the filter settings and not the filter settings combined with some expert knowledge that you only get by studying the source code.

**Comment by sovainfo** [comment]
Don't need to study code, just use your brain. For the record N/A means not applicable. What are you doing here, you lack the qualifications for Super user!

**Comment by infograf768** [comment]
>So, the filter for folder should be hidded when it doesn't apply?

That would indeed be the best.

**Comment by bertmert** [comment]
@test Success
I prefer to see what I've selected even if it's nothing (exclusion). One more click. Who cares?
I think hard coded filter conditions by name ('plugin', 'library') are inflexible.

**Comment by nueckman** [comment]
IMO just commit the patch and open a new PR for conditional fields in the frontend (the whole js-thing).

**Comment by Kubik-Rubik** [comment]
IMO this is a bug and should be fixed. Thank you @Erftralle! Merged.

**Pull request closed without merging**
