### PR TITLE
[4.0] Some SCSS files not shipped

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/31091, at least in some part.

### Summary of Changes

Moves some SCSS files back to media folder so all SCSS files are shipped and CSS can be compiled in production environment.

### Testing Instructions

Testing BEFORE result requires a built package like nightly or beta. For testing AFTER result download the package from the link below this comment.

Download scssphp from https://github.com/scssphp/scssphp (bad idea, I know, but it's fine for testing purposes).
Use scssphp to compile some file, e.g. `templates/cassiopeia/scss/template.scss`.

### Actual result BEFORE applying this Pull Request

CSS compilation fails because of missing files:

>../../../build/media_source/system/scss/icomoon` file not found for @import: ../templates/cassiopeia/scss/template.scss on line 21, at column 1

### Expected result AFTER applying this Pull Request

CSS file compiled.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Please DON'T reintroduce the media folder in the repo, there's another way to move the scss files to media (in the init module)

**Comment by SharkyKZ** [comment]
I wanted to avoid having duplicate files in the working directory. This makes things complicated because assets needs to be copied after affected SCSS files are modified (because other SCSS files reference files from `media` directory). But OK.

**Comment by dgrammatiko** [comment]
> This makes things complicated because assets needs to be copied after affected SCSS files are modified (because other SCSS files reference files from media directory)

I'll have to update the code for the tooling anyhow, but good to know what the requirements (for scss) are...

**Comment by dgrammatiko** [comment]
@SharkyKZ please undo the changes in the build tools modules. I 've updated them in https://github.com/joomla/joomla-cms/pull/31221 to always ship and update as necessary the scss files per compilation

**Pull request closed without merging**
