### PR TITLE
[4.0] Fix invalid argument for foreach

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix `Invalid argument supplied for foreach() in \libraries\src\Form\FormField.php on line 1134` by checking that it is an array.

### Testing Instructions
* Create a text field.
* Create a subfield field.
* Edit an article (leave subfield field empty).
* Save the article.
* Check PHP error log.
* Apply PR.
* Check PHP error log for no errors.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Looks like `$value` is normally an object, not an array.

**Comment by Fedik** [comment]
It may be both, object or array
~maybe try `!is_scalar($value)`~
for subform it may enough to check the value exists:
`if ($this->multiple && $value)`

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 2603787dd2f5d75ea5d412fa1f72ffda2741acbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27556">issues.joomla.org/tracker/joomla-cms/27556</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2603787dd2f5d75ea5d412fa1f72ffda2741acbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27556">issues.joomla.org/tracker/joomla-cms/27556</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27556">issues.joomla.org/tracker/joomla-cms/27556</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
