### PR TITLE
[com_finder] Improve disabled smart search content plugin message

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to improve the disabled Smart Search Content plugin in com_finder.

Before (the link is to the plugin list with harcoded text search)
image

After (the link is now to edit the Smart Search Content plugin)
image
#### Testing Instructions

Code review, or:
1. Use latest staging
2. Disable Smart Search Content plugin
3. Go to Components -> Smart Search and check the warning message. Click the link, you'll be redirected to the plugin manager list view with a search.
4. Apply patch
5. Go to Components -> Smart Search and check the warning message. Click the link, you'll be redirected to directly edit the smart search content plugin.

### CODE REVIEW

**Comment by brianteeman** [comment]
I would prefer it if the new string ended with
.... unless it is enabled.

On 5 June 2016 at 22:25, andrepereiradasilva <notifications@github.com>
wrote:

> Summary of Changes
>
> Simple PR to improve the disabled Smart Search Content plugin in
> com_finder.
>
> Before (the link is to the plugin list with harcoded text search)
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15808299/50ea2426-2b6c-11e6-8f89-a19ae48a71cc.png>
>
> After (the link is now to edit the Smart Search Content plugin)
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15808296/34c4e542-2b6c-11e6-8960-63c99c60fdaf.png>
> Testing Instructions
>
> Code review, or:
> 1. Use latest staging
> 2. Disable Smart Search Content plugin
> 3. Go to Components -> Smart Search and check the warning message. Click
> the link, you'll be redirected to the plugin manager list view with a
> search.
> 4. Apply patch
> 5. Go to Components -> Smart Search and check the warning message. Click
> the link, you'll be redirected to directly edit the smart search content
> plugin.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/10737
> Commit Summary
>
>    - do not hardcode link in warning message
>    - cs
>
> File Changes
>
>    - *M* administrator/components/com_finder/helpers/finder.php
>    <https://github.com/joomla/joomla-cms/pull/10737/files#diff-0> (29)
>    - *M* administrator/components/com_finder/views/index/view.html.php
>    <https://github.com/joomla/joomla-cms/pull/10737/files#diff-1> (3)
>    - *M* administrator/language/en-GB/en-GB.com_finder.ini
>    <https://github.com/joomla/joomla-cms/pull/10737/files#diff-2> (3)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/10737.patch
>    - https://github.com/joomla/joomla-cms/pull/10737.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10737>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8UdxaSX05hZvkchNB3YNmWdIWOy2ks5qIz7CgaJpZM4Iuc2v>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
done

**Comment by brianteeman** [comment]
Thanks

On 5 June 2016 at 23:05, andrepereiradasilva <notifications@github.com>
wrote:

> done
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10737#issuecomment-223840724>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8XQO2-hLtOg3h2fUudmv4In05ni2ks5qI0hBgaJpZM4Iuc2v>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Sorry - just spotted that the description of the plugin is "Changes to content will not update the Smart Search index if you do not enable this plugin." So it would be better if you used that text for the second sentence<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10737">issues.joomla.org/joomla-cms/10737</a>.</sub>

**Comment by andrepereiradasilva** [comment]
done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c066ecccda6ae929e8596b3935f2acd879131c22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10737">issues.joomla.org/joomla-cms/10737</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on c066ecccda6ae929e8596b3935f2acd879131c22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10737">issues.joomla.org/joomla-cms/10737</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10737">issues.joomla.org/joomla-cms/10737</a>.</sub>

**Comment by wojsmol** [comment]
@joomla-cms-bot Please remove RTC label as this PR is merged :smile:

**Pull request merged**
