### PR TITLE
[4.2] php cs

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

fix indentation

### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 375e4c28406adbfc035f6887302fd45ff5f852c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38735">issues.joomla.org/tracker/joomla-cms/38735</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 375e4c28406adbfc035f6887302fd45ff5f852c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38735">issues.joomla.org/tracker/joomla-cms/38735</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38735">issues.joomla.org/tracker/joomla-cms/38735</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
