### PR TITLE
clarification of the return value for the user ID

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

~~To make it clear what the returned number is. It is the user ID. There was some confusion about this in the German language files, and some site operators asked for the unit and thought it was days.~~

With this change, the username is returned as suggested and the super user is notified.

### Testing Instructions

.

### Expected result

.

### Actual result

.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 00955a9a785ad970bbbaf4dcd432ba59fb6b103c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27374">issues.joomla.org/tracker/joomla-cms/27374</a>.</sub>

**Comment by brianteeman** [comment]
Would it not be better to keep the language string the same and to change the id to username
https://github.com/joomla/joomla-cms/blob/8f40198c02ed2016a1f0f1f39eefec45e74bd20f/plugins/system/privacyconsent/privacyconsent.php#L703

**Comment by tecpromotion** [comment]
> Would it not be better to keep the language string the same and to change the id to username

I've been thinking about that, too. Especially because we (almost) always use the user name in the action logs.

**Comment by richard67** [comment]
> > Would it not be better to keep the language string the same and to change the id to username
> 
> I've been thinking about that, too. Especially because we (almost) always use the user name in the action logs.

Agree.

**Comment by zero-24** [comment]
```php
			$messageModel->notifySuperUsers(
				JText::_('PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_SUBJECT'),
				JText::sprintf(
					'PLG_SYSTEM_PRIVACYCONSENT_NOTIFICATION_USER_PRIVACY_EXPIRED_MESSAGE',
					JFactory::getUser($user->user_id)->username
				)
			);
```
https://github.com/joomla/joomla-cms/blob/staging/plugins/system/privacyconsent/privacyconsent.php#L701-L704

This should do the trick. cc @tecpromotion

**Comment by tecpromotion** [comment]
@brianteeman I have withdrawn the adjustment of the language string and as suggested committed the username as return value. Many thanks to @zero-24 and @richard67

**Review by richard67 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 65407b68238356f472958f07de60ec4da606fcba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27374">issues.joomla.org/tracker/joomla-cms/27374</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 65407b68238356f472958f07de60ec4da606fcba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27374">issues.joomla.org/tracker/joomla-cms/27374</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27374">issues.joomla.org/tracker/joomla-cms/27374</a>.</sub>

**Comment by zero-24** [comment]
Merging + cc for @imanickam @infograf768 to check whether this can / should / need to be communicated to the TT's

Thanks @tecpromotion

**Pull request merged**
