### PR TITLE
[6.0] Upmerges - 2024-10-09

### PR DESCRIPTION
**Pull request by Bodge-IT**
Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Bodge-IT** [comment]
This upmerge is wrong.  Has been squashed.

**Comment by Bodge-IT** [comment]
OK, my next steps would be close this PR and undo my last upmerge commit.

**Comment by richard67** [comment]
> OK, my next steps would be close this PR and undo my last upmerge commit.

Better close this PR, delete your branch "upmerges/2024-10-09" locally, and if in your repo on GitHub also there, then create the branch again based on the current 6.0-dev branch and start with that.

**Comment by Bodge-IT** [comment]
Closing as suggested

**Pull request closed without merging**
