### PR TITLE
[4.3] Deprecate Joomla\CMS\Schema\ChangeItem\SqlsrvChangeItem for 5.0

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for https://github.com/joomla/joomla-cms/pull/38405#pullrequestreview-1066493530 .

### Summary of Changes

Deprecate the SqlsrvChangeItem class which was used by the database checker in Joomla 3 for checking the schema on MS SQL Server databases and which will be removed in Joomla 5 with PR #38405 .

### Testing Instructions

Code review.

### Actual result BEFORE applying this Pull Request

The SqlsrvChangeItem class which is already useless in J4 is not marked as deprecated.

### Expected result AFTER applying this Pull Request

The SqlsrvChangeItem class which is already useless in J4 is marked as deprecated.

### Documentation Changes Required

None. It is already documented that Joomla 4 does not support running with a MS SQL Server database.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on deae51d11b8a2b778cd652dadc12fa3745d549bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38428">issues.joomla.org/tracker/joomla-cms/38428</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38428">issues.joomla.org/tracker/joomla-cms/38428</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
