### PR TITLE
Rewrite fields description in English

### PR DESCRIPTION
**Pull request by brianteeman**
the description of the fields plugins that was merged in 13750 is not correct english

this PR rewrites them into correct English

This doesnt affect translations as presumably they wrote their translations correctly

### CODE REVIEW

**Comment by infograf768** [comment]
If you want to change, OK, BUT please normalise to use lowercase for the `'calendar'` as this does NOT depend on English Grammar: it is the Type of the field in code.
Therefore, should be:
`PLG_FIELDS_CALENDAR_XML_DESCRIPTION="This plugin lets you create new fields of type 'calendar' in any extensions where custom fields are supported."`

This is what we have done for all PLG_FIELDS_

**Comment by infograf768** [comment]
Example in French, we do not translate `'calendar'`:
`PLG_FIELDS_CALENDAR_XML_DESCRIPTION="Ce plugin permet de créer de nouveaux champs de type 'calendar' dans les extensions où les champs personnalisés sont implémentés."`

**Comment by RonakParmar** [comment]
Found "No newline at end of file" in below file:
- administrator/language/en-GB/en-GB.plg_fields_color.ini 
- administrator/language/en-GB/en-GB.plg_fields_color.sys.ini <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14447">issues.joomla.org/tracker/joomla-cms/14447</a>.</sub>

**Comment by brianteeman** [comment]
@infograf768 updated to use lowercase for calendar even though it was beyond the scope of this PR as it was originally committed incorrectly - I guess you didn't spot it before ;)

@RonakParmar done

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 480296b903f4c61a06b52323736c7ca6aa85a7a0<br /><br />Done code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14447">issues.joomla.org/tracker/joomla-cms/14447</a>.</sub>

**Comment by infograf768** [comment]
> I guess you didn't spot it before

It was indeed modified in a more recent committed PR and yep, I did not spot that one.

It was modified here:
https://github.com/joomla/joomla-cms/pull/13638

while it was correct here:
https://github.com/joomla/joomla-cms/pull/13710

**Comment by wilsonge** [comment]
I'm good with this too so merged :)

**Pull request merged**
