### PR TITLE
[4.0] Fix nested items reorder

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #34855.

### Summary of Changes
This PR fixes re-order nested items (categories/menu items) as described in https://github.com/joomla/joomla-cms/issues/34855. I did two things here:

- Move the code to save order back to `drop` instead of `dragend`. I haven't had time to check to see why it is not working for `dragend` but we always use `drop` before and it works, so it makes sense to make the change
- Remove the code to initialize data-order for each item and reset it on dragend. We do not use data-order in our script at the moment, so no need to set data for it.

### Testing Instructions
1. Confirm the issue https://github.com/joomla/joomla-cms/issues/34855
2. Update your site to update package for this PR
3. Try to change ordering of categories and make sure it is working as expected. It would be good if you can test change ordering of menu items, modules, articles and make sure it is still working, too.

### CODE REVIEW

**Comment by richard67** [comment]
SCSS code style errors in Drone are not related to this PR but to the 4.0-dev branch currently have such an error.

@joomdonation But the javascript code style error in Drone is related to this PR, see https://ci.joomla.org/joomla/joomla-cms/45993/1/21 :

```
/********/src/build/media_source/system/js/draggable.es6.js
11:5  error  'dropElement' is defined but never used         no-unused-vars
13:7  error  'orderRows' is assigned a value but never used  no-unused-vars

2 problems (2 errors, 0 warnings)
```

**Comment by joomdonation** [comment]
Thanks @richard67. Should be fixed now.

**Comment by richard67** [comment]
@joomdonation The scss code style error has just been fixed in the 4.0-dev branch, so if you update the branch your PR it will be ok here, too.

**Comment by richard67** [comment]
Setting release blocker label as inherited from the issue.

**Comment by ChristineWk** [comment]
Prebuilt Package.

OK: categories and menues

articles and modules inactive icon:screen shot 2021-07-22 at 09 48 09
Therefore: Not sure about<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Comment by joomdonation** [comment]
@ChristineWk Thanks for testing. You need to click on the order icon to have items ordered by ordering before you can change order. See this attached screenshot
Articles-Joomla-4-RC5-Administration

**Comment by ChristineWk** [comment]
@joomdonation 

Thank you - I saw it minutes before and it's OK now :-)Because the 1st column belongs to "actions".

So: categories, menues and articles = successful.
modules: No. Can't reorder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Comment by joomdonation** [comment]
@ChristineWk Note that you can only change order of modules from same position. So if the two modules are from different positions , you cannot change ordering

Same with articles from different categories

**Comment by ChristineWk** [comment]
@joomdonation 

Ahhhhh, of course: Same positions, sounds logical now. I hadn't noticed. And it works :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b239457401dc7463b844c6e5493f524365e3b3e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b239457401dc7463b844c6e5493f524365e3b3e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34864">issues.joomla.org/tracker/joomla-cms/34864</a>.</sub>

**Pull request merged**
