### PR TITLE
[4.0] Fix two factor error on profile page

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #31890 .

### Summary of Changes
Fixes JS notice on the profile page when totp plugin is enabled.

### Testing Instructions
Enable the totp two factor plugin. Navigate to the profile page (not the edit area). Before page JS notice. After patch no notice.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f38eb748ca932b5fca435d38dbc5cc1848297f52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31907">issues.joomla.org/tracker/joomla-cms/31907</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f38eb748ca932b5fca435d38dbc5cc1848297f52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31907">issues.joomla.org/tracker/joomla-cms/31907</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31907">issues.joomla.org/tracker/joomla-cms/31907</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
