### PR TITLE
[5.2] typo urlrule

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to fix a comment typo. Spotted while reviewing code for a new feature.

Code review

cc @rdeutz

third time lucky?

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 284784efa76431512c1c340f5ff0d5e6297daf99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44235">issues.joomla.org/tracker/joomla-cms/44235</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 284784efa76431512c1c340f5ff0d5e6297daf99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44235">issues.joomla.org/tracker/joomla-cms/44235</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44235">issues.joomla.org/tracker/joomla-cms/44235</a>.</sub>

**Comment by rdeutz** [comment]
Thanks, sorry for the trouble

**Comment by brianteeman** [comment]
got there in the end

**Pull request merged**
