### PR TITLE
[com_fields] Escape checkboxes/radio option's text

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Option's value is escaped, but not the option's text which it should be.

### Testing Instructions
Create checkboxes and radio custom fields with `A&B` for the text/value.
Edit an article.
View page source.
Find `A&B`.

### Expected result
`A&amp;B`

### Actual result
`A&B`

### CODE REVIEW

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on 9b0c82dadc0a9f07e254e6403a4607155a85f85f<br /><br />The options value and text are both correctly escaped as you can see:
deepinscreenshot20170424225013

deepinscreenshot20170424225027
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15492">issues.joomla.org/tracker/joomla-cms/15492</a>.</sub>

**Comment by rjcf18** [comment]
Forgot to mention that while doing the fresh installation for this PR this happened, but I'm guessing it is unrelated to this PR:
deepinscreenshot20170424200600
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15492">issues.joomla.org/tracker/joomla-cms/15492</a>.</sub>

**Comment by Quy** [comment]
Good catch! Unfortunately, it is related to this pr. I will check it out.

**Comment by rjcf18** [comment]
Aaah ok nice, then good thing I spotted it :)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 9b0c82dadc0a9f07e254e6403a4607155a85f85f<br /><br />With and -out PR got `A&amp;B` in Pagesource.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15492">issues.joomla.org/tracker/joomla-cms/15492</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by Quy** [comment]
Please remove RTC for now as it affects the installation as discovered above which needs to be fixed. Thanks.

**Comment by franz-wohlkoenig** [comment]
Set back on pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15492">issues.joomla.org/tracker/joomla-cms/15492</a>.</sub>

**Comment by brianteeman** [comment]
@quy gentle reminder this needs updating<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15492">issues.joomla.org/tracker/joomla-cms/15492</a>.</sub>

**Comment by brianteeman** [comment]
@quy is this going to be updated or shall it be closed?

**Comment by Quy** [comment]
I will close it for now.

**Pull request closed without merging**
