### PR TITLE
[4.0] correcting com_content choose layout field class

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Adding class `custom-select` to all com_content fileds of type `componentlayout`

### Testing Instructions
Check all places where Change Layout or Layout is proposed in com_content stuff
Global com_content Options
Article edit options

Menu items:
List all categories
Category blog
category list
### Before patch
screen shot 2018-08-26 at 08 21 25

### After patch
screen shot 2018-08-26 at 08 24 04

NOTE: Looks like there are some issues here with `uitab` when editing a menu item (firefox but also Safari f). Therefore it may be difficult to get to the tab where the field concerned is displayed.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ea02d467dcedb0b81a9e7a86f45c17c2ede13936<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21850">issues.joomla.org/tracker/joomla-cms/21850</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on ea02d467dcedb0b81a9e7a86f45c17c2ede13936<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21850">issues.joomla.org/tracker/joomla-cms/21850</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
@infograf768 do you plan to change also in com_modules?

screen shot 2018-08-26 at 14 27 33


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21850">issues.joomla.org/tracker/joomla-cms/21850</a>.</sub>

**Comment by wilsonge** [comment]
We should fix the modules as well. PRs welcome!

**Comment by infograf768** [comment]
3 each for
contact
tags 
newsfeed 

plus: modules site and admin = 40 of them...

**Comment by infograf768** [comment]
plus category.xml

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/21862

**Pull request merged**
