### PR TITLE
Fix list select (with choicesjs) losing values in subform

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/41791 .

### Summary of Changes

Fix list select (with choicesjs) losing values in subform

### Testing Instructions

Run `npm install`
Please follow https://github.com/joomla/joomla-cms/issues/41791
Or create a subfrom with fancy-select:
```xml
<field type="subform" name="subform" label="subform" multiple="true">
  <form>
    <field type="list" name="list" label="list" layout="joomla.form.field.list-fancy-select">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
    </field>
  </form>
</field>
```
Select some values and change order of subform rows

### Actual result BEFORE applying this Pull Request
Values are resets

### Expected result AFTER applying this Pull Request
Values stays as selected

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by AndySDH** [comment]
I have tested this item :white_check_mark: successfully on e28bb6a8d7d673476c8cebc8b0386d4c4ada909f<br /><br />Thank you, the fix works :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42332">issues.joomla.org/tracker/joomla-cms/42332</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e28bb6a8d7d673476c8cebc8b0386d4c4ada909f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42332">issues.joomla.org/tracker/joomla-cms/42332</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42332">issues.joomla.org/tracker/joomla-cms/42332</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
