### PR TITLE
[com_fields] MSSQL - sql for Custom fields

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #12624  .

### Summary of Changes

- MSSQL - update sql for Custom fields (#11833)
- MSSQL - install sql for Custom fields (#11833)
- MSSQL - update sql for Custom fields (#13091)
- MSSQL - install sql for Custom fields (#13091)
- MSSQL - update sql for Custom fields (#13115)
- MSSQL - install sql for Custom fields (#13115)
- MSSQL - update sql for Custom fields (#13175)
- MSSQL - install sql for Custom fields (#13175)
- MSSQL - update sql for Custom fields (#13246)
- MSSQL - install sql for Custom fields (#13246)

### CODE REVIEW

**Comment by zero-24** [comment]
@alikon this jjust includes the update part is that correct / expected?

Also this is all in one line? is this expected too?

**Comment by alikon** [comment]
No, I'm having big connection issues, hope to solve soon i'll put install
file too, sorry...

**Comment by zero-24** [comment]
no problem. Thanks!

**Comment by andrepereiradasilva** [comment]
@alikon can you please add line endings

**Comment by alikon** [comment]
@andrepereiradasilva I'll complete this pr when I regain a stable
connection ;)

**Comment by alikon** [comment]
can someone do a review or a test on MSSQL (cause i don't have a mssql environment available)

**Comment by laoneo** [comment]
Had a discussion with @matrikular about the MSSQL scripts. Perhaps he can test it as well.

**Comment by alikon** [comment]
updated  for #13091

**Comment by laoneo** [comment]
Can you add the "[com_fields]" to the beginning of the title? People start asking about open pull requests and I'm telling them that they have to search for com_fields. Thanks.

**Comment by Bakual** [comment]
Adjusted the title

**Comment by alikon** [comment]
updated for #13115

**Comment by waader** [comment]
There is a missing comma at the end of this line
     [language] [nvarchar](7) NOT NULL DEFAULT ''
in both files.

With this change installation and update went fine.

I also applied #13115 but when creating a new fields group I get this sql error:

Microsoft][SQL Server Native Client 11.0][SQL Server]No column name was specified for column 1 of 'A'. SQL=SELECT * FROM ( SELECT count(id) , ROW_NUMBER() OVER (ORDER BY (select 0)) AS RowNumber FROM #__usergroups) A WHERE A.RowNumber BETWEEN 1 AND 1 

But this is something for another patch, right?

**Comment by laoneo** [comment]
@waader thank you very much for testing. @alikon can you update the code please?

**Comment by alikon** [comment]
thanks @waader for testing, and yes please open a new issue for that

**Comment by waader** [comment]
Installation works now but at Extensions > Manage > Database you will find:

    Table 'tf7qr_fields( id' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'tf7qr_fields_groups( id' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'tf7qr_fields_values( field_id' does not exist. (From file 3.7.0-2016-08-29.sql.)

When updating an older joomla version you will find the same messages but also an error that indicates that com_fields could not be loaded.

A Click on Discover shows this error:
515 [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla35.dbo.#__extensions'; column does not allow nulls. INSERT fails. SQL=INSERT INTO [#__extensions] ([name],[type],[element],[folder],[client_id],[access],[manifest_cache],[params],[state]) VALUES ('com_fields','component','com_fields','','1','1','{"name":"com_fields","type":"component","creationDate":"March 2016","author":"Joomla! Project","copyright":"(C) 2005 - 2016 Open Source Matters. All rights reserved.","authorEmail":"admin@joomla.org","authorUrl":"www.joomla.org","version":"__DEPLOY_VERSION__","description":"COM_FIELDS_XML_DESCRIPTION","group":"","filename":"fields"}','{}','-1')

**Comment by alikon** [comment]
I suspect that this is unrelated from com_fields, can you can confirm discovering another extension

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on db9cce56a1a76dfbec31e2572aaa95c23869b673<br /><br />@alikon: you are right. Has nothing to do with your patch. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12660">issues.joomla.org/tracker/joomla-cms/12660</a>.</sub>

**Comment by laoneo** [comment]
I guess this one here can be merged as it is unlikely we will find another person who is testing it on MSSQL.

**Comment by mbabker** [comment]
Actually, if you spin up Ubuntu 16.04 you can run SQL Server from there now.  https://www.microsoft.com/en-us/sql-server/developer-get-started/php-ubuntu

Same with Red Hat - https://www.microsoft.com/en-us/sql-server/developer-get-started/php-rhel

**Comment by Bakual** [comment]
If I find someone to move my Crowdin scripts from my private server to Joomla property, I would be happy to spin up a new server and try that out :)

**Comment by alikon** [comment]
updated for #13175

**Comment by laoneo** [comment]
@alikon you are fast. Just wanted to write a notice, that the structure of com_fields changed again and saw that you did it already :smile: . Good work.

**Comment by alikon** [comment]
updated for #13246

**Comment by csthomas** [comment]
I have tested it on backend and it is OK.

Why there is a few difference between sql install and update file?

joomla_sql_diff

**Comment by zero-24** [comment]
The install and update file need to be equal as we need everything (tables etc.) also on sites that got updated to 3.7.0 :)

**Comment by alikon** [comment]
fixed the missed default

**Comment by csthomas** [comment]
After I patched by Patch Tester a see (it is incorrect - table name should not contain  column name):

    Table 'j37_fields( id' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'j37_fields_categories(  field_id' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'j37_fields_groups( id' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'j37_fields_values( field_id' does not exist. (From file 3.7.0-2016-08-29.sql.)

After I click FIX the tables are created and fields work OK.

But I still see above warnings.

Please add white space before '(':
```sql
CREATE TABLE [#__fields](
```

replace to:
```sql
CREATE TABLE [#__fields] (
```

and for others do the same. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12660">issues.joomla.org/tracker/joomla-cms/12660</a>.</sub>

**Comment by alikon** [comment]
@csthomas added the space, but all other existing `CREATE TABLE` don't have that space
anyway thanks for testing

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 6fad1a277653d22ab841bd27389ea0067d106251<br /><br />Because of some regex in database fix in component installer "CREATE TABLE" requires space.
It is only needed in update sql files:)

Success.

    Database schema version (in #__schemas): 3.7.0-2016-11-24.
    Update version (in #__extensions): 3.7.0-alpha2.
    Database driver: sqlsrv.
    12 database changes were checked successfully.
    225 database changes did not alter table structure and were skipped.


Because the last two commits add only white spaces and " DEFAULT ''" which exists in the install sql file 
IMO it can be merged without additional test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12660">issues.joomla.org/tracker/joomla-cms/12660</a>.</sub>

**Comment by alikon** [comment]
> Because of some regex in database fix in component installer "CREATE TABLE" requires space.
It is only needed in update sql files

we need to remeber this when we will update some others on MSSQL

**Comment by laoneo** [comment]
Can a maintainer set this to RTC as we have a successful test on MSSQL.

**Comment by laoneo** [comment]
There will be some more work then when pr #13319 got merged. But let's get this one in first.

**Comment by infograf768** [comment]
We have only one test as https://github.com/joomla/joomla-cms/pull/12660#issuecomment-266682769 was done before changes

**Comment by laoneo** [comment]
Honestly I'm not sure if we will find two testers for this.

**Comment by waader** [comment]
I will test this one later today.

**Comment by alikon** [comment]
thanks @waader

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 6fad1a277653d22ab841bd27389ea0067d106251<br /><br />I tested the backend with content, users and contacts and it works. Frontend is currently broken which has nothing to do with this patch. With a rudimentary fix I could get it working also in frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12660">issues.joomla.org/tracker/joomla-cms/12660</a>.</sub>

**Comment by csthomas** [comment]
You can try to test front end with applied https://github.com/joomla/joomla-cms/pull/13262

**Comment by waader** [comment]
I also did that, but it didn´t work.

**Comment by laoneo** [comment]
Thanks for all the work guys!! Ready for RTC.

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12660">issues.joomla.org/tracker/joomla-cms/12660</a>.</sub>

**Pull request merged**
