### PR TITLE
[4.2] MFA backup codes list view

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #38207 .

### Summary of Changes

Don't show empty alert box

### Testing Instructions

- create a new user
- register at least one MFA method for the new user
- edit user in administrator

### Actual result BEFORE applying this Pull Request

Empty alert box
image

### Expected result AFTER applying this Pull Request

No empty alert box
image

### Documentation Changes Required

No

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on c15ec8855d9e8d94aa81fac5149e32d52220fbf1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38319">issues.joomla.org/tracker/joomla-cms/38319</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c15ec8855d9e8d94aa81fac5149e32d52220fbf1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38319">issues.joomla.org/tracker/joomla-cms/38319</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38319">issues.joomla.org/tracker/joomla-cms/38319</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
