### PR TITLE
PlgSystemUpdatenotification::getSuperUsers - replace query with API call

### PR DESCRIPTION
**Pull request by klas**
PlgSystemUpdatenotification::getSuperUsers is doing direct database queries to find groups with superuser permissions. We have existing API that should be used for this  (to avoid code duplication and maintainance problems).

To test check behaviour of notification plugin before and after the patch, it should stay the same.

### CODE REVIEW

**Comment by brianteeman** [comment]
NOTE: The travis errors are unrelated to this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8684">issues.joomla.org/joomla-cms/8684</a>.</sub>

**Comment by Bakual** [comment]
@klas Can you update your PR with current staging. The codestyle issues which went in with the 3.4.6 release are now fixed.

**Comment by klas** [comment]
@Bakual Done

**Comment by conconnl** [comment]
@klas, how can I test this exactly.
Then I can ask PBF visitors to test this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8684">issues.joomla.org/joomla-cms/8684</a>.</sub>

**Comment by klas** [comment]
@conconnl getSuperUsers fuction behaviour should stay the same, what specifically you can test is that the same set of superusers gets email notification about update than before patch (emails are sent either to superusers with emails matching those from the list or all superusers, if no emails have been set in the plugin)

**Comment by conconnl** [comment]
@klas I have tried to test it but can't seem to trigger the update mails.
I manually changed the version numbers in the files, but the update mechanism in Joomla can't find a update even when I use 3.4.0 as number.

I you know which changes are needed to trigger it, then I would gladly test it again.

**Comment by faynt0** [comment]
I have tested this item :white_check_mark: successfully on 91d4e47b1e2930a3cdb21617f2da661851bdae81<br /><br />First I tried to trigger the update notification by manually change the version string.
This step worked worked and the backend popup to update. But it didn't send an email to the superuser (pre-patch).
So I vardumpped the codenotification.php return values that are affected by the patch and compared them with the return values of the patched code.
Pre- and postpatch returned the same values.

  
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8684">issues.joomla.org/joomla-cms/8684</a>.</sub>

**Comment by wmchris** [comment]
I have tested this item :white_check_mark: successfully on 91d4e47b1e2930a3cdb21617f2da661851bdae81<br /><br />changed the version in database and cleared cache. dumped the return information from ./plugins/system/updatenotification/updatenotification.php

both looked the same.  @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8684">issues.joomla.org/joomla-cms/8684</a>.</sub>

**Comment by roland-d** [comment]
RTC as we have 2 successful tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8684">issues.joomla.org/joomla-cms/8684</a>.</sub>

**Comment by klas** [comment]
Thank you all for testing

**Pull request merged**
