### PR TITLE
[4.2] Column Width

### PR DESCRIPTION
**Pull request by brianteeman**
Changes the css classes for the dropdown column selector to remove text wrapping which is especially a problem in German but can also be seen in english in the category list view

Pull Request for Issue #38503 .

### Testing Instructions
Either npm run build:js or install a prebuilt package

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by sba** [comment]
looks good to me. thanks @brianteeman !

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on e5421a94271c670ae0f9ad6b60079ece1bd0216f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38507">issues.joomla.org/tracker/joomla-cms/38507</a>.</sub>

**Comment by sandewt** [comment]
Result test:

screen shot 2022-08-18 at 07 49 26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38507">issues.joomla.org/tracker/joomla-cms/38507</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e5421a94271c670ae0f9ad6b60079ece1bd0216f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38507">issues.joomla.org/tracker/joomla-cms/38507</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38507">issues.joomla.org/tracker/joomla-cms/38507</a>.</sub>

**Comment by brianteeman** [comment]
Bottom margin removed as requested

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 30a9c9d60301ba951f377f71318931c1fad01b36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38507">issues.joomla.org/tracker/joomla-cms/38507</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
