### PR TITLE
Update names of Article and Tag modules

### PR DESCRIPTION
**Pull request by brianteeman**
The en-GB user-interface-text WG discussed and agreed it would be better and more consistent if we renamed the article and tag modules as below and this will mean that they are all grouped together in the list of available modules
- Tags - Popular
- Tags - Similar
- Articles - Archived
- Articles - Newsflash
- Articles - Related
- Articles - Categories
- Articles - Category
- Articles - Latest
- Articles - Most Read

### CODE REVIEW

**Comment by zero-24** [comment]
@brianteeman as it is save by the en-GB native speakers is here any test / review required? If not i think we can move it to RTC :smile:

**Comment by brianteeman** [comment]
It still needs testing to make sure the PR does what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5725">issues.joomla.org/joomla-cms/5725</a>.</sub>

**Comment by zero-24** [comment]
ok thanks @brianteeman 

just noticed do you think we should update also the SQL files like here:
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L341

**Comment by waader** [comment]
@test success!

I would test any update for postgresql and mssql sample data.

**Comment by brianteeman** [comment]
I dont see any value in updating the data in the sample testing sql - its just the title of an instance of a module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5725">issues.joomla.org/joomla-cms/5725</a>.</sub>

**Comment by zero-24** [comment]
ok thanks @brianteeman

**Comment by zero-24** [comment]
@test successful moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5725">issues.joomla.org/joomla-cms/5725</a>.</sub>

**Pull request merged**
