### PR TITLE
Fix wrong CSS Class on Tags edit view title

### PR DESCRIPTION
**Pull request by zero-24**
### How to reproduce

Go to: BE --> Components --> Tags --> "edit on tag" --> analyse (e.g. with Firebug or Inspector) the title.
### Actual result

edit_edit_old
### After the patch and correct result

edit_edit_new

### CODE REVIEW

**Comment by n9iels** [comment]
@test works fine for me!

Just remove that white space at the end of line 89 and Travis will be happy to :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7759">issues.joomla.org/joomla-cms/7759</a>.</sub>

**Comment by zero-24** [comment]
>Just remove that white space at the end of line 89 and Travis will be happy to :smiley:

Thanks just fixed.

**Comment by watchfulli-dev** [comment]
@test successful, works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7759">issues.joomla.org/joomla-cms/7759</a>.</sub>

**Comment by zero-24** [comment]
RTC after fixing the merge conflicts. Thanks to the testers!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7759">issues.joomla.org/joomla-cms/7759</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @zero-24! Merged.

**Pull request merged**
