### PR TITLE
remove console.log debug call from javascript

### PR DESCRIPTION
**Pull request by PhilETaylor**
remove console.log debug call from javascript when extracting a Joomla update

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 91845ba3e6ea8ad28fffae2343cdf73350b53b25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23698">issues.joomla.org/tracker/joomla-cms/23698</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 91845ba3e6ea8ad28fffae2343cdf73350b53b25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23698">issues.joomla.org/tracker/joomla-cms/23698</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23698">issues.joomla.org/tracker/joomla-cms/23698</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
