### PR TITLE
[4.3] Fix Media Field with Windows directory separator in value

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #39203.

### Summary of Changes
Sometime, on a window system, value stored for a media form field has this format `images\headers\banner.jpg` and it will throw warning and there will be notice like below when you edit the record contains that field:

`Notice: Undefined offset: 0 in ...\libraries\src\Form\Field\MediaField.php on line 294`

This PR just fixes that notice.

### Testing Instructions
If you want to fully re-procedure the issue, you need to have Joomla setup on windows and follow instructions at https://github.com/joomla/joomla-cms/issues/39203#issuecomment-1312715797 to see the issue. However, there is a simple way to re-procedure it :

1. Add the line of code below after this line https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Form/Field/MediaField.php#L263  . That will fake name of the image file in window directory separator format
```php
$this->value = 'images\headers\banner.jpg';
```

### Actual result BEFORE applying this Pull Request
You see notice like below:

`Notice: Undefined offset: 0 in ...\libraries\src\Form\Field\MediaField.php on line 294`

### Expected result AFTER applying this Pull Request

No notice anymore.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 546b4c4b73c14916ed2cc6595c4015c8d37ba60e<br /><br />Looks good. Tested on Windows 11.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39248">issues.joomla.org/tracker/joomla-cms/39248</a>.</sub>

**Comment by robbiejackson** [comment]
I've tested this and can confirm that it fixes the original [issue 39203](https://github.com/joomla/joomla-cms/issues/39203 "39203") which I raised.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39248">issues.joomla.org/tracker/joomla-cms/39248</a>.</sub>

**Comment by robbiejackson** [comment]
I have tested this item :white_check_mark: successfully on 546b4c4b73c14916ed2cc6595c4015c8d37ba60e<br /><br />Tested using images uploaded from a front-end form and which resulted in the images being given pathnames which were of the Windows format (with backslashes). This included tests for wben the Media Global Config "Path to Images Folder" was set to a Windows-format pathname images\photos, as well as a linux format pathname, and the images uploaded were saved to that folder.

These image files were then treated as media form fields in the admin backend, and the tests confirmed that the fields displayed and were editable ok, both before and after the associated records (with the image pathnames) were saved to the database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39248">issues.joomla.org/tracker/joomla-cms/39248</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39248">issues.joomla.org/tracker/joomla-cms/39248</a>.</sub>

**Comment by laoneo** [comment]
Thank you!

**Pull request merged**
