### PR TITLE
Fix Cancel new Field (Group) issue

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue 14181 .

### Summary of Changes
This PR just fix the issue #14181

### Testing Instructions
1. Install Joomla 4

2. See https://github.com/joomla/joomla-cms/issues/14181 for the issue description, confirm the issue

3. Apply patch, confirm the issue fixed

### Documentation Changes Required

None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 429baa8992cfce14c81416659264096c87e6498c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14182">issues.joomla.org/tracker/joomla-cms/14182</a>.</sub>

**Comment by marncz** [comment]
I have tested this item :white_check_mark: successfully on 429baa8992cfce14c81416659264096c87e6498c<br /><br />Works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14182">issues.joomla.org/tracker/joomla-cms/14182</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC cause 2 successfully Tests?

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14182">issues.joomla.org/tracker/joomla-cms/14182</a>.</sub>

**Pull request merged**
