### PR TITLE
[5.2] Fix of backward compatibility for Login event arguments

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

This is fix for extensions which triggers onUserAfterLogin, onUserAfterLogout, onUserLoginFailure, onUserLogoutFailure events in their code.
Prior Joomla 5 these events had 1 argument, with Joomla 5 they have 2 arguments, to be consisten with onUserLoginEvent and onUserLogiutEvent events.

### Testing Instructions

Add following code, in to index.php of the template:
```
$e1 = new \Joomla\CMS\Event\User\AfterLoginEvent('onFooBar', [['option' => 1]]);
$e2 = new \Joomla\CMS\Event\User\LoginFailureEvent('onFooBar', [['user' => 1]]);
$e3 = new \Joomla\CMS\Event\User\LogoutFailureEvent('onFooBar', [['user' => 1]]);
dd($e1, $e2, $e3);
```

### Actual result BEFORE applying this Pull Request
An error page.

### Expected result AFTER applying this Pull Request
Dump of event objects, on blank page.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 0cfd1205f84a557967e755ab34d134e0a3b663e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43934">issues.joomla.org/tracker/joomla-cms/43934</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0cfd1205f84a557967e755ab34d134e0a3b663e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43934">issues.joomla.org/tracker/joomla-cms/43934</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43934">issues.joomla.org/tracker/joomla-cms/43934</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @Fedik!

**Pull request merged**
