### PR TITLE
[4.3] Fix browser page title for article menu item

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #28468.

### Summary of Changes
Currently, if you create a menu item to link to Article menu item type but does not set browser page title, Joomla uses title of that article for browser page title instead of using Browser Page Title set in the article (if it is set). See https://github.com/joomla/joomla-cms/issues/28468 for details issue description

### Testing Instructions

1. Create an article, look at Options tab and enter certain text for **Browser Page Title** setting of that article
2. Create a menu item to link to that article. Leave Browser Page Title empty in the menu item setup.

### Actual result BEFORE applying this Pull Request
Joomla uses Title of the article for browser page title

### Expected result AFTER applying this Pull Request
Joomla use **Browser Page Title** setup in the article for Browser Page Title.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8b93a907649afe84261233d976f5932a13682cc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39249">issues.joomla.org/tracker/joomla-cms/39249</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39249">issues.joomla.org/tracker/joomla-cms/39249</a>.</sub>

**Review by richard67 — APPROVED** [review]

**Comment by laoneo** [comment]
Thanks!

**Review by hans2103 — COMMENTED** [review]
smart!

**Pull request merged**
