### PR TITLE
Render all exceptions on error page when in debug mode

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

An Exception may have been chained to include additional errors.  If this is the case, the chained errors may help with debugging an issue.  So when in debug mode, I suggest that our error templates display the error data for all Exceptions.
#### Testing Instructions

Enable debug mode.

You'll be testing each core template, in both the site and admin apps, and you'll also want to test the system templates (default error pages), to do that you'll need to temporarily rename the `error.php` file in your active template to something else.  Remember to give it back its original name when finished testing this.

Trigger the error page with a chained Exception (when creating an Exception object, pass the "previous" Exception as the third constructor argument).  The previous Exception(s) should display when in debug mode with their stack trace after the main error is rendered.

### CODE REVIEW

**Comment by ggppdk** [comment]
> Trigger the error page with a chained Exception (when creating an Exception object, pass the "previous" Exception as the third constructor argument). 

Can you make this testing step to be more detailed, e.g. provide an example of file/line to change to trigger such an error, i don't understand it

**Comment by mbabker** [comment]
```php
throw new Exception('Top Exception', 500, new Exception('Nested Exception'));
```

**Comment by yvesh** [comment]
For me it does not output the "Nested Exception" message, but two times the parent one (Top Exception in your example).

screenshot 2016-06-29 21 02 24

P.S.: You should maybe mention turning on joomla debug in the testing instructions and not only in the title.

**Comment by mbabker** [comment]
I left all these comments about using `$this->_error` versus `$this->error` and I still managed to screw that up.  It's fixed now.

**Comment by yvesh** [comment]
Yep working now. Imo it's a nice improvement, there are some valid use cases for nested exceptions 👍

**Comment by ggppdk** [comment]
Yes, it shows both correctly,

not relevant to this topic, i hope something is decided for getFile() getLine() too that will show the line that the exception occured, thanks

**Comment by mbabker** [comment]
No longer RFC, changes made to all core templates, please test.

**Comment by andrepereiradasilva** [comment]
@mbabker the test whent well

But one thing is missing

I tested in admin template so i get a JERROR_LAYOUT_PREVIOUS_ERROR not translated

image

So i think you need to add that language var also to https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.ini

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b9bfda1b80ae5ae9867f6e4b959850c1aac43723<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10964">issues.joomla.org/joomla-cms/10964</a>.</sub>

**Comment by yvesh** [comment]
@mbabker How about moving that output to a helper / library - so much duplicate code? :(

JHtmlError for example

**Comment by mbabker** [comment]
It's appropriate in the template.  Otherwise there will have to be additional public APIs to do the same.  Plus, there should be zero output generated by helper methods, meaning the helper method would have to call JLayout, and now to override markup that was originally created in the template (either directly or through a method called by the template) you have to override a layout file.  This is the cleanest approach.

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on b9bfda1b80ae5ae9867f6e4b959850c1aac43723<br /><br />Thank you for the explanation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10964">issues.joomla.org/joomla-cms/10964</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10964">issues.joomla.org/joomla-cms/10964</a>.</sub>

**Pull request merged**
