### PR TITLE
s/backslahses/backslashes

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/backslahses/backslashes

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 548b3fe599c14ec1a611b9bf4867864ffb3b7a70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31949">issues.joomla.org/tracker/joomla-cms/31949</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31949">issues.joomla.org/tracker/joomla-cms/31949</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31949">issues.joomla.org/tracker/joomla-cms/31949</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for all the PRs @PhilETaylor

**Comment by PhilETaylor** [comment]
No worries. Just surprised that even now there are so many typos to fix :)

**Comment by HLeithner** [comment]
Me too ;)

**Pull request merged**
