### PR TITLE
Toggle Featured

### PR DESCRIPTION
**Pull request by brianteeman**
See discussion #5819 

This changes and simplifies the toggle featured tooltip for com_content and com_contact

It introduces a new global string

The old strings are not removed for B/C

### CODE REVIEW

**Comment by nternetinspired** [comment]
@test success. Great change, thanks Brian.

**Comment by brianteeman** [comment]
Before com_content
screen shot 2015-01-19 at 05 29 32


Before com_contact
screen shot 2015-01-19 at 05 29 56




After com_content
screen shot 2015-01-19 at 05 26 47

After com_contact
screen shot 2015-01-19 at 05 27 26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5823">issues.joomla.org/joomla-cms/5823</a>.</sub>

**Comment by dgt41** [comment]
@test success

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5823">issues.joomla.org/joomla-cms/5823</a>.</sub>

**Pull request merged**
