### PR TITLE
[4.0] Use rel="noopener" for more links

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Use `rel="noopener"` for more links that open in a new window (`target="_blank"`)

### Testing Instructions

Code review

### CODE REVIEW

**Comment by zero-24** [comment]
can you add the noreferrer there too?

**Comment by C-Lodder** [comment]
Why?

`noopener` supports all the browsers that J4 supports

**Comment by zero-24** [comment]
my intention is to add rel = noreferrer noopener ;)

**Comment by zero-24** [comment]
but will merge them as it is some we can later come back and add it. Thanks @C-Lodder

**Pull request merged**
