### PR TITLE
Admin menu dropdown in Joomla! 3.6.0 RC1

### PR DESCRIPTION
**Pull request by cyrez**
Pull Request for Issue #10972.
#### Summary of Changes
- Fix missing pointer in dropdown menu
- Fix sub-menu top placement
#### Testing Instructions
- See issue #10972 for more details

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on daa3d4db9d99fa73d2dfae8488d69962c643faf5<br /><br />All good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by brianteeman** [comment]
@joomlic bad memory I guess I thought the other PR was yours - thanks for fixing it though

@C-Lodder can you confirm

**Comment by JoomliC** [comment]
> @joomlic bad memory I guess I thought the other PR was yours - thanks for fixing it though

This what i thought ;-)
Thanks for test!

**Comment by StefanSTS** [comment]
Tested and works. Applied Commit SHA: daa3d4db9d with patch tester.

**Comment by wojsmol** [comment]
@StefanSTS  please mark as tested https://issues.joomla.org/tracker/joomla-cms/10987 (after login the Test button appears). See https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by StefanSTS** [comment]
I have tested this item :white_check_mark: successfully on daa3d4db9d99fa73d2dfae8488d69962c643faf5<br /><br />Thanks for the links. Works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by brianteeman** [comment]
Setting for 3.6 as it fixes a bug introduced in 3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by infograf768** [comment]
Not sure it should be RTC.
RTL needs more care, before as well as after patch.
Position of sub and arrow.

Before patch

screen shot 2016-07-02 at 08 21 37
After patch


screen shot 2016-07-02 at 08 18 08

**Comment by infograf768** [comment]
Would already be better imho (although the arrow will not display exactly as it should) without
```
.navbar .nav > .dropdown.open:after {
	right: 10px;
}
```
for rtl

**Comment by JoomliC** [comment]
@infograf768 you're right, i should have checked on RTL!
I remove the rtl declaration for pointer.
There are issue in RTL not yet reported, and i thought it was ok in RTL as PR #9375 was already merged (but not sure it was tested on RTL...)

So, the position top and arrow not displayed is fixed now.
But 2 other issues in RTL : placement of pointer & placement of sub-menu.

It seems that <code>template.js</code> is not working to get correctly the offset (as i suspected here https://github.com/joomla/joomla-cms/issues/10972#issuecomment-229997793  there is maybe something wrong in the script...) @C-Lodder any idea ? (as you did the PR, your help is welcomed, as i don't see yet how to fix it, and keep your auto-scrolling feature...)

**Comment by brianteeman** [comment]
Removed rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 8c324bade7dbb1ddd38718056f6d1f333d4420d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by JoomliC** [comment]
@Twincarb not to be tested again yet, as still an issue in RTL that should be fixed ;-)

**Comment by Twincarb** [comment]
I have tested this item :red_circle: unsuccessfully on 8c324bade7dbb1ddd38718056f6d1f333d4420d4<br /><br />Changed my result having read down to the first successful tests then paged down to the bottom with the extra commits missing infografs input.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by JoomliC** [comment]
@infograf768 @Twincarb @brianteeman @StefanSTS i have updated this PR to fix the issue too in RTL language, and to fix the issue with submenu placement in RTL reported by @infograf768 

If you could test again this PR ? (in LTR and RTL language)

Thanks everybody!

Note: @C-Lodder if you have time to look at code, i have redo a bit your script code in template.js, to set the offset of the submenu with no hardcoded value, and changing a bit the way it is handled. Thanks! ;-)

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on d7442a87fabff70a768cfcae473c2dba94f2baa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by infograf768** [comment]
@JoomliC 
I also made a PR with simpler changes to template.js.
https://www.dropbox.com/s/lmbobjg8rj5ly5v/admin_menu.diff?dl=0
```
diff --git a/administrator/templates/isis/js/template.js b/administrator/templates/isis/js/template.js
index 28eb4ff..d465088 100644
--- a/administrator/templates/isis/js/template.js
+++ b/administrator/templates/isis/js/template.js
@@ -75,6 +75,7 @@
 			var dropdown = $self.next('.dropdown-menu');
 			var offset   = $self.offset();
-			var scroll   = $(window).scrollTop() + 5;
+			var scroll   = $(window).scrollTop() + 8;
 			var width    = menuWidth - 13;
+			var rtlwidth = menuWidth + 10;
 
 			// Set the submenu position
@@ -83,5 +84,5 @@
 				emptyMenu.css({
 					top : offset.top - scroll,
-					left: offset.left - width
+					left: offset.left - rtlwidth
 				});
 			}
```
I get exactly the same results as your PR, but... in both cases I have issues here with the **User Menu** and some glitches with the bottom link in each menu with a sub.
Here is a screen recording :
https://www.dropbox.com/s/fhlweqzwmq1s07g/admin_menu_rtl.mp4?dl=0

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on d7442a87fabff70a768cfcae473c2dba94f2baa1<br /><br />Checked in several rtl languages, and also across Chrome, IE, Edge, Firefox. No issues found having cleared the browser cache. Unable to replicate the issues infograf768 found in his video.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by infograf768** [comment]
@JoomliC
Ok, I found the culprit. All depends on the length of the lang string value in mod_menu.ini
If the value is more than a certain number of characters/glyphs, it breaks the way I show in my video.
For Farsi, which was the language I used, 
we have 
`MOD_MENU_COM_USERS_ADD_LEVEL="ایجاد سطح دسترسی جدید"`
 and
`MOD_MENU_COM_USERS_NOTE_CATEGORIES="مجموعه یادداشت کاربر"`

If the value is more than 19 latin characters (or its equivalent in glyphs), in the menu OR the submenu it pushes the submenu by a number of pixels depending on the longest glyph.

**Comment by JoomliC** [comment]
@infograf768 Do you have recorded your video with this PR updated, or with your own changes in template.js ?
As if with your own changes, the issue is normal because of submenu width not a fixed one (that's the reason i add the submenu width to dynamically adjust the offset left. ;-) )

I don't have any issue with Farsi with this PR as it is now. Could you do a test with only this PR applied and no custom changes ?

Note: in the updated PR, to fix RTL, i get dynamically the link width (menu link to open the dropdown) and then get too is padding left (this is currently 10px, so that's the reason for the need of "10", but better to get this padding dynamically than statically ;-) ).
And if you check the left position set in RTL for submenu in my PR, you will see that i get the submenu width dynamically too (this is to fix the issue you have with your custom template.js ;-) ) : 
`					left: offsetLeft - (menuWidth - linkWidth) - submenuWidth`

So, maybe an issue in your re-test of this PR after update ? (As i don't have the issue you have recorded here in Farsi : https://www.dropbox.com/s/fhlweqzwmq1s07g/admin_menu_rtl.mp4?dl=0 but with your custom code for template.js, it is "normal" to have this issue ;-) )

Thanks!
Cyril

**Comment by infograf768** [comment]
My mistake somewhere among all the tests sites...


RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by JoomliC** [comment]
You're welcome @infograf768 :+1: 

Thanks everybody for testing!

**Comment by infograf768** [comment]
@JoomliC 
Please look at https://github.com/joomla/joomla-cms/issues/11013
I don't have any test sites here with so many components.

**Comment by RonakParmar** [comment]
I have tested this item :red_circle: unsuccessfully on d7442a87fabff70a768cfcae473c2dba94f2baa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by RonakParmar** [comment]
I have installed latest staging branch in my local and applied this PR, still having same issue.screen shot 2016-07-04 at 01 28 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10987">issues.joomla.org/joomla-cms/10987</a>.</sub>

**Comment by infograf768** [comment]
I confirm issue
https://github.com/joomla/joomla-cms/issues/11013

@RonakParmar 
No relation with this PR. Your screenshot is fine.
I posted my findings on https://github.com/joomla/joomla-cms/issues/11013

**Comment by C-Lodder** [comment]
What's happening with this. Do I need to look into anything or is it now RTC

**Comment by infograf768** [comment]
It is RTC.
@wilsonge 

I suggest this goes into next RC.

**Pull request merged**
