### PR TITLE
com_Media grammar corrections

### PR DESCRIPTION
**Pull request by brianteeman**
Change for upload to to upload for consistency and good grammar

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on b60c26776abea32c6146720ee106fa6ed963e84f<br /><br />on review - Thanks
@brianteeman What to do with the punycode thing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9506">issues.joomla.org/joomla-cms/9506</a>.</sub>

**Comment by brianteeman** [comment]
yes just spotted that - its a corruption in my fork - fixing it

On 21 March 2016 at 15:21, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> I have tested this item [image: :white_check_mark:] successfully on
> b60c267
> <https://github.com/joomla/joomla-cms/commit/b60c26776abea32c6146720ee106fa6ed963e84f>
>
> on review - Thanks
> @brianteeman <https://github.com/brianteeman> What to do with the
> punycode thing?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9506
> <https://issues.joomla.org/tracker/joomla-cms/9506>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9506#issuecomment-199336377>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
The extra punycode file has been removed - thanks @wilsonge

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on cfcd5b1aacbbf73492445e0a3acc65c580c162f6<br /><br />Don't know if I have to "test" it again but success on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9506">issues.joomla.org/joomla-cms/9506</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on cfcd5b1aacbbf73492445e0a3acc65c580c162f6<br /><br />:smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9506">issues.joomla.org/joomla-cms/9506</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9506">issues.joomla.org/joomla-cms/9506</a>.</sub>

**Pull request merged**
