### PR TITLE
[4.0] missing icon

### PR DESCRIPTION
**Pull request by brianteeman**
in font awesome 5 there is no fa-times-close

This PR changes it to fa-times which is what is used elsewhere

### Before
image

### After
image

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on eab0ccf3c156d96f6bc1a567711960dcfa418a34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26760">issues.joomla.org/tracker/joomla-cms/26760</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eab0ccf3c156d96f6bc1a567711960dcfa418a34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26760">issues.joomla.org/tracker/joomla-cms/26760</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26760">issues.joomla.org/tracker/joomla-cms/26760</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
