### PR TITLE
[4] missing changelog when discover a plugin/module/template

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .
If you discover a plugin/module/template which  have the `changelog` then no changelog info is saved

### Summary of Changes
set the changelog vaule

### Testing Instructions
install  this plugin https://github.com/alikon/testcom/raw/main/plugins/content/export/plg_content_export-1.0.1.zip with Discover

install  this module https://github.com/alikon/testcom/raw/main/modules/mod_jstats-1.0.0.zip with Discover

install this template   [template_test.zip](https://github.com/joomla/joomla-cms/files/9248582/template_test.zip) with Discover

### Actual result BEFORE applying this Pull Request
no changelog link available on Extensions: Manage

image

### Expected result AFTER applying this Pull Request
changelog link available on Extensions: Manage

image

### CODE REVIEW

**Comment by brianteeman** [comment]
does this change need to be applied to all extensions?

**Comment by alikon** [comment]
didn't checked yet with other extensions type, cause few of them use the changelog
i'll check it later , did you know some extensions that use changelog ?

**Comment by Kostelano** [comment]
@alikon jCode Syntax Highlighter 1.3.0 uses.

[plg_jcodesyntaxhighlighter_1.3.0.zip](https://github.com/joomla/joomla-cms/files/9241336/plg_jcodesyntaxhighlighter_1.3.0.zip)

UPD
Sorry, you probably meant a different type of extensions.

**Comment by alikon** [comment]
yes looking for modules, components

**Comment by ChristineWk** [comment]
@alikon Installed your Plugin, activated Patchtester, but got only:

screen shot 2022-08-02 at 10 38 20

Other extensions: Pinged: @PhocaCz. Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by alikon** [comment]
@ChristineWk  you need to click on the version number  (1.0.1) to open the modal with the changelog
and you need to install it via discover not normal installation

**Comment by Kostelano** [comment]
No, at least for modules it does not work. Probably for components too. I added the `<changelogurl>` tag beforehand.

Screenshot_1

**Comment by alikon** [comment]
@Kostelano  can you share it please

**Comment by ChristineWk** [comment]
> @ChristineWk you need to click on the version number (1.0.1) to open the modal with the changelog and you need to install it via discover not normal installation

Ah ... when clicking on version number the modal opened with the changelog info.
Will delete plugin and try with discover.

**Comment by Kostelano** [comment]
@alikon Sorry, I already left the PC. Just add your own line from the plugin to the manifest of any module/component.

**Comment by ChristineWk** [comment]
Plugin Installed via FTP and checked Discover:

pr38372-plugin-via-discover

After: "Install":

pr38372-alikon-install-discover

@alikon Sorry, when doing something wrong. (Usually never installed before via Discover).

**Comment by Kostelano** [comment]
@alikon Sorry, I can't understand the changes to the PR with the screenshots in your header post. As far as I understand, it was about displaying a link to the changelog BEFORE installing the extension on the discovery page. Your screenshots are from another section.

In addition, having tested the PR, I cannot get a successful test. The extension version is still not clickable on the discovery page.

Please explain. Maybe I'm not interpreting PR in the right way.

**Comment by alikon** [comment]
the 2nd screenshot is after discover installtion  then go to Extension-> Manage

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on afaedaffdb253f2d07d38a5630a28c009b611798<br /><br />Thanks, now I understand.
Yes, PR works great, I confirm. BEFORE - "not transferred" information with changelog, AFTER - "transferred".

I send a successful test. However, I would be happy if we could implement the same scenario for templates, and for components.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by alikon** [comment]
for component should be already ok https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Installer/Adapter/ComponentAdapter.php#L844

**Comment by alikon** [comment]
for template i need a template with changelog to test  cause  seems missing

**Comment by Kostelano** [comment]
I have already tested, you can safely add the same line to the corresponding file for the template, it is missing there.

Testing is easy - I just copied the **Cassiopeia** template directory, renamed it to template_test, added a link to the changelog, and installed the template.

Test and add a line please, I will resubmit a successful test. Thank you.

[template_test.zip](https://github.com/joomla/joomla-cms/files/9243816/template_test.zip)

**Comment by ChristineWk** [comment]
OK, the Plugin is tested successfully now: 
screen shot 2022-08-02 at 20 34 04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

For the loading of module I get an error 404

**Comment by alikon** [comment]
added the template extensions type

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 70a0738dccc7b2168769dd4da50f463f14a81170<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by Kostelano** [comment]
@ChristineWk, could you check and send the test, since you have already paid attention to this PR?

**Comment by ChristineWk** [comment]
@Kostelano 
a) yes test Plugin was/is successful. 
b) as I wrote: loading mod_jstats ... get error 404.
c) Loaded template_test OK, but in Backend not found under discover. Maybe installed on wrong place (FTP)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by Kostelano** [comment]
@ChristineWk 

2. https://github.com/alikon/testcom/blob/main/modules/mod_jstats/mod_jstats-1.0.0.zip
3. Throw the template into the directory with templates. Where is the Cassiopeia.

**Comment by ChristineWk** [comment]
3. OK installed via discover, but ...... sorry.

screen shot 2022-08-03 at 14 47 14
screen shot 2022-08-03 at 14 47 29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by Kostelano** [comment]
@ChristineWk Find **template_test** on the extension management page and look at the version - if it's clickable, then your test is successful. You do not need any other pages in this PR. Only managing extensions and having a clickable version.

**Comment by ChristineWk** [comment]
@Kostelano The version was clickable in the plugin test, but not in the template_test. 
That's why I made a screenshot of it where there is no underlined line in blue.

**Comment by sandewt** [comment]
@ChristineWk , see Extensions: Manage
screen shot 2022-08-04 at 12 33 38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by ChristineWk** [comment]
@sandewt Thanks, but I showed in the screenshot above that I was in extensions: Manage. 
The zips from the instructions here didn't work.

I tried it with other extensions which @ReLater provided me with the changelogs and test instructions!
A change also had to be made in adapter.php for module and template because I couldn't use the patch tester for that. 

It wasn't easy for me, but thanks to his support, I succeeded.
testtemplate-erfolgreich-05aug-nach-adapterphp
testmodul-erfolgreich-nach-adapterphp

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 70a0738dccc7b2168769dd4da50f463f14a81170<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by wilsonge** [comment]
Before I merge this can someone please just confirm that this PR doesn't cause any issues with older extensions without a changelog?

**Comment by laoneo** [comment]
@wilsonge you can install any module of DPCalendar for test.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 5b0f413447672604793c5053c20b77a2a5f13a65<br /><br />Installed the upcoming module from DPCalendar which doesn't have a changelog entry.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38372">issues.joomla.org/tracker/joomla-cms/38372</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you! Nice to see the changelogs now :)

**Pull request merged**
