### PR TITLE
[4.2] Fix breadcrumb for Tagged Items menu item type

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #27866.

### Summary of Changes
Currently, when you view a menu item which is linked to **Tagged Items** menu item type, the browser page title (or titles of the selected tags) in the menu item parameter will be added as the last item in breadcrumb. That's not expected behavior, the breadcrumb should end with title of that menu item only. See https://github.com/joomla/joomla-cms/issues/27866 for the long discussion about this.

### Testing Instructions
1. Use Joomla 4.2
2. Create articles with tag added to these articles
3. Create a menu item links to Tagged Items menu item type. Choose one or several tags in the menu item parameter

### Actual result BEFORE applying this Pull Request
Check the breadcrumb. The browser page title (or titles of the selected tags) in the menu item parameter will be added as the last item in breadcrumb.

### Expected result AFTER applying this Pull Request
Check the breadcrumb. The browser page title (or titles of the selected tags) in the menu item parameter is  not added as the last item in breadcrumb. The last item in breadcrumb is title of the menu item

### CODE REVIEW

**Comment by cyanama** [comment]
I've applied #39331 however breadcrumbs still don't work correct.

baseline3

Above I have three menus of tagged items

baseline1

Clicking the menu lines works as expected and shows correct breadcrumbs.

baseline2

However, when you select an item from the list, breadcrumbs always show the parent tag for the second menu line, in my case 'Series' instead of 'Authors'; same happens for the menus 'Genres' below. Somewhere in the code must be a variable constantly set to the value for the second menu.

Thanks
Cyana

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4fe5e47c2b3a7c3be1afdfdca2ba0db9710fcda0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39331">issues.joomla.org/tracker/joomla-cms/39331</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4fe5e47c2b3a7c3be1afdfdca2ba0db9710fcda0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39331">issues.joomla.org/tracker/joomla-cms/39331</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39331">issues.joomla.org/tracker/joomla-cms/39331</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
