### PR TITLE
[4.0] Removes unnecessary limit calculation in pagination

### PR DESCRIPTION
**Pull request by rajkumaar23**
### Summary of Changes
Removes redundant calculation of limit value in pagination.

### Testing Instructions
1) Code review
2) Ensure pagination doesn't break after this PR

### Documentation Changes Required
Nothing

### CODE REVIEW

**Comment by brianteeman** [comment]
What makes you feel it's not needed

**Comment by rajkumaar23** [comment]
> What makes you feel it's not needed

If you look at the previous line, the content is being stored in a variable `$limit.` 
```
	if ($item->base > 0)
	{
		$limit = 'limitstart.value=' . $item->base;
	}
	else
	{
		$limit = 'limitstart.value=0';
	}
```
Hence, it is meaningless to recalculate.

**Comment by richard67** [comment]
@brianteeman It seems the same calculation is already done here: [https://github.com/joomla/joomla-cms/blob/1334f2b0552822fa849614f7019225c161d4ed95/layouts/joomla/pagination/link.php#L57-L64](https://github.com/joomla/joomla-cms/blob/1334f2b0552822fa849614f7019225c161d4ed95/layouts/joomla/pagination/link.php#L57-L64).

So the PR could be right.

@rajkumaar23 Could you provide some testing instructions?

**Comment by rajkumaar23** [comment]
> @brianteeman It seems the same calculation is already done here:
> 
> https://github.com/joomla/joomla-cms/blob/1334f2b0552822fa849614f7019225c161d4ed95/layouts/joomla/pagination/link.php#L57-L64
> .
> 
> So the PR could be right.
> 
> @rajkumaar23 Could you provide some testing instructions?

Sorry, I'm new to Joomla. I have no idea about how tests work here. Could you please help ?

**Comment by richard67** [comment]
@rajkumaar23 Just add some testing instructions for human testers to the description in your PR where the head lines from the PR template say so:

### Testing Instructions
### Expected result
### Actual result

For example you could simply write "Code review" below "Testing inctructions".

If you want to be sure that you made no mistake which could be missed by some reviewer you also could write instructions for a real test by a human, e.g.:

1. Apply the patch of this PR.
2. Make sure that pagination links in frontend still work.

(or so)

Here for this PR it is trivial, but our contribution rules require to fill out the necessary information in the description.

Thank you for your PR.

**Comment by rajkumaar23** [comment]
@richard67 
Sure, thanks. I've updated my PR description :+1:

**Comment by richard67** [comment]
@rajkumaar23 When we make PRs for the 4.0-dev branch we're used to have "[4.0] " at the beginning of the title, so we can quickly see it is not for staging (= 3.9.x-dev) or 3.10-dev. Is not a must but good practice. I've just updated the title for you. Will test soon, but as I could already see by code review I am sure the result will be success.

**Comment by rajkumaar23** [comment]
@richard67 Sure, I'll follow that format. And, thanks for the help :)

**Comment by richard67** [comment]
@rajkumaar23 Another suggestion: I see you were using your 4.0-dev branch for this PR. This is ok as long as you do not make several PRs for the 4.0-dev branch of Joomla.

But as you maybe can imagine, new contributors are always welcome, and so if you have some free time and find other issues to fix you might make more than one PR at a time. We (Joomla community) would be happy about that.

For working on several issues it will be necessary to create a new branch for making a PR. Depending on the branch for which the PR will be, you will make this new branch based on the 4.0-dev branch or the staging branch of the CMS.

Maybe you know all that already and this time it was just faster not to do it. But if that is new to you, you can find some useful information here: [https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests](https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests) and here [https://docs.joomla.org/Git_branching_quickstart](https://docs.joomla.org/Git_branching_quickstart) and at a few other places linked on [https://docs.joomla.org/Portal:Joomla!_Code_Contributors](https://docs.joomla.org/Portal:Joomla!_Code_Contributors).

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1334f2b0552822fa849614f7019225c161d4ed95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27480">issues.joomla.org/tracker/joomla-cms/27480</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1334f2b0552822fa849614f7019225c161d4ed95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27480">issues.joomla.org/tracker/joomla-cms/27480</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27480">issues.joomla.org/tracker/joomla-cms/27480</a>.</sub>

**Comment by wilsonge** [comment]
Thanks for your first PR to Joomla 🎉

**Comment by rajkumaar23** [comment]
> Thanks for your first PR to Joomla :tada: 

Thank you! 🤩️ Looking forward to contribute more.

**Pull request merged**
