### PR TITLE
[4.0] Quick Icons description

### PR DESCRIPTION
**Pull request by brianteeman**
The description for the group of this module has not been updated since the module was enhanced and changed in J4. As a result the information about the core icons is not correct any more and this PR resolves that.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 02e63844b5b91a60cfa824d1fac3bb0f5f6d9ffc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35116">issues.joomla.org/tracker/joomla-cms/35116</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 02e63844b5b91a60cfa824d1fac3bb0f5f6d9ffc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35116">issues.joomla.org/tracker/joomla-cms/35116</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35116">issues.joomla.org/tracker/joomla-cms/35116</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
