### PR TITLE
[4.4] tags learn more link

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #42812 .

### Summary of Changes
Changes the link to the docs to one for j4 and not j3 which is more detailed

### Testing Instructions
With no tags you will see the emtpy state view and the learn more button

image

### Actual result BEFORE applying this Pull Request
j3 page opens

### Expected result AFTER applying this Pull Request
j4 page opens

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a07734af52e61a6fbdb7e447ec2bd391363bd359<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42815">issues.joomla.org/tracker/joomla-cms/42815</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on a07734af52e61a6fbdb7e447ec2bd391363bd359<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42815">issues.joomla.org/tracker/joomla-cms/42815</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42815">issues.joomla.org/tracker/joomla-cms/42815</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
