### PR TITLE
[4] s/to add to add/to add

### PR DESCRIPTION
**Pull request by PhilETaylor**
Typo

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d537e6d7c09a88a184451ef68ce6554af2456038<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36429">issues.joomla.org/tracker/joomla-cms/36429</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on d537e6d7c09a88a184451ef68ce6554af2456038<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36429">issues.joomla.org/tracker/joomla-cms/36429</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36429">issues.joomla.org/tracker/joomla-cms/36429</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
