### PR TITLE
[4] hits - Move rendering from outside of the model

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

https://github.com/joomla/joomla-cms/pull/34257 (@brianteeman) added rendering in the helper (which is used as a proxy to the model, for a `getList` method calling a `getItems` in the model. 

This is the wrong place to be rendering output. 

This PR moves the output rendering to the parent module file. 

### Testing Instructions

Add the `Articles - Most Read` module to your home page and view it with Record Hits enabled and disabled in Article Options. 

and/or code review

### Actual result BEFORE applying this Pull Request

Same as before this PR 

### Expected result AFTER applying this Pull Request

Same as before this PR but correct code placement. 

### Documentation Changes Required

None. 

**This PR will conflict with #34318 eventually - when it does I'll fix it before merge**

### CODE REVIEW

**Comment by PhilETaylor** [comment]
**This PR will conflict with #34318 eventually - when it does I'll fix it before merge**

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 213b62374875e4bf44e69b75b33a799587f41598<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34320">issues.joomla.org/tracker/joomla-cms/34320</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 213b62374875e4bf44e69b75b33a799587f41598<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34320">issues.joomla.org/tracker/joomla-cms/34320</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34320">issues.joomla.org/tracker/joomla-cms/34320</a>.</sub>

**Comment by HLeithner** [comment]
Not that bothers to much but shouldn't this be in it's own layout then?

**Comment by PhilETaylor** [comment]
yes probably, but its overkill as its

1) Used once, in one place
2) more function calls, file loads, just to echo out a single string

:)

**Comment by richard67** [comment]
@PhilETaylor Could you fix the conflict in file `modules/mod_articles_popular/src/Helper/ArticlesPopularHelper.php`? It comes from your other, merged PR #34318 .

**Comment by PhilETaylor** [comment]
Sone.

**Comment by richard67** [comment]
@PhilETaylor Thanks. In fact this PR had the correction of the other one already, as I could see, so the last commit was just a clean branch update.

Previous test results are still valid. I've restored them in the issue tracker.

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
