### PR TITLE
[4.0] Fix month filter in com_content

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Fixes the month filter introduced in https://github.com/joomla/joomla-cms/pull/18361 for namespaced code

### Testing Instructions
Set the "Filter Field" parameter to 'month' for a article category list view. Before patch page breaks. After patch page works.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fa1198f4b09d4b2aa1097fb16afe8f34a5c2a272<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27471">issues.joomla.org/tracker/joomla-cms/27471</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e908ac0c212c5f43093cf1e44ec65cb76675fc39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27471">issues.joomla.org/tracker/joomla-cms/27471</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27471">issues.joomla.org/tracker/joomla-cms/27471</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
