### PR TITLE
[4.1] Finder auto-suggestions broken

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Finder auto-suggestions for search fields are broken due to encoded URL for suggestion requests.

### Testing Instructions

Load finder page, enable suggestions, try to search for any existing word, see requests with encoded `&amp;` and invalid data.

### Actual result BEFORE applying this Pull Request

Finder suggestions are broken.

### Expected result AFTER applying this Pull Request

Finder suggestions are fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@bembelimen Should this be rebased to 4.1-dev?

**Comment by bembelimen** [comment]
There will be most likely no 4.0 merges anymore (if not a security issue comes up), so yes please.

**Comment by richard67** [comment]
@Denitz Let us know if you need help with rebasing the PR to the 4.1-dev branch.

**Comment by Denitz** [comment]
@richard67 I rebased this PR.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3be67ab04261f582570ea25531bf66f0aa83d0ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36877">issues.joomla.org/tracker/joomla-cms/36877</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 3be67ab04261f582570ea25531bf66f0aa83d0ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36877">issues.joomla.org/tracker/joomla-cms/36877</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36877">issues.joomla.org/tracker/joomla-cms/36877</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
