### PR TITLE
Fixes enable / disable check box in plugin manager on IE 10

### PR DESCRIPTION
**Pull request by ericfernance**
Hi Folks,

Prior to this commit on IE 10 trying to publish / unpublish a plugin in the Plugin Manager by clicking the tick or cross box would not work.  

The IE 10 developer tools console would throw SCRIPT87: Invalid argument error in core.js.  (see screenshot) This only affected IE 10, other browsers were fine.

ie-10-core-js-error

This fixes that by changing the document.adminForm.fireEvent from submit to onsubmit as per HTML DOM Event Object list here(http://www.w3schools.com/jsref/dom_obj_event.asp)

To test, WITHOUT patch go to Plugin Manager and click on the cross box next to a plugin to publish.  IE 10 developer tools should show error message as per screenshot and the plugin publish state will not change.  Install patch and repeat.  With patch installed the plugin should be correctly enabled / disabled.

### CODE REVIEW

**Comment by n9iels** [comment]
Looks like this problem only occurs in IE10, I can't reproduce it for IE11

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/5914 This should have been already fixed by this PR in 3.4. Can you ensure you've tested this bug against 3.4 please :)

**Comment by digitalgarage** [comment]
@n9iels yes it was only IE10.  IE11 was fine.

@wilsonge that fixes the same problem further up in core-uncompressed.js.  In 3.4 the toolbar was fixed by #5914 on line 30.   ...But.... the toggle buttons to publish / unpublish were using almost identical code on line 427 - 429 of core-uncompressed.js that weren't updated.

Copy of current lines 427 - 429 below from core-uncompressed.js.  This is taken from branch staging checked out this morning.  This PR replicates the fix used at line 30 (ie. to change the submit to onsubmit') but applies it to 427-429.

    if (typeof document.adminForm.fireEvent == "function") {
        document.adminForm.fireEvent('submit');
    }

Eric.

**Comment by Fedik** [comment]
@wilsonge looks like somewhere still in use deprecated `function submitform(pressbutton)`
I missed it in #5914

**Comment by wilsonge** [comment]
My bad :) Didn't notice it was different lines. I blame it on reviewing stuff before I had morning coffee

**Comment by digitalgarage** [comment]
No worries.... Coffee is the only thing that keeps my brain ticking over some days!

**Pull request merged**
