### PR TITLE
[4.0] Correct tooltip on contact edit icon on PDO

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds explicit cast for value returned from database.

### Testing Instructions

Code review is fine.

Or create and unpublish a contact.
Login as admin to frontend.
View the contact, hover over the icon next to Edit button.

### Expected result

    <strong>Edit Contact</strong><br>Unpublished<br />Saturday, 06 June 2020<br />Written by You

### Actual result

    <strong>Edit Contact</strong><br>Published<br />Saturday, 06 June 2020<br />Written by You

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5fcd5cf953e2c9b3d7ca7763de94176742fe7b50<br /><br />Both code review and real test ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29458">issues.joomla.org/tracker/joomla-cms/29458</a>.</sub>

**Comment by adj9** [comment]
To see the contacts in the FrontEnd I have to publish them, I have to activate his status. Otherwise, by setting a menu item in the contact list, I have an empty list.

How do I see the expected result on the frontend with the contacts disabled?

However, the HTML code I inspect with active contacts (with PR enabled) is
Schermata 2020-06-06 alle 17 20 44

**Comment by richard67** [comment]
@adj9 You have to set a menu item of type "Single Contact" for that contact. Then, when being logged in as super admin on frontend, navigate to that menu item so you can see the single contact. Then open the drop down at the right top coerne and hover over the item "Edit" in that drop down, and you see the tooltip.

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 5fcd5cf953e2c9b3d7ca7763de94176742fe7b50<br /><br />Thanks @richard67, I was lost.

I confirmed the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29458">issues.joomla.org/tracker/joomla-cms/29458</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29458">issues.joomla.org/tracker/joomla-cms/29458</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
