### PR TITLE
Switcher field transition, from j3.10 to j4.0

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #29885 

### Summary of Changes
As for comment https://github.com/joomla/joomla-cms/pull/29885#issuecomment-654792367
The patch allows to transition from "btn-group" to "switcher" field more transparent.
The developer only need to add the layout attribute `layout="joomla.form.field.radio.switcher"` to the field xml.

I guess it has to be merged to 3.10 :)

### Testing Instructions
Testing a bit tricky:
 * Apply the patch.
 * ~~Edit https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Version.php : set~~ (no need to edit it anymore)
 * Create a "btn-group" field, somewhere, example in Custom HTML module:
```xml
<field
	name="switchertest"
	type="radio"
	label="switcher test"
	class="btn-group btn-group-yesno"
	layout="joomla.form.field.radio.switcher"
	default="1"
>
	<option value="1">JYES</option>
	<option value="0">JNO</option>
</field>
```

### Actual result BEFORE applying this Pull Request
The field are empty

### Expected result AFTER applying this Pull Request
The field rendered as "btn-group"

Also try testing Instructions from #29885 pull.

### Documentation Changes Required
I guess, maybe some explanation about transition to Joomla! 4

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Don't need the version thing in this case. You can just add `joomla.form.field.radio.switcher` layout and load `joomla.form.field.radio` layout inside it.

**Comment by Fedik** [comment]
hm, that also true, I did not thought about :smile: 
will see, what others will say

**Comment by HLeithner** [comment]
> Don't need the version thing in this case. You can just add `joomla.form.field.radio.switcher` layout and load `joomla.form.field.radio` layout inside it.

That's the point you can't if you want to support j3 and j4 if I understand the original problem correct.

**Comment by SharkyKZ** [comment]
It works. Just need to make sure the new layout from J3 doesn't get merged into 4.0.

**Comment by HLeithner** [comment]
Maybe I miss something but how should this work?
In j3 we have a file called `layouts/joomla/form/field/radio.php`
In j4 we have a file called `layouts/joomla/form/field/radiobasic.php` and a directory `layouts/joomla/form/field/radio/` with 2 files `buttons.php` and `switcher.php` 

When you set `joomla.form.field.radio.switcher` in j3 it can't find the layout right?
When you set `joomla.form.field.radio` in j4 it can't find the layout right?

**Comment by HLeithner** [comment]
Or do you suggest to create the `radio/switcher.php` in 3.10.0?

**Comment by Fedik** [comment]
@HLeithner  the layout file `joomla.form.field.radio.switcher` (from Joomla 3) should not be merged to Joomla 4 branch. 
Then while upgrade Joomla 3 `joomla.form.field.radio.switcher` file will be overridden by file from Joomla 4.
So Joomla 4 will use own `joomla.form.field.radio.switcher`.
That what @SharkyKZ meant

> Or do you suggest to create the radio/switcher.php in 3.10.0?

yeap

**Comment by HLeithner** [comment]
Would make more sense. can you make a pr against 3.10?

**Comment by Fedik** [comment]
redo for 3.10 #30078

**Pull request closed without merging**
