### PR TITLE
com_tags. Respect Browser Page Title in view Tagged Items

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13365

### Testing Instructions
- See comment 1 in issue please https://github.com/joomla/joomla-cms/issues/13365#issue-197480449
- Apply patch
- Test again
- Please test also with other com_tags menu item types concerning conflicts because com_tags "is a little bit strange".

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3065e5955ae7539fefc587d7a168d68c88a8bb3e<br /><br />Test with all 3 com_tags-Menu Item Types.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16773">issues.joomla.org/tracker/joomla-cms/16773</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f8a4bec489ef957f75f6f2c00b71e088e36a1bb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16773">issues.joomla.org/tracker/joomla-cms/16773</a>.</sub>

**Comment by bertmert** [comment]
Sorry but because of some pedantry you have to test again...

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1c2c611d3ca85a3a252231f7760ad6bbdd26d54a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16773">issues.joomla.org/tracker/joomla-cms/16773</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1c2c611d3ca85a3a252231f7760ad6bbdd26d54a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16773">issues.joomla.org/tracker/joomla-cms/16773</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@ghost couldn't test cause "Error: The patch could not be applied because the repository is missing".

**Comment by Quy** [comment]
The user deleted his Git account/branch. You will have to manually patch under `Files changed` to test.

**Comment by franz-wohlkoenig** [comment]
@Quy thanks for Info. Will wait for @ghost to append branch again for Test.

**Comment by Quy** [comment]
ghost is a Git deleted user account. For more information:
http://help.github.com/articles/deleting-your-user-account

**Comment by franz-wohlkoenig** [comment]
@Quy bad News, no Branch coming. Will look if i figure out to manually apply changed Files.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully by manually patch view.html.php.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1c2c611d3ca85a3a252231f7760ad6bbdd26d54a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16773">issues.joomla.org/tracker/joomla-cms/16773</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
