### PR TITLE
[com_finder] Add/Improve search tooltip in all views

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to add the search tooltip and element label (accessibility) in com_finder.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Go to Components -> Smart Search -> Indexed Content, check the tooltip in the search field.
3. Go to Components -> Smart Search -> Content Maps, check the tooltip in the search field.
4. Go to Components -> Smart Search -> Search Filters, check the tooltip in the search field.

### CODE REVIEW

**Comment by RonakParmar** [comment]
@andrepereiradasilva Sorry, but I am not able to see any changes before and after patch applied, Can you please provide some more information regarding changes of the PR.
System Information:
Joomla Version: Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT
PHP Version: 5.4.45-3+deb.sury.org~precise+1
Database Version: 5.5.49-0ubuntu0.12.04.1
Web Server: Apache/2.2.22 (Ubuntu)

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Comment by RonakParmar** [comment]
Hi,
I am not able see any tooltip on "Indexed Content" and "Search Filters" views of com_finder component.
On "Content Maps" view I can see "Search in content map title." tooltip on mouse-over of search-box. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@RonakParmar are you using latest staging? There have been a lot of changes recently.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on c9330ddaebc660fb29093cb7d22e524ef7220f0b<br /><br />same results as @RonakParmar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Comment by andrepereiradasilva** [comment]
strange, will check later

**Comment by andrepereiradasilva** [comment]
@brianteeman @RonakParmar just tested again in latest staging.

It's working fine. please check code difference to see the changes that should exist after PR.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c9330ddaebc660fb29093cb7d22e524ef7220f0b<br /><br />No idea what was wrong before. I probably needed more cafeine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on c9330ddaebc660fb29093cb7d22e524ef7220f0b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10181">issues.joomla.org/joomla-cms/10181</a>.</sub>

**Pull request merged**
