### PR TITLE
Pagination user manager when Search Tools present

### PR DESCRIPTION
**Pull request by Bakual**
### Issue

Pagination doesn't work when you select a "0" value in the SearchTools. In the user manager this is for example "Activated" or the state "Enabled". In the Article Manager this would be the state "Disabled" (btw consistency ftw!).
See https://github.com/joomla/joomla-cms/issues/7486 for the original issue
### Solution

I tried to fix that originally with https://github.com/joomla/joomla-cms/pull/7194 but did a stupid mistake. Of course "0" is a valid filter value, but my boolean check would take that as an invalid value.
This PR fixes it by only threating an empty string (nothing selected) as invalid.
### Testing

Test that the pagination the managers with Search Tools work with any values. Also test that it still works in Hathor and modal layouts.

~~Known issue so far~~
~~The "Groups" filter in the user manager still acts wrong. I haven't found yet why that is. maybe someone has an idea.~~

### CODE REVIEW

**Comment by LaurensGoedel** [comment]
This fixes indeed the state filter.
As described, the group filter isn't working. I'll try to have a look at it later today

**Comment by LaurensGoedel** [comment]
Somewhere is the function 'getUserStateFromRequest' called with the wrong key. Key com_users.users.default.filter.group is being called instead of com_users.users.default.filter.group_id.

Thats why the cur_state isn't the same as new_state and that is why the limitstart is set to 0

Haven't found the wrong call yet, someone got a clue where to search?

**Comment by Bakual** [comment]
@LaurensGoedel That was the hint I needed, thanks! Can you try again?

**Comment by LaurensGoedel** [comment]
@Bakual yes, thats it! 
i've overlooked that multiple times :disappointed: 

Thanks!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on d667541474794c1788cbba6888e574bc5136028a<br /><br />Thanks fixes the issue for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7487">issues.joomla.org/joomla-cms/7487</a>.</sub>

**Comment by zero-24** [comment]
Together with the test by @LaurensGoedel I'm goint to mark this RTC for 3.5.0. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7487">issues.joomla.org/joomla-cms/7487</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @Bakual and testers! Merged.

**Pull request merged**
