### PR TITLE
[4.0] Joomla 3 reference

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to change reference to joomla 4

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fcab00fde0d1d5ba7bd71b2ba0f1c86b7e16db6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19276">issues.joomla.org/tracker/joomla-cms/19276</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fcab00fde0d1d5ba7bd71b2ba0f1c86b7e16db6f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19276">issues.joomla.org/tracker/joomla-cms/19276</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
