### PR TITLE
[4.0] Descriptions review (again)

### PR DESCRIPTION
**Pull request by brianteeman**
Another round of reviewing descriptions and removing ones we dont need and checking codestyle

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba0e6c2e880ee5d3ee648ce8723143f3eb71da33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24975">issues.joomla.org/tracker/joomla-cms/24975</a>.</sub>

**Review by zero-24 — COMMENTED** [review]
com_csp looks good to me.

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 03df601d1af57c6a5539a735826ae7aa1addc9c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24975">issues.joomla.org/tracker/joomla-cms/24975</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24975">issues.joomla.org/tracker/joomla-cms/24975</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 03df601d1af57c6a5539a735826ae7aa1addc9c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24975">issues.joomla.org/tracker/joomla-cms/24975</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24975">issues.joomla.org/tracker/joomla-cms/24975</a>.</sub>

**Comment by wilsonge** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
