### PR TITLE
enable custom fields option

### PR DESCRIPTION
**Pull request by brianteeman**
The current option is a little confusing as it does NOT refer to enabling/disabling custom fields - it only refers to if you can create them.

The use case would be that you have built the site and set up all the fields and field groups that you want to use and no longer want to display the two menu links to fields and field groups

Hopefully this is a little clearer

### Before
n9vh 1

### After
ryla 1

### CODE REVIEW

**Comment by astridx** [comment]
The text is currently confusing. I say “hide” but I still see the -in the past created- fields. 

With this patch it is clearer to me. 


I've tested the patch successfully in com_content and com_conact - it works as described.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 71ef60f6d1086f7ec0d42adbcf258eb99315eee5<br /><br />more clear now following your use case<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12663">issues.joomla.org/tracker/joomla-cms/12663</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 71ef60f6d1086f7ec0d42adbcf258eb99315eee5<br /><br />Thanks for clarification.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12663">issues.joomla.org/tracker/joomla-cms/12663</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12663">issues.joomla.org/tracker/joomla-cms/12663</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
