### PR TITLE
[4.0] com_messages blank state

### PR DESCRIPTION
**Pull request by brianteeman**
See #33264 for instructions but this time for user private messages and not content

This PR requires the code from #33264 to be merged first - specifically the change in libraries/src/MVC/Model/ListModel.php

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 25f229093a09e6de3c12953bfe1b0c03131a9a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33274">issues.joomla.org/tracker/joomla-cms/33274</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 25f229093a09e6de3c12953bfe1b0c03131a9a1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33274">issues.joomla.org/tracker/joomla-cms/33274</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33274">issues.joomla.org/tracker/joomla-cms/33274</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
