### PR TITLE
[5.0] Add alternative field labels (+ a new attribute) for the Status field

### PR DESCRIPTION
**Pull request by ditsuke**
### Summary of Changes
Many extensions currently use custom status fields ([PluginStatusField](https://github.com/ditsuke/joomla-cms/blob/dcon/libraries/src/Form/Field/PluginstatusField.php), [RedirectStatusField](https://github.com/ditsuke/joomla-cms/blob/dcon/libraries/src/Form/Field/RedirectStatusField.php), [TaskStateField](https://github.com/ditsuke/joomla-cms/blob/dcon/administrator/components/com_scheduler/src/Field/TaskStateField.php) (from #35143)), mainly because it makes more contextual sense to use Enabled/Disabled as states at some places instead of Published/Unpublished. 
This also increases scope for inconsistencies which can be seen as an example in the forms for `com_workflows` (reference #35056). 

This PR adds alternative labels the `status` field which can be used with the `alt_labels` field attribute. This can be used in conjunction with `optionsFilter` at places where a list field or a custom field might be needed right now.

For example, if you want to support the enabled, disabled and trashed state for an item, you could use:
```xml
<field 
	name="state"
	type"status" 
	label="JSTATUS"
	optionsFilter="-2, 0, 1"
	alt_labels="true"
/> 
```

Right now, you'd have to contend with a custom field, a list field everywhere or a language override (https://github.com/joomla/joomla-cms/pull/35743#issuecomment-933180203).

### Testing Instructions
You can test that StatusField (field type="status") behaves the same as before in all existing forms.
I can also add the `alt_labels` attribute to the workflow forms and some more places in this PR so those could be tested here and perhaps some redundant field classes removed.

### Actual result BEFORE applying this Pull Request
StatusField only supports "publish" type labels.

### Expected result AFTER applying this Pull Request
StatusField supports alternative state labels needed by a number of existing core extensions.

### Documentation Changes Required
Update to the Form Fields/StatusField documentation on JDocs.

### CODE REVIEW

**Comment by brianteeman** [comment]
Could you give an example please of where this would be used

**Comment by ditsuke** [comment]
> 
> 
> Could you give an example please of where this would be used

Workflow forms (I linked a PR for reference), replacing PluginStatusField, RedirectStatusField and TaskStatusField (from Scheduler).

**Comment by brianteeman** [comment]
Personally I have always done this with just a language string

For example (together with your fix for workflows) it will look like this
image

Just by adding two language string overrides to com_workflows.ini
image

**Comment by ditsuke** [comment]
> 
> 
> Personally I have always done this with just a language string
> 
> For example (together with your fix for workflows) it will look like this [image](https://user-images.githubusercontent.com/1296369/135803232-97e0a15b-c52c-437d-b5a5-00303a49cca1.png)
> 
> Just by adding two language string overrides to com_workflows.ini [image](https://user-images.githubusercontent.com/1296369/135803308-a1763584-08ce-4d0c-af44-77ac97fc4b7e.png)

That's a good solution! I think this change should still be worth considering as it might be easier perhaps to use an attribute for the safe effect as its used in quite a few places.

**Comment by ditsuke** [comment]
Rebased to `4.1-dev`

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 255d84099782b565094e32f646b1f1f8c5abc1ec<br /><br />I tested the alt_labels attribute in several filters like categories and the patch worked. Enabled and Disabled showed up.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35743">issues.joomla.org/tracker/joomla-cms/35743</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev.

**Comment by brianteeman** [comment]
Looking at this again and I realise now the benefits. Together with the optionsFilter this PR would allow us to remove several fields as they would become redundant.

**Comment by brianteeman** [comment]
could someone change the title to say [5.0] instead of 4.1 please

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bd4110616d3d68f34e6257aa1a65be5a3feccd3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35743">issues.joomla.org/tracker/joomla-cms/35743</a>.</sub>

**Comment by HLeithner** [comment]
The proper way would be to create an addition field with other default values, then you don't need an extra attribute.

Something like StateField instead of StatusField.

**Comment by richard67** [comment]
Although it has 2 successful human tests I don't set it to RTC because it has a conflict in file "libraries/src/Form/Field/StatusField.php".

And @HLeithner 's comment above suggest a different solution.

**Comment by HLeithner** [comment]
as said own field instead of additonal attribute please. I'm closing this but can be reopend when we get it's own field or a more flexible way to change the label of the options (maybe swapable language constants)

**Pull request closed without merging**
