### PR TITLE
Components configuration menu items

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #14256 

### Summary of Changes
* Components configuration menu link - show only applicable components.
* Let alone the current JFormFieldComponents as a library class for general usage, create a new field class specific for com_config.
* Remove JFormFieldsComponents from com_users as it is essentially the same as the generic field class added in J3.7.
* Do not show PHP warnings if someone tries to open unsupported component config page. Handle it gracefully.

### Testing Instructions
Create a new admin menu type.
For that menutype, create a new menu item of type "Component Configuration".

### Expected result
In the "Choose a component" dropdown, one CANNOT choose "Administrator - System Information" as it has no configuration.

### Actual result
In the "Choose a component" dropdown, one can choose "Administrator - System Information"

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
@izharaazmi where to find `Component Configuration`, found this types:
bildschirmfoto 2017-02-27 um 14 20 03

**Comment by izharaazmi** [comment]
Under configuration manager

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 27d95027fab003621307cbe3960f066c7c1f9ace<br /><br />After choose `Configuration Manager` or another Value in Dropdown got: ` Fatal error: Class 'JFormFieldList' not found in /administrator/components/com_config/model/field/configcomponents.php on line 19`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14267">issues.joomla.org/tracker/joomla-cms/14267</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8bb661af67005add4b1265edb65d7ef921603c1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14267">issues.joomla.org/tracker/joomla-cms/14267</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8bb661af67005add4b1265edb65d7ef921603c1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14267">issues.joomla.org/tracker/joomla-cms/14267</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14267">issues.joomla.org/tracker/joomla-cms/14267</a>.</sub>

**Pull request merged**
