### PR TITLE
Remove type Attribute from <script> tag

### PR DESCRIPTION
**Pull request by thuebschmann**
Pull Request for Issue # .

### Summary of Changes

Remove type Attribute vom Inline script

### Testing Instructions

enable emailcloack plugin
set document->isHTML5(true)
have an emial in Content
Check the gernerated page with https://validator.w3.org/nu/

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This causes validation errors on non-HTML5 pages.

**Comment by richard67** [comment]
See also comment here: [https://github.com/joomla/joomla-cms/issues/23300#issuecomment-448613049](https://github.com/joomla/joomla-cms/issues/23300#issuecomment-448613049)

**Review by richard67 — CHANGES_REQUESTED** [review]
This pull request is wrong for reasons started in comments be @SharkyKZ and in comment in the issue here: [https://github.com/joomla/joomla-cms/issues/23300#issuecomment-448613049](https://github.com/joomla/joomla-cms/issues/23300#issuecomment-448613049).

Therefore it should be closed.

**Comment by Bakual** [comment]
If you really want to get rid of that type attribute, you'd have to check if the document is set to HTML5 first and only then remove the type.

I'll close this PR as it is wrong in the current state.

**Pull request closed without merging**
