### PR TITLE
[4.3] Language of parts bug

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40568 .

### Testing Instructions
Go to the TinyMCE plugin and add a Language of Parts item but leave the fields blank.
Save and go to edit an article.

Also test after the PR that you can still add a language of parts without error

### Actual result BEFORE applying this Pull Request
Error page:
array_merge(): Argument https://github.com/joomla/joomla-cms/pull/1 must be of type array, null given
JROOT/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php:393

### Expected result AFTER applying this Pull Request
No error

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
Testing on 4.3.1 - patch works fine. So I should pass this. But...

Testing this on 4.2.10-dev with the patch applied, I get
call to a member function getIdentity() on null 
1 	() 	JROOT/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php:71
2 	PlgEditorTinymce->onDisplay() 	JROOT/libraries/src/Editor/Editor.php:194 
I applied the patch, added the empty Language of Parts, then went to Article edit. New error appears.
Reverted LofP and Patch - back to normal.

That maybe irrelevant but I though it best to mention it before reporting a pass.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40581">issues.joomla.org/tracker/joomla-cms/40581</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b5b487b945f37559549f96436f0860a74d4f00d5<br /><br />Decided my previous comment was stupid. Patch works fine on 4.3.1. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40581">issues.joomla.org/tracker/joomla-cms/40581</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b5b487b945f37559549f96436f0860a74d4f00d5<br /><br />Works as described.

However, isn't it an issue that the plugin settings form allows to save an empty language of parts? Could that be fixed with another PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40581">issues.joomla.org/tracker/joomla-cms/40581</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40581">issues.joomla.org/tracker/joomla-cms/40581</a>.</sub>

**Comment by brianteeman** [comment]
> However, isn't it an issue that the plugin settings form allows to save an empty language of parts? Could that be fixed with another PR?

I think that is a generic issue with the repeatable field

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
