### PR TITLE
[4.x] Batch Users move

### PR DESCRIPTION
**Pull request by brianteeman**
Set to group means to remove the user from any existing group and put them in the selected group. It is more consistent terminology, and easier to understand, to change the label to "Move To"

### Testing Instructions
Use the batch user option to add, move and remove a user from a group

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### CODE REVIEW

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on 157ea068291bdbc0236ae384ce1013223d6cd397<br /><br />IMHO it makes more sense to change it to "Move To". 
In the Batch option of Content > Articles, the term "Move" is also used: "Copy or Move to Category"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37657">issues.joomla.org/tracker/joomla-cms/37657</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 157ea068291bdbc0236ae384ce1013223d6cd397<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37657">issues.joomla.org/tracker/joomla-cms/37657</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37657">issues.joomla.org/tracker/joomla-cms/37657</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
