### PR TITLE
delete old files from 3.2.3

### PR DESCRIPTION
**Pull request by AlexRed**
Pull Request for Issue # .
### Summary of Changes

delete old files and folders in the update procedure
### Testing Instructions

install a new 3.2.3 version, update to 3.6.3 and some old files still here:
administrator/components/com_config/controller/application/refreshhelp.php
administrator/templates/hathor/html/com_categories/categories/default_batch.php
administrator/templates/hathor/html/com_tags/tags/default_batch.php
libraries/joomla/github/users.php
media/com_finder/css/selectfilter.css
media/com_finder/css/sliderfilter.css
media/com_finder/js/sliderfilter.js
media/editors/tinymce/skins/lightgray/fonts/icomoon-small.eot
media/editors/tinymce/skins/lightgray/fonts/icomoon-small.svg
media/editors/tinymce/skins/lightgray/fonts/icomoon-small.ttf
media/editors/tinymce/skins/lightgray/fonts/icomoon-small.woff
media/editors/tinymce/skins/lightgray/fonts/icomoon.eot
media/editors/tinymce/skins/lightgray/fonts/icomoon.svg
media/editors/tinymce/skins/lightgray/fonts/icomoon.ttf
media/editors/tinymce/skins/lightgray/fonts/icomoon.woff
media/editors/tinymce/skins/lightgray/fonts/readme.md
media/editors/tinymce/skins/lightgray/img/wline.gif
media/system/js/validate-jquery-uncompressed.js
templates/beez3/html/message.php
### Documentation Changes Required

from an 3.2.3 installation, these file no longer exist in Joomla 3.6.3

### CODE REVIEW

**Comment by brianteeman** [comment]
There are a lot more unused files that were forgotten in the past. There is a PR/Issue for this already I just cant find it right now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12304">issues.joomla.org/tracker/joomla-cms/12304</a>.</sub>

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/issues/11616#issuecomment-251194149

@brianteeman ?

**Comment by brianteeman** [comment]
@zero-24 see I knew it existed ;) just forgot it was me that was supposed to do something with it.

**Comment by brianteeman** [comment]
@jsubri could you test this one as well please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12304">issues.joomla.org/tracker/joomla-cms/12304</a>.</sub>

**Comment by jsubri** [comment]
I ve almost no access to the net until 31th Oct. I can't test before 1st week of Nov.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12304">issues.joomla.org/tracker/joomla-cms/12304</a>.</sub>

**Comment by jsubri** [comment]
I ve almost no access to the net until 31th Oct. I can't test before 1st week of Nov.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12304">issues.joomla.org/tracker/joomla-cms/12304</a>.</sub>

**Comment by jsubri** [comment]
A significant clean-up went into the 3.6.4 script.php, I only confirm 3 files from your list
'/libraries/joomla/github/users.php',
'/media/system/js/validate-jquery-uncompressed.js',
'/templates/beez3/html/message.php',

You can add the below 2 files that are part of the 3.2.3 build date “2014-03-06” and no longer exist.
‘/libraries/fof/platform/joomla.php’,
‘/libraries/fof/readme.txt’,

**Comment by AlexRed** [comment]
Thanks jsubri for the info, new PR https://github.com/joomla/joomla-cms/pull/12802 
Now I close this.

**Pull request closed without merging**
