### PR TITLE
Composer update 

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

composer update --no-dev

Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading joomla/archive (1.1.8 => 1.1.10)
  - Upgrading joomla/filter (1.4.3 df3403c => 1.4.3 ec95176)
  - Upgrading leafo/lessphp (dev-joomla3-php8 1bddadb => dev-joomla3-php8 a149187)
  - Upgrading psr/log (1.1.3 => 1.1.4)

### Testing Instructions

Make sure the following packages still work:
- joomla/filter
- lessphp (generation of less files from within the template manager)
- joomla/archive (upload + install an extension)
- psr/log

### Actual result BEFORE applying this Pull Request

non up-to-date packages

### Expected result AFTER applying this Pull Request

up-to-date packages

### Documentation Changes Required

none

@brianteeman that should look better now.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looking at the changed files in this pr there are no changes in the leafo/lessphp files

**Comment by zero-24** [comment]
Yes cause the last commit to that repo is a file (Readme; https://github.com/joomla-backports/lessphp/pull/6) thats not included in the packaged build here from my understanding.

**Comment by brianteeman** [comment]
I can see the composer lock changes so thats ok

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
@zero-24 did you tested this pr? because it seems autoloader is broken. the file `platform_check.php` is missing

**Comment by zero-24** [comment]
I have just run the mentiond command to see that i have not an broken composer update again. I have not yet tested the changes itself. While i'm supprised when that file does not exist cause i have 'just' updated the packages and not changed something internal within composer atleast not intentional.

**Comment by HLeithner** [comment]
yeah it's a bit tricky, it seems you missed to add the new files that composer added. I created the #34659 pr and hopefully it will fix it.

**Comment by chrisdavenport** [comment]
I'm not seeing platform_check.php in that PR.  All our automated tests are currently failing because that file is missing.

**Comment by HLeithner** [comment]
@chrisdavenport as mentioned above https://github.com/joomla/joomla-cms/pull/34659 fixes this issue

**Comment by chrisdavenport** [comment]
Thanks @HLeithner I can confirm that it does indeed fix the issue.

**Comment by zero-24** [comment]
> yeah it's a bit tricky, it seems you missed to add the new files that composer added. I created the #34659 pr and hopefully it will fix it.

Thanks sorry for creating that mess..

**Pull request merged**
