### PR TITLE
[4.1] Remove unnecessary text

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
This option is under the Advanced tab so it would imply that it is an advanced option. Removing text that adds no value.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 669912606467938e4a0bf507b6945711dc437cc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36721">issues.joomla.org/tracker/joomla-cms/36721</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 669912606467938e4a0bf507b6945711dc437cc2<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36721">issues.joomla.org/tracker/joomla-cms/36721</a>.</sub>

**Comment by tecpromotion** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36721">issues.joomla.org/tracker/joomla-cms/36721</a>.</sub>

**Comment by richard67** [comment]
@tecpromotion You don't have the power to set RTC 😛

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36721">issues.joomla.org/tracker/joomla-cms/36721</a>.</sub>

**Comment by tecpromotion** [comment]
not yet @richard67 :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36721">issues.joomla.org/tracker/joomla-cms/36721</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
