### PR TITLE
Add Bootstrap 3 alert-link class

### PR DESCRIPTION
**Pull request by mbabker**
Partial Pull Request for Issue #10604
#### Summary of Changes

Adds support for the Bootstrap 3 `alert-link` class to make links stand out more and implement it in the Install from Web alert
#### Testing Instructions

Apply the patch and navigate to `administrator/index.php?option=com_installer`; note that the links stand out more now.

Before:
screen shot 2016-05-30 at 11 50 39 am

After:
screen shot 2016-05-30 at 11 50 55 am

### CODE REVIEW

**Comment by zero-24** [comment]
@mbabker maybe we want to add it to the download message at com_joomlaupdate here too? (as that was the point that got reported)

The state now works as expected

**Comment by mbabker** [comment]
It wasn't my intent to review every use of an alert and add the class, just adding it in one spot to make it easy to demonstrate.  If accepted, then the work to go through and make the changes can begin.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 8d69485493162e7cc0ea98e8c00f86586f0da1f6<br /><br />The links in the Install from Web are regular light blue links, after applying the patch the links are now bold and stand out more.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10678">issues.joomla.org/joomla-cms/10678</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8d69485493162e7cc0ea98e8c00f86586f0da1f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10678">issues.joomla.org/joomla-cms/10678</a>.</sub>

**Comment by brianteeman** [comment]
Rtx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10678">issues.joomla.org/joomla-cms/10678</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot can we have your helping hand here too?

**Pull request merged**
