### PR TITLE
[4] s/cachtimeout/cachetimeout

### PR DESCRIPTION
**Pull request by PhilETaylor**
[4] s/cachtimeout/cachetimeout

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de8043b279ecadae971d09859274611f9f92a00e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35346">issues.joomla.org/tracker/joomla-cms/35346</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on de8043b279ecadae971d09859274611f9f92a00e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35346">issues.joomla.org/tracker/joomla-cms/35346</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35346">issues.joomla.org/tracker/joomla-cms/35346</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor Why the "[3]" in the title? isn't it for 4?

**Comment by PhilETaylor** [comment]
copy and paste error :)

**Comment by PhilETaylor** [comment]
Closing for https://github.com/joomla/joomla-cms/pull/35348 then that can upmerge

**Pull request closed without merging**
