### PR TITLE
Arc pull request 2015-02-03 (SQL Server query fixes)

### PR DESCRIPTION
**Pull request by pmorrisarctg**
Fixed the default SQL Server (Azure) popular tags module data to use “order_by”:”title” instead of “order_by”:”count” as count in this query is being used as a variable and SQL server will not GROUP BY a non-explicit column name.

Changed the getList function in helper.php for modules/mod_articles_archive to use explicit columns for the GROUP BY clause.  Created_year and created_month are not explicit column names in this query for SQL Server.

### CODE REVIEW

**Comment by waader** [comment]
I am unable to test this patch because as soon as I publish mod_popular_tags I get an sql error no matter if I have applied the patch or not.

 [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'count'.SQL=SELECT MAX([tag_id]) AS tag_id, COUNT(*) AS count,MAX(t.title) AS title,MAX([t].[access]) AS access,MAX([t].[alias]) AS alias , ROW_NUMBER() OVER (ORDER BY [count] DESC) AS RowNumber FROM [trko9_contentitem_tag_map] AS [m] INNER JOIN [trko9_tags] AS [t] ON [tag_id] = t.id INNER JOIN [trko9_ucm_content] AS [c] ON [m].[core_content_id] = [c].[core_content_id] WHERE [t].[access] IN (1,5,1) AND [t].[published] = 1 AND [m].[type_alias] = [c].[core_type_alias] AND [c].[core_state] = 1 AND ([c].[core_publish_up] = '1900-01-01 00:00:00' OR [c].[core_publish_up] <= '2015-02-04 10:52:14') AND ([c].[core_publish_down] = '1900-01-01 00:00:00' OR [c].[core_publish_down] >= '2015-02-04 10:52:14') GROUP BY [tag_id],[title],[access],[alias] 

The formated sql statement for better view:
```
SELECT 
	MAX([tag_id]) AS tag_id, 
	COUNT(*) AS count,
	MAX(t.title) AS title,
	MAX([t].[access]) AS access,
	MAX([t].[alias]) AS alias, 
	ROW_NUMBER() OVER (ORDER BY [count] DESC) AS RowNumber 
FROM 
	[trko9_contentitem_tag_map] AS [m] INNER JOIN 
	[trko9_tags] AS [t] ON [tag_id] = t.id INNER JOIN 
	[trko9_ucm_content] AS [c] ON [m].[core_content_id] = [c].[core_content_id] 
WHERE 
	[t].[access] IN (1,5,1) AND 
	[t].[published] = 1 AND 
	[m].[type_alias] = [c].[core_type_alias] AND 
	[c].[core_state] = 1 AND 
	([c].[core_publish_up] = '1900-01-01 00:00:00' OR 
	[c].[core_publish_up] <= '2015-02-04 10:52:14') AND 
	([c].[core_publish_down] = '1900-01-01 00:00:00' OR 
	[c].[core_publish_down] >= '2015-02-04 10:52:14') 
GROUP BY [tag_id],[title],[access],[alias] ```

If I would change the line
	ROW_NUMBER() OVER (ORDER BY [count] DESC) AS RowNumber 
to
	ROW_NUMBER() OVER (ORDER BY [title] DESC) AS RowNumber 
then the error would disappear.

But I don´t know if these makes sense.

**Comment by pmorrisarctg** [comment]
Thank your for the test and yes this does make sense. The change you made should be in this pull request. The sample data needs to be updated as well as 'count' is in the default data to build the order_by clause and we switched to 'title' for now. See ["order_value":"title"] in the  installation/sql/sqlazure/sample_blog.sql and  installation/sql/sqlazure/sample_data.sql files

This breaks in MSSQL.Was this tried with a fresh install or repo pull from the php files only?

Patrick.

+INSERT [#__modules] ([id], [title], [note], [content], [ordering], [position], [checked_out], [checked_out_time], [publish_up], [publish_down], [published], [module], [access], [showtitle], [params], [client_id], [language]) VALUES (89, 'Popular Tags', '', '', 1, 'position-7', 0, '1900-01-01 00:00:00', '1900-01-01 00:00:00', '1900-01-01 00:00:00', 1, 'mod_tags_popular', 1, 1, '{"maximum":"8","timeframe":"alltime","order_value":"title","order_direction":"1","display_count":0,"no_results_text":"0","minsize":1,"maxsize":2,"layout":"_:default","moduleclass_sfx":"","owncache":"1","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*');

**Comment by waader** [comment]
This was done with the lasted staging branch. So a bit more current then the beta2 version.

**Comment by pmorrisarctg** [comment]
It looks like the branch passed the CI build but it has not been merged into the current staging branch. Did you pull the data from the staging branch or our pull request? The data change is only in this pull request now and not in staging currently. thanks. Patrick

**Comment by waader** [comment]
I did it from staging.

**Comment by ArcTechnologyGroupJacobi** [comment]
You need to pull the dataset from pmorrisarctg:staging not joomla:staging. This works for me.

**Comment by waader** [comment]
@ArcTechnologyGroupJacobi What version of mssql are you using?

**Comment by ArcTechnologyGroupJacobi** [comment]
MS SQL 2008/12/14

**Comment by ArcTechnologyGroupJacobi** [comment]
Any updates on this?

**Comment by waader** [comment]
Well I installed the staging branch from pmorrisarctg and that worked. I hadn´t time to find out what went wrong when applying the patch to joomla:staging. To mark this as successfully it must work with joomla:staging.

**Comment by pmorrisarctg** [comment]
A few quick questions. 

1. Was our pull request added to the staging branch prior to testing? 
2. The test will require a new database as the test data scripts have been updated as well. Was this with a new DB installation or only patching the PHP files?

Thank you, Patrick

**Comment by waader** [comment]
I downloaded the staging branch from https://github.com/pmorrisarctg/joomla-cms and installed in a new db with the "test data sample".

**Comment by pmorrisarctg** [comment]
And that worked correct?

**Comment by waader** [comment]
Well, the popular tags modul is display. In contrast, when I apply your patch to joomla staging I get the above error message. 

joomla_popular_tags

The test data certainly needs some adjustments, as no article is display when clicking on any of the popular tags.

**Comment by pmorrisarctg** [comment]
The core Joomla staging branch will not have the needed sample data updates we had applied to our pull request. So this may not be a real-world test. Unless you are using a merged Joomla Staging (has our changes merged) along with the sample data from our pull request.

Thanks again. Patrick

**Comment by pmorrisarctg** [comment]
The 'sample data' is being used for field names for sorting. So the sample data (prior to our update) is platform dependent.

**Comment by pmorrisarctg** [comment]
Try this installation path as you will need the updated data set.

1. Download Joomla staging branch.
2. Apply all of our patches. PHP and SQL files with updated sample data prior to installation over the Joomla staging clone.
3. Run the installation.
4. Test.

This will be a test of our pull request 'merged' into core staging.

Regards,
Patrick

**Comment by waader** [comment]
@test works! Thanks Patrick!

**Comment by pmorrisarctg** [comment]
Great news! Thank you for testing. Patrick

**Comment by waader** [comment]
@pmorrisarctg I just open this issue: #6160

Maybe you could have a look at this problem.

**Comment by ArcTechnologyGroupJacobi** [comment]
Why was this PR not merged into 3.4?

**Comment by waader** [comment]
@ArcTechnologyGroupJacobi: Maybe it would help if you could mark your test as successful in the issue tracker at http://issues.joomla.org/tracker/joomla-cms/5959.

**Comment by ArcTechnologyGroupJacobi** [comment]
Thanks. Submitted as successful.








ARC TECHNOLOGY GROUP

open solutions driving business success




Robert Jacobi, president

+1 312-212-8600 office
+1 847-687-5860 mobile

440 North Wells Street, #600

Chicago, IL 60654





www.arctg.com
www.twitter.com/arctg




Joomla on Azure

**Comment by zero-24** [comment]
Thanks for testing and coding. Moving to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5959">issues.joomla.org/joomla-cms/5959</a>.</sub>

**Comment by phproberto** [comment]
Sorry @pmorrisarctg this is not mergeable anymore. Can you update it vs the latest staging so it can go into v3.4.1 ? 

Thanks!

**Comment by mbabker** [comment]
@pmorrisarctg and @ArcTechnologyGroupJacobi I was able to extract out the one line that changed in the sample_testing.sql file and commit the diff (it looks like something caused GitHub to show the full file had changed which wasn't helping with the conflicts).  https://github.com/joomla/joomla-cms/commit/dc38dfe9261803088530ba9064e0272d81f01a22 has the committed changes and should be in the 3.4.1 release.

**Comment by Erftralle** [comment]
Sorry, but the changes regarding to the SQL query in ```getList()``` of the **mod_articles_archive** do not work. The module output is full of duplicate entries and the ordering is not correct. See #6263 for more information, which is a pull request for issue #6246.

**Pull request closed without merging**
