### PR TITLE
[4.1] Unification of the language com_scheduler, part 2

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

During the translation into German, further strings were unified to form the core.

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7b8b11817716b933a2d3ce841eebe23ee9eb55b3<br /><br />Thanks for these. I did spot them earlier but I would have been creating conflict hell for myself at the time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36296">issues.joomla.org/tracker/joomla-cms/36296</a>.</sub>

**Comment by tecpromotion** [comment]
> I have tested this item ✅ successfully on [7b8b118](https://github.com/joomla/joomla-cms/commit/7b8b11817716b933a2d3ce841eebe23ee9eb55b3)Thanks for these. I did spot them earlier but I would have been creating conflict hell for myself at the time
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36296](https://issues.joomla.org/tracker/joomla-cms/36296).

I think there are more not-so-good lines of text in this new component that deviate from the core and the other extensions. I'll try my best during translation and then do PRs for the core.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7b8b11817716b933a2d3ce841eebe23ee9eb55b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36296">issues.joomla.org/tracker/joomla-cms/36296</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36296">issues.joomla.org/tracker/joomla-cms/36296</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 7b8b11817716b933a2d3ce841eebe23ee9eb55b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36296">issues.joomla.org/tracker/joomla-cms/36296</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
