### PR TITLE
Make default CODEMIRROR parameter values in PHP equal to the default parameter values in XML

### PR DESCRIPTION
**Pull request by n9iels**
This PR is a replaces #7653 
## The problem

The default values of the codemirror parameters defined in the PHP file are not equal to the default values of the parameters defined in the XML file. The result of this is that on a new installation the active line is highlighted but the XML parameter is set to "no".
## Changes
- Set the default values in the XML file equal to the PHP file
- Apply the Joomla! Codestyle for XML files
## How to test

Just confirm that the all the parameters are working correct. The only thing that is changed are the default values of the XML parameters.

### CODE REVIEW

**Comment by brianteeman** [comment]
What happens on a site update. Are the "wrong" params still in the database?

**Comment by n9iels** [comment]
The only changes I made are the `default` values in the XML file. These values are only applied when the parameters are not in the database or if they are empty.

So on a site update the current configuration of the parameters will be untouched.

**Comment by brianteeman** [comment]
Which means that it doesn't fix existing sites ?

**Comment by mbabker** [comment]
Historically updates haven't touched sites' existing configs unless
absolutely necessary.

**Comment by n9iels** [comment]
That determines on what you call "wrong" parameters. Keep in mind there are no problems with the current parameters. The only thing is that when you save the parameters of a new site (a site where the parameters of Codemirror are never saved before) the configuration change after save.

Example:
in the PHP file the following parameter is configured `$this->params->get('activeLine', true)` but the XML says this:
```
<field
	name="activeLine"
	type="radio"
	class="btn-group btn-group-yesno"
	default="0"
	filter="options"
	description="PLG_CODEMIRROR_FIELD_ACTIVELINE_DESC"
	label="PLG_CODEMIRROR_FIELD_ACTIVELINE_LABEL"
	>
	<option value="1">JON</option>
	<option value="0">JOFF</option>
</field>
```
If the parameters are not in the database the active line will be highlighted, because this is the default value. When open the plugin settings of code mirror the setting for

**Comment by brianteeman** [comment]
Updated title to show it is for codemirror<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10286">issues.joomla.org/joomla-cms/10286</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 84cfc32fa58d363106f17b9ce2b451c1a2b10ec3<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10286">issues.joomla.org/tracker/joomla-cms/10286</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@n9iels shouldn't his PR updatet cause Install shows 3.6 Look?

**Comment by n9iels** [comment]
@franz-wohlkoenig update date now

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1cd5ad78fe939479b168fe9cf48b553fdaf942b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10286">issues.joomla.org/tracker/joomla-cms/10286</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@AlexRed can you please retest?

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 1cd5ad78fe939479b168fe9cf48b553fdaf942b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10286">issues.joomla.org/tracker/joomla-cms/10286</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@n9iels could you merge staging into your PR and ping me so I can merge it, thanks.

**Pull request merged**
