### PR TITLE
[4.0] No jQuery

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Various simple jQuery conversions

### Testing Instructions
Review the code

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 5c0f2294592b13532a177e0dc06c5bc775d423c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23416">issues.joomla.org/tracker/joomla-cms/23416</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on 5c0f2294592b13532a177e0dc06c5bc775d423c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23416">issues.joomla.org/tracker/joomla-cms/23416</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23416">issues.joomla.org/tracker/joomla-cms/23416</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
