### PR TITLE
Improvement to updatenotification plugin language strings

### PR DESCRIPTION
**Pull request by infograf768**
See: https://github.com/joomla/joomla-cms/issues/8285

What this basically does:
— Normalise the description constant to `PLG_SYSTEM_UPDATENOTIFICATION_XML_DESCRIPTION`
— Corrects the tip for the Language field to:

> PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto (default), the update notification email to Super Users may be in the logged in user's front-end language or, if a user is not logged in, in the default site language of the page at the time the plugin is triggered.`<br />`This can create confusion on sites where multiple languages are installed (multi-language sites or not): the language of the page loaded when the plugin is triggered may be one the Super User receiving the email doesn't speak. By selecting a language here you are forcing the update notification emails to be sent in this specific language."`

--Corrects the email body message to obtain nicer newlines
One will now get (this capture shows the message when \n are changed to returns:
screen shot 2015-11-07 at 11 59 27

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry I have to disagree with this. The content you have added is correct but it belongs in documentation off site and not in a tooltip or on a web page. We dont have such detailed text for everything else which covers all possible explanations and scenarios.

**Comment by infograf768** [comment]
@brianteeman 
This one is extremely important. Please compare with former one which was wrong.
>PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto (default), the update notification email to Super Users will be in the logged in user's front-end language at the time the plugin is triggered. In multi-language sites this can create confusion: the user's language may be one the Super User receiving the email doesn't speak. By selecting a language here you are forcing the update notification emails to be sent in this specific language."

**Comment by infograf768** [comment]
@brianteeman
We could also simplify more this way:
>PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto (default), the update notification email to Super Users will be in the site language of the page displayed at the time the plugin is triggered.<br />On sites where multiple languages are installed (multilingual sites or not): the language of the page loaded may be one the Super User receiving the email doesn't speak. By selecting a language here you are forcing the update notification emails to be sent in this specific language."
What do you think?

**Comment by brianteeman** [comment]
How about even simpler

PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto
(default), the update notification email to Super Users will be in the site
language at the time the plugin is triggered.
By selecting a language here you are forcing the update notification emails
to be sent in this specific language."

On 8 November 2015 at 08:20, infograf768 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> We could also simplify more this way:
>
> PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto
> (default), the update notification email to Super Users will be in the site
> language of the page displayed at the time the plugin is triggered.
> On sites where multiple languages are installed (multilingual sites or
> not): the language of the page loaded may be one the Super User receiving
> the email doesn't speak. By selecting a language here you are forcing the
> update notification emails to be sent in this specific language."
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8315#issuecomment-154788901>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
@brianteeman 
Your proposal, I think, is missing the necessary explanation of the simple reason why one should choose a specific language instead of Auto on some sites. After all, my last proposal above is only one line more.

**Comment by Bakual** [comment]
Imho, the one Brian proposed is clear enough and simple to understand. To me it would be clear that "the site language at the time the plugin is triggered." may not be my preferred language.

**Comment by infograf768** [comment]
OK, OK... Modification done. Let's get this i.n

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on a3ee5c318cd9cefd9b0ec8eff0fc720234256757<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8315">issues.joomla.org/joomla-cms/8315</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8315">issues.joomla.org/joomla-cms/8315</a>.</sub>

**Pull request merged**
