### PR TITLE
Update script.php: Removing old fof scripts

### PR DESCRIPTION
**Pull request by sovainfo**
The introduction of fof in core didn't cater for old installations of the library. The scripts in the top level folder conclict with the proper working of core extensions based on fof.

### CODE REVIEW

**Comment by wilsonge** [comment]
I think we considered this in the past. But because often people did have such an old version of akeeba products installed things still got broken on their site because the FOF files no longer existed. I dunno whether @nikosdion can remember better than me.

**Comment by zero-24** [comment]
@wilsonge This: https://github.com/joomla/joomla-cms/pull/2519 Is the PR by @nikosdion that you mean.

**Comment by nikosdion** [comment]
This PR is correct. What @sovainfo means is this scenario:

You have an old Joomla! 1.6/1.7/2.5/3.0/3.1 site where FOF 1.x is installed. When you upgrade to Joomla! 3.2 or later the old FOF 1.x files exist in the libraries/fof folder along with the FOF 2.4 files. Due to the legacy mode in the FOF autoloader the FOF 1.x classes take precedence over FOF 2.4 causing the FOF-based components to crash.

This PR is absolutely correct and fairly trivial. @wilsonge please merge it. This is a serious problem for people upgrading from very old versions of Joomla! using *very* old versions of FOF-based components and the solution here is very simple and absolutely correct.

**Comment by wilsonge** [comment]
I remember the scenario. I just thought that people with those old akeeba products had sites break as FOF no longer existed.

Doesn't matter anyhow. You're the boss in this regard!! merged

**Comment by nikosdion** [comment]
:+1:

**Comment by sovainfo** [comment]
Thank you both!

**Pull request merged**
