### PR TITLE
[libraries][legacy][request] - fix php 7.1 warning not numeric

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #19695 .

### Summary of Changes
cast to integer

### Testing Instructions
see #19695

### CODE REVIEW

**Review by rotech1 — APPROVED** [review]
successfully tested

**Comment by Quy** [comment]
@rotech1 Please do the following to mark your test as successful:

* Open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19710)
* Log in with your Github account
* Click on blue `Test this` button above author's photo
* Mark your test as `Tested successfully`
* Click `Submit test result`

**Comment by rotech1** [comment]
I have tested this item :white_check_mark: successfully on 3f0a5f8cd2caccf1eaf22c938e27aac40b487492<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19710">issues.joomla.org/tracker/joomla-cms/19710</a>.</sub>

**Comment by Quy** [comment]
I couldn't reproduce the warnings without this PR. 

How about adding the following code at the top of the method so you don't have to cast it 3 times?
`$mask = (int) $mask;`

**Comment by alikon** [comment]
to reproduce the warnings https://github.com/joomla/joomla-cms/issues/19695#issuecomment-366332553

thanks for the dry tip :+1:

**Comment by Quy** [comment]
@rotech1 Please retest.

@alikon I still can't reproduce the warnings with PHP 7.1.13.

**Comment by alikon** [comment]
@Quy me neither, code review ?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44dfbcdb13257b1eee0a0cd11dfabcdf0a65c135<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19710">issues.joomla.org/tracker/joomla-cms/19710</a>.</sub>

**Comment by rotech1** [comment]
I have tested this item :white_check_mark: successfully on 44dfbcdb13257b1eee0a0cd11dfabcdf0a65c135<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19710">issues.joomla.org/tracker/joomla-cms/19710</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19710">issues.joomla.org/tracker/joomla-cms/19710</a>.</sub>

**Pull request merged**
