### PR TITLE
Code review on admin com_banners component

### PR DESCRIPTION
**Pull request by mbabker**
This PR is a general overview and cleanup of some code structure and doc blocks in the admin com_banners component. Changes of note:
- Doc blocks cleaned up some to follow standard
- Return the results of the view's `display()` methods to be consistent with the documented return
- Not using variables for items only referenced once
- Use `Joomla\Utilities\ArrayHelper` instead of `JArrayHelper`
### Testing Instructions

The admin com_banners component should continue to function correctly

### CODE REVIEW

**Comment by coolman01** [comment]
I have tested this item :white_check_mark: successfully on d3e2c828143e7ee845787fadbbaaad77eb6a2866<br /><br />created banner
created customer
created module
published all
all tests including banner click successful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8080">issues.joomla.org/joomla-cms/8080</a>.</sub>

**Comment by widmann-it** [comment]
is working

**Comment by SniperSister** [comment]
2 successful tests, setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8080">issues.joomla.org/joomla-cms/8080</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @mbabker and testers! Merged.

**Pull request merged**
