### PR TITLE
Some code clean-up in Tags

### PR DESCRIPTION
**Pull request by smz**
#### Description

This PR extends #5449 by @okonomiyaki3000 (thanks!) by also removing a duplicated method, and identifying the nature of the problem.
#### Test instructions:

There are no specific test instructions: this is just code clean-up, but it would be advisable to test that nothing is broken in Tags (setting, deleting, selecting, batch processing)

~~Perform a batch "Set tag" operation on categories~~
#### ~~Expected result:~~

~~Tags are set~~
### ~~Actual result:~~

~~Tags are not set~~
### ~~The fix:~~

~~Apply this PR and repeat the above: tags will be set~~

### CODE REVIEW

**Comment by rmittl** [comment]
I didn't apply the patch and the batch to add a new tag to categories is working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5459">issues.joomla.org/joomla-cms/5459</a>.</sub>

**Comment by asysta** [comment]
i didnt apply the patch too, add tags ist working without the patch.

**Comment by okonomiyaki3000** [comment]
You guys are missing the point. This patch extends #5449. That patch fixes a typo which exposes a bug in the batch operation. This patch fixes that bug.

**Comment by smz** [comment]
Since this PR is lingering since about 5 months I decided to give it a new look and see if it was still actual.

After a thorough code review I can say it is still valid but it needs to be re-purposed: there was no "*issue*" to fix, but the code introduced by @okonomiyaki3000 and myself was anyway good.

--------
Let's separately analyse the two modifications introduced by this PR:
 1. correct the test inside an `if () ...` statement (@okonomiyaki3000)
 2. eliminate a duplicate method from an extended class (@smz)

1.) the function of the code inside the botched `if` in `JHelperTags::postStoreProcess()` should be  to "*Delete all tags data*" if no `$newTags = array()` are passed **and** the `$replace = true` is TRUE.

The affected method is called either directly or through the `JTableObserverTags::setNewTags()` method.

As the botched test is affected only in case of $replace being FALSE (and its default value is TRUE) we should concentrate on cases where it is either explicitly set to FALSE or can assume that value. 

`JHelperTags::postStoreProcess()` by itself is always called without expressing the $replace parameter which then assumes the TRUE value by default and hence the botched test is not affected (good!).

`setNewTags()`, on the contrary is always called  with its $replaceTags parameter set to FALSE and then passses it down to `JHelperTags::postStoreProcess()` as $replace. These, thus, can be affected cases.

**But** `setNewTags()` is called only inside the two `batchTag($value, $pks, $contexts)` methods - one in `JModelAdmin` and the second in `CategoriesModelCategory` (which is an extended class of `JModelAdmin`) - and I'm pretty sure that in those cases (we are batch processing tags...) the $newTags **is** populated, and thus the the botched test is not affected here as well.

At the end of the story, the botched test doesn't practically affects any operation: it could only in case JHelperTags::postStoreProcess() would be called with the intention of deleting all tags data, which doesn't happens right now in our code. In any case my personal opinion is that it is correct the botched test.

2.) Easy: we have the very same method verbatim duplicated in an extended class: or simplicty and code "cleanness", it should be eliminated from the extended class.

-------

Now, as my original description was absolutely wrong (and test instructions were wrong as well...), I'm going to fix PR title and description.

I hope this help...

**Comment by okonomiyaki3000** [comment]
Yay

**Pull request closed without merging**
