### PR TITLE
[4][com_actionlog] export csv untranslated key

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #43460 .

### Summary of Changes
load actionlog lang plugin

### Testing Instructions
Export the user action logs to a csv file and the view the file

### Actual result BEFORE applying this Pull Request
untranslated 

### Expected result AFTER applying this Pull Request
translated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b05c0cad949b43c1116e01a936b5031dc1267cf7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43464">issues.joomla.org/tracker/joomla-cms/43464</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b05c0cad949b43c1116e01a936b5031dc1267cf7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43464">issues.joomla.org/tracker/joomla-cms/43464</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43464">issues.joomla.org/tracker/joomla-cms/43464</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
