### PR TITLE
[4.0] Frontend editing is not inline editing

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
The label inline editing is wrong. Inline editing is not having buttons to open an edit form.

### Testing Instructions
Code review, or see the label on Global cofniguration.

### CODE REVIEW

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 30c0bb97c9f0aee78c866aa26a7ce0493efedf90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32552">issues.joomla.org/tracker/joomla-cms/32552</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 30c0bb97c9f0aee78c866aa26a7ce0493efedf90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32552">issues.joomla.org/tracker/joomla-cms/32552</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32552">issues.joomla.org/tracker/joomla-cms/32552</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
