### PR TITLE
[4.0] th scope

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue # .

### Summary of Changes
Change `th` to `td` in `grid.checkall` and 
Add scope in `th`

### Testing Instructions
Code Review

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry this is not correct. It is a cell not a header.

**Comment by rjharishabh** [comment]
> Sorry this is not correct. It is a cell not a header.

I don't understand what you want to say

I changed `th` to `td` because at all other places its `td` for example in articles

**Comment by brianteeman** [comment]
I am saying that this pr is not required. the cell you are changing is not a header. it doesnt contain information relating to the other cells in the column.

**Comment by rjharishabh** [comment]
> I am saying that this pr is not required. the cell you are changing is not a header. it doesnt contain information relating to the other cells in the column.

Or at first place where I change `th` to `td`

**Comment by brianteeman** [comment]
There is nothing to change. This PR should be closed.

**Pull request closed without merging**
