### PR TITLE
[3.9] remove mcrypt check

### PR DESCRIPTION
**Pull request by brianteeman**
We were checking and reporting on the presence of mcrypt. We no longer need to do that as it is no longer a requirement and mcrypt itself is not present in php 7.2 so the checks would fail anyway then.

Didnt see the point in wrapping it in a conditional php version check as we dont need the info any more

See #18169 for the other mcrypt removal

### CODE REVIEW

**Comment by zero-24** [comment]
👍 Thanks @brianteeman

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b7faaab06b69e7d5b0e3417f86c7daef22026faf<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18334">issues.joomla.org/tracker/joomla-cms/18334</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b7faaab06b69e7d5b0e3417f86c7daef22026faf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18334">issues.joomla.org/tracker/joomla-cms/18334</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
