### PR TITLE
[4.4] Joomlaupdate remove br tag from language strings - follow up to PR 42489

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #42489 (follow-up).

### Summary of Changes

With my PR #42489 which just has been merged I have added information about not fulfilled PHP and database requirements to the "No updates" view of the Joomla Update component in case if an update has been found but the environment doesn't fulfil the mentioned requirements for that update.

I've done it like I've seen it elsewhere with a `<br>` tag in language strings to get all text better readable.

But as mentioned by @brianteeman in that PR, html tags should be avoided in language strings.

This PR here now changes that by removing the `<br>` tag from the new language strings added with PR #42489 as well as from the previously existing language string which had been added with PR #42103 once and then modified with my mentioned PR, and it changes the PHP code to prepare the content so that it adds these `<br>` tags.

### Testing Instructions

Same as for PR #42489 , except that this time the actual and the expected result is the same, i.e. there should not be any visual difference without and with the PR applied, the `<br>` tags are still where they should be.

Or just do a code review and make sure that the language strings modified with this PR here are only used by the PHP code modified with this PR here and nowhere else, and that the result regarding the `<br>` tags will be the same as before.

### Actual result BEFORE applying this Pull Request

When the PHP version requirement is not met, an additional sentence shows that, telling the current and the required version.

When the database version requirement is not met, an additional sentence shows that, telling the database type and the current and required versions.

Sentences are separated by `<br>` tags.

### Expected result AFTER applying this Pull Request

Same as actual, no change. But now the `<br>` tags are added in PHP and are not at the end of language strings.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
LGTM by codereview

**Comment by richard67** [comment]
> LGTM by codereview

@brianteeman Could you mark a test result in the issue tracker?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f38a0b514e668e02f632f3c18d40b3aa6954709f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42550">issues.joomla.org/tracker/joomla-cms/42550</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on f38a0b514e668e02f632f3c18d40b3aa6954709f<br /><br />I have done a code review. The <br>-tags have been removed from the language strings and inserted in the PHP code. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42550">issues.joomla.org/tracker/joomla-cms/42550</a>.</sub>

**Comment by richard67** [comment]
Thanks all for testing/reviews.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
