### PR TITLE
PHP8.1 Deprecation string in trim in banners

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue [#36623 .](https://github.com/joomla/joomla-cms/issues/36623)

### Summary of Changes

ensure sensible default before passing to trim()

### Testing Instructions

Code review

### Actual result BEFORE applying this Pull Request

Deprecation notice

### Expected result AFTER applying this Pull Request

No deprecation notice.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ab87c11e88a9900882e81a216149ef78799ef88e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36625">issues.joomla.org/tracker/joomla-cms/36625</a>.</sub>

**Comment by alikon** [comment]
should be merged on  j4 too

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on ab87c11e88a9900882e81a216149ef78799ef88e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36625">issues.joomla.org/tracker/joomla-cms/36625</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36625">issues.joomla.org/tracker/joomla-cms/36625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
