### PR TITLE
fixed 12953 - Removed methods from JLanguage to JLanguageHelper 

### PR DESCRIPTION
**Pull request by yasirunilan**
Pull Request for Issue # 12953.

### Summary of Changes
Moved methods from JLanguage to JLanguageHelper 

### Testing Instructions
Code Review
### Documentation Changes Required
None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
The deprecated method is already replaced in this PR https://github.com/joomla/joomla-cms/pull/13464

The other are not correct. Also don't exactly know what is your intend here...

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on c945a28963ee7be3407d36230a0fa226d244c0a0<br /><br />Done code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13473">issues.joomla.org/tracker/joomla-cms/13473</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on c945a28963ee7be3407d36230a0fa226d244c0a0<br /><br />This PR is not correct from code review
JLanguageHelper constructor does not generate a JLanguage object.
The remove of deprecated code as already been merged in https://github.com/joomla/joomla-cms/pull/13464<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13473">issues.joomla.org/tracker/joomla-cms/13473</a>.</sub>

**Comment by zero-24** [comment]
I'm closing here do of the reasons @andrepereiradasilva posted above. This change is not correct at this state and the other part is fixed by the other PR allready. Thanks!

**Pull request closed without merging**
