### PR TITLE
Info displayed in Languages: Installed (Site) are taken from admin language xml

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9342.
#### Summary of Changes

See https://github.com/joomla/joomla-cms/issues/9342
#### Testing Instructions

See https://github.com/joomla/joomla-cms/issues/9342

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9344">issues.joomla.org/joomla-cms/9344</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6a9ebc5b52eb5b3ae8c730e877a3e54e149e209c<br /><br />Tested all fields are read from the correct xml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9344">issues.joomla.org/joomla-cms/9344</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6a9ebc5b52eb5b3ae8c730e877a3e54e149e209c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9344">issues.joomla.org/joomla-cms/9344</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on 6a9ebc5b52eb5b3ae8c730e877a3e54e149e209c<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9344">issues.joomla.org/joomla-cms/9344</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9344">issues.joomla.org/joomla-cms/9344</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks

**Pull request merged**
