### PR TITLE
Update jQuery and jQuery Migrate

### PR DESCRIPTION
**Pull request by viocassel**
This PR updates the library jQuery to 1.12.4 and jQuery Migrate to 1.4.1.

### CODE REVIEW

**Comment by JoomliC** [comment]
There's already a PR open about jQuery update : https://github.com/joomla/joomla-cms/pull/9935
;-)

**Comment by mbabker** [comment]
The one that was merged a couple hours ago?

**Comment by JoomliC** [comment]
Yes this one, and i just see it merged.

**Comment by brianteeman** [comment]
However this PR is to an even newer release

**Comment by andrepereiradasilva** [comment]
yes is the newst release of jquery and jquer migrate. See https://jquery.com/download/

**Comment by wilsonge** [comment]
Merged on review

**Comment by zero-24** [comment]
@wilsonge @brianteeman can we get the 3.6.0 milestone here?

**Pull request merged**
