### PR TITLE
[4.0] Match quickicons with new sidebar icons

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #19036

### Summary of Changes

Update the icons so that match the icons in the sidebar

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8ae934d100081fabc559521e60e6a10091f79e1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19037">issues.joomla.org/tracker/joomla-cms/19037</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 8ae934d100081fabc559521e60e6a10091f79e1e

Using Pull Request got different Icons in Sidebar and Quickicon:

bildschirmfoto 2017-12-10 um 18 55 39

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19037">issues.joomla.org/tracker/joomla-cms/19037</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig See PR #19000. You should see the new icons in the sidebar.

**Comment by C-Lodder** [comment]
@franz-wohlkoenig you need to fetch the latest code before testing the PR.

The other PR that changed the sidebar icons got merged a couple of hours ago ;)

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8ae934d100081fabc559521e60e6a10091f79e1e<br /><br />@C-Lodder Thanks for Reminder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19037">issues.joomla.org/tracker/joomla-cms/19037</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
