### PR TITLE
[5.1] Button and link text color issue on focus

### PR DESCRIPTION
**Pull request by sandewt**
Text is not readable on focus

Pull Request for Issue #40306, #41153 and #41172

### Summary of Changes

The Pull Request #40435 for issue #40306, caused the issues #41153 and #41172.
Hopefully this PR will provide the overall solution. Or there is possible a better css solution.

### Testing Instructions

Build: npm ci
Clear the browser cache (historie) after the patch if necessary

- Code review

- see #40306
- see #41153
- see #41172

### Actual result BEFORE applying this Pull Request

The button and the link text is NOT readable on focus.

### Expected result AFTER applying this Pull Request

The button and the link text is always readable on focus.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Thanks @RickR2H

### CODE REVIEW

**Comment by RickR2H** [comment]
@sandewt on reviewing the code I would suggest leaving this code as is. The problem is now only in the header and the footer.

I would suggest changing the following:

build\media_source\templates\site\cassiopeia\scss\blocks\_layout.scss on line: 19

`
a:not(.btn) {
  color: currentColor;

  &:hover,
  &:focus {
    color: var(--gray-200);
  }
}
`

build\media_source\templates\site\cassiopeia\scss\blocks\_footer.scss on line: 15

`
a:not(.btn) {
  color: currentColor;

  &:hover,
  &:focus {
    color: var(--gray-200);
  }
}
`

For testing put the following code in a custom html module and in an article:

`
<a href="#" class="btn btn-primary">Primary</a>
<a href="#" class="btn btn-secondary">Secondary</a>
<a href="#" class="btn btn-success">Success</a>
<a href="#" class="btn btn-danger">Danger</a>
<a href="#" class="btn btn-warning">Warning</a>
<a href="#" class="btn btn-info">Info</a>
<a href="#" class="btn btn-light">Light</a>
<a href="#" class="btn btn-dark">Dark</a>
<a href="#" class="btn btn-link">Link</a>
<a href="#">Default Link</a>
`

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c3051299450fe71d4e2b4d4d6c72db94295fb768<br /><br />Please note that I tested this on Joomla 5.0.0-beta3-dev. And a better command is npm run build:css<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by ceford** [comment]
Also tested on 4.3.5-dev works there too, except the Banner test `Get started` button is white on green both with and without the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by RickR2H** [comment]
@sandewt please consider mty solutions are stated above. https://github.com/joomla/joomla-cms/pull/41749#issuecomment-1720838295

@ceford please create 3 modules. In the banner, footer  and the main-top with the code for all the buttons in my post above.
```
<a href="#" class="btn btn-primary">Primary</a>
<a href="#" class="btn btn-secondary">Secondary</a>
<a href="#" class="btn btn-success">Success</a>
<a href="#" class="btn btn-danger">Danger</a>
<a href="#" class="btn btn-warning">Warning</a>
<a href="#" class="btn btn-info">Info</a>
<a href="#" class="btn btn-light">Light</a>
<a href="#" class="btn btn-dark">Dark</a>
<a href="#" class="btn btn-link">Link</a>
<a href="#">Default Link</a>
```

**Comment by ceford** [comment]
Tested again on 4.3.5-dev and 5.0.0-beta3-dev. I see no difference between the two. The patch fixes the problem with Default links in the footer but not the links with the `btn btn-link` style. In the banner and main-top positions the buttons and link all appear normal. But in the footer the Secondary and Light buttons have invisible text except on hover/focus. Firefox on Mac.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by sandewt** [comment]
> But in the footer the Secondary and Light buttons have invisible text except on hover/focus.

@ceford I can confirm this, see the image. Would you please mark your test as unsuccessful?

errors_issue

**Comment by ceford** [comment]
I have not tested this item.<br /><br />I think the footer button problems make my `successful` test invalid.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by sandewt** [comment]
> I think the footer button problems make my successful test invalid.

At first I thought this too.
But I just ran a test. It turns out that this issue is not caused by pr #40435. In fact, this is a new issue.

**Comment by sandewt** [comment]
> The problem is now only in the header and the footer.

Not correct, also in an acticle

See:https://github.com/joomla/joomla-cms/issues/40420

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c3051299450fe71d4e2b4d4d6c72db94295fb768<br /><br />This PR fixes the problem with links where the background is dark - the `Default Link` in the data set suggested by @RickR2H - so it a Success.

The links styled as buttons is a separate issue - I confirm the problem in positions `below-top` and `footer` but not in an article with a white background. So I assume there will be a separate PR to deal with that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on c3051299450fe71d4e2b4d4d6c72db94295fb768<br /><br />@sandewt Could you make an new PR to fix the colors in the header and the footer with the changes mentioned by me?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by ceford** [comment]
Comment in the Forum that this was not fixed in 4.4!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41749">issues.joomla.org/tracker/joomla-cms/41749</a>.</sub>

**Comment by sandewt** [comment]
> @sandewt Could you make an new PR to fix the colors in the header and the footer with the changes mentioned by me?

> Comment in the Forum that this was not fixed in 4.4!

@RickR2H Thanks for your suggestion. I think others are more skilled at writing the most appropriate code. Partly due to the fact that the PR code was originally intended for J4.4. And there may also be a better solution for this PR.

**Comment by RickR2H** [comment]
@sandewt Maybe better close this ticket and I'll create a new one with all the fixes mentioning this PR.

**Comment by sandewt** [comment]
> @sandewt Maybe better close this ticket and I'll create a new one with all the fixes mentioning this PR.

That seems like a good idea to me. Closed.

**Comment by sandewt** [comment]
Thanks all

**Comment by sandewt** [comment]
Please test #42504

@ceford thanks in advance

**Pull request closed without merging**
