### PR TITLE
Fix `class_exists` checks in `restore_finalisation.php`

### PR DESCRIPTION
**Pull request by nikosdion**
Pull Request for Issue #35297.

### Summary of Changes

Converted the File, Folder and Text classes in the `class_exists` checks into their proper FQN format.

### Testing Instructions

Please see issue #35297

### Documentation Changes Required

None :)

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f5547a7cac682924db6ba7087c74f9b03c7aac57<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35309">issues.joomla.org/tracker/joomla-cms/35309</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on f5547a7cac682924db6ba7087c74f9b03c7aac57<br /><br />Code review only, trusting Nic.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35309">issues.joomla.org/tracker/joomla-cms/35309</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35309">issues.joomla.org/tracker/joomla-cms/35309</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
