### PR TITLE
[4.0] subform repeatable-table cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
~1. continues earlier work by @quy to remove inline styles~
2. changes `th` to `td` for the button column

To test create a new field of type checkboxes or code-review

### CODE REVIEW

**Comment by Quy** [comment]
These custom width classes are available in Atums but not on the frontend.

**Comment by brianteeman** [comment]
ok well to make the pr easier I will remove that part to be handled in another pr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c0aa670d7f52f64a2997c70a1108aa8e50172782<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29919">issues.joomla.org/tracker/joomla-cms/29919</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c0aa670d7f52f64a2997c70a1108aa8e50172782<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29919">issues.joomla.org/tracker/joomla-cms/29919</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29919">issues.joomla.org/tracker/joomla-cms/29919</a>.</sub>

**Pull request merged**
