### PR TITLE
[4.0] Automate build versioning

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

This is only for maintainers, move on

### Summary of Changes

Just adding the CLI command in the build.php. My hope that I would have completed the work on the build process evaporated with the new beta of Bootstrap.

### Documentation Changes Required

@wilsonge you've asked for this one, I should have updated that PR, my bad...

### CODE REVIEW

**Comment by rdeutz** [comment]
@SniperSister or @zero24 can someone have a look rips failed

**Comment by zero-24** [comment]
Mostlikly false positive but will come back here once I looked into the report :-)

**Review by rdeutz — APPROVED** [review]

**Comment by wilsonge** [comment]
I know I said build.php but thinking about it I guess bump.php is the better place? Because this will need to be committed to the repo right with the version bump etc. Sorry to be a pita

**Comment by dgrammatiko** [comment]
> Because this will need to be committed to the repo right with the version bump

Actually, you can't commit this back :( The reason is that the versioning is done in the `media/**/joomla.asset.json` files which are in the exclusion zone. But you shouldn't worry about this as the versioning will invalidate all the files that need a new hash in the next build (the hash is derived by the actual content so we are totally safe here) as long as the process always includes the versioning script per release (which will happen automatically with this PR)

**Comment by zero-24** [comment]
I have restarted drone and fixed the false positive

**Comment by wilsonge** [comment]
Oh yes! I'm being stupid! This is fine then

**Pull request merged**
