### PR TITLE
[Privacy XML export] standardized convention for domain (Redo #22240)

### PR DESCRIPTION
**Pull request by cyrez**
REDO https://github.com/joomla/joomla-cms/pull/22240

Use standardized strings for domain name and description in Privacy request xml export file.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 18faa4c08b31ac849ff3f1bd41c286ffebe2c36f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22253">issues.joomla.org/tracker/joomla-cms/22253</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 18faa4c08b31ac849ff3f1bd41c286ffebe2c36f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22253">issues.joomla.org/tracker/joomla-cms/22253</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22253">issues.joomla.org/tracker/joomla-cms/22253</a>.</sub>

**Comment by mbabker** [comment]
https://docs.joomla.org/J3.x:Integrate_Extensions_with_the_Privacy_Component needs to be updated to reflect the standardization of name/description

**Comment by cyrez** [comment]
Well, someone edited code example before i do ;-)

About details for name and description, maybe to give some insights and recommendation on naming to keep futur usability when xml use programmatically ?

eg by replacing this part: 

> Domain name - A name to identify the domain
> Domain description - A short description of the data contained in the domain

By this: 
> Domain name - A name to identify the domain (lowercase underscore separated string for reusability as a variable) eg "user_galleries"
> Domain description - A short description of the data contained in the domain (lowercase underscore separated string recommended for reusability as a variable) eg "joomla_user_galleries_data"

RTC and if ok, i will update docs.
Note that if for `name`, it seems to me a good idea to use a variable, maybe not mandatory to request the same for description (recommended, but not required ?).

So, open to comments!

**Pull request merged**
