### PR TITLE
[4] Return is unnecessary as the last statement in a void method

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Return is unnecessary as the last statement in a void method

### Testing Instructions

Code review

### CODE REVIEW

**Comment by HLeithner** [comment]
In the catch blocks in plugins/system/redirect/redirect.php  are 2 returns missing. Don't know if they are mean as "early return" at least they are unneeded.

**Comment by PhilETaylor** [comment]
You don't need to return early within a if/elseif/elseif/else block if no code follow the block, as PHP will simply be returning without further processing in that method anyway. 

These are all "Code Smell" as reported by phpStorm.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 75a386ceecc38436cb44531fc0707c55b757e441<br /><br />Saw the code changes - seem OK. But in plugins/system/redirect/redirect.php the removed return is not the last statement in the method. It is the last statement in an if/elseif block. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31051">issues.joomla.org/tracker/joomla-cms/31051</a>.</sub>

**Comment by wilsonge** [comment]
LGTM. Thanks!

**Pull request merged**
