### PR TITLE
[4.0] Fix modal close for pagebreak

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #18733

### Summary of Changes

The modal now closes once you insert a page break into an article

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Nope. This will not work with the tinyMCE modals

**Comment by C-Lodder** [comment]
Do the TinyMCE modals use `jModalClose`?

**Comment by dgrammatiko** [comment]
Yes, because apparently their modals are not booscrap (and why the should be?).

Anyhow there are couple of options here:
- Provide a solid API as I have proposed way back
- Modify the code in the modal section of bootstrap-init.js to expose a `jModalClose` method. But let's not do this, personally I hate global functions...

**Comment by C-Lodder** [comment]
Or just wait till CE?

**Comment by brianteeman** [comment]
CE?

**Comment by C-Lodder** [comment]
The modal custom element. Not idea what the verdict on that is though

**Comment by dgrammatiko** [comment]
The status of the modal custom element is:
- a11y tests passed
- API is not finalised
- we need solution for the sizing (css or js or a combo)
- we need to decide the final html structure of the modal

@C-Lodder we have to organise a meeting this week or the next one to move things forward

**Pull request closed without merging**
