### PR TITLE
Category Manager :: Wrong message after publishing sub-category

### PR DESCRIPTION
**Pull request by kathastaden**
Solved issue from #5596

**The issue:**

If you have a category and a related sub-category and unpublish the category, both get unpublished. If you now publish the sub-category, the message will be "Successful" but the sub-category hasn't been published. This message should be changed.

**The solution:**
1. I needed to create a new language constant, because there was none that could be used. Therefore I created the constant, COM_CATEGORIES_PUBLISHING_NOT_SUCCESSFUL="Publishing was not successful."
2. If a sub-category gets published, there is a check that checks for the related main category and if this one is active. If not, an error is set. The problem was, that there was no check if an error occurred during this process and therefor the error message always said that everything was fine and published. I created a new variable $errors = $model->getErrors(); which will inherit all the errors that are set. After that I also needed to create the check and throw an error.

**How to test:**
- Navigate to Category Manager
- Create a main category
- Create a sub-category that is related to the new main category
- unpublish the main category
- Both main & sub-category will get unpublished
- Click on the sub-category and try to publish and check the message

**Expected Result after solution.** 
An error message will be displayed that the publishing was not successful. 

_Worked as a group on that issue: @icampus, @FPerisa, @flow87 and @xsability_

### CODE REVIEW

**Comment by Preview** [comment]
I have tested this item :white_check_mark: successfully on 931d184d71f05f451f88f8bb799c2f2b0103d94c<br /><br />Test was successful, following the test instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8038">issues.joomla.org/joomla-cms/8038</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 931d184d71f05f451f88f8bb799c2f2b0103d94c<br /><br />Tested according to instruction. Results as expected.

However:

When publishing subcategory in list view, error message appears and subcategory remains unpublished.

When publishing subcategory in detail view, no error message appears and subcategory is published while category is not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8038">issues.joomla.org/joomla-cms/8038</a>.</sub>

**Comment by infograf768** [comment]
I confirm @crommie findings

Also, even modifying the code so that the language string should not be of the type COM_CATEGORIES, I do not think this is the solution to this issue.

I guess the error should be checked and displayed in the category model.

**Comment by infograf768** [comment]
I looked a bit further into this.
We can indeed use libraries/legacy/controller/admin.php to display the right message, but it is necessary to take into account that the error/exception is not only possible for category but also for any extension using nested.
In core this is the case for Menus and Tags.

I propose this:
```
diff --git a/administrator/language/en-GB/en-GB.com_categories.ini b/administrator/language/en-GB/en-GB.com_categories.ini
index f6b6659..08232e7 100644
--- a/administrator/language/en-GB/en-GB.com_categories.ini
+++ b/administrator/language/en-GB/en-GB.com_categories.ini
@@ -59,4 +59,6 @@
 COM_CATEGORIES_N_ITEMS_DELETED="%d categories successfully deleted."
 COM_CATEGORIES_N_ITEMS_DELETED_1="%d category successfully deleted."
+COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING="Failed publishing %d categories"
+COM_CATEGORIES_N_ITEMS_FAILED_PUBLISHING_1="Failed publishing %d category"
 COM_CATEGORIES_N_ITEMS_PUBLISHED="%d categories successfully published."
 COM_CATEGORIES_N_ITEMS_PUBLISHED_1="%d category successfully published."
diff --git a/administrator/language/en-GB/en-GB.com_menus.ini b/administrator/language/en-GB/en-GB.com_menus.ini
index 57eba66..64997f9 100644
--- a/administrator/language/en-GB/en-GB.com_menus.ini
+++ b/administrator/language/en-GB/en-GB.com_menus.ini
@@ -144,4 +144,6 @@
 COM_MENUS_N_ITEMS_DELETED="%d menu items successfully deleted."
 COM_MENUS_N_ITEMS_DELETED_1="%d menu item successfully deleted."
+COM_MENUS_N_ITEMS_FAILED_PUBLISHING="Failed publishing %d menu items"
+COM_MENUS_N_ITEMS_FAILED_PUBLISHING_1="Failed publishing %d menu item"
 COM_MENUS_N_ITEMS_PUBLISHED="%d menu items successfully published."
 COM_MENUS_N_ITEMS_PUBLISHED_1="%d menu item successfully published."
diff --git a/administrator/language/en-GB/en-GB.com_tags.ini b/administrator/language/en-GB/en-GB.com_tags.ini
index 281167c..015fb6e 100644
--- a/administrator/language/en-GB/en-GB.com_tags.ini
+++ b/administrator/language/en-GB/en-GB.com_tags.ini
@@ -106,4 +106,6 @@
 COM_TAGS_N_ITEMS_DELETED="%d tags successfully deleted."
 COM_TAGS_N_ITEMS_DELETED_1="%d tag successfully deleted."
+COM_TAGS_N_ITEMS_FAILED_PUBLISHING="Failed publishing %d tag"
+COM_TAGS_N_ITEMS_FAILED_PUBLISHING_1="Failed publishing %d tags"
 COM_TAGS_N_ITEMS_PUBLISHED="%d tags successfully published."
 COM_TAGS_N_ITEMS_PUBLISHED_1="%d tag successfully published."
diff --git a/libraries/legacy/controller/admin.php b/libraries/legacy/controller/admin.php
index 0aee760..015feee 100644
--- a/libraries/legacy/controller/admin.php
+++ b/libraries/legacy/controller/admin.php
@@ -209,7 +209,16 @@
 				$model->publish($cid, $value);
 
+				$errors = $model->getErrors();
+
 				if ($value == 1)
 				{
-					$ntext = $this->text_prefix . '_N_ITEMS_PUBLISHED';
+				if (!empty($errors))
+					{
+						$ntext = $this->text_prefix . '_N_ITEMS_FAILED_PUBLISHING';
+					}
+					else
+					{
+						$ntext = $this->text_prefix . '_N_ITEMS_PUBLISHED';
+					}
 				}
 				elseif ($value == 0)
```
This would work when using the list display and has the advantage of being able to customise the message per extension.

The exception is thrown line 991 of ~ROOT/libraries/joomla/table/nested.php
```
				if (!empty($rows))
				{
					$e = new UnexpectedValueException(
						sprintf('%s::publish(%s, %d, %d) ancestors have lower state.', get_class($this), $pks, $state, $userId)
					);
					$this->setError($e);

					return false;
				}
```
If we want to prevent publishing the subcategory when we edit its details and throw a specific message, I guess this should be done in the save method for the category model (menu and tags too).

What do you think?

**Comment by infograf768** [comment]
@brianteeman 
Would the string values I proposed above fit OK in en-GB?

**Comment by brianteeman** [comment]
@infograf768 the strings need to follow the style guide. So they need a
period at the end

**Comment by infograf768** [comment]
@brianteeman
Already corrected above some time ago (see https://github.com/joomla/joomla-cms/pull/8038)

**Comment by infograf768** [comment]
To avoid using this string for any model error, I would even change to:

```
diff --git a/libraries/legacy/controller/admin.php b/libraries/legacy/controller/admin.php
index 0aee760..af79e44 100644
--- a/libraries/legacy/controller/admin.php
+++ b/libraries/legacy/controller/admin.php
@@ -209,7 +209,23 @@
 				$model->publish($cid, $value);
 
+				$errors = $model->getErrors();
+
 				if ($value == 1)
 				{
-					$ntext = $this->text_prefix . '_N_ITEMS_PUBLISHED';
+					// Check is ancestor has lower state
+					if (!empty($errors))
+					{
+						foreach ($errors as $error)
+						{
+							if (strpos($error, 'ancestors have lower state') !== false)
+							{
+								$ntext = $this->text_prefix . '_N_ITEMS_FAILED_PUBLISHING';
+							}
+						}
+					}
+					else
+					{
+						$ntext = $this->text_prefix . '_N_ITEMS_PUBLISHED';
+					}
 				}
 				elseif ($value == 0)
```

**Comment by infograf768** [comment]
I created a new PR to simplify testing. Please test https://github.com/joomla/joomla-cms/pull/8065

**Comment by kathastaden** [comment]
Thank you for your additions, I haven't thought about that. 
I am new to Joomla and this was my first PR, so thank you for your help!

**Comment by infograf768** [comment]
@kathastaden 
No p.

Please test though.  :smile:

**Pull request closed without merging**
