### PR TITLE
Update tinyMCE 4.2.1

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Latest version

Among the changes:
New flat theme,
Ability to upload images through editor
#### Preview

screenshot 2015-07-12 20 10 10

### CODE REVIEW

**Comment by brianteeman** [comment]
I couldnt test this with com_patchtester. I "think" this is a known issue with com_patchtester with binary files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7423">issues.joomla.org/joomla-cms/7423</a>.</sub>

**Comment by brianteeman** [comment]
If you are not using git then the only way I can think of to test this would be to use the full branch as a complete joomla install https://github.com/dgt41/joomla-cms/archive/tinyMCE_4.2.1.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7423">issues.joomla.org/joomla-cms/7423</a>.</sub>

**Comment by brianteeman** [comment]
@dgt41 where is "Ability to upload images through editor"
I couldnt see it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7423">issues.joomla.org/joomla-cms/7423</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman this needs to be enabled. you can test it -client side only here- by replacing
line 708 from	`plugins : \"table link image code hr charmap autolink lists importcss\",` to
`plugins : \"table link image code hr charmap autolink lists importcss imagetools\",` and selecting Advanced Mode. Similar thing can be done for simple and extended. 
But bear in mind that any changes will not be uploaded to the server and the images will be save as blob (inline). But of course you can play around and test the functionality (client side).
The solution for the images upload will come with the other PR that implements drag and drop for tinyMCE.

**Comment by brianteeman** [comment]
So realistically this is not a feature that you are proposing we use

On 14 July 2015 at 12:00, Dimitris Grammatiko <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> this needs to be enabled.
> you can test it -client side only here- by replacing
> line 708 from plugins : \"table link image code hr charmap autolink lists
> importcss\", to
> plugins : \"table link image code hr charmap autolink lists importcss
> imagetools\", and selecting Advanced Mode. Similar thing can be done for
> simple and extended.
> But bear in mind that any changes will not be uploaded to the server and
> the images will be save as blob (inline). But of course you can play around
> and test the functionality (client side).
> The solution for the images upload will come with the other PR that
> implements drag and drop for tinyMCE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7423#issuecomment-121201544>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
I didn’t say that, but for the moment this PR only provides the new version of tinyMCE. 
The image tools option requires two parts in order to function as it was intended. The client side is provided by the editor (with this PR) and then we need the server side part which hopefully will come with the other PR (drag and drop).

**Comment by Fedik** [comment]
**test** works good

maybe better change description to "Ability to upload images through editor after # 7435" (or something) :wink:

**Comment by jwaisner** [comment]
@test 

After installing latest version of tinyMCE everything tests successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7423">issues.joomla.org/joomla-cms/7423</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7423">issues.joomla.org/joomla-cms/7423</a>.</sub>

**Comment by infograf768** [comment]
Are there any new TinyMCE lang strings (i.e. to add into each file in media/editors/tinymce/langs/ ?

**Comment by dgt41** [comment]
@infograf768 from the diff it doesn’t look that something was changed in the lang folder

**Comment by infograf768** [comment]
@dgt41
A diff, if any, will not show in the langs folder as this is made with various specific xx.js files which are not part of the Tiny release.
They would show in the general tiny js files where the texts are in English, and also, possibly in their transifex reference.

**Comment by infograf768** [comment]
Found these new ones:
```
"Zoom in": "Zoomer",
"Contrast": "Contraste",
"Back": "Retour",
"Gamma": "Gamma",
"Flip horizontally": "Retournement horizontal",
"Resize": "Redimensionner",
"Sharpen": "Affiner",
"Zoom out": "D\u00e9zoomer",
"Image options": "Options de l'image",
"Apply": "Appliquer",
"Brightness": "Luminosit\u00e9",
"Rotate clockwise": "Rotation horaire",
"Rotate counterclockwise": "Rotation anti-horaire",
"Edit image": "Modifier l'image",
"Color levels": "Niveaux de couleur",
"Crop": "Rogner",
"Orientation": "Orientation",
"Flip vertically": "Retournement vertical",
"Invert": "Inverser",
```

We do have to update all our Tiny language files. I am signalling this to Mig at once

**Comment by brianteeman** [comment]
Before translating those strings are we even using the functionality that
they come from. I wasnt able to in my tests.

These are from the new inline image editing
http://www.tinymce.com/tryit/imagetools.php

On 15 July 2015 at 10:41, infograf768 <notifications@github.com> wrote:

> Found these new ones:
>
> "Zoom in": "Zoomer",
> "Contrast": "Contraste",
> "Back": "Retour",
> "Gamma": "Gamma",
> "Flip horizontally": "Retournement horizontal",
> "Resize": "Redimensionner",
> "Sharpen": "Affiner",
> "Zoom out": "D\u00e9zoomer",
> "Image options": "Options de l'image",
> "Apply": "Appliquer",
> "Brightness": "Luminosit\u00e9",
> "Rotate clockwise": "Rotation horaire",
> "Rotate counterclockwise": "Rotation anti-horaire",
> "Edit image": "Modifier l'image",
> "Color levels": "Niveaux de couleur",
> "Crop": "Rogner",
> "Orientation": "Orientation",
> "Flip vertically": "Retournement vertical",
> "Invert": "Inverser",
>
> We do have to update all our Tiny language files. I am signalling this to
> Mig at once
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7423#issuecomment-121554215>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
@infograf768 I thought we were using the files from the langs directory. But then I saw the code for the language handling insidetinymce.php and realized that there should be some more languages files provided by Joomla translation team. So yes the strings are the ones from image tools.

@infograf768 @brianteeman about imagetools: although these look great we need to figure out the server side code for this. There are some things we have to thing how to solve them:
- Images do not retain their filenames (means that the uploaded images have to get a random name on the server)
- There is no advanced access control in tinyMCE to match Joomla's ACL
- With the new media a complete images toolset will also be available (also client-side) so maybe we can just create a similar plugin that will use our tools (much easier to accomplish)
- Their images tool work on form submit (by default) which is not optimal e.g. #7435 works instantly!

**Comment by infograf768** [comment]
@dgt41
I explain the process
A TinyMCE new release as obtained from Tiny site does not contain anything in the langs folder except the readme.
The ones present in staging for some of them come after adapting files obtained directly from this page:
http://www.tinymce.com/i18n/index.php
Then we encouraged the TTs to participate in Tiny Transifex project (some did) and also some of our langs are directly produced or customised by the TTs themseves as the ones available are/were pretty bad or incomplete.

**Comment by dgt41** [comment]
Since there is another PR #7667 that updates tinyMCE to the latest version, this is obsolete

**Pull request merged**
