### PR TITLE
[4.2] CLI user scripts cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
This is part of a series of pr (broken down to smaller ones to make testing easier) that fixes several issues in the cli commands.

1. Make sure the title is displayed
2. Make sure the case of the title matches the styleguide
3. Make sure table column headings match the styleguide

### Delete User
EeAtdW7eP6

### Add User
ETNKnNtukE

### Add user to group
JmrYkA44pS

### Remove user from group
VSLxzhiV95

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d2f0cf49696c6a0874a179b3738c7a2cf768b3b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38210">issues.joomla.org/tracker/joomla-cms/38210</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d2f0cf49696c6a0874a179b3738c7a2cf768b3b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38210">issues.joomla.org/tracker/joomla-cms/38210</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38210">issues.joomla.org/tracker/joomla-cms/38210</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
