### PR TITLE
[4.3] Batch tags variable

### PR DESCRIPTION
**Pull request by brianteeman**
Removes unused variable

Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 050b681ba01cdce1723a76b0aa325fa7b6b7e018<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40265">issues.joomla.org/tracker/joomla-cms/40265</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 050b681ba01cdce1723a76b0aa325fa7b6b7e018<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40265">issues.joomla.org/tracker/joomla-cms/40265</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40265">issues.joomla.org/tracker/joomla-cms/40265</a>.</sub>

**Comment by obuisard** [comment]
Thanks again, Brian @brianteeman !

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
