### PR TITLE
New TinyMCE: Correcting default TinyMCE params when installing Joomla

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13344#issuecomment-269857020

### Summary of Changes
Updating default tiny params in joomla.sql
### Testing Instructions
Patch and install a new staging. Check that the Warning message is not displayed anymore when editing an article and when editing the plugin

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on ff013001b76274b0d726e7a17f30d582553cfaae<br /><br />Patch ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13431">issues.joomla.org/tracker/joomla-cms/13431</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on ff013001b76274b0d726e7a17f30d582553cfaae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13431">issues.joomla.org/tracker/joomla-cms/13431</a>.</sub>

**Comment by infograf768** [comment]
@rdeutz @wilsonge 
Please merge to go on improving this new feature

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768 and testers. Merged!

**Pull request merged**
