### PR TITLE
[4.1] Remove Bootstrap tooltip

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Due to an incorrect selector, the Bootstrap tooltip did not display. This PR removes the use of Bootstrap tooltip markup and update the title attribute to include the site name to be consistent with other lists.

### Testing Instructions
Go to System > Update Sites
Move cursor over a site.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 15faa917f00cde3b61ff4275e300c31e707850cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37238">issues.joomla.org/tracker/joomla-cms/37238</a>.</sub>

**Comment by brianteeman** [comment]
i agree the current code is wrong but i dont agree in adding the tip. its not in any other list

**Comment by Quy** [comment]
Changed. Thanks.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9cb22cc065d1a901e52af6db2e5458dc250c5062<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37238">issues.joomla.org/tracker/joomla-cms/37238</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9cb22cc065d1a901e52af6db2e5458dc250c5062<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37238">issues.joomla.org/tracker/joomla-cms/37238</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37238">issues.joomla.org/tracker/joomla-cms/37238</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
