### PR TITLE
[4.0] Ajax typo

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes typo - probably from a search & replace

Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 82e436e48639dc98ec5292a0a212f9927d8bdef4<br /><br />Can be merged by review, but as long as tests are failing due to unrelated reasons I would need the super power for forced merge which I don't have (and don't wanna have).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33034">issues.joomla.org/tracker/joomla-cms/33034</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 82e436e48639dc98ec5292a0a212f9927d8bdef4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33034">issues.joomla.org/tracker/joomla-cms/33034</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33034">issues.joomla.org/tracker/joomla-cms/33034</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
ta

**Pull request merged**
