### PR TITLE
[4.0] Fix Global Config Text Filters table width

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/27731#issuecomment-580763630

### Summary of Changes
Solution provided by @ciar4n (Thanks)
https://github.com/joomla/joomla-cms/pull/27731#issuecomment-581009221

### After patch
Screen Shot 2020-02-01 at 11 24 53

@Quy @ciar4n

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7350d216901abc3e1486c05f2bb26099ccdd7203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27754">issues.joomla.org/tracker/joomla-cms/27754</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 7350d216901abc3e1486c05f2bb26099ccdd7203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27754">issues.joomla.org/tracker/joomla-cms/27754</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 7350d216901abc3e1486c05f2bb26099ccdd7203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27754">issues.joomla.org/tracker/joomla-cms/27754</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27754">issues.joomla.org/tracker/joomla-cms/27754</a>.</sub>

**Pull request merged**
