### PR TITLE
Fix media field tooltip wrong path for multiple instances

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Steps to reproduce the issue

Create or edit an article in backend.
In the tab "Images and links", set two different images for intro and fulltext image.
Move your mouse over the fulltext image field.
#### Expected result

The path for the fulltext image should be displayed when hovering over the respective field.
#### Actual result

Instead, the tooltip always shows the path for the intro image.
#### Testing

Apply the patch with patch tester and repeat the above steps
#### Extras (for PLT)

This patch also introduces two static javascript files places in `/media/media/js`
They are named as mediafied-mootools so introducing the jquery field later on we won’t get a conflict
There was a value passed for php to js (the root path), this is now passed as a data attribute on the input field.

### CODE REVIEW

**Comment by 810** [comment]
typo filename: mootols.js

**Comment by dgt41** [comment]
@810 thanks

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 38f3d22a9dd131f8ed529c5c461c9cc4ad77200c<br /><br />OK here. Both tips now fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8100">issues.joomla.org/joomla-cms/8100</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 38f3d22a9dd131f8ed529c5c461c9cc4ad77200c<br /><br />Successfully tested and works after applying patch. 
Thanks @dgt41 for fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8100">issues.joomla.org/joomla-cms/8100</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8100">issues.joomla.org/joomla-cms/8100</a>.</sub>

**Pull request merged**
