### PR TITLE
fix #42191 Unknown column 'id' in 'field list'

### LINKED ISSUE #42191: Joomla\CMS\Installer\InstallerScript::getInstances Unknown column 'id' in 'field list'
In this method it tries to load the field 'id' from the extensions table. But there isn't any field called id in this table.

The id field for the extenions table is called extension_id
```
        // Select the item(s) and retrieve the id
        $query->select($db->quoteName('id'));

        if ($isModule) {
            $query->from($db->quoteName('#__modules'))
                ->where($db->quoteName('module') . ' = :extension');
        } else {
            $query->from($db->quoteName('#__extensions'))
                ->where($db->quoteName('element') . ' = :extension');
        }
```

It would need to look like 

```
        // Select the item(s) and retrieve the id
       
        if ($isModule) {
            $query->select($db->quoteName('id'))
                  ->from($db->quoteName('#__modules'))
                ->where($db->quoteName('module') . ' = :extension');
        } else {
            $query->select($db->quoteName('extension_id') . ' as id')
                ->from($db->quoteName('#__extensions'))
                ->where($db->quoteName('element') . ' = :extension');
        }
```

### PR DESCRIPTION
**Pull request by svanschu**
In this method it tries to load the field 'id' from the extensions table. But there isn't any field called id in this table. The id field for the extenions table is called extension_id

Pull Request for Issue # .

### Summary of Changes
Moved the select id statement into the module if clause and create a new select extension_id as id clause for the else branch

### Testing Instructions
```
class testingInstallerScript extends InstallerScript
{
    public function postflight($type, $parent)
    {
        $extid = $this->getInstances(false);
    }
}
```

### Actual result BEFORE applying this Pull Request

Unknown column 'id' in 'field list'

### Expected result AFTER applying this Pull Request

successfully return extension id in an array

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by svanschu** [comment]
@richard67 as suggested the PR for 4.4-dev

**Comment by HLeithner** [comment]
wow nobody noticed this issue in the at least last 7 years?

**Comment by svanschu** [comment]
> wow nobody noticed this issue in the at least last 7 years? 

Or just overriden the method without fixing the source. Or just done it on it's own.

I only noticed the method because I wanted to know what is all available and read the class code. It's as well the first time I ever used it.

**Review by richard67 — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dca2c7e0f4e8493524827b8c3b17326899ed36a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42199">issues.joomla.org/tracker/joomla-cms/42199</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dca2c7e0f4e8493524827b8c3b17326899ed36a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42199">issues.joomla.org/tracker/joomla-cms/42199</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42199">issues.joomla.org/tracker/joomla-cms/42199</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
