### PR TITLE
Updating 4.3-dev with changes from 4.2-dev

### PR DESCRIPTION
**Pull request by sdwjoomla**

### CODE REVIEW

**Comment by brianteeman** [comment]
changes in package.json do not look right

some packages are being removed and some others are being downgraded

**Comment by richard67** [comment]
> changes in package.json do not look right
> 
> some packages are being removed and some others are being downgraded

Yes, and it also seems to undo Dimitris‘ move from sass to sass-embedded.

**Comment by richard67** [comment]
And besides that it changes package.json but not package.lock, that can’t go well.

**Comment by richard67** [comment]
To properly solve this mess, it needs to study the change history of the package.json in both branches 4.2-dev and 4.3-dev and check each change individually. And after that when the package lock is right it needs to remove the lock file and run npm install, or keep the lock and run npm update for the individual packages which shall be updated.

**Comment by richard67** [comment]
By review the changes in package.json look ok to me. Changes from PR's #39320 and #39315 correctly merged up from 4.2-dev, and no changes for 4.3-dev got lost. The 2 mentioned PR's from 4.2-dev do not result in changes in the lock file, so it is ok that this PR here doesn't change that.

The other changes in this PR I haven't checked.

**Pull request merged**
