### PR TITLE
Fixing missing parameter usage.

### PR DESCRIPTION
**Pull request by artur-stepien**
Pull Request for Issue #9224 .
#### Summary of Changes

Fixed missing parameter.
#### Testing Instructions

Just add `mod_languages` module. Select **Use Dropdown** and deselect **Languages Full Names**. Then go to front and look at `mod_languages` select field.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9e3dd699aa86c134361ec8adb4ee4be0088adce1<br /><br />Works.

@infograf768, for reference, i think PR https://github.com/joomla/joomla-cms/pull/9095 is hidding this option can you check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9225">issues.joomla.org/joomla-cms/9225</a>.</sub>

**Comment by infograf768** [comment]
Imho , as it is very easy to do an override (as nobody for years has ever asked for that type of dropdown), we should rather consider improving #9095.

**Comment by artur-stepien** [comment]
Can be a good idea. Better to have both.

**Comment by andrepereiradasilva** [comment]
@infograf768 yes https://github.com/joomla/joomla-cms/pull/9095 should be improved.
But https://github.com/joomla/joomla-cms/pull/9095 is only for 3.6.0

This PR solves a bug that IMHO can be in 3.5.0.

**Comment by infograf768** [comment]
FYI, it is not a bug. It was never intended since we implemented the switcher to show uppercase language sef in the dropdown.

I am a bit concerned here by B/C. I explain.
If a user has, by mistake or just as it had no impact until now, set the Language Full Names to "No", then it will change the dropdown display without the user knowledge.

**Comment by andrepereiradasilva** [comment]
button tooltip: `<strong>Languages Full Names</strong><br />If set to 'Yes' and image flags set to 'No', full content language native names are displayed. If set to 'No', upper case abbreviations from the content languages URL Language Code are used. Example: EN for English, FR for French.`

reggarding the B/C i understnad your concerns, but woudn't that make resolving bugs in all parameters B/C? Is thta part of the b/c policy?

**Comment by infograf768** [comment]
you forgot the spacer:
`MOD_LANGUAGES_SPACERDROP_LABEL="<u>If Use Dropdown is set to 'Yes', <br />the display options below will be ignored</u>"`

**Comment by andrepereiradasilva** [comment]
oh ok :)
you're right then !

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on 9e3dd699aa86c134361ec8adb4ee4be0088adce1<br /><br />As previous comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9225">issues.joomla.org/joomla-cms/9225</a>.</sub>

**Comment by artur-stepien** [comment]
Patch it self works. No idea why you mark this test as unseccesful. This is more about the fact that when applied module will change the way settings are interpreted (in my opinion it should be like this from the begining, simple logic). If you want to ignore this patch it can be a good idea to use "showon" with full_names field. It will be less confusing. And maybe merge this into previously mentioned patch with flags in dropdown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9225">issues.joomla.org/joomla-cms/9225</a>.</sub>

**Comment by andrepereiradasilva** [comment]
artue, yes i marked unseccesful, because as the current language switcher behaviour this is not a bug, as explained in the posts above.

Your code seems correct, and i agree with you that should had work like this since the begiining.

But unfortanly it didn't work like this so infograf as reason when it can have reporcursions on users.

I let infograf decide if he want to change the behaviour in his patch.

I thank you for your contribution, but as you can see for previous post this raises some issues, so for me, as it is now, is a "no go".

**Comment by roland-d** [comment]
Since we all agree this is a nice to have, I have added the label to re-evaluate for Joomla 4. This way we can have a look at it later when B/C is not an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9225">issues.joomla.org/joomla-cms/9225</a>.</sub>

**Comment by laoneo** [comment]
@infograf768 are you ok when this gets into 4?

**Comment by artur-stepien** [comment]
I suppose better then never?

**Comment by infograf768** [comment]
@laoneo 
not at my desk until the 17th. will re-evaluate when back. can you remind me on glip? thanks

**Comment by infograf768** [comment]
OK, will try to make patch. The showon may become a bit complex.

**Comment by artur-stepien** [comment]
@infograf768  What showon has to do with this?

**Comment by infograf768** [comment]
The Language Full Names field should only be displayed in certain cases in the form. Please look at the xml where we make extensive use of showon.

**Comment by artur-stepien** [comment]
I don't see anything like that in source branch module declaration. I suppose it is new in version 4. My bad

**Comment by infograf768** [comment]
Not new.
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_languages/mod_languages.xml#L127-L138

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/20192 (using https://github.com/joomla/joomla-cms/archive/4.0-dev.zip before patch) .
Closing as we have a patch.

**Pull request closed without merging**
