### PR TITLE
[4.0] [mod_tags_popular] Array to string conversion

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/28378.

### Summary of Changes

Fixes error in query.

### Testing Instructions

Publish Tags - Popular module.

### Expected result

Works.

### Actual result

> Notice: Array to string conversion in modules\mod_tags_popular\src\Helper\TagsPopularHelper.php on line 100
>Error: Unknown column 'Array' in 'where clause': Unknown column 'Array' in 'where clause'

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
Please also correct in 3.10

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 827411a2a8d33c2e9cf2187f68de51a88a4ab028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28379">issues.joomla.org/tracker/joomla-cms/28379</a>.</sub>

**Comment by SharkyKZ** [comment]
>Please also correct in 3.10

Are you having this issue on 3.10? Looks fine on code review.

**Comment by infograf768** [comment]
In 3.10, the difference is that we have
`$groups      = implode(',', $user->getAuthorisedViewLevels());`

no `bindArray`

Is that OK?

(I do not have a test site in 3.10 right now.)

**Comment by SharkyKZ** [comment]
That's fine. In 4.0 we're using parameterized queries. That's where the difference came from.

**Comment by wilsonge** [comment]
Yup this is fine - only needed in 4.0

**Comment by infograf768** [comment]
can be merged. No use for another test (cs only)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ddd30a78721f198e609695b04e5a7a7be0c9a38b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28379">issues.joomla.org/tracker/joomla-cms/28379</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ddd30a78721f198e609695b04e5a7a7be0c9a38b<br /><br />i've got the error before applying the pr even without tags
after pr no more errors with and without tags<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28379">issues.joomla.org/tracker/joomla-cms/28379</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28379">issues.joomla.org/tracker/joomla-cms/28379</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
