### PR TITLE
postgresql - workaround for uppercase table prefix - #8713

### PR DESCRIPTION
**Pull request by alikon**
Workaround for UPPERCASE table prefix for postgresql  see #8713

### CODE REVIEW

**Comment by brianteeman** [comment]
Works correctly but you need alpha order the language string or you will have someone complaining

**Comment by alikon** [comment]
not so sure what kind of alpha order are used in that file it seems they are alpha ordered by group of string ordered by Event ??

**Comment by brianteeman** [comment]
Just swap these two lines
>INSTL_DATABASE_FIX_LOWERCASE="The table prefix must be lowercase for Postgresql."
  INSTL_DATABASE_FIX_TOO_LONG="The MySQL table prefix must be a maximum of 15 characters."

**Comment by brianteeman** [comment]
DOH BRIAN NEEDS MORE COFFEE - ignore me

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 14ee2670ce053286b3330c2907e8ce28e32a0ca4<br /><br />Perfect thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8856">issues.joomla.org/joomla-cms/8856</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Shouldn't that check be made in global configuration option "Database Tables Prefix" too?

**Comment by alikon** [comment]
we don't need for the database name  works well even for UPPERCASE name

**Comment by andrepereiradasilva** [comment]
ok

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f4ae006e8ddef05bc35bdc081d104c4826c1f52e<br /><br />Thanks alikon!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8856">issues.joomla.org/joomla-cms/8856</a>.</sub>

**Comment by sovainfo** [comment]
Agree with @andrepereiradasilva that this validation should also be in global configuration. When it makes sense to stop dummies at installation, they should be stopped at configuration as well.

**Pull request merged**
