### PR TITLE
Fixed#36117 -- Underlined links in Joomla Update Section

### PR DESCRIPTION
**Pull request by khu5h1**
Pull Request for Issue #36117 .

### Summary of Changes
Added Underline in the link in Joomla Update Section.

### Testing Instructions
See the link underlined in the Joomla update section and set the colour to monochrome for atum and see the link (underlined).

### Actual result BEFORE applying this Pull Request
No underlined link.

### Expected result AFTER applying this Pull Request
Underlined link in Joomla Update Section.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by richard67** [comment]
Please fix the scss code style errors reported here https://ci.joomla.org/joomla/joomla-cms/48730/1/20 . Thanks in advance.

**Comment by richard67** [comment]
Sorry my mistake. Closed by accident.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 458a4742928842d11217f76b5b1bdc94762faf2a<br /><br />with prebuilt package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by richard67** [comment]
I think this PR has some unwanted side effects. It underlines EVERY link in monochrome mode, even the icons.

See the red marks in the following screen shot:

2021-11-27_monochrome

@chmst Is this what you had in mind when reporting the issue? Or did you just refer to the link at the bottom?

I think it needs to be more specific here with the CSS selector.

**Comment by brianteeman** [comment]
Fairly certain that the monochrome screenshot was to emphasise the problem of that link and not that the change should be made just for monochrome

**Comment by richard67** [comment]
@brianteeman Would you say it justifies a negative test in the tracker? Or is it more caused by a probably misleading description of the issue?

**Comment by brianteeman** [comment]
It's a negative test because of the issue you reported.
It's not the correct solution if my assumption is correct

**Comment by richard67** [comment]
@brianteeman I think we think the same: That one link should be underlined regardless of monochrome or not because without monochrome the only visual indicator for it being a link is the colour, and that's not enough. Other links should not be touched if not having the same issue.

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on 458a4742928842d11217f76b5b1bdc94762faf2a<br /><br />With the PR not only that one link is underlined but also other links and even the icons for these links, see the red marks in the screen shot in my comment above https://github.com/joomla/joomla-cms/pull/36134#issuecomment-980636162 .

I think a better fix would be to make sure that the one link which has no visual indication at all when monochrome and only the colour when not monochrome should get underlined in any case, regardless of monochrome or not, and the other links should not be touched if they don't have the same problem as thins one link has.

Links looking like buttons and icons attached to the link text should never be underlined in my opinion because that simply looks ugly and has no benefit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by khu5h1** [comment]
@richard67 @brianteeman Thanks for the feedback. I will do the required changes as suggested and will update the PR accordingly.

**Comment by ChristineWk** [comment]
I have not tested this item.<br /><br />sorry did not pay attention to the other underlined links.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by chmst** [comment]
Sorry, was absent for a few days. Thank you @khu5h1 for working on that issue. I was surprised myself by this screen as in general we did carefully underline links. 
Seems that the new empty-state texts were forgotten.

**Comment by khu5h1** [comment]
I have committed the desired changes. Thanks :)

**Comment by richard67** [comment]
Now after the last change it needs to update title and description because they still refer to monochrome.

**Comment by khu5h1** [comment]
@richard67 Thanks for the suggestion. I have updated the title and description of the PR.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4117a5118f80d83e5ebf71c1ebe6a4367c38ab94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by chmst** [comment]
@khu5h1 
thanks for your contribution. 
Underlining the link is correct independent from monochrome style. It was an accessibility issue as colorblind users see every screen as monochrome.

**Comment by richard67** [comment]
@chmst Shouldn't that be done in other places, too, where we have a link at the bottom e.g. of a blank state page?

**Comment by chmst** [comment]
Yes., but as much as I know there are no other links on  "Empty state screens". The update process is something "extra" and it seems overkill now to find generic solutions here.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 4117a5118f80d83e5ebf71c1ebe6a4367c38ab94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 4117a5118f80d83e5ebf71c1ebe6a4367c38ab94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36134">issues.joomla.org/tracker/joomla-cms/36134</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
