### PR TITLE
[4.2] Inject the database into the banner HTML service

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Ongoing effort to inject the database into components and get rid of the deprecated `Factory::getDbo();` calls.

### Testing Instructions
- Create a banners client
- Create a banner
- In the banners list, select a banner and then click on the batch action
image

### Actual result BEFORE applying this Pull Request
The client list in the batch modal shows the new client.

### Expected result AFTER applying this Pull Request
The client list in the batch modal shows the new client.

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on e2e209f7c0049202e808531355a2412ea8b1ba4d<br /><br />Patch works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37604">issues.joomla.org/tracker/joomla-cms/37604</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on e2e209f7c0049202e808531355a2412ea8b1ba4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37604">issues.joomla.org/tracker/joomla-cms/37604</a>.</sub>

**Comment by kiki-G** [comment]
I have tested this item :white_check_mark: successfully on e2e209f7c0049202e808531355a2412ea8b1ba4d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37604">issues.joomla.org/tracker/joomla-cms/37604</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37604">issues.joomla.org/tracker/joomla-cms/37604</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
