### PR TITLE
Adding Menu Title to menu items page

### PR DESCRIPTION
**Pull request by infograf768**
This PR will make it clear to which menu the menu items belong.

After patch:
screen shot 2016-02-27 at 08 56 00

@andrepereiradasilva https://github.com/joomla/joomla-cms/pull/9218#issuecomment-189204660
@richard67

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 1c87b4c412ff13a5bd4ea38bea29b772c94309bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1c87b4c412ff13a5bd4ea38bea29b772c94309bf<br /><br />Nice, works like a charm here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.

If https://github.com/joomla/joomla-cms/pull/8411 was ever considered, this would require a slight change as we would have no $menutype when displaying all menu items.javascript:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1c87b4c412ff13a5bd4ea38bea29b772c94309bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by brianteeman** [comment]
If #8411 is accepted as well what is displayed in the title bar when you have "all menu itms" selected?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1c87b4c412ff13a5bd4ea38bea29b772c94309bf<br /><br />works fine.

One commnent. In the other views that have a view selector we use: xxxxxx - Site ou xxxxxx - Administrator, here we use xxxxxx (menu title).
IMHO the other views should be updated to follow this logic, ex:

- Maintenance: Clear Cache (Site)
- Maintenance: Clear Cache (Administrator)
- Modules (Site)
- Modules (Administrator)
- Languages: Installed (Site)
- Languages: Installed (Administrator)

Following the same logic everywhere is more user friendly.
What do you think? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by brianteeman** [comment]
I agree<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9227">issues.joomla.org/joomla-cms/9227</a>.</sub>

**Comment by infograf768** [comment]
>If #8411 is accepted as well what is displayed in the title bar when you have "all menu itms" selected?

it would be a new string, something like
Menus : All menu items

with a conditional

**Comment by wilsonge** [comment]
Merging this. JM #8411 will need to be updated after this

**Comment by infograf768** [comment]
Instead of updating #8411 I created a new PR https://github.com/joomla/joomla-cms/pull/9231

Concerning the parenthesis, no objection.

**Comment by andrepereiradasilva** [comment]
ok. will do a PR for that

**Pull request merged**
