### PR TITLE
Exclude the sec read me from the final package as discussed eralier

### PR DESCRIPTION
**Pull request by zero-24**
This execlud the new md file from the final package as discussed earlier.

//cc @wilsonge @bakual @rdeutz 

As discussed this can be merged on review ;)
### For The reason

This file needs to be removed from The final package as it Can ne accessed direct via URL and there is no reason to have this in the final package ;)

Btw should we add some kind of message to the unsecure classes too? (out of scope for this PR but if needed we can have a follow up)

### CODE REVIEW

**Comment by brianteeman** [comment]
What is the point of having the readme file with "important" information in
it if its not going to be distributed

On 27 November 2015 at 22:39, zero-24 <notifications@github.com> wrote:

> This execlud the new md file from the final package as discussed earlier.
>
> //cc @wilsonge <https://github.com/wilsonge> @bakual
> <https://github.com/bakual> @rdeutz <https://github.com/rdeutz>
>
> As discussed this can be merged on review ;)
> For The reason
>
> This file needs to be removed from The final package as it Can ne accessed
> direct via URL and there is no reason to have this in the final package ;)
>
> Btw should we add some kind of message to the unsecure classes too? (out
> of scope for this PR but if needed we can have a follow up)
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/8554
> Commit Summary
>
>    - exclude the sec warning from the final package
>    - Update build.php
>
> File Changes
>
>    - *M* build/build.php
>    <https://github.com/joomla/joomla-cms/pull/8554/files#diff-0> (1)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/8554.patch
>    - https://github.com/joomla/joomla-cms/pull/8554.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8554>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
Gotta agree with that.  If you're gonna strip it in packages then move its contents to the docs site.  Where it just might get a little more attention.

**Comment by zero-24** [comment]
Lets ship it with the update. Thanks for the feedback.

**Comment by Bakual** [comment]
It doesn't really matter if that file is present and accessible or not. The content of the file is available for everyone to read right here in this repo anyway.
If it would be a security issue by having that information public, then we should never had added it here to begin with.
But then, security through obscurity never works out well anyway :smile:

**Pull request closed without merging**
