### PR TITLE
[4.0] Private messages

### PR DESCRIPTION
**Pull request by brianteeman**
Change the menu to remove the named "New Private Message" and replace with the +

PR for #28651

### Before
image

### After
image

### CODE REVIEW

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on 7f4ba0306d84ddf10943bbd4590a5202d3678c9d<br /><br />good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28653">issues.joomla.org/tracker/joomla-cms/28653</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 7f4ba0306d84ddf10943bbd4590a5202d3678c9d<br /><br />It's OK!!! Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28653">issues.joomla.org/tracker/joomla-cms/28653</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28653">issues.joomla.org/tracker/joomla-cms/28653</a>.</sub>

**Comment by ggenovino** [comment]
I have tested this item :white_check_mark: successfully on 7f4ba0306d84ddf10943bbd4590a5202d3678c9d<br /><br />ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28653">issues.joomla.org/tracker/joomla-cms/28653</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
