### PR TITLE
Adding russian calendar language file

### PR DESCRIPTION
**Pull request by nvyush**
Pull Request for Issue # .

### Summary of Changes
Adding russian language file for new calendar

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by Bakual** [comment]
The process for the calendar files (as any other official translation file) would be to post the file in the translator forum and it gets merged from there.
Otherwise we can't be sure if your from the official translation team (https://community.joomla.org/translations/joomla-3-translations.html#ru-ru).

**Comment by SergeyLitvinov** [comment]
@Bakual I've checked this commit and translation is OK. I can add this file on the TT forum but as it already here I think we can merge it)

**Comment by infograf768** [comment]
As Sergey is ok with it, i set as rtc

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d6cacafd255e784123da5ccfc014209225ad14ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17443">issues.joomla.org/tracker/joomla-cms/17443</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17443">issues.joomla.org/tracker/joomla-cms/17443</a>.</sub>

**Comment by SergeyLitvinov** [comment]
Thank you @infograf768!

**Pull request merged**
