### PR TITLE
[4.0] Add json to source_formats of template editor

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
- Go to `administrator/index.php?option=com_templates&view=templates`
- Click on "Cassiopeia Details and Files"
- See file list on the left:
File `joomla.asset.json` (an essential file for templates configuration in J4) is missing.

### CODE REVIEW

**Comment by wilsonge** [comment]
@zero-24 rips please (might be same as the other one i tagged you in)

**Comment by zero-24** [comment]
rebooted: http://ci.joomla.org/joomla/joomla-cms/13523

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on e9e0499448d740dd1aeabe0885f0d46c80a59ba2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23470">issues.joomla.org/tracker/joomla-cms/23470</a>.</sub>

**Comment by astridx** [comment]
I have applied this patch and after that I made a new installation. Then I opened the options for com_templates in Global Configuration and I could see the json as valid source format. I tested only mysql not postgrep.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
