### PR TITLE
Remove unused variable $lang

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
Removed unused variable
`$lang  = JFactory::getLanguage();`

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 63ac25ad84ee0a450bd5fb2f1ad26d0c4cef307f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26787">issues.joomla.org/tracker/joomla-cms/26787</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 63ac25ad84ee0a450bd5fb2f1ad26d0c4cef307f<br /><br />LOL. Goes back to 2013...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26787">issues.joomla.org/tracker/joomla-cms/26787</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26787">issues.joomla.org/tracker/joomla-cms/26787</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
