### PR TITLE
[4.0] Remove empty JHtmlBehavior methods

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes some empty `JHtmlBehavior` methods.

### Testing Instructions

Code review.

### Documentation Changes Required

Some methods removed.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dfd2d6cb6dfca5381af951d1529c85254d3873eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27335">issues.joomla.org/tracker/joomla-cms/27335</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on dfd2d6cb6dfca5381af951d1529c85254d3873eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27335">issues.joomla.org/tracker/joomla-cms/27335</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27335">issues.joomla.org/tracker/joomla-cms/27335</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
