### PR TITLE
Correcting smartsearch filter #8140

### PR DESCRIPTION
**Pull request by infograf768**
Error in https://github.com/joomla/joomla-cms/pull/8140 

We get
screen shot 2015-11-27 at 17 43 51

After this Pr we will rightfully get

screen shot 2015-11-28 at 08 13 12

I have also modified the constant (as it is a new string, it is OK. Thanks Mig for that one)

```
-COM_FINDER_MAPS_SELECT_BRANCHE="- Select Branch -"
+COM_FINDER_MAPS_SELECT_BRANCH="- Select Branch -"
```

and corrected the spaces to tabs in filter_maps.xml

### CODE REVIEW

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on dbc02cb442b3fea49aec4d0e6a02f28105d9e5cb<br /><br />Tested with success on last staging. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8558">issues.joomla.org/joomla-cms/8558</a>.</sub>

**Comment by brianteeman** [comment]
Good spot that it should have a -select- string BUT I am not sure it is correct
Shouldnt it be - Select Content Map - that is the menu name 

and the string Branches Only doesnt seem to make sense to me as it is actually All Branches or All Content Maps as its a parent item containing all the other content maps.

If thats correct then the string Return to Branches should also probably be changed to Return to Content Maps

**Comment by infograf768** [comment]
`Branches only` as well as `Return to branches` exist in core since the original porting of com_finder to Joomla.

See history (2011), where the terms branches and content maps are already present: 
https://github.com/joomla/joomla-cms/blob/baa509338c8b92e41999fbc8d79ac755f9b6a761/administrator/language/en-GB/en-GB.com_finder.ini

We also have:
`COM_FINDER_STATISTICS_STATS_DESCRIPTION="The indexed content on this site includes %s terms across %s links with %s attributes in %s branches."`
`COM_FINDER_MAPS_BRANCH_LINK="Select to show the children in this branch."`
`COM_FINDER_MAPS_MULTILANG="Note: Language filter system plugin has been enabled, so this branch will not be used."`

We can obviously change whatever needed, but this patch is only correcting an error in https://github.com/joomla/joomla-cms/pull/8140 where the Select should have been on top of dropdown and get rid of "Branches only" which never made any sense.

**Comment by infograf768** [comment]
Looking further into this: there is a difference between `Branches' and 'Maps'
A `branch` is a sort of category which contains `maps` (also called children)
I.e. when you display only one branch, its contents are maps, which you can publish/unpublish/delete if desired.

screen shot 2015-11-28 at 11 46 31

Therefore I would leave the terms alone and just merge this PR correcting https://github.com/joomla/joomla-cms/pull/8140

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dbc02cb442b3fea49aec4d0e6a02f28105d9e5cb<br /><br />String changed correctly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8558">issues.joomla.org/joomla-cms/8558</a>.</sub>

**Comment by brianteeman** [comment]
OK I guess any other change is out of scope so its a good test from me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8558">issues.joomla.org/joomla-cms/8558</a>.</sub>

**Comment by infograf768** [comment]
2 good tests. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8558">issues.joomla.org/joomla-cms/8558</a>.</sub>

**Pull request merged**
