### PR TITLE
New Feature: add redirect option after article submission

### PR DESCRIPTION
**Pull request by infograf768**
Replacing https://github.com/joomla/joomla-cms/pull/13011 after discussing with @bembelimen 

**Testing Instructions**

=> Create a frontend `Create Article` menu item
=> Look in the tab "Options"
=> The only parameter is to choose or not a specific category
=> Submit an article in the frontend, you'll redirected to the front page
=> Apply patch
=> Look into the menu item options again, there should be a new parameter `Submission Redirect`

screen shot 2016-12-17 at 11 00 10

=> Do not Select any menu item and submit a new article, the redirect to the frontpage should still work
=> Choose a new redirect target in the menu item option
=> Submit an article
=> The user should be redirected to the new (defined) target

Now works in multilang and only when creating an article when the menu item exists.

Thanks @bembelimen 

Note: also corrected some missing JRoute for redirects in the same file.

### CODE REVIEW

**Comment by infograf768** [comment]
@bembelimen Please test

**Comment by infograf768** [comment]
@jeckodevelopment 
Please mark this as New Feature

**Comment by jeckodevelopment** [comment]
@infograf768 , @zero-24 is faster :P

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on da9fecee11687cb9021ceac3c7b8e3db0739403d<br /><br />Tested on localhost using patchtester with latest version of Staging 

Works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13228">issues.joomla.org/tracker/joomla-cms/13228</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on da9fecee11687cb9021ceac3c7b8e3db0739403d<br /><br />Test ok for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13228">issues.joomla.org/tracker/joomla-cms/13228</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13228">issues.joomla.org/tracker/joomla-cms/13228</a>.</sub>

**Comment by wilsonge** [comment]
Nice Work JM :)

**Pull request merged**
