### PR TITLE
[5.0] SQL fix and update scripts for PR #41259 

### PR DESCRIPTION
**Pull request by richard67**
Follow-up Pull Request (PR) for PR #41259 .

### Summary of Changes

Add update SQL scripts for migrating the filter parameters of relevant core field plugins and the fieldparams of relevant custom fields on update.

### Testing Instructions

Have a clean 5.0.0-alpha3 or previous 5.0.0 alpha version or a 4.4-alpha3.

Create a few custom fields of types "text", "textarea" or "editor" for articles, and for some of these fields use the "Text" filter, for some use the filter from the plugin and for others use some other filter.

Now update to a new package build on the 5.0-dev branch for the actual result, or update to the patched package or custom update URL created by Drone for this PR for the expected result.

Then check the filter parameter of the fields plugins in the `#__extensions` table.

Then check the filter parameter of the field's fieldparams plugins in the `#__fields` table.

Finally create an article using the custom fields created before the update and save that article.

### Actual result BEFORE applying this Pull Request

After an update, the parameters and fieldparams have not been migrated.

### Expected result AFTER applying this Pull Request

After an update, the parameters and fieldparams have been migrated.

Saving the article with the custom fields works.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo Why did you close this PR? The new update SQL scripts are missing in Harald's PR.

**Comment by richard67** [comment]
Rebased to 5.0-dev after PR #41259 has been merged.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 64883f430e16ba46fe2d7c09f61f30acaf223326<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41417">issues.joomla.org/tracker/joomla-cms/41417</a>.</sub>

**Comment by richard67** [comment]
@laoneo Have you tested with both MySQL and PostgreSQL? Or only MySQL?

**Comment by HLeithner** [comment]
thanks richard and allon

**Comment by laoneo** [comment]
Only mysql

**Pull request merged**
