### PR TITLE
[4.0] fix data tag so that insert works

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #32676 .

### Summary of Changes
Changed Link Target so that input of a tag works.

### Testing Instructions (Check out the linked Issues for a better desciption) 
* Create a new Template
* Enable Edit Body
* Click on a tag e.g. username

### Actual result BEFORE applying this Pull Request
Nothing happens

### Expected result AFTER applying this Pull Request
Tag will be inserted and the end or the cursor position in the Body field.

### Documentation Changes Required
nothing

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 1a23f81650fc1608edb5585a9b4af4dc064c1dbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32681">issues.joomla.org/tracker/joomla-cms/32681</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1a23f81650fc1608edb5585a9b4af4dc064c1dbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32681">issues.joomla.org/tracker/joomla-cms/32681</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32681">issues.joomla.org/tracker/joomla-cms/32681</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
