### PR TITLE
[4.1] Missing description line in config

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
The line was added in PR https://github.com/joomla/joomla-cms/pull/35610, but omitted from the XML.

Screenshot_1

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :red_circle: unsuccessfully on e99e19ed385f2c9ea5e1ff655cee9aa9e13d20db<br /><br />After the page loads the description is hidden.  When the page is refreshed, the description is displayed for a fraction of a second and then it disappears.

Tested in Joomla 4.1.3-dev of 26 April in Wampserver 3.2.8 using PHP 8.0.15 in Google Chrome Version 101.0.4951.41 (Official Build) (64-bit)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37671">issues.joomla.org/tracker/joomla-cms/37671</a>.</sub>

**Comment by Kostelano** [comment]
I have reproduced the problem you describe, but this is not related to the PR. The description string does not affect this behavior.

When the page is reloaded, ALL parameter descriptions are displayed for half a second.

**Comment by toivo** [comment]
I would have thought that the field descriptions should be available as tooltips, when the cursor hovers above the title of the field.  Displaying the descriptions for half a second only is a UX problem.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e99e19ed385f2c9ea5e1ff655cee9aa9e13d20db<br /><br />The patch works as described. When the Toggle-inline-help is activated, the description is visible. 

I confirm the  "half-second-visible" effect but this is another issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37671">issues.joomla.org/tracker/joomla-cms/37671</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e99e19ed385f2c9ea5e1ff655cee9aa9e13d20db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37671">issues.joomla.org/tracker/joomla-cms/37671</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37671">issues.joomla.org/tracker/joomla-cms/37671</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
