### PR TITLE
[4.4] text not visible (error_login)

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #42600 .

### Summary of Changes
add class text-dark to the h1 to force it to be visible

### Testing Instructions
do not log in to the backend
visit https://example.tl/administrator/index.php?option=com_admin&view=sysinfo&format=text

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
It will be a regression with v5 in dark mode.

42616-dark-mode

**Comment by brianteeman** [comment]
The PR is for j4 ;)

**Comment by dautrich** [comment]
I have successfully tested this PR on J4.4 Stable.
Should I use the issue tracker to document my successful test?

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 87dfabec329264cd6f9b36f8c599cef2ef2f8588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42616">issues.joomla.org/tracker/joomla-cms/42616</a>.</sub>

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 87dfabec329264cd6f9b36f8c599cef2ef2f8588<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42616">issues.joomla.org/tracker/joomla-cms/42616</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42616">issues.joomla.org/tracker/joomla-cms/42616</a>.</sub>

**Pull request merged**
