### PR TITLE
Trigger full suite of events in com_contact

### PR DESCRIPTION
**Pull request by wilsonge**
The first part of a bigger set of PR's to try and have more consistent Joomla events triggered. There's also a set of code style fixes as well within the PR.

This PR targets the frontend view of com_contact (and by proxy ALL frontend category views as they use a shared JLayout and JViewCategory class)

### CODE REVIEW

**Comment by brianteeman** [comment]
@wilsonge after almost a year and with zero comments (probably because of the lack of meaningful description) can this just be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3630">issues.joomla.org/joomla-cms/3630</a>.</sub>

**Comment by Harmageddon** [comment]
@wilsonge As I need some plugin triggers on com_contact for a project, I just wanted to create a similar PR, until I found this one. Do you mind if I open and test this one or should I rather create a new one?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3630">issues.joomla.org/joomla-cms/3630</a>.</sub>

**Comment by Harmageddon** [comment]
New PR for this functionality: #8024

**Comment by wilsonge** [comment]
Hey I'm sorry I never replied on here or glip. I've been running around like crazy the last month with 2 joomla events, a major work deadline and other personal stuff. Thanks so much for taking up me slacking on this!! It's super appreciated!

**Comment by Harmageddon** [comment]
No problem at all, I know these "Why does a day only have 24 hours" phases very well, too. Just had some spare time and thought, I'll just do it. :wink:

**Pull request closed without merging**
