### PR TITLE
[4.0] Media field no preview

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/34921 .

### Summary of Changes
-  pick the right extension regardless of the url (code was only working for local adpters)

### Testing Instructions

Test that local files have a preview
Test that remote files have apreview

### Documentation Changes Required

@laoneo

### CODE REVIEW

**Comment by richard67** [comment]
@dgrammatiko JS linter complains about 2 missing semicolons: https://ci.joomla.org/joomla/joomla-cms/46175/1/21

**Comment by laoneo** [comment]
Works :+1:

**Comment by richard67** [comment]
> Works 👍

@laoneo Then mark your test result in the issue tracker. Thanks in advance.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
