### PR TITLE
[4.0] Can't search redirects

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25429.

### Summary of Changes

Removes `required` attribute from a field.

### Testing Instructions

Go to Redirects.
Search for keywords.

### Expected result

Form submitted.

### Actual result

Form not submitted, "Please fill out this field." prompt is shown by browser.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 338f033f6ba80d138e149139fa8737d454a4a371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25442">issues.joomla.org/tracker/joomla-cms/25442</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 338f033f6ba80d138e149139fa8737d454a4a371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25442">issues.joomla.org/tracker/joomla-cms/25442</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
@HLeithner @wilsonge so its ok to remove the required field here but not where it actually makes sense for the form to remove required fields? 🤦‍♂

**Comment by SharkyKZ** [comment]
@brianteeman, here the attribute only exists in HTML markup, not in XML form definition. It can only perform client-side validation. Your concern relates to uses that affect server-side validation. This is something that needs to be a addressed on a case-by-case basis.

**Comment by brianteeman** [comment]
And it's not. It's arbitrary and inconsistent

**Comment by wilsonge** [comment]
Well the correct solution to this is that batch should be a separate form. And this should be required in that form. My guess is that this is the only place in the CMS where this is the only field (and by proxy required in a batch form)

Can someone check if there are any other places where batch is a separate form? If there's not we can remove this temporarily and try and refactor batch in another PR so we can reintroduce it. If there is already places were we have separate batch forms then let's get it right first time :)

**Comment by brianteeman** [comment]
this is the only place. I guess it was created at a later date to the bulk import as that uses the batch ;(

**Comment by wilsonge** [comment]
OK I'm merging this to unblock but i think we've identified the longer term issue here and I've captured that in https://github.com/joomla/joomla-cms/issues/25489

**Pull request merged**
