### PR TITLE
Workflows Default - message

### PR DESCRIPTION
**Pull request by brianteeman**
Change the messages when you try to make multiple items the default workflow/stage

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
Could someone with necessary privileges remove the "PR-staging" label? Bot hasn't done that.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e0e89d7925d7da626ac33c53ac44b3c241a0f03a<br /><br />Very good change. We should get rid of generic error messages like "Too many items selected" wherever possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26886">issues.joomla.org/tracker/joomla-cms/26886</a>.</sub>

**Comment by brianteeman** [comment]
@richard67 most of them have already gone. Just finding the last ones

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e0e89d7925d7da626ac33c53ac44b3c241a0f03a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26886">issues.joomla.org/tracker/joomla-cms/26886</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26886">issues.joomla.org/tracker/joomla-cms/26886</a>.</sub>

**Comment by alikon** [comment]
i'm unprivileged too :smile:

**Comment by richard67** [comment]
But you can say "RTC" and bot sets "RTC". Can I do that, too, and just don't know it yet because never tried?

**Comment by alikon** [comment]
i think so.... i've allowed all jbs members to set RTC....if not please just send me a msg on glip...i'll investigate more ....with my low power

**Comment by zero-24** [comment]
Merging thanks. Please ping me on Glip at label issues.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
