### PR TITLE
Improvements for JLibraryHelper

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
Alternative solution for #14046

Instead load all libraries as it was done in previous PR this PR load only one and cache it alone.
Introduce a new method `loadLibrary($element)` and deprecate `_load($element)` method. 

### Testing Instructions
The same as in previous PR.

### Documentation Changes Required
Document the deprecation.

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 2b91bb5654a56530c6d44d0ea8737df9881c0df3<br /><br />Tested with both cache on and off. Everything is working as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14172">issues.joomla.org/tracker/joomla-cms/14172</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@joomdonation can you please write how you tested cause i don't understand #14046-instructions.

**Comment by csthomas** [comment]
I have tested by interactive console https://github.com/joomla/joomla-cms/pull/14046#issuecomment-281197263 which may be not available on a lots of php installs.

But you can open your template index.php file and paste:
```
print_r(JLibraryHelper::getLibrary('phpass', true));
print_r(JLibraryHelper::getLibrary('fof', true));
print_r(JLibraryHelper::getLibrary('phputf8', true));

// Repeat again to test data from cache
print_r(JLibraryHelper::getLibrary('phpass', true));
print_r(JLibraryHelper::getLibrary('fof', true));
print_r(JLibraryHelper::getLibrary('phputf8', true));
```

And test it with cache enabled and disabled. Result on page should be the same.
  
Optional with cache enabled you can open page a few times to check whether the cache is reused and does not recreated each time.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 2b91bb5654a56530c6d44d0ea8737df9881c0df3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14172">issues.joomla.org/tracker/joomla-cms/14172</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14172">issues.joomla.org/tracker/joomla-cms/14172</a>.</sub>

**Pull request merged**
