### PR TITLE
Fix com_contact > created vcf in contactform can´t handle german umlauts (issue #7937)

### PR DESCRIPTION
**Pull request by coolcat-creations**
Steps to reproduce the issue

Put in some contact information with ß ä ö ü inside and enable the Option .vcf for the contact view.
Download the vcf

Expected result

The vcf should contain the umlauts.

Actual result

On Apple devices the umlauts are shown correctly but but not in outlook on windows.

System information (as much as possible)

Additional comments

I added utf8decoding in the code, that fixes the problem. As i´m not a developer please review also the way how i fixed it.

This fixes issue: https://github.com/joomla/joomla-cms/issues/7937

### CODE REVIEW

**Comment by rdeutz** [comment]
Not bad for a non developer :-) 

Indentation gets lost somewhere and the comment is in German, fine for me but not the usual way we are doing it. Some code style issues on top.

Pretty normal for the first PR :-)

**Comment by infograf768** [comment]
This breaks UTF8 characters here.
utf8_decode converts a UTF8 string into ISO-8859-1

so it may work for some latin characters (for example with umlauts) but not for Greek or Chinese, etc.

**Comment by rdeutz** [comment]
@infograf768 does it work with Greek/Chinese without this patch?

**Comment by infograf768** [comment]
It does on Macintosh:
I added `ä ݑώ⽋` i.e. an umlaut, an arabic, a greek and a japanese character in a few fields.
This is the vcf I get before this PR
```
BEGIN:VCARD
VERSION:3.0
N:Here;Contact;Name
FN:Contact Name Here
TITLE:Position ä ݑώ⽋
TEL;TYPE=WORK,VOICE:2224556
TEL;TYPE=WORK,FAX:Fax
TEL;TYPE=WORK,MOBILE:
ADR;TYPE=WORK:;;Street ä ݑώ⽋;City ä ݑώ⽋;State ä ݑώ⽋;;country ä ݑώ⽋
LABEL;TYPE=WORK:Street ä ݑώ⽋
City ä ݑώ⽋
State ä ݑώ⽋

country ä ݑώ⽋
EMAIL;TYPE=PREF,INTERNET:email@xn----7sblgc4ag8bhcd.xn--p1ai
URL:http://www.xn----7sblgc4ag8bhcd.xn--p1ai/master
REV:2015-09-24T09:47:00+02:00Z
END:VCARD 
```
This is what we get after this patch...

```
BEGIN:VCARD
VERSION:3.0
N:Here;Contact;Name
FN:Contact Name Here
TITLE:Position ä ???
TEL;TYPE=WORK,VOICE:2224556
TEL;TYPE=WORK,FAX:Fax
TEL;TYPE=WORK,MOBILE:
ADR;TYPE=WORK:;;Street ä ???;City ä ???;State ä ???;;country ä ???
LABEL;TYPE=WORK:Street ä ???
City ä ???
State ä ???

country ä ???
EMAIL;TYPE=PREF,INTERNET:email@xn----7sblgc4ag8bhcd.xn--p1ai
URL:http://www.xn----7sblgc4ag8bhcd.xn--p1ai/master
REV:2015-09-24T09:47:00+02:00Z
END:VCARD
```
Each non-latin glyph is replaced by a ?

**Comment by infograf768** [comment]
See last post here:
http://stackoverflow.com/questions/7240532/php-generated-vcard-change-character-encoding-so-accented-character-can-be-disp?lq=1

**Comment by designbengel** [comment]
@infograf768 on a apple it works with german umlauts also, but not in win outlook

**Comment by infograf768** [comment]
`on a apple it works with german umlauts also, but not in win outlook`

Yes, as stated in the link I gave above. We can't though provide wrong vcf because Windows is a piece of  s...  :smile: 

In any case the solution provided here does not work.

**Comment by balzercomp** [comment]
You should add the coding to the lines containing the value.
For UTF-8 this means: 
FN:Contact Name Here 
becomes 
FN;CHARSET=UTF-8:Contact Name Here

**Comment by infograf768** [comment]
all what i have read on the net says it will not help for microsoft apps.

**Comment by balzercomp** [comment]
You'r right. I just tested it on the latest outlook with win 10. Doesn't work. Seems that microsoft doesn't obey standards again. Vcard version 3.0 requires the values to be in UTF-8.

**Comment by balzercomp** [comment]
Maybe it would be useful to build a switch that allows to export in different codesets depending on the browser's OS.

**Comment by infograf768** [comment]
Not so simple:
1. Check that the string concerned contains <b>ONLY</b> ISO-8859-1 glyphs (or CP1252 for windows)
2. Check that the browser OS is Windows
3. Change the vcard version to 2.1 (3.0 does not use charset and has to be utf8)
4. Add the charset if all the conditions are met.

**Comment by infograf768** [comment]
In any case the view 
ROOT/components/com_contact/views/contact/view.vcf.php
can be overriden in the template if one is sure all contacts info will be ISO-8859-1
List is here:
http://goodtools.net/pages/HowCharactersMap.html

**Comment by Hackwar** [comment]
Sorry, but based on the feedback by @infograf768 and that this seems to be a bug in Outlook, I think this PR should be closed. I'm not using Outlook on my Windows system and I'd rather have standards-compliant output than account for one program. (Even though it is admittedly the one with the largest distribution)

**Comment by roland-d** [comment]
From what I understand it now doesn't work anywhere with UTF-8 characters, at least with the patch it works for people using a Mac? Is that correct? If so, I believe we should more this forward otherwise we may as well close it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7938">issues.joomla.org/joomla-cms/7938</a>.</sub>

**Comment by brianteeman** [comment]
No. @infograf768 said it worked on a Mac without this patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7938">issues.joomla.org/joomla-cms/7938</a>.</sub>

**Comment by roland-d** [comment]
Closing this PR because it can't solve the issue. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7938">issues.joomla.org/joomla-cms/7938</a>.</sub>

**Pull request closed without merging**
