### PR TITLE
Plugin System - Redirect - Display error 404 instead 500 when page does not exist [postgresql, sqlsrv]

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/13262#issuecomment-279743085

### Summary of Changes
In table `#__redirect_links` column `comment` does not have a default value.

On J4 mysql error should be visible.
On postgresql and sqlsrv error exists. 

### Testing Instructions
Install fresh joomla staging on postgresql or sqlsrv database.
Enable System - Redirect plugin
Go to not exists page like "index.php?option=sdfsdf"

Before patch:
Error 500 PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE 
After patch:
Error 404

### Expected result
ERROR 404

### Actual result
ERROR 500

### Documentation Changes Required
None

### CODE REVIEW

**Comment by waader** [comment]
Works for mssql. For postgresql it works when I change the line to
"comment" varchar(255) DEFAULT '' NOT NULL,

**Comment by csthomas** [comment]
I will fix it in a few moments

**Comment by csthomas** [comment]
@waader I have seen more similar bugs in joomla.sql file for postgresql or I'm wrong.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on cb4e027c0c86726c20b79b8c97254da2ab15bc16<br /><br />Before the last change I got an installation error. Now it works fine. As I get no other errors everythings seems ok, at least at my side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14093">issues.joomla.org/tracker/joomla-cms/14093</a>.</sub>

**Comment by csthomas** [comment]
It is not related to this PR, but can you check if you have correct installed tables like:
#__postinstall_messages
#__ucm_content
#__ucm_history
#__content_types
#__contentitem_tag_map

which also uses "NOT NULL DEFAULT ..."

**Pull request merged**
