### PR TITLE
[4.0] Fix color of Yes/No button in Versions

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove class so Yes/No button change color on hover.

### Testing Instructions
Edit an article.
Click Versions button.
Hover cursor on Yes/No button under Keep Forever column.

### Actual result BEFORE applying this Pull Request
Black button with no visual change on hover.

### Expected result AFTER applying this Pull Request
Blue button and on hover change to black button.

### CODE REVIEW

**Comment by ChristineWk** [comment]
Don't get Expected Result
4.0.0-rc4-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34668">issues.joomla.org/tracker/joomla-cms/34668</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on abb078275f1e728133c9bf76c329febe1c7292cb<br /><br />Ah, checked again and saw it now. The blue is so dark :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34668">issues.joomla.org/tracker/joomla-cms/34668</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on abb078275f1e728133c9bf76c329febe1c7292cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34668">issues.joomla.org/tracker/joomla-cms/34668</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34668">issues.joomla.org/tracker/joomla-cms/34668</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
