### PR TITLE
Update en-GB.com_joomlaupdate.ini

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #10132 
#### Summary of Changes

Change Upload and Install to Upload and Update as the name of the tab has changed in current staging

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 54b464e0299c5e0429bfa0a3329e8f086417137d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10133">issues.joomla.org/joomla-cms/10133</a>.</sub>

**Comment by infograf768** [comment]
RTC, this can be merged on Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10133">issues.joomla.org/joomla-cms/10133</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Comment by rdeutz** [comment]
If I am not wrong then we have Language freeze and this has to wait for 3.5.3

**Comment by infograf768** [comment]
we have Installation lang freeze as far as I know
General lang freeze has not been yet posted

**Comment by brianteeman** [comment]
Language freeze is for the installation files

On 29 April 2016 at 16:37, Robert Deutz <notifications@github.com> wrote:

> If I am not wrong then we have Language freeze and this has to wait for
> 3.5.3
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10133#issuecomment-215763021>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rdeutz** [comment]
this is always save point for confusing me, I ask in the PLT chat and @roland-d said "The lang freeze has been announced already" "Last Thursday"

**Comment by rdeutz** [comment]
ok, now I got it

**Comment by mbabker** [comment]
Where was the announcement?  Used to go out on the CMS mailing list; I've got all the messages for April still in my inbox and there aren't any freeze announcements...

screen shot 2016-04-29 at 10 44 59 am

**Comment by rdeutz** [comment]
@Bakual should know

**Comment by brianteeman** [comment]
Yeah there is usually a post in the Google group but not this time.
@wilsonge told me about it.

**Comment by roland-d** [comment]
I don't know who makes the announcements but perhaps Mig has yet to do so.

**Pull request merged**
