### PR TITLE
[a11y] toolbar

### PR DESCRIPTION
**Pull request by brianteeman**
Complete the work to ensure that the font icons in toolbar buttons have an aria-hidden value to prevent the value of the font being read by assistive technology

{note that some of the toolbar buttons eg batch and help were already fixed in another PR that may not have been merged yet)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f717aa28a5405c0cc243ce63c98d925e4c606e99<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15054">issues.joomla.org/tracker/joomla-cms/15054</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on f717aa28a5405c0cc243ce63c98d925e4c606e99<br /><br />Code Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15054">issues.joomla.org/tracker/joomla-cms/15054</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
