### PR TITLE
Regression: hide menu in com_config breaks hathor!

### PR DESCRIPTION
**Pull request by dgrammatiko**
Solves #5906

### CODE REVIEW

**Comment by brianteeman** [comment]
Just to be clear - is this PR supposed to keep the menu disabled or not

On 29 January 2015 at 16:26, Dimitris Grammatiko <notifications@github.com>
wrote:

> Solves #5906 <https://github.com/joomla/joomla-cms/issues/5906>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/5925
> Commit Summary
>
>    - hidemenu breaks hathor!
>
> File Changes
>
>    - *M* administrator/components/com_config/view/application/html.php
>    <https://github.com/joomla/joomla-cms/pull/5925/files#diff-0> (1)
>    - *M* administrator/components/com_config/view/component/html.php
>    <https://github.com/joomla/joomla-cms/pull/5925/files#diff-1> (1)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/5925.patch
>    - https://github.com/joomla/joomla-cms/pull/5925.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5925>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
No this reverts the #4844. Unfortunately I am on tight schedule right now to do a proper solution (keep menu disabled and gator happy)

**Comment by brianteeman** [comment]
@test confirm the bug and confirm that this reversion of a previous PR resolves it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5925">issues.joomla.org/joomla-cms/5925</a>.</sub>

**Comment by brianteeman** [comment]
As this is just reverting a PR to the previous good status seen in 3.3.6 I am setting this RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5925">issues.joomla.org/joomla-cms/5925</a>.</sub>

**Pull request merged**
