### PR TITLE
Maintenance submenu

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This simple PR aggregates com_checkin and com_cache menu option in a "Maintenance" submenu,

Note the titles of the views already follow that logic.

image

image

image
##### Before PR

image
##### After PR

image
#### Testing Instructions
1. Use latest staging
2. Apply patch
3. Check the "System" menu

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 0cb62a2626026b5f7556bb558034b4d404d18533<br /><br />Back to the 2.5's :smile: 

Works as described - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9840">issues.joomla.org/joomla-cms/9840</a>.</sub>

**Comment by andrepereiradasilva** [comment]
don't even remember how it was in 2.5.x :)

**Comment by brianteeman** [comment]
You forgot to check Hathor ;)

**Comment by brianteeman** [comment]
Joomla 2.5
7i65

**Comment by andrepereiradasilva** [comment]
if you want my honest opinion. i'm don't really like to make changes in hathor because IMHO is wasted time.

hathor can live perfectly good without the submenu ... hathor menus doesn't need to be like (and they aren't) isis menus.

**Comment by andrepereiradasilva** [comment]
:smile: yes just like 2.5. IMO in this case the 2.5 way is better

**Comment by MATsxm** [comment]
@andrepereiradasilva 
I would say that everyone agrees with your about Hathor but as long as we have not a real admin template respecting the a11y basics, we will have to deal with it.

**Comment by andrepereiradasilva** [comment]
and hathor with all the changed added respects that a11y basics??

**Comment by MATsxm** [comment]
Not what I said...
Just try to explain with my tarzan frenglish that as long as the goal of hathor was accessibility (not saying it reaches this goal) and as long as we have no other adequate response...
at least, that is what was explained to me :wink:

**Comment by andrepereiradasilva** [comment]
anyway, as i said this changes are not needed in hathor, as hathor doesn't have to add exactly the same menu as isis.

**Comment by andrepereiradasilva** [comment]
i now that was the goal.

I worked with accessibility in web sites/apps for quite some time and i never used another template to do the job.

**Comment by andrepereiradasilva** [comment]
sorry, wrong button...

**Comment by andrepereiradasilva** [comment]
FYI just checked the admin control panel in a auto accessibility WCAG 2.0 test tool:
- Isis: 4 errors in WCAG 2.0
- Hathor: 2 errors in WCAG 2.0

Note: i know there are also manual tests there should be made and all pages need to be checked. just to prove the point.

**Comment by MATsxm** [comment]
no need to proove something known...

**Comment by andrepereiradasilva** [comment]
Ok then.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0cb62a2626026b5f7556bb558034b4d404d18533<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9840">issues.joomla.org/joomla-cms/9840</a>.</sub>

**Comment by brianteeman** [comment]
I am setting this to needs review so the maintainers can make a decision. I am assuming that there was a reason the behaviour changed from 2.5 and also a decision about it not being applied to hathor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9840">issues.joomla.org/joomla-cms/9840</a>.</sub>

**Comment by andrepereiradasilva** [comment]
is there a label "Needs review" to more clearly identity the PR that needs review so they don't go inside the black hole?

**Comment by brianteeman** [comment]
Right now the Needs Review is only in the issue tracker not github. (I will ask and see what they think about adding it on github as well.)

During the sprint next month I will be forcing the plt members there to make a decision on all the needs review issues ;)

**Comment by wilsonge** [comment]
*gulp*

**Comment by brianteeman** [comment]
I can add the label on github and manually update those issues there as well (if you want)

**Comment by wilsonge** [comment]
Ok I have no clue what the original intention was by the UX team in 3.x - but in my opinion less clicks (i.e. submenu's) is better. So I'd rather keep what we have and amend the language strings to be honest!

This kinda makes the hathor question redundant. But my opinion there is that Hathor is a separate template with different styling so it doesn't have to visually be exactly in sync with ISIS, however it does need to work..... so whatever makes sense - in this case I'd probably have applied it there as it's dead simple and it's easier to maintain them in parallel. But it doesn't mean as a rule of thumb every single change to ISIS must be applied to Hathor.

**Comment by andrepereiradasilva** [comment]
ok so this is a no go. fine.

**Pull request closed without merging**
