### PR TITLE
[#33392] Repeatable form fields fix (2)

### PR DESCRIPTION
**Pull request by Fedik**
What here:
- complete rewritten script
- fixed multiple instances on the one page
- fixed rows duplication
- fixed some fields that stopped work right, after duplication
- fixed "to big modal" - added scroll
- each new row will be added after the row where the button "add" was clicked, as  alternative for "sortable" :wink: 

Links:
- [[#33392] Repeatable form fields fix](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33392&start=0), maybe some other already exist to 
- related on github, that I found #3192 #3564 #3573 #3214

XML that I use for testing:

``` xml
<field name="test" type="repeatable" icon="list"
        label="Test" description="Test descr"
        default=""
        maximum="5">
    <fieldset hidden="true" repeat="true">
        <field name="test_color" type="color" default="#eee"
            label="color"  description="test_color" />

       <field name="test_tag" type="tag"
            label="JTAG" description="test_tag" mode="nested"
            multiple="true" />

        <field name="test_list" type="list" default="1"
            label="test_list" description="test_list" >
            <option value="1">JYES</option>
            <option value="0">JNO</option>
        </field>

        <field name="test_text" type="text"
            label="test_text" description="test_text" />

        <field name="test_textarea" type="textarea"
            label="textarea"  width="100" />

        <field name="test_radio" default="0" type="radio"
            label="test_radio" description="test_radio">
            <option value="1">JYES</option>
            <option value="0">JNO</option>
        </field>

        <field name="test_checkbox1" type="checkbox"
            label="checkbox1" description="test_checkbox1"  />

        <field name="test_checkboxes" type="checkboxes"
            label="checkboxes" description="test_checkboxes" >
            <option value="a">A</option>
            <option value="b">B</option>
            <option value="c">C</option>
            <option value="d">D</option>
        </field>

        <field name="test_media" type="media" directory=""
            label="media" description="test_media"/>

    </fieldset>
</field>

```

And of course can be used existing, if someone already have.

Who brave enough to make a test? :smirk:

### CODE REVIEW

**Comment by motamedimasoud** [comment]
FEDIK Please Help me man please...I have problem with field type media in repeatable..when i use this i choose for example one pic when i want to save or cancell that page doesnt do anything..how can i fixed that its make me old plaeas help me

**Comment by losedk** [comment]
@motamedimasoud Could you provide your xml code?

**Comment by Fedik** [comment]
@motamedimasoud do backup of your site, then download and replace to new files:
[libraries/joomla/form/fields/repeatable.php](https://raw.githubusercontent.com/joomla/joomla-cms/staging/libraries/joomla/form/fields/repeatable.php)
[media/system/js/repeatable.js](https://raw.githubusercontent.com/joomla/joomla-cms/staging/media/system/js/repeatable.js)
[media/system/js/repeatable-uncompressed.js](https://raw.githubusercontent.com/joomla/joomla-cms/staging/media/system/js/repeatable-uncompressed.js)

in theory should help :smile:

**Comment by motamedimasoud** [comment]
FEDIK THANK U ALOT I LOVE U SO MUCHHHHHHHHHHHHHHHHH IT WORKED THANK U I WANT TO KEEP IN TOUCH WITH U PLEASE GIVE ME YOURM EMAIL ADDRESS I NEED U MY EMAIL ADDRESS IS MOTAMEDI_MASOUD@YAHOO.COM PLZ SEND ME AN EMAIL THANK U AGAIN MAN

**Comment by degobbis** [comment]
Does anyone know a patch to use the field "moduleposition" in a repeatable field?

**Comment by jrseliga** [comment]
The format of the JSON stored from a repeatable seems counter intuitive. Take for example:

repeatable

It stores the following JSON string.
```
{
	"title":
		["Beach","Mountains"],
	"caption":
		["Sun","Snow"],
	"link":
		["Home","Home"],
	"image":
		["beach.jpg","mountains.jpg"]
}
```
That data structure isn't representative of the input from the user.

A structure similar to the one below is a better representation. Each value is associated with a row in the repeatable, and is also more friendly to decoding into an array for iterative purposes.
```
"0":
	{
		"title": "Beach",
		"caption": "Sun",
		"link": "Home",
		"image": "beach.jpg"
	},
"1":	
	{
		"title": "Mountains",
		"caption": "Snow",
		"link": "Home",
		"image": "mountains.jpg"
	}
```

**Comment by OLSA** [comment]
Hello for all.
I respect all your hard works with Joomla repeatable form fields, but I I use different approach to get same things (no other popups inside main popup etc...)... 
More about my Multipler module that at: http://olsa.me/joomla-extensions/3-repeatable-section-module

Sorry  @Fedik  because I write about it here, but if it is interesting I will create repository for that.

Thanks and regards for all.

**Comment by wilsonge** [comment]
@jrseliga I agree with this - the problem is that we just can't do this for the form field anymore because of b/c. Users who are using this field (yes there are some poor poor people who tried it before this patch) now expect the current data structure. And it's not even like we can find all the database tables currently using this structure and alter them either.... :( It would need a 'new' form field.

**Comment by jrseliga** [comment]
@wilsonge I don't know the process of deprecating code, it seems to me that it would be wise to create that "new" form field (repeatable2 or something) that addresses this issue. Mark the current as deprecated and remove it for a future 3.x or the 4.0 release. I would argue that the current JSON format approaches unusable, if nothing else it requires some ugly code once decoded into "usable" PHP array.

**Comment by okonomiyaki3000** [comment]
It may not require a new field type. Maybe you just need an attribute in the on the `<field>` tag to specify which format you want to save as.

**Pull request closed without merging**
