### PR TITLE
[4.0] Remove extra type attribute

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix markup where it has two type attributes.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c2f2401f0beefa6498155031af6a25ff46792847<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23753">issues.joomla.org/tracker/joomla-cms/23753</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c2f2401f0beefa6498155031af6a25ff46792847<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23753">issues.joomla.org/tracker/joomla-cms/23753</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23753">issues.joomla.org/tracker/joomla-cms/23753</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
