### PR TITLE
Merge JoomlaUpdate into Installer (beta)

### PR DESCRIPTION
**Pull request by dakuzen**
Pull Request for Issue #9547.
# Merge JoomlaUpdate into Installer (beta)
#### Objectives
- Eliminate the separation between `com_joomlaupdate` and `com_installer`, and deprecate the `com_joomlaupdate` component.
- Work toward a simplification of the entire package installation and update classes and procedures.
- Restrict changes to `com_installer` at this time to validate direction.
#### Assertions
- Joomla! will benefit from the centralization & simplification of package management.
- No insurmountable challenges prevent centralized installation logic for all packages.
- Isolating the installer from runtime will allow for the future use of 3rd party package managers.
#### Approach
- The standalone features in `com_joomlaupdate` has been merged into `com_installer` so that all installations and upgrades are processed using the forked installer and monitor.  The same Akeeba restore code is still used, with a second Joomla! forked installer for non-core packages.
#### Testing Instructions
- Create a Joomla! package containing a [joomla.xml](https://gist.github.com/dakuzen/5ef728525d64ba24daa235fabe601263) file and install using the extension installer.
- Configure your Joomla! installation to pull core updates from a custom server, recreate the required [xml](http://update.joomla.org/core/list.xml) files, and stage a customized Joomla! package containing the [joomla.xml](https://gist.github.com/dakuzen/5ef728525d64ba24daa235fabe601263) file, then perform an extension update.
#### Summary of Changes
- Joomla! core updates were made visible in the Extension Update list.
- All `install` and `update` controller events that performed installation were supplanted with logic to direct the procedure to a new `installer` controller.
- A new `installer` controller and model were added that receive requests for single or batch installation.
- The `com_joomlaupdate` monitor and standalone installer logic was ported into the new `installer` operation.
- The Akeeba restore engine was ported and upgraded to support package folders.
- A Joomla! standalone installer was created.
#### Issues & Considerations
- During installation we are unpacking using a new `InstallerModelInstall -> initialize` operation that separates the previous unpacking and installation operations.  The net result of this method is the set the `package` state value for the model and return true on success.  This should be further compressed into the core `JInstaller` class.
- The forked Joomla! installer that is launched for `extension` processing currently requires the Joomla! kernal / library.
- The `com_joomlaupdate` features that deal with instructions and notification have not been ported.  This could best be refactored into a standard for all packages to share, allowing updates and upgrade notices for all packages.
- A standard for the installer provider needs to be defined along with considerations toward deprecating all `JUpdate` class operations into the `JInstaller` class.
- Management of the forked installer should be controlled by the `JInstaller` class to eliminate dependency on the `com_installer` controller.
- The `JInstaller` class dependencies need to be isolated & minized so that it can be included for standalone operations.

### CODE REVIEW

**Comment by brianteeman** [comment]
Note to testers this can not be tested using com_patchtester<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9793">issues.joomla.org/joomla-cms/9793</a>.</sub>

**Comment by dakuzen** [comment]
@brianteeman I've not used the com_patchtester.  Is there a specific change required to work with that component?

**Comment by brianteeman** [comment]
no its a limitation of that component not your code

On 14 April 2016 at 16:49, Dakuzen <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I've not used the
> com_patchtester. Is there a specific change required to work with that
> component?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9793#issuecomment-210011981>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by joris85** [comment]
I think this is a good idea!
I use Watchfully though but it nice to have things on one place.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9793">issues.joomla.org/joomla-cms/9793</a>.</sub>

**Comment by brianteeman** [comment]
Setting to Needs Review before any more time is spent on this to see if this is a route that we want to go down or not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9793">issues.joomla.org/joomla-cms/9793</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for your suggestion but the PLT has decided that this is not something that we will include in the core of Joomla! at the moment after balancing the pros and cons.

**Comment by joris85** [comment]
Well there could be technical pros and cons i think.

But i think like a user and cant see any Cons.
Stuf on one place is just easier and i like easy. 
If i update in jooma and extensions i am always a bit confused about the 2 different places and where to find the extensions update location (that difficult to find).

On my mac i also have 1 place for updates. Not one for my OS an one for my apps.

**Comment by dakuzen** [comment]
Out of curiosity @Kubik-Rubik, what are the "pros and cons" you levied in this decision?

**Comment by dakuzen** [comment]
I'm going to walk away from this but I will say it seems, as with mbabker's original rejection of this idea, that this is being dismissed for no reason other than an entrenchment with the recent separation agenda.

**Pull request closed without merging**
