### PR TITLE
Fix for #9888

### PR DESCRIPTION
**Pull request by cyrez**
See https://github.com/joomla/joomla-cms/issues/9888#issue-148012042 for screenshots showing issue, and to help testing this patch.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 868657309e687702b895c40bfe9bdc4a8359224a<br /><br />Almost but now the folder tree is not scrollable so only shows a partial tree<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9897">issues.joomla.org/joomla-cms/9897</a>.</sub>

**Comment by brianteeman** [comment]
Sorry that should have been a failed test

Almost but now the folder tree is not scrollable so only shows a partial tree

**Comment by andrepereiradasilva** [comment]
yes, i think it needs a scroll:
image

**Comment by JoomliC** [comment]
<blockquote>Almost but now the folder tree is not scrollable so only shows a partial tree</blockquote>
Yes i see, but it's not related to display issue, but to the fail of the layout to get the right $selector (i was just explaining it in your issuer report ;-)

**Comment by brianteeman** [comment]
All I know is that there was a scroll before

BTW before the scroll was on the entire page - i discovered this issue when
i was trying to write a PR that would make the left hand column scroll but
keep the right hand column fixed

On 13 April 2016 at 14:53, Cyril Rezé <notifications@github.com> wrote:

> Almost but now the folder tree is not scrollable so only shows a partial
> tree
>
> Yes i see, but it's not related to display issue, but to the fail of the
> layout to get the right $selector (i was just explaining it in your issuer
> report ;-)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9897#issuecomment-209451341>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
also, don't know if related with this PR, but in the content categories batch model when i select a operation the selectbox is hidden.

image

**Comment by JoomliC** [comment]
So, @brianteeman you can set an unsuccessfull test for now, as @andrepereiradasilva is right, it will break again the batch modals...

> BTW before the scroll was on the entire page - i discovered this issue when i was trying to write a PR that would make the left hand column scroll but keep the right hand column fixed

Yes it was scrolling, because in 3.5.0 RC, when BS modal was added, there was an issue with scrolling and i added a forced <code>overflow-y: auto !important</code> on modal-body.
This was not the best looking way to fix it, as in many cases, the scrolling appeared even if not needed.
That's why the redo for 3.5.2 (currently in staging).
But, this scrolling patch reveals now an other issue, with the way BS modal are implemented in com_templates not using the modal layouts...

So, i'm trying to check all this ;-)

**Comment by brianteeman** [comment]
Already changed my test on the tracker it just doesnt show on github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9897">issues.joomla.org/joomla-cms/9897</a>.</sub>

**Comment by JoomliC** [comment]
Thanks @brianteeman !

I have updated this PR to only the "display" issue, link to changes done few days ago in <code>.nav</code> classes by addition of <code>clear:both</code> needed as well for modal-footer to clear modal-body rendering.

About scrolling, it's another issue, due to hardcoded modals in com_templates, not using Joomla BS modals API (layouts).
I'm working as well on this change, which needs a bit of refactory.

Will do my best for a PR concerning this. ;-)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 95339d93e7f78f03af8eed24f12a2d8177a0860b<br /><br />> About scrolling, it's another issue, due to hardcoded modals in com_templates, not using Joomla BS modals API (layouts).
> I'm working as well on this change, which needs a bit of refactory.

So you will do another PR for that, right?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9897">issues.joomla.org/joomla-cms/9897</a>.</sub>

**Comment by JoomliC** [comment]
@andrepereiradasilva Exactly :+1: 
I'm working on it: com_templates (admin) modals refactory, with new views, and a minor improvement in the same time for the modal layout (better detection if scroll is needed in modal) ;-)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 95339d93e7f78f03af8eed24f12a2d8177a0860b<br /><br />Folder-Tree is now scrollable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9897">issues.joomla.org/joomla-cms/9897</a>.</sub>

**Comment by JoomliC** [comment]
> Folder-Tree is now scrollable.

@franz-wohlkoenig this PR needed to be tested on the last staging (due to last changes in .nav classes).

But, i close here, to include this display fix in the com_templates refactory of modals, to allow loading of the JLayouts modal including the core hack script to fix BS modal. (easier to have only 1 PR to be tested for modal ;-) )

So, close in favor of: https://github.com/joomla/joomla-cms/pull/9908

**Comment by JoomliC** [comment]
@andrepereiradasilva @brianteeman i've created a PR to improve a bit the html structure of modals in template manager, and in the same time, did it to have a scrolling on left column for the list of files/folders : https://github.com/joomla/joomla-cms/pull/10100
Maybe something you were thinking of ? ;-)

**Pull request closed without merging**
