### PR TITLE
Removed menutype variable in All Menu items menu link

### PR DESCRIPTION
**Pull request by tumbigani**
Pull Request for Issue # .
#### Summary of Changes

Removed Unnecessary variable of menutype in **All Menu Items** link. 
#### Testing Instructions

Please check All Menu Items link in administrator.  
_**index.php?option=com_menus&view=items&menutype=**_
I have removed **menutype** variable in link.

### CODE REVIEW

**Comment by hardikPTailored** [comment]
I have tested this item :white_check_mark: successfully on b82cca4f59006decf799226f464aa7a182370e1c<br /><br />I have tested this issue <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11073">issues.joomla.org/joomla-cms/11073</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :red_circle: unsuccessfully on b82cca4f59006decf799226f464aa7a182370e1c<br /><br />will not work.

simple test: change to another menu and then click "All menu item" the link in admin menu.
Is needed to reset to "All menu" when a menutype is already chosed is previous actions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11073">issues.joomla.org/joomla-cms/11073</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :red_circle: unsuccessfully on b82cca4f59006decf799226f464aa7a182370e1c<br /><br />&menutpe=
- allows clearing the menutype filter when **"populating" state**

See line:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/items.php#L98

```
$menuType        = $app->input->getString('menutype', $currentMenuType);
```

e.g. another example filter by "Registered" access your menus
then add to URL:
&filter_access=

you will see that the filter will be clear<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11073">issues.joomla.org/joomla-cms/11073</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as clearly the menutype is required<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11073">issues.joomla.org/joomla-cms/11073</a>.</sub>

**Comment by rahultomar** [comment]
I have tested this item :red_circle: unsuccessfully on b82cca4f59006decf799226f464aa7a182370e1c<br /><br />I have checked it, it is same as before<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11073">issues.joomla.org/joomla-cms/11073</a>.</sub>

**Pull request closed without merging**
