### PR TITLE
Change warning descriptions for minimum to 16MB

### PR DESCRIPTION
**Pull request by kochinc**
In administrator/components/com_installer/src/Model/WarningsModel.php the minimum required value for both post_max_size and upload_max_filesize is set to 16MB ($minMemory). The warning descriptions should reflect that.

Pull Request for Issue # (N/A).

### Summary of Changes

Correct minimum value in warning descriptions.

### Testing Instructions

Set post_max_size and upload_max_filesize to 10MB in /etc/php.ini.

### Actual result BEFORE applying this Pull Request

Got these 2 warnings in System -> Information -> Warnings, even though those values are larger than the minimum required shown in the warnings:

"Small PHP maximum POST size.
This is the maximum amount of data that can be sent via POST to the server. This includes form submissions for articles, media (images, videos) and extensions. This value is less than 8MB which may impact on uploading large extensions. This is set in the php.ini under post_max_size."

"Maximum PHP file upload size is too small.
The maximum file size for uploads is set to less than 8MB which may impact on uploading large extensions. This is set in php.ini in both the upload_max_filesize and post_max_size settings of your PHP settings (located in php.ini and/or .htaccess file). The value of post_max_size must be greater than the value of upload_max_filesize."

### Expected result AFTER applying this Pull Request

The correct warnings should be:

"Small PHP maximum POST size.
This is the maximum amount of data that can be sent via POST to the server. This includes form submissions for articles, media (images, videos) and extensions. This value is less than 16MB which may impact on uploading large extensions. This is set in the php.ini under post_max_size."

"Maximum PHP file upload size is too small.
The maximum file size for uploads is set to less than 16MB which may impact on uploading large extensions. This is set in php.ini in both the upload_max_filesize and post_max_size settings of your PHP settings (located in php.ini and/or .htaccess file). The value of post_max_size must be greater than the value of upload_max_filesize."

### Documentation Changes Required

None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 053a0ae0c60e20ba758b9cf73b8b3fafcae2d344<br /><br />The change of the messages is correct.

The corresponding change of the minimum sizes from 8 to 16 MB has been made with PR #34754 here https://github.com/joomla/joomla-cms/pull/34754/files#diff-0998cd4637eab77ec0459b0d09df3bf6c093d012ed0ec6e7f5ab3f19bd9c3a6c

Tested by code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35909">issues.joomla.org/tracker/joomla-cms/35909</a>.</sub>

**Comment by richard67** [comment]
P.S.: The string "COM_INSTALLER_MSG_WARNINGS_MEDMEMORYDESC" seems to be already ok, i.e. it seems to reflect already the change from PR #34754 , so the fix made here seems to be complete.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 053a0ae0c60e20ba758b9cf73b8b3fafcae2d344<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35909">issues.joomla.org/tracker/joomla-cms/35909</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35909">issues.joomla.org/tracker/joomla-cms/35909</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
