### PR TITLE
Add a native cache handler for APCu

### PR DESCRIPTION
**Pull request by mbabker**
Based on http://forum.joomla.org/viewtopic.php?f=709&t=909389&p=3368420#p3368420 and changes in PHP 7 (well, 5.5 really), this adds native support for cache handling using PHP's APCu extension.

To test, you must be in an environment where the APCu extension is enabled.  Set it as your chosen cache handler and validate cache data is processed as expected.

### CODE REVIEW

**Comment by JensKirk** [comment]
Working very well :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9167">issues.joomla.org/joomla-cms/9167</a>.</sub>

**Comment by JensKirk** [comment]
I have tested this item :white_check_mark: successfully on 41807b2cb96740ff050e4411330f872f459db12a<br /><br />Working :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9167">issues.joomla.org/joomla-cms/9167</a>.</sub>

**Comment by wilsonge** [comment]
As we're unlikely to get many testers on this. I'm going to merge this on review with the good test we have!

**Comment by infograf768** [comment]
Please add the new string in en-GB.lib_joomla.ini frontend too as these two files should be equal.

**Comment by infograf768** [comment]
Oops, please forget it. It's done.

**Pull request merged**
