### PR TITLE
Handle DB errors in content search plugin

### PR DESCRIPTION
**Pull request by alikon**
updated to handle DB errors like #6710, #6711,#6714,#6715 #6632 and for #6591

Testing info
simulate a db error

### CODE REVIEW

**Comment by nonumber** [comment]
@test Success

**Comment by nonumber** [comment]
Not sure if this should get merged with regards to discussion on https://github.com/joomla/joomla-cms/pull/6710

**Comment by dgt41** [comment]
@test ok

**Comment by brianteeman** [comment]
Setting RTC- thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6716">issues.joomla.org/joomla-cms/6716</a>.</sub>

**Pull request closed without merging**
