### PR TITLE
New feature: allow local URI rules

### PR DESCRIPTION
**Pull request by podlom**
This simple patch allows user to create redirect rules based on local URIs.
It is very useful then you migrate from one domain to another.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please provide a full set of instructions to enable people to test this. This should include the behaviour before and after the patch

**Comment by podlom** [comment]
Test instructions:

1. Behavior before patch: local URI redirects without domain name starting
with / does not work.
2. Behavior after patch: local URI redirects with domain name starting with
/ does work.

С уважением,
Тарас.


http://www.shkodenko.kiev.ua/
Программирование и разработка сайтов, Киев

**Comment by Kubik-Rubik** [comment]
@podlom Thank you for your contribution. This additional check is already implemented (starting from line 88 *// If no published redirect was found try with the server-relative URL*), so your proposal is redundant and not required. I will close this PR, feel free to comment on it and request a reopening.

A more interesting change would be that the plugin saves the URLs relatively, this would make the domain changing process easier!

**Comment by podlom** [comment]
Thank you, @Kubik-Rubik 
I think we shouldn't change anything in user input.
If he wants to save full URL - it should be done.
If he wants to save relative URI it should work as well as full URL.

**Comment by Kubik-Rubik** [comment]
@podlom I didn't mean the user input but the automatic saving process by the plugin. :-)

**Pull request closed without merging**
