### PR TITLE
[4.4] Broken language comment

### PR DESCRIPTION
**Pull request by brianteeman**
The recent security update has exposed a bug in a language string. You cannot have a " in a comment.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Comment 
This will need to be upmerged to j5 AND @tecpromotion will need to notify translators

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
Could you also fix:
- `PLG_FIELDS_IMAGELIST_PARAMS_DIRECTORY_DESC`
image

**Comment by brianteeman** [comment]
I did a quick grep and can't find any more

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8d2e4815b34fc837ff0a338ad4a4ca902fbb92ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42425">issues.joomla.org/tracker/joomla-cms/42425</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42425">issues.joomla.org/tracker/joomla-cms/42425</a>.</sub>

**Comment by MacJoom** [comment]
Thanks for fix

**Pull request merged**
