### PR TITLE
[4.0] br as html5

### PR DESCRIPTION
**Pull request by brianteeman**
Found a few more instances of `<br/`

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4a24441ef13a80ba8d3096dc0fdf57a4431db087<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24900">issues.joomla.org/tracker/joomla-cms/24900</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4a24441ef13a80ba8d3096dc0fdf57a4431db087<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24900">issues.joomla.org/tracker/joomla-cms/24900</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24900">issues.joomla.org/tracker/joomla-cms/24900</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
