### PR TITLE
remove tab on meta charset

### PR DESCRIPTION
**Pull request by 810**
On the template source you will see a tab on the meta.

Before:
before
After:
after

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ad2fb054cd206d37dfaf099fe96daedb9baaac5a<br /><br />Simple cosmetic change to align the `<meta charset="utf-8" />` with other meta in source<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12895">issues.joomla.org/tracker/joomla-cms/12895</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on ad2fb054cd206d37dfaf099fe96daedb9baaac5a<br /><br />It assumes that <jdoc:include type="head" /> is always correct intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12895">issues.joomla.org/tracker/joomla-cms/12895</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12895">issues.joomla.org/tracker/joomla-cms/12895</a>.</sub>

**Comment by Bakual** [comment]
That is actually the wrong place as it only works for HTML5 templates. If isHtml5 is false, the double tab will still appear.
The real question is where the double tab is being generated, and the answer is simple: In the template is an initial tab:
https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/index.php#L130

So you either trim the tab from the buffer before returning/echoing it or you remove the tab in the template.

**Comment by brianteeman** [comment]
But the code says this is only for html5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12895">issues.joomla.org/tracker/joomla-cms/12895</a>.</sub>

**Comment by 810** [comment]
if you remove the tab on the template itself, you have the same issue, but then on template:
dd

**Comment by mbabker** [comment]
You'd have to `ltrim()` the tab off when returning the contents.  If you're not in HTML5 mode, then whatever your first tag is will still have a tab, and we really don't need to litter the method with a `$isFirst` variable to decide whether to include the tab on stuff.

**Comment by andrepereiradasilva** [comment]
if you are going to that, please do it for all templates, including installation

**Comment by mbabker** [comment]
If you `return ltrim($buffer, $tab);` at the end of `JDocumentRendererHtmlHead::fetchHead()` that does fix it for all templates, instead of this specific fix which only works correctly if the template's in HTML5 mode.

**Comment by 810** [comment]
Ok, updated the code.

Works fine now. 
Next ocd todo: order by type

**Review by Bakual — APPROVED** [review]

**Comment by jeckodevelopment** [comment]
Can we go back to RTC?

**Comment by Bakual** [comment]
> Can we go back to RTC?

Without any tests?

**Comment by jeckodevelopment** [comment]
I saw your "Approval". Then let's go with tests

**Comment by Bakual** [comment]
Ah, that's just the new "Review" feature from GitHub 😄

**Comment by laoneo** [comment]
I would just do `trim($buffer);` then all the blancks and new lines are gone, or is this too radical?

**Comment by mbabker** [comment]
We're spitting back a "formatted" HTML string, so doing that would break all of that formatting.  Great if you're trying to compress the size of your HTML response but IMO not appropriate as a default behavior.

**Comment by Bakual** [comment]
trim would only remove whitespace from the beginning and end of the string. But since we know for sure there is only the tab in front of it, there is no reason to let trim look for other cases as well. It's just added work for trim without added value :smile:

**Comment by dgt41** [comment]
@laoneo I've tried something like what you're proposing couple years ago: https://github.com/joomla/joomla-cms/pull/3413

**Comment by laoneo** [comment]
@Bakual trim does also remove whitespaces and new lines http://php.net/manual/en/function.trim.php

**Comment by laoneo** [comment]
@dgt41 it is just about removing the beginning and ending characters, not the whole output

**Comment by mbabker** [comment]
We don't want to be trimming the ending line break from the end of the processed head, so what this patch is doing now is just fine.

**Comment by Bakual** [comment]
@laoneo Exactly. tabs and newlines count as whitespace as well. :smile:

**Comment by 810** [comment]
ok,then we can merge this one

**Pull request merged**
