### PR TITLE
Fix CS issues in the build script

### PR DESCRIPTION
**Pull request by zero-24**
This PR fix CS issues in the build script

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
@zero-24 Can you please remove the last comma in the array? Thanks!

**Comment by zero-24** [comment]
>@zero-24 Can you please remove the last comma in the array? Thanks!

@Kubik-Rubik why? see here for the array example: http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

>Assignments (the => operator) in arrays may be aligned with tabs. When splitting array definitions onto several lines, the last value may also have a trailing comma. This is valid PHP syntax and helps to keep code diffs minimal.

**Comment by Kubik-Rubik** [comment]
Ugly... ;-) Personally I would not use the commay in the last assignment but of course it is not an error:

*Having a trailing comma after the last defined array entry, while unusual, is a valid syntax.* (http://php.net/manual/en/function.array.php) 

Since it is a no-brainer (just syntax changes) I will merge it PR. Thanks @zero-24!

**Comment by zero-24** [comment]
Thanks @Kubik-Rubik

**Pull request merged**
