### PR TITLE
Media Version on installation (solves #12711)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/12711.

### Summary of Changes

Following @brianteeman idea this adds the current date (up to minute) as media version for installation.

### Testing Instructions

1. Code review
2. Go to `/installation/index.php?view=languages`, view page source and confirm media version DOES NOT EXISTS in js files
3. Apply patch
4. Go to `/installation/index.php?view=languages`, view page source and confirm media version EXISTS js files

### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
Tested successfully - (sha missing)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12713">issues.joomla.org/tracker/joomla-cms/12713</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on adcf21b1228374c2cee5524e70e682854c733510<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12713">issues.joomla.org/tracker/joomla-cms/12713</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment RTC?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12713">issues.joomla.org/tracker/joomla-cms/12713</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks

**Pull request merged**
