### PR TITLE
[4.0] Remove .button

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
There is no .button class.

### Testing Instructions
Code review.

or

Go to System > Plugins
Edit System - Redirect
Add entries under Exclude URLs.
Make sure icons work as before.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 04087a642efc5658b0c61a576fa1b9fa32295abb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32876">issues.joomla.org/tracker/joomla-cms/32876</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 04087a642efc5658b0c61a576fa1b9fa32295abb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32876">issues.joomla.org/tracker/joomla-cms/32876</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32876">issues.joomla.org/tracker/joomla-cms/32876</a>.</sub>

**Comment by meinhoonharsh** [comment]
I have not tested this item.<br /><br />I am trying to Test this, but when click on Apply Patch for this Patch, It says, "Could not connect to GitHub: No commit found for the ref remove-button"

Now What should I do to test this??
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32876">issues.joomla.org/tracker/joomla-cms/32876</a>.</sub>

**Pull request merged**
