### PR TITLE
[com_fields] Cf permission strings

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue #13327 

### Summary of Changes
Updated language strings to clarify com_fields permissions parameter Edit Value functionality

### Testing Instructions
New Edit Value language strings (Label and Description tooltip) should be seen at:
Content - fields - edit - permissions - Edit Custom Field Value
Users - options - permissions - Edit Custom Field Value
Component - Contacts - options - permissions - Edit Custom Field Value

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
Concerning Global Config, I see an error:
```ini
-COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any value of an item in any extension."
+COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any value of custom fields submitted in this extension."
```
it should be imho
```ini
COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any value of custom fields submitted in any extension."
```

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 5de4943ce104392800b63064b8c5f642267e1268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13384">issues.joomla.org/tracker/joomla-cms/13384</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 5de4943ce104392800b63064b8c5f642267e1268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13384">issues.joomla.org/tracker/joomla-cms/13384</a>.</sub>

**Comment by brianpeat** [comment]
I have tested this item :white_check_mark: successfully on 5de4943ce104392800b63064b8c5f642267e1268<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13384">issues.joomla.org/tracker/joomla-cms/13384</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13384">issues.joomla.org/tracker/joomla-cms/13384</a>.</sub>

**Pull request merged**
