### PR TITLE
[4.1] Schedule Tasks class

### PR DESCRIPTION
**Pull request by brianteeman**
The class mr-2 does not exist. I am assuming it is supposed to be margin-right so using logical css properties it is changed to me-2

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 026e89a7a771a1f60885c80b662f3ee08d9a562a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36247">issues.joomla.org/tracker/joomla-cms/36247</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5a0bec7cf91ab6ec433eb77495f1caab87acbbd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36247">issues.joomla.org/tracker/joomla-cms/36247</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36247">issues.joomla.org/tracker/joomla-cms/36247</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
