### PR TITLE
[com_fields] Hide tab when empty

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #13395.

### Summary of Changes
When a field will be shown on the front end, then an empty tab is shown on the back end.

### Testing Instructions
- Create a new article custom field and set the option "Show On" to front end
image
- Open an article in the back end.

### Expected result
Tab with name fields is not shown.

### Actual result
Empty tab with the name Fields is shown.

### CODE REVIEW

**Comment by cpfeifer** [comment]
I'm getting this on the field pages:
`Fatal error: Class 'FieldsHelperInternal' not found in administrator/components/com_fields/views/fields/view.html.php on line 95`

**Comment by zero-24** [comment]
That helper got moved we need to update that PR against staging / to the new name ;)

**Comment by zero-24** [comment]
See https://github.com/joomla/joomla-cms/pull/13316

**Comment by laoneo** [comment]
I guess @cpfeifer needs to update his Joomla installation to the latest staging.

**Comment by cpfeifer** [comment]
I have tested this item :white_check_mark: successfully on 60443b4427179aadc8d16c729389a5e9fd609d3a<br /><br />Tested in Articles, Contacts and Users and it looks good :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13456">issues.joomla.org/tracker/joomla-cms/13456</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 60443b4427179aadc8d16c729389a5e9fd609d3a<br /><br />Tab ist hidden, but in "Fields" and "Field Groups" in Article get Error:
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13456">issues.joomla.org/tracker/joomla-cms/13456</a>.</sub>

**Comment by zero-24** [comment]
@franz-wohlkoenig

You need to update to the last staging or nightly ;)

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 60443b4427179aadc8d16c729389a5e9fd609d3a<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13456">issues.joomla.org/tracker/joomla-cms/13456</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@zero-24 is ther a common way to get staging or nightly (you mean Update Channel "Custom Url")?

**Comment by zero-24** [comment]
You can use this: https://developer.joomla.org/nightly-builds.html but only for testing!

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 60443b4427179aadc8d16c729389a5e9fd609d3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13456">issues.joomla.org/tracker/joomla-cms/13456</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13456">issues.joomla.org/tracker/joomla-cms/13456</a>.</sub>

**Pull request merged**
