### PR TITLE
[4.0] remove chzn class

### PR DESCRIPTION
**Pull request by brianteeman**
This PR is to replace the use of the chzn class in the admin with custom-select-color and custom-select-color-state

NOTE these classes are not doing anything yet but thats for another PR

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c89a8668d35dfef05770328a4e4cb8d72444d61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24985">issues.joomla.org/tracker/joomla-cms/24985</a>.</sub>

**Comment by brianteeman** [comment]
Updated branch to trigger drone again

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 9526514b21b1affe9d9e01244970535c19011361<br /><br />@Quy can we get a retest?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24985">issues.joomla.org/tracker/joomla-cms/24985</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9526514b21b1affe9d9e01244970535c19011361<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24985">issues.joomla.org/tracker/joomla-cms/24985</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24985">issues.joomla.org/tracker/joomla-cms/24985</a>.</sub>

**Comment by wilsonge** [comment]
Please make sure the other PR now comes in ;) Thanks!

**Pull request merged**
