### PR TITLE
[4.0][a11y]Improved accessibility of Edit Your Profile form

### PR DESCRIPTION
**Pull request by hardik-codes**
### Summary of Changes
changes in ```components/com_users/tmpl/profile/edit.php```

### Testing Instructions
open edit your profile form in the front end 

### Expected result
```Cancel``` should be a button

### Actual result
```Cancel``` is not a button, instead it is a link

### Documentation Changes Required
None

### CODE REVIEW

**Comment by hardik-codes** [comment]
@zwiastunsw @chmst  please review.

**Comment by SharkyKZ** [comment]
It's the same as #24007 was initially and it won't work. See comments there.

**Comment by SharkyKZ** [comment]
See #24088 for potential alternative please.

**Comment by brianteeman** [comment]
href is not a valid element for a button

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 46c6eb2292397ed29e6c56919209b06272e2ab45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24087">issues.joomla.org/tracker/joomla-cms/24087</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :red_circle: unsuccessfully on 46c6eb2292397ed29e6c56919209b06272e2ab45<br /><br />See a good solution: https://github.com/joomla/joomla-cms/pull/24088#issuecomment-469430822<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24087">issues.joomla.org/tracker/joomla-cms/24087</a>.</sub>

**Comment by Quy** [comment]
Closing in favor for PR #24088<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24087">issues.joomla.org/tracker/joomla-cms/24087</a>.</sub>

**Pull request closed without merging**
