### PR TITLE
Administrator module cache is not cleared after editing a module

### PR DESCRIPTION
**Pull request by sourcecoast**
*Issue:*
When caching is enabled, changes to administrator modules require manually clearing cache before the change is applied.

*Underlying Cause:*
The /administrator/components/com_modules/models/module.php file uses an overridden cleanCache function which tries to guess whether the front-end or admin com_modules cache should be cleaned. That function calls $this->getClient() which uses a private variable ($_clientId) which is never set. Therefore, the local cleanCache always clears the front-end module cache even if an administrator module is being edited.

*Fix:*
Remove the erroneous and otherwise unused getClient function
Update the cleanCache function to always clear the front-end and administrator com_modules cache. 

*Possible improvements:*
Since the front-end modules are primarily what users edit, this adds a little overhead to clear admin modules everytime. However, it should have no impact on the site overall. The code could be implemented to properly determine the module type being edited and only clear that cache, but I wanted this change to be as surgical as possible.

*Testing:*
Enable caching in the Global Configuration - I was using File / Conservative, but I believe any caching will exhibit this problem
Edit an admin module - Title, published state or any setting
The changes should be immediately visible

### CODE REVIEW

**Comment by Kostelano** [comment]
Issue https://github.com/joomla/joomla-cms/issues/30492

**Comment by alikon** [comment]
1st of all thank you for your 1st pr
i would like to clean the cache selectively i.e if i'm  updating an admin module then only the admin module cache should be cleaned and viceversa

**Comment by sourcecoast** [comment]
> 1st of all thank you for your 1st pr
> i would like to clean the cache selectively i.e if i'm updating an admin module then only the admin module cache should be cleaned and viceversa

I agree that would be 'better'. The reasons I didn't is because it's more difficult to get that right and test. For editing/saving one module, it's not terribly troublesome since we can ask "Are you an admin or front-end module" and simply clear that.

When you add in batch copying/moving or group publishing, then we need to loop over each module and set a flag for if any were front-end or admin. Definitely do-able, but I don't have the time to implement that and test right now, so I put this in.

The current method is 100% broken though and goes back to how this file was updated in 2011.. so this is an improvement :)

As noted above:
* Currently, when editing any module (front or admin) the front-end modules are all flushed.
* With this PR, when editing any module, both front and admin are flushed
* Since front-end modules are much more commonly edited, this means we're only adding some overhead of flushing the admin modules (which are used less frequently and regenerating their cache is unlikely to be a server load).
* This shouldn't have any additional negative impact on the front-end, but could be improved by not flushing the front-end cache when admin modules are edited in the future.

Let me know. If this can't be integrated as-is, I can gladly investigate the improvements, but I don't know when they'd be implemented.

**Comment by adj9** [comment]
I tried PR with Joooml!'s default modules 3.9.21.
I don't find any problem in changing the features of the modules with active cache.
The cache is not full, I have enabled it for this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30565">issues.joomla.org/tracker/joomla-cms/30565</a>.</sub>

**Comment by sourcecoast** [comment]
> I tried PR with Joooml!'s default modules 3.9.21.
> I don't find any problem in changing the features of the modules with active cache.
> The cache is not full, I have enabled it for this PR.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/30565](https://issues.joomla.org/tracker/joomla-cms/30565).

Thanks for testing! I'm glad to hear this PR worked for you.

**Comment by gostn** [comment]
I have tested this item :white_check_mark: successfully on f39b1c0518215f87bf8aeac8c0881f78e88cd740<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30565">issues.joomla.org/tracker/joomla-cms/30565</a>.</sub>

**Comment by gostn** [comment]
@adj9 can you test again?

**Comment by gostn** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30565">issues.joomla.org/tracker/joomla-cms/30565</a>.</sub>

**Comment by HLeithner** [comment]
@gostn stop spamming our tracker with useless actions, if you continue you will be blocked.

**Comment by gostn** [comment]
All i have done is deleting my tests and comments.

**Comment by HLeithner** [comment]
Every time you do this (which makes no sense to me anyway) hundreds of people get notifications and that's annoying. So please stop it and if you don't want to contribute any longer I sorry for this but can't change it.
So please don't flood us with unneeded notifications.

**Comment by zero-24** [comment]
@sourcecoast I'm sorry that it took that long to come back to this but I will take this here into 3.10.11 (after drone passes) so after a few days more than usually (:D) that issue is finally fixed. Thanks

**Comment by zero-24** [comment]
I have put more thourth into this and decided to not merge this change into the very last 3.10 release and will limit it to the absolute required changes nessesarry.

**Pull request closed without merging**
