### PR TITLE
[4.4] Fix articles categories module bug

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #42924.

### Summary of Changes
Currently, children categories are being displayed multiple times on articles categories module, see https://github.com/joomla/joomla-cms/issues/42924 to understand more about the issue. This PR just fixes that wrong behavior.

### Testing Instructions
Follow instructions at https://github.com/joomla/joomla-cms/issues/42924 to create the module and confirm the issue

### Actual result BEFORE applying this Pull Request
Children categories are being displayed multiple times, both at top level and children level

### Expected result AFTER applying this Pull Request
Each category will only be displayed one time as expected.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by woluweb** [comment]
I have tested this item :white_check_mark: successfully on 9cbbe5932bba67d6e61d09dae47e76cc88c7cbe3<br /><br />I have tested this successfully
- on J4
- on J5

Txs Tuan!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42925">issues.joomla.org/tracker/joomla-cms/42925</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9cbbe5932bba67d6e61d09dae47e76cc88c7cbe3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42925">issues.joomla.org/tracker/joomla-cms/42925</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42925">issues.joomla.org/tracker/joomla-cms/42925</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
