### PR TITLE
Change Files according #8579

### PR DESCRIPTION
**Pull request by coolcat-creations**
This PR replaces #8579 due to merge conflicts.

### CODE REVIEW

**Comment by Sieger66** [comment]
I have tested this item :red_circle: unsuccessfully on df670004e646dbc42b13f3863c5d6213a3b9ec5f<br /><br />Make a article-category-list-menuitem.
Make an override in the Template Protostar for example: /html/com_content/article/my-66-override.php
Select this override in this article-category-list-menuitem -> List Layouts -> Alternative Layouts for Article 
and save it.
I see in the frontend no override of a the article-view if i click on a article of the article-category-list of this menuitem.

Also the same, if you additional save in the article-category-list-menuitem -> Details -> Template Style -> protostar - default<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16755">issues.joomla.org/tracker/joomla-cms/16755</a>.</sub>

**Comment by shamsbd71** [comment]
I have tested this item :white_check_mark: successfully on df670004e646dbc42b13f3863c5d6213a3b9ec5f<br /><br />@coolcat-creations can you apply the same xml code on `archive` `category` `featured` and `categories`. As all of theme are listing page and has a article details links on it.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16755">issues.joomla.org/tracker/joomla-cms/16755</a>.</sub>

**Comment by Sieger66** [comment]
The override works only if you use a default name for the override.

For example two overides in Protostar with the same content in the override-file:

This override works: 
/html/com_content/article/default.php
But it works not always as expected !

This override dont work:
/html/com_content/article/my-66-override.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16755">issues.joomla.org/tracker/joomla-cms/16755</a>.</sub>

**Comment by brianteeman** [comment]
> But it works not always as expected !

Please explain further

**Comment by coolcat-creations** [comment]
@Sieger66 please make a difference between overriding the default.php (Override) and providing a alternate Layout (giving the thing another name and select it in backend). Also please be sure that you use a clean site structure for testing and don´t use different overrides for the same duplicated blog category / article / whatever.

**Comment by Sieger66** [comment]
Not always as expected is similar as in my post in #8579  ;  15.8.2016

article-category-list-menuitem  -> Details -> Template Style 
change to an other Template(for example Beez) and save it.

Then works the override with the Protostar-Template furthermore.
But you dont see this in the menu-item at:
article-category-list-menuitem -> List Layouts -> Alternative Layout for Article

**Comment by Sieger66** [comment]
>  for the same duplicated blog category / article / whatever.

Yes i have found a article-category-list-menuitem in a other menu with the same category.
After change this i can see my alternate Layout-override as expected. 

But if i change to an other Template(for example Beez) 
article-category-list-menuitem -> Details -> Template Style
change to an other Template(for example Beez) and save it.

Then works the override furthermore.
But you dont see this in the menu-item at:
article-category-list-menuitem -> List Layouts -> Alternative Layout for Article

If you now go to the article-category-list-menuitem to List Layouts -> Alternative Layout for Article and change this to "From Component -> default" and save it then is come the expected result(view without the override from the other Template).

**Comment by shamsbd71** [comment]
@Sieger66 
I have tested as you asked and yes there is an issue but its not related to this xml params. its relate to 
 filed type `componentlayout`. we can create a new pull request to correct that. but for now its fine as it works with params as expected. 

### It Works

**Comment by Sieger66** [comment]
alternative article layout override from category is a new feature and i dont now if we should RTC with this known issue ?

If yes then needs additional "documentation" or "warning" or not ?
I dont know that.

**Comment by mbabker** [comment]
> alternative article layout override from category is a new feature and i dont now if we should RTC with this known bug ?

It uses the same underlying form field as the other component based layout overrides do (and inherently the same underlying PHP API to handle that value).  That layout parameter should save with a value like "template_name:layout_name" when saved to the database, and when used in the PHP API, that template name segment gets parsed by the view class to figure out that it needs to change the active template.

If that logic is broken, it will be a bug that already exists and would need to be addressed separately from adding this field.

**Comment by Webdongle** [comment]
I have tested this item :red_circle: unsuccessfully on df670004e646dbc42b13f3863c5d6213a3b9ec5f<br /><br />The same problem exists for Category Layout overrides but this patch does Not fix that.  imho both problems should be fixed with one patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16755">issues.joomla.org/tracker/joomla-cms/16755</a>.</sub>

**Comment by mbabker** [comment]
Are you talking about the feature this patch introduces in general or something with an already existing convention?  If the latter, that is correctly a separate bug report and should be resolved with a separate patch independent of this.

**Comment by Webdongle** [comment]
@mbabker 
I am now confused.  Please look at #16926 ... is it part of the same issue or a separate issue ?

**Comment by mbabker** [comment]
To be honest, that's not a part of the system I'm intimately familiar with.  I see what this PR is adding on its own, but the rest of it is kind of over my head at the moment, especially when you start factoring in menu item configurations and parameter merging in the different scenarios.

**Comment by Webdongle** [comment]
@mbabker 
Unless otherwise informed perhaps we should treat it as part of this issue ?  This appears to be one of those issues that has more than one affect.  Perhaps there is a common (underlying) root cause that needs to be addressed ?

**Comment by mbabker** [comment]
Adding this field isn't going to fix the underlying issue.  It might expose it in other ways, but to me it's separate just on what I'm reading.

**Comment by Webdongle** [comment]
Perhaps we should reopen the other tracker then ?

**Comment by mbabker** [comment]
As long as it's clear what exactly each item is, then sure.

**Comment by coolcat-creations** [comment]
@Sieger66  @Webdongle @mbabker 
Seems that the issue from Sieger66 is an expected behaviour and has nothing to do with this PR. 
(After assigning a new template style to your menüitem, you have to apply the change to be able to select an override from that template) Please open a new issue if you want the Usability to be improved.

Can we set it RTC as we have two successful test?

**Comment by Sieger66** [comment]
> the issue from Sieger66 is an expected behaviour 

I think **this is not correct.**

@coolcat-creations : please read my answer at 
https://forum.joomla.de/index.php/Conversation/576-github/

**Comment by ghost** [comment]
@coolcat-creations how to go on with that PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16755">issues.joomla.org/tracker/joomla-cms/16755</a>.</sub>

**Comment by coolcat-creations** [comment]
IMO the Bug that was Reported has nothing to do with this PR and could possibly be already fixed in this PR: https://github.com/joomla/joomla-cms/pull/18061 
Since we have successfull and unsuccessful tests, maybe someone can test again ?

**Comment by ghost** [comment]
@Sieger66 or @Webdongle can you please retest?

**Comment by saraheagle** [comment]
@coolcat-creations, I will test this :)
I am learning how to do testing, reading these instructions https://docs.joomla.org/Testing_Joomla!_patches.
Please let me know if I should read any other documentation.

**Comment by ghost** [comment]
@saraheagle https://brian.teeman.net/joomla/a-dummies-guide-to-joomla-bug-testing

**Comment by Sieger66** [comment]
I have retest this PR but the problem is the similar same problem as with #14802 that i have write in issue
#17912

**Comment by AndySDH** [comment]
Isn't this already implemented?

cattura

This sets the layout for Articles from a Category Blog menu item.

**Comment by Sieger66** [comment]
Your picture is from the Article-Category-Blog-menuitem 
PR 16755 make this in the Article Category List-menueitem

But, yes it is implemented with PR 14802 in the Options-Tab of the Article Category List-menuitem

https://github.com/joomla/joomla-cms/blob/3.8.2/components/com_content/views/category/tmpl/default.xml#L394-L401

PR 16755 do it in the List-Layouts-Tab of the Article Category List-menuitem and add a better description.

@coolcat-creations 
If you want PR 16755
Delete in PR 16755 your changes from PR 14802 in the /components/com_content/views/category/tmpl/default.xml
or change only the descriptions in the files and delete your changes in PR 16755
in the /components/com_content/views/category/tmpl/default.xml

**Comment by AndySDH** [comment]
I think the position is correct because it relates to Article Options, and all article options are in the Options tab. No need to change position imho.

**Comment by coolcat-creations** [comment]
@Sieger66 Sorry I don't understand, what is the exact issue?

> PR 16755 do it in the List-Layouts-Tab of the Article Category List-menuitem and add a better description.
> 
> @coolcat-creations
> If you want PR 16755
> Delete in PR 16755 your changes from PR 14802 in the /components/com_content/views/category/tmpl/default.xml
> or change only the descriptions in the files and delete your changes in PR 16755
> in the /components/com_content/views/category/tmpl/default.xml

**Comment by Sieger66** [comment]
@coolcat-creations 

with your PR 14802 comes in the Options-Tab of the **Article-Category-List-menuitem** already the  
Choose a Layout. 

Is no need to add with PR 16755 the same function in the 
List-Layouts-Tab of the **Article Category List-menuitem**

**Comment by coolcat-creations** [comment]
Ah did not see this, this PR is actually from someone else I just moved the code, so let's close this then - right?

**Comment by ghost** [comment]
@coolcat-creations give me a go for closing.

**Comment by coolcat-creations** [comment]
done ;)

**Pull request closed without merging**
