### PR TITLE
[4.0] Codeowner: Adding @hackwar for tests and cleanup

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says. The rows that I removed were for folders that don't exist anymore.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 312666802b73938a2f9de1e45363be05dc84ca2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25674">issues.joomla.org/tracker/joomla-cms/25674</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 312666802b73938a2f9de1e45363be05dc84ca2a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25674">issues.joomla.org/tracker/joomla-cms/25674</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
