### PR TITLE
Replace string interpolation deprectaed in PHP 8.2

### PR DESCRIPTION
**Pull request by ManuelHu**
Pull Request for Issue #38259.

### Summary of Changes

Applied the migration script from the PHP RFC to the repository. This replaces th deprecated `${...}` interpolation syntax with a longer-supported one (`{$...}).

### Testing Instructions

code review, no functional changes

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by Hackwar — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6cb637847025c6dee73cf88d3913965581bbccd2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38983">issues.joomla.org/tracker/joomla-cms/38983</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6cb637847025c6dee73cf88d3913965581bbccd2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38983">issues.joomla.org/tracker/joomla-cms/38983</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38983">issues.joomla.org/tracker/joomla-cms/38983</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
