### PR TITLE
Revert "Show configured upload limit when uploading installer package. (Dependency #11026)"

### PR DESCRIPTION
**Pull request by rdeutz**
Reverts joomla/joomla-cms#11255

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@brianteeman @zero-24 i think this as gone to 3.6.3, but not sure. anyway it's missing the milestone label

**Comment by brianteeman** [comment]
Not sure it needs a milestone

**Comment by rdeutz** [comment]
Because it is a revert I have set the same milestone as the PR I have reverted, the other option is the remove the milestones on both.

**Comment by zero-24** [comment]
We don't need any milestone as the milestone is at the final merged PR. I'm going to remove both milestones now.

**Pull request merged**
