### PR TITLE
[4.0] Document and Extension library prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds prepared statements in `Joomla\CMS\Document` and `Joomla\CMS\Extension` namespaces.

### Testing Instructions

Simple queries, code review is fine.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 098121d723246ce8db8ff1bcf63b6585af376b47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26059">issues.joomla.org/tracker/joomla-cms/26059</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 098121d723246ce8db8ff1bcf63b6585af376b47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26059">issues.joomla.org/tracker/joomla-cms/26059</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26059">issues.joomla.org/tracker/joomla-cms/26059</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26059">issues.joomla.org/tracker/joomla-cms/26059</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
