### PR TITLE
Use &quote;  instead of \"

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31564 .

### Summary of Changes
Changed \"%s\" to &quote;%s&quote for an url. 

### Testing Instructions
see #31564

Unfortunately I cannot test with php 8.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9a3811bd49492613997e2e71cf26f3e89bad5d2e<br /><br />Tested successfully in Beta6-dev of 3 December using PHP 7.4.13.

Installing sample data in PHP 8.0.0 fails with the message "There is an error in sample data plugin.  Response in invalid".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31566">issues.joomla.org/tracker/joomla-cms/31566</a>.</sub>

**Comment by toivo** [comment]
It would be too early to test in PHP 8 because apparently not all the PHP 8 fixes from 3.9.23 have been implemented in Joomla 4.  This info is from yesterday.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31566">issues.joomla.org/tracker/joomla-cms/31566</a>.</sub>

**Comment by kk9** [comment]
I have tested this item :white_check_mark: successfully on 9a3811bd49492613997e2e71cf26f3e89bad5d2e<br /><br />Tested on 7.3.21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31566">issues.joomla.org/tracker/joomla-cms/31566</a>.</sub>

**Comment by paritshivani** [comment]
I have tested this item :white_check_mark: successfully on 9a3811bd49492613997e2e71cf26f3e89bad5d2e<br /><br />Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31566">issues.joomla.org/tracker/joomla-cms/31566</a>.</sub>

**Comment by frostmakk** [comment]
I have tested this item :red_circle: unsuccessfully on 9a3811bd49492613997e2e71cf26f3e89bad5d2e<br /><br />The issue this PR is supposed to fix is installing sample data when running PHP 8.0
It does not fix the issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31566">issues.joomla.org/tracker/joomla-cms/31566</a>.</sub>

**Comment by frostmakk** [comment]
From debug:
CRITICAL ::1	error	Uncaught Throwable of type ValueError thrown with message "Missing format specifier at end of string". Stack trace: #0 D:\virtualhosts\new40\libraries\vendor\wamania\php-stemmer\src\StemmerFactory.php(52)

If line 52 in StemmerFactory.php is changed from:
`throw new NotFoundException(sprintf('Stemmer not found for %', $code)); `
to:
`throw new NotFoundException(sprintf('Stemmer not found for %d', $code));  `
the sample data installation works.

EDIT:  %s would probably be more correct.

**Comment by chmst** [comment]
Closing this, it dies not resolve the issue

**Pull request closed without merging**
