### PR TITLE
[4] Code cleanup

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 0c0a49a20544069fb2c2369198f8ee4e00caebe2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35124">issues.joomla.org/tracker/joomla-cms/35124</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0c0a49a20544069fb2c2369198f8ee4e00caebe2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35124">issues.joomla.org/tracker/joomla-cms/35124</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35124">issues.joomla.org/tracker/joomla-cms/35124</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
