### PR TITLE
[3.8] Restructure version constants

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

This PR splits up the information in our existing version constants so each value represents one segment of the version string and deprecates the constants which hold combined segments.  This also deprecates the `BUILD` constant as we aren't using it at all.

### Testing Instructions

The CMS should function normally and all places working with version data through the functions on our version class should have no change.

### Documentation Changes Required

Note the deprecated constants.

### TODO

- [x] Update the build script
- [x] Update the version bump script

### CODE REVIEW

**Comment by mbabker** [comment]
FWIW the build script does run with this PR applied without warnings, so it is fixing a bug 😉 (granted, only 3 or 4 people might ever run into it)

**Comment by N6REJ** [comment]
just fyi @mbabker issue still exists in 3.7.3  php 7.1.5 but NOT in 7.0.19
akeeba-error 
This might be relevant..
image

**Comment by mbabker** [comment]
This isn't going to fix an error where the stack trace points to code in Akeeba Backup.  Specifically, the only error it will actually fix is in our packaging script.

Plus, this is a PR targeted for 3.8, not a 3.7 release.

**Comment by mbabker** [comment]
While this mostly fixes an issue with PHP 7.1 and our build script, it also affects outside API use, it'd be nice if folks could please review and test this.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 556fabb2269f047c13591fd6240a28b3b5d6d33e<br /><br />looks good. Can you update / rebase that to staging? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16169">issues.joomla.org/tracker/joomla-cms/16169</a>.</sub>

**Pull request merged**
