### PR TITLE
[4.0] Fixes #20374 Cannot order on plugins page

### LINKED ISSUE #20374: [4.0] Cannot order on plugins page (JS Error)
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
Go to plugins manager
Sort by ordering column
see that the cursor looks like a croshairs indicating sorting is possible
Attempt to sort with a drag and drop action 

### Expected result

No error

### Actual result

JS error and no sorting happening

Watch:

screen recording 2018-05-12 at 10 21 pm

### System information (as much as possible)

Google Chrome.

### PR DESCRIPTION
**Pull request by dgrammatiko**
Fixes #20374

Pull Request for Issue # .

### Testing Instructions
Check #20374

### Documentation Changes Required
No, bug

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 1d08dbedafc753316ce4eaeceac0aaad3967fe64<br /><br />After the patch, plunis can be ordered in their plugin group. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23731">issues.joomla.org/tracker/joomla-cms/23731</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1d08dbedafc753316ce4eaeceac0aaad3967fe64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23731">issues.joomla.org/tracker/joomla-cms/23731</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23731">issues.joomla.org/tracker/joomla-cms/23731</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
