### PR TITLE
Mod submenu fix display of Components dashboard Dashboard icons

### PR DESCRIPTION
**Pull request by ceford**
Pull Request for Issue # .

Problem identified in #31382

### Summary of Changes

Correct display and title of Component Dashboard display of a Dashboard icon

### Testing Instructions

Obtain and install this dummy component: https://github.com/Harmageddon/com_demoj4
Go to Components Dashboard

### Actual result BEFORE applying this Pull Request

image
And the title is shown as %s Dashboard

### Expected result AFTER applying this Pull Request

image
And the Ttile is shown as J4 Demonstration Component Dashboard

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Harmageddon** [comment]
I have not tested this item.<br /><br />Good spot! Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31391">issues.joomla.org/tracker/joomla-cms/31391</a>.</sub>

**Comment by brianteeman** [comment]
~I have installed the component for testing as instructed~

~BEFORE applying the patch the title is correct and not as you describe - am I looking in the wrong place?~

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 51473dcbd082263463cc738c1ff22af9f61aa392<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31391">issues.joomla.org/tracker/joomla-cms/31391</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 51473dcbd082263463cc738c1ff22af9f61aa392<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31391">issues.joomla.org/tracker/joomla-cms/31391</a>.</sub>

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on 51473dcbd082263463cc738c1ff22af9f61aa392<br /><br />No idea what happened to my test, hope it works now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31391">issues.joomla.org/tracker/joomla-cms/31391</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31391">issues.joomla.org/tracker/joomla-cms/31391</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
