### PR TITLE
[com_content] - regression missing placeholder in modal

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #18106 .

### Summary of Changes
added the missed multiselect in modal
side effect from #17668

### Testing Instructions
see #18106

screenshot from 2017-09-27 18-06-41

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4221246e7de55e4ff21aa4c2ee71d285e68284aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18140">issues.joomla.org/tracker/joomla-cms/18140</a>.</sub>

**Comment by ghost** [comment]
@alexpanfilov can you please test?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4221246e7de55e4ff21aa4c2ee71d285e68284aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18140">issues.joomla.org/tracker/joomla-cms/18140</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
