### PR TITLE
[4] add missing import for typehint in docblock

### PR DESCRIPTION
**Pull request by PhilETaylor**
add missing import for typehint in docblock

Code review.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on bbe54a47e6799207843ef979658260cd12e8360d<br /><br />Tested successfully in Beta7-dev of 16 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32050">issues.joomla.org/tracker/joomla-cms/32050</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bbe54a47e6799207843ef979658260cd12e8360d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32050">issues.joomla.org/tracker/joomla-cms/32050</a>.</sub>

**Review by bembelimen — APPROVED** [review]

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32050">issues.joomla.org/tracker/joomla-cms/32050</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
