### PR TITLE
[4.0] [plg_finder_categories] Use injected database object

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use injected database object.

### Testing Instructions

Plugin works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 49fcec8a9a58ce1ff5f57c8a5d5cbf5ee8d46031<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25625">issues.joomla.org/tracker/joomla-cms/25625</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 49fcec8a9a58ce1ff5f57c8a5d5cbf5ee8d46031<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25625">issues.joomla.org/tracker/joomla-cms/25625</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25625">issues.joomla.org/tracker/joomla-cms/25625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
