### PR TITLE
[4.0] Update jQuery Minicolours to v2.2.6

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Title says it all. 

**Changelog:**
- Fixed dev dependencies and updated minified version.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am confused why only the minified version is updated.
#15461 updated everything

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/15461 is for v2.2.5 and this PR is for 2.2.6.

I'm just providing the changelog that was on their release page. They probably just made a mistake when compiling the minified version last time.

**Comment by wilsonge** [comment]
Comparing the git tags only the minifed file has changed :/ https://github.com/claviska/jquery-minicolors/compare/2.2.5...2.2.6

**Comment by brianteeman** [comment]
ok - thanks for confirming this odd behaviour

**Pull request merged**
