### PR TITLE
[4.0] Fix menu export

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #34700 .

### Summary of Changes

Fix menu export feature

### Testing Instructions
Apply patch and please follow #34700

### Actual result BEFORE applying this Pull Request
Export not works

### Expected result AFTER applying this Pull Request
Export  works

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 862dcf578cc062be0cee96e2de1133340455130c<br /><br />Thanks, the button is working.

Note that a warning is available in the export file. This is probably not related to this solution, but please check your export files - those who will be testing the PR.

```
<br />
<b>Warning</b>:  SimpleXMLElement::addChild(): unterminated entity reference task=getMenuBadgeData&amp;format=json&quot;,&quot;menu-anchor_title&quot;:&quot;&quot;,&quot;menu_icon&quot;:&quot;&quot;,&quot;menu_image&quot;:&quot;&quot;,&quot;menu_image_css&quot;:&quot;&quot;,&quot;menu_text&quot;:1,&quot;menu_show&quot;:1} in <b>C:\OSPanel\domains\joomla4\administrator\components\com_menus\src\View\Menu\XmlView.php</b> on line <b>172</b><br />
<?xml version="1.0"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:joomla.org" xsi:schemaLocation="urn:joomla.org menu.xsd">
  <menuitem type="component" title="&#x421;&#x43E;&#x43E;&#x431;&#x449;&#x435;&#x43D;&#x438;&#x44F; &#x43F;&#x43E;&#x441;&#x43B;&#x435; &#x443;&#x441;&#x442;&#x430;&#x43D;&#x43E;&#x432;&#x43A;&#x438;" link="index.php?option=com_postinstall&amp;view=messages" element="com_postinstall" class=" " access="1">
    <params/>
  </menuitem>
  <menuitem type="heading" title="&#x437;&#x430;&#x433;&#x43E;&#x43B;" link="#" class=" " access="1">
    <params>{"menu-anchor_title":"","menu_icon":"","menu_image":"","menu_image_css":"","menu_text":1,"menu_show":1,"dashboard":"131"}</params>
  </menuitem>
</menu>
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34746">issues.joomla.org/tracker/joomla-cms/34746</a>.</sub>

**Comment by Fedik** [comment]
@Kostelano please test again, should be good now, with UTF-8 and stuff

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 8d66f545bb196021d117ed518cd43757a5259cef<br /><br />Everything is fine now, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34746">issues.joomla.org/tracker/joomla-cms/34746</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 8d66f545bb196021d117ed518cd43757a5259cef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34746">issues.joomla.org/tracker/joomla-cms/34746</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34746">issues.joomla.org/tracker/joomla-cms/34746</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
