### PR TITLE
[4.0] Correct field type casing

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes https://github.com/joomla/joomla-cms/issues/29996.

### Summary of Changes

Corrects field type casing.

### Testing Instructions

Needs OS with case sensitive filesystem (e.g. Linux).
Edit an article in frontend.
Click `CMS Content` button, select `Module`.
In the modal click `Filter Options`.
Inspect `Position` field.

### Actual result BEFORE applying this Pull Request

Field appears as text box.

### Expected result AFTER applying this Pull Request

Field appears as a dropdown with module positions.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Pr 29999 ;-) almost there... who will get the #30000???? haha

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3a82bdd3fa7bce6a521d77d5bf36b9005ff81484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29999">issues.joomla.org/tracker/joomla-cms/29999</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a82bdd3fa7bce6a521d77d5bf36b9005ff81484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29999">issues.joomla.org/tracker/joomla-cms/29999</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29999">issues.joomla.org/tracker/joomla-cms/29999</a>.</sub>

**Pull request merged**
