### PR TITLE
[3.10] Backport php8.1 compatibility fixes

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/36041

### Summary of Changes

Take the changes from https://github.com/joomla/joomla-cms/pull/36041 and apply it to J3.10 to fix that php8.1 issues
Thanks and all the credits go to @nikosdion 

### Testing Instructions

- Install [this package](https://ci.joomla.org/artifacts/joomla/joomla-cms/3.10-dev/36083/downloads/48562/Joomla_3.10.4-dev+pr.36083-Development-Full_Package.zip) on PHP your current php version
- Install [this package](https://ci.joomla.org/artifacts/joomla/joomla-cms/3.10-dev/36083/downloads/48562/Joomla_3.10.4-dev+pr.36083-Development-Full_Package.zip) on PHP 8.1
- check the test instructions here: https://github.com/joomla/joomla-cms/pull/36041 as its a backport to 3.10

### Actual result BEFORE applying this Pull Request

issues with php 8.1

### Expected result AFTER applying this Pull Request

The known issues with php 8.1 are gone

### Documentation Changes Required

none

cc @richard67 would be great when you could take a look on your php 8.1 setup

### CODE REVIEW

**Comment by richard67** [comment]
All unit tests were failing in Appveyor and Drone, except of the one for PHP 8, so there could be something wrong. I've restarted Appveyor and Drone to see if it was an unrelated issue.

**Comment by zero-24** [comment]
> All unit tests were failing in Appveyor and Drone, except of the one for PHP 8, so there could be something wrong. I've restarted Appveyor and Drone to see if it was an unrelated issue.

when you check the datails for the php8 test it also fails but seems to be still an allowed failer and there for is marked as "passed".

**Comment by richard67** [comment]
I see … then there is really something wrong.

**Comment by zero-24** [comment]
To me it looks like an issue with the tests given that i can not reproduce any issues with the changed code.

**Comment by HLeithner** [comment]
The issue is that the cache now works for all instances of the class if it has the same cache key (dbtype, dbname, tablename).
Since the table is already loaded in an earlier test, the cache is already filled. The question is what's in the cache and is it wrong for the next test call.

@wilsonge can you have a look?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f330e25445efe01e7fd1d95aa5967b2211823a6<br /><br />Tested in the same way as for #36041 plus checked that without the PR, creating a new article fails on PHP 8.1-dev with an exception without this PR applied, while it succeeds with this PR applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36083">issues.joomla.org/tracker/joomla-cms/36083</a>.</sub>

**Comment by wilsonge** [comment]
I’ll take a quick look but if it’s not a fairly quick fix my priorities need to be on the two J4 upgrade issues (media dir + classloader) before RC’s this weekend I’m afraid

**Comment by zero-24** [comment]
@HLeithner @rdeutz @wilsonge Looks like the test has issues when I do this the tests passes: https://github.com/joomla/joomla-cms/pull/36083/commits/dee42a6141b5e9ce1c2da01182dfac214edb6648

Before that the `key` is: `mock__925f07b0:mock__925f07b0:#__extensions` ([src](https://ci.joomla.org/joomla/joomla-cms/48646/6/8)) which I dont understand where they are comming from. Any Ideas?

Could it be that somewhere the `$this->_db` has not been setup correctly in the tests?

**Comment by richard67** [comment]
@zero-24 Regarding the title of this PR, I assume you mean compat(ibility) and not combat (which is a military term you know from the German word „Kombattant“), right?

**Comment by zero-24** [comment]
Updated

**Comment by zero-24** [comment]
@HLeithner @nibra can you please have a look here and hit merge once you agree on the test changes that forces the TestCaseDatebase here to use sqlite so this test can pass?

**Review by nibra — APPROVED** [review]

**Comment by nikosdion** [comment]
@nibra Should we work on the installer issues for PHP 8.1? I may have some limited time over the weekend.

**Comment by zero-24** [comment]
@nikosdion what installer issues are you working on?

The test issues here where something different because the mocked database was not fully setup.

**Comment by nikosdion** [comment]
@zero-24 I haven't started working on it yet. I was told by @richard67 that he had trouble installing Joomla on PHP 8.1. I am gonna give it a go and see if I can fix anything to fix. Fair enough?

**Comment by zero-24** [comment]
Sure. I only want to make sure there is no double work going on as here we had issues with the installer unittests that where issues with the tests but you are talking about the installer of the CMS thats a different thing and should be checked when there are any issues.

**Comment by zero-24** [comment]
@nikosdion just for the record and to not waste your time. I have just installed 3.10 (with this patch here) as well as a current nighly build of J4 (that already include your patches) on PHP 8.1-dev (provided by devilbox) without any issues.

**Comment by zero-24** [comment]
Will merge here now based on the tests done by @richard67 as well as the now passing unittests and the tests done on J4 for the 1:1 changes taken down to J3 with this PR.

Thanks 👍

**Comment by nibra** [comment]
@nikosdion This seems to have been taken care of. I'd love to work with you on code another time!

**Comment by nikosdion** [comment]
@zero-24 @nibra Thank you, lads! Have a great weekend :)

**Comment by richard67** [comment]
> @nikosdion just for the record and to not waste your time. I have just installed 3.10 (with this patch here) as well as a current nighly build of J4 (that already include your patches) on PHP 8.1-dev (provided by devilbox) without any issues.

@zero-24 I had issues only when display errors was switched on in PHP settings or by switching on debug system in backend.

**Comment by richard67** [comment]
@zero-24 P.S.: See this comment and those after that about the issues I had: https://github.com/joomla/joomla-cms/pull/36041#issuecomment-974798813 and how they were circumvented by switching off error reporting.

**Comment by nikosdion** [comment]
@richard67 Gotcha. Yeah, most of these cannot be fixed right now. We need to add a bunch of PHP 8 annotations and even then we will have some deprecated notices we cannot get rid of. I had already said that in my comment on #36041, I am repeating here for the sake of completeness. No need to reply :)

**Comment by zero-24** [comment]
Hmm interesting i did not got any like that. But i have not checked the error reporting setting yet. Under xampp it IIRC was on i'm not sure how it is under devilbox. If anything they are non-blocking issues for now and can go with the next release as the normal install works without issues for now.

**Comment by richard67** [comment]
@zero-24 I haven't checked yet if I have the same issues with 3.10-dev. So or so they are not blocking. I just wanted to make sure you are aware of them.

**Pull request merged**
