### PR TITLE
Chnage the String class, in PHP 7 its reserved

### PR DESCRIPTION
**Pull request by AviMoto**
Fix reserved Class name and his referances in the Joomla Framework
see ticket #8729

### CODE REVIEW

**Comment by brianteeman** [comment]
Already fixed in 3.5 Beta 1 (Staging branch).


On 18 December 2015 at 12:59, Avi <notifications@github.com> wrote:

> Fix reserved Class name and his referances in the Joomla Framework
> see ticket #8729 <https://github.com/joomla/joomla-cms/issues/8729>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/8730
> Commit Summary
>
>    - Chnage the Sting class, in PHP 7 its reserved
>
> File Changes
>
>    - *M* libraries/vendor/joomla/filter/src/OutputFilter.php
>    <https://github.com/joomla/joomla-cms/pull/8730/files#diff-0> (6)
>    - *M* libraries/vendor/joomla/string/src/Inflector.php
>    <https://github.com/joomla/joomla-cms/pull/8730/files#diff-1> (6)
>    - *R* libraries/vendor/joomla/string/src/JoomlaString.php
>    <https://github.com/joomla/joomla-cms/pull/8730/files#diff-2> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/8730.patch
>    - https://github.com/joomla/joomla-cms/pull/8730.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8730>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by AviMoto** [comment]
Hi Brain,
I run a PHP 7 readiness test and  the Sting class is still exist and use by
two functions of the OutputFilter class, right now no one call this
function but it can use easily by mistake, why not just remove it or rename
it?

On Fri, Dec 18, 2015 at 3:01 PM, Brian Teeman <notifications@github.com>
wrote:

> Already fixed in 3.5 Beta 1 (Staging branch).
>
>
> On 18 December 2015 at 12:59, Avi <notifications@github.com> wrote:
>
> > Fix reserved Class name and his referances in the Joomla Framework
> > see ticket #8729 <https://github.com/joomla/joomla-cms/issues/8729>
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/joomla/joomla-cms/pull/8730
> > Commit Summary
> >
> > - Chnage the Sting class, in PHP 7 its reserved
> >
> > File Changes
> >
> > - *M* libraries/vendor/joomla/filter/src/OutputFilter.php
> > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-0> (6)
> > - *M* libraries/vendor/joomla/string/src/Inflector.php
> > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-1> (6)
> > - *R* libraries/vendor/joomla/string/src/JoomlaString.php
> > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-2> (2)
> >
> > Patch Links:
> >
> > - https://github.com/joomla/joomla-cms/pull/8730.patch
> > - https://github.com/joomla/joomla-cms/pull/8730.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/pull/8730>.
> >
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8730#issuecomment-165772221>.
>



--

**Comment by brianteeman** [comment]
Were you running that on 3.4.6 or 3.5 beta1?

On 18 December 2015 at 13:06, Avi <notifications@github.com> wrote:

> Hi Brain,
> I run a PHP 7 readiness test and the Sting class is still exist and use by
> two functions of the OutputFilter class, right now no one call this
> function but it can use easily by mistake, why not just remove it or rename
> it?
>
> On Fri, Dec 18, 2015 at 3:01 PM, Brian Teeman <notifications@github.com>
> wrote:
>
> > Already fixed in 3.5 Beta 1 (Staging branch).
> >
> >
> > On 18 December 2015 at 12:59, Avi <notifications@github.com> wrote:
> >
> > > Fix reserved Class name and his referances in the Joomla Framework
> > > see ticket #8729 <https://github.com/joomla/joomla-cms/issues/8729>
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/joomla/joomla-cms/pull/8730
> > > Commit Summary
> > >
> > > - Chnage the Sting class, in PHP 7 its reserved
> > >
> > > File Changes
> > >
> > > - *M* libraries/vendor/joomla/filter/src/OutputFilter.php
> > > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-0> (6)
> > > - *M* libraries/vendor/joomla/string/src/Inflector.php
> > > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-1> (6)
> > > - *R* libraries/vendor/joomla/string/src/JoomlaString.php
> > > <https://github.com/joomla/joomla-cms/pull/8730/files#diff-2> (2)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/joomla/joomla-cms/pull/8730.patch
> > > - https://github.com/joomla/joomla-cms/pull/8730.diff
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/joomla/joomla-cms/pull/8730>.
> > >
> >
> >
> >
> > --
> > Brian Teeman
> > Co-founder Joomla! and OpenSourceMatters Inc.
> > http://brian.teeman.net/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/pull/8730#issuecomment-165772221>.
> >
>
>
>
> --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8730#issuecomment-165772921>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
We don't take changes to upstream files here. FWIW this has been fixed in verison 1.1.6 of the framework - so all we should need to do is update composer dependencies and this will "fix itself"

**Comment by AviMoto** [comment]
On staging branch

בתאריך יום ו׳, 18 בדצמ׳ 2015, 3:19 PM מאת George Wilson <
notifications@github.com>:

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/8730 (you know this class is unused by the core CMS though?). We generally use the one in `libraries/joomla/filter/output.php`

**Comment by AviMoto** [comment]
Ok, I just suppose to change it and be on the safe side that no one will
use it by mistake, or maybe we need to update the framework group?

On Sat, Dec 19, 2015 at 3:40 AM, George Wilson <notifications@github.com>
wrote:

> #8730 <https://github.com/joomla/joomla-cms/pull/8730> (you know this
> class is unused by the core CMS though?). We generally use the one in
> libraries/joomla/filter/output.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8730#issuecomment-165933606>.
>



--

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/8734 PR here. The framework group already did the update. We just needed to do the composer update

**Comment by AviMoto** [comment]
Hi Gorge,
Thanks for the update.

On Sun, Dec 20, 2015 at 3:10 PM, George Wilson <notifications@github.com>
wrote:

> #8734 <https://github.com/joomla/joomla-cms/pull/8734> PR here. The
> framework group already did the update. We just needed to do the composer
> update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/8730#issuecomment-166115404>.
>



--

**Pull request closed without merging**
