### PR TITLE
Define correct type for field helper doc

### PR DESCRIPTION
**Pull request by laoneo**
The $item parameter `FieldsHelper::getFields` has to be an object or array and not null.

### CODE REVIEW

**Comment by sandewt** [comment]
>The $item parameter FieldsHelper::getFields has to be an object or array **and not null.**

I don't understand this, because in line 108 $item gets the value null? You probably mean something else.

https://github.com/joomla/joomla-cms/blob/37df313248cf33e461c45f0d021c456e76f679f4/administrator/components/com_fields/src/Helper/FieldsHelper.php#L108

In line 128 I can see that the variable $item can be an array.
https://github.com/joomla/joomla-cms/blob/37df313248cf33e461c45f0d021c456e76f679f4/administrator/components/com_fields/src/Helper/FieldsHelper.php#L128

How can I best test this PR?

**Comment by laoneo** [comment]
Use a debugger and check the types of $item while working with custom fields. But as you can see in the code, it can be an object, array or null. The doc comment is wrong as it can, but not must, be null.

If you want to test something as this one here is just cosmetic, better to look at https://github.com/joomla/joomla-cms/pull/42473.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 37df313248cf33e461c45f0d021c456e76f679f4<br /><br />cosmetically tested by just looking at the code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42635">issues.joomla.org/tracker/joomla-cms/42635</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 37df313248cf33e461c45f0d021c456e76f679f4<br /><br />Working on differnt applications with custom fields. No problem with this PR. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42635">issues.joomla.org/tracker/joomla-cms/42635</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42635">issues.joomla.org/tracker/joomla-cms/42635</a>.</sub>

**Pull request merged**
