### PR TITLE
[com_config] Fallback warning in send test mail (solves #9680)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9680.
#### Summary of Changes

Sometimes when sending a testmail the mail is sent even that you know the mail config is not correct.

This happens because JMail has some fallbacks (see, for instance, https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L601-L627).

So this PR adds a fallback warning in global configuration "Send Test Mail" button result s users can notice that the mail is sent, but not with the configurations that the user chossed.

Before PR
image

After PR
image
#### Testing Instructions
1. Apply patch and go to global config
2. Clear browser cache
3. Test "Send Test Mail" with all possible mail configs you can remember.

I get the fallback message by using SMTP with SMTP Authentication and didn't type the SMTP Auth user or password (leave the fields empty). I this will not allow to connect to my SMTP server.
image

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on a90a53188940d73c1b176f1fefc6f5531f43366a<br /><br />Works good. please remember on testing to clear your browser cache.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman since you also add the original issue, can you test this one?

**Comment by andrepereiradasilva** [comment]
@brianteeman can i ask you to please test this one?

**Comment by brianteeman** [comment]
I would test it if I could recreate the scenario now but i cant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok @brianteeman thanks anyway.
anyone else can test this?

**Comment by AnishaVora** [comment]
Hello,
I have tried with incorrect SMTP details (incorrect username and password) but I could not see the same message that you have shown in **before PR** section. Instead I am getting 'Test mail could not be sent.' and 'SMTP Error: Could not authenticate.' 

I have tested this on Joomla! 3.6.0-alpha2-dev staging.
screen shot 2016-06-03 at 08 25 28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by gunjanpatel** [comment]
Unfortunately I am also not able to reproduce this issue before applying patch. I have followed instructions in the main issue. Like giving wrong port and wrong host but still not getting green message. Is there any other possible way to reproduce it? 

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> Unfortunately I am also not able to reproduce this issue before applying patch. I have followed instructions in the main issue. Like giving wrong port and wrong host but still not getting green message. Is there any other possible way to reproduce it?

Set smtp authentication to yes, with user and password empty

**Comment by gunjanpatel** [comment]
Thanks @andrepereiradasilva Follow your comments, but still having the same and not able to reproduce it before applying patch. I am using latest staging branch with smtp authentication to yes, with user and password empty.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
what error do you have with the last test case? Maybe you don't have php mailer working so there is not fallback.

**Comment by gunjanpatel** [comment]
I am getting the same error which @AnishaVora is getting.

screen shot 2016-06-06 at 08 05 21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
so your SMTP fails and your fallback also fails.

To test this you have to php `mail` function working properly to have a fallback in case SMTP does not work.

Probably you don't have a correct sendmail path in your server.
Check if your php ini `sendmail_path` is correct: http://php.net/manual/en/mail.configuration.php#ini.sendmail-path

**Comment by AnishaVora** [comment]
Hello,
I have tested this successfully with empty SMTP username and password (re-tested after installing sendmail). After applying the patch the following message is displayed.
screen shot 2016-06-08 at 05 20 00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by AnishaVora** [comment]
I have tested this item :white_check_mark: successfully on a90a53188940d73c1b176f1fefc6f5531f43366a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by andrepereiradasilva** [comment]
nice thanks!

**Comment by andrepereiradasilva** [comment]
@brianteeman RTC?

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by gunjanpatel** [comment]
I can also confirm the test successful as I was there while Anisha was testing this issue on her machine. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10370">issues.joomla.org/joomla-cms/10370</a>.</sub>

**Comment by wilsonge** [comment]
Conflicts please :)

**Comment by andrepereiradasilva** [comment]
conflicts fixed

**Comment by andrepereiradasilva** [comment]
sorry for this late one, just one thing lost in the conflixcts fix
https://github.com/joomla/joomla-cms/pull/10370/commits/c41292d2b9ac852bdc7613a4b19aae5817580b87

**Comment by wilsonge** [comment]
It's ok :) Thanks for getting on it so fast!

**Pull request merged**
