### PR TITLE
Upgrade font awesome to version 6

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Upgrades font awesome to version 6.

### Testing Instructions
Browse around in Joomla.

### Actual result BEFORE applying this Pull Request
All icons are displayed.

### Expected result AFTER applying this Pull Request
All icons are displayed.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
> Browse around in Joomla.

I think that's not a sufficient test. It would also need to check if running "npm ci" (or "npm run build:js" and "npm run build:css") show any new errors or warnings.

**Comment by dgrammatiko** [comment]
@laoneo this won’t cut it, as you break everything from j4 that are referencing fa5. Get the code from here: https://github.com/joomla/joomla-cms/pull/36906/files

**Comment by laoneo** [comment]
Can you not open then a new pr with the upgrade? I don't want to copy your code and you understand it more deeply than me.

**Comment by laoneo** [comment]
@dgrammatiko can you have a look again as I did copy the fontawesome related changes from #36906?

**Comment by dgrammatiko** [comment]
LGTM

**Comment by HLeithner** [comment]
can you create a documentation entry on manual joomla for this because it's a b/c break for some images (iirc some images are missing in 6)

**Comment by dgrammatiko** [comment]
Just some heads up here, I was playing with FA6 for my template Muta and I think that in order to keep the b/c here the font-family needs to stay as `Font Awesome 5 Free` otherwise direct calls to the font family are broken: https://github.com/joomla/joomla-cms/pull/39400

**Pull request merged**
