### PR TITLE
Fixes 9054  (part 1, com_newsfeeds). [REGRESSION] sort order

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/joomla/joomla-cms/issues/9054 for instructions.
Fixes com_newsfeeds.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2352c0e5fd7e10092563eb48d2a607a99d1b2984<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9056">issues.joomla.org/joomla-cms/9056</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2352c0e5fd7e10092563eb48d2a607a99d1b2984<br /><br />Tested with success on current staging. Before patch: Sort order changed from Title Ascending to ID Descending after paging (or changing items per page). After patch: Sort order is Title Ascending and stays like this when paging. In opposite to test description in #9054 there was no need to clear any cookies for this test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9056">issues.joomla.org/joomla-cms/9056</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9056">issues.joomla.org/joomla-cms/9056</a>.</sub>

**Comment by richard67** [comment]
Let's hope it goes into Beta 3 ... maybe someone can set the milestone to 3.5.0 to force that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9056">issues.joomla.org/joomla-cms/9056</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @bertmert and testers!

**Pull request merged**
