### PR TITLE
[4.0] Webcomponent tab.js typo

### PR DESCRIPTION
**Pull request by brianteeman**
oriendation ==> orientation

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by dgrammatiko** [comment]
@brianteeman @wilsonge actually that file is not being used. The code in use is from the other repo

**Comment by wilsonge** [comment]
Then please do a PR to delete the file.... we can't have unused duplicates everywhere

**Comment by brianteeman** [comment]
Please do - and fix the typo in the other repo

**Comment by dgrammatiko** [comment]
@brianteeman if you're gonna fix this please do it in the panels script not the tabs. Tabs is the old script, not a11y 100%

**Comment by wilsonge** [comment]
Patched typo in custom elements repo https://github.com/joomla-projects/custom-elements/commit/fac7caae32e92e8d6159b22f751912442d76e732 (panels was already fixed/fine).

**Comment by wilsonge** [comment]
@dgrammatiko can you do the PR to remove tabs from this repo then please

**Comment by dgrammatiko** [comment]
@wilsonge there you go: https://github.com/joomla/joomla-cms/pull/21609

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
