### PR TITLE
fix "mut implemet" typo in comments

### PR DESCRIPTION
**Pull request by PhilETaylor**
fix "mut implemet" typo in comments

No other changes

### CODE REVIEW

**Comment by PhilETaylor** [comment]
@wilsonge A quick merge available here. 37mins is your record...

**Comment by zero-24** [comment]
On review thanks. Looks like you are now in PR mode 😄

**Comment by PhilETaylor** [comment]
42 mins to merge... pah - @wilsonge still has the record :)

**Comment by zero-24** [comment]
We need to wait atleast if travis passes as if it fails also merging to master fails. So this is the minimum of time for that even if we don't change production code.

**Pull request merged**
