### PR TITLE
[4.0] use _blank as target

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

While translating, I noticed two undefined target="_new". In this PR, rel='noopener noreferrer' was also inserted directly.

### Testing Instructions

The link will open in a new window/tab.

### Actual result BEFORE applying this Pull Request

There is no keyword as _new in HTML5, and not in HTML4 (and consequently XHTML) either. That means, that there will be no consistent behavior whatsoever if you use this as a value for the target attribute.

### Expected result AFTER applying this Pull Request

> Browsing contexts can have a browsing context name. Unless stated otherwise, it is the empty string.
> 
> A valid browsing context name is any string with at least one character that does not start with a U+005F LOW LINE character. (Names starting with an underscore are reserved for special keywords.)
> 
> A valid browsing context name or keyword is any string that is either a valid browsing context name or that is an ASCII case-insensitive match for one of: _blank, _self, _parent, or _top.

Source: https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-names

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good. Does it also have to be done in J3 ?

**Comment by tecpromotion** [comment]
> Looks good. Does it also have to be done in J3 ?

yes. new pr for 3 or merge in staging/3.10-dev?

**Comment by ceford** [comment]
I can't find the string keys anywhere in the Joomla 4 code!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34881">issues.joomla.org/tracker/joomla-cms/34881</a>.</sub>

**Comment by brianteeman** [comment]
Look again

**Comment by brianteeman** [comment]
seriously though. iirc they are needed for upgrades

**Comment by ceford** [comment]
> Look again

I looked again. The string keys occur in ini files but I do not see them anywhere in the code. If I have somehow missed them could you explain where? Or if not in the code exactly how they get used.

**Comment by brianteeman** [comment]
> seriously though. iirc they are needed for upgrades

https://github.com/joomla/joomla-cms/pull/31838

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on c0d99b79a6d7434ebfc8af24c820c8900cf350f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34881">issues.joomla.org/tracker/joomla-cms/34881</a>.</sub>

**Comment by richard67** [comment]
> > seriously though. iirc they are needed for upgrades
> 
> #31838

Correct. So for testing it needs to update a 3.10 to 4 and then check the postinstall messages without and with this PR applied.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c0d99b79a6d7434ebfc8af24c820c8900cf350f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34881">issues.joomla.org/tracker/joomla-cms/34881</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34881">issues.joomla.org/tracker/joomla-cms/34881</a>.</sub>

**Comment by richard67** [comment]
Setting RTC because 2 good tests ... maintainers will respect the milestone "4.0.1" due to the language freeze.

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
