### PR TITLE
Debuguser and debuggroup legend

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

The legend just looked wrong and it was because there was a space between the icon and the text which made it look like the wrong icon was associated with the text
#### Testing Instructions

If you enable debug in global configuration and then visit the users and groups pages there is a debug option. When selected you will see a legend at the top
#### Before

xwa9
#### After

v3ox

### CODE REVIEW

**Comment by brianteeman** [comment]
[note hathor uses colours not icons so doesnt need an update]<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10045">issues.joomla.org/joomla-cms/10045</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 239d017f2d07b8e0c8ee276c918c13a7ca9e09c8<br /><br />Tested ok and made the same changes in my debuguser PR
https://github.com/joomla/joomla-cms/pull/10007<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10045">issues.joomla.org/joomla-cms/10045</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 239d017f2d07b8e0c8ee276c918c13a7ca9e09c8<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10045">issues.joomla.org/joomla-cms/10045</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10045">issues.joomla.org/joomla-cms/10045</a>.</sub>

**Pull request merged**
