### PR TITLE
[4.2] actionlog plugin prepared statements

### PR DESCRIPTION
**Pull request by alikon**
follow up https://github.com/joomla/joomla-cms/pull/37788#pullrequestreview-987097423
### Summary of Changes
used prepared statements

### Testing Instructions
login with incorret credentials
check the user action log

### Actual result BEFORE applying this Pull Request
works as expected

### Expected result AFTER applying this Pull Request
works as expected

### CODE REVIEW

**Comment by toivo** [comment]
I have not tested this item.<br /><br />Unable to test because the Patch Tester does not find one of the files, plugins/actionlog/Joomla/src/Extension/Joomla.php.  Had updated the 4.2.0 test site using the latest available Nightly Build update of 4.2.0-beta1-dev from 30 May.  The other two Nightly Builds were updated this morning, 31 May, but 4.2.0 was from yesterday.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37935">issues.joomla.org/tracker/joomla-cms/37935</a>.</sub>

**Comment by alikon** [comment]
i think you'll find the merged #37788 at the next nightly build

**Comment by toivo** [comment]
Thank you, will test this PR tomorrow then
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37935">issues.joomla.org/tracker/joomla-cms/37935</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on fa76795a19db9120f6f85512804673551cbd1274<br /><br />Joomla! 4.2.0-beta1-dev Development<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37935">issues.joomla.org/tracker/joomla-cms/37935</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fa76795a19db9120f6f85512804673551cbd1274<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37935">issues.joomla.org/tracker/joomla-cms/37935</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37935">issues.joomla.org/tracker/joomla-cms/37935</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
