### PR TITLE
[4.2] Clean the logo URL in Atum

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request is the same bug fix as #39574

### Summary of Changes
Use the recommended way to render an image: through the HTMLHelper

### Testing Instructions
Check that selecting a custom logo image works and that the source doesn't have the hash part of the URL. Also check that svg renders as expected

### Actual result BEFORE applying this Pull Request

The URL contains the hash (it is dirty) and SVG images get 0 width and height thus are not visible

### Expected result AFTER applying this Pull Request

The URL **does not** contain the hash (it is clean) and SVG images are visible

### Link to documentations
This is a bug fix without changing any of the existing functionality
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 53821a0a25fbf9f29b7715e3d6f374a4fe2fbad7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39579">issues.joomla.org/tracker/joomla-cms/39579</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 53821a0a25fbf9f29b7715e3d6f374a4fe2fbad7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39579">issues.joomla.org/tracker/joomla-cms/39579</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39579">issues.joomla.org/tracker/joomla-cms/39579</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
