### PR TITLE
[4] remove unused import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
if only we actually used php-cs then we wouldnt need all these PR and everyone could concentrate on something more useful. https://github.com/joomla/joomla-cms/pull/33908

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on e98a28a27c6a540c10a245d9f48e859742d51ced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35410">issues.joomla.org/tracker/joomla-cms/35410</a>.</sub>

**Comment by joomdonation** [comment]
> if only we actually used php-cs then we wouldnt need all these PR and everyone could concentrate on something more useful. #33908

@brianteeman Agreed !

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e98a28a27c6a540c10a245d9f48e859742d51ced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35410">issues.joomla.org/tracker/joomla-cms/35410</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35410">issues.joomla.org/tracker/joomla-cms/35410</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
