### PR TITLE
[com_newsfeeds] add searchtools to modal layout and solves bugs

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds searchtools to com_newsfeeds modal layout newsfeeds view.
The modal hasn't working properly (wasn't forcing the language in language association modal).

Also, in normal layout:
- correct bug: ordering the view for Association doesn't add the arrow icon (removed ordering in this column).
- improves responsive visual (mobile/tablet/desktop)
- solves other minor graphical issues.
- minor code style improvements
###### Before PR (modal)

before-pr
###### After PR  (modal)

after-pr
#### How to test

Normal view:
1. Install latest staging and apply this patch
2. Go to Components -> News Feeds
3. Check if search, filters, ordering and pagination are working properly
4. Test on mobile and tablet (ex: reduce browser width)

Modal view:
1. Enable language associations.
2. Create some news feeds in several languages.
3. Edit one of those news feeds and go to "Associations" tab and click on "Select" on any language.
4. Check if search, filters, ordering and pagination are working properly in modal.
5. Test on mobile and tablet (ex: reduce browser width)

### CODE REVIEW

**Comment by infograf768** [comment]
To testers, this PR includes the same changes to the field type "Category" as #9195 and https://github.com/joomla/joomla-cms/pull/9198

Therefore they have to be tested separately after reverting these.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 32c1ca5ac031d7441c7d65d1c36b02ebc558bdf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9206">issues.joomla.org/joomla-cms/9206</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 32c1ca5ac031d7441c7d65d1c36b02ebc558bdf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9206">issues.joomla.org/joomla-cms/9206</a>.</sub>

**Comment by brianteeman** [comment]
RTC -thanks for being so thorough in finding all of these issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9206">issues.joomla.org/joomla-cms/9206</a>.</sub>

**Comment by rdeutz** [comment]
@andrepereiradasilva could you have a look at the merge conflicts, thanks.

**Comment by andrepereiradasilva** [comment]
fixed conflicts

**Pull request merged**
