### PR TITLE
[4.0] Fix menu rebuild message in menus

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #34723 .

### Summary of Changes
Remove message JTOOLBAR_REBUILD
Set correct message in com _modules

### Testing Instructions
See  #34723

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 7154bcd67b3a85dc998a48f5c705360566fa43f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34739">issues.joomla.org/tracker/joomla-cms/34739</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7154bcd67b3a85dc998a48f5c705360566fa43f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34739">issues.joomla.org/tracker/joomla-cms/34739</a>.</sub>

**Comment by chmst** [comment]
Thank you for testing. But the more I see the more I am convinced that the button "rebuild" on menus overview is wrong. 
The menus themselves are not a nested sets and therefore must not be rebuilt. 

This button rebuilds the structure of the menuItems. It belongs to menuItems. Wouldn't it be better to remove this button from the menus overview?

**Comment by ChristineWk** [comment]
> This button rebuilds the structure of the menuItems. It belongs to menuItems. Wouldn't it be better to remove this button from the menus overview?

I think the question is, in which case would we need / use this rebuild? I don't know. 
Maybe then it will be easier to answer your question?

**Comment by chmst** [comment]
The rebuild button re-creates the paths of each menu item based on its alias, as well as the path of its parent item. Additionally, it fixes the lft and rgt fields. It is needed on menuItems overview. I am pretty sure that no one knows what it is for and that it does nothing with menus.

**Comment by richard67** [comment]
> Thank you for testing. But the more I see the more I am convinced that the button "rebuild" on menus overview is wrong.
> The menus themselves are not a nested sets and therefore must not be rebuilt.
> 
> This button rebuilds the structure of the menuItems. It belongs to menuItems. Wouldn't it be better to remove this button from the menus overview?

@chmst RTC or not? It has 2 good tests. My personal opinion: As the button rebuilds the complete menu table, I would not remove it from the menus overview.

**Comment by Quy** [comment]
Decision to remove or not to remove the button can be done in a separate PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34739">issues.joomla.org/tracker/joomla-cms/34739</a>.</sub>

**Comment by chmst** [comment]
@richard67 RTC please . Thanks @Quy.

Will make an extra PR for removing the Button.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
