### PR TITLE
[CODE STYLING] Fixes code styling in cms-uncompressed.js

### PR DESCRIPTION
**Pull request by regularlabs**
Fixes code styling in `cms-uncompressed.js`
- indentation
- use of braces
- whitespace
- etc

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Comment by wilsonge** [comment]
RTC on review for 3.7.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16947">issues.joomla.org/tracker/joomla-cms/16947</a>.</sub>

**Comment by laoneo** [comment]
Are the comments of the Hound CI valid ones or will they be ignored?

**Comment by wilsonge** [comment]
None of the issues are introduced with this PR. They're all existing so for the purposes of this PR it's all good. In the long run it should be cleaned up though

**Comment by regularlabs** [comment]
I'll do a cleanup of some of these (dot notation, confusing '!') after this PR is merged.

**Comment by mbabker** [comment]
@C-Lodder do you think you could do a Hound configuration for 3.x since it seems that's running on all PRs and not just 4.0?

**Comment by C-Lodder** [comment]
Sure will do

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/16956 @mbabker

**Comment by rdeutz** [comment]
This needs a test

**Comment by regularlabs** [comment]
Code styling fixes don't need tests.
Especially not when the final minified js file (the one that gets loaded) is not affected.

**Comment by rdeutz** [comment]
So it is only cosmetic ;-) Merged

**Pull request merged**
