### PR TITLE
[4.0] Use variables for Bootstrap badges

### PR DESCRIPTION
**Pull request by SharkyKZ**
Partial Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26052 .

### Summary of Changes

Cleans up badge SCSS a little.
Also removes unused `badge-inverse` class.

### Testing Instructions

Look at some badges (e.g. Post Installation Messages in the header).

### Expected result

Looks the same.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de9d7a686b0808e38545fae92ee8da8b9cb8bf70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28186">issues.joomla.org/tracker/joomla-cms/28186</a>.</sub>

**Comment by brianteeman** [comment]
badge-pill is also used in 
`modules\mod_stats\tmpl\default.php
`and
`build\media_source\com_cpanel\js\admin-system-loader.es6.js`

**Comment by SharkyKZ** [comment]
Removed from `admin-system-loader.es6.js`. Don't see it in `mod_stats`. And this is for backend template only.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/bf7782e9ee009fc78ad9238ea6eefc50fc6089ea/modules/mod_stats/tmpl/default.php#L16

but fare comment about this being an admin only pr

**Comment by SharkyKZ** [comment]
Derp. I did remove it in first commit (https://github.com/joomla/joomla-cms/pull/28186/commits/de9d7a686b0808e38545fae92ee8da8b9cb8bf70#diff-ea6dc2def3568a4d1c41eef8a1b08288).

**Comment by infograf768** [comment]
I have not tested this item.<br /><br />Looks fine here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28186">issues.joomla.org/tracker/joomla-cms/28186</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a01bc62e509e88cee3810a9f8d26f7c1caf7f278<br /><br />Looks fine here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28186">issues.joomla.org/tracker/joomla-cms/28186</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a01bc62e509e88cee3810a9f8d26f7c1caf7f278<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28186">issues.joomla.org/tracker/joomla-cms/28186</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28186">issues.joomla.org/tracker/joomla-cms/28186</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge
Can be merged. Drone failure is unrelated.

**Pull request merged**
