### PR TITLE
[4.0] Fix login button string

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Fix login button string after #17039

### Testing Instructions
Ensure admin login button text ('Log In') is displaying correctly.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0a2201e2cb5c022c7f3d9c2e2fb8f7e6afd1d601<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17089">issues.joomla.org/tracker/joomla-cms/17089</a>.</sub>

**Comment by C-Lodder** [comment]
@wilsonge

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0a2201e2cb5c022c7f3d9c2e2fb8f7e6afd1d601<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17089">issues.joomla.org/tracker/joomla-cms/17089</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
