### PR TITLE
Update Module Select title

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

A recent PR changed the title for the Modules page to display if it was Site or Administrator modules
This PR adds the same functionality to the New Modules Select

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
While you are at it. in the create/edit module view, IMO it should have those title changes too.

Currently is like this
image

**Comment by andrepereiradasilva** [comment]
i tested with success i mark it when you solve the travis stuff

**Comment by brianteeman** [comment]
travis is happy<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10074">issues.joomla.org/joomla-cms/10074</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on bdbb6003bbec41b0f617094736977ca47b3efa28<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10074">issues.joomla.org/joomla-cms/10074</a>.</sub>

**Comment by JoomliC** [comment]
Hummm... don't know why, but the patch is applied (i have checked the code), on localhost, but when select "admin" modules, and then click on "New" button, i still have "site" in header:
capture d ecran 2016-04-24 a 18 00 32

I don't know why... not related to cache... 
The code seems good... Any idea ?

**Comment by brianteeman** [comment]
No idea. Couldn't replicate it

**Comment by JoomliC** [comment]
Sorry, i didn't have updated sraging there, and a change in model select with filter.client_id state changed to client_id : https://github.com/joomla/joomla-cms/commit/99866abd86df4edfd190ff81639b6ade6e6c9e43

So, it ok after test on latest staging! :+1:

**Comment by JoomliC** [comment]
I have tested this item :white_check_mark: successfully on bdbb6003bbec41b0f617094736977ca47b3efa28<br /><br />Test success on latest staging.
Work as describe, and fix the issue in select new module page header<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10074">issues.joomla.org/joomla-cms/10074</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10074">issues.joomla.org/joomla-cms/10074</a>.</sub>

**Pull request merged**
