### PR TITLE
[5.2] alias function usage

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove usage of alias functions, use original functions.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Alias function usage. Alias function doesn't provide full info in IDE.

### Expected result AFTER applying this Pull Request

Original function usage.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
lgtm

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on a40c44e4ee5497d698f7c6d445607c2c943fc497<br /><br />All works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41985">issues.joomla.org/tracker/joomla-cms/41985</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Review by Hackwar — APPROVED** [review]

**Comment by pe7er** [comment]
Thanks @Denitz !

**Pull request merged**
