### PR TITLE
[4.1] Fix undefined $filetype

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #36347

### Summary of Changes
Delete duplicate png.
Fix undefined $filetype.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 2ddb69aa542c8ee4ab6a21b0e92c6a4fa6a9bd1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36705">issues.joomla.org/tracker/joomla-cms/36705</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2ddb69aa542c8ee4ab6a21b0e92c6a4fa6a9bd1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36705">issues.joomla.org/tracker/joomla-cms/36705</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36705">issues.joomla.org/tracker/joomla-cms/36705</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 2ddb69aa542c8ee4ab6a21b0e92c6a4fa6a9bd1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36705">issues.joomla.org/tracker/joomla-cms/36705</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
