### PR TITLE
[4.2] - Adds ordering parameters to web service requests.

### PR DESCRIPTION
**Pull request by pjdevries**
### Summary of Changes

Adds the possibility of passing ordering parameters to `com_content` web service requests in `\Joomla\Component\Content\Api\Controller\ArticlesController::displayList()`

### Testing Instructions

Make a request to https://_&lt;your website&gt;_/api/index.php/v1/content/articles.
Add either or both of the following parameters to the request uri: 
- `list[ordering]=field_name` (where field_name is the name of a field in the SELECT list of the query)
- `list[direction]=direction` (where direction is ASC or DESC).

### Actual result BEFORE applying this Pull Request

Articles returned by the request will always be in `DESC`ending order by article `id`. 

### Expected result AFTER applying this Pull Request

Depending on the ordering parameters passed, articles returned by the request will be in the desired `ASC`ending or `DESC`ending order by the field specified.

### Documentation Changes Required

Obviously, as this is a new feature.

### CODE REVIEW

**Comment by pjdevries** [comment]
@alikon I'm quite sure your dev setup is such, that you can quickly test this PR :) Would you be so kind?

**Comment by richard67** [comment]
@bembelimen Should this be rebased to 4.2-dev?

**Comment by pjdevries** [comment]
Please don't. It's such a simple PR, with no impact on anything else, whatsoever.

**Comment by pjdevries** [comment]
I mean, include it in 4.1 please.

**Comment by pjdevries** [comment]
Apologies for my remarks @richard67. @roland-d just pointed out that 4.1 is RC and does not allow new features. Stupid me.

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 569af00b545739fc159afdeec60d9ffc7d92abca<br /><br />Before the PR the articles came in order of the ID descending. After applying the PR I was able to retrieve articles sorted on the field specified and ordered by the ordering I supplied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36876">issues.joomla.org/tracker/joomla-cms/36876</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36876">issues.joomla.org/tracker/joomla-cms/36876</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you!

**Comment by alexandreelise** [comment]
nice one.

**Pull request merged**
