### PR TITLE
Increases min width on yes/no btn groups

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #13625 .

### Summary of Changes
Increases the min width on yes/no button groups

### Testing Instructions
Check that #13625 is fixed

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f06b69b8846f8b4964eb51ba0bc2440f562eefdb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13698">issues.joomla.org/tracker/joomla-cms/13698</a>.</sub>

**Comment by marrouchi** [comment]
I have tested this item :white_check_mark: successfully on f06b69b8846f8b4964eb51ba0bc2440f562eefdb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13698">issues.joomla.org/tracker/joomla-cms/13698</a>.</sub>

**Comment by marrouchi** [comment]
I would rather suggest making a small change (vertical instead of horizontal buttons) in /administrator/components/com_menus/layouts/joomla/menu/edit_modules.php :
`$html[] = '<fieldset class="form-horizontal"><ul class="vertical-buttons unstyled">';`

**Comment by Fedik** [comment]
maybe would be better to add some left/right padding, instead of width?
current fix will not help, when there will be longer text

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13698">issues.joomla.org/tracker/joomla-cms/13698</a>.</sub>

**Pull request merged**
