### PR TITLE
[4.0] Fix Codemirror as a custom elements

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue #20679 

### Summary of Changes

As @okonomiyaki3000 Suggested to remove the fullscreen message. I removed it.

### Testing Instructions
1. Set default editor to codemirror in global configuration.

2. Open com_content and start creating an article. See, that there are no errors in web console.

3. Open the file `administrator/components/com_content/forms/article.xml` and  the text

```
<field
name="articletext2"
type="editor"
label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
filter="JComponentHelper::filterText"
buttons="true"
/>
```
after the field with the name articletext

4 . Open file
<code>/administrator/components/com_content/tmpl/article/edit.php</code>

and add the text

`<?php echo $this->form->getInput('articletext2'); ?>`

after the text

`<?php echo $this->form->getInput('articletext'); ?>`

### Expected result

No error in console.

Fix codemirror as a customelements .
Credit goes to @dgrammatiko joomla/joomla-cms#20679 (comment)

### Actual result
`/media/vendor/codemirror/mode/text/html/text/html.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]
language string approved

**Comment by anuragteapot** [comment]
@dgrammatiko Please take a look in the code I have done some changes.

**Comment by anuragteapot** [comment]
And, also on eslint codestyle issue . Thanks

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on c8da110c219618903e4a05be15e0a02b5c236b71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20684">issues.joomla.org/tracker/joomla-cms/20684</a>.</sub>

**Comment by astridx** [comment]
I saw no error in console and the language string is changed like explained. I would only suggest to change the language string into something like this:
"In read only mode, a full screen is not possible"
Because the full screen does not open in read only mode.

If more than one editor is in write mode (no read only) on the page, the F10 key opens the editor where the cursor is currently located.

**Comment by laoneo** [comment]
Can you also have a look on the remaining three hound issues?

**Comment by anuragteapot** [comment]
@laoneo Done!

**Comment by laoneo** [comment]
@okonomiyaki3000 can you please test this pr as you are the code mirror expert? Thanks.

**Comment by anuragteapot** [comment]
@brianteeman Can you please check language string? Thanks

**Comment by brianteeman** [comment]
I already have :)

**Comment by okonomiyaki3000** [comment]
A few problems still:

- The theme selector lists all themes twice. Once normally and once as  `.min`. 
- After saving the plugin options, the editor is broken. Console says `Uncaught SyntaxError: Unexpected token <`
- When editing a php file, there seems to be something wrong with syntax highlighting and the html part doesn't do things like tag completion. (now that I try it, this might be broken in the J3 version too...)

**Comment by okonomiyaki3000** [comment]
Ah, and it's a little out of date. The appearance options tab should show a preview of what the editor will look like with the current settings.

**Comment by okonomiyaki3000** [comment]
Oh and why not just remove that silly fullscreen message? I added it in the first place because I was changing the fullscreen hotkey from ctrl-q (seriously, who thought that was a good idea?) to something configurable but I figured that after a while we could remove it. People must have adjusted to the change by now, right?

**Comment by okonomiyaki3000** [comment]
You may like to see #20746 for a way to fix my third point above.

**Comment by laoneo** [comment]
@Anu1601CS can you have a look on the two first issues from @okonomiyaki3000. Thanks.

**Comment by anuragteapot** [comment]
@laoneo I will take a look on it.

**Comment by anuragteapot** [comment]
> A few problems still:
> 
> The theme selector lists all themes twice. Once normally and once as .min.
> After saving the plugin options, the editor is broken. Console says Uncaught SyntaxError: Unexpected token <
> When editing a php file, there seems to be something wrong with syntax highlighting and the HTML part doesn't do things like tag completion. (now that I try it, this might be broken in the J3 version too...)

@okonomiyaki3000 Can you please share the testing instruction?

And, what you want to do in fullscreen message ?

**Comment by okonomiyaki3000** [comment]
The theme selector is in the plugin settings in the appearance tab. It's just a list of themes.

If you run the editor with ever having saved any options, it works. When you open the plugin settings and then save, all pages with codemirror on them will have errors.

To see the syntax highlighting issue, just open any php file with code mirror.

For the fullscreen message, I just think we don't need it at all. It doesn't make much sense. If we need to put instructions for using CodeMirror there, we should have a lot more than just that one item but why should we? We don't list instructions for other things.

**Comment by anuragteapot** [comment]
@okonomiyaki3000 As you suggested #20746 to fix mode, it works fine and syntax highlight is also good. But, one problem is still present, if two codemirror editor is present in a same page, then we are only able to toggle last codemirror to fullscreen ( only one codemirror makes toggle) .

**Comment by anuragteapot** [comment]
@okonomiyaki3000 Seems like i found solution of fullscreen. 
And, should i remove fullscreen message for both ?

**Comment by okonomiyaki3000** [comment]
I'm not really the one to ask. I never liked the message at all. I'm sure someone must have asked me to put it there but it was so long ago... So, personally, I'd love to see it gone. If nobody else objects...

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on f663276e3aecaf55a3c668452bd5d091031c4a51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20684">issues.joomla.org/tracker/joomla-cms/20684</a>.</sub>

**Comment by astridx** [comment]
I saw no error in console. I saw no full screen message. I like it, that there is no full screen message. I think it is confusing if there is more than one editor on a page. If people see the text "click F10 to open full-screen" more than one time, they will be wondering which editor will be opened. 

If more than one editor is in write mode (no read only) on the page, the F10 key opens still the editor where the cursor is currently located. I think this is OK, because so people who know this feature from the past, can still use it.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on f663276e3aecaf55a3c668452bd5d091031c4a51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20684">issues.joomla.org/tracker/joomla-cms/20684</a>.</sub>

**Comment by anuragteapot** [comment]
Thanks @dgrammatiko

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Nice one, thanks all involved.

**Pull request merged**
