### PR TITLE
[4.1] English error

### PR DESCRIPTION
**Pull request by brianteeman**
The correct word to use here is "alternate". ie _we alternate between left and right._

Alternative has a different meaning. ie _As an alternative we could hide the image_

### CODE REVIEW

**Comment by brianteeman** [comment]
Its confusing I know. Alternate has two different meanings depending on how it is pronounced ;)

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 05134eaa7098521014b493bd2159ba219316eb7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37119">issues.joomla.org/tracker/joomla-cms/37119</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 05134eaa7098521014b493bd2159ba219316eb7b<br /><br />Tested successfully in Joomla 4.1.1-dev of 23 February<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37119">issues.joomla.org/tracker/joomla-cms/37119</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
