### PR TITLE
[4.1 ScheduledTasks] Test task to run task and ACL PERMISSION also updated

### PR DESCRIPTION
**Pull request by niharikamahajan02**
Pull Request for Issue #36453 (Part 2).

### Summary of Changes
The ACL Permission also renaming and column header test task renamed to run task.

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :red_circle: unsuccessfully on be523c4b6fcbd43d5041686239da15757db05491<br /><br />@niharikamahajan02 if you change the value for the string COM_SCHEDULER_PERMISSION_TASKRUN, then the constant must also be changed, right?

See https://github.com/joomla/joomla-cms/blob/dc2f3a8e5065f7f728d250836c24c735011db217/administrator/components/com_scheduler/access.xml#L11 and https://github.com/joomla/joomla-cms/blob/dc2f3a8e5065f7f728d250836c24c735011db217/administrator/components/com_scheduler/access.xml#L17

otherwise, unfortunately, this does not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36664">issues.joomla.org/tracker/joomla-cms/36664</a>.</sub>

**Comment by richard67** [comment]
@niharikamahajan02 Does this replace your other PR #36656 ? If so, then please  close that other one. We do not need lots of duplicate PRs here in this repository.

**Comment by tecpromotion** [comment]
> @niharikamahajan02 Does this replace your other PR #36656 ? If so, then please close that other one. We do not need lots of duplicate PRs here in this repository.

Perhaps both should be closed and a new and clean PR with all the incidents submitted as PR.

**Comment by niharikamahajan02** [comment]
> > @niharikamahajan02 Does this replace your other PR #36656 ? If so, then please close that other one. We do not need lots of duplicate PRs here in this repository.
> 
> Perhaps both should be closed and a new and clean PR with all the incidents submitted as PR.

Ok sir , would submit a new PR with required changes suggested by you. Thanks.

**Comment by bembelimen** [comment]
I would prefere to have this PR here the way like it is.

**Comment by richard67** [comment]
> I would prefere to have this PR here the way like it is.

@niharikamahajan02 Could you close your other PR #36656 then? It seems to be duplicate to this one here. Thanks in advance.

**Comment by richard67** [comment]
P.S.: And #36655 and #36607 too, they seem to be also duplicates to be closed.

**Comment by tecpromotion** [comment]
> I would prefere to have this PR here the way like it is.

But it doesn't work like that without further adjustments.

**Comment by niharikamahajan02** [comment]
> P.S.: And #36655 and #36607 too, they seem to be also duplicates to be closed.

Yes , I have closed those PR now.

**Comment by niharikamahajan02** [comment]
> > I would prefere to have this PR here the way like it is.
> 
> But it doesn't work like that without further adjustments.

Yes , @bembelimen sir that's why I thought to make a new PR with suggested changes.

**Comment by tecpromotion** [comment]
> > > I would prefere to have this PR here the way like it is.
> 
> > 
> 
> > But it doesn't work like that without further adjustments.
> 
> 
> 
> Yes , @bembelimen sir that's why I thought to make a new PR with suggested changes.

That is good. However, there are then many more adjustments that are necessary here to make it clean.

**Comment by tecpromotion** [comment]
I think it is easier to close this PR as well and submit all the necessary amendments collectively in PR #36656.

**Pull request closed without merging**
