### PR TITLE
[4] Code Cleanup

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on a1f634c2f1ebd5c1a932b250029a5e03cc2d653a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35125">issues.joomla.org/tracker/joomla-cms/35125</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on a1f634c2f1ebd5c1a932b250029a5e03cc2d653a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35125">issues.joomla.org/tracker/joomla-cms/35125</a>.</sub>

**Comment by Fedik** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35125">issues.joomla.org/tracker/joomla-cms/35125</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
