### PR TITLE
Rename all User Groups

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #36322 .

### Summary of Changes
Due to a bug in the way the parent group field was calculated it was not possible to rename the Public usergroup. Now you can.

### Testing Instructions
Edit the public usergroep
Change the name
Save

### Actual result BEFORE applying this Pull Request
Error: "Invalid field: Group Parent"

### Expected result AFTER applying this Pull Request

New name is saved

### Documentation Changes Required
Remove "The default groups should not be edited!" from the docs

### Notes
1. This will now allow a site owner to rename all the groups to those for their own language instead of english
2. If desired a future pull request could be created to allow translations of the group names for a multilingual website. But that would have to wait for 4.3 as it would be a feature not a bug fix like this PR

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on a94a0d1ee6051d9601cc133e69265a28d5b4ae88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38592">issues.joomla.org/tracker/joomla-cms/38592</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a94a0d1ee6051d9601cc133e69265a28d5b4ae88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38592">issues.joomla.org/tracker/joomla-cms/38592</a>.</sub>

**Comment by chmst** [comment]
Thanks for this PR. 

As users can replace the name "public" now to "wrdlbrmpft", I think it is better to let the English defalt names for all languages also in future. It woul need rewriting lots of tutorials.

**Comment by brianteeman** [comment]
If I ran a multlingual site I would definitely want my non-english speaking admins to be able to understand what the groups are. For people who use a different character set its even harder to understand - thats why I will make it multlingual translatable in a future pr. (just like workflows is)

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38592">issues.joomla.org/tracker/joomla-cms/38592</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by roland-d** [comment]
Thank you

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
