### PR TITLE
[com_finder] Remove unused params

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

This PR removes some params displayed in the form but not used in the code.

### Testing Instructions

Code review.

### Documentation Changes Required

Help article needs updating https://help.joomla.org/proxy?keyref=Help38:Menus_Menu_Item_Finder_Search&lang=en#Advanced_Options

### CODE REVIEW

**Comment by jcata** [comment]
Hi guys, I've tested this patch and is ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20009">issues.joomla.org/tracker/joomla-cms/20009</a>.</sub>

**Comment by Quy** [comment]
@jcata Please do the following to mark your test as successful:

* Open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/20009)
* Log in with your Github account
* Click on blue `Test this` button above author's photo
* Select `Tested successfully`
* Click `Submit test result`

**Comment by jcata** [comment]
I have tested this item :white_check_mark: successfully on 5040a04a2c67991fc71619c775ffbf326931f376<br /><br />Hi guys, I've tested this patch and is ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20009">issues.joomla.org/tracker/joomla-cms/20009</a>.</sub>

**Comment by brianteeman** [comment]
The usual rule is that language strings are not removed as they might be used elsewhere. They can be marked as deprecated

**Comment by SharkyKZ** [comment]
Strings restored and marked for deprecation.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 841cec1eb87272bd4032e43534fae651e7dcc6fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20009">issues.joomla.org/tracker/joomla-cms/20009</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20009">issues.joomla.org/tracker/joomla-cms/20009</a>.</sub>

**Comment by jcata** [comment]
I have tested this item :white_check_mark: successfully on 841cec1eb87272bd4032e43534fae651e7dcc6fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20009">issues.joomla.org/tracker/joomla-cms/20009</a>.</sub>

**Pull request merged**
