### PR TITLE
Registration model doesn't create messages on failed registration email

### PR DESCRIPTION
**Pull request by Denitz**
Pull Request for Issue #8900 .

Correction of message to admins on user registration email send failure.

Testing Instructions:

1. Set dummy SMTP settings in Global Configuration.
2. Register a user, see "Warning!: An error was encountered while sending the registration email. A message has been sent to the administrator of this site." message.
3. There is no message in /administrator/index.php?option=com_messages
4. Apply patch.
5. Register user, see message in /administrator/index.php?option=com_messages

### CODE REVIEW

**Comment by henkrijneveld** [comment]
The messages are added. However, when "Notification mail to administrators"  is set to Yes, still nothing is added (due to the return false in line 585). Probably should be changed to a break in this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9886">issues.joomla.org/joomla-cms/9886</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on db0ca0d2fa3aabb13fae1dc89a9e01d93f8f3e95<br /><br />I have tested this item successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9886">issues.joomla.org/joomla-cms/9886</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on db0ca0d2fa3aabb13fae1dc89a9e01d93f8f3e95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9886">issues.joomla.org/tracker/joomla-cms/9886</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9886">issues.joomla.org/tracker/joomla-cms/9886</a>.</sub>

**Pull request merged**
