### PR TITLE
Load language file from module in ajax interface #3651

### PR DESCRIPTION
**Pull request by zero-24**
This PR Load the language file from module in ajax interface; Coding is by @piotrmocko at #3651

### CODE REVIEW

**Comment by zero-24** [comment]
It is tested on #3651 maybe we can merge here on review?

**Comment by roland-d** [comment]
@zero-24 To merge is fine but there is a CS issue, we need a blank line after line 76. Once that is done, it can be merged. Thanks.

**Comment by zero-24** [comment]
done with https://github.com/zero-24/joomla-cms/commit/55a3861674ee087f2bbea010a44e7d8c948881e3 @roland-d

**Comment by zero-24** [comment]
based on @roland-d's comment i move this here now to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6020">issues.joomla.org/joomla-cms/6020</a>.</sub>

**Comment by jackkum** [comment]
@zero-24 
Sorry for the stupid question, what means RTC? :smile:

**Comment by zero-24** [comment]
@jackkum 

RTC is `Ready to Commit` so a maintainer can merge the PR :smile:

**Comment by jackkum** [comment]
@zero-24 
Thanks very much :smile:

**Comment by infograf768** [comment]
Folks, is this taking into account the loading of the language file from core language folders AS WELL as module/language/ folder?

in com_modules/models/module.php , we use
```
		// Load the core and/or local language file(s).
		$lang->load($module, $client->path, null, false, true)
		||	$lang->load($module, $client->path . '/modules/' . $module, null, false, true);
```

**Comment by infograf768** [comment]
I confirm it is not.

I propose to change from
```
				// Load language file for module
				$lang = JFactory::getLanguage();
				$lang->load('mod_' . $module);
```
to

```
				// Load language file for module
				$basePath = JPATH_BASE;
				$lang = JFactory::getLanguage();
				$lang->load('mod_' . $module, $basePath, null, false, true)
				||	$lang->load('mod_' . $module, $basePath . '/modules/mod_' . $module, null, false, true);
```
To test, use the module proposed by piotrmocko
http://www.perfect-web.co/downloads/mod_ajaxtester-lang.zip


Unzip it, add a `language' folder and an 'en-GB' folder in that `language` folder. move the `en-GB.mod_ajaxtester.ini` file in the `en-GB` folder.
 => `language/en-GB/en-GB.mod_ajaxtester.ini`

then modify the xml to
```
<version>3.3.3</version>
	<files>
		<filename module="mod_ajaxtester">mod_ajaxtester.php</filename>
		<folder>language</folder>
		<folder>tmpl</folder>
		<filename>helper.php</filename>
		<filename>index.html</filename>
	</files>
```
save, zip and install.
Follow instructions of use from
See: https://github.com/joomla/joomla-cms/pull/3651#issuecomment-56193973

**Comment by zero-24** [comment]
Thanks @infograf768 i have just add your fix: https://github.com/joomla/joomla-cms/commit/9ed8cf23da576e5094ae17d7ec292410714cc859

**Comment by infograf768** [comment]
Thanks. Merged.

**Pull request merged**
