### PR TITLE
User save profile: read requested data from session after form validation failed

### PR DESCRIPTION
**Pull request by csthomas**
#### Summary of Changes

[front-end] On save user profile, read requested data from session after form validation failed.
#### Testing Instructions

I believe that code review should be enough.
Please compare to https://github.com/joomla/joomla-cms/blob/staging/components/com_users/controllers/registration.php

**Otherwise**
Front-end: 
[before and after patch]
Go to user profile view, next to edit form and try to save some changes.
For valid changes/data there won't be any difference.

After patch for saving invalid data there will be difference, 
because invalid/request data will be load from session
and the user won't need to re-change valid fields again.

### CODE REVIEW

**Comment by hardiktasol** [comment]
I have tested this item :white_check_mark: successfully on 5e2bacdee64fe7d80ca10efefe8aaf5d0e4fc24e<br /><br />I have tested this patch on Joomla 3.6.0 and patch works perfectly. Data is not storing in sessions and after error it repopulates in the fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10920">issues.joomla.org/joomla-cms/10920</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 5e2bacdee64fe7d80ca10efefe8aaf5d0e4fc24e<br /><br />It works normally as it should. Only changes in code style - variable name.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10920">issues.joomla.org/joomla-cms/10920</a>.</sub>

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10920">issues.joomla.org/joomla-cms/10920</a>.</sub>

**Comment by wilsonge** [comment]
Before this can be merged you need to ensure that passwords are removed from this form. We do not want any passwords being saved into the user session

**Comment by wilsonge** [comment]
Removing RTC so we can get this change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10920">issues.joomla.org/joomla-cms/10920</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou very much! Merged :)

**Pull request merged**
