### PR TITLE
[4.0] layout option for com_contact category menu item

### PR DESCRIPTION
**Pull request by brianteeman**
When #23514 was merged from staging it was not updated for J4

This simple PR does that

### Before
image

### After
image

### CODE REVIEW

**Comment by pranotiTechjoomla** [comment]
I have tested this item :white_check_mark: successfully on 18f60eebce96fb2b791778500cf0c908705129ea<br /><br />I have tested this successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26630">issues.joomla.org/tracker/joomla-cms/26630</a>.</sub>

**Comment by punambaravkar** [comment]
I have tested this item :white_check_mark: successfully on 18f60eebce96fb2b791778500cf0c908705129ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26630">issues.joomla.org/tracker/joomla-cms/26630</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26630">issues.joomla.org/tracker/joomla-cms/26630</a>.</sub>

**Comment by zero-24** [comment]
Merging here thanks @brianteeman and testers 👍

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
