### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by marcobiedermann**
Optimize images with [ImageOptim](https://imageoptim.com/).
Saves 92KB without losing any quality.

joomla-images

### CODE REVIEW

**Comment by designbengel** [comment]
How to test in connection with Joomla ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by balzercomp** [comment]
Nothing to test. Another tool for image compression.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by SniperSister** [comment]
@balzercomp @designbengel in this PR the images already have been optimized with imageoptim.

So, in order to test this, you should check a few of the mentioned images in multiple browsers (and maybe some older operating systems too) to make sure the optimization didn't break anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by designbengel** [comment]
After @SniperSister cleared it up, i wanted to test this but i can´t find the usages of the files.
For Example: administrator/templates/isis/images/admin/featured.png, administrator/templates/isis/images/admin/filesave.png, administrator/templates/isis/images/admin/publish_x.png, administrator/templates/isis/images/admin/icon-16-deny.png

I searched with phpStorm "find in path" option... seems for me there ist some absolutely unused stuff in there ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by mbabker** [comment]
I'm pretty sure in Isis most of the images are unused (1.5 and 2.5 admin templates were really image heavy, Isis is mostly font icons with fewer images).

**Comment by superknutsel** [comment]
I have tested this item :white_check_mark: successfully on 4803f7692a29a4f569509f142e97dc71e7212b6c<br /><br />@test Tested several images in both Firefox, Chrome and Internet Explorer without any issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 4803f7692a29a4f569509f142e97dc71e7212b6c<br /><br />Works! A nice example that all small things count! Thanks for the PR @marcobiedermann<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by marcobiedermann** [comment]
@RickR2H You are very welcome :)

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7828">issues.joomla.org/joomla-cms/7828</a>.</sub>

**Comment by photodude** [comment]
@rdeutz Is there really any reason to hold back this PR until 3.5.1? Seems reducing image file size is a good optimization that should go in 3.5.0.

**Comment by rdeutz** [comment]
Beta state means only bug fixes go in, that's the procedure, that's all.

**Comment by photodude** [comment]
I would consider this a SEO bug since Google flags sites that don't lossly compress images.

**Comment by wilsonge** [comment]
Can we solve the conflicts please?

**Comment by Hackwar** [comment]
@marcobiedermann Can you please fix the conflicts?

**Comment by marcobiedermann** [comment]
@Hackwar Fixed merge conflicts

**Pull request merged**
