### PR TITLE
Fix for admin menu link attribute in component manifest doing nothing

### PR DESCRIPTION
**Pull request by chrBrd**
#### Issue

The link attribute in the parent administrator <menu> element of a component XML manifest is currently completely ignored on installation; it isn't used anywhere. Instead the link is built using a value derived from the undocumented, therefore typically not present, <element> element. As there is usually not a value set for this it defaults to using the component's <name>, causing issues if you want to have the component named slightly differently from any desired URLs.

I'm assuming the link attribute should do something on parent menus, as it's included in all the core component manifests, as well as the 3.x MVC Component [tutorial](https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_a_menu_type_to_the_site_part) and the manifest files [docs](https://docs.joomla.org/Manifest_files#Menu_links_and_submenus) (where it doesn't state the attribute is for submenu use only).
#### Summary of Changes

Created a new method, getMenuLinkOption(), in JInstallerAdapter. This is executed in the getElement() method in the same class. If the admin menu element's link attribute is set it returns a filtered string matching all text after 'option='.

If a string is returned it becomes the extension's element attribute, otherwise the element value defaults to the <name> element from the manifest as usual.
#### Testing Instructions
- Download the MVC Component tutorial [archive](https://github.com/scionescire/Joomla-3.2-Hello-World-Component/archive/step-3-adding-a-site-menu.zip).
- In the component's XML manifest file change value of the <name> element to 'Simple Hello World Component'.
- Install the component

The link to the component in the administrator menu will still work, but the component's name in the extension manager will be 'Simple Hello World Component'. Submenus are linked properly too.
#### Additional Comments

I originally started out changing _buildAdminMenus in JInstallerAdapterComponent. The $option variable used to build all the admin menu links is the value of the manifest's <element> element. This isn't set in any XML manifest I've found and the only reference to it in the code is in the JUpdate class where it doesn't seem to do anything.  Rather than modifying _buildAdminMenus, it was far neater to create a new method in JInstallerAdapter and set the element to the menu link's option. Setting the element attribute this way seems to make more sense given what it's used for anyway. 

The new method maintains compatibility should anyone have used <element> in a manifest. It will also function as normal and default to the <name> element's value if a menu link is not set. If the link attribute's option is changed without a clean install of the component you'll get the same errors you would by changing the component's <name>.

### CODE REVIEW

**Comment by brianteeman** [comment]
I m a little confused by your initial comments so I went to look at the first component I could find which was JCE

This has a line in the xml
 > <menu view="cpanel" img="components/com_jce/media/img/menu/logo.png" link="option=com_jce">JCE</menu>

Which if I understand you correctly you are saying is completely ignored by Joomla during installation and the link is generated by some \<element>

As there is no \<element> in JCE I wondered where the menu is coming from if as you say the \<menu> element is ignored. So to test I deleted that line from the xml and installed JCE. Guess what - no admin menu. My only conclusion is that the \<menu> element is working as documented - or am i missing something

**Comment by chrBrd** [comment]
Look for these lines in the XML:

`<administration>
        <menu view="cpanel" img="components/com_jce/media/img/menu/logo.png" link="option=com_jce">JCE</menu>`

Currently `link="option=com_jce"` is completely redundant, it isn't used anywhere. Instead admin menu links are built using:

`$data['link'] = 'index.php?option=' . $option;`

in the _buildAdminMenus() method in JInstallerAdapterComponent. That value, $option, is initialised like this at the start of the method:

`$option = $this->get('element');`

This then executes the getElement() method from JInstallerAdapter (which is what I've changed).

Here's the original code:

```
if (!$element)
		{
			// Ensure the element is a string
			$element = (string) $this->getManifest()->element;
		}

		if (!$element)
		{
			$element = $this->getName();
		}
```

In any manifest without \<element\> tags, which is probably all of them, this line always returns null:

`$element = (string) $this->getManifest()->element;`

Consequently $element always defaults to the value of \<name\>, and in turn the value of `$data['link'] = 'index.php?option=' . $option;` will always be the same as `$data['link'] = 'index.php?option=jce`, regardless of how the link option is set in the manifest.

If, for any reason, you decided to set `link="option=com_jceditor"`, for example, it wouldn't work - that link attribute is completely pointless at the moment.

**Comment by mbabker** [comment]
If accepted this change needs to be made in the component adapter, not the
base adapter class in a method that will be run on all adapters.

**Comment by brianteeman** [comment]
> If, for any reason, you decided to set link="option=com_jceditor", for example, it wouldn't work - that link attribute is completely pointless at the moment.

OK I can confirm that part - thanks for the explanation

**Comment by chrBrd** [comment]
I thought that may well be the case.

In that case, however, the getElement() method in JInstallerAdapter is totally redundant. I can't find any examples of any Joomla manifests including \<element\> tags, so all it's doing is seeking a null value and then running getName().

**Comment by chrBrd** [comment]
Oh aye, should also point out that to maintain functionality of submenus and some other things, the link option _must_ be saved into the __extension table's 'element' column.

**Comment by mbabker** [comment]
It may well be something that extension developers aren't implementing for
whatever reason (redundant value or undocumented feature).  Either way the
menu item processing is specific to components and shouldn't be in code
executed in all adapters.

**Comment by chrBrd** [comment]
No worries, I'll copy it over.

**Comment by chrBrd** [comment]
That's the changes copied over to the controller's own adapter.

**Comment by roland-d** [comment]
@chrBrd Could you update your PR with the current codebase so we can test this? Thank you.

**Comment by chrBrd** [comment]
I'm afraid that probably won't be happening any time soon - I'm currently busy as sin with other stuff and don't have a working Joomla dev environment ready to go at the moment.

**Comment by roland-d** [comment]
Thank you for following up, I will get someone else to do this.

**Comment by roland-d** [comment]
Closing in favor of #17749

**Pull request closed without merging**
