### PR TITLE
[4.4] Check pagination parameters from request, another try

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Existing approach still have a problem, it is always forcing the parameters defined in `$defaultUrlParams`, and make it impossible to remove. 

I suggest a different approach, take the allowed parameters from the router, and filtering them before adding. Also this now happen in the pagination constructor, which allows for developers to unset unneeded params.

### Testing Instructions

Code review. Test with your component.

Or, add following code, somewhere here https://github.com/joomla/joomla-cms/blob/67cd90ebcd3c8b12a3edd8103c0d94e3236a189c/templates/cassiopeia/index.php#L202
```php
<?php
$pg = new \Joomla\CMS\Pagination\Pagination(100, 0, 20);
$pg->setAdditionalUrlParam('tmpl', null);
echo $pg->getPaginationLinks();
?>
```
Then open any page with `?tmpl=index` in URL, and check pagination links.

### Actual result BEFORE applying this Pull Request
Somehow works.

Pagination links contain `?tmpl=index` .

### Expected result AFTER applying this Pull Request
Works but better.

Pagination links without `?tmpl=index` .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by SniperSister** [comment]
This PR re-introduces the issue that was fixed in the security release.

**Comment by Fedik** [comment]
I updated the PR, it now takes only allowed parameters. However now it is allowing to remove unneeded

**Comment by PhocaCz** [comment]
Testing now, it is interesting that it removes in testing component (Phoca Cart) the format parametr (which is OK) but it does not remove the ID parameter. :-(

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on 097ef2ed4aff25847100de7a6a6e17a0046ccd23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44023">issues.joomla.org/tracker/joomla-cms/44023</a>.</sub>

**Comment by n3t** [comment]
Generally this aproach is much better than the hardcoded one introduced in 4.4.7, however doesn't solve the whole issue. start=0 would lead to duplicate pages issues, search engines wouldn't be happy :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44023">issues.joomla.org/tracker/joomla-cms/44023</a>.</sub>

**Comment by Fedik** [comment]
@n3t your test is unrelated to current PR.
Forfixing `start=0` there need a separated fix. Please test https://github.com/joomla/joomla-cms/pull/44069

**Comment by n3t** [comment]
I have tested this item :white_check_mark: successfully on 399ab15bb4b5fe91b94bccc37d31307d08f09558<br /><br />In combination with patch #44069 this works as expected. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44023">issues.joomla.org/tracker/joomla-cms/44023</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44023">issues.joomla.org/tracker/joomla-cms/44023</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
