### PR TITLE
[4.0] remove deprecated files

### PR DESCRIPTION
**Pull request by brianteeman**
This time its the correct files being removed
Positions was only used in hathor
Preview has not been used for a very long time

Thanks @wilsonge

### CODE REVIEW

**Comment by tonypartridge** [comment]
Please fix conflicts :-)

**Comment by brianteeman** [comment]
@tonypartridge I would if there were any

**Comment by brianteeman** [comment]
Oops sorry the mobile says no and the desktop says yes

**Comment by brianteeman** [comment]
i really dont see how a PR to remove a file can have conflicts or how the conflicts can be fixed - please advise @wilsonge

**Comment by mbabker** [comment]
You probably can't fix this one through the GitHub UI on its own.

Even when you delete/rename files, git can still track those operations so it sees that you tried one change and someone else tried another change and it creates a conflict because it gets confused.

**Comment by brianteeman** [comment]
best to close and create a new pr?

**Comment by mbabker** [comment]
Unless George wants to just manually merge this then yes.

**Comment by brianteeman** [comment]
@wilsonge please advise

**Comment by wilsonge** [comment]
Sorry do it again. Will make sure it gets merged

**Pull request closed without merging**
