### PR TITLE
[5.2] replace scss variables by css variables

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #41105 .

### Summary of Changes

This PR will replace the SCSS variables used to adjust the styling of btn-secondary by css variables. 
With this change we are more in line with the rest of the css using css variables

### Testing Instructions

Before and after the test the look and feel of an element with className `btn-secondary` should be the same
- Have a Joomla website up and running
- Apply this PR
- Rebuild the assets using `npm run watch` (or similar)
- Refresh the page 
- Inspect the css inside Dev Toolbar

### Actual result BEFORE applying this Pull Request

Scherm­afbeelding 2023-12-13 om 16 27 45

### Expected result AFTER applying this Pull Request

Scherm­afbeelding 2023-12-13 om 16 28 22

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@hans2103 When you make a pull request for your own issue then please close the issue.

**Comment by hans2103** [comment]
> quest for your own issue then please close th

my bad... thank you

**Comment by fgsw** [comment]
The Download is not available (```Expected — Waiting for status to be reported```).

**Comment by brianteeman** [comment]
Not expected - it should not take 2 days ;)

**Comment by alikon** [comment]
Prebuilt Download Packages are available here https://artifacts.joomla.org/drone/joomla/joomla-cms/5.1-dev/42509/downloads/72262

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d24a009faa5af19d29406bc44fdff390fad77d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42509">issues.joomla.org/tracker/joomla-cms/42509</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9d24a009faa5af19d29406bc44fdff390fad77d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42509">issues.joomla.org/tracker/joomla-cms/42509</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42509">issues.joomla.org/tracker/joomla-cms/42509</a>.</sub>

**Comment by pe7er** [comment]
Thanks @hans2103 !

**Pull request merged**
