### PR TITLE
[3.7.x] Input field invalid highlight

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #12438  .
### Summary of Changes

Adds highlight (border & text) to input fields if invalid.
### Testing Instructions

Navigate to Global Configuration -> System. Check 'Session Lifetime' field with non integer number (0.5).

**Before Patch**
session-field1

**After Patch**
session-field2
### Documentation Changes Required

None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
hum ... imho this should be applied to all invalid fields (input select) not only session. i think in staging works like that

**Comment by ciar4n** [comment]
Ah I was just thinking that. I'll change this to cover all fields.

**Comment by C-Lodder** [comment]
Just FYI, `input:invalid` only work for IE10 and above. EI10 is still only partially supported.

**Comment by andrepereiradasilva** [comment]
in staging (3.6.3) template.css
https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/css/template.css#L1343

**Comment by ciar4n** [comment]
@andrepereiradasilva This CSS still exists in 3.7 however was been overridden. This is now the applied CSS with the latest commit so highlighting is now the same as 3.6. Thank you.

@C-Lodder True. I guess using javascript is the only B/C solution. I'll leave this PR to revert invalid highlighting to that of 3.6.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1d688cd4475ad59a5dfc2cbf26c7c9d15c81f798<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12443">issues.joomla.org/tracker/joomla-cms/12443</a>.</sub>

**Comment by dgt41** [comment]
Mixing browser's native validation with joomla's own javascript validation will require something more than the css code. Don;t get me wrong I like the idea, but it needs more than this. Although this works fine (the problem is that the rest of the fields will not behave the same...)

**Comment by ciar4n** [comment]
@dgt41 This PR no longer adds any CSS. Instead it ensures that the original bootstrap 'invalid' CSS is been used as was the case in 3.6.. https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/css/template.css#L1343

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1d688cd4475ad59a5dfc2cbf26c7c9d15c81f798<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12443">issues.joomla.org/tracker/joomla-cms/12443</a>.</sub>

**Comment by C-Lodder** [comment]
@ciar4n - conflicts need fixing before rtc is set

**Comment by ciar4n** [comment]
Thank you. Forgotten about this.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ca1ef0ec969a5a9f58de72d1beddfb1ee4286bb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12443">issues.joomla.org/tracker/joomla-cms/12443</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on ca1ef0ec969a5a9f58de72d1beddfb1ee4286bb7<br /><br />tested successfully - but can it stay highlighted instead of fading out after leaving the focus?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12443">issues.joomla.org/tracker/joomla-cms/12443</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12443">issues.joomla.org/tracker/joomla-cms/12443</a>.</sub>

**Comment by wilsonge** [comment]
Conflict fixes again please - sorry!

**Comment by ciar4n** [comment]
@wilsonge Fixed!

**Pull request merged**
