### PR TITLE
Front side bugs

### PR DESCRIPTION
**Pull request by coolcat-creations**
Changed the wording and Removed unused Language Strings

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Wrong branch, sorry :)

**Comment by dgrammatiko** [comment]
@coolcat-creations editing the title you can change the branch

**Comment by brianteeman** [comment]
i just changed it to j4 branch but still not correct :(

**Comment by dgrammatiko** [comment]
@brianteeman you need to reopen :)

**Comment by coolcat-creations** [comment]
Its ok its already merged there thank you, i checked it out wrong i guess

**Pull request closed without merging**
