### PR TITLE
[com_fields] Change extension variable to context for custom field groups

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The new field groups (#13019) are created globally per component. It means when a component has more than one context, it is not possible to create groups per context. This pr solves that and allows to create groups per context of fields. A field belongs to a context and with this pr the group as well.

It fixes also an issue where a second asset per group is created when a permission has changed.

### Testing Instructions
After a fresh installation, create groups, assign fields to them. All should work as before.

A fresh installation is needed as the database schema has changed..

### CODE REVIEW

**Comment by Bakual** [comment]
Some background to explain why I chose "extension" instead of "context" for the groups:
* com_categories basically does the same thing and uses "&extension" as the URL parameter to determine the category context. So I just kept the "standard".
* "context" is already used in JModelList as a class proeprty ($this->context). There is some chance for confusion if there is an additional context which doesn't relate to the model context.

So imho we should change all "context" to "extension" but Allon disagrees with me here :smile:

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 8a7f5b018cc141d6ce3efe4fab0a5371b815c855<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13175">issues.joomla.org/tracker/joomla-cms/13175</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 8a7f5b018cc141d6ce3efe4fab0a5371b815c855<br /><br />Test OK.

Amazing progress!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13175">issues.joomla.org/tracker/joomla-cms/13175</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC based on 2 successful tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13175">issues.joomla.org/tracker/joomla-cms/13175</a>.</sub>

**Comment by laoneo** [comment]
Thanks to the testers!

**Pull request merged**
