### PR TITLE
[5.1] Dark Mode menu select toggle colour

### PR DESCRIPTION
**Pull request by brianteeman**
final part Pull Request for Issue #43068 .

### Summary of Changes
Change the colour of the icon in the treeselect for assigning modules to pages to satisfy contrast rules

### Testing Instructions
see #43068 for more details

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d9bd44ac56d6187a737546af9fd6d0a029697aa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43160">issues.joomla.org/tracker/joomla-cms/43160</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d9bd44ac56d6187a737546af9fd6d0a029697aa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43160">issues.joomla.org/tracker/joomla-cms/43160</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43160">issues.joomla.org/tracker/joomla-cms/43160</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @brianteeman and also for testing @viocassel @Quy

**Comment by brianteeman** [comment]
thanks

**Comment by RickR2H** [comment]
@brianteeman I commited to the 5.2 branch. I think you PR was not up-merged. That why I didn't notice it. I'll close my PR and I'll wait for the up-merge.

**Pull request merged**
