### PR TITLE
[4.1] Missing error strings in installation

### PR DESCRIPTION
**Pull request by brianteeman**
Partial PR for #36370
see https://github.com/joomla/joomla-cms/issues/36370#issuecomment-1000136274

### CODE REVIEW

**Comment by richard67** [comment]
By review I think the added stings are ok, but I haven't really managed to get one of them shown when making an installation and choosing to install some languages at the end. E.g. I disabled the allow_url_fopen setting but did not get the JLIB_UPDATER_ERROR_COLLECTION_FOPEN message shown anywhere.

**Comment by brianteeman** [comment]
We definitely need the parse string. As the others are related I figured there was no harm in adding thosse as well.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e84078df93f0ea8e5545a0b867a5e6c539fa4833<br /><br />By review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37286">issues.joomla.org/tracker/joomla-cms/37286</a>.</sub>

**Comment by RickR2H** [comment]
@brianteeman 
I noticed that the language strings **JLIB_UPDATER_ERROR_COLLECTION_FOPEN** and **JLIB_UPDATER_ERROR_COLLECTION_OPEN_URL** aren't used in any file? Can you point me where the strings are used?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37286">issues.joomla.org/tracker/joomla-cms/37286</a>.</sub>

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/37286#issuecomment-1070960130

**Comment by brianteeman** [comment]
They are some of the compound strings so you wont be able to seatch the code base for them

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on e84078df93f0ea8e5545a0b867a5e6c539fa4833<br /><br />I tried differente ways (on WAMP) but was also unable to reproduce the error. But as they are valid text strings I agree with @richard67 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37286">issues.joomla.org/tracker/joomla-cms/37286</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37286">issues.joomla.org/tracker/joomla-cms/37286</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
