### PR TITLE
[5.0] Fix cli installation

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

1. Apply the changes from `installation/includes/app.php` of #36499 also for cli `installation/includes/cli.php`
2. Apply the changes from `installation/src/Application/InstallationApplication.php` of #40664 also for cli `installation/src/Application/CliInstallationApplication.php`

### Testing Instructions

run `php installation/joomla.php`

### Actual result BEFORE applying this Pull Request

image

image

### Expected result AFTER applying this Pull Request

image

image

### CODE REVIEW

**Comment by HLeithner** [comment]
@wilsonge that was not expected or?

**Comment by heelc29** [comment]
The PR for "cli installation" #38325 have been merged in october 2022 and the pr for "rework session/application" is last updated in june 2022...

**Comment by heelc29** [comment]
@HLeithner I also found another bug that interrupts the installation (has something to do with the compat plugin pr)

**Comment by heelc29** [comment]
Since the API system tests were also moved to cypress in 4.4, there is no longer a "test" for the cli installation 😢

**Comment by wilsonge** [comment]
Yeah as @heelc29 says. CLI came along after my PR and i didn't even think about it when rebasing.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
