### PR TITLE
Enable caching of the module list for page loads

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Cache the result set of the query to load modules for a page.

This will cache based on an ID generated for the variables for a query; the user's authorized view levels, the current client ID, the menu item ID, and on the frontend if the language filter is enabled the language code.
#### Testing Instructions

The modules assigned to a page based should be cached based on the conditions for the request and data properly loaded going forward.  As an example, all guests visiting the frontend with a page assigned to menu item ID 101 would have the same data set; users in the registered user group visiting a page with no Itemid would have a unique data set, etc.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on c848f8f08631e3c3cdf3ef628828a9d646172d56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10796">issues.joomla.org/joomla-cms/10796</a>.</sub>

**Comment by csthomas** [comment]
Do you wondered about the publish up/down time and cache time?

What about if I set cache to 24 hours and I have publish up time to show module ex. on Monday at 00:00.
For some groups module won't show at correct time. The same for publish down.

I know you can say that I should disable cache for that module and problem disappears.
If that is not a problem then OK, you do not need to read below.

Other way you can load all modules means with out checking dates and cache that.
After that each time when you load you have to filter by dates (publish_up/down)

**Comment by mbabker** [comment]
The same issue is going to exist with anything that is cached and has publish up/down times.  If you're caching component or module content, you're hitting this issue already.  If your site has such a requirement that these things need to be precise to the second then caching is probably something you have disabled to begin with; otherwise if you can live with things generally being off by a little bit then it's an acceptable tradeoff or you manually go in and clear the cache for the affected groups.

**Comment by csthomas** [comment]
I just wanted to note this issue there.
If you say it is OK, then so be it.

**Comment by mbabker** [comment]
It's a legitimate concern to be aware of but it's not something that's unique to this patch.  In general that's one of the tradeoffs you're going to hit when using a caching mechanism in front of a system which has time based conditionals.

**Comment by mbabker** [comment]
Is this going anywhere or can I close for lack of interest?

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c848f8f08631e3c3cdf3ef628828a9d646172d56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10796">issues.joomla.org/joomla-cms/10796</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c848f8f08631e3c3cdf3ef628828a9d646172d56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10796">issues.joomla.org/joomla-cms/10796</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10796">issues.joomla.org/joomla-cms/10796</a>.</sub>

**Pull request merged**
