### PR TITLE
[4.0] Code cleanup: remove unnecessary onContentAfterSave in PlgFieldsRepeatable

### PR DESCRIPTION
**Pull request by nhusung**
### Summary of Changes

Prior to this pull request `PlgFieldsRepeatable::onContentAfterSave` was responsible for converting the field values to JSON. However `PlgSystemFields::onContentAfterSave` (see below) does the same task. This pull request removes the unnecessary processing.

https://github.com/joomla/joomla-cms/blob/27371eecdba5247fdc5344c85f616ea1b1aa8e08/plugins/system/fields/fields.php#L66-L148

### Testing Instructions

Create a custom field of type repeatable and save data to it. After the saving process the entered data should still be there.

### Expected result

Same as before this commit

### CODE REVIEW

**Comment by stutteringp0et** [comment]
Isn't the repeatable field type deprecated?  I thought everything deprecated was being removed in J4.

https://docs.joomla.org/Repeatable_form_field_type

**Comment by nhusung** [comment]
There is an issue concerning the plugin‘s name. It is true that the repeatable form field is deprecated but this is only the repeatable com_fields plugin, which internally uses the subform form field. I already considered renaming this plugin, however the only use case I could imagine is to have repeatable fields. Anyway, this plugin was first introduced in J4.0 and backported to J3.9 afterwards.

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on d7987bd35e3f27ee810b1b38fa6d8f3314ba9c27<br /><br />After merging latest dev branch into this (to actually be able to add fields) data is stored in the repeatable field after the removal of the code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24506">issues.joomla.org/tracker/joomla-cms/24506</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on d7987bd35e3f27ee810b1b38fa6d8f3314ba9c27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24506">issues.joomla.org/tracker/joomla-cms/24506</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24506">issues.joomla.org/tracker/joomla-cms/24506</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
