### PR TITLE
[#33270] Add ability to empty the message queue

### PR DESCRIPTION
**Pull request by ghost**
Tracker: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33270

This PR makes it possible to empty the message queue.
#### The issue

Since Joomla 3, the `_messageQueue` in the `JApplicationCms` is private, so it cannot be overwritten.
In Joomla 2.5, if you want to reset/empty the message queue, you can simply do:

``` php
JFactory::getApplication()->set('_messageQueue', '');
```

In Joomla 3 that is not possible.
#### The solution

This PR adds a (smart) public method to be able to clear the message queue.
To clear the entire message queue, you can now simply do:

``` php
JFactory::getApplication()->clearMessageQueue();
```

You can also give an array of types to clear. So if you only want to clear the messages and notices, but not the errors, you can do:

``` php
JFactory::getApplication()->clearMessageQueue(array('message', 'notice'));
```
#### Some fool-proofing

There are some extra checks to make it a little fool-proof.

You can also pass a string instead of an array if you only want to clear 1 type:
So these do the same:

``` php
JFactory::getApplication()->clearMessageQueue('message');
JFactory::getApplication()->clearMessageQueue(array('message'));
```

It will also check if you put the plural form of the type(s) instead. So if you give `messsages` instead of `message`, or `errors` instead of `error`.
So these do the same:

``` php
JFactory::getApplication()->clearMessageQueue('message');
JFactory::getApplication()->clearMessageQueue('messages');
```

The entire queue will also get cleared if the given types include `all`.
So these all do the same:

``` php
JFactory::getApplication()->clearMessageQueue();
JFactory::getApplication()->clearMessageQueue('all');
JFactory::getApplication()->clearMessageQueue(array('all'));
JFactory::getApplication()->clearMessageQueue(array('all', 'message'));
```
#### Why need this?

Well, sometimes you want to be able to clear the messages and only show an error.
Or if some error occurs, you want to only show that error, and not anything else in the error queue.
Think for example the long lists of (nearly) the same errors you sometimes get when installing something because a bunch of folders are not writable.
With this you could catch that and just return a single error.

### CODE REVIEW

**Comment by pollen8** [comment]
I'd like to see this as well.
Here's an example of where I need it. 
Fabrik has its own password field, these fields are extended from JFormField, but I do want to use the JRulePassword class to validate it against the new com_user password options. The JRule class enqueue their message in the application. However, Fabrik works by inserting errors inline, next to their corresponding field. This gives the form better affordance than simply displayed at the top of the page.
However now the form shows messages both at the top of the page and next to the field. :(

I don't buy the theory that its an issue - you could take that argument to the extreme and say that we shouldn't provide db access to developers in case they drop tables. However, what might be good would be to add a new property to the message array to state the provenance of the message e.g. 'com_user', 'lib_cms' etc. And ass creativeprogramming states you can get round this by using a reflexion class anyway. All we really want to do is provide a simple interface for developer to access rather than hacking a less than optimal solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3098">issues.joomla.org/joomla-cms/3098</a>.</sub>

**Comment by pollen8** [comment]
for what its worth here's a slightly modified version of the function to kill a message type: taken from https://groups.google.com/forum/#!topic/joomla-dev-general/TRFT0gtNIio

```
function _killMessage($app, $type)
	{
		$appReflection = new ReflectionClass(get_class($app));
		$_messageQueue = $appReflection->getProperty('_messageQueue');
		$_messageQueue->setAccessible(true);
		$messages = $_messageQueue->getValue($app);

		foreach ($messages as $key => $message)
		{
			if ($message['type'] == $type)
			{
				unset($messages[$key]);
			}
		}

		$_messageQueue->setValue($app, $messages);
	}
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3098">issues.joomla.org/joomla-cms/3098</a>.</sub>

**Comment by GeoTimber** [comment]
thanks Pollen, it is a must 4m to be able to override a message, there is always a Use Case that wants you to do just that.

Speed of development is important too. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3098">issues.joomla.org/joomla-cms/3098</a>.</sub>

**Comment by nueckman** [comment]
Sorry, but this code scares the hell out of me. Reflection does have some benefits, but it should surely not used to alter core classes at runtime.

**Comment by tgv604** [comment]
Here's a case - http://issues.joomla.org/tracker/joomla-cms/6993<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3098">issues.joomla.org/joomla-cms/3098</a>.</sub>

**Pull request closed without merging**
