### PR TITLE
[4.0] Remove mod_footer directory

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

We've remove the SQL to install `mod_footer` in Joomla 4 as we went with a custom module instead. So this PR also removes the `mod_footer` directory.

100% B/C.

3.x to 4.x won't be affected as we're not uninstalling it via `com_admin`

### Testing Instructions

Just a code review needed

@brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good to me.

(At some point we will need to make sure that all the file changes are handled correctly in the ugrade scripts)

**Comment by brianteeman** [comment]
Just a thought

We are not including it on new installs but are keeping it on upgrades. 

Potentially this could cause a problem in the future if there were any bugs or security issues with the module as it wouldnt be maintained any more

**Comment by brianteeman** [comment]
The more I think about this the more issues i see going forward. We will end up in the situation that all sites which have been updated will have a core module on their site (that is not mantained) and all new sites will not have the same core modules.

This will create lots of issues for example a template club which uses the footer module on a J3 site will need to either  not use that module anymore or have code to see if the module exists or not.

Removing it from new installs only  just because we dont need to use it (or there is a better way) is not a good idea

**Comment by C-Lodder** [comment]
How was it done for weblinks?

**Comment by brianteeman** [comment]
Weblinks is different because it was not abandoned but became a standalone extension in itss own right so that users on new installs could still install it if they wanted to and so that if there were any bugs we had a method to push an update to weblinks

**Comment by C-Lodder** [comment]
Thing with `mod_footer` is that it's **completely** the wrong approach. Hardcoding a string based on a language constant, which doesn't allow the user to customize it to their needs without having to find the language string and override it.

Most big template providers I know either have a textarea in the template settings of make use of a custom module.

I know where you're coming from, but based on the above, I'm still in favour of this PR.

Let's see what others have to say I suppose.

**Comment by brianteeman** [comment]
I am not disagreeing with not using the module - just that we need to think carefully before it is removed in this way

**Comment by mbabker** [comment]
If we intend to remove it (which IMO we're fine to do), we should properly uninstall it from all sites.  If we're going to keep it installed and usable in existing sites, we will have to extract it to a repo and put the info needed into the core package to add an update server for it (as was done when the weblinks code was extracted).  It's bad news for us to strip out a core extension but leave it installed as abandonware on user sites.

**Comment by brianteeman** [comment]
With our track record with decoupled extensions its easier all round just to keep it ;)

**Pull request closed without merging**
