### PR TITLE
remove incorrect text

### PR DESCRIPTION
**Pull request by brianteeman**
In the article options 5 strings had the text
"This is a global setting but can be changed at the Category, Menu and Article levels."

This text is not needed because 
1) it applies to all options set on the article options screen - so it should be on all or none
2) the same string is used in the other locations mentioned in the string eg menu item single article options screen where it is not correct to say its a globale setting

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on f55ee0c229e4292c85943ac31669d1db33360b55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11386">issues.joomla.org/joomla-cms/11386</a>.</sub>

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on f55ee0c229e4292c85943ac31669d1db33360b55<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11386">issues.joomla.org/joomla-cms/11386</a>.</sub>

**Comment by brianteeman** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11386">issues.joomla.org/joomla-cms/11386</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the merge conflicts, thanks.

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the merge conflicts, thanks.

**Comment by brianteeman** [comment]
@rdeutz merge conflicts resolved

**Pull request merged**
