### PR TITLE
[5.0] Modal field for MenutypeField

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Changing MenutypeField field to use new modal dialog.

It may not hit 5.0, but in future will need to update anyway.

### Testing Instructions
Run `npm install`

Create/Edit menu item, change the menu type.

### Actual result BEFORE applying this Pull Request
Works with old bs modal

### Expected result AFTER applying this Pull Request
Works with new dialog.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: as part of https://github.com/joomla/Manual/pull/178
- [ ] No documentation changes for manual.joomla.org needed

Reference:
- https://github.com/joomla/joomla-cms/pull/40462

### CODE REVIEW

**Comment by Fedik** [comment]
> New Menu Item has component preset

Hm, no, something wrong. Need to check.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 7efeb34db33bdfa6ce735e35d4bfd88ffe17de42<br /><br />It works - I see the different types of dialog. But it was my understanding that iframes are not recommended by some authorities. Has the wind changed? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41632">issues.joomla.org/tracker/joomla-cms/41632</a>.</sub>

**Comment by Fedik** [comment]
> I have tested this item

Sorry, I made litle more change, please try again.
It still should be the same, but just to be sure. Thanks!

> But it was my understanding that iframes are not recommended by some authorities

It depend for what it is used and when :wink:

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b52d8846952b7c79aae7b3ec081dc9e06605a422<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41632">issues.joomla.org/tracker/joomla-cms/41632</a>.</sub>

**Pull request merged**
