### PR TITLE
[5.0] typo sss

### PR DESCRIPTION
**Pull request by brianteeman**
Obvious typo classs/class

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman In addition, we have the same typos in the same file in 4.4-dev, too.

**Comment by brianteeman** [comment]
> @brianteeman In addition, we have the same typos in the same file in 4.4-dev, too.

i'm not wasting my time looking at 4.4

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e9ab8bb968f8b7de4145ccce965d3b2e5fd7cdd7<br /><br />Ok by review. Same 2 typos in the same file we also have in 4.4-dev. Both my mistake Release managers shall decide when and there it is to be fixed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41948">issues.joomla.org/tracker/joomla-cms/41948</a>.</sub>

**Comment by laoneo** [comment]
> > @brianteeman In addition, we have the same typos in the same file in 4.4-dev, too.
> 
> i'm not wasting my time looking at 4.4

Why not?

**Pull request merged**
