### PR TITLE
[4.0] Atum: Changing hue value, module-position-colour stay same

### PR DESCRIPTION
**Pull request by pinak3748**
### Summary of Changes

> This is issue #34307

  <h3>What needs to be fixed</h3>

<p>Go to <code>System</code>&gt; <code>Administrator Template Styles</code> and change the hue value for the dark template colour (i used 89).</p>
<p>In modules the position-colour stay same:</p>
<blockquote>
<p><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/78906980/120194884-786aba80-c21e-11eb-9354-25313839a3ea.png">image</a></p>
</blockquote>
<h3>Why this should be fixed</h3>
<p>At <code>Menu</code> (multilingual site) the colour change.</p>
<table role="table">
<thead>
<tr>
<th>Changed template style</th>
<th>Default template style</th>
</tr>
</thead>
<tbody>
<tr>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/78906980/120194617-1c079b00-c21e-11eb-9b23-3e885a767f65.png">image</a></td>
<td><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/78906980/120196517-3b9fc300-c220-11eb-81e5-b9cf310ae925.png">image</a></td>
</tr>
</tbody>
</table>

### Expected result AFTER applying this Pull Request

aaa

### CODE REVIEW

**Comment by drmenzelit** [comment]
Hi @pinak3748 , thank you for your contribution. Please check the Bootstrap documentation for badges: https://getbootstrap.com/docs/5.0/components/badge/
In your PR you are mixing badge and btn classes.

**Comment by pinak3748** [comment]
Thanks for letting me @drmenzelit  know I have made the changes without using buttons or badges

**Comment by pinak3748** [comment]
@brianteeman  Can you review and test my changes

**Comment by pinak3748** [comment]
Can someone please test changes on #34923

**Comment by drmenzelit** [comment]
@pinak3748 please be patient... I checked the code, but not tested the PR. You are now giving all badges a background colour, that seems wrong to me. Have you checked for side effects? What happen to other badges in the backend?

**Comment by pinak3748** [comment]
I have checked this in all cases but I think I misss the object of the issue and created a new one along that way and my approach is wrong so that's why I am closing this issue.

**Pull request closed without merging**
