### PR TITLE
[4.1] Automating the rmrf on the startup of the (npm) build tools

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue  #35198 .

### Summary of Changes

With #35198 we introduced a registry for all the folders of the media folder. This PR just automates the creation/update of that registry.

### Testing Instructions

This PR needs `npm`

- modify the `build/build.js` so that line 157 to line 171 are muted eg: 

```js
// Prepare the repo for dev work
if (Program.prepare) {
    const bench = new Timer('Build');
    allowedVersion();
    recreateMediaFolder(options)
    // .then(() => cleanVendors())
    // .then(() => localisePackages(options))
    // .then(() => Promise.all(
    //   [
    //     patchPackages(options),
    //     minifyVendor(),
    //     createErrorPages(options),
    //     stylesheets(options, Program.args[0]),
    //     scripts(options, Program.args[0]),
    //     bootstrapJs(),
    //     mediaManager(true)
    //   ]))
    // .then(() => bench.stop('Build'))
    // .then(() => { process.exit(0); })
    .catch((err) => {
      // eslint-disable-next-line no-console
      console.error(err);
      process.exit(-1);
    });
}
```
and also mute line 73 of `build/build-modules-js/init/recreate-media.es6.js` `// await copy(join(RootPath, 'build/media_source'), join(RootPath, 'media'), { filter: filterFunc });`

- Run `node ./build/build.js --prepare`
- Check that all the existing folders in the `media` are empty and any non-core Joomla extensions are unaffected

### Documentation Changes Required

@richard67 this is the missing part you were asking at #35198

@wilsonge @HLeithner ~~this one actually needs to run with a GitHub action on every merge, let me know if you want me to add the action here or is something for you...~~

### CODE REVIEW

**Comment by wilsonge** [comment]
Is there a reason we put this as a config setting rather than just generating this list of directories at run time?

**Comment by dgrammatiko** [comment]
> Is there a reason we put this as a config setting rather than just generating this list of directories at run time?

That will work also. I'm tweaking the code to do that... (hopefully, I won't recall some weird edge case that the registry is needed)

**Comment by dgrammatiko** [comment]
@wilsonge updated

**Comment by wilsonge** [comment]
@dgrammatiko i think you didn't push :)

**Comment by dgrammatiko** [comment]
> @dgrammatiko i think you didn't push :)

Don't you love Github's PWA? It's a caching thing, try hard reload to see the commit...

**Comment by HLeithner** [comment]
do we really need this after each merge?

**Comment by dgrammatiko** [comment]
> do we really need this after each merge?

No, not anymore the code is auto-generating the list at runtime. Sorry, I forgot to remove the comment above...

**Comment by dgrammatiko** [comment]
@wilsonge reminder that this one needs to be merged at some point. Thanks

**Comment by dgrammatiko** [comment]
@wilsonge friendly reminder for this one

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on fe62137aa80f6daec8ccfc961cd6e12904e8d500<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35322">issues.joomla.org/tracker/joomla-cms/35322</a>.</sub>

**Comment by dgrammatiko** [comment]
@richard67 could you test this one?

**Comment by richard67** [comment]
> @richard67 could you test this one?

@dgrammatiko Not before late tonight or tomorrow, not sure yet when.

**Comment by richard67** [comment]
@bembelimen Maybe this one should be rebased to 4.1-dev, too? If that works cleanly we could maybe still count the one human test which is has right now.

**Comment by dgrammatiko** [comment]
> Maybe this one should be rebased to 4.1-dev, too?

I did it through the GitHub UI and I guess it worked

**Comment by wilsonge** [comment]
LGTM. Thanks!

**Comment by dgrammatiko** [comment]
Thanks George!

**Comment by richard67** [comment]
Thanks for saving me time for testing 😄 .

**Pull request merged**
