### PR TITLE
CodeMirror Updated to 5.34.0

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue #19520 .

### Summary of Changes
See here: http://codemirror.net/doc/releases.html
Although not mentioned on the releases page, the previous version had a Typo that caused syntax coloring of PHP code to stop working. This is fixed in the new version.

### Testing Instructions
Use codemirror.

### Expected result
It will work as usual.

### Actual result
It works as usual.

### Documentation Changes Required
Nope

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2c0d2f4f405538ead087f6c29629178d6db5fdb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19533">issues.joomla.org/tracker/joomla-cms/19533</a>.</sub>

**Comment by ghost** [comment]
@okonomiyaki3000 #19522 is same PR, should this one be closed as #19522 is RTC?

**Comment by brianteeman** [comment]
@franz-wohlkoenig the other way around as this is the official update from codemirror. We should never be changing upstream files ;)

**Comment by okonomiyaki3000** [comment]
#19522 is not needed if this is merged. 

However, I should point out that it does not modify any upstream files. It does not fix codemirror's bug, it merely works around it. So merging that would potentially protect against the same or similar bug being introduced in a future version of codemirror.

**Comment by davidbrooksio** [comment]
I have tested this item :white_check_mark: successfully on 2c0d2f4f405538ead087f6c29629178d6db5fdb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19533">issues.joomla.org/tracker/joomla-cms/19533</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 2c0d2f4f405538ead087f6c29629178d6db5fdb2<br /><br />Everything seems good in Joomla template manager,
Tested usage of code mirror in custom extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19533">issues.joomla.org/tracker/joomla-cms/19533</a>.</sub>

**Pull request merged**
