### PR TITLE
User profile form is prepated twice in frontend. #18065

### PR DESCRIPTION
**Pull request by Denitz**
Pull Request for Issue #18065

### Steps to reproduce the issue

debug FieldsHelper::prepareForm() and see that it's launched twice in frontend:

Initially via PlgSystemFields->onContentPrepareForm event and see that it's launched twice in frontend.

Next FieldsHelper::prepareForm() is called again via UsersModelProfile::getForm()

### Expected result

FieldsHelper::prepareForm() should be called once on user profile form display.

### Actual result

Called twice

### CODE REVIEW

**Comment by Denitz** [comment]
Who can fix AppVeyor issue with `sqlite` for PHP 5.6?

http://ci.joomla.org/joomla/joomla-cms/136 fails as well.

**Comment by stutteringp0et** [comment]
This PR solves #18427 (now closed) - how can I help?

**Comment by ghost** [comment]
@stutteringp0et please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/18211)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by stutteringp0et** [comment]
I have tested this item :white_check_mark: successfully on 3a1b6355e1b9a3bd48be2ba9caf1d61bac34b460<br /><br />Fields are still rendered, FieldsHelper::prepareForm is executed only once.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18211">issues.joomla.org/tracker/joomla-cms/18211</a>.</sub>

**Comment by stutteringp0et** [comment]
Done - looking forward to seeing this update in the next release.  This issue was killing a feature of an extension I'm about to release.

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 3a1b6355e1b9a3bd48be2ba9caf1d61bac34b460<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18211">issues.joomla.org/tracker/joomla-cms/18211</a>.</sub>

**Comment by stutteringp0et** [comment]
I was playing around with this, and with the patch applied - the user profile fields are still rendered, and work correctly for the most part - but when I tried a "color" type field, the value doesn't get stored.  It works for any other custom fields I create, but not the color type.  I suspect this should be raised as a separate issue - but thought I should mention it here.  When I try this on a vanilla 3.8.1 the color value is stored as expected.

**Comment by ghost** [comment]
@stutteringp0et can you please open a new Issue?

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by stutteringp0et** [comment]
Can I raise an issue based on a PR that hasn't been merged yet?

**Comment by stutteringp0et** [comment]
Scratch my report about the color field type - I went through my settings and found that I forgot to give the user permission to change the value.  Works fine now.  No need for any action.

**Comment by stutteringp0et** [comment]
@mbabker  - when will this make it into the 4.0-dev branch?

**Pull request merged**
