### PR TITLE
[4.0] - Focus password input when password is revealed

### PR DESCRIPTION
**Pull request by travisrisner**
Pull Request for Issue #27801 .

### Summary of Changes
Updated the javascript to give the password input focus when the password is revelead.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e6ce340b4bab887384a7856c09fa9f5096c039e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27821">issues.joomla.org/tracker/joomla-cms/27821</a>.</sub>

**Comment by brianteeman** [comment]
Perfect - thanks

**Comment by mothershedc** [comment]
:white_check_mark: successfully on e6ce340

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27821">issues.joomla.org/tracker/joomla-cms/27821</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27821">issues.joomla.org/tracker/joomla-cms/27821</a>.</sub>

**Pull request merged**
