### PR TITLE
[4] typos

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 831b8b93d3d094570c36dd10478a42258901ea8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34299">issues.joomla.org/tracker/joomla-cms/34299</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 831b8b93d3d094570c36dd10478a42258901ea8c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34299">issues.joomla.org/tracker/joomla-cms/34299</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34299">issues.joomla.org/tracker/joomla-cms/34299</a>.</sub>

**Comment by zero-24** [comment]
Merged

**Pull request merged**
