### PR TITLE
Add thumbsnails-media class - fixes BS 'thumbnail' class

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #13349 & #13383.

### Summary of Changes
Adds a unique class for changes in #12643, ensuring these changes only effect the media manager.

### Testing Instructions
Apply patch and check styling of any 3rd party extension using the BS 'thumbnail' class . Instance also in core #13383 (Install from Web).

### Documentation Changes Required
No

@Bakual

### CODE REVIEW

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 87105c440aee8ee819112fdfbc548364e9ff6d00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13406">issues.joomla.org/tracker/joomla-cms/13406</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 87105c440aee8ee819112fdfbc548364e9ff6d00<br /><br />Test only on "Install from Web" cause don't know, which 3rd party extensions are using the BS 'thumbnail' class.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13406">issues.joomla.org/tracker/joomla-cms/13406</a>.</sub>

**Comment by dgt41** [comment]
RTC

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13406">issues.joomla.org/tracker/joomla-cms/13406</a>.</sub>

**Comment by zero-24** [comment]
Merged. Thanks :+1:

**Pull request merged**
