### PR TITLE
Delete unnecesary catslug query from mod_related_items

### PR DESCRIPTION
**Pull request by shur**
This PR just removes part of sql request which retrieves catslug because it's not used anywhere.

There is a query part that retrieves catslug, but this catslug parameter is never used in this module and doesn't impact anything because later another catslug is created.
## How to test:

Just `print_r($item->catslug);` after [this line](https://github.com/joomla/joomla-cms/pull/8946/files#diff-41447c87f8416eb947248fc54df6cbebL182) and make sure that this parameter is still present even after we remove this part of the sql request.

### CODE REVIEW

**Comment by brianteeman** [comment]
Before patch the list of related articles is sorted in alphabetical order
After the patch the list of related articles is not

## Before
screen shot 2016-01-20 at 04 37 56

## After
screen shot 2016-01-20 at 04 38 30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8946">issues.joomla.org/joomla-cms/8946</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on d04a7ad70aa67956fb3151216a5e24fba8405941<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8946">issues.joomla.org/joomla-cms/8946</a>.</sub>

**Comment by shur** [comment]
@brianteeman I don't see such behavior in my tests.
Moreover this module doesn't have any ordering option at all.

**Comment by brianteeman** [comment]
I can only go by the screenshot

**Comment by Bakual** [comment]
The difference is because there is no ordering specified in the query, which means the results are sort of random. Changing the query may result in different ordering because MySQL does a different intern processing. So that is expected behavior.

However I don't think it's good to remove the data from the query as it may be used in template overrides. Maybe it's better to just a deprecate note so it can be removed with 4.0 safely without a potential to break something.

It was only becoming obsolete with https://github.com/joomla/joomla-cms/pull/5276, before that it was (wrongly) used to generate the URL.

**Comment by shur** [comment]
> ...which means the results are sort of random.
Exactly! That's why only screenshots are not informative. Thanks for the detailed explanation.

> However I don't think it's good to remove the data from the query as it may be used in template overrides. Maybe it's better to just a deprecate note so it can be removed with 4.0 safely without a potential to break something.
I was the one who insisted on removing catslug a while ago ( #4363 ). Yes, you are right, it can be used in template overrides. But somehow I confused the version, I thought Joomla 3.5 is the major version that is going to be without catslug.

No problem, I'll adjust this PR and add deprecated note.

**Comment by shur** [comment]
One more crazy thing in this module. There is a query part that retrieves catslug, but this catslug parameter is never used in this module and doesn't impact anything because later another catslug is  created.

That's why I deleted this part of the query.

**Comment by shur** [comment]
How to test added to description.

**Comment by shur** [comment]
Joomla 3.5 is soon to come, but this simple PR hasn't got any response for almost a month. 
I'd like to know what is the final decision - include or not in Joomla 3.5? 
Or maybe something else is needed from me?

**Comment by Bakual** [comment]
As it has no tests, it will not go into 3.5. Simple as that.

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on 83b85b816eb25b4000a887c21e94add8b032b047<br /><br />Deprecated message is added and output is unchanged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8946">issues.joomla.org/tracker/joomla-cms/8946</a>.</sub>

**Comment by Martijn-Boomsma** [comment]
I have tested this item :white_check_mark: successfully on 83b85b816eb25b4000a887c21e94add8b032b047<br /><br />I applied the patch and don't see any difference in the front-end as it shouldn't.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8946">issues.joomla.org/tracker/joomla-cms/8946</a>.</sub>

**Comment by shur** [comment]
Thanks for testing.

**Pull request merged**
