### PR TITLE
[4.0] Toolbarfix

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/28036.

### Summary of Changes
I removed the override for the `Toolbar` in Autum Template that was created in https://github.com/joomla/joomla-cms/pull/27918

In this override the filter was moved before the search int the toolbar. I hope that I not oversee something again. But I see no reason for doing this move. That is why for me the easiest solution is to delete this override.

### Testing Instructions

Please see https://github.com/joomla/joomla-cms/pull/28032 and test the view on Mobil.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 53a127173c4bc22d42753fd08904b1b424ccaaf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28046">issues.joomla.org/tracker/joomla-cms/28046</a>.</sub>

**Comment by richard67** [comment]
@astridx I think this fixes #28045 too. Is that right?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 53a127173c4bc22d42753fd08904b1b424ccaaf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28046">issues.joomla.org/tracker/joomla-cms/28046</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28046">issues.joomla.org/tracker/joomla-cms/28046</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
@richard67 we usually dont merge a pull request if we are one of the testers.

**Comment by richard67** [comment]
@brianteeman I know, but I thought in such a trivial case I can make an exception. I've double checked that it doesn't do any harm.

**Comment by brianteeman** [comment]
it's just good practice

**Comment by richard67** [comment]
I'll respect it then.

**Pull request merged**
