### PR TITLE
[4.0] Workflow-related filter fields not defined

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #24814.

### Summary of Changes

Adds missing filter fields.

### Testing Instructions

Paste this snippet in `administrator/components/com_content/tmpl/articles/default.php` or `administrator/components/com_content/tmpl/featured/default.php`:

    var_dump($this->activeFilters);

Go to articles or featured view. Under `Filter Options` filter by Condition or by Stage. Inspect the output of the code snippet.

### Expected result

Array with filter value, e.g.

    array(1) { ["condition"]=> string(1) "1" } 

### Actual result

Empty array.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by chmst** [comment]
Could you test this PR?  https://issues.joomla.org/tracker/joomla-cms/24864
It should resolve the empty filter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25183">issues.joomla.org/tracker/joomla-cms/25183</a>.</sub>

**Comment by SharkyKZ** [comment]
@chmst your PR is for `com_workflows` (and has already been merged). This one is for `com_content`.

**Comment by chmst** [comment]
oops - sry.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ed4995964dac88d17bf73fed628986d5204cc871<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25183">issues.joomla.org/tracker/joomla-cms/25183</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ed4995964dac88d17bf73fed628986d5204cc871<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25183">issues.joomla.org/tracker/joomla-cms/25183</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25183">issues.joomla.org/tracker/joomla-cms/25183</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
