### PR TITLE
Removed orphan weblinks languages

### PR DESCRIPTION
**Pull request by demis-palma**
To be merged on review.

### CODE REVIEW

**Comment by zero-24** [comment]
We can not remove them in 3.x ;) else you break amy site still using weblinks

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 3089e953171668edc3db87d483b83890c07e393a<br /><br />Done Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17199">issues.joomla.org/tracker/joomla-cms/17199</a>.</sub>

**Comment by wilsonge** [comment]
We aren't removing these in 3.x due to issues with translator workflows

**Comment by Bakual** [comment]
Just for reference: https://github.com/joomla/joomla-cms/issues/16753

**Pull request closed without merging**
