### PR TITLE
[5.0beta1] Update table columns

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
The table column selecctor is missing from com_installer&view=update

### Testing Instructions
Install the german language. This will tell you that an update is available

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c8b1d39d8a52ca7b7682edec135f96420a7d0b80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41606">issues.joomla.org/tracker/joomla-cms/41606</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Due to the branch update the human test counter has been reset. It needs to restore the tests with the “Alter test” button in the issue tracker in such a case if the brach update was clean without any conflicts. I will restore my test now, but I can’t always do that, so please try to avoid branch updates if they are not necessary when your PR has tests.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 9f948b90d5632a777a752852f7f14c89ad1b2bef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41606">issues.joomla.org/tracker/joomla-cms/41606</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41606">issues.joomla.org/tracker/joomla-cms/41606</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
