### PR TITLE
[4.0] Record number of hits description

### PR DESCRIPTION
**Pull request by brianteeman**
We really don't need to have this description as it adds nothing at all

image

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 46c83900259c525142ab0ec25473293fa242fa92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27633">issues.joomla.org/tracker/joomla-cms/27633</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 46c83900259c525142ab0ec25473293fa242fa92<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27633">issues.joomla.org/tracker/joomla-cms/27633</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27633">issues.joomla.org/tracker/joomla-cms/27633</a>.</sub>

**Comment by richard67** [comment]
@brianteeman It would have been helpful to have some info in testing instruction on where to find that field.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
