### PR TITLE
PHP 8.1 json_decode(null) deprecated when creating new Access Level

### PR DESCRIPTION
**Pull request by OctavianC**
### Testing Instructions
- Switch to PHP 8.1 and set Error Reporting to Maximum
- Go to Users > Access Levels > click New

### Actual result BEFORE applying this Pull Request
Deprecated warning showing up
image

### Expected result AFTER applying this Pull Request
No warnings
image

### CODE REVIEW

**Comment by alikon** [comment]
see #38467 too

**Comment by richard67** [comment]
So we have 2 PRs for the same issue, this one and #38467 . While this here changes `$result->rules` to an empty array when it is null, the other one leaves it as it is and just doesn't try to decode it. I'm not sure what's better, but I tend to think the other PR is better.

**Comment by nibra** [comment]
Most simple solution:

`$result->rules = json_decode($result->rules ?? '{}');`

since `$result->rules` is expected to be an array afterwards.

**Comment by HLeithner** [comment]
And non of the solutions documents why this value could be empty.

**Comment by chmst** [comment]
Good hint @HLeithner. Would you like another PR for user notes and access levels and maybe others to cure the disease, not the symptoms?

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 4be4e9d29940bb8e7a2c934088f0d11eaa65a077<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39297">issues.joomla.org/tracker/joomla-cms/39297</a>.</sub>

**Comment by joomdonation** [comment]
> And non of the solutions documents why this value could be empty.

It is null because when we create a new level, `getItem()`  method from `AdminModel` just return an  object of that item with all fields from that table set to null. For reference :

- https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_users/src/Model/LevelModel.php#L155
- https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/MVC/Model/AdminModel.php#L970
- https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Table/Table.php#L198

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4be4e9d29940bb8e7a2c934088f0d11eaa65a077<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39297">issues.joomla.org/tracker/joomla-cms/39297</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39297">issues.joomla.org/tracker/joomla-cms/39297</a>.</sub>

**Comment by fancyFranci** [comment]
Thanks, everybody

**Pull request merged**
