### PR TITLE
The sidebar arrow jumps fix

### LINKED ISSUE #5920: The sidebar arrow jumps when there is a message in com_installer
This is a very minor issue.

#### Steps to reproduce the issue
Check this video: http://www.youtube.com/watch?v=Calf4MOuhzc
If you install a component in joomla administrator you will see the effect.

The problem is that Messages div is over the rest of the contents of the page

#### Expected result
The arrow to open the menu sidebar doesn't jump after sidebar collapses

#### Actual result
The arrow to open the sidebar jumps after the sidebar collapses

### PR DESCRIPTION
**Pull request by burakcakirel**
#5920

### CODE REVIEW

**Comment by brianteeman** [comment]
Didnt appear to make any difference to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5956">issues.joomla.org/joomla-cms/5956</a>.</sub>

**Comment by burakcakirel** [comment]
It works for me. Cache, CTRL + F5 ? 
Anybody test this ?

**Comment by losedk** [comment]
tested. There are no difference

**Comment by Aeliot-Tm** [comment]
It's problem of template 'isis'. It is can be detected with a few items in a lists. For example, i have this problem regularly on my notebook with diagonal 15.6 inch on pages:
- /administrator/index.php?option=com_content
- /administrator/index.php?option=com_menus&view=items
- /administrator/index.php?option=com_akeeba&view=fsfilter

It can be fixed by edit file /administrator/templates/isis/index.php
You must add code after line 297 (after function 'processScroll'):
$win.ready(function() {
    function fixSubheadHeight(){
        if(!$nav.hasClass('subhead-fixed')){
            $nav.parent().css({'min-height':$nav.height() + 1})
        }
    }
    fixSubheadHeight();
    $win.on('resize', fixSubheadHeight)
})

It is not ideal solution, but admin-pages become much more useful.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5956">issues.joomla.org/joomla-cms/5956</a>.</sub>

**Comment by designbengel** [comment]
Seems this issue is solved by another PR ? I have a different icon in nothing is "jumping".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5956">issues.joomla.org/joomla-cms/5956</a>.</sub>

**Comment by dgt41** [comment]
This problem should be solved with https://github.com/joomla/joomla-cms/pull/7342

**Comment by dgt41** [comment]
Set to "closed" on behalf of @dgt41 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5956">issues.joomla.org/joomla-cms/5956</a>

**Comment by dgt41** [comment]
Fix with #7342<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5956">issues.joomla.org/joomla-cms/5956</a>.</sub>

**Pull request closed without merging**
