### PR TITLE
[4.0] Correct ID in ordering field

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #27514.

### Summary of Changes

Corrects `<select>` element IDs in ordering fields.

### Testing Instructions

Edit a plugin.
Inspect markup of Ordering field.

### Expected result

`<select>` element has `id="jform_ordering"`.

### Actual result

Element has `id="jformordering"`.

### Documentation Changes Required

New argument added to `JHtmlList::ordering()`.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 135cf3ba71426e0422d4773f7bc5ddfc7470bd13<br /><br />After applying PR, markup changes to correct id="jform_ordering". Also confirmed that the order field saves changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27582">issues.joomla.org/tracker/joomla-cms/27582</a>.</sub>

**Comment by Quy** [comment]
Should the number be displayed? Let's do like menus where it is not and First/Last are more obvious.

ordering

**Comment by SharkyKZ** [comment]
>Should the number be displayed?

I have no preference. But even if we change this to be like the menu field, this PR is still needed to fix the issues in the `Joomla\CMS\Form\Field\OrderingField` class, in case someone extends it.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 135cf3ba71426e0422d4773f7bc5ddfc7470bd13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27582">issues.joomla.org/tracker/joomla-cms/27582</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27582">issues.joomla.org/tracker/joomla-cms/27582</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
