### PR TITLE
[4.0] Update files and folder deletion in script.php to recent changes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This pull request (PR) adapts the lists of files and folders to be deleted on update in `script.php` to recent changes:
- Add files being removed from builds which results from PR #34191 - the `/libraries/vendor/bin` folder will not be deleted because it might contain other files added by the site admin.
- Add the 3.9.x update SQL scripts which come from PR #33212 .
- Remove deletion of the `/bin` folder for the same reasons as it is with the `/libraries/vendor/bin` folder.

### Testing Instructions

Code review.

### Actual result BEFORE applying this Pull Request

Files which have been removed with PR #34191 in the 4.0-dev branch and the update SQL scripts "3.9.27-2021-04-20.sql" which have been added to staging by PR #33212 are not removed on update if they are present.

### Expected result AFTER applying this Pull Request

Files which have been removed with PR #34191 in the 4.0-dev branch and the update SQL scripts "3.9.27-2021-04-20.sql" which have been added to staging by PR #33212 are removed on update if they are present.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by wilsonge** [comment]
> The tool from PR #25559 used to create the lists adds folder /libraries/vendor/bin because that folder is removed from the builds since PR #34191 has been merged.

bin folder indeed should be removed - we don't really want to be dealing with the symlinks on different installs. Plus tbh just outright not sure for security we want to come close to exposing these binaries anyhow.

> That was right for those which have been released before, but the ones which were added after the last Beta 7 don't need to be in the list because we don't support updates between or from nightly builds.

This is correct. Don't bother adding them. In the grand scheme of things it really won't matter.

**Comment by richard67** [comment]
~~Not sure if we can delete the "bin" folder if it contains links which are not removed before by the script because they are not part of any package. I have to test that. See also issue #34298 .~~

Update: Sorry, was mixing up "bin" with "libraries/vendor/bin". All ok.

**Comment by brianteeman** [comment]
the question on #34290 is still valid even if you were thinking of the wrong folder

**Comment by richard67** [comment]
> the question on #34290 is still valid even if you were thinking of the wrong folder

@brianteeman That's right. It's just nothing I should change with this PR here.

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks too, especially to the testers 😆

**Pull request merged**
