### PR TITLE
Filter for special characters that fail sending test mail

### PR DESCRIPTION
**Pull request by magnussinger**
Pull Request for Issue #41061.

### Summary of Changes
When trying to send a test mail from the backend, it now filters the site name so the sending does succeed.

### Testing Instructions
Enter a site name containing "@" and/or "|" and try to send a test mail

### Actual result BEFORE applying this Pull Request
The mail could not be sent

### Expected result AFTER applying this Pull Request
The mail can be sent

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by formfranska** [comment]
I have tested this item :white_check_mark: successfully on 90f94a6aa3a5efdaf56de72b8ab1b5c479fcb1f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41469">issues.joomla.org/tracker/joomla-cms/41469</a>.</sub>

**Comment by brianteeman** [comment]
This should contain some comments in the code so that in the future someone will know why the preg_filter has been added

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 90f94a6aa3a5efdaf56de72b8ab1b5c479fcb1f0<br /><br />on 4.3.4 - the patch works however i could not reproduce the issue on my system: My sitename is Test|PR@Infotech
before: 
Test mail from Test|PR@Infotech (Subject works,  all send methods)
after:
Test mail from TestPRInfotech ( | and @ are stripped in the subject for all send methods)

but anyway it just in the testmail...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41469">issues.joomla.org/tracker/joomla-cms/41469</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41469">issues.joomla.org/tracker/joomla-cms/41469</a>.</sub>

**Comment by MagnusSinger** [comment]
> This should contain some comments in the code so that in the future someone will know why the preg_filter has been added

@brianteeman I added a comment to the file

**Comment by obuisard** [comment]
Thank you Magnus @MagnusSinger for the PR!

**Comment by laoneo** [comment]
This here breaks the system tests on 4.4 as the site name is always null when none of these special characters are in the string. You can test it here https://onlinephp.io?s=s7EvyCjg5SpLLIpPKc0t0CgoSk2PT8vMKUkt0ohW13fQV9dRUNePqdFXjwUyQJyQ1OISIK1rqKlpDQA%2C&v=8.2.10

**Pull request merged**
