### PR TITLE
[4.2] Fix class name in uri test

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #37606.

### Summary of Changes
Adapts the class name of the uri test.

### Testing Instructions
Run composer install

### Actual result BEFORE applying this Pull Request
It shows the warning:
_Class Joomla\Tests\Unit\Libraries\Cms\Uri\JUriTest located in ./tests/Unit/Libraries/Cms/Uri/UriTest.php does not comply with psr-4 autoloading standard. Skipping._

### Expected result AFTER applying this Pull Request
Runs through.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fe1f0a0780a3aa17eaf92f01ea4f22d2beeb0c40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37632">issues.joomla.org/tracker/joomla-cms/37632</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fe1f0a0780a3aa17eaf92f01ea4f22d2beeb0c40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37632">issues.joomla.org/tracker/joomla-cms/37632</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37632">issues.joomla.org/tracker/joomla-cms/37632</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
