### PR TITLE
More useful message when "Force HTTPS" config save fails (because of HTTPS config issues)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Since the current global config "Force HTTPS" warning message doesn't say much to user, this PR makes the message show the real problem.
### Testing Instructions
- Use latest staging
- In a server with SSL config issues try to save joomla config as Forced HTTPS
- You will get a warning message like this

image
- Now apply this patch and test again. you will get a more useful warning message that says why the problem exists

image
### Documentation Changes Required

None.

@brianteeman please check

### CODE REVIEW

**Comment by conconnl** [comment]
@andrepereiradasilva any ideas on creating config issues for HTTPS :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12465">issues.joomla.org/tracker/joomla-cms/12465</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@conconnl didn't understand your question

**Comment by conconnl** [comment]
@andrepereiradasilva to be able to test this PR, you need a server with SSL configuration issues.
Any idea how to create those issues ❓

**Comment by andrepereiradasilva** [comment]
To create an issue do this:
- Go to https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/application.php#L137 and set this to `CURLOPT_PROXY => 'nohost.local',`
- Now try to change the site config to Force HTTPS
- It will fail

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 93fd030ff87fb8eeece26363a04c0d4ec9ed5fbe<br /><br />Tested successfully.
The test instructions in the last message are the easiest way to create a not working HTTPS situation to be able to see the error message.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12465">issues.joomla.org/tracker/joomla-cms/12465</a>.</sub>

**Comment by MartijnMaandag** [comment]
I have tested this item :white_check_mark: successfully on 93fd030ff87fb8eeece26363a04c0d4ec9ed5fbe<br /><br />Tested on Localhost:
Message: 
HTTPS has not been enabled as it is not available on this server. HTTPS connection test failed with the following error: Failed to connect to localhost port 443: Connection refused<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12465">issues.joomla.org/tracker/joomla-cms/12465</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12465">issues.joomla.org/tracker/joomla-cms/12465</a>.</sub>

**Pull request merged**
