### PR TITLE
[4.0] Remove inputbox class from forms

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Simple PR to remove unused `inputbox` class from XML forms.

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ed3668315e697f695ae5729c46f24574a945a3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26182">issues.joomla.org/tracker/joomla-cms/26182</a>.</sub>

**Comment by brianteeman** [comment]
Not sure about removing it from the frontend

**Comment by N6REJ** [comment]
removing from front end, imo, will require man template dev's to create a custom form(s). as it's not uncommon to want to style the design of input boxes

**Comment by SharkyKZ** [comment]
This class is placed on a few random fields and serves no real purpose.

**Comment by wilsonge** [comment]
Agree with @SharkyKZ - if it was used consistently there'd be a definitely case for frontend template developers. But it's only used on a very small number of fields so best be consistent I think

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
