### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Piyussshh**
Pull Request for Issue # .

### CODE REVIEW

**Comment by richard67** [comment]
@Piyussshh Please fill in the missing information in the description of your pull request, i.e. add the necessary text below the headings "Summary of Changes", "Testing Instructions" and so on. We don't have these headings without reason in our template for new pull requests.

And please give your pull request a meaningful title.

Finally, at the top of the description of your pull request you can see a line "Pull Request for Issue # .". Please complete the issue number so people know which issue your pull request shall solve. I assume it's issue #32929 , but that's just my guess.

Thanks in advance.

**Comment by brianteeman** [comment]
Just close it. It refers to an issue of mine but its nt the correct solution and its to the wrong branch

**Comment by richard67** [comment]
@brianteeman Ouch ... I did not notice the wrong branch. I need more coffee (or better one).

**Comment by richard67** [comment]
@Piyussshh Thank you for your contribution. Unfortunately it is wrong because:
1. Your pull request (PR) is made for the staging branch, but there the files exist where they should be. The issue was for the 4.0-dev branch.
2. In the comments in issue #32929 you can see that the problem is not the files missing, it's the (S)CSS to be removed.

Please don't be disappointed. It can happen that a PR is wrong. Happened to me too once.

**Comment by brianteeman** [comment]
@richard67 the images are also a mix of formats, completely the wrong size and sourced from ???

**Comment by richard67** [comment]
Yes, that too.

**Pull request closed without merging**
