### PR TITLE
Moving "afterDisplayTitle" after the article title

### PR DESCRIPTION
**Pull request by Bakual**
Currently the "After Title" position for fields is misleading as it is actually the exact same place as "Before Display". The only difference is that "After Title" is wrapped into a conditional which checks if "Show Intro" is disabled. Which is confusing as well since the position actually has no ties to the intro text.

### Summary of Changes
This moves the position up after the title and before the info block and removes the conditional.

### Testing Instructions
* Create a field and set it to display "After Title". Assign some value to that field in the article.
* Check in frontend the featured view, blog view and article view.

### Expected result
Field appears after the title

### Actual result
Field appears (if "Show Intro" is disabled) after the info block, right where the fields from "Before Display" appear as well.

### Documentation Changes Required
Not sure.

#### B/C Note
This is not strictly B/C since the fields (and other plugin content using that event) may appear in a different place. Or even appear now when they didn't before (due to param). However this change is only for the Protostar and Beez template and templates that don't override this views. 3rd party templates with overrides to those views will not be affected at all.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f6be2f25d0d5ec6187a14eb0f10050ab238d7c3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15639">issues.joomla.org/tracker/joomla-cms/15639</a>.</sub>

**Comment by AlexRed** [comment]
Is it only for com_content?  or also for com_users and com_contact etc.. ?

**Comment by Bakual** [comment]
This PR only deals with com_content.
I haven't looked yet at how com_users and com_contact behave in this case. If the same issue exists there I can expand this PR.

**Comment by laoneo** [comment]
Com_users don't have that events at all. Com_contact has them.

**Comment by AlexRed** [comment]
yes, Com_users don't have that events at all but have the parameter  :(
Also for Com_contact "Mail" i think don't have that events at all but have the parameter

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on f6be2f25d0d5ec6187a14eb0f10050ab238d7c3b<br /><br />Thank you for this PR! The position of the fields makes more sense in this way. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15639">issues.joomla.org/tracker/joomla-cms/15639</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by Bakual** [comment]
> Com_users don't have that events at all but have the parameter

The parameter is hardcoded. Com_fields has no knowledge about the implementation of the respective extension. So until someone writes code to change that, we will have to live with it.

> Also for Com_contact "Mail" I think don't have that events at all but have the parameter

Same case here for the mail. The events aren't triggered for the contact form. The whole form is done different.
The contact itself imho looks fine.

**Comment by AlexRed** [comment]
So until someone writes code to fix it, can we write in the parameter it is not to use on com_users and com_contact "Mail" ? 
We need to inform the Joomla users about it

**Comment by mbabker** [comment]
No.  The issue is not unique to these core components.  Any extension integrating com_fields support and not having these event triggers have the same problem.

The best you can do for a tooltip is to note that the parameter requires the extension to support its options and not create an explicit list of supported or unsupported configurations.

**Comment by AlexRed** [comment]
my english is very very bad....  but if nobody can edit the tooltip I can try  :(

**Comment by Bakual** [comment]
The english from @brianteeman is a bit better, maybe he can help here 😄

**Pull request merged**
