### PR TITLE
[com_fields] Filters for text, textarea and editor field

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #14359.

### Summary of Changes
Add more filter options to the text, textarea and editor field. The hardcoded filters for the textarea and editor are removed, but set as default.

### Testing Instructions
- Create a textarea field and set an integer filter
- Edit an article and put into the field letters and numbers

### Expected result
After save the value of the field in the article should only be the integers.

### Actual result
Only some HTML filtering is done.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a2fbbfeb2a1ccd0611bc5ef7d75835b9e36cb54a<br /><br />In Text Area-Field value "asdf1234" is saved as "1234"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14403">issues.joomla.org/tracker/joomla-cms/14403</a>.</sub>

**Comment by zero-24** [comment]
FYI @laoneo i have just fixed the XMLs ;)

**Comment by laoneo** [comment]
Thanks!

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 30a74c2cc115644ff382a00cd9e6e77ebc119a19<br /><br />Thank you Allon, works !!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14403">issues.joomla.org/tracker/joomla-cms/14403</a>.</sub>

**Comment by laoneo** [comment]
Also RTC.

**Comment by laoneo** [comment]
Just resolved the merge conflict, so still available for RTC.

**Comment by franz-wohlkoenig** [comment]
test again, @laoneo?

**Comment by laoneo** [comment]
@franz-wohlkoenig yes please or we can set it directly to RTC as there are two tests, only merge conflicts and CS commits are done.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7e8711f36bafde97777ee57ec052e58afa5caa02<br /><br />On Text, Textfield and Editor "asdf1234" is after `Save` of Article changed to "1234".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14403">issues.joomla.org/tracker/joomla-cms/14403</a>.</sub>

**Comment by zero-24** [comment]
@rdeutz please take the final decision here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14403">issues.joomla.org/tracker/joomla-cms/14403</a>.</sub>

**Comment by infograf768** [comment]
@laoneo 

Please see https://github.com/joomla/joomla-cms/issues/18566#issuecomment-660659941

**Pull request merged**
