### PR TITLE
[4.0] RTL: Fixing template tree

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Overriding _treeselect.scss by adding RTL specific css

### Testing Instructions
Display Cassiopea template edit using Persian language or setting en-GB.xml to rtl

### Before patch
treertlbefore

### After patch
Screen Shot 2019-09-21 at 12 01 42

### CODE REVIEW

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on d0550e15a212b055175abe77379e5c5c6e79d2e7<br /><br />Works as advertised. Changed language to Persian, applied the patch and the tree view looks way better now. 
(Note that I don't speak Persian or other RTL languages, so this comment is based on my assumption how I think it makes sense)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26367">issues.joomla.org/tracker/joomla-cms/26367</a>.</sub>

**Comment by infograf768** [comment]
@richard67 
can you also test this one?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d0550e15a212b055175abe77379e5c5c6e79d2e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26367">issues.joomla.org/tracker/joomla-cms/26367</a>.</sub>

**Comment by infograf768** [comment]
rtc
thNks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26367">issues.joomla.org/tracker/joomla-cms/26367</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
