### PR TITLE
[4.0] TinyMCE Editor-xtd image button

### PR DESCRIPTION
**Pull request by brianteeman**
Remove code putting the image editor button on a new line

PR for #18860

NOTE: This entire file needs refactoring

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5972f435a68babb88befda769163350d0a81f0d4

Image-Button is now in same Row as other Buttons:

bildschirmfoto 2018-01-08 um 16 18 33

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19334">issues.joomla.org/tracker/joomla-cms/19334</a>.</sub>

**Comment by dgrammatiko** [comment]
Do you still have the xtd-media working?

**Comment by dgrammatiko** [comment]
Actually this PR is wrong. You are removing the native TinyMCE plugin and we fall back to the old code!
The idea was to have all the core buttons as native tinyMCE buttons (on a dropdown), so this PR reverts all that

**Comment by brianteeman** [comment]
sorry you are wrong. in #10000 we removed the native plugin when this  xtd-image was loaded. 
This pr still loads the xtd-image NOT the native tinymce

But as i said in the OP the entire script needs to be reviewed as the changes made to it here in j4 are all wrong

**Comment by brianteeman** [comment]
> The idea was to have all the core buttons as native tinyMCE buttons (on a dropdown), so this PR reverts all that

A PR cannot revert a non-implemented idea. Thats why code should never be merged until it is completed - wastes so much of everyones time!!!!!

**Comment by dgrammatiko** [comment]
@brianteeman you are confused: xtd-image is **now** native tinyMCE plugin! With this PR we're are removing that and we fall back to the buggy PHP rendered javascript thing of the dark days! Read the code: it loads a script path, follow that path and read the file, that's the native tinyMCE plugin I wrote and with this PR you're removing it!

**Comment by brianteeman** [comment]
ok i give up trying to fix your bugs then - do it yourself

**Comment by dgrammatiko** [comment]
Brian, sorry for being thick here but you have to consider couple things that are in the todo list here:
- the design team is asking for a specific template for tiny
- the Js team is having a hard time already trying to deliver all kind of requested changes

That was the reason I marked it as known problem on the initial issue and also the reason I didn’t try to post some code. It’s on the todo list but will happen only after we have an agreement on the final design for tiny. Again sorry to waste your time here

**Comment by brianteeman** [comment]
if ypu can just stop it being on a new line then its ok and you can convert the others at your leisure. but please also bring back the ability to use the native tinymce plugin for images if for some reason the user doesnt enable the plugin and prefers the tinymce option.

**Pull request closed without merging**
