### PR TITLE
PostgreSQL - SQL error when add new tag

### LINKED ISSUE #6104: Postgresql: tags created on the fly are not saved
On a postgresql installation: go to the article manager and create a new article or edit an existing article. In the tags field create a tag on the fly or in other words don´t select an existing tag but put in a new tag. Then hit the "Save". The tag field will be cleared. When you pressed "Save & Close" the tag field will be cleared and the article mask will not be closed.

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

go to the article manager and create a new article or edit an existing article In the tags field create a tag on the fly or in other words don´t select an existing tag but put in a new tag. Then hit the "Save".
#### Expected result

The article is saved with the new added tag
#### Actual result

the tag field is cleared and the article is not saved
#### System information

PostgreSQL 9.3.5
Joomla 3.4.0
#### Additional comments

As suggested added a sanity check for NOT NULL FIELDS
fix #6104

### CODE REVIEW

**Comment by waader** [comment]
@alikon Please try the following:

- Add a new article with a title and fill in a new tag (= adhoc tag), then save. The article is saved.
- Repeate the above step. You get the error message: 

Save failed with the following error: SQL=INSERT INTO udzse_contentitem_tag_map

Another test case: 
- Add to an existing article two or more tags: only the first tag is saved.

Under mssql to get the following error when you try to add a new tag to an existing article:

Save failed with the following error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Error converting data type varchar to bigint.SQL=INSERT INTO [ufv5y_tags] ([parent_id],[level],[lft],[rgt],[alias],[path],[title],[note],[published],[checked_out],[checked_out_time],[access],[params],[metadesc],[metakey],[metadata],[created_user_id],[created_time],[created_by_alias],[modified_user_id],[modified_time],[images],[urls],[hits],[language],[version],[publish_up],[publish_down]) VALUES ('1','1','17','18','2015-03-05-20-25-47','2015-03-05-20-25-47','Stiege','('''')','1','((0))','2015-03-05 20:25:47','1','{}',' ',' ','{}','((0))','2015-03-05 20:25:47','('''')','((0))','2015-03-05 20:25:47','{}','{}','((0))','*','((1))','2015-03-05 20:25:47','2015-03-05 20:25:47')

**Comment by alikon** [comment]
@waader 
i'm experiencing the same issues on postgresql  
where the driver return a bad default value for fields of type (TEXT, CHARACTER VARYING) declared NOT NULL WITH DEFAULT , for postgresql i have a fix , 
i guess for MSSQL  the same reason
if you can help me on sqlsrv runnnig this query and report back the results
```
	SELECT column_name as Field, data_type as Type, is_nullable as \'Null\', column_default as \'Default\'
           FROM information_schema.columns WHERE table_name = #__tags
```

maybe i will able to find a fix to mssql too

**Comment by waader** [comment]
@alikon I modified your sql slightly to 

SELECT column_name as Field, data_type as Type, is_nullable as 'Null', column_default as 'Default'
           FROM information_schema.columns WHERE table_name = 'aqmag_tags'

and this gives the following back:

id	bigint	NO	NULL
parent_id	bigint	NO	((0))
lft	int	NO	((0))
rgt	int	NO	((0))
level	bigint	NO	((0))
path	nvarchar	NO	('')
title	nvarchar	NO	NULL
alias	nvarchar	NO	('')
note	nvarchar	NO	('')
description	nvarchar	NO	NULL
published	smallint	NO	((0))
checked_out	bigint	NO	((0))
checked_out_time	datetime	NO	('1900-01-01T00:00:00.000')
access	bigint	NO	((0))
params	nvarchar	NO	NULL
metadesc	nvarchar	NO	NULL
metakey	nvarchar	NO	NULL
metadata	nvarchar	NO	NULL
created_user_id	bigint	NO	((0))
created_time	datetime	NO	('1900-01-01T00:00:00.000')
created_by_alias	nvarchar	NO	('')
modified_user_id	bigint	NO	((0))
modified_time	datetime	NO	('1900-01-01T00:00:00.000')
images	nvarchar	NO	NULL
urls	nvarchar	NO	NULL
hits	bigint	NO	((0))
language	nvarchar	NO	NULL
version	bigint	NO	((1))
publish_up	datetime	NO	('1900-01-01T00:00:00.000')
publish_down	datetime	NO	('1900-01-01T00:00:00.000')

**Comment by alikon** [comment]
@waader can you send the results in a more viewable (tabular/matrix) way even with  screenshot I'm not sure I've fully understand the results

**Comment by waader** [comment]
Of course:
j33_sql_tag

**Comment by alikon** [comment]
Thx now is clear, let me prepare a fix.....

**Comment by alikon** [comment]
@waader
i'm not so confident with mssql is more diffcult blind code

**Comment by waader** [comment]
@test works much better now, but there is one case I would like you to try:

- add a new article and add three tags on the fly: test1, test2, test3
- then hit save
- only test1 gets saved
- it is possible now to add further tags, but no more than one at a time

**Comment by alikon** [comment]
@waader 
should be fixed now i've tested with 7 tags
can you confirm

**Comment by waader** [comment]
@alikon works fine with postgresql now. Mssql is another chapter and not in the scope of this pr. Thanks!

**Comment by brianteeman** [comment]
Confirmed issue
Confirmed PR resolved it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6314">issues.joomla.org/joomla-cms/6314</a>.</sub>

**Comment by brianteeman** [comment]
Two tests setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6314">issues.joomla.org/joomla-cms/6314</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @alikon! Merged.

**Pull request closed without merging**
