### PR TITLE
Compatibility with the JURI::isInternal() hardening

### PR DESCRIPTION
**Pull request by PhilETaylor**
see: #8689 - all explained there.

### CODE REVIEW

**Comment by infograf768** [comment]
This will work if `false` is taken off as base64_encode accepts only one argument.
```
-				$item->link->setVar('return', base64_encode(JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language), false)));
+				$item->link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language), false));
```
should be
```
-				$item->link->setVar('return', base64_encode(JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language), false)));
+				$item->link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language)));
```

Can you redo?

**Comment by infograf768** [comment]
@PhilETaylor 
@mbabker 
Please look into this as, for me, it would solve https://github.com/joomla/joomla-cms/issues/9846

I worry about people having used overrides, thus why I am thinking there could be a better solution.

**Comment by joomdonation** [comment]
@infograf768 The change you suggested is correct (I think it is a typo from @PhilETaylor code). If we could not fix the issue with JUri::isInternal(), we should make this change to fix the bug.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8698">issues.joomla.org/joomla-cms/8698</a>

**Comment by infograf768** [comment]
Closed as typos and misses a change in Beez. Replaced by https://github.com/joomla/joomla-cms/issues/9959<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8698">issues.joomla.org/joomla-cms/8698</a>.</sub>

**Pull request closed without merging**
