### PR TITLE
Use correct language in search tooltip

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #28590.

### Summary of Changes
Use the correct search tooltip.

### Testing Instructions
Go to Extensions -> Languages -> Overrides
Put cursor over Search field.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cdc6cf24fda50d2498713676214a8a89c0e60b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28598">issues.joomla.org/tracker/joomla-cms/28598</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cdc6cf24fda50d2498713676214a8a89c0e60b27<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28598">issues.joomla.org/tracker/joomla-cms/28598</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28598">issues.joomla.org/tracker/joomla-cms/28598</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
