### PR TITLE
[com_languages] submenu changes

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
##### Description

With the change from https://github.com/joomla/joomla-cms/pull/9101 doesn't make much sense for the languages submenu to have two entries for Installed languages.

This PR, merges them in one submenu option and also adds a submenu in the global admin menu (like exists for extensions).
###### After PR

image

image
##### How to test
1. Install latest joomla staging
2. Apply this patch
3. Check language submenu is working properly

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry typing this from my phone so can't check but please make sure you can
still switch between site and admin languages from a mobile device. You
can't for modules and this looks like it "might" have the same problem.

**Comment by andrepereiradasilva** [comment]
good point, will check that

**Comment by andrepereiradasilva** [comment]
@brianteeman done https://github.com/joomla/joomla-cms/commit/270add5a841ba4df8ce0420d7a56f2ba86752cf3

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
For reference on the modules see #9031

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 19ec4c48c947d4cdbc10f56bf5b726e84ad9d0ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by sandstorm871** [comment]
I have tested this item :red_circle: unsuccessfully on 19ec4c48c947d4cdbc10f56bf5b726e84ad9d0ea<br /><br />Tried to install PR from #9101 first as advised, but then I couldn't install this PR as I got an error saying it conflicts with PR #9101.
So I just installed this PR #9102 , which shows the pop out menu for the language sub menus, but clicking on any of the links produces a 500 Error **"JForm::getInstance could not load file"**
Tested with J3.5 beta2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by brianteeman** [comment]
@sandstorm871 because of the way that patchtester component works it wont be possible to do that. I am resetting your test result to untested <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
Yes, you have to merge these 2 PRs manually. But then everything works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
Just apply the patch for PR #9101, then download the changed files from PR #9102 and manually drop then into your installation (e.g. via ftp), then everything should work well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
To be more precise: For those files from PR #9102 which have merge conflicts with PR #9101, replace the file from PR #9101 by the one from PR #9102.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by sandstorm871** [comment]
@richard67 Thanks, Just testing that now :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by sandstorm871** [comment]
At the chance of making myself look daft (Its not hard) , How do I **_then download the changed files from PR #9102_** 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
@sandstorm871 After having applied PR #9101, you go to [PR #9102 on GitHub, list of changed files](https://github.com/joomla/joomla-cms/pull/9102/files), and then **for each of these 5 files**:

1. Open the changed file by clicking the "View" button.
2. Then in the open file view click the "Raw" button.
3. Then use your browser's "Save as" function to save the file within the Joomla installation which you use for testing, into the same subdirectory as shown within the path in the list of changed files of the PR on GitHub.

If your test site is not on your local PC, save the files locally and then copy them with ftp or so up to your host.

I hope this information helps.

**Comment by sandstorm871** [comment]
Ah OK, I'm not too daft then. That's how I was doing it.
I just thought I may have been missing a button somewhere to download, all the modified files :)

**Comment by andrepereiradasilva** [comment]
conflicts fixed. Test instructions now simplified.

@infograf768, could you also test  that this brings no issue to your latest changes?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6e188d536be5c0366b770581af9feae149e67e38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6e188d536be5c0366b770581af9feae149e67e38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by infograf768** [comment]
No problem here. All fine.

**Comment by andrepereiradasilva** [comment]
mantainers don't merge this. A way to choose the client in hathor is needed too.
I will check when i have time.

**Comment by andrepereiradasilva** [comment]
ok, now we can also choose the client in hathor

**Comment by richard67** [comment]
@wilsonge  Ah, and again regarding my else clause you mentioned: I still think we should handle the combined drop and add of the indexes in this way that we do not check for the drop, because the index should exist after this statement. If we would check for the drop we could not use the details for the index from the actual data because this is the one we for sure not will have dropped (because it's the one later created). We have no chance to find out which were the details of something dropped without having initial database status and goint through all the history of the update files again, but we don't have this initial status.

The only reason why this fails now is that we only check if the index has been added, but not for the details from the update query (columns and their subpart lengths). As soon as we have this, it will work, and the schema manager will try to execute again the combined statemet (drop and add).

So I still think it is enough to check for the add part statement of such a combined statement, and so never go into this else. This else is only for those drop statements where no add iss appended, and there we still can live with the old situation that if we once dropped an index we should never add it back with the same name in anther statement. But for the combined statments it works as soon as we check for the details, too.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
AAAAAHHH COMMENTED WRONG PR!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5c4ce032a83615c9d81954bd44777001fa5a6f7f<br /><br />Works as with my previous test for Isis plus now for Hathor, too (new dropdown plus submitt button).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by infograf768** [comment]
Negative here. Patch does not apply. It has conflict.
error: patch failed: administrator/components/com_languages/views/installed/view.html.php:18
error: administrator/components/com_languages/views/installed/view.html.php: patch does not apply
error: patch failed: administrator/language/en-GB/en-GB.com_languages.ini:46
error: administrator/language/en-GB/en-GB.com_languages.ini: patch does not apply
error: patch failed: administrator/components/com_languages/helpers/languages.php:23
error: administrator/components/com_languages/helpers/languages.php: patch does not apply
error: patch failed: administrator/templates/hathor/html/com_languages/installed/default.php:14
error: administrator/templates/hathor/html/com_languages/installed/default.php: patch does not apply
error: patch failed: administrator/templates/hathor/html/com_languages/installed/default.php:33
error: administrator/templates/hathor/html/com_languages/installed/default.php: patch does not apply

**Comment by brianteeman** [comment]
@infograf768 thats strange - github reports that there are no conflicts

**Comment by infograf768** [comment]
I also get the conflict (for administrator/templates/hathor/html/com_languages/installed/default.php) when using eclipse.

**Comment by richard67** [comment]
Also here all was fine. Used staging with state as of yesterday afternoon, applied the patch and all was fine. Since yesterday afternoon was no commit on staging for the files treated by this PR.

**Comment by infograf768** [comment]
SInce then was merged: https://github.com/joomla/joomla-cms/pull/9190 which modified hathor

**Comment by richard67** [comment]
@infograf768 Ahhhhhhh ... you are right, and I am blind!

So either you change your nick name into "eagleEye768", or I change mine into "blindMole67" :smile: 

But why the hell it is not shown on GitHub for the PR that there might be conflicts?

**Comment by andrepereiradasilva** [comment]
hum ... strange i will check that later.

**Comment by wilsonge** [comment]
Because if the file modifications are exactly the same then you can't apply the patch/diff but you can merge (as the lines are the same)

**Comment by andrepereiradasilva** [comment]
should be ok for tests now.

**Comment by infograf768** [comment]
It works, but I am not sure I like the sidebar containing only Installed.
It was much easier to see which client was displayed imho with:
screen shot 2016-02-26 at 09 03 27


Another solution would be to use
```
if ($this->state->get('client_id', 0) == 1)
		{
			JToolbarHelper::title(JText::_('COM_LANGUAGES_VIEW_INSTALLED_ADMIN_TITLE'), 'comments-2 langmanager');
		}
		else
		{
			JToolbarHelper::title(JText::_('COM_LANGUAGES_VIEW_INSTALLED_SITE_TITLE'), 'comments-2 langmanager');
		}
```
with the new strings:
```
COM_LANGUAGES_VIEW_INSTALLED_ADMIN_TITLE="Languages: Installed - Administrator"
COM_LANGUAGES_VIEW_INSTALLED_SITE_TITLE="Languages: Installed - Site"
```

to get in the toolbar title:
screen shot 2016-02-26 at 09 11 54

and
screen shot 2016-02-26 at 09 12 11

**Comment by infograf768** [comment]
This would be consistent with the proposed PR here for Modules:
https://github.com/joomla/joomla-cms/pull/9218
Please also test that one.

**Comment by andrepereiradasilva** [comment]
ok ticle now changes, please test.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on aabe015c622711535221e0a5a6426bd78caeba9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on aabe015c622711535221e0a5a6426bd78caeba9d<br /><br />Not sure we absolutely need here `(int)` and `===`, but as it creates no issue. Works fine for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva  Sorry, I could not help with testing, have no usable test system right now, all messed up by failed utf8mb4 tests. Good that Brian and JM already have tested, thanks to both.

**Comment by andrepereiradasilva** [comment]
@richard67 i know you are with another task now ;)

**Comment by infograf768** [comment]
@wilsonge this can go in imho. thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9102">issues.joomla.org/joomla-cms/9102</a>.</sub>

**Pull request merged**
