### PR TITLE
[4.0] pre-update check unused class

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to remove a class that doesn't exist in the css stylesheet

No visible changes obviously

Code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1eabb2be71c7b8c208dc88664c4dbe0f6d2038ec<br /><br />I've verified that "text-left" doesn't appear in any scss or any relevant css file and that removing it doesn's cause any visual change.

Hint for other testers: You can get the pre-update check shown in a Joomla 4.0 by changing the update channel to use the custom URL https://update.joomla.org/core/nightlies/next_minor_list.xml . You will be offered to update to 4.1 and the checks are shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36077">issues.joomla.org/tracker/joomla-cms/36077</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on 1eabb2be71c7b8c208dc88664c4dbe0f6d2038ec<br /><br />The class "text-left" is not present in any of the CSS or SCSS file<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36077">issues.joomla.org/tracker/joomla-cms/36077</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36077">issues.joomla.org/tracker/joomla-cms/36077</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 1eabb2be71c7b8c208dc88664c4dbe0f6d2038ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36077">issues.joomla.org/tracker/joomla-cms/36077</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
