### PR TITLE
[4.0] Fix tooltip for disabled grid button

### PR DESCRIPTION
**Pull request by schnuti**
Pull Request for Issue # .

### Summary of Changes

Fix tooltip for disabled grid button

### Testing Instructions
In a backend list e.g. article list. (in your single user test system)

    checkout an article as a first user = an edit article.
    leave the editing by clicking the browsers back button.
    The checked-out button shows a tool tip on hover - DO NOT CLICK IT!
    Log out as first user - log in as another user. This user must not be allowed to check in records.
    (user group setting in com.checkin -> not allowed)
    Go to the list (articles)
    Hover the checked-out button.

Quick-test: change $canCheckin to false in line 262 tmpl/articles/deafult.php
editor, $item->checked_out_time, 'articles.', $canCheckin); ?> 

joomla-bug-is

### Expected result

joomla-bug-should

### Actual result
see above

### Documentation Changes Required
No

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bb6009fc8893169c76ad086529cc6da5c76146a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26451">issues.joomla.org/tracker/joomla-cms/26451</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bb6009fc8893169c76ad086529cc6da5c76146a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26451">issues.joomla.org/tracker/joomla-cms/26451</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26451">issues.joomla.org/tracker/joomla-cms/26451</a>.</sub>

**Comment by blueforce** [comment]
I have tested this item :white_check_mark: successfully on bb6009fc8893169c76ad086529cc6da5c76146a0<br /><br />work for me as described..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26451">issues.joomla.org/tracker/joomla-cms/26451</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
