### PR TITLE
[4.0] Migrate com_menus to services

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #20487.

Moves com_menus to the service based extension setup. Additionally it makes extensions work which do route their views completely to the back end.

See #20217 for details.

### CODE REVIEW

**Comment by infograf768** [comment]
Very hard to test this as git apply does not work with it.
After trying some stuff (renaming and moving some files, I do get
 `0 Class 'Joomla\Component\Menus\Administrator\Helper\JTable' not found' when selecting menu items associations in com_associations

Not sure this is related to the PR as I may have been wrong in applying the patch

**Comment by infograf768** [comment]
Looks also like we still have a call to `MenusHtml` line 248 of `/administrator/components/com_menus/tmpl/items/default.php`
it should be
`<?php echo JHtml::_('menus.association', $item->id); ?>`

**Comment by zero-24** [comment]
Can you please update the since tags to deploy Version?

**Comment by laoneo** [comment]
@infograf768 fixed the issues.

**Comment by infograf768** [comment]
@laoneo 
git apply still does not work with this PR.
As it is quite a job to apply this patch with eclipse (it does not rename and move files around and does not create new folders), could you give a link to your branch for us to download, install and test? I could not find the Digital-Peak:j4/service/menus branch.

**Comment by laoneo** [comment]
Here we go https://github.com/Digital-Peak/joomla-cms/tree/j4/service/menus

**Comment by infograf768** [comment]
I do not have the errors I remarked before. Menu items associations look like working fine too.

**Comment by laoneo** [comment]
So can we mark it as successful?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e5eb5073a92ef9f6e351aa6a9468a314e29a4e44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20704">issues.joomla.org/tracker/joomla-cms/20704</a>.</sub>

**Comment by wilsonge** [comment]
Nice one! Thanks :)

**Pull request merged**
