### PR TITLE
[4] remove redundant sessions folder in installation

### PR DESCRIPTION
**Pull request by PhilETaylor**
Core review

This folder is never used. Therefore it doesnt need to exist.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 67617a9964098d7fffb36095962369a7732dd102<br /><br />doesnt remove the folder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35140">issues.joomla.org/tracker/joomla-cms/35140</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 67617a9964098d7fffb36095962369a7732dd102<br /><br />doesnt remove the folder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35140">issues.joomla.org/tracker/joomla-cms/35140</a>.</sub>

**Comment by PhilETaylor** [comment]
Well you believe what you want to believe. This PR meets its aims as evidenced by the missing folder in the correct branch. https://github.com/PhilETaylor/joomla-cms/tree/removesessionsfolder/installation

There is no need to "clean up" existing folders like when we deleted folders in Joomla CMS elsewhere, because this is in the installation folder - and therefore is deleted on installation anyway.

**Comment by richard67** [comment]
The installation folder is indeed not handled by the files and folders deletion by purpose: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/deleted_file_check.php#L63-L75

**Comment by PhilETaylor** [comment]
> The installation folder is indeed not handled by the files and folders deletion by purpose:

Therefore this PR is correct and marking it with a an unsuccessful test is incorrect.

**Comment by richard67** [comment]
> > The installation folder is indeed not handled by the files and folders deletion by purpose:
> 
> Therefore this PR is correct and marking it with a an unsuccessful test is incorrect.

@PhilETaylor I agree. @brianteeman could you revert your unsuccessful test? Thanks in advance.

**Comment by wilsonge** [comment]
This formerly was hardcoded here https://github.com/joomla/joomla-cms/commit/14c78cfce6d9b06ed8c9aaa56898f722ed3fc8a1#diff-b000eaf18097ff802a6ad7bd96bd84543e8e232b2ded62dec482d0641d552defR56 . I think we've removed it when we moved here https://github.com/joomla/joomla-cms/pull/18896 and we just use php temp directory now?

**Comment by PhilETaylor** [comment]
>  I think we've removed it when we moved here #18896 and we just use php temp directory now?

Further supporting the aims of this PR as being perfectly valid

**Comment by richard67** [comment]
> This formerly was hardcoded here [14c78cf#diff-b000eaf18097ff802a6ad7bd96bd84543e8e232b2ded62dec482d0641d552defR56](https://github.com/joomla/joomla-cms/commit/14c78cfce6d9b06ed8c9aaa56898f722ed3fc8a1#diff-b000eaf18097ff802a6ad7bd96bd84543e8e232b2ded62dec482d0641d552defR56) . I think we've removed it when we moved here #18896 and we just use php temp directory now?

Yes, seems so.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 67617a9964098d7fffb36095962369a7732dd102<br /><br />The folder seems not to be used, at least I could not see it being accessed anyhow when making a new installation of J4.

When making a new installation where the folder has been removed before, the installation works well and there is no PHP error or warning logged.

Since the folder is below the installation folder, there is not need to care for removal on update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35140">issues.joomla.org/tracker/joomla-cms/35140</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
