### PR TITLE
[4.0] Use setDocumentTitle to set title for com_privacy

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Modify com_privacy component, uses setDocumentTitle method of HtmlView class to document title instead of writing repeating code. 

### Testing Instructions
For this simple change, code review should be enough.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 490a0b0b78c1e50b5d347e9904f37b9855948355<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32313">issues.joomla.org/tracker/joomla-cms/32313</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 490a0b0b78c1e50b5d347e9904f37b9855948355<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32313">issues.joomla.org/tracker/joomla-cms/32313</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32313">issues.joomla.org/tracker/joomla-cms/32313</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
