### PR TITLE
[com_menus] - remove notice

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #14951 .

### Summary of Changes
remove notice `Undefined variable: ntext `

### Testing Instructions
Create a menu with a menu item.
Disable this menu.
Try to enable the menu item under this menu.

### Expected result
no notice

### Actual result
PHP Notice: Undefined variable: ntext in \administrator\components\com_menus\controllers\items.php on line 248

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
Without PR there is an "Error"-Message, with PR there is a Message too:
bildschirmfoto 2017-03-28 um 08 06 32

**Comment by alikon** [comment]
you are 2 fast 4 me :sweat_smile:

**Comment by franz-wohlkoenig** [comment]
Set Error reporting to Maximum but don't get a PHP-Notice, only "Error"-Message is shown.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5055daa770fbaf9c5c3e9d409ecb6887021befeb<br /><br />@franz-wohlkoenig 

after patching no more Notice in php logs.

We only get the Error message as should.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14955">issues.joomla.org/tracker/joomla-cms/14955</a>.</sub>

**Comment by infograf768** [comment]
@alikon 
NOTE: I remarked something else that may be worth looking into. Unrelated to this PR.
Test:
Create a parent menu item and a few children. 
Whether you publish or unpublish the parent, the Message states only 1 menu item is published/unpublished, although all children are also concerned and change status.

**Comment by alikon** [comment]
yes is unrelated to this pr, but @infograf768 you can look at #13242

**Comment by joomdonation** [comment]
Personal, I think we can simplify the code of the PR a bit:

```php
try
{
	$model->publish($cid, $value);
	$errors      = $model->getErrors();
	$messageType = 'message';

	if ($value == 1)
	{
		if ($errors)
		{
			$messageType = 'error';
			$ntext       = $this->text_prefix . '_N_ITEMS_FAILED_PUBLISHING';
		}
		else
		{
			$ntext = $this->text_prefix . '_N_ITEMS_PUBLISHED';
		}
	}
	elseif ($value == 0)
	{
		$ntext = $this->text_prefix . '_N_ITEMS_UNPUBLISHED';
	}
	else
	{
		$ntext = $this->text_prefix . '_N_ITEMS_TRASHED';
	}

	$this->setMessage(JText::plural($ntext, count($cid)), $messageType);
}
catch (Exception $e)
{
	$this->setMessage($e->getMessage(), 'error');
}
```

Compare to the propose code;

1. It doesn't have to call app->enqueueMessage to queue the message

2. Doesn't have to call $this->setMessage, JText::plural on each part in if else if. I think the code is easier to read

It requires an extra variable to store $messageType, thought.

**Comment by franz-wohlkoenig** [comment]
@infograf768 thanks for Info.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on e54c695de3ba4449f43cc68d1a45d8c4e2f7f0ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14955">issues.joomla.org/tracker/joomla-cms/14955</a>.</sub>

**Comment by joomdonation** [comment]
@alikon Thanks for making the changes

@infograf768 Please re-test

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e54c695de3ba4449f43cc68d1a45d8c4e2f7f0ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14955">issues.joomla.org/tracker/joomla-cms/14955</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14955">issues.joomla.org/tracker/joomla-cms/14955</a>.</sub>

**Comment by alikon** [comment]
@joomdonation i really like when we can simplify stuff 
:wink:

**Comment by steinsson** [comment]
This still seems to be a problem after the official 3.7 release, at least in some cases. One of my grammar-school websites is facing this problem (http://grandaskoli.is). Any idea what couses this? Could an addon be interfearing in any way?

granda_error

**Comment by rdeutz** [comment]
You should open an issue if you think it is an error, but getting the message is not a problem when the error condition is met.

**Comment by zero-24** [comment]
Please open a new issue with the exact steps to reproduce this. Your error looks not realted to this PR.

**Pull request merged**
