### PR TITLE
code style fix for administrator/components/com_cache

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for code style
#### Summary of Changes

Expected "integer" but found "int" for function return type
No blank line found after control structure

[Automatically fixed with PHPCS2 fixers](https://github.com/joomla/coding-standards/pull/109)
#### Testing Instructions

merge by code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2d38c44e708d251587c82019c8442bf1dd571ca0<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11041">issues.joomla.org/joomla-cms/11041</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 2d38c44e708d251587c82019c8442bf1dd571ca0<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11041">issues.joomla.org/joomla-cms/11041</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11041">issues.joomla.org/joomla-cms/11041</a>.</sub>

**Comment by zero-24** [comment]
Bot please :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11041">issues.joomla.org/joomla-cms/11041</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot gone deaf?

**Comment by photodude** [comment]
Thanks everyone

**Pull request merged**
