### PR TITLE
Remove the newline character from the comment

### PR DESCRIPTION
**Pull request by shur**
A very simple PR just to remove an unnecessary newline character in a comment.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 668c7d4979437f1c805b98b8186f4e44164a5418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43596">issues.joomla.org/tracker/joomla-cms/43596</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 668c7d4979437f1c805b98b8186f4e44164a5418<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43596">issues.joomla.org/tracker/joomla-cms/43596</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43596">issues.joomla.org/tracker/joomla-cms/43596</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
