### PR TITLE
[5.0] schemaorg fix user parameter

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- inject `UserFactory` into schemaorg system plugin
- get user plugin parameter (`userId` is used instead of `user`)
https://github.com/joomla/joomla-cms/blob/d0a2509484366bf4439b8266c1debfe3e88d1e7f/plugins/system/schemaorg/schemaorg.xml#L37-L39

### Testing Instructions

set base type to `Person` and select an user account
image

check Person type

### Actual result BEFORE applying this Pull Request

`name` is not present (or you entered the name manually and to not match to the user)
image

### Expected result AFTER applying this Pull Request

`name` is preset (`name` of the selected user)
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on f315f7597e48a71e0a2e25b93fbcdc29380cb08c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41269">issues.joomla.org/tracker/joomla-cms/41269</a>.</sub>

**Comment by LadySolveig** [comment]
@heelc29 I have tested your pr successfully. Can you please merge the changes from PR #41260 into your branch so I can test on actual code state.
Then I can test again and record my result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41269">issues.joomla.org/tracker/joomla-cms/41269</a>.</sub>

**Comment by heelc29** [comment]
> Can you please merge the changes from PR #41260 into your branch

@LadySolveig conflicts resolved and branch updated

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on a1c6d7bb6ff47ce3539703b2310867d0e4c7a54d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41269">issues.joomla.org/tracker/joomla-cms/41269</a>.</sub>

**Comment by chmst** [comment]
@bembelimen could you repeat your test, please? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41269">issues.joomla.org/tracker/joomla-cms/41269</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
