### PR TITLE
[4.0] sr-only

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to replace use of the class element-invisible with sr-only. Just for consistency.

Code review should be enough

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b930c97137fa35c5d72520cfe90e294afb82baa1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25222">issues.joomla.org/tracker/joomla-cms/25222</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b930c97137fa35c5d72520cfe90e294afb82baa1<br /><br />PR covers all "element-invisible" class usage in 4.0-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25222">issues.joomla.org/tracker/joomla-cms/25222</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25222">issues.joomla.org/tracker/joomla-cms/25222</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
