### PR TITLE
[4.1] page class not suffix

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37047 .

The option to set a page class on a menu item sets a class on the body tag. But in some places it is also used on the container div of the component. As it is a class and not a suffix now (despite the name which wasnt changed for bc) this PR ensures that it is used as a class and not a suffix. ie there is a space before the page class.

PS not sure if this page class should even be used here so an alternative would be to remove it from these files

### CODE REVIEW

**Comment by RickR2H** [comment]
IMHO This will add empty spaces in the class names which is better to avoid. Some HTML validator might get picky about it.
Why not use:
```
<?php echo $this->pageclass_sfx ? ' ' . $this->pageclass_sfx : ''; ?>
```

**Comment by brianteeman** [comment]
Quite correct. I guess I was being lazy and copying the existing code from com_wrapper. I will update this pr shortly. Hopefully someone can then decide if the classes are even needed/desired

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 6b547a5ca7a1517f338348a2ec5456454296e490<br /><br />Patch works. Nice catch!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37055">issues.joomla.org/tracker/joomla-cms/37055</a>.</sub>

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on 6b547a5ca7a1517f338348a2ec5456454296e490<br /><br />

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37055">issues.joomla.org/tracker/joomla-cms/37055</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37055">issues.joomla.org/tracker/joomla-cms/37055</a>.</sub>

**Comment by bembelimen** [comment]
So we will break all templates which relies on the fact, that the page class suffix is attached to the existing classes (beside that it was a brackish decision in the past to put this class anywhere else than the body tag).

I see the point in this PR, but for b/c reasons I can't merge it (and probably for 5.0 we should remove it from inside the extensions as suggested by Brian).

**Comment by brianteeman** [comment]
I fully agree and understand

**Pull request closed without merging**
