### PR TITLE
[4.0] Remove unused model class

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes unused `Joomla\Component\Config\Site\Model\CmsModel` class which now also errors on PHP 8 due to method signature mismatch.

### Testing Instructions

Code review?

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by chmst** [comment]
Is it possible that 3rd party extension use this model?

**Comment by SharkyKZ** [comment]
It's possible. But to maintain PHP 8 compatibility we'd have to either update the method signatures or break class inheritance again, both of which are B/C breaks for anyone extending the class. So I think it's more painless to remove it and have developers extend `Joomla\CMS\MVC\Model\BaseDatabaseModel` instead. We have no way of testing if the model's code works in core anyways.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c27d0113d91cdb37f74977a9b7ae16d5a869041d<br /><br />I looked for CmsModel in php files throughout the code and found only one instance in CmsModel.php. I think this is a successful test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30600">issues.joomla.org/tracker/joomla-cms/30600</a>.</sub>

**Comment by ceford** [comment]
Belay that last test - after applying the patch the class is still in the code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30600">issues.joomla.org/tracker/joomla-cms/30600</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c27d0113d91cdb37f74977a9b7ae16d5a869041d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30600">issues.joomla.org/tracker/joomla-cms/30600</a>.</sub>

**Comment by ghost** [comment]
RTC?

**Comment by richard67** [comment]
@wilsonge Does anything speak against RTC with respect to the [comment above](https://github.com/joomla/joomla-cms/pull/30600#issuecomment-689803897)?

**Comment by wilsonge** [comment]
No we should be good as it's part of the component. Our B/C promise has never extended into components

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
