### PR TITLE
[4.0] LanguageAdapter prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds some missing prepared statements and cleans up queries in `Joomla\CMS\Installer\Adapter\LanguageAdapter`.

### Testing Instructions

Test that installing/updating/uninstalling languages works like before.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a980c7bb413dfbeeb921d9a385f5f7c2af656631<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26347">issues.joomla.org/tracker/joomla-cms/26347</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a980c7bb413dfbeeb921d9a385f5f7c2af656631<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26347">issues.joomla.org/tracker/joomla-cms/26347</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26347">issues.joomla.org/tracker/joomla-cms/26347</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
