### PR TITLE
[3.10] Backport Table _supportNullValue handling to 3.10

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This backports the `_supportNullValue` from the base table class to Joomla 3.10

It bases on this commits against 4.x:
https://github.com/joomla/joomla-cms/commit/447983bd7f3613c2708f500ccb7fa461f30d71b2
https://github.com/joomla/joomla-cms/commit/f472a7c44fe0f660eea66b870a9875c244774358
https://github.com/joomla/joomla-cms/commit/ba6641c1ca9c64150d08773781d64037f1ce5670

This is fully B/C and there are not intentions to change to NULL Dates in 3.x. This here just has the intention to allow extension devs to use the same code for the tables in 3.10 and 4.x including the `_supportNullValue` switch.

### Testing Instructions

- Apply the patch and navigate arround
- create an article
- checkout an article
- checkin an article 

### Actual result BEFORE applying this Pull Request

It works

### Expected result AFTER applying this Pull Request

It still works but now has the optional supportNullValue switch for developers backported.

### Documentation Changes Required

Maybe it is worth mention that in the doc for the 4.x changes.

cc @wilsonge

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
Is this PR for #29441 and #29429?

**Comment by zero-24** [comment]
Only the first issue i guess this does not change anything for existing extensions nor provide any kind of migration for them it just allow them to use the same code for the table class in 3.10 and 4.0

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f00381a98a1bcf433dfa3cba836cacce8257038f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30102">issues.joomla.org/tracker/joomla-cms/30102</a>.</sub>

**Comment by adj9** [comment]
One thing is not clear to me: how do I check the article?

**Comment by zero-24** [comment]
What do you mean by check the article?

**Comment by adj9** [comment]
The third point of Testing Instructions, "checkout an article".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30102">issues.joomla.org/tracker/joomla-cms/30102</a>.</sub>

**Comment by zero-24** [comment]
You checkout an article when you edit an  article in the backend. When you save & close the article they are checked in again.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d8c088b5d1d95ad2bec86fcb91a962eb917fedd4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30102">issues.joomla.org/tracker/joomla-cms/30102</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by zero-24** [comment]
This has been documented here: https://docs.joomla.org/J3.x:Joomla_3.10_Backports

**Pull request merged**
