### PR TITLE
Fixing curl following redirect everytime

### PR DESCRIPTION
**Pull request by alex7r**
### Summary of Changes
Include user options into check

### Testing Instructions
```PHP
$options = array('follow_location'=>false);
$options = new \Joomla\Registry\Registry($options);
$http = \JHttpFactory::getHttp($options);
```
Should not follow redirects

### Documentation Changes Required

Fix of following redirects even if user doesn't want to

### CODE REVIEW

**Comment by alex7r** [comment]
@mbabker , @rdeutz 
Would somebody look here?
It's really missed and should be there.

**Review by mbabker — APPROVED** [review]

**Comment by alex7r** [comment]
@rdeutz , @wilsonge 
Who is the person that can be pointed to merge?

**Comment by rdeutz** [comment]
I will have a look when I find a minute

**Comment by wilsonge** [comment]
This is fine

**Comment by alex7r** [comment]
Thanks

**Pull request merged**
