### PR TITLE
_getUser invalide name fix

### PR DESCRIPTION
**Pull request by HRIT-Florian**
"fullname" is undefined, correct key is "name"

tested with joomla 4.0.3

### CODE REVIEW

**Comment by brianteeman** [comment]
I'm a little confused by this as this code hasn't changed in 13 years<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35679">issues.joomla.org/tracker/joomla-cms/35679</a>.</sub>

**Comment by HRIT-Florian** [comment]
@brianteeman so maybe these is now the problem, because the passed array is not more valide with the 13 years old code.
fullname is not defined, tested with joomla 4.0.3

**Comment by joomdonation** [comment]
@Didldu-Florian **fullname** is still the right key. Maybe it is not working for you because you are using a none-core authentication plugin? For core plugins, it returns **fullname** in response object like this https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/authentication/joomla/joomla.php#L86 , and you won't get that undefined error.

**Comment by HRIT-Florian** [comment]
@joomdonation okay, that's it, you are all right. 
Did closed that PR

**Pull request closed without merging**
