### PR TITLE
[com_users] - fix typo in profile view

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #11666 .

### Summary of Changes
fix typo in profile view

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
is this Test a code Review?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15139">issues.joomla.org/tracker/joomla-cms/15139</a>.</sub>

**Comment by alikon** [comment]
should be enough

**Comment by franz-wohlkoenig** [comment]
@alikon thanks for Info, that this is for Code Review.

**Comment by zero-24** [comment]
i have fixed the typo here too: https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/form/view.html.php#L74

with: https://github.com/joomla/joomla-cms/commit/6c497b90d27cd86e305b66022086879cc63d931f

**Pull request merged**
