### PR TITLE
Missing bottom border in modal.

### PR DESCRIPTION
**Pull request by NikitaEmberi**
Pull Request for Issue #32190 
### Summary of Changes

Changes as suggested in:https://github.com/joomla/joomla-cms/issues/32190#issuecomment-801452820
and https://github.com/joomla/joomla-cms/pull/32762#issuecomment-803442647

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b462a9809a3cba51ad54c44fa04276d2287da5c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32814">issues.joomla.org/tracker/joomla-cms/32814</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b462a9809a3cba51ad54c44fa04276d2287da5c4<br /><br />with Prebuild Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32814">issues.joomla.org/tracker/joomla-cms/32814</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32814">issues.joomla.org/tracker/joomla-cms/32814</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks!

**Comment by richard67** [comment]
@NikitaEmberi Thank you, and congratulations to your first pull request for the Joomla CMS.

**Pull request merged**
