### PR TITLE
Notice Trying to get property of non object on login page

### PR DESCRIPTION
**Pull request by danieldsf**
Pull Request for Issue # .

### Summary of Changes

I was getting an error:  **Notice Trying to get property of non object** on the administrator login page, so I decided to fix this issue according to this suggestions: [Notice Trying to get property of non object](https://stackoverflow.com/questions/27408663/notice-trying-to-get-property-of-non-object-in-php). I hope it doesn't create any other bugs.

### CODE REVIEW

**Comment by zero-24** [comment]
Hi, thanks for your contribution 👍 

What did you do to get the `Notice Trying to get property of non object`? How can we reproduce the issue? As on a first look this does not look like the best fix. As we should fix the root cause if possible and not the symptom ;)

**Comment by danieldsf** [comment]
Hello, @zero-24 !
I am not really sure **why** it appears. I was updating my old 3.6.4 Joomla Version to latest one (3.8.6) and then when I got to the login page it just appeared.

**Comment by SharkyKZ** [comment]
This will break the entire function because language code is never numeric.

**Comment by zero-24** [comment]
> I am not really sure why it appears. I was updating my old 3.6.4 Joomla Version to latest one (3.8.6) and then when I got to the login page it just appeared.

Can you please check the languages that you have installed?

**Comment by danieldsf** [comment]
That makes sense. You are right, it's not really numeric. In php 5.6 it works, though. I will close the pull request then.

**Comment by danieldsf** [comment]
Languages: pt-PT, pt-BR, en-US, en-GB

**Comment by zero-24** [comment]
> Languages: pt-PT, pt-BR, en-US, en-GB

hmm do you know how to do a breakpoint and setup xdebug to see what comes there?
can you reproduce that issue on a new install with that languages too?
what 3rd party Extension do you have installed

**Pull request closed without merging**
