### PR TITLE
[4.3] Bypass access level check for users with core.admin permission

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #40151.

### Summary of Changes
This PR modifies the code uses in **Category** form field to by pass access level check for users with `core.admin` permission, similar as how we are doing for other field type like https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_categories/src/Field/CategoryeditField.php#L214

### Testing Instructions
1. Login using a super users account.
2. Create a new access level **Author**, only select **Author** user group for that access level
3. Access to Content -> Categories, create a new category, set Access to Author access level above
4. Access to Content -> Articles, click on **Filter Options**, look at Categories filter dropdown in search tools

### Actual result BEFORE applying this Pull Request
You do not see the category you created above in the categories dropdown. You should see it, as a super user, you should see all categories in the dropdown (same as the categories dropdown when you add new article).

### Expected result AFTER applying this Pull Request
You see the category which you created above in the categories filter dropdown, not depend on the access level you set for the category.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by boddunan** [comment]
@joomdonation  Tested this change and it is working fine. The category form field now shows all categories.

**Comment by joomdonation** [comment]
@boddunan Could you please go to https://issues.joomla.org/tracker/joomla-cms/40193 and report your test result there ?

**Comment by boddunan** [comment]
I have tested this item :white_check_mark: successfully on c63878cc982446c808a5b88898d80013b6efc287<br /><br />1. Created new child user group under registered user group
2. Created new access level that allow child user group
3. Created a custom component with category support
4. Created new category with child access level
5. Created new category menu item for the child category

Can see child category with child access level in the category form field.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40193">issues.joomla.org/tracker/joomla-cms/40193</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c63878cc982446c808a5b88898d80013b6efc287<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40193">issues.joomla.org/tracker/joomla-cms/40193</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40193">issues.joomla.org/tracker/joomla-cms/40193</a>.</sub>

**Comment by obuisard** [comment]
Thank you Tuan @joomdonation for the PR!

**Pull request merged**
