### PR TITLE
[4.2] article status script

### PR DESCRIPTION
**Pull request by brianteeman**
Completes an `@todo` by moving an inline script to a standaloine script using webassetmanager.

### Testing Instructions
The script is used to disable clicking on the status icon in the content admin when workflows is enabled.
apply the pr and `npm ci`

### Expected result AFTER applying this Pull Request
workflows disabled - no change the status button is clickable
workflows enabled - no change the status button is not clickable

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7b62221e134d77a65312a9dab56b9eaa899acdab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38154">issues.joomla.org/tracker/joomla-cms/38154</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7b62221e134d77a65312a9dab56b9eaa899acdab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38154">issues.joomla.org/tracker/joomla-cms/38154</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38154">issues.joomla.org/tracker/joomla-cms/38154</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
