### PR TITLE
[staging] Missing language strings in frontend en-GB.lib_joomla.ini

### PR DESCRIPTION
**Pull request by infograf768**
Backend and frontend en-GB.lib_joomla.ini should be exactly the same.
4 strings were missing from the frontend file.

Can be merged on review.
@rdeutz 
@zero-24

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c7e1e4026dbecdc367d0ecfabae630f576e53fc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12468">issues.joomla.org/tracker/joomla-cms/12468</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on c7e1e4026dbecdc367d0ecfabae630f576e53fc3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12468">issues.joomla.org/tracker/joomla-cms/12468</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12468">issues.joomla.org/tracker/joomla-cms/12468</a>.</sub>

**Comment by infograf768** [comment]
this has been targetted to staging because the lib was updated in staging last night

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/commit/0af7cafe7ca530018c338c357dcf4f9862d7c375

**Pull request merged**
