### PR TITLE
[4.0] Handle errors generated by language downloads gracefully

### PR DESCRIPTION
**Pull request by roland-d**
### Summary of Changes
While trying to install a multi-language site I ran into several errors but was not given any information about them on screen. I found them in the XHR request and later in the log file.

### Testing Instructions
1. Get a clean Joomla 4 checkout
2. Start the installation process
3. When the installer is done with the basics, you see this screen:
image
4. Click on Customize Installation
5. Select the `Dutch` language
6. Scroll down and click Next
7. You are back at step 3. If you are lucky you would see a message flash by
8. Apply the patch
9. Select the `Dutch` language
10. Scroll down and click Next
11. Now you stay on the page and see this warning message:
image

I have another problem with the French language, here you see no warning but an error.
1. Select the `French` language
2. Scroll down and click Next
3. Now you stay on the page and see this error message:
image

### Expected result
User is shown the error message

### Actual result
Message is shown but page is immediately redirected so impossible to read.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
Hi @roland-d thanks for this
The problem of the messages disappearing is not limited to the ones you identified but i am not at my pc this morning to look and my memory is failing

**Comment by roland-d** [comment]
@brianteeman I can take a look later to see which others there are. Feel free to post your comments later on as I am not sure when I will be back.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on af9833911486d9886b430b741772b134560c010a<br /><br />Tested a bit different to the description:
1. Installed J4 with currend 4.0-dev.
2. Customize installation: Tried Dutch language => Failed, but no warning or error message shown.
3. Customize installation: Tried French language => Failed, but no warning or error message shown.
4. Logged in at backend.
5. Installed Patchtester (I have modified up-to-date package which works).
6. Installed patch of this PR with Patchtester.
7. `npm i` (Not necessary I guess, but who knows).
8. Cleared database and removed configuration.php
9. Repeated steps 1 to 3: This time the warning and error messages were shown.

In case of French language, I would like to see in addition to the error message the warning like shown for the Dutch language. But this might be done in another PR. This one here works as described.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25078">issues.joomla.org/tracker/joomla-cms/25078</a>.</sub>

**Comment by infograf768** [comment]
Reminder. Afaik language installation atm is limited to french,german and persian.
it has always been broken at J4 installation time, but works fine from admin installer install languages.

**Comment by richard67** [comment]
@infograf768 Sure, we know that. This PR uses that fact to have some error happening, and fixes the fact that the warnings or error messages never became visible.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on af9833911486d9886b430b741772b134560c010a<br /><br />Does what it says

Can you open an issue for the JNamespacePsr4Map not found
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25078">issues.joomla.org/tracker/joomla-cms/25078</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by roland-d** [comment]
@brianteeman I posted PR #25121  to fix the `JNamespacePsr4Map` error.

**Comment by brianteeman** [comment]
Thanks

**Comment by SniperSister** [comment]
Merged, thanks!

**Pull request merged**
