### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change `it's` to `its`. 

### Testing Instructions
Code review.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Review by C-Lodder — APPROVED** [review]

**Comment by zero-24** [comment]
Thanks

**Comment by laoneo** [comment]
Just curious, what does it mean in the Joomla land when somebody is approving a pr?

**Comment by mbabker** [comment]
Someone basically did a code review but didn't really test it is the way I read it.

**Comment by zero-24** [comment]
How can you test a comment change?

**Comment by brianteeman** [comment]
Exactly

**Comment by laoneo** [comment]
My question (not critic) was in general and not particular for this pr. I see more and more people approving pull requests but not testing them.

**Comment by brianteeman** [comment]
Several months ago on glip it was suggested that all PR needed to be tested and to have reviews

**Comment by C-Lodder** [comment]
@laoneo - Personally, I tend to do this when I don't have time to test a PR properly, but instead have a quick skim through the code (on a small PR)

**Pull request merged**
