### PR TITLE
[4.0] Flex based control-group fields

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #27558, #27681, #27676 #27664 .

### Summary of Changes
Moves field control-groups to flex.

- Less CSS required
- Flex naturally supports RTL so no RTL CSS required.
- Media queries look at the width of the viewport and are the only way to change the orientation of the current control-group fields. Flex would allow us to change the orientation of the field depending on the space available to it. A much more versatile and safer way to approach responsive fields especially.
- Duplicate CSS removed
- Fixes `form-vertical` class

Simply put, with this PR,  label/fields will become container aware,  moving from vertical to horizontal aligned if the field is reduced to less than 210px. I have also enabled the `form-vertical` class. The addition of this class and the field will always display vertically. The `fields-no-margin` has been removed completely.

Edit: Any field in a multi-column layout, displays in a vertical format regardless of the space available to it. This was always the case.

### Testing Instructions
Apply this patch and run `node build.js --compile-css` for updating the changed SCSS. Check fields display correctly.

### CODE REVIEW

**Comment by Fedik** [comment]
> Less CSS required

I thought Joomla! 4 use scss 😋

**Comment by brianteeman** [comment]
Might be me doing something wrong but something isnt right with the switcher now

### Before
image

### After
image

**Comment by ciar4n** [comment]
@brianteeman Do you know of any reason why the switcher has a `sr-only` class on the label and then adds a second visible 'label' in the form of a legend within the field control? It seems strange and at odds with all other fields.

**Comment by ciar4n** [comment]
Switcher html...

```
<div class="control-group">
  <div class="control-label sr-only">
    <label id="jform_featured-lbl" for="jform_featured">
      Featured
    </label>
  </div>
  <div class="controls">
    <fieldset id="jform_featured">
      <legend class="switcher__legend">
        Featured
      </legend>
      <div class="switcher">
        <input type="radio" id="jform_featured0" name="jform[featured]" value="0">    <label for="jform_featured0">No</label>         <input type="radio" id="jform_featured1" name="jform[featured]" value="1" checked="checked" class="active">   <label for="jform_featured1">Yes</label>    <span class="toggle-outside"><span class="toggle-inside"></span></span>
      </div>
    </fieldset> 
  </div>
</div>
```

**Comment by brianteeman** [comment]
Yes. It was the only way to achieve the correct accessibility. But without checking the original pr I don't remember more than that

**Comment by ciar4n** [comment]
Does that mean only the switcher has the correct accessible html? If so then we can probably close this until all other fields are brought up to speed. Considering the switcher html, this PR would be quite different.

**Comment by brianteeman** [comment]
switcher is a fieldset and a fieldset requires a legend

**Comment by C-Lodder** [comment]
@ciar4n - The switcher is like this because you can't associate a label with multiple inputs...only a single input. The only other form fields I can think of that may need checking are checkbox/radio....but only when using multiple.

**Comment by ciar4n** [comment]
Ok thank you. I'm guessing we can't just move the `sr-only` class from the label to the legend?

**Comment by C-Lodder** [comment]
I think it's being used incorrectly so that the `.control-label` doesn't take up any space.

Instead the `.sr-only` should be moved to the `<label>` and a `d-none` class be added to the parent `<div>`

**Comment by brianteeman** [comment]
give me two seconds to check that. my memory is failing me but there must have been a reason I did it that way

**Comment by brianteeman** [comment]
changing the sr-only to being on the legend instead of the label seems to be ok. not sure I understand the d-none comment

**Comment by C-Lodder** [comment]
@brianteeman Form fields in Joomla have a label to the left of the field (220px in width or somthing). This isn't the case with the switcher. Instead it's to the right hand side.
So to hide that 200px gap to the left of the switcher, they've used `sr-only` on `<div class="control-label sr-only">`.

**Comment by brianteeman** [comment]
my brain isnt in gear sorry.

The label to the right is the label for the value of the radio = eg yes/no
the field label and legend are to the left

why I chose to hide the label and not the the legend is something I dont remember and looking at the original pr doesnt help me

**Comment by brianteeman** [comment]
corrected last comment

**Comment by ciar4n** [comment]
I've moved the `sr-only` from the legend to the label which fixes the switcher style issue.

**Comment by ciar4n** [comment]
Just to mention, any field in a multi column layout, displays in a vertical format regardless of the space available to it. This was always the case.

**Comment by ciar4n** [comment]
> Instead the .sr-only should be moved to the <label> and a d-none class be added to the parent <div>

I read that a little fast. I'll look in to this later.

**Comment by brianteeman** [comment]
the switcher changes look good to me now

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ad91d2752ccef2a8fdc51782fd5cfa322ab20108<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by Quy** [comment]
help

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on ad91d2752ccef2a8fdc51782fd5cfa322ab20108<br /><br />Perfect on a Macbook Pro.
Can't see the last error mentioned by @Quy in Indexing options. But again it's tested on a MacBook.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by Quy** [comment]
More display issues. Firefox 72.0.2 Windows 10

**Comment by ciar4n** [comment]
@Quy should be ok now

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0fc2363daf5bf524d2e5b7490d671c783e162976<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0fc2363daf5bf524d2e5b7490d671c783e162976<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by Quy** [comment]
There is a top/bottom padding with the label. Is that OK?

AFTER:
27684-after

BEFORE:
27684-before

**Comment by ciar4n** [comment]
@Quy I have reduced the label padding...

image

Minor change so can probably remain RTC

**Comment by Quy** [comment]
Switcher needs to be adjusted too.

27684-switcher

**Comment by ciar4n** [comment]
@Quy Ty. Switcher updated.

**Comment by Quy** [comment]
There is less vertical spacing between the fields.

BEFORE:
27684-spacing

AFTER:
27684-less-spacing

**Comment by ciar4n** [comment]
@Quy updated

**Comment by Quy** [comment]
Looks good!! Thank you.

**Comment by infograf768** [comment]
Anyone tested rtl ?

**Comment by Quy** [comment]
There is extra padding on the first field.

27684-top

**Comment by Quy** [comment]
> Anyone tested rtl ?

Yes, looks fine.

**Comment by ciar4n** [comment]
> There is extra padding on the first field.

@Quy Top margin removed.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e47639225cbab2378b8158880927f71d42b0ebba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27684">issues.joomla.org/tracker/joomla-cms/27684</a>.</sub>

**Comment by infograf768** [comment]
Works fine here but one question:

@ciar4n 
Is it possible to also correct the Global Configuration Text Filters tab in reduced window width (LTR and RTL)? Or shall we postpone this to another PR (if even possible)?

Screen Shot 2020-01-30 at 08 35 46
Screen Shot 2020-01-30 at 08 36 43

**Comment by ciar4n** [comment]
Outside the scope of this PR but as a quick fix I have added the `table-responsive` class to the table which basically adds a horizontal scroll on smaller screens.  This area is in a table which will always be an issue on smaller screens. Maybe something like https://github.com/joomla/joomla-cms/pull/13769 could be applied if the horizontal scroll is not sufficient (separate pr).

**Comment by brianteeman** [comment]
We have a PR for the permissions already see #27670

**Comment by infograf768** [comment]
@ciar4n 
Better, but not enough indeed. specially for the dropdowns.
may I suggest a change?

add
```
#page-filters .custom-select {
	width: auto;
}
```
in `administrator/templates/atum/scss/blocks/_form.scss`
towards the end of the file.
npm

### Before patch
beforeconfig


### After patch
afterconfig

**Comment by ciar4n** [comment]
@infograf768 I'll leave it for a separate PR. As mentioned there is a PR for the permissions already. This PR is for the field `control-group`. The permissions is not even in a `control-group`.

**Comment by infograf768** [comment]
This proposal above does not concerns **Permissions**, but the **Text Filters**.
https://github.com/joomla/joomla-cms/pull/27670 concerns only Permissions... and works well for that.

**Comment by infograf768** [comment]
I have tested both Permissions PR and this PR.
They are Ok for what they do.
Will make a new PR for Text Filters after they are merged.
In the mean while, I merge this one as it solves many issues.

**Comment by infograf768** [comment]
Tks.

**Comment by ciar4n** [comment]
Thank you for the tests!

**Pull request merged**
