### PR TITLE
send test mail button   ajax call has always smtpauth = 1

### PR DESCRIPTION
**Pull request by anibalsanchez**
Pull Request for Issue #9768.
#### Summary of Changes

Send Test Mail button does not correctly evaluate "SMTP Authentication" radio. Then, mails are sent via SMTP even when "SMTP Authentication" is disabled.

Fix: smtpauth : $('input[name="jform[smtpauth]"]:checked').val(),
#### Testing Instructions
1. Fill all SMTP fields in Mail Settings for a server that requires authentication
2. Test it, click on 'Send Test Mail' button to receive an email
3. Disable "SMTP Authentication" radio
4. Test it, click on 'Send Test Mail' button ... email must not be received

### CODE REVIEW

**Comment by brianteeman** [comment]
Not sure its quite correct
If I set smtp and authentication yes and invalid username and password then i correctly get SMTP Error: Could not authenticate.
BUT
1. If i leave username and password empty i get the success message
2. If i enter a fake username and leave password empty I get the success message

**Comment by anibalsanchez** [comment]
@brianteeman The problem is found when your fill all SMTP credentials and keep "SMTP Authentication"=No... it applies the credentials even when it is disabled.

In this PR, I have modified the code to really check for the "SMTP Authentication" radio value.

An alternative solution could be to just remove the useless "SMTP Authentication" radio. If there are SMTP credentials, they are applied without checking for a radio.

**Comment by smz** [comment]
> An alternative solution could be to just remove the useless "SMTP Authentication" radio. If there are SMTP credentials, they are applied without checking for a radio.

This! (_and, if you wish, password displayed on showon of the username..._)

**Comment by smz** [comment]
... but probably "_showon not empty text field_" is not possible, or is it?

**Comment by anibalsanchez** [comment]
The aim of this issue is to fix the user interface bug.

**Comment by andrepereiradasilva** [comment]
could you solve the conflicts now the other one as been merged?

**Comment by anibalsanchez** [comment]
Please, close this one as I have submitted an updated PR for testing - #9904

@andrepereiradasilva @smz

**Pull request closed without merging**
