### PR TITLE
[4.0] Console error on installer.js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #21076 .

### Summary of Changes
A variable didnt exist (due to bad copy pasting)

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 11cfca9141d40b0f92d850ab12508c799c4f2c43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21077">issues.joomla.org/tracker/joomla-cms/21077</a>.</sub>

**Comment by dgrammatiko** [comment]
@brianteeman what was the package you tried to install?
Also which browser did you use?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 11cfca9141d40b0f92d850ab12508c799c4f2c43<br /><br />retested after making even more sure the cache was cleared and it worked<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21077">issues.joomla.org/tracker/joomla-cms/21077</a>.</sub>

**Comment by laoneo** [comment]
Can you not exclude the js files by wildcard?

**Comment by dgrammatiko** [comment]
It conflicts with the first rule

**Comment by laoneo** [comment]
Just to have a rough idea, what needs to be done that the .js files do pass too? I'm a bit hesitant to merge this in the state as it is now.

**Comment by dgrammatiko** [comment]
>  what needs to be done that the .js files do pass too?

Nope, the transpiled files (eg dest) should not be part of the linting because these are ES5 files and the linter expect **only** ES6 files. I'm still in favour of a dedicated **source** folder and the whole `media` folder gets created from our tools (eg npm install)

**Comment by brianteeman** [comment]
@dgrammatiko can you resolve the conflicts please

**Pull request merged**
