### PR TITLE
Contacts - move Filters from left to [Search Tools] #6951

### PR DESCRIPTION
**Pull request by pe7er**
I had a merge conflict & redid the changes.
Please see https://github.com/joomla/joomla-cms/pull/6951 for test.

---

This PR moves the 5 Filter options of the Contacts Manager to the [Search Tools] button.
**note**: The ordering dropdown in [Search Tools] **needs to be fixed** before merging.
(See Issue #6941 regarding the inconsistency with Filter options).
## Test instructions

In back-end > Components > Contacts
See the filters on the left

screen shot 2015-05-15 at 06 37 24

Compare with the filters in Category Manager for Contacts: 
In back-end > Components > Contacts > Categories

screen shot 2015-05-15 at 06 37 23
### This PR changes moves the Filters

from the left to the middle column and will be visible when you click on the [Search Tools] button.

screen shot 2015-05-15 at 06 37 23
### **Notes:**

I can use some help & suggestions regarding the following issues:
- The ordering dropdown in [Search Tools] is currently not working
- Code cleanup 1 - tmpl view ( /administrator/components/com_tags/views/tags/tmpl/default.php ) 
  contains "Joomla.orderTable = function()" that probably can be removed

### CODE REVIEW

**Comment by infograf768** [comment]
not tested but code style:
```
		if ($canDo->get('core.create') || (count($user->getAuthorisedCategories('com_contact', 'core.create'))) > 0) {
 			JToolbarHelper::addNew('contact.add');
 		}
```
should be
```
		if ($canDo->get('core.create') || (count($user->getAuthorisedCategories('com_contact', 'core.create'))) > 0)
		{
 			JToolbarHelper::addNew('contact.add');
 		}
```

**Comment by brianteeman** [comment]
Updated the title to more meaningful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7072">issues.joomla.org/joomla-cms/7072</a>.</sub>

**Comment by peterlose** [comment]
Tested. Seems to work fine. Could you look at the CS @pe7er ?

**Comment by ramya185** [comment]
Tested on chrome Version 43.0.2357.134.
Worked fine. #jqConf15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7072">issues.joomla.org/joomla-cms/7072</a>.</sub>

**Comment by brianteeman** [comment]
When the codestyle issues have been resolved this can be moved to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7072">issues.joomla.org/joomla-cms/7072</a>.</sub>

**Comment by zero-24** [comment]
here is a PR that should fix the CS issues: https://github.com/pe7er/joomla-cms/pull/3

**Comment by pe7er** [comment]
Thanks for the fix @zero-24!

**Comment by zero-24** [comment]
RTC Thanks @pe7er <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7072">issues.joomla.org/joomla-cms/7072</a>.</sub>

**Comment by roland-d** [comment]
@pe7er Can you please fix the merge conflicts?

**Comment by pe7er** [comment]
@roland-d The functionality of this PR seems to be merged in 4.6dev already with a later PR #7995 from someone else...

**Comment by zero-24** [comment]
Ok so I close here.

**Pull request closed without merging**
