### PR TITLE
Use the right mime type in the the media field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #38333 .

### Summary of Changes

The preview might get the wrong mime type in some cases.

### Testing Instructions

- Edit the file `administrator/components/com_content/forms/article.xml` and add `types="images,audios,videos,documents"` after https://github.com/joomla/joomla-cms/blob/7cf5e1228db337881d7678ad1c71915d5c885150/administrator/components/com_content/forms/article.xml#L752
- Try to upload and select different type of media, especially video, audio and document (eg, mp3, mp4, mov, pdf, doc, docx, etc)

### Actual result BEFORE applying this Pull Request

No preview in some cases

### Expected result AFTER applying this Pull Request

Preview is ok

### Documentation Changes Required

No

### CODE REVIEW

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on abd4aca766a4e5ac61b39d8776a90d669ee9472f<br /><br />Thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38425">issues.joomla.org/tracker/joomla-cms/38425</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on abd4aca766a4e5ac61b39d8776a90d669ee9472f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38425">issues.joomla.org/tracker/joomla-cms/38425</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38425">issues.joomla.org/tracker/joomla-cms/38425</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
