### PR TITLE
Release Blocker: Fix tabs disappearing

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #14281 .

### Summary of Changes
Bug fix

### Testing Instructions
Apply the patch and go to Admin->Extensions->Templates->templates
Make sure that tabs are there and fully functional

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 94b7875acd5f79c903fd2fe1a1a0f60c9c6d9c35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14287">issues.joomla.org/tracker/joomla-cms/14287</a>.</sub>

**Comment by uglyeoin** [comment]
I have tested this item :white_check_mark: successfully on 94b7875acd5f79c903fd2fe1a1a0f60c9c6d9c35<br /><br />I have tested this on localhost.  

The button appears.  It says success when it is clicked.  An override appears in the /templates/**/html/com_content folder as I expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14287">issues.joomla.org/tracker/joomla-cms/14287</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 94b7875acd5f79c903fd2fe1a1a0f60c9c6d9c35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14287">issues.joomla.org/tracker/joomla-cms/14287</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14287">issues.joomla.org/tracker/joomla-cms/14287</a>.</sub>

**Pull request merged**
