### PR TITLE
Remove indexes from contentitem_tag_map

### PR DESCRIPTION
**Pull request by sovainfo**
Removing indexes that are not needed.
This assumes the primary key is using type_id instead of type_alias. See #6748 
The indexes on type_id and tag_id are redundant because of the other
indexes avialable. The index on tag-name (tag_id, type_alias) only
existed for MsSQL.

### CODE REVIEW

**Comment by waader** [comment]
Successfully tested with all databases.

**Comment by pos-it** [comment]
I have tested this item :white_check_mark: successfully on f23313f5101c6ffb6d9edd079ad822bd7e4ea43f<br /><br />Tested only on MySQL but there it works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6795">issues.joomla.org/joomla-cms/6795</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f23313f5101c6ffb6d9edd079ad822bd7e4ea43f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6795">issues.joomla.org/joomla-cms/6795</a>.</sub>

**Comment by zero-24** [comment]
RTC :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6795">issues.joomla.org/joomla-cms/6795</a>.</sub>

**Comment by roland-d** [comment]
@sovainfo Can you please update this PR by renaming the SQL files to version 3.5.0 as this is the version they will be merged in. The date for the SQL files needs to be 2015-12-04 as that will be release date of 3.5.0. Thank you.

**Comment by mbabker** [comment]
It doesn't *NEED* to be the date of release.  Typically we've done it where it's the day it's merged in the past.

**Comment by sovainfo** [comment]
Changed the version to 3.5.0, don't understand why this bugfix is delayed to a minor update!
Kept the date as is, consider it absurd to predict the date upon creation of a fix!

Note that all three files are renamed using Github, despite it only shows one on the commit!

**Comment by roland-d** [comment]
@sovainfo Very simple why it is delayed, second test didn't come in until 2 days ago.

Thanks everybody, merged with commit 1542855

**Comment by sovainfo** [comment]
@roland-d That explains why it takes that long for bugfixes to get through. It doesn't explain why SemVer is not followed!

**Comment by Bakual** [comment]
@sovainfo Actually, it doesn't matter at all in this case. 3.5.0 is expected to be the next release anyway.

**Comment by sovainfo** [comment]
It matters when you claim to be following SemVer. Current actions don't make sense. Why is there a milestone 3.4.6 ? What happens when 3.5 will be postponed again and 3.4.6, 3.4.7 and following will be released?

How hard can it be to really follow SemVer?

**Comment by mbabker** [comment]
If we were following SemVer to the letter with zero deviation then 3.4.5 should have been 4.0.0, likewise 3.5.0 should be 4.0.0 (actually 5.0.0 had we incremented the major version correctly).  Sometimes it's a judgement call and sometimes there is an intended plan that changes and causes things to go awry.

**Pull request closed without merging**
