### PR TITLE
[4.0] sql install there is no more plg_system_p3p

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
remove from install.sql the no more existent plugin `plg_system_p3p`

### Testing Instructions
code review

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ff6b9e97ade4d6d98f17f3eda4c350f985f4d7ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21913">issues.joomla.org/tracker/joomla-cms/21913</a>.</sub>

**Comment by alikon** [comment]
oops just discovered a new one  R.I.P `mod_submenu`  :pray:

**Comment by alikon** [comment]
i will do a new pr cause of `#__assets` table involved

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on ff6b9e97ade4d6d98f17f3eda4c350f985f4d7ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21913">issues.joomla.org/tracker/joomla-cms/21913</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21913">issues.joomla.org/tracker/joomla-cms/21913</a>.</sub>

**Comment by zero-24** [comment]
Thanks merging.

**Pull request merged**
