### PR TITLE
[4][webservices] wrong parameter for setting  Access-Control-Allow-Methods

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
wrong parameter  for setting  Access-Control-Allow-Methods

### Testing Instructions
code review

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on e41a3291e1cb0dbf73368f907303209ec10f2dba<br /><br />Checked the variable in configuration.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35893">issues.joomla.org/tracker/joomla-cms/35893</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on e41a3291e1cb0dbf73368f907303209ec10f2dba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35893">issues.joomla.org/tracker/joomla-cms/35893</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35893">issues.joomla.org/tracker/joomla-cms/35893</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35893">issues.joomla.org/tracker/joomla-cms/35893</a>.</sub>

**Comment by richard67** [comment]
@alikon Either the tracker got confused by the labels or it was not set RTC by changing status in the tracker so it was not RTC.

I've set RTC now again and it seems that worked.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
