### PR TITLE
[4.2] Backup confirm message

### PR DESCRIPTION
**Pull request by brianteeman**
PR for the last remaining part of #36151

image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e0755e1a8a4533c1bc96f869ae0b183d3b3f1592<br /><br />Tested successfully in Joomla 4.2.0-beta2-dev of 15 June using PHP 8.0.15.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38071">issues.joomla.org/tracker/joomla-cms/38071</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e0755e1a8a4533c1bc96f869ae0b183d3b3f1592<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38071">issues.joomla.org/tracker/joomla-cms/38071</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38071">issues.joomla.org/tracker/joomla-cms/38071</a>.</sub>

**Comment by richard67** [comment]
Thanks all.

**Pull request merged**
