### PR TITLE
com_cache (cache view) implement searchtools and ordering

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the search tools (filter, order, etc) to com_cache cache view.
###### Before PR

image
###### After PR

image
#### How to test
1. Install latest staging
2. Go to System -> Global configuration and enable some type of caching
3. Naviagt in the backend and in the frontend
4. Go to System -> Clear Cache, you will see some cached items in "site" and in "administrator"
5. Apply this PR
6. Go to System -> Clear Cache
7. Test the new searchtools (search, filter, client selector, ordering, pagination)

### CODE REVIEW

**Comment by richard67** [comment]
@andrepereiradasilva I just tested this and everything works except of the search box: Whatever I type in and enter, I always see all cache groups in the list and no message that no records found in case if I type in some stuff which should not be found. What shall it be good for? To search for a cache group name? Currently it seems to be good for nothing and have no effect. Do we really need a search box here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on d09486f503b8be7a6e78590cbc998df4bb0e68cb<br /><br />Works as expected except the search box as Richaerd67 mentionned.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Comment by ghazal** [comment]
@andrepereiradasilva
And a huge thanks for all your work.

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on d09486f503b8be7a6e78590cbc998df4bb0e68cb<br /><br />Search box does not work, see my previous comment and confirmation of this in test result from @ghazal.

Everything else works.

Setting my test result to not successful so @andrepereiradasilva is able to check this before someone else sets a test result to success and we get a (too early) RTC here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ups, thanks forget to check that, will check when i have time.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5f391b9a4b062f33d91ba2e29666b5d6b07d2ce2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 5f391b9a4b062f33d91ba2e29666b5d6b07d2ce2<br /><br />Search box OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9121">issues.joomla.org/joomla-cms/9121</a>.</sub>

**Pull request merged**
