### PR TITLE
[4.0] Move mod menu script to es6

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue NAN .

### Summary of Changes
Use current javascript

### Testing Instructions
Menu still works fine

### Documentation Changes Required
No

PS. The admin menu is still NOT ACCESSIBLE and the current state should not be considered nowhere near production ready... Eg: this needs to be done properly, but in another PR

PS. 2 The other files touched here due to eslint... BTW before compiling eslint should ALWAYS run and prevent compiling if any file fails linting

### CODE REVIEW

**Comment by brianteeman** [comment]
Instead of saying it's not accessible it would really help if you opened an issue with information exactly what the issues are.

**Comment by dgrammatiko** [comment]
> it would really help if you opened an issue

That's not my way, I do PRs not issues

**Comment by brianteeman** [comment]
Well how does anyone know what the problem is?

**Comment by dgrammatiko** [comment]
Well a simple comparison with the ARIA best practices example : https://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html will reveal all the shortcomings. Still I will not create an issue, I plan to do a PR...

**Comment by dgrammatiko** [comment]
@rdeutz can you restart the tests here?

**Pull request merged**
