### PR TITLE
[4.0] Missing field class

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Fixes missing field class in Redirect form.

### Testing Instructions

Go to Redirects.
In configuration enable `Advanced Mode`.
Go to create new Redirect.
Inspect `Redirect Status Code` field.

### Actual result BEFORE applying this Pull Request

It's a text field.

### Expected result AFTER applying this Pull Request

It's a select list with predefined options.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4f98fd373357cd9f3ce8082d60a90054f8f4054d

### with pr:

Screen Shot 2020-10-09 at 09 14 44


### without pr:

95553776-6b8b2380-0a0f-11eb-8b6b-aaf81e66babd


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31015">issues.joomla.org/tracker/joomla-cms/31015</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4f98fd373357cd9f3ce8082d60a90054f8f4054d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31015">issues.joomla.org/tracker/joomla-cms/31015</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31015">issues.joomla.org/tracker/joomla-cms/31015</a>.</sub>

**Comment by ohrionmartin** [comment]
I have tested this item :white_check_mark: successfully on 4f98fd373357cd9f3ce8082d60a90054f8f4054d<br /><br />System Information
=============
php: Linux orion 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
dbserver: mysql
dbversion: 8.0.21-0ubuntu0.20.04.4
dbcollation: utf8mb4_0900_ai_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.4.3
server: Apache/2.4.41 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 4.0.0-beta4 Beta [ Mañana ] 15-September-2020 13:46 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31015">issues.joomla.org/tracker/joomla-cms/31015</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
