### PR TITLE
[4.1] gitignore update

### PR DESCRIPTION
**Pull request by brianteeman**
Post the move to placing css files in the media folder this pr updates the gitignore.

No point in ignoring non-existent files ;)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2660ff979ce90241da5fda6307d18fc147ba6aae<br /><br />By review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36895">issues.joomla.org/tracker/joomla-cms/36895</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 2660ff979ce90241da5fda6307d18fc147ba6aae<br /><br />Tested by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36895">issues.joomla.org/tracker/joomla-cms/36895</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36895">issues.joomla.org/tracker/joomla-cms/36895</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
np

**Pull request merged**
