### PR TITLE
Fixed wrong redirection by menu item

### PR DESCRIPTION
**Pull request by jjdelvalle**
An attempt to fix issue #4934 
#### Steps to reproduce the issue
1. create an article for registered users only,
2. create a menu item to aforementioned article,
3. go to the front-end of the site and log in,
4. access the article through the menu item,
5. log out,
6. click menu item.
#### Expected result

Get error explaining I'm not authorized to access the article since I'm not logged in.
#### Additional Information

Problem seemed to only be happening with Firefox.

Make sure to use an incognito/private browsing window to ensure that neither cookies nor the cache will affect the testing.

If you try accessing the article without ever having logged in, you'll get what was described in the "Expected result" section, so it's the logging in that's causing this behaviour after logging out.

This PR deals with the problem making the logout not spit out a "permanently moved" code.

### CODE REVIEW

**Comment by clinchergt** [comment]
@yireo and @roland-d: sorry for taking so long. I read your comments and decided to check further. I've updated the PR with a, imo, better fix.

Apparently, that true I removed was returning a 301 code (permanently moved). I'm guessing Firefox and IE handle this differently from Chrome, so that's why it wasn't happening on both. However, even if they do handle it differently, this redirect does *not* warrant a 301 code since the page hasn't been moved.

See also: https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/application/src/AbstractWebApplication.php#L258

I'd appreciate a PR review and some testers :D

**Comment by jissereitsma** [comment]
(I'm the same guy as @Yireo) I checked the PR and it looks dead-simple to me. Next, I tested it myself to see the difference. Without the patch a 303 code is sent, with the patch a 301 code is sent. Looks fine to me!

**Comment by clinchergt** [comment]
@infograf768: I'd appreciate your input here as well since you were also part of the discussion here: https://github.com/joomla/joomla-cms/issues/4934
Thanks!

**Comment by clinchergt** [comment]
Hey @crystalenka and @RCheesley could I get you guys to test this fix once again? I'd appreciate it. Thanks!

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5019">issues.joomla.org/joomla-cms/5019</a>.</sub>

**Pull request merged**
