### PR TITLE
[imp] Adding a dropdown with flags display in language switcher

### PR DESCRIPTION
**Pull request by infograf768**
Redo because of a conflict in https://github.com/joomla/joomla-cms/pull/9084

This improvement adds a new parameter to let display a bootstrap dropdown with flags and language names instead of the older dropdown. It is B/C. Test on Protostar. Beez3 is untouched by adding an override.
It was requested by many users on the forums.
Until now choosing dropdown display we would get:
screen shot 2016-02-08 at 12 17 43

---

<b>New parameters in the language Switcher</b>

Use simple dropdown (as in the past)
screen shot 2016-02-10 at 09 54 14

Yes to Flags for dropdown
screen shot 2016-02-10 at 09 56 19

Do not use dropdown as well as do not use Image flags
screen shot 2016-02-10 at 09 57 46

No to dropdown and yes to Image flags
screen shot 2016-02-10 at 09 58 49

---

Results of the new type of dropdown in frontend (other types are unchanged)

screen shot 2016-02-08 at 12 08 10

screen shot 2016-02-08 at 12 11 04

if choosing Yes to decrease line height:
screen shot 2016-02-08 at 12 12 17

@andrepereiradasilva 
@dgt41 
@richard67

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2ddec62bc687b479e38a69e2b04f971719020c35<br /><br />Tested with success all possible combinations and also for RTL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 check this:

1. Set only `Dropdown` to Yes. Result:
image

2. Now set `Dropdown` to No then, set `Use Image Flags` to Yes and finally set `Dropdown` to Yes. Result:
image

Why this happens?
Because the showon says `[OR]image:1`, image is the `Use Image Flags` and although it's hidden in the second scenario, is netherless setted to Yes, so it will appear even if the dropdown is set to Yes (dropdown:1).

**Comment by richard67** [comment]
I have not tested this item.<br /><br />@infograf768 I can confirm what @andrepereiradasilva mentioned in his previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by infograf768** [comment]
@andrepereiradasilva 
what is the solution?

**Comment by andrepereiradasilva** [comment]
Does this work: `dropdown:0[OR]dropdownimage:1` ?

Shows `Active language` if `Dropdown` = No OR `Use Flags For Dropdown` = Yes

**Comment by infograf768** [comment]
@andrepereiradasilva 
Right on! Thanks. Should be OK now.

@richard67 

Please confirm.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on aa4c76586331b183b64539d5eeb251395054c622<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by richard67** [comment]
@infograf768 I am not sure if it is Ok or not now after the latest commit.

The option "Active Language" is shown if neither dropdown nor image flags are used, i.e. only text links, or if the drowpdown is used with flags, or if image flags (i.e. no dropdown, no text links) are used. But if the dropdown is used without flags, the option is not shown.

But in opposite to the tooltip for this option, it is not only adding a class to the link, it also decides whether the active language is among the selectable options in the dropdown or not.

And this would make also sense for a drop down without flags.

As it is now, it is not consistent between dropdown with flags and dropdown without flags.

Either this has technical reasons (because duifferents kinds of dropdown in these 2 cases), or it has historical reasons (because was like this before), but as I tried to explain it is not logical/consistent and so may cause issues in the tracker and support requests in forums forever and ever.

From my point of view, the option "Active Language" makes sense for all kinds of links, i.e. text links only, flags only, or any kind of dropdown, and so should not have any showon condition but be shown always, and the tool tip for this option maybe should be changed or extended.

So in principle I could text this PR with success now because it does what is described and what it shall do.

But maybe you agree with me and wanna change that, too?

Please advice if I shall set my test result to OK or if I shall wait for your decision and any further commits.

@andrepereiradasilva What do you think about it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by richard67** [comment]
P.S.: @infograf768 I just see the showon of the option "Active Language" fits to the code in modules/mod_languages/tmpl/default.php, so if it shall be changed because of the inconsistency I mentioned in my previous comment, it will be necessary to change both the showon condition and the code in modules/mod_languages/tmpl/default.php.

Otherwise, if you are OK with how it is now, let me know and I set my test result to success.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aa4c76586331b183b64539d5eeb251395054c622<br /><br />@infograf768 Despite of the inconsistency I mentioned in my previous 2 comments, I decided to set the test result to success because all works now as intended by you, and I can live with it.

If we later, after release, will see in forums or here that people are confused by the complexity of the options and their interdependencies and the resulting behavour of the module, someone (e.g. me if I am available) can make a new PR.

So or tho this PR here is a great improvement and should go into 3.5.0, if this is possible because languages not frozen yet.

Thanks a lot for your work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by infograf768** [comment]
As I stated in the former pr, when we use a simple drodown, it is a simple select list and Active Language parameter is useless in this case as it always displays the active language.

**Comment by richard67** [comment]
@infograf768 Yes, I understand this meanwhile.

**Comment by infograf768** [comment]
@andrepereiradasilva 
We need another successful test here to get it RTC. :smiley:

**Comment by andrepereiradasilva** [comment]
i already tested. Was 2 tests.

**Comment by infograf768** [comment]
Oops, did not see. Thanks both for testing.

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9095">issues.joomla.org/joomla-cms/9095</a>.</sub>

**Comment by richard67** [comment]
Hmm, if we say it was a bug and not by design that the language switcher did not have any flags in the dropdown before, could this go into 3.5.0 then?

Ok, am joking with the bug, but it really would be nice.

**Comment by infograf768** [comment]
@rdeutz 
This was merged in staging while the milestone is 3.6.0
Is it a mistake?

**Comment by brianteeman** [comment]
No it is correct. the next release is now 3.6 there will be no 35.2

On 2 May 2016 at 07:42, infograf768 <notifications@github.com> wrote:

> @rdeutz <https://github.com/rdeutz>
> This was merged in staging while the milestone is 3.6.0
> Is it a mistake?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9095#issuecomment-216117150>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@infograf768 see: https://developer.joomla.org/news/644-version-number-shifting.html

**Pull request merged**
