### PR TITLE
[4.0] Fix Media manager for multilingual sites

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #32288 .

### Summary of Changes
Corrects the URL for media manager

### CODE REVIEW

**Comment by infograf768** [comment]
@dgrammatiko 
Sorry, but this does not help.
I still get `GET http://localhost:8888/newfolder/joomla40/fr/administrator/undefined`

**Comment by infograf768** [comment]
Along my tests on that test site I had added 2 files in the images folder
file_example.mp4
login.svg

Deleting these solves my issue. No more GET

remains to find why...

**Comment by dgrammatiko** [comment]
> Deleting these solves my issue. No more GET

Does this happen only on multilingual or on normal sites as well?

**Comment by infograf768** [comment]
> Does this happen only on multilingual or on normal sites as well?

testing now. give me a sec

**Comment by dgrammatiko** [comment]
The media manager is missing a lot of file types:
Screenshot 2021-02-06 at 18 20 53

Updating:
- Legal Extensions (File Types): `mp4,svg,bmp,csv,doc,gif,ico,jpg,jpeg,odg,odp,ods,odt,pdf,png,ppt,txt,xcf,xls,BMP,CSV,DOC,GIF,ICO,JPG,JPEG,ODG,ODP,ODS,ODT,PDF,PNG,PPT,TXT,XCF,XLS`
- Legal Image Extensions (File Types): `svg,bmp,gif,jpg,png`
- Legal MIME Types: `video/mp4,image/svg+xml,image/jpeg,image/gif,image/png,image/bmp,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip`

**Comment by infograf768** [comment]
I have the issue when monolanguage or multilanguage when media parameters were in my test site 

Screen Shot 2021-02-06 at 18 29 03


If I leave the default params, the svg and mp4 don't show at all as placeholders in the manager and I do not have the `GET`

**Comment by dgrammatiko** [comment]
@infograf768 for starters this https://github.com/joomla/joomla-cms/blob/f8565780fc2eefea09e86071eb4d0d346f52420a/administrator/components/com_media/src/Model/ApiModel.php#L543 is not the best way to get the extension, there's a PHP native method for this https://www.php.net/manual/en/function.pathinfo.php

Also can you `var_dump($e)` or get a breakpoint here: https://github.com/joomla/joomla-cms/blob/f8565780fc2eefea09e86071eb4d0d346f52420a/plugins/filesystem/local/src/Adapter/LocalAdapter.php#L367

Sorry, I still can't replicate it

**Comment by infograf768** [comment]
The path is correctly obtained. Tested by deleting the svg.
I have no problem editing the usual files (jpg, etc.) with this PR or without it.

`var_dump($e);` gives nothing.

**Comment by Fedik** [comment]
this is bug for SVG preview , it does not have a correct preview url:
image

Media manager fail to make a preview, somewhere deep in code (client side or both sides)

**Comment by infograf768** [comment]
and same for mp4 I guess.

**Comment by Fedik** [comment]
mp4 works fine, it display "file-icon".

btw, you should not add mp4 to legal images, because it not an image :wink: 
this may be a reason if you have this bug with mp4

**Comment by infograf768** [comment]
> mp4 works fine, it display "file-icon".

nope

Screen Shot 2021-02-07 at 11 05 14

and I have `video/mp4` for mp4 in `Legal MIME Types`

but I understand that J does not like mp4 ;)

**Comment by Fedik** [comment]
yes, it because mp4 not an image.

I think the code need to be smarter, and do not crash even if user add doc,xls,pdf as "legal images". Enough to show a "file icon" or another random icon.

**Comment by dgrammatiko** [comment]
@infograf768 @Fedik I guess someone needs to do the remain tasks from https://github.com/joomla/joomla-cms/pull/31233
See my comment there https://github.com/joomla/joomla-cms/pull/31233#issuecomment-716215821

**Comment by infograf768** [comment]
hmm
we have a specific video vue
`administrator/components/com_media/resources/scripts/components/browser/items/video.vue`

and mp4 is all over the place in constants

```
/Applications/MAMP/htdocs/newfolder/joomla40/administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js:21:       const videoExtensions = ['mp4'];
/Applications/MAMP/htdocs/newfolder/joomla40/administrator/components/com_media/resources/scripts/components/browser/items/item.js:20:             let videoExtensions = ['mp4'];
/Applications/MAMP/htdocs/newfolder/joomla40/administrator/components/com_media/resources/scripts/components/browser/items/row.vue:73:       const extensionWithPreview = ['jpg', 'jpeg', 'png', 'gif', 'mp4'];
```
```
/Applications/MAMP/htdocs/newfolder/joomla40/libraries/vendor/guzzlehttp/psr7/src/MimeType.php:81:             'mp4' => 'video/mp4',
```

**Comment by dgrammatiko** [comment]
> and mp4 is all over the place in constants

The `guzzlehttp` is a composer dependency so this is something the project can't directly change. Also I have no clue if this is even used here

About the `administrator/components/com_media/resources/scripts/components/browser/items/video.vue` file this was exactly what I was referring in https://github.com/joomla/joomla-cms/pull/31233#issuecomment-716215821 The hard coded parts there are really bad
 
EDIT: One more thing here, the local adapter, as far as I understand the code, is only returning info for images: https://github.com/joomla/joomla-cms/blob/f8565780fc2eefea09e86071eb4d0d346f52420a/plugins/filesystem/local/src/Adapter/LocalAdapter.php#L325-L372

This can't be right

**Comment by Fedik** [comment]
There need to hardcode "previewable" file types, it should not depend from User config. 
So User can enter anything in to "Images", and system only do preview only for "previewable".

**Comment by dgrammatiko** [comment]
> So User can enter anything in to "Images", and system only do preview only for "reviewable".

I'm not sure that I agree here. Eg I'm the admin and I disable `.webp` I would expect the system to respect my choice and use the placeholder icon for any `.webp` image

**Comment by richard67** [comment]
> > So User can enter anything in to "Images", and system only do preview only for "reviewable".
> 
> I'm not sure that I agree here. Eg I'm the admin and I disable `.webp` I would expect the system to respect my choice and use the placeholder icon for any `.webp` image

So it needs to check both arrays, the allowed images and the previewable images, and only if it is in both it shall be previewed.

Or check the intersect of the 2 arrays only one time.

**Comment by dgrammatiko** [comment]
> Or check the intersect of the 2 arrays only one time.

I'll go for this one

**Comment by richard67** [comment]
Who of you two will make the PR? 😄

**Comment by Fedik** [comment]
> I'm not sure that I agree here. Eg I'm the admin and I disable .webp I would expect the system to respect my choice and use the placeholder icon for any .webp image

You cannot show more than browser able to show.

Add .webp and .avif to list of previewable, but they need an extra care in non supported browsers,

> Or check the intersect of the 2 arrays only one time.

It does not make sense, again you cannot show more than browser able to show.

**Comment by richard67** [comment]
@Fedik It's not about to show more than the browser can do, it's about showing less because an admin wants to exclude a certain type of images from the list of allowed.

**Comment by dgrammatiko** [comment]
> It does not make sense, again you cannot show more than browser able to show.

@Fedik it's not about the browser's capabilities, it's about respecting the admin's options. If for whatever reason they don't want to support `.gif` files these files should **not** appear in the media manager 😉

**Comment by richard67** [comment]
@Fedik That means we like your idea of the hard-coded pre-defined list, we only like to check the allowed images maintained in backend in addition, so if an image is not in both lists, we don't show a preview.

**Comment by Fedik** [comment]
> it's about respecting the admin's options

I am not talking about what is diplaied in the Media browser, admin can show any :hankey: there.

I am about render the preview. 
If Admin choose to show `png,jpg,webp,pdf,foobar` then in Media browser should be visible ALL this files, but render preview only for previewable `png,jpg,webp`, rest should stay as Icon.

**Comment by richard67** [comment]
> I am about render the preview.
> If Admin choose to show `png,jpg,webp,pdf,foobar` then in Media browser should be visible ALL this files, but render preview only for previewable `png,jpg,webp`, rest should stay as Icon.

@Fedik Then I think we want the same thing, we have just chosen different words to describe it 😄

**Comment by Fedik** [comment]
> we have just chosen different words to describe it 

Can be :smile: 

Here is pseudo code:
```
loop Image in Images:
  if can preview Image:
    show preview
  else:
    show icon

```

**Comment by dgrammatiko** [comment]
> Here is pseudo code:

Well, in that case, we need to pass from PHP a list with all the files that can have a preview. The allowed list should be used only to upload/manipulate/select a file. A simple JSON file with all the valid extensions for all file types could be passed with addScriptOptions so we don;t have to hard code things...

**Comment by richard67** [comment]
> ```
> loop Image in Images:
>   if can preview Image:
>     show preview
>   else:
>     show icon
> ```

Maybe we can do a
```
>   if can preview Image:
>     show preview
>   else if image shows a cat:
>     show preview in any case because it's soo cute
>   else:
>     show icon
```
😸

**Comment by dgrammatiko** [comment]
> show preview in any case because it's soo cute

This is debatable. Dog people might suggest their favourite pet 🤣

**Comment by Magnytu2** [comment]
Hello, I just downloaded the latest nocture version. To my great surprise, there are no more thumbnails in the media manager, and we can no longer edit the images.

Capture d’écran 2021-02-13 à 13 56 51

**Comment by dgrammatiko** [comment]
I'm closing this as it's obviously not solving the problem here

**Comment by richard67** [comment]
So shall we re-open issue #32288 ? Or open a new one because #32288 is not exactly the same issue? I‘m not really sure.

**Comment by dgrammatiko** [comment]
Maybe open an umbrella issue for all media manager issues (eg https://github.com/joomla/joomla-cms/projects)

**Comment by richard67** [comment]
There is one, but it's closed: https://github.com/joomla/joomla-cms/projects/9 ;-)

**Comment by richard67** [comment]
Anyway, creating projects is beyond my privileges. Will check what to do.

**Comment by Magnytu2** [comment]
Hello, sorry for this intervention. But the Joomshaper team had already found problems in the media manager (from memory). They had for that, realized a new media manager. Maybe we need to get closer to them to save time? It's a simple proposition.
https://youtu.be/Ks8tuxrmv24

**Comment by richard67** [comment]
Not on me to decide such things.

**Comment by dgrammatiko** [comment]
@Magnytu2 the repo is still there: https://github.com/joomla-projects/j4adminui so someone (not me) could diff and merge things

**Comment by Magnytu2** [comment]
@dgrammatiko There was another version, much easier to install. I am a fan of Joomla! and yet it is bigger mistake than I regret. Since the time everything would already be corrected.

**Pull request closed without merging**
