### PR TITLE
Logical error in the com_newsfeeds controller

### PR DESCRIPTION
**Pull request by philip-sorokin**
Please, see changes.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 6e9684d801e82c2c0ab3cfbc6c057cc1528b6047<br /><br />It just fixes a logical error. Thanks and good spot :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10705">issues.joomla.org/joomla-cms/10705</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6e9684d801e82c2c0ab3cfbc6c057cc1528b6047<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10705">issues.joomla.org/joomla-cms/10705</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10705">issues.joomla.org/joomla-cms/10705</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
