### PR TITLE
fix problem with accordions using parent option

### PR DESCRIPTION
**Pull request by Minei3oat**
Pull Request for Issue # .
### Summary of Changes

Now `accordion-toggle` of slides which where collapsed by opening an other slide in an accordion with the option parent set to the id of the accordion gets the class `collapsed`.
### Testing Instructions

For making the testing simple I've created a component :).
Download and install https://github.com/Minei3oat/com_test .
The component contains a single view with five slides. The style of the component will show `accordion-toggle`s with class `collapsed` green and without red. This makes it easy to see the difference.
Now open a slide which is not open. The open slide will close, but its `accordion-toggle` don't gets the class `collapsed` as it gets when you close the slide yourself.
After applying this patch the class `collapsed` will get asseigned.
### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
Changing the bootstrap supplied js files is not an option

**Comment by Minei3oat** [comment]
Then I don't see a posibility to fix this issue.
Bootstrap fixed this issue with the code in this PR in version 3 but updating isn't good because it is not backward compatible.

**Comment by brianteeman** [comment]
If there is no other way then it will have to be closed as a known issue

**Comment by Minei3oat** [comment]
I've did some research. It is possible to add the code with the declaration of the needed variables  
- in an other js file loaded after bootstrap (I found no suitable: There is no suitable general js file loaded and in the template.js all templates must apply this fix)
- or in the script part in the head. There it could be added once by `JHtmlBootstrap` if it is needed.

Is the second one an option?

**Comment by Bakual** [comment]
Using JHtmlBootstrap should be fine.

**Pull request closed without merging**
