### PR TITLE
[4.0] Additional fields available to display in Contact Articles

### PR DESCRIPTION
**Pull request by AndySDH**
The Joomla 4 re-do version of this: https://github.com/joomla/joomla-cms/pull/14671

### Summary of Changes

This adds the ability to display images and introtext fields for articles in contact pages.

Despite not being used in the default core view, this is useful to make the introtext and images fields available at your disposal to use in overrides.

### Testing Instructions

No need to.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on f8d2c84acefb4ab55ed654e8e5e3673a4296d05c<br /><br />works as advertised ;) personally see no reason not to include fulltext but this is a great addition!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24897">issues.joomla.org/tracker/joomla-cms/24897</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 99fc3f71719e07f05563b78ca2e1c1740d8c6e0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24897">issues.joomla.org/tracker/joomla-cms/24897</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24897">issues.joomla.org/tracker/joomla-cms/24897</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
