### PR TITLE
[3.9] fix typo in com_privacy

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

descending -> ascending

### Testing Instructions

.

### Expected result

ascending

### Actual result

descending

### Documentation Changes Required

.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cfc28d745ae2922b1e3762df97e0edd3f9398f44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22029">issues.joomla.org/tracker/joomla-cms/22029</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cfc28d745ae2922b1e3762df97e0edd3f9398f44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22029">issues.joomla.org/tracker/joomla-cms/22029</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22029">issues.joomla.org/tracker/joomla-cms/22029</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
