### PR TITLE
[4.0] Remove closest and matches polyfills

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #25186

### Summary of Changes

This removes the custom polyfills for the `closest()` and `matches()` methods and replaces with the the native JS methods

### Testing Instructions

1. Ensure you can unpublish a module in the admin dashboard and it's removed
2. Ensure subform fields work as expected
3. Ensure the sidebar menu works the same as before

Or:

Code review

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by C-Lodder** [comment]
@wilsonge Just an FYI, `closest()` isn't supported in IE11, so if you still expect frontend JS to work in IE11, then you may want to revert this.

**Comment by Quy** [comment]
To reproduce, go to Global Configuration > Users > Email Domain Options,  click + icon.

> TypeError: row is null

> /media/system/js/fields/joomla-field-subform.js:107

> row = row.closest('joomla-field-subform') === that ? row : null;

**Comment by wilsonge** [comment]
@Quy what browser is that in? I'm not too fussed about dropping IE11 support I don't think at this point.

**Comment by Quy** [comment]
Firefox 75.0 Windows 10

**Comment by C-Lodder** [comment]
@Quy I'll look into this now anf fix. Thanks for reporting.

@wilsonge Can you please make a dedicated decision about IE11

**Comment by C-Lodder** [comment]
@Quy  https://github.com/joomla/joomla-cms/pull/28753

**Comment by wilsonge** [comment]
Started going through the full requirements list two weeks ago to get formal approval from production. Right now my intention is no ie11 support. But that’s still to be fully confirmed based on their vote

**Pull request merged**
