### PR TITLE
Update en-AU installation file

### PR DESCRIPTION
**Pull request by brianteeman**
Update en-AU installation language file to be in sync with recent changes

### CODE REVIEW

**Comment by Bakual** [comment]
Merged from review

**Comment by brianteeman** [comment]
@Bakual I can do en-CA and en-US as well but they need a bit more work as they are really out of date. Should i do it?

**Comment by Bakual** [comment]
@brianteeman There is @Stevec4 who is supposed to do it. He did some updates for J3.5.0.
However I think it should be fine if you help as well.

**Comment by brianteeman** [comment]
@bakual I have done them both<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10477">issues.joomla.org/joomla-cms/10477</a>.</sub>

**Comment by Stevec4** [comment]
Thanks guys the files should have been good up to 3.5. Missed the notice that there were changes to be done to the install files for 3.6

**Comment by Bakual** [comment]
@Stevec4 I've merged them all from Brian. If you see anything amiss, feel free to send your updates the usual ways :smile:

**Comment by Stevec4** [comment]
Will do Thomas
thank you.

**Pull request merged**
