### PR TITLE
Remove trailing whitespaces from com_tags xml files

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue # .

### Summary of Changes
Only remove trailing whitespaces in xml files.
In one file a new line was added at end of file.

### Testing Instructions
Merge by code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 09bf596402f321638ea0822e1496d7fb694165c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22021">issues.joomla.org/tracker/joomla-cms/22021</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09bf596402f321638ea0822e1496d7fb694165c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22021">issues.joomla.org/tracker/joomla-cms/22021</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22021">issues.joomla.org/tracker/joomla-cms/22021</a>.</sub>

**Comment by zero-24** [comment]
Thanks!

**Pull request merged**
