### PR TITLE
[4.3][GUIDEDTOURS] Move code from helper to model

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR move the code which is used to update language of steps belong to a tour from Helper to Model for two reasons:

- In model, we have database object and ready to use, unless in Helper, we have to use Factory::getDbo() to get database object (we are trying to move a way from using the static methods from Factory)
- I believe that a **doing something operation**, especially update data from database should be a task of model, not something for Helper

### Testing Instructions
1. Use Joomla 4.3 nightly build or a Joomla 4.3 installation which has Guided Tours available
2. Edit a tour, save it, make sure nothing broken

### Actual result BEFORE applying this Pull Request
Works.

### Expected result AFTER applying this Pull Request
Works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 7da46542084f677befe852b7e4347fda3b6c2f8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40015">issues.joomla.org/tracker/joomla-cms/40015</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 7da46542084f677befe852b7e4347fda3b6c2f8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40015">issues.joomla.org/tracker/joomla-cms/40015</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40015">issues.joomla.org/tracker/joomla-cms/40015</a>.</sub>

**Comment by obuisard** [comment]
Thank you Tuan @joomdonation !

**Comment by joomdonation** [comment]
Thanks Olivier !

**Pull request merged**
