### PR TITLE
CodeMirror 5.7

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
There's nothing much of interest to Joomla users in this update but anyway, CodeMirror is updated.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 290c56bee46885d4939f04675daf2d79e5ab4867<br />Thanks @okonomiyaki3000 CodeMirror still works as expected here :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7974">issues.joomla.org/joomla-cms/7974</a>.</sub>

**Comment by zero-24** [comment]
### How to test

- Set the codemirror as default editor (Global Configuration)
- apply this patch
- confirm the template editor still works
- confirm creating and editing of an article still works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7974">issues.joomla.org/joomla-cms/7974</a>.</sub>

**Comment by patjun** [comment]
I have tested this item :white_check_mark: successfully on 290c56bee46885d4939f04675daf2d79e5ab4867<br /><br />Tested the editor in article and in template editor. The editor works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7974">issues.joomla.org/joomla-cms/7974</a>.</sub>

**Comment by Coscha** [comment]
I do it too and its look like fine.

It works in article and template files with change plugin settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7974">issues.joomla.org/joomla-cms/7974</a>.</sub>

**Comment by SniperSister** [comment]
3 successful tests, setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7974">issues.joomla.org/joomla-cms/7974</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @okonomiyaki3000! Merged.

**Pull request merged**
