### PR TITLE
[4.0] Remove double variable $spellcheck in field layouts

### PR DESCRIPTION
**Pull request by shur**
The $spellcheck variable must be declared once and have a boolean type.

### Testing Instructions
code review

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e9eb75fc28ce31d25b06465e2911dc7c99d81ccf<br /><br />good find. 
It seems that this occours also in lots of other layouts.
I am asking myself if an alphabetical order of variables is possible? I t took me quite a time to see the duplicates becausethey are not alpha-ordered.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31862">issues.joomla.org/tracker/joomla-cms/31862</a>.</sub>

**Comment by brianteeman** [comment]
> I am asking myself if an alphabetical order of variables is possible?

Fairly easy to do one night sat in front of the tv if there is value to it

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e9eb75fc28ce31d25b06465e2911dc7c99d81ccf<br /><br />Tested successfully in Beta6-dev of 5 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31862">issues.joomla.org/tracker/joomla-cms/31862</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31862">issues.joomla.org/tracker/joomla-cms/31862</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
