### PR TITLE
Added Serializable interface and methods to JTable. Fixes #16185.

### LINKED ISSUE #16185: Crash in core cache lib when debug enabled
During a recent piece of work, I enabled the Joomla debug mode. With debug activated, I found that certain pages within my site started giving me an error dump screen with the following error:

> Exception
>  Serialization of 'Closure' is not allowed
> .../libraries/joomla/cache/controller/callback.php:184

For ref, line 184 looks like this:

    $this->cache->store(serialize($data), $id);

The error occurs when I view a page that shows a K2 category list. I don't believe that K2 is directly at fault here though because K2 has not had any version updates lately and debugging has worked just fine previously. It also works fine when debug mode is switched off, so it's something specific to debug.

Things that have changed on my site since the last time I used debug include the 3.7.0 and 3.7.1 updates, and various relatively minor extension updates.

I have done some debugging and used `print_r()` to dump the contents of `$data` into a file. It does indeed contain a number of closures within the `callStacks` array. (I guess that the `callStacks` array is only kept in debug mode, hence why the error only occurs with debug enabled?)

My dump file is 90MB in size, so I won't attach it here, but it shows that the closures which are triggering the error are at:

> libraries/cms/component/helper.php:443
> libraries/cms/plugin/helper.php:298
> libraries/cms/menu/site.php:72
> libraries/cms/library/helper.php:156

Looking at the code for all of these, I see that they all had similar changes made for the 3.7.0 release to wrap a DB query in a closure.

I would suggest that something needs to be corrected here in core. The obvious quick fix would be to remove the closures (maybe convert them into regular methods), but that wouldn't be good long-term, and would mean that we couldn't use closures anywhere. A better fix would be to sanitise the `callStacks` array so that closures make it don't blow up when we try to serialize. Alternatively if serializing the stack for the cache is going to be a problem, maybe just remove `callStacks` from the data being cached?

### Steps to reproduce the issue

I haven't had time to set up an isolated system to find a minimum configuration to reproduce this issue, but it seems like it ought to be fairly easy to create a scenario that triggers it.

* Set up a Joomla instance
* Build a page that will result in a call to one or more of the closures listed above.<br>
    (in my case it is a K2 category listing page, but I suspect it could be triggered in plenty of other ways)
* Switch Debug on.
* Navigate to your page.

### Expected result

The page ought to render normally (but with the debug block at the foot)

### Actual result

Error page showing exception and line where it occurred.

### System information (as much as possible)

Joomla 3.7.1 with a bunch of extensions installed and debug mode switched on.

### PR DESCRIPTION
**Pull request by Spudley**
Pull Request for Issue #16185 .

### Summary of Changes

Added Serializable interface and methods to JTable. Excluding the DB object from serialization, because under some circumstances the DB object may contain closures; these are unserializable, and thus caused a crash when serializing JTable.

### Testing Instructions

* Install Joomla any of 3.7.0 / 3.7.1 / 3.7.2.
* Install K2 extension.
* Create a K2 category and add some articles to it.
* Create a menu entry for the category view.
* Navigate to the menu entry: It should work.
* Turn on Joomla's debug mode.
* Navigate to the menu entry again: It will crash with `Serialization of 'Closure' is not allowed`.
* Now install the patch.
* Keep debug mode enabled.
* Navigate to the menu entry again: It should now work correctly.

### Expected result

See above: The category view should work correctly in debug mode.

### Actual result

Without the patch, navigating to the category view in debug mode crashes and gives the following error:

> Exception
> Serialization of 'Closure' is not allowed
> .../libraries/joomla/cache/controller/callback.php:184

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please see the comments by @mbabker on this at #16185

**Comment by franz-wohlkoenig** [comment]
Comment of mbabker sounds like "no Core Issue" > close, @brianteeman?

**Comment by brianteeman** [comment]
i would leave it to @mbabker or @rdeutz to make that decision

**Comment by rdeutz** [comment]
In some way this follows the advice Michale gave, but I have my doubts if we should cache table data this way. I might miss the point but what is when we cache the user table data, would that not allow to get the user data out of the cache and maybe misuse it. Maybe I am too paranoid :-)

**Comment by mbabker** [comment]
Personally I think caching a database related object (JTable, JDatabaseDriver) is asking for trouble and you're better off caching just the record data.  Unfortunately there isn't an eloquent way to get just the record data (`get_object_vars()` can work as long as you aren't running it from within the class and the only public properties are the ones created with the field structure).

The fix here is technically valid, anyone who is doing something resulting in the serialization of JTable objects avoids running into a scenario where the database driver gets included into the mix, and that's in general not a good object to serialize.

**Comment by Spudley** [comment]
wondering why the appveyor build has been stuck in 'pending' for two days... ??

**Comment by Spudley** [comment]
@mbabker, @rdeutz -- I'm not totally clear from your comments here whether you're falling in favour of this PR or against it?  I'm hoping the fact that it hasn't been closed means you're still considering it?  :)

**Comment by Kev1n337** [comment]
I have tested this item :red_circle: unsuccessfully on 82f9364c9ec5afb3072ed3e9be96211c17a11070<br /><br />I wasn't able to reproduce this issue following these steps:
* Installed Joomla 3.7.0
* Installed K2 extension
* Created K2 Categories
* Created new items and attached them to the new category
* Created menu item directing to the articles in this category
* navigated to this view
* It works
* After enabling "Debug System" in Global configuration, it still works the same as before

@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16216">issues.joomla.org/tracker/joomla-cms/16216</a>.</sub>

**Comment by brianteeman** [comment]
Note. K2 had a lot of updates last week so "maybe" they changed something.

**Comment by ghost** [comment]
> Note. K2 had a lot of updates last week so "maybe" they changed something.

@Spudley can you please at this?

**Comment by jwaisner** [comment]
@Spudley are you able to update this PR if this is still something that needs resolved?

**Comment by Spudley** [comment]
> @Spudley are you able to update this PR if this is still something that needs resolved?

Hi @jwaisner. I am no longer maintaining the Joomla system that was exhibiting the bug and it's been two years since I last thought about it, so I'm not really in a position to follow it up any longer. Thank you.

**Comment by jwaisner** [comment]
Closing PR and reopened issue report #16185 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16216">issues.joomla.org/tracker/joomla-cms/16216</a>.</sub>

**Pull request closed without merging**
