### PR TITLE
Reattempt 8024

### PR DESCRIPTION
**Pull request by mbabker**
This fixes the bad merge of #8024 by reverting https://github.com/joomla/joomla-cms/commit/88fb40b7ad4bbc2d525c63cadfa8b62e1307fb96 and reapplying the diff from the pull request.

### CODE REVIEW

**Comment by infograf768** [comment]
What shall we check for when testing?

**Comment by Bakual** [comment]
@wilsonge @roland-d As you were involved in the original merge, please review.

**Comment by mbabker** [comment]
> What shall we check for when testing?

This should be mostly review and validation that things are in the same state they were before the reverted commit.  The diff shows a majority of the changes are code style related or replacing calls to the deprecated `$app->getCfg()`

**Comment by roland-d** [comment]
@mbabker Thanks for the PR, I have reviewed the changes and they look good to me. @wilsonge You want to go over it as well? After that we can merge this if all looks good to you.

**Comment by wilsonge** [comment]
Merged on review

**Pull request merged**
