### PR TITLE
[5.2] SEF: Enable new SEF options for new installations

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This PR enables the new SEF features for new installations by default. It also changes the value of the trailingslash option. In Joomla 6.0 we want to remove the "Do nothing" option again and it would be stupid to then have to switch between the values 1 and 2 instead of 0 and 1.

### Testing Instructions
Codereview?

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Hackwar** [comment]
No, because the default for existing installations should be the current behavior, not the new behavior. If I set the default to the value in the installation SQL, then a user editing the SEF plugin, not changing anything and then saving would have the new behavior.

**Comment by SniperSister** [comment]
I have tested this item :white_check_mark: successfully on d03b7bb39cd10f4f0d87846ad53965e76f37638b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43024">issues.joomla.org/tracker/joomla-cms/43024</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f64664bb437867b1a421e08618c03365c66b9a7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43024">issues.joomla.org/tracker/joomla-cms/43024</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43024">issues.joomla.org/tracker/joomla-cms/43024</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Pull request merged**
