### PR TITLE
[5.0] Smart Search: Fixing taxonomy filter handling

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #39718 .

### Summary of Changes
When I refactored the taxonomies to be a nested set, I overlooked this part. This means that nested taxonomies in filters don't work.

### Testing Instructions
1. Create an article in a category which is at least on the second level.
2. Create a filter which only searches in that articles parent category. 
3. Go to the frontend and search for a word in that article. You will get the article as result.
4. Add &f=[filter-id] to the URL to only show results from our category.
5. Notice that you get no result at all!
6. Apply changes.
7. Only the article appears again.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

@crystalenka can you check if this fixes your issue?

### CODE REVIEW

**Comment by crystalenka** [comment]
Thank you!! Will test shortly.

**Comment by crystalenka** [comment]
I have tested this item :red_circle: unsuccessfully on 6647838bd9ce51942843567ee8e4d5a66e688be0<br /><br />Unfortunately this does not fix the problem in a multilingual environment. :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39751">issues.joomla.org/tracker/joomla-cms/39751</a>.</sub>

**Comment by EJBJane** [comment]
Looks good but it doesnt work. Give it a try. Search for ricotta in for example Pasta & Risotto recipes. 
See as example:  https://www.dolcevia.com/nl/italiaanse-recepten/pasta-gnocchi-risotto/4501-cannelloni-van-grano-arso-met-ricotta-en-spek-in-honingsaus
Search is on the right / sidebar.

**Comment by Hackwar** [comment]
@EJBJane without having more knowledge about your setup, it is difficult to judge your report. Yes, you don't get a result when searching for ricotta, but I also don't know what you have in the filter that is activated on your search. If you want me to debug that, please contact me on the Joomla Mattermost.

**Comment by EJBJane** [comment]
> @EJBJane without having more knowledge about your setup, it is difficult to judge your report. Yes, you don't get a result when searching for ricotta, but I also don't know what you have in the filter that is activated on your search. If you want me to debug that, please contact me on the Joomla Mattermost.

I have to take this back, it was my fault, there was accidently an author selected for the results. This is why the search results didnt work, because there was no recipe with that author. I'm sorry!

**Comment by EJBJane** [comment]
It thus does work for me.

**Comment by Hackwar** [comment]
I'm sorry, I accidently changed the base branch to 4.3-dev and then updated the branch with the latest changes. I actually didn't want to do that. The forced push only restores the previous state. So, we only need one more test to get this fix on the road.

**Comment by Hackwar** [comment]
Since there wont be any more patch releases in 4.2, I'm moving this over to 4.3-dev.

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on 6245d12d30176adcaecf208a7e6f8347166fcbee<br /><br />This fixed it in multilingual along with the second PR you linked. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39751">issues.joomla.org/tracker/joomla-cms/39751</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39751">issues.joomla.org/tracker/joomla-cms/39751</a>.</sub>

**Comment by richard67** [comment]
Does this also fix issue #40495 ?

**Comment by Hackwar** [comment]
Yes

**Comment by HLeithner** [comment]
thanks

**Comment by crystalenka** [comment]
I guess that answers that it definitely won't go in earlier, but could either of you please help me understand why? This is a bug and filters straight up don't work without the fix.

**Comment by HLeithner** [comment]
No that's not the answer and completely independent, this fix can still be back-ported @sdwjoomla and @obuisard can do this or ask for a pr.

**Comment by obuisard** [comment]
Ok, this PR lost the RTC label and therefore got overlooked and I do apologize for it Hannes @Hackwar. It is indeed a bug that should be fixed in 4.3 in our opinion. I will backport the changes so you don't have to go through this again.

**Comment by artur-stepien** [comment]
Hello. I would like to ask if this will come to 4.3 at all?

**Comment by Quy** [comment]
Yes in 4.3.5. See #40687.

**Comment by artur-stepien** [comment]
> Yes in 4.3.5. See #40687.

Thanks for the info.

**Comment by richard67** [comment]
> Yes in 4.3.5. See #40687.

There will not be a 4.3.5. it will be 4.4.0 stable, release is Tuesday next week.

**Pull request merged**
