### PR TITLE
typo

### PR DESCRIPTION
**Pull request by brianteeman**
can be merged on review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 37f09ba349e8ace549005fd5f529def6b632d556<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19691">issues.joomla.org/tracker/joomla-cms/19691</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 37f09ba349e8ace549005fd5f529def6b632d556<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19691">issues.joomla.org/tracker/joomla-cms/19691</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19691">issues.joomla.org/tracker/joomla-cms/19691</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
