### PR TITLE
[com_ajax] Change modules check

### PR DESCRIPTION
**Pull request by Septdir**
### Summary of Changes
Change modules check to ignore the Menu Assignment menu in com_ajax

### Testing Instructions
* Install Joomla 3.8.5
* Download and install this test module [mod_ajaxtest.zip](https://github.com/joomla/joomla-cms/files/1777445/mod_ajaxtest.zip) (or you can use your module)
* Go to modules manager and then go to mod_ajaxtest settings 
* Сheck Module Assignment set No pages and save module
* Apply this path
* Return to the mod_ajaxtest settings and you will see a message about a successful request

### Expected result
The request will be successful regardless of the  Menu Assignment 

### Actual result
The request is executed with an error  
Module mod_ajaxtest is not published, you do not have access to it, or it's not assigned to the current menu item.

### What is it for
If you honestly bothered each time to pass the itemID when I need use com_ajax in modules, if the module is form is still quite tolerable (you can make a hidden field), then in all other cases you have to be wiser.

And if you need com_ajax in the module settings. For example, some kind of field, then you have to do a third-party file handler

### CODE REVIEW

**Comment by mbabker** [comment]
This is going to break caching this query result...

**Comment by Septdir** [comment]
@mbabker hm.. Then maybe so
https://github.com/joomla/joomla-cms/pull/19818/commits/e9eee7bf6e8d1777da2ffe29f7d422b77de5b5a5

I change check inside com_ajax

**Comment by mbabker** [comment]
On a quick glance that seems fine.

**Comment by schnuti** [comment]
I have tested this item :white_check_mark: successfully on e9eee7bf6e8d1777da2ffe29f7d422b77de5b5a5<br /><br />Works with my own a bit complicated ajax-module. Translations using the PHP DeepLy library for the DeepL API.

I wondered why it didn't work until I found the evil in the module check. I was happy to find this fix. Thanks! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19818">issues.joomla.org/tracker/joomla-cms/19818</a>.</sub>

**Comment by pavluk** [comment]
I have tested this item :white_check_mark: successfully on e9eee7bf6e8d1777da2ffe29f7d422b77de5b5a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19818">issues.joomla.org/tracker/joomla-cms/19818</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
