### PR TITLE
Fixed rate button misalignment

### PR DESCRIPTION
**Pull request by JackKellyUK**
Pull Request for Issue #37920  .

### Summary of Changes

Added vertical align baseline class to Rate button

### Testing Instructions

- Enable the vote plugin
- Show voting (in an article or a menu item)

### Actual result BEFORE applying this Pull Request

Rate button is misaligned

### Expected result AFTER applying this Pull Request

Rate button is aligned as expected

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 5765a55d6f3c9e1f85ead7d9e62643cc23ab69ec<br /><br />See my comment above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39465">issues.joomla.org/tracker/joomla-cms/39465</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5765a55d6f3c9e1f85ead7d9e62643cc23ab69ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39465">issues.joomla.org/tracker/joomla-cms/39465</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39465">issues.joomla.org/tracker/joomla-cms/39465</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for this small but nice PR

**Pull request merged**
