### PR TITLE
[4.0] Fix filtering categories and contacts by tags

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #28008.

### Summary of Changes

Fixes filtering categories and contacts by tags in backend.

### Testing Instructions

Create some categories and contacts with tags.
Filter categories/contacts by single and multiple tags.

### Expected result

Categories/contacts filtered.

### Actual result

Categories/contacts not filtered.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
The notice is gone, however, items are not filtered.

**Comment by ChristineWk** [comment]
@Quy Confirm both. It's not successful now? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28009">issues.joomla.org/tracker/joomla-cms/28009</a>.</sub>

**Comment by SharkyKZ** [comment]
PR updated. Please test again.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 46b1667b0ce8c28edf7e83c85e8c1c4d98f8625f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28009">issues.joomla.org/tracker/joomla-cms/28009</a>.</sub>

**Comment by SharkyKZ** [comment]
Hold on, same issue exists in `com_contact`.

**Comment by SharkyKZ** [comment]
PR updated. Please test again.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 91cf05f54b85681c498ca621a027d327825c169c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28009">issues.joomla.org/tracker/joomla-cms/28009</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 91cf05f54b85681c498ca621a027d327825c169c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28009">issues.joomla.org/tracker/joomla-cms/28009</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28009">issues.joomla.org/tracker/joomla-cms/28009</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ To be honest: I have no idea how filtering by tags shall work when filtering by multiple tags. Shall the articles be shown which contain any of the tags in the filter, like it is with this PR? Or shall only articles be shown which contain all of the tags in the filter?

**Comment by SharkyKZ** [comment]
Any of the tags, same as in other components.

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
