### PR TITLE
[Deprecate _QQ_ 2] Save language overrides with escaped double quotes

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

As discussed in https://github.com/joomla/joomla-cms/issues/13421
This PR changes language overrides save to ini method so we use escaped double quotes (`\"`) instead of `"_QQ_"`.
Also adds a new method to save the language strings to a ini file so it can be easily used when needed.

### Testing Instructions

- Apply patch
- Create a new language override from Extensions -> Languages -> Overrides for the en-GB admin language with some double quotes on it (`"`). Save it, load it again and confirm if ok.
- Confirm it's saved as escaped double quote in `/administrator/language/overrides/en-GB.override.ini`.  Example: `A test with <a href=\"https://joomla.org\" target=\"_blank\">Joomla</a>`
- Manually add an override in `/administrator/language/overrides/en-GB.override.ini` with `_QQ_` and escaped quotes. Example:
```ini
JLIB_DATABASE_ERROR_DATABASE_UPGRADE_FAILED="A second test with <a href="_QQ_"https://joomla.org"_QQ_" target=\"_blank\">Joomla</a>"
```
- Confirm language override works
Ex: add to template index.php
```php
// Server side message system
$app->enqueueMessage(JText::_('JLIB_DATABASE_ERROR_DATABASE_UPGRADE_FAILED'), 'warning');

// Client side message system (click on the page to show the javascript message)
JText::script('JLIB_DATABASE_ERROR_DATABASE_UPGRADE_FAILED');
$this->addScriptDeclaration("document.addEventListener('click', function () { Joomla.renderMessages({'error': [Joomla.JText._('JLIB_DATABASE_ERROR_DATABASE_UPGRADE_FAILED')]}) });");

```

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on 56d1bc0d34cf75305c4fee01d0ac4ee1f823bad1<br /><br />Both `"_QQ_"` and `\"` are being translated as expected and quotes in overrides save as `\"`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13427">issues.joomla.org/tracker/joomla-cms/13427</a>.</sub>

**Comment by frankmayer** [comment]
I have tested this item :white_check_mark: successfully on 56d1bc0d34cf75305c4fee01d0ac4ee1f823bad1<br /><br />Code review OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13427">issues.joomla.org/tracker/joomla-cms/13427</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13427">issues.joomla.org/tracker/joomla-cms/13427</a>.</sub>

**Comment by infograf768** [comment]
warning concerning strings that would be used through js. see my comment in the specific pr.
let's first solve that one before merging this!!

**Comment by infograf768** [comment]
In any case, can you explain the reason for using `addcslashes` instead of `addslashes` ?

**Comment by andrepereiradasilva** [comment]
> warning concerning strings that would be used through js. see my comment in the specific pr.

Is not related to this PR.

> In any case, can you explain the reason for using addcslashes instead of addslashes ?

because the only thing to escape are the double quotes (`"`), ie, the ini string delimiters, the rest AFAIK is allowed in the ini file.

**Comment by infograf768** [comment]
@rdeutz 
Please merge.
Indeed we have to solve the js strings issue in the 2 existing PRs.

**Pull request merged**
