### PR TITLE
Remove files that are still there after an upgrade from 2.5 to 3.x

### PR DESCRIPTION
**Pull request by zero-24**
See: https://github.com/joomla/joomla-cms/issues/5326 by @ITPrism 

And the first PR here: https://github.com/joomla/joomla-cms/pull/5431
#### Quote from #5326

```
Hi.
I upgraded my site from J!2.5 to J! 3.3.6 and I did some comparisons with a new copy of Joomla! 3.3.6 to check the differences.

It seems, the process of upgrading misses some things and some files and folders still exist.
I am posting a list of files and folders that still exists.

**Folders**
_/administrator/components/com_config/views_
_/administrator/components/com_config/models/fields_
_/administrator/components/com_config/models/forms_

**The files in that folder**
_/administrator/help/en-GB_

**Files**
_/libraries/joomla/environment/request.php_
_/media/editors/tinymce/templates/template_list.js_

```

### CODE REVIEW

**Comment by brianteeman** [comment]
I am pretty sure that there was a decision NOT to remove geshi from
existing sites

On 12 March 2015 at 12:49, zero-24 <notifications@github.com> wrote:

> See: #5326 <https://github.com/joomla/joomla-cms/issues/5326> by @ITPrism
> <https://github.com/ITPrism>
>
> And the first PR here: #5431
> <https://github.com/joomla/joomla-cms/pull/5431>
> Quote from #5326 <https://github.com/joomla/joomla-cms/issues/5326>
>
> Hi.
> I upgraded my site from J!2.5 to J! 3.3.6 and I did some comparisons with a new copy of Joomla! 3.3.6 to check the differences.
>
> It seems, the process of upgrading misses some things and some files and folders still exist.
> I am posting a list of files and folders that still exists.
>
> **Folders**
> _/administrator/components/com_config/views_
> _/administrator/components/com_config/models/fields_
> _/administrator/components/com_config/models/forms_
>
> **The files in that folder**
> _/administrator/help/en-GB_
>
> **Files**
> _/libraries/joomla/environment/request.php_
> _/media/editors/tinymce/templates/template_list.js_
>
> **The plugin Geshi ( plg_content_geshi ) still exists.**
> _/plugins/content/geshi_
>
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/6402
> Commit Summary
>
>    - Update script.php
>    - Update script.php
>
> File Changes
>
>    - *M* administrator/components/com_admin/script.php
>    <https://github.com/joomla/joomla-cms/pull/6402/files#diff-0> (109)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/6402.patch
>    - https://github.com/joomla/joomla-cms/pull/6402.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6402>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Yes Geshi was supposed to be core supported but a bit ahead of it's time. The rest indeed should be removed

**Comment by zero-24** [comment]
@brianteeman @wilsonge i don't remove geshi here. :smile: I will update my comment

**Comment by Bakual** [comment]
I tried to create a Joomla Update package where this changes are included.
See Joomla_3.4.0-Stable-Full_Package-PR6402.zip and try to install it using the extension manager. Should work in theory :smile:

**Comment by Bakual** [comment]
Correct link so it shows right in JIssues.
http://www.bakual.ch/images/pr6402/Joomla_3.4.0-Stable-Full_Package-PR6402.zip

**Comment by webuniverse** [comment]
I installed a 2.5.11, then updated to 2.5.28, then i updated with Bakuals Package. All Files are removed, Test ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6402">issues.joomla.org/joomla-cms/6402</a>.</sub>

**Comment by Worti2** [comment]
I installed 2.5.28 and updated the installation with Bakuls Pakage. Everything is fine. All files and folders removed.
Test ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6402">issues.joomla.org/joomla-cms/6402</a>.</sub>

**Comment by Harmageddon** [comment]
Successful test, works fine!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6402">issues.joomla.org/joomla-cms/6402</a>.</sub>

**Comment by Worti2** [comment]
I forgot to mark that the test was successful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6402">issues.joomla.org/joomla-cms/6402</a>.</sub>

**Comment by Bloggerschmidt** [comment]
tested. I got a lot of errors after successful installing (see below) but **it works**.

Error on updating manifest cache: (type, element, folder, client) = (...)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6402">issues.joomla.org/joomla-cms/6402</a>.</sub>

**Comment by Bakual** [comment]
I'd say the errors are coming because you didn't use com_joomlaupdate to install the update. It's not really the preferred way to update Joomla :smile: 
It sure isn't related to this PR.

**Pull request merged**
