### PR TITLE
[4.4] Adminmenu: Fix export for child items

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #37273 .

### Summary of Changes
When exporting a menu preset in J4, the information about the tree of the menu items gets lost. This fixes that.

### Testing Instructions
1. Go to menu manager, filter by admin and create a new menu for the administrator. Make sure to select a preset to pre-populate the menu.
2. In the menu manager, select the menu and click "Download as Preset"

### Actual result BEFORE applying this Pull Request
You get a XML in return and all `<menuitem>` tags are on the same level.

### Expected result AFTER applying this Pull Request
The menuitem tags are nested properly in the way they are in the menu tree.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a4eb988be7a76205fe9914e736bc0701da122b1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43178">issues.joomla.org/tracker/joomla-cms/43178</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a4eb988be7a76205fe9914e736bc0701da122b1f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43178">issues.joomla.org/tracker/joomla-cms/43178</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43178">issues.joomla.org/tracker/joomla-cms/43178</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
