### PR TITLE
[4.0] Fix wrong line break in params value in postgresql/base.sql caused by PR #30823

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue [https://github.com/joomla/joomla-cms/pull/30823#discussion_r507974271](https://github.com/joomla/joomla-cms/pull/30823#discussion_r507974271).

### Summary of Changes

This pull request (PR) fixes a wrong line break in the params value of an insert statement which came into the installation SQL script "base.sql" for PostgreSQL with the merge of PR #30823 .

See the review comment referred above.

As you can see, system tests were passing with that erroneous line break, so it did not cause an SQL error on installation, but it is at least a code style error so to say.

### Testing Instructions

1. Check that system tests on PostgreSQL are passing in Drone.

2. Code review: Compare the part of code changed by this PR here with the same SQL statement in the same script for MySQL.

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/base.sql#L163

### Actual result BEFORE applying this Pull Request

In the script for PostgreSQL there is a line break:

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/postgresql/base.sql#L169-L170

### Expected result AFTER applying this Pull Request

In the script for PostgreSQL there is no erroneous line break, so it looks the same as the script for MySQL:

https://github.com/joomla/joomla-cms/blob/2bc9e223c9fd4cc67e7388e532eec44b9dd98e92/installation/sql/postgresql/base.sql#L169-L170

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@alikon As you are an SQL expert: Could you test by review?

@brianteeman Could you give it a test, too?

Thanks in advance.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2bc9e223c9fd4cc67e7388e532eec44b9dd98e92<br /><br />obvious fix  - by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31164">issues.joomla.org/tracker/joomla-cms/31164</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 2bc9e223c9fd4cc67e7388e532eec44b9dd98e92<br /><br />Reviewed no line break present.
passes drone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31164">issues.joomla.org/tracker/joomla-cms/31164</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31164">issues.joomla.org/tracker/joomla-cms/31164</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
