### PR TITLE
[com_cache] advanced permissions ACL reports

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #14959 .

### Summary of Changes
moved actions from config.xml to access.xml

### Testing Instructions
Users->Manage->Advanced Permissions Report 

### Expected result
after

### Actual result
before

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f52c85f295664b3ddf7054eb01d1993da4d313bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15524">issues.joomla.org/tracker/joomla-cms/15524</a>.</sub>

**Comment by brianteeman** [comment]
This PR only resolves the issue identified in #14959 for one component. there are more than com_cache effected

**Comment by franz-wohlkoenig** [comment]
Re-opened #14959

**Comment by alikon** [comment]
can you list the other's please

**Comment by brianteeman** [comment]
Just work through the select list - it is almost everything that is listed there that is NOT a traditional component like content eg Ajax, Content history, categrories etc

**Comment by alikon** [comment]
yes i see now ....

**Comment by brianteeman** [comment]
it does look like you correctly found the reason - I had failed in that search

**Comment by jsubri** [comment]
Works fine for the 2 below views, however only when the filtering is on for Cache
administrator/index.php?option=com_users&view=debuguser&user_id=851 
administrator/index.php?option=com_users&view=debuggroup&group_id=10
Without filtering we have the previous display, is it the expected behavior?

**Comment by alikon** [comment]
i'm not sure what should be the correct behavior without filtering, cause you may have different item's listed,
 so the action that can be correct for an item (for example an article)  cannot be correct  for another one (for example com_cache)

**Comment by roland-d** [comment]
@alikon Can you elaborate on what the issue is?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15524">issues.joomla.org/tracker/joomla-cms/15524</a>.</sub>

**Comment by alikon** [comment]
this pr fix the list of  permissions showed when the com_cache is selected  (i.e ony the permission related to com_cache (core.admin,core.manage))

but if you don't select a component, the list of permission showed are general permissions
permission

in addition as @brianteeman https://github.com/joomla/joomla-cms/pull/15524#issuecomment-296971862 pointed out, we stil need to manage componen'ts like com_ajax, com_contenthistory, etc.

**Comment by roland-d** [comment]
@alikon Thank you for the explanation. Are you planning to do the other components in this PR as well or are we going to get a separate PR for each extension?

**Comment by alikon** [comment]
imo the latter should be a  better way

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on d5902e1329a3b0e0d25d3f9767748c8c005134d5<br /><br />Tested on 3.8RC1, this is fixing the com_cache when filtering is on.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15524">issues.joomla.org/tracker/joomla-cms/15524</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d5902e1329a3b0e0d25d3f9767748c8c005134d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15524">issues.joomla.org/tracker/joomla-cms/15524</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
