### PR TITLE
[4.1] Install Languages columns

### PR DESCRIPTION
**Pull request by brianteeman**
The column was aligned right which means that the numbers are not aligned due to the optional presence of the information icon.

This PR changes the alignmeent to left so that the numbers are always aligned vertically

### Before
image

### After
image

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 05445a24780efe6aeba1c4df70c74e0eace21e9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37326">issues.joomla.org/tracker/joomla-cms/37326</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 05445a24780efe6aeba1c4df70c74e0eace21e9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37326">issues.joomla.org/tracker/joomla-cms/37326</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37326">issues.joomla.org/tracker/joomla-cms/37326</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
