### PR TITLE
Code mirror update

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue #19520

### Summary of Changes
See here: http://codemirror.net/doc/releases.html
Although not mentioned on the releases page, the previous version had a Typo that caused syntax coloring of PHP code to stop working. This is fixed in the new version.

### Testing Instructions
Use codemirror.

### Expected result
It will work as usual.

### Actual result
It works as usual.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
yeah so... I don't know why there are these conflicts. Can this be correct?

**Comment by okonomiyaki3000** [comment]
Why three commits? I think there's something wrong with this branch. Wait.

**Comment by okonomiyaki3000** [comment]
That's more like it.

**Comment by okonomiyaki3000** [comment]
Something is weird here. I reopened but it's still closed.

**Comment by Quy** [comment]
@mbabker Please fix tracker. Here is the error when attempting to open it:

```
422 RuntimeException
Invalid response from GitHub
```

**Comment by okonomiyaki3000** [comment]
I just pushed some meaningless commits to see if it would trigger anything but no.

**Comment by okonomiyaki3000** [comment]
So I suppose I'll abandon this one and put in a new PR.

**Comment by okonomiyaki3000** [comment]
OK, forget about this one, the real codemirror update is #19533

**Pull request closed without merging**
