### PR TITLE
[4.0] br not br/

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to update the use of br/ with the correct br

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on be5baf17acedcb8ea867b7dd266c69dc01a1c25f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33024">issues.joomla.org/tracker/joomla-cms/33024</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on be5baf17acedcb8ea867b7dd266c69dc01a1c25f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33024">issues.joomla.org/tracker/joomla-cms/33024</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33024">issues.joomla.org/tracker/joomla-cms/33024</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR. It comes from the 4.0-dev branch and will be fixed with #33026 .

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
