### PR TITLE
0 default value is not applied for custom fields

### PR DESCRIPTION
**Pull request by Denitz**
### Steps to reproduce the issue

Create custom user field of Radio type.
Set Default Value to `0`
Set Radio Values with values `0` and `1`
Edit user, save field with 0 value

### Expected result

Field is displayed with `0` option selected

### Actual result

No options are selected.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5ec6dbc7f4f0441bc95bd487577b91161de26e22<br /><br />Test on com_users<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18032">issues.joomla.org/tracker/joomla-cms/18032</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5ec6dbc7f4f0441bc95bd487577b91161de26e22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18032">issues.joomla.org/tracker/joomla-cms/18032</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
