### PR TITLE
[4.0] Fix contact and newsfeed association propagate functionality

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27037.

### Summary of Changes

Fixes table class loading.

### Testing Instructions

Set up a multilingual site with 3 languages (English, German, French).
Create a contact/newsfeed for each language.
Associate German contact/newsfeed with French and save.
Edit English contact/newsfeed.
Add an association and click `Propagate`.

### Expected result

Associated with German and French.
>All existing associations have been set.

### Actual result

>Failed propagating associations. You may have to select or create them manually.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3356d07c0b8a3f3935ebbd1eced63dce4817fa7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27984">issues.joomla.org/tracker/joomla-cms/27984</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 3356d07c0b8a3f3935ebbd1eced63dce4817fa7c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27984">issues.joomla.org/tracker/joomla-cms/27984</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27984">issues.joomla.org/tracker/joomla-cms/27984</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
