### PR TITLE
[comp & lib] Always use htmlspecialchars($str, ENT_COMPAT, 'UTF-8')

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #10399 .
#### Summary of Changes

Always use htmlspecialchars($str, ENT_COMPAT, 'UTF-8')
#### Testing Instructions

Please do a code review or test all changed files.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0898f7f7dac1cf212f5bb91be7ab62b305db4ae3<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10437">issues.joomla.org/joomla-cms/10437</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0898f7f7dac1cf212f5bb91be7ab62b305db4ae3<br /><br />it's  quite strange that travis is unhappy with @zero-24  :eyes:

tested on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10437">issues.joomla.org/joomla-cms/10437</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10437">issues.joomla.org/joomla-cms/10437</a>.</sub>

**Comment by zero-24** [comment]
I'm going to fix it tomorrow. It is an too much char per line error :(

**Comment by brianteeman** [comment]
Remove RTC for now

**Comment by brianteeman** [comment]
remove milestone for now

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10437">issues.joomla.org/joomla-cms/10437</a>.</sub>

**Pull request merged**
