### PR TITLE
[com_fields] Change the default value text of the user field

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #14362.

### Summary of Changes
Changes the default text of the user custom field.

### Testing Instructions
Create a user custom field.

### Expected result
The following default text should be shown:
> Default Users

With the tooltip:
> A comma separated list of user ids.

### Actual result
The standard text of com_fields is shown.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 78b2b23a2f7aaf21fd6e38686ad8484ed56edd1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14404">issues.joomla.org/tracker/joomla-cms/14404</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 78b2b23a2f7aaf21fd6e38686ad8484ed56edd1e<br /><br />Thank you Allon! Works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14404">issues.joomla.org/tracker/joomla-cms/14404</a>.</sub>

**Comment by laoneo** [comment]
Also RTC.

**Comment by infograf768** [comment]
please alpha order the strings. if you do not, we will have another pr...

**Comment by laoneo** [comment]
Done, but for me it looks awkward to have first the strings of another extension I'm overwriting.

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14404">issues.joomla.org/tracker/joomla-cms/14404</a>.</sub>

**Comment by Twincarb** [comment]
This language string doesn't make a lot of sense:
PLG_FIELDS_USER_XML_DESCRIPTION="This plugin lets create new fields of type 'user' in the extensions where custom fields are implemented."

This plugin allows you to create new fields of the type....

is probably better<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14404">issues.joomla.org/tracker/joomla-cms/14404</a>.</sub>

**Comment by brianteeman** [comment]
@Twincarb the string was changed in #14447

**Comment by brianteeman** [comment]
Looks like this PR is wrong a it is changing the default value for all field types not just Users see #14674

**Pull request merged**
