### PR TITLE
[4][com_finder] min value zero for Multiplier options

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #35365

### Summary of Changes
set min value zero for Multiplier options

### Testing Instructions
index content

### Actual result BEFORE applying this Pull Request
 you can input negative weight multipliers.

### Expected result AFTER applying this Pull Request
 you cannot input negative weight multipliers.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 38f90688f6a584b7ad2f86f7209da09ac8ac87da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35367">issues.joomla.org/tracker/joomla-cms/35367</a>.</sub>

**Comment by Waleet** [comment]
I have tested this item :white_check_mark: successfully on 38f90688f6a584b7ad2f86f7209da09ac8ac87da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35367">issues.joomla.org/tracker/joomla-cms/35367</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35367">issues.joomla.org/tracker/joomla-cms/35367</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
