### PR TITLE
[4.4] Mfa::getConfigurationInterface throws error if called from other component

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #43812.

### Summary of Changes
Fix syntax error throws error.

### Testing Instructions
Code review

or 

follow instructions #43812

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9db2a10d4568e4012e465fea5c6a262a6b19b580<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43818">issues.joomla.org/tracker/joomla-cms/43818</a>.</sub>

**Comment by OctavianC** [comment]
I have tested this item :white_check_mark: successfully on 9db2a10d4568e4012e465fea5c6a262a6b19b580<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43818">issues.joomla.org/tracker/joomla-cms/43818</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43818">issues.joomla.org/tracker/joomla-cms/43818</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
