### PR TITLE
Update Codemirror to 5.1

### PR DESCRIPTION
**Pull request by C-Lodder**
Changelog for Codemirror 5.1 can be found here:

https://github.com/codemirror/CodeMirror/compare/5.0.0...5.1.0

### CODE REVIEW

**Comment by infograf768** [comment]
Not sure we put into joomla these index.hrml files

**Comment by C-Lodder** [comment]
@infograf768 - I've removed the HTML files but can't yet commit as Github servers appear to be down. Thanks for pointing this out though

**Comment by okonomiyaki3000** [comment]
@C-Lodder It looks like maybe you just took the CodeMirror distro and dropped it in. That's not the correct way to update CodeMirror for Joomla.

**Comment by wilsonge** [comment]
Closing in favour of https://github.com/joomla/joomla-cms/pull/6686 

Just for my information as much as anyone elses why isn't that correct - so I'm aware for the future :)

**Pull request closed without merging**
