### PR TITLE
Sync changes to hathor override for the com_joomlaupdate default view

### PR DESCRIPTION
**Pull request by zero-24**
This PR Sync the changes to hathor override for the com_joomlaupdate default view
### How to test
- Install 3.3.6
- Install patchtester
- apply patch
- switch to the testing update server
- access com_joomlaupdate
- see the update
- see that we now also have the `You are connected on ...` message
- switch to "Write with FTP"
- and see that the password field now is ******

Thanks.

### CODE REVIEW

**Comment by brianteeman** [comment]
@test works for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5884">issues.joomla.org/joomla-cms/5884</a>.</sub>

**Comment by waader** [comment]
@test works!

**Comment by brianteeman** [comment]
Has two tests - setting to RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5884">issues.joomla.org/joomla-cms/5884</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request merged**
