### PR TITLE
[3.10] s/overwritting/overwriting

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/overwritting/overwriting

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 582ff19889058110d64439f9e7216575536e758d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35859">issues.joomla.org/tracker/joomla-cms/35859</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 582ff19889058110d64439f9e7216575536e758d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35859">issues.joomla.org/tracker/joomla-cms/35859</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35859">issues.joomla.org/tracker/joomla-cms/35859</a>.</sub>

**Comment by zero-24** [comment]
Merging now thanks

**Pull request merged**
