### PR TITLE
Regression: Messages paragraph spacing

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR partly revert the changes made in PR https://github.com/joomla/joomla-cms/pull/9181

Unfortunately we had some side effect after that PR: When using messages with several "p" tags the line spacing has also lost. Two of those examples are the Stats notification and the Post install messages as show in the image below.
image

This PR, besides reverting the "p" tag spacing, also changes the message container from a "p" tag to a "div" tag. This will also allow to had block level HTML elements inside the message ("p", "ul", "ol" etc).

After applying the patch you will see all message as before and this "special" messages with the correct spacing between paragraph as one can see in the image below.

image
#### Testing Instructions
1. Use latest staging.
2. Enable stats plugin and reset the unique id, so the message appears.
3. Go to control panel and check the paragraph spacing.
4. Apply this PR and clean browser cache (Ctrl+F5)
5. Repeat step 3. You will see the message is now with the correct spacing between paragraphs.
6. Check other info, warning, sucess and error messages in the frontend and in the backend.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7715371f31032e666c7664a66cdc94b0543e62f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9222">issues.joomla.org/joomla-cms/9222</a>.</sub>

**Comment by brianteeman** [comment]
When testing dont forget that you must be testing on current staging AND that you clear you browser cache after applying the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9222">issues.joomla.org/joomla-cms/9222</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7715371f31032e666c7664a66cdc94b0543e62f3<br /><br />Tested with success.

I had to clear browser cache also before the patch in order to be able to reproduce the error.

So clear browser cache at test start and then again after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9222">issues.joomla.org/joomla-cms/9222</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9222">issues.joomla.org/joomla-cms/9222</a>.</sub>

**Pull request merged**
