### PR TITLE
[4.0] Remove behavior.tabstate

### PR DESCRIPTION
**Pull request by brianteeman**
As confirmed https://github.com/joomla/joomla-cms/issues/25359#issuecomment-506873865 this line does nothing as the files have been removed

It hasn't been marked as deprecated in Joomla 3 - should it be https://github.com/joomla/joomla-cms/issues/25359#issuecomment-507550889

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 74ed964ac049b24b5138449d45cf401c7d13ff93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25502">issues.joomla.org/tracker/joomla-cms/25502</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 74ed964ac049b24b5138449d45cf401c7d13ff93<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25502">issues.joomla.org/tracker/joomla-cms/25502</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25502">issues.joomla.org/tracker/joomla-cms/25502</a>.</sub>

**Comment by Quy** [comment]
@brianteeman Please fix conflicts.

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by wilsonge** [comment]
It should be deprecated yup

**Comment by brianteeman** [comment]
So if I mark it as deprecated in staging will this be merged ?

**Comment by wilsonge** [comment]
Do it to 3.10-dev but yes

**Comment by brianteeman** [comment]
@wilsonge fone - see #27067

**Comment by SharkyKZ** [comment]
Shouldn't the method be removed?

**Comment by wilsonge** [comment]
@brianteeman deprecation notice has been merged through so can we just remove the method from this PR please

**Comment by brianteeman** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Sorry my message was ambiguous. I meant remove the function outright. If this is all the uses and it's deprecated remove the empty function from the behaviour.php file

**Comment by brianteeman** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks - got there in the end

**Pull request merged**
