### PR TITLE
[5.1] Fix TinyMCE media button, frontend edit

### LINKED ISSUE #43344: Media Manager is wrongly initialised by TinyMCE when accessed from a front-end submenu item
### Steps to reproduce the issue
Edit an article in a submenu, e.g. `menu/article`. Try to access "media" in "CMS Content" using TinyMCE.

### Expected result
The media manager starts.

### Actual result
The media manager window loads `/menu/index.php?option=com_media&view=media&tmpl=component&e_name=jform_articletext&asset=675&mediatypes=0,1,2,3&author=36` and displays "File not found. "

### System information (as much as possible)
Joomla 5.1.0 on Nginx 1.22.1, PHP 8.2.18.

### Additional comments
Patchable by adding a "/" before the URL at https://github.com/joomla/joomla-cms/blob/5.1-dev/plugins/editors-xtd/image/src/Extension/Image.php#L187. I can make an MR but I am not familiar with Joomla's internal. It was working fine on 4.4, not sure what caused the issue.

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43344 .

### Summary of Changes

Fix the Media button for frontend, in submenu.

### Testing Instructions
Please follow https://github.com/joomla/joomla-cms/issues/43344

### Actual result BEFORE applying this Pull Request
Broken

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 30936e09f2aed9ce48ce932879e54c3508134371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43376">issues.joomla.org/tracker/joomla-cms/43376</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 30936e09f2aed9ce48ce932879e54c3508134371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43376">issues.joomla.org/tracker/joomla-cms/43376</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43376">issues.joomla.org/tracker/joomla-cms/43376</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and for testing @brianteeman @carlitorweb

**Comment by brianteeman** [comment]
Please do not comment on closed issues or pull requests. Very few people will see it.

**Pull request merged**
