### PR TITLE
[4.0] Fix broken preset menu import

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #18684 #19904 #22758 .

### Summary of Changes
This problem is a bit complicated because there are two bugs, which are overlaying.
First: When a non component menu entry will be imported by the preset, the component_id is missing (fixed here: https://github.com/joomla/joomla-cms/pull/22852/files#diff-1b5557519e9638a5bde91cf3432456dfR490)
Second: if the menu saving failed for new menu items, the model still tries to publish non existing items (without an id) and throws another error (fixed here; https://github.com/joomla/joomla-cms/pull/22852/files#diff-8987d50fd63f0f6c70155058af33e7abR904).

### Testing Instructions
Create a backen menu and choose a preset.

### Expected result
Preset is imported

### Actual result
Preset import fails

See #22853 for the follow up bug (not related to this fixes)

### CODE REVIEW

**Comment by infograf768** [comment]
Preset is created after this patch. Only the direct links do work. Items which use collapse don't.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b0a57f2f6b53ae6e11d6c50cdc1222792883cb82<br /><br />Thank you, @bembelimen, just what I needed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22852">issues.joomla.org/tracker/joomla-cms/22852</a>.</sub>

**Comment by Quy** [comment]
This PR is for v4 yet #19904 pertains to v3. Will a separate PR be created for it?

**Comment by bembelimen** [comment]
@Quy I did not tackle this problem (yet) in this PR. Could you please check if this problem is also in J! 4? Then I'll update this PR and we can convert it to J! 3.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f00d6ee7adc0f183babb23fb5f040a84ca183895<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22852">issues.joomla.org/tracker/joomla-cms/22852</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22852">issues.joomla.org/tracker/joomla-cms/22852</a>.</sub>

**Comment by laoneo** [comment]
@bembelimen do you change this pr, or do you create a new one for J3?

**Comment by bembelimen** [comment]
For j3 is a new PR needed. This is fine as it is.

**Comment by laoneo** [comment]
Ok, thanks

**Pull request merged**
