### PR TITLE
[category modal field] Adds Create Category button and other improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
### Summary of Changes

This PR is the sequence of https://github.com/joomla/joomla-cms/pull/11830 but for now for categories modal.

For list of changes see https://github.com/joomla/joomla-cms/pull/11830 (same changes, but for categories now).

Similiar PR: 
- Article: https://github.com/joomla/joomla-cms/pull/11830
- Category: https://github.com/joomla/joomla-cms/pull/11857 (this one)
- Contact: https://github.com/joomla/joomla-cms/pull/11858
- Newsfeed: https://github.com/joomla/joomla-cms/pull/11862
### Animated Gif (click to view in full screen)

modal-category
### Testing Instructions
- Use latest staging
- Apply patch https://github.com/joomla/joomla-cms/pull/11830 and then this patch
- In a multilanguage install edit a category and try the modal button in the associations tab (as animated gif)
- Test all the "Edit", "Create", "Select" and "Clear" buttons.
- Code review to check all is ok.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
(someone has a new toy)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11857">issues.joomla.org/joomla-cms/11857</a>.</sub>

**Comment by izharaazmi** [comment]
@andrepereiradasilva Thanks! You saved my time that I was not able to put any sooner for my another PR. 👍

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2b8675b03fa7c9120fbd69f0a714d0e858011104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11857">issues.joomla.org/joomla-cms/11857</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 can you test this one so all of this PR be RTC, is test ok?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2b8675b03fa7c9120fbd69f0a714d0e858011104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11857">issues.joomla.org/joomla-cms/11857</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11857">issues.joomla.org/joomla-cms/11857</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@wilsonge @rdeutz since this is RTC can you merge it to 3.7.x branch.
i ask this because 3.7.x branch added this category modal in more places and i can only do this changes with this one merged.

**Comment by brianteeman** [comment]
@andrepereiradasilva the milestone was already set to 3.7

**Comment by andrepereiradasilva** [comment]
yeah i know thanks :+1:
just asking to be merged when possible, so i can proceed with the final PR (3.7.x branch) for this sequence of modals PR :smile: 

but will wait, of course

**Comment by brianteeman** [comment]
@andrepereiradasilva I've been pushing for 3.7 RTC issues to be merged and quite a few were merged overnight

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/28bd41da54fe66287bb4673b41e71b7a56fa334e

**Comment by andrepereiradasilva** [comment]
thanks @wilsonge !

**Pull request closed without merging**
