### PR TITLE
Fix double border on toolbar

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/41571 (Partial).

### Summary of Changes
Fixes the save button toolbar double border when editing and also fixes an undefined variable in the tabs element too that invisible but still was a technical bug. `bg-color` was a bad copy paste from quickicons (where it was correct specifically ther) and should have been `body-bg`

For the toolbar I’ve been consistent with the original dark mode approach and removed the background just hiding the extra border. But if this causes any unexpected issues I’ll revert to using body-bg there too.

### Testing Instructions
Check images from original issue specifically related to the toolbar icon. Should be the same as the Joomla 4.x layout after patch applied

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
:)

image

**Comment by wilsonge** [comment]
OK I give up. I guess I didn't hit compile after the last time I changed it. Should be fixed.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 725210d28817910b151da51c0b60a63adeaed638<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41615">issues.joomla.org/tracker/joomla-cms/41615</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3951f0931d9b2574b881004f74ce3a08ee257f83<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41615">issues.joomla.org/tracker/joomla-cms/41615</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41615">issues.joomla.org/tracker/joomla-cms/41615</a>.</sub>

**Pull request merged**
