### PR TITLE
Fix 0 value in range field

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #24938 .

### Summary of Changes

Fixes 0 value usage in range field.

### Testing Instructions

Add range field with default value 0 to any form:

```
<field 
	name="testrange" 
	type="range" 
	label="Test Range" 
	description="Test range desc" 
	min="-10" 
	max="10"
	step="0.1" 
	class="" 
	default="0"
/>
```
View the form. Look at the field.

### Expected result

Slider is at 0 value (centered).

### Actual result

Slider is at -10 value (left).

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fcc96acc2c655f2515f20cef3128caae0b19c1be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24939">issues.joomla.org/tracker/joomla-cms/24939</a>.</sub>

**Comment by ghost** [comment]
@thednp please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by thednp** [comment]
@franz-wohlkoenig I tested the change directly into the code, it fixes the issue.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fcc96acc2c655f2515f20cef3128caae0b19c1be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24939">issues.joomla.org/tracker/joomla-cms/24939</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24939">issues.joomla.org/tracker/joomla-cms/24939</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24939">issues.joomla.org/tracker/joomla-cms/24939</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
