### PR TITLE
[4.0] bootstrap.popover

### PR DESCRIPTION
**Pull request by brianteeman**
Remove this behavior on pages where it will never be used ie there is nothing with a class of `.haspopup`

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4c9cbfd028a30e0ade92af531fab1ef69b14ec1d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25521">issues.joomla.org/tracker/joomla-cms/25521</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 82e0a39089b32e85c8d3b3c4eca4f38fccdba989<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25521">issues.joomla.org/tracker/joomla-cms/25521</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25521">issues.joomla.org/tracker/joomla-cms/25521</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
