### PR TITLE
[4.0] Removing base tag from frontend

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #9010.

### Summary of Changes
This removes the base tag from the frontend. The idea of the base tag is to define a base for relative URLs. Consider you have the site http://www.example.com/this/is/index.php/with/more/content and all requests should go to the folder http://www.example.com/this/is/, you would set the base tag to exactly that URL. However, we are setting that base tag always to the current URL, which simply is wrong. Even worse, we aren't doing it correctly, because we are forgetting the query part. So we are not setting it to a special path, but are just using the current URL. Now guess what the default value is, when that base tag is NOT set at all. The answer is not "42", but: The current URL.

A quick check shows that neither Wordpress nor Drupal or Typo3 seem to have a base tag in their default output. We are just oh-so-special... Sorry...

### Testing Instructions
Apply this change and then check if everything on your site still works as expected. 

This would be a fix for an issue that is over 3 years old and that has been discussed several times in the Joomla project... Would be nice to finally solve that.

### CODE REVIEW

**Comment by ghost** [comment]
@Spudley @izharaazmi please test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by brianteeman** [comment]
Does this need to be removed as well?

https://github.com/joomla/joomla-cms/blob/6caaceeec8cbf19bcee8635c2e9c318052ce3804/libraries/src/Document/Renderer/Html/MetasRenderer.php#L71-L77

**Comment by Hackwar** [comment]
@brianteeman I thought about this. I opted for keeping that feature generally available to whoever wants to use it, but just to not use it in the SiteApplication. That makes the (small) B/C break smaller.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 7d9b0b3162c4a3d966abbfe5e4576d44ad747106<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25077">issues.joomla.org/tracker/joomla-cms/25077</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7d9b0b3162c4a3d966abbfe5e4576d44ad747106<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25077">issues.joomla.org/tracker/joomla-cms/25077</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25077">issues.joomla.org/tracker/joomla-cms/25077</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by HLeithner** [comment]
This needs to be documented in the migration guide.

**Comment by brianteeman** [comment]
@HLeithner please add the documentation required label

**Comment by HLeithner** [comment]
thx franz

**Pull request merged**
