### PR TITLE
Cookies Review

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR does a cookies review across the cms.
1. Use epoch + 1 to delete the cookie. I think it's not necessary time() - xxxx. Epoch + 1 should be enough. Also we can have problems with timezones if not putting time() less a full day.
2. Use always '' (empty) when deleting a cookie.
3. Use the Api when deleting the session cookie.
4. Always use HTTPOnly for cookies so they can't be accessed through JS.
5. If HTTPS is forced in the client (Site/Admin) always use only secure cookies
6. Don't use `app->isSSLConnection()` for checking if the cookie should be secure. We could have problem setting a secure cookie in a dual HTTP/HTTPS site. Use the new `$app->isHttpsForced()` instead.
7. Don't use a new language cookie if the cookie language is defined in the language filter plugin to be only session. Use the session instead (we already have a cookie...).

And minor code and code style improvements.
### Testing Instructions

Since this impacts the users/admin sessions the tests must be made with special attention.
1. First do a code review.
2. Apply this patch in latest 3.7.x branch
3. Watch the cookies that are created in the developer console (Resources -> Cookies) in the following processes:
   - site login/logout process
   - backend login/logout process
   - the remember me process in site authentication
   - in a multilanguage site, the remember of the user language (aka the language cookie)
### Observations

I checked all the cookies in joomla core (i think i'm not missing none), one i don't know what it does (banner tracks), but i also updated that one.

### CODE REVIEW

**Comment by wilsonge** [comment]
This is actually very important. Adding release blocker tag

**Comment by dgt41** [comment]
@andrepereiradasilva can you fix the conflicts here?

**Comment by andrepereiradasilva** [comment]
@dgt41 done

**Comment by qrem** [comment]
is it solved now, or still needs testing?

**Comment by wilsonge** [comment]
This needs testing for sure

**Comment by qrem** [comment]
What we should test?

**Comment by wilsonge** [comment]
I have fixed conflicts

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on b0da24581cf2d8df03aa0170a360c617db181a98<br /><br />Tested both the front end and backend, works great.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12306">issues.joomla.org/tracker/joomla-cms/12306</a>.</sub>

**Comment by JoshuaLewis** [comment]
@wilsonge Are you willing to test this PR now that fixes are made?

**Comment by kalemanzi** [comment]
Hi. 
I just tried to test this, but after I removed all patches and applied patch 12306 it logged me out from administrator and now when I try to login it gives me:

"The most recent request was denied because it contained an invalid security token. Please refresh the page and try again."

No matter if I refresh the page, I still get this. My current setup is Nginx on Mac with php 7. This was in FF. I also tried it in Chrome to be sure, getting the same error. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12306">issues.joomla.org/tracker/joomla-cms/12306</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b0da24581cf2d8df03aa0170a360c617db181a98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12306">issues.joomla.org/tracker/joomla-cms/12306</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by richard67** [comment]
I tested frontend and backend and force ssl for admin only and for the entire site, and shared sessions no and yes, and language filter cookie for session and for year. Works like a charm, this PR does not introduce new bugs but saves 1 cookie in case if language filter cookie is session only, and the language filter still remembers the previously selected site language as before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12306">issues.joomla.org/tracker/joomla-cms/12306</a>.</sub>

**Comment by richard67** [comment]
@kalemanzi This PR requires to be tested on latest staging + this patch applied (which can be done with patchtester latest stable release after having installed a clean staging with multilingual option). If you applied the patch on a 3.6.5 or something else not being latest staging, it can have caused your problems because other patches might have been missing. Can you check and if possible test again with latest staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12306">issues.joomla.org/tracker/joomla-cms/12306</a>.</sub>

**Comment by mino182** [comment]
Hi, this cookies changes in plugins/system/languagefilter/languagefilter.php cause problem with "com_tags" in single tag view, if tags option "language filter" is set to "Current".

In my case in tag view I have only EN articles, no matter what language I set in frontend...

If I replace these lines with code from j 3.7.2, there is no problem.

Thanks.

**Comment by ghost** [comment]
@mino182 can you please open a Issue?

**Comment by mino182** [comment]
Ok

**Comment by infograf768** [comment]
Regression.
https://github.com/joomla/joomla-cms/issues/17053

@andrepereiradasilva

**Pull request merged**
