### PR TITLE
[4.0] fixed js errors in editor

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue - JS errors in console when size of window is reduced, as pointed out in #24547 .
**Only JS errors are removed in this PR, the Editor is still unresponsive.**

### Summary of Changes
Corrected the functions in ES6 files

### Expected result
No errors in console

### Actual result
Console errors

Run node install before testing

### CODE REVIEW

**Comment by Puneet-Jain-18** [comment]
I have tested this item :white_check_mark: successfully on 8f5b605cabcdecc9ebee4557775acaa08296d95c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24548">issues.joomla.org/tracker/joomla-cms/24548</a>.</sub>

**Comment by bahl24** [comment]
@infograf768 kindly test

**Comment by euismod2336** [comment]
I have tested this item :white_check_mark: successfully on 8f5b605cabcdecc9ebee4557775acaa08296d95c<br /><br />works as advertised; no more errors in console<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24548">issues.joomla.org/tracker/joomla-cms/24548</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Works for me too. Thanks!

**Pull request merged**
