### PR TITLE
[4.0] JText namespace

### PR DESCRIPTION
**Pull request by brianteeman**
Fixed some instances of JText usage introduced from merge updates

codereview

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on ad50af35a3ab82d8b87b8ad4a3dfe6aa7edfa076<br /><br />Tested successfully in Beta6-dev of 26 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31494">issues.joomla.org/tracker/joomla-cms/31494</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ad50af35a3ab82d8b87b8ad4a3dfe6aa7edfa076<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31494">issues.joomla.org/tracker/joomla-cms/31494</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
