### PR TITLE
[4.0] Fix frontend module editing

### PR DESCRIPTION
**Pull request by dgrammatiko**
Issue: https://github.com/joomla/joomla-cms/issues/20389

### Summary of Changes
Standard forms dont require inline js for validation, they only require a class `form-validate`!

### Testing Instructions

Apply patch and try to edit a module in the frontend. Save, Save and close and Close buttons should behave normally. Also check that editing the article also works

BTW, I've applied the same code to the rest views of com_config and also com_content

### Expected result

screen shot 2018-05-14 at 20 37 53

### Documentation Changes Required
At some point we really need to document this submitbutton...

@wilsonge

### CODE REVIEW

**Comment by Quy** [comment]
This one #20389 ?

**Comment by dgrammatiko** [comment]
@Quy thanks that's the one

**Comment by carlitorweb** [comment]
I tested this successful, just waiting for the drone fix

**Comment by franz-wohlkoenig** [comment]
@carlitorweb please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/20398)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by infograf768** [comment]
Successful here too

**Comment by laoneo** [comment]
The drone tests are because of some other issues.

**Review by laoneo — APPROVED** [review]

**Pull request merged**
