### PR TITLE
Removing duplicate code in com_search

### PR DESCRIPTION
**Pull request by Hackwar**
The whole check for mb_string is unnecessary. We've abstracted exactly that into the JString class, so all of that is unnecessary and should be removed. Hmm, testing instructions... Use the normal com_search with some multibyte strings and see that nothing changed, I guess...

### CODE REVIEW

**Comment by 810** [comment]
maybe you can use already the Joomla\String\StringHelper

**Comment by Hackwar** [comment]
That would be something that we can do in 4.0, but for now I would simply remove the unnecessary code. I've been playing around with the idea of merging com_search and com_finder and been doing some work on that and most likely all of that will get rewritten for 4.0. All of that of course without any guarantees that I get enough time to work on this and get it done in time.

**Comment by franz-wohlkoenig** [comment]
@Hackwar can you give Examples of Multibyte Strings to test?

**Comment by roland-d** [comment]
@franz-wohlkoenig Multi-byte strings are letters with accents like ö and ï.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12481">issues.joomla.org/tracker/joomla-cms/12481</a>.</sub>

**Comment by ghost** [comment]
@Hackwar can you please resolve conflicting Files for test?

**Comment by Hackwar** [comment]
since I'm working towards dropping com_search, I'm going to close this one to not waste any more time.

**Pull request closed without merging**
