### PR TITLE
Clean up old code in cache.php file

### PR DESCRIPTION
**Pull request by csthomas**
## Summary of Changes
- Remove old php4 style to catch exception which currently is useless. 
- Add shorten version of ternary operators.
- In `lock` and `unlock` methods direct call to handler.
### Testing Instructions

Code review or real test:
1. Get latest staging Joomla.
2. Enable cache and set timeout to low value, for ex. 1 minute.
3. Go to frontend and check if pages work as before.
4. Go to backend and some cache items should be visible, clear only expired cache, clear all cache.

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by franz-wohlkoenig** [comment]
"Error-Reporting" set on "Maximum" got in Module "Main Menu" `Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'JCache' does not have a method 'contains' in __/Joomla/libraries/joomla/cache/controller.php on line 69 `

**Comment by mbabker** [comment]
If you're using patch tester then that'd be expected because of how the file is updated.  You'll either need to apply the patch through git or wait for the branch this pull request comes from to be synchronized with the current staging branch.

**Comment by franz-wohlkoenig** [comment]
@mbabker used Patchtester, got a "SHA"-Error at marking Test unsuccessfully.

**Comment by csthomas** [comment]
I have updated branch. Please try again to test.

**Comment by csthomas** [comment]
After I clicked on "Update branch" I saw that the last changes use the old style. 
Therefore I added the last commit. Test ready.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 0fc183208869e9fe36326a29937bfc8a1991cd16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12183">issues.joomla.org/tracker/joomla-cms/12183</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 0fc183208869e9fe36326a29937bfc8a1991cd16<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12183">issues.joomla.org/tracker/joomla-cms/12183</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12183">issues.joomla.org/tracker/joomla-cms/12183</a>.</sub>

**Pull request merged**
