### PR TITLE
a11y icons site templates

### PR DESCRIPTION
**Pull request by brianteeman**
When reading our default markup for rendering icons, assisistive technology may have the following problems.

The assistive technology will not find any content to read out to a user
The assistive technology will read the unicode equivalent, which does not match up to what the icon means in context, or worse is just plain confusing. In our use case it is always plain wrong. For example the unicode character used to display the trashed icon is \4c which is equal to L

When an icon is not an interactive element the simplest way to provide a text alternative is to use the aria-hidden="true" attribute on the icon and to include the text with an additional element, such as a < span>, with appropriate CSS to visually hide the element while keeping it accessible to assistive technologies.

In this case we have the text and it is displayed so we just need to add the aria-hidden to prevent the icon being "read aloud"

This PR should address all the remaining icons in the templates folder where we do have text

### CODE REVIEW

**Comment by brianteeman** [comment]
No idea why this failed appveyor test. looks like an issue with appveyor not this pr

**Review by dgrammatiko — APPROVED** [review]

**Comment by photodude** [comment]
@mbabker looks like appveyor needs to be rerun here. (looks like the SQLSVR  module has an intermitant download connection failure)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 15ada2cc1a3225eca409fe29b04d209430315c92<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14704">issues.joomla.org/tracker/joomla-cms/14704</a>.</sub>

**Comment by tonypartridge** [comment]
@mbabker can you please re-run drone?

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 15ada2cc1a3225eca409fe29b04d209430315c92<br /><br />Code Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14704">issues.joomla.org/tracker/joomla-cms/14704</a>.</sub>

**Comment by zero-24** [comment]
Drone did rerun and is happy now

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
