### PR TITLE
Regression: Correct Modules ordering on drag and drop

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
##### Description

Modules should be ordered by their order in the position, so when we order using drag and drop we should get only enabled the modules in the same position.

That is not happening right now, the enabled modules on drag are the ones with the same "ordering" indepedent of the position.
###### Before PR

image
###### After PR

image
##### How to test
1. Install latest staging
2. Create some modules in the same position
3. Try to order them within the position in the list view with drag and drop
4. Apply this PR
5. Try to order them now within the position in the list view with drag and drop

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 95e56b4d13f6538d4aa764d5ca990aba58f8ed35<br /><br />I can confirm the bug, and I can confirm that this PR solves it.

@andrepereiradasilva Since this somewhen in past has worked as far as I remember, it very likely is a regression. Maybe you should mark this PR as such, e.g. by starting the title with [Regression], so maintainers can see quickly that is has to go into 3.5.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I think this is not a regression, if i'm correct is long standing bug (aug 2012) https://github.com/joomla/joomla-cms/blob/e11117d37241f4683c6cc13d22017ded30a60d02/administrator/components/com_modules/views/modules/tmpl/default.php

**Comment by richard67** [comment]
Wow ... it seems people not use the drag and drop sorting so often (like me), or they accepted the bug as desired behavior ... otherwise the issue tracker should be full of it, or not? :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by andrepereiradasilva** [comment]
maybe there was a javascript change between that changed the drag and drop behaviour.

**Comment by andrepereiradasilva** [comment]
Found it! https://github.com/joomla/joomla-cms/commit/06f0d960b8536e776a6ebc9a51270bbce8c2cbb1

@dgt41 can you check?

**Comment by dgt41** [comment]
@andrepereiradasilva what happens if you revert it back to position? https://github.com/joomla/joomla-cms/commit/06f0d960b8536e776a6ebc9a51270bbce8c2cbb1#diff-bbb8ae0595d2d0e10b67b23fd3d1e670R96

**Comment by andrepereiradasilva** [comment]
@dgt41 if only "position" the modules with "None" position caan be ordered anywhere.
Is this how it's supossed to work?

**Comment by dgt41** [comment]
Ahh, yes that's why I changed it in the first place

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6d80a0f88d5a3518854f1c2d5c054af27c4e9d61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6d80a0f88d5a3518854f1c2d5c054af27c4e9d61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 @richard67 thanks for testing.

**Comment by richard67** [comment]
@wilsonge Somehow the issue tracker shows this as "new" in the list now, and not as closed. Am I just to impatient? Sorry if so.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Comment by wilsonge** [comment]
I don't know. I just use the github GUI :/

@mbabker ?

**Comment by richard67** [comment]
Ah, now it is ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9120">issues.joomla.org/joomla-cms/9120</a>.</sub>

**Pull request merged**
