### PR TITLE
Remove role="button" from installer. Ref #23737

### PR DESCRIPTION
**Pull request by wilsonge**
Removes a redundant role attribute. These are links and are not acting like buttons

To test ensure the installer keeps functioning

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 51ecd73f1199769acf2267547eff29f7329cb1a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24620">issues.joomla.org/tracker/joomla-cms/24620</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 51ecd73f1199769acf2267547eff29f7329cb1a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24620">issues.joomla.org/tracker/joomla-cms/24620</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by Quy** [comment]
Remove `title` attributes too? They don't add additional information to the buttons. If yes, I will create a PR for it.

**Comment by zwiastunsw** [comment]
@Quy : yes! It's a redundant attribute.

**Comment by wilsonge** [comment]
Thanks!

**Comment by hardik-codes** [comment]
> Remove `title` attributes too? They don't add additional information to the buttons. If yes, I will create a PR for it.

@Quy may I do a PR for you?

**Comment by Quy** [comment]
@hardik-codes Go for it. Thanks.

**Pull request merged**
