### PR TITLE
[5.0] Select New Module

### PR DESCRIPTION
**Pull request by brianteeman**
#41920 broke the ability to search for a module.

Changed the js to search for the correct new class as the previous js searched for a class removed in #41920
cc @wilsonge

### CODE REVIEW

**Comment by wilsonge** [comment]
About to head to bed but I think switching https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/com_modules/js/admin-module-search.es6.js#L67 this line from `.card-body` to `.new-module-caption` makes things work. Only a did a very quick test locally though

**Comment by brianteeman** [comment]
ah ok then - will go down the js route to fix it

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8c41ea1cc7deb3cb671b19d724c86b9dccba9809<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41943">issues.joomla.org/tracker/joomla-cms/41943</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c41ea1cc7deb3cb671b19d724c86b9dccba9809<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41943">issues.joomla.org/tracker/joomla-cms/41943</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41943">issues.joomla.org/tracker/joomla-cms/41943</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
