### PR TITLE
[4.0]com_csp filters

### PR DESCRIPTION
**Pull request by brianteeman**
Re-order the filters so that they are in the same order as the columns

Rename Client Ascending to Location Ascending etc so that it matches the column header and is consistent with similar fields elsewhere

To test you will need to enable the "Detect" mode in the com_csp options and browse a few pages in the admin to gather some data

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c99618adaa78aa82f2e125d70ec5f1bdd093d5bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26502">issues.joomla.org/tracker/joomla-cms/26502</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c99618adaa78aa82f2e125d70ec5f1bdd093d5bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26502">issues.joomla.org/tracker/joomla-cms/26502</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26502">issues.joomla.org/tracker/joomla-cms/26502</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks @brianteeman and testers 👍

**Pull request merged**
