### PR TITLE
Config Modules - changed title: Module: Options

### PR DESCRIPTION
**Pull request by pe7er**
The **Title** of the configuration view **Module: Options** is **different** (singular) from the **Modules** title in the list of Components on the Global Configuration page.

configure-components-plural-single-modules-before-both
#### Before the PR:

Backend: System > Global Configuration > under COMPONENT (left menu)
Click on Configure Menu Title: **Modules** (= plural).
The Title " **Module**: Options" is singular.

configure-components-plural-single-modules-before
#### After the PR:

Backend: System > Global Configuration > under COMPONENT (left menu)
Click on Configure Menu Title: **Modules**.
The Title " **Modules**: Options" is plural too.

configure-components-plural-single-modules-after

### CODE REVIEW

**Review by jeckodevelopment — APPROVED** [review]

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on b243898111d9523b576314ffccffbd61ea315ded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12099">issues.joomla.org/joomla-cms/12099</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on b243898111d9523b576314ffccffbd61ea315ded<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12099">issues.joomla.org/joomla-cms/12099</a>.</sub>

**Comment by brianteeman** [comment]
This is not correct. It is not the option for modules plural it is the
option for the component singular

**Comment by brianteeman** [comment]
I am going to set this and the related PR to needs review so they are not merged until we make a decision on them all as I am not convinced it is correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12099">issues.joomla.org/joomla-cms/12099</a>.</sub>

**Comment by korneliusz401** [comment]
I have tested this item :white_check_mark: successfully on adebf4dc47dec011ca34ae92971a9e897e948b0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12099">issues.joomla.org/tracker/joomla-cms/12099</a>.</sub>

**Comment by Heggi93** [comment]
I have tested this item :white_check_mark: successfully on adebf4dc47dec011ca34ae92971a9e897e948b0a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12099">issues.joomla.org/tracker/joomla-cms/12099</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Please remove RTC for now for the reasons I stated above. This relates to multiple open PRs that are awaiting a decision.

**Pull request closed without merging**
