### PR TITLE
[4.0] Update files and folder removal on updates in script.php to latest changes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Keep files and folder deletion in script.php up to date with recent changes on the 4.0-dev branch.
- Add removal of the file and folder removed with PR #33437 to script.php .
- Add the changelog of tinymce to the file removal because we also don't include that in our packages, i.e. remove it on build.

With these changes, the files and folders deletion in script.php will be up to date with all what the tool I use for generating the lists generates right now with latest 3.10-dev and 4.10-dev branches.

To be tested and merged after PR #33437 has been merged. Will keep it in draft status until then.

### Testing Instructions

Code review:
- The 2 files added by this PR are 1. the one deleted with PR #33437 from the sources, and 2. the changelog of tinymce.
- The 1 folder added by this PR is the one deleted with PR #33437 from the sources.
- The files are added at the right place for alphabetical order to the `$files` array within the section after the `// 4.0 from Beta 7 to Beta 8` comment in script.php.
- The folder is added at the right place for reverse alphabetical order to the `$folders` array within the section after the `// 4.0 from Beta 7 to Beta 8` comment in script.php.
- There is no PHP syntax error (missing quotes, missing comma, whatever possible).

Alternatively do a real test with updating a current 4.0-dev or latest nightly to the update package or custom URL created by Drone for this PR and checking that the files are really removed by the update.

### Actual result BEFORE applying this Pull Request

The one files and the one folder removed with PR #33390 from the sources and the changelog of tinymce will not be deleted with a CMS update.

### Expected result AFTER applying this Pull Request

The one files and the one folder removed with PR #33390 from the sources and the changelog of tinymce will be deleted with a CMS update.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
its a bug if that changelog is being created

**Comment by richard67** [comment]
> its a bug if that changelog is being created

@brianteeman I don't understand. Do you mean it's a but if it's in the package? Then the bug has been solved, and so it comes that it is not in the package anymore. Or do you mean it is a bug that it is added to the list of files to be deleted here?

**Comment by brianteeman** [comment]
the contents of the media/vendor/tinymce folder are created by our build scripts. If there is a changelog in that folder then its a bug and we need to check the build scripts to make sure it is not added to media/vendor/tinymce

**Comment by richard67** [comment]
@brianteeman The files was in the folder with 4.0 Beta 7. The list in this PR here has been updated based on the difference between a newly build package locally on my current and clean 4.0-dev, and in that new build the file was not in and so it's added to the list here. So the bug was in Beta 7 and maybe earlier and has meanwhile been solved.

**Comment by richard67** [comment]
@brianteeman I think it was PR #32300 which fixed it, and that came after Beta 7, so that could explain it.

**Comment by richard67** [comment]
Ready for tests.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 2129ad9607e19a6c91ec801f7f0722de0392b7d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33646">issues.joomla.org/tracker/joomla-cms/33646</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
